include::./index.adoc[]

[[v62-3-0]]
=== The First of John, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v62-3-1]]

^<<v62-3-1,1>>^ See what sort of love the Father has given us, that we should be called children of God! And that is what we are. That is why the world does not know us, because it has not come to know him.

[[v62-3-2]]

^<<v62-3-2,2>>^ Beloved ones, we are now children of God, but it has not yet been made manifest what we will be. We do know that when he is made manifest we will be like him, because we will see him just as he is.

[[v62-3-3]]

^<<v62-3-3,3>>^ And everyone who has this hope in him purifies himself, just as that one is pure.

[[v62-3-4]]

^<<v62-3-4,4>>^ Everyone who practices sin is also practicing lawlessness, and sin is lawlessness.

[[v62-3-5]]

^<<v62-3-5,5>>^ You know, too, that he was made manifest to take away our sins, and there is no sin in him.

[[v62-3-6]]

^<<v62-3-6,6>>^ Everyone remaining in union with him does not practice sin; no one who practices sin has either seen him or come to know him.

[[v62-3-7]]

^<<v62-3-7,7>>^ Little children, let no one mislead you; the one who practices righteousness is righteous, just as that one is righteous.

[[v62-3-8]]

^<<v62-3-8,8>>^ The one who practices sin originates with the Devil, because the Devil has been sinning from the beginning.^&#42;1^ For this purpose the Son of God was made manifest, to break up^&#42;2^ the works of the Devil.

[NOTE]
====
. Or “from when he began.”
. Or “destroy.”
====

[[v62-3-9]]

^<<v62-3-9,9>>^ Everyone who has been born from God does not practice sin, for His seed^&#42;1^ remains in such one, and he cannot practice sin, for he has been born from God.

[NOTE]
====
. That is, seed capable of reproducing, or bearing fruit.
====

[[v62-3-10]]

^<<v62-3-10,10>>^ The children of God and the children of the Devil are evident by this fact: Whoever does not practice righteousness does not originate with God, nor does the one who does not love his brother.

[[v62-3-11]]

^<<v62-3-11,11>>^ For this is the message that you have heard from the beginning, that we should love one another;

[[v62-3-12]]

^<<v62-3-12,12>>^ not like Cain, who originated with the wicked one and slaughtered his brother. And for what reason did he slaughter him? Because his own works were wicked, but those of his brother were righteous.

[[v62-3-13]]

^<<v62-3-13,13>>^ Do not be surprised, brothers, that the world hates you.

[[v62-3-14]]

^<<v62-3-14,14>>^ We know that we have passed over from death to life, because we love the brothers. The one who does not love remains in death.

[[v62-3-15]]

^<<v62-3-15,15>>^ Everyone who hates his brother is a murderer,^&#42;1^ and you know that no murderer has everlasting life remaining in him.

[NOTE]
====
. Or “manslayer.”
====

[[v62-3-16]]

^<<v62-3-16,16>>^ By this we have come to know love, because that one surrendered his life^&#42;1^ for us, and we are under obligation to surrender our lives^&#42;2^ for our brothers.

[NOTE]
====
. Or “soul.”
. Or “souls.”
====

[[v62-3-17]]

^<<v62-3-17,17>>^ But whoever has the material possessions of this world and sees his brother in need and yet refuses to show him compassion, in what way does the love of God remain in him?

[[v62-3-18]]

^<<v62-3-18,18>>^ Little children, we should love, not in word or with the tongue, but in deed and truth.

[[v62-3-19]]

^<<v62-3-19,19>>^ By this we will know that we originate with the truth, and we will assure^&#42;1^ our hearts before him

[NOTE]
====
. Or “persuade; convince.”
====

[[v62-3-20]]

^<<v62-3-20,20>>^ regarding whatever our hearts may condemn us in, because God is greater than our hearts and knows all things.

[[v62-3-21]]

^<<v62-3-21,21>>^ Beloved ones, if our hearts do not condemn us, we have freeness of speech toward God;

[[v62-3-22]]

^<<v62-3-22,22>>^ and whatever we ask we receive from him, because we are observing his commandments and doing what is pleasing in his eyes.

[[v62-3-23]]

^<<v62-3-23,23>>^ Indeed, this is his commandment: that we have faith in the name of his Son Jesus Christ and love one another, just as he gave us a commandment.

[[v62-3-24]]

^<<v62-3-24,24>>^ Moreover, the one who observes his commandments remains in union with him, and he in union with such one. And by the spirit that he gave us, we know that he remains in union with us.

'''

xref:062-1-john/062-1-john-002.adoc#v62-2-0[&#60; Capítulo Anterior] | <<v62-3-0,Topo>> | xref:062-1-john/062-1-john-004.adoc#v62-4-0[Próximo Capítulo &#62;]