include::./index.adoc[]

[[v62-2-0]]
=== The First of John, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v62-2-1]]

^<<v62-2-1,1>>^ My little children, I am writing you these things so that you may not commit a sin. And yet, if anyone does commit a sin, we have a helper^&#42;1^ with the Father, Jesus Christ, a righteous one.

[NOTE]
====
. Or “an advocate.”
====

[[v62-2-2]]

^<<v62-2-2,2>>^ And he is a propitiatory sacrifice^&#42;1^ for our sins, yet not for ours only but also for the whole world’s.

[NOTE]
====
. Or “an atoning sacrifice; a means of appeasement.”
====

[[v62-2-3]]

^<<v62-2-3,3>>^ And by this we realize that we have come to know him, namely, if we continue observing his commandments.

[[v62-2-4]]

^<<v62-2-4,4>>^ The one who says, “I have come to know him,” and yet does not observe his commandments is a liar, and the truth is not in this person.

[[v62-2-5]]

^<<v62-2-5,5>>^ But whoever does observe his word, in this person the love of God has truly been made perfect. By this we know that we are in union with him.

[[v62-2-6]]

^<<v62-2-6,6>>^ The one who says he remains in union with him is himself under obligation to go on walking just as that one walked.

[[v62-2-7]]

^<<v62-2-7,7>>^ Beloved ones, I am writing you, not a new commandment, but an old commandment that you have had from the beginning. This old commandment is the word that you heard.

[[v62-2-8]]

^<<v62-2-8,8>>^ Again, I am writing you a new commandment, which is true in his case and in yours, because the darkness is passing away and the true light is already shining.

[[v62-2-9]]

^<<v62-2-9,9>>^ The one who says that he is in the light and yet hates his brother is still in the darkness.

[[v62-2-10]]

^<<v62-2-10,10>>^ The one who loves his brother remains in the light, and in him there is no cause for stumbling.

[[v62-2-11]]

^<<v62-2-11,11>>^ But the one who hates his brother is in the darkness and is walking in the darkness, and he does not know where he is going, because the darkness has blinded his eyes.

[[v62-2-12]]

^<<v62-2-12,12>>^ I am writing you, little children, because your sins have been forgiven you for the sake of his name.

[[v62-2-13]]

^<<v62-2-13,13>>^ I am writing you, fathers, because you have come to know him who is from the beginning. I am writing you, young men, because you have conquered the wicked one. I write you, young children, because you have come to know the Father.

[[v62-2-14]]

^<<v62-2-14,14>>^ I write you, fathers, because you have come to know him who is from the beginning. I write you, young men, because you are strong and the word of God remains in you and you have conquered the wicked one.

[[v62-2-15]]

^<<v62-2-15,15>>^ Do not love either the world or the things in the world. If anyone loves the world, the love of the Father is not in him;

[[v62-2-16]]

^<<v62-2-16,16>>^ because everything in the world—the desire of the flesh and the desire of the eyes and the showy display of one’s means of life^&#42;1^—does not originate with the Father, but originates with the world.

[NOTE]
====
. Or “the bragging about one’s possessions.”
====

[[v62-2-17]]

^<<v62-2-17,17>>^ Furthermore, the world is passing away and so is its desire, but the one who does the will of God remains forever.

[[v62-2-18]]

^<<v62-2-18,18>>^ Young children, it is the last hour, and just as you have heard that the antichrist is coming, even now many antichrists have appeared, from which fact we know that it is the last hour.

[[v62-2-19]]

^<<v62-2-19,19>>^ They went out from us, but they were not of our sort;^&#42;1^ for if they had been of our sort, they would have remained with us. But they went out so that it might be shown that not all are of our sort.

[NOTE]
====
. Or “they did not belong to us.”
====

[[v62-2-20]]

^<<v62-2-20,20>>^ And you have an anointing from the holy one, and all of you have knowledge.

[[v62-2-21]]

^<<v62-2-21,21>>^ I write you, not because you do not know the truth, but because you know it, and because no lie originates with the truth.

[[v62-2-22]]

^<<v62-2-22,22>>^ Who is the liar but the one who denies that Jesus is the Christ? This is the antichrist, the one who denies the Father and the Son.

[[v62-2-23]]

^<<v62-2-23,23>>^ Everyone who denies the Son does not have the Father either. But whoever acknowledges the Son has the Father also.

[[v62-2-24]]

^<<v62-2-24,24>>^ As for you, what you have heard from the beginning must remain in you. If what you have heard from the beginning remains in you, you will also remain in union with the Son and in union with the Father.

[[v62-2-25]]

^<<v62-2-25,25>>^ Furthermore, this is what he himself promised us—the life everlasting.

[[v62-2-26]]

^<<v62-2-26,26>>^ I write you these things about those who are trying to mislead you.

[[v62-2-27]]

^<<v62-2-27,27>>^ And as for you, the anointing that you received from him remains in you, and you do not need anyone to be teaching you; but the anointing from him is teaching you about all things and is true and is no lie. Just as it has taught you, remain in union with him.

[[v62-2-28]]

^<<v62-2-28,28>>^ So now, little children, remain in union with him, so that when he is made manifest we may have freeness of speech and not shrink away from him in shame at his presence.

[[v62-2-29]]

^<<v62-2-29,29>>^ If you know that he is righteous, you also know that everyone who practices righteousness has been born from him.

'''

xref:062-1-john/062-1-john-001.adoc#v62-1-0[&#60; Capítulo Anterior] | <<v62-2-0,Topo>> | xref:062-1-john/062-1-john-003.adoc#v62-3-0[Próximo Capítulo &#62;]