include::./index.adoc[]

[[v62-4-0]]
=== The First of John, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v62-4-1]]

^<<v62-4-1,1>>^ Beloved ones, do not believe every inspired statement,^&#42;1^ but test the inspired statements^&#42;2^ to see whether they originate with God, for many false prophets have gone out into the world.

[NOTE]
====
. Lit., “every spirit.”
. Lit., “the spirits.”
====

[[v62-4-2]]

^<<v62-4-2,2>>^ This is how you know that the inspired statement is from God: Every inspired statement that acknowledges Jesus Christ as having come in the flesh originates with God.

[[v62-4-3]]

^<<v62-4-3,3>>^ But every inspired statement that does not acknowledge Jesus does not originate with God. Furthermore, this is the antichrist’s inspired statement that you have heard was coming, and now it is already in the world.

[[v62-4-4]]

^<<v62-4-4,4>>^ You originate with God, little children, and you have conquered them, because the one who is in union with you is greater than the one who is in union with the world.

[[v62-4-5]]

^<<v62-4-5,5>>^ They originate with the world; that is why they speak what originates with the world and the world listens to them.

[[v62-4-6]]

^<<v62-4-6,6>>^ We originate with God. Whoever comes to know God listens to us; whoever does not originate with God does not listen to us. By this we distinguish the inspired statement of truth from the inspired statement of error.

[[v62-4-7]]

^<<v62-4-7,7>>^ Beloved ones, let us continue loving one another, because love is from God, and everyone who loves has been born from God and knows God.

[[v62-4-8]]

^<<v62-4-8,8>>^ Whoever does not love has not come to know God, because God is love.

[[v62-4-9]]

^<<v62-4-9,9>>^ By this the love of God was revealed in our case, that God sent his only-begotten Son into the world so that we might gain life through him.

[[v62-4-10]]

^<<v62-4-10,10>>^ The love is in this respect, not that we have loved God, but that he loved us and sent his Son as a propitiatory sacrifice^&#42;1^ for our sins.

[NOTE]
====
. Or “an atoning sacrifice; a means of appeasement.”
====

[[v62-4-11]]

^<<v62-4-11,11>>^ Beloved ones, if this is how God loved us, then we are also under obligation to love one another.

[[v62-4-12]]

^<<v62-4-12,12>>^ No one has seen God at any time. If we continue loving one another, God remains in us and his love is made perfect in us.

[[v62-4-13]]

^<<v62-4-13,13>>^ By this we know that we are remaining in union with him and he in union with us, because he has given his spirit to us.

[[v62-4-14]]

^<<v62-4-14,14>>^ In addition, we ourselves have seen and are bearing witness that the Father has sent his Son as savior of the world.

[[v62-4-15]]

^<<v62-4-15,15>>^ Whoever acknowledges that Jesus is God’s Son, God remains in union with such one and he in union with God.

[[v62-4-16]]

^<<v62-4-16,16>>^ And we have come to know and believe the love that God has for us.
God is love, and the one who remains in love remains in union with God and God remains in union with him.

[[v62-4-17]]

^<<v62-4-17,17>>^ In this way love has been made perfect in us, so that we may have freeness of speech^&#42;1^ in the day of judgment, because just as that one is, so are we ourselves in this world.

[NOTE]
====
. Or “have confidence.”
====

[[v62-4-18]]

^<<v62-4-18,18>>^ There is no fear in love, but perfect love casts^&#42;1^ fear out, because fear restrains us. Indeed, the one who is fearful has not been made perfect in love.

[NOTE]
====
. Or “drives.”
====

[[v62-4-19]]

^<<v62-4-19,19>>^ We love, because he first loved us.

[[v62-4-20]]

^<<v62-4-20,20>>^ If anyone says, “I love God,” and yet is hating his brother, he is a liar. For the one who does not love his brother, whom he has seen, cannot love God, whom he has not seen.

[[v62-4-21]]

^<<v62-4-21,21>>^ And we have this commandment from him, that whoever loves God must also love his brother.

'''

xref:062-1-john/062-1-john-003.adoc#v62-3-0[&#60; Capítulo Anterior] | <<v62-4-0,Topo>> | xref:062-1-john/062-1-john-005.adoc#v62-5-0[Próximo Capítulo &#62;]