include::./index.adoc[]

[[v62-1-0]]
=== The First of John, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v62-1-1]]

^<<v62-1-1,1>>^ That which was from the beginning, which we have heard, which we have seen with our eyes, which we have observed and our hands have felt, concerning the word of life,

[[v62-1-2]]

^<<v62-1-2,2>>^ (yes, the life was made manifest, and we have seen and are bearing witness and reporting to you the everlasting life that was with the Father and was made manifest to us),

[[v62-1-3]]

^<<v62-1-3,3>>^ that which we have seen and heard we are reporting also to you, so that you too may have fellowship^&#42;1^ with us. And this fellowship of ours is with the Father and with his Son Jesus Christ.

[NOTE]
====
. Or “a sharing.”
====

[[v62-1-4]]

^<<v62-1-4,4>>^ And we are writing these things so that our joy may be complete.

[[v62-1-5]]

^<<v62-1-5,5>>^ This is the message that we heard from him and are announcing to you: God is light, and there is no darkness at all in him.^&#42;1^

[NOTE]
====
. Or “in union with him.”
====

[[v62-1-6]]

^<<v62-1-6,6>>^ If we make the statement, “We are having fellowship with him,” and yet we go on walking in the darkness, we are lying and are not practicing the truth.

[[v62-1-7]]

^<<v62-1-7,7>>^ However, if we are walking in the light as he himself is in the light, we do have fellowship with one another, and the blood of Jesus his Son cleanses us from all sin.

[[v62-1-8]]

^<<v62-1-8,8>>^ If we make the statement, “We have no sin,” we are misleading ourselves and the truth is not in us.

[[v62-1-9]]

^<<v62-1-9,9>>^ If we confess our sins, he is faithful and righteous so as to forgive us our sins and to cleanse us from all unrighteousness.

[[v62-1-10]]

^<<v62-1-10,10>>^ If we make the statement, “We have not sinned,” we are making him a liar, and his word is not in us.

'''

xref:061-2-peter/061-2-peter-003.adoc#v61-3-0[&#60; Capítulo Anterior] | <<v62-1-0,Topo>> | xref:062-1-john/062-1-john-002.adoc#v62-2-0[Próximo Capítulo &#62;]