include::./index.adoc[]

[[v28-13-0]]
=== Hosea, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-13-1]]

^<<v28-13-1,1>>^ “When Eʹphra·im spoke, there was trembling;
He was prominent in Israel.
But he became guilty with regard to Baʹal and died.

[[v28-13-2]]

^<<v28-13-2,2>>^ Now they add to their sin
And make metal statues^&#42;1^ from their silver;
They skillfully make idols, all the work of craftsmen.
To them they say, ‘Let the men who sacrifice kiss the calves.’

[NOTE]
====
. Or “molten statues.”
====

[[v28-13-3]]

^<<v28-13-3,3>>^ So they will become like the morning clouds,
Like the dew that vanishes early,
Like chaff blown from the threshing floor by a storm,
And like smoke out of the hole in the roof.

[[v28-13-4]]

^<<v28-13-4,4>>^ But I am Jehovah your God from^&#42;1^ the land of Egypt;
You knew no God except me,
And besides me there is no savior.

[NOTE]
====
. Or “since.”
====

[[v28-13-5]]

^<<v28-13-5,5>>^ I knew you in the wilderness, in the land of drought.

[[v28-13-6]]

^<<v28-13-6,6>>^ They were satisfied with their pastures,
They were satisfied and their heart became proud.
And so they forgot me.

[[v28-13-7]]

^<<v28-13-7,7>>^ I will become like a young lion to them,
Like a leopard lurking along the path.

[[v28-13-8]]

^<<v28-13-8,8>>^ I will come upon them like a bear that has lost its cubs,
And I will rip open their chest.^&#42;1^
I will devour them there like a lion;
A wild beast of the field will tear them to pieces.

[NOTE]
====
. Lit., “the enclosure of their heart.”
====

[[v28-13-9]]

^<<v28-13-9,9>>^ It will destroy you, O Israel,
Because you turned against me, against your helper.

[[v28-13-10]]

^<<v28-13-10,10>>^ Where, then, is your king, that he may save you in all your cities,
And your rulers,^&#42;1^ of whom you said,
‘Give me a king and princes’?

[NOTE]
====
. Lit., “judges.”
====

[[v28-13-11]]

^<<v28-13-11,11>>^ I gave you a king in my anger,
And I will take him away in my fury.

[[v28-13-12]]

^<<v28-13-12,12>>^ The error of Eʹphra·im is wrapped up;^&#42;1^
His sin is stored up.

[NOTE]
====
. Or “is preserved.”
====

[[v28-13-13]]

^<<v28-13-13,13>>^ The pangs of childbirth will come for him.
But he is an unwise child;
He does not present himself when it is time to be born.

[[v28-13-14]]

^<<v28-13-14,14>>^ From the power of the Grave^&#42;1^ I will redeem them;
From death I will recover them.
Where are your stings, O Death?
Where is your destructiveness, O Grave?
Compassion will be concealed from my eyes.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v28-13-15]]

^<<v28-13-15,15>>^ Even if he should flourish among the reeds,
An east wind will come, the wind of Jehovah,
From the desert it comes, to dry up his well and drain his spring.
That one will pillage the treasury of all his precious things.

[[v28-13-16]]

^<<v28-13-16,16>>^ Sa·marʹi·a will be held guilty, for she has rebelled against her God.
By the sword they will fall,
Their children will be dashed to pieces,
And their pregnant women will be ripped open.”

'''

xref:028-hosea/028-hosea-012.adoc#v28-12-0[&#60; Capítulo Anterior] | <<v28-13-0,Topo>> | xref:028-hosea/028-hosea-014.adoc#v28-14-0[Próximo Capítulo &#62;]