include::./index.adoc[]

[[v28-7-0]]
=== Hosea, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-7-1]]

^<<v28-7-1,1>>^ “At the time when I would heal Israel,
The error of Eʹphra·im is also exposed,
And the wickedness of Sa·marʹi·a.
For they practice deception;
Thieves break in and marauder bands raid outside.

[[v28-7-2]]

^<<v28-7-2,2>>^ But they do not say in their heart that I will remember all their wickedness.
Now their dealings are all around them;
They are right in front of my face.

[[v28-7-3]]

^<<v28-7-3,3>>^ They make the king rejoice by their wickedness,
And princes by their deceit.

[[v28-7-4]]

^<<v28-7-4,4>>^ All of them are adulterers,
Burning like an oven fired by a baker,
Who stops stirring the fire after kneading the dough until it is leavened.

[[v28-7-5]]

^<<v28-7-5,5>>^ On the day of our king, princes have become sick
—They are enraged because of wine.
He has reached out his hand to ridiculers.

[[v28-7-6]]

^<<v28-7-6,6>>^ For they approach with hearts burning like an oven.^&#42;1^
All night long the baker sleeps;
In the morning the oven blazes like a flaming fire.

[NOTE]
====
. Or possibly, “For their hearts are like an oven as they approach with their intrigues.”
====

[[v28-7-7]]

^<<v28-7-7,7>>^ All of them are hot like an oven,
And they devour their rulers.^&#42;1^
All their kings have fallen;
No one among them calls out to me.

[NOTE]
====
. Lit., “judges.”
====

[[v28-7-8]]

^<<v28-7-8,8>>^ Eʹphra·im mixes with the nations.
Eʹphra·im is like a round cake left unturned.

[[v28-7-9]]

^<<v28-7-9,9>>^ Strangers have consumed his strength, but he does not know it.
And his gray hairs have turned white, but he does not notice it.

[[v28-7-10]]

^<<v28-7-10,10>>^ The pride of Israel has testified against him,
But they have not returned to Jehovah their God,
Nor have they looked for him despite all of this.

[[v28-7-11]]

^<<v28-7-11,11>>^ Eʹphra·im is like a simpleminded dove, lacking good sense.^&#42;1^
They have called out to Egypt; they have gone to As·syrʹi·a.

[NOTE]
====
. Lit., “without heart.”
====

[[v28-7-12]]

^<<v28-7-12,12>>^ Wherever they go, I will spread my net over them.
I will bring them down like the birds of the heavens.
I will discipline them according to the warning given to their assembly.

[[v28-7-13]]

^<<v28-7-13,13>>^ Woe to them, for they have fled from me!
Devastation to them, for they have transgressed against me!
I was ready to redeem them, but they have spoken lies against me.

[[v28-7-14]]

^<<v28-7-14,14>>^ From their heart they did not call to me for help,
Although they kept wailing on their beds.
For their grain and new wine they would slash themselves;
They turn against me.

[[v28-7-15]]

^<<v28-7-15,15>>^ Although I disciplined them and strengthened their arms,
They are against me, scheming what is bad.

[[v28-7-16]]

^<<v28-7-16,16>>^ They changed course, but not to anything loftier;^&#42;1^
They were as unreliable as a loose bow.
Their princes will fall by the sword because of their defiant tongues.
For this they will be an object of ridicule in the land of Egypt.”

[NOTE]
====
. That is, not to an elevated form of worship.
====

'''

xref:028-hosea/028-hosea-006.adoc#v28-6-0[&#60; Capítulo Anterior] | <<v28-7-0,Topo>> | xref:028-hosea/028-hosea-008.adoc#v28-8-0[Próximo Capítulo &#62;]