include::./index.adoc[]

[[v28-1-0]]
=== Hosea, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-1-1]]

^<<v28-1-1,1>>^ The word of Jehovah that came to Ho·seʹa^&#42;1^ the son of Be·eʹri in the days of Uz·ziʹah, Joʹtham, Aʹhaz, and Hez·e·kiʹah, kings of Judah, and in the days of Jer·o·boʹam son of Joʹash, the king of Israel.

[NOTE]
====
. Shortened form of Hoshaiah, which means “Saved by Jah; Jah Has Saved.”
====

[[v28-1-2]]

^<<v28-1-2,2>>^ When Jehovah started to speak his word through Ho·seʹa, Jehovah said to Ho·seʹa: “Go, marry a woman of prostitution^&#42;1^ and have children of prostitution,^&#42;2^ because by prostitution^&#42;3^ the land has turned completely away from following Jehovah.”

[NOTE]
====
. Or “immorality; promiscuity.”
. Or “immorality; promiscuity.”
. Or “immorality; promiscuity.”
====

[[v28-1-3]]

^<<v28-1-3,3>>^ So he went and married Goʹmer the daughter of Dib·laʹim, and she conceived and bore him a son.

[[v28-1-4]]

^<<v28-1-4,4>>^ Then Jehovah said to him: “Name him Jezʹre·el,^&#42;1^ for in a little while I will hold an accounting against the house of Jeʹhu for the acts of bloodshed of Jezʹre·el, and I will put an end to the royal rule of the house of Israel.

[NOTE]
====
. Meaning “God Will Sow Seed.”
====

[[v28-1-5]]

^<<v28-1-5,5>>^ In that day I will break the bow of Israel in the Valley^&#42;1^ of Jezʹre·el.”

[NOTE]
====
. Or “Low Plain.”
====

[[v28-1-6]]

^<<v28-1-6,6>>^ She conceived again and gave birth to a daughter. And He told him: “Name her Lo-ru·haʹmah,^&#42;1^ for I will no longer show mercy to the house of Israel, because I will certainly drive them away.

[NOTE]
====
. Meaning “Not Shown Mercy.”
====

[[v28-1-7]]

^<<v28-1-7,7>>^ But I will show mercy to the house of Judah, and I will save them by Jehovah their God; I will not save them by bow or by sword or by war or by horses or by horsemen.”

[[v28-1-8]]

^<<v28-1-8,8>>^ After weaning Lo-ru·haʹmah, she conceived and gave birth to a son.

[[v28-1-9]]

^<<v28-1-9,9>>^ Then He said: “Name him Lo-amʹmi,^&#42;1^ because you are not my people and I will not be yours.

[NOTE]
====
. Meaning “Not My People.”
====

[[v28-1-10]]

^<<v28-1-10,10>>^ “And the number of the people^&#42;1^ of Israel will be like the grains of sand of the sea, which cannot be measured or numbered. And in the place where it was said to them, ‘You are not my people,’ it will be said to them, ‘The sons of the living God.’

[NOTE]
====
. Lit., “sons.”
====

[[v28-1-11]]

^<<v28-1-11,11>>^ And the people of Judah and of Israel will be gathered together into unity and will choose for themselves one head and go up out of the land, for great will be the day of Jezʹre·el.

'''

xref:027-daniel/027-daniel-012.adoc#v27-12-0[&#60; Capítulo Anterior] | <<v28-1-0,Topo>> | xref:028-hosea/028-hosea-002.adoc#v28-2-0[Próximo Capítulo &#62;]