include::./index.adoc[]

[[v28-2-0]]
=== Hosea, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-2-1]]

^<<v28-2-1,1>>^ “Say to your brothers, ‘My people!’^&#42;1^
And to your sisters, ‘O woman shown mercy!’^&#42;2^

[NOTE]
====
. See Ho 1:9 ftn.
. See Ho 1:6 ftn.
====

[[v28-2-2]]

^<<v28-2-2,2>>^ Accuse your mother; accuse her,
For she is not my wife and I am not her husband.
She should remove her prostitution^&#42;1^ from herself
And her adultery from between her breasts,

[NOTE]
====
. Or “immorality; promiscuity.”
====

[[v28-2-3]]

^<<v28-2-3,3>>^ Or I will strip her naked and make her as in the day she was born,
Making her like a wilderness,
Reducing her to a waterless land,
And causing her to die of thirst.

[[v28-2-4]]

^<<v28-2-4,4>>^ And to her sons I will not show mercy,
For they are the sons of prostitution.^&#42;1^

[NOTE]
====
. Or “immorality; promiscuity.”
====

[[v28-2-5]]

^<<v28-2-5,5>>^ For their mother has committed prostitution.^&#42;1^
She who was pregnant with them has acted shamefully, for she said,
‘I will go after my passionate lovers,
Those who give me my bread and my water,
My wool and my linen, my oil and my drink.’

[NOTE]
====
. Or “engaged in immorality (promiscuity).”
====

[[v28-2-6]]

^<<v28-2-6,6>>^ So I will block your way with a hedge of thorns;
And I will raise up a stone wall against her,
So that she cannot find her paths.

[[v28-2-7]]

^<<v28-2-7,7>>^ She will chase after her passionate lovers, but she will not overtake them;
She will look for them, but she will not find them.
Then she will say, ‘I will go back to my first husband,
For I was better off at that time than I am now.’

[[v28-2-8]]

^<<v28-2-8,8>>^ She did not recognize that it was I who had given her the grain, the new wine, and the oil,
And I who had given her silver in abundance
And gold, which they used for Baʹal.

[[v28-2-9]]

^<<v28-2-9,9>>^ ‘Therefore, I will return and take away my grain in its time
And my new wine in its season,
And I will snatch away my wool and my linen that were to cover her nakedness.

[[v28-2-10]]

^<<v28-2-10,10>>^ Now I will expose her private parts in full view of her passionate lovers,
And no man will rescue her out of my hand.

[[v28-2-11]]

^<<v28-2-11,11>>^ I will put an end to all her joy,
Her festivals, her new moons, her sabbaths, and all her festive seasons.

[[v28-2-12]]

^<<v28-2-12,12>>^ And I will ruin her vines and her fig trees, of which she has said:
“These are my wages, which my passionate lovers gave to me”;
I will turn them into a forest,
And the wild animals of the field will devour them.

[[v28-2-13]]

^<<v28-2-13,13>>^ I will hold an accounting against her for the days when she offered sacrifices to the Baʹal images,
When she would adorn herself with her rings and ornaments and would chase after her passionate lovers,
And I was the one she forgot,’ declares Jehovah.

[[v28-2-14]]

^<<v28-2-14,14>>^ ‘So I will persuade her,
I will lead her into the wilderness,
And I will speak to win her heart.

[[v28-2-15]]

^<<v28-2-15,15>>^ I will give her vineyards back to her from that time onward,
And the Valley^&#42;1^ of Aʹchor as a gateway to hope;
She will answer there as in the days of her youth,
As in the day when she came out of the land of Egypt.

[NOTE]
====
. Or “Low Plain.”
====

[[v28-2-16]]

^<<v28-2-16,16>>^ And in that day,’ declares Jehovah,
‘You will call me My husband, and you will no longer call me My master.’^&#42;1^

[NOTE]
====
. Or “My Baal.”
====

[[v28-2-17]]

^<<v28-2-17,17>>^ ‘I will remove the names of the Baʹal images from her mouth,
And they will no longer be remembered by their name.

[[v28-2-18]]

^<<v28-2-18,18>>^ In that day I will make a covenant for them with the wild animals of the field,
And with the birds of the heavens and the creeping things of the ground;
I will rid the land of the bow and the sword and war,
And I will make them lie down^&#42;1^ in security.

[NOTE]
====
. Or “let them live.”
====

[[v28-2-19]]

^<<v28-2-19,19>>^ I will engage myself to you forever;
And I will engage myself to you in righteousness and in justice,
In loyal love and in mercy.

[[v28-2-20]]

^<<v28-2-20,20>>^ I will engage myself to you in faithfulness,
And you will certainly know Jehovah.’

[[v28-2-21]]

^<<v28-2-21,21>>^ ‘In that day I will answer,’ declares Jehovah,
‘I will answer the heavens,
And they will answer the earth;

[[v28-2-22]]

^<<v28-2-22,22>>^ And the earth will answer the grain and the new wine and the oil;
And they will answer Jezʹre·el.^&#42;1^

[NOTE]
====
. Meaning “God Will Sow Seed.”
====

[[v28-2-23]]

^<<v28-2-23,23>>^ I will sow her like seed for myself in the earth,
And I will show mercy to her who was not shown mercy;^&#42;1^
I will say to those not my people:^&#42;2^ “You are my people,”
And they will say: “You are my God.”’”

[NOTE]
====
. See Ho 1:6 ftn.
. See Ho 1:9 ftn.
====

'''

xref:028-hosea/028-hosea-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-hosea/028-hosea-003.adoc#v28-3-0[Próximo Capítulo &#62;]