include::./index.adoc[]

[[v28-5-0]]
=== Hosea, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-5-1]]

^<<v28-5-1,1>>^ “Hear this, you priests,
Pay attention, O house of Israel,
Listen, O house of the king,
For the judgment involves you;
Because you are a trap to Mizʹpah
And a net spread over Taʹbor.

[[v28-5-2]]

^<<v28-5-2,2>>^ And those falling away^&#42;1^ have sunk deep^&#42;2^ in slaughter,
And I am warning^&#42;3^ all of them.

[NOTE]
====
. Or “the rebels.”
. Or “have been deeply involved.”
. Or “I will discipline.”
====

[[v28-5-3]]

^<<v28-5-3,3>>^ I know Eʹphra·im,
And Israel is not hidden from me.
For now, O Eʹphra·im, you have acted promiscuously;^&#42;1^
Israel has defiled itself.

[NOTE]
====
. Or “have acted immorally; have engaged in prostitution.”
====

[[v28-5-4]]

^<<v28-5-4,4>>^ Their dealings do not permit them to return to their God,
Because there is a spirit of prostitution^&#42;1^ among them;
And Jehovah they do not acknowledge.

[NOTE]
====
. Or “immorality; promiscuity.”
====

[[v28-5-5]]

^<<v28-5-5,5>>^ The pride of Israel has testified against him;^&#42;1^
Both Israel and Eʹphra·im have stumbled in their error,
And Judah has stumbled with them.

[NOTE]
====
. Lit., “to his face.”
====

[[v28-5-6]]

^<<v28-5-6,6>>^ With their flock and their herd they went to look for Jehovah,
But they could not find him.
He had drawn away from them.

[[v28-5-7]]

^<<v28-5-7,7>>^ They have betrayed Jehovah,
For they have fathered foreign sons.
Now a month will devour them^&#42;1^ and their portions.^&#42;2^

[NOTE]
====
. Or possibly, “Within a month they will be devoured.”
. Or “fields.”
====

[[v28-5-8]]

^<<v28-5-8,8>>^ Blow a horn in Gibʹe·ah, a trumpet in Raʹmah!
Shout a war cry at Beth-aʹven—after you, O Benjamin!

[[v28-5-9]]

^<<v28-5-9,9>>^ O Eʹphra·im, you will become an object of horror in the day of punishment.
I have made known what will surely happen among the tribes of Israel.

[[v28-5-10]]

^<<v28-5-10,10>>^ The princes of Judah are like those moving a boundary.
I will pour out my fury on them like water.

[[v28-5-11]]

^<<v28-5-11,11>>^ Eʹphra·im is oppressed, crushed by judgment,
For he was determined to follow after his adversary.

[[v28-5-12]]

^<<v28-5-12,12>>^ So I was like a moth to Eʹphra·im
And like rottenness to the house of Judah.

[[v28-5-13]]

^<<v28-5-13,13>>^ When Eʹphra·im saw his sickness, and Judah his ulcer,
Eʹphra·im went to As·syrʹi·a and sent to a great king.
But he was unable to heal you,
And he could not cure your ulcer.

[[v28-5-14]]

^<<v28-5-14,14>>^ For I will be like a young lion to Eʹphra·im,
And like a strong lion^&#42;1^ to the house of Judah.
I myself will tear to pieces and go away;
I will carry them off, and no one will rescue them.

[NOTE]
====
. Or “a maned young lion.”
====

[[v28-5-15]]

^<<v28-5-15,15>>^ I will go away and return to my place until they bear the consequences of their guilt,
And then they will seek my favor.^&#42;1^
When they are in distress, they will seek me.”

[NOTE]
====
. Lit., “face.”
====

'''

xref:028-hosea/028-hosea-004.adoc#v28-4-0[&#60; Capítulo Anterior] | <<v28-5-0,Topo>> | xref:028-hosea/028-hosea-006.adoc#v28-6-0[Próximo Capítulo &#62;]