include::./index.adoc[]

[[v28-8-0]]
=== Hosea, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-8-1]]

^<<v28-8-1,1>>^ “Put a horn to your mouth!
One comes like an eagle against the house of Jehovah,
For they have violated my covenant and transgressed against my law.

[[v28-8-2]]

^<<v28-8-2,2>>^ To me they cry out, ‘My God, we, Israel, know you!’

[[v28-8-3]]

^<<v28-8-3,3>>^ Israel has rejected what is good.
Let an enemy pursue him.

[[v28-8-4]]

^<<v28-8-4,4>>^ They have appointed kings, but not through me.
They have appointed princes, but I did not recognize them.
With their silver and their gold they have made idols,
To their own destruction.

[[v28-8-5]]

^<<v28-8-5,5>>^ Your calf has been rejected, O Sa·marʹi·a.
My anger flares up against them.
How long will they be incapable of innocence?^&#42;1^

[NOTE]
====
. Or “purity?”
====

[[v28-8-6]]

^<<v28-8-6,6>>^ For this is from Israel.
A craftsman made it, and it is not God;
The calf of Sa·marʹi·a will be reduced to splinters.

[[v28-8-7]]

^<<v28-8-7,7>>^ For it is wind that they are sowing,
And they will reap a storm wind.
No stalk produces ripe^&#42;1^ grain;
Whatever sprouts produces no flour.
If any is produced, foreigners^&#42;2^ will swallow it down.

[NOTE]
====
. Or “standing.”
. Or “strangers.”
====

[[v28-8-8]]

^<<v28-8-8,8>>^ Israel will be swallowed down.
Now they will be among the nations,
Like an unwanted vessel.

[[v28-8-9]]

^<<v28-8-9,9>>^ For they have gone up to As·syrʹi·a, like a lone wild donkey.
Eʹphra·im has hired lovers.

[[v28-8-10]]

^<<v28-8-10,10>>^ Although they hire them from among the nations,
I will now round them up;
They will begin to suffer because of the burden imposed by king and princes.

[[v28-8-11]]

^<<v28-8-11,11>>^ For Eʹphra·im has multiplied altars to sin.
They became his altars for sinning.

[[v28-8-12]]

^<<v28-8-12,12>>^ I wrote for him the many things of my law,^&#42;1^
But they were regarded as something strange.

[NOTE]
====
. Or “instruction.”
====

[[v28-8-13]]

^<<v28-8-13,13>>^ They offer sacrificial gifts to me, and they eat the meat,
But Jehovah takes no pleasure in them.
Now he will remember their error and punish them for their sins.
They have turned back^&#42;1^ to Egypt.

[NOTE]
====
. Or possibly, “They will return.”
====

[[v28-8-14]]

^<<v28-8-14,14>>^ Israel has forgotten his Maker and has built temples,
And Judah has multiplied fortified cities.
But I will send fire into his cities,
And it will consume the towers of each one.”

'''

xref:028-hosea/028-hosea-007.adoc#v28-7-0[&#60; Capítulo Anterior] | <<v28-8-0,Topo>> | xref:028-hosea/028-hosea-009.adoc#v28-9-0[Próximo Capítulo &#62;]