include::./index.adoc[]

[[v28-14-0]]
=== Hosea, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-14-1]]

^<<v28-14-1,1>>^ “Come back, O Israel, to Jehovah your God,
For you have stumbled because of your error.

[[v28-14-2]]

^<<v28-14-2,2>>^ Come back to Jehovah with these words,
Say to him, ‘May you pardon our error and accept what is good,
And we will offer the praise of our lips as we would young bulls.^&#42;1^

[NOTE]
====
. Lit., “offer in return the young bulls of our lips.”
====

[[v28-14-3]]

^<<v28-14-3,3>>^ As·syrʹi·a will not save us.
We will not ride on horses,
And we will no longer say, “O our God!” to the work of our hands,
For it is by you that the fatherless child is shown mercy.’

[[v28-14-4]]

^<<v28-14-4,4>>^ I will heal their unfaithfulness.
I will love them of my own free will,
Because my anger has turned away from him.

[[v28-14-5]]

^<<v28-14-5,5>>^ I will become like the dew to Israel;
He will blossom like the lily
And will send down his roots like the trees of Lebʹa·non.

[[v28-14-6]]

^<<v28-14-6,6>>^ His twigs will spread,
His splendor will be like that of the olive tree,
And his fragrance like that of Lebʹa·non.

[[v28-14-7]]

^<<v28-14-7,7>>^ They will again dwell in his shadow.
They will grow grain and will bud like the vine.
His fame^&#42;1^ will be like the wine of Lebʹa·non.

[NOTE]
====
. Lit., “memorial.”
====

[[v28-14-8]]

^<<v28-14-8,8>>^ Eʹphra·im will say, ‘What more do I have to do with idols?’
I will answer and watch over him.
I will be like a thriving juniper tree.
From me your fruit will be found.”

[[v28-14-9]]

^<<v28-14-9,9>>^ Who is wise? Let him understand these things.
Who is discreet? Let him know them.
For the ways of Jehovah are upright,
And the righteous will walk in them;
But the transgressors will stumble in them.

'''

xref:028-hosea/028-hosea-013.adoc#v28-13-0[&#60; Capítulo Anterior] | <<v28-14-0,Topo>> | xref:029-joel/029-joel-001.adoc#v29-1-0[Próximo Capítulo &#62;]