include::./index.adoc[]

[[v28-11-0]]
=== Hosea, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-11-1]]

^<<v28-11-1,1>>^ “When Israel was a boy, I loved him,
And out of Egypt I called my son.

[[v28-11-2]]

^<<v28-11-2,2>>^ The more they^&#42;1^ called them,
The more they went away from them.
They kept sacrificing to the Baʹal images
And offering sacrifices to the graven images.

[NOTE]
====
. That is, prophets and others sent to instruct Israel.
====

[[v28-11-3]]

^<<v28-11-3,3>>^ But it was I who taught Eʹphra·im to walk, taking them in my arms;
And they did not acknowledge that I had healed them.

[[v28-11-4]]

^<<v28-11-4,4>>^ With the ropes of men^&#42;1^ I kept drawing them, with the cords of love;
And I was to them like one lifting a yoke from their jaws,
And I gently brought food to each one.

[NOTE]
====
. Or “the ropes of kindness,” like those of a parent.
====

[[v28-11-5]]

^<<v28-11-5,5>>^ They will not return to the land of Egypt, but As·syrʹi·a will be their king,
Because they refused to return to me.

[[v28-11-6]]

^<<v28-11-6,6>>^ And a sword will whirl against his cities
And destroy his bars and devour them because of their schemes.

[[v28-11-7]]

^<<v28-11-7,7>>^ My people are bent on unfaithfulness to me.
Though they called them upward,^&#42;1^ no one rises up.

[NOTE]
====
. That is, to an elevated form of worship.
====

[[v28-11-8]]

^<<v28-11-8,8>>^ How can I give you up, O Eʹphra·im?
How can I hand you over, O Israel?
How can I treat you like Adʹmah?
How can I make you like Ze·boiʹim?
I have had a change of heart;
At the same time my compassions are stirred.^&#42;1^

[NOTE]
====
. Lit., “have grown hot.”
====

[[v28-11-9]]

^<<v28-11-9,9>>^ I will not vent my burning anger.
I will not destroy Eʹphra·im again,
For I am God and not man,
The Holy One in your midst;
And I will not come against you in fury.

[[v28-11-10]]

^<<v28-11-10,10>>^ They will walk after Jehovah, and he will roar like a lion;
When he roars, his sons will come trembling from the west.

[[v28-11-11]]

^<<v28-11-11,11>>^ They will tremble like a bird when they come out of Egypt,
Like a dove out of the land of As·syrʹi·a;
And I will settle them in their houses,” declares Jehovah.

[[v28-11-12]]

^<<v28-11-12,12>>^ “Eʹphra·im has surrounded me with lies,
And the house of Israel with deceit.
But Judah still roams^&#42;1^ with God,
And he is faithful to the Most Holy One.”

[NOTE]
====
. Or “walks.”
====

'''

xref:028-hosea/028-hosea-010.adoc#v28-10-0[&#60; Capítulo Anterior] | <<v28-11-0,Topo>> | xref:028-hosea/028-hosea-012.adoc#v28-12-0[Próximo Capítulo &#62;]