include::./index.adoc[]

[[v28-3-0]]
=== Hosea, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-3-1]]

^<<v28-3-1,1>>^ Then Jehovah said to me: “Go once again, love the woman who is loved by another man and is committing adultery, just as Jehovah loves the people of Israel while they turn to other gods and love raisin cakes.”^&#42;1^

[NOTE]
====
. That is, those used in false worship.
====

[[v28-3-2]]

^<<v28-3-2,2>>^ So I purchased her for myself for 15 silver pieces and a hoʹmer measure^&#42;1^ and a half of barley.

[NOTE]
====
. A homer equaled 220 L (200 dry qt). See App. B14.
====

[[v28-3-3]]

^<<v28-3-3,3>>^ Then I said to her: “You will remain mine for many days. You must not commit prostitution,^&#42;1^ and you must not have relations with another man, and I will behave the same way toward you.”^&#42;2^

[NOTE]
====
. Or “engage in immorality (promiscuity).”
. Or “I will not have relations with you.”
====

[[v28-3-4]]

^<<v28-3-4,4>>^ It is because for a long time^&#42;1^ the people of Israel will dwell without a king, without a prince, without a sacrifice, without a pillar, and without an ephʹod and teraphim statues.^&#42;2^

[NOTE]
====
. Lit., “many days.”
. Or “household gods; idols.”
====

[[v28-3-5]]

^<<v28-3-5,5>>^ Afterward the people of Israel will come back and look for Jehovah their God and for David their king, and they will come trembling to Jehovah and to his goodness in the final part of the days.

'''

xref:028-hosea/028-hosea-002.adoc#v28-2-0[&#60; Capítulo Anterior] | <<v28-3-0,Topo>> | xref:028-hosea/028-hosea-004.adoc#v28-4-0[Próximo Capítulo &#62;]