include::./index.adoc[]

[[v28-4-0]]
=== Hosea, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-4-1]]

^<<v28-4-1,1>>^ Hear the word of Jehovah, O people of Israel,
For Jehovah has a legal case against the inhabitants of the land,
Because there is no truth nor loyal love nor knowledge of God in the land.

[[v28-4-2]]

^<<v28-4-2,2>>^ False oaths and lying and murder
And stealing and adultery are widespread,
And one act of bloodshed follows another act of bloodshed.

[[v28-4-3]]

^<<v28-4-3,3>>^ That is why the land will mourn
And every inhabitant in it will waste away;
The wild animals of the field and the birds of the heavens,
Even the fish of the sea, will perish.

[[v28-4-4]]

^<<v28-4-4,4>>^ “However, let no man contend or reprove,
For your people are like those who contend against a priest.

[[v28-4-5]]

^<<v28-4-5,5>>^ So you will stumble in broad daylight,
And the prophet will stumble with you, as if it were night.
And I will silence^&#42;1^ your mother.

[NOTE]
====
. Or “destroy.”
====

[[v28-4-6]]

^<<v28-4-6,6>>^ My people will be silenced,^&#42;1^ because there is no knowledge.
Because you have rejected knowledge,
I will also reject you from serving as my priest;
And because you have forgotten the law^&#42;2^ of your God,
I myself will forget your sons.

[NOTE]
====
. Or “destroyed.”
. Or “instruction.”
====

[[v28-4-7]]

^<<v28-4-7,7>>^ The more they increased, the more they sinned against me.
I will change their glory into disgrace.^&#42;1^

[NOTE]
====
. Or possibly, “They have exchanged my own glory for disgrace.”
====

[[v28-4-8]]

^<<v28-4-8,8>>^ They feed on the sin of my people,
And they are greedy for^&#42;1^ their error.

[NOTE]
====
. Or “lift up their soul to.” See Glossary, “Soul.”
====

[[v28-4-9]]

^<<v28-4-9,9>>^ It will be the same for the people as for the priest;
I will call them to account for their ways,
And I will bring on them the consequences of their actions.

[[v28-4-10]]

^<<v28-4-10,10>>^ They will eat but not be satisfied.
They will be promiscuous,^&#42;1^ but they will not increase,
Because they have shown no regard for Jehovah.

[NOTE]
====
. Or “be grossly immoral; engage in prostitution.”
====

[[v28-4-11]]

^<<v28-4-11,11>>^ Prostitution^&#42;1^ and wine and new wine
Take away the motivation to do what is right.^&#42;2^

[NOTE]
====
. Or “Immorality; Promiscuity.”
. Lit., “Take away heart.”
====

[[v28-4-12]]

^<<v28-4-12,12>>^ My people consult their wooden idols,
Doing what their staff^&#42;1^ tells them;
Because the spirit of prostitution^&#42;2^ causes them to go astray,
And by their prostitution^&#42;3^ they refuse to submit to their God.

[NOTE]
====
. Or “diviner’s rod.”
. Or “immorality; promiscuity.”
. Or “immorality; promiscuity.”
====

[[v28-4-13]]

^<<v28-4-13,13>>^ On the tops of the mountains they sacrifice,
And on the hills they make sacrifices smoke,
Under oak trees and storax trees and every big tree,
Because their shade is good.
That is why your daughters commit prostitution^&#42;1^
And your daughters-in-law commit adultery.

[NOTE]
====
. Or “immorality; promiscuity.”
====

[[v28-4-14]]

^<<v28-4-14,14>>^ I will not hold an accounting against your daughters because of their prostitution,^&#42;1^
And against your daughters-in-law because of their adultery.
For the men go off with the harlots
And sacrifice with the temple prostitutes;
Such a people without understanding will come to ruin.

[NOTE]
====
. Or “immorality; promiscuity.”
====

[[v28-4-15]]

^<<v28-4-15,15>>^ Although you are committing prostitution,^&#42;1^ O Israel,
Let not Judah become guilty.
Do not come to Gilʹgal or to Beth-aʹven,
And do not swear, ‘As surely as Jehovah is alive!’

[NOTE]
====
. Or “immorality; promiscuity.”
====

[[v28-4-16]]

^<<v28-4-16,16>>^ For like a stubborn cow, Israel has become stubborn.
Will Jehovah now shepherd them like a young ram in an open pasture?^&#42;1^

[NOTE]
====
. Lit., “a roomy place?”
====

[[v28-4-17]]

^<<v28-4-17,17>>^ Eʹphra·im is joined to idols.
Let him alone!

[[v28-4-18]]

^<<v28-4-18,18>>^ When their beer^&#42;1^ is finished,
They become promiscuous.^&#42;2^
And her rulers^&#42;3^ dearly love dishonor.

[NOTE]
====
. Or “wheat beer.”
. Or “become grossly immoral; engage in prostitution.”
. Lit., “shields.”
====

[[v28-4-19]]

^<<v28-4-19,19>>^ The wind will wrap her^&#42;1^ in its wings,
And they will be ashamed of their sacrifices.”

[NOTE]
====
. Or “will sweep her away.”
====

'''

xref:028-hosea/028-hosea-003.adoc#v28-3-0[&#60; Capítulo Anterior] | <<v28-4-0,Topo>> | xref:028-hosea/028-hosea-005.adoc#v28-5-0[Próximo Capítulo &#62;]