include::./index.adoc[]

[[v28-12-0]]
=== Hosea, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-12-1]]

^<<v28-12-1,1>>^ “Eʹphra·im is feeding on wind.
He chases after the east wind all day long.
He multiplies lies and violence.
They make a covenant with As·syrʹi·a and take oil to Egypt.

[[v28-12-2]]

^<<v28-12-2,2>>^ Jehovah has a legal case against Judah;
He will call for an accounting against Jacob according to his ways,
And he will repay him according to his deeds.

[[v28-12-3]]

^<<v28-12-3,3>>^ In the womb he seized his brother by the heel,
And with his vigor he contended with God.

[[v28-12-4]]

^<<v28-12-4,4>>^ He kept contending with an angel and prevailed.
He wept and begged for his favor.”
He found him at Bethʹel, and there He spoke with us,

[[v28-12-5]]

^<<v28-12-5,5>>^ Jehovah the God of armies,
Jehovah is his memorial name.^&#42;1^

[NOTE]
====
. Or “is the name by which he is remembered.”
====

[[v28-12-6]]

^<<v28-12-6,6>>^ “So return to your God,
Maintain loyal love and justice,
And always hope in your God.

[[v28-12-7]]

^<<v28-12-7,7>>^ But in the hand of the tradesman^&#42;1^ are deceptive scales;
He loves to defraud.

[NOTE]
====
. Or “merchant.”
====

[[v28-12-8]]

^<<v28-12-8,8>>^ Eʹphra·im keeps saying, ‘Indeed, I have become rich;
I have found wealth.
And in all my toil, they will not find anything wrong or sinful.’

[[v28-12-9]]

^<<v28-12-9,9>>^ But I am Jehovah your God from^&#42;1^ the land of Egypt.
I will again make you dwell in tents
As in the days of an appointed time.^&#42;2^

[NOTE]
====
. Or “since.”
. Or possibly, “a festival.”
====

[[v28-12-10]]

^<<v28-12-10,10>>^ I spoke to the prophets,
I multiplied their visions,
And I spoke parables through the prophets.

[[v28-12-11]]

^<<v28-12-11,11>>^ With Gilʹe·ad there has been deception^&#42;1^ and untruth.
In Gilʹgal they have sacrificed bulls,
And their altars are like piles of stones in the furrows of the field.

[NOTE]
====
. Or “what is uncanny; what is mystical.”
====

[[v28-12-12]]

^<<v28-12-12,12>>^ Jacob ran away to the territory^&#42;1^ of Aʹram;^&#42;2^
Israel served there for a wife,
And for a wife he guarded sheep.

[NOTE]
====
. Lit., “field.”
. Or “Syria.”
====

[[v28-12-13]]

^<<v28-12-13,13>>^ By a prophet Jehovah brought Israel up from Egypt,
And by a prophet he was guarded.

[[v28-12-14]]

^<<v28-12-14,14>>^ Eʹphra·im has caused bitter offense;
His bloodguilt remains on him;
His Lord will repay him for his reproach.”

'''

xref:028-hosea/028-hosea-011.adoc#v28-11-0[&#60; Capítulo Anterior] | <<v28-12-0,Topo>> | xref:028-hosea/028-hosea-013.adoc#v28-13-0[Próximo Capítulo &#62;]