include::./index.adoc[]

[[v28-9-0]]
=== Hosea, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v28-9-1]]

^<<v28-9-1,1>>^ “Do not rejoice, O Israel,
Do not act joyfully like the peoples.
For by prostitution^&#42;1^ you have strayed from your God.
You have loved the wages of a prostitute on every threshing floor of grain.

[NOTE]
====
. Or “immorality; promiscuity.”
====

[[v28-9-2]]

^<<v28-9-2,2>>^ But the threshing floor and winepress will not feed them,
And new wine will fail her.

[[v28-9-3]]

^<<v28-9-3,3>>^ They will not continue dwelling in the land of Jehovah;
Instead, Eʹphra·im will return to Egypt,
And in As·syrʹi·a they will eat what is unclean.

[[v28-9-4]]

^<<v28-9-4,4>>^ They will no longer pour out wine offerings to Jehovah;
Their sacrifices will not please him.
They are like the bread of mourning;
All those eating it will defile themselves.
For their bread is for themselves alone;^&#42;1^
It will not come into the house of Jehovah.

[NOTE]
====
. Or “for their own soul.”
====

[[v28-9-5]]

^<<v28-9-5,5>>^ What will you do in the day of meeting,^&#42;1^
In the day of Jehovah’s festival?

[NOTE]
====
. Or “your appointed feast.”
====

[[v28-9-6]]

^<<v28-9-6,6>>^ For look! they will have to flee because of destruction.
Egypt will gather them together, and Memʹphis will bury them.
Nettles will take possession of their precious things of silver,
And thornbushes will be in their tents.

[[v28-9-7]]

^<<v28-9-7,7>>^ The days of reckoning will come,
The days of retribution will come,
And Israel will know it.
Their prophet will be a fool, and the man of inspiration will go mad;
Because your error is abundant, the animosity against you is abundant.”

[[v28-9-8]]

^<<v28-9-8,8>>^ The watchman of Eʹphra·im was with my God.
But now all the ways of his prophets are as the traps of a birdcatcher;
There is animosity in the house of his God.

[[v28-9-9]]

^<<v28-9-9,9>>^ They have sunk deep into ruin, as in the days of Gibʹe·ah.
He will remember their error and punish their sins.

[[v28-9-10]]

^<<v28-9-10,10>>^ “Like grapes in the wilderness I found Israel.
Like the first of the early figs on a fig tree I saw your forefathers.
But they went to Baʹal of Peʹor;
They dedicated themselves to the shameful thing,^&#42;1^
And they became disgusting like the object of their love.

[NOTE]
====
. Or “the shameful god.”
====

[[v28-9-11]]

^<<v28-9-11,11>>^ Eʹphra·im’s glory flies away like a bird;
There is no giving birth, no pregnancy, and no conception.

[[v28-9-12]]

^<<v28-9-12,12>>^ Even if they raise children,
I will bereave them until no man is left;
Yes, woe to them when I turn away from them!

[[v28-9-13]]

^<<v28-9-13,13>>^ Eʹphra·im, planted in a pasture, was to me like Tyre;
Now Eʹphra·im must bring his sons out to the slaughter.”

[[v28-9-14]]

^<<v28-9-14,14>>^ Give them, O Jehovah, what you should give them;
A womb that miscarries and dry^&#42;1^ breasts.

[NOTE]
====
. Or “shriveled.”
====

[[v28-9-15]]

^<<v28-9-15,15>>^ “All their wickedness was in Gilʹgal, for there I came to hate them.
I will drive them away from my house because of their evil deeds.
I will no longer love them;
All their princes are stubborn.

[[v28-9-16]]

^<<v28-9-16,16>>^ Eʹphra·im will be struck down.
Their root will dry up, and they will produce no fruit.
Even if they give birth, I will put to death their cherished offspring.”

[[v28-9-17]]

^<<v28-9-17,17>>^ My God will reject them,
For they have not listened to him,
And they will become fugitives among the nations.

'''

xref:028-hosea/028-hosea-008.adoc#v28-8-0[&#60; Capítulo Anterior] | <<v28-9-0,Topo>> | xref:028-hosea/028-hosea-010.adoc#v28-10-0[Próximo Capítulo &#62;]