include::./index.adoc[]

[[v34-2-0]]
=== Nahum, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v34-2-1]]

^<<v34-2-1,1>>^ One who scatters has come up against you.^&#42;1^
Guard the fortifications.
Keep watch over the road.
Brace yourselves^&#42;2^ and muster all your strength.

[NOTE]
====
. That is, Nineveh.
. Lit., “Strengthen the hips.”
====

[[v34-2-2]]

^<<v34-2-2,2>>^ For Jehovah will restore the pride of Jacob,
Along with the pride of Israel,
For the devastators have devastated them;
And they have ruined their shoots.

[[v34-2-3]]

^<<v34-2-3,3>>^ The shields of his mighty men are dyed red,
His warriors are dressed in crimson.
The iron fittings of his war chariots flash like fire
In the day he prepares for battle,
And the juniper spears are brandished.

[[v34-2-4]]

^<<v34-2-4,4>>^ The war chariots race madly through the streets.
They rush up and down the public squares.
They shine like burning torches and flash like lightning.

[[v34-2-5]]

^<<v34-2-5,5>>^ He will summon his officers.
They will stumble as they advance.
They rush to her wall;
They set up the barricade.

[[v34-2-6]]

^<<v34-2-6,6>>^ The gates of the rivers will be opened,
And the palace will be dissolved.^&#42;1^

[NOTE]
====
. Or “will collapse.”
====

[[v34-2-7]]

^<<v34-2-7,7>>^ It has been decreed:^&#42;1^ She is exposed,
She is carried away, and her slave girls moan;
They sound like doves as they beat their breasts.^&#42;2^

[NOTE]
====
. Or “fixed.”
. Lit., “hearts.”
====

[[v34-2-8]]

^<<v34-2-8,8>>^ Throughout her days Ninʹe·veh was like a pool of waters,
But now they are fleeing.
“Stand still! Stand still!”
But no one is turning back.

[[v34-2-9]]

^<<v34-2-9,9>>^ Plunder silver, plunder gold!
There is no end to the treasures.
It is stocked with all sorts of precious things.

[[v34-2-10]]

^<<v34-2-10,10>>^ The city is empty, desolate, devastated!
Their hearts melt in fear, their knees buckle, their hips tremble;
All their faces are flushed.

[[v34-2-11]]

^<<v34-2-11,11>>^ Where is the lair of lions, where the young lions^&#42;1^ feed,
Where the lion goes out leading its cub,
With no one to make them afraid?

[NOTE]
====
. Or “maned young lions.”
====

[[v34-2-12]]

^<<v34-2-12,12>>^ The lion tore apart enough prey for his cubs
And strangled for his lionesses.
He kept his dens filled with prey,
His lairs with torn animals.

[[v34-2-13]]

^<<v34-2-13,13>>^ “Look! I am against you,” declares Jehovah of armies,
“I will burn up her war chariots in smoke,
And the sword will devour your young lions.^&#42;1^
I will cut off your prey from the earth,
And the sound of your messengers will be heard no more.”

[NOTE]
====
. Or “maned young lions.”
====

'''

xref:034-nahum/034-nahum-001.adoc#v34-1-0[&#60; Capítulo Anterior] | <<v34-2-0,Topo>> | xref:034-nahum/034-nahum-003.adoc#v34-3-0[Próximo Capítulo &#62;]