include::./index.adoc[]

[[v34-1-0]]
=== Nahum, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v34-1-1]]

^<<v34-1-1,1>>^ A pronouncement against Ninʹe·veh: The book of the vision of Naʹhum^&#42;1^ the Elʹkosh·ite:

[NOTE]
====
. Meaning “Comforter.”
====

[[v34-1-2]]

^<<v34-1-2,2>>^ Jehovah is a God who requires exclusive devotion and takes vengeance;
Jehovah takes vengeance and is ready to express his wrath.
Jehovah takes vengeance against his foes,
And he stores up wrath for his enemies.

[[v34-1-3]]

^<<v34-1-3,3>>^ Jehovah is slow to anger and great in power,
But by no means will Jehovah hold back due punishment.
His path is in destructive wind and storm,
And the clouds are the dust of his feet.

[[v34-1-4]]

^<<v34-1-4,4>>^ He rebukes the sea, and he dries it up;
And he makes all the rivers run dry.
Baʹshan and Carʹmel wither,
And the blossoms of Lebʹa·non wither.

[[v34-1-5]]

^<<v34-1-5,5>>^ Mountains quake because of him,
And the hills melt.
The earth will be in an upheaval because of his face,
Along with the land and all those dwelling in it.

[[v34-1-6]]

^<<v34-1-6,6>>^ Who can stand before his indignation?
And who can withstand the heat of his anger?
His wrath will be poured out like fire,
And the rocks will be shattered because of him.

[[v34-1-7]]

^<<v34-1-7,7>>^ Jehovah is good, a stronghold in the day of distress.
He is mindful of^&#42;1^ those seeking refuge in him.

[NOTE]
====
. Or “takes care of.” Lit., “knows.”
====

[[v34-1-8]]

^<<v34-1-8,8>>^ With a sweeping flood he will make a complete extermination of her^&#42;1^ place,
And darkness will pursue his enemies.

[NOTE]
====
. That is, Nineveh’s.
====

[[v34-1-9]]

^<<v34-1-9,9>>^ What will you plot against Jehovah?
He is causing a complete extermination.
Distress will not arise a second time.

[[v34-1-10]]

^<<v34-1-10,10>>^ For they are interwoven like thorns,
And they are like those drunk with beer;^&#42;1^
But they will be consumed like dry stubble.

[NOTE]
====
. Or “wheat beer.”
====

[[v34-1-11]]

^<<v34-1-11,11>>^ From you will come one who plots evil against Jehovah,
Giving worthless advice.

[[v34-1-12]]

^<<v34-1-12,12>>^ This is what Jehovah says:
“Though they were at full strength and numerous,
Even so they will be cut down and will pass away.^&#42;1^
I have afflicted you,^&#42;2^ but I will afflict you no more.

[NOTE]
====
. Or possibly, “and he will pass through.”
. That is, Judah.
====

[[v34-1-13]]

^<<v34-1-13,13>>^ And now I will break his yoke bar from off you,
And I will tear your bonds in two.

[[v34-1-14]]

^<<v34-1-14,14>>^ Jehovah has commanded concerning you,^&#42;1^
‘Your name will not be perpetuated further.
I will do away with the carved images and metal statues^&#42;2^ from the house^&#42;3^ of your gods.
I will make a grave for you, because you are contemptible.’

[NOTE]
====
. That is, Assyria.
. Or “molten statues.”
. Or “temple.”
====

[[v34-1-15]]

^<<v34-1-15,15>>^ Look! On the mountains are the feet of one bringing good news,
The one proclaiming peace.
Celebrate your festivals, O Judah, pay your vows,
For the worthless one will never pass through you again.
He will be utterly destroyed.”

'''

xref:033-micah/033-micah-007.adoc#v33-7-0[&#60; Capítulo Anterior] | <<v34-1-0,Topo>> | xref:034-nahum/034-nahum-002.adoc#v34-2-0[Próximo Capítulo &#62;]