include::./index.adoc[]

[[v34-3-0]]
=== Nahum, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v34-3-1]]

^<<v34-3-1,1>>^ Woe to the city of bloodshed!
She is completely full of deception and robbery.
She is never without prey!

[[v34-3-2]]

^<<v34-3-2,2>>^ There is the crack of the whip and the rattle of wheels,
The dashing horse and the bounding chariot.

[[v34-3-3]]

^<<v34-3-3,3>>^ The mounted horseman, the flashing sword, and the glittering spear,
The multitude of the slain and the heaps of carcasses
—There is no end to the dead bodies.
They keep stumbling over the dead bodies.

[[v34-3-4]]

^<<v34-3-4,4>>^ This is because of the many acts of prostitution of the prostitute,
She who is attractive and charming, a mistress of sorceries,
Who ensnares nations by her prostitution and families by her sorceries.

[[v34-3-5]]

^<<v34-3-5,5>>^ “Look! I am against you,”^&#42;1^ declares Jehovah of armies,
“I will lift your skirts up over your face;
I will cause nations to see your nakedness,
And kingdoms your disgrace.

[NOTE]
====
. That is, Nineveh.
====

[[v34-3-6]]

^<<v34-3-6,6>>^ And I will throw filth on you
And make you despicable;
I will make a spectacle of you.

[[v34-3-7]]

^<<v34-3-7,7>>^ Everyone who sees you will flee from you and say,
‘Ninʹe·veh has been devastated!
Who will sympathize with her?’
Where will I find comforters for you?

[[v34-3-8]]

^<<v34-3-8,8>>^ Are you better than No-aʹmon,^&#42;1^ which sat by the Nile canals?
Waters surrounded her;
Her wealth was the sea and her wall was the sea.

[NOTE]
====
. That is, Thebes.
====

[[v34-3-9]]

^<<v34-3-9,9>>^ E·thi·oʹpi·a was her source of boundless strength, also Egypt.
Put and the Libʹy·ans were your helpers.

[[v34-3-10]]

^<<v34-3-10,10>>^ But even she became an exile;
She went into captivity.
Her children also were dashed to pieces on every street corner.^&#42;1^
They cast lots over her honored men,
And all her great men have been bound with fetters.

[NOTE]
====
. Lit., “at the head of all streets.”
====

[[v34-3-11]]

^<<v34-3-11,11>>^ You will also become drunk;
You will go into hiding.
You will seek refuge from the enemy.

[[v34-3-12]]

^<<v34-3-12,12>>^ All your fortifications are like fig trees with the first ripe fruits;
If they are shaken, they will fall into the mouth of devourers.

[[v34-3-13]]

^<<v34-3-13,13>>^ Look! Your troops are like women in your midst.
The gates of your land will be wide open for your enemies.
Fire will consume the bars of your gates.

[[v34-3-14]]

^<<v34-3-14,14>>^ Draw water for the siege!
Strengthen your fortifications.
Go down into the mire and tread the clay;
Grab hold of the brick mold.

[[v34-3-15]]

^<<v34-3-15,15>>^ Even there fire will consume you.
A sword will cut you down.
It will devour you as the young locusts do.
Make yourself as numerous as the young locusts!
Yes, make yourself as numerous as the locusts!

[[v34-3-16]]

^<<v34-3-16,16>>^ You have multiplied your merchants more than the stars of the heavens.
The young locust strips off its skin and flies away.

[[v34-3-17]]

^<<v34-3-17,17>>^ Your guards are like the locust,
And your officers like a locust swarm.
They camp in the stone pens on a cold day,
But when the sun shines, they fly away;
And no one knows where they are.

[[v34-3-18]]

^<<v34-3-18,18>>^ Your shepherds are drowsy, O king of As·syrʹi·a;
Your nobles stay in their residences.
Your people are scattered on the mountains,
And no one is gathering them together.

[[v34-3-19]]

^<<v34-3-19,19>>^ There is no relief for your catastrophe.
Your wound is beyond healing.
All those hearing the report about you will clap their hands;
For who has not suffered from your relentless cruelty?”

'''

xref:034-nahum/034-nahum-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:035-habakkuk/035-habakkuk-001.adoc#v35-1-0[Próximo Capítulo &#62;]