include::./index.adoc[]

[[v52-1-0]]
=== The First to the Thessalonians, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v52-1-1]]

^<<v52-1-1,1>>^ Paul, Sil·vaʹnus,^&#42;1^ and Timothy, to the congregation of the Thes·sa·loʹni·ans in union with God the Father and the Lord Jesus Christ:
May you have undeserved kindness and peace.

[NOTE]
====
. Also called Silas.
====

[[v52-1-2]]

^<<v52-1-2,2>>^ We always thank God when we mention all of you in our prayers,

[[v52-1-3]]

^<<v52-1-3,3>>^ for we continually remember your faithful work, your loving labor, and your endurance because of your hope in our Lord Jesus Christ in the presence of our God and Father.

[[v52-1-4]]

^<<v52-1-4,4>>^ For we know, brothers loved by God, his choosing of you,

[[v52-1-5]]

^<<v52-1-5,5>>^ because the good news we preach did not come to you with speech alone but also with power and with holy spirit and with strong conviction, just as you know what sort of men we became among you for your sakes.

[[v52-1-6]]

^<<v52-1-6,6>>^ And you became imitators of us and of the Lord, seeing that you accepted the word under much tribulation with joy of holy spirit,

[[v52-1-7]]

^<<v52-1-7,7>>^ so that you became an example to all the believers in Mac·e·doʹni·a and in A·chaʹia.

[[v52-1-8]]

^<<v52-1-8,8>>^ The fact is, not only has the word of Jehovah^&#42;1^ sounded out from you in Mac·e·doʹni·a and A·chaʹia but your faith in God has spread abroad in every place, so that we do not need to say anything.

[NOTE]
====
. See App. A5.
====

[[v52-1-9]]

^<<v52-1-9,9>>^ For they themselves keep reporting about our first contact with you and how you turned to God from your idols to slave for a living and true God,

[[v52-1-10]]

^<<v52-1-10,10>>^ and to wait for his Son from the heavens, whom he raised up from the dead, namely, Jesus, who rescues us from the wrath that is coming.

'''

xref:051-colossians/051-colossians-004.adoc#v51-4-0[&#60; Capítulo Anterior] | <<v52-1-0,Topo>> | xref:052-1-thessalonians/052-1-thessalonians-002.adoc#v52-2-0[Próximo Capítulo &#62;]