include::./index.adoc[]

[[v52-4-0]]
=== The First to the Thessalonians, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v52-4-1]]

^<<v52-4-1,1>>^ Finally, brothers, just as you received instruction from us on how you should walk in order to please God, just as you are in fact walking, we request you and appeal to you by the Lord Jesus to keep doing it more fully.

[[v52-4-2]]

^<<v52-4-2,2>>^ For you know the instructions^&#42;1^ we gave you through the Lord Jesus.

[NOTE]
====
. Or “orders.”
====

[[v52-4-3]]

^<<v52-4-3,3>>^ For this is the will of God, that you should be holy and abstain from sexual immorality.^&#42;1^

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
====

[[v52-4-4]]

^<<v52-4-4,4>>^ Each one of you should know how to control his own body^&#42;1^ in holiness and honor,

[NOTE]
====
. Lit., “vessel.”
====

[[v52-4-5]]

^<<v52-4-5,5>>^ not with greedy, uncontrolled sexual passion like the nations have that do not know God.

[[v52-4-6]]

^<<v52-4-6,6>>^ No one should go beyond proper limits and take advantage of his brother in this matter, because Jehovah^&#42;1^ exacts punishment for all these things, just as we told you previously and also strongly warned you.

[NOTE]
====
. See App. A5.
====

[[v52-4-7]]

^<<v52-4-7,7>>^ For God has called us, not for uncleanness, but for holiness.

[[v52-4-8]]

^<<v52-4-8,8>>^ So, then, the man who disregards this is disregarding, not man, but God, who gives you his holy spirit.

[[v52-4-9]]

^<<v52-4-9,9>>^ However, concerning brotherly love, you do not need us to write to you, for you yourselves are taught by God to love one another.

[[v52-4-10]]

^<<v52-4-10,10>>^ In fact, you are doing so toward all the brothers in all of Mac·e·doʹni·a. But we urge you, brothers, to go on doing so in fuller measure.

[[v52-4-11]]

^<<v52-4-11,11>>^ Make it your aim to live quietly and to mind your own business and to work with your hands, just as we instructed you,

[[v52-4-12]]

^<<v52-4-12,12>>^ so that you may walk decently in the eyes of people outside and not need anything.

[[v52-4-13]]

^<<v52-4-13,13>>^ Moreover, brothers, we do not want you to be ignorant^&#42;1^ about those who are sleeping in death, so that you may not sorrow as the rest do who have no hope.

[NOTE]
====
. Or “uninformed.”
====

[[v52-4-14]]

^<<v52-4-14,14>>^ For if we have faith that Jesus died and rose again, so too God will bring with him those who have fallen asleep in death through Jesus.

[[v52-4-15]]

^<<v52-4-15,15>>^ For this is what we tell you by Jehovah’s^&#42;1^ word, that we the living who survive to the presence of the Lord will in no way precede those who have fallen asleep in death;

[NOTE]
====
. See App. A5.
====

[[v52-4-16]]

^<<v52-4-16,16>>^ because the Lord himself will descend from heaven with a commanding call, with an archangel’s voice and with God’s trumpet, and those who are dead in union with Christ will rise first.

[[v52-4-17]]

^<<v52-4-17,17>>^ Afterward we the living who are surviving will, together with them, be caught away in clouds to meet the Lord in the air; and thus we will always be with the Lord.

[[v52-4-18]]

^<<v52-4-18,18>>^ So keep comforting one another with these words.

'''

xref:052-1-thessalonians/052-1-thessalonians-003.adoc#v52-3-0[&#60; Capítulo Anterior] | <<v52-4-0,Topo>> | xref:052-1-thessalonians/052-1-thessalonians-005.adoc#v52-5-0[Próximo Capítulo &#62;]