include::./index.adoc[]

[[v52-2-0]]
=== The First to the Thessalonians, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v52-2-1]]

^<<v52-2-1,1>>^ You yourselves surely know, brothers, that our visit to you has not been without results.

[[v52-2-2]]

^<<v52-2-2,2>>^ For although we had first suffered and been insolently treated in Phi·lipʹpi, as you know, we mustered up boldness^&#42;1^ by means of our God to tell you the good news of God in the face of much opposition.^&#42;2^

[NOTE]
====
. Or “courage.”
. Or possibly, “amid much struggling.”
====

[[v52-2-3]]

^<<v52-2-3,3>>^ For the exhortation we give does not spring from error or from uncleanness or with deceit,

[[v52-2-4]]

^<<v52-2-4,4>>^ but just as we have been approved by God to be entrusted with the good news, so we speak to please, not men, but God, who examines our hearts.

[[v52-2-5]]

^<<v52-2-5,5>>^ In fact, you know that we never used flattering speech or put on any false front with greedy motives; God is witness!

[[v52-2-6]]

^<<v52-2-6,6>>^ Nor have we been seeking glory from men, either from you or from others, though we could be an expensive burden as apostles of Christ.

[[v52-2-7]]

^<<v52-2-7,7>>^ On the contrary, we became gentle in your midst, as when a nursing mother tenderly cares for^&#42;1^ her own children.

[NOTE]
====
. Or “cherishes.”
====

[[v52-2-8]]

^<<v52-2-8,8>>^ So having tender affection for you, we were determined^&#42;1^ to impart to you, not only the good news of God but also our very selves,^&#42;2^ because you became so beloved to us.

[NOTE]
====
. Lit., “well-pleased.”
. Or “souls.”
====

[[v52-2-9]]

^<<v52-2-9,9>>^ Surely you remember, brothers, our labor and toil. We were working night and day, so that we would not put an expensive burden on any one of you, when we preached the good news of God to you.

[[v52-2-10]]

^<<v52-2-10,10>>^ You are witnesses, God is also, of how loyal and righteous and blameless we behaved toward you believers.

[[v52-2-11]]

^<<v52-2-11,11>>^ You well know that we kept exhorting and consoling you and bearing witness to each one of you, just as a father does his children,

[[v52-2-12]]

^<<v52-2-12,12>>^ so that you would go on walking worthily of God, who is calling you to his Kingdom and glory.

[[v52-2-13]]

^<<v52-2-13,13>>^ Indeed, that is why we also thank God unceasingly, because when you received God’s word, which you heard from us, you accepted it not as the word of men but, just as it truthfully is, as the word of God, which is also at work in you believers.

[[v52-2-14]]

^<<v52-2-14,14>>^ For you, brothers, became imitators of the congregations of God in union with Christ Jesus that are in Ju·deʹa, because you suffered at the hands of your own countrymen the same things that they also are suffering at the hands of the Jews,

[[v52-2-15]]

^<<v52-2-15,15>>^ who even killed the Lord Jesus and the prophets and persecuted us. Furthermore, they are not pleasing God, but are against the interests of all men,

[[v52-2-16]]

^<<v52-2-16,16>>^ as they try to prevent us from speaking to people of the nations so that these might be saved. In this way they always fill up the measure of their sins. But his wrath has at last come upon them.

[[v52-2-17]]

^<<v52-2-17,17>>^ But when we were separated from^&#42;1^ you, brothers, for just a short time (in person, not in our hearts), because of our strong desire, we made every effort to see you in person.^&#42;2^

[NOTE]
====
. Or “bereaved of.”
. Lit., “to see your face.”
====

[[v52-2-18]]

^<<v52-2-18,18>>^ For this reason we wanted to come to you, yes I, Paul, tried not just once but twice; yet Satan cut across our path.

[[v52-2-19]]

^<<v52-2-19,19>>^ For what is our hope or joy or crown of exultation before our Lord Jesus at his presence? Is it not in fact you?

[[v52-2-20]]

^<<v52-2-20,20>>^ You certainly are our glory and joy.

'''

xref:052-1-thessalonians/052-1-thessalonians-001.adoc#v52-1-0[&#60; Capítulo Anterior] | <<v52-2-0,Topo>> | xref:052-1-thessalonians/052-1-thessalonians-003.adoc#v52-3-0[Próximo Capítulo &#62;]