include::./index.adoc[]

[[v33-1-0]]
=== Micah, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v33-1-1]]

^<<v33-1-1,1>>^ The word of Jehovah that came to Miʹcah^&#42;1^ of Moʹresh·eth, in the days of Joʹtham, Aʹhaz, and Hez·e·kiʹah, kings of Judah, and that he received in a vision concerning Sa·marʹi·a and Jerusalem:

[NOTE]
====
. A shortened form of Michael (meaning “Who Is Like God?”) or Micaiah (meaning “Who Is Like Jehovah?”).
====

[[v33-1-2]]

^<<v33-1-2,2>>^ “Hear, all you peoples!
Pay attention, O earth and what fills you,
And let the Sovereign Lord Jehovah serve as a witness against you
—Jehovah from his holy temple.

[[v33-1-3]]

^<<v33-1-3,3>>^ For look! Jehovah is going out from his place;
He will come down and tread on earth’s high places.

[[v33-1-4]]

^<<v33-1-4,4>>^ The mountains will melt under him,
And the valleys^&#42;1^ will split apart
Like wax before the fire,
Like waters poured down a steep slope.

[NOTE]
====
. Or “low plains.”
====

[[v33-1-5]]

^<<v33-1-5,5>>^ All of this is because of the revolt of Jacob,
Because of the sins of the house of Israel.
What is the revolt of Jacob?
Is it not Sa·marʹi·a?
And what are the high places of Judah?
Are they not Jerusalem?

[[v33-1-6]]

^<<v33-1-6,6>>^ I will make Sa·marʹi·a a heap of ruins of the field,
A place for planting vineyards;
I will hurl^&#42;1^ her stones down into the valley,
And I will lay bare her foundations.

[NOTE]
====
. Lit., “pour.”
====

[[v33-1-7]]

^<<v33-1-7,7>>^ All her graven images will be crushed to pieces,
And all the gifts for which she hired herself out^&#42;1^ will be burned in the fire.
I will devastate all her idols.
For she collected them from the wages of prostitution,
And they will again become the wages of prostitutes.”

[NOTE]
====
. Or “all the wages of her prostitution.”
====

[[v33-1-8]]

^<<v33-1-8,8>>^ Because of this I will wail and howl;
I will walk barefoot and naked.
My wailing will be like that of jackals,
And my mourning like that of ostriches.

[[v33-1-9]]

^<<v33-1-9,9>>^ For her wound cannot be healed;
It has come as far as Judah.
The plague has spread to the gate of my people, to Jerusalem.

[[v33-1-10]]

^<<v33-1-10,10>>^ “Do not announce it in Gath;
You must not weep at all.
In Beth-aphʹrah^&#42;1^ roll in the dust.

[NOTE]
====
. Or “In the house of Aphrah.”
====

[[v33-1-11]]

^<<v33-1-11,11>>^ Cross over in nakedness and shame, O inhabitants^&#42;1^ of Shaʹphir.
The inhabitants^&#42;2^ of Zaʹa·nan have not come out.
There will be wailing in Beth-eʹzel, and it will take its support away from you.

[NOTE]
====
. Lit., “inhabitress.”
. Lit., “inhabitress.”
====

[[v33-1-12]]

^<<v33-1-12,12>>^ For the inhabitants^&#42;1^ of Maʹroth have waited for good,
But what is bad has come down from Jehovah to the gate of Jerusalem.

[NOTE]
====
. Lit., “inhabitress.”
====

[[v33-1-13]]

^<<v33-1-13,13>>^ Harness the chariot to the team of horses, O inhabitants^&#42;1^ of Laʹchish.
You were the beginning of sin to the daughter of Zion,
For in you were found the revolts of Israel.

[NOTE]
====
. Lit., “inhabitress.”
====

[[v33-1-14]]

^<<v33-1-14,14>>^ So you will give parting^&#42;1^ gifts to Moʹresh·eth-gath.
The houses of Achʹzib were something deceitful to the kings of Israel.

[NOTE]
====
. Or “farewell.”
====

[[v33-1-15]]

^<<v33-1-15,15>>^ The conqueror^&#42;1^ I will yet bring in to you, O inhabitants^&#42;2^ of Ma·reʹshah.
As far as A·dulʹlam the glory of Israel will come.

[NOTE]
====
. Or “dispossessor.”
. Lit., “inhabitress.”
====

[[v33-1-16]]

^<<v33-1-16,16>>^ Make yourselves bald and shear off your hair for your cherished children.
Make yourselves as bald as an eagle,
For they have been taken away from you into exile.”

'''

xref:032-jonah/032-jonah-004.adoc#v32-4-0[&#60; Capítulo Anterior] | <<v33-1-0,Topo>> | xref:033-micah/033-micah-002.adoc#v33-2-0[Próximo Capítulo &#62;]