include::./index.adoc[]

[[v33-6-0]]
=== Micah, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v33-6-1]]

^<<v33-6-1,1>>^ Hear, please, what Jehovah is saying.
Get up, present a legal case before the mountains,
And may the hills hear your voice.

[[v33-6-2]]

^<<v33-6-2,2>>^ Hear, O mountains, the legal case of Jehovah,
You firm foundations of the earth,
For Jehovah has a legal case with his people;
It is against Israel that he will argue:

[[v33-6-3]]

^<<v33-6-3,3>>^ “My people, what have I done to you?
How have I tired you out?
Testify against me.

[[v33-6-4]]

^<<v33-6-4,4>>^ For I brought you up out of the land of Egypt,
From the house of slavery I redeemed you;
I sent before you Moses, Aaron, and Mirʹi·am.

[[v33-6-5]]

^<<v33-6-5,5>>^ My people, remember, please, what King Baʹlak of Moʹab proposed,
And what Baʹlaam the son of Beʹor answered him
—What took place from Shitʹtim to Gilʹgal—
So that you may know the righteous acts of Jehovah.”

[[v33-6-6]]

^<<v33-6-6,6>>^ With what will I come before Jehovah?
With what will I bow before God on high?
Will I come before him with whole burnt offerings,
With year-old calves?

[[v33-6-7]]

^<<v33-6-7,7>>^ Will Jehovah be pleased with thousands of rams,
With tens of thousands of torrents of oil?
Will I give my firstborn son for my revolt,
The fruit of my body for my sin?^&#42;1^

[NOTE]
====
. Or “for the sin of my soul?”
====

[[v33-6-8]]

^<<v33-6-8,8>>^ He has told you, O man, what is good.
And what is Jehovah requiring^&#42;1^ of you?
Only to exercise justice,^&#42;2^ to cherish loyalty,^&#42;3^
And to walk in modesty with your God!

[NOTE]
====
. Or “asking back.”
. Or “to be just; to be fair.”
. Or “to be kind and loyal in your love.” Lit., “to love loyal love.”
====

[[v33-6-9]]

^<<v33-6-9,9>>^ The voice of Jehovah calls out to the city;
Those with practical wisdom will fear your name.
Pay attention to the rod and to the one who appointed it.

[[v33-6-10]]

^<<v33-6-10,10>>^ Are there still the treasures of wickedness in the house of the wicked
And the incomplete eʹphah measure^&#42;1^ that is detestable?

[NOTE]
====
. See App. B14.
====

[[v33-6-11]]

^<<v33-6-11,11>>^ Can I be morally clean^&#42;1^ with wicked scales,
With a bag of fraudulent stone weights?

[NOTE]
====
. Or “be innocent.”
====

[[v33-6-12]]

^<<v33-6-12,12>>^ For her rich men are full of violence,
And her inhabitants speak lies;
Their tongue is deceitful in their mouth.

[[v33-6-13]]

^<<v33-6-13,13>>^ “Therefore, I will wound you by striking you,
Making you desolate because of your sins.

[[v33-6-14]]

^<<v33-6-14,14>>^ You will eat but not be satisfied;
You will be empty inside.
What you remove, you will not carry off safely,
And what you do carry off, I will give to the sword.

[[v33-6-15]]

^<<v33-6-15,15>>^ You will sow seed, but you will not reap.
You will tread olives, but you will not use the oil;
And you will make new wine, but you will drink no wine.

[[v33-6-16]]

^<<v33-6-16,16>>^ For you observe the statutes of Omʹri and all the work of the house of Aʹhab,
And you walk in accord with their advice.
That is why I will make you an object of horror
And her inhabitants something to be whistled at;
And you will bear the scorn of the peoples.”

'''

xref:033-micah/033-micah-005.adoc#v33-5-0[&#60; Capítulo Anterior] | <<v33-6-0,Topo>> | xref:033-micah/033-micah-007.adoc#v33-7-0[Próximo Capítulo &#62;]