include::./index.adoc[]

[[v33-2-0]]
=== Micah, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v33-2-1]]

^<<v33-2-1,1>>^ “Woe to those who scheme what is harmful,
Who work out evil on their beds!
When morning light comes they carry it out,
Because it is in the power of their hand.

[[v33-2-2]]

^<<v33-2-2,2>>^ They desire fields and seize them;
Also houses, and they take them;
They defraud a man of his house,
A man of his inheritance.

[[v33-2-3]]

^<<v33-2-3,3>>^ Therefore this is what Jehovah says:
‘Here I am devising against this family a calamity from which you will not escape.^&#42;1^
You will no longer walk haughtily, for it is a time of calamity.

[NOTE]
====
. Lit., “you will not remove your necks.”
====

[[v33-2-4]]

^<<v33-2-4,4>>^ In that day people will recite a proverb concerning you,
And they will bitterly lament over you.
They will say: “We are completely devastated!
He caused the portion of my people to change hands—how he removes it from me!
To the unfaithful one he assigns our fields.”

[[v33-2-5]]

^<<v33-2-5,5>>^ So you will have no one to stretch the measuring cord,
To allot the land in the congregation of Jehovah.

[[v33-2-6]]

^<<v33-2-6,6>>^ “Stop preaching!” they preach,
“They should not preach these things;
Humiliation will not overtake us!”

[[v33-2-7]]

^<<v33-2-7,7>>^ Is it being said, O house of Jacob:
“Has the spirit of Jehovah become impatient?
Are these his deeds?”
Do not my own words bring good to those walking uprightly?

[[v33-2-8]]

^<<v33-2-8,8>>^ But lately my own people have risen up as an enemy.
You openly strip off the majestic ornament with^&#42;1^ the garment
From those passing by confidently, like those returning from war.

[NOTE]
====
. Or possibly, “from.”
====

[[v33-2-9]]

^<<v33-2-9,9>>^ You drive the women of my people out from their delightful houses;
From their children you take away my splendor forever.

[[v33-2-10]]

^<<v33-2-10,10>>^ Get up and go, for this is no place of rest.
Because of uncleanness, there is destruction, grievous destruction.

[[v33-2-11]]

^<<v33-2-11,11>>^ If a man walks after wind and deception and tells this lie:
“I will preach to you about wine and alcoholic drink,”
Then he would be just the preacher for this people!

[[v33-2-12]]

^<<v33-2-12,12>>^ I will certainly gather all of you, O Jacob;
I will surely collect the remaining ones of Israel together.
In unity I will place them, like sheep in the pen,
Like a flock in its pasture;
It will be noisy with people.’

[[v33-2-13]]

^<<v33-2-13,13>>^ The one breaking out will go before them;
They will break out and pass through the gate and go out by it.
Their king will pass through before them,
With Jehovah at their head.”

'''

xref:033-micah/033-micah-001.adoc#v33-1-0[&#60; Capítulo Anterior] | <<v33-2-0,Topo>> | xref:033-micah/033-micah-003.adoc#v33-3-0[Próximo Capítulo &#62;]