include::./index.adoc[]

[[v33-5-0]]
=== Micah, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v33-5-1]]

^<<v33-5-1,1>>^ “Now you are slashing yourself,
O daughter under attack;
A siege is laid against us.
With a rod they strike the judge of Israel on the cheek.

[[v33-5-2]]

^<<v33-5-2,2>>^ And you, O Bethʹle·hem Ephʹra·thah,
The one too little to be among the thousands^&#42;1^ of Judah,
From you will come out for me the one to be ruler in Israel,
Whose origin is from ancient times, from the days of long ago.

[NOTE]
====
. Or “clans.”
====

[[v33-5-3]]

^<<v33-5-3,3>>^ So he will give them up
Until the time that she who is to give birth has given birth.
And the rest of his brothers will return to the people of Israel.

[[v33-5-4]]

^<<v33-5-4,4>>^ He will stand up and shepherd in the strength of Jehovah,
In the superiority of the name of Jehovah his God.
And they will dwell in security,
For now his greatness will reach the ends of the earth.

[[v33-5-5]]

^<<v33-5-5,5>>^ And he will bring peace.
Should the As·syrʹi·an invade our land and tread on our fortified towers,
We will raise up against him seven shepherds, yes, eight princes^&#42;1^ of mankind.

[NOTE]
====
. Or “leaders.”
====

[[v33-5-6]]

^<<v33-5-6,6>>^ They will shepherd the land of As·syrʹi·a with the sword,
And the land of Nimʹrod at its entrances.
And he will rescue us from the As·syrʹi·an,
When he invades our land and treads on our territory.

[[v33-5-7]]

^<<v33-5-7,7>>^ The remaining ones of Jacob will be in the midst of many peoples
Like dew from Jehovah,
Like showers of rain on vegetation
That do not put hope in man
Or wait for the sons of men.

[[v33-5-8]]

^<<v33-5-8,8>>^ The remaining ones of Jacob will be among the nations,
In the midst of many peoples,
Like a lion among the beasts of a forest,
Like a young lion^&#42;1^ among flocks of sheep,
That passes through and pounces and tears in pieces;
And there is no one to rescue them.

[NOTE]
====
. Or “a maned young lion.”
====

[[v33-5-9]]

^<<v33-5-9,9>>^ Your hand will be raised over your adversaries,
And all your enemies will be destroyed.”

[[v33-5-10]]

^<<v33-5-10,10>>^ “In that day,” declares Jehovah,
“I will do away with your horses from your midst and destroy your chariots.

[[v33-5-11]]

^<<v33-5-11,11>>^ I will destroy the cities of your land
And tear down all your fortified places.

[[v33-5-12]]

^<<v33-5-12,12>>^ I will put an end to the sorcery you practice,^&#42;1^
And no one practicing magic will remain among you.

[NOTE]
====
. Lit., “from your hand.”
====

[[v33-5-13]]

^<<v33-5-13,13>>^ I will destroy your graven images and your pillars from your midst,
And you will no longer bow down to the work of your hands.

[[v33-5-14]]

^<<v33-5-14,14>>^ I will uproot your sacred poles^&#42;1^ from your midst
And annihilate your cities.

[NOTE]
====
. See Glossary.
====

[[v33-5-15]]

^<<v33-5-15,15>>^ In anger and wrath I will execute vengeance
On the nations that have not obeyed.”

'''

xref:033-micah/033-micah-004.adoc#v33-4-0[&#60; Capítulo Anterior] | <<v33-5-0,Topo>> | xref:033-micah/033-micah-006.adoc#v33-6-0[Próximo Capítulo &#62;]