include::./index.adoc[]

[[v33-3-0]]
=== Micah, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v33-3-1]]

^<<v33-3-1,1>>^ I said: “Hear, please, you heads of Jacob
And you commanders of the house of Israel.
Should you not know what is just?

[[v33-3-2]]

^<<v33-3-2,2>>^ But you hate what is good and love what is bad;
You tear off the skin from my people and the flesh from their bones.

[[v33-3-3]]

^<<v33-3-3,3>>^ You also eat the flesh of my people
And strip off their skin,
Smashing their bones, crushing them to pieces,
Like what is cooked in a pot,^&#42;1^ like meat in a cooking pot.

[NOTE]
====
. Or “wide-mouthed cooking pot.”
====

[[v33-3-4]]

^<<v33-3-4,4>>^ At that time they will call to Jehovah for help,
But he will not answer them.
He will hide his face from them at that time,
Because of their wicked deeds.

[[v33-3-5]]

^<<v33-3-5,5>>^ This is what Jehovah says against the prophets who are leading my people astray,
Who proclaim ‘Peace!’ while they bite^&#42;1^ with their teeth
But who declare^&#42;2^ war against him who puts nothing into their mouths:

[NOTE]
====
. Or possibly, “when they have something to chew.”
. Lit., “sanctify.”
====

[[v33-3-6]]

^<<v33-3-6,6>>^ ‘You will have night; there will be no vision;
There will only be darkness for you, no divination.
The sun will set on the prophets,
And the day will turn dark for them.

[[v33-3-7]]

^<<v33-3-7,7>>^ The visionaries will be put to shame,
And the diviners will be disappointed.
All of them will have to cover over the mustache,^&#42;1^
For there is no answer from God.’”

[NOTE]
====
. Or “cover their mouths.”
====

[[v33-3-8]]

^<<v33-3-8,8>>^ As for me, I am filled with power by the spirit of Jehovah,
And with justice and might,
To tell to Jacob his revolt and to Israel his sin.

[[v33-3-9]]

^<<v33-3-9,9>>^ Hear this, please, you heads of the house of Jacob
And you commanders of the house of Israel,
Who detest justice and who make crooked all that is straight,

[[v33-3-10]]

^<<v33-3-10,10>>^ Who build Zion with bloodshed and Jerusalem with unrighteousness.

[[v33-3-11]]

^<<v33-3-11,11>>^ Her leaders^&#42;1^ judge for a bribe,
Her priests instruct for a price,
And her prophets practice divination for money.^&#42;2^
And yet they lean on Jehovah,^&#42;3^ saying:
“Is not Jehovah with us?
No calamity will come upon us.”

[NOTE]
====
. Lit., “heads.”
. Or “silver.”
. Or “they claim to lean on Jehovah.”
====

[[v33-3-12]]

^<<v33-3-12,12>>^ So because of you,
Zion will be plowed up as a field,
Jerusalem will become heaps of ruins,
And the mountain of the House^&#42;1^ will become like high places in a forest.^&#42;2^

[NOTE]
====
. Or “the temple mount.”
. Or “like a wooded ridge.”
====

'''

xref:033-micah/033-micah-002.adoc#v33-2-0[&#60; Capítulo Anterior] | <<v33-3-0,Topo>> | xref:033-micah/033-micah-004.adoc#v33-4-0[Próximo Capítulo &#62;]