include::./index.adoc[]

[[v33-4-0]]
=== Micah, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v33-4-1]]

^<<v33-4-1,1>>^ In the final part of the days,^&#42;1^
The mountain of the house of Jehovah
Will become firmly established above the top of the mountains,
And it will be raised up above the hills,
And to it peoples will stream.

[NOTE]
====
. Or “In the last days.”
====

[[v33-4-2]]

^<<v33-4-2,2>>^ And many nations will go and say:
“Come, let us go up to the mountain of Jehovah
And to the house of the God of Jacob.
He will instruct us about his ways,
And we will walk in his paths.”
For law^&#42;1^ will go out of Zion,
And the word of Jehovah out of Jerusalem.

[NOTE]
====
. Or “instruction.”
====

[[v33-4-3]]

^<<v33-4-3,3>>^ He will render judgment among many peoples
And set matters straight^&#42;1^ respecting mighty nations far away.
They will beat their swords into plowshares
And their spears into pruning shears.
Nation will not lift up sword against nation,
Nor will they learn war anymore.

[NOTE]
====
. Or “correct matters.”
====

[[v33-4-4]]

^<<v33-4-4,4>>^ They will sit,^&#42;1^ each one under his vine and under his fig tree,
And no one will make them afraid,
For the mouth of Jehovah of armies has spoken.

[NOTE]
====
. Or “dwell.”
====

[[v33-4-5]]

^<<v33-4-5,5>>^ For all the peoples will walk, each in the name of its god,
But we will walk in the name of Jehovah our God forever and ever.

[[v33-4-6]]

^<<v33-4-6,6>>^ “In that day,” declares Jehovah,
“I will gather the one^&#42;1^ who was limping,
And collect together the dispersed one,
Along with those I treated harshly.

[NOTE]
====
. Lit., “her.”
====

[[v33-4-7]]

^<<v33-4-7,7>>^ I will make the one^&#42;1^ who was limping a remnant,
And the one far removed a mighty nation;
And Jehovah will rule as king over them in Mount Zion,
From now on and forever.

[NOTE]
====
. Lit., “her.”
====

[[v33-4-8]]

^<<v33-4-8,8>>^ As for you, O tower of the flock,
The mound of the daughter of Zion,
To you it will come, yes, the first^&#42;1^ dominion will come,
The kingdom belonging to the daughter of Jerusalem.

[NOTE]
====
. Or “former.”
====

[[v33-4-9]]

^<<v33-4-9,9>>^ Now why are you shouting loudly?
Have you no king,
Or has your adviser perished,
So that pain has seized you like a woman giving birth?

[[v33-4-10]]

^<<v33-4-10,10>>^ Writhe and groan, O daughter of Zion,
Like a woman giving birth,
For now you will go from the city and reside in the field.
You will go as far as to Babylon,
And there you will be rescued;
There Jehovah will buy you back from the hand of your enemies.

[[v33-4-11]]

^<<v33-4-11,11>>^ Now many nations will be gathered against you;
They will say, ‘Let her be defiled,
And let our eyes see this happen to Zion.’

[[v33-4-12]]

^<<v33-4-12,12>>^ But they do not know the thoughts of Jehovah,
They do not understand his purpose;^&#42;1^
For he will gather them like a row of newly cut grain to the threshing floor.

[NOTE]
====
. Or “counsel.”
====

[[v33-4-13]]

^<<v33-4-13,13>>^ Get up and thresh, O daughter of Zion;
For I will change your horns into iron,
And I will change your hooves into copper,
And you will pulverize many peoples.
You will devote their dishonest profit to Jehovah,
And their resources to the true Lord of the whole earth.”

'''

xref:033-micah/033-micah-003.adoc#v33-3-0[&#60; Capítulo Anterior] | <<v33-4-0,Topo>> | xref:033-micah/033-micah-005.adoc#v33-5-0[Próximo Capítulo &#62;]