include::./index.adoc[]

[[v33-7-0]]
=== Micah, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v33-7-1]]

^<<v33-7-1,1>>^ Woe to me! I am like one who,
After the gathering of summer fruit
And the gleaning following a grape harvest,
Finds no cluster of grapes to eat,
No early fig that I crave.^&#42;1^

[NOTE]
====
. Or “my soul craves.”
====

[[v33-7-2]]

^<<v33-7-2,2>>^ The loyal one has perished^&#42;1^ from the earth;
Among men there is no one upright.
All of them lie in ambush for bloodshed.
Each hunts his own brother with a dragnet.

[NOTE]
====
. Or “vanished.”
====

[[v33-7-3]]

^<<v33-7-3,3>>^ Their hands are expert at doing what is bad;
The prince is making demands,
The judge asks for a reward,
The prominent one makes known his desires,^&#42;1^
And they work it out together.^&#42;2^

[NOTE]
====
. Or “the craving of his soul.”
. Lit., “they weave it together.”
====

[[v33-7-4]]

^<<v33-7-4,4>>^ Their best one is like thorns,
Their most upright one is worse than a thorn hedge.
The day of your watchmen and of your reckoning will come.
Now they will panic.

[[v33-7-5]]

^<<v33-7-5,5>>^ Do not put faith in your companion
Or trust a close friend.
Guard what you say to the one who lies in your embrace.

[[v33-7-6]]

^<<v33-7-6,6>>^ For a son despises his father,
A daughter rises up against her mother,
And a daughter-in-law is against her mother-in-law;
A man’s enemies are the men of his household.

[[v33-7-7]]

^<<v33-7-7,7>>^ But as for me, I will keep on the lookout for Jehovah.
I will show a waiting attitude^&#42;1^ for the God of my salvation.
My God will hear me.

[NOTE]
====
. Or “I will wait patiently.”
====

[[v33-7-8]]

^<<v33-7-8,8>>^ Do not rejoice over me, O my enemy.^&#42;1^
Although I have fallen, I will rise up;
Although I dwell in the darkness, Jehovah will be my light.

[NOTE]
====
. In Hebrew, the word for “enemy” is in the feminine gender.
====

[[v33-7-9]]

^<<v33-7-9,9>>^ The wrath of Jehovah I will bear
—For I have sinned against him—
Until he pleads my legal case and brings about justice for me.
He will bring me out to the light;
I will look upon his righteousness.

[[v33-7-10]]

^<<v33-7-10,10>>^ My enemy will also see,
And shame will cover her who said to me:
“Where is Jehovah your God?”
My eyes will look upon her.
Now she will be trampled like mud in the streets.

[[v33-7-11]]

^<<v33-7-11,11>>^ It will be a day for building your stone walls;
On that day the boundary will be extended.^&#42;1^

[NOTE]
====
. Or possibly, “the decree will be far away.”
====

[[v33-7-12]]

^<<v33-7-12,12>>^ On that day they will come to you
All the way from As·syrʹi·a and the cities of Egypt,
From Egypt all the way to the River;^&#42;1^
From sea to sea and from mountain to mountain.

[NOTE]
====
. That is, the Euphrates.
====

[[v33-7-13]]

^<<v33-7-13,13>>^ And the land will become desolate because of its inhabitants,
As a result of what they have done.^&#42;1^

[NOTE]
====
. Lit., “Because of the fruitage of their deeds.”
====

[[v33-7-14]]

^<<v33-7-14,14>>^ Shepherd your people with your staff, the flock of your inheritance,
The one who was living alone in a forest—in the midst of an orchard.
Let them feed on Baʹshan and Gilʹe·ad as in the days of old.

[[v33-7-15]]

^<<v33-7-15,15>>^ “As in the days when you came out of the land of Egypt,
I will show him wonderful things.

[[v33-7-16]]

^<<v33-7-16,16>>^ Nations will see and be ashamed despite all their might.
They will put their hand over their mouth;
Their ears will become deaf.

[[v33-7-17]]

^<<v33-7-17,17>>^ They will lick the dust like serpents;
Like the reptiles of the earth they will come trembling out of their strongholds.
To Jehovah our God they will come in dread,
And they will be in fear of you.”

[[v33-7-18]]

^<<v33-7-18,18>>^ Who is a God like you,
Pardoning error and passing over the transgression of the remnant of his inheritance?
He will not hold onto his anger forever,
For he delights in loyal love.

[[v33-7-19]]

^<<v33-7-19,19>>^ He will again show us mercy; he will conquer^&#42;1^ our errors.
You will throw all their sins into the depths of the sea.

[NOTE]
====
. Or “tread down; subdue.”
====

[[v33-7-20]]

^<<v33-7-20,20>>^ You will show faithfulness to Jacob,
Loyal love to Abraham,
As you swore to our forefathers from the days of old.

'''

xref:033-micah/033-micah-006.adoc#v33-6-0[&#60; Capítulo Anterior] | <<v33-7-0,Topo>> | xref:034-nahum/034-nahum-001.adoc#v34-1-0[Próximo Capítulo &#62;]