include::./index.adoc[]

[[v23-30-0]]
=== Isaiah, 30
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-30-1]]

^<<v23-30-1,1>>^ “Woe to the stubborn sons,” declares Jehovah,
“Who carry out plans that are not mine,
Who make alliances,^&#42;1^ but not by my spirit,
In order to add sin to sin.

[NOTE]
====
. Lit., “pour out a libation,” evidently referring to making an agreement.
====

[[v23-30-2]]

^<<v23-30-2,2>>^ They go down to Egypt without consulting me,^&#42;1^
To take shelter under Pharʹaoh’s protection^&#42;2^
And to take refuge in the shadow of Egypt!

[NOTE]
====
. Or “without inquiring of my mouth.”
. Lit., “in the stronghold of Pharaoh.”
====

[[v23-30-3]]

^<<v23-30-3,3>>^ But the protection of Pharʹaoh will become for you a reason for shame,
And refuge in Egypt’s shadow a cause for humiliation.

[[v23-30-4]]

^<<v23-30-4,4>>^ For his princes are in Zoʹan,
And his envoys have reached Haʹnes.

[[v23-30-5]]

^<<v23-30-5,5>>^ They will all be put to shame
By a people who can bring no benefit to them,
Who offer no help and no benefit,
Only shame and disgrace.”

[[v23-30-6]]

^<<v23-30-6,6>>^ A pronouncement against the beasts of the south:
Through the land of distress and hardship,
Of the lion, the roaring lion,
Of the viper and the flying fiery snake,^&#42;1^
They carry their wealth on the backs of donkeys
And their supplies on the humps of camels.
But these things will not benefit the people.

[NOTE]
====
. Or “the darting poisonous snake.”
====

[[v23-30-7]]

^<<v23-30-7,7>>^ For Egypt’s help is completely useless.
So I have called this one: “Raʹhab, who sits still.”

[[v23-30-8]]

^<<v23-30-8,8>>^ “Now go, write it on a tablet in their presence,
And inscribe it in a book,
So that it may serve for a future day
As a permanent witness.

[[v23-30-9]]

^<<v23-30-9,9>>^ For they are a rebellious people, deceitful sons,
Sons who are unwilling to hear the law^&#42;1^ of Jehovah.

[NOTE]
====
. Or “instruction.”
====

[[v23-30-10]]

^<<v23-30-10,10>>^ They say to the seers, ‘Do not see,’
And to the visionaries, ‘Do not tell us truthful visions.
Tell us flattering^&#42;1^ things; envision deceptive illusions.

[NOTE]
====
. Lit., “smooth.”
====

[[v23-30-11]]

^<<v23-30-11,11>>^ Turn aside from the way; deviate from the path.
Quit putting before us the Holy One of Israel.’”

[[v23-30-12]]

^<<v23-30-12,12>>^ Therefore this is what the Holy One of Israel says:
“Since you reject this word
And you trust in fraud and deceit
And you rely on these,

[[v23-30-13]]

^<<v23-30-13,13>>^ So this error will be for you like a broken wall,
Like a bulging high wall ready to fall.
It will crash suddenly, in an instant.

[[v23-30-14]]

^<<v23-30-14,14>>^ It will be broken like a large potter’s jar,
So completely smashed that no fragment among its pieces will be left
To rake the fire from the fireplace
Or to scoop water from a puddle.”^&#42;1^

[NOTE]
====
. Or possibly, “a cistern.”
====

[[v23-30-15]]

^<<v23-30-15,15>>^ For this is what the Sovereign Lord Jehovah, the Holy One of Israel, says:
“By returning to me and resting, you will be saved;
Your strength will be in keeping calm and showing trust.”
But you were unwilling.

[[v23-30-16]]

^<<v23-30-16,16>>^ Instead, you said: “No, we will flee on horses!”
So flee you will.
“And on swift horses we will ride!”
So those pursuing you will be swift.

[[v23-30-17]]

^<<v23-30-17,17>>^ A thousand will tremble at the threat of one;
At the threat of five you will flee
Until what is left of you is like a mast on the top of a mountain,
Like a signal pole on a hill.

[[v23-30-18]]

^<<v23-30-18,18>>^ But Jehovah is waiting patiently^&#42;1^ to show you favor,
And he will rise up to show you mercy.
For Jehovah is a God of justice.
Happy are all those keeping in expectation of^&#42;2^ him.

[NOTE]
====
. Or “keeping in expectation.”
. Or “eagerly waiting for.”
====

[[v23-30-19]]

^<<v23-30-19,19>>^ When the people dwell in Zion, in Jerusalem, you will by no means weep. He will surely show you favor at the sound of your cry for help; he will answer you as soon as he hears it.

[[v23-30-20]]

^<<v23-30-20,20>>^ Though Jehovah will give you bread in the form of distress and water in the form of oppression, your Grand Instructor will no longer hide himself, and you will see your Grand Instructor with your own eyes.

[[v23-30-21]]

^<<v23-30-21,21>>^ And your own ears will hear a word behind you saying, “This is the way. Walk in it,” in case you should go to the right or in case you should go to the left.

[[v23-30-22]]

^<<v23-30-22,22>>^ And you will defile the silver overlay of your graven images and the golden plating of your metal statues.^&#42;1^ You will cast them away like a menstrual cloth and say to them, “Be gone!”^&#42;2^

[NOTE]
====
. Or “molten statues.”
. Or possibly, “and call them filth.”
====

[[v23-30-23]]

^<<v23-30-23,23>>^ And he will give the rain for the seed you sow in the ground, and the bread that the ground produces will be abundant and rich.^&#42;1^ In that day your livestock will graze in spacious pastures.

[NOTE]
====
. Lit., “fat and well-oiled.”
====

[[v23-30-24]]

^<<v23-30-24,24>>^ And the cattle and the donkeys that work the ground will eat fodder seasoned with sorrel, which was winnowed with the shovel and the pitchfork.

[[v23-30-25]]

^<<v23-30-25,25>>^ And on every tall mountain and on every high hill will be streams and watercourses, in the day of the great slaughter when the towers fall.

[[v23-30-26]]

^<<v23-30-26,26>>^ And the light of the full moon will become like the light of the sun; and the light of the sun will become seven times stronger, like the light of seven days, in the day that Jehovah binds up the breakdown^&#42;1^ of his people and heals the severe wound from the blow he inflicted.

[NOTE]
====
. Or “fracture.”
====

[[v23-30-27]]

^<<v23-30-27,27>>^ Look! The name of Jehovah is coming from far away,
Burning with his anger and with heavy clouds.
His lips are full of indignation,
And his tongue is like a consuming fire.

[[v23-30-28]]

^<<v23-30-28,28>>^ His spirit^&#42;1^ is like a flooding torrent that reaches clear to the neck,
To shake the nations in a sieve of destruction;^&#42;2^
And the peoples will have a bridle in their jaws that leads them astray.

[NOTE]
====
. Or “breath.”
. Lit., “a sieve of worthlessness.”
====

[[v23-30-29]]

^<<v23-30-29,29>>^ But your song will be like the one sung in the night
When you prepare^&#42;1^ for a festival,
And your heart will rejoice like one
Who walks with^&#42;2^ a flute
On his way to the mountain of Jehovah, to the Rock of Israel.

[NOTE]
====
. Or “sanctify yourself.”
. Or “to the sound of.”
====

[[v23-30-30]]

^<<v23-30-30,30>>^ Jehovah will make his majestic voice heard
And reveal his arm as it descends in the heat of anger,
With the flame of a consuming fire,
A cloudburst and a thunderstorm and hailstones.

[[v23-30-31]]

^<<v23-30-31,31>>^ For because of the voice of Jehovah, As·syrʹi·a will be struck with terror;
He will strike it with a rod.

[[v23-30-32]]

^<<v23-30-32,32>>^ And every swing of his rod of punishment
That Jehovah will bring down on As·syrʹi·a
Will be accompanied by tambourines and harps
As he brandishes his arm against them in battle.

[[v23-30-33]]

^<<v23-30-33,33>>^ For his Toʹpheth^&#42;1^ is already prepared;
It is also made ready for the king.
He has made the woodpile deep and wide,
With an abundance of fire and wood.
The breath of Jehovah, like a torrent of sulfur,
Will set fire to it.

[NOTE]
====
. “Topheth” is here used as a figurative place of burning, representing destruction.
====

'''

xref:023-isaiah/023-isaiah-029.adoc#v23-29-0[&#60; Capítulo Anterior] | <<v23-30-0,Topo>> | xref:023-isaiah/023-isaiah-031.adoc#v23-31-0[Próximo Capítulo &#62;]