include::./index.adoc[]

[[v23-48-0]]
=== Isaiah, 48
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-48-1]]

^<<v23-48-1,1>>^ Hear this, O house of Jacob,
You who call yourselves by the name of Israel
And who have come from the waters of^&#42;1^ Judah,
You who swear by the name of Jehovah
And who call on the God of Israel,
Though not in truth and righteousness.

[NOTE]
====
. Or possibly, “who are descended from.”
====

[[v23-48-2]]

^<<v23-48-2,2>>^ For they call themselves after the holy city
And seek the support of the God of Israel,
Whose name is Jehovah of armies.

[[v23-48-3]]

^<<v23-48-3,3>>^ “The former^&#42;1^ things I told you long ago.
From my own mouth they went out,
And I made them known.
Suddenly I took action, and they came about.

[NOTE]
====
. Lit., “first.”
====

[[v23-48-4]]

^<<v23-48-4,4>>^ Because I knew how stubborn you are
—That your neck is an iron sinew and your forehead is copper—

[[v23-48-5]]

^<<v23-48-5,5>>^ I told you long ago.
Before it came about, I caused you to hear it,
So that you could not say, ‘My idol did this;
My carved image and my metal image^&#42;1^ commanded this.’

[NOTE]
====
. Or “molten statue.”
====

[[v23-48-6]]

^<<v23-48-6,6>>^ You have heard and seen all of this.
Will you not declare it?
From now on I am announcing new things to you,
Guarded secrets that you have not known.

[[v23-48-7]]

^<<v23-48-7,7>>^ Only now are they being created, and not long ago,
Things that you never heard before today,
So that you cannot say, ‘Look! I already know them.’

[[v23-48-8]]

^<<v23-48-8,8>>^ No, you have not heard, you have not known,
And in the past your ears were not opened.
For I know that you are very treacherous,
And you have been called a transgressor from birth.

[[v23-48-9]]

^<<v23-48-9,9>>^ But for the sake of my name I will hold back my anger;
For my own praise I will restrain myself toward you,
And I will not do away with you.

[[v23-48-10]]

^<<v23-48-10,10>>^ Look! I have refined you, but not in the form of silver.
I have tested^&#42;1^ you in the smelting furnace of affliction.

[NOTE]
====
. Or “examined.” Or possibly, “chosen.”
====

[[v23-48-11]]

^<<v23-48-11,11>>^ For my own sake, for my own sake I will act,
For how could I let myself be profaned?
I give my glory to no one else.^&#42;1^

[NOTE]
====
. Or “I do not share my glory with anyone else.”
====

[[v23-48-12]]

^<<v23-48-12,12>>^ Listen to me, O Jacob, and Israel, whom I have called.
I am the same One. I am the first; I am also the last.

[[v23-48-13]]

^<<v23-48-13,13>>^ My own hand laid the foundation of the earth,
And my right hand spread out the heavens.
When I call to them, they stand up together.

[[v23-48-14]]

^<<v23-48-14,14>>^ Gather together, all of you, and listen.
Who among them has announced these things?
Jehovah has loved him.
He will carry out his delight against Babylon,
And his arm will come against the Chal·deʹans.

[[v23-48-15]]

^<<v23-48-15,15>>^ I myself have spoken, and I have called him.
I have brought him, and his way will be successful.

[[v23-48-16]]

^<<v23-48-16,16>>^ Come near to me, and hear this.
From the very start I have not spoken in secret.
From the time it happened I was there.”
And now the Sovereign Lord Jehovah has sent me, and^&#42;1^ his spirit.

[NOTE]
====
. Or “along with.”
====

[[v23-48-17]]

^<<v23-48-17,17>>^ This is what Jehovah says, your Repurchaser, the Holy One of Israel:
“I, Jehovah, am your God,
The One teaching you to benefit yourself,^&#42;1^
The One guiding you in the way you should walk.

[NOTE]
====
. Or “for your own good.”
====

[[v23-48-18]]

^<<v23-48-18,18>>^ If only you would pay attention to my commandments!
Then your peace would become just like a river
And your righteousness like the waves of the sea.

[[v23-48-19]]

^<<v23-48-19,19>>^ Your offspring^&#42;1^ would be as many as the sand
And your descendants as its grains.
Their name would never be cut off or annihilated from before me.”

[NOTE]
====
. Lit., “seed.”
====

[[v23-48-20]]

^<<v23-48-20,20>>^ Go out from Babylon!
Flee from the Chal·deʹans!
Announce it with a joyful cry! Proclaim it!
Make it known to the ends of the earth.
Say: “Jehovah has repurchased his servant Jacob.

[[v23-48-21]]

^<<v23-48-21,21>>^ They did not become thirsty when he led them through devastated places.
He caused water to flow out of the rock for them;
He split a rock and made water gush out.”

[[v23-48-22]]

^<<v23-48-22,22>>^ “There is no peace,” says Jehovah, “for the wicked.”

'''

xref:023-isaiah/023-isaiah-047.adoc#v23-47-0[&#60; Capítulo Anterior] | <<v23-48-0,Topo>> | xref:023-isaiah/023-isaiah-049.adoc#v23-49-0[Próximo Capítulo &#62;]