include::./index.adoc[]

[[v23-16-0]]
=== Isaiah, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-16-1]]

^<<v23-16-1,1>>^ Send a ram to the ruler of the land,
From Seʹla through the wilderness
To the mountain of the daughter of Zion.

[[v23-16-2]]

^<<v23-16-2,2>>^ Like a bird chased away from its nest,
So the daughters of Moʹab will be at the fords of Arʹnon.

[[v23-16-3]]

^<<v23-16-3,3>>^ “Offer counsel, carry out the decision.
Make your shadow at high noon like the night.
Conceal the dispersed and do not betray those fleeing.

[[v23-16-4]]

^<<v23-16-4,4>>^ May my dispersed ones reside in you, O Moʹab.
Become a place of concealment to them because of the destroyer.
The oppressor will reach his end,
The destruction will come to an end,
And those trampling others down will perish from the earth.

[[v23-16-5]]

^<<v23-16-5,5>>^ Then a throne will be firmly established in loyal love.
The one who sits on it in the tent of David will be faithful;
He will judge fairly and will swiftly execute righteousness.”

[[v23-16-6]]

^<<v23-16-6,6>>^ We have heard about the pride of Moʹab—he is very proud—
His haughtiness and his pride and his fury;
But his empty talk will come to nothing.

[[v23-16-7]]

^<<v23-16-7,7>>^ So Moʹab will wail for Moʹab;
They will all wail.
Those who are stricken will moan for the raisin cakes of Kir-harʹe·seth.

[[v23-16-8]]

^<<v23-16-8,8>>^ For the terraces of Heshʹbon have withered,
The vine of Sibʹmah,
The rulers of the nations have trampled its bright-red branches;^&#42;1^
They had reached as far as Jaʹzer;
They had extended into the wilderness.
Its shoots had spread out and gone as far as the sea.

[NOTE]
====
. Or “its branches laden with red grapes.”
====

[[v23-16-9]]

^<<v23-16-9,9>>^ That is why I will weep over the vine of Sibʹmah as I weep for Jaʹzer.
With my tears I will drench you, O Heshʹbon and E·le·aʹleh,
Because the shouting over your summer fruit and your harvest has ended.^&#42;1^

[NOTE]
====
. Or possibly, “Because the battle cry has descended on your summer fruit and your harvest.”
====

[[v23-16-10]]

^<<v23-16-10,10>>^ Rejoicing and joyfulness have been taken away from the orchard,
And there are no songs of joy or shouting in the vineyards.
The treader no longer treads out wine in the presses,
For I have caused the shouting to cease.

[[v23-16-11]]

^<<v23-16-11,11>>^ That is why deep within me I am boisterous over Moʹab,
Like the strumming of a harp,
And my innermost being over Kir-harʹe·seth.

[[v23-16-12]]

^<<v23-16-12,12>>^ Even when Moʹab wears himself out on the high place and goes to pray in his sanctuary, he will accomplish nothing.

[[v23-16-13]]

^<<v23-16-13,13>>^ This is the word that Jehovah previously spoke concerning Moʹab.

[[v23-16-14]]

^<<v23-16-14,14>>^ And now Jehovah says: “Within three years, like the years of a hired worker,^&#42;1^ the glory of Moʹab will be disgraced with much tumult of every sort, and those who remain will be very few and insignificant.”

[NOTE]
====
. Or “counted as carefully as a hired worker does”; that is, in exactly three years.
====

'''

xref:023-isaiah/023-isaiah-015.adoc#v23-15-0[&#60; Capítulo Anterior] | <<v23-16-0,Topo>> | xref:023-isaiah/023-isaiah-017.adoc#v23-17-0[Próximo Capítulo &#62;]