include::./index.adoc[]

[[v23-57-0]]
=== Isaiah, 57
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-57-1]]

^<<v23-57-1,1>>^ The righteous one has perished,
But no one takes it to heart.
Loyal men are taken away,^&#42;1^
With no one discerning that the righteous one has been taken away
Because of^&#42;2^ the calamity.

[NOTE]
====
. That is, in death.
. Or possibly, “From.”
====

[[v23-57-2]]

^<<v23-57-2,2>>^ He enters into peace.
They rest on their beds,^&#42;1^ all who walk uprightly.

[NOTE]
====
. That is, in the grave.
====

[[v23-57-3]]

^<<v23-57-3,3>>^ “But as for you, come closer,
You sons of a sorceress,
You children of an adulterer and a prostitute:

[[v23-57-4]]

^<<v23-57-4,4>>^ Whom are you making fun of?
Against whom do you open your mouth wide and stick out your tongue?
Are you not the children of transgression,
The children of deceit,

[[v23-57-5]]

^<<v23-57-5,5>>^ Those who are inflamed with passion among big trees,
Under every luxuriant tree,
Who slaughter the children in the valleys,^&#42;1^
Under the clefts of the crags?

[NOTE]
====
. Or “wadis.”
====

[[v23-57-6]]

^<<v23-57-6,6>>^ With the smooth stones of the valley^&#42;1^ is your portion.
Yes, these are your lot.
Even to them you pour out drink offerings and offer gifts.
Should I be satisfied^&#42;2^ with these things?

[NOTE]
====
. Or “wadi.”
. Or “Should I comfort myself.”
====

[[v23-57-7]]

^<<v23-57-7,7>>^ On a mountain high and lofty you prepared your bed,
And you went up there to offer sacrifice.

[[v23-57-8]]

^<<v23-57-8,8>>^ Behind the door and the doorpost you set up your memorial.
You left me and uncovered yourself;
You went up and made your bed spacious.
And you made a covenant with them.
You loved sharing their bed,
And you gazed at the male organ.^&#42;1^

[NOTE]
====
. Possibly referring to idolatrous worship.
====

[[v23-57-9]]

^<<v23-57-9,9>>^ You went down to Melʹech^&#42;1^ with oil
And with an abundance of perfume.
You sent your envoys far off,
So that you descended to the Grave.^&#42;2^

[NOTE]
====
. Or possibly, “the king.”
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v23-57-10]]

^<<v23-57-10,10>>^ You have toiled in following your many ways,
But you did not say, ‘It is hopeless!’
You found renewed strength.
That is why you do not give up.^&#42;1^

[NOTE]
====
. Lit., “grow weary.”
====

[[v23-57-11]]

^<<v23-57-11,11>>^ Whom did you dread and fear
So that you started to lie?
You did not remember me.
You took nothing to heart.
Have I not kept silent and withdrawn?^&#42;1^
So you showed no fear of me.

[NOTE]
====
. Or “and hidden matters?”
====

[[v23-57-12]]

^<<v23-57-12,12>>^ I will make known your ‘righteousness’ and your works,
And they will not benefit you.

[[v23-57-13]]

^<<v23-57-13,13>>^ When you cry for help,
Your collection of idols will not rescue you.
A wind will carry all of them away,
A mere breath will blow them away,
But the one who takes refuge in me will inherit the land
And will take possession of my holy mountain.

[[v23-57-14]]

^<<v23-57-14,14>>^ It will be said, ‘Build up, build up a road! Prepare the way!
Remove any obstacle from the way of my people.’”

[[v23-57-15]]

^<<v23-57-15,15>>^ For this is what the High and Lofty One says,
Who lives^&#42;1^ forever and whose name is holy:
“I reside in the high and holy place,
But also with those crushed and lowly in spirit,
To revive the spirit of the lowly
And to revive the heart of those being crushed.

[NOTE]
====
. Or “resides.”
====

[[v23-57-16]]

^<<v23-57-16,16>>^ For I will not oppose them forever
Or always remain indignant;
For a man’s spirit would grow feeble because of me,
Even the breathing creatures that I have made.

[[v23-57-17]]

^<<v23-57-17,17>>^ I was indignant at his sinful pursuit of dishonest gain,
So I struck him, I hid my face, and I was indignant.
But he kept walking as a renegade, following the way of his heart.

[[v23-57-18]]

^<<v23-57-18,18>>^ I have seen his ways,
But I will heal him and lead him
And restore^&#42;1^ comfort to him and to his mourning ones.”

[NOTE]
====
. Or “make compensation with.”
====

[[v23-57-19]]

^<<v23-57-19,19>>^ “I am creating the fruit of the lips.
Continuous peace will be given to the one who is far away and the one who is near,” says Jehovah,
“And I will heal him.”

[[v23-57-20]]

^<<v23-57-20,20>>^ “But the wicked are like the restless sea that cannot calm down,
And its waters keep tossing up seaweed and mire.

[[v23-57-21]]

^<<v23-57-21,21>>^ There is no peace,” says my God, “for the wicked.”

'''

xref:023-isaiah/023-isaiah-056.adoc#v23-56-0[&#60; Capítulo Anterior] | <<v23-57-0,Topo>> | xref:023-isaiah/023-isaiah-058.adoc#v23-58-0[Próximo Capítulo &#62;]