include::./index.adoc[]

[[v23-25-0]]
=== Isaiah, 25
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-25-1]]

^<<v23-25-1,1>>^ O Jehovah, you are my God.
I exalt you, I praise your name,
For you have done wonderful things,
Things purposed^&#42;1^ from ancient times,
In faithfulness, in trustworthiness.

[NOTE]
====
. Or “Counsels.”
====

[[v23-25-2]]

^<<v23-25-2,2>>^ For you have turned a city into a pile of stones,
A fortified town into a crumbling ruin.
The foreigner’s tower is a city no more;
It will never be rebuilt.

[[v23-25-3]]

^<<v23-25-3,3>>^ That is why a strong people will glorify you;
The city of tyrannical nations will fear you.

[[v23-25-4]]

^<<v23-25-4,4>>^ For you have become a stronghold to the lowly,
A stronghold to the poor in his distress,
A refuge from the rainstorm,
And a shade from the heat.
When the blast of the tyrants is like a rainstorm against a wall,

[[v23-25-5]]

^<<v23-25-5,5>>^ As the heat in a parched land,
You subdue the uproar of strangers.
Like heat that is subdued by the shadow of a cloud,
So the song of the tyrants is silenced.

[[v23-25-6]]

^<<v23-25-6,6>>^ In this mountain Jehovah of armies will make for all the peoples
A banquet of rich dishes,
A banquet of fine wine,^&#42;1^
Of rich dishes filled with marrow,
Of fine, filtered wine.

[NOTE]
====
. Or “of wine kept on the dregs.”
====

[[v23-25-7]]

^<<v23-25-7,7>>^ In this mountain he will do away with^&#42;1^ the shroud that is enveloping all the peoples
And the covering^&#42;2^ that is woven over all the nations.

[NOTE]
====
. Lit., “swallow up.”
. Or “veil.”
====

[[v23-25-8]]

^<<v23-25-8,8>>^ He will swallow up^&#42;1^ death forever,
And the Sovereign Lord Jehovah will wipe away the tears from all faces.
The reproach of his people he will take away from all the earth,
For Jehovah himself has spoken it.

[NOTE]
====
. Or “do away with.”
====

[[v23-25-9]]

^<<v23-25-9,9>>^ In that day they will say:
“Look! This is our God!
We have hoped in him,
And he will save us.
This is Jehovah!
We have hoped in him.
Let us be joyful and rejoice in the salvation by him.”

[[v23-25-10]]

^<<v23-25-10,10>>^ For the hand of Jehovah will rest on this mountain,
And Moʹab will be trampled on in its place
Like straw trampled into a pile of manure.

[[v23-25-11]]

^<<v23-25-11,11>>^ He will slap out his hands into it
Like a swimmer slapping out his hands to swim,
And he will bring down its haughtiness
With the skillful movements of his hands.

[[v23-25-12]]

^<<v23-25-12,12>>^ And the fortified city, with your high walls of security,
He will bring down;
He will knock it down to the ground, to the very dust.

'''

xref:023-isaiah/023-isaiah-024.adoc#v23-24-0[&#60; Capítulo Anterior] | <<v23-25-0,Topo>> | xref:023-isaiah/023-isaiah-026.adoc#v23-26-0[Próximo Capítulo &#62;]