include::./index.adoc[]

[[v23-7-0]]
=== Isaiah, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-7-1]]

^<<v23-7-1,1>>^ Now in the days of Aʹhaz son of Joʹtham son of Uz·ziʹah, the king of Judah, King Reʹzin of Syria and Peʹkah son of Rem·a·liʹah, the king of Israel, came up to wage war against Jerusalem, but he^&#42;1^ could not capture it.

[NOTE]
====
. Or possibly, “they.”
====

[[v23-7-2]]

^<<v23-7-2,2>>^ A report was made to the house of David: “Syria has joined forces with Eʹphra·im.”
And the heart of Aʹhaz and the heart of his people began to tremble, like the trees of the forest shaking in the wind.

[[v23-7-3]]

^<<v23-7-3,3>>^ Jehovah then said to Isaiah: “Go out, please, to meet Aʹhaz, you and your son Sheʹar-jaʹshub,^&#42;1^ at the end of the conduit^&#42;2^ of the upper pool by the highway of the laundryman’s field.

[NOTE]
====
. Meaning “Only a Remnant Will Return.”
. Or “water channel.”
====

[[v23-7-4]]

^<<v23-7-4,4>>^ You must say to him, ‘Take care to stay calm. Do not be afraid, and do not lose heart because of these two stumps of smoldering logs, because of the hot anger of Reʹzin and Syria and the son of Rem·a·liʹah.

[[v23-7-5]]

^<<v23-7-5,5>>^ For Syria with Eʹphra·im and the son of Rem·a·liʹah have plotted harm against you, saying:

[[v23-7-6]]

^<<v23-7-6,6>>^ “Let us go up against Judah and tear it apart^&#42;1^ and conquer it^&#42;2^ for ourselves, and let us appoint the son of Tabʹe·el as its king.”

[NOTE]
====
. Or possibly, “terrorize it.”
. Or “make a breach in its walls.” Lit., “split it open.”
====

[[v23-7-7]]

^<<v23-7-7,7>>^ “‘This is what the Sovereign Lord Jehovah says:
“It will not succeed,
Nor will it take place.

[[v23-7-8]]

^<<v23-7-8,8>>^ For the head of Syria is Damascus,
And the head of Damascus is Reʹzin.
Within just 65 years
Eʹphra·im will be completely shattered and cease to be a people.

[[v23-7-9]]

^<<v23-7-9,9>>^ The head of Eʹphra·im is Sa·marʹi·a,
And the head of Sa·marʹi·a is the son of Rem·a·liʹah.
Unless you have firm faith,
You will not be firmly established.”’”

[[v23-7-10]]

^<<v23-7-10,10>>^ Jehovah continued speaking to Aʹhaz:

[[v23-7-11]]

^<<v23-7-11,11>>^ “Ask for a sign from Jehovah your God; it may be as deep as the Grave^&#42;1^ or as high as the sky.”

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v23-7-12]]

^<<v23-7-12,12>>^ But Aʹhaz said: “I will not ask, nor will I put Jehovah to the test.”

[[v23-7-13]]

^<<v23-7-13,13>>^ Isaiah then said: “Listen, please, O house of David. Is it not enough that you try the patience of men? Must you also try the patience of God?

[[v23-7-14]]

^<<v23-7-14,14>>^ Therefore, Jehovah himself will give you a sign: Look! The young woman^&#42;1^ will become pregnant and will give birth to a son, and she will name him Im·manʹu·el.^&#42;2^

[NOTE]
====
. Or “The maiden.”
. Meaning “With Us Is God.”
====

[[v23-7-15]]

^<<v23-7-15,15>>^ He will eat butter and honey by the time that he knows how to reject the bad and choose the good.

[[v23-7-16]]

^<<v23-7-16,16>>^ For before the boy knows how to reject the bad and choose the good, the land of the two kings whom you dread will be completely abandoned.

[[v23-7-17]]

^<<v23-7-17,17>>^ Jehovah will bring against you and against your people and against the house of your father a time such as has not come since the day Eʹphra·im broke away from Judah, for He will bring the king of As·syrʹi·a.

[[v23-7-18]]

^<<v23-7-18,18>>^ “In that day Jehovah will whistle for the flies from the distant streams of the Nile of Egypt and for the bees in the land of As·syrʹi·a,

[[v23-7-19]]

^<<v23-7-19,19>>^ and they will all come and settle down on the steep valleys,^&#42;1^ on the rocky clefts, on all the thornbushes, and on all the watering places.

[NOTE]
====
. Or “wadis.”
====

[[v23-7-20]]

^<<v23-7-20,20>>^ “In that day by means of a hired razor from the region of the River,^&#42;1^ by means of the king of As·syrʹi·a, Jehovah will shave the head and the hair of the legs, and it will sweep away the beard as well.

[NOTE]
====
. That is, the Euphrates.
====

[[v23-7-21]]

^<<v23-7-21,21>>^ “In that day a man will keep alive a young cow of the herd and two sheep.

[[v23-7-22]]

^<<v23-7-22,22>>^ And because of the abundance of milk, he will eat butter, for everyone remaining in the land will eat butter and honey.

[[v23-7-23]]

^<<v23-7-23,23>>^ “In that day wherever there used to be 1,000 vines worth 1,000 pieces of silver, there will be only thornbushes and weeds.

[[v23-7-24]]

^<<v23-7-24,24>>^ Men will go there with bow and arrow, because all the land will become thornbushes and weeds.

[[v23-7-25]]

^<<v23-7-25,25>>^ And all the mountains that used to be cleared with a hoe, you will not go near for fear of thornbushes and weeds; they will become a grazing place for bulls and a trampling ground of sheep.”

'''

xref:023-isaiah/023-isaiah-006.adoc#v23-6-0[&#60; Capítulo Anterior] | <<v23-7-0,Topo>> | xref:023-isaiah/023-isaiah-008.adoc#v23-8-0[Próximo Capítulo &#62;]