include::./index.adoc[]

[[v23-3-0]]
=== Isaiah, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-3-1]]

^<<v23-3-1,1>>^ For look! the true Lord, Jehovah of armies,
Is removing from Jerusalem and Judah every kind of support and supply,
All support of bread and water,

[[v23-3-2]]

^<<v23-3-2,2>>^ Mighty man and warrior,
Judge and prophet, diviner and elder,

[[v23-3-3]]

^<<v23-3-3,3>>^ Chief of 50, dignitary, and adviser,
The expert magician and the skilled charmer.

[[v23-3-4]]

^<<v23-3-4,4>>^ I will make boys their princes,
And the unstable^&#42;1^ will rule over them.

[NOTE]
====
. Or “fickle.”
====

[[v23-3-5]]

^<<v23-3-5,5>>^ The people will oppress one another,
Each one his fellow man.
The boy will assault the old man,
And the lightly esteemed one will defy the respected one.

[[v23-3-6]]

^<<v23-3-6,6>>^ Each one will take hold of his brother in his father’s house and say:
“You have a cloak—you be our commander.
Take charge of this overthrown pile of ruins.”

[[v23-3-7]]

^<<v23-3-7,7>>^ But he will protest in that day:
“I will not be your wound dresser;^&#42;1^
I have no food or clothing in my house.
Do not make me commander over the people.”

[NOTE]
====
. Or “your healer.”
====

[[v23-3-8]]

^<<v23-3-8,8>>^ For Jerusalem has stumbled,
And Judah has fallen,
Because in word and deed they are against Jehovah;
They behave defiantly in his glorious presence.^&#42;1^

[NOTE]
====
. Lit., “in the eyes of his glory.”
====

[[v23-3-9]]

^<<v23-3-9,9>>^ The expression of their faces testifies against them,
And they proclaim their sin like Sodʹom;
They do not try to hide it.
Woe to them,^&#42;1^ for they are bringing disaster on themselves!

[NOTE]
====
. Or “their soul.”
====

[[v23-3-10]]

^<<v23-3-10,10>>^ Tell the righteous that it will go well for them;
They will be rewarded for what they do.^&#42;1^

[NOTE]
====
. Lit., “will eat the fruitage of their deeds.”
====

[[v23-3-11]]

^<<v23-3-11,11>>^ Woe to the wicked one!
Disaster will befall him,
For what his hands have done will be done to him!

[[v23-3-12]]

^<<v23-3-12,12>>^ As for my people, their taskmasters are abusive,
And women rule over them.
My people, your leaders are causing you to wander,
And they confuse the direction of your paths.

[[v23-3-13]]

^<<v23-3-13,13>>^ Jehovah is taking his position to accuse;
He is standing up to pass sentence on peoples.

[[v23-3-14]]

^<<v23-3-14,14>>^ Jehovah will enter into judgment with the elders and princes of his people.
“You have burned down the vineyard,
And what you have stolen from the poor is in your houses.

[[v23-3-15]]

^<<v23-3-15,15>>^ How dare you crush my people
And grind the faces of the poor in the dirt?” declares the Sovereign Lord, Jehovah of armies.

[[v23-3-16]]

^<<v23-3-16,16>>^ Jehovah says: “Because the daughters of Zion are haughty,
Walking with their heads high,^&#42;1^
Flirting with their eyes, skipping along,
Making a tinkling sound with their anklets,

[NOTE]
====
. Lit., “with an outstretched neck (throat).”
====

[[v23-3-17]]

^<<v23-3-17,17>>^ Jehovah will also strike the head of the daughters of Zion with scabs,
And Jehovah will make their forehead bare.

[[v23-3-18]]

^<<v23-3-18,18>>^ In that day Jehovah will take away the beauty of their bangles,
The headbands and the crescent-shaped ornaments,

[[v23-3-19]]

^<<v23-3-19,19>>^ The earrings,^&#42;1^ the bracelets, and the veils,

[NOTE]
====
. Or “pendants.”
====

[[v23-3-20]]

^<<v23-3-20,20>>^ The headdresses, the ankle chains, and the breastbands,^&#42;1^
The perfume receptacles^&#42;2^ and the charms,^&#42;3^

[NOTE]
====
. Or “sashes.”
. Lit., “houses of the soul.”
. Or “ornamental humming shells.”
====

[[v23-3-21]]

^<<v23-3-21,21>>^ The finger rings and the nose rings,

[[v23-3-22]]

^<<v23-3-22,22>>^ The ceremonial robes, the overtunics, the cloaks, and the purses,

[[v23-3-23]]

^<<v23-3-23,23>>^ The hand mirrors and the linen garments,^&#42;1^
The turbans and the veils.

[NOTE]
====
. Or “the undergarments.”
====

[[v23-3-24]]

^<<v23-3-24,24>>^ Instead of balsam oil, there will be a rotten smell;
Instead of a belt, a rope;
Instead of a beautiful hairstyle, baldness;
Instead of a rich garment, a garment of sackcloth;
And a brand mark instead of beauty.

[[v23-3-25]]

^<<v23-3-25,25>>^ By the sword your men will fall,
And your mighty men in battle.

[[v23-3-26]]

^<<v23-3-26,26>>^ Her entrances will mourn and grieve,
And she will sit on the ground desolate.”

'''

xref:023-isaiah/023-isaiah-002.adoc#v23-2-0[&#60; Capítulo Anterior] | <<v23-3-0,Topo>> | xref:023-isaiah/023-isaiah-004.adoc#v23-4-0[Próximo Capítulo &#62;]