include::./index.adoc[]

[[v23-43-0]]
=== Isaiah, 43
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-43-1]]

^<<v23-43-1,1>>^ Now this is what Jehovah says,
Your Creator, O Jacob, the One who formed you, O Israel:
“Do not be afraid, for I have repurchased you.
I have called you by your name.
You belong to me.

[[v23-43-2]]

^<<v23-43-2,2>>^ When you pass through the waters, I will be with you,
And through the rivers, they will not flood over you.
When you walk through the fire, you will not be scorched,
Nor will the flame singe you.

[[v23-43-3]]

^<<v23-43-3,3>>^ For I am Jehovah your God,
The Holy One of Israel, your Savior.
I have given Egypt as a ransom for you,
E·thi·oʹpi·a and Seʹba in exchange for you.

[[v23-43-4]]

^<<v23-43-4,4>>^ For you became precious in my eyes,
You were honored, and I have loved you.
So I will give people in place of you
And nations in exchange for your life.^&#42;1^

[NOTE]
====
. Or “soul.”
====

[[v23-43-5]]

^<<v23-43-5,5>>^ Do not be afraid, for I am with you.
I will bring your offspring^&#42;1^ from the east
And gather you together from the west.

[NOTE]
====
. Lit., “seed.”
====

[[v23-43-6]]

^<<v23-43-6,6>>^ I will say to the north, ‘Give them up!’
And to the south, ‘Do not hold them back.
Bring my sons from afar, and my daughters from the ends of the earth,

[[v23-43-7]]

^<<v23-43-7,7>>^ Everyone who is called by my name
And whom I created for my own glory,
Whom I have formed and made.’

[[v23-43-8]]

^<<v23-43-8,8>>^ Bring out a people who are blind, though they have eyes,
And who are deaf, though they have ears.

[[v23-43-9]]

^<<v23-43-9,9>>^ Let all the nations assemble in one place,
And let the peoples be gathered together.
Who among them can tell this?
Or can they cause us to hear the first things?^&#42;1^
Let them present their witnesses to prove themselves right,
Or let them hear and say, ‘It is the truth!’”

[NOTE]
====
. Possibly referring to the first things to come in the future.
====

[[v23-43-10]]

^<<v23-43-10,10>>^ “You are my witnesses,” declares Jehovah,
“Yes, my servant whom I have chosen,
So that you may know and have faith in me^&#42;1^
And understand that I am the same One.
Before me no God was formed,
And after me there has been none.

[NOTE]
====
. Or “and trust me.”
====

[[v23-43-11]]

^<<v23-43-11,11>>^ I—I am Jehovah, and besides me there is no savior.”

[[v23-43-12]]

^<<v23-43-12,12>>^ “I am the One who declared and saved and made known
When there was no foreign god among you.
So you are my witnesses,” declares Jehovah, “and I am God.

[[v23-43-13]]

^<<v23-43-13,13>>^ Also, I am always the same One;
And no one can snatch anything out of my hand.
When I act, who can prevent it?”

[[v23-43-14]]

^<<v23-43-14,14>>^ This is what Jehovah says, your Repurchaser, the Holy One of Israel:
“For your sakes I will send to Babylon and bring down all the bars of the gates,
And the Chal·deʹans, in their ships, will cry out in distress.

[[v23-43-15]]

^<<v23-43-15,15>>^ I am Jehovah, your Holy One, the Creator of Israel, your King.”

[[v23-43-16]]

^<<v23-43-16,16>>^ This is what Jehovah says,
The One making a way through the sea
And a path even through turbulent waters,

[[v23-43-17]]

^<<v23-43-17,17>>^ The One who draws out the war chariot and the horse,
The army together with the mighty warriors:
“They will lie down and not get up.
They will be extinguished, snuffed out like a burning wick.”

[[v23-43-18]]

^<<v23-43-18,18>>^ “Do not remember the former things,
And do not dwell on the past.

[[v23-43-19]]

^<<v23-43-19,19>>^ Look! I am doing something new;
Even now it is springing up.
Do you not recognize it?
I will make a way through the wilderness
And rivers through the desert.

[[v23-43-20]]

^<<v23-43-20,20>>^ The wild beast of the field will honor me,
The jackals and the ostriches,
For I provide water in the wilderness,
Rivers in the desert,
For my people, my chosen one, to drink,

[[v23-43-21]]

^<<v23-43-21,21>>^ The people whom I formed for myself
So that they might declare my praise.

[[v23-43-22]]

^<<v23-43-22,22>>^ But you have not called on me, O Jacob,
Because you grew weary of me, O Israel.

[[v23-43-23]]

^<<v23-43-23,23>>^ You have not brought me sheep for your whole burnt offerings
Or glorified me with your sacrifices.
I have not compelled you to bring me a gift,
Nor have I made you weary by demanding frankincense.

[[v23-43-24]]

^<<v23-43-24,24>>^ You did not buy me sweet cane^&#42;1^ with your money,
And with the fat of your sacrifices you did not satisfy me.
Instead, you have burdened me with your sins
And made me weary with your errors.

[NOTE]
====
. An aromatic reed.
====

[[v23-43-25]]

^<<v23-43-25,25>>^ I, I am the One who is blotting out your transgressions^&#42;1^ for my own sake,
And I will not remember your sins.

[NOTE]
====
. Or “rebellious acts.”
====

[[v23-43-26]]

^<<v23-43-26,26>>^ Remind me; let us bring our case against each other;
Tell your side of it to prove you are in the right.

[[v23-43-27]]

^<<v23-43-27,27>>^ Your first forefather sinned,
And your own spokesmen^&#42;1^ have rebelled against me.

[NOTE]
====
. Possibly referring to teachers of the Law.
====

[[v23-43-28]]

^<<v23-43-28,28>>^ So I will profane the princes of the holy place,
And I will give Jacob over to destruction
And subject Israel to insulting words.

'''

xref:023-isaiah/023-isaiah-042.adoc#v23-42-0[&#60; Capítulo Anterior] | <<v23-43-0,Topo>> | xref:023-isaiah/023-isaiah-044.adoc#v23-44-0[Próximo Capítulo &#62;]