include::./index.adoc[]

[[v23-5-0]]
=== Isaiah, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-5-1]]

^<<v23-5-1,1>>^ Let me sing, please, to my beloved
A song about my loved one and his vineyard.
My beloved had a vineyard on a fruitful hillside.

[[v23-5-2]]

^<<v23-5-2,2>>^ He dug it up and rid it of stones.
He planted it with a choice red vine,
Built a tower in the middle of it,
And hewed out a winepress in it.
Then he kept hoping for it to produce grapes,
But it produced only wild grapes.

[[v23-5-3]]

^<<v23-5-3,3>>^ “And now, you inhabitants of Jerusalem and men of Judah,
Please judge between me and my vineyard.

[[v23-5-4]]

^<<v23-5-4,4>>^ What more could I have done for my vineyard
That I have not already done?
Why, when I hoped for grapes,
Did it produce only wild grapes?

[[v23-5-5]]

^<<v23-5-5,5>>^ Now, please, let me tell you
What I will do to my vineyard:
I will remove its hedge,
And it will be burned down.
I will break down its stone wall,
And it will be trampled on.

[[v23-5-6]]

^<<v23-5-6,6>>^ I will make it a wasteland;
It will not be pruned or hoed.
It will be overgrown with thornbushes and weeds,
And I will command the clouds not to send any rain on it.

[[v23-5-7]]

^<<v23-5-7,7>>^ For the vineyard of Jehovah of armies is the house of Israel;
The men of Judah are the plantation^&#42;1^ he was fond of.
He kept hoping for justice,
But look! there was injustice;
For righteousness,
But look! a cry of distress.”

[NOTE]
====
. Or “planting.”
====

[[v23-5-8]]

^<<v23-5-8,8>>^ Woe to those who join one house to another house
And who annex one field to another field
Until there is no more room
And you live by yourselves on the land!

[[v23-5-9]]

^<<v23-5-9,9>>^ Jehovah of armies has sworn in my ears
That many houses, though great and beautiful,
Will become an object of horror,
Without an inhabitant.

[[v23-5-10]]

^<<v23-5-10,10>>^ For ten acres^&#42;1^ of vineyard will produce but one bath measure,^&#42;2^
And a hoʹmer measure^&#42;3^ of seed will produce only an eʹphah.^&#42;4^

[NOTE]
====
. Lit., “ten spans.”
. See App. B14.
. See App. B14.
. See App. B14.
====

[[v23-5-11]]

^<<v23-5-11,11>>^ Woe to those who get up early in the morning to drink alcohol,
Who linger late into the evening darkness until wine inflames them!

[[v23-5-12]]

^<<v23-5-12,12>>^ They have harp and stringed instrument,
Tambourine, flute, and wine at their feasts;
But they do not consider the activity of Jehovah,
And they do not see the work of his hands.

[[v23-5-13]]

^<<v23-5-13,13>>^ So my people will go into exile
For lack of knowledge;
Their glorious men will go hungry,
And all their people will be parched with thirst.

[[v23-5-14]]

^<<v23-5-14,14>>^ So the Grave^&#42;1^ has enlarged itself^&#42;2^
And has opened its mouth wide without limit;
And her splendor,^&#42;3^ her noisy multitudes, and her revelers
Will certainly go down into it.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
. Or “its soul.”
. Or “her nobles.”
====

[[v23-5-15]]

^<<v23-5-15,15>>^ And man will bow down,
Man will be brought low,
And the eyes of the haughty will be brought low.

[[v23-5-16]]

^<<v23-5-16,16>>^ Jehovah of armies will be exalted by his judgment;^&#42;1^
The true God, the Holy One, will sanctify himself through righteousness.

[NOTE]
====
. Or “justice.”
====

[[v23-5-17]]

^<<v23-5-17,17>>^ And the lambs will graze as in their pasture;
Foreign residents will feed on the desolate places of well-fed animals.

[[v23-5-18]]

^<<v23-5-18,18>>^ Woe to those who drag along their guilt with ropes of deception
And their sin with wagon cords;

[[v23-5-19]]

^<<v23-5-19,19>>^ Those who say: “Let Him speed up his work;
Let it come quickly that we may see it.
Let the purpose^&#42;1^ of the Holy One of Israel take place
That we may know it!”

[NOTE]
====
. Or “decision; counsel.”
====

[[v23-5-20]]

^<<v23-5-20,20>>^ Woe to those who say that good is bad and bad is good,
Those who substitute darkness for light and light for darkness,
Those who put bitter for sweet and sweet for bitter!

[[v23-5-21]]

^<<v23-5-21,21>>^ Woe to those wise in their own eyes
And discreet in their own sight!

[[v23-5-22]]

^<<v23-5-22,22>>^ Woe to those who are mighty in drinking wine
And to the men who are masters at mixing alcoholic drinks,

[[v23-5-23]]

^<<v23-5-23,23>>^ Those who acquit the wicked for a bribe
And who deny justice to the righteous!

[[v23-5-24]]

^<<v23-5-24,24>>^ Therefore, just as the tongue of fire consumes the stubble
And dry grass shrivels in the flames,
Their very roots will rot,
And their blossoms will scatter like powder,
Because they rejected the law^&#42;1^ of Jehovah of armies
And disrespected the word of the Holy One of Israel.

[NOTE]
====
. Or “instruction.”
====

[[v23-5-25]]

^<<v23-5-25,25>>^ That is why the anger of Jehovah burns against his people,
And he will stretch out his hand against them and strike them.
The mountains will quake,
And their corpses will be like refuse in the streets.
In view of all this, his anger has not turned back,
But his hand is still stretched out to strike.

[[v23-5-26]]

^<<v23-5-26,26>>^ He has raised up a signal^&#42;1^ to a distant nation;
He has whistled for them to come from the ends of the earth;
And look! they are coming very swiftly.

[NOTE]
====
. Or “signal pole.”
====

[[v23-5-27]]

^<<v23-5-27,27>>^ None among them are tired or stumbling.
No one is drowsy or sleeps.
The belt around their waist is not loosened,
Nor are their sandal laces broken.

[[v23-5-28]]

^<<v23-5-28,28>>^ All their arrows are sharp,
And all their bows are bent.^&#42;1^
The hooves of their horses are like flint,
And their wheels like a storm wind.

[NOTE]
====
. Or “ready to shoot.”
====

[[v23-5-29]]

^<<v23-5-29,29>>^ Their roaring is like that of a lion;
They roar like young lions.^&#42;1^
They will growl and seize the prey
And carry it off with no one to rescue it.

[NOTE]
====
. Or “maned young lions.”
====

[[v23-5-30]]

^<<v23-5-30,30>>^ In that day they will growl over it
Like the growling of the sea.
Anyone who gazes at the land will see distressing darkness;
Even the light has grown dark because of the clouds.

'''

xref:023-isaiah/023-isaiah-004.adoc#v23-4-0[&#60; Capítulo Anterior] | <<v23-5-0,Topo>> | xref:023-isaiah/023-isaiah-006.adoc#v23-6-0[Próximo Capítulo &#62;]