include::./index.adoc[]

[[v23-58-0]]
=== Isaiah, 58
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-58-1]]

^<<v23-58-1,1>>^ “Call out full-throated; do not hold back!
Raise your voice like a horn.
Proclaim to my people their revolt,
To the house of Jacob their sins.

[[v23-58-2]]

^<<v23-58-2,2>>^ They seek me day after day,
And they express delight to know my ways,
As if they were a nation that had practiced righteousness
And had not abandoned the justice of their God.
They ask me for righteous judgments,
Delighting to draw close to God:

[[v23-58-3]]

^<<v23-58-3,3>>^ ‘Why do you not see when we fast?
And why do you not notice when we afflict ourselves?’^&#42;1^
Because on the day of your fast, you pursue your own interests,^&#42;2^
And you oppress your laborers.

[NOTE]
====
. Or “our soul?”
. Or “delight.”
====

[[v23-58-4]]

^<<v23-58-4,4>>^ Your fasting ends in quarrels and fights,
And you strike with the fist of wickedness.
You cannot fast as you do today and have your voice heard in heaven.

[[v23-58-5]]

^<<v23-58-5,5>>^ Should the fast that I choose be like this,
As a day for someone to afflict himself,^&#42;1^
To bow down his head like a rush,
To make his bed on sackcloth and ashes?
Is this what you call a fast and a day pleasing to Jehovah?

[NOTE]
====
. Or “his soul.”
====

[[v23-58-6]]

^<<v23-58-6,6>>^ No, this is the fast that I choose:
To remove the fetters of wickedness,
To untie the bands of the yoke bar,
To let the oppressed go free,
And to break in half every yoke bar;

[[v23-58-7]]

^<<v23-58-7,7>>^ It is to share your bread with the hungry,
To bring the poor and homeless into your house,
To clothe someone naked when you see him,
And not to turn your back on your own flesh.

[[v23-58-8]]

^<<v23-58-8,8>>^ Then your light will shine through like the dawn,
And your healing will spring up quickly.
Your righteousness will go before you,
And the glory of Jehovah will be your rear guard.

[[v23-58-9]]

^<<v23-58-9,9>>^ Then you will call, and Jehovah will answer;
You will cry for help, and he will say, ‘Here I am!’
If you remove from among you the yoke bar
And stop pointing your finger and speaking maliciously,

[[v23-58-10]]

^<<v23-58-10,10>>^ If you grant to the hungry what you yourself desire^&#42;1^
And satisfy those who are afflicted,^&#42;2^
Then your light will shine even in the darkness,
And your gloom will be like midday.

[NOTE]
====
. Or “your own soul desires.”
. Or “the afflicted souls.”
====

[[v23-58-11]]

^<<v23-58-11,11>>^ Jehovah will always lead you
And satisfy you^&#42;1^ even in a parched land;
He will invigorate your bones,
And you will become like a well-watered garden,
Like a spring whose waters never fail.

[NOTE]
====
. Or “your soul.”
====

[[v23-58-12]]

^<<v23-58-12,12>>^ They will rebuild ancient ruins on your account,
And you will restore the foundations of past generations.
You will be called the repairer of the broken walls,^&#42;1^
The restorer of roadways by which to dwell.

[NOTE]
====
. Lit., “the breach.”
====

[[v23-58-13]]

^<<v23-58-13,13>>^ If because of the Sabbath you refrain^&#42;1^ from pursuing your own interests^&#42;2^ on my holy day
And you call the Sabbath an exquisite delight, a holy day of Jehovah, a day to be glorified,
And you glorify it rather than pursuing your own interests and speaking idle words,

[NOTE]
====
. Lit., “turn your foot back.”
. Or “your own delights.”
====

[[v23-58-14]]

^<<v23-58-14,14>>^ Then you will find your exquisite delight in Jehovah,
And I will make you ride on the high places of the earth.
I will cause you to eat from^&#42;1^ the inheritance of Jacob your forefather,
For the mouth of Jehovah has spoken.”

[NOTE]
====
. Or “to enjoy.”
====

'''

xref:023-isaiah/023-isaiah-057.adoc#v23-57-0[&#60; Capítulo Anterior] | <<v23-58-0,Topo>> | xref:023-isaiah/023-isaiah-059.adoc#v23-59-0[Próximo Capítulo &#62;]