include::./index.adoc[]

[[v23-15-0]]
=== Isaiah, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-15-1]]

^<<v23-15-1,1>>^ A pronouncement against Moʹab:
Because it has been devastated in a night,
Ar of Moʹab has been silenced.
Because it has been devastated in a night,
Kir of Moʹab has been silenced.

[[v23-15-2]]

^<<v23-15-2,2>>^ He has gone up to the House^&#42;1^ and to Diʹbon,
To the high places to weep.
Moʹab wails over Neʹbo and over Medʹe·ba.
Every head is shaved bald, every beard is clipped.

[NOTE]
====
. Or “the Temple.”
====

[[v23-15-3]]

^<<v23-15-3,3>>^ In its streets they have put on sackcloth.
On their roofs and in their public squares they all wail;
They go down weeping.

[[v23-15-4]]

^<<v23-15-4,4>>^ Heshʹbon and E·le·aʹleh cry out;
Their voice is heard as far as Jaʹhaz.
That is why the armed men of Moʹab keep shouting.
He^&#42;1^ is trembling.

[NOTE]
====
. Or “His soul.”
====

[[v23-15-5]]

^<<v23-15-5,5>>^ My heart cries out over Moʹab.
Its fugitives have fled as far as Zoʹar and Egʹlath-she·liʹshi·yah.
On the ascent of Luʹhith they weep as they go up;
On the way to Hor·o·naʹim they cry out over the catastrophe.

[[v23-15-6]]

^<<v23-15-6,6>>^ For the waters of Nimʹrim are desolate;
The green grass has dried up,
The grass is gone and nothing green is left.

[[v23-15-7]]

^<<v23-15-7,7>>^ That is why they are carrying away what is left of their stores and their riches;
They are crossing the valley^&#42;1^ of poplars.

[NOTE]
====
. Or “wadi.”
====

[[v23-15-8]]

^<<v23-15-8,8>>^ For the outcry echoes throughout the territory of Moʹab.
The wailing reaches to Eg·laʹim;
The wailing reaches to Beʹer-eʹlim.

[[v23-15-9]]

^<<v23-15-9,9>>^ For the waters of Diʹmon are full of blood,
And I have more in store for Diʹmon:
A lion for those of Moʹab who escape
And for those remaining in the land.

'''

xref:023-isaiah/023-isaiah-014.adoc#v23-14-0[&#60; Capítulo Anterior] | <<v23-15-0,Topo>> | xref:023-isaiah/023-isaiah-016.adoc#v23-16-0[Próximo Capítulo &#62;]