include::./index.adoc[]

[[v23-1-0]]
=== Isaiah, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-1-1]]

^<<v23-1-1,1>>^ The vision that Isaiah^&#42;1^ the son of Aʹmoz saw concerning Judah and Jerusalem in the days of Uz·ziʹah, Joʹtham, Aʹhaz, and Hez·e·kiʹah, kings of Judah:

[NOTE]
====
. Meaning “Salvation of Jehovah.”
====

[[v23-1-2]]

^<<v23-1-2,2>>^ Hear, O heavens, and pay attention, O earth,
For Jehovah has spoken:
“Sons I have brought up and raised,
But they have revolted against me.

[[v23-1-3]]

^<<v23-1-3,3>>^ A bull well knows its buyer,
And a donkey the manger of its owner;
But Israel does not know me,^&#42;1^
My own people do not behave with understanding.”

[NOTE]
====
. Or “its master.”
====

[[v23-1-4]]

^<<v23-1-4,4>>^ Woe to the sinful nation,
The people weighed down with error,
A brood of wicked men, corrupt children!
They have abandoned Jehovah;
They have treated the Holy One of Israel with disrespect;
They have turned their backs on him.

[[v23-1-5]]

^<<v23-1-5,5>>^ Where will you be struck next as you add to your rebellion?
The whole head is sick,
And the whole heart is diseased.

[[v23-1-6]]

^<<v23-1-6,6>>^ From the sole of the foot to the head, nothing is healthy.
There are wounds and bruises and open sores
—They have not been treated^&#42;1^ or bound up or softened with oil.

[NOTE]
====
. Lit., “pressed out.”
====

[[v23-1-7]]

^<<v23-1-7,7>>^ Your land is desolate.
Your cities are burned with fire.
Foreigners devour your land right in front of you.
It is like a wasteland overthrown by foreigners.

[[v23-1-8]]

^<<v23-1-8,8>>^ The daughter of Zion has been left like a shelter^&#42;1^ in a vineyard,
Like a hut in a cucumber field,
Like a city under siege.

[NOTE]
====
. Or “booth.”
====

[[v23-1-9]]

^<<v23-1-9,9>>^ Unless Jehovah of armies had left us a few survivors,
We should have become just like Sodʹom,
And we should have resembled Go·morʹrah.

[[v23-1-10]]

^<<v23-1-10,10>>^ Hear the word of Jehovah, you dictators^&#42;1^ of Sodʹom.
Pay attention to the law^&#42;2^ of our God, you people of Go·morʹrah.

[NOTE]
====
. Or “rulers.”
. Or “instruction.”
====

[[v23-1-11]]

^<<v23-1-11,11>>^ “Of what benefit to me are your many sacrifices?” says Jehovah.
“I have had enough of your burnt offerings of rams and the fat of well-fed animals,
And I have no delight in the blood of young bulls and lambs and goats.

[[v23-1-12]]

^<<v23-1-12,12>>^ When you come to appear before me,
Who has required this from you,
This trampling of my courtyards?

[[v23-1-13]]

^<<v23-1-13,13>>^ Stop bringing in any more worthless grain offerings.
Your incense is detestable to me.
New moons, sabbaths, the calling of conventions
—I cannot put up with the use of magical power along with your solemn assembly.

[[v23-1-14]]

^<<v23-1-14,14>>^ I have^&#42;1^ hated your new moons and your festivals.
They have become a burden to me;
I am tired of bearing them.

[NOTE]
====
. Or “My soul has.”
====

[[v23-1-15]]

^<<v23-1-15,15>>^ And when you spread out your palms,
I hide my eyes from you.
Although you offer many prayers,
I am not listening;
Your hands are filled with blood.

[[v23-1-16]]

^<<v23-1-16,16>>^ Wash yourselves, make yourselves clean;
Remove your evil deeds from my sight;
Stop doing bad.

[[v23-1-17]]

^<<v23-1-17,17>>^ Learn to do good, seek justice,
Correct the oppressor,
Defend the rights of the fatherless child,^&#42;1^
And plead the cause of the widow.”

[NOTE]
====
. Or “the orphan.”
====

[[v23-1-18]]

^<<v23-1-18,18>>^ “Come, now, and let us set matters straight between us,” says Jehovah.
“Though your sins are like scarlet,
They will be made as white as snow;
Though they are as red as crimson cloth,
They will become like wool.

[[v23-1-19]]

^<<v23-1-19,19>>^ If you show willingness and listen,
You will eat the good things of the land.

[[v23-1-20]]

^<<v23-1-20,20>>^ But if you refuse and rebel,
You will be devoured by the sword,
For the mouth of Jehovah has spoken it.”

[[v23-1-21]]

^<<v23-1-21,21>>^ How the faithful city has become a prostitute!
She was full of justice;
Righteousness used to lodge in her,
But now murderers.

[[v23-1-22]]

^<<v23-1-22,22>>^ Your silver has become dross,
And your beer^&#42;1^ is diluted with water.

[NOTE]
====
. Or “wheat beer.”
====

[[v23-1-23]]

^<<v23-1-23,23>>^ Your princes are stubborn and partners with thieves.
Every one of them loves a bribe and chases after gifts.
They do not grant justice to the fatherless,^&#42;1^
And the legal case of the widow never reaches them.

[NOTE]
====
. Or “the orphans.”
====

[[v23-1-24]]

^<<v23-1-24,24>>^ Therefore the true Lord, Jehovah of armies,
The Powerful One of Israel, declares:
“Ah! I will rid myself of my adversaries,
And I will take revenge on my enemies.

[[v23-1-25]]

^<<v23-1-25,25>>^ I will turn my hand against you,
I will smelt away your dross as with lye,
And I will remove all your impurities.

[[v23-1-26]]

^<<v23-1-26,26>>^ I will restore your judges as in the beginning
And your advisers as at the start.
After this you will be called City of Righteousness, Faithful Town.

[[v23-1-27]]

^<<v23-1-27,27>>^ With justice Zion will be redeemed,
And her people who return, with righteousness.

[[v23-1-28]]

^<<v23-1-28,28>>^ The rebels and the sinners will be broken together,
And those leaving Jehovah will come to their finish.

[[v23-1-29]]

^<<v23-1-29,29>>^ For they will be ashamed of the mighty trees that you desired,
And you will be disgraced because of the gardens^&#42;1^ that you chose.

[NOTE]
====
. Apparently trees and gardens connected with idolatrous worship.
====

[[v23-1-30]]

^<<v23-1-30,30>>^ For you will become like a big tree with withering leaves,
And like a garden without water.

[[v23-1-31]]

^<<v23-1-31,31>>^ The strong man will become tow,^&#42;1^
And his work a spark;
Both of them will go up in flames together,
With no one to extinguish them.”

[NOTE]
====
. A flammable ropelike fiber.
====

'''

xref:022-song-of-solomon/022-song-of-solomon-008.adoc#v22-8-0[&#60; Capítulo Anterior] | <<v23-1-0,Topo>> | xref:023-isaiah/023-isaiah-002.adoc#v23-2-0[Próximo Capítulo &#62;]