include::./index.adoc[]

[[v23-36-0]]
=== Isaiah, 36
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-36-1]]

^<<v23-36-1,1>>^ In the 14th year of King Hez·e·kiʹah, Sen·nachʹer·ib the king of As·syrʹi·a came up against all the fortified cities of Judah and captured them.

[[v23-36-2]]

^<<v23-36-2,2>>^ The king of As·syrʹi·a then sent the Rabʹsha·keh^&#42;1^ with a vast army from Laʹchish to King Hez·e·kiʹah in Jerusalem. They took up a position by the conduit of the upper pool, which is at the highway of the laundryman’s field.

[NOTE]
====
. Or “the chief cupbearer.”
====

[[v23-36-3]]

^<<v23-36-3,3>>^ Then E·liʹa·kim son of Hil·kiʹah, who was in charge of the household,^&#42;1^ Shebʹna the secretary, and Joʹah son of Aʹsaph the recorder came out to him.

[NOTE]
====
. Or “palace.”
====

[[v23-36-4]]

^<<v23-36-4,4>>^ So the Rabʹsha·keh said to them: “Please, say to Hez·e·kiʹah, ‘This is what the great king, the king of As·syrʹi·a, says: “What is the basis for your confidence?

[[v23-36-5]]

^<<v23-36-5,5>>^ You are saying, ‘I have a strategy and the power to wage war,’ but these are empty words. In whom have you put trust, so that you dare to rebel against me?

[[v23-36-6]]

^<<v23-36-6,6>>^ Look! You trust in the support of this crushed reed, Egypt, which if a man should lean on it would enter into his palm and pierce it. That is the way Pharʹaoh king of Egypt is to all those who trust in him.

[[v23-36-7]]

^<<v23-36-7,7>>^ And if you should say to me, ‘We trust in Jehovah our God,’ is he not the one whose high places and altars Hez·e·kiʹah has removed, while he says to Judah and Jerusalem, ‘You should bow down before this altar’?”’

[[v23-36-8]]

^<<v23-36-8,8>>^ So now make this wager, please, with my lord the king of As·syrʹi·a: I will give you 2,000 horses if you are able to find enough riders for them.

[[v23-36-9]]

^<<v23-36-9,9>>^ How, then, could you drive back even one governor who is the least of my lord’s servants, while you put your trust in Egypt for chariots and for horsemen?

[[v23-36-10]]

^<<v23-36-10,10>>^ Now is it without authorization from Jehovah that I have come up against this land to destroy it? Jehovah himself said to me, ‘Go up against this land and destroy it.’”

[[v23-36-11]]

^<<v23-36-11,11>>^ At this E·liʹa·kim and Shebʹna and Joʹah said to the Rabʹsha·keh: “Speak to your servants, please, in the Ar·a·maʹic^&#42;1^ language, for we can understand it; do not speak to us in the language of the Jews in the hearing of the people on the wall.”

[NOTE]
====
. Or “Syrian.”
====

[[v23-36-12]]

^<<v23-36-12,12>>^ But the Rabʹsha·keh said: “Is it just to your lord and to you that my lord sent me to speak these words? Is it not also to the men who sit on the wall, those who will eat their own excrement and drink their own urine along with you?”

[[v23-36-13]]

^<<v23-36-13,13>>^ Then the Rabʹsha·keh stood and called out loudly in the language of the Jews, saying: “Hear the word of the great king, the king of As·syrʹi·a.

[[v23-36-14]]

^<<v23-36-14,14>>^ This is what the king says, ‘Do not let Hez·e·kiʹah deceive you, for he is not able to rescue you.

[[v23-36-15]]

^<<v23-36-15,15>>^ And do not let Hez·e·kiʹah cause you to trust in Jehovah by saying: “Jehovah will surely rescue us, and this city will not be given into the hand of the king of As·syrʹi·a.”

[[v23-36-16]]

^<<v23-36-16,16>>^ Do not listen to Hez·e·kiʹah, for this is what the king of As·syrʹi·a says: “Make peace with me and surrender,^&#42;1^ and each of you will eat from his own vine and from his own fig tree and will drink the water of his own cistern,

[NOTE]
====
. Lit., “Make with me a blessing and come out to me.”
====

[[v23-36-17]]

^<<v23-36-17,17>>^ until I come and take you to a land like your own land, a land of grain and new wine, a land of bread and vineyards.

[[v23-36-18]]

^<<v23-36-18,18>>^ Do not let Hez·e·kiʹah mislead you by saying, ‘Jehovah will rescue us.’ Have any of the gods of the nations rescued their land out of the hand of the king of As·syrʹi·a?

[[v23-36-19]]

^<<v23-36-19,19>>^ Where are the gods of Haʹmath and Arʹpad? Where are the gods of Seph·ar·vaʹim? And have they rescued Sa·marʹi·a out of my hand?

[[v23-36-20]]

^<<v23-36-20,20>>^ Who among all the gods of these lands have rescued their land out of my hand, so that Jehovah should rescue Jerusalem out of my hand?”’”

[[v23-36-21]]

^<<v23-36-21,21>>^ But they kept silent and did not say a word to him in reply, for the order of the king was, “You must not answer him.”

[[v23-36-22]]

^<<v23-36-22,22>>^ But E·liʹa·kim son of Hil·kiʹah, who was in charge of the household,^&#42;1^ Shebʹna the secretary, and Joʹah son of Aʹsaph the recorder came to Hez·e·kiʹah with their garments ripped apart and told him the words of the Rabʹsha·keh.

[NOTE]
====
. Or “palace.”
====

'''

xref:023-isaiah/023-isaiah-035.adoc#v23-35-0[&#60; Capítulo Anterior] | <<v23-36-0,Topo>> | xref:023-isaiah/023-isaiah-037.adoc#v23-37-0[Próximo Capítulo &#62;]