include::./index.adoc[]

[[v23-17-0]]
=== Isaiah, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-17-1]]

^<<v23-17-1,1>>^ A pronouncement against Damascus:
“Look! Damascus will cease to be a city,
And it will become a heap of ruins.

[[v23-17-2]]

^<<v23-17-2,2>>^ The cities of A·roʹer will be abandoned;
They will become places for flocks to lie down
With no one to make them afraid.

[[v23-17-3]]

^<<v23-17-3,3>>^ Fortified cities will disappear from Eʹphra·im,
And the kingdom from Damascus;
And those remaining of Syria
Will be like the glory of the Israelites,”^&#42;1^ declares Jehovah of armies.

[NOTE]
====
. Lit., “sons of Israel.”
====

[[v23-17-4]]

^<<v23-17-4,4>>^ “In that day the glory of Jacob will diminish,
And his healthy body^&#42;1^ will grow thin.

[NOTE]
====
. Lit., “the fat of his flesh.”
====

[[v23-17-5]]

^<<v23-17-5,5>>^ It will be as when the harvester is gathering the standing grain
And his arm harvests the ears of grain,
Like when one gleans grain in the Valley^&#42;1^ of Rephʹa·im.

[NOTE]
====
. Or “Low Plain.”
====

[[v23-17-6]]

^<<v23-17-6,6>>^ Only gleanings will be left,
As when an olive tree is beaten:
Only two or three ripe olives remain on the highest branch,
Only four or five on its fruit-bearing branches,” declares Jehovah the God of Israel.

[[v23-17-7]]

^<<v23-17-7,7>>^ In that day man will look up to his Maker, and his eyes will gaze at the Holy One of Israel.

[[v23-17-8]]

^<<v23-17-8,8>>^ He will not look to the altars, the work of his hands; and he will not gaze at what his fingers have made, either the sacred poles^&#42;1^ or the incense stands.

[NOTE]
====
. See Glossary.
====

[[v23-17-9]]

^<<v23-17-9,9>>^ In that day his fortress cities will become like an abandoned site in the woodland,
Like a branch that was abandoned before the Israelites;
It will become a wasteland.

[[v23-17-10]]

^<<v23-17-10,10>>^ For you have forgotten the God of your salvation;
You have failed to remember the Rock of your fortress.
That is why you plant beautiful^&#42;1^ plantations
And set it with the shoot of a stranger.^&#42;2^

[NOTE]
====
. Or “pleasant.”
. Or “a foreign god.”
====

[[v23-17-11]]

^<<v23-17-11,11>>^ In the day you carefully fence in your plantation,
In the morning you make your seed sprout,
But the harvest will vanish in the day of disease and incurable pain.

[[v23-17-12]]

^<<v23-17-12,12>>^ Listen! There is a commotion of many peoples,
Who are as boisterous as the seas!
There is an uproar of nations,
Whose sound is like the roar of mighty waters!

[[v23-17-13]]

^<<v23-17-13,13>>^ The nations will make a sound like the roar of many waters.
He will rebuke them, and they will flee far away,
Chased like the chaff of the mountains before a wind,
Like a whirling thistle^&#42;1^ before a storm wind.

[NOTE]
====
. Or “Like tumbleweed.”
====

[[v23-17-14]]

^<<v23-17-14,14>>^ In the evening there is terror.
Before morning they are no more.
This is the share of those pillaging us
And the lot of those plundering us.

'''

xref:023-isaiah/023-isaiah-016.adoc#v23-16-0[&#60; Capítulo Anterior] | <<v23-17-0,Topo>> | xref:023-isaiah/023-isaiah-018.adoc#v23-18-0[Próximo Capítulo &#62;]