include::./index.adoc[]

[[v23-28-0]]
=== Isaiah, 28
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-28-1]]

^<<v23-28-1,1>>^ Woe to the showy^&#42;1^ crown^&#42;2^ of the drunkards of Eʹphra·im
And the fading blossom of its glorious beauty,
Which is on the head of the fertile valley of those overcome with wine!

[NOTE]
====
. Or “haughty; proud.”
. Apparently referring to the capital city, Samaria.
====

[[v23-28-2]]

^<<v23-28-2,2>>^ Look! Jehovah has someone strong and mighty.
Like a thundering hailstorm, a destructive windstorm,
Like a thunderstorm of powerful floodwaters,
He will forcefully hurl it down to the earth.

[[v23-28-3]]

^<<v23-28-3,3>>^ The showy^&#42;1^ crowns of the drunkards of Eʹphra·im
Will be trampled underfoot.

[NOTE]
====
. Or “haughty; proud.”
====

[[v23-28-4]]

^<<v23-28-4,4>>^ And the fading flower of its glorious beauty,
Which is on the head of the fertile valley,
Will become like the early fig before summer.
When someone sees it, he swallows it as soon as it is in his hand.

[[v23-28-5]]

^<<v23-28-5,5>>^ In that day Jehovah of armies will become a glorious crown and a beautiful garland to those left of his people.

[[v23-28-6]]

^<<v23-28-6,6>>^ And he will become a spirit of justice to the one who sits in judgment and a source of mightiness to those who repel the attack at the gate.

[[v23-28-7]]

^<<v23-28-7,7>>^ And these also go astray because of wine;
Their alcoholic beverages make them stagger.
Priest and prophet go astray because of alcohol;
The wine confuses them,
And they stagger from their alcohol;
Their vision makes them go astray,
And they stumble in judgment.

[[v23-28-8]]

^<<v23-28-8,8>>^ For their tables are full of filthy vomit
—There is no place without it.

[[v23-28-9]]

^<<v23-28-9,9>>^ To whom will one impart knowledge,
And to whom will one explain the message?
To those who have just been weaned from milk,
Those just taken away from the breasts?

[[v23-28-10]]

^<<v23-28-10,10>>^ For it is “command after command, command after command,
Line by line, line by line,^&#42;1^
A little here, a little there.”

[NOTE]
====
. Or “Measuring line upon measuring line, measuring line upon measuring line.”
====

[[v23-28-11]]

^<<v23-28-11,11>>^ So by means of those with stammering speech^&#42;1^ and a foreign language, he will speak to this people.

[NOTE]
====
. Lit., “lip.”
====

[[v23-28-12]]

^<<v23-28-12,12>>^ He once told them: “This is the resting-place. Let the weary one rest; this is the place of refreshment,” but they refused to listen.

[[v23-28-13]]

^<<v23-28-13,13>>^ So to them the word of Jehovah will be:
“Command after command, command after command,
Line by line, line by line,^&#42;1^
A little here, a little there,”
So that when they walk,
They will stumble and fall backward
And be broken and ensnared and caught.

[NOTE]
====
. Or “Measuring line upon measuring line, measuring line upon measuring line.”
====

[[v23-28-14]]

^<<v23-28-14,14>>^ So hear the word of Jehovah, you boasters,
You rulers of this people in Jerusalem,

[[v23-28-15]]

^<<v23-28-15,15>>^ For you men say:
“We have made a covenant with Death,
And with the Grave^&#42;1^ we have made an agreement.^&#42;2^
When the raging flash flood passes through,
It will not reach us,
For we have made a lie our refuge
And we have hidden ourselves in falsehood.”

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
. Or possibly, “effected a vision.”
====

[[v23-28-16]]

^<<v23-28-16,16>>^ Therefore this is what the Sovereign Lord Jehovah says:
“Here I am laying as a foundation in Zion a tested stone,
The precious cornerstone of a sure foundation.
No one exercising faith will panic.

[[v23-28-17]]

^<<v23-28-17,17>>^ And I will make justice the measuring line
And righteousness the leveling tool.^&#42;1^
The hail will sweep away the refuge of lies,
And the waters will flood out the hiding place.

[NOTE]
====
. Or “plumb line.”
====

[[v23-28-18]]

^<<v23-28-18,18>>^ Your covenant with Death will be dissolved,
And your agreement with the Grave^&#42;1^ will not stand.
When the raging flash flood passes through,
You will be crushed by it.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v23-28-19]]

^<<v23-28-19,19>>^ As often as it passes through,
It will sweep you away;
For it will pass through morning after morning,
During the day and during the night.
Only terror will make them understand what was heard.”^&#42;1^

[NOTE]
====
. Or possibly, “When they understand, they will feel sheer terror.”
====

[[v23-28-20]]

^<<v23-28-20,20>>^ For the bed is too short to stretch out on,
And the woven sheet is too narrow to wrap up in.

[[v23-28-21]]

^<<v23-28-21,21>>^ For Jehovah will rise up as at Mount Pe·raʹzim;
He will rouse himself as in the valley^&#42;1^ near Gibʹe·on,
That he may do his deed—his strange deed—
And that he may carry out his work—his unusual work.

[NOTE]
====
. Or “low plain.”
====

[[v23-28-22]]

^<<v23-28-22,22>>^ Now do not scoff,
So that your bonds may not be further tightened,
For I have heard from the Sovereign Lord, Jehovah of armies,
That an extermination has been determined for all the land.^&#42;1^

[NOTE]
====
. Or “for the whole earth.”
====

[[v23-28-23]]

^<<v23-28-23,23>>^ Give ear and listen to my voice;
Pay attention and listen to what I say.

[[v23-28-24]]

^<<v23-28-24,24>>^ Does the plower keep plowing all day before he sows seed?
Does he continually break up and harrow his ground?

[[v23-28-25]]

^<<v23-28-25,25>>^ When he has smoothed out its surface,
Does he not then scatter black cumin and sow cumin,
And does he not plant wheat, millet, and barley in their places
And spelt around the edges?

[[v23-28-26]]

^<<v23-28-26,26>>^ For He teaches^&#42;1^ him the right way;
His God instructs him.

[NOTE]
====
. Or “disciplines; chastises.”
====

[[v23-28-27]]

^<<v23-28-27,27>>^ For black cumin is not crushed with a threshing sledge,
And a wagon wheel is not driven over cumin.
Rather, black cumin is beaten out with a rod,
And cumin with a staff.

[[v23-28-28]]

^<<v23-28-28,28>>^ Does a person crush grain for bread?
No, he does not thresh it incessantly;
And when he drives the roller of his wagon over it with his horses,
He does not crush it.

[[v23-28-29]]

^<<v23-28-29,29>>^ This also comes from Jehovah of armies,
Whose counsel^&#42;1^ is wonderful
And whose achievements are great.^&#42;2^

[NOTE]
====
. Or “purpose.”
. Or “And whose practical wisdom is great.”
====

'''

xref:023-isaiah/023-isaiah-027.adoc#v23-27-0[&#60; Capítulo Anterior] | <<v23-28-0,Topo>> | xref:023-isaiah/023-isaiah-029.adoc#v23-29-0[Próximo Capítulo &#62;]