include::./index.adoc[]

[[v23-10-0]]
=== Isaiah, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-10-1]]

^<<v23-10-1,1>>^ Woe to those who enact harmful regulations,
Who constantly draft oppressive decrees,

[[v23-10-2]]

^<<v23-10-2,2>>^ To deny the legal claim of the poor,
To deprive the lowly among my people of justice,
Making widows their spoil
And fatherless children^&#42;1^ their plunder!

[NOTE]
====
. Or “And orphans.”
====

[[v23-10-3]]

^<<v23-10-3,3>>^ What will you do on the day of reckoning,^&#42;1^
When destruction comes from afar?
To whom will you flee for assistance,
And where will you leave your wealth?^&#42;2^

[NOTE]
====
. Or “punishment.”
. Or “glory.”
====

[[v23-10-4]]

^<<v23-10-4,4>>^ Nothing remains except to crouch among the prisoners
Or to fall among the slain.
In view of all this, his anger has not turned back,
But his hand is still stretched out to strike.

[[v23-10-5]]

^<<v23-10-5,5>>^ “Aha! the As·syrʹi·an,
The rod to express my anger
And the staff in their hand for my denunciation!

[[v23-10-6]]

^<<v23-10-6,6>>^ I will send him against an apostate nation,
Against the people who infuriated me;
I will command him to take much spoil and much plunder
And to trample them like mud in the streets.

[[v23-10-7]]

^<<v23-10-7,7>>^ But he will not be inclined this way
And his heart will not scheme this way;
For it is in his heart to annihilate,
To cut off many nations, not a few.

[[v23-10-8]]

^<<v23-10-8,8>>^ For he says,
‘Are not my princes all kings?

[[v23-10-9]]

^<<v23-10-9,9>>^ Is not Calʹno just like Carʹche·mish?
Is not Haʹmath like Arʹpad?
Is not Sa·marʹi·a like Damascus?

[[v23-10-10]]

^<<v23-10-10,10>>^ My hand has seized the kingdoms of the worthless gods,
Whose graven images were more than those of Jerusalem and Sa·marʹi·a!

[[v23-10-11]]

^<<v23-10-11,11>>^ Will I not also do to Jerusalem and her idols
Just as I have done to Sa·marʹi·a and to her worthless gods?’

[[v23-10-12]]

^<<v23-10-12,12>>^ “When Jehovah finishes all his work on Mount Zion and in Jerusalem, He^&#42;1^ will punish the king of As·syrʹi·a for his insolent heart and his proud, arrogant gaze.

[NOTE]
====
. Lit., “I.”
====

[[v23-10-13]]

^<<v23-10-13,13>>^ For he says,
‘I will do this by the strength of my hand
And with my wisdom, for I am wise.
I will remove the boundaries of peoples
And pillage their treasures,
And I will subdue the inhabitants like a mighty one.

[[v23-10-14]]

^<<v23-10-14,14>>^ Like a man reaching into a nest,
My hand will seize the resources of the peoples;
And like one gathering abandoned eggs,
I will gather the whole earth!
No one will flutter his wings or open his mouth or chirp.’”

[[v23-10-15]]

^<<v23-10-15,15>>^ Will the ax exalt itself over the one who chops with it?
Will the saw exalt itself over the one who saws with it?
Could a staff wave the one who lifts it?
Or could a rod lift up the one who is not made of wood?

[[v23-10-16]]

^<<v23-10-16,16>>^ Therefore the true Lord, Jehovah of armies,
Will inflict emaciation on his fat ones,
And beneath his glory he will kindle a blazing fire.

[[v23-10-17]]

^<<v23-10-17,17>>^ Israel’s Light will become a fire,
And his Holy One a flame;
It will blaze up and consume his weeds and his thornbushes in one day.

[[v23-10-18]]

^<<v23-10-18,18>>^ He will utterly^&#42;1^ do away with the glory of his forest and his orchard;
It will be as when a sick man wastes away.

[NOTE]
====
. Or “from soul to flesh.”
====

[[v23-10-19]]

^<<v23-10-19,19>>^ The rest of the trees of his forest
Will be so few that a boy could list them.

[[v23-10-20]]

^<<v23-10-20,20>>^ In that day those remaining of Israel
And the survivors of the house of Jacob
Will no longer support themselves on the one who struck them;
But they will support themselves on Jehovah,
The Holy One of Israel, with faithfulness.

[[v23-10-21]]

^<<v23-10-21,21>>^ Only a remnant will return,
The remnant of Jacob, to the Mighty God.

[[v23-10-22]]

^<<v23-10-22,22>>^ For though your people, O Israel,
Are as the grains of sand of the sea,
Only a remnant of them will return.
An extermination has been decided on,
And justice^&#42;1^ will engulf them.

[NOTE]
====
. Or “punishment.”
====

[[v23-10-23]]

^<<v23-10-23,23>>^ Yes, the extermination decided on by the Sovereign Lord, Jehovah of armies,
Will be carried out in the entire land.

[[v23-10-24]]

^<<v23-10-24,24>>^ Therefore this is what the Sovereign Lord, Jehovah of armies, says: “Do not be afraid, my people who are dwelling in Zion, because of the As·syrʹi·an, who used to strike you with the rod and to lift up his staff against you as Egypt did.

[[v23-10-25]]

^<<v23-10-25,25>>^ For in a very little while the denunciation will come to an end; my anger will be directed to their destruction.

[[v23-10-26]]

^<<v23-10-26,26>>^ Jehovah of armies will brandish a whip against him, as when he defeated Midʹi·an by the rock Oʹreb. And his staff will be over the sea, and he will raise it as he did with Egypt.

[[v23-10-27]]

^<<v23-10-27,27>>^ In that day his load will depart from on your shoulder,
And his yoke from on your neck,
And the yoke will be broken because of the oil.”

[[v23-10-28]]

^<<v23-10-28,28>>^ He has come to Aiʹath;
He has passed through Migʹron;
At Michʹmash he deposits his baggage.

[[v23-10-29]]

^<<v23-10-29,29>>^ They have passed over the ford;
They spend the night at Geʹba;
Raʹmah trembles, Gibʹe·ah of Saul has fled.

[[v23-10-30]]

^<<v23-10-30,30>>^ Cry out and scream, O daughter of Galʹlim!
Pay attention, O Laʹi·shah!
O poor Anʹa·thoth!

[[v23-10-31]]

^<<v23-10-31,31>>^ Mad·meʹnah has run away.
The inhabitants of Geʹbim have sought shelter.

[[v23-10-32]]

^<<v23-10-32,32>>^ This very day he will halt in Nob.
He shakes his fist at the mountain of the daughter of Zion,
The hill of Jerusalem.

[[v23-10-33]]

^<<v23-10-33,33>>^ Look! The true Lord, Jehovah of armies,
Is chopping off branches with a terrible crash;
The tallest trees are being cut down,
And the lofty are brought low.

[[v23-10-34]]

^<<v23-10-34,34>>^ He strikes down the thickets of the forest with an iron tool,^&#42;1^
And Lebʹa·non will fall by a mighty one.

[NOTE]
====
. Or “an ax.”
====

'''

xref:023-isaiah/023-isaiah-009.adoc#v23-9-0[&#60; Capítulo Anterior] | <<v23-10-0,Topo>> | xref:023-isaiah/023-isaiah-011.adoc#v23-11-0[Próximo Capítulo &#62;]