include::./index.adoc[]

[[v23-54-0]]
=== Isaiah, 54
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-54-1]]

^<<v23-54-1,1>>^ “Shout joyfully, you barren woman who has not given birth!
Become cheerful and cry out for joy, you who never had birth pains,
For the sons^&#42;1^ of the desolate one are more numerous
Than the sons of the woman with a husband,”^&#42;2^ says Jehovah.

[NOTE]
====
. Or “children.”
. Or “master.”
====

[[v23-54-2]]

^<<v23-54-2,2>>^ “Make the place of your tent more spacious.
Stretch out the tent cloths of your grand tabernacle.
Do not hold back, lengthen your tent cords,
And make your tent pins strong.

[[v23-54-3]]

^<<v23-54-3,3>>^ For you will spread out to the right and to the left.
Your offspring will take possession of nations,
And they will inhabit the desolated cities.

[[v23-54-4]]

^<<v23-54-4,4>>^ Do not be afraid, for you will not be put to shame;
And do not feel humiliated, for you will not be disappointed.
For you will forget the shame of your youth,
And the disgrace of your widowhood you will remember no more.”

[[v23-54-5]]

^<<v23-54-5,5>>^ “For your Grand Maker is as your husband,^&#42;1^
Jehovah of armies is his name,
And the Holy One of Israel is your Repurchaser.
He will be called the God of the whole earth.

[NOTE]
====
. Or “master.”
====

[[v23-54-6]]

^<<v23-54-6,6>>^ For Jehovah called you as if you were an abandoned wife and grief-stricken,^&#42;1^
Like a wife married in youth and then rejected,” says your God.

[NOTE]
====
. Lit., “hurt in spirit.”
====

[[v23-54-7]]

^<<v23-54-7,7>>^ “For a brief moment I abandoned you,
But with great mercy I will gather you back.

[[v23-54-8]]

^<<v23-54-8,8>>^ In a flood of indignation I hid my face from you for a moment,
But with everlasting loyal love I will have mercy on you,” says your Repurchaser, Jehovah.

[[v23-54-9]]

^<<v23-54-9,9>>^ “This is like the days of Noah to me.
Just as I have sworn that the waters of Noah will no more cover the earth,
So I swear that I will no more become indignant toward you or rebuke you.

[[v23-54-10]]

^<<v23-54-10,10>>^ For the mountains may be removed
And the hills may be shaken,
But my loyal love will not be removed from you,
Nor will my covenant of peace be shaken,” says Jehovah, the One having mercy on you.

[[v23-54-11]]

^<<v23-54-11,11>>^ “O afflicted woman, storm-tossed, uncomforted,
I am laying your stones with hard mortar
And your foundation with sapphires.

[[v23-54-12]]

^<<v23-54-12,12>>^ I will make your battlements of rubies,
Your gates of sparkling stones,^&#42;1^
And all your boundaries of precious stones.

[NOTE]
====
. Or “of stones of fire.”
====

[[v23-54-13]]

^<<v23-54-13,13>>^ And all your sons^&#42;1^ will be taught by Jehovah,
And the peace of your sons^&#42;2^ will be abundant.

[NOTE]
====
. Or “children.”
. Or “children.”
====

[[v23-54-14]]

^<<v23-54-14,14>>^ You will be firmly established in righteousness.
You will be far removed from oppression,
You will fear nothing and have no cause for terror,
For it will not come near you.

[[v23-54-15]]

^<<v23-54-15,15>>^ If anyone should attack you,
It will not be at my orders.
Whoever makes an attack on you will fall because of you.”

[[v23-54-16]]

^<<v23-54-16,16>>^ “Look! I myself created the craftsman,
Who blows on the charcoal fire,
And his work produces a weapon.
I myself also created the destructive man to bring ruin.

[[v23-54-17]]

^<<v23-54-17,17>>^ No weapon formed against you will have any success,
And you will condemn any tongue that rises up against you in the judgment.
This is the heritage^&#42;1^ of the servants of Jehovah,
And their righteousness is from me,” declares Jehovah.

[NOTE]
====
. Or “inheritance.”
====

'''

xref:023-isaiah/023-isaiah-053.adoc#v23-53-0[&#60; Capítulo Anterior] | <<v23-54-0,Topo>> | xref:023-isaiah/023-isaiah-055.adoc#v23-55-0[Próximo Capítulo &#62;]