include::./index.adoc[]

[[v23-53-0]]
=== Isaiah, 53
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-53-1]]

^<<v23-53-1,1>>^ Who has put faith in the thing heard from us?^&#42;1^
And as for the arm of Jehovah, to whom has it been revealed?

[NOTE]
====
. Or possibly, “in what we heard?”
====

[[v23-53-2]]

^<<v23-53-2,2>>^ He will come up like a twig before him,^&#42;1^ like a root out of parched land.
No stately form does he have, nor any splendor;
And when we see him, his appearance does not draw us to him.^&#42;2^

[NOTE]
====
. “Him” could refer to an observer in general or to God.
. Or “there is no special appearance that we should desire him.”
====

[[v23-53-3]]

^<<v23-53-3,3>>^ He was despised and was avoided by men,
A man who was meant for^&#42;1^ pains and was familiar with sickness.
It was as if his face were hidden from us.^&#42;2^
He was despised, and we held him as of no account.

[NOTE]
====
. Or “who understood.”
. Or possibly, “He was like someone from whom people turned their faces.”
====

[[v23-53-4]]

^<<v23-53-4,4>>^ Truly he himself carried our sicknesses,
And he bore our pains.
But we considered him as plagued, stricken by God and afflicted.

[[v23-53-5]]

^<<v23-53-5,5>>^ But he was pierced for our transgression;
He was crushed for our errors.
He bore the punishment for our peace,
And because of his wounds we were healed.

[[v23-53-6]]

^<<v23-53-6,6>>^ Like sheep we have all wandered about,
Each has turned his own way,
And Jehovah has caused the error of us all to meet up with him.

[[v23-53-7]]

^<<v23-53-7,7>>^ He was oppressed and he let himself be afflicted,
But he would not open his mouth.
He was brought like a sheep to the slaughter,
Like a ewe that is silent before its shearers,
And he would not open his mouth.

[[v23-53-8]]

^<<v23-53-8,8>>^ Because of restraint^&#42;1^ and judgment he was taken away;
And who will concern himself with the details of his generation?^&#42;2^
For he was cut off from the land of the living;
Because of the transgression of my people he received the stroke.^&#42;3^

[NOTE]
====
. Or “oppression.”
. Or “his manner of life?”
. Or “was struck dead.”
====

[[v23-53-9]]

^<<v23-53-9,9>>^ And he was given a burial place^&#42;1^ with the wicked,
And with the rich^&#42;2^ in his death,
Although he had done no wrong^&#42;3^
And there was no deception in his mouth.

[NOTE]
====
. Or “And one will give his burial place.”
. Lit., “a rich man.”
. Or “no violence.”
====

[[v23-53-10]]

^<<v23-53-10,10>>^ But it was Jehovah’s will^&#42;1^ to crush him, and he let him become sick.
If you will present his life^&#42;2^ as a guilt offering,
He will see his offspring,^&#42;3^ he will prolong his days,
And through him the delight^&#42;4^ of Jehovah will have success.

[NOTE]
====
. Or “But Jehovah took delight.”
. Or “soul.”
. Lit., “seed.”
. Or “will; good pleasure.”
====

[[v23-53-11]]

^<<v23-53-11,11>>^ Because of his anguish,^&#42;1^ he will see and be satisfied.
By means of his knowledge the righteous one, my servant,
Will bring a righteous standing to many people,
And their errors he will bear.

[NOTE]
====
. Or “the trouble of his soul.”
====

[[v23-53-12]]

^<<v23-53-12,12>>^ For that reason I will assign him a portion among the many,
And he will apportion the spoil with the mighty,
Because he poured out his life^&#42;1^ even to death
And was counted among the transgressors;
He carried the sin of many people,
And he interceded for the transgressors.

[NOTE]
====
. Or “soul.”
====

'''

xref:023-isaiah/023-isaiah-052.adoc#v23-52-0[&#60; Capítulo Anterior] | <<v23-53-0,Topo>> | xref:023-isaiah/023-isaiah-054.adoc#v23-54-0[Próximo Capítulo &#62;]