include::./index.adoc[]

[[v23-62-0]]
=== Isaiah, 62
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-62-1]]

^<<v23-62-1,1>>^ For the sake of Zion I will not keep silent,
And for the sake of Jerusalem I will not keep still
Until her righteousness shines like a bright light
And her salvation burns like a torch.

[[v23-62-2]]

^<<v23-62-2,2>>^ “The nations will see your righteousness, O woman,
And all kings your glory.
And you will be called by a new name,
Which Jehovah’s own mouth will designate.

[[v23-62-3]]

^<<v23-62-3,3>>^ You will become a crown of beauty in the hand of Jehovah,
A royal turban in the palm of your God.

[[v23-62-4]]

^<<v23-62-4,4>>^ No more will you be called an abandoned woman,
And your land will no longer be called desolate.
But you will be called My Delight Is in Her,
And your land will be called the Married One.
For Jehovah will take delight in you,
And your land will be as one married.

[[v23-62-5]]

^<<v23-62-5,5>>^ For just as a young man marries a virgin,
Your sons will marry you.
With the rejoicing of a bridegroom over a bride,
Your God will rejoice over you.

[[v23-62-6]]

^<<v23-62-6,6>>^ Upon your walls, O Jerusalem, I have commissioned watchmen.
Continuously, all day long and all night long, they should not be silent.
You who make mention of Jehovah,
Do not rest,

[[v23-62-7]]

^<<v23-62-7,7>>^ And do not give him any rest until he firmly establishes Jerusalem,
Yes, until he makes her the praise of the earth.”

[[v23-62-8]]

^<<v23-62-8,8>>^ Jehovah has sworn an oath with his right hand, with his strong arm:
“I will no longer give your grain as food to your enemies,
Nor will foreigners drink your new wine, for which you have toiled.

[[v23-62-9]]

^<<v23-62-9,9>>^ But those gathering it will eat it and they will praise Jehovah;
And those collecting it will drink it in my holy courtyards.”

[[v23-62-10]]

^<<v23-62-10,10>>^ Pass through, pass through the gates.
Clear the way for the people.
Build up, build up the highway.
Rid it of stones.
Raise up a signal^&#42;1^ for the peoples.

[NOTE]
====
. Or “signal pole.”
====

[[v23-62-11]]

^<<v23-62-11,11>>^ Look! Jehovah has proclaimed to the ends of the earth:
“Say to the daughter of Zion,
‘Look! Your salvation is coming.
Look! His reward is with him,
And the wage he pays is before him.’”

[[v23-62-12]]

^<<v23-62-12,12>>^ They will be called the holy people, those repurchased by Jehovah,
And you will be called Sought After, a City Not Abandoned.

'''

xref:023-isaiah/023-isaiah-061.adoc#v23-61-0[&#60; Capítulo Anterior] | <<v23-62-0,Topo>> | xref:023-isaiah/023-isaiah-063.adoc#v23-63-0[Próximo Capítulo &#62;]