include::./index.adoc[]

[[v23-23-0]]
=== Isaiah, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-23-1]]

^<<v23-23-1,1>>^ A pronouncement about Tyre:
Wail, you ships of Tarʹshish!
For the port has been destroyed; it cannot be entered.
From the land of Kitʹtim it has been revealed to them.

[[v23-23-2]]

^<<v23-23-2,2>>^ Be silent, you inhabitants of the coastland.
The merchants from Siʹdon who cross the sea have filled you.

[[v23-23-3]]

^<<v23-23-3,3>>^ Over many waters went the grain^&#42;1^ of Shiʹhor,^&#42;2^
The harvest of the Nile, her revenue,
Bringing the profit of the nations.

[NOTE]
====
. Lit., “seed.”
. That is, a branch of the Nile River.
====

[[v23-23-4]]

^<<v23-23-4,4>>^ Be ashamed, O Siʹdon, you stronghold of the sea,
Because the sea has said:
“I have not had birth pains, and I have not given birth,
Nor have I brought up young men or raised young women.”^&#42;1^

[NOTE]
====
. Lit., “virgins.”
====

[[v23-23-5]]

^<<v23-23-5,5>>^ As when they heard the report about Egypt,
People will be in anguish over the report about Tyre.

[[v23-23-6]]

^<<v23-23-6,6>>^ Cross over to Tarʹshish!
Wail, you inhabitants of the coastland!

[[v23-23-7]]

^<<v23-23-7,7>>^ Is this your city that was exultant from long ago, from her early times?
Her feet used to take her to distant lands to reside.

[[v23-23-8]]

^<<v23-23-8,8>>^ Who has decided this against Tyre,
The bestower of crowns,
Whose merchants were princes,
Whose tradesmen were honored in all the earth?

[[v23-23-9]]

^<<v23-23-9,9>>^ Jehovah of armies himself has decided this,
To profane her pride over all her beauty,
To humiliate all those who were honored throughout the earth.

[[v23-23-10]]

^<<v23-23-10,10>>^ Cross over your land like the Nile River, O daughter of Tarʹshish.
There is no longer any shipyard.^&#42;1^

[NOTE]
====
. Or possibly, “harbor.”
====

[[v23-23-11]]

^<<v23-23-11,11>>^ He has stretched his hand out over the sea;
He has shaken kingdoms.
Jehovah has ordered the annihilation of Phoe·niʹcia’s strongholds.

[[v23-23-12]]

^<<v23-23-12,12>>^ And he says: “You will exult no more,
O oppressed one, the virgin daughter of Siʹdon.
Get up, cross over to Kitʹtim.
Even there you will find no rest.”

[[v23-23-13]]

^<<v23-23-13,13>>^ Look! The land of the Chal·deʹans.
This is the people—As·syrʹi·a was not the one—
They made her a place for those haunting the desert.
They have erected their siege towers;
They have stripped bare her fortified towers,
Reducing her to a crumbling ruin.

[[v23-23-14]]

^<<v23-23-14,14>>^ Wail, you ships of Tarʹshish,
For your stronghold has been destroyed.

[[v23-23-15]]

^<<v23-23-15,15>>^ In that day Tyre will be forgotten for 70 years, the same as the lifetime^&#42;1^ of one king. At the end of 70 years, it will happen to Tyre as in the song of a prostitute:

[NOTE]
====
. Lit., “days.”
====

[[v23-23-16]]

^<<v23-23-16,16>>^ “Take a harp, go around the city, O forgotten prostitute.
Play your harp skillfully;
Sing many songs,
So that they will remember you.”

[[v23-23-17]]

^<<v23-23-17,17>>^ At the end of 70 years, Jehovah will turn his attention to Tyre, and she will return to her hire and prostitute herself with all the world’s kingdoms on the face of the earth.

[[v23-23-18]]

^<<v23-23-18,18>>^ But her profit and her hire will become something holy to Jehovah. It will not be stored or laid away, because her hire will be for those dwelling before Jehovah, so that they may eat to satisfaction and wear elegant clothing.

'''

xref:023-isaiah/023-isaiah-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaiah/023-isaiah-024.adoc#v23-24-0[Próximo Capítulo &#62;]