include::./index.adoc[]

[[v23-8-0]]
=== Isaiah, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-8-1]]

^<<v23-8-1,1>>^ Jehovah said to me: “Take a large tablet and write on it with an ordinary stylus,^&#42;1^ ‘Maʹher-shalʹal-hash-baz.’^&#42;2^

[NOTE]
====
. Lit., “with the stylus of a mortal man.”
. Possibly meaning “Hurrying to the Spoil, Coming Quickly to the Plunder.”
====

[[v23-8-2]]

^<<v23-8-2,2>>^ And let me have it confirmed in writing^&#42;1^ by faithful witnesses, U·riʹah the priest and Zech·a·riʹah the son of Je·ber·e·chiʹah.”

[NOTE]
====
. Or “witnessed; attested.”
====

[[v23-8-3]]

^<<v23-8-3,3>>^ Then I had relations with^&#42;1^ the prophetess,^&#42;2^ and she became pregnant and in time gave birth to a son. Jehovah then said to me: “Name him Maʹher-shalʹal-hash-baz,

[NOTE]
====
. Lit., “went near to.”
. That is, the wife of Isaiah.
====

[[v23-8-4]]

^<<v23-8-4,4>>^ for before the boy knows how to call out, ‘My father!’ and ‘My mother!’ the resources of Damascus and the spoil of Sa·marʹi·a will be carried away before the king of As·syrʹi·a.”

[[v23-8-5]]

^<<v23-8-5,5>>^ Jehovah spoke to me again:

[[v23-8-6]]

^<<v23-8-6,6>>^ “Because this people has rejected the gently flowing waters of the Shi·loʹah^&#42;1^
And they rejoice over Reʹzin and the son of Rem·a·liʹah,

[NOTE]
====
. The Shiloah was a water conduit.
====

[[v23-8-7]]

^<<v23-8-7,7>>^ Therefore look! Jehovah will bring against them
The mighty and vast waters of the River,^&#42;1^
The king of As·syrʹi·a and all his glory.
He will come up over all his streambeds
And overflow all his banks

[NOTE]
====
. That is, the Euphrates.
====

[[v23-8-8]]

^<<v23-8-8,8>>^ And sweep through Judah.
He will flood and pass through, reaching to the neck;
His outspread wings will fill the breadth of your land,
O Im·manʹu·el!”^&#42;1^

[NOTE]
====
. See Isa 7:14.
====

[[v23-8-9]]

^<<v23-8-9,9>>^ Cause harm, you peoples, but you will be shattered to pieces.
Listen, all you from distant parts of the earth!
Prepare for battle,^&#42;1^ but you will be shattered to pieces!
Prepare for battle, but you will be shattered to pieces!

[NOTE]
====
. Or “Gird yourselves.”
====

[[v23-8-10]]

^<<v23-8-10,10>>^ Devise a plan, but it will be thwarted!
Say what you like, but it will not succeed,
For God is with us!^&#42;1^

[NOTE]
====
. The Hebrew for “God is with us” is Immanuel. See Isa 7:14; 8:8.
====

[[v23-8-11]]

^<<v23-8-11,11>>^ With his strong hand on me, this is what Jehovah said to me to warn me away from following the course of this people:

[[v23-8-12]]

^<<v23-8-12,12>>^ “You should not call a conspiracy what this people calls a conspiracy!
Do not fear what they fear;
Do not tremble at it.

[[v23-8-13]]

^<<v23-8-13,13>>^ Jehovah of armies—he is the One you should regard as holy,
He is the One you should fear,
And he is the One who should cause you to tremble.”

[[v23-8-14]]

^<<v23-8-14,14>>^ He will become as a sanctuary,
But as a stone to strike against
And as a rock to stumble over
To both houses of Israel,
As a trap and a snare
To the inhabitants of Jerusalem.

[[v23-8-15]]

^<<v23-8-15,15>>^ Many of them will stumble and fall and be broken;
They will be ensnared and caught.

[[v23-8-16]]

^<<v23-8-16,16>>^ Wrap up the written confirmation;^&#42;1^
Seal up the law^&#42;2^ among my disciples!

[NOTE]
====
. Or “the attestation.”
. Or “instruction.”
====

[[v23-8-17]]

^<<v23-8-17,17>>^ I will keep in expectation of^&#42;1^ Jehovah, who is hiding his face from the house of Jacob, and I will hope in him.

[NOTE]
====
. Or “eagerly wait for.”
====

[[v23-8-18]]

^<<v23-8-18,18>>^ Look! I and the children whom Jehovah has given me are as signs and as miracles in Israel from Jehovah of armies, who resides on Mount Zion.

[[v23-8-19]]

^<<v23-8-19,19>>^ And if they say to you: “Inquire of the spirit mediums or of the fortune-tellers who chirp and mutter,” is it not of their God that a people should inquire? Should they inquire of the dead in behalf of the living?

[[v23-8-20]]

^<<v23-8-20,20>>^ Instead, they should inquire of the law and of the written confirmation!^&#42;1^
When they do not speak according to this word, they have no light.^&#42;2^

[NOTE]
====
. Or “the attestation.”
. Lit., “dawn.”
====

[[v23-8-21]]

^<<v23-8-21,21>>^ And each one will pass through the land afflicted and hungry; and because he is hungry and indignant, he will curse his king and his God as he looks upward.

[[v23-8-22]]

^<<v23-8-22,22>>^ Then he will look to the earth and see only distress and darkness, obscurity and hard times, gloom and no brightness.

'''

xref:023-isaiah/023-isaiah-007.adoc#v23-7-0[&#60; Capítulo Anterior] | <<v23-8-0,Topo>> | xref:023-isaiah/023-isaiah-009.adoc#v23-9-0[Próximo Capítulo &#62;]