include::./index.adoc[]

[[v23-9-0]]
=== Isaiah, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-9-1]]

^<<v23-9-1,1>>^ However, the gloom will not be as when the land had distress, as in former times when the land of Zebʹu·lun and the land of Naphʹta·li were treated with contempt. But at a later time He will cause it to be honored—the way by the sea, in the region of the Jordan, Galʹi·lee of the nations.

[[v23-9-2]]

^<<v23-9-2,2>>^ The people who were walking in the darkness
Have seen a great light.
As for those dwelling in the land of deep shadow,
Light has shone on them.

[[v23-9-3]]

^<<v23-9-3,3>>^ You have made the nation populous;
You have made its rejoicing great.
They rejoice before you
As people rejoice in the harvesttime,
As those who joyfully divide up the spoil.

[[v23-9-4]]

^<<v23-9-4,4>>^ For you have shattered to pieces the yoke of their load,
The rod on their shoulders, the staff of the taskmaster,
As in the day of Midʹi·an.

[[v23-9-5]]

^<<v23-9-5,5>>^ Every boot that shakes the earth as it marches
And every garment soaked in blood
Will become fuel for the fire.

[[v23-9-6]]

^<<v23-9-6,6>>^ For a child has been born to us,
A son has been given to us;
And the rulership^&#42;1^ will rest on his shoulder.
His name will be called Wonderful Counselor, Mighty God, Eternal Father, Prince of Peace.

[NOTE]
====
. Or “government; princely rule.”
====

[[v23-9-7]]

^<<v23-9-7,7>>^ To the increase of his rulership^&#42;1^
And to peace, there will be no end,
On the throne of David and on his kingdom
In order to establish it firmly and to sustain it
Through justice and righteousness,
From now on and forever.
The zeal of Jehovah of armies will do this.

[NOTE]
====
. Or “government; princely rule.”
====

[[v23-9-8]]

^<<v23-9-8,8>>^ Jehovah sent a word against Jacob,
And it has come against Israel.

[[v23-9-9]]

^<<v23-9-9,9>>^ And all the people will know it
—Eʹphra·im and the inhabitants of Sa·marʹi·a—
Who say in their haughtiness and in their insolence of heart:

[[v23-9-10]]

^<<v23-9-10,10>>^ “Bricks have fallen,
But we will build with hewn stone.
Sycamore trees have been cut down,
But we will replace them with cedars.”

[[v23-9-11]]

^<<v23-9-11,11>>^ Jehovah will raise up Reʹzin’s adversaries against him
And will stir his enemies to action,

[[v23-9-12]]

^<<v23-9-12,12>>^ Syria from the east and the Phi·lisʹtines from the west,^&#42;1^
They will devour Israel with open mouths.
In view of all this, his anger has not turned back,
But his hand is still stretched out to strike.

[NOTE]
====
. Lit., “from behind.”
====

[[v23-9-13]]

^<<v23-9-13,13>>^ For the people have not returned to the One who strikes them;
They have not sought Jehovah of armies.

[[v23-9-14]]

^<<v23-9-14,14>>^ Jehovah will cut off from Israel
Head and tail, shoot and rush,^&#42;1^ in one day.

[NOTE]
====
. Or possibly, “palm branch and reed.”
====

[[v23-9-15]]

^<<v23-9-15,15>>^ The elder and highly respected one is the head,
And the prophet giving false instruction is the tail.

[[v23-9-16]]

^<<v23-9-16,16>>^ Those leading this people are causing them to wander,
And those who are being led are confused.

[[v23-9-17]]

^<<v23-9-17,17>>^ That is why Jehovah will not rejoice over their young men,
And he will have no mercy on their fatherless children^&#42;1^ and their widows
Because all of them are apostates and evildoers
And every mouth is speaking senselessness.
In view of all this, his anger has not turned back,
But his hand is still stretched out to strike.

[NOTE]
====
. Or “their orphans.”
====

[[v23-9-18]]

^<<v23-9-18,18>>^ For wickedness burns like a fire,
Consuming thornbushes and weeds.
It will set fire to the thickets of the forest,
And they will go up in clouds of smoke.

[[v23-9-19]]

^<<v23-9-19,19>>^ In the fury of Jehovah of armies
The land has been set on fire,
And the people will become fuel for the fire.
No one will spare even his brother.

[[v23-9-20]]

^<<v23-9-20,20>>^ One will cut down on the right
But still be hungry;
And one will eat on the left
But will not be satisfied.
Each will devour the flesh of his own arm,

[[v23-9-21]]

^<<v23-9-21,21>>^ Ma·nasʹseh will devour Eʹphra·im,
And Eʹphra·im Ma·nasʹseh.
Together they will be against Judah.
In view of all this, his anger has not turned back,
But his hand is still stretched out to strike.

'''

xref:023-isaiah/023-isaiah-008.adoc#v23-8-0[&#60; Capítulo Anterior] | <<v23-9-0,Topo>> | xref:023-isaiah/023-isaiah-010.adoc#v23-10-0[Próximo Capítulo &#62;]