include::./index.adoc[]

[[v23-33-0]]
=== Isaiah, 33
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-33-1]]

^<<v23-33-1,1>>^ Woe to you, you destroyer who has not been destroyed;
You betrayer who has not been betrayed!
When you finish destroying, you will be destroyed.
When you finish betraying, you will be betrayed.

[[v23-33-2]]

^<<v23-33-2,2>>^ O Jehovah, show us favor.
Our hope is in you.
Become our arm^&#42;1^ every morning,
Yes, our salvation in the time of distress.

[NOTE]
====
. Or “strength.”
====

[[v23-33-3]]

^<<v23-33-3,3>>^ At the sound of turmoil peoples flee.
When you rise up, nations scatter.

[[v23-33-4]]

^<<v23-33-4,4>>^ As the voracious locusts gather, so your spoil will be gathered;
People will rush on it like swarms of locusts.

[[v23-33-5]]

^<<v23-33-5,5>>^ Jehovah will be exalted,
For he resides in the heights above.
He will fill Zion with justice and righteousness.

[[v23-33-6]]

^<<v23-33-6,6>>^ He is the stability of your times;
An abundance of salvation, wisdom, knowledge, and the fear of Jehovah
—This is his treasure.

[[v23-33-7]]

^<<v23-33-7,7>>^ Look! Their heroes cry out in the street;
The messengers of peace weep bitterly.

[[v23-33-8]]

^<<v23-33-8,8>>^ The highways are deserted;
There is no one traveling on the pathways.
He^&#42;1^ has broken the covenant;
He has rejected the cities;
He shows no regard for mortal man.

[NOTE]
====
. Referring to the enemy.
====

[[v23-33-9]]

^<<v23-33-9,9>>^ The land mourns^&#42;1^ and withers away.
Lebʹa·non is ashamed; it has decayed.
Sharʹon has become like the desert,
And Baʹshan and Carʹmel shake off their leaves.

[NOTE]
====
. Or possibly, “dries up.”
====

[[v23-33-10]]

^<<v23-33-10,10>>^ “Now I will rise up,” says Jehovah,
“Now I will exalt myself;
Now I will magnify myself.

[[v23-33-11]]

^<<v23-33-11,11>>^ You conceive dried grass and give birth to stubble.
Your own spirit will consume you like a fire.

[[v23-33-12]]

^<<v23-33-12,12>>^ And peoples will become as the burnings of lime.
As thorns cut down, they will be set ablaze with fire.

[[v23-33-13]]

^<<v23-33-13,13>>^ You who are far away, listen to what I will do!
And you who are nearby, acknowledge my might!

[[v23-33-14]]

^<<v23-33-14,14>>^ The sinners in Zion are in dread;
Trembling has seized the apostates:
‘Who of us can live where there is a consuming fire?
Who of us can live with unquenchable flames?’

[[v23-33-15]]

^<<v23-33-15,15>>^ The one who walks in continual righteousness,
Who speaks what is upright,
Who rejects dishonest, fraudulent gain,
Whose hands refuse a bribe rather than grabbing it,
Who closes his ear to talk of bloodshed,
And who shuts his eyes to avoid seeing what is bad

[[v23-33-16]]

^<<v23-33-16,16>>^ —He will reside in the heights;
His secure refuge^&#42;1^ will be in rocky strongholds,
His bread will be provided,
And his water supply will never fail.”

[NOTE]
====
. Or “secure height.”
====

[[v23-33-17]]

^<<v23-33-17,17>>^ Your eyes will behold a king in his splendor;
They will see a land far away.

[[v23-33-18]]

^<<v23-33-18,18>>^ In your heart you will recall^&#42;1^ the terror:
“Where is the secretary?
Where is the one who weighed out the tribute?
Where is the one who counted the towers?”

[NOTE]
====
. Or “meditate on.”
====

[[v23-33-19]]

^<<v23-33-19,19>>^ You will no more see the insolent people,
A people whose language is too obscure^&#42;1^ to comprehend,
Whose stammering tongue you cannot understand.

[NOTE]
====
. Lit., “deep.”
====

[[v23-33-20]]

^<<v23-33-20,20>>^ Behold Zion, the city of our festivals!
Your eyes will see Jerusalem as a tranquil dwelling place,
A tent that will not be moved.
Never will its tent pins be pulled out,
And none of its ropes will be torn apart.

[[v23-33-21]]

^<<v23-33-21,21>>^ But there the Majestic One, Jehovah,
Will be for us a region of rivers, of wide canals,
Where no galley fleet will go
And no majestic ships will pass by.

[[v23-33-22]]

^<<v23-33-22,22>>^ For Jehovah is our Judge,
Jehovah is our Lawgiver,
Jehovah is our King;
He is the One who will save us.

[[v23-33-23]]

^<<v23-33-23,23>>^ Your ropes will hang loose;
They cannot hold up the mast nor spread the sail.
At that time an abundance of spoil will be divided up;
Even the lame will take much plunder.

[[v23-33-24]]

^<<v23-33-24,24>>^ And no resident^&#42;1^ will say: “I am sick.”
The people dwelling in the land will be pardoned for their error.

[NOTE]
====
. Or “inhabitant.”
====

'''

xref:023-isaiah/023-isaiah-032.adoc#v23-32-0[&#60; Capítulo Anterior] | <<v23-33-0,Topo>> | xref:023-isaiah/023-isaiah-034.adoc#v23-34-0[Próximo Capítulo &#62;]