include::./index.adoc[]

[[v23-63-0]]
=== Isaiah, 63
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-63-1]]

^<<v23-63-1,1>>^ Who is this coming from Eʹdom,
From Bozʹrah with bright-colored^&#42;1^ garments,
This one with splendid clothing,
Marching in his great power?
“It is I, the One speaking in righteousness,
The One with great power to save.”

[NOTE]
====
. Or possibly, “bright-red.”
====

[[v23-63-2]]

^<<v23-63-2,2>>^ Why is your clothing red,
And why are your garments like those of one treading the winepress?

[[v23-63-3]]

^<<v23-63-3,3>>^ “I have trodden the wine trough alone.
No one from the peoples was with me.
I kept treading them in my anger,
And I kept trampling them in my wrath.
My garments were spattered with their blood,
And I have stained all my clothing.

[[v23-63-4]]

^<<v23-63-4,4>>^ For the day of vengeance is in my heart,
And the year of my repurchased ones has come.

[[v23-63-5]]

^<<v23-63-5,5>>^ I looked, but there was no one to help;
I was appalled that no one offered support.
So my arm brought me salvation,^&#42;1^
And my own wrath supported me.

[NOTE]
====
. Or “victory.”
====

[[v23-63-6]]

^<<v23-63-6,6>>^ I trampled peoples in my anger,
I made them drunk with my wrath
And poured out their blood on the ground.”

[[v23-63-7]]

^<<v23-63-7,7>>^ I will mention Jehovah’s acts of loyal love,
The praiseworthy acts of Jehovah,
Because of all that Jehovah has done for us,
The many good things he has done for the house of Israel,
According to his mercy and his great loyal love.

[[v23-63-8]]

^<<v23-63-8,8>>^ For he said: “Surely they are my people, sons who will not be disloyal.”^&#42;1^
So he became their Savior.

[NOTE]
====
. Or “prove false.”
====

[[v23-63-9]]

^<<v23-63-9,9>>^ During all their distress it was distressing to him.
And his own personal messenger^&#42;1^ saved them.
In his love and compassion he repurchased them,
And he lifted them up and carried them all the days of old.

[NOTE]
====
. Or “the angel of his presence.”
====

[[v23-63-10]]

^<<v23-63-10,10>>^ But they rebelled and grieved his holy spirit.
He then turned into their enemy,
And he fought against them.

[[v23-63-11]]

^<<v23-63-11,11>>^ And they remembered the days of old,
The days of Moses his servant:
“Where is the One who brought them up out of the sea with the shepherds of his flock?
Where is the One who put within him His holy spirit,

[[v23-63-12]]

^<<v23-63-12,12>>^ The One who made His glorious arm go with the right hand of Moses,
The One who split the waters before them
To make an everlasting name for himself,

[[v23-63-13]]

^<<v23-63-13,13>>^ The One who made them walk through the surging waters,^&#42;1^
So that they walked without stumbling,
Like a horse in the open country?^&#42;2^

[NOTE]
====
. Or “deep waters.”
. Or “the wilderness?”
====

[[v23-63-14]]

^<<v23-63-14,14>>^ Just like livestock when they go down into the valley plain,
The spirit of Jehovah made them rest.”
This is how you led your people,
To make a majestic^&#42;1^ name for yourself.

[NOTE]
====
. Or “beautiful.”
====

[[v23-63-15]]

^<<v23-63-15,15>>^ Look down from heaven and see
From your lofty abode of holiness and glory.^&#42;1^
Where are your zeal and your mightiness,
The stirring of your compassions^&#42;2^ and your mercy?
They are withheld from me.

[NOTE]
====
. Or “beauty.”
. Lit., “The agitation of your inward parts.”
====

[[v23-63-16]]

^<<v23-63-16,16>>^ For you are our Father;
Although Abraham may not know us
And Israel may not recognize us,
You, O Jehovah, are our Father.
Our Repurchaser of long ago is your name.

[[v23-63-17]]

^<<v23-63-17,17>>^ Why do you, O Jehovah, let us^&#42;1^ wander from your ways?
Why do you let^&#42;2^ our hearts become hard, so that we do not fear you?
Return, for the sake of your servants,
The tribes of your inheritance.

[NOTE]
====
. Or “cause us to.”
. Lit., “make.”
====

[[v23-63-18]]

^<<v23-63-18,18>>^ Your holy people possessed it for a short time.
Our adversaries have trampled on your sanctuary.

[[v23-63-19]]

^<<v23-63-19,19>>^ For too long we have become like those you never ruled over,
Like those never called by your name.

'''

xref:023-isaiah/023-isaiah-062.adoc#v23-62-0[&#60; Capítulo Anterior] | <<v23-63-0,Topo>> | xref:023-isaiah/023-isaiah-064.adoc#v23-64-0[Próximo Capítulo &#62;]