include::./index.adoc[]

[[v23-29-0]]
=== Isaiah, 29
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-29-1]]

^<<v23-29-1,1>>^ “Woe to Arʹi·el,^&#42;1^ Arʹi·el, the city where David encamped!
Continue year after year;
Let the cycle of festivals continue.

[NOTE]
====
. Possibly meaning “The Altar Hearth of God,” apparently referring to Jerusalem.
====

[[v23-29-2]]

^<<v23-29-2,2>>^ But I will bring distress on Arʹi·el,
And there will be mourning and lamentation,
And she will become to me like an altar hearth of God.

[[v23-29-3]]

^<<v23-29-3,3>>^ I will encamp on all sides against you,
And I will besiege you with a palisade
And raise up siegeworks against you.

[[v23-29-4]]

^<<v23-29-4,4>>^ You will be brought low;
From the ground you will speak,
And what you say will be muffled by dust.
Your voice will come from the ground
Like the voice of a spirit medium,
And your words will chirp from the dust.

[[v23-29-5]]

^<<v23-29-5,5>>^ The crowd of your enemies^&#42;1^ will be like fine powder,
The crowd of the tyrants just like the blowing chaff.
And it will happen in an instant, suddenly.

[NOTE]
====
. Lit., “strangers.”
====

[[v23-29-6]]

^<<v23-29-6,6>>^ Jehovah of armies will give you his attention
With thunder and earthquake and a great noise,
With storm wind and tempest and the flames of a consuming fire.”

[[v23-29-7]]

^<<v23-29-7,7>>^ Then the crowd of all the nations waging war against Arʹi·el
—All those waging war against her,
The siege towers against her,
And those bringing distress on her—
Will become like a dream, a vision of the night.

[[v23-29-8]]

^<<v23-29-8,8>>^ Yes, it will be just as when someone hungry dreams that he is eating,
But he wakes up hungry,^&#42;1^
And as when someone thirsty dreams that he is drinking,
But he wakes up tired and thirsty.^&#42;2^
So it will happen with the crowd of all the nations
That wage war against Mount Zion.

[NOTE]
====
. Or “and his soul is empty.”
. Or “and his soul is parched.”
====

[[v23-29-9]]

^<<v23-29-9,9>>^ Be stunned and amazed;
Blind yourselves and be blinded.
They are drunk, but not with wine;
They are staggering, but not from alcohol.

[[v23-29-10]]

^<<v23-29-10,10>>^ For Jehovah has poured a spirit of deep sleep on you;
He has closed your eyes, the prophets,
And he has covered your heads, the visionaries.

[[v23-29-11]]

^<<v23-29-11,11>>^ Every vision becomes for you like the words of a sealed book. When they give it to someone who can read, saying: “Read this out loud, please,” he will say: “I cannot, for it is sealed up.”

[[v23-29-12]]

^<<v23-29-12,12>>^ And when they give the book to someone who cannot read, saying: “Read this, please,” he will say: “I cannot read at all.”

[[v23-29-13]]

^<<v23-29-13,13>>^ Jehovah says: “This people approach me with their mouth
And they honor me with their lips,
But their heart is far removed from me;
And their fear of me is based on commands of men that they have been taught.

[[v23-29-14]]

^<<v23-29-14,14>>^ Therefore, I am the One who will again do wonderful things with this people,
With wonder upon wonder;
And the wisdom of their wise men will perish,
And the understanding of their discreet men will be hidden.”

[[v23-29-15]]

^<<v23-29-15,15>>^ Woe to those who go to great lengths to conceal their plans^&#42;1^ from Jehovah.
Their deeds are done in a dark place,
While they say: “Who sees us?
Who knows about us?”

[NOTE]
====
. Or “counsel.”
====

[[v23-29-16]]

^<<v23-29-16,16>>^ How you twist things!^&#42;1^
Should the potter be regarded the same as the clay?
Should what is made say about its maker:
“He did not make me”?
And does what is formed say about its former:
“He shows no understanding”?

[NOTE]
====
. Or “How perverse of you!”
====

[[v23-29-17]]

^<<v23-29-17,17>>^ In just a short time, Lebʹa·non will be turned into an orchard,
And the orchard will be regarded as a forest.

[[v23-29-18]]

^<<v23-29-18,18>>^ In that day the deaf will hear the words of the book,
And out of the gloom and darkness the eyes of the blind will see.

[[v23-29-19]]

^<<v23-29-19,19>>^ The meek will rejoice greatly in Jehovah,
And the poor among men will be joyful in the Holy One of Israel.

[[v23-29-20]]

^<<v23-29-20,20>>^ For the tyrant will be no more,
The boaster will come to his finish,
And all those keeping alert to do harm will be destroyed,

[[v23-29-21]]

^<<v23-29-21,21>>^ Those who with a false word make others guilty,
Who lay traps for the defender^&#42;1^ in the city gate,
And who with empty arguments deny justice to the righteous one.

[NOTE]
====
. Lit., “the one reproving.”
====

[[v23-29-22]]

^<<v23-29-22,22>>^ So this is what Jehovah, who redeemed Abraham, says to the house of Jacob:
“Jacob will no longer be ashamed,
And no more will his face grow pale.^&#42;1^

[NOTE]
====
. That is, from shame and disappointment.
====

[[v23-29-23]]

^<<v23-29-23,23>>^ For when he sees his children,
Who are the work of my hands, in his midst,
They will sanctify my name;
Yes, they will sanctify the Holy One of Jacob,
And they will stand in awe of the God of Israel.

[[v23-29-24]]

^<<v23-29-24,24>>^ Those who are wayward in spirit will acquire understanding,
And those who complain will accept instruction.”

'''

xref:023-isaiah/023-isaiah-028.adoc#v23-28-0[&#60; Capítulo Anterior] | <<v23-29-0,Topo>> | xref:023-isaiah/023-isaiah-030.adoc#v23-30-0[Próximo Capítulo &#62;]