include::./index.adoc[]

[[v23-14-0]]
=== Isaiah, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-14-1]]

^<<v23-14-1,1>>^ For Jehovah will show mercy to Jacob, and he will again choose Israel. He will settle them^&#42;1^ in their land, and the foreign residents will join them and attach themselves to the house of Jacob.

[NOTE]
====
. Or “give them rest.”
====

[[v23-14-2]]

^<<v23-14-2,2>>^ And peoples will take them and bring them to their own place, and the house of Israel will possess them as male and female servants in Jehovah’s land; and they will be the captors of those who held them captive, and they will have in subjection those who were forcing them to work.^&#42;1^

[NOTE]
====
. Or “their taskmasters.”
====

[[v23-14-3]]

^<<v23-14-3,3>>^ In the day when Jehovah gives you rest from your pain and from your turmoil and from the hard slavery imposed on you,

[[v23-14-4]]

^<<v23-14-4,4>>^ you will recite this proverb^&#42;1^ against the king of Babylon:
“How the one forcing others to work^&#42;2^ has met his end!
How the oppression has ended!

[NOTE]
====
. Or “taunt.”
. Or “the taskmaster.”
====

[[v23-14-5]]

^<<v23-14-5,5>>^ Jehovah has broken the rod of the wicked,
The staff of the rulers,

[[v23-14-6]]

^<<v23-14-6,6>>^ The one furiously striking peoples with unceasing blows,
The one angrily subduing nations with relentless persecution.

[[v23-14-7]]

^<<v23-14-7,7>>^ The whole earth now rests, free of disturbance.
People cry out for joy.

[[v23-14-8]]

^<<v23-14-8,8>>^ Even the juniper trees rejoice over you,
Along with the cedars of Lebʹa·non.
They say, ‘Ever since you have fallen,
No woodcutter comes up against us.’

[[v23-14-9]]

^<<v23-14-9,9>>^ Even the Grave^&#42;1^ underneath is stirred up
To meet you when you come.
Because of you, it awakens those powerless in death,
All the oppressive leaders^&#42;2^ of the earth.
It makes all the kings of the nations rise from their thrones.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
. Lit., “the he-goats.”
====

[[v23-14-10]]

^<<v23-14-10,10>>^ All of them speak up and say to you,
‘Have you also become weak like us?
Have you become like us?

[[v23-14-11]]

^<<v23-14-11,11>>^ Down to the Grave^&#42;1^ your pride has been brought,
The sound of your stringed instruments.
Maggots are spread beneath you as a bed,
And worms are your covering.’

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v23-14-12]]

^<<v23-14-12,12>>^ How you have fallen from heaven,
O shining one, son of the dawn!
How you have been cut down to the earth,
You who vanquished nations!

[[v23-14-13]]

^<<v23-14-13,13>>^ You said in your heart, ‘I will ascend to the heavens.
Above the stars of God I will lift up my throne,
And I will sit down on the mountain of meeting,
In the remotest parts of the north.

[[v23-14-14]]

^<<v23-14-14,14>>^ I will go up above the tops of the clouds;
I will make myself resemble the Most High.’

[[v23-14-15]]

^<<v23-14-15,15>>^ Instead, you will be brought down to the Grave,^&#42;1^
To the remotest parts of the pit.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v23-14-16]]

^<<v23-14-16,16>>^ Those seeing you will stare at you;
They will closely examine you, saying,
‘Is this the man who was shaking the earth,
Who made kingdoms tremble,

[[v23-14-17]]

^<<v23-14-17,17>>^ Who made the inhabited earth like the wilderness
And overthrew its cities,
Who refused to let his prisoners go home?’

[[v23-14-18]]

^<<v23-14-18,18>>^ All other kings of the nations,
Yes, all of them, lie down in glory,
Each one in his own tomb.^&#42;1^

[NOTE]
====
. Lit., “house.”
====

[[v23-14-19]]

^<<v23-14-19,19>>^ But you are discarded without a grave,
Like a detested sprout,^&#42;1^
Clothed with the slain who were stabbed with the sword,
Who go down to the stones of a pit,
Like a carcass trampled underfoot.

[NOTE]
====
. Or “branch.”
====

[[v23-14-20]]

^<<v23-14-20,20>>^ You will not join them in a grave,
For you destroyed your own land,
You killed your own people.
The offspring of evildoers will never again be named.

[[v23-14-21]]

^<<v23-14-21,21>>^ Prepare a slaughtering block for his sons
Because of the guilt of their forefathers,
So that they will not rise up and take over the earth
And fill the land with their cities.”

[[v23-14-22]]

^<<v23-14-22,22>>^ “I will rise up against them,” declares Jehovah of armies.
“And I will wipe out from Babylon name and remnant and descendants and posterity,” declares Jehovah.

[[v23-14-23]]

^<<v23-14-23,23>>^ “And I will make her a possession of porcupines and a region of marshes, and I will sweep her with the broom of annihilation,” declares Jehovah of armies.

[[v23-14-24]]

^<<v23-14-24,24>>^ Jehovah of armies has sworn:
“Just as I have intended, so it will occur,
And just as I have decided, that is what will come true.

[[v23-14-25]]

^<<v23-14-25,25>>^ I will crush the As·syrʹi·an in my land,
And I will trample him on my mountains.
His yoke will be removed from them,
And his load will be removed from their shoulder.”

[[v23-14-26]]

^<<v23-14-26,26>>^ This is what has been decided^&#42;1^ against all the earth,
And this is the hand that is stretched out^&#42;2^ against all the nations.

[NOTE]
====
. Lit., “the counsel that is counseled.”
. Or “is ready to strike.”
====

[[v23-14-27]]

^<<v23-14-27,27>>^ For Jehovah of armies has decided,
And who can thwart it?
His hand is stretched out,
And who can turn it back?

[[v23-14-28]]

^<<v23-14-28,28>>^ In the year that King Aʹhaz died, this pronouncement was made:

[[v23-14-29]]

^<<v23-14-29,29>>^ “Do not rejoice, Phi·lisʹti·a, any of you,
Just because the staff of the one striking you has been broken.
For from the root of the serpent will come a poisonous snake,
And its offspring will be a flying fiery snake.^&#42;1^

[NOTE]
====
. Or “a darting poisonous snake.”
====

[[v23-14-30]]

^<<v23-14-30,30>>^ While the firstborn of the lowly feed
And the poor lie down in security,
I will put your root to death with famine,
And what is left of you will be killed.

[[v23-14-31]]

^<<v23-14-31,31>>^ Wail, O gate! Cry out, O city!
All of you will lose heart, O Phi·lisʹti·a!
For a smoke is coming from the north,
And there are no stragglers in his ranks.”

[[v23-14-32]]

^<<v23-14-32,32>>^ How should they answer the messengers of the nation?
That Jehovah has laid the foundation of Zion,
And that the lowly ones of his people will take refuge in her.

'''

xref:023-isaiah/023-isaiah-013.adoc#v23-13-0[&#60; Capítulo Anterior] | <<v23-14-0,Topo>> | xref:023-isaiah/023-isaiah-015.adoc#v23-15-0[Próximo Capítulo &#62;]