include::./index.adoc[]

[[v23-52-0]]
=== Isaiah, 52
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-52-1]]

^<<v23-52-1,1>>^ Awake! Awake! Clothe yourself with strength, O Zion!
Put on your beautiful garments, O Jerusalem, the holy city!
For no more will the uncircumcised and unclean one enter into you.

[[v23-52-2]]

^<<v23-52-2,2>>^ Shake off the dust, rise and take a seat, O Jerusalem.
Loosen the bonds on your neck, O captive daughter of Zion.

[[v23-52-3]]

^<<v23-52-3,3>>^ For this is what Jehovah says:
“You were sold for nothing,
And without money you will be repurchased.”

[[v23-52-4]]

^<<v23-52-4,4>>^ For this is what the Sovereign Lord Jehovah says:
“At first my people went down to Egypt to live there as foreigners;
Then As·syrʹi·a oppressed them without cause.”

[[v23-52-5]]

^<<v23-52-5,5>>^ “What, then, should I do here?” declares Jehovah.
“For my people were taken for nothing.
Those ruling over them keep howling in triumph,” declares Jehovah,
“And constantly, all day long, my name is treated with disrespect.

[[v23-52-6]]

^<<v23-52-6,6>>^ For that reason my people will know my name;
For that reason they will know in that day that I am the One speaking.
Look, it is I!”

[[v23-52-7]]

^<<v23-52-7,7>>^ How beautiful on the mountains are the feet of the one bringing good news,
The one proclaiming peace,
The one bringing good news of something better,
The one proclaiming salvation,
The one saying to Zion: “Your God has become King!”

[[v23-52-8]]

^<<v23-52-8,8>>^ Listen! Your watchmen raise their voice.
In unison they shout joyfully,
For they will see it clearly^&#42;1^ when Jehovah gathers back Zion.

[NOTE]
====
. Or “eye to eye.”
====

[[v23-52-9]]

^<<v23-52-9,9>>^ Become cheerful, shout joyfully in unison, you ruins of Jerusalem,
For Jehovah has comforted his people; he has repurchased Jerusalem.

[[v23-52-10]]

^<<v23-52-10,10>>^ Jehovah has bared his holy arm before the eyes of all the nations;
All the ends of the earth will see the acts of salvation^&#42;1^ of our God.

[NOTE]
====
. Or “the victory.”
====

[[v23-52-11]]

^<<v23-52-11,11>>^ Turn away, turn away, get out of there, touch nothing unclean!
Get out from the midst of her, keep yourselves clean,
You who are carrying the utensils of Jehovah.

[[v23-52-12]]

^<<v23-52-12,12>>^ For you will not depart in panic,
Nor will you have to flee,
For Jehovah will go ahead of you,
And the God of Israel will be your rear guard.

[[v23-52-13]]

^<<v23-52-13,13>>^ Look! My servant will act with insight.
He will be raised up high,
He will be elevated and greatly exalted.

[[v23-52-14]]

^<<v23-52-14,14>>^ Just as there were many who stared at him in amazement
—For his appearance was disfigured more than that of any other man
And his stately form more than that of mankind—

[[v23-52-15]]

^<<v23-52-15,15>>^ So he will startle many nations.
Kings will shut their mouths^&#42;1^ before him,
Because they will see what they had not been told
And give consideration to what they had not heard.

[NOTE]
====
. Or “will be speechless.”
====

'''

xref:023-isaiah/023-isaiah-051.adoc#v23-51-0[&#60; Capítulo Anterior] | <<v23-52-0,Topo>> | xref:023-isaiah/023-isaiah-053.adoc#v23-53-0[Próximo Capítulo &#62;]