include::./index.adoc[]

[[v23-26-0]]
=== Isaiah, 26
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-26-1]]

^<<v23-26-1,1>>^ In that day this song will be sung in the land of Judah:
“We have a strong city.
He makes salvation its walls and its ramparts.

[[v23-26-2]]

^<<v23-26-2,2>>^ Open up the gates so that the righteous nation may enter,
A nation that is keeping faithful conduct.

[[v23-26-3]]

^<<v23-26-3,3>>^ You will safeguard those who fully lean on you;^&#42;1^
You will give them continuous peace,
Because it is in you that they trust.

[NOTE]
====
. Or possibly, “those whose inclination is unshakable.”
====

[[v23-26-4]]

^<<v23-26-4,4>>^ Trust in Jehovah forever,
For Jah^&#42;1^ Jehovah is the eternal Rock.

[NOTE]
====
. “Jah” is a shortened form of the name Jehovah.
====

[[v23-26-5]]

^<<v23-26-5,5>>^ For he has brought low those inhabiting the height, the lofty city.
He brings it down,
He brings it down to the earth;
He casts it down to the dust.

[[v23-26-6]]

^<<v23-26-6,6>>^ The foot will trample it,
The feet of the afflicted, the steps of the lowly.”

[[v23-26-7]]

^<<v23-26-7,7>>^ The path of the righteous one is upright.^&#42;1^
Because you are upright,
You will smooth out the course of the righteous.

[NOTE]
====
. Or “level.”
====

[[v23-26-8]]

^<<v23-26-8,8>>^ As we follow the path of your judgments, O Jehovah,
Our hope is in you.
We^&#42;1^ long for your name and your memorial.^&#42;2^

[NOTE]
====
. Or “With our soul we.”
. That is, that God and his name be remembered, made known.
====

[[v23-26-9]]

^<<v23-26-9,9>>^ In the night I long for you with my whole being,^&#42;1^
Yes, my spirit keeps looking for you;
For when there are judgments from you for the earth,
The inhabitants of the land learn about righteousness.

[NOTE]
====
. Or “with my soul.”
====

[[v23-26-10]]

^<<v23-26-10,10>>^ Even if the wicked is shown favor,
He will not learn righteousness.
Even in the land of uprightness^&#42;1^ he will act wickedly,
And he will not see the majesty of Jehovah.

[NOTE]
====
. Or “straightforwardness.”
====

[[v23-26-11]]

^<<v23-26-11,11>>^ O Jehovah, your hand is raised, but they do not see it.
They will see your zeal for your people and be put to shame.
Yes, the fire for your adversaries will consume them.

[[v23-26-12]]

^<<v23-26-12,12>>^ O Jehovah, you will grant us peace,
Because everything we have done
You have accomplished for us.

[[v23-26-13]]

^<<v23-26-13,13>>^ O Jehovah our God, other masters besides you have ruled over us,
But we make mention of your name alone.

[[v23-26-14]]

^<<v23-26-14,14>>^ They are dead; they will not live.
Powerless in death, they will not rise up.
For you have turned your attention to them
To annihilate them and destroy all mention of them.

[[v23-26-15]]

^<<v23-26-15,15>>^ You have enlarged the nation, O Jehovah,
You have enlarged the nation;
You have glorified yourself.
You have greatly extended all the borders of the land.

[[v23-26-16]]

^<<v23-26-16,16>>^ O Jehovah, during distress they turned to you;
They poured out their prayer in a whisper when you disciplined them.

[[v23-26-17]]

^<<v23-26-17,17>>^ Just as a pregnant woman about to give birth
Has labor pains and cries out in pain,
So we have been because of you, O Jehovah.

[[v23-26-18]]

^<<v23-26-18,18>>^ We became pregnant, we had labor pains,
But it is as if we had given birth to wind.
We have not brought salvation to the land,
And no one is born to inhabit the land.

[[v23-26-19]]

^<<v23-26-19,19>>^ “Your dead will live.
My corpses^&#42;1^ will rise up.
Awake and shout joyfully,
You residents in the dust!
For your dew is as the dew of the morning,^&#42;2^
And the earth will let those powerless in death come to life.^&#42;3^

[NOTE]
====
. Lit., “A corpse of mine.”
. Or possibly, “the dew of herbs (mallows).”
. Or “will give birth to those powerless in death.”
====

[[v23-26-20]]

^<<v23-26-20,20>>^ Go, my people, enter your inner rooms,
And shut your doors behind you.
Hide yourself for a brief moment
Until the wrath^&#42;1^ has passed by.

[NOTE]
====
. Or “denunciation.”
====

[[v23-26-21]]

^<<v23-26-21,21>>^ For look! Jehovah is coming from his place
To call the inhabitants of the land to account for their error,
And the land will expose her bloodshed
And will no longer cover over her slain.”

'''

xref:023-isaiah/023-isaiah-025.adoc#v23-25-0[&#60; Capítulo Anterior] | <<v23-26-0,Topo>> | xref:023-isaiah/023-isaiah-027.adoc#v23-27-0[Próximo Capítulo &#62;]