include::./index.adoc[]

[[v23-47-0]]
=== Isaiah, 47
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-47-1]]

^<<v23-47-1,1>>^ Come down and sit in the dust,
O virgin daughter of Babylon.
Sit down on the ground where there is no throne,
O daughter of the Chal·deʹans,
For never again will people call you delicate and pampered.

[[v23-47-2]]

^<<v23-47-2,2>>^ Take a hand mill and grind flour.
Remove your veil.
Strip off your skirt, uncover your legs.
Cross over the rivers.

[[v23-47-3]]

^<<v23-47-3,3>>^ Your nakedness will be uncovered.
Your shame will be exposed.
I will take vengeance, and no man will stand in my way.^&#42;1^

[NOTE]
====
. Or possibly, “and I will not meet anyone kindly.”
====

[[v23-47-4]]

^<<v23-47-4,4>>^ “The One repurchasing us
—Jehovah of armies is his name—
Is the Holy One of Israel.”

[[v23-47-5]]

^<<v23-47-5,5>>^ Sit there silently and go into darkness,
O daughter of the Chal·deʹans;
No more will they call you Mistress^&#42;1^ of Kingdoms.

[NOTE]
====
. Or “Queen.”
====

[[v23-47-6]]

^<<v23-47-6,6>>^ I grew indignant at my people.
I profaned my inheritance,
And I gave them into your hand.
But you showed them no mercy.
Even on the elderly you placed a heavy yoke.

[[v23-47-7]]

^<<v23-47-7,7>>^ You said: “I will always be the Mistress,^&#42;1^ forever.”
You did not take these things to heart;
You did not consider how the matter would end.

[NOTE]
====
. Or “Queen.”
====

[[v23-47-8]]

^<<v23-47-8,8>>^ Now hear this, O lover of pleasure,
Who sits in security, who says in her heart:
“I am the one, and there is no one else.
I will not become a widow.
I will never know the loss of children.”

[[v23-47-9]]

^<<v23-47-9,9>>^ But these two things will come upon you suddenly, in one day:
Loss of children and widowhood.
In full measure they will come upon you
Because of^&#42;1^ your many sorceries and all your powerful spells.

[NOTE]
====
. Or possibly, “Despite.”
====

[[v23-47-10]]

^<<v23-47-10,10>>^ You trusted in your wickedness.
You said: “No one sees me.”
Your wisdom and knowledge are what led you astray,
And you say in your heart: “I am the one, and there is no one else.”

[[v23-47-11]]

^<<v23-47-11,11>>^ But calamity will come upon you,
And none of your charms will stop it.^&#42;1^
Adversity will befall you; you will not be able to avert it.
Sudden ruin will come upon you like you have never known.

[NOTE]
====
. Or “And you will not know how to charm it away.”
====

[[v23-47-12]]

^<<v23-47-12,12>>^ Go ahead, then, with your spells and your many sorceries,
With which you have toiled from your youth.
Perhaps you may be able to benefit;
Perhaps you may strike people with awe.

[[v23-47-13]]

^<<v23-47-13,13>>^ You have grown weary with the multitude of your advisers.
Let them stand up now and save you,
Those who worship the heavens,^&#42;1^ who gaze at the stars,
Those giving out knowledge at the new moons
About the things that will come upon you.

[NOTE]
====
. Or possibly, “Those who divide the heavens; The astrologers.”
====

[[v23-47-14]]

^<<v23-47-14,14>>^ Look! They are like stubble.
A fire will burn them up.
They cannot save themselves^&#42;1^ from the power of the flame.
These are not charcoals for keeping warm,
And this is not a fire to sit in front of.

[NOTE]
====
. Or “their soul.”
====

[[v23-47-15]]

^<<v23-47-15,15>>^ So your charmers will become to you,
Those with whom you toiled from your youth.
They will wander, each one in his own direction.^&#42;1^
There will be no one to save you.

[NOTE]
====
. Lit., “to his own region.”
====

'''

xref:023-isaiah/023-isaiah-046.adoc#v23-46-0[&#60; Capítulo Anterior] | <<v23-47-0,Topo>> | xref:023-isaiah/023-isaiah-048.adoc#v23-48-0[Próximo Capítulo &#62;]