include::./index.adoc[]

[[v23-45-0]]
=== Isaiah, 45
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-45-1]]

^<<v23-45-1,1>>^ This is what Jehovah says to his anointed one, to Cyrus,
Whose right hand I have taken hold of
To subdue nations before him,
To disarm^&#42;1^ kings,
To open before him the double doors,
So that the gates will not be shut:

[NOTE]
====
. Lit., “ungird the hips of.”
====

[[v23-45-2]]

^<<v23-45-2,2>>^ “Before you I will go,
And the hills I will level.
The copper doors I will break in pieces,
And the iron bars I will cut down.

[[v23-45-3]]

^<<v23-45-3,3>>^ I will give you the treasures in the darkness
And the hidden treasures in the concealed places,
So that you may know that I am Jehovah,
The God of Israel, who is calling you by your name.

[[v23-45-4]]

^<<v23-45-4,4>>^ For the sake of my servant Jacob and of Israel my chosen one,
I am calling you by your name.
I am giving you a name of honor, although you did not know me.

[[v23-45-5]]

^<<v23-45-5,5>>^ I am Jehovah, and there is no one else.
There is no God except me.
I will strengthen^&#42;1^ you, although you did not know me,

[NOTE]
====
. Lit., “closely gird.”
====

[[v23-45-6]]

^<<v23-45-6,6>>^ In order that people may know
From the rising of the sun to its setting^&#42;1^
That there is none besides me.
I am Jehovah, and there is no one else.

[NOTE]
====
. Or “From east to west.”
====

[[v23-45-7]]

^<<v23-45-7,7>>^ I form light and create darkness,
I make peace and create calamity;
I, Jehovah, am doing all these things.

[[v23-45-8]]

^<<v23-45-8,8>>^ You heavens, rain down from above;
Let the clouds pour down righteousness.
Let the earth open up and be fruitful with salvation,
And let it cause righteousness to spring up at the same time.
I, Jehovah, have created it.”

[[v23-45-9]]

^<<v23-45-9,9>>^ Woe to the one who contends^&#42;1^ with his Maker,^&#42;2^
For he is just an earthenware fragment
Among the other earthenware fragments lying on the ground!
Should the clay say to the Potter:^&#42;3^ “What are you making?”
Or should your work say: “He has no hands”?^&#42;4^

[NOTE]
====
. Or “argues.”
. Or “with the One who formed him.”
. Or “the One who formed it.”
. Or possibly, “Or should the clay say: ‘Your work has no handles’?”
====

[[v23-45-10]]

^<<v23-45-10,10>>^ Woe to the one who says to a father: “What do you become father to?”
And to a woman: “What are you giving birth to?”^&#42;1^

[NOTE]
====
. Or “What are you in birth pains with?”
====

[[v23-45-11]]

^<<v23-45-11,11>>^ This is what Jehovah says, the Holy One of Israel, the One who formed him:
“Would you question me about the things coming
And command me about my sons and the works of my hands?

[[v23-45-12]]

^<<v23-45-12,12>>^ I made the earth and created man on it.
I stretched out the heavens with my own hands,
And I give orders to all their army.”

[[v23-45-13]]

^<<v23-45-13,13>>^ “I have raised up a man in righteousness,
And I will make all his ways straight.
He is the one who will build my city
And set my exiles free without a price or a bribe,” says Jehovah of armies.

[[v23-45-14]]

^<<v23-45-14,14>>^ This is what Jehovah says:
“The profit^&#42;1^ of Egypt and the merchandise^&#42;2^ of E·thi·oʹpi·a and the Sa·beʹans, tall of stature,
Will come over to you and become yours.
They will walk behind you in chains.
They will come over and bow down to you.
To you they will say in prayer, ‘Surely God is with you,
And there is no one else; there is no other God.’”

[NOTE]
====
. Or possibly, “laborers.”
. Or possibly, “merchants.”
====

[[v23-45-15]]

^<<v23-45-15,15>>^ Truly you are a God who conceals himself,
O God of Israel, the Savior.

[[v23-45-16]]

^<<v23-45-16,16>>^ They will all be put to shame and be humiliated;
The makers of idols will all go off in disgrace.

[[v23-45-17]]

^<<v23-45-17,17>>^ But Israel will be saved by Jehovah with an everlasting salvation.
You will not be put to shame or disgraced for all eternity.

[[v23-45-18]]

^<<v23-45-18,18>>^ For this is what Jehovah says,
The Creator of the heavens, the true God,
The One who formed the earth, its Maker who firmly established it,
Who did not create it simply for nothing,^&#42;1^ but formed it to be inhabited:
“I am Jehovah, and there is no one else.

[NOTE]
====
. Or possibly, “to be empty.”
====

[[v23-45-19]]

^<<v23-45-19,19>>^ I did not speak in a concealed place, in a land of darkness;
I did not say to the offspring^&#42;1^ of Jacob,
‘Seek me simply for nothing.’^&#42;2^
I am Jehovah, who speaks what is righteous and declares what is upright.

[NOTE]
====
. Lit., “seed.”
. Or “in vain.”
====

[[v23-45-20]]

^<<v23-45-20,20>>^ Gather together and come.
Approach together, you escapees from the nations.
They know nothing, those who carry around carved images
And pray to a god that cannot save them.

[[v23-45-21]]

^<<v23-45-21,21>>^ Make your report, present your case.
Let them consult together in unity.
Who foretold this long ago
And declared it from times past?
Is it not I, Jehovah?
There is no other God but me;
A righteous God and a Savior, there is none besides me.

[[v23-45-22]]

^<<v23-45-22,22>>^ Turn to me and be saved, all the ends of the earth,
For I am God, and there is no one else.

[[v23-45-23]]

^<<v23-45-23,23>>^ By myself I have sworn;
The word has gone out of my mouth in righteousness,
And it will not return:
To me every knee will bend,
Every tongue will swear loyalty

[[v23-45-24]]

^<<v23-45-24,24>>^ And say, ‘Surely in Jehovah are true righteousness and strength.
All those enraged against him will come before him in shame.

[[v23-45-25]]

^<<v23-45-25,25>>^ In Jehovah all the offspring^&#42;1^ of Israel will prove to be right,
And in him they will make their boast.’”

[NOTE]
====
. Lit., “seed.”
====

'''

xref:023-isaiah/023-isaiah-044.adoc#v23-44-0[&#60; Capítulo Anterior] | <<v23-45-0,Topo>> | xref:023-isaiah/023-isaiah-046.adoc#v23-46-0[Próximo Capítulo &#62;]