include::./index.adoc[]

[[v23-24-0]]
=== Isaiah, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-24-1]]

^<<v23-24-1,1>>^ Look! Jehovah is emptying the land^&#42;1^ and making it desolate.
He turns it upside down^&#42;2^ and scatters its inhabitants.

[NOTE]
====
. Or “earth.”
. Or “He twists the face of it.”
====

[[v23-24-2]]

^<<v23-24-2,2>>^ It will be the same for everyone:
The people as well as the priest,
The servant and his master,
The servant and her mistress,
The buyer and the seller,
The lender and the borrower,
The creditor and the debtor.

[[v23-24-3]]

^<<v23-24-3,3>>^ The land will be completely emptied;
It will be completely plundered,
For Jehovah has spoken this word.

[[v23-24-4]]

^<<v23-24-4,4>>^ The land mourns;^&#42;1^ it is wasting away.
The productive land withers; it is fading away.
The prominent people of the land wither.

[NOTE]
====
. Or possibly, “dries up.”
====

[[v23-24-5]]

^<<v23-24-5,5>>^ The land has been polluted by its inhabitants,
For they have bypassed the laws,
Changed the regulation,
And broken the lasting^&#42;1^ covenant.

[NOTE]
====
. Or “ancient.”
====

[[v23-24-6]]

^<<v23-24-6,6>>^ That is why the curse devours the land,
And those inhabiting it are held guilty.
That is why the inhabitants of the land have dwindled,
And very few men are left.

[[v23-24-7]]

^<<v23-24-7,7>>^ The new wine mourns,^&#42;1^ the vine withers,
And all those cheerful at heart are sighing.

[NOTE]
====
. Or possibly, “dries up.”
====

[[v23-24-8]]

^<<v23-24-8,8>>^ The joy of the tambourines has ceased;
The noise of the revelers has ended;
The happy sound of the harp has ceased.

[[v23-24-9]]

^<<v23-24-9,9>>^ They drink wine without song,
And alcohol tastes bitter to those drinking it.

[[v23-24-10]]

^<<v23-24-10,10>>^ The deserted town is broken down;
Every house is shut up so that no one can enter.

[[v23-24-11]]

^<<v23-24-11,11>>^ They cry out for wine in the streets.
All rejoicing has disappeared;
The joy of the land has gone.

[[v23-24-12]]

^<<v23-24-12,12>>^ The city is left in ruins;
The gate has been crushed to a heap of rubble.

[[v23-24-13]]

^<<v23-24-13,13>>^ For this is how it will be in the land, among the peoples:
As when an olive tree is beaten,
Like the gleaning when the grape harvest comes to an end.

[[v23-24-14]]

^<<v23-24-14,14>>^ They will raise their voice,
They will shout joyfully.
From the sea^&#42;1^ they will proclaim the majesty of Jehovah.

[NOTE]
====
. Or “the west.”
====

[[v23-24-15]]

^<<v23-24-15,15>>^ That is why they will glorify Jehovah in the region of light;^&#42;1^
In the islands of the sea they will glorify the name of Jehovah the God of Israel.

[NOTE]
====
. Or “in the east.”
====

[[v23-24-16]]

^<<v23-24-16,16>>^ From the ends of the earth we hear songs:
“Glory^&#42;1^ to the Righteous One!”
But I say: “I am wasting away, I am wasting away!
Woe to me! The treacherous have acted treacherously;
With treachery the treacherous have acted treacherously.”

[NOTE]
====
. Or “Decoration.”
====

[[v23-24-17]]

^<<v23-24-17,17>>^ Terror and pits and traps await you, inhabitant of the land.

[[v23-24-18]]

^<<v23-24-18,18>>^ Anyone fleeing from the sound of terror will fall into the pit,
And anyone coming up from the pit will be caught in the trap.
For the floodgates above will be opened,
And the foundations of the land will quake.

[[v23-24-19]]

^<<v23-24-19,19>>^ The land has burst apart;
The land has been shaken up;
The land convulses violently.

[[v23-24-20]]

^<<v23-24-20,20>>^ The land staggers like a drunken man,
And it sways back and forth like a hut in the wind.
Its transgression weighs heavily on it,
And it will fall, so that it will not rise up again.

[[v23-24-21]]

^<<v23-24-21,21>>^ In that day Jehovah will turn his attention to the army of the heights above
And to the kings of the earth upon the earth.

[[v23-24-22]]

^<<v23-24-22,22>>^ And they will be gathered together
Like prisoners gathered into a pit,
And they will be shut up in the dungeon;
After many days they will be given attention.

[[v23-24-23]]

^<<v23-24-23,23>>^ The full moon will be abashed,
And the shining sun will be ashamed,
For Jehovah of armies has become King in Mount Zion and in Jerusalem,
Glorious before the elders of his people.^&#42;1^

[NOTE]
====
. Lit., “before his elders.”
====

'''

xref:023-isaiah/023-isaiah-023.adoc#v23-23-0[&#60; Capítulo Anterior] | <<v23-24-0,Topo>> | xref:023-isaiah/023-isaiah-025.adoc#v23-25-0[Próximo Capítulo &#62;]