include::./index.adoc[]

[[v23-22-0]]
=== Isaiah, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-22-1]]

^<<v23-22-1,1>>^ A pronouncement about the Valley of Vision:^&#42;1^
What is the matter with you that you have all gone up to the roofs?

[NOTE]
====
. Evidently referring to Jerusalem.
====

[[v23-22-2]]

^<<v23-22-2,2>>^ You were full of turmoil,
A boisterous city, an exultant town.
Your slain were not slain with the sword,
Nor did they die in battle.

[[v23-22-3]]

^<<v23-22-3,3>>^ All your dictators have fled together.
They were taken prisoner without need of a bow.
All who were found were taken prisoner,
Even though they had fled far away.

[[v23-22-4]]

^<<v23-22-4,4>>^ That is why I said: “Turn your eyes away from me,
And I will weep bitterly.
Do not insist on comforting me
Over the destruction of the daughter of^&#42;1^ my people.

[NOTE]
====
. A poetic personification, perhaps expressing pity or sympathy.
====

[[v23-22-5]]

^<<v23-22-5,5>>^ For it is a day of confusion and of defeat and of panic,
From the Sovereign Lord, Jehovah of armies,
In the Valley of Vision.
There is a demolishing of the wall
And a cry to the mountain.

[[v23-22-6]]

^<<v23-22-6,6>>^ Eʹlam picks up the quiver
With manned chariots and horses,^&#42;1^
And Kir uncovers^&#42;2^ the shield.

[NOTE]
====
. Or “horsemen.”
. Or “prepares.”
====

[[v23-22-7]]

^<<v23-22-7,7>>^ Your choicest valleys^&#42;1^
Will become full of war chariots,
And the horses^&#42;2^ will take their positions at the gate,

[NOTE]
====
. Or “low plains.”
. Or “horsemen.”
====

[[v23-22-8]]

^<<v23-22-8,8>>^ And the screen^&#42;1^ of Judah will be removed.
“In that day you will look toward the armory of the House of the Forest,

[NOTE]
====
. Or “protection.”
====

[[v23-22-9]]

^<<v23-22-9,9>>^ and you will see the many breaches of the City of David. And you will collect the waters of the lower pool.

[[v23-22-10]]

^<<v23-22-10,10>>^ You will count the houses of Jerusalem, and you will pull down the houses to reinforce the wall.

[[v23-22-11]]

^<<v23-22-11,11>>^ And you will make a basin between the two walls for the water of the old pool, but you will not look to its Grand Maker, and you will not see the One who formed it long ago.

[[v23-22-12]]

^<<v23-22-12,12>>^ In that day the Sovereign Lord, Jehovah of armies,
Will call for weeping and mourning,
For shaved heads and the wearing of sackcloth.

[[v23-22-13]]

^<<v23-22-13,13>>^ But instead, there is celebration and rejoicing,
The killing of cattle and the slaughtering of sheep,
The eating of meat and the drinking of wine.
‘Let us eat and drink, for tomorrow we will die.’”

[[v23-22-14]]

^<<v23-22-14,14>>^ Then Jehovah of armies revealed himself in my ears: “‘This error will not be atoned in your behalf until you people die,’ says the Sovereign Lord, Jehovah of armies.”

[[v23-22-15]]

^<<v23-22-15,15>>^ This is what the Sovereign Lord, Jehovah of armies, says: “Go in to this steward, to Shebʹna, who is in charge of the house,^&#42;1^ and say,

[NOTE]
====
. Or “palace.”
====

[[v23-22-16]]

^<<v23-22-16,16>>^ ‘What is your interest here, and who is there of interest to you here, that you hewed out a burial place here for yourself?’ He is hewing out his burial place in a high place; he is cutting out a resting-place^&#42;1^ for himself in a crag.

[NOTE]
====
. Lit., “a residence.”
====

[[v23-22-17]]

^<<v23-22-17,17>>^ ‘Look! Jehovah will hurl you down violently, O man, and seize you forcibly.

[[v23-22-18]]

^<<v23-22-18,18>>^ He will certainly wrap you up tightly and hurl you like a ball into a wide land. There you will die, and there your glorious chariots will be, a disgrace to your master’s house.

[[v23-22-19]]

^<<v23-22-19,19>>^ And I will depose you from your position and throw you out of your office.

[[v23-22-20]]

^<<v23-22-20,20>>^ “‘In that day I will call my servant E·liʹa·kim the son of Hil·kiʹah,

[[v23-22-21]]

^<<v23-22-21,21>>^ and I will clothe him with your robe and firmly bind your sash around him, and I will give your authority^&#42;1^ into his hand. And he will be a father to the inhabitants of Jerusalem and to the house of Judah.

[NOTE]
====
. Or “dominion.”
====

[[v23-22-22]]

^<<v23-22-22,22>>^ And I will put the key of the house of David on his shoulder. He will open and no one will shut; and he will shut and no one will open.

[[v23-22-23]]

^<<v23-22-23,23>>^ I will drive him in as a peg in a lasting place, and he will become as a throne of glory to the house of his father.

[[v23-22-24]]

^<<v23-22-24,24>>^ And they will hang on him all the glory^&#42;1^ of the house of his father, the descendants and the offspring,^&#42;2^ all the small vessels, the bowl-shaped vessels, as well as all the large jars.

[NOTE]
====
. Lit., “weight.”
. Or “offshoots.”
====

[[v23-22-25]]

^<<v23-22-25,25>>^ “‘In that day,’ declares Jehovah of armies, ‘the peg that is driven in a lasting place will be removed, and it will be cut down and fall, and the load that it supported will fall to ruin, for Jehovah himself has spoken.’”

'''

xref:023-isaiah/023-isaiah-021.adoc#v23-21-0[&#60; Capítulo Anterior] | <<v23-22-0,Topo>> | xref:023-isaiah/023-isaiah-023.adoc#v23-23-0[Próximo Capítulo &#62;]