include::./index.adoc[]

[[v23-66-0]]
=== Isaiah, 66
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-66-1]]

^<<v23-66-1,1>>^ This is what Jehovah says:
“The heavens are my throne, and the earth is my footstool.
Where, then, is the house that you could build for me,
And where is my resting-place?”

[[v23-66-2]]

^<<v23-66-2,2>>^ “My own hand has made all these things,
And this is how they all came to be,” declares Jehovah.
“To this one, then, I will look,
To the one humble and broken in spirit who trembles at^&#42;1^ my word.

[NOTE]
====
. Or “is anxious about.”
====

[[v23-66-3]]

^<<v23-66-3,3>>^ The one slaughtering the bull is like one striking down a man.
The one sacrificing a sheep is like one breaking the neck of a dog.
The one offering a gift—like the blood of a pig!
The one presenting a memorial offering of frankincense is like one saying a blessing with magical words.^&#42;1^
They have chosen their own ways,
And they take delight^&#42;2^ in what is disgusting.

[NOTE]
====
. Or possibly, “one praising an idol.”
. Or “their soul takes delight.”
====

[[v23-66-4]]

^<<v23-66-4,4>>^ So I will choose ways to punish them,
And the very things they dread I will bring upon them.
Because when I called, no one answered;
When I spoke, there were none who listened.
They kept doing what was bad in my eyes,
And they chose to do what displeased me.”

[[v23-66-5]]

^<<v23-66-5,5>>^ Hear the word of Jehovah, you who tremble at^&#42;1^ his word:
“Your brothers who hate you and exclude you because of my name said, ‘May Jehovah be glorified!’
But He will appear and bring you joy,
And they are the ones who will be put to shame.”

[NOTE]
====
. Or “are anxious about.”
====

[[v23-66-6]]

^<<v23-66-6,6>>^ There is a sound of uproar from the city, a sound from the temple!
It is the sound of Jehovah repaying his enemies what they deserve.

[[v23-66-7]]

^<<v23-66-7,7>>^ Before she went into labor, she gave birth.
Before birth pangs came to her, she delivered a male child.

[[v23-66-8]]

^<<v23-66-8,8>>^ Who has ever heard of such a thing?
Who has seen such things?
Will a land be brought to birth in one day?
Or will a nation be born all at once?
Yet, as soon as Zion went into labor, she gave birth to her sons.

[[v23-66-9]]

^<<v23-66-9,9>>^ “Will I bring it to the point of birth and then not bring it forth?” says Jehovah.
“Or would I cause the birth and then shut the womb?” says your God.

[[v23-66-10]]

^<<v23-66-10,10>>^ Rejoice with Jerusalem and be joyful with her, all you who love her.
Exult greatly with her, all you who are in mourning over her,

[[v23-66-11]]

^<<v23-66-11,11>>^ For you will nurse and be fully satisfied from her breast of consolation,
And you will drink deeply and find delight in the abundance of her glory.

[[v23-66-12]]

^<<v23-66-12,12>>^ For this is what Jehovah says:
“Here I am extending to her peace just like a river
And the glory of nations like a flooding torrent.
You will nurse and be carried on the hip,
And you will be bounced on the knees.

[[v23-66-13]]

^<<v23-66-13,13>>^ As a mother comforts her son,
So I will keep comforting you;
And over Jerusalem you will be comforted.

[[v23-66-14]]

^<<v23-66-14,14>>^ You will see this, and your heart will rejoice,
Your bones will flourish just like new grass.
And the hand^&#42;1^ of Jehovah will become known to his servants,
But he will denounce his enemies.”

[NOTE]
====
. Or “power.”
====

[[v23-66-15]]

^<<v23-66-15,15>>^ “For Jehovah will come as a fire,
And his chariots are like a storm wind,
To repay in furious anger,
To rebuke with flames of fire.

[[v23-66-16]]

^<<v23-66-16,16>>^ For with fire Jehovah will execute judgment,
Yes, with his sword, against all flesh;^&#42;1^
And the slain of Jehovah will be many.

[NOTE]
====
. Or “all humans.”
====

[[v23-66-17]]

^<<v23-66-17,17>>^ “Those sanctifying themselves and cleansing themselves to enter the gardens^&#42;1^ following one who is in the center, those eating the flesh of pigs and loathsome things and mice, they will all come to their end together,” declares Jehovah.

[NOTE]
====
. That is, special gardens used in idol worship.
====

[[v23-66-18]]

^<<v23-66-18,18>>^ “Since I know about their works and their thoughts, I am coming to gather people of all nations and languages, and they will come and see my glory.”

[[v23-66-19]]

^<<v23-66-19,19>>^ “I will set a sign among them, and I will send some of those who escape to the nations—to Tarʹshish, Pul, and Lud, those who draw the bow, to Tuʹbal and Jaʹvan, and to the faraway islands—who have not heard a report about me or seen my glory; and they will proclaim my glory among the nations.

[[v23-66-20]]

^<<v23-66-20,20>>^ They will bring all your brothers out of all the nations as a gift to Jehovah, on horses, in chariots, in covered wagons, on mules, and on swift camels, up to my holy mountain, Jerusalem,” says Jehovah, “just as when the people of Israel bring their gift in a clean vessel into the house of Jehovah.”

[[v23-66-21]]

^<<v23-66-21,21>>^ “I will also take some for the priests and for the Levites,” says Jehovah.

[[v23-66-22]]

^<<v23-66-22,22>>^ “For just as the new heavens and the new earth that I am making will remain standing before me,” declares Jehovah, “so your offspring^&#42;1^ and your name will remain.”

[NOTE]
====
. Lit., “seed.”
====

[[v23-66-23]]

^<<v23-66-23,23>>^ “And from new moon to new moon and from sabbath to sabbath,
All flesh^&#42;1^ will come in to bow down before^&#42;2^ me,” says Jehovah.

[NOTE]
====
. Or “all humans.”
. Or “to worship.”
====

[[v23-66-24]]

^<<v23-66-24,24>>^ “And they will go out and look on the carcasses of the men who rebelled against me;
For the worms on them will not die,
And their fire will not be extinguished,
And they will become something repulsive to all people.”^&#42;1^

[NOTE]
====
. Lit., “all flesh.”
====

'''

xref:023-isaiah/023-isaiah-065.adoc#v23-65-0[&#60; Capítulo Anterior] | <<v23-66-0,Topo>> | xref:024-jeremiah/024-jeremiah-001.adoc#v24-1-0[Próximo Capítulo &#62;]