include::./index.adoc[]

[[v23-50-0]]
=== Isaiah, 50
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-50-1]]

^<<v23-50-1,1>>^ This is what Jehovah says:
“Where is the divorce certificate of your mother, whom I sent away?
Or to which of my creditors did I sell you?
Look! It was because of your own errors you were sold,
And because of your own transgressions your mother was sent away.

[[v23-50-2]]

^<<v23-50-2,2>>^ Why, then, was no one here when I came?
Why did no one answer when I called?
Is my hand too short to redeem,
Or is there no power in me to rescue?
Look! With my rebuke I dry up the sea;
I make rivers a desert.
Their fish rot for lack of water,
And they die because of thirst.

[[v23-50-3]]

^<<v23-50-3,3>>^ I clothe the heavens with gloom,
And I make sackcloth their covering.”

[[v23-50-4]]

^<<v23-50-4,4>>^ The Sovereign Lord Jehovah has given me the tongue of those taught,^&#42;1^
So that I may know how to answer^&#42;2^ the tired one with the right word.^&#42;3^
He awakens me morning by morning;
He awakens my ear to listen like the taught ones.

[NOTE]
====
. Or “a well-trained tongue.”
. Or possibly, “strengthen.”
. Lit., “with a word.”
====

[[v23-50-5]]

^<<v23-50-5,5>>^ The Sovereign Lord Jehovah has opened my ear,
And I was not rebellious.
I did not turn in the opposite direction.

[[v23-50-6]]

^<<v23-50-6,6>>^ I offered my back to those striking me
And my cheeks to those who plucked them bare.^&#42;1^
I did not hide my face from humiliating things and from spit.

[NOTE]
====
. Or “who plucked the beard.”
====

[[v23-50-7]]

^<<v23-50-7,7>>^ But the Sovereign Lord Jehovah will help me.
That is why I will not feel humiliated.
That is why I have set my face like a flint,
And I know that I will not be put to shame.

[[v23-50-8]]

^<<v23-50-8,8>>^ The One who declares me righteous is near.
Who can accuse^&#42;1^ me?
Let us stand up together.^&#42;2^
Who has a case against me?
Let him approach me.

[NOTE]
====
. Or “contend with.”
. Or “face each other.”
====

[[v23-50-9]]

^<<v23-50-9,9>>^ Look! The Sovereign Lord Jehovah will help me.
Who will pronounce me guilty?
Look! They will all wear out like a garment.
A moth will eat them up.

[[v23-50-10]]

^<<v23-50-10,10>>^ Who among you fears Jehovah
And listens to the voice of his servant?
Who has walked in deep darkness, without any brightness?
Let him trust in the name of Jehovah and support himself on^&#42;1^ his God.

[NOTE]
====
. Or “rely on.”
====

[[v23-50-11]]

^<<v23-50-11,11>>^ “Look! All of you who are igniting a fire,
Making sparks fly,
Walk in the light of your fire,
Among the sparks you have set ablaze.
This is what you will have from my hand:
In sheer pain you will lie down.

'''

xref:023-isaiah/023-isaiah-049.adoc#v23-49-0[&#60; Capítulo Anterior] | <<v23-50-0,Topo>> | xref:023-isaiah/023-isaiah-051.adoc#v23-51-0[Próximo Capítulo &#62;]