include::./index.adoc[]

[[v23-55-0]]
=== Isaiah, 55
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-55-1]]

^<<v23-55-1,1>>^ Come, all you thirsty ones, come to the water!
You with no money, come, buy and eat!
Yes, come, buy wine and milk without money and without cost.

[[v23-55-2]]

^<<v23-55-2,2>>^ Why do you keep paying out money for what is not bread,
And why spend your earnings^&#42;1^ for what brings no satisfaction?
Listen intently to me, and eat what is good,
And you^&#42;2^ will find great delight in what is truly rich.^&#42;3^

[NOTE]
====
. Or “hard-earned money.”
. Or “your soul.”
. Lit., “in fatness.”
====

[[v23-55-3]]

^<<v23-55-3,3>>^ Incline your ear and come to me.
Listen, and you^&#42;1^ will keep alive,
And I will readily make with you an everlasting covenant
In harmony with the expressions of loyal love to David, which are faithful.^&#42;2^

[NOTE]
====
. Or “your soul.”
. Or “trustworthy; reliable.”
====

[[v23-55-4]]

^<<v23-55-4,4>>^ Look! I made him a witness to the nations,
A leader and commander to the nations.

[[v23-55-5]]

^<<v23-55-5,5>>^ Look! You will call a nation that you do not know,
And those of a nation who have not known you will run to you
For the sake of Jehovah your God, the Holy One of Israel,
Because he will glorify you.

[[v23-55-6]]

^<<v23-55-6,6>>^ Search for Jehovah while he may be found.
Call to him while he is near.

[[v23-55-7]]

^<<v23-55-7,7>>^ Let the wicked man leave his way
And the evil man his thoughts;
Let him return to Jehovah, who will have mercy on him,
To our God, for he will forgive in a large way.^&#42;1^

[NOTE]
====
. Or “will freely forgive.”
====

[[v23-55-8]]

^<<v23-55-8,8>>^ “For my thoughts are not your thoughts,
And your ways are not my ways,” declares Jehovah.

[[v23-55-9]]

^<<v23-55-9,9>>^ “For as the heavens are higher than the earth,
So my ways are higher than your ways
And my thoughts than your thoughts.

[[v23-55-10]]

^<<v23-55-10,10>>^ For just as the rain and the snow pour down from heaven
And do not return there until they saturate the earth, making it produce and sprout,
Giving seed to the sower and bread to the eater,

[[v23-55-11]]

^<<v23-55-11,11>>^ So my word that goes out of my mouth will be.^&#42;1^
It will not return to me without results,
But it will certainly accomplish whatever is my delight,^&#42;2^
And it will have sure success in what I send it to do.

[NOTE]
====
. Or “will prove to be.”
. Or “my will.”
====

[[v23-55-12]]

^<<v23-55-12,12>>^ For you will go out with rejoicing,
And in peace you will be brought back.
The mountains and the hills will become cheerful before you with a joyful cry,
And the trees of the field will all clap their hands.

[[v23-55-13]]

^<<v23-55-13,13>>^ Instead of thornbushes the juniper tree will grow,
And instead of the stinging nettle the myrtle tree will grow.
And it will bring fame to^&#42;1^ Jehovah,
An everlasting sign that will never perish.”

[NOTE]
====
. Or “will make a name for.”
====

'''

xref:023-isaiah/023-isaiah-054.adoc#v23-54-0[&#60; Capítulo Anterior] | <<v23-55-0,Topo>> | xref:023-isaiah/023-isaiah-056.adoc#v23-56-0[Próximo Capítulo &#62;]