include::./index.adoc[]

[[v23-18-0]]
=== Isaiah, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-18-1]]

^<<v23-18-1,1>>^ Woe to the land of whirring insect wings
In the region of the rivers of E·thi·oʹpi·a!

[[v23-18-2]]

^<<v23-18-2,2>>^ It sends envoys by sea,
Across the waters in papyrus vessels, saying:
“Go, you swift messengers,
To a tall and smooth-skinned nation,^&#42;1^
To a people feared everywhere,
To a strong, conquering nation,^&#42;2^
Whose land is washed away by rivers.”

[NOTE]
====
. Lit., “a nation drawn out and scoured.”
. Or “a nation of tensile strength that treads down.”
====

[[v23-18-3]]

^<<v23-18-3,3>>^ All you inhabitants of the land and you residents of the earth,
What you see will be like a signal^&#42;1^ raised on the mountains,
And you will hear a sound like the blowing of a horn.

[NOTE]
====
. Or “signal pole.”
====

[[v23-18-4]]

^<<v23-18-4,4>>^ For this is what Jehovah said to me:
“I will remain undisturbed and look on^&#42;1^ my established place,
Like the shimmering heat along with the sunlight,
Like the cloud of dew in the heat of harvest.

[NOTE]
====
. Or possibly, “from.”
====

[[v23-18-5]]

^<<v23-18-5,5>>^ For before the harvest,
When the blossom is finished and the bloom becomes a ripening grape,
The shoots will be cut off with pruning shears
And the tendrils will be lopped off and removed.

[[v23-18-6]]

^<<v23-18-6,6>>^ They will all be left for the birds of prey of the mountains
And for the beasts of the earth.
The birds of prey will spend the summer on them,
And all the beasts of the earth will spend the harvesttime on them.

[[v23-18-7]]

^<<v23-18-7,7>>^ At that time a gift will be brought to Jehovah of armies,
From a tall and smooth-skinned nation,^&#42;1^
From a people feared everywhere,
From a strong, conquering nation,^&#42;2^
Whose land is washed away by rivers
To the place that bears the name of Jehovah of armies, Mount Zion.”

[NOTE]
====
. Lit., “a nation drawn out and scoured.”
. Or “a nation of tensile strength that treads down.”
====

'''

xref:023-isaiah/023-isaiah-017.adoc#v23-17-0[&#60; Capítulo Anterior] | <<v23-18-0,Topo>> | xref:023-isaiah/023-isaiah-019.adoc#v23-19-0[Próximo Capítulo &#62;]