include::./index.adoc[]

[[v23-44-0]]
=== Isaiah, 44
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-44-1]]

^<<v23-44-1,1>>^ “Now listen, O Jacob my servant,
And you, O Israel, whom I have chosen.

[[v23-44-2]]

^<<v23-44-2,2>>^ This is what Jehovah says,
Your Maker and the One who formed you,
Who has helped you from the womb:^&#42;1^
‘Do not be afraid, my servant Jacob,
And you, Jeshʹu·run,^&#42;2^ whom I have chosen.

[NOTE]
====
. Or “from birth.”
. Meaning “Upright One,” an honorary title for Israel.
====

[[v23-44-3]]

^<<v23-44-3,3>>^ For I will pour out water on the thirsty one^&#42;1^
And flowing streams on the dry ground.
I will pour out my spirit on your offspring^&#42;2^
And my blessing on your descendants.

[NOTE]
====
. Or “thirsty land.”
. Lit., “seed.”
====

[[v23-44-4]]

^<<v23-44-4,4>>^ And they will spring up as among the green grass,
Like poplars by the streams of water.

[[v23-44-5]]

^<<v23-44-5,5>>^ One will say: “I belong to Jehovah.”
Another will call himself by the name of Jacob,
And yet another will write on his hand: “Belonging to Jehovah.”
And he will adopt the name of Israel.’

[[v23-44-6]]

^<<v23-44-6,6>>^ This is what Jehovah says,
The King of Israel and his Repurchaser, Jehovah of armies:
‘I am the first and I am the last.
There is no God but me.

[[v23-44-7]]

^<<v23-44-7,7>>^ Who is there like me?
Let him call out and tell it and prove it to me!
From the time I established the people of long ago,
Let them tell both the things to come
And what will yet happen.

[[v23-44-8]]

^<<v23-44-8,8>>^ Do not be in dread,
And do not become paralyzed with fear.
Have I not told each of you beforehand and declared it?
You are my witnesses.
Is there any God but me?
No, there is no other Rock; I know of none.’”

[[v23-44-9]]

^<<v23-44-9,9>>^ All who form carved images amount to nothing,
And their cherished objects will be of no benefit.
As their witnesses, they^&#42;1^ see nothing and know nothing,
So those who made them will be put to shame.

[NOTE]
====
. That is, the images.
====

[[v23-44-10]]

^<<v23-44-10,10>>^ Who would form a god or cast a metal image^&#42;1^
That can bring no benefit?

[NOTE]
====
. Or “molten statue.”
====

[[v23-44-11]]

^<<v23-44-11,11>>^ Look! All his associates will be put to shame!
The craftsmen are mere humans.
Let them all assemble and take their stand.
They will be terrified and be put to shame together.

[[v23-44-12]]

^<<v23-44-12,12>>^ The metalsmith works the iron over the coals with his tool.^&#42;1^
He forms it with hammers,
Working it with his powerful arm.
Then he grows hungry and his strength fails;
He drinks no water and grows tired.

[NOTE]
====
. Or “billhook.”
====

[[v23-44-13]]

^<<v23-44-13,13>>^ The wood-carver stretches the measuring line, tracing out the pattern with red chalk.
He works it with a wood scraper and traces it with a compass.
He patterns it after a man,
With the beauty of a man,
To sit in a house.^&#42;1^

[NOTE]
====
. Or “shrine.”
====

[[v23-44-14]]

^<<v23-44-14,14>>^ There is one whose work is to cut down cedars.
He selects a certain type of tree, an oak,
And he lets it grow strong among the trees of the forest.
He plants a laurel tree, and the rain makes it grow.

[[v23-44-15]]

^<<v23-44-15,15>>^ Then it becomes fuel for a man to make fires.
He takes part of it to warm himself;
He builds a fire and bakes bread.
But he also makes a god and worships it.
He makes it into a carved image, and he bows down before it.

[[v23-44-16]]

^<<v23-44-16,16>>^ Half of it he burns up in a fire;
With that half he roasts the meat that he eats, and he is satisfied.
He also warms himself and says:
“Ah! I am warm as I watch the fire.”

[[v23-44-17]]

^<<v23-44-17,17>>^ But the rest of it he makes into a god, into his carved image.
He bows down to it and worships it.
He prays to it and says:
“Save me, for you are my god.”

[[v23-44-18]]

^<<v23-44-18,18>>^ They know nothing, they understand nothing,
Because their eyes are sealed shut and they cannot see,
And their heart has no insight.

[[v23-44-19]]

^<<v23-44-19,19>>^ No one reflects in his heart
Or has knowledge or understanding, saying:
“Half of it I burned up in a fire,
And on its coals I baked bread and roasted meat to eat.
Should I, then, make the rest of it into a detestable thing?
Should I worship a block^&#42;1^ of wood from a tree?”

[NOTE]
====
. Or “a dry piece.”
====

[[v23-44-20]]

^<<v23-44-20,20>>^ He feeds on ashes.
His own deluded heart has led him astray.
He cannot save himself,^&#42;1^ nor does he say:
“Is there not a lie in my right hand?”

[NOTE]
====
. Or “his soul.”
====

[[v23-44-21]]

^<<v23-44-21,21>>^ “Remember these things, O Jacob, and you, O Israel,
For you are my servant.
I formed you, and you are my servant.
O Israel, I will not forget you.

[[v23-44-22]]

^<<v23-44-22,22>>^ I will blot out your transgressions as with a cloud
And your sins as with a thick cloud.
Return to me, for I will repurchase you.

[[v23-44-23]]

^<<v23-44-23,23>>^ Shout joyfully, you heavens,
For Jehovah has acted!
Shout in triumph, you depths of the earth!
Shout for joy, you mountains,
You forest, and all your trees!
For Jehovah has repurchased Jacob,
And on Israel he displays his splendor.”

[[v23-44-24]]

^<<v23-44-24,24>>^ This is what Jehovah says, your Repurchaser,
Who formed you since you were in the womb:
“I am Jehovah, who made everything.
I stretched out the heavens by myself,
And I spread out the earth.
Who was with me?

[[v23-44-25]]

^<<v23-44-25,25>>^ I am frustrating the signs of the empty talkers,^&#42;1^
And I am the One who makes diviners act like fools;
The One confounding the wise men
And turning their knowledge into foolishness;

[NOTE]
====
. Or “the false prophets.”
====

[[v23-44-26]]

^<<v23-44-26,26>>^ The One making the word of his servant come true
And completely fulfilling the predictions of his messengers;
The One saying of Jerusalem, ‘She will be inhabited,’
And of the cities of Judah, ‘They will be rebuilt,
And I will restore her ruins’;

[[v23-44-27]]

^<<v23-44-27,27>>^ The One saying to the deep waters, ‘Be evaporated,
And I will dry up all your rivers’;

[[v23-44-28]]

^<<v23-44-28,28>>^ The One saying of Cyrus, ‘He is my shepherd,
And he will completely carry out all my will’;
The One saying of Jerusalem, ‘She will be rebuilt,’
And of the temple, ‘Your foundation will be laid.’”

'''

xref:023-isaiah/023-isaiah-043.adoc#v23-43-0[&#60; Capítulo Anterior] | <<v23-44-0,Topo>> | xref:023-isaiah/023-isaiah-045.adoc#v23-45-0[Próximo Capítulo &#62;]