include::./index.adoc[]

[[v23-51-0]]
=== Isaiah, 51
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-51-1]]

^<<v23-51-1,1>>^ “Listen to me, you who are pursuing righteousness,
You who are seeking Jehovah.
Look to the rock from which you were hewn
And to the quarry from which you were dug.

[[v23-51-2]]

^<<v23-51-2,2>>^ Look to Abraham your father
And to Sarah who gave birth to you.^&#42;1^
For he was only one when I called him,
And I blessed him and made him many.

[NOTE]
====
. Or “brought you forth with labor pains.”
====

[[v23-51-3]]

^<<v23-51-3,3>>^ For Jehovah will comfort Zion.
He will bring comfort to all her ruins,
And he will make her wilderness like Eʹden
And her desert plain like the garden of Jehovah.
Exultation and rejoicing will be found in her,
Thanksgiving and melodious song.

[[v23-51-4]]

^<<v23-51-4,4>>^ Pay attention to me, O my people,
And give ear to me, my nation.
For a law will go out from me,
And my justice I will establish as a light to the peoples.

[[v23-51-5]]

^<<v23-51-5,5>>^ My righteousness draws near.
My salvation will go out,
And my arms will judge the peoples.
In me the islands will hope,
And for my arm^&#42;1^ they will wait.

[NOTE]
====
. Or “power.”
====

[[v23-51-6]]

^<<v23-51-6,6>>^ Raise your eyes to the heavens,
And look at the earth below.
For the heavens will disperse in fragments like smoke;
The earth will wear out like a garment,
And its inhabitants will die like gnats.
But my salvation will be eternal,
And my righteousness will never fail.^&#42;1^

[NOTE]
====
. Or “will not be shattered.”
====

[[v23-51-7]]

^<<v23-51-7,7>>^ Listen to me, you who know righteousness,
The people with my law^&#42;1^ in their heart.
Do not be afraid of the taunts of mortal men,
And do not be terrified because of their insults.

[NOTE]
====
. Or “instruction.”
====

[[v23-51-8]]

^<<v23-51-8,8>>^ For a moth will eat them up just like a garment;
The clothes moth^&#42;1^ will devour them like wool.
But my righteousness will last forever,
And my salvation for all generations.”

[NOTE]
====
. Or possibly, “The worm.”
====

[[v23-51-9]]

^<<v23-51-9,9>>^ Awake! Awake! Clothe yourself with strength,
O arm of Jehovah!
Awake as in the days of long ago, as in past generations.
Was it not you who broke Raʹhab^&#42;1^ to pieces,
Who pierced the sea monster?

[NOTE]
====
. See Glossary.
====

[[v23-51-10]]

^<<v23-51-10,10>>^ Are you not the one who dried up the sea, the waters of the vast deep?
The one who made the depths of the sea a roadway for the repurchased ones to cross?

[[v23-51-11]]

^<<v23-51-11,11>>^ The redeemed ones of Jehovah will return.
They will come to Zion with a joyful cry,
And unending joy will crown them.^&#42;1^
Exultation and rejoicing will be theirs,
And grief and sighing will flee away.

[NOTE]
====
. Lit., “be upon their head.”
====

[[v23-51-12]]

^<<v23-51-12,12>>^ “I myself am the One comforting you.
Why should you be afraid of a mortal man who will die
And of a son of man who will wither like green grass?

[[v23-51-13]]

^<<v23-51-13,13>>^ Why do you forget Jehovah your Maker,
The One who stretched out the heavens and laid the foundation of the earth?
And all day long you were in constant fear of the rage of the oppressor,^&#42;1^
As though he were in a position to bring you to ruin.
Where, now, is the rage of the oppressor?

[NOTE]
====
. Or “the one hemming you in.”
====

[[v23-51-14]]

^<<v23-51-14,14>>^ The one bent over in chains will soon be set free;
He will not die and go into the pit,
Nor will his bread be lacking.

[[v23-51-15]]

^<<v23-51-15,15>>^ But I am Jehovah your God,
Who stirs up the sea and makes its waves boisterous
—Jehovah of armies is his name.

[[v23-51-16]]

^<<v23-51-16,16>>^ I will put my words in your mouth,
And with the shadow of my hand I will cover you,
In order to plant the heavens and to lay the foundation of the earth
And to say to Zion, ‘You are my people.’

[[v23-51-17]]

^<<v23-51-17,17>>^ Awake! Awake! Rise up, O Jerusalem,
You who have drunk from the hand of Jehovah his cup of wrath.
You have drunk the goblet;
You have drained out the cup causing staggering.

[[v23-51-18]]

^<<v23-51-18,18>>^ Not one of all the sons whom she bore is there to guide her,
And not one of all the sons whom she raised has taken hold of her hand.

[[v23-51-19]]

^<<v23-51-19,19>>^ These two things have befallen you.
Who will sympathize with you?
Destruction and devastation, hunger and sword!
Who will comfort you?

[[v23-51-20]]

^<<v23-51-20,20>>^ Your sons have fainted.
They lie down at every street corner^&#42;1^
Like wild sheep in the net.
They are full of the wrath of Jehovah, the rebuke of your God.”

[NOTE]
====
. Lit., “at the head of all streets.”
====

[[v23-51-21]]

^<<v23-51-21,21>>^ So please listen to this,
O woman afflicted and drunk, though not with wine.

[[v23-51-22]]

^<<v23-51-22,22>>^ This is what your Lord Jehovah says, your God who defends his people:
“Look! I will take from your hand the cup causing staggering,
The goblet, my cup of wrath;
You will never drink it again.

[[v23-51-23]]

^<<v23-51-23,23>>^ I will put it into the hand of your tormentors,
Those who said to you,^&#42;1^ ‘Bow down so that we may walk over you!’
So you made your back like the ground,
Like a street for them to walk on.”

[NOTE]
====
. Or “to your soul.”
====

'''

xref:023-isaiah/023-isaiah-050.adoc#v23-50-0[&#60; Capítulo Anterior] | <<v23-51-0,Topo>> | xref:023-isaiah/023-isaiah-052.adoc#v23-52-0[Próximo Capítulo &#62;]