include::./index.adoc[]

[[v23-38-0]]
=== Isaiah, 38
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-38-1]]

^<<v23-38-1,1>>^ In those days Hez·e·kiʹah became sick and was at the point of death. The prophet Isaiah the son of Aʹmoz came and said to him, “This is what Jehovah says: ‘Give instructions to your household, for you will die; you will not recover.’”

[[v23-38-2]]

^<<v23-38-2,2>>^ At that Hez·e·kiʹah turned his face to the wall and began to pray to Jehovah:

[[v23-38-3]]

^<<v23-38-3,3>>^ “I beg you, O Jehovah, remember, please, how I have walked before you faithfully and with a complete heart, and I have done what was good in your eyes.” And Hez·e·kiʹah began to weep profusely.

[[v23-38-4]]

^<<v23-38-4,4>>^ Then the word of Jehovah came to Isaiah, saying:

[[v23-38-5]]

^<<v23-38-5,5>>^ “Go back and say to Hez·e·kiʹah, ‘This is what Jehovah the God of David your forefather says: “I have heard your prayer. I have seen your tears. Here I am adding 15 years to your life,^&#42;1^

[NOTE]
====
. Lit., “days.”
====

[[v23-38-6]]

^<<v23-38-6,6>>^ and I will rescue you and this city out of the hand of the king of As·syrʹi·a, and I will defend this city.

[[v23-38-7]]

^<<v23-38-7,7>>^ This is the sign from Jehovah to show you that Jehovah will carry out the word that he has spoken:

[[v23-38-8]]

^<<v23-38-8,8>>^ Here I will make the declining shadow of the sun on the stairway^&#42;1^ of Aʹhaz go back ten steps.”’” So the sun went back ten steps on the stairway that it had already descended.

[NOTE]
====
. Perhaps these stairs were used to count time, as on a sundial.
====

[[v23-38-9]]

^<<v23-38-9,9>>^ A writing^&#42;1^ of King Hez·e·kiʹah of Judah when he became sick and recovered from his sickness.

[NOTE]
====
. Or “composition.”
====

[[v23-38-10]]

^<<v23-38-10,10>>^ I said: “In the middle of my life
I must go into the gates of the Grave.^&#42;1^
I will be deprived of my remaining years.”

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v23-38-11]]

^<<v23-38-11,11>>^ I said: “I will not see Jah,^&#42;1^ Jah in the land of the living.
I will look no more on mankind
When I am with the inhabitants of the place where everything ceases.

[NOTE]
====
. “Jah” is a shortened form of the name Jehovah.
====

[[v23-38-12]]

^<<v23-38-12,12>>^ My own dwelling has been pulled out and removed from me
Like the tent of a shepherd.
I have rolled up my life like a loom worker;
He cuts me off like the threads of the warp.
From daylight to nightfall you keep bringing me to an end.

[[v23-38-13]]

^<<v23-38-13,13>>^ I calm myself until the morning.
Like a lion, he keeps breaking all my bones;
From daylight to nightfall you keep bringing me to an end.

[[v23-38-14]]

^<<v23-38-14,14>>^ Like the swift or the thrush,^&#42;1^ so I keep chirping;
I keep cooing like the dove.
My eyes look wearily to the height:
‘O Jehovah, I am in great distress;
Be my support!’^&#42;2^

[NOTE]
====
. Or possibly, “crane.”
. Lit., “Be my surety.”
====

[[v23-38-15]]

^<<v23-38-15,15>>^ What can I say?
He has spoken to me and acted.
I will walk humbly^&#42;1^ all my years
Because of my bitter distress.^&#42;2^

[NOTE]
====
. Or “solemnly.”
. Or “the bitterness of my soul.”
====

[[v23-38-16]]

^<<v23-38-16,16>>^ ‘O Jehovah, by these things^&#42;1^ every man lives,
And in them is the life of my spirit.
You will restore me to health and preserve me alive.

[NOTE]
====
. That is, God’s words and deeds.
====

[[v23-38-17]]

^<<v23-38-17,17>>^ Look! Instead of peace, I had great bitterness;
But in your fondness for me,^&#42;1^
You preserved me from the pit of destruction.
You have thrown all my sins behind your back.^&#42;2^

[NOTE]
====
. Or “my soul.”
. Or “removed all my sins from your sight.”
====

[[v23-38-18]]

^<<v23-38-18,18>>^ For the Grave^&#42;1^ cannot glorify you,
Death cannot praise you.
Those who go down into the pit cannot hope for your faithfulness.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v23-38-19]]

^<<v23-38-19,19>>^ The living, the living can praise you,
Just as I can this day.
A father can give his sons knowledge about your faithfulness.

[[v23-38-20]]

^<<v23-38-20,20>>^ O Jehovah, save me,
And we will play my songs on stringed instruments
All the days of our life at the house of Jehovah.’”

[[v23-38-21]]

^<<v23-38-21,21>>^ Isaiah then said: “Bring a cake of pressed dried figs and apply it to the boil, so that he may recover.”

[[v23-38-22]]

^<<v23-38-22,22>>^ Hez·e·kiʹah had asked: “What is the sign that I will go up to the house of Jehovah?”

'''

xref:023-isaiah/023-isaiah-037.adoc#v23-37-0[&#60; Capítulo Anterior] | <<v23-38-0,Topo>> | xref:023-isaiah/023-isaiah-039.adoc#v23-39-0[Próximo Capítulo &#62;]