include::./index.adoc[]

[[v23-27-0]]
=== Isaiah, 27
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-27-1]]

^<<v23-27-1,1>>^ In that day Jehovah, with his harsh and great and strong sword,
Will turn his attention to Le·viʹa·than,^&#42;1^ the gliding serpent,
To Le·viʹa·than, the twisting serpent,
And he will kill the monster that is in the sea.

[NOTE]
====
. See Glossary.
====

[[v23-27-2]]

^<<v23-27-2,2>>^ In that day sing to her:^&#42;1^
“A vineyard of foaming wine!

[NOTE]
====
. Apparently referring to Israel, here personified as a woman and likened to a vineyard.
====

[[v23-27-3]]

^<<v23-27-3,3>>^ I, Jehovah, am safeguarding her.
Every moment I water her.
I safeguard her night and day,
So that no one may harm her.

[[v23-27-4]]

^<<v23-27-4,4>>^ There is no wrath in me.
Who will confront me with thornbushes and weeds in the battle?
I will trample them and set them on fire all together.

[[v23-27-5]]

^<<v23-27-5,5>>^ Otherwise, let him hold fast to my stronghold.
Let him make peace with me;
Peace let him make with me.”

[[v23-27-6]]

^<<v23-27-6,6>>^ In the coming days Jacob will take root,
Israel will blossom and sprout,
And they will fill the land with produce.

[[v23-27-7]]

^<<v23-27-7,7>>^ Must he be struck with the stroke of the one striking him?
Or must he be killed as with the slaughter of his slain?

[[v23-27-8]]

^<<v23-27-8,8>>^ With a startling cry you will contend with her when sending her away.
He will expel her with his fierce blast in the day of the east wind.

[[v23-27-9]]

^<<v23-27-9,9>>^ So in this way the error of Jacob will be atoned for,
And this will be the full fruitage when his sin is taken away:
He will make all the stones of the altar
Like chalkstones that have been pulverized,
And no sacred poles^&#42;1^ or incense stands will be left.

[NOTE]
====
. See Glossary.
====

[[v23-27-10]]

^<<v23-27-10,10>>^ For the fortified city will be deserted;
The pastures will be forsaken and abandoned like a wilderness.
There the calf will graze and lie down
And will consume her branches.

[[v23-27-11]]

^<<v23-27-11,11>>^ When her twigs have dried up,
Women will come and break them off,
Making fires with them.
For this people is without understanding.
That is why their Maker will show them no mercy,
And the One who formed them will show them no favor.

[[v23-27-12]]

^<<v23-27-12,12>>^ In that day Jehovah will beat out the fruit from the flowing stream of the River^&#42;1^ to the Wadi^&#42;2^ of Egypt, and you will be gathered up one after the other, O people of Israel.

[NOTE]
====
. That is, the Euphrates.
. See Glossary.
====

[[v23-27-13]]

^<<v23-27-13,13>>^ In that day a great horn will be blown, and those who are perishing in the land of As·syrʹi·a and those dispersed in the land of Egypt will come and bow down to Jehovah in the holy mountain in Jerusalem.

'''

xref:023-isaiah/023-isaiah-026.adoc#v23-26-0[&#60; Capítulo Anterior] | <<v23-27-0,Topo>> | xref:023-isaiah/023-isaiah-028.adoc#v23-28-0[Próximo Capítulo &#62;]