include::./index.adoc[]

[[v23-19-0]]
=== Isaiah, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-19-1]]

^<<v23-19-1,1>>^ A pronouncement against Egypt:
Look! Jehovah is riding on a swift cloud and is coming into Egypt.
The worthless gods of Egypt will tremble before him,
And the heart of Egypt will melt within it.

[[v23-19-2]]

^<<v23-19-2,2>>^ “I will incite Egyptians against Egyptians,
And they will fight one another,
Each against his brother and his neighbor,
City against city, kingdom against kingdom.

[[v23-19-3]]

^<<v23-19-3,3>>^ And the spirit of Egypt will become bewildered within it,
And I will confuse its plans.
They will resort to the worthless gods,
To the charmers and to the spirit mediums and to the fortune-tellers.

[[v23-19-4]]

^<<v23-19-4,4>>^ I will hand Egypt over to a hard master,
And a harsh king will rule over them,” declares the true Lord, Jehovah of armies.

[[v23-19-5]]

^<<v23-19-5,5>>^ The water of the sea will be dried up,
And the river will become parched and run dry.

[[v23-19-6]]

^<<v23-19-6,6>>^ And the rivers will stink;
The Nile canals of Egypt will become low and parched.
The reeds and the rushes will decay.

[[v23-19-7]]

^<<v23-19-7,7>>^ The plants along the Nile River, at the mouth of the Nile,
And all the land sown with seed along the Nile will dry up.
It will be blown away, and it will be no more.

[[v23-19-8]]

^<<v23-19-8,8>>^ And the fishermen will mourn,
Those casting fishhooks into the Nile will lament,
And those who spread their nets on the water will dwindle.

[[v23-19-9]]

^<<v23-19-9,9>>^ Those who work in combed flax
And those making white fabric on the loom will be put to shame.

[[v23-19-10]]

^<<v23-19-10,10>>^ Her weavers will be crushed;
All the hired workers will grieve.^&#42;1^

[NOTE]
====
. Or “be grieved in soul.”
====

[[v23-19-11]]

^<<v23-19-11,11>>^ The princes of Zoʹan are foolish.
The wisest advisers of Pharʹaoh give unreasonable advice.
How can you say to Pharʹaoh:
“I am a descendant of wise ones,
A descendant of ancient kings”?

[[v23-19-12]]

^<<v23-19-12,12>>^ Where, then, are your wise men?
Let them tell you if they know what Jehovah of armies has decided concerning Egypt.

[[v23-19-13]]

^<<v23-19-13,13>>^ The princes of Zoʹan have acted foolishly;
The princes of Noph^&#42;1^ have been deceived;
The chiefs of her tribes have led Egypt astray.

[NOTE]
====
. Or “Memphis.”
====

[[v23-19-14]]

^<<v23-19-14,14>>^ Jehovah has poured out on her a spirit of confusion;
And they have led Egypt astray in whatever she does,
Like a drunk staggering in his vomit.

[[v23-19-15]]

^<<v23-19-15,15>>^ And Egypt will not have any work to do,
Whether for the head or the tail, the shoot or the rush.^&#42;1^

[NOTE]
====
. Or possibly, “the palm branch or the reed.”
====

[[v23-19-16]]

^<<v23-19-16,16>>^ In that day Egypt will become like women, trembling and terrified because of the threatening hand that Jehovah of armies raises against it.

[[v23-19-17]]

^<<v23-19-17,17>>^ And the land of Judah will become a cause for terror to Egypt. They will feel dread at the mention of it because of the decision that Jehovah of armies has made against them.

[[v23-19-18]]

^<<v23-19-18,18>>^ In that day there will be five cities in the land of Egypt speaking the language of Caʹnaan and swearing loyalty to Jehovah of armies. One city will be called The City of Tearing Down.

[[v23-19-19]]

^<<v23-19-19,19>>^ In that day there will be an altar to Jehovah in the middle of the land of Egypt and a pillar to Jehovah at its boundary.

[[v23-19-20]]

^<<v23-19-20,20>>^ It will be for a sign and for a witness to Jehovah of armies in the land of Egypt; for they will cry out to Jehovah because of the oppressors, and he will send them a savior, a grand one, who will save them.

[[v23-19-21]]

^<<v23-19-21,21>>^ And Jehovah will become known to the Egyptians, and the Egyptians will know Jehovah in that day, and they will offer sacrifices and gifts and make a vow to Jehovah and pay it.

[[v23-19-22]]

^<<v23-19-22,22>>^ Jehovah will strike Egypt, striking and healing it; and they will return to Jehovah, and he will respond to their entreaties and heal them.

[[v23-19-23]]

^<<v23-19-23,23>>^ In that day there will be a highway out of Egypt to As·syrʹi·a. Then As·syrʹi·a will come into Egypt, and Egypt into As·syrʹi·a, and Egypt will serve God together with As·syrʹi·a.

[[v23-19-24]]

^<<v23-19-24,24>>^ In that day Israel will be the third along with Egypt and with As·syrʹi·a, a blessing in the midst of the earth,

[[v23-19-25]]

^<<v23-19-25,25>>^ for Jehovah of armies will have blessed it, saying: “Blessed be my people, Egypt, and the work of my hands, As·syrʹi·a, and my inheritance, Israel.”

'''

xref:023-isaiah/023-isaiah-018.adoc#v23-18-0[&#60; Capítulo Anterior] | <<v23-19-0,Topo>> | xref:023-isaiah/023-isaiah-020.adoc#v23-20-0[Próximo Capítulo &#62;]