include::./index.adoc[]

[[v23-34-0]]
=== Isaiah, 34
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-34-1]]

^<<v23-34-1,1>>^ Come close to hear, you nations,
And pay attention, you peoples.
Let the earth and that which fills it listen,
The land and all its produce.

[[v23-34-2]]

^<<v23-34-2,2>>^ For Jehovah’s indignation is against all the nations,
And his wrath is against all their army.
He will devote them to destruction;
He will give them to the slaughter.

[[v23-34-3]]

^<<v23-34-3,3>>^ Their slain will be thrown out,
And the stench of their carcasses will ascend;
The mountains will melt because of^&#42;1^ their blood.

[NOTE]
====
. Or “will flow with.”
====

[[v23-34-4]]

^<<v23-34-4,4>>^ All the army of the heavens will rot away,
And the heavens will be rolled up like a scroll.
All their army will wither away,
As a withered leaf falls from the vine
And a shriveled fig from the fig tree.

[[v23-34-5]]

^<<v23-34-5,5>>^ “For in the heavens my sword will be drenched.
It will descend on Eʹdom in judgment,
On the people whom I devoted to destruction.

[[v23-34-6]]

^<<v23-34-6,6>>^ Jehovah has a sword; it will be covered with blood.
It will be covered with the fat,
With the blood of young rams and goats,
With the kidney fat of rams.
For Jehovah has a sacrifice in Bozʹrah,
A great slaughter in the land of Eʹdom.

[[v23-34-7]]

^<<v23-34-7,7>>^ The wild bulls will go down with them,
The young bulls with the powerful ones.
Their land will be drenched in blood,
And their dust will be soaked with fat.”

[[v23-34-8]]

^<<v23-34-8,8>>^ For Jehovah has a day of vengeance,
A year of retribution for the legal case over Zion.

[[v23-34-9]]

^<<v23-34-9,9>>^ Her^&#42;1^ streams will be changed into pitch,
And her dust into sulfur,
And her land will become like burning pitch.

[NOTE]
====
. Evidently referring to Bozrah, the capital of Edom.
====

[[v23-34-10]]

^<<v23-34-10,10>>^ By night or by day it will not be extinguished;
Its smoke will keep ascending forever.
From generation to generation she will remain devastated;
No one will pass through her forever and ever.

[[v23-34-11]]

^<<v23-34-11,11>>^ The pelican and the porcupine will possess her,
And long-eared owls and ravens will reside in her.
He will stretch out over her the measuring line of emptiness
And the plumb line^&#42;1^ of desolation.

[NOTE]
====
. Lit., “the stones.”
====

[[v23-34-12]]

^<<v23-34-12,12>>^ None of her nobles will be called to the kingship,
And all her princes will come to nothing.

[[v23-34-13]]

^<<v23-34-13,13>>^ Thorns will grow in her fortified towers,
Nettles and thorny weeds in her fortresses.
She will become a lair of jackals,
An enclosure for ostriches.

[[v23-34-14]]

^<<v23-34-14,14>>^ Desert creatures will meet up with howling animals,
And the wild goat^&#42;1^ will call to its companion.
Yes, there the nightjar will settle and find a place of rest.

[NOTE]
====
. Or possibly, “the goatlike demon.”
====

[[v23-34-15]]

^<<v23-34-15,15>>^ There the arrow snake will make its nest and lay eggs,
And it will hatch them and gather them in its shadow.
Yes, there the kites will gather, each one with her mate.

[[v23-34-16]]

^<<v23-34-16,16>>^ Search in the book of Jehovah and read it out loud:
Not one of them will be missing;
None of them will be lacking a mate,
For it is the mouth of Jehovah that has given the order,
And it is his spirit that has gathered them together.

[[v23-34-17]]

^<<v23-34-17,17>>^ He is the One who has cast the lot for them,
And his own hand has measured out their assigned place.^&#42;1^
They will possess it for all time;
They will reside in it throughout all generations.

[NOTE]
====
. Lit., “divided it for them with a measuring line.”
====

'''

xref:023-isaiah/023-isaiah-033.adoc#v23-33-0[&#60; Capítulo Anterior] | <<v23-34-0,Topo>> | xref:023-isaiah/023-isaiah-035.adoc#v23-35-0[Próximo Capítulo &#62;]