include::./index.adoc[]

[[v23-49-0]]
=== Isaiah, 49
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-49-1]]

^<<v23-49-1,1>>^ Listen to me, you islands,
And pay attention, you faraway nations.
Jehovah has called me before I was born.^&#42;1^
From the time I was in my mother’s womb he has made mention of my name.

[NOTE]
====
. Lit., “from the womb.”
====

[[v23-49-2]]

^<<v23-49-2,2>>^ He made my mouth like a sharp sword;
He has hidden me in the shadow of his hand.
He made me a polished arrow;
He concealed me in his quiver.

[[v23-49-3]]

^<<v23-49-3,3>>^ He said to me: “You are my servant, O Israel,
Through whom I will show my splendor.”

[[v23-49-4]]

^<<v23-49-4,4>>^ But I said: “I have toiled for nothing.
I used up my strength for an unreality, in vain.
But surely my judgment is with Jehovah,^&#42;1^
And my wages^&#42;2^ with my God.”

[NOTE]
====
. Or “Jehovah will grant me justice.”
. Or “reward.”
====

[[v23-49-5]]

^<<v23-49-5,5>>^ And now Jehovah, the One who formed me from the womb as his servant,
Has said for me to bring Jacob back to him,
So that Israel may be gathered to him.
I will be glorified in the eyes of Jehovah,
And my God will have become my strength.

[[v23-49-6]]

^<<v23-49-6,6>>^ And he said: “It is not enough that you are my servant
To raise up the tribes of Jacob
And to bring back those who were preserved of Israel.
I have also given you as a light of nations,
So that my salvation may reach the ends of the earth.”

[[v23-49-7]]

^<<v23-49-7,7>>^ This is what Jehovah, the Repurchaser of Israel, his Holy One, says to the one who is despised,^&#42;1^ to the one who is detested by the nation, to the servant of rulers:
“Kings will see and rise up,
And princes will bow down
Because of Jehovah, who is faithful,
The Holy One of Israel, who has chosen you.”

[NOTE]
====
. Or “despised in soul.”
====

[[v23-49-8]]

^<<v23-49-8,8>>^ This is what Jehovah says:
“In a time of favor^&#42;1^ I answered you,
And in a day of salvation I helped you;
I kept safeguarding you to give you as a covenant for the people,
To rehabilitate the land,
To cause them to possess their desolate inheritances,

[NOTE]
====
. Or “goodwill.”
====

[[v23-49-9]]

^<<v23-49-9,9>>^ To say to the prisoners, ‘Come out!’
And to those in the darkness, ‘Show yourselves!’
By the roadways they will feed,
Along all the worn paths^&#42;1^ will be their pastures.

[NOTE]
====
. Or possibly, “the bare hills.”
====

[[v23-49-10]]

^<<v23-49-10,10>>^ They will not go hungry, nor will they thirst,
Nor will scorching heat or the sun beat down on them.
For the One who has mercy on them will lead them,
And he will guide them by the springs of water.

[[v23-49-11]]

^<<v23-49-11,11>>^ I will make all my mountains into a road,
And my highways will be raised up.

[[v23-49-12]]

^<<v23-49-12,12>>^ Look! These are coming from far away,
And look! these from the north and from the west,
And these from the land of Siʹnim.”

[[v23-49-13]]

^<<v23-49-13,13>>^ Shout for joy, you heavens, and rejoice, you earth.
Let the mountains become cheerful with a joyful cry.
For Jehovah has comforted his people,
And he shows mercy to his own afflicted ones.

[[v23-49-14]]

^<<v23-49-14,14>>^ But Zion kept saying:
“Jehovah has abandoned me, and Jehovah has forgotten me.”

[[v23-49-15]]

^<<v23-49-15,15>>^ Can a woman forget her nursing child
Or have no compassion for the son of her womb?
Even if these women forget, I would never forget you.

[[v23-49-16]]

^<<v23-49-16,16>>^ Look! On my palms I have engraved you.
Your walls are always before me.

[[v23-49-17]]

^<<v23-49-17,17>>^ Your sons hurry back.
Those who tore you down and devastated you will depart from you.

[[v23-49-18]]

^<<v23-49-18,18>>^ Raise your eyes and look all around.
They are all gathering together.
They are coming to you.
“As surely as I am living,” declares Jehovah,
“You will clothe yourself with all of them as with ornaments,
And you will fasten them on yourself as a bride does.

[[v23-49-19]]

^<<v23-49-19,19>>^ Although your places were devastated and desolate and your land was in ruins,
Now it will become too cramped for those dwelling there,
And those who swallowed you down will be far away.

[[v23-49-20]]

^<<v23-49-20,20>>^ The sons born when you were bereaved will say in your hearing,
‘This place is too cramped for me.
Make room for me to dwell here.’

[[v23-49-21]]

^<<v23-49-21,21>>^ And you will say in your heart,
‘Who has fathered these for me,
Since I am a woman bereaved of children and barren,
Exiled and taken prisoner?
Who has raised these?
Look! I was left all alone,
So where have these come from?’”

[[v23-49-22]]

^<<v23-49-22,22>>^ This is what the Sovereign Lord Jehovah says:
“Look! I will raise up my hand to the nations,
And I will lift up my signal^&#42;1^ to the peoples.
They will bring your sons in their arms^&#42;2^
And carry your daughters on their shoulders.

[NOTE]
====
. Or “signal pole.”
. Lit., “bosom.”
====

[[v23-49-23]]

^<<v23-49-23,23>>^ Kings will become caretakers for you,
And their princesses will be your nurses.
They will bow down to you with their faces to the ground
And lick the dust of your feet,
And you will have to know that I am Jehovah;
Those hoping in me will not be put to shame.”

[[v23-49-24]]

^<<v23-49-24,24>>^ Can those already captured be taken from a mighty man,
Or can the captives of the tyrant be rescued?

[[v23-49-25]]

^<<v23-49-25,25>>^ But this is what Jehovah says:
“Even the captives of a mighty man will be taken away,
And those captured by the tyrant will be rescued.
I will oppose those who oppose you,
And I will save your own sons.

[[v23-49-26]]

^<<v23-49-26,26>>^ I will make those who mistreat you eat their own flesh,
And as with sweet wine, they will become drunk with their own blood.
And all people^&#42;1^ will have to know that I am Jehovah,
Your Savior and your Repurchaser,
The Powerful One of Jacob.”

[NOTE]
====
. Lit., “all flesh.”
====

'''

xref:023-isaiah/023-isaiah-048.adoc#v23-48-0[&#60; Capítulo Anterior] | <<v23-49-0,Topo>> | xref:023-isaiah/023-isaiah-050.adoc#v23-50-0[Próximo Capítulo &#62;]