include::./index.adoc[]

[[v23-42-0]]
=== Isaiah, 42
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-42-1]]

^<<v23-42-1,1>>^ Look! My servant, whom I support!
My chosen one, whom I have^&#42;1^ approved!
I have put my spirit in him;
He will bring justice to the nations.

[NOTE]
====
. Or “my soul has.”
====

[[v23-42-2]]

^<<v23-42-2,2>>^ He will not cry out or raise his voice,
And he will not make his voice heard in the street.

[[v23-42-3]]

^<<v23-42-3,3>>^ No crushed reed will he break,
And no smoldering wick will he extinguish.
In faithfulness he will bring justice.

[[v23-42-4]]

^<<v23-42-4,4>>^ He will not grow dim or be crushed until he establishes justice in the earth;
And the islands keep waiting for his law.^&#42;1^

[NOTE]
====
. Or “instruction.”
====

[[v23-42-5]]

^<<v23-42-5,5>>^ This is what the true God, Jehovah, says,
The Creator of the heavens and the Grand One who stretched them out,
The One who spread out the earth and its produce,
The One who gives breath to the people on it
And spirit to those who walk on it:

[[v23-42-6]]

^<<v23-42-6,6>>^ “I, Jehovah, have called you in righteousness;
I have taken hold of your hand.
I will safeguard you and give you as a covenant for the people
And as a light of the nations,

[[v23-42-7]]

^<<v23-42-7,7>>^ For you to open the blind eyes,
To bring the prisoner out of the dungeon
And those sitting in darkness out of the prison.

[[v23-42-8]]

^<<v23-42-8,8>>^ I am Jehovah. That is my name;
I give my glory to no one else,^&#42;1^
Nor my praise to graven images.

[NOTE]
====
. Or “I do not share my glory with anyone else.”
====

[[v23-42-9]]

^<<v23-42-9,9>>^ See, the first things have come to pass;
Now I am declaring new things.
Before they spring up, I tell you about them.”

[[v23-42-10]]

^<<v23-42-10,10>>^ Sing to Jehovah a new song,
His praise from the ends of the earth,
You who go down to the sea and all that fills it,
You islands and their inhabitants.

[[v23-42-11]]

^<<v23-42-11,11>>^ Let the wilderness and its cities raise their voice,
The settlements where Keʹdar dwells.
Let the inhabitants of the crag shout joyfully;
Let them cry out from the top of the mountains.

[[v23-42-12]]

^<<v23-42-12,12>>^ Let them attribute glory to Jehovah
And declare his praise in the islands.

[[v23-42-13]]

^<<v23-42-13,13>>^ Jehovah will go out like a mighty man.
He will awaken his zeal like a warrior.
He will shout, yes, he will let out a war cry;
He will show himself mightier than his enemies.

[[v23-42-14]]

^<<v23-42-14,14>>^ “I have kept quiet for a long time.
I remained silent and restrained myself.
Like a woman giving birth,
I will groan, pant, and gasp all at once.

[[v23-42-15]]

^<<v23-42-15,15>>^ I will devastate mountains and hills
And dry up all their vegetation.
I will turn rivers into islands^&#42;1^
And dry up reedy pools of water.

[NOTE]
====
. Or “coastlands.”
====

[[v23-42-16]]

^<<v23-42-16,16>>^ I will lead the blind in a way that they do not know
And cause them to tread on unfamiliar paths.
I will turn the darkness before them into light
And turn the rugged terrain into level land.
This is what I will do for them, and I will not abandon them.”

[[v23-42-17]]

^<<v23-42-17,17>>^ They will be turned back and will be utterly put to shame,
Those who trust in carved images,
Those who say to metal statues:^&#42;1^ “You are our gods.”

[NOTE]
====
. Or “molten statues.”
====

[[v23-42-18]]

^<<v23-42-18,18>>^ Listen, you who are deaf;
Look and see, you who are blind.

[[v23-42-19]]

^<<v23-42-19,19>>^ Who is blind except my servant,
So deaf as the messenger I send?
Who is so blind as the one rewarded,
So blind as the servant of Jehovah?

[[v23-42-20]]

^<<v23-42-20,20>>^ You see many things, but you do not keep watch.
You open your ears, but you do not listen.

[[v23-42-21]]

^<<v23-42-21,21>>^ For the sake of his righteousness,
Jehovah has taken pleasure in magnifying the law^&#42;1^ and making it glorious.

[NOTE]
====
. Or “instruction.”
====

[[v23-42-22]]

^<<v23-42-22,22>>^ But this is a people plundered and pillaged;
All of them are trapped in the holes and hidden in the prisons.
They have been plundered with no one to rescue them,
And pillaged with no one to say: “Bring them back!”

[[v23-42-23]]

^<<v23-42-23,23>>^ Who among you will hear this?
Who will pay attention and listen for the time to come?

[[v23-42-24]]

^<<v23-42-24,24>>^ Who has given Jacob for pillage
And Israel to the plunderers?
Is it not Jehovah, the One against whom we sinned?
In His ways they refused to walk,
And His law^&#42;1^ they would not obey.

[NOTE]
====
. Or “instruction.”
====

[[v23-42-25]]

^<<v23-42-25,25>>^ So He kept pouring out on him wrath,
His anger and the fury of war.
It consumed everything around him, but he paid no attention.
It blazed up against him, but he would not take it to heart.

'''

xref:023-isaiah/023-isaiah-041.adoc#v23-41-0[&#60; Capítulo Anterior] | <<v23-42-0,Topo>> | xref:023-isaiah/023-isaiah-043.adoc#v23-43-0[Próximo Capítulo &#62;]