include::./index.adoc[]

[[v23-35-0]]
=== Isaiah, 35
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-35-1]]

^<<v23-35-1,1>>^ The wilderness and the parched land will exult,
And the desert plain will be joyful and blossom as the saffron.^&#42;1^

[NOTE]
====
. Or “crocus.”
====

[[v23-35-2]]

^<<v23-35-2,2>>^ Without fail it will blossom;
It will rejoice and shout for joy.
The glory of Lebʹa·non will be given to it,
The splendor of Carʹmel and of Sharʹon.
They will see the glory of Jehovah, the splendor of our God.

[[v23-35-3]]

^<<v23-35-3,3>>^ Strengthen the weak hands,
And make firm the knees that are shaking.

[[v23-35-4]]

^<<v23-35-4,4>>^ Say to those who are anxious at heart:
“Be strong. Do not be afraid.
Look! Your own God will come with vengeance,
God will come with retribution.
He will come and save you.”

[[v23-35-5]]

^<<v23-35-5,5>>^ At that time the eyes of the blind will be opened,
And the ears of the deaf will be unstopped.

[[v23-35-6]]

^<<v23-35-6,6>>^ At that time the lame will leap like the deer,
And the tongue of the speechless will shout for joy.
For waters will burst forth in the wilderness,
And streams in the desert plain.

[[v23-35-7]]

^<<v23-35-7,7>>^ The heat-parched ground will become a reedy pool,
And the thirsty ground springs of water.
In the lairs where jackals rested,
There will be green grass and reeds and papyrus.

[[v23-35-8]]

^<<v23-35-8,8>>^ And a highway will be there,
Yes, a way called the Way of Holiness.
The unclean one will not travel on it.
It is reserved for the one walking on the way;
No one foolish will stray onto it.

[[v23-35-9]]

^<<v23-35-9,9>>^ No lion will be there,
And no vicious wild beasts will come on it.
They will not be found there;
Only the repurchased ones will walk there.

[[v23-35-10]]

^<<v23-35-10,10>>^ Those redeemed by Jehovah will return and come to Zion with a joyful cry.
Unending joy will crown their heads.
Exultation and rejoicing will be theirs,
And grief and sighing will flee away.

'''

xref:023-isaiah/023-isaiah-034.adoc#v23-34-0[&#60; Capítulo Anterior] | <<v23-35-0,Topo>> | xref:023-isaiah/023-isaiah-036.adoc#v23-36-0[Próximo Capítulo &#62;]