include::./index.adoc[]

[[v23-41-0]]
=== Isaiah, 41
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v23-41-1]]

^<<v23-41-1,1>>^ “Listen to me in silence,^&#42;1^ you islands;
Let the nations regain their strength.
Let them approach; then let them speak.
Let us come together for judgment.

[NOTE]
====
. Or “Keep silence before me.”
====

[[v23-41-2]]

^<<v23-41-2,2>>^ Who has raised up someone from the sunrise,^&#42;1^
Calling him in righteousness to His feet,^&#42;2^
To hand over nations to him
And to make him subdue kings?
Who reduces them to dust before his sword,
Like windblown stubble before his bow?

[NOTE]
====
. Or “from the east.”
. That is, to serve Him.
====

[[v23-41-3]]

^<<v23-41-3,3>>^ He pursues them, passing along unhindered
Over paths that his feet have not traveled.

[[v23-41-4]]

^<<v23-41-4,4>>^ Who has acted and done this,
Summoning the generations from the beginning?
I, Jehovah, am the First One;
And with the last ones I am the same.”

[[v23-41-5]]

^<<v23-41-5,5>>^ The islands have seen it and have become afraid.
The ends of the earth began to tremble.
They draw near and come forward.

[[v23-41-6]]

^<<v23-41-6,6>>^ Each one helps his companion
And says to his brother: “Be strong.”

[[v23-41-7]]

^<<v23-41-7,7>>^ So the craftsman strengthens the metalworker;
The one who flattens with the forge hammer
Strengthens the one hammering at the anvil.
He says about the soldering: “It is good.”
Then it is fastened with nails so that it will not topple over.

[[v23-41-8]]

^<<v23-41-8,8>>^ “But you, O Israel, are my servant,
You, O Jacob, whom I have chosen,
The offspring^&#42;1^ of Abraham my friend,

[NOTE]
====
. Lit., “seed.”
====

[[v23-41-9]]

^<<v23-41-9,9>>^ You, whom I took from the ends of the earth,
And you, whom I called from its most distant parts.
I said to you, ‘You are my servant;
I have chosen you; I have not rejected you.

[[v23-41-10]]

^<<v23-41-10,10>>^ Do not be afraid, for I am with you.
Do not be anxious, for I am your God.
I will fortify you, yes, I will help you,
I will really hold on to you with my right hand of righteousness.’

[[v23-41-11]]

^<<v23-41-11,11>>^ Look! All those getting enraged against you will be put to shame and humiliated.
Those who fight with you will be brought to nothing and perish.

[[v23-41-12]]

^<<v23-41-12,12>>^ You will search for men who struggle with you, but you will not find them;
The men at war with you will become as something nonexistent, as nothing at all.

[[v23-41-13]]

^<<v23-41-13,13>>^ For I, Jehovah your God, am grasping your right hand,
The One saying to you, ‘Do not be afraid. I will help you.’

[[v23-41-14]]

^<<v23-41-14,14>>^ Do not be afraid, you worm^&#42;1^ Jacob,
You men of Israel, I will help you,” declares Jehovah, your Repurchaser, the Holy One of Israel.

[NOTE]
====
. That is, defenseless and lowly.
====

[[v23-41-15]]

^<<v23-41-15,15>>^ “Look! I have made you a threshing sledge,
A new threshing instrument with double-edged teeth.
You will tread down the mountains and crush them
And make the hills like chaff.

[[v23-41-16]]

^<<v23-41-16,16>>^ You will winnow them,
And the wind will carry them away;
A windstorm will scatter them.
You will be joyful in Jehovah,
And you will boast in the Holy One of Israel.”

[[v23-41-17]]

^<<v23-41-17,17>>^ “The needy and the poor are seeking water, but there is none.
Their tongue is dry from thirst.
I, Jehovah, will answer them.
I, the God of Israel, will not abandon them.

[[v23-41-18]]

^<<v23-41-18,18>>^ I will make rivers flow on the bare hills
And springs in the valley plains.
I will turn the wilderness into a reedy pool of water
And the waterless land into springs of water.

[[v23-41-19]]

^<<v23-41-19,19>>^ In the desert I will plant the cedar tree,
The acacia and the myrtle and the pine tree.
In the desert plain I will plant the juniper tree,
Together with the ash and the cypress tree,

[[v23-41-20]]

^<<v23-41-20,20>>^ So that all people may see and know
And pay attention and understand
That the hand of Jehovah has done this,
And the Holy One of Israel has created it.”

[[v23-41-21]]

^<<v23-41-21,21>>^ “Present your case,” says Jehovah.
“Produce your arguments,” says the King of Jacob.

[[v23-41-22]]

^<<v23-41-22,22>>^ “Produce evidence and tell us the things that will happen.
Do tell us about the former^&#42;1^ things,
So that we may reflect on them^&#42;2^ and know their outcome.
Or declare to us the things that are coming.

[NOTE]
====
. Lit., “first.”
. Or “apply our heart.”
====

[[v23-41-23]]

^<<v23-41-23,23>>^ Tell us what will happen in the future,
So that we may know that you are gods.
Yes, do something, good or bad,
So that we may be amazed when we see it.

[[v23-41-24]]

^<<v23-41-24,24>>^ Look! You are something nonexistent,
And your achievement is nothing.
Anyone who chooses you is detestable.

[[v23-41-25]]

^<<v23-41-25,25>>^ I have raised up someone from the north, and he will come,
One from the rising of the sun^&#42;1^ who will call on my name.
He will trample rulers^&#42;2^ as if they were clay,
Like a potter who treads moist clay.

[NOTE]
====
. Or “from the east.”
. Or “deputy rulers.”
====

[[v23-41-26]]

^<<v23-41-26,26>>^ Who told about this from the beginning, so that we could know,
Or from times past, so that we could say, ‘He is right’?
Indeed, no one announced it!
No one declared it!
No one heard anything from you!”

[[v23-41-27]]

^<<v23-41-27,27>>^ I was the first to say to Zion: “Look! Here they are!”
And to Jerusalem I will send a bearer of good news.

[[v23-41-28]]

^<<v23-41-28,28>>^ But I kept looking, and there was no one;
There was not one among them to give advice.
And I kept asking them to reply.

[[v23-41-29]]

^<<v23-41-29,29>>^ Look! All of them are a delusion.^&#42;1^
Their works are nothing.
Their metal images^&#42;2^ are wind and unreality.

[NOTE]
====
. Or “something nonexistent.”
. Or “molten statues.”
====

'''

xref:023-isaiah/023-isaiah-040.adoc#v23-40-0[&#60; Capítulo Anterior] | <<v23-41-0,Topo>> | xref:023-isaiah/023-isaiah-042.adoc#v23-42-0[Próximo Capítulo &#62;]