include::./index.adoc[]

[[v11-22-0]]
=== The First of Kings, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-22-1]]

^<<v11-22-1,1>>^ For three years there was no war between Syria and Israel.

[[v11-22-2]]

^<<v11-22-2,2>>^ In the third year King Je·hoshʹa·phat of Judah went down to the king of Israel.

[[v11-22-3]]

^<<v11-22-3,3>>^ Then the king of Israel said to his servants: “Do you know that Raʹmoth-gilʹe·ad belongs to us? And yet we are hesitating to take it back from the king of Syria.”

[[v11-22-4]]

^<<v11-22-4,4>>^ He then said to Je·hoshʹa·phat: “Will you go with me to fight at Raʹmoth-gilʹe·ad?” Je·hoshʹa·phat replied to the king of Israel: “I am the same as you. My people are the same as your people. My horses are the same as your horses.”

[[v11-22-5]]

^<<v11-22-5,5>>^ But Je·hoshʹa·phat said to the king of Israel: “First inquire, please, for the word of Jehovah.”

[[v11-22-6]]

^<<v11-22-6,6>>^ So the king of Israel gathered the prophets together, about 400 men, and said to them: “Should I go to war against Raʹmoth-gilʹe·ad, or should I refrain?” They said: “Go up, and Jehovah will give it into the king’s hand.”

[[v11-22-7]]

^<<v11-22-7,7>>^ Je·hoshʹa·phat then said: “Is there not here a prophet of Jehovah? Let us also inquire through him.”

[[v11-22-8]]

^<<v11-22-8,8>>^ At that the king of Israel said to Je·hoshʹa·phat: “There is still one more man through whom we can inquire of Jehovah; but I hate him, for he never prophesies good things concerning me, only bad. He is Mi·caiʹah the son of Imʹlah.” However, Je·hoshʹa·phat said: “The king should not say such a thing.”

[[v11-22-9]]

^<<v11-22-9,9>>^ So the king of Israel called a court official and said: “Bring Mi·caiʹah the son of Imʹlah quickly.”

[[v11-22-10]]

^<<v11-22-10,10>>^ Now the king of Israel and Je·hoshʹa·phat the king of Judah were each sitting on his throne, dressed in royal attire, at the threshing floor at the entrance of the gate of Sa·marʹi·a, and all the prophets were prophesying before them.

[[v11-22-11]]

^<<v11-22-11,11>>^ Then Zed·e·kiʹah the son of Che·naʹa·nah made for himself iron horns and said: “This is what Jehovah says, ‘With these you will gore^&#42;1^ the Syrians until you exterminate them.’”

[NOTE]
====
. Or “push.”
====

[[v11-22-12]]

^<<v11-22-12,12>>^ All the other prophets were prophesying the same way, saying: “Go up to Raʹmoth-gilʹe·ad and you will be successful; Jehovah will give it into the king’s hand.”

[[v11-22-13]]

^<<v11-22-13,13>>^ So the messenger who went to call Mi·caiʹah said to him: “Look! The words of the prophets are unanimously favorable to the king. Let your word, please, become like their words, and speak favorably.”

[[v11-22-14]]

^<<v11-22-14,14>>^ But Mi·caiʹah said: “As surely as Jehovah is living, whatever Jehovah says to me is what I will speak.”

[[v11-22-15]]

^<<v11-22-15,15>>^ Then he came in to the king, and the king asked him: “Mi·caiʹah, should we go to war against Raʹmoth-gilʹe·ad, or should we refrain?” At once he replied: “Go up and you will be successful; Jehovah will give it into the king’s hand.”

[[v11-22-16]]

^<<v11-22-16,16>>^ At that the king said to him: “How many times must I put you under oath not to speak to me anything but the truth in the name of Jehovah?”

[[v11-22-17]]

^<<v11-22-17,17>>^ So he said: “I see all the Israelites scattered on the mountains, like sheep that have no shepherd. Jehovah said: ‘These have no master. Let each one go back to his house in peace.’”

[[v11-22-18]]

^<<v11-22-18,18>>^ Then the king of Israel said to Je·hoshʹa·phat: “Did I not tell you, ‘He will not prophesy good things concerning me, only bad’?”

[[v11-22-19]]

^<<v11-22-19,19>>^ Mi·caiʹah then said: “Therefore, hear the word of Jehovah: I saw Jehovah sitting on his throne and all the army of the heavens standing by him, to his right and to his left.

[[v11-22-20]]

^<<v11-22-20,20>>^ Jehovah then said, ‘Who will fool Aʹhab, so that he will go up and fall at Raʹmoth-gilʹe·ad?’ And one was saying one thing while another said something else.

[[v11-22-21]]

^<<v11-22-21,21>>^ Then a spirit^&#42;1^ came forward and stood before Jehovah and said, ‘I will fool him.’ Jehovah asked him, ‘How will you do it?’

[NOTE]
====
. Or “an angel.”
====

[[v11-22-22]]

^<<v11-22-22,22>>^ He replied, ‘I will go out and become a deceptive spirit in the mouth of all his prophets.’ So he said, ‘You will fool him, and what is more, you will be successful. Go out and do that.’

[[v11-22-23]]

^<<v11-22-23,23>>^ And now Jehovah has put a deceptive spirit in the mouth of all these prophets of yours, but Jehovah has declared calamity for you.”

[[v11-22-24]]

^<<v11-22-24,24>>^ Zed·e·kiʹah the son of Che·naʹa·nah now approached and struck Mi·caiʹah on the cheek and said: “Which way did the spirit of Jehovah pass from me to speak with you?”

[[v11-22-25]]

^<<v11-22-25,25>>^ Mi·caiʹah replied: “Look! You will see which way on the day when you will enter the innermost room to hide.”

[[v11-22-26]]

^<<v11-22-26,26>>^ Then the king of Israel said: “Take Mi·caiʹah and turn him over to Aʹmon the chief of the city and to Joʹash the king’s son.

[[v11-22-27]]

^<<v11-22-27,27>>^ Tell them, ‘This is what the king says: “Put this fellow in the prison and feed him with a reduced allowance of bread and water until I return in peace.”’”

[[v11-22-28]]

^<<v11-22-28,28>>^ But Mi·caiʹah said: “If you do return in peace, Jehovah has not spoken with me.” Then he added: “Take note, all you peoples.”

[[v11-22-29]]

^<<v11-22-29,29>>^ So the king of Israel and Je·hoshʹa·phat the king of Judah went up to Raʹmoth-gilʹe·ad.

[[v11-22-30]]

^<<v11-22-30,30>>^ The king of Israel now said to Je·hoshʹa·phat: “I will disguise myself and will go into the battle, but you should put on your royal attire.” So the king of Israel disguised himself and entered the battle.

[[v11-22-31]]

^<<v11-22-31,31>>^ Now the king of Syria had ordered his 32 chariot commanders: “Do not fight with anyone, small or great, except the king of Israel.”

[[v11-22-32]]

^<<v11-22-32,32>>^ And as soon as the chariot commanders saw Je·hoshʹa·phat, they said to themselves: “Surely it is the king of Israel.” So they turned to fight against him; and Je·hoshʹa·phat began to cry for help.

[[v11-22-33]]

^<<v11-22-33,33>>^ When the chariot commanders saw that it was not the king of Israel, they immediately turned back from following him.

[[v11-22-34]]

^<<v11-22-34,34>>^ But one man shot his bow at random,^&#42;1^ and he struck the king of Israel between the joints of his coat of mail. So the king said to his charioteer: “Turn around and take me out of the battle,^&#42;2^ for I have been badly wounded.”

[NOTE]
====
. Or “in his innocence.”
. Lit., “camp.”
====

[[v11-22-35]]

^<<v11-22-35,35>>^ The fighting raged throughout that day, and the king had to be propped up in the chariot, facing the Syrians. The blood of the wound poured out into the interior of the war chariot, and he died in the evening.

[[v11-22-36]]

^<<v11-22-36,36>>^ Around sunset a cry passed through the camp, saying: “Everyone to his city! Everyone to his land!”

[[v11-22-37]]

^<<v11-22-37,37>>^ Thus the king died, and he was brought to Sa·marʹi·a; they buried the king in Sa·marʹi·a.

[[v11-22-38]]

^<<v11-22-38,38>>^ When they washed off the war chariot by the pool of Sa·marʹi·a, the dogs licked up his blood and the prostitutes bathed there,^&#42;1^ according to the word that Jehovah had spoken.

[NOTE]
====
. Or possibly, “where the prostitutes bathed, the dogs licked up his blood.”
====

[[v11-22-39]]

^<<v11-22-39,39>>^ As for the rest of the history of Aʹhab, all that he did and the house^&#42;1^ of ivory that he built and all the cities that he built, is it not written in the book of the history of the times of the kings of Israel?

[NOTE]
====
. Or “palace.”
====

[[v11-22-40]]

^<<v11-22-40,40>>^ Then Aʹhab was laid to rest with his forefathers; and his son A·ha·ziʹah became king in his place.

[[v11-22-41]]

^<<v11-22-41,41>>^ Je·hoshʹa·phat the son of Aʹsa had become king over Judah in the fourth year of King Aʹhab of Israel.

[[v11-22-42]]

^<<v11-22-42,42>>^ Je·hoshʹa·phat was 35 years old when he became king, and he reigned for 25 years in Jerusalem. His mother’s name was A·zuʹbah the daughter of Shilʹhi.

[[v11-22-43]]

^<<v11-22-43,43>>^ He kept walking in all the way of Aʹsa his father. He did not deviate from it, and he did what was right in Jehovah’s eyes. However, the high places were not removed, and the people were still sacrificing and making sacrificial smoke on the high places.

[[v11-22-44]]

^<<v11-22-44,44>>^ Je·hoshʹa·phat kept peaceful relations with the king of Israel.

[[v11-22-45]]

^<<v11-22-45,45>>^ As for the rest of the history of Je·hoshʹa·phat, his mighty exploits and how he waged war, is it not written in the book of the history of the times of the kings of Judah?

[[v11-22-46]]

^<<v11-22-46,46>>^ He also cleared out of the land the rest of the male temple prostitutes who had been left over in the days of Aʹsa his father.

[[v11-22-47]]

^<<v11-22-47,47>>^ Then there was no king in Eʹdom; a deputy was acting as king.

[[v11-22-48]]

^<<v11-22-48,48>>^ Je·hoshʹa·phat also made Tarʹshish ships^&#42;1^ to go to Oʹphir for gold, but they did not go because the ships were wrecked at Eʹzi·on-geʹber.

[NOTE]
====
. See Glossary.
====

[[v11-22-49]]

^<<v11-22-49,49>>^ It was then that A·ha·ziʹah the son of Aʹhab said to Je·hoshʹa·phat: “Let my servants go with your servants in the ships,” but Je·hoshʹa·phat did not consent.

[[v11-22-50]]

^<<v11-22-50,50>>^ Then Je·hoshʹa·phat was laid to rest with his forefathers and was buried with his forefathers in the City of David his forefather; and his son Je·hoʹram became king in his place.

[[v11-22-51]]

^<<v11-22-51,51>>^ A·ha·ziʹah the son of Aʹhab became king over Israel in Sa·marʹi·a in the 17th year of King Je·hoshʹa·phat of Judah, and he reigned over Israel for two years.

[[v11-22-52]]

^<<v11-22-52,52>>^ And he kept doing what was bad in Jehovah’s eyes and walking in the way of his father and his mother and in the way of Jer·o·boʹam the son of Neʹbat, who had caused Israel to sin.

[[v11-22-53]]

^<<v11-22-53,53>>^ He continued serving Baʹal and bowing down to him and kept offending Jehovah the God of Israel, just as his father had done.

'''

xref:011-1-kings/011-1-kings-021.adoc#v11-21-0[&#60; Capítulo Anterior] | <<v11-22-0,Topo>> | xref:012-2-kings/012-2-kings-001.adoc#v12-1-0[Próximo Capítulo &#62;]