include::./index.adoc[]

[[v11-2-0]]
=== The First of Kings, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-2-1]]

^<<v11-2-1,1>>^ When the time of David’s death drew near, he gave his son Solʹo·mon these instructions:

[[v11-2-2]]

^<<v11-2-2,2>>^ “I am about to die.^&#42;1^ Therefore, be strong and prove yourself a man.

[NOTE]
====
. Lit., “I am going in the way of all the earth.”
====

[[v11-2-3]]

^<<v11-2-3,3>>^ You must keep your obligation to Jehovah your God by walking in his ways and by observing his statutes, his commandments, his judgments, and his reminders as they are written in the Law of Moses; then you will succeed^&#42;1^ in everything you do and everywhere you turn.

[NOTE]
====
. Or “act wisely.”
====

[[v11-2-4]]

^<<v11-2-4,4>>^ And Jehovah will carry out his promise that he made concerning me: ‘If your sons pay attention to their way by walking faithfully before me with all their heart and soul,^&#42;1^ there will never fail to be a man of your line^&#42;2^ sitting on the throne of Israel.’

[NOTE]
====
. See Glossary.
. Lit., “will not be cut off from you a man.”
====

[[v11-2-5]]

^<<v11-2-5,5>>^ “You also well know what Joʹab the son of Ze·ruʹiah did to me, what he did to two chiefs of the armies of Israel—Abʹner the son of Ner and A·maʹsa the son of Jeʹther. He killed them, shedding the blood of war in peacetime, and he put the blood of war on the belt around his waist and on the sandals on his feet.

[[v11-2-6]]

^<<v11-2-6,6>>^ You must act according to your wisdom and not let his gray hairs go down in peace to the Grave.^&#42;1^

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v11-2-7]]

^<<v11-2-7,7>>^ “But toward the sons of Bar·zilʹlai the Gilʹe·ad·ite, you should show loyal love, and they should be among those eating at your table, for that was how they stood by me when I ran away from your brother Abʹsa·lom.

[[v11-2-8]]

^<<v11-2-8,8>>^ “There is also with you Shimʹe·i the son of Geʹra the Benʹja·min·ite from Ba·huʹrim. He was the one who cursed me with a vicious curse on the day that I was going to Ma·ha·naʹim; but when he came down to meet me at the Jordan, I swore to him by Jehovah: ‘I will not put you to death by the sword.’

[[v11-2-9]]

^<<v11-2-9,9>>^ Now do not leave him unpunished, for you are a wise man and you know what you should do to him; you must bring his gray hairs down to the Grave^&#42;1^ with blood.”

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v11-2-10]]

^<<v11-2-10,10>>^ Then David was laid to rest with his forefathers and was buried in the City of David.

[[v11-2-11]]

^<<v11-2-11,11>>^ The length^&#42;1^ of David’s reign over Israel was 40 years. In Hebʹron he reigned for 7 years, and in Jerusalem he reigned for 33 years.

[NOTE]
====
. Lit., “The days.”
====

[[v11-2-12]]

^<<v11-2-12,12>>^ Solʹo·mon then sat down on the throne of David his father, and gradually his kingship became firmly established.

[[v11-2-13]]

^<<v11-2-13,13>>^ In time Ad·o·niʹjah the son of Hagʹgith came to Bath-sheʹba, Solʹo·mon’s mother. She asked: “Is your coming peaceable?” He replied: “It is peaceable.”

[[v11-2-14]]

^<<v11-2-14,14>>^ He then said: “I have something to say to you.” So she said: “Speak.”

[[v11-2-15]]

^<<v11-2-15,15>>^ He continued: “You well know that the kingship was to become mine, and all Israel expected^&#42;1^ me to become king; but the kingship eluded me and became my brother’s, for it was from Jehovah that it became his.

[NOTE]
====
. Lit., “had set their faces on.”
====

[[v11-2-16]]

^<<v11-2-16,16>>^ But now there is just one request that I am making of you. Do not turn me away.” So she said to him: “Speak.”

[[v11-2-17]]

^<<v11-2-17,17>>^ He then said: “Please, ask Solʹo·mon the king—for he will not turn you away—to give me Abʹi·shag the Shuʹnam·mite as a wife.”

[[v11-2-18]]

^<<v11-2-18,18>>^ To this Bath-sheʹba said: “Very well! I will speak for you to the king.”

[[v11-2-19]]

^<<v11-2-19,19>>^ So Bath-sheʹba went in to King Solʹo·mon to speak to him for Ad·o·niʹjah. At once the king rose to meet her and bowed down to her. Then he sat down on his throne and had a throne set for the king’s mother, so that she could sit at his right.

[[v11-2-20]]

^<<v11-2-20,20>>^ She then said: “There is one small request that I am making of you. Do not turn me away.” So the king said to her: “Make it, my mother; for I will not turn you away.”

[[v11-2-21]]

^<<v11-2-21,21>>^ She said: “Let Abʹi·shag the Shuʹnam·mite be given as a wife to your brother Ad·o·niʹjah.”

[[v11-2-22]]

^<<v11-2-22,22>>^ At this King Solʹo·mon answered his mother: “Why are you requesting Abʹi·shag the Shuʹnam·mite for Ad·o·niʹjah? You may as well request the kingship for him, for he is my older brother, and supporting him are A·biʹa·thar the priest and Joʹab the son of Ze·ruʹiah.”

[[v11-2-23]]

^<<v11-2-23,23>>^ With that King Solʹo·mon swore by Jehovah: “So may God do to me and add to it if it was not at the cost of his own life^&#42;1^ that Ad·o·niʹjah made this request.

[NOTE]
====
. Or “not against his own soul.”
====

[[v11-2-24]]

^<<v11-2-24,24>>^ And now, as surely as Jehovah is living, who has firmly established me and seated me on the throne of David my father and who made a house^&#42;1^ for me, just as he promised, Ad·o·niʹjah will be put to death today.”

[NOTE]
====
. Or “dynasty.”
====

[[v11-2-25]]

^<<v11-2-25,25>>^ King Solʹo·mon immediately sent Be·naiʹah the son of Je·hoiʹa·da, who went out and struck Ad·o·niʹjah down,^&#42;1^ and he died.

[NOTE]
====
. Or “who fell upon Adonijah.”
====

[[v11-2-26]]

^<<v11-2-26,26>>^ To A·biʹa·thar the priest, the king said: “Go to your fields in Anʹa·thoth! You deserve to die, but on this day I will not put you to death because you carried the Ark of the Sovereign Lord Jehovah before David my father and because you shared in all the hardships that my father suffered.”

[[v11-2-27]]

^<<v11-2-27,27>>^ So Solʹo·mon drove A·biʹa·thar out from serving as a priest of Jehovah, to fulfill Jehovah’s word against the house of Eʹli in Shiʹloh.

[[v11-2-28]]

^<<v11-2-28,28>>^ When the news reached Joʹab—for Joʹab had supported Ad·o·niʹjah but he had not supported Abʹsa·lom—Joʹab fled to the tent of Jehovah and grabbed hold of the horns of the altar.

[[v11-2-29]]

^<<v11-2-29,29>>^ Then King Solʹo·mon was told: “Joʹab has fled to the tent of Jehovah, and he is there beside the altar.” So Solʹo·mon sent Be·naiʹah the son of Je·hoiʹa·da, saying: “Go, strike him down!”

[[v11-2-30]]

^<<v11-2-30,30>>^ So Be·naiʹah went to the tent of Jehovah and said to him: “This is what the king says, ‘Come out!’” But he said: “No! I will die here.” Be·naiʹah brought word back to the king: “This is what Joʹab said, and this is what he answered me.”

[[v11-2-31]]

^<<v11-2-31,31>>^ Then the king said to him: “Do just as he said; strike him down and bury him and remove from me and from the house of my father the blood that Joʹab spilled without just cause.

[[v11-2-32]]

^<<v11-2-32,32>>^ Jehovah will bring his blood back on his own head, for without my father David’s knowledge, he struck down and killed with the sword two men more righteous and better than he was: Abʹner the son of Ner, the chief of the army of Israel, and A·maʹsa the son of Jeʹther, the chief of the army of Judah.

[[v11-2-33]]

^<<v11-2-33,33>>^ Their blood will come back on the head of Joʹab and on the head of his offspring^&#42;1^ forever; but for David, his offspring,^&#42;2^ his house, and his throne, may there be peace from Jehovah forever.”

[NOTE]
====
. Or “descendants.”
. Or “descendants.”
====

[[v11-2-34]]

^<<v11-2-34,34>>^ Then Be·naiʹah the son of Je·hoiʹa·da went up and struck Joʹab down and put him to death, and he was buried at his own house in the wilderness.

[[v11-2-35]]

^<<v11-2-35,35>>^ Then the king appointed Be·naiʹah the son of Je·hoiʹa·da over the army in his place, and the king appointed Zaʹdok the priest in place of A·biʹa·thar.

[[v11-2-36]]

^<<v11-2-36,36>>^ Then the king summoned Shimʹe·i and said to him: “Build yourself a house in Jerusalem, and live there; do not go out from there to any other place.

[[v11-2-37]]

^<<v11-2-37,37>>^ On the day you go out and cross the Kidʹron Valley, you can be sure that you will die. Your blood will be on your own head.”

[[v11-2-38]]

^<<v11-2-38,38>>^ Shimʹe·i replied to the king: “What you have said is fair. Your servant will do just as my lord the king has said.” So Shimʹe·i stayed in Jerusalem for many days.

[[v11-2-39]]

^<<v11-2-39,39>>^ But at the end of three years, two of Shimʹe·i’s slaves ran away to Aʹchish the son of Maʹa·cah the king of Gath. When Shimʹe·i was told: “Look! Your slaves are in Gath,”

[[v11-2-40]]

^<<v11-2-40,40>>^ Shimʹe·i immediately saddled his donkey and went to see Aʹchish in Gath to find his slaves. When Shimʹe·i returned from Gath with his slaves,

[[v11-2-41]]

^<<v11-2-41,41>>^ Solʹo·mon was told: “Shimʹe·i has gone out of Jerusalem to Gath and has returned.”

[[v11-2-42]]

^<<v11-2-42,42>>^ At that the king summoned Shimʹe·i and said to him: “Did I not put you under oath by Jehovah and warn you: ‘On the day you go out from here to any other place, you can be sure that you will die’? And did you not say to me, ‘What you are saying is fair; I will obey’?

[[v11-2-43]]

^<<v11-2-43,43>>^ Why, then, did you not keep the oath of Jehovah and the commandment that I imposed on you?”

[[v11-2-44]]

^<<v11-2-44,44>>^ The king then said to Shimʹe·i: “You know in your heart all the injury that you did to David my father, and Jehovah will bring back that injury on your own head.

[[v11-2-45]]

^<<v11-2-45,45>>^ But King Solʹo·mon will be blessed, and the throne of David will be firmly established before Jehovah forever.”

[[v11-2-46]]

^<<v11-2-46,46>>^ With that the king commanded Be·naiʹah the son of Je·hoiʹa·da, who went out and struck him down, and he died.
Thus the kingdom was firmly established in the hand of Solʹo·mon.

'''

xref:011-1-kings/011-1-kings-001.adoc#v11-1-0[&#60; Capítulo Anterior] | <<v11-2-0,Topo>> | xref:011-1-kings/011-1-kings-003.adoc#v11-3-0[Próximo Capítulo &#62;]