include::./index.adoc[]

[[v11-11-0]]
=== The First of Kings, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-11-1]]

^<<v11-11-1,1>>^ But King Solʹo·mon loved many foreign women besides the daughter of Pharʹaoh: Moʹab·ite, Amʹmon·ite, Eʹdom·ite, Si·doʹni·an, and Hitʹtite women.

[[v11-11-2]]

^<<v11-11-2,2>>^ They were from the nations about whom Jehovah had said to the Israelites: “You must not go in among them,^&#42;1^ and they should not come in among you, for they will surely incline your heart to follow their gods.” But Solʹo·mon clung to them and loved them.

[NOTE]
====
. Or “You must not intermarry with them.”
====

[[v11-11-3]]

^<<v11-11-3,3>>^ And he had 700 wives who were princesses and 300 concubines, and his wives gradually inclined his heart.^&#42;1^

[NOTE]
====
. Or “his wives had a powerful influence over him.”
====

[[v11-11-4]]

^<<v11-11-4,4>>^ In Solʹo·mon’s old age, his wives inclined^&#42;1^ his heart to follow other gods, and his heart was not complete with^&#42;2^ Jehovah his God like the heart of David his father.

[NOTE]
====
. Or “turned away.”
. Or “completely devoted to.”
====

[[v11-11-5]]

^<<v11-11-5,5>>^ And Solʹo·mon followed after Ashʹto·reth, the goddess of the Si·doʹni·ans, and Milʹcom, the disgusting god of the Amʹmon·ites.

[[v11-11-6]]

^<<v11-11-6,6>>^ And Solʹo·mon did what was bad in the eyes of Jehovah, and he did not follow Jehovah completely^&#42;1^ as David his father had done.

[NOTE]
====
. Lit., “fully.”
====

[[v11-11-7]]

^<<v11-11-7,7>>^ It was then that Solʹo·mon built a high place to Cheʹmosh, the disgusting god of Moʹab, on the mountain in front of Jerusalem and to Moʹlech, the disgusting god of the Amʹmon·ites.

[[v11-11-8]]

^<<v11-11-8,8>>^ That was what he did for all his foreign wives who were making sacrificial smoke and sacrificing to their gods.

[[v11-11-9]]

^<<v11-11-9,9>>^ Jehovah became furious at Solʹo·mon, because his heart had inclined away from Jehovah the God of Israel, who had appeared to him twice

[[v11-11-10]]

^<<v11-11-10,10>>^ and had warned him about this very thing, that he should not go after other gods. But he did not obey what Jehovah had commanded.

[[v11-11-11]]

^<<v11-11-11,11>>^ Jehovah now said to Solʹo·mon: “Because you have done this and you have not kept my covenant and my statutes as I commanded you, I will surely rip the kingdom away from you, and I will give it to one of your servants.

[[v11-11-12]]

^<<v11-11-12,12>>^ However, for the sake of your father David, I will not do it in your lifetime. I will rip it out of the hand of your son,

[[v11-11-13]]

^<<v11-11-13,13>>^ but I will not rip away the entire kingdom. One tribe I will give to your son, for the sake of David my servant and for the sake of Jerusalem, which I have chosen.”

[[v11-11-14]]

^<<v11-11-14,14>>^ Jehovah then raised up a resister against Solʹo·mon, Haʹdad the Eʹdom·ite, of the royal family of Eʹdom.

[[v11-11-15]]

^<<v11-11-15,15>>^ When David defeated Eʹdom, Joʹab the chief of the army went up to bury the slain, and he tried to strike down every male in Eʹdom.

[[v11-11-16]]

^<<v11-11-16,16>>^ (For Joʹab and all Israel stayed there for six months until he had done away with^&#42;1^ every male in Eʹdom.)

[NOTE]
====
. Lit., “cut off.”
====

[[v11-11-17]]

^<<v11-11-17,17>>^ But Haʹdad fled with some of his father’s Eʹdom·ite servants, and they went to Egypt; Haʹdad was then a young boy.

[[v11-11-18]]

^<<v11-11-18,18>>^ So they set out from Midʹi·an and came to Paʹran. They took men with them from Paʹran and came to Egypt, to Pharʹaoh king of Egypt, who gave him a house, assigned him a food allowance, and gave him land.

[[v11-11-19]]

^<<v11-11-19,19>>^ Haʹdad found favor in the eyes of Pharʹaoh, so much so that he gave him in marriage the sister of his own wife, Tahʹpe·nes the queen.^&#42;1^

[NOTE]
====
. Not a ruling queen.
====

[[v11-11-20]]

^<<v11-11-20,20>>^ In time the sister of Tahʹpe·nes bore him a son, Ge·nuʹbath, and Tahʹpe·nes brought him up^&#42;1^ in the house of Pharʹaoh, and Ge·nuʹbath remained in the house of Pharʹaoh among the sons of Pharʹaoh.

[NOTE]
====
. Or possibly, “weaned him.”
====

[[v11-11-21]]

^<<v11-11-21,21>>^ Haʹdad heard in Egypt that David had been laid to rest with his forefathers and that Joʹab the chief of the army had died. So Haʹdad said to Pharʹaoh: “Send me away, so that I may go to my own land.”

[[v11-11-22]]

^<<v11-11-22,22>>^ But Pharʹaoh said to him: “What have you lacked with me that you now seek to go to your own land?” To this he said: “Nothing, but please send me away.”

[[v11-11-23]]

^<<v11-11-23,23>>^ God also raised up against Solʹo·mon another resister, Reʹzon the son of E·liʹa·da, who had fled from his lord, Had·ad·eʹzer the king of Zoʹbah.

[[v11-11-24]]

^<<v11-11-24,24>>^ He gathered men to himself and became chief of a marauder band when David defeated^&#42;1^ them. So they went to Damascus and settled there and began reigning in Damascus.

[NOTE]
====
. Lit., “killed.”
====

[[v11-11-25]]

^<<v11-11-25,25>>^ And he became a resister of Israel all the days of Solʹo·mon, adding to the harm done by Haʹdad, and he abhorred Israel while he reigned over Syria.

[[v11-11-26]]

^<<v11-11-26,26>>^ And there was Jer·o·boʹam the son of Neʹbat, an Eʹphra·im·ite from Zerʹe·dah, a servant of Solʹo·mon’s whose mother’s name was Ze·ruʹah, a widow. He too began to rebel^&#42;1^ against the king.

[NOTE]
====
. Lit., “lift his hand.”
====

[[v11-11-27]]

^<<v11-11-27,27>>^ This is why he rebelled against the king: Solʹo·mon had built the Mound^&#42;1^ and had closed up the gap of the City of David his father.

[NOTE]
====
. Or “Millo.” A Hebrew term meaning “fill.”
====

[[v11-11-28]]

^<<v11-11-28,28>>^ Now this Jer·o·boʹam was a capable man. When Solʹo·mon saw that the young man was a hard worker, he made him overseer over all the compulsory service of the house of Joseph.

[[v11-11-29]]

^<<v11-11-29,29>>^ During that time Jer·o·boʹam went out from Jerusalem, and the prophet A·hiʹjah the Shiʹlo·nite found him on the road. A·hiʹjah was wearing a new garment, and the two of them were by themselves in the field.

[[v11-11-30]]

^<<v11-11-30,30>>^ A·hiʹjah took hold of the new garment he was wearing and ripped it into 12 pieces.

[[v11-11-31]]

^<<v11-11-31,31>>^ Then he said to Jer·o·boʹam:
“Take ten pieces for yourself, for this is what Jehovah the God of Israel says: ‘Here I am ripping the kingdom out of the hand of Solʹo·mon, and I will give you ten tribes.

[[v11-11-32]]

^<<v11-11-32,32>>^ But one tribe will remain his for the sake of my servant David and for the sake of Jerusalem, the city I have chosen out of all the tribes of Israel.

[[v11-11-33]]

^<<v11-11-33,33>>^ I will do this because they have left me and are bowing down to Ashʹto·reth the goddess of the Si·doʹni·ans, to Cheʹmosh the god of Moʹab, and to Milʹcom the god of the Amʹmon·ites, and they have not walked in my ways by doing what is right in my eyes and observing my statutes and my judgments as his father David did.

[[v11-11-34]]

^<<v11-11-34,34>>^ But I will not take the entire kingdom out of his hand, and I will keep him as a chieftain for all the days of his life, for the sake of David my servant whom I chose, because he obeyed my commandments and my statutes.

[[v11-11-35]]

^<<v11-11-35,35>>^ But I will take the kingship out of the hand of his son and give it to you, that is, ten tribes.

[[v11-11-36]]

^<<v11-11-36,36>>^ To his son I will give one tribe, so that David my servant may always have a lamp before me in Jerusalem, the city that I have chosen for myself as the place to put my name.

[[v11-11-37]]

^<<v11-11-37,37>>^ I will take you, and you will reign over all that you desire,^&#42;1^ and you will become king over Israel.

[NOTE]
====
. Or “your soul desires.”
====

[[v11-11-38]]

^<<v11-11-38,38>>^ And if you obey all that I command you and walk in my ways and do what is right in my eyes by obeying my statutes and my commandments, just as David my servant did, I will also be with you. I will build you a lasting house, just as I have built for David, and I will give you Israel.

[[v11-11-39]]

^<<v11-11-39,39>>^ And I will humiliate the offspring of David because of this, but not always.’”

[[v11-11-40]]

^<<v11-11-40,40>>^ So Solʹo·mon tried to put Jer·o·boʹam to death, but Jer·o·boʹam fled to Egypt, to Shiʹshak the king of Egypt, and he remained in Egypt until Solʹo·mon’s death.

[[v11-11-41]]

^<<v11-11-41,41>>^ As for the rest of the history of Solʹo·mon, all that he did and his wisdom, is it not written in the book of the history of Solʹo·mon?

[[v11-11-42]]

^<<v11-11-42,42>>^ The length^&#42;1^ of Solʹo·mon’s reign in Jerusalem over all Israel was 40 years.

[NOTE]
====
. Lit., “The days.”
====

[[v11-11-43]]

^<<v11-11-43,43>>^ Then Solʹo·mon was laid to rest with his forefathers and was buried in the City of David his father; and his son Re·ho·boʹam became king in his place.

'''

xref:011-1-kings/011-1-kings-010.adoc#v11-10-0[&#60; Capítulo Anterior] | <<v11-11-0,Topo>> | xref:011-1-kings/011-1-kings-012.adoc#v11-12-0[Próximo Capítulo &#62;]