include::./index.adoc[]

[[v11-4-0]]
=== The First of Kings, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-4-1]]

^<<v11-4-1,1>>^ King Solʹo·mon ruled over all Israel.

[[v11-4-2]]

^<<v11-4-2,2>>^ These were his high officials:^&#42;1^ Az·a·riʹah the son of Zaʹdok was the priest;

[NOTE]
====
. Or “his princes.”
====

[[v11-4-3]]

^<<v11-4-3,3>>^ El·i·horʹeph and A·hiʹjah the sons of Shiʹsha were secretaries; Je·hoshʹa·phat the son of A·hiʹlud was the recorder;

[[v11-4-4]]

^<<v11-4-4,4>>^ Be·naiʹah the son of Je·hoiʹa·da was in charge of the army; Zaʹdok and A·biʹa·thar were priests;

[[v11-4-5]]

^<<v11-4-5,5>>^ Az·a·riʹah the son of Nathan was over the deputies; Zaʹbud the son of Nathan was a priest and the king’s friend;

[[v11-4-6]]

^<<v11-4-6,6>>^ A·hiʹshar was over the household; and Ad·o·niʹram the son of Abʹda was over those conscripted for forced labor.

[[v11-4-7]]

^<<v11-4-7,7>>^ Solʹo·mon had 12 deputies in charge of all Israel who provided the king and his household with food. Each one was responsible for providing the food for one month of the year.

[[v11-4-8]]

^<<v11-4-8,8>>^ These were their names: The son of Hur, in the mountainous region of Eʹphra·im;

[[v11-4-9]]

^<<v11-4-9,9>>^ the son of Deʹker, in Maʹkaz, Sha·alʹbim, Beth-sheʹmesh, and Eʹlon-beth-haʹnan;

[[v11-4-10]]

^<<v11-4-10,10>>^ the son of Heʹsed, in A·rubʹboth (he had Soʹcoh and all the land of Heʹpher);

[[v11-4-11]]

^<<v11-4-11,11>>^ the son of A·binʹa·dab, in all the slopes of Dor (Solʹo·mon’s daughter Taʹphath became his wife);

[[v11-4-12]]

^<<v11-4-12,12>>^ Baʹa·na the son of A·hiʹlud, in Taʹa·nach, Me·gidʹdo, and all Beth-sheʹan, which is beside Zarʹe·than below Jezʹre·el, from Beth-sheʹan to Aʹbel-me·hoʹlah to the region of Jokʹme·am;

[[v11-4-13]]

^<<v11-4-13,13>>^ the son of Geʹber, in Raʹmoth-gilʹe·ad (he had the tent villages of Jaʹir the son of Ma·nasʹseh, which are in Gilʹe·ad; he also had the region of Arʹgob, which is in Baʹshan: 60 large cities with walls and copper bars);

[[v11-4-14]]

^<<v11-4-14,14>>^ A·hinʹa·dab the son of Idʹdo, in Ma·ha·naʹim;

[[v11-4-15]]

^<<v11-4-15,15>>^ A·himʹa·az, in Naphʹta·li (he took Basʹe·math, another of Solʹo·mon’s daughters, as his wife);

[[v11-4-16]]

^<<v11-4-16,16>>^ Baʹa·na the son of Huʹshai, in Ashʹer and Be·aʹloth;

[[v11-4-17]]

^<<v11-4-17,17>>^ Je·hoshʹa·phat the son of Pa·ruʹah, in Isʹsa·char;

[[v11-4-18]]

^<<v11-4-18,18>>^ Shimʹe·i the son of Eʹla, in Benjamin;

[[v11-4-19]]

^<<v11-4-19,19>>^ Geʹber the son of Uʹri, in the land of Gilʹe·ad, the land of Siʹhon king of the Amʹor·ites and of Og king of Baʹshan. There was also one deputy in charge of all these other deputies in the land.

[[v11-4-20]]

^<<v11-4-20,20>>^ Judah and Israel were as numerous as the grains of sand by the sea; they were eating and drinking and rejoicing.

[[v11-4-21]]

^<<v11-4-21,21>>^ Solʹo·mon ruled over all the kingdoms from the River^&#42;1^ to the land of the Phi·lisʹtines and to the boundary of Egypt. They brought tribute and served Solʹo·mon all the days of his life.

[NOTE]
====
. That is, the Euphrates.
====

[[v11-4-22]]

^<<v11-4-22,22>>^ Solʹo·mon’s food for each day was 30 cor measures^&#42;1^ of fine flour and 60 cor measures of flour,

[NOTE]
====
. A cor equaled 220 L (200 dry qt). See App. B14.
====

[[v11-4-23]]

^<<v11-4-23,23>>^ 10 fattened cattle, 20 pastured cattle, and 100 sheep, besides some stags, gazelles, roebucks, and fattened cuckoos.

[[v11-4-24]]

^<<v11-4-24,24>>^ For he controlled everything this side of the River,^&#42;1^ from Tiphʹsah to Gazʹa, including all the kings on this side of the River; and he enjoyed peace in every region, all around him.

[NOTE]
====
. That is, west of the Euphrates.
====

[[v11-4-25]]

^<<v11-4-25,25>>^ Judah and Israel lived in security, everyone under his own vine and under his own fig tree, from Dan to Beʹer-sheʹba, all the days of Solʹo·mon.

[[v11-4-26]]

^<<v11-4-26,26>>^ And Solʹo·mon had 4,000^&#42;1^ stalls of horses for his chariots and 12,000 horses.^&#42;2^

[NOTE]
====
. This figure is found in some manuscripts and in the parallel account. Other manuscripts say 40,000.
. Or “horsemen.”
====

[[v11-4-27]]

^<<v11-4-27,27>>^ These deputies supplied food to King Solʹo·mon and to everyone who ate at the table of King Solʹo·mon. Each was responsible for his month and saw to it that nothing was lacking.

[[v11-4-28]]

^<<v11-4-28,28>>^ They also brought barley and straw wherever it was needed for the horses and for the teams of horses, each according to his quota.

[[v11-4-29]]

^<<v11-4-29,29>>^ And God gave Solʹo·mon wisdom and discernment in very great measure and a broadness of heart^&#42;1^ like the sand on the seashore.

[NOTE]
====
. Or “heart with understanding.”
====

[[v11-4-30]]

^<<v11-4-30,30>>^ Solʹo·mon’s wisdom surpassed the wisdom of all the people of the East and all the wisdom of Egypt.

[[v11-4-31]]

^<<v11-4-31,31>>^ He was wiser than any other man, wiser than Eʹthan the Ezʹra·hite and Heʹman, Calʹcol, and Darʹda, the sons of Maʹhol; his fame spread among all the surrounding nations.

[[v11-4-32]]

^<<v11-4-32,32>>^ He composed^&#42;1^ 3,000 proverbs and his songs numbered 1,005.

[NOTE]
====
. Or “spoke.”
====

[[v11-4-33]]

^<<v11-4-33,33>>^ He would speak about the trees, from the cedar in Lebʹa·non to the hyssop that grows on the wall; he would speak about the animals, the birds,^&#42;1^ the creeping things,^&#42;2^ and the fish.

[NOTE]
====
. Or “flying creatures.”
. Possibly including reptiles and insects.
====

[[v11-4-34]]

^<<v11-4-34,34>>^ People from all the nations came to hear Solʹo·mon’s wisdom, including kings from all over the earth who had heard about his wisdom.

'''

xref:011-1-kings/011-1-kings-003.adoc#v11-3-0[&#60; Capítulo Anterior] | <<v11-4-0,Topo>> | xref:011-1-kings/011-1-kings-005.adoc#v11-5-0[Próximo Capítulo &#62;]