include::./index.adoc[]

[[v11-16-0]]
=== The First of Kings, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-16-1]]

^<<v11-16-1,1>>^ The word of Jehovah against Baʹa·sha then came to Jeʹhu the son of Ha·naʹni, saying:

[[v11-16-2]]

^<<v11-16-2,2>>^ “I raised you up out of the dust and made you leader over my people Israel, but you kept walking in the way of Jer·o·boʹam and caused my people Israel to sin so that they offended me with their sins.

[[v11-16-3]]

^<<v11-16-3,3>>^ So I am making a clean sweep of Baʹa·sha and his house, and I will make his house like the house of Jer·o·boʹam the son of Neʹbat.

[[v11-16-4]]

^<<v11-16-4,4>>^ Anyone belonging to Baʹa·sha who dies in the city the dogs will eat; and anyone belonging to him who dies in the field the birds of the heavens will eat.”

[[v11-16-5]]

^<<v11-16-5,5>>^ As for the rest of the history of Baʹa·sha, what he did and his mightiness, is it not written in the book of the history of the times of the kings of Israel?

[[v11-16-6]]

^<<v11-16-6,6>>^ Then Baʹa·sha was laid to rest with his forefathers and was buried in Tirʹzah; and Eʹlah his son became king in his place.

[[v11-16-7]]

^<<v11-16-7,7>>^ Also through the prophet Jeʹhu the son of Ha·naʹni, Jehovah’s word came against Baʹa·sha and his house, both because of all the badness that he committed in the eyes of Jehovah by offending him with the work of his hands, becoming like the house of Jer·o·boʹam, and also because of his striking him^&#42;1^ down.

[NOTE]
====
. That is, Nadab, the son of Jeroboam.
====

[[v11-16-8]]

^<<v11-16-8,8>>^ In the 26th year of King Aʹsa of Judah, Eʹlah the son of Baʹa·sha became king over Israel in Tirʹzah, and he reigned for two years.

[[v11-16-9]]

^<<v11-16-9,9>>^ His servant Zimʹri, the chief of half of his chariot forces, conspired against him while he was in Tirʹzah drinking himself drunk at the house of Arʹza, who was over the household in Tirʹzah.

[[v11-16-10]]

^<<v11-16-10,10>>^ Zimʹri came in and struck him down and put him to death in the 27th year of King Aʹsa of Judah, and he became king in his place.

[[v11-16-11]]

^<<v11-16-11,11>>^ When he became king, as soon as he sat down on his throne, he struck down all the house of Baʹa·sha. He did not spare a single male,^&#42;1^ whether of his relatives^&#42;2^ or of his friends.

[NOTE]
====
. Lit., “anyone urinating against a wall.” A Hebrew expression of contempt referring to males.
. Or “his avengers of blood.”
====

[[v11-16-12]]

^<<v11-16-12,12>>^ Thus Zimʹri annihilated the whole house of Baʹa·sha, according to the word that Jehovah had spoken against Baʹa·sha through Jeʹhu the prophet.

[[v11-16-13]]

^<<v11-16-13,13>>^ This was for all the sins that Baʹa·sha and his son Eʹlah had committed and the sins they had caused Israel to commit by offending Jehovah the God of Israel with their worthless idols.

[[v11-16-14]]

^<<v11-16-14,14>>^ As for the rest of the history of Eʹlah, all that he did, is it not written in the book of the history of the times of the kings of Israel?

[[v11-16-15]]

^<<v11-16-15,15>>^ In the 27th year of King Aʹsa of Judah, Zimʹri became king for seven days in Tirʹzah while the troops were camped against Gibʹbe·thon, which belonged to the Phi·lisʹtines.

[[v11-16-16]]

^<<v11-16-16,16>>^ In time the troops who were encamped heard it being said: “Zimʹri has conspired and has also struck down the king.” So all Israel made Omʹri, the chief of the army, king over Israel on that day in the camp.

[[v11-16-17]]

^<<v11-16-17,17>>^ Omʹri and all Israel with him went up from Gibʹbe·thon and laid siege to Tirʹzah.

[[v11-16-18]]

^<<v11-16-18,18>>^ When Zimʹri saw that the city had been captured, he went into the fortified tower of the king’s house^&#42;1^ and burned the house down over himself, and he died.

[NOTE]
====
. Or “palace.”
====

[[v11-16-19]]

^<<v11-16-19,19>>^ This was for his own sins that he had committed by doing what was bad in the eyes of Jehovah by walking in the way of Jer·o·boʹam and for the sin he had caused Israel to commit.

[[v11-16-20]]

^<<v11-16-20,20>>^ As for the rest of the history of Zimʹri and his conspiracy, is it not written in the book of the history of the times of the kings of Israel?

[[v11-16-21]]

^<<v11-16-21,21>>^ It was then that the people of Israel were divided into two factions. One part of the people became followers of Tibʹni the son of Giʹnath, wanting to make him king, and the other part followed Omʹri.

[[v11-16-22]]

^<<v11-16-22,22>>^ But the people who were following Omʹri prevailed over the people following Tibʹni the son of Giʹnath. So Tibʹni died, and Omʹri became king.

[[v11-16-23]]

^<<v11-16-23,23>>^ In the 31st year of King Aʹsa of Judah, Omʹri became king over Israel, and he reigned for 12 years. In Tirʹzah he reigned for six years.

[[v11-16-24]]

^<<v11-16-24,24>>^ He bought the mountain of Sa·marʹi·a from Sheʹmer for two talents^&#42;1^ of silver, and he built a city on the mountain. He named the city that he built Sa·marʹi·a,^&#42;2^ after Sheʹmer the owner^&#42;3^ of the mountain.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
. Meaning “Belonging to the Clan Shemer.”
. Lit., “lord.”
====

[[v11-16-25]]

^<<v11-16-25,25>>^ Omʹri kept doing what was bad in the eyes of Jehovah, and he was worse than all who were prior to him.

[[v11-16-26]]

^<<v11-16-26,26>>^ He walked in all the ways of Jer·o·boʹam the son of Neʹbat and in the sin he had caused Israel to commit by offending Jehovah the God of Israel with their worthless idols.

[[v11-16-27]]

^<<v11-16-27,27>>^ As for the rest of the history of Omʹri, what he did and his mighty exploits, is it not written in the book of the history of the times of the kings of Israel?

[[v11-16-28]]

^<<v11-16-28,28>>^ Then Omʹri was laid to rest with his forefathers and was buried in Sa·marʹi·a; and his son Aʹhab became king in his place.

[[v11-16-29]]

^<<v11-16-29,29>>^ Aʹhab the son of Omʹri became king over Israel in the 38th year of King Aʹsa of Judah, and Aʹhab the son of Omʹri reigned over Israel in Sa·marʹi·a for 22 years.

[[v11-16-30]]

^<<v11-16-30,30>>^ Aʹhab the son of Omʹri was worse in the eyes of Jehovah than all those who were prior to him.

[[v11-16-31]]

^<<v11-16-31,31>>^ As if it were a trivial thing for him to walk in the sins of Jer·o·boʹam the son of Neʹbat, he also took as wife Jezʹe·bel the daughter of Eth·baʹal, the king of the Si·doʹni·ans, and began to serve Baʹal and to bow down to him.

[[v11-16-32]]

^<<v11-16-32,32>>^ Further, he set up an altar to Baʹal at the house^&#42;1^ of Baʹal that he built in Sa·marʹi·a.

[NOTE]
====
. Or “temple.”
====

[[v11-16-33]]

^<<v11-16-33,33>>^ Aʹhab also made the sacred pole.^&#42;1^ Aʹhab did more to offend Jehovah the God of Israel than all the kings of Israel prior to him.

[NOTE]
====
. See Glossary.
====

[[v11-16-34]]

^<<v11-16-34,34>>^ In his days, Hiʹel the Bethʹel·ite rebuilt Jerʹi·cho. At the cost of A·biʹram his firstborn he laid its foundation, and at the cost of Seʹgub his youngest he put up its doors, according to the word of Jehovah spoken through Joshua the son of Nun.

'''

xref:011-1-kings/011-1-kings-015.adoc#v11-15-0[&#60; Capítulo Anterior] | <<v11-16-0,Topo>> | xref:011-1-kings/011-1-kings-017.adoc#v11-17-0[Próximo Capítulo &#62;]