include::./index.adoc[]

[[v11-8-0]]
=== The First of Kings, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-8-1]]

^<<v11-8-1,1>>^ At that time Solʹo·mon congregated the elders of Israel, all the heads of the tribes, the chieftains of the paternal houses of Israel. They came to King Solʹo·mon at Jerusalem to bring up the ark of the covenant of Jehovah from the City of David, that is, Zion.

[[v11-8-2]]

^<<v11-8-2,2>>^ All the men of Israel assembled before King Solʹo·mon at the festival^&#42;1^ in the month of Ethʹa·nim,^&#42;2^ that is, the seventh month.

[NOTE]
====
. That is, the Festival of Booths.
. See App. B15.
====

[[v11-8-3]]

^<<v11-8-3,3>>^ So all the elders of Israel came, and the priests lifted up the Ark.

[[v11-8-4]]

^<<v11-8-4,4>>^ They brought up the Ark of Jehovah, the tent of meeting, and all the holy utensils that were in the tent. The priests and the Levites brought them up.

[[v11-8-5]]

^<<v11-8-5,5>>^ King Solʹo·mon and the entire assembly of Israel, who had been summoned to meet with him, were before the Ark. So many sheep and cattle were being sacrificed that they could not be counted or numbered.

[[v11-8-6]]

^<<v11-8-6,6>>^ Then the priests brought the ark of the covenant of Jehovah to its place, into the innermost room of the house, the Most Holy, underneath the wings of the cherubs.

[[v11-8-7]]

^<<v11-8-7,7>>^ Thus the wings of the cherubs were spread out over the place of the Ark, so that the cherubs overshadowed the Ark and its poles.

[[v11-8-8]]

^<<v11-8-8,8>>^ The poles were so long that the tips of the poles were visible from the Holy in front of the innermost room, but they were not visible from outside. And they are there to this day.

[[v11-8-9]]

^<<v11-8-9,9>>^ There was nothing in the Ark but the two stone tablets that Moses placed there at Horʹeb, when Jehovah made a covenant with the people of Israel while they were coming out of the land of Egypt.

[[v11-8-10]]

^<<v11-8-10,10>>^ When the priests came out from the holy place, the cloud filled the house of Jehovah.

[[v11-8-11]]

^<<v11-8-11,11>>^ The priests were not able to stand to minister because of the cloud, for the glory of Jehovah filled the house of Jehovah.

[[v11-8-12]]

^<<v11-8-12,12>>^ At that time Solʹo·mon said: “Jehovah said he would reside in the thick gloom.

[[v11-8-13]]

^<<v11-8-13,13>>^ I have successfully built a lofty house for you, an established place for you to dwell in forever.”

[[v11-8-14]]

^<<v11-8-14,14>>^ Then the king turned around and began to bless all the congregation of Israel while all the congregation of Israel stood.

[[v11-8-15]]

^<<v11-8-15,15>>^ He said: “May Jehovah the God of Israel be praised, the one who by his own mouth promised my father David, and by his own hand has given fulfillment, saying,

[[v11-8-16]]

^<<v11-8-16,16>>^ ‘From the day I brought my people Israel out of Egypt, I have not chosen a city out of all the tribes of Israel in which to build a house for my name to remain there, but I have chosen David to be over my people Israel.’

[[v11-8-17]]

^<<v11-8-17,17>>^ And it was the heart’s desire of my father David to build a house for the name of Jehovah the God of Israel.

[[v11-8-18]]

^<<v11-8-18,18>>^ But Jehovah said to my father David, ‘It was your heart’s desire to build a house for my name, and you did well to desire this in your heart.

[[v11-8-19]]

^<<v11-8-19,19>>^ However, you will not build the house, but your own son who is to be born to you^&#42;1^ is the one who will build the house for my name.’

[NOTE]
====
. Lit., “your son, the one coming out of your loins.”
====

[[v11-8-20]]

^<<v11-8-20,20>>^ Jehovah has carried out the promise that he made, for I have succeeded my father David and I sit on the throne of Israel, just as Jehovah promised. I have also built the house for the name of Jehovah the God of Israel

[[v11-8-21]]

^<<v11-8-21,21>>^ and have set up a place there for the Ark containing the covenant that Jehovah made with our forefathers when he was bringing them out of the land of Egypt.”

[[v11-8-22]]

^<<v11-8-22,22>>^ Then Solʹo·mon stood before the altar of Jehovah in front of all the congregation of Israel, and he spread his hands out to the heavens,

[[v11-8-23]]

^<<v11-8-23,23>>^ and he said: “O Jehovah the God of Israel, there is no God like you in the heavens above or on the earth beneath, keeping the covenant and showing loyal love to your servants who are walking before you with all their heart.

[[v11-8-24]]

^<<v11-8-24,24>>^ You have kept the promise that you made to your servant David my father. You made the promise with your own mouth, and this day you have fulfilled it with your own hand.

[[v11-8-25]]

^<<v11-8-25,25>>^ And now, O Jehovah the God of Israel, keep the promise you made to your servant David my father when you said: ‘There will never fail to be a man of your line before me to sit on the throne of Israel, if only your sons will pay attention to their way by walking before me, just as you have walked before me.’

[[v11-8-26]]

^<<v11-8-26,26>>^ And now, O God of Israel, let the promise that you made to your servant David my father prove trustworthy, please.

[[v11-8-27]]

^<<v11-8-27,27>>^ “But will God really dwell on the earth? Look! The heavens, yes, the heaven of the heavens, cannot contain you; how much less, then, this house that I have built!

[[v11-8-28]]

^<<v11-8-28,28>>^ Now pay attention to the prayer of your servant and to his request for favor, O Jehovah my God, and listen to the cry for help and to the prayer that your servant is praying before you today.

[[v11-8-29]]

^<<v11-8-29,29>>^ May your eyes be open toward this house night and day, toward the place of which you said, ‘My name will be there,’ to listen to the prayer that your servant prays toward this place.

[[v11-8-30]]

^<<v11-8-30,30>>^ And listen to your servant’s request for favor and to the request by your people Israel that they pray toward this place, and may you hear from your dwelling place in the heavens; yes, may you hear and forgive.

[[v11-8-31]]

^<<v11-8-31,31>>^ “When a man sins against his fellow man and is made to take an oath^&#42;1^ and is brought under liability to the oath,^&#42;2^ and while under the oath^&#42;3^ he comes before your altar in this house,

[NOTE]
====
. Or “and the latter lays a cursing on him.” That is, an oath that carried with it a curse as its penalty if sworn falsely or violated.
. Lit., “curse.”
. Lit., “curse.”
====

[[v11-8-32]]

^<<v11-8-32,32>>^ may you then hear from the heavens and act and judge your servants by pronouncing the wicked one guilty^&#42;1^ and bringing what he did on his own head, and by pronouncing the righteous one innocent^&#42;2^ and rewarding him according to his own righteousness.

[NOTE]
====
. Lit., “wicked.”
. Lit., “righteous.”
====

[[v11-8-33]]

^<<v11-8-33,33>>^ “When your people Israel are defeated by an enemy because they kept sinning against you, and they return to you and glorify your name and pray and beg you for favor in this house,

[[v11-8-34]]

^<<v11-8-34,34>>^ may you then hear from the heavens and forgive the sin of your people Israel and bring them back to the land that you gave to their forefathers.

[[v11-8-35]]

^<<v11-8-35,35>>^ “When the heavens are shut up and there is no rain because they kept sinning against you, and they pray toward this place and glorify your name and turn back from their sin because you humbled^&#42;1^ them,

[NOTE]
====
. Or “afflicted.”
====

[[v11-8-36]]

^<<v11-8-36,36>>^ may you then hear from the heavens and forgive the sin of your servants, of your people Israel, for you will instruct them about the good way in which they should walk; and bring rain on your land that you gave to your people as an inheritance.

[[v11-8-37]]

^<<v11-8-37,37>>^ “If a famine occurs in the land, or a pestilence, a scorching blight, mildew, swarming locusts, or voracious locusts;^&#42;1^ or if their enemy besieges them in any of the cities of the land^&#42;2^ or if any other sort of plague or disease occurs,

[NOTE]
====
. Or “grasshoppers.”
. Lit., “in the land of his gates.”
====

[[v11-8-38]]

^<<v11-8-38,38>>^ whatever prayer, whatever request for favor may be made by any man or by all your people Israel (for each one knows the plague of his own heart) when they spread out their hands toward this house,

[[v11-8-39]]

^<<v11-8-39,39>>^ then may you hear from the heavens, your dwelling place, and may you forgive and take action; and reward each one according to all his ways, for you know his heart (you alone truly know every human heart),

[[v11-8-40]]

^<<v11-8-40,40>>^ so that they may fear you all the days they live on the land that you gave to our forefathers.

[[v11-8-41]]

^<<v11-8-41,41>>^ “Also concerning the foreigner who is not part of your people Israel and who comes from a distant land because of your name^&#42;1^

[NOTE]
====
. Or “reputation.”
====

[[v11-8-42]]

^<<v11-8-42,42>>^ (for they will hear about your great name and your mighty hand and your outstretched arm), and he comes and prays toward this house,

[[v11-8-43]]

^<<v11-8-43,43>>^ may you then listen from the heavens, your dwelling place, and do all that the foreigner asks of you, so that all the peoples of the earth may know your name and fear you, as your people Israel do, and may know that your name has been called on this house that I have built.

[[v11-8-44]]

^<<v11-8-44,44>>^ “If your people go to war against their enemy in the way that you send them, and they pray to Jehovah in the direction of the city that you have chosen and toward the house that I have built for your name,

[[v11-8-45]]

^<<v11-8-45,45>>^ then hear from the heavens their prayer and their request for favor and execute judgment for them.

[[v11-8-46]]

^<<v11-8-46,46>>^ “If they sin against you (for there is no man who does not sin), and you are furious with them and you abandon them to an enemy, and their captors carry them off captive to the land of the enemy, far or near;

[[v11-8-47]]

^<<v11-8-47,47>>^ and they come to their senses in the land where they were carried off captive, and they return to you and beg you for favor in the land of their captors, saying, ‘We have sinned and done wrong; we have acted wickedly,’

[[v11-8-48]]

^<<v11-8-48,48>>^ and they return to you with all their heart and all their soul^&#42;1^ in the land of their enemies who carried them off captive, and they pray to you in the direction of their land that you gave to their forefathers and of the city that you have chosen and the house that I have built for your name,

[NOTE]
====
. See Glossary.
====

[[v11-8-49]]

^<<v11-8-49,49>>^ then hear from the heavens, your dwelling place, their prayer and their request for favor, and execute judgment for them

[[v11-8-50]]

^<<v11-8-50,50>>^ and forgive your people who have sinned against you, forgiving all their transgressions they committed against you. You will make them objects of pity before their captors, and they will pity them

[[v11-8-51]]

^<<v11-8-51,51>>^ (for they are your people and your inheritance, whom you brought out of Egypt, from inside the iron-smelting furnace).

[[v11-8-52]]

^<<v11-8-52,52>>^ May your eyes be opened to your servant’s request for favor and to the request for favor by your people Israel by listening whenever they call to you.^&#42;1^

[NOTE]
====
. Or “listening to them whatever they ask of you.”
====

[[v11-8-53]]

^<<v11-8-53,53>>^ For you set them apart as your inheritance out of all the peoples of the earth, just as you declared through Moses your servant when you were bringing our forefathers out of Egypt, O Sovereign Lord Jehovah.”

[[v11-8-54]]

^<<v11-8-54,54>>^ And as soon as Solʹo·mon finished offering to Jehovah this entire prayer and request for favor, he rose up from before the altar of Jehovah, where he had been kneeling with his hands spread out to the heavens.

[[v11-8-55]]

^<<v11-8-55,55>>^ He then stood and blessed all the congregation of Israel with a loud voice, saying:

[[v11-8-56]]

^<<v11-8-56,56>>^ “Praised be Jehovah, who has given a resting-place to his people Israel, just as he promised. Not one word of all his good promise that he made through Moses his servant has failed.

[[v11-8-57]]

^<<v11-8-57,57>>^ May Jehovah our God be with us just as he was with our forefathers. May he not abandon us nor forsake us.

[[v11-8-58]]

^<<v11-8-58,58>>^ May he draw our heart toward himself, to walk in all his ways and to keep his commandments, his regulations, and his judgments, which he commanded our forefathers to observe.

[[v11-8-59]]

^<<v11-8-59,59>>^ And may these words of mine with which I have begged Jehovah for favor be near to Jehovah our God by day and night, that he may execute judgment for his servant and for his people Israel as each day requires,

[[v11-8-60]]

^<<v11-8-60,60>>^ so that all the peoples of the earth may know that Jehovah is the true God. There is no other!

[[v11-8-61]]

^<<v11-8-61,61>>^ So let your heart be complete with^&#42;1^ Jehovah our God by walking in his regulations and by keeping his commandments as on this day.”

[NOTE]
====
. Or “completely devoted to.”
====

[[v11-8-62]]

^<<v11-8-62,62>>^ Now the king and all Israel with him offered a grand sacrifice before Jehovah.

[[v11-8-63]]

^<<v11-8-63,63>>^ Solʹo·mon offered the communion sacrifices to Jehovah: He offered 22,000 cattle and 120,000 sheep. Thus the king and all the Israelites inaugurated the house of Jehovah.

[[v11-8-64]]

^<<v11-8-64,64>>^ On that day the king had to sanctify the middle of the courtyard that is before the house of Jehovah, for there he had to offer up the burnt sacrifices, the grain offerings, and the fat pieces of the communion sacrifices, because the copper altar that is before Jehovah was too small to contain the burnt sacrifices, the grain offerings, and the fat pieces of the communion sacrifices.

[[v11-8-65]]

^<<v11-8-65,65>>^ At that time Solʹo·mon held the festival together with all Israel, a great congregation from Leʹbo-haʹmath^&#42;1^ down to the Wadi^&#42;2^ of Egypt, before Jehovah our God for 7 days and then another 7 days, 14 days in all.

[NOTE]
====
. Or “the entrance of Hamath.”
. See Glossary.
====

[[v11-8-66]]

^<<v11-8-66,66>>^ On the following^&#42;1^ day, he sent the people away, and they blessed the king and went to their homes rejoicing and feeling glad of heart over all the goodness that Jehovah had shown to David his servant and Israel his people.

[NOTE]
====
. Lit., “eighth,” that is, the day after the second seven-day period.
====

'''

xref:011-1-kings/011-1-kings-007.adoc#v11-7-0[&#60; Capítulo Anterior] | <<v11-8-0,Topo>> | xref:011-1-kings/011-1-kings-009.adoc#v11-9-0[Próximo Capítulo &#62;]