include::./index.adoc[]

[[v11-20-0]]
=== The First of Kings, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-20-1]]

^<<v11-20-1,1>>^ Now King Ben-haʹdad of Syria gathered his whole army together along with 32 other kings and their horses and chariots; he went up and laid siege to Sa·marʹi·a and fought against it.

[[v11-20-2]]

^<<v11-20-2,2>>^ Then he sent messengers to King Aʹhab of Israel at the city and said to him: “This is what Ben-haʹdad says,

[[v11-20-3]]

^<<v11-20-3,3>>^ ‘Your silver and your gold are mine, as well as the best of your wives and your sons.’”

[[v11-20-4]]

^<<v11-20-4,4>>^ To this the king of Israel answered: “According to your word, my lord the king, I am yours along with all that belongs to me.”

[[v11-20-5]]

^<<v11-20-5,5>>^ The messengers later came back and said: “This is what Ben-haʹdad says, ‘I sent this message to you: “Your silver, your gold, your wives, and your sons you will give me.”

[[v11-20-6]]

^<<v11-20-6,6>>^ But about this time tomorrow I will send my servants to you, and they will carefully search your house and the houses of your servants, and all your desirable things they will seize and take away.’”

[[v11-20-7]]

^<<v11-20-7,7>>^ At that the king of Israel called all the elders of the land and said: “Take note, please, and see that this man is bent on bringing calamity, for he demanded my wives, my sons, my silver, and my gold, and I did not refuse him.”

[[v11-20-8]]

^<<v11-20-8,8>>^ Then all the elders and all the people said to him: “Do not obey, and do not consent.”

[[v11-20-9]]

^<<v11-20-9,9>>^ So he said to the messengers of Ben-haʹdad: “Say to my lord the king, ‘All that you first demanded of your servant I will do, but this I cannot do.’” With that the messengers went off and brought word back to him.

[[v11-20-10]]

^<<v11-20-10,10>>^ Ben-haʹdad now sent him this message: “So may the gods do to me and add to it if there is enough dust in Sa·marʹi·a to give each of the people following me a handful!”

[[v11-20-11]]

^<<v11-20-11,11>>^ The king of Israel answered: “Tell him, ‘The one who puts on his armor should not boast about himself like one who takes it off.’”

[[v11-20-12]]

^<<v11-20-12,12>>^ As soon as he heard this reply, while he and the kings were drinking in their tents,^&#42;1^ he said to his servants: “Get ready to attack!” So they got ready to attack the city.

[NOTE]
====
. Or “booths.”
====

[[v11-20-13]]

^<<v11-20-13,13>>^ But a prophet approached King Aʹhab of Israel and said: “This is what Jehovah says, ‘Have you seen all this large crowd? Here I am giving it into your hand today, and then you will know that I am Jehovah.’”

[[v11-20-14]]

^<<v11-20-14,14>>^ Aʹhab asked: “By whom?” to which he said: “This is what Jehovah says, ‘By the attendants of the princes of the provinces.’”^&#42;1^ So he asked: “Who will start the battle?” to which he said: “You!”

[NOTE]
====
. Or “the jurisdictional districts.”
====

[[v11-20-15]]

^<<v11-20-15,15>>^ Aʹhab then counted the attendants of the princes of the provinces, and they were 232; after that, he counted all the Israelite men, 7,000.

[[v11-20-16]]

^<<v11-20-16,16>>^ They went out at noon while Ben-haʹdad was drinking himself drunk in the tents^&#42;1^ along with the 32 kings who were helping him.

[NOTE]
====
. Or “booths.”
====

[[v11-20-17]]

^<<v11-20-17,17>>^ When the attendants of the princes of the provinces came out first, Ben-haʹdad at once sent messengers. They reported to him: “Men have come out from Sa·marʹi·a.”

[[v11-20-18]]

^<<v11-20-18,18>>^ At that he said: “If they have come out for peace, take them alive; or if they have come out for battle, you should still take them alive.”

[[v11-20-19]]

^<<v11-20-19,19>>^ But when these came out of the city—the attendants of the princes of the provinces and the armies that were following them—

[[v11-20-20]]

^<<v11-20-20,20>>^ each one struck down his opponent. Then the Syrians fled, and Israel pursued them, but King Ben-haʹdad of Syria escaped on a horse with some of the horsemen.

[[v11-20-21]]

^<<v11-20-21,21>>^ But the king of Israel went out and kept striking down the horses and the chariots, and he inflicted a great defeat^&#42;1^ on the Syrians.

[NOTE]
====
. Or “slaughter.”
====

[[v11-20-22]]

^<<v11-20-22,22>>^ Later the prophet approached the king of Israel and said to him: “Go, strengthen yourself and consider what you are going to do, for at the start of the next year^&#42;1^ the king of Syria will come up against you.”

[NOTE]
====
. That is, next spring.
====

[[v11-20-23]]

^<<v11-20-23,23>>^ Now the servants of the king of Syria said to him: “Their God is a God of mountains. That is why they overpowered us. But if we fight against them on level land, we will overpower them.

[[v11-20-24]]

^<<v11-20-24,24>>^ Also do this: Remove all the kings from their places, and replace them with governors.

[[v11-20-25]]

^<<v11-20-25,25>>^ Then gather^&#42;1^ an army equal to the army you lost, horse for horse and chariot for chariot. Let us fight against them on level land, and we will surely overpower them.” So he listened to their advice and did just that.

[NOTE]
====
. Lit., “number.”
====

[[v11-20-26]]

^<<v11-20-26,26>>^ At the start of the year,^&#42;1^ Ben-haʹdad mustered the Syrians and went up to Aʹphek for battle against Israel.

[NOTE]
====
. That is, in the spring.
====

[[v11-20-27]]

^<<v11-20-27,27>>^ The people of Israel were also mustered and supplied, and they went out to meet them. When the people of Israel camped in front of them, they were like two tiny flocks of goats, while the Syrians filled the whole land.

[[v11-20-28]]

^<<v11-20-28,28>>^ Then the man of the true God approached the king of Israel and said: “This is what Jehovah says, ‘Because the Syrians have said: “Jehovah is a God of mountains, and he is not a God of plains,” I will give all this large crowd into your hand, and you will certainly know that I am Jehovah.’”

[[v11-20-29]]

^<<v11-20-29,29>>^ They remained encamped opposite each other for seven days, and on the seventh day the battle began. The people of Israel struck down 100,000 Syrian foot soldiers in one day.

[[v11-20-30]]

^<<v11-20-30,30>>^ And the rest fled to Aʹphek, into the city. But the wall fell down on 27,000 of the men who were left. Ben-haʹdad also fled and came into the city, and he hid in an inner room.

[[v11-20-31]]

^<<v11-20-31,31>>^ So his servants said to him: “Look, we have heard that the kings of the house of Israel are merciful kings.^&#42;1^ Please, let us wear sackcloth on our hips and put ropes on our heads and go out to the king of Israel. Perhaps he will spare your life.”^&#42;2^

[NOTE]
====
. Or “are kings of loyal love.”
. Or “soul.”
====

[[v11-20-32]]

^<<v11-20-32,32>>^ So they wore sackcloth around their hips and ropes on their heads and came in to the king of Israel and said: “Your servant Ben-haʹdad says, ‘Please, let me^&#42;1^ live.’” He replied: “Is he still alive? He is my brother.”

[NOTE]
====
. Or “my soul.”
====

[[v11-20-33]]

^<<v11-20-33,33>>^ The men took it as an omen and quickly took him at his word, so they said: “Ben-haʹdad is your brother.” At that he said: “Go and get him.” Then Ben-haʹdad went out to him, and he had him get up into the chariot.

[[v11-20-34]]

^<<v11-20-34,34>>^ Ben-haʹdad now said to him: “The cities that my father took from your father I will return, and you may establish markets^&#42;1^ for yourself in Damascus, just as my father did in Sa·marʹi·a.”
Aʹhab replied: “On the basis of this agreement,^&#42;2^ I will let you go.”
With that he made an agreement with him and let him go.

[NOTE]
====
. Or “assign streets.”
. Or “covenant.”
====

[[v11-20-35]]

^<<v11-20-35,35>>^ By the word of Jehovah, one of the sons of the prophets^&#42;1^ said to his companion: “Strike me, please.” But the man refused to strike him.

[NOTE]
====
. “The sons of the prophets” seems to refer to a school of instruction for prophets or to an association of prophets.
====

[[v11-20-36]]

^<<v11-20-36,36>>^ So he said to him: “Because you did not listen to the voice of Jehovah, as soon as you leave me, a lion will kill you.”^&#42;1^ After he left him, a lion came upon him and killed him.

[NOTE]
====
. Or “strike you down.”
====

[[v11-20-37]]

^<<v11-20-37,37>>^ He found another man and said: “Strike me, please.” So the man struck him and wounded him.

[[v11-20-38]]

^<<v11-20-38,38>>^ Then the prophet went and waited for the king by the road, disguising himself with a bandage over his eyes.

[[v11-20-39]]

^<<v11-20-39,39>>^ As the king was passing by, he cried out to the king: “Your servant went into the thick of the battle, and there was a man coming out who brought a man to me and said, ‘Guard this man. If he is found missing, your life will have to take the place of his life,^&#42;1^ or else you will pay a talent^&#42;2^ of silver.’

[NOTE]
====
. Or “your soul will be in place of his soul.”
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v11-20-40]]

^<<v11-20-40,40>>^ And while your servant was busy here and there, suddenly the man was gone.” The king of Israel said to him: “So your own judgment will be; you have decided it yourself.”

[[v11-20-41]]

^<<v11-20-41,41>>^ Then he quickly removed the bandage from his eyes, and the king of Israel recognized that he was one of the prophets.

[[v11-20-42]]

^<<v11-20-42,42>>^ He said to him: “This is what Jehovah says, ‘Because you have let the man who I said should be destroyed escape from your hand, your life must take the place of his life,^&#42;1^ and your people the place of his people.’”

[NOTE]
====
. Or “your soul will be in place of his soul.”
====

[[v11-20-43]]

^<<v11-20-43,43>>^ At that the king of Israel went home to Sa·marʹi·a, sullen and dejected.

'''

xref:011-1-kings/011-1-kings-019.adoc#v11-19-0[&#60; Capítulo Anterior] | <<v11-20-0,Topo>> | xref:011-1-kings/011-1-kings-021.adoc#v11-21-0[Próximo Capítulo &#62;]