include::./index.adoc[]

[[v11-6-0]]
=== The First of Kings, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-6-1]]

^<<v11-6-1,1>>^ In the 480th year after the Israelites^&#42;1^ came out of the land of Egypt, in the fourth year after Solʹo·mon became king over Israel, in the month of Ziv^&#42;2^ (that is, the second month), he began to build the house of Jehovah.^&#42;3^

[NOTE]
====
. Lit., “sons of Israel.”
. See App. B15.
. See App. B8.
====

[[v11-6-2]]

^<<v11-6-2,2>>^ The house that King Solʹo·mon built for Jehovah was 60 cubits^&#42;1^ long, 20 cubits wide, and 30 cubits high.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
====

[[v11-6-3]]

^<<v11-6-3,3>>^ The porch in front of the temple^&#42;1^ was 20 cubits long,^&#42;2^ corresponding to the width of the house.^&#42;3^ Its depth was ten cubits from the front of the house.

[NOTE]
====
. Lit., “temple of the house.”
. Or “wide.”
. Or “20 cubits extending across the width of the house.”
====

[[v11-6-4]]

^<<v11-6-4,4>>^ He made windows of narrowing frames^&#42;1^ for the house.

[NOTE]
====
. Or “beveled (splayed) windows.”
====

[[v11-6-5]]

^<<v11-6-5,5>>^ Further, he built a side structure against the wall of the house; it went around the walls of the house, those of the temple^&#42;1^ and the innermost room, and he made side chambers all around.

[NOTE]
====
. Here referring to the Holy.
====

[[v11-6-6]]

^<<v11-6-6,6>>^ The lowest level of the side chambers was five cubits wide, the middle level was six cubits wide, and the third level was seven cubits wide, for he made offsets^&#42;1^ all around the house, so that nothing was attached to the walls of the house.

[NOTE]
====
. Or “recesses.”
====

[[v11-6-7]]

^<<v11-6-7,7>>^ The house was built with quarry stone that had already been prepared, so that no hammers or axes or any iron tools were heard in the house while it was being built.

[[v11-6-8]]

^<<v11-6-8,8>>^ The entrance of the lowest side chamber was on the south^&#42;1^ side of the house, and a winding staircase led up to the middle floor, and from the middle floor up to the third floor.

[NOTE]
====
. Lit., “right.”
====

[[v11-6-9]]

^<<v11-6-9,9>>^ He continued building the house and finished it and covered the house with cedar beams and rows of cedar planks.

[[v11-6-10]]

^<<v11-6-10,10>>^ He built the side chambers all around the house, each five cubits high, and they were joined to the house by cedar timbers.

[[v11-6-11]]

^<<v11-6-11,11>>^ Meanwhile, the word of Jehovah came to Solʹo·mon, saying:

[[v11-6-12]]

^<<v11-6-12,12>>^ “As for this house that you are building, if you walk in my statutes and carry out my judgments and observe all my commandments by walking in them, I will also carry out with you my promise that I made to David your father,

[[v11-6-13]]

^<<v11-6-13,13>>^ and I will reside in the midst of the Israelites, and I will not forsake my people Israel.”

[[v11-6-14]]

^<<v11-6-14,14>>^ Solʹo·mon continued building the house to finish it.

[[v11-6-15]]

^<<v11-6-15,15>>^ He built the inside walls of the house with cedar boards. He paneled the inside walls with timber, from the floor of the house up to the rafters of the ceiling, and he overlaid the floor of the house with juniper boards.

[[v11-6-16]]

^<<v11-6-16,16>>^ And he built a section of 20 cubits at the rear of the house with cedar boards, from the floor up to the rafters, and he built inside of it^&#42;1^ the innermost room, the Most Holy.

[NOTE]
====
. That is, inside the house.
====

[[v11-6-17]]

^<<v11-6-17,17>>^ And the temple^&#42;1^—the part of the house in front of it—was 40 cubits.

[NOTE]
====
. That is, the Holy, which was in front of the Most Holy.
====

[[v11-6-18]]

^<<v11-6-18,18>>^ The cedar inside the house was carved with gourds and flowers in bloom. All of it was cedar; no stone was seen.

[[v11-6-19]]

^<<v11-6-19,19>>^ And he prepared the innermost room inside the house to put there the ark of the covenant of Jehovah.

[[v11-6-20]]

^<<v11-6-20,20>>^ The innermost room was 20 cubits long, 20 cubits wide, and 20 cubits high; and he overlaid it with pure gold; he overlaid the altar with cedar.

[[v11-6-21]]

^<<v11-6-21,21>>^ Solʹo·mon overlaid the interior of the house with pure gold, and he stretched gold chains in front of the innermost room, which was overlaid with gold.

[[v11-6-22]]

^<<v11-6-22,22>>^ He overlaid the whole house with gold until all the house was completed; he also overlaid with gold the entire altar near the innermost room.

[[v11-6-23]]

^<<v11-6-23,23>>^ In the innermost room he made two cherubs of pinewood,^&#42;1^ each ten cubits high.

[NOTE]
====
. Lit., “oil wood,” possibly the Aleppo pine.
====

[[v11-6-24]]

^<<v11-6-24,24>>^ One wing of the cherub measured five cubits, and the other wing was five cubits. From the tip of one wing to the tip of the other wing was ten cubits.

[[v11-6-25]]

^<<v11-6-25,25>>^ The second cherub was also ten cubits. The two cherubs had the same size and shape.

[[v11-6-26]]

^<<v11-6-26,26>>^ The height of the one cherub was ten cubits, as was that of the other cherub.

[[v11-6-27]]

^<<v11-6-27,27>>^ Then he put the cherubs inside the inner house.^&#42;1^ The wings of the cherubs were extended so that the wing of the one cherub reached to one wall and the wing of the other cherub reached to the other wall, and their wings extended toward the middle of the house, so that the wings touched.

[NOTE]
====
. That is, the Most Holy.
====

[[v11-6-28]]

^<<v11-6-28,28>>^ And he overlaid the cherubs with gold.

[[v11-6-29]]

^<<v11-6-29,29>>^ And on all the walls of the house all around both the inner and outer rooms,^&#42;1^ he carved figures of cherubs, palm trees, and flowers in bloom.

[NOTE]
====
. Lit., “inside and outside.”
====

[[v11-6-30]]

^<<v11-6-30,30>>^ He overlaid the floor of the house with gold in the inner and outer rooms.

[[v11-6-31]]

^<<v11-6-31,31>>^ And for the entrance of the innermost room he made doors of pinewood, side pillars, and doorposts, as a fifth part.^&#42;1^

[NOTE]
====
. Perhaps referring to the construction of the doorframe or to the size of the doors.
====

[[v11-6-32]]

^<<v11-6-32,32>>^ The two doors were of pinewood, and he carved on them cherubs, palm trees, and flowers in bloom, and he overlaid them with gold; and he hammered the gold down over the cherubs and the palm trees.

[[v11-6-33]]

^<<v11-6-33,33>>^ For the entrance of the temple,^&#42;1^ that was how he made the doorposts of pinewood, belonging to a fourth part.^&#42;2^

[NOTE]
====
. Here referring to the Holy.
. Perhaps referring to the construction of the doorframe or to the size of the doors.
====

[[v11-6-34]]

^<<v11-6-34,34>>^ And he made two doors of juniper wood. The one door had two leaves that turned on pivots, and the other door had two leaves that turned on pivots.

[[v11-6-35]]

^<<v11-6-35,35>>^ He carved cherubs, palm trees, and flowers in bloom, and overlaid gold foil on the carvings.

[[v11-6-36]]

^<<v11-6-36,36>>^ He built the inner courtyard with three rows of hewn stone and a row of cedar beams.

[[v11-6-37]]

^<<v11-6-37,37>>^ In the 4th year, in the month of Ziv,^&#42;1^ the house of Jehovah had its foundation laid;

[NOTE]
====
. See App. B15.
====

[[v11-6-38]]

^<<v11-6-38,38>>^ and in the 11th year, in the month of Bul^&#42;1^ (that is, the eighth month), the house was finished in all its details and according to its plan. So he spent seven years building it.

[NOTE]
====
. See App. B15.
====

'''

xref:011-1-kings/011-1-kings-005.adoc#v11-5-0[&#60; Capítulo Anterior] | <<v11-6-0,Topo>> | xref:011-1-kings/011-1-kings-007.adoc#v11-7-0[Próximo Capítulo &#62;]