include::./index.adoc[]

[[v11-5-0]]
=== The First of Kings, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-5-1]]

^<<v11-5-1,1>>^ When Hiʹram the king of Tyre heard that Solʹo·mon had been anointed as king in place of his father, he sent his servants to Solʹo·mon, for Hiʹram had always been a friend of David’s.^&#42;1^

[NOTE]
====
. Or “had always loved David.”
====

[[v11-5-2]]

^<<v11-5-2,2>>^ In turn Solʹo·mon sent word to Hiʹram:

[[v11-5-3]]

^<<v11-5-3,3>>^ “You well know that David my father was not able to build a house for the name of Jehovah his God because of the wars waged against him from every side until Jehovah put his enemies under the soles of his feet.

[[v11-5-4]]

^<<v11-5-4,4>>^ But now Jehovah my God has given me rest on all sides. There is no one opposing me and nothing bad happening.

[[v11-5-5]]

^<<v11-5-5,5>>^ So I intend to build a house for the name of Jehovah my God, just as Jehovah promised to David my father, saying: ‘Your son whom I will put on your throne in your place, he is the one who will build the house for my name.’

[[v11-5-6]]

^<<v11-5-6,6>>^ Now command your people to cut cedars of Lebʹa·non for me. My servants will work with your servants, and I will pay the wages of your servants according to the rate you set, for you are aware that not one of us knows how to cut trees like the Si·doʹni·ans.”

[[v11-5-7]]

^<<v11-5-7,7>>^ When Hiʹram heard Solʹo·mon’s words, he rejoiced greatly and said: “May Jehovah be praised today, for he has given David a wise son over this great^&#42;1^ people!”

[NOTE]
====
. Or “numerous.”
====

[[v11-5-8]]

^<<v11-5-8,8>>^ So Hiʹram sent word to Solʹo·mon: “I have heard the message you sent to me. I will do all you desire in providing the cedar and juniper timbers.

[[v11-5-9]]

^<<v11-5-9,9>>^ My servants will bring them down from Lebʹa·non to the sea, and I will make them into log rafts to go by sea to the place that you designate to me. I will have them broken up there, and you can carry them away. In exchange, you will provide the food that I request for my household.”

[[v11-5-10]]

^<<v11-5-10,10>>^ So Hiʹram supplied all the timbers of cedar and juniper that Solʹo·mon desired.

[[v11-5-11]]

^<<v11-5-11,11>>^ And Solʹo·mon gave Hiʹram 20,000 cor measures^&#42;1^ of wheat as food supplies for his household and 20 cor measures of very fine olive oil.^&#42;2^ That was what Solʹo·mon gave Hiʹram year after year.

[NOTE]
====
. A cor equaled 220 L (200 dry qt). See App. B14.
. Lit., “of beaten oil.”
====

[[v11-5-12]]

^<<v11-5-12,12>>^ And Jehovah gave Solʹo·mon wisdom, just as He had promised him. And there was peace between Hiʹram and Solʹo·mon, and the two of them made a treaty.^&#42;1^

[NOTE]
====
. Or “covenant.”
====

[[v11-5-13]]

^<<v11-5-13,13>>^ King Solʹo·mon conscripted men for forced labor out of all Israel; 30,000 men were conscripted.

[[v11-5-14]]

^<<v11-5-14,14>>^ He would send them to Lebʹa·non in shifts of 10,000 each month. They would spend a month in Lebʹa·non and two months at their homes; and Ad·o·niʹram was over those conscripted for forced labor.

[[v11-5-15]]

^<<v11-5-15,15>>^ Solʹo·mon had 70,000 common laborers^&#42;1^ and 80,000 stonecutters in the mountains,

[NOTE]
====
. Or “burden bearers.”
====

[[v11-5-16]]

^<<v11-5-16,16>>^ as well as Solʹo·mon’s 3,300 princely deputies who served as foremen to supervise the workmen.

[[v11-5-17]]

^<<v11-5-17,17>>^ At the king’s order, they quarried large stones, expensive stones, to lay the foundation of the house with hewn stones.

[[v11-5-18]]

^<<v11-5-18,18>>^ So Solʹo·mon’s builders and Hiʹram’s builders and the Geʹbal·ites did the cutting, and they prepared the timbers and the stones to build the house.

'''

xref:011-1-kings/011-1-kings-004.adoc#v11-4-0[&#60; Capítulo Anterior] | <<v11-5-0,Topo>> | xref:011-1-kings/011-1-kings-006.adoc#v11-6-0[Próximo Capítulo &#62;]