include::./index.adoc[]

[[v11-14-0]]
=== The First of Kings, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-14-1]]

^<<v11-14-1,1>>^ At that time A·biʹjah the son of Jer·o·boʹam fell sick.

[[v11-14-2]]

^<<v11-14-2,2>>^ So Jer·o·boʹam said to his wife: “Rise up, please, and disguise yourself so that they will not know that you are Jer·o·boʹam’s wife, and go to Shiʹloh. Look! A·hiʹjah the prophet is there. He is the one who spoke of me becoming king over this people.

[[v11-14-3]]

^<<v11-14-3,3>>^ Take with you ten loaves of bread, sprinkled cakes, and a flask of honey, and go to him. He will then tell you what is going to happen to the boy.”

[[v11-14-4]]

^<<v11-14-4,4>>^ Jer·o·boʹam’s wife did what he said. She rose up and went to Shiʹloh and came to the house of A·hiʹjah. A·hiʹjah’s eyes stared straight ahead, and he could not see because of his age.

[[v11-14-5]]

^<<v11-14-5,5>>^ But Jehovah had told A·hiʹjah: “Here is the wife of Jer·o·boʹam coming to inquire of you regarding her son, for he is sick. I will tell you what to say to her.^&#42;1^ When she arrives, she will conceal her identity.”

[NOTE]
====
. Or “You should tell her such and such.”
====

[[v11-14-6]]

^<<v11-14-6,6>>^ As soon as A·hiʹjah heard the sound of her footsteps as she was coming into the entrance, he said: “Come in, wife of Jer·o·boʹam. Why are you concealing your identity? I have been assigned to give you a harsh message.

[[v11-14-7]]

^<<v11-14-7,7>>^ Go, tell Jer·o·boʹam, ‘This is what Jehovah the God of Israel says: “I raised you up from among your people to make you a leader over my people Israel.

[[v11-14-8]]

^<<v11-14-8,8>>^ Then I ripped the kingdom away from the house of David and gave it to you. But you have not become like my servant David, who kept my commandments and who walked after me with all his heart, doing only what was right in my eyes.

[[v11-14-9]]

^<<v11-14-9,9>>^ But you have done worse than all those who were prior to you, and you made for yourself another god and metal images^&#42;1^ to offend me, and it is I whom you have turned your back on.

[NOTE]
====
. Or “molten statues.”
====

[[v11-14-10]]

^<<v11-14-10,10>>^ For that reason I am bringing calamity on the house of Jer·o·boʹam, and I will annihilate^&#42;1^ from Jer·o·boʹam every male,^&#42;2^ including the helpless and weak in Israel, and I will make a clean sweep of the house of Jer·o·boʹam, just as one clears away the dung until it is all gone!

[NOTE]
====
. Lit., “cut off.”
. Lit., “anyone urinating against a wall.” A Hebrew expression of contempt referring to males.
====

[[v11-14-11]]

^<<v11-14-11,11>>^ Anyone belonging to Jer·o·boʹam who dies in the city, the dogs will eat; and anyone who dies in the field, the birds of the heavens will eat, for Jehovah has spoken it.”’

[[v11-14-12]]

^<<v11-14-12,12>>^ “Now rise up; go to your house. When you set foot in the city, the child will die.

[[v11-14-13]]

^<<v11-14-13,13>>^ All Israel will mourn him and bury him, for he alone of Jer·o·boʹam’s family will be laid in a grave, because he is the only one of the house of Jer·o·boʹam in whom Jehovah the God of Israel has found something good.

[[v11-14-14]]

^<<v11-14-14,14>>^ Jehovah will raise up for himself a king over Israel who will do away with^&#42;1^ the house of Jer·o·boʹam from that day forward, yes, even now.

[NOTE]
====
. Lit., “cut off.”
====

[[v11-14-15]]

^<<v11-14-15,15>>^ Jehovah will strike Israel down like a reed that sways in the water, and he will uproot Israel off this good land that he gave to their forefathers, and he will scatter them beyond the River,^&#42;1^ because they made their sacred poles,^&#42;2^ offending Jehovah.

[NOTE]
====
. That is, the Euphrates.
. See Glossary.
====

[[v11-14-16]]

^<<v11-14-16,16>>^ And he will abandon Israel because of the sins that Jer·o·boʹam has committed and has caused Israel to commit.”

[[v11-14-17]]

^<<v11-14-17,17>>^ At that Jer·o·boʹam’s wife rose up and went on her way and came to Tirʹzah. As she came to the threshold of the house, the boy died.

[[v11-14-18]]

^<<v11-14-18,18>>^ So they buried him, and all Israel mourned him, according to Jehovah’s word that he had spoken through his servant A·hiʹjah the prophet.

[[v11-14-19]]

^<<v11-14-19,19>>^ And the rest of the history of Jer·o·boʹam, how he waged war and how he reigned, is written in the book of the history of the times of the kings of Israel.

[[v11-14-20]]

^<<v11-14-20,20>>^ And the length^&#42;1^ of Jer·o·boʹam’s reign was 22 years, after which he was laid to rest with his forefathers; and his son Naʹdab became king in his place.

[NOTE]
====
. Lit., “days.”
====

[[v11-14-21]]

^<<v11-14-21,21>>^ Meanwhile, Re·ho·boʹam the son of Solʹo·mon had become king in Judah. Re·ho·boʹam was 41 years old when he became king, and he reigned for 17 years in Jerusalem, the city that Jehovah had chosen out of all the tribes of Israel as the place to put his name. The name of Re·ho·boʹam’s mother was Naʹa·mah the Amʹmon·it·ess.

[[v11-14-22]]

^<<v11-14-22,22>>^ And Judah was doing what was bad in the eyes of Jehovah, and by the sins they committed they provoked him more than their forefathers had done.

[[v11-14-23]]

^<<v11-14-23,23>>^ They too kept building for themselves high places, sacred pillars, and sacred poles^&#42;1^ on every high hill and under every luxuriant tree.

[NOTE]
====
. See Glossary.
====

[[v11-14-24]]

^<<v11-14-24,24>>^ There were also male temple prostitutes in the land. They acted according to all the detestable things of the nations that Jehovah had driven out before the Israelites.

[[v11-14-25]]

^<<v11-14-25,25>>^ In the fifth year of King Re·ho·boʹam, King Shiʹshak of Egypt came up against Jerusalem.

[[v11-14-26]]

^<<v11-14-26,26>>^ He took the treasures of the house of Jehovah and the treasures of the king’s house.^&#42;1^ He took everything, including all the gold shields that Solʹo·mon had made.

[NOTE]
====
. Or “palace.”
====

[[v11-14-27]]

^<<v11-14-27,27>>^ So King Re·ho·boʹam made copper shields to replace them, and he entrusted them to the chiefs of the guard,^&#42;1^ who guarded the entrance of the king’s house.

[NOTE]
====
. Lit., “runners.”
====

[[v11-14-28]]

^<<v11-14-28,28>>^ Whenever the king came to the house of Jehovah, the guards would carry them, and then they would return them to the guard chamber.

[[v11-14-29]]

^<<v11-14-29,29>>^ And the rest of the history of Re·ho·boʹam, all that he did, is it not written in the book of the history of the times of the kings of Judah?

[[v11-14-30]]

^<<v11-14-30,30>>^ There was constant warfare between Re·ho·boʹam and Jer·o·boʹam.

[[v11-14-31]]

^<<v11-14-31,31>>^ Then Re·ho·boʹam was laid to rest with his forefathers and was buried with his forefathers in the City of David. His mother’s name was Naʹa·mah the Amʹmon·it·ess. And his son A·biʹjam^&#42;1^ became king in his place.

[NOTE]
====
. Also called Abijah.
====

'''

xref:011-1-kings/011-1-kings-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-1-kings/011-1-kings-015.adoc#v11-15-0[Próximo Capítulo &#62;]