include::./index.adoc[]

[[v11-13-0]]
=== The First of Kings, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-13-1]]

^<<v11-13-1,1>>^ By the word of Jehovah, a man of God came from Judah to Bethʹel while Jer·o·boʹam was standing by the altar to make sacrificial smoke.

[[v11-13-2]]

^<<v11-13-2,2>>^ Then he called out against the altar by the word of Jehovah and said: “O altar, altar! This is what Jehovah says: ‘Look! A son named Jo·siʹah will be born to the house of David! He will sacrifice on you the priests of the high places, those making sacrificial smoke on you, and he will burn human bones on you.’”

[[v11-13-3]]

^<<v11-13-3,3>>^ He gave a sign^&#42;1^ on that day, saying: “This is the sign^&#42;2^ that Jehovah has declared: Look! The altar will be ripped apart, and the ashes^&#42;3^ that are on it will be spilled out.”

[NOTE]
====
. Or “portent.”
. Or “portent.”
. Or “fatty ashes,” that is, ashes soaked with the fat of the sacrifices.
====

[[v11-13-4]]

^<<v11-13-4,4>>^ As soon as the king heard the word that the man of the true God had called out against the altar at Bethʹel, Jer·o·boʹam stretched out his hand from the altar and said: “Seize him!” Immediately, the hand that he had stretched out against him dried up,^&#42;1^ and he could not draw it back.

[NOTE]
====
. Or “was paralyzed.”
====

[[v11-13-5]]

^<<v11-13-5,5>>^ Then the altar was ripped apart and the ashes were spilled out from the altar according to the sign^&#42;1^ that the man of the true God had given by the word of Jehovah.

[NOTE]
====
. Or “portent.”
====

[[v11-13-6]]

^<<v11-13-6,6>>^ The king now said to the man of the true God: “Please, beg for the favor^&#42;1^ of Jehovah your God, and pray in my behalf that my hand may be restored to me.” At this the man of the true God begged for the favor of Jehovah, and the king’s hand was restored to its former condition.

[NOTE]
====
. Or “soften the face.”
====

[[v11-13-7]]

^<<v11-13-7,7>>^ The king then said to the man of the true God: “Come home with me and take some food, and let me give you a gift.”

[[v11-13-8]]

^<<v11-13-8,8>>^ But the man of the true God said to the king: “Even if you gave me half your house, I would not come with you and eat bread or drink water in this place.

[[v11-13-9]]

^<<v11-13-9,9>>^ For this is what I was commanded by the word of Jehovah: ‘You must not eat bread or drink water, and you must not return by the way you came.’”

[[v11-13-10]]

^<<v11-13-10,10>>^ So he left by another way, and he did not return by the way he had come to Bethʹel.

[[v11-13-11]]

^<<v11-13-11,11>>^ There was a certain old prophet dwelling in Bethʹel, and his sons came home and related to him all the things that the man of the true God had done that day in Bethʹel and the words he had spoken to the king. After they related this to their father,

[[v11-13-12]]

^<<v11-13-12,12>>^ their father asked them: “Which way did he go?” So his sons showed him the way that the man of the true God from Judah had gone.

[[v11-13-13]]

^<<v11-13-13,13>>^ He now said to his sons: “Saddle the donkey for me.” They saddled the donkey for him, and he mounted it.

[[v11-13-14]]

^<<v11-13-14,14>>^ He followed the man of the true God and found him sitting under a big tree. Then he said to him: “Are you the man of the true God who came from Judah?” He replied: “I am.”

[[v11-13-15]]

^<<v11-13-15,15>>^ He said to him: “Come home with me and eat bread.”

[[v11-13-16]]

^<<v11-13-16,16>>^ But he said: “I cannot go back with you or accept your invitation, nor may I eat bread or drink water with you in this place.

[[v11-13-17]]

^<<v11-13-17,17>>^ For I was told by the word of Jehovah, ‘You must not eat bread or drink water there. You must not return by the way you came.’”

[[v11-13-18]]

^<<v11-13-18,18>>^ At this he said to him: “I too am a prophet like you, and an angel told me by the word of Jehovah, ‘Have him come back with you to your house so that he may eat bread and drink water.’” (He deceived him.)

[[v11-13-19]]

^<<v11-13-19,19>>^ So he went back with him to eat bread and drink water in his house.

[[v11-13-20]]

^<<v11-13-20,20>>^ While they were sitting at the table, the word of Jehovah came to the prophet who had brought him back,

[[v11-13-21]]

^<<v11-13-21,21>>^ and he called out to the man of the true God from Judah, saying, “This is what Jehovah says: ‘Because you rebelled against the order of Jehovah and did not keep the commandment that Jehovah your God gave you,

[[v11-13-22]]

^<<v11-13-22,22>>^ but you went back to eat bread and drink water in the place about which you were told, “Do not eat bread or drink water,” your dead body will not come into the tomb of your forefathers.’”

[[v11-13-23]]

^<<v11-13-23,23>>^ After the man of the true God ate bread and drank, the old prophet saddled the donkey for the prophet whom he had brought back.

[[v11-13-24]]

^<<v11-13-24,24>>^ Then he got on his way, but a lion came across him on the road and killed him. His dead body was thrown onto the road, and the donkey stood beside it; the lion was also standing beside the dead body.

[[v11-13-25]]

^<<v11-13-25,25>>^ There were men passing by who saw the dead body thrown onto the road and the lion standing beside the dead body. They came in and told about it in the city where the old prophet lived.

[[v11-13-26]]

^<<v11-13-26,26>>^ When the prophet who had brought him back from the road heard of it, he immediately said: “It is the man of the true God who rebelled against the order of Jehovah; so Jehovah gave him over to the lion, to maul and to kill him, according to the word of Jehovah that he spoke to him.”

[[v11-13-27]]

^<<v11-13-27,27>>^ He then said to his sons: “Saddle the donkey for me.” So they saddled it.

[[v11-13-28]]

^<<v11-13-28,28>>^ Then he went on his way and found the dead body thrown onto the road, with the donkey and the lion standing beside it. The lion had not eaten the dead body, nor had it mauled the donkey.

[[v11-13-29]]

^<<v11-13-29,29>>^ The prophet lifted up the dead body of the man of the true God and put him on the donkey, and he brought him back into his own city to mourn and bury him.

[[v11-13-30]]

^<<v11-13-30,30>>^ So he laid the dead body in his own tomb, and they kept crying out over him: “Too bad, my brother!”

[[v11-13-31]]

^<<v11-13-31,31>>^ After burying him, he told his sons: “When I die, you must bury me in the place where the man of the true God is buried. Lay my bones next to his bones.

[[v11-13-32]]

^<<v11-13-32,32>>^ The word that he called out by the word of Jehovah against the altar in Bethʹel and against all the houses of worship on the high places in the cities of Sa·marʹi·a is sure to take place.”

[[v11-13-33]]

^<<v11-13-33,33>>^ Even after this happened, Jer·o·boʹam did not turn back from his bad way, but he kept appointing priests for the high places from the people in general. He would install as priests^&#42;1^ anyone who so desired, saying: “Let him become one of the priests for the high places.”

[NOTE]
====
. Lit., “fill the hand of.”
====

[[v11-13-34]]

^<<v11-13-34,34>>^ This sin on the part of the household of Jer·o·boʹam led to their destruction and annihilation from the face of the earth.

'''

xref:011-1-kings/011-1-kings-012.adoc#v11-12-0[&#60; Capítulo Anterior] | <<v11-13-0,Topo>> | xref:011-1-kings/011-1-kings-014.adoc#v11-14-0[Próximo Capítulo &#62;]