include::./index.adoc[]

[[v11-15-0]]
=== The First of Kings, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-15-1]]

^<<v11-15-1,1>>^ In the 18th year of King Jer·o·boʹam the son of Neʹbat, A·biʹjam became king over Judah.

[[v11-15-2]]

^<<v11-15-2,2>>^ He reigned for three years in Jerusalem. His mother’s name was Maʹa·cah the granddaughter of A·bishʹa·lom.

[[v11-15-3]]

^<<v11-15-3,3>>^ He went on walking in all the sins that his father committed prior to him, and his heart was not complete with^&#42;1^ Jehovah his God like the heart of David his forefather.

[NOTE]
====
. Or “not completely devoted to.”
====

[[v11-15-4]]

^<<v11-15-4,4>>^ However, on account of David, Jehovah his God gave him a lamp in Jerusalem by raising up his son after him and keeping Jerusalem in existence.

[[v11-15-5]]

^<<v11-15-5,5>>^ For David did what was right in the eyes of Jehovah, and he did not turn aside from anything that He had commanded him all the days of his life, except in the matter of U·riʹah the Hitʹtite.

[[v11-15-6]]

^<<v11-15-6,6>>^ And there was warfare between Re·ho·boʹam and Jer·o·boʹam all the days of his life.

[[v11-15-7]]

^<<v11-15-7,7>>^ As for the rest of the history of A·biʹjam, all that he did, is it not written in the book of the history of the times of the kings of Judah? There was also war between A·biʹjam and Jer·o·boʹam.

[[v11-15-8]]

^<<v11-15-8,8>>^ Then A·biʹjam was laid to rest with his forefathers, and they buried him in the City of David; and his son Aʹsa became king in his place.

[[v11-15-9]]

^<<v11-15-9,9>>^ In the 20th year of King Jer·o·boʹam of Israel, Aʹsa began to reign over Judah.

[[v11-15-10]]

^<<v11-15-10,10>>^ He reigned in Jerusalem for 41 years. His grandmother’s name was Maʹa·cah the granddaughter of A·bishʹa·lom.

[[v11-15-11]]

^<<v11-15-11,11>>^ Aʹsa did what was right in the eyes of Jehovah, like David his forefather.

[[v11-15-12]]

^<<v11-15-12,12>>^ He expelled the male temple prostitutes from the land and removed all the disgusting idols^&#42;1^ that his forefathers had made.

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v11-15-13]]

^<<v11-15-13,13>>^ He even removed Maʹa·cah his grandmother from her position as queen mother,^&#42;1^ because she had made an obscene idol for the worship of the sacred pole.^&#42;2^ Aʹsa cut down her obscene idol and burned it in the Kidʹron Valley.

[NOTE]
====
. Or “as lady.”
. See Glossary.
====

[[v11-15-14]]

^<<v11-15-14,14>>^ But the high places were not removed. Nevertheless, Aʹsa’s heart was complete with^&#42;1^ Jehovah all his life.^&#42;2^

[NOTE]
====
. Or “was completely devoted to.”
. Lit., “days.”
====

[[v11-15-15]]

^<<v11-15-15,15>>^ And he brought the things that he and his father had made holy into the house of Jehovah—silver, gold, and various utensils.

[[v11-15-16]]

^<<v11-15-16,16>>^ There was constant warfare between Aʹsa and Baʹa·sha the king of Israel.

[[v11-15-17]]

^<<v11-15-17,17>>^ So King Baʹa·sha of Israel came up against Judah and began to build up^&#42;1^ Raʹmah to prevent anyone from going out or coming in to^&#42;2^ King Aʹsa of Judah.

[NOTE]
====
. Or “fortify; rebuild.”
. Or “leaving or entering the territory of.”
====

[[v11-15-18]]

^<<v11-15-18,18>>^ At that Aʹsa took all the silver and the gold that were left in the treasuries of the house of Jehovah and the treasuries of the house^&#42;1^ of the king and handed them over to his servants. King Aʹsa then sent them to Ben-haʹdad the son of Tab·rimʹmon the son of Heʹzi·on, the king of Syria, who was dwelling in Damascus, saying:

[NOTE]
====
. Or “palace.”
====

[[v11-15-19]]

^<<v11-15-19,19>>^ “There is a treaty^&#42;1^ between me and you and between my father and your father. I am sending you a gift of silver and gold. Come, break your treaty^&#42;2^ with King Baʹa·sha of Israel, so that he will withdraw from me.”

[NOTE]
====
. Or “covenant.”
. Or “covenant.”
====

[[v11-15-20]]

^<<v11-15-20,20>>^ Ben-haʹdad listened to King Aʹsa and sent the chiefs of his armies against the cities of Israel, and they struck down Iʹjon, Dan, Aʹbel-beth-maʹa·cah, all Chinʹne·reth, and all the land of Naphʹta·li.

[[v11-15-21]]

^<<v11-15-21,21>>^ When Baʹa·sha heard of it, he immediately quit building^&#42;1^ Raʹmah and continued dwelling in Tirʹzah.

[NOTE]
====
. Or “fortifying; rebuilding.”
====

[[v11-15-22]]

^<<v11-15-22,22>>^ King Aʹsa then summoned all Judah—no one was exempt—and they carried off the stones and timbers of Raʹmah that Baʹa·sha had been building with, and with them King Aʹsa built up^&#42;1^ Geʹba in Benjamin, and Mizʹpah.

[NOTE]
====
. Or “fortified; rebuilt.”
====

[[v11-15-23]]

^<<v11-15-23,23>>^ As for all the rest of the history of Aʹsa, all his mightiness and all that he did and the cities that he built,^&#42;1^ is it not written in the book of the history of the times of the kings of Judah? But in his old age he suffered from a disease in his feet.

[NOTE]
====
. Or “fortified; rebuilt.”
====

[[v11-15-24]]

^<<v11-15-24,24>>^ Then Aʹsa was laid to rest with his forefathers and was buried with them in the City of David his forefather; and his son Je·hoshʹa·phat became king in his place.

[[v11-15-25]]

^<<v11-15-25,25>>^ Naʹdab the son of Jer·o·boʹam became king over Israel in the second year of King Aʹsa of Judah, and he reigned over Israel for two years.

[[v11-15-26]]

^<<v11-15-26,26>>^ He kept doing what was bad in the eyes of Jehovah and walked in the way of his father and in his sin that he caused Israel to commit.

[[v11-15-27]]

^<<v11-15-27,27>>^ Baʹa·sha the son of A·hiʹjah of the house of Isʹsa·char conspired against him, and Baʹa·sha struck him down at Gibʹbe·thon, which belonged to the Phi·lisʹtines, while Naʹdab and all Israel were besieging Gibʹbe·thon.

[[v11-15-28]]

^<<v11-15-28,28>>^ So Baʹa·sha put him to death in the third year of King Aʹsa of Judah and became king in his place.

[[v11-15-29]]

^<<v11-15-29,29>>^ And as soon as he became king, he struck down all the house of Jer·o·boʹam. He did not let remain anyone breathing who belonged to Jer·o·boʹam; he had them annihilated according to Jehovah’s word that he had spoken through his servant A·hiʹjah the Shiʹlo·nite.

[[v11-15-30]]

^<<v11-15-30,30>>^ This was because of the sins that Jer·o·boʹam had committed and had caused Israel to commit and because he had greatly offended Jehovah the God of Israel.

[[v11-15-31]]

^<<v11-15-31,31>>^ As for the rest of the history of Naʹdab, all that he did, is it not written in the book of the history of the times of the kings of Israel?

[[v11-15-32]]

^<<v11-15-32,32>>^ And there was constant warfare between Aʹsa and King Baʹa·sha of Israel.

[[v11-15-33]]

^<<v11-15-33,33>>^ In the third year of King Aʹsa of Judah, Baʹa·sha the son of A·hiʹjah became king in Tirʹzah over all Israel and reigned for 24 years.

[[v11-15-34]]

^<<v11-15-34,34>>^ But he kept doing what was bad in the eyes of Jehovah, and he walked in the way of Jer·o·boʹam and in his sin that he caused Israel to commit.

'''

xref:011-1-kings/011-1-kings-014.adoc#v11-14-0[&#60; Capítulo Anterior] | <<v11-15-0,Topo>> | xref:011-1-kings/011-1-kings-016.adoc#v11-16-0[Próximo Capítulo &#62;]