include::./index.adoc[]

[[v11-18-0]]
=== The First of Kings, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-18-1]]

^<<v11-18-1,1>>^ After some time, in the third year, Jehovah’s word came to E·liʹjah, saying: “Go, present yourself to Aʹhab, and I will send rain on the surface of the ground.”

[[v11-18-2]]

^<<v11-18-2,2>>^ So E·liʹjah went to present himself to Aʹhab, while the famine was severe in Sa·marʹi·a.

[[v11-18-3]]

^<<v11-18-3,3>>^ Meanwhile, Aʹhab called O·ba·diʹah, who was over the household. (Now O·ba·diʹah greatly feared Jehovah,

[[v11-18-4]]

^<<v11-18-4,4>>^ and when Jezʹe·bel was doing away with^&#42;1^ Jehovah’s prophets, O·ba·diʹah took 100 prophets and hid them 50 to a cave, and he supplied them with bread and water.)

[NOTE]
====
. Lit., “cutting off.”
====

[[v11-18-5]]

^<<v11-18-5,5>>^ Aʹhab then said to O·ba·diʹah: “Go through the land to all the springs of water and to all the valleys.^&#42;1^ Perhaps we can find enough grass to keep the horses and mules alive and not have all our animals die.”

[NOTE]
====
. Or “wadis.”
====

[[v11-18-6]]

^<<v11-18-6,6>>^ So they divided between themselves the land they were going to pass through. Aʹhab went alone by one way, and O·ba·diʹah went alone by another way.

[[v11-18-7]]

^<<v11-18-7,7>>^ As O·ba·diʹah was on his way, E·liʹjah was there to meet him. At once he recognized him and fell facedown and said: “Is this you, my lord E·liʹjah?”

[[v11-18-8]]

^<<v11-18-8,8>>^ He replied to him: “It is I. Go and tell your lord: ‘E·liʹjah is here.’”

[[v11-18-9]]

^<<v11-18-9,9>>^ But he said: “What sin have I committed that you should hand your servant over to Aʹhab to put me to death?

[[v11-18-10]]

^<<v11-18-10,10>>^ As surely as Jehovah your God is living, there is not a nation or a kingdom where my lord has not sent to look for you. After they said, ‘He is not here,’ he made the kingdom and the nation swear that they could not find you.

[[v11-18-11]]

^<<v11-18-11,11>>^ Now you are saying, ‘Go and tell your lord: “E·liʹjah is here.”’

[[v11-18-12]]

^<<v11-18-12,12>>^ When I depart from you, the spirit of Jehovah will carry you away to a place I will not know, and when I tell Aʹhab and he does not find you, he will surely kill me. Yet, your servant has feared Jehovah from his youth.

[[v11-18-13]]

^<<v11-18-13,13>>^ Has my lord not been told what I did when Jezʹe·bel was killing the prophets of Jehovah, how I hid 100 of the prophets of Jehovah by groups of 50 in a cave and kept supplying them bread and water?

[[v11-18-14]]

^<<v11-18-14,14>>^ But now you are saying, ‘Go and tell your lord: “E·liʹjah is here.”’ He will certainly kill me.”

[[v11-18-15]]

^<<v11-18-15,15>>^ However, E·liʹjah said: “As surely as Jehovah of armies whom I serve^&#42;1^ is living, today I will present myself to him.”

[NOTE]
====
. Lit., “before whom I stand.”
====

[[v11-18-16]]

^<<v11-18-16,16>>^ So O·ba·diʹah went off to meet Aʹhab and told him, and Aʹhab went to meet E·liʹjah.

[[v11-18-17]]

^<<v11-18-17,17>>^ As soon as Aʹhab saw E·liʹjah, he said to him: “Is this you, the one bringing great trouble^&#42;1^ on Israel?”

[NOTE]
====
. Or “bringing ostracism.”
====

[[v11-18-18]]

^<<v11-18-18,18>>^ To this he said: “I have not brought trouble on Israel, but you and the house of your father have, by abandoning the commandments of Jehovah and by following the Baʹals.

[[v11-18-19]]

^<<v11-18-19,19>>^ And now summon all Israel to me at Mount Carʹmel, as well as the 450 prophets of Baʹal and the 400 prophets of the sacred pole,^&#42;1^ who are eating at the table of Jezʹe·bel.”

[NOTE]
====
. See Glossary.
====

[[v11-18-20]]

^<<v11-18-20,20>>^ So Aʹhab sent word among all the people of Israel and collected the prophets together at Mount Carʹmel.

[[v11-18-21]]

^<<v11-18-21,21>>^ Then E·liʹjah approached all the people and said: “How long will you be limping between two different opinions?^&#42;1^ If Jehovah is the true God, follow him; but if Baʹal is, follow him!” But the people did not say a word in answer to him.

[NOTE]
====
. Or “on two crutches.”
====

[[v11-18-22]]

^<<v11-18-22,22>>^ E·liʹjah then said to the people: “I am the only prophet of Jehovah left, while the prophets of Baʹal are 450 men.

[[v11-18-23]]

^<<v11-18-23,23>>^ Let them give us two young bulls, and let them choose one young bull and cut it into pieces and put it on the wood, but they should not put fire to it. I will prepare the other young bull, and I will place it on the wood, but I will not put fire to it.

[[v11-18-24]]

^<<v11-18-24,24>>^ Then you must call on the name of your god, and I will call on the name of Jehovah. The God who answers by fire will show that he is the true God.” To this all the people answered: “What you say is good.”

[[v11-18-25]]

^<<v11-18-25,25>>^ E·liʹjah now said to the prophets of Baʹal: “Choose one young bull and prepare it first, because you are the majority. Then call on the name of your god, but you must not put fire to it.”

[[v11-18-26]]

^<<v11-18-26,26>>^ So they took the young bull that was given to them, prepared it, and kept calling on the name of Baʹal from morning until noon, saying: “O Baʹal, answer us!” But there was no voice and no one answering. They kept limping around the altar that they had made.

[[v11-18-27]]

^<<v11-18-27,27>>^ About noon E·liʹjah began to mock them and say: “Call out at the top of your voice! After all, he is a god! Perhaps he is deep in thought or he has gone to relieve himself.^&#42;1^ Or maybe he is asleep and someone needs to wake him up!”

[NOTE]
====
. Or possibly, “he has gone on a journey.”
====

[[v11-18-28]]

^<<v11-18-28,28>>^ They were calling out at the top of their voice and cutting themselves with daggers and lances, according to their custom, until their blood gushed out all over them.

[[v11-18-29]]

^<<v11-18-29,29>>^ Noon was past and they continued in a frenzy^&#42;1^ until the time the evening grain offering is presented, but there was no voice and no one answering; no one was paying attention.

[NOTE]
====
. Or “behaving like prophets.”
====

[[v11-18-30]]

^<<v11-18-30,30>>^ At length E·liʹjah said to all the people: “Approach me.” So all the people approached him. Then he repaired the altar of Jehovah that had been torn down.

[[v11-18-31]]

^<<v11-18-31,31>>^ E·liʹjah then took 12 stones, corresponding to the number of the tribes of the sons of Jacob, to whom Jehovah’s word had come, saying: “Israel will be your name.”

[[v11-18-32]]

^<<v11-18-32,32>>^ With the stones he built an altar in the name of Jehovah. Then he made a trench all around the altar, an area large enough to sow with two seah measures^&#42;1^ of seed.

[NOTE]
====
. A seah equaled 7.33 L (6.66 dry qt). See App. B14.
====

[[v11-18-33]]

^<<v11-18-33,33>>^ After that he put the pieces of wood in order, cut the young bull into pieces, and placed it on the wood. He now said: “Fill four large jars with water and pour it on the burnt offering and on the pieces of wood.”

[[v11-18-34]]

^<<v11-18-34,34>>^ Then he said: “Do it again.” So they did it again. Once more he said: “Do it a third time.” So they did it a third time.

[[v11-18-35]]

^<<v11-18-35,35>>^ And the water ran all around the altar, and he also filled the trench with water.

[[v11-18-36]]

^<<v11-18-36,36>>^ About the time when the evening grain offering is presented, E·liʹjah the prophet stepped forward and said: “O Jehovah, the God of Abraham, Isaac, and Israel, today let it be known that you are God in Israel and that I am your servant and that it is by your word that I have done all these things.

[[v11-18-37]]

^<<v11-18-37,37>>^ Answer me, O Jehovah! Answer me so that this people may know that you, Jehovah, are the true God and that you are turning their hearts back to you.”

[[v11-18-38]]

^<<v11-18-38,38>>^ At that the fire of Jehovah fell from above and consumed the burnt offering, the pieces of wood, the stones, and the dust, and it licked up the water from the trench.

[[v11-18-39]]

^<<v11-18-39,39>>^ When all the people saw it, they immediately fell facedown and said: “Jehovah is the true God! Jehovah is the true God!”

[[v11-18-40]]

^<<v11-18-40,40>>^ Then E·liʹjah said to them: “Seize the prophets of Baʹal! Do not let a single one of them escape!” At once they seized them, and E·liʹjah brought them down to the stream^&#42;1^ of Kiʹshon and slaughtered them there.

[NOTE]
====
. Or “wadi.”
====

[[v11-18-41]]

^<<v11-18-41,41>>^ E·liʹjah now said to Aʹhab: “Go up, eat and drink, for there is the sound of a heavy downpour.”

[[v11-18-42]]

^<<v11-18-42,42>>^ So Aʹhab went up to eat and drink, while E·liʹjah went up to the top of Carʹmel and crouched on the ground, keeping his face between his knees.

[[v11-18-43]]

^<<v11-18-43,43>>^ Then he said to his attendant: “Go up, please, and look toward the sea.” So he went up and looked and said: “There is nothing at all.” Seven times E·liʹjah said, “Go back.”

[[v11-18-44]]

^<<v11-18-44,44>>^ The seventh time his attendant said: “Look! There is a small cloud like a man’s hand ascending out of the sea.” He now said: “Go, say to Aʹhab, ‘Hitch up the chariot! Go down so that the downpour may not detain you!’”

[[v11-18-45]]

^<<v11-18-45,45>>^ Meanwhile, the sky grew dark with clouds, the wind blew, and a heavy downpour fell; and Aʹhab kept riding and made his way to Jezʹre·el.

[[v11-18-46]]

^<<v11-18-46,46>>^ But the hand of Jehovah came on E·liʹjah, and he wrapped his garment around^&#42;1^ his hips and ran ahead of Aʹhab all the way to Jezʹre·el.

[NOTE]
====
. Or “he girded.”
====

'''

xref:011-1-kings/011-1-kings-017.adoc#v11-17-0[&#60; Capítulo Anterior] | <<v11-18-0,Topo>> | xref:011-1-kings/011-1-kings-019.adoc#v11-19-0[Próximo Capítulo &#62;]