include::./index.adoc[]

[[v11-12-0]]
=== The First of Kings, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-12-1]]

^<<v11-12-1,1>>^ Re·ho·boʹam went to Sheʹchem, for all Israel had come to Sheʹchem to make him king.

[[v11-12-2]]

^<<v11-12-2,2>>^ As soon as Jer·o·boʹam the son of Neʹbat heard of it (he was still in Egypt because he had run off on account of King Solʹo·mon and was living in Egypt),

[[v11-12-3]]

^<<v11-12-3,3>>^ they sent for him. After that Jer·o·boʹam and all the congregation of Israel came to Re·ho·boʹam and said:

[[v11-12-4]]

^<<v11-12-4,4>>^ “Your father made our yoke harsh. But if you make the harsh service of your father easier and you lighten the heavy^&#42;1^ yoke he put on us, we will serve you.”

[NOTE]
====
. Or “oppressive.”
====

[[v11-12-5]]

^<<v11-12-5,5>>^ At this he said to them: “Go away for three days; then return to me.” So the people went away.

[[v11-12-6]]

^<<v11-12-6,6>>^ King Re·ho·boʹam then consulted with the older men^&#42;1^ who had served his father Solʹo·mon while he was alive, saying: “What advice would you give on how to reply to this people?”

[NOTE]
====
. Or “the elders.”
====

[[v11-12-7]]

^<<v11-12-7,7>>^ They answered him: “If today you would become a servant to this people and submit to their request and give them a favorable answer, they will always be your servants.”

[[v11-12-8]]

^<<v11-12-8,8>>^ However, he rejected the advice that the older men^&#42;1^ gave him, and he consulted with the young men who had grown up with him and who were now his attendants.

[NOTE]
====
. Or “the elders.”
====

[[v11-12-9]]

^<<v11-12-9,9>>^ He asked them: “What advice do you offer on how we should reply to this people who have said to me, ‘Make the yoke your father put on us lighter’?”

[[v11-12-10]]

^<<v11-12-10,10>>^ The young men who had grown up with him said to him: “This is what you should say to this people who have said to you, ‘Your father made our yoke heavy, but you should make it lighter for us’; this is what you should tell them, ‘My little finger will be thicker than my father’s hips.

[[v11-12-11]]

^<<v11-12-11,11>>^ My father imposed a heavy yoke on you, but I will add to your yoke. My father punished you with whips, but I will punish you with scourges.’”

[[v11-12-12]]

^<<v11-12-12,12>>^ Jer·o·boʹam and all the people came to Re·ho·boʹam on the third day, just as the king had said: “Return to me on the third day.”

[[v11-12-13]]

^<<v11-12-13,13>>^ But the king answered the people harshly, rejecting the advice that the older men^&#42;1^ had given him.

[NOTE]
====
. Or “the elders.”
====

[[v11-12-14]]

^<<v11-12-14,14>>^ He spoke to them according to the advice of the young men, saying: “My father made your yoke heavy, but I will add to your yoke. My father punished you with whips, but I will punish you with scourges.”

[[v11-12-15]]

^<<v11-12-15,15>>^ So the king did not listen to the people, for this turn of events was caused by Jehovah, in order to carry out the word that Jehovah had spoken through A·hiʹjah the Shiʹlo·nite to Jer·o·boʹam the son of Neʹbat.

[[v11-12-16]]

^<<v11-12-16,16>>^ When all Israel saw that the king refused to listen to them, the people replied to the king: “What share do we have in David? We have no inheritance in the son of Jesʹse. To your gods, O Israel. Now look after your own house, O David!” With that Israel returned to their homes.^&#42;1^

[NOTE]
====
. Lit., “tents.”
====

[[v11-12-17]]

^<<v11-12-17,17>>^ But Re·ho·boʹam continued to reign over the Israelites living in the cities of Judah.

[[v11-12-18]]

^<<v11-12-18,18>>^ Then King Re·ho·boʹam sent A·doʹram, who was in charge of those conscripted for forced labor, but all Israel stoned him to death. King Re·ho·boʹam managed to mount his chariot to flee to Jerusalem.

[[v11-12-19]]

^<<v11-12-19,19>>^ And the Israelites have been in revolt against the house of David down to this day.

[[v11-12-20]]

^<<v11-12-20,20>>^ As soon as all Israel heard that Jer·o·boʹam had returned, they summoned him to the assembly and made him king over all Israel. None of the people followed the house of David except the tribe of Judah.

[[v11-12-21]]

^<<v11-12-21,21>>^ When Re·ho·boʹam arrived in Jerusalem, he immediately congregated all the house of Judah and the tribe of Benjamin, 180,000 trained^&#42;1^ warriors, to fight against the house of Israel in order to restore the kingship to Re·ho·boʹam the son of Solʹo·mon.

[NOTE]
====
. Lit., “chosen.”
====

[[v11-12-22]]

^<<v11-12-22,22>>^ Then the word of the true God came to She·maiʹah the man of the true God, saying:

[[v11-12-23]]

^<<v11-12-23,23>>^ “Say to Re·ho·boʹam the son of Solʹo·mon the king of Judah and to all the house of Judah and Benjamin and the rest of the people,

[[v11-12-24]]

^<<v11-12-24,24>>^ ‘This is what Jehovah says: “You must not go up and fight against your Israelite brothers. Each one of you must return to his house, for I have caused this to happen.”’” So they obeyed the word of Jehovah and went back home, as Jehovah had told them.

[[v11-12-25]]

^<<v11-12-25,25>>^ Jer·o·boʹam then built up^&#42;1^ Sheʹchem in the mountainous region of Eʹphra·im and lived there. From there he went out and built up^&#42;2^ Pe·nuʹel.

[NOTE]
====
. Or “fortified.”
. Or “fortified.”
====

[[v11-12-26]]

^<<v11-12-26,26>>^ Jer·o·boʹam said in his heart: “Now the kingdom will return to the house of David.

[[v11-12-27]]

^<<v11-12-27,27>>^ If this people continues to go up to offer sacrifices at the house of Jehovah in Jerusalem, the heart of this people will also return to their lord, King Re·ho·boʹam of Judah. Yes, they will kill me and return to King Re·ho·boʹam of Judah.”

[[v11-12-28]]

^<<v11-12-28,28>>^ After consultation, the king made two golden calves and said to the people: “It is too much for you to go up to Jerusalem. Here is your God, O Israel, who brought you up out of the land of Egypt.”

[[v11-12-29]]

^<<v11-12-29,29>>^ Then he placed one in Bethʹel, and the other he put in Dan.

[[v11-12-30]]

^<<v11-12-30,30>>^ And this caused them to sin, and the people went as far as Dan to worship the one there.

[[v11-12-31]]

^<<v11-12-31,31>>^ And he made houses of worship on the high places and appointed priests from the people in general, those who were not Levites.

[[v11-12-32]]

^<<v11-12-32,32>>^ Jer·o·boʹam also established a festival in the eighth month, on the 15th day of the month, like the festival in Judah. On the altar that he made at Bethʹel, he sacrificed to the calves he had made, and at Bethʹel he assigned priests for the high places that he had made.

[[v11-12-33]]

^<<v11-12-33,33>>^ And he began to make offerings on the altar that he had made at Bethʹel on the 15th day in the eighth month, in the month that he had devised on his own; and he established a festival for the people of Israel, and he ascended the altar to make offerings and sacrificial smoke.

'''

xref:011-1-kings/011-1-kings-011.adoc#v11-11-0[&#60; Capítulo Anterior] | <<v11-12-0,Topo>> | xref:011-1-kings/011-1-kings-013.adoc#v11-13-0[Próximo Capítulo &#62;]