include::./index.adoc[]

[[v11-3-0]]
=== The First of Kings, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-3-1]]

^<<v11-3-1,1>>^ Solʹo·mon made a marriage alliance with Pharʹaoh king of Egypt. He married^&#42;1^ Pharʹaoh’s daughter and brought her to the City of David until he finished building his own house, and the house of Jehovah, and the wall around Jerusalem.

[NOTE]
====
. Or “took.”
====

[[v11-3-2]]

^<<v11-3-2,2>>^ But the people were still sacrificing on the high places, because until that time a house for the name of Jehovah had not yet been built.

[[v11-3-3]]

^<<v11-3-3,3>>^ Solʹo·mon continued to love Jehovah by walking in the statutes of David his father, except that he was sacrificing and making offerings smoke on the high places.

[[v11-3-4]]

^<<v11-3-4,4>>^ The king went to Gibʹe·on to sacrifice there, for that was the most prominent^&#42;1^ high place. Solʹo·mon offered 1,000 burnt sacrifices on that altar.

[NOTE]
====
. Lit., “the great.”
====

[[v11-3-5]]

^<<v11-3-5,5>>^ In Gibʹe·on Jehovah appeared to Solʹo·mon in a dream by night, and God said: “Ask what you would like me to give you.”

[[v11-3-6]]

^<<v11-3-6,6>>^ At this Solʹo·mon said: “You have shown great loyal love toward your servant David my father as he walked before you in faithfulness and in righteousness and in uprightness of heart. You have continued to show him this great loyal love down to this day by giving him a son to sit on his throne.

[[v11-3-7]]

^<<v11-3-7,7>>^ And now, Jehovah my God, you have made your servant king in the place of David my father, though I am just a youth^&#42;1^ and I am inexperienced.^&#42;2^

[NOTE]
====
. Or “little boy.”
. Lit., “and I do not know going out and coming in.”
====

[[v11-3-8]]

^<<v11-3-8,8>>^ Your servant is among your people whom you have chosen, a people so vast that they cannot be numbered or counted.

[[v11-3-9]]

^<<v11-3-9,9>>^ So grant your servant an obedient heart to judge your people, to discern between good and bad, for who is able to judge this numerous^&#42;1^ people of yours?”

[NOTE]
====
. Or possibly, “difficult.” Lit., “heavy.”
====

[[v11-3-10]]

^<<v11-3-10,10>>^ It was pleasing to Jehovah that Solʹo·mon had requested this.

[[v11-3-11]]

^<<v11-3-11,11>>^ God then said to him: “Because you requested this and you did not request for yourself long life^&#42;1^ or riches or the death^&#42;2^ of your enemies, but you requested understanding to hear judicial cases,

[NOTE]
====
. Lit., “many days.”
. Or “souls.”
====

[[v11-3-12]]

^<<v11-3-12,12>>^ I will do what you asked. I will give you a wise and understanding heart, so that just as there has never been anyone like you before, there will never be anyone like you again.

[[v11-3-13]]

^<<v11-3-13,13>>^ Furthermore, what you have not requested I will give you, both riches and glory, so that there will be no other king like you in your lifetime.^&#42;1^

[NOTE]
====
. Lit., “all your days.”
====

[[v11-3-14]]

^<<v11-3-14,14>>^ And if you walk in my ways by keeping my regulations and my commandments, just as David your father walked, I will also give you a long life.”^&#42;1^

[NOTE]
====
. Lit., “lengthen your days.”
====

[[v11-3-15]]

^<<v11-3-15,15>>^ When Solʹo·mon awoke, he realized that it had been a dream. Then he went to Jerusalem and stood before the ark of the covenant of Jehovah and offered up burnt sacrifices and communion offerings and spread a feast for all his servants.

[[v11-3-16]]

^<<v11-3-16,16>>^ At that time two prostitutes came in to the king and stood before him.

[[v11-3-17]]

^<<v11-3-17,17>>^ The first woman said: “Please, my lord, this woman and I live in one house, and I gave birth while she was in the house.

[[v11-3-18]]

^<<v11-3-18,18>>^ On the third day after I gave birth, this woman also gave birth. We were together, just the two of us; there was no one else with us in the house.

[[v11-3-19]]

^<<v11-3-19,19>>^ During the night this woman’s son died, because she lay on him.

[[v11-3-20]]

^<<v11-3-20,20>>^ So she got up in the middle of the night and took my son from my side while your slave girl was asleep and laid him in her arms,^&#42;1^ and she laid her dead son in my arms.

[NOTE]
====
. Lit., “her bosom.”
====

[[v11-3-21]]

^<<v11-3-21,21>>^ When I got up in the morning to nurse my son, I saw that he was dead. So I examined him closely in the morning and saw that it was not my son whom I had given birth to.”

[[v11-3-22]]

^<<v11-3-22,22>>^ But the other woman said: “No, my son is the living one, and your son is the dead one!” But the first woman was saying: “No, your son is the dead one, and my son is the living one.” That is how they argued before the king.

[[v11-3-23]]

^<<v11-3-23,23>>^ Finally the king said: “This one says, ‘This is my son, the living one, and your son is the dead one!’ and that one says, ‘No, your son is the dead one, and my son is the living one!’”

[[v11-3-24]]

^<<v11-3-24,24>>^ The king said: “Bring me a sword.” So they brought a sword to the king.

[[v11-3-25]]

^<<v11-3-25,25>>^ The king then said: “Cut the living child in two, and give half to one woman and half to the other.”

[[v11-3-26]]

^<<v11-3-26,26>>^ At once the woman whose son was the living one pleaded with the king, for her compassions were stirred toward her son. She said: “Please, my lord! You should give her the living child! By no means put him to death!” But the other woman was saying: “He will be neither mine nor yours! Let them cut him in two!”

[[v11-3-27]]

^<<v11-3-27,27>>^ At that the king answered: “Give the living child to the first woman! By no means put him to death, for she is his mother.”

[[v11-3-28]]

^<<v11-3-28,28>>^ So all Israel heard about the judgment that the king had handed down, and they were in awe^&#42;1^ of the king, for they saw that the wisdom of God was with him to execute justice.

[NOTE]
====
. Lit., “fear.”
====

'''

xref:011-1-kings/011-1-kings-002.adoc#v11-2-0[&#60; Capítulo Anterior] | <<v11-3-0,Topo>> | xref:011-1-kings/011-1-kings-004.adoc#v11-4-0[Próximo Capítulo &#62;]