include::./index.adoc[]

[[v11-9-0]]
=== The First of Kings, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-9-1]]

^<<v11-9-1,1>>^ As soon as Solʹo·mon had finished building the house of Jehovah, the house^&#42;1^ of the king, and everything Solʹo·mon desired to make,

[NOTE]
====
. Or “palace.”
====

[[v11-9-2]]

^<<v11-9-2,2>>^ Jehovah appeared to Solʹo·mon a second time, just as he had appeared to him in Gibʹe·on.

[[v11-9-3]]

^<<v11-9-3,3>>^ Jehovah said to him: “I have heard your prayer and your request for favor that you made before me. I have sanctified this house that you built by permanently putting my name there, and my eyes and my heart will always be there.

[[v11-9-4]]

^<<v11-9-4,4>>^ And you, if you walk before me as your father David walked, with integrity of heart and with uprightness, by doing everything I have commanded you, and you obey my regulations and my judgments,

[[v11-9-5]]

^<<v11-9-5,5>>^ then I will establish the throne of your kingdom over Israel forever, just as I promised your father David, saying, ‘There will never fail to be a man of your line sitting on the throne of Israel.’

[[v11-9-6]]

^<<v11-9-6,6>>^ But if you and your sons turn away from following me and do not keep my commandments and my statutes that I have put before you, and you go and serve other gods and bow down to them,

[[v11-9-7]]

^<<v11-9-7,7>>^ I will cut Israel off from the surface of the land that I have given to them, and the house that I have sanctified for my name I will cast out of my sight, and Israel will become an object of scorn^&#42;1^ and a cause for ridicule among all the peoples.

[NOTE]
====
. Lit., “a proverb.”
====

[[v11-9-8]]

^<<v11-9-8,8>>^ And this house will become heaps of ruins. Everyone passing by it will stare in amazement and will whistle and say, ‘Why did Jehovah do that to this land and this house?’

[[v11-9-9]]

^<<v11-9-9,9>>^ Then they will say, ‘It was because they abandoned Jehovah their God, who had brought their forefathers out of the land of Egypt, and they embraced other gods and bowed down to them and served them. That is why Jehovah brought all this calamity on them.’”

[[v11-9-10]]

^<<v11-9-10,10>>^ At the end of 20 years, during which Solʹo·mon built the two houses, the house of Jehovah and the house^&#42;1^ of the king,

[NOTE]
====
. Or “palace.”
====

[[v11-9-11]]

^<<v11-9-11,11>>^ Hiʹram the king of Tyre had supplied Solʹo·mon with cedar and juniper timbers and with as much gold as he desired, and King Solʹo·mon gave to Hiʹram 20 cities in the land of Galʹi·lee.

[[v11-9-12]]

^<<v11-9-12,12>>^ So Hiʹram went out from Tyre to see the cities that Solʹo·mon had given him, but he was not satisfied with them.^&#42;1^

[NOTE]
====
. Lit., “they were not right in his eyes.”
====

[[v11-9-13]]

^<<v11-9-13,13>>^ He said: “What sort of cities are these that you have given me, my brother?” So they came to be called the Land of Caʹbul^&#42;1^ down to this day.

[NOTE]
====
. Or possibly, “the Land as Good as Nothing.”
====

[[v11-9-14]]

^<<v11-9-14,14>>^ In the meantime, Hiʹram sent to the king 120 talents^&#42;1^ of gold.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v11-9-15]]

^<<v11-9-15,15>>^ This is the account of those whom King Solʹo·mon conscripted for forced labor to build the house of Jehovah, his own house,^&#42;1^ the Mound,^&#42;2^ the wall of Jerusalem, Haʹzor, Me·gidʹdo, and Geʹzer.

[NOTE]
====
. Or “palace.”
. Or “Millo.” A Hebrew term meaning “fill.”
====

[[v11-9-16]]

^<<v11-9-16,16>>^ (Pharʹaoh king of Egypt had come up and captured Geʹzer and had burned it with fire, and he had also killed the Caʹnaan·ites dwelling in the city. So he gave it as a parting gift^&#42;1^ to his daughter, the wife of Solʹo·mon.)

[NOTE]
====
. Or “a wedding gift; a dowry.”
====

[[v11-9-17]]

^<<v11-9-17,17>>^ Solʹo·mon built up^&#42;1^ Geʹzer, Lower Beth-hoʹron,

[NOTE]
====
. Or “fortified.”
====

[[v11-9-18]]

^<<v11-9-18,18>>^ Baʹal·ath, and Taʹmar in the wilderness, within the land,

[[v11-9-19]]

^<<v11-9-19,19>>^ as well as all of Solʹo·mon’s storage cities, the chariot cities, the cities for the horsemen, and whatever Solʹo·mon desired to build in Jerusalem, in Lebʹa·non, and in all the land of his dominion.

[[v11-9-20]]

^<<v11-9-20,20>>^ As for all the people who were left from the Amʹor·ites, the Hitʹtites, the Perʹiz·zites, the Hiʹvites, and the Jebʹu·sites, who were not part of the people of Israel,

[[v11-9-21]]

^<<v11-9-21,21>>^ their descendants who were left in the land—those whom the Israelites had been unable to devote to destruction—were conscripted by Solʹo·mon for forced labor as slaves until this day.

[[v11-9-22]]

^<<v11-9-22,22>>^ But Solʹo·mon did not make any of the Israelites slaves, for they were his warriors, servants, princes, adjutants, and the chiefs of his charioteers and horsemen.

[[v11-9-23]]

^<<v11-9-23,23>>^ There were 550 chiefs of the deputies who were over the work of Solʹo·mon, the foremen over the people who were doing the work.

[[v11-9-24]]

^<<v11-9-24,24>>^ But Pharʹaoh’s daughter came up from the City of David to her own house that he had built for her; then he built the Mound.^&#42;1^

[NOTE]
====
. Or “Millo.” A Hebrew term meaning “fill.”
====

[[v11-9-25]]

^<<v11-9-25,25>>^ Three times a year Solʹo·mon offered up burnt sacrifices and communion sacrifices on the altar that he had built for Jehovah, also making sacrificial smoke on the altar, which was before Jehovah, so he completed the house.

[[v11-9-26]]

^<<v11-9-26,26>>^ King Solʹo·mon also made a fleet of ships in Eʹzi·on-geʹber, which is by Eʹloth, on the shore of the Red Sea in the land of Eʹdom.

[[v11-9-27]]

^<<v11-9-27,27>>^ Hiʹram sent his own servants with the fleet of ships, experienced seamen, to serve along with the servants of Solʹo·mon.

[[v11-9-28]]

^<<v11-9-28,28>>^ They went to Oʹphir and took from there 420 talents of gold and brought it to King Solʹo·mon.

'''

xref:011-1-kings/011-1-kings-008.adoc#v11-8-0[&#60; Capítulo Anterior] | <<v11-9-0,Topo>> | xref:011-1-kings/011-1-kings-010.adoc#v11-10-0[Próximo Capítulo &#62;]