include::./index.adoc[]

[[v11-1-0]]
=== The First of Kings, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v11-1-1]]

^<<v11-1-1,1>>^ Now King David was old, advanced in years,^&#42;1^ and although they would cover him with garments, he could not get warm.

[NOTE]
====
. Lit., “days.”
====

[[v11-1-2]]

^<<v11-1-2,2>>^ So his servants said to him: “Let a girl, a virgin, be found for my lord the king, and she will wait on the king as his nurse. She will lie in your arms so that my lord the king may feel warm.”

[[v11-1-3]]

^<<v11-1-3,3>>^ They searched throughout all the territory of Israel for a beautiful girl, and they found Abʹi·shag the Shuʹnam·mite and brought her in to the king.

[[v11-1-4]]

^<<v11-1-4,4>>^ The girl was extremely beautiful, and she became the king’s nurse and waited on him, but the king did not have sexual relations with her.

[[v11-1-5]]

^<<v11-1-5,5>>^ Meanwhile, Ad·o·niʹjah the son of Hagʹgith was exalting himself, saying: “I am going to be king!” He had a chariot made for himself with horsemen and 50 men to run before him.

[[v11-1-6]]

^<<v11-1-6,6>>^ But his father had never confronted him^&#42;1^ by saying: “Why have you done this?” He was also very handsome, and his mother had given birth to him after Abʹsa·lom.

[NOTE]
====
. Or “hurt his feelings; rebuked him.”
====

[[v11-1-7]]

^<<v11-1-7,7>>^ He conferred with Joʹab the son of Ze·ruʹiah and A·biʹa·thar the priest, and they offered Ad·o·niʹjah help and support.

[[v11-1-8]]

^<<v11-1-8,8>>^ But Zaʹdok the priest, Be·naiʹah the son of Je·hoiʹa·da, Nathan the prophet, Shimʹe·i, Reʹi, and David’s mighty warriors did not support Ad·o·niʹjah.

[[v11-1-9]]

^<<v11-1-9,9>>^ Eventually Ad·o·niʹjah held a sacrifice of sheep, cattle, and fattened animals by the stone of Zoʹhe·leth, which is near En-roʹgel, and he invited all his brothers the king’s sons, and all the men of Judah the king’s servants.

[[v11-1-10]]

^<<v11-1-10,10>>^ But he did not invite Nathan the prophet, Be·naiʹah and the mighty warriors, or Solʹo·mon his brother.

[[v11-1-11]]

^<<v11-1-11,11>>^ Nathan then said to Bath-sheʹba, Solʹo·mon’s mother: “Have you not heard that Ad·o·niʹjah the son of Hagʹgith has become king, and our lord David does not know anything about it?

[[v11-1-12]]

^<<v11-1-12,12>>^ So now come, please, and let me advise you, so that you may save your own life and the life of^&#42;1^ your son Solʹo·mon.

[NOTE]
====
. Or “your own soul and the soul of.”
====

[[v11-1-13]]

^<<v11-1-13,13>>^ Go in to King David and say to him, ‘Was it not you, my lord the king, who swore to your servant, saying: “Your son Solʹo·mon will become king after me, and he is the one who will sit on my throne”? So why has Ad·o·niʹjah become king?’

[[v11-1-14]]

^<<v11-1-14,14>>^ While you are still there speaking with the king, I will come in after you and confirm your words.”

[[v11-1-15]]

^<<v11-1-15,15>>^ So Bath-sheʹba went in to the king, into his private room. The king was very old, and Abʹi·shag the Shuʹnam·mite was waiting on the king.

[[v11-1-16]]

^<<v11-1-16,16>>^ Then Bath-sheʹba bowed low and prostrated herself to the king, and the king said: “What is your request?”

[[v11-1-17]]

^<<v11-1-17,17>>^ She replied: “My lord, it was you who swore by Jehovah your God to your servant, ‘Your son Solʹo·mon will become king after me, and he is the one who will sit on my throne.’

[[v11-1-18]]

^<<v11-1-18,18>>^ But look! Ad·o·niʹjah has become king, and my lord the king does not know anything about it.

[[v11-1-19]]

^<<v11-1-19,19>>^ He sacrificed bulls, fattened animals, and sheep in great quantity and invited all the sons of the king and A·biʹa·thar the priest and Joʹab the chief of the army; but he did not invite your servant Solʹo·mon.

[[v11-1-20]]

^<<v11-1-20,20>>^ And now, my lord the king, the eyes of all Israel are upon you to tell them who will sit on the throne of my lord the king after him.

[[v11-1-21]]

^<<v11-1-21,21>>^ Otherwise, as soon as my lord the king is laid to rest with his forefathers, I and also my son Solʹo·mon will be considered traitors.”

[[v11-1-22]]

^<<v11-1-22,22>>^ And while she was still speaking to the king, Nathan the prophet came in.

[[v11-1-23]]

^<<v11-1-23,23>>^ At once the king was told: “Here is Nathan the prophet!” He came in before the king and prostrated himself to the king with his face to the ground.

[[v11-1-24]]

^<<v11-1-24,24>>^ Then Nathan said: “My lord the king, did you say, ‘Ad·o·niʹjah will become king after me, and he is the one who will sit on my throne’?

[[v11-1-25]]

^<<v11-1-25,25>>^ For today he has gone down to sacrifice bulls, fattened animals, and sheep in great quantity, and he has invited all the sons of the king and the chiefs of the army and A·biʹa·thar the priest. They are there eating and drinking with him, and they keep saying, ‘Long live King Ad·o·niʹjah!’

[[v11-1-26]]

^<<v11-1-26,26>>^ But he did not invite me, your servant, or Zaʹdok the priest, or Be·naiʹah the son of Je·hoiʹa·da, or your servant Solʹo·mon.

[[v11-1-27]]

^<<v11-1-27,27>>^ Has my lord the king authorized this without telling your servant who should sit on the throne of my lord the king after him?”

[[v11-1-28]]

^<<v11-1-28,28>>^ King David now answered: “Call Bath-sheʹba for me.” At that she came in and stood before the king.

[[v11-1-29]]

^<<v11-1-29,29>>^ The king then swore an oath: “As surely as Jehovah is living, the one who rescued me^&#42;1^ out of all distress,

[NOTE]
====
. Or “redeemed my soul.”
====

[[v11-1-30]]

^<<v11-1-30,30>>^ just as I swore to you by Jehovah the God of Israel, saying, ‘Your son Solʹo·mon will become king after me, and he is the one who will sit on my throne in my place!’ that is what I will bring about this day.”

[[v11-1-31]]

^<<v11-1-31,31>>^ Then Bath-sheʹba bowed low with her face to the ground and prostrated herself to the king and said: “May my lord King David live forever!”

[[v11-1-32]]

^<<v11-1-32,32>>^ Immediately King David said: “Call for me Zaʹdok the priest, Nathan the prophet, and Be·naiʹah the son of Je·hoiʹa·da.” So they came in before the king.

[[v11-1-33]]

^<<v11-1-33,33>>^ The king said to them: “Take with you the servants of your lord, and have my son Solʹo·mon ride on my own mule,^&#42;1^ and lead him down to Giʹhon.

[NOTE]
====
. Or “she-mule.”
====

[[v11-1-34]]

^<<v11-1-34,34>>^ Zaʹdok the priest and Nathan the prophet will anoint him there as king over Israel; then blow the horn and say, ‘Long live King Solʹo·mon!’

[[v11-1-35]]

^<<v11-1-35,35>>^ Then follow him back, and he will come in and sit on my throne; and he will be king in my place, and I will commission him as leader over Israel and over Judah.”

[[v11-1-36]]

^<<v11-1-36,36>>^ At once Be·naiʹah the son of Je·hoiʹa·da said to the king: “Amen! May Jehovah the God of my lord the king confirm it.

[[v11-1-37]]

^<<v11-1-37,37>>^ Just as Jehovah was with my lord the king, so let him be with Solʹo·mon, and may He make his throne greater than the throne of my lord King David.”

[[v11-1-38]]

^<<v11-1-38,38>>^ Then Zaʹdok the priest, Nathan the prophet, Be·naiʹah the son of Je·hoiʹa·da, and the Cherʹe·thites and the Pelʹe·thites went down and had Solʹo·mon ride on the mule of King David, and they brought him to Giʹhon.

[[v11-1-39]]

^<<v11-1-39,39>>^ Zaʹdok the priest now took the horn of oil out of the tent and anointed Solʹo·mon, and they began to blow the horn, and all the people began shouting: “Long live King Solʹo·mon!”

[[v11-1-40]]

^<<v11-1-40,40>>^ After that all the people followed him and went up, playing flutes and rejoicing greatly, so that the earth was split open by their noise.

[[v11-1-41]]

^<<v11-1-41,41>>^ Ad·o·niʹjah and all those invited by him heard it when they had finished eating. As soon as Joʹab heard the sound of the horn, he said: “Why is there such a noisy uproar in the city?”

[[v11-1-42]]

^<<v11-1-42,42>>^ While he was still speaking, Jonʹa·than the son of A·biʹa·thar the priest came. Then Ad·o·niʹjah said: “Come in, for you are a good^&#42;1^ man, and you must bring good news.”

[NOTE]
====
. Or “worthy.”
====

[[v11-1-43]]

^<<v11-1-43,43>>^ But Jonʹa·than answered Ad·o·niʹjah: “No! Our lord King David has made Solʹo·mon king.

[[v11-1-44]]

^<<v11-1-44,44>>^ The king sent with him Zaʹdok the priest, Nathan the prophet, Be·naiʹah the son of Je·hoiʹa·da, and the Cherʹe·thites and the Pelʹe·thites, and they had him ride on the mule of the king.

[[v11-1-45]]

^<<v11-1-45,45>>^ Then Zaʹdok the priest and Nathan the prophet anointed him as king in Giʹhon. After that they came up from there rejoicing, and the city is in an uproar. That was the noise that you heard.

[[v11-1-46]]

^<<v11-1-46,46>>^ Moreover, Solʹo·mon has sat down on the royal throne.

[[v11-1-47]]

^<<v11-1-47,47>>^ Another thing, the servants of the king have come in to congratulate our lord King David, saying, ‘May your God make Solʹo·mon’s name more splendid than your name, and may He make his throne greater than your throne!’ At that the king bowed down on the bed.

[[v11-1-48]]

^<<v11-1-48,48>>^ And the king also said, ‘May Jehovah the God of Israel be praised, who today has granted someone to sit on my throne and has allowed my own eyes to see it!’”

[[v11-1-49]]

^<<v11-1-49,49>>^ And all those invited by Ad·o·niʹjah became terrified, and each of them rose up and went his own way.

[[v11-1-50]]

^<<v11-1-50,50>>^ Ad·o·niʹjah was also afraid because of Solʹo·mon, so he got up and went and grabbed hold of the horns of the altar.

[[v11-1-51]]

^<<v11-1-51,51>>^ The report was made to Solʹo·mon: “Here Ad·o·niʹjah has become afraid of King Solʹo·mon; and he has taken hold of the horns of the altar, saying, ‘Let King Solʹo·mon first swear to me that he will not put his servant to death by the sword.’”

[[v11-1-52]]

^<<v11-1-52,52>>^ To this Solʹo·mon said: “If he behaves in a worthy manner, not a single hair of his will fall to the ground; but if what is bad is found in him, he will have to die.”

[[v11-1-53]]

^<<v11-1-53,53>>^ So King Solʹo·mon sent for him to be brought down from the altar. Then he came in and bowed down to King Solʹo·mon, after which Solʹo·mon said to him: “Go to your own house.”

'''

xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[&#60; Capítulo Anterior] | <<v11-1-0,Topo>> | xref:011-1-kings/011-1-kings-002.adoc#v11-2-0[Próximo Capítulo &#62;]