include::./index.adoc[]

[[v15-4-0]]
=== Ezra, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v15-4-1]]

^<<v15-4-1,1>>^ When the enemies of Judah and Benjamin heard that the returned exiles were building a temple to Jehovah the God of Israel,

[[v15-4-2]]

^<<v15-4-2,2>>^ they immediately approached Ze·rubʹba·bel and the heads of the paternal houses and said to them: “Let us build along with you; for like you, we worship^&#42;1^ your God and we have been sacrificing to him since the days of King Eʹsar-hadʹdon of As·syrʹi·a, who brought us here.”

[NOTE]
====
. Lit., “search for.”
====

[[v15-4-3]]

^<<v15-4-3,3>>^ However, Ze·rubʹba·bel and Jeshʹu·a and the rest of the heads of the paternal houses of Israel said to them: “You have no share with us in building a house to our God, for we alone will build it to Jehovah the God of Israel, just as King Cyrus the king of Persia has commanded us.”

[[v15-4-4]]

^<<v15-4-4,4>>^ Then the people of the land were continually discouraging^&#42;1^ the people of Judah and disheartening them from building.

[NOTE]
====
. Lit., “weakening the hands of.”
====

[[v15-4-5]]

^<<v15-4-5,5>>^ They hired advisers against them to frustrate their plans all the days of King Cyrus of Persia until the reign of King Da·riʹus of Persia.

[[v15-4-6]]

^<<v15-4-6,6>>^ At the beginning of the reign of A·has·u·eʹrus, they wrote an accusation against the inhabitants of Judah and Jerusalem.

[[v15-4-7]]

^<<v15-4-7,7>>^ And in the days of King Ar·ta·xerxʹes of Persia, Bishʹlam, Mithʹre·dath, Tabʹe·el, and the rest of his colleagues wrote to Ar·ta·xerxʹes the king; they translated the letter into Ar·a·maʹic, writing it with Ar·a·maʹic characters.^&#42;1^

[NOTE]
====
. Or possibly, “it was written in Aramaic and then translated.”
====

[[v15-4-8]]

^<<v15-4-8,8>>^ ^&#42;1^ Reʹhum the chief government official and Shimʹshai the scribe wrote a letter against Jerusalem to King Ar·ta·xerxʹes, as follows:

[NOTE]
====
. Ezr 4:8 through 6:18 was originally written in Aramaic.
====

[[v15-4-9]]

^<<v15-4-9,9>>^ (It was from Reʹhum the chief government official and Shimʹshai the scribe and the rest of their colleagues, the judges and the lesser governors, the secretaries, the people of Eʹrech, the Babylonians, the inhabitants of Suʹsa, that is, the Eʹlam·ites,

[[v15-4-10]]

^<<v15-4-10,10>>^ and the rest of the nations that the great and honorable Asʹe·nap·par took into exile and settled in the cities of Sa·marʹi·a, and the rest in the region Beyond the River,^&#42;1^ and now

[NOTE]
====
. Or “in Trans-Euphrates.”
====

[[v15-4-11]]

^<<v15-4-11,11>>^ this is a copy of the letter that they sent him.)
“To King Ar·ta·xerxʹes from your servants, the men of the region Beyond the River: And now

[[v15-4-12]]

^<<v15-4-12,12>>^ let it be known to the king that the Jews who came up here from you to us have arrived at Jerusalem. They are rebuilding the rebellious and wicked city, and they are finishing the walls and repairing the foundations.

[[v15-4-13]]

^<<v15-4-13,13>>^ Now let it be known to the king that if this city should be rebuilt and its walls finished, they will not give tax, tribute, or toll, and it will result in a loss to the treasuries of the kings.

[[v15-4-14]]

^<<v15-4-14,14>>^ Since we eat the salt of the palace^&#42;1^ and it is not proper for us to see the king’s interests harmed, we have therefore sent to make this known to the king,

[NOTE]
====
. Or “we receive our salary from the palace.”
====

[[v15-4-15]]

^<<v15-4-15,15>>^ so that there may be an investigation of the book of records of your ancestors. You will find in the book of records and learn that this city is a rebellious city, injurious to kings and provinces,^&#42;1^ and within it have been those stirring up sedition from ancient times. That is why this city was destroyed.

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v15-4-16]]

^<<v15-4-16,16>>^ We are making known to the king that if this city is rebuilt and its walls are finished, you will have no control^&#42;1^ of the region Beyond the River.”

[NOTE]
====
. Lit., “share.”
====

[[v15-4-17]]

^<<v15-4-17,17>>^ The king sent word to Reʹhum the chief government official and Shimʹshai the scribe and the rest of their colleagues who were dwelling in Sa·marʹi·a and the rest of the region Beyond the River:
“Greetings! And now

[[v15-4-18]]

^<<v15-4-18,18>>^ the official document that you sent us has been clearly read^&#42;1^ before me.

[NOTE]
====
. Or possibly, “has been translated and read.”
====

[[v15-4-19]]

^<<v15-4-19,19>>^ By my order an investigation was made, and it was found that from long ago the city has had uprisings against kings, and rebellions and revolts have taken place there.

[[v15-4-20]]

^<<v15-4-20,20>>^ There were powerful kings over Jerusalem who ruled the whole region Beyond the River, and tax, tribute, and toll were paid to them.

[[v15-4-21]]

^<<v15-4-21,21>>^ Now issue an order for these men to stop work, so that the city may not be rebuilt until I issue an order.

[[v15-4-22]]

^<<v15-4-22,22>>^ Be careful not to neglect acting in this regard, so that the king’s interests are not harmed any further.”

[[v15-4-23]]

^<<v15-4-23,23>>^ Now after the copy of the official document of King Ar·ta·xerxʹes had been read before Reʹhum and Shimʹshai the scribe and their colleagues, they quickly went to Jerusalem to the Jews and used force to stop them.

[[v15-4-24]]

^<<v15-4-24,24>>^ It was then that the work on the house of God, which was in Jerusalem, came to a halt; and it remained at a standstill until the second year of the reign of King Da·riʹus of Persia.

'''

xref:015-ezra/015-ezra-003.adoc#v15-3-0[&#60; Capítulo Anterior] | <<v15-4-0,Topo>> | xref:015-ezra/015-ezra-005.adoc#v15-5-0[Próximo Capítulo &#62;]