include::./index.adoc[]

[[v15-10-0]]
=== Ezra, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v15-10-1]]

^<<v15-10-1,1>>^ While Ezʹra was praying and making confession, weeping and lying prostrate before the house of the true God, a large crowd of men, women, and children of Israel gathered around him, for the people were weeping profusely.

[[v15-10-2]]

^<<v15-10-2,2>>^ Then Shec·a·niʹah the son of Je·hiʹel of the sons of Eʹlam said to Ezʹra: “We have acted unfaithfully against our God by marrying^&#42;1^ foreign women from the peoples of the land. Despite this, there is still hope for Israel.

[NOTE]
====
. Or “by taking into our houses.”
====

[[v15-10-3]]

^<<v15-10-3,3>>^ Now let us make a covenant with our God to send away all the wives and those born from them, in harmony with the direction of Jehovah and of those who have reverence for^&#42;1^ the commandment of our God. Let us act according to the Law.

[NOTE]
====
. Lit., “who tremble at.”
====

[[v15-10-4]]

^<<v15-10-4,4>>^ Get up, for this matter is your responsibility, and we are with you. Be strong and take action.”

[[v15-10-5]]

^<<v15-10-5,5>>^ At that Ezʹra rose and had the chiefs of the priests, the Levites, and all Israel take an oath to do what had been said. So they took an oath.

[[v15-10-6]]

^<<v15-10-6,6>>^ Ezʹra now got up from before the house of the true God and went to the chamber^&#42;1^ of Je·ho·haʹnan the son of E·liʹa·shib. Although he went there, he ate no food and drank no water, for he was in mourning because of the unfaithfulness of the exiled people.

[NOTE]
====
. Or “dining hall.”
====

[[v15-10-7]]

^<<v15-10-7,7>>^ Then they made a proclamation throughout Judah and Jerusalem that all the former exiles gather together at Jerusalem;

[[v15-10-8]]

^<<v15-10-8,8>>^ and according to the decision of the princes and the elders, anyone who did not come within three days’ time would have all his goods confiscated,^&#42;1^ and he would be banished from the congregation of the exiled people.

[NOTE]
====
. Or “put under ban.”
====

[[v15-10-9]]

^<<v15-10-9,9>>^ So all the men of Judah and Benjamin gathered together at Jerusalem within three days, that is, in the ninth month, on the 20th day of the month. All the people were sitting in a courtyard of the house of the true God, shivering because of the matter at hand and because of the heavy rain.

[[v15-10-10]]

^<<v15-10-10,10>>^ Then Ezʹra the priest rose and said to them: “You have acted unfaithfully by marrying foreign women, and so you have added to the guilt of Israel.

[[v15-10-11]]

^<<v15-10-11,11>>^ Now make confession to Jehovah the God of your forefathers and do his will. Separate yourselves from the peoples of the land and from these foreign wives.”

[[v15-10-12]]

^<<v15-10-12,12>>^ To this the whole congregation answered with a loud voice: “It is our duty to do exactly as you say.

[[v15-10-13]]

^<<v15-10-13,13>>^ However, there are many people, and it is the rainy season. It is not possible to stand outside, and the matter will not take just one or two days, for we have rebelled extensively in this matter.

[[v15-10-14]]

^<<v15-10-14,14>>^ So, please, let our princes represent the entire congregation; and let all those in our cities who have married foreign women come at an appointed time, along with the elders and judges of each city, until we turn back the burning anger of our God from us concerning this matter.”

[[v15-10-15]]

^<<v15-10-15,15>>^ However, Jonʹa·than the son of Asʹa·hel and Jah·zeiʹah the son of Tikʹvah objected to this, and the Levites Me·shulʹlam and Shabʹbe·thai supported them.

[[v15-10-16]]

^<<v15-10-16,16>>^ But the former exiles did what was agreed on; and Ezʹra the priest and the family heads of their paternal houses, all designated by name, convened separately on the first day of the tenth month to look into the matter;

[[v15-10-17]]

^<<v15-10-17,17>>^ and by the first day of the first month they finished dealing with all the men who had married foreign women.

[[v15-10-18]]

^<<v15-10-18,18>>^ And it was discovered that some of the sons of the priests had married foreign women: of the sons of Jeshʹu·a the son of Je·hozʹa·dak and his brothers, Ma·a·seiʹah, E·li·eʹzer, Jaʹrib, and Ged·a·liʹah.

[[v15-10-19]]

^<<v15-10-19,19>>^ But they promised^&#42;1^ to send their wives away, and since they were guilty, they would offer a ram of the flock for their guilt.

[NOTE]
====
. Lit., “they gave their hands.”
====

[[v15-10-20]]

^<<v15-10-20,20>>^ Of the sons of Imʹmer, there were Ha·naʹni and Zeb·a·diʹah;

[[v15-10-21]]

^<<v15-10-21,21>>^ and of the sons of Haʹrim, Ma·a·seiʹah, E·liʹjah, She·maiʹah, Je·hiʹel, and Uz·ziʹah;

[[v15-10-22]]

^<<v15-10-22,22>>^ and of the sons of Pashʹhur, Eli·o·eʹnai, Ma·a·seiʹah, Ishʹma·el, Ne·thanʹel, Joʹza·bad and El·e·aʹsah.

[[v15-10-23]]

^<<v15-10-23,23>>^ And of the Levites, there were Joʹza·bad, Shimʹe·i, Ke·laiʹah (that is, Ke·liʹta), Peth·a·hiʹah, Judah, and E·li·eʹzer;

[[v15-10-24]]

^<<v15-10-24,24>>^ and of the singers, E·liʹa·shib; and of the gatekeepers, Shalʹlum, Teʹlem, and Uʹri.

[[v15-10-25]]

^<<v15-10-25,25>>^ And of Israel, of the sons of Paʹrosh, there were Ra·miʹah, Iz·ziʹah, Mal·chiʹjah, Mijʹa·min, El·e·aʹzar, Mal·chiʹjah, and Be·naiʹah;

[[v15-10-26]]

^<<v15-10-26,26>>^ and of the sons of Eʹlam, Mat·ta·niʹah, Zech·a·riʹah, Je·hiʹel, Abʹdi, Jerʹe·moth, and E·liʹjah;

[[v15-10-27]]

^<<v15-10-27,27>>^ and of the sons of Zatʹtu, Eli·o·eʹnai, E·liʹa·shib, Mat·ta·niʹah, Jerʹe·moth, Zaʹbad, and A·ziʹza;

[[v15-10-28]]

^<<v15-10-28,28>>^ and of the sons of Beʹbai, Je·ho·haʹnan, Han·a·niʹah, Zabʹbai, and Athʹlai;

[[v15-10-29]]

^<<v15-10-29,29>>^ and of the sons of Baʹni, Me·shulʹlam, Malʹluch, A·daiʹah, Jaʹshub, Sheʹal, and Jerʹe·moth;

[[v15-10-30]]

^<<v15-10-30,30>>^ and of the sons of Paʹhath-moʹab, Adʹna, Cheʹlal, Be·naiʹah, Ma·a·seiʹah, Mat·ta·niʹah, Bezʹal·el, Binʹnu·i, and Ma·nasʹseh;

[[v15-10-31]]

^<<v15-10-31,31>>^ and of the sons of Haʹrim, E·li·eʹzer, Is·shiʹjah, Mal·chiʹjah, She·maiʹah, Shimʹe·on,

[[v15-10-32]]

^<<v15-10-32,32>>^ Benjamin, Malʹluch, and Shem·a·riʹah;

[[v15-10-33]]

^<<v15-10-33,33>>^ of the sons of Haʹshum, Mat·teʹnai, Matʹtat·tah, Zaʹbad, E·liphʹe·let, Jerʹe·mai, Ma·nasʹseh, and Shimʹe·i;

[[v15-10-34]]

^<<v15-10-34,34>>^ of the sons of Baʹni, Ma·a·daʹi, Amʹram, Uʹel,

[[v15-10-35]]

^<<v15-10-35,35>>^ Be·naiʹah, Be·deiʹah, Chelʹu·hi,

[[v15-10-36]]

^<<v15-10-36,36>>^ Va·niʹah, Merʹe·moth, E·liʹa·shib,

[[v15-10-37]]

^<<v15-10-37,37>>^ Mat·ta·niʹah, Mat·teʹnai, and Jaʹa·su;

[[v15-10-38]]

^<<v15-10-38,38>>^ and of the sons of Binʹnu·i, Shimʹe·i,

[[v15-10-39]]

^<<v15-10-39,39>>^ Shel·e·miʹah, Nathan, A·daiʹah,

[[v15-10-40]]

^<<v15-10-40,40>>^ Mach·nadʹe·bai, Shaʹshai, Shaʹrai,

[[v15-10-41]]

^<<v15-10-41,41>>^ Azʹar·el, Shel·e·miʹah, Shem·a·riʹah,

[[v15-10-42]]

^<<v15-10-42,42>>^ Shalʹlum, Am·a·riʹah, and Joseph;

[[v15-10-43]]

^<<v15-10-43,43>>^ and of the sons of Neʹbo, Je·iʹel, Mat·ti·thiʹah, Zaʹbad, Ze·biʹna, Jadʹdai, Joel, and Be·naiʹah.

[[v15-10-44]]

^<<v15-10-44,44>>^ All of these had taken foreign wives, and they sent their wives away, along with their sons.

'''

xref:015-ezra/015-ezra-009.adoc#v15-9-0[&#60; Capítulo Anterior] | <<v15-10-0,Topo>> | xref:016-nehemiah/016-nehemiah-001.adoc#v16-1-0[Próximo Capítulo &#62;]