include::./index.adoc[]

[[v15-6-0]]
=== Ezra, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v15-6-1]]

^<<v15-6-1,1>>^ It was then that King Da·riʹus issued an order, and they made an investigation in the archives^&#42;1^ where the treasures were deposited in Babylon.

[NOTE]
====
. Lit., “the house of the records.”
====

[[v15-6-2]]

^<<v15-6-2,2>>^ And a scroll was found in the citadel at Ec·batʹa·na, in the province^&#42;1^ of Meʹdi·a, and the following memorandum was written on it:

[NOTE]
====
. Or “jurisdictional district.”
====

[[v15-6-3]]

^<<v15-6-3,3>>^ “In the first year of King Cyrus, King Cyrus issued an order concerning the house of God in Jerusalem: ‘Let the house be rebuilt as the place where they are to offer sacrifices, and its foundations are to be set in place; its height is to be 60 cubits,^&#42;1^ its width 60 cubits,

[NOTE]
====
. About 26.7 m (87.6 ft). See App. B14.
====

[[v15-6-4]]

^<<v15-6-4,4>>^ with three layers of large stones rolled into place and one layer of timbers; and let the expense be paid from the king’s house.

[[v15-6-5]]

^<<v15-6-5,5>>^ Also, let the gold and silver vessels of the house of God that Neb·u·chad·nezʹzar took out of the temple that was in Jerusalem and brought to Babylon be returned, so that they may be put in their place in the temple in Jerusalem and be deposited in the house of God.’

[[v15-6-6]]

^<<v15-6-6,6>>^ “So now Tatʹte·nai the governor of the region Beyond the River,^&#42;1^ Sheʹthar-bozʹe·nai, and your colleagues, the lesser governors of the region Beyond the River—stay away from there.

[NOTE]
====
. Or “of Trans-Euphrates.”
====

[[v15-6-7]]

^<<v15-6-7,7>>^ Do not interfere with the work on that house of God. The governor of the Jews and the elders of the Jews will rebuild that house of God in its former place.

[[v15-6-8]]

^<<v15-6-8,8>>^ Furthermore, I am issuing an order as to what you are to do for these elders of the Jews for rebuilding that house of God: From the royal treasury, from the tax collected in the region Beyond the River, the expenses are to be promptly given to these men to continue without interruption.

[[v15-6-9]]

^<<v15-6-9,9>>^ And whatever is needed—young bulls as well as rams and lambs for the burnt offerings to the God of heaven, wheat, salt, wine, and oil, just as the priests who are in Jerusalem say—is to be given them continually day by day without fail,

[[v15-6-10]]

^<<v15-6-10,10>>^ so that they may continually present offerings that please the God of the heavens and pray for the life of the king and his sons.

[[v15-6-11]]

^<<v15-6-11,11>>^ I have also issued an order that if anyone violates this decree, a timber will be pulled out of his house and he will be lifted up and fastened to it,^&#42;1^ and his house will be turned into a public latrine^&#42;2^ for this offense.

[NOTE]
====
. Or “and he will be impaled on it.”
. Or possibly, “a garbage dump; a dunghill.”
====

[[v15-6-12]]

^<<v15-6-12,12>>^ And may the God who has caused his name to reside there overthrow any king and people who lift a hand to violate this order and destroy that house of God, which is in Jerusalem. I, Da·riʹus, issue this order. Let it be done promptly.”

[[v15-6-13]]

^<<v15-6-13,13>>^ Then Tatʹte·nai the governor of the region Beyond the River, Sheʹthar-bozʹe·nai, and their colleagues promptly carried out everything that King Da·riʹus had ordered.

[[v15-6-14]]

^<<v15-6-14,14>>^ And the elders of the Jews continued building and making progress, urged on by the prophesying of Hagʹgai the prophet and Zech·a·riʹah the grandson of Idʹdo; they finished building it by the order of the God of Israel and by the order of Cyrus and Da·riʹus and King Ar·ta·xerxʹes of Persia.

[[v15-6-15]]

^<<v15-6-15,15>>^ They completed the house by the third day of the month of Aʹdar,^&#42;1^ in the sixth year of the reign of King Da·riʹus.

[NOTE]
====
. See App. B15.
====

[[v15-6-16]]

^<<v15-6-16,16>>^ Then the Israelites, the priests, the Levites, and the rest of the former exiles held the inauguration^&#42;1^ of this house of God with joy.

[NOTE]
====
. Or “dedication.”
====

[[v15-6-17]]

^<<v15-6-17,17>>^ And they presented for the inauguration of this house of God 100 bulls, 200 rams, 400 lambs, and as a sin offering for all Israel 12 male goats, corresponding to the number of the tribes of Israel.

[[v15-6-18]]

^<<v15-6-18,18>>^ And they appointed the priests in their groups and the Levites in their divisions for the service of God in Jerusalem, according to what is written in the book of Moses.

[[v15-6-19]]

^<<v15-6-19,19>>^ And the former exiles held the Passover on the 14th day of the first month.

[[v15-6-20]]

^<<v15-6-20,20>>^ The priests and the Levites, without exception, had cleansed themselves, so they were all clean; they slaughtered the Passover sacrifice for all the former exiles, for their fellow priests, and for themselves.

[[v15-6-21]]

^<<v15-6-21,21>>^ Then the Israelites who had returned from the exile ate of it, along with everyone who had joined them and had separated himself from the uncleanness of the nations of the land to worship^&#42;1^ Jehovah the God of Israel.

[NOTE]
====
. Lit., “search for.”
====

[[v15-6-22]]

^<<v15-6-22,22>>^ They also joyfully held the Festival of Unleavened Bread for seven days, for Jehovah caused them to rejoice and he had made the heart of the king of As·syrʹi·a favorable toward them, so that he supported them^&#42;1^ in the work of the house of the true God, the God of Israel.

[NOTE]
====
. Lit., “strengthened their hands.”
====

'''

xref:015-ezra/015-ezra-005.adoc#v15-5-0[&#60; Capítulo Anterior] | <<v15-6-0,Topo>> | xref:015-ezra/015-ezra-007.adoc#v15-7-0[Próximo Capítulo &#62;]