include::./index.adoc[]

[[v15-3-0]]
=== Ezra, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v15-3-1]]

^<<v15-3-1,1>>^ When the seventh month arrived and the Israelites^&#42;1^ were in their cities, they gathered together with one accord in Jerusalem.

[NOTE]
====
. Lit., “sons of Israel.”
====

[[v15-3-2]]

^<<v15-3-2,2>>^ Jeshʹu·a the son of Je·hozʹa·dak and his fellow priests and Ze·rubʹba·bel the son of She·alʹti·el and his brothers rose up and built the altar of the God of Israel, so that they could offer up burnt sacrifices on it, as it is written in the Law of Moses the man of the true God.

[[v15-3-3]]

^<<v15-3-3,3>>^ So they set the altar up on its former site, despite their fear of the peoples of the surrounding lands, and they began offering up burnt sacrifices to Jehovah on it, the morning and the evening burnt sacrifices.

[[v15-3-4]]

^<<v15-3-4,4>>^ Then they held the Festival of Booths^&#42;1^ according to what is written, and day by day they offered up the specified number of burnt sacrifices that were required each day.

[NOTE]
====
. Or “Temporary Shelters.”
====

[[v15-3-5]]

^<<v15-3-5,5>>^ Afterward they offered up the regular burnt offering and the offerings for the new moons and those for all the sanctified festival seasons of Jehovah, as well as those from everyone who willingly offered a voluntary offering to Jehovah.

[[v15-3-6]]

^<<v15-3-6,6>>^ From the first day of the seventh month they started to offer up burnt sacrifices to Jehovah, though the foundation of Jehovah’s temple had not yet been laid.

[[v15-3-7]]

^<<v15-3-7,7>>^ They gave money to the stonecutters and the craftsmen, and food and drink and oil to the Si·doʹni·ans and the Tyrʹi·ans for bringing cedar timbers by sea from Lebʹa·non to Jopʹpa, according to the authorization granted them by King Cyrus of Persia.

[[v15-3-8]]

^<<v15-3-8,8>>^ In the second year after they came to the house of the true God at Jerusalem, in the second month, Ze·rubʹba·bel the son of She·alʹti·el, Jeshʹu·a the son of Je·hozʹa·dak and the rest of their brothers, the priests and the Levites, and all those who had come to Jerusalem out of the captivity started the work; they appointed the Levites from 20 years old and up to serve as supervisors over the work of the house of Jehovah.

[[v15-3-9]]

^<<v15-3-9,9>>^ So Jeshʹu·a, his sons and his brothers, and Kadʹmi·el and his sons, the sons of Judah, joined together to supervise those doing the work in the house of the true God, along with the sons of Henʹa·dad, their sons and their brothers, the Levites.

[[v15-3-10]]

^<<v15-3-10,10>>^ When the builders laid the foundation of the temple of Jehovah, then the priests in official clothing, with the trumpets, and the Levites, the sons of Aʹsaph, with the cymbals, stood up to praise Jehovah according to the direction of King David of Israel.

[[v15-3-11]]

^<<v15-3-11,11>>^ And they began to sing in response by praising and giving thanks to Jehovah, “for he is good; his loyal love toward Israel endures forever.” Then all the people shouted with a loud shout of praise to Jehovah because the foundation of the house of Jehovah had been laid.

[[v15-3-12]]

^<<v15-3-12,12>>^ Many of the priests, the Levites, and the heads of the paternal houses—the old men who had seen the former house—wept with a loud voice when they saw the foundation of this house being laid, while many others shouted joyfully at the top of their voice.

[[v15-3-13]]

^<<v15-3-13,13>>^ So the people could not distinguish the sound of the joyful shouts from the sound of the weeping, for the people were shouting so loudly that the sound was heard from a great distance.

'''

xref:015-ezra/015-ezra-002.adoc#v15-2-0[&#60; Capítulo Anterior] | <<v15-3-0,Topo>> | xref:015-ezra/015-ezra-004.adoc#v15-4-0[Próximo Capítulo &#62;]