include::./index.adoc[]

[[v15-2-0]]
=== Ezra, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v15-2-1]]

^<<v15-2-1,1>>^ And these were the people of the province^&#42;1^ who came up from the captives of the exile, those whom King Neb·u·chad·nezʹzar of Babylon had exiled to Babylon and who later returned to Jerusalem and Judah, each to his own city,

[NOTE]
====
. Or “jurisdictional district.”
====

[[v15-2-2]]

^<<v15-2-2,2>>^ those who came with Ze·rubʹba·bel, Jeshʹu·a, Ne·he·miʹah, Se·raiʹah, Re·el·aiʹah, Morʹde·cai, Bilʹshan, Misʹpar, Bigʹvai, Reʹhum, and Baʹa·nah.
The number of the Israelite men included:

[[v15-2-3]]

^<<v15-2-3,3>>^ the sons of Paʹrosh, 2,172;

[[v15-2-4]]

^<<v15-2-4,4>>^ the sons of Sheph·a·tiʹah, 372;

[[v15-2-5]]

^<<v15-2-5,5>>^ the sons of Aʹrah, 775;

[[v15-2-6]]

^<<v15-2-6,6>>^ the sons of Paʹhath-moʹab, of the sons of Jeshʹu·a and Joʹab, 2,812;

[[v15-2-7]]

^<<v15-2-7,7>>^ the sons of Eʹlam, 1,254;

[[v15-2-8]]

^<<v15-2-8,8>>^ the sons of Zatʹtu, 945;

[[v15-2-9]]

^<<v15-2-9,9>>^ the sons of Zacʹcai, 760;

[[v15-2-10]]

^<<v15-2-10,10>>^ the sons of Baʹni, 642;

[[v15-2-11]]

^<<v15-2-11,11>>^ the sons of Beʹbai, 623;

[[v15-2-12]]

^<<v15-2-12,12>>^ the sons of Azʹgad, 1,222;

[[v15-2-13]]

^<<v15-2-13,13>>^ the sons of Ad·o·niʹkam, 666;

[[v15-2-14]]

^<<v15-2-14,14>>^ the sons of Bigʹvai, 2,056;

[[v15-2-15]]

^<<v15-2-15,15>>^ the sons of Aʹdin, 454;

[[v15-2-16]]

^<<v15-2-16,16>>^ the sons of Aʹter, of Hez·e·kiʹah, 98;

[[v15-2-17]]

^<<v15-2-17,17>>^ the sons of Beʹzai, 323;

[[v15-2-18]]

^<<v15-2-18,18>>^ the sons of Joʹrah, 112;

[[v15-2-19]]

^<<v15-2-19,19>>^ the sons of Haʹshum, 223;

[[v15-2-20]]

^<<v15-2-20,20>>^ the sons of Gibʹbar, 95;

[[v15-2-21]]

^<<v15-2-21,21>>^ the sons of Bethʹle·hem, 123;

[[v15-2-22]]

^<<v15-2-22,22>>^ the men of Ne·toʹphah, 56;

[[v15-2-23]]

^<<v15-2-23,23>>^ the men of Anʹa·thoth, 128;

[[v15-2-24]]

^<<v15-2-24,24>>^ the sons of Azʹma·veth, 42;

[[v15-2-25]]

^<<v15-2-25,25>>^ the sons of Kirʹi·ath-jeʹa·rim, Che·phiʹrah, and Be·erʹoth, 743;

[[v15-2-26]]

^<<v15-2-26,26>>^ the sons of Raʹmah and Geʹba, 621;

[[v15-2-27]]

^<<v15-2-27,27>>^ the men of Michʹmas, 122;

[[v15-2-28]]

^<<v15-2-28,28>>^ the men of Bethʹel and Aʹi, 223;

[[v15-2-29]]

^<<v15-2-29,29>>^ the sons of Neʹbo, 52;

[[v15-2-30]]

^<<v15-2-30,30>>^ the sons of Magʹbish, 156;

[[v15-2-31]]

^<<v15-2-31,31>>^ the sons of the other Eʹlam, 1,254;

[[v15-2-32]]

^<<v15-2-32,32>>^ the sons of Haʹrim, 320;

[[v15-2-33]]

^<<v15-2-33,33>>^ the sons of Lod, Haʹdid, and Oʹno, 725;

[[v15-2-34]]

^<<v15-2-34,34>>^ the sons of Jerʹi·cho, 345;

[[v15-2-35]]

^<<v15-2-35,35>>^ the sons of Se·naʹah, 3,630.

[[v15-2-36]]

^<<v15-2-36,36>>^ The priests: the sons of Je·daʹiah of the house of Jeshʹu·a, 973;

[[v15-2-37]]

^<<v15-2-37,37>>^ the sons of Imʹmer, 1,052;

[[v15-2-38]]

^<<v15-2-38,38>>^ the sons of Pashʹhur, 1,247;

[[v15-2-39]]

^<<v15-2-39,39>>^ the sons of Haʹrim, 1,017.

[[v15-2-40]]

^<<v15-2-40,40>>^ The Levites: the sons of Jeshʹu·a and Kadʹmi·el, of the sons of Hod·a·viʹah, 74.

[[v15-2-41]]

^<<v15-2-41,41>>^ The singers: the sons of Aʹsaph, 128.

[[v15-2-42]]

^<<v15-2-42,42>>^ The sons of the gatekeepers: the sons of Shalʹlum, the sons of Aʹter, the sons of Talʹmon, the sons of Akʹkub, the sons of Ha·tiʹta, the sons of Shoʹbai, altogether 139.

[[v15-2-43]]

^<<v15-2-43,43>>^ The temple servants:^&#42;1^ the sons of Ziʹha, the sons of Ha·suʹpha, the sons of Tab·baʹoth,

[NOTE]
====
. Or “The Nethinim.” Lit., “The given ones.”
====

[[v15-2-44]]

^<<v15-2-44,44>>^ the sons of Keʹros, the sons of Siʹa·ha, the sons of Paʹdon,

[[v15-2-45]]

^<<v15-2-45,45>>^ the sons of Le·baʹnah, the sons of Hagʹa·bah, the sons of Akʹkub,

[[v15-2-46]]

^<<v15-2-46,46>>^ the sons of Haʹgab, the sons of Salʹmai, the sons of Haʹnan,

[[v15-2-47]]

^<<v15-2-47,47>>^ the sons of Gidʹdel, the sons of Gaʹhar, the sons of Re·aʹiah,

[[v15-2-48]]

^<<v15-2-48,48>>^ the sons of Reʹzin, the sons of Ne·koʹda, the sons of Gazʹzam,

[[v15-2-49]]

^<<v15-2-49,49>>^ the sons of Uzʹza, the sons of Pa·seʹah, the sons of Beʹsai,

[[v15-2-50]]

^<<v15-2-50,50>>^ the sons of Asʹnah, the sons of Me·uʹnim, the sons of Ne·phuʹsim,

[[v15-2-51]]

^<<v15-2-51,51>>^ the sons of Bakʹbuk, the sons of Ha·kuʹpha, the sons of Harʹhur,

[[v15-2-52]]

^<<v15-2-52,52>>^ the sons of Bazʹluth, the sons of Me·hiʹda, the sons of Harʹsha,

[[v15-2-53]]

^<<v15-2-53,53>>^ the sons of Barʹkos, the sons of Sisʹe·ra, the sons of Teʹmah,

[[v15-2-54]]

^<<v15-2-54,54>>^ the sons of Ne·ziʹah, the sons of Ha·tiʹpha.

[[v15-2-55]]

^<<v15-2-55,55>>^ The sons of the servants of Solʹo·mon: the sons of Soʹtai, the sons of So·pheʹreth, the sons of Pe·ruʹda,

[[v15-2-56]]

^<<v15-2-56,56>>^ the sons of Jaʹa·lah, the sons of Darʹkon, the sons of Gidʹdel,

[[v15-2-57]]

^<<v15-2-57,57>>^ the sons of Sheph·a·tiʹah, the sons of Hatʹtil, the sons of Poʹche·reth-haz·ze·baʹim, the sons of Aʹmi.

[[v15-2-58]]

^<<v15-2-58,58>>^ All the temple servants^&#42;1^ and the sons of the servants of Solʹo·mon were 392.

[NOTE]
====
. Or “the Nethinim.” Lit., “the given ones.”
====

[[v15-2-59]]

^<<v15-2-59,59>>^ And these went up from Tel-meʹlah, Tel-harʹsha, Cheʹrub, Adʹdon, and Imʹmer, but they were unable to verify their paternal house and their origin, as to whether they were Israelites:

[[v15-2-60]]

^<<v15-2-60,60>>^ the sons of De·laʹiah, the sons of To·biʹah, the sons of Ne·koʹda, 652.

[[v15-2-61]]

^<<v15-2-61,61>>^ And of the sons of the priests: the sons of Ha·baiʹah, the sons of Hakʹkoz, the sons of Bar·zilʹlai, who took a wife from the daughters of Bar·zilʹlai the Gilʹe·ad·ite and was called by their name.

[[v15-2-62]]

^<<v15-2-62,62>>^ These looked for their records to establish their genealogy, but they did not find them, so they were disqualified from the priesthood.^&#42;1^

[NOTE]
====
. Or “were excluded from the priesthood as unclean.”
====

[[v15-2-63]]

^<<v15-2-63,63>>^ The governor^&#42;1^ told them that they could not eat from the most holy things until there was a priest who could consult the Uʹrim and Thumʹmim.

[NOTE]
====
. Or “The Tirshatha,” a Persian title for a governor of a province.
====

[[v15-2-64]]

^<<v15-2-64,64>>^ The total number of the entire congregation was 42,360,

[[v15-2-65]]

^<<v15-2-65,65>>^ apart from their male and female slaves, who were 7,337; they also had 200 male and female singers.

[[v15-2-66]]

^<<v15-2-66,66>>^ Their horses were 736, their mules 245,

[[v15-2-67]]

^<<v15-2-67,67>>^ their camels 435, their donkeys 6,720.

[[v15-2-68]]

^<<v15-2-68,68>>^ When they arrived at the house of Jehovah in Jerusalem, some of the heads of the paternal houses made voluntary offerings for the house of the true God, to rebuild it^&#42;1^ on its own site.

[NOTE]
====
. Or “make it stand.”
====

[[v15-2-69]]

^<<v15-2-69,69>>^ According to their means, they gave to the project treasury 61,000 gold drachmas,^&#42;1^ 5,000 silver miʹnas,^&#42;2^ and 100 robes for the priests.

[NOTE]
====
. Generally equated with the Persian gold daric that weighed 8.4 g (0.27 oz t). Not the drachma of the Greek Scriptures. See App. B14.
. A mina in the Hebrew Scriptures equaled 570 g (18.35 oz t). See App. B14.
====

[[v15-2-70]]

^<<v15-2-70,70>>^ And the priests, the Levites, some of the people, the singers, the gatekeepers, and the temple servants^&#42;1^ settled in their cities, and all the rest of Israel^&#42;2^ settled in their cities.

[NOTE]
====
. Or “the Nethinim.” Lit., “the given ones.”
. Lit., “all Israel.”
====

'''

xref:015-ezra/015-ezra-001.adoc#v15-1-0[&#60; Capítulo Anterior] | <<v15-2-0,Topo>> | xref:015-ezra/015-ezra-003.adoc#v15-3-0[Próximo Capítulo &#62;]