include::./index.adoc[]

[[v15-9-0]]
=== Ezra, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v15-9-1]]

^<<v15-9-1,1>>^ And as soon as these things had been done, the princes approached me and said: “The people of Israel and the priests and the Levites have not separated themselves from the peoples of the lands and their detestable practices, those of the Caʹnaan·ites, the Hitʹtites, the Perʹiz·zites, the Jebʹu·sites, the Amʹmon·ites, the Moʹab·ites, the Egyptians, and the Amʹor·ites.

[[v15-9-2]]

^<<v15-9-2,2>>^ They have taken some of their daughters as wives for themselves and for their sons. Now they, the holy offspring,^&#42;1^ have become mingled with the peoples of the lands. The princes and the deputy rulers have been the foremost offenders in this unfaithfulness.”

[NOTE]
====
. Lit., “seed.”
====

[[v15-9-3]]

^<<v15-9-3,3>>^ Now as soon as I heard of this, I ripped apart my garment and my sleeveless coat and pulled out some of the hair of my head and my beard, and I sat down in shock.

[[v15-9-4]]

^<<v15-9-4,4>>^ Then everyone who had reverence for^&#42;1^ the words of the God of Israel gathered around me because of the unfaithfulness of the exiled people, while I was sitting in shock until the evening grain offering.

[NOTE]
====
. Lit., “who trembled at.”
====

[[v15-9-5]]

^<<v15-9-5,5>>^ And at the time of the evening grain offering, I stood up from my humiliation, with my garment and my sleeveless coat torn apart, and I got down on my knees and spread out my hands to Jehovah my God.

[[v15-9-6]]

^<<v15-9-6,6>>^ And I said: “O my God, I feel ashamed and embarrassed to raise my face to you, O my God, for our errors have multiplied over our heads and our guilt has mounted up to the heavens.

[[v15-9-7]]

^<<v15-9-7,7>>^ From the days of our forefathers until this day our guilt has been great; and because of our errors, we, our kings, and our priests have been given into the hand of the kings of the lands, to the sword, to captivity, to plunder, and to disgrace, as is the case today.

[[v15-9-8]]

^<<v15-9-8,8>>^ But now for a brief moment, favor has come from Jehovah our God by letting a remnant escape and by giving us a secure position^&#42;1^ in his holy place, to make our eyes shine, O our God, and to revive us a little in our slavery.

[NOTE]
====
. Lit., “a peg.”
====

[[v15-9-9]]

^<<v15-9-9,9>>^ For although we are slaves, our God has not abandoned us in our slavery; but he has extended his loyal love toward us before the kings of Persia, to revive us so as to raise up the house of our God and to restore its ruins and to give us a stone wall^&#42;1^ in Judah and in Jerusalem.

[NOTE]
====
. Or “a wall of protection.”
====

[[v15-9-10]]

^<<v15-9-10,10>>^ “But now what can we say, O our God, after this? For we have left your commandments,

[[v15-9-11]]

^<<v15-9-11,11>>^ which you gave us through your servants the prophets, saying: ‘The land that you are going in to take possession of is an impure land because of the impurity of the peoples of the lands, because of their detestable practices with which they have filled it from end to end with their uncleanness.

[[v15-9-12]]

^<<v15-9-12,12>>^ Therefore, do not give your daughters to their sons, neither accept their daughters for your sons; and you must never seek their peace and their prosperity, so that you may grow strong and eat the good of the land and take possession of it for your sons forever.’

[[v15-9-13]]

^<<v15-9-13,13>>^ And after all that has come upon us for our bad deeds and our great guilt—for you, O our God, have not dealt with us according to our error, and you have allowed those of us here to escape—

[[v15-9-14]]

^<<v15-9-14,14>>^ are we to break your commandments again and form marriage alliances^&#42;1^ with the peoples who practice these detestable things? Would you not become so angry with us that you would completely destroy us, leaving no remnant or survivor?

[NOTE]
====
. Or “and intermarry.”
====

[[v15-9-15]]

^<<v15-9-15,15>>^ O Jehovah the God of Israel, you are righteous, for we have survived as a remnant to this day. Here we are before you in our guilt, for it is impossible to stand before you because of this.”

'''

xref:015-ezra/015-ezra-008.adoc#v15-8-0[&#60; Capítulo Anterior] | <<v15-9-0,Topo>> | xref:015-ezra/015-ezra-010.adoc#v15-10-0[Próximo Capítulo &#62;]