include::./index.adoc[]

[[v65-1-0]]
=== The Letter of Jude, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v65-1-1]]

^<<v65-1-1,1>>^ Jude, a slave of Jesus Christ, but a brother of James, to the called ones who are loved by God the Father and preserved for Jesus Christ:

[[v65-1-2]]

^<<v65-1-2,2>>^ May mercy and peace and love be increased to you.

[[v65-1-3]]

^<<v65-1-3,3>>^ Beloved ones, although I was making every effort to write you about the salvation we hold in common, I found it necessary to write you to urge you to put up a hard fight for the faith that was once for all time delivered to the holy ones.

[[v65-1-4]]

^<<v65-1-4,4>>^ My reason is that certain men have slipped in among you who were long ago appointed to this judgment by the Scriptures; they are ungodly men who turn the undeserved kindness of our God into an excuse for brazen conduct^&#42;1^ and who prove false to our only owner^&#42;2^ and Lord, Jesus Christ.

[NOTE]
====
. Or “shameless conduct.” Greek, a·selʹgei·a. See Glossary.
. Or “master.”
====

[[v65-1-5]]

^<<v65-1-5,5>>^ Although you are fully aware of all of this, I want to remind you that Jehovah,^&#42;1^ having saved a people out of the land of Egypt, afterward destroyed those not showing faith.

[NOTE]
====
. See App. A5.
====

[[v65-1-6]]

^<<v65-1-6,6>>^ And the angels who did not keep their original position but forsook their own proper dwelling place, he has reserved with eternal bonds in dense darkness for the judgment of the great day.

[[v65-1-7]]

^<<v65-1-7,7>>^ In the same manner, Sodʹom and Go·morʹrah and the cities around them also gave themselves over to gross sexual immorality^&#42;1^ and pursued unnatural fleshly desires; they are placed before us as a warning example by undergoing the judicial punishment of everlasting fire.

[NOTE]
====
. See Glossary.
====

[[v65-1-8]]

^<<v65-1-8,8>>^ Despite this, these men too are indulging in dreams, defiling the flesh, despising authority, and speaking abusively of glorious ones.

[[v65-1-9]]

^<<v65-1-9,9>>^ But when Miʹcha·el the archangel had a difference with the Devil and was disputing about Moses’ body, he did not dare to bring a judgment against him in abusive terms, but said: “May Jehovah^&#42;1^ rebuke you.”

[NOTE]
====
. See App. A5.
====

[[v65-1-10]]

^<<v65-1-10,10>>^ But these men are speaking abusively about all the things they really do not understand. And in all the things that they do understand by instinct like unreasoning animals, they go on corrupting themselves.

[[v65-1-11]]

^<<v65-1-11,11>>^ Too bad for them, for they have followed the path of Cain and have rushed into the erroneous course of Baʹlaam for reward, and they have perished in the rebellious talk of Korʹah!

[[v65-1-12]]

^<<v65-1-12,12>>^ These are the rocks hidden below water at your love feasts while they feast with you, shepherds who feed themselves without fear; waterless clouds carried here and there by the wind; fruitless trees in late autumn, having died twice^&#42;1^ and having been uprooted;

[NOTE]
====
. Or “being completely dead.”
====

[[v65-1-13]]

^<<v65-1-13,13>>^ wild waves of the sea that cast up the foam of their own shame; stars with no set course, for which the blackest darkness stands reserved forever.

[[v65-1-14]]

^<<v65-1-14,14>>^ Yes, the seventh one in line from Adam, Eʹnoch, also prophesied about them when he said: “Look! Jehovah^&#42;1^ came with his holy myriads^&#42;2^

[NOTE]
====
. See App. A5.
. Or “tens of thousands.”
====

[[v65-1-15]]

^<<v65-1-15,15>>^ to execute judgment against all, and to convict all the ungodly concerning all their ungodly deeds that they did in an ungodly way, and concerning all the shocking things that ungodly sinners spoke against him.”

[[v65-1-16]]

^<<v65-1-16,16>>^ These men are murmurers, complainers about their lot in life, following their own desires, and their mouths make grandiose boasts, while they are flattering others^&#42;1^ for their own benefit.

[NOTE]
====
. Or “admiring personalities.”
====

[[v65-1-17]]

^<<v65-1-17,17>>^ As for you, beloved ones, call to mind the sayings that have been previously spoken^&#42;1^ by the apostles of our Lord Jesus Christ,

[NOTE]
====
. Or “the things foretold.”
====

[[v65-1-18]]

^<<v65-1-18,18>>^ how they used to say to you: “In the last time there will be ridiculers, following their own desires for ungodly things.”

[[v65-1-19]]

^<<v65-1-19,19>>^ These are the ones who cause divisions, animalistic men,^&#42;1^ not having spirituality.^&#42;2^

[NOTE]
====
. Or “physical men.”
. Lit., “the spirit.”
====

[[v65-1-20]]

^<<v65-1-20,20>>^ But you, beloved ones, build yourselves up on your most holy faith, and pray with holy spirit,

[[v65-1-21]]

^<<v65-1-21,21>>^ in order to keep yourselves in God’s love, while you await the mercy of our Lord Jesus Christ with everlasting life in view.

[[v65-1-22]]

^<<v65-1-22,22>>^ Also, continue showing mercy to some who have doubts;

[[v65-1-23]]

^<<v65-1-23,23>>^ save them by snatching them out of the fire. But continue showing mercy to others, doing so with fear, while you hate even the garment that has been stained by the flesh.

[[v65-1-24]]

^<<v65-1-24,24>>^ Now to the one who is able to guard you from stumbling and to make you stand unblemished in the sight of his glory^&#42;1^ with great joy,

[NOTE]
====
. Or “in his glorious presence.”
====

[[v65-1-25]]

^<<v65-1-25,25>>^ to the only God our Savior through Jesus Christ our Lord, be glory, majesty, might, and authority for all past eternity and now and into all eternity. Amen.

'''

xref:064-3-john/064-3-john-001.adoc#v64-1-0[&#60; Capítulo Anterior] | <<v65-1-0,Topo>> | xref:066-revelation/066-revelation-001.adoc#v66-1-0[Próximo Capítulo &#62;]