include::./index.adoc[]

[[v4-10-0]]
=== Numbers, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-10-1]]

^<<v4-10-1,1>>^ Jehovah then said to Moses:

[[v4-10-2]]

^<<v4-10-2,2>>^ “Make two trumpets for yourself; make them of hammered silver, and use them to summon the assembly and to break up the camps.

[[v4-10-3]]

^<<v4-10-3,3>>^ When both of them are blown, the whole assembly must be summoned to you at the entrance of the tent of meeting.

[[v4-10-4]]

^<<v4-10-4,4>>^ If just one is blown, only the chieftains, the heads of the thousands of Israel, will be summoned to you.

[[v4-10-5]]

^<<v4-10-5,5>>^ “When you sound a fluctuating trumpet blast, the camps of those to the east should depart.

[[v4-10-6]]

^<<v4-10-6,6>>^ When you sound a fluctuating trumpet blast a second time, the camps of those to the south should depart. They should sound the trumpet blasts in this way each time one of them departs.

[[v4-10-7]]

^<<v4-10-7,7>>^ “Now when calling the congregation together, you should blow the trumpets, but not with fluctuating blasts.

[[v4-10-8]]

^<<v4-10-8,8>>^ Aaron’s sons, the priests, should blow the trumpets, and the use of them will serve as a lasting statute for you throughout your generations.

[[v4-10-9]]

^<<v4-10-9,9>>^ “If you should go to war in your land against an oppressor who is harassing you, you should sound a war call on the trumpets, and you will be remembered by Jehovah your God and be saved from your enemies.

[[v4-10-10]]

^<<v4-10-10,10>>^ “Also, on your joyous occasions—your festivals and at the beginning of your months—you are to sound the trumpets over your burnt offerings and your communion sacrifices; they will serve as a reminder for you before your God. I am Jehovah your God.”

[[v4-10-11]]

^<<v4-10-11,11>>^ Now in the second year, in the second month, on the 20th day of the month, the cloud lifted from over the tabernacle of the Testimony.

[[v4-10-12]]

^<<v4-10-12,12>>^ So the Israelites began to pull away from the wilderness of Siʹnai in the order established for their departure, and the cloud settled in the wilderness of Paʹran.

[[v4-10-13]]

^<<v4-10-13,13>>^ This was the first time they departed following the order of Jehovah through Moses.

[[v4-10-14]]

^<<v4-10-14,14>>^ So the three-tribe division of the camp of the sons of Judah departed first by their companies,^&#42;1^ and Nahʹshon the son of Am·minʹa·dab was over its company.

[NOTE]
====
. Lit., “according to their armies.”
====

[[v4-10-15]]

^<<v4-10-15,15>>^ Over the company of the tribe of the sons of Isʹsa·char was Ne·thanʹel the son of Zuʹar.

[[v4-10-16]]

^<<v4-10-16,16>>^ Over the company of the tribe of the sons of Zebʹu·lun was E·liʹab the son of Heʹlon.

[[v4-10-17]]

^<<v4-10-17,17>>^ When the tabernacle was taken down, the sons of Gerʹshon and the sons of Me·rarʹi, who carried the tabernacle, departed.

[[v4-10-18]]

^<<v4-10-18,18>>^ Then the three-tribe division of the camp of Reuʹben departed by their companies,^&#42;1^ and E·liʹzur the son of Shedʹe·ur was over its company.

[NOTE]
====
. Lit., “according to their armies.”
====

[[v4-10-19]]

^<<v4-10-19,19>>^ Over the company of the tribe of the sons of Simʹe·on was She·luʹmi·el the son of Zu·ri·shadʹdai.

[[v4-10-20]]

^<<v4-10-20,20>>^ Over the company of the tribe of the sons of Gad was E·liʹa·saph the son of Deuʹel.

[[v4-10-21]]

^<<v4-10-21,21>>^ Then the Koʹhath·ites, who carried the sanctuary items, departed. The tabernacle was to be set up by the time they arrived.

[[v4-10-22]]

^<<v4-10-22,22>>^ Then the three-tribe division of the camp of the sons of Eʹphra·im departed by their companies,^&#42;1^ and E·lishʹa·ma the son of Am·miʹhud was over its company.

[NOTE]
====
. Lit., “according to their armies.”
====

[[v4-10-23]]

^<<v4-10-23,23>>^ Over the company of the tribe of the sons of Ma·nasʹseh was Ga·maʹli·el the son of Pe·dahʹzur.

[[v4-10-24]]

^<<v4-10-24,24>>^ Over the company of the tribe of the sons of Benjamin was Abʹi·dan the son of Gid·e·oʹni.

[[v4-10-25]]

^<<v4-10-25,25>>^ Then the three-tribe division of the camp of the sons of Dan departed by their companies,^&#42;1^ forming the rear guard for all the camps, and A·hi·eʹzer the son of Am·mi·shadʹdai was over its company.

[NOTE]
====
. Lit., “according to their armies.”
====

[[v4-10-26]]

^<<v4-10-26,26>>^ Over the company of the tribe of the sons of Ashʹer was Paʹgi·el the son of Ochʹran.

[[v4-10-27]]

^<<v4-10-27,27>>^ Over the company of the tribe of the sons of Naphʹta·li was A·hiʹra the son of Eʹnan.

[[v4-10-28]]

^<<v4-10-28,28>>^ This was the order of departure that the Israelites and their companies^&#42;1^ followed when they would depart.

[NOTE]
====
. Lit., “according to their armies.”
====

[[v4-10-29]]

^<<v4-10-29,29>>^ Then Moses said to Hoʹbab the son of Reuʹel^&#42;1^ the Midʹi·an·ite, the father-in-law of Moses: “We are setting out for the place about which Jehovah said, ‘I will give it to you.’ Do come with us, and we will treat you well, because Jehovah has promised good things for Israel.”

[NOTE]
====
. That is, Jethro.
====

[[v4-10-30]]

^<<v4-10-30,30>>^ But he said to him: “I will not go. I will return to my own country and to my relatives.”

[[v4-10-31]]

^<<v4-10-31,31>>^ At this he said: “Please do not leave us, for you know where we should camp in the wilderness, and you can serve as our guide.^&#42;1^

[NOTE]
====
. Or “eyes.”
====

[[v4-10-32]]

^<<v4-10-32,32>>^ And if you do come with us, whatever goodness Jehovah shows to us, we will surely show to you.”

[[v4-10-33]]

^<<v4-10-33,33>>^ So they began marching from the mountain of Jehovah for a journey of three days, and the ark of Jehovah’s covenant traveled before them for the three-day journey to search out a resting-place for them.

[[v4-10-34]]

^<<v4-10-34,34>>^ And Jehovah’s cloud was over them by day when they set out from the encampment.

[[v4-10-35]]

^<<v4-10-35,35>>^ Whenever the Ark was moved, Moses would say: “Rise up, O Jehovah, and let your enemies be scattered, and let those who hate you flee from before you.”

[[v4-10-36]]

^<<v4-10-36,36>>^ And when it would rest, he would say: “Do return, O Jehovah, to the countless^&#42;1^ thousands of Israel.”

[NOTE]
====
. Or “myriads of.”
====

'''

xref:004-numbers/004-numbers-009.adoc#v4-9-0[&#60; Capítulo Anterior] | <<v4-10-0,Topo>> | xref:004-numbers/004-numbers-011.adoc#v4-11-0[Próximo Capítulo &#62;]