include::./index.adoc[]

[[v4-22-0]]
=== Numbers, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-22-1]]

^<<v4-22-1,1>>^ Then the Israelites departed and camped on the desert plains of Moʹab across the Jordan from Jerʹi·cho.

[[v4-22-2]]

^<<v4-22-2,2>>^ Now Baʹlak the son of Zipʹpor saw all that Israel had done to the Amʹor·ites,

[[v4-22-3]]

^<<v4-22-3,3>>^ and Moʹab became very frightened of the people, because they were so many; indeed, Moʹab felt sick with fear because of the Israelites.

[[v4-22-4]]

^<<v4-22-4,4>>^ So Moʹab said to the elders of Midʹi·an: “Now this congregation will devour all our surroundings, just as a bull devours the grass in the field.”
Baʹlak the son of Zipʹpor was king of Moʹab at that time.

[[v4-22-5]]

^<<v4-22-5,5>>^ He sent messengers to Baʹlaam the son of Beʹor at Peʹthor, which is by the River^&#42;1^ in his native land. He summoned him, saying: “Look! A people has come out of Egypt. Look! They have covered the face^&#42;2^ of the earth,^&#42;3^ and they are dwelling right in front of me.

[NOTE]
====
. Evidently, the Euphrates.
. Lit., “eye.”
. Or “land.”
====

[[v4-22-6]]

^<<v4-22-6,6>>^ Now, please, come and curse this people for me, for they are mightier than I am. Perhaps I can defeat them and drive them out of the land, for I well know that the one whom you bless is blessed and the one whom you curse is cursed.”

[[v4-22-7]]

^<<v4-22-7,7>>^ So the elders of Moʹab and the elders of Midʹi·an traveled with the fee for divination in their hands and went to Baʹlaam and conveyed to him Baʹlak’s message.

[[v4-22-8]]

^<<v4-22-8,8>>^ At that he said to them: “Spend the night here, and I will bring back to you whatever word Jehovah speaks to me.” So the princes of Moʹab stayed with Baʹlaam.

[[v4-22-9]]

^<<v4-22-9,9>>^ Then God came to Baʹlaam and said: “Who are these men with you?”

[[v4-22-10]]

^<<v4-22-10,10>>^ Baʹlaam said to the true God: “Baʹlak the son of Zipʹpor, the king of Moʹab, has sent me a message, saying,

[[v4-22-11]]

^<<v4-22-11,11>>^ ‘Look! The people who are coming out of Egypt are covering the face^&#42;1^ of the earth.^&#42;2^ Now come and put a curse on them for me. Perhaps I may be able to fight against them and drive them out.’”

[NOTE]
====
. Lit., “eye.”
. Or “land.”
====

[[v4-22-12]]

^<<v4-22-12,12>>^ But God said to Baʹlaam: “You must not go with them. You must not curse the people, for they are blessed.”

[[v4-22-13]]

^<<v4-22-13,13>>^ Baʹlaam got up in the morning and said to the princes of Baʹlak: “Go to your land, for Jehovah has refused to let me go with you.”

[[v4-22-14]]

^<<v4-22-14,14>>^ So the princes of Moʹab departed and returned to Baʹlak and said: “Baʹlaam has refused to come with us.”

[[v4-22-15]]

^<<v4-22-15,15>>^ However, Baʹlak again sent princes, more numerous and more distinguished than the first group.

[[v4-22-16]]

^<<v4-22-16,16>>^ They came to Baʹlaam and said to him: “This is what Baʹlak the son of Zipʹpor has said, ‘Please do not let anything hinder you from coming to me,

[[v4-22-17]]

^<<v4-22-17,17>>^ for I will honor you greatly and I will do anything you tell me to do. So come, please, and curse this people for me.’”

[[v4-22-18]]

^<<v4-22-18,18>>^ But Baʹlaam answered the servants of Baʹlak: “If Baʹlak were to give me his own house full of silver and gold, I could not do anything beyond the order of Jehovah my God, whether small or great.

[[v4-22-19]]

^<<v4-22-19,19>>^ But please stay here tonight also, so that I may learn what else Jehovah will tell me.”

[[v4-22-20]]

^<<v4-22-20,20>>^ Then God came to Baʹlaam by night and said to him: “If these men have come to summon you, go along with them. But you may speak only the words that I tell you to say.”

[[v4-22-21]]

^<<v4-22-21,21>>^ So Baʹlaam got up in the morning and saddled his donkey^&#42;1^ and went with the princes of Moʹab.

[NOTE]
====
. Lit., “female donkey.”
====

[[v4-22-22]]

^<<v4-22-22,22>>^ But God’s anger blazed because he was going, and Jehovah’s angel stationed himself in the road to resist him. Now Baʹlaam was riding on his donkey, and two of his attendants were with him.

[[v4-22-23]]

^<<v4-22-23,23>>^ And when the donkey saw Jehovah’s angel standing in the road with a drawn sword in his hand, it tried to turn off the road into the field. But Baʹlaam began to beat the donkey to make it return to the road.

[[v4-22-24]]

^<<v4-22-24,24>>^ Then Jehovah’s angel stood in a narrow path between two vineyards, with stone walls on both sides.

[[v4-22-25]]

^<<v4-22-25,25>>^ When the donkey saw Jehovah’s angel, it began to squeeze itself against the wall and it jammed Baʹlaam’s foot against the wall, and Baʹlaam began beating it again.

[[v4-22-26]]

^<<v4-22-26,26>>^ Jehovah’s angel now passed by again and stood in a narrow place where there was no way to turn to the right or to the left.

[[v4-22-27]]

^<<v4-22-27,27>>^ When the donkey saw Jehovah’s angel, it lay down under Baʹlaam, so Baʹlaam became furious and kept beating the donkey with his staff.

[[v4-22-28]]

^<<v4-22-28,28>>^ Finally Jehovah caused the donkey to speak,^&#42;1^ and it said to Baʹlaam: “What have I done to you to make you beat me these three times?”

[NOTE]
====
. Lit., “opened the mouth of the female donkey.”
====

[[v4-22-29]]

^<<v4-22-29,29>>^ Baʹlaam replied to the donkey: “It is because you have made a fool of me. If only I had a sword in my hand, I would kill you!”

[[v4-22-30]]

^<<v4-22-30,30>>^ Then the donkey said to Baʹlaam: “Am I not your donkey that you have ridden on all your life until today? Have I ever treated you this way before?” He replied: “No!”

[[v4-22-31]]

^<<v4-22-31,31>>^ Then Jehovah uncovered Baʹlaam’s eyes, and he saw Jehovah’s angel standing in the road with a drawn sword in his hand. At once he bowed low and prostrated himself on his face.

[[v4-22-32]]

^<<v4-22-32,32>>^ Then Jehovah’s angel said to him: “Why have you beaten your donkey these three times? Look! I myself came out to offer resistance, because your way is in defiance of my will.

[[v4-22-33]]

^<<v4-22-33,33>>^ The donkey saw me and tried to turn away from me these three times. Supposing it had not turned away from me! By now I would have killed you and let the donkey live.”

[[v4-22-34]]

^<<v4-22-34,34>>^ Baʹlaam said to Jehovah’s angel: “I have sinned, because I did not know that it was you standing in the road to meet me. And now if it is bad in your eyes, I will go back.”

[[v4-22-35]]

^<<v4-22-35,35>>^ But Jehovah’s angel said to Baʹlaam: “Go with the men, but you may speak only the words that I tell you.” So Baʹlaam continued going with the princes of Baʹlak.

[[v4-22-36]]

^<<v4-22-36,36>>^ When Baʹlak heard that Baʹlaam had come, he immediately went out to meet him at the city of Moʹab, which is on the bank of the Arʹnon on the border of the territory.

[[v4-22-37]]

^<<v4-22-37,37>>^ Baʹlak said to Baʹlaam: “Did I not send for you? Why did you not come to me? Did you think I am not able to honor you greatly?”

[[v4-22-38]]

^<<v4-22-38,38>>^ Baʹlaam replied to Baʹlak: “Well, I have come to you now. But will I be allowed to say anything? I can only speak words that God puts in my mouth.”

[[v4-22-39]]

^<<v4-22-39,39>>^ So Baʹlaam went with Baʹlak, and they came to Kirʹi·ath-huʹzoth.

[[v4-22-40]]

^<<v4-22-40,40>>^ Baʹlak sacrificed cattle and sheep and sent some to Baʹlaam and the princes who were with him.

[[v4-22-41]]

^<<v4-22-41,41>>^ In the morning Baʹlak took Baʹlaam and brought him up to Baʹmoth-baʹal; from there he could see all the people.

'''

xref:004-numbers/004-numbers-021.adoc#v4-21-0[&#60; Capítulo Anterior] | <<v4-22-0,Topo>> | xref:004-numbers/004-numbers-023.adoc#v4-23-0[Próximo Capítulo &#62;]