include::./index.adoc[]

[[v4-28-0]]
=== Numbers, 28
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-28-1]]

^<<v4-28-1,1>>^ Jehovah next said to Moses:

[[v4-28-2]]

^<<v4-28-2,2>>^ “Command the Israelites and tell them, ‘You should take care that you present to me my offering, my bread. My offerings by fire as a pleasing^&#42;1^ aroma to me must be made at their appointed times.’

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-28-3]]

^<<v4-28-3,3>>^ “And say to them, ‘This is the offering made by fire that you will present to Jehovah: two sound year-old male lambs a day as a burnt offering regularly.

[[v4-28-4]]

^<<v4-28-4,4>>^ The one male lamb you will offer in the morning, and the other male lamb you will offer at twilight,^&#42;1^

[NOTE]
====
. Lit., “between the two evenings.”
====

[[v4-28-5]]

^<<v4-28-5,5>>^ together with a tenth of an eʹphah^&#42;1^ of fine flour mixed with a fourth of a hin^&#42;2^ of beaten oil as a grain offering.

[NOTE]
====
. A tenth of an ephah equaled 2.2 L (2 dry qt). See App. B14.
. A hin equaled 3.67 L (7.75 pt). See App. B14.
====

[[v4-28-6]]

^<<v4-28-6,6>>^ It is a regular burnt offering, which was established at Mount Siʹnai as a pleasing^&#42;1^ aroma, an offering made by fire to Jehovah,

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-28-7]]

^<<v4-28-7,7>>^ along with its drink offering, a fourth of a hin for each male lamb. Pour out the alcoholic drink in the holy place as a drink offering to Jehovah.

[[v4-28-8]]

^<<v4-28-8,8>>^ And you will offer the other male lamb at twilight.^&#42;1^ With the same grain offering as that made in the morning and with its same drink offering, you will present it as an offering made by fire as a pleasing^&#42;2^ aroma to Jehovah.

[NOTE]
====
. Lit., “between the two evenings.”
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-28-9]]

^<<v4-28-9,9>>^ “‘However, on the Sabbath day, the offering should be two sound year-old male lambs and two tenths of an eʹphah measure of fine flour mixed with oil as a grain offering, together with its drink offering.

[[v4-28-10]]

^<<v4-28-10,10>>^ This is the burnt offering for the Sabbath, along with the regular burnt offering and its drink offering.

[[v4-28-11]]

^<<v4-28-11,11>>^ “‘At the start of each month^&#42;1^ you will present as a burnt offering to Jehovah two young bulls, one ram, and seven sound male lambs each a year old,

[NOTE]
====
. Lit., “of your months.”
====

[[v4-28-12]]

^<<v4-28-12,12>>^ and three tenth measures of fine flour mixed with oil as a grain offering for each bull and two tenth measures of fine flour mixed with oil as a grain offering for the one ram,

[[v4-28-13]]

^<<v4-28-13,13>>^ and a tenth measure of fine flour mixed with oil as a grain offering for each male lamb, as a burnt offering, a pleasing^&#42;1^ aroma, an offering made by fire to Jehovah.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-28-14]]

^<<v4-28-14,14>>^ And their drink offerings should be half a hin of wine for a bull and a third of a hin for the ram and a fourth of a hin for a male lamb. This is the monthly burnt offering each month throughout the year.

[[v4-28-15]]

^<<v4-28-15,15>>^ Also, one young goat should be offered as a sin offering to Jehovah in addition to the regular burnt offering together with its drink offering.

[[v4-28-16]]

^<<v4-28-16,16>>^ “‘In the first month, on the 14th day of the month, will be Jehovah’s Passover.

[[v4-28-17]]

^<<v4-28-17,17>>^ And on the 15th day of this month, there will be a festival. Unleavened bread will be eaten for seven days.

[[v4-28-18]]

^<<v4-28-18,18>>^ On the first day there will be a holy convention. You must not do any hard work.

[[v4-28-19]]

^<<v4-28-19,19>>^ And you will present as a burnt offering made by fire to Jehovah two young bulls, one ram, and seven male lambs each a year old. You should offer sound animals.

[[v4-28-20]]

^<<v4-28-20,20>>^ You should offer them with their grain offerings of fine flour mixed with oil, three tenth measures for a bull and two tenth measures for the ram.

[[v4-28-21]]

^<<v4-28-21,21>>^ You will offer a tenth measure respectively for each male lamb of the seven male lambs,

[[v4-28-22]]

^<<v4-28-22,22>>^ as well as one goat as a sin offering to make atonement for you.

[[v4-28-23]]

^<<v4-28-23,23>>^ Aside from the morning burnt offering, which is for the regular burnt offering, you will offer these.

[[v4-28-24]]

^<<v4-28-24,24>>^ You will offer these in the same manner each day for seven days as food,^&#42;1^ an offering made by fire as a pleasing^&#42;2^ aroma to Jehovah. It should be offered along with the regular burnt offering and its drink offering.

[NOTE]
====
. Lit., “bread.”
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-28-25]]

^<<v4-28-25,25>>^ On the seventh day you should hold a holy convention. You must not do any hard work.

[[v4-28-26]]

^<<v4-28-26,26>>^ “‘On the day of the first ripe fruits, when you present a new grain offering to Jehovah, you should hold a holy convention in your feast of weeks. You must not do any hard work.

[[v4-28-27]]

^<<v4-28-27,27>>^ You will present as a burnt offering for a pleasing^&#42;1^ aroma to Jehovah two young bulls, one ram, and seven male lambs each a year old,

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-28-28]]

^<<v4-28-28,28>>^ and as their grain offering of fine flour mixed with oil, three tenth measures for each bull, two tenth measures for the one ram,

[[v4-28-29]]

^<<v4-28-29,29>>^ a tenth measure respectively for each male lamb of the seven male lambs,

[[v4-28-30]]

^<<v4-28-30,30>>^ as well as one young goat to make atonement for you.

[[v4-28-31]]

^<<v4-28-31,31>>^ You will offer them in addition to the regular burnt offering and its grain offering. They should be sound animals, along with their drink offerings.

'''

xref:004-numbers/004-numbers-027.adoc#v4-27-0[&#60; Capítulo Anterior] | <<v4-28-0,Topo>> | xref:004-numbers/004-numbers-029.adoc#v4-29-0[Próximo Capítulo &#62;]