include::./index.adoc[]

[[v4-24-0]]
=== Numbers, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-24-1]]

^<<v4-24-1,1>>^ When Baʹlaam saw that it pleased^&#42;1^ Jehovah to bless Israel, he did not go away again to search for omens of doom, but he turned his face to the wilderness.

[NOTE]
====
. Lit., “was good in the eyes of.”
====

[[v4-24-2]]

^<<v4-24-2,2>>^ When Baʹlaam raised his eyes and saw Israel encamped by his tribes, then the spirit of God came upon him.

[[v4-24-3]]

^<<v4-24-3,3>>^ He then spoke this proverbial saying:
“The saying of Baʹlaam the son of Beʹor,
And the saying of a man whose eyes have been opened,

[[v4-24-4]]

^<<v4-24-4,4>>^ The saying of the one hearing the word of God,
Who saw a vision of the Almighty,
Who has bowed down with his eyes uncovered:

[[v4-24-5]]

^<<v4-24-5,5>>^ How beautiful are your tents, O Jacob,
Your tabernacles, O Israel!

[[v4-24-6]]

^<<v4-24-6,6>>^ Like the valleys^&#42;1^ they have extended a long way,
Like gardens by the river,
Like aloes that Jehovah has planted,
Like cedars by the waters.

[NOTE]
====
. Or “wadis.”
====

[[v4-24-7]]

^<<v4-24-7,7>>^ Water keeps trickling from his two leather buckets,
And his seed^&#42;1^ is sown by many waters.
His king also will be greater than Aʹgag,
And his kingdom will be exalted.

[NOTE]
====
. Or “offspring.”
====

[[v4-24-8]]

^<<v4-24-8,8>>^ God is bringing him out of Egypt;
He is like the horns of a wild bull for them.
He will consume the nations, his oppressors,
And their bones he will gnaw, and he will shatter them with his arrows.

[[v4-24-9]]

^<<v4-24-9,9>>^ He has crouched down, he has lain down like the lion,
And like a lion, who dares rouse him?
Those blessing you are blessed,
And those cursing you are cursed.”

[[v4-24-10]]

^<<v4-24-10,10>>^ Then Baʹlak became furious with Baʹlaam. Baʹlak scornfully clapped his hands together and said to Baʹlaam: “It was to put a curse on my enemies that I called you, but now you have done nothing but bless them these three times.

[[v4-24-11]]

^<<v4-24-11,11>>^ Now go home immediately. I intended to honor you greatly, but look! Jehovah has deprived you of honor.”

[[v4-24-12]]

^<<v4-24-12,12>>^ Baʹlaam replied to Baʹlak: “Did I not say to the messengers you sent,

[[v4-24-13]]

^<<v4-24-13,13>>^ ‘If Baʹlak were to give me his house full of silver and gold, I could not of my own will^&#42;1^ do anything beyond the order of Jehovah, whether good or bad. I will only speak what Jehovah will tell me’?

[NOTE]
====
. Lit., “from my heart.”
====

[[v4-24-14]]

^<<v4-24-14,14>>^ And now I am going away to my people. Come and let me advise you what this people will do to your people in the future.”^&#42;1^

[NOTE]
====
. Or “in the end of the days.”
====

[[v4-24-15]]

^<<v4-24-15,15>>^ So he spoke this proverbial saying:
“The saying of Baʹlaam the son of Beʹor,
And the saying of a man whose eyes have been opened,

[[v4-24-16]]

^<<v4-24-16,16>>^ The saying of the one hearing the word of God,
And the one having the knowledge of the Most High,
A vision of the Almighty he saw
While bowing down with his eyes uncovered:

[[v4-24-17]]

^<<v4-24-17,17>>^ I will see him, but not now;
I will behold him, but not soon.
A star will come out of Jacob,
And a scepter will rise out of Israel.
And he will certainly break apart the forehead of Moʹab^&#42;1^
And the skull of all the sons of tumult.

[NOTE]
====
. Or “the temples of Moab’s head.”
====

[[v4-24-18]]

^<<v4-24-18,18>>^ And Eʹdom will become a possession,
Yes, Seʹir the possession of his enemies,
While Israel is displaying his courage.

[[v4-24-19]]

^<<v4-24-19,19>>^ And out of Jacob one will be subduing,
And he will destroy any survivor from the city.”

[[v4-24-20]]

^<<v4-24-20,20>>^ When he saw Amʹa·lek, he continued his proverbial saying:
“Amʹa·lek was the first of the nations,
But in the end he will perish.”

[[v4-24-21]]

^<<v4-24-21,21>>^ When he saw the Kenʹites, he continued his proverbial saying:
“Secure is your dwelling, and set on the crag is your abode.

[[v4-24-22]]

^<<v4-24-22,22>>^ But someone will burn Kaʹin down.
How long before As·syrʹi·a carries you away captive?”

[[v4-24-23]]

^<<v4-24-23,23>>^ And he continued his proverbial saying:
“Woe! Who will survive when God does this?

[[v4-24-24]]

^<<v4-24-24,24>>^ Ships will come from the coast of Kitʹtim,
And they will afflict As·syrʹi·a,
And they will afflict Eʹber.
But he too will utterly perish.”

[[v4-24-25]]

^<<v4-24-25,25>>^ Then Baʹlaam got up and went and returned to his place. Baʹlak also went his own way.

'''

xref:004-numbers/004-numbers-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numbers/004-numbers-025.adoc#v4-25-0[Próximo Capítulo &#62;]