include::./index.adoc[]

[[v4-5-0]]
=== Numbers, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-5-1]]

^<<v4-5-1,1>>^ Jehovah spoke further to Moses, saying:

[[v4-5-2]]

^<<v4-5-2,2>>^ “Command the Israelites to send out of the camp every leprous person and everyone having a discharge and everyone unclean by a dead person.^&#42;1^

[NOTE]
====
. Or “by a soul.” See Glossary.
====

[[v4-5-3]]

^<<v4-5-3,3>>^ Whether a male or a female, you should send them out. You should send them outside the camp, so that they may not contaminate the camps of those in whose midst I am dwelling.”^&#42;1^

[NOTE]
====
. Or “tabernacling.”
====

[[v4-5-4]]

^<<v4-5-4,4>>^ Therefore, the Israelites did so and sent them outside the camp. Just as Jehovah told Moses, so the Israelites did.

[[v4-5-5]]

^<<v4-5-5,5>>^ Jehovah continued speaking to Moses, saying:

[[v4-5-6]]

^<<v4-5-6,6>>^ “Tell the Israelites, ‘If a man or a woman commits any of the sins of mankind and acts unfaithfully toward Jehovah, that person^&#42;1^ has become guilty.

[NOTE]
====
. Or “soul.”
====

[[v4-5-7]]

^<<v4-5-7,7>>^ He^&#42;1^ must confess the sin that he has^&#42;2^ committed and return the full amount as compensation for his guilt and also add a fifth of its value; he is to give it to the one he wronged.

[NOTE]
====
. Lit., “They.”
. Lit., “they have.”
====

[[v4-5-8]]

^<<v4-5-8,8>>^ But if the victim does not have a close relative to receive the compensation, it should be returned to Jehovah and will belong to the priest, apart from the ram of atonement with which he will make atonement for him.

[[v4-5-9]]

^<<v4-5-9,9>>^ “‘Every holy contribution from the Israelites that is presented to the priest should become his.

[[v4-5-10]]

^<<v4-5-10,10>>^ The holy things of each person will remain his own. Whatever each one gives to the priest, that will belong to the priest.’”

[[v4-5-11]]

^<<v4-5-11,11>>^ Jehovah went on to speak to Moses, saying:

[[v4-5-12]]

^<<v4-5-12,12>>^ “Speak to the Israelites and tell them, ‘This is what should be done if a man’s wife goes astray and is unfaithful to him

[[v4-5-13]]

^<<v4-5-13,13>>^ and another man has sexual relations with her, but it was unknown to her husband and remains undiscovered, so that she has defiled herself but there is no witness against her and she has not been caught:

[[v4-5-14]]

^<<v4-5-14,14>>^ Whether the husband becomes jealous and suspicious of his wife’s faithfulness when she has defiled herself, or whether he is jealous and suspicious of his wife’s faithfulness when she has not defiled herself,

[[v4-5-15]]

^<<v4-5-15,15>>^ the man must bring his wife to the priest, along with an offering for her, a tenth of an eʹphah^&#42;1^ of barley flour. He must not pour oil on it nor put frankincense on it, because it is a grain offering of jealousy, a grain offering bringing guilt to mind.

[NOTE]
====
. A tenth of an ephah equaled 2.2 L (2 dry qt). See App. B14.
====

[[v4-5-16]]

^<<v4-5-16,16>>^ “‘The priest will bring her forward and make her stand before Jehovah.

[[v4-5-17]]

^<<v4-5-17,17>>^ The priest will take holy water in an earthenware vessel, and the priest will take some of the dust from the floor of the tabernacle and put it in the water.

[[v4-5-18]]

^<<v4-5-18,18>>^ And the priest will make the woman stand before Jehovah and unbind the woman’s hair and put in her palms the grain offering for a reminder, that is, the grain offering of jealousy, and the priest will have in his hand the bitter water that brings a curse.

[[v4-5-19]]

^<<v4-5-19,19>>^ “‘The priest will then make her swear, saying to the woman: “If no other man had sexual relations with you while you were under your husband’s authority and you have not gone astray and become defiled, may you be free of the effect of this bitter water that brings a curse.

[[v4-5-20]]

^<<v4-5-20,20>>^ But if you have gone astray while under your husband’s authority by defiling yourself, and you have had sexual relations with another man besides your husband—”

[[v4-5-21]]

^<<v4-5-21,21>>^ The priest will then make the woman swear an oath that includes a curse, and the priest will say to the woman: “May Jehovah make you an object for cursing and for an oath among your people, as Jehovah makes your thigh^&#42;1^ fall away^&#42;2^ and causes your abdomen to swell.

[NOTE]
====
. Evidently referring to the reproductive organs.
. Or “waste away.” This may suggest loss of fertility.
====

[[v4-5-22]]

^<<v4-5-22,22>>^ This water that brings a curse will enter into your intestines to cause your abdomen to swell and make your thigh^&#42;1^ fall away.”^&#42;2^ To this the woman should say: “Amen! Amen!”^&#42;3^

[NOTE]
====
. Evidently referring to the reproductive organs.
. Or “waste away.” This may suggest loss of fertility.
. Or “So be it! So be it!”
====

[[v4-5-23]]

^<<v4-5-23,23>>^ “‘Then the priest should write these curses in the book and wash them off into the bitter water.

[[v4-5-24]]

^<<v4-5-24,24>>^ He will then make the woman drink the bitter water that brings a curse, and the water that brings a curse will enter into her and produce bitterness.

[[v4-5-25]]

^<<v4-5-25,25>>^ And the priest should take the grain offering of jealousy from the woman’s hand and wave the grain offering back and forth before Jehovah, and he will bring it near the altar.

[[v4-5-26]]

^<<v4-5-26,26>>^ The priest will take a handful of the grain offering as a token offering and make it smoke on the altar, and afterward he will make the woman drink the water.

[[v4-5-27]]

^<<v4-5-27,27>>^ When he makes her drink the water, if she has defiled herself and committed an act of unfaithfulness toward her husband, the water that brings a curse will then enter into her and become something bitter, and her abdomen will swell, and her thigh^&#42;1^ will fall away,^&#42;2^ and the woman will become an object of cursing among her people.

[NOTE]
====
. Evidently referring to the reproductive organs.
. Or “waste away.” This may suggest loss of fertility.
====

[[v4-5-28]]

^<<v4-5-28,28>>^ However, if the woman has not defiled herself and is clean, she will then be free from such punishment, and she will be able to conceive and produce offspring.

[[v4-5-29]]

^<<v4-5-29,29>>^ “‘This is the law about jealousy, when a woman may go astray and defile herself while under her husband’s authority,

[[v4-5-30]]

^<<v4-5-30,30>>^ or in the case of a man who becomes jealous and suspects his wife of unfaithfulness; he should make his wife stand before Jehovah, and the priest must carry out toward her all this law.

[[v4-5-31]]

^<<v4-5-31,31>>^ The man will be free from guilt, but his wife will answer for her guilt.’”

'''

xref:004-numbers/004-numbers-004.adoc#v4-4-0[&#60; Capítulo Anterior] | <<v4-5-0,Topo>> | xref:004-numbers/004-numbers-006.adoc#v4-6-0[Próximo Capítulo &#62;]