include::./index.adoc[]

[[v4-15-0]]
=== Numbers, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-15-1]]

^<<v4-15-1,1>>^ Jehovah spoke further to Moses, saying:

[[v4-15-2]]

^<<v4-15-2,2>>^ “Speak to the Israelites and say to them, ‘When you eventually come into the land that I am giving you to dwell in

[[v4-15-3]]

^<<v4-15-3,3>>^ and you make an offering by fire to Jehovah from the herd or from the flock—whether a burnt offering or a sacrifice to perform a special vow or a voluntary offering or an offering during your seasonal festivals, in order to make a pleasing^&#42;1^ aroma to Jehovah—

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-15-4]]

^<<v4-15-4,4>>^ the one presenting his offering must also present to Jehovah a grain offering of fine flour, a tenth of an eʹphah,^&#42;1^ mixed with a fourth of a hin^&#42;2^ of oil.

[NOTE]
====
. A tenth of an ephah equaled 2.2 L (2 dry qt). See App. B14.
. A hin equaled 3.67 L (7.75 pt). See App. B14.
====

[[v4-15-5]]

^<<v4-15-5,5>>^ You should also offer wine as a drink offering, a fourth of a hin, together with the burnt offering or for the sacrifice of each male lamb.

[[v4-15-6]]

^<<v4-15-6,6>>^ Or for a ram, you should make a grain offering of two tenths of an eʹphah measure of fine flour mixed with a third of a hin of oil.

[[v4-15-7]]

^<<v4-15-7,7>>^ And you should present wine as a drink offering, a third of a hin, as a pleasing^&#42;1^ aroma to Jehovah.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-15-8]]

^<<v4-15-8,8>>^ “‘But if you should offer a male of the herd as a burnt offering or a sacrifice to perform a special vow or communion sacrifices to Jehovah,

[[v4-15-9]]

^<<v4-15-9,9>>^ you should also present together with the male of the herd a grain offering of three tenths of an eʹphah measure of fine flour mixed with half a hin of oil.

[[v4-15-10]]

^<<v4-15-10,10>>^ You should also present wine as a drink offering, half a hin, as an offering made by fire, as a pleasing^&#42;1^ aroma to Jehovah.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-15-11]]

^<<v4-15-11,11>>^ This is what should be done for each bull or for each ram or for each of the male lambs or of the goats.

[[v4-15-12]]

^<<v4-15-12,12>>^ Whatever may be the number that you offer, that is what you should do for each one, according to their number.

[[v4-15-13]]

^<<v4-15-13,13>>^ This is how every native-born Israelite should present an offering made by fire, as a pleasing^&#42;1^ aroma to Jehovah.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-15-14]]

^<<v4-15-14,14>>^ “‘If a foreigner who is residing with you or one who has been in your midst for many of your generations should also make an offering by fire, as a pleasing^&#42;1^ aroma to Jehovah, he should do just as you do.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-15-15]]

^<<v4-15-15,15>>^ You who are of the congregation and the foreigner who is residing with you will have one statute. It will be a lasting statute for all your generations. The foreign resident should be the same as you before Jehovah.

[[v4-15-16]]

^<<v4-15-16,16>>^ There should be one law and one judicial decision for you and for the foreigner who is residing with you.’”

[[v4-15-17]]

^<<v4-15-17,17>>^ Jehovah went on to say to Moses:

[[v4-15-18]]

^<<v4-15-18,18>>^ “Speak to the Israelites and tell them, ‘When you come into the land where I am bringing you

[[v4-15-19]]

^<<v4-15-19,19>>^ and you eat any of the bread^&#42;1^ of the land, you should make a contribution to Jehovah.

[NOTE]
====
. Or “food.”
====

[[v4-15-20]]

^<<v4-15-20,20>>^ You should make a contribution of the firstfruits of your coarse meal as ring-shaped loaves. Like the contribution of a threshing floor is the way you should contribute it.

[[v4-15-21]]

^<<v4-15-21,21>>^ Some of the firstfruits of your coarse meal you should give as a contribution to Jehovah throughout your generations.

[[v4-15-22]]

^<<v4-15-22,22>>^ “‘Now if you make a mistake and fail to observe all these commandments that Jehovah has spoken to Moses,

[[v4-15-23]]

^<<v4-15-23,23>>^ all that Jehovah has commanded you through Moses from the day that Jehovah commanded and onward for your generations,

[[v4-15-24]]

^<<v4-15-24,24>>^ and if it was done by mistake and without the knowledge of the assembly, the whole assembly must offer one young bull as a burnt offering for a pleasing^&#42;1^ aroma to Jehovah, together with its grain offering and its drink offering according to the regular procedure, and one young goat as a sin offering.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v4-15-25]]

^<<v4-15-25,25>>^ The priest will make atonement for the whole assembly of the Israelites, and it will be forgiven them, because it was a mistake, and they brought as their offering an offering made by fire to Jehovah and their sin offering before Jehovah for their mistake.

[[v4-15-26]]

^<<v4-15-26,26>>^ It will be forgiven the whole assembly of the Israelites and the foreigner who is residing in their midst, because it was by mistake on the part of all the people.

[[v4-15-27]]

^<<v4-15-27,27>>^ “‘If any person^&#42;1^ should sin by mistake, then he must present a female goat in its first year for a sin offering.

[NOTE]
====
. Or “soul.”
====

[[v4-15-28]]

^<<v4-15-28,28>>^ And the priest will make atonement for the person^&#42;1^ who made a mistake by an unintentional sin before Jehovah, so as to make atonement for it, and it will be forgiven him.

[NOTE]
====
. Or “soul.”
====

[[v4-15-29]]

^<<v4-15-29,29>>^ As for the native-born among the Israelites and the foreigner who is residing in their midst, there should be one law for you in the matter of doing something unintentionally.

[[v4-15-30]]

^<<v4-15-30,30>>^ “‘But the person^&#42;1^ who does something deliberately, whether he is native-born or a foreign resident, is blaspheming Jehovah and must be cut off^&#42;2^ from among his people.

[NOTE]
====
. Or “soul.”
. Or “put to death.”
====

[[v4-15-31]]

^<<v4-15-31,31>>^ Because he has despised Jehovah’s word and broken his commandment, that person^&#42;1^ should be cut off without fail. His own error is upon him.’”

[NOTE]
====
. Or “soul.”
====

[[v4-15-32]]

^<<v4-15-32,32>>^ While the Israelites were in the wilderness, they found a man collecting pieces of wood on the Sabbath day.

[[v4-15-33]]

^<<v4-15-33,33>>^ Those who found him collecting wood brought him up to Moses and Aaron and the whole assembly.

[[v4-15-34]]

^<<v4-15-34,34>>^ They committed him into custody because it had not been specified what should be done to him.

[[v4-15-35]]

^<<v4-15-35,35>>^ And Jehovah said to Moses: “The man should be put to death without fail, and the whole assembly should stone him outside the camp.”

[[v4-15-36]]

^<<v4-15-36,36>>^ So the whole assembly brought him outside the camp and stoned him so that he died, just as Jehovah had commanded Moses.

[[v4-15-37]]

^<<v4-15-37,37>>^ Jehovah went on to say this to Moses:

[[v4-15-38]]

^<<v4-15-38,38>>^ “Speak to the Israelites and tell them that they must make for themselves fringed edges on the skirts of their garments throughout their generations, and they are to put a blue string above the fringed edge of the skirt.

[[v4-15-39]]

^<<v4-15-39,39>>^ ‘You must have this fringed edge so that you will see it and remember all the commandments of Jehovah and observe them. You must not follow your own hearts and eyes, which are leading you to spiritual prostitution.

[[v4-15-40]]

^<<v4-15-40,40>>^ This will help you remember, and you will observe all my commandments and be holy to your God.

[[v4-15-41]]

^<<v4-15-41,41>>^ I am Jehovah your God, who brought you out of the land of Egypt in order to prove myself your God. I am Jehovah your God.’”

'''

xref:004-numbers/004-numbers-014.adoc#v4-14-0[&#60; Capítulo Anterior] | <<v4-15-0,Topo>> | xref:004-numbers/004-numbers-016.adoc#v4-16-0[Próximo Capítulo &#62;]