include::./index.adoc[]

[[v4-2-0]]
=== Numbers, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-2-1]]

^<<v4-2-1,1>>^ Jehovah now spoke to Moses and Aaron, saying:

[[v4-2-2]]

^<<v4-2-2,2>>^ “The Israelites should encamp where their three-tribe division is assigned, each man near the banner^&#42;1^ of his paternal house. They should camp facing the tent of meeting, all around it.

[NOTE]
====
. Or “sign.”
====

[[v4-2-3]]

^<<v4-2-3,3>>^ “Those camping on the east side, toward the sunrise, will be the three-tribe division of the encampment of Judah by their companies;^&#42;1^ the chieftain for the sons of Judah is Nahʹshon the son of Am·minʹa·dab.

[NOTE]
====
. Lit., “according to their armies.”
====

[[v4-2-4]]

^<<v4-2-4,4>>^ Those registered in his army are 74,600.

[[v4-2-5]]

^<<v4-2-5,5>>^ Camping alongside him will be the tribe of Isʹsa·char; the chieftain for the sons of Isʹsa·char is Ne·thanʹel the son of Zuʹar.

[[v4-2-6]]

^<<v4-2-6,6>>^ Those registered in his army are 54,400.

[[v4-2-7]]

^<<v4-2-7,7>>^ Next is the tribe of Zebʹu·lun; the chieftain for the sons of Zebʹu·lun is E·liʹab the son of Heʹlon.

[[v4-2-8]]

^<<v4-2-8,8>>^ Those registered in his army are 57,400.

[[v4-2-9]]

^<<v4-2-9,9>>^ “All those registered in the armies of the camp of Judah are 186,400. They should break camp first.

[[v4-2-10]]

^<<v4-2-10,10>>^ “The three-tribe division of the encampment of Reuʹben by their companies^&#42;1^ will be toward the south; the chieftain for the sons of Reuʹben is E·liʹzur the son of Shedʹe·ur.

[NOTE]
====
. Lit., “according to their armies.”
====

[[v4-2-11]]

^<<v4-2-11,11>>^ Those registered in his army are 46,500.

[[v4-2-12]]

^<<v4-2-12,12>>^ Camping alongside him will be the tribe of Simʹe·on; the chieftain for the sons of Simʹe·on is She·luʹmi·el the son of Zu·ri·shadʹdai.

[[v4-2-13]]

^<<v4-2-13,13>>^ Those registered in his army are 59,300.

[[v4-2-14]]

^<<v4-2-14,14>>^ Next is the tribe of Gad; the chieftain for the sons of Gad is E·liʹa·saph the son of Reuʹel.

[[v4-2-15]]

^<<v4-2-15,15>>^ Those registered in his army are 45,650.

[[v4-2-16]]

^<<v4-2-16,16>>^ “All those registered in the armies of the camp of Reuʹben are 151,450, and they should break camp second.

[[v4-2-17]]

^<<v4-2-17,17>>^ “When the tent of meeting is moved, the camp of the Levites should be in the middle of the other camps.
“They should travel in the same order as they encamp, with each in his place, according to their three-tribe divisions.

[[v4-2-18]]

^<<v4-2-18,18>>^ “The three-tribe division of the encampment of Eʹphra·im by their companies^&#42;1^ will be toward the west; the chieftain for the sons of Eʹphra·im is E·lishʹa·ma the son of Am·miʹhud.

[NOTE]
====
. Lit., “according to their armies.”
====

[[v4-2-19]]

^<<v4-2-19,19>>^ Those registered in his army are 40,500.

[[v4-2-20]]

^<<v4-2-20,20>>^ Next to him will be the tribe of Ma·nasʹseh; the chieftain for the sons of Ma·nasʹseh is Ga·maʹli·el the son of Pe·dahʹzur.

[[v4-2-21]]

^<<v4-2-21,21>>^ Those registered in his army are 32,200.

[[v4-2-22]]

^<<v4-2-22,22>>^ Next is the tribe of Benjamin; the chieftain for the sons of Benjamin is Abʹi·dan the son of Gid·e·oʹni.

[[v4-2-23]]

^<<v4-2-23,23>>^ Those registered in his army are 35,400.

[[v4-2-24]]

^<<v4-2-24,24>>^ “All those registered in the armies of the camp of Eʹphra·im are 108,100, and they should break camp third.

[[v4-2-25]]

^<<v4-2-25,25>>^ “The three-tribe division of the encampment of Dan by their companies^&#42;1^ will be toward the north; the chieftain for the sons of Dan is A·hi·eʹzer the son of Am·mi·shadʹdai.

[NOTE]
====
. Lit., “according to their armies.”
====

[[v4-2-26]]

^<<v4-2-26,26>>^ Those registered in his army are 62,700.

[[v4-2-27]]

^<<v4-2-27,27>>^ Camping alongside him will be the tribe of Ashʹer; the chieftain for the sons of Ashʹer is Paʹgi·el the son of Ochʹran.

[[v4-2-28]]

^<<v4-2-28,28>>^ Those registered in his army are 41,500.

[[v4-2-29]]

^<<v4-2-29,29>>^ Next is the tribe of Naphʹta·li; the chieftain for the sons of Naphʹta·li is A·hiʹra the son of Eʹnan.

[[v4-2-30]]

^<<v4-2-30,30>>^ Those registered in his army are 53,400.

[[v4-2-31]]

^<<v4-2-31,31>>^ “All those registered in the camp of Dan are 157,600. They should break camp last, according to their three-tribe divisions.”

[[v4-2-32]]

^<<v4-2-32,32>>^ These were the Israelites who were registered according to their paternal houses; the total of those in the camps registered for the army was 603,550.

[[v4-2-33]]

^<<v4-2-33,33>>^ But the Levites did not get registered along with the other Israelites, just as Jehovah had commanded Moses.

[[v4-2-34]]

^<<v4-2-34,34>>^ The Israelites did everything that Jehovah had commanded Moses. This is how they encamped by their three-tribe divisions and how they broke camp, each by family and according to their paternal houses.

'''

xref:004-numbers/004-numbers-001.adoc#v4-1-0[&#60; Capítulo Anterior] | <<v4-2-0,Topo>> | xref:004-numbers/004-numbers-003.adoc#v4-3-0[Próximo Capítulo &#62;]