include::./index.adoc[]

[[v4-21-0]]
=== Numbers, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-21-1]]

^<<v4-21-1,1>>^ When the Caʹnaan·ite king of Aʹrad, who dwelled in the Negʹeb, heard that Israel had come by the way of Athʹa·rim, he attacked Israel and carried away some of them as captives.

[[v4-21-2]]

^<<v4-21-2,2>>^ So Israel made this vow to Jehovah: “If you give this people into my hand, I will without fail devote their cities to destruction.”

[[v4-21-3]]

^<<v4-21-3,3>>^ So Jehovah listened to Israel’s voice and gave the Caʹnaan·ites over to them, and they devoted them and their cities to destruction. Therefore, they named the place Horʹmah.^&#42;1^

[NOTE]
====
. Meaning “A Devoting to Destruction.”
====

[[v4-21-4]]

^<<v4-21-4,4>>^ As they continued their journey from Mount Hor by the way of the Red Sea in order to go around the land of Eʹdom, the people^&#42;1^ became weary of the journey.

[NOTE]
====
. Or “the soul of the people.”
====

[[v4-21-5]]

^<<v4-21-5,5>>^ And the people kept speaking against God and Moses, saying: “Why have you brought us up out of Egypt to die in the wilderness? There is no food and no water, and we^&#42;1^ have come to hate^&#42;2^ this contemptible bread.”

[NOTE]
====
. Or “our souls.”
. Or “abhor.”
====

[[v4-21-6]]

^<<v4-21-6,6>>^ So Jehovah sent poisonous^&#42;1^ serpents among the people, and they kept biting the people, so that many Israelites died.

[NOTE]
====
. Or “fiery.”
====

[[v4-21-7]]

^<<v4-21-7,7>>^ So the people came to Moses and said: “We have sinned by speaking against Jehovah and against you. Intercede with Jehovah so that he may remove the serpents from us.” And Moses interceded on behalf of the people.

[[v4-21-8]]

^<<v4-21-8,8>>^ Then Jehovah said to Moses: “Make a replica of a poisonous^&#42;1^ snake and put it on a pole. Then when anyone has been bitten, he will have to look at it in order to keep alive.”

[NOTE]
====
. Or “fiery.”
====

[[v4-21-9]]

^<<v4-21-9,9>>^ Moses at once made a serpent of copper and put it on the pole, and whenever a serpent had bitten a man and he looked at the copper serpent, he survived.

[[v4-21-10]]

^<<v4-21-10,10>>^ After that the Israelites departed and camped in Oʹboth.

[[v4-21-11]]

^<<v4-21-11,11>>^ Then they departed from Oʹboth and camped in Iʹye-abʹa·rim, in the wilderness that faces Moʹab, toward the east.

[[v4-21-12]]

^<<v4-21-12,12>>^ From there they departed and camped by the Valley^&#42;1^ of Zeʹred.

[NOTE]
====
. Or “Wadi.”
====

[[v4-21-13]]

^<<v4-21-13,13>>^ From there they departed and camped in the region of the Arʹnon, which is in the wilderness that extends from the border of the Amʹor·ites, for the Arʹnon is the boundary of Moʹab, between Moʹab and the Amʹor·ites.

[[v4-21-14]]

^<<v4-21-14,14>>^ That is why the book of the Wars of Jehovah speaks of “Vaʹheb in Suʹphah and the valleys^&#42;1^ of Arʹnon,

[NOTE]
====
. Or “wadis.”
====

[[v4-21-15]]

^<<v4-21-15,15>>^ and the descent^&#42;1^ of the valleys,^&#42;2^ which extends toward the settlement of Ar and adjoins the border of Moʹab.”

[NOTE]
====
. Lit., “mouth.”
. Or “wadis.”
====

[[v4-21-16]]

^<<v4-21-16,16>>^ Next they went on to Beʹer. This is the well about which Jehovah said to Moses: “Gather the people, and let me give them water.”

[[v4-21-17]]

^<<v4-21-17,17>>^ At that time, Israel sang this song:
“Spring up, O well!—Respond^&#42;1^ to it!

[NOTE]
====
. Or “Sing.”
====

[[v4-21-18]]

^<<v4-21-18,18>>^ The well that princes dug, that nobles of the people excavated,
With a commander’s staff and with their own staffs.”
Then they went from the wilderness on to Matʹta·nah,

[[v4-21-19]]

^<<v4-21-19,19>>^ from Matʹta·nah on to Na·halʹi·el, and from Na·halʹi·el on to Baʹmoth.

[[v4-21-20]]

^<<v4-21-20,20>>^ They went from Baʹmoth on to the valley that is in the territory^&#42;1^ of Moʹab, on top of Pisʹgah, which overlooks Je·shiʹmon.^&#42;2^

[NOTE]
====
. Lit., “field.”
. Or possibly, “the desert; the wilderness.”
====

[[v4-21-21]]

^<<v4-21-21,21>>^ Israel now sent messengers to Siʹhon, the king of the Amʹor·ites, saying:

[[v4-21-22]]

^<<v4-21-22,22>>^ “Let us pass through your land. We will not turn aside into a field or a vineyard. We will not drink water from any well. We will march on the King’s Road until we pass through your territory.”

[[v4-21-23]]

^<<v4-21-23,23>>^ But Siʹhon did not allow Israel to pass through his territory. Instead, Siʹhon gathered all his people and went out against Israel in the wilderness and came to Jaʹhaz and began fighting with Israel.

[[v4-21-24]]

^<<v4-21-24,24>>^ But Israel defeated him with the sword and took possession of his land from the Arʹnon to the Jabʹbok, near the Amʹmon·ites, because Jaʹzer borders the territory of the Amʹmon·ites.

[[v4-21-25]]

^<<v4-21-25,25>>^ So Israel took all these cities, and they began dwelling in all the cities of the Amʹor·ites, in Heshʹbon and all its dependent^&#42;1^ towns.

[NOTE]
====
. Or “surrounding.”
====

[[v4-21-26]]

^<<v4-21-26,26>>^ For Heshʹbon was the city of Siʹhon, the king of the Amʹor·ites, who had fought with the king of Moʹab and taken all his land from him as far as the Arʹnon.

[[v4-21-27]]

^<<v4-21-27,27>>^ That is what gave rise to the taunting proverbial saying:
“Come to Heshʹbon.
Let the city of Siʹhon be built and firmly established.

[[v4-21-28]]

^<<v4-21-28,28>>^ For a fire came out of Heshʹbon, a flame from the town of Siʹhon.
It has consumed Ar of Moʹab, the lords of the high places of the Arʹnon.

[[v4-21-29]]

^<<v4-21-29,29>>^ Woe to you, Moʹab! You will be destroyed, O people of Cheʹmosh!
He makes his sons fugitives and his daughters captives of Siʹhon, the king of the Amʹor·ites.

[[v4-21-30]]

^<<v4-21-30,30>>^ Let us shoot at them;
Heshʹbon will be destroyed as far as Diʹbon;
Let us desolate it as far as Noʹphah;
Fire will spread as far as Medʹe·ba.”

[[v4-21-31]]

^<<v4-21-31,31>>^ So Israel began to dwell in the land of the Amʹor·ites.

[[v4-21-32]]

^<<v4-21-32,32>>^ Moses then sent some men to spy on Jaʹzer. They captured its dependent^&#42;1^ towns and drove out the Amʹor·ites who were there.

[NOTE]
====
. Or “surrounding.”
====

[[v4-21-33]]

^<<v4-21-33,33>>^ After that they turned and went up by the Way of Baʹshan. And Og the king of Baʹshan came out with all his people to meet them in battle at Edʹre·i.

[[v4-21-34]]

^<<v4-21-34,34>>^ Jehovah said to Moses: “Do not be afraid of him, for I will give him and all his people and his land into your hand, and you will do to him just as you did to Siʹhon the king of the Amʹor·ites, who lived in Heshʹbon.”

[[v4-21-35]]

^<<v4-21-35,35>>^ So they kept striking him down, along with his sons and all his people, until none of his people survived, and they took possession of his land.

'''

xref:004-numbers/004-numbers-020.adoc#v4-20-0[&#60; Capítulo Anterior] | <<v4-21-0,Topo>> | xref:004-numbers/004-numbers-022.adoc#v4-22-0[Próximo Capítulo &#62;]