include::./index.adoc[]

[[v4-23-0]]
=== Numbers, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-23-1]]

^<<v4-23-1,1>>^ Then Baʹlaam said to Baʹlak: “Build on this spot seven altars, and prepare seven bulls and seven rams for me.”

[[v4-23-2]]

^<<v4-23-2,2>>^ Baʹlak immediately did just as Baʹlaam had said. And Baʹlak and Baʹlaam offered up a bull and a ram on each altar.

[[v4-23-3]]

^<<v4-23-3,3>>^ Baʹlaam then said to Baʹlak: “Stay here by your burnt offering, and I will go. Perhaps Jehovah will get in touch with me. Whatever he reveals to me, I will tell you.” So he went to a barren hill.

[[v4-23-4]]

^<<v4-23-4,4>>^ Then God got in touch with Baʹlaam, who said to Him: “I set the seven altars in rows, and I offered up a bull and a ram on each altar.”

[[v4-23-5]]

^<<v4-23-5,5>>^ Jehovah put this word in the mouth of Baʹlaam: “Return to Baʹlak, and this is what you are to say.”

[[v4-23-6]]

^<<v4-23-6,6>>^ So he returned and saw that Baʹlak and all the princes of Moʹab were standing by his burnt offering.

[[v4-23-7]]

^<<v4-23-7,7>>^ Then he spoke this proverbial saying:
“Baʹlak the king of Moʹab has brought me from Aʹram,
From the mountains of the east:
‘Do come to curse Jacob for me.
Yes, come to denounce Israel.’

[[v4-23-8]]

^<<v4-23-8,8>>^ How could I put a curse on those whom God has not cursed?
And how could I denounce those whom Jehovah has not denounced?

[[v4-23-9]]

^<<v4-23-9,9>>^ From the top of the rocks I see them,
And from the hills I see them.
As a people they dwell there alone;
They do not count themselves among the nations.

[[v4-23-10]]

^<<v4-23-10,10>>^ Who can number the dust particles of Jacob
Or count even the fourth part of Israel?
Let me^&#42;1^ die the death of the upright,
And let my end be like theirs.”

[NOTE]
====
. Or “my soul.”
====

[[v4-23-11]]

^<<v4-23-11,11>>^ Baʹlak then said to Baʹlaam: “What have you done to me? I brought you to put a curse on my enemies, and here you have done nothing but bless them.”

[[v4-23-12]]

^<<v4-23-12,12>>^ He answered: “Must I not speak whatever Jehovah puts in my mouth?”

[[v4-23-13]]

^<<v4-23-13,13>>^ Baʹlak said to him: “Please come with me to another place from which you can see them. You will see only a part of them; you will not see them all. Put a curse on them for me from there.”

[[v4-23-14]]

^<<v4-23-14,14>>^ So he took him to the field of Zoʹphim, to the top of Pisʹgah, and built seven altars and offered up a bull and a ram on each altar.

[[v4-23-15]]

^<<v4-23-15,15>>^ So Baʹlaam said to Baʹlak: “Stay here by your burnt offering while I get in touch with Him over there.”

[[v4-23-16]]

^<<v4-23-16,16>>^ And Jehovah got in touch with Baʹlaam and put this word in his mouth: “Return to Baʹlak, and this is what you are to say.”

[[v4-23-17]]

^<<v4-23-17,17>>^ So he came to him and saw that he was waiting by his burnt offering, and the princes of Moʹab were with him. Baʹlak asked him: “What has Jehovah said?”

[[v4-23-18]]

^<<v4-23-18,18>>^ Then he spoke this proverbial saying:
“Get up, Baʹlak, and listen.
Hear me, O son of Zipʹpor.

[[v4-23-19]]

^<<v4-23-19,19>>^ God is not a mere man who tells lies,
Nor a son of man who changes his mind.^&#42;1^
When he says something, will he not do it?
When he speaks, will he not carry it out?

[NOTE]
====
. Or “who feels regret.”
====

[[v4-23-20]]

^<<v4-23-20,20>>^ Look! I have been taken to bless;
Now He has blessed, and I cannot reverse it.

[[v4-23-21]]

^<<v4-23-21,21>>^ He does not tolerate any magical power against Jacob,
And he does not allow any trouble against Israel.
Jehovah his God is with them,
And he is loudly hailed as king among them.

[[v4-23-22]]

^<<v4-23-22,22>>^ God is bringing them out of Egypt.
He is like the horns of a wild bull for them.

[[v4-23-23]]

^<<v4-23-23,23>>^ For there are no omens of doom against Jacob,
Nor any divination against Israel.
At this time it may be said about Jacob and Israel:
‘Look at what God has done!’

[[v4-23-24]]

^<<v4-23-24,24>>^ Here is a people who will rise up like a lion,
And like the lion, it will raise itself up.
It will not lie down until it eats prey
And drinks the blood of the slain ones.”

[[v4-23-25]]

^<<v4-23-25,25>>^ Baʹlak then said to Baʹlaam: “If on the one hand you cannot put any curse on him, then on the other hand you should not bless him either.”

[[v4-23-26]]

^<<v4-23-26,26>>^ Baʹlaam answered Baʹlak: “Did I not say to you, ‘I will do all that Jehovah says’?”

[[v4-23-27]]

^<<v4-23-27,27>>^ Baʹlak said to Baʹlaam: “Please come and let me take you to yet another place. Perhaps it will be right in the eyes of the true God for you to put a curse on him for me from there.”

[[v4-23-28]]

^<<v4-23-28,28>>^ So Baʹlak took Baʹlaam to the top of Peʹor, which looks toward Je·shiʹmon.^&#42;1^

[NOTE]
====
. Or possibly, “the desert; the wilderness.”
====

[[v4-23-29]]

^<<v4-23-29,29>>^ Then Baʹlaam said to Baʹlak: “Build seven altars on this spot, and prepare seven bulls and seven rams for me.”

[[v4-23-30]]

^<<v4-23-30,30>>^ So Baʹlak did just as Baʹlaam had said, and he offered up a bull and a ram on each altar.

'''

xref:004-numbers/004-numbers-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numbers/004-numbers-024.adoc#v4-24-0[Próximo Capítulo &#62;]