include::./index.adoc[]

[[v4-8-0]]
=== Numbers, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-8-1]]

^<<v4-8-1,1>>^ Jehovah spoke to Moses, saying:

[[v4-8-2]]

^<<v4-8-2,2>>^ “Speak to Aaron and tell him, ‘When you light up the lamps, the seven lamps should shine on the area in front of the lampstand.’”

[[v4-8-3]]

^<<v4-8-3,3>>^ So Aaron did this: He lit up its lamps for the area in front of the lampstand, just as Jehovah had commanded Moses.

[[v4-8-4]]

^<<v4-8-4,4>>^ This is how the lampstand was made: It was hammered work of gold; from its stem to its blossoms, it was hammered work. The lampstand was made according to the vision that Jehovah had shown Moses.

[[v4-8-5]]

^<<v4-8-5,5>>^ Jehovah spoke again to Moses, saying:

[[v4-8-6]]

^<<v4-8-6,6>>^ “Take the Levites from among the Israelites, and cleanse them.

[[v4-8-7]]

^<<v4-8-7,7>>^ This is how you should cleanse them: Sprinkle sin-cleansing water on them, and they must shave their whole body with a razor, wash their garments, and cleanse themselves.

[[v4-8-8]]

^<<v4-8-8,8>>^ Then they will take a young bull and its grain offering of fine flour mixed with oil, and you will take another young bull for a sin offering.

[[v4-8-9]]

^<<v4-8-9,9>>^ And you are to present the Levites before the tent of meeting and gather all the assembly of the Israelites.

[[v4-8-10]]

^<<v4-8-10,10>>^ When you present the Levites before Jehovah, the Israelites are to lay their hands on the Levites.

[[v4-8-11]]

^<<v4-8-11,11>>^ And Aaron must offer^&#42;1^ the Levites before Jehovah as a wave offering from the Israelites, and they will carry out the service of Jehovah.

[NOTE]
====
. Lit., “wave,” that is, cause to move back and forth.
====

[[v4-8-12]]

^<<v4-8-12,12>>^ “Then the Levites will lay their hands on the heads of the bulls. After that, offer the one as a sin offering and the other as a burnt offering to Jehovah to make atonement for the Levites.

[[v4-8-13]]

^<<v4-8-13,13>>^ And you will have the Levites stand before Aaron and his sons and offer^&#42;1^ them as a wave offering to Jehovah.

[NOTE]
====
. Lit., “wave,” that is, cause to move back and forth.
====

[[v4-8-14]]

^<<v4-8-14,14>>^ You must separate the Levites from among the Israelites, and the Levites will become mine.

[[v4-8-15]]

^<<v4-8-15,15>>^ Afterward, the Levites will come in to serve at the tent of meeting. This is how you should cleanse them and offer^&#42;1^ them as a wave offering.

[NOTE]
====
. Lit., “wave,” that is, cause to move back and forth.
====

[[v4-8-16]]

^<<v4-8-16,16>>^ For they are given ones, given to me from among the Israelites. In place of all those who are firstborn^&#42;1^ of the Israelites, I will take them for myself.

[NOTE]
====
. Or “all the firstborn opening the wombs.”
====

[[v4-8-17]]

^<<v4-8-17,17>>^ For every firstborn among the Israelites is mine, both man and animal. I sanctified them to myself on the day I struck down every firstborn in the land of Egypt.

[[v4-8-18]]

^<<v4-8-18,18>>^ I will take the Levites in place of all the firstborn among the Israelites.

[[v4-8-19]]

^<<v4-8-19,19>>^ I will give the Levites as given ones to Aaron and his sons from among the Israelites, to carry out the service in behalf of the Israelites at the tent of meeting and to make atonement for the Israelites, so that no plague may occur among the Israelites because the people of Israel come near the holy place.”

[[v4-8-20]]

^<<v4-8-20,20>>^ Moses and Aaron and all the assembly of the Israelites did this with the Levites. In accord with all that Jehovah had commanded Moses regarding the Levites, that is what the Israelites did with them.

[[v4-8-21]]

^<<v4-8-21,21>>^ So the Levites purified themselves and washed their garments, after which Aaron offered^&#42;1^ them as a wave offering before Jehovah. Then Aaron made atonement for them to cleanse them.

[NOTE]
====
. Lit., “waved,” that is, caused to move back and forth.
====

[[v4-8-22]]

^<<v4-8-22,22>>^ Thereafter, the Levites went in to carry out their service at the tent of meeting before Aaron and his sons. Just as Jehovah had commanded Moses respecting the Levites, so they did with them.

[[v4-8-23]]

^<<v4-8-23,23>>^ Jehovah now spoke to Moses, saying:

[[v4-8-24]]

^<<v4-8-24,24>>^ “This applies to the Levites: From 25 years old and up, a man will join the company of those in the service of the tent of meeting.

[[v4-8-25]]

^<<v4-8-25,25>>^ But after the age of 50 years, he will retire from the service company and not serve any longer.

[[v4-8-26]]

^<<v4-8-26,26>>^ He may minister to his brothers who are taking care of the responsibilities at the tent of meeting, but he must not perform the service there. This is what you are to do regarding the Levites and their responsibilities.”

'''

xref:004-numbers/004-numbers-007.adoc#v4-7-0[&#60; Capítulo Anterior] | <<v4-8-0,Topo>> | xref:004-numbers/004-numbers-009.adoc#v4-9-0[Próximo Capítulo &#62;]