include::./index.adoc[]

[[v4-9-0]]
=== Numbers, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-9-1]]

^<<v4-9-1,1>>^ Jehovah spoke to Moses in the wilderness of Siʹnai in the first month of the second year after they had come out of the land of Egypt, saying:

[[v4-9-2]]

^<<v4-9-2,2>>^ “The Israelites should prepare the Passover sacrifice at its appointed time.

[[v4-9-3]]

^<<v4-9-3,3>>^ On the 14th day of this month at twilight,^&#42;1^ you should prepare it at its appointed time. According to all its statutes and all its set procedures, you should prepare it.”

[NOTE]
====
. Lit., “between the two evenings.”
====

[[v4-9-4]]

^<<v4-9-4,4>>^ So Moses told the Israelites to prepare the Passover sacrifice.

[[v4-9-5]]

^<<v4-9-5,5>>^ Then they prepared the Passover sacrifice in the first month, on the 14th day of the month at twilight,^&#42;1^ in the wilderness of Siʹnai. According to all that Jehovah had commanded Moses, so the Israelites did.

[NOTE]
====
. Lit., “between the two evenings.”
====

[[v4-9-6]]

^<<v4-9-6,6>>^ Now there were men who had become unclean by touching a dead body,^&#42;1^ so that they were not able to prepare the Passover sacrifice on that day. So those men presented themselves before Moses and Aaron on that day

[NOTE]
====
. Or “by a human soul.”
====

[[v4-9-7]]

^<<v4-9-7,7>>^ and said to him: “We are unclean because of touching a dead body.^&#42;1^ Why should we be kept from presenting the offering to Jehovah at its appointed time among the Israelites?”

[NOTE]
====
. Or “because of a human soul.”
====

[[v4-9-8]]

^<<v4-9-8,8>>^ At this Moses said to them: “Wait there, and let me hear what Jehovah may command regarding you.”

[[v4-9-9]]

^<<v4-9-9,9>>^ Then Jehovah said to Moses:

[[v4-9-10]]

^<<v4-9-10,10>>^ “Tell the Israelites, ‘Although any man among you or of your future generations should become unclean by touching a dead body^&#42;1^ or should be off on a distant journey, he must still prepare the Passover sacrifice to Jehovah.

[NOTE]
====
. Or “by a soul.”
====

[[v4-9-11]]

^<<v4-9-11,11>>^ They should prepare it in the second month, on the 14th day at twilight.^&#42;1^ They should eat it together with unleavened bread and bitter greens.

[NOTE]
====
. Lit., “between the two evenings.”
====

[[v4-9-12]]

^<<v4-9-12,12>>^ They must not let any of it remain until morning, and they should not break any bone in it. They should prepare it according to every statute regarding the Passover.

[[v4-9-13]]

^<<v4-9-13,13>>^ But if a man was clean or was not off on a journey and neglected to prepare the Passover sacrifice, that person^&#42;1^ must then be cut off^&#42;2^ from his people, because he did not present the offering of Jehovah at its appointed time. That man will answer for his sin.

[NOTE]
====
. Or “soul.”
. Or “put to death.”
====

[[v4-9-14]]

^<<v4-9-14,14>>^ “‘And if a foreign resident is residing with you, he should also prepare the Passover sacrifice to Jehovah. He should do so according to the statute of the Passover and its set procedure. There should exist one statute for you, both for the foreign resident and for the native of the land.’”

[[v4-9-15]]

^<<v4-9-15,15>>^ Now on the day the tabernacle was set up, the cloud covered the tabernacle, the tent of the Testimony, but in the evening what appeared to be fire remained over the tabernacle until morning.

[[v4-9-16]]

^<<v4-9-16,16>>^ That is what continued to take place: The cloud would cover it by day, and the appearance of fire by night.

[[v4-9-17]]

^<<v4-9-17,17>>^ Whenever the cloud lifted from the tent, the Israelites would promptly depart, and in the place where the cloud would remain, there is where the Israelites would encamp.

[[v4-9-18]]

^<<v4-9-18,18>>^ At the order of Jehovah the Israelites would depart, and at the order of Jehovah they would encamp. As long as the cloud remained over the tabernacle, they would remain encamped.

[[v4-9-19]]

^<<v4-9-19,19>>^ When the cloud would stay over the tabernacle for many days, the Israelites would obey Jehovah and not depart.

[[v4-9-20]]

^<<v4-9-20,20>>^ Sometimes the cloud would remain for a few days over the tabernacle. At the order of Jehovah they would remain encamped, and at the order of Jehovah they would depart.

[[v4-9-21]]

^<<v4-9-21,21>>^ Sometimes the cloud would remain only from evening until morning, and when the cloud lifted in the morning, they would depart. Whether it was day or night when the cloud lifted, they would depart.

[[v4-9-22]]

^<<v4-9-22,22>>^ Whether it was two days, a month, or longer, as long as the cloud stayed over the tabernacle, the Israelites remained encamped and would not depart. But when it lifted, they would depart.

[[v4-9-23]]

^<<v4-9-23,23>>^ At the order of Jehovah they would encamp, and at the order of Jehovah they would depart. They kept their obligation to Jehovah at the order of Jehovah through Moses.

'''

xref:004-numbers/004-numbers-008.adoc#v4-8-0[&#60; Capítulo Anterior] | <<v4-9-0,Topo>> | xref:004-numbers/004-numbers-010.adoc#v4-10-0[Próximo Capítulo &#62;]