include::./index.adoc[]

[[v4-26-0]]
=== Numbers, 26
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-26-1]]

^<<v4-26-1,1>>^ After the scourge, Jehovah said to Moses and El·e·aʹzar the son of Aaron the priest:

[[v4-26-2]]

^<<v4-26-2,2>>^ “Take a census of the whole assembly of the Israelites from 20 years of age and up, by their paternal houses, counting all those who can serve in the army in Israel.”

[[v4-26-3]]

^<<v4-26-3,3>>^ So Moses and El·e·aʹzar the priest spoke with them in the desert plains of Moʹab by the Jordan at Jerʹi·cho, saying:

[[v4-26-4]]

^<<v4-26-4,4>>^ “Take a census of them from the age of 20 years and up, just as Jehovah commanded Moses.”
Now the sons of Israel who went out of the land of Egypt were:

[[v4-26-5]]

^<<v4-26-5,5>>^ Reuʹben, Israel’s firstborn; Reuʹben’s sons were: of Haʹnoch, the family of the Haʹnoch·ites; of Palʹlu, the family of the Palʹlu·ites;

[[v4-26-6]]

^<<v4-26-6,6>>^ of Hezʹron, the family of the Hezʹron·ites; of Carʹmi, the family of the Carʹmites.

[[v4-26-7]]

^<<v4-26-7,7>>^ These were the families of the Reuʹben·ites, and their registered ones amounted to 43,730.

[[v4-26-8]]

^<<v4-26-8,8>>^ The son of Palʹlu was E·liʹab.

[[v4-26-9]]

^<<v4-26-9,9>>^ And the sons of E·liʹab were Nemʹu·el, Daʹthan, and A·biʹram. This Daʹthan and A·biʹram were chosen ones of the assembly who fought against Moses and Aaron along with Korʹah’s group when they fought against Jehovah.

[[v4-26-10]]

^<<v4-26-10,10>>^ Then the earth opened^&#42;1^ and swallowed them up. As for Korʹah, he died with his supporters when the fire consumed 250 men. And they became a warning example.

[NOTE]
====
. Lit., “opened its mouth.”
====

[[v4-26-11]]

^<<v4-26-11,11>>^ However, the sons of Korʹah did not die.

[[v4-26-12]]

^<<v4-26-12,12>>^ The sons of Simʹe·on by their families were: of Nemʹu·el, the family of the Nemʹu·el·ites; of Jaʹmin, the family of the Jaʹmin·ites; of Jaʹchin, the family of the Jaʹchin·ites;

[[v4-26-13]]

^<<v4-26-13,13>>^ of Zeʹrah, the family of the Zeʹrah·ites; of Shaʹul, the family of the Sha·uʹlites.

[[v4-26-14]]

^<<v4-26-14,14>>^ These were the families of the Simʹe·on·ites: 22,200.

[[v4-26-15]]

^<<v4-26-15,15>>^ The sons of Gad by their families were: of Zeʹphon, the family of the Zeʹphon·ites; of Hagʹgi, the family of the Hagʹgites; of Shuʹni, the family of the Shuʹnites;

[[v4-26-16]]

^<<v4-26-16,16>>^ of Ozʹni, the family of the Ozʹnites; of Eʹri, the family of the Eʹrites;

[[v4-26-17]]

^<<v4-26-17,17>>^ of Arʹod, the family of the Arʹod·ites; of A·reʹli, the family of the A·reʹlites.

[[v4-26-18]]

^<<v4-26-18,18>>^ These were the families of the sons of Gad, and their registered ones were 40,500.

[[v4-26-19]]

^<<v4-26-19,19>>^ The sons of Judah were Er and Oʹnan. However, Er and Oʹnan died in the land of Caʹnaan.

[[v4-26-20]]

^<<v4-26-20,20>>^ And the sons of Judah by their families were: of Sheʹlah, the family of the She·laʹnites; of Peʹrez, the family of the Perʹe·zites; of Zeʹrah, the family of the Zeʹrah·ites.

[[v4-26-21]]

^<<v4-26-21,21>>^ And the sons of Peʹrez were: of Hezʹron, the family of the Hezʹron·ites; of Haʹmul, the family of the Ha·muʹlites.

[[v4-26-22]]

^<<v4-26-22,22>>^ These were the families of Judah, and their registered ones were 76,500.

[[v4-26-23]]

^<<v4-26-23,23>>^ The sons of Isʹsa·char by their families were: of Toʹla, the family of the Toʹla·ites; of Puʹvah, the family of the Puʹnites;

[[v4-26-24]]

^<<v4-26-24,24>>^ of Jaʹshub, the family of the Jashʹu·bites; of Shimʹron, the family of the Shimʹron·ites.

[[v4-26-25]]

^<<v4-26-25,25>>^ These were the families of Isʹsa·char, and their registered ones were 64,300.

[[v4-26-26]]

^<<v4-26-26,26>>^ The sons of Zebʹu·lun by their families were: of Seʹred, the family of the Serʹe·dites; of Eʹlon, the family of the Eʹlon·ites; of Jahʹle·el, the family of the Jahʹle·el·ites.

[[v4-26-27]]

^<<v4-26-27,27>>^ These were the families of the Zebʹu·lun·ites, and their registered ones were 60,500.

[[v4-26-28]]

^<<v4-26-28,28>>^ The sons of Joseph by their families were: Ma·nasʹseh and Eʹphra·im.

[[v4-26-29]]

^<<v4-26-29,29>>^ The sons of Ma·nasʹseh were: of Maʹchir, the family of the Maʹchir·ites; and Maʹchir became father to Gilʹe·ad; of Gilʹe·ad, the family of the Gilʹe·ad·ites.

[[v4-26-30]]

^<<v4-26-30,30>>^ These were the sons of Gilʹe·ad: of Ieʹzer, the family of the Ieʹzer·ites; of Heʹlek, the family of the Heʹlek·ites;

[[v4-26-31]]

^<<v4-26-31,31>>^ of Asʹri·el, the family of the Asʹri·el·ites; of Sheʹchem, the family of the Sheʹchem·ites;

[[v4-26-32]]

^<<v4-26-32,32>>^ of She·miʹda, the family of the She·miʹda·ites; of Heʹpher, the family of the Heʹpher·ites.

[[v4-26-33]]

^<<v4-26-33,33>>^ Now Ze·loʹphe·had the son of Heʹpher had no sons, only daughters, and the names of the daughters of Ze·loʹphe·had were Mahʹlah, Noah, Hogʹlah, Milʹcah, and Tirʹzah.

[[v4-26-34]]

^<<v4-26-34,34>>^ These were the families of Ma·nasʹseh, and their registered ones were 52,700.

[[v4-26-35]]

^<<v4-26-35,35>>^ These were the sons of Eʹphra·im by their families: of Shuʹthe·lah, the family of the Shuʹthel·aʹhites; of Beʹcher, the family of the Beʹcher·ites; of Taʹhan, the family of the Taʹhan·ites.

[[v4-26-36]]

^<<v4-26-36,36>>^ And these were the sons of Shuʹthe·lah: of Eʹran, the family of the Eʹran·ites.

[[v4-26-37]]

^<<v4-26-37,37>>^ These were the families of the sons of Eʹphra·im, and their registered ones were 32,500. These were the sons of Joseph by their families.

[[v4-26-38]]

^<<v4-26-38,38>>^ The sons of Benjamin by their families were: of Beʹla, the family of the Beʹla·ites; of Ashʹbel, the family of the Ashʹbel·ites; of A·hiʹram, the family of the A·hiʹram·ites;

[[v4-26-39]]

^<<v4-26-39,39>>^ of She·phuʹpham, the family of the Shuʹpham·ites; of Huʹpham, the family of the Huʹpham·ites.

[[v4-26-40]]

^<<v4-26-40,40>>^ The sons of Beʹla were Ard and Naʹa·man: of Ard, the family of the Ardʹites; of Naʹa·man, the family of the Naʹa·mites.

[[v4-26-41]]

^<<v4-26-41,41>>^ These were the sons of Benjamin by their families, and their registered ones were 45,600.

[[v4-26-42]]

^<<v4-26-42,42>>^ These were the sons of Dan by their families: of Shuʹham, the family of the Shuʹham·ites. These were the families of Dan by their families.

[[v4-26-43]]

^<<v4-26-43,43>>^ All the families of the Shuʹham·ites, of their registered ones, were 64,400.

[[v4-26-44]]

^<<v4-26-44,44>>^ The sons of Ashʹer by their families were: of Imʹnah, the family of the Imʹnites; of Ishʹvi, the family of the Ishʹvites; of Be·riʹah, the family of the Be·riʹites;

[[v4-26-45]]

^<<v4-26-45,45>>^ of the sons of Be·riʹah: of Heʹber, the family of the Heʹber·ites; of Malʹchi·el, the family of the Malʹchi·el·ites.

[[v4-26-46]]

^<<v4-26-46,46>>^ The name of Ashʹer’s daughter was Seʹrah.

[[v4-26-47]]

^<<v4-26-47,47>>^ These were the families of the sons of Ashʹer, and their registered ones were 53,400.

[[v4-26-48]]

^<<v4-26-48,48>>^ The sons of Naphʹta·li by their families were: of Jahʹze·el, the family of the Jahʹze·el·ites; of Guʹni, the family of the Guʹnites;

[[v4-26-49]]

^<<v4-26-49,49>>^ of Jeʹzer, the family of the Jeʹzer·ites; of Shilʹlem, the family of the Shilʹlem·ites.

[[v4-26-50]]

^<<v4-26-50,50>>^ These were the families of Naphʹta·li by their families, and their registered ones were 45,400.

[[v4-26-51]]

^<<v4-26-51,51>>^ This is the total of those registered of the Israelites: 601,730.

[[v4-26-52]]

^<<v4-26-52,52>>^ After that Jehovah said to Moses:

[[v4-26-53]]

^<<v4-26-53,53>>^ “Among these the land should be divided as an inheritance according to the list of the names.^&#42;1^

[NOTE]
====
. Or “proportionate to the number of names listed.”
====

[[v4-26-54]]

^<<v4-26-54,54>>^ For the larger groups, you should increase the inheritance, and for the smaller groups, you should reduce the inheritance. Each group’s inheritance should be given in proportion to the number of those registered.

[[v4-26-55]]

^<<v4-26-55,55>>^ However, the land should be apportioned by lot. They should receive their inheritance according to the names of the tribes of their fathers.

[[v4-26-56]]

^<<v4-26-56,56>>^ Each inheritance will be determined by lot and apportioned among the larger and the smaller groups.”

[[v4-26-57]]

^<<v4-26-57,57>>^ Now these were the registered ones of the Levites by their families: of Gerʹshon, the family of the Gerʹshon·ites; of Koʹhath, the family of the Koʹhath·ites; of Me·rarʹi, the family of the Me·rarʹites.

[[v4-26-58]]

^<<v4-26-58,58>>^ These were the families of the Levites: the family of the Libʹnites, the family of the Hebʹron·ites, the family of the Mahʹlites, the family of the Muʹshites, the family of the Korʹah·ites.
Koʹhath became father to Amʹram.

[[v4-26-59]]

^<<v4-26-59,59>>^ And the name of Amʹram’s wife was Jochʹe·bed, Leʹvi’s daughter, whom his wife bore to Leʹvi in Egypt. And to Amʹram she bore Aaron and Moses and their sister Mirʹi·am.

[[v4-26-60]]

^<<v4-26-60,60>>^ Then to Aaron there were born Naʹdab, A·biʹhu, El·e·aʹzar, and Ithʹa·mar.

[[v4-26-61]]

^<<v4-26-61,61>>^ But Naʹdab and A·biʹhu died for presenting unauthorized fire before Jehovah.

[[v4-26-62]]

^<<v4-26-62,62>>^ The total of those registered was 23,000, all males from a month old and up. For they were not registered among the Israelites, because no inheritance was to be given to them among the Israelites.

[[v4-26-63]]

^<<v4-26-63,63>>^ These were the ones registered by Moses and El·e·aʹzar the priest when they registered the Israelites in the desert plains of Moʹab by the Jordan at Jerʹi·cho.

[[v4-26-64]]

^<<v4-26-64,64>>^ But among them there was no one who had been registered by Moses and Aaron the priest in the census of the Israelites taken in the wilderness of Siʹnai.

[[v4-26-65]]

^<<v4-26-65,65>>^ For Jehovah had said concerning them: “They will die without fail in the wilderness.” So there was not a man left of them except Caʹleb the son of Je·phunʹneh and Joshua the son of Nun.

'''

xref:004-numbers/004-numbers-025.adoc#v4-25-0[&#60; Capítulo Anterior] | <<v4-26-0,Topo>> | xref:004-numbers/004-numbers-027.adoc#v4-27-0[Próximo Capítulo &#62;]