include::./index.adoc[]

[[v4-17-0]]
=== Numbers, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-17-1]]

^<<v4-17-1,1>>^ Jehovah now said to Moses:

[[v4-17-2]]

^<<v4-17-2,2>>^ “Speak to the Israelites and take from them one rod for each paternal house, from the chieftains of each paternal house, 12 rods in all. Write the name of each one on his rod.

[[v4-17-3]]

^<<v4-17-3,3>>^ You should write Aaron’s name on Leʹvi’s rod, because there is one rod for the head of each paternal house.

[[v4-17-4]]

^<<v4-17-4,4>>^ Deposit the rods in the tent of meeting before the Testimony, where I regularly present myself to you.

[[v4-17-5]]

^<<v4-17-5,5>>^ And the rod of the man whom I choose will bud, and I will put a stop to the murmuring of the Israelites against me, which they are also murmuring against you.”

[[v4-17-6]]

^<<v4-17-6,6>>^ So Moses spoke to the Israelites, and all their chieftains gave him rods—a rod for each chieftain of a paternal house, 12 rods—and Aaron’s rod was among their rods.

[[v4-17-7]]

^<<v4-17-7,7>>^ Then Moses deposited the rods before Jehovah in the tent of the Testimony.

[[v4-17-8]]

^<<v4-17-8,8>>^ On the next day, when Moses went into the tent of the Testimony, look! Aaron’s rod for the house of Leʹvi had budded and was bringing forth buds and blossoming flowers and bearing ripe almonds.

[[v4-17-9]]

^<<v4-17-9,9>>^ Moses then brought out all the rods from before Jehovah to all the people of Israel. They looked at them, and each man took his own rod.

[[v4-17-10]]

^<<v4-17-10,10>>^ Jehovah then said to Moses: “Put Aaron’s rod back before the Testimony as something to be kept for a sign to the sons of rebelliousness, so that their murmurings against me may cease and so that they may not die.”

[[v4-17-11]]

^<<v4-17-11,11>>^ Moses immediately did just as Jehovah had commanded him. He did just so.

[[v4-17-12]]

^<<v4-17-12,12>>^ The Israelites then said to Moses: “Now we will die, we will surely perish, we are all going to perish!

[[v4-17-13]]

^<<v4-17-13,13>>^ Anyone who even comes close to Jehovah’s tabernacle will die! Must we end up dying that way?”

'''

xref:004-numbers/004-numbers-016.adoc#v4-16-0[&#60; Capítulo Anterior] | <<v4-17-0,Topo>> | xref:004-numbers/004-numbers-018.adoc#v4-18-0[Próximo Capítulo &#62;]