include::./index.adoc[]

[[v4-4-0]]
=== Numbers, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-4-1]]

^<<v4-4-1,1>>^ Jehovah now spoke to Moses and Aaron, saying:

[[v4-4-2]]

^<<v4-4-2,2>>^ “A census should be taken of the sons of Koʹhath from among the sons of Leʹvi, by their families and by their paternal houses,

[[v4-4-3]]

^<<v4-4-3,3>>^ all those from 30 to 50 years old who are in the group assigned to work in the tent of meeting.

[[v4-4-4]]

^<<v4-4-4,4>>^ “This is the service of the sons of Koʹhath in the tent of meeting. It is something most holy:

[[v4-4-5]]

^<<v4-4-5,5>>^ Aaron and his sons will come in when the camp is departing and take down the screening curtain and cover the ark of the Testimony with it.

[[v4-4-6]]

^<<v4-4-6,6>>^ They will put a sealskin covering over it and spread out a solid blue cloth over it and put its carrying poles in place.

[[v4-4-7]]

^<<v4-4-7,7>>^ “They will also spread out a blue cloth over the table of showbread, and they will put on it the dishes, the cups, the bowls, and the pitchers of the drink offering; the regular offering of bread should remain on it.

[[v4-4-8]]

^<<v4-4-8,8>>^ They will spread out a scarlet cloth over them and cover it with a sealskin covering and put its carrying poles in place.

[[v4-4-9]]

^<<v4-4-9,9>>^ Then they will take a blue cloth and cover the lampstand for the light, along with its lamps, its snuffers,^&#42;1^ its fire holders, and all its containers for oil that are used to maintain it.

[NOTE]
====
. Or “tongs.”
====

[[v4-4-10]]

^<<v4-4-10,10>>^ They will wrap it and all its utensils in a sealskin covering and put it on a carrying bar.

[[v4-4-11]]

^<<v4-4-11,11>>^ And they will spread out a blue cloth over the golden altar, cover it with a sealskin covering, and put its carrying poles in place.

[[v4-4-12]]

^<<v4-4-12,12>>^ They will then take all the utensils of the ministry with which they regularly minister in the holy place and put them in a blue cloth and cover them with a sealskin covering and put them on a carrying bar.

[[v4-4-13]]

^<<v4-4-13,13>>^ “They should remove the ashes^&#42;1^ from the altar and spread out a cloth of purple wool over it.

[NOTE]
====
. Or “fatty ashes,” that is, ashes soaked with the fat of the sacrifices.
====

[[v4-4-14]]

^<<v4-4-14,14>>^ They will put on it all its utensils that are used when they minister at the altar: the fire holders, the forks, the shovels, and the bowls, all the utensils of the altar; and they are to spread a sealskin covering over it and put its carrying poles in place.

[[v4-4-15]]

^<<v4-4-15,15>>^ “Aaron and his sons must finish covering the holy place and all the equipment of the holy place when the camp is departing. Then the sons of Koʹhath will come in to carry them, but they must not touch the holy place or they will die. These things are the responsibility^&#42;1^ of the sons of Koʹhath in connection with the tent of meeting.

[NOTE]
====
. Lit., “load.”
====

[[v4-4-16]]

^<<v4-4-16,16>>^ “El·e·aʹzar the son of Aaron the priest is responsible for overseeing the oil of the lighting, the perfumed incense, the regular grain offering, and the anointing oil. He has oversight of the entire tabernacle and all that is in it, including the holy place and its utensils.”

[[v4-4-17]]

^<<v4-4-17,17>>^ Jehovah spoke further to Moses and Aaron, saying:

[[v4-4-18]]

^<<v4-4-18,18>>^ “Do not let the tribe of the families of the Koʹhath·ites be cut off from among the Levites.

[[v4-4-19]]

^<<v4-4-19,19>>^ But do this for them that they may remain alive and not die because of approaching the most holy things. Aaron and his sons will go in and assign each of them to his service and what he is to carry.

[[v4-4-20]]

^<<v4-4-20,20>>^ They must not come in and see the holy things even for an instant, or they will die.”

[[v4-4-21]]

^<<v4-4-21,21>>^ Then Jehovah spoke to Moses, saying:

[[v4-4-22]]

^<<v4-4-22,22>>^ “A census should be taken of the sons of Gerʹshon by their paternal houses and their families.

[[v4-4-23]]

^<<v4-4-23,23>>^ You are to register all those from 30 to 50 years old who are in the group assigned to serve in the tent of meeting.

[[v4-4-24]]

^<<v4-4-24,24>>^ This is what the families of the Gerʹshon·ites are assigned to care for and to carry:

[[v4-4-25]]

^<<v4-4-25,25>>^ They will carry the tent cloths of the tabernacle, the tent of meeting, its covering and the sealskin covering that is on top over it, the screen^&#42;1^ of the entrance of the tent of meeting,

[NOTE]
====
. Or “curtain.”
====

[[v4-4-26]]

^<<v4-4-26,26>>^ the hanging curtains of the courtyard, the screen^&#42;1^ of the entrance of the courtyard that surrounds the tabernacle and the altar, their tent cords and all their utensils and everything used in its service. This is their assignment.

[NOTE]
====
. Or “curtain.”
====

[[v4-4-27]]

^<<v4-4-27,27>>^ All the service and the loads of the Gerʹshon·ites should be overseen by Aaron and his sons; you will assign all these loads as their responsibility.

[[v4-4-28]]

^<<v4-4-28,28>>^ This is the service that the families of the Gerʹshon·ites are to carry out in the tent of meeting, and their responsibilities are under the direction of Ithʹa·mar the son of Aaron the priest.

[[v4-4-29]]

^<<v4-4-29,29>>^ “As for the sons of Me·rarʹi, you will register them by family and by their paternal house.

[[v4-4-30]]

^<<v4-4-30,30>>^ From 30 to 50 years old you will register them, all who are in the group assigned to the service of the tent of meeting.

[[v4-4-31]]

^<<v4-4-31,31>>^ This is what they are responsible for carrying in connection with their service at the tent of meeting: the panel frames of the tabernacle, its bars, its pillars, its socket pedestals;

[[v4-4-32]]

^<<v4-4-32,32>>^ the pillars of the surrounding courtyard, their socket pedestals, their tent pins, and their tent cords together with all their equipment and all the service connected with these. You will assign to them by name the equipment they are responsible for carrying.

[[v4-4-33]]

^<<v4-4-33,33>>^ This is how the families of the sons of Me·rarʹi are to serve at the tent of meeting, under the direction of Ithʹa·mar the son of Aaron the priest.”

[[v4-4-34]]

^<<v4-4-34,34>>^ Moses and Aaron and the chieftains of the assembly then registered the sons of the Koʹhath·ites by their families and by their paternal house,

[[v4-4-35]]

^<<v4-4-35,35>>^ all those from 30 to 50 years old who were in the group assigned to the service of the tent of meeting.

[[v4-4-36]]

^<<v4-4-36,36>>^ The total of those registered by their families was 2,750.

[[v4-4-37]]

^<<v4-4-37,37>>^ These were registered from the families of the Koʹhath·ites, all those who were serving at the tent of meeting. Moses and Aaron registered them at the order of Jehovah through Moses.

[[v4-4-38]]

^<<v4-4-38,38>>^ The sons of Gerʹshon were registered by their families and by their paternal house,

[[v4-4-39]]

^<<v4-4-39,39>>^ all those from 30 to 50 years old who were in the group assigned to the service at the tent of meeting.

[[v4-4-40]]

^<<v4-4-40,40>>^ The total of those registered by their families and by their paternal house was 2,630.

[[v4-4-41]]

^<<v4-4-41,41>>^ This was the registration of the families of the sons of Gerʹshon, all those who were serving at the tent of meeting. Moses and Aaron had them registered at the order of Jehovah.

[[v4-4-42]]

^<<v4-4-42,42>>^ The sons of Me·rarʹi were registered by their families and by their paternal house,

[[v4-4-43]]

^<<v4-4-43,43>>^ all those from 30 to 50 years old who were in the group assigned to the service at the tent of meeting.

[[v4-4-44]]

^<<v4-4-44,44>>^ The total of those registered of them by their families was 3,200.

[[v4-4-45]]

^<<v4-4-45,45>>^ This was the registration of the families of the sons of Me·rarʹi, whom Moses and Aaron registered at the order of Jehovah through Moses.

[[v4-4-46]]

^<<v4-4-46,46>>^ Moses and Aaron and the chieftains of Israel registered all these Levites by their families and by their paternal houses;

[[v4-4-47]]

^<<v4-4-47,47>>^ they were from 30 to 50 years old, and all were assigned to serve and carry loads in connection with the tent of meeting.

[[v4-4-48]]

^<<v4-4-48,48>>^ The total of those registered was 8,580.

[[v4-4-49]]

^<<v4-4-49,49>>^ They were registered at the order of Jehovah through Moses, each according to his assigned service and his load; they were registered just as Jehovah had commanded Moses.

'''

xref:004-numbers/004-numbers-003.adoc#v4-3-0[&#60; Capítulo Anterior] | <<v4-4-0,Topo>> | xref:004-numbers/004-numbers-005.adoc#v4-5-0[Próximo Capítulo &#62;]