include::./index.adoc[]

[[v4-35-0]]
=== Numbers, 35
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-35-1]]

^<<v4-35-1,1>>^ Jehovah went on to speak to Moses on the desert plains of Moʹab by the Jordan at Jerʹi·cho, saying:

[[v4-35-2]]

^<<v4-35-2,2>>^ “Instruct the Israelites that they are to give the Levites cities to inhabit out of the inheritance they will possess, and they should give the Levites the pastures around the cities.

[[v4-35-3]]

^<<v4-35-3,3>>^ They will inhabit the cities, and the pastures will be for their livestock, their goods, and all their other animals.

[[v4-35-4]]

^<<v4-35-4,4>>^ The pastures of the cities that you will give the Levites will extend for 1,000 cubits^&#42;1^ from the wall all around the city.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
====

[[v4-35-5]]

^<<v4-35-5,5>>^ You should measure outside the city 2,000 cubits on the east side, 2,000 cubits on the south side, 2,000 cubits on the west side, and 2,000 cubits on the north side, with the city in the middle. These will be the pastures of their cities.

[[v4-35-6]]

^<<v4-35-6,6>>^ “The cities that you will give to the Levites will be 6 cities of refuge, which you will give for the manslayer to flee to, as well as 42 other cities.

[[v4-35-7]]

^<<v4-35-7,7>>^ You are to give to the Levites a total of 48 cities, together with their pastures.

[[v4-35-8]]

^<<v4-35-8,8>>^ The cities you give them will be from the possession of the Israelites. From the larger group you will take many, and from the smaller group you will take few. Each group will give some of its cities to the Levites in proportion to the inheritance that it receives.”

[[v4-35-9]]

^<<v4-35-9,9>>^ Jehovah continued to speak to Moses, saying:

[[v4-35-10]]

^<<v4-35-10,10>>^ “Speak to the Israelites and tell them, ‘You are crossing the Jordan to the land of Caʹnaan.

[[v4-35-11]]

^<<v4-35-11,11>>^ You should choose cities convenient for yourselves to serve as cities of refuge, where the manslayer who unintentionally kills someone^&#42;1^ should flee.

[NOTE]
====
. Or “strikes a soul.”
====

[[v4-35-12]]

^<<v4-35-12,12>>^ These cities will serve as a refuge for you from the blood avenger, so that the manslayer will not die until he stands trial before the assembly.

[[v4-35-13]]

^<<v4-35-13,13>>^ The six cities of refuge that you provide will serve this purpose.

[[v4-35-14]]

^<<v4-35-14,14>>^ You will provide three cities on this side of the Jordan and three cities in the land of Caʹnaan to serve as cities of refuge.

[[v4-35-15]]

^<<v4-35-15,15>>^ These six cities will serve as a refuge for the Israelites, for the foreign resident, and for the settler among them, for anyone to flee there who unintentionally kills someone.^&#42;1^

[NOTE]
====
. Or “strikes a soul.”
====

[[v4-35-16]]

^<<v4-35-16,16>>^ “‘But if he struck him with an iron instrument and he dies, he is a murderer. The murderer should be put to death without fail.

[[v4-35-17]]

^<<v4-35-17,17>>^ And if he struck him with a stone that could cause death and he dies, he is a murderer. The murderer should be put to death without fail.

[[v4-35-18]]

^<<v4-35-18,18>>^ And if he struck him with a wooden instrument that could cause death and he dies, he is a murderer. The murderer should be put to death without fail.

[[v4-35-19]]

^<<v4-35-19,19>>^ “‘The avenger of blood is the one who will put the murderer to death. When he encounters him, he himself will put him to death.

[[v4-35-20]]

^<<v4-35-20,20>>^ If death resulted because he pushed him out of hatred or threw something at him with malicious intent,^&#42;1^

[NOTE]
====
. Lit., “while lying in wait.”
====

[[v4-35-21]]

^<<v4-35-21,21>>^ or out of hatred he struck him with his hand, and he died, the one who struck him will be put to death without fail. He is a murderer. The avenger of blood will put the murderer to death when he encounters him.

[[v4-35-22]]

^<<v4-35-22,22>>^ “‘But if it was unexpectedly and not out of hatred that he pushed him or threw any article at him without malicious intent,^&#42;1^

[NOTE]
====
. Lit., “without lying in wait.”
====

[[v4-35-23]]

^<<v4-35-23,23>>^ or if he did not see him and caused a stone to fall on him and he was not an enemy or seeking his injury, and the person died,

[[v4-35-24]]

^<<v4-35-24,24>>^ the assembly should then judge between the one who struck him and the avenger of blood, in harmony with these judgments.

[[v4-35-25]]

^<<v4-35-25,25>>^ The assembly should then save the manslayer from the hand of the avenger of blood and return him to his city of refuge to which he had fled, and he must dwell in it until the death of the high priest who was anointed with the holy oil.

[[v4-35-26]]

^<<v4-35-26,26>>^ “‘But if the manslayer goes out of the boundary of his city of refuge to which he fled

[[v4-35-27]]

^<<v4-35-27,27>>^ and the avenger of blood finds him outside the boundary of his city of refuge and slays the manslayer, he has no bloodguilt.

[[v4-35-28]]

^<<v4-35-28,28>>^ For he must dwell in his city of refuge until the high priest’s death. But after the high priest’s death, the manslayer may return to the land that he owns.

[[v4-35-29]]

^<<v4-35-29,29>>^ These things will serve for you as a statute for judgment throughout your generations in all your dwelling places.

[[v4-35-30]]

^<<v4-35-30,30>>^ “‘Whoever kills a person^&#42;1^ should be put to death as a murderer on the testimony^&#42;2^ of witnesses; but no one^&#42;3^ will be put to death on the testimony of just one witness.

[NOTE]
====
. Or “soul.”
. Lit., “mouth.”
. Or “soul.”
====

[[v4-35-31]]

^<<v4-35-31,31>>^ You must take no ransom for the life^&#42;1^ of a murderer who is deserving to die, for he should be put to death without fail.

[NOTE]
====
. Or “soul.”
====

[[v4-35-32]]

^<<v4-35-32,32>>^ And you must not take a ransom for one who has fled to his city of refuge, allowing him to resume dwelling in his land before the death of the high priest.

[[v4-35-33]]

^<<v4-35-33,33>>^ “‘You must not pollute the land in which you live, for blood pollutes the land, and there may be no atonement for the blood that has been spilled on the land except by the blood of the one who spilled it.

[[v4-35-34]]

^<<v4-35-34,34>>^ You must not defile the land in which you dwell, in which I am residing; for I, Jehovah, am residing in the midst of the people of Israel.’”

'''

xref:004-numbers/004-numbers-034.adoc#v4-34-0[&#60; Capítulo Anterior] | <<v4-35-0,Topo>> | xref:004-numbers/004-numbers-036.adoc#v4-36-0[Próximo Capítulo &#62;]