include::./index.adoc[]

[[v4-27-0]]
=== Numbers, 27
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-27-1]]

^<<v4-27-1,1>>^ Then the daughters of Ze·loʹphe·had, the son of Heʹpher, the son of Gilʹe·ad, the son of Maʹchir, the son of Ma·nasʹseh, of the families of Ma·nasʹseh the son of Joseph, approached. The names of his daughters were Mahʹlah, Noah, Hogʹlah, Milʹcah, and Tirʹzah.

[[v4-27-2]]

^<<v4-27-2,2>>^ They stood before Moses, El·e·aʹzar the priest, the chieftains, and all the assembly at the entrance of the tent of meeting and said:

[[v4-27-3]]

^<<v4-27-3,3>>^ “Our father died in the wilderness, but he was not among the group who banded together against Jehovah, the supporters of Korʹah, but he died for his own sin and he did not have any sons.

[[v4-27-4]]

^<<v4-27-4,4>>^ Why should the name of our father be lost from his family because he had no son? Give us a possession among our father’s brothers.”

[[v4-27-5]]

^<<v4-27-5,5>>^ So Moses presented their case before Jehovah.

[[v4-27-6]]

^<<v4-27-6,6>>^ Jehovah then said this to Moses:

[[v4-27-7]]

^<<v4-27-7,7>>^ “The daughters of Ze·loʹphe·had are correct. You should by all means give them the possession as an inheritance among their father’s brothers and transfer their father’s inheritance to them.

[[v4-27-8]]

^<<v4-27-8,8>>^ And tell the Israelites, ‘If a man dies without having a son, you must then cause his inheritance to pass to his daughter.

[[v4-27-9]]

^<<v4-27-9,9>>^ And if he has no daughter, you will give his inheritance to his brothers.

[[v4-27-10]]

^<<v4-27-10,10>>^ And if he has no brothers, you will give his inheritance to his father’s brothers.

[[v4-27-11]]

^<<v4-27-11,11>>^ And if his father has no brothers, you will give his inheritance to the closest blood relative in his family, and he will take possession of it. This will serve as a statute by judicial decision for the Israelites, just as Jehovah has commanded Moses.’”

[[v4-27-12]]

^<<v4-27-12,12>>^ Then Jehovah said to Moses: “Go up into this mountain of Abʹa·rim, and view the land that I will give the Israelites.

[[v4-27-13]]

^<<v4-27-13,13>>^ When you have seen it, you will also be gathered to your people,^&#42;1^ just as Aaron your brother was,

[NOTE]
====
. This is a poetic expression for death.
====

[[v4-27-14]]

^<<v4-27-14,14>>^ because when the assembly was quarreling with me in the wilderness of Zin, you rebelled against my order to sanctify me before them by means of the waters. These are the waters of Merʹi·bah at Kaʹdesh in the wilderness of Zin.”

[[v4-27-15]]

^<<v4-27-15,15>>^ Then Moses said to Jehovah:

[[v4-27-16]]

^<<v4-27-16,16>>^ “Let Jehovah, the God of the spirit of all people,^&#42;1^ appoint over the assembly a man

[NOTE]
====
. Lit., “the spirits of all flesh.”
====

[[v4-27-17]]

^<<v4-27-17,17>>^ who will go out and come in before them and who will lead them out and bring them in, so that Jehovah’s assembly may not become like sheep that have no shepherd.”

[[v4-27-18]]

^<<v4-27-18,18>>^ So Jehovah said to Moses: “Take Joshua the son of Nun, a man in whom there is spirit, and lay your hand on him.

[[v4-27-19]]

^<<v4-27-19,19>>^ Then stand him before El·e·aʹzar the priest and before all the assembly, and you must commission him before their eyes.

[[v4-27-20]]

^<<v4-27-20,20>>^ You are to confer some of your authority^&#42;1^ on him, so that all the assembly of the Israelites may listen to him.

[NOTE]
====
. Or “dignity.”
====

[[v4-27-21]]

^<<v4-27-21,21>>^ He will stand before El·e·aʹzar the priest, who will inquire in his behalf by the judgment of the Uʹrim before Jehovah. At his order they will go out and at his order they will come in, he and all the Israelites with him and all the assembly.”

[[v4-27-22]]

^<<v4-27-22,22>>^ So Moses did just as Jehovah had commanded him. He took Joshua and stood him before El·e·aʹzar the priest and before all the assembly,

[[v4-27-23]]

^<<v4-27-23,23>>^ and he laid his hands on him and commissioned him, just as Jehovah had spoken through Moses.

'''

xref:004-numbers/004-numbers-026.adoc#v4-26-0[&#60; Capítulo Anterior] | <<v4-27-0,Topo>> | xref:004-numbers/004-numbers-028.adoc#v4-28-0[Próximo Capítulo &#62;]