include::./index.adoc[]

[[v4-11-0]]
=== Numbers, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-11-1]]

^<<v4-11-1,1>>^ Now the people began to complain bitterly before Jehovah. When Jehovah heard it, his anger flared, and a fire from Jehovah began to blaze against them and to consume some on the outskirts of the camp.

[[v4-11-2]]

^<<v4-11-2,2>>^ When the people began to cry out to Moses, he made supplication to Jehovah, and the fire died out.

[[v4-11-3]]

^<<v4-11-3,3>>^ So that place was given the name Tabʹe·rah,^&#42;1^ because a fire from Jehovah had blazed against them.

[NOTE]
====
. Meaning “Burning,” that is, a conflagration; blaze.
====

[[v4-11-4]]

^<<v4-11-4,4>>^ The mixed crowd^&#42;1^ who were in their midst then expressed selfish longing, and the Israelites too began to weep again and say: “Who will give us meat to eat?

[NOTE]
====
. Apparently the non-Israelites among them.
====

[[v4-11-5]]

^<<v4-11-5,5>>^ How fondly we remember the fish that we used to eat without cost in Egypt, also the cucumbers, the watermelons, the leeks, the onions, and the garlic!

[[v4-11-6]]

^<<v4-11-6,6>>^ But now we^&#42;1^ are withering away. We see nothing at all except this manna.”

[NOTE]
====
. Or “our souls.”
====

[[v4-11-7]]

^<<v4-11-7,7>>^ Incidentally, the manna was like coriander seed, and it looked like bdellium gum.

[[v4-11-8]]

^<<v4-11-8,8>>^ The people would spread out and pick it up and grind it in hand mills or pound it in a mortar. Then they would boil it in cooking pots or make it into round loaves, and it tasted like an oiled sweet cake.

[[v4-11-9]]

^<<v4-11-9,9>>^ When the dew descended on the camp by night, the manna would also descend on it.

[[v4-11-10]]

^<<v4-11-10,10>>^ Moses heard the people weeping, family after family, each man at the entrance of his tent. And Jehovah became very angry, and Moses was also very displeased.

[[v4-11-11]]

^<<v4-11-11,11>>^ Then Moses said to Jehovah: “Why have you afflicted your servant? Why have I not found favor in your eyes, so that you put the burden of all this people on me?

[[v4-11-12]]

^<<v4-11-12,12>>^ Did I conceive all this people? Did I give birth to them, so that you should tell me, ‘Carry them in your bosom, just as an attendant^&#42;1^ carries the nursing child,’ to the land that you swore to give to their forefathers?

[NOTE]
====
. Or “a male nurse.”
====

[[v4-11-13]]

^<<v4-11-13,13>>^ From where will I get meat to give to all this people? For they keep weeping before me, saying, ‘Give us meat to eat!’

[[v4-11-14]]

^<<v4-11-14,14>>^ I am not able to bear all this people by myself; it is too much for me.

[[v4-11-15]]

^<<v4-11-15,15>>^ If this is how you are going to treat me, please kill me right now. If I have found favor in your eyes, do not make me see any more calamity.”

[[v4-11-16]]

^<<v4-11-16,16>>^ Jehovah replied to Moses: “Gather for me 70 men from the elders of Israel, men whom you recognize as^&#42;1^ elders and officials of the people, and take them to the tent of meeting, and have them stand there with you.

[NOTE]
====
. Or “who you know are; who are known to you as.”
====

[[v4-11-17]]

^<<v4-11-17,17>>^ I will come down and speak with you there, and I will take away some of the spirit that is on you and place it on them, and they will help you in bearing the burden of the people so that you may not have to bear it alone.

[[v4-11-18]]

^<<v4-11-18,18>>^ You should say to the people, ‘Sanctify yourselves for tomorrow, for you will certainly eat meat, because you have wept in Jehovah’s hearing and have said: “Who will give us meat to eat? It was better for us in Egypt.” Jehovah will certainly give you meat, and you will eat.

[[v4-11-19]]

^<<v4-11-19,19>>^ You will eat, not one day nor 2 days nor 5 days nor 10 days nor 20 days,

[[v4-11-20]]

^<<v4-11-20,20>>^ but for a whole month of days, until it comes out of your nostrils and it has become loathsome to you, for you rejected Jehovah, who is in your midst, and you were weeping before him, saying: “Why is it that we have come out of Egypt?”’”

[[v4-11-21]]

^<<v4-11-21,21>>^ Then Moses said: “The people I am among number 600,000 men on foot, and yet you yourself have said, ‘Meat I will give them, and they will eat enough for a whole month of days’!

[[v4-11-22]]

^<<v4-11-22,22>>^ If whole flocks and herds were slaughtered, would it be enough for them? Or if all the fish of the sea were caught, would it be enough for them?”

[[v4-11-23]]

^<<v4-11-23,23>>^ Jehovah then said to Moses: “Is the hand of Jehovah too short? Now you will see whether what I say will happen to you or not.”

[[v4-11-24]]

^<<v4-11-24,24>>^ So Moses went out and spoke the words of Jehovah to the people. And he gathered 70 men from the elders of the people and had them stand around the tent.

[[v4-11-25]]

^<<v4-11-25,25>>^ Then Jehovah came down in a cloud and spoke to him and took away some of the spirit that was on him and put it on each of the 70 elders. And as soon as the spirit settled down on them, they began to behave as prophets,^&#42;1^ but they did not do it again.

[NOTE]
====
. Or “began to prophesy.”
====

[[v4-11-26]]

^<<v4-11-26,26>>^ There were two of the men still in the camp. Their names were Elʹdad and Meʹdad. And the spirit began to settle down on them, as they were among those whose names had been written down, but they had not gone out to the tent. So they began to behave as prophets in the camp.

[[v4-11-27]]

^<<v4-11-27,27>>^ And a young man ran and reported to Moses: “Elʹdad and Meʹdad are behaving as prophets in the camp!”

[[v4-11-28]]

^<<v4-11-28,28>>^ Then Joshua the son of Nun, the minister of Moses from his youth, responded and said: “My lord Moses, restrain them!”

[[v4-11-29]]

^<<v4-11-29,29>>^ But Moses said to him: “Are you jealous for me? No, I wish that all of Jehovah’s people were prophets and that Jehovah would put his spirit on them!”

[[v4-11-30]]

^<<v4-11-30,30>>^ Later Moses returned to the camp along with the elders of Israel.

[[v4-11-31]]

^<<v4-11-31,31>>^ Then a wind from Jehovah sprang up and began driving quail from the sea and causing them to fall around the camp, about a day’s journey on this side and a day’s journey on the other side, all around the camp, and they were about two cubits^&#42;1^ deep on the ground.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
====

[[v4-11-32]]

^<<v4-11-32,32>>^ So all that day and all night and all the next day, the people stayed up and gathered the quail. No one gathered less than ten hoʹmers,^&#42;1^ and they kept spreading them all around the camp for themselves.

[NOTE]
====
. A homer equaled 220 L (200 dry qt). See App. B14.
====

[[v4-11-33]]

^<<v4-11-33,33>>^ But while the meat was still between their teeth, before it could be chewed, Jehovah’s anger blazed against the people, and Jehovah began striking the people with a very great slaughter.

[[v4-11-34]]

^<<v4-11-34,34>>^ So they gave that place the name Kibʹroth-hat·taʹa·vah,^&#42;1^ because there they buried the people who showed selfish craving.

[NOTE]
====
. Meaning “Burial Places of the Craving.”
====

[[v4-11-35]]

^<<v4-11-35,35>>^ From Kibʹroth-hat·taʹa·vah the people departed for Ha·zeʹroth, and they remained at Ha·zeʹroth.

'''

xref:004-numbers/004-numbers-010.adoc#v4-10-0[&#60; Capítulo Anterior] | <<v4-11-0,Topo>> | xref:004-numbers/004-numbers-012.adoc#v4-12-0[Próximo Capítulo &#62;]