include::./index.adoc[]

[[v4-36-0]]
=== Numbers, 36
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-36-1]]

^<<v4-36-1,1>>^ The family heads of the descendants of Gilʹe·ad the son of Maʹchir the son of Ma·nasʹseh of the families of the sons of Joseph approached and spoke before Moses and the chieftains, the family heads of the Israelites.

[[v4-36-2]]

^<<v4-36-2,2>>^ They said: “Jehovah commanded my lord to distribute the land by lot as an inheritance to the Israelites; and my lord was commanded by Jehovah to give the inheritance of our brother Ze·loʹphe·had to his daughters.

[[v4-36-3]]

^<<v4-36-3,3>>^ If they marry men from another Israelite tribe, the women’s inheritance will also be withdrawn from the inheritance of our fathers and be added to the inheritance of the tribe to which they would then belong, so that it would be withdrawn from the lot of our inheritance.

[[v4-36-4]]

^<<v4-36-4,4>>^ Now when the Jubilee takes place for the people of Israel, the women’s inheritance will also be added to the inheritance of the tribe to which they then belong, so that their inheritance would be withdrawn from the inheritance of the tribe of our fathers.”

[[v4-36-5]]

^<<v4-36-5,5>>^ Then Moses commanded the Israelites at the order of Jehovah: “What the tribe of the sons of Joseph is saying is correct.

[[v4-36-6]]

^<<v4-36-6,6>>^ This is the word that Jehovah has commanded for the daughters of Ze·loʹphe·had: ‘They may marry whomever they wish. However, they should marry someone from a family of the tribe of their father.

[[v4-36-7]]

^<<v4-36-7,7>>^ No inheritance of the Israelites should circulate from tribe to tribe, for the Israelites should hold on to the inheritance of the tribe of their forefathers.

[[v4-36-8]]

^<<v4-36-8,8>>^ And every daughter who possesses an inheritance among the tribes of Israel should become a wife of a descendant of her father’s tribe, so that the Israelites may keep possession of the inheritance of their forefathers.

[[v4-36-9]]

^<<v4-36-9,9>>^ No inheritance should circulate from one tribe to another tribe, for the tribes of Israel should hold on to their own inheritance.’”

[[v4-36-10]]

^<<v4-36-10,10>>^ The daughters of Ze·loʹphe·had did just as Jehovah had commanded Moses.

[[v4-36-11]]

^<<v4-36-11,11>>^ So Mahʹlah, Tirʹzah, Hogʹlah, Milʹcah, and Noah, the daughters of Ze·loʹphe·had, married the sons of their father’s brothers.

[[v4-36-12]]

^<<v4-36-12,12>>^ They became wives of men from the families of Ma·nasʹseh the son of Joseph so that their inheritance would remain in the tribe of their father’s family.

[[v4-36-13]]

^<<v4-36-13,13>>^ These are the commandments and the judicial decisions that Jehovah gave to the Israelites through Moses on the desert plains of Moʹab by the Jordan at Jerʹi·cho.

'''

xref:004-numbers/004-numbers-035.adoc#v4-35-0[&#60; Capítulo Anterior] | <<v4-36-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-001.adoc#v5-1-0[Próximo Capítulo &#62;]