include::./index.adoc[]

[[v4-14-0]]
=== Numbers, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-14-1]]

^<<v4-14-1,1>>^ Then all the assembly raised their voice, and the people continued crying out and weeping all through that night.

[[v4-14-2]]

^<<v4-14-2,2>>^ All the Israelites began to murmur against Moses and Aaron, and the whole assembly spoke against them, saying: “If only we had died in the land of Egypt, or if only we had died in this wilderness!

[[v4-14-3]]

^<<v4-14-3,3>>^ Why is Jehovah bringing us to this land to fall by the sword? Our wives and children will become plunder. Is it not better for us to return to Egypt?”

[[v4-14-4]]

^<<v4-14-4,4>>^ They were even saying to one another: “Let us appoint a leader and return to Egypt!”

[[v4-14-5]]

^<<v4-14-5,5>>^ At this Moses and Aaron fell with their faces to the ground before the whole assembled congregation of the Israelites.

[[v4-14-6]]

^<<v4-14-6,6>>^ Joshua the son of Nun and Caʹleb the son of Je·phunʹneh, who were among those who spied out the land, ripped their garments apart,

[[v4-14-7]]

^<<v4-14-7,7>>^ and they said this to all the assembly of the Israelites: “The land that we passed through to spy out is a very, very good land.

[[v4-14-8]]

^<<v4-14-8,8>>^ If Jehovah is pleased with us, he will certainly bring us into this land and give it to us, a land that is flowing with milk and honey.

[[v4-14-9]]

^<<v4-14-9,9>>^ But you must not rebel against Jehovah, and you must not fear the people of the land, for we will devour them.^&#42;1^ Their protection has been removed from them, and Jehovah is with us. Do not fear them.”

[NOTE]
====
. Lit., “for they are bread to us.”
====

[[v4-14-10]]

^<<v4-14-10,10>>^ However, all the assembly talked of stoning them. But Jehovah’s glory appeared on the tent of meeting to all the people of Israel.

[[v4-14-11]]

^<<v4-14-11,11>>^ Then Jehovah said to Moses: “How much longer will this people treat me without respect, and how much longer will they not put faith in me in spite of all the signs that I performed among them?

[[v4-14-12]]

^<<v4-14-12,12>>^ Let me strike them with pestilence and drive them away, and let me make you into a nation greater and mightier than they are.”

[[v4-14-13]]

^<<v4-14-13,13>>^ But Moses said to Jehovah: “Then the Egyptians, from whose midst you brought this people out by your power, will hear,

[[v4-14-14]]

^<<v4-14-14,14>>^ and they will speak about it to the inhabitants of this land. These also have heard that you, Jehovah, are among this people and have appeared to them face-to-face. You are Jehovah, and your cloud is standing over them, and you are going before them in the pillar of cloud by day and in the pillar of fire by night.

[[v4-14-15]]

^<<v4-14-15,15>>^ If you put this people to death all at once,^&#42;1^ the nations who have heard of your fame would say this:

[NOTE]
====
. Lit., “as one man.”
====

[[v4-14-16]]

^<<v4-14-16,16>>^ ‘Jehovah was not able to bring this people into the land he swore to give them, so he slaughtered them in the wilderness.’

[[v4-14-17]]

^<<v4-14-17,17>>^ Please, now, Jehovah, let your power be great, as you promised when you said:

[[v4-14-18]]

^<<v4-14-18,18>>^ ‘Jehovah, slow to anger and abundant in loyal love,^&#42;1^ pardoning error and transgression, but he will by no means leave the guilty unpunished, bringing punishment for the error of fathers upon sons, upon the third generation and upon the fourth generation.’

[NOTE]
====
. Or “loving-kindness.”
====

[[v4-14-19]]

^<<v4-14-19,19>>^ Forgive, please, the error of this people according to your great loyal love, just as you have pardoned this people from Egypt until now.”

[[v4-14-20]]

^<<v4-14-20,20>>^ Then Jehovah said: “I forgive them according to your word.

[[v4-14-21]]

^<<v4-14-21,21>>^ But on the other hand, as surely as I live, all the earth will be filled with the glory of Jehovah.

[[v4-14-22]]

^<<v4-14-22,22>>^ However, not one of the men who have seen my glory and my signs that I performed in Egypt and in the wilderness and yet have kept testing me these ten times and have not listened to my voice

[[v4-14-23]]

^<<v4-14-23,23>>^ will ever see the land about which I swore to their fathers. No, not one of those treating me without respect will see it.

[[v4-14-24]]

^<<v4-14-24,24>>^ But because my servant Caʹleb had a different spirit and kept following after me wholeheartedly, I will certainly bring him into the land where he went, and his offspring will take possession of it.

[[v4-14-25]]

^<<v4-14-25,25>>^ Since the A·malʹek·ites and the Caʹnaan·ites are dwelling in the valley,^&#42;1^ you should turn back tomorrow and set off for the wilderness by the way of the Red Sea.”

[NOTE]
====
. Or “low plain.”
====

[[v4-14-26]]

^<<v4-14-26,26>>^ Jehovah then said to Moses and Aaron:

[[v4-14-27]]

^<<v4-14-27,27>>^ “How much longer will this evil assembly keep up this murmuring against me? I have heard what the Israelites are murmuring against me.

[[v4-14-28]]

^<<v4-14-28,28>>^ Say to them, ‘“As surely as I live,” declares Jehovah, “I will do to you just what I have heard you speak!

[[v4-14-29]]

^<<v4-14-29,29>>^ In this wilderness your corpses will fall, yes, the whole number of you from 20 years old and up who were registered, all of you who have murmured against me.

[[v4-14-30]]

^<<v4-14-30,30>>^ None of you will enter into the land that I swore^&#42;1^ to have you reside in except Caʹleb the son of Je·phunʹneh and Joshua the son of Nun.

[NOTE]
====
. Lit., “I lifted my hand.”
====

[[v4-14-31]]

^<<v4-14-31,31>>^ “‘“And I will bring in your children, who you said would become plunder, and they will get to know the land that you have rejected.

[[v4-14-32]]

^<<v4-14-32,32>>^ But your own corpses will fall in this wilderness.

[[v4-14-33]]

^<<v4-14-33,33>>^ Now your sons will become shepherds in the wilderness 40 years, and they will have to answer for your acts of unfaithfulness^&#42;1^ until the last one of your corpses falls in the wilderness.

[NOTE]
====
. Lit., “prostitution.”
====

[[v4-14-34]]

^<<v4-14-34,34>>^ According to the number of the days that you spied out the land, 40 days, a day for a year, a day for a year, you will answer for your errors 40 years, for you will know what it means to oppose me.^&#42;1^

[NOTE]
====
. Or “to have me as an enemy.”
====

[[v4-14-35]]

^<<v4-14-35,35>>^ “‘“I, Jehovah, have spoken. This is what I will do to all this evil assembly, those who have gathered together against me: In this wilderness they will come to their end, and here they will die.

[[v4-14-36]]

^<<v4-14-36,36>>^ The men whom Moses sent to spy out the land and who caused the whole assembly to murmur against him when they returned with a bad report about the land,

[[v4-14-37]]

^<<v4-14-37,37>>^ yes, the men who brought back the bad report about the land will be struck down and die before Jehovah.

[[v4-14-38]]

^<<v4-14-38,38>>^ But Joshua the son of Nun and Caʹleb the son of Je·phunʹneh, who were among those who went to spy out the land, will certainly keep living.”’”

[[v4-14-39]]

^<<v4-14-39,39>>^ When Moses spoke these words to all the Israelites, the people began to mourn a great deal.

[[v4-14-40]]

^<<v4-14-40,40>>^ Moreover, they got up early in the morning and tried to go up to the top of the mountain, saying: “Here we are ready to go up to the place that Jehovah spoke about, for we have sinned.”

[[v4-14-41]]

^<<v4-14-41,41>>^ But Moses said: “Why are you going beyond the order of Jehovah? This will not succeed.

[[v4-14-42]]

^<<v4-14-42,42>>^ Do not go up, for Jehovah is not with you; and you will be defeated by your enemies.

[[v4-14-43]]

^<<v4-14-43,43>>^ For the A·malʹek·ites and the Caʹnaan·ites are there to face you, and you will fall by the sword. Because you turned away from following Jehovah, Jehovah will not be with you.”

[[v4-14-44]]

^<<v4-14-44,44>>^ However, they presumptuously went toward the top of the mountain, but the ark of Jehovah’s covenant and Moses did not move away from the middle of the camp.

[[v4-14-45]]

^<<v4-14-45,45>>^ Then the A·malʹek·ites and the Caʹnaan·ites who were dwelling in that mountain came down and struck them, scattering them as far as Horʹmah.

'''

xref:004-numbers/004-numbers-013.adoc#v4-13-0[&#60; Capítulo Anterior] | <<v4-14-0,Topo>> | xref:004-numbers/004-numbers-015.adoc#v4-15-0[Próximo Capítulo &#62;]