include::./index.adoc[]

[[v4-20-0]]
=== Numbers, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-20-1]]

^<<v4-20-1,1>>^ In the first month, the entire assembly of the Israelites came into the wilderness of Zin, and the people began dwelling in Kaʹdesh. It was there that Mirʹi·am died and was buried.

[[v4-20-2]]

^<<v4-20-2,2>>^ Now there was no water for the assembly, and they gathered together against Moses and Aaron.

[[v4-20-3]]

^<<v4-20-3,3>>^ The people were quarreling with Moses, saying: “If only we had died when our brothers died before Jehovah!

[[v4-20-4]]

^<<v4-20-4,4>>^ Why have you brought Jehovah’s congregation into this wilderness for us and our livestock to die here?

[[v4-20-5]]

^<<v4-20-5,5>>^ And why have you led us up out of Egypt to bring us into this evil place? It is no place for seed and figs and vines and pomegranates, and there is no water to drink.”

[[v4-20-6]]

^<<v4-20-6,6>>^ Then Moses and Aaron came from before the congregation to the entrance of the tent of meeting and fell with their faces to the ground, and Jehovah’s glory began to appear to them.

[[v4-20-7]]

^<<v4-20-7,7>>^ Then Jehovah said to Moses:

[[v4-20-8]]

^<<v4-20-8,8>>^ “Take the rod and call the assembly together, you and Aaron your brother, and speak to the crag before their eyes that it may give its water, and you will bring out water for them from the crag and give the assembly and their livestock something to drink.”

[[v4-20-9]]

^<<v4-20-9,9>>^ So Moses took the rod from before Jehovah, just as He had commanded him.

[[v4-20-10]]

^<<v4-20-10,10>>^ Then Moses and Aaron called the congregation together before the crag, and he said to them: “Hear, now, you rebels! Must we bring out water for you from this crag?”

[[v4-20-11]]

^<<v4-20-11,11>>^ With that Moses lifted his hand up and struck the crag twice with his rod, and much water began to pour out, and the assembly and their livestock began to drink.

[[v4-20-12]]

^<<v4-20-12,12>>^ Jehovah later said to Moses and Aaron: “Because you did not show faith in me and sanctify me before the eyes of the people of Israel, you will not bring this congregation into the land that I will give them.”

[[v4-20-13]]

^<<v4-20-13,13>>^ These are the waters of Merʹi·bah,^&#42;1^ where the Israelites quarreled with Jehovah, so that he was sanctified among them.

[NOTE]
====
. Meaning “Quarreling.”
====

[[v4-20-14]]

^<<v4-20-14,14>>^ Then Moses sent messengers from Kaʹdesh to the king of Eʹdom: “This is what your brother Israel says, ‘You well know all the hardship that we have experienced.

[[v4-20-15]]

^<<v4-20-15,15>>^ Our fathers went to Egypt, and we dwelled in Egypt many years,^&#42;1^ and the Egyptians mistreated us and our fathers.

[NOTE]
====
. Lit., “days.”
====

[[v4-20-16]]

^<<v4-20-16,16>>^ Finally we cried out to Jehovah, and he heard us and sent an angel and brought us out of Egypt, and here we are in Kaʹdesh, a city on the border of your territory.

[[v4-20-17]]

^<<v4-20-17,17>>^ Please let us pass through your land. We will not pass through any field or vineyard, and we will not drink the water of any well. We will march on the King’s Road without turning to the right or the left until we pass through your territory.’”

[[v4-20-18]]

^<<v4-20-18,18>>^ However, Eʹdom said to him: “You may not pass through our territory. If you do, I will come out with the sword to meet you.”

[[v4-20-19]]

^<<v4-20-19,19>>^ In turn the Israelites said to him: “By the highway we will go up, and if we and our livestock drink your water, we will pay for it. We want nothing more than to pass through on foot.”

[[v4-20-20]]

^<<v4-20-20,20>>^ Still he said: “You may not pass through.” With that Eʹdom came out to encounter him with many people and a strong army.^&#42;1^

[NOTE]
====
. Lit., “hand.”
====

[[v4-20-21]]

^<<v4-20-21,21>>^ So Eʹdom refused to allow Israel to pass through his territory; therefore, Israel turned away from him.

[[v4-20-22]]

^<<v4-20-22,22>>^ The people of Israel, the entire assembly, departed from Kaʹdesh and came to Mount Hor.

[[v4-20-23]]

^<<v4-20-23,23>>^ Then Jehovah said to Moses and Aaron in Mount Hor by the border of the land of Eʹdom:

[[v4-20-24]]

^<<v4-20-24,24>>^ “Aaron will be gathered to his people.^&#42;1^ He will not enter the land that I will give to the Israelites, because you both rebelled against my order regarding the waters of Merʹi·bah.

[NOTE]
====
. This is a poetic expression for death.
====

[[v4-20-25]]

^<<v4-20-25,25>>^ Take Aaron and his son El·e·aʹzar and bring them up into Mount Hor.

[[v4-20-26]]

^<<v4-20-26,26>>^ Remove Aaron’s garments and clothe El·e·aʹzar his son with them, and Aaron will die there.”^&#42;1^

[NOTE]
====
. Lit., “will be gathered and die there.”
====

[[v4-20-27]]

^<<v4-20-27,27>>^ So Moses did just as Jehovah had commanded, and they climbed Mount Hor before the eyes of all the assembly.

[[v4-20-28]]

^<<v4-20-28,28>>^ Then Moses removed Aaron’s garments and clothed El·e·aʹzar his son with them. After that Aaron died there on the top of the mountain. And Moses and El·e·aʹzar came down from the mountain.

[[v4-20-29]]

^<<v4-20-29,29>>^ When all the assembly saw that Aaron had died, the entire house of Israel wept for Aaron for 30 days.

'''

xref:004-numbers/004-numbers-019.adoc#v4-19-0[&#60; Capítulo Anterior] | <<v4-20-0,Topo>> | xref:004-numbers/004-numbers-021.adoc#v4-21-0[Próximo Capítulo &#62;]