include::./index.adoc[]

[[v4-31-0]]
=== Numbers, 31
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-31-1]]

^<<v4-31-1,1>>^ Jehovah then told Moses:

[[v4-31-2]]

^<<v4-31-2,2>>^ “Take vengeance for the Israelites on the Midʹi·an·ites. Afterward you will be gathered to your people.”^&#42;1^

[NOTE]
====
. This is a poetic expression for death.
====

[[v4-31-3]]

^<<v4-31-3,3>>^ So Moses spoke to the people, saying: “Equip men from among you for battle^&#42;1^ against Midʹi·an and to execute Jehovah’s vengeance on Midʹi·an.

[NOTE]
====
. Or “for the army.”
====

[[v4-31-4]]

^<<v4-31-4,4>>^ You should send 1,000 of each tribe of all the tribes of Israel into the army.”

[[v4-31-5]]

^<<v4-31-5,5>>^ So from the thousands of Israel, 1,000 were assigned from each tribe, 12,000 equipped for battle.^&#42;1^

[NOTE]
====
. Or “for the army.”
====

[[v4-31-6]]

^<<v4-31-6,6>>^ Then Moses sent them out, 1,000 from each tribe to the army, along with Phinʹe·has the son of El·e·aʹzar the priest for the army, who had the holy utensils and the signal trumpets in his hand.

[[v4-31-7]]

^<<v4-31-7,7>>^ They waged war against Midʹi·an, just as Jehovah had commanded Moses, and they killed every male.

[[v4-31-8]]

^<<v4-31-8,8>>^ Along with the others slain, they killed the kings of Midʹi·an, namely, Eʹvi, Reʹkem, Zur, Hur, and Reʹba, the five kings of Midʹi·an. They also killed Baʹlaam the son of Beʹor with the sword.

[[v4-31-9]]

^<<v4-31-9,9>>^ But the Israelites carried off captive the women and children of Midʹi·an. They also plundered all their domestic animals, all their livestock, and all their possessions.

[[v4-31-10]]

^<<v4-31-10,10>>^ And all their cities in which they had settled and all their encampments^&#42;1^ they burned with fire.

[NOTE]
====
. Or “walled camps.”
====

[[v4-31-11]]

^<<v4-31-11,11>>^ And they took all the spoil and all the plunder, both humans and animals.

[[v4-31-12]]

^<<v4-31-12,12>>^ Then they brought the captives, the plunder, and the spoil to Moses and El·e·aʹzar the priest and to the assembly of the Israelites, to the camp in the desert plains of Moʹab near the Jordan at Jerʹi·cho.

[[v4-31-13]]

^<<v4-31-13,13>>^ Then Moses and El·e·aʹzar the priest and all the chieftains of the assembly went out to meet them outside the camp.

[[v4-31-14]]

^<<v4-31-14,14>>^ But Moses grew indignant at the appointed men of the combat forces, the chiefs of the thousands and the chiefs of the hundreds who were coming in from the military expedition.

[[v4-31-15]]

^<<v4-31-15,15>>^ Moses said to them: “Have you preserved all the females alive?

[[v4-31-16]]

^<<v4-31-16,16>>^ Look! They are the ones who by Baʹlaam’s word induced the Israelites to commit unfaithfulness toward Jehovah over the affair of Peʹor, so that the scourge came upon the assembly of Jehovah.

[[v4-31-17]]

^<<v4-31-17,17>>^ Now you should kill every male among the children and kill every woman who has had sexual relations with a man.

[[v4-31-18]]

^<<v4-31-18,18>>^ But you may keep alive all the young girls who have not had sexual relations with a man.

[[v4-31-19]]

^<<v4-31-19,19>>^ And you should camp outside the camp seven days. Every one of you who has killed someone^&#42;1^ and every one of you who has touched someone slain should purify himself on the third day and on the seventh day, you and your captives.

[NOTE]
====
. Or “a soul.”
====

[[v4-31-20]]

^<<v4-31-20,20>>^ And you should purify from sin every garment, every article of skin, everything made of goat hair, and every article of wood.”

[[v4-31-21]]

^<<v4-31-21,21>>^ El·e·aʹzar the priest then said to the men of the army who had gone into the battle: “This is the statute of the law that Jehovah commanded Moses,

[[v4-31-22]]

^<<v4-31-22,22>>^ ‘Only the gold, the silver, the copper, the iron, the tin, and the lead,

[[v4-31-23]]

^<<v4-31-23,23>>^ everything that can be processed with fire, you should pass through the fire, and it will be clean. However, it should also be purified by the water for cleansing. Everything that cannot be processed with fire, you should pass through the water.

[[v4-31-24]]

^<<v4-31-24,24>>^ And you should wash your garments on the seventh day and be clean, and then you may come into the camp.’”

[[v4-31-25]]

^<<v4-31-25,25>>^ Jehovah then said this to Moses:

[[v4-31-26]]

^<<v4-31-26,26>>^ “Take an inventory of the plunder, counting the captives both of humans and animals; do this together with El·e·aʹzar the priest and the heads of the paternal houses of the assembly.

[[v4-31-27]]

^<<v4-31-27,27>>^ Divide what was plundered into two parts to be shared between those in the army who took part in the battle and all the rest of the assembly.

[[v4-31-28]]

^<<v4-31-28,28>>^ As a tax for Jehovah, you should take from the soldiers who went out into the battle one soul^&#42;1^ out of every 500, of the people, the herd, the donkeys, and the flock.

[NOTE]
====
. See Glossary.
====

[[v4-31-29]]

^<<v4-31-29,29>>^ You should take it from their half and give it to El·e·aʹzar the priest as Jehovah’s contribution.

[[v4-31-30]]

^<<v4-31-30,30>>^ From the half given to the Israelites, you should take one out of 50, of the people, the herd, the donkeys, the flock, and every sort of domestic animal, and give them to the Levites, who care for the responsibilities connected with Jehovah’s tabernacle.”

[[v4-31-31]]

^<<v4-31-31,31>>^ So Moses and El·e·aʹzar the priest did just as Jehovah had commanded Moses.

[[v4-31-32]]

^<<v4-31-32,32>>^ The spoils, the rest of the plunder that the people of the expedition had taken, amounted to 675,000 of the flock,

[[v4-31-33]]

^<<v4-31-33,33>>^ 72,000 of the herd,

[[v4-31-34]]

^<<v4-31-34,34>>^ and 61,000 donkeys.

[[v4-31-35]]

^<<v4-31-35,35>>^ The women who had not had sexual relations with a man amounted to 32,000 women.^&#42;1^

[NOTE]
====
. Or “souls.”
====

[[v4-31-36]]

^<<v4-31-36,36>>^ The half that was the share of those who went out into the battle amounted to 337,500 of the flock.

[[v4-31-37]]

^<<v4-31-37,37>>^ The tax for Jehovah from the flock amounted to 675.

[[v4-31-38]]

^<<v4-31-38,38>>^ And there were 36,000 of the herd, and the tax on them for Jehovah was 72.

[[v4-31-39]]

^<<v4-31-39,39>>^ And there were 30,500 donkeys, and the tax on them for Jehovah was 61.

[[v4-31-40]]

^<<v4-31-40,40>>^ And there were 16,000 humans,^&#42;1^ and the tax on them for Jehovah was 32 persons.^&#42;2^

[NOTE]
====
. Or “human souls.”
. Or “souls.”
====

[[v4-31-41]]

^<<v4-31-41,41>>^ Then Moses gave the tax as Jehovah’s contribution to El·e·aʹzar the priest, just as Jehovah had commanded Moses.

[[v4-31-42]]

^<<v4-31-42,42>>^ From the half belonging to the Israelites, which Moses had divided off from the portion that belonged to the men who waged war,

[[v4-31-43]]

^<<v4-31-43,43>>^ that half of the flock amounted to 337,500,

[[v4-31-44]]

^<<v4-31-44,44>>^ and of the herd, 36,000,

[[v4-31-45]]

^<<v4-31-45,45>>^ and of the donkeys, 30,500,

[[v4-31-46]]

^<<v4-31-46,46>>^ and of the people,^&#42;1^ 16,000.

[NOTE]
====
. Or “the human souls.”
====

[[v4-31-47]]

^<<v4-31-47,47>>^ Then Moses took from the half belonging to the Israelites one out of 50, of the people and of the animals, and gave them to the Levites, who cared for the responsibility of Jehovah’s tabernacle, just as Jehovah had commanded Moses.

[[v4-31-48]]

^<<v4-31-48,48>>^ Then the appointed men who were of the thousands of the army, the chiefs of the thousands and the chiefs of the hundreds, approached Moses,

[[v4-31-49]]

^<<v4-31-49,49>>^ and they said to Moses: “Your servants have taken the count of the men of war who are under our command, and not one has been reported missing from us.

[[v4-31-50]]

^<<v4-31-50,50>>^ So let us each present what he has found as Jehovah’s offering, articles of gold, ankle chains, bracelets, signet rings, earrings, and other jewelry, in order to make atonement for ourselves^&#42;1^ before Jehovah.”

[NOTE]
====
. Or “our souls.”
====

[[v4-31-51]]

^<<v4-31-51,51>>^ So Moses and El·e·aʹzar the priest accepted the gold from them, all the jewelry.

[[v4-31-52]]

^<<v4-31-52,52>>^ All the gold of the contribution that they made to Jehovah amounted to 16,750 shekels,^&#42;1^ from the chiefs of the thousands and the chiefs of the hundreds.

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v4-31-53]]

^<<v4-31-53,53>>^ The men of the army had each taken plunder for himself.

[[v4-31-54]]

^<<v4-31-54,54>>^ Moses and El·e·aʹzar the priest accepted the gold from the chiefs of the thousands and of the hundreds and brought it into the tent of meeting as a reminder^&#42;1^ for the people of Israel before Jehovah.

[NOTE]
====
. Or “memorial.”
====

'''

xref:004-numbers/004-numbers-030.adoc#v4-30-0[&#60; Capítulo Anterior] | <<v4-31-0,Topo>> | xref:004-numbers/004-numbers-032.adoc#v4-32-0[Próximo Capítulo &#62;]