include::./index.adoc[]

[[v4-25-0]]
=== Numbers, 25
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v4-25-1]]

^<<v4-25-1,1>>^ When Israel was dwelling in Shitʹtim, the people started to commit sexual immorality with the daughters of Moʹab.

[[v4-25-2]]

^<<v4-25-2,2>>^ The women invited the people to the sacrifices of their gods, and the people began to eat and to bow down to their gods.

[[v4-25-3]]

^<<v4-25-3,3>>^ So Israel joined in worship of^&#42;1^ the Baʹal of Peʹor, and Jehovah became enraged with Israel.

[NOTE]
====
. Or “attached itself to.”
====

[[v4-25-4]]

^<<v4-25-4,4>>^ Jehovah said to Moses: “Take all the leaders^&#42;1^ of these people and hang them up before Jehovah in broad daylight,^&#42;2^ that the burning anger of Jehovah may turn back from Israel.”

[NOTE]
====
. Lit., “heads.”
. Lit., “in front of the sun.”
====

[[v4-25-5]]

^<<v4-25-5,5>>^ Then Moses said to the judges of Israel: “Each one of you should kill his men who joined in worship of^&#42;1^ the Baʹal of Peʹor.”

[NOTE]
====
. Or “attached themselves to.”
====

[[v4-25-6]]

^<<v4-25-6,6>>^ But just then, there came one of the Israelites bringing near to his brothers a Midʹi·an·ite woman before the eyes of Moses and of all the assembly of the Israelites, while they were weeping at the entrance of the tent of meeting.

[[v4-25-7]]

^<<v4-25-7,7>>^ When Phinʹe·has the son of El·e·aʹzar the son of Aaron the priest saw it, he immediately rose up from the midst of the assembly and took a spear^&#42;1^ in his hand.

[NOTE]
====
. Or “lance.”
====

[[v4-25-8]]

^<<v4-25-8,8>>^ Then he went after the man of Israel into the tent and pierced both of them through, the man of Israel and the woman through her genital parts. At that the scourge on the Israelites was halted.

[[v4-25-9]]

^<<v4-25-9,9>>^ Those who died from the scourge amounted to 24,000.

[[v4-25-10]]

^<<v4-25-10,10>>^ Then Jehovah said to Moses:

[[v4-25-11]]

^<<v4-25-11,11>>^ “Phinʹe·has the son of El·e·aʹzar the son of Aaron the priest has turned my wrath away from the people of Israel because he tolerated no rivalry at all toward me among them. So I have not exterminated the Israelites in my insistence on exclusive devotion.

[[v4-25-12]]

^<<v4-25-12,12>>^ Therefore, say, ‘I am giving him my covenant of peace.

[[v4-25-13]]

^<<v4-25-13,13>>^ And it will serve as the covenant of a lasting priesthood for him and his offspring after him, because he tolerated no rivalry toward his God and he made atonement for the people of Israel.’”

[[v4-25-14]]

^<<v4-25-14,14>>^ Incidentally, the name of the Israelite man who was put to death along with the Midʹi·an·i·tess was Zimʹri the son of Saʹlu, a chieftain of a paternal house of the Simʹe·on·ites.

[[v4-25-15]]

^<<v4-25-15,15>>^ The name of the Midʹi·an·ite woman who was put to death was Cozʹbi the daughter of Zur; he was a leader of the clans of a paternal house in Midʹi·an.

[[v4-25-16]]

^<<v4-25-16,16>>^ Jehovah later said to Moses:

[[v4-25-17]]

^<<v4-25-17,17>>^ “Harass the Midʹi·an·ites and strike them down,

[[v4-25-18]]

^<<v4-25-18,18>>^ because they have been harassing you with their cunning dealings against you in the affair of Peʹor and of Cozʹbi the daughter of a chieftain of Midʹi·an, their sister who was put to death in the day of the scourge over the affair of Peʹor.”

'''

xref:004-numbers/004-numbers-024.adoc#v4-24-0[&#60; Capítulo Anterior] | <<v4-25-0,Topo>> | xref:004-numbers/004-numbers-026.adoc#v4-26-0[Próximo Capítulo &#62;]