include::./index.adoc[]

[[v27-6-0]]
=== Daniel, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v27-6-1]]

^<<v27-6-1,1>>^ It seemed good to Da·riʹus to appoint 120 satraps over the whole kingdom.

[[v27-6-2]]

^<<v27-6-2,2>>^ Over them were three high officials, one of whom was Daniel; and the satraps would report to them, so that the king would not suffer loss.

[[v27-6-3]]

^<<v27-6-3,3>>^ Now Daniel was distinguishing himself over the other high officials and the satraps, for there was an extraordinary spirit in him, and the king intended to elevate him over the entire kingdom.

[[v27-6-4]]

^<<v27-6-4,4>>^ At that time the high officials and the satraps were seeking to find some grounds for accusation against Daniel respecting matters of state,^&#42;1^ but they could find no grounds for accusation or anything corrupt, for he was trustworthy and no negligence or corruption could be found in him.

[NOTE]
====
. Lit., “the kingdom.”
====

[[v27-6-5]]

^<<v27-6-5,5>>^ These men then said: “We will find in this Daniel no grounds for accusation at all, unless we find it against him in the law of his God.”

[[v27-6-6]]

^<<v27-6-6,6>>^ So these high officials and satraps went in as a group to the king, and they said to him: “O King Da·riʹus, may you live on forever.

[[v27-6-7]]

^<<v27-6-7,7>>^ All the royal officials, prefects, satraps, high royal officers, and governors have consulted together to establish a royal decree and to enforce a ban,^&#42;1^ that for 30 days whoever makes a petition to any god or man except to you, O king, should be thrown into the lions’ pit.

[NOTE]
====
. Or “an interdict.”
====

[[v27-6-8]]

^<<v27-6-8,8>>^ Now, O king, may you establish the decree and sign it, so that it cannot be changed, according to the law of the Medes and the Persians, which cannot be annulled.”

[[v27-6-9]]

^<<v27-6-9,9>>^ So King Da·riʹus signed the decree and the ban.

[[v27-6-10]]

^<<v27-6-10,10>>^ But as soon as Daniel knew that the decree had been signed, he went to his house, which had the windows of his roof chamber open toward Jerusalem. And three times a day he got down on his knees and prayed and offered praise before his God, as he had regularly done prior to this.

[[v27-6-11]]

^<<v27-6-11,11>>^ At that time those men burst in and found Daniel petitioning and pleading for favor before his God.

[[v27-6-12]]

^<<v27-6-12,12>>^ So they approached the king and reminded him about the royal ban: “Did you not sign a ban stating that for 30 days any man who makes a petition to any god or man except to you, O king, should be thrown into the lions’ pit?” The king replied: “The matter is well-established according to the law of the Medes and the Persians, which cannot be annulled.”

[[v27-6-13]]

^<<v27-6-13,13>>^ They immediately said to the king: “Daniel, who is of the exiles of Judah, has paid no regard to you, O king, nor to the ban that you signed, but three times a day he is praying.”

[[v27-6-14]]

^<<v27-6-14,14>>^ As soon as the king heard this, he was greatly distressed, and he tried to think of a way to rescue Daniel; and until the sun set he made every effort to save him.

[[v27-6-15]]

^<<v27-6-15,15>>^ Finally those men went in as a group to the king, and they said to the king: “Take note, O king, that the law of the Medes and the Persians is that any ban or decree that the king establishes cannot be changed.”

[[v27-6-16]]

^<<v27-6-16,16>>^ So the king gave the order, and they brought Daniel and threw him into the pit of lions. The king said to Daniel: “Your God whom you are continually serving will rescue you.”

[[v27-6-17]]

^<<v27-6-17,17>>^ Then a stone was brought and placed over the entrance^&#42;1^ of the pit, and the king sealed it with his signet ring and with the signet ring of his nobles, so that nothing could be changed with regard to Daniel.

[NOTE]
====
. Lit., “mouth.”
====

[[v27-6-18]]

^<<v27-6-18,18>>^ The king then went to his palace. He passed the night fasting and refused any entertainment,^&#42;1^ and he could not sleep.^&#42;2^

[NOTE]
====
. Or possibly, “no musicians were brought in.”
. Lit., “his sleep fled from him.”
====

[[v27-6-19]]

^<<v27-6-19,19>>^ Finally at the first light of dawn, the king got up and hurried to the lions’ pit.

[[v27-6-20]]

^<<v27-6-20,20>>^ As he got near the pit, he called out to Daniel with a sad voice. The king asked Daniel: “O Daniel, servant of the living God, has your God whom you are continually serving been able to rescue you from the lions?”

[[v27-6-21]]

^<<v27-6-21,21>>^ Daniel immediately said to the king: “O king, may you live on forever.

[[v27-6-22]]

^<<v27-6-22,22>>^ My God sent his angel and shut the mouth of the lions, and they have not harmed me, for I was found innocent before him; nor have I done any wrong to you, O king.”

[[v27-6-23]]

^<<v27-6-23,23>>^ The king was overjoyed, and he commanded that Daniel be lifted up out of the pit. When Daniel was lifted up out of the pit, he was completely unharmed, because he had trusted in his God.

[[v27-6-24]]

^<<v27-6-24,24>>^ The king then gave an order, and the men who had accused^&#42;1^ Daniel were brought, and they were thrown into the lions’ pit, along with their sons and their wives. They had not reached the bottom of the pit before the lions overpowered them and crushed all their bones.

[NOTE]
====
. Or “slandered.”
====

[[v27-6-25]]

^<<v27-6-25,25>>^ Then King Da·riʹus wrote to all the peoples, nations, and language groups dwelling throughout the earth: “May you have abundant peace!

[[v27-6-26]]

^<<v27-6-26,26>>^ I am issuing an order that in every domain of my kingdom, people are to tremble in fear before the God of Daniel. For he is the living God and he endures forever. His kingdom will never be destroyed, and his rulership^&#42;1^ is eternal.

[NOTE]
====
. Or “sovereignty.”
====

[[v27-6-27]]

^<<v27-6-27,27>>^ He rescues, saves, and performs signs and wonders in the heavens and on the earth, for he rescued Daniel from the paw of the lions.”

[[v27-6-28]]

^<<v27-6-28,28>>^ So this Daniel prospered in the kingdom of Da·riʹus and in the kingdom of Cyrus the Persian.

'''

xref:027-daniel/027-daniel-005.adoc#v27-5-0[&#60; Capítulo Anterior] | <<v27-6-0,Topo>> | xref:027-daniel/027-daniel-007.adoc#v27-7-0[Próximo Capítulo &#62;]