include::./index.adoc[]

[[v27-10-0]]
=== Daniel, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v27-10-1]]

^<<v27-10-1,1>>^ In the third year of King Cyrus of Persia, a revelation was given to Daniel, who was called by the name Bel·te·shazʹzar; and the message was true, and it was about a great conflict. And he understood the message and was given understanding about what he had seen.

[[v27-10-2]]

^<<v27-10-2,2>>^ In those days I, Daniel, had been mourning for three full weeks.

[[v27-10-3]]

^<<v27-10-3,3>>^ I ate no rich food, and no meat or wine entered my mouth, and I did not put any oil on myself for three full weeks.

[[v27-10-4]]

^<<v27-10-4,4>>^ On the 24th day of the first month, while I was on the bank of the great river, the Tiʹgris,^&#42;1^

[NOTE]
====
. Lit., “Hiddekel.”
====

[[v27-10-5]]

^<<v27-10-5,5>>^ I looked up and saw a man clothed in linen, and around his waist was a belt of gold from Uʹphaz.

[[v27-10-6]]

^<<v27-10-6,6>>^ His body was like chrysʹo·lite, his face had the appearance of lightning, his eyes were like fiery torches, his arms and his feet looked like burnished copper, and the sound of his words was like the sound of a multitude.

[[v27-10-7]]

^<<v27-10-7,7>>^ Only I, Daniel, saw the vision; the men with me did not see the vision. However, a great trembling seized them, and they ran away and hid.

[[v27-10-8]]

^<<v27-10-8,8>>^ Then I was left by myself, and when I saw this great vision, there was no power left in me and my dignified appearance left me and I lost all strength.

[[v27-10-9]]

^<<v27-10-9,9>>^ Then I heard the sound of him speaking; but when I heard him speaking, I fell fast asleep with my face to the ground.

[[v27-10-10]]

^<<v27-10-10,10>>^ But then a hand touched me, and it stirred me to get up on my hands and knees.

[[v27-10-11]]

^<<v27-10-11,11>>^ Then he said to me:
“O Daniel, you very precious^&#42;1^ man, give attention to the words that I am about to speak to you. Now stand up in your place, for I have been sent to you.”
When he said this to me, I stood up, trembling.

[NOTE]
====
. Or “very desirable; highly esteemed.”
====

[[v27-10-12]]

^<<v27-10-12,12>>^ He then said to me: “Do not be afraid, O Daniel. Your words have been heard from the first day that you gave your heart to understanding and to humbling yourself before your God, and I have come because of your words.

[[v27-10-13]]

^<<v27-10-13,13>>^ But the prince of the royal realm of Persia stood in opposition to me for 21 days. But then Miʹcha·el,^&#42;1^ one of the foremost princes,^&#42;2^ came to help me; and I remained there beside the kings of Persia.

[NOTE]
====
. Meaning “Who Is Like God?”
. Or “a prince of the first rank.”
====

[[v27-10-14]]

^<<v27-10-14,14>>^ I have come to make you understand what will befall your people in the final part of the days, because it is a vision yet for the days to come.”

[[v27-10-15]]

^<<v27-10-15,15>>^ Now when he spoke these words to me, I turned my face to the ground and became speechless.

[[v27-10-16]]

^<<v27-10-16,16>>^ Then one who looked like a man touched my lips, and I opened my mouth and said to the one who stood in front of me: “My lord, I am shuddering because of the vision, and I have no strength.

[[v27-10-17]]

^<<v27-10-17,17>>^ So how can my lord’s servant speak with my lord? For now I have no strength, and there is no breath left in me.”

[[v27-10-18]]

^<<v27-10-18,18>>^ The one who looked like a man touched me again and strengthened me.

[[v27-10-19]]

^<<v27-10-19,19>>^ Then he said: “Do not be afraid, O very precious^&#42;1^ man. May you have peace. Be strong, yes, be strong.” As he spoke with me I was strengthened and I said: “Let my lord speak, for you have strengthened me.”

[NOTE]
====
. Or “very desirable; highly esteemed.”
====

[[v27-10-20]]

^<<v27-10-20,20>>^ Then he said: “Do you know why I have come to you? Now I will go back to fight with the prince of Persia. When I leave, the prince of Greece will come.

[[v27-10-21]]

^<<v27-10-21,21>>^ However, I will tell you the things recorded in the writings of truth. There is no one strongly supporting me in these things but Miʹcha·el, your prince.

'''

xref:027-daniel/027-daniel-009.adoc#v27-9-0[&#60; Capítulo Anterior] | <<v27-10-0,Topo>> | xref:027-daniel/027-daniel-011.adoc#v27-11-0[Próximo Capítulo &#62;]