include::./index.adoc[]

[[v27-2-0]]
=== Daniel, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v27-2-1]]

^<<v27-2-1,1>>^ In the second year of his kingship, Neb·u·chad·nezʹzar had a number of dreams, and he^&#42;1^ was so agitated that he could not sleep.

[NOTE]
====
. Lit., “his spirit.”
====

[[v27-2-2]]

^<<v27-2-2,2>>^ So the king gave the order to summon the magic-practicing priests, the conjurers, the sorcerers, and the Chal·deʹans^&#42;1^ to tell the king his dreams. So they came in and stood before the king.

[NOTE]
====
. That is, a group skilled in divination and astrology.
====

[[v27-2-3]]

^<<v27-2-3,3>>^ Then the king said to them: “I have had a dream, and I am^&#42;1^ agitated because I want to know what I dreamed.”

[NOTE]
====
. Lit., “my spirit is.”
====

[[v27-2-4]]

^<<v27-2-4,4>>^ The Chal·deʹans replied to the king in the Ar·a·maʹic language:^&#42;1^ “O king, may you live on forever. Relate the dream to your servants, and we will tell the interpretation.”

[NOTE]
====
. Da 2:4b through 7:28 was originally written in Aramaic.
====

[[v27-2-5]]

^<<v27-2-5,5>>^ The king answered the Chal·deʹans: “This is my final word: If you do not make the dream known to me, along with its interpretation, you will be dismembered, and your houses will be turned into public latrines.^&#42;1^

[NOTE]
====
. Or possibly, “garbage dumps; dunghills.”
====

[[v27-2-6]]

^<<v27-2-6,6>>^ But if you do tell the dream and its interpretation, you will receive from me gifts and a reward and great honor. So tell me the dream and its interpretation.”

[[v27-2-7]]

^<<v27-2-7,7>>^ They answered a second time: “Let the king relate the dream to his servants, and we will tell its interpretation.”

[[v27-2-8]]

^<<v27-2-8,8>>^ The king replied: “I am well-aware that you are trying to gain time, for you realize what my final word is.

[[v27-2-9]]

^<<v27-2-9,9>>^ If you do not make the dream known to me, there is only one penalty for all of you. But you have agreed to tell me something false and deceitful until the situation changes. So tell me the dream, and I will know that you can explain its interpretation.”

[[v27-2-10]]

^<<v27-2-10,10>>^ The Chal·deʹans answered the king: “There is not a man on earth^&#42;1^ who is able to do what the king demands, for no great king or governor has asked such a thing of any magic-practicing priest or conjurer or Chal·deʹan.

[NOTE]
====
. Or “dry land.”
====

[[v27-2-11]]

^<<v27-2-11,11>>^ What the king is asking is difficult, and no one exists who could tell the king this except the gods, who do not dwell among mortals.”^&#42;1^

[NOTE]
====
. Lit., “with flesh.”
====

[[v27-2-12]]

^<<v27-2-12,12>>^ At this the king flew into a violent rage and gave the order to destroy all the wise men of Babylon.

[[v27-2-13]]

^<<v27-2-13,13>>^ When the order was issued and the wise men were about to be killed, they also looked for Daniel and his companions to put them to death.

[[v27-2-14]]

^<<v27-2-14,14>>^ At that time Daniel discreetly and cautiously spoke to Arʹi·och the chief of the king’s bodyguard, who had gone out to kill the wise men of Babylon.

[[v27-2-15]]

^<<v27-2-15,15>>^ He asked Arʹi·och the officer of the king: “Why is there such a harsh order from the king?” Then Arʹi·och informed Daniel about the matter.

[[v27-2-16]]

^<<v27-2-16,16>>^ So Daniel went in and asked the king to grant him time to tell the interpretation to the king.

[[v27-2-17]]

^<<v27-2-17,17>>^ Daniel then went to his house and informed his companions Han·a·niʹah, Mishʹa·el, and Az·a·riʹah of the matter.

[[v27-2-18]]

^<<v27-2-18,18>>^ He asked them to pray for mercy from the God of heaven concerning this secret, so that Daniel and his companions would not be destroyed along with the rest of the wise men of Babylon.

[[v27-2-19]]

^<<v27-2-19,19>>^ Then the secret was revealed to Daniel in a vision at night. So Daniel praised the God of heaven.

[[v27-2-20]]

^<<v27-2-20,20>>^ Daniel declared:
“Let the name of God be praised for all eternity,^&#42;1^
For wisdom and mightiness are his alone.

[NOTE]
====
. Or “from eternity to eternity.”
====

[[v27-2-21]]

^<<v27-2-21,21>>^ He changes times and seasons,
Removes kings and sets up kings,
Gives wisdom to the wise and knowledge to those with discernment.

[[v27-2-22]]

^<<v27-2-22,22>>^ He reveals the deep things and the hidden things,
He knows what is in the darkness,
And with him the light dwells.

[[v27-2-23]]

^<<v27-2-23,23>>^ To you, O God of my forefathers, I offer thanks and praise,
Because you have given me wisdom and power.
And now you have made known to me what we requested of you;
You have made known to us the concern of the king.”

[[v27-2-24]]

^<<v27-2-24,24>>^ Daniel then went in to Arʹi·och, whom the king had appointed to destroy the wise men of Babylon, and he said to him: “Do not destroy any wise men of Babylon. Take me in before the king, and I will tell the interpretation to the king.”

[[v27-2-25]]

^<<v27-2-25,25>>^ Arʹi·och quickly took Daniel in before the king and said to him: “I have found a man of the exiles of Judah who can make known the interpretation to the king.”

[[v27-2-26]]

^<<v27-2-26,26>>^ The king said to Daniel, whose name was Bel·te·shazʹzar: “Can you really make known to me the dream that I saw, and its interpretation?”

[[v27-2-27]]

^<<v27-2-27,27>>^ Daniel replied to the king: “None of the wise men, conjurers, magic-practicing priests, or astrologers are able to tell the king the secret that he is asking.

[[v27-2-28]]

^<<v27-2-28,28>>^ But there is a God in the heavens who is a Revealer of secrets, and he has made known to King Neb·u·chad·nezʹzar what is to happen in the final part of the days. This is your dream, and these are the visions of your head as you lay on your bed:

[[v27-2-29]]

^<<v27-2-29,29>>^ “As for you, O king, on your bed your thoughts turned to what is to take place in the future, and the Revealer of secrets has made known to you what is to happen.

[[v27-2-30]]

^<<v27-2-30,30>>^ As for me, this secret was not revealed to me because I have greater wisdom than anyone living; rather, it was to make the interpretation known to the king so that you may know the thoughts in your heart.

[[v27-2-31]]

^<<v27-2-31,31>>^ “You, O king, were watching, and you saw an immense image.^&#42;1^ That image, which was huge and extremely bright, was standing in front of you, and its appearance was terrifying.

[NOTE]
====
. Or “statue.”
====

[[v27-2-32]]

^<<v27-2-32,32>>^ The head of that image was of fine gold, its chest and its arms were of silver, its abdomen and its thighs were of copper,

[[v27-2-33]]

^<<v27-2-33,33>>^ its legs were of iron, and its feet were partly of iron and partly of clay.^&#42;1^

[NOTE]
====
. Or “baked (molded) clay.”
====

[[v27-2-34]]

^<<v27-2-34,34>>^ You looked on until a stone was cut out, not by hands, and it struck the image on its feet of iron and of clay and crushed them.

[[v27-2-35]]

^<<v27-2-35,35>>^ At that time the iron, the clay, the copper, the silver, and the gold were, all together, crushed and became like the chaff from the summer threshing floor, and the wind carried them away so that not a trace of them could be found. But the stone that struck the image became a large mountain, and it filled the whole earth.

[[v27-2-36]]

^<<v27-2-36,36>>^ “This is the dream, and we will now tell the king its interpretation.

[[v27-2-37]]

^<<v27-2-37,37>>^ You, O king—the king of kings to whom the God of heaven has given the kingdom, the might, the strength, and the glory,

[[v27-2-38]]

^<<v27-2-38,38>>^ and into whose hand he has given men wherever they may dwell, as well as the beasts of the field and the birds of the heavens, and whom he has made ruler over all of them—you yourself are the head of gold.

[[v27-2-39]]

^<<v27-2-39,39>>^ “But after you another kingdom will rise, inferior to you; then another kingdom, a third one, of copper, that will rule over the whole earth.

[[v27-2-40]]

^<<v27-2-40,40>>^ “As for the fourth kingdom, it will be strong like iron. For just as iron crushes and pulverizes everything else, yes, like iron that shatters, it will crush and shatter all of these.

[[v27-2-41]]

^<<v27-2-41,41>>^ “And just as you saw the feet and the toes to be partly of clay of a potter and partly of iron, the kingdom will be divided, but some of the hardness of iron will be in it, just as you saw the iron mixed with soft clay.

[[v27-2-42]]

^<<v27-2-42,42>>^ And as the toes of the feet were partly of iron and partly of clay, so the kingdom will be partly strong and partly fragile.

[[v27-2-43]]

^<<v27-2-43,43>>^ Just as you saw iron mixed with soft clay, they will be mixed with the people;^&#42;1^ but they will not stick together, one to the other, just as iron does not mix with clay.

[NOTE]
====
. Or “the offspring of mankind,” that is, the common people.
====

[[v27-2-44]]

^<<v27-2-44,44>>^ “In the days of those kings the God of heaven will set up a kingdom that will never be destroyed. And this kingdom will not be passed on to any other people. It will crush and put an end to all these kingdoms, and it alone will stand forever,

[[v27-2-45]]

^<<v27-2-45,45>>^ just as you saw that out of the mountain a stone was cut not by hands, and that it crushed the iron, the copper, the clay, the silver, and the gold. The Grand God has made known to the king what will happen in the future. The dream is true, and its interpretation is trustworthy.”

[[v27-2-46]]

^<<v27-2-46,46>>^ Then King Neb·u·chad·nezʹzar fell down with his face to the ground before Daniel and paid homage to him. And he gave the order to offer a present and incense to him.

[[v27-2-47]]

^<<v27-2-47,47>>^ The king said to Daniel: “Truly your God is a God of gods and a Lord of kings and a Revealer of secrets, because you were able to reveal this secret.”

[[v27-2-48]]

^<<v27-2-48,48>>^ The king then elevated Daniel and gave him many fine gifts, and he made him the ruler over all the province^&#42;1^ of Babylon and the chief prefect over all the wise men of Babylon.

[NOTE]
====
. Or “jurisdictional district.”
====

[[v27-2-49]]

^<<v27-2-49,49>>^ And at Daniel’s request, the king appointed Shaʹdrach, Meʹshach, and A·bedʹne·go over the administration of the province^&#42;1^ of Babylon, but Daniel served in the king’s court.

[NOTE]
====
. Or “jurisdictional district.”
====

'''

xref:027-daniel/027-daniel-001.adoc#v27-1-0[&#60; Capítulo Anterior] | <<v27-2-0,Topo>> | xref:027-daniel/027-daniel-003.adoc#v27-3-0[Próximo Capítulo &#62;]