include::./index.adoc[]

[[v27-3-0]]
=== Daniel, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v27-3-1]]

^<<v27-3-1,1>>^ Neb·u·chad·nezʹzar the king made an image^&#42;1^ of gold that was 60 cubits^&#42;2^ high and 6 cubits^&#42;3^ wide. He set it up on the plain of Duʹra in the province^&#42;4^ of Babylon.

[NOTE]
====
. Or “statue.”
. About 27 m (88 ft). See App. B14.
. About 2.7 m (8.8 ft). See App. B14.
. Or “jurisdictional district.”
====

[[v27-3-2]]

^<<v27-3-2,2>>^ Then King Neb·u·chad·nezʹzar sent word to assemble the satraps, prefects, governors, advisers, treasurers, judges, magistrates, and all the administrators of the provinces^&#42;1^ to come to the inauguration of the image that King Neb·u·chad·nezʹzar had set up.

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v27-3-3]]

^<<v27-3-3,3>>^ So the satraps, prefects, governors, advisers, treasurers, judges, magistrates, and all the administrators of the provinces^&#42;1^ assembled for the inauguration of the image that King Neb·u·chad·nezʹzar had set up. And they stood in front of the image that Neb·u·chad·nezʹzar had set up.

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v27-3-4]]

^<<v27-3-4,4>>^ The herald loudly proclaimed: “You are commanded, O peoples, nations, and language groups,

[[v27-3-5]]

^<<v27-3-5,5>>^ that when you hear the sound of the horn, pipe, zither, triangular harp, stringed instrument, bagpipe, and all the other musical instruments, you must fall down and worship the image of gold that King Neb·u·chad·nezʹzar has set up.

[[v27-3-6]]

^<<v27-3-6,6>>^ Whoever does not fall down and worship will immediately be thrown into the burning fiery furnace.”

[[v27-3-7]]

^<<v27-3-7,7>>^ So when all the peoples heard the sound of the horn, pipe, zither, triangular harp, stringed instrument, and all the other musical instruments, all the peoples, nations, and language groups fell down and worshipped the image of gold that King Neb·u·chad·nezʹzar had set up.

[[v27-3-8]]

^<<v27-3-8,8>>^ Now at that time some of the Chal·deʹans came forward and accused^&#42;1^ the Jews.

[NOTE]
====
. Or “slandered.”
====

[[v27-3-9]]

^<<v27-3-9,9>>^ They said to King Neb·u·chad·nezʹzar: “O king, may you live on forever.

[[v27-3-10]]

^<<v27-3-10,10>>^ You, O king, gave the command that every man who hears the sound of the horn, pipe, zither, triangular harp, stringed instrument, bagpipe, and all the other musical instruments should fall down and worship the image of gold;

[[v27-3-11]]

^<<v27-3-11,11>>^ and that whoever would not fall down and worship should be thrown into the burning fiery furnace.

[[v27-3-12]]

^<<v27-3-12,12>>^ But there are certain Jews whom you appointed to administer the province^&#42;1^ of Babylon: Shaʹdrach, Meʹshach, and A·bedʹne·go. These men have paid no regard to you, O king. They are not serving your gods, and they refuse to worship the image of gold that you have set up.”

[NOTE]
====
. Or “jurisdictional district.”
====

[[v27-3-13]]

^<<v27-3-13,13>>^ Then Neb·u·chad·nezʹzar, in a furious rage, ordered Shaʹdrach, Meʹshach, and A·bedʹne·go to be brought in. So these men were brought in before the king.

[[v27-3-14]]

^<<v27-3-14,14>>^ Neb·u·chad·nezʹzar said to them: “Is it really true, Shaʹdrach, Meʹshach, and A·bedʹne·go, that you are not serving my gods and that you refuse to worship the image of gold that I have set up?

[[v27-3-15]]

^<<v27-3-15,15>>^ Now when you hear the sound of the horn, the pipe, the zither, the triangular harp, the stringed instrument, the bagpipe, and all the other musical instruments, if you are ready to fall down and worship the image that I have made, fine. But if you refuse to worship, you will immediately be thrown into the burning fiery furnace. And who is the god who can rescue you out of my hands?”

[[v27-3-16]]

^<<v27-3-16,16>>^ Shaʹdrach, Meʹshach, and A·bedʹne·go answered the king: “O Neb·u·chad·nezʹzar, we have no need to answer you in this matter.

[[v27-3-17]]

^<<v27-3-17,17>>^ If it must be, our God whom we serve is able to rescue us from the burning fiery furnace, O king, and to rescue us from your hand.

[[v27-3-18]]

^<<v27-3-18,18>>^ But even if he does not, let it be known to you, O king, that we will not serve your gods or worship the image of gold that you have set up.”

[[v27-3-19]]

^<<v27-3-19,19>>^ Then Neb·u·chad·nezʹzar became so furious with Shaʹdrach, Meʹshach, and A·bedʹne·go that the expression of his face changed^&#42;1^ toward them, and he gave orders to heat the furnace seven times hotter than usual.

[NOTE]
====
. Or “that his attitude changed completely.”
====

[[v27-3-20]]

^<<v27-3-20,20>>^ He ordered some of the mighty men from his army to bind Shaʹdrach, Meʹshach, and A·bedʹne·go and to throw them into the burning fiery furnace.

[[v27-3-21]]

^<<v27-3-21,21>>^ So these men were tied up while still wearing their cloaks, garments, caps, and all their other clothing, and they were thrown into the burning fiery furnace.

[[v27-3-22]]

^<<v27-3-22,22>>^ Because the king’s command was so harsh and the furnace was exceptionally hot, the men who took up Shaʹdrach, Meʹshach, and A·bedʹne·go were the ones killed by the flames of the fire.

[[v27-3-23]]

^<<v27-3-23,23>>^ But these three men, Shaʹdrach, Meʹshach, and A·bedʹne·go, fell bound into the burning fiery furnace.

[[v27-3-24]]

^<<v27-3-24,24>>^ King Neb·u·chad·nezʹzar then became frightened and quickly rose up and said to his high officials: “Did we not tie up three men and throw them into the fire?” They answered the king: “Yes, O king.”

[[v27-3-25]]

^<<v27-3-25,25>>^ He said: “Look! I see four men walking about free in the midst of the fire, and they are unharmed, and the fourth one looks like a son of the gods.”

[[v27-3-26]]

^<<v27-3-26,26>>^ Neb·u·chad·nezʹzar approached the door of the burning fiery furnace and said: “Shaʹdrach, Meʹshach, and A·bedʹne·go, you servants of the Most High God, step out and come here!” Shaʹdrach, Meʹshach, and A·bedʹne·go stepped out from the midst of the fire.

[[v27-3-27]]

^<<v27-3-27,27>>^ And the satraps, prefects, governors, and the high officials of the king who were assembled there saw that the fire had had no effect on^&#42;1^ the bodies of these men; not a hair of their heads had been singed, their cloaks looked no different, and there was not even the smell of fire on them.

[NOTE]
====
. Or “power over.”
====

[[v27-3-28]]

^<<v27-3-28,28>>^ Neb·u·chad·nezʹzar then declared: “Praised be the God of Shaʹdrach, Meʹshach, and A·bedʹne·go, who sent his angel and rescued his servants. They trusted in him and went against the command of the king and were willing to die^&#42;1^ rather than serve or worship any god except their own God.

[NOTE]
====
. Or “and gave up their bodies.”
====

[[v27-3-29]]

^<<v27-3-29,29>>^ I am therefore issuing an order that any people, nation, or language group that says anything against the God of Shaʹdrach, Meʹshach, and A·bedʹne·go should be dismembered, and their houses should be turned into public latrines;^&#42;1^ for there is no other god who is able to rescue like this one.”

[NOTE]
====
. Or possibly, “garbage dumps; dunghills.”
====

[[v27-3-30]]

^<<v27-3-30,30>>^ The king then promoted^&#42;1^ Shaʹdrach, Meʹshach, and A·bedʹne·go in the province^&#42;2^ of Babylon.

[NOTE]
====
. Lit., “caused to prosper.”
. Or “jurisdictional district.”
====

'''

xref:027-daniel/027-daniel-002.adoc#v27-2-0[&#60; Capítulo Anterior] | <<v27-3-0,Topo>> | xref:027-daniel/027-daniel-004.adoc#v27-4-0[Próximo Capítulo &#62;]