include::./index.adoc[]

[[v27-12-0]]
=== Daniel, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v27-12-1]]

^<<v27-12-1,1>>^ “During that time Miʹcha·el^&#42;1^ will stand up,^&#42;2^ the great prince who is standing in behalf of your people.^&#42;3^ And there will occur a time of distress such as has not occurred since there came to be a nation until that time. And during that time your people will escape, everyone who is found written down in the book.

[NOTE]
====
. Meaning “Who Is Like God?”
. Or “arise.”
. Lit., “the sons of your people.”
====

[[v27-12-2]]

^<<v27-12-2,2>>^ And many of those asleep in the dust of the earth will wake up, some to everlasting life and others to reproach and to everlasting contempt.

[[v27-12-3]]

^<<v27-12-3,3>>^ “And those having insight will shine as brightly as the expanse of heaven, and those bringing the many to righteousness like the stars, forever and ever.

[[v27-12-4]]

^<<v27-12-4,4>>^ “As for you, Daniel, keep the words secret, and seal up the book until the time of the end. Many will rove about,^&#42;1^ and the true knowledge will become abundant.”

[NOTE]
====
. Or “examine it [that is, the book] thoroughly.”
====

[[v27-12-5]]

^<<v27-12-5,5>>^ Then I, Daniel, looked and saw two others standing there, one on this bank of the stream and one on the other bank of the stream.

[[v27-12-6]]

^<<v27-12-6,6>>^ Then one said to the man clothed in linen, who was up above the waters of the stream: “How long will it be to the end of these marvelous things?”

[[v27-12-7]]

^<<v27-12-7,7>>^ Then I heard the man clothed in linen, who was up above the waters of the stream, as he raised his right hand and his left hand to the heavens and swore by the One who is alive forever: “It will be for an appointed time, appointed times, and half a time.^&#42;1^ As soon as the dashing to pieces of the power of the holy people comes to an end, all these things will come to their finish.”

[NOTE]
====
. That is, three and a half times.
====

[[v27-12-8]]

^<<v27-12-8,8>>^ Now as for me, I heard, but I could not understand; so I said: “O my lord, what will be the outcome of these things?”

[[v27-12-9]]

^<<v27-12-9,9>>^ Then he said: “Go, Daniel, because the words are to be kept secret and sealed up until the time of the end.

[[v27-12-10]]

^<<v27-12-10,10>>^ Many will cleanse themselves and whiten themselves and will be refined. And the wicked ones will act wickedly, and none of the wicked will understand; but those having insight will understand.

[[v27-12-11]]

^<<v27-12-11,11>>^ “And from the time that the constant feature^&#42;1^ has been removed and the disgusting thing that causes desolation has been put in place, there will be 1,290 days.

[NOTE]
====
. Or “the continual sacrifice.”
====

[[v27-12-12]]

^<<v27-12-12,12>>^ “Happy is the one who keeps in expectation^&#42;1^ and who arrives at the 1,335 days!

[NOTE]
====
. Or “who is waiting eagerly.”
====

[[v27-12-13]]

^<<v27-12-13,13>>^ “But as for you, go on to the end. You will rest, but you will stand up for your lot^&#42;1^ at the end of the days.”

[NOTE]
====
. Or “in your allotted place.”
====

'''

xref:027-daniel/027-daniel-011.adoc#v27-11-0[&#60; Capítulo Anterior] | <<v27-12-0,Topo>> | xref:028-hosea/028-hosea-001.adoc#v28-1-0[Próximo Capítulo &#62;]