include::./index.adoc[]

[[v27-7-0]]
=== Daniel, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v27-7-1]]

^<<v27-7-1,1>>^ In the first year of King Bel·shazʹzar of Babylon, Daniel saw a dream and visions of his head as he lay on his bed. Then he wrote down the dream; he recorded a complete account of the matters.

[[v27-7-2]]

^<<v27-7-2,2>>^ Daniel declared:
“I was watching in my visions during the night, and look! the four winds of the heavens were stirring up the vast sea.

[[v27-7-3]]

^<<v27-7-3,3>>^ And four huge beasts came out of the sea, each different from the others.

[[v27-7-4]]

^<<v27-7-4,4>>^ “The first one was like a lion, and it had the wings of an eagle. I watched until its wings were plucked out, and it was lifted up from the earth and was made to stand up on two feet like a man, and it was given the heart of a man.

[[v27-7-5]]

^<<v27-7-5,5>>^ “And look! another beast, a second one, like a bear. It was raised up on one side, and three ribs were in its mouth between its teeth; and it was told, ‘Get up, eat much flesh.’

[[v27-7-6]]

^<<v27-7-6,6>>^ “After this I kept watching, and look! another beast, like a leopard, but on its back it had four wings like those of a bird. And the beast had four heads, and it was given authority to rule.

[[v27-7-7]]

^<<v27-7-7,7>>^ “After this I kept watching in the visions of the night, and I saw a fourth beast, fearsome and terrifying and unusually strong, and it had large iron teeth. It was devouring and crushing, and what was left it trampled down with its feet. It was different from all the other beasts that were prior to it, and it had ten horns.

[[v27-7-8]]

^<<v27-7-8,8>>^ While I considered the horns, look! another horn, a small one, came up among them, and three of the first horns were plucked up from before it. And look! there were eyes like human eyes in this horn, and there was a mouth speaking arrogantly.^&#42;1^

[NOTE]
====
. Or “boastfully.”
====

[[v27-7-9]]

^<<v27-7-9,9>>^ “I kept watching until thrones were set in place and the Ancient of Days sat down. His clothing was white like snow, and the hair of his head was like clean wool. His throne was flames of fire; its wheels were a burning fire.

[[v27-7-10]]

^<<v27-7-10,10>>^ A stream of fire was flowing and going out from before him. A thousand thousands kept ministering to him, and ten thousand times ten thousand stood before him. The Court took its seat, and books were opened.

[[v27-7-11]]

^<<v27-7-11,11>>^ “I kept watching at that time because of the sound of the arrogant^&#42;1^ words that the horn was speaking; I watched until the beast was killed and its body was destroyed and it was given over to be burned in the fire.

[NOTE]
====
. Or “boastful.”
====

[[v27-7-12]]

^<<v27-7-12,12>>^ But as for the rest of the beasts, their rulerships were taken away, and their lives were prolonged for a time and a season.

[[v27-7-13]]

^<<v27-7-13,13>>^ “I kept watching in the visions of the night, and look! with the clouds of the heavens, someone like a son of man was coming; and he gained access to the Ancient of Days, and they brought him up close before that One.

[[v27-7-14]]

^<<v27-7-14,14>>^ And to him there were given rulership, honor, and a kingdom, that the peoples, nations, and language groups should all serve him. His rulership is an everlasting rulership that will not pass away, and his kingdom will not be destroyed.

[[v27-7-15]]

^<<v27-7-15,15>>^ “As for me, Daniel, my spirit was distressed within me because the visions of my head frightened me.

[[v27-7-16]]

^<<v27-7-16,16>>^ I went near to one of those who were standing there to ask him about the true meaning of this. So he replied and made known to me the interpretation of these things.

[[v27-7-17]]

^<<v27-7-17,17>>^ “‘These huge beasts, four in number, are four kings who will stand up from the earth.

[[v27-7-18]]

^<<v27-7-18,18>>^ But the holy ones of the Supreme One will receive the kingdom, and they will possess the kingdom forever, yes, forever and ever.’

[[v27-7-19]]

^<<v27-7-19,19>>^ “Then I wanted to know more about the fourth beast, which was different from all the others; it was extraordinarily fearsome, with iron teeth and copper claws, and it was devouring and crushing, and trampling down what was left with its feet;

[[v27-7-20]]

^<<v27-7-20,20>>^ and about the ten horns on its head, and the other horn that came up and before which three fell, the horn that had eyes and a mouth speaking arrogantly^&#42;1^ and whose appearance was bigger than that of the others.

[NOTE]
====
. Or “boastfully.”
====

[[v27-7-21]]

^<<v27-7-21,21>>^ “I kept watching as that horn made war on the holy ones, and it was prevailing against them,

[[v27-7-22]]

^<<v27-7-22,22>>^ until the Ancient of Days came and judgment was rendered in favor of the holy ones of the Supreme One, and the appointed time arrived for the holy ones to take possession of the kingdom.

[[v27-7-23]]

^<<v27-7-23,23>>^ “This is what he said: ‘As for the fourth beast, there is a fourth kingdom that will come to be on the earth. It will be different from all the other kingdoms, and it will devour all the earth and will trample it down and crush it.

[[v27-7-24]]

^<<v27-7-24,24>>^ As for the ten horns, ten kings will rise up out of that kingdom; and still another one will rise up after them, and he will be different from the first ones, and he will humiliate three kings.

[[v27-7-25]]

^<<v27-7-25,25>>^ He will speak words against the Most High, and he will continually harass the holy ones of the Supreme One. He will intend to change times and law, and they will be given into his hand for a time, times, and half a time.^&#42;1^

[NOTE]
====
. That is, three and a half times.
====

[[v27-7-26]]

^<<v27-7-26,26>>^ But the Court sat, and they took away his rulership, in order to annihilate him and to destroy him completely.

[[v27-7-27]]

^<<v27-7-27,27>>^ “‘And the kingdom and the rulership and the grandeur of the kingdoms under all the heavens were given to the people who are the holy ones of the Supreme One. Their kingdom is an everlasting kingdom, and all rulerships will serve and obey them.’

[[v27-7-28]]

^<<v27-7-28,28>>^ “This is the end of the matter. As for me, Daniel, my thoughts alarmed me greatly, so that I turned pale;^&#42;1^ but I kept the matter in my own heart.”

[NOTE]
====
. Or “my appearance changed.”
====

'''

xref:027-daniel/027-daniel-006.adoc#v27-6-0[&#60; Capítulo Anterior] | <<v27-7-0,Topo>> | xref:027-daniel/027-daniel-008.adoc#v27-8-0[Próximo Capítulo &#62;]