include::./index.adoc[]

[[v27-9-0]]
=== Daniel, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v27-9-1]]

^<<v27-9-1,1>>^ In the first year of Da·riʹus the son of A·has·u·eʹrus—a descendant of the Medes who had been made king over the kingdom of the Chal·deʹans—

[[v27-9-2]]

^<<v27-9-2,2>>^ in the first year of his reign I, Daniel, discerned by the books^&#42;1^ the number of years mentioned in the word of Jehovah to Jeremiah the prophet to fulfill the desolation of Jerusalem, namely, 70 years.

[NOTE]
====
. That is, the sacred books.
====

[[v27-9-3]]

^<<v27-9-3,3>>^ So I turned my face to Jehovah the true God, entreating him in prayer, along with fasting and sackcloth and ashes.

[[v27-9-4]]

^<<v27-9-4,4>>^ I prayed to Jehovah my God and made confession and said:
“O Jehovah the true God, the great and awe-inspiring One, who keeps his covenant and shows loyal love to those who love him and keep his commandments,

[[v27-9-5]]

^<<v27-9-5,5>>^ we have sinned and done wrong and acted wickedly and rebelled; and we have deviated from your commandments and your judgments.

[[v27-9-6]]

^<<v27-9-6,6>>^ We have not listened to your servants the prophets, who spoke in your name to our kings, our princes, our forefathers, and all the people of the land.

[[v27-9-7]]

^<<v27-9-7,7>>^ To you, O Jehovah, belongs righteousness, but to us belongs shame^&#42;1^ as is the case today, to the men of Judah, the inhabitants of Jerusalem, and all Israel, those nearby and far away, in all the lands to which you dispersed them because they acted unfaithfully toward you.

[NOTE]
====
. Lit., “shame of face.”
====

[[v27-9-8]]

^<<v27-9-8,8>>^ “O Jehovah, to us belongs shame,^&#42;1^ to our kings, our princes, and our forefathers, because we have sinned against you.

[NOTE]
====
. Lit., “shame of face.”
====

[[v27-9-9]]

^<<v27-9-9,9>>^ To Jehovah our God belong mercy and forgiveness, for we have rebelled against him.

[[v27-9-10]]

^<<v27-9-10,10>>^ We have not obeyed the voice of Jehovah our God by following his laws that he set before us through his servants the prophets.

[[v27-9-11]]

^<<v27-9-11,11>>^ All Israel has overstepped your Law and turned away by not obeying your voice, so that you poured out on us the curse and the sworn oath written about in the Law of Moses the servant of the true God, for we have sinned against Him.

[[v27-9-12]]

^<<v27-9-12,12>>^ He has carried out his words that he spoke against us and against our rulers who ruled over us,^&#42;1^ by bringing great calamity on us; nothing has ever been done under the whole heavens such as what was done in Jerusalem.

[NOTE]
====
. Lit., “our judges who judged us.”
====

[[v27-9-13]]

^<<v27-9-13,13>>^ Just as it is written in the Law of Moses, all this calamity has come upon us, yet we have not begged for the favor^&#42;1^ of Jehovah our God by turning away from our error and by showing insight into your truth.^&#42;2^

[NOTE]
====
. Or “softened the face.”
. Or “faithfulness.”
====

[[v27-9-14]]

^<<v27-9-14,14>>^ “So Jehovah kept watchful and brought calamity on us, for Jehovah our God is righteous in all the works that he has done; yet we have not obeyed his voice.

[[v27-9-15]]

^<<v27-9-15,15>>^ “Now, O Jehovah our God, the One who brought your people out of the land of Egypt by a mighty hand and made a name for yourself down to this day, we have sinned and acted wickedly.

[[v27-9-16]]

^<<v27-9-16,16>>^ O Jehovah, according to all your righteous acts, please, may your anger and wrath turn away from your city Jerusalem, your holy mountain; for because of our sins and the errors of our forefathers, Jerusalem and your people are an object of reproach to all those around us.

[[v27-9-17]]

^<<v27-9-17,17>>^ And now listen, O our God, to the prayer of your servant and to his entreaties, and cause your face to shine upon your sanctuary that is desolate, for your own sake, O Jehovah.

[[v27-9-18]]

^<<v27-9-18,18>>^ Incline your ear, O my God, and hear! Do open your eyes and see our desolate condition and the city that has been called by your name; for we are not entreating you because of our righteous acts but because of your great mercy.

[[v27-9-19]]

^<<v27-9-19,19>>^ O Jehovah, do hear. O Jehovah, do forgive. O Jehovah, do pay attention and act! Do not delay, for your own sake, O my God, for your own name has been called upon your city and upon your people.”

[[v27-9-20]]

^<<v27-9-20,20>>^ While I was still speaking and praying and confessing my sin and the sin of my people Israel and making my request for favor before Jehovah my God concerning the holy mountain of my God,

[[v27-9-21]]

^<<v27-9-21,21>>^ yes, while I was yet speaking in prayer, the man Gaʹbri·el, whom I had previously seen in the vision, came to me when I was extremely weary at about the time of the evening gift offering.

[[v27-9-22]]

^<<v27-9-22,22>>^ And he gave me understanding, saying:
“O Daniel, now I have come to give you insight and understanding.

[[v27-9-23]]

^<<v27-9-23,23>>^ When you began your entreaty the word went out, and I have come to report it to you, because you are someone very precious.^&#42;1^ So consider the matter and understand the vision.

[NOTE]
====
. Or “very desirable; highly esteemed.”
====

[[v27-9-24]]

^<<v27-9-24,24>>^ “There are 70 weeks^&#42;1^ that have been determined for your people and your holy city, in order to terminate the transgression, to finish off sin, to make atonement for error, to bring in everlasting righteousness, to seal up the vision and the prophecy,^&#42;2^ and to anoint the Holy of Holies.^&#42;3^

[NOTE]
====
. That is, weeks of years.
. Lit., “prophet.”
. Or “the Most Holy.”
====

[[v27-9-25]]

^<<v27-9-25,25>>^ You should know and understand that from the issuing of the word to restore and to rebuild Jerusalem until Mes·siʹah^&#42;1^ the Leader, there will be 7 weeks, also 62 weeks. She will be restored and rebuilt, with a public square and moat, but in times of distress.

[NOTE]
====
. Or “the Anointed One.”
====

[[v27-9-26]]

^<<v27-9-26,26>>^ “And after the 62 weeks, Mes·siʹah will be cut off,^&#42;1^ with nothing for himself.
“And the people of a leader who is coming will destroy the city and the holy place. And its end will be by the flood. And until the end there will be war; what is decided upon is desolations.

[NOTE]
====
. Or “put to death.”
====

[[v27-9-27]]

^<<v27-9-27,27>>^ “And he will keep the covenant in force for the many for one week; and at the half of the week, he will cause sacrifice and gift offering to cease.
“And on the wing of disgusting things there will be the one causing desolation; and until an extermination, what was decided on will be poured out also on the one lying desolate.”

'''

xref:027-daniel/027-daniel-008.adoc#v27-8-0[&#60; Capítulo Anterior] | <<v27-9-0,Topo>> | xref:027-daniel/027-daniel-010.adoc#v27-10-0[Próximo Capítulo &#62;]