include::./index.adoc[]

[[v27-1-0]]
=== Daniel, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v27-1-1]]

^<<v27-1-1,1>>^ In the third year of the kingship of King Je·hoiʹa·kim of Judah, King Neb·u·chad·nezʹzar of Babylon came to Jerusalem and besieged it.

[[v27-1-2]]

^<<v27-1-2,2>>^ In time Jehovah gave King Je·hoiʹa·kim of Judah into his hand, along with some of the utensils of the house^&#42;1^ of the true God, and he brought them to the land of Shiʹnar^&#42;2^ to the house^&#42;3^ of his god. He placed the utensils in the treasury of his god.

[NOTE]
====
. Or “temple.”
. That is, Babylonia.
. Or “temple.”
====

[[v27-1-3]]

^<<v27-1-3,3>>^ Then the king ordered Ashʹpe·naz his chief court official to bring some of the Israelites,^&#42;1^ including those of royal and noble descent.

[NOTE]
====
. Lit., “sons of Israel.”
====

[[v27-1-4]]

^<<v27-1-4,4>>^ They were to be youths^&#42;1^ without any defect, of good appearance, endowed with wisdom, knowledge, and discernment, and capable of serving in the king’s palace. He was to teach them the writing and the language of the Chal·deʹans.

[NOTE]
====
. Lit., “children.”
====

[[v27-1-5]]

^<<v27-1-5,5>>^ Furthermore, the king assigned to them a daily ration from the king’s delicacies and from the wine he drank. They were to be trained^&#42;1^ for three years, and at the end of that time they were to enter the king’s service.

[NOTE]
====
. Or possibly, “nourished.”
====

[[v27-1-6]]

^<<v27-1-6,6>>^ Now among them were some from the tribe^&#42;1^ of Judah: Daniel,^&#42;2^ Han·a·niʹah,^&#42;3^ Mishʹa·el,^&#42;4^ and Az·a·riʹah.^&#42;5^

[NOTE]
====
. Lit., “sons.”
. Meaning “My Judge Is God.”
. Meaning “Jehovah Has Shown Favor.”
. Possibly meaning “Who Is Like God?”
. Meaning “Jehovah Has Helped.”
====

[[v27-1-7]]

^<<v27-1-7,7>>^ And the principal court official assigned names^&#42;1^ to them; he gave to Daniel the name Bel·te·shazʹzar, to Han·a·niʹah the name Shaʹdrach, to Mishʹa·el the name Meʹshach, and to Az·a·riʹah the name A·bedʹne·go.

[NOTE]
====
. That is, Babylonian names.
====

[[v27-1-8]]

^<<v27-1-8,8>>^ But Daniel resolved in his heart that he would not defile himself with the king’s delicacies or with the wine he drank. So he asked the principal court official for permission not to defile himself in this way.

[[v27-1-9]]

^<<v27-1-9,9>>^ And the true God caused the principal court official to show Daniel favor^&#42;1^ and mercy.

[NOTE]
====
. Or “kindness.”
====

[[v27-1-10]]

^<<v27-1-10,10>>^ But the principal court official said to Daniel: “I am afraid of my lord the king, who has assigned your food and drink. What if he should see you looking worse in appearance than the other youths^&#42;1^ of your age? You would make me^&#42;2^ guilty before the king.”

[NOTE]
====
. Lit., “children.”
. Lit., “my head.”
====

[[v27-1-11]]

^<<v27-1-11,11>>^ But Daniel said to the guardian whom the principal court official had appointed over Daniel, Han·a·niʹah, Mishʹa·el, and Az·a·riʹah:

[[v27-1-12]]

^<<v27-1-12,12>>^ “Please, test your servants for ten days, and let us be given some vegetables to eat and water to drink;

[[v27-1-13]]

^<<v27-1-13,13>>^ then compare our appearance with the appearance of the youths^&#42;1^ who are eating the king’s delicacies, and deal with your servants according to what you see.”

[NOTE]
====
. Lit., “children.”
====

[[v27-1-14]]

^<<v27-1-14,14>>^ So he agreed to their proposal and tested them for ten days.

[[v27-1-15]]

^<<v27-1-15,15>>^ At the end of ten days their appearance was better and healthier^&#42;1^ than all the youths^&#42;2^ who were eating the king’s delicacies.

[NOTE]
====
. Lit., “fat of flesh.”
. Lit., “children.”
====

[[v27-1-16]]

^<<v27-1-16,16>>^ So the guardian would take away their delicacies and their wine and give them vegetables.

[[v27-1-17]]

^<<v27-1-17,17>>^ And the true God gave these four youths^&#42;1^ knowledge and insight into every kind of writing and wisdom; and Daniel was given understanding in all sorts of visions and dreams.

[NOTE]
====
. Lit., “children.”
====

[[v27-1-18]]

^<<v27-1-18,18>>^ At the end of the time that the king had specified to bring them in, the principal court official brought them in before Neb·u·chad·nezʹzar.

[[v27-1-19]]

^<<v27-1-19,19>>^ When the king spoke with them, no one in the entire group was found to be like Daniel, Han·a·niʹah, Mishʹa·el, and Az·a·riʹah; and they continued to serve before the king.

[[v27-1-20]]

^<<v27-1-20,20>>^ In every matter requiring wisdom and understanding that the king would ask them about, he found them ten times better than all the magic-practicing priests and the conjurers in his entire realm.

[[v27-1-21]]

^<<v27-1-21,21>>^ And Daniel remained there until the first year of King Cyrus.

'''

xref:026-ezekiel/026-ezekiel-048.adoc#v26-48-0[&#60; Capítulo Anterior] | <<v27-1-0,Topo>> | xref:027-daniel/027-daniel-002.adoc#v27-2-0[Próximo Capítulo &#62;]