include::./index.adoc[]

[[v27-5-0]]
=== Daniel, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v27-5-1]]

^<<v27-5-1,1>>^ As regards King Bel·shazʹzar, he held a great feast for a thousand of his nobles, and he was drinking wine in front of them.

[[v27-5-2]]

^<<v27-5-2,2>>^ While under the influence of the wine, Bel·shazʹzar gave an order to bring in the vessels of gold and silver that his father Neb·u·chad·nezʹzar had taken from the temple in Jerusalem, so that the king and his nobles, his concubines and his secondary wives could drink from them.

[[v27-5-3]]

^<<v27-5-3,3>>^ Then they brought in the gold vessels that had been taken from the temple of the house of God in Jerusalem, and the king and his nobles, his concubines and his secondary wives drank from them.

[[v27-5-4]]

^<<v27-5-4,4>>^ They drank wine, and they praised the gods of gold and silver, of copper, iron, wood, and stone.

[[v27-5-5]]

^<<v27-5-5,5>>^ At that very moment the fingers of a man’s hand appeared and began writing on the plaster of the wall of the king’s palace opposite the lampstand, and the king could see the back of the hand as it was writing.

[[v27-5-6]]

^<<v27-5-6,6>>^ Then the king turned pale^&#42;1^ and his thoughts terrified him, and his hips shook and his knees began to knock together.

[NOTE]
====
. Or “the king’s appearance changed.”
====

[[v27-5-7]]

^<<v27-5-7,7>>^ The king called out loudly to summon the conjurers, the Chal·deʹans,^&#42;1^ and the astrologers. The king said to the wise men of Babylon: “Any man who reads this writing and tells me its interpretation will be clothed with purple, a gold necklace will be placed around his neck, and he will rule as the third one in the kingdom.”

[NOTE]
====
. That is, a group skilled in divination and astrology.
====

[[v27-5-8]]

^<<v27-5-8,8>>^ Then all the wise men of the king came in, but they were not able to read the writing or to make known the interpretation to the king.

[[v27-5-9]]

^<<v27-5-9,9>>^ So King Bel·shazʹzar was very frightened and his face turned pale; and his nobles were perplexed.

[[v27-5-10]]

^<<v27-5-10,10>>^ Because of the words of the king and his nobles, the queen entered the banqueting hall. The queen said: “O king, may you live on forever. Do not let your thoughts terrify you, nor let your face turn pale.

[[v27-5-11]]

^<<v27-5-11,11>>^ There is a man^&#42;1^ in your kingdom who has the spirit of holy gods. In the days of your father, enlightenment and insight and wisdom like the wisdom of gods were found in him. King Neb·u·chad·nezʹzar your father appointed him as chief of the magic-practicing priests, conjurers, Chal·deʹans,^&#42;2^ and astrologers; your father did this, O king.

[NOTE]
====
. Or “a capable man.”
. That is, a group skilled in divination and astrology.
====

[[v27-5-12]]

^<<v27-5-12,12>>^ For Daniel, whom the king named Bel·te·shazʹzar, had an extraordinary spirit and knowledge and insight to interpret dreams, to explain riddles, and to solve knotty problems.^&#42;1^ Now let Daniel be summoned, and he will tell you the interpretation.”

[NOTE]
====
. Lit., “to untie knots.”
====

[[v27-5-13]]

^<<v27-5-13,13>>^ So Daniel was brought in before the king. The king asked Daniel: “Are you Daniel of the exiles of Judah, whom my father the king brought out of Judah?

[[v27-5-14]]

^<<v27-5-14,14>>^ I have heard concerning you that the spirit of gods is in you and that enlightenment and insight and extraordinary wisdom have been found in you.

[[v27-5-15]]

^<<v27-5-15,15>>^ Now the wise men and the conjurers were brought in before me to read this writing and to make its interpretation known to me, but they are not able to tell the interpretation of the message.

[[v27-5-16]]

^<<v27-5-16,16>>^ But I have heard concerning you that you are able to provide interpretations and to solve knotty problems.^&#42;1^ Now if you are able to read the writing and to make its interpretation known to me, you will be clothed with purple, a gold necklace will be placed around your neck, and you will rule as the third one in the kingdom.”

[NOTE]
====
. Lit., “to untie knots.”
====

[[v27-5-17]]

^<<v27-5-17,17>>^ Daniel then replied to the king: “You may keep your gifts and give your presents to others. However, I will read the writing to the king and make known its interpretation to him.

[[v27-5-18]]

^<<v27-5-18,18>>^ As for you, O king, the Most High God granted to Neb·u·chad·nezʹzar your father the kingdom and greatness and honor and majesty.

[[v27-5-19]]

^<<v27-5-19,19>>^ Because of the greatness He gave him, all peoples, nations, and language groups trembled with fear before him. Whomever he wanted, he killed or let live, and whomever he wanted, he exalted or humiliated.

[[v27-5-20]]

^<<v27-5-20,20>>^ But when his heart became haughty and his spirit became hardened, so that he acted presumptuously, he was brought down from the throne of his kingdom, and his dignity was taken away from him.

[[v27-5-21]]

^<<v27-5-21,21>>^ He was driven away from mankind, and his heart was made like that of a beast, and his dwelling was with the wild donkeys. He was given vegetation to eat just like bulls, and his body became wet with the dew of the heavens, until he came to know that the Most High God is Ruler in the kingdom of mankind and that he sets up over it whomever he wants.

[[v27-5-22]]

^<<v27-5-22,22>>^ “But you, his son Bel·shazʹzar, have not humbled your heart, although you knew all of this.

[[v27-5-23]]

^<<v27-5-23,23>>^ Instead, you exalted yourself against the Lord of the heavens, and you had them bring you the vessels of his house. Then you and your nobles, your concubines and your secondary wives drank wine from them and praised gods of silver and gold, of copper, iron, wood, and stone, gods that see nothing and hear nothing and know nothing. But you have not glorified the God in whose hand is your breath and all your ways.

[[v27-5-24]]

^<<v27-5-24,24>>^ So the hand was sent from him, and this writing was inscribed.

[[v27-5-25]]

^<<v27-5-25,25>>^ And this is the writing that was inscribed: MEʹNE, MEʹNE, TEʹKEL, and PARʹSIN.

[[v27-5-26]]

^<<v27-5-26,26>>^ “This is the interpretation of the words: MEʹNE, God has numbered the days of your kingdom and brought it to an end.

[[v27-5-27]]

^<<v27-5-27,27>>^ “TEʹKEL, you have been weighed in the balances and found lacking.

[[v27-5-28]]

^<<v27-5-28,28>>^ “PEʹRES, your kingdom has been divided and given to the Medes and the Persians.”

[[v27-5-29]]

^<<v27-5-29,29>>^ Then Bel·shazʹzar gave the command, and they clothed Daniel with purple and placed a gold necklace around his neck; and they heralded concerning him that he was to become the third ruler in the kingdom.

[[v27-5-30]]

^<<v27-5-30,30>>^ That very night Bel·shazʹzar the Chal·deʹan king was killed.

[[v27-5-31]]

^<<v27-5-31,31>>^ And Da·riʹus the Mede received the kingdom; he was about 62 years old.

'''

xref:027-daniel/027-daniel-004.adoc#v27-4-0[&#60; Capítulo Anterior] | <<v27-5-0,Topo>> | xref:027-daniel/027-daniel-006.adoc#v27-6-0[Próximo Capítulo &#62;]