include::./index.adoc[]

[[v27-11-0]]
=== Daniel, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v27-11-1]]

^<<v27-11-1,1>>^ “As for me, in the first year of Da·riʹus the Mede, I stood up to strengthen and fortify him.^&#42;1^

[NOTE]
====
. Or “and as a fortress to him.”
====

[[v27-11-2]]

^<<v27-11-2,2>>^ What I will tell you now is the truth:
“Look! Three more kings will stand up^&#42;1^ for Persia, and the fourth one will amass greater riches than all others. And when he becomes strong by means of his riches, he will rouse up everything against the kingdom of Greece.

[NOTE]
====
. Or “arise.”
====

[[v27-11-3]]

^<<v27-11-3,3>>^ “And a mighty king will stand up and rule with extensive dominion and do as he pleases.

[[v27-11-4]]

^<<v27-11-4,4>>^ But when he has stood up, his kingdom will be broken and be divided toward the four winds of the heavens, but not to his descendants^&#42;1^ and not like the dominion with which he ruled; for his kingdom will be uprooted and go to others besides these.

[NOTE]
====
. Or “posterity.”
====

[[v27-11-5]]

^<<v27-11-5,5>>^ “And the king of the south will become strong, that is, one of his princes; but one will prevail against him and will rule with extensive dominion, greater than that one’s ruling power.

[[v27-11-6]]

^<<v27-11-6,6>>^ “After some years they will make an alliance, and the daughter of the king of the south will come to the king of the north in order to make an equitable arrangement.^&#42;1^ But she will not retain the power of her arm; and he will not stand, nor his arm; and she will be given up, she and those bringing her in, and the one who caused her birth, and the one making her strong in those times.

[NOTE]
====
. Or “an agreement.”
====

[[v27-11-7]]

^<<v27-11-7,7>>^ And one from the sprout of her roots will stand up in his position, and he will come to the army and come against the fortress of the king of the north and will take action against them and prevail.

[[v27-11-8]]

^<<v27-11-8,8>>^ Also with their gods, with their metal images,^&#42;1^ with their desirable^&#42;2^ articles of silver and of gold, and with captives, he will come to Egypt. For some years he will stand off from the king of the north,

[NOTE]
====
. Or “molten statues.”
. Or “precious.”
====

[[v27-11-9]]

^<<v27-11-9,9>>^ who will come against the kingdom of the king of the south, but will go back to his own land.

[[v27-11-10]]

^<<v27-11-10,10>>^ “As for his sons, they will prepare for war and assemble a vast, great army. He will certainly advance and sweep through like a flood. But he will go back, and he will wage war all the way to his fortress.

[[v27-11-11]]

^<<v27-11-11,11>>^ “And the king of the south will become bitter and will go out and fight with him, that is, with the king of the north; and he will muster a large crowd, but the crowd will be given into that one’s hand.

[[v27-11-12]]

^<<v27-11-12,12>>^ And the crowd will be carried away. His heart will become exalted, and he will cause tens of thousands to fall; but he will not make use of his strong position.

[[v27-11-13]]

^<<v27-11-13,13>>^ “And the king of the north will return and muster a crowd larger than the first; and at the end of the times, after some years, he will surely come with a large army and with many resources.

[[v27-11-14]]

^<<v27-11-14,14>>^ In those times many will stand up against the king of the south.
“And the violent ones^&#42;1^ among your people will be carried along to try making a vision come true; but they will stumble.

[NOTE]
====
. Or “the sons of the robbers.”
====

[[v27-11-15]]

^<<v27-11-15,15>>^ “And the king of the north will come and throw up a siege rampart and capture a fortified city. And the arms^&#42;1^ of the south will not stand, nor will his select men; and they will have no power to stand.

[NOTE]
====
. Or “armies.”
====

[[v27-11-16]]

^<<v27-11-16,16>>^ The one coming against him will do as he pleases, and no one will stand before him. He will stand in the land of the Decoration,^&#42;1^ and ability to exterminate will be in his hand.

[NOTE]
====
. Or “the Beauty.”
====

[[v27-11-17]]

^<<v27-11-17,17>>^ He will set his face^&#42;1^ to come with the full force of his kingdom, and there will be equitable terms^&#42;2^ with him; and he will act effectively. As regards the daughter of women, it will be granted to him to bring her to ruin. And she will not stand, and she will not continue to be his.

[NOTE]
====
. Or “be determined.”
. Or “he will make an agreement.”
====

[[v27-11-18]]

^<<v27-11-18,18>>^ He will turn his face back to the coastlands and will capture many. And a commander will make the reproach from him cease for himself, so that his reproach will not be. He will make it turn back on that one.

[[v27-11-19]]

^<<v27-11-19,19>>^ Then he will turn his face back to the fortresses of his own land, and he will stumble and fall, and he will not be found.

[[v27-11-20]]

^<<v27-11-20,20>>^ “And there will stand up in his position one who causes an exactor^&#42;1^ to pass through the splendid kingdom, but in a few days he will be broken, though not in anger nor in warfare.

[NOTE]
====
. “An exactor,” possibly of taxes. Or “a taskmaster.”
====

[[v27-11-21]]

^<<v27-11-21,21>>^ “And there will stand up in his position a despised^&#42;1^ one, and they will not give him the majesty of the kingdom; and he will come in during a time of security^&#42;2^ and take hold of the kingdom by means of smoothness.^&#42;3^

[NOTE]
====
. Or “despicable.”
. Or possibly, “without warning.”
. Or “intrigue.”
====

[[v27-11-22]]

^<<v27-11-22,22>>^ And the arms^&#42;1^ of the flood will be swept away on account of him, and they will be broken; as will be the Leader of the covenant.

[NOTE]
====
. Or “armies.”
====

[[v27-11-23]]

^<<v27-11-23,23>>^ And because of their alliance with him, he will carry on deception and rise up and become mighty by means of a little nation.

[[v27-11-24]]

^<<v27-11-24,24>>^ During a time of security^&#42;1^ he will come into the richest parts^&#42;2^ of the province^&#42;3^ and do what his fathers and their fathers have not done. Plunder and spoil and goods he will distribute among them; and against fortified places he will plot his schemes, but only for a time.

[NOTE]
====
. Or possibly, “without warning.”
. Lit., “the fatness.”
. Or “jurisdictional district.”
====

[[v27-11-25]]

^<<v27-11-25,25>>^ “And he will muster his power and his heart against the king of the south with a large army, and the king of the south will prepare himself for the war with an exceedingly large and mighty army. And he will not stand, because they will plot schemes against him.

[[v27-11-26]]

^<<v27-11-26,26>>^ And those eating his delicacies will bring his downfall.
“As for his army, it will be swept^&#42;1^ away, and many will fall down slain.

[NOTE]
====
. Or “flooded.”
====

[[v27-11-27]]

^<<v27-11-27,27>>^ “As regards these two kings, their heart will be inclined to do what is bad, and they will sit at one table speaking lies to each other. But nothing will succeed, because the end is yet for the time appointed.

[[v27-11-28]]

^<<v27-11-28,28>>^ “And he will go back to his land with a great amount of goods, and his heart will be against the holy covenant. He will act effectively and go back to his land.

[[v27-11-29]]

^<<v27-11-29,29>>^ “At the time appointed he will return and come against the south. But this time will not be as it was before,

[[v27-11-30]]

^<<v27-11-30,30>>^ for the ships of Kitʹtim will come against him, and he will be humbled.
“He will go back and hurl denunciations^&#42;1^ against the holy covenant and act effectively; and he will go back and will give attention to those leaving the holy covenant.

[NOTE]
====
. Or “direct his fury.”
====

[[v27-11-31]]

^<<v27-11-31,31>>^ And arms^&#42;1^ will stand up, proceeding from him; and they will profane the sanctuary, the fortress, and remove the constant feature.^&#42;2^
“And they will put in place the disgusting thing that causes desolation.

[NOTE]
====
. Or “armies.”
. Or “the continual sacrifice.”
====

[[v27-11-32]]

^<<v27-11-32,32>>^ “And those who act wickedly against the covenant, he will lead into apostasy by means of smooth words.^&#42;1^ But the people who know their God will prevail and act effectively.

[NOTE]
====
. Or “flattery; insincerity.”
====

[[v27-11-33]]

^<<v27-11-33,33>>^ And those having insight among the people will impart understanding to the many. And they will be made to stumble by sword and by flame, by captivity and by plundering, for some days.

[[v27-11-34]]

^<<v27-11-34,34>>^ But when they are made to stumble, they will be given a little help; and many will join with them by means of smooth speech.^&#42;1^

[NOTE]
====
. Or “flattery; insincerity.”
====

[[v27-11-35]]

^<<v27-11-35,35>>^ And some of those having insight will be made to stumble, in order to do a refining work because of them and to do a cleansing and a whitening until the time of the end; because it is yet for the time appointed.

[[v27-11-36]]

^<<v27-11-36,36>>^ “The king will do as he pleases, and he will exalt himself and magnify himself above every god; and against the God of gods he will speak astonishing things. And he will prove successful until the denunciation comes to a finish; because what is determined must take place.

[[v27-11-37]]

^<<v27-11-37,37>>^ He will show no regard for the God of his fathers; nor will he show regard for the desire of women or for any other god, but he will magnify himself over everyone.

[[v27-11-38]]

^<<v27-11-38,38>>^ But instead^&#42;1^ he will give glory to the god of fortresses; to a god that his fathers did not know he will give glory by means of gold and silver and precious stones and desirable^&#42;2^ things.

[NOTE]
====
. Or “in his place.”
. Or “precious.”
====

[[v27-11-39]]

^<<v27-11-39,39>>^ He will act effectively against the most fortified strongholds, along with^&#42;1^ a foreign god. He will give great glory to those who give him recognition,^&#42;2^ and he will make them rule among many; and the ground he will apportion out^&#42;3^ for a price.

[NOTE]
====
. Or “helped by.”
. Or possibly, “to whomever he recognizes.”
. Or “distribute.”
====

[[v27-11-40]]

^<<v27-11-40,40>>^ “In the time of the end the king of the south will engage with him in a pushing,^&#42;1^ and against him the king of the north will storm with chariots and horsemen and many ships; and he will enter into the lands and sweep through like a flood.

[NOTE]
====
. Or “will lock horns with him.”
====

[[v27-11-41]]

^<<v27-11-41,41>>^ He will also enter into the land of the Decoration,^&#42;1^ and many lands will be made to stumble. But these are the ones that will escape out of his hand: Eʹdom and Moʹab and the main part of the Amʹmon·ites.

[NOTE]
====
. Or “Beauty.”
====

[[v27-11-42]]

^<<v27-11-42,42>>^ And he will keep thrusting out his hand against the lands; and as regards the land of Egypt, she will not escape.

[[v27-11-43]]

^<<v27-11-43,43>>^ And he will rule over the hidden treasures of gold and silver and over all the desirable^&#42;1^ things of Egypt. And the Libʹy·ans and the E·thi·oʹpi·ans will be at his steps.^&#42;2^

[NOTE]
====
. Or “precious.”
. Or “will follow him.”
====

[[v27-11-44]]

^<<v27-11-44,44>>^ “But reports out of the east^&#42;1^ and out of the north will disturb him, and he will go out in a great rage to annihilate and to devote many to destruction.

[NOTE]
====
. Or “sunrise.”
====

[[v27-11-45]]

^<<v27-11-45,45>>^ And he will plant his royal^&#42;1^ tents between the grand sea and the holy mountain of Decoration;^&#42;2^ and he will come all the way to his end, and there will be no helper for him.

[NOTE]
====
. Or “palatial.”
. Or “Beauty.”
====

'''

xref:027-daniel/027-daniel-010.adoc#v27-10-0[&#60; Capítulo Anterior] | <<v27-11-0,Topo>> | xref:027-daniel/027-daniel-012.adoc#v27-12-0[Próximo Capítulo &#62;]