include::./index.adoc[]

[[v27-8-0]]
=== Daniel, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v27-8-1]]

^<<v27-8-1,1>>^ In the third year of the kingship of King Bel·shazʹzar, a vision appeared to me, Daniel, after the one that appeared to me previously.

[[v27-8-2]]

^<<v27-8-2,2>>^ I saw the vision, and as I watched I was in Shuʹshan^&#42;1^ the citadel,^&#42;2^ which is in the province^&#42;3^ of Eʹlam; I viewed the vision, and I was next to the watercourse of Uʹlai.

[NOTE]
====
. Or “Susa.”
. Or “palace; fortress.”
. Or “jurisdictional district.”
====

[[v27-8-3]]

^<<v27-8-3,3>>^ As I raised my eyes, look! there was a ram standing before the watercourse, and it had two horns. The two horns were tall, but one was higher than the other, and the higher one came up later.

[[v27-8-4]]

^<<v27-8-4,4>>^ I saw the ram making thrusts to the west and to the north and to the south, and no wild beasts could stand before it, and there was no one who could provide rescue from its power.^&#42;1^ It did as it pleased and exalted itself.

[NOTE]
====
. Lit., “hand.”
====

[[v27-8-5]]

^<<v27-8-5,5>>^ As I kept watching, look! there was a male goat coming from the west^&#42;1^ crossing the surface of the whole earth without touching the ground. And the goat had a conspicuous horn between its eyes.

[NOTE]
====
. Or “sunset.”
====

[[v27-8-6]]

^<<v27-8-6,6>>^ It was coming toward the ram with the two horns, which I had seen standing before the watercourse; it was running toward it in a powerful rage.

[[v27-8-7]]

^<<v27-8-7,7>>^ I saw it closing in on the ram, and it was filled with bitterness toward it. It struck down the ram and broke its two horns, and the ram was powerless to stand up to it. It threw the ram to the ground and trampled it down, and there was no one to rescue it from its power.^&#42;1^

[NOTE]
====
. Lit., “hand.”
====

[[v27-8-8]]

^<<v27-8-8,8>>^ Then the male goat exalted itself exceedingly, but as soon as it became mighty, the great horn was broken; then four conspicuous horns came up instead of the one, toward the four winds of the heavens.

[[v27-8-9]]

^<<v27-8-9,9>>^ Out of one of them came another horn, a small one, and it grew very great toward the south and toward the east^&#42;1^ and toward the Decoration.^&#42;2^

[NOTE]
====
. Or “sunrise.”
. Or “the Beauty.”
====

[[v27-8-10]]

^<<v27-8-10,10>>^ It grew so great that it reached all the way to the army of the heavens, and it caused some of the army and some of the stars to fall to the earth, and it trampled them down.

[[v27-8-11]]

^<<v27-8-11,11>>^ It exalted itself even against the Prince of the army, and from him the constant feature^&#42;1^ was taken away, and the established place of his sanctuary was thrown down.

[NOTE]
====
. Or “the continual sacrifice.”
====

[[v27-8-12]]

^<<v27-8-12,12>>^ And an army was given over, together with the constant feature,^&#42;1^ because of transgression; and it kept throwing truth to the earth, and it acted and had success.

[NOTE]
====
. Or “the continual sacrifice.”
====

[[v27-8-13]]

^<<v27-8-13,13>>^ And I heard a holy one speaking, and another holy one said to the one speaking: “How long will the vision of the constant feature^&#42;1^ and of the transgression causing desolation continue, to make both the holy place and the army things to trample on?”

[NOTE]
====
. Or “the continual sacrifice.”
====

[[v27-8-14]]

^<<v27-8-14,14>>^ So he said to me: “Until 2,300 evenings and mornings; and the holy place will certainly be restored to its right condition.”

[[v27-8-15]]

^<<v27-8-15,15>>^ While I, Daniel, was watching the vision and seeking to understand it, suddenly I saw standing in front of me someone who appeared to be a man.

[[v27-8-16]]

^<<v27-8-16,16>>^ Then I heard the voice of a man in the midst of the Uʹlai, and he called out: “Gaʹbri·el, make that one understand what he saw.”

[[v27-8-17]]

^<<v27-8-17,17>>^ So he came near to where I was standing, but when he came I was so terrified that I fell facedown. He said to me: “Understand, O son of man, that the vision is for the time of the end.”

[[v27-8-18]]

^<<v27-8-18,18>>^ But while he was speaking with me, I fell fast asleep with my face to the ground. So he touched me and made me stand up where I had been standing.

[[v27-8-19]]

^<<v27-8-19,19>>^ Then he said: “Here I am causing you to know what will happen in the final part of the denunciation, because it is for the appointed time of the end.

[[v27-8-20]]

^<<v27-8-20,20>>^ “The two-horned ram that you saw stands for the kings of Meʹdi·a and Persia.

[[v27-8-21]]

^<<v27-8-21,21>>^ The hairy male goat stands for the king of Greece; and the great horn that was between its eyes stands for the first king.

[[v27-8-22]]

^<<v27-8-22,22>>^ As for the horn that was broken, so that four stood up instead of it, there are four kingdoms from his nation that will stand up, but not with his power.

[[v27-8-23]]

^<<v27-8-23,23>>^ “And in the final part of their kingdom, as the transgressors act to a completion,^&#42;1^ a fierce-looking king who understands ambiguous sayings^&#42;2^ will stand up.

[NOTE]
====
. Or “have reached their limit.”
. Or “who is skilled in intrigue.”
====

[[v27-8-24]]

^<<v27-8-24,24>>^ His power will become great, but not through his own power. He will bring ruin in an extraordinary way,^&#42;1^ and he will be successful and act effectively. He will bring mighty ones to ruin, also the people made up of the holy ones.

[NOTE]
====
. Or “bring terrible destruction.”
====

[[v27-8-25]]

^<<v27-8-25,25>>^ And by his cunning he will use deception to succeed; and in his heart he will exalt himself; and during a time of security^&#42;1^ he will bring many to ruin. He will even stand up against the Prince of princes, but he will be broken without human hand.

[NOTE]
====
. Or possibly, “and without warning.”
====

[[v27-8-26]]

^<<v27-8-26,26>>^ “What was said in the vision about the evenings and the mornings is true, but you must keep the vision secret, for it refers to a time many days from now.”^&#42;1^

[NOTE]
====
. Or “to the distant future.”
====

[[v27-8-27]]

^<<v27-8-27,27>>^ As for me, Daniel, I felt exhausted and I was sick for some days. Then I got up and carried out the king’s work; but I was numbed by what I had seen, and no one could understand it.

'''

xref:027-daniel/027-daniel-007.adoc#v27-7-0[&#60; Capítulo Anterior] | <<v27-8-0,Topo>> | xref:027-daniel/027-daniel-009.adoc#v27-9-0[Próximo Capítulo &#62;]