include::./index.adoc[]

[[v31-1-0]]
=== Obadiah, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v31-1-1]]

^<<v31-1-1,1>>^ The vision of O·ba·diʹah:^&#42;1^
This is what the Sovereign Lord Jehovah says regarding Eʹdom:
“We have heard a report from Jehovah,
An envoy has been sent among the nations:
‘Rise up, let us prepare for battle against her.’”

[NOTE]
====
. Meaning “Servant of Jehovah.”
====

[[v31-1-2]]

^<<v31-1-2,2>>^ “Look! I have made you insignificant among the nations;
You are utterly despised.

[[v31-1-3]]

^<<v31-1-3,3>>^ The presumptuousness of your heart has deceived you,
You who reside in the retreats of the crag,
Dwelling in the height, saying in your heart,
‘Who will bring me down to the earth?’

[[v31-1-4]]

^<<v31-1-4,4>>^ Even if you make your dwelling high^&#42;1^ like the eagle,
Or if you place your nest among the stars,
I would bring you down from there,” declares Jehovah.

[NOTE]
====
. Or possibly, “you fly high.”
====

[[v31-1-5]]

^<<v31-1-5,5>>^ “If thieves would come to you, robbers by night,
(How utterly you will be destroyed!)^&#42;1^
Would they not steal only what they wanted?
Or if it were grape gatherers who would come to you,
Would they not leave some gleanings behind?

[NOTE]
====
. Or possibly, “How much would they destroy?”
====

[[v31-1-6]]

^<<v31-1-6,6>>^ O how Eʹsau has been searched out!
How his hidden treasures have been sought after!

[[v31-1-7]]

^<<v31-1-7,7>>^ They have driven you to the border.
All your allies^&#42;1^ have deceived you.
The men at peace with you have prevailed against you.
Those eating bread with you will place a net under you,
But you will not discern it.

[NOTE]
====
. Or “those in covenant with you.”
====

[[v31-1-8]]

^<<v31-1-8,8>>^ In that day,” declares Jehovah,
“Will I not destroy the wise ones out of Eʹdom
And discernment out of the mountainous region of Eʹsau?

[[v31-1-9]]

^<<v31-1-9,9>>^ And your warriors will become terrified, O Teʹman,
Because each one in the mountainous region of Eʹsau will be destroyed in the slaughter.

[[v31-1-10]]

^<<v31-1-10,10>>^ Because of the violence done to your brother Jacob,
Shame will cover you,
And you will perish forever.

[[v31-1-11]]

^<<v31-1-11,11>>^ On the day when you stood off to the side,
On the day when strangers took his army into captivity,
When foreigners entered his gate and cast lots over Jerusalem,
You acted like one of them.

[[v31-1-12]]

^<<v31-1-12,12>>^ You should not gloat over your brother’s day on the day of his misfortune,
You should not rejoice over the people of Judah on the day of their perishing,
And you should not speak so arrogantly on the day of their distress.

[[v31-1-13]]

^<<v31-1-13,13>>^ You should not come into the gate of my people in the day of their disaster,
You should not gloat over his calamity in the day of his disaster,
And you should not lay your hands on his wealth in the day of his disaster.

[[v31-1-14]]

^<<v31-1-14,14>>^ You should not stand at the crossroads to slaughter his escapees,
And you should not hand over his survivors in the day of distress.

[[v31-1-15]]

^<<v31-1-15,15>>^ For the day of Jehovah against all the nations is near.
As you have done, so it will be done to you.
The way you treated others will come back on your own head.

[[v31-1-16]]

^<<v31-1-16,16>>^ For in the way that you have drunk on my holy mountain,
All the nations will keep drinking constantly.
They will drink and gulp down,
And they will be as though they had never existed.

[[v31-1-17]]

^<<v31-1-17,17>>^ But on Mount Zion will be those who escape,
And it will be holy;
And the house of Jacob will take possession of the things belonging to them.

[[v31-1-18]]

^<<v31-1-18,18>>^ The house of Jacob will become a fire,
The house of Joseph a flame,
And the house of Eʹsau like stubble;
They will set them ablaze and consume them,
And there will be no survivor of the house of Eʹsau,
For Jehovah himself has spoken.

[[v31-1-19]]

^<<v31-1-19,19>>^ They will take possession of the Negʹeb and the mountainous region of Eʹsau,
Of the She·pheʹlah and the land of the Phi·lisʹtines.
They will take possession of the field of Eʹphra·im and the field of Sa·marʹi·a,
And Benjamin will take possession of Gilʹe·ad.

[[v31-1-20]]

^<<v31-1-20,20>>^ To the exiles of this rampart,^&#42;1^
To the people of Israel will belong the land of the Caʹnaan·ites as far as Zarʹe·phath.
And the exiles of Jerusalem, who were in Se·pharʹad, will possess the cities of the Negʹeb.

[NOTE]
====
. Or “fortification.”
====

[[v31-1-21]]

^<<v31-1-21,21>>^ And saviors will go up on Mount Zion
To judge the mountainous region of Eʹsau,
And the kingship will become Jehovah’s.”

'''

xref:030-amos/030-amos-009.adoc#v30-9-0[&#60; Capítulo Anterior] | <<v31-1-0,Topo>> | xref:032-jonah/032-jonah-001.adoc#v32-1-0[Próximo Capítulo &#62;]