include::./index.adoc[]

[[v13-3-0]]
=== The First of Chronicles, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-3-1]]

^<<v13-3-1,1>>^ These were the sons of David who were born to him in Hebʹron: the firstborn Amʹnon, whose mother was A·hinʹo·am of Jezʹre·el; the second, Daniel, whose mother was Abʹi·gail the Carʹmel·ite;

[[v13-3-2]]

^<<v13-3-2,2>>^ the third, Abʹsa·lom the son of Maʹa·cah the daughter of Talʹmai the king of Geshʹur; the fourth, Ad·o·niʹjah the son of Hagʹgith;

[[v13-3-3]]

^<<v13-3-3,3>>^ the fifth, Sheph·a·tiʹah, whose mother was A·biʹtal; and the sixth, Ithʹre·am, whose mother was David’s wife Egʹlah.

[[v13-3-4]]

^<<v13-3-4,4>>^ These six were born to him in Hebʹron; he reigned there for 7 years and 6 months, and for 33 years he reigned in Jerusalem.

[[v13-3-5]]

^<<v13-3-5,5>>^ These were born to him in Jerusalem: Shimʹe·a, Shoʹbab, Nathan, and Solʹo·mon; the mother of these four was Bath-sheʹba the daughter of Amʹmi·el.

[[v13-3-6]]

^<<v13-3-6,6>>^ And nine other sons were Ibʹhar, E·lishʹa·ma, E·liphʹe·let,

[[v13-3-7]]

^<<v13-3-7,7>>^ Noʹgah, Neʹpheg, Ja·phiʹa,

[[v13-3-8]]

^<<v13-3-8,8>>^ E·lishʹa·ma, E·liʹa·da, and E·liphʹe·let.

[[v13-3-9]]

^<<v13-3-9,9>>^ All of these were the sons of David, besides the sons of the concubines, and Taʹmar was their sister.

[[v13-3-10]]

^<<v13-3-10,10>>^ The son of Solʹo·mon was Re·ho·boʹam; A·biʹjah was his son, Aʹsa his son, Je·hoshʹa·phat his son,

[[v13-3-11]]

^<<v13-3-11,11>>^ Je·hoʹram his son, A·ha·ziʹah his son, Je·hoʹash his son,

[[v13-3-12]]

^<<v13-3-12,12>>^ Am·a·ziʹah his son, Az·a·riʹah his son, Joʹtham his son,

[[v13-3-13]]

^<<v13-3-13,13>>^ Aʹhaz his son, Hez·e·kiʹah his son, Ma·nasʹseh his son,

[[v13-3-14]]

^<<v13-3-14,14>>^ Aʹmon his son, Jo·siʹah his son.

[[v13-3-15]]

^<<v13-3-15,15>>^ The sons of Jo·siʹah were the firstborn, Jo·haʹnan, the second, Je·hoiʹa·kim, the third, Zed·e·kiʹah, the fourth, Shalʹlum.

[[v13-3-16]]

^<<v13-3-16,16>>^ The sons of Je·hoiʹa·kim were Jec·o·niʹah his son and Zed·e·kiʹah his son.

[[v13-3-17]]

^<<v13-3-17,17>>^ The sons of Jec·o·niʹah the prisoner were She·alʹti·el,

[[v13-3-18]]

^<<v13-3-18,18>>^ Mal·chiʹram, Pe·daiʹah, She·nazʹzar, Jek·a·miʹah, Hoshʹa·ma, and Ned·a·biʹah.

[[v13-3-19]]

^<<v13-3-19,19>>^ The sons of Pe·daiʹah were Ze·rubʹba·bel and Shimʹe·i; and the sons of Ze·rubʹba·bel were Me·shulʹlam and Han·a·niʹah (and She·loʹmith was their sister);

[[v13-3-20]]

^<<v13-3-20,20>>^ and five other sons were Ha·shuʹbah, Oʹhel, Ber·e·chiʹah, Has·a·diʹah, and Juʹshab-heʹsed.

[[v13-3-21]]

^<<v13-3-21,21>>^ And the sons of Han·a·niʹah were Pel·a·tiʹah and Je·shaʹiah; the son^&#42;1^ of Je·shaʹiah was Re·phaʹiah; the son^&#42;2^ of Re·phaʹiah was Arʹnan; the son^&#42;3^ of Arʹnan was O·ba·diʹah; the son^&#42;4^ of O·ba·diʹah was Shec·a·niʹah;

[NOTE]
====
. Lit., “sons.”
. Lit., “sons.”
. Lit., “sons.”
. Lit., “sons.”
====

[[v13-3-22]]

^<<v13-3-22,22>>^ and the sons of Shec·a·niʹah were She·maiʹah and the sons of She·maiʹah: Hatʹtush, Iʹgal, Ba·riʹah, Ne·a·riʹah, and Shaʹphat—six in all.

[[v13-3-23]]

^<<v13-3-23,23>>^ And the sons of Ne·a·riʹah were Eli·o·eʹnai, Hiz·kiʹah, and Az·riʹkam, three.

[[v13-3-24]]

^<<v13-3-24,24>>^ And the sons of Eli·o·eʹnai were Hod·a·viʹah, E·liʹa·shib, Pe·laʹiah, Akʹkub, Jo·haʹnan, De·laʹiah, and A·naʹni, seven.

'''

xref:013-1-chronicles/013-1-chronicles-002.adoc#v13-2-0[&#60; Capítulo Anterior] | <<v13-3-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-004.adoc#v13-4-0[Próximo Capítulo &#62;]