include::./index.adoc[]

[[v13-17-0]]
=== The First of Chronicles, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-17-1]]

^<<v13-17-1,1>>^ As soon as David was settled in his own house,^&#42;1^ he said to Nathan the prophet: “Here I am living in a house of cedars while the ark of the covenant of Jehovah is under tent cloths.”

[NOTE]
====
. Or “palace.”
====

[[v13-17-2]]

^<<v13-17-2,2>>^ Nathan replied to David: “Do whatever is in your heart, for the true God is with you.”

[[v13-17-3]]

^<<v13-17-3,3>>^ On that very night, the word of God came to Nathan, saying:

[[v13-17-4]]

^<<v13-17-4,4>>^ “Go and say to my servant David, ‘This is what Jehovah says: “You are not the one who will build the house for me to dwell in.

[[v13-17-5]]

^<<v13-17-5,5>>^ For I have not dwelled in a house from the day I brought Israel out to this day, but I continued going from tent to tent and from one tabernacle to another.^&#42;1^

[NOTE]
====
. Possibly meaning “from one tent site to another and from one dwelling place to another.”
====

[[v13-17-6]]

^<<v13-17-6,6>>^ During all the time that I went with all Israel, did I ever say one word to any of the judges of Israel whom I appointed to shepherd my people, saying, ‘Why did you not build a house of cedars for me?’”’

[[v13-17-7]]

^<<v13-17-7,7>>^ “Now say this to my servant David, ‘This is what Jehovah of armies says: “I took you from the pastures, from following the flock, to become a leader over my people Israel.

[[v13-17-8]]

^<<v13-17-8,8>>^ And I will be with you wherever you go, and I will do away with^&#42;1^ all your enemies from before you; and I will make a name for you like the name of the great men of the earth.

[NOTE]
====
. Lit., “cut off.”
====

[[v13-17-9]]

^<<v13-17-9,9>>^ I will appoint a place for my people Israel and settle them, and they will live there and not be disturbed anymore; and wicked men will not oppress them^&#42;1^ again as they did in the past,

[NOTE]
====
. Lit., “wear them out.”
====

[[v13-17-10]]

^<<v13-17-10,10>>^ from the day that I appointed judges over my people Israel. And I will subdue all your enemies. Moreover, I tell you, ‘Jehovah will build a house^&#42;1^ for you.’

[NOTE]
====
. Or “dynasty.”
====

[[v13-17-11]]

^<<v13-17-11,11>>^ “‘“When your days come to an end and you go to be with your forefathers, I will raise up your offspring^&#42;1^ after you, one of your sons, and I will firmly establish his kingship.

[NOTE]
====
. Lit., “seed.”
====

[[v13-17-12]]

^<<v13-17-12,12>>^ He is the one who will build a house for me, and I will firmly establish his throne forever.

[[v13-17-13]]

^<<v13-17-13,13>>^ I will become his father, and he will become my son. I will not remove my loyal love from him the way I removed it from the one who was prior to you.

[[v13-17-14]]

^<<v13-17-14,14>>^ I will cause him to stand in my house and in my kingship forever, and his throne will last forever.”’”

[[v13-17-15]]

^<<v13-17-15,15>>^ Nathan told David all these words and this entire vision.

[[v13-17-16]]

^<<v13-17-16,16>>^ At that King David came in and sat down before Jehovah and said: “Who am I, O Jehovah God? And what is my house that you have brought me this far?

[[v13-17-17]]

^<<v13-17-17,17>>^ As if this were not enough, O God, you also speak about the house of your servant down to a distant future time, and you have looked on me as if I were a man who should be further exalted,^&#42;1^ O Jehovah God.

[NOTE]
====
. Or “a man of high station.”
====

[[v13-17-18]]

^<<v13-17-18,18>>^ What more can your servant David say to you about the honor given me when you know your servant so well?

[[v13-17-19]]

^<<v13-17-19,19>>^ O Jehovah, for the sake of your servant and in agreement with your heart^&#42;1^ you have done all these great things by revealing your greatness.

[NOTE]
====
. Or “in harmony with your will.”
====

[[v13-17-20]]

^<<v13-17-20,20>>^ O Jehovah, there is no one like you, and there is no God except you; everything we have heard with our ears confirms this.

[[v13-17-21]]

^<<v13-17-21,21>>^ And what other nation on earth is like your people Israel? The true God went and redeemed them as his people. You made a name for yourself by your great and awe-inspiring deeds, driving out nations from before your people, whom you redeemed from Egypt.

[[v13-17-22]]

^<<v13-17-22,22>>^ You made your people Israel your own people for all time; and you, O Jehovah, became their God.

[[v13-17-23]]

^<<v13-17-23,23>>^ Now, O Jehovah, may the promise you have made concerning your servant and his house prove faithful for all time, and may you do just as you have promised.

[[v13-17-24]]

^<<v13-17-24,24>>^ May your name endure^&#42;1^ and be exalted forever, so that people may say, ‘Jehovah of armies, the God of Israel, is God to Israel,’ and may the house of your servant David be firmly established before you.

[NOTE]
====
. Or “prove faithful.”
====

[[v13-17-25]]

^<<v13-17-25,25>>^ For you, my God, have revealed to your servant your purpose to build him a house.^&#42;1^ That is why your servant has the confidence to offer this prayer to you.

[NOTE]
====
. Or “dynasty.”
====

[[v13-17-26]]

^<<v13-17-26,26>>^ And now, O Jehovah, you are the true God, and you have promised these good things concerning your servant.

[[v13-17-27]]

^<<v13-17-27,27>>^ So may it please you to bless the house of your servant, and may it continue forever before you, for you, O Jehovah, have blessed, and it is blessed forever.”

'''

xref:013-1-chronicles/013-1-chronicles-016.adoc#v13-16-0[&#60; Capítulo Anterior] | <<v13-17-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-018.adoc#v13-18-0[Próximo Capítulo &#62;]