include::./index.adoc[]

[[v13-13-0]]
=== The First of Chronicles, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-13-1]]

^<<v13-13-1,1>>^ David consulted with the chiefs of the thousands and of the hundreds and with every leader.

[[v13-13-2]]

^<<v13-13-2,2>>^ Then David said to all the congregation of Israel: “If it seems good to you and it is acceptable to Jehovah our God, let us send word to our remaining brothers in all regions of Israel and also to the priests and the Levites in their cities with pastures to come and join us.

[[v13-13-3]]

^<<v13-13-3,3>>^ And let us bring back the Ark of our God.” For they had not cared for it in the days of Saul.

[[v13-13-4]]

^<<v13-13-4,4>>^ All the congregation agreed to do that, for it seemed right to all the people.

[[v13-13-5]]

^<<v13-13-5,5>>^ So David congregated all Israel, from the river^&#42;1^ of Egypt as far as Leʹbo-haʹmath,^&#42;2^ to bring the Ark of the true God from Kirʹi·ath-jeʹa·rim.

[NOTE]
====
. Or “from Shihor.”
. Or “the entrance of Hamath.”
====

[[v13-13-6]]

^<<v13-13-6,6>>^ David and all Israel went up to Baʹal·ah, to Kirʹi·ath-jeʹa·rim, which belongs to Judah, to bring up from there the Ark of the true God, Jehovah, who sits enthroned above^&#42;1^ the cherubs, where his name is called on.

[NOTE]
====
. Or possibly, “between.”
====

[[v13-13-7]]

^<<v13-13-7,7>>^ However, they placed the Ark of the true God on a new wagon and brought it from the house of A·binʹa·dab, and Uzʹzah and A·hiʹo were leading the wagon.

[[v13-13-8]]

^<<v13-13-8,8>>^ David and all Israel were celebrating before the true God with all their might, accompanied by songs, harps, other stringed instruments, tambourines, cymbals, and trumpets.

[[v13-13-9]]

^<<v13-13-9,9>>^ But when they came to the threshing floor of Chiʹdon, Uzʹzah thrust his hand out and grabbed hold of the Ark, for the cattle nearly upset it.

[[v13-13-10]]

^<<v13-13-10,10>>^ At that Jehovah’s anger blazed against Uzʹzah, and He struck him down because he had thrust his hand out to the Ark, and he died there before God.

[[v13-13-11]]

^<<v13-13-11,11>>^ But David became angry^&#42;1^ because Jehovah’s wrath had broken through against Uzʹzah; and that place has been called Peʹrez-uzʹzah^&#42;2^ down to this day.

[NOTE]
====
. Or “upset.”
. Meaning “Breach Against Uzzah.”
====

[[v13-13-12]]

^<<v13-13-12,12>>^ So David became fearful of the true God on that day and said: “How can I bring the Ark of the true God to me?”

[[v13-13-13]]

^<<v13-13-13,13>>^ David did not bring the Ark to where he was in the City of David, but he had it taken to the house of Oʹbed-eʹdom the Gitʹtite.

[[v13-13-14]]

^<<v13-13-14,14>>^ The Ark of the true God was with the household of Oʹbed-eʹdom, remaining at his house for three months, and Jehovah kept blessing the household of Oʹbed-eʹdom and all he had.

'''

xref:013-1-chronicles/013-1-chronicles-012.adoc#v13-12-0[&#60; Capítulo Anterior] | <<v13-13-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-014.adoc#v13-14-0[Próximo Capítulo &#62;]