include::./index.adoc[]

[[v13-18-0]]
=== The First of Chronicles, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-18-1]]

^<<v13-18-1,1>>^ Some time later, David defeated the Phi·lisʹtines and subdued them and took Gath and its dependent^&#42;1^ towns out of the hands of the Phi·lisʹtines.

[NOTE]
====
. Or “surrounding.”
====

[[v13-18-2]]

^<<v13-18-2,2>>^ Then he defeated Moʹab, and the Moʹab·ites became David’s servants and brought tribute.

[[v13-18-3]]

^<<v13-18-3,3>>^ David defeated King Had·ad·eʹzer of Zoʹbah near Haʹmath as he was on his way to establish his authority at the Eu·phraʹtes River.

[[v13-18-4]]

^<<v13-18-4,4>>^ David captured 1,000 chariots, 7,000 horsemen, and 20,000 foot soldiers from him. Then David hamstrung all but 100 of the chariot horses.

[[v13-18-5]]

^<<v13-18-5,5>>^ When the Syrians of Damascus came to help King Had·ad·eʹzer of Zoʹbah, David struck down 22,000 of the Syrians.

[[v13-18-6]]

^<<v13-18-6,6>>^ David then established garrisons in Syria of Damascus, and the Syrians became David’s servants and brought tribute. Jehovah gave David victory^&#42;1^ wherever he went.

[NOTE]
====
. Or “salvation.”
====

[[v13-18-7]]

^<<v13-18-7,7>>^ Moreover, David took the circular shields of gold from the servants of Had·ad·eʹzer and brought them to Jerusalem.

[[v13-18-8]]

^<<v13-18-8,8>>^ From Tibʹhath and Cun, cities of Had·ad·eʹzer, David took a great quantity of copper. With it Solʹo·mon made the copper Sea, the pillars, and the copper utensils.

[[v13-18-9]]

^<<v13-18-9,9>>^ When King Toʹu of Haʹmath heard that David had defeated the entire army of King Had·ad·eʹzer of Zoʹbah,

[[v13-18-10]]

^<<v13-18-10,10>>^ he immediately sent his son Ha·doʹram to King David to ask about his welfare and to congratulate him because he had fought and defeated Had·ad·eʹzer (for Had·ad·eʹzer had often fought against Toʹu), and he brought all sorts of articles of gold, silver, and copper.

[[v13-18-11]]

^<<v13-18-11,11>>^ King David sanctified these to Jehovah, along with the silver and the gold that he had carried off from all the nations: from Eʹdom and Moʹab, from the Amʹmon·ites, the Phi·lisʹtines, and the A·malʹek·ites.

[[v13-18-12]]

^<<v13-18-12,12>>^ A·bishʹai the son of Ze·ruʹiah struck down 18,000 Eʹdom·ites in the Valley of Salt.

[[v13-18-13]]

^<<v13-18-13,13>>^ He established garrisons in Eʹdom, and all the Eʹdom·ites became David’s servants. Jehovah gave David victory^&#42;1^ wherever he went.

[NOTE]
====
. Or “salvation.”
====

[[v13-18-14]]

^<<v13-18-14,14>>^ David kept reigning over all Israel, and he was administering justice and righteousness for all his people.

[[v13-18-15]]

^<<v13-18-15,15>>^ Joʹab the son of Ze·ruʹiah was over the army, Je·hoshʹa·phat the son of A·hiʹlud was recorder,

[[v13-18-16]]

^<<v13-18-16,16>>^ Zaʹdok the son of A·hiʹtub and A·himʹe·lech the son of A·biʹa·thar were priests, and Shavʹsha was secretary.

[[v13-18-17]]

^<<v13-18-17,17>>^ Be·naiʹah the son of Je·hoiʹa·da was over the Cherʹe·thites and the Pelʹe·thites. And David’s sons were first in position next to the king.

'''

xref:013-1-chronicles/013-1-chronicles-017.adoc#v13-17-0[&#60; Capítulo Anterior] | <<v13-18-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-019.adoc#v13-19-0[Próximo Capítulo &#62;]