include::./index.adoc[]

[[v13-21-0]]
=== The First of Chronicles, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-21-1]]

^<<v13-21-1,1>>^ Then Satan^&#42;1^ stood up against Israel and incited David to number Israel.

[NOTE]
====
. Or possibly, “a resister.”
====

[[v13-21-2]]

^<<v13-21-2,2>>^ So David said to Joʹab and the chiefs of the people: “Go, count Israel from Beʹer-sheʹba to Dan; then report to me so that I may know their number.”

[[v13-21-3]]

^<<v13-21-3,3>>^ But Joʹab said: “May Jehovah multiply his people 100 times! My lord the king, are not all of them already servants of my lord? Why does my lord want to do this? Why should he become a cause of guilt to Israel?”

[[v13-21-4]]

^<<v13-21-4,4>>^ But the king’s word prevailed over Joʹab. So Joʹab went out and traveled throughout Israel, after which he came to Jerusalem.

[[v13-21-5]]

^<<v13-21-5,5>>^ Joʹab now gave to David the number of the people who were registered. All Israel amounted to 1,100,000 men armed with swords, and Judah, 470,000 men armed with swords.

[[v13-21-6]]

^<<v13-21-6,6>>^ But Leʹvi and Benjamin were not registered among them, because the king’s word was detestable to Joʹab.

[[v13-21-7]]

^<<v13-21-7,7>>^ Now this was very displeasing to the true God, so he struck Israel.

[[v13-21-8]]

^<<v13-21-8,8>>^ David then said to the true God: “I have sinned greatly by doing this. And now, please, forgive your servant’s error, for I have acted very foolishly.”

[[v13-21-9]]

^<<v13-21-9,9>>^ Jehovah then spoke to Gad, David’s visionary, saying:

[[v13-21-10]]

^<<v13-21-10,10>>^ “Go and say to David, ‘This is what Jehovah says: “I am giving you three options. Choose the one that I should bring on you.”’”

[[v13-21-11]]

^<<v13-21-11,11>>^ So Gad came in to David and said to him: “This is what Jehovah says, ‘Take your pick

[[v13-21-12]]

^<<v13-21-12,12>>^ whether there should be three years of famine, or three months of being swept away by your adversaries while the sword of your enemies overtakes you, or three days of the sword of Jehovah—pestilence in the land—with Jehovah’s angel bringing destruction in all the territory of Israel.’ Now consider what I should reply to the One who sent me.”

[[v13-21-13]]

^<<v13-21-13,13>>^ So David said to Gad: “It is very distressing to me. Please, let me fall into the hand of Jehovah, for his mercy is very great; but do not let me fall into the hand of man.”

[[v13-21-14]]

^<<v13-21-14,14>>^ Then Jehovah sent a pestilence on Israel, so that 70,000 people out of Israel fell.

[[v13-21-15]]

^<<v13-21-15,15>>^ Moreover, the true God sent an angel to Jerusalem to destroy it; but as he was about to do so, Jehovah saw it and felt regret^&#42;1^ over the calamity, and he said to the angel bringing destruction: “It is enough! Now let your hand drop.” Jehovah’s angel was standing close to the threshing floor of Orʹnan the Jebʹu·site.

[NOTE]
====
. Or “grieved.”
====

[[v13-21-16]]

^<<v13-21-16,16>>^ When David raised his eyes, he saw Jehovah’s angel standing between the earth and the heavens with a drawn sword in his hand extended toward Jerusalem. David and the elders, covered with sackcloth, at once threw themselves down with their faces to the ground.

[[v13-21-17]]

^<<v13-21-17,17>>^ David said to the true God: “Was it not I who said to number the people? I am the one who sinned, and I am the one who did wrong; but these sheep—what have they done? O Jehovah my God, let your hand, please, come against me and my father’s house; but do not bring this scourge on your people.”

[[v13-21-18]]

^<<v13-21-18,18>>^ Jehovah’s angel then told Gad to tell David to go up and erect an altar to Jehovah on the threshing floor of Orʹnan the Jebʹu·site.

[[v13-21-19]]

^<<v13-21-19,19>>^ So David went up at the word of Gad, which he had spoken in the name of Jehovah.

[[v13-21-20]]

^<<v13-21-20,20>>^ Meanwhile, Orʹnan turned around and saw the angel, and his four sons who were with him hid themselves. Now Orʹnan had been threshing wheat.

[[v13-21-21]]

^<<v13-21-21,21>>^ When David came up to him, Orʹnan looked and saw David, and he immediately went out from the threshing floor and bowed down to David with his face to the ground.

[[v13-21-22]]

^<<v13-21-22,22>>^ David said to Orʹnan: “Sell^&#42;1^ me the site of the threshing floor, so that I may build an altar to Jehovah on it. Sell it to me for the full price, so that the scourge against the people may be halted.”

[NOTE]
====
. Lit., “Give.”
====

[[v13-21-23]]

^<<v13-21-23,23>>^ But Orʹnan said to David: “Take it as your own, and let my lord the king do what seems good to him.^&#42;1^ Here, I am providing the cattle for burnt offerings and the threshing sledge for the wood and the wheat as a grain offering. I give all of it.”

[NOTE]
====
. Lit., “what is good in his eyes.”
====

[[v13-21-24]]

^<<v13-21-24,24>>^ However, King David said to Orʹnan: “No, I must buy it for the full price, because I will not take what is yours and give it to Jehovah or offer up burnt sacrifices that cost me nothing.”

[[v13-21-25]]

^<<v13-21-25,25>>^ So David gave Orʹnan 600 gold shekels^&#42;1^ by weight for the site.

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v13-21-26]]

^<<v13-21-26,26>>^ And David built an altar there to Jehovah and offered up burnt sacrifices and communion sacrifices, and he called on Jehovah, who now answered him with fire from the heavens on the altar of burnt offering.

[[v13-21-27]]

^<<v13-21-27,27>>^ Then Jehovah ordered the angel to return his sword to its sheath.

[[v13-21-28]]

^<<v13-21-28,28>>^ At that time, when David saw that Jehovah had answered him at the threshing floor of Orʹnan the Jebʹu·site, he continued to sacrifice there.

[[v13-21-29]]

^<<v13-21-29,29>>^ However, the tabernacle of Jehovah that Moses had made in the wilderness and the altar of burnt offering were at that time on the high place at Gibʹe·on.

[[v13-21-30]]

^<<v13-21-30,30>>^ But David had not been able to go before it to consult God, for he was terrified because of the sword of Jehovah’s angel.

'''

xref:013-1-chronicles/013-1-chronicles-020.adoc#v13-20-0[&#60; Capítulo Anterior] | <<v13-21-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-022.adoc#v13-22-0[Próximo Capítulo &#62;]