include::./index.adoc[]

[[v13-14-0]]
=== The First of Chronicles, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-14-1]]

^<<v13-14-1,1>>^ King Hiʹram of Tyre sent messengers to David, along with cedar timbers, stonemasons,^&#42;1^ and woodworkers to build a house^&#42;2^ for him.

[NOTE]
====
. Or “builders of walls.”
. Or “palace.”
====

[[v13-14-2]]

^<<v13-14-2,2>>^ And David knew that Jehovah had firmly established him as king over Israel, for his kingship was highly exalted for the sake of His people Israel.

[[v13-14-3]]

^<<v13-14-3,3>>^ David took more wives in Jerusalem, and David became father to more sons and daughters.

[[v13-14-4]]

^<<v13-14-4,4>>^ These are the names of the children born to him in Jerusalem: Sham·muʹa, Shoʹbab, Nathan, Solʹo·mon,

[[v13-14-5]]

^<<v13-14-5,5>>^ Ibʹhar, E·liʹshu·a, Elʹpe·let,

[[v13-14-6]]

^<<v13-14-6,6>>^ Noʹgah, Neʹpheg, Ja·phiʹa,

[[v13-14-7]]

^<<v13-14-7,7>>^ E·lishʹa·ma, Be·e·liʹa·da, and E·liphʹe·let.

[[v13-14-8]]

^<<v13-14-8,8>>^ When the Phi·lisʹtines heard that David had been anointed as king over all Israel, all the Phi·lisʹtines came up to search for David. When David heard about it, he went out against them.

[[v13-14-9]]

^<<v13-14-9,9>>^ Then the Phi·lisʹtines came in and kept making raids in the Valley^&#42;1^ of Rephʹa·im.

[NOTE]
====
. Or “Low Plain.”
====

[[v13-14-10]]

^<<v13-14-10,10>>^ David inquired of God, saying: “Should I go up against the Phi·lisʹtines? Will you give them into my hand?” At this Jehovah said to him: “Go up, and I will surely give them into your hand.”

[[v13-14-11]]

^<<v13-14-11,11>>^ So David went up to Baʹal-pe·raʹzim, and he struck them down there. At that David said: “The true God has broken through my enemies by my hand, like a breach made by waters.” That is why they named that place Baʹal-pe·raʹzim.^&#42;1^

[NOTE]
====
. Meaning “Master of Breakings Through.”
====

[[v13-14-12]]

^<<v13-14-12,12>>^ The Phi·lisʹtines abandoned their gods there, and when David gave the order, these were burned in the fire.

[[v13-14-13]]

^<<v13-14-13,13>>^ Later the Phi·lisʹtines once again made a raid in the valley.^&#42;1^

[NOTE]
====
. Or “low plain.”
====

[[v13-14-14]]

^<<v13-14-14,14>>^ David again inquired of God, but the true God said to him: “Do not go directly up after them. Instead, go around behind them, and come against them in front of the baʹca bushes.

[[v13-14-15]]

^<<v13-14-15,15>>^ And when you hear the sound of marching in the tops of the baʹca bushes, launch your attack, for the true God will have gone out before you to strike down the army of the Phi·lisʹtines.”

[[v13-14-16]]

^<<v13-14-16,16>>^ So David did just as the true God commanded him, and they struck down the Phi·lisʹtine army from Gibʹe·on to Geʹzer.

[[v13-14-17]]

^<<v13-14-17,17>>^ And David’s fame spread into all the lands, and Jehovah put the dread of him upon all the nations.

'''

xref:013-1-chronicles/013-1-chronicles-013.adoc#v13-13-0[&#60; Capítulo Anterior] | <<v13-14-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-015.adoc#v13-15-0[Próximo Capítulo &#62;]