include::./index.adoc[]

[[v13-8-0]]
=== The First of Chronicles, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-8-1]]

^<<v13-8-1,1>>^ Benjamin became father to Beʹla his firstborn, Ashʹbel the second, A·harʹah the third,

[[v13-8-2]]

^<<v13-8-2,2>>^ Noʹhah the fourth, and Raʹpha the fifth.

[[v13-8-3]]

^<<v13-8-3,3>>^ Beʹla’s sons were Adʹdar, Geʹra, A·biʹhud,

[[v13-8-4]]

^<<v13-8-4,4>>^ Ab·i·shuʹa, Naʹa·man, A·hoʹah,

[[v13-8-5]]

^<<v13-8-5,5>>^ Geʹra, She·phuʹphan, and Huʹram.

[[v13-8-6]]

^<<v13-8-6,6>>^ These were the sons of Eʹhud, the heads of the paternal houses of the inhabitants of Geʹba, who were taken into exile to Manʹa·hath:

[[v13-8-7]]

^<<v13-8-7,7>>^ Naʹa·man, A·hiʹjah, and Geʹra—he was the one who took them into exile and he became father to Uzʹza and A·hiʹhud.

[[v13-8-8]]

^<<v13-8-8,8>>^ Sha·ha·raʹim became father to children in the territory^&#42;1^ of Moʹab after he sent them away. Huʹshim and Baʹa·ra were his wives.^&#42;2^

[NOTE]
====
. Lit., “field.”
. Or possibly, “after he sent away his wives Hu­shim and Baara.”
====

[[v13-8-9]]

^<<v13-8-9,9>>^ And by his wife Hoʹdesh, he became father to Joʹbab, Zibʹi·a, Meʹsha, Malʹcam,

[[v13-8-10]]

^<<v13-8-10,10>>^ Jeʹuz, Sa·chiʹa, and Mirʹmah. These were his sons, heads of the paternal houses.

[[v13-8-11]]

^<<v13-8-11,11>>^ By Huʹshim he became father to A·biʹtub and El·paʹal.

[[v13-8-12]]

^<<v13-8-12,12>>^ And the sons of El·paʹal were Eʹber, Miʹsham, Sheʹmed (who built Oʹno and Lod and its dependent^&#42;1^ towns),

[NOTE]
====
. Or “surrounding.”
====

[[v13-8-13]]

^<<v13-8-13,13>>^ Be·riʹah, and Sheʹma. These were heads of the paternal houses of the inhabitants of Aiʹja·lon. These drove out the inhabitants of Gath.

[[v13-8-14]]

^<<v13-8-14,14>>^ And there were A·hiʹo, Shaʹshak, Jerʹe·moth,

[[v13-8-15]]

^<<v13-8-15,15>>^ Zeb·a·diʹah, Aʹrad, Eʹder,

[[v13-8-16]]

^<<v13-8-16,16>>^ Miʹcha·el, Ishʹpah, Joʹha, the sons of Be·riʹah;

[[v13-8-17]]

^<<v13-8-17,17>>^ and Zeb·a·diʹah, Me·shulʹlam, Hizʹki, Heʹber,

[[v13-8-18]]

^<<v13-8-18,18>>^ Ishʹme·rai, Iz·liʹah, Joʹbab, the sons of El·paʹal;

[[v13-8-19]]

^<<v13-8-19,19>>^ and Jaʹkim, Zichʹri, Zabʹdi,

[[v13-8-20]]

^<<v13-8-20,20>>^ E·li·eʹnai, Zilʹle·thai, Eʹli·el,

[[v13-8-21]]

^<<v13-8-21,21>>^ A·daiʹah, Be·raʹiah, Shimʹrath, the sons of Shimʹe·i;

[[v13-8-22]]

^<<v13-8-22,22>>^ and Ishʹpan, Eʹber, Eʹli·el,

[[v13-8-23]]

^<<v13-8-23,23>>^ Abʹdon, Zichʹri, Haʹnan,

[[v13-8-24]]

^<<v13-8-24,24>>^ Han·a·niʹah, Eʹlam, An·tho·thiʹjah,

[[v13-8-25]]

^<<v13-8-25,25>>^ Iph·deʹiah, Pe·nuʹel, the sons of Shaʹshak;

[[v13-8-26]]

^<<v13-8-26,26>>^ and Shamʹshe·rai, She·ha·riʹah, Ath·a·liʹah,

[[v13-8-27]]

^<<v13-8-27,27>>^ Ja·a·re·shiʹah, E·liʹjah, Zichʹri, the sons of Je·roʹham.

[[v13-8-28]]

^<<v13-8-28,28>>^ These were heads of the paternal houses by their descendants. These headmen lived in Jerusalem.

[[v13-8-29]]

^<<v13-8-29,29>>^ The father of Gibʹe·on, Je·iʹel, lived in Gibʹe·on. His wife’s name was Maʹa·cah.

[[v13-8-30]]

^<<v13-8-30,30>>^ And his firstborn son was Abʹdon, followed by Zur, Kish, Baʹal, Naʹdab,

[[v13-8-31]]

^<<v13-8-31,31>>^ Geʹdor, A·hiʹo, and Zeʹcher.

[[v13-8-32]]

^<<v13-8-32,32>>^ Mikʹloth became father to Shimʹe·ah. And they all lived near their brothers in Jerusalem, along with their other brothers.

[[v13-8-33]]

^<<v13-8-33,33>>^ Ner became father to Kish; Kish became father to Saul; Saul became father to Jonʹa·than, Malʹchi-shuʹa, A·binʹa·dab, and Esh·baʹal.^&#42;1^

[NOTE]
====
. Also called Ish-bosheth.
====

[[v13-8-34]]

^<<v13-8-34,34>>^ And Jonʹa·than’s son was Merʹib-baʹal.^&#42;1^ Merʹib-baʹal became father to Miʹcah.

[NOTE]
====
. Also called Mephibosheth.
====

[[v13-8-35]]

^<<v13-8-35,35>>^ And the sons of Miʹcah were Piʹthon, Melʹech, Ta·reʹa, and Aʹhaz.

[[v13-8-36]]

^<<v13-8-36,36>>^ Aʹhaz became father to Je·hoʹad·dah; Je·hoʹad·dah became father to Alʹe·meth, Azʹma·veth, and Zimʹri. Zimʹri became father to Moʹza.

[[v13-8-37]]

^<<v13-8-37,37>>^ Moʹza became father to Binʹe·a, Raʹphah his son, El·e·aʹsah his son, Aʹzel his son.

[[v13-8-38]]

^<<v13-8-38,38>>^ Aʹzel had six sons, and their names were Az·riʹkam, Boʹche·ru, Ishʹma·el, She·a·riʹah, O·ba·diʹah, and Haʹnan. All of these were the sons of Aʹzel.

[[v13-8-39]]

^<<v13-8-39,39>>^ And the sons of his brother Eʹshek were Uʹlam his firstborn, Jeʹush the second, and E·liphʹe·let the third.

[[v13-8-40]]

^<<v13-8-40,40>>^ And the sons of Uʹlam were mighty warriors who could handle^&#42;1^ the bow, and they had many sons and grandsons, numbering 150. All of these were descendants of Benjamin.

[NOTE]
====
. Lit., “who tread.”
====

'''

xref:013-1-chronicles/013-1-chronicles-007.adoc#v13-7-0[&#60; Capítulo Anterior] | <<v13-8-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-009.adoc#v13-9-0[Próximo Capítulo &#62;]