include::./index.adoc[]

[[v13-10-0]]
=== The First of Chronicles, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-10-1]]

^<<v13-10-1,1>>^ Now the Phi·lisʹtines were fighting against Israel. And the men of Israel fled from before the Phi·lisʹtines, and many fell slain on Mount Gil·boʹa.

[[v13-10-2]]

^<<v13-10-2,2>>^ The Phi·lisʹtines kept in close range of Saul and his sons, and the Phi·lisʹtines struck down Jonʹa·than, A·binʹa·dab, and Malʹchi-shuʹa, Saul’s sons.

[[v13-10-3]]

^<<v13-10-3,3>>^ The fighting grew fierce against Saul, and the archers found him, and he was wounded by the archers.

[[v13-10-4]]

^<<v13-10-4,4>>^ Then Saul said to his armor-bearer: “Draw your sword and run me through with it, so that these uncircumcised men may not come and deal ruthlessly^&#42;1^ with me.” But his armor-bearer was unwilling, because he was very much afraid. So Saul took the sword and fell on it.

[NOTE]
====
. Or “abusively.”
====

[[v13-10-5]]

^<<v13-10-5,5>>^ When his armor-bearer saw that Saul was dead, he too fell on his own sword and died.

[[v13-10-6]]

^<<v13-10-6,6>>^ Thus Saul and his three sons died, and all those of his house died together.

[[v13-10-7]]

^<<v13-10-7,7>>^ When all the people of Israel in the valley^&#42;1^ saw that everyone had fled and that Saul and his sons had died, they began to abandon their cities and flee; the Phi·lisʹtines then came and occupied them.

[NOTE]
====
. Or “low plain.”
====

[[v13-10-8]]

^<<v13-10-8,8>>^ The next day, when the Phi·lisʹtines came to strip the slain, they found Saul and his sons fallen on Mount Gil·boʹa.

[[v13-10-9]]

^<<v13-10-9,9>>^ So they stripped him and took off his head and his armor, and they sent word throughout the land of the Phi·lisʹtines to spread the news to their idols and the people.

[[v13-10-10]]

^<<v13-10-10,10>>^ Then they put his armor in the house^&#42;1^ of their god and fastened his skull to the house of Daʹgon.

[NOTE]
====
. Or “temple.”
====

[[v13-10-11]]

^<<v13-10-11,11>>^ When all those of Jaʹbesh in Gilʹe·ad heard about all that the Phi·lisʹtines had done to Saul,

[[v13-10-12]]

^<<v13-10-12,12>>^ all the warriors rose up and carried off the corpse of Saul and the corpses of his sons. They brought them to Jaʹbesh and buried their bones under the big tree in Jaʹbesh, and they fasted for seven days.

[[v13-10-13]]

^<<v13-10-13,13>>^ Thus Saul died for the unfaithfulness he had shown against Jehovah because he had not obeyed the word of Jehovah, also for consulting a spirit medium

[[v13-10-14]]

^<<v13-10-14,14>>^ instead of inquiring of Jehovah. So He put him to death and turned the kingship over to David the son of Jesʹse.

'''

xref:013-1-chronicles/013-1-chronicles-009.adoc#v13-9-0[&#60; Capítulo Anterior] | <<v13-10-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-011.adoc#v13-11-0[Próximo Capítulo &#62;]