include::./index.adoc[]

[[v13-26-0]]
=== The First of Chronicles, 26
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-26-1]]

^<<v13-26-1,1>>^ The divisions of gatekeepers were as follows: of the Korʹah·ites, Me·shel·e·miʹah the son of Koʹre of the sons of Aʹsaph.

[[v13-26-2]]

^<<v13-26-2,2>>^ And Me·shel·e·miʹah had sons: Zech·a·riʹah the firstborn, Je·diʹa·el the second, Zeb·a·diʹah the third, Jathʹni·el the fourth,

[[v13-26-3]]

^<<v13-26-3,3>>^ Eʹlam the fifth, Je·ho·haʹnan the sixth, Elʹie·ho-eʹnai the seventh.

[[v13-26-4]]

^<<v13-26-4,4>>^ And Oʹbed-eʹdom had sons: She·maiʹah the firstborn, Je·hozʹa·bad the second, Joʹah the third, Saʹcar the fourth, Ne·thanʹel the fifth,

[[v13-26-5]]

^<<v13-26-5,5>>^ Amʹmi·el the sixth, Isʹsa·char the seventh, and Pe·ulʹle·thai the eighth; for God had blessed him.

[[v13-26-6]]

^<<v13-26-6,6>>^ And to his son She·maiʹah, there were sons born who were rulers of their paternal house, for they were mighty, capable men.

[[v13-26-7]]

^<<v13-26-7,7>>^ The sons of She·maiʹah: Othʹni, Rephʹa·el, Oʹbed, and El·zaʹbad; and his brothers E·liʹhu and Sem·a·chiʹah were also capable men.

[[v13-26-8]]

^<<v13-26-8,8>>^ All of these were of the sons of Oʹbed-eʹdom; they and their sons and their brothers were capable men and qualified for the service, 62 belonging to Oʹbed-eʹdom.

[[v13-26-9]]

^<<v13-26-9,9>>^ And Me·shel·e·miʹah had sons and brothers, 18 capable men.

[[v13-26-10]]

^<<v13-26-10,10>>^ And Hoʹsah of the sons of Me·rarʹi had sons. Shimʹri was the head, for although he was not the firstborn, his father appointed him as head,

[[v13-26-11]]

^<<v13-26-11,11>>^ Hil·kiʹah the second, Teb·a·liʹah the third, Zech·a·riʹah the fourth. All the sons and brothers of Hoʹsah were 13.

[[v13-26-12]]

^<<v13-26-12,12>>^ Of these divisions of the gatekeepers, the headmen had duties just as their brothers did, to minister at the house of Jehovah.

[[v13-26-13]]

^<<v13-26-13,13>>^ So they cast lots, the small and the great alike by their paternal houses, for the different gates.

[[v13-26-14]]

^<<v13-26-14,14>>^ Then the lot to the east fell to Shel·e·miʹah. For Zech·a·riʹah his son, a discreet adviser, they cast the lots, and his lot came out to the north.

[[v13-26-15]]

^<<v13-26-15,15>>^ Oʹbed-eʹdom had his to the south, and his sons were assigned the storehouses.

[[v13-26-16]]

^<<v13-26-16,16>>^ Shupʹpim and Hoʹsah had theirs to the west, near the Shalʹlech·eth Gate by the highway that goes up, guard group corresponding to guard group;

[[v13-26-17]]

^<<v13-26-17,17>>^ there were six Levites to the east; to the north, four each day and to the south, four each day; and for the storehouses, two by two;

[[v13-26-18]]

^<<v13-26-18,18>>^ for the portico to the west, there were four at the highway and two at the portico.

[[v13-26-19]]

^<<v13-26-19,19>>^ These were the divisions of the gatekeepers from the sons of the Korʹah·ites and of the Me·rarʹites.

[[v13-26-20]]

^<<v13-26-20,20>>^ As regards the Levites, A·hiʹjah was in charge of the treasuries of the house of the true God and the treasuries of the things made holy.^&#42;1^

[NOTE]
====
. Or “the things dedicated.”
====

[[v13-26-21]]

^<<v13-26-21,21>>^ The sons of Laʹdan: the sons of the Gerʹshon·ite belonging to Laʹdan, the heads of the paternal houses belonging to Laʹdan the Gerʹshon·ite, Je·hiʹe·li

[[v13-26-22]]

^<<v13-26-22,22>>^ and the sons of Je·hiʹe·li, Zeʹtham and his brother Joel. They were in charge of the treasuries of the house of Jehovah.

[[v13-26-23]]

^<<v13-26-23,23>>^ From the Amʹram·ites, the Izʹhar·ites, the Hebʹron·ites, and the Uz·ziʹel·ites,

[[v13-26-24]]

^<<v13-26-24,24>>^ Shebʹu·el son of Gerʹshom son of Moses was a leader in charge of the storehouses.

[[v13-26-25]]

^<<v13-26-25,25>>^ As regards his brothers, of E·li·eʹzer, there was Re·ha·biʹah his son, Je·shaʹiah his son, Joʹram his son, Zichʹri his son, and She·loʹmoth his son.

[[v13-26-26]]

^<<v13-26-26,26>>^ This She·loʹmoth and his brothers were in charge of all the treasuries of the things made holy, which King David, the heads of the paternal houses, the chiefs of the thousands and of the hundreds, and the chiefs of the army had made holy.

[[v13-26-27]]

^<<v13-26-27,27>>^ From the wars and from the spoil, they had made things holy to maintain the house of Jehovah;

[[v13-26-28]]

^<<v13-26-28,28>>^ also, all that Samuel the seer, Saul the son of Kish, Abʹner the son of Ner, and Joʹab the son of Ze·ruʹiah had made holy. Whatever anyone made holy was put in the care of She·loʹmith and his brothers.

[[v13-26-29]]

^<<v13-26-29,29>>^ Of the Izʹhar·ites, Chen·a·niʹah and his sons were assigned outside administrative duties as officers and as judges over Israel.

[[v13-26-30]]

^<<v13-26-30,30>>^ Of the Hebʹron·ites, Hash·a·biʹah and his brothers, 1,700 capable men, were over the administration of Israel in the region west of the Jordan for all the work of Jehovah and for the king’s service.

[[v13-26-31]]

^<<v13-26-31,31>>^ Of the Hebʹron·ites, Je·riʹjah was the head of the Hebʹron·ites by line of descent of their paternal house. In the 40th year of David’s kingship, they were sought out, and mighty, capable men were found among them in Jaʹzer in Gilʹe·ad.

[[v13-26-32]]

^<<v13-26-32,32>>^ And his brothers numbered 2,700 capable men, heads of the paternal houses. So King David assigned them over the Reuʹben·ites, the Gadʹites, and the half tribe of the Ma·nasʹsites, for every matter of the true God and matter of the king.

'''

xref:013-1-chronicles/013-1-chronicles-025.adoc#v13-25-0[&#60; Capítulo Anterior] | <<v13-26-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-027.adoc#v13-27-0[Próximo Capítulo &#62;]