include::./index.adoc[]

[[v13-28-0]]
=== The First of Chronicles, 28
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-28-1]]

^<<v13-28-1,1>>^ David then congregated all the princes of Israel to Jerusalem: the princes of the tribes, the chiefs of the divisions ministering to the king, the chiefs of thousands and the chiefs of hundreds, the chiefs of all the property and livestock of the king and of his sons, together with the court officials and every mighty and capable man.

[[v13-28-2]]

^<<v13-28-2,2>>^ Then King David rose to his feet and said:
“Hear me, my brothers and my people. It was my heart’s desire to build a house as the resting-place for the ark of the covenant of Jehovah and as the footstool of our God, and I made preparations to build.

[[v13-28-3]]

^<<v13-28-3,3>>^ But the true God told me, ‘You will not build a house for my name, for you are a man of wars, and you have shed blood.’

[[v13-28-4]]

^<<v13-28-4,4>>^ However, Jehovah the God of Israel chose me out of all the house of my father to become king over Israel forever, for he chose Judah as leader and of the house of Judah, my father’s house, and of my father’s sons, I was the one whom he approved, to make me king over all Israel.

[[v13-28-5]]

^<<v13-28-5,5>>^ And of all my sons—for Jehovah has given me many sons—he chose my son Solʹo·mon to sit on the throne of the kingship of Jehovah over Israel.

[[v13-28-6]]

^<<v13-28-6,6>>^ “He said to me, ‘Your son Solʹo·mon is the one who will build my house and my courtyards, for I have chosen him as my son and I will become his father.

[[v13-28-7]]

^<<v13-28-7,7>>^ I will firmly establish his kingship forever if he resolutely observes my commandments and my judicial decisions, as he is now doing.’

[[v13-28-8]]

^<<v13-28-8,8>>^ So I say before the eyes of all Israel, Jehovah’s congregation, and in the ears of our God: Carefully observe and search for all the commandments of Jehovah your God, so that you may possess the good land and pass it on as a permanent inheritance to your sons after you.

[[v13-28-9]]

^<<v13-28-9,9>>^ “And you, Solʹo·mon my son, know the God of your father and serve him with a complete^&#42;1^ heart and with a delightful^&#42;2^ soul,^&#42;3^ for Jehovah searches through all hearts, and he discerns every inclination of the thoughts. If you search for him, he will let himself be found by you, but if you leave him, he will reject you forever.

[NOTE]
====
. Or “completely devoted.”
. Or “willing.”
. See Glossary.
====

[[v13-28-10]]

^<<v13-28-10,10>>^ See, now, for Jehovah has chosen you to build a house as a sanctuary. Be courageous and go to work.”

[[v13-28-11]]

^<<v13-28-11,11>>^ David then gave to his son Solʹo·mon the architectural plan of the porch and of its houses, its storerooms, its roof chambers, its inner rooms, and the house of the propitiatory cover.^&#42;1^

[NOTE]
====
. Or “house of the atonement.”
====

[[v13-28-12]]

^<<v13-28-12,12>>^ He gave him the architectural plan of everything that had been conveyed to him through inspiration^&#42;1^ for the courtyards of Jehovah’s house, for all the dining rooms around it, for the treasuries of the house of the true God, and for the treasuries of the things made holy;^&#42;2^

[NOTE]
====
. Lit., “by the spirit.”
. Or “things dedicated.”
====

[[v13-28-13]]

^<<v13-28-13,13>>^ also for the divisions of the priests and of the Levites, for all the duties of the service of Jehovah’s house, and for all the utensils of the service of Jehovah’s house;

[[v13-28-14]]

^<<v13-28-14,14>>^ also for the weight of the gold, the gold for all the utensils for the different services, the weight of all the utensils of silver, and for all the utensils for the different services;

[[v13-28-15]]

^<<v13-28-15,15>>^ also the weight for the gold lampstands and their gold lamps, the weight of the different lampstands and their lamps, and the weight of the silver lampstands, for each lampstand and its lamps according to its use;

[[v13-28-16]]

^<<v13-28-16,16>>^ also the weight of the gold for the tables of the layer bread,^&#42;1^ for each table, as well as the silver for the tables of silver,

[NOTE]
====
. That is, the showbread.
====

[[v13-28-17]]

^<<v13-28-17,17>>^ for the forks, the bowls, the pitchers of pure gold, and the weight of the small gold bowls, for each small bowl, and the weight of the small silver bowls, for each small bowl.

[[v13-28-18]]

^<<v13-28-18,18>>^ He also gave the weight for the refined gold for the incense altar and for the representation of the chariot, namely, the cherubs of gold that spread their wings out and overshadow the ark of the covenant of Jehovah.

[[v13-28-19]]

^<<v13-28-19,19>>^ David said: “The hand of Jehovah was upon me, and he gave me insight to put all the details of the architectural plan in writing.”

[[v13-28-20]]

^<<v13-28-20,20>>^ Then David said to his son Solʹo·mon: “Be courageous and strong and go to work. Do not be afraid or be terrified, for Jehovah God, my God, is with you. He will not desert you or abandon you, but he will be with you until all the work for the service of Jehovah’s house is finished.

[[v13-28-21]]

^<<v13-28-21,21>>^ And here are the divisions of the priests and of the Levites for all the service of the house of the true God. You have willing, skilled workers to perform every kind of service, as well as the princes and all the people who will carry out all your instructions.”

'''

xref:013-1-chronicles/013-1-chronicles-027.adoc#v13-27-0[&#60; Capítulo Anterior] | <<v13-28-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-029.adoc#v13-29-0[Próximo Capítulo &#62;]