include::./index.adoc[]

[[v13-27-0]]
=== The First of Chronicles, 27
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-27-1]]

^<<v13-27-1,1>>^ This is the number of Israelites, the heads of the paternal houses, the chiefs of the thousands and of the hundreds, and their officers who ministered to the king in every matter of the divisions that would come in and go out month by month during all the months of the year; there were 24,000 in each division.

[[v13-27-2]]

^<<v13-27-2,2>>^ Over the first division of the first month was Ja·shoʹbe·am the son of Zabʹdi·el, and 24,000 were in his division.

[[v13-27-3]]

^<<v13-27-3,3>>^ Of the sons of Peʹrez, he was the head of all the chiefs of the groups assigned to serve during the first month.

[[v13-27-4]]

^<<v13-27-4,4>>^ Over the division of the second month was Doʹdai the A·hoʹhite with his division, and Mikʹloth was the leader, and 24,000 were in his division.

[[v13-27-5]]

^<<v13-27-5,5>>^ The chief of the third group assigned to serve during the third month was Be·naiʹah the son of Je·hoiʹa·da the chief priest, and 24,000 were in his division.

[[v13-27-6]]

^<<v13-27-6,6>>^ This Be·naiʹah was a mighty warrior of the thirty and in charge of the thirty, and over his division was his son Am·mizʹa·bad.

[[v13-27-7]]

^<<v13-27-7,7>>^ The fourth for the fourth month was Asʹa·hel, Joʹab’s brother, and his son Zeb·a·diʹah after him, and 24,000 were in his division.

[[v13-27-8]]

^<<v13-27-8,8>>^ The fifth chief for the fifth month was Shamʹhuth the Izʹrah·ite, and 24,000 were in his division.

[[v13-27-9]]

^<<v13-27-9,9>>^ The sixth for the sixth month was Iʹra the son of Ikʹkesh the Te·koʹite, and 24,000 were in his division.

[[v13-27-10]]

^<<v13-27-10,10>>^ The seventh for the seventh month was Heʹlez the Pelʹo·nite of the Eʹphra·im·ites, and 24,000 were in his division.

[[v13-27-11]]

^<<v13-27-11,11>>^ The eighth for the eighth month was Sibʹbe·cai the Huʹshath·ite of the Zeʹrah·ites, and 24,000 were in his division.

[[v13-27-12]]

^<<v13-27-12,12>>^ The ninth for the ninth month was Abi-eʹzer the Anʹa·thoth·ite of the Benʹja·min·ites, and 24,000 were in his division.

[[v13-27-13]]

^<<v13-27-13,13>>^ The tenth for the tenth month was Maʹha·rai the Ne·tophʹa·thite of the Zeʹrah·ites, and 24,000 were in his division.

[[v13-27-14]]

^<<v13-27-14,14>>^ The 11th for the 11th month was Be·naiʹah the Pirʹa·thon·ite of the sons of Eʹphra·im, and 24,000 were in his division.

[[v13-27-15]]

^<<v13-27-15,15>>^ The 12th for the 12th month was Helʹdai the Ne·tophʹa·thite, of Othʹni·el, and 24,000 were in his division.

[[v13-27-16]]

^<<v13-27-16,16>>^ These were the leaders of the tribes of Israel: Of the Reuʹben·ites, E·li·eʹzer the son of Zichʹri was leader; of the Simʹe·on·ites, Sheph·a·tiʹah the son of Maʹa·cah;

[[v13-27-17]]

^<<v13-27-17,17>>^ of Leʹvi, Hash·a·biʹah the son of Kem·uʹel; of Aaron, Zaʹdok;

[[v13-27-18]]

^<<v13-27-18,18>>^ of Judah, E·liʹhu, one of David’s brothers; of Isʹsa·char, Omʹri the son of Miʹcha·el;

[[v13-27-19]]

^<<v13-27-19,19>>^ of Zebʹu·lun, Ish·maʹiah the son of O·ba·diʹah; of Naphʹta·li, Jerʹi·moth the son of Azʹri·el;

[[v13-27-20]]

^<<v13-27-20,20>>^ of the Eʹphra·im·ites, Ho·sheʹa the son of Az·a·ziʹah; of the half tribe of Ma·nasʹseh, Joel the son of Pe·daiʹah;

[[v13-27-21]]

^<<v13-27-21,21>>^ of the half tribe of Ma·nasʹseh in Gilʹe·ad, Idʹdo the son of Zech·a·riʹah; of Benjamin, Ja·a·siʹel the son of Abʹner;

[[v13-27-22]]

^<<v13-27-22,22>>^ of Dan, Azʹar·el the son of Je·roʹham. These were the princes of the tribes of Israel.

[[v13-27-23]]

^<<v13-27-23,23>>^ David did not count those 20 years of age and under, because Jehovah had promised to make Israel as many as the stars of the heavens.

[[v13-27-24]]

^<<v13-27-24,24>>^ Joʹab the son of Ze·ruʹiah had started to take the count, but he did not finish; and God’s anger came against Israel^&#42;1^ because of this, and the number was not entered into the account of the history of the times of King David.

[NOTE]
====
. Lit., “and anger was on Israel.”
====

[[v13-27-25]]

^<<v13-27-25,25>>^ Over the treasuries of the king was Azʹma·veth the son of Adʹi·el. Jonʹa·than the son of Uz·ziʹah was over the storehouses^&#42;1^ in the fields, in the cities, in the villages, and in the towers.

[NOTE]
====
. Or “treasuries.”
====

[[v13-27-26]]

^<<v13-27-26,26>>^ Over the field workers who cultivated the soil was Ezʹri the son of Cheʹlub.

[[v13-27-27]]

^<<v13-27-27,27>>^ Shimʹe·i the Raʹmath·ite was over the vineyards; over the produce of the vineyards for the wine supplies was Zabʹdi the Shiphʹmite.

[[v13-27-28]]

^<<v13-27-28,28>>^ Over the olive groves and the sycamore trees in the She·pheʹlah was Baʹal-haʹnan the Ge·deʹrite; over the oil supplies was Joʹash.

[[v13-27-29]]

^<<v13-27-29,29>>^ Over the herds that grazed in Sharʹon was Shitʹrai the Sharʹon·ite, and Shaʹphat the son of Adʹlai was over the herds in the valley plains.^&#42;1^

[NOTE]
====
. Or “low plains.”
====

[[v13-27-30]]

^<<v13-27-30,30>>^ Over the camels was Oʹbil the Ishʹma·el·ite; over the donkeys^&#42;1^ was Jeh·deʹiah the Me·ronʹo·thite.

[NOTE]
====
. Lit., “female donkeys.”
====

[[v13-27-31]]

^<<v13-27-31,31>>^ Over the flocks was Jaʹziz the Hagʹrite. All of these were the chiefs of King David’s property.

[[v13-27-32]]

^<<v13-27-32,32>>^ Jonʹa·than, David’s nephew, was an adviser, a man of understanding and a secretary, and Je·hiʹel the son of Hachʹmo·ni looked after the king’s sons.

[[v13-27-33]]

^<<v13-27-33,33>>^ A·hithʹo·phel was an adviser to the king, and Huʹshai the Arʹchite was the king’s friend.^&#42;1^

[NOTE]
====
. Or “confidant.”
====

[[v13-27-34]]

^<<v13-27-34,34>>^ After A·hithʹo·phel there were Je·hoiʹa·da the son of Be·naiʹah and A·biʹa·thar; and Joʹab was chief of the king’s army.

'''

xref:013-1-chronicles/013-1-chronicles-026.adoc#v13-26-0[&#60; Capítulo Anterior] | <<v13-27-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-028.adoc#v13-28-0[Próximo Capítulo &#62;]