include::./index.adoc[]

[[v13-25-0]]
=== The First of Chronicles, 25
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-25-1]]

^<<v13-25-1,1>>^ Further, David and the chiefs of the groups for the service separated some of the sons of Aʹsaph, Heʹman, and Je·duʹthun to serve by prophesying with the harps, the stringed instruments, and the cymbals. The list of the official men for this service was,

[[v13-25-2]]

^<<v13-25-2,2>>^ of the sons of Aʹsaph: Zacʹcur, Joseph, Neth·a·niʹah, and Ash·a·reʹlah, the sons of Aʹsaph under the direction of Aʹsaph, who prophesied under the direction of the king.

[[v13-25-3]]

^<<v13-25-3,3>>^ Of Je·duʹthun, the sons of Je·duʹthun: Ged·a·liʹah, Zeʹri, Je·shaʹiah, Shimʹe·i, Hash·a·biʹah, and Mat·ti·thiʹah, six, under the direction of their father Je·duʹthun, who prophesied with the harp, thanking and praising Jehovah.

[[v13-25-4]]

^<<v13-25-4,4>>^ Of Heʹman, the sons of Heʹman: Buk·kiʹah, Mat·ta·niʹah, Uzʹzi·el, Shebʹu·el, Jerʹi·moth, Han·a·niʹah, Ha·naʹni, E·liʹa·thah, Gid·dalʹti, Ro·mamʹti-eʹzer, Josh·be·kashʹah, Mal·loʹthi, Hoʹthir, and Ma·haʹzi·oth.

[[v13-25-5]]

^<<v13-25-5,5>>^ All of these were sons of Heʹman, a visionary of the king in matters pertaining to the true God to his glory;^&#42;1^ thus the true God gave Heʹman 14 sons and 3 daughters.

[NOTE]
====
. Lit., “to raise up his horn.”
====

[[v13-25-6]]

^<<v13-25-6,6>>^ All of these were under the direction of their father for singing at the house of Jehovah, with cymbals, stringed instruments, and harps for the service of the house of the true God.
Under the king’s direction were Aʹsaph, Je·duʹthun, and Heʹman.

[[v13-25-7]]

^<<v13-25-7,7>>^ The number of them and their brothers who were trained in song to Jehovah, all experts, was 288.

[[v13-25-8]]

^<<v13-25-8,8>>^ So they cast lots for their duties, the small and the great alike, the expert along with the learner.

[[v13-25-9]]

^<<v13-25-9,9>>^ The first lot to come out belonged to Aʹsaph for Joseph, the second for Ged·a·liʹah (he and his brothers and his sons were 12);

[[v13-25-10]]

^<<v13-25-10,10>>^ the third for Zacʹcur, his sons and his brothers, 12;

[[v13-25-11]]

^<<v13-25-11,11>>^ the fourth for Izʹri, his sons and his brothers, 12;

[[v13-25-12]]

^<<v13-25-12,12>>^ the fifth for Neth·a·niʹah, his sons and his brothers, 12;

[[v13-25-13]]

^<<v13-25-13,13>>^ the sixth for Buk·kiʹah, his sons and his brothers, 12;

[[v13-25-14]]

^<<v13-25-14,14>>^ the seventh for Jesh·a·reʹlah, his sons and his brothers, 12;

[[v13-25-15]]

^<<v13-25-15,15>>^ the eighth for Je·shaʹiah, his sons and his brothers, 12;

[[v13-25-16]]

^<<v13-25-16,16>>^ the ninth for Mat·ta·niʹah, his sons and his brothers, 12;

[[v13-25-17]]

^<<v13-25-17,17>>^ the tenth for Shimʹe·i, his sons and his brothers, 12;

[[v13-25-18]]

^<<v13-25-18,18>>^ the 11th for Azʹar·el, his sons and his brothers, 12;

[[v13-25-19]]

^<<v13-25-19,19>>^ the 12th for Hash·a·biʹah, his sons and his brothers, 12;

[[v13-25-20]]

^<<v13-25-20,20>>^ for the 13th, Shuʹba·el, his sons and his brothers, 12;

[[v13-25-21]]

^<<v13-25-21,21>>^ for the 14th, Mat·ti·thiʹah, his sons and his brothers, 12;

[[v13-25-22]]

^<<v13-25-22,22>>^ for the 15th, for Jerʹe·moth, his sons and his brothers, 12;

[[v13-25-23]]

^<<v13-25-23,23>>^ for the 16th, for Han·a·niʹah, his sons and his brothers, 12;

[[v13-25-24]]

^<<v13-25-24,24>>^ for the 17th, for Josh·be·kashʹah, his sons and his brothers, 12;

[[v13-25-25]]

^<<v13-25-25,25>>^ for the 18th, for Ha·naʹni, his sons and his brothers, 12;

[[v13-25-26]]

^<<v13-25-26,26>>^ for the 19th, for Mal·loʹthi, his sons and his brothers, 12;

[[v13-25-27]]

^<<v13-25-27,27>>^ for the 20th, for E·liʹa·thah, his sons and his brothers, 12;

[[v13-25-28]]

^<<v13-25-28,28>>^ for the 21st, for Hoʹthir, his sons and his brothers, 12;

[[v13-25-29]]

^<<v13-25-29,29>>^ for the 22nd, for Gid·dalʹti, his sons and his brothers, 12;

[[v13-25-30]]

^<<v13-25-30,30>>^ for the 23rd, for Ma·haʹzi·oth, his sons and his brothers, 12;

[[v13-25-31]]

^<<v13-25-31,31>>^ for the 24th, for Ro·mamʹti-eʹzer, his sons and his brothers, 12.

'''

xref:013-1-chronicles/013-1-chronicles-024.adoc#v13-24-0[&#60; Capítulo Anterior] | <<v13-25-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-026.adoc#v13-26-0[Próximo Capítulo &#62;]