include::./index.adoc[]

[[v13-19-0]]
=== The First of Chronicles, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-19-1]]

^<<v13-19-1,1>>^ Later Naʹhash the king of the Amʹmon·ites died, and his son became king in his place.

[[v13-19-2]]

^<<v13-19-2,2>>^ At that David said: “I will show loyal love toward Haʹnun the son of Naʹhash, because his father showed loyal love toward me.” So David sent messengers to offer him comfort over the loss of his father. But when David’s servants came into the land of the Amʹmon·ites to comfort Haʹnun,

[[v13-19-3]]

^<<v13-19-3,3>>^ the princes of the Amʹmon·ites said to Haʹnun: “Do you think that David is honoring your father by sending comforters to you? Is it not to make a thorough search and to overthrow you and to spy out the land that his servants have come to you?”

[[v13-19-4]]

^<<v13-19-4,4>>^ So Haʹnun took the servants of David and shaved them and cut their garments in half at their buttocks and sent them away.

[[v13-19-5]]

^<<v13-19-5,5>>^ When David was told about the men, he at once sent others to meet them, because the men had been deeply humiliated; and the king told them: “Stay in Jerʹi·cho until your beards grow back, and then return.”

[[v13-19-6]]

^<<v13-19-6,6>>^ In time the Amʹmon·ites saw that they had become a stench to David, so Haʹnun and the Amʹmon·ites sent 1,000 silver talents^&#42;1^ to hire chariots and horsemen from Mes·o·po·taʹmi·a,^&#42;2^ Aʹram-maʹa·cah, and Zoʹbah.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
. Lit., “Aram-naharaim.”
====

[[v13-19-7]]

^<<v13-19-7,7>>^ Thus they hired 32,000 chariots, along with the king of Maʹa·cah and his people. Then they came and camped before Medʹe·ba. The Amʹmon·ites gathered together from their cities and came out for the battle.

[[v13-19-8]]

^<<v13-19-8,8>>^ When David heard about it, he sent Joʹab and the entire army, including his mightiest warriors.

[[v13-19-9]]

^<<v13-19-9,9>>^ And the Amʹmon·ites went out and drew up in battle formation at the entrance of the city while the kings who had come were by themselves in the open field.

[[v13-19-10]]

^<<v13-19-10,10>>^ When Joʹab saw that the battle charges were coming against him from the front and the rear, he chose some of the best troops in Israel and drew them up in battle formation to meet the Syrians.

[[v13-19-11]]

^<<v13-19-11,11>>^ He put the rest of the men under the command^&#42;1^ of his brother A·bishʹai, in order to draw them up in battle formation to meet the Amʹmon·ites.

[NOTE]
====
. Lit., “in the hand.”
====

[[v13-19-12]]

^<<v13-19-12,12>>^ Then he said: “If the Syrians become too strong for me, then you must come to my rescue; but if the Amʹmon·ites become too strong for you, I will rescue you.

[[v13-19-13]]

^<<v13-19-13,13>>^ We must be strong and courageous for our people and for the cities of our God, and Jehovah will do what is good in his eyes.”

[[v13-19-14]]

^<<v13-19-14,14>>^ Then Joʹab and his men advanced to meet the Syrians in battle, and they fled from before him.

[[v13-19-15]]

^<<v13-19-15,15>>^ When the Amʹmon·ites saw that the Syrians had fled, they also fled from his brother A·bishʹai and went into the city. After that Joʹab came to Jerusalem.

[[v13-19-16]]

^<<v13-19-16,16>>^ When the Syrians saw that they had been defeated by Israel, they sent messengers to summon the Syrians in the region of the River,^&#42;1^ with Shoʹphach the chief of the army of Had·ad·eʹzer leading them.

[NOTE]
====
. That is, the Euphrates.
====

[[v13-19-17]]

^<<v13-19-17,17>>^ When the report was made to David, he immediately gathered all Israel and crossed the Jordan and came to them and drew up in battle formation against them. David drew up in battle formation to meet the Syrians, and they fought against him.

[[v13-19-18]]

^<<v13-19-18,18>>^ But the Syrians fled from Israel; and David killed 7,000 charioteers and 40,000 foot soldiers of the Syrians, and he put Shoʹphach the chief of the army to death.

[[v13-19-19]]

^<<v13-19-19,19>>^ When the servants of Had·ad·eʹzer saw that they had been defeated by Israel, they promptly made peace with David and became his subjects; and Syria did not want to help the Amʹmon·ites anymore.

'''

xref:013-1-chronicles/013-1-chronicles-018.adoc#v13-18-0[&#60; Capítulo Anterior] | <<v13-19-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-020.adoc#v13-20-0[Próximo Capítulo &#62;]