include::./index.adoc[]

[[v13-2-0]]
=== The First of Chronicles, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-2-1]]

^<<v13-2-1,1>>^ These were the sons of Israel: Reuʹben, Simʹe·on, Leʹvi, Judah, Isʹsa·char, Zebʹu·lun,

[[v13-2-2]]

^<<v13-2-2,2>>^ Dan, Joseph, Benjamin, Naphʹta·li, Gad, and Ashʹer.

[[v13-2-3]]

^<<v13-2-3,3>>^ The sons of Judah were Er, Oʹnan, and Sheʹlah. These three were born to him from Shuʹa’s daughter, the Caʹnaan·it·ess. But Er, Judah’s firstborn, was displeasing to Jehovah, so He put him to death.

[[v13-2-4]]

^<<v13-2-4,4>>^ Taʹmar, Judah’s daughter-in-law, bore to him Peʹrez and Zeʹrah. Judah had five sons in all.

[[v13-2-5]]

^<<v13-2-5,5>>^ The sons of Peʹrez were Hezʹron and Haʹmul.

[[v13-2-6]]

^<<v13-2-6,6>>^ The sons of Zeʹrah were Zimʹri, Eʹthan, Heʹman, Calʹcol, and Daʹra. There were five of them in all.

[[v13-2-7]]

^<<v13-2-7,7>>^ The son^&#42;1^ of Carʹmi was Aʹchar,^&#42;2^ who brought disaster^&#42;3^ on Israel, who was unfaithful with regard to what had been devoted to destruction.

[NOTE]
====
. Lit., “sons.”
. Meaning “Bringer of Disaster; Bringer of Ostracism.” In Jos 7:1, also called Achan.
. Or “trouble; ostracism.”
====

[[v13-2-8]]

^<<v13-2-8,8>>^ The son^&#42;1^ of Eʹthan was Az·a·riʹah.

[NOTE]
====
. Lit., “sons.”
====

[[v13-2-9]]

^<<v13-2-9,9>>^ The sons of Hezʹron who were born to him were Je·rahʹme·el, Ram, and Che·luʹbai.^&#42;1^

[NOTE]
====
. Also called Caleb in vss. 18, 19, 42.
====

[[v13-2-10]]

^<<v13-2-10,10>>^ Ram became father to Am·minʹa·dab. Am·minʹa·dab became father to Nahʹshon the chieftain of the descendants of Judah.

[[v13-2-11]]

^<<v13-2-11,11>>^ Nahʹshon became father to Salʹma. Salʹma became father to Boʹaz.

[[v13-2-12]]

^<<v13-2-12,12>>^ Boʹaz became father to Oʹbed. Oʹbed became father to Jesʹse.

[[v13-2-13]]

^<<v13-2-13,13>>^ Jesʹse became father to his firstborn E·liʹab, A·binʹa·dab the second, Shimʹe·a the third,

[[v13-2-14]]

^<<v13-2-14,14>>^ Ne·thanʹel the fourth, Radʹdai the fifth,

[[v13-2-15]]

^<<v13-2-15,15>>^ Oʹzem the sixth, and David the seventh.

[[v13-2-16]]

^<<v13-2-16,16>>^ Their sisters were Ze·ruʹiah and Abʹi·gail. The sons of Ze·ruʹiah were A·bishʹai, Joʹab, and Asʹa·hel, three.

[[v13-2-17]]

^<<v13-2-17,17>>^ Abʹi·gail gave birth to A·maʹsa, and the father of A·maʹsa was Jeʹther the Ishʹma·el·ite.

[[v13-2-18]]

^<<v13-2-18,18>>^ Caʹleb^&#42;1^ the son of Hezʹron became father to sons by his wife A·zuʹbah and by Jerʹi·oth; and these were her sons: Jeʹsher, Shoʹbab, and Arʹdon.

[NOTE]
====
. Also called Chelubai in vs. 9.
====

[[v13-2-19]]

^<<v13-2-19,19>>^ When A·zuʹbah died, Caʹleb married Ephʹrath, and she bore Hur to him.

[[v13-2-20]]

^<<v13-2-20,20>>^ Hur became father to Uʹri. Uʹri became father to Bezʹal·el.

[[v13-2-21]]

^<<v13-2-21,21>>^ Afterward Hezʹron had relations with the daughter of Maʹchir the father of Gilʹe·ad. He married her when he was 60 years old, and she bore Seʹgub to him.

[[v13-2-22]]

^<<v13-2-22,22>>^ Seʹgub became father to Jaʹir, who had 23 cities in the land of Gilʹe·ad.

[[v13-2-23]]

^<<v13-2-23,23>>^ Later Geshʹur and Syria took Havʹvoth-jaʹir from them, along with Keʹnath and its dependent^&#42;1^ towns, 60 cities. All of these were the descendants of Maʹchir the father of Gilʹe·ad.

[NOTE]
====
. Or “surrounding.”
====

[[v13-2-24]]

^<<v13-2-24,24>>^ After the death of Hezʹron in Caʹleb-ephʹra·thah, A·biʹjah the wife of Hezʹron bore him Ashʹhur the father of Te·koʹa.

[[v13-2-25]]

^<<v13-2-25,25>>^ The sons of Je·rahʹme·el the firstborn of Hezʹron were Ram the firstborn, Buʹnah, Oʹren, Oʹzem, and A·hiʹjah.

[[v13-2-26]]

^<<v13-2-26,26>>^ Je·rahʹme·el had another wife, whose name was Atʹa·rah. She was the mother of Oʹnam.

[[v13-2-27]]

^<<v13-2-27,27>>^ The sons of Ram the firstborn of Je·rahʹme·el were Maʹaz, Jaʹmin, and Eʹker.

[[v13-2-28]]

^<<v13-2-28,28>>^ The sons of Oʹnam were Shamʹmai and Jaʹda. The sons of Shamʹmai were Naʹdab and A·biʹshur.

[[v13-2-29]]

^<<v13-2-29,29>>^ The name of A·biʹshur’s wife was Abʹi·ha·il, who bore him Ahʹban and Moʹlid.

[[v13-2-30]]

^<<v13-2-30,30>>^ The sons of Naʹdab were Seʹled and Apʹpa·im. But Seʹled died without sons.

[[v13-2-31]]

^<<v13-2-31,31>>^ The son^&#42;1^ of Apʹpa·im was Ishʹi. And the son^&#42;2^ of Ishʹi was Sheʹshan, and the son^&#42;3^ of Sheʹshan, Ahʹlai.

[NOTE]
====
. Lit., “sons.”
. Lit., “sons.”
. Lit., “sons.”
====

[[v13-2-32]]

^<<v13-2-32,32>>^ The sons of Jaʹda the brother of Shamʹmai were Jeʹther and Jonʹa·than. But Jeʹther died without sons.

[[v13-2-33]]

^<<v13-2-33,33>>^ The sons of Jonʹa·than were Peʹleth and Zaʹza. These were the descendants of Je·rahʹme·el.

[[v13-2-34]]

^<<v13-2-34,34>>^ Sheʹshan had no sons, only daughters. Now Sheʹshan had an Egyptian servant whose name was Jarʹha.

[[v13-2-35]]

^<<v13-2-35,35>>^ Sheʹshan gave his daughter to be the wife of his servant Jarʹha, and she bore him Atʹtai.

[[v13-2-36]]

^<<v13-2-36,36>>^ Atʹtai became father to Nathan. Nathan became father to Zaʹbad.

[[v13-2-37]]

^<<v13-2-37,37>>^ Zaʹbad became father to Ephʹlal. Ephʹlal became father to Oʹbed.

[[v13-2-38]]

^<<v13-2-38,38>>^ Oʹbed became father to Jeʹhu. Jeʹhu became father to Az·a·riʹah.

[[v13-2-39]]

^<<v13-2-39,39>>^ Az·a·riʹah became father to Heʹlez. Heʹlez became father to El·e·aʹsah.

[[v13-2-40]]

^<<v13-2-40,40>>^ El·e·aʹsah became father to Sisʹmai. Sisʹmai became father to Shalʹlum.

[[v13-2-41]]

^<<v13-2-41,41>>^ Shalʹlum became father to Jek·a·miʹah. Jek·a·miʹah became father to E·lishʹa·ma.

[[v13-2-42]]

^<<v13-2-42,42>>^ The sons of Caʹleb^&#42;1^ the brother of Je·rahʹme·el were Meʹsha his firstborn, who was the father of Ziph, and the sons of Ma·reʹshah the father of Hebʹron.

[NOTE]
====
. Also called Chelubai in vs. 9.
====

[[v13-2-43]]

^<<v13-2-43,43>>^ The sons of Hebʹron were Korʹah, Tapʹpu·ah, Reʹkem, and Sheʹma.

[[v13-2-44]]

^<<v13-2-44,44>>^ Sheʹma became father to Raʹham the father of Jorʹke·am. Reʹkem became father to Shamʹmai.

[[v13-2-45]]

^<<v13-2-45,45>>^ The son of Shamʹmai was Maʹon. Maʹon was the father of Beth-zur.

[[v13-2-46]]

^<<v13-2-46,46>>^ Caʹleb’s concubine Eʹphah gave birth to Haʹran, Moʹza, and Gaʹzez. Haʹran became father to Gaʹzez.

[[v13-2-47]]

^<<v13-2-47,47>>^ The sons of Jahʹdai were Reʹgem, Joʹtham, Geʹshan, Pelʹet, Eʹphah, and Shaʹaph.

[[v13-2-48]]

^<<v13-2-48,48>>^ Caʹleb’s concubine Maʹa·cah gave birth to Sheʹber and Tirʹha·nah.

[[v13-2-49]]

^<<v13-2-49,49>>^ In time she bore Shaʹaph the father of Mad·manʹnah and Sheʹva the father of Mach·beʹnah and Gibʹe·a. Caʹleb’s daughter was Achʹsah.

[[v13-2-50]]

^<<v13-2-50,50>>^ These were the descendants of Caʹleb.
The sons of Hur the firstborn of Ephʹra·thah were Shoʹbal the father of Kirʹi·ath-jeʹa·rim,

[[v13-2-51]]

^<<v13-2-51,51>>^ Salʹma the father of Bethʹle·hem, and Haʹreph the father of Beth-gaʹder.

[[v13-2-52]]

^<<v13-2-52,52>>^ Shoʹbal the father of Kirʹi·ath-jeʹa·rim had sons: Ha·roʹeh and half of the Me·nuʹhoth.

[[v13-2-53]]

^<<v13-2-53,53>>^ The families of Kirʹi·ath-jeʹa·rim were the Ithʹrites, the Puʹthites, the Shuʹmath·ites, and the Mishʹra·ites. It was from these that the Zorʹath·ites and the Eshʹta·ol·ites came.

[[v13-2-54]]

^<<v13-2-54,54>>^ The sons of Salʹma were Bethʹle·hem, the Ne·tophʹa·thites, Atʹroth-beth-joʹab, half of the Man·a·haʹthites, and the Zorʹites.

[[v13-2-55]]

^<<v13-2-55,55>>^ The families of the scribes dwelling at Jaʹbez were the Tiʹrath·ites, the Shimʹe·ath·ites, and the Suʹcath·ites. These were the Kenʹites who came from Hamʹmath the father of the house of Reʹchab.

'''

xref:013-1-chronicles/013-1-chronicles-001.adoc#v13-1-0[&#60; Capítulo Anterior] | <<v13-2-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-003.adoc#v13-3-0[Próximo Capítulo &#62;]