include::./index.adoc[]

[[v13-16-0]]
=== The First of Chronicles, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-16-1]]

^<<v13-16-1,1>>^ So they brought the Ark of the true God in and placed it inside the tent that David had pitched for it; and they presented burnt offerings and communion sacrifices before the true God.

[[v13-16-2]]

^<<v13-16-2,2>>^ When David finished offering up the burnt offerings and the communion sacrifices, he blessed the people in the name of Jehovah.

[[v13-16-3]]

^<<v13-16-3,3>>^ Further, he distributed to all the Israelites, to each man and woman, a round loaf of bread, a date cake, and a raisin cake.

[[v13-16-4]]

^<<v13-16-4,4>>^ Then he appointed some of the Levites to minister before the Ark of Jehovah, to honor,^&#42;1^ thank, and praise Jehovah the God of Israel.

[NOTE]
====
. Lit., “to remember.”
====

[[v13-16-5]]

^<<v13-16-5,5>>^ Aʹsaph was the head, and second to him was Zech·a·riʹah; and Je·iʹel, She·mirʹa·moth, Je·hiʹel, Mat·ti·thiʹah, E·liʹab, Be·naiʹah, Oʹbed-eʹdom, and Je·iʹel played stringed instruments and harps; and Aʹsaph played the cymbals,

[[v13-16-6]]

^<<v13-16-6,6>>^ and Be·naiʹah and Ja·ha·ziʹel the priests blew the trumpets constantly before the ark of the covenant of the true God.

[[v13-16-7]]

^<<v13-16-7,7>>^ It was on that day that David first contributed a song of thanks to Jehovah through Aʹsaph and his brothers:

[[v13-16-8]]

^<<v13-16-8,8>>^ “Give thanks to Jehovah, call on his name,
Make his deeds known among the peoples!

[[v13-16-9]]

^<<v13-16-9,9>>^ Sing to him, sing praises^&#42;1^ to him,
Ponder over^&#42;2^ all his wonderful works.

[NOTE]
====
. Or “make music.”
. Or possibly, “Speak about.”
====

[[v13-16-10]]

^<<v13-16-10,10>>^ Boast about his holy name.
Let the hearts of those seeking Jehovah rejoice.

[[v13-16-11]]

^<<v13-16-11,11>>^ Search for Jehovah and his strength.
Seek his face^&#42;1^ constantly.

[NOTE]
====
. Or “presence.”
====

[[v13-16-12]]

^<<v13-16-12,12>>^ Remember the wonderful works he has performed,
His miracles and the judgments he has pronounced,

[[v13-16-13]]

^<<v13-16-13,13>>^ You offspring^&#42;1^ of Israel his servant,
You sons of Jacob, his chosen ones.

[NOTE]
====
. Or “descendants.” Lit., “seed.”
====

[[v13-16-14]]

^<<v13-16-14,14>>^ He is Jehovah our God.
His judgments are throughout the earth.

[[v13-16-15]]

^<<v13-16-15,15>>^ Remember his covenant forever,
The promise he made,^&#42;1^ to a thousand generations,

[NOTE]
====
. Lit., “The word he commanded.”
====

[[v13-16-16]]

^<<v13-16-16,16>>^ The covenant he made with Abraham,
And the oath he swore to Isaac,

[[v13-16-17]]

^<<v13-16-17,17>>^ Which he established as a decree to Jacob
And as a lasting covenant to Israel,

[[v13-16-18]]

^<<v13-16-18,18>>^ Saying, ‘I will give you the land of Caʹnaan
As your allotted inheritance.’

[[v13-16-19]]

^<<v13-16-19,19>>^ This was when you were few in number,
Yes, very few, and you were foreigners in the land.

[[v13-16-20]]

^<<v13-16-20,20>>^ They walked about from nation to nation,
From one kingdom to another people.

[[v13-16-21]]

^<<v13-16-21,21>>^ He did not allow any man to oppress them,
But on their account he reproved kings,

[[v13-16-22]]

^<<v13-16-22,22>>^ Saying, ‘Do not touch my anointed ones,
And to my prophets do nothing bad.’

[[v13-16-23]]

^<<v13-16-23,23>>^ Sing to Jehovah, all the earth!
Announce his salvation day after day!

[[v13-16-24]]

^<<v13-16-24,24>>^ Declare his glory among the nations,
His wonderful works among all the peoples.

[[v13-16-25]]

^<<v13-16-25,25>>^ For Jehovah is great and most worthy of praise.
He is more awe-inspiring than all other gods.

[[v13-16-26]]

^<<v13-16-26,26>>^ All the gods of the peoples are worthless gods,
But Jehovah is the one who made the heavens.

[[v13-16-27]]

^<<v13-16-27,27>>^ In his presence are majesty^&#42;1^ and splendor;
Strength and joy are in his dwelling place.

[NOTE]
====
. Or “dignity.”
====

[[v13-16-28]]

^<<v13-16-28,28>>^ Give Jehovah his due, you families of the peoples,
Give Jehovah his due for his glory and strength.

[[v13-16-29]]

^<<v13-16-29,29>>^ Give Jehovah the glory due his name;
Bring a gift and come in before him.
Bow down to^&#42;1^ Jehovah in holy adornment.^&#42;2^

[NOTE]
====
. Or “Worship.”
. Or possibly, “because of the splendor of his holiness.”
====

[[v13-16-30]]

^<<v13-16-30,30>>^ Tremble before him, all the earth!
The earth^&#42;1^ is firmly established; it cannot be moved.^&#42;2^

[NOTE]
====
. Or “The productive land.”
. Or “be shaken; be made to totter.”
====

[[v13-16-31]]

^<<v13-16-31,31>>^ Let the heavens rejoice, and let the earth be joyful;
Declare among the nations: ‘Jehovah has become King!’

[[v13-16-32]]

^<<v13-16-32,32>>^ Let the sea thunder and all that fills it;
Let the fields and everything in them rejoice.

[[v13-16-33]]

^<<v13-16-33,33>>^ At the same time let the trees of the forest shout joyfully before Jehovah,
For he is coming^&#42;1^ to judge the earth.

[NOTE]
====
. Or “has come.”
====

[[v13-16-34]]

^<<v13-16-34,34>>^ Give thanks to Jehovah, for he is good;
His loyal love endures forever.

[[v13-16-35]]

^<<v13-16-35,35>>^ And say, ‘Save us, O God of our salvation,
Gather us and rescue us from the nations,
So that we may give thanks to your holy name
And exult in praising you.^&#42;1^

[NOTE]
====
. Or “exult in your praise.”
====

[[v13-16-36]]

^<<v13-16-36,36>>^ May Jehovah, the God of Israel, be praised
Throughout all eternity.’”^&#42;1^
And all the people said, “Amen!”^&#42;2^ and they praised Jehovah.

[NOTE]
====
. Or “From eternity to eternity.”
. Or “So be it!”
====

[[v13-16-37]]

^<<v13-16-37,37>>^ Then David left Aʹsaph and his brothers there before the ark of the covenant of Jehovah to minister continually before the Ark, according to the daily routine.

[[v13-16-38]]

^<<v13-16-38,38>>^ Oʹbed-eʹdom and his brothers, numbering 68, and Oʹbed-eʹdom, the son of Je·duʹthun, and Hoʹsah were gatekeepers;

[[v13-16-39]]

^<<v13-16-39,39>>^ and Zaʹdok the priest and his fellow priests were before the tabernacle of Jehovah on the high place at Gibʹe·on

[[v13-16-40]]

^<<v13-16-40,40>>^ to offer up burnt offerings to Jehovah regularly on the altar of burnt offering, morning and evening, and to do all that is written in the Law of Jehovah that he commanded Israel.

[[v13-16-41]]

^<<v13-16-41,41>>^ With them were Heʹman and Je·duʹthun and the rest of the selected men who were designated by their names to thank Jehovah, because “his loyal love endures forever”;

[[v13-16-42]]

^<<v13-16-42,42>>^ and with them were Heʹman and Je·duʹthun to sound the trumpets, cymbals, and the instruments used to praise^&#42;1^ the true God; and the sons of Je·duʹthun were at the gate.

[NOTE]
====
. Or “instruments of the song of.”
====

[[v13-16-43]]

^<<v13-16-43,43>>^ Then all the people went to their homes, and David went to bless his own household.

'''

xref:013-1-chronicles/013-1-chronicles-015.adoc#v13-15-0[&#60; Capítulo Anterior] | <<v13-16-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-017.adoc#v13-17-0[Próximo Capítulo &#62;]