include::./index.adoc[]

[[v13-15-0]]
=== The First of Chronicles, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-15-1]]

^<<v13-15-1,1>>^ And he continued building houses for himself in the City of David, and he prepared a place for the Ark of the true God and pitched a tent for it.

[[v13-15-2]]

^<<v13-15-2,2>>^ It was then that David said: “No one is to carry the Ark of the true God except the Levites, for Jehovah has chosen them to carry the Ark of Jehovah and to minister to him always.”

[[v13-15-3]]

^<<v13-15-3,3>>^ Then David congregated all Israel at Jerusalem to bring the Ark of Jehovah up to the place that he had prepared for it.

[[v13-15-4]]

^<<v13-15-4,4>>^ David gathered the descendants of Aaron and the Levites:

[[v13-15-5]]

^<<v13-15-5,5>>^ from the Koʹhath·ites, U·riʹel the chief and 120 of his brothers;

[[v13-15-6]]

^<<v13-15-6,6>>^ from the Me·rarʹites, A·saiʹah the chief and 220 of his brothers;

[[v13-15-7]]

^<<v13-15-7,7>>^ from the Gerʹshom·ites, Joel the chief and 130 of his brothers;

[[v13-15-8]]

^<<v13-15-8,8>>^ from the descendants of E·li·zaʹphan, She·maiʹah the chief and 200 of his brothers;

[[v13-15-9]]

^<<v13-15-9,9>>^ from the descendants of Hebʹron, Eʹli·el the chief and 80 of his brothers;

[[v13-15-10]]

^<<v13-15-10,10>>^ from the descendants of Uzʹzi·el, Am·minʹa·dab the chief and 112 of his brothers.

[[v13-15-11]]

^<<v13-15-11,11>>^ Furthermore, David called the priests Zaʹdok and A·biʹa·thar and the Levites U·riʹel, A·saiʹah, Joel, She·maiʹah, Eʹli·el, and Am·minʹa·dab,

[[v13-15-12]]

^<<v13-15-12,12>>^ and he said to them: “You are the heads of the paternal houses of the Levites. Sanctify yourselves, you and your brothers, and bring the Ark of Jehovah the God of Israel up to the place that I have prepared for it.

[[v13-15-13]]

^<<v13-15-13,13>>^ Since you did not carry it the first time, the anger of Jehovah our God broke out against us, because we did not search out the proper procedure.”

[[v13-15-14]]

^<<v13-15-14,14>>^ So the priests and the Levites sanctified themselves to bring up the Ark of Jehovah the God of Israel.

[[v13-15-15]]

^<<v13-15-15,15>>^ Then the Levites carried the Ark of the true God on their shoulders with the poles, just as Moses had commanded by Jehovah’s word.

[[v13-15-16]]

^<<v13-15-16,16>>^ David then told the chiefs of the Levites to appoint their brothers the singers to sing out joyfully, accompanied by musical instruments: stringed instruments, harps, and cymbals.

[[v13-15-17]]

^<<v13-15-17,17>>^ So the Levites appointed Heʹman the son of Joel and, of his brothers, Aʹsaph the son of Ber·e·chiʹah and, of the Me·rarʹites their brothers, Eʹthan the son of Kush·aʹiah.

[[v13-15-18]]

^<<v13-15-18,18>>^ Together with them were their brothers of the second division, Zech·a·riʹah, Ben, Ja·aʹzi·el, She·mirʹa·moth, Je·hiʹel, Unʹni, E·liʹab, Be·naiʹah, Ma·a·seiʹah, Mat·ti·thiʹah, E·liphʹe·le·hu, and Mik·neʹiah and Oʹbed-eʹdom and Je·iʹel the gatekeepers.

[[v13-15-19]]

^<<v13-15-19,19>>^ The singers Heʹman, Aʹsaph, and Eʹthan were to play the copper cymbals;

[[v13-15-20]]

^<<v13-15-20,20>>^ and Zech·a·riʹah, Aʹzi·el, She·mirʹa·moth, Je·hiʹel, Unʹni, E·liʹab, Ma·a·seiʹah, and Be·naiʹah played stringed instruments tuned to Alʹa·moth;^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v13-15-21]]

^<<v13-15-21,21>>^ and Mat·ti·thiʹah, E·liphʹe·le·hu, Mik·neʹiah, Oʹbed-eʹdom, Je·iʹel, and Az·a·ziʹah played harps tuned to Shemʹi·nith,^&#42;1^ to act as directors.

[NOTE]
====
. See Glossary.
====

[[v13-15-22]]

^<<v13-15-22,22>>^ Chen·a·niʹah the chief of the Levites supervised the transport, for he was an expert,

[[v13-15-23]]

^<<v13-15-23,23>>^ and Ber·e·chiʹah and El·kaʹnah were gatekeepers for the Ark.

[[v13-15-24]]

^<<v13-15-24,24>>^ The priests Sheb·a·niʹah, Joshʹa·phat, Ne·thanʹel, A·maʹsai, Zech·a·riʹah, Be·naiʹah, and E·li·eʹzer loudly sounded the trumpets before the Ark of the true God, and Oʹbed-eʹdom and Je·hiʹah also served as gatekeepers for the Ark.

[[v13-15-25]]

^<<v13-15-25,25>>^ Then David and the elders of Israel and the chiefs of the thousands were walking along to bring the ark of the covenant of Jehovah up from the house of Oʹbed-eʹdom with rejoicing.

[[v13-15-26]]

^<<v13-15-26,26>>^ When the true God helped the Levites who were carrying the ark of the covenant of Jehovah, they sacrificed seven young bulls and seven rams.

[[v13-15-27]]

^<<v13-15-27,27>>^ David was dressed in a sleeveless coat of fine fabric, as were all the Levites carrying the Ark, the singers, and Chen·a·niʹah the chief of the transport and the singers; David was also wearing a linen ephʹod.

[[v13-15-28]]

^<<v13-15-28,28>>^ All the Israelites were bringing up the ark of the covenant of Jehovah with joyful shouting, with the sound of the horn, with trumpets, with cymbals, playing loudly on stringed instruments and harps.

[[v13-15-29]]

^<<v13-15-29,29>>^ But when the ark of the covenant of Jehovah came to the City of David, Saul’s daughter Miʹchal looked down through the window and saw King David skipping about and celebrating; and she began to despise him in her heart.

'''

xref:013-1-chronicles/013-1-chronicles-014.adoc#v13-14-0[&#60; Capítulo Anterior] | <<v13-15-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-016.adoc#v13-16-0[Próximo Capítulo &#62;]