include::./index.adoc[]

[[v13-29-0]]
=== The First of Chronicles, 29
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-29-1]]

^<<v13-29-1,1>>^ King David now said to all the congregation: “My son Solʹo·mon, the one whom God has chosen, is young and inexperienced,^&#42;1^ and the work is great, for it is not a temple^&#42;2^ for man but for Jehovah God.

[NOTE]
====
. Or “delicate.”
. Or “citadel; palace.”
====

[[v13-29-2]]

^<<v13-29-2,2>>^ And I have spared no effort to prepare for the house of my God, providing the gold for the goldwork, the silver for the silverwork, the copper for the copperwork, the iron for the ironwork, the timbers for the timberwork, onyx stones, and stones to be set with mortar, mosaic pebbles, every kind of precious stone, and alabaster stones in great quantity.

[[v13-29-3]]

^<<v13-29-3,3>>^ Moreover, because of my delight in the house of my God, there is also my private treasure of gold and silver that I am giving to the house of my God, in addition to all that I have prepared for the holy house,

[[v13-29-4]]

^<<v13-29-4,4>>^ including 3,000 talents^&#42;1^ of gold from Oʹphir and 7,000 talents of refined silver, for coating the walls of the houses,

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v13-29-5]]

^<<v13-29-5,5>>^ the gold for the goldwork and the silver for the silverwork, and for all the work to be done by the craftsmen. Now who volunteers to come forward today with a gift in hand for Jehovah?”

[[v13-29-6]]

^<<v13-29-6,6>>^ So the princes of the paternal houses, the princes of the tribes of Israel, the chiefs of thousands and of hundreds, and the chiefs of the business of the king came forward voluntarily.

[[v13-29-7]]

^<<v13-29-7,7>>^ And they gave to the service of the house of the true God: 5,000 talents of gold, 10,000 darics,^&#42;1^ 10,000 talents of silver, 18,000 talents of copper, and 100,000 talents of iron.

[NOTE]
====
. A daric was a Persian gold coin. See App. B14.
====

[[v13-29-8]]

^<<v13-29-8,8>>^ Whoever had precious stones gave them to the treasury of the house of Jehovah, under the care of Je·hiʹel the Gerʹshon·ite.

[[v13-29-9]]

^<<v13-29-9,9>>^ The people rejoiced over making these voluntary offerings, for they made the voluntary offerings to Jehovah with a complete heart, and David the king also rejoiced greatly.

[[v13-29-10]]

^<<v13-29-10,10>>^ Then David praised Jehovah before the eyes of all the congregation. David said: “May you be praised, O Jehovah the God of Israel our father, throughout all eternity.^&#42;1^

[NOTE]
====
. Or “from eternity to eternity.”
====

[[v13-29-11]]

^<<v13-29-11,11>>^ Yours, O Jehovah, are the greatness and the mightiness and the beauty and the splendor and the majesty,^&#42;1^ for everything in the heavens and on the earth is yours. Yours is the kingdom, O Jehovah. You are the One exalting yourself as head over all.

[NOTE]
====
. Or “dignity.”
====

[[v13-29-12]]

^<<v13-29-12,12>>^ The riches and the glory are from you, and you rule over everything, and in your hand there are power and mightiness, and your hand is able to make great and to give strength to all.

[[v13-29-13]]

^<<v13-29-13,13>>^ And now, O our God, we thank you and praise your beautiful name.

[[v13-29-14]]

^<<v13-29-14,14>>^ “And yet, who am I and who are my people that we should be in a position to make voluntary offerings like this? For everything is from you, and we have given to you what comes from your own hand.

[[v13-29-15]]

^<<v13-29-15,15>>^ For we are foreign residents in your presence and settlers, just like all our forefathers. For our days on the earth are like a shadow—without hope.

[[v13-29-16]]

^<<v13-29-16,16>>^ O Jehovah our God, all this wealth that we have prepared to build for you a house for your holy name is from your own hand, and it all belongs to you.

[[v13-29-17]]

^<<v13-29-17,17>>^ I well know, O my God, that you examine the heart and that you take pleasure in integrity.^&#42;1^ In the uprightness^&#42;2^ of my heart, I have voluntarily offered all these things, and I am overjoyed to see your people who are present here make voluntary offerings to you.

[NOTE]
====
. Or “rectitude; uprightness.”
. Or “sincerity.”
====

[[v13-29-18]]

^<<v13-29-18,18>>^ O Jehovah, the God of Abraham, Isaac, and Israel, our forefathers, keep these inclinations and thoughts in the hearts of your people forever, and direct their hearts to you.

[[v13-29-19]]

^<<v13-29-19,19>>^ And give a complete^&#42;1^ heart to my son Solʹo·mon, so that he may observe your commandments, your reminders, and your regulations and do all these things and build the temple^&#42;2^ for which I have made preparation.”

[NOTE]
====
. Or “completely devoted.”
. Or “citadel; palace.”
====

[[v13-29-20]]

^<<v13-29-20,20>>^ David then said to all the congregation: “Now praise Jehovah your God.” And all the congregation praised Jehovah the God of their forefathers and bowed low and prostrated themselves to Jehovah and to the king.

[[v13-29-21]]

^<<v13-29-21,21>>^ And they continued to offer sacrifices to Jehovah and to offer up burnt offerings to Jehovah on the following day, 1,000 young bulls, 1,000 rams, 1,000 male lambs, and their drink offerings; they offered sacrifices in great number for all Israel.

[[v13-29-22]]

^<<v13-29-22,22>>^ They continued eating and drinking before Jehovah on that day with great rejoicing, and for a second time they made Solʹo·mon the son of David king and anointed him before Jehovah as leader, and also Zaʹdok as priest.

[[v13-29-23]]

^<<v13-29-23,23>>^ And Solʹo·mon sat on Jehovah’s throne as king in place of David his father, and he was successful, and all the Israelites were obedient to him.

[[v13-29-24]]

^<<v13-29-24,24>>^ All the princes, the mighty warriors, and also all the sons of King David submitted themselves to Solʹo·mon the king.

[[v13-29-25]]

^<<v13-29-25,25>>^ And Jehovah made Solʹo·mon exceedingly great before the eyes of all Israel and bestowed on him royal majesty such as no king over Israel ever had before.

[[v13-29-26]]

^<<v13-29-26,26>>^ Thus David the son of Jesʹse reigned over all Israel,

[[v13-29-27]]

^<<v13-29-27,27>>^ and the length^&#42;1^ of his reign over Israel was 40 years. In Hebʹron he reigned for 7 years, and in Jerusalem he reigned for 33 years.

[NOTE]
====
. Lit., “the days.”
====

[[v13-29-28]]

^<<v13-29-28,28>>^ And he died at a good old age, satisfied with long life,^&#42;1^ wealth, and glory; and his son Solʹo·mon became king in his place.

[NOTE]
====
. Lit., “with days.”
====

[[v13-29-29]]

^<<v13-29-29,29>>^ As for the history of King David, from beginning to end, it is written among the words of Samuel the seer, Nathan the prophet, and Gad the visionary,

[[v13-29-30]]

^<<v13-29-30,30>>^ together with all his kingship, his mightiness, and the events of the times involving him and Israel and all the surrounding kingdoms.

'''

xref:013-1-chronicles/013-1-chronicles-028.adoc#v13-28-0[&#60; Capítulo Anterior] | <<v13-29-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-001.adoc#v14-1-0[Próximo Capítulo &#62;]