include::./index.adoc[]

[[v13-5-0]]
=== The First of Chronicles, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-5-1]]

^<<v13-5-1,1>>^ These are the sons of Reuʹben, Israel’s firstborn. He was the firstborn, but because he defiled^&#42;1^ the bed of his father, his right as firstborn was given to the sons of Joseph the son of Israel, so he was not enrolled genealogically for the right of the firstborn.

[NOTE]
====
. Or “profaned.”
====

[[v13-5-2]]

^<<v13-5-2,2>>^ Though Judah was superior to his brothers and from him came the one to be the leader, the right as firstborn belonged to Joseph.

[[v13-5-3]]

^<<v13-5-3,3>>^ The sons of Reuʹben the firstborn of Israel were Haʹnoch, Palʹlu, Hezʹron, and Carʹmi.

[[v13-5-4]]

^<<v13-5-4,4>>^ The sons of Joel were She·maiʹah his son, Gog his son, Shimʹe·i his son,

[[v13-5-5]]

^<<v13-5-5,5>>^ Miʹcah his son, Re·aʹiah his son, Baʹal his son,

[[v13-5-6]]

^<<v13-5-6,6>>^ and Be·erʹah his son, whom King Tilʹgath-pil·neʹser of As·syrʹi·a took into exile; he was a chieftain of the Reuʹben·ites.

[[v13-5-7]]

^<<v13-5-7,7>>^ His brothers by their families in the genealogical enrollment by their descendants were, as the head, Je·iʹel, Zech·a·riʹah,

[[v13-5-8]]

^<<v13-5-8,8>>^ and Beʹla son of Aʹzaz son of Sheʹma son of Joel, who lived in A·roʹer and as far as Neʹbo and Baʹal-meʹon.

[[v13-5-9]]

^<<v13-5-9,9>>^ To the east he settled as far as the beginning of the wilderness at the Eu·phraʹtes River, for their livestock had become numerous in the land of Gilʹe·ad.

[[v13-5-10]]

^<<v13-5-10,10>>^ In the days of Saul, they waged war against the Hagʹrites, who were defeated before them, so they dwelled in their tents throughout all the territory east of Gilʹe·ad.

[[v13-5-11]]

^<<v13-5-11,11>>^ Now the descendants of Gad lived next to them in the land of Baʹshan as far as Salʹe·cah.

[[v13-5-12]]

^<<v13-5-12,12>>^ Joel was the head, Shaʹpham the second, and Jaʹnai and Shaʹphat in Baʹshan.

[[v13-5-13]]

^<<v13-5-13,13>>^ And their brothers belonging to their paternal houses were Miʹcha·el, Me·shulʹlam, Sheʹba, Joʹrai, Jaʹcan, Ziʹa, and Eʹber, seven in all.

[[v13-5-14]]

^<<v13-5-14,14>>^ These were the sons of Abʹi·ha·il son of Huʹri son of Ja·roʹah son of Gilʹe·ad son of Miʹcha·el son of Je·shishʹai son of Jahʹdo son of Buz.

[[v13-5-15]]

^<<v13-5-15,15>>^ Aʹhi son of Abʹdi·el son of Guʹni was head of their paternal house.

[[v13-5-16]]

^<<v13-5-16,16>>^ They lived in Gilʹe·ad, in Baʹshan and its dependent^&#42;1^ towns, and in all the pastures of Sharʹon as far as they extended.

[NOTE]
====
. Or “surrounding.”
====

[[v13-5-17]]

^<<v13-5-17,17>>^ They were all enrolled genealogically in the days of King Joʹtham of Judah and in the days of King Jer·o·boʹam^&#42;1^ of Israel.

[NOTE]
====
. That is, Jeroboam II.
====

[[v13-5-18]]

^<<v13-5-18,18>>^ The Reuʹben·ites, the Gadʹites, and the half tribe of Ma·nasʹseh had 44,760 mighty warriors in their army who carried shields and swords and were armed with bows,^&#42;1^ and they were trained in war.

[NOTE]
====
. Lit., “and tread the bow.”
====

[[v13-5-19]]

^<<v13-5-19,19>>^ They waged war against the Hagʹrites, Jeʹtur, Naʹphish, and Noʹdab.

[[v13-5-20]]

^<<v13-5-20,20>>^ And they were helped in fighting them, so that the Hagʹrites and all who were with them were given into their hand, for they called to God for help in the war, and he responded to their entreaty because they trusted in him.

[[v13-5-21]]

^<<v13-5-21,21>>^ They captured their livestock—50,000 camels, 250,000 sheep, and 2,000 donkeys—as well as 100,000 people.^&#42;1^

[NOTE]
====
. Or “human souls.”
====

[[v13-5-22]]

^<<v13-5-22,22>>^ Many had fallen slain, because the war was waged by the true God. And they lived in their place until the time of the exile.

[[v13-5-23]]

^<<v13-5-23,23>>^ The descendants of the half tribe of Ma·nasʹseh lived in the land from Baʹshan to Baʹal-herʹmon and Seʹnir and Mount Herʹmon. They were numerous.

[[v13-5-24]]

^<<v13-5-24,24>>^ These were the heads of their paternal houses: Eʹpher, Ishʹi, Eʹli·el, Azʹri·el, Jeremiah, Hod·a·viʹah, and Jahʹdi·el; they were mighty warriors, men of fame, and heads of their paternal houses.

[[v13-5-25]]

^<<v13-5-25,25>>^ But they acted unfaithfully toward the God of their forefathers and prostituted themselves to the gods of the peoples of the land, whom God had annihilated from before them.

[[v13-5-26]]

^<<v13-5-26,26>>^ So the God of Israel stirred up the spirit of King Pul of As·syrʹi·a (that is, King Tilʹgath-pil·neʹser of As·syrʹi·a) so that he took into exile those of the Reuʹben·ites, the Gadʹites, and the half tribe of Ma·nasʹseh and brought them to Haʹlah, Haʹbor, Haʹra, and the river Goʹzan, where they are until this day.

'''

xref:013-1-chronicles/013-1-chronicles-004.adoc#v13-4-0[&#60; Capítulo Anterior] | <<v13-5-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-006.adoc#v13-6-0[Próximo Capítulo &#62;]