include::./index.adoc[]

[[v13-7-0]]
=== The First of Chronicles, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-7-1]]

^<<v13-7-1,1>>^ Now the sons of Isʹsa·char were Toʹla, Puʹah, Jaʹshub, and Shimʹron—four.

[[v13-7-2]]

^<<v13-7-2,2>>^ And the sons of Toʹla were Uzʹzi, Re·phaʹiah, Jeʹri·el, Jahʹmai, Ibʹsam, and She·muʹel, the heads of their paternal houses. Descended from Toʹla were mighty warriors, whose number in the days of David was 22,600.

[[v13-7-3]]

^<<v13-7-3,3>>^ And the descendants^&#42;1^ of Uzʹzi were Iz·ra·hiʹah and the sons of Iz·ra·hiʹah: Miʹcha·el, O·ba·diʹah, Joel, and Is·shiʹah—all five of them were chiefs.^&#42;2^

[NOTE]
====
. Lit., “sons.”
. Lit., “heads.”
====

[[v13-7-4]]

^<<v13-7-4,4>>^ And with them by their descendants, according to their paternal houses, there were 36,000 soldiers in their army available for war, for they had many wives and sons.

[[v13-7-5]]

^<<v13-7-5,5>>^ And their brothers of all the families of Isʹsa·char were mighty warriors, 87,000 as listed in the genealogical enrollment.

[[v13-7-6]]

^<<v13-7-6,6>>^ The sons of Benjamin were Beʹla, Beʹcher, and Je·diʹa·el—three.

[[v13-7-7]]

^<<v13-7-7,7>>^ And the sons of Beʹla were Ezʹbon, Uzʹzi, Uzʹzi·el, Jerʹi·moth, and Iʹri—five—heads of their paternal houses, mighty warriors, and 22,034 were in their genealogical enrollment.

[[v13-7-8]]

^<<v13-7-8,8>>^ And the sons of Beʹcher were Ze·miʹrah, Joʹash, E·li·eʹzer, Eli·o·eʹnai, Omʹri, Jerʹe·moth, A·biʹjah, Anʹa·thoth, and Alʹe·meth—all of these were the sons of Beʹcher.

[[v13-7-9]]

^<<v13-7-9,9>>^ Their genealogical enrollment by their descendants as respects the heads of their paternal houses was 20,200 mighty warriors.

[[v13-7-10]]

^<<v13-7-10,10>>^ And the sons of Je·diʹa·el were Bilʹhan and the sons of Bilʹhan: Jeʹush, Benjamin, Eʹhud, Che·naʹa·nah, Zeʹthan, Tarʹshish, and A·hishʹa·har.

[[v13-7-11]]

^<<v13-7-11,11>>^ All of these were the sons of Je·diʹa·el, according to the heads of their forefathers, 17,200 mighty warriors ready to go out to the army for war.

[[v13-7-12]]

^<<v13-7-12,12>>^ The Shupʹpim and the Hupʹpim were the sons of Ir; the Huʹshim were the sons of Aʹher.

[[v13-7-13]]

^<<v13-7-13,13>>^ The sons of Naphʹta·li were Jahʹzi·el, Guʹni, Jeʹzer, and Shalʹlum—descendants^&#42;1^ of Bilʹhah.

[NOTE]
====
. Lit., “sons.”
====

[[v13-7-14]]

^<<v13-7-14,14>>^ The sons of Ma·nasʹseh: Asʹri·el, whom his Syrian concubine bore. (She bore Maʹchir the father of Gilʹe·ad.

[[v13-7-15]]

^<<v13-7-15,15>>^ Maʹchir took a wife for Hupʹpim and for Shupʹpim, and the name of his sister was Maʹa·cah.) The name of the second was Ze·loʹphe·had, but Ze·loʹphe·had had daughters.

[[v13-7-16]]

^<<v13-7-16,16>>^ Maʹa·cah, Maʹchir’s wife, bore a son and named him Peʹresh; and the name of his brother was Sheʹresh; and his sons were Uʹlam and Reʹkem.

[[v13-7-17]]

^<<v13-7-17,17>>^ And the son^&#42;1^ of Uʹlam was Beʹdan. These were the sons of Gilʹe·ad son of Maʹchir son of Ma·nasʹseh.

[NOTE]
====
. Lit., “sons.”
====

[[v13-7-18]]

^<<v13-7-18,18>>^ And his sister was Ham·moʹle·cheth. She gave birth to Ishʹhod, Abi-eʹzer, and Mahʹlah.

[[v13-7-19]]

^<<v13-7-19,19>>^ And the sons of She·miʹda were A·hiʹan, Sheʹchem, Likʹhi, and A·niʹam.

[[v13-7-20]]

^<<v13-7-20,20>>^ The sons of Eʹphra·im were Shuʹthe·lah, Beʹred his son, Taʹhath his son, E·le·aʹdah his son, Taʹhath his son,

[[v13-7-21]]

^<<v13-7-21,21>>^ Zaʹbad his son, Shuʹthe·lah his son, Eʹzer, and Eʹle·ad. The men of Gath who were born in the land killed them because they went down to take their livestock.

[[v13-7-22]]

^<<v13-7-22,22>>^ Eʹphra·im their father carried on mourning for many days, and his brothers kept coming in to comfort him.

[[v13-7-23]]

^<<v13-7-23,23>>^ Afterward he had relations with his wife, and she became pregnant and gave birth to a son. But he named him Be·riʹah^&#42;1^ because it was with calamity that she was in his house.

[NOTE]
====
. Meaning “With Calamity.”
====

[[v13-7-24]]

^<<v13-7-24,24>>^ And his daughter was Sheʹe·rah, who built Lower and Upper Beth-hoʹron and Uzʹzen-sheʹe·rah.

[[v13-7-25]]

^<<v13-7-25,25>>^ And there was Reʹphah his son, Reʹsheph, Teʹlah his son, Taʹhan his son,

[[v13-7-26]]

^<<v13-7-26,26>>^ Laʹdan his son, Am·miʹhud his son, E·lishʹa·ma his son,

[[v13-7-27]]

^<<v13-7-27,27>>^ Nun his son, and Joshua^&#42;1^ his son.

[NOTE]
====
. Or “Jehoshua,” meaning “Jehovah Is Salvation.”
====

[[v13-7-28]]

^<<v13-7-28,28>>^ Their possession and their settlements were Bethʹel and its dependent^&#42;1^ towns, and to the east Naʹa·ran, and to the west Geʹzer and its dependent towns, and Sheʹchem and its dependent towns, as far as Ayʹyah^&#42;2^ and its dependent towns;

[NOTE]
====
. Or “surrounding.”
. Or possibly, “Gaza,” though not the Gaza in Philistia.
====

[[v13-7-29]]

^<<v13-7-29,29>>^ and next to the descendants of Ma·nasʹseh, Beth-sheʹan and its dependent towns, Taʹa·nach and its dependent towns, Me·gidʹdo and its dependent towns, and Dor and its dependent towns. In these the descendants of Joseph the son of Israel lived.

[[v13-7-30]]

^<<v13-7-30,30>>^ The sons of Ashʹer were Imʹnah, Ishʹvah, Ishʹvi, and Be·riʹah, and their sister was Seʹrah.

[[v13-7-31]]

^<<v13-7-31,31>>^ The sons of Be·riʹah were Heʹber and Malʹchi·el, who was the father of Birʹza·ith.

[[v13-7-32]]

^<<v13-7-32,32>>^ Heʹber became father to Japhʹlet, Shoʹmer, and Hoʹtham, and to Shuʹa their sister.

[[v13-7-33]]

^<<v13-7-33,33>>^ The sons of Japhʹlet were Paʹsach, Bimʹhal, and Ashʹvath. These were the sons of Japhʹlet.

[[v13-7-34]]

^<<v13-7-34,34>>^ The sons of Sheʹmer^&#42;1^ were Aʹhi, Rohʹgah, Je·hubʹbah, and Aʹram.

[NOTE]
====
. Also called Shomer in vs. 32.
====

[[v13-7-35]]

^<<v13-7-35,35>>^ The sons of Heʹlem^&#42;1^ his brother were Zoʹphah, Imʹna, Sheʹlesh, and Aʹmal.

[NOTE]
====
. Likely the same as “Hotham” in vs. 32.
====

[[v13-7-36]]

^<<v13-7-36,36>>^ The sons of Zoʹphah were Suʹah, Harʹne·pher, Shuʹal, Beʹri, Imʹrah,

[[v13-7-37]]

^<<v13-7-37,37>>^ Beʹzer, Hod, Shamʹma, Shilʹshah, Ithʹran, and Be·eʹra.

[[v13-7-38]]

^<<v13-7-38,38>>^ The sons of Jeʹther were Je·phunʹneh, Pisʹpah, and Aʹra.

[[v13-7-39]]

^<<v13-7-39,39>>^ The sons of Ulʹla were Aʹrah, Hanʹni·el, and Ri·ziʹa.

[[v13-7-40]]

^<<v13-7-40,40>>^ All of these were the sons of Ashʹer, heads of their paternal houses, select, mighty warriors, heads of the chieftains; and their number listed in the genealogical enrollment was 26,000 men in the army available for war.

'''

xref:013-1-chronicles/013-1-chronicles-006.adoc#v13-6-0[&#60; Capítulo Anterior] | <<v13-7-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-008.adoc#v13-8-0[Próximo Capítulo &#62;]