include::./index.adoc[]

[[v13-23-0]]
=== The First of Chronicles, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-23-1]]

^<<v13-23-1,1>>^ When David had grown old and was near the end of his life,^&#42;1^ he made his son Solʹo·mon king over Israel.

[NOTE]
====
. Lit., “old and full of days.”
====

[[v13-23-2]]

^<<v13-23-2,2>>^ He then gathered all the princes of Israel, the priests, and the Levites.

[[v13-23-3]]

^<<v13-23-3,3>>^ The Levites who were 30 years old and up were numbered; their number, their head count man by man, was 38,000.

[[v13-23-4]]

^<<v13-23-4,4>>^ Of these, 24,000 served as supervisors over the work of Jehovah’s house, and there were 6,000 officers and judges,

[[v13-23-5]]

^<<v13-23-5,5>>^ and there were 4,000 gatekeepers, and 4,000 gave praise to Jehovah on the instruments about which David said, “I made them for giving praise.”

[[v13-23-6]]

^<<v13-23-6,6>>^ Then David organized^&#42;1^ them into divisions according to the sons of Leʹvi: Gerʹshon, Koʹhath, and Me·rarʹi.

[NOTE]
====
. Or “divided.”
====

[[v13-23-7]]

^<<v13-23-7,7>>^ Of the Gerʹshon·ites were Laʹdan and Shimʹe·i.

[[v13-23-8]]

^<<v13-23-8,8>>^ The sons of Laʹdan were Je·hiʹel the headman, Zeʹtham, and Joel, three.

[[v13-23-9]]

^<<v13-23-9,9>>^ The sons of Shimʹe·i were She·loʹmoth, Haʹzi·el, and Haʹran, three. These were the heads of the paternal houses for Laʹdan.

[[v13-23-10]]

^<<v13-23-10,10>>^ And the sons of Shimʹe·i were Jaʹhath, Ziʹna, Jeʹush, and Be·riʹah. These four were the sons of Shimʹe·i.

[[v13-23-11]]

^<<v13-23-11,11>>^ Jaʹhath was the head and Ziʹzah, the second. But since Jeʹush and Be·riʹah did not have many sons, they were counted as one paternal house with one area of responsibility.

[[v13-23-12]]

^<<v13-23-12,12>>^ The sons of Koʹhath were Amʹram, Izʹhar, Hebʹron, and Uzʹzi·el, four.

[[v13-23-13]]

^<<v13-23-13,13>>^ The sons of Amʹram were Aaron and Moses. But Aaron was permanently set apart to sanctify the Most Holy, he and his sons, to offer sacrifices before Jehovah, to minister to him, and to pronounce blessings in his name always.

[[v13-23-14]]

^<<v13-23-14,14>>^ As for Moses the man of the true God, his sons were named among the tribe of the Levites.

[[v13-23-15]]

^<<v13-23-15,15>>^ The sons of Moses were Gerʹshom and E·li·eʹzer.

[[v13-23-16]]

^<<v13-23-16,16>>^ Of the sons of Gerʹshom, Shebʹu·el was the head.

[[v13-23-17]]

^<<v13-23-17,17>>^ Of the descendants^&#42;1^ of E·li·eʹzer, Re·ha·biʹah was the head; E·li·eʹzer did not have other sons, but the sons of Re·ha·biʹah were very many.

[NOTE]
====
. Lit., “sons.”
====

[[v13-23-18]]

^<<v13-23-18,18>>^ Of the sons of Izʹhar, She·loʹmith was the headman.

[[v13-23-19]]

^<<v13-23-19,19>>^ The sons of Hebʹron were Je·riʹah the head, Am·a·riʹah the second, Ja·ha·ziʹel the third, and Jek·a·meʹam the fourth.

[[v13-23-20]]

^<<v13-23-20,20>>^ The sons of Uzʹzi·el were Miʹcah the head and Is·shiʹah the second.

[[v13-23-21]]

^<<v13-23-21,21>>^ The sons of Me·rarʹi were Mahʹli and Muʹshi. The sons of Mahʹli were El·e·aʹzar and Kish.

[[v13-23-22]]

^<<v13-23-22,22>>^ El·e·aʹzar died, but he had no sons, only daughters. So the sons of Kish, their relatives,^&#42;1^ took them as wives.

[NOTE]
====
. Lit., “brothers.”
====

[[v13-23-23]]

^<<v13-23-23,23>>^ The sons of Muʹshi were Mahʹli, Eʹder, and Jerʹe·moth, three.

[[v13-23-24]]

^<<v13-23-24,24>>^ These were the sons of Leʹvi according to their paternal houses, the heads of the paternal houses, by those registered who were counted and listed by their names and who carried out the work for the service of the house of Jehovah, from 20 years old and up.

[[v13-23-25]]

^<<v13-23-25,25>>^ For David had said: “Jehovah the God of Israel has given rest to his people, and he will reside in Jerusalem forever.

[[v13-23-26]]

^<<v13-23-26,26>>^ Also the Levites will not have to carry the tabernacle or any of its equipment for its service.”

[[v13-23-27]]

^<<v13-23-27,27>>^ For according to the last instructions of David, the Levites from 20 years old and up were numbered.

[[v13-23-28]]

^<<v13-23-28,28>>^ Their function was to assist the sons of Aaron for the service of the house of Jehovah, to be in charge of the courtyards, the dining rooms, the purification of every holy thing, and any work needed for the service of the house of the true God.

[[v13-23-29]]

^<<v13-23-29,29>>^ They assisted with the layer bread,^&#42;1^ the fine flour for the grain offering, the wafers of unleavened bread, the griddle cakes, the mixed dough, and all measures of quantity and size.

[NOTE]
====
. That is, the showbread.
====

[[v13-23-30]]

^<<v13-23-30,30>>^ They were to stand morning by morning to thank and praise Jehovah and likewise in the evening.

[[v13-23-31]]

^<<v13-23-31,31>>^ They assisted whenever the burnt sacrifices were offered to Jehovah on the Sabbaths, the new moons, and during the festival seasons, according to the number required by the rules concerning them, doing so regularly before Jehovah.

[[v13-23-32]]

^<<v13-23-32,32>>^ They also took care of their responsibilities toward the tent of meeting, toward the holy place, and toward their brothers the sons of Aaron for the service of the house of Jehovah.

'''

xref:013-1-chronicles/013-1-chronicles-022.adoc#v13-22-0[&#60; Capítulo Anterior] | <<v13-23-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-024.adoc#v13-24-0[Próximo Capítulo &#62;]