include::./index.adoc[]

[[v13-6-0]]
=== The First of Chronicles, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-6-1]]

^<<v13-6-1,1>>^ The sons of Leʹvi were Gerʹshon, Koʹhath, and Me·rarʹi.

[[v13-6-2]]

^<<v13-6-2,2>>^ The sons of Koʹhath were Amʹram, Izʹhar, Hebʹron, and Uzʹzi·el.

[[v13-6-3]]

^<<v13-6-3,3>>^ The children^&#42;1^ of Amʹram were Aaron, Moses, and also Mirʹi·am. And the sons of Aaron were Naʹdab, A·biʹhu, El·e·aʹzar, and Ithʹa·mar.

[NOTE]
====
. Lit., “sons.”
====

[[v13-6-4]]

^<<v13-6-4,4>>^ El·e·aʹzar became father to Phinʹe·has; Phinʹe·has became father to Ab·i·shuʹa.

[[v13-6-5]]

^<<v13-6-5,5>>^ Ab·i·shuʹa became father to Bukʹki; Bukʹki became father to Uzʹzi.

[[v13-6-6]]

^<<v13-6-6,6>>^ Uzʹzi became father to Zer·a·hiʹah; Zer·a·hiʹah became father to Me·raʹioth.

[[v13-6-7]]

^<<v13-6-7,7>>^ Me·raʹioth became father to Am·a·riʹah; Am·a·riʹah became father to A·hiʹtub.

[[v13-6-8]]

^<<v13-6-8,8>>^ A·hiʹtub became father to Zaʹdok; Zaʹdok became father to A·himʹa·az.

[[v13-6-9]]

^<<v13-6-9,9>>^ A·himʹa·az became father to Az·a·riʹah; Az·a·riʹah became father to Jo·haʹnan.

[[v13-6-10]]

^<<v13-6-10,10>>^ Jo·haʹnan became father to Az·a·riʹah. He served as priest in the house that Solʹo·mon built in Jerusalem.

[[v13-6-11]]

^<<v13-6-11,11>>^ Az·a·riʹah became father to Am·a·riʹah; Am·a·riʹah became father to A·hiʹtub.

[[v13-6-12]]

^<<v13-6-12,12>>^ A·hiʹtub became father to Zaʹdok; Zaʹdok became father to Shalʹlum.

[[v13-6-13]]

^<<v13-6-13,13>>^ Shalʹlum became father to Hil·kiʹah; Hil·kiʹah became father to Az·a·riʹah.

[[v13-6-14]]

^<<v13-6-14,14>>^ Az·a·riʹah became father to Se·raiʹah; Se·raiʹah became father to Je·hozʹa·dak.

[[v13-6-15]]

^<<v13-6-15,15>>^ And Je·hozʹa·dak went into exile when Jehovah took Judah and Jerusalem into exile by the hand of Neb·u·chad·nezʹzar.

[[v13-6-16]]

^<<v13-6-16,16>>^ The sons of Leʹvi were Gerʹshom,^&#42;1^ Koʹhath, and Me·rarʹi.

[NOTE]
====
. Also called Gershon in vs. 1.
====

[[v13-6-17]]

^<<v13-6-17,17>>^ These are the names of the sons of Gerʹshom: Libʹni and Shimʹe·i.

[[v13-6-18]]

^<<v13-6-18,18>>^ The sons of Koʹhath were Amʹram, Izʹhar, Hebʹron, and Uzʹzi·el.

[[v13-6-19]]

^<<v13-6-19,19>>^ The sons of Me·rarʹi were Mahʹli and Muʹshi.
These were the families of the Levites by their forefathers:

[[v13-6-20]]

^<<v13-6-20,20>>^ Of Gerʹshom, Libʹni his son, Jaʹhath his son, Zimʹmah his son,

[[v13-6-21]]

^<<v13-6-21,21>>^ Joʹah his son, Idʹdo his son, Zeʹrah his son, Je·athʹe·rai his son.

[[v13-6-22]]

^<<v13-6-22,22>>^ The sons^&#42;1^ of Koʹhath were Am·minʹa·dab his son, Korʹah his son, Asʹsir his son,

[NOTE]
====
. Or “descendants.”
====

[[v13-6-23]]

^<<v13-6-23,23>>^ El·kaʹnah his son, E·biʹa·saph his son, Asʹsir his son,

[[v13-6-24]]

^<<v13-6-24,24>>^ Taʹhath his son, U·riʹel his son, Uz·ziʹah his son, and Shaʹul his son.

[[v13-6-25]]

^<<v13-6-25,25>>^ The sons of El·kaʹnah were A·maʹsai and A·hiʹmoth.

[[v13-6-26]]

^<<v13-6-26,26>>^ As for El·kaʹnah, the sons of El·kaʹnah were Zoʹphai his son, Naʹhath his son,

[[v13-6-27]]

^<<v13-6-27,27>>^ E·liʹab his son, Je·roʹham his son, El·kaʹnah his son.

[[v13-6-28]]

^<<v13-6-28,28>>^ The sons of Samuel were Joel the firstborn and A·biʹjah the second.

[[v13-6-29]]

^<<v13-6-29,29>>^ The sons^&#42;1^ of Me·rarʹi were Mahʹli, Libʹni his son, Shimʹe·i his son, Uzʹzah his son,

[NOTE]
====
. Or “descendants.”
====

[[v13-6-30]]

^<<v13-6-30,30>>^ Shimʹe·a his son, Hag·giʹah his son, and A·saiʹah his son.

[[v13-6-31]]

^<<v13-6-31,31>>^ These were the ones whom David appointed to direct the singing at the house of Jehovah after the Ark came to rest there.

[[v13-6-32]]

^<<v13-6-32,32>>^ They were responsible for the singing at the tabernacle of the tent of meeting until Solʹo·mon built the house of Jehovah in Jerusalem, and they carried out their service as prescribed for them.

[[v13-6-33]]

^<<v13-6-33,33>>^ These are the men who served with their sons: Of the Koʹhath·ites, Heʹman the singer, son of Joel son of Samuel

[[v13-6-34]]

^<<v13-6-34,34>>^ son of El·kaʹnah son of Je·roʹham son of Eʹli·el son of Toʹah

[[v13-6-35]]

^<<v13-6-35,35>>^ son of Zuph son of El·kaʹnah son of Maʹhath son of A·maʹsai

[[v13-6-36]]

^<<v13-6-36,36>>^ son of El·kaʹnah son of Joel son of Az·a·riʹah son of Zeph·a·niʹah

[[v13-6-37]]

^<<v13-6-37,37>>^ son of Taʹhath son of Asʹsir son of E·biʹa·saph son of Korʹah

[[v13-6-38]]

^<<v13-6-38,38>>^ son of Izʹhar son of Koʹhath son of Leʹvi son of Israel.

[[v13-6-39]]

^<<v13-6-39,39>>^ His brother Aʹsaph stood at his right hand; Aʹsaph was son of Ber·e·chiʹah son of Shimʹe·a

[[v13-6-40]]

^<<v13-6-40,40>>^ son of Miʹcha·el son of Ba·a·seʹiah son of Mal·chiʹjah

[[v13-6-41]]

^<<v13-6-41,41>>^ son of Ethʹni son of Zeʹrah son of A·daiʹah

[[v13-6-42]]

^<<v13-6-42,42>>^ son of Eʹthan son of Zimʹmah son of Shimʹe·i

[[v13-6-43]]

^<<v13-6-43,43>>^ son of Jaʹhath son of Gerʹshom son of Leʹvi.

[[v13-6-44]]

^<<v13-6-44,44>>^ The descendants of Me·rarʹi their brothers were at the left hand; there was Eʹthan son of Kishʹi son of Abʹdi son of Malʹluch

[[v13-6-45]]

^<<v13-6-45,45>>^ son of Hash·a·biʹah son of Am·a·ziʹah son of Hil·kiʹah

[[v13-6-46]]

^<<v13-6-46,46>>^ son of Amʹzi son of Baʹni son of Sheʹmer

[[v13-6-47]]

^<<v13-6-47,47>>^ son of Mahʹli son of Muʹshi son of Me·rarʹi son of Leʹvi.

[[v13-6-48]]

^<<v13-6-48,48>>^ Their brothers the Levites were appointed^&#42;1^ for all the service of the tabernacle, the house of the true God.

[NOTE]
====
. Lit., “were the ones given.”
====

[[v13-6-49]]

^<<v13-6-49,49>>^ Aaron and his sons made the sacrifices smoke on the altar of burnt offering and on the altar of incense, performing the duties connected with the most holy things, to make atonement for Israel, according to all that Moses the servant of the true God had commanded.

[[v13-6-50]]

^<<v13-6-50,50>>^ These were the descendants of Aaron: El·e·aʹzar his son, Phinʹe·has his son, Ab·i·shuʹa his son,

[[v13-6-51]]

^<<v13-6-51,51>>^ Bukʹki his son, Uzʹzi his son, Zer·a·hiʹah his son,

[[v13-6-52]]

^<<v13-6-52,52>>^ Me·raʹioth his son, Am·a·riʹah his son, A·hiʹtub his son,

[[v13-6-53]]

^<<v13-6-53,53>>^ Zaʹdok his son, and A·himʹa·az his son.

[[v13-6-54]]

^<<v13-6-54,54>>^ These were their settlements by their encampments^&#42;1^ in their territory: for the descendants of Aaron belonging to the family of the Koʹhath·ites, as the first lot fell to them,

[NOTE]
====
. Or “walled camps.”
====

[[v13-6-55]]

^<<v13-6-55,55>>^ they gave them Hebʹron in the land of Judah, with its surrounding pastures.

[[v13-6-56]]

^<<v13-6-56,56>>^ But the field of the city and its settlements they gave to Caʹleb the son of Je·phunʹneh.

[[v13-6-57]]

^<<v13-6-57,57>>^ And to the descendants of Aaron they gave the cities^&#42;1^ of refuge, Hebʹron, also Libʹnah with its pastures, Jatʹtir, Esh·te·moʹa with its pastures,

[NOTE]
====
. Or possibly, “city,” in agreement with Jos 21:13.
====

[[v13-6-58]]

^<<v13-6-58,58>>^ Hiʹlen with its pastures, Deʹbir with its pastures,

[[v13-6-59]]

^<<v13-6-59,59>>^ Aʹshan with its pastures, and Beth-sheʹmesh with its pastures;

[[v13-6-60]]

^<<v13-6-60,60>>^ and from the tribe of Benjamin, Geʹba with its pastures, Alʹe·meth with its pastures, and Anʹa·thoth with its pastures. All their cities for their families were 13 cities.

[[v13-6-61]]

^<<v13-6-61,61>>^ To the rest of the Koʹhath·ites, there were allotted^&#42;1^ ten cities, from the family of the tribe, from the half tribe, the half of Ma·nasʹseh.

[NOTE]
====
. Or “given by lot.”
====

[[v13-6-62]]

^<<v13-6-62,62>>^ To the Gerʹshom·ites by their families they assigned 13 cities from the tribe of Isʹsa·char, the tribe of Ashʹer, the tribe of Naphʹta·li, and the tribe of Ma·nasʹseh in Baʹshan.

[[v13-6-63]]

^<<v13-6-63,63>>^ To the Me·rarʹites by their families they assigned by lot 12 cities from the tribe of Reuʹben, the tribe of Gad, and the tribe of Zebʹu·lun.

[[v13-6-64]]

^<<v13-6-64,64>>^ Thus the Israelites gave the Levites these cities with their pastures.

[[v13-6-65]]

^<<v13-6-65,65>>^ Furthermore, they assigned by lot these cities from the tribe of Judah, the tribe of Simʹe·on, and the tribe of Benjamin, which are mentioned by their names.

[[v13-6-66]]

^<<v13-6-66,66>>^ Some of the Koʹhath·ite families had cities from the tribe of Eʹphra·im as their territory.

[[v13-6-67]]

^<<v13-6-67,67>>^ They gave them the cities^&#42;1^ of refuge, Sheʹchem with its pastures in the mountainous region of Eʹphra·im, Geʹzer with its pastures,

[NOTE]
====
. Or possibly, “city,” in agreement with Jos 21:21.
====

[[v13-6-68]]

^<<v13-6-68,68>>^ Jokʹme·am with its pastures, Beth-hoʹron with its pastures,

[[v13-6-69]]

^<<v13-6-69,69>>^ Aiʹja·lon with its pastures, and Gath-rimʹmon with its pastures;

[[v13-6-70]]

^<<v13-6-70,70>>^ and from half of the tribe of Ma·nasʹseh, Aʹner with its pastures and Bilʹe·am with its pastures, to the rest of the families of the Koʹhath·ites.

[[v13-6-71]]

^<<v13-6-71,71>>^ To the Gerʹshom·ites they assigned from the family of the half tribe of Ma·nasʹseh, Goʹlan in Baʹshan with its pastures and Ashʹta·roth with its pastures;

[[v13-6-72]]

^<<v13-6-72,72>>^ and from the tribe of Isʹsa·char, Keʹdesh with its pastures, Dabʹe·rath with its pastures,

[[v13-6-73]]

^<<v13-6-73,73>>^ Raʹmoth with its pastures, and Aʹnem with its pastures;

[[v13-6-74]]

^<<v13-6-74,74>>^ and from the tribe of Ashʹer, Maʹshal with its pastures, Abʹdon with its pastures,

[[v13-6-75]]

^<<v13-6-75,75>>^ Huʹkok with its pastures, and Reʹhob with its pastures;

[[v13-6-76]]

^<<v13-6-76,76>>^ and from the tribe of Naphʹta·li, Keʹdesh in Galʹi·lee with its pastures, Hamʹmon with its pastures, and Kir·i·a·thaʹim with its pastures.

[[v13-6-77]]

^<<v13-6-77,77>>^ To the rest of the Me·rarʹites they assigned from the tribe of Zebʹu·lun, Rimʹmo·no with its pastures, Taʹbor with its pastures;

[[v13-6-78]]

^<<v13-6-78,78>>^ and in the region of the Jordan at Jerʹi·cho, to the east of the Jordan, from the tribe of Reuʹben, they were given Beʹzer in the wilderness with its pastures, Jaʹhaz with its pastures,

[[v13-6-79]]

^<<v13-6-79,79>>^ Kedʹe·moth with its pastures, and Mephʹa·ath with its pastures;

[[v13-6-80]]

^<<v13-6-80,80>>^ and from the tribe of Gad, Raʹmoth in Gilʹe·ad with its pastures, Ma·ha·naʹim with its pastures,

[[v13-6-81]]

^<<v13-6-81,81>>^ Heshʹbon with its pastures, and Jaʹzer with its pastures.

'''

xref:013-1-chronicles/013-1-chronicles-005.adoc#v13-5-0[&#60; Capítulo Anterior] | <<v13-6-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-007.adoc#v13-7-0[Próximo Capítulo &#62;]