include::./index.adoc[]

[[v13-11-0]]
=== The First of Chronicles, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-11-1]]

^<<v13-11-1,1>>^ In time all the Israelites gathered to David at Hebʹron and said: “Look! We are your own bone and flesh.^&#42;1^

[NOTE]
====
. Or “your blood relatives.”
====

[[v13-11-2]]

^<<v13-11-2,2>>^ In times past while Saul was king, you were the one who was leading Israel on its campaigns.^&#42;1^ And Jehovah your God said to you: ‘You will shepherd my people Israel, and you will become leader over my people Israel.’”

[NOTE]
====
. Lit., “the one bringing out and the one bringing in Israel.”
====

[[v13-11-3]]

^<<v13-11-3,3>>^ So all the elders of Israel came to the king at Hebʹron, and David made a covenant with them in Hebʹron before Jehovah. Then they anointed David as king over Israel, according to Jehovah’s word through Samuel.

[[v13-11-4]]

^<<v13-11-4,4>>^ Later David and all Israel set out for Jerusalem, that is, Jeʹbus, where the Jebʹu·sites were inhabiting the land.

[[v13-11-5]]

^<<v13-11-5,5>>^ The inhabitants of Jeʹbus taunted David: “You will never come in here!” However, David captured the stronghold of Zion, which is now the City of David.

[[v13-11-6]]

^<<v13-11-6,6>>^ So David said: “Whoever is the first to strike the Jebʹu·sites will become chief^&#42;1^ and prince.” And Joʹab the son of Ze·ruʹiah went up first, and he became the chief.

[NOTE]
====
. Lit., “head.”
====

[[v13-11-7]]

^<<v13-11-7,7>>^ Then David took up residence in the stronghold. That is why they called it the City of David.

[[v13-11-8]]

^<<v13-11-8,8>>^ He began to build up the city all around, from the Mound^&#42;1^ to the areas around it, and Joʹab restored the rest of the city.

[NOTE]
====
. Or “Millo.” A Hebrew term meaning “fill.”
====

[[v13-11-9]]

^<<v13-11-9,9>>^ Thus David became greater and greater, and Jehovah of armies was with him.

[[v13-11-10]]

^<<v13-11-10,10>>^ Now these are the heads of David’s mighty warriors, who gave him strong support in his kingship, together with all Israel, to make him king according to Jehovah’s word concerning Israel.

[[v13-11-11]]

^<<v13-11-11,11>>^ This is the list of David’s mighty warriors: Ja·shoʹbe·am the son of a Hachʹmon·ite, the head of the three. He brandished his spear over 300 slain at one time.

[[v13-11-12]]

^<<v13-11-12,12>>^ Next to him was El·e·aʹzar the son of Doʹdo the A·hoʹhite. He was among the three mighty warriors.

[[v13-11-13]]

^<<v13-11-13,13>>^ He was with David at Pas-damʹmim, where the Phi·lisʹtines had gathered together for war. Now there was a plot of land full of barley, and the people had fled because of the Phi·lisʹtines.

[[v13-11-14]]

^<<v13-11-14,14>>^ But he took his stand in the middle of the field and defended it and kept striking down the Phi·lisʹtines, so that Jehovah brought about a great victory.^&#42;1^

[NOTE]
====
. Or “salvation.”
====

[[v13-11-15]]

^<<v13-11-15,15>>^ Three of the 30 headmen went down to the rock, to David at the cave of A·dulʹlam, while a Phi·lisʹtine army was camped in the Valley^&#42;1^ of Rephʹa·im.

[NOTE]
====
. Or “Low Plain.”
====

[[v13-11-16]]

^<<v13-11-16,16>>^ David was then in the stronghold, and a garrison of the Phi·lisʹtines was in Bethʹle·hem.

[[v13-11-17]]

^<<v13-11-17,17>>^ Then David expressed his longing: “If only I could have a drink of the water from the cistern by the gate of Bethʹle·hem!”

[[v13-11-18]]

^<<v13-11-18,18>>^ At that the three forced their way into the camp of the Phi·lisʹtines and drew water from the cistern by the gate of Bethʹle·hem and brought it to David; but David refused to drink it and poured it out to Jehovah.

[[v13-11-19]]

^<<v13-11-19,19>>^ He said: “It is unthinkable on my part from the standpoint of my God to do this! Should I drink the blood of these men who risked their lives?^&#42;1^ For it was at the risk of their lives^&#42;2^ that they brought it.” So he refused to drink it. These are the things that his three mighty warriors did.

[NOTE]
====
. Or “souls.”
. Or “souls.”
====

[[v13-11-20]]

^<<v13-11-20,20>>^ A·bishʹai the brother of Joʹab became head of another three; he brandished his spear over 300 slain, and he had a reputation like the three.

[[v13-11-21]]

^<<v13-11-21,21>>^ Of the other three, he was more distinguished than two of them, and he was their chief; yet he did not attain to the rank of the first three.

[[v13-11-22]]

^<<v13-11-22,22>>^ Be·naiʹah the son of Je·hoiʹa·da was a courageous man^&#42;1^ who performed many exploits in Kabʹze·el. He struck down the two sons of Arʹi·el of Moʹab, and he descended into a waterpit on a snowy day and killed a lion.

[NOTE]
====
. Lit., “the son of a man of valor.”
====

[[v13-11-23]]

^<<v13-11-23,23>>^ He also struck down an Egyptian man of extraordinary size—five cubits^&#42;1^ tall. Though the Egyptian had a spear in his hand like the beam of loom workers, he went against him with a rod and snatched the spear away from the Egyptian’s hand and killed him with his own spear.

[NOTE]
====
. His height was about 2.23 m (7.3 ft). See App. B14.
====

[[v13-11-24]]

^<<v13-11-24,24>>^ These things Be·naiʹah the son of Je·hoiʹa·da did, and he had a reputation like that of the three mighty warriors.

[[v13-11-25]]

^<<v13-11-25,25>>^ Although he was distinguished even more than the thirty, he did not attain to the rank of the three. However, David appointed him over his own bodyguard.

[[v13-11-26]]

^<<v13-11-26,26>>^ The mighty warriors of the military forces were Asʹa·hel the brother of Joʹab, El·haʹnan the son of Doʹdo of Bethʹle·hem,

[[v13-11-27]]

^<<v13-11-27,27>>^ Shamʹmoth the Haʹro·rite, Heʹlez the Pelʹo·nite,

[[v13-11-28]]

^<<v13-11-28,28>>^ Iʹra the son of Ikʹkesh the Te·koʹite, Abi-eʹzer the Anʹa·thoth·ite,

[[v13-11-29]]

^<<v13-11-29,29>>^ Sibʹbe·cai the Huʹshath·ite, Iʹlai the A·hoʹhite,

[[v13-11-30]]

^<<v13-11-30,30>>^ Maʹha·rai the Ne·tophʹa·thite, Heʹled the son of Baʹa·nah the Ne·tophʹa·thite,

[[v13-11-31]]

^<<v13-11-31,31>>^ Iʹthai the son of Riʹbai of Gibʹe·ah of the Benʹja·min·ites, Be·naiʹah the Pirʹa·thon·ite,

[[v13-11-32]]

^<<v13-11-32,32>>^ Huʹrai of the wadis^&#42;1^ of Gaʹash, A·biʹel the Arʹbath·ite,

[NOTE]
====
. See Glossary.
====

[[v13-11-33]]

^<<v13-11-33,33>>^ Azʹma·veth the Ba·haʹrum·ite, E·liʹah·ba the Sha·alʹbo·nite,

[[v13-11-34]]

^<<v13-11-34,34>>^ the sons of Haʹshem the Giʹzo·nite, Jonʹa·than the son of Shaʹgee the Harʹa·rite,

[[v13-11-35]]

^<<v13-11-35,35>>^ A·hiʹam the son of Saʹcar the Harʹa·rite, E·liʹphal the son of Ur,

[[v13-11-36]]

^<<v13-11-36,36>>^ Heʹpher the Me·cheʹrath·ite, A·hiʹjah the Pelʹo·nite,

[[v13-11-37]]

^<<v13-11-37,37>>^ Hezʹro the Carʹmel·ite, Naʹa·rai the son of Ezʹbai,

[[v13-11-38]]

^<<v13-11-38,38>>^ Joel the brother of Nathan, Mibʹhar the son of Hagʹri,

[[v13-11-39]]

^<<v13-11-39,39>>^ Zeʹlek the Amʹmon·ite, Naʹha·rai the Be·rothʹite, the armor-bearer of Joʹab the son of Ze·ruʹiah;

[[v13-11-40]]

^<<v13-11-40,40>>^ Iʹra the Ithʹrite, Gaʹreb the Ithʹrite,

[[v13-11-41]]

^<<v13-11-41,41>>^ U·riʹah the Hitʹtite, Zaʹbad the son of Ahʹlai,

[[v13-11-42]]

^<<v13-11-42,42>>^ Adʹi·na the son of Shiʹza the Reuʹben·ite, a head of the Reuʹben·ites, and 30 with him;

[[v13-11-43]]

^<<v13-11-43,43>>^ Haʹnan the son of Maʹa·cah, Joshʹa·phat the Mithʹnite,

[[v13-11-44]]

^<<v13-11-44,44>>^ Uz·ziʹa the Ashʹte·rath·ite, Shaʹma and Je·iʹel, the sons of Hoʹtham the A·roʹer·ite;

[[v13-11-45]]

^<<v13-11-45,45>>^ Je·diʹa·el the son of Shimʹri, and Joʹha his brother the Tiʹzite;

[[v13-11-46]]

^<<v13-11-46,46>>^ Eʹli·el the Maʹha·vite, Jerʹi·bai and Josh·a·viʹah the sons of Elʹna·am, and Ithʹmah the Moʹab·ite;

[[v13-11-47]]

^<<v13-11-47,47>>^ Eʹli·el, Oʹbed, and Ja·a·siʹel the Me·zoʹba·ite.

'''

xref:013-1-chronicles/013-1-chronicles-010.adoc#v13-10-0[&#60; Capítulo Anterior] | <<v13-11-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-012.adoc#v13-12-0[Próximo Capítulo &#62;]