include::./index.adoc[]

[[v13-22-0]]
=== The First of Chronicles, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v13-22-1]]

^<<v13-22-1,1>>^ David then said: “This is the house of Jehovah the true God, and this is an altar for burnt offering for Israel.”

[[v13-22-2]]

^<<v13-22-2,2>>^ David then gave orders to bring together the foreign residents who were in the land of Israel, and he assigned them to be stonecutters to cut and shape stones for building the house of the true God.

[[v13-22-3]]

^<<v13-22-3,3>>^ David also prepared iron in great quantity for nails for the doors of the gates and for clamps, and so much copper that it was beyond weighing,

[[v13-22-4]]

^<<v13-22-4,4>>^ and also cedar timbers without number, for the Si·doʹni·ans and the Tyrʹi·ans brought great quantities of cedar timbers to David.

[[v13-22-5]]

^<<v13-22-5,5>>^ And David said: “My son Solʹo·mon is young and inexperienced,^&#42;1^ and the house to be built for Jehovah is to be exceedingly magnificent, so that its fame and beauty will be known in all lands. Therefore, I will make preparation for him.” So David prepared materials in great quantity before his death.

[NOTE]
====
. Or “delicate.”
====

[[v13-22-6]]

^<<v13-22-6,6>>^ Moreover, he summoned his son Solʹo·mon and instructed him to build a house for Jehovah the God of Israel.

[[v13-22-7]]

^<<v13-22-7,7>>^ David told his son Solʹo·mon: “As for me, it was my heart’s desire to build a house for the name of Jehovah my God.

[[v13-22-8]]

^<<v13-22-8,8>>^ But Jehovah’s word came to me, saying, ‘You have shed a great deal of blood, and you have fought great wars. You will not build a house for my name, for you have shed a great deal of blood on the earth before me.

[[v13-22-9]]

^<<v13-22-9,9>>^ Look! You will have a son who will be a man of peace,^&#42;1^ and I will give him rest from all his enemies who surround him, for Solʹo·mon^&#42;2^ will be his name and I will grant Israel peace and quiet in his days.

[NOTE]
====
. Lit., “rest.”
. From a Hebrew word meaning “Peace.”
====

[[v13-22-10]]

^<<v13-22-10,10>>^ He is the one who will build a house for my name. He will become my son, and I will be his father. I will firmly establish the throne of his kingship over Israel forever.’

[[v13-22-11]]

^<<v13-22-11,11>>^ “Now, my son, may Jehovah be with you, and may you be successful and build the house of Jehovah your God, just as he has spoken concerning you.

[[v13-22-12]]

^<<v13-22-12,12>>^ Only may Jehovah give you discretion and understanding when he gives you authority over Israel, so that you may keep the law of Jehovah your God.

[[v13-22-13]]

^<<v13-22-13,13>>^ Then you will be successful if you carefully observe the regulations and the judgments that Jehovah ordered Moses to give Israel. Be courageous and strong. Do not be afraid or be terrified.

[[v13-22-14]]

^<<v13-22-14,14>>^ Here I have taken great pains to prepare for Jehovah’s house 100,000 talents^&#42;1^ of gold and 1,000,000 talents of silver and such great quantities of copper and iron that they cannot be weighed, and I have prepared timbers and stones, but you will add to them.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v13-22-15]]

^<<v13-22-15,15>>^ A great number of workmen are with you—stonecutters, stonemasons, woodworkers, and all kinds of skilled workers.

[[v13-22-16]]

^<<v13-22-16,16>>^ The gold, silver, copper, and iron are beyond measure. Get up and begin the work, and may Jehovah be with you.”

[[v13-22-17]]

^<<v13-22-17,17>>^ David then ordered all the princes of Israel to help his son Solʹo·mon:

[[v13-22-18]]

^<<v13-22-18,18>>^ “Is not Jehovah your God with you, and has he not given you rest on every side? For he handed over to me the inhabitants of the land, and the land has been subdued before Jehovah and before his people.

[[v13-22-19]]

^<<v13-22-19,19>>^ Now determine with all your heart and soul^&#42;1^ to seek Jehovah your God, and start building the sanctuary of Jehovah the true God, in order to bring the ark of the covenant of Jehovah and the holy utensils of the true God to the house built for the name of Jehovah.”

[NOTE]
====
. See Glossary.
====

'''

xref:013-1-chronicles/013-1-chronicles-021.adoc#v13-21-0[&#60; Capítulo Anterior] | <<v13-22-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-023.adoc#v13-23-0[Próximo Capítulo &#62;]