include::./index.adoc[]

[[v54-4-0]]
=== The First to Timothy, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v54-4-1]]

^<<v54-4-1,1>>^ However, the inspired word^&#42;1^ clearly says that in later times some will fall away from the faith, paying attention to misleading inspired statements^&#42;2^ and teachings of demons,

[NOTE]
====
. Lit., “the spirit.”
. Lit., “misleading spirits.”
====

[[v54-4-2]]

^<<v54-4-2,2>>^ by means of the hypocrisy of men who speak lies, whose conscience is seared as with a branding iron.

[[v54-4-3]]

^<<v54-4-3,3>>^ They forbid marriage and command people to abstain from foods that God created to be partaken of with thanksgiving by those who have faith and accurately know the truth.

[[v54-4-4]]

^<<v54-4-4,4>>^ For every creation of God is fine, and nothing is to be rejected if it is received with thanksgiving,

[[v54-4-5]]

^<<v54-4-5,5>>^ for it is sanctified through God’s word and prayer over it.

[[v54-4-6]]

^<<v54-4-6,6>>^ By giving this counsel to the brothers, you will be a fine minister of Christ Jesus, one nourished with the words of the faith and of the fine teaching that you have followed closely.

[[v54-4-7]]

^<<v54-4-7,7>>^ But reject irreverent false stories, like those told by old women. On the other hand, train yourself with godly devotion as your aim.

[[v54-4-8]]

^<<v54-4-8,8>>^ For physical training^&#42;1^ is beneficial for a little, but godly devotion is beneficial for all things, as it holds promise of the life now and the life that is to come.

[NOTE]
====
. Or “exercise.”
====

[[v54-4-9]]

^<<v54-4-9,9>>^ That statement is trustworthy and deserves full acceptance.

[[v54-4-10]]

^<<v54-4-10,10>>^ This is why we are working hard and exerting ourselves, because we have rested our hope on a living God, who is a Savior of all sorts of men, especially of faithful ones.

[[v54-4-11]]

^<<v54-4-11,11>>^ Keep on giving these commands and teaching them.

[[v54-4-12]]

^<<v54-4-12,12>>^ Never let anyone look down on your youth. Instead, become an example to the faithful ones in speaking, in conduct, in love, in faith, in chasteness.^&#42;1^

[NOTE]
====
. Or “purity.”
====

[[v54-4-13]]

^<<v54-4-13,13>>^ Until I come, continue applying yourself to public reading, to exhortation,^&#42;1^ to teaching.

[NOTE]
====
. Or “encouragement.”
====

[[v54-4-14]]

^<<v54-4-14,14>>^ Do not neglect the gift in you that was given you through a prophecy when the body of elders laid their hands on you.

[[v54-4-15]]

^<<v54-4-15,15>>^ Ponder over^&#42;1^ these things; be absorbed in them, so that your advancement may be plainly seen by all people.

[NOTE]
====
. Or “Meditate on.”
====

[[v54-4-16]]

^<<v54-4-16,16>>^ Pay constant attention to yourself and to your teaching. Persevere in these things, for by doing this you will save both yourself and those who listen to you.

'''

xref:054-1-timothy/054-1-timothy-003.adoc#v54-3-0[&#60; Capítulo Anterior] | <<v54-4-0,Topo>> | xref:054-1-timothy/054-1-timothy-005.adoc#v54-5-0[Próximo Capítulo &#62;]