include::./index.adoc[]

[[v54-1-0]]
=== The First to Timothy, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v54-1-1]]

^<<v54-1-1,1>>^ Paul, an apostle of Christ Jesus by the command of God our Savior and of Christ Jesus, our hope,

[[v54-1-2]]

^<<v54-1-2,2>>^ to Timothy,^&#42;1^ a genuine child in the faith:
May you have undeserved kindness and mercy and peace from God the Father and Christ Jesus our Lord.

[NOTE]
====
. Meaning “One Who Honors God.”
====

[[v54-1-3]]

^<<v54-1-3,3>>^ Just as I encouraged you to stay in Ephʹe·sus when I was about to go to Mac·e·doʹni·a, so I do now, in order for you to command certain ones not to teach different doctrine,

[[v54-1-4]]

^<<v54-1-4,4>>^ nor to pay attention to false stories and to genealogies. Such things end up in nothing useful but merely give rise to speculations rather than providing anything from God in connection with faith.

[[v54-1-5]]

^<<v54-1-5,5>>^ Really, the objective of this instruction^&#42;1^ is love out of a clean heart and out of a good conscience and out of faith without hypocrisy.

[NOTE]
====
. Or “mandate; order.”
====

[[v54-1-6]]

^<<v54-1-6,6>>^ By deviating from these things, some have been turned aside to meaningless talk.

[[v54-1-7]]

^<<v54-1-7,7>>^ They want to be teachers of law, but they do not understand either the things they are saying or the things they insist on so strongly.

[[v54-1-8]]

^<<v54-1-8,8>>^ Now we know that the Law is fine if one applies it properly,^&#42;1^

[NOTE]
====
. Lit., “lawfully.”
====

[[v54-1-9]]

^<<v54-1-9,9>>^ recognizing that law is made, not for a righteous man, but for those who are lawless and rebellious, ungodly and sinners, disloyal^&#42;1^ and profane, murderers of fathers and murderers of mothers, manslayers,

[NOTE]
====
. Or “lacking loyal love.”
====

[[v54-1-10]]

^<<v54-1-10,10>>^ sexually immoral people,^&#42;1^ men who practice homosexuality,^&#42;2^ kidnappers, liars, perjurers,^&#42;3^ and everything else that is in opposition to the wholesome^&#42;4^ teaching

[NOTE]
====
. See Glossary, “Sexual immorality.”
. Or “men who have sex with men.” Lit., “men who lie with men.”
. Or “those who swear falsely.”
. Or “healthful; beneficial.”
====

[[v54-1-11]]

^<<v54-1-11,11>>^ according to the glorious good news of the happy God, with which I was entrusted.

[[v54-1-12]]

^<<v54-1-12,12>>^ I am grateful to Christ Jesus our Lord, who imparted power to me, because he considered me faithful by assigning me to a ministry,

[[v54-1-13]]

^<<v54-1-13,13>>^ although formerly I was a blasphemer and a persecutor and an insolent man. Nevertheless, I was shown mercy because I acted in ignorance and with a lack of faith.

[[v54-1-14]]

^<<v54-1-14,14>>^ But the undeserved kindness of our Lord abounded exceedingly along with faith and the love that is in Christ Jesus.

[[v54-1-15]]

^<<v54-1-15,15>>^ This saying is trustworthy and deserving of full acceptance: Christ Jesus came into the world to save sinners. Of these, I am foremost.

[[v54-1-16]]

^<<v54-1-16,16>>^ Nevertheless, I was shown mercy so that by means of me as the foremost case, Christ Jesus might demonstrate all his patience, making me an example to those who are going to rest their faith on him for everlasting life.

[[v54-1-17]]

^<<v54-1-17,17>>^ Now to the King of eternity, incorruptible, invisible, the only God, be honor and glory forever and ever. Amen.

[[v54-1-18]]

^<<v54-1-18,18>>^ This instruction^&#42;1^ I entrust to you, my child Timothy, in harmony with the prophecies that were made about you, that by these you may go on waging the fine warfare,

[NOTE]
====
. Or “mandate; order.”
====

[[v54-1-19]]

^<<v54-1-19,19>>^ holding faith and a good conscience, which some have thrust aside, resulting in the shipwreck of their faith.

[[v54-1-20]]

^<<v54-1-20,20>>^ Hy·me·naeʹus and Alexander are among these, and I have handed them over to Satan so that they may be taught by discipline not to blaspheme.

'''

xref:053-2-thessalonians/053-2-thessalonians-003.adoc#v53-3-0[&#60; Capítulo Anterior] | <<v54-1-0,Topo>> | xref:054-1-timothy/054-1-timothy-002.adoc#v54-2-0[Próximo Capítulo &#62;]