include::./index.adoc[]

[[v54-6-0]]
=== The First to Timothy, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v54-6-1]]

^<<v54-6-1,1>>^ Let those who are under the yoke of slavery keep on considering their owners worthy of full honor, so that the name of God and the teaching may never be spoken of injuriously.

[[v54-6-2]]

^<<v54-6-2,2>>^ Moreover, let those having believing owners not be disrespectful to them because they are brothers. Rather, they should serve more readily, because those receiving the benefit of their good service are believers and beloved.
Keep on teaching these things and giving these exhortations.

[[v54-6-3]]

^<<v54-6-3,3>>^ If any man teaches another doctrine and does not agree with the wholesome^&#42;1^ instruction, which is from our Lord Jesus Christ, nor with the teaching that is in harmony with godly devotion,

[NOTE]
====
. Or “healthful; beneficial.”
====

[[v54-6-4]]

^<<v54-6-4,4>>^ he is puffed up with pride and does not understand anything. He is obsessed^&#42;1^ with arguments and debates about words. These things give rise to envy, strife, slander,^&#42;2^ wicked suspicions,

[NOTE]
====
. Or “has an unhealthy fascination.”
. Or “abusive speeches.”
====

[[v54-6-5]]

^<<v54-6-5,5>>^ constant disputes about minor matters by men who are corrupted in mind and deprived of the truth, thinking that godly devotion is a means of gain.

[[v54-6-6]]

^<<v54-6-6,6>>^ To be sure, there is great gain in godly devotion along with contentment.^&#42;1^

[NOTE]
====
. Lit., “along with self-sufficiency.”
====

[[v54-6-7]]

^<<v54-6-7,7>>^ For we have brought nothing into the world, and neither can we carry anything out.

[[v54-6-8]]

^<<v54-6-8,8>>^ So, having food^&#42;1^ and clothing,^&#42;2^ we will be content with these things.

[NOTE]
====
. Or “sustenance.”
. Or possibly, “shelter.” Lit., “covering.”
====

[[v54-6-9]]

^<<v54-6-9,9>>^ But those who are determined to be rich fall into temptation and a snare and many senseless and harmful desires that plunge men into destruction and ruin.

[[v54-6-10]]

^<<v54-6-10,10>>^ For the love of money is a root of all sorts of injurious things, and by reaching out for this love some have been led astray from the faith and have stabbed themselves all over with many pains.

[[v54-6-11]]

^<<v54-6-11,11>>^ However, you, O man of God, flee from these things. But pursue righteousness, godly devotion, faith, love, endurance, and mildness.

[[v54-6-12]]

^<<v54-6-12,12>>^ Fight the fine fight of the faith; get a firm hold on the everlasting life for which you were called and you offered the fine public declaration in front of many witnesses.

[[v54-6-13]]

^<<v54-6-13,13>>^ Before God, who preserves all things alive, and Christ Jesus, who as a witness made the fine public declaration before Pontius Pilate, I give you orders

[[v54-6-14]]

^<<v54-6-14,14>>^ to observe the commandment in a spotless and irreprehensible way until the manifestation of our Lord Jesus Christ,

[[v54-6-15]]

^<<v54-6-15,15>>^ which the happy and only Potentate will show in its own appointed times. He is the King of those who rule as kings and Lord of those who rule as lords,

[[v54-6-16]]

^<<v54-6-16,16>>^ the one alone having immortality, who dwells in unapproachable light, whom no man has seen or can see. To him be honor and eternal might. Amen.

[[v54-6-17]]

^<<v54-6-17,17>>^ Instruct^&#42;1^ those who are rich in the present system of things^&#42;2^ not to be arrogant,^&#42;3^ and to place their hope, not on uncertain riches, but on God, who richly provides us with all the things we enjoy.

[NOTE]
====
. Or “Order.”
. Or “present age.” See Glossary.
. Or “high-minded.”
====

[[v54-6-18]]

^<<v54-6-18,18>>^ Tell them to work at good, to be rich in fine works, to be generous,^&#42;1^ ready to share,

[NOTE]
====
. Or “liberal.”
====

[[v54-6-19]]

^<<v54-6-19,19>>^ safely treasuring up for themselves a fine foundation for the future, so that they may get a firm hold on the real life.

[[v54-6-20]]

^<<v54-6-20,20>>^ Timothy, guard what has been entrusted to you, turning away from the empty speeches that violate what is holy and from the contradictions of the falsely called “knowledge.”

[[v54-6-21]]

^<<v54-6-21,21>>^ By making a show of such knowledge, some have deviated from the faith.
May the undeserved kindness be with you.

'''

xref:054-1-timothy/054-1-timothy-005.adoc#v54-5-0[&#60; Capítulo Anterior] | <<v54-6-0,Topo>> | xref:055-2-timothy/055-2-timothy-001.adoc#v55-1-0[Próximo Capítulo &#62;]