include::./index.adoc[]

[[v54-5-0]]
=== The First to Timothy, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v54-5-1]]

^<<v54-5-1,1>>^ Do not severely criticize an older man. On the contrary, appeal to him as a father, to younger men as brothers,

[[v54-5-2]]

^<<v54-5-2,2>>^ to older women as mothers, to younger women as sisters, with all chasteness.

[[v54-5-3]]

^<<v54-5-3,3>>^ Give consideration to^&#42;1^ widows who are truly widows.^&#42;2^

[NOTE]
====
. Lit., “Honor.”
. Or “widows who are truly in need”; that is, with no one to support them.
====

[[v54-5-4]]

^<<v54-5-4,4>>^ But if any widow has children or grandchildren, let these learn first to practice godly devotion in their own household and to repay their parents and grandparents what is due them, for this is acceptable in God’s sight.

[[v54-5-5]]

^<<v54-5-5,5>>^ Now the woman who is truly a widow and left destitute has put her hope in God and continues in supplications and prayers night and day.

[[v54-5-6]]

^<<v54-5-6,6>>^ But the one who gives herself to sensual gratification is dead though she is living.

[[v54-5-7]]

^<<v54-5-7,7>>^ So keep on giving these instructions,^&#42;1^ so that they may be irreprehensible.

[NOTE]
====
. Or “commands.”
====

[[v54-5-8]]

^<<v54-5-8,8>>^ Certainly if anyone does not provide for those who are his own, and especially for those who are members of his household, he has disowned the faith and is worse than a person without faith.

[[v54-5-9]]

^<<v54-5-9,9>>^ A widow is to be put on the list if she is not less than 60 years old, was the wife of one husband,

[[v54-5-10]]

^<<v54-5-10,10>>^ having a reputation for fine works, if she raised children, if she practiced hospitality, if she washed the feet of holy ones, if she assisted the afflicted, if she devoted herself to every good work.

[[v54-5-11]]

^<<v54-5-11,11>>^ On the other hand, do not put younger widows on the list, for when their sexual desires come between them and the Christ, they want to marry.

[[v54-5-12]]

^<<v54-5-12,12>>^ And they will incur judgment because they have abandoned their first expression of faith.^&#42;1^

[NOTE]
====
. Or “their previous promise.”
====

[[v54-5-13]]

^<<v54-5-13,13>>^ At the same time they also learn to be unoccupied, going around from one house to another; yes, not only unoccupied but also gossipers and meddlers in other people’s affairs, talking about things they should not.

[[v54-5-14]]

^<<v54-5-14,14>>^ Therefore, I desire the younger widows to marry, to bear children, to manage a household, to give no opportunity to the opposer to criticize.

[[v54-5-15]]

^<<v54-5-15,15>>^ In fact, some have already been turned aside to follow Satan.

[[v54-5-16]]

^<<v54-5-16,16>>^ If any believing woman has relatives who are widows, let her assist them so that the congregation is not burdened. Then it can assist those who are truly widows.^&#42;1^

[NOTE]
====
. Or “widows who are truly in need”; that is, with no one to support them.
====

[[v54-5-17]]

^<<v54-5-17,17>>^ Let the elders who preside in a fine way be considered worthy of double honor, especially those who work hard in speaking and teaching.

[[v54-5-18]]

^<<v54-5-18,18>>^ For the scripture says, “You must not muzzle a bull when it is threshing out the grain,” also, “The worker is worthy of his wages.”

[[v54-5-19]]

^<<v54-5-19,19>>^ Do not accept an accusation against an older man^&#42;1^ except on the evidence of two or three witnesses.

[NOTE]
====
. Or “an elder.”
====

[[v54-5-20]]

^<<v54-5-20,20>>^ Reprove before all onlookers those who practice sin, as a warning to the rest.^&#42;1^

[NOTE]
====
. Lit., “that the rest may have fear.”
====

[[v54-5-21]]

^<<v54-5-21,21>>^ I solemnly charge you before God and Christ Jesus and the chosen angels to observe these instructions without any prejudice or partiality.

[[v54-5-22]]

^<<v54-5-22,22>>^ Never lay your hands hastily on any man;^&#42;1^ neither become a sharer in the sins of others; keep yourself chaste.

[NOTE]
====
. That is, do not appoint any man hastily.
====

[[v54-5-23]]

^<<v54-5-23,23>>^ Do not drink water any longer,^&#42;1^ but take a little wine for the sake of your stomach and your frequent cases of sickness.

[NOTE]
====
. Or “Stop drinking just water.”
====

[[v54-5-24]]

^<<v54-5-24,24>>^ The sins of some men are publicly known, leading directly to judgment, but those of other men become evident later.

[[v54-5-25]]

^<<v54-5-25,25>>^ In the same way also, the fine works are publicly known and those that are otherwise cannot be kept hidden.

'''

xref:054-1-timothy/054-1-timothy-004.adoc#v54-4-0[&#60; Capítulo Anterior] | <<v54-5-0,Topo>> | xref:054-1-timothy/054-1-timothy-006.adoc#v54-6-0[Próximo Capítulo &#62;]