include::./index.adoc[]

[[v54-3-0]]
=== The First to Timothy, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v54-3-1]]

^<<v54-3-1,1>>^ This statement is trustworthy: If a man is reaching out to be an overseer, he is desirous of a fine work.

[[v54-3-2]]

^<<v54-3-2,2>>^ The overseer should therefore be irreprehensible, a husband of one wife, moderate in habits, sound in mind,^&#42;1^ orderly, hospitable, qualified to teach,

[NOTE]
====
. Or “have good judgment; be sensible.”
====

[[v54-3-3]]

^<<v54-3-3,3>>^ not a drunkard, not violent,^&#42;1^ but reasonable, not quarrelsome, not a lover of money,

[NOTE]
====
. Or “a smiter.”
====

[[v54-3-4]]

^<<v54-3-4,4>>^ a man presiding over^&#42;1^ his own household in a fine manner, having his children in subjection with all seriousness

[NOTE]
====
. Or “managing.”
====

[[v54-3-5]]

^<<v54-3-5,5>>^ (for if any man does not know how to preside over^&#42;1^ his own household, how will he care for the congregation of God?),

[NOTE]
====
. Or “manage.”
====

[[v54-3-6]]

^<<v54-3-6,6>>^ not a newly converted man, for fear that he might get puffed up with pride and fall into the judgment passed on the Devil.

[[v54-3-7]]

^<<v54-3-7,7>>^ Moreover, he should also have a fine testimony^&#42;1^ from outsiders so that he does not fall into reproach^&#42;2^ and a snare of the Devil.

[NOTE]
====
. Or “a good reputation.”
. Or “disgrace.”
====

[[v54-3-8]]

^<<v54-3-8,8>>^ Ministerial servants should likewise be serious, not double-tongued,^&#42;1^ not indulging in a lot of wine, not greedy of dishonest gain,

[NOTE]
====
. Or “not deceitful in speech.”
====

[[v54-3-9]]

^<<v54-3-9,9>>^ holding the sacred secret of the faith with a clean conscience.

[[v54-3-10]]

^<<v54-3-10,10>>^ Also, let these be tested as to fitness^&#42;1^ first; then let them serve as ministers, as they are free from accusation.

[NOTE]
====
. Or “tested as to whether they qualify.”
====

[[v54-3-11]]

^<<v54-3-11,11>>^ Women should likewise be serious, not slanderous, moderate in habits, faithful in all things.

[[v54-3-12]]

^<<v54-3-12,12>>^ Let ministerial servants be husbands of one wife, presiding in a fine manner over their children and their own households.

[[v54-3-13]]

^<<v54-3-13,13>>^ For the men who minister in a fine manner are acquiring for themselves a fine standing and great freeness of speech in the faith that is in Christ Jesus.

[[v54-3-14]]

^<<v54-3-14,14>>^ I am writing you these things, though I am hoping to come to you shortly,

[[v54-3-15]]

^<<v54-3-15,15>>^ but in case I am delayed, so that you may know how you ought to conduct yourself in God’s household, which is the congregation of the living God, a pillar and support of the truth.

[[v54-3-16]]

^<<v54-3-16,16>>^ Indeed, the sacred secret of this godly devotion is admittedly great: ‘He was made manifest in flesh, was declared righteous in spirit, appeared to angels, was preached about among nations, was believed upon in the world, was received up in glory.’

'''

xref:054-1-timothy/054-1-timothy-002.adoc#v54-2-0[&#60; Capítulo Anterior] | <<v54-3-0,Topo>> | xref:054-1-timothy/054-1-timothy-004.adoc#v54-4-0[Próximo Capítulo &#62;]