include::./index.adoc[]

[[v54-2-0]]
=== The First to Timothy, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v54-2-1]]

^<<v54-2-1,1>>^ First of all, then, I urge that supplications, prayers, intercessions, and thanksgiving be made concerning all sorts of men,

[[v54-2-2]]

^<<v54-2-2,2>>^ concerning kings and all those who are in high positions,^&#42;1^ so that we may go on leading a calm and quiet life with complete godly devotion and seriousness.

[NOTE]
====
. Or “in positions of authority.”
====

[[v54-2-3]]

^<<v54-2-3,3>>^ This is fine and acceptable in the sight of our Savior, God,

[[v54-2-4]]

^<<v54-2-4,4>>^ whose will is that all sorts of people should be saved and come to an accurate knowledge of truth.

[[v54-2-5]]

^<<v54-2-5,5>>^ For there is one God, and one mediator between God and men, a man, Christ Jesus,

[[v54-2-6]]

^<<v54-2-6,6>>^ who gave himself a corresponding ransom for all^&#42;1^—this is what is to be witnessed to in its own due time.

[NOTE]
====
. Or “all sorts of people.”
====

[[v54-2-7]]

^<<v54-2-7,7>>^ For the purpose of this witness I was appointed a preacher and an apostle—I am telling the truth, I am not lying—a teacher of nations in the matter of faith and truth.

[[v54-2-8]]

^<<v54-2-8,8>>^ So I desire that in every place the men carry on prayer, lifting up loyal hands, without anger and debates.

[[v54-2-9]]

^<<v54-2-9,9>>^ Likewise, the women should adorn themselves in appropriate^&#42;1^ dress, with modesty and soundness of mind,^&#42;2^ not with styles of hair braiding and gold or pearls or very expensive clothing,

[NOTE]
====
. Or “respectable.”
. Or “good judgment; sensibleness.”
====

[[v54-2-10]]

^<<v54-2-10,10>>^ but in the way that is proper for women professing devotion to God, namely, through good works.

[[v54-2-11]]

^<<v54-2-11,11>>^ Let a woman learn in silence^&#42;1^ with full submissiveness.

[NOTE]
====
. Or “quietness; calmness.”
====

[[v54-2-12]]

^<<v54-2-12,12>>^ I do not permit a woman to teach or to exercise authority over a man, but she is to remain silent.^&#42;1^

[NOTE]
====
. Or “remain calm; remain quiet.”
====

[[v54-2-13]]

^<<v54-2-13,13>>^ For Adam was formed first, then Eve.

[[v54-2-14]]

^<<v54-2-14,14>>^ Also, Adam was not deceived, but the woman was thoroughly deceived and became a transgressor.

[[v54-2-15]]

^<<v54-2-15,15>>^ However, she will be kept safe through childbearing, provided she^&#42;1^ continues in faith and love and holiness along with soundness of mind.^&#42;2^

[NOTE]
====
. Lit., “they.”
. Or “good judgment; sensibleness.”
====

'''

xref:054-1-timothy/054-1-timothy-001.adoc#v54-1-0[&#60; Capítulo Anterior] | <<v54-2-0,Topo>> | xref:054-1-timothy/054-1-timothy-003.adoc#v54-3-0[Próximo Capítulo &#62;]