include::./index.adoc[]

[[v32-4-0]]
=== Jonah, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v32-4-1]]

^<<v32-4-1,1>>^ But this was highly displeasing to Joʹnah, and he became hot with anger.

[[v32-4-2]]

^<<v32-4-2,2>>^ So he prayed to Jehovah: “Ah, now, Jehovah, was this not my concern when I was in my own land? That is why I tried to flee to Tarʹshish in the first place; for I knew that you are a compassionate^&#42;1^ and merciful God, slow to anger and abundant in loyal love, one who feels grieved over calamity.

[NOTE]
====
. Or “gracious.”
====

[[v32-4-3]]

^<<v32-4-3,3>>^ Now, O Jehovah, please take away my life,^&#42;1^ for it is better for me to die than to live.”

[NOTE]
====
. Or “soul.”
====

[[v32-4-4]]

^<<v32-4-4,4>>^ Jehovah asked: “Is it right for you to be so angry?”

[[v32-4-5]]

^<<v32-4-5,5>>^ Joʹnah then went out of the city and sat down east of the city. He made a shelter for himself there and sat in its shade to see what would happen to the city.

[[v32-4-6]]

^<<v32-4-6,6>>^ Jehovah God then provided a bottle-gourd plant^&#42;1^ to grow up over Joʹnah, to give him shade for his head and to relieve his misery. And Joʹnah was very pleased with the bottle-gourd plant.

[NOTE]
====
. Or possibly, “castor-oil plant.”
====

[[v32-4-7]]

^<<v32-4-7,7>>^ But the true God sent a worm at the break of dawn on the next day, and it attacked the bottle-gourd plant, and it withered.

[[v32-4-8]]

^<<v32-4-8,8>>^ When the sun began to shine, God also sent a scorching east wind, and the sun beat down on Joʹnah’s head, and he grew faint. He kept asking to die,^&#42;1^ and he kept saying, “It is better for me to die than to live.”

[NOTE]
====
. Or “that his soul might die.”
====

[[v32-4-9]]

^<<v32-4-9,9>>^ God asked Joʹnah: “Is it right for you to be so angry over the bottle-gourd plant?”
At that he said: “I have a right to be angry, so angry that I want to die.”

[[v32-4-10]]

^<<v32-4-10,10>>^ But Jehovah said: “You felt sorry for the bottle-gourd plant, which you did not work for, nor did you make it grow; it grew in one night and perished in one night.

[[v32-4-11]]

^<<v32-4-11,11>>^ Should I not also feel sorry for Ninʹe·veh the great city, in which there are more than 120,000 men who do not even know right from wrong,^&#42;1^ as well as their many animals?”

[NOTE]
====
. Or “know their right hand from their left.”
====

'''

xref:032-jonah/032-jonah-003.adoc#v32-3-0[&#60; Capítulo Anterior] | <<v32-4-0,Topo>> | xref:033-micah/033-micah-001.adoc#v33-1-0[Próximo Capítulo &#62;]