include::./index.adoc[]

[[v3-13-0]]
=== Leviticus, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-13-1]]

^<<v3-13-1,1>>^ Jehovah continued to speak to Moses and Aaron, saying:

[[v3-13-2]]

^<<v3-13-2,2>>^ “If a man develops on his skin^&#42;1^ a swelling, a scab, or a blotch and it could become the disease of leprosy^&#42;2^ on his skin, he must then be brought to Aaron the priest or to one of his sons, the priests.

[NOTE]
====
. Lit., “in the skin of his flesh.”
. The Hebrew word rendered “leprosy” is broad in meaning and can include various contagious skin diseases. It may also include certain infections found on clothing and in houses.
====

[[v3-13-3]]

^<<v3-13-3,3>>^ The priest will examine the infection on his skin. When the hair in the infection has turned white and the appearance of the infection is deeper than the skin, it is the disease of leprosy. The priest will examine it and declare him unclean.

[[v3-13-4]]

^<<v3-13-4,4>>^ But if the blotch on his skin is white and its appearance is not deeper than the skin and the hair has not turned white, the priest will then quarantine the infected person for seven days.

[[v3-13-5]]

^<<v3-13-5,5>>^ The priest will then examine him on the seventh day, and if it appears that the infection has stopped and has not spread on the skin, the priest will quarantine him for another seven days.

[[v3-13-6]]

^<<v3-13-6,6>>^ “The priest should examine him again on the seventh day, and if the infection has faded and has not spread in the skin, the priest will declare him clean; it was only a scab. The man will then wash his garments and be clean.

[[v3-13-7]]

^<<v3-13-7,7>>^ But if the scab^&#42;1^ has definitely spread on the skin after he appears before the priest to establish his purification, he will then appear again^&#42;2^ before the priest.

[NOTE]
====
. Or “the infection.”
. Or “a second time.”
====

[[v3-13-8]]

^<<v3-13-8,8>>^ The priest will examine it, and if the scab has spread in the skin, the priest will then declare him unclean. It is leprosy.

[[v3-13-9]]

^<<v3-13-9,9>>^ “If the disease of leprosy develops in a man, he must then be brought to the priest,

[[v3-13-10]]

^<<v3-13-10,10>>^ and the priest will examine him. If there is a white swelling on the skin and it has turned the hair white and there is an open sore in the swelling,

[[v3-13-11]]

^<<v3-13-11,11>>^ it is chronic leprosy on his skin, and the priest will declare him unclean. He should not quarantine him, for he is unclean.

[[v3-13-12]]

^<<v3-13-12,12>>^ Now if the leprosy breaks out all over the skin and the leprosy covers the person with the disease from head to foot, as far as the priest can see,

[[v3-13-13]]

^<<v3-13-13,13>>^ and the priest has examined him and sees that the leprosy has covered all his skin, he will then declare the infected person clean.^&#42;1^ All of it has turned white, and he is clean.

[NOTE]
====
. Or “not contagious.”
====

[[v3-13-14]]

^<<v3-13-14,14>>^ But whenever an open sore appears in it, he will be unclean.

[[v3-13-15]]

^<<v3-13-15,15>>^ When the priest sees the open sore, he will declare him unclean. The open sore is unclean. It is leprosy.

[[v3-13-16]]

^<<v3-13-16,16>>^ But if the open sore again turns white, he will then come to the priest.

[[v3-13-17]]

^<<v3-13-17,17>>^ The priest will examine him, and if the infection has turned white, the priest will then declare the infected person clean. He is clean.

[[v3-13-18]]

^<<v3-13-18,18>>^ “If a person develops a boil on his skin and it heals,

[[v3-13-19]]

^<<v3-13-19,19>>^ but in the place of the boil a white swelling or a reddish-white blotch has developed, he must then show himself to the priest.

[[v3-13-20]]

^<<v3-13-20,20>>^ The priest will examine it, and if it appears to be deeper than the skin and its hair has turned white, the priest will then declare him unclean. It is the disease of leprosy that has broken out in the boil.

[[v3-13-21]]

^<<v3-13-21,21>>^ But if the priest examines it and sees that there is no white hair in it and it is not deeper than the skin and appears faded, the priest will then quarantine him for seven days.

[[v3-13-22]]

^<<v3-13-22,22>>^ And if it has clearly spread on the skin, the priest will then declare him unclean. It is a disease.

[[v3-13-23]]

^<<v3-13-23,23>>^ But if the blotch stays in one place and has not spread, it is only the inflammation from the boil, and the priest will declare him clean.

[[v3-13-24]]

^<<v3-13-24,24>>^ “Or if someone has a scar from the fire and the raw flesh of the scar becomes a reddish-white blotch or a white one,

[[v3-13-25]]

^<<v3-13-25,25>>^ the priest will then examine it. If the hair in the blotch has turned white and it appears to be deeper than the skin, it is leprosy that has broken out in the scar, and the priest will declare him unclean. It is the disease of leprosy.

[[v3-13-26]]

^<<v3-13-26,26>>^ But if the priest examines it and sees that there is no white hair in the blotch and it is not deeper than the skin and it is faded, the priest will then quarantine him for seven days.

[[v3-13-27]]

^<<v3-13-27,27>>^ The priest will examine him on the seventh day, and if it has clearly spread on the skin, the priest will then declare him unclean. It is the disease of leprosy.

[[v3-13-28]]

^<<v3-13-28,28>>^ But if the blotch stays in one place and has not spread over the skin and it is faded, it is only a swelling of the scar, and the priest will declare him clean, because it is an inflammation of the scar.

[[v3-13-29]]

^<<v3-13-29,29>>^ “When a man or a woman develops an infection on the head or on the chin,

[[v3-13-30]]

^<<v3-13-30,30>>^ the priest will then examine the infection. If it appears to be deeper than the skin and the hair is yellow and thin, the priest will then declare such one unclean; it is an infection of the scalp or the beard. It is leprosy of the head or of the chin.

[[v3-13-31]]

^<<v3-13-31,31>>^ But if the priest sees that the infection does not appear to be deeper than the skin and there is no black hair in it, the priest should quarantine the infected person for seven days.

[[v3-13-32]]

^<<v3-13-32,32>>^ The priest will examine the infection on the seventh day, and if the infected area has not spread and no yellow hair has developed in it and the appearance of the infected area is not deeper than the skin,

[[v3-13-33]]

^<<v3-13-33,33>>^ the person should have himself shaved, but he will not have the infected area shaved. Then the priest will quarantine the infected person for seven days.

[[v3-13-34]]

^<<v3-13-34,34>>^ “The priest will again examine the infected area on the seventh day, and if the infection of the scalp and beard has not spread on the skin and it does not appear deeper than the skin, the priest must then declare him clean, and he should wash his garments and be clean.

[[v3-13-35]]

^<<v3-13-35,35>>^ But if the infection clearly spreads on the skin after his purification,

[[v3-13-36]]

^<<v3-13-36,36>>^ the priest will examine him, and if the infection has spread on the skin, the priest does not need to look for yellow hair; that person is unclean.

[[v3-13-37]]

^<<v3-13-37,37>>^ But if the examination shows that the infection has not spread and black hair has grown on it, the infection has been healed. He is clean, and the priest will declare him clean.

[[v3-13-38]]

^<<v3-13-38,38>>^ “If a man or a woman develops blotches on the skin^&#42;1^ and the blotches are white,

[NOTE]
====
. Lit., “in the skin of their flesh.”
====

[[v3-13-39]]

^<<v3-13-39,39>>^ the priest will examine them. If the skin blotches are faded white, it is a harmless rash that has broken out on the skin. That person is clean.

[[v3-13-40]]

^<<v3-13-40,40>>^ “If a man loses the hair of his head and becomes bald, he is clean.

[[v3-13-41]]

^<<v3-13-41,41>>^ If he loses the hair on the front of his head and becomes bald there, he is clean.

[[v3-13-42]]

^<<v3-13-42,42>>^ But if a reddish-white sore develops on the bald part of his scalp or on his forehead, it is leprosy breaking out on his scalp or on his forehead.

[[v3-13-43]]

^<<v3-13-43,43>>^ The priest will examine him, and if the swelling from the infection is reddish-white on the bald spot on top of his head or on his forehead and it looks like leprosy on his skin,

[[v3-13-44]]

^<<v3-13-44,44>>^ he is a leper. He is unclean, and the priest should declare him unclean because of the disease on his head.

[[v3-13-45]]

^<<v3-13-45,45>>^ As for the leper who has the disease, his garments should be torn and his head should be left ungroomed and he should cover over his mustache and call out, ‘Unclean, unclean!’

[[v3-13-46]]

^<<v3-13-46,46>>^ He will be unclean the whole time that he has the disease. Since he is unclean, he should live in isolation. His dwelling place will be outside the camp.

[[v3-13-47]]

^<<v3-13-47,47>>^ “If the disease of leprosy contaminates a garment, whether a woolen or a linen garment,

[[v3-13-48]]

^<<v3-13-48,48>>^ either in the warp or in the woof of the linen or of the wool, or in a skin or in anything made of skin,

[[v3-13-49]]

^<<v3-13-49,49>>^ and the yellowish-green or reddish stain from the disease contaminates the garment, a skin, the warp, the woof, or any article of skin, it is a contamination from leprosy, and it should be shown to the priest.

[[v3-13-50]]

^<<v3-13-50,50>>^ The priest will examine the disease, and he must quarantine the disease for seven days.

[[v3-13-51]]

^<<v3-13-51,51>>^ When he examines the disease on the seventh day and sees that it has spread in the garment, in the warp, in the woof, or in the skin (regardless of what the skin is used for), the disease is malignant leprosy, and it is unclean.

[[v3-13-52]]

^<<v3-13-52,52>>^ He should burn the garment or the warp or the woof in the wool or in the linen or any article of skin in which the disease has developed, for it is malignant leprosy. It should be burned in the fire.

[[v3-13-53]]

^<<v3-13-53,53>>^ “But if the priest examines it and the disease has not spread in the garment or in the warp or in the woof or in any article of skin,

[[v3-13-54]]

^<<v3-13-54,54>>^ the priest will then command that they should wash the contaminated item, and he will quarantine it for another seven days.

[[v3-13-55]]

^<<v3-13-55,55>>^ The priest will then examine the contaminated item after it has been thoroughly washed. If the appearance of the contamination has not changed, even if the disease has not spread, it is unclean. You should burn it in the fire because it has been eaten away, either from its underside or from its outside.

[[v3-13-56]]

^<<v3-13-56,56>>^ “But if the priest has examined it and the contaminated part is faded after it has been thoroughly washed, he will then tear it out of the garment or the skin or the warp or the woof.

[[v3-13-57]]

^<<v3-13-57,57>>^ However, if it still appears in another part of the garment or in the warp or in the woof or in any article of skin, it is spreading, and you should burn any contaminated item in the fire.

[[v3-13-58]]

^<<v3-13-58,58>>^ But when the contamination disappears from the garment or the warp or the woof or any article of skin that you wash, it should then be washed a second time, and it will be clean.

[[v3-13-59]]

^<<v3-13-59,59>>^ “This is the law of the disease of leprosy in a garment of wool or of linen, or in the warp or in the woof, or in any article of skin, for declaring it clean or unclean.”

'''

xref:003-leviticus/003-leviticus-012.adoc#v3-12-0[&#60; Capítulo Anterior] | <<v3-13-0,Topo>> | xref:003-leviticus/003-leviticus-014.adoc#v3-14-0[Próximo Capítulo &#62;]