include::./index.adoc[]

[[v3-12-0]]
=== Leviticus, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-12-1]]

^<<v3-12-1,1>>^ Jehovah went on to say to Moses:

[[v3-12-2]]

^<<v3-12-2,2>>^ “Tell the Israelites, ‘If a woman becomes pregnant^&#42;1^ and gives birth to a male, she will be unclean for seven days, just as she is in the days of the impurity when she is menstruating.

[NOTE]
====
. Or “conceives seed.”
====

[[v3-12-3]]

^<<v3-12-3,3>>^ On the eighth day, the flesh of his foreskin will be circumcised.

[[v3-12-4]]

^<<v3-12-4,4>>^ She will continue cleansing herself from the blood for the next 33 days. She should not touch any holy thing, and she should not come into the holy place until she fulfills the days of her purification.

[[v3-12-5]]

^<<v3-12-5,5>>^ “‘If she should give birth to a female, she will then be unclean for 14 days, just as she would be during her menstruation. She will continue cleansing herself from the blood for the next 66 days.

[[v3-12-6]]

^<<v3-12-6,6>>^ When the days of her purification for a son or a daughter are completed, she will bring a young ram in its first year for a burnt offering and a young pigeon or a turtledove for a sin offering to the entrance of the tent of meeting, to the priest.

[[v3-12-7]]

^<<v3-12-7,7>>^ He will present it before Jehovah and make atonement for her, and she will be clean from her flow of blood. This is the law about the woman who gives birth to either a male or a female.

[[v3-12-8]]

^<<v3-12-8,8>>^ But if she cannot afford a sheep, she must then take two turtledoves or two young pigeons, one for a burnt offering and one for a sin offering, and the priest will make atonement for her, and she will be clean.’”

'''

xref:003-leviticus/003-leviticus-011.adoc#v3-11-0[&#60; Capítulo Anterior] | <<v3-12-0,Topo>> | xref:003-leviticus/003-leviticus-013.adoc#v3-13-0[Próximo Capítulo &#62;]