include::./index.adoc[]

[[v3-9-0]]
=== Leviticus, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-9-1]]

^<<v3-9-1,1>>^ On the eighth day, Moses called Aaron and his sons and the elders of Israel.

[[v3-9-2]]

^<<v3-9-2,2>>^ He said to Aaron: “Take for yourself a young calf for a sin offering and a ram for a burnt offering, sound ones, and present them before Jehovah.

[[v3-9-3]]

^<<v3-9-3,3>>^ But you will say to the Israelites, ‘Take a male goat for a sin offering and a calf and a young ram, each a year old, sound ones, for a burnt offering,

[[v3-9-4]]

^<<v3-9-4,4>>^ and a bull and a ram for communion sacrifices, to sacrifice them before Jehovah, and a grain offering mixed with oil, for today Jehovah will appear to you.’”

[[v3-9-5]]

^<<v3-9-5,5>>^ So they took what Moses had commanded before the tent of meeting. Then the whole assembly came forward and stood before Jehovah.

[[v3-9-6]]

^<<v3-9-6,6>>^ And Moses said: “This is what Jehovah has commanded you to do, so that the glory of Jehovah may appear to you.”

[[v3-9-7]]

^<<v3-9-7,7>>^ Then Moses said to Aaron: “Approach the altar and present your sin offering and your burnt offering, and make atonement in your own behalf and in behalf of your house; and present the offering of the people, and make atonement in their behalf, just as Jehovah has commanded.”

[[v3-9-8]]

^<<v3-9-8,8>>^ Aaron immediately approached the altar and slaughtered the calf of the sin offering that was for him.

[[v3-9-9]]

^<<v3-9-9,9>>^ Then Aaron’s sons presented the blood to him, and he dipped his finger in the blood and put it on the horns of the altar, and he poured the rest of the blood at the base of the altar.

[[v3-9-10]]

^<<v3-9-10,10>>^ He made the fat and the kidneys and the appendage of the liver from the sin offering smoke on the altar, just as Jehovah had commanded Moses.

[[v3-9-11]]

^<<v3-9-11,11>>^ And he burned the flesh and the skin with fire outside the camp.

[[v3-9-12]]

^<<v3-9-12,12>>^ Then he slaughtered the burnt offering, and Aaron’s sons handed him the blood, and he sprinkled it on all sides of the altar.

[[v3-9-13]]

^<<v3-9-13,13>>^ They handed him the pieces of the burnt offering along with the head, and he made them smoke on the altar.

[[v3-9-14]]

^<<v3-9-14,14>>^ Further, he washed the intestines and the shanks and made them smoke on the burnt offering on the altar.

[[v3-9-15]]

^<<v3-9-15,15>>^ He then presented the offering of the people and took the goat of the sin offering that was for the people and slaughtered it and made a sin offering with it like the first one.

[[v3-9-16]]

^<<v3-9-16,16>>^ And he presented the burnt offering and handled it according to the regular procedure.

[[v3-9-17]]

^<<v3-9-17,17>>^ He next presented the grain offering, filling his hand with some of it and making it smoke on the altar, in addition to the burnt offering of the morning.

[[v3-9-18]]

^<<v3-9-18,18>>^ After that he slaughtered the bull and the ram of the communion sacrifice that was for the people. Then Aaron’s sons handed him the blood, and he sprinkled it around on all sides of the altar.

[[v3-9-19]]

^<<v3-9-19,19>>^ As for the pieces of fat of the bull, the fat tail of the ram, the fat covering the internal organs, the kidneys, and the appendage of the liver,

[[v3-9-20]]

^<<v3-9-20,20>>^ they placed all those pieces of fat on the breasts, after which he made the pieces of fat smoke on the altar.

[[v3-9-21]]

^<<v3-9-21,21>>^ But the breasts and the right leg Aaron waved back and forth as a wave offering before Jehovah, just as Moses had commanded.

[[v3-9-22]]

^<<v3-9-22,22>>^ Then Aaron raised his hands toward the people and blessed them and came down from making the sin offering and the burnt offering and the communion sacrifices.

[[v3-9-23]]

^<<v3-9-23,23>>^ Finally Moses and Aaron went into the tent of meeting and came out and blessed the people.
Jehovah’s glory now appeared to all the people,

[[v3-9-24]]

^<<v3-9-24,24>>^ and fire came out from Jehovah and began consuming the burnt offering and the pieces of fat on the altar. When all the people saw it, they started shouting and they fell with their faces to the ground.

'''

xref:003-leviticus/003-leviticus-008.adoc#v3-8-0[&#60; Capítulo Anterior] | <<v3-9-0,Topo>> | xref:003-leviticus/003-leviticus-010.adoc#v3-10-0[Próximo Capítulo &#62;]