include::./index.adoc[]

[[v3-1-0]]
=== Leviticus, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-1-1]]

^<<v3-1-1,1>>^ And Jehovah called Moses and spoke to him from the tent of meeting, saying:

[[v3-1-2]]

^<<v3-1-2,2>>^ “Speak to the Israelites^&#42;1^ and tell them, ‘If any one of you would present an offering to Jehovah from the domestic animals, you should present your offering from the herd or from the flock.

[NOTE]
====
. Lit., “sons of Israel.”
====

[[v3-1-3]]

^<<v3-1-3,3>>^ “‘If his offering is a burnt offering from the herd, he should present a sound male animal. He should present it of his own free will before Jehovah at the entrance of the tent of meeting.

[[v3-1-4]]

^<<v3-1-4,4>>^ He is to lay his hand on the head of the burnt offering, and it will be accepted in his behalf to make atonement for him.

[[v3-1-5]]

^<<v3-1-5,5>>^ “‘Then the young bull must be slaughtered before Jehovah, and the sons of Aaron, the priests, will present the blood and sprinkle the blood on all sides of the altar, which is at the entrance of the tent of meeting.

[[v3-1-6]]

^<<v3-1-6,6>>^ The burnt offering should be skinned and cut into pieces.

[[v3-1-7]]

^<<v3-1-7,7>>^ The sons of Aaron, the priests, are to put fire on the altar and arrange wood on the fire.

[[v3-1-8]]

^<<v3-1-8,8>>^ The sons of Aaron, the priests, will arrange the pieces of the offering with the head and the suet^&#42;1^ over the wood that is on the fire on the altar.

[NOTE]
====
. Or “the fat around the kidneys.”
====

[[v3-1-9]]

^<<v3-1-9,9>>^ Its intestines and its shanks will be washed with water, and the priest is to make all of it smoke on the altar as a burnt offering, an offering made by fire of a pleasing^&#42;1^ aroma to Jehovah.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v3-1-10]]

^<<v3-1-10,10>>^ “‘If his offering for a burnt offering is from the flock, from the young rams or the goats, he should present a sound male.

[[v3-1-11]]

^<<v3-1-11,11>>^ It is to be slaughtered at the north side of the altar before Jehovah, and the sons of Aaron, the priests, will sprinkle its blood on all sides of the altar.

[[v3-1-12]]

^<<v3-1-12,12>>^ He will cut it up into pieces, and with its head and its suet,^&#42;1^ the priest will arrange them over the wood on the fire on the altar.

[NOTE]
====
. Or “the fat around the kidneys.”
====

[[v3-1-13]]

^<<v3-1-13,13>>^ He will wash the intestines and the shanks with water, and the priest will present all of it and make it smoke on the altar. It is a burnt offering, an offering made by fire of a pleasing^&#42;1^ aroma to Jehovah.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v3-1-14]]

^<<v3-1-14,14>>^ “‘However, if he offers birds as a burnt offering to Jehovah, he will present his offering from the turtledoves or the young pigeons.

[[v3-1-15]]

^<<v3-1-15,15>>^ The priest will present it at the altar and nip off its head and make it smoke on the altar, but its blood should be drained out on the side of the altar.

[[v3-1-16]]

^<<v3-1-16,16>>^ He should remove its crop and its feathers and throw them beside the altar, to the east, to the place for the ashes.^&#42;1^

[NOTE]
====
. Or “fatty ashes,” that is, ashes soaked with the fat of the sacrifices.
====

[[v3-1-17]]

^<<v3-1-17,17>>^ He will split it at its wings without dividing it into two parts. Then the priest will make it smoke on the altar over the wood that is on the fire. It is a burnt offering, an offering made by fire of a pleasing^&#42;1^ aroma to Jehovah.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

'''

xref:002-exodus/002-exodus-040.adoc#v2-40-0[&#60; Capítulo Anterior] | <<v3-1-0,Topo>> | xref:003-leviticus/003-leviticus-002.adoc#v3-2-0[Próximo Capítulo &#62;]