include::./index.adoc[]

[[v3-20-0]]
=== Leviticus, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-20-1]]

^<<v3-20-1,1>>^ Jehovah went on speaking to Moses, saying:

[[v3-20-2]]

^<<v3-20-2,2>>^ “You are to say to the Israelites, ‘Any man of Israel and any foreigner who resides in Israel who gives any of his offspring to Moʹlech should be put to death without fail. The people of the land should stone him to death.

[[v3-20-3]]

^<<v3-20-3,3>>^ I myself will set my face against that man, and I will cut him off^&#42;1^ from among his people, because he has given some of his offspring to Moʹlech and has defiled my holy place and has profaned my holy name.

[NOTE]
====
. Or “put him to death.”
====

[[v3-20-4]]

^<<v3-20-4,4>>^ If the people of the land should deliberately close their eyes to what that man does when he gives his offspring to Moʹlech and they do not put him to death,

[[v3-20-5]]

^<<v3-20-5,5>>^ then I myself will certainly set my face against that man and his family. I will cut off^&#42;1^ that man from his people along with all who join him in prostituting themselves to Moʹlech.

[NOTE]
====
. Or “put to death.”
====

[[v3-20-6]]

^<<v3-20-6,6>>^ “‘As for the person^&#42;1^ who turns to the spirit mediums and the fortune-tellers so as to commit spiritual prostitution with them, I will certainly turn against that person^&#42;2^ and cut him off^&#42;3^ from his people.

[NOTE]
====
. Or “soul.”
. Or “soul.”
. Or “put him to death.”
====

[[v3-20-7]]

^<<v3-20-7,7>>^ “‘You must sanctify yourselves and become holy, because I am Jehovah your God.

[[v3-20-8]]

^<<v3-20-8,8>>^ And you must keep my statutes and carry them out. I am Jehovah, who is sanctifying you.

[[v3-20-9]]

^<<v3-20-9,9>>^ “‘If there is any man who curses^&#42;1^ his father or his mother, he should be put to death without fail. Since he has cursed his father or his mother, his own blood is upon him.

[NOTE]
====
. Or “calls down evil upon.”
====

[[v3-20-10]]

^<<v3-20-10,10>>^ “‘Now regarding a man who commits adultery with another man’s wife: The one who commits adultery with the wife of his fellow man should be put to death without fail, the adulterer and the adulteress.

[[v3-20-11]]

^<<v3-20-11,11>>^ A man who lies down with his father’s wife has exposed his father to shame.^&#42;1^ Both of them should be put to death without fail. Their own blood is upon them.

[NOTE]
====
. Lit., “his father’s nakedness.”
====

[[v3-20-12]]

^<<v3-20-12,12>>^ If a man lies down with his daughter-in-law, both of them should be put to death without fail. They have violated what is natural. Their own blood is upon them.

[[v3-20-13]]

^<<v3-20-13,13>>^ “‘If a man lies down with a male the same as one lies down with a woman, both of them have done a detestable thing. They should be put to death without fail. Their own blood is upon them.

[[v3-20-14]]

^<<v3-20-14,14>>^ “‘If a man takes a woman and her mother, it is an obscene act.^&#42;1^ They should burn him and them in the fire, so that obscene conduct may not continue among you.

[NOTE]
====
. Or “shameful conduct; lewdness.”
====

[[v3-20-15]]

^<<v3-20-15,15>>^ “‘If a man has intercourse with a beast, he should be put to death without fail, and you should kill the beast.

[[v3-20-16]]

^<<v3-20-16,16>>^ If a woman approaches any beast to have intercourse with it, you must kill the woman and the beast. They should be put to death without fail. Their own blood is upon them.

[[v3-20-17]]

^<<v3-20-17,17>>^ “‘If a man has sexual relations with his sister, the daughter of his father or the daughter of his mother, and he sees her nakedness and she sees his nakedness, it is a disgrace. They must be cut off^&#42;1^ before the eyes of the sons of their people. He has exposed his sister to shame.^&#42;2^ He should answer for his error.

[NOTE]
====
. Or “put to death.”
. Lit., “his sister’s nakedness.”
====

[[v3-20-18]]

^<<v3-20-18,18>>^ “‘If a man lies down with a menstruating woman and has sexual relations with her, both he and she have exposed her flow of blood. Both of them must be cut off^&#42;1^ from among their people.

[NOTE]
====
. Or “put to death.”
====

[[v3-20-19]]

^<<v3-20-19,19>>^ “‘You must not have sexual relations with your mother’s sister or your father’s sister, because that would be exposing a blood relative to shame. They should answer for their error.

[[v3-20-20]]

^<<v3-20-20,20>>^ A man who lies down with his uncle’s wife has exposed his uncle to shame.^&#42;1^ They should answer for their sin. They should die childless.

[NOTE]
====
. Lit., “his uncle’s nakedness.”
====

[[v3-20-21]]

^<<v3-20-21,21>>^ If a man takes his brother’s wife, it is something abhorrent. He has exposed his brother to shame.^&#42;1^ They should become childless.

[NOTE]
====
. Lit., “his brother’s nakedness.”
====

[[v3-20-22]]

^<<v3-20-22,22>>^ “‘You must keep all my statutes and all my judicial decisions and carry them out, so that the land where I am bringing you to dwell will not vomit you out.

[[v3-20-23]]

^<<v3-20-23,23>>^ You must not walk in the statutes of the nations that I am driving out from before you; for they have done all these things and I abhor them.

[[v3-20-24]]

^<<v3-20-24,24>>^ That is why I said to you: “You will take possession of their land, and I will give it to you as your possession, a land flowing with milk and honey. Jehovah your God I am, who has set you apart from the peoples.”

[[v3-20-25]]

^<<v3-20-25,25>>^ You must make a distinction between the clean animal and the unclean and between the unclean bird and the clean; you must not make yourselves^&#42;1^ loathsome by means of an animal or a bird or anything that creeps on the ground that I set apart for you to regard as unclean.

[NOTE]
====
. Or “your souls.”
====

[[v3-20-26]]

^<<v3-20-26,26>>^ You must be holy to me, because I, Jehovah, am holy, and I am setting you apart from the peoples to become mine.

[[v3-20-27]]

^<<v3-20-27,27>>^ “‘Any man or woman who acts as a spirit medium or is a fortune-teller^&#42;1^ should be put to death without fail. The people should stone them to death. Their own blood is upon them.’”

[NOTE]
====
. Or “has a spirit of prediction.”
====

'''

xref:003-leviticus/003-leviticus-019.adoc#v3-19-0[&#60; Capítulo Anterior] | <<v3-20-0,Topo>> | xref:003-leviticus/003-leviticus-021.adoc#v3-21-0[Próximo Capítulo &#62;]