include::./index.adoc[]

[[v3-19-0]]
=== Leviticus, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-19-1]]

^<<v3-19-1,1>>^ Jehovah spoke further to Moses, saying:

[[v3-19-2]]

^<<v3-19-2,2>>^ “Speak to the entire assembly of the Israelites and tell them, ‘You should be holy, because I, Jehovah your God, am holy.

[[v3-19-3]]

^<<v3-19-3,3>>^ “‘Each of you should respect^&#42;1^ his mother and his father, and you should keep my sabbaths. I am Jehovah your God.

[NOTE]
====
. Lit., “fear.”
====

[[v3-19-4]]

^<<v3-19-4,4>>^ Do not turn to worthless gods or make for yourselves gods of cast metal. I am Jehovah your God.

[[v3-19-5]]

^<<v3-19-5,5>>^ “‘Now if you offer a communion sacrifice to Jehovah, you should sacrifice it in such a way that you gain approval for yourselves.

[[v3-19-6]]

^<<v3-19-6,6>>^ It should be eaten on the day of your sacrifice and on the next day, but what is left over until the third day should be burned in the fire.

[[v3-19-7]]

^<<v3-19-7,7>>^ If, though, any of it is eaten on the third day, it is an offensive thing that will not be accepted with approval.

[[v3-19-8]]

^<<v3-19-8,8>>^ The one eating it will answer for his error because he has profaned a holy thing of Jehovah, and that person^&#42;1^ must be cut off^&#42;2^ from his people.

[NOTE]
====
. Or “soul.”
. Or “put to death.”
====

[[v3-19-9]]

^<<v3-19-9,9>>^ “‘When you reap the harvest of your land, you must not reap the edge of your field completely and you must not pick up the gleaning^&#42;1^ of your harvest.

[NOTE]
====
. Or “what is left.”
====

[[v3-19-10]]

^<<v3-19-10,10>>^ Also, you must not gather the leftovers of your vineyard or pick up the scattered grapes of your vineyard. You should leave them for the poor^&#42;1^ and the foreign resident. I am Jehovah your God.

[NOTE]
====
. Or “afflicted.”
====

[[v3-19-11]]

^<<v3-19-11,11>>^ “‘You must not steal, you must not deceive, and you must not deal falsely with one another.

[[v3-19-12]]

^<<v3-19-12,12>>^ You must not swear to a lie in my name and thus profane the name of your God. I am Jehovah.

[[v3-19-13]]

^<<v3-19-13,13>>^ You must not defraud your fellow man, and you must not rob. You should not withhold the wages of a hired worker all night until morning.

[[v3-19-14]]

^<<v3-19-14,14>>^ “‘You must not curse^&#42;1^ a deaf man or put an obstacle before a blind man, and you must be in fear of your God. I am Jehovah.

[NOTE]
====
. Or “call down evil upon.”
====

[[v3-19-15]]

^<<v3-19-15,15>>^ “‘You must not be unjust in your judgment. You must not show partiality to the poor or show preference to the rich. With justice you should judge your fellow man.

[[v3-19-16]]

^<<v3-19-16,16>>^ “‘You must not go around spreading slander among your people. You must not stand up against the life^&#42;1^ of your fellow man.^&#42;2^ I am Jehovah.

[NOTE]
====
. Lit., “blood.”
. Or possibly, “You must not stand by when your fellow man’s life is endangered.”
====

[[v3-19-17]]

^<<v3-19-17,17>>^ “‘You must not hate your brother in your heart. You should by all means reprove your fellow man, so that you will not bear sin along with him.

[[v3-19-18]]

^<<v3-19-18,18>>^ “‘You must not take vengeance nor hold a grudge against the sons of your people, and you must love your fellow man as yourself. I am Jehovah.

[[v3-19-19]]

^<<v3-19-19,19>>^ “‘You should keep my statutes: You must not interbreed two sorts of your domestic animals. You must not sow your field with two sorts of seed, and you must not wear a garment made with two sorts of thread mixed together.

[[v3-19-20]]

^<<v3-19-20,20>>^ “‘Now if a man lies down with a woman and has intercourse with her and she is a servant who is designated for another man, but she has not been redeemed or given her freedom, there should be a punishment. However, they should not be put to death, for she was not yet set free.

[[v3-19-21]]

^<<v3-19-21,21>>^ He should bring his guilt offering to Jehovah to the entrance of the tent of meeting, a ram of guilt offering.

[[v3-19-22]]

^<<v3-19-22,22>>^ The priest will make atonement for him with the ram of the guilt offering before Jehovah for the sin that he committed, and he will be forgiven for the sin that he committed.

[[v3-19-23]]

^<<v3-19-23,23>>^ “‘When you come into the land and you plant any tree for food, you must consider its fruitage impure and forbidden.^&#42;1^ For three years it will be forbidden^&#42;2^ to you. It must not be eaten.

[NOTE]
====
. Lit., “as its foreskin.”
. Lit., “uncircumcised.”
====

[[v3-19-24]]

^<<v3-19-24,24>>^ But in the fourth year, all its fruit will be holy for rejoicing before Jehovah.

[[v3-19-25]]

^<<v3-19-25,25>>^ Then in the fifth year, you may eat its fruit in order to add its produce to your harvest. I am Jehovah your God.

[[v3-19-26]]

^<<v3-19-26,26>>^ “‘You must eat nothing containing blood.
“‘You must not look for omens or practice magic.

[[v3-19-27]]

^<<v3-19-27,27>>^ “‘You must not shave^&#42;1^ the hair on the side of your head^&#42;2^ or disfigure the edges of your beard.

[NOTE]
====
. Or “trim; cut.”
. Or “cut your ­sidelocks.”
====

[[v3-19-28]]

^<<v3-19-28,28>>^ “‘You must not make cuts in your flesh for a dead person,^&#42;1^ and you must not make tattoo markings on yourselves. I am Jehovah.

[NOTE]
====
. Or “for a soul.” The Hebrew word neʹphesh here refers to a dead person.
====

[[v3-19-29]]

^<<v3-19-29,29>>^ “‘Do not dishonor your daughter by making her a prostitute, so that the land may not commit prostitution and be filled with loose morals.

[[v3-19-30]]

^<<v3-19-30,30>>^ “‘You must keep my sabbaths, and you must show reverence^&#42;1^ for my sanctuary. I am Jehovah.

[NOTE]
====
. Or “stand in awe of.” Lit., “fear.”
====

[[v3-19-31]]

^<<v3-19-31,31>>^ “‘Do not turn to the spirit mediums, and do not consult fortune-tellers so as to become unclean by them. I am Jehovah your God.

[[v3-19-32]]

^<<v3-19-32,32>>^ “‘Before gray hair you should rise up, and you must show honor to an older man, and you must be in fear of your God. I am Jehovah.

[[v3-19-33]]

^<<v3-19-33,33>>^ “‘If a foreigner resides with you in your land, you must not mistreat him.

[[v3-19-34]]

^<<v3-19-34,34>>^ The foreigner who resides with you should become to you like a native among you; and you must love him as yourself, for you were foreign residents in the land of Egypt. I am Jehovah your God.

[[v3-19-35]]

^<<v3-19-35,35>>^ “‘You must not use dishonest standards in measuring length, weight, or volume.

[[v3-19-36]]

^<<v3-19-36,36>>^ You should use accurate scales, accurate weights, an accurate dry measure,^&#42;1^ and an accurate liquid measure.^&#42;2^ I am Jehovah your God, who brought you out of the land of Egypt.

[NOTE]
====
. Lit., “an accurate ephah.” See App. B14.
. Lit., “an accurate hin.” See App. B14.
====

[[v3-19-37]]

^<<v3-19-37,37>>^ So you must keep all my statutes and all my judicial decisions, and you must follow them. I am Jehovah.’”

'''

xref:003-leviticus/003-leviticus-018.adoc#v3-18-0[&#60; Capítulo Anterior] | <<v3-19-0,Topo>> | xref:003-leviticus/003-leviticus-020.adoc#v3-20-0[Próximo Capítulo &#62;]