include::./index.adoc[]

[[v3-15-0]]
=== Leviticus, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-15-1]]

^<<v3-15-1,1>>^ Jehovah continued to speak to Moses and Aaron, saying:

[[v3-15-2]]

^<<v3-15-2,2>>^ “Speak to the Israelites and tell them, ‘If a man has a discharge from his genital organ,^&#42;1^ this discharge makes him unclean.

[NOTE]
====
. Lit., “his flesh.”
====

[[v3-15-3]]

^<<v3-15-3,3>>^ He is unclean from the discharge, whether the discharge continues to flow from his genitals or is obstructed, he is still unclean.

[[v3-15-4]]

^<<v3-15-4,4>>^ “‘Any bed that the one with the discharge lies on will be unclean, and anything he sits on will be unclean.

[[v3-15-5]]

^<<v3-15-5,5>>^ A man who touches his bed must wash his garments, and he should bathe in water and be unclean until the evening.

[[v3-15-6]]

^<<v3-15-6,6>>^ Anyone who sits on an article that the one having a discharge sat on should wash his garments, bathe in water, and be unclean until the evening.

[[v3-15-7]]

^<<v3-15-7,7>>^ Whoever touches the flesh of the one having a discharge should wash his garments, bathe in water, and be unclean until the evening.

[[v3-15-8]]

^<<v3-15-8,8>>^ If the one who has a discharge spits on someone clean, that person must wash his garments, bathe in water, and be unclean until the evening.

[[v3-15-9]]

^<<v3-15-9,9>>^ Any saddle that the one with the discharge rides on will be unclean.

[[v3-15-10]]

^<<v3-15-10,10>>^ Anyone touching anything that was under him will be unclean until the evening, and anyone who carries those items will wash his garments, bathe in water, and be unclean until the evening.

[[v3-15-11]]

^<<v3-15-11,11>>^ If the one with the discharge has not washed his hands in water and he touches someone, that person must then wash his garments, bathe in water, and be unclean until the evening.

[[v3-15-12]]

^<<v3-15-12,12>>^ An earthenware vessel that the one having a discharge touches should be smashed, and any wooden vessel should be washed with water.

[[v3-15-13]]

^<<v3-15-13,13>>^ “‘When the discharge stops and the person becomes clean from it, he will then count seven days for his purification, and he must wash his garments, bathe himself in running water, and he will be clean.

[[v3-15-14]]

^<<v3-15-14,14>>^ On the eighth day, he should take two turtledoves or two young pigeons and come before Jehovah at the entrance of the tent of meeting and give them to the priest.

[[v3-15-15]]

^<<v3-15-15,15>>^ And the priest will offer them, the one as a sin offering and the other as a burnt offering, and the priest will make atonement for him before Jehovah concerning his discharge.

[[v3-15-16]]

^<<v3-15-16,16>>^ “‘Now if a man has an emission of semen, he should bathe his whole body in water and be unclean until the evening.

[[v3-15-17]]

^<<v3-15-17,17>>^ He must wash with water any garment and any skin with semen on it, and it will be unclean until the evening.

[[v3-15-18]]

^<<v3-15-18,18>>^ “‘When a man lies with a woman and has an emission of semen, they should bathe in water and be unclean until the evening.

[[v3-15-19]]

^<<v3-15-19,19>>^ “‘If a woman has a discharge of blood from her body, she will continue in her menstrual impurity for seven days. Anyone touching her will be unclean until the evening.

[[v3-15-20]]

^<<v3-15-20,20>>^ Anything she lies down on in her menstrual impurity will be unclean, and everything she sits on will be unclean.

[[v3-15-21]]

^<<v3-15-21,21>>^ Anyone touching her bed should wash his garments, bathe in water, and be unclean until the evening.

[[v3-15-22]]

^<<v3-15-22,22>>^ Anyone touching any article she sat on should wash his garments, bathe in water, and be unclean until the evening.

[[v3-15-23]]

^<<v3-15-23,23>>^ If she sat on the bed or on another article, his touching it will make him unclean until the evening.

[[v3-15-24]]

^<<v3-15-24,24>>^ And if a man lies down with her and her menstrual impurity comes on him, he will then be unclean for seven days, and any bed on which he lies down will be unclean.

[[v3-15-25]]

^<<v3-15-25,25>>^ “‘When a woman’s discharge of blood flows for many days when it is not the regular time of her menstruation, or if she should have a flow longer than her usual menstruation, she will be unclean during all the days of her discharge, as in the days of her menstrual impurity.

[[v3-15-26]]

^<<v3-15-26,26>>^ Any bed she lies on during the days of her discharge will become like the bed of her menstrual impurity, and any article she sits on will become unclean like the uncleanness of her menstrual impurity.

[[v3-15-27]]

^<<v3-15-27,27>>^ Anyone touching them will be unclean, and he must wash his garments, bathe in water, and be unclean until the evening.

[[v3-15-28]]

^<<v3-15-28,28>>^ “‘However, when she is clean from her discharge, she will count for herself seven days, and afterward she will be clean.

[[v3-15-29]]

^<<v3-15-29,29>>^ On the eighth day, she should take two turtledoves or two young pigeons, and she will bring them to the priest at the entrance of the tent of meeting.

[[v3-15-30]]

^<<v3-15-30,30>>^ The priest will make the one a sin offering and the other a burnt offering, and the priest will make atonement for her before Jehovah concerning her unclean discharge.

[[v3-15-31]]

^<<v3-15-31,31>>^ “‘Thus you must keep the Israelites separate from their uncleanness, so that they do not die in their uncleanness by defiling my tabernacle, which is in their midst.

[[v3-15-32]]

^<<v3-15-32,32>>^ “‘This is the law about the man having a discharge, the man who is unclean because of an emission of semen,

[[v3-15-33]]

^<<v3-15-33,33>>^ the woman during her menstrual impurity, any male or female who has a discharge flowing from the body, and a man who lies down with an unclean woman.’”

'''

xref:003-leviticus/003-leviticus-014.adoc#v3-14-0[&#60; Capítulo Anterior] | <<v3-15-0,Topo>> | xref:003-leviticus/003-leviticus-016.adoc#v3-16-0[Próximo Capítulo &#62;]