include::./index.adoc[]

[[v3-6-0]]
=== Leviticus, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-6-1]]

^<<v3-6-1,1>>^ Jehovah went on to say to Moses:

[[v3-6-2]]

^<<v3-6-2,2>>^ “If someone^&#42;1^ sins and behaves unfaithfully toward Jehovah by deceiving his neighbor in connection with something entrusted to him, or something deposited with him, or he robs or defrauds his neighbor,

[NOTE]
====
. Or “a soul.”
====

[[v3-6-3]]

^<<v3-6-3,3>>^ or he finds something lost and is deceptive about it, and if he swears falsely over any such sin he may commit, this is what he should do:

[[v3-6-4]]

^<<v3-6-4,4>>^ If he has sinned and is guilty, he must return what he stole, what he extorted, what he took by fraud, what was entrusted to him, or the lost thing that he found,

[[v3-6-5]]

^<<v3-6-5,5>>^ or anything about which he swore falsely, and he must make full compensation for it, and he will add to it a fifth of its value. He will give it to the owner on the day his guilt is proved.

[[v3-6-6]]

^<<v3-6-6,6>>^ And he will bring to the priest as his guilt offering to Jehovah a sound ram from the flock according to the assessed value, for a guilt offering.

[[v3-6-7]]

^<<v3-6-7,7>>^ The priest will make atonement for him before Jehovah, and he will be forgiven for anything he may have done resulting in his guilt.”

[[v3-6-8]]

^<<v3-6-8,8>>^ Jehovah continued to speak to Moses, saying:

[[v3-6-9]]

^<<v3-6-9,9>>^ “Command Aaron and his sons and say, ‘This is the law of the burnt offering: The burnt offering will remain on the hearth on the altar all night long until the morning, and the fire will be kept burning on the altar.

[[v3-6-10]]

^<<v3-6-10,10>>^ The priest will clothe himself with his official dress of linen, and he will put the linen shorts^&#42;1^ on over his flesh. Then he will remove the ashes^&#42;2^ of the burnt offering that the fire had consumed on the altar and place them beside the altar.

[NOTE]
====
. Or “undergarments.”
. Or “fatty ashes,” that is, ashes soaked with the fat of the sacrifices.
====

[[v3-6-11]]

^<<v3-6-11,11>>^ Then he will take off his garments and put on other garments and take the ashes to a clean place outside the camp.

[[v3-6-12]]

^<<v3-6-12,12>>^ The fire will be kept burning on the altar. It must not go out. The priest must burn wood on it each morning and arrange the burnt offering over it, and he will make the fat of the communion sacrifices smoke over it.

[[v3-6-13]]

^<<v3-6-13,13>>^ Fire will be kept constantly burning on the altar. It must not go out.

[[v3-6-14]]

^<<v3-6-14,14>>^ “‘Now this is the law of the grain offering: You sons of Aaron are to present it before Jehovah in front of the altar.

[[v3-6-15]]

^<<v3-6-15,15>>^ One of them will take a handful from the fine flour of the grain offering and some of its oil and all the frankincense that is on the grain offering, and he will make it smoke on the altar as a pleasing^&#42;1^ aroma for a token offering^&#42;2^ to Jehovah.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
. Or “as a memorial (representative) portion of it.”
====

[[v3-6-16]]

^<<v3-6-16,16>>^ Aaron and his sons will eat what is left of it. It will be eaten as unleavened bread in a holy place. They will eat it in the courtyard of the tent of meeting.

[[v3-6-17]]

^<<v3-6-17,17>>^ It should not be baked with anything leavened. I have given it as their share out of my offerings made by fire. It is something most holy, like the sin offering and like the guilt offering.

[[v3-6-18]]

^<<v3-6-18,18>>^ Every male among the sons of Aaron will eat it. It is their permanent allowance throughout your generations from Jehovah’s offerings made by fire. Everything that touches them^&#42;1^ will become holy.’”

[NOTE]
====
. Or “the offerings.”
====

[[v3-6-19]]

^<<v3-6-19,19>>^ Jehovah spoke again to Moses:

[[v3-6-20]]

^<<v3-6-20,20>>^ “This is the offering that Aaron and his sons will present to Jehovah on the day he is anointed: the tenth of an eʹphah^&#42;1^ of fine flour as a regular grain offering, half of it in the morning and half of it in the evening.

[NOTE]
====
. A tenth of an ephah equaled 2.2 L (2 dry qt). See App. B14.
====

[[v3-6-21]]

^<<v3-6-21,21>>^ It will be made with oil on a griddle. You will bring it well-mixed with oil and present it in pieces as a baked product of the grain offering as a pleasing^&#42;1^ aroma to Jehovah.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v3-6-22]]

^<<v3-6-22,22>>^ The anointed priest who succeeds him from among his sons will make it. It is a lasting regulation: As a whole offering it will be made to smoke to Jehovah.

[[v3-6-23]]

^<<v3-6-23,23>>^ Every grain offering of a priest should be a whole offering. It must not be eaten.”

[[v3-6-24]]

^<<v3-6-24,24>>^ Jehovah spoke again to Moses and said:

[[v3-6-25]]

^<<v3-6-25,25>>^ “Tell Aaron and his sons, ‘This is the law of the sin offering: In the place where the burnt offering is slaughtered, the sin offering will also be slaughtered before Jehovah. It is a most holy thing.

[[v3-6-26]]

^<<v3-6-26,26>>^ The priest who offers it for sin will eat it. It will be eaten in a holy place, in the courtyard of the tent of meeting.

[[v3-6-27]]

^<<v3-6-27,27>>^ “‘Everything that touches its flesh will become holy, and when anyone spatters some of its blood on his garment, you should wash what was spattered with blood in a holy place.

[[v3-6-28]]

^<<v3-6-28,28>>^ The earthenware vessel in which it was boiled is to be shattered. But if it was boiled in a copper vessel, then the vessel must be scoured and washed with water.

[[v3-6-29]]

^<<v3-6-29,29>>^ “‘Every male among the priests will eat it. It is something most holy.

[[v3-6-30]]

^<<v3-6-30,30>>^ However, no sin offering is to be eaten if some of its blood is brought into the tent of meeting to make atonement in the holy place. It is to be burned with fire.

'''

xref:003-leviticus/003-leviticus-005.adoc#v3-5-0[&#60; Capítulo Anterior] | <<v3-6-0,Topo>> | xref:003-leviticus/003-leviticus-007.adoc#v3-7-0[Próximo Capítulo &#62;]