include::./index.adoc[]

[[v3-10-0]]
=== Leviticus, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-10-1]]

^<<v3-10-1,1>>^ Later Aaron’s sons Naʹdab and A·biʹhu each took his fire holder and put fire in it and placed incense on it. Then they began offering before Jehovah unauthorized fire, which he had not commanded them to do.

[[v3-10-2]]

^<<v3-10-2,2>>^ At this a fire came out from before Jehovah and consumed them, so that they died before Jehovah.

[[v3-10-3]]

^<<v3-10-3,3>>^ Then Moses said to Aaron: “This is what Jehovah has said, ‘I will be made holy among those near to me, and I will be glorified before all the people.’” And Aaron kept silent.

[[v3-10-4]]

^<<v3-10-4,4>>^ So Moses called Mishʹa·el and El·zaʹphan, the sons of Uzʹzi·el, Aaron’s uncle, and said to them: “Come here, carry your brothers from in front of the holy place to a place outside the camp.”

[[v3-10-5]]

^<<v3-10-5,5>>^ So they came forward and carried the men away in their robes to a place outside the camp, just as Moses had told them.

[[v3-10-6]]

^<<v3-10-6,6>>^ Moses then said to Aaron and his other sons El·e·aʹzar and Ithʹa·mar: “Do not let your heads go ungroomed or tear your garments, so that you may not die and that God may not become indignant against all the assembly. Your brothers of the whole house of Israel will weep over those whom Jehovah has killed by the fire.

[[v3-10-7]]

^<<v3-10-7,7>>^ You must not go out from the entrance of the tent of meeting or you will die, for Jehovah’s anointing oil is upon you.” So they did according to Moses’ word.

[[v3-10-8]]

^<<v3-10-8,8>>^ Then Jehovah said to Aaron:

[[v3-10-9]]

^<<v3-10-9,9>>^ “Do not drink wine or other alcoholic beverages, you and your sons with you, when you come into the tent of meeting, so that you will not die. It is a permanent statute for your generations.

[[v3-10-10]]

^<<v3-10-10,10>>^ This is to distinguish between the holy thing and the profane and between the unclean thing and the clean,

[[v3-10-11]]

^<<v3-10-11,11>>^ and to teach the Israelites all the regulations that Jehovah has spoken to them through Moses.”

[[v3-10-12]]

^<<v3-10-12,12>>^ Then Moses spoke to Aaron and to El·e·aʹzar and Ithʹa·mar, his sons who were left: “Take what was left of the grain offering from Jehovah’s offerings made by fire and eat it as unleavened bread near the altar, because it is something most holy.

[[v3-10-13]]

^<<v3-10-13,13>>^ You must eat it in a holy place, because it is your allowance and the allowance of your sons from Jehovah’s offerings made by fire, for this is what I have been commanded.

[[v3-10-14]]

^<<v3-10-14,14>>^ You will also eat the breast of the wave offering and the leg of the sacred portion in a clean place, you and your sons and your daughters with you, because these things have been given as your allowance and the allowance of your sons from the communion sacrifices of the Israelites.

[[v3-10-15]]

^<<v3-10-15,15>>^ They will bring the leg of the sacred portion and the breast of the wave offering along with the offerings of fat made by fire, in order to wave the wave offering back and forth before Jehovah; and it will serve as a permanent allowance for you and your sons with you, just as Jehovah has commanded.”

[[v3-10-16]]

^<<v3-10-16,16>>^ And Moses diligently searched for the goat of the sin offering, and he discovered that it had been burned up. So he grew indignant at El·e·aʹzar and Ithʹa·mar, Aaron’s sons who were left, and he said:

[[v3-10-17]]

^<<v3-10-17,17>>^ “Why did you not eat the sin offering in the holy place, since it is something most holy and he has given it to you so that you may answer for the error of the assembly and make atonement for them before Jehovah?

[[v3-10-18]]

^<<v3-10-18,18>>^ Look! Its blood has not been brought inside the holy place. You certainly should have eaten it in the holy place, just as I was commanded.”

[[v3-10-19]]

^<<v3-10-19,19>>^ Aaron replied to Moses: “Look! Today they presented their sin offering and their burnt offering before Jehovah, and yet these things happened to me. If I had eaten the sin offering today, would that have been pleasing to Jehovah?”

[[v3-10-20]]

^<<v3-10-20,20>>^ When Moses heard that, he was satisfied.

'''

xref:003-leviticus/003-leviticus-009.adoc#v3-9-0[&#60; Capítulo Anterior] | <<v3-10-0,Topo>> | xref:003-leviticus/003-leviticus-011.adoc#v3-11-0[Próximo Capítulo &#62;]