include::./index.adoc[]

[[v3-22-0]]
=== Leviticus, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-22-1]]

^<<v3-22-1,1>>^ Jehovah spoke further to Moses, saying:

[[v3-22-2]]

^<<v3-22-2,2>>^ “Tell Aaron and his sons that they should be careful how they handle^&#42;1^ the holy things of the Israelites and not profane my holy name regarding the things they are sanctifying to me. I am Jehovah.

[NOTE]
====
. Lit., “they should separate themselves from.”
====

[[v3-22-3]]

^<<v3-22-3,3>>^ Say to them, ‘Throughout your generations, any of your offspring who, while he is unclean, comes near to the holy things that the Israelites sanctify to Jehovah, that person^&#42;1^ will be cut off^&#42;2^ from before me. I am Jehovah.

[NOTE]
====
. Or “soul.”
. Or “put to death.”
====

[[v3-22-4]]

^<<v3-22-4,4>>^ No man of Aaron’s offspring who has leprosy or a discharge may eat of the holy things until he becomes clean, neither the man who touches someone who became unclean by a dead person,^&#42;1^ nor a man who has a seminal emission,

[NOTE]
====
. Or “by a soul.”
====

[[v3-22-5]]

^<<v3-22-5,5>>^ nor a man who touches an unclean swarming creature or who touches a man who is unclean for any reason and who can make him unclean.

[[v3-22-6]]

^<<v3-22-6,6>>^ The person^&#42;1^ who touches any of these will be unclean until the evening and may not eat any of the holy things, but he should bathe himself in water.

[NOTE]
====
. Or “soul.”
====

[[v3-22-7]]

^<<v3-22-7,7>>^ When the sun has set, he will be clean, and afterward he may eat some of the holy things because it is his food.

[[v3-22-8]]

^<<v3-22-8,8>>^ Also, he should not eat any animal found dead or anything torn by wild animals and become unclean by it. I am Jehovah.

[[v3-22-9]]

^<<v3-22-9,9>>^ “‘They must keep their obligation to me, so that they may not incur sin because of it and have to die for it because they were profaning it. I am Jehovah, who is sanctifying them.

[[v3-22-10]]

^<<v3-22-10,10>>^ “‘No unauthorized person^&#42;1^ may eat anything holy. No foreign guest of a priest or hired worker may eat anything holy.

[NOTE]
====
. Lit., “No stranger,” that is, a man not of Aaron’s family.
====

[[v3-22-11]]

^<<v3-22-11,11>>^ But if a priest should purchase someone^&#42;1^ with his own money, that person may share in eating it. Slaves born in his house may also share in eating his food.

[NOTE]
====
. Or “a soul.”
====

[[v3-22-12]]

^<<v3-22-12,12>>^ If the daughter of a priest should marry someone who is not a priest,^&#42;1^ she may not eat of the contribution of the holy things.

[NOTE]
====
. Or “marry a stranger.”
====

[[v3-22-13]]

^<<v3-22-13,13>>^ But if the daughter of a priest should become a widow or is divorced and she has no offspring and she returns to her father’s house as in her youth, she may eat some of her father’s food; but no unauthorized person^&#42;1^ may eat it.

[NOTE]
====
. Lit., “stranger,” that is, a man not of Aaron’s family.
====

[[v3-22-14]]

^<<v3-22-14,14>>^ “‘Now if a man eats a holy thing by mistake, he must add a fifth of its value and give the holy offering to the priest.

[[v3-22-15]]

^<<v3-22-15,15>>^ So they should not profane the holy things of the Israelites that they contribute to Jehovah

[[v3-22-16]]

^<<v3-22-16,16>>^ and cause them to incur punishment for their guilt because of eating their holy things; for I am Jehovah, who is sanctifying them.’”

[[v3-22-17]]

^<<v3-22-17,17>>^ Jehovah continued speaking to Moses, saying:

[[v3-22-18]]

^<<v3-22-18,18>>^ “Speak to Aaron and his sons and all the Israelites and say to them, ‘When an Israelite man or a foreign resident in Israel presents a burnt offering to Jehovah to fulfill his vows or to make a voluntary offering,

[[v3-22-19]]

^<<v3-22-19,19>>^ he should present a sound male from the herd, the young rams, or the goats, in order to gain approval.

[[v3-22-20]]

^<<v3-22-20,20>>^ You must not present anything with a defect, for it will not serve to gain approval for you.

[[v3-22-21]]

^<<v3-22-21,21>>^ “‘If a man presents a communion sacrifice to Jehovah to pay a vow or as a voluntary offering, it should be a sound animal from the herd or the flock, in order to gain approval. No defect at all should be in it.

[[v3-22-22]]

^<<v3-22-22,22>>^ No offering should be blind, have a fracture, a cut, a wart, scabbiness, or ringworm; you must not present any of these to Jehovah or make such an offering on the altar for Jehovah.

[[v3-22-23]]

^<<v3-22-23,23>>^ You may present a bull or a sheep with a limb that is too long or too short as a voluntary offering, but it will not be accepted with approval as a vow offering.

[[v3-22-24]]

^<<v3-22-24,24>>^ You must not present to Jehovah one having the testicles damaged or crushed or pulled off or cut off, and you should not offer such animals in your land.

[[v3-22-25]]

^<<v3-22-25,25>>^ And you must not present any of these from the hand of a foreigner as the bread of your God, for they are corrupted and defective. They will not be accepted with approval for you.’”

[[v3-22-26]]

^<<v3-22-26,26>>^ Jehovah spoke further to Moses, saying:

[[v3-22-27]]

^<<v3-22-27,27>>^ “When a bull or a young ram or a goat is born, it will continue with its mother for seven days, but from the eighth day forward it will be accepted with approval as an offering, an offering made by fire to Jehovah.

[[v3-22-28]]

^<<v3-22-28,28>>^ As for a bull or a sheep, you must not slaughter it and its young on the same day.

[[v3-22-29]]

^<<v3-22-29,29>>^ “If you sacrifice a thanksgiving sacrifice to Jehovah, you should sacrifice it to gain approval for yourselves.

[[v3-22-30]]

^<<v3-22-30,30>>^ It should be eaten on that day. You must not leave any of it until morning. I am Jehovah.

[[v3-22-31]]

^<<v3-22-31,31>>^ “You must keep my commandments and carry them out. I am Jehovah.

[[v3-22-32]]

^<<v3-22-32,32>>^ You must not profane my holy name, and I must be sanctified in the midst of the Israelites. I am Jehovah, who is sanctifying you,

[[v3-22-33]]

^<<v3-22-33,33>>^ the one bringing you out of the land of Egypt to prove myself God to you. I am Jehovah.”

'''

xref:003-leviticus/003-leviticus-021.adoc#v3-21-0[&#60; Capítulo Anterior] | <<v3-22-0,Topo>> | xref:003-leviticus/003-leviticus-023.adoc#v3-23-0[Próximo Capítulo &#62;]