include::./index.adoc[]

[[v3-21-0]]
=== Leviticus, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-21-1]]

^<<v3-21-1,1>>^ Jehovah went on to say to Moses: “Talk to the priests, Aaron’s sons, and say to them, ‘No one should defile himself for a dead person^&#42;1^ among his people.

[NOTE]
====
. Or “for a soul.”
====

[[v3-21-2]]

^<<v3-21-2,2>>^ But he may do so for a close blood relative, for his mother, his father, his son, his daughter, his brother,

[[v3-21-3]]

^<<v3-21-3,3>>^ and he may defile himself for his sister if she is a virgin who is near to him and has not yet married.

[[v3-21-4]]

^<<v3-21-4,4>>^ He may not defile himself and make himself profane for a woman who belongs to a husband of his people.

[[v3-21-5]]

^<<v3-21-5,5>>^ They should not make their heads bald or shave off the fringe of their beard or make cuts on their body.

[[v3-21-6]]

^<<v3-21-6,6>>^ They should be holy to their God, and they should not profane the name of their God, for they are presenting Jehovah’s offerings made by fire, the bread^&#42;1^ of their God, and they must be holy.

[NOTE]
====
. Or “food,” referring to sacrifices.
====

[[v3-21-7]]

^<<v3-21-7,7>>^ They should not marry a prostitute, a woman who has been defiled, or a woman divorced from her husband, because the priest is holy to his God.

[[v3-21-8]]

^<<v3-21-8,8>>^ You must sanctify him, because he is one presenting the bread of your God. He should be holy to you, because I, Jehovah, the one sanctifying you, am holy.

[[v3-21-9]]

^<<v3-21-9,9>>^ “‘Now if the daughter of a priest should profane herself by committing prostitution, she is profaning her father. She should be burned in the fire.

[[v3-21-10]]

^<<v3-21-10,10>>^ “‘The high priest of his brothers, on whose head the anointing oil is poured and who has been installed^&#42;1^ to wear the priestly garments, should not let his head go ungroomed or tear his garments.

[NOTE]
====
. Lit., “whose hand was filled.”
====

[[v3-21-11]]

^<<v3-21-11,11>>^ He should not approach any dead person;^&#42;1^ he may not defile himself even for his father or his mother.

[NOTE]
====
. Or “any dead soul.” The Hebrew word neʹphesh is here connected to a Hebrew word meaning “dead.”
====

[[v3-21-12]]

^<<v3-21-12,12>>^ He should not go out from the sanctuary and should not profane the sanctuary of his God, for the sign of dedication, the anointing oil of his God, is upon him. I am Jehovah.

[[v3-21-13]]

^<<v3-21-13,13>>^ “‘He must take as a wife a woman who is a virgin.

[[v3-21-14]]

^<<v3-21-14,14>>^ He may not marry a widow, a divorced woman, one who has been defiled, or a prostitute; but he should take a virgin from his people as a wife.

[[v3-21-15]]

^<<v3-21-15,15>>^ He should not profane his offspring^&#42;1^ among his people, for I am Jehovah, who is sanctifying him.’”

[NOTE]
====
. Lit., “seed.”
====

[[v3-21-16]]

^<<v3-21-16,16>>^ Jehovah continued to speak to Moses, saying:

[[v3-21-17]]

^<<v3-21-17,17>>^ “Tell Aaron, ‘No man of your offspring^&#42;1^ throughout their generations who has a defect may approach to present the bread of his God.

[NOTE]
====
. Lit., “seed.”
====

[[v3-21-18]]

^<<v3-21-18,18>>^ If there is any man who has a defect, he may not approach: a man who is blind or lame or has a disfigured face^&#42;1^ or one limb too long,

[NOTE]
====
. Lit., “or with his nose slit.”
====

[[v3-21-19]]

^<<v3-21-19,19>>^ a man with a fractured foot or a fractured hand,

[[v3-21-20]]

^<<v3-21-20,20>>^ a hunchback or a dwarf,^&#42;1^ or a man with an eye defect or eczema or ringworm or damaged testicles.

[NOTE]
====
. Or possibly, “emaciated.”
====

[[v3-21-21]]

^<<v3-21-21,21>>^ No man of the offspring^&#42;1^ of Aaron the priest who has a defect may approach to present Jehovah’s offerings made by fire. Because he has a defect, he may not approach to present the bread of his God.

[NOTE]
====
. Lit., “seed.”
====

[[v3-21-22]]

^<<v3-21-22,22>>^ He may eat the bread of his God from the most holy things and from the holy things.

[[v3-21-23]]

^<<v3-21-23,23>>^ However, he may not come near the curtain, and he may not approach the altar, because there is a defect in him; and he should not profane my sanctuary, for I am Jehovah, who is sanctifying them.’”

[[v3-21-24]]

^<<v3-21-24,24>>^ So Moses spoke to Aaron and his sons and all the Israelites.

'''

xref:003-leviticus/003-leviticus-020.adoc#v3-20-0[&#60; Capítulo Anterior] | <<v3-21-0,Topo>> | xref:003-leviticus/003-leviticus-022.adoc#v3-22-0[Próximo Capítulo &#62;]