include::./index.adoc[]

[[v3-2-0]]
=== Leviticus, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-2-1]]

^<<v3-2-1,1>>^ “‘Now if someone^&#42;1^ presents a grain offering to Jehovah, his offering must be fine flour, and he should pour oil on it and put frankincense on it.

[NOTE]
====
. Or “a soul.”
====

[[v3-2-2]]

^<<v3-2-2,2>>^ Then he will bring it to the sons of Aaron, the priests, and the priest will take a handful of the fine flour and oil and all its frankincense, and he will make it smoke as a token offering^&#42;1^ on the altar, an offering made by fire of a pleasing^&#42;2^ aroma to Jehovah.

[NOTE]
====
. Or “as a memorial (representative) portion of it.”
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v3-2-3]]

^<<v3-2-3,3>>^ Whatever is left of the grain offering belongs to Aaron and his sons as something most holy from Jehovah’s offerings made by fire.

[[v3-2-4]]

^<<v3-2-4,4>>^ “‘If you present a grain offering that has been baked in the oven, it should be of fine flour, unleavened ring-shaped loaves mixed with oil or unleavened wafers spread with oil.

[[v3-2-5]]

^<<v3-2-5,5>>^ “‘If your offering is a grain offering from the griddle, it should be of fine, unleavened flour mixed with oil.

[[v3-2-6]]

^<<v3-2-6,6>>^ It should be broken into pieces, and you are to pour oil on it. It is a grain offering.

[[v3-2-7]]

^<<v3-2-7,7>>^ “‘If your offering is a grain offering prepared in a pan, it should be made of fine flour with oil.

[[v3-2-8]]

^<<v3-2-8,8>>^ You should bring the grain offering that was made of these to Jehovah, and it will be presented to the priest, who will bring it near to the altar.

[[v3-2-9]]

^<<v3-2-9,9>>^ And the priest will lift off some of the grain offering as a token offering^&#42;1^ and make it smoke on the altar as an offering made by fire of a pleasing^&#42;2^ aroma to Jehovah.

[NOTE]
====
. Or “as a memorial (representative) portion of it.”
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v3-2-10]]

^<<v3-2-10,10>>^ What is left of the grain offering belongs to Aaron and his sons as something most holy of Jehovah’s offerings by fire.

[[v3-2-11]]

^<<v3-2-11,11>>^ “‘No grain offering that you present to Jehovah should be leavened, for you must not make any sourdough or honey smoke as an offering made by fire to Jehovah.

[[v3-2-12]]

^<<v3-2-12,12>>^ “‘You may present them to Jehovah as an offering of the firstfruits, but they must not be brought to the altar as a pleasing^&#42;1^ aroma.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v3-2-13]]

^<<v3-2-13,13>>^ “‘Every grain offering you make is to be seasoned with salt; and you must not allow the salt of the covenant of your God to be missing from your grain offering. Along with every offering of yours, you will present salt.

[[v3-2-14]]

^<<v3-2-14,14>>^ “‘If you present the grain offering of the first ripe fruits to Jehovah, you should present new grain^&#42;1^ roasted with fire, coarsely crushed new kernels, as the grain offering of your first ripe fruits.

[NOTE]
====
. Or “present green ears.”
====

[[v3-2-15]]

^<<v3-2-15,15>>^ You are to put oil on it and place frankincense on it. It is a grain offering.

[[v3-2-16]]

^<<v3-2-16,16>>^ The priest will make it smoke as a token offering,^&#42;1^ that is, some of the coarse grain and oil along with all its frankincense, as an offering made by fire to Jehovah.

[NOTE]
====
. Or “as a memorial (representative) portion of it.”
====

'''

xref:003-leviticus/003-leviticus-001.adoc#v3-1-0[&#60; Capítulo Anterior] | <<v3-2-0,Topo>> | xref:003-leviticus/003-leviticus-003.adoc#v3-3-0[Próximo Capítulo &#62;]