include::./index.adoc[]

[[v3-8-0]]
=== Leviticus, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-8-1]]

^<<v3-8-1,1>>^ Jehovah continued to speak to Moses, saying:

[[v3-8-2]]

^<<v3-8-2,2>>^ “Take Aaron and his sons with him, the garments, the anointing oil, the bull of the sin offering, the two rams, and the basket of unleavened bread,

[[v3-8-3]]

^<<v3-8-3,3>>^ and make all the assembly gather together at the entrance of the tent of meeting.”

[[v3-8-4]]

^<<v3-8-4,4>>^ Then Moses did just as Jehovah had commanded him, and the assembly gathered together at the entrance of the tent of meeting.

[[v3-8-5]]

^<<v3-8-5,5>>^ Moses now said to the assembly: “This is what Jehovah has commanded us to do.”

[[v3-8-6]]

^<<v3-8-6,6>>^ So Moses brought Aaron and his sons near and washed them with water.

[[v3-8-7]]

^<<v3-8-7,7>>^ After that he put the robe on him, wrapped him with the sash, clothed him with the sleeveless coat, and put the ephʹod on him and tied it with the woven belt^&#42;1^ of the ephʹod, binding it securely on him.

[NOTE]
====
. Or “waistband.”
====

[[v3-8-8]]

^<<v3-8-8,8>>^ Next he placed the breastpiece on him and put the Uʹrim and the Thumʹmim in the breastpiece.

[[v3-8-9]]

^<<v3-8-9,9>>^ Then he placed the turban on his head, and he put on the front of the turban the shining plate of gold, the holy sign of dedication,^&#42;1^ just as Jehovah had commanded Moses.

[NOTE]
====
. Or “the holy diadem.”
====

[[v3-8-10]]

^<<v3-8-10,10>>^ Moses then took the anointing oil and anointed the tabernacle and all that was in it and sanctified them.

[[v3-8-11]]

^<<v3-8-11,11>>^ After that he spattered some of it seven times on the altar and anointed the altar and all its utensils and the basin and its stand in order to sanctify them.

[[v3-8-12]]

^<<v3-8-12,12>>^ Finally he poured some of the anointing oil on Aaron’s head and anointed him in order to sanctify him.

[[v3-8-13]]

^<<v3-8-13,13>>^ Moses then brought Aaron’s sons near and clothed them with robes and wrapped them with sashes and put^&#42;1^ headgear on them, just as Jehovah had commanded Moses.

[NOTE]
====
. Or “wrapped.”
====

[[v3-8-14]]

^<<v3-8-14,14>>^ Then he brought the bull of the sin offering, and Aaron and his sons laid their hands on the head of the bull of the sin offering.

[[v3-8-15]]

^<<v3-8-15,15>>^ Moses slaughtered it and took the blood with his finger and put it on the horns of the altar on all sides, and he purified the altar from sin, but the rest of the blood he poured at the base of the altar, in order to sanctify it to make atonement on it.

[[v3-8-16]]

^<<v3-8-16,16>>^ After that he took all the fat that was on the intestines, the appendage of the liver, and the two kidneys and their fat, and Moses made them smoke on the altar.

[[v3-8-17]]

^<<v3-8-17,17>>^ Then he had the rest of the bull, its skin, its flesh, and its dung, burned with fire outside the camp, just as Jehovah had commanded Moses.

[[v3-8-18]]

^<<v3-8-18,18>>^ He now brought the ram of the burnt offering near, and Aaron and his sons laid their hands on the head of the ram.

[[v3-8-19]]

^<<v3-8-19,19>>^ Moses then slaughtered it and sprinkled the blood on all sides of the altar.

[[v3-8-20]]

^<<v3-8-20,20>>^ He cut the ram into its pieces, and Moses made the head, the pieces, and the suet^&#42;1^ smoke.

[NOTE]
====
. Or “the fat around the kidneys.”
====

[[v3-8-21]]

^<<v3-8-21,21>>^ He washed the intestines and the shanks with water, and Moses made the entire ram smoke on the altar. It was a burnt offering as a pleasing^&#42;1^ aroma. It was an offering made by fire to Jehovah, just as Jehovah had commanded Moses.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v3-8-22]]

^<<v3-8-22,22>>^ Then he brought the second ram, the ram of the installation, and Aaron and his sons laid their hands on the ram’s head.

[[v3-8-23]]

^<<v3-8-23,23>>^ Moses slaughtered it and took some of its blood and put it on Aaron’s right earlobe and on the thumb of his right hand and on the big toe of his right foot.

[[v3-8-24]]

^<<v3-8-24,24>>^ Next Moses brought Aaron’s sons forward and put some of the blood on their right earlobe and on the thumb of their right hand and on the big toe of their right foot; but Moses sprinkled the rest of the blood on all sides of the altar.

[[v3-8-25]]

^<<v3-8-25,25>>^ Then he took the fat, the fat tail, all the fat that was on the intestines, the appendage of the liver, the two kidneys and their fat, and the right leg.

[[v3-8-26]]

^<<v3-8-26,26>>^ He took out of the basket of unleavened bread that was before Jehovah one unleavened ring-shaped loaf, one ring-shaped loaf of oiled bread, and one wafer. He then placed them on the pieces of fat and the right leg.

[[v3-8-27]]

^<<v3-8-27,27>>^ After that he put all of them on the palms of Aaron and the palms of his sons and began to wave them back and forth as a wave offering before Jehovah.

[[v3-8-28]]

^<<v3-8-28,28>>^ Then Moses took them from their hands and made them smoke on the altar on top of the burnt offering. They were an installation sacrifice as a pleasing^&#42;1^ aroma. It was an offering made by fire to Jehovah.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v3-8-29]]

^<<v3-8-29,29>>^ Moses then took the breast and waved it back and forth as a wave offering before Jehovah. From the installation ram it became the portion for Moses, just as Jehovah had commanded Moses.

[[v3-8-30]]

^<<v3-8-30,30>>^ And Moses took some of the anointing oil and some of the blood that was on the altar and spattered it on Aaron and his garments and on his sons and the garments of his sons who were with him. Thus he sanctified Aaron and his garments and his sons and their garments.

[[v3-8-31]]

^<<v3-8-31,31>>^ Then Moses said to Aaron and his sons: “Boil the flesh at the entrance of the tent of meeting, and you will eat it there with the bread that is in the installation basket, just as I was commanded, ‘Aaron and his sons will eat it.’

[[v3-8-32]]

^<<v3-8-32,32>>^ What is left over of the flesh and the bread you will burn with fire.

[[v3-8-33]]

^<<v3-8-33,33>>^ You must not go out from the entrance of the tent of meeting for seven days, until the days for completing your installation are over, because it will take seven days to install you as priests.^&#42;1^

[NOTE]
====
. Lit., “fill your hand.”
====

[[v3-8-34]]

^<<v3-8-34,34>>^ Jehovah commanded that we do what we have done today in order to make atonement for you.

[[v3-8-35]]

^<<v3-8-35,35>>^ You will stay at the entrance of the tent of meeting day and night for seven days and carry out your obligation to Jehovah, so that you may not die; for so I have been commanded.”

[[v3-8-36]]

^<<v3-8-36,36>>^ And Aaron and his sons did all the things that Jehovah had commanded by means of Moses.

'''

xref:003-leviticus/003-leviticus-007.adoc#v3-7-0[&#60; Capítulo Anterior] | <<v3-8-0,Topo>> | xref:003-leviticus/003-leviticus-009.adoc#v3-9-0[Próximo Capítulo &#62;]