include::./index.adoc[]

[[v3-18-0]]
=== Leviticus, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-18-1]]

^<<v3-18-1,1>>^ Jehovah continued to speak to Moses, saying:

[[v3-18-2]]

^<<v3-18-2,2>>^ “Speak to the Israelites and say to them, ‘I am Jehovah your God.

[[v3-18-3]]

^<<v3-18-3,3>>^ You must not behave as they do in the land of Egypt, where you were dwelling, and you must not do what they do in the land of Caʹnaan, where I am bringing you. And you must not walk in their statutes.

[[v3-18-4]]

^<<v3-18-4,4>>^ You should carry out my judicial decisions, and you should keep my statutes and walk in them. I am Jehovah your God.

[[v3-18-5]]

^<<v3-18-5,5>>^ You must keep my statutes and my judicial decisions; anyone who does so will live by means of them. I am Jehovah.

[[v3-18-6]]

^<<v3-18-6,6>>^ “‘No man among you should approach any of his close relatives to have sexual relations.^&#42;1^ I am Jehovah.

[NOTE]
====
. Lit., “to uncover nakedness,” here and in subsequent occurrences.
====

[[v3-18-7]]

^<<v3-18-7,7>>^ You must not have sexual relations with your father, and you must not have sexual relations with your mother. She is your mother, and you must not have sexual relations with her.

[[v3-18-8]]

^<<v3-18-8,8>>^ “‘You must not have sexual relations with your father’s wife. It is exposing your father to shame.^&#42;1^

[NOTE]
====
. Lit., “It is your father’s nakedness.”
====

[[v3-18-9]]

^<<v3-18-9,9>>^ “‘You must not have sexual relations with your sister, either the daughter of your father or the daughter of your mother, whether she is born in the same household or born outside of it.

[[v3-18-10]]

^<<v3-18-10,10>>^ “‘You must not have sexual relations with the daughter of your son or the daughter of your daughter, because they are your own nakedness.

[[v3-18-11]]

^<<v3-18-11,11>>^ “‘You must not have sexual relations with the daughter of your father’s wife, the offspring of your father, because she is your sister.

[[v3-18-12]]

^<<v3-18-12,12>>^ “‘You must not have sexual relations with your father’s sister. She is your father’s blood relative.

[[v3-18-13]]

^<<v3-18-13,13>>^ “‘You must not have sexual relations with your mother’s sister, because she is your mother’s blood relative.

[[v3-18-14]]

^<<v3-18-14,14>>^ “‘You must not expose your father’s brother to shame^&#42;1^ by having sexual relations with his wife. She is your aunt.

[NOTE]
====
. Lit., “expose the nakedness of your father’s brother.”
====

[[v3-18-15]]

^<<v3-18-15,15>>^ “‘You must not have sexual relations with your daughter-in-law. She is your son’s wife, and you must not have relations with her.

[[v3-18-16]]

^<<v3-18-16,16>>^ “‘You must not have sexual relations with your brother’s wife, because it is exposing your brother to shame.^&#42;1^

[NOTE]
====
. Lit., “it is your brother’s nakedness.”
====

[[v3-18-17]]

^<<v3-18-17,17>>^ “‘You must not have sexual relations with a woman and her daughter. You must not take the daughter of her son and the daughter of her daughter in order to have relations. They are her close relatives; it is an obscene act.^&#42;1^

[NOTE]
====
. Or “shameful conduct; lewdness.”
====

[[v3-18-18]]

^<<v3-18-18,18>>^ “‘You must not take a woman in addition to her sister as a rival wife and have sexual relations with her while her sister is alive.

[[v3-18-19]]

^<<v3-18-19,19>>^ “‘You must not approach a woman during her menstrual impurity to have sexual relations with her.

[[v3-18-20]]

^<<v3-18-20,20>>^ “‘You must not have sexual intercourse with the wife of your fellow man,^&#42;1^ making yourself unclean.

[NOTE]
====
. Or “your neighbor; your associate.”
====

[[v3-18-21]]

^<<v3-18-21,21>>^ “‘You must not allow any of your offspring to be offered^&#42;1^ to Moʹlech. You must not profane the name of your God in that way. I am Jehovah.

[NOTE]
====
. Or “devoted; sacrificed.”
====

[[v3-18-22]]

^<<v3-18-22,22>>^ “‘You must not lie down with a male in the same way that you lie down with a woman. It is a detestable act.

[[v3-18-23]]

^<<v3-18-23,23>>^ “‘A man must not have sexual intercourse with an animal to become unclean by it; nor should a woman offer herself to an animal to have intercourse with it. It is a violation of what is natural.

[[v3-18-24]]

^<<v3-18-24,24>>^ “‘Do not make yourselves unclean by any of these things, for it is by all these things that the nations that I am driving out from before you have made themselves unclean.

[[v3-18-25]]

^<<v3-18-25,25>>^ Therefore, the land is unclean, and I will bring punishment on it for its error, and the land will vomit its inhabitants out.

[[v3-18-26]]

^<<v3-18-26,26>>^ But you yourselves must keep my statutes and my judicial decisions, and you must not do any of these detestable things, whether a native or a foreigner who is residing among you.

[[v3-18-27]]

^<<v3-18-27,27>>^ For all these detestable things were done by the men who lived in the land before you, and now the land is unclean.

[[v3-18-28]]

^<<v3-18-28,28>>^ Then the land will not have to vomit you out for defiling it in the same way that it will vomit out the nations that were before you.

[[v3-18-29]]

^<<v3-18-29,29>>^ If anyone does any of these detestable things, all those^&#42;1^ doing them must be cut off^&#42;2^ from among their people.

[NOTE]
====
. Or “the souls.”
. Or “put to death.”
====

[[v3-18-30]]

^<<v3-18-30,30>>^ You must keep your obligation to me by not practicing any of the detestable customs that were carried on before you, so that you do not make yourselves unclean by them. I am Jehovah your God.’”

'''

xref:003-leviticus/003-leviticus-017.adoc#v3-17-0[&#60; Capítulo Anterior] | <<v3-18-0,Topo>> | xref:003-leviticus/003-leviticus-019.adoc#v3-19-0[Próximo Capítulo &#62;]