include::./index.adoc[]

[[v3-24-0]]
=== Leviticus, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-24-1]]

^<<v3-24-1,1>>^ Jehovah continued to speak to Moses, saying:

[[v3-24-2]]

^<<v3-24-2,2>>^ “Command the Israelites to bring to you pure, beaten olive oil for the lights, to keep the lamps lit constantly.

[[v3-24-3]]

^<<v3-24-3,3>>^ Outside the curtain of the Testimony in the tent of meeting, Aaron should arrange to keep the lamps lit from evening to morning before Jehovah constantly. It is a permanent statute for all your generations.

[[v3-24-4]]

^<<v3-24-4,4>>^ He should set the lamps in order on the lampstand of pure gold before Jehovah constantly.

[[v3-24-5]]

^<<v3-24-5,5>>^ “You will take fine flour and bake it into 12 ring-shaped loaves. Two tenths of an eʹphah^&#42;1^ should go into each loaf.

[NOTE]
====
. Two tenths of an ephah equaled 4.4 L (4 dry qt). See App. B14.
====

[[v3-24-6]]

^<<v3-24-6,6>>^ You will place them in two sets of layers, six to the layer set, on the table of pure gold before Jehovah.

[[v3-24-7]]

^<<v3-24-7,7>>^ You should put pure frankincense on each layer set, and it will serve as the bread for a token offering^&#42;1^ made by fire to Jehovah.

[NOTE]
====
. Or “as a memorial (representative) portion of it.”
====

[[v3-24-8]]

^<<v3-24-8,8>>^ On each Sabbath day, he should regularly arrange it before Jehovah. It is a lasting covenant with the Israelites.

[[v3-24-9]]

^<<v3-24-9,9>>^ It will become Aaron’s and his sons’, and they will eat it in a holy place, because it is something most holy for him from Jehovah’s offerings made by fire, as a lasting regulation.”

[[v3-24-10]]

^<<v3-24-10,10>>^ Now among the Israelites was a son of an Israelite woman and an Egyptian man, and a fight broke out between him and an Israelite man in the camp.

[[v3-24-11]]

^<<v3-24-11,11>>^ The son of the Israelite woman began to abuse the Name^&#42;1^ and to curse^&#42;2^ it. So they brought him to Moses. Incidentally, his mother was She·loʹmith, the daughter of Dibʹri of the tribe of Dan.

[NOTE]
====
. That is, the name Jehovah, as indicated by vss. 15 and 16.
. Or “call down evil upon.”
====

[[v3-24-12]]

^<<v3-24-12,12>>^ They placed him in custody until Jehovah’s decision was made clear to them.

[[v3-24-13]]

^<<v3-24-13,13>>^ Then Jehovah said to Moses:

[[v3-24-14]]

^<<v3-24-14,14>>^ “Bring the one who cursed to the outside of the camp, and all those who heard him must lay their hands on his head, and then the entire assembly must stone him.

[[v3-24-15]]

^<<v3-24-15,15>>^ And you should tell the Israelites, ‘If any man curses his God, he will answer for his sin.

[[v3-24-16]]

^<<v3-24-16,16>>^ So the abuser of Jehovah’s name should be put to death without fail. The entire assembly should stone him without fail. The foreign resident should be put to death the same as the native for his abusing the Name.

[[v3-24-17]]

^<<v3-24-17,17>>^ “‘If a man takes a human life,^&#42;1^ he should be put to death without fail.

[NOTE]
====
. Or “fatally strikes any human soul.”
====

[[v3-24-18]]

^<<v3-24-18,18>>^ Anyone who strikes and kills a domestic animal^&#42;1^ should make compensation for it, life for life.^&#42;2^

[NOTE]
====
. Or “And one who fatally strikes the soul of an animal.”
. Or “soul for soul.”
====

[[v3-24-19]]

^<<v3-24-19,19>>^ If a man injures his fellow man, then what he has done should be done to him.

[[v3-24-20]]

^<<v3-24-20,20>>^ Fracture for fracture, eye for eye, tooth for tooth, the same sort of injury he inflicted should be inflicted on him.

[[v3-24-21]]

^<<v3-24-21,21>>^ The man who strikes and kills an animal should make compensation for it, but the one who strikes and kills a man should be put to death.

[[v3-24-22]]

^<<v3-24-22,22>>^ “‘One judicial decision will apply for you, whether a foreign resident or a native, because I am Jehovah your God.’”

[[v3-24-23]]

^<<v3-24-23,23>>^ Moses then spoke to the Israelites, and they brought the one who uttered the curse to the outside of the camp, and they stoned him. Thus the Israelites did just as Jehovah had commanded Moses.

'''

xref:003-leviticus/003-leviticus-023.adoc#v3-23-0[&#60; Capítulo Anterior] | <<v3-24-0,Topo>> | xref:003-leviticus/003-leviticus-025.adoc#v3-25-0[Próximo Capítulo &#62;]