include::./index.adoc[]

[[v3-16-0]]
=== Leviticus, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v3-16-1]]

^<<v3-16-1,1>>^ Jehovah spoke to Moses after the death of Aaron’s two sons who died for approaching Jehovah.

[[v3-16-2]]

^<<v3-16-2,2>>^ Jehovah said to Moses: “Tell Aaron your brother that he may not come at just any time into the holy place inside the curtain, in front of the cover on the Ark, so that he may not die, for I will appear over the cover in a cloud.

[[v3-16-3]]

^<<v3-16-3,3>>^ “This is what Aaron should bring when he comes into the holy place: a young bull for a sin offering and a ram for a burnt offering.

[[v3-16-4]]

^<<v3-16-4,4>>^ He should put on the holy linen robe, and the linen shorts^&#42;1^ should cover his body,^&#42;2^ and he should wrap himself with the linen sash and his head with the linen turban. They are holy garments. He will bathe himself in water and put them on.

[NOTE]
====
. Or “undergarments.”
. Or “his exposed flesh.”
====

[[v3-16-5]]

^<<v3-16-5,5>>^ “He should take from the assembly of the Israelites two young male goats for a sin offering and one ram for a burnt offering.

[[v3-16-6]]

^<<v3-16-6,6>>^ “Aaron must then present the bull of the sin offering, which is for himself, and he will make atonement in behalf of himself and his house.

[[v3-16-7]]

^<<v3-16-7,7>>^ “He will then take the two goats and make them stand before Jehovah at the entrance of the tent of meeting.

[[v3-16-8]]

^<<v3-16-8,8>>^ Aaron will draw lots over the two goats, the one lot for Jehovah and the other lot for A·zaʹzel.^&#42;1^

[NOTE]
====
. Possibly meaning “Goat That Disappears.”
====

[[v3-16-9]]

^<<v3-16-9,9>>^ Aaron will present the goat that was designated by lot for Jehovah and make it a sin offering.

[[v3-16-10]]

^<<v3-16-10,10>>^ But the goat designated by lot for A·zaʹzel should be brought alive to stand before Jehovah in order to perform the atonement upon it, so that it may be sent away for A·zaʹzel into the wilderness.

[[v3-16-11]]

^<<v3-16-11,11>>^ “Aaron will present the bull of the sin offering, which is for himself, and make atonement in behalf of himself and his house; afterward he will slaughter the bull of the sin offering, which is for himself.

[[v3-16-12]]

^<<v3-16-12,12>>^ “He will then take the fire holder full of burning coals from the altar before Jehovah and two handfuls of fine perfumed incense, and he will bring them inside the curtain.

[[v3-16-13]]

^<<v3-16-13,13>>^ He will also put the incense on the fire before Jehovah, and the cloud of the incense will envelop the Ark cover, which is on the Testimony, so that he may not die.

[[v3-16-14]]

^<<v3-16-14,14>>^ “He will take some of the bull’s blood and spatter it with his finger in front of the cover on the east side, and he will spatter some of the blood with his finger seven times before the cover.

[[v3-16-15]]

^<<v3-16-15,15>>^ “He will then slaughter the goat of the sin offering, which is for the people, and bring its blood inside the curtain and do with its blood the same as he did with the bull’s blood; he is to spatter it toward the cover and before the cover.

[[v3-16-16]]

^<<v3-16-16,16>>^ “He must make atonement for the holy place concerning the acts of uncleanness of the Israelites and concerning their transgressions and their sins, and that is what he should do for the tent of meeting, which is located among them in the midst of their acts of uncleanness.

[[v3-16-17]]

^<<v3-16-17,17>>^ “No other man should be in the tent of meeting from the time he goes in to make atonement in the holy place until he comes out. He will make atonement in behalf of himself and his house and in behalf of the entire congregation of Israel.

[[v3-16-18]]

^<<v3-16-18,18>>^ “He will then come out to the altar, which is before Jehovah, and make atonement for it, and he will take some of the bull’s blood and some of the goat’s blood and put it on the horns of the altar on all sides.

[[v3-16-19]]

^<<v3-16-19,19>>^ He will also spatter some of the blood on it with his finger seven times and cleanse it and sanctify it from the acts of uncleanness of the Israelites.

[[v3-16-20]]

^<<v3-16-20,20>>^ “When he has finished making atonement for the holy place and the tent of meeting and the altar, he will also present the live goat.

[[v3-16-21]]

^<<v3-16-21,21>>^ Aaron will lay both his hands on the head of the live goat and confess over it all the errors of the Israelites and all their transgressions and all their sins, and he will put them on the head of the goat and send it away into the wilderness by the hand of a man designated to do this.^&#42;1^

[NOTE]
====
. Or “a man standing ready.”
====

[[v3-16-22]]

^<<v3-16-22,22>>^ The goat will carry upon itself all their errors into a desert land, and he will send the goat away into the wilderness.

[[v3-16-23]]

^<<v3-16-23,23>>^ “Aaron will then enter into the tent of meeting and take off the linen garments that he put on when he went into the holy place, and he will lay them down there.

[[v3-16-24]]

^<<v3-16-24,24>>^ He must bathe himself^&#42;1^ in water in a holy place and put on his garments; then he will come out and offer up his burnt offering and the people’s burnt offering and make atonement in his own behalf and in behalf of the people.

[NOTE]
====
. Lit., “his flesh.”
====

[[v3-16-25]]

^<<v3-16-25,25>>^ He will make the fat of the sin offering smoke on the altar.

[[v3-16-26]]

^<<v3-16-26,26>>^ “The man who sent away the goat for A·zaʹzel should wash his garments and bathe himself in water, and after that he may come into the camp.

[[v3-16-27]]

^<<v3-16-27,27>>^ “And the bull of the sin offering and the goat of the sin offering, whose blood was brought into the holy place to make atonement, will be taken outside the camp, and their skins and their flesh and their dung will be burned in the fire.

[[v3-16-28]]

^<<v3-16-28,28>>^ The one who burns them should wash his garments and bathe himself in water, and after that he may come into the camp.

[[v3-16-29]]

^<<v3-16-29,29>>^ “It will serve as a lasting statute for you: In the seventh month, on the tenth of the month, you should afflict yourselves,^&#42;1^ and you must not do any work, whether a native or a foreigner who is residing among you.

[NOTE]
====
. Or “your souls.” To “afflict oneself” is generally understood to mean various forms of self-denial, including fasting.
====

[[v3-16-30]]

^<<v3-16-30,30>>^ On this day atonement will be made for you, to declare you clean. You will be clean from all your sins before Jehovah.

[[v3-16-31]]

^<<v3-16-31,31>>^ It is a sabbath of complete rest for you, and you should afflict yourselves.^&#42;1^ It is a lasting statute.

[NOTE]
====
. Or “your souls.”
====

[[v3-16-32]]

^<<v3-16-32,32>>^ “The priest who is anointed and installed^&#42;1^ to serve as priest in place of his father will make atonement and put on the linen garments, the holy garments.

[NOTE]
====
. Lit., “whose hand will be filled.”
====

[[v3-16-33]]

^<<v3-16-33,33>>^ He will make atonement for the holy sanctuary, the tent of meeting, and the altar; and he will make atonement for the priests and for all the people of the congregation.

[[v3-16-34]]

^<<v3-16-34,34>>^ This will serve as a lasting statute for you, to make atonement for the Israelites concerning all their sins once each year.”
So he did just as Jehovah had commanded Moses.

'''

xref:003-leviticus/003-leviticus-015.adoc#v3-15-0[&#60; Capítulo Anterior] | <<v3-16-0,Topo>> | xref:003-leviticus/003-leviticus-017.adoc#v3-17-0[Próximo Capítulo &#62;]