include::./index.adoc[]

[[v39-2-0]]
=== Malachi, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v39-2-1]]

^<<v39-2-1,1>>^ “And now, O priests, this commandment is for you.

[[v39-2-2]]

^<<v39-2-2,2>>^ If you refuse to listen and to take it to heart to glorify my name,” says Jehovah of armies, “I will send on you the curse, and I will turn your blessings into curses. Yes, I have turned the blessings into curses, because you are not taking it to heart.”

[[v39-2-3]]

^<<v39-2-3,3>>^ “Look! I will ruin^&#42;1^ your sown seed because of you, and I will scatter dung on your faces, the dung of your festivals; and you will be carried away to it.^&#42;2^

[NOTE]
====
. Lit., “rebuke.”
. That is, to the place where dung from sacrifices was deposited.
====

[[v39-2-4]]

^<<v39-2-4,4>>^ Then you will know that I have given this commandment to you so that my covenant with Leʹvi may continue,” says Jehovah of armies.

[[v39-2-5]]

^<<v39-2-5,5>>^ “My covenant with him was one of life and of peace, which I gave to him, along with fear.^&#42;1^ He feared me, yes, he stood in awe of my name.

[NOTE]
====
. Or “respect; reverence.”
====

[[v39-2-6]]

^<<v39-2-6,6>>^ The law^&#42;1^ of truth was in his mouth, and no unrighteousness was found on his lips. He walked with me in peace and in uprightness, and he turned many back from error.

[NOTE]
====
. Or “instruction.”
====

[[v39-2-7]]

^<<v39-2-7,7>>^ For the lips of a priest should safeguard knowledge, and people should seek the law^&#42;1^ from his mouth, because he is the messenger of Jehovah of armies.

[NOTE]
====
. Or “instruction.”
====

[[v39-2-8]]

^<<v39-2-8,8>>^ “But you yourselves have turned aside from the way. You have made many stumble with regard to the law.^&#42;1^ You have ruined the covenant of Leʹvi,” says Jehovah of armies.

[NOTE]
====
. Or possibly, “by your instruction.”
====

[[v39-2-9]]

^<<v39-2-9,9>>^ “So I will make you despised and low before all the people, because you did not keep my ways but showed partiality in applying the law.”

[[v39-2-10]]

^<<v39-2-10,10>>^ “Do we not all have one father? Was it not one God who created us? So why do we deal treacherously with one another, profaning the covenant of our forefathers?

[[v39-2-11]]

^<<v39-2-11,11>>^ Judah has dealt treacherously, and something detestable has been done in Israel and in Jerusalem; for Judah has profaned the holiness^&#42;1^ of Jehovah, which He loves, and he has taken as a bride the daughter of a foreign god.

[NOTE]
====
. Or possibly, “the sanctuary.”
====

[[v39-2-12]]

^<<v39-2-12,12>>^ Jehovah will cut off from the tents of Jacob anyone who does this, whoever he may be,^&#42;1^ though he presents a gift offering to Jehovah of armies.”

[NOTE]
====
. Lit., “one who is awake and one who answers.”
====

[[v39-2-13]]

^<<v39-2-13,13>>^ “And there is another^&#42;1^ thing that you do, which results in covering the altar of Jehovah with tears and with weeping and sighing, so that he no longer pays attention to your gift offering or looks favorably on anything from your hand.

[NOTE]
====
. Lit., “a second.”
====

[[v39-2-14]]

^<<v39-2-14,14>>^ And you say, ‘For what reason?’ It is because Jehovah has acted as a witness between you and the wife of your youth, with whom you have dealt treacherously, although she is your partner and your wife by covenant.^&#42;1^

[NOTE]
====
. Or “your legal wife.”
====

[[v39-2-15]]

^<<v39-2-15,15>>^ But there was one who did not do it, for he had what remained of the spirit. And what was that one seeking? The offspring^&#42;1^ of God. So guard yourselves respecting your spirit, and do not deal treacherously with the wife of your youth.

[NOTE]
====
. Lit., “seed.”
====

[[v39-2-16]]

^<<v39-2-16,16>>^ For I hate^&#42;1^ divorce,” says Jehovah the God of Israel, “and the one who covers his garment with violence,”^&#42;2^ says Jehovah of armies. “And guard yourselves respecting your spirit, and you must not deal treacherously.

[NOTE]
====
. Lit., “he hates.”
. Or “who engages in violence.”
====

[[v39-2-17]]

^<<v39-2-17,17>>^ “You have made Jehovah weary with your words. But you say, ‘How have we made him weary?’ By saying, ‘Everyone who does bad is good in the eyes of Jehovah, and he finds pleasure in him,’ or by saying, ‘Where is the God of justice?’”

'''

xref:039-malachi/039-malachi-001.adoc#v39-1-0[&#60; Capítulo Anterior] | <<v39-2-0,Topo>> | xref:039-malachi/039-malachi-003.adoc#v39-3-0[Próximo Capítulo &#62;]