include::./index.adoc[]

[[v39-4-0]]
=== Malachi, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v39-4-1]]

^<<v39-4-1,1>>^ “For look! the day is coming, burning like a furnace, when all the presumptuous ones and all those practicing wickedness will become like stubble. The coming day will certainly devour them,” says Jehovah of armies, “and it will leave them neither root nor branch.

[[v39-4-2]]

^<<v39-4-2,2>>^ But on you who honor^&#42;1^ my name, the sun of righteousness will shine, with healing in its rays;^&#42;2^ and you will skip about like fattened calves.”

[NOTE]
====
. Lit., “fear.”
. Lit., “wings.”
====

[[v39-4-3]]

^<<v39-4-3,3>>^ “And you will tread the wicked underfoot, for they will be like dust under the soles of your feet on the day when I take action,” says Jehovah of armies.

[[v39-4-4]]

^<<v39-4-4,4>>^ “Remember the Law of my servant Moses, the regulations and judgments that I commanded at Horʹeb for all Israel to obey.

[[v39-4-5]]

^<<v39-4-5,5>>^ “Look! I am sending to you E·liʹjah the prophet before the coming of the great and awe-inspiring day of Jehovah.

[[v39-4-6]]

^<<v39-4-6,6>>^ And he will turn the hearts of fathers back toward sons, and the hearts of sons back toward fathers, so that I may not come and strike the earth, devoting it to destruction.”

_(End of the translation of the Hebrew-Aramaic Scriptures, to be followed by that of the Christian Greek Scriptures)_

'''

xref:039-malachi/039-malachi-003.adoc#v39-3-0[&#60; Capítulo Anterior] | <<v39-4-0,Topo>> | xref:040-matthew/040-matthew-001.adoc#v40-1-0[Próximo Capítulo &#62;]