include::./index.adoc[]

[[v39-3-0]]
=== Malachi, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v39-3-1]]

^<<v39-3-1,1>>^ “Look! I am sending my messenger, and he will clear up^&#42;1^ a way before me. And suddenly the true Lord, whom you are seeking, will come to his temple; and the messenger of the covenant will come, in whom you take delight. Look! He will certainly come,” says Jehovah of armies.

[NOTE]
====
. Or “prepare.”
====

[[v39-3-2]]

^<<v39-3-2,2>>^ “But who will endure the day of his coming, and who will be able to stand when he appears? For he will be like the fire of a refiner and like the lye^&#42;1^ of laundrymen.

[NOTE]
====
. Or “soap.”
====

[[v39-3-3]]

^<<v39-3-3,3>>^ And he will sit as a refiner and cleanser of silver and will cleanse the sons of Leʹvi; and he will clarify^&#42;1^ them like gold and like silver, and they will certainly become to Jehovah people presenting a gift offering in righteousness.

[NOTE]
====
. Or “refine.”
====

[[v39-3-4]]

^<<v39-3-4,4>>^ And the gift offering of Judah and of Jerusalem will actually be pleasing^&#42;1^ to Jehovah, as in the days of long ago and as in the years of antiquity.

[NOTE]
====
. Or “gratifying.”
====

[[v39-3-5]]

^<<v39-3-5,5>>^ “I will come near to you for judgment, and I will be a swift witness against the sorcerers, against the adulterers, against those who take false oaths, against those who defraud the hired worker, the widow, and the fatherless child,^&#42;1^ and against those who refuse to help^&#42;2^ the foreigner. These have not feared me,” says Jehovah of armies.

[NOTE]
====
. Or “the orphan.”
. Or “who deny the rights of.”
====

[[v39-3-6]]

^<<v39-3-6,6>>^ “For I am Jehovah; I do not change.^&#42;1^ And you are sons of Jacob; you have not yet come to your finish.

[NOTE]
====
. Or “I have not changed.”
====

[[v39-3-7]]

^<<v39-3-7,7>>^ From the days of your forefathers you have turned aside from my regulations and have not kept them. Return to me, and I will return to you,” says Jehovah of armies.
But you say: “How are we supposed to return?”

[[v39-3-8]]

^<<v39-3-8,8>>^ “Will a mere human rob God? But you are robbing me.”
And you say: “How have we robbed you?”
“In the tithes^&#42;1^ and in the contributions.

[NOTE]
====
. Or “tenth parts.”
====

[[v39-3-9]]

^<<v39-3-9,9>>^ You are certainly cursed,^&#42;1^ for you are robbing me—yes, the entire nation is doing so.

[NOTE]
====
. Or possibly, “With a curse you are cursing me.”
====

[[v39-3-10]]

^<<v39-3-10,10>>^ Bring the entire tithe^&#42;1^ into the storehouse, so that there may be food in my house; and test me out, please, in this regard,” Jehovah of armies says, “to see whether I will not open to you the floodgates of the heavens and pour out^&#42;2^ on you a blessing until there is nothing lacking.”

[NOTE]
====
. Or “all the tenth parts.”
. Lit., “empty out.”
====

[[v39-3-11]]

^<<v39-3-11,11>>^ “And I will rebuke the devouring one^&#42;1^ for you, and it will not ruin the fruit of your land, nor will the vine in your field be fruitless,” says Jehovah of armies.

[NOTE]
====
. Apparently referring to insect plagues.
====

[[v39-3-12]]

^<<v39-3-12,12>>^ “All the nations will have to declare you happy, for you will become a land of delight,” says Jehovah of armies.

[[v39-3-13]]

^<<v39-3-13,13>>^ “Your words against me have been strong,” says Jehovah.
And you say: “How have we spoken against you among ourselves?”

[[v39-3-14]]

^<<v39-3-14,14>>^ “You say, ‘It is of no value to serve God. How have we benefited by keeping our obligations to him and by walking somberly before Jehovah of armies?

[[v39-3-15]]

^<<v39-3-15,15>>^ Now we consider presumptuous people happy. Also, those who practice wickedness are successful. They dare to put God to the test and get away with it.’”

[[v39-3-16]]

^<<v39-3-16,16>>^ At that time those who fear Jehovah spoke with one another, each one with his companion, and Jehovah kept paying attention and listening. And a book of remembrance was written before him for those fearing Jehovah and for those meditating on^&#42;1^ his name.

[NOTE]
====
. Or “thinking on.” Or possibly, “treasuring.”
====

[[v39-3-17]]

^<<v39-3-17,17>>^ “And they will be mine,” says Jehovah of armies, “in the day when I produce a special property.^&#42;1^ I will show them compassion, just as a man shows compassion to his son who serves him.

[NOTE]
====
. Or “a treasured possession.”
====

[[v39-3-18]]

^<<v39-3-18,18>>^ And you will again see the distinction between a righteous person and a wicked person, between one serving God and one not serving him.”

'''

xref:039-malachi/039-malachi-002.adoc#v39-2-0[&#60; Capítulo Anterior] | <<v39-3-0,Topo>> | xref:039-malachi/039-malachi-004.adoc#v39-4-0[Próximo Capítulo &#62;]