include::./index.adoc[]

[[v39-1-0]]
=== Malachi, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v39-1-1]]

^<<v39-1-1,1>>^ A pronouncement:
The word of Jehovah to Israel through Malʹa·chi:^&#42;1^

[NOTE]
====
. Meaning “My Messenger.”
====

[[v39-1-2]]

^<<v39-1-2,2>>^ “I have shown love to you people,” says Jehovah.
But you say: “How have you shown us love?”
“Was not Eʹsau the brother of Jacob?” declares Jehovah. “But I loved Jacob,

[[v39-1-3]]

^<<v39-1-3,3>>^ and Eʹsau I hated; and I made his mountains desolate and left his inheritance for the jackals of the wilderness.”

[[v39-1-4]]

^<<v39-1-4,4>>^ “Though Eʹdom says, ‘We have been shattered, but we will return and rebuild the ruins,’ this is what Jehovah of armies says, ‘They will build, but I will tear down, and they will be called “the territory of wickedness” and “the people whom Jehovah has forever condemned.”

[[v39-1-5]]

^<<v39-1-5,5>>^ Your own eyes will see it, and you will say: “May Jehovah be magnified over the territory of Israel.”’”

[[v39-1-6]]

^<<v39-1-6,6>>^ “‘A son honors a father, and a servant his master. So if I am a father, where is the honor due me? And if I am a master,^&#42;1^ where is the fear^&#42;2^ due me?’ Jehovah of armies says to you priests who are despising my name.
“‘But you say: “How have we despised your name?”’

[NOTE]
====
. Or “grand master.”
. Or “respect.”
====

[[v39-1-7]]

^<<v39-1-7,7>>^ “‘By presenting polluted food^&#42;1^ on my altar.’
“‘And you say: “How have we polluted you?”’
“‘By saying: “The table of Jehovah is something to be despised.”

[NOTE]
====
. Lit., “bread.”
====

[[v39-1-8]]

^<<v39-1-8,8>>^ And when you present a blind animal as a sacrifice, you say: “It is nothing bad.” And when you present a lame animal or a sick one: “It is nothing bad.”’”
“Try presenting them, please, to your governor. Will he be pleased with you or receive you with favor?” says Jehovah of armies.

[[v39-1-9]]

^<<v39-1-9,9>>^ “And now, please, appeal to^&#42;1^ God, that he may show us favor. With such offerings from your own hand, will he receive any of you with favor?” says Jehovah of armies.

[NOTE]
====
. Or “soften the face of.”
====

[[v39-1-10]]

^<<v39-1-10,10>>^ “And who among you is willing to shut the doors?^&#42;1^ For you will not even light my altar without charge. I find no delight in you,” says Jehovah of armies, “and I take no pleasure in any gift offering from your hand.”

[NOTE]
====
. Evidently, the doors of the temple, as a duty.
====

[[v39-1-11]]

^<<v39-1-11,11>>^ “For from the rising of the sun to its setting,^&#42;1^ my name will be great among the nations. In every place sacrifices will be made to smoke, and offerings will be made to my name, as a pure gift; because my name will be great among the nations,” says Jehovah of armies.

[NOTE]
====
. Or “from east to west.”
====

[[v39-1-12]]

^<<v39-1-12,12>>^ “But you are profaning it^&#42;1^ by saying, ‘The table of Jehovah is polluted, and its fruit, its food, is to be despised.’

[NOTE]
====
. Or possibly, “profaning me.”
====

[[v39-1-13]]

^<<v39-1-13,13>>^ You also say, ‘Look! How tiresome!’ and you sniff scornfully at it,” says Jehovah of armies. “And you bring stolen, lame, and sick animals. Yes, you bring such things as a gift! Should I accept it from your hand?” says Jehovah.

[[v39-1-14]]

^<<v39-1-14,14>>^ “Cursed is the cunning one who has a sound male animal in his flock, but he makes a vow and sacrifices a blemished^&#42;1^ one to Jehovah. For I am a great King,” says Jehovah of armies, “and my name will be awe-inspiring among the nations.”

[NOTE]
====
. Or “defective.”
====

'''

xref:038-zechariah/038-zechariah-014.adoc#v38-14-0[&#60; Capítulo Anterior] | <<v39-1-0,Topo>> | xref:039-malachi/039-malachi-002.adoc#v39-2-0[Próximo Capítulo &#62;]