include::./index.adoc[]

[[v36-3-0]]
=== Zephaniah, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v36-3-1]]

^<<v36-3-1,1>>^ Woe to the rebellious, the polluted, the oppressive city!

[[v36-3-2]]

^<<v36-3-2,2>>^ She has obeyed no voice; she has accepted no discipline.
In Jehovah she has not trusted; she has not drawn near to her God.

[[v36-3-3]]

^<<v36-3-3,3>>^ Her princes within her are roaring lions.
Her judges are wolves in the night;
They do not leave even a bone to gnaw until morning.

[[v36-3-4]]

^<<v36-3-4,4>>^ Her prophets are insolent, treacherous men.
Her priests defile what is holy;
They do violence to the law.

[[v36-3-5]]

^<<v36-3-5,5>>^ Jehovah is righteous in her midst; he does no wrong.
Morning by morning he makes known his judgments,
As unfailing as the daylight.
But the unrighteous one knows no shame.

[[v36-3-6]]

^<<v36-3-6,6>>^ “I destroyed nations; their corner towers were left desolate.
I devastated their streets, so that no one was passing through.
Their cities were left in ruins, without a man, without an inhabitant.

[[v36-3-7]]

^<<v36-3-7,7>>^ I said, ‘Surely you will fear me and accept discipline,’^&#42;1^
So that her dwelling place might not be destroyed
—I must call her to account for^&#42;2^ all these things.
But they were all the more eager to act corruptly.

[NOTE]
====
. Or “correction.”
. Or “punish her for.”
====

[[v36-3-8]]

^<<v36-3-8,8>>^ ‘So keep yourselves in expectation of^&#42;1^ me,’ declares Jehovah,
‘Until the day when I rise up to take plunder,^&#42;2^
For my judicial decision is to gather nations, to assemble kingdoms,
To pour out on them my indignation, all my burning anger;
For by the fire of my zeal the whole earth will be consumed.

[NOTE]
====
. Or “wait patiently for.”
. Or possibly, “rise up as a witness.”
====

[[v36-3-9]]

^<<v36-3-9,9>>^ For then I will change the language of the peoples to a pure language,
So that all of them may call on the name of Jehovah,
To serve him shoulder to shoulder.’^&#42;1^

[NOTE]
====
. Or “worship him in unity.”
====

[[v36-3-10]]

^<<v36-3-10,10>>^ From the region of the rivers of E·thi·oʹpi·a,
Those entreating me, the daughter of my scattered ones, will bring a gift to me.

[[v36-3-11]]

^<<v36-3-11,11>>^ On that day you will not be put to shame
Because of all your deeds with which you rebelled against me,
For then I will remove the haughty boasters from among you;
And you will never again be haughty in my holy mountain.

[[v36-3-12]]

^<<v36-3-12,12>>^ I will allow a humble and lowly people to remain in your midst,
And they will take refuge in the name of Jehovah.

[[v36-3-13]]

^<<v36-3-13,13>>^ Those remaining of Israel will practice no unrighteousness;
They will not speak a lie, nor will a deceitful tongue be found in their mouths;
They will feed^&#42;1^ and lie down, and no one will make them afraid.”

[NOTE]
====
. Or “graze.”
====

[[v36-3-14]]

^<<v36-3-14,14>>^ Shout joyfully, O daughter of Zion!
Shout in triumph, O Israel!
Be joyful and rejoice with all your heart, O daughter of Jerusalem!

[[v36-3-15]]

^<<v36-3-15,15>>^ Jehovah has removed the judgments against you.
He has turned away your enemy.
The King of Israel, Jehovah, is in your midst.
You will fear calamity no more.

[[v36-3-16]]

^<<v36-3-16,16>>^ On that day it will be said to Jerusalem:
“Do not be afraid, O Zion.
Do not let your hands drop down.

[[v36-3-17]]

^<<v36-3-17,17>>^ Jehovah your God is in your midst.
As a mighty One, he will save.
He will exult over you with great joy.
He will become silent^&#42;1^ in his love.
He will rejoice over you with shouts of joy.

[NOTE]
====
. Or “quiet; at ease; satisfied.”
====

[[v36-3-18]]

^<<v36-3-18,18>>^ I will gather together those grieving over their absence from your festivals;
They were absent from you because of bearing reproach for her.

[[v36-3-19]]

^<<v36-3-19,19>>^ Look! At that time I will act against all those oppressing you;
And I will save the one limping,
And I will gather together the dispersed.
I will make them an object of praise and fame^&#42;1^
In all the land of their shame.

[NOTE]
====
. Lit., “a name.”
====

[[v36-3-20]]

^<<v36-3-20,20>>^ At that time I will bring you in,
At the time I gather you together.
For I will make you an object of fame^&#42;1^ and praise among all the peoples of the earth,
When I gather back your captives before your eyes,” says Jehovah.

[NOTE]
====
. Lit., “a name.”
====

'''

xref:036-zephaniah/036-zephaniah-002.adoc#v36-2-0[&#60; Capítulo Anterior] | <<v36-3-0,Topo>> | xref:037-haggai/037-haggai-001.adoc#v37-1-0[Próximo Capítulo &#62;]