include::./index.adoc[]

[[v36-2-0]]
=== Zephaniah, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v36-2-1]]

^<<v36-2-1,1>>^ Gather together, yes, gather yourselves,
O nation that feels no shame.

[[v36-2-2]]

^<<v36-2-2,2>>^ Before the decree takes effect,
Before the day passes by like chaff,
Before the burning anger of Jehovah comes upon you,
Before the day of Jehovah’s anger comes upon you,

[[v36-2-3]]

^<<v36-2-3,3>>^ Seek Jehovah, all you meek ones^&#42;1^ of the earth,
Who observe his righteous decrees.^&#42;2^
Seek righteousness, seek meekness.^&#42;3^
Probably^&#42;4^ you will be concealed on the day of Jehovah’s anger.

[NOTE]
====
. Or “humble ones.”
. Lit., “his judgment.”
. Or “humility.”
. Or “It may be that.”
====

[[v36-2-4]]

^<<v36-2-4,4>>^ For Gazʹa will be an abandoned city;
And Ashʹke·lon will be desolated.
Ashʹdod will be driven away in broad daylight,^&#42;1^
And Ekʹron will be uprooted.

[NOTE]
====
. Or “at high noon.”
====

[[v36-2-5]]

^<<v36-2-5,5>>^ “Woe to those who inhabit the seacoast, the nation of Cherʹe·thites!
The word of Jehovah is against you.
O Caʹnaan, land of the Phi·lisʹtines, I will destroy you,
So that there will be no inhabitant left.

[[v36-2-6]]

^<<v36-2-6,6>>^ And the seacoast will become pasture grounds,
With wells for shepherds and stone pens for sheep.

[[v36-2-7]]

^<<v36-2-7,7>>^ It will become a region for the remaining ones of the house of Judah;
There they will feed.
In the houses of Ashʹke·lon they will lie down in the evening.
For Jehovah their God will turn his attention to them,^&#42;1^
And he will gather back their captives.”

[NOTE]
====
. Or “will care for them.”
====

[[v36-2-8]]

^<<v36-2-8,8>>^ “I have heard the reproach by Moʹab and the insults of the Amʹmon·ites,
Who have taunted my people and made boasts against their territory.

[[v36-2-9]]

^<<v36-2-9,9>>^ Therefore as surely as I am alive,” declares Jehovah of armies, the God of Israel,
“Moʹab will become just like Sodʹom,
And the Amʹmon·ites like Go·morʹrah,
A place of nettles, a salt pit, and a permanent wasteland.
The remaining ones of my people will plunder them,
And the remnant of my nation will dispossess them.

[[v36-2-10]]

^<<v36-2-10,10>>^ This is what they will have instead of their pride,
Because they taunted and exalted themselves against the people of Jehovah of armies.

[[v36-2-11]]

^<<v36-2-11,11>>^ Jehovah will be awe-inspiring^&#42;1^ against them;
For he will bring to nothing^&#42;2^ all the gods of the earth,
And all the islands of the nations will bow down to^&#42;3^ him,
Each one from its place.

[NOTE]
====
. Or “terrifying.”
. Or “emaciate.”
. Or “worship.”
====

[[v36-2-12]]

^<<v36-2-12,12>>^ You E·thi·oʹpi·ans will also be slain by my sword.

[[v36-2-13]]

^<<v36-2-13,13>>^ He will stretch out his hand toward the north and destroy As·syrʹi·a,
And he will make Ninʹe·veh desolate, as dry as a desert.

[[v36-2-14]]

^<<v36-2-14,14>>^ Herds will lie down within her, all sorts of wild animals.^&#42;1^
Both pelican and porcupine will spend the night among her pillar capitals.
A voice will sing in the window.
There will be devastation at the threshold;
For he will expose the cedar panels.

[NOTE]
====
. Lit., “every beast of a nation.”
====

[[v36-2-15]]

^<<v36-2-15,15>>^ This is the proud city that was sitting in security,
That was saying in her heart, ‘I am the one, and there is nobody else.’
How she has become an object of horror,
A place for the wild animals to lie down!
Everyone passing by her will whistle and shake his fist.”

'''

xref:036-zephaniah/036-zephaniah-001.adoc#v36-1-0[&#60; Capítulo Anterior] | <<v36-2-0,Topo>> | xref:036-zephaniah/036-zephaniah-003.adoc#v36-3-0[Próximo Capítulo &#62;]