include::./index.adoc[]

[[v26-36-0]]
=== Ezekiel, 36
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-36-1]]

^<<v26-36-1,1>>^ “As for you, son of man, prophesy about the mountains of Israel and say, ‘O mountains of Israel, hear the word of Jehovah.

[[v26-36-2]]

^<<v26-36-2,2>>^ This is what the Sovereign Lord Jehovah says: “The enemy has said against you, ‘Aha! Even the ancient high places have become our possession!’”’

[[v26-36-3]]

^<<v26-36-3,3>>^ “So prophesy and say, ‘This is what the Sovereign Lord Jehovah says: “Because they have desolated and attacked you from every direction, so that you would become a possession of the survivors^&#42;1^ from among the nations and people keep talking about you and slandering you,

[NOTE]
====
. Lit., “remnant; remaining ones.”
====

[[v26-36-4]]

^<<v26-36-4,4>>^ therefore, O mountains of Israel, hear the word of the Sovereign Lord Jehovah! This is what the Sovereign Lord Jehovah says to the mountains and the hills, to the streams and the valleys, to the ruins that were desolated, and to the abandoned cities that have been plundered and ridiculed by the survivors of the nations around them;

[[v26-36-5]]

^<<v26-36-5,5>>^ to these the Sovereign Lord Jehovah says: ‘In the fire of my zeal I will speak against the survivors of the nations and against all Eʹdom, those who with great rejoicing and utter scorn^&#42;1^ have claimed my land as their own possession, to take over its pastures and to plunder it.’”’

[NOTE]
====
. Or “scorn in the soul.”
====

[[v26-36-6]]

^<<v26-36-6,6>>^ “So prophesy concerning the land of Israel, and say to the mountains and to the hills, to the streams and to the valleys, ‘This is what the Sovereign Lord Jehovah says: “Look! I will speak in my zeal and in my rage, because you have borne humiliation by the nations.”’

[[v26-36-7]]

^<<v26-36-7,7>>^ “Therefore this is what the Sovereign Lord Jehovah says: ‘I myself raise my hand in an oath that the surrounding nations will themselves bear their own shame.

[[v26-36-8]]

^<<v26-36-8,8>>^ But you, O mountains of Israel, will produce branches and bear your fruitage for my people Israel, for they will soon return.

[[v26-36-9]]

^<<v26-36-9,9>>^ For I am with you, and I will turn toward you, and you will be cultivated and sown with seed.

[[v26-36-10]]

^<<v26-36-10,10>>^ I will multiply your people—the whole house of Israel, all of it—and the cities will be inhabited and the ruins will be rebuilt.

[[v26-36-11]]

^<<v26-36-11,11>>^ Yes, I will multiply your people and your livestock; they will increase and be fruitful. And I will cause you to be inhabited as you were formerly, and I will make you prosper more than in the past; and you will have to know that I am Jehovah.

[[v26-36-12]]

^<<v26-36-12,12>>^ I will cause people—my people Israel—to walk upon you, and they will take possession of you. You will become their inheritance, and you will never again make them childless.’”

[[v26-36-13]]

^<<v26-36-13,13>>^ “This is what the Sovereign Lord Jehovah says: ‘Because they are saying to you, “You are a land that devours people and bereaves your nations of children,”’

[[v26-36-14]]

^<<v26-36-14,14>>^ ‘therefore, you will no longer devour people or make your nations childless,’ declares the Sovereign Lord Jehovah.

[[v26-36-15]]

^<<v26-36-15,15>>^ ‘I will not subject you to any more insults of the nations or make you bear the taunts of people, and you will no longer cause your nations to stumble,’ declares the Sovereign Lord Jehovah.”

[[v26-36-16]]

^<<v26-36-16,16>>^ And the word of Jehovah again came to me, saying:

[[v26-36-17]]

^<<v26-36-17,17>>^ “Son of man, when the house of Israel was dwelling in their land, they made it unclean by their ways and their dealings. Their ways were like the uncleanness of menstruation to me.

[[v26-36-18]]

^<<v26-36-18,18>>^ So I poured out my rage on them because of the blood that they had shed upon the land and because they made the land unclean with their disgusting idols.^&#42;1^

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v26-36-19]]

^<<v26-36-19,19>>^ So I scattered them among the nations and dispersed them among the lands. I judged them according to their way and according to their dealings.

[[v26-36-20]]

^<<v26-36-20,20>>^ But when they came to those nations, people profaned my holy name by saying about them, ‘These are the people of Jehovah, but they had to leave his land.’

[[v26-36-21]]

^<<v26-36-21,21>>^ So I will show concern for my holy name, which the house of Israel profaned among the nations where they have gone.”

[[v26-36-22]]

^<<v26-36-22,22>>^ “Therefore say to the house of Israel, ‘This is what the Sovereign Lord Jehovah says: “Not for your sakes am I acting, O house of Israel, but for my holy name, which you profaned among the nations where you have gone.”’

[[v26-36-23]]

^<<v26-36-23,23>>^ ‘I will certainly sanctify my great name, which was profaned among the nations, which you profaned among them; and the nations will have to know that I am Jehovah,’ declares the Sovereign Lord Jehovah, ‘when I am sanctified among you before their eyes.

[[v26-36-24]]

^<<v26-36-24,24>>^ I will take you from the nations and gather you back from all the lands and bring you into your land.

[[v26-36-25]]

^<<v26-36-25,25>>^ I will sprinkle clean water on you, and you will become clean; I will cleanse you from all your uncleanness and from all your disgusting idols.

[[v26-36-26]]

^<<v26-36-26,26>>^ I will give you a new heart and put a new spirit inside you. I will remove the heart of stone from your body and give you a heart of flesh.^&#42;1^

[NOTE]
====
. That is, one sensitive to God’s guidance.
====

[[v26-36-27]]

^<<v26-36-27,27>>^ I will put my spirit inside you, and I will cause you to walk in my regulations, and you will observe and carry out my judicial decisions.

[[v26-36-28]]

^<<v26-36-28,28>>^ Then you will dwell in the land that I gave to your forefathers, and you will be my people and I will be your God.’

[[v26-36-29]]

^<<v26-36-29,29>>^ “‘I will save you from all your uncleanness and summon the grain and make it abound, and I will not bring famine upon you.

[[v26-36-30]]

^<<v26-36-30,30>>^ I will make the fruitage of the tree and the produce of the field abound, so that you may never again suffer the disgrace of famine among the nations.

[[v26-36-31]]

^<<v26-36-31,31>>^ Then you will remember your evil ways and your deeds that were not good, and you will loathe yourselves because of your guilt and your detestable practices.

[[v26-36-32]]

^<<v26-36-32,32>>^ But know this: I am not doing this for your sakes,’ declares the Sovereign Lord Jehovah. ‘Instead, be ashamed and feel humiliated because of your ways, O house of Israel.’

[[v26-36-33]]

^<<v26-36-33,33>>^ “This is what the Sovereign Lord Jehovah says: ‘In the day that I cleanse you from all your guilt, I will cause the cities to be inhabited and the ruins to be rebuilt.

[[v26-36-34]]

^<<v26-36-34,34>>^ The desolate land that was lying desolate for everyone passing by to see will be cultivated.

[[v26-36-35]]

^<<v26-36-35,35>>^ And people will say: “The desolate land has become like the garden of Eʹden, and the cities that were in ruins and desolate and torn down are now fortified and inhabited.”

[[v26-36-36]]

^<<v26-36-36,36>>^ And the nations that are left remaining around you will have to know that I myself, Jehovah, have built what was torn down, and I have planted what was desolate. I myself, Jehovah, have spoken, and I have done it.’

[[v26-36-37]]

^<<v26-36-37,37>>^ “This is what the Sovereign Lord Jehovah says: ‘I will also let the house of Israel ask me to do this for them: I will multiply their people like a flock.

[[v26-36-38]]

^<<v26-36-38,38>>^ Like the flock of holy ones, like the flock of Jerusalem^&#42;1^ during her festivals, the cities that were in ruins will become full of flocks of people; and they will have to know that I am Jehovah.’”

[NOTE]
====
. Or possibly, “Like the sacrificial flocks of sheep in Jerusalem.”
====

'''

xref:026-ezekiel/026-ezekiel-035.adoc#v26-35-0[&#60; Capítulo Anterior] | <<v26-36-0,Topo>> | xref:026-ezekiel/026-ezekiel-037.adoc#v26-37-0[Próximo Capítulo &#62;]