include::./index.adoc[]

[[v26-19-0]]
=== Ezekiel, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-19-1]]

^<<v26-19-1,1>>^ “You must sing a dirge^&#42;1^ concerning the chieftains of Israel

[NOTE]
====
. Or “song of mourning.”
====

[[v26-19-2]]

^<<v26-19-2,2>>^ and say,
‘What was your mother? A lioness among lions.
She lay down among strong young lions^&#42;1^ and reared her cubs.

[NOTE]
====
. Or “among maned young lions.”
====

[[v26-19-3]]

^<<v26-19-3,3>>^ She raised one of her cubs, and he became a strong young lion.
He learned how to tear prey apart,
He even devoured humans.

[[v26-19-4]]

^<<v26-19-4,4>>^ Nations heard about him and caught him in their pit,
And they brought him to the land of Egypt with hooks.

[[v26-19-5]]

^<<v26-19-5,5>>^ She waited and eventually saw that there was no hope for his return.
So she took another of her cubs and sent him out as a strong young lion.

[[v26-19-6]]

^<<v26-19-6,6>>^ He also walked about among the lions and became a strong young lion.
He learned how to tear prey apart, and he even devoured humans.

[[v26-19-7]]

^<<v26-19-7,7>>^ He prowled among their fortified towers and devastated their cities,
So that the desolate land was filled with the sound of his roaring.

[[v26-19-8]]

^<<v26-19-8,8>>^ Nations from the surrounding districts came against him to cast their net over him,
And he was caught in their pit.

[[v26-19-9]]

^<<v26-19-9,9>>^ With hooks they put him in a cage and brought him to the king of Babylon.
There they confined him, so that his voice would no more be heard on the mountains of Israel.

[[v26-19-10]]

^<<v26-19-10,10>>^ Your mother was like a vine in your blood,^&#42;1^ planted by waters.
It bore fruit and was full of branches because of the abundant water.

[NOTE]
====
. Or possibly, “like a vine in your vineyard.”
====

[[v26-19-11]]

^<<v26-19-11,11>>^ It developed strong branches,^&#42;1^ fit for the scepters of rulers.
It grew and towered over the other trees,
And it became visible because of its height and because of the abundance of its foliage.

[NOTE]
====
. Or “rods.”
====

[[v26-19-12]]

^<<v26-19-12,12>>^ But in fury she was uprooted and thrown to the earth,
And an east wind dried up her fruit.
Her strong branches were torn off and became dry, and fire consumed them.

[[v26-19-13]]

^<<v26-19-13,13>>^ Now she is planted in the wilderness,
In a waterless, thirsty land.

[[v26-19-14]]

^<<v26-19-14,14>>^ The fire spread from her branches^&#42;1^ and consumed her shoots and her fruit,
And there was no strong branch left, no scepter for ruling.
“‘That is a dirge, and it will serve as a dirge.’”

[NOTE]
====
. Or “rods.”
====

'''

xref:026-ezekiel/026-ezekiel-018.adoc#v26-18-0[&#60; Capítulo Anterior] | <<v26-19-0,Topo>> | xref:026-ezekiel/026-ezekiel-020.adoc#v26-20-0[Próximo Capítulo &#62;]