include::./index.adoc[]

[[v26-45-0]]
=== Ezekiel, 45
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-45-1]]

^<<v26-45-1,1>>^ “‘When you allot the land as an inheritance, you should offer as a contribution to Jehovah a holy portion out of the land. Its length should be 25,000 cubits,^&#42;1^ and its width, 10,000 cubits. Its entire area^&#42;2^ will be a holy portion.

[NOTE]
====
. This refers to long cubits. See App. B14.
. Or “Within all its boundaries.”
====

[[v26-45-2]]

^<<v26-45-2,2>>^ Within this will be a square lot for the holy place measuring 500 cubits by 500 cubits,^&#42;1^ and it will have 50 cubits as pastures on each side.

[NOTE]
====
. Lit., “500 by 500.”
====

[[v26-45-3]]

^<<v26-45-3,3>>^ Out of this measurement you should measure the length of 25,000 and the width of 10,000, and within it will be the sanctuary, something most holy.

[[v26-45-4]]

^<<v26-45-4,4>>^ It will be a holy portion of the land for the priests, the ministers of the sanctuary, who approach to minister to Jehovah. It will be a place for their houses and a sacred place for the sanctuary.

[[v26-45-5]]

^<<v26-45-5,5>>^ “‘For the Levites, the ministers of the temple, there will be a portion 25,000 cubits long and 10,000 cubits wide, and they will have 20 dining rooms^&#42;1^ as a possession.

[NOTE]
====
. Or “20 chambers.”
====

[[v26-45-6]]

^<<v26-45-6,6>>^ “‘You should give as the possession of the city an area that is 25,000 cubits long (corresponding to the holy contribution) and 5,000 cubits wide. It will belong to all the house of Israel.

[[v26-45-7]]

^<<v26-45-7,7>>^ “‘And for the chieftain there will be land on both sides of the holy contribution and of the area allotted to the city. It will be next to the holy contribution and the possession of the city. It will be on the west side and on the east side. Its length from the western boundary to the eastern boundary will correspond to one of the tribal portions.

[[v26-45-8]]

^<<v26-45-8,8>>^ This land will become his possession in Israel. My chieftains will no longer mistreat my people, and they will give the land to the house of Israel according to their tribes.’

[[v26-45-9]]

^<<v26-45-9,9>>^ “This is what the Sovereign Lord Jehovah says: ‘You have gone far enough, chieftains of Israel!’
“‘Put an end to your violence and oppression, and do what is just and righteous. Stop seizing the property of my people,’ declares the Sovereign Lord Jehovah.

[[v26-45-10]]

^<<v26-45-10,10>>^ ‘You should use accurate scales, an accurate eʹphah measure^&#42;1^ and an accurate bath measure.^&#42;2^

[NOTE]
====
. See App. B14.
. See App. B14.
====

[[v26-45-11]]

^<<v26-45-11,11>>^ There should be a fixed measurement for the eʹphah measure and the bath measure. The bath measure should hold a tenth of a hoʹmer,^&#42;1^ and the eʹphah measure should hold a tenth of a hoʹmer. The hoʹmer will be the standard for measuring.

[NOTE]
====
. See App. B14.
====

[[v26-45-12]]

^<<v26-45-12,12>>^ The shekel^&#42;1^ is to be 20 geʹrahs.^&#42;2^ And 20 shekels plus 25 shekels plus 15 shekels will make up one maʹneh^&#42;3^ for you.’

[NOTE]
====
. See App. B14.
. See App. B14.
. Or “mina.” See App. B14.
====

[[v26-45-13]]

^<<v26-45-13,13>>^ “‘This is the contribution that you should offer: one sixth of an eʹphah from each hoʹmer of wheat and one sixth of an eʹphah from each hoʹmer of barley.

[[v26-45-14]]

^<<v26-45-14,14>>^ The allowance of the oil is to be based on the bath measure. The bath is a tenth of a cor,^&#42;1^ and ten baths are a hoʹmer, for ten baths equal a hoʹmer.

[NOTE]
====
. See App. B14.
====

[[v26-45-15]]

^<<v26-45-15,15>>^ And from the flock of the livestock of Israel, one sheep out of every 200 should be given. These will be for the grain offering, the whole burnt offering, and the communion sacrifices, in order to make atonement for the people,’ declares the Sovereign Lord Jehovah.

[[v26-45-16]]

^<<v26-45-16,16>>^ “‘All the people of the land will make this contribution to the chieftain in Israel.

[[v26-45-17]]

^<<v26-45-17,17>>^ But the chieftain will be responsible for the whole burnt offerings, the grain offering, and the drink offering during the festivals, the new moons, the Sabbaths, and all the designated festivals of the house of Israel. He will be the one to provide the sin offering, the grain offering, the whole burnt offering, and the communion sacrifices, in order to make atonement in behalf of the house of Israel.’

[[v26-45-18]]

^<<v26-45-18,18>>^ “This is what the Sovereign Lord Jehovah says: ‘In the first month, on the first day of the month, you should take a sound young bull of the herd, and you are to purify the sanctuary from sin.

[[v26-45-19]]

^<<v26-45-19,19>>^ The priest will take some of the blood of the sin offering and put it on the doorpost of the temple, on the four corners of the surrounding ledge of the altar, and on the doorpost of the gate of the inner courtyard.

[[v26-45-20]]

^<<v26-45-20,20>>^ That is what you will do on the seventh day of the month because of anyone who sins by mistake or through ignorance; and you are to make atonement for the temple.

[[v26-45-21]]

^<<v26-45-21,21>>^ “‘In the first month, on the 14th day of the month, you will observe the festival of the Passover. For seven days unleavened bread should be eaten.

[[v26-45-22]]

^<<v26-45-22,22>>^ On that day the chieftain will provide a young bull as a sin offering in his own behalf and in behalf of all the people of the land.

[[v26-45-23]]

^<<v26-45-23,23>>^ For the seven days of the festival he will provide as a whole burnt offering to Jehovah seven sound young bulls and seven sound rams each of the seven days, as well as a male goat each day as a sin offering.

[[v26-45-24]]

^<<v26-45-24,24>>^ He should also provide as a grain offering an eʹphah for each young bull and an eʹphah for each ram, as well as a hin^&#42;1^ of oil for each eʹphah.

[NOTE]
====
. See App. B14.
====

[[v26-45-25]]

^<<v26-45-25,25>>^ “‘In the seventh month, on the 15th day of the month, for seven days during the festival, he should provide the same sin offering, whole burnt offering, grain offering, and oil.’”

'''

xref:026-ezekiel/026-ezekiel-044.adoc#v26-44-0[&#60; Capítulo Anterior] | <<v26-45-0,Topo>> | xref:026-ezekiel/026-ezekiel-046.adoc#v26-46-0[Próximo Capítulo &#62;]