include::./index.adoc[]

[[v26-30-0]]
=== Ezekiel, 30
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-30-1]]

^<<v26-30-1,1>>^ And the word of Jehovah again came to me, saying:

[[v26-30-2]]

^<<v26-30-2,2>>^ “Son of man, prophesy and say, ‘This is what the Sovereign Lord Jehovah says:
“Wail, ‘Alas, the day is coming!’

[[v26-30-3]]

^<<v26-30-3,3>>^ For the day is near, yes, a day of Jehovah is near.
It will be a day of clouds, an appointed time of nations.

[[v26-30-4]]

^<<v26-30-4,4>>^ A sword will come against Egypt, and panic will overtake E·thi·oʹpi·a when the slain fall in Egypt;
Its wealth is taken and its foundations are torn down.

[[v26-30-5]]

^<<v26-30-5,5>>^ E·thi·oʹpi·a, Put, Lud, and all the mixed populations,^&#42;1^
And Chub, along with the sons of the land of the covenant,^&#42;2^
By the sword they will all fall.”’

[NOTE]
====
. Or “all those from other nations.”
. Perhaps a reference to Israelites who were allied with Egypt.
====

[[v26-30-6]]

^<<v26-30-6,6>>^ This is what Jehovah says:
‘The supporters of Egypt will also fall,
And its arrogant power will be brought down.’
“‘From Migʹdol to Sy·eʹne they will fall by the sword in the land,’ declares the Sovereign Lord Jehovah.

[[v26-30-7]]

^<<v26-30-7,7>>^ ‘They will be made the most desolate of lands, and its own cities will become the most devastated cities.

[[v26-30-8]]

^<<v26-30-8,8>>^ And they will have to know that I am Jehovah when I set a fire in Egypt and all its allies are crushed.

[[v26-30-9]]

^<<v26-30-9,9>>^ In that day I will send messengers in ships to make self-confident E·thi·oʹpi·a tremble; panic will seize them in the day that is coming upon Egypt, for it will surely come.’

[[v26-30-10]]

^<<v26-30-10,10>>^ “This is what the Sovereign Lord Jehovah says: ‘I will bring an end to Egypt’s hordes by the hand of King Neb·u·chad·nezʹzar^&#42;1^ of Babylon.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v26-30-11]]

^<<v26-30-11,11>>^ He and his troops, the most ruthless of the nations, will be brought in to destroy the land. They will draw their swords against Egypt and fill the land with the slain.

[[v26-30-12]]

^<<v26-30-12,12>>^ I will turn the canals of the Nile into dry ground and will sell the land into the hand of wicked men. I will make the land and everything in it desolate by the hand of foreigners. I myself, Jehovah, have spoken.’

[[v26-30-13]]

^<<v26-30-13,13>>^ “This is what the Sovereign Lord Jehovah says: ‘I will also destroy the disgusting idols^&#42;1^ and bring an end to the worthless gods of Noph.^&#42;2^ There will no longer be a prince^&#42;3^ from the land of Egypt, and I will put fear in the land of Egypt.

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
. Or “Memphis.”
. Or “chieftain.”
====

[[v26-30-14]]

^<<v26-30-14,14>>^ I will desolate Pathʹros and set a fire in Zoʹan and execute judgment on No.^&#42;1^

[NOTE]
====
. That is, Thebes.
====

[[v26-30-15]]

^<<v26-30-15,15>>^ I will pour out my rage on Sin, the stronghold of Egypt, and destroy the population of No.

[[v26-30-16]]

^<<v26-30-16,16>>^ I will set a fire in Egypt; and Sin will be seized with terror and No will be broken through and Noph^&#42;1^ will face attack in broad daylight!

[NOTE]
====
. Or “Memphis.”
====

[[v26-30-17]]

^<<v26-30-17,17>>^ The young men of On^&#42;1^ and Pi·beʹseth will fall by the sword, and the cities will go into captivity.

[NOTE]
====
. That is, Heliopolis.
====

[[v26-30-18]]

^<<v26-30-18,18>>^ In Te·haphʹne·hes the day will grow dark when I break the yoke bars of Egypt there. Her arrogant power will come to an end, clouds will cover her, and her towns will go into captivity.

[[v26-30-19]]

^<<v26-30-19,19>>^ I will execute judgment on Egypt, and they will have to know that I am Jehovah.’”

[[v26-30-20]]

^<<v26-30-20,20>>^ And in the 11th year, in the first month, on the seventh day of the month, the word of Jehovah came to me, saying:

[[v26-30-21]]

^<<v26-30-21,21>>^ “Son of man, I have broken the arm of Pharʹaoh king of Egypt; it will not be bound up to be healed or wrapped with a bandage to make it strong enough to take up the sword.”

[[v26-30-22]]

^<<v26-30-22,22>>^ “Therefore this is what the Sovereign Lord Jehovah says: ‘Here I am against Pharʹaoh king of Egypt, and I will break his arms, the strong one and the broken one, and I will make the sword fall from his hand.

[[v26-30-23]]

^<<v26-30-23,23>>^ Then I will scatter the Egyptians among the nations and disperse them among the lands.

[[v26-30-24]]

^<<v26-30-24,24>>^ I will strengthen the arms^&#42;1^ of the king of Babylon and put my sword into his hand, and I will break the arms of Pharʹaoh, and he will groan loudly like a dying man before him.^&#42;2^

[NOTE]
====
. Or “increase the power.”
. That is, before the king of Babylon.
====

[[v26-30-25]]

^<<v26-30-25,25>>^ I will strengthen the arms of the king of Babylon, but the arms of Pharʹaoh will fall limp; and they will have to know that I am Jehovah when I put my sword into the hand of the king of Babylon and he wields it against the land of Egypt.

[[v26-30-26]]

^<<v26-30-26,26>>^ And I will scatter the Egyptians among the nations and disperse them among the lands, and they will have to know that I am Jehovah.’”

'''

xref:026-ezekiel/026-ezekiel-029.adoc#v26-29-0[&#60; Capítulo Anterior] | <<v26-30-0,Topo>> | xref:026-ezekiel/026-ezekiel-031.adoc#v26-31-0[Próximo Capítulo &#62;]