include::./index.adoc[]

[[v26-25-0]]
=== Ezekiel, 25
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-25-1]]

^<<v26-25-1,1>>^ The word of Jehovah again came to me, saying:

[[v26-25-2]]

^<<v26-25-2,2>>^ “Son of man, turn your face toward the Amʹmon·ites, and prophesy against them.

[[v26-25-3]]

^<<v26-25-3,3>>^ You must say concerning the Amʹmon·ites, ‘Hear the word of the Sovereign Lord Jehovah. This is what the Sovereign Lord Jehovah says: “Because you said ‘Aha!’ against my sanctuary when it was profaned, and against the land of Israel when it was laid desolate, and against the house of Judah when they went into exile,

[[v26-25-4]]

^<<v26-25-4,4>>^ therefore I am giving you to the people of the East as a possession. They will set up their encampments^&#42;1^ within you and pitch their tents among you. They will eat your fruitage, and they will drink your milk.

[NOTE]
====
. Or “walled camps.”
====

[[v26-25-5]]

^<<v26-25-5,5>>^ I will make Rabʹbah a pasture ground for camels, and the land of the Amʹmon·ites a resting-place for the flock; and you will have to know that I am Jehovah.”’”

[[v26-25-6]]

^<<v26-25-6,6>>^ “For this is what the Sovereign Lord Jehovah says: ‘Because you clapped your hands and stamped your feet and you^&#42;1^ rejoiced over the land of Israel with such utter scorn,

[NOTE]
====
. Or “your soul.”
====

[[v26-25-7]]

^<<v26-25-7,7>>^ therefore I will stretch out my hand against you to give you to the nations as something to plunder. I will cut you off from the peoples and destroy you from the lands. I will annihilate you, and you will have to know that I am Jehovah.’

[[v26-25-8]]

^<<v26-25-8,8>>^ “This is what the Sovereign Lord Jehovah says: ‘Because Moʹab and Seʹir have said, “Look! The house of Judah is like all the other nations,”

[[v26-25-9]]

^<<v26-25-9,9>>^ I am exposing Moʹab’s flank^&#42;1^ at his frontier cities, the beauty^&#42;2^ of his land, Beth-jeshʹi·moth, Baʹal-meʹon, and clear to Kir·i·a·thaʹim.

[NOTE]
====
. Or “slope.”
. Or “decoration.”
====

[[v26-25-10]]

^<<v26-25-10,10>>^ I will give it along with the Amʹmon·ites as a possession to the people of the East, so that the Amʹmon·ites will not be remembered among the nations.

[[v26-25-11]]

^<<v26-25-11,11>>^ And I will execute judgment in Moʹab, and they will have to know that I am Jehovah.’

[[v26-25-12]]

^<<v26-25-12,12>>^ “This is what the Sovereign Lord Jehovah says: ‘Eʹdom has acted vengefully against the house of Judah and has incurred great guilt in taking revenge on them;

[[v26-25-13]]

^<<v26-25-13,13>>^ therefore this is what the Sovereign Lord Jehovah says: “I will also stretch out my hand against Eʹdom and cut off from it both man and livestock, and I will make it desolate. From Teʹman clear to Deʹdan, they will fall by the sword.

[[v26-25-14]]

^<<v26-25-14,14>>^ ‘I will take vengeance on Eʹdom by the hand of my people Israel. They will bring my anger and my wrath on Eʹdom, so that they experience my own vengeance,’ declares the Sovereign Lord Jehovah.”’

[[v26-25-15]]

^<<v26-25-15,15>>^ “This is what the Sovereign Lord Jehovah says: ‘Because of their unrelenting hostility, the Phi·lisʹtines have maliciously^&#42;1^ sought to bring vengeance and destruction.

[NOTE]
====
. Or “with scorn in the soul.”
====

[[v26-25-16]]

^<<v26-25-16,16>>^ Therefore this is what the Sovereign Lord Jehovah says: “Here I am stretching out my hand against the Phi·lisʹtines, and I will cut off the Cherʹe·thites and will destroy the remaining inhabitants of the seacoast.

[[v26-25-17]]

^<<v26-25-17,17>>^ I will execute on them great acts of vengeance with furious punishments, and they will have to know that I am Jehovah when I bring my vengeance on them.”’”

'''

xref:026-ezekiel/026-ezekiel-024.adoc#v26-24-0[&#60; Capítulo Anterior] | <<v26-25-0,Topo>> | xref:026-ezekiel/026-ezekiel-026.adoc#v26-26-0[Próximo Capítulo &#62;]