include::./index.adoc[]

[[v26-6-0]]
=== Ezekiel, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-6-1]]

^<<v26-6-1,1>>^ The word of Jehovah again came to me, saying:

[[v26-6-2]]

^<<v26-6-2,2>>^ “Son of man, turn your face toward the mountains of Israel and prophesy against them.

[[v26-6-3]]

^<<v26-6-3,3>>^ You must say, ‘O mountains of Israel, hear the word of the Sovereign Lord Jehovah: This is what the Sovereign Lord Jehovah says to the mountains, to the hills, to the streams, and to the valleys: “Look! I will bring a sword against you, and I will destroy your high places.

[[v26-6-4]]

^<<v26-6-4,4>>^ Your altars will be demolished, your incense stands will be broken, and I will throw your slain ones down before your disgusting idols.^&#42;1^

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v26-6-5]]

^<<v26-6-5,5>>^ I will throw the carcasses of the people of Israel before their disgusting idols, and I will scatter your bones all around your altars.

[[v26-6-6]]

^<<v26-6-6,6>>^ In all the places where you dwell, the cities will be devastated and the high places will be demolished and will lie devastated. Your altars will be demolished and shattered, your disgusting idols will perish, your incense stands will be cut down, and your works will be wiped out.

[[v26-6-7]]

^<<v26-6-7,7>>^ And those slain will fall in your midst, and you will have to know that I am Jehovah.

[[v26-6-8]]

^<<v26-6-8,8>>^ “‘“But I will leave a remnant, for some of you will escape the sword among the nations when you are scattered throughout the lands.

[[v26-6-9]]

^<<v26-6-9,9>>^ And those who escape will remember me among the nations where they are taken captive. They will realize that I was brokenhearted over their unfaithful^&#42;1^ heart that turned away from me and at their eyes that are lusting^&#42;2^ after their disgusting idols. They will be ashamed of and loathe all the evil and detestable things they have done.

[NOTE]
====
. Or “immoral; promiscuous.”
. Or “are immorally following.”
====

[[v26-6-10]]

^<<v26-6-10,10>>^ They will have to know that I am Jehovah and that my threats to bring this calamity on them were not empty.”’

[[v26-6-11]]

^<<v26-6-11,11>>^ “This is what the Sovereign Lord Jehovah says: ‘Clap your hands and stamp your foot and bemoan all the evil and detestable things done by the house of Israel, for they will fall by the sword, by famine, and by pestilence.

[[v26-6-12]]

^<<v26-6-12,12>>^ The one far away will die by pestilence, the one nearby will fall by the sword, and whoever escapes these and is left remaining will die by famine; and I will fully unleash my wrath against them.

[[v26-6-13]]

^<<v26-6-13,13>>^ And you will have to know that I am Jehovah, when their slain lie among their disgusting idols, all around their altars, on every high hill, on all the mountaintops, under every luxuriant tree, and under the branches of big trees where they have made fragrant offerings^&#42;1^ to appease all their disgusting idols.

[NOTE]
====
. Or “offered pleasing aromas.”
====

[[v26-6-14]]

^<<v26-6-14,14>>^ I will stretch out my hand against them and make the land desolate, and all their dwelling places will become more desolate than the wilderness near Dibʹlah. And they will have to know that I am Jehovah.’”

'''

xref:026-ezekiel/026-ezekiel-005.adoc#v26-5-0[&#60; Capítulo Anterior] | <<v26-6-0,Topo>> | xref:026-ezekiel/026-ezekiel-007.adoc#v26-7-0[Próximo Capítulo &#62;]