include::./index.adoc[]

[[v26-46-0]]
=== Ezekiel, 46
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-46-1]]

^<<v26-46-1,1>>^ “This is what the Sovereign Lord Jehovah says: ‘The gate of the inner courtyard that is facing east should remain shut for the six workdays, but on the Sabbath day and on the day of the new moon it should be opened.

[[v26-46-2]]

^<<v26-46-2,2>>^ The chieftain will enter from outside by way of the porch of the gate, and he will stand by the doorpost of the gate. The priests will offer his whole burnt offering and his communion sacrifices, and he will bow down at the threshold of the gate and then go out. But the gate should not be shut until the evening.

[[v26-46-3]]

^<<v26-46-3,3>>^ The people of the land will also bow down before Jehovah at the entrance of that gate on the Sabbaths and on the new moons.

[[v26-46-4]]

^<<v26-46-4,4>>^ “‘The whole burnt offering that the chieftain will present to Jehovah on the Sabbath day should consist of six sound male lambs and a sound ram.

[[v26-46-5]]

^<<v26-46-5,5>>^ The grain offering will be an eʹphah^&#42;1^ for the ram and whatever he is able to give for the male lambs, along with a hin^&#42;2^ of oil with each eʹphah.

[NOTE]
====
. See App. B14.
. See App. B14.
====

[[v26-46-6]]

^<<v26-46-6,6>>^ On the day of the new moon the offering will consist of a sound young bull of the herd, six male lambs, and a ram; they should be sound ones.

[[v26-46-7]]

^<<v26-46-7,7>>^ He should offer as a grain offering an eʹphah for the young bull, an eʹphah for the ram, and whatever he can afford for the male lambs. And he should offer a hin of oil with each eʹphah.

[[v26-46-8]]

^<<v26-46-8,8>>^ “‘When the chieftain enters, he should enter by way of the porch of the gate, and he should go out the same way.

[[v26-46-9]]

^<<v26-46-9,9>>^ And when the people of the land come in before Jehovah during the festivals, those who come in to worship through the north gate should go out through the south gate, and those who come in through the south gate should go out through the north gate. No one should go back by way of the gate through which he entered, for they should exit through the gate that is opposite them.

[[v26-46-10]]

^<<v26-46-10,10>>^ As for the chieftain who is among them, he should come in when they come in, and he should go out when they go out.

[[v26-46-11]]

^<<v26-46-11,11>>^ During the festivals and the festal seasons the grain offering should be an eʹphah for the young bull, an eʹphah for the ram, and whatever he is able to give for the male lambs, along with a hin of oil with each eʹphah.

[[v26-46-12]]

^<<v26-46-12,12>>^ “‘If the chieftain provides a whole burnt offering or communion sacrifices as a voluntary offering to Jehovah, the gate facing east will be opened for him, and he will provide his whole burnt offering and his communion sacrifices just as he does on the Sabbath day. After he goes out, the gate should be shut behind him.

[[v26-46-13]]

^<<v26-46-13,13>>^ “‘Each day you should provide a sound male lamb in its first year as a whole burnt offering to Jehovah. You should do this morning by morning.

[[v26-46-14]]

^<<v26-46-14,14>>^ Along with it, each morning you should provide a sixth of an eʹphah as a grain offering, along with a third of a hin of oil for sprinkling on the fine flour as a regular grain offering to Jehovah. This is a lasting statute.

[[v26-46-15]]

^<<v26-46-15,15>>^ They must provide the male lamb, the grain offering, and the oil each morning as a regular whole burnt offering.’

[[v26-46-16]]

^<<v26-46-16,16>>^ “This is what the Sovereign Lord Jehovah says: ‘If the chieftain gives a gift to each one of his sons as an inheritance, it will become the property of his sons. It is their possession by inheritance.

[[v26-46-17]]

^<<v26-46-17,17>>^ But if he gives a gift from his inheritance to one of his servants, it will be his until the year of liberty; and then it will return to the chieftain. Only the inheritance of his sons will be permanently theirs.

[[v26-46-18]]

^<<v26-46-18,18>>^ The chieftain should not take any of the inheritance of the people by forcing them off their property. He should give his sons an inheritance from his own property, so that no one among my people may be driven from his property.’”

[[v26-46-19]]

^<<v26-46-19,19>>^ Then he brought me in by the entryway that was beside the gate leading to the holy dining rooms^&#42;1^ of the priests, which faced north, and there I saw a place at the rear toward the west.

[NOTE]
====
. Or “holy chambers.”
====

[[v26-46-20]]

^<<v26-46-20,20>>^ He said to me: “This is the place where the priests will boil the guilt offering and the sin offering and where they will bake the grain offering, so that they will not carry anything out to the outer courtyard and transmit holiness to^&#42;1^ the people.”

[NOTE]
====
. Lit., “sanctify.”
====

[[v26-46-21]]

^<<v26-46-21,21>>^ He brought me out to the outer courtyard and led me past the four corners of the courtyard, and I saw a courtyard by each corner of the outer courtyard.

[[v26-46-22]]

^<<v26-46-22,22>>^ At the four corners of the courtyard were small courtyards, 40 cubits^&#42;1^ long and 30 cubits wide. All four of them were the same size.^&#42;2^

[NOTE]
====
. This refers to long cubits. See App. B14.
. Or “The four of them and their corner structures were the same size.”
====

[[v26-46-23]]

^<<v26-46-23,23>>^ There were ledges^&#42;1^ all around the four of them, and beneath the ledges were built places to boil the offerings.

[NOTE]
====
. Or “rows.”
====

[[v26-46-24]]

^<<v26-46-24,24>>^ Then he said to me: “These are the houses where the ministers of the temple boil the sacrifice of the people.”

'''

xref:026-ezekiel/026-ezekiel-045.adoc#v26-45-0[&#60; Capítulo Anterior] | <<v26-46-0,Topo>> | xref:026-ezekiel/026-ezekiel-047.adoc#v26-47-0[Próximo Capítulo &#62;]