include::./index.adoc[]

[[v26-16-0]]
=== Ezekiel, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-16-1]]

^<<v26-16-1,1>>^ The word of Jehovah again came to me, saying:

[[v26-16-2]]

^<<v26-16-2,2>>^ “Son of man, make known to Jerusalem her detestable practices.

[[v26-16-3]]

^<<v26-16-3,3>>^ You must say, ‘This is what the Sovereign Lord Jehovah says to Jerusalem: “Your origin and your birth were in the land of the Caʹnaan·ite. Your father was an Amʹor·ite, and your mother was a Hitʹtite.

[[v26-16-4]]

^<<v26-16-4,4>>^ As for your birth, on the day you were born, your umbilical cord was not cut, you were not washed in water to make you clean, you were not rubbed with salt, and you were not wrapped in cloths.

[[v26-16-5]]

^<<v26-16-5,5>>^ No one pitied you enough to do any of these things. No one had compassion for you. Instead, you were thrown into the open field because you were^&#42;1^ hated on the day you were born.

[NOTE]
====
. Or “your soul was.”
====

[[v26-16-6]]

^<<v26-16-6,6>>^ “‘“When I was passing by, I saw you kicking about in your own blood, and as you lay there in your blood, I said: ‘Keep living!’ Yes, I said to you lying there in your blood: ‘Keep living!’

[[v26-16-7]]

^<<v26-16-7,7>>^ I made you a very great multitude, like plants sprouting in the field, and you grew up and developed and wore the finest ornaments. Your breasts became firm, and your hair grew; but you were still naked and exposed.”’

[[v26-16-8]]

^<<v26-16-8,8>>^ “‘When I was passing by and saw you, I noticed that you were old enough for expressions of love. So I spread my garment^&#42;1^ over you and covered your nakedness and made an oath and entered into a covenant with you,’ declares the Sovereign Lord Jehovah, ‘and you became mine.

[NOTE]
====
. Or “skirt.”
====

[[v26-16-9]]

^<<v26-16-9,9>>^ Furthermore, I washed you with water and rinsed away your blood and put oil on you.

[[v26-16-10]]

^<<v26-16-10,10>>^ I then clothed you with an embroidered garment and gave you fine leather^&#42;1^ sandals and wrapped you in fine linen, and I clothed you with costly garments.

[NOTE]
====
. Or “sealskin.”
====

[[v26-16-11]]

^<<v26-16-11,11>>^ I adorned you with ornaments and put bracelets on your hands and a necklace around your neck.

[[v26-16-12]]

^<<v26-16-12,12>>^ I also put a ring in your nose and earrings on your ears and a beautiful crown on your head.

[[v26-16-13]]

^<<v26-16-13,13>>^ You kept adorning yourself with gold and silver, and your clothing was fine linen, costly material, and an embroidered garment. Fine flour, honey, and oil were what you ate, and you grew to be extremely beautiful, and you became fit to be a queen.’”^&#42;1^

[NOTE]
====
. Or “fit for a royal position.”
====

[[v26-16-14]]

^<<v26-16-14,14>>^ “‘Your fame^&#42;1^ began to spread among the nations because of your beauty, for it was perfect because my own splendor I placed upon you,’ declares the Sovereign Lord Jehovah.”

[NOTE]
====
. Lit., “name.”
====

[[v26-16-15]]

^<<v26-16-15,15>>^ “‘But you began to trust in your beauty, and you became a prostitute because of your fame. You lavished your acts of prostitution on everyone passing by, and your beauty became his.

[[v26-16-16]]

^<<v26-16-16,16>>^ You took some of your garments and made colorful high places where you prostituted yourself—such things should not take place, nor should they ever happen.

[[v26-16-17]]

^<<v26-16-17,17>>^ You also took your beautiful jewelry^&#42;1^ made from the gold and silver that I had given to you and you made for yourself male images and prostituted yourself with them.

[NOTE]
====
. Or “ornaments.”
====

[[v26-16-18]]

^<<v26-16-18,18>>^ And you took your embroidered garments and covered them,^&#42;1^ and you offered them my oil and my incense.

[NOTE]
====
. That is, the male idols.
====

[[v26-16-19]]

^<<v26-16-19,19>>^ And the bread that I had given to you—made from fine flour, oil, and honey that I gave you to eat—you also offered to them as a pleasing^&#42;1^ aroma. That is exactly what happened,’ declares the Sovereign Lord Jehovah.”

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v26-16-20]]

^<<v26-16-20,20>>^ “‘You took your sons and your daughters whom you had borne to me, and you sacrificed these to idols to be devoured—have your acts of prostitution not gone far enough?

[[v26-16-21]]

^<<v26-16-21,21>>^ You slaughtered my sons, and you offered them as sacrifices by making them pass through the fire.

[[v26-16-22]]

^<<v26-16-22,22>>^ While engaging in all your detestable practices and acts of prostitution, you did not remember the days of your youth when you were naked and exposed, kicking about in your own blood.

[[v26-16-23]]

^<<v26-16-23,23>>^ After all your evil, woe, woe to you,’ declares the Sovereign Lord Jehovah.

[[v26-16-24]]

^<<v26-16-24,24>>^ ‘You built yourself a mound and made a high place for yourself in every public square.

[[v26-16-25]]

^<<v26-16-25,25>>^ You built your high places at the most prominent place of every street, and you turned your beauty into something detestable by offering yourself^&#42;1^ to everyone passing by, and you multiplied your acts of prostitution.

[NOTE]
====
. Lit., “spreading your legs.”
====

[[v26-16-26]]

^<<v26-16-26,26>>^ You prostituted yourself to the sons of Egypt, your lustful neighbors,^&#42;1^ and you offended me with your countless acts of prostitution.

[NOTE]
====
. Lit., “your neighbors great of flesh.”
====

[[v26-16-27]]

^<<v26-16-27,27>>^ Now I will bring my hand against you and diminish your food allowance and give you over to the will^&#42;1^ of the women who hate you, the daughters of the Phi·lisʹtines, who were appalled because of your obscene conduct.

[NOTE]
====
. Or “soul.”
====

[[v26-16-28]]

^<<v26-16-28,28>>^ “‘Because you could not be satisfied, you then prostituted yourself to the sons of As·syrʹi·a, but after prostituting yourself to them, you still did not find satisfaction.

[[v26-16-29]]

^<<v26-16-29,29>>^ So you increased your prostitution toward the land of traders^&#42;1^ and toward the Chal·deʹans, but even then you did not find satisfaction.

[NOTE]
====
. Lit., “land of Canaan.”
====

[[v26-16-30]]

^<<v26-16-30,30>>^ How sick^&#42;1^ your heart was,’^&#42;2^ declares the Sovereign Lord Jehovah, ‘when you did all these things, behaving like a brazen prostitute!

[NOTE]
====
. Or “weak.”
. Or possibly, “O how I am filled up with rage against you.”
====

[[v26-16-31]]

^<<v26-16-31,31>>^ But when you built your mound at the most prominent place of every street and made your high place in every public square, you were not like a prostitute, because you refused any payment.

[[v26-16-32]]

^<<v26-16-32,32>>^ You are an adulterous wife who takes strangers instead of her own husband!

[[v26-16-33]]

^<<v26-16-33,33>>^ People give all prostitutes a gift, but you are the one who has given gifts to all those lusting after you, and you bribe them to come to you from all around to commit prostitution.

[[v26-16-34]]

^<<v26-16-34,34>>^ You are the opposite of other women who engage in prostitution. No one commits prostitution your way! You pay others, and they do not pay you. Your way is the opposite.’

[[v26-16-35]]

^<<v26-16-35,35>>^ “Therefore, O prostitute, hear the word of Jehovah.

[[v26-16-36]]

^<<v26-16-36,36>>^ This is what the Sovereign Lord Jehovah says: ‘Because your lust has been poured out and your nakedness has been exposed during your prostitution with your lovers and all your detestable, disgusting idols^&#42;1^ to which you even sacrificed the blood of your sons,

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v26-16-37]]

^<<v26-16-37,37>>^ therefore I am collecting together all the lovers you have given pleasure to, all those you loved together with all those you hated. I will collect them together against you from all around and expose your nakedness to them, and they will see you completely naked.

[[v26-16-38]]

^<<v26-16-38,38>>^ “‘And I will punish you with the judgments that adulteresses and women shedding blood deserve, and your blood will be shed in rage and jealousy.

[[v26-16-39]]

^<<v26-16-39,39>>^ I will give you into their hand, and they will tear down your mounds, and your high places will be pulled down; and they will strip you of your garments and take your beautiful jewelry^&#42;1^ and leave you naked and exposed.

[NOTE]
====
. Or “ornaments.”
====

[[v26-16-40]]

^<<v26-16-40,40>>^ They will bring against you a crowd, and they will stone you and will slaughter you with their swords.

[[v26-16-41]]

^<<v26-16-41,41>>^ They will burn your houses with fire and execute judgment on you before the eyes of many women; and I will bring an end to your prostitution, and you will stop giving payment.

[[v26-16-42]]

^<<v26-16-42,42>>^ I will satisfy my rage against you, and my indignation will turn away from you; and I will be calm and no longer feel offended.’

[[v26-16-43]]

^<<v26-16-43,43>>^ “‘Because you did not remember the days of your youth and you have angered me by doing all these things, I will now bring the consequences of your ways on your own head,’ declares the Sovereign Lord Jehovah, ‘and you will no longer carry on your obscene conduct and all your detestable practices.

[[v26-16-44]]

^<<v26-16-44,44>>^ “‘Look! Everyone who uses proverbs will apply this proverb to you: “Like mother, like daughter!”

[[v26-16-45]]

^<<v26-16-45,45>>^ You are the daughter of your mother, who despised her husband and her children. And you are the sister of your sisters, who despised their husbands and their children. Your mother was a Hitʹtite, and your father was an Amʹor·ite.’”

[[v26-16-46]]

^<<v26-16-46,46>>^ “‘Your older sister is Sa·marʹi·a, who is dwelling to the north of you^&#42;1^ with her daughters,^&#42;2^ and your younger sister, who is dwelling to the south of you,^&#42;3^ is Sodʹom with her daughters.

[NOTE]
====
. Lit., “on your left.”
. Probably referring to dependent towns.
. Lit., “on your right.”
====

[[v26-16-47]]

^<<v26-16-47,47>>^ Not only did you walk in their ways and follow their detestable practices, but in a short while you were even more corrupt in all your conduct than they were.

[[v26-16-48]]

^<<v26-16-48,48>>^ As surely as I am alive,’ declares the Sovereign Lord Jehovah, ‘Sodʹom your sister and her daughters have not done what you and your daughters have done.

[[v26-16-49]]

^<<v26-16-49,49>>^ Look! This was the error of Sodʹom your sister: She and her daughters were proud and had an abundance of food and carefree tranquility; yet they did not support the afflicted and the poor.

[[v26-16-50]]

^<<v26-16-50,50>>^ They remained haughty and carried on detestable practices in my sight, so I found it necessary to remove them.

[[v26-16-51]]

^<<v26-16-51,51>>^ “‘Nor did Sa·marʹi·a commit even half as many sins as you did. You kept making your detestable practices abound more than they have, to the point that your sisters appeared righteous because of all your detestable practices.

[[v26-16-52]]

^<<v26-16-52,52>>^ You must now bear your humiliation because you have justified the behavior^&#42;1^ of your sisters. On account of your sin of acting more detestably than they have, they are more righteous than you. So now, be ashamed and bear the humiliation of making your sisters appear righteous.’

[NOTE]
====
. Or “have argued in favor.”
====

[[v26-16-53]]

^<<v26-16-53,53>>^ “‘And I will gather their captives, the captives of Sodʹom and her daughters and the captives of Sa·marʹi·a and her daughters; I will also gather your captives along with them,

[[v26-16-54]]

^<<v26-16-54,54>>^ so that you may bear your humiliation; and you will feel humiliated because of what you have done by comforting them.

[[v26-16-55]]

^<<v26-16-55,55>>^ Your own sisters, Sodʹom and her daughters, will return to their former state, and Sa·marʹi·a and her daughters will return to their former state, and you along with your own daughters will return to your former state.

[[v26-16-56]]

^<<v26-16-56,56>>^ Sodʹom your sister was not worthy of your mention in the day of your pride,

[[v26-16-57]]

^<<v26-16-57,57>>^ before your own wickedness was exposed. Now the daughters of Syria and her neighbors reproach you, and the daughters of the Phi·lisʹtines, those all around you, treat you with scorn.

[[v26-16-58]]

^<<v26-16-58,58>>^ You will bear the consequences of your obscene conduct and your detestable practices,’ declares Jehovah.”

[[v26-16-59]]

^<<v26-16-59,59>>^ “For this is what the Sovereign Lord Jehovah says: ‘I will now do with you just as you have done, for you despised the oath by breaking my covenant.

[[v26-16-60]]

^<<v26-16-60,60>>^ But I myself will remember the covenant that I made with you in the days of your youth, and I will establish with you a permanent covenant.

[[v26-16-61]]

^<<v26-16-61,61>>^ You will remember your behavior and feel humiliated when you welcome your sisters, those older than you as well as those younger than you, and I will give them to you as daughters, but not because of your covenant.’

[[v26-16-62]]

^<<v26-16-62,62>>^ “‘And I myself will establish my covenant with you; and you will have to know that I am Jehovah.

[[v26-16-63]]

^<<v26-16-63,63>>^ Then you will remember and be too ashamed to open your mouth because of your humiliation, when I make an atonement for you despite all that you have done,’ declares the Sovereign Lord Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-015.adoc#v26-15-0[&#60; Capítulo Anterior] | <<v26-16-0,Topo>> | xref:026-ezekiel/026-ezekiel-017.adoc#v26-17-0[Próximo Capítulo &#62;]