include::./index.adoc[]

[[v26-20-0]]
=== Ezekiel, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-20-1]]

^<<v26-20-1,1>>^ Now in the seventh year, in the fifth month, on the tenth day of the month, some of the elders of Israel came and sat down before me to inquire of Jehovah.

[[v26-20-2]]

^<<v26-20-2,2>>^ Then the word of Jehovah came to me, saying:

[[v26-20-3]]

^<<v26-20-3,3>>^ “Son of man, speak with the elders of Israel, and tell them, ‘This is what the Sovereign Lord Jehovah says: “Are you coming to inquire of me? ‘As surely as I am alive, I will not respond to your inquiry,’ declares the Sovereign Lord Jehovah.”’

[[v26-20-4]]

^<<v26-20-4,4>>^ “Are you ready to judge them?^&#42;1^ Are you ready to judge them, son of man? Make them know the detestable things that their forefathers did.

[NOTE]
====
. Or “to pronounce judgment on them?”
====

[[v26-20-5]]

^<<v26-20-5,5>>^ Tell them, ‘This is what the Sovereign Lord Jehovah says: “In the day I chose Israel, I also swore^&#42;1^ to the offspring^&#42;2^ of the house of Jacob, and I made myself known to them in the land of Egypt. Yes, I swore to them and said, ‘I am Jehovah your God.’

[NOTE]
====
. Lit., “raised my hand.”
. Lit., “seed.”
====

[[v26-20-6]]

^<<v26-20-6,6>>^ In that day I swore that I would bring them out of the land of Egypt to a land that I had searched out^&#42;1^ for them, one flowing with milk and honey. It was the most beautiful^&#42;2^ of all the lands.

[NOTE]
====
. Or “spied out.”
. Or “the decoration.”
====

[[v26-20-7]]

^<<v26-20-7,7>>^ I then said to them, ‘Each of you must throw away the detestable things that are before your eyes; do not defile yourselves with the disgusting idols^&#42;1^ of Egypt. I am Jehovah your God.’

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v26-20-8]]

^<<v26-20-8,8>>^ “‘“But they rebelled against me and were not willing to listen to me. They did not throw away the detestable things that were before them, and they would not abandon the disgusting idols of Egypt. So I promised to pour out my rage on them and to unleash my anger fully against them in the land of Egypt.

[[v26-20-9]]

^<<v26-20-9,9>>^ But I acted for the sake of my name so that it would not be profaned before the nations among whom they were living. For I made myself known to them^&#42;1^ before these nations when I brought them^&#42;2^ out of the land of Egypt.

[NOTE]
====
. That is, Israel.
. That is, Israel.
====

[[v26-20-10]]

^<<v26-20-10,10>>^ So I brought them out of the land of Egypt and led them into the wilderness.

[[v26-20-11]]

^<<v26-20-11,11>>^ “‘“I then gave them my statutes and made my judicial decisions known to them, so that the man who follows them may have life by them.

[[v26-20-12]]

^<<v26-20-12,12>>^ I also gave my sabbaths to them as a sign between me and them, so that they would know that I, Jehovah, am the one sanctifying them.

[[v26-20-13]]

^<<v26-20-13,13>>^ “‘“But the house of Israel rebelled against me in the wilderness. They did not walk in my statutes, and they rejected my judicial decisions, which if a man follows them, he will have life by them. They utterly profaned my sabbaths. So I promised to pour out my fury on them in the wilderness to exterminate them.

[[v26-20-14]]

^<<v26-20-14,14>>^ I acted for the sake of my own name so that it would not be profaned before the nations, in whose sight I brought them^&#42;1^ out.

[NOTE]
====
. That is, Israel.
====

[[v26-20-15]]

^<<v26-20-15,15>>^ I also swore to them in the wilderness that I would not bring them into the land that I had given them—a land flowing with milk and honey, the most beautiful^&#42;1^ of all the lands—

[NOTE]
====
. Or “the decoration.”
====

[[v26-20-16]]

^<<v26-20-16,16>>^ because they rejected my judicial decisions, they did not walk in my statutes, and they profaned my sabbaths, for their heart was following after their disgusting idols.

[[v26-20-17]]

^<<v26-20-17,17>>^ “‘“But I^&#42;1^ felt sorry for them, and I did not destroy them; I did not exterminate them in the wilderness.

[NOTE]
====
. Lit., “my eye.”
====

[[v26-20-18]]

^<<v26-20-18,18>>^ I said to their sons in the wilderness, ‘Do not walk in the regulations of your forefathers or keep their judgments or defile yourselves with their disgusting idols.

[[v26-20-19]]

^<<v26-20-19,19>>^ I am Jehovah your God. Walk in my statutes, and keep my judicial decisions, and carry them out.

[[v26-20-20]]

^<<v26-20-20,20>>^ And sanctify my sabbaths, and they will serve as a sign between me and you for you to know that I am Jehovah your God.’

[[v26-20-21]]

^<<v26-20-21,21>>^ “‘“But the sons began to rebel against me. They did not walk in my statutes, and they did not observe and carry out my judicial decisions, which if a man follows them, he will have life by them. My sabbaths they profaned. So I promised to pour out my rage on them and to unleash my anger against them fully in the wilderness.

[[v26-20-22]]

^<<v26-20-22,22>>^ But I refrained and acted for the sake of my own name, so that it should not be profaned before the nations, in whose sight I brought them^&#42;1^ out.

[NOTE]
====
. That is, Israel.
====

[[v26-20-23]]

^<<v26-20-23,23>>^ Also, I swore to them in the wilderness that I would scatter them among the nations and disperse them among the lands,

[[v26-20-24]]

^<<v26-20-24,24>>^ because they did not carry out my judicial decisions and they rejected my statutes, they profaned my sabbaths, and they followed after^&#42;1^ the disgusting idols of their forefathers.

[NOTE]
====
. Lit., “their eyes were after.”
====

[[v26-20-25]]

^<<v26-20-25,25>>^ I also allowed them to follow regulations that were not good and judicial decisions by which they could not have life.

[[v26-20-26]]

^<<v26-20-26,26>>^ I let them become defiled by their own sacrifices—when they made every firstborn child pass through the fire—in order to make them desolate, so that they would know that I am Jehovah.”’

[[v26-20-27]]

^<<v26-20-27,27>>^ “So speak to the house of Israel, O son of man, and tell them, ‘This is what the Sovereign Lord Jehovah says: “In this way also, your forefathers blasphemed me by acting unfaithfully against me.

[[v26-20-28]]

^<<v26-20-28,28>>^ I brought them into the land that I swore to give them. When they saw all the high hills and leafy trees, they began offering their sacrifices and their offensive offerings. They presented the pleasing^&#42;1^ aromas of their sacrifices and poured out their drink offerings there.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v26-20-29]]

^<<v26-20-29,29>>^ So I asked them, ‘What is the meaning of this high place to which you go? (It is still called High Place to this day.)’”’

[[v26-20-30]]

^<<v26-20-30,30>>^ “Now say to the house of Israel, ‘This is what the Sovereign Lord Jehovah says: “Are you defiling yourselves the same way your forefathers did by going after their disgusting idols to commit spiritual prostitution with them?

[[v26-20-31]]

^<<v26-20-31,31>>^ And are you still defiling yourselves to this day by offering sacrifices to all your disgusting idols, making your sons pass through the fire? Should I at the same time respond to your inquiry, O house of Israel?”’
“‘As surely as I am alive,’ declares the Sovereign Lord Jehovah, ‘I will not respond to your inquiry.

[[v26-20-32]]

^<<v26-20-32,32>>^ And what you have in mind^&#42;1^ when you say, “Let us become like the nations, like the families of the other lands, who worship^&#42;2^ wood and stone,” it will never happen.’”

[NOTE]
====
. Lit., “spirit.”
. Or “minister to; serve.”
====

[[v26-20-33]]

^<<v26-20-33,33>>^ “‘As surely as I am alive,’ declares the Sovereign Lord Jehovah, ‘I will rule as king over you with a mighty hand, with an outstretched arm, and with an outpouring of rage.

[[v26-20-34]]

^<<v26-20-34,34>>^ I will bring you out from the peoples and collect you together out of the lands where you have been scattered with a mighty hand, with an outstretched arm, and with an outpouring of rage.

[[v26-20-35]]

^<<v26-20-35,35>>^ I will bring you into the wilderness of the peoples and enter into judgment with you there face-to-face.

[[v26-20-36]]

^<<v26-20-36,36>>^ “‘Just as I entered into judgment with your forefathers in the wilderness of the land of Egypt, so I will enter into judgment with you,’ declares the Sovereign Lord Jehovah.

[[v26-20-37]]

^<<v26-20-37,37>>^ ‘I will make you pass under the shepherd’s staff and bring you under obligation to^&#42;1^ the covenant.

[NOTE]
====
. Lit., “into the bond of.”
====

[[v26-20-38]]

^<<v26-20-38,38>>^ But I will remove from you the rebels and those transgressing against me. For I will bring them out of the land of their foreign residence, but they will not enter the land of Israel; and you will have to know that I am Jehovah.’

[[v26-20-39]]

^<<v26-20-39,39>>^ “As for you, O house of Israel, this is what the Sovereign Lord Jehovah says: ‘Each of you go and serve his disgusting idols. But afterward if you do not listen to me, you will no longer be able to profane my holy name by your sacrifices and your disgusting idols.’

[[v26-20-40]]

^<<v26-20-40,40>>^ “‘For in my holy mountain, on a high mountain of Israel,’ declares the Sovereign Lord Jehovah, ‘is where the whole house of Israel, all of them, will serve me in the land. I will take pleasure in them there, and I will require your contributions and the firstfruits of your offerings, all your holy things.

[[v26-20-41]]

^<<v26-20-41,41>>^ Because of the pleasing^&#42;1^ aroma, I will take pleasure in you when I bring you out from the peoples and collect you together from the lands to which you have been scattered; and I will be sanctified among you before the eyes of the nations.’

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
====

[[v26-20-42]]

^<<v26-20-42,42>>^ “‘And you will have to know that I am Jehovah when I bring you to the land of Israel, into the land that I swore to give to your forefathers.

[[v26-20-43]]

^<<v26-20-43,43>>^ And there you will remember your conduct and all your deeds by which you defiled yourselves, and you will loathe yourselves^&#42;1^ because of all the bad things that you did.

[NOTE]
====
. Lit., “your faces.”
====

[[v26-20-44]]

^<<v26-20-44,44>>^ Then you will have to know that I am Jehovah when I deal with you for the sake of my name, not according to your wicked conduct or according to your corrupted dealings, O house of Israel,’ declares the Sovereign Lord Jehovah.”

[[v26-20-45]]

^<<v26-20-45,45>>^ And the word of Jehovah again came to me, saying:

[[v26-20-46]]

^<<v26-20-46,46>>^ “Son of man, turn your face in the direction of the southern quarter and proclaim to the south, and prophesy to the forest of the field of the south.

[[v26-20-47]]

^<<v26-20-47,47>>^ Say to the forest of the south, ‘Hear the word of Jehovah. This is what the Sovereign Lord Jehovah says: “Here I am setting a fire ablaze against you, and it will consume every green tree and every dry tree in you. The burning flame will not be extinguished, and every face will be scorched by it, from south to north.

[[v26-20-48]]

^<<v26-20-48,48>>^ And all flesh^&#42;1^ will see that I myself, Jehovah, have set it afire, so that it will not be extinguished.”’”

[NOTE]
====
. Or “people.”
====

[[v26-20-49]]

^<<v26-20-49,49>>^ And I said: “Alas, O Sovereign Lord Jehovah! They are saying about me, ‘Is he not just speaking in riddles?’”^&#42;1^

[NOTE]
====
. Or “proverbial sayings?”
====

'''

xref:026-ezekiel/026-ezekiel-019.adoc#v26-19-0[&#60; Capítulo Anterior] | <<v26-20-0,Topo>> | xref:026-ezekiel/026-ezekiel-021.adoc#v26-21-0[Próximo Capítulo &#62;]