include::./index.adoc[]

[[v26-44-0]]
=== Ezekiel, 44
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-44-1]]

^<<v26-44-1,1>>^ He brought me back by way of the outer gate of the sanctuary facing east, and it was shut.

[[v26-44-2]]

^<<v26-44-2,2>>^ Then Jehovah said to me: “This gate will remain shut. It is not to be opened, and no human will enter by it; for Jehovah, the God of Israel, has entered through it, so it must remain shut.

[[v26-44-3]]

^<<v26-44-3,3>>^ However, the chieftain will sit in it to eat bread before Jehovah, for he is a chieftain. He will come in through the porch of the gate, and he will go out through it.”

[[v26-44-4]]

^<<v26-44-4,4>>^ Then he brought me through the north gate to the front of the temple. When I looked, I saw that the glory of Jehovah had filled the temple of Jehovah. So I fell with my face to the ground.

[[v26-44-5]]

^<<v26-44-5,5>>^ Then Jehovah said to me: “Son of man, pay attention,^&#42;1^ watch, and listen carefully to everything I tell you about the statutes and the laws of the temple of Jehovah. Pay close attention to the entryway of the temple and all the exits of the sanctuary.

[NOTE]
====
. Lit., “set your heart.”
====

[[v26-44-6]]

^<<v26-44-6,6>>^ You must say to the rebellious house of Israel, ‘This is what the Sovereign Lord Jehovah says: “That is enough of your detestable practices, O house of Israel.

[[v26-44-7]]

^<<v26-44-7,7>>^ When you bring foreigners who are uncircumcised in heart and flesh into my sanctuary, they profane my temple. You present my bread, fat and blood, while my covenant is being broken because of all your detestable practices.

[[v26-44-8]]

^<<v26-44-8,8>>^ You have not taken care of my holy things. Instead, you assign others to take care of the duties in my sanctuary.”’

[[v26-44-9]]

^<<v26-44-9,9>>^ “‘This is what the Sovereign Lord Jehovah says: “No foreigner living in Israel who is uncircumcised in heart and in flesh may enter my sanctuary.”’

[[v26-44-10]]

^<<v26-44-10,10>>^ “‘But the Levites who strayed far from me when Israel strayed from me to follow their disgusting idols^&#42;1^ will bear the consequences of their error.

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v26-44-11]]

^<<v26-44-11,11>>^ And they will become ministers in my sanctuary to oversee the gates of the temple and to minister at the temple. They will slaughter the whole burnt offering and the sacrifice for the people, and they will stand before the people to minister to them.

[[v26-44-12]]

^<<v26-44-12,12>>^ Because they ministered to them before their disgusting idols and became a stumbling block causing the house of Israel to sin, that is why I have raised my hand against them in an oath,’ declares the Sovereign Lord Jehovah, ‘and they will bear the consequences of their error.

[[v26-44-13]]

^<<v26-44-13,13>>^ They will not approach me to serve as my priests or approach any of my holy or most holy things, and they will bear their shame because of the detestable things that they did.

[[v26-44-14]]

^<<v26-44-14,14>>^ But I will make them caretakers of the responsibilities of the temple, to take care of its service and all the things that should be done in it.’

[[v26-44-15]]

^<<v26-44-15,15>>^ “‘As for the Levitical priests, the sons of Zaʹdok, who took care of the responsibilities of my sanctuary when the Israelites strayed from me, they will approach me to minister to me, and they will stand before me to offer me the fat and the blood,’ declares the Sovereign Lord Jehovah.

[[v26-44-16]]

^<<v26-44-16,16>>^ ‘They are the ones who will enter my sanctuary, and they will approach my table to minister to me, and they will take care of their responsibilities to me.

[[v26-44-17]]

^<<v26-44-17,17>>^ “‘When they come into the gates of the inner courtyard, they should wear linen garments. They should not wear any wool when they minister in the gates of the inner courtyard or inside it.

[[v26-44-18]]

^<<v26-44-18,18>>^ They should wear linen turbans on their head, and linen shorts should cover their hips. They should not wear anything that makes them perspire.

[[v26-44-19]]

^<<v26-44-19,19>>^ Before they go out to the outer courtyard—the outer courtyard where the people are—they should remove the garments they were ministering in and place them in the holy dining rooms.^&#42;1^ Then they will put on other garments, so that they will not transmit holiness to^&#42;2^ the people with their garments.

[NOTE]
====
. Or “the holy chambers.”
. Lit., “sanctify.”
====

[[v26-44-20]]

^<<v26-44-20,20>>^ They should not shave their head or let the hair of their head grow long. They should trim the hair of their heads.

[[v26-44-21]]

^<<v26-44-21,21>>^ The priests should not drink wine when they enter the inner courtyard.

[[v26-44-22]]

^<<v26-44-22,22>>^ They should not take a widow or a divorced woman as a wife; but they may marry either a virgin of the offspring of Israel or the widow of a priest.’

[[v26-44-23]]

^<<v26-44-23,23>>^ “‘They should instruct my people about the difference between what is holy and what is common; and they will teach them the difference between what is unclean and what is clean.

[[v26-44-24]]

^<<v26-44-24,24>>^ They should preside as judges in a legal case; they must judge it in harmony with my judicial decisions. They should keep my laws and my statutes regarding all my festivals and sanctify my sabbaths.

[[v26-44-25]]

^<<v26-44-25,25>>^ They should not approach any dead human, or they will become unclean. However, they may make themselves unclean for their father, mother, son, daughter, brother, or an unmarried sister.

[[v26-44-26]]

^<<v26-44-26,26>>^ And after the purification of a priest, they should count off seven days for him.

[[v26-44-27]]

^<<v26-44-27,27>>^ On the day he enters into the holy place, into the inner courtyard, to minister in the holy place, he should present his sin offering,’ declares the Sovereign Lord Jehovah.

[[v26-44-28]]

^<<v26-44-28,28>>^ “‘And this will be their inheritance: I am their inheritance. You should not give them any possession in Israel, for I am their possession.

[[v26-44-29]]

^<<v26-44-29,29>>^ They will be the ones to eat the grain offering, the sin offering, and the guilt offering, and every devoted thing in Israel will become theirs.

[[v26-44-30]]

^<<v26-44-30,30>>^ The choicest of all the first ripe fruits and every sort of contribution from you will belong to the priests. And you should give the firstfruits of your coarse meal to the priest. This will cause a blessing to rest on your households.

[[v26-44-31]]

^<<v26-44-31,31>>^ The priests should not eat any bird or animal that was found dead or torn to pieces.’

'''

xref:026-ezekiel/026-ezekiel-043.adoc#v26-43-0[&#60; Capítulo Anterior] | <<v26-44-0,Topo>> | xref:026-ezekiel/026-ezekiel-045.adoc#v26-45-0[Próximo Capítulo &#62;]