include::./index.adoc[]

[[v26-26-0]]
=== Ezekiel, 26
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-26-1]]

^<<v26-26-1,1>>^ In the 11th year, on the first day of the month, the word of Jehovah came to me, saying:

[[v26-26-2]]

^<<v26-26-2,2>>^ “Son of man, because Tyre has said against Jerusalem, ‘Aha! The gateway of the peoples has been broken! Everything will come my way, and I will become rich now that she is devastated’;

[[v26-26-3]]

^<<v26-26-3,3>>^ therefore this is what the Sovereign Lord Jehovah says: ‘Here I am against you, O Tyre, and I will bring up many nations against you, just as the sea brings up its waves.

[[v26-26-4]]

^<<v26-26-4,4>>^ They will destroy the walls of Tyre and tear down her towers, and I will scrape away soil and make her a shining, bare rock.

[[v26-26-5]]

^<<v26-26-5,5>>^ She will become a drying yard for dragnets in the midst of the sea.’
“‘For I myself have spoken,’ declares the Sovereign Lord Jehovah, ‘and she will become plunder for the nations.

[[v26-26-6]]

^<<v26-26-6,6>>^ And her settlements^&#42;1^ in the countryside will be slaughtered by the sword, and people will have to know that I am Jehovah.’

[NOTE]
====
. Lit., “daughters.”
====

[[v26-26-7]]

^<<v26-26-7,7>>^ “For this is what the Sovereign Lord Jehovah says: ‘Here I am bringing King Neb·u·chad·nezʹzar^&#42;1^ of Babylon against Tyre from the north; he is a king of kings, with horses, war chariots, cavalrymen, and an army of many soldiers.^&#42;2^

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
. Lit., “peoples.”
====

[[v26-26-8]]

^<<v26-26-8,8>>^ He will destroy your settlements in the countryside with the sword, and he will build a siege wall and throw up a siege rampart against you and raise up a great shield against you.

[[v26-26-9]]

^<<v26-26-9,9>>^ He will pound your walls with his battering ram,^&#42;1^ and with his axes^&#42;2^ he will pull down your towers.

[NOTE]
====
. Or “his attack engine.”
. Or “swords.”
====

[[v26-26-10]]

^<<v26-26-10,10>>^ His horses will be so many that they will cover you with dust, and the sound of the cavalry, the wheels, and the chariots will cause your walls to shake when he enters your gates, like men storming a city with broken walls.

[[v26-26-11]]

^<<v26-26-11,11>>^ The hooves of his horses will trample down all your streets; he will kill your people with the sword, and your mighty pillars will crash to the ground.

[[v26-26-12]]

^<<v26-26-12,12>>^ They will loot your resources, plunder your merchandise, tear down your walls, and pull down your fine houses; then they will throw your stones and your woodwork and your soil into the water.’

[[v26-26-13]]

^<<v26-26-13,13>>^ “‘I will put an end to the noise of your songs, and the sound of your harps will be heard no more.

[[v26-26-14]]

^<<v26-26-14,14>>^ And I will make you a shining, bare rock, and you will become a drying yard for dragnets. You will never be rebuilt, for I myself, Jehovah, have spoken,’ declares the Sovereign Lord Jehovah.

[[v26-26-15]]

^<<v26-26-15,15>>^ “This is what the Sovereign Lord Jehovah says to Tyre: ‘At the sound of your downfall, when the dying ones^&#42;1^ are groaning, when a slaughter takes place in your midst, will the islands not shudder?

[NOTE]
====
. Lit., “the slain.”
====

[[v26-26-16]]

^<<v26-26-16,16>>^ All the princes^&#42;1^ of the sea will come down from their thrones and remove their robes^&#42;2^ and strip off their embroidered garments, and they will be seized with^&#42;3^ trembling. They will sit on the ground and tremble constantly and stare at you in amazement.

[NOTE]
====
. Or “chieftains.”
. Or “sleeveless coats.”
. Lit., “clothed with.”
====

[[v26-26-17]]

^<<v26-26-17,17>>^ And they will sing a dirge^&#42;1^ over you and say to you:
“How you have perished, you who were inhabited from the seas, the praised city;
You and your^&#42;2^ inhabitants were mighty on the sea,
Spreading terror to all the inhabitants of the earth!

[NOTE]
====
. Or “song of mourning.”
. Lit., “She and her.”
====

[[v26-26-18]]

^<<v26-26-18,18>>^ The islands will tremble on the day of your downfall,
The islands of the sea will be disturbed when you are gone.”’

[[v26-26-19]]

^<<v26-26-19,19>>^ “For this is what the Sovereign Lord Jehovah says: ‘When I devastate you like the cities that are not inhabited, when I overwhelm you with the surging waters and the mighty waters have covered you,

[[v26-26-20]]

^<<v26-26-20,20>>^ I will bring you and those going down into the pit^&#42;1^ with you to the people of long ago; I will cause you to dwell in the lowest place, like the places of old that have been devastated, together with those going down into the pit, so that you may not be inhabited. Then I will glorify^&#42;2^ the land of the living.

[NOTE]
====
. Or “grave.”
. Or “decorate.”
====

[[v26-26-21]]

^<<v26-26-21,21>>^ “‘I will bring sudden terror upon you, and you will no longer be. They will search for you, but you will never again be found,’ declares the Sovereign Lord Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-025.adoc#v26-25-0[&#60; Capítulo Anterior] | <<v26-26-0,Topo>> | xref:026-ezekiel/026-ezekiel-027.adoc#v26-27-0[Próximo Capítulo &#62;]