include::./index.adoc[]

[[v26-40-0]]
=== Ezekiel, 40
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-40-1]]

^<<v26-40-1,1>>^ In the 25th year of our exile, at the beginning of the year, on the tenth day of the month, in the 14th year after the city had fallen, on that very day the hand of Jehovah was upon me, and he took me to the city.

[[v26-40-2]]

^<<v26-40-2,2>>^ By means of visions from God, he brought me to the land of Israel and set me down on a very high mountain, on which there was a structure like a city to the south.

[[v26-40-3]]

^<<v26-40-3,3>>^ When he brought me there, I saw a man whose appearance was like that of copper. He had a flax cord and a measuring reed^&#42;1^ in his hand, and he was standing in the gateway.

[NOTE]
====
. See App. B14.
====

[[v26-40-4]]

^<<v26-40-4,4>>^ The man said to me: “Son of man, look closely, listen carefully, and pay attention^&#42;1^ to everything I show you, for that is why you were brought here. Tell the house of Israel everything that you see.”

[NOTE]
====
. Lit., “set your heart.”
====

[[v26-40-5]]

^<<v26-40-5,5>>^ I saw a wall surrounding the outside of the temple.^&#42;1^ In the man’s hand was a measuring reed six cubits long (to each cubit, a handbreadth was added).^&#42;2^ He began to measure the wall, and its thickness was one reed and its height was one reed.

[NOTE]
====
. Lit., “house.” Rendered this way in chapters 40-48 when “house” refers to the temple complex or the actual temple building.
. Lit., “a measuring reed of six cubits, a cubit and a handbreadth.” This refers to long cubits. See App. B14.
====

[[v26-40-6]]

^<<v26-40-6,6>>^ Then he came to the gate that faced east and climbed its steps. When he measured the threshold of the gate, its width was one reed, and the width of the other threshold was also one reed.

[[v26-40-7]]

^<<v26-40-7,7>>^ Each guard chamber was one reed long and one reed wide, and there were five cubits between the guard chambers. The threshold of the gate beside the porch of the gate facing the interior measured one reed.

[[v26-40-8]]

^<<v26-40-8,8>>^ He measured the porch of the gate toward the interior, and it was one reed.

[[v26-40-9]]

^<<v26-40-9,9>>^ He then measured the porch of the gate, which was eight cubits; and he measured its side pillars, which were two cubits; and the porch of the gate was on the side facing the interior.

[[v26-40-10]]

^<<v26-40-10,10>>^ There were three guard chambers on each side of the east gate. The three were the same size, and the side pillars on either side were the same size.

[[v26-40-11]]

^<<v26-40-11,11>>^ Then he measured the width of the entrance of the gate, which was 10 cubits; and the length of the gate was 13 cubits.

[[v26-40-12]]

^<<v26-40-12,12>>^ The partitioned area in front of the guard chambers on either side was one cubit. The guard chambers on both sides were six cubits each.

[[v26-40-13]]

^<<v26-40-13,13>>^ He then measured the gate from the roof of the one guard chamber^&#42;1^ to the roof of the other, and it was 25 cubits wide; one entrance was across from the other entrance.

[NOTE]
====
. Possibly referring to the top of the wall of the guard chamber.
====

[[v26-40-14]]

^<<v26-40-14,14>>^ Then he measured the side pillars, which were 60 cubits tall, as well as the side pillars in the gates all around the courtyard.

[[v26-40-15]]

^<<v26-40-15,15>>^ From the front of the entrance of the gate to the front of the porch on the inner side of the gate was 50 cubits.

[[v26-40-16]]

^<<v26-40-16,16>>^ There were windows with narrowing frames^&#42;1^ for the guard chambers and for their side pillars inside the gate on each side. The interior of the porches also had windows on each side, and there were palm-tree figures on the side pillars.

[NOTE]
====
. Or “beveled (splayed) windows.”
====

[[v26-40-17]]

^<<v26-40-17,17>>^ He then brought me into the outer courtyard, and I saw dining rooms^&#42;1^ and a pavement around the courtyard. There were 30 dining rooms on the pavement.

[NOTE]
====
. Or “I saw chambers.”
====

[[v26-40-18]]

^<<v26-40-18,18>>^ The pavement at the side of the gates corresponded to the length of the gates—this was the lower pavement.

[[v26-40-19]]

^<<v26-40-19,19>>^ Then he measured the distance^&#42;1^ from the front of the lower gate to the perimeter of the inner courtyard. It was 100 cubits on the east and on the north.

[NOTE]
====
. Lit., “width.”
====

[[v26-40-20]]

^<<v26-40-20,20>>^ The outer courtyard had a gate facing north, and he measured its length and its width.

[[v26-40-21]]

^<<v26-40-21,21>>^ There were three guard chambers on each side. Its side pillars and porch had the same measurements as the first gate. It was 50 cubits long and 25 cubits wide.

[[v26-40-22]]

^<<v26-40-22,22>>^ Its windows, its porch, and its palm-tree figures were the same size as those of the east gate. People could reach it by climbing seven steps, and its porch was in front of them.

[[v26-40-23]]

^<<v26-40-23,23>>^ There was a gate in the inner courtyard opposite the north gate and one opposite the east gate. He measured the distance from gate to gate, and it was 100 cubits.

[[v26-40-24]]

^<<v26-40-24,24>>^ Next he brought me toward the south, and I saw a gate on the south side. He measured its side pillars and its porch, and they were the same size as the others.

[[v26-40-25]]

^<<v26-40-25,25>>^ There were windows on each side of it and its porch, like the other windows. It was 50 cubits long and 25 cubits wide.

[[v26-40-26]]

^<<v26-40-26,26>>^ There were seven steps leading up to it, and its porch was in front of them. And it had palm-tree figures on its side pillars, one on each side.

[[v26-40-27]]

^<<v26-40-27,27>>^ The inner courtyard had a gate facing south; he measured southward from gate to gate, and the distance was 100 cubits.

[[v26-40-28]]

^<<v26-40-28,28>>^ Next he brought me into the inner courtyard through the south gate; when he measured the south gate, it was the same size as the others.

[[v26-40-29]]

^<<v26-40-29,29>>^ Its guard chambers, its side pillars, and its porch were the same size as the others. There were windows on each side of it and its porch. It was 50 cubits long and 25 cubits wide.

[[v26-40-30]]

^<<v26-40-30,30>>^ There were porches all around; they were 25 cubits long and 5 cubits wide.

[[v26-40-31]]

^<<v26-40-31,31>>^ Its porch faced the outer courtyard, and there were palm-tree figures on its side pillars, and eight steps led up to it.

[[v26-40-32]]

^<<v26-40-32,32>>^ When he brought me into the inner courtyard from the east, he measured the gate, and it was the same size as the others.

[[v26-40-33]]

^<<v26-40-33,33>>^ Its guard chambers, its side pillars, and its porch were the same size as the others, and there were windows on each side of it and its porch. It was 50 cubits long and 25 cubits wide.

[[v26-40-34]]

^<<v26-40-34,34>>^ Its porch faced the outer courtyard, and there were palm-tree figures on both of its side pillars, and eight steps led up to it.

[[v26-40-35]]

^<<v26-40-35,35>>^ He then brought me into the north gate and measured it; it was the same size as the others.

[[v26-40-36]]

^<<v26-40-36,36>>^ Its guard chambers, its side pillars, and its porch were the same as the others. It had windows on each side. It was 50 cubits long and 25 cubits wide.

[[v26-40-37]]

^<<v26-40-37,37>>^ Its side pillars faced the outer courtyard, and there were palm-tree figures on both of its side pillars, and eight steps led up to it.

[[v26-40-38]]

^<<v26-40-38,38>>^ A dining room with its entrance was near the side pillars of the gates, where the whole burnt offerings were washed.

[[v26-40-39]]

^<<v26-40-39,39>>^ There were two tables on each side of the porch of the gate on which to slaughter the whole burnt offerings, the sin offerings, and the guilt offerings.

[[v26-40-40]]

^<<v26-40-40,40>>^ On the way up to the north gate, there were two tables outside the entrance. There were also two tables on the other side of the porch of the gate.

[[v26-40-41]]

^<<v26-40-41,41>>^ There were four tables on each side of the gate—eight tables in all—on which the sacrifices were slaughtered.

[[v26-40-42]]

^<<v26-40-42,42>>^ The four tables for the whole burnt offering were of hewn stone. They were one and a half cubits long, one and a half cubits wide, and one cubit high. On them were kept the implements used to slaughter the burnt offerings and the sacrifices.

[[v26-40-43]]

^<<v26-40-43,43>>^ Shelves, one handbreadth wide, were attached all around the interior walls; and the flesh of the gift offerings would be placed on the tables.

[[v26-40-44]]

^<<v26-40-44,44>>^ Outside the inner gate were the dining rooms for the singers; they were in the inner courtyard near the north gate, facing south. Another dining room was near the east gate, facing north.

[[v26-40-45]]

^<<v26-40-45,45>>^ He said to me: “This dining room that faces south is for the priests who are responsible for the services in the temple.

[[v26-40-46]]

^<<v26-40-46,46>>^ The dining room that faces north is for the priests who are responsible for the service of the altar. They are the sons of Zaʹdok, those from the Levites who are assigned to approach Jehovah to minister to him.”

[[v26-40-47]]

^<<v26-40-47,47>>^ Then he measured the inner courtyard. It was 100 cubits long and 100 cubits wide, foursquare. The altar was in front of the temple.

[[v26-40-48]]

^<<v26-40-48,48>>^ Then he brought me into the porch of the temple, and he measured the side pillar of the porch, and it was five cubits on one side and five cubits on the other side. The width of the gate was three cubits on one side and three cubits on the other side.

[[v26-40-49]]

^<<v26-40-49,49>>^ The porch was 20 cubits long and 11^&#42;1^ cubits wide. People would reach it by climbing the steps. There were pillars by the side posts, one on each side.

[NOTE]
====
. Or possibly, “12.”
====

'''

xref:026-ezekiel/026-ezekiel-039.adoc#v26-39-0[&#60; Capítulo Anterior] | <<v26-40-0,Topo>> | xref:026-ezekiel/026-ezekiel-041.adoc#v26-41-0[Próximo Capítulo &#62;]