include::./index.adoc[]

[[v26-37-0]]
=== Ezekiel, 37
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-37-1]]

^<<v26-37-1,1>>^ The hand of Jehovah was upon me, and by his spirit Jehovah took me and set me down in the middle of the valley plain, and it was full of bones.

[[v26-37-2]]

^<<v26-37-2,2>>^ He had me pass all around them, and I saw that there were very many bones lying in the valley plain, and they were very dry.

[[v26-37-3]]

^<<v26-37-3,3>>^ He asked me: “Son of man, can these bones come to life?” To that I said: “Sovereign Lord Jehovah, you are the one who knows.”

[[v26-37-4]]

^<<v26-37-4,4>>^ So he said to me: “Prophesy over these bones, and say to them, ‘You dry bones, hear the word of Jehovah:

[[v26-37-5]]

^<<v26-37-5,5>>^ “‘This is what the Sovereign Lord Jehovah says to these bones: “I will cause breath to enter you, and you will come to life.

[[v26-37-6]]

^<<v26-37-6,6>>^ I will put sinews and flesh on you, and I will cover you with skin and put breath in you, and you will come to life; and you will have to know that I am Jehovah.”’”

[[v26-37-7]]

^<<v26-37-7,7>>^ Then I prophesied just as I had been commanded. As soon as I prophesied, there was a noise, a rattling sound, and the bones began to come together, bone to bone.

[[v26-37-8]]

^<<v26-37-8,8>>^ Then I saw sinews and flesh come on them, and skin covered over them. But there was still no breath in them.

[[v26-37-9]]

^<<v26-37-9,9>>^ He then said to me: “Prophesy to the wind. Prophesy, son of man, and say to the wind, ‘This is what the Sovereign Lord Jehovah says: “From the four winds come in, O wind,^&#42;1^ and blow upon these people who were killed, so that they may come to life.”’”

[NOTE]
====
. Or “breath; spirit.”
====

[[v26-37-10]]

^<<v26-37-10,10>>^ So I prophesied just as he commanded me, and breath^&#42;1^ came into them, and they began to live and to stand on their feet, an extremely large army.

[NOTE]
====
. Or “spirit.”
====

[[v26-37-11]]

^<<v26-37-11,11>>^ Then he said to me: “Son of man, these bones are the whole house of Israel. Here they are saying, ‘Our bones are dry, and our hope has perished. We are completely cut off.’

[[v26-37-12]]

^<<v26-37-12,12>>^ So prophesy and say to them, ‘This is what the Sovereign Lord Jehovah says: “I will open your graves and raise you up from your graves, my people, and bring you to the land of Israel.

[[v26-37-13]]

^<<v26-37-13,13>>^ And you will have to know that I am Jehovah when I open your graves and when I raise you up out of your graves, O my people.”’

[[v26-37-14]]

^<<v26-37-14,14>>^ ‘I will put my spirit in you and you will come to life, and I will settle you on your land; and you will have to know that I myself, Jehovah, have spoken and I have done it,’ declares Jehovah.”

[[v26-37-15]]

^<<v26-37-15,15>>^ The word of Jehovah again came to me, saying:

[[v26-37-16]]

^<<v26-37-16,16>>^ “And you, son of man, take a stick and write on it, ‘For Judah and for the people of Israel who are with him.’^&#42;1^ Then take another stick and write on it, ‘For Joseph, the stick of Eʹphra·im, and all the house of Israel who are with him.’^&#42;2^

[NOTE]
====
. Or “who are his partners.”
. Or “who are his partners.”
====

[[v26-37-17]]

^<<v26-37-17,17>>^ Then bring them close to each other so that they become just one stick in your hand.

[[v26-37-18]]

^<<v26-37-18,18>>^ When your people^&#42;1^ say to you, ‘Will you not tell us what these things mean?’

[NOTE]
====
. Lit., “the sons of your people.”
====

[[v26-37-19]]

^<<v26-37-19,19>>^ tell them, ‘This is what the Sovereign Lord Jehovah says: “I will take the stick of Joseph, which is in the hand of Eʹphra·im, and the tribes of Israel who are with him, and I will join them to the stick of Judah; and I will make them one stick, and they will become one in my hand.”’

[[v26-37-20]]

^<<v26-37-20,20>>^ The sticks that you write on should be in your hand for them to see.

[[v26-37-21]]

^<<v26-37-21,21>>^ “Then tell them, ‘This is what the Sovereign Lord Jehovah says: “I will take the Israelites from among the nations where they have gone, and I will collect them together from every direction and bring them to their land.

[[v26-37-22]]

^<<v26-37-22,22>>^ I will make them one nation in the land, on the mountains of Israel, and one king will rule over all of them, and they will no longer be two nations; nor will they be divided any longer into two kingdoms.

[[v26-37-23]]

^<<v26-37-23,23>>^ They will no longer defile themselves with their disgusting idols^&#42;1^ and their detestable practices and all their transgressions. I will save them from all their unfaithfulness by which they have sinned, and I will cleanse them. They will be my people, and I myself will be their God.

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v26-37-24]]

^<<v26-37-24,24>>^ “‘“My servant David will be their king, and they will all have one shepherd. They will walk in my judicial decisions and carefully observe my statutes.

[[v26-37-25]]

^<<v26-37-25,25>>^ They will dwell on the land that I gave to my servant, to Jacob, where your forefathers lived, and they will dwell on it forever, they and their children^&#42;1^ and their children’s children; and David my servant will be their chieftain^&#42;2^ forever.

[NOTE]
====
. Lit., “sons.”
. Or “prince.”
====

[[v26-37-26]]

^<<v26-37-26,26>>^ “‘“And I will make a covenant of peace with them; it will be an eternal covenant with them. I will establish them and make them many and place my sanctuary among them forever.

[[v26-37-27]]

^<<v26-37-27,27>>^ My tent^&#42;1^ will be with^&#42;2^ them, and I will be their God, and they will be my people.

[NOTE]
====
. Or “dwelling place; home.”
. Or “over.”
====

[[v26-37-28]]

^<<v26-37-28,28>>^ And the nations will have to know that I, Jehovah, am sanctifying Israel when my sanctuary is in their midst forever.”’”

'''

xref:026-ezekiel/026-ezekiel-036.adoc#v26-36-0[&#60; Capítulo Anterior] | <<v26-37-0,Topo>> | xref:026-ezekiel/026-ezekiel-038.adoc#v26-38-0[Próximo Capítulo &#62;]