include::./index.adoc[]

[[v26-48-0]]
=== Ezekiel, 48
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-48-1]]

^<<v26-48-1,1>>^ “These are the names of the tribes, starting from the northern extremity: Dan’s portion runs along the way of Hethʹlon to Leʹbo-haʹmath^&#42;1^ to Haʹzar-eʹnan, along the boundary of Damascus northward, beside Haʹmath; and it extends from the eastern to the western border.

[NOTE]
====
. Or “the entrance of Hamath.”
====

[[v26-48-2]]

^<<v26-48-2,2>>^ Ashʹer’s portion is on the boundary of Dan, from the eastern border to the western border.

[[v26-48-3]]

^<<v26-48-3,3>>^ Naphʹta·li’s portion is on the boundary of Ashʹer, from the eastern border to the western border.

[[v26-48-4]]

^<<v26-48-4,4>>^ Ma·nasʹseh’s portion is on the boundary of Naphʹta·li, from the eastern border to the western border.

[[v26-48-5]]

^<<v26-48-5,5>>^ Eʹphra·im’s portion is on the boundary of Ma·nasʹseh, from the eastern border to the western border.

[[v26-48-6]]

^<<v26-48-6,6>>^ Reuʹben’s portion is on the boundary of Eʹphra·im, from the eastern border to the western border.

[[v26-48-7]]

^<<v26-48-7,7>>^ Judah’s portion is on the boundary of Reuʹben, from the eastern border to the western border.

[[v26-48-8]]

^<<v26-48-8,8>>^ On the boundary of Judah, from the eastern border to the western border, the contribution that you are to set apart should be 25,000 cubits^&#42;1^ wide and correspond to the length of the other tribal portions from the eastern border to the western border. The sanctuary will be in the middle of it.

[NOTE]
====
. This refers to long cubits. See App. B14.
====

[[v26-48-9]]

^<<v26-48-9,9>>^ “The contribution that you are to set apart to Jehovah will be 25,000 cubits long and 10,000 wide.

[[v26-48-10]]

^<<v26-48-10,10>>^ This will be the holy contribution for the priests. It will be 25,000 cubits on the north side, 10,000 on the west, 10,000 on the east, and 25,000 on the south. The sanctuary of Jehovah will be in the middle of it.

[[v26-48-11]]

^<<v26-48-11,11>>^ It will be for the sanctified priests from the sons of Zaʹdok, those who took care of their responsibilities toward me and did not go astray when the Israelites and the Levites went astray.

[[v26-48-12]]

^<<v26-48-12,12>>^ They will have a portion of the contribution of the land set apart as something most holy, on the boundary of the Levites.

[[v26-48-13]]

^<<v26-48-13,13>>^ “Right next to the territory of the priests, the Levites will have a portion 25,000 cubits long and 10,000 wide. (The whole length will be 25,000 long and 10,000 wide.)

[[v26-48-14]]

^<<v26-48-14,14>>^ They should not sell, exchange, or transfer any of this choicest portion of the land, for it is something holy to Jehovah.

[[v26-48-15]]

^<<v26-48-15,15>>^ “The remaining area that is 5,000 cubits wide alongside the 25,000 cubit border will be for common use of the city, for housing and pasture ground. The city will be in the middle of it.

[[v26-48-16]]

^<<v26-48-16,16>>^ These are the city’s measurements: The northern border is 4,500 cubits, the southern border is 4,500, the eastern border is 4,500, and the western border is 4,500.

[[v26-48-17]]

^<<v26-48-17,17>>^ The pasture ground of the city will be 250 cubits to the north, 250 to the south, 250 to the east, and 250 to the west.

[[v26-48-18]]

^<<v26-48-18,18>>^ “The length of the remaining portion will correspond to the holy contribution, 10,000 cubits to the east and 10,000 to the west. It will correspond to the holy contribution, and its produce will provide food for those serving the city.

[[v26-48-19]]

^<<v26-48-19,19>>^ Those who are serving the city from all the tribes of Israel will cultivate it.

[[v26-48-20]]

^<<v26-48-20,20>>^ “The whole contribution is 25,000 cubits square. You should set it aside as the holy contribution along with the possession of the city.

[[v26-48-21]]

^<<v26-48-21,21>>^ “What remains on both sides of the holy contribution and of the possession of the city will belong to the chieftain. It will be alongside the 25,000 cubit borders that are east and west of the contribution. It will correspond to those adjoining portions, and it will be for the chieftain. The holy contribution and the sanctuary of the temple will be in the middle of it.

[[v26-48-22]]

^<<v26-48-22,22>>^ “The possession of the Levites and the possession of the city will be between what belongs to the chieftain. The chieftain’s territory will be between the boundary of Judah and the boundary of Benjamin.

[[v26-48-23]]

^<<v26-48-23,23>>^ “As for the remaining tribes, Benjamin’s portion is from the eastern border to the western border.

[[v26-48-24]]

^<<v26-48-24,24>>^ Simʹe·on’s portion is by the boundary of Benjamin, from the eastern border to the western border.

[[v26-48-25]]

^<<v26-48-25,25>>^ Isʹsa·char’s portion is by the boundary of Simʹe·on, from the eastern border to the western border.

[[v26-48-26]]

^<<v26-48-26,26>>^ Zebʹu·lun’s portion is by the boundary of Isʹsa·char, from the eastern border to the western border.

[[v26-48-27]]

^<<v26-48-27,27>>^ Gad’s portion is by the boundary of Zebʹu·lun, from the eastern border to the western border.

[[v26-48-28]]

^<<v26-48-28,28>>^ The southern border by the boundary of Gad will run from Taʹmar to the waters of Merʹi·bath-kaʹdesh, to the Wadi^&#42;1^ and on to the Great Sea.^&#42;2^

[NOTE]
====
. That is, the Wadi of Egypt.
. That is, the Mediterranean.
====

[[v26-48-29]]

^<<v26-48-29,29>>^ “This is the land that you should distribute as an inheritance to the tribes of Israel, and these will be their portions,” declares the Sovereign Lord Jehovah.

[[v26-48-30]]

^<<v26-48-30,30>>^ “These will be the exits of the city: The northern side will measure 4,500 cubits.

[[v26-48-31]]

^<<v26-48-31,31>>^ “The gates of the city will be named according to the tribes of Israel. Of the three gates on the north, there is one gate for Reuʹben, one gate for Judah, and one gate for Leʹvi.

[[v26-48-32]]

^<<v26-48-32,32>>^ “The eastern side will be 4,500 cubits long, and there are three gates: one gate for Joseph, one gate for Benjamin, and one gate for Dan.

[[v26-48-33]]

^<<v26-48-33,33>>^ “The southern side will measure 4,500 cubits, with three gates: one gate for Simʹe·on, one gate for Isʹsa·char, and one gate for Zebʹu·lun.

[[v26-48-34]]

^<<v26-48-34,34>>^ “The western side will be 4,500 cubits long, with three gates: one gate for Gad, one gate for Ashʹer, and one gate for Naphʹta·li.

[[v26-48-35]]

^<<v26-48-35,35>>^ “The perimeter will be 18,000 cubits. And the name of the city from that day on will be Jehovah Is There.”

'''

xref:026-ezekiel/026-ezekiel-047.adoc#v26-47-0[&#60; Capítulo Anterior] | <<v26-48-0,Topo>> | xref:027-daniel/027-daniel-001.adoc#v27-1-0[Próximo Capítulo &#62;]