include::./index.adoc[]

[[v26-31-0]]
=== Ezekiel, 31
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-31-1]]

^<<v26-31-1,1>>^ In the 11th year, in the third month, on the first day of the month, the word of Jehovah again came to me, saying:

[[v26-31-2]]

^<<v26-31-2,2>>^ “Son of man, say to Pharʹaoh king of Egypt and to his hordes,
‘Whom are you like in your greatness?

[[v26-31-3]]

^<<v26-31-3,3>>^ There was an As·syrʹi·an, a cedar in Lebʹa·non,
With beautiful branches like a shady thicket, lofty in stature;
Its top was among the clouds.

[[v26-31-4]]

^<<v26-31-4,4>>^ The waters made it grow big, the deep springs of water caused it to grow high.
Streams were all around where it was planted;
Their channels watered all the trees of the field.

[[v26-31-5]]

^<<v26-31-5,5>>^ That is why it grew taller than all the other trees of the field.
Its boughs multiplied, and its branches grew long
Because of the abundant water in its streams.

[[v26-31-6]]

^<<v26-31-6,6>>^ All the birds of the sky nested in its boughs,
All the wild animals of the field gave birth under its branches,
And all the populous nations were dwelling in its shade.

[[v26-31-7]]

^<<v26-31-7,7>>^ It became majestic in beauty and in the length of its branches,
For its roots went down into abundant waters.

[[v26-31-8]]

^<<v26-31-8,8>>^ No other cedars in the garden of God could compare to it.
None of the juniper trees had boughs like it,
And none of the plane trees could match its branches.
No other tree in the garden of God could rival its beauty.

[[v26-31-9]]

^<<v26-31-9,9>>^ I made it beautiful, with abundant foliage,
And all the other trees of Eʹden, the garden of the true God, envied it.’

[[v26-31-10]]

^<<v26-31-10,10>>^ “Therefore this is what the Sovereign Lord Jehovah says: ‘Because it^&#42;1^ became so tall, lifting its top among the clouds, and its heart became arrogant because of its height,

[NOTE]
====
. Lit., “you.”
====

[[v26-31-11]]

^<<v26-31-11,11>>^ I will hand it over to the mighty ruler of the nations. He will surely act against it, and I will reject it for its wickedness.

[[v26-31-12]]

^<<v26-31-12,12>>^ And foreigners, the most ruthless of the nations, will cut it down, and they will abandon it on the mountains, and its foliage will fall in all the valleys, and its branches will lie broken in all the streams of the land. All the peoples of the earth will depart from its shade and abandon it.

[[v26-31-13]]

^<<v26-31-13,13>>^ All the birds of the sky will live on its fallen trunk, and all the wild animals of the field on its branches.

[[v26-31-14]]

^<<v26-31-14,14>>^ This is so that no tree near the waters should grow so tall or lift up its top among the clouds and that no well-watered tree may reach up to them in height. For they will all be given over to death, to the land down below, along with the sons of mankind, who are going down into the pit.’^&#42;1^

[NOTE]
====
. Or “grave.”
====

[[v26-31-15]]

^<<v26-31-15,15>>^ “This is what the Sovereign Lord Jehovah says: ‘On the day it goes down to the Grave,^&#42;1^ I will cause a mourning. Therefore, I will cover over the deep waters and hold back its streams so that the abundant waters are restrained. I will darken Lebʹa·non because of it, and the trees of the field will all wither away.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v26-31-16]]

^<<v26-31-16,16>>^ At the sound of its downfall, I will cause nations to shudder when I bring it down to the Grave^&#42;1^ along with all those going down into the pit,^&#42;2^ and all the trees of Eʹden, the choicest and the best of Lebʹa·non, all that are well-watered, will be comforted in the land down below.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
. Or “grave.”
====

[[v26-31-17]]

^<<v26-31-17,17>>^ They have gone down to the Grave^&#42;1^ with him, to those slain by the sword, together with his supporters^&#42;2^ who lived in his shadow among the nations.’

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
. Lit., “arm.”
====

[[v26-31-18]]

^<<v26-31-18,18>>^ “‘Which of the trees of Eʹden was like you in glory and greatness? But you will certainly be brought down with the trees of Eʹden to the land down below. You will lie down among the uncircumcised ones, with those slain by the sword. This will happen to Pharʹaoh and all his hordes,’ declares the Sovereign Lord Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-030.adoc#v26-30-0[&#60; Capítulo Anterior] | <<v26-31-0,Topo>> | xref:026-ezekiel/026-ezekiel-032.adoc#v26-32-0[Próximo Capítulo &#62;]