include::./index.adoc[]

[[v26-39-0]]
=== Ezekiel, 39
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-39-1]]

^<<v26-39-1,1>>^ “And you, son of man, prophesy against Gog, and tell him, ‘This is what the Sovereign Lord Jehovah says: “I am against you, Gog, head chieftain^&#42;1^ of Meʹshech and Tuʹbal.

[NOTE]
====
. Or “chief prince.”
====

[[v26-39-2]]

^<<v26-39-2,2>>^ I will turn you around and lead you and make you come up from the remotest parts of the north and bring you in upon the mountains of Israel.

[[v26-39-3]]

^<<v26-39-3,3>>^ I will knock your bow out of your left hand and make your arrows fall from your right hand.

[[v26-39-4]]

^<<v26-39-4,4>>^ On the mountains of Israel you will fall, you and all your troops and the peoples who will be with you. I will give you as food to all kinds of birds of prey and the wild beasts of the field.”’

[[v26-39-5]]

^<<v26-39-5,5>>^ “‘You will fall on the open field, for I myself have spoken,’ declares the Sovereign Lord Jehovah.

[[v26-39-6]]

^<<v26-39-6,6>>^ “‘And I will send fire against Maʹgog and against those who are inhabiting the islands in security, and they will have to know that I am Jehovah.

[[v26-39-7]]

^<<v26-39-7,7>>^ I will make my holy name known among my people Israel, and I will not allow my holy name to be profaned any longer; and the nations will have to know that I am Jehovah, the Holy One in Israel.’

[[v26-39-8]]

^<<v26-39-8,8>>^ “‘Yes, this is coming, and it will be done,’ declares the Sovereign Lord Jehovah. ‘This is the day I have spoken about.

[[v26-39-9]]

^<<v26-39-9,9>>^ The inhabitants of the cities of Israel will go out and make fires with the weapons—the bucklers^&#42;1^ and shields, the bows and arrows, the war clubs^&#42;2^ and lances. And they will use them to light fires for seven years.

[NOTE]
====
. A small shield, often carried by archers.
. Or possibly, “handpikes,” a weapon with a pointed tip.
====

[[v26-39-10]]

^<<v26-39-10,10>>^ They will not need to take wood from the field or gather firewood from the forests because they will use the weapons to light fires.’
“‘They will take spoil from those who despoiled them and plunder from those who had been plundering them,’ declares the Sovereign Lord Jehovah.

[[v26-39-11]]

^<<v26-39-11,11>>^ “‘On that day I will give Gog a burial place there in Israel, in the valley of those who travel east of the sea, and it will block the path of those passing through. That is where they will bury Gog and all his hordes, and they will call it the Valley of Haʹmon-Gog.^&#42;1^

[NOTE]
====
. Or “the Valley of Gog’s Hordes.”
====

[[v26-39-12]]

^<<v26-39-12,12>>^ The house of Israel will spend seven months burying them in order to cleanse the land.

[[v26-39-13]]

^<<v26-39-13,13>>^ All the people of the land will work at burying them, and this will bring them fame in the day that I glorify myself,’ declares the Sovereign Lord Jehovah.

[[v26-39-14]]

^<<v26-39-14,14>>^ “‘Men will be assigned to pass through the land constantly and bury the bodies left remaining on the surface of the earth, in order to cleanse it. They will continue the search for seven months.

[[v26-39-15]]

^<<v26-39-15,15>>^ When those who pass through the land see a human bone, they will set up a marker beside it. Then those assigned to do the burying will bury it in the Valley of Haʹmon-Gog.

[[v26-39-16]]

^<<v26-39-16,16>>^ And there will also be a city there named Ha·moʹnah.^&#42;1^ And they will cleanse the land.’

[NOTE]
====
. Meaning “Hordes.”
====

[[v26-39-17]]

^<<v26-39-17,17>>^ “As for you, son of man, this is what the Sovereign Lord Jehovah says: ‘Say to every sort of bird and to all the wild beasts of the field, “Gather yourselves together and come. Gather all around my sacrifice that I am preparing for you, a great sacrifice on the mountains of Israel. You will eat flesh and drink blood.

[[v26-39-18]]

^<<v26-39-18,18>>^ You will eat the flesh of mighty ones and drink the blood of the chieftains of the earth—the rams, lambs, goats, and bulls—all the fattened animals of Baʹshan.

[[v26-39-19]]

^<<v26-39-19,19>>^ You will gorge yourselves on fat and drink blood until you are drunk from the sacrifice that I prepare for you.”’

[[v26-39-20]]

^<<v26-39-20,20>>^ “‘At my table you will be filled up with horses and charioteers, mighty ones and all sorts of warriors,’ declares the Sovereign Lord Jehovah.

[[v26-39-21]]

^<<v26-39-21,21>>^ “‘I will display my glory among the nations, and all the nations will see the judgment that I have executed and the power^&#42;1^ that I have demonstrated among them.

[NOTE]
====
. Lit., “hand.”
====

[[v26-39-22]]

^<<v26-39-22,22>>^ From that day on the house of Israel will have to know that I am Jehovah their God.

[[v26-39-23]]

^<<v26-39-23,23>>^ And the nations will have to know that the house of Israel went into exile because of their own error, because they were unfaithful to me. So I hid my face from them and handed them over to their enemies, and they all fell by the sword.

[[v26-39-24]]

^<<v26-39-24,24>>^ I dealt with them according to their uncleanness and their transgressions, and I hid my face from them.’

[[v26-39-25]]

^<<v26-39-25,25>>^ “Therefore this is what the Sovereign Lord Jehovah says: ‘I will restore the captives of Jacob and have mercy on the whole house of Israel; and I will zealously defend^&#42;1^ my holy name.

[NOTE]
====
. Lit., “show exclusive devotion for.”
====

[[v26-39-26]]

^<<v26-39-26,26>>^ After they have been humiliated for all their unfaithfulness toward me, they will dwell securely on their land, with no one to make them afraid.

[[v26-39-27]]

^<<v26-39-27,27>>^ When I bring them back from the peoples and collect them together from the lands of their enemies, I will also sanctify myself among them before the eyes of many nations.’

[[v26-39-28]]

^<<v26-39-28,28>>^ “‘They will have to know that I am Jehovah their God when I send them into exile among the nations and then gather them back to their land, not leaving any of them behind.

[[v26-39-29]]

^<<v26-39-29,29>>^ I will not hide my face from them any longer, for I will pour out my spirit on the house of Israel,’ declares the Sovereign Lord Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-038.adoc#v26-38-0[&#60; Capítulo Anterior] | <<v26-39-0,Topo>> | xref:026-ezekiel/026-ezekiel-040.adoc#v26-40-0[Próximo Capítulo &#62;]