include::./index.adoc[]

[[v26-18-0]]
=== Ezekiel, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-18-1]]

^<<v26-18-1,1>>^ And the word of Jehovah again came to me, saying:

[[v26-18-2]]

^<<v26-18-2,2>>^ “What does this proverb that you quote in the land of Israel mean, ‘Fathers have eaten sour grapes, but the teeth of the sons are set on edge’?

[[v26-18-3]]

^<<v26-18-3,3>>^ “‘As surely as I am alive,’ declares the Sovereign Lord Jehovah, ‘you will not continue to quote this saying in Israel.

[[v26-18-4]]

^<<v26-18-4,4>>^ Look! All the souls^&#42;1^—to me they belong. As the soul of the father so also the soul of the son—to me they belong. The soul^&#42;2^ who sins is the one who will die.

[NOTE]
====
. Or “lives.” See Glossary.
. Or “person.” See Glossary.
====

[[v26-18-5]]

^<<v26-18-5,5>>^ “‘Suppose that a man is righteous and does what is just and right.

[[v26-18-6]]

^<<v26-18-6,6>>^ He does not eat idolatrous sacrifices on the mountains; he does not look up to the disgusting idols^&#42;1^ of the house of Israel; he does not defile his neighbor’s wife or have relations with a woman who is menstruating;

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v26-18-7]]

^<<v26-18-7,7>>^ he does not mistreat anyone, but he returns what a debtor has given him in pledge; he does not rob anyone, but he gives his own food to the hungry one and covers the naked one with a garment;

[[v26-18-8]]

^<<v26-18-8,8>>^ he does not charge interest or engage in usury, but he refrains from acting with injustice; he executes true justice between one man and another;

[[v26-18-9]]

^<<v26-18-9,9>>^ and he keeps walking in my statutes and observing my judicial decisions in order to act in faithfulness. Such a man is righteous and will surely keep living,’ declares the Sovereign Lord Jehovah.

[[v26-18-10]]

^<<v26-18-10,10>>^ “‘But suppose that he has become father to a son who is a robber or a murderer^&#42;1^ or who does any of these other things

[NOTE]
====
. Lit., “shedder of blood.”
====

[[v26-18-11]]

^<<v26-18-11,11>>^ (though the father has not done any of these things)—he eats idolatrous sacrifices on the mountains, defiles his neighbor’s wife,

[[v26-18-12]]

^<<v26-18-12,12>>^ mistreats the needy and the poor, takes things by robbery, does not return a pledge, looks up to the disgusting idols, engages in detestable practices,

[[v26-18-13]]

^<<v26-18-13,13>>^ engages in usury and charges interest—then the son will not keep living. Because of all these detestable things that he has done, he will surely be put to death. His own blood will be upon him.

[[v26-18-14]]

^<<v26-18-14,14>>^ “‘But suppose that a father has a son who sees all the sins his father has committed, and though he sees them, he does not do such things.

[[v26-18-15]]

^<<v26-18-15,15>>^ He does not eat idolatrous sacrifices on the mountains; he does not look up to the disgusting idols of the house of Israel; he does not defile his neighbor’s wife;

[[v26-18-16]]

^<<v26-18-16,16>>^ he does not mistreat anyone; he does not seize what was pledged; he does not take anything in robbery; he gives his own food to the hungry one and covers the naked one with a garment;

[[v26-18-17]]

^<<v26-18-17,17>>^ he refrains from oppressing the poor; he does not engage in usury or charge interest; and he carries out my judicial decisions and walks in my statutes. Such a man will not die because of the error of his father. He will surely keep living.

[[v26-18-18]]

^<<v26-18-18,18>>^ But because his father practiced fraud, robbed his brother, and did what was wrong among his people, he will die for his error.

[[v26-18-19]]

^<<v26-18-19,19>>^ “‘But you will say: “Why does the son not bear guilt because of his father’s error?” Since the son has done what is just and righteous, has kept all my statutes and has observed them, he will surely keep living.

[[v26-18-20]]

^<<v26-18-20,20>>^ The soul^&#42;1^ who sins is the one who will die. A son will bear no guilt because of the error of his father, and a father will bear no guilt because of the error of his son. The righteousness of the righteous one will be accounted to him alone, and the wickedness of the wicked one will be accounted to him alone.

[NOTE]
====
. Or “person.”
====

[[v26-18-21]]

^<<v26-18-21,21>>^ “‘Now if someone wicked turns away from all the sins he has committed and keeps my statutes and does what is just and righteous, he will surely keep living. He will not die.

[[v26-18-22]]

^<<v26-18-22,22>>^ None of the transgressions that he has committed will be held^&#42;1^ against him. He will keep living for doing what is righteous.’

[NOTE]
====
. Lit., “remembered.”
====

[[v26-18-23]]

^<<v26-18-23,23>>^ “‘Do I take any pleasure at all in the death of a wicked person?’ declares the Sovereign Lord Jehovah. ‘Do I not prefer that he turn away from his ways and keep living?’

[[v26-18-24]]

^<<v26-18-24,24>>^ “‘But when someone righteous abandons his righteousness and does what is wrong,^&#42;1^ doing all the detestable things the wicked do, will he live? None of the righteous acts that he did will be remembered. For his unfaithfulness and the sin he has committed, he will die.

[NOTE]
====
. Or “does injustice.”
====

[[v26-18-25]]

^<<v26-18-25,25>>^ “‘But you will say: “The way of Jehovah is unjust.” Please listen, O house of Israel! Is it my way that is unjust? Is it not your ways that are unjust?

[[v26-18-26]]

^<<v26-18-26,26>>^ “‘When someone righteous abandons his righteousness and does what is wrong and dies because of it, he will die for his own wrongdoing.

[[v26-18-27]]

^<<v26-18-27,27>>^ “‘And when someone wicked turns away from the wickedness that he has committed and begins to do what is just and righteous, he will preserve his own life.^&#42;1^

[NOTE]
====
. Or “soul.” See Glossary.
====

[[v26-18-28]]

^<<v26-18-28,28>>^ When he realizes and turns away from all the transgressions that he has committed, he will surely keep living. He will not die.

[[v26-18-29]]

^<<v26-18-29,29>>^ “‘But the house of Israel will say: “The way of Jehovah is unjust.” Is it really my ways that are unjust, O house of Israel? Is it not your ways that are unjust?’

[[v26-18-30]]

^<<v26-18-30,30>>^ “‘Therefore, I will judge each one of you according to his ways, O house of Israel,’ declares the Sovereign Lord Jehovah. ‘Turn away, yes, turn completely away from all your transgressions, so that they will not be a stumbling block bringing guilt upon you.

[[v26-18-31]]

^<<v26-18-31,31>>^ Rid yourselves of all the transgressions you have committed and acquire^&#42;1^ a new heart and a new spirit, for why should you die, O house of Israel?’

[NOTE]
====
. Lit., “make for yourselves.”
====

[[v26-18-32]]

^<<v26-18-32,32>>^ “‘I do not take any pleasure in the death of anyone,’ declares the Sovereign Lord Jehovah. ‘So turn back and live.’”

'''

xref:026-ezekiel/026-ezekiel-017.adoc#v26-17-0[&#60; Capítulo Anterior] | <<v26-18-0,Topo>> | xref:026-ezekiel/026-ezekiel-019.adoc#v26-19-0[Próximo Capítulo &#62;]