include::./index.adoc[]

[[v26-27-0]]
=== Ezekiel, 27
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-27-1]]

^<<v26-27-1,1>>^ The word of Jehovah again came to me, saying:

[[v26-27-2]]

^<<v26-27-2,2>>^ “As for you, son of man, sing a dirge^&#42;1^ over Tyre,

[NOTE]
====
. Or “song of mourning.”
====

[[v26-27-3]]

^<<v26-27-3,3>>^ and say to Tyre,
‘You who dwell at the gateways of the sea,
The merchant for the peoples of many islands,
This is what the Sovereign Lord Jehovah says:
“O Tyre, you yourself have said, ‘I am perfect in beauty.’

[[v26-27-4]]

^<<v26-27-4,4>>^ Your territories are in the heart of the sea,
And your builders have perfected your beauty.

[[v26-27-5]]

^<<v26-27-5,5>>^ They made all your planks from the juniper trees of Seʹnir,
And they took a cedar from Lebʹa·non to make a mast for you.

[[v26-27-6]]

^<<v26-27-6,6>>^ They made your oars from oaks of Baʹshan,
And your prow was of cypress inlaid with ivory from the islands of Kitʹtim.

[[v26-27-7]]

^<<v26-27-7,7>>^ Colorful linen from Egypt served as cloth for your sail,
And your deck awnings were of blue thread and purple wool from the islands of E·liʹshah.

[[v26-27-8]]

^<<v26-27-8,8>>^ The inhabitants of Siʹdon and of Arʹvad were your rowers.
Your own skilled men, O Tyre, were your sailors.

[[v26-27-9]]

^<<v26-27-9,9>>^ The experienced^&#42;1^ and skilled men of Geʹbal caulked your seams.
All the ships of the sea and their mariners came to you to trade merchandise.

[NOTE]
====
. Lit., “The old men.”
====

[[v26-27-10]]

^<<v26-27-10,10>>^ Men of Persia, Lud, and Put were in your army, your men of war.
They hung their shields and helmets in you, and they brought you splendor.

[[v26-27-11]]

^<<v26-27-11,11>>^ The men of Arʹvad in your army were stationed on your walls all around,
And brave men manned your towers.
They hung circular shields all around your walls
And perfected your beauty.

[[v26-27-12]]

^<<v26-27-12,12>>^ “‘“Tarʹshish did business with you because of your abundant wealth. They exchanged silver, iron, tin, and lead for your goods.

[[v26-27-13]]

^<<v26-27-13,13>>^ Jaʹvan, Tuʹbal, and Meʹshech traded with you, exchanging slaves and articles of copper for your merchandise.

[[v26-27-14]]

^<<v26-27-14,14>>^ The house of To·garʹmah exchanged horses and steeds and mules for your goods.

[[v26-27-15]]

^<<v26-27-15,15>>^ The people of Deʹdan traded with you; you employed merchants on many islands; they gave ivory tusks and ebony as your tribute.

[[v26-27-16]]

^<<v26-27-16,16>>^ Eʹdom did business with you because of the abundance of your products. They gave turquoise, purple wool, colorful embroidery, fine fabric, corals, and rubies in exchange for your goods.

[[v26-27-17]]

^<<v26-27-17,17>>^ “‘“Judah and the land of Israel traded with you, giving the wheat of Minʹnith, choice foods, honey, oil, and balsam in exchange for your goods.

[[v26-27-18]]

^<<v26-27-18,18>>^ “‘“Damascus did business with you because of the abundance of your products and all your wealth, trading the wine of Helʹbon and wool of Zaʹhar.^&#42;1^

[NOTE]
====
. Or “and reddish-gray wool.”
====

[[v26-27-19]]

^<<v26-27-19,19>>^ Veʹdan and Jaʹvan from Uʹzal gave wrought iron, cassia,^&#42;1^ and cane^&#42;2^ in exchange for your goods.

[NOTE]
====
. A tree of the same family as the cinnamon tree.
. An aromatic reed.
====

[[v26-27-20]]

^<<v26-27-20,20>>^ Deʹdan traded with you in saddlecloths^&#42;1^ for riding.

[NOTE]
====
. Or “garments of woven material.”
====

[[v26-27-21]]

^<<v26-27-21,21>>^ You employed the Arabs and all the chieftains of Keʹdar, who were merchants of lambs and rams and goats.

[[v26-27-22]]

^<<v26-27-22,22>>^ The merchants of Sheʹba and Raʹa·mah traded with you; they gave all sorts of the finest perfumes, precious stones, and gold in exchange for your goods.

[[v26-27-23]]

^<<v26-27-23,23>>^ Haʹran, Canʹneh, Eʹden, the merchants of Sheʹba, Asʹshur, and Chilʹmad traded with you.

[[v26-27-24]]

^<<v26-27-24,24>>^ In your marketplace they traded beautiful garments, cloaks made of blue material and colorful embroidery, and multicolored carpets, all bound and secured with ropes.

[[v26-27-25]]

^<<v26-27-25,25>>^ The ships of Tarʹshish were the caravans for your merchandise,
So that you were filled and loaded down^&#42;1^ in the heart of the open sea.

[NOTE]
====
. Or possibly, “and glorious.”
====

[[v26-27-26]]

^<<v26-27-26,26>>^ Your rowers have brought you into heavy seas;
The east wind has wrecked you in the heart of the open sea.

[[v26-27-27]]

^<<v26-27-27,27>>^ Your wealth, your goods, your merchandise, your mariners, and your sailors,
Those caulking your seams, those trading your merchandise, and all the men of war
—The entire multitude^&#42;1^ within you—
They will all sink in the heart of the open sea on the day of your downfall.

[NOTE]
====
. Lit., “congregation.”
====

[[v26-27-28]]

^<<v26-27-28,28>>^ When your sailors cry out, the coastlands will shudder.

[[v26-27-29]]

^<<v26-27-29,29>>^ All the oarsmen, the mariners, and the seamen
Will come down from their ships and stand on the land.

[[v26-27-30]]

^<<v26-27-30,30>>^ They will raise their voices and cry out bitterly over you
As they throw dust on their heads and wallow in ashes.

[[v26-27-31]]

^<<v26-27-31,31>>^ They will make themselves bald and put on sackcloth;
They will weep bitterly^&#42;1^ over you with intense wailing.

[NOTE]
====
. Or “with bitterness of soul.”
====

[[v26-27-32]]

^<<v26-27-32,32>>^ In their lamentation they will sing a dirge and chant over you:
‘Who is like Tyre, now silent in the midst of the sea?

[[v26-27-33]]

^<<v26-27-33,33>>^ When your goods came in from the open sea, you satisfied many peoples.
Your abundant wealth and your merchandise enriched earth’s kings.

[[v26-27-34]]

^<<v26-27-34,34>>^ Now you have been wrecked in the open sea, in the deep waters,
And all your merchandise and your people have sunk with you.

[[v26-27-35]]

^<<v26-27-35,35>>^ All the inhabitants of the islands will stare at you in amazement,
And their kings will shudder with horror—their faces will be troubled.

[[v26-27-36]]

^<<v26-27-36,36>>^ The merchants among the nations will whistle over what happened to you.
Your end will be sudden and terrible,
And you will cease to exist for all time.’”’”

'''

xref:026-ezekiel/026-ezekiel-026.adoc#v26-26-0[&#60; Capítulo Anterior] | <<v26-27-0,Topo>> | xref:026-ezekiel/026-ezekiel-028.adoc#v26-28-0[Próximo Capítulo &#62;]