include::./index.adoc[]

[[v26-7-0]]
=== Ezekiel, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-7-1]]

^<<v26-7-1,1>>^ The word of Jehovah again came to me, saying:

[[v26-7-2]]

^<<v26-7-2,2>>^ “As for you, son of man, this is what the Sovereign Lord Jehovah says to the land of Israel: ‘An end! The end has come upon the four corners of the land.

[[v26-7-3]]

^<<v26-7-3,3>>^ The end is now upon you, and I will unleash my anger against you, and I will judge you according to your ways and call you to account for all your detestable deeds.

[[v26-7-4]]

^<<v26-7-4,4>>^ My eye will not feel sorry for you; nor will I feel compassion, for I will bring upon you the results of your own ways, and you will suffer the consequences of your detestable deeds. And you will have to know that I am Jehovah.’

[[v26-7-5]]

^<<v26-7-5,5>>^ “This is what the Sovereign Lord Jehovah says: ‘Look! A calamity, a unique calamity, is coming.

[[v26-7-6]]

^<<v26-7-6,6>>^ An end is coming; the end will come; it will rouse itself^&#42;1^ against you. Look! It is coming.

[NOTE]
====
. Lit., “awaken.”
====

[[v26-7-7]]

^<<v26-7-7,7>>^ Your turn^&#42;1^ has come, you who inhabit the land. The time is coming, the day is near. There is confusion and not joyful shouting on the mountains.

[NOTE]
====
. Or possibly, “The garland.”
====

[[v26-7-8]]

^<<v26-7-8,8>>^ “‘Very soon I will pour out my rage on you, and I will fully unleash my anger against you, and I will judge you according to your ways and call you to account for all your detestable deeds.

[[v26-7-9]]

^<<v26-7-9,9>>^ My eye will not feel sorry; nor will I feel compassion. I will bring on you the results of your ways, and you will suffer the consequences of your own detestable deeds. And you will have to know that I, Jehovah, am striking you.

[[v26-7-10]]

^<<v26-7-10,10>>^ “‘Look, the day! Look, it is coming! Your turn^&#42;1^ has come; the rod has blossomed and presumptuousness has sprouted.

[NOTE]
====
. Or possibly, “The garland.”
====

[[v26-7-11]]

^<<v26-7-11,11>>^ Violence has grown into a rod of wickedness. Neither they nor their wealth nor their crowds nor their prominence will survive.

[[v26-7-12]]

^<<v26-7-12,12>>^ The time will come, the day will arrive. Let the buyer not rejoice, and let the seller not mourn, for there is wrath against their whole crowd.^&#42;1^

[NOTE]
====
. That is, neither those who buy property nor those who sell it will benefit, since the destruction will come upon all.
====

[[v26-7-13]]

^<<v26-7-13,13>>^ For the seller will not return to what was sold, even if his life is spared, for the vision is against the entire multitude. No one will return, and because of his error,^&#42;1^ no one will preserve his life.

[NOTE]
====
. Or possibly, “by his error.”
====

[[v26-7-14]]

^<<v26-7-14,14>>^ “‘They have blown the trumpet, and everyone is ready, but no one is going to the battle, because my wrath is against the whole multitude.

[[v26-7-15]]

^<<v26-7-15,15>>^ The sword is outside, and the pestilence and the famine are inside. Whoever is in the field will die by the sword, and famine and pestilence will consume those in the city.

[[v26-7-16]]

^<<v26-7-16,16>>^ Their survivors who manage to escape will go to the mountains, and like the doves of the valleys, each one will moan over his error.

[[v26-7-17]]

^<<v26-7-17,17>>^ All their hands will hang limp, and all their knees will drip with water.^&#42;1^

[NOTE]
====
. That is, from urination as a result of fear.
====

[[v26-7-18]]

^<<v26-7-18,18>>^ They have put on sackcloth, and shuddering has seized^&#42;1^ them. Everyone will be put to shame, and every head will be bald.^&#42;2^

[NOTE]
====
. Lit., “covered.”
. That is, their heads will be shaved in mourning.
====

[[v26-7-19]]

^<<v26-7-19,19>>^ “‘They will throw their silver into the streets, and their gold will become abhorrent to them. Neither their silver nor their gold will be able to save them in the day of Jehovah’s fury. They^&#42;1^ will not be satisfied, nor will they fill their stomachs, for it^&#42;2^ has become a stumbling block causing their error.

[NOTE]
====
. Or “Their souls.”
. That is, their silver and their gold.
====

[[v26-7-20]]

^<<v26-7-20,20>>^ They took pride in the beauty of their ornaments, and they made with them^&#42;1^ their detestable images, their disgusting idols. That is why I will make it an abhorrent thing to them.

[NOTE]
====
. That is, their objects of gold and silver.
====

[[v26-7-21]]

^<<v26-7-21,21>>^ I will give it^&#42;1^ into the hand of the foreigners for plunder and to the wicked ones of the earth for spoil, and they will profane it.

[NOTE]
====
. That is, their silver and their gold used to make idols.
====

[[v26-7-22]]

^<<v26-7-22,22>>^ “‘I will turn my face away from them, and they will profane my concealed place,^&#42;1^ and robbers will enter it and profane it.

[NOTE]
====
. Apparently referring to the innermost part of Jehovah’s sanctuary.
====

[[v26-7-23]]

^<<v26-7-23,23>>^ “‘Make the chain,^&#42;1^ for the land is full of bloodstained judgment and the city is full of violence.

[NOTE]
====
. That is, chains of captivity.
====

[[v26-7-24]]

^<<v26-7-24,24>>^ I will bring in the worst of the nations, and they will take possession of their houses, and I will put an end to the pride of the strong ones, and their sanctuaries will be profaned.

[[v26-7-25]]

^<<v26-7-25,25>>^ When their anguish comes, they will seek peace, but there will be none.

[[v26-7-26]]

^<<v26-7-26,26>>^ There will come disaster upon disaster, and one report after another, and people will seek a vision from a prophet, but the law^&#42;1^ will perish from a priest and advice^&#42;2^ from the elders.

[NOTE]
====
. Or “instruction.”
. Or “counsel.”
====

[[v26-7-27]]

^<<v26-7-27,27>>^ The king will go into mourning, and the chieftain will be clothed with despair,^&#42;1^ and the hands of the people of the land will tremble in terror. I will treat them according to their ways, and I will judge them as they have judged. And they will have to know that I am Jehovah.’”

[NOTE]
====
. Or “desolation.”
====

'''

xref:026-ezekiel/026-ezekiel-006.adoc#v26-6-0[&#60; Capítulo Anterior] | <<v26-7-0,Topo>> | xref:026-ezekiel/026-ezekiel-008.adoc#v26-8-0[Próximo Capítulo &#62;]