include::./index.adoc[]

[[v26-21-0]]
=== Ezekiel, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-21-1]]

^<<v26-21-1,1>>^ The word of Jehovah again came to me, saying:

[[v26-21-2]]

^<<v26-21-2,2>>^ “Son of man, turn your face toward Jerusalem, and make a proclamation against the holy places, and prophesy against the land of Israel.

[[v26-21-3]]

^<<v26-21-3,3>>^ Say to the land of Israel, ‘This is what Jehovah says: “Here I am against you, and I will bring my sword out of its sheath and cut off from you both the righteous and the wicked.

[[v26-21-4]]

^<<v26-21-4,4>>^ Because I will cut off from you the righteous and the wicked, my sword will be drawn from its sheath against all flesh,^&#42;1^ from south to north.

[NOTE]
====
. Or “people.”
====

[[v26-21-5]]

^<<v26-21-5,5>>^ All people will have to know that I myself, Jehovah, have drawn my sword from its sheath. It will not go back again.”’

[[v26-21-6]]

^<<v26-21-6,6>>^ “And you, son of man, sigh while you^&#42;1^ tremble, yes, sigh bitterly before them.

[NOTE]
====
. Lit., “your hips.”
====

[[v26-21-7]]

^<<v26-21-7,7>>^ And if they say to you, ‘Why are you sighing?’ you will say, ‘Because of a report.’ For it will certainly come, and every heart will melt with fear and every hand will hang limp and every spirit will become dejected and every knee will drip with water.^&#42;1^ ‘Look! It will certainly come—it will take place,’ declares the Sovereign Lord Jehovah.”

[NOTE]
====
. That is, from urination as a result of fear.
====

[[v26-21-8]]

^<<v26-21-8,8>>^ The word of Jehovah again came to me, saying:

[[v26-21-9]]

^<<v26-21-9,9>>^ “Son of man, prophesy and say, ‘This is what Jehovah says: “Say, ‘A sword! A sword is sharpened, and it is polished.

[[v26-21-10]]

^<<v26-21-10,10>>^ It is sharpened to inflict a great slaughter; it is polished to flash like lightning.’”’”
“Should we not rejoice?”
“‘Will it^&#42;1^ reject the scepter of my own son, as it does every tree?

[NOTE]
====
. That is, Jehovah’s sword.
====

[[v26-21-11]]

^<<v26-21-11,11>>^ “‘It is given to be polished and to be wielded with the hand. This sword is sharpened and polished, to be put into the hand of an executioner.

[[v26-21-12]]

^<<v26-21-12,12>>^ “‘Cry out and wail, son of man, for it has come against my people; it is against all the chieftains of Israel. These will be victims of the sword along with my people. So strike your thigh in grief.

[[v26-21-13]]

^<<v26-21-13,13>>^ For an examination has been made, and what will happen if the sword rejects the scepter? It^&#42;1^ will cease to exist,’ declares the Sovereign Lord Jehovah.

[NOTE]
====
. Or “The scepter.”
====

[[v26-21-14]]

^<<v26-21-14,14>>^ “And you, son of man, prophesy and clap your hands and repeat ‘A sword!’ three times. It is the sword of the slain victims, the sword of great slaughter, that surrounds them.

[[v26-21-15]]

^<<v26-21-15,15>>^ Their hearts will melt with fear and many will fall at their city gates; I will inflict a slaughter by the sword. Yes, it flashes like lightning and is polished for a slaughter!

[[v26-21-16]]

^<<v26-21-16,16>>^ Cut sharply to the right! Swing to the left! Go wherever your blade is directed!

[[v26-21-17]]

^<<v26-21-17,17>>^ I will also clap my hands and satisfy my rage. I myself, Jehovah, have spoken.”

[[v26-21-18]]

^<<v26-21-18,18>>^ And the word of Jehovah again came to me, saying:

[[v26-21-19]]

^<<v26-21-19,19>>^ “As for you, son of man, mark out two ways for the sword of the king of Babylon to come. Both of them will originate from the same land, and a signpost^&#42;1^ should be set up where the road branches off to the two cities.

[NOTE]
====
. Lit., “hand.”
====

[[v26-21-20]]

^<<v26-21-20,20>>^ You should mark out one way for the sword to come against Rabʹbah of the Amʹmon·ites, and the other way against fortified Jerusalem in Judah.

[[v26-21-21]]

^<<v26-21-21,21>>^ For the king of Babylon stops to use divination at the fork in the road, where the two roads branch off. He shakes the arrows. He consults his idols;^&#42;1^ he examines the liver.

[NOTE]
====
. Lit., “the teraphim.”
====

[[v26-21-22]]

^<<v26-21-22,22>>^ The divination in his right hand is pointed toward Jerusalem, to set up battering rams, to give the word for slaughter, to sound the battle cry, to set battering rams against the gates, to throw up a siege rampart, to build a siege wall.

[[v26-21-23]]

^<<v26-21-23,23>>^ But it will seem like false divination in the eyes of those^&#42;1^ who had sworn oaths to them. But he remembers their guilt and will capture them.

[NOTE]
====
. That is, the inhabitants of Jerusalem.
====

[[v26-21-24]]

^<<v26-21-24,24>>^ “Therefore this is what the Sovereign Lord Jehovah says: ‘You have caused your own guilt to be remembered by exposing your transgressions and causing your sins to be seen in all your actions. Now that you have been remembered, you will be taken by force.’^&#42;1^

[NOTE]
====
. Lit., “by the hand.”
====

[[v26-21-25]]

^<<v26-21-25,25>>^ “But your day has come, O fatally wounded, wicked chieftain of Israel, the time of your final punishment.

[[v26-21-26]]

^<<v26-21-26,26>>^ This is what the Sovereign Lord Jehovah says: ‘Remove the turban, and take off the crown. This will not remain the same. Raise up the low one, and bring low the high one.

[[v26-21-27]]

^<<v26-21-27,27>>^ A ruin, a ruin, a ruin I will make it. And it will not belong to anyone until the one who has the legal right comes, and I will give it to him.’

[[v26-21-28]]

^<<v26-21-28,28>>^ “And you, son of man, prophesy and say, ‘This is what the Sovereign Lord Jehovah says about the Amʹmon·ites and about their insults.’ Say, ‘A sword! A sword is drawn for a slaughter; it is polished to devour and to flash like lightning.

[[v26-21-29]]

^<<v26-21-29,29>>^ Despite the false visions and lying divination about you, you will be piled up on the slain,^&#42;1^ the wicked men whose day has come, the time of their final punishment.

[NOTE]
====
. Lit., “the necks of the slain.”
====

[[v26-21-30]]

^<<v26-21-30,30>>^ Return it to its sheath. I will judge you in the place that you were created, in the land of your origin.

[[v26-21-31]]

^<<v26-21-31,31>>^ I will pour out my indignation on you. I will blow upon you with the fire of my fury, and I will hand you over to brutal men, the craftsmen of destruction.

[[v26-21-32]]

^<<v26-21-32,32>>^ You will become fuel for the fire; your own blood will be shed in the land, and you will be remembered no more, for I myself, Jehovah, have spoken.’”

'''

xref:026-ezekiel/026-ezekiel-020.adoc#v26-20-0[&#60; Capítulo Anterior] | <<v26-21-0,Topo>> | xref:026-ezekiel/026-ezekiel-022.adoc#v26-22-0[Próximo Capítulo &#62;]