include::./index.adoc[]

[[v26-38-0]]
=== Ezekiel, 38
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-38-1]]

^<<v26-38-1,1>>^ The word of Jehovah again came to me, saying:

[[v26-38-2]]

^<<v26-38-2,2>>^ “Son of man, set your face against Gog of the land of Maʹgog, the head chieftain^&#42;1^ of Meʹshech and Tuʹbal, and prophesy against him.

[NOTE]
====
. Or “chief prince.”
====

[[v26-38-3]]

^<<v26-38-3,3>>^ Say, ‘This is what the Sovereign Lord Jehovah says: “Here I am against you, O Gog, head chieftain^&#42;1^ of Meʹshech and Tuʹbal.

[NOTE]
====
. Or “chief prince.”
====

[[v26-38-4]]

^<<v26-38-4,4>>^ I will turn you around and put hooks in your jaws and bring you out with all your army, horses and horsemen, all of them clothed in splendor, a vast assembly with large shields and bucklers,^&#42;1^ all of them wielding swords;

[NOTE]
====
. A small shield, often carried by archers.
====

[[v26-38-5]]

^<<v26-38-5,5>>^ Persia, E·thi·oʹpi·a, and Put are with them, all of them with buckler and helmet;

[[v26-38-6]]

^<<v26-38-6,6>>^ Goʹmer and all its troops, the house of To·garʹmah from the remotest parts of the north, along with all its troops—many peoples are with you.

[[v26-38-7]]

^<<v26-38-7,7>>^ “‘“Be ready, prepare yourselves, you with all your armies that are assembled with you, and you will be their commander.^&#42;1^

[NOTE]
====
. Lit., “guard.”
====

[[v26-38-8]]

^<<v26-38-8,8>>^ “‘“You will be given attention^&#42;1^ after many days. In the final part of the years you will invade the land whose people have been restored from the ravages of the sword, collected together out of many peoples onto the mountains of Israel, which had long been lying devastated. The inhabitants of this land were restored from the peoples, and all of them dwell in security.

[NOTE]
====
. Or “summoned.”
====

[[v26-38-9]]

^<<v26-38-9,9>>^ You will come against them like a storm, and you will cover the land like clouds, you and all your troops and many peoples with you.”’

[[v26-38-10]]

^<<v26-38-10,10>>^ “This is what the Sovereign Lord Jehovah says: ‘In that day thoughts will come into your heart, and you will devise an evil plan.

[[v26-38-11]]

^<<v26-38-11,11>>^ You will say: “I will invade the land of unprotected settlements.^&#42;1^ I will come against those living in security, without disturbance, all of them living in settlements unprotected by walls, bars, or gates.”

[NOTE]
====
. Or “of open, rural country.”
====

[[v26-38-12]]

^<<v26-38-12,12>>^ It will be to take much spoil and plunder, to attack the devastated places that are now inhabited and a people regathered from the nations, who are accumulating wealth and property, those who are living in the center of the earth.

[[v26-38-13]]

^<<v26-38-13,13>>^ “‘Sheʹba and Deʹdan, the merchants of Tarʹshish and all its warriors^&#42;1^ will say to you: “Are you invading to get much spoil and plunder? Have you assembled your armies to carry off silver and gold, to take wealth and property, to seize a very great spoil?”’

[NOTE]
====
. Or “maned young lions.”
====

[[v26-38-14]]

^<<v26-38-14,14>>^ “So prophesy, son of man, and say to Gog, ‘This is what the Sovereign Lord Jehovah says: “On that day when my people Israel are dwelling in security, will you not know it?

[[v26-38-15]]

^<<v26-38-15,15>>^ You will come from your place, from the remotest parts of the north, you and many peoples with you, all of them riding on horses, a great assembly, a vast army.

[[v26-38-16]]

^<<v26-38-16,16>>^ Like clouds covering the land, you will come against my people Israel. In the final part of the days I will bring you against my land so that the nations may know me when I sanctify myself through you before their eyes, O Gog.”’

[[v26-38-17]]

^<<v26-38-17,17>>^ “This is what the Sovereign Lord Jehovah says: ‘Are you not the same one I spoke about in the former days through my servants the prophets of Israel, who prophesied for many years that you would be brought against them?’

[[v26-38-18]]

^<<v26-38-18,18>>^ “‘On that day, the day when Gog invades the land of Israel,’ declares the Sovereign Lord Jehovah, ‘my great rage will flare up.

[[v26-38-19]]

^<<v26-38-19,19>>^ In my zeal, in the fire of my fury, I will speak; and in that day there will be a great earthquake in the land of Israel.

[[v26-38-20]]

^<<v26-38-20,20>>^ Because of me the fish of the sea, the birds of the sky, the wild beasts of the field, all the reptiles that creep on the ground, and all humans on the surface of the earth will tremble, and the mountains will be thrown down, and the cliffs will fall, and every wall will collapse to the ground.’

[[v26-38-21]]

^<<v26-38-21,21>>^ “‘I will call for a sword against him on all my mountains,’ declares the Sovereign Lord Jehovah. ‘Every man’s sword will be against his own brother.

[[v26-38-22]]

^<<v26-38-22,22>>^ I will bring my judgment against him^&#42;1^ with pestilence and bloodshed; and I will rain down a torrential downpour and hailstones and fire and sulfur on him and on his troops and on the many peoples with him.

[NOTE]
====
. Or “I will bring myself into judgment with him.”
====

[[v26-38-23]]

^<<v26-38-23,23>>^ And I will certainly magnify myself and sanctify myself and make myself known before the eyes of many nations; and they will have to know that I am Jehovah.’

'''

xref:026-ezekiel/026-ezekiel-037.adoc#v26-37-0[&#60; Capítulo Anterior] | <<v26-38-0,Topo>> | xref:026-ezekiel/026-ezekiel-039.adoc#v26-39-0[Próximo Capítulo &#62;]