include::./index.adoc[]

[[v26-23-0]]
=== Ezekiel, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-23-1]]

^<<v26-23-1,1>>^ The word of Jehovah again came to me, saying:

[[v26-23-2]]

^<<v26-23-2,2>>^ “Son of man, there were two women who were the daughters of the same mother.

[[v26-23-3]]

^<<v26-23-3,3>>^ They became prostitutes in Egypt; from their youth they engaged in prostitution. Their breasts were squeezed there, and their virgin bosoms were fondled.

[[v26-23-4]]

^<<v26-23-4,4>>^ Their names were O·hoʹlah,^&#42;1^ the older one, and her sister O·hoʹli·bah.^&#42;2^ They became mine and gave birth to sons and daughters. As for their names, O·hoʹlah is Sa·marʹi·a, and O·hoʹli·bah is Jerusalem.

[NOTE]
====
. Meaning “Her Tent.”
. Meaning “My Tent Is in Her.”
====

[[v26-23-5]]

^<<v26-23-5,5>>^ “O·hoʹlah began to prostitute herself while she belonged to me. She lusted after her passionate lovers, her neighbors the As·syrʹi·ans.

[[v26-23-6]]

^<<v26-23-6,6>>^ They were governors clothed in blue and deputy rulers—all desirable young men mounted on their horses.

[[v26-23-7]]

^<<v26-23-7,7>>^ She continued to prostitute herself with all the choicest sons of As·syrʹi·a, and she defiled herself with the disgusting idols^&#42;1^ of those she lusted after.

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v26-23-8]]

^<<v26-23-8,8>>^ She did not abandon the prostitution she practiced in Egypt, for in her youth they had lain down with her, and they fondled her virgin bosom and poured out their lust^&#42;1^ on her.

[NOTE]
====
. Or “immoral intercourse.”
====

[[v26-23-9]]

^<<v26-23-9,9>>^ So I gave her into the hand of her passionate lovers, the sons of As·syrʹi·a, after whom she had lusted.

[[v26-23-10]]

^<<v26-23-10,10>>^ They exposed her nakedness and seized her sons and daughters, and they killed her with a sword. She became notorious among women, and they executed judgment against her.

[[v26-23-11]]

^<<v26-23-11,11>>^ “When her sister O·hoʹli·bah saw it, her lust became even more depraved, and her prostitution was worse than that of her sister.

[[v26-23-12]]

^<<v26-23-12,12>>^ She lusted after her neighbors the sons of As·syrʹi·a, the governors and deputy rulers who were clothed in splendor and mounted on horses—all desirable young men.

[[v26-23-13]]

^<<v26-23-13,13>>^ When she defiled herself, I saw that both of them had followed the same course.

[[v26-23-14]]

^<<v26-23-14,14>>^ But she kept adding to her acts of prostitution. She saw men carved on the wall, images of Chal·deʹans carved in vermilion,^&#42;1^

[NOTE]
====
. Or “red.”
====

[[v26-23-15]]

^<<v26-23-15,15>>^ wearing belts around their waist, with flowing turbans on their heads, having the appearance of warriors, all of them depicting Babylonians, born in the land of the Chal·deʹans.

[[v26-23-16]]

^<<v26-23-16,16>>^ She began to lust after them as soon as she saw them, and she sent messengers to them in Chal·deʹa.

[[v26-23-17]]

^<<v26-23-17,17>>^ So the sons of Babylon kept coming to her bed of lovemaking, and they defiled her with their lust.^&#42;1^ After she was defiled by them, she^&#42;2^ turned away from them in disgust.

[NOTE]
====
. Or “immoral intercourse.”
. Or “her soul.”
====

[[v26-23-18]]

^<<v26-23-18,18>>^ “When she went on brazenly engaging in prostitution and exposing her nakedness, I turned away from her in disgust, just as I^&#42;1^ had turned away from her sister in disgust.

[NOTE]
====
. Or “my soul.”
====

[[v26-23-19]]

^<<v26-23-19,19>>^ And she kept increasing her acts of prostitution, calling to mind the days of her youth when she prostituted herself in the land of Egypt.

[[v26-23-20]]

^<<v26-23-20,20>>^ She lusted after them like the concubines of men whose male members are like those of a donkey and whose genitals are like those of a horse.

[[v26-23-21]]

^<<v26-23-21,21>>^ You yearned for the obscene conduct of your youth in Egypt when they fondled your bosom, the breasts of your youth.

[[v26-23-22]]

^<<v26-23-22,22>>^ “Therefore, O·hoʹli·bah, this is what the Sovereign Lord Jehovah says: ‘Here I am stirring up your lovers whom you^&#42;1^ turned away from in disgust, and I will bring them against you from every direction,

[NOTE]
====
. Or “your soul.”
====

[[v26-23-23]]

^<<v26-23-23,23>>^ the sons of Babylon and all the Chal·deʹans, the men of Peʹkod and Shoʹa and Koʹa, along with all the sons of As·syrʹi·a. All of them are desirable young men, governors and deputy rulers, warriors and handpicked,^&#42;1^ all mounted on horses.

[NOTE]
====
. Lit., “summoned ones.”
====

[[v26-23-24]]

^<<v26-23-24,24>>^ They will attack you with rumbling war chariots and wheels and with a great assembly of troops, with large shield and buckler^&#42;1^ and helmet. They will take up positions all around you, and I will authorize them to pass judgment, and they will judge you as they see fit.

[NOTE]
====
. A small shield, often carried by archers.
====

[[v26-23-25]]

^<<v26-23-25,25>>^ I will express my indignation against you, and they will deal with you in their rage. They will cut off your nose and your ears, and those of you who remain will fall by the sword. They will take away your sons and your daughters, and those of you who remain will be consumed by fire.

[[v26-23-26]]

^<<v26-23-26,26>>^ They will strip off your garments and seize your beautiful jewelry.^&#42;1^

[NOTE]
====
. Or “ornaments.”
====

[[v26-23-27]]

^<<v26-23-27,27>>^ I will put an end to your obscene conduct and your prostitution, which started in the land of Egypt. You will stop looking at them, and you will remember Egypt no more.’

[[v26-23-28]]

^<<v26-23-28,28>>^ “For this is what the Sovereign Lord Jehovah says: ‘Here I am about to hand you over to those you hate, those you^&#42;1^ turned away from in disgust.

[NOTE]
====
. Or “your soul.”
====

[[v26-23-29]]

^<<v26-23-29,29>>^ They will deal with you in hatred and take away all you have toiled for and leave you naked and exposed. The shameful nakedness of your immorality and your obscene conduct and your prostitution will be exposed.

[[v26-23-30]]

^<<v26-23-30,30>>^ These things will be done to you because you chased after the nations like a prostitute, because you defiled yourself with their disgusting idols.

[[v26-23-31]]

^<<v26-23-31,31>>^ You have followed the same course as your sister, and I will put her cup into your hand.’

[[v26-23-32]]

^<<v26-23-32,32>>^ “This is what the Sovereign Lord Jehovah says:
‘You will drink the deep and wide cup of your sister,
And you will become an object of laughter and ridicule, of which the cup contains much.

[[v26-23-33]]

^<<v26-23-33,33>>^ You will be overcome by^&#42;1^ drunkenness and grief,
A cup of horror and desolation,
The cup of your sister, Sa·marʹi·a.

[NOTE]
====
. Lit., “filled with.”
====

[[v26-23-34]]

^<<v26-23-34,34>>^ You will have to drink it and drain it dry and gnaw on its earthenware fragments
And then tear out your breasts.
“For I myself have spoken,” declares the Sovereign Lord Jehovah.’

[[v26-23-35]]

^<<v26-23-35,35>>^ “Therefore this is what the Sovereign Lord Jehovah says: ‘Because you have forgotten me and have completely disregarded me,^&#42;1^ you will bear the consequences of your obscene conduct and your acts of prostitution.’”

[NOTE]
====
. Lit., “have cast me behind your back.”
====

[[v26-23-36]]

^<<v26-23-36,36>>^ Jehovah then said to me: “Son of man, will you pronounce judgment on O·hoʹlah and O·hoʹli·bah and confront them with their disgusting practices?

[[v26-23-37]]

^<<v26-23-37,37>>^ They have committed adultery,^&#42;1^ and there is blood on their hands. Not only have they committed adultery with their disgusting idols, but they have also made their sons whom they bore to me pass through the fire as food for their idols.

[NOTE]
====
. That is, spiritual adultery.
====

[[v26-23-38]]

^<<v26-23-38,38>>^ Moreover, this is what they have done to me: They defiled my sanctuary on that day, and they profaned my sabbaths.

[[v26-23-39]]

^<<v26-23-39,39>>^ After they slaughtered their sons as sacrifices to their disgusting idols, they came into my sanctuary to profane it on that very day. That is what they did inside my own house.

[[v26-23-40]]

^<<v26-23-40,40>>^ They even sent a messenger for men to come from far away. When they were coming, you washed yourself and painted your eyes and adorned yourself with ornaments.

[[v26-23-41]]

^<<v26-23-41,41>>^ And you sat down on a magnificent couch with a table set in front of it, on which you put my incense and my oil.

[[v26-23-42]]

^<<v26-23-42,42>>^ The sound of a carefree crowd of men was heard there, among whom were drunkards brought in from the wilderness. They put bracelets on the hands of the women and beautiful crowns on their heads.

[[v26-23-43]]

^<<v26-23-43,43>>^ “Then I said regarding her who was worn out with adultery: ‘Now she will keep committing her prostitution.’

[[v26-23-44]]

^<<v26-23-44,44>>^ So they kept going in to her, just as one goes to a prostitute. That is how they went in to O·hoʹlah and to O·hoʹli·bah, the women of obscene conduct.

[[v26-23-45]]

^<<v26-23-45,45>>^ But righteous men will render to her the appropriate judgment for adultery and bloodshed; for adulteresses is what they are, and they have blood on their hands.

[[v26-23-46]]

^<<v26-23-46,46>>^ “For this is what the Sovereign Lord Jehovah says: ‘An army will be brought against them to make them an object of horror and something to plunder.

[[v26-23-47]]

^<<v26-23-47,47>>^ The army will hurl stones at them and cut them down with their swords. They will kill their sons and daughters and burn their houses with fire.

[[v26-23-48]]

^<<v26-23-48,48>>^ I will put an end to the obscene conduct in the land, and all the women will learn a lesson and not copy your obscene conduct.

[[v26-23-49]]

^<<v26-23-49,49>>^ They will bring on you the consequences of your obscene conduct and of your sins with your disgusting idols; and you will have to know that I am the Sovereign Lord Jehovah.’”

'''

xref:026-ezekiel/026-ezekiel-022.adoc#v26-22-0[&#60; Capítulo Anterior] | <<v26-23-0,Topo>> | xref:026-ezekiel/026-ezekiel-024.adoc#v26-24-0[Próximo Capítulo &#62;]