include::./index.adoc[]

[[v26-10-0]]
=== Ezekiel, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-10-1]]

^<<v26-10-1,1>>^ As I was watching, I saw above the expanse that was over the heads of the cherubs something like a sapphire stone appearing above them, and its appearance resembled a throne.

[[v26-10-2]]

^<<v26-10-2,2>>^ Then he said to the man clothed in linen: “Enter between the wheelwork, under the cherubs, and fill both your hands with burning coals from between the cherubs and toss them over the city.” So he entered as I watched.

[[v26-10-3]]

^<<v26-10-3,3>>^ The cherubs were standing to the right of the house when the man entered, and the cloud filled the inner courtyard.

[[v26-10-4]]

^<<v26-10-4,4>>^ And the glory of Jehovah rose up from the cherubs to the threshold of the doorway of the house, and the house gradually became filled with the cloud, and the courtyard was full of the brightness of the glory of Jehovah.

[[v26-10-5]]

^<<v26-10-5,5>>^ And the sound of the wings of the cherubs could be heard in the outer courtyard, like the sound of God Almighty when he speaks.

[[v26-10-6]]

^<<v26-10-6,6>>^ Then he commanded the man clothed in linen: “Take fire from between the wheelwork, from between the cherubs,” and he entered and stood beside the wheel.

[[v26-10-7]]

^<<v26-10-7,7>>^ Then one of the cherubs stretched his hand out toward the fire that was between the cherubs. He took some and put it into both hands of the one clothed in linen, who now took it and went out.

[[v26-10-8]]

^<<v26-10-8,8>>^ The cherubs had what looked like the form of human hands under their wings.

[[v26-10-9]]

^<<v26-10-9,9>>^ As I was watching, I saw four wheels beside the cherubs, one wheel beside each cherub, and the wheels appeared to glow like chrysʹo·lite stone.

[[v26-10-10]]

^<<v26-10-10,10>>^ As for their appearance, the four of them were alike, looking as though a wheel were within a wheel.

[[v26-10-11]]

^<<v26-10-11,11>>^ When they moved, they could go in any of the four directions without turning, because they would go to the place where the head would face without turning.

[[v26-10-12]]

^<<v26-10-12,12>>^ Their entire bodies, their backs, their hands, their wings, and the wheels, the wheels of all four of them, were full of eyes all around.

[[v26-10-13]]

^<<v26-10-13,13>>^ As regards the wheels, I heard a voice that called to them, “Wheelwork!”

[[v26-10-14]]

^<<v26-10-14,14>>^ Each one^&#42;1^ had four faces. The first face was the face of the cherub, the second face was the face of a man,^&#42;2^ the third was the face of a lion, and the fourth was the face of an eagle.

[NOTE]
====
. That is, each of the cherubs.
. Or “human.”
====

[[v26-10-15]]

^<<v26-10-15,15>>^ And the cherubs would rise—they were the same living creatures^&#42;1^ that I had seen at the river Cheʹbar—

[NOTE]
====
. Lit., “it was the living creature.”
====

[[v26-10-16]]

^<<v26-10-16,16>>^ and when the cherubs moved, the wheels would move alongside them; and when the cherubs lifted up their wings to be high above the earth, the wheels would not turn or move from their side.

[[v26-10-17]]

^<<v26-10-17,17>>^ When these stood still, they would stand still; and when these rose, they would rise with them, for the spirit operating on the living creatures^&#42;1^ was in them.

[NOTE]
====
. Lit., “the spirit of the living creature.”
====

[[v26-10-18]]

^<<v26-10-18,18>>^ Then the glory of Jehovah departed from over the threshold of the doorway of the house and stood still over the cherubs.

[[v26-10-19]]

^<<v26-10-19,19>>^ The cherubs now lifted up their wings and rose from the earth as I watched. The wheels were also alongside them when they departed. They stopped at the entrance of the eastern gate of the house of Jehovah, and the glory of the God of Israel was above them.

[[v26-10-20]]

^<<v26-10-20,20>>^ These were the living creatures^&#42;1^ that I had seen under the God of Israel at the river Cheʹbar, so I came to know that they were cherubs.

[NOTE]
====
. Lit., “This is the living creature.”
====

[[v26-10-21]]

^<<v26-10-21,21>>^ All four had four faces, four wings, and what appeared to be human hands under their wings.

[[v26-10-22]]

^<<v26-10-22,22>>^ And the appearances of their faces were like the faces I had seen by the river Cheʹbar. They would each go straight forward.

'''

xref:026-ezekiel/026-ezekiel-009.adoc#v26-9-0[&#60; Capítulo Anterior] | <<v26-10-0,Topo>> | xref:026-ezekiel/026-ezekiel-011.adoc#v26-11-0[Próximo Capítulo &#62;]