include::./index.adoc[]

[[v26-11-0]]
=== Ezekiel, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-11-1]]

^<<v26-11-1,1>>^ And a spirit lifted me up and brought me to the eastern gate of the house of Jehovah, the gate that faces east. There at the entrance of the gate I saw 25 men, and among them were Ja·az·a·niʹah the son of Azʹzur and Pel·a·tiʹah the son of Be·naiʹah, princes of the people.

[[v26-11-2]]

^<<v26-11-2,2>>^ Then He said to me: “Son of man, these are the men who are scheming evil and giving wicked advice in^&#42;1^ this city.

[NOTE]
====
. Or “against.”
====

[[v26-11-3]]

^<<v26-11-3,3>>^ They are saying, ‘Is it not the time for building houses? The city^&#42;1^ is the cooking pot,^&#42;2^ and we are the flesh.’

[NOTE]
====
. Lit., “She,” the city of Jerusalem, where the Jews thought they would be protected.
. Or “wide-mouthed cooking pot.”
====

[[v26-11-4]]

^<<v26-11-4,4>>^ “So prophesy against them. Prophesy, son of man.”

[[v26-11-5]]

^<<v26-11-5,5>>^ Then the spirit of Jehovah came upon me, and he said to me: “Say, ‘This is what Jehovah says: “What you have said is correct, O house of Israel, and I know what you are thinking.^&#42;1^

[NOTE]
====
. Or “the things that come up in your spirit.”
====

[[v26-11-6]]

^<<v26-11-6,6>>^ You have caused many to die in this city, and you have filled her streets with the dead.”’”

[[v26-11-7]]

^<<v26-11-7,7>>^ “Therefore this is what the Sovereign Lord Jehovah says: ‘The dead bodies that you have strewn about the city are the flesh, and the city is the cooking pot. But you yourselves will be taken out of it.’”

[[v26-11-8]]

^<<v26-11-8,8>>^ “‘A sword you have feared, and a sword I will bring against you,’ declares the Sovereign Lord Jehovah.

[[v26-11-9]]

^<<v26-11-9,9>>^ ‘I will bring you out of her and give you into the hand of foreigners and execute judgment on you.

[[v26-11-10]]

^<<v26-11-10,10>>^ You will fall by the sword. I will judge you at the border of Israel, and you will have to know that I am Jehovah.

[[v26-11-11]]

^<<v26-11-11,11>>^ The city will not be a cooking pot for you, and you will not be the flesh within it; I will judge you at the border of Israel,

[[v26-11-12]]

^<<v26-11-12,12>>^ and you will have to know that I am Jehovah. For you did not walk in my regulations and carry out my judgments, but you have acted in harmony with the judgments of the nations around you.’”

[[v26-11-13]]

^<<v26-11-13,13>>^ As soon as I prophesied, Pel·a·tiʹah the son of Be·naiʹah died, and I fell facedown and cried with a loud voice: “Alas, O Sovereign Lord Jehovah! Are you going to exterminate the remaining ones of Israel?”

[[v26-11-14]]

^<<v26-11-14,14>>^ The word of Jehovah again came to me, saying:

[[v26-11-15]]

^<<v26-11-15,15>>^ “Son of man, your brothers, those of your brothers with the right of repurchase, along with the entire house of Israel, have been told by the inhabitants of Jerusalem, ‘Keep far away from Jehovah. The land is ours; it has been given to us as a possession.’

[[v26-11-16]]

^<<v26-11-16,16>>^ Therefore say, ‘This is what the Sovereign Lord Jehovah says: “Although I have removed them far away among the nations and I have scattered them among the lands, for a little while I will become a sanctuary for them in the lands to which they have gone.”’

[[v26-11-17]]

^<<v26-11-17,17>>^ “Therefore say, ‘This is what the Sovereign Lord Jehovah says: “I will also collect you from the peoples and gather you from the lands to which you have been scattered, and I will give you the land of Israel.

[[v26-11-18]]

^<<v26-11-18,18>>^ And they will return there and remove from it all its disgusting things and detestable practices.

[[v26-11-19]]

^<<v26-11-19,19>>^ And I will give them a unified heart,^&#42;1^ and I will put a new spirit in them; and I will remove the heart of stone from their bodies and give them a heart of flesh,^&#42;2^

[NOTE]
====
. Lit., “one heart.”
. That is, one sensitive to God’s guidance.
====

[[v26-11-20]]

^<<v26-11-20,20>>^ in order that they may walk in my statutes and observe my judgments and obey them. Then they will be my people, and I will be their God.”’

[[v26-11-21]]

^<<v26-11-21,21>>^ “‘“But as for those whose hearts are set to continue in their disgusting things and their detestable practices, I will bring the consequences of their way upon their head,” declares the Sovereign Lord Jehovah.’”

[[v26-11-22]]

^<<v26-11-22,22>>^ The cherubs now lifted up their wings, and the wheels were close to them, and the glory of the God of Israel was above them.

[[v26-11-23]]

^<<v26-11-23,23>>^ Then the glory of Jehovah ascended from the city and stopped over the mountain to the east of the city.

[[v26-11-24]]

^<<v26-11-24,24>>^ A spirit then lifted me up—through a vision by the spirit of God—and brought me to the exiled people in Chal·deʹa. Then the vision that I had seen left me.

[[v26-11-25]]

^<<v26-11-25,25>>^ And I began to tell the exiled people all the things that Jehovah had shown me.

'''

xref:026-ezekiel/026-ezekiel-010.adoc#v26-10-0[&#60; Capítulo Anterior] | <<v26-11-0,Topo>> | xref:026-ezekiel/026-ezekiel-012.adoc#v26-12-0[Próximo Capítulo &#62;]