include::./index.adoc[]

[[v26-5-0]]
=== Ezekiel, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-5-1]]

^<<v26-5-1,1>>^ “As for you, son of man, take a sharp sword for yourself to use as a barber’s razor. Shave your head and your beard, and then take scales to weigh and divide the hair into portions.

[[v26-5-2]]

^<<v26-5-2,2>>^ You will burn a third of it in the fire inside the city when the days of the siege are completed. Then you will take another third and strike it with the sword all around the city,^&#42;1^ and the last third you will scatter to the wind, and I will draw a sword to chase after them.

[NOTE]
====
. Lit., “her.”
====

[[v26-5-3]]

^<<v26-5-3,3>>^ “You must also take a few strands of them and wrap them up in the folds^&#42;1^ of your garment.

[NOTE]
====
. Or “skirts.”
====

[[v26-5-4]]

^<<v26-5-4,4>>^ And take some more of them and throw them into the fire and incinerate them. From this a fire will spread to all the house of Israel.

[[v26-5-5]]

^<<v26-5-5,5>>^ “This is what the Sovereign Lord Jehovah says: ‘This is Jerusalem. I have set her in the middle of the nations, with lands all around her.

[[v26-5-6]]

^<<v26-5-6,6>>^ But she has rebelled against my judicial decisions and my statutes, acting more wickedly than the nations and the lands all around her. For they have rejected my judicial decisions, and they did not walk in my statutes.’

[[v26-5-7]]

^<<v26-5-7,7>>^ “Therefore this is what the Sovereign Lord Jehovah says: ‘Because you were more troublesome than the nations all around you and you did not walk in my statutes or carry out my judicial decisions but, instead, you followed the judicial decisions of the nations all around you,

[[v26-5-8]]

^<<v26-5-8,8>>^ this is what the Sovereign Lord Jehovah says: “Here I am against you, O city, and I myself will execute judgment in your midst before the eyes of the nations.

[[v26-5-9]]

^<<v26-5-9,9>>^ I will do in you what I have never done before, and the likes of which I will not do again, because of all your detestable practices.

[[v26-5-10]]

^<<v26-5-10,10>>^ “‘“So fathers among you will eat their sons, and sons will eat their fathers, and I will execute judgment among you and scatter all the rest of you in every direction.”’^&#42;1^

[NOTE]
====
. Lit., “to every wind.”
====

[[v26-5-11]]

^<<v26-5-11,11>>^ “‘Therefore as surely as I am alive,’ declares the Sovereign Lord Jehovah, ‘because it was my sanctuary that you defiled with all your disgusting idols and with all your detestable practices, I will also reject^&#42;1^ you; my eye will not feel sorry, and I will show no compassion.

[NOTE]
====
. Or “diminish.”
====

[[v26-5-12]]

^<<v26-5-12,12>>^ A third of you will die by the pestilence^&#42;1^ or perish in your midst by famine. Another third will fall all around you by the sword. And I will scatter the last third in every direction,^&#42;2^ and I will draw a sword to chase after them.

[NOTE]
====
. Or “disease.”
. Lit., “to every wind.”
====

[[v26-5-13]]

^<<v26-5-13,13>>^ Then my anger will come to an end, and my wrath against them will subside, and I will be satisfied. And they will have to know that I, Jehovah, have spoken in my insistence on exclusive devotion, when I have finished unleashing my wrath against them.

[[v26-5-14]]

^<<v26-5-14,14>>^ “‘I will make you a devastated place and an object of reproach among the surrounding nations and in the eyes of everyone passing by.

[[v26-5-15]]

^<<v26-5-15,15>>^ You will become an object of reproach and scorn, a warning example and a horror to the nations around you, when I execute judgment on you in anger and in wrath and with furious punishments. I, Jehovah, have spoken.

[[v26-5-16]]

^<<v26-5-16,16>>^ “‘I will send against them the deadly arrows of famine to destroy them. The arrows that I send will bring you to ruin. I will make the famine worse for you by cutting off your food supply.^&#42;1^

[NOTE]
====
. Lit., “breaking your bread rods.” Possibly referring to rods used for storing bread.
====

[[v26-5-17]]

^<<v26-5-17,17>>^ I will send against you famine and vicious wild beasts, and they will bereave you of children. Pestilence and bloodshed will overwhelm you, and I will bring a sword against you. I, Jehovah, have spoken.’”

'''

xref:026-ezekiel/026-ezekiel-004.adoc#v26-4-0[&#60; Capítulo Anterior] | <<v26-5-0,Topo>> | xref:026-ezekiel/026-ezekiel-006.adoc#v26-6-0[Próximo Capítulo &#62;]