include::./index.adoc[]

[[v26-8-0]]
=== Ezekiel, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-8-1]]

^<<v26-8-1,1>>^ And in the sixth year, in the sixth month, on the fifth day of the month, when I was sitting in my house and the elders of Judah were sitting before me, the hand of the Sovereign Lord Jehovah took hold of me there.

[[v26-8-2]]

^<<v26-8-2,2>>^ As I watched, I saw a form similar to the appearance of fire; there was fire below what appeared to be his waist, and from his waist upward his appearance was bright, like the glow of electrum.^&#42;1^

[NOTE]
====
. A shining alloy of gold and silver.
====

[[v26-8-3]]

^<<v26-8-3,3>>^ Then he stretched out what appeared to be a hand and took me by a tuft of hair of my head, and a spirit carried me between the earth and the heavens and brought me to Jerusalem by means of the visions from God, to the entrance of the inner gate that faces north, where the idolatrous symbol^&#42;1^ of jealousy that incites jealousy stood.

[NOTE]
====
. Or “image.”
====

[[v26-8-4]]

^<<v26-8-4,4>>^ And look! the glory of the God of Israel was there, like the appearance that I had seen in the valley plain.

[[v26-8-5]]

^<<v26-8-5,5>>^ He then said to me: “Son of man, please raise your eyes toward the north.” So I raised my eyes toward the north, and there, north of the gate of the altar, was this symbol^&#42;1^ of jealousy in the entryway.

[NOTE]
====
. Or “image.”
====

[[v26-8-6]]

^<<v26-8-6,6>>^ And he said to me: “Son of man, do you see what terrible, detestable things the house of Israel is doing here, things that make me go far away from my sanctuary? But you will see detestable things that are even more terrible.”

[[v26-8-7]]

^<<v26-8-7,7>>^ Then he brought me to the entrance of the courtyard, and when I looked, I saw a hole in the wall.

[[v26-8-8]]

^<<v26-8-8,8>>^ He said to me: “Son of man, please bore through the wall.” So I bored through the wall, and I saw an entryway.

[[v26-8-9]]

^<<v26-8-9,9>>^ He said to me: “Go in and see the evil, detestable things that they are doing here.”

[[v26-8-10]]

^<<v26-8-10,10>>^ So I went in and looked, and I saw all sorts of images of creeping things and loathsome beasts and all the disgusting idols^&#42;1^ of the house of Israel; they were carved on the wall all around.

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v26-8-11]]

^<<v26-8-11,11>>^ And 70 of the elders of the house of Israel were standing before them, with Ja·az·a·niʹah the son of Shaʹphan standing among them. Each one had his censer in his hand, and the perfumed cloud of incense was ascending.

[[v26-8-12]]

^<<v26-8-12,12>>^ He said to me: “Son of man, do you see what the elders of the house of Israel are doing in the darkness, each one in the inner rooms where his idols are displayed?^&#42;1^ For they are saying, ‘Jehovah is not seeing us. Jehovah has left the land.’”

[NOTE]
====
. Or “in the inner rooms of his showpiece?”
====

[[v26-8-13]]

^<<v26-8-13,13>>^ And he went on to say to me: “You will see detestable things that are even more terrible that they are doing.”

[[v26-8-14]]

^<<v26-8-14,14>>^ So he brought me to the entrance of the north gate of the house of Jehovah, and there I saw women sitting and weeping over the god Tamʹmuz.

[[v26-8-15]]

^<<v26-8-15,15>>^ And he further said to me: “Do you see this, O son of man? You will see detestable things that are even more terrible than these.”

[[v26-8-16]]

^<<v26-8-16,16>>^ So he brought me to the inner courtyard of the house of Jehovah. There at the entrance of the temple of Jehovah, between the porch and the altar, were about 25 men with their backs to the temple of Jehovah and their faces to the east; they were bowing down to the sun in the east.

[[v26-8-17]]

^<<v26-8-17,17>>^ He said to me: “Son of man, do you see this? Is it a trivial thing for the house of Judah to do these detestable things, to fill the land with violence and keep offending me? Here they are thrusting out the branch^&#42;1^ to my nose.

[NOTE]
====
. Apparently a branch used in idolatrous worship.
====

[[v26-8-18]]

^<<v26-8-18,18>>^ So I will act in rage. My eye will not feel sorry; nor will I feel compassion. Even though they cry out loudly in my ears, I will not hear them.”

'''

xref:026-ezekiel/026-ezekiel-007.adoc#v26-7-0[&#60; Capítulo Anterior] | <<v26-8-0,Topo>> | xref:026-ezekiel/026-ezekiel-009.adoc#v26-9-0[Próximo Capítulo &#62;]