include::./index.adoc[]

[[v26-41-0]]
=== Ezekiel, 41
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-41-1]]

^<<v26-41-1,1>>^ Then he brought me into the outer sanctuary,^&#42;1^ and he measured the side pillars; they were six cubits^&#42;2^ wide on one side and six cubits wide on the other side.

[NOTE]
====
. Lit., “the temple.” In chapters 41 and 42, this expression refers to the outer sanctuary (Holy) or to the entire sanctuary (the temple including the Holy and the Most Holy).
. This refers to long cubits. See App. B14.
====

[[v26-41-2]]

^<<v26-41-2,2>>^ The entrance was ten cubits wide, and the sidewalls^&#42;1^ of the entrance were five cubits on one side and five cubits on the other side. He measured its length, which was 40 cubits, and its width, 20 cubits.

[NOTE]
====
. Lit., “sides.”
====

[[v26-41-3]]

^<<v26-41-3,3>>^ He then went inside^&#42;1^ and measured the side pillar of the entrance, and it was two cubits thick, and the entrance was six cubits wide. The sidewalls of the entrance were^&#42;2^ seven cubits.

[NOTE]
====
. That is, into the inner sanctuary, or Most Holy.
. Lit., “The width of the entrance was.”
====

[[v26-41-4]]

^<<v26-41-4,4>>^ Next he measured the room facing the outer sanctuary, and it was 20 cubits long and 20 cubits wide. And he said to me: “This is the Most Holy.”

[[v26-41-5]]

^<<v26-41-5,5>>^ Then he measured the wall of the temple, and it was six cubits thick. The side chambers around the temple were four cubits wide.

[[v26-41-6]]

^<<v26-41-6,6>>^ The side chambers were three stories high, one on top of the other, with 30 chambers on each story. There were ledges around the wall of the temple that served as supports for the side chambers, so that the supports did not go into the wall of the temple itself.

[[v26-41-7]]

^<<v26-41-7,7>>^ On both sides of the temple was a winding passage^&#42;1^ that widened as it ascended to the upper chambers. The width increased from story to story as one ascended from the lowest story to the uppermost story by passing through the middle story.

[NOTE]
====
. Apparently referring to circular staircases.
====

[[v26-41-8]]

^<<v26-41-8,8>>^ I saw that there was a raised platform all around the temple, and the foundations of the side chambers measured a full reed of six cubits to the corner.

[[v26-41-9]]

^<<v26-41-9,9>>^ The width of the outside wall of the side chambers was five cubits. There was an open space^&#42;1^ alongside the structure of the side chambers that was part of the temple.

[NOTE]
====
. Apparently a narrow walkway around the temple.
====

[[v26-41-10]]

^<<v26-41-10,10>>^ Between the temple and the dining rooms^&#42;1^ was an area that was 20 cubits wide on each side.

[NOTE]
====
. Or “the chambers.”
====

[[v26-41-11]]

^<<v26-41-11,11>>^ There was an entrance between the side chambers and the open space on the north side and another entrance on the south side. The width of the open space was five cubits all around.

[[v26-41-12]]

^<<v26-41-12,12>>^ The building that was on the west facing the open area was 70 cubits wide and 90 cubits long; the wall of the building was five cubits thick all around.

[[v26-41-13]]

^<<v26-41-13,13>>^ He measured the temple, and it was 100 cubits long. The open area, the building,^&#42;1^ and its walls were also 100 cubits long.

[NOTE]
====
. That is, the building west of the sanctuary.
====

[[v26-41-14]]

^<<v26-41-14,14>>^ The width of the front of the temple facing east and the open area was 100 cubits.

[[v26-41-15]]

^<<v26-41-15,15>>^ He measured the length of the building that faced the open area in the rear, along with its galleries on both sides, and it was 100 cubits.
He also measured the outer sanctuary, the inner sanctuary, and the porches of the courtyard,

[[v26-41-16]]

^<<v26-41-16,16>>^ as well as the thresholds, the windows with narrowing frames, and the galleries that were in those three areas. Near the threshold were wood panels from the floor up to the windows; and the windows were covered.

[[v26-41-17]]

^<<v26-41-17,17>>^ Measurements were taken above the entrance and in the inner temple and on the outside and on the entire wall all around.

[[v26-41-18]]

^<<v26-41-18,18>>^ It had carved cherubs and palm-tree figures, with each palm tree between two cherubs, and each cherub had two faces.

[[v26-41-19]]

^<<v26-41-19,19>>^ The human face was toward the palm tree on one side, and the face of a lion^&#42;1^ was toward the palm tree on the other side. They were carved this way throughout the entire temple.

[NOTE]
====
. Or “maned young lion.”
====

[[v26-41-20]]

^<<v26-41-20,20>>^ From the floor to the area above the entrance were carved cherubs and palm-tree figures on the wall of the sanctuary.

[[v26-41-21]]

^<<v26-41-21,21>>^ The doorposts^&#42;1^ of the sanctuary were square. In front of the holy place^&#42;2^ was something like

[NOTE]
====
. Lit., “The doorpost.” This apparently refers to the entrance into the Holy.
. Apparently referring to the Most Holy.
====

[[v26-41-22]]

^<<v26-41-22,22>>^ a wooden altar that was three cubits high and two cubits long. It had corner posts, and its base^&#42;1^ and its sides were made of wood. He then said to me: “This is the table that is before Jehovah.”

[NOTE]
====
. Lit., “length.”
====

[[v26-41-23]]

^<<v26-41-23,23>>^ The outer sanctuary and the holy place each had two doors.

[[v26-41-24]]

^<<v26-41-24,24>>^ The doors had two swinging leaves, two leaves for each door.

[[v26-41-25]]

^<<v26-41-25,25>>^ There were carved cherubs and palm-tree figures on the doors of the sanctuary, like those on the walls. There was also a wooden overhang^&#42;1^ on the front of the porch on the outside.

[NOTE]
====
. Or “canopy.”
====

[[v26-41-26]]

^<<v26-41-26,26>>^ There were also windows with narrowing frames and palm-tree figures along both sides of the porch, as well as along the side chambers of the temple and the overhangs.

'''

xref:026-ezekiel/026-ezekiel-040.adoc#v26-40-0[&#60; Capítulo Anterior] | <<v26-41-0,Topo>> | xref:026-ezekiel/026-ezekiel-042.adoc#v26-42-0[Próximo Capítulo &#62;]