include::./index.adoc[]

[[v26-29-0]]
=== Ezekiel, 29
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-29-1]]

^<<v26-29-1,1>>^ In the tenth year, in the tenth month, on the 12th day of the month, the word of Jehovah came to me, saying:

[[v26-29-2]]

^<<v26-29-2,2>>^ “Son of man, turn your face toward Pharʹaoh king of Egypt, and prophesy against him and against all Egypt.

[[v26-29-3]]

^<<v26-29-3,3>>^ Speak these words: ‘This is what the Sovereign Lord Jehovah says:
“Here I am against you, Pharʹaoh king of Egypt,
The great sea monster lying among the streams of his Nile,^&#42;1^
Who has said, ‘My Nile River belongs to me.
I made it for myself.’

[NOTE]
====
. Here and below, “Nile” refers to the river and its irrigation canals.
====

[[v26-29-4]]

^<<v26-29-4,4>>^ But I will put hooks in your jaws and cause the fish of your Nile to cling to your scales.
I will bring you up out of your Nile along with all the fish of the Nile that cling to your scales.

[[v26-29-5]]

^<<v26-29-5,5>>^ I will abandon you in the desert, you and all the fish of your Nile.
You will fall on the open field, and you will not be gathered up nor be collected together.
I will give you as food to the wild beasts of the earth and the birds of the sky.

[[v26-29-6]]

^<<v26-29-6,6>>^ Then all the inhabitants of Egypt will have to know that I am Jehovah,
For they were no more support to the house of Israel than a piece of straw.^&#42;1^

[NOTE]
====
. Lit., “a reed.”
====

[[v26-29-7]]

^<<v26-29-7,7>>^ When they grasped your hand, you were crushed,
And you caused them to tear their shoulder.
When they supported themselves on you, you were broken,
And you caused their legs^&#42;1^ to wobble.”

[NOTE]
====
. Lit., “hips.”
====

[[v26-29-8]]

^<<v26-29-8,8>>^ “‘Therefore this is what the Sovereign Lord Jehovah says: “Here I am bringing a sword upon you, and I will cut off from you both man and beast.

[[v26-29-9]]

^<<v26-29-9,9>>^ The land of Egypt will become a desolate and devastated place; and they will have to know that I am Jehovah, for you have^&#42;1^ said, ‘The Nile River belongs to me; I am the one who made it.’

[NOTE]
====
. Lit., “he has.”
====

[[v26-29-10]]

^<<v26-29-10,10>>^ So I am against you and against your Nile, and I will make the land of Egypt devastated and dry, a desolate wasteland, from Migʹdol to Sy·eʹne to the boundary of E·thi·oʹpi·a.

[[v26-29-11]]

^<<v26-29-11,11>>^ Neither man nor livestock will pass through it on foot, and it will not be inhabited for 40 years.

[[v26-29-12]]

^<<v26-29-12,12>>^ I will make the land of Egypt the most desolate of lands, and its cities will be the most desolate of cities for 40 years; and I will scatter the Egyptians among the nations and disperse them among the lands.”

[[v26-29-13]]

^<<v26-29-13,13>>^ “‘For this is what the Sovereign Lord Jehovah says: “After 40 years I will gather back the Egyptians from the peoples where they were scattered;

[[v26-29-14]]

^<<v26-29-14,14>>^ I will bring the Egyptian captives back to the land of Pathʹros, to the land of their origin, and there they will become an insignificant kingdom.

[[v26-29-15]]

^<<v26-29-15,15>>^ Egypt will become lower than the other kingdoms and will no longer dominate the other nations, and I will make them so small that they will not be able to subdue other nations.

[[v26-29-16]]

^<<v26-29-16,16>>^ It will never again be a source of confidence for the house of Israel, but it will only remind them of their error in turning to the Egyptians for help. And they will have to know that I am the Sovereign Lord Jehovah.”’”

[[v26-29-17]]

^<<v26-29-17,17>>^ Now in the 27th year, in the first month, on the first day of the month, the word of Jehovah came to me, saying:

[[v26-29-18]]

^<<v26-29-18,18>>^ “Son of man, King Neb·u·chad·nezʹzar^&#42;1^ of Babylon made his army labor greatly against Tyre. Every head became bald, and every shoulder was rubbed bare. But he and his army received no wages for the labor he expended on Tyre.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v26-29-19]]

^<<v26-29-19,19>>^ “Therefore this is what the Sovereign Lord Jehovah says, ‘Here I am giving the land of Egypt to King Neb·u·chad·nezʹzar^&#42;1^ of Babylon, and he will carry off its wealth and take much spoil and plunder from it; and it will become wages for his army.’

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v26-29-20]]

^<<v26-29-20,20>>^ “‘As compensation for his labor against her,^&#42;1^ I will give him the land of Egypt because they acted for me,’ declares the Sovereign Lord Jehovah.

[NOTE]
====
. That is, against Tyre.
====

[[v26-29-21]]

^<<v26-29-21,21>>^ “In that day I will cause a horn to sprout for the house of Israel,^&#42;1^ and I will give you an opportunity to speak among them; and they will have to know that I am Jehovah.”

[NOTE]
====
. Or “endow the house of Israel with strength.”
====

'''

xref:026-ezekiel/026-ezekiel-028.adoc#v26-28-0[&#60; Capítulo Anterior] | <<v26-29-0,Topo>> | xref:026-ezekiel/026-ezekiel-030.adoc#v26-30-0[Próximo Capítulo &#62;]