include::./index.adoc[]

[[v26-24-0]]
=== Ezekiel, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-24-1]]

^<<v26-24-1,1>>^ The word of Jehovah again came to me in the ninth year, in the tenth month, on the tenth day of the month, saying:

[[v26-24-2]]

^<<v26-24-2,2>>^ “Son of man, record this date,^&#42;1^ this very day. The king of Babylon has begun his attack against Jerusalem on this very day.

[NOTE]
====
. Lit., “the name of the day.”
====

[[v26-24-3]]

^<<v26-24-3,3>>^ And relate a proverb^&#42;1^ concerning the rebellious house, and say concerning them:
“‘This is what the Sovereign Lord Jehovah says:
“Put the cooking pot^&#42;2^ on; put it on the fire and pour water into it.

[NOTE]
====
. Or “an allegory.”
. Or “wide-mouthed cooking pot.”
====

[[v26-24-4]]

^<<v26-24-4,4>>^ Put pieces of meat into it, every good piece,
The thigh and the shoulder; fill it with the choicest bones.

[[v26-24-5]]

^<<v26-24-5,5>>^ Take the choicest sheep of the flock, and stack the logs all around under the pot.
Boil the pieces, and cook the bones inside it.”’

[[v26-24-6]]

^<<v26-24-6,6>>^ “Therefore this is what the Sovereign Lord Jehovah says:
‘Woe to the city of bloodshed, the rusty cooking pot, whose rust has not been removed!
Empty it piece by piece; do not cast lots for them.

[[v26-24-7]]

^<<v26-24-7,7>>^ For its blood is within it; she poured it out on the bare rock.
She did not pour it out on the earth, to cover it over with dust.

[[v26-24-8]]

^<<v26-24-8,8>>^ To stir up rage for executing vengeance,
I have put her blood on the shining, bare rock
So that it may not be covered over.’

[[v26-24-9]]

^<<v26-24-9,9>>^ “Therefore this is what the Sovereign Lord Jehovah says:
‘Woe to the city of bloodshed!
I will pile the wood high.

[[v26-24-10]]

^<<v26-24-10,10>>^ Heap on the logs and kindle the fire,
Boil the flesh thoroughly, pour out the broth, and let the bones be charred.

[[v26-24-11]]

^<<v26-24-11,11>>^ Set the empty pot on the coals to make it hot
So that its copper will become red hot.
Its uncleanness will melt away within it, and its rust will be consumed.

[[v26-24-12]]

^<<v26-24-12,12>>^ It is frustrating and exhausting,
For the heavy rust will not come off.
Throw it into the fire with its rust!’

[[v26-24-13]]

^<<v26-24-13,13>>^ “‘Your uncleanness was due to your obscene conduct. I tried to cleanse you, but you would not become clean from your uncleanness. You will not become clean until my rage against you subsides.

[[v26-24-14]]

^<<v26-24-14,14>>^ I myself, Jehovah, have spoken. It will come to pass. I will act without holding back, without sorrow, without regret. They will judge you according to your ways and your dealings,’ declares the Sovereign Lord Jehovah.”

[[v26-24-15]]

^<<v26-24-15,15>>^ And the word of Jehovah again came to me, saying:

[[v26-24-16]]

^<<v26-24-16,16>>^ “Son of man, in a single blow I am about to take away your dear one from you. You should not mourn;^&#42;1^ nor should you weep or shed tears.

[NOTE]
====
. Or “beat your chest.”
====

[[v26-24-17]]

^<<v26-24-17,17>>^ Groan in silence, and do not observe mourning rites for the dead. Bind on your turban, and put on your sandals. You should not cover over the mustache,^&#42;1^ and do not eat the bread brought to you by others.”^&#42;2^

[NOTE]
====
. Or “upper lip.”
. Lit., “the bread of men.”
====

[[v26-24-18]]

^<<v26-24-18,18>>^ And I spoke to the people in the morning, and my wife died in the evening. So I did in the morning just as I had been commanded.

[[v26-24-19]]

^<<v26-24-19,19>>^ The people were saying to me: “Will you not tell us what these things you are doing have to do with us?”

[[v26-24-20]]

^<<v26-24-20,20>>^ I replied to them: “The word of Jehovah has come to me, saying,

[[v26-24-21]]

^<<v26-24-21,21>>^ ‘Tell the house of Israel: “This is what the Sovereign Lord Jehovah says, ‘I am about to profane my sanctuary, the source of your great pride, the thing dear to you and the desire of your heart.^&#42;1^ Your own sons and daughters whom you left behind will fall by the sword.

[NOTE]
====
. Or “your soul’s compassion.”
====

[[v26-24-22]]

^<<v26-24-22,22>>^ Then you will have to do just as I have done. You will not cover over your mustache, and you will not eat the bread brought to you by others.

[[v26-24-23]]

^<<v26-24-23,23>>^ Your turbans will be on your heads and your sandals on your feet. You will not mourn or weep. Instead, you will rot away in your errors, and you will groan to one another.

[[v26-24-24]]

^<<v26-24-24,24>>^ Ezekiel has become a sign for you. Just as he has done, you will do. When it happens, you will have to know that I am the Sovereign Lord Jehovah.’”’”

[[v26-24-25]]

^<<v26-24-25,25>>^ “And as for you, son of man, on the day that I take away from them their fortress—the beautiful object of their joy, the thing dear to them, their heart’s^&#42;1^ desire—along with their sons and daughters,

[NOTE]
====
. Or “soul’s.”
====

[[v26-24-26]]

^<<v26-24-26,26>>^ it will be reported to you by one who has escaped.

[[v26-24-27]]

^<<v26-24-27,27>>^ In that day you will open your mouth and speak to the one who escaped, and you will no longer be mute. You will become a sign to them, and they will have to know that I am Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-023.adoc#v26-23-0[&#60; Capítulo Anterior] | <<v26-24-0,Topo>> | xref:026-ezekiel/026-ezekiel-025.adoc#v26-25-0[Próximo Capítulo &#62;]