include::./index.adoc[]

[[v26-4-0]]
=== Ezekiel, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-4-1]]

^<<v26-4-1,1>>^ “And you, son of man, take a brick and put it in front of you. Engrave on it a city—Jerusalem.

[[v26-4-2]]

^<<v26-4-2,2>>^ Lay siege to it, build a siege wall against it, raise up a siege rampart against it, set up camps against it, and surround it with battering rams.

[[v26-4-3]]

^<<v26-4-3,3>>^ Take an iron griddle and place it as an iron wall between you and the city. Then set your face against it, and it will be under siege; you are to besiege it. This is a sign to the house of Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ “Then you should lie on your left side and lay the guilt of the house of Israel on yourself.^&#42;1^ You will carry their guilt for the number of days that you lie on your side.

[NOTE]
====
. Lit., “it,” that is, Ezekiel’s left side.
====

[[v26-4-5]]

^<<v26-4-5,5>>^ And I will impose on you 390 days, corresponding to the years of their guilt, and you will carry the guilt of the house of Israel.

[[v26-4-6]]

^<<v26-4-6,6>>^ And you must complete them.
“Then for a second time you will lie down, on your right side, and you will carry the guilt of the house of Judah for 40 days. A day for a year, a day for a year, is what I have given you.

[[v26-4-7]]

^<<v26-4-7,7>>^ And you will turn your face toward the siege of Jerusalem with your arm bared, and you must prophesy against it.

[[v26-4-8]]

^<<v26-4-8,8>>^ “Look! I will tie you with ropes so that you cannot turn from your one side to your other side until you have completed the days of your siege.

[[v26-4-9]]

^<<v26-4-9,9>>^ “And you should take wheat, barley, broad beans, lentils, millet, and spelt and put them in one container and make them into bread for yourself. For the number of the days that you are lying on your side, 390 days, you will eat it.

[[v26-4-10]]

^<<v26-4-10,10>>^ You will weigh out and eat 20 shekels^&#42;1^ of food per day. You will eat it at set times.

[NOTE]
====
. About 230 g (7.3 oz t). See App. B14.
====

[[v26-4-11]]

^<<v26-4-11,11>>^ “And you will drink water by measure, a sixth of a hin.^&#42;1^ You will drink it at set times.

[NOTE]
====
. About 0.6 L (1.3 pt). See App. B14.
====

[[v26-4-12]]

^<<v26-4-12,12>>^ “You will eat it as you would a round barley loaf; you will bake it before their eyes, using dried human excrement as fuel.”

[[v26-4-13]]

^<<v26-4-13,13>>^ Jehovah went on to say: “This is how the Israelites will eat their bread—unclean—among the nations where I will disperse them.”

[[v26-4-14]]

^<<v26-4-14,14>>^ I then said: “Not that, Sovereign Lord Jehovah! From my youth until now, I have^&#42;1^ not been defiled by eating meat from an animal found dead or a torn animal, and no unclean^&#42;2^ meat has entered my mouth.”

[NOTE]
====
. Or “my soul has.”
. Or “foul.”
====

[[v26-4-15]]

^<<v26-4-15,15>>^ So he said to me: “All right, I will allow you to use cattle manure instead of human excrement, and you will bake your bread over it.”

[[v26-4-16]]

^<<v26-4-16,16>>^ He then said to me: “Son of man, here I am cutting off the food supply^&#42;1^ in Jerusalem, and with great anxiety they will eat their bread ration by weight, and in horror they will drink their water ration by measure.

[NOTE]
====
. Lit., “breaking the bread rods.” Possibly referring to rods used for storing bread.
====

[[v26-4-17]]

^<<v26-4-17,17>>^ This will happen so that lacking bread and water, they may look in shock at one another and waste away because of their error.

'''

xref:026-ezekiel/026-ezekiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezekiel/026-ezekiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]