include::./index.adoc[]

[[v26-28-0]]
=== Ezekiel, 28
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-28-1]]

^<<v26-28-1,1>>^ The word of Jehovah again came to me, saying:

[[v26-28-2]]

^<<v26-28-2,2>>^ “Son of man, tell the leader of Tyre, ‘This is what the Sovereign Lord Jehovah says:
“Because your heart has become haughty, you keep saying, ‘I am a god.
I sit on the throne of a god in the heart of the sea.’
But you are only a man, not a god,
Though in your heart you feel that you are a god.

[[v26-28-3]]

^<<v26-28-3,3>>^ Look! You are wiser than Daniel.
No secrets have been hidden from you.

[[v26-28-4]]

^<<v26-28-4,4>>^ You have made yourself wealthy by your wisdom and your discernment,
And you keep storing up gold and silver in your treasuries.

[[v26-28-5]]

^<<v26-28-5,5>>^ Your skillful trading brought you great wealth,
And your heart grew haughty because of your wealth.”’

[[v26-28-6]]

^<<v26-28-6,6>>^ “‘Therefore this is what the Sovereign Lord Jehovah says:
“Because in your heart you feel that you are a god,

[[v26-28-7]]

^<<v26-28-7,7>>^ I am bringing foreigners against you, the most ruthless of the nations,
And they will draw their swords against the beauty of your wisdom
And defile your glorious splendor.

[[v26-28-8]]

^<<v26-28-8,8>>^ They will bring you down to the pit,^&#42;1^
And you will die a violent death in the heart of the open sea.

[NOTE]
====
. Or “grave.”
====

[[v26-28-9]]

^<<v26-28-9,9>>^ Will you still say, ‘I am a god,’ to the one killing you?
You will be a mere man, not a god, in the hand of those defiling you.”’

[[v26-28-10]]

^<<v26-28-10,10>>^ ‘By the hand of foreigners, you will die the death of the uncircumcised ones,
For I myself have spoken,’ declares the Sovereign Lord Jehovah.”

[[v26-28-11]]

^<<v26-28-11,11>>^ And the word of Jehovah again came to me, saying:

[[v26-28-12]]

^<<v26-28-12,12>>^ “Son of man, sing a dirge^&#42;1^ concerning the king of Tyre, and tell him, ‘This is what the Sovereign Lord Jehovah says:
“You were the model of perfection,^&#42;2^
Full of wisdom and perfect in beauty.

[NOTE]
====
. Or “song of mourning.”
. Lit., “were sealing up a pattern.”
====

[[v26-28-13]]

^<<v26-28-13,13>>^ You were in Eʹden, the garden of God.
You were adorned with every precious stone
—Ruby, topaz, and jasper; chrysʹo·lite, onyx, and jade; sapphire, turquoise, and emerald;
And their settings and mountings were made of gold.
They were prepared on the day you were created.

[[v26-28-14]]

^<<v26-28-14,14>>^ I assigned you as the anointed covering cherub.
You were on the holy mountain of God, and you walked about among fiery stones.

[[v26-28-15]]

^<<v26-28-15,15>>^ You were faultless in your ways from the day you were created
Until unrighteousness was found in you.

[[v26-28-16]]

^<<v26-28-16,16>>^ Because of your abundant trade,
You became filled with violence, and you began to sin.
So I will cast you out as profane from the mountain of God and destroy you,
O covering cherub, away from the stones of fire.

[[v26-28-17]]

^<<v26-28-17,17>>^ Your heart became haughty because of your beauty.
You corrupted your wisdom because of your own glorious splendor.
I will throw you down to the earth.
I will make you a spectacle before kings.

[[v26-28-18]]

^<<v26-28-18,18>>^ Because of your great guilt and your dishonest trading, you have profaned your sanctuaries.
I will cause a fire to break out in your midst, and it will consume you.
I will reduce you to ashes on the earth before all those looking at you.

[[v26-28-19]]

^<<v26-28-19,19>>^ All who knew you among the peoples will stare at you in amazement.
Your end will be sudden and terrible,
And you will cease to exist for all time.”’”

[[v26-28-20]]

^<<v26-28-20,20>>^ And the word of Jehovah again came to me, saying:

[[v26-28-21]]

^<<v26-28-21,21>>^ “Son of man, turn your face toward Siʹdon, and prophesy against her.

[[v26-28-22]]

^<<v26-28-22,22>>^ You should say, ‘This is what the Sovereign Lord Jehovah says:
“Here I am against you, O Siʹdon, and I will be glorified in your midst;
And people will have to know that I am Jehovah when I execute judgment on her and I am sanctified in her.

[[v26-28-23]]

^<<v26-28-23,23>>^ I will send pestilence into her and blood will flow in her streets.
The slain will fall in her midst when the sword comes against her from all sides;
And they will have to know that I am Jehovah.

[[v26-28-24]]

^<<v26-28-24,24>>^ “‘“Then the house of Israel will no longer be surrounded by injurious briars and painful thorns, those who treat them with scorn; and people will have to know that I am the Sovereign Lord Jehovah.”’

[[v26-28-25]]

^<<v26-28-25,25>>^ “‘This is what the Sovereign Lord Jehovah says: “When I regather the house of Israel from among the peoples where they were scattered, I will be sanctified among them in the eyes of the nations. And they will dwell on their land that I gave to my servant Jacob.

[[v26-28-26]]

^<<v26-28-26,26>>^ They will dwell on it in security and build houses and plant vineyards, and they will dwell in security when I execute judgment on all those around them who treat them with scorn; and they will have to know that I am Jehovah their God.”’”

'''

xref:026-ezekiel/026-ezekiel-027.adoc#v26-27-0[&#60; Capítulo Anterior] | <<v26-28-0,Topo>> | xref:026-ezekiel/026-ezekiel-029.adoc#v26-29-0[Próximo Capítulo &#62;]