include::./index.adoc[]

[[v26-32-0]]
=== Ezekiel, 32
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v26-32-1]]

^<<v26-32-1,1>>^ And in the 12th year, in the 12th month, on the first day of the month, the word of Jehovah again came to me, saying:

[[v26-32-2]]

^<<v26-32-2,2>>^ “Son of man, sing a dirge^&#42;1^ concerning Pharʹaoh king of Egypt, and say to him,
‘You were like a strong young lion^&#42;2^ of the nations,
But you have been silenced.
You were like a sea monster, thrashing about in your rivers,
Muddying the waters with your feet and fouling the^&#42;3^ rivers.’

[NOTE]
====
. Or “song of mourning.”
. Or “a maned young lion.”
. Lit., “their.”
====

[[v26-32-3]]

^<<v26-32-3,3>>^ This is what the Sovereign Lord Jehovah says:
‘By means of an assembly of many nations I will cast my net over you,
And they will haul you up in my dragnet.

[[v26-32-4]]

^<<v26-32-4,4>>^ I will abandon you on the land;
I will cast you onto the open field.
I will cause all the birds of the sky to settle on you,
And I will satisfy the wild beasts of the whole earth with you.

[[v26-32-5]]

^<<v26-32-5,5>>^ I will cast your flesh on the mountains
And fill the valleys with your remains.

[[v26-32-6]]

^<<v26-32-6,6>>^ I will drench the land with your gushing blood up to the mountains,
And it will fill the streams.’^&#42;1^

[NOTE]
====
. Lit., “And the streambeds will be filled from (with) you.”
====

[[v26-32-7]]

^<<v26-32-7,7>>^ ‘And when you are extinguished I will cover the heavens and darken their stars.
I will cover the sun with clouds,
And the moon will not give its light.

[[v26-32-8]]

^<<v26-32-8,8>>^ I will darken all the shining luminaries in the heavens because of you,
And I will cover your land with darkness,’ declares the Sovereign Lord Jehovah.

[[v26-32-9]]

^<<v26-32-9,9>>^ ‘I will distress the hearts of many peoples when I lead your captives to other nations,
To lands that you have not known.

[[v26-32-10]]

^<<v26-32-10,10>>^ I will cause many peoples to be awestruck,
And their kings will shudder in horror over you when I brandish my sword before them.
They will tremble continually, each fearing for his life,
On the day of your downfall.’

[[v26-32-11]]

^<<v26-32-11,11>>^ For this is what the Sovereign Lord Jehovah says:
‘The sword of the king of Babylon will come upon you.

[[v26-32-12]]

^<<v26-32-12,12>>^ I will cause your hordes to fall by the swords of mighty warriors,
The most ruthless of the nations, all of them.
They will bring down the pride of Egypt, and all her hordes will be annihilated.

[[v26-32-13]]

^<<v26-32-13,13>>^ I will destroy all her livestock beside her abundant waters,
And no foot of a human or hoof of the livestock will muddy them again.’

[[v26-32-14]]

^<<v26-32-14,14>>^ ‘At that time I will clear up their waters,
And I will make their rivers flow like oil,’ declares the Sovereign Lord Jehovah.

[[v26-32-15]]

^<<v26-32-15,15>>^ ‘When I make Egypt a desolate wasteland, a land stripped of all that filled it,
When I strike down all the inhabitants in it,
They will have to know that I am Jehovah.

[[v26-32-16]]

^<<v26-32-16,16>>^ This is a dirge, and people will certainly chant it;
The daughters of the nations will chant it.
They will chant it over Egypt and over all its hordes,’ declares the Sovereign Lord Jehovah.”

[[v26-32-17]]

^<<v26-32-17,17>>^ Then in the 12th year, on the 15th day of the month, the word of Jehovah came to me, saying:

[[v26-32-18]]

^<<v26-32-18,18>>^ “Son of man, wail over the hordes of Egypt and bring her down to the land below, her and the daughters of mighty nations, with those going down into the pit.^&#42;1^

[NOTE]
====
. Or “grave.”
====

[[v26-32-19]]

^<<v26-32-19,19>>^ “‘Whom do you surpass in beauty? Go down, and lie with the uncircumcised ones!’

[[v26-32-20]]

^<<v26-32-20,20>>^ “‘They will fall among those slain by the sword. She has been given to the sword; drag her away along with all her hordes.

[[v26-32-21]]

^<<v26-32-21,21>>^ “‘From the depths of the Grave^&#42;1^ the mightiest warriors will speak to him and his helpers. They will certainly go down and will lie just like the uncircumcised, slain by the sword.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v26-32-22]]

^<<v26-32-22,22>>^ As·syrʹi·a is there with all her assembly. Their graves are all around him, all of them fallen by the sword.

[[v26-32-23]]

^<<v26-32-23,23>>^ Her graves are in the depths of the pit,^&#42;1^ and her assembly is all around her grave, all of them struck down by the sword, because they caused terror in the land of the living.

[NOTE]
====
. Or “grave.”
====

[[v26-32-24]]

^<<v26-32-24,24>>^ “‘Eʹlam is there with all her hordes around her grave, all of them fallen by the sword. They have gone down uncircumcised to the land below, those who caused terror in the land of the living. Now they will bear their shame with those going down into the pit.^&#42;1^

[NOTE]
====
. Or “grave.”
====

[[v26-32-25]]

^<<v26-32-25,25>>^ They have made a bed for her among the slain, along with all her hordes around her graves. All of them are uncircumcised, slain by the sword, because they caused terror in the land of the living; and they will bear their shame with those going down into the pit.^&#42;1^ He has been put among the slain.

[NOTE]
====
. Or “grave.”
====

[[v26-32-26]]

^<<v26-32-26,26>>^ “‘There is where Meʹshech and Tuʹbal and all their^&#42;1^ hordes are. Their^&#42;2^ graves are all around him. All of them are uncircumcised, pierced through by the sword, because they caused terror in the land of the living.

[NOTE]
====
. Lit., “her.”
. Lit., “Her.”
====

[[v26-32-27]]

^<<v26-32-27,27>>^ Will they not lie with mighty uncircumcised warriors who have fallen, who went down to the Grave^&#42;1^ with their weapons of war? And they will put their swords under their heads^&#42;2^ and their sins on their bones, because these mighty warriors terrorized the land of the living.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
. Perhaps a reference to warriors buried with their sword, with military honors.
====

[[v26-32-28]]

^<<v26-32-28,28>>^ But as for you, you will be crushed among the uncircumcised ones, and you will lie with those who were slain by the sword.

[[v26-32-29]]

^<<v26-32-29,29>>^ “‘Eʹdom is there, her kings and all her chieftains, who despite their mightiness, were laid among those slain by the sword; they too will lie with the uncircumcised ones and with those going down into the pit.^&#42;1^

[NOTE]
====
. Or “grave.”
====

[[v26-32-30]]

^<<v26-32-30,30>>^ “‘There all the princes^&#42;1^ of the north are, along with all the Si·doʹni·ans, who have gone down in disgrace with the slain, despite the terror caused by their mightiness. They will lie uncircumcised with those who were slain by the sword and will bear their shame with those going down into the pit.^&#42;2^

[NOTE]
====
. Or “leaders.”
. Or “grave.”
====

[[v26-32-31]]

^<<v26-32-31,31>>^ “‘Pharʹaoh will see all of these, and he will be comforted over all that happened to his hordes; Pharʹaoh and all his army will be slain by the sword,’ declares the Sovereign Lord Jehovah.

[[v26-32-32]]

^<<v26-32-32,32>>^ “‘Because he caused terror in the land of the living, Pharʹaoh and all his hordes will be laid to rest with the uncircumcised, with those slain by the sword,’ declares the Sovereign Lord Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-031.adoc#v26-31-0[&#60; Capítulo Anterior] | <<v26-32-0,Topo>> | xref:026-ezekiel/026-ezekiel-033.adoc#v26-33-0[Próximo Capítulo &#62;]