include::./index.adoc[]

[[v35-1-0]]
=== Habakkuk, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v35-1-1]]

^<<v35-1-1,1>>^ A pronouncement that Ha·bakʹkuk^&#42;1^ the prophet received in a vision:

[NOTE]
====
. Possibly meaning “Ardent Embrace.”
====

[[v35-1-2]]

^<<v35-1-2,2>>^ How long, O Jehovah, must I cry for help, but you do not hear?
How long must I ask for help from violence, but you do not intervene?^&#42;1^

[NOTE]
====
. Or “save.”
====

[[v35-1-3]]

^<<v35-1-3,3>>^ Why do you make me witness wrongdoing?
And why do you tolerate oppression?
Why are destruction and violence before me?
And why do quarreling and conflict abound?

[[v35-1-4]]

^<<v35-1-4,4>>^ So law is paralyzed,
And justice is never carried out.
For the wicked surround the righteous;
That is why justice is perverted.

[[v35-1-5]]

^<<v35-1-5,5>>^ “Look among the nations and pay attention!
Stare in amazement and be astounded;
For something will happen in your days
That you will not believe even if it is told to you.

[[v35-1-6]]

^<<v35-1-6,6>>^ For here I am raising up the Chal·deʹans,
The ruthless and impetuous nation.
They sweep through vast stretches of the earth
To seize homes not theirs.

[[v35-1-7]]

^<<v35-1-7,7>>^ They are frightening and fearsome.
They establish their own justice and authority.^&#42;1^

[NOTE]
====
. Or “dignity.”
====

[[v35-1-8]]

^<<v35-1-8,8>>^ Their horses are swifter than leopards,
And they are fiercer than wolves in the night.
Their warhorses gallop forward;
Their horses come from far away.
They swoop down like the eagle rushing to feed.

[[v35-1-9]]

^<<v35-1-9,9>>^ All of them come bent on violence.
The assembling of their faces is like the east wind,
And they scoop up captives like sand.

[[v35-1-10]]

^<<v35-1-10,10>>^ They scoff at kings
And laugh at high officials.
They laugh at every fortified place;
They pile up a dirt ramp and capture it.

[[v35-1-11]]

^<<v35-1-11,11>>^ Then they move forward like the wind and pass through,
But they will become guilty,
Because they credit their power to their god.”^&#42;1^

[NOTE]
====
. Or possibly, “their power is their god.”
====

[[v35-1-12]]

^<<v35-1-12,12>>^ Are you not from everlasting, O Jehovah?
O my God, my Holy One, you do not die.^&#42;1^
O Jehovah, you appointed them to execute judgment;
My Rock, you established them for punishment.^&#42;2^

[NOTE]
====
. Or possibly, “we will not die.”
. Or “for reproving.”
====

[[v35-1-13]]

^<<v35-1-13,13>>^ Your eyes are too pure to look on what is evil,
And you cannot tolerate wickedness.
Why, then, do you tolerate the treacherous
And keep silent when a wicked man swallows up someone more righteous than he is?

[[v35-1-14]]

^<<v35-1-14,14>>^ Why do you make man like the fish of the sea,
Like creeping things that have no ruler?

[[v35-1-15]]

^<<v35-1-15,15>>^ All of these he^&#42;1^ hauls up with a fishhook.
He catches them in his dragnet,
And he gathers them in his fishing net.
That is why he rejoices greatly.

[NOTE]
====
. That is, the Chaldean enemy.
====

[[v35-1-16]]

^<<v35-1-16,16>>^ That is why he offers sacrifices to his dragnet
And makes sacrifices^&#42;1^ to his fishing net;
For by them his portion is rich,^&#42;2^
And his food is choice.

[NOTE]
====
. Or “sacrificial smoke.”
. Lit., “well-oiled.”
====

[[v35-1-17]]

^<<v35-1-17,17>>^ Will he then keep emptying out his dragnet?^&#42;1^
Will he go on slaughtering nations without compassion?

[NOTE]
====
. Or possibly, “keep drawing his sword?”
====

'''

xref:034-nahum/034-nahum-003.adoc#v34-3-0[&#60; Capítulo Anterior] | <<v35-1-0,Topo>> | xref:035-habakkuk/035-habakkuk-002.adoc#v35-2-0[Próximo Capítulo &#62;]