include::./index.adoc[]

[[v35-2-0]]
=== Habakkuk, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v35-2-1]]

^<<v35-2-1,1>>^ At my guardpost I will keep standing,
And I will station myself on the rampart.
I will keep watch to see what he will speak by means of me
And what I will reply when I am reproved.

[[v35-2-2]]

^<<v35-2-2,2>>^ Jehovah then answered me:
“Write down the vision, and inscribe it clearly on tablets,
So that the one reading aloud from it may do so easily.^&#42;1^

[NOTE]
====
. Or “fluently.”
====

[[v35-2-3]]

^<<v35-2-3,3>>^ For the vision is yet for its appointed time,
And it is rushing toward its end,^&#42;1^ and it will not lie.
Even if it should delay,^&#42;2^ keep in expectation of it!^&#42;3^
For it will without fail come true.
It will not be late!

[NOTE]
====
. Or “fulfillment.”
. Or “if it seems to delay.”
. Or “wait eagerly for it!”
====

[[v35-2-4]]

^<<v35-2-4,4>>^ Look at the one who is proud;^&#42;1^
He is not upright within himself.
But the righteous one will live by his faithfulness.^&#42;2^

[NOTE]
====
. Or “Look! His soul is swelled up.”
. Or possibly, “faith; belief.”
====

[[v35-2-5]]

^<<v35-2-5,5>>^ Indeed, because the wine is treacherous,
The arrogant man will not reach his goal.
He makes his appetite^&#42;1^ as large as the Grave;^&#42;2^
He is like death and cannot be satisfied.
He keeps gathering all the nations
And collecting for himself all the peoples.

[NOTE]
====
. Or “soul.”
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v35-2-6]]

^<<v35-2-6,6>>^ Will not all of these speak a proverb, an allusion, and riddles against him?
They will say:
‘Woe to him who accumulates what is not his
—For how long?—
And who makes even greater his own debt!

[[v35-2-7]]

^<<v35-2-7,7>>^ Will not your creditors rise up suddenly?
They will wake up and violently shake you,
And you will become something for them to plunder.

[[v35-2-8]]

^<<v35-2-8,8>>^ Because you plundered many nations,
All the rest of the peoples will plunder you,
Because of your shedding men’s blood
And your violence to the earth,
To the cities and those living in them.

[[v35-2-9]]

^<<v35-2-9,9>>^ Woe to the one who makes evil gain for his house,
So as to set his nest on the height,
To escape the grasp of calamity!

[[v35-2-10]]

^<<v35-2-10,10>>^ You have plotted shame against your house.
By wiping out many peoples you sin against yourself.^&#42;1^

[NOTE]
====
. Or “your soul.”
====

[[v35-2-11]]

^<<v35-2-11,11>>^ For a stone will cry out from the wall,
And from the woodwork a rafter will answer it.

[[v35-2-12]]

^<<v35-2-12,12>>^ Woe to the one who builds a city by bloodshed,
And who establishes a town by unrighteousness!

[[v35-2-13]]

^<<v35-2-13,13>>^ Look! Is it not from Jehovah of armies that peoples will work hard to feed the fire,
And that nations tire themselves out for nothing?

[[v35-2-14]]

^<<v35-2-14,14>>^ For the earth will be filled with the knowledge of the glory of Jehovah
As the waters cover the sea.

[[v35-2-15]]

^<<v35-2-15,15>>^ Woe to the one who gives his companions something to drink,
Adding to it rage and anger, to make them drunk,
In order to look on their nakedness!

[[v35-2-16]]

^<<v35-2-16,16>>^ You will be glutted with dishonor rather than glory.
You too—drink and expose your uncircumcised condition.^&#42;1^
The cup in the right hand of Jehovah will come around to you,
And disgrace will cover over your glory;

[NOTE]
====
. Or possibly, “and stagger.”
====

[[v35-2-17]]

^<<v35-2-17,17>>^ For the violence done to Lebʹa·non will cover you,
And the destruction that terrified the beasts will come upon you,
Because of your shedding men’s blood
And your violence to the earth,
To the cities and those living in them.

[[v35-2-18]]

^<<v35-2-18,18>>^ Of what benefit is a carved image
When its maker has carved it?
Of what benefit is a metal statue^&#42;1^ and a teacher of lies,
Even though its maker trusts in it,
Making worthless gods that are speechless?

[NOTE]
====
. Or “molten statue.”
====

[[v35-2-19]]

^<<v35-2-19,19>>^ Woe to the one who says to a piece of wood, “Awake!”
Or to a speechless stone, “Wake up! Instruct us!”
Look! It is overlaid in gold and silver,
And there is no breath at all within it.

[[v35-2-20]]

^<<v35-2-20,20>>^ But Jehovah is in his holy temple.
Be silent before him, all the earth!’”

'''

xref:035-habakkuk/035-habakkuk-001.adoc#v35-1-0[&#60; Capítulo Anterior] | <<v35-2-0,Topo>> | xref:035-habakkuk/035-habakkuk-003.adoc#v35-3-0[Próximo Capítulo &#62;]