include::./index.adoc[]

[[v35-3-0]]
=== Habakkuk, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v35-3-1]]

^<<v35-3-1,1>>^ The prayer of Ha·bakʹkuk the prophet, in dirges:^&#42;1^

[NOTE]
====
. Or “songs of mourning.”
====

[[v35-3-2]]

^<<v35-3-2,2>>^ O Jehovah, I have heard the report about you.
I am in awe, O Jehovah, of your activity.
In the midst of the years^&#42;1^ bring it to life!
In the midst of the years^&#42;2^ make it known.
May you remember to show mercy during the turmoil.

[NOTE]
====
. Or possibly, “In our time.”
. Or possibly, “In our time.”
====

[[v35-3-3]]

^<<v35-3-3,3>>^ God came from Teʹman,
The Holy One from Mount Paʹran. (Selah)^&#42;1^
His majesty covered the heavens;
With his praise the earth was filled.

[NOTE]
====
. See Glossary.
====

[[v35-3-4]]

^<<v35-3-4,4>>^ His brightness was like the light.
Two rays flashed from his hand,
Where his strength was hidden.

[[v35-3-5]]

^<<v35-3-5,5>>^ Before him went pestilence,
And burning fever followed at his feet.

[[v35-3-6]]

^<<v35-3-6,6>>^ He stood still and shook the earth.
With a look, he made nations leap.
The eternal mountains were smashed,
And the ancient hills bowed down.
The paths of long ago are his.

[[v35-3-7]]

^<<v35-3-7,7>>^ I saw trouble in the tents of Cuʹshan.
The tent cloths of the land of Midʹi·an trembled.

[[v35-3-8]]

^<<v35-3-8,8>>^ Is it against the rivers, O Jehovah,
Is it against the rivers that your anger is burning?
Or is your fury against the sea?
For you rode on your horses;
Your chariots were victorious.^&#42;1^

[NOTE]
====
. Or “salvation.”
====

[[v35-3-9]]

^<<v35-3-9,9>>^ Your bow is uncovered and ready.
The rods^&#42;1^ are assigned with an oath.^&#42;2^ (Selah)
You split the earth with rivers.

[NOTE]
====
. Or possibly, “arrows.”
. Or possibly, “The sworn oaths of the tribes are stated.”
====

[[v35-3-10]]

^<<v35-3-10,10>>^ Mountains writhed in pain at the sight of you.
A downpour of waters swept through.
The deep roared with its voice.
It lifted its hands high.

[[v35-3-11]]

^<<v35-3-11,11>>^ Sun and moon stood still in their lofty abode.
Your arrows went out like the light.
The lightning of your spear was brilliant.

[[v35-3-12]]

^<<v35-3-12,12>>^ You marched through the earth with indignation.
You trampled^&#42;1^ the nations in anger.

[NOTE]
====
. Lit., “threshed.”
====

[[v35-3-13]]

^<<v35-3-13,13>>^ You went out for the salvation of your people, to save your anointed one.
You crushed the leader^&#42;1^ of the house of the wicked.
It was exposed from the foundation to the top.^&#42;2^ (Selah)

[NOTE]
====
. Lit., “head.”
. Lit., “neck.”
====

[[v35-3-14]]

^<<v35-3-14,14>>^ You pierced the head of his warriors with his own weapons^&#42;1^
When they stormed out to scatter me.
They were overjoyed to devour an afflicted one in secret.

[NOTE]
====
. Lit., “his rods.”
====

[[v35-3-15]]

^<<v35-3-15,15>>^ Through the sea you trod with your horses,
Through the surging of vast waters.

[[v35-3-16]]

^<<v35-3-16,16>>^ I heard and I trembled within;^&#42;1^
At the sound my lips quivered.
Rottenness entered my bones;
My legs beneath me were shaking.
But I quietly wait for the day of distress,
For it is coming upon the people who attack us.

[NOTE]
====
. Lit., “and my belly trembled.”
====

[[v35-3-17]]

^<<v35-3-17,17>>^ Although the fig tree may not blossom,
And there may be no fruit on the vines;
Although the olive crop may fail,
And the fields^&#42;1^ may produce no food;
Although the flock may disappear from the pen,
And there may be no cattle in the stalls;

[NOTE]
====
. Or “terraces.”
====

[[v35-3-18]]

^<<v35-3-18,18>>^ Yet, as for me, I will exult in Jehovah;
I will be joyful in the God of my salvation.

[[v35-3-19]]

^<<v35-3-19,19>>^ The Sovereign Lord Jehovah is my strength;
He will make my feet like those of a deer
And cause me to tread on high places.

_To the director; with my stringed instruments._

'''

xref:035-habakkuk/035-habakkuk-002.adoc#v35-2-0[&#60; Capítulo Anterior] | <<v35-3-0,Topo>> | xref:036-zephaniah/036-zephaniah-001.adoc#v36-1-0[Próximo Capítulo &#62;]