include::./index.adoc[]

[[v45-13-0]]
=== To the Romans, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v45-13-1]]

^<<v45-13-1,1>>^ Let every person^&#42;1^ be in subjection to the superior authorities, for there is no authority except by God; the existing authorities stand placed in their relative positions by God.

[NOTE]
====
. Or “soul.”
====

[[v45-13-2]]

^<<v45-13-2,2>>^ Therefore, whoever opposes the authority has taken a stand against the arrangement of God; those who have taken a stand against it will bring judgment against themselves.

[[v45-13-3]]

^<<v45-13-3,3>>^ For those rulers are an object of fear, not to the good deed, but to the bad. Do you want to be free of fear of the authority? Keep doing good, and you will have praise from it;

[[v45-13-4]]

^<<v45-13-4,4>>^ for it is God’s minister to you for your good. But if you are doing what is bad, be in fear, for it is not without purpose that it bears the sword. It is God’s minister, an avenger to express wrath^&#42;1^ against the one practicing what is bad.

[NOTE]
====
. Or “bring punishment.”
====

[[v45-13-5]]

^<<v45-13-5,5>>^ There is therefore compelling reason for you to be in subjection, not only on account of that wrath but also on account of your conscience.

[[v45-13-6]]

^<<v45-13-6,6>>^ That is why you are also paying taxes; for they are God’s public servants constantly serving this very purpose.

[[v45-13-7]]

^<<v45-13-7,7>>^ Render to all their dues: to the one who calls for the tax, the tax; to the one who calls for the tribute, the tribute; to the one who calls for fear, such fear; to the one who calls for honor, such honor.

[[v45-13-8]]

^<<v45-13-8,8>>^ Do not owe anything to anyone except to love one another; for whoever loves his fellow man has fulfilled the law.

[[v45-13-9]]

^<<v45-13-9,9>>^ For the law code, “You must not commit adultery, you must not murder, you must not steal, you must not covet,” and whatever other commandment there is, is summed up in this saying: “You must love your neighbor as yourself.”

[[v45-13-10]]

^<<v45-13-10,10>>^ Love does not work evil to one’s neighbor; therefore, love is the law’s fulfillment.

[[v45-13-11]]

^<<v45-13-11,11>>^ And do this because you know the season, that it is already the hour for you to awake from sleep, for now our salvation is nearer than at the time when we became believers.

[[v45-13-12]]

^<<v45-13-12,12>>^ The night is well along; the day has drawn near. Let us therefore throw off the works belonging to darkness and let us put on the weapons of the light.

[[v45-13-13]]

^<<v45-13-13,13>>^ Let us walk decently as in the daytime, not in wild parties^&#42;1^ and drunkenness, not in immoral intercourse and brazen conduct,^&#42;2^ not in strife and jealousy.

[NOTE]
====
. Or “in revelries.”
. Or “acts of shameless conduct.” Plural of the Greek a·selʹgei·a. See Glossary.
====

[[v45-13-14]]

^<<v45-13-14,14>>^ But put on the Lord Jesus Christ, and do not be planning ahead for the desires of the flesh.

'''

xref:045-romans/045-romans-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romans/045-romans-014.adoc#v45-14-0[Próximo Capítulo &#62;]