include::./index.adoc[]

[[v45-6-0]]
=== To the Romans, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v45-6-1]]

^<<v45-6-1,1>>^ What are we to say then? Should we continue in sin so that undeserved kindness may increase?

[[v45-6-2]]

^<<v45-6-2,2>>^ Certainly not! Seeing that we died with reference to sin, how can we keep living any longer in it?

[[v45-6-3]]

^<<v45-6-3,3>>^ Or do you not know that all of us who were baptized into Christ Jesus were baptized into his death?

[[v45-6-4]]

^<<v45-6-4,4>>^ So we were buried with him through our baptism into his death, in order that just as Christ was raised up from the dead through the glory of the Father, so we also should walk in a newness of life.

[[v45-6-5]]

^<<v45-6-5,5>>^ If we have become united with him in the likeness of his death, we will certainly also be united with him in the likeness of his resurrection.

[[v45-6-6]]

^<<v45-6-6,6>>^ For we know that our old personality was nailed to the stake along with him in order for our sinful body to be made powerless, so that we should no longer go on being slaves to sin.

[[v45-6-7]]

^<<v45-6-7,7>>^ For the one who has died has been acquitted^&#42;1^ from his sin.

[NOTE]
====
. Or “released; pardoned.”
====

[[v45-6-8]]

^<<v45-6-8,8>>^ Moreover, if we have died with Christ, we believe that we will also live with him.

[[v45-6-9]]

^<<v45-6-9,9>>^ For we know that Christ, now that he has been raised up from the dead, dies no more; death is no longer master over him.

[[v45-6-10]]

^<<v45-6-10,10>>^ For the death that he died, he died with reference to sin^&#42;1^ once for all time, but the life that he lives, he lives with reference to God.

[NOTE]
====
. That is, to remove sin.
====

[[v45-6-11]]

^<<v45-6-11,11>>^ Likewise you, consider yourselves to be dead with reference to sin but living with reference to God by Christ Jesus.

[[v45-6-12]]

^<<v45-6-12,12>>^ Therefore, do not let sin continue to rule as king in your mortal bodies so that you should obey their desires.

[[v45-6-13]]

^<<v45-6-13,13>>^ Neither go on presenting your bodies^&#42;1^ to sin as weapons of unrighteousness, but present yourselves to God as those alive from the dead, also your bodies^&#42;2^ to God as weapons of righteousness.

[NOTE]
====
. Lit., “members.”
. Lit., “members.”
====

[[v45-6-14]]

^<<v45-6-14,14>>^ For sin must not be master over you, seeing that you are not under law but under undeserved kindness.

[[v45-6-15]]

^<<v45-6-15,15>>^ What follows? Are we to commit a sin because we are not under law but under undeserved kindness? Certainly not!

[[v45-6-16]]

^<<v45-6-16,16>>^ Do you not know that if you present yourselves to anyone as obedient slaves, you are slaves of the one you obey, either of sin leading to death or of obedience leading to righteousness?

[[v45-6-17]]

^<<v45-6-17,17>>^ But thanks to God that although you were once the slaves of sin, you became obedient from the heart to that pattern of teaching to which you were handed over.

[[v45-6-18]]

^<<v45-6-18,18>>^ Yes, since you were set free from sin, you became slaves to righteousness.

[[v45-6-19]]

^<<v45-6-19,19>>^ I am speaking in human terms because of the weakness of your flesh; for just as you presented your members as slaves to uncleanness and lawlessness leading to lawlessness, so now present your members as slaves to righteousness leading to holiness.

[[v45-6-20]]

^<<v45-6-20,20>>^ For when you were slaves of sin, you were free as to righteousness.

[[v45-6-21]]

^<<v45-6-21,21>>^ What, then, was the fruit that you used to produce at that time? Things of which you are now ashamed. For the end of those things is death.

[[v45-6-22]]

^<<v45-6-22,22>>^ However, now that you were set free from sin and became slaves to God, you are producing your fruit in the way of holiness, and the end is everlasting life.

[[v45-6-23]]

^<<v45-6-23,23>>^ For the wages sin pays is death, but the gift God gives is everlasting life by Christ Jesus our Lord.

'''

xref:045-romans/045-romans-005.adoc#v45-5-0[&#60; Capítulo Anterior] | <<v45-6-0,Topo>> | xref:045-romans/045-romans-007.adoc#v45-7-0[Próximo Capítulo &#62;]