include::./index.adoc[]

[[v45-12-0]]
=== To the Romans, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v45-12-1]]

^<<v45-12-1,1>>^ Therefore, I appeal to you by the compassions of God, brothers, to present your bodies as a living sacrifice, holy and acceptable to God, a sacred service with your power of reason.

[[v45-12-2]]

^<<v45-12-2,2>>^ And stop being molded by this system of things,^&#42;1^ but be transformed by making your mind over, so that you may prove to yourselves the good and acceptable and perfect will of God.

[NOTE]
====
. Or “this age.” See Glossary.
====

[[v45-12-3]]

^<<v45-12-3,3>>^ For through the undeserved kindness given to me, I tell everyone there among you not to think more of himself than it is necessary to think, but to think so as to have a sound mind, each one as God has given^&#42;1^ to him a measure of faith.

[NOTE]
====
. Or “apportioned; distributed.”
====

[[v45-12-4]]

^<<v45-12-4,4>>^ For just as we have in one body many members, but the members do not all have the same function,

[[v45-12-5]]

^<<v45-12-5,5>>^ so we, although many, are one body in union with Christ, but individually we are members belonging to one another.

[[v45-12-6]]

^<<v45-12-6,6>>^ Since, then, we have gifts that differ according to the undeserved kindness given to us, if it is of prophecy, let us prophesy in proportion to our faith;

[[v45-12-7]]

^<<v45-12-7,7>>^ or if it is a ministry, let us be at this ministry; or the one who teaches, let him be at his teaching;

[[v45-12-8]]

^<<v45-12-8,8>>^ or the one who encourages,^&#42;1^ let him give encouragement;^&#42;2^ the one who distributes,^&#42;3^ let him do it liberally; the one who presides,^&#42;4^ let him do it diligently;^&#42;5^ the one who shows mercy, let him do it cheerfully.

[NOTE]
====
. Or “exhorts.”
. Or “exhortation.”
. Or “contributes.”
. Or “takes the lead.”
. Or “earnestly.”
====

[[v45-12-9]]

^<<v45-12-9,9>>^ Let your love be without hypocrisy. Abhor what is wicked; cling to what is good.

[[v45-12-10]]

^<<v45-12-10,10>>^ In brotherly love have tender affection for one another. In showing honor to one another, take the lead.^&#42;1^

[NOTE]
====
. Or “initiative.”
====

[[v45-12-11]]

^<<v45-12-11,11>>^ Be industrious,^&#42;1^ not lazy.^&#42;2^ Be aglow with the spirit. Slave for Jehovah.^&#42;3^

[NOTE]
====
. Or “diligent; zealous.”
. Or “Do not loiter at your business.”
. See App. A5.
====

[[v45-12-12]]

^<<v45-12-12,12>>^ Rejoice in the hope. Endure under tribulation. Persevere in prayer.

[[v45-12-13]]

^<<v45-12-13,13>>^ Share with the holy ones according to their needs. Follow the course of hospitality.

[[v45-12-14]]

^<<v45-12-14,14>>^ Keep on blessing those who persecute; bless and do not curse.

[[v45-12-15]]

^<<v45-12-15,15>>^ Rejoice with those who rejoice; weep with those who weep.

[[v45-12-16]]

^<<v45-12-16,16>>^ Have the same attitude toward others as toward yourselves; do not set your mind on lofty things,^&#42;1^ but be led along with the lowly things. Do not become wise in your own eyes.

[NOTE]
====
. Or “cultivate lofty ideas.”
====

[[v45-12-17]]

^<<v45-12-17,17>>^ Return evil for evil to no one. Take into consideration what is fine from the viewpoint of^&#42;1^ all men.

[NOTE]
====
. Or “in the sight of.”
====

[[v45-12-18]]

^<<v45-12-18,18>>^ If possible, as far as it depends on you, be peaceable with all men.

[[v45-12-19]]

^<<v45-12-19,19>>^ Do not avenge yourselves, beloved, but yield place to the wrath;^&#42;1^ for it is written: “‘Vengeance is mine; I will repay,’ says Jehovah.”^&#42;2^

[NOTE]
====
. That is, God’s wrath.
. See App. A5.
====

[[v45-12-20]]

^<<v45-12-20,20>>^ But “if your enemy is hungry, feed him; if he is thirsty, give him something to drink; for by doing this you will heap fiery coals on his head.”^&#42;1^

[NOTE]
====
. That is, to soften the person and melt his hardness.
====

[[v45-12-21]]

^<<v45-12-21,21>>^ Do not let yourself be conquered by the evil, but keep conquering the evil with the good.

'''

xref:045-romans/045-romans-011.adoc#v45-11-0[&#60; Capítulo Anterior] | <<v45-12-0,Topo>> | xref:045-romans/045-romans-013.adoc#v45-13-0[Próximo Capítulo &#62;]