include::./index.adoc[]

[[v45-15-0]]
=== To the Romans, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v45-15-1]]

^<<v45-15-1,1>>^ We, though, who are strong ought to bear the weaknesses of those not strong, and not to be pleasing ourselves.

[[v45-15-2]]

^<<v45-15-2,2>>^ Let each of us please his neighbor for his good, to build him up.

[[v45-15-3]]

^<<v45-15-3,3>>^ For even the Christ did not please himself, but just as it is written: “The reproaches of those reproaching you have fallen upon me.”

[[v45-15-4]]

^<<v45-15-4,4>>^ For all the things that were written beforehand were written for our instruction, so that through our endurance and through the comfort from the Scriptures we might have hope.

[[v45-15-5]]

^<<v45-15-5,5>>^ Now may the God who supplies endurance and comfort grant you to have among yourselves the same mental attitude that Christ Jesus had,

[[v45-15-6]]

^<<v45-15-6,6>>^ so that unitedly you may with one voice^&#42;1^ glorify the God and Father of our Lord Jesus Christ.

[NOTE]
====
. Lit., “mouth.”
====

[[v45-15-7]]

^<<v45-15-7,7>>^ So welcome^&#42;1^ one another, just as the Christ also welcomed you, with glory to God in view.

[NOTE]
====
. Or “accept.”
====

[[v45-15-8]]

^<<v45-15-8,8>>^ For I tell you that Christ became a minister of those who are circumcised in behalf of God’s truthfulness, so as to verify the promises He made to their forefathers,

[[v45-15-9]]

^<<v45-15-9,9>>^ and that the nations might glorify God for his mercy. Just as it is written: “That is why I will openly acknowledge you among the nations, and to your name I will sing praises.”

[[v45-15-10]]

^<<v45-15-10,10>>^ And again he says: “Be glad, you nations, with his people.”

[[v45-15-11]]

^<<v45-15-11,11>>^ And again: “Praise Jehovah,^&#42;1^ all you nations, and let all the peoples praise him.”

[NOTE]
====
. See App. A5.
====

[[v45-15-12]]

^<<v45-15-12,12>>^ And again Isaiah says: “There will be the root of Jesʹse, the one arising to rule nations; on him nations will rest their hope.”

[[v45-15-13]]

^<<v45-15-13,13>>^ May the God who gives hope fill you with all joy and peace by your trusting in him, so that you may abound^&#42;1^ in hope with power of holy spirit.

[NOTE]
====
. Or “overflow.”
====

[[v45-15-14]]

^<<v45-15-14,14>>^ Now I myself am convinced about you, my brothers, that you yourselves are also full of goodness, filled with all knowledge, and that you are able to admonish^&#42;1^ one another.

[NOTE]
====
. Or “instruct.”
====

[[v45-15-15]]

^<<v45-15-15,15>>^ However, I have written to you more outspokenly on some points, so as to give you another reminder, because of the undeserved kindness given to me from God

[[v45-15-16]]

^<<v45-15-16,16>>^ for me to be a public servant of Christ Jesus to the nations. I am engaging in the holy work of the good news of God, so that these nations might be an acceptable offering, sanctified with holy spirit.

[[v45-15-17]]

^<<v45-15-17,17>>^ So I have reason to exult in Christ Jesus over the things pertaining to God.

[[v45-15-18]]

^<<v45-15-18,18>>^ For I will not presume to speak about anything except what Christ has done through me in order for the nations to be obedient, by my word and deed,

[[v45-15-19]]

^<<v45-15-19,19>>^ with the power of signs and wonders,^&#42;1^ with the power of God’s spirit, so that from Jerusalem and in a circuit as far as Il·lyrʹi·cum I have thoroughly preached the good news about the Christ.

[NOTE]
====
. Or “portents.”
====

[[v45-15-20]]

^<<v45-15-20,20>>^ In this way, indeed, I made it my aim not to declare the good news where the name of Christ had already been made known, so as not to build on another man’s foundation;

[[v45-15-21]]

^<<v45-15-21,21>>^ but just as it is written: “Those who received no report about him will see, and those who have not heard will understand.”

[[v45-15-22]]

^<<v45-15-22,22>>^ This is also why I was many times hindered from coming to you.

[[v45-15-23]]

^<<v45-15-23,23>>^ But now I no longer have untouched territory in these regions, and for many^&#42;1^ years I have longed to come to you.

[NOTE]
====
. Or possibly, “some.”
====

[[v45-15-24]]

^<<v45-15-24,24>>^ Therefore, when I journey to Spain, I hope that I will see you and be accompanied partway there by you after I have first enjoyed your company for a time.

[[v45-15-25]]

^<<v45-15-25,25>>^ But now I am about to travel to Jerusalem to minister to the holy ones.

[[v45-15-26]]

^<<v45-15-26,26>>^ For those in Mac·e·doʹni·a and A·chaʹia have been pleased to share their things by a contribution to the poor among the holy ones in Jerusalem.

[[v45-15-27]]

^<<v45-15-27,27>>^ True, they have been pleased to do so, and indeed they were debtors to them; for if the nations have shared in their spiritual things, they also owe it to minister to them with their material things.

[[v45-15-28]]

^<<v45-15-28,28>>^ So after I have finished with this and have delivered this contribution^&#42;1^ securely to them, I will depart by way of you for Spain.

[NOTE]
====
. Lit., “fruit.”
====

[[v45-15-29]]

^<<v45-15-29,29>>^ Moreover, I know that when I do come to you, I will come with a full measure of blessing from Christ.

[[v45-15-30]]

^<<v45-15-30,30>>^ Now I urge you, brothers, through our Lord Jesus Christ and through the love of the spirit, that you exert yourselves with me in prayers to God for me,

[[v45-15-31]]

^<<v45-15-31,31>>^ that I may be rescued from the unbelievers in Ju·deʹa and that my ministry in behalf of Jerusalem may prove to be acceptable to the holy ones,

[[v45-15-32]]

^<<v45-15-32,32>>^ so that by God’s will I will come to you with joy and be refreshed together with you.

[[v45-15-33]]

^<<v45-15-33,33>>^ May the God who gives peace be with all of you. Amen.

'''

xref:045-romans/045-romans-014.adoc#v45-14-0[&#60; Capítulo Anterior] | <<v45-15-0,Topo>> | xref:045-romans/045-romans-016.adoc#v45-16-0[Próximo Capítulo &#62;]