include::./index.adoc[]

[[v45-1-0]]
=== To the Romans, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v45-1-1]]

^<<v45-1-1,1>>^ Paul, a slave of Christ Jesus and called to be an apostle, set apart for God’s good news,

[[v45-1-2]]

^<<v45-1-2,2>>^ which he promised beforehand through his prophets in the holy Scriptures,

[[v45-1-3]]

^<<v45-1-3,3>>^ concerning his Son, who came to be from the offspring^&#42;1^ of David according to the flesh,

[NOTE]
====
. Lit., “seed.”
====

[[v45-1-4]]

^<<v45-1-4,4>>^ but who with power was declared God’s Son according to the spirit of holiness by means of resurrection from the dead—yes, Jesus Christ our Lord.

[[v45-1-5]]

^<<v45-1-5,5>>^ Through him we received undeserved kindness and an apostleship with a view to obedience by faith among all the nations respecting his name,

[[v45-1-6]]

^<<v45-1-6,6>>^ among which nations you also have been called to belong to Jesus Christ—

[[v45-1-7]]

^<<v45-1-7,7>>^ to all those who are in Rome as God’s beloved ones, called to be holy ones:
May you have undeserved kindness and peace from God our Father and the Lord Jesus Christ.

[[v45-1-8]]

^<<v45-1-8,8>>^ First of all, I give thanks to my God through Jesus Christ concerning all of you, because your faith is talked about throughout the whole world.

[[v45-1-9]]

^<<v45-1-9,9>>^ For God, to whom I render sacred service with my spirit in connection with the good news about his Son, is my witness of how without ceasing I always mention you in my prayers,

[[v45-1-10]]

^<<v45-1-10,10>>^ begging that if at all possible I may now at last succeed in coming to you by God’s will.

[[v45-1-11]]

^<<v45-1-11,11>>^ For I am longing to see you, that I may impart some spiritual gift to you for you to be made firm;

[[v45-1-12]]

^<<v45-1-12,12>>^ or, rather, that we may have an interchange of encouragement by one another’s faith, both yours and mine.

[[v45-1-13]]

^<<v45-1-13,13>>^ But I do not want you to be unaware, brothers, that many times I have intended to come to you—but I have been prevented until now—in order that I might acquire some fruitage also among you just as among the rest of the nations.

[[v45-1-14]]

^<<v45-1-14,14>>^ Both to Greeks and to foreigners,^&#42;1^ both to wise and to senseless ones, I am a debtor;

[NOTE]
====
. Or “non-Greeks.” Lit., “barbarians.”
====

[[v45-1-15]]

^<<v45-1-15,15>>^ so I am eager to declare the good news also to you there in Rome.

[[v45-1-16]]

^<<v45-1-16,16>>^ For I am not ashamed of the good news; it is, in fact, God’s power for salvation to everyone having faith, to the Jew first and also to the Greek.

[[v45-1-17]]

^<<v45-1-17,17>>^ For in it God’s righteousness is being revealed by faith and for faith, just as it is written: “But the righteous one will live by reason of faith.”

[[v45-1-18]]

^<<v45-1-18,18>>^ For God’s wrath is being revealed from heaven against all ungodliness and unrighteousness of men who are suppressing the truth in an unrighteous way,

[[v45-1-19]]

^<<v45-1-19,19>>^ because what may be known about God is clearly evident among them, for God made it clear to them.

[[v45-1-20]]

^<<v45-1-20,20>>^ For his invisible qualities are clearly seen from the world’s creation onward, because they are perceived by the things made, even his eternal power and Godship, so that they are inexcusable.

[[v45-1-21]]

^<<v45-1-21,21>>^ For although they knew God, they did not glorify him as God nor did they thank him, but they became empty-headed in their reasonings and their senseless hearts became darkened.

[[v45-1-22]]

^<<v45-1-22,22>>^ Although claiming they were wise, they became foolish

[[v45-1-23]]

^<<v45-1-23,23>>^ and turned the glory of the incorruptible God into something like the image of corruptible man and birds and four-footed creatures and reptiles.^&#42;1^

[NOTE]
====
. Or “creeping things.”
====

[[v45-1-24]]

^<<v45-1-24,24>>^ Therefore, God, in keeping with the desires of their hearts, gave them up to uncleanness, so that their bodies might be dishonored among them.

[[v45-1-25]]

^<<v45-1-25,25>>^ They exchanged the truth of God for the lie and venerated^&#42;1^ and rendered sacred service to the creation rather than the Creator, who is praised forever. Amen.

[NOTE]
====
. Or “worshipped.”
====

[[v45-1-26]]

^<<v45-1-26,26>>^ That is why God gave them over to disgraceful sexual passion, for their females changed the natural use of themselves into one contrary to nature;

[[v45-1-27]]

^<<v45-1-27,27>>^ likewise also the males left the natural use of^&#42;1^ the female and became violently inflamed in their lust toward one another, males with males, working what is obscene and receiving in themselves the full penalty,^&#42;2^ which was due for their error.

[NOTE]
====
. Or “natural relations with.”
. Or “recompense.”
====

[[v45-1-28]]

^<<v45-1-28,28>>^ Just as they did not see fit to acknowledge God,^&#42;1^ God gave them over to a disapproved mental state, to do the things not fitting.

[NOTE]
====
. Or “they did not approve of holding God in accurate knowledge.”
====

[[v45-1-29]]

^<<v45-1-29,29>>^ And they were filled with all unrighteousness, wickedness, greed,^&#42;1^ and badness, being full of envy, murder, strife, deceit, and malice, being whisperers,^&#42;2^

[NOTE]
====
. Or “covetousness.”
. Or “gossipers.”
====

[[v45-1-30]]

^<<v45-1-30,30>>^ backbiters, haters of God, insolent, haughty, boastful, schemers of what is harmful,^&#42;1^ disobedient to parents,

[NOTE]
====
. Or “inventors of injurious things.”
====

[[v45-1-31]]

^<<v45-1-31,31>>^ without understanding, false to agreements, having no natural affection, and merciless.

[[v45-1-32]]

^<<v45-1-32,32>>^ Although these know full well the righteous decree of God—that those practicing such things are deserving of death—they not only keep on doing them but also approve of those practicing them.

'''

xref:044-acts/044-acts-028.adoc#v44-28-0[&#60; Capítulo Anterior] | <<v45-1-0,Topo>> | xref:045-romans/045-romans-002.adoc#v45-2-0[Próximo Capítulo &#62;]