include::./index.adoc[]

[[v45-2-0]]
=== To the Romans, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v45-2-1]]

^<<v45-2-1,1>>^ Therefore you are inexcusable, O man, whoever you are, if you judge; for when you judge another, you condemn yourself, because you who judge practice the same things.

[[v45-2-2]]

^<<v45-2-2,2>>^ Now we know that God’s judgment is in harmony with truth, against those who practice such things.

[[v45-2-3]]

^<<v45-2-3,3>>^ But do you suppose, O man, that while you judge those who practice such things and yet you do them, you will escape the judgment of God?

[[v45-2-4]]

^<<v45-2-4,4>>^ Or do you despise the riches of his kindness and forbearance^&#42;1^ and patience, because you do not know that God in his kindness is trying to lead you to repentance?

[NOTE]
====
. Or “tolerance.”
====

[[v45-2-5]]

^<<v45-2-5,5>>^ But according to your stubbornness and your unrepentant heart, you are storing up wrath for yourself on the day of wrath and of the revealing of God’s righteous judgment.

[[v45-2-6]]

^<<v45-2-6,6>>^ And he will pay back to each one according to his works:

[[v45-2-7]]

^<<v45-2-7,7>>^ everlasting life to those who are seeking glory and honor and incorruptibleness by endurance in work that is good;

[[v45-2-8]]

^<<v45-2-8,8>>^ however, for those who are contentious and who disobey the truth but obey unrighteousness, there will be wrath and anger.

[[v45-2-9]]

^<<v45-2-9,9>>^ There will be tribulation and distress on every person^&#42;1^ who works what is harmful, on the Jew first and also on the Greek;

[NOTE]
====
. Or “the soul of every man.”
====

[[v45-2-10]]

^<<v45-2-10,10>>^ but glory and honor and peace for everyone who works what is good, for the Jew first and also for the Greek.

[[v45-2-11]]

^<<v45-2-11,11>>^ For there is no partiality with God.

[[v45-2-12]]

^<<v45-2-12,12>>^ For all those who sinned without law will also perish without law; but all those who sinned under law will be judged by law.

[[v45-2-13]]

^<<v45-2-13,13>>^ For the hearers of law are not the ones righteous before God, but the doers of law will be declared righteous.

[[v45-2-14]]

^<<v45-2-14,14>>^ For when people of the nations, who do not have law, do by nature the things of the law, these people, although not having law, are a law to themselves.

[[v45-2-15]]

^<<v45-2-15,15>>^ They are the very ones who demonstrate the matter of the law to be written in their hearts, while their conscience is bearing witness with them, and by^&#42;1^ their own thoughts they are being accused or even excused.

[NOTE]
====
. Lit., “between.”
====

[[v45-2-16]]

^<<v45-2-16,16>>^ This will take place in the day when God through Christ Jesus judges the secret things of mankind, according to the good news I declare.

[[v45-2-17]]

^<<v45-2-17,17>>^ If, now, you are a Jew in name and rely on law and take pride in God,

[[v45-2-18]]

^<<v45-2-18,18>>^ and you know his will and approve of things that are excellent because you are instructed^&#42;1^ out of the Law,

[NOTE]
====
. Or “orally instructed.”
====

[[v45-2-19]]

^<<v45-2-19,19>>^ and you are convinced that you are a guide of the blind, a light for those in darkness,

[[v45-2-20]]

^<<v45-2-20,20>>^ a corrector of the unreasonable ones, a teacher of young children, and having the framework of the knowledge and of the truth in the Law—

[[v45-2-21]]

^<<v45-2-21,21>>^ do you, however, the one teaching someone else, not teach yourself? You, the one preaching, “Do not steal,” do you steal?

[[v45-2-22]]

^<<v45-2-22,22>>^ You, the one saying, “Do not commit adultery,” do you commit adultery? You, the one abhorring idols, do you rob temples?

[[v45-2-23]]

^<<v45-2-23,23>>^ You who take pride in law, do you dishonor God by your transgressing of the Law?

[[v45-2-24]]

^<<v45-2-24,24>>^ For “the name of God is being blasphemed among the nations because of you,” just as it is written.

[[v45-2-25]]

^<<v45-2-25,25>>^ Circumcision is, in fact, of benefit only if you practice law; but if you are a transgressor of law, your circumcision has become uncircumcision.

[[v45-2-26]]

^<<v45-2-26,26>>^ If, therefore, an uncircumcised person keeps the righteous requirements of the Law, his uncircumcision will be counted as circumcision, will it not?

[[v45-2-27]]

^<<v45-2-27,27>>^ And the physically uncircumcised person will, by carrying out the Law, judge you who are a transgressor of law despite having its written code and circumcision.

[[v45-2-28]]

^<<v45-2-28,28>>^ For he is not a Jew who is one on the outside, nor is circumcision something on the outside, on the flesh.

[[v45-2-29]]

^<<v45-2-29,29>>^ But he is a Jew who is one on the inside, and his circumcision is that of the heart by spirit and not by a written code. That person’s praise comes from God, not from people.

'''

xref:045-romans/045-romans-001.adoc#v45-1-0[&#60; Capítulo Anterior] | <<v45-2-0,Topo>> | xref:045-romans/045-romans-003.adoc#v45-3-0[Próximo Capítulo &#62;]