include::./index.adoc[]

[[v45-11-0]]
=== To the Romans, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v45-11-1]]

^<<v45-11-1,1>>^ I ask, then, God did not reject his people, did he? By no means! For I too am an Israelite, of the offspring^&#42;1^ of Abraham, from the tribe of Benjamin.

[NOTE]
====
. Lit., “seed.”
====

[[v45-11-2]]

^<<v45-11-2,2>>^ God did not reject his people, whom he first recognized. Do you not know what the scripture says in connection with E·liʹjah, as he pleads with God against Israel?

[[v45-11-3]]

^<<v45-11-3,3>>^ “Jehovah,^&#42;1^ they have killed your prophets, they have dug up your altars, and I alone am left, and now they are trying to take my life.”^&#42;2^

[NOTE]
====
. See App. A5.
. Or “soul.”
====

[[v45-11-4]]

^<<v45-11-4,4>>^ Yet, what does the divine pronouncement say to him? “I have left for myself 7,000 men who have not bent the knee to Baʹal.”

[[v45-11-5]]

^<<v45-11-5,5>>^ So in the same way, at the present time also, there is a remnant according to a choosing through undeserved kindness.

[[v45-11-6]]

^<<v45-11-6,6>>^ Now if it is by undeserved kindness, it is no longer through works; otherwise, the undeserved kindness would no longer be undeserved kindness.

[[v45-11-7]]

^<<v45-11-7,7>>^ What, then? The very thing Israel is earnestly seeking he did not obtain, but the ones chosen obtained it. The rest had their senses dulled,

[[v45-11-8]]

^<<v45-11-8,8>>^ just as it is written: “God has given them a spirit of deep sleep, eyes that do not see and ears that do not hear, down to this very day.”

[[v45-11-9]]

^<<v45-11-9,9>>^ Also, David says: “Let their table become a snare and a trap and a stumbling block and a retribution for them.

[[v45-11-10]]

^<<v45-11-10,10>>^ Let their eyes become darkened so that they cannot see, and always make them bend their backs.”

[[v45-11-11]]

^<<v45-11-11,11>>^ So I ask, They did not stumble and fall completely, did they? Certainly not! But by their false step, there is salvation to people of the nations, to incite them to jealousy.

[[v45-11-12]]

^<<v45-11-12,12>>^ Now if their false step means riches to the world and their decrease means riches to people of the nations, how much more will their full number mean!

[[v45-11-13]]

^<<v45-11-13,13>>^ Now I speak to you who are people of the nations. Seeing that I am an apostle to the nations, I glorify^&#42;1^ my ministry

[NOTE]
====
. Or “magnify.”
====

[[v45-11-14]]

^<<v45-11-14,14>>^ to see if I may in some way incite my own people^&#42;1^ to jealousy and save some from among them.

[NOTE]
====
. Lit., “my flesh.”
====

[[v45-11-15]]

^<<v45-11-15,15>>^ For if their being cast away means reconciliation for the world, what will the acceptance of them mean but life from the dead?

[[v45-11-16]]

^<<v45-11-16,16>>^ Further, if the part of the dough taken as firstfruits is holy, the entire batch is also holy; and if the root is holy, the branches are also.

[[v45-11-17]]

^<<v45-11-17,17>>^ However, if some of the branches were broken off and you, although being a wild olive, were grafted in among them and became a sharer of the richness of the olive’s root,

[[v45-11-18]]

^<<v45-11-18,18>>^ do not be arrogant toward^&#42;1^ the branches. If, though, you are arrogant toward^&#42;2^ them, remember that you do not bear the root, but the root bears you.

[NOTE]
====
. Or “boast against.”
. Or “boast against.”
====

[[v45-11-19]]

^<<v45-11-19,19>>^ You will say, then: “Branches were broken off so that I might be grafted in.”

[[v45-11-20]]

^<<v45-11-20,20>>^ That is true! For their lack of faith, they were broken off, but you are standing by faith. Do not be haughty, but be in fear.

[[v45-11-21]]

^<<v45-11-21,21>>^ For if God did not spare the natural branches, neither will he spare you.

[[v45-11-22]]

^<<v45-11-22,22>>^ Consider, therefore, God’s kindness and severity. There is severity toward those who fell, but toward you there is God’s kindness, provided you remain in his kindness; otherwise, you too will be lopped off.

[[v45-11-23]]

^<<v45-11-23,23>>^ And they also, if they do not remain in their lack of faith, will be grafted in, for God is able to graft them back in.

[[v45-11-24]]

^<<v45-11-24,24>>^ For if you were cut out of the olive tree that is wild by nature and were grafted contrary to nature into the garden olive tree, how much more will these who are natural branches be grafted back into their own olive tree!

[[v45-11-25]]

^<<v45-11-25,25>>^ For I do not want you to be unaware of this sacred secret, brothers, so that you do not become wise in your own eyes: A partial dulling of senses has come upon Israel until the full number of people of the nations has come in,

[[v45-11-26]]

^<<v45-11-26,26>>^ and in this manner all Israel will be saved. Just as it is written: “The deliverer^&#42;1^ will come out of Zion and turn away ungodly practices from Jacob.

[NOTE]
====
. Or “savior.”
====

[[v45-11-27]]

^<<v45-11-27,27>>^ And this is my covenant with them, when I take their sins away.”

[[v45-11-28]]

^<<v45-11-28,28>>^ True, with respect to the good news, they are enemies for your sakes; but with respect to God’s choosing, they are beloved for the sake of their forefathers.

[[v45-11-29]]

^<<v45-11-29,29>>^ For the gifts and the calling of God are not things he will regret.

[[v45-11-30]]

^<<v45-11-30,30>>^ For just as you were once disobedient to God but have now been shown mercy because of their disobedience,

[[v45-11-31]]

^<<v45-11-31,31>>^ so also these now have been disobedient with mercy resulting to you, so that they themselves may also now be shown mercy.

[[v45-11-32]]

^<<v45-11-32,32>>^ For God has confined all of them together in disobedience so that he might show all of them mercy.

[[v45-11-33]]

^<<v45-11-33,33>>^ O the depth of God’s riches and wisdom and knowledge! How unsearchable his judgments are and beyond tracing out his ways are!

[[v45-11-34]]

^<<v45-11-34,34>>^ For “who has come to know Jehovah’s^&#42;1^ mind, or who has become his adviser?”

[NOTE]
====
. See App. A5.
====

[[v45-11-35]]

^<<v45-11-35,35>>^ Or, “who has first given to him, so that it must be repaid to him?”

[[v45-11-36]]

^<<v45-11-36,36>>^ Because from him and by him and for him are all things. To him be the glory forever. Amen.

'''

xref:045-romans/045-romans-010.adoc#v45-10-0[&#60; Capítulo Anterior] | <<v45-11-0,Topo>> | xref:045-romans/045-romans-012.adoc#v45-12-0[Próximo Capítulo &#62;]