include::./index.adoc[]

[[v45-16-0]]
=== To the Romans, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v45-16-1]]

^<<v45-16-1,1>>^ I am introducing^&#42;1^ to you Phoeʹbe, our sister, who is a minister of the congregation that is in Cenʹchre·ae,

[NOTE]
====
. Or “I recommend.”
====

[[v45-16-2]]

^<<v45-16-2,2>>^ so that you may welcome her in the Lord in a way worthy of the holy ones and give her whatever help she may need, for she herself also proved to be a defender of many, including me.

[[v45-16-3]]

^<<v45-16-3,3>>^ Give my greetings to Prisʹca and Aqʹui·la, my fellow workers in Christ Jesus,

[[v45-16-4]]

^<<v45-16-4,4>>^ who have risked their own necks for me^&#42;1^ and to whom not only I but also all the congregations of the nations give thanks.

[NOTE]
====
. Or “my soul.”
====

[[v45-16-5]]

^<<v45-16-5,5>>^ Also greet the congregation that is in their house. Greet my beloved E·paeʹne·tus, who is a firstfruits of Asia for Christ.

[[v45-16-6]]

^<<v45-16-6,6>>^ Greet Mary, who has worked hard for you.

[[v45-16-7]]

^<<v45-16-7,7>>^ Greet An·dronʹi·cus and Juʹni·as, my relatives and fellow prisoners, who are men well-known to the apostles and who have been in union with Christ longer than I have.

[[v45-16-8]]

^<<v45-16-8,8>>^ Give my greetings to Am·pli·aʹtus, my beloved in the Lord.

[[v45-16-9]]

^<<v45-16-9,9>>^ Greet Ur·baʹnus, our fellow worker in Christ, and my beloved Staʹchys.

[[v45-16-10]]

^<<v45-16-10,10>>^ Greet A·pelʹles, the approved one in Christ. Greet those from the household of A·ris·tobʹu·lus.

[[v45-16-11]]

^<<v45-16-11,11>>^ Greet He·roʹdi·on, my relative. Greet those from the household of Nar·cisʹsus who are in the Lord.

[[v45-16-12]]

^<<v45-16-12,12>>^ Greet Try·phaeʹna and Try·phoʹsa, women who are working hard in the Lord. Greet Perʹsis, our beloved one, for she has worked hard in the Lord.

[[v45-16-13]]

^<<v45-16-13,13>>^ Greet Ruʹfus, the chosen one in the Lord, and his mother and mine.

[[v45-16-14]]

^<<v45-16-14,14>>^ Greet A·synʹcri·tus, Phleʹgon, Herʹmes, Patʹro·bas, Herʹmas, and the brothers with them.

[[v45-16-15]]

^<<v45-16-15,15>>^ Greet Phi·lolʹo·gus and Julia, Neʹreus and his sister, and O·lymʹpas, and all the holy ones with them.

[[v45-16-16]]

^<<v45-16-16,16>>^ Greet one another with a holy kiss. All the congregations of the Christ greet you.

[[v45-16-17]]

^<<v45-16-17,17>>^ Now I urge you, brothers, to keep your eye on those who create divisions and causes for stumbling contrary to the teaching that you have learned, and avoid them.

[[v45-16-18]]

^<<v45-16-18,18>>^ For men of that sort are slaves, not of our Lord Christ, but of their own appetites,^&#42;1^ and by smooth talk and flattering speech they seduce the hearts of unsuspecting ones.

[NOTE]
====
. Or “bellies.”
====

[[v45-16-19]]

^<<v45-16-19,19>>^ Your obedience has come to the notice of all, and so I rejoice over you. But I want you to be wise as to what is good, but innocent as to what is evil.

[[v45-16-20]]

^<<v45-16-20,20>>^ For his part, the God who gives peace will crush Satan under your feet shortly. May the undeserved kindness of our Lord Jesus be with you.

[[v45-16-21]]

^<<v45-16-21,21>>^ Timothy, my fellow worker, greets you, and so do Lucius, Jaʹson, and So·sipʹa·ter, my relatives.

[[v45-16-22]]

^<<v45-16-22,22>>^ I, Terʹtius, who have done the writing of this letter, greet you in the Lord.

[[v45-16-23]]

^<<v45-16-23,23>>^ Gaʹius, host to me and to all the congregation, greets you. E·rasʹtus, the city treasurer,^&#42;1^ greets you, and so does Quarʹtus, his brother.

[NOTE]
====
. Or “steward.”
====

[[v45-16-24]]

^<<v45-16-24,24>>^ ^&#42;1^ ——

[NOTE]
====
. See App. A3.
====

[[v45-16-25]]

^<<v45-16-25,25>>^ Now to Him who can make you firm according to the good news I declare and the preaching of Jesus Christ, according to the revelation of the sacred secret that has been kept in silence for long-lasting times

[[v45-16-26]]

^<<v45-16-26,26>>^ but has now been made manifest^&#42;1^ and has been made known through the prophetic Scriptures among all the nations according to the command of the everlasting God to promote obedience by faith;

[NOTE]
====
. Or “revealed.”
====

[[v45-16-27]]

^<<v45-16-27,27>>^ to God, who alone is wise, be the glory through Jesus Christ forever. Amen.

'''

xref:045-romans/045-romans-015.adoc#v45-15-0[&#60; Capítulo Anterior] | <<v45-16-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-001.adoc#v46-1-0[Próximo Capítulo &#62;]