include::./index.adoc[]

[[v45-14-0]]
=== To the Romans, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v45-14-1]]

^<<v45-14-1,1>>^ Welcome the man having weaknesses in his faith, but do not pass judgment on differing opinions.^&#42;1^

[NOTE]
====
. Or possibly, “inward questionings.”
====

[[v45-14-2]]

^<<v45-14-2,2>>^ One man has faith to eat everything, but the man who is weak eats only vegetables.

[[v45-14-3]]

^<<v45-14-3,3>>^ Let the one eating not look down on the one not eating, and let the one not eating not judge the one eating, for God has welcomed him.

[[v45-14-4]]

^<<v45-14-4,4>>^ Who are you to judge the servant of another? To his own master he stands or falls. Indeed, he will be made to stand, for Jehovah^&#42;1^ can make him stand.

[NOTE]
====
. See App. A5.
====

[[v45-14-5]]

^<<v45-14-5,5>>^ One man judges one day as above another; another judges one day the same as all others; let each one be fully convinced in his own mind.

[[v45-14-6]]

^<<v45-14-6,6>>^ The one who observes the day observes it to Jehovah.^&#42;1^ Also, the one who eats, eats to Jehovah,^&#42;2^ for he gives thanks to God; and the one who does not eat does not eat to Jehovah,^&#42;3^ and yet gives thanks to God.

[NOTE]
====
. See App. A5.
. See App. A5.
. See App. A5.
====

[[v45-14-7]]

^<<v45-14-7,7>>^ Not one of us, in fact, lives with regard to himself only, and no one dies with regard to himself only.

[[v45-14-8]]

^<<v45-14-8,8>>^ For if we live, we live to Jehovah,^&#42;1^ and if we die, we die to Jehovah.^&#42;2^ So both if we live and if we die, we belong to Jehovah.^&#42;3^

[NOTE]
====
. See App. A5.
. See App. A5.
. See App. A5.
====

[[v45-14-9]]

^<<v45-14-9,9>>^ For to this end Christ died and came to life again, so that he might be Lord over both the dead and the living.

[[v45-14-10]]

^<<v45-14-10,10>>^ But why do you judge your brother? Or why do you also look down on your brother? For we will all stand before the judgment seat of God.

[[v45-14-11]]

^<<v45-14-11,11>>^ For it is written: “‘As surely as I live,’ says Jehovah,^&#42;1^ ‘to me every knee will bend, and every tongue will make open acknowledgment to God.’”

[NOTE]
====
. See App. A5.
====

[[v45-14-12]]

^<<v45-14-12,12>>^ So, then, each of us will render an account for himself to God.

[[v45-14-13]]

^<<v45-14-13,13>>^ Therefore, let us not judge one another any longer but, rather, be determined not to put a stumbling block or an obstacle before a brother.

[[v45-14-14]]

^<<v45-14-14,14>>^ I know and am convinced in the Lord Jesus that nothing is unclean in itself; only where a man considers something to be unclean, to him it is unclean.

[[v45-14-15]]

^<<v45-14-15,15>>^ For if your brother is being offended because of food, you are no longer walking according to love. Do not by your food ruin^&#42;1^ that one for whom Christ died.

[NOTE]
====
. Or “destroy.”
====

[[v45-14-16]]

^<<v45-14-16,16>>^ Therefore, do not let the good you do be spoken of as bad.

[[v45-14-17]]

^<<v45-14-17,17>>^ For the Kingdom of God does not mean eating and drinking, but means righteousness and peace and joy with holy spirit.

[[v45-14-18]]

^<<v45-14-18,18>>^ For whoever slaves for Christ in this way is acceptable to God and has approval with men.

[[v45-14-19]]

^<<v45-14-19,19>>^ So, then, let us pursue the things making for peace and the things that build one another up.

[[v45-14-20]]

^<<v45-14-20,20>>^ Stop tearing down the work of God just for the sake of food. True, all things are clean, but it is detrimental for^&#42;1^ a man to eat when it will cause stumbling.

[NOTE]
====
. Or “wrong for.”
====

[[v45-14-21]]

^<<v45-14-21,21>>^ It is best not to eat meat or drink wine or do anything over which your brother stumbles.

[[v45-14-22]]

^<<v45-14-22,22>>^ The faith that you have, keep it to yourself before God. Happy is the man who does not judge himself by what he approves.

[[v45-14-23]]

^<<v45-14-23,23>>^ But if he has doubts, he is already condemned if he eats, because he does not eat based on faith. Indeed, everything that is not based on faith is sin.

'''

xref:045-romans/045-romans-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:045-romans/045-romans-015.adoc#v45-15-0[Próximo Capítulo &#62;]