include::./index.adoc[]

[[v45-8-0]]
=== To the Romans, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v45-8-1]]

^<<v45-8-1,1>>^ Therefore, those in union with Christ Jesus have no condemnation.

[[v45-8-2]]

^<<v45-8-2,2>>^ For the law of the spirit that gives life in union with Christ Jesus has set you free from the law of sin and of death.

[[v45-8-3]]

^<<v45-8-3,3>>^ What the Law was incapable of doing because it was weak through the flesh, God did by sending his own Son in the likeness of sinful flesh and concerning sin, condemning sin in the flesh,

[[v45-8-4]]

^<<v45-8-4,4>>^ so that the righteous requirement of the Law might be fulfilled in us who walk, not according to the flesh, but according to the spirit.

[[v45-8-5]]

^<<v45-8-5,5>>^ For those who live according to the flesh set their minds on the things of the flesh, but those who live according to the spirit, on the things of the spirit.

[[v45-8-6]]

^<<v45-8-6,6>>^ For setting the mind on the flesh means death, but setting the mind on the spirit means life and peace;

[[v45-8-7]]

^<<v45-8-7,7>>^ because setting the mind on the flesh means enmity with God, for it is not in subjection to the law of God, nor, in fact, can it be.

[[v45-8-8]]

^<<v45-8-8,8>>^ So those who are in harmony with the flesh cannot please God.

[[v45-8-9]]

^<<v45-8-9,9>>^ However, you are in harmony, not with the flesh, but with the spirit, if God’s spirit truly dwells in you. But if anyone does not have Christ’s spirit, this person does not belong to him.

[[v45-8-10]]

^<<v45-8-10,10>>^ But if Christ is in union with you, the body is dead because of sin, but the spirit is life because of righteousness.

[[v45-8-11]]

^<<v45-8-11,11>>^ If, now, the spirit of him who raised up Jesus from the dead dwells in you, the one who raised up Christ Jesus from the dead will also make your mortal bodies alive through his spirit that resides in you.

[[v45-8-12]]

^<<v45-8-12,12>>^ So, then, brothers, we are under obligation, not to the flesh to live according to the flesh;

[[v45-8-13]]

^<<v45-8-13,13>>^ for if you live according to the flesh, you are sure to die; but if you put the practices of the body to death by the spirit, you will live.

[[v45-8-14]]

^<<v45-8-14,14>>^ For all who are led by God’s spirit are indeed God’s sons.

[[v45-8-15]]

^<<v45-8-15,15>>^ For you did not receive a spirit of slavery causing fear again, but you received a spirit of adoption as sons, by which spirit we cry out: “Abba,^&#42;1^ Father!”

[NOTE]
====
. A Hebrew or an Aramaic word meaning “O Father!”
====

[[v45-8-16]]

^<<v45-8-16,16>>^ The spirit itself bears witness with our spirit that we are God’s children.

[[v45-8-17]]

^<<v45-8-17,17>>^ If, then, we are children, we are also heirs—heirs indeed of God, but joint heirs with Christ—provided we suffer together so that we may also be glorified together.

[[v45-8-18]]

^<<v45-8-18,18>>^ For I consider that the sufferings of the present time do not amount to anything in comparison with the glory that is going to be revealed in us.

[[v45-8-19]]

^<<v45-8-19,19>>^ For the creation is waiting with eager expectation for the revealing of the sons of God.

[[v45-8-20]]

^<<v45-8-20,20>>^ For the creation was subjected to futility, not by its own will, but through the one who subjected it, on the basis of hope

[[v45-8-21]]

^<<v45-8-21,21>>^ that the creation itself will also be set free from enslavement to corruption and have the glorious freedom of the children of God.

[[v45-8-22]]

^<<v45-8-22,22>>^ For we know that all creation keeps on groaning together and being in pain together until now.

[[v45-8-23]]

^<<v45-8-23,23>>^ Not only that, but we ourselves also who have the firstfruits, namely, the spirit, yes, we ourselves groan within ourselves while we are earnestly waiting for adoption as sons, the release from our bodies by ransom.

[[v45-8-24]]

^<<v45-8-24,24>>^ For we were saved in this hope; but hope that is seen is not hope, for when a man sees a thing, does he hope for it?

[[v45-8-25]]

^<<v45-8-25,25>>^ But if we hope for what we do not see, we keep eagerly waiting for it with endurance.

[[v45-8-26]]

^<<v45-8-26,26>>^ In like manner, the spirit also joins in with help for our weakness; for the problem is that we do not know what we should pray for as we need to, but the spirit itself pleads for us with unuttered^&#42;1^ groanings.

[NOTE]
====
. Or “unspoken.”
====

[[v45-8-27]]

^<<v45-8-27,27>>^ But the one who searches the hearts knows what the meaning of the spirit is, because it is pleading in harmony with God for the holy ones.

[[v45-8-28]]

^<<v45-8-28,28>>^ We know that God makes all his works cooperate together for the good of those who love God, those who are the ones called according to his purpose;

[[v45-8-29]]

^<<v45-8-29,29>>^ because those whom he gave his first recognition he also foreordained to be patterned after the image of his Son, so that he might be the firstborn among many brothers.

[[v45-8-30]]

^<<v45-8-30,30>>^ Moreover, those whom he foreordained are the ones he also called; and those whom he called are the ones he also declared to be righteous. Finally those whom he declared righteous are the ones he also glorified.

[[v45-8-31]]

^<<v45-8-31,31>>^ What, then, are we to say about these things? If God is for us, who will be against us?

[[v45-8-32]]

^<<v45-8-32,32>>^ Since he did not even spare his own Son but handed him over for us all, will he not also, along with him, kindly give us all other things?

[[v45-8-33]]

^<<v45-8-33,33>>^ Who will file accusation against God’s chosen ones? God is the One who declares them righteous.

[[v45-8-34]]

^<<v45-8-34,34>>^ Who will condemn them? Christ Jesus is the one who died, yes, more than that, the one who was raised up, who is at the right hand of God and who also pleads for us.

[[v45-8-35]]

^<<v45-8-35,35>>^ Who will separate us from the love of the Christ? Will tribulation or distress or persecution or hunger or nakedness or danger or sword?

[[v45-8-36]]

^<<v45-8-36,36>>^ Just as it is written: “For your sake we are being put to death all day long; we have been accounted as sheep for slaughtering.”

[[v45-8-37]]

^<<v45-8-37,37>>^ On the contrary, in all these things we are coming off completely victorious through the one who loved us.

[[v45-8-38]]

^<<v45-8-38,38>>^ For I am convinced that neither death nor life nor angels nor governments nor things now here nor things to come nor powers

[[v45-8-39]]

^<<v45-8-39,39>>^ nor height nor depth nor any other creation will be able to separate us from God’s love that is in Christ Jesus our Lord.

'''

xref:045-romans/045-romans-007.adoc#v45-7-0[&#60; Capítulo Anterior] | <<v45-8-0,Topo>> | xref:045-romans/045-romans-009.adoc#v45-9-0[Próximo Capítulo &#62;]