include::./index.adoc[]

[[v45-10-0]]
=== To the Romans, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v45-10-1]]

^<<v45-10-1,1>>^ Brothers, the goodwill of my heart and my supplication to God for them are indeed for their salvation.

[[v45-10-2]]

^<<v45-10-2,2>>^ For I bear them witness that they have a zeal for God, but not according to accurate knowledge.

[[v45-10-3]]

^<<v45-10-3,3>>^ For because of not knowing the righteousness of God but seeking to establish their own, they did not subject themselves to the righteousness of God.

[[v45-10-4]]

^<<v45-10-4,4>>^ For Christ is the end of the Law, so that everyone exercising faith may have righteousness.

[[v45-10-5]]

^<<v45-10-5,5>>^ For Moses writes about the righteousness that is by the Law: “The man who does these things will live by means of them.”

[[v45-10-6]]

^<<v45-10-6,6>>^ But the righteousness resulting from faith says: “Do not say in your heart, ‘Who will ascend into heaven?’ that is, to bring Christ down,

[[v45-10-7]]

^<<v45-10-7,7>>^ or, ‘Who will descend into the abyss?’ that is, to bring Christ up from the dead.”

[[v45-10-8]]

^<<v45-10-8,8>>^ But what does it say? “The word is near you, in your own mouth and in your own heart”; that is, “the word” of faith, which we are preaching.

[[v45-10-9]]

^<<v45-10-9,9>>^ For if you publicly declare with your mouth that Jesus is Lord, and exercise faith in your heart that God raised him up from the dead, you will be saved.

[[v45-10-10]]

^<<v45-10-10,10>>^ For with the heart one exercises faith for righteousness, but with the mouth one makes public declaration for salvation.

[[v45-10-11]]

^<<v45-10-11,11>>^ For the scripture says: “No one who rests his faith on him will be disappointed.”

[[v45-10-12]]

^<<v45-10-12,12>>^ For there is no distinction between Jew and Greek. There is the same Lord over all, who is rich^&#42;1^ toward all those calling on him.

[NOTE]
====
. Or “generous.”
====

[[v45-10-13]]

^<<v45-10-13,13>>^ For “everyone who calls on the name of Jehovah^&#42;1^ will be saved.”

[NOTE]
====
. See App. A5.
====

[[v45-10-14]]

^<<v45-10-14,14>>^ However, how will they call on him if they have not put faith in him? How, in turn, will they put faith in him about whom they have not heard? How, in turn, will they hear without someone to preach?

[[v45-10-15]]

^<<v45-10-15,15>>^ How, in turn, will they preach unless they have been sent out? Just as it is written: “How beautiful are the feet of those who declare good news of good things!”

[[v45-10-16]]

^<<v45-10-16,16>>^ Nevertheless, they did not all obey the good news. For Isaiah says: “Jehovah,^&#42;1^ who has put faith in the thing heard from us?”^&#42;2^

[NOTE]
====
. See App. A5.
. Or “in our report?”
====

[[v45-10-17]]

^<<v45-10-17,17>>^ So faith follows the thing heard. In turn, what is heard is through the word about Christ.

[[v45-10-18]]

^<<v45-10-18,18>>^ But I ask, They did not fail to hear, did they? Why, in fact, “into all the earth their sound went out, and to the ends of the inhabited earth their message.”

[[v45-10-19]]

^<<v45-10-19,19>>^ But I ask, Israel did not fail to know, did they? First Moses says: “I will incite you to jealousy through that which is not a nation; I will incite you to violent anger through a foolish nation.”

[[v45-10-20]]

^<<v45-10-20,20>>^ But Isaiah becomes very bold and says: “I was found by those who were not seeking me; I became known to those who were not asking for me.”

[[v45-10-21]]

^<<v45-10-21,21>>^ But he says regarding Israel: “All day long I have spread out my hands toward a disobedient and obstinate people.”

'''

xref:045-romans/045-romans-009.adoc#v45-9-0[&#60; Capítulo Anterior] | <<v45-10-0,Topo>> | xref:045-romans/045-romans-011.adoc#v45-11-0[Próximo Capítulo &#62;]