include::./index.adoc[]

[[v51-4-0]]
=== Letter to the Colossians, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v51-4-1]]

^<<v51-4-1,1>>^ You masters, treat your slaves in a righteous and fair way, knowing that you also have a Master in heaven.

[[v51-4-2]]

^<<v51-4-2,2>>^ Persevere in prayer, remaining awake in it with thanksgiving.

[[v51-4-3]]

^<<v51-4-3,3>>^ At the same time, pray also for us, that God may open a door for the word so that we can declare the sacred secret about the Christ, for which I am in prison bonds,

[[v51-4-4]]

^<<v51-4-4,4>>^ and that I may proclaim it as clearly as I ought to.

[[v51-4-5]]

^<<v51-4-5,5>>^ Go on walking in wisdom toward those on the outside, making the best use of your time.^&#42;1^

[NOTE]
====
. Lit., “buying out the appointed time.”
====

[[v51-4-6]]

^<<v51-4-6,6>>^ Let your words always be gracious, seasoned with salt, so that you will know how you should answer each person.

[[v51-4-7]]

^<<v51-4-7,7>>^ Tychʹi·cus, my beloved brother and faithful minister and fellow slave in the Lord, will tell you all the news about me.

[[v51-4-8]]

^<<v51-4-8,8>>^ I am sending him to you so that you will know how we are and that he may comfort your hearts.

[[v51-4-9]]

^<<v51-4-9,9>>^ He is coming along with O·nesʹi·mus, my faithful and beloved brother, who is from among you; they will tell you all the things happening here.

[[v51-4-10]]

^<<v51-4-10,10>>^ Ar·is·tarʹchus, my fellow captive, sends you his greetings, and so does Mark, the cousin of Barʹna·bas (concerning whom you received instructions to welcome him if he comes to you),

[[v51-4-11]]

^<<v51-4-11,11>>^ and Jesus who is called Justus, who are of those circumcised. Only these are my fellow workers for the Kingdom of God, and they have become a source of great comfort^&#42;1^ to me.

[NOTE]
====
. Or “a strengthening aid.”
====

[[v51-4-12]]

^<<v51-4-12,12>>^ Epʹa·phras, a slave of Christ Jesus who is from among you, sends you his greetings. He is always exerting himself in your behalf in his prayers, so that you may finally stand complete and with firm conviction in all the will of God.

[[v51-4-13]]

^<<v51-4-13,13>>^ For I bear him witness that he makes great efforts in your behalf and in behalf of those in La·o·di·ceʹa and Hi·e·rapʹo·lis.

[[v51-4-14]]

^<<v51-4-14,14>>^ Luke, the beloved physician, sends you his greetings, and so does Deʹmas.

[[v51-4-15]]

^<<v51-4-15,15>>^ Give my greetings to the brothers in La·o·di·ceʹa and to Nymʹpha and to the congregation at her house.

[[v51-4-16]]

^<<v51-4-16,16>>^ And when this letter has been read among you, arrange for it also to be read in the congregation of the La·o·di·ceʹans and for you also to read the one from La·o·di·ceʹa.

[[v51-4-17]]

^<<v51-4-17,17>>^ Also, tell Ar·chipʹpus: “Pay attention to the ministry that you accepted in the Lord, in order to fulfill it.”

[[v51-4-18]]

^<<v51-4-18,18>>^ Here is my greeting, Paul’s, in my own hand. Keep my prison bonds in mind. The undeserved kindness be with you.

'''

xref:051-colossians/051-colossians-003.adoc#v51-3-0[&#60; Capítulo Anterior] | <<v51-4-0,Topo>> | xref:052-1-thessalonians/052-1-thessalonians-001.adoc#v52-1-0[Próximo Capítulo &#62;]