include::./index.adoc[]

[[v51-1-0]]
=== Letter to the Colossians, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v51-1-1]]

^<<v51-1-1,1>>^ Paul, an apostle of Christ Jesus through God’s will, and Timothy our brother,

[[v51-1-2]]

^<<v51-1-2,2>>^ to the holy ones and faithful brothers in union with Christ at Co·losʹsae:
May you have undeserved kindness and peace from God our Father.

[[v51-1-3]]

^<<v51-1-3,3>>^ We always thank God, the Father of our Lord Jesus Christ, when we pray for you,

[[v51-1-4]]

^<<v51-1-4,4>>^ since we heard of your faith in Christ Jesus and the love you have for all the holy ones

[[v51-1-5]]

^<<v51-1-5,5>>^ because of the hope that is being reserved for you in the heavens. You previously heard about this hope through the message of truth of the good news

[[v51-1-6]]

^<<v51-1-6,6>>^ that has come to you. Just as the good news is bearing fruit and increasing in all the world, so it is also doing among you from the day you heard and accurately knew the undeserved kindness of God in truth.

[[v51-1-7]]

^<<v51-1-7,7>>^ That is what you have learned from our beloved fellow slave Epʹa·phras, who is a faithful minister of the Christ on our behalf.

[[v51-1-8]]

^<<v51-1-8,8>>^ He also made known to us your love in a spiritual way.^&#42;1^

[NOTE]
====
. Lit., “in spirit.”
====

[[v51-1-9]]

^<<v51-1-9,9>>^ That is also why from the day we heard of it, we have never stopped praying for you and asking that you may be filled with the accurate knowledge of his will in all wisdom and spiritual comprehension,

[[v51-1-10]]

^<<v51-1-10,10>>^ so as to walk worthily of Jehovah^&#42;1^ in order to please him fully as you go on bearing fruit in every good work and increasing in the accurate knowledge of God;

[NOTE]
====
. See App. A5.
====

[[v51-1-11]]

^<<v51-1-11,11>>^ and may you be strengthened with all power according to his glorious might so that you may endure fully with patience and joy,

[[v51-1-12]]

^<<v51-1-12,12>>^ as you thank the Father, who made you qualify to share in the inheritance of the holy ones in the light.

[[v51-1-13]]

^<<v51-1-13,13>>^ He rescued us from the authority of the darkness and transferred us into the kingdom of his beloved Son,

[[v51-1-14]]

^<<v51-1-14,14>>^ by means of whom we have our release by ransom, the forgiveness of our sins.

[[v51-1-15]]

^<<v51-1-15,15>>^ He is the image of the invisible God, the firstborn of all creation;

[[v51-1-16]]

^<<v51-1-16,16>>^ because by means of him all other things were created in the heavens and on the earth, the things visible and the things invisible, whether they are thrones or lordships or governments or authorities. All other things have been created through him and for him.

[[v51-1-17]]

^<<v51-1-17,17>>^ Also, he is before all other things, and by means of him all other things were made to exist,

[[v51-1-18]]

^<<v51-1-18,18>>^ and he is the head of the body, the congregation. He is the beginning, the firstborn from the dead, so that he might become the one who is first in all things;

[[v51-1-19]]

^<<v51-1-19,19>>^ because God was pleased to have all fullness to dwell in him,

[[v51-1-20]]

^<<v51-1-20,20>>^ and through him to reconcile to himself all other things by making peace through the blood he shed on the torture stake,^&#42;1^ whether the things on the earth or the things in the heavens.

[NOTE]
====
. See Glossary.
====

[[v51-1-21]]

^<<v51-1-21,21>>^ Indeed, you who were once alienated and enemies because your minds were on the works that were wicked,

[[v51-1-22]]

^<<v51-1-22,22>>^ he has now reconciled by means of that one’s fleshly body through his death, in order to present you holy and unblemished and open to no accusation before him—

[[v51-1-23]]

^<<v51-1-23,23>>^ provided, of course, that you continue in the faith, established on the foundation and steadfast, not being shifted away from the hope of that good news that you heard and that was preached in all creation under heaven. Of this good news I, Paul, became a minister.

[[v51-1-24]]

^<<v51-1-24,24>>^ I am now rejoicing in my sufferings for your sake, and I am undergoing the tribulations of the Christ that are yet lacking in my flesh in behalf of his body, which is the congregation.

[[v51-1-25]]

^<<v51-1-25,25>>^ I became a minister of this congregation in accord with the stewardship from God that was given to me in your behalf to preach the word of God fully,

[[v51-1-26]]

^<<v51-1-26,26>>^ the sacred secret that was hidden from the past systems of things^&#42;1^ and from the past generations. But now it has been revealed to his holy ones,

[NOTE]
====
. Or “past ages.” See Glossary.
====

[[v51-1-27]]

^<<v51-1-27,27>>^ to whom God has been pleased to make known among the nations the glorious riches of this sacred secret, which is Christ in union with you, the hope of his glory.

[[v51-1-28]]

^<<v51-1-28,28>>^ He is the one we are proclaiming, admonishing everyone and teaching everyone in all wisdom, so that we may present every person complete in union with Christ.

[[v51-1-29]]

^<<v51-1-29,29>>^ To this end I am indeed working hard, exerting myself with his strength that is operating powerfully within me.

'''

xref:050-philippians/050-philippians-004.adoc#v50-4-0[&#60; Capítulo Anterior] | <<v51-1-0,Topo>> | xref:051-colossians/051-colossians-002.adoc#v51-2-0[Próximo Capítulo &#62;]