include::./index.adoc[]

[[v51-3-0]]
=== Letter to the Colossians, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v51-3-1]]

^<<v51-3-1,1>>^ If, however, you were raised up with the Christ, go on seeking the things above, where the Christ is seated at the right hand of God.

[[v51-3-2]]

^<<v51-3-2,2>>^ Keep your minds fixed on the things above, not on the things on the earth.

[[v51-3-3]]

^<<v51-3-3,3>>^ For you died, and your life has been hidden with the Christ in union with God.

[[v51-3-4]]

^<<v51-3-4,4>>^ When the Christ, our life, is made manifest, then you also will be made manifest with him in glory.

[[v51-3-5]]

^<<v51-3-5,5>>^ Deaden, therefore, your body members that are on the earth as respects sexual immorality,^&#42;1^ uncleanness, uncontrolled sexual passion, hurtful desire, and greediness, which is idolatry.

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
====

[[v51-3-6]]

^<<v51-3-6,6>>^ On account of those things the wrath of God is coming.

[[v51-3-7]]

^<<v51-3-7,7>>^ That is how you too used to conduct yourselves^&#42;1^ in your former way of life.^&#42;2^

[NOTE]
====
. Or “used to walk.”
. Or “when you lived that way.”
====

[[v51-3-8]]

^<<v51-3-8,8>>^ But now you must put them all away from you: wrath, anger, badness, abusive speech, and obscene talk out of your mouth.

[[v51-3-9]]

^<<v51-3-9,9>>^ Do not lie to one another. Strip off the old personality^&#42;1^ with its practices,

[NOTE]
====
. Lit., “man.”
====

[[v51-3-10]]

^<<v51-3-10,10>>^ and clothe yourselves with the new personality, which through accurate knowledge is being made new according to the image of the One who created it,

[[v51-3-11]]

^<<v51-3-11,11>>^ where there is neither Greek nor Jew, circumcision nor uncircumcision, foreigner, Scythʹi·an,^&#42;1^ slave, or freeman; but Christ is all things and in all.

[NOTE]
====
. “Scythian” implied an uncivilized person.
====

[[v51-3-12]]

^<<v51-3-12,12>>^ Accordingly, as God’s chosen ones, holy and loved, clothe yourselves with the tender affections of compassion, kindness, humility,^&#42;1^ mildness, and patience.

[NOTE]
====
. Or “lowliness of mind.”
====

[[v51-3-13]]

^<<v51-3-13,13>>^ Continue putting up with one another and forgiving one another freely even if anyone has a cause for complaint against another. Just as Jehovah^&#42;1^ freely forgave you, you must also do the same.

[NOTE]
====
. See App. A5.
====

[[v51-3-14]]

^<<v51-3-14,14>>^ But besides all these things, clothe yourselves with love, for it is a perfect bond of union.

[[v51-3-15]]

^<<v51-3-15,15>>^ Also, let the peace of the Christ rule in your hearts,^&#42;1^ for you were called to that peace in one body. And show yourselves thankful.

[NOTE]
====
. Or “control your hearts.”
====

[[v51-3-16]]

^<<v51-3-16,16>>^ Let the word of the Christ reside in you richly in all wisdom. Keep on teaching and encouraging^&#42;1^ one another with psalms, praises to God, spiritual songs sung with gratitude,^&#42;2^ singing in your hearts to Jehovah.^&#42;3^

[NOTE]
====
. Or “admonishing.”
. Or “graciousness.”
. See App. A5.
====

[[v51-3-17]]

^<<v51-3-17,17>>^ Whatever it is that you do in word or in deed, do everything in the name of the Lord Jesus, thanking God the Father through him.

[[v51-3-18]]

^<<v51-3-18,18>>^ You wives, be in subjection to your husbands, as it is becoming in the Lord.

[[v51-3-19]]

^<<v51-3-19,19>>^ You husbands, keep on loving your wives and do not be bitterly angry^&#42;1^ with them.

[NOTE]
====
. Or “be harsh.”
====

[[v51-3-20]]

^<<v51-3-20,20>>^ You children, be obedient to your parents in everything, for this is well-pleasing to the Lord.

[[v51-3-21]]

^<<v51-3-21,21>>^ You fathers, do not be exasperating^&#42;1^ your children, so that they do not become downhearted.^&#42;2^

[NOTE]
====
. Or “provoking; irritating.”
. Or “discouraged.”
====

[[v51-3-22]]

^<<v51-3-22,22>>^ You slaves, be obedient in everything to those who are your human^&#42;1^ masters, not only when they are watching, just to please men,^&#42;2^ but with sincerity of heart, with fear of Jehovah.^&#42;3^

[NOTE]
====
. Lit., “fleshly.”
. Lit., “not with acts of eye-service, as men pleasers.”
. See App. A5.
====

[[v51-3-23]]

^<<v51-3-23,23>>^ Whatever you are doing, work at it whole-souled^&#42;1^ as for Jehovah,^&#42;2^ and not for men,

[NOTE]
====
. See Glossary, “Soul.”
. See App. A5.
====

[[v51-3-24]]

^<<v51-3-24,24>>^ for you know that it is from Jehovah^&#42;1^ you will receive the inheritance as a reward. Slave for the Master, Christ.

[NOTE]
====
. See App. A5.
====

[[v51-3-25]]

^<<v51-3-25,25>>^ Certainly the one who does wrong will be repaid for the wrong he has done, and there is no partiality.

'''

xref:051-colossians/051-colossians-002.adoc#v51-2-0[&#60; Capítulo Anterior] | <<v51-3-0,Topo>> | xref:051-colossians/051-colossians-004.adoc#v51-4-0[Próximo Capítulo &#62;]