include::./index.adoc[]

[[v38-9-0]]
=== Zechariah, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v38-9-1]]

^<<v38-9-1,1>>^ A pronouncement:
“The word of Jehovah is against the land of Haʹdrach,
And Damascus is its target^&#42;1^
—For Jehovah’s eye is on mankind
And on all the tribes of Israel—

[NOTE]
====
. Lit., “resting-place.”
====

[[v38-9-2]]

^<<v38-9-2,2>>^ And against Haʹmath, which borders on her,
And against Tyre and Siʹdon, for they are so wise.

[[v38-9-3]]

^<<v38-9-3,3>>^ Tyre built herself a rampart.^&#42;1^
She piled up silver like dust
And gold like the dirt of the streets.

[NOTE]
====
. Or “fortress.”
====

[[v38-9-4]]

^<<v38-9-4,4>>^ Look! Jehovah will take away her possessions,
And he will strike down her army into the sea;^&#42;1^
And she will be consumed in the fire.

[NOTE]
====
. Or possibly, “on the sea.”
====

[[v38-9-5]]

^<<v38-9-5,5>>^ Ashʹke·lon will see it and be afraid;
Gazʹa will feel great anguish,
Also Ekʹron, because her hope is put to shame.
A king will perish from Gazʹa,
And Ashʹke·lon will not be inhabited.

[[v38-9-6]]

^<<v38-9-6,6>>^ An illegitimate son will settle in Ashʹdod,
And I will do away with the pride of the Phi·lisʹtine.

[[v38-9-7]]

^<<v38-9-7,7>>^ I will remove the bloodstained things from his mouth
And the disgusting things from between his teeth,
And he will be left remaining for our God;
And he will become like a sheikh^&#42;1^ in Judah,
And Ekʹron like the Jebʹu·site.

[NOTE]
====
. A sheikh was a tribal chief.
====

[[v38-9-8]]

^<<v38-9-8,8>>^ I will encamp as a guard^&#42;1^ for my house,
So that there will be no one passing through and no one returning;
And no taskmaster^&#42;2^ will pass through again,
For now I have seen it^&#42;3^ with my eyes.

[NOTE]
====
. Or “an outpost.”
. Or “oppressor.”
. Evidently, the affliction of his people.
====

[[v38-9-9]]

^<<v38-9-9,9>>^ Rejoice greatly, O daughter of Zion.
Shout in triumph, O daughter of Jerusalem.
Look! Your king is coming to you.
He is righteous, bringing salvation,^&#42;1^
Humble and riding on a donkey,
On a colt,^&#42;2^ the foal of a female donkey.

[NOTE]
====
. Or “and victorious; and saved.”
. Or “a male donkey.”
====

[[v38-9-10]]

^<<v38-9-10,10>>^ I will take away the war chariot from Eʹphra·im
And the horse from Jerusalem.
The battle bow will be taken away.
And he will proclaim peace to the nations;
His rulership will be from sea to sea
And from the River^&#42;1^ to the ends of the earth.

[NOTE]
====
. That is, the Euphrates.
====

[[v38-9-11]]

^<<v38-9-11,11>>^ As for you, O woman, by the blood of your covenant,
I will send your prisoners out of the waterless pit.

[[v38-9-12]]

^<<v38-9-12,12>>^ Return to the stronghold, you prisoners with hope.
Today I am telling you,
‘I will repay to you, O woman, a double portion.

[[v38-9-13]]

^<<v38-9-13,13>>^ For I will bend^&#42;1^ Judah as my bow.
The bow I will fill with Eʹphra·im,^&#42;2^
And I will awaken your sons, O Zion,
Against your sons, O Greece,
And I will make you like a warrior’s sword.’

[NOTE]
====
. Lit., “tread.”
. That is, like an arrow.
====

[[v38-9-14]]

^<<v38-9-14,14>>^ Jehovah will be seen over them,
And his arrow will go out like lightning.
The Sovereign Lord Jehovah will sound the horn,
And he will advance with the windstorms of the south.

[[v38-9-15]]

^<<v38-9-15,15>>^ Jehovah of armies will defend them,
And they will devour and subdue the slingstones.
They will drink and be boisterous, as if with wine;
And they will be filled like the bowl,
Like the corners of the altar.

[[v38-9-16]]

^<<v38-9-16,16>>^ Jehovah their God will save them in that day
As the flock of his people;
For they will be like the gemstones of a crown^&#42;1^ glittering over his soil.

[NOTE]
====
. Or “diadem.”
====

[[v38-9-17]]

^<<v38-9-17,17>>^ For how great his goodness is,
And how great his handsomeness is!
Grain will make the young men thrive,
And new wine the virgins.”

'''

xref:038-zechariah/038-zechariah-008.adoc#v38-8-0[&#60; Capítulo Anterior] | <<v38-9-0,Topo>> | xref:038-zechariah/038-zechariah-010.adoc#v38-10-0[Próximo Capítulo &#62;]