include::./index.adoc[]

[[v38-2-0]]
=== Zechariah, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v38-2-1]]

^<<v38-2-1,1>>^ And I looked up and saw a man with a measuring line in his hand.

[[v38-2-2]]

^<<v38-2-2,2>>^ So I asked: “Where are you going?”
He replied: “To measure Jerusalem, to see what is her width and what is her length.”

[[v38-2-3]]

^<<v38-2-3,3>>^ And look! the angel who was speaking with me went out, and another angel came to meet him.

[[v38-2-4]]

^<<v38-2-4,4>>^ Then he said to him: “Run over there and tell that young man, ‘“Jerusalem will be inhabited as open rural country,^&#42;1^ because of all the men and livestock within her.

[NOTE]
====
. That is, without walls to enclose it.
====

[[v38-2-5]]

^<<v38-2-5,5>>^ And I will become to her,” declares Jehovah, “a wall of fire all around, and I will become the glory in her midst.”’”

[[v38-2-6]]

^<<v38-2-6,6>>^ “Come! Come! Flee from the land of the north,” declares Jehovah.
“For I have scattered you to the four winds of the heavens,” declares Jehovah.

[[v38-2-7]]

^<<v38-2-7,7>>^ “Come, Zion! Make your escape, you who are dwelling with the daughter of Babylon.

[[v38-2-8]]

^<<v38-2-8,8>>^ For this is what Jehovah of armies says, who after being glorified^&#42;1^ has sent me to the nations that were plundering you: ‘Whoever touches you touches the pupil of my eye.^&#42;2^

[NOTE]
====
. Lit., “after glory.”
. Or “touches my eyeball.”
====

[[v38-2-9]]

^<<v38-2-9,9>>^ For now I will wave my hand against them, and they will become plunder for their own slaves.’ And you will certainly know that Jehovah of armies has sent me.

[[v38-2-10]]

^<<v38-2-10,10>>^ “Shout for joy, O daughter of Zion; for I am coming, and I will reside in your midst,” declares Jehovah.

[[v38-2-11]]

^<<v38-2-11,11>>^ “Many nations will join themselves to Jehovah in that day, and they will become my people; and I will reside in your midst.” And you will have to know that Jehovah of armies has sent me to you.

[[v38-2-12]]

^<<v38-2-12,12>>^ Jehovah will take possession of Judah as his portion on the holy ground, and he will again choose Jerusalem.

[[v38-2-13]]

^<<v38-2-13,13>>^ Be silent, all flesh,^&#42;1^ before Jehovah, for he is taking action from his holy dwelling.

[NOTE]
====
. Or “mankind.”
====

'''

xref:038-zechariah/038-zechariah-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v38-2-0,Topo>> | xref:038-zechariah/038-zechariah-003.adoc#v38-3-0[Próximo Capítulo &#62;]