include::./index.adoc[]

[[v38-12-0]]
=== Zechariah, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v38-12-1]]

^<<v38-12-1,1>>^ A pronouncement:
“The word of Jehovah concerning Israel,” declares Jehovah,
The One who stretched out the heavens,
Who laid the foundation of the earth,
And who formed the spirit^&#42;1^ of man within him.

[NOTE]
====
. Or “breath.”
====

[[v38-12-2]]

^<<v38-12-2,2>>^ “Here I am making Jerusalem a cup^&#42;1^ that causes all the surrounding peoples to stagger; and there will be a siege against Judah as well as against Jerusalem.

[NOTE]
====
. Or “bowl.”
====

[[v38-12-3]]

^<<v38-12-3,3>>^ In that day I will make Jerusalem a heavy^&#42;1^ stone to all the peoples. All those who lift it are sure to be severely injured; and all the nations of the earth will be gathered against her.

[NOTE]
====
. Or “burdensome.”
====

[[v38-12-4]]

^<<v38-12-4,4>>^ In that day,” declares Jehovah, “I will strike every horse with panic and its rider with madness. I will keep my eyes on the house of Judah, but I will strike every horse of the peoples with blindness.

[[v38-12-5]]

^<<v38-12-5,5>>^ And the sheikhs^&#42;1^ of Judah will say in their heart, ‘The inhabitants of Jerusalem are a strength to me by means of Jehovah of armies their God.’

[NOTE]
====
. A sheikh was a tribal chief.
====

[[v38-12-6]]

^<<v38-12-6,6>>^ In that day I will make the sheikhs of Judah like a fiery pot among wood and like a fiery torch in a row of cut grain, and they will consume all the surrounding peoples on the right and on the left; and Jerusalem will again be inhabited in her place,^&#42;1^ in Jerusalem.

[NOTE]
====
. Or “in her rightful place.”
====

[[v38-12-7]]

^<<v38-12-7,7>>^ “And Jehovah will save the tents of Judah first, so that the beauty^&#42;1^ of the house of David and the beauty^&#42;2^ of the inhabitants of Jerusalem may not be too great over Judah.

[NOTE]
====
. Or “splendor.”
. Or “splendor.”
====

[[v38-12-8]]

^<<v38-12-8,8>>^ In that day Jehovah will be a defense around the inhabitants of Jerusalem; in that day the one who stumbles^&#42;1^ among them will be like David, and the house of David like God, like Jehovah’s angel who goes before them.

[NOTE]
====
. Or “the weakest.”
====

[[v38-12-9]]

^<<v38-12-9,9>>^ And in that day I will be certain to annihilate all the nations that come against Jerusalem.

[[v38-12-10]]

^<<v38-12-10,10>>^ “I will pour out on the house of David and on the inhabitants of Jerusalem the spirit of favor and supplication, and they will look to the one whom they pierced, and they will wail over him as they would wail over an only son; and they will grieve bitterly over him as they would grieve over a firstborn son.

[[v38-12-11]]

^<<v38-12-11,11>>^ In that day the wailing in Jerusalem will be great, like the wailing at Ha·dad·rimʹmon in the Plain of Me·gidʹdo.

[[v38-12-12]]

^<<v38-12-12,12>>^ And the land will wail, each family by itself; the family of David’s house by itself, and their women by themselves; the family of Nathan’s house by itself, and their women by themselves;

[[v38-12-13]]

^<<v38-12-13,13>>^ the family of Leʹvi’s house by itself, and their women by themselves; the family of the Shimʹe·ites by itself, and their women by themselves;

[[v38-12-14]]

^<<v38-12-14,14>>^ and all the families that are left remaining, each family by itself, and their women by themselves.

'''

xref:038-zechariah/038-zechariah-011.adoc#v38-11-0[&#60; Capítulo Anterior] | <<v38-12-0,Topo>> | xref:038-zechariah/038-zechariah-013.adoc#v38-13-0[Próximo Capítulo &#62;]