include::./index.adoc[]

[[v38-5-0]]
=== Zechariah, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v38-5-1]]

^<<v38-5-1,1>>^ Again I looked up, and I saw a flying scroll.

[[v38-5-2]]

^<<v38-5-2,2>>^ He asked me: “What do you see?”
I replied: “I see a flying scroll, which is 20 cubits^&#42;1^ long and 10 cubits wide.”

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
====

[[v38-5-3]]

^<<v38-5-3,3>>^ Then he said to me: “This is the curse that is going out over the face of all the earth, because everyone who steals, as written on its one side, has gone unpunished; and everyone who makes a sworn oath, as written on its other side, has gone unpunished.

[[v38-5-4]]

^<<v38-5-4,4>>^ ‘I have sent it out,’ declares Jehovah of armies, ‘and it will enter into the house of the thief and into the house of the one who makes a false oath in my name; and it will remain inside that house and consume it and its timbers and its stones.’”

[[v38-5-5]]

^<<v38-5-5,5>>^ Then the angel who was speaking with me came forward and said to me: “Look up, please, and see what is going out.”

[[v38-5-6]]

^<<v38-5-6,6>>^ So I asked: “What is it?”
He replied: “This is the eʹphah container^&#42;1^ that is going out.” He continued: “This is their appearance in all the earth.”

[NOTE]
====
. Lit., “the ephah,” here referring to a container or basket used to measure an ephah. An ephah equaled 22 L (20 dry qt). See App. B14.
====

[[v38-5-7]]

^<<v38-5-7,7>>^ And I saw that the round lid of lead was lifted up, and there was a woman sitting inside the container.

[[v38-5-8]]

^<<v38-5-8,8>>^ So he said: “This is Wickedness.” Then he threw her back into the eʹphah container, after which he thrust the lead weight over its mouth.

[[v38-5-9]]

^<<v38-5-9,9>>^ Then I looked up and saw two women coming forward, and they were soaring in the wind. They had wings like the wings of a stork. And they lifted up the container between the earth and heaven.

[[v38-5-10]]

^<<v38-5-10,10>>^ So I asked the angel who was speaking with me: “Where are they taking the eʹphah container?”

[[v38-5-11]]

^<<v38-5-11,11>>^ He replied: “To the land of Shiʹnar^&#42;1^ to build her a house; and when it is prepared, she will be deposited there in her proper place.”

[NOTE]
====
. That is, Babylonia.
====

'''

xref:038-zechariah/038-zechariah-004.adoc#v38-4-0[&#60; Capítulo Anterior] | <<v38-5-0,Topo>> | xref:038-zechariah/038-zechariah-006.adoc#v38-6-0[Próximo Capítulo &#62;]