include::./index.adoc[]

[[v38-8-0]]
=== Zechariah, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v38-8-1]]

^<<v38-8-1,1>>^ The word of Jehovah of armies again came, saying:

[[v38-8-2]]

^<<v38-8-2,2>>^ “This is what Jehovah of armies says, ‘I will be zealous for Zion with a great zeal, and with great wrath I will be zealous for her.’”

[[v38-8-3]]

^<<v38-8-3,3>>^ “This is what Jehovah says, ‘I will return to Zion and reside in Jerusalem; and Jerusalem will be called the city of truth,^&#42;1^ and the mountain of Jehovah of armies, the holy mountain.’”

[NOTE]
====
. Or “faithfulness.”
====

[[v38-8-4]]

^<<v38-8-4,4>>^ “This is what Jehovah of armies says, ‘Old men and women will again sit in the public squares of Jerusalem, each with his staff in his hand because of his great age.^&#42;1^

[NOTE]
====
. Lit., “because of the multitude of days.”
====

[[v38-8-5]]

^<<v38-8-5,5>>^ And the public squares of the city will be filled with boys and girls playing there.’”

[[v38-8-6]]

^<<v38-8-6,6>>^ “This is what Jehovah of armies says, ‘Although it may seem too difficult to the remaining ones of this people in those days, should it seem too difficult also to me?’ declares Jehovah of armies.”

[[v38-8-7]]

^<<v38-8-7,7>>^ “This is what Jehovah of armies says, ‘Here I am saving my people from the lands of the east and the west.^&#42;1^

[NOTE]
====
. Or “from the land of the sunrise and the land of the setting sun.”
====

[[v38-8-8]]

^<<v38-8-8,8>>^ And I will bring them in, and they will reside in Jerusalem; and they will become my people, and I will become their God in truth^&#42;1^ and in righteousness.’”

[NOTE]
====
. Or “faithfulness.”
====

[[v38-8-9]]

^<<v38-8-9,9>>^ “This is what Jehovah of armies says, ‘Let your hands be strong,^&#42;1^ you who now hear these words from the mouth of the prophets, the same words that were spoken on the day the foundation of the house of Jehovah of armies was laid for the temple to be built.

[NOTE]
====
. Or “Take courage.”
====

[[v38-8-10]]

^<<v38-8-10,10>>^ For before that time, there were no wages being paid either for man or for beast; and it was not safe to come and go because of the adversary, for I turned all men one against another.’

[[v38-8-11]]

^<<v38-8-11,11>>^ “‘But now I will not deal with the remaining ones of this people as in the former days,’ declares Jehovah of armies.

[[v38-8-12]]

^<<v38-8-12,12>>^ ‘For the seed of peace will be sown; the vine will produce its fruit and the earth its yield, and the heavens will give their dew; and I will cause the remaining ones of this people to inherit all these things.

[[v38-8-13]]

^<<v38-8-13,13>>^ And just as you became an object of cursing among the nations, O house of Judah and house of Israel, so I will save you, and you will become a blessing. Do not be afraid! Let your hands be strong.’^&#42;1^

[NOTE]
====
. Or “Take courage.”
====

[[v38-8-14]]

^<<v38-8-14,14>>^ “For this is what Jehovah of armies says, ‘“Just as I had determined to bring calamity on you because your forefathers made me indignant,” says Jehovah of armies, “and I felt no regret,

[[v38-8-15]]

^<<v38-8-15,15>>^ so at this time I have determined to do good to Jerusalem and to the house of Judah. Do not be afraid!”’

[[v38-8-16]]

^<<v38-8-16,16>>^ “‘These are the things you should do: Speak the truth with one another, and the judgments in your gates must promote truth and peace.

[[v38-8-17]]

^<<v38-8-17,17>>^ Do not scheme calamity against one another in your hearts, and do not love any false oath; for these are all things that I hate,’ declares Jehovah.”

[[v38-8-18]]

^<<v38-8-18,18>>^ The word of Jehovah of armies again came to me, saying:

[[v38-8-19]]

^<<v38-8-19,19>>^ “This is what Jehovah of armies says, ‘The fast of the fourth month, the fast of the fifth month, the fast of the seventh month, and the fast of the tenth month will be occasions for exultation and joy for the house of Judah—festivals of rejoicing. So love truth and peace.’

[[v38-8-20]]

^<<v38-8-20,20>>^ “This is what Jehovah of armies says, ‘It will yet come to pass that peoples and the inhabitants of many cities will come;

[[v38-8-21]]

^<<v38-8-21,21>>^ and the inhabitants of one city will go to those of another and say: “Let us earnestly go to beg for the favor^&#42;1^ of Jehovah and to seek Jehovah of armies. I am also going.”

[NOTE]
====
. Or “soften the face.”
====

[[v38-8-22]]

^<<v38-8-22,22>>^ And many peoples and mighty nations will come to seek Jehovah of armies in Jerusalem and to beg for the favor^&#42;1^ of Jehovah.’

[NOTE]
====
. Or “soften the face.”
====

[[v38-8-23]]

^<<v38-8-23,23>>^ “This is what Jehovah of armies says, ‘In those days ten men out of all the languages of the nations will take hold, yes, they will take firm hold of the robe^&#42;1^ of a Jew,^&#42;2^ saying: “We want to go with you, for we have heard that God is with you people.”’”

[NOTE]
====
. Or “extremity of the garment.”
. Lit., “a Jewish man.”
====

'''

xref:038-zechariah/038-zechariah-007.adoc#v38-7-0[&#60; Capítulo Anterior] | <<v38-8-0,Topo>> | xref:038-zechariah/038-zechariah-009.adoc#v38-9-0[Próximo Capítulo &#62;]