include::./index.adoc[]

[[v38-4-0]]
=== Zechariah, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v38-4-1]]

^<<v38-4-1,1>>^ The angel who had been speaking with me came back and woke me up, as when waking someone from sleep.

[[v38-4-2]]

^<<v38-4-2,2>>^ Then he said to me: “What do you see?”
So I said: “I see, and look! a lampstand entirely of gold, with a bowl on top of it. There are seven lamps on it, yes, seven, and the lamps, which are at the top of it, have seven pipes.

[[v38-4-3]]

^<<v38-4-3,3>>^ And next to it are two olive trees, one on the right of the bowl and one on the left.”

[[v38-4-4]]

^<<v38-4-4,4>>^ Then I asked the angel who was speaking with me: “What do these things mean, my lord?”

[[v38-4-5]]

^<<v38-4-5,5>>^ So the angel who was speaking with me asked: “Do you not know what these things mean?”
I replied: “No, my lord.”

[[v38-4-6]]

^<<v38-4-6,6>>^ He then said to me: “This is the word of Jehovah to Ze·rubʹba·bel: ‘“Not by a military force, nor by power, but by my spirit,” says Jehovah of armies.

[[v38-4-7]]

^<<v38-4-7,7>>^ Who are you, O great mountain? Before Ze·rubʹba·bel you will become a level land.^&#42;1^ And he will bring out the top stone^&#42;2^ amid shouts of: “How wonderful! How wonderful!”’”

[NOTE]
====
. Or “a plain.”
. Or “the capstone.”
====

[[v38-4-8]]

^<<v38-4-8,8>>^ The word of Jehovah again came to me, saying:

[[v38-4-9]]

^<<v38-4-9,9>>^ “The hands of Ze·rubʹba·bel have laid the foundation of this house, and his own hands will finish it. And you will have to know that Jehovah of armies has sent me to you.

[[v38-4-10]]

^<<v38-4-10,10>>^ For who has despised the day of small beginnings?^&#42;1^ For they will rejoice and see the plumb line^&#42;2^ in the hand of Ze·rubʹba·bel. These seven are the eyes of Jehovah, which are roving about in all the earth.”

[NOTE]
====
. Or “small things?”
. Lit., “the stone, the tin.”
====

[[v38-4-11]]

^<<v38-4-11,11>>^ Then I asked him: “What is the meaning of these two olive trees on the right and on the left of the lampstand?”

[[v38-4-12]]

^<<v38-4-12,12>>^ I asked him a second time: “What is the meaning of the two bunches of twigs^&#42;1^ of the olive trees that are pouring out the golden liquid through the two golden tubes?”

[NOTE]
====
. That is, fruit-laden twigs of the tree.
====

[[v38-4-13]]

^<<v38-4-13,13>>^ So he asked me: “Do you not know what these things mean?”
I replied: “No, my lord.”

[[v38-4-14]]

^<<v38-4-14,14>>^ He said: “These are the two anointed ones who are standing alongside the Lord of the whole earth.”

'''

xref:038-zechariah/038-zechariah-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zechariah/038-zechariah-005.adoc#v38-5-0[Próximo Capítulo &#62;]