include::./index.adoc[]

[[v38-11-0]]
=== Zechariah, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v38-11-1]]

^<<v38-11-1,1>>^ “Open your doors, O Lebʹa·non,
So that a fire may consume your cedars.

[[v38-11-2]]

^<<v38-11-2,2>>^ Wail, you juniper, for the cedar has fallen;
The majestic trees have been destroyed!
Wail, you oaks of Baʹshan,
For the dense forest has come down!

[[v38-11-3]]

^<<v38-11-3,3>>^ Listen! The wailing of shepherds,
For their majesty has been devastated.
Listen! The roaring of young lions,^&#42;1^
For the dense thickets along the Jordan have been destroyed.

[NOTE]
====
. Or “maned young lions.”
====

[[v38-11-4]]

^<<v38-11-4,4>>^ “This is what Jehovah my God says, ‘Shepherd the flock meant for the slaughter,

[[v38-11-5]]

^<<v38-11-5,5>>^ whose buyers slaughter them and are not held guilty. And those who sell them say, “May Jehovah be praised, for I will become rich.” And their shepherds have no compassion for them.’

[[v38-11-6]]

^<<v38-11-6,6>>^ “‘For I will no longer show compassion on the inhabitants of the land,’ declares Jehovah. ‘So I will cause each man to fall into the hand of his neighbor and his king; and they will crush the land, and I will not rescue them out of their hand.’”

[[v38-11-7]]

^<<v38-11-7,7>>^ And I began to shepherd the flock meant for slaughter, in your behalf, O afflicted ones of the flock. So I took two staffs, and I called one Pleasantness, and the other Union, and I began to shepherd the flock.

[[v38-11-8]]

^<<v38-11-8,8>>^ And I dismissed three shepherds in one month, for I^&#42;1^ became impatient with them, and they^&#42;2^ detested me as well.

[NOTE]
====
. Or “my soul.”
. Or “their soul.”
====

[[v38-11-9]]

^<<v38-11-9,9>>^ And I said: “I will not keep shepherding you. Let the one who is dying die, and let the one perishing perish. As for those who are left, let them devour one another’s flesh.”

[[v38-11-10]]

^<<v38-11-10,10>>^ So I took my staff Pleasantness and cut it up, breaking my covenant that I had made with all the peoples.

[[v38-11-11]]

^<<v38-11-11,11>>^ So it was broken in that day, and the afflicted ones of the flock who were watching me knew that it was the word of Jehovah.

[[v38-11-12]]

^<<v38-11-12,12>>^ Then I said to them: “If it seems good to you, give me my wages; but if not, withhold them.” And they paid^&#42;1^ my wages, 30 pieces of silver.

[NOTE]
====
. Lit., “weighed out.”
====

[[v38-11-13]]

^<<v38-11-13,13>>^ Then Jehovah said to me: “Throw it into the treasury—the magnificent value with which they valued me.” So I took the 30 pieces of silver and threw it into the treasury at the house of Jehovah.

[[v38-11-14]]

^<<v38-11-14,14>>^ Then I cut up my second staff, the Union, breaking the brotherhood between Judah and Israel.

[[v38-11-15]]

^<<v38-11-15,15>>^ And Jehovah said to me: “Now take the equipment of a useless shepherd.

[[v38-11-16]]

^<<v38-11-16,16>>^ For I am letting a shepherd rise up in the land. He will not take care of the sheep that are perishing; he will not seek out the young or heal the injured or feed those able to stand. Instead, he devours the flesh of the fat one and tears off the hooves of the sheep.

[[v38-11-17]]

^<<v38-11-17,17>>^ Woe to my worthless shepherd, who is abandoning the flock!
A sword will strike his arm and his right eye.
His arm will wither completely,
And his right eye will go completely blind.”^&#42;1^

[NOTE]
====
. Lit., “dim.”
====

'''

xref:038-zechariah/038-zechariah-010.adoc#v38-10-0[&#60; Capítulo Anterior] | <<v38-11-0,Topo>> | xref:038-zechariah/038-zechariah-012.adoc#v38-12-0[Próximo Capítulo &#62;]