include::./index.adoc[]

[[v38-6-0]]
=== Zechariah, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v38-6-1]]

^<<v38-6-1,1>>^ Then I looked up again and saw four chariots coming from between two mountains, and the mountains were of copper.

[[v38-6-2]]

^<<v38-6-2,2>>^ The first chariot had red horses, and the second chariot, black horses.

[[v38-6-3]]

^<<v38-6-3,3>>^ The third chariot had white horses, and the fourth chariot, speckled and dappled horses.

[[v38-6-4]]

^<<v38-6-4,4>>^ I asked the angel who was speaking with me: “What are these, my lord?”

[[v38-6-5]]

^<<v38-6-5,5>>^ The angel answered me: “These are the four spirits of the heavens that are going out after having taken their station before the Lord of the whole earth.

[[v38-6-6]]

^<<v38-6-6,6>>^ The one^&#42;1^ with the black horses is going out to the land of the north; the white ones are going out beyond the sea; and the speckled ones are going out to the land of the south.

[NOTE]
====
. That is, the chariot.
====

[[v38-6-7]]

^<<v38-6-7,7>>^ And the dappled ones were eager to go out to walk about through the earth.” Then he said: “Go, walk about through the earth.” And they began walking about through the earth.

[[v38-6-8]]

^<<v38-6-8,8>>^ He then called out to me and said: “See, those going out to the land of the north have caused the spirit of Jehovah to rest in the land of the north.”

[[v38-6-9]]

^<<v38-6-9,9>>^ The word of Jehovah again came to me, saying:

[[v38-6-10]]

^<<v38-6-10,10>>^ “Take from Helʹdai, To·biʹjah, and Je·daʹiah what they brought from the people in exile; and on that day, you must go to the house of Jo·siʹah the son of Zeph·a·niʹah along with these who have come from Babylon.

[[v38-6-11]]

^<<v38-6-11,11>>^ You should take silver and gold and make a crown^&#42;1^ and put it on the head of Joshua son of Je·hozʹa·dak, the high priest.

[NOTE]
====
. Or “a grand crown.”
====

[[v38-6-12]]

^<<v38-6-12,12>>^ And say to him,
“‘This is what Jehovah of armies says: “Here is the man whose name is Sprout. He will sprout from his own place, and he will build the temple of Jehovah.

[[v38-6-13]]

^<<v38-6-13,13>>^ He is the one who will build the temple of Jehovah, and he is the one who will assume the majesty. He will sit down on his throne and rule, and he will also be a priest on his throne, and there will be a peaceable agreement between the two.^&#42;1^

[NOTE]
====
. That is, between his roles as ruler and priest.
====

[[v38-6-14]]

^<<v38-6-14,14>>^ And the crown^&#42;1^ will serve as a memorial^&#42;2^ for Heʹlem, To·biʹjah, Je·daʹiah, and Hen the son of Zeph·a·niʹah, in the temple of Jehovah.

[NOTE]
====
. Or “the grand crown.”
. Or “reminder.”
====

[[v38-6-15]]

^<<v38-6-15,15>>^ And those who are far away will come and take part in building the temple of Jehovah.” And you will have to know that Jehovah of armies has sent me to you. And it will occur—if you do not fail to listen to the voice of Jehovah your God.’”

'''

xref:038-zechariah/038-zechariah-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zechariah/038-zechariah-007.adoc#v38-7-0[Próximo Capítulo &#62;]