include::./index.adoc[]

[[v38-10-0]]
=== Zechariah, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v38-10-1]]

^<<v38-10-1,1>>^ “Ask Jehovah for rain in the time of the spring rain.
It is Jehovah who makes the storm clouds,
Who pours rain for them,
And gives vegetation in the field to everyone.

[[v38-10-2]]

^<<v38-10-2,2>>^ For the teraphim statues^&#42;1^ have spoken deception;^&#42;2^
And the diviners have visioned a lie.
They speak about worthless dreams,
And in vain they try to comfort.
That is why they will wander like sheep.
They will suffer, for there is no shepherd.

[NOTE]
====
. Or “household gods; idols.”
. Or “what is uncanny; what is mystical.”
====

[[v38-10-3]]

^<<v38-10-3,3>>^ Against the shepherds my anger burns,
And against the oppressive leaders^&#42;1^ I will hold an accounting;
For Jehovah of armies has turned his attention to his flock, to the house of Judah,
And he has made them like his majestic horse in the battle.

[NOTE]
====
. Lit., “the he-goats.”
====

[[v38-10-4]]

^<<v38-10-4,4>>^ From him comes the keyman,^&#42;1^
From him comes the supporting ruler,^&#42;2^
From him comes the battle bow;
From him goes forth every overseer,^&#42;3^ all of them together.

[NOTE]
====
. Lit., “the corner tower,” pictorial of a vital or important man; a chief.
. Lit., “the peg,” pictorial of one who is a support; a ruler.
. Or “taskmaster.”
====

[[v38-10-5]]

^<<v38-10-5,5>>^ And they will become like warriors,
Trampling down the mud of the streets in the battle.
They will wage war, for Jehovah is with them;
And the riders of horses will be put to shame.

[[v38-10-6]]

^<<v38-10-6,6>>^ I will make the house of Judah superior,
And the house of Joseph I will save.
I will restore them,
For I will show them mercy;
And they will be as though I had never cast them off;
For I am Jehovah their God, and I will answer them.

[[v38-10-7]]

^<<v38-10-7,7>>^ Those of Eʹphra·im must become like a mighty warrior,
And their heart will rejoice as though from wine.
Their sons will see this and rejoice;
Their heart will be joyful in Jehovah.

[[v38-10-8]]

^<<v38-10-8,8>>^ ‘I will whistle for them and gather them together;
For I will redeem them, and they will become many,
And continue to be many.

[[v38-10-9]]

^<<v38-10-9,9>>^ Though I scatter them like seed among the peoples,
They will remember me in the distant places;
With their sons they will revive and return.

[[v38-10-10]]

^<<v38-10-10,10>>^ I will bring them back from the land of Egypt
And gather them from As·syrʹi·a;
I will bring them to the land of Gilʹe·ad and Lebʹa·non,
And there will be no more room for them.

[[v38-10-11]]

^<<v38-10-11,11>>^ He must pass through the sea with distress;
And in the sea he will strike down the waves;
All the depths of the Nile will dry up.
The pride of As·syrʹi·a will be brought down,
And the scepter of Egypt will depart.

[[v38-10-12]]

^<<v38-10-12,12>>^ I will make them superior in Jehovah,
And they will walk about in his name,’ declares Jehovah.”

'''

xref:038-zechariah/038-zechariah-009.adoc#v38-9-0[&#60; Capítulo Anterior] | <<v38-10-0,Topo>> | xref:038-zechariah/038-zechariah-011.adoc#v38-11-0[Próximo Capítulo &#62;]