include::./index.adoc[]

[[v38-13-0]]
=== Zechariah, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v38-13-1]]

^<<v38-13-1,1>>^ “In that day a well will be opened to the house of David and to the inhabitants of Jerusalem for cleansing sin and impurity.

[[v38-13-2]]

^<<v38-13-2,2>>^ “In that day,” declares Jehovah of armies, “I will erase the names of the idols from the land, and they will no longer be remembered; and I will rid the land of the prophets and the spirit of uncleanness.

[[v38-13-3]]

^<<v38-13-3,3>>^ And if a man should prophesy again, his father and his mother who caused his birth will say to him, ‘You will not live, because you have spoken lies in the name of Jehovah.’ And his father and his mother who caused his birth will pierce him through because of his prophesying.

[[v38-13-4]]

^<<v38-13-4,4>>^ “In that day each of the prophets will be ashamed of his vision when he prophesies; and they will not wear an official garment of hair in order to deceive.

[[v38-13-5]]

^<<v38-13-5,5>>^ And he will say, ‘I am no prophet. I am a man cultivating the soil, because a man bought me when I was young.’

[[v38-13-6]]

^<<v38-13-6,6>>^ And if someone asks him, ‘What are these wounds between your shoulders?’^&#42;1^ he will answer, ‘Wounds I received in the house of my friends.’”^&#42;2^

[NOTE]
====
. Lit., “between your hands?” That is, on the chest or on the back.
. Or “of those who love me.”
====

[[v38-13-7]]

^<<v38-13-7,7>>^ “O sword, awake against my shepherd,
Against the man who is my companion,” declares Jehovah of armies.
“Strike the shepherd, and let the flock^&#42;1^ be scattered;
And I will turn my hand against those who are insignificant.”

[NOTE]
====
. Or “sheep.”
====

[[v38-13-8]]

^<<v38-13-8,8>>^ “And in all the land,” declares Jehovah,
“Two parts in it will be cut off and perish;^&#42;1^
And the third part will be left remaining in it.

[NOTE]
====
. Or “die.”
====

[[v38-13-9]]

^<<v38-13-9,9>>^ And I will bring the third part through the fire;
And I will refine them as silver is refined,
And test them as gold is tested.
They will call on my name,
And I will answer them.
I will say, ‘They are my people,’
And they will say, ‘Jehovah is our God.’”

'''

xref:038-zechariah/038-zechariah-012.adoc#v38-12-0[&#60; Capítulo Anterior] | <<v38-13-0,Topo>> | xref:038-zechariah/038-zechariah-014.adoc#v38-14-0[Próximo Capítulo &#62;]