include::./index.adoc[]

[[v7-17-0]]
=== Judges, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-17-1]]

^<<v7-17-1,1>>^ There was a man of the mountainous region of Eʹphra·im named Miʹcah.

[[v7-17-2]]

^<<v7-17-2,2>>^ He said to his mother: “The 1,100 silver pieces that were taken from you about which you pronounced a curse, which I heard—look! the silver is with me. I was the one who took it.” At that his mother said: “May Jehovah bless my son.”

[[v7-17-3]]

^<<v7-17-3,3>>^ So he gave the 1,100 pieces of silver back to his mother, but his mother said: “I will without fail sanctify the silver to Jehovah from my hand for my son to use in making a carved image and a metal statue.^&#42;1^ Now I give it back to you.”

[NOTE]
====
. Or “molten statue.”
====

[[v7-17-4]]

^<<v7-17-4,4>>^ After he returned the silver to his mother, his mother took 200 silver pieces and gave them to the silversmith. He made a carved image and a metal statue;^&#42;1^ and they were put in Miʹcah’s house.

[NOTE]
====
. Or “molten statue.”
====

[[v7-17-5]]

^<<v7-17-5,5>>^ This man Miʹcah had a house of gods, and he made an ephʹod and teraphim statues^&#42;1^ and installed^&#42;2^ one of his sons to serve as priest for him.

[NOTE]
====
. Or “household gods; idols.”
. Lit., “filled the hand of.”
====

[[v7-17-6]]

^<<v7-17-6,6>>^ In those days, there was no king in Israel. Each one was doing what was right in his own eyes.^&#42;1^

[NOTE]
====
. Or “what he thought was right.”
====

[[v7-17-7]]

^<<v7-17-7,7>>^ Now there was a young man of Bethʹle·hem in Judah who was of the family of Judah. He was a Levite who had been living there for a time.

[[v7-17-8]]

^<<v7-17-8,8>>^ The man left the city of Bethʹle·hem in Judah to find a place to live. While on his journey, he came to the mountainous region of Eʹphra·im, to the house of Miʹcah.

[[v7-17-9]]

^<<v7-17-9,9>>^ Then Miʹcah said to him: “Where do you come from?” He replied: “I am a Levite from Bethʹle·hem in Judah, and I am on my way to find a place to live.”

[[v7-17-10]]

^<<v7-17-10,10>>^ So Miʹcah said to him: “Stay with me and serve as a father^&#42;1^ and a priest for me. I will give you ten silver pieces a year and a set of garments and your food.” So the Levite went in.

[NOTE]
====
. Or “an adviser.”
====

[[v7-17-11]]

^<<v7-17-11,11>>^ Thus the Levite agreed to stay with the man, and the young man became like one of his sons.

[[v7-17-12]]

^<<v7-17-12,12>>^ Furthermore, Miʹcah installed^&#42;1^ the Levite to serve as a priest for him, and he lived in the house of Miʹcah.

[NOTE]
====
. Lit., “filled the hand of.”
====

[[v7-17-13]]

^<<v7-17-13,13>>^ Then Miʹcah said: “Now I know that Jehovah will be good to me, for the Levite has become my priest.”

'''

xref:007-judges/007-judges-016.adoc#v7-16-0[&#60; Capítulo Anterior] | <<v7-17-0,Topo>> | xref:007-judges/007-judges-018.adoc#v7-18-0[Próximo Capítulo &#62;]