include::./index.adoc[]

[[v7-9-0]]
=== Judges, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-9-1]]

^<<v7-9-1,1>>^ In time A·bimʹe·lech the son of Jer·ub·baʹal went to his mother’s brothers in Sheʹchem, and he said to them and to all the family of his grandfather:^&#42;1^

[NOTE]
====
. Lit., “the family of the house of the father of his mother.”
====

[[v7-9-2]]

^<<v7-9-2,2>>^ “Please ask all the leaders^&#42;1^ of Sheʹchem, ‘Which is better for you, for all 70 sons of Jer·ub·baʹal to rule over you or for one man to rule over you? And remember that I am your own bone and flesh.’”^&#42;2^

[NOTE]
====
. Or possibly, “landowners.”
. Or “your blood relative.”
====

[[v7-9-3]]

^<<v7-9-3,3>>^ So his mother’s brothers said this in his behalf to all the leaders of Sheʹchem, and their hearts were inclined to follow A·bimʹe·lech, for they said: “He is our own brother.”

[[v7-9-4]]

^<<v7-9-4,4>>^ Then they gave him 70 pieces of silver from the house^&#42;1^ of Baʹal-beʹrith, and A·bimʹe·lech used it to hire idle and insolent men to accompany him.

[NOTE]
====
. Or “temple.”
====

[[v7-9-5]]

^<<v7-9-5,5>>^ After that he went to his father’s house at Ophʹrah and killed his brothers, the sons of Jer·ub·baʹal, 70 men, on one stone. The only survivor was Joʹtham, the youngest son of Jer·ub·baʹal, because he hid.

[[v7-9-6]]

^<<v7-9-6,6>>^ Then all the leaders of Sheʹchem and all Beth-milʹlo gathered together and made A·bimʹe·lech king, close by the big tree, by the pillar that was in Sheʹchem.

[[v7-9-7]]

^<<v7-9-7,7>>^ When they reported it to Joʹtham, he at once went and stood on the top of Mount Gerʹi·zim and called out in a loud voice to them: “Listen to me, you leaders of Sheʹchem, and then God will listen to you.

[[v7-9-8]]

^<<v7-9-8,8>>^ “Once there were trees that went to anoint a king over them. So they said to the olive tree, ‘Rule over us.’

[[v7-9-9]]

^<<v7-9-9,9>>^ But the olive tree said to them, ‘Must I give up my oil,^&#42;1^ which they use to glorify God and men, to go and wave over the other trees?’

[NOTE]
====
. Or “fruitfulness.”
====

[[v7-9-10]]

^<<v7-9-10,10>>^ Then the trees said to the fig tree, ‘Come and rule over us.’

[[v7-9-11]]

^<<v7-9-11,11>>^ But the fig tree said to them, ‘Must I give up my sweetness and my good fruitage to go and wave over the other trees?’

[[v7-9-12]]

^<<v7-9-12,12>>^ Next the trees said to the vine, ‘Come and rule over us.’

[[v7-9-13]]

^<<v7-9-13,13>>^ The vine replied to them, ‘Must I give up my new wine that makes God and men rejoice to go and wave over the trees?’

[[v7-9-14]]

^<<v7-9-14,14>>^ Finally all the other trees said to the bramble, ‘Come and rule over us.’

[[v7-9-15]]

^<<v7-9-15,15>>^ At this the bramble said to the trees, ‘If you are really anointing me as king over you, come and seek refuge under my shadow. But if not, let fire come out of the bramble and consume the cedars of Lebʹa·non.’

[[v7-9-16]]

^<<v7-9-16,16>>^ “Now have you acted sincerely and honorably in making A·bimʹe·lech king, and have you shown goodness toward Jer·ub·baʹal and his household, and have you treated him as he deserves?

[[v7-9-17]]

^<<v7-9-17,17>>^ When my father fought for you, he risked his life^&#42;1^ to save you from Midʹi·an’s hand.

[NOTE]
====
. Or “soul.”
====

[[v7-9-18]]

^<<v7-9-18,18>>^ But today you have risen up against my father’s household and killed his sons, 70 men, on one stone. Then you made A·bimʹe·lech, the son of his slave girl, king over the leaders of Sheʹchem just because he is your brother.

[[v7-9-19]]

^<<v7-9-19,19>>^ Yes, if you are acting sincerely and honorably toward Jer·ub·baʹal and his household this day, rejoice over A·bimʹe·lech and let him also rejoice over you.

[[v7-9-20]]

^<<v7-9-20,20>>^ But if not, may fire come out of A·bimʹe·lech and consume the leaders of Sheʹchem and Beth-milʹlo, and may fire come out of the leaders of Sheʹchem and Beth-milʹlo and consume A·bimʹe·lech.”

[[v7-9-21]]

^<<v7-9-21,21>>^ Then Joʹtham fled and escaped to Beʹer, and he lived there because of his brother A·bimʹe·lech.

[[v7-9-22]]

^<<v7-9-22,22>>^ A·bimʹe·lech ruled^&#42;1^ over Israel for three years.

[NOTE]
====
. Or “played the prince.”
====

[[v7-9-23]]

^<<v7-9-23,23>>^ Then God let hostility develop^&#42;1^ between A·bimʹe·lech and the leaders of Sheʹchem, and they dealt treacherously with A·bimʹe·lech.

[NOTE]
====
. Lit., “sent a bad spirit.”
====

[[v7-9-24]]

^<<v7-9-24,24>>^ This was so that the violence done to the 70 sons of Jer·ub·baʹal might be avenged, so as to place responsibility for their blood on their brother A·bimʹe·lech for killing them and on the leaders of Sheʹchem for helping him to kill his brothers.

[[v7-9-25]]

^<<v7-9-25,25>>^ So the leaders of Sheʹchem set men to ambush him on the mountaintops, and they would rob everyone who passed by them on the road. In time it was reported to A·bimʹe·lech.

[[v7-9-26]]

^<<v7-9-26,26>>^ Then Gaʹal son of Eʹbed and his brothers crossed over into Sheʹchem, and the leaders of Sheʹchem put their trust in him.

[[v7-9-27]]

^<<v7-9-27,27>>^ They went out into the field and gathered the grapes of their vineyards, trod them out, and held a festival, after which they went into the house of their god and ate and drank and cursed A·bimʹe·lech.

[[v7-9-28]]

^<<v7-9-28,28>>^ Then Gaʹal the son of Eʹbed said: “Who is A·bimʹe·lech, and who is Sheʹchem that we should serve him? Is he not the son of Jer·ub·baʹal, and is not Zeʹbul his commissioner? Serve the men of Haʹmor, Sheʹchem’s father! But why should we serve him?

[[v7-9-29]]

^<<v7-9-29,29>>^ If only this people were under my command, I would depose A·bimʹe·lech.” Then he said to A·bimʹe·lech: “Increase your army and come out.”

[[v7-9-30]]

^<<v7-9-30,30>>^ When Zeʹbul the prince of the city heard the words of Gaʹal the son of Eʹbed, his anger blazed.

[[v7-9-31]]

^<<v7-9-31,31>>^ So he secretly^&#42;1^ sent messengers to A·bimʹe·lech, saying: “Look! Gaʹal the son of Eʹbed and his brothers are now in Sheʹchem, and here they are inciting the city against you.

[NOTE]
====
. Or “cunningly.”
====

[[v7-9-32]]

^<<v7-9-32,32>>^ Now come up by night, you and your men, and lie in wait in the field.

[[v7-9-33]]

^<<v7-9-33,33>>^ As soon as the sun rises in the morning, you should get up early and attack the city; and when he and his men come out against you, do whatever you can to defeat him.”^&#42;1^

[NOTE]
====
. Or “do to him what your hand finds possible.”
====

[[v7-9-34]]

^<<v7-9-34,34>>^ So A·bimʹe·lech and all the people with him rose up by night, and in four bands they lay in wait against Sheʹchem.

[[v7-9-35]]

^<<v7-9-35,35>>^ When Gaʹal the son of Eʹbed went out and stood at the entrance of the city gate, A·bimʹe·lech and the people with him rose up from the ambush.

[[v7-9-36]]

^<<v7-9-36,36>>^ When Gaʹal saw the people, he said to Zeʹbul: “Look! There are people coming down from the mountaintops.” But Zeʹbul said to him: “You are seeing the shadows of the mountains as if they were men.”

[[v7-9-37]]

^<<v7-9-37,37>>^ Gaʹal later said: “Look! People are coming down from the center of the land, and one band is coming by the way of the big tree of Me·onʹe·nim.”

[[v7-9-38]]

^<<v7-9-38,38>>^ Zeʹbul replied to him: “Where now is your boast, ‘Who is A·bimʹe·lech that we should serve him?’ Are these not the people you rejected? Go out now and fight against them.”

[[v7-9-39]]

^<<v7-9-39,39>>^ So Gaʹal went out at the head of the leaders of Sheʹchem and fought against A·bimʹe·lech.

[[v7-9-40]]

^<<v7-9-40,40>>^ A·bimʹe·lech pursued him, and Gaʹal fled from him, and many fell slain as far as the entrance of the city gate.

[[v7-9-41]]

^<<v7-9-41,41>>^ And A·bimʹe·lech continued to dwell in A·ruʹmah, and Zeʹbul drove Gaʹal and his brothers out of Sheʹchem.

[[v7-9-42]]

^<<v7-9-42,42>>^ The next day the people went out into the field, and A·bimʹe·lech was told about it.

[[v7-9-43]]

^<<v7-9-43,43>>^ So he took the people and divided them into three bands and lay in wait in the field. When he saw the people going out of the city, he attacked them and struck them down.

[[v7-9-44]]

^<<v7-9-44,44>>^ A·bimʹe·lech and the bands with him charged forward and took a position at the entrance of the city gate, while two bands attacked all who were in the field, and they struck them down.

[[v7-9-45]]

^<<v7-9-45,45>>^ A·bimʹe·lech fought against the city all that day and captured it. He killed the people in it, and then he pulled the city down and sowed it with salt.

[[v7-9-46]]

^<<v7-9-46,46>>^ When all the leaders of the tower of Sheʹchem heard about this, they immediately went to the vault^&#42;1^ of the house^&#42;2^ of El-beʹrith.

[NOTE]
====
. Or “stronghold.”
. Or “temple.”
====

[[v7-9-47]]

^<<v7-9-47,47>>^ As soon as it was reported to A·bimʹe·lech that all the leaders of the tower of Sheʹchem had gathered together,

[[v7-9-48]]

^<<v7-9-48,48>>^ A·bimʹe·lech and all the men with him went up Mount Zalʹmon. A·bimʹe·lech took an ax in his hand and cut off a tree branch and lifted it on his shoulder and said to the people with him: “What you saw me do, hurry and do the same!”

[[v7-9-49]]

^<<v7-9-49,49>>^ So all the people also cut off branches and followed A·bimʹe·lech. Then they put the branches against the vault and set the vault on fire. So all the people of the tower of Sheʹchem also died, about 1,000 men and women.

[[v7-9-50]]

^<<v7-9-50,50>>^ A·bimʹe·lech then went to Theʹbez; he camped against Theʹbez and captured it.

[[v7-9-51]]

^<<v7-9-51,51>>^ There was a strong tower in the middle of the city, and all the men and women and all the city leaders fled there. They shut themselves in and climbed onto the roof of the tower.

[[v7-9-52]]

^<<v7-9-52,52>>^ A·bimʹe·lech made his way to the tower and attacked it. He approached the entrance of the tower to set it on fire.

[[v7-9-53]]

^<<v7-9-53,53>>^ Then one of the women dropped an upper millstone on A·bimʹe·lech’s head and crushed his skull.

[[v7-9-54]]

^<<v7-9-54,54>>^ He quickly called the attendant bearing his weapons and said to him: “Draw your sword and put me to death, so that they may not say about me, ‘A woman killed him.’” So his attendant ran him through, and he died.

[[v7-9-55]]

^<<v7-9-55,55>>^ When the men of Israel saw that A·bimʹe·lech was dead, they all went back home.

[[v7-9-56]]

^<<v7-9-56,56>>^ Thus God repaid A·bimʹe·lech for the evil that he had done to his father by killing his 70 brothers.

[[v7-9-57]]

^<<v7-9-57,57>>^ God also made all the evil of the men of Sheʹchem come back on their own heads. So the curse of Joʹtham the son of Jer·ub·baʹal came upon them.

'''

xref:007-judges/007-judges-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-judges/007-judges-010.adoc#v7-10-0[Próximo Capítulo &#62;]