include::./index.adoc[]

[[v7-7-0]]
=== Judges, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-7-1]]

^<<v7-7-1,1>>^ Then Jer·ub·baʹal, that is, Gidʹe·on, and all the people with him rose early and encamped at the Spring of Haʹrod, while the camp of Midʹi·an was north of him at the hill of Moʹreh in the valley plain.^&#42;1^

[NOTE]
====
. Or “low plain.”
====

[[v7-7-2]]

^<<v7-7-2,2>>^ Jehovah now said to Gidʹe·on: “There are too many people with you for me to give Midʹi·an into their hand. Otherwise, Israel might brag about itself against me and say, ‘My own hand saved me.’

[[v7-7-3]]

^<<v7-7-3,3>>^ Now, please, announce in the presence of the people: ‘Whoever is afraid and trembling, let him return home.’” So Gidʹe·on put them to the test. With that, 22,000 of the people returned home, and 10,000 remained.

[[v7-7-4]]

^<<v7-7-4,4>>^ Still Jehovah said to Gidʹe·on: “There are yet too many people. Have them go down to the water so that I may test them for you there. When I say to you, ‘This one will go with you,’ he will go with you, but when I say to you, ‘This one will not go along with you,’ he will not go along.”

[[v7-7-5]]

^<<v7-7-5,5>>^ So he took the people down to the water.
Then Jehovah said to Gidʹe·on: “Separate everyone who laps up the water with his tongue just as a dog laps, from those who bend down on their knees to drink.”

[[v7-7-6]]

^<<v7-7-6,6>>^ The number of those lapping up the water, putting their hand to their mouth, was 300 men. The rest of the people bent down on their knees to drink.

[[v7-7-7]]

^<<v7-7-7,7>>^ Jehovah now said to Gidʹe·on: “I will save you with the 300 men who lapped the water, and I will give Midʹi·an into your hand. But let all the other people go back home.”

[[v7-7-8]]

^<<v7-7-8,8>>^ So after they took the provisions and the horns from the people, he sent all the other men of Israel back home, and he kept only the 300 men. The camp of Midʹi·an was below him in the valley plain.

[[v7-7-9]]

^<<v7-7-9,9>>^ During that night, Jehovah said to him: “Get up, attack the camp, for I have given it into your hand.

[[v7-7-10]]

^<<v7-7-10,10>>^ But if you are afraid to attack, go down to the camp with Puʹrah your attendant.

[[v7-7-11]]

^<<v7-7-11,11>>^ Listen to what they say, and afterward you will have the courage^&#42;1^ to attack the camp.” At that he and Puʹrah his attendant went down to the edge of the encamped army.

[NOTE]
====
. Lit., “your hands will grow strong.”
====

[[v7-7-12]]

^<<v7-7-12,12>>^ Now Midʹi·an and Amʹa·lek and all the Easterners covered the valley plain like a swarm of locusts, and their camels were without number, as many as the grains of sand on the seashore.

[[v7-7-13]]

^<<v7-7-13,13>>^ Gidʹe·on now came, and there was a man relating a dream to his companion, and he said: “This is the dream I had. There was a round loaf of barley bread rolling into the camp of Midʹi·an. It came to a tent and struck it so hard that it collapsed. Yes, it turned the tent upside down, and the tent fell flat.”

[[v7-7-14]]

^<<v7-7-14,14>>^ At this his companion said: “This can only be the sword of Gidʹe·on the son of Joʹash, a man of Israel. God has given Midʹi·an and all the camp into his hand.”

[[v7-7-15]]

^<<v7-7-15,15>>^ As soon as Gidʹe·on heard him relate the dream and its interpretation, he bowed down to worship. After that he returned to the camp of Israel and said: “Get up, for Jehovah has given the camp of Midʹi·an into your hand.”

[[v7-7-16]]

^<<v7-7-16,16>>^ Then he divided the 300 men into three bands and gave all of them horns and large empty jars with torches inside the jars.

[[v7-7-17]]

^<<v7-7-17,17>>^ Then he said to them: “Watch me and do exactly what I do. When I come to the edge of the camp, you should do just as I do.

[[v7-7-18]]

^<<v7-7-18,18>>^ When I blow the horn, I and all who are with me, you also must blow the horns all around the camp and shout, ‘For Jehovah and for Gidʹe·on!’”

[[v7-7-19]]

^<<v7-7-19,19>>^ Gidʹe·on and the 100 men who were with him came to the edge of the camp at the start of the middle night watch,^&#42;1^ just after the sentries were posted. They blew the horns and smashed the large water jars that were in their hands.

[NOTE]
====
. From about 10:00 p.m. to about 2:00 a.m.
====

[[v7-7-20]]

^<<v7-7-20,20>>^ So the three bands blew the horns and shattered the large jars. They held the torches in their left hands and blew the horns in their right hands and they called out: “The sword of Jehovah and of Gidʹe·on!”

[[v7-7-21]]

^<<v7-7-21,21>>^ All the while each man stood in his place all around the camp, and the whole army ran away, shouting as they fled.

[[v7-7-22]]

^<<v7-7-22,22>>^ The 300 continued to blow the horns, and Jehovah turned the sword of each one against the other throughout the camp; and the army fled as far as Beth-shitʹtah, on to Zerʹe·rah, as far as the outskirts of Aʹbel-me·hoʹlah by Tabʹbath.

[[v7-7-23]]

^<<v7-7-23,23>>^ And the men of Israel were called together from Naphʹta·li, Ashʹer, and all of Ma·nasʹseh, and they chased after Midʹi·an.

[[v7-7-24]]

^<<v7-7-24,24>>^ Gidʹe·on sent messengers into all the mountainous region of Eʹphra·im, saying: “Go down to attack Midʹi·an, and capture the access to the waters as far as Beth-barʹah and the Jordan.” So all the men of Eʹphra·im were gathered together, and they captured the waters as far as Beth-barʹah and the Jordan.

[[v7-7-25]]

^<<v7-7-25,25>>^ They also captured the two princes of Midʹi·an, Oʹreb and Zeʹeb; they killed Oʹreb on the rock of Oʹreb, and they killed Zeʹeb at the winepress of Zeʹeb. They kept on pursuing Midʹi·an, and they brought the heads of Oʹreb and Zeʹeb to Gidʹe·on in the region of the Jordan.

'''

xref:007-judges/007-judges-006.adoc#v7-6-0[&#60; Capítulo Anterior] | <<v7-7-0,Topo>> | xref:007-judges/007-judges-008.adoc#v7-8-0[Próximo Capítulo &#62;]