include::./index.adoc[]

[[v7-15-0]]
=== Judges, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-15-1]]

^<<v7-15-1,1>>^ After a while, in the days of the wheat harvest, Samson went to visit his wife, bringing a young goat. He said: “I wish to go in to my wife in the bedroom.”^&#42;1^ But her father did not allow him to go in.

[NOTE]
====
. Or “the interior room.”
====

[[v7-15-2]]

^<<v7-15-2,2>>^ Her father said: “I thought, ‘You must surely hate her.’ So I gave her to your groomsman. Is not her younger sister more attractive than she is? Please, take her instead.”

[[v7-15-3]]

^<<v7-15-3,3>>^ However, Samson said to them: “This time I cannot be blamed by the Phi·lisʹtines for harming them.”

[[v7-15-4]]

^<<v7-15-4,4>>^ So Samson went and caught 300 foxes. Then he took torches, turned the foxes tail to tail, and put one torch between each pair of tails.

[[v7-15-5]]

^<<v7-15-5,5>>^ Then he set fire to the torches and sent the foxes out into the fields of standing grain of the Phi·lisʹtines. He set on fire everything from sheaf to standing grain, as well as the vineyards and the olive groves.

[[v7-15-6]]

^<<v7-15-6,6>>^ The Phi·lisʹtines asked: “Who did this?” They were told: “It was Samson, the son-in-law of the Timʹnite, because he took his wife and gave her to his groomsman.” At that the Phi·lisʹtines went up and burned her and her father with fire.

[[v7-15-7]]

^<<v7-15-7,7>>^ Then Samson said to them: “If this is how you act, I will not quit until I take revenge on you.”

[[v7-15-8]]

^<<v7-15-8,8>>^ Then he struck them down one after the other^&#42;1^ with a great slaughter, after which he went down and stayed in a cave^&#42;2^ of the crag Eʹtam.

[NOTE]
====
. Lit., “struck them leg on thigh.”
. Or “cleft.”
====

[[v7-15-9]]

^<<v7-15-9,9>>^ Later the Phi·lisʹtines came up and camped in Judah and were tramping about in Leʹhi.

[[v7-15-10]]

^<<v7-15-10,10>>^ Then the men of Judah said: “Why have you come up against us?” to which they answered: “We have come up to capture^&#42;1^ Samson, to do to him just as he did to us.”

[NOTE]
====
. Or “tie.”
====

[[v7-15-11]]

^<<v7-15-11,11>>^ So 3,000 men of Judah went down to the cave^&#42;1^ of the crag Eʹtam and said to Samson: “Do you not know that the Phi·lisʹtines are ruling over us? So why have you done this to us?” He said to them: “As they did to me, so I did to them.”

[NOTE]
====
. Or “cleft.”
====

[[v7-15-12]]

^<<v7-15-12,12>>^ But they said to him: “We have come to capture^&#42;1^ you and to hand you over to the Phi·lisʹtines.” Then Samson said: “Swear to me that you yourselves will not assault me.”

[NOTE]
====
. Or “tie.”
====

[[v7-15-13]]

^<<v7-15-13,13>>^ They said to him: “No, we will only tie you and hand you over to them, but we will not put you to death.”
So they bound him with two new ropes and brought him up from the crag.

[[v7-15-14]]

^<<v7-15-14,14>>^ When he came to Leʹhi, the Phi·lisʹtines shouted triumphantly at meeting him. Then Jehovah’s spirit empowered him, and the ropes on his arms became like linen threads that were scorched with fire, and his fetters melted off his hands.

[[v7-15-15]]

^<<v7-15-15,15>>^ He now found a fresh jawbone of a male donkey; he reached out and grabbed it and struck down 1,000 men with it.

[[v7-15-16]]

^<<v7-15-16,16>>^ Then Samson said:
“With the jawbone of a donkey—one heap, two heaps!
With the jawbone of a donkey I struck down 1,000 men.”

[[v7-15-17]]

^<<v7-15-17,17>>^ When he finished speaking, he threw the jawbone away and called that place Raʹmath-leʹhi.^&#42;1^

[NOTE]
====
. Meaning “Lofty Place of the Jawbone.”
====

[[v7-15-18]]

^<<v7-15-18,18>>^ Then he became very thirsty, and he called on Jehovah and said: “It was you who gave this great salvation into the hand of your servant. But now am I to die of thirst and fall into the hands of the uncircumcised?”

[[v7-15-19]]

^<<v7-15-19,19>>^ So God split open a hollow that was in Leʹhi, and water flowed from it. When he drank, his spirit^&#42;1^ returned and he revived. That is why he named the place En-hak·korʹe,^&#42;2^ which is in Leʹhi to this day.

[NOTE]
====
. Or “strength.”
. Meaning “Spring of the One Calling.”
====

[[v7-15-20]]

^<<v7-15-20,20>>^ And he judged Israel in the days of the Phi·lisʹtines for 20 years.

'''

xref:007-judges/007-judges-014.adoc#v7-14-0[&#60; Capítulo Anterior] | <<v7-15-0,Topo>> | xref:007-judges/007-judges-016.adoc#v7-16-0[Próximo Capítulo &#62;]