include::./index.adoc[]

[[v7-8-0]]
=== Judges, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-8-1]]

^<<v7-8-1,1>>^ Then the men of Eʹphra·im said to him: “What have you done to us? Why did you not call us when you went to fight against Midʹi·an?” And they quarreled bitterly with him.

[[v7-8-2]]

^<<v7-8-2,2>>^ But he said to them: “What have I done compared with you? Are not the gleanings of Eʹphra·im better than the grape harvest of Abi-eʹzer?

[[v7-8-3]]

^<<v7-8-3,3>>^ It was into your hand that God gave Midʹi·an’s princes Oʹreb and Zeʹeb, and what have I done compared with you?” When he spoke this way,^&#42;1^ they calmed down.^&#42;2^

[NOTE]
====
. Lit., “word.”
. Lit., “their spirit relaxed from against him.”
====

[[v7-8-4]]

^<<v7-8-4,4>>^ Gidʹe·on then came to the Jordan and crossed it. He and the 300 men with him were tired, but they kept up the pursuit.

[[v7-8-5]]

^<<v7-8-5,5>>^ So he said to the men of Sucʹcoth: “Please give loaves of bread to the people following me, for they are tired and I am chasing after Zeʹbah and Zal·munʹna, the kings of Midʹi·an.”

[[v7-8-6]]

^<<v7-8-6,6>>^ But the princes of Sucʹcoth said: “Are the palms of Zeʹbah and Zal·munʹna already in your hand so that we should give bread to your army?”

[[v7-8-7]]

^<<v7-8-7,7>>^ At this Gidʹe·on said: “Just for that, when Jehovah gives Zeʹbah and Zal·munʹna into my hand, I will give you a thrashing with the thorns and the briars of the wilderness.”

[[v7-8-8]]

^<<v7-8-8,8>>^ And he went up from there to Pe·nuʹel and made the same request, but the men of Pe·nuʹel gave him the same answer as the men of Sucʹcoth.

[[v7-8-9]]

^<<v7-8-9,9>>^ So he said also to the men of Pe·nuʹel: “When I return in peace, I will pull down this tower.”

[[v7-8-10]]

^<<v7-8-10,10>>^ Now Zeʹbah and Zal·munʹna were in Karʹkor with their armies, about 15,000 men. These were all who remained of the entire army of the Easterners, for 120,000 men armed with swords had fallen.

[[v7-8-11]]

^<<v7-8-11,11>>^ Gidʹe·on continued up by the way of the tent dwellers east of Noʹbah and Jogʹbe·hah and attacked the camp, which was off guard.

[[v7-8-12]]

^<<v7-8-12,12>>^ When Zeʹbah and Zal·munʹna fled, he pursued and captured the two Midʹi·an·ite kings, Zeʹbah and Zal·munʹna, throwing the whole camp into a panic.

[[v7-8-13]]

^<<v7-8-13,13>>^ Gidʹe·on the son of Joʹash then returned from the war by way of the pass that goes up to Heʹres.

[[v7-8-14]]

^<<v7-8-14,14>>^ En route he captured and interrogated a young man from Sucʹcoth. So the young man wrote out for him the names of the princes and elders of Sucʹcoth, 77 men.

[[v7-8-15]]

^<<v7-8-15,15>>^ With that he went to the men of Sucʹcoth and said: “Here are Zeʹbah and Zal·munʹna about whom you taunted me, saying, ‘Are the palms of Zeʹbah and Zal·munʹna already in your hand so that we should give bread to your exhausted men?’”

[[v7-8-16]]

^<<v7-8-16,16>>^ Then he took the elders of the city and with thorns and briars of the wilderness, he taught the men of Sucʹcoth a lesson.

[[v7-8-17]]

^<<v7-8-17,17>>^ And he pulled down the tower of Pe·nuʹel and killed the men of the city.

[[v7-8-18]]

^<<v7-8-18,18>>^ He asked Zeʹbah and Zal·munʹna: “What sort of men did you kill in Taʹbor?” To this they said: “They were like you, each one looked like the son of a king.”

[[v7-8-19]]

^<<v7-8-19,19>>^ At that he said: “They were my brothers, the sons of my mother. As surely as Jehovah lives, if you had spared their lives, I would not have to kill you.”

[[v7-8-20]]

^<<v7-8-20,20>>^ Then he said to Jeʹther his firstborn: “Get up, kill them.” But the young man did not draw his sword; he was afraid, for he was still a young man.

[[v7-8-21]]

^<<v7-8-21,21>>^ So Zeʹbah and Zal·munʹna said: “Get up yourself and slay us, for a man is judged by his mightiness.”^&#42;1^ So Gidʹe·on got up and killed Zeʹbah and Zal·munʹna and took the crescent-shaped ornaments that were on the necks of their camels.

[NOTE]
====
. Or “for as a man is, so is his strength.”
====

[[v7-8-22]]

^<<v7-8-22,22>>^ Later the men of Israel said to Gidʹe·on: “Rule over us, you and your son and your grandson as well, for you saved us out of the hand of Midʹi·an.”

[[v7-8-23]]

^<<v7-8-23,23>>^ But Gidʹe·on said to them: “I will not rule over you, nor will my son rule over you. Jehovah is the one who will rule over you.”

[[v7-8-24]]

^<<v7-8-24,24>>^ Gidʹe·on continued: “Let me make one request of you: that each of you give me a nose ring from his spoil.” (For they had gold nose rings because they were Ishʹma·el·ites.)

[[v7-8-25]]

^<<v7-8-25,25>>^ They replied: “We will surely give them.” With that they spread out a robe and each man threw a nose ring from his spoil on it.

[[v7-8-26]]

^<<v7-8-26,26>>^ The weight of the gold nose rings that he had requested amounted to 1,700 gold shekels,^&#42;1^ besides the crescent-shaped ornaments, the pendants, the purple wool garments worn by the kings of Midʹi·an, and the necklaces from the camels.

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v7-8-27]]

^<<v7-8-27,27>>^ Gidʹe·on made it into an ephʹod and exhibited it in his city Ophʹrah; and all Israel committed spiritual prostitution with it there, and it served as a snare to Gidʹe·on and to his household.

[[v7-8-28]]

^<<v7-8-28,28>>^ Thus Midʹi·an was subdued before the Israelites, and they did not challenge them^&#42;1^ again; and the land had rest^&#42;2^ for 40 years in the days of Gidʹe·on.

[NOTE]
====
. Lit., “did not lift up their head.”
. Or “peace.”
====

[[v7-8-29]]

^<<v7-8-29,29>>^ So Jer·ub·baʹal the son of Joʹash returned to his home and stayed there.

[[v7-8-30]]

^<<v7-8-30,30>>^ Gidʹe·on became father to 70 sons,^&#42;1^ for he had many wives.

[NOTE]
====
. Lit., “had 70 sons who came out from his thigh.”
====

[[v7-8-31]]

^<<v7-8-31,31>>^ His concubine in Sheʹchem also bore him a son, and he named him A·bimʹe·lech.

[[v7-8-32]]

^<<v7-8-32,32>>^ And Gidʹe·on the son of Joʹash died at a good old age and was buried in the tomb of Joʹash his father in Ophʹrah of the Abi-ezʹrites.

[[v7-8-33]]

^<<v7-8-33,33>>^ As soon as Gidʹe·on died, the Israelites again committed spiritual prostitution with the Baʹals, and they appointed Baʹal-beʹrith as their god.

[[v7-8-34]]

^<<v7-8-34,34>>^ The Israelites did not remember Jehovah their God, who had rescued them from the hand of all their enemies around them;

[[v7-8-35]]

^<<v7-8-35,35>>^ nor did they show loyal love toward the household of Jer·ub·baʹal, that is Gidʹe·on, in return for all the good that he had done for Israel.

'''

xref:007-judges/007-judges-007.adoc#v7-7-0[&#60; Capítulo Anterior] | <<v7-8-0,Topo>> | xref:007-judges/007-judges-009.adoc#v7-9-0[Próximo Capítulo &#62;]