include::./index.adoc[]

[[v7-5-0]]
=== Judges, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-5-1]]

^<<v7-5-1,1>>^ On that day Debʹo·rah along with Baʹrak the son of A·binʹo·am sang this song:

[[v7-5-2]]

^<<v7-5-2,2>>^ “Because of the unbound hair^&#42;1^ in Israel,
Because of the people’s volunteering,
Praise Jehovah!

[NOTE]
====
. Or “the warriors with unbound hair.”
====

[[v7-5-3]]

^<<v7-5-3,3>>^ Listen, you kings! Give ear, you rulers!
To Jehovah I will sing.
I will sing praises^&#42;1^ to Jehovah, Israel’s God.

[NOTE]
====
. Or “make music.”
====

[[v7-5-4]]

^<<v7-5-4,4>>^ Jehovah, when you went out from Seʹir,
When you marched out of the territory of Eʹdom,
The earth shook, and the heavens poured,
The clouds poured down water.

[[v7-5-5]]

^<<v7-5-5,5>>^ Mountains melted^&#42;1^ before the face of Jehovah,
Even Siʹnai before the face of Jehovah, Israel’s God.

[NOTE]
====
. Or possibly, “quaked.”
====

[[v7-5-6]]

^<<v7-5-6,6>>^ In the days of Shamʹgar the son of Aʹnath,
In the days of Jaʹel, the roads were deserted;
Travelers kept to the back roads.

[[v7-5-7]]

^<<v7-5-7,7>>^ The villagers in Israel were no more;^&#42;1^
They were no more until I, Debʹo·rah, rose up,
Until I arose as a mother in Israel.

[NOTE]
====
. Or “ceased.”
====

[[v7-5-8]]

^<<v7-5-8,8>>^ They chose new gods;
Then there was war in the gates.
A shield could not be seen, nor a lance,
Among 40,000 in Israel.

[[v7-5-9]]

^<<v7-5-9,9>>^ My heart is with the commanders of Israel,
Who went as volunteers with the people.
Praise Jehovah!

[[v7-5-10]]

^<<v7-5-10,10>>^ You riders on tawny donkeys,
You who sit on fine carpets,
And you who walk on the road,
Consider!

[[v7-5-11]]

^<<v7-5-11,11>>^ The voices of the water distributors were heard at the watering places;
There they were recounting the righteous acts of Jehovah,
The righteous acts of his villagers in Israel.
Then Jehovah’s people went down to the gates.

[[v7-5-12]]

^<<v7-5-12,12>>^ Awake, awake, O Debʹo·rah!
Awake, awake, sing a song!
Rise up, Baʹrak! Lead your captives away, you son of A·binʹo·am!

[[v7-5-13]]

^<<v7-5-13,13>>^ Then those who were left came down to the nobles;
Jehovah’s people came down to me against the mighty.

[[v7-5-14]]

^<<v7-5-14,14>>^ Out of Eʹphra·im was their origin, those in the valley;^&#42;1^
They are following you, O Benjamin, among your peoples.
From Maʹchir the commanders went down,
And from Zebʹu·lun those who bear the recruiter’s staff.^&#42;2^

[NOTE]
====
. Or “low plain.”
. Or possibly, “those handling the equipment of a scribe.”
====

[[v7-5-15]]

^<<v7-5-15,15>>^ The princes in Isʹsa·char were with Debʹo·rah,
As was Isʹsa·char, so was Baʹrak.
Into the valley plain^&#42;1^ he was sent on foot.
Among the divisions of Reuʹben there was intense heart-searching.

[NOTE]
====
. Or “low plain.”
====

[[v7-5-16]]

^<<v7-5-16,16>>^ Why did you sit down between the two saddlebags,
Listening to them playing their pipes for the flocks?
For the divisions of Reuʹben, there was intense heart-searching.

[[v7-5-17]]

^<<v7-5-17,17>>^ Gilʹe·ad remained beyond the Jordan;
And Dan, why did he stay with the ships?
Ashʹer sat idle at the seashore,
And by his harbors^&#42;1^ he remained.

[NOTE]
====
. Or “landing places.”
====

[[v7-5-18]]

^<<v7-5-18,18>>^ Zebʹu·lun was a people who risked their lives^&#42;1^ to the point of death;
Naphʹta·li also, on the open heights.

[NOTE]
====
. Or “scorned their souls.”
====

[[v7-5-19]]

^<<v7-5-19,19>>^ Kings came, they fought;
The kings of Caʹnaan then fought
In Taʹa·nach, by the waters of Me·gidʹdo.
No spoil of silver did they take.

[[v7-5-20]]

^<<v7-5-20,20>>^ From heaven the stars fought;
From their orbits they fought against Sisʹe·ra.

[[v7-5-21]]

^<<v7-5-21,21>>^ The torrent^&#42;1^ of Kiʹshon washed them away,
The ancient torrent,^&#42;2^ the torrent^&#42;3^ of Kiʹshon.
You trampled down the powerful, O my soul.^&#42;4^

[NOTE]
====
. Or “stream.”
. Or “stream.”
. Or “stream.”
. See Glossary.
====

[[v7-5-22]]

^<<v7-5-22,22>>^ Then the hooves of horses pounded
As his stallions galloped furiously.

[[v7-5-23]]

^<<v7-5-23,23>>^ ‘Curse Meʹroz,’ said the angel of Jehovah,
‘Yes, curse its inhabitants,
For they did not come to the assistance of Jehovah,
To the assistance of Jehovah with the mighty ones.’

[[v7-5-24]]

^<<v7-5-24,24>>^ Most blessed of women is Jaʹel
The wife of Heʹber the Kenʹite;
She is most blessed of women living in tents.

[[v7-5-25]]

^<<v7-5-25,25>>^ He asked for water; she gave him milk.
In a majestic banquet bowl she offered curdled milk.^&#42;1^

[NOTE]
====
. Or “offered cream.”
====

[[v7-5-26]]

^<<v7-5-26,26>>^ With her hand she reached for the tent pin,
Her right hand for the workman’s mallet.
And she hammered Sisʹe·ra, she crushed his head,
And she smashed and pierced his temples.

[[v7-5-27]]

^<<v7-5-27,27>>^ Between her feet he collapsed; he fell and lay still;
Between her feet he collapsed and fell;
Where he collapsed, there he fell defeated.

[[v7-5-28]]

^<<v7-5-28,28>>^ From the window a woman looked out,
Sisʹe·ra’s mother peered out from the lattice,
‘Why is his chariot delayed in coming?
Why are the hoofbeats of his chariots so late?’

[[v7-5-29]]

^<<v7-5-29,29>>^ The wisest of her noble ladies would answer her;
Yes, she too would repeat to herself,

[[v7-5-30]]

^<<v7-5-30,30>>^ ‘They must be dividing the spoil they found,
A girl,^&#42;1^ two girls,^&#42;2^ to every warrior,
Spoil of dyed cloth for Sisʹe·ra, spoil of dyed cloth,
An embroidered garment, dyed cloth, two embroidered garments
For the necks of the plunderers.’

[NOTE]
====
. Lit., “womb.”
. Lit., “wombs.”
====

[[v7-5-31]]

^<<v7-5-31,31>>^ So let all your enemies perish, O Jehovah,
But let those who love you be like the sun rising in its glory.”
And the land had rest^&#42;1^ for 40 years.

[NOTE]
====
. Or “peace.”
====

'''

xref:007-judges/007-judges-004.adoc#v7-4-0[&#60; Capítulo Anterior] | <<v7-5-0,Topo>> | xref:007-judges/007-judges-006.adoc#v7-6-0[Próximo Capítulo &#62;]