include::./index.adoc[]

[[v7-4-0]]
=== Judges, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-4-1]]

^<<v7-4-1,1>>^ But after Eʹhud died, the Israelites again did what was bad in Jehovah’s eyes.

[[v7-4-2]]

^<<v7-4-2,2>>^ So Jehovah sold them into the hand of Jaʹbin the king of Caʹnaan, who reigned in Haʹzor. The chief of his army was Sisʹe·ra, who lived in Ha·roʹsheth of the nations.^&#42;1^

[NOTE]
====
. Or “Harosheth-ha-goiim.”
====

[[v7-4-3]]

^<<v7-4-3,3>>^ The Israelites cried out to Jehovah, because Jaʹbin^&#42;1^ had 900 war chariots with iron scythes,^&#42;2^ and he harshly oppressed the Israelites for 20 years.

[NOTE]
====
. Lit., “he.”
. Lit., “chariots of iron.”
====

[[v7-4-4]]

^<<v7-4-4,4>>^ Now Debʹo·rah, a prophetess, the wife of Lapʹpi·doth, was judging Israel at that time.

[[v7-4-5]]

^<<v7-4-5,5>>^ She used to sit under Debʹo·rah’s palm tree between Raʹmah and Bethʹel in the mountainous region of Eʹphra·im; the Israelites would go up to her for judgment.

[[v7-4-6]]

^<<v7-4-6,6>>^ She sent for Baʹrak the son of A·binʹo·am out of Keʹdesh-naphʹta·li and said to him: “Has not Jehovah the God of Israel given the command? ‘Go and march to^&#42;1^ Mount Taʹbor, and take 10,000 men of Naphʹta·li and Zebʹu·lun with you.

[NOTE]
====
. Or “Deploy your men on.”
====

[[v7-4-7]]

^<<v7-4-7,7>>^ I will bring to you Sisʹe·ra, the chief of Jaʹbin’s army, along with his war chariots and his troops to the stream^&#42;1^ of Kiʹshon, and I will give him into your hand.’”

[NOTE]
====
. Or “wadi.”
====

[[v7-4-8]]

^<<v7-4-8,8>>^ At this Baʹrak said to her: “If you go with me, I will go, but if you do not go with me, I will not go.”

[[v7-4-9]]

^<<v7-4-9,9>>^ To this she said: “I will certainly go with you. However, the campaign you are going on will not bring you glory, for it will be into the hand of a woman that Jehovah will give Sisʹe·ra.” Then Debʹo·rah got up and went with Baʹrak to Keʹdesh.

[[v7-4-10]]

^<<v7-4-10,10>>^ Baʹrak summoned Zebʹu·lun and Naphʹta·li to Keʹdesh, and 10,000 men followed his steps. Debʹo·rah also went up with him.

[[v7-4-11]]

^<<v7-4-11,11>>^ Incidentally, Heʹber the Kenʹite had separated from the Kenʹites, the descendants of Hoʹbab, Moses’ father-in-law, and his tent was pitched near the big tree in Za·a·nanʹnim, which is at Keʹdesh.

[[v7-4-12]]

^<<v7-4-12,12>>^ They reported to Sisʹe·ra that Baʹrak the son of A·binʹo·am had gone up to Mount Taʹbor.

[[v7-4-13]]

^<<v7-4-13,13>>^ At once Sisʹe·ra assembled all his war chariots—900 chariots with iron scythes^&#42;1^—and all the troops that were with him from Ha·roʹsheth of the nations to go to the stream^&#42;2^ of Kiʹshon.

[NOTE]
====
. Lit., “chariots of iron.”
. Or “wadi.”
====

[[v7-4-14]]

^<<v7-4-14,14>>^ Debʹo·rah now said to Baʹrak: “Rise up, for this is the day that Jehovah will give Sisʹe·ra into your hand. Is Jehovah not going out before you?” And Baʹrak descended from Mount Taʹbor with 10,000 men following him.

[[v7-4-15]]

^<<v7-4-15,15>>^ Then Jehovah threw Sisʹe·ra and all his war chariots and all the army into confusion before the sword of Baʹrak. Finally Sisʹe·ra got down from his chariot and fled on foot.

[[v7-4-16]]

^<<v7-4-16,16>>^ Baʹrak chased after the war chariots and the army as far as Ha·roʹsheth of the nations. So Sisʹe·ra’s whole army fell by the sword; not even one remained.

[[v7-4-17]]

^<<v7-4-17,17>>^ But Sisʹe·ra fled on foot to the tent of Jaʹel the wife of Heʹber the Kenʹite, for there was peace between Jaʹbin the king of Haʹzor and the house of Heʹber the Kenʹite.

[[v7-4-18]]

^<<v7-4-18,18>>^ Then Jaʹel came out to meet Sisʹe·ra and said to him: “Come in, my lord, come in here. Do not be afraid.” So he went into her tent, and she covered him with a blanket.

[[v7-4-19]]

^<<v7-4-19,19>>^ Then he said to her: “Give me, please, a little water to drink, for I am thirsty.” So she opened a skin bottle of milk and gave him a drink, after which she again covered him.

[[v7-4-20]]

^<<v7-4-20,20>>^ He told her: “Stand at the entrance of the tent, and if anybody comes and asks you, ‘Is there a man here?’ say, ‘No!’”

[[v7-4-21]]

^<<v7-4-21,21>>^ But Jaʹel the wife of Heʹber took a tent pin and a hammer in her hand. Then while he was fast asleep and exhausted, she stealthily approached him and drove the pin through his temples and beat it into the ground, and he died.

[[v7-4-22]]

^<<v7-4-22,22>>^ Baʹrak went there in pursuit of Sisʹe·ra, and Jaʹel now came out to meet him and said: “Come and I will show you the man you are looking for.” He went in with her and saw Sisʹe·ra lying dead, with the tent pin through his temples.

[[v7-4-23]]

^<<v7-4-23,23>>^ So on that day, God subdued Jaʹbin the king of Caʹnaan before the Israelites.

[[v7-4-24]]

^<<v7-4-24,24>>^ The hand of the Israelites came down harder and harder against Jaʹbin the king of Caʹnaan, until they destroyed Jaʹbin the king of Caʹnaan.

'''

xref:007-judges/007-judges-003.adoc#v7-3-0[&#60; Capítulo Anterior] | <<v7-4-0,Topo>> | xref:007-judges/007-judges-005.adoc#v7-5-0[Próximo Capítulo &#62;]