include::./index.adoc[]

[[v7-19-0]]
=== Judges, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-19-1]]

^<<v7-19-1,1>>^ In those days, when there was no king in Israel, a Levite who was then living in a remote part of the mountainous region of Eʹphra·im took a concubine from Bethʹle·hem in Judah as his wife.

[[v7-19-2]]

^<<v7-19-2,2>>^ But his concubine was unfaithful to him, and she left him to go to her father’s house at Bethʹle·hem in Judah. She remained there for four months.

[[v7-19-3]]

^<<v7-19-3,3>>^ Then her husband went after her to persuade her to come back; he had his male attendant and a couple of donkeys with him. So she brought him into her father’s house. When her father saw him, he was glad to meet him.

[[v7-19-4]]

^<<v7-19-4,4>>^ So his father-in-law, the young woman’s father, convinced him to stay with him three days; and they would eat and drink, and he would spend the night there.

[[v7-19-5]]

^<<v7-19-5,5>>^ On the fourth day, when they got up early in the morning to go, the father of the young woman said to his son-in-law: “Eat something to give you strength,^&#42;1^ and then you may go.”

[NOTE]
====
. Or “to sustain your heart.”
====

[[v7-19-6]]

^<<v7-19-6,6>>^ So they sat down, and they both ate and drank together; after that the father of the young woman said to the man: “Please, stay overnight and enjoy yourself.”^&#42;1^

[NOTE]
====
. Or “make your heart feel good.”
====

[[v7-19-7]]

^<<v7-19-7,7>>^ When the man rose to go, his father-in-law kept begging him, so he stayed overnight again.

[[v7-19-8]]

^<<v7-19-8,8>>^ When he got up early in the morning on the fifth day to go, the father of the young woman said: “Please, eat something to give you strength.”^&#42;1^ And they lingered until it was late in the day, and they both kept eating.

[NOTE]
====
. Or “to sustain your heart.”
====

[[v7-19-9]]

^<<v7-19-9,9>>^ When the man rose to go with his concubine and his attendant, his father-in-law, the young woman’s father, said to him: “Look, now! It is almost evening. Please, stay overnight. Here the day is coming to an end. Stay here overnight and enjoy yourself. Tomorrow you can get up early for your journey and go to your home.”^&#42;1^

[NOTE]
====
. Lit., “tent.”
====

[[v7-19-10]]

^<<v7-19-10,10>>^ However, the man did not want to stay another night, so he got up and traveled as far as Jeʹbus, that is, Jerusalem. He had with him the two saddled donkeys, his concubine, and his attendant.

[[v7-19-11]]

^<<v7-19-11,11>>^ When they were close to Jeʹbus, the daylight was nearly gone. So the attendant said to his master: “Should we stop at this city of the Jebʹu·sites and stay overnight here?”

[[v7-19-12]]

^<<v7-19-12,12>>^ But his master said to him: “We should not stop at a city of foreigners who are not Israelites. We will go on as far as Gibʹe·ah.”

[[v7-19-13]]

^<<v7-19-13,13>>^ Then he said to his attendant: “Come and let us try to reach one of those places; we will stay overnight either in Gibʹe·ah or in Raʹmah.”

[[v7-19-14]]

^<<v7-19-14,14>>^ So they went on their way, and the sun began to set when they were near Gibʹe·ah, which belongs to Benjamin.

[[v7-19-15]]

^<<v7-19-15,15>>^ So they stopped there and went in to stay overnight in Gibʹe·ah. Once inside, they sat down in the public square of the city, but nobody took them into his house to stay overnight.

[[v7-19-16]]

^<<v7-19-16,16>>^ Eventually that evening, an old man came in from his work in the field. He was from the mountainous region of Eʹphra·im, and he was living for a time in Gibʹe·ah; but the residents of the city were Benʹja·min·ites.

[[v7-19-17]]

^<<v7-19-17,17>>^ When he looked up and saw the traveler in the public square of the city, the old man said: “Where are you going, and where do you come from?”

[[v7-19-18]]

^<<v7-19-18,18>>^ He replied: “We are traveling from Bethʹle·hem in Judah to a remote area of the mountainous region of Eʹphra·im, where I am from. I went to Bethʹle·hem in Judah, and I am going to the house of Jehovah,^&#42;1^ but nobody is taking me into his house.

[NOTE]
====
. Or possibly, “and I serve at the house of Jehovah.”
====

[[v7-19-19]]

^<<v7-19-19,19>>^ We have enough straw and fodder for our donkeys, and bread and wine for me, the woman, and our attendant. There is nothing lacking.”

[[v7-19-20]]

^<<v7-19-20,20>>^ However, the old man said: “May you have peace! Let me take care of anything you need. Just do not stay overnight in the public square.”

[[v7-19-21]]

^<<v7-19-21,21>>^ So he brought him into his house and gave feed^&#42;1^ to the donkeys. Then they washed their feet and ate and drank.

[NOTE]
====
. Or “gave mixed fodder.”
====

[[v7-19-22]]

^<<v7-19-22,22>>^ While they were enjoying themselves, some worthless men of the city surrounded the house and were pounding on the door, and they kept saying to the old man who owned the house: “Bring out the man who came into your house, so that we may have sex with him.”

[[v7-19-23]]

^<<v7-19-23,23>>^ At that the owner of the house went out and said to them: “No, my brothers, do not act wickedly. Please, this man is a guest in my house. Do not commit this disgraceful act.

[[v7-19-24]]

^<<v7-19-24,24>>^ Here are my virgin daughter and this man’s concubine. Let me bring them out, and you can humiliate them if you must.^&#42;1^ But you must not commit this disgraceful act toward this man.”

[NOTE]
====
. Or “abuse them and do what is good in your eyes.”
====

[[v7-19-25]]

^<<v7-19-25,25>>^ But the men refused to listen to him, so the man grabbed hold of his concubine and brought her outside to them. They raped her and abused her all night long until the morning. Then they sent her away at the break of dawn.

[[v7-19-26]]

^<<v7-19-26,26>>^ Early in the morning, the woman came and fell down at the entrance of the man’s house where her master was and lay there until it was light.

[[v7-19-27]]

^<<v7-19-27,27>>^ When her master got up in the morning and opened the doors of the house to go out to resume his journey, he saw the woman, his concubine, lying at the entrance of the house with her hands on the threshold.

[[v7-19-28]]

^<<v7-19-28,28>>^ So he said to her: “Get up; let us go.” But there was no answer. The man then put her on the donkey and set out for his home.

[[v7-19-29]]

^<<v7-19-29,29>>^ When he reached his house, he took the slaughtering knife and took hold of his concubine and cut her up limb by limb into 12 pieces and sent one piece into each territory of Israel.

[[v7-19-30]]

^<<v7-19-30,30>>^ All who saw it said: “Such a thing has never happened or been seen from the day that the Israelites went up out of the land of Egypt down to this day. Consider it,^&#42;1^ take counsel, and tell us what to do.”

[NOTE]
====
. Or “Set your hearts on it.”
====

'''

xref:007-judges/007-judges-018.adoc#v7-18-0[&#60; Capítulo Anterior] | <<v7-19-0,Topo>> | xref:007-judges/007-judges-020.adoc#v7-20-0[Próximo Capítulo &#62;]