include::./index.adoc[]

[[v7-6-0]]
=== Judges, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-6-1]]

^<<v7-6-1,1>>^ But the Israelites again did what was bad in the eyes of Jehovah, so Jehovah gave them into the hand of Midʹi·an for seven years.

[[v7-6-2]]

^<<v7-6-2,2>>^ The hand of Midʹi·an dominated over Israel. Because of Midʹi·an, the Israelites made hiding places^&#42;1^ for themselves in the mountains, in the caves, and in the places difficult to approach.

[NOTE]
====
. Or possibly, “underground storage places.”
====

[[v7-6-3]]

^<<v7-6-3,3>>^ If Israel sowed seed, Midʹi·an and Amʹa·lek and the Easterners would attack them.

[[v7-6-4]]

^<<v7-6-4,4>>^ They would camp against them and ruin the produce of the land all the way to Gazʹa, and they left nothing for Israel to eat and no sheep or bull or donkey.

[[v7-6-5]]

^<<v7-6-5,5>>^ For they would come up with their livestock and tents as numerous as the locusts, and they and their camels could not be numbered, and they would come into the land to destroy it.

[[v7-6-6]]

^<<v7-6-6,6>>^ So Israel became greatly impoverished on account of Midʹi·an; and the Israelites called to Jehovah for help.

[[v7-6-7]]

^<<v7-6-7,7>>^ When the Israelites called to Jehovah for help because of Midʹi·an,

[[v7-6-8]]

^<<v7-6-8,8>>^ Jehovah sent to the Israelites a prophet who said to them: “This is what Jehovah the God of Israel says, ‘I brought you up from Egypt and thus brought you out of the house of slavery.

[[v7-6-9]]

^<<v7-6-9,9>>^ So I rescued you from the hand of Egypt and from all your oppressors and drove them out from before you and gave you their land.

[[v7-6-10]]

^<<v7-6-10,10>>^ And I said to you: “I am Jehovah your God. You must not fear the gods of the Amʹor·ites in whose land you are dwelling.” But you did not obey me.’”^&#42;1^

[NOTE]
====
. Lit., “listen to my voice.”
====

[[v7-6-11]]

^<<v7-6-11,11>>^ Later Jehovah’s angel came and sat under the big tree that was in Ophʹrah, which belonged to Joʹash the Abi-ezʹrite. His son Gidʹe·on was beating out wheat in the winepress in order to hide it from Midʹi·an.

[[v7-6-12]]

^<<v7-6-12,12>>^ Jehovah’s angel appeared to him and said: “Jehovah is with you, you mighty warrior.”

[[v7-6-13]]

^<<v7-6-13,13>>^ At this Gidʹe·on said to him: “Pardon me, my lord, but if Jehovah is with us, why has all of this come upon us? Where are all his wonderful acts that our fathers related to us, saying, ‘Did Jehovah not bring us up out of Egypt?’ Now Jehovah has deserted us and given us into Midʹi·an’s hand.”

[[v7-6-14]]

^<<v7-6-14,14>>^ Jehovah faced him and said: “Go with the strength you have, and you will save Israel out of Midʹi·an’s hand. Is it not I who send you?”

[[v7-6-15]]

^<<v7-6-15,15>>^ Gidʹe·on answered him: “Pardon me, Jehovah. How can I save Israel? Look! My clan^&#42;1^ is the least in Ma·nasʹseh, and I am the most insignificant in my father’s house.”

[NOTE]
====
. Lit., “thousand.”
====

[[v7-6-16]]

^<<v7-6-16,16>>^ But Jehovah said to him: “Because I will be with you, you will strike down Midʹi·an as if they were one man.”

[[v7-6-17]]

^<<v7-6-17,17>>^ Then he said to him: “If, now, I have found favor in your eyes, show me a sign that you are the one speaking with me.

[[v7-6-18]]

^<<v7-6-18,18>>^ Please do not depart from here until I return with my gift and set it before you.” So he said: “I will stay here until you return.”

[[v7-6-19]]

^<<v7-6-19,19>>^ And Gidʹe·on went in and prepared a young goat and made unleavened bread from an eʹphah^&#42;1^ of flour. He put the meat in the basket and the broth in the cooking pot; then he brought them out to him and served them under the big tree.

[NOTE]
====
. About 22 L (20 dry qt). See App. B14.
====

[[v7-6-20]]

^<<v7-6-20,20>>^ The angel of the true God now said to him: “Take the meat and the unleavened bread and place them on the big rock there, and pour out the broth.” And he did so.

[[v7-6-21]]

^<<v7-6-21,21>>^ Then Jehovah’s angel stretched out the tip of the staff that was in his hand and touched the meat and the unleavened bread, and fire flared up from the rock and consumed the meat and the unleavened bread. Jehovah’s angel then vanished from his sight.

[[v7-6-22]]

^<<v7-6-22,22>>^ Gidʹe·on now realized that it was Jehovah’s angel.
At once Gidʹe·on said: “Alas, Sovereign Lord Jehovah, for I have seen Jehovah’s angel face-to-face!”

[[v7-6-23]]

^<<v7-6-23,23>>^ But Jehovah said to him: “Peace be with you. Have no fear; you will not die.”

[[v7-6-24]]

^<<v7-6-24,24>>^ So Gidʹe·on built an altar there to Jehovah, and it is called Je·hoʹvah-shaʹlom^&#42;1^ down to this day. It is still in Ophʹrah of the Abi-ezʹrites.

[NOTE]
====
. Meaning “Jehovah Is Peace.”
====

[[v7-6-25]]

^<<v7-6-25,25>>^ That night Jehovah said to him: “Take the young bull that belongs to your father, the second young bull that is seven years old, and tear down the altar of Baʹal that belongs to your father, and cut down the sacred pole^&#42;1^ next to it.

[NOTE]
====
. See Glossary.
====

[[v7-6-26]]

^<<v7-6-26,26>>^ After you build an altar to Jehovah your God on top of this stronghold with the row of stones, take the second young bull and offer it as a burnt offering on the pieces of wood from the sacred pole^&#42;1^ that you cut down.”

[NOTE]
====
. See Glossary.
====

[[v7-6-27]]

^<<v7-6-27,27>>^ So Gidʹe·on took ten men of his servants and did just as Jehovah told him. But he feared the household of his father and the men of the city too much to do it by day, so he did it at night.

[[v7-6-28]]

^<<v7-6-28,28>>^ When the men of the city got up early the next morning, they saw that the altar of Baʹal had been pulled down and the sacred pole^&#42;1^ beside it had been cut down and the second young bull had been offered up on the altar that had been built.

[NOTE]
====
. See Glossary.
====

[[v7-6-29]]

^<<v7-6-29,29>>^ They asked one another: “Who did this?” After they investigated, they said: “Gidʹe·on the son of Joʹash did this.”

[[v7-6-30]]

^<<v7-6-30,30>>^ So the men of the city said to Joʹash: “Bring your son out that he may die, because he pulled down the altar of Baʹal and cut down the sacred pole^&#42;1^ next to it.”

[NOTE]
====
. See Glossary.
====

[[v7-6-31]]

^<<v7-6-31,31>>^ Joʹash then said to all those who confronted him: “Do you have to defend Baʹal? Do you have to save him? Whoever defends him should be put to death this morning. If he is a god, let him defend himself, since someone pulled down his altar.”

[[v7-6-32]]

^<<v7-6-32,32>>^ And he called Gidʹe·on Jer·ub·baʹal^&#42;1^ on that day, saying: “Let Baʹal defend himself, for someone has pulled down his altar.”

[NOTE]
====
. Meaning “Let Baal Make a Legal Defense (Contend).”
====

[[v7-6-33]]

^<<v7-6-33,33>>^ All Midʹi·an and Amʹa·lek and the Easterners joined forces; and they crossed over^&#42;1^ into the Valley^&#42;2^ of Jezʹre·el and camped.

[NOTE]
====
. Or “crossed the river.”
. Or “Low Plain.”
====

[[v7-6-34]]

^<<v7-6-34,34>>^ Then Jehovah’s spirit came upon^&#42;1^ Gidʹe·on and he sounded the horn, and the Abi-ezʹrites rallied behind him.

[NOTE]
====
. Lit., “clothed.”
====

[[v7-6-35]]

^<<v7-6-35,35>>^ He sent out messengers through all of Ma·nasʹseh, and they too rallied behind him. He also sent out messengers through Ashʹer, Zebʹu·lun, and Naphʹta·li, and they came up to meet him.

[[v7-6-36]]

^<<v7-6-36,36>>^ Then Gidʹe·on said to the true God: “If you are saving Israel by means of me, just as you have promised,

[[v7-6-37]]

^<<v7-6-37,37>>^ here I am laying a fleece of wool on the threshing floor. If there is dew on the fleece only but all the ground around it is dry, then I will know that you will save Israel by means of me, just as you have promised.”

[[v7-6-38]]

^<<v7-6-38,38>>^ And that is how it happened. When he rose up early the next day and wrung the fleece, he squeezed off enough dew from the fleece to fill a large banquet bowl with water.

[[v7-6-39]]

^<<v7-6-39,39>>^ However, Gidʹe·on said to the true God: “Do not let your anger burn against me, but let me ask just once more. Let me, please, make just one more test with the fleece. Please let the fleece alone be dry while there is dew all over the ground.”

[[v7-6-40]]

^<<v7-6-40,40>>^ So that is what God did that night; only the fleece was dry, and there was dew all over the ground.

'''

xref:007-judges/007-judges-005.adoc#v7-5-0[&#60; Capítulo Anterior] | <<v7-6-0,Topo>> | xref:007-judges/007-judges-007.adoc#v7-7-0[Próximo Capítulo &#62;]