include::./index.adoc[]

[[v7-13-0]]
=== Judges, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-13-1]]

^<<v7-13-1,1>>^ Again the Israelites did what was bad in Jehovah’s eyes, and Jehovah gave them into the hand of the Phi·lisʹtines for 40 years.

[[v7-13-2]]

^<<v7-13-2,2>>^ Meanwhile, there was a man of Zorʹah of the family of the Danʹites, whose name was Ma·noʹah. His wife was barren and childless.

[[v7-13-3]]

^<<v7-13-3,3>>^ In time Jehovah’s angel appeared to the woman and said to her: “Look, you are barren and childless. But you will conceive and give birth to a son.

[[v7-13-4]]

^<<v7-13-4,4>>^ Now be careful not to drink wine or anything alcoholic, and do not eat anything unclean.

[[v7-13-5]]

^<<v7-13-5,5>>^ Look! You will conceive and give birth to a son, and no razor should touch his head, because the child will be a Nazʹi·rite of God from birth,^&#42;1^ and he will take the lead in saving Israel out of the hand of the Phi·lisʹtines.”

[NOTE]
====
. Lit., “from the womb.”
====

[[v7-13-6]]

^<<v7-13-6,6>>^ Then the woman went and told her husband: “A man of the true God came to me, and his appearance was like an angel of the true God, very awe-inspiring. I did not ask him where he was from, nor did he tell me his name.

[[v7-13-7]]

^<<v7-13-7,7>>^ But he said to me, ‘Look! You will conceive and give birth to a son. Now do not drink wine or anything alcoholic, and do not eat anything unclean, because the child will be a Nazʹi·rite of God from birth^&#42;1^ until the day of his death.’”

[NOTE]
====
. Lit., “from the womb.”
====

[[v7-13-8]]

^<<v7-13-8,8>>^ Ma·noʹah pleaded with Jehovah and said: “Pardon me, Jehovah. Please let the man of the true God whom you just sent come again to instruct us about what we should do with the child who will be born.”

[[v7-13-9]]

^<<v7-13-9,9>>^ So the true God listened to Ma·noʹah, and the angel of the true God came again to the woman while she was sitting in the field; her husband Ma·noʹah was not with her.

[[v7-13-10]]

^<<v7-13-10,10>>^ The woman quickly ran and told her husband: “Look! The man who came to me the other day has appeared to me.”

[[v7-13-11]]

^<<v7-13-11,11>>^ Then Ma·noʹah got up and went with his wife. He came to the man and said to him: “Are you the man who spoke to my wife?” He said: “I am.”

[[v7-13-12]]

^<<v7-13-12,12>>^ Then Ma·noʹah said: “May your words come true! What will be the child’s manner of life, and what will be his work?”

[[v7-13-13]]

^<<v7-13-13,13>>^ So Jehovah’s angel said to Ma·noʹah: “Your wife should keep herself from everything that I mentioned to her.

[[v7-13-14]]

^<<v7-13-14,14>>^ She should not eat anything that the grapevine produces, she should not drink wine or anything alcoholic, and she should not eat anything unclean. Everything that I commanded her, let her observe.”

[[v7-13-15]]

^<<v7-13-15,15>>^ Ma·noʹah now said to Jehovah’s angel: “Please stay, and let us prepare a young goat for you.”

[[v7-13-16]]

^<<v7-13-16,16>>^ But Jehovah’s angel said to Ma·noʹah: “If I stay, I will not eat your food; but if you wish to present a burnt offering to Jehovah, you may offer it up.” Ma·noʹah did not know that he was Jehovah’s angel.

[[v7-13-17]]

^<<v7-13-17,17>>^ Then Ma·noʹah said to Jehovah’s angel: “What is your name, so that we may honor you when your word comes true?”

[[v7-13-18]]

^<<v7-13-18,18>>^ However, Jehovah’s angel said to him: “Why are you asking about my name, seeing that it is a wonderful one?”

[[v7-13-19]]

^<<v7-13-19,19>>^ Then Ma·noʹah took the young goat and the grain offering and offered them on the rock to Jehovah. And He was doing something amazing while Ma·noʹah and his wife were looking on.

[[v7-13-20]]

^<<v7-13-20,20>>^ As the flame ascended from the altar heavenward, Jehovah’s angel ascended in the flame from the altar while Ma·noʹah and his wife were looking on. At once they fell with their faces to the ground.

[[v7-13-21]]

^<<v7-13-21,21>>^ Jehovah’s angel did not appear again to Ma·noʹah and his wife. Then Ma·noʹah realized that he was Jehovah’s angel.

[[v7-13-22]]

^<<v7-13-22,22>>^ Ma·noʹah then said to his wife: “We are sure to die, because it is God whom we have seen.”

[[v7-13-23]]

^<<v7-13-23,23>>^ But his wife said to him: “If Jehovah wanted to put us to death, he would not have accepted a burnt offering and a grain offering from our hand, he would not have shown us all these things, and he would not have told us any of these things.”

[[v7-13-24]]

^<<v7-13-24,24>>^ The woman later gave birth to a son and named him Samson; and as the boy grew, Jehovah continued to bless him.

[[v7-13-25]]

^<<v7-13-25,25>>^ In time Jehovah’s spirit started to impel him in Maʹha·neh-dan, between Zorʹah and Eshʹta·ol.

'''

xref:007-judges/007-judges-012.adoc#v7-12-0[&#60; Capítulo Anterior] | <<v7-13-0,Topo>> | xref:007-judges/007-judges-014.adoc#v7-14-0[Próximo Capítulo &#62;]