include::./index.adoc[]

[[v7-18-0]]
=== Judges, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-18-1]]

^<<v7-18-1,1>>^ In those days there was no king in Israel. And in those days the tribe of the Danʹites was looking for an inheritance to dwell in, because until then they had not received an inheritance among the tribes of Israel.

[[v7-18-2]]

^<<v7-18-2,2>>^ The Danʹites sent five men from among their family, capable men from Zorʹah and Eshʹta·ol, to spy out the land and to explore it. They said to them: “Go, explore the land.” When they came to the mountainous region of Eʹphra·im, to the house of Miʹcah, they spent the night there.

[[v7-18-3]]

^<<v7-18-3,3>>^ While they were near the house of Miʹcah, they recognized the voice^&#42;1^ of the young Levite man, so they went over to him and asked: “Who brought you here? What are you doing in this place? What is keeping you here?”

[NOTE]
====
. Or “accent.”
====

[[v7-18-4]]

^<<v7-18-4,4>>^ He replied to them: “Thus and so Miʹcah did for me, and he hired me to serve as priest for him.”

[[v7-18-5]]

^<<v7-18-5,5>>^ Then they said to him: “Please ask God whether our journey will be successful.”

[[v7-18-6]]

^<<v7-18-6,6>>^ The priest said to them: “Go in peace. Jehovah is with you on your journey.”

[[v7-18-7]]

^<<v7-18-7,7>>^ So the five men went on and came to Laʹish. They saw how the people in it were dwelling in self-reliance in the manner of the Si·doʹni·ans. They were quiet and unsuspecting, and no oppressive conqueror was in the land to disturb them. They were far away from the Si·doʹni·ans, and they had no dealings with anyone else.

[[v7-18-8]]

^<<v7-18-8,8>>^ When they returned to their brothers at Zorʹah and Eshʹta·ol, their brothers said to them: “How did it go?”

[[v7-18-9]]

^<<v7-18-9,9>>^ They replied: “Let us go up against them, for we have seen that the land is very good. Why are you hesitant? Do not delay to go in to take possession of the land.

[[v7-18-10]]

^<<v7-18-10,10>>^ When you arrive, you will find an unsuspecting people, and the land is spacious. God has given it into your hand, a place where there is no lack of anything on the earth.”

[[v7-18-11]]

^<<v7-18-11,11>>^ Then 600 men armed for battle from the family of the Danʹites departed from Zorʹah and Eshʹta·ol.

[[v7-18-12]]

^<<v7-18-12,12>>^ They went up and camped at Kirʹi·ath-jeʹa·rim in Judah. That is why that place, which is west of Kirʹi·ath-jeʹa·rim, is called Maʹha·neh-dan^&#42;1^ to this day.

[NOTE]
====
. Meaning “Camp of Dan.”
====

[[v7-18-13]]

^<<v7-18-13,13>>^ They went from there to the mountainous region of Eʹphra·im and came to the house of Miʹcah.

[[v7-18-14]]

^<<v7-18-14,14>>^ Then the five men who had gone to spy out the land of Laʹish said to their brothers: “Did you know that there are in these houses an ephʹod, teraphim statues,^&#42;1^ a carved image, and a metal statue?^&#42;2^ Think about what you should do.”

[NOTE]
====
. Or “household gods; idols.”
. Or “molten statue.”
====

[[v7-18-15]]

^<<v7-18-15,15>>^ So they stopped there and came to the house of the young Levite man at the house of Miʹcah and asked how he was.

[[v7-18-16]]

^<<v7-18-16,16>>^ All the while the 600 men of Dan, armed for battle, stood at the entrance of the gate.

[[v7-18-17]]

^<<v7-18-17,17>>^ The five men who had gone to spy out the land went inside to take the carved image, the ephʹod, the teraphim statues,^&#42;1^ and the metal image.^&#42;2^ (The priest was standing at the entrance of the gate with the 600 men armed for battle.)

[NOTE]
====
. Or “household gods; idols.”
. Or “molten statue.”
====

[[v7-18-18]]

^<<v7-18-18,18>>^ They went into the house of Miʹcah and took the carved image, the ephʹod, the teraphim statues,^&#42;1^ and the metal image.^&#42;2^ The priest said to them: “What are you doing?”

[NOTE]
====
. Or “household gods; idols.”
. Or “molten statue.”
====

[[v7-18-19]]

^<<v7-18-19,19>>^ But they said to him: “Be quiet. Put your hand over your mouth, and come with us to be a father^&#42;1^ and a priest for us. Which is better—for you to be a priest to the house of one man or to become a priest to a tribe and family in Israel?”

[NOTE]
====
. Or “an adviser.”
====

[[v7-18-20]]

^<<v7-18-20,20>>^ So the priest was satisfied, and he took the ephʹod, the teraphim statues,^&#42;1^ and the carved image and went off with the people.

[NOTE]
====
. Or “household gods; idols.”
====

[[v7-18-21]]

^<<v7-18-21,21>>^ Then they turned to go on their way, putting the children, the livestock, and the valuable things ahead of them.

[[v7-18-22]]

^<<v7-18-22,22>>^ They had gone some distance away from the house of Miʹcah when the men who lived in the houses near the house of Miʹcah gathered together and caught up with the Danʹites.

[[v7-18-23]]

^<<v7-18-23,23>>^ When they cried out to the Danʹites, they turned to face them and said to Miʹcah: “What is the matter? Why have you been gathered together?”

[[v7-18-24]]

^<<v7-18-24,24>>^ So he said: “You have taken my gods that I made, and you have gone off with the priest too. What do I have left? How, then, can you ask me, ‘What is the matter with you?’”

[[v7-18-25]]

^<<v7-18-25,25>>^ The Danʹites replied: “Do not raise your voice against us; otherwise, angry men^&#42;1^ may assault you, and that would cost you your life^&#42;2^ and the lives^&#42;3^ of your household.”

[NOTE]
====
. Or “men bitter of soul.”
. Or “soul.”
. Or “souls.”
====

[[v7-18-26]]

^<<v7-18-26,26>>^ So the Danʹites went on their way; and Miʹcah, seeing that they were stronger than he was, turned and went back to his house.

[[v7-18-27]]

^<<v7-18-27,27>>^ After they took what Miʹcah had made, as well as his priest, they went to Laʹish, to a people quiet and unsuspecting. They struck them down with the sword and burned the city with fire.

[[v7-18-28]]

^<<v7-18-28,28>>^ There was no one to rescue it, for it was far from Siʹdon and they had no dealings with anyone else and it was in the valley plain^&#42;1^ that belonged to Beth-reʹhob. Then they rebuilt the city and settled in it.

[NOTE]
====
. Or “low plain.”
====

[[v7-18-29]]

^<<v7-18-29,29>>^ Furthermore, they named the city Dan after the name of their father, Dan, who was born to Israel. But Laʹish was the city’s former name.

[[v7-18-30]]

^<<v7-18-30,30>>^ After that the Danʹites set up the carved image for themselves, and Jonʹa·than the son of Gerʹshom, the son of Moses, and his sons became priests to the tribe of the Danʹites until the day that the inhabitants of the land went into exile.

[[v7-18-31]]

^<<v7-18-31,31>>^ And they set up the carved image that Miʹcah had made, and it remained there all the days that the house of the true God was in Shiʹloh.

'''

xref:007-judges/007-judges-017.adoc#v7-17-0[&#60; Capítulo Anterior] | <<v7-18-0,Topo>> | xref:007-judges/007-judges-019.adoc#v7-19-0[Próximo Capítulo &#62;]