include::./index.adoc[]

[[v7-10-0]]
=== Judges, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-10-1]]

^<<v7-10-1,1>>^ After A·bimʹe·lech, Toʹla the son of Puʹah, the son of Doʹdo, a man of Isʹsa·char, rose up to save Israel. He lived in Shaʹmir in the mountainous region of Eʹphra·im.

[[v7-10-2]]

^<<v7-10-2,2>>^ He judged Israel for 23 years. Then he died and was buried in Shaʹmir.

[[v7-10-3]]

^<<v7-10-3,3>>^ After him Jaʹir the Gilʹe·ad·ite rose up and judged Israel for 22 years.

[[v7-10-4]]

^<<v7-10-4,4>>^ He had 30 sons who rode on 30 donkeys, and they had 30 cities, which to this day are called Havʹvoth-jaʹir; they are in the land of Gilʹe·ad.

[[v7-10-5]]

^<<v7-10-5,5>>^ After that Jaʹir died and was buried in Kaʹmon.

[[v7-10-6]]

^<<v7-10-6,6>>^ Again the Israelites did what was bad in the eyes of Jehovah, and they began to serve the Baʹals, the Ashʹto·reth images, the gods of Aʹram,^&#42;1^ the gods of Siʹdon, the gods of Moʹab, the gods of the Amʹmon·ites, and the gods of the Phi·lisʹtines. They abandoned Jehovah and did not serve him.

[NOTE]
====
. Or “Syria.”
====

[[v7-10-7]]

^<<v7-10-7,7>>^ Then Jehovah’s anger blazed against Israel, and he sold them into the hands of the Phi·lisʹtines and the Amʹmon·ites.

[[v7-10-8]]

^<<v7-10-8,8>>^ So they crushed and greatly oppressed the Israelites in that year—for 18 years they oppressed all the Israelites on the side of the Jordan that had been the land of the Amʹor·ites in Gilʹe·ad.

[[v7-10-9]]

^<<v7-10-9,9>>^ The Amʹmon·ites would also cross the Jordan to fight against Judah and Benjamin and the house of Eʹphra·im; and Israel was greatly distressed.

[[v7-10-10]]

^<<v7-10-10,10>>^ Then the Israelites called to Jehovah for help, saying: “We have sinned against you, for we abandoned our God and served the Baʹals.”

[[v7-10-11]]

^<<v7-10-11,11>>^ But Jehovah said to the Israelites: “Did I not save you from Egypt and from the Amʹor·ites, the Amʹmon·ites, the Phi·lisʹtines,

[[v7-10-12]]

^<<v7-10-12,12>>^ the Si·doʹni·ans, Amʹa·lek, and Midʹi·an when they oppressed you? When you cried out to me, I saved you out of their hand.

[[v7-10-13]]

^<<v7-10-13,13>>^ But you abandoned me and served other gods. That is why I will not save you again.

[[v7-10-14]]

^<<v7-10-14,14>>^ Go to the gods whom you have chosen and call for help. Let them save you in your time of distress.”

[[v7-10-15]]

^<<v7-10-15,15>>^ But the Israelites said to Jehovah: “We have sinned. Do to us whatever is good in your eyes. Only save us, please, this day.”

[[v7-10-16]]

^<<v7-10-16,16>>^ And they removed the foreign gods from their midst and served Jehovah, so that he could no longer tolerate^&#42;1^ Israel’s suffering.

[NOTE]
====
. Or “and his soul became impatient because of.”
====

[[v7-10-17]]

^<<v7-10-17,17>>^ In time the Amʹmon·ites were called together, and they pitched camp in Gilʹe·ad. So the Israelites gathered together and pitched camp in Mizʹpah.

[[v7-10-18]]

^<<v7-10-18,18>>^ The people and the princes of Gilʹe·ad said to one another: “Who will take the lead in fighting against the Amʹmon·ites? Let him become the chief over all the inhabitants of Gilʹe·ad.”

'''

xref:007-judges/007-judges-009.adoc#v7-9-0[&#60; Capítulo Anterior] | <<v7-10-0,Topo>> | xref:007-judges/007-judges-011.adoc#v7-11-0[Próximo Capítulo &#62;]