include::./index.adoc[]

[[v7-20-0]]
=== Judges, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-20-1]]

^<<v7-20-1,1>>^ Consequently, all the Israelites came out from Dan down to Beʹer-sheʹba and from the land of Gilʹe·ad, and the entire assembly gathered unitedly^&#42;1^ before Jehovah at Mizʹpah.

[NOTE]
====
. Lit., “as one man.”
====

[[v7-20-2]]

^<<v7-20-2,2>>^ So the chiefs of the people and all the tribes of Israel took their places in the congregation of God’s people—400,000 foot soldiers armed with swords.

[[v7-20-3]]

^<<v7-20-3,3>>^ The Benʹja·min·ites heard that the men of Israel had gone up to Mizʹpah.
Then the men of Israel said: “Tell us, how did this terrible thing happen?”

[[v7-20-4]]

^<<v7-20-4,4>>^ At this the Levite man, the husband of the murdered woman, said in answer: “I came to Gibʹe·ah of Benjamin with my concubine to stay overnight.

[[v7-20-5]]

^<<v7-20-5,5>>^ And the inhabitants^&#42;1^ of Gibʹe·ah rose up against me and surrounded the house by night. They meant to kill me, but they raped my concubine instead, and she died.

[NOTE]
====
. Or possibly, “landowners.”
====

[[v7-20-6]]

^<<v7-20-6,6>>^ So I took my concubine’s body and cut it up and sent the pieces into every part of Israel’s inheritance, because they had committed a shameful and disgraceful act in Israel.

[[v7-20-7]]

^<<v7-20-7,7>>^ Now all you people of Israel, give your advice and counsel here.”

[[v7-20-8]]

^<<v7-20-8,8>>^ Then all the people rose up in unison^&#42;1^ and said: “Not one of us will go to his tent or return to his house.

[NOTE]
====
. Lit., “as one man.”
====

[[v7-20-9]]

^<<v7-20-9,9>>^ Now this is what we will do to Gibʹe·ah: We will go up against it by lot.

[[v7-20-10]]

^<<v7-20-10,10>>^ We will take 10 men out of 100 from all the tribes of Israel, and 100 out of 1,000 and 1,000 out of 10,000 to collect provisions for the army, so that they may take action against Gibʹe·ah of Benjamin, in view of the disgraceful act that they committed in Israel.”

[[v7-20-11]]

^<<v7-20-11,11>>^ Thus all the men of Israel were gathered against the city united^&#42;1^ as allies.

[NOTE]
====
. Lit., “as one man.”
====

[[v7-20-12]]

^<<v7-20-12,12>>^ Then the tribes of Israel sent men to all the tribesmen of Benjamin, saying: “What is this terrible thing that has happened among you?

[[v7-20-13]]

^<<v7-20-13,13>>^ Now hand over the worthless men from Gibʹe·ah, so that we may put them to death and clear out what is bad from Israel.” But the Benʹja·min·ites refused to listen to their Israelite brothers.

[[v7-20-14]]

^<<v7-20-14,14>>^ Then the Benʹja·min·ites gathered together out of the cities to Gibʹe·ah to go out to battle against the men of Israel.

[[v7-20-15]]

^<<v7-20-15,15>>^ That day the Benʹja·min·ites mustered from their cities 26,000 men armed with swords, apart from the 700 chosen men of Gibʹe·ah.

[[v7-20-16]]

^<<v7-20-16,16>>^ In this army were 700 chosen men who were left-handed. Every one of these men could sling a stone to within a hairbreadth and would not miss.

[[v7-20-17]]

^<<v7-20-17,17>>^ The men of Israel apart from Benjamin mustered 400,000 men armed with swords, and each one was an experienced warrior.

[[v7-20-18]]

^<<v7-20-18,18>>^ They rose up and went up to Bethʹel to inquire of God. Then the people of Israel said: “Who of us should go up in the lead to the battle against the Benʹja·min·ites?” Jehovah replied: “Judah is to take the lead.”

[[v7-20-19]]

^<<v7-20-19,19>>^ After that the Israelites rose up in the morning and camped against Gibʹe·ah.

[[v7-20-20]]

^<<v7-20-20,20>>^ The men of Israel now went out to battle against Benjamin; they drew up in battle formation against them at Gibʹe·ah.

[[v7-20-21]]

^<<v7-20-21,21>>^ So the Benʹja·min·ites came out from Gibʹe·ah and struck down 22,000 men of Israel on that day.

[[v7-20-22]]

^<<v7-20-22,22>>^ However, the army of the men of Israel showed themselves courageous and again drew up in battle formation in the same place as on the first day.

[[v7-20-23]]

^<<v7-20-23,23>>^ Then the Israelites went up and wept before Jehovah until the evening and inquired of Jehovah: “Should we again go into battle against our brothers, the people of Benjamin?” To this Jehovah said: “Go up against them.”

[[v7-20-24]]

^<<v7-20-24,24>>^ So the Israelites drew near to the Benʹja·min·ites on the second day.

[[v7-20-25]]

^<<v7-20-25,25>>^ In turn Benjamin came out from Gibʹe·ah to meet them on the second day and struck down another 18,000 Israelites, all of them armed with swords.

[[v7-20-26]]

^<<v7-20-26,26>>^ At that all the men of Israel went up to Bethʹel. They wept and sat there before Jehovah, and they fasted on that day until the evening and offered up burnt offerings and communion offerings before Jehovah.

[[v7-20-27]]

^<<v7-20-27,27>>^ After that the men of Israel inquired of Jehovah, for the ark of the covenant of the true God was there in those days.

[[v7-20-28]]

^<<v7-20-28,28>>^ Now Phinʹe·has the son of El·e·aʹzar, the son of Aaron, was ministering^&#42;1^ before it in those days. They asked: “Should we go out yet again to battle against our brothers, the men of Benjamin, or should we stop?” Jehovah replied: “Go up, because tomorrow I will give them into your hand.”

[NOTE]
====
. Lit., “standing.”
====

[[v7-20-29]]

^<<v7-20-29,29>>^ Then Israel set men in ambush all around Gibʹe·ah.

[[v7-20-30]]

^<<v7-20-30,30>>^ The Israelites went up against the Benʹja·min·ites on the third day, and they drew up in formation against Gibʹe·ah the same as at the other times.

[[v7-20-31]]

^<<v7-20-31,31>>^ When the Benʹja·min·ites went out to meet the army, they were drawn away from the city. Then, as at the other times, they started to attack and kill some of the men on the highways, one of which goes up to Bethʹel and the other to Gibʹe·ah, leaving about 30 men of Israel dead in the open field.

[[v7-20-32]]

^<<v7-20-32,32>>^ So the Benʹja·min·ites said: “They are suffering defeat before us the same as before.” But the Israelites said: “We will retreat and draw them away from the city onto the highways.”

[[v7-20-33]]

^<<v7-20-33,33>>^ So all the men of Israel rose up from their places and drew up in formation at Baʹal-taʹmar while the Israelite ambush charged out of their places in the vicinity of Gibʹe·ah.

[[v7-20-34]]

^<<v7-20-34,34>>^ Thus 10,000 chosen men out of all Israel came in front of Gibʹe·ah, and the fighting was heavy. But the Benʹja·min·ites did not know that disaster was near at hand.

[[v7-20-35]]

^<<v7-20-35,35>>^ Jehovah defeated Benjamin before Israel, and on that day the Israelites struck down 25,100 men in Benjamin, all of them armed with swords.

[[v7-20-36]]

^<<v7-20-36,36>>^ However, the Benʹja·min·ites imagined that the men of Israel would be defeated when they retreated from Benjamin, but they retreated because they trusted in the ambush that was set against Gibʹe·ah.

[[v7-20-37]]

^<<v7-20-37,37>>^ The ambush acted quickly and charged toward Gibʹe·ah. Then the ambush spread out and struck down the whole city with the sword.

[[v7-20-38]]

^<<v7-20-38,38>>^ Now the men of Israel had arranged that the men who ambushed the city would make a smoke signal go up from there.

[[v7-20-39]]

^<<v7-20-39,39>>^ When the Israelites turned around in the battle, the men of Benjamin started by attacking and killing about 30 men of Israel, and they said: “They are clearly suffering another defeat before us, just as in the previous battle.”

[[v7-20-40]]

^<<v7-20-40,40>>^ But the signal started to go up from the city as a pillar of smoke. When the men of Benjamin turned to look, they saw the whole city going up in flames to the sky.

[[v7-20-41]]

^<<v7-20-41,41>>^ Then the men of Israel made an about-face, and the men of Benjamin were dismayed, for they saw that disaster had overtaken them.

[[v7-20-42]]

^<<v7-20-42,42>>^ So they retreated from the men of Israel toward the wilderness, but the battle followed them; the men coming out of the cities joined in striking them down.

[[v7-20-43]]

^<<v7-20-43,43>>^ They surrounded the Benʹja·min·ites and pursued them relentlessly. They trampled them down directly in front of Gibʹe·ah toward the east.

[[v7-20-44]]

^<<v7-20-44,44>>^ Finally 18,000 men of Benjamin fell, all mighty warriors.

[[v7-20-45]]

^<<v7-20-45,45>>^ The men of Benjamin turned and fled into the wilderness to the crag of Rimʹmon, and the Israelites killed^&#42;1^ 5,000 of them on the highways, and they kept pursuing them as far as Giʹdom; so they struck down 2,000 more men.

[NOTE]
====
. Lit., “they made a gleaning of.”
====

[[v7-20-46]]

^<<v7-20-46,46>>^ All those of Benjamin who fell on that day amounted to 25,000 men armed with swords, all mighty warriors.

[[v7-20-47]]

^<<v7-20-47,47>>^ But 600 retreated into the wilderness to the crag of Rimʹmon, and they stayed on the crag of Rimʹmon for four months.

[[v7-20-48]]

^<<v7-20-48,48>>^ And the men of Israel turned back against the Benʹja·min·ites and struck those of the city with the sword, from men to livestock, all that remained. Also, they set all the cities in their path on fire.

'''

xref:007-judges/007-judges-019.adoc#v7-19-0[&#60; Capítulo Anterior] | <<v7-20-0,Topo>> | xref:007-judges/007-judges-021.adoc#v7-21-0[Próximo Capítulo &#62;]