include::./index.adoc[]

[[v7-3-0]]
=== Judges, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v7-3-1]]

^<<v7-3-1,1>>^ These are the nations that Jehovah allowed to remain so that they could test all those of Israel who had not experienced any of the wars of Caʹnaan

[[v7-3-2]]

^<<v7-3-2,2>>^ (this was so that succeeding generations of Israelites would experience war, those who had not experienced such things before):

[[v7-3-3]]

^<<v7-3-3,3>>^ the five lords of the Phi·lisʹtines, and all the Caʹnaan·ites, the Si·doʹni·ans, and the Hiʹvites inhabiting Mount Lebʹa·non from Mount Baʹal-herʹmon as far as Leʹbo-haʹmath.^&#42;1^

[NOTE]
====
. Or “the entrance of Hamath.”
====

[[v7-3-4]]

^<<v7-3-4,4>>^ They served as a means of testing Israel to determine whether Israel would obey Jehovah’s commandments that he had given their fathers through Moses.

[[v7-3-5]]

^<<v7-3-5,5>>^ So the Israelites lived among the Caʹnaan·ites, the Hitʹtites, the Amʹor·ites, the Perʹiz·zites, the Hiʹvites, and the Jebʹu·sites.

[[v7-3-6]]

^<<v7-3-6,6>>^ They would take their daughters as wives, and their own daughters they gave to their sons, and they began serving their gods.

[[v7-3-7]]

^<<v7-3-7,7>>^ So the Israelites did what was bad in Jehovah’s eyes, and they forgot Jehovah their God and were serving the Baʹals and the sacred poles.^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v7-3-8]]

^<<v7-3-8,8>>^ At this Jehovah’s anger blazed against Israel, and he sold them into the hand of Cuʹshan-rish·a·thaʹim the king of Mes·o·po·taʹmi·a.^&#42;1^ The Israelites served Cuʹshan-rish·a·thaʹim for eight years.

[NOTE]
====
. Lit., “Aram-naharaim.”
====

[[v7-3-9]]

^<<v7-3-9,9>>^ When the Israelites called to Jehovah for help, Jehovah raised up a savior to rescue the Israelites, Othʹni·el the son of Keʹnaz, the younger brother of Caʹleb.

[[v7-3-10]]

^<<v7-3-10,10>>^ The spirit of Jehovah came upon him, and he became the judge of Israel. When he went out to battle, Jehovah gave Cuʹshan-rish·a·thaʹim the king of Mes·o·po·taʹmi·a^&#42;1^ into his hand so that he prevailed over Cuʹshan-rish·a·thaʹim.

[NOTE]
====
. Lit., “Aram.”
====

[[v7-3-11]]

^<<v7-3-11,11>>^ After that the land had rest^&#42;1^ for 40 years. Then Othʹni·el the son of Keʹnaz died.

[NOTE]
====
. Or “peace.”
====

[[v7-3-12]]

^<<v7-3-12,12>>^ And once again the Israelites began doing what was bad in Jehovah’s eyes. So Jehovah let Egʹlon the king of Moʹab prevail over Israel, because they did what was bad in Jehovah’s eyes.

[[v7-3-13]]

^<<v7-3-13,13>>^ Furthermore, he brought against them the Amʹmon·ites and the A·malʹek·ites. They attacked Israel and captured the city of palm trees.

[[v7-3-14]]

^<<v7-3-14,14>>^ The Israelites served Egʹlon the king of Moʹab for 18 years.

[[v7-3-15]]

^<<v7-3-15,15>>^ Then the Israelites called to Jehovah for help, so Jehovah raised up for them a savior, Eʹhud the son of Geʹra, a Benʹja·min·ite who was left-handed. In time the Israelites sent tribute through him to Egʹlon the king of Moʹab.

[[v7-3-16]]

^<<v7-3-16,16>>^ Meanwhile, Eʹhud made for himself a two-edged sword, a cubit^&#42;1^ long, and he strapped it underneath his garment on his right thigh.

[NOTE]
====
. Perhaps a short cubit of about 38 cm (15 in.). See App. B14.
====

[[v7-3-17]]

^<<v7-3-17,17>>^ He then presented the tribute to Egʹlon the king of Moʹab. Now Egʹlon was a very fat man.

[[v7-3-18]]

^<<v7-3-18,18>>^ When Eʹhud finished presenting the tribute, he sent away the people who had carried the tribute.

[[v7-3-19]]

^<<v7-3-19,19>>^ But after reaching the carved images^&#42;1^ at Gilʹgal, he himself went back and said: “I have a secret message for you, O king.” So the king said: “Silence!” With that all his attendants left him.

[NOTE]
====
. Or possibly, “the quarries.”
====

[[v7-3-20]]

^<<v7-3-20,20>>^ So Eʹhud came to him as he was sitting alone in his cool roof chamber. Then Eʹhud said: “I have a message from God for you.” So he rose up from his throne.^&#42;1^

[NOTE]
====
. Or “seat.”
====

[[v7-3-21]]

^<<v7-3-21,21>>^ Then Eʹhud drew the sword from his right thigh with his left hand and plunged it into his belly.

[[v7-3-22]]

^<<v7-3-22,22>>^ The handle went in after the blade, and the fat closed in over the blade, for he did not draw the sword out of his belly, and the fecal matter came out.

[[v7-3-23]]

^<<v7-3-23,23>>^ Eʹhud went out through the porch,^&#42;1^ closing the doors of the roof chamber behind him and locking them.

[NOTE]
====
. Or possibly, “air vent.”
====

[[v7-3-24]]

^<<v7-3-24,24>>^ After he left, the servants returned and saw that the doors of the roof chamber were locked. So they said: “He must be relieving himself^&#42;1^ in the cool interior room.”

[NOTE]
====
. Lit., “covering his feet.”
====

[[v7-3-25]]

^<<v7-3-25,25>>^ They kept waiting until they were embarrassed, but when they saw that he was still not opening the doors of the roof chamber, they took the key and opened them and saw their lord fallen to the floor^&#42;1^ dead!

[NOTE]
====
. Lit., “earth.”
====

[[v7-3-26]]

^<<v7-3-26,26>>^ Eʹhud escaped while they were lingering, and he passed by the carved images^&#42;1^ and made it safely to Se·iʹrah.

[NOTE]
====
. Or possibly, “the quarries.”
====

[[v7-3-27]]

^<<v7-3-27,27>>^ When he arrived, he sounded the horn in the mountainous region of Eʹphra·im; and the Israelites went down out of the mountainous region, with him at their head.

[[v7-3-28]]

^<<v7-3-28,28>>^ Then he said to them: “Follow me, because Jehovah has given your enemies, the Moʹab·ites, into your hand.” So they followed him and captured the fords of the Jordan against the Moʹab·ites, and they did not allow anyone to cross.

[[v7-3-29]]

^<<v7-3-29,29>>^ At that time they struck down about 10,000 Moʹab·ites, all strong and valiant men; not a single one escaped.

[[v7-3-30]]

^<<v7-3-30,30>>^ So Moʹab was subdued on that day under Israel’s hand; and the land had rest^&#42;1^ for 80 years.

[NOTE]
====
. Or “peace.”
====

[[v7-3-31]]

^<<v7-3-31,31>>^ After him was Shamʹgar the son of Aʹnath, who struck down 600 Phi·lisʹtine men with a cattle goad; he too saved Israel.

'''

xref:007-judges/007-judges-002.adoc#v7-2-0[&#60; Capítulo Anterior] | <<v7-3-0,Topo>> | xref:007-judges/007-judges-004.adoc#v7-4-0[Próximo Capítulo &#62;]