include::./index.adoc[]

[[v40-26-0]]
=== According to Matthew, 26
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-26-1]]

^<<v40-26-1,1>>^ Now when Jesus had finished saying all these things, he said to his disciples:

[[v40-26-2]]

^<<v40-26-2,2>>^ “You know that two days from now the Passover takes place, and the Son of man will be handed over to be executed on the stake.”

[[v40-26-3]]

^<<v40-26-3,3>>^ Then the chief priests and the elders of the people gathered in the courtyard of the high priest, who was named Caʹia·phas,

[[v40-26-4]]

^<<v40-26-4,4>>^ and they conspired together to seize^&#42;1^ Jesus by cunning^&#42;2^ and to kill him.

[NOTE]
====
. Or “arrest.”
. Or “crafty device.”
====

[[v40-26-5]]

^<<v40-26-5,5>>^ However, they were saying: “Not at the festival, so that there may not be an uproar among the people.”

[[v40-26-6]]

^<<v40-26-6,6>>^ While Jesus was in Bethʹa·ny in the house of Simon the leper,

[[v40-26-7]]

^<<v40-26-7,7>>^ a woman with an alabaster jar of costly perfumed oil approached him, and she began pouring it on his head as he was dining.^&#42;1^

[NOTE]
====
. Or “reclining at the table.”
====

[[v40-26-8]]

^<<v40-26-8,8>>^ On seeing this, the disciples became indignant and said: “Why this waste?

[[v40-26-9]]

^<<v40-26-9,9>>^ For this could have been sold for a great deal of money and given to the poor.”

[[v40-26-10]]

^<<v40-26-10,10>>^ Aware of this, Jesus said to them: “Why do you try to make trouble for the woman? She did a fine deed toward me.

[[v40-26-11]]

^<<v40-26-11,11>>^ For you always have the poor with you, but you will not always have me.

[[v40-26-12]]

^<<v40-26-12,12>>^ When she put this perfumed oil on my body, she did it to prepare me for burial.

[[v40-26-13]]

^<<v40-26-13,13>>^ Truly I say to you, wherever this good news is preached in all the world, what this woman did will also be told in memory of her.”

[[v40-26-14]]

^<<v40-26-14,14>>^ Then one of the Twelve, the one called Judas Is·carʹi·ot, went to the chief priests

[[v40-26-15]]

^<<v40-26-15,15>>^ and said: “What will you give me to betray him to you?” They stipulated to him 30 silver pieces.

[[v40-26-16]]

^<<v40-26-16,16>>^ So from then on, he kept looking for a good opportunity to betray him.

[[v40-26-17]]

^<<v40-26-17,17>>^ On the first day of the Unleavened Bread, the disciples came to Jesus, saying: “Where do you want us to prepare for you to eat the Passover?”

[[v40-26-18]]

^<<v40-26-18,18>>^ He said: “Go into the city to So-and-so and say to him, ‘The Teacher says: “My appointed time is near; I will celebrate the Passover with my disciples at your home.”’”

[[v40-26-19]]

^<<v40-26-19,19>>^ So the disciples did as Jesus instructed them and prepared for the Passover.

[[v40-26-20]]

^<<v40-26-20,20>>^ When evening came, he was reclining at the table with the 12 disciples.

[[v40-26-21]]

^<<v40-26-21,21>>^ While they were eating, he said: “Truly I say to you, one of you will betray me.”

[[v40-26-22]]

^<<v40-26-22,22>>^ Being very much grieved at this, each and every one began to say to him: “Lord, it is not I, is it?”

[[v40-26-23]]

^<<v40-26-23,23>>^ In reply he said: “The one who dips his hand with me into the bowl is the one who will betray me.

[[v40-26-24]]

^<<v40-26-24,24>>^ True, the Son of man is going away, just as it is written about him, but woe to that man through whom the Son of man is betrayed! It would have been better for that man if he had not been born.”

[[v40-26-25]]

^<<v40-26-25,25>>^ Judas, who was about to betray him, replied: “It is not I, is it, Rabbi?” Jesus said to him: “You yourself said it.”

[[v40-26-26]]

^<<v40-26-26,26>>^ As they continued eating, Jesus took a loaf, and after saying a blessing, he broke it, and giving it to the disciples, he said: “Take, eat. This means my body.”

[[v40-26-27]]

^<<v40-26-27,27>>^ And taking a cup, he offered thanks and gave it to them, saying: “Drink out of it, all of you,

[[v40-26-28]]

^<<v40-26-28,28>>^ for this means my ‘blood of the covenant,’ which is to be poured out in behalf of many for forgiveness of sins.

[[v40-26-29]]

^<<v40-26-29,29>>^ But I say to you: I will by no means drink again any of this product of the vine until that day when I drink it new with you in the Kingdom of my Father.”

[[v40-26-30]]

^<<v40-26-30,30>>^ Finally, after singing praises,^&#42;1^ they went out to the Mount of Olives.

[NOTE]
====
. Or “hymns; psalms.”
====

[[v40-26-31]]

^<<v40-26-31,31>>^ Then Jesus said to them: “All of you will be stumbled in connection with me on this night, for it is written: ‘I will strike the shepherd, and the sheep of the flock will be scattered about.’

[[v40-26-32]]

^<<v40-26-32,32>>^ But after I have been raised up, I will go ahead of you into Galʹi·lee.”

[[v40-26-33]]

^<<v40-26-33,33>>^ But Peter, in response, said to him: “Although all the others are stumbled in connection with you, I will never be stumbled!”

[[v40-26-34]]

^<<v40-26-34,34>>^ Jesus said to him: “Truly I say to you, on this night, before a rooster crows, you will disown me three times.”

[[v40-26-35]]

^<<v40-26-35,35>>^ Peter said to him: “Even if I should have to die with you, I will by no means disown you.” All the other disciples also said the same thing.

[[v40-26-36]]

^<<v40-26-36,36>>^ Then Jesus came with them to the spot called Geth·semʹa·ne, and he said to the disciples: “Sit down here while I go over there and pray.”

[[v40-26-37]]

^<<v40-26-37,37>>^ And taking along Peter and the two sons of Zebʹe·dee, he began to feel grieved and to be greatly troubled.

[[v40-26-38]]

^<<v40-26-38,38>>^ Then he said to them: “I am^&#42;1^ deeply grieved, even to death. Stay here and keep on the watch with me.”

[NOTE]
====
. Or “My soul is.”
====

[[v40-26-39]]

^<<v40-26-39,39>>^ And going a little way forward, he fell facedown, praying: “My Father, if it is possible, let this cup pass away from me. Yet, not as I will, but as you will.”

[[v40-26-40]]

^<<v40-26-40,40>>^ He returned to the disciples and found them sleeping, and he said to Peter: “Could you not so much as keep on the watch for one hour with me?

[[v40-26-41]]

^<<v40-26-41,41>>^ Keep on the watch and pray continually, so that you may not enter into temptation. The spirit, of course, is eager,^&#42;1^ but the flesh is weak.”

[NOTE]
====
. Or “willing.”
====

[[v40-26-42]]

^<<v40-26-42,42>>^ Again, a second time, he went off and prayed: “My Father, if it is not possible for this to pass away unless I drink it, let your will take place.”

[[v40-26-43]]

^<<v40-26-43,43>>^ And he came again and found them sleeping, for their eyes were heavy.

[[v40-26-44]]

^<<v40-26-44,44>>^ So leaving them, he again went off and prayed for a third time, saying once more the same thing.

[[v40-26-45]]

^<<v40-26-45,45>>^ Then he returned to the disciples and said to them: “At such a time as this, you are sleeping and resting! Look! The hour has drawn near for the Son of man to be betrayed into the hands of sinners.

[[v40-26-46]]

^<<v40-26-46,46>>^ Get up, let us go. Look! My betrayer has drawn near.”

[[v40-26-47]]

^<<v40-26-47,47>>^ While he was still speaking, look! Judas, one of the Twelve, came and with him a large crowd with swords and clubs, sent from the chief priests and the elders of the people.

[[v40-26-48]]

^<<v40-26-48,48>>^ Now his betrayer had given them a sign, saying: “Whoever it is I kiss, he is the one; take him into custody.”

[[v40-26-49]]

^<<v40-26-49,49>>^ And going straight up to Jesus, he said: “Greetings, Rabbi!” and gave him a tender kiss.

[[v40-26-50]]

^<<v40-26-50,50>>^ But Jesus said to him: “Fellow, for what purpose are you present?” Then they came forward and seized Jesus and took him into custody.

[[v40-26-51]]

^<<v40-26-51,51>>^ But look! one of those with Jesus reached out his hand and drew his sword and struck the slave of the high priest, taking off his ear.

[[v40-26-52]]

^<<v40-26-52,52>>^ Then Jesus said to him: “Return your sword to its place, for all those who take up the sword will perish by the sword.

[[v40-26-53]]

^<<v40-26-53,53>>^ Or do you think that I cannot appeal to my Father to supply me at this moment more than 12 legions of angels?

[[v40-26-54]]

^<<v40-26-54,54>>^ In that case, how would the Scriptures be fulfilled that say it must take place this way?”

[[v40-26-55]]

^<<v40-26-55,55>>^ In that hour Jesus said to the crowds: “Did you come out to arrest me with swords and clubs as against a robber? Day after day I used to sit in the temple teaching, and yet you did not take me into custody.

[[v40-26-56]]

^<<v40-26-56,56>>^ But all of this has taken place for the writings^&#42;1^ of the prophets to be fulfilled.” Then all the disciples abandoned him and fled.

[NOTE]
====
. Or “scriptures.”
====

[[v40-26-57]]

^<<v40-26-57,57>>^ Those who took Jesus into custody led him away to Caʹia·phas the high priest, where the scribes and the elders were gathered together.

[[v40-26-58]]

^<<v40-26-58,58>>^ But Peter kept following him from a good distance, as far as the courtyard of the high priest, and after going inside, he sat with the house attendants to see the outcome.

[[v40-26-59]]

^<<v40-26-59,59>>^ Now the chief priests and the entire Sanʹhe·drin were looking for false testimony against Jesus in order to put him to death.

[[v40-26-60]]

^<<v40-26-60,60>>^ But they found none, although many false witnesses came forward. Later two came forward

[[v40-26-61]]

^<<v40-26-61,61>>^ and said: “This man said, ‘I am able to throw down the temple of God and build it up in three days.’”

[[v40-26-62]]

^<<v40-26-62,62>>^ With that the high priest stood up and said to him: “Do you say nothing in reply? What is it these men are testifying against you?”

[[v40-26-63]]

^<<v40-26-63,63>>^ But Jesus kept silent. So the high priest said to him: “I put you under oath by the living God to tell us whether you are the Christ, the Son of God!”

[[v40-26-64]]

^<<v40-26-64,64>>^ Jesus said to him: “You yourself said it. But I say to you: From now on you will see the Son of man sitting at the right hand of power and coming on the clouds of heaven.”

[[v40-26-65]]

^<<v40-26-65,65>>^ Then the high priest ripped his outer garments, saying: “He has blasphemed! What further need do we have of witnesses? See! Now you have heard the blasphemy.

[[v40-26-66]]

^<<v40-26-66,66>>^ What is your opinion?” They answered: “He deserves to die.”

[[v40-26-67]]

^<<v40-26-67,67>>^ Then they spat in his face and hit him with their fists. Others slapped him on the face,

[[v40-26-68]]

^<<v40-26-68,68>>^ saying: “Prophesy to us, you Christ. Who struck you?”

[[v40-26-69]]

^<<v40-26-69,69>>^ Now Peter was sitting outside in the courtyard, and a servant girl came up to him and said: “You too were with Jesus the Gal·i·leʹan!”

[[v40-26-70]]

^<<v40-26-70,70>>^ But he denied it before them all, saying: “I do not know what you are talking about.”

[[v40-26-71]]

^<<v40-26-71,71>>^ When he went out to the gatehouse, another girl noticed him and said to those there: “This man was with Jesus the Naz·a·reneʹ.”

[[v40-26-72]]

^<<v40-26-72,72>>^ Again he denied it, with an oath: “I do not know the man!”

[[v40-26-73]]

^<<v40-26-73,73>>^ After a little while, those standing around came up and said to Peter: “Certainly you are also one of them, for in fact, your dialect^&#42;1^ gives you away.”

[NOTE]
====
. Or “accent.”
====

[[v40-26-74]]

^<<v40-26-74,74>>^ Then he started to curse and swear: “I do not know the man!” And immediately a rooster crowed.

[[v40-26-75]]

^<<v40-26-75,75>>^ And Peter called to mind what Jesus had said, namely: “Before a rooster crows, you will disown me three times.” And he went outside and wept bitterly.

'''

xref:040-matthew/040-matthew-025.adoc#v40-25-0[&#60; Capítulo Anterior] | <<v40-26-0,Topo>> | xref:040-matthew/040-matthew-027.adoc#v40-27-0[Próximo Capítulo &#62;]