include::./index.adoc[]

[[v40-4-0]]
=== According to Matthew, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-4-1]]

^<<v40-4-1,1>>^ Then Jesus was led by the spirit up into the wilderness to be tempted by the Devil.

[[v40-4-2]]

^<<v40-4-2,2>>^ After he had fasted for 40 days and 40 nights, he felt hungry.

[[v40-4-3]]

^<<v40-4-3,3>>^ And the Tempter approached and said to him: “If you are a son of God, tell these stones to become loaves of bread.”

[[v40-4-4]]

^<<v40-4-4,4>>^ But he answered: “It is written: ‘Man must live, not on bread alone, but on every word that comes from Jehovah’s^&#42;1^ mouth.’”

[NOTE]
====
. See App. A5.
====

[[v40-4-5]]

^<<v40-4-5,5>>^ Then the Devil took him along into the holy city, and he stationed him on the battlement^&#42;1^ of the temple

[NOTE]
====
. Or “parapet; highest point.”
====

[[v40-4-6]]

^<<v40-4-6,6>>^ and said to him: “If you are a son of God, throw yourself down, for it is written: ‘He will give his angels a command concerning you,’ and, ‘They will carry you on their hands, so that you may not strike your foot against a stone.’”

[[v40-4-7]]

^<<v40-4-7,7>>^ Jesus said to him: “Again it is written: ‘You must not put Jehovah^&#42;1^ your God to the test.’”

[NOTE]
====
. See App. A5.
====

[[v40-4-8]]

^<<v40-4-8,8>>^ Again the Devil took him along to an unusually high mountain and showed him all the kingdoms of the world and their glory.

[[v40-4-9]]

^<<v40-4-9,9>>^ And he said to him: “All these things I will give you if you fall down and do an act of worship to me.”

[[v40-4-10]]

^<<v40-4-10,10>>^ Then Jesus said to him: “Go away, Satan! For it is written: ‘It is Jehovah^&#42;1^ your God you must worship, and it is to him alone you must render sacred service.’”

[NOTE]
====
. See App. A5.
====

[[v40-4-11]]

^<<v40-4-11,11>>^ Then the Devil left him, and look! angels came and began to minister to him.

[[v40-4-12]]

^<<v40-4-12,12>>^ Now when he heard that John had been arrested, he withdrew into Galʹi·lee.

[[v40-4-13]]

^<<v40-4-13,13>>^ Further, after leaving Nazʹa·reth, he came and took up residence in Ca·perʹna·um beside the sea in the districts of Zebʹu·lun and Naphʹta·li,

[[v40-4-14]]

^<<v40-4-14,14>>^ so as to fulfill what was spoken through Isaiah the prophet, who said:

[[v40-4-15]]

^<<v40-4-15,15>>^ “O land of Zebʹu·lun and land of Naphʹta·li, along the road of the sea, on the other side of the Jordan, Galʹi·lee of the nations!

[[v40-4-16]]

^<<v40-4-16,16>>^ The people sitting in darkness saw a great light, and as for those sitting in a region of deathly shadow, light rose on them.”

[[v40-4-17]]

^<<v40-4-17,17>>^ From that time on, Jesus began preaching and saying: “Repent, for the Kingdom of the heavens has drawn near.”

[[v40-4-18]]

^<<v40-4-18,18>>^ Walking alongside the Sea of Galʹi·lee, he saw two brothers, Simon, who is called Peter, and Andrew his brother, casting a net into the sea, for they were fishermen.

[[v40-4-19]]

^<<v40-4-19,19>>^ And he said to them: “Come after me, and I will make you fishers of men.”

[[v40-4-20]]

^<<v40-4-20,20>>^ At once they abandoned their nets and followed him.

[[v40-4-21]]

^<<v40-4-21,21>>^ Going on from there, he saw two others who were brothers, James the son of Zebʹe·dee and his brother John. They were in the boat with Zebʹe·dee their father, mending their nets, and he called them.

[[v40-4-22]]

^<<v40-4-22,22>>^ At once they left the boat and their father and followed him.

[[v40-4-23]]

^<<v40-4-23,23>>^ Then he went throughout the whole of Galʹi·lee, teaching in their synagogues and preaching the good news of the Kingdom and curing every sort of disease and every sort of infirmity among the people.

[[v40-4-24]]

^<<v40-4-24,24>>^ And the report about him spread throughout all Syria, and they brought him all those who were suffering with various diseases and torments, those who were demon-possessed and epileptic and paralyzed, and he cured them.

[[v40-4-25]]

^<<v40-4-25,25>>^ Consequently, large crowds followed him from Galʹi·lee and De·capʹo·lis^&#42;1^ and Jerusalem and Ju·deʹa and from the other side of the Jordan.

[NOTE]
====
. Or “the Ten City Region.”
====

'''

xref:040-matthew/040-matthew-003.adoc#v40-3-0[&#60; Capítulo Anterior] | <<v40-4-0,Topo>> | xref:040-matthew/040-matthew-005.adoc#v40-5-0[Próximo Capítulo &#62;]