include::./index.adoc[]

[[v40-9-0]]
=== According to Matthew, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-9-1]]

^<<v40-9-1,1>>^ So boarding the boat, he traveled across and went into his own city.

[[v40-9-2]]

^<<v40-9-2,2>>^ And look! they were bringing him a paralyzed man lying on a stretcher. On seeing their faith, Jesus said to the paralytic: “Take courage, child! Your sins are forgiven.”

[[v40-9-3]]

^<<v40-9-3,3>>^ Now certain scribes said to themselves: “This fellow is blaspheming.”

[[v40-9-4]]

^<<v40-9-4,4>>^ Jesus, knowing their thoughts, said: “Why are you thinking wicked things in your hearts?

[[v40-9-5]]

^<<v40-9-5,5>>^ For instance, which is easier, to say, ‘Your sins are forgiven,’ or to say, ‘Get up and walk’?

[[v40-9-6]]

^<<v40-9-6,6>>^ However, in order for you to know that the Son of man has authority on earth to forgive sins—” then he said to the paralytic: “Get up, pick up your stretcher, and go to your home.”

[[v40-9-7]]

^<<v40-9-7,7>>^ And he got up and went to his home.

[[v40-9-8]]

^<<v40-9-8,8>>^ When the crowds saw this, they were struck with fear, and they glorified God, who gave such authority to men.

[[v40-9-9]]

^<<v40-9-9,9>>^ Next, while moving on from there, Jesus caught sight of a man named Matthew sitting at the tax office, and he said to him: “Be my follower.” At that he rose up and followed him.

[[v40-9-10]]

^<<v40-9-10,10>>^ Later as he was dining^&#42;1^ in the house, look! many tax collectors and sinners came and began dining^&#42;2^ with Jesus and his disciples.

[NOTE]
====
. Or “reclining at the table.”
. Or “reclining at the table.”
====

[[v40-9-11]]

^<<v40-9-11,11>>^ But on seeing this, the Pharisees said to his disciples: “Why does your teacher eat with tax collectors and sinners?”

[[v40-9-12]]

^<<v40-9-12,12>>^ Hearing them, he said: “Healthy people do not need a physician, but those who are ill do.

[[v40-9-13]]

^<<v40-9-13,13>>^ Go, then, and learn what this means: ‘I want mercy, and not sacrifice.’ For I came to call, not righteous people, but sinners.”

[[v40-9-14]]

^<<v40-9-14,14>>^ Then John’s disciples came to him and asked: “Why do we and the Pharisees practice fasting but your disciples do not fast?”

[[v40-9-15]]

^<<v40-9-15,15>>^ At this Jesus said to them: “The friends of the bridegroom have no reason to mourn as long as the bridegroom is with them, do they? But days will come when the bridegroom will be taken away from them, and then they will fast.

[[v40-9-16]]

^<<v40-9-16,16>>^ Nobody sews a patch of unshrunk cloth on an old outer garment, for the new piece pulls away from the garment and the tear becomes worse.

[[v40-9-17]]

^<<v40-9-17,17>>^ Nor do people put new wine into old wineskins. If they do, then the wineskins burst and the wine spills out and the wineskins are ruined. But people put new wine into new wineskins, and both are preserved.”

[[v40-9-18]]

^<<v40-9-18,18>>^ While he was telling them these things, look! a certain ruler who had approached did obeisance^&#42;1^ to him, saying: “By now my daughter must be dead, but come and lay your hand on her, and she will come to life.”

[NOTE]
====
. Or “bowed down.”
====

[[v40-9-19]]

^<<v40-9-19,19>>^ Then Jesus got up and, with his disciples, followed him.

[[v40-9-20]]

^<<v40-9-20,20>>^ And look! a woman suffering for 12 years from a flow of blood approached from behind and touched the fringe of his outer garment,

[[v40-9-21]]

^<<v40-9-21,21>>^ for she kept saying to herself: “If I only touch his outer garment, I will get well.”

[[v40-9-22]]

^<<v40-9-22,22>>^ Jesus turned around and, noticing her, said: “Take courage, daughter! Your faith has made you well.” And from that hour the woman was made well.

[[v40-9-23]]

^<<v40-9-23,23>>^ When, now, he came into the ruler’s house and caught sight of the flute players and the crowd making a commotion,

[[v40-9-24]]

^<<v40-9-24,24>>^ Jesus said: “Leave the place, for the little girl did not die but is sleeping.” At this they began to laugh at him scornfully.

[[v40-9-25]]

^<<v40-9-25,25>>^ As soon as the crowd had been sent outside, he went in and took hold of her hand, and the little girl got up.

[[v40-9-26]]

^<<v40-9-26,26>>^ Of course, the talk about this spread into all that region.

[[v40-9-27]]

^<<v40-9-27,27>>^ As Jesus moved on from there, two blind men followed him, shouting out: “Have mercy on us, Son of David.”

[[v40-9-28]]

^<<v40-9-28,28>>^ After he had gone into the house, the blind men came to him, and Jesus asked them: “Do you have faith that I can do this?” They answered him: “Yes, Lord.”

[[v40-9-29]]

^<<v40-9-29,29>>^ Then he touched their eyes, saying: “According to your faith let it happen to you.”

[[v40-9-30]]

^<<v40-9-30,30>>^ And their eyes received sight. Moreover, Jesus sternly warned them, saying: “See that nobody gets to know it.”

[[v40-9-31]]

^<<v40-9-31,31>>^ But after going outside, they made it public about him in all that region.

[[v40-9-32]]

^<<v40-9-32,32>>^ When they were leaving, look! people brought him a speechless man possessed of a demon;

[[v40-9-33]]

^<<v40-9-33,33>>^ and after the demon had been expelled, the speechless man spoke. Well, the crowds were amazed and said: “Never has anything like this been seen in Israel.”

[[v40-9-34]]

^<<v40-9-34,34>>^ But the Pharisees were saying: “It is by the ruler of the demons that he expels the demons.”

[[v40-9-35]]

^<<v40-9-35,35>>^ And Jesus set out on a tour of all the cities and villages, teaching in their synagogues and preaching the good news of the Kingdom and curing every sort of disease and every sort of infirmity.

[[v40-9-36]]

^<<v40-9-36,36>>^ On seeing the crowds, he felt pity for them, because they were skinned and thrown about like sheep without a shepherd.

[[v40-9-37]]

^<<v40-9-37,37>>^ Then he said to his disciples: “Yes, the harvest is great, but the workers are few.

[[v40-9-38]]

^<<v40-9-38,38>>^ Therefore, beg the Master of the harvest to send out workers into his harvest.”

'''

xref:040-matthew/040-matthew-008.adoc#v40-8-0[&#60; Capítulo Anterior] | <<v40-9-0,Topo>> | xref:040-matthew/040-matthew-010.adoc#v40-10-0[Próximo Capítulo &#62;]