include::./index.adoc[]

[[v40-15-0]]
=== According to Matthew, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-15-1]]

^<<v40-15-1,1>>^ Then there came to Jesus from Jerusalem Pharisees and scribes, saying:

[[v40-15-2]]

^<<v40-15-2,2>>^ “Why do your disciples overstep the tradition of the men of former times? For example, they do not wash^&#42;1^ their hands when about to eat a meal.”

[NOTE]
====
. That is, ceremonially cleanse.
====

[[v40-15-3]]

^<<v40-15-3,3>>^ In reply he said to them: “Why do you overstep the commandment of God because of your tradition?

[[v40-15-4]]

^<<v40-15-4,4>>^ For example, God said, ‘Honor your father and your mother,’ and, ‘Let the one who speaks abusively of^&#42;1^ his father or mother be put to death.’

[NOTE]
====
. Or “reviles.”
====

[[v40-15-5]]

^<<v40-15-5,5>>^ But you say, ‘Whoever says to his father or mother: “Whatever I have that could benefit you is a gift dedicated to God,”

[[v40-15-6]]

^<<v40-15-6,6>>^ he need not honor his father at all.’ So you have made the word of God invalid because of your tradition.

[[v40-15-7]]

^<<v40-15-7,7>>^ You hypocrites, Isaiah aptly prophesied about you when he said:

[[v40-15-8]]

^<<v40-15-8,8>>^ ‘This people honor me with their lips, but their hearts are far removed from me.

[[v40-15-9]]

^<<v40-15-9,9>>^ It is in vain that they keep worshipping me, for they teach commands of men as doctrines.’”

[[v40-15-10]]

^<<v40-15-10,10>>^ With that he called the crowd near and said to them: “Listen and get the sense of it:

[[v40-15-11]]

^<<v40-15-11,11>>^ It is not what enters into a man’s mouth that defiles him, but it is what comes out of his mouth that defiles him.”

[[v40-15-12]]

^<<v40-15-12,12>>^ Then the disciples came and said to him: “Do you know that the Pharisees were stumbled at hearing what you said?”

[[v40-15-13]]

^<<v40-15-13,13>>^ In reply he said: “Every plant that my heavenly Father did not plant will be uprooted.

[[v40-15-14]]

^<<v40-15-14,14>>^ Let them be. Blind guides is what they are. If, then, a blind man guides a blind man, both will fall into a pit.”

[[v40-15-15]]

^<<v40-15-15,15>>^ Peter responded: “Make the illustration plain to us.”

[[v40-15-16]]

^<<v40-15-16,16>>^ At this he said: “Are you also still without understanding?

[[v40-15-17]]

^<<v40-15-17,17>>^ Are you not aware that whatever enters into the mouth passes through the stomach and is discharged into the sewer?

[[v40-15-18]]

^<<v40-15-18,18>>^ However, whatever comes out of the mouth comes from the heart, and those things defile a man.

[[v40-15-19]]

^<<v40-15-19,19>>^ For example, out of the heart come wicked reasonings: murders, adulteries, sexual immorality,^&#42;1^ thefts, false testimonies, blasphemies.

[NOTE]
====
. Plural of the Greek por·neiʹa. See Glossary.
====

[[v40-15-20]]

^<<v40-15-20,20>>^ These are the things that defile a man; but to take a meal with unwashed^&#42;1^ hands does not defile a man.”

[NOTE]
====
. That is, not ceremonially cleansed.
====

[[v40-15-21]]

^<<v40-15-21,21>>^ Leaving there, Jesus now went into the region of Tyre and Siʹdon.

[[v40-15-22]]

^<<v40-15-22,22>>^ And look! a Phoe·niʹcian woman from that region came and cried out: “Have mercy on me, Lord, Son of David. My daughter is cruelly demon possessed.”

[[v40-15-23]]

^<<v40-15-23,23>>^ But he did not say a word in answer to her. So his disciples came and began to urge him: “Send her away, because she keeps crying out after us.”

[[v40-15-24]]

^<<v40-15-24,24>>^ He answered: “I was not sent to anyone except to the lost sheep of the house of Israel.”

[[v40-15-25]]

^<<v40-15-25,25>>^ But the woman came and did obeisance^&#42;1^ to him, saying: “Lord, help me!”

[NOTE]
====
. Or “bowed down.”
====

[[v40-15-26]]

^<<v40-15-26,26>>^ In answer he said: “It is not right to take the bread of the children and throw it to the little dogs.”

[[v40-15-27]]

^<<v40-15-27,27>>^ She said: “Yes, Lord, but really the little dogs do eat of the crumbs falling from the table of their masters.”

[[v40-15-28]]

^<<v40-15-28,28>>^ Then Jesus replied to her: “O woman, great is your faith; let it happen to you as you wish.” And her daughter was healed from that hour on.

[[v40-15-29]]

^<<v40-15-29,29>>^ Departing from there, Jesus next came near the Sea of Galʹi·lee, and after going up on the mountain, he was sitting there.

[[v40-15-30]]

^<<v40-15-30,30>>^ Then large crowds approached him, bringing along people who were lame, maimed, blind, speechless, and many others, and they laid them at his feet, and he cured them.

[[v40-15-31]]

^<<v40-15-31,31>>^ So the crowd felt amazement as they saw the speechless speaking and the maimed being made sound and the lame walking and the blind seeing, and they glorified the God of Israel.

[[v40-15-32]]

^<<v40-15-32,32>>^ But Jesus called his disciples to him and said: “I feel pity for the crowd, because they have already stayed with me for three days and they have had nothing to eat. I do not want to send them away hungry,^&#42;1^ for they may give out on the road.”

[NOTE]
====
. Or “fasting.”
====

[[v40-15-33]]

^<<v40-15-33,33>>^ However, the disciples said to him: “Where in this isolated place are we going to get enough bread to satisfy a crowd of this size?”

[[v40-15-34]]

^<<v40-15-34,34>>^ At this Jesus said to them: “How many loaves do you have?” They said: “Seven, and a few small fish.”

[[v40-15-35]]

^<<v40-15-35,35>>^ So after instructing the crowd to recline on the ground,

[[v40-15-36]]

^<<v40-15-36,36>>^ he took the seven loaves and the fish, and after offering thanks, he broke them and began giving them to the disciples, and the disciples gave them to the crowds.

[[v40-15-37]]

^<<v40-15-37,37>>^ And all ate and were satisfied, and they took up seven large baskets^&#42;1^ full of leftover fragments.

[NOTE]
====
. Or “provision baskets.”
====

[[v40-15-38]]

^<<v40-15-38,38>>^ Now those eating were 4,000 men, as well as women and young children.

[[v40-15-39]]

^<<v40-15-39,39>>^ Finally, after sending the crowds away, he got into the boat and came into the region of Magʹa·dan.

'''

xref:040-matthew/040-matthew-014.adoc#v40-14-0[&#60; Capítulo Anterior] | <<v40-15-0,Topo>> | xref:040-matthew/040-matthew-016.adoc#v40-16-0[Próximo Capítulo &#62;]