include::./index.adoc[]

[[v40-14-0]]
=== According to Matthew, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-14-1]]

^<<v40-14-1,1>>^ At that time Herod, the district ruler,^&#42;1^ heard the report about Jesus

[NOTE]
====
. Lit., “the tetrarch.”
====

[[v40-14-2]]

^<<v40-14-2,2>>^ and said to his servants: “This is John the Baptist. He was raised up from the dead, and this is why these powerful works are operating in him.”

[[v40-14-3]]

^<<v40-14-3,3>>^ Herod^&#42;1^ had arrested John and had bound him and imprisoned him because of He·roʹdi·as, the wife of Philip his brother.

[NOTE]
====
. That is, Herod Antipas. See Glossary.
====

[[v40-14-4]]

^<<v40-14-4,4>>^ For John had been saying to him: “It is not lawful for you to have her.”

[[v40-14-5]]

^<<v40-14-5,5>>^ However, although he wanted to kill him, he feared the crowd, because they took him for a prophet.

[[v40-14-6]]

^<<v40-14-6,6>>^ But when Herod’s birthday was being celebrated, the daughter of He·roʹdi·as danced for the occasion and pleased Herod so much

[[v40-14-7]]

^<<v40-14-7,7>>^ that he promised with an oath to give her whatever she asked.

[[v40-14-8]]

^<<v40-14-8,8>>^ Then she, at her mother’s prompting, said: “Give me here on a platter the head of John the Baptist.”

[[v40-14-9]]

^<<v40-14-9,9>>^ Grieved though he was, the king, out of regard for his oaths and for those dining^&#42;1^ with him, commanded it to be given.

[NOTE]
====
. Or “reclining at the table.”
====

[[v40-14-10]]

^<<v40-14-10,10>>^ So he sent and had John beheaded in the prison.

[[v40-14-11]]

^<<v40-14-11,11>>^ His head was brought on a platter and given to the girl, and she brought it to her mother.

[[v40-14-12]]

^<<v40-14-12,12>>^ Later his disciples came and removed his corpse and buried him; then they came and reported to Jesus.

[[v40-14-13]]

^<<v40-14-13,13>>^ At hearing this, Jesus departed from there by boat into an isolated place to be alone. But the crowds, getting to hear of it, followed him on foot from the cities.

[[v40-14-14]]

^<<v40-14-14,14>>^ When he came ashore, he saw a large crowd, and he felt pity for them, and he cured their sick ones.

[[v40-14-15]]

^<<v40-14-15,15>>^ But when evening fell, his disciples came to him and said: “The place is isolated and the hour is already late; send the crowds away, so that they may go into the villages and buy themselves food.”

[[v40-14-16]]

^<<v40-14-16,16>>^ However, Jesus said to them: “They do not have to leave; you give them something to eat.”

[[v40-14-17]]

^<<v40-14-17,17>>^ They said to him: “We have nothing here except five loaves and two fish.”

[[v40-14-18]]

^<<v40-14-18,18>>^ He said: “Bring them here to me.”

[[v40-14-19]]

^<<v40-14-19,19>>^ And he instructed the crowds to recline on the grass. Then he took the five loaves and two fish, and looking up to heaven, he said a blessing, and after breaking the loaves, he gave them to the disciples, and the disciples gave them to the crowds.

[[v40-14-20]]

^<<v40-14-20,20>>^ So they all ate and were satisfied, and they took up the leftover fragments, 12 baskets full.

[[v40-14-21]]

^<<v40-14-21,21>>^ Now those eating were about 5,000 men, as well as women and young children.

[[v40-14-22]]

^<<v40-14-22,22>>^ Then, without delay, he made his disciples board the boat and go ahead of him to the opposite shore, while he sent the crowds away.

[[v40-14-23]]

^<<v40-14-23,23>>^ After sending the crowds away, he went up on the mountain by himself to pray. When evening came, he was there alone.

[[v40-14-24]]

^<<v40-14-24,24>>^ By now the boat was many hundreds of yards^&#42;1^ away from land, struggling against the waves because the wind was against them.

[NOTE]
====
. Lit., “many stadia.” A stadium equaled 185 m (606.95 ft).
====

[[v40-14-25]]

^<<v40-14-25,25>>^ But in the fourth watch of the night^&#42;1^ he came to them, walking on the sea.

[NOTE]
====
. That is, about 3:00 a.m. until sunrise at about 6:00 a.m.
====

[[v40-14-26]]

^<<v40-14-26,26>>^ When they caught sight of him walking on the sea, the disciples were troubled, saying: “It is an apparition!” And they cried out in their fear.

[[v40-14-27]]

^<<v40-14-27,27>>^ But at once Jesus spoke to them, saying: “Take courage! It is I; do not be afraid.”

[[v40-14-28]]

^<<v40-14-28,28>>^ Peter answered him: “Lord, if it is you, command me to come to you over the waters.”

[[v40-14-29]]

^<<v40-14-29,29>>^ He said: “Come!” So Peter got out of the boat and walked over the waters and went toward Jesus.

[[v40-14-30]]

^<<v40-14-30,30>>^ But looking at the windstorm, he became afraid. And when he started to sink, he cried out: “Lord, save me!”

[[v40-14-31]]

^<<v40-14-31,31>>^ Immediately stretching out his hand, Jesus caught hold of him and said to him: “You with little faith, why did you give way to doubt?”

[[v40-14-32]]

^<<v40-14-32,32>>^ After they got up into the boat, the windstorm abated.

[[v40-14-33]]

^<<v40-14-33,33>>^ Then those in the boat did obeisance^&#42;1^ to him, saying: “You really are God’s Son.”

[NOTE]
====
. Or “bowed down.”
====

[[v40-14-34]]

^<<v40-14-34,34>>^ And they crossed over and came to land in Gen·nesʹa·ret.

[[v40-14-35]]

^<<v40-14-35,35>>^ On recognizing him, the men of that place sent word into all that surrounding country, and people brought him all those who were ill.

[[v40-14-36]]

^<<v40-14-36,36>>^ And they pleaded with him that they might just touch the fringe of his outer garment, and all those who touched it were made completely well.

'''

xref:040-matthew/040-matthew-013.adoc#v40-13-0[&#60; Capítulo Anterior] | <<v40-14-0,Topo>> | xref:040-matthew/040-matthew-015.adoc#v40-15-0[Próximo Capítulo &#62;]