include::./index.adoc[]

[[v40-6-0]]
=== According to Matthew, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-6-1]]

^<<v40-6-1,1>>^ “Take care not to practice your righteousness in front of men to be noticed by them; otherwise you will have no reward with your Father who is in the heavens.

[[v40-6-2]]

^<<v40-6-2,2>>^ So when you make gifts of mercy,^&#42;1^ do not blow a trumpet ahead of you, as the hypocrites do in the synagogues and in the streets, so that they may be glorified by men. Truly I say to you, they have their reward in full.

[NOTE]
====
. Or “gifts to the poor.” See Glossary.
====

[[v40-6-3]]

^<<v40-6-3,3>>^ But you, when making gifts of mercy, do not let your left hand know what your right hand is doing,

[[v40-6-4]]

^<<v40-6-4,4>>^ so that your gifts of mercy may be in secret. Then your Father who looks on in secret will repay you.

[[v40-6-5]]

^<<v40-6-5,5>>^ “Also, when you pray, do not act like the hypocrites, for they like to pray standing in the synagogues and on the corners of the main streets to be seen by men. Truly I say to you, they have their reward in full.

[[v40-6-6]]

^<<v40-6-6,6>>^ But when you pray, go into your private room and, after shutting your door, pray to your Father who is in secret. Then your Father who looks on in secret will repay you.

[[v40-6-7]]

^<<v40-6-7,7>>^ When praying, do not say the same things over and over again as the people of the nations do, for they imagine they will get a hearing for their use of many words.

[[v40-6-8]]

^<<v40-6-8,8>>^ So do not be like them, for your Father knows what you need even before you ask him.

[[v40-6-9]]

^<<v40-6-9,9>>^ “You must pray, then, this way:
“‘Our Father in the heavens, let your name be sanctified.^&#42;1^

[NOTE]
====
. Or “be held sacred; be treated as holy.”
====

[[v40-6-10]]

^<<v40-6-10,10>>^ Let your Kingdom come. Let your will take place, as in heaven, also on earth.

[[v40-6-11]]

^<<v40-6-11,11>>^ Give us today our bread for this day;

[[v40-6-12]]

^<<v40-6-12,12>>^ and forgive us our debts, as we also have forgiven our debtors.

[[v40-6-13]]

^<<v40-6-13,13>>^ And do not bring us into temptation, but deliver^&#42;1^ us from the wicked one.’

[NOTE]
====
. Or “rescue.”
====

[[v40-6-14]]

^<<v40-6-14,14>>^ “For if you forgive men their trespasses, your heavenly Father will also forgive you;

[[v40-6-15]]

^<<v40-6-15,15>>^ whereas if you do not forgive men their trespasses, neither will your Father forgive your trespasses.

[[v40-6-16]]

^<<v40-6-16,16>>^ “When you fast, stop becoming sad-faced like the hypocrites, for they disfigure their faces^&#42;1^ so they may appear to men to be fasting. Truly I say to you, they have their reward in full.

[NOTE]
====
. Or “they neglect their appearance.”
====

[[v40-6-17]]

^<<v40-6-17,17>>^ But you, when fasting, put oil on your head and wash your face,

[[v40-6-18]]

^<<v40-6-18,18>>^ so that you may not appear to be fasting to men but only to your Father who is in secret. Then your Father who looks on in secret will repay you.

[[v40-6-19]]

^<<v40-6-19,19>>^ “Stop storing up for yourselves treasures on the earth, where moth and rust consume and where thieves break in and steal.

[[v40-6-20]]

^<<v40-6-20,20>>^ Rather, store up for yourselves treasures in heaven, where neither moth nor rust consumes, and where thieves do not break in and steal.

[[v40-6-21]]

^<<v40-6-21,21>>^ For where your treasure is, there your heart will be also.

[[v40-6-22]]

^<<v40-6-22,22>>^ “The lamp of the body is the eye. If, then, your eye is focused,^&#42;1^ your whole body will be bright.^&#42;2^

[NOTE]
====
. Or “clear.” Lit., “simple.”
. Or “full of light.”
====

[[v40-6-23]]

^<<v40-6-23,23>>^ But if your eye is envious,^&#42;1^ your whole body will be dark. If the light that is in you is really darkness, how great that darkness is!

[NOTE]
====
. Lit., “bad; wicked.”
====

[[v40-6-24]]

^<<v40-6-24,24>>^ “No one can slave for two masters; for either he will hate the one and love the other, or he will stick to the one and despise the other. You cannot slave for God and for Riches.

[[v40-6-25]]

^<<v40-6-25,25>>^ “On this account I say to you: Stop being anxious about your lives^&#42;1^ as to what you will eat or what you will drink, or about your bodies as to what you will wear. Does not life^&#42;2^ mean more than food and the body than clothing?

[NOTE]
====
. Or “souls.”
. Or “the soul.”
====

[[v40-6-26]]

^<<v40-6-26,26>>^ Observe intently the birds of heaven; they do not sow seed or reap or gather into storehouses, yet your heavenly Father feeds them. Are you not worth more than they are?

[[v40-6-27]]

^<<v40-6-27,27>>^ Who of you by being anxious can add one cubit^&#42;1^ to his life span?

[NOTE]
====
. See App. B14.
====

[[v40-6-28]]

^<<v40-6-28,28>>^ Also, why are you anxious about clothing? Take a lesson from the lilies of the field, how they grow; they do not toil, nor do they spin;

[[v40-6-29]]

^<<v40-6-29,29>>^ but I tell you that not even Solʹo·mon in all his glory was arrayed as one of these.

[[v40-6-30]]

^<<v40-6-30,30>>^ Now if this is how God clothes the vegetation of the field that is here today and tomorrow is thrown into the oven, will he not much rather clothe you, you with little faith?

[[v40-6-31]]

^<<v40-6-31,31>>^ So never be anxious and say, ‘What are we to eat?’ or, ‘What are we to drink?’ or, ‘What are we to wear?’

[[v40-6-32]]

^<<v40-6-32,32>>^ For all these are the things the nations are eagerly pursuing. Your heavenly Father knows that you need all these things.

[[v40-6-33]]

^<<v40-6-33,33>>^ “Keep on, then, seeking first the Kingdom and his righteousness, and all these other things will be added to you.

[[v40-6-34]]

^<<v40-6-34,34>>^ So never be anxious about the next day, for the next day will have its own anxieties. Each day has enough of its own troubles.

'''

xref:040-matthew/040-matthew-005.adoc#v40-5-0[&#60; Capítulo Anterior] | <<v40-6-0,Topo>> | xref:040-matthew/040-matthew-007.adoc#v40-7-0[Próximo Capítulo &#62;]