include::./index.adoc[]

[[v40-17-0]]
=== According to Matthew, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-17-1]]

^<<v40-17-1,1>>^ Six days later Jesus took Peter and James and his brother John along and led them up into a lofty mountain by themselves.

[[v40-17-2]]

^<<v40-17-2,2>>^ And he was transfigured before them; his face shone as the sun, and his outer garments became brilliant^&#42;1^ as the light.

[NOTE]
====
. Or “white.”
====

[[v40-17-3]]

^<<v40-17-3,3>>^ And look! there appeared to them Moses and E·liʹjah conversing with him.

[[v40-17-4]]

^<<v40-17-4,4>>^ Then Peter said to Jesus: “Lord, it is fine for us to be here. If you wish, I will erect three tents here, one for you, one for Moses, and one for E·liʹjah.”

[[v40-17-5]]

^<<v40-17-5,5>>^ While he was still speaking, look! a bright cloud overshadowed them, and look! a voice out of the cloud said: “This is my Son, the beloved, whom I have approved. Listen to him.”

[[v40-17-6]]

^<<v40-17-6,6>>^ At hearing this, the disciples fell facedown and became very much afraid.

[[v40-17-7]]

^<<v40-17-7,7>>^ Then Jesus came near, and touching them, he said: “Get up. Have no fear.”

[[v40-17-8]]

^<<v40-17-8,8>>^ When they looked up, they saw no one but Jesus himself.

[[v40-17-9]]

^<<v40-17-9,9>>^ As they were descending from the mountain, Jesus commanded them: “Tell the vision to no one until the Son of man is raised up from the dead.”

[[v40-17-10]]

^<<v40-17-10,10>>^ However, the disciples put the question to him: “Why, then, do the scribes say that E·liʹjah must come first?”

[[v40-17-11]]

^<<v40-17-11,11>>^ In reply he said: “E·liʹjah is indeed coming and will restore all things.

[[v40-17-12]]

^<<v40-17-12,12>>^ However, I say to you that E·liʹjah has already come, and they did not recognize him but did whatever they wanted with him. In this way also, the Son of man is going to suffer at their hands.”

[[v40-17-13]]

^<<v40-17-13,13>>^ Then the disciples perceived that he spoke to them about John the Baptist.

[[v40-17-14]]

^<<v40-17-14,14>>^ When they came toward the crowd, a man approached him, knelt down to him, and said:

[[v40-17-15]]

^<<v40-17-15,15>>^ “Lord, have mercy on my son, because he is an epileptic and is ill. He falls often into the fire and often into the water.

[[v40-17-16]]

^<<v40-17-16,16>>^ I brought him to your disciples, but they could not cure him.”

[[v40-17-17]]

^<<v40-17-17,17>>^ In reply Jesus said: “O faithless and twisted generation, how long must I continue with you? How long must I put up with you? Bring him here to me.”

[[v40-17-18]]

^<<v40-17-18,18>>^ Then Jesus rebuked the demon, and it came out of him, and the boy was cured from that hour.

[[v40-17-19]]

^<<v40-17-19,19>>^ Then the disciples came to Jesus privately and said: “Why could we not expel it?”

[[v40-17-20]]

^<<v40-17-20,20>>^ He said to them: “Because of your little faith. For truly I say to you, if you have faith the size of a mustard grain, you will say to this mountain, ‘Move from here to there,’ and it will move, and nothing will be impossible for you.”

[[v40-17-21]]

^<<v40-17-21,21>>^ ^&#42;1^ ——

[NOTE]
====
. See App. A3.
====

[[v40-17-22]]

^<<v40-17-22,22>>^ It was while they were gathered together in Galʹi·lee that Jesus said to them: “The Son of man is going to be betrayed into men’s hands,

[[v40-17-23]]

^<<v40-17-23,23>>^ and they will kill him, and on the third day he will be raised up.” And they were very much grieved.

[[v40-17-24]]

^<<v40-17-24,24>>^ After they arrived in Ca·perʹna·um, the men collecting the two drachmas^&#42;1^ tax approached Peter and said: “Does your teacher not pay the two drachmas tax?”

[NOTE]
====
. Lit., “the double drachmas.” See App. B14.
====

[[v40-17-25]]

^<<v40-17-25,25>>^ He said: “Yes.” However, when he entered the house, Jesus spoke to him first and said: “What do you think, Simon? From whom do the kings of the earth receive duties or head tax? From their sons or from the strangers?”

[[v40-17-26]]

^<<v40-17-26,26>>^ When he said: “From the strangers,” Jesus said to him: “Really, then, the sons are tax-free.

[[v40-17-27]]

^<<v40-17-27,27>>^ But that we do not cause them to stumble, go to the sea, cast a fishhook, and take the first fish that comes up, and when you open its mouth, you will find a silver coin.^&#42;1^ Take that and give it to them for me and you.”

[NOTE]
====
. Lit., “stater coin,” considered to be the tetradrachma. See App. B14.
====

'''

xref:040-matthew/040-matthew-016.adoc#v40-16-0[&#60; Capítulo Anterior] | <<v40-17-0,Topo>> | xref:040-matthew/040-matthew-018.adoc#v40-18-0[Próximo Capítulo &#62;]