include::./index.adoc[]

[[v40-21-0]]
=== According to Matthew, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-21-1]]

^<<v40-21-1,1>>^ When they got close to Jerusalem and arrived at Bethʹpha·ge on the Mount of Olives, then Jesus sent two disciples,

[[v40-21-2]]

^<<v40-21-2,2>>^ saying to them: “Go into the village that is within sight, and you will at once find a donkey tied and a colt with her. Untie them and bring them to me.

[[v40-21-3]]

^<<v40-21-3,3>>^ If someone says anything to you, you must say, ‘The Lord needs them.’ At that he will immediately send them.”

[[v40-21-4]]

^<<v40-21-4,4>>^ This actually took place to fulfill what was spoken through the prophet, who said:

[[v40-21-5]]

^<<v40-21-5,5>>^ “Tell the daughter of Zion: ‘Look! Your king is coming to you, mild-tempered and mounted on a donkey, yes, on a colt, the offspring of a beast of burden.’”

[[v40-21-6]]

^<<v40-21-6,6>>^ So the disciples went and did just as Jesus had instructed them.

[[v40-21-7]]

^<<v40-21-7,7>>^ They brought the donkey and its colt, and they put their outer garments on them, and he sat on them.

[[v40-21-8]]

^<<v40-21-8,8>>^ Most of the crowd spread their outer garments on the road, while others were cutting down branches from the trees and spreading them on the road.

[[v40-21-9]]

^<<v40-21-9,9>>^ Moreover, the crowds going ahead of him and those following him kept shouting: “Save, we pray, the Son of David! Blessed is the one who comes in Jehovah’s^&#42;1^ name! Save him, we pray, in the heights above!”

[NOTE]
====
. See App. A5.
====

[[v40-21-10]]

^<<v40-21-10,10>>^ And when he entered Jerusalem, the whole city was in an uproar, saying: “Who is this?”

[[v40-21-11]]

^<<v40-21-11,11>>^ The crowds kept saying: “This is the prophet Jesus, from Nazʹa·reth of Galʹi·lee!”

[[v40-21-12]]

^<<v40-21-12,12>>^ Jesus entered the temple and threw out all those selling and buying in the temple, and he overturned the tables of the money changers and the benches of those selling doves.

[[v40-21-13]]

^<<v40-21-13,13>>^ And he said to them: “It is written, ‘My house will be called a house of prayer,’ but you are making it a cave of robbers.”

[[v40-21-14]]

^<<v40-21-14,14>>^ Also, blind and lame people came to him in the temple, and he cured them.

[[v40-21-15]]

^<<v40-21-15,15>>^ When the chief priests and the scribes saw the marvelous things he did and the boys who were shouting in the temple, “Save, we pray, the Son of David!” they became indignant

[[v40-21-16]]

^<<v40-21-16,16>>^ and said to him: “Do you hear what these are saying?” Jesus said to them: “Yes. Did you never read this, ‘Out of the mouth of children and infants, you have brought forth praise’?”

[[v40-21-17]]

^<<v40-21-17,17>>^ And leaving them behind, he went out of the city to Bethʹa·ny and spent the night there.

[[v40-21-18]]

^<<v40-21-18,18>>^ While returning to the city early in the morning, he felt hungry.

[[v40-21-19]]

^<<v40-21-19,19>>^ He caught sight of a fig tree by the road and went to it, but he found nothing on it except leaves, and he said to it: “Let no fruit come from you ever again.” And the fig tree withered instantly.

[[v40-21-20]]

^<<v40-21-20,20>>^ When the disciples saw this, they were amazed and said: “How is it that the fig tree withered instantly?”

[[v40-21-21]]

^<<v40-21-21,21>>^ In answer Jesus said to them: “Truly I say to you, if you have faith and do not doubt, not only will you do what I did to the fig tree, but even if you say to this mountain, ‘Be lifted up and thrown into the sea,’ it will happen.

[[v40-21-22]]

^<<v40-21-22,22>>^ And all the things you ask in prayer, having faith, you will receive.”

[[v40-21-23]]

^<<v40-21-23,23>>^ After he went into the temple, the chief priests and the elders of the people came up to him while he was teaching and said: “By what authority do you do these things? And who gave you this authority?”

[[v40-21-24]]

^<<v40-21-24,24>>^ In reply Jesus said to them: “I will also ask you one thing. If you tell me, then I will also tell you by what authority I do these things:

[[v40-21-25]]

^<<v40-21-25,25>>^ The baptism by John, from what source was it? From heaven or from men?”^&#42;1^ But they began to reason among themselves, saying: “If we say, ‘From heaven,’ he will say to us, ‘Why, then, did you not believe him?’

[NOTE]
====
. Or “of human origin?”
====

[[v40-21-26]]

^<<v40-21-26,26>>^ But if we say, ‘From men,’ we have the crowd to fear, for they all regard John as a prophet.”

[[v40-21-27]]

^<<v40-21-27,27>>^ So they answered Jesus: “We do not know.” He, in turn, said to them: “Neither am I telling you by what authority I do these things.

[[v40-21-28]]

^<<v40-21-28,28>>^ “What do you think? A man had two children. Going up to the first, he said, ‘Child, go work today in the vineyard.’

[[v40-21-29]]

^<<v40-21-29,29>>^ In answer this one said, ‘I will not,’ but afterward, he felt regret and went out.

[[v40-21-30]]

^<<v40-21-30,30>>^ Approaching the second, he said the same. This one replied, ‘I will, Sir,’ but did not go out.

[[v40-21-31]]

^<<v40-21-31,31>>^ Which of the two did the will of his father?” They said: “The first.” Jesus said to them: “Truly I say to you that the tax collectors and the prostitutes are going ahead of you into the Kingdom of God.

[[v40-21-32]]

^<<v40-21-32,32>>^ For John came to you in a way of righteousness, but you did not believe him. However, the tax collectors and the prostitutes believed him, and even when you saw this, you did not feel regret afterward so as to believe him.

[[v40-21-33]]

^<<v40-21-33,33>>^ “Hear another illustration: There was a man, a landowner, who planted a vineyard and put a fence around it and dug a winepress in it and erected a tower; then he leased it to cultivators and traveled abroad.

[[v40-21-34]]

^<<v40-21-34,34>>^ When the fruit season came around, he sent his slaves to the cultivators to collect his fruit.

[[v40-21-35]]

^<<v40-21-35,35>>^ However, the cultivators took his slaves, and they beat one up, another they killed, another they stoned.

[[v40-21-36]]

^<<v40-21-36,36>>^ Again he sent other slaves, more than the first group, but they did the same to these.

[[v40-21-37]]

^<<v40-21-37,37>>^ Lastly he sent his son to them, saying, ‘They will respect my son.’

[[v40-21-38]]

^<<v40-21-38,38>>^ On seeing the son, the cultivators said among themselves, ‘This is the heir. Come, let us kill him and get his inheritance!’

[[v40-21-39]]

^<<v40-21-39,39>>^ So they took him and threw him out of the vineyard and killed him.

[[v40-21-40]]

^<<v40-21-40,40>>^ Therefore, when the owner of the vineyard comes, what will he do to those cultivators?”

[[v40-21-41]]

^<<v40-21-41,41>>^ They said to him: “Because they are evil, he will bring a terrible^&#42;1^ destruction on them and will lease the vineyard to other cultivators, who will give him the fruits when they become due.”

[NOTE]
====
. Or “an evil.”
====

[[v40-21-42]]

^<<v40-21-42,42>>^ Jesus said to them: “Did you never read in the Scriptures, ‘The stone that the builders rejected, this has become the chief cornerstone.^&#42;1^ This has come from Jehovah,^&#42;2^ and it is marvelous in our eyes’?

[NOTE]
====
. Lit., “the head of the corner.”
. See App. A5.
====

[[v40-21-43]]

^<<v40-21-43,43>>^ This is why I say to you, the Kingdom of God will be taken from you and be given to a nation producing its fruits.

[[v40-21-44]]

^<<v40-21-44,44>>^ Also, the person falling on this stone will be shattered. As for anyone on whom it falls, it will crush him.”

[[v40-21-45]]

^<<v40-21-45,45>>^ When the chief priests and the Pharisees heard his illustrations, they knew that he was speaking about them.

[[v40-21-46]]

^<<v40-21-46,46>>^ Although they wanted to seize^&#42;1^ him, they feared the crowds, because these regarded him as a prophet.

[NOTE]
====
. Or “arrest.”
====

'''

xref:040-matthew/040-matthew-020.adoc#v40-20-0[&#60; Capítulo Anterior] | <<v40-21-0,Topo>> | xref:040-matthew/040-matthew-022.adoc#v40-22-0[Próximo Capítulo &#62;]