include::./index.adoc[]

[[v40-16-0]]
=== According to Matthew, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-16-1]]

^<<v40-16-1,1>>^ Here the Pharisees and Sadducees approached him, and to test him, they asked him to display to them a sign from heaven.

[[v40-16-2]]

^<<v40-16-2,2>>^ In reply he said to them: “When evening falls, you say, ‘It will be fair weather, for the sky is fire-red,’

[[v40-16-3]]

^<<v40-16-3,3>>^ and in the morning, ‘It will be wintry, rainy weather today, for the sky is fire-red but gloomy.’ You know how to interpret the appearance of the sky, but the signs of the times you cannot interpret.

[[v40-16-4]]

^<<v40-16-4,4>>^ A wicked and adulterous^&#42;1^ generation keeps seeking a sign, but no sign will be given it except the sign of Joʹnah.” With that he went away, leaving them behind.

[NOTE]
====
. Or “unfaithful.”
====

[[v40-16-5]]

^<<v40-16-5,5>>^ Now the disciples crossed to the other side and forgot to take bread along.

[[v40-16-6]]

^<<v40-16-6,6>>^ Jesus said to them: “Keep your eyes open and watch out for the leaven of the Pharisees and Sadducees.”

[[v40-16-7]]

^<<v40-16-7,7>>^ So they began to reason among themselves, saying: “We did not take any loaves along.”

[[v40-16-8]]

^<<v40-16-8,8>>^ Knowing this, Jesus said: “Why are you discussing among yourselves that you have no loaves, you with little faith?

[[v40-16-9]]

^<<v40-16-9,9>>^ Do you not yet see the point, or do you not remember the five loaves in the case of the 5,000 and how many baskets you took up?

[[v40-16-10]]

^<<v40-16-10,10>>^ Or the seven loaves in the case of the 4,000 and how many large baskets^&#42;1^ you took up?

[NOTE]
====
. Or “provision baskets.”
====

[[v40-16-11]]

^<<v40-16-11,11>>^ How is it you do not discern that I did not speak to you about bread? But watch out for the leaven of the Pharisees and Sadducees.”

[[v40-16-12]]

^<<v40-16-12,12>>^ Then they grasped that he said to watch out, not for the leaven of bread, but for the teaching of the Pharisees and Sadducees.

[[v40-16-13]]

^<<v40-16-13,13>>^ When he had come into the region of Caes·a·reʹa Phi·lipʹpi, Jesus asked his disciples: “Who are men saying the Son of man is?”

[[v40-16-14]]

^<<v40-16-14,14>>^ They said: “Some say John the Baptist, others E·liʹjah, and still others Jeremiah or one of the prophets.”

[[v40-16-15]]

^<<v40-16-15,15>>^ He said to them: “You, though, who do you say I am?”

[[v40-16-16]]

^<<v40-16-16,16>>^ Simon Peter answered: “You are the Christ, the Son of the living God.”

[[v40-16-17]]

^<<v40-16-17,17>>^ In response Jesus said to him: “Happy you are, Simon son of Joʹnah, because flesh and blood^&#42;1^ did not reveal it to you, but my Father in the heavens did.

[NOTE]
====
. Or “because a human.”
====

[[v40-16-18]]

^<<v40-16-18,18>>^ Also, I say to you: You are Peter, and on this rock I will build my congregation, and the gates of the Grave^&#42;1^ will not overpower it.

[NOTE]
====
. Or “Hades,” that is, the common grave of mankind. See Glossary.
====

[[v40-16-19]]

^<<v40-16-19,19>>^ I will give you the keys of the Kingdom of the heavens, and whatever you may bind on earth will already be bound in the heavens, and whatever you may loosen on earth will already be loosened in the heavens.”

[[v40-16-20]]

^<<v40-16-20,20>>^ Then he sternly instructed the disciples not to tell anybody that he was the Christ.

[[v40-16-21]]

^<<v40-16-21,21>>^ From that time forward, Jesus began explaining to his disciples that he must go to Jerusalem and suffer many things from the elders and chief priests and scribes and be killed, and on the third day be raised up.

[[v40-16-22]]

^<<v40-16-22,22>>^ At this Peter took him aside and began to rebuke him, saying: “Be kind to yourself, Lord; you will not have this happen to you at all.”

[[v40-16-23]]

^<<v40-16-23,23>>^ But turning his back, he said to Peter: “Get behind me, Satan! You are a stumbling block to me, because you think, not God’s thoughts, but those of men.”

[[v40-16-24]]

^<<v40-16-24,24>>^ Then Jesus said to his disciples: “If anyone wants to come after me, let him disown himself and pick up his torture stake^&#42;1^ and keep following me.

[NOTE]
====
. See Glossary.
====

[[v40-16-25]]

^<<v40-16-25,25>>^ For whoever wants to save his life^&#42;1^ will lose it, but whoever loses his life^&#42;2^ for my sake will find it.

[NOTE]
====
. Or “soul.”
. Or “soul.”
====

[[v40-16-26]]

^<<v40-16-26,26>>^ Really, what good will it do a man if he gains the whole world but loses his life?^&#42;1^ Or what will a man give in exchange for his life?^&#42;2^

[NOTE]
====
. Or “soul.”
. Or “soul.”
====

[[v40-16-27]]

^<<v40-16-27,27>>^ For the Son of man is to come in the glory of his Father with his angels, and then he will repay each one according to his behavior.

[[v40-16-28]]

^<<v40-16-28,28>>^ Truly I say to you that there are some of those standing here who will not taste death at all until first they see the Son of man coming in his Kingdom.”

'''

xref:040-matthew/040-matthew-015.adoc#v40-15-0[&#60; Capítulo Anterior] | <<v40-16-0,Topo>> | xref:040-matthew/040-matthew-017.adoc#v40-17-0[Próximo Capítulo &#62;]