include::./index.adoc[]

[[v40-24-0]]
=== According to Matthew, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-24-1]]

^<<v40-24-1,1>>^ Now as Jesus was departing from the temple, his disciples approached to show him the buildings of the temple.

[[v40-24-2]]

^<<v40-24-2,2>>^ In response he said to them: “Do you not see all these things? Truly I say to you, by no means will a stone be left here upon a stone and not be thrown down.”

[[v40-24-3]]

^<<v40-24-3,3>>^ While he was sitting on the Mount of Olives, the disciples approached him privately, saying: “Tell us, when will these things be, and what will be the sign of your presence^&#42;1^ and of the conclusion of the system of things?”^&#42;2^

[NOTE]
====
. See Glossary.
. Or “the age.” See Glossary.
====

[[v40-24-4]]

^<<v40-24-4,4>>^ In answer Jesus said to them: “Look out that nobody misleads you,

[[v40-24-5]]

^<<v40-24-5,5>>^ for many will come on the basis of my name, saying, ‘I am the Christ,’ and will mislead many.

[[v40-24-6]]

^<<v40-24-6,6>>^ You are going to hear of wars and reports of wars. See that you are not alarmed, for these things must take place, but the end is not yet.

[[v40-24-7]]

^<<v40-24-7,7>>^ “For nation will rise against nation and kingdom against kingdom, and there will be food shortages and earthquakes in one place after another.

[[v40-24-8]]

^<<v40-24-8,8>>^ All these things are a beginning of pangs of distress.

[[v40-24-9]]

^<<v40-24-9,9>>^ “Then people will hand you over to tribulation and will kill you, and you will be hated by all the nations on account of my name.

[[v40-24-10]]

^<<v40-24-10,10>>^ Then, too, many will be stumbled and will betray one another and will hate one another.

[[v40-24-11]]

^<<v40-24-11,11>>^ Many false prophets will arise and mislead many;

[[v40-24-12]]

^<<v40-24-12,12>>^ and because of the increasing of lawlessness, the love of the greater number will grow cold.

[[v40-24-13]]

^<<v40-24-13,13>>^ But the one who has endured^&#42;1^ to the end will be saved.

[NOTE]
====
. Or “who endures.”
====

[[v40-24-14]]

^<<v40-24-14,14>>^ And this good news of the Kingdom will be preached in all the inhabited earth for a witness to all the nations, and then the end will come.

[[v40-24-15]]

^<<v40-24-15,15>>^ “Therefore, when you catch sight of the disgusting thing that causes desolation, as spoken about by Daniel the prophet, standing in a holy place (let the reader use discernment),

[[v40-24-16]]

^<<v40-24-16,16>>^ then let those in Ju·deʹa begin fleeing to the mountains.

[[v40-24-17]]

^<<v40-24-17,17>>^ Let the man on the housetop not come down to take the goods out of his house,

[[v40-24-18]]

^<<v40-24-18,18>>^ and let the man in the field not return to pick up his outer garment.

[[v40-24-19]]

^<<v40-24-19,19>>^ Woe to the pregnant women and those nursing a baby in those days!

[[v40-24-20]]

^<<v40-24-20,20>>^ Keep praying that your flight may not occur in wintertime nor on the Sabbath day;

[[v40-24-21]]

^<<v40-24-21,21>>^ for then there will be great tribulation such as has not occurred since the world’s beginning until now, no, nor will occur again.

[[v40-24-22]]

^<<v40-24-22,22>>^ In fact, unless those days were cut short, no flesh would be saved; but on account of the chosen ones those days will be cut short.

[[v40-24-23]]

^<<v40-24-23,23>>^ “Then if anyone says to you, ‘Look! Here is the Christ,’ or, ‘There!’ do not believe it.

[[v40-24-24]]

^<<v40-24-24,24>>^ For false Christs and false prophets will arise and will perform great signs and wonders so as to mislead, if possible, even the chosen ones.

[[v40-24-25]]

^<<v40-24-25,25>>^ Look! I have forewarned you.

[[v40-24-26]]

^<<v40-24-26,26>>^ Therefore, if people say to you, ‘Look! He is in the wilderness,’ do not go out; ‘Look! He is in the inner rooms,’ do not believe it.

[[v40-24-27]]

^<<v40-24-27,27>>^ For just as the lightning comes out of the east and shines over to the west, so the presence^&#42;1^ of the Son of man will be.

[NOTE]
====
. See Glossary.
====

[[v40-24-28]]

^<<v40-24-28,28>>^ Wherever the carcass is, there the eagles will be gathered together.

[[v40-24-29]]

^<<v40-24-29,29>>^ “Immediately after the tribulation of those days, the sun will be darkened, and the moon will not give its light, and the stars will fall from heaven, and the powers of the heavens will be shaken.

[[v40-24-30]]

^<<v40-24-30,30>>^ Then the sign of the Son of man will appear in heaven, and all the tribes of the earth will beat themselves in grief, and they will see the Son of man coming on the clouds of heaven with power and great glory.

[[v40-24-31]]

^<<v40-24-31,31>>^ And he will send out his angels with a great trumpet sound, and they will gather his chosen ones together from the four winds, from one extremity of the heavens to their other extremity.

[[v40-24-32]]

^<<v40-24-32,32>>^ “Now learn this illustration from the fig tree: Just as soon as its young branch grows tender and sprouts its leaves, you know that summer is near.

[[v40-24-33]]

^<<v40-24-33,33>>^ Likewise also you, when you see all these things, know that he is near at the doors.

[[v40-24-34]]

^<<v40-24-34,34>>^ Truly I say to you that this generation will by no means pass away until all these things happen.

[[v40-24-35]]

^<<v40-24-35,35>>^ Heaven and earth will pass away, but my words will by no means pass away.

[[v40-24-36]]

^<<v40-24-36,36>>^ “Concerning that day and hour nobody knows, neither the angels of the heavens nor the Son, but only the Father.

[[v40-24-37]]

^<<v40-24-37,37>>^ For just as the days of Noah were, so the presence^&#42;1^ of the Son of man will be.

[NOTE]
====
. See Glossary.
====

[[v40-24-38]]

^<<v40-24-38,38>>^ For as they were in those days before the Flood, eating and drinking, men marrying and women being given in marriage, until the day that Noah entered into the ark,

[[v40-24-39]]

^<<v40-24-39,39>>^ and they took no note until the Flood came and swept them all away, so the presence of the Son of man will be.

[[v40-24-40]]

^<<v40-24-40,40>>^ Then two men will be in the field; one will be taken along and the other abandoned.

[[v40-24-41]]

^<<v40-24-41,41>>^ Two women will be grinding at the hand mill; one will be taken along and the other abandoned.

[[v40-24-42]]

^<<v40-24-42,42>>^ Keep on the watch, therefore, because you do not know on what day your Lord is coming.

[[v40-24-43]]

^<<v40-24-43,43>>^ “But know one thing: If the householder had known in what watch^&#42;1^ the thief was coming, he would have kept awake and not allowed his house to be broken into.

[NOTE]
====
. Or “at what time of night.”
====

[[v40-24-44]]

^<<v40-24-44,44>>^ On this account, you too prove yourselves ready, because the Son of man is coming at an hour that you do not think to be it.

[[v40-24-45]]

^<<v40-24-45,45>>^ “Who really is the faithful and discreet^&#42;1^ slave whom his master appointed over his domestics, to give them their food at the proper time?

[NOTE]
====
. Or “wise.”
====

[[v40-24-46]]

^<<v40-24-46,46>>^ Happy is that slave if his master on coming finds him doing so!

[[v40-24-47]]

^<<v40-24-47,47>>^ Truly I say to you, he will appoint him over all his belongings.

[[v40-24-48]]

^<<v40-24-48,48>>^ “But if ever that evil slave says in his heart, ‘My master is delaying,’

[[v40-24-49]]

^<<v40-24-49,49>>^ and he starts to beat his fellow slaves and to eat and drink with the confirmed drunkards,

[[v40-24-50]]

^<<v40-24-50,50>>^ the master of that slave will come on a day that he does not expect and in an hour that he does not know,

[[v40-24-51]]

^<<v40-24-51,51>>^ and he will punish him with the greatest severity and will assign him his place with the hypocrites. There is where his weeping and the gnashing of his teeth will be.

'''

xref:040-matthew/040-matthew-023.adoc#v40-23-0[&#60; Capítulo Anterior] | <<v40-24-0,Topo>> | xref:040-matthew/040-matthew-025.adoc#v40-25-0[Próximo Capítulo &#62;]