include::./index.adoc[]

[[v40-27-0]]
=== According to Matthew, 27
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-27-1]]

^<<v40-27-1,1>>^ When morning came, all the chief priests and the elders of the people consulted together against Jesus to put him to death.

[[v40-27-2]]

^<<v40-27-2,2>>^ After binding him, they led him off and handed him over to Pilate, the governor.

[[v40-27-3]]

^<<v40-27-3,3>>^ Then Judas, his betrayer, seeing that Jesus had been condemned, felt remorse and brought the 30 pieces of silver back to the chief priests and elders,

[[v40-27-4]]

^<<v40-27-4,4>>^ saying: “I sinned when I betrayed innocent blood.” They said: “What is that to us? You must see to it!”^&#42;1^

[NOTE]
====
. Or “That is your problem!”
====

[[v40-27-5]]

^<<v40-27-5,5>>^ So he threw the silver pieces into the temple and departed. Then he went off and hanged himself.

[[v40-27-6]]

^<<v40-27-6,6>>^ But the chief priests took the silver pieces and said: “It is not lawful to put them into the sacred treasury, because they are the price of blood.”

[[v40-27-7]]

^<<v40-27-7,7>>^ After consulting together, they used the money to buy the potter’s field as a burial place for strangers.

[[v40-27-8]]

^<<v40-27-8,8>>^ Therefore, that field has been called Field of Blood to this very day.

[[v40-27-9]]

^<<v40-27-9,9>>^ Then what was spoken through Jeremiah the prophet was fulfilled: “And they took the 30 silver pieces, the price that was set on the man, the one on whom a price was set by some of the sons of Israel,

[[v40-27-10]]

^<<v40-27-10,10>>^ and they gave them for the potter’s field, according to what Jehovah^&#42;1^ had commanded me.”

[NOTE]
====
. See App. A5.
====

[[v40-27-11]]

^<<v40-27-11,11>>^ Jesus now stood before the governor, and the governor put the question to him: “Are you the King of the Jews?” Jesus replied: “You yourself say it.”

[[v40-27-12]]

^<<v40-27-12,12>>^ But while he was being accused by the chief priests and elders, he made no answer.

[[v40-27-13]]

^<<v40-27-13,13>>^ Then Pilate said to him: “Do you not hear how many things they are testifying against you?”

[[v40-27-14]]

^<<v40-27-14,14>>^ But he did not answer him, no, not a word, so that the governor was very surprised.

[[v40-27-15]]

^<<v40-27-15,15>>^ Now from festival to festival, it was the custom of the governor to release a prisoner to the crowd, whomever they wanted.

[[v40-27-16]]

^<<v40-27-16,16>>^ Just at that time they were holding a notorious prisoner called Bar·abʹbas.

[[v40-27-17]]

^<<v40-27-17,17>>^ So when they were gathered together, Pilate said to them: “Which one do you want me to release to you, Bar·abʹbas or Jesus the so-called Christ?”

[[v40-27-18]]

^<<v40-27-18,18>>^ For Pilate was aware that out of envy they had handed him over.

[[v40-27-19]]

^<<v40-27-19,19>>^ Moreover, while he was sitting on the judgment seat, his wife sent a message to him, saying: “Have nothing to do with that righteous man, for I suffered a lot today in a dream because of him.”

[[v40-27-20]]

^<<v40-27-20,20>>^ But the chief priests and the elders persuaded the crowds to ask for Bar·abʹbas, but to have Jesus put to death.

[[v40-27-21]]

^<<v40-27-21,21>>^ In response the governor said to them: “Which of the two do you want me to release to you?” They said: “Bar·abʹbas.”

[[v40-27-22]]

^<<v40-27-22,22>>^ Pilate said to them: “What, then, should I do with Jesus the so-called Christ?” They all said: “To the stake with him!”^&#42;1^

[NOTE]
====
. Or “Execute him on the stake!”
====

[[v40-27-23]]

^<<v40-27-23,23>>^ He said: “Why? What bad thing did he do?” Still they kept shouting out all the more: “To the stake with him!”

[[v40-27-24]]

^<<v40-27-24,24>>^ Seeing that it did no good but, rather, an uproar was arising, Pilate took water and washed his hands before the crowd, saying: “I am innocent of the blood of this man. You yourselves must see to it.”

[[v40-27-25]]

^<<v40-27-25,25>>^ At that all the people said in answer: “Let his blood come upon us and upon our children.”

[[v40-27-26]]

^<<v40-27-26,26>>^ Then he released Bar·abʹbas to them, but he had Jesus whipped and handed him over to be executed on the stake.

[[v40-27-27]]

^<<v40-27-27,27>>^ Then the soldiers of the governor took Jesus into the governor’s residence and gathered the whole body of troops together around him.

[[v40-27-28]]

^<<v40-27-28,28>>^ And disrobing him, they draped him with a scarlet cloak,

[[v40-27-29]]

^<<v40-27-29,29>>^ and they braided a crown out of thorns and put it on his head and put a reed in his right hand. And kneeling before him, they mocked him, saying: “Greetings,^&#42;1^ you King of the Jews!”

[NOTE]
====
. Or “Hail.”
====

[[v40-27-30]]

^<<v40-27-30,30>>^ And they spat on him and took the reed and began hitting him on his head.

[[v40-27-31]]

^<<v40-27-31,31>>^ Finally, after they had mocked him, they stripped him of the cloak and put his outer garments on him and led him off to be nailed to the stake.

[[v40-27-32]]

^<<v40-27-32,32>>^ As they were going out, they found a man of Cy·reʹne named Simon. This man they compelled into service to carry his torture stake.^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v40-27-33]]

^<<v40-27-33,33>>^ And when they came to a place called Golʹgo·tha, that is, Skull Place,

[[v40-27-34]]

^<<v40-27-34,34>>^ they gave him wine mixed with gall^&#42;1^ to drink; but after tasting it, he refused to drink it.

[NOTE]
====
. A bitter liquid.
====

[[v40-27-35]]

^<<v40-27-35,35>>^ When they had nailed him to the stake, they distributed his outer garments by casting lots,

[[v40-27-36]]

^<<v40-27-36,36>>^ and they sat there keeping watch over him.

[[v40-27-37]]

^<<v40-27-37,37>>^ They also posted above his head the charge against him, in writing: “This is Jesus the King of the Jews.”

[[v40-27-38]]

^<<v40-27-38,38>>^ Then two robbers were put on stakes alongside him, one on his right and one on his left.

[[v40-27-39]]

^<<v40-27-39,39>>^ And those passing by spoke abusively of him, shaking their heads

[[v40-27-40]]

^<<v40-27-40,40>>^ and saying: “You who would throw down the temple and build it in three days, save yourself! If you are a son of God, come down off the torture stake!”^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v40-27-41]]

^<<v40-27-41,41>>^ In the same way also, the chief priests with the scribes and the elders began mocking him, saying:

[[v40-27-42]]

^<<v40-27-42,42>>^ “Others he saved; himself he cannot save! He is King of Israel; let him now come down off the torture stake,^&#42;1^ and we will believe in him.

[NOTE]
====
. See Glossary.
====

[[v40-27-43]]

^<<v40-27-43,43>>^ He has put his trust in God; let Him now rescue him if He wants him, for he said, ‘I am God’s Son.’”

[[v40-27-44]]

^<<v40-27-44,44>>^ In the same way, even the robbers who were on stakes alongside him were reproaching him.

[[v40-27-45]]

^<<v40-27-45,45>>^ From the sixth hour^&#42;1^ on, a darkness fell over all the land until the ninth hour.^&#42;2^

[NOTE]
====
. That is, about 12:00 noon.
. That is, about 3:00 p.m.
====

[[v40-27-46]]

^<<v40-27-46,46>>^ About the ninth hour, Jesus called out with a loud voice, saying: “Eʹli, Eʹli, laʹma sa·bach·thaʹni?” that is, “My God, my God, why have you forsaken me?”

[[v40-27-47]]

^<<v40-27-47,47>>^ At hearing this, some of those standing there began to say: “This man is calling E·liʹjah.”

[[v40-27-48]]

^<<v40-27-48,48>>^ And immediately one of them ran and took a sponge and soaked it in sour wine and put it on a reed and gave it to him to drink.

[[v40-27-49]]

^<<v40-27-49,49>>^ But the rest of them said: “Let him be! Let us see whether E·liʹjah comes to save him.”

[[v40-27-50]]

^<<v40-27-50,50>>^ Again Jesus called out with a loud voice and yielded up his spirit.^&#42;1^

[NOTE]
====
. Or “and expired.”
====

[[v40-27-51]]

^<<v40-27-51,51>>^ And look! the curtain of the sanctuary was torn in two, from top to bottom, and the earth quaked, and the rocks were split.

[[v40-27-52]]

^<<v40-27-52,52>>^ And the tombs^&#42;1^ were opened, and many bodies of the holy ones who had fallen asleep were raised up

[NOTE]
====
. Or “memorial tombs.”
====

[[v40-27-53]]

^<<v40-27-53,53>>^ (and people coming out from among the tombs after his being raised up entered into the holy city), and they became visible to many people.

[[v40-27-54]]

^<<v40-27-54,54>>^ But when the army officer and those with him keeping watch over Jesus saw the earthquake and the things happening, they grew very much afraid and said: “Certainly this was God’s Son.”

[[v40-27-55]]

^<<v40-27-55,55>>^ And many women were there watching from a distance, who had accompanied Jesus from Galʹi·lee to minister to him;

[[v40-27-56]]

^<<v40-27-56,56>>^ among them were Mary Magʹda·lene and Mary the mother of James and Joʹses and the mother of the sons of Zebʹe·dee.

[[v40-27-57]]

^<<v40-27-57,57>>^ Now as it was late in the afternoon, a rich man of Ar·i·ma·theʹa came, named Joseph, who had also become a disciple of Jesus.

[[v40-27-58]]

^<<v40-27-58,58>>^ This man approached Pilate and asked for the body of Jesus. Then Pilate commanded that it be given to him.

[[v40-27-59]]

^<<v40-27-59,59>>^ Joseph took the body, wrapped it up in clean, fine linen,

[[v40-27-60]]

^<<v40-27-60,60>>^ and laid it in his new tomb,^&#42;1^ which he had quarried in the rock. And after rolling a big stone to the entrance of the tomb,^&#42;2^ he left.

[NOTE]
====
. Or “memorial tomb.”
. Or “memorial tomb.”
====

[[v40-27-61]]

^<<v40-27-61,61>>^ But Mary Magʹda·lene and the other Mary continued there, sitting before the grave.

[[v40-27-62]]

^<<v40-27-62,62>>^ The next day, which was after the Preparation, the chief priests and the Pharisees gathered together before Pilate,

[[v40-27-63]]

^<<v40-27-63,63>>^ saying: “Sir, we recall what that impostor said while he was still alive, ‘After three days I am to be raised up.’

[[v40-27-64]]

^<<v40-27-64,64>>^ Therefore, command that the grave be made secure until the third day, so that his disciples may not come and steal him and say to the people, ‘He was raised up from the dead!’ Then this last deception will be worse than the first.”

[[v40-27-65]]

^<<v40-27-65,65>>^ Pilate said to them: “You may have a guard. Go make it as secure as you know how.”

[[v40-27-66]]

^<<v40-27-66,66>>^ So they went and made the grave secure by sealing the stone and posting a guard.

'''

xref:040-matthew/040-matthew-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-matthew/040-matthew-028.adoc#v40-28-0[Próximo Capítulo &#62;]