include::./index.adoc[]

[[v40-12-0]]
=== According to Matthew, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-12-1]]

^<<v40-12-1,1>>^ At that time Jesus went through the grainfields on the Sabbath. His disciples got hungry and started to pluck heads of grain and to eat.

[[v40-12-2]]

^<<v40-12-2,2>>^ At seeing this, the Pharisees said to him: “Look! Your disciples are doing what is not lawful to do on the Sabbath.”

[[v40-12-3]]

^<<v40-12-3,3>>^ He said to them: “Have you not read what David did when he and the men with him were hungry?

[[v40-12-4]]

^<<v40-12-4,4>>^ How he entered into the house of God and they ate the loaves of presentation,^&#42;1^ something that it was not lawful for him or those with him to eat, but for the priests only?

[NOTE]
====
. Or “the showbread.”
====

[[v40-12-5]]

^<<v40-12-5,5>>^ Or have you not read in the Law that on the Sabbaths the priests in the temple violate the Sabbath and continue guiltless?

[[v40-12-6]]

^<<v40-12-6,6>>^ But I tell you that something greater than the temple is here.

[[v40-12-7]]

^<<v40-12-7,7>>^ However, if you had understood what this means, ‘I want mercy and not sacrifice,’ you would not have condemned the guiltless ones.

[[v40-12-8]]

^<<v40-12-8,8>>^ For the Son of man is Lord of the Sabbath.”

[[v40-12-9]]

^<<v40-12-9,9>>^ After departing from that place, he went into their synagogue,

[[v40-12-10]]

^<<v40-12-10,10>>^ and look! there was a man with a withered^&#42;1^ hand! So they asked him, “Is it lawful to cure on the Sabbath?” so that they might accuse him.

[NOTE]
====
. Or “paralyzed.”
====

[[v40-12-11]]

^<<v40-12-11,11>>^ He said to them: “If you have one sheep and that sheep falls into a pit on the Sabbath, is there a man among you who will not grab hold of it and lift it out?

[[v40-12-12]]

^<<v40-12-12,12>>^ How much more valuable is a man than a sheep! So it is lawful to do a fine thing on the Sabbath.”

[[v40-12-13]]

^<<v40-12-13,13>>^ Then he said to the man: “Stretch out your hand.” And he stretched it out, and it was restored sound like the other hand.

[[v40-12-14]]

^<<v40-12-14,14>>^ But the Pharisees went out and conspired against him to kill him.

[[v40-12-15]]

^<<v40-12-15,15>>^ Having come to know this, Jesus departed from there. Many also followed him, and he cured them all,

[[v40-12-16]]

^<<v40-12-16,16>>^ but he sternly ordered them not to make him known,

[[v40-12-17]]

^<<v40-12-17,17>>^ in order to fulfill what was spoken through Isaiah the prophet, who said:

[[v40-12-18]]

^<<v40-12-18,18>>^ “Look! My servant whom I chose, my beloved, whom I have^&#42;1^ approved! I will put my spirit upon him, and what justice is he will make clear to the nations.

[NOTE]
====
. Or “my soul has.”
====

[[v40-12-19]]

^<<v40-12-19,19>>^ He will not quarrel nor cry aloud, nor will anyone hear his voice in the main streets.

[[v40-12-20]]

^<<v40-12-20,20>>^ No bruised reed will he crush, and no smoldering wick will he extinguish, until he brings justice with success.

[[v40-12-21]]

^<<v40-12-21,21>>^ Indeed, in his name nations will hope.”

[[v40-12-22]]

^<<v40-12-22,22>>^ Then they brought him a demon-possessed man who was blind and speechless, and he cured him, so that the speechless man could speak and see.

[[v40-12-23]]

^<<v40-12-23,23>>^ Well, all the crowds were astounded and began to say: “May this not perhaps be the Son of David?”

[[v40-12-24]]

^<<v40-12-24,24>>^ At hearing this, the Pharisees said: “This fellow does not expel the demons except by means of Be·elʹze·bub,^&#42;1^ the ruler of the demons.”

[NOTE]
====
. A designation applied to Satan.
====

[[v40-12-25]]

^<<v40-12-25,25>>^ Knowing their thoughts, he said to them: “Every kingdom divided against itself comes to ruin, and every city or house divided against itself will not stand.

[[v40-12-26]]

^<<v40-12-26,26>>^ In the same way, if Satan expels Satan, he has become divided against himself; how, then, will his kingdom stand?

[[v40-12-27]]

^<<v40-12-27,27>>^ Moreover, if I expel the demons by means of Be·elʹze·bub, by whom do your sons expel them? This is why they will be your judges.

[[v40-12-28]]

^<<v40-12-28,28>>^ But if it is by means of God’s spirit that I expel the demons, the Kingdom of God has really overtaken you.

[[v40-12-29]]

^<<v40-12-29,29>>^ Or how can anyone invade the house of a strong man and seize his possessions unless he first ties up the strong man? Only then can he plunder his house.

[[v40-12-30]]

^<<v40-12-30,30>>^ Whoever is not on my side is against me, and whoever does not gather with me scatters.

[[v40-12-31]]

^<<v40-12-31,31>>^ “For this reason I say to you, every sort of sin and blasphemy will be forgiven men, but the blasphemy against the spirit will not be forgiven.

[[v40-12-32]]

^<<v40-12-32,32>>^ For example, whoever speaks a word against the Son of man, it will be forgiven him; but whoever speaks against the holy spirit, it will not be forgiven him, no, not in this system of things^&#42;1^ nor in that to come.

[NOTE]
====
. Or “this age.” See Glossary.
====

[[v40-12-33]]

^<<v40-12-33,33>>^ “Either you make the tree fine and its fruit fine or make the tree rotten and its fruit rotten, for by its fruit the tree is known.

[[v40-12-34]]

^<<v40-12-34,34>>^ Offspring of vipers, how can you speak good things when you are wicked? For out of the abundance of the heart the mouth speaks.

[[v40-12-35]]

^<<v40-12-35,35>>^ The good man out of his good treasure sends out good things, whereas the wicked man out of his wicked treasure sends out wicked things.

[[v40-12-36]]

^<<v40-12-36,36>>^ I tell you that men will render an account on Judgment Day for every unprofitable saying that they speak;

[[v40-12-37]]

^<<v40-12-37,37>>^ for by your words you will be declared righteous, and by your words you will be condemned.”

[[v40-12-38]]

^<<v40-12-38,38>>^ Then as an answer to him, some of the scribes and the Pharisees said: “Teacher, we want to see a sign from you.”

[[v40-12-39]]

^<<v40-12-39,39>>^ In reply he said to them: “A wicked and adulterous^&#42;1^ generation keeps on seeking a sign, but no sign will be given it except the sign of Joʹnah the prophet.

[NOTE]
====
. Or “unfaithful.”
====

[[v40-12-40]]

^<<v40-12-40,40>>^ For just as Joʹnah was in the belly of the huge fish for three days and three nights, so the Son of man will be in the heart of the earth for three days and three nights.

[[v40-12-41]]

^<<v40-12-41,41>>^ Men of Ninʹe·veh will rise up in the judgment with this generation and will condemn it, because they repented at what Joʹnah preached. But look! something more than Joʹnah is here.

[[v40-12-42]]

^<<v40-12-42,42>>^ The queen of the south will be raised up in the judgment with this generation and will condemn it, for she came from the ends of the earth to hear the wisdom of Solʹo·mon. But look! something more than Solʹo·mon is here.

[[v40-12-43]]

^<<v40-12-43,43>>^ “When an unclean spirit comes out of a man, it passes through waterless places in search of a resting-place and finds none.

[[v40-12-44]]

^<<v40-12-44,44>>^ Then it says, ‘I will go back to my house from which I moved,’ and on arriving, it finds the house unoccupied but swept clean and adorned.

[[v40-12-45]]

^<<v40-12-45,45>>^ Then it goes and takes along with it seven different spirits more wicked than itself, and after getting inside, they dwell there; and the final circumstances of that man become worse than the first. That is how it will be also with this wicked generation.”

[[v40-12-46]]

^<<v40-12-46,46>>^ While he was yet speaking to the crowds, his mother and brothers were standing outside, seeking to speak to him.

[[v40-12-47]]

^<<v40-12-47,47>>^ So someone said to him: “Look! Your mother and your brothers are standing outside, seeking to speak to you.”

[[v40-12-48]]

^<<v40-12-48,48>>^ In reply he said to the one who spoke to him: “Who is my mother, and who are my brothers?”

[[v40-12-49]]

^<<v40-12-49,49>>^ And extending his hand toward his disciples, he said: “Look! My mother and my brothers!

[[v40-12-50]]

^<<v40-12-50,50>>^ For whoever does the will of my Father who is in heaven, that one is my brother and sister and mother.”

'''

xref:040-matthew/040-matthew-011.adoc#v40-11-0[&#60; Capítulo Anterior] | <<v40-12-0,Topo>> | xref:040-matthew/040-matthew-013.adoc#v40-13-0[Próximo Capítulo &#62;]