include::./index.adoc[]

[[v40-11-0]]
=== According to Matthew, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-11-1]]

^<<v40-11-1,1>>^ When Jesus had finished giving instructions to his 12 disciples, he set out from there to teach and preach in their cities.

[[v40-11-2]]

^<<v40-11-2,2>>^ But John, having heard in jail about the works of the Christ, sent his disciples

[[v40-11-3]]

^<<v40-11-3,3>>^ to ask him: “Are you the Coming One, or are we to expect a different one?”

[[v40-11-4]]

^<<v40-11-4,4>>^ In reply Jesus said to them: “Go and report to John what you are hearing and seeing:

[[v40-11-5]]

^<<v40-11-5,5>>^ The blind are now seeing and the lame are walking, the lepers are being cleansed and the deaf are hearing, the dead are being raised up and the poor are being told the good news.

[[v40-11-6]]

^<<v40-11-6,6>>^ Happy is the one who finds no cause for stumbling in me.”

[[v40-11-7]]

^<<v40-11-7,7>>^ While these were on their way, Jesus began to speak to the crowds about John: “What did you go out into the wilderness to see? A reed being tossed by the wind?

[[v40-11-8]]

^<<v40-11-8,8>>^ What, then, did you go out to see? A man dressed in soft garments?^&#42;1^ Why, those wearing soft garments are in the houses of kings.

[NOTE]
====
. Or “fine clothing?”
====

[[v40-11-9]]

^<<v40-11-9,9>>^ Really, then, why did you go out? To see a prophet? Yes, I tell you, and far more than a prophet.

[[v40-11-10]]

^<<v40-11-10,10>>^ This is the one about whom it is written: ‘Look! I am sending my messenger ahead of you,^&#42;1^ who will prepare your way ahead of you!’

[NOTE]
====
. Lit., “before your face.”
====

[[v40-11-11]]

^<<v40-11-11,11>>^ Truly I say to you, among those born of women, there has not been raised up anyone greater than John the Baptist, but a lesser person in the Kingdom of the heavens is greater than he is.

[[v40-11-12]]

^<<v40-11-12,12>>^ From the days of John the Baptist until now, the Kingdom of the heavens is the goal toward which men press, and those pressing forward are seizing it.

[[v40-11-13]]

^<<v40-11-13,13>>^ For all, the Prophets and the Law, prophesied until John;

[[v40-11-14]]

^<<v40-11-14,14>>^ and if you are willing to accept it, he is ‘E·liʹjah who is to come.’

[[v40-11-15]]

^<<v40-11-15,15>>^ Let the one who has ears listen.

[[v40-11-16]]

^<<v40-11-16,16>>^ “With whom will I compare this generation? It is like young children sitting in the marketplaces who call out to their playmates,

[[v40-11-17]]

^<<v40-11-17,17>>^ saying: ‘We played the flute for you, but you did not dance; we wailed, but you did not beat yourselves in grief.’

[[v40-11-18]]

^<<v40-11-18,18>>^ Likewise, John came neither eating nor drinking, but people say, ‘He has a demon.’

[[v40-11-19]]

^<<v40-11-19,19>>^ The Son of man did come eating and drinking, but people say, ‘Look! A man who is a glutton and is given to drinking wine, a friend of tax collectors and sinners.’ All the same, wisdom is proved righteous^&#42;1^ by its works.”^&#42;2^

[NOTE]
====
. Or “is vindicated.”
. Or “by its results.”
====

[[v40-11-20]]

^<<v40-11-20,20>>^ Then he began to reproach the cities in which most of his powerful works had taken place, for they did not repent:

[[v40-11-21]]

^<<v40-11-21,21>>^ “Woe to you, Cho·raʹzin! Woe to you, Beth·saʹi·da! because if the powerful works that took place in you had taken place in Tyre and Siʹdon, they would long ago have repented in sackcloth and ashes.

[[v40-11-22]]

^<<v40-11-22,22>>^ But I say to you, it will be more endurable for Tyre and Siʹdon on Judgment Day than for you.

[[v40-11-23]]

^<<v40-11-23,23>>^ And you, Ca·perʹna·um, will you perhaps be exalted to heaven? Down to the Grave^&#42;1^ you will come; because if the powerful works that took place in you had taken place in Sodʹom, it would have remained until this very day.

[NOTE]
====
. Or “Hades,” that is, the common grave of mankind. See Glossary.
====

[[v40-11-24]]

^<<v40-11-24,24>>^ But I say to you, it will be more endurable for the land of Sodʹom on Judgment Day than for you.”

[[v40-11-25]]

^<<v40-11-25,25>>^ At that time Jesus said in response: “I publicly praise you, Father, Lord of heaven and earth, because you have hidden these things from the wise and intellectual ones and have revealed them to young children.

[[v40-11-26]]

^<<v40-11-26,26>>^ Yes, O Father, because this is the way you approved.

[[v40-11-27]]

^<<v40-11-27,27>>^ All things have been handed over to me by my Father, and no one fully knows the Son except the Father; neither does anyone fully know the Father except the Son and anyone to whom the Son is willing to reveal him.

[[v40-11-28]]

^<<v40-11-28,28>>^ Come to me, all you who are toiling and loaded down, and I will refresh you.

[[v40-11-29]]

^<<v40-11-29,29>>^ Take my yoke upon you and learn from me, for I am mild-tempered and lowly in heart, and you will find refreshment for yourselves.^&#42;1^

[NOTE]
====
. Or “your souls.”
====

[[v40-11-30]]

^<<v40-11-30,30>>^ For my yoke is kindly,^&#42;1^ and my load is light.”

[NOTE]
====
. Or “easy to bear.”
====

'''

xref:040-matthew/040-matthew-010.adoc#v40-10-0[&#60; Capítulo Anterior] | <<v40-11-0,Topo>> | xref:040-matthew/040-matthew-012.adoc#v40-12-0[Próximo Capítulo &#62;]