include::./index.adoc[]

[[v40-19-0]]
=== According to Matthew, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-19-1]]

^<<v40-19-1,1>>^ When Jesus had finished speaking these things, he departed from Galʹi·lee and came to the borders^&#42;1^ of Ju·deʹa across the Jordan.

[NOTE]
====
. Or “frontiers.”
====

[[v40-19-2]]

^<<v40-19-2,2>>^ Also, large crowds followed him, and he cured them there.

[[v40-19-3]]

^<<v40-19-3,3>>^ And Pharisees came to him intent on testing him, and they asked: “Is it lawful for a man to divorce his wife on every sort of grounds?”

[[v40-19-4]]

^<<v40-19-4,4>>^ In reply he said: “Have you not read that the one who created them from the beginning made them male and female

[[v40-19-5]]

^<<v40-19-5,5>>^ and said: ‘For this reason a man will leave his father and his mother and will stick to his wife, and the two will be one flesh’?

[[v40-19-6]]

^<<v40-19-6,6>>^ So that they are no longer two, but one flesh. Therefore, what God has yoked together, let no man put apart.”

[[v40-19-7]]

^<<v40-19-7,7>>^ They said to him: “Why, then, did Moses direct giving a certificate of dismissal and divorcing her?”

[[v40-19-8]]

^<<v40-19-8,8>>^ He said to them: “Out of regard for your hard-heartedness, Moses made the concession to you of divorcing your wives, but that has not been the case from the beginning.

[[v40-19-9]]

^<<v40-19-9,9>>^ I say to you that whoever divorces his wife, except on the grounds of sexual immorality,^&#42;1^ and marries another commits adultery.”

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
====

[[v40-19-10]]

^<<v40-19-10,10>>^ The disciples said to him: “If that is the situation of a man with his wife, it is not advisable to marry.”

[[v40-19-11]]

^<<v40-19-11,11>>^ He said to them: “Not all men make room for the saying, but only those who have the gift.

[[v40-19-12]]

^<<v40-19-12,12>>^ For there are eunuchs who were born that way, and there are eunuchs who were made eunuchs by men, and there are eunuchs who have made themselves eunuchs on account of the Kingdom of the heavens. Let the one who can make room for it make room for it.”

[[v40-19-13]]

^<<v40-19-13,13>>^ Then young children were brought to him for him to place his hands on them and offer prayer, but the disciples reprimanded them.

[[v40-19-14]]

^<<v40-19-14,14>>^ Jesus, however, said: “Let the young children alone, and do not try to stop them from coming to me, for the Kingdom of the heavens belongs to such ones.”

[[v40-19-15]]

^<<v40-19-15,15>>^ And he placed his hands on them and departed from there.

[[v40-19-16]]

^<<v40-19-16,16>>^ Now look! someone came up to him and said: “Teacher, what good must I do to gain everlasting life?”

[[v40-19-17]]

^<<v40-19-17,17>>^ He said to him: “Why do you ask me about what is good? One there is who is good. If, though, you want to enter into life, observe the commandments continually.”

[[v40-19-18]]

^<<v40-19-18,18>>^ He said to him: “Which ones?” Jesus said: “You must not murder, you must not commit adultery, you must not steal, you must not bear false witness,

[[v40-19-19]]

^<<v40-19-19,19>>^ honor your father and your mother, and you must love your neighbor as yourself.”

[[v40-19-20]]

^<<v40-19-20,20>>^ The young man said to him: “I have kept all of these; what am I still lacking?”

[[v40-19-21]]

^<<v40-19-21,21>>^ Jesus said to him: “If you want to be perfect,^&#42;1^ go sell your belongings and give to the poor, and you will have treasure in heaven; and come be my follower.”

[NOTE]
====
. Or “complete.”
====

[[v40-19-22]]

^<<v40-19-22,22>>^ When the young man heard this, he went away grieved, for he had many possessions.

[[v40-19-23]]

^<<v40-19-23,23>>^ Then Jesus said to his disciples: “Truly I say to you that it will be difficult for a rich man to enter the Kingdom of the heavens.

[[v40-19-24]]

^<<v40-19-24,24>>^ Again I say to you, it is easier for a camel to get through a needle’s eye than for a rich man to enter the Kingdom of God.”

[[v40-19-25]]

^<<v40-19-25,25>>^ When the disciples heard that, they were greatly astounded, saying: “Who really can be saved?”

[[v40-19-26]]

^<<v40-19-26,26>>^ Looking at them intently, Jesus said to them: “With men this is impossible, but with God all things are possible.”

[[v40-19-27]]

^<<v40-19-27,27>>^ Then Peter said in reply: “Look! We have left all things and followed you; what, then, will there be for us?”

[[v40-19-28]]

^<<v40-19-28,28>>^ Jesus said to them: “Truly I say to you, in the re-creation, when the Son of man sits down on his glorious throne, you who have followed me will sit on 12 thrones, judging the 12 tribes of Israel.

[[v40-19-29]]

^<<v40-19-29,29>>^ And everyone who has left houses or brothers or sisters or father or mother or children or lands for the sake of my name will receive a hundred times as much and will inherit everlasting life.

[[v40-19-30]]

^<<v40-19-30,30>>^ “But many who are first will be last, and the last first.

'''

xref:040-matthew/040-matthew-018.adoc#v40-18-0[&#60; Capítulo Anterior] | <<v40-19-0,Topo>> | xref:040-matthew/040-matthew-020.adoc#v40-20-0[Próximo Capítulo &#62;]