include::./index.adoc[]

[[v40-8-0]]
=== According to Matthew, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-8-1]]

^<<v40-8-1,1>>^ After he came down from the mountain, large crowds followed him.

[[v40-8-2]]

^<<v40-8-2,2>>^ And look! a leper came up and did obeisance^&#42;1^ to him, saying: “Lord, if you just want to, you can make me clean.”

[NOTE]
====
. Or “bowed down.”
====

[[v40-8-3]]

^<<v40-8-3,3>>^ So stretching out his hand, he touched him, saying: “I want to! Be made clean.” Immediately his leprosy was cleansed away.

[[v40-8-4]]

^<<v40-8-4,4>>^ Then Jesus said to him: “See that you tell no one, but go, show yourself to the priest, and offer the gift that Moses appointed, for a witness to them.”

[[v40-8-5]]

^<<v40-8-5,5>>^ When he entered Ca·perʹna·um, an army officer came to him, pleading with him

[[v40-8-6]]

^<<v40-8-6,6>>^ and saying: “Sir, my servant is laid up in the house with paralysis, and he is suffering terribly.”

[[v40-8-7]]

^<<v40-8-7,7>>^ He said to him: “When I get there, I will cure him.”

[[v40-8-8]]

^<<v40-8-8,8>>^ The army officer replied: “Sir, I am not worthy to have you come under my roof, but just say the word and my servant will be healed.

[[v40-8-9]]

^<<v40-8-9,9>>^ For I too am a man under authority, having soldiers under me, and I say to this one, ‘Go!’ and he goes, and to another, ‘Come!’ and he comes, and to my slave, ‘Do this!’ and he does it.”

[[v40-8-10]]

^<<v40-8-10,10>>^ When Jesus heard that, he was amazed and said to those following him: “I tell you the truth, with no one in Israel have I found so great a faith.

[[v40-8-11]]

^<<v40-8-11,11>>^ But I tell you that many from east and west will come and recline at the table with Abraham and Isaac and Jacob in the Kingdom of the heavens;

[[v40-8-12]]

^<<v40-8-12,12>>^ whereas the sons of the Kingdom will be thrown into the darkness outside. There is where their weeping and the gnashing of their teeth will be.”

[[v40-8-13]]

^<<v40-8-13,13>>^ Then Jesus said to the army officer: “Go. Just as you have shown faith, so let it come to pass for you.” And the servant was healed in that hour.

[[v40-8-14]]

^<<v40-8-14,14>>^ And Jesus, on coming into Peter’s house, saw his mother-in-law lying down and sick with fever.

[[v40-8-15]]

^<<v40-8-15,15>>^ So he touched her hand, and the fever left her, and she got up and began ministering to him.

[[v40-8-16]]

^<<v40-8-16,16>>^ But after it became evening, people brought him many demon-possessed ones; and he expelled the spirits with a word, and he cured all who were suffering,

[[v40-8-17]]

^<<v40-8-17,17>>^ in order to fulfill what was spoken through Isaiah the prophet: “He himself took our sicknesses and carried our diseases.”

[[v40-8-18]]

^<<v40-8-18,18>>^ When Jesus saw a crowd around him, he gave the command to depart for the other side.

[[v40-8-19]]

^<<v40-8-19,19>>^ And a scribe came up and said to him: “Teacher, I will follow you wherever you go.”

[[v40-8-20]]

^<<v40-8-20,20>>^ But Jesus said to him: “Foxes have dens and birds of heaven have nests, but the Son of man has nowhere to lay down his head.”

[[v40-8-21]]

^<<v40-8-21,21>>^ Then another of the disciples said to him: “Lord, permit me first to go and bury my father.”

[[v40-8-22]]

^<<v40-8-22,22>>^ Jesus said to him: “Keep following me, and let the dead bury their dead.”

[[v40-8-23]]

^<<v40-8-23,23>>^ And when he went aboard a boat, his disciples followed him.

[[v40-8-24]]

^<<v40-8-24,24>>^ Now look! a great storm arose on the sea, so that the boat was being covered by the waves; but he was sleeping.

[[v40-8-25]]

^<<v40-8-25,25>>^ And they came and woke him up, saying: “Lord, save us, we are about to perish!”

[[v40-8-26]]

^<<v40-8-26,26>>^ But he said to them: “Why are you so afraid,^&#42;1^ you with little faith?” Then he got up and rebuked the winds and the sea, and a great calm set in.

[NOTE]
====
. Or “fainthearted.”
====

[[v40-8-27]]

^<<v40-8-27,27>>^ So the men were amazed and said: “What sort of person is this? Even the winds and the sea obey him.”

[[v40-8-28]]

^<<v40-8-28,28>>^ When he came to the other side into the region of the Gad·a·renesʹ, two demon-possessed men coming out from among the tombs^&#42;1^ met him. They were unusually fierce, so nobody had the courage to pass by on that road.

[NOTE]
====
. Or “memorial tombs.”
====

[[v40-8-29]]

^<<v40-8-29,29>>^ And look! they screamed, saying: “What have we to do with you, Son of God? Did you come here to torment us before the appointed time?”

[[v40-8-30]]

^<<v40-8-30,30>>^ A long way off from them, a herd of many swine was feeding.

[[v40-8-31]]

^<<v40-8-31,31>>^ So the demons began to plead with him, saying: “If you expel us, send us into the herd of swine.”

[[v40-8-32]]

^<<v40-8-32,32>>^ And he said to them: “Go!” With that they came out and went off into the swine, and look! the entire herd rushed over the precipice^&#42;1^ into the sea and died in the waters.

[NOTE]
====
. Or “steep bank.”
====

[[v40-8-33]]

^<<v40-8-33,33>>^ But the herders fled, and going into the city, they reported everything, including the account of the demon-possessed men.

[[v40-8-34]]

^<<v40-8-34,34>>^ And look! all the city turned out to meet Jesus, and when they saw him, they urged him to depart from their region.

'''

xref:040-matthew/040-matthew-007.adoc#v40-7-0[&#60; Capítulo Anterior] | <<v40-8-0,Topo>> | xref:040-matthew/040-matthew-009.adoc#v40-9-0[Próximo Capítulo &#62;]