include::./index.adoc[]

[[v40-10-0]]
=== According to Matthew, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v40-10-1]]

^<<v40-10-1,1>>^ So he summoned his 12 disciples and gave them authority over unclean spirits, in order to expel these and to cure every sort of disease and every sort of infirmity.

[[v40-10-2]]

^<<v40-10-2,2>>^ The names of the 12 apostles are these: First, Simon, the one called Peter, and Andrew his brother; James the son of Zebʹe·dee and John his brother;

[[v40-10-3]]

^<<v40-10-3,3>>^ Philip and Bar·tholʹo·mew; Thomas and Matthew the tax collector; James the son of Al·phaeʹus; and Thad·daeʹus;

[[v40-10-4]]

^<<v40-10-4,4>>^ Simon the Ca·na·naeʹan;^&#42;1^ and Judas Is·carʹi·ot, who later betrayed him.

[NOTE]
====
. Or “the zealous one.”
====

[[v40-10-5]]

^<<v40-10-5,5>>^ These 12 Jesus sent out, giving them these instructions: “Do not go off into the road of the nations, and do not enter any Sa·marʹi·tan city;

[[v40-10-6]]

^<<v40-10-6,6>>^ but instead, go continually to the lost sheep of the house of Israel.

[[v40-10-7]]

^<<v40-10-7,7>>^ As you go, preach, saying: ‘The Kingdom of the heavens has drawn near.’

[[v40-10-8]]

^<<v40-10-8,8>>^ Cure the sick, raise up the dead, make lepers clean, expel demons. You received free, give free.

[[v40-10-9]]

^<<v40-10-9,9>>^ Do not acquire gold or silver or copper for your money belts,

[[v40-10-10]]

^<<v40-10-10,10>>^ or a food pouch for the trip, or two garments,^&#42;1^ or sandals, or a staff, for the worker deserves his food.

[NOTE]
====
. Or “an extra garment.”
====

[[v40-10-11]]

^<<v40-10-11,11>>^ “Into whatever city or village you enter, search out who in it is deserving, and stay there until you leave.

[[v40-10-12]]

^<<v40-10-12,12>>^ When you enter the house, greet the household.

[[v40-10-13]]

^<<v40-10-13,13>>^ If the house is deserving, let the peace you wish it come upon it; but if it is not deserving, let the peace from you return upon you.

[[v40-10-14]]

^<<v40-10-14,14>>^ Wherever anyone does not receive you or listen to your words, on going out of that house or that city, shake the dust off your feet.

[[v40-10-15]]

^<<v40-10-15,15>>^ Truly I say to you, it will be more endurable for the land of Sodʹom and Go·morʹrah on Judgment Day than for that city.

[[v40-10-16]]

^<<v40-10-16,16>>^ “Look! I am sending you out as sheep among wolves; so prove yourselves cautious as serpents and yet innocent as doves.

[[v40-10-17]]

^<<v40-10-17,17>>^ Be on your guard against men, for they will hand you over to local courts and they will scourge you in their synagogues.

[[v40-10-18]]

^<<v40-10-18,18>>^ And you will be brought before governors and kings for my sake, for a witness to them and the nations.

[[v40-10-19]]

^<<v40-10-19,19>>^ However, when they hand you over, do not become anxious about how or what you are to speak, for what you are to speak will be given you in that hour;

[[v40-10-20]]

^<<v40-10-20,20>>^ for the ones speaking are not just you, but it is the spirit of your Father that speaks by you.

[[v40-10-21]]

^<<v40-10-21,21>>^ Further, brother will hand brother over to death, and a father his child, and children will rise up against parents and will have them put to death.

[[v40-10-22]]

^<<v40-10-22,22>>^ And you will be hated by all people on account of my name, but the one who has endured^&#42;1^ to the end will be saved.

[NOTE]
====
. Or “who endures.”
====

[[v40-10-23]]

^<<v40-10-23,23>>^ When they persecute you in one city, flee to another; for truly I say to you, you will by no means complete the circuit of the cities of Israel until the Son of man arrives.

[[v40-10-24]]

^<<v40-10-24,24>>^ “A student is not above his teacher, nor a slave above his master.

[[v40-10-25]]

^<<v40-10-25,25>>^ It is enough for the student to become as his teacher, and the slave as his master. If people have called the master of the house Be·elʹze·bub,^&#42;1^ how much more those of his household?

[NOTE]
====
. A designation applied to Satan, the prince, or ruler, of the demons.
====

[[v40-10-26]]

^<<v40-10-26,26>>^ So do not fear them, for there is nothing covered over that will not become uncovered, and nothing secret that will not become known.

[[v40-10-27]]

^<<v40-10-27,27>>^ What I tell you in the darkness, say in the light, and what you hear whispered, preach from the housetops.

[[v40-10-28]]

^<<v40-10-28,28>>^ And do not become fearful of those who kill the body but cannot kill the soul;^&#42;1^ rather, fear him who can destroy both soul and body in Ge·henʹna.^&#42;2^

[NOTE]
====
. Or “life,” that is, life prospects.
. See Glossary.
====

[[v40-10-29]]

^<<v40-10-29,29>>^ Two sparrows sell for a coin of small value,^&#42;1^ do they not? Yet not one of them will fall to the ground without your Father’s knowledge.

[NOTE]
====
. Lit., “for an assarion.” See App. B14.
====

[[v40-10-30]]

^<<v40-10-30,30>>^ But even the hairs of your head are all numbered.

[[v40-10-31]]

^<<v40-10-31,31>>^ So have no fear; you are worth more than many sparrows.

[[v40-10-32]]

^<<v40-10-32,32>>^ “Everyone, then, who acknowledges me before men, I will also acknowledge him before my Father who is in the heavens.

[[v40-10-33]]

^<<v40-10-33,33>>^ But whoever disowns me before men, I will also disown him before my Father who is in the heavens.

[[v40-10-34]]

^<<v40-10-34,34>>^ Do not think I came to bring peace to the earth; I came to bring, not peace, but a sword.

[[v40-10-35]]

^<<v40-10-35,35>>^ For I came to cause division, with a man against his father, and a daughter against her mother, and a daughter-in-law against her mother-in-law.

[[v40-10-36]]

^<<v40-10-36,36>>^ Indeed, a man’s enemies will be those of his own household.

[[v40-10-37]]

^<<v40-10-37,37>>^ Whoever has greater affection for father or mother than for me is not worthy of me; and whoever has greater affection for son or daughter than for me is not worthy of me.

[[v40-10-38]]

^<<v40-10-38,38>>^ And whoever does not accept his torture stake^&#42;1^ and follow after me is not worthy of me.

[NOTE]
====
. See Glossary.
====

[[v40-10-39]]

^<<v40-10-39,39>>^ Whoever finds his soul^&#42;1^ will lose it, and whoever loses his soul^&#42;2^ for my sake will find it.

[NOTE]
====
. Or “life.”
. Or “life.”
====

[[v40-10-40]]

^<<v40-10-40,40>>^ “Whoever receives you receives me also, and whoever receives me receives also the One who sent me.

[[v40-10-41]]

^<<v40-10-41,41>>^ Whoever receives a prophet because he is a prophet will get a prophet’s reward, and whoever receives a righteous man because he is a righteous man will get a righteous man’s reward.

[[v40-10-42]]

^<<v40-10-42,42>>^ And whoever gives one of these little ones only a cup of cold water to drink because he is a disciple, I tell you truly, he will by no means lose his reward.”

'''

xref:040-matthew/040-matthew-009.adoc#v40-9-0[&#60; Capítulo Anterior] | <<v40-10-0,Topo>> | xref:040-matthew/040-matthew-011.adoc#v40-11-0[Próximo Capítulo &#62;]