include::./index.adoc[]

[[v47-2-0]]
=== The Second to the Corinthians, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v47-2-1]]

^<<v47-2-1,1>>^ For I have made up my mind not to come to you again in sadness.

[[v47-2-2]]

^<<v47-2-2,2>>^ For if I make you sad, who will be there to cheer me up except the one I saddened?

[[v47-2-3]]

^<<v47-2-3,3>>^ I wrote what I did, so that when I come I may not be saddened by those over whom I ought to rejoice, because I have confidence that what brings me joy brings all of you the same joy.

[[v47-2-4]]

^<<v47-2-4,4>>^ For out of much tribulation and anguish of heart I wrote you with many tears, not to sadden you, but to let you know the depth of love I have for you.

[[v47-2-5]]

^<<v47-2-5,5>>^ Now if anyone has caused sadness, he has saddened, not me, but all of you to an extent—not to be too harsh in what I say.

[[v47-2-6]]

^<<v47-2-6,6>>^ This rebuke given by the majority is sufficient for such a man;

[[v47-2-7]]

^<<v47-2-7,7>>^ now you should instead kindly forgive and comfort him, so that he may not be overwhelmed^&#42;1^ by excessive sadness.

[NOTE]
====
. Or “swallowed up.”
====

[[v47-2-8]]

^<<v47-2-8,8>>^ I therefore exhort you to confirm your love for him.

[[v47-2-9]]

^<<v47-2-9,9>>^ For this is also why I wrote to you: to determine whether you would give proof of your obedience in all things.

[[v47-2-10]]

^<<v47-2-10,10>>^ If you forgive anyone for anything, I do also. In fact, whatever I have forgiven (if I have forgiven anything) has been for your sake in Christ’s sight,

[[v47-2-11]]

^<<v47-2-11,11>>^ so that we may not be overreached^&#42;1^ by Satan, for we are not ignorant of his designs.^&#42;2^

[NOTE]
====
. Or “outwitted.”
. Or “intentions; schemes.”
====

[[v47-2-12]]

^<<v47-2-12,12>>^ Now when I arrived in Troʹas to declare the good news about the Christ and a door was opened to me in the Lord,

[[v47-2-13]]

^<<v47-2-13,13>>^ my spirit felt no relief because of not finding Titus my brother. So I said good-bye to them and departed for Mac·e·doʹni·a.

[[v47-2-14]]

^<<v47-2-14,14>>^ But thanks be to God, who always leads us in a triumphal procession in company with the Christ and through us spreads^&#42;1^ the fragrance of the knowledge of him in every place!

[NOTE]
====
. Or “makes perceptible.”
====

[[v47-2-15]]

^<<v47-2-15,15>>^ For to God we are a sweet fragrance of Christ among those who are being saved and among those who are perishing;

[[v47-2-16]]

^<<v47-2-16,16>>^ to the latter ones an odor^&#42;1^ of death leading to death, to the former ones a fragrance of life leading to life. And who is adequately qualified for these things?

[NOTE]
====
. Or “fragrance.”
====

[[v47-2-17]]

^<<v47-2-17,17>>^ We are, for we are not peddlers of^&#42;1^ the word of God as many men are, but we speak in all sincerity as sent from God, yes, in the sight of God and in company with Christ.

[NOTE]
====
. Or “not commercializing; not making profit from.”
====

'''

xref:047-2-corinthians/047-2-corinthians-001.adoc#v47-1-0[&#60; Capítulo Anterior] | <<v47-2-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-003.adoc#v47-3-0[Próximo Capítulo &#62;]