include::./index.adoc[]

[[v47-8-0]]
=== The Second to the Corinthians, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v47-8-1]]

^<<v47-8-1,1>>^ Now we want you to know, brothers, about the undeserved kindness of God that has been granted to the congregations of Mac·e·doʹni·a.

[[v47-8-2]]

^<<v47-8-2,2>>^ During a great test under affliction, their abundance of joy and their deep poverty made the riches of their generosity abound.^&#42;1^

[NOTE]
====
. Or “overflow.”
====

[[v47-8-3]]

^<<v47-8-3,3>>^ For it was according to their means, yes, I testify, it was even beyond their means,

[[v47-8-4]]

^<<v47-8-4,4>>^ while they on their own initiative kept earnestly begging us for the privilege of kindly giving, to have a share in the relief ministry for the holy ones.

[[v47-8-5]]

^<<v47-8-5,5>>^ And not merely as we had hoped, but first they gave themselves to the Lord and to us through God’s will.

[[v47-8-6]]

^<<v47-8-6,6>>^ So we encouraged Titus that, just as he had initiated this work among you, he should also complete this same kind giving on your part.

[[v47-8-7]]

^<<v47-8-7,7>>^ Nevertheless, just as you abound in everything, in faith and word and knowledge and all earnestness and in our love for you, may you also abound in this kind giving.

[[v47-8-8]]

^<<v47-8-8,8>>^ I am saying this, not to command you, but to make you aware of the earnestness of others and to test the genuineness of your love.

[[v47-8-9]]

^<<v47-8-9,9>>^ For you know the undeserved kindness of our Lord Jesus Christ, that although he was rich, he became poor for your sake, so that you might become rich through his poverty.

[[v47-8-10]]

^<<v47-8-10,10>>^ And in this I give my opinion: This is for your benefit, seeing that already a year ago you not only initiated the action but also showed your desire to do it.

[[v47-8-11]]

^<<v47-8-11,11>>^ So now, also complete what you started to do, so that your readiness to act may be completed according to the means you have available.

[[v47-8-12]]

^<<v47-8-12,12>>^ For if the readiness is there first, it is especially acceptable according to what a person has, not according to what a person does not have.

[[v47-8-13]]

^<<v47-8-13,13>>^ For I do not want to make it easy for others, but difficult for you;

[[v47-8-14]]

^<<v47-8-14,14>>^ but that by means of an equalizing, your surplus at the present time might offset their need, so that their surplus might also offset your deficiency, that there may be an equalizing.

[[v47-8-15]]

^<<v47-8-15,15>>^ Just as it is written: “The person with much did not have too much, and the person with little did not have too little.”

[[v47-8-16]]

^<<v47-8-16,16>>^ Now thanks be to God for putting the same earnest concern for you in the heart of Titus,

[[v47-8-17]]

^<<v47-8-17,17>>^ because he has indeed responded to the encouragement, but being very eager, he is coming to you on his own initiative.

[[v47-8-18]]

^<<v47-8-18,18>>^ But we are sending along with him the brother whose praise in connection with the good news has spread through all the congregations.

[[v47-8-19]]

^<<v47-8-19,19>>^ Not only that, but he was also appointed by the congregations to be our traveling companion as we administer this kind gift for the glory of the Lord and in proof of our readiness to assist.

[[v47-8-20]]

^<<v47-8-20,20>>^ Thus we are avoiding having any man find fault with us in connection with this liberal contribution that we are administering.

[[v47-8-21]]

^<<v47-8-21,21>>^ For we ‘care for everything honestly, not only in the sight of Jehovah^&#42;1^ but also in the sight of men.’

[NOTE]
====
. See App. A5.
====

[[v47-8-22]]

^<<v47-8-22,22>>^ Moreover, we are sending with them our brother whom we have often tested and found to be diligent in many matters, but now much more diligent on account of his great confidence in you.

[[v47-8-23]]

^<<v47-8-23,23>>^ If, though, there is any question about Titus, he is my companion^&#42;1^ and a fellow worker for your interests; or if there are questions about our brothers, they are apostles of congregations and a glory of Christ.

[NOTE]
====
. Lit., “sharer.”
====

[[v47-8-24]]

^<<v47-8-24,24>>^ So demonstrate the proof of your love to them, and show the congregations why we boasted about you.

'''

xref:047-2-corinthians/047-2-corinthians-007.adoc#v47-7-0[&#60; Capítulo Anterior] | <<v47-8-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-009.adoc#v47-9-0[Próximo Capítulo &#62;]