include::./index.adoc[]

[[v47-4-0]]
=== The Second to the Corinthians, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v47-4-1]]

^<<v47-4-1,1>>^ Therefore, since we have this ministry through the mercy that was shown us, we do not give up.

[[v47-4-2]]

^<<v47-4-2,2>>^ But we have renounced the shameful, underhanded things, not walking with cunning or adulterating the word of God; but by making the truth manifest, we recommend ourselves to every human conscience in the sight of God.

[[v47-4-3]]

^<<v47-4-3,3>>^ If, in fact, the good news we declare is veiled, it is veiled among those who are perishing,

[[v47-4-4]]

^<<v47-4-4,4>>^ among whom the god of this system of things^&#42;1^ has blinded the minds of the unbelievers, so that the illumination^&#42;2^ of the glorious good news about the Christ, who is the image of God, might not shine through.

[NOTE]
====
. Or “this age.” See Glossary.
. Or “light.”
====

[[v47-4-5]]

^<<v47-4-5,5>>^ For we are preaching, not about ourselves, but about Jesus Christ as Lord and ourselves as your slaves for Jesus’ sake.

[[v47-4-6]]

^<<v47-4-6,6>>^ For God is the one who said: “Let the light shine out of darkness,” and he has shone on our hearts to illuminate them with the glorious knowledge of God by the face of Christ.

[[v47-4-7]]

^<<v47-4-7,7>>^ However, we have this treasure in earthen vessels,^&#42;1^ so that the power beyond what is normal may be God’s and not from us.

[NOTE]
====
. Or “in jars of clay.”
====

[[v47-4-8]]

^<<v47-4-8,8>>^ We are hard-pressed in every way, but not cramped beyond movement; we are perplexed, but not absolutely with no way out;^&#42;1^

[NOTE]
====
. Or possibly, “not left in despair.”
====

[[v47-4-9]]

^<<v47-4-9,9>>^ we are persecuted, but not abandoned; we are knocked down, but not destroyed.

[[v47-4-10]]

^<<v47-4-10,10>>^ Always we endure in our body the death-dealing treatment that Jesus suffered, that the life of Jesus may also be made manifest in our body.

[[v47-4-11]]

^<<v47-4-11,11>>^ For we who live are ever being brought face-to-face with death for Jesus’ sake, so that the life of Jesus may also be made manifest in our mortal flesh.

[[v47-4-12]]

^<<v47-4-12,12>>^ So death is at work in us, but life in you.

[[v47-4-13]]

^<<v47-4-13,13>>^ Now because we have the same spirit of faith as that of which it is written: “I exercised faith, therefore I spoke”; we too exercise faith and therefore we speak,

[[v47-4-14]]

^<<v47-4-14,14>>^ knowing that the One who raised Jesus up will raise us up also with Jesus and will present us together with you.

[[v47-4-15]]

^<<v47-4-15,15>>^ For all these things are for your sake, so that the increase of the undeserved kindness should abound even more because many more are offering thanksgiving to the glory of God.

[[v47-4-16]]

^<<v47-4-16,16>>^ Therefore, we do not give up, but even if the man we are outside is wasting away, certainly the man we are inside is being renewed from day to day.

[[v47-4-17]]

^<<v47-4-17,17>>^ For though the tribulation^&#42;1^ is momentary and light, it works out for us a glory that is of more and more surpassing greatness^&#42;2^ and is everlasting;

[NOTE]
====
. Or “trial.”
. Lit., “weight.”
====

[[v47-4-18]]

^<<v47-4-18,18>>^ while we keep our eyes, not on the things seen, but on the things unseen. For the things seen are temporary, but the things unseen are everlasting.

'''

xref:047-2-corinthians/047-2-corinthians-003.adoc#v47-3-0[&#60; Capítulo Anterior] | <<v47-4-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-005.adoc#v47-5-0[Próximo Capítulo &#62;]