include::./index.adoc[]

[[v47-5-0]]
=== The Second to the Corinthians, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v47-5-1]]

^<<v47-5-1,1>>^ For we know that if our earthly house, this tent, should be torn down,^&#42;1^ we are to have a building from God, a house not made with hands, everlasting in the heavens.

[NOTE]
====
. Or “dissolved.”
====

[[v47-5-2]]

^<<v47-5-2,2>>^ For in this house^&#42;1^ we do indeed groan, earnestly desiring to put on the one for us^&#42;2^ from heaven,^&#42;3^

[NOTE]
====
. Or “dwelling.”
. Or “to put on our dwelling that is.”
. Or “our heavenly dwelling.”
====

[[v47-5-3]]

^<<v47-5-3,3>>^ so that when we do put it on, we will not be found naked.

[[v47-5-4]]

^<<v47-5-4,4>>^ In fact, we who are in this tent groan, being weighed down, because we do not want to put this one off, but we want to put the other on, so that what is mortal may be swallowed up by life.

[[v47-5-5]]

^<<v47-5-5,5>>^ Now the one who prepared us for this very thing is God, who gave us the spirit as a token of what is to come.^&#42;1^

[NOTE]
====
. Or “a down payment (earnest money); a guarantee (pledge) of what is to come.”
====

[[v47-5-6]]

^<<v47-5-6,6>>^ So we are always of good courage and know that while we have our home in the body, we are absent from the Lord,

[[v47-5-7]]

^<<v47-5-7,7>>^ for we are walking by faith, not by sight.

[[v47-5-8]]

^<<v47-5-8,8>>^ But we are of good courage and would prefer to be absent from the body and to make our home with the Lord.

[[v47-5-9]]

^<<v47-5-9,9>>^ So whether at home with him or absent from him, we make it our aim to be acceptable to him.

[[v47-5-10]]

^<<v47-5-10,10>>^ For we must all appear^&#42;1^ before the judgment seat of the Christ, so that each one may be repaid according to the things he has practiced while in the body, whether good or bad.^&#42;2^

[NOTE]
====
. Or “be made manifest.”
. Or “vile.”
====

[[v47-5-11]]

^<<v47-5-11,11>>^ Therefore, since we know the fear of the Lord, we keep persuading men, but we are well-known^&#42;1^ to God. However, I hope that we are well-known^&#42;2^ also to your consciences.

[NOTE]
====
. Or “manifest.”
. Or “manifest.”
====

[[v47-5-12]]

^<<v47-5-12,12>>^ We are not recommending ourselves to you again but giving you an incentive to boast about us, so that you may be able to answer those who boast over the outward appearance but not over what is in the heart.

[[v47-5-13]]

^<<v47-5-13,13>>^ For if we were out of our mind, it was for God; if we are sound in mind, it is for you.

[[v47-5-14]]

^<<v47-5-14,14>>^ For the love the Christ has compels us, because this is what we have concluded, that one man died for all; so, then, all had died.

[[v47-5-15]]

^<<v47-5-15,15>>^ And he died for all so that those who live should live no longer for themselves, but for him who died for them and was raised up.

[[v47-5-16]]

^<<v47-5-16,16>>^ So from now on we know no man from a fleshly viewpoint. Even if we once knew Christ according to the flesh, we certainly no longer know him in that way.

[[v47-5-17]]

^<<v47-5-17,17>>^ Therefore, if anyone is in union with Christ, he is a new creation; the old things passed away; look! new things have come into existence.

[[v47-5-18]]

^<<v47-5-18,18>>^ But all things are from God, who reconciled us to himself through Christ and gave us the ministry of the reconciliation,

[[v47-5-19]]

^<<v47-5-19,19>>^ namely, that God was by means of Christ reconciling a world to himself, not counting their offenses against them, and he entrusted to us the message of the reconciliation.

[[v47-5-20]]

^<<v47-5-20,20>>^ Therefore, we are ambassadors substituting for Christ, as though God were making an appeal through us. As substitutes for Christ, we beg: “Become reconciled to God.”

[[v47-5-21]]

^<<v47-5-21,21>>^ The one who did not know sin, he made to be sin^&#42;1^ for us, so that by means of him we might become God’s righteousness.

[NOTE]
====
. Or “a sin offering.”
====

'''

xref:047-2-corinthians/047-2-corinthians-004.adoc#v47-4-0[&#60; Capítulo Anterior] | <<v47-5-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-006.adoc#v47-6-0[Próximo Capítulo &#62;]