include::./index.adoc[]

[[v47-6-0]]
=== The Second to the Corinthians, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v47-6-1]]

^<<v47-6-1,1>>^ Working together with him, we also urge you not to accept the undeserved kindness of God and miss its purpose.

[[v47-6-2]]

^<<v47-6-2,2>>^ For he says: “In an acceptable time I heard you, and in a day of salvation I helped you.” Look! Now is the especially acceptable time. Look! Now is the day of salvation.

[[v47-6-3]]

^<<v47-6-3,3>>^ In no way are we giving any cause for stumbling, so that no fault may be found with our ministry;

[[v47-6-4]]

^<<v47-6-4,4>>^ but in every way we recommend ourselves as God’s ministers, by the endurance of much, by tribulations, by times of need, by difficulties,

[[v47-6-5]]

^<<v47-6-5,5>>^ by beatings, by imprisonments, by riots, by hard work, by sleepless nights, by times without food;

[[v47-6-6]]

^<<v47-6-6,6>>^ by purity, by knowledge, by patience, by kindness, by holy spirit, by love free from hypocrisy,

[[v47-6-7]]

^<<v47-6-7,7>>^ by truthful speech, by God’s power; through the weapons of righteousness in the right hand^&#42;1^ and in the left,^&#42;2^

[NOTE]
====
. Perhaps for offense.
. Perhaps for defense.
====

[[v47-6-8]]

^<<v47-6-8,8>>^ through glory and dishonor, through bad report and good report. We are regarded as deceivers and yet we are truthful,

[[v47-6-9]]

^<<v47-6-9,9>>^ as unknown and yet we are recognized, as dying^&#42;1^ and yet look! we live, as punished^&#42;2^ and yet not handed over to death,

[NOTE]
====
. Or “considered worthy of death.”
. Or “disciplined.”
====

[[v47-6-10]]

^<<v47-6-10,10>>^ as sorrowing but ever rejoicing, as poor but making many rich, as having nothing and yet possessing all things.

[[v47-6-11]]

^<<v47-6-11,11>>^ We have opened our mouth to speak^&#42;1^ to you, Corinthians, and we have opened wide our heart.

[NOTE]
====
. Or “have spoken openly.”
====

[[v47-6-12]]

^<<v47-6-12,12>>^ We are not restricted in^&#42;1^ our affections for you, but you are restricted in your own tender affections for us.

[NOTE]
====
. Or “cramped for room in.”
====

[[v47-6-13]]

^<<v47-6-13,13>>^ So in response—I speak as to my children—you too open your hearts wide.^&#42;1^

[NOTE]
====
. Or “you too widen out.”
====

[[v47-6-14]]

^<<v47-6-14,14>>^ Do not become unevenly yoked^&#42;1^ with unbelievers. For what fellowship do righteousness and lawlessness have? Or what sharing does light have with darkness?

[NOTE]
====
. Or “joined.”
====

[[v47-6-15]]

^<<v47-6-15,15>>^ Further, what harmony is there between Christ and Beʹli·al?^&#42;1^ Or what does a believer^&#42;2^ share in common^&#42;3^ with an unbeliever?

[NOTE]
====
. From a Hebrew word meaning “Good for Nothing.” A reference to Satan.
. Or “a faithful person.”
. Or “what share does a believer have.”
====

[[v47-6-16]]

^<<v47-6-16,16>>^ And what agreement does God’s temple have with idols? For we are a temple of a living God; just as God said: “I will reside among them and walk among them, and I will be their God, and they will be my people.”

[[v47-6-17]]

^<<v47-6-17,17>>^ “‘Therefore, get out from among them, and separate yourselves,’ says Jehovah,^&#42;1^ ‘and quit touching the unclean thing’”; “‘and I will take you in.’”

[NOTE]
====
. See App. A5.
====

[[v47-6-18]]

^<<v47-6-18,18>>^ “‘And I will become a father to you, and you will become sons and daughters to me,’ says Jehovah,^&#42;1^ the Almighty.”

[NOTE]
====
. See App. A5.
====

'''

xref:047-2-corinthians/047-2-corinthians-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-007.adoc#v47-7-0[Próximo Capítulo &#62;]