include::./index.adoc[]

[[v47-3-0]]
=== The Second to the Corinthians, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v47-3-1]]

^<<v47-3-1,1>>^ Are we starting to recommend ourselves again? Or do we need, like some men, letters of recommendation to you or from you?

[[v47-3-2]]

^<<v47-3-2,2>>^ You yourselves are our letter, inscribed on our hearts and known and being read by all mankind.

[[v47-3-3]]

^<<v47-3-3,3>>^ For you are shown to be a letter of Christ written by us as ministers, inscribed not with ink but with the spirit of a living God, not on stone tablets but on fleshly tablets, on hearts.

[[v47-3-4]]

^<<v47-3-4,4>>^ We have this sort of confidence toward God through the Christ.

[[v47-3-5]]

^<<v47-3-5,5>>^ Not that we of ourselves are adequately qualified to consider that anything comes from us, but our being adequately qualified comes from God,

[[v47-3-6]]

^<<v47-3-6,6>>^ who has indeed adequately qualified us to be ministers of a new covenant, not of a written code, but of spirit; for the written code condemns to death, but the spirit makes alive.

[[v47-3-7]]

^<<v47-3-7,7>>^ Now if the code that administers death and that was engraved in letters on stones came with such glory that the sons of Israel could not gaze at the face of Moses because of the glory of his face, a glory that was to be done away with,

[[v47-3-8]]

^<<v47-3-8,8>>^ why should the administering of the spirit not be with even greater glory?

[[v47-3-9]]

^<<v47-3-9,9>>^ For if the code administering condemnation was glorious, how much more glorious would be the administering of righteousness!

[[v47-3-10]]

^<<v47-3-10,10>>^ In fact, even what had once been made glorious has been stripped of glory because of the glory that excels it.

[[v47-3-11]]

^<<v47-3-11,11>>^ For if what was to be done away with was brought in with glory, how much greater would be the glory of what remains!

[[v47-3-12]]

^<<v47-3-12,12>>^ Since we have such a hope, we are using great freeness of speech,

[[v47-3-13]]

^<<v47-3-13,13>>^ and not doing what Moses did when he would put a veil over his face so that the sons of Israel might not gaze intently at the end of what was to be done away with.

[[v47-3-14]]

^<<v47-3-14,14>>^ But their minds were dulled. For to this present day, the same veil remains unlifted when the old covenant is read, because it is taken away only by means of Christ.

[[v47-3-15]]

^<<v47-3-15,15>>^ In fact, to this day whenever Moses is read, a veil lies upon their hearts.

[[v47-3-16]]

^<<v47-3-16,16>>^ But when one turns to Jehovah,^&#42;1^ the veil is taken away.

[NOTE]
====
. See App. A5.
====

[[v47-3-17]]

^<<v47-3-17,17>>^ Now Jehovah^&#42;1^ is the Spirit, and where the spirit of Jehovah^&#42;2^ is, there is freedom.

[NOTE]
====
. See App. A5.
. See App. A5.
====

[[v47-3-18]]

^<<v47-3-18,18>>^ And all of us, while we with unveiled faces reflect like mirrors the glory of Jehovah,^&#42;1^ are transformed into the same image from one degree of glory to another,^&#42;2^ exactly as it is done by Jehovah^&#42;3^ the Spirit.^&#42;4^

[NOTE]
====
. See App. A5.
. Lit., “from glory to glory.”
. See App. A5.
. Or possibly, “by the spirit of Jehovah.”
====

'''

xref:047-2-corinthians/047-2-corinthians-002.adoc#v47-2-0[&#60; Capítulo Anterior] | <<v47-3-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-004.adoc#v47-4-0[Próximo Capítulo &#62;]