include::./index.adoc[]

[[v47-10-0]]
=== The Second to the Corinthians, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v47-10-1]]

^<<v47-10-1,1>>^ Now I myself, Paul, appeal to you by the mildness and kindness of the Christ, lowly though I am when among you face-to-face, but bold toward you when absent.

[[v47-10-2]]

^<<v47-10-2,2>>^ I beg that when present, I may not have to be bold and take the strong measures that I expect against some who view us as if we walked in a fleshly manner.

[[v47-10-3]]

^<<v47-10-3,3>>^ For though we walk in the flesh, we do not wage warfare according to what we are in the flesh.

[[v47-10-4]]

^<<v47-10-4,4>>^ For the weapons of our warfare are not fleshly, but powerful by God for overturning strongly entrenched things.

[[v47-10-5]]

^<<v47-10-5,5>>^ For we are overturning reasonings and every lofty thing raised up against the knowledge of God, and we are bringing every thought into captivity to make it obedient to the Christ;

[[v47-10-6]]

^<<v47-10-6,6>>^ and we are prepared to inflict punishment for every disobedience, as soon as your own obedience is complete.

[[v47-10-7]]

^<<v47-10-7,7>>^ You look at things according to their face value. If anyone is confident in himself that he belongs to Christ, let him reflect again on this fact: Just as he belongs to Christ, so do we also.

[[v47-10-8]]

^<<v47-10-8,8>>^ For even if I should boast a bit too much about the authority that the Lord gave us to build you up and not to tear you down, I would not be put to shame.

[[v47-10-9]]

^<<v47-10-9,9>>^ For I do not want to seem as though I were trying to terrify you by my letters.

[[v47-10-10]]

^<<v47-10-10,10>>^ For they say: “His letters are weighty and forceful, but his presence in person is weak and his speech contemptible.”

[[v47-10-11]]

^<<v47-10-11,11>>^ Let such a man consider that what we say^&#42;1^ by letters when absent, this we will also do^&#42;2^ when present.

[NOTE]
====
. Lit., “what we are in word.”
. Lit., “also be in action.”
====

[[v47-10-12]]

^<<v47-10-12,12>>^ For we do not dare to class ourselves or compare ourselves with some who recommend themselves. But when they measure themselves by themselves and compare themselves with themselves, they are without understanding.

[[v47-10-13]]

^<<v47-10-13,13>>^ However, we will not boast outside our assigned boundaries, but within the boundary of the territory that God measured out to us,^&#42;1^ making it reach even as far as you.

[NOTE]
====
. Or “apportioned by measure to us.”
====

[[v47-10-14]]

^<<v47-10-14,14>>^ Really, we are not overextending ourselves as if we did not reach you, for we were the first to reach as far as you with the good news about the Christ.

[[v47-10-15]]

^<<v47-10-15,15>>^ No, we are not boasting outside our assigned boundaries about the labors of someone else, but we hope that as your faith continues to increase, what we have done may be made to increase, within our territory. Then we will abound still more,

[[v47-10-16]]

^<<v47-10-16,16>>^ so that we may declare the good news to the countries beyond you, so as not to boast in what has already been done in someone else’s territory.

[[v47-10-17]]

^<<v47-10-17,17>>^ “But the one who boasts, let him boast in Jehovah.”^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v47-10-18]]

^<<v47-10-18,18>>^ For it is not the one who recommends himself who is approved, but the one whom Jehovah^&#42;1^ recommends.

[NOTE]
====
. See App. A5.
====

'''

xref:047-2-corinthians/047-2-corinthians-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-011.adoc#v47-11-0[Próximo Capítulo &#62;]