include::./index.adoc[]

[[v47-9-0]]
=== The Second to the Corinthians, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v47-9-1]]

^<<v47-9-1,1>>^ Now concerning the ministry that is for the holy ones, it is not really necessary for me to write you,

[[v47-9-2]]

^<<v47-9-2,2>>^ for I know your willingness about which I am boasting to the Mac·e·doʹni·ans, that A·chaʹia has been ready now for a year, and your zeal has stirred up the majority of them.

[[v47-9-3]]

^<<v47-9-3,3>>^ But I am sending the brothers, so that our boasting about you might not prove empty in this respect and that you may really be ready, just as I said you would be.

[[v47-9-4]]

^<<v47-9-4,4>>^ Otherwise, if the Mac·e·doʹni·ans should come with me and find you not ready, we—not to mention you—should be put to shame by our confidence in you.

[[v47-9-5]]

^<<v47-9-5,5>>^ So I thought it necessary to encourage the brothers to come to you ahead of time and to get your promised bountiful gift ready in advance, so that this might be ready as a generous gift, and not as something extorted.

[[v47-9-6]]

^<<v47-9-6,6>>^ But as to this, whoever sows sparingly will also reap sparingly, and whoever sows bountifully will also reap bountifully.

[[v47-9-7]]

^<<v47-9-7,7>>^ Let each one do just as he has resolved in his heart, not grudgingly^&#42;1^ or under compulsion, for God loves a cheerful giver.

[NOTE]
====
. Or “reluctantly.”
====

[[v47-9-8]]

^<<v47-9-8,8>>^ Moreover, God is able to cause all his undeserved kindness to abound toward you so that you are always completely self-sufficient in everything, as well as having plenty for every good work.

[[v47-9-9]]

^<<v47-9-9,9>>^ (Just as it is written: “He has distributed widely;^&#42;1^ he has given to the poor. His righteousness continues forever.”

[NOTE]
====
. Or “generously.”
====

[[v47-9-10]]

^<<v47-9-10,10>>^ Now the One who abundantly supplies seed to the sower and bread for eating will supply and multiply the seed for you to sow and will increase the harvest of your righteousness.)

[[v47-9-11]]

^<<v47-9-11,11>>^ In everything you are being enriched for every sort of generosity, which produces through us an expression of thanks to God;

[[v47-9-12]]

^<<v47-9-12,12>>^ because the ministry of this public service is not only to provide well for the needs of the holy ones but also to be rich in many expressions of thanks to God.

[[v47-9-13]]

^<<v47-9-13,13>>^ Through the proof that this relief ministry gives, they glorify God because you are submissive to the good news about the Christ, as you publicly declared, and because you are generous in your contribution to them and to all.

[[v47-9-14]]

^<<v47-9-14,14>>^ And with supplication for you, they express affection for you because of the surpassing undeserved kindness of God upon you.

[[v47-9-15]]

^<<v47-9-15,15>>^ Thanks be to God for his indescribable free gift.

'''

xref:047-2-corinthians/047-2-corinthians-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-010.adoc#v47-10-0[Próximo Capítulo &#62;]