include::./index.adoc[]

[[v47-11-0]]
=== The Second to the Corinthians, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v47-11-1]]

^<<v47-11-1,1>>^ I wish you would put up with me in a little unreasonableness. But, in fact, you are putting up with me!

[[v47-11-2]]

^<<v47-11-2,2>>^ For I am jealous over you with a godly jealousy,^&#42;1^ for I personally promised you in marriage to one husband that I might present you as a chaste^&#42;2^ virgin to the Christ.

[NOTE]
====
. Lit., “God’s zeal.”
. Or “pure.”
====

[[v47-11-3]]

^<<v47-11-3,3>>^ But I am afraid that somehow, as the serpent seduced Eve by its cunning, your minds might be corrupted away from the sincerity and the chastity^&#42;1^ that are due the Christ.

[NOTE]
====
. Or “purity.”
====

[[v47-11-4]]

^<<v47-11-4,4>>^ For as it is, if someone comes and preaches a Jesus other than the one we preached, or you receive a spirit other than what you received, or good news other than what you accepted, you easily put up with him.

[[v47-11-5]]

^<<v47-11-5,5>>^ For I consider that I have not proved inferior to your superfine apostles in a single thing.

[[v47-11-6]]

^<<v47-11-6,6>>^ But even if I am unskilled in speech, I certainly am not in knowledge; indeed we made it clear to you in every way and in everything.

[[v47-11-7]]

^<<v47-11-7,7>>^ Or did I commit a sin by humbling myself that you might be exalted, because I gladly declared the good news of God to you without cost?

[[v47-11-8]]

^<<v47-11-8,8>>^ Other congregations I deprived^&#42;1^ by accepting provisions^&#42;2^ in order to minister to you.

[NOTE]
====
. Lit., “robbed.”
. Or “support.”
====

[[v47-11-9]]

^<<v47-11-9,9>>^ Yet, when I was present with you and I fell into need, I did not become a burden on anyone, for the brothers who came from Mac·e·doʹni·a abundantly supplied my needs. Yes, in every way I kept myself from becoming a burden to you and will continue to do so.

[[v47-11-10]]

^<<v47-11-10,10>>^ As surely as the truth of Christ is in me, I will not stop this boasting in the regions of A·chaʹia.

[[v47-11-11]]

^<<v47-11-11,11>>^ For what reason? Because I do not love you? God knows I do.

[[v47-11-12]]

^<<v47-11-12,12>>^ But what I am doing I will continue to do, in order to eliminate the pretext of those who are wanting a basis^&#42;1^ for being found equal to us in the things^&#42;2^ about which they boast.

[NOTE]
====
. Or “pretext.”
. Or “the office.”
====

[[v47-11-13]]

^<<v47-11-13,13>>^ For such men are false apostles, deceitful workers, disguising themselves as apostles of Christ.

[[v47-11-14]]

^<<v47-11-14,14>>^ And no wonder, for Satan himself keeps disguising himself as an angel of light.

[[v47-11-15]]

^<<v47-11-15,15>>^ It is therefore nothing extraordinary if his ministers also keep disguising themselves as ministers of righteousness. But their end will be according to their works.

[[v47-11-16]]

^<<v47-11-16,16>>^ I say again: Let no one think I am unreasonable. But even if you do, then accept me as an unreasonable person, so that I too may boast a little.

[[v47-11-17]]

^<<v47-11-17,17>>^ What I now say is, not as following the Lord’s example, but as an unreasonable person would, with boastful self-confidence.

[[v47-11-18]]

^<<v47-11-18,18>>^ Since many are boasting according to the flesh,^&#42;1^ I too will boast.

[NOTE]
====
. That is, on human grounds.
====

[[v47-11-19]]

^<<v47-11-19,19>>^ Since you are so “reasonable,” you gladly put up with the unreasonable ones.

[[v47-11-20]]

^<<v47-11-20,20>>^ In fact, you put up with whoever enslaves you, whoever devours your possessions, whoever grabs what you have, whoever exalts himself over you, and whoever strikes you in the face.

[[v47-11-21]]

^<<v47-11-21,21>>^ I say this to our dishonor, since it may seem that we have acted in weakness.
But if others act boldly—I am talking unreasonably—I too act boldly.

[[v47-11-22]]

^<<v47-11-22,22>>^ Are they Hebrews? I am one also. Are they Israelites? I am one also. Are they Abraham’s offspring?^&#42;1^ I am also.

[NOTE]
====
. Lit., “seed.”
====

[[v47-11-23]]

^<<v47-11-23,23>>^ Are they ministers of Christ? I reply like a madman, I am more outstandingly one: I have done more work, been imprisoned more often, suffered countless beatings, and experienced many near-deaths.

[[v47-11-24]]

^<<v47-11-24,24>>^ Five times I received 40 strokes less one from the Jews,

[[v47-11-25]]

^<<v47-11-25,25>>^ three times I was beaten with rods, once I was stoned, three times I experienced shipwreck, a night and a day I have spent in the open sea;

[[v47-11-26]]

^<<v47-11-26,26>>^ in journeys often, in dangers from rivers, in dangers from robbers, in dangers from my own people, in dangers from the nations, in dangers in the city, in dangers in the wilderness, in dangers at sea, in dangers among false brothers,

[[v47-11-27]]

^<<v47-11-27,27>>^ in labor and toil, in sleepless nights often, in hunger and thirst, frequently without food, in cold and lacking clothing.^&#42;1^

[NOTE]
====
. Lit., “and in nakedness.”
====

[[v47-11-28]]

^<<v47-11-28,28>>^ Besides those things of an external kind, there is what rushes in on me from day to day:^&#42;1^ the anxiety for all the congregations.

[NOTE]
====
. Or “the daily pressure on me.”
====

[[v47-11-29]]

^<<v47-11-29,29>>^ Who is weak, and I am not weak? Who is stumbled, and I am not incensed?

[[v47-11-30]]

^<<v47-11-30,30>>^ If I must boast, I will boast of the things that show my weakness.

[[v47-11-31]]

^<<v47-11-31,31>>^ The God and Father of the Lord Jesus, the One who is to be praised forever, knows I am not lying.

[[v47-11-32]]

^<<v47-11-32,32>>^ In Damascus the governor under A·reʹtas the king was guarding the city of the Dam·a·scenesʹ to seize me,

[[v47-11-33]]

^<<v47-11-33,33>>^ but I was lowered in a basket^&#42;1^ through a window in the city wall, and I escaped his hands.

[NOTE]
====
. Or “wicker basket.”
====

'''

xref:047-2-corinthians/047-2-corinthians-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-012.adoc#v47-12-0[Próximo Capítulo &#62;]