include::./index.adoc[]

[[v66-11-0]]
=== A Revelation to John, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-11-1]]

^<<v66-11-1,1>>^ And a reed like a rod^&#42;1^ was given to me as he said: “Get up and measure the temple sanctuary of God and the altar and those worshipping in it.

[NOTE]
====
. Or “a measuring rod.”
====

[[v66-11-2]]

^<<v66-11-2,2>>^ But as for the courtyard that is outside the temple sanctuary, leave it out and do not measure it, because it has been given to the nations, and they will trample the holy city underfoot for 42 months.

[[v66-11-3]]

^<<v66-11-3,3>>^ I will cause my two witnesses to prophesy for 1,260 days dressed in sackcloth.”

[[v66-11-4]]

^<<v66-11-4,4>>^ These are symbolized by the two olive trees and the two lampstands and are standing before the Lord of the earth.

[[v66-11-5]]

^<<v66-11-5,5>>^ If anyone wants to harm them, fire comes out of their mouths and consumes their enemies. If anyone should want to harm them, this is how he must be killed.

[[v66-11-6]]

^<<v66-11-6,6>>^ These have the authority to shut up the sky^&#42;1^ so that no rain may fall during the days of their prophesying, and they have authority over the waters to turn them into blood and to strike the earth with every sort of plague as often as they wish.

[NOTE]
====
. Or “heaven.”
====

[[v66-11-7]]

^<<v66-11-7,7>>^ When they have finished their witnessing, the wild beast that ascends out of the abyss will wage war with them and conquer them and kill them.

[[v66-11-8]]

^<<v66-11-8,8>>^ And their corpses will be on the main street of the great city that is in a spiritual sense called Sodʹom and Egypt, where their Lord was also executed on the stake.

[[v66-11-9]]

^<<v66-11-9,9>>^ And those of the peoples and tribes and tongues^&#42;1^ and nations will look at their corpses for three and a half days, and they do not allow their corpses to be laid in a tomb.

[NOTE]
====
. Or “languages.”
====

[[v66-11-10]]

^<<v66-11-10,10>>^ And those dwelling on the earth rejoice over them and celebrate, and they will send gifts to one another, because these two prophets tormented those dwelling on the earth.

[[v66-11-11]]

^<<v66-11-11,11>>^ After the three and a half days, spirit of life from God entered into them, and they stood on their feet, and great fear fell upon those who saw them.

[[v66-11-12]]

^<<v66-11-12,12>>^ And they heard a loud voice from heaven say to them: “Come up here.” And they went up into heaven in the cloud, and their enemies saw them.^&#42;1^

[NOTE]
====
. Or “were looking on.”
====

[[v66-11-13]]

^<<v66-11-13,13>>^ In that hour there was a great earthquake, and a tenth of the city fell; and 7,000 persons were killed by the earthquake, and the rest became frightened and gave glory to the God of heaven.

[[v66-11-14]]

^<<v66-11-14,14>>^ The second woe is past. Look! The third woe is coming quickly.

[[v66-11-15]]

^<<v66-11-15,15>>^ The seventh angel blew his trumpet. And there were loud voices in heaven, saying: “The kingdom of the world has become the Kingdom of our Lord and of his Christ, and he will rule as king forever and ever.”

[[v66-11-16]]

^<<v66-11-16,16>>^ And the 24 elders who were seated before God on their thrones fell upon their faces and worshipped God,

[[v66-11-17]]

^<<v66-11-17,17>>^ saying: “We thank you, Jehovah^&#42;1^ God, the Almighty, the one who is and who was, because you have taken your great power and begun ruling as king.

[NOTE]
====
. See App. A5.
====

[[v66-11-18]]

^<<v66-11-18,18>>^ But the nations became wrathful, and your own wrath came, and the appointed time came for the dead to be judged and to reward your slaves the prophets and the holy ones and those fearing your name, the small and the great, and to bring to ruin those ruining^&#42;1^ the earth.”

[NOTE]
====
. Or “to destroy those who are destroying.”
====

[[v66-11-19]]

^<<v66-11-19,19>>^ And the temple sanctuary of God in heaven was opened, and the ark of his covenant was seen in his temple sanctuary. And there were flashes of lightning and voices and thunders and an earthquake and a great hail.

'''

xref:066-revelation/066-revelation-010.adoc#v66-10-0[&#60; Capítulo Anterior] | <<v66-11-0,Topo>> | xref:066-revelation/066-revelation-012.adoc#v66-12-0[Próximo Capítulo &#62;]