include::./index.adoc[]

[[v66-4-0]]
=== A Revelation to John, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-4-1]]

^<<v66-4-1,1>>^ After this I saw, and look! an opened door in heaven, and the first voice that I heard speaking with me was like a trumpet, saying: “Come up here, and I will show you the things that must take place.”

[[v66-4-2]]

^<<v66-4-2,2>>^ After this I immediately came to be in the power of the spirit, and look! a throne was in its position in heaven, and someone was seated on the throne.

[[v66-4-3]]

^<<v66-4-3,3>>^ And the One seated had the appearance of a jasper stone and a sardius stone,^&#42;1^ and all around the throne was a rainbow like an emerald in appearance.

[NOTE]
====
. Or “a precious red-colored stone.”
====

[[v66-4-4]]

^<<v66-4-4,4>>^ All around the throne were 24 thrones, and on these thrones I saw seated 24 elders dressed in white garments, and on their heads golden crowns.

[[v66-4-5]]

^<<v66-4-5,5>>^ From the throne were coming lightning and voices and thunders; and there were seven lamps of fire burning before the throne, and these mean the seven spirits of God.

[[v66-4-6]]

^<<v66-4-6,6>>^ Before the throne was something resembling a glassy sea, like crystal.
In the midst of the throne^&#42;1^ and around the throne were four living creatures that were full of eyes in front and behind.

[NOTE]
====
. Or “In the middle with the throne.”
====

[[v66-4-7]]

^<<v66-4-7,7>>^ The first living creature was like a lion, and the second living creature was like a young bull, and the third living creature had a face like a man’s, and the fourth living creature was like a flying eagle.

[[v66-4-8]]

^<<v66-4-8,8>>^ As for the four living creatures, each one of them had six wings; they were full of eyes all around and underneath. And continuously, day and night, they say: “Holy, holy, holy is Jehovah^&#42;1^ God, the Almighty, who was and who is and who is coming.”

[NOTE]
====
. See App. A5.
====

[[v66-4-9]]

^<<v66-4-9,9>>^ Whenever the living creatures give glory and honor and thanksgiving to the One seated on the throne, the One who lives forever and ever,

[[v66-4-10]]

^<<v66-4-10,10>>^ the 24 elders fall down before the One seated on the throne and worship the One who lives forever and ever, and they cast their crowns before the throne, saying:

[[v66-4-11]]

^<<v66-4-11,11>>^ “You are worthy, Jehovah^&#42;1^ our God, to receive the glory and the honor and the power, because you created all things, and because of your will they came into existence and were created.”

[NOTE]
====
. See App. A5.
====

'''

xref:066-revelation/066-revelation-003.adoc#v66-3-0[&#60; Capítulo Anterior] | <<v66-4-0,Topo>> | xref:066-revelation/066-revelation-005.adoc#v66-5-0[Próximo Capítulo &#62;]