include::./index.adoc[]

[[v66-22-0]]
=== A Revelation to John, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-22-1]]

^<<v66-22-1,1>>^ And he showed me a river of water of life, clear as crystal, flowing out from the throne of God and of the Lamb

[[v66-22-2]]

^<<v66-22-2,2>>^ down the middle of its main street. On both sides of the river were trees of life producing 12 crops of fruit, yielding their fruit each month. And the leaves of the trees were for the healing of the nations.

[[v66-22-3]]

^<<v66-22-3,3>>^ And there will no longer be any curse. But the throne of God and of the Lamb will be in the city, and his slaves will offer him sacred service;

[[v66-22-4]]

^<<v66-22-4,4>>^ and they will see his face, and his name will be on their foreheads.

[[v66-22-5]]

^<<v66-22-5,5>>^ Also, night will be no more, and they have no need of lamplight or sunlight, for Jehovah^&#42;1^ God will shed light upon them, and they will rule as kings forever and ever.

[NOTE]
====
. See App. A5.
====

[[v66-22-6]]

^<<v66-22-6,6>>^ He said to me: “These words are faithful^&#42;1^ and true; yes, Jehovah,^&#42;2^ the God who inspired the prophets, has sent his angel to show his slaves the things that must shortly take place.

[NOTE]
====
. Or “trustworthy.”
. See App. A5.
====

[[v66-22-7]]

^<<v66-22-7,7>>^ Look! I am coming quickly. Happy is anyone observing the words of the prophecy of this scroll.”

[[v66-22-8]]

^<<v66-22-8,8>>^ Well I, John, was the one hearing and seeing these things. When I heard and saw them, I fell down to worship at the feet of the angel who had been showing me these things.

[[v66-22-9]]

^<<v66-22-9,9>>^ But he tells me: “Be careful! Do not do that! I am only a fellow slave of you and of your brothers the prophets and of those observing the words of this scroll. Worship God.”

[[v66-22-10]]

^<<v66-22-10,10>>^ He also tells me: “Do not seal up the words of the prophecy of this scroll, for the appointed time is near.

[[v66-22-11]]

^<<v66-22-11,11>>^ Let the one who is unrighteous continue in unrighteousness, and let the filthy one continue in his filth; but let the righteous one continue in righteousness, and let the holy one continue in holiness.

[[v66-22-12]]

^<<v66-22-12,12>>^ “‘Look! I am coming quickly, and the reward I give is with me, to repay each one according to his work.

[[v66-22-13]]

^<<v66-22-13,13>>^ I am the Alʹpha and the O·meʹga,^&#42;1^ the first and the last, the beginning and the end.

[NOTE]
====
. Or “the A and the Z.” Alpha and Omega are the first and last letters of the Greek alphabet.
====

[[v66-22-14]]

^<<v66-22-14,14>>^ Happy are those who wash their robes, so that they may have authority to go to the trees of life and that they may gain entrance into the city through its gates.

[[v66-22-15]]

^<<v66-22-15,15>>^ Outside are the dogs^&#42;1^ and those who practice spiritism and those who are sexually immoral^&#42;2^ and the murderers and the idolaters and everyone who loves and practices lying.’

[NOTE]
====
. That is, those whose practices are disgusting in God’s eyes.
. See Glossary, “Sexual immorality.”
====

[[v66-22-16]]

^<<v66-22-16,16>>^ “‘I, Jesus, sent my angel to bear witness to you about these things for the congregations. I am the root and the offspring of David and the bright morning star.’”

[[v66-22-17]]

^<<v66-22-17,17>>^ And the spirit and the bride keep on saying, “Come!” and let anyone hearing say, “Come!” and let anyone thirsting come; let anyone who wishes take life’s water free.

[[v66-22-18]]

^<<v66-22-18,18>>^ “I am bearing witness to everyone who hears the words of the prophecy of this scroll: If anyone makes an addition to these things, God will add to him the plagues that are written in this scroll;

[[v66-22-19]]

^<<v66-22-19,19>>^ and if anyone takes anything away from the words of the scroll of this prophecy, God will take his portion away from the trees of life and out of the holy city, things that are written about in this scroll.

[[v66-22-20]]

^<<v66-22-20,20>>^ “The one who bears witness of these things says, ‘Yes, I am coming quickly.’”
“Amen! Come, Lord Jesus.”

[[v66-22-21]]

^<<v66-22-21,21>>^ May the undeserved kindness of the Lord Jesus be with the holy ones.

'''

xref:066-revelation/066-revelation-021.adoc#v66-21-0[&#60; Capítulo Anterior] | <<v66-22-0,Topo>> | **Próximo Capítulo &#62;**