include::./index.adoc[]

[[v66-2-0]]
=== A Revelation to John, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-2-1]]

^<<v66-2-1,1>>^ “To the angel of the congregation in Ephʹe·sus write: These are the things that he says who holds the seven stars in his right hand and walks among the seven golden lampstands:

[[v66-2-2]]

^<<v66-2-2,2>>^ ‘I know your deeds, and your labor and endurance, and that you cannot tolerate bad men, and that you put to the test those who say they are apostles, but they are not, and you found them to be liars.

[[v66-2-3]]

^<<v66-2-3,3>>^ You are also showing endurance, and you have persevered for the sake of my name and have not grown weary.

[[v66-2-4]]

^<<v66-2-4,4>>^ Nevertheless, I hold this against you, that you have left the love you had at first.

[[v66-2-5]]

^<<v66-2-5,5>>^ “‘Therefore remember from where you have fallen, and repent and do the deeds you did at first. If you do not, I will come to you, and I will remove your lampstand from its place, unless you repent.

[[v66-2-6]]

^<<v66-2-6,6>>^ Still, you do have this in your favor: that you hate the deeds of the sect of Nic·o·laʹus, which I also hate.

[[v66-2-7]]

^<<v66-2-7,7>>^ Let the one who has an ear hear what the spirit says to the congregations: To the one who conquers I will grant to eat of the tree of life, which is in the paradise of God.’

[[v66-2-8]]

^<<v66-2-8,8>>^ “And to the angel of the congregation in Smyrʹna write: These are the things that he says, ‘the First and the Last,’ who became dead and came to life again:

[[v66-2-9]]

^<<v66-2-9,9>>^ ‘I know your tribulation and poverty—but you are rich—and the blasphemy by those who call themselves Jews and really are not, but they are a synagogue of Satan.

[[v66-2-10]]

^<<v66-2-10,10>>^ Do not be afraid of the things you are about to suffer. Look! The Devil will keep on throwing some of you into prison so that you may be fully put to the test, and you will have tribulation for ten days. Prove yourself faithful even to death, and I will give you the crown of life.

[[v66-2-11]]

^<<v66-2-11,11>>^ Let the one who has an ear hear what the spirit says to the congregations: The one who conquers will by no means be harmed by the second death.’

[[v66-2-12]]

^<<v66-2-12,12>>^ “To the angel of the congregation in Perʹga·mum write: These are the things that he says who has the sharp, long, two-edged sword:

[[v66-2-13]]

^<<v66-2-13,13>>^ ‘I know where you are dwelling, that is, where the throne of Satan is; and yet you keep holding fast to my name, and you did not deny your faith in me even in the days of Anʹti·pas, my faithful witness, who was killed by your side, where Satan is dwelling.

[[v66-2-14]]

^<<v66-2-14,14>>^ “‘Nevertheless, I have a few things against you, that you have there those adhering to the teaching of Baʹlaam, who taught Baʹlak to put a stumbling block before the sons of Israel, to eat things sacrificed to idols and to commit sexual immorality.^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v66-2-15]]

^<<v66-2-15,15>>^ In the same way, you also have those adhering to the teaching of the sect of Nic·o·laʹus.

[[v66-2-16]]

^<<v66-2-16,16>>^ So repent. If you do not, I am coming to you quickly, and I will war against them with the long sword of my mouth.

[[v66-2-17]]

^<<v66-2-17,17>>^ “‘Let the one who has an ear hear what the spirit says to the congregations: To the one who conquers I will give some of the hidden manna, and I will give him a white pebble, and written on the pebble is a new name that no one knows except the one receiving it.’

[[v66-2-18]]

^<<v66-2-18,18>>^ “To the angel of the congregation in Thy·a·tiʹra write: These are the things that the Son of God says, the one who has eyes like a fiery flame and whose feet are like fine copper:

[[v66-2-19]]

^<<v66-2-19,19>>^ ‘I know your deeds, and your love and faith and ministry and endurance, and that your deeds of late are more than those you did at first.

[[v66-2-20]]

^<<v66-2-20,20>>^ “‘Nevertheless, I do hold this against you, that you tolerate that woman Jezʹe·bel, who calls herself a prophetess, and she teaches and misleads my slaves to commit sexual immorality^&#42;1^ and to eat things sacrificed to idols.

[NOTE]
====
. See Glossary.
====

[[v66-2-21]]

^<<v66-2-21,21>>^ And I gave her time to repent, but she is not willing to repent of her sexual immorality.^&#42;1^

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
====

[[v66-2-22]]

^<<v66-2-22,22>>^ Look! I am about to throw her into a sickbed, and those committing adultery with her into great tribulation, unless they repent of her deeds.

[[v66-2-23]]

^<<v66-2-23,23>>^ And I will kill her children with deadly plague, so that all the congregations will know that I am the one who searches the innermost thoughts^&#42;1^ and hearts, and I will give to you individually according to your deeds.

[NOTE]
====
. Or “the deepest emotions.” Lit., “kidneys.”
====

[[v66-2-24]]

^<<v66-2-24,24>>^ “‘However, I say to the rest of you who are in Thy·a·tiʹra, all those who do not follow this teaching, those who did not get to know the so-called “deep things of Satan”: I am not putting on you any other burden.

[[v66-2-25]]

^<<v66-2-25,25>>^ Just the same, hold fast to what you have until I come.

[[v66-2-26]]

^<<v66-2-26,26>>^ And to the one who conquers and observes my deeds down to the end, I will give authority over the nations,

[[v66-2-27]]

^<<v66-2-27,27>>^ and he will shepherd the people with an iron rod so that they will be broken to pieces like clay vessels, just as I have received from my Father.

[[v66-2-28]]

^<<v66-2-28,28>>^ And I will give him the morning star.

[[v66-2-29]]

^<<v66-2-29,29>>^ Let the one who has an ear hear what the spirit says to the congregations.’

'''

xref:066-revelation/066-revelation-001.adoc#v66-1-0[&#60; Capítulo Anterior] | <<v66-2-0,Topo>> | xref:066-revelation/066-revelation-003.adoc#v66-3-0[Próximo Capítulo &#62;]