include::./index.adoc[]

[[v66-5-0]]
=== A Revelation to John, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-5-1]]

^<<v66-5-1,1>>^ And I saw in the right hand of the One seated on the throne a scroll written on both sides,^&#42;1^ sealed tight with seven seals.

[NOTE]
====
. Lit., “inside and on the back.”
====

[[v66-5-2]]

^<<v66-5-2,2>>^ And I saw a strong angel proclaiming with a loud voice: “Who is worthy to open the scroll and break its seals?”

[[v66-5-3]]

^<<v66-5-3,3>>^ But no one in heaven or on earth or underneath the earth was able to open the scroll or to look into it.

[[v66-5-4]]

^<<v66-5-4,4>>^ I gave way to a great deal of weeping because no one was found worthy to open the scroll or to look into it.

[[v66-5-5]]

^<<v66-5-5,5>>^ But one of the elders said to me: “Stop weeping. Look! The Lion of the tribe of Judah, the root of David, has conquered so as to open the scroll and its seven seals.”

[[v66-5-6]]

^<<v66-5-6,6>>^ And I saw standing in the midst^&#42;1^ of the throne and of the four living creatures and in the midst of the elders a lamb that seemed to have been slaughtered, having seven horns and seven eyes, and the eyes mean the seven spirits of God that have been sent out into the whole earth.

[NOTE]
====
. Or “at the center.”
====

[[v66-5-7]]

^<<v66-5-7,7>>^ At once he came forward and took it out of the right hand of the One seated on the throne.

[[v66-5-8]]

^<<v66-5-8,8>>^ When he took the scroll, the four living creatures and the 24 elders fell down before the Lamb, and each one had a harp and golden bowls that were full of incense. (The incense means the prayers of the holy ones.)

[[v66-5-9]]

^<<v66-5-9,9>>^ And they sing a new song, saying: “You are worthy to take the scroll and open its seals, for you were slaughtered and with your blood you bought people for God out of every tribe and tongue^&#42;1^ and people and nation,

[NOTE]
====
. Or “language.”
====

[[v66-5-10]]

^<<v66-5-10,10>>^ and you made them to be a kingdom and priests to our God, and they are to rule as kings over the earth.”

[[v66-5-11]]

^<<v66-5-11,11>>^ And I saw, and I heard a voice of many angels around the throne and the living creatures and the elders, and the number of them was myriads of myriads^&#42;1^ and thousands of thousands,

[NOTE]
====
. Or “tens of thousands times tens of thousands.”
====

[[v66-5-12]]

^<<v66-5-12,12>>^ and they were saying with a loud voice: “The Lamb who was slaughtered is worthy to receive the power and riches and wisdom and strength and honor and glory and blessing.”

[[v66-5-13]]

^<<v66-5-13,13>>^ And I heard every creature in heaven and on earth and underneath the earth and on the sea, and all the things in them, saying: “To the One sitting on the throne and to the Lamb be the blessing and the honor and the glory and the might forever and ever.”

[[v66-5-14]]

^<<v66-5-14,14>>^ The four living creatures were saying: “Amen!” and the elders fell down and worshipped.

'''

xref:066-revelation/066-revelation-004.adoc#v66-4-0[&#60; Capítulo Anterior] | <<v66-5-0,Topo>> | xref:066-revelation/066-revelation-006.adoc#v66-6-0[Próximo Capítulo &#62;]