include::./index.adoc[]

[[v66-7-0]]
=== A Revelation to John, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-7-1]]

^<<v66-7-1,1>>^ After this I saw four angels standing on the four corners of the earth, holding tight the four winds of the earth, so that no wind could blow on the earth or on the sea or on any tree.

[[v66-7-2]]

^<<v66-7-2,2>>^ And I saw another angel ascending from the sunrise,^&#42;1^ having a seal of the living God; and he called with a loud voice to the four angels to whom it was granted to harm the earth and the sea,

[NOTE]
====
. Or “east.”
====

[[v66-7-3]]

^<<v66-7-3,3>>^ saying: “Do not harm the earth or the sea or the trees, until after we have sealed the slaves of our God in their foreheads.”

[[v66-7-4]]

^<<v66-7-4,4>>^ And I heard the number of those who were sealed, 144,000, sealed out of every tribe of the sons of Israel:

[[v66-7-5]]

^<<v66-7-5,5>>^ Out of the tribe of Judah 12,000 sealed;
out of the tribe of Reuʹben 12,000;
out of the tribe of Gad 12,000;

[[v66-7-6]]

^<<v66-7-6,6>>^ out of the tribe of Ashʹer 12,000;
out of the tribe of Naphʹta·li 12,000;
out of the tribe of Ma·nasʹseh 12,000;

[[v66-7-7]]

^<<v66-7-7,7>>^ out of the tribe of Simʹe·on 12,000;
out of the tribe of Leʹvi 12,000;
out of the tribe of Isʹsa·char 12,000;

[[v66-7-8]]

^<<v66-7-8,8>>^ out of the tribe of Zebʹu·lun 12,000;
out of the tribe of Joseph 12,000;
out of the tribe of Benjamin 12,000 sealed.

[[v66-7-9]]

^<<v66-7-9,9>>^ After this I saw, and look! a great crowd, which no man was able to number, out of all nations and tribes and peoples and tongues,^&#42;1^ standing before the throne and before the Lamb, dressed in white robes; and there were palm branches in their hands.

[NOTE]
====
. Or “languages.”
====

[[v66-7-10]]

^<<v66-7-10,10>>^ And they keep shouting with a loud voice, saying: “Salvation we owe to our God, who is seated on the throne, and to the Lamb.”

[[v66-7-11]]

^<<v66-7-11,11>>^ All the angels were standing around the throne and the elders and the four living creatures, and they fell facedown before the throne and worshipped God,

[[v66-7-12]]

^<<v66-7-12,12>>^ saying: “Amen! Let the praise and the glory and the wisdom and the thanksgiving and the honor and the power and the strength be to our God forever and ever. Amen.”

[[v66-7-13]]

^<<v66-7-13,13>>^ In response one of the elders said to me: “These who are dressed in the white robes, who are they and where did they come from?”

[[v66-7-14]]

^<<v66-7-14,14>>^ So right away I said to him: “My lord, you are the one who knows.” And he said to me: “These are the ones who come out of the great tribulation, and they have washed their robes and made them white in the blood of the Lamb.

[[v66-7-15]]

^<<v66-7-15,15>>^ That is why they are before the throne of God, and they are rendering him sacred service day and night in his temple; and the One seated on the throne will spread his tent over them.

[[v66-7-16]]

^<<v66-7-16,16>>^ They will hunger no more nor thirst anymore, neither will the sun beat down on them nor any scorching heat,

[[v66-7-17]]

^<<v66-7-17,17>>^ because the Lamb, who is in the midst^&#42;1^ of the throne, will shepherd them and will guide them to springs^&#42;2^ of waters of life. And God will wipe out every tear from their eyes.”

[NOTE]
====
. Or “at the center.”
. Or “fountains.”
====

'''

xref:066-revelation/066-revelation-006.adoc#v66-6-0[&#60; Capítulo Anterior] | <<v66-7-0,Topo>> | xref:066-revelation/066-revelation-008.adoc#v66-8-0[Próximo Capítulo &#62;]