include::./index.adoc[]

[[v66-20-0]]
=== A Revelation to John, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-20-1]]

^<<v66-20-1,1>>^ And I saw an angel coming down out of heaven with the key of the abyss and a great chain in his hand.

[[v66-20-2]]

^<<v66-20-2,2>>^ He seized the dragon, the original serpent, who is the Devil and Satan, and bound him for 1,000 years.

[[v66-20-3]]

^<<v66-20-3,3>>^ And he hurled him into the abyss and shut it and sealed it over him, so that he would not mislead the nations anymore until the 1,000 years were ended. After this he must be released for a little while.

[[v66-20-4]]

^<<v66-20-4,4>>^ And I saw thrones, and those who sat on them were given authority to judge. Yes, I saw the souls^&#42;1^ of those executed^&#42;2^ for the witness they gave about Jesus and for speaking about God, and those who had not worshipped the wild beast or its image and had not received the mark on their forehead and on their hand. And they came to life and ruled as kings with the Christ for 1,000 years.

[NOTE]
====
. See Glossary and Re 6:9 ftn.
. Lit., “executed with the ax.”
====

[[v66-20-5]]

^<<v66-20-5,5>>^ (The rest of the dead did not come to life until the 1,000 years were ended.) This is the first resurrection.

[[v66-20-6]]

^<<v66-20-6,6>>^ Happy and holy is anyone having part in the first resurrection; over these the second death has no authority, but they will be priests of God and of the Christ, and they will rule as kings with him for the 1,000 years.

[[v66-20-7]]

^<<v66-20-7,7>>^ Now as soon as the 1,000 years have ended, Satan will be released from his prison,

[[v66-20-8]]

^<<v66-20-8,8>>^ and he will go out to mislead those nations in the four corners of the earth, Gog and Maʹgog, to gather them together for the war. The number of these is as the sand of the sea.

[[v66-20-9]]

^<<v66-20-9,9>>^ And they advanced over the whole earth and encircled the camp of the holy ones and the beloved city. But fire came down out of heaven and consumed them.

[[v66-20-10]]

^<<v66-20-10,10>>^ And the Devil who was misleading them was hurled into the lake of fire and sulfur, where both the wild beast and the false prophet already were; and they will be tormented^&#42;1^ day and night forever and ever.

[NOTE]
====
. Or “restrained; imprisoned.”
====

[[v66-20-11]]

^<<v66-20-11,11>>^ And I saw a great white throne and the One seated on it. From before him the earth and the heaven fled away, and no place was found for them.

[[v66-20-12]]

^<<v66-20-12,12>>^ And I saw the dead, the great and the small, standing before the throne, and scrolls were opened. But another scroll was opened; it is the scroll of life. The dead were judged out of those things written in the scrolls according to their deeds.

[[v66-20-13]]

^<<v66-20-13,13>>^ And the sea gave up the dead in it, and death and the Grave^&#42;1^ gave up the dead in them, and they were judged individually according to their deeds.

[NOTE]
====
. Or “Hades,” that is, the common grave of mankind. See Glossary.
====

[[v66-20-14]]

^<<v66-20-14,14>>^ And death and the Grave^&#42;1^ were hurled into the lake of fire. This means the second death, the lake of fire.

[NOTE]
====
. Or “Hades,” that is, the common grave of mankind. See Glossary.
====

[[v66-20-15]]

^<<v66-20-15,15>>^ Furthermore, whoever was not found written in the book of life was hurled into the lake of fire.

'''

xref:066-revelation/066-revelation-019.adoc#v66-19-0[&#60; Capítulo Anterior] | <<v66-20-0,Topo>> | xref:066-revelation/066-revelation-021.adoc#v66-21-0[Próximo Capítulo &#62;]