include::./index.adoc[]

[[v66-17-0]]
=== A Revelation to John, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-17-1]]

^<<v66-17-1,1>>^ One of the seven angels who had the seven bowls came and said to me: “Come, I will show you the judgment on the great prostitute who sits on many waters,

[[v66-17-2]]

^<<v66-17-2,2>>^ with whom the kings of the earth committed sexual immorality,^&#42;1^ and earth’s inhabitants were made drunk with the wine of her sexual immorality.”^&#42;2^

[NOTE]
====
. See Glossary.
. Greek, por·neiʹa. See Glossary.
====

[[v66-17-3]]

^<<v66-17-3,3>>^ And he carried me away in the power of the spirit into a wilderness. And I saw a woman sitting on a scarlet-colored wild beast that was full of blasphemous names and that had seven heads and ten horns.

[[v66-17-4]]

^<<v66-17-4,4>>^ The woman was clothed in purple and scarlet, and she was adorned with gold and precious stones and pearls, and she had in her hand a golden cup that was full of disgusting things and the unclean things of her sexual immorality.^&#42;1^

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
====

[[v66-17-5]]

^<<v66-17-5,5>>^ On her forehead was written a name, a mystery: “Babylon the Great, the mother of the prostitutes and of the disgusting things of the earth.”

[[v66-17-6]]

^<<v66-17-6,6>>^ And I saw that the woman was drunk with the blood of the holy ones and with the blood of the witnesses of Jesus.
Well, on seeing her I was greatly amazed.

[[v66-17-7]]

^<<v66-17-7,7>>^ So the angel said to me: “Why is it that you were amazed? I will tell you the mystery of the woman and of the wild beast that is carrying her and that has the seven heads and the ten horns:

[[v66-17-8]]

^<<v66-17-8,8>>^ The wild beast that you saw was, but is not, and yet is about to ascend out of the abyss, and it is to go off into destruction. And the inhabitants of the earth—those whose names have not been written in the scroll of life from the founding of the world—will be amazed when they see how the wild beast was, but is not, and yet will be present.

[[v66-17-9]]

^<<v66-17-9,9>>^ “This calls for a mind^&#42;1^ that has wisdom: The seven heads mean seven mountains, where the woman sits on top.

[NOTE]
====
. Or “for intelligence.”
====

[[v66-17-10]]

^<<v66-17-10,10>>^ And there are seven kings: Five have fallen, one is, and the other has not yet arrived; but when he does arrive, he must remain a short while.

[[v66-17-11]]

^<<v66-17-11,11>>^ And the wild beast that was but is not, it is also an eighth king, but it springs from the seven, and it goes off into destruction.

[[v66-17-12]]

^<<v66-17-12,12>>^ “The ten horns that you saw mean ten kings who have not yet received a kingdom, but they do receive authority as kings for one hour with the wild beast.

[[v66-17-13]]

^<<v66-17-13,13>>^ These have one thought, so they give their power and authority to the wild beast.

[[v66-17-14]]

^<<v66-17-14,14>>^ These will battle with the Lamb, but because he is Lord of lords and King of kings, the Lamb will conquer them. Also, those with him who are called and chosen and faithful will do so.”

[[v66-17-15]]

^<<v66-17-15,15>>^ He said to me: “The waters that you saw, where the prostitute is sitting, mean peoples and crowds and nations and tongues.^&#42;1^

[NOTE]
====
. Or “languages.”
====

[[v66-17-16]]

^<<v66-17-16,16>>^ And the ten horns that you saw and the wild beast, these will hate the prostitute and will make her devastated and naked, and they will eat up her flesh and completely burn her with fire.

[[v66-17-17]]

^<<v66-17-17,17>>^ For God put it into their hearts to carry out his thought, yes, to carry out their one thought by giving their kingdom to the wild beast, until the words of God will have been accomplished.

[[v66-17-18]]

^<<v66-17-18,18>>^ And the woman whom you saw means the great city that has a kingdom over the kings of the earth.”

'''

xref:066-revelation/066-revelation-016.adoc#v66-16-0[&#60; Capítulo Anterior] | <<v66-17-0,Topo>> | xref:066-revelation/066-revelation-018.adoc#v66-18-0[Próximo Capítulo &#62;]