include::./index.adoc[]

[[v66-10-0]]
=== A Revelation to John, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-10-1]]

^<<v66-10-1,1>>^ And I saw another strong angel descending from heaven, arrayed^&#42;1^ with a cloud, and a rainbow was on his head, and his face was like the sun, and his legs^&#42;2^ were like pillars of fire,

[NOTE]
====
. Or “wrapped.”
. Lit., “feet.”
====

[[v66-10-2]]

^<<v66-10-2,2>>^ and he had in his hand a little scroll that had been unrolled. And he set his right foot on the sea, but his left one on the earth,

[[v66-10-3]]

^<<v66-10-3,3>>^ and he cried out with a loud voice just as when a lion roars. And when he cried out, the voices of the seven thunders spoke.

[[v66-10-4]]

^<<v66-10-4,4>>^ Now when the seven thunders spoke, I was about to write, but I heard a voice out of heaven say: “Seal up the things the seven thunders spoke, and do not write them down.”

[[v66-10-5]]

^<<v66-10-5,5>>^ The angel whom I saw standing on the sea and on the earth raised his right hand to heaven,

[[v66-10-6]]

^<<v66-10-6,6>>^ and he swore by the One who lives forever and ever, who created the heaven and the things in it and the earth and the things in it and the sea and the things in it: “There will be no delay any longer.

[[v66-10-7]]

^<<v66-10-7,7>>^ But in the days when the seventh angel is about to blow his trumpet, the sacred secret that God declared as good news to his own slaves the prophets is indeed brought to a finish.”

[[v66-10-8]]

^<<v66-10-8,8>>^ And I heard the voice out of heaven speaking again with me and saying: “Go, take the opened scroll that is in the hand of the angel who is standing on the sea and on the earth.”

[[v66-10-9]]

^<<v66-10-9,9>>^ I went to the angel and told him to give me the little scroll. He said to me: “Take it and eat it up, and it will make your stomach bitter, but in your mouth it will be sweet like honey.”

[[v66-10-10]]

^<<v66-10-10,10>>^ I took the little scroll out of the hand of the angel and ate it, and in my mouth it was sweet like honey, but when I had eaten it, my stomach was made bitter.

[[v66-10-11]]

^<<v66-10-11,11>>^ And they said to me: “You must prophesy again about peoples and nations and tongues^&#42;1^ and many kings.”

[NOTE]
====
. Or “languages.”
====

'''

xref:066-revelation/066-revelation-009.adoc#v66-9-0[&#60; Capítulo Anterior] | <<v66-10-0,Topo>> | xref:066-revelation/066-revelation-011.adoc#v66-11-0[Próximo Capítulo &#62;]