include::./index.adoc[]

[[v66-18-0]]
=== A Revelation to John, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-18-1]]

^<<v66-18-1,1>>^ After this I saw another angel descending from heaven with great authority, and the earth was illuminated by his glory.

[[v66-18-2]]

^<<v66-18-2,2>>^ And he cried out with a strong voice, saying: “She has fallen! Babylon the Great has fallen, and she has become a dwelling place of demons and a place where every unclean spirit^&#42;1^ and every unclean and hated bird lurks!

[NOTE]
====
. Or possibly, “breath; exhalation; inspired statement.”
====

[[v66-18-3]]

^<<v66-18-3,3>>^ For because of the wine of the passion^&#42;1^ of her sexual immorality,^&#42;2^ all the nations have fallen victim, and the kings of the earth committed sexual immorality with her, and the merchants^&#42;3^ of the earth became rich owing to the power of her shameless luxury.”

[NOTE]
====
. Or “anger.”
. Greek, por·neiʹa. See Glossary.
. Or “traveling merchants.”
====

[[v66-18-4]]

^<<v66-18-4,4>>^ And I heard another voice out of heaven say: “Get out of her, my people, if you do not want to share with her in her sins, and if you do not want to receive part of her plagues.

[[v66-18-5]]

^<<v66-18-5,5>>^ For her sins have massed together clear up to heaven, and God has called her acts of injustice^&#42;1^ to mind.

[NOTE]
====
. Or “her crimes.”
====

[[v66-18-6]]

^<<v66-18-6,6>>^ Repay her in the way she treated others, yes, pay her back double for the things she has done; in the cup she has mixed, mix a double portion for her.

[[v66-18-7]]

^<<v66-18-7,7>>^ To the extent that she glorified herself and lived in shameless luxury, to that extent give her torment and mourning. For she keeps saying in her heart: ‘I sit as queen, and I am not a widow, and I will never see mourning.’

[[v66-18-8]]

^<<v66-18-8,8>>^ That is why in one day her plagues will come, death and mourning and famine, and she will be completely burned with fire, because Jehovah^&#42;1^ God, who judged her, is strong.

[NOTE]
====
. See App. A5.
====

[[v66-18-9]]

^<<v66-18-9,9>>^ “And the kings of the earth who committed sexual immorality^&#42;1^ with her and lived with her in shameless luxury will weep and beat themselves in grief over her when they see the smoke from her burning.

[NOTE]
====
. See Glossary.
====

[[v66-18-10]]

^<<v66-18-10,10>>^ They will stand at a distance because of their fear of her torment and say: ‘Too bad, too bad, you great city, Babylon you strong city, because in one hour your judgment has arrived!’

[[v66-18-11]]

^<<v66-18-11,11>>^ “Also, the merchants of the earth are weeping and mourning over her, because there is no one to buy their full cargo anymore,

[[v66-18-12]]

^<<v66-18-12,12>>^ a full cargo of gold, silver, precious stones, pearls, fine linen, purple cloth, silk, and scarlet cloth; and everything made from scented wood; and every sort of object made from ivory, and from precious wood, copper, iron, and marble;

[[v66-18-13]]

^<<v66-18-13,13>>^ also cinnamon, Indian spice, incense, perfumed oil, frankincense, wine, olive oil, fine flour, wheat, cattle, sheep, horses, carriages, slaves, and human lives.^&#42;1^

[NOTE]
====
. Or “souls.”
====

[[v66-18-14]]

^<<v66-18-14,14>>^ Yes, the fine fruit that you^&#42;1^ desired has left you, and all the delicacies and the splendid things have vanished from you, never to be found again.

[NOTE]
====
. Or “your soul.”
====

[[v66-18-15]]

^<<v66-18-15,15>>^ “The merchants who sold these things, who became rich from her, will stand at a distance because of their fear of her torment and will weep and mourn,

[[v66-18-16]]

^<<v66-18-16,16>>^ saying: ‘Too bad, too bad, the great city, clothed with fine linen, purple, and scarlet and richly adorned with gold ornaments, precious stones, and pearls,

[[v66-18-17]]

^<<v66-18-17,17>>^ because in one hour such great riches have been devastated!’
“And every ship captain and every seafaring person and sailors and all those who make a living by the sea stood at a distance

[[v66-18-18]]

^<<v66-18-18,18>>^ and cried out as they looked at the smoke from her burning and said: ‘What city is like the great city?’

[[v66-18-19]]

^<<v66-18-19,19>>^ They threw dust on their heads and cried out, weeping and mourning, and said: ‘Too bad, too bad, the great city, in which all those who had ships at sea became rich from her wealth, because in one hour she has been devastated!’

[[v66-18-20]]

^<<v66-18-20,20>>^ “Be glad over her, O heaven, also you holy ones and apostles and prophets, because God has pronounced his judgment on her in your behalf!”

[[v66-18-21]]

^<<v66-18-21,21>>^ And a strong angel lifted up a stone like a great millstone and hurled it into the sea, saying: “Thus with a swift pitch will Babylon the great city be hurled down, and she will never be found again.

[[v66-18-22]]

^<<v66-18-22,22>>^ And the sound of singers who accompany themselves on the harp, of musicians, of flutists, and of trumpeters will never be heard in you again. And no craftsman who practices any trade will ever be found in you again, and no sound of a millstone will ever be heard in you again.

[[v66-18-23]]

^<<v66-18-23,23>>^ No light of a lamp will ever shine in you again, and no voice of a bridegroom and of a bride will ever be heard in you again; for your merchants were the top-ranking men of the earth, and by your spiritistic practices all the nations were misled.

[[v66-18-24]]

^<<v66-18-24,24>>^ Yes, in her was found the blood of prophets and of holy ones and of all those who have been slaughtered on the earth.”

'''

xref:066-revelation/066-revelation-017.adoc#v66-17-0[&#60; Capítulo Anterior] | <<v66-18-0,Topo>> | xref:066-revelation/066-revelation-019.adoc#v66-19-0[Próximo Capítulo &#62;]