include::./index.adoc[]

[[v66-14-0]]
=== A Revelation to John, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-14-1]]

^<<v66-14-1,1>>^ Then I saw, and look! the Lamb standing on Mount Zion, and with him 144,000 who have his name and the name of his Father written on their foreheads.

[[v66-14-2]]

^<<v66-14-2,2>>^ I heard a sound coming out of heaven like the sound of many waters and like the sound of loud thunder; and the sound that I heard was like singers who accompany themselves by playing on their harps.

[[v66-14-3]]

^<<v66-14-3,3>>^ And they are singing what seems to be a new song before the throne and before the four living creatures and the elders, and no one was able to master that song except the 144,000, who have been bought from the earth.

[[v66-14-4]]

^<<v66-14-4,4>>^ These are the ones who did not defile themselves with women; in fact, they are virgins. These are the ones who keep following the Lamb no matter where he goes. These were bought from among mankind as firstfruits to God and to the Lamb,

[[v66-14-5]]

^<<v66-14-5,5>>^ and no deceit was found in their mouths; they are without blemish.

[[v66-14-6]]

^<<v66-14-6,6>>^ And I saw another angel flying in midheaven,^&#42;1^ and he had everlasting good news to declare to those who dwell on the earth, to every nation and tribe and tongue^&#42;2^ and people.

[NOTE]
====
. Or “in midair; overhead.”
. Or “language.”
====

[[v66-14-7]]

^<<v66-14-7,7>>^ He was saying in a loud voice: “Fear God and give him glory, because the hour of judgment by him has arrived, so worship the One who made the heaven and the earth and the sea and the springs^&#42;1^ of water.”

[NOTE]
====
. Or “fountains.”
====

[[v66-14-8]]

^<<v66-14-8,8>>^ Another, a second angel, followed, saying: “She has fallen! Babylon the Great has fallen, she who made all the nations drink of the wine of the passion^&#42;1^ of her sexual immorality!”^&#42;2^

[NOTE]
====
. Or “anger.”
. Greek, por·neiʹa. See Glossary.
====

[[v66-14-9]]

^<<v66-14-9,9>>^ Another angel, a third, followed them, saying in a loud voice: “If anyone worships the wild beast and its image and receives a mark on his forehead or on his hand,

[[v66-14-10]]

^<<v66-14-10,10>>^ he will also drink of the wine of the anger of God that is poured out undiluted into the cup of His wrath, and he will be tormented with fire and sulfur in the sight of the holy angels and in the sight of the Lamb.

[[v66-14-11]]

^<<v66-14-11,11>>^ And the smoke of their torment ascends forever and ever, and day and night they have no rest, those who worship the wild beast and its image and whoever receives the mark of its name.

[[v66-14-12]]

^<<v66-14-12,12>>^ Here is where it calls for endurance on the part of the holy ones, those who keep the commandments of God and hold fast to the faith of Jesus.”

[[v66-14-13]]

^<<v66-14-13,13>>^ And I heard a voice out of heaven say, “Write: Happy are the dead who die in union with the Lord from this time onward. Yes, says the spirit, let them rest from their labors, for the things they did go right^&#42;1^ with them.”

[NOTE]
====
. Or “along.”
====

[[v66-14-14]]

^<<v66-14-14,14>>^ Then I saw, and look! a white cloud, and seated on the cloud was someone like a son of man, with a golden crown on his head and a sharp sickle in his hand.

[[v66-14-15]]

^<<v66-14-15,15>>^ Another angel emerged from the temple sanctuary, calling with a loud voice to the one seated on the cloud: “Put your sickle in and reap, because the hour has come to reap, for the harvest of the earth is fully ripe.”

[[v66-14-16]]

^<<v66-14-16,16>>^ And the one seated on the cloud thrust his sickle into the earth, and the earth was reaped.

[[v66-14-17]]

^<<v66-14-17,17>>^ And still another angel emerged from the temple sanctuary that is in heaven, and he also had a sharp sickle.

[[v66-14-18]]

^<<v66-14-18,18>>^ And still another angel emerged from the altar, and he had authority over the fire. And he called out with a loud voice to the one who had the sharp sickle, saying: “Put your sharp sickle in and gather the clusters of the vine of the earth, for its grapes have become ripe.”

[[v66-14-19]]

^<<v66-14-19,19>>^ The angel thrust his sickle into the earth and gathered the vine of the earth, and he hurled it into the great winepress of God’s anger.

[[v66-14-20]]

^<<v66-14-20,20>>^ The winepress was trodden outside the city, and blood came out of the winepress as high up as the bridles of the horses for a distance of 1,600 stadia.^&#42;1^

[NOTE]
====
. About 296 km (184 mi). A stadium equaled 185 m (606.95 ft). See App. B14.
====

'''

xref:066-revelation/066-revelation-013.adoc#v66-13-0[&#60; Capítulo Anterior] | <<v66-14-0,Topo>> | xref:066-revelation/066-revelation-015.adoc#v66-15-0[Próximo Capítulo &#62;]