include::./index.adoc[]

[[v66-9-0]]
=== A Revelation to John, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-9-1]]

^<<v66-9-1,1>>^ The fifth angel blew his trumpet. And I saw a star that had fallen from heaven to the earth, and the key to the shaft^&#42;1^ of the abyss was given to him.

[NOTE]
====
. Or “pit.”
====

[[v66-9-2]]

^<<v66-9-2,2>>^ He opened the shaft^&#42;1^ of the abyss, and smoke ascended out of the shaft^&#42;2^ like the smoke of a great furnace, and the sun was darkened, also the air, by the smoke of the shaft.^&#42;3^

[NOTE]
====
. Or “pit.”
. Or “pit.”
. Or “pit.”
====

[[v66-9-3]]

^<<v66-9-3,3>>^ And locusts came out of the smoke onto the earth, and authority was given to them, the same authority that the scorpions of the earth have.

[[v66-9-4]]

^<<v66-9-4,4>>^ They were told not to harm the vegetation of the earth or any green plant or any tree, but only those people who do not have the seal of God on their foreheads.

[[v66-9-5]]

^<<v66-9-5,5>>^ And it was granted the locusts, not to kill them, but to torment them five months, and their torment was like torment by a scorpion when it strikes a person.

[[v66-9-6]]

^<<v66-9-6,6>>^ In those days people will seek death but will by no means find it, and they will long to die, but death will flee from them.

[[v66-9-7]]

^<<v66-9-7,7>>^ And in appearance the locusts resembled horses prepared for battle; on their heads were what seemed to be crowns of gold, and their faces were like human faces,

[[v66-9-8]]

^<<v66-9-8,8>>^ but they had hair like women’s hair. And their teeth were like those of lions,

[[v66-9-9]]

^<<v66-9-9,9>>^ and they had breastplates like iron breastplates. And the sound of their wings was like the sound of horse-drawn chariots rushing into battle.

[[v66-9-10]]

^<<v66-9-10,10>>^ Also, they have tails with stingers like scorpions, and in their tails is their authority to hurt the people for five months.

[[v66-9-11]]

^<<v66-9-11,11>>^ They have over them a king, the angel of the abyss. In Hebrew his name is A·badʹdon,^&#42;1^ but in Greek he has the name A·polʹlyon.^&#42;2^

[NOTE]
====
. Meaning “Destruction.”
. Meaning “Destroyer.”
====

[[v66-9-12]]

^<<v66-9-12,12>>^ The one woe is past. Look! Two more woes are coming after these things.

[[v66-9-13]]

^<<v66-9-13,13>>^ The sixth angel blew his trumpet. And I heard one voice from the horns of the golden altar that is before God

[[v66-9-14]]

^<<v66-9-14,14>>^ say to the sixth angel who had the trumpet: “Untie the four angels who are bound at the great river Eu·phraʹtes.”

[[v66-9-15]]

^<<v66-9-15,15>>^ And the four angels who have been prepared for the hour and day and month and year were untied to kill a third of the people.

[[v66-9-16]]

^<<v66-9-16,16>>^ The number of the armies of cavalry was two myriads of myriads;^&#42;1^ I heard the number of them.

[NOTE]
====
. Or “20,000 times 10,000,” that is, 200,000,000.
====

[[v66-9-17]]

^<<v66-9-17,17>>^ And this is how I saw the horses in the vision and those seated on them: They had fire-red and hyacinth-blue and sulfur-yellow breastplates, and the heads of the horses were like the heads of lions, and fire and smoke and sulfur came out of their mouths.

[[v66-9-18]]

^<<v66-9-18,18>>^ A third of the people were killed by these three plagues, by the fire and the smoke and the sulfur that came out of their mouths.

[[v66-9-19]]

^<<v66-9-19,19>>^ For the authority of the horses is in their mouths and in their tails, for their tails are like serpents and have heads, and with these they inflict harm.

[[v66-9-20]]

^<<v66-9-20,20>>^ But the rest of the people who were not killed by these plagues did not repent of the works of their hands; they did not stop worshipping the demons and the idols of gold and silver and copper and stone and wood, which can neither see nor hear nor walk.

[[v66-9-21]]

^<<v66-9-21,21>>^ And they did not repent of their murders nor of their spiritistic practices nor of their sexual immorality^&#42;1^ nor of their thefts.

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
====

'''

xref:066-revelation/066-revelation-008.adoc#v66-8-0[&#60; Capítulo Anterior] | <<v66-9-0,Topo>> | xref:066-revelation/066-revelation-010.adoc#v66-10-0[Próximo Capítulo &#62;]