include::./index.adoc[]

[[v66-13-0]]
=== A Revelation to John, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-13-1]]

^<<v66-13-1,1>>^ And it^&#42;1^ stood still on the sand of the sea.
And I saw a wild beast ascending out of the sea, with ten horns and seven heads, and on its horns ten diadems,^&#42;2^ but on its heads blasphemous names.

[NOTE]
====
. That is, the dragon.
. Or “royal headbands.”
====

[[v66-13-2]]

^<<v66-13-2,2>>^ Now the wild beast that I saw was like a leopard, but its feet were like those of a bear, and its mouth was like a lion’s mouth. And the dragon gave to the beast its power and its throne and great authority.

[[v66-13-3]]

^<<v66-13-3,3>>^ I saw that one of its heads seemed to have been fatally wounded, but its mortal wound had been healed, and all the earth followed the wild beast with admiration.

[[v66-13-4]]

^<<v66-13-4,4>>^ And they worshipped the dragon because it gave the authority to the wild beast, and they worshipped the wild beast with the words: “Who is like the wild beast, and who can do battle with it?”

[[v66-13-5]]

^<<v66-13-5,5>>^ It was given a mouth speaking great things and blasphemies, and it was given authority to act for 42 months.

[[v66-13-6]]

^<<v66-13-6,6>>^ And it opened its mouth in blasphemies against God to blaspheme his name and his dwelling place, even those residing in heaven.

[[v66-13-7]]

^<<v66-13-7,7>>^ It was permitted to wage war with the holy ones and conquer them, and it was given authority over every tribe and people and tongue^&#42;1^ and nation.

[NOTE]
====
. Or “language.”
====

[[v66-13-8]]

^<<v66-13-8,8>>^ And all those who dwell on the earth will worship it. From the founding of the world, not one of their names has been written in the scroll of life of the Lamb who was slaughtered.

[[v66-13-9]]

^<<v66-13-9,9>>^ If anyone has an ear, let him hear.

[[v66-13-10]]

^<<v66-13-10,10>>^ If anyone is meant for captivity, he will go into captivity. If anyone will kill with the sword,^&#42;1^ he must be killed with the sword. This is where it calls for endurance and faith on the part of the holy ones.

[NOTE]
====
. Or possibly, “If anyone is to be killed with the sword.”
====

[[v66-13-11]]

^<<v66-13-11,11>>^ Then I saw another wild beast ascending out of the earth, and it had two horns like a lamb, but it began speaking like a dragon.

[[v66-13-12]]

^<<v66-13-12,12>>^ It exercises all the authority of the first wild beast in its sight. And it makes the earth and its inhabitants worship the first wild beast, whose mortal wound was healed.

[[v66-13-13]]

^<<v66-13-13,13>>^ And it performs great signs, even making fire come down out of heaven to the earth in the sight of mankind.

[[v66-13-14]]

^<<v66-13-14,14>>^ It misleads those who dwell on the earth, because of the signs that it was permitted to perform in the sight of the wild beast, while it tells those who dwell on the earth to make an image to the wild beast that had the sword-stroke and yet revived.

[[v66-13-15]]

^<<v66-13-15,15>>^ And it was permitted to give breath^&#42;1^ to the image of the wild beast, so that the image of the wild beast should both speak and cause to be killed all those who refuse to worship the image of the wild beast.

[NOTE]
====
. Or “spirit.”
====

[[v66-13-16]]

^<<v66-13-16,16>>^ It puts under compulsion all people—the small and the great, the rich and the poor, the free and the slaves—that these should be marked on their right hand or on their forehead,

[[v66-13-17]]

^<<v66-13-17,17>>^ and that nobody can buy or sell except a person having the mark, the name of the wild beast or the number of its name.

[[v66-13-18]]

^<<v66-13-18,18>>^ This is where it calls for wisdom: Let the one who has insight calculate the number of the wild beast, for it is a man’s number,^&#42;1^ and its number is 666.

[NOTE]
====
. Or “a human number.”
====

'''

xref:066-revelation/066-revelation-012.adoc#v66-12-0[&#60; Capítulo Anterior] | <<v66-13-0,Topo>> | xref:066-revelation/066-revelation-014.adoc#v66-14-0[Próximo Capítulo &#62;]