include::./index.adoc[]

[[v66-16-0]]
=== A Revelation to John, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-16-1]]

^<<v66-16-1,1>>^ And I heard a loud voice out of the sanctuary say to the seven angels: “Go and pour out the seven bowls of the anger of God on the earth.”

[[v66-16-2]]

^<<v66-16-2,2>>^ The first one went off and poured out his bowl on the earth. And a hurtful and malignant ulcer afflicted the people who had the mark of the wild beast and who were worshipping its image.

[[v66-16-3]]

^<<v66-16-3,3>>^ The second one poured out his bowl into the sea. And it became blood like that of a dead man, and every living creature^&#42;1^ died, yes, the things in the sea.

[NOTE]
====
. Or “soul.”
====

[[v66-16-4]]

^<<v66-16-4,4>>^ The third one poured out his bowl into the rivers and the springs^&#42;1^ of water. And they became blood.

[NOTE]
====
. Or “fountains.”
====

[[v66-16-5]]

^<<v66-16-5,5>>^ I heard the angel over the waters say: “You, the One who is and who was, the loyal One, are righteous, for you have issued these judgments,

[[v66-16-6]]

^<<v66-16-6,6>>^ because they poured out the blood of holy ones and of prophets, and you have given them blood to drink; they deserve it.”

[[v66-16-7]]

^<<v66-16-7,7>>^ And I heard the altar say: “Yes, Jehovah^&#42;1^ God, the Almighty, true and righteous are your judgments.”^&#42;2^

[NOTE]
====
. See App. A5.
. Or “judicial decisions.”
====

[[v66-16-8]]

^<<v66-16-8,8>>^ The fourth one poured out his bowl on the sun, and to the sun it was granted to scorch the people with fire.

[[v66-16-9]]

^<<v66-16-9,9>>^ And the people were scorched by the great heat, but they blasphemed the name of God, who has the authority over these plagues, and they did not repent and give glory to him.

[[v66-16-10]]

^<<v66-16-10,10>>^ The fifth one poured out his bowl on the throne of the wild beast. And its kingdom became darkened, and they began to gnaw their tongues because of their pain,

[[v66-16-11]]

^<<v66-16-11,11>>^ but they blasphemed the God of heaven because of their pains and their ulcers, and they did not repent of their works.

[[v66-16-12]]

^<<v66-16-12,12>>^ The sixth one poured out his bowl on the great river Eu·phraʹtes, and its water was dried up to prepare the way for the kings from the rising of the sun.^&#42;1^

[NOTE]
====
. Or “from the east.”
====

[[v66-16-13]]

^<<v66-16-13,13>>^ And I saw three unclean inspired expressions^&#42;1^ that looked like frogs come out of the mouth of the dragon and out of the mouth of the wild beast and out of the mouth of the false prophet.

[NOTE]
====
. Lit., “unclean spirits.”
====

[[v66-16-14]]

^<<v66-16-14,14>>^ They are, in fact, expressions inspired by demons and they perform signs, and they go out to the kings of the entire inhabited earth, to gather them together to the war of the great day of God the Almighty.

[[v66-16-15]]

^<<v66-16-15,15>>^ “Look! I am coming as a thief. Happy is the one who stays awake and keeps his outer garments, so that he may not walk naked and people look upon his shamefulness.”

[[v66-16-16]]

^<<v66-16-16,16>>^ And they gathered them together to the place that is called in Hebrew Armageddon.^&#42;1^

[NOTE]
====
. Greek, Har Ma·ge·donʹ, from a Hebrew term meaning “Mountain of Megiddo.”
====

[[v66-16-17]]

^<<v66-16-17,17>>^ The seventh one poured out his bowl on the air. At this a loud voice came out of the sanctuary from the throne, saying: “It has come to pass!”

[[v66-16-18]]

^<<v66-16-18,18>>^ And there were flashes of lightning and voices and thunders, and there was a great earthquake unlike any that had occurred since men came to be on the earth, so extensive and so great was the earthquake.

[[v66-16-19]]

^<<v66-16-19,19>>^ The great city split into three parts, and the cities of the nations fell; and Babylon the Great was remembered before God, to give her the cup of the wine of the fury of his wrath.

[[v66-16-20]]

^<<v66-16-20,20>>^ Also, every island fled, and mountains were not found.

[[v66-16-21]]

^<<v66-16-21,21>>^ Then great hailstones, each about the weight of a talent,^&#42;1^ fell from heaven on the people, and the people blasphemed God because of the plague of hail, for the plague was unusually great.

[NOTE]
====
. A Greek talent equaled 20.4 kg (654 oz t). See App. B14.
====

'''

xref:066-revelation/066-revelation-015.adoc#v66-15-0[&#60; Capítulo Anterior] | <<v66-16-0,Topo>> | xref:066-revelation/066-revelation-017.adoc#v66-17-0[Próximo Capítulo &#62;]