include::./index.adoc[]

[[v66-19-0]]
=== A Revelation to John, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-19-1]]

^<<v66-19-1,1>>^ After this I heard what seemed to be a loud voice of a great crowd in heaven. They said: “Praise Jah!^&#42;1^ The salvation and the glory and the power belong to our God,

[NOTE]
====
. Or “Hallelujah!” “Jah” is a shortened form of the name Jehovah.
====

[[v66-19-2]]

^<<v66-19-2,2>>^ because his judgments are true and righteous. For he has executed judgment on the great prostitute who corrupted the earth with her sexual immorality,^&#42;1^ and he has avenged the blood of his slaves that is on her hands.”^&#42;2^

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
. Lit., “from her hand.”
====

[[v66-19-3]]

^<<v66-19-3,3>>^ And right away for the second time they said: “Praise Jah!^&#42;1^ And the smoke from her goes on ascending forever and ever.”

[NOTE]
====
. Or “Hallelujah!” “Jah” is a shortened form of the name Jehovah.
====

[[v66-19-4]]

^<<v66-19-4,4>>^ And the 24 elders and the four living creatures fell down and worshipped God who sits on the throne and said: “Amen! Praise Jah!”^&#42;1^

[NOTE]
====
. Or “Hallelujah!” “Jah” is a shortened form of the name Jehovah.
====

[[v66-19-5]]

^<<v66-19-5,5>>^ Also, a voice came from the throne and said: “Be praising our God, all you his slaves, who fear him, the small ones and the great.”

[[v66-19-6]]

^<<v66-19-6,6>>^ And I heard what sounded like a voice of a great crowd and like the sound of many waters and like the sound of heavy thunders. They said: “Praise Jah,^&#42;1^ because Jehovah^&#42;2^ our God, the Almighty, has begun to rule as king!

[NOTE]
====
. Or “Hallelujah!” “Jah” is a shortened form of the name Jehovah.
. See App. A5.
====

[[v66-19-7]]

^<<v66-19-7,7>>^ Let us rejoice and be overjoyed and give him glory, because the marriage of the Lamb has arrived and his wife has prepared herself.

[[v66-19-8]]

^<<v66-19-8,8>>^ Yes, it has been granted to her to be clothed with bright, clean, fine linen—for the fine linen stands for the righteous acts of the holy ones.”

[[v66-19-9]]

^<<v66-19-9,9>>^ And he tells me, “Write: Happy are those invited to the evening meal of the Lamb’s marriage.” Also, he tells me: “These are the true sayings of God.”

[[v66-19-10]]

^<<v66-19-10,10>>^ At that I fell down before his feet to worship him. But he tells me: “Be careful! Do not do that! I am only a fellow slave of you and of your brothers who have the work of witnessing concerning Jesus. Worship God! For the witness concerning Jesus is what inspires prophecy.”

[[v66-19-11]]

^<<v66-19-11,11>>^ I saw heaven opened, and look! a white horse. And the one seated on it is called Faithful and True, and he judges and carries on war in righteousness.

[[v66-19-12]]

^<<v66-19-12,12>>^ His eyes are a fiery flame, and on his head are many diadems.^&#42;1^ He has a name written that no one knows but he himself,

[NOTE]
====
. Or “royal headbands.”
====

[[v66-19-13]]

^<<v66-19-13,13>>^ and he is clothed with an outer garment stained^&#42;1^ with blood, and he is called by the name The Word of God.

[NOTE]
====
. Or possibly, “sprinkled.”
====

[[v66-19-14]]

^<<v66-19-14,14>>^ Also, the armies in heaven were following him on white horses, and they were clothed in white, clean, fine linen.

[[v66-19-15]]

^<<v66-19-15,15>>^ And out of his mouth protrudes a sharp, long sword with which to strike the nations, and he will shepherd them with a rod of iron. Moreover, he treads the winepress of the fury of the wrath of God the Almighty.

[[v66-19-16]]

^<<v66-19-16,16>>^ On his outer garment, yes, on his thigh, he has a name written, King of kings and Lord of lords.

[[v66-19-17]]

^<<v66-19-17,17>>^ I saw also an angel standing in the sun, and he cried out with a loud voice and said to all the birds that fly in midheaven:^&#42;1^ “Come here, be gathered together to the great evening meal of God,

[NOTE]
====
. Or “in midair; overhead.”
====

[[v66-19-18]]

^<<v66-19-18,18>>^ so that you may eat the flesh of kings and the flesh of military commanders and the flesh of strong men and the flesh of horses and of those seated on them, and the flesh of all, of freemen as well as of slaves and of small ones and great.”

[[v66-19-19]]

^<<v66-19-19,19>>^ And I saw the wild beast and the kings of the earth and their armies gathered together to wage war against the one seated on the horse and against his army.

[[v66-19-20]]

^<<v66-19-20,20>>^ And the wild beast was caught, and along with it the false prophet that performed in front of it the signs with which he misled those who received the mark of the wild beast and those who worship its image. While still alive, they both were hurled into the fiery lake that burns with sulfur.

[[v66-19-21]]

^<<v66-19-21,21>>^ But the rest were killed off with the long sword that proceeded out of the mouth of the one seated on the horse. And all the birds were filled with their flesh.

'''

xref:066-revelation/066-revelation-018.adoc#v66-18-0[&#60; Capítulo Anterior] | <<v66-19-0,Topo>> | xref:066-revelation/066-revelation-020.adoc#v66-20-0[Próximo Capítulo &#62;]