include::./index.adoc[]

[[v66-12-0]]
=== A Revelation to John, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v66-12-1]]

^<<v66-12-1,1>>^ Then a great sign was seen in heaven: A woman was arrayed^&#42;1^ with the sun, and the moon was beneath her feet, and on her head was a crown of 12 stars,

[NOTE]
====
. Or “clothed.”
====

[[v66-12-2]]

^<<v66-12-2,2>>^ and she was pregnant. And she was crying out in her pains and in her agony to give birth.

[[v66-12-3]]

^<<v66-12-3,3>>^ Another sign was seen in heaven. Look! A great fiery-colored dragon, with seven heads and ten horns and on its heads seven diadems;^&#42;1^

[NOTE]
====
. Or “royal headbands.”
====

[[v66-12-4]]

^<<v66-12-4,4>>^ and its tail drags a third of the stars of heaven, and it hurled them down to the earth. And the dragon kept standing before the woman who was about to give birth, so that when she did give birth, it might devour her child.

[[v66-12-5]]

^<<v66-12-5,5>>^ And she gave birth to a son, a male, who is to shepherd all the nations with an iron rod. And her child was snatched^&#42;1^ away to God and to his throne.

[NOTE]
====
. Or “caught.”
====

[[v66-12-6]]

^<<v66-12-6,6>>^ And the woman fled into the wilderness, where she has a place prepared by God and where they would feed her for 1,260 days.

[[v66-12-7]]

^<<v66-12-7,7>>^ And war broke out in heaven: Miʹcha·el^&#42;1^ and his angels battled with the dragon, and the dragon and its angels battled

[NOTE]
====
. Meaning “Who Is Like God?”
====

[[v66-12-8]]

^<<v66-12-8,8>>^ but they did not prevail,^&#42;1^ nor was a place found for them any longer in heaven.

[NOTE]
====
. Or possibly, “but it [that is, the dragon] was defeated.”
====

[[v66-12-9]]

^<<v66-12-9,9>>^ So down the great dragon was hurled, the original serpent, the one called Devil and Satan, who is misleading the entire inhabited earth; he was hurled down to the earth, and his angels were hurled down with him.

[[v66-12-10]]

^<<v66-12-10,10>>^ I heard a loud voice in heaven say:
“Now have come to pass the salvation and the power and the Kingdom of our God and the authority of his Christ, because the accuser of our brothers has been hurled down, who accuses them day and night before our God!

[[v66-12-11]]

^<<v66-12-11,11>>^ And they conquered him because of the blood of the Lamb and because of the word of their witnessing, and they did not love their souls^&#42;1^ even in the face of death.

[NOTE]
====
. Or “lives.” See Glossary.
====

[[v66-12-12]]

^<<v66-12-12,12>>^ On this account be glad, you heavens and you who reside in them! Woe for the earth and for the sea, because the Devil has come down to you, having great anger, knowing that he has a short period of time.”

[[v66-12-13]]

^<<v66-12-13,13>>^ Now when the dragon saw that it had been hurled down to the earth, it persecuted the woman who gave birth to the male child.

[[v66-12-14]]

^<<v66-12-14,14>>^ But the two wings of the great eagle were given to the woman, so that she might fly into the wilderness to her place, where she is to be fed for a time and times and half a time^&#42;1^ away from the face of the serpent.

[NOTE]
====
. That is, three and a half times.
====

[[v66-12-15]]

^<<v66-12-15,15>>^ And the serpent spewed out water like a river from its mouth after the woman, to cause her to be drowned by the river.

[[v66-12-16]]

^<<v66-12-16,16>>^ But the earth came to the woman’s help, and the earth opened its mouth and swallowed up the river that the dragon spewed out from its mouth.

[[v66-12-17]]

^<<v66-12-17,17>>^ So the dragon became enraged at the woman and went off to wage war with the remaining ones of her offspring,^&#42;1^ who observe the commandments of God and have the work of bearing witness concerning Jesus.

[NOTE]
====
. Lit., “seed.”
====

'''

xref:066-revelation/066-revelation-011.adoc#v66-11-0[&#60; Capítulo Anterior] | <<v66-12-0,Topo>> | xref:066-revelation/066-revelation-013.adoc#v66-13-0[Próximo Capítulo &#62;]