include::./index.adoc[]

[[v63-1-0]]
=== The Second of John, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v63-1-1]]

^<<v63-1-1,1>>^ The older man^&#42;1^ to the chosen lady and to her children, whom I truly love, and not only I but also all those who have come to know the truth,

[NOTE]
====
. Or “The elder.”
====

[[v63-1-2]]

^<<v63-1-2,2>>^ because of the truth that remains in us and will be with us forever.

[[v63-1-3]]

^<<v63-1-3,3>>^ There will be with us undeserved kindness, mercy, and peace from God the Father and from Jesus Christ, the Son of the Father, with truth and love.

[[v63-1-4]]

^<<v63-1-4,4>>^ I rejoice very much because I have found some of your children walking in the truth, just as we received commandment from the Father.

[[v63-1-5]]

^<<v63-1-5,5>>^ So now I request you, lady, that we love one another. (I am writing you, not a new commandment, but one that we had from the beginning.)

[[v63-1-6]]

^<<v63-1-6,6>>^ And this is what love means, that we go on walking according to his commandments. This is the commandment, just as you have heard from the beginning, that you should go on walking in it.

[[v63-1-7]]

^<<v63-1-7,7>>^ For many deceivers have gone out into the world, those not acknowledging Jesus Christ as coming in the flesh. This is the deceiver and the antichrist.

[[v63-1-8]]

^<<v63-1-8,8>>^ Look out for yourselves, so that you do not lose the things we have worked to produce, but that you may obtain a full reward.

[[v63-1-9]]

^<<v63-1-9,9>>^ Everyone who pushes ahead and does not remain in the teaching of the Christ does not have God. The one who does remain in this teaching is the one who has both the Father and the Son.

[[v63-1-10]]

^<<v63-1-10,10>>^ If anyone comes to you and does not bring this teaching, do not receive him into your homes or say a greeting to him.

[[v63-1-11]]

^<<v63-1-11,11>>^ For the one who says a greeting to him is a sharer in his wicked works.

[[v63-1-12]]

^<<v63-1-12,12>>^ Although I have many things to write to you, I do not want to do so with paper and ink, but I am hoping to come to you and to speak with you face-to-face, so that your joy may be in full measure.

[[v63-1-13]]

^<<v63-1-13,13>>^ The children of your sister, the chosen one, send you their greetings.

'''

xref:062-1-john/062-1-john-005.adoc#v62-5-0[&#60; Capítulo Anterior] | <<v63-1-0,Topo>> | xref:064-3-john/064-3-john-001.adoc#v64-1-0[Próximo Capítulo &#62;]