include::./index.adoc[]

[[v55-1-0]]
=== The Second to Timothy, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v55-1-1]]

^<<v55-1-1,1>>^ Paul, an apostle of Christ Jesus by God’s will according to the promise of the life that is through Christ Jesus,

[[v55-1-2]]

^<<v55-1-2,2>>^ to Timothy, a beloved child:
May you have undeserved kindness, mercy, and peace from God the Father and Christ Jesus our Lord.

[[v55-1-3]]

^<<v55-1-3,3>>^ I am grateful to God, to whom I am rendering sacred service as my forefathers did, and with a clean conscience, never ceasing to remember you in my supplications night and day.

[[v55-1-4]]

^<<v55-1-4,4>>^ As I remember your tears, I am longing to see you, so that I may get filled with joy.

[[v55-1-5]]

^<<v55-1-5,5>>^ For I recall your unhypocritical faith, which dwelled first in your grandmother Loʹis and your mother Euʹnice, but which I am confident is also in you.

[[v55-1-6]]

^<<v55-1-6,6>>^ For this reason I remind you to stir up like a fire the gift of God that is in you through the laying of my hands on you.

[[v55-1-7]]

^<<v55-1-7,7>>^ For God did not give us a spirit of cowardice, but one of power and of love and of soundness of mind.

[[v55-1-8]]

^<<v55-1-8,8>>^ So do not become ashamed either of the witness about our Lord or of me, a prisoner for his sake, but take your part in suffering adversity for the good news by relying on the power of God.

[[v55-1-9]]

^<<v55-1-9,9>>^ He saved us and called us with a holy calling, not because of our works, but because of his own purpose and undeserved kindness. This was given to us in connection with Christ Jesus before times long ago,

[[v55-1-10]]

^<<v55-1-10,10>>^ but now it has been made clearly evident through the manifestation of our Savior, Christ Jesus, who has abolished death and has shed light on life and incorruption through the good news,

[[v55-1-11]]

^<<v55-1-11,11>>^ for which I was appointed a preacher and an apostle and a teacher.

[[v55-1-12]]

^<<v55-1-12,12>>^ This is why I am also suffering these things, but I am not ashamed. For I know the One whom I have believed, and I am confident that he is able to guard what I have laid up in trust with him until that day.

[[v55-1-13]]

^<<v55-1-13,13>>^ Keep holding to the standard^&#42;1^ of wholesome^&#42;2^ words that you heard from me with the faith and love that result from union with Christ Jesus.

[NOTE]
====
. Or “outline.”
. Or “healthful; beneficial.”
====

[[v55-1-14]]

^<<v55-1-14,14>>^ Guard this fine trust by means of the holy spirit, which is dwelling in us.

[[v55-1-15]]

^<<v55-1-15,15>>^ You know this, that all the men in the province of Asia have turned away from me, including Phy·gelʹus and Her·mogʹe·nes.

[[v55-1-16]]

^<<v55-1-16,16>>^ May the Lord grant mercy to the household of On·e·siphʹo·rus, for he often refreshed me, and he did not become ashamed of my prison chains.

[[v55-1-17]]

^<<v55-1-17,17>>^ On the contrary, when he was in Rome, he diligently looked for me and found me.

[[v55-1-18]]

^<<v55-1-18,18>>^ May the Lord grant him to find mercy from Jehovah^&#42;1^ in that day. And you well know all the services he rendered in Ephʹe·sus.

[NOTE]
====
. See App. A5.
====

'''

xref:054-1-timothy/054-1-timothy-006.adoc#v54-6-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-2-timothy/055-2-timothy-002.adoc#v55-2-0[Próximo Capítulo &#62;]