include::./index.adoc[]

[[v55-4-0]]
=== The Second to Timothy, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v55-4-1]]

^<<v55-4-1,1>>^ I solemnly charge you before God and Christ Jesus, who is to judge the living and the dead, and by his manifestation and his Kingdom:

[[v55-4-2]]

^<<v55-4-2,2>>^ Preach the word; be at it urgently in favorable times and difficult times; reprove, reprimand, exhort, with all patience and art of teaching.

[[v55-4-3]]

^<<v55-4-3,3>>^ For there will be a period of time when they will not put up with the wholesome^&#42;1^ teaching, but according to their own desires, they will surround themselves with teachers to have their ears tickled.^&#42;2^

[NOTE]
====
. Or “healthful; beneficial.”
. Or “to tell them what they want to hear.”
====

[[v55-4-4]]

^<<v55-4-4,4>>^ They will turn away from listening to the truth and give attention to false stories.

[[v55-4-5]]

^<<v55-4-5,5>>^ You, though, keep your senses in all things, endure hardship, do the work of an evangelizer,^&#42;1^ fully accomplish your ministry.

[NOTE]
====
. Or “keep preaching the good news.”
====

[[v55-4-6]]

^<<v55-4-6,6>>^ For I am already being poured out like a drink offering, and the time for my releasing is imminent.

[[v55-4-7]]

^<<v55-4-7,7>>^ I have fought the fine fight, I have run the race to the finish, I have observed the faith.

[[v55-4-8]]

^<<v55-4-8,8>>^ From this time on, there is reserved for me the crown of righteousness, which the Lord, the righteous judge, will give me as a reward in that day, yet not to me only, but also to all those who have loved his manifestation.

[[v55-4-9]]

^<<v55-4-9,9>>^ Do your utmost to come to me shortly.

[[v55-4-10]]

^<<v55-4-10,10>>^ For Deʹmas has forsaken me because he loved the present system of things,^&#42;1^ and he has gone to Thes·sa·lo·niʹca, Cresʹcens to Ga·laʹti·a, Titus to Dal·maʹtia.

[NOTE]
====
. Or “present age.” See Glossary.
====

[[v55-4-11]]

^<<v55-4-11,11>>^ Only Luke is with me. Bring Mark along with you, for he is helpful to me in the ministry.

[[v55-4-12]]

^<<v55-4-12,12>>^ But I have sent Tychʹi·cus off to Ephʹe·sus.

[[v55-4-13]]

^<<v55-4-13,13>>^ When you come, bring the cloak I left at Troʹas with Carpus, and the scrolls, especially the parchments.^&#42;1^

[NOTE]
====
. That is, the leather scrolls.
====

[[v55-4-14]]

^<<v55-4-14,14>>^ Alexander the coppersmith did me a great deal of harm. Jehovah^&#42;1^ will repay him according to his deeds.

[NOTE]
====
. See App. A5.
====

[[v55-4-15]]

^<<v55-4-15,15>>^ You too should be on guard against him, for he opposed our message to an excessive degree.

[[v55-4-16]]

^<<v55-4-16,16>>^ In my first defense no one came to my side, but they all forsook me—may they not be held accountable.

[[v55-4-17]]

^<<v55-4-17,17>>^ But the Lord stood near me and infused power into me, so that through me the preaching might be fully accomplished and all the nations might hear it; and I was rescued from the lion’s mouth.

[[v55-4-18]]

^<<v55-4-18,18>>^ The Lord will rescue me from every wicked work and will save me for his heavenly Kingdom. To him be the glory forever and ever. Amen.

[[v55-4-19]]

^<<v55-4-19,19>>^ Give my greetings to Prisʹca and Aqʹui·la and the household of On·e·siphʹo·rus.

[[v55-4-20]]

^<<v55-4-20,20>>^ E·rasʹtus stayed in Corinth, but I left Trophʹi·mus sick at Mi·leʹtus.

[[v55-4-21]]

^<<v55-4-21,21>>^ Do your utmost to arrive before winter.
Eu·buʹlus sends you his greetings, and so do Puʹdens and Liʹnus and Clauʹdi·a and all the brothers.

[[v55-4-22]]

^<<v55-4-22,22>>^ The Lord be with the spirit you show. His undeserved kindness be with you.

'''

xref:055-2-timothy/055-2-timothy-003.adoc#v55-3-0[&#60; Capítulo Anterior] | <<v55-4-0,Topo>> | xref:056-titus/056-titus-001.adoc#v56-1-0[Próximo Capítulo &#62;]