include::./index.adoc[]

[[v49-2-0]]
=== To the Ephesians, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v49-2-1]]

^<<v49-2-1,1>>^ Furthermore, God made you alive, though you were dead in your trespasses and sins,

[[v49-2-2]]

^<<v49-2-2,2>>^ in which you at one time walked according to the system of things^&#42;1^ of this world, according to the ruler of the authority of the air, the spirit that is now at work in the sons of disobedience.

[NOTE]
====
. Or “the course.”
====

[[v49-2-3]]

^<<v49-2-3,3>>^ Yes, among them we all at one time conducted ourselves in harmony with the desires of our flesh, carrying out the will of the flesh and of our thoughts, and we were naturally children of wrath just as the rest.

[[v49-2-4]]

^<<v49-2-4,4>>^ But God, being rich in mercy, because of his great love with which he loved us,

[[v49-2-5]]

^<<v49-2-5,5>>^ made us alive together with the Christ, even when we were dead in trespasses—by undeserved kindness you have been saved.

[[v49-2-6]]

^<<v49-2-6,6>>^ Moreover, he raised us up together and seated us together in the heavenly places in union with Christ Jesus,

[[v49-2-7]]

^<<v49-2-7,7>>^ so that in the coming systems of things^&#42;1^ he might demonstrate the surpassing riches of his undeserved kindness in his graciousness^&#42;2^ toward us in union with Christ Jesus.

[NOTE]
====
. Or “the coming ages.” See Glossary.
. Or “favor.”
====

[[v49-2-8]]

^<<v49-2-8,8>>^ By this undeserved kindness you have been saved through faith, and this is not of your own doing; rather, it is God’s gift.

[[v49-2-9]]

^<<v49-2-9,9>>^ No, it is not a result of works, so that no one should have grounds for boasting.

[[v49-2-10]]

^<<v49-2-10,10>>^ We are God’s handiwork^&#42;1^ and were created in union with Christ Jesus for good works, which God determined in advance for us to walk in them.

[NOTE]
====
. Or “are a product of His work.”
====

[[v49-2-11]]

^<<v49-2-11,11>>^ Therefore, remember that at one time you, people of the nations by fleshly descent, were the ones called “uncircumcision” by those called “circumcision,” which is made in the flesh by human hands.

[[v49-2-12]]

^<<v49-2-12,12>>^ At that time you were without Christ, alienated from the state of Israel, strangers to the covenants of the promise; you had no hope and were without God in the world.

[[v49-2-13]]

^<<v49-2-13,13>>^ But now in union with Christ Jesus, you who were once far off have come to be near by the blood of the Christ.

[[v49-2-14]]

^<<v49-2-14,14>>^ For he is our peace, the one who made the two groups one and destroyed the wall in between that fenced them off.

[[v49-2-15]]

^<<v49-2-15,15>>^ By means of his flesh he abolished the enmity, the Law of commandments consisting in decrees, in order to make the two groups in union with himself into one new man and to make peace,

[[v49-2-16]]

^<<v49-2-16,16>>^ and to reconcile fully both peoples in one body to God through the torture stake,^&#42;1^ because he had killed off the enmity by means of himself.

[NOTE]
====
. See Glossary.
====

[[v49-2-17]]

^<<v49-2-17,17>>^ And he came and declared the good news of peace to you who were far off, and peace to those near,

[[v49-2-18]]

^<<v49-2-18,18>>^ because through him we, both peoples, have free access to the Father by one spirit.

[[v49-2-19]]

^<<v49-2-19,19>>^ So you are no longer strangers and foreigners, but you are fellow citizens of the holy ones and are members of the household of God,

[[v49-2-20]]

^<<v49-2-20,20>>^ and you have been built up on the foundation of the apostles and prophets, while Christ Jesus himself is the foundation cornerstone.

[[v49-2-21]]

^<<v49-2-21,21>>^ In union with him the whole building, being harmoniously joined together, is growing into a holy temple for Jehovah.^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v49-2-22]]

^<<v49-2-22,22>>^ In union with him you too are being built up together into a place for God to inhabit by spirit.

'''

xref:049-ephesians/049-ephesians-001.adoc#v49-1-0[&#60; Capítulo Anterior] | <<v49-2-0,Topo>> | xref:049-ephesians/049-ephesians-003.adoc#v49-3-0[Próximo Capítulo &#62;]