include::./index.adoc[]

[[v49-5-0]]
=== To the Ephesians, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v49-5-1]]

^<<v49-5-1,1>>^ Therefore, become imitators of God, as beloved children,

[[v49-5-2]]

^<<v49-5-2,2>>^ and go on walking in love, just as the Christ also loved us^&#42;1^ and gave himself for us^&#42;2^ as an offering and a sacrifice, a sweet fragrance to God.

[NOTE]
====
. Or possibly, “you.”
. Or possibly, “you.”
====

[[v49-5-3]]

^<<v49-5-3,3>>^ Let sexual immorality^&#42;1^ and every sort of uncleanness or greediness not even be mentioned among you, just as is proper for holy people;

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
====

[[v49-5-4]]

^<<v49-5-4,4>>^ neither shameful conduct nor foolish talking nor obscene jesting—things that are not befitting—but rather the giving of thanks.

[[v49-5-5]]

^<<v49-5-5,5>>^ For you know this, recognizing it for yourselves, that no sexually immoral person^&#42;1^ or unclean person or greedy person, which means being an idolater, has any inheritance in the Kingdom of the Christ and of God.

[NOTE]
====
. See Glossary, “Sexual immorality.”
====

[[v49-5-6]]

^<<v49-5-6,6>>^ Let no man deceive you with empty words, for because of such things the wrath of God is coming upon the sons of disobedience.

[[v49-5-7]]

^<<v49-5-7,7>>^ Therefore, do not be sharers with them;

[[v49-5-8]]

^<<v49-5-8,8>>^ for you were once darkness, but you are now light in connection with the Lord. Go on walking as children of light,

[[v49-5-9]]

^<<v49-5-9,9>>^ for the fruitage of the light consists of every sort of goodness and righteousness and truth.

[[v49-5-10]]

^<<v49-5-10,10>>^ Keep on making sure of what is acceptable to the Lord;

[[v49-5-11]]

^<<v49-5-11,11>>^ and stop sharing in the unfruitful works that belong to the darkness; rather, expose them for what they are.

[[v49-5-12]]

^<<v49-5-12,12>>^ For the things they do in secret are shameful even to mention.

[[v49-5-13]]

^<<v49-5-13,13>>^ Now all the things that are being exposed^&#42;1^ are made evident by the light, for everything that is being made evident is light.

[NOTE]
====
. Or “reproved.”
====

[[v49-5-14]]

^<<v49-5-14,14>>^ Therefore, it is said: “Awake, O sleeper, and arise from the dead, and the Christ will shine upon you.”

[[v49-5-15]]

^<<v49-5-15,15>>^ So keep strict watch that how you walk is not as unwise but as wise persons,

[[v49-5-16]]

^<<v49-5-16,16>>^ making the best use of your time,^&#42;1^ because the days are wicked.

[NOTE]
====
. Lit., “buying out the appointed time.”
====

[[v49-5-17]]

^<<v49-5-17,17>>^ On this account stop being unreasonable, but keep perceiving what the will of Jehovah^&#42;1^ is.

[NOTE]
====
. See App. A5.
====

[[v49-5-18]]

^<<v49-5-18,18>>^ Also, do not get drunk with wine, in which there is debauchery,^&#42;1^ but keep getting filled with spirit.

[NOTE]
====
. Or “unruliness.”
====

[[v49-5-19]]

^<<v49-5-19,19>>^ Speak to one another^&#42;1^ with psalms, praises to God, and spiritual songs, singing and accompanying yourselves with music in your hearts to Jehovah,^&#42;2^

[NOTE]
====
. Or possibly, “to yourselves.”
. See App. A5.
====

[[v49-5-20]]

^<<v49-5-20,20>>^ always giving thanks to our God and Father for everything in the name of our Lord Jesus Christ.

[[v49-5-21]]

^<<v49-5-21,21>>^ Be in subjection to one another in fear of Christ.

[[v49-5-22]]

^<<v49-5-22,22>>^ Let wives be in subjection to their husbands as to the Lord,

[[v49-5-23]]

^<<v49-5-23,23>>^ because a husband is head of his wife just as the Christ is head of the congregation, he being a savior of this body.

[[v49-5-24]]

^<<v49-5-24,24>>^ In fact, as the congregation is in subjection to the Christ, wives should also be to their husbands in everything.

[[v49-5-25]]

^<<v49-5-25,25>>^ Husbands, continue loving your wives, just as the Christ also loved the congregation and gave himself up for it,

[[v49-5-26]]

^<<v49-5-26,26>>^ in order that he might sanctify it, cleansing it with the bath of water by means of the word,

[[v49-5-27]]

^<<v49-5-27,27>>^ so that he might present the congregation to himself in its splendor, without a spot or a wrinkle or any of such things, but holy and without blemish.

[[v49-5-28]]

^<<v49-5-28,28>>^ In the same way husbands should love their wives as their own bodies. A man who loves his wife loves himself,

[[v49-5-29]]

^<<v49-5-29,29>>^ for no man ever hated his own body,^&#42;1^ but he feeds and cherishes it, just as the Christ does the congregation,

[NOTE]
====
. Lit., “flesh.”
====

[[v49-5-30]]

^<<v49-5-30,30>>^ because we are members of his body.

[[v49-5-31]]

^<<v49-5-31,31>>^ “For this reason a man will leave his father and his mother and he will stick to^&#42;1^ his wife, and the two will be one flesh.”

[NOTE]
====
. Or “remain with.”
====

[[v49-5-32]]

^<<v49-5-32,32>>^ This sacred secret is great. Now I am speaking about Christ and the congregation.

[[v49-5-33]]

^<<v49-5-33,33>>^ Nevertheless, each one of you must love his wife as he does himself; on the other hand, the wife should have deep respect for her husband.

'''

xref:049-ephesians/049-ephesians-004.adoc#v49-4-0[&#60; Capítulo Anterior] | <<v49-5-0,Topo>> | xref:049-ephesians/049-ephesians-006.adoc#v49-6-0[Próximo Capítulo &#62;]