include::./index.adoc[]

[[v49-4-0]]
=== To the Ephesians, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v49-4-1]]

^<<v49-4-1,1>>^ Therefore I, the prisoner in the Lord, appeal to you to walk worthily of the calling with which you were called,

[[v49-4-2]]

^<<v49-4-2,2>>^ with all humility^&#42;1^ and mildness, with patience, putting up with one another in love,

[NOTE]
====
. Or “lowliness of mind.”
====

[[v49-4-3]]

^<<v49-4-3,3>>^ earnestly endeavoring to maintain the oneness of the spirit in the uniting bond of peace.

[[v49-4-4]]

^<<v49-4-4,4>>^ One body there is, and one spirit, just as you were called to the one hope of your calling;

[[v49-4-5]]

^<<v49-4-5,5>>^ one Lord, one faith, one baptism;

[[v49-4-6]]

^<<v49-4-6,6>>^ one God and Father of all, who is over all and through all and in all.

[[v49-4-7]]

^<<v49-4-7,7>>^ Now undeserved kindness was given to each one of us according to how the Christ measured out the free gift.

[[v49-4-8]]

^<<v49-4-8,8>>^ For it says: “When he ascended on high he carried away captives; he gave gifts in men.”

[[v49-4-9]]

^<<v49-4-9,9>>^ Now what does the expression “he ascended” mean but that he also descended into the lower regions, that is, the earth?

[[v49-4-10]]

^<<v49-4-10,10>>^ The very one who descended is also the one who ascended far above all the heavens, so that he might give fullness to all things.

[[v49-4-11]]

^<<v49-4-11,11>>^ And he gave some as apostles, some as prophets, some as evangelizers,^&#42;1^ some as shepherds and teachers,

[NOTE]
====
. Or “proclaimers of the good news.”
====

[[v49-4-12]]

^<<v49-4-12,12>>^ with a view to the readjustment^&#42;1^ of the holy ones, for ministerial work, to build up the body of the Christ,

[NOTE]
====
. Or “training.”
====

[[v49-4-13]]

^<<v49-4-13,13>>^ until we all attain to the oneness^&#42;1^ of the faith and of the accurate knowledge of the Son of God, to being a full-grown^&#42;2^ man, attaining the measure of stature that belongs to the fullness of the Christ.

[NOTE]
====
. Or “unity.”
. Or “mature.”
====

[[v49-4-14]]

^<<v49-4-14,14>>^ So we should no longer be children, tossed about as by waves and carried here and there by every wind of teaching by means of the trickery of men, by means of cunning in deceptive schemes.

[[v49-4-15]]

^<<v49-4-15,15>>^ But speaking the truth, let us by love grow up in all things into him who is the head, Christ.

[[v49-4-16]]

^<<v49-4-16,16>>^ From him all the body is harmoniously joined together and made to cooperate through every joint that gives what is needed. When each respective member functions properly, this contributes to the growth of the body as it builds itself up in love.

[[v49-4-17]]

^<<v49-4-17,17>>^ So this is what I say and bear witness to in the Lord, that you should no longer go on walking just as the nations also walk, in the futility^&#42;1^ of their minds.

[NOTE]
====
. Or “emptiness; vanity.”
====

[[v49-4-18]]

^<<v49-4-18,18>>^ They are in darkness mentally and alienated from the life that belongs to God, because of the ignorance that is in them, because of the insensitivity^&#42;1^ of their hearts.

[NOTE]
====
. Lit., “dulling.”
====

[[v49-4-19]]

^<<v49-4-19,19>>^ Having gone past all moral sense, they gave themselves over to brazen conduct^&#42;1^ to practice every sort of uncleanness with greediness.

[NOTE]
====
. Or “shameless conduct.” Greek, a·selʹgei·a. See Glossary.
====

[[v49-4-20]]

^<<v49-4-20,20>>^ But you did not learn the Christ to be like this,

[[v49-4-21]]

^<<v49-4-21,21>>^ if, indeed, you heard him and were taught by means of him, just as truth is in Jesus.

[[v49-4-22]]

^<<v49-4-22,22>>^ You were taught to put away the old personality that conforms to your former course of conduct and that is being corrupted according to its deceptive desires.

[[v49-4-23]]

^<<v49-4-23,23>>^ And you should continue to be made new in your dominant mental attitude,^&#42;1^

[NOTE]
====
. Or “in the force actuating your mind.” Lit., “to the spirit of your mind.”
====

[[v49-4-24]]

^<<v49-4-24,24>>^ and should put on the new personality that was created according to God’s will in true righteousness and loyalty.

[[v49-4-25]]

^<<v49-4-25,25>>^ Therefore, now that you have put away deceit, each one of you speak truth with his neighbor, because we are members belonging to one another.

[[v49-4-26]]

^<<v49-4-26,26>>^ Be wrathful, but do not sin; do not let the sun set while you are still angry;

[[v49-4-27]]

^<<v49-4-27,27>>^ do not give the Devil an opportunity.^&#42;1^

[NOTE]
====
. Or “neither allow place for the Devil.”
====

[[v49-4-28]]

^<<v49-4-28,28>>^ Let the one who steals steal no more; rather, let him do hard work, doing good work with his hands, so that he may have something to share with someone in need.

[[v49-4-29]]

^<<v49-4-29,29>>^ Let a rotten word not come out of your mouth, but only what is good for building up as the need may be, to impart what is beneficial to the hearers.

[[v49-4-30]]

^<<v49-4-30,30>>^ Also, do not be grieving^&#42;1^ God’s holy spirit, with which you have been sealed for a day of releasing by ransom.

[NOTE]
====
. Or “cause sorrow to.”
====

[[v49-4-31]]

^<<v49-4-31,31>>^ Put away from yourselves every kind of malicious bitterness, anger, wrath, screaming, and abusive speech, as well as everything injurious.

[[v49-4-32]]

^<<v49-4-32,32>>^ But become kind to one another, tenderly compassionate, freely forgiving one another just as God also by Christ freely forgave you.

'''

xref:049-ephesians/049-ephesians-003.adoc#v49-3-0[&#60; Capítulo Anterior] | <<v49-4-0,Topo>> | xref:049-ephesians/049-ephesians-005.adoc#v49-5-0[Próximo Capítulo &#62;]