include::./index.adoc[]

[[v49-3-0]]
=== To the Ephesians, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v49-3-1]]

^<<v49-3-1,1>>^ For this reason I, Paul, the prisoner of Christ Jesus in behalf of you, the people of the nations—

[[v49-3-2]]

^<<v49-3-2,2>>^ if, really, you have heard about the stewardship of God’s undeserved kindness that was given to me for your sakes,

[[v49-3-3]]

^<<v49-3-3,3>>^ that by way of a revelation the sacred secret was made known to me, just as I wrote previously in brief.

[[v49-3-4]]

^<<v49-3-4,4>>^ So when you read this, you can realize my comprehension of the sacred secret of the Christ.

[[v49-3-5]]

^<<v49-3-5,5>>^ In other generations this secret was not made known to the sons of men as it has now been revealed to his holy apostles and prophets by spirit,

[[v49-3-6]]

^<<v49-3-6,6>>^ namely, that people of the nations should, in union with Christ Jesus and through the good news, be joint heirs and fellow members of the body and partakers with us of the promise.

[[v49-3-7]]

^<<v49-3-7,7>>^ I became a minister of this according to the free gift of God’s undeserved kindness that was given me through the operation of his power.

[[v49-3-8]]

^<<v49-3-8,8>>^ To me, a man less than the least of all holy ones, this undeserved kindness was given, so that I should declare to the nations the good news about the unfathomable riches of the Christ

[[v49-3-9]]

^<<v49-3-9,9>>^ and should make everyone see the administration of the sacred secret that has been hidden through the ages in God, who created all things.

[[v49-3-10]]

^<<v49-3-10,10>>^ This was so that now, through the congregation, there might be made known to the governments and the authorities in the heavenly places the greatly diversified wisdom of God.

[[v49-3-11]]

^<<v49-3-11,11>>^ This is according to the eternal purpose that he formed in connection with the Christ, Jesus our Lord,

[[v49-3-12]]

^<<v49-3-12,12>>^ by means of whom we have this freeness of speech and free access with confidence through our faith in him.

[[v49-3-13]]

^<<v49-3-13,13>>^ So I ask you not to give up on account of my tribulations in your behalf, for these mean glory for you.

[[v49-3-14]]

^<<v49-3-14,14>>^ For this reason I bend my knees to the Father,

[[v49-3-15]]

^<<v49-3-15,15>>^ to whom every family in heaven and on earth owes its name.

[[v49-3-16]]

^<<v49-3-16,16>>^ I pray that he may grant you through the abundance of his glory to be made mighty in the man you are inside, with power through his spirit,

[[v49-3-17]]

^<<v49-3-17,17>>^ and that through your faith you may have the Christ dwell in your hearts with love. May you be rooted and established on the foundation,

[[v49-3-18]]

^<<v49-3-18,18>>^ in order that with all the holy ones you may be thoroughly able to comprehend fully what is the breadth and length and height and depth,

[[v49-3-19]]

^<<v49-3-19,19>>^ and to know the love of the Christ, which surpasses knowledge, so that you may be filled with all the fullness that God gives.

[[v49-3-20]]

^<<v49-3-20,20>>^ Now to the one who can, according to his power that is operating in us, do more than superabundantly beyond all the things we ask or conceive,

[[v49-3-21]]

^<<v49-3-21,21>>^ to him be the glory by means of the congregation and by means of Christ Jesus to all generations forever and ever. Amen.

'''

xref:049-ephesians/049-ephesians-002.adoc#v49-2-0[&#60; Capítulo Anterior] | <<v49-3-0,Topo>> | xref:049-ephesians/049-ephesians-004.adoc#v49-4-0[Próximo Capítulo &#62;]