include::./index.adoc[]

[[v10-11-0]]
=== The Second of Samuel, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-11-1]]

^<<v10-11-1,1>>^ At the start of the year,^&#42;1^ at the time when kings go on campaigns, David sent Joʹab and his servants and the entire army of Israel to bring the Amʹmon·ites to ruin, and they besieged Rabʹbah, while David stayed in Jerusalem.

[NOTE]
====
. That is, in the spring.
====

[[v10-11-2]]

^<<v10-11-2,2>>^ One evening^&#42;1^ David got up from his bed and walked around on the rooftop of the king’s house.^&#42;2^ From the rooftop he saw a woman bathing, and the woman was very beautiful.

[NOTE]
====
. Or “Late one afternoon.”
. Or “palace.”
====

[[v10-11-3]]

^<<v10-11-3,3>>^ David sent someone to inquire about the woman, and he reported: “Is this not Bath-sheʹba the daughter of E·liʹam and the wife of U·riʹah the Hitʹtite?”

[[v10-11-4]]

^<<v10-11-4,4>>^ Then David sent messengers to bring her. So she came in to him, and he lay down with her. (This happened while she was purifying herself from her uncleanness.^&#42;1^) Afterward, she returned to her house.

[NOTE]
====
. Possibly her menstrual uncleanness.
====

[[v10-11-5]]

^<<v10-11-5,5>>^ The woman became pregnant, and she sent a message to David: “I am pregnant.”

[[v10-11-6]]

^<<v10-11-6,6>>^ At this David sent a message to Joʹab: “Send to me U·riʹah the Hitʹtite.” So Joʹab sent U·riʹah to David.

[[v10-11-7]]

^<<v10-11-7,7>>^ When U·riʹah came to him, David asked him how Joʹab was getting along, how the troops were getting along, and how the war was going.

[[v10-11-8]]

^<<v10-11-8,8>>^ David then said to U·riʹah: “Go down to your house and relax.”^&#42;1^ When U·riʹah left the king’s house, the king’s courtesy gift^&#42;2^ was sent after him.

[NOTE]
====
. Lit., “wash your feet.”
. Or “the king’s portion,” that is, the portion sent by the host to the honored guest.
====

[[v10-11-9]]

^<<v10-11-9,9>>^ However, U·riʹah slept at the entrance of the king’s house with all the other servants of his lord, and he did not go down to his own house.

[[v10-11-10]]

^<<v10-11-10,10>>^ So David was told: “U·riʹah did not go down to his own house.” At that David said to U·riʹah: “Have you not just returned from a journey? Why did you not go down to your own house?”

[[v10-11-11]]

^<<v10-11-11,11>>^ U·riʹah replied to David: “The Ark and Israel and Judah are dwelling in temporary shelters, and my lord Joʹab and the servants of my lord are camping in the open field. So should I go into my own house to eat and drink and lie down with my wife? As surely as you live and are alive,^&#42;1^ I will not do this thing!”

[NOTE]
====
. Or “and as your soul is living.”
====

[[v10-11-12]]

^<<v10-11-12,12>>^ Then David said to U·riʹah: “Stay here also today, and tomorrow I will send you away.” So U·riʹah stayed in Jerusalem on that day and the following day.

[[v10-11-13]]

^<<v10-11-13,13>>^ David then sent for him to come and eat and drink with him, and he got him drunk. But in the evening, he went out to sleep on his bed with the servants of his lord, and he did not go down to his house.

[[v10-11-14]]

^<<v10-11-14,14>>^ In the morning David wrote a letter to Joʹab and sent it by the hand of U·riʹah.

[[v10-11-15]]

^<<v10-11-15,15>>^ He wrote in the letter: “Put U·riʹah in the front lines where the fighting is fiercest. Then retreat from behind him, so that he will be struck down and die.”

[[v10-11-16]]

^<<v10-11-16,16>>^ Joʹab had been carefully watching the city, and he stationed U·riʹah where he knew there were mighty warriors.

[[v10-11-17]]

^<<v10-11-17,17>>^ When the men of the city came out and fought against Joʹab, some of David’s servants fell, and U·riʹah the Hitʹtite was among those who died.

[[v10-11-18]]

^<<v10-11-18,18>>^ Joʹab now reported to David all the news about the war.

[[v10-11-19]]

^<<v10-11-19,19>>^ He instructed the messenger: “When you finish speaking to the king about all the news of the war,

[[v10-11-20]]

^<<v10-11-20,20>>^ the king may become angry and say to you, ‘Why did you have to go so near to the city to fight? Did you not know that they would shoot from the top of the wall?

[[v10-11-21]]

^<<v10-11-21,21>>^ Who struck down A·bimʹe·lech the son of Je·rubʹbe·sheth? Was it not a woman who threw an upper millstone on him from the top of the wall, causing his death at Theʹbez? Why did you have to go so close to the wall?’ Then say, ‘Your servant U·riʹah the Hitʹtite also died.’”

[[v10-11-22]]

^<<v10-11-22,22>>^ So the messenger went and told David everything that Joʹab had sent him to tell.

[[v10-11-23]]

^<<v10-11-23,23>>^ Then the messenger told David: “Their men overpowered us, and they came out against us in the field; but we drove them back to the entrance of the city gate.

[[v10-11-24]]

^<<v10-11-24,24>>^ And the archers were shooting at your servants from the top of the wall, and some of the servants of the king died; your servant U·riʹah the Hitʹtite also died.”

[[v10-11-25]]

^<<v10-11-25,25>>^ At that David said to the messenger: “Say this to Joʹab: ‘Do not let this matter trouble you, for the sword devours one as well as another. Intensify your battle against the city and conquer it.’ And encourage him.”

[[v10-11-26]]

^<<v10-11-26,26>>^ When U·riʹah’s wife heard that her husband U·riʹah had died, she began to mourn her husband.

[[v10-11-27]]

^<<v10-11-27,27>>^ As soon as the mourning period was over, David sent for her and brought her to his house, and she became his wife and bore him a son. But what David had done was very displeasing to^&#42;1^ Jehovah.

[NOTE]
====
. Lit., “was bad in the eyes of.”
====

'''

xref:010-2-samuel/010-2-samuel-010.adoc#v10-10-0[&#60; Capítulo Anterior] | <<v10-11-0,Topo>> | xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[Próximo Capítulo &#62;]