include::./index.adoc[]

[[v10-18-0]]
=== The Second of Samuel, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-18-1]]

^<<v10-18-1,1>>^ Then David numbered the men who were with him and placed over them chiefs of thousands and chiefs of hundreds.

[[v10-18-2]]

^<<v10-18-2,2>>^ And David sent one third of the men under the command^&#42;1^ of Joʹab, one third under the command of Joʹab’s brother A·bishʹai the son of Ze·ruʹiah, and one third under the command of Itʹtai the Gitʹtite. The king then said to the men: “I will also go out with you.”

[NOTE]
====
. Lit., “hand.”
====

[[v10-18-3]]

^<<v10-18-3,3>>^ But they said: “You must not go out, for if we flee, they would not care about^&#42;1^ us; and if half of us would die, they would not care about us, because you are worth 10,000 of us. Therefore, it would be better if you would send us help from the city.”

[NOTE]
====
. Lit., “set heart toward.”
====

[[v10-18-4]]

^<<v10-18-4,4>>^ The king said to them: “Whatever seems best to you, I will do.” So the king stood next to the city gate, and all the men went out by hundreds and by thousands.

[[v10-18-5]]

^<<v10-18-5,5>>^ Then the king gave Joʹab and A·bishʹai and Itʹtai this order: “Deal gently with the young man Abʹsa·lom for my sake.” All the men heard it when the king gave all the chiefs the order about Abʹsa·lom.

[[v10-18-6]]

^<<v10-18-6,6>>^ The men went out to the field to meet Israel, and the battle took place in the forest of Eʹphra·im.

[[v10-18-7]]

^<<v10-18-7,7>>^ There the people of Israel were defeated by the servants of David, and a great slaughter took place on that day—20,000 men.

[[v10-18-8]]

^<<v10-18-8,8>>^ The battle spread through the whole region. Furthermore, the forest devoured more of the people than the sword did on that day.

[[v10-18-9]]

^<<v10-18-9,9>>^ Abʹsa·lom eventually found himself facing the servants of David. Abʹsa·lom was riding on a mule, and the mule went under the thick branches of a large tree, and his head got entangled in the big tree, so that he was suspended in midair^&#42;1^ while the mule he had been riding kept going.

[NOTE]
====
. Lit., “between the heavens and the earth.”
====

[[v10-18-10]]

^<<v10-18-10,10>>^ Then someone saw it and told Joʹab: “Look! I have seen Abʹsa·lom hanging in a big tree.”

[[v10-18-11]]

^<<v10-18-11,11>>^ Joʹab replied to the man who told him: “If you saw it, why did you not strike him down to the ground on the spot? Then I would have gladly given you ten pieces of silver and a belt.”

[[v10-18-12]]

^<<v10-18-12,12>>^ But the man said to Joʹab: “Even if I were handed^&#42;1^ 1,000 pieces of silver, I could not lift my hand against the king’s son, for we heard the king order you and A·bishʹai and Itʹtai, ‘Whoever you are, watch over the young man Abʹsa·lom.’

[NOTE]
====
. Lit., “were weighing upon my palms.”
====

[[v10-18-13]]

^<<v10-18-13,13>>^ If I had disobeyed and taken his life,^&#42;1^ it could never have remained hidden from the king, and you would not have protected me.”

[NOTE]
====
. Or “If I had dealt treacherously against his soul.”
====

[[v10-18-14]]

^<<v10-18-14,14>>^ To this Joʹab said: “I am not going to waste any more time with you!” So he took three spikes^&#42;1^ in his hand and drove them through the heart of Abʹsa·lom while he was still alive in the midst of the big tree.

[NOTE]
====
. Or possibly, “darts; spears.” Lit., “rods.”
====

[[v10-18-15]]

^<<v10-18-15,15>>^ Then ten attendants who carried Joʹab’s weapons came and struck Abʹsa·lom until he was dead.

[[v10-18-16]]

^<<v10-18-16,16>>^ Joʹab now blew the horn, and the men returned from chasing after Israel; Joʹab called for them to halt.

[[v10-18-17]]

^<<v10-18-17,17>>^ They took Abʹsa·lom and threw him into a big pit in the forest and piled up over him a very big heap of stones. And all Israel fled to their homes.

[[v10-18-18]]

^<<v10-18-18,18>>^ Now Abʹsa·lom, while he was alive, had taken and set up for himself a pillar in the Valley^&#42;1^ of the King, for he said: “I have no son to preserve the memory of my name.” So he named the pillar after himself, and it is called Abʹsa·lom’s Monument to this day.

[NOTE]
====
. Or “Low Plain.”
====

[[v10-18-19]]

^<<v10-18-19,19>>^ A·himʹa·az the son of Zaʹdok said: “Let me run, please, and break the news to the king, for Jehovah has given him justice by freeing him from his enemies.”

[[v10-18-20]]

^<<v10-18-20,20>>^ But Joʹab said to him: “You will not be a bearer of news this day. You may break the news on another day, but today you will not break the news, because the king’s own son has died.”

[[v10-18-21]]

^<<v10-18-21,21>>^ Then Joʹab said to a Cushʹite: “Go, tell the king what you have seen.” At that the Cushʹite bowed to Joʹab and ran off.

[[v10-18-22]]

^<<v10-18-22,22>>^ A·himʹa·az the son of Zaʹdok said once again to Joʹab: “Whatever happens, please let me also run behind the Cushʹite.” However, Joʹab said: “Why should you run, my son, when there is no news for you to tell?”

[[v10-18-23]]

^<<v10-18-23,23>>^ Still he said: “Whatever happens, let me run.” So Joʹab said to him: “Run!” And A·himʹa·az ran by the way of the district of the Jordan,^&#42;1^ and he eventually overtook the Cushʹite.

[NOTE]
====
. Lit., “the district.”
====

[[v10-18-24]]

^<<v10-18-24,24>>^ Now David was sitting between the two city gates, and the watchman went up to the roof of the gate by the wall. He looked up and saw a man running by himself.

[[v10-18-25]]

^<<v10-18-25,25>>^ So the watchman called out and told the king. The king said: “If he is by himself, he has news to tell.” As he came steadily nearer,

[[v10-18-26]]

^<<v10-18-26,26>>^ the watchman saw another man running. The watchman then called to the gatekeeper: “Look! Another man running by himself!” The king said: “This one is also bringing news.”

[[v10-18-27]]

^<<v10-18-27,27>>^ The watchman said: “I can see that the first man runs like A·himʹa·az the son of Zaʹdok,” so the king said: “He is a good man, and he comes with good news.”

[[v10-18-28]]

^<<v10-18-28,28>>^ A·himʹa·az then called out to the king: “All is well!” With that he bowed to the king with his face to the ground. Then he said: “May Jehovah your God be praised, who has surrendered the men who rebelled^&#42;1^ against my lord the king!”

[NOTE]
====
. Lit., “lifted up their hand.”
====

[[v10-18-29]]

^<<v10-18-29,29>>^ However, the king said: “Is everything all right with the young man Abʹsa·lom?” To this A·himʹa·az said: “I saw the great commotion when Joʹab sent the king’s servant and your servant, but I did not know what it was.”

[[v10-18-30]]

^<<v10-18-30,30>>^ So the king said: “Step aside, stand here.” At that he stepped aside and stood there.

[[v10-18-31]]

^<<v10-18-31,31>>^ Then the Cushʹite arrived, and the Cushʹite said: “Let my lord the king accept this news: Today Jehovah has brought justice by freeing you from the hand of all those who rebelled against you.”

[[v10-18-32]]

^<<v10-18-32,32>>^ But the king said to the Cushʹite: “Is everything all right with the young man Abʹsa·lom?” To this the Cushʹite said: “May all the enemies of my lord the king and all those who rebelled against you to harm you become like the young man!”

[[v10-18-33]]

^<<v10-18-33,33>>^ This disturbed the king, and he went up to the roof chamber over the gateway and wept, saying as he walked: “My son Abʹsa·lom, my son, my son Abʹsa·lom! If only I had died instead of you, Abʹsa·lom my son, my son!”

'''

xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[&#60; Capítulo Anterior] | <<v10-18-0,Topo>> | xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[Próximo Capítulo &#62;]