include::./index.adoc[]

[[v10-20-0]]
=== The Second of Samuel, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-20-1]]

^<<v10-20-1,1>>^ Now there was a troublemaker named Sheʹba the son of Bichʹri, a Benʹja·min·ite. He blew the horn and said: “We have no share in David, and we have no inheritance in the son of Jesʹse. Everyone to his gods,^&#42;1^ O Israel!”

[NOTE]
====
. Or possibly, “tents.”
====

[[v10-20-2]]

^<<v10-20-2,2>>^ At that all the men of Israel quit following David to follow Sheʹba the son of Bichʹri; but the men of Judah stuck to their king, from the Jordan to Jerusalem.

[[v10-20-3]]

^<<v10-20-3,3>>^ When David came to his house^&#42;1^ at Jerusalem, the king took the ten concubines he had left behind to take care of the house, and he put them in a house under guard. He supplied food to them, but he did not have any relations with them. They remained in confinement until the day of their death, living as if they were widows, even though they had a living husband.

[NOTE]
====
. Or “palace.”
====

[[v10-20-4]]

^<<v10-20-4,4>>^ The king now said to A·maʹsa: “Call the men of Judah together to me within three days, and you also should be here.”

[[v10-20-5]]

^<<v10-20-5,5>>^ So A·maʹsa went to call Judah together, but he came later than the set time that had been appointed for him.

[[v10-20-6]]

^<<v10-20-6,6>>^ Then David said to A·bishʹai: “Sheʹba the son of Bichʹri may do us more harm than Abʹsa·lom did. Take the servants of your lord and chase after him, so that he may not find fortified cities and escape from us.”

[[v10-20-7]]

^<<v10-20-7,7>>^ So the men of Joʹab, the Cherʹe·thites, the Pelʹe·thites, and all the mighty men went out after him; they left Jerusalem to chase after Sheʹba the son of Bichʹri.

[[v10-20-8]]

^<<v10-20-8,8>>^ When they were near the great stone in Gibʹe·on, A·maʹsa came to meet them. Now Joʹab was wearing his battle clothing, and he had a sword in its sheath strapped to his hip. When he stepped forward, the sword fell out.

[[v10-20-9]]

^<<v10-20-9,9>>^ Joʹab said to A·maʹsa: “Are you all right, my brother?” Then with his right hand, Joʹab took hold of A·maʹsa’s beard as if to kiss him.

[[v10-20-10]]

^<<v10-20-10,10>>^ A·maʹsa was not on guard against the sword that was in Joʹab’s hand, and Joʹab stabbed him with it in the abdomen, and his intestines spilled out on the ground. He did not have to stab him again; once was enough to kill him. Then Joʹab and his brother A·bishʹai chased after Sheʹba the son of Bichʹri.

[[v10-20-11]]

^<<v10-20-11,11>>^ One of Joʹab’s young men stood by him and was saying: “Whoever is on Joʹab’s side and whoever belongs to David, let him follow Joʹab!”

[[v10-20-12]]

^<<v10-20-12,12>>^ All the while A·maʹsa was wallowing in his blood in the middle of the road. When the man saw that all the people were stopping, he moved A·maʹsa from the road to the field. Then he threw a garment over him, because he saw that everyone was stopping when they came up to him.

[[v10-20-13]]

^<<v10-20-13,13>>^ After he had removed him from the road, all the men followed Joʹab to chase after Sheʹba the son of Bichʹri.

[[v10-20-14]]

^<<v10-20-14,14>>^ Sheʹba passed through all the tribes of Israel to Abel of Beth-maʹa·cah. The Bichʹrites gathered together and also went in after him.

[[v10-20-15]]

^<<v10-20-15,15>>^ Joʹab and his men^&#42;1^ came and besieged him in Abel of Beth-maʹa·cah and raised up a siege rampart against the city, as it was standing within a rampart. And all the men with Joʹab were undermining the wall to knock it down.

[NOTE]
====
. Lit., “They.”
====

[[v10-20-16]]

^<<v10-20-16,16>>^ And a wise woman called out from the city: “Listen, men, listen! Please tell Joʹab, ‘Come here, and let me speak to you.’”

[[v10-20-17]]

^<<v10-20-17,17>>^ So he went near to her, and the woman said: “Are you Joʹab?” He replied: “I am.” At this she said to him: “Listen to the words of your servant.” He said: “I am listening.”

[[v10-20-18]]

^<<v10-20-18,18>>^ She continued: “They would always say in the past, ‘Let them inquire in Abel,’ and that was the end of the matter.

[[v10-20-19]]

^<<v10-20-19,19>>^ I represent the peaceable and faithful ones of Israel. You are seeking to destroy a city that is like a mother in Israel. Why should you do away with^&#42;1^ the inheritance of Jehovah?”

[NOTE]
====
. Lit., “swallow up.”
====

[[v10-20-20]]

^<<v10-20-20,20>>^ Joʹab answered: “It is unthinkable for me to do away with it and destroy it.

[[v10-20-21]]

^<<v10-20-21,21>>^ That is not the case at all. Rather, a man named Sheʹba the son of Bichʹri from the mountainous region of Eʹphra·im has rebelled^&#42;1^ against King David. If you hand over this one man, I will withdraw from the city.” Then the woman said to Joʹab: “Look! His head will be thrown over the wall to you!”

[NOTE]
====
. Lit., “lifted up his hand.”
====

[[v10-20-22]]

^<<v10-20-22,22>>^ At once the wise woman went in to all the people, and they cut off the head of Sheʹba the son of Bichʹri and threw it to Joʹab. At that he blew the horn, and they dispersed from the city, each one to his home; and Joʹab returned to Jerusalem to the king.

[[v10-20-23]]

^<<v10-20-23,23>>^ Now Joʹab was in charge of all the army of Israel; Be·naiʹah the son of Je·hoiʹa·da was over the Cherʹe·thites and the Pelʹe·thites.

[[v10-20-24]]

^<<v10-20-24,24>>^ A·doʹram was over those conscripted for forced labor; Je·hoshʹa·phat the son of A·hiʹlud was the recorder.

[[v10-20-25]]

^<<v10-20-25,25>>^ Sheʹva was the secretary; Zaʹdok and A·biʹa·thar were priests.

[[v10-20-26]]

^<<v10-20-26,26>>^ And Iʹra the Jaʹir·ite also became a chief minister^&#42;1^ for David.

[NOTE]
====
. Lit., “became a priest.”
====

'''

xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[&#60; Capítulo Anterior] | <<v10-20-0,Topo>> | xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[Próximo Capítulo &#62;]