include::./index.adoc[]

[[v10-12-0]]
=== The Second of Samuel, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-12-1]]

^<<v10-12-1,1>>^ So Jehovah sent Nathan to David. He came in to him and said: “There were two men in one city, the one rich and the other poor.

[[v10-12-2]]

^<<v10-12-2,2>>^ The rich man had very many sheep and cattle;

[[v10-12-3]]

^<<v10-12-3,3>>^ but the poor man had nothing but one small female lamb, which he had bought. He cared for it, and it grew up together with him and his sons. It would eat from the little food he had and drink from his cup and sleep in his arms. It became as a daughter to him.

[[v10-12-4]]

^<<v10-12-4,4>>^ Later a visitor came to the rich man, but he would not take any of his own sheep and cattle to prepare a meal for the traveler who had come to him. Instead, he took the poor man’s lamb and prepared it for the man who had come to him.”

[[v10-12-5]]

^<<v10-12-5,5>>^ At this David grew very angry against the man, and he said to Nathan: “As surely as Jehovah is living, the man who did this deserves to die!

[[v10-12-6]]

^<<v10-12-6,6>>^ And he should pay for the lamb four times over, because he did this and showed no compassion.”

[[v10-12-7]]

^<<v10-12-7,7>>^ Then Nathan said to David: “You are the man! This is what Jehovah the God of Israel says: ‘I myself anointed you as king over Israel, and I rescued you from the hand of Saul.

[[v10-12-8]]

^<<v10-12-8,8>>^ I was willing to give you your master’s house and put your master’s wives in your arms, and I gave you the house of Israel and of Judah. And as if that were not enough, I was willing to do much more for you.

[[v10-12-9]]

^<<v10-12-9,9>>^ Why did you despise the word of Jehovah by doing what is bad in his eyes? You struck down U·riʹah the Hitʹtite with the sword! Then you took his wife as your wife after you killed him by the sword of the Amʹmon·ites.

[[v10-12-10]]

^<<v10-12-10,10>>^ Now a sword will never depart from your own house, because you despised me by taking the wife of U·riʹah the Hitʹtite as your wife.’

[[v10-12-11]]

^<<v10-12-11,11>>^ This is what Jehovah says: ‘Here I am bringing against you calamity from within your own house; and before your own eyes, I will take your wives and give them to another man,^&#42;1^ and he will lie down with your wives in broad daylight.^&#42;2^

[NOTE]
====
. Or “to your fellow man.”
. Lit., “to the eyes of this sun.”
====

[[v10-12-12]]

^<<v10-12-12,12>>^ Although you acted in secret, I will do this in front of all Israel and in broad daylight.’”^&#42;1^

[NOTE]
====
. Lit., “before the sun.”
====

[[v10-12-13]]

^<<v10-12-13,13>>^ David then said to Nathan: “I have sinned against Jehovah.” Nathan replied to David: “Jehovah, in turn, forgives your sin.^&#42;1^ You will not die.

[NOTE]
====
. Or “lets your sin pass by.”
====

[[v10-12-14]]

^<<v10-12-14,14>>^ Nevertheless, because you have treated Jehovah with utter disrespect in this matter, the son just born to you will certainly die.”

[[v10-12-15]]

^<<v10-12-15,15>>^ Then Nathan went to his own house.
And Jehovah struck the child whom U·riʹah’s wife had borne to David, and he became sick.

[[v10-12-16]]

^<<v10-12-16,16>>^ David pleaded with the true God in behalf of the boy. David went on a strict fast and would go in and spend the night lying on the ground.

[[v10-12-17]]

^<<v10-12-17,17>>^ So the elders of his house stood over him and tried to raise him up from the ground, but he refused and would not eat with them.

[[v10-12-18]]

^<<v10-12-18,18>>^ On the seventh day the child died, but David’s servants were afraid to tell him that the child was dead. They said: “While the child was alive we spoke to him, and he did not listen to us. So how can we tell him that the child has died? He may do something terrible.”

[[v10-12-19]]

^<<v10-12-19,19>>^ When David saw that his servants were whispering to one another, he discerned that the child had died. David said to his servants: “Has the child died?” They replied: “He has died.”

[[v10-12-20]]

^<<v10-12-20,20>>^ So David got up from the ground. He washed, rubbed himself with oil, changed his clothing, and went to the house of Jehovah and prostrated himself. Afterward, he went to his house^&#42;1^ and asked for food to be brought to him, and he ate.

[NOTE]
====
. Or “palace.”
====

[[v10-12-21]]

^<<v10-12-21,21>>^ His servants asked him: “Why have you acted in this way? While the child was alive, you fasted and kept weeping; but as soon as the child died, you got up and ate food.”

[[v10-12-22]]

^<<v10-12-22,22>>^ He replied: “While the child was alive, I fasted and kept weeping because I said to myself, ‘Who knows whether Jehovah may show me favor and let the child live?’

[[v10-12-23]]

^<<v10-12-23,23>>^ Now that he has died, why should I fast? Can I bring him back? I will go to him, but he will not return to me.”

[[v10-12-24]]

^<<v10-12-24,24>>^ Then David comforted his wife Bath-sheʹba. He went in to her and lay down with her. In time she bore a son, and he was named Solʹo·mon.^&#42;1^ And Jehovah loved him,

[NOTE]
====
. From a Hebrew word meaning “Peace.”
====

[[v10-12-25]]

^<<v10-12-25,25>>^ and he sent word through Nathan the prophet to name him Jed·i·diʹah,^&#42;1^ for the sake of Jehovah.

[NOTE]
====
. Meaning “Beloved of Jah.”
====

[[v10-12-26]]

^<<v10-12-26,26>>^ Joʹab continued fighting against Rabʹbah of the Amʹmon·ites, and he captured the royal city.^&#42;1^

[NOTE]
====
. Or “the city of the kingdom.”
====

[[v10-12-27]]

^<<v10-12-27,27>>^ So Joʹab sent messengers to David and said: “I have fought against Rabʹbah, and I have captured the city of waters.^&#42;1^

[NOTE]
====
. Possibly referring to the water resources of the city.
====

[[v10-12-28]]

^<<v10-12-28,28>>^ Now gather the rest of the troops and encamp against the city and capture it. Otherwise, I will be the one to capture the city, and it will be credited to me.”^&#42;1^

[NOTE]
====
. Lit., “and my name will be called upon it.”
====

[[v10-12-29]]

^<<v10-12-29,29>>^ So David gathered all the troops and went to Rabʹbah and fought against it and captured it.

[[v10-12-30]]

^<<v10-12-30,30>>^ Then he took the crown of Malʹcam from its head. The weight of it was a talent^&#42;1^ of gold, along with precious stones, and it was placed on David’s head. He also took a vast amount of spoil from the city.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v10-12-31]]

^<<v10-12-31,31>>^ And he brought out the people who were in it and put them to work at sawing stones, at working with sharp iron instruments and with iron axes, and at brickmaking. That was what he did to all the cities of the Amʹmon·ites. Finally David and all the troops returned to Jerusalem.

'''

xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[&#60; Capítulo Anterior] | <<v10-12-0,Topo>> | xref:010-2-samuel/010-2-samuel-013.adoc#v10-13-0[Próximo Capítulo &#62;]