include::./index.adoc[]

[[v10-1-0]]
=== The Second of Samuel, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-1-1]]

^<<v10-1-1,1>>^ After Saul’s death, when David had returned from defeating^&#42;1^ the A·malʹek·ites, David stayed at Zikʹlag for two days.

[NOTE]
====
. Or “striking down.”
====

[[v10-1-2]]

^<<v10-1-2,2>>^ On the third day, a man came from the camp of Saul with his garments ripped apart and dirt on his head. When he approached David, he fell down to the ground and prostrated himself.

[[v10-1-3]]

^<<v10-1-3,3>>^ David asked him: “Where are you coming from?” He replied: “I have escaped from the camp of Israel.”

[[v10-1-4]]

^<<v10-1-4,4>>^ David asked him: “How did things turn out? Please tell me.” To this he said: “The people have fled from the battle and many have fallen and died. Even Saul and his son Jonʹa·than have died.”

[[v10-1-5]]

^<<v10-1-5,5>>^ Then David asked the young man who brought him the news: “How do you know that Saul and his son Jonʹa·than are dead?”

[[v10-1-6]]

^<<v10-1-6,6>>^ The young man replied: “By chance I was on Mount Gil·boʹa, and there was Saul supporting himself on his spear, and the chariots and horsemen had caught up with him.

[[v10-1-7]]

^<<v10-1-7,7>>^ When he turned around and saw me, he called me, and I said, ‘Here I am!’

[[v10-1-8]]

^<<v10-1-8,8>>^ He asked me, ‘Who are you?’ I replied, ‘I am an A·malʹek·ite.’

[[v10-1-9]]

^<<v10-1-9,9>>^ Then he said, ‘Please stand over me and put me to death, for I am in great agony, but I am still alive.’^&#42;1^

[NOTE]
====
. Or “because all my soul is still in me.”
====

[[v10-1-10]]

^<<v10-1-10,10>>^ So I stood over him and put him to death, for I knew that he could not survive after he had fallen down wounded. Then I took the crown^&#42;1^ that was on his head and the bracelet that was on his arm, and I brought them here to my lord.”

[NOTE]
====
. Or “diadem.”
====

[[v10-1-11]]

^<<v10-1-11,11>>^ At this David took hold of his garments and ripped them apart, and so did all the men who were with him.

[[v10-1-12]]

^<<v10-1-12,12>>^ And they wailed and wept and fasted until evening for Saul, for his son Jonʹa·than, for the people of Jehovah, and for the house of Israel, because they had fallen by the sword.

[[v10-1-13]]

^<<v10-1-13,13>>^ David asked the young man who brought him the news: “Where are you from?” He said: “I am the son of a foreign resident, an A·malʹek·ite.”

[[v10-1-14]]

^<<v10-1-14,14>>^ Then David said to him: “Why did you not fear to lift your hand to do away with the anointed of Jehovah?”

[[v10-1-15]]

^<<v10-1-15,15>>^ With that David called one of the young men and said: “Step forward and strike him.” So he struck him down, and he died.

[[v10-1-16]]

^<<v10-1-16,16>>^ David said to him: “Your blood is on your own head, because your own mouth testified against you by saying, ‘I myself put the anointed of Jehovah to death.’”

[[v10-1-17]]

^<<v10-1-17,17>>^ Then David chanted this dirge^&#42;1^ over Saul and his son Jonʹa·than

[NOTE]
====
. Or “song of mourning.”
====

[[v10-1-18]]

^<<v10-1-18,18>>^ and said that the people of Judah should be taught the dirge called “The Bow,” which is written in the book of Jaʹshar:

[[v10-1-19]]

^<<v10-1-19,19>>^ “The beauty, O Israel, lies slain upon your high places.
How the mighty have fallen!

[[v10-1-20]]

^<<v10-1-20,20>>^ Do not tell it in Gath;
Do not announce it in the streets of Ashʹke·lon,
Or the daughters of the Phi·lisʹtines will rejoice,
Or the daughters of the uncircumcised men will exult.

[[v10-1-21]]

^<<v10-1-21,21>>^ You mountains of Gil·boʹa,
May there be no dew or rain upon you,
Nor fields producing holy contributions,
Because there the shield of mighty ones was defiled,
The shield of Saul is no longer anointed with oil.

[[v10-1-22]]

^<<v10-1-22,22>>^ From the blood of the slain, from the fat of mighty ones,
The bow of Jonʹa·than did not turn back,
And the sword of Saul would not return without success.

[[v10-1-23]]

^<<v10-1-23,23>>^ Saul and Jonʹa·than, beloved and cherished^&#42;1^ during their life,
And in death they were not separated.
Swifter than the eagles they were,
Mightier than the lions.

[NOTE]
====
. Or “pleasant.”
====

[[v10-1-24]]

^<<v10-1-24,24>>^ O daughters of Israel, weep over Saul,
Who clothed you in scarlet and finery,
Who put gold ornaments upon your clothing.

[[v10-1-25]]

^<<v10-1-25,25>>^ How the mighty have fallen in battle!
Jonʹa·than lies slain upon your high places!

[[v10-1-26]]

^<<v10-1-26,26>>^ I am distressed over you, my brother Jonʹa·than;
You were very dear to me.
More wonderful was your love to me than the love of women.

[[v10-1-27]]

^<<v10-1-27,27>>^ How the mighty have fallen
And the weapons of war have perished!”

'''

xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[&#60; Capítulo Anterior] | <<v10-1-0,Topo>> | xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[Próximo Capítulo &#62;]