include::./index.adoc[]

[[v10-6-0]]
=== The Second of Samuel, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-6-1]]

^<<v10-6-1,1>>^ David again gathered all the best troops in Israel, 30,000 men.

[[v10-6-2]]

^<<v10-6-2,2>>^ Then David and all the men with him set out for Baʹal·e-juʹdah to bring up from there the Ark of the true God, before which people call on the name of Jehovah of armies, who sits enthroned above^&#42;1^ the cherubs.

[NOTE]
====
. Or possibly, “between.”
====

[[v10-6-3]]

^<<v10-6-3,3>>^ However, they placed the Ark of the true God on a new wagon to transport it from the house of A·binʹa·dab, which was on the hill; and Uzʹzah and A·hiʹo, the sons of A·binʹa·dab, were leading the new wagon.

[[v10-6-4]]

^<<v10-6-4,4>>^ So they transported the Ark of the true God from A·binʹa·dab’s house on the hill, and A·hiʹo was walking ahead of the Ark.

[[v10-6-5]]

^<<v10-6-5,5>>^ David and all the house of Israel were celebrating before Jehovah with all sorts of juniper-wood instruments, harps, other stringed instruments, tambourines, sistrums, and cymbals.

[[v10-6-6]]

^<<v10-6-6,6>>^ But when they came to the threshing floor of Naʹcon, Uzʹzah thrust his hand out to the Ark of the true God and grabbed hold of it, for the cattle nearly upset it.

[[v10-6-7]]

^<<v10-6-7,7>>^ At that Jehovah’s anger blazed against Uzʹzah, and the true God struck him down there for his irreverent act, and he died there beside the Ark of the true God.

[[v10-6-8]]

^<<v10-6-8,8>>^ But David became angry^&#42;1^ because Jehovah’s wrath had broken through against Uzʹzah; and that place has been called Peʹrez-uzʹzah^&#42;2^ down to this day.

[NOTE]
====
. Or “upset.”
. Meaning “Breach Against Uzzah.”
====

[[v10-6-9]]

^<<v10-6-9,9>>^ So David became fearful of Jehovah on that day and said: “How can the Ark of Jehovah come to me?”

[[v10-6-10]]

^<<v10-6-10,10>>^ David was not willing to bring the Ark of Jehovah to where he was in the City of David. Instead, David had it taken to the house of Oʹbed-eʹdom the Gitʹtite.

[[v10-6-11]]

^<<v10-6-11,11>>^ The Ark of Jehovah remained at the house of Oʹbed-eʹdom the Gitʹtite for three months, and Jehovah kept blessing Oʹbed-eʹdom and all his household.

[[v10-6-12]]

^<<v10-6-12,12>>^ The report was made to King David: “Jehovah has blessed the house of Oʹbed-eʹdom and all that belongs to him because of the Ark of the true God.” So David went to bring the Ark of the true God from the house of Oʹbed-eʹdom up to the City of David with rejoicing.

[[v10-6-13]]

^<<v10-6-13,13>>^ When the carriers of the Ark of Jehovah had marched six steps, he sacrificed a bull and a fattened animal.

[[v10-6-14]]

^<<v10-6-14,14>>^ David was dancing around before Jehovah with all his might; all the while David wore^&#42;1^ a linen ephʹod.

[NOTE]
====
. Lit., “was girded with.”
====

[[v10-6-15]]

^<<v10-6-15,15>>^ David and all the house of Israel were bringing up the Ark of Jehovah with joyful shouting and with the sound of the horn.

[[v10-6-16]]

^<<v10-6-16,16>>^ But when the Ark of Jehovah came into the City of David, Saul’s daughter Miʹchal looked down through the window and saw King David leaping and dancing around before Jehovah; and she began to despise him in her heart.

[[v10-6-17]]

^<<v10-6-17,17>>^ So they brought the Ark of Jehovah in and set it in its place inside the tent that David had pitched for it. Then David offered up burnt offerings and communion sacrifices before Jehovah.

[[v10-6-18]]

^<<v10-6-18,18>>^ When David finished offering up the burnt offerings and the communion sacrifices, he blessed the people in the name of Jehovah of armies.

[[v10-6-19]]

^<<v10-6-19,19>>^ Further, he distributed to all the people, to the whole multitude of Israel, to each man and woman, a ring-shaped loaf of bread, a date cake, and a raisin cake, and then all the people left, each to his own house.

[[v10-6-20]]

^<<v10-6-20,20>>^ When David returned to bless his own household, Saul’s daughter Miʹchal came out to meet him. She said: “How glorious the king of Israel made himself when he uncovered himself today before the eyes of the slave girls of his servants, just as an empty-headed man openly uncovers himself!”

[[v10-6-21]]

^<<v10-6-21,21>>^ At this David said to Miʹchal: “My celebration was before Jehovah, who chose me rather than your father and all his household and who appointed me as leader over Jehovah’s people, Israel. Therefore, I will celebrate before Jehovah,

[[v10-6-22]]

^<<v10-6-22,22>>^ and I will humble myself even more than this and become low even in my own eyes. But by the slave girls whom you mentioned, I will be glorified.”

[[v10-6-23]]

^<<v10-6-23,23>>^ So Saul’s daughter Miʹchal had no children down to the day of her death.

'''

xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[&#60; Capítulo Anterior] | <<v10-6-0,Topo>> | xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[Próximo Capítulo &#62;]