include::./index.adoc[]

[[v10-23-0]]
=== The Second of Samuel, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-23-1]]

^<<v10-23-1,1>>^ These are the last words of David:
“The word of David the son of Jesʹse,
And the word of the man who was raised on high,
The anointed of the God of Jacob,
The pleasant singer^&#42;1^ of the songs of Israel.

[NOTE]
====
. Or “The pleasant one.”
====

[[v10-23-2]]

^<<v10-23-2,2>>^ The spirit of Jehovah spoke through me;
His word was on my tongue.

[[v10-23-3]]

^<<v10-23-3,3>>^ The God of Israel spoke;
To me the Rock of Israel said:
‘When the one ruling over mankind is righteous,
Ruling in the fear of God,

[[v10-23-4]]

^<<v10-23-4,4>>^ It is like the morning light when the sun shines,
A morning without clouds.
It is like the brightness after the rain,
Making grass sprout from the earth.’

[[v10-23-5]]

^<<v10-23-5,5>>^ Is not my house like that before God?
For he has made an eternal covenant with me,
Arranged in every detail and secured.
Because it means my complete salvation and all my delight,
Is that not why he makes it flourish?

[[v10-23-6]]

^<<v10-23-6,6>>^ But worthless men are all thrown away like thornbushes,
For they cannot be taken with the hand.

[[v10-23-7]]

^<<v10-23-7,7>>^ When a man touches them,
He should be fully armed with iron and the shaft of a spear,
And they should be completely burned up with fire in their place.”

[[v10-23-8]]

^<<v10-23-8,8>>^ These are the names of David’s mighty warriors: Joʹsheb-bas·sheʹbeth a Tah·cheʹmo·nite, the head of the three. He brandished his spear over 800 slain at one time.

[[v10-23-9]]

^<<v10-23-9,9>>^ Next to him, El·e·aʹzar the son of Doʹdo the son of A·hoʹhi was among the three mighty warriors with David when they taunted the Phi·lisʹtines. They had gathered there for the battle, and when the men of Israel retreated,

[[v10-23-10]]

^<<v10-23-10,10>>^ he stood his ground and kept striking down the Phi·lisʹtines until his arm grew weary and his hand became stiff from gripping the sword. So Jehovah brought about a great victory^&#42;1^ on that day; and the people returned behind him to strip the slain.

[NOTE]
====
. Or “salvation.”
====

[[v10-23-11]]

^<<v10-23-11,11>>^ Next to him was Shamʹmah the son of Aʹgee the Harʹa·rite. The Phi·lisʹtines gathered together at Leʹhi, where there was a plot of land full of lentils; and the people fled because of the Phi·lisʹtines.

[[v10-23-12]]

^<<v10-23-12,12>>^ But he took his stand in the middle of the field and defended it and kept striking down the Phi·lisʹtines, so that Jehovah brought about a great victory.^&#42;1^

[NOTE]
====
. Or “salvation.”
====

[[v10-23-13]]

^<<v10-23-13,13>>^ Three of the 30 headmen went down during the harvest to David at the cave of A·dulʹlam, and a company^&#42;1^ of the Phi·lisʹtines was camped in the Valley^&#42;2^ of Rephʹa·im.

[NOTE]
====
. Or “tent village.”
. Or “Low Plain.”
====

[[v10-23-14]]

^<<v10-23-14,14>>^ David was then in the stronghold, and an outpost of the Phi·lisʹtines was in Bethʹle·hem.

[[v10-23-15]]

^<<v10-23-15,15>>^ Then David expressed his longing: “If only I could have a drink of the water from the cistern by the gate of Bethʹle·hem!”

[[v10-23-16]]

^<<v10-23-16,16>>^ At that the three mighty warriors forced their way into the camp of the Phi·lisʹtines and drew water from the cistern by the gate of Bethʹle·hem and brought it to David; but he refused to drink it and poured it out to Jehovah.

[[v10-23-17]]

^<<v10-23-17,17>>^ He said: “It is unthinkable on my part, O Jehovah, that I should do this! Should I drink the blood of the men going at the risk of their lives?”^&#42;1^ So he refused to drink it. These are the things that his three mighty warriors did.

[NOTE]
====
. Or “souls?”
====

[[v10-23-18]]

^<<v10-23-18,18>>^ A·bishʹai the brother of Joʹab the son of Ze·ruʹiah was the head of another three; he brandished his spear over 300 slain, and he had a reputation like the three.

[[v10-23-19]]

^<<v10-23-19,19>>^ Although he was the most distinguished of the other three and he was their chief, he did not attain to the rank of the first three.

[[v10-23-20]]

^<<v10-23-20,20>>^ Be·naiʹah the son of Je·hoiʹa·da was a courageous man^&#42;1^ who performed many exploits in Kabʹze·el. He struck down the two sons of Arʹi·el of Moʹab, and he descended into a waterpit on a snowy day and killed a lion.

[NOTE]
====
. Lit., “the son of a man of valor.”
====

[[v10-23-21]]

^<<v10-23-21,21>>^ He also struck down an Egyptian man of extraordinary size. Though the Egyptian had a spear in his hand, he went against him with a rod and snatched the spear away from the Egyptian’s hand and killed him with his own spear.

[[v10-23-22]]

^<<v10-23-22,22>>^ These things Be·naiʹah the son of Je·hoiʹa·da did, and he had a reputation like that of the three mighty warriors.

[[v10-23-23]]

^<<v10-23-23,23>>^ Although he was distinguished even more than the thirty, he did not attain to the rank of the three. However, David appointed him over his own bodyguard.

[[v10-23-24]]

^<<v10-23-24,24>>^ Asʹa·hel the brother of Joʹab was among the thirty: El·haʹnan the son of Doʹdo of Bethʹle·hem,

[[v10-23-25]]

^<<v10-23-25,25>>^ Shamʹmah the Haʹrod·ite, E·liʹka the Haʹrod·ite,

[[v10-23-26]]

^<<v10-23-26,26>>^ Heʹlez the Palʹtite, Iʹra the son of Ikʹkesh the Te·koʹite,

[[v10-23-27]]

^<<v10-23-27,27>>^ Abi-eʹzer the Anʹa·thoth·ite, Me·bunʹnai the Huʹshath·ite,

[[v10-23-28]]

^<<v10-23-28,28>>^ Zalʹmon the A·hoʹhite, Maʹha·rai the Ne·tophʹa·thite,

[[v10-23-29]]

^<<v10-23-29,29>>^ Heʹleb the son of Baʹa·nah the Ne·tophʹa·thite, Itʹtai the son of Riʹbai of Gibʹe·ah of the Benʹja·min·ites,

[[v10-23-30]]

^<<v10-23-30,30>>^ Be·naiʹah a Pirʹa·thon·ite, Hidʹdai of the wadis^&#42;1^ of Gaʹash,

[NOTE]
====
. See Glossary.
====

[[v10-23-31]]

^<<v10-23-31,31>>^ Aʹbi-alʹbon the Arʹbath·ite, Azʹma·veth the Bar-huʹmite,

[[v10-23-32]]

^<<v10-23-32,32>>^ E·liʹah·ba the Sha·alʹbo·nite, the sons of Jaʹshen, Jonʹa·than,

[[v10-23-33]]

^<<v10-23-33,33>>^ Shamʹmah the Harʹa·rite, A·hiʹam the son of Shaʹrar the Harʹa·rite,

[[v10-23-34]]

^<<v10-23-34,34>>^ E·liphʹe·let the son of A·hasʹbai the son of the Ma·acʹa·thite, E·liʹam the son of A·hithʹo·phel the Giʹlon·ite,

[[v10-23-35]]

^<<v10-23-35,35>>^ Hezʹro the Carʹmel·ite, Paʹa·rai the Arʹbite,

[[v10-23-36]]

^<<v10-23-36,36>>^ Iʹgal the son of Nathan of Zoʹbah, Baʹni the Gadʹite,

[[v10-23-37]]

^<<v10-23-37,37>>^ Zeʹlek the Amʹmon·ite, Naʹha·rai the Be·erʹoth·ite, the armor-bearer of Joʹab the son of Ze·ruʹiah,

[[v10-23-38]]

^<<v10-23-38,38>>^ Iʹra the Ithʹrite, Gaʹreb the Ithʹrite,

[[v10-23-39]]

^<<v10-23-39,39>>^ and U·riʹah the Hitʹtite—37 in all.

'''

xref:010-2-samuel/010-2-samuel-022.adoc#v10-22-0[&#60; Capítulo Anterior] | <<v10-23-0,Topo>> | xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[Próximo Capítulo &#62;]