include::./index.adoc[]

[[v10-24-0]]
=== The Second of Samuel, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-24-1]]

^<<v10-24-1,1>>^ The anger of Jehovah again blazed against Israel when one incited David^&#42;1^ against them, saying: “Go, take a count of Israel and Judah.”

[NOTE]
====
. Or “when David was incited.”
====

[[v10-24-2]]

^<<v10-24-2,2>>^ So the king said to Joʹab the chief of the army who was with him: “Please go through all the tribes of Israel, from Dan to Beʹer-sheʹba, and register the people, so that I may know the number of the people.”

[[v10-24-3]]

^<<v10-24-3,3>>^ But Joʹab said to the king: “May Jehovah your God multiply the people 100 times, and may the eyes of my lord the king see it, but why does my lord the king want to do such a thing?”

[[v10-24-4]]

^<<v10-24-4,4>>^ But the king’s word prevailed over Joʹab and the chiefs of the army. So Joʹab and the chiefs of the army went out from before the king to register the people of Israel.

[[v10-24-5]]

^<<v10-24-5,5>>^ They crossed the Jordan and camped at A·roʹer, to the right^&#42;1^ of the city in the middle of the valley,^&#42;2^ and they went toward the Gadʹites and on to Jaʹzer.

[NOTE]
====
. Or “the south.”
. Or “wadi.”
====

[[v10-24-6]]

^<<v10-24-6,6>>^ After that they went on to Gilʹe·ad and the land of Tahʹtim-hodʹshi and continued to Dan-jaʹan and went around to Siʹdon.

[[v10-24-7]]

^<<v10-24-7,7>>^ Then they went to the fortress of Tyre and all the cities of the Hiʹvites and of the Caʹnaan·ites, and finally they ended up in the Negʹeb of Judah at Beʹer-sheʹba.

[[v10-24-8]]

^<<v10-24-8,8>>^ Thus they went through all the land and came to Jerusalem at the end of nine months and 20 days.

[[v10-24-9]]

^<<v10-24-9,9>>^ Joʹab now gave to the king the number of the people who were registered. Israel amounted to 800,000 warriors armed with swords, and the men of Judah were 500,000.

[[v10-24-10]]

^<<v10-24-10,10>>^ But David’s heart^&#42;1^ was struck with remorse after he had numbered the people. David then said to Jehovah: “I have sinned greatly by doing this. And now, Jehovah, please forgive your servant’s error, for I have acted very foolishly.”

[NOTE]
====
. Or “conscience.”
====

[[v10-24-11]]

^<<v10-24-11,11>>^ When David got up in the morning, Jehovah’s word came to Gad the prophet, David’s visionary, saying:

[[v10-24-12]]

^<<v10-24-12,12>>^ “Go and say to David, ‘This is what Jehovah says: “I am giving you three options. Choose the one that I should bring on you.”’”

[[v10-24-13]]

^<<v10-24-13,13>>^ So Gad came in to David and told him: “Should seven years of famine come on your land? Or should you flee for three months from your adversaries while they pursue you? Or should there be three days of pestilence in your land? Now consider carefully what I should reply to the One who sent me.”

[[v10-24-14]]

^<<v10-24-14,14>>^ So David said to Gad: “It is very distressing to me. Let us fall, please, into the hand of Jehovah, for his mercy is great; but do not let me fall into the hand of man.”

[[v10-24-15]]

^<<v10-24-15,15>>^ Then Jehovah sent a pestilence on Israel from the morning until the designated time, so that 70,000 of the people from Dan to Beʹer-sheʹba died.

[[v10-24-16]]

^<<v10-24-16,16>>^ When the angel stretched out his hand toward Jerusalem to destroy it, Jehovah felt regret^&#42;1^ over the calamity, and he said to the angel bringing destruction among the people: “It is enough! Now let your hand drop.” Jehovah’s angel was close to the threshing floor of A·rauʹnah the Jebʹu·site.

[NOTE]
====
. Or “grieved.”
====

[[v10-24-17]]

^<<v10-24-17,17>>^ When David saw the angel who was striking the people down, he said to Jehovah: “I am the one who sinned, and I am the one who did wrong; but these sheep—what have they done? Let your hand, please, come against me and my father’s house.”

[[v10-24-18]]

^<<v10-24-18,18>>^ So Gad came in to David on that day and said to him: “Go up, set up for Jehovah an altar on the threshing floor of A·rauʹnah the Jebʹu·site.”

[[v10-24-19]]

^<<v10-24-19,19>>^ So David went up at the word of Gad, as Jehovah had commanded.

[[v10-24-20]]

^<<v10-24-20,20>>^ When A·rauʹnah looked down and saw the king and his servants coming toward him, A·rauʹnah immediately went out and bowed down to the king with his face to the ground.

[[v10-24-21]]

^<<v10-24-21,21>>^ A·rauʹnah asked: “Why has my lord the king come to his servant?” David replied: “To buy from you the threshing floor in order to build an altar to Jehovah, so that the scourge against the people may be halted.”

[[v10-24-22]]

^<<v10-24-22,22>>^ But A·rauʹnah said to David: “Let my lord the king take it and offer up what seems good to him.^&#42;1^ Here are cattle for the burnt offering and the threshing sledge and the equipment of the cattle for the wood.

[NOTE]
====
. Lit., “what is good in his eyes.”
====

[[v10-24-23]]

^<<v10-24-23,23>>^ All of this, O king, A·rauʹnah gives to the king.” Then A·rauʹnah said to the king: “May Jehovah your God show you favor.”

[[v10-24-24]]

^<<v10-24-24,24>>^ However, the king said to A·rauʹnah: “No, I must buy it from you for a price. I will not offer up to Jehovah my God burnt sacrifices that cost me nothing.” So David bought the threshing floor and the cattle for 50 silver shekels.^&#42;1^

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v10-24-25]]

^<<v10-24-25,25>>^ And David built an altar there to Jehovah and offered up burnt sacrifices and communion sacrifices. Jehovah then responded to the entreaty for the land, and the scourge against Israel was halted.

'''

xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[&#60; Capítulo Anterior] | <<v10-24-0,Topo>> | xref:011-1-kings/011-1-kings-001.adoc#v11-1-0[Próximo Capítulo &#62;]