include::./index.adoc[]

[[v10-22-0]]
=== The Second of Samuel, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-22-1]]

^<<v10-22-1,1>>^ And David spoke to Jehovah the words of this song in the day that Jehovah rescued him out of the hand of all his enemies and out of Saul’s hand.

[[v10-22-2]]

^<<v10-22-2,2>>^ He said:
“Jehovah is my crag and my stronghold and the One who rescues me.

[[v10-22-3]]

^<<v10-22-3,3>>^ My God is my rock, in whom I take refuge,
My shield and my horn^&#42;1^ of salvation,^&#42;2^ my secure refuge^&#42;3^
And my place to flee, my savior; you who save me from violence.

[NOTE]
====
. See Glossary.
. Or “my powerful savior.”
. Or “secure height.”
====

[[v10-22-4]]

^<<v10-22-4,4>>^ I call on Jehovah, who is worthy of praise,
And I will be saved from my enemies.

[[v10-22-5]]

^<<v10-22-5,5>>^ The waves of death broke all around me;
Flash floods of worthless men terrified me.

[[v10-22-6]]

^<<v10-22-6,6>>^ The ropes of the Grave^&#42;1^ surrounded me;
The snares of death confronted me.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v10-22-7]]

^<<v10-22-7,7>>^ In my distress I called on Jehovah,
To my God I kept calling.
Then from his temple he heard my voice,
And my cry for help reached his ears.

[[v10-22-8]]

^<<v10-22-8,8>>^ Back and forth the earth began to shake and rock;
The foundations of the heavens trembled
And shook back and forth because he had been angered.

[[v10-22-9]]

^<<v10-22-9,9>>^ Smoke ascended from his nostrils,
And a consuming fire came from his mouth;
Glowing coals blazed from him.

[[v10-22-10]]

^<<v10-22-10,10>>^ He made the heavens bend as he descended,
And thick gloom was beneath his feet.

[[v10-22-11]]

^<<v10-22-11,11>>^ He rode on a cherub and came flying.
He was visible on the wings of a spirit.^&#42;1^

[NOTE]
====
. Or “of the wind.”
====

[[v10-22-12]]

^<<v10-22-12,12>>^ Then he put darkness around him as a shelter,
In dark waters and thick clouds.

[[v10-22-13]]

^<<v10-22-13,13>>^ From the brightness before him fiery coals blazed.

[[v10-22-14]]

^<<v10-22-14,14>>^ Then Jehovah began to thunder from heaven;
The Most High made his voice heard.

[[v10-22-15]]

^<<v10-22-15,15>>^ He shot his arrows and scattered them;
Lightning, and he threw them into confusion.

[[v10-22-16]]

^<<v10-22-16,16>>^ The bed of the sea became visible;
The foundations of the land were exposed by the rebuke of Jehovah,
By the blast of the breath from his nostrils.

[[v10-22-17]]

^<<v10-22-17,17>>^ He reached down from on high;
He took hold of me and pulled me from deep waters.

[[v10-22-18]]

^<<v10-22-18,18>>^ He rescued me from my strong enemy,
From those hating me, who were stronger than I was.

[[v10-22-19]]

^<<v10-22-19,19>>^ They confronted me on the day of my disaster,
But Jehovah was my support.

[[v10-22-20]]

^<<v10-22-20,20>>^ He brought me out into a place of safety;^&#42;1^
He rescued me because he was pleased with me.

[NOTE]
====
. Or “a roomy place.”
====

[[v10-22-21]]

^<<v10-22-21,21>>^ Jehovah rewards me according to my righteousness;
He repays me according to the innocence^&#42;1^ of my hands.

[NOTE]
====
. Lit., “the cleanness.”
====

[[v10-22-22]]

^<<v10-22-22,22>>^ For I have kept the ways of Jehovah,
And I have not wickedly abandoned my God.

[[v10-22-23]]

^<<v10-22-23,23>>^ All his judgments are before me;
I will not deviate from his statutes.

[[v10-22-24]]

^<<v10-22-24,24>>^ I will remain blameless before him,
And I will keep myself from error.

[[v10-22-25]]

^<<v10-22-25,25>>^ May Jehovah repay me according to my righteousness,
According to my innocence before him.

[[v10-22-26]]

^<<v10-22-26,26>>^ With someone loyal you act in loyalty;
With the blameless, mighty man, you deal blamelessly;

[[v10-22-27]]

^<<v10-22-27,27>>^ With the pure you show yourself pure,
But with the crooked you show yourself shrewd.^&#42;1^

[NOTE]
====
. Or possibly, “act as silly.”
====

[[v10-22-28]]

^<<v10-22-28,28>>^ For you save those who are humble,
But your eyes are against the haughty, and you abase them.

[[v10-22-29]]

^<<v10-22-29,29>>^ For you are my lamp, O Jehovah;
It is Jehovah who lights up my darkness.

[[v10-22-30]]

^<<v10-22-30,30>>^ With your help I can charge against a marauder band;
By God’s power I can scale a wall.

[[v10-22-31]]

^<<v10-22-31,31>>^ The way of the true God is perfect;
The saying of Jehovah is refined.
He is a shield to all those taking refuge in him.

[[v10-22-32]]

^<<v10-22-32,32>>^ For who is a God besides Jehovah?
And who is a rock except our God?

[[v10-22-33]]

^<<v10-22-33,33>>^ The true God is my strong fortress,
And he will make my way perfect.

[[v10-22-34]]

^<<v10-22-34,34>>^ He makes my feet like those of a deer;
He makes me stand on high places.

[[v10-22-35]]

^<<v10-22-35,35>>^ He trains my hands for warfare;
My arms can bend a bow of copper.

[[v10-22-36]]

^<<v10-22-36,36>>^ You give me your shield of salvation,
And your humility makes me great.

[[v10-22-37]]

^<<v10-22-37,37>>^ You widen the path for my footsteps;
My feet^&#42;1^ will not slip.

[NOTE]
====
. Or “ankles.”
====

[[v10-22-38]]

^<<v10-22-38,38>>^ I will pursue my enemies and annihilate them;
I will not return until they are wiped out.

[[v10-22-39]]

^<<v10-22-39,39>>^ And I will wipe them out and crush them, so that they will not rise up;
They will fall under my feet.

[[v10-22-40]]

^<<v10-22-40,40>>^ You will equip me with strength for the battle;
You will make my foes collapse under me.

[[v10-22-41]]

^<<v10-22-41,41>>^ You will make my enemies retreat from me;^&#42;1^
I will put an end to^&#42;2^ those who hate me.

[NOTE]
====
. Or “You will give me the backs of my enemies.”
. Lit., “silence.”
====

[[v10-22-42]]

^<<v10-22-42,42>>^ They cry for help, but there is no one to save them;
They even cry to Jehovah, but he does not answer them.

[[v10-22-43]]

^<<v10-22-43,43>>^ I will pound them as fine as the dust of the earth;
I will pulverize and trample them like mud in the streets.

[[v10-22-44]]

^<<v10-22-44,44>>^ You will rescue me from the faultfinding of my people.
You will safeguard me to be the head of nations;
A people whom I have not known will serve me.

[[v10-22-45]]

^<<v10-22-45,45>>^ Foreigners will come cringing before me;
What they hear about me will make them obey me.^&#42;1^

[NOTE]
====
. Lit., “At the hearing of the ear, they will obey me.”
====

[[v10-22-46]]

^<<v10-22-46,46>>^ Foreigners will lose courage;^&#42;1^
They will come trembling from their strongholds.

[NOTE]
====
. Or “fade away.”
====

[[v10-22-47]]

^<<v10-22-47,47>>^ Jehovah is alive! Praised be my Rock!
Let the God of the rock of my salvation be exalted.

[[v10-22-48]]

^<<v10-22-48,48>>^ The true God executes vengeance for me;
He subdues the peoples under me;

[[v10-22-49]]

^<<v10-22-49,49>>^ He rescues me from my enemies.
You lift me high above those who attack me;
You save me from the man of violence.

[[v10-22-50]]

^<<v10-22-50,50>>^ That is why I will thank you, O Jehovah, among the nations,
And to your name I will sing praises:^&#42;1^

[NOTE]
====
. Or “make music.”
====

[[v10-22-51]]

^<<v10-22-51,51>>^ He performs great acts of salvation^&#42;1^ for his king;
He displays loyal love to his anointed one,
To David and his offspring^&#42;2^ forever.”

[NOTE]
====
. Or “great victories.”
. Lit., “seed.”
====

'''

xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[&#60; Capítulo Anterior] | <<v10-22-0,Topo>> | xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[Próximo Capítulo &#62;]