include::./index.adoc[]

[[v10-17-0]]
=== The Second of Samuel, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-17-1]]

^<<v10-17-1,1>>^ A·hithʹo·phel then said to Abʹsa·lom: “Please let me choose 12,000 men and rise up and chase after David tonight.

[[v10-17-2]]

^<<v10-17-2,2>>^ I will come upon him when he is weary and powerless,^&#42;1^ and I will throw him into a panic; and all the people who are with him will flee, and I will strike down only the king.

[NOTE]
====
. Or “feeble in both hands.”
====

[[v10-17-3]]

^<<v10-17-3,3>>^ Then I will bring all the people back to you. The return of all the people depends on what happens with the man you are seeking. Then all the people will be at peace.”

[[v10-17-4]]

^<<v10-17-4,4>>^ The proposal was just right in the eyes of Abʹsa·lom and all the elders of Israel.

[[v10-17-5]]

^<<v10-17-5,5>>^ However, Abʹsa·lom said: “Please call Huʹshai the Arʹchite as well, and let us hear what he has to say.”

[[v10-17-6]]

^<<v10-17-6,6>>^ So Huʹshai came in to Abʹsa·lom. Then Abʹsa·lom said to him: “This is the advice A·hithʹo·phel gave. Should we act on his advice? If not, you tell us.”

[[v10-17-7]]

^<<v10-17-7,7>>^ At this Huʹshai said to Abʹsa·lom: “The advice that A·hithʹo·phel gave is not good in this instance!”

[[v10-17-8]]

^<<v10-17-8,8>>^ Huʹshai continued: “You well know that your father and his men are mighty, and they are desperate,^&#42;1^ like a bear that has lost her cubs in the field. Moreover, your father is a warrior, and he will not spend the night with the people.

[NOTE]
====
. Or “bitter of soul.”
====

[[v10-17-9]]

^<<v10-17-9,9>>^ At this very moment he is hiding in one of the caves^&#42;1^ or in some other place; and if he attacks first, those hearing of it will say, ‘The people following Abʹsa·lom have been defeated!’

[NOTE]
====
. Or “pits; ravines.”
====

[[v10-17-10]]

^<<v10-17-10,10>>^ Even the courageous man whose heart is like that of a lion will surely melt in fear, for all Israel knows that your father is a mighty man and that the men with him are courageous.

[[v10-17-11]]

^<<v10-17-11,11>>^ I give this advice: Let all Israel be gathered to you, from Dan to Beʹer-sheʹba, as many as the grains of sand by the sea, and you should lead them into the fight.

[[v10-17-12]]

^<<v10-17-12,12>>^ We will come against him wherever he is found, and we will come upon him just like the dew that falls on the ground; and not one of them will survive, not he nor any of the men with him.

[[v10-17-13]]

^<<v10-17-13,13>>^ If he retreats into a city, all Israel will carry ropes to that city, and we will drag it down into the valley until not even a pebble is left.”

[[v10-17-14]]

^<<v10-17-14,14>>^ Then Abʹsa·lom and all the men of Israel said: “The advice of Huʹshai the Arʹchite is better than the advice of A·hithʹo·phel!” For Jehovah had determined^&#42;1^ to frustrate the sound advice of A·hithʹo·phel, so that Jehovah could bring disaster on Abʹsa·lom.

[NOTE]
====
. Or “commanded.”
====

[[v10-17-15]]

^<<v10-17-15,15>>^ Huʹshai later said to Zaʹdok and A·biʹa·thar the priests: “This is what A·hithʹo·phel has advised Abʹsa·lom and the elders of Israel, and this is what I have advised.

[[v10-17-16]]

^<<v10-17-16,16>>^ Now quickly send word to David and warn him: ‘Do not stay at the fords^&#42;1^ of the wilderness tonight, but cross over without fail, or the king and all the people with him may be wiped out.’”^&#42;2^

[NOTE]
====
. Or possibly, “the desert plains.”
. Lit., “swallowed up.”
====

[[v10-17-17]]

^<<v10-17-17,17>>^ Jonʹa·than and A·himʹa·az were staying at En-roʹgel; so a servant girl went off and told them and they went to tell King David, for they did not dare to be seen entering the city.

[[v10-17-18]]

^<<v10-17-18,18>>^ However, a young man saw them and told Abʹsa·lom. So the two of them quickly went off and came to the house of a man in Ba·huʹrim who had a well in his courtyard. They went down into it,

[[v10-17-19]]

^<<v10-17-19,19>>^ and the man’s wife spread a covering over the top of the well and covered it with cracked grain; no one knew about it.

[[v10-17-20]]

^<<v10-17-20,20>>^ The servants of Abʹsa·lom came to the woman at her house and asked: “Where are A·himʹa·az and Jonʹa·than?” The woman replied: “They passed by toward the water.” Then the men searched for them but did not find them, so they returned to Jerusalem.

[[v10-17-21]]

^<<v10-17-21,21>>^ After the men were gone, they came up out of the well and went and informed King David. They said to him: “Rise up and quickly cross the water, for this is what A·hithʹo·phel advised against you.”

[[v10-17-22]]

^<<v10-17-22,22>>^ Immediately David and all the people with him rose up and crossed the Jordan. By daybreak, there was no one left who had not crossed the Jordan.

[[v10-17-23]]

^<<v10-17-23,23>>^ When A·hithʹo·phel saw that his advice had not been acted on, he saddled a donkey and went to his house in his hometown. After he gave instructions to his household, he hanged^&#42;1^ himself. So he died and was buried in the burial place of his forefathers.

[NOTE]
====
. Or “strangled.”
====

[[v10-17-24]]

^<<v10-17-24,24>>^ Meanwhile, David went to Ma·ha·naʹim, and Abʹsa·lom crossed the Jordan with all the men of Israel.

[[v10-17-25]]

^<<v10-17-25,25>>^ Abʹsa·lom put A·maʹsa in charge of the army in place of Joʹab; A·maʹsa was the son of a man named Ithʹra the Israelite, who had relations with Abʹi·gail the daughter of Naʹhash, the sister of Ze·ruʹiah, Joʹab’s mother.

[[v10-17-26]]

^<<v10-17-26,26>>^ Israel and Abʹsa·lom camped in the land of Gilʹe·ad.

[[v10-17-27]]

^<<v10-17-27,27>>^ As soon as David came to Ma·ha·naʹim, Shoʹbi the son of Naʹhash from Rabʹbah of the Amʹmon·ites, Maʹchir the son of Amʹmi·el from Lo-deʹbar, and Bar·zilʹlai the Gilʹe·ad·ite from Ro·geʹlim

[[v10-17-28]]

^<<v10-17-28,28>>^ brought beds, basins, clay pots, wheat, barley, flour, roasted grain, broad beans, lentils, parched grain,

[[v10-17-29]]

^<<v10-17-29,29>>^ honey, butter, sheep, and cheese.^&#42;1^ They brought all of this out for David and the people with him to eat, for they said: “The people are hungry and tired and thirsty in the wilderness.”

[NOTE]
====
. Lit., “curds of cattle.”
====

'''

xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[&#60; Capítulo Anterior] | <<v10-17-0,Topo>> | xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[Próximo Capítulo &#62;]