include::./index.adoc[]

[[v10-13-0]]
=== The Second of Samuel, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-13-1]]

^<<v10-13-1,1>>^ Now David’s son Abʹsa·lom had a beautiful sister named Taʹmar, and David’s son Amʹnon fell in love with her.

[[v10-13-2]]

^<<v10-13-2,2>>^ Amʹnon was so distressed that he became sick because of his sister Taʹmar, for she was a virgin and it seemed impossible for Amʹnon to do anything to her.

[[v10-13-3]]

^<<v10-13-3,3>>^ Now Amʹnon had a companion named Je·honʹa·dab, the son of Shimʹe·ah, David’s brother; and Je·honʹa·dab was a very clever man.

[[v10-13-4]]

^<<v10-13-4,4>>^ So he said to him: “Why are you, the king’s son, so depressed every morning? Why not tell me?” Amʹnon replied to him: “I am in love with Taʹmar, the sister of my brother Abʹsa·lom.”

[[v10-13-5]]

^<<v10-13-5,5>>^ Je·honʹa·dab replied to him: “Lie down on your bed and pretend to be sick. When your father comes to see you, say to him, ‘Please, let my sister Taʹmar come and serve me some food. If she prepares the food given to the sick^&#42;1^ before my eyes, I will eat it from her hand.’”

[NOTE]
====
. Or “the bread of consolation.”
====

[[v10-13-6]]

^<<v10-13-6,6>>^ So Amʹnon lay down and pretended to be sick, and the king came in to see him. Then Amʹnon said to the king: “Please, let my sister Taʹmar come in and bake two heart-shaped cakes before my eyes so that I may take food from her hand.”

[[v10-13-7]]

^<<v10-13-7,7>>^ At that David sent a message to Taʹmar at the house, saying: “Please go to the house of your brother Amʹnon and prepare food^&#42;1^ for him.”

[NOTE]
====
. Or “the bread of consolation.”
====

[[v10-13-8]]

^<<v10-13-8,8>>^ So Taʹmar went to the house of her brother Amʹnon, where he was lying down. She took the dough and kneaded it into cakes before his eyes and cooked the cakes.

[[v10-13-9]]

^<<v10-13-9,9>>^ Then she took the pan and served him. But Amʹnon refused to eat and said: “Have everybody leave me!” So everybody left him.

[[v10-13-10]]

^<<v10-13-10,10>>^ Amʹnon now said to Taʹmar: “Bring the food^&#42;1^ into the bedroom, so that I may eat it from your hand.” So Taʹmar took the heart-shaped cakes that she had made and brought them to her brother Amʹnon in the bedroom.

[NOTE]
====
. Or “the bread of consolation.”
====

[[v10-13-11]]

^<<v10-13-11,11>>^ When she brought them for him to eat, he grabbed her and said: “Come, lie down with me, my sister.”

[[v10-13-12]]

^<<v10-13-12,12>>^ But she said to him: “No, my brother! Do not humiliate me, for such a thing is not done in Israel. Do not do this disgraceful thing.

[[v10-13-13]]

^<<v10-13-13,13>>^ How could I live down my shame? And you will be regarded as one of the disgraceful men in Israel. Now speak, please, to the king, for he will not withhold me from you.”

[[v10-13-14]]

^<<v10-13-14,14>>^ But he refused to listen to her, and he overpowered her and humiliated her by raping her.

[[v10-13-15]]

^<<v10-13-15,15>>^ Then Amʹnon began hating her with a very intense hatred, so that his hatred for her became greater than the love he had felt for her. Amʹnon said to her: “Get up; go away!”

[[v10-13-16]]

^<<v10-13-16,16>>^ At this she said to him: “No, my brother, for sending me away now is worse than what you have done with me!” But he refused to listen to her.

[[v10-13-17]]

^<<v10-13-17,17>>^ With that he called his young attendant and said: “Get this person out of my presence, please, and lock the door behind her.”

[[v10-13-18]]

^<<v10-13-18,18>>^ (Now she was wearing a special^&#42;1^ robe, for those were the garments that the virgin daughters of the king wore.) So his attendant led her outside, and he locked the door behind her.

[NOTE]
====
. Or “an ornamented.”
====

[[v10-13-19]]

^<<v10-13-19,19>>^ Then Taʹmar put ashes on her head, and she ripped apart the fine robe she was wearing; and she kept her hands on her head and walked off, crying out as she walked.

[[v10-13-20]]

^<<v10-13-20,20>>^ At this her brother Abʹsa·lom asked her: “Was it your brother Amʹnon who was with you? And now keep silent, my sister. He is your brother. Do not let your heart dwell on this matter.” Then Taʹmar lived in isolation at the house of her brother Abʹsa·lom.

[[v10-13-21]]

^<<v10-13-21,21>>^ When King David heard about all these things, he became very angry. But he would not hurt the feelings of Amʹnon his son, because he loved him, for he was his firstborn.

[[v10-13-22]]

^<<v10-13-22,22>>^ And Abʹsa·lom said nothing to Amʹnon, either bad or good; for Abʹsa·lom hated Amʹnon because he had humiliated his sister Taʹmar.

[[v10-13-23]]

^<<v10-13-23,23>>^ After two full years, Abʹsa·lom’s sheepshearers were at Baʹal-haʹzor, near Eʹphra·im, and Abʹsa·lom invited all the sons of the king.

[[v10-13-24]]

^<<v10-13-24,24>>^ So Abʹsa·lom came in to the king and said: “Your servant is having his sheep sheared. Please let the king and his servants go with me.”

[[v10-13-25]]

^<<v10-13-25,25>>^ But the king said to Abʹsa·lom: “No, my son. If all of us go, we will be a burden to you.” Although he kept urging him, he did not consent to go, but he blessed him.

[[v10-13-26]]

^<<v10-13-26,26>>^ Abʹsa·lom then said: “If not you, please let my brother Amʹnon go with us.” The king replied to him: “Why should he go with you?”

[[v10-13-27]]

^<<v10-13-27,27>>^ But Abʹsa·lom urged him, so he sent Amʹnon and all the king’s sons with him.

[[v10-13-28]]

^<<v10-13-28,28>>^ Then Abʹsa·lom ordered his attendants: “Watch, and when Amʹnon’s heart is in a cheerful mood from the wine, I will say to you, ‘Strike down Amʹnon!’ You must then put him to death. Do not be afraid. Is it not I who command you? Be strong and courageous.”

[[v10-13-29]]

^<<v10-13-29,29>>^ So Abʹsa·lom’s attendants did to Amʹnon exactly as Abʹsa·lom had ordered; then all the other sons of the king got up, and each one mounted his mule and fled.

[[v10-13-30]]

^<<v10-13-30,30>>^ While they were on the way, the report reached David: “Abʹsa·lom has struck down all the sons of the king, and not one of them survived.”

[[v10-13-31]]

^<<v10-13-31,31>>^ At this the king got up and ripped his clothes apart and lay on the ground, and all his servants were standing by with their garments ripped apart.

[[v10-13-32]]

^<<v10-13-32,32>>^ However, Je·honʹa·dab the son of Shimʹe·ah, David’s brother, said: “Do not let my lord think that they have killed all the young sons of the king, for only Amʹnon has died. This is by the order of Abʹsa·lom, who decided to do this from the day that Amʹnon humiliated his sister Taʹmar.

[[v10-13-33]]

^<<v10-13-33,33>>^ Now do not let my lord the king pay attention to^&#42;1^ the report that says, ‘All the king’s sons have died’; only Amʹnon has died.”

[NOTE]
====
. Lit., “take to his heart.”
====

[[v10-13-34]]

^<<v10-13-34,34>>^ Meanwhile, Abʹsa·lom ran away. Later the watchman raised his eyes and saw that there were many people coming from the road behind him next to the mountain.

[[v10-13-35]]

^<<v10-13-35,35>>^ At this Je·honʹa·dab said to the king: “Look! The king’s sons have returned. It is just as your servant said.”

[[v10-13-36]]

^<<v10-13-36,36>>^ As he finished speaking, the king’s sons came in, weeping loudly; also the king and all his servants wept very bitterly.

[[v10-13-37]]

^<<v10-13-37,37>>^ But Abʹsa·lom fled and went to Talʹmai the son of Am·miʹhud the king of Geshʹur. David mourned his son for many days.

[[v10-13-38]]

^<<v10-13-38,38>>^ After Abʹsa·lom fled and went to Geshʹur, he stayed there for three years.

[[v10-13-39]]

^<<v10-13-39,39>>^ Finally King David longed to go to Abʹsa·lom, for he had become reconciled to^&#42;1^ the death of Amʹnon.

[NOTE]
====
. Or “had found consolation over.”
====

'''

xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[&#60; Capítulo Anterior] | <<v10-13-0,Topo>> | xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[Próximo Capítulo &#62;]