include::./index.adoc[]

[[v10-5-0]]
=== The Second of Samuel, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-5-1]]

^<<v10-5-1,1>>^ In time all the tribes of Israel came to David at Hebʹron and said: “Look! We are your own bone and flesh.^&#42;1^

[NOTE]
====
. Or “your blood relatives.”
====

[[v10-5-2]]

^<<v10-5-2,2>>^ In times past while Saul was our king, you were the one who was leading Israel on its campaigns.^&#42;1^ And Jehovah said to you: ‘You will shepherd my people Israel, and you will become leader over Israel.’”

[NOTE]
====
. Lit., “the one bringing out and the one bringing in Israel.”
====

[[v10-5-3]]

^<<v10-5-3,3>>^ So all the elders of Israel came to the king at Hebʹron, and King David made a covenant with them in Hebʹron before Jehovah. Then they anointed David as king over Israel.

[[v10-5-4]]

^<<v10-5-4,4>>^ David was 30 years old when he became king, and he reigned for 40 years.

[[v10-5-5]]

^<<v10-5-5,5>>^ In Hebʹron he reigned over Judah for 7 years and 6 months, and in Jerusalem he reigned for 33 years over all Israel and Judah.

[[v10-5-6]]

^<<v10-5-6,6>>^ And the king and his men set out for Jerusalem against the Jebʹu·sites who were inhabiting the land. They taunted David: “You will never come in here! Even the blind and the lame will drive you away.” They thought, ‘David will never get in here.’

[[v10-5-7]]

^<<v10-5-7,7>>^ However, David captured the stronghold of Zion, which is now the City of David.

[[v10-5-8]]

^<<v10-5-8,8>>^ So David said on that day: “Those who attack the Jebʹu·sites should go through the water tunnel to strike down both ‘the lame and the blind,’ who are hateful to David!”^&#42;1^ That is why it is said: “The blind and the lame will never enter the house.”

[NOTE]
====
. Or “the soul of David.”
====

[[v10-5-9]]

^<<v10-5-9,9>>^ Then David took up residence in the stronghold, and it was called^&#42;1^ the City of David; and David began to build all around from the Mound^&#42;2^ inward.

[NOTE]
====
. Or possibly, “and he called it.”
. Or “Millo.” A Hebrew term meaning “fill.”
====

[[v10-5-10]]

^<<v10-5-10,10>>^ Thus David became greater and greater, and Jehovah the God of armies was with him.

[[v10-5-11]]

^<<v10-5-11,11>>^ King Hiʹram of Tyre sent messengers to David, also cedar timbers, woodworkers, and stonemasons for building walls, and they began to build a house^&#42;1^ for David.

[NOTE]
====
. Or “palace.”
====

[[v10-5-12]]

^<<v10-5-12,12>>^ And David knew that Jehovah had firmly established him as king over Israel and had exalted his kingdom for the sake of His people Israel.

[[v10-5-13]]

^<<v10-5-13,13>>^ David took more concubines and wives in Jerusalem after he came from Hebʹron, and more sons and daughters were born to David.

[[v10-5-14]]

^<<v10-5-14,14>>^ These are the names of those born to him in Jerusalem: Sham·muʹa, Shoʹbab, Nathan, Solʹo·mon,

[[v10-5-15]]

^<<v10-5-15,15>>^ Ibʹhar, E·liʹshu·a, Neʹpheg, Ja·phiʹa,

[[v10-5-16]]

^<<v10-5-16,16>>^ E·lishʹa·ma, E·liʹa·da, and E·liphʹe·let.

[[v10-5-17]]

^<<v10-5-17,17>>^ When the Phi·lisʹtines heard that David had been anointed as king over Israel, all the Phi·lisʹtines came up to search for David. When David heard about it, he went down to the stronghold.

[[v10-5-18]]

^<<v10-5-18,18>>^ Then the Phi·lisʹtines came in and spread out in the Valley^&#42;1^ of Rephʹa·im.

[NOTE]
====
. Or “Low Plain.”
====

[[v10-5-19]]

^<<v10-5-19,19>>^ David inquired of Jehovah, saying: “Should I go up against the Phi·lisʹtines? Will you give them into my hand?” At this Jehovah said to David: “Go up, for I will surely give the Phi·lisʹtines into your hand.”

[[v10-5-20]]

^<<v10-5-20,20>>^ So David came to Baʹal-pe·raʹzim, and David struck them down there. At that he said: “Jehovah has broken through my enemies before me, like a breach made by waters.” That is why he named that place Baʹal-pe·raʹzim.^&#42;1^

[NOTE]
====
. Meaning “Master of Breakings Through.”
====

[[v10-5-21]]

^<<v10-5-21,21>>^ The Phi·lisʹtines abandoned their idols there, and David and his men took them away.

[[v10-5-22]]

^<<v10-5-22,22>>^ Later the Phi·lisʹtines came up once again and spread out in the Valley^&#42;1^ of Rephʹa·im.

[NOTE]
====
. Or “Low Plain.”
====

[[v10-5-23]]

^<<v10-5-23,23>>^ David inquired of Jehovah, but He said: “Do not go directly up. Instead, go around behind them, and come against them in front of the baʹca bushes.

[[v10-5-24]]

^<<v10-5-24,24>>^ And when you hear the sound of marching in the tops of the baʹca bushes, then act decisively, for Jehovah will have gone out before you to strike down the army of the Phi·lisʹtines.”

[[v10-5-25]]

^<<v10-5-25,25>>^ So David did just as Jehovah commanded him, and he struck down the Phi·lisʹtines from Geʹba all the way to Geʹzer.

'''

xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[&#60; Capítulo Anterior] | <<v10-5-0,Topo>> | xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[Próximo Capítulo &#62;]