include::./index.adoc[]

[[v10-21-0]]
=== The Second of Samuel, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-21-1]]

^<<v10-21-1,1>>^ Now there was a famine in the days of David for three consecutive years, so David consulted Jehovah, and Jehovah said: “There is bloodguilt on Saul and on his house, because he put the Gibʹe·on·ites to death.”

[[v10-21-2]]

^<<v10-21-2,2>>^ So the king called the Gibʹe·on·ites and spoke to them. (Incidentally, the Gibʹe·on·ites were not Israelites but Amʹor·ites who remained, and the Israelites had sworn to spare them, but Saul sought to strike them down in his zeal for the people of Israel and Judah.)

[[v10-21-3]]

^<<v10-21-3,3>>^ David said to the Gibʹe·on·ites: “What should I do for you, and how can I make atonement, so that you will bless the inheritance of Jehovah?”

[[v10-21-4]]

^<<v10-21-4,4>>^ The Gibʹe·on·ites said to him: “It is not a matter of silver or gold for us in connection with Saul and his household; nor can we put any man to death in Israel.” At that he said: “Whatever you say, I will do for you.”

[[v10-21-5]]

^<<v10-21-5,5>>^ They said to the king: “The man who exterminated us and schemed to annihilate us from living anywhere in the territory of Israel—

[[v10-21-6]]

^<<v10-21-6,6>>^ let seven of his sons be given to us. We will hang their dead bodies^&#42;1^ before Jehovah in Gibʹe·ah of Saul, the chosen one of Jehovah.” The king then said: “I will hand them over.”

[NOTE]
====
. Lit., “will expose them,” that is, with arms and legs broken.
====

[[v10-21-7]]

^<<v10-21-7,7>>^ However, the king showed compassion for Me·phibʹo·sheth, the son of Jonʹa·than the son of Saul, because of the oath made before Jehovah between David and Jonʹa·than, the son of Saul.

[[v10-21-8]]

^<<v10-21-8,8>>^ So the king took Ar·moʹni and Me·phibʹo·sheth, the two sons of Rizʹpah the daughter of Aʹiah whom she bore to Saul, and the five sons of Miʹchal^&#42;1^ the daughter of Saul whom she bore to Aʹdri·el the son of Bar·zilʹlai the Me·holʹath·ite.

[NOTE]
====
. Or possibly, “Merab.”
====

[[v10-21-9]]

^<<v10-21-9,9>>^ Then he handed them over to the Gibʹe·on·ites, and they hung their dead bodies on the mountain before Jehovah. All seven of them died together; they were put to death in the first days of harvest, at the start of the barley harvest.

[[v10-21-10]]

^<<v10-21-10,10>>^ Then Rizʹpah the daughter of Aʹiah took sackcloth and spread it out on the rock from the start of harvest until rain poured down from the heavens on the bodies; she did not allow the birds of the heavens to land on them by day nor the wild beasts of the field to come near by night.

[[v10-21-11]]

^<<v10-21-11,11>>^ David was told what Saul’s concubine Rizʹpah the daughter of Aʹiah had done.

[[v10-21-12]]

^<<v10-21-12,12>>^ So David went and took the bones of Saul and the bones of his son Jonʹa·than from the leaders^&#42;1^ of Jaʹbesh-gilʹe·ad, who had stolen them from the public square of Beth-shan, where the Phi·lisʹtines had hung them on the day that the Phi·lisʹtines struck down Saul on Gil·boʹa.

[NOTE]
====
. Or possibly, “landowners.”
====

[[v10-21-13]]

^<<v10-21-13,13>>^ He brought the bones of Saul and the bones of his son Jonʹa·than up from there, and they also gathered the bones of the men who had been executed.^&#42;1^

[NOTE]
====
. Lit., “exposed.”
====

[[v10-21-14]]

^<<v10-21-14,14>>^ Then they buried the bones of Saul and of Jonʹa·than his son in the land of Benjamin in Zeʹla in the tomb of Kish his father. After they did everything that the king had commanded, God listened to their entreaties for the land.

[[v10-21-15]]

^<<v10-21-15,15>>^ Once again there was war between the Phi·lisʹtines and Israel. So David and his servants went down and fought the Phi·lisʹtines, but David became exhausted.

[[v10-21-16]]

^<<v10-21-16,16>>^ A descendant of the Rephʹa·im named Ishʹbi-beʹnob, whose copper spear weighed 300 shekels^&#42;1^ and who was armed with a new sword, intended to strike David down.

[NOTE]
====
. About 3.42 kg (7.5 lb). See App. B14.
====

[[v10-21-17]]

^<<v10-21-17,17>>^ At once A·bishʹai the son of Ze·ruʹiah came to his aid and struck the Phi·lisʹtine down and put him to death. At that time the men of David swore this oath to him: “You must not go out with us to battle anymore! You must not extinguish the lamp of Israel!”

[[v10-21-18]]

^<<v10-21-18,18>>^ After this, war broke out again with the Phi·lisʹtines at Gob. At that time Sibʹbe·cai the Huʹshath·ite struck down Saph, who was a descendant of the Rephʹa·im.

[[v10-21-19]]

^<<v10-21-19,19>>^ And war broke out again with the Phi·lisʹtines at Gob, and El·haʹnan the son of Jaʹa·re-orʹe·gim the Bethʹle·hem·ite struck down Go·liʹath the Gitʹtite, whose spear had a shaft like the beam of loom workers.

[[v10-21-20]]

^<<v10-21-20,20>>^ War broke out yet again at Gath, where there was a man of extraordinary size, with 6 fingers on each hand and 6 toes on each foot, 24 in all; and he too was a descendant of the Rephʹa·im.

[[v10-21-21]]

^<<v10-21-21,21>>^ He kept taunting Israel. So Jonʹa·than the son of Shimʹe·i, David’s brother, struck him down.

[[v10-21-22]]

^<<v10-21-22,22>>^ These four were descendants of the Rephʹa·im in Gath, and they fell by the hand of David and by the hand of his servants.

'''

xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[&#60; Capítulo Anterior] | <<v10-21-0,Topo>> | xref:010-2-samuel/010-2-samuel-022.adoc#v10-22-0[Próximo Capítulo &#62;]