include::./index.adoc[]

[[v10-7-0]]
=== The Second of Samuel, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-7-1]]

^<<v10-7-1,1>>^ When the king was settled in his own house^&#42;1^ and Jehovah had given him rest from all his surrounding enemies,

[NOTE]
====
. Or “palace.”
====

[[v10-7-2]]

^<<v10-7-2,2>>^ the king said to Nathan the prophet: “Here I am living in a house of cedars while the Ark of the true God sits in the midst of tent cloths.”

[[v10-7-3]]

^<<v10-7-3,3>>^ Nathan replied to the king: “Go and do whatever is in your heart, for Jehovah is with you.”

[[v10-7-4]]

^<<v10-7-4,4>>^ On that very night, the word of Jehovah came to Nathan, saying:

[[v10-7-5]]

^<<v10-7-5,5>>^ “Go and say to my servant David, ‘This is what Jehovah says: “Should you build me a house to dwell in?

[[v10-7-6]]

^<<v10-7-6,6>>^ For I have not dwelled in a house from the day I brought the people of Israel out of Egypt to this day, but I have been moving^&#42;1^ about in a tent and in a tabernacle.

[NOTE]
====
. Lit., “walking.”
====

[[v10-7-7]]

^<<v10-7-7,7>>^ During all the time that I went with all the Israelites,^&#42;1^ did I ever say one word to any of the tribal leaders of Israel whom I appointed to shepherd my people Israel, saying, ‘Why did you not build a house of cedars for me?’”’

[NOTE]
====
. Lit., “sons of Israel.”
====

[[v10-7-8]]

^<<v10-7-8,8>>^ Now say this to my servant David, ‘This is what Jehovah of armies says: “I took you from the pastures, from following the flock, to become a leader over my people Israel.

[[v10-7-9]]

^<<v10-7-9,9>>^ And I will be with you wherever you go, and I will do away with^&#42;1^ all your enemies from before you; and I will make a great name for you like the name of the great men of the earth.

[NOTE]
====
. Lit., “cut off.”
====

[[v10-7-10]]

^<<v10-7-10,10>>^ I will appoint a place for my people Israel and settle them, and they will live there and not be disturbed anymore; and wicked men will not oppress them again as they did in the past,

[[v10-7-11]]

^<<v10-7-11,11>>^ from the day that I appointed judges over my people Israel. And I will give you rest from all your enemies.
“‘“Also, Jehovah has told you that Jehovah will make a house^&#42;1^ for you.

[NOTE]
====
. Or “dynasty.”
====

[[v10-7-12]]

^<<v10-7-12,12>>^ When your days come to an end and you are laid to rest with your forefathers, then I will raise up your offspring^&#42;1^ after you, your own son,^&#42;2^ and I will firmly establish his kingdom.

[NOTE]
====
. Lit., “seed.”
. Lit., “one who will come out of your inward parts.”
====

[[v10-7-13]]

^<<v10-7-13,13>>^ He is the one who will build a house for my name, and I will firmly establish the throne of his kingdom forever.

[[v10-7-14]]

^<<v10-7-14,14>>^ I will become his father, and he will become my son. When he does wrong, I will reprove him with the rod of men and with the strokes of the sons of men.^&#42;1^

[NOTE]
====
. Or possibly, “Adam.”
====

[[v10-7-15]]

^<<v10-7-15,15>>^ My loyal love will not be taken away from him the way I took it away from Saul, whom I removed from before you.

[[v10-7-16]]

^<<v10-7-16,16>>^ Your house and your kingdom will be secure forever before you; your throne will be firmly established forever.”’”

[[v10-7-17]]

^<<v10-7-17,17>>^ Nathan told David all these words and this entire vision.

[[v10-7-18]]

^<<v10-7-18,18>>^ At that King David came in and sat down before Jehovah and said: “Who am I, O Sovereign Lord Jehovah? And what is my house that you have brought me this far?

[[v10-7-19]]

^<<v10-7-19,19>>^ As if this were not enough, O Sovereign Lord Jehovah, you also speak about the house of your servant down to a distant future time; and this is instruction^&#42;1^ for all mankind, O Sovereign Lord Jehovah.

[NOTE]
====
. Or “law.”
====

[[v10-7-20]]

^<<v10-7-20,20>>^ What more can your servant David say to you when you know me so well, O Sovereign Lord Jehovah?

[[v10-7-21]]

^<<v10-7-21,21>>^ For the sake of your word and in agreement with your heart^&#42;1^ you have done all these great things and have revealed them to your servant.

[NOTE]
====
. Or “in harmony with your will.”
====

[[v10-7-22]]

^<<v10-7-22,22>>^ That is why you are truly great, O Sovereign Lord Jehovah. There is no one like you, and there is no God except you; everything we have heard with our ears confirms this.

[[v10-7-23]]

^<<v10-7-23,23>>^ And what other nation on earth is like your people Israel? God went and redeemed them as his people, making a name for himself by doing great and awe-inspiring things for them. You drove out the nations and their gods in behalf of your people, whom you redeemed to yourself from Egypt.

[[v10-7-24]]

^<<v10-7-24,24>>^ You established your people Israel as your own people for all time; and you, O Jehovah, have become their God.

[[v10-7-25]]

^<<v10-7-25,25>>^ “Now, O Jehovah God, carry out the promise you have made concerning your servant and his house for all time, and may you do just as you have promised.

[[v10-7-26]]

^<<v10-7-26,26>>^ May your name be exalted forever, so that people may say, ‘Jehovah of armies is God over Israel,’ and may the house of your servant David be firmly established before you.

[[v10-7-27]]

^<<v10-7-27,27>>^ For you, Jehovah of armies, the God of Israel, have made a revelation to your servant by saying, ‘I will build a house^&#42;1^ for you.’ That is why your servant has the courage^&#42;2^ to pray this prayer to you.

[NOTE]
====
. Or “dynasty.”
. Lit., “has found his heart.”
====

[[v10-7-28]]

^<<v10-7-28,28>>^ And now, O Sovereign Lord Jehovah, you are the true God, and your words are truth, and you have promised these good things to your servant.

[[v10-7-29]]

^<<v10-7-29,29>>^ So may it please you to bless the house of your servant, and may it continue forever before you; for you, O Sovereign Lord Jehovah, have promised, and with your blessing may the house of your servant be blessed forever.”

'''

xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[&#60; Capítulo Anterior] | <<v10-7-0,Topo>> | xref:010-2-samuel/010-2-samuel-008.adoc#v10-8-0[Próximo Capítulo &#62;]