include::./index.adoc[]

[[v10-8-0]]
=== The Second of Samuel, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-8-1]]

^<<v10-8-1,1>>^ Some time later, David defeated the Phi·lisʹtines and subdued them, and David took Methʹeg-amʹmah out of the hands of the Phi·lisʹtines.

[[v10-8-2]]

^<<v10-8-2,2>>^ He defeated the Moʹab·ites and made them lie down on the ground and measured them with a line. He measured out two lines to be put to death, and one full line to be kept alive. And the Moʹab·ites became David’s servants and brought tribute.

[[v10-8-3]]

^<<v10-8-3,3>>^ David defeated Had·ad·eʹzer the son of Reʹhob the king of Zoʹbah as he was on his way to restore his authority at the Eu·phraʹtes River.

[[v10-8-4]]

^<<v10-8-4,4>>^ David captured 1,700 horsemen and 20,000 foot soldiers from him. Then David hamstrung all but 100 of the chariot horses.

[[v10-8-5]]

^<<v10-8-5,5>>^ When the Syrians of Damascus came to help King Had·ad·eʹzer of Zoʹbah, David struck down 22,000 of the Syrians.

[[v10-8-6]]

^<<v10-8-6,6>>^ David then established garrisons in Syria of Damascus, and the Syrians became David’s servants and brought tribute. Jehovah gave David victory^&#42;1^ wherever he went.

[NOTE]
====
. Or “salvation.”
====

[[v10-8-7]]

^<<v10-8-7,7>>^ Moreover, David took the circular shields of gold from the servants of Had·ad·eʹzer and brought them to Jerusalem.

[[v10-8-8]]

^<<v10-8-8,8>>^ From Beʹtah and Be·roʹthai, cities of Had·ad·eʹzer, King David took a great quantity of copper.

[[v10-8-9]]

^<<v10-8-9,9>>^ Now King Toʹi of Haʹmath heard that David had defeated the entire army of Had·ad·eʹzer.

[[v10-8-10]]

^<<v10-8-10,10>>^ So Toʹi sent his son Joʹram to King David to ask about his welfare and to congratulate him because he had fought and defeated Had·ad·eʹzer (for Had·ad·eʹzer had often fought against Toʹi), and he brought articles of silver, gold, and copper.

[[v10-8-11]]

^<<v10-8-11,11>>^ King David sanctified these to Jehovah, along with the silver and the gold that he had sanctified from all the nations that he had subdued:

[[v10-8-12]]

^<<v10-8-12,12>>^ from Syria and Moʹab, from the Amʹmon·ites, the Phi·lisʹtines, the A·malʹek·ites, and from the spoil of Had·ad·eʹzer the son of Reʹhob the king of Zoʹbah.

[[v10-8-13]]

^<<v10-8-13,13>>^ David also made a name for himself when he came back from striking down 18,000 Eʹdom·ites in the Valley of Salt.

[[v10-8-14]]

^<<v10-8-14,14>>^ He established garrisons in Eʹdom. In all Eʹdom he established garrisons, and all the Eʹdom·ites became David’s servants. Jehovah gave David victory^&#42;1^ wherever he went.

[NOTE]
====
. Or “salvation.”
====

[[v10-8-15]]

^<<v10-8-15,15>>^ David kept reigning over all Israel, and David was administering justice and righteousness for all his people.

[[v10-8-16]]

^<<v10-8-16,16>>^ Joʹab the son of Ze·ruʹiah was over the army, and Je·hoshʹa·phat the son of A·hiʹlud was recorder.

[[v10-8-17]]

^<<v10-8-17,17>>^ Zaʹdok the son of A·hiʹtub and A·himʹe·lech the son of A·biʹa·thar were priests, and Se·raiʹah was secretary.

[[v10-8-18]]

^<<v10-8-18,18>>^ Be·naiʹah the son of Je·hoiʹa·da was over the Cherʹe·thites and the Pelʹe·thites. And David’s sons became chief ministers.^&#42;1^

[NOTE]
====
. Lit., “became priests.”
====

'''

xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[&#60; Capítulo Anterior] | <<v10-8-0,Topo>> | xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[Próximo Capítulo &#62;]