include::./index.adoc[]

[[v10-3-0]]
=== The Second of Samuel, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-3-1]]

^<<v10-3-1,1>>^ The war between the house of Saul and the house of David dragged on; and David kept getting stronger, and the house of Saul grew steadily weaker.

[[v10-3-2]]

^<<v10-3-2,2>>^ Meanwhile, sons were born to David in Hebʹron. His firstborn was Amʹnon by A·hinʹo·am of Jezʹre·el.

[[v10-3-3]]

^<<v10-3-3,3>>^ His second was Chilʹe·ab by Abʹi·gail, the widow of Naʹbal the Carʹmel·ite; and the third was Abʹsa·lom the son of Maʹa·cah, the daughter of Talʹmai the king of Geshʹur.

[[v10-3-4]]

^<<v10-3-4,4>>^ The fourth was Ad·o·niʹjah the son of Hagʹgith, and the fifth was Sheph·a·tiʹah the son of A·biʹtal.

[[v10-3-5]]

^<<v10-3-5,5>>^ The sixth was Ithʹre·am by David’s wife Egʹlah. These were born to David in Hebʹron.

[[v10-3-6]]

^<<v10-3-6,6>>^ While the war between the house of Saul and the house of David continued, Abʹner kept strengthening his position in the house of Saul.

[[v10-3-7]]

^<<v10-3-7,7>>^ Now Saul had had a concubine whose name was Rizʹpah, the daughter of Aʹiah. Ish-boʹsheth later said to Abʹner: “Why did you have relations with the concubine of my father?”

[[v10-3-8]]

^<<v10-3-8,8>>^ Abʹner grew very angry over the words of Ish-boʹsheth and said: “Am I a dog’s head from Judah? Until this very day, I have shown loyal love toward the house of your father Saul and to his brothers and his friends, and I have not betrayed you into the hand of David; yet today you call me to account for an error concerning a woman.

[[v10-3-9]]

^<<v10-3-9,9>>^ May God do so to Abʹner and add to it if I do not do for David just as Jehovah swore to him:

[[v10-3-10]]

^<<v10-3-10,10>>^ to transfer the kingdom from the house of Saul and to establish the throne of David over Israel and over Judah, from Dan to Beʹer-sheʹba.”

[[v10-3-11]]

^<<v10-3-11,11>>^ He was not able to say one more word in reply to Abʹner, for he was afraid of him.

[[v10-3-12]]

^<<v10-3-12,12>>^ Abʹner immediately sent messengers to David, saying: “To whom does the land belong?” He added: “Make a covenant with me, and I will do whatever I can^&#42;1^ to turn all Israel to your side.”

[NOTE]
====
. Lit., “and look! my hand is with you.”
====

[[v10-3-13]]

^<<v10-3-13,13>>^ To this he replied: “Good! I will make a covenant with you. The only thing I ask of you is that you do not try to see my face unless first you bring Miʹchal, Saul’s daughter, when you come to see me.”

[[v10-3-14]]

^<<v10-3-14,14>>^ Then David sent messengers to Ish-boʹsheth, Saul’s son, saying: “Give me my wife Miʹchal, to whom I became engaged for 100 foreskins of the Phi·lisʹtines.”

[[v10-3-15]]

^<<v10-3-15,15>>^ So Ish-boʹsheth sent to take her from her husband, Palʹti·el the son of Laʹish.

[[v10-3-16]]

^<<v10-3-16,16>>^ But her husband kept walking with her, weeping as he followed her as far as Ba·huʹrim. Then Abʹner said to him: “Go, return!” At that he returned.

[[v10-3-17]]

^<<v10-3-17,17>>^ Meanwhile, Abʹner sent word to the elders of Israel, saying: “For some time you wanted to have David as king over you.

[[v10-3-18]]

^<<v10-3-18,18>>^ Now act, for Jehovah said to David: ‘By the hand of my servant David I will save my people Israel from the hand of the Phi·lisʹtines and from the hand of all their enemies.’”

[[v10-3-19]]

^<<v10-3-19,19>>^ Then Abʹner spoke to the people of Benjamin. Abʹner also went to speak privately to David at Hebʹron to tell him what Israel and the whole house of Benjamin had agreed upon.

[[v10-3-20]]

^<<v10-3-20,20>>^ When Abʹner came to David at Hebʹron with 20 men, David held a feast for Abʹner and for the men with him.

[[v10-3-21]]

^<<v10-3-21,21>>^ Then Abʹner said to David: “Let me go and gather all Israel together to my lord the king, so that they may make a covenant with you, and you will become king over all that you desire.”^&#42;1^ So David sent Abʹner off, and he went his way in peace.

[NOTE]
====
. Or “your soul desires.”
====

[[v10-3-22]]

^<<v10-3-22,22>>^ Just then, David’s servants and Joʹab returned from a raid, bringing a great quantity of spoil back with them. Abʹner was no longer with David in Hebʹron, for he had sent him on his way in peace.

[[v10-3-23]]

^<<v10-3-23,23>>^ When Joʹab and all the army that was with him arrived, Joʹab was told: “Abʹner the son of Ner came to the king, and he sent him off, and he went his way in peace.”

[[v10-3-24]]

^<<v10-3-24,24>>^ So Joʹab went in to the king and said: “What have you done? Here Abʹner came to you. Why did you send him off so that he successfully got away?

[[v10-3-25]]

^<<v10-3-25,25>>^ You know Abʹner the son of Ner! He came here to fool you and to get to know your every move and to find out everything that you are doing.”

[[v10-3-26]]

^<<v10-3-26,26>>^ So Joʹab left David and sent messengers after Abʹner, and they brought him back from the cistern of Siʹrah; but David did not know anything about it.

[[v10-3-27]]

^<<v10-3-27,27>>^ When Abʹner returned to Hebʹron, Joʹab took him aside inside the gate to speak with him privately. However, there he stabbed him in the abdomen, and he died; this was for killing^&#42;1^ his brother Asʹa·hel.

[NOTE]
====
. Lit., “for the blood of.”
====

[[v10-3-28]]

^<<v10-3-28,28>>^ When David heard about it later, he said: “I and my kingdom are forever innocent before Jehovah of the bloodguilt for Abʹner the son of Ner.

[[v10-3-29]]

^<<v10-3-29,29>>^ May it turn back on the head of Joʹab and on the entire house of his father. May Joʹab’s house never be without a man suffering from a discharge or a leper or a man working at the spindle^&#42;1^ or one falling by the sword or one in need of food!”

[NOTE]
====
. Perhaps referring to a crippled man required to do women’s work.
====

[[v10-3-30]]

^<<v10-3-30,30>>^ So Joʹab and his brother A·bishʹai killed Abʹner because he had put Asʹa·hel their brother to death in the battle at Gibʹe·on.

[[v10-3-31]]

^<<v10-3-31,31>>^ Then David said to Joʹab and all the people with him: “Rip your garments apart and tie on sackcloth and wail over Abʹner.” King David himself was walking behind the funeral bier.

[[v10-3-32]]

^<<v10-3-32,32>>^ They buried Abʹner in Hebʹron; and the king wept loudly at Abʹner’s tomb, and all the people gave way to weeping.

[[v10-3-33]]

^<<v10-3-33,33>>^ The king chanted over Abʹner and said:
“Should Abʹner die the death of a senseless person?

[[v10-3-34]]

^<<v10-3-34,34>>^ Your hands had not been bound,
And your feet were not in fetters.^&#42;1^
You fell like one falling before criminals.”^&#42;2^
At that all the people wept over him again.

[NOTE]
====
. Lit., “copper.”
. Lit., “the sons of unrighteousness.”
====

[[v10-3-35]]

^<<v10-3-35,35>>^ Later all the people came to give David bread for consolation^&#42;1^ while it was still daytime, but David swore: “May God do so to me and add to it if before the sun sets I taste bread or anything at all!”

[NOTE]
====
. Or “bread of mourning.”
====

[[v10-3-36]]

^<<v10-3-36,36>>^ All the people took notice, and it pleased them. Like everything that the king did, it pleased all the people.

[[v10-3-37]]

^<<v10-3-37,37>>^ So all the people and all Israel knew on that day that the king was not responsible for having Abʹner the son of Ner put to death.

[[v10-3-38]]

^<<v10-3-38,38>>^ Then the king said to his servants: “Do you not know that a prince and a great man has fallen this day in Israel?

[[v10-3-39]]

^<<v10-3-39,39>>^ Today I am weak, although anointed as king, and these men, the sons of Ze·ruʹiah, are too brutal for me. May Jehovah repay the evildoer according to his own evil.”

'''

xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[&#60; Capítulo Anterior] | <<v10-3-0,Topo>> | xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[Próximo Capítulo &#62;]