include::./index.adoc[]

[[v10-15-0]]
=== The Second of Samuel, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-15-1]]

^<<v10-15-1,1>>^ After all these things, Abʹsa·lom acquired for himself a chariot and horses and 50 men to run before him.

[[v10-15-2]]

^<<v10-15-2,2>>^ Abʹsa·lom would rise up early and stand at the side of the road to the city gate. Whenever any man had a legal case that was to come to the king for judgment, Abʹsa·lom would call him and say: “From what city are you?” and he would say: “Your servant is from one of the tribes of Israel.”

[[v10-15-3]]

^<<v10-15-3,3>>^ Abʹsa·lom would say to him: “See, your claims are right and proper, but there is no one from the king to hear your case.”

[[v10-15-4]]

^<<v10-15-4,4>>^ Abʹsa·lom would say: “If only I were appointed judge in the land! Then every man who has a legal case or judgment could come to me, and I would see that he receives justice.”

[[v10-15-5]]

^<<v10-15-5,5>>^ And when a man came near to bow down to him, Abʹsa·lom would extend his hand and grab hold of him and kiss him.

[[v10-15-6]]

^<<v10-15-6,6>>^ Abʹsa·lom would do this to all the Israelites who would come in to the king for judgment; so Abʹsa·lom kept stealing the hearts of the men of Israel.

[[v10-15-7]]

^<<v10-15-7,7>>^ At the end of four years,^&#42;1^ Abʹsa·lom said to the king: “Let me go, please, to Hebʹron to pay my vow that I made to Jehovah.

[NOTE]
====
. Or possibly, “40 years.”
====

[[v10-15-8]]

^<<v10-15-8,8>>^ For your servant made this solemn vow when I was dwelling in Geshʹur in Syria: ‘If Jehovah will bring me back to Jerusalem, I will make an offering to^&#42;1^ Jehovah.’”

[NOTE]
====
. Or “worship.” Lit., “render service to.”
====

[[v10-15-9]]

^<<v10-15-9,9>>^ So the king said to him: “Go in peace.” With that he rose up and went to Hebʹron.

[[v10-15-10]]

^<<v10-15-10,10>>^ Abʹsa·lom now sent spies through all the tribes of Israel, saying: “As soon as you hear the sound of the horn, announce, ‘Abʹsa·lom has become king in Hebʹron!’”

[[v10-15-11]]

^<<v10-15-11,11>>^ Now 200 men from Jerusalem had gone there with Abʹsa·lom; they were invited and went unsuspectingly, unaware of what was happening.

[[v10-15-12]]

^<<v10-15-12,12>>^ Further, when he offered the sacrifices, Abʹsa·lom sent for A·hithʹo·phel the Giʹlon·ite, David’s adviser,^&#42;1^ from his city Giʹloh. The conspiracy kept gaining momentum, and the people who supported Abʹsa·lom were growing in number.

[NOTE]
====
. Or “counselor.”
====

[[v10-15-13]]

^<<v10-15-13,13>>^ In time an informer came to David, saying: “The heart of the men of Israel has turned to Abʹsa·lom.”

[[v10-15-14]]

^<<v10-15-14,14>>^ At once David said to all his servants with him in Jerusalem: “Get up, and let us run away, for none of us will escape from Abʹsa·lom! Hurry, for fear he may quickly overtake us and bring disaster on us and strike the city with the sword!”

[[v10-15-15]]

^<<v10-15-15,15>>^ The king’s servants replied to the king: “Whatever my lord the king decides, your servants are ready to do.”

[[v10-15-16]]

^<<v10-15-16,16>>^ So the king went out with all his household following him, but the king left ten concubines to take care of the house.^&#42;1^

[NOTE]
====
. Or “palace.”
====

[[v10-15-17]]

^<<v10-15-17,17>>^ And the king continued on his way out with all the people following, and they stopped at Beth-merʹhak.

[[v10-15-18]]

^<<v10-15-18,18>>^ All his servants leaving with him^&#42;1^ and all the Cherʹe·thites, the Pelʹe·thites, and the Gitʹtites, 600 men who had followed him from Gath, were passing by as the king reviewed them.^&#42;2^

[NOTE]
====
. Or “crossing at his side.”
. Or “crossing before the king’s face.”
====

[[v10-15-19]]

^<<v10-15-19,19>>^ Then the king said to Itʹtai the Gitʹtite: “Why should you also go with us? Go back and dwell with the new king, for you are a foreigner and also an exile from your place.

[[v10-15-20]]

^<<v10-15-20,20>>^ Yesterday you came, so today should I make you wander with us, to go when I must go and where I must go? Go back and take your brothers with you, and may Jehovah show you loyal love and faithfulness!”

[[v10-15-21]]

^<<v10-15-21,21>>^ But Itʹtai answered the king: “As surely as Jehovah is living and as surely as my lord the king is living, wherever my lord the king may be, whether for death or for life, there your servant will be!”

[[v10-15-22]]

^<<v10-15-22,22>>^ At that David said to Itʹtai: “Go and cross over.” So Itʹtai the Gitʹtite crossed over, together with all his men and children.

[[v10-15-23]]

^<<v10-15-23,23>>^ Everyone in the land was weeping loudly while all these people crossed over, and the king was standing by the Kidʹron Valley; all the people were crossing over to the road leading to the wilderness.

[[v10-15-24]]

^<<v10-15-24,24>>^ Zaʹdok was also there and with him were all the Levites carrying the ark of the covenant of the true God; and they set the Ark of the true God down; and A·biʹa·thar went up, while all the people completed crossing over from the city.

[[v10-15-25]]

^<<v10-15-25,25>>^ But the king said to Zaʹdok: “Take the Ark of the true God back to the city. If I find favor in the eyes of Jehovah, he will also bring me back and let me see it and its dwelling place.

[[v10-15-26]]

^<<v10-15-26,26>>^ But if he should say, ‘I have found no pleasure in you,’ then let him do to me whatever seems good in his eyes.”

[[v10-15-27]]

^<<v10-15-27,27>>^ The king said to Zaʹdok the priest: “Are you not a seer? Return to the city in peace, and take the two sons of you men with you, A·himʹa·az your own son and Jonʹa·than the son of A·biʹa·thar.

[[v10-15-28]]

^<<v10-15-28,28>>^ See, I will linger by the fords of the wilderness until word comes from you to inform me.”

[[v10-15-29]]

^<<v10-15-29,29>>^ So Zaʹdok and A·biʹa·thar took the Ark of the true God back to Jerusalem, and they remained there.

[[v10-15-30]]

^<<v10-15-30,30>>^ As David was going up the Mount^&#42;1^ of Olives, he was weeping as he went up; his head was covered, and he was walking barefoot. All the people with him also covered their heads and were weeping as they went up.

[NOTE]
====
. Or “ascent.”
====

[[v10-15-31]]

^<<v10-15-31,31>>^ David was then told: “A·hithʹo·phel is among those conspiring with Abʹsa·lom.” At this David said: “Turn, please, the advice^&#42;1^ of A·hithʹo·phel into foolishness, O Jehovah!”

[NOTE]
====
. Or “counsel.”
====

[[v10-15-32]]

^<<v10-15-32,32>>^ When David came to the summit where people used to bow down to God, Huʹshai the Arʹchite was there to meet him, with his robe ripped apart and dirt on his head.

[[v10-15-33]]

^<<v10-15-33,33>>^ However, David said to him: “If you go across with me, you will be a load on me.

[[v10-15-34]]

^<<v10-15-34,34>>^ But if you return to the city and you say to Abʹsa·lom, ‘I am your servant, O King. I was the servant of your father in the past, but now I am your servant,’ you can then frustrate the advice of A·hithʹo·phel for me.

[[v10-15-35]]

^<<v10-15-35,35>>^ Are not Zaʹdok and A·biʹa·thar the priests there with you? You must tell Zaʹdok and A·biʹa·thar the priests everything that you hear from the house of the king.

[[v10-15-36]]

^<<v10-15-36,36>>^ Look! There with them are their two sons, A·himʹa·az the son of Zaʹdok and Jonʹa·than the son of A·biʹa·thar, and through them send to me everything that you hear.”

[[v10-15-37]]

^<<v10-15-37,37>>^ So Huʹshai, David’s friend,^&#42;1^ went into the city as Abʹsa·lom was entering into Jerusalem.

[NOTE]
====
. Or “confidant.”
====

'''

xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[&#60; Capítulo Anterior] | <<v10-15-0,Topo>> | xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[Próximo Capítulo &#62;]