include::./index.adoc[]

[[v10-16-0]]
=== The Second of Samuel, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v10-16-1]]

^<<v10-16-1,1>>^ When David had passed a little beyond the summit, Ziʹba, the attendant of Me·phibʹo·sheth, was there to meet him with a couple of saddled donkeys, and on them were 200 loaves of bread, 100 cakes of raisins, 100 cakes of summer fruit,^&#42;1^ and a large jar of wine.

[NOTE]
====
. Especially figs and perhaps also dates.
====

[[v10-16-2]]

^<<v10-16-2,2>>^ Then the king said to Ziʹba: “Why have you brought these things?” Ziʹba replied: “The donkeys are for the household of the king to ride, the bread and the summer fruit are for the young men to eat, and the wine is for those who get exhausted in the wilderness to drink.”

[[v10-16-3]]

^<<v10-16-3,3>>^ The king now said: “And where is the son^&#42;1^ of your master?” At this Ziʹba said to the king: “He is staying in Jerusalem, for he said, ‘Today the house of Israel will give back the royal rule of my father to me.’”

[NOTE]
====
. Or “grandson.”
====

[[v10-16-4]]

^<<v10-16-4,4>>^ The king then said to Ziʹba: “Look! Everything that belongs to Me·phibʹo·sheth is yours.” Ziʹba replied: “I bow down before you. May I find favor in your eyes, my lord the king.”

[[v10-16-5]]

^<<v10-16-5,5>>^ When King David reached Ba·huʹrim, a man of the family of Saul’s house named Shimʹe·i, the son of Geʹra, came out shouting curses as he approached.

[[v10-16-6]]

^<<v10-16-6,6>>^ He was throwing stones at David and at all the servants of King David, as well as at all the people and the mighty men on his right and on his left.

[[v10-16-7]]

^<<v10-16-7,7>>^ Shimʹe·i said as he cursed: “Get out, get out, you bloodguilty man! You worthless man!

[[v10-16-8]]

^<<v10-16-8,8>>^ Jehovah has brought back on you all the bloodguilt for the house of Saul, in whose place you have ruled as king, but Jehovah gives the kingship into the hand of Abʹsa·lom your son. Now calamity has overtaken you because you are a bloodguilty man!”

[[v10-16-9]]

^<<v10-16-9,9>>^ Then A·bishʹai the son of Ze·ruʹiah said to the king: “Why should this dead dog curse my lord the king? Let me go over, please, and take off his head.”

[[v10-16-10]]

^<<v10-16-10,10>>^ But the king said: “What do I have to do with you, you sons of Ze·ruʹiah? Let him curse me, for Jehovah has said to him, ‘Curse David!’ So who should say, ‘Why are you doing this?’”

[[v10-16-11]]

^<<v10-16-11,11>>^ David then said to A·bishʹai and all his servants: “Here my own son, who came from my own body, is seeking my life,^&#42;1^ and how much more now a Benʹja·min·ite! Leave him alone so that he may curse me, for Jehovah told him to!

[NOTE]
====
. Or “soul.”
====

[[v10-16-12]]

^<<v10-16-12,12>>^ Perhaps Jehovah will see my affliction, and Jehovah will restore goodness to me instead of the curses shouted at me this day.”

[[v10-16-13]]

^<<v10-16-13,13>>^ With that David and his men kept going down the road while Shimʹe·i was walking alongside the mountain abreast of him, shouting curses and throwing stones and a lot of dust.

[[v10-16-14]]

^<<v10-16-14,14>>^ At length the king and all the people with him arrived at their destination exhausted, and they refreshed themselves.

[[v10-16-15]]

^<<v10-16-15,15>>^ Meanwhile, Abʹsa·lom and all the men of Israel arrived in Jerusalem, and A·hithʹo·phel was with him.

[[v10-16-16]]

^<<v10-16-16,16>>^ When Huʹshai the Arʹchite, David’s friend,^&#42;1^ came in to Abʹsa·lom, Huʹshai said to Abʹsa·lom: “Long live the king! Long live the king!”

[NOTE]
====
. Or “confidant.”
====

[[v10-16-17]]

^<<v10-16-17,17>>^ At this Abʹsa·lom said to Huʹshai: “Is this your loyal love toward your friend? Why did you not go with your friend?”

[[v10-16-18]]

^<<v10-16-18,18>>^ So Huʹshai said to Abʹsa·lom: “No, I am on the side of the one who has been chosen by Jehovah, this people, and all the men of Israel. I will stay with him.

[[v10-16-19]]

^<<v10-16-19,19>>^ And again I say, Whom should I serve? Should it not be his son? Just as I served your father, so I will serve you.”

[[v10-16-20]]

^<<v10-16-20,20>>^ Abʹsa·lom then said to A·hithʹo·phel: “Give me your advice.^&#42;1^ What should we do?”

[NOTE]
====
. Or “counsel.”
====

[[v10-16-21]]

^<<v10-16-21,21>>^ At that A·hithʹo·phel said to Abʹsa·lom: “Have relations with your father’s concubines, those whom he left behind to take care of the house.^&#42;1^ Then all Israel will hear that you have made yourself a stench to your father, and those who support you will be strengthened.”

[NOTE]
====
. Or “palace.”
====

[[v10-16-22]]

^<<v10-16-22,22>>^ So they pitched a tent for Abʹsa·lom on the roof, and Abʹsa·lom had relations with the concubines of his father before the eyes of all Israel.

[[v10-16-23]]

^<<v10-16-23,23>>^ In those days the advice that A·hithʹo·phel gave was considered as^&#42;1^ the word of the true God. That was how all the advice of A·hithʹo·phel was esteemed, both by David and by Abʹsa·lom.

[NOTE]
====
. Or “was as if someone were inquiring of.”
====

'''

xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[&#60; Capítulo Anterior] | <<v10-16-0,Topo>> | xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[Próximo Capítulo &#62;]