include::./index.adoc[]

[[v64-1-0]]
=== The Third of John, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v64-1-1]]

^<<v64-1-1,1>>^ The older man^&#42;1^ to Gaʹius, the beloved, whom I truly love.

[NOTE]
====
. Or “The elder.”
====

[[v64-1-2]]

^<<v64-1-2,2>>^ Beloved one, I pray that in all things you continue to prosper and enjoy good health, just as you are^&#42;1^ now prospering.

[NOTE]
====
. Or “your soul is.”
====

[[v64-1-3]]

^<<v64-1-3,3>>^ For I rejoiced very much when brothers came and bore witness about the truth you hold, as you go on walking in the truth.

[[v64-1-4]]

^<<v64-1-4,4>>^ No greater joy^&#42;1^ do I have than this: that I should hear that my children go on walking in the truth.

[NOTE]
====
. Or possibly, “cause for thankfulness.”
====

[[v64-1-5]]

^<<v64-1-5,5>>^ Beloved one, you show your faithfulness in what you do for the brothers, even though they are strangers to you.

[[v64-1-6]]

^<<v64-1-6,6>>^ They have given a witness about your love before the congregation. Please send them on their way in a manner worthy of God.

[[v64-1-7]]

^<<v64-1-7,7>>^ For it was in behalf of his name that they went out, not taking anything from the people of the nations.

[[v64-1-8]]

^<<v64-1-8,8>>^ So we are under obligation to show hospitality to such ones, so that we may become fellow workers in the truth.

[[v64-1-9]]

^<<v64-1-9,9>>^ I wrote something to the congregation, but Di·otʹre·phes, who likes to have the first place among them, does not accept anything from us with respect.

[[v64-1-10]]

^<<v64-1-10,10>>^ That is why if I come, I will call attention to the works he is doing in spreading malicious talk about us.^&#42;1^ Not being content with this, he refuses to welcome the brothers with respect; and those who want to welcome them, he tries to hinder and to throw out of the congregation.

[NOTE]
====
. Lit., “chattering about us with wicked words.”
====

[[v64-1-11]]

^<<v64-1-11,11>>^ Beloved one, do not imitate what is bad, but imitate what is good. The one who does good originates with God. The one who does bad has not seen God.

[[v64-1-12]]

^<<v64-1-12,12>>^ De·meʹtri·us has been well-reported-on by them all and by the truth itself. In fact, we too are bearing witness about him, and you know that the witness we give is true.

[[v64-1-13]]

^<<v64-1-13,13>>^ I had many things to write you, but I do not wish to go on writing you with pen and ink.

[[v64-1-14]]

^<<v64-1-14,14>>^ However, I am hoping to see you soon, and we will speak face-to-face.
May you have peace.
The friends send you their greetings. Give my greetings to the friends by name.

'''

xref:063-2-john/063-2-john-001.adoc#v63-1-0[&#60; Capítulo Anterior] | <<v64-1-0,Topo>> | xref:065-jude/065-jude-001.adoc#v65-1-0[Próximo Capítulo &#62;]