include::./index.adoc[]

[[v30-3-0]]
=== Amos, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v30-3-1]]

^<<v30-3-1,1>>^ “Hear this word that Jehovah has spoken concerning you, O people of Israel, concerning the whole family that I brought up out of the land of Egypt:

[[v30-3-2]]

^<<v30-3-2,2>>^ ‘You alone I have known out of all the families of the earth.
That is why I will call you to account for all your errors.

[[v30-3-3]]

^<<v30-3-3,3>>^ Will two walk together unless they have agreed to meet?^&#42;1^

[NOTE]
====
. Or “have met by appointment?”
====

[[v30-3-4]]

^<<v30-3-4,4>>^ Will a lion roar in the forest when it has no prey?
Will a young lion^&#42;1^ growl from its lair when it has caught nothing?

[NOTE]
====
. Or “a maned young lion.”
====

[[v30-3-5]]

^<<v30-3-5,5>>^ Will a bird fall into a trap on the ground when there is no snare for it?^&#42;1^
Does a trap spring up from the ground when it has caught nothing?

[NOTE]
====
. Or possibly, “when there is no bait in it?”
====

[[v30-3-6]]

^<<v30-3-6,6>>^ If a horn is blown in a city, do the people not tremble?
If a calamity occurs in the city, is it not Jehovah who has acted?

[[v30-3-7]]

^<<v30-3-7,7>>^ For the Sovereign Lord Jehovah will not do a thing
Unless he has revealed his confidential matter^&#42;1^ to his servants the prophets.

[NOTE]
====
. Or “his ­secret.”
====

[[v30-3-8]]

^<<v30-3-8,8>>^ The lion has roared! Who will not be afraid?
The Sovereign Lord Jehovah has spoken! Who will not prophesy?’

[[v30-3-9]]

^<<v30-3-9,9>>^ ‘Proclaim it on the fortified towers of Ashʹdod
And on the fortified towers in the land of Egypt.
Say: “Gather together against the mountains of Sa·marʹi·a;
See the turmoil in her midst
And the defrauding within her.

[[v30-3-10]]

^<<v30-3-10,10>>^ For they do not know how to do what is right,” declares Jehovah,
“Those who are storing up violence and destruction in their fortified towers.”’

[[v30-3-11]]

^<<v30-3-11,11>>^ Therefore this is what the Sovereign Lord Jehovah says,
‘An adversary will surround the land,
He will strip you of your strength,
And your fortified towers will be plundered.’

[[v30-3-12]]

^<<v30-3-12,12>>^ This is what Jehovah says,
‘Just as the shepherd snatches away two legs or a piece of an ear from the mouth of the lion,
That is how the people of Israel will be snatched away,
Those now sitting in Sa·marʹi·a on splendid beds and on fine couches.’^&#42;1^

[NOTE]
====
. Or “Damascene couches.”
====

[[v30-3-13]]

^<<v30-3-13,13>>^ ‘Hear and warn^&#42;1^ the house of Jacob,’ declares the Sovereign Lord Jehovah, the God of armies.

[NOTE]
====
. Or “bear witness against.”
====

[[v30-3-14]]

^<<v30-3-14,14>>^ ‘For in the day I call Israel to account for all his revolts,^&#42;1^
I will also call for an accounting against the altars of Bethʹel;
The horns of the altar will be cut off and fall to the earth.

[NOTE]
====
. Or “crimes.”
====

[[v30-3-15]]

^<<v30-3-15,15>>^ I will strike down the winter house along with the summer house.’
‘The houses of ivory will perish,
And the great^&#42;1^ houses will come to their end,’ declares Jehovah.”

[NOTE]
====
. Or possibly, “And many.”
====

'''

xref:030-amos/030-amos-002.adoc#v30-2-0[&#60; Capítulo Anterior] | <<v30-3-0,Topo>> | xref:030-amos/030-amos-004.adoc#v30-4-0[Próximo Capítulo &#62;]