include::./index.adoc[]

[[v30-8-0]]
=== Amos, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v30-8-1]]

^<<v30-8-1,1>>^ This is what the Sovereign Lord Jehovah showed me: Look! There was a basket of summer fruit.

[[v30-8-2]]

^<<v30-8-2,2>>^ Then he said, “What do you see, Aʹmos?” I replied, “A basket of summer fruit.” Then Jehovah said to me: “The end has come for my people Israel. I will no longer pardon them.

[[v30-8-3]]

^<<v30-8-3,3>>^ ‘The songs of the temple will turn into wailing in that day,’ declares the Sovereign Lord Jehovah. ‘There will be many carcasses thrown everywhere—hush!’

[[v30-8-4]]

^<<v30-8-4,4>>^ Hear this, you who trample on the poor
And who bring the meek of the land to an end,

[[v30-8-5]]

^<<v30-8-5,5>>^ Who say, ‘When will the new moon festival be over, that we may sell our grain,
And the Sabbath, that we may offer grain for sale?
So that we may make the eʹphah^&#42;1^ measure smaller
And the shekel^&#42;2^ weight greater,
To falsify our scales of deception;

[NOTE]
====
. See App. B14.
. See App. B14.
====

[[v30-8-6]]

^<<v30-8-6,6>>^ So that we may buy the needy for silver
And the poor for a pair of sandals,
And sell the worthless part of the grain.’

[[v30-8-7]]

^<<v30-8-7,7>>^ Jehovah has sworn by the Pride of Jacob,
‘Never will I forget all their deeds.

[[v30-8-8]]

^<<v30-8-8,8>>^ On this account the land^&#42;1^ will tremble,
And every inhabitant in it will mourn.
Will it not all rise like the Nile,
And surge and sink down like the Nile of Egypt?’

[NOTE]
====
. Or “earth.”
====

[[v30-8-9]]

^<<v30-8-9,9>>^ ‘In that day,’ declares the Sovereign Lord Jehovah,
‘I will make the sun go down at high noon,
And I will darken the land on a bright day.

[[v30-8-10]]

^<<v30-8-10,10>>^ I will turn your festivals into mourning
And all your songs into dirges.^&#42;1^
I will put sackcloth on all hips and make every head bald;
I will make it like the mourning for an only son,
And the end of it like a bitter day.’

[NOTE]
====
. Or “songs of mourning.”
====

[[v30-8-11]]

^<<v30-8-11,11>>^ ‘Look! The days are coming,’ declares the Sovereign Lord Jehovah,
‘When I will send a famine into the land,
Not a famine for bread or a thirst for water,
But for hearing the words of Jehovah.

[[v30-8-12]]

^<<v30-8-12,12>>^ They will stagger from sea to sea
And from the north to the east.^&#42;1^
They will rove about searching for the word of Jehovah, but they will not find it.

[NOTE]
====
. Or “sunrise.”
====

[[v30-8-13]]

^<<v30-8-13,13>>^ In that day beautiful virgins will faint,
Also young men, because of the thirst;

[[v30-8-14]]

^<<v30-8-14,14>>^ Those who swear by the guilt of Sa·marʹi·a and who say,
“As surely as your god lives, O Dan!”
And, “As surely as the way of Beʹer-sheʹba lives!”
They will fall, and they will not rise up again.’”

'''

xref:030-amos/030-amos-007.adoc#v30-7-0[&#60; Capítulo Anterior] | <<v30-8-0,Topo>> | xref:030-amos/030-amos-009.adoc#v30-9-0[Próximo Capítulo &#62;]