include::./index.adoc[]

[[v30-5-0]]
=== Amos, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v30-5-1]]

^<<v30-5-1,1>>^ “Hear this word that I am taking up against you as a dirge,^&#42;1^ O house of Israel:

[NOTE]
====
. Or “song of mourning.”
====

[[v30-5-2]]

^<<v30-5-2,2>>^ ‘The virgin, Israel, has fallen;
She cannot get up again.
She has been abandoned on her own ground;
There is no one to raise her up.’

[[v30-5-3]]

^<<v30-5-3,3>>^ “For this is what the Sovereign Lord Jehovah says:
‘The city that marches out with a thousand will have a hundred left;
And the one that goes out with a hundred will have ten left, for the house of Israel.’

[[v30-5-4]]

^<<v30-5-4,4>>^ “For this is what Jehovah says to the house of Israel:
‘Search for me and keep living.

[[v30-5-5]]

^<<v30-5-5,5>>^ Do not search for Bethʹel,
Do not go to Gilʹgal or pass over to Beʹer-sheʹba,
For Gilʹgal will certainly go into exile,
And Bethʹel will come to nothing.^&#42;1^

[NOTE]
====
. Or possibly, “become something un­canny.”
====

[[v30-5-6]]

^<<v30-5-6,6>>^ Search for Jehovah, and keep living,
So that he does not burst out like a fire on the house of Joseph,
Consuming Bethʹel, with no one to extinguish it.

[[v30-5-7]]

^<<v30-5-7,7>>^ You turn justice into wormwood,^&#42;1^
And you cast righteousness to the earth.

[NOTE]
====
. Or “bitterness.”
====

[[v30-5-8]]

^<<v30-5-8,8>>^ The One who made the Kiʹmah constellation^&#42;1^ and the Keʹsil constellation,^&#42;2^
The One who turns deep shadow into morning,
The One who makes day as dark as night,
The One who summons the waters of the sea
To pour them out on the surface of the earth
—Jehovah is his name.

[NOTE]
====
. Possibly the Pleiades stars in the Taurus constellation.
. Possibly the Orion constellation.
====

[[v30-5-9]]

^<<v30-5-9,9>>^ He will cause destruction to burst out against the strong,
Bringing destruction on fortified places.

[[v30-5-10]]

^<<v30-5-10,10>>^ They hate those who give reproof in the city gate,
And they detest those who speak truthfully.

[[v30-5-11]]

^<<v30-5-11,11>>^ Because you demand farm rent^&#42;1^ from the poor
And you take his grain as tribute,
You will not keep dwelling in the houses of hewn stone that you have built
Nor drink the wine from the choice vineyards that you have planted.

[NOTE]
====
. Or “land tax.”
====

[[v30-5-12]]

^<<v30-5-12,12>>^ For I know how many your revolts^&#42;1^ are
And how great your sins are
—You harass the righteous,
You take bribes,^&#42;2^
And you deny the rights of the poor in the city gate.

[NOTE]
====
. Or “crimes.”
. Or “hush money.”
====

[[v30-5-13]]

^<<v30-5-13,13>>^ Therefore, those with insight will keep silent at that time,
For it will be a time of calamity.

[[v30-5-14]]

^<<v30-5-14,14>>^ Search for what is good, and not what is bad,
So that you may keep living.
Then Jehovah the God of armies may be with you,
Just as you say he is.

[[v30-5-15]]

^<<v30-5-15,15>>^ Hate what is bad, and love what is good,
Let justice prevail in the city gate.
It may be that Jehovah the God of armies
Will show favor to the remaining ones of Joseph.’

[[v30-5-16]]

^<<v30-5-16,16>>^ “Therefore this is what Jehovah the God of armies, Jehovah, says:
‘In all the public squares there will be wailing,
And in all the streets they will say, “Alas, alas!”
They will call on the farmers to mourn
And the professional mourners to wail.’

[[v30-5-17]]

^<<v30-5-17,17>>^ ‘In every vineyard there will be wailing;
For I will pass through your midst,’ says Jehovah.

[[v30-5-18]]

^<<v30-5-18,18>>^ ‘Woe to those who yearn for the day of Jehovah!
What, then, will the day of Jehovah mean for you?
It will be darkness, and not light.

[[v30-5-19]]

^<<v30-5-19,19>>^ It will be like a man who flees from a lion and is confronted by a bear,
And when he enters his house and leans his hand against the wall, a snake bites him.

[[v30-5-20]]

^<<v30-5-20,20>>^ Will not the day of Jehovah be darkness, and not light;
Will it not have gloom, and not brightness?

[[v30-5-21]]

^<<v30-5-21,21>>^ I hate, I despise your festivals,
And I take no pleasure in the aroma of your solemn assemblies.

[[v30-5-22]]

^<<v30-5-22,22>>^ Even if you offer me whole burnt offerings and gift offerings,
I will find no pleasure in them;
And I will not look with favor on your communion sacrifices of fattened animals.

[[v30-5-23]]

^<<v30-5-23,23>>^ Spare me the din of your songs;
And let me not hear the melodies of your stringed instruments.

[[v30-5-24]]

^<<v30-5-24,24>>^ Let justice flow down like waters,
And righteousness like an ever-flowing stream.

[[v30-5-25]]

^<<v30-5-25,25>>^ Did you bring me sacrifices and gift offerings
For those 40 years in the wilderness, O house of Israel?

[[v30-5-26]]

^<<v30-5-26,26>>^ Now you will have to carry away Sakʹkuth your king and Kaiʹwan,^&#42;1^
Your images, the star of your god, whom you made for yourselves,

[NOTE]
====
. These deities may both refer to the planet Saturn, which was worshipped as a god.
====

[[v30-5-27]]

^<<v30-5-27,27>>^ And I will send you into exile beyond Damascus,’ says he whose name is Jehovah the God of armies.”

'''

xref:030-amos/030-amos-004.adoc#v30-4-0[&#60; Capítulo Anterior] | <<v30-5-0,Topo>> | xref:030-amos/030-amos-006.adoc#v30-6-0[Próximo Capítulo &#62;]