include::./index.adoc[]

[[v30-7-0]]
=== Amos, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v30-7-1]]

^<<v30-7-1,1>>^ This is what the Sovereign Lord Jehovah showed me: Look! He formed a locust swarm when the late crop^&#42;1^ was beginning to come up. This was the later crop after the king’s hay had been cut.

[NOTE]
====
. That is, during January and February.
====

[[v30-7-2]]

^<<v30-7-2,2>>^ When the swarm finished eating up the vegetation of the land, I said: “O Sovereign Lord Jehovah, please forgive! How can Jacob survive?^&#42;1^ For he is weak!”

[NOTE]
====
. Lit., “rise up?”
====

[[v30-7-3]]

^<<v30-7-3,3>>^ So Jehovah reconsidered^&#42;1^ this. “It will not happen,” Jehovah said.

[NOTE]
====
. Or “felt regret over.”
====

[[v30-7-4]]

^<<v30-7-4,4>>^ This is what the Sovereign Lord Jehovah showed me: Look! The Sovereign Lord Jehovah called for a punishment by fire. It consumed the vast deep waters, and it consumed a portion of the land.

[[v30-7-5]]

^<<v30-7-5,5>>^ Then I said: “O Sovereign Lord Jehovah, please hold this back. How can Jacob survive?^&#42;1^ For he is weak!”

[NOTE]
====
. Lit., “rise up?”
====

[[v30-7-6]]

^<<v30-7-6,6>>^ So Jehovah reconsidered^&#42;1^ this. “That too will not happen,” the Sovereign Lord Jehovah said.

[NOTE]
====
. Or “felt regret over.”
====

[[v30-7-7]]

^<<v30-7-7,7>>^ This is what he showed me: Look! Jehovah was standing on a wall made with a plumb line,^&#42;1^ and there was a plumb line in his hand.

[NOTE]
====
. Or “a plummet.”
====

[[v30-7-8]]

^<<v30-7-8,8>>^ Then Jehovah said to me: “What do you see, Aʹmos?” So I said: “A plumb line.” Jehovah then said: “Here I am putting a plumb line among my people Israel. I will no longer pardon them.

[[v30-7-9]]

^<<v30-7-9,9>>^ The high places of Isaac will be desolated, and the sanctuaries of Israel will be devastated; and I will come against the house of Jer·o·boʹam with a sword.”

[[v30-7-10]]

^<<v30-7-10,10>>^ Am·a·ziʹah the priest of Bethʹel sent this message to King Jer·o·boʹam of Israel: “Aʹmos is conspiring against you right in the midst of the house of Israel. The land cannot put up with all his words.

[[v30-7-11]]

^<<v30-7-11,11>>^ For this is what Aʹmos says, ‘Jer·o·boʹam will die by the sword, and Israel will surely go into exile from its land.’”

[[v30-7-12]]

^<<v30-7-12,12>>^ Am·a·ziʹah then said to Aʹmos: “O visionary, go, run away to the land of Judah, earn your bread^&#42;1^ there, and there you may prophesy.

[NOTE]
====
. Lit., “eat bread.”
====

[[v30-7-13]]

^<<v30-7-13,13>>^ But you must no longer prophesy at Bethʹel, for it is the sanctuary of a king and the house of a kingdom.”

[[v30-7-14]]

^<<v30-7-14,14>>^ Then Aʹmos answered Am·a·ziʹah: “I was not a prophet nor the son of a prophet; but I was a herdsman, and I took care of sycamore fig trees.^&#42;1^

[NOTE]
====
. Or “was a nipper of sycamore figs.”
====

[[v30-7-15]]

^<<v30-7-15,15>>^ But Jehovah took me away from following the flock, and Jehovah said to me, ‘Go, prophesy to my people Israel.’

[[v30-7-16]]

^<<v30-7-16,16>>^ So now hear the word of Jehovah: ‘You are saying, “Do not prophesy against Israel, and do not preach against the house of Isaac.”

[[v30-7-17]]

^<<v30-7-17,17>>^ Therefore this is what Jehovah says: “Your wife will become a prostitute in the city, and your sons and your daughters will fall by the sword. Your land will be apportioned out with a measuring line, and you yourself will die in an unclean land; and Israel will surely go into exile from its land.”’”

'''

xref:030-amos/030-amos-006.adoc#v30-6-0[&#60; Capítulo Anterior] | <<v30-7-0,Topo>> | xref:030-amos/030-amos-008.adoc#v30-8-0[Próximo Capítulo &#62;]