include::./index.adoc[]

[[v30-9-0]]
=== Amos, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v30-9-1]]

^<<v30-9-1,1>>^ I saw Jehovah stationed above the altar, and he said: “Strike the head of the pillar, and the thresholds will shake. Cut them off at the head, and I will kill the last of them with the sword. No one who flees will get away, and no one trying to escape will succeed.

[[v30-9-2]]

^<<v30-9-2,2>>^ If they dig down into the Grave,^&#42;1^
From there my hand will take them;
And if they go up to the heavens,
From there I will bring them down.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v30-9-3]]

^<<v30-9-3,3>>^ And if they hide themselves on the top of Carʹmel,
From there I will search them out and take them.
If they conceal themselves from my eyes on the bottom of the sea,
There I will command the serpent to bite them.

[[v30-9-4]]

^<<v30-9-4,4>>^ If they go into captivity before their enemies,
From there I will command the sword, and it will kill them;
I will fix my eyes on them for bad, and not for good.

[[v30-9-5]]

^<<v30-9-5,5>>^ For the Sovereign Lord, Jehovah of the armies, is the One who touches the land,^&#42;1^
So that it melts, and all its inhabitants will mourn;
And all of it will rise like the Nile,
And sink down like the Nile of Egypt.

[NOTE]
====
. Or “earth.”
====

[[v30-9-6]]

^<<v30-9-6,6>>^ ‘The one who builds his stairs in the heavens
And establishes his structure^&#42;1^ over the earth;
The one who summons the waters of the sea,
To pour them out on the surface of the earth
—Jehovah is his name.’

[NOTE]
====
. Or “dome; vault.”
====

[[v30-9-7]]

^<<v30-9-7,7>>^ ‘Are you not like the sons of the Cushʹites to me, O people of Israel?’ declares Jehovah.
‘Did I not bring Israel up out of the land of Egypt,
The Phi·lisʹtines out of Crete, and Syria out of Kir?’

[[v30-9-8]]

^<<v30-9-8,8>>^ ‘Look! The eyes of the Sovereign Lord Jehovah are on the sinful kingdom,
And he will annihilate it from the surface of the land.
But I will not completely annihilate the house of Jacob,’ declares Jehovah.

[[v30-9-9]]

^<<v30-9-9,9>>^ ‘For look! I am giving the command,
And I will shake the house of Israel among all the nations,
Just as one shakes a sieve,
And not a pebble falls to the ground.

[[v30-9-10]]

^<<v30-9-10,10>>^ They will die by the sword, all the sinners of my people,
Those who are saying, “The calamity will not come near us or reach us.”’

[[v30-9-11]]

^<<v30-9-11,11>>^ ‘In that day I will raise up the booth^&#42;1^ of David that is fallen,
I will repair the^&#42;2^ breaches,
And I will restore its ruins;
I will rebuild it as in the days of long ago,

[NOTE]
====
. Or “tent; hut.”
. Or “their.”
====

[[v30-9-12]]

^<<v30-9-12,12>>^ So that they may take possession of what is remaining of Eʹdom,
And all the nations on whom my name has been called,’ declares Jehovah, who is doing this.

[[v30-9-13]]

^<<v30-9-13,13>>^ ‘Look! The days are coming,’ declares Jehovah,
‘When the plowman will overtake the harvester,
And the treader of grapes, the one carrying seed;
And the mountains will drip with sweet wine,
And all the hills will flow with it.^&#42;1^

[NOTE]
====
. Lit., “will melt.”
====

[[v30-9-14]]

^<<v30-9-14,14>>^ I will gather back the captives of my people Israel,
And they will rebuild the desolated cities and inhabit them;
They will plant vineyards and drink their wine,
And make gardens and eat their fruit.’

[[v30-9-15]]

^<<v30-9-15,15>>^ ‘I will plant them on their land,
And they will never again be uprooted
From their land that I have given them,’ says Jehovah your God.”

'''

xref:030-amos/030-amos-008.adoc#v30-8-0[&#60; Capítulo Anterior] | <<v30-9-0,Topo>> | xref:031-obadiah/031-obadiah-001.adoc#v31-1-0[Próximo Capítulo &#62;]