include::./index.adoc[]

[[v30-2-0]]
=== Amos, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v30-2-1]]

^<<v30-2-1,1>>^ “This is what Jehovah says,
‘“For three revolts^&#42;1^ of Moʹab, and for four, I will not reverse it,
Because he burned the bones of the king of Eʹdom for lime.

[NOTE]
====
. Or “crimes.”
====

[[v30-2-2]]

^<<v30-2-2,2>>^ So I will send a fire into Moʹab,
And it will consume the fortified towers of Keʹri·oth;
Moʹab will die amid an uproar,
With a war cry, with the sound of a horn.

[[v30-2-3]]

^<<v30-2-3,3>>^ I will remove the ruler^&#42;1^ from her midst
And kill all her princes along with him,” says Jehovah.’

[NOTE]
====
. Lit., “judge.”
====

[[v30-2-4]]

^<<v30-2-4,4>>^ This is what Jehovah says,
‘For three revolts of Judah, and for four, I will not reverse it,
Because they rejected the law^&#42;1^ of Jehovah,
And because they did not keep his regulations;
But the same lies their forefathers followed have led them astray.

[NOTE]
====
. Or “instruction.”
====

[[v30-2-5]]

^<<v30-2-5,5>>^ So I will send a fire into Judah,
And it will consume the fortified towers of Jerusalem.’

[[v30-2-6]]

^<<v30-2-6,6>>^ This is what Jehovah says,
‘For three revolts of Israel, and for four, I will not reverse it,
Because they sell the righteous for silver,
And the poor for a pair of sandals.

[[v30-2-7]]

^<<v30-2-7,7>>^ They trample the heads of the lowly into the dust of the earth,
And they block the path of the meek.
A man and his father have relations with the same girl,
Profaning my holy name.

[[v30-2-8]]

^<<v30-2-8,8>>^ They stretch out next to every altar on garments they seized as security for a loan;^&#42;1^
And the wine they drink at the house^&#42;2^ of their gods was obtained from those they fined.’

[NOTE]
====
. Or “a pledge.”
. Or “temple.”
====

[[v30-2-9]]

^<<v30-2-9,9>>^ ‘But it was I who annihilated the Amʹor·ite before them,
Who was as tall as the cedars and as strong as the oaks;
I destroyed his fruit above and his roots below.

[[v30-2-10]]

^<<v30-2-10,10>>^ I brought you up out of the land of Egypt,
And I made you walk through the wilderness 40 years,
To take possession of the land of the Amʹor·ite.

[[v30-2-11]]

^<<v30-2-11,11>>^ I raised up some of your sons as prophets
And some of your young men as Nazʹi·rites.
Is this not so, O people of Israel?’ declares Jehovah.

[[v30-2-12]]

^<<v30-2-12,12>>^ ‘But you kept giving the Nazʹi·rites wine to drink,
And you commanded the prophets: “You must not prophesy.”

[[v30-2-13]]

^<<v30-2-13,13>>^ So I will crush you in your place,
Just as a wagon loaded with cut grain crushes what is under it.

[[v30-2-14]]

^<<v30-2-14,14>>^ The swift one will have no place to flee,
The strong one will not retain his power,
And no warrior will escape with his life.^&#42;1^

[NOTE]
====
. Or “soul.”
====

[[v30-2-15]]

^<<v30-2-15,15>>^ The bowman will not stand his ground,
The swift of foot will not escape,
And the horseman will not escape with his life.^&#42;1^

[NOTE]
====
. Or “soul.”
====

[[v30-2-16]]

^<<v30-2-16,16>>^ Even the most courageous^&#42;1^ among the warriors
Will flee naked in that day,’ declares Jehovah.”

[NOTE]
====
. Or “those strong of heart.”
====

'''

xref:030-amos/030-amos-001.adoc#v30-1-0[&#60; Capítulo Anterior] | <<v30-2-0,Topo>> | xref:030-amos/030-amos-003.adoc#v30-3-0[Próximo Capítulo &#62;]