include::./index.adoc[]

[[v30-4-0]]
=== Amos, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v30-4-1]]

^<<v30-4-1,1>>^ “Hear this word, you cows of Baʹshan,
Who are on the mountain of Sa·marʹi·a,
You women who are defrauding the lowly and crushing the poor,
Who say to their husbands,^&#42;1^ ‘Bring us something to drink!’

[NOTE]
====
. Or “masters.”
====

[[v30-4-2]]

^<<v30-4-2,2>>^ The Sovereign Lord Jehovah has sworn by his holiness,
‘“Look! The days are coming upon you when he will lift you up with butcher hooks
And the rest of you with fishhooks.

[[v30-4-3]]

^<<v30-4-3,3>>^ You will go out through the breaches in the wall, each one straight ahead;
And you will be cast out to Harʹmon,” declares Jehovah.’

[[v30-4-4]]

^<<v30-4-4,4>>^ ‘Come to Bethʹel and commit transgression,^&#42;1^
To Gilʹgal and transgress even more!
Bring your sacrifices in the morning,
And your tithes^&#42;2^ on the third day.

[NOTE]
====
. Or “rebel.”
. Or “tenth parts.”
====

[[v30-4-5]]

^<<v30-4-5,5>>^ Burn a thanksgiving sacrifice of leavened bread;
Loudly proclaim your voluntary offerings!
For that is what you love to do, O people of Israel,’ declares the Sovereign Lord Jehovah.

[[v30-4-6]]

^<<v30-4-6,6>>^ ‘And for my part, I made your teeth clean of food^&#42;1^ in all your cities
And caused a lack of bread in all your houses;
But you did not come back to me,’ declares Jehovah.

[NOTE]
====
. Or “gave you no food to eat.”
====

[[v30-4-7]]

^<<v30-4-7,7>>^ ‘I also withheld rain from you three months before the harvest;
I made it rain on one city but not on another city.
One plot of land would have rain,
But another plot of land where there was no rain would dry up.

[[v30-4-8]]

^<<v30-4-8,8>>^ People of two or three cities staggered to one city to drink water,
And they would not get satisfied;
But you did not come back to me,’ declares Jehovah.

[[v30-4-9]]

^<<v30-4-9,9>>^ ‘I struck you with scorching heat and mildew.
You multiplied your gardens and vineyards,
But the locust would devour your fig trees and olive trees;
And you still did not come back to me,’ declares Jehovah.

[[v30-4-10]]

^<<v30-4-10,10>>^ ‘I sent among you a pestilence like that of Egypt.
With the sword I killed your young men and captured your horses.
I made the stench of your camps rise up into your nostrils;
But you did not come back to me,’ declares Jehovah.

[[v30-4-11]]

^<<v30-4-11,11>>^ ‘I caused an overthrow among you
Like God’s overthrow of Sodʹom and Go·morʹrah.
And you were like a log snatched out of the fire;
But you did not come back to me,’ declares Jehovah.

[[v30-4-12]]

^<<v30-4-12,12>>^ So that is what I will do to you, O Israel.
Because this is what I will do to you,
Get ready to meet your God, O Israel.

[[v30-4-13]]

^<<v30-4-13,13>>^ For look! he is the One who formed the mountains and created the wind;
He tells man what His thoughts are,
He turns the dawn into darkness,
And he treads on earth’s high places;
Jehovah the God of armies is his name.”

'''

xref:030-amos/030-amos-003.adoc#v30-3-0[&#60; Capítulo Anterior] | <<v30-4-0,Topo>> | xref:030-amos/030-amos-005.adoc#v30-5-0[Próximo Capítulo &#62;]