include::./index.adoc[]

[[v30-6-0]]
=== Amos, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v30-6-1]]

^<<v30-6-1,1>>^ “Woe to the self-assured^&#42;1^ ones in Zion,
To those feeling secure in the mountain of Sa·marʹi·a,
The prominent men of the foremost of nations,
Those to whom the house of Israel comes!

[NOTE]
====
. Or “complacent.”
====

[[v30-6-2]]

^<<v30-6-2,2>>^ Cross over to Calʹneh and see.
Go from there to Great Haʹmath,
And go down to Gath of the Phi·lisʹtines.
Are they better than these kingdoms,^&#42;1^
Or is their territory larger than yours?

[NOTE]
====
. Evidently referring to the kingdoms of Judah and Israel.
====

[[v30-6-3]]

^<<v30-6-3,3>>^ Are you putting out of your mind the day of calamity
And bringing in a reign^&#42;1^ of violence?

[NOTE]
====
. Lit., “seat.”
====

[[v30-6-4]]

^<<v30-6-4,4>>^ They lie on beds of ivory and sprawl out on couches,
Eating the rams of the flock and the fattened calves;^&#42;1^

[NOTE]
====
. Or “young bulls.”
====

[[v30-6-5]]

^<<v30-6-5,5>>^ They improvise songs to the sound of the harp,^&#42;1^
And like David, they invent musical instruments;

[NOTE]
====
. Or “stringed instrument.”
====

[[v30-6-6]]

^<<v30-6-6,6>>^ They drink wine by the bowlful
And anoint themselves with the choicest oils.
But they are unconcerned about^&#42;1^ the catastrophe of Joseph.

[NOTE]
====
. Lit., “did not become sick at.”
====

[[v30-6-7]]

^<<v30-6-7,7>>^ So they will go into exile at the head of the exiles,
And the revelry of those sprawled out will come to an end.

[[v30-6-8]]

^<<v30-6-8,8>>^ ‘The Sovereign Lord Jehovah has sworn by himself,’^&#42;1^ declares Jehovah the God of armies,
‘“I detest the pride of Jacob,
I hate his fortified towers,
And I will hand over the city and what fills it.

[NOTE]
====
. Or “his soul.”
====

[[v30-6-9]]

^<<v30-6-9,9>>^ “‘“And if ten men are left in one house, they will also die.

[[v30-6-10]]

^<<v30-6-10,10>>^ A relative^&#42;1^ will come to carry them out and burn them one by one. He will bring their bones out from the house; then he will say to whoever is in the inner rooms of the house, ‘Are there any more with you?’ And he will say, ‘Nobody!’ Then he will say, ‘Keep silent! For it is not the time to make any mention of the name of Jehovah.’”

[NOTE]
====
. Lit., “His father’s brother.”
====

[[v30-6-11]]

^<<v30-6-11,11>>^ For it is Jehovah giving the command,
And he will strike down the great house into rubble,
And the small house into debris.

[[v30-6-12]]

^<<v30-6-12,12>>^ Do horses run on a crag,
Or will one plow there with cattle?
For you have turned justice into a poisonous plant,
And the fruit of righteousness into wormwood.^&#42;1^

[NOTE]
====
. Or “bitterness.”
====

[[v30-6-13]]

^<<v30-6-13,13>>^ You rejoice over what is worthless,
And you say, “Have we not become powerful^&#42;1^ in our own strength?”

[NOTE]
====
. Lit., “taken horns for ourselves.”
====

[[v30-6-14]]

^<<v30-6-14,14>>^ Therefore, O house of Israel, I will bring against you a nation,’ declares Jehovah the God of armies,
‘And they will oppress you from Leʹbo-haʹmath^&#42;1^ down to the Wadi^&#42;2^ of the Arʹa·bah.’”

[NOTE]
====
. Or “the entrance of Hamath.”
. See Glossary.
====

'''

xref:030-amos/030-amos-005.adoc#v30-5-0[&#60; Capítulo Anterior] | <<v30-6-0,Topo>> | xref:030-amos/030-amos-007.adoc#v30-7-0[Próximo Capítulo &#62;]