include::./index.adoc[]

[[v12-5-0]]
=== The Second of Kings, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-5-1]]

^<<v12-5-1,1>>^ Now Naʹa·man the army chief of the king of Syria was a prominent man who was held in esteem by his lord, because through him Jehovah had given victory^&#42;1^ to Syria. He was a mighty warrior, although he was a leper.^&#42;2^

[NOTE]
====
. Or “salvation.”
. Or “struck with a skin disease.”
====

[[v12-5-2]]

^<<v12-5-2,2>>^ On one of their raids, the Syrians had taken captive from the land of Israel a little girl who became a servant to Naʹa·man’s wife.

[[v12-5-3]]

^<<v12-5-3,3>>^ She said to her mistress: “If only my lord would visit the prophet in Sa·marʹi·a! Then he would cure him of his leprosy.”

[[v12-5-4]]

^<<v12-5-4,4>>^ So he^&#42;1^ went and reported to his lord, telling him what the girl from Israel had said.

[NOTE]
====
. Possibly referring to Naaman.
====

[[v12-5-5]]

^<<v12-5-5,5>>^ Then the king of Syria said: “Go now! And I will send a letter to the king of Israel.” So he went, taking with him ten talents^&#42;1^ of silver, 6,000 pieces of gold, and ten changes of garments.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v12-5-6]]

^<<v12-5-6,6>>^ He brought to the king of Israel the letter, which read: “Along with this letter that has come to you, I send my servant Naʹa·man so that you may cure him of his leprosy.”

[[v12-5-7]]

^<<v12-5-7,7>>^ As soon as the king of Israel read the letter, he ripped his garments apart and said: “Am I God, to put to death and to keep alive? For he is sending this man to me, telling me to cure him of his leprosy! You can see for yourselves that he is seeking a quarrel with me.”

[[v12-5-8]]

^<<v12-5-8,8>>^ But when E·liʹsha the man of the true God heard that the king of Israel had ripped his garments apart, he at once sent word to the king: “Why did you rip your garments apart? Please let him come to me so that he may know that there is a prophet in Israel.”

[[v12-5-9]]

^<<v12-5-9,9>>^ So Naʹa·man came with his horses and his war chariots and stood at the entrance of the house of E·liʹsha.

[[v12-5-10]]

^<<v12-5-10,10>>^ However, E·liʹsha sent a messenger to tell him: “Go, wash seven times in the Jordan, and your flesh will be restored, and you will be clean.”

[[v12-5-11]]

^<<v12-5-11,11>>^ At this Naʹa·man became indignant and started to leave, saying: “Here I said to myself, ‘He will come out to me and stand here and call on the name of Jehovah his God, moving his hand back and forth over the leprosy to cure it.’

[[v12-5-12]]

^<<v12-5-12,12>>^ Are not the A·baʹnah and the Pharʹpar, the rivers of Damascus, better than all the waters of Israel? Can I not wash in them and become clean?” With that he turned and went away in a rage.

[[v12-5-13]]

^<<v12-5-13,13>>^ His servants now approached him and said: “My father, if the prophet had told you to do something extraordinary, would you not do it? How much more, then, since he only said to you, ‘Wash and be clean’?”

[[v12-5-14]]

^<<v12-5-14,14>>^ At that he went down and plunged into^&#42;1^ the Jordan seven times, according to the word of the man of the true God. Then his flesh was restored like the flesh of a little boy, and he became clean.

[NOTE]
====
. Or “immersed himself in.”
====

[[v12-5-15]]

^<<v12-5-15,15>>^ After that he went back to the man of the true God, he and all his entourage,^&#42;1^ and he stood before him and said: “Now I know that there is no God anywhere in all the earth but in Israel. Now accept, please, a gift^&#42;2^ from your servant.”

[NOTE]
====
. Lit., “camp.”
. Lit., “blessing.”
====

[[v12-5-16]]

^<<v12-5-16,16>>^ However, E·liʹsha said: “As surely as Jehovah whom I serve^&#42;1^ is living, I will not accept it.” He urged him to accept it, but he kept refusing.

[NOTE]
====
. Lit., “before whom I stand.”
====

[[v12-5-17]]

^<<v12-5-17,17>>^ Finally Naʹa·man said: “If not, please, let your servant be given two mule-loads of soil from this land, for your servant will no longer offer a burnt offering or a sacrifice to any gods other than Jehovah.

[[v12-5-18]]

^<<v12-5-18,18>>^ But may Jehovah forgive your servant for this one thing: When my lord goes into the house^&#42;1^ of Rimʹmon to bow down there, he supports himself on my arm, so I have to bow down at the house of Rimʹmon. When I bow down at the house of Rimʹmon, may Jehovah, please, forgive your servant for this.”

[NOTE]
====
. Or “temple.”
====

[[v12-5-19]]

^<<v12-5-19,19>>^ At this he said to him: “Go in peace.” After he departed from him and had traveled for some distance,

[[v12-5-20]]

^<<v12-5-20,20>>^ Ge·haʹzi the attendant of E·liʹsha the man of the true God said to himself: ‘Here my master has spared this Syrian Naʹa·man by not accepting from him what he brought. As surely as Jehovah is living, I will run after him and take something from him.’

[[v12-5-21]]

^<<v12-5-21,21>>^ So Ge·haʹzi chased after Naʹa·man. When Naʹa·man saw someone running after him, he got down from his chariot to meet him and said: “Is everything all right?”

[[v12-5-22]]

^<<v12-5-22,22>>^ To this he said: “All is well. My master has sent me, saying, ‘Look! Just now two young men from the mountainous region of Eʹphra·im from the sons of the prophets came to me. Give them, please, a talent of silver and two changes of garments.’”

[[v12-5-23]]

^<<v12-5-23,23>>^ Naʹa·man said: “Go on, take two talents.” He kept urging him, and he wrapped up two talents of silver in two bags, with two changes of garments, and gave them to two of his attendants, who carried them before him.

[[v12-5-24]]

^<<v12-5-24,24>>^ When he reached Oʹphel,^&#42;1^ he took them from their hand and put them in the house and sent the men away. After they left,

[NOTE]
====
. A location in Samaria, possibly a hill or a fortification.
====

[[v12-5-25]]

^<<v12-5-25,25>>^ he went in and stood by his master. E·liʹsha now said to him: “Where did you come from, Ge·haʹzi?” But he said: “Your servant did not go anywhere.”

[[v12-5-26]]

^<<v12-5-26,26>>^ E·liʹsha said to him: “Was my heart not there with you when the man got down from his chariot to meet you? Is it a time to accept silver or to accept garments or olive groves or vineyards or sheep or cattle or male or female servants?

[[v12-5-27]]

^<<v12-5-27,27>>^ Now Naʹa·man’s leprosy will stick to you and your descendants forever.” Immediately he went out from before him a leper, white as snow.

'''

xref:012-2-kings/012-2-kings-004.adoc#v12-4-0[&#60; Capítulo Anterior] | <<v12-5-0,Topo>> | xref:012-2-kings/012-2-kings-006.adoc#v12-6-0[Próximo Capítulo &#62;]