include::./index.adoc[]

[[v12-19-0]]
=== The Second of Kings, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-19-1]]

^<<v12-19-1,1>>^ As soon as King Hez·e·kiʹah heard this, he ripped his garments apart and covered himself with sackcloth and went into the house of Jehovah.

[[v12-19-2]]

^<<v12-19-2,2>>^ Then he sent E·liʹa·kim, who was in charge of the household,^&#42;1^ Shebʹnah the secretary, and the elders of the priests, covered with sackcloth, to the prophet Isaiah, the son of Aʹmoz.

[NOTE]
====
. Or “palace.”
====

[[v12-19-3]]

^<<v12-19-3,3>>^ They said to him: “This is what Hez·e·kiʹah says, ‘This day is a day of distress, of rebuke,^&#42;1^ and of disgrace; for the children are ready to be born,^&#42;2^ but there is no strength to give birth.

[NOTE]
====
. Or “insult.”
. Lit., “have come to the opening of the womb.”
====

[[v12-19-4]]

^<<v12-19-4,4>>^ Perhaps Jehovah your God will hear all the words of the Rabʹsha·keh, whom the king of As·syrʹi·a his lord sent to taunt the living God, and he will call him to account for the words that Jehovah your God has heard. So offer up a prayer in behalf of the remnant who have survived.’”

[[v12-19-5]]

^<<v12-19-5,5>>^ So the servants of King Hez·e·kiʹah went in to Isaiah,

[[v12-19-6]]

^<<v12-19-6,6>>^ and Isaiah said to them: “This is what you should say to your lord, ‘This is what Jehovah says: “Do not be afraid because of the words that you heard, the words with which the attendants of the king of As·syrʹi·a blasphemed me.

[[v12-19-7]]

^<<v12-19-7,7>>^ Here I am putting a thought in his mind,^&#42;1^ and he will hear a report and return to his own land; and I will make him fall by the sword in his own land.”’”

[NOTE]
====
. Lit., “a spirit in him.”
====

[[v12-19-8]]

^<<v12-19-8,8>>^ After the Rabʹsha·keh heard that the king of As·syrʹi·a had pulled away from Laʹchish, he returned to him and found him fighting against Libʹnah.

[[v12-19-9]]

^<<v12-19-9,9>>^ Now the king heard it said about King Tir·haʹkah of E·thi·oʹpi·a: “Here he has come out to fight against you.” So he sent messengers again to Hez·e·kiʹah, saying:

[[v12-19-10]]

^<<v12-19-10,10>>^ “This is what you should say to King Hez·e·kiʹah of Judah, ‘Do not let your God in whom you trust deceive you by saying: “Jerusalem will not be given into the hand of the king of As·syrʹi·a.”

[[v12-19-11]]

^<<v12-19-11,11>>^ Look! You have heard what the kings of As·syrʹi·a did to all the lands by devoting them to destruction. Will you alone be rescued?

[[v12-19-12]]

^<<v12-19-12,12>>^ Did the gods of the nations that my forefathers destroyed rescue them? Where are Goʹzan, Haʹran, Reʹzeph, and the people of Eʹden who were in Tel-asʹsar?

[[v12-19-13]]

^<<v12-19-13,13>>^ Where is the king of Haʹmath, the king of Arʹpad, and the king of the cities of Seph·ar·vaʹim, and of Heʹna, and of Ivʹvah?’”

[[v12-19-14]]

^<<v12-19-14,14>>^ Hez·e·kiʹah took the letters out of the hand of the messengers and read them. Hez·e·kiʹah then went up to the house of Jehovah and spread them^&#42;1^ out before Jehovah.

[NOTE]
====
. Lit., “it.”
====

[[v12-19-15]]

^<<v12-19-15,15>>^ And Hez·e·kiʹah began to pray before Jehovah and say: “O Jehovah the God of Israel, sitting enthroned above^&#42;1^ the cherubs, you alone are the true God of all the kingdoms of the earth. You made the heavens and the earth.

[NOTE]
====
. Or possibly, “between.”
====

[[v12-19-16]]

^<<v12-19-16,16>>^ Incline your ear, O Jehovah, and hear! Open your eyes, O Jehovah, and see! Hear the words that Sen·nachʹer·ib has sent to taunt the living God.

[[v12-19-17]]

^<<v12-19-17,17>>^ It is a fact, O Jehovah, that the kings of As·syrʹi·a have devastated the nations and their lands.

[[v12-19-18]]

^<<v12-19-18,18>>^ And they have thrown their gods into the fire, because they were not gods but the work of human hands, wood and stone. That is why they could destroy them.

[[v12-19-19]]

^<<v12-19-19,19>>^ But now, O Jehovah our God, please save us out of his hand, so that all the kingdoms of the earth may know that you alone are God, O Jehovah.”

[[v12-19-20]]

^<<v12-19-20,20>>^ Isaiah son of Aʹmoz then sent this message to Hez·e·kiʹah: “This is what Jehovah the God of Israel says, ‘I have heard your prayer to me concerning King Sen·nachʹer·ib of As·syrʹi·a.

[[v12-19-21]]

^<<v12-19-21,21>>^ This is the word that Jehovah has spoken against him:
“The virgin daughter of Zion despises you, she scoffs at you.
The daughter of Jerusalem shakes her head at you.

[[v12-19-22]]

^<<v12-19-22,22>>^ Whom have you taunted and blasphemed?
Against whom have you raised your voice
And lifted your arrogant eyes?
It is against the Holy One of Israel!

[[v12-19-23]]

^<<v12-19-23,23>>^ Through your messengers you have taunted Jehovah and said,
‘With the multitude of my war chariots
I will ascend the heights of mountains,
The remotest parts of Lebʹa·non.
I will cut down its lofty cedars, its choice juniper trees.
I will enter its farthest retreats, its densest forests.

[[v12-19-24]]

^<<v12-19-24,24>>^ I will dig wells and drink foreign waters;
I will dry up all the streams^&#42;1^ of Egypt with the soles of my feet.’

[NOTE]
====
. Or “the Nile canals.”
====

[[v12-19-25]]

^<<v12-19-25,25>>^ Have you not heard? From long ago it was determined.^&#42;1^
From days gone by I have prepared^&#42;2^ it.
Now I will bring it about.
You will turn fortified cities into desolate piles of ruins.

[NOTE]
====
. Lit., “done.”
. Or “formed.”
====

[[v12-19-26]]

^<<v12-19-26,26>>^ Their inhabitants will be helpless;
They will be terrified and put to shame.
They will become as vegetation of the field and green grass,
As grass of the roofs that is scorched by the east wind.

[[v12-19-27]]

^<<v12-19-27,27>>^ But I well know when you sit, when you go out, when you come in,
And when you are enraged against me,

[[v12-19-28]]

^<<v12-19-28,28>>^ Because your rage against me and your roaring have reached my ears.
So I will put my hook in your nose and my bridle between your lips,
And I will lead you back the way you came.”

[[v12-19-29]]

^<<v12-19-29,29>>^ “‘And this will be the sign for you:^&#42;1^ This year you will eat what grows on its own;^&#42;2^ and in the second year you will eat grain that sprouts from that; but in the third year you will sow seed and reap, and you will plant vineyards and eat their fruitage.

[NOTE]
====
. That is, Hezekiah.
. Or “the growth from spilled kernels of grain.”
====

[[v12-19-30]]

^<<v12-19-30,30>>^ Those of the house of Judah who escape, those who are left, will take root downward and produce fruit upward.

[[v12-19-31]]

^<<v12-19-31,31>>^ For a remnant will go out of Jerusalem and survivors from Mount Zion. The zeal of Jehovah of armies will do this.

[[v12-19-32]]

^<<v12-19-32,32>>^ “‘Therefore this is what Jehovah says about the king of As·syrʹi·a:
“He will not come into this city
Or shoot an arrow there
Or confront it with a shield
Or cast up a siege rampart against it.

[[v12-19-33]]

^<<v12-19-33,33>>^ By the way he came he will return;
He will not come into this city,” declares Jehovah.

[[v12-19-34]]

^<<v12-19-34,34>>^ “I will defend this city and save it for my own sake
And for the sake of my servant David.”’”

[[v12-19-35]]

^<<v12-19-35,35>>^ On that very night the angel of Jehovah went out and struck down 185,000 men in the camp of the As·syrʹi·ans. When people rose up early in the morning, they saw all the dead bodies.

[[v12-19-36]]

^<<v12-19-36,36>>^ So King Sen·nachʹer·ib of As·syrʹi·a departed and returned to Ninʹe·veh and stayed there.

[[v12-19-37]]

^<<v12-19-37,37>>^ And as he was bowing down at the house^&#42;1^ of his god Nisʹroch, his own sons A·dramʹme·lech and Shar·eʹzer struck him down with the sword and then escaped to the land of Arʹa·rat. And his son Eʹsar-hadʹdon became king in his place.

[NOTE]
====
. Or “temple.”
====

'''

xref:012-2-kings/012-2-kings-018.adoc#v12-18-0[&#60; Capítulo Anterior] | <<v12-19-0,Topo>> | xref:012-2-kings/012-2-kings-020.adoc#v12-20-0[Próximo Capítulo &#62;]