include::./index.adoc[]

[[v12-8-0]]
=== The Second of Kings, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-8-1]]

^<<v12-8-1,1>>^ E·liʹsha said to the woman whose son he had restored to life:^&#42;1^ “Rise up and go, you with your household, and live as a foreigner wherever you can, for Jehovah has declared a famine, and it will come on the land for seven years.”

[NOTE]
====
. Or “had revived.”
====

[[v12-8-2]]

^<<v12-8-2,2>>^ So the woman got up and did what the man of the true God said. She went with her household and settled in the land of the Phi·lisʹtines for seven years.

[[v12-8-3]]

^<<v12-8-3,3>>^ At the end of seven years, the woman returned from the land of the Phi·lisʹtines and went to appeal to the king for her house and her field.

[[v12-8-4]]

^<<v12-8-4,4>>^ Now the king was speaking to Ge·haʹzi the attendant of the man of the true God, saying: “Relate to me, please, all the great things that E·liʹsha has done.”

[[v12-8-5]]

^<<v12-8-5,5>>^ Just as he was relating to the king how he had restored the dead one to life, the woman whose son he had restored to life came to the king, appealing for her house and her field. At once Ge·haʹzi said: “My lord the king, this is the woman, and this is her son, whom E·liʹsha restored to life.”

[[v12-8-6]]

^<<v12-8-6,6>>^ At that the king asked the woman, and she related the story to him. Then the king assigned her a court official, telling him: “Return all that belongs to her and all the products of the field from the day she left the land until now.”

[[v12-8-7]]

^<<v12-8-7,7>>^ E·liʹsha came to Damascus when Ben-haʹdad the king of Syria was sick. So the report was made to him: “The man of the true God has come here.”

[[v12-8-8]]

^<<v12-8-8,8>>^ At that the king said to Hazʹa·el: “Take a gift with you and go and meet the man of the true God. Inquire of Jehovah through him, asking, ‘Will I recover from this sickness?’”

[[v12-8-9]]

^<<v12-8-9,9>>^ Hazʹa·el went to meet him and took a gift with him, every sort of good thing of Damascus, the load of 40 camels. He came and stood before him and said: “Your son, Ben-haʹdad the king of Syria, has sent me to you, asking, ‘Will I recover from this sickness?’”

[[v12-8-10]]

^<<v12-8-10,10>>^ E·liʹsha replied to him: “Go and tell him, ‘You will certainly recover,’ but Jehovah has shown me that he will certainly die.”

[[v12-8-11]]

^<<v12-8-11,11>>^ And he kept staring at him to the point of embarrassment. Then the man of the true God gave way to weeping.

[[v12-8-12]]

^<<v12-8-12,12>>^ Hazʹa·el asked: “Why is my lord weeping?” He replied: “Because I know what harm you will do to the people of Israel. Their fortified places you will set on fire, their choice men you will kill with the sword, their children you will dash to pieces, and their pregnant women you will rip open.”

[[v12-8-13]]

^<<v12-8-13,13>>^ Hazʹa·el said: “How could your servant, who is a mere dog, do such a deed?” But E·liʹsha said: “Jehovah has shown me that you will be king over Syria.”

[[v12-8-14]]

^<<v12-8-14,14>>^ Then he left E·liʹsha and returned to his own lord, who said to him: “What did E·liʹsha say to you?” He replied: “He told me that you will certainly recover.”

[[v12-8-15]]

^<<v12-8-15,15>>^ But the next day, Hazʹa·el took a coverlet, dipped it in water, and held^&#42;1^ it over his face until he died. And Hazʹa·el became king in his place.

[NOTE]
====
. Or “placed.”
====

[[v12-8-16]]

^<<v12-8-16,16>>^ In the fifth year of Je·hoʹram the son of Aʹhab the king of Israel, while Je·hoshʹa·phat was king of Judah, Je·hoʹram the son of King Je·hoshʹa·phat of Judah became king.

[[v12-8-17]]

^<<v12-8-17,17>>^ He was 32 years old when he became king, and he reigned for eight years in Jerusalem.

[[v12-8-18]]

^<<v12-8-18,18>>^ He walked in the way of the kings of Israel, just as those of the house of Aʹhab had done, for Aʹhab’s daughter had become his wife; and he kept doing what was bad in Jehovah’s eyes.

[[v12-8-19]]

^<<v12-8-19,19>>^ But Jehovah did not want to bring Judah to ruin for the sake of David his servant, since he had promised him to give a lamp to him and to his sons always.

[[v12-8-20]]

^<<v12-8-20,20>>^ In his days Eʹdom revolted against Judah and then set up its own king.

[[v12-8-21]]

^<<v12-8-21,21>>^ So Je·hoʹram crossed over to Zaʹir with all his chariots, and he rose up by night and defeated the Eʹdom·ites who were surrounding him and the chariot commanders; and the troops fled to their tents.

[[v12-8-22]]

^<<v12-8-22,22>>^ But Eʹdom has kept up its revolt against Judah to this day. Libʹnah also revolted at that time.

[[v12-8-23]]

^<<v12-8-23,23>>^ And the rest of the history of Je·hoʹram, all that he did, is it not written in the book of the history of the times of the kings of Judah?

[[v12-8-24]]

^<<v12-8-24,24>>^ Then Je·hoʹram was laid to rest with his forefathers and was buried with his forefathers in the City of David. And his son A·ha·ziʹah became king in his place.

[[v12-8-25]]

^<<v12-8-25,25>>^ In the 12th year of Je·hoʹram the son of Aʹhab the king of Israel, A·ha·ziʹah the son of King Je·hoʹram of Judah became king.

[[v12-8-26]]

^<<v12-8-26,26>>^ A·ha·ziʹah was 22 years old when he became king, and he reigned for one year in Jerusalem. His mother’s name was Ath·a·liʹah the granddaughter^&#42;1^ of King Omʹri of Israel.

[NOTE]
====
. Lit., “daughter.”
====

[[v12-8-27]]

^<<v12-8-27,27>>^ He walked in the way of the house of Aʹhab and kept doing what was bad in Jehovah’s eyes, like the house of Aʹhab, for he was related to the house of Aʹhab by marriage.

[[v12-8-28]]

^<<v12-8-28,28>>^ So he went with Je·hoʹram the son of Aʹhab to wage war against King Hazʹa·el of Syria at Raʹmoth-gilʹe·ad, but the Syrians wounded Je·hoʹram.

[[v12-8-29]]

^<<v12-8-29,29>>^ So King Je·hoʹram returned to Jezʹre·el to recover from the wounds that the Syrians had inflicted on him at Raʹmah when he fought against King Hazʹa·el of Syria. A·ha·ziʹah the son of Je·hoʹram the king of Judah went down to Jezʹre·el to see Je·hoʹram the son of Aʹhab, because he had been wounded.^&#42;1^

[NOTE]
====
. Or “he was sick.”
====

'''

xref:012-2-kings/012-2-kings-007.adoc#v12-7-0[&#60; Capítulo Anterior] | <<v12-8-0,Topo>> | xref:012-2-kings/012-2-kings-009.adoc#v12-9-0[Próximo Capítulo &#62;]