include::./index.adoc[]

[[v12-12-0]]
=== The Second of Kings, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-12-1]]

^<<v12-12-1,1>>^ In the seventh year of Jeʹhu, Je·hoʹash became king, and he reigned for 40 years in Jerusalem. His mother’s name was Zibʹi·ah from Beʹer-sheʹba.

[[v12-12-2]]

^<<v12-12-2,2>>^ Je·hoʹash continued doing what was right in Jehovah’s eyes all the days that Je·hoiʹa·da the priest instructed him.

[[v12-12-3]]

^<<v12-12-3,3>>^ However, the high places were not removed, and the people were still sacrificing and making sacrificial smoke on the high places.

[[v12-12-4]]

^<<v12-12-4,4>>^ Je·hoʹash said to the priests: “Take all the money that is brought to the house of Jehovah for the holy offerings, the money for which each one is assessed, the money given as an estimated value for a person,^&#42;1^ and all the money that each person’s heart is moved to bring to the house of Jehovah.

[NOTE]
====
. Or “soul.”
====

[[v12-12-5]]

^<<v12-12-5,5>>^ The priests will personally take it from their donors^&#42;1^ and use it to repair the house, wherever any damage is^&#42;2^ found.”

[NOTE]
====
. Or “acquaintances.”
. Or “cracks are.”
====

[[v12-12-6]]

^<<v12-12-6,6>>^ By the 23rd year of King Je·hoʹash, the priests had not yet repaired the damage to the house.

[[v12-12-7]]

^<<v12-12-7,7>>^ So King Je·hoʹash called Je·hoiʹa·da the priest and the other priests and said to them: “Why are you not repairing the damage to the house? Therefore, do not take any more money from your donors unless it is used to repair the house.”

[[v12-12-8]]

^<<v12-12-8,8>>^ At that the priests agreed not to take any more money from the people and not to be responsible for repairing the house.

[[v12-12-9]]

^<<v12-12-9,9>>^ Je·hoiʹa·da the priest then took a chest and bored a hole in its lid and put it next to the altar on the right as one enters the house of Jehovah. That is where the priests who served as doorkeepers would put all the money that was brought into the house of Jehovah.

[[v12-12-10]]

^<<v12-12-10,10>>^ Whenever they saw that there was a great deal of money in the chest, the secretary of the king and the high priest would come up and collect^&#42;1^ and count the money that had been brought to the house of Jehovah.

[NOTE]
====
. Or “put into bags.” Lit., “bind.”
====

[[v12-12-11]]

^<<v12-12-11,11>>^ They would give the money that had been counted to those appointed over the work being done in the house of Jehovah. They, in turn, paid it to the woodworkers and to the builders who were working at the house of Jehovah,

[[v12-12-12]]

^<<v12-12-12,12>>^ as well as to the masons and the stonecutters. They also bought timbers and hewn stones for repairing the damage to the house of Jehovah and used the money for all the other expenses incurred in repairing the house.

[[v12-12-13]]

^<<v12-12-13,13>>^ However, none of the money brought to the house of Jehovah was used to make basins of silver, extinguishers, bowls, trumpets, or any sort of gold or silver article for the house of Jehovah.

[[v12-12-14]]

^<<v12-12-14,14>>^ They would give it only to those who did the work, and with it they repaired the house of Jehovah.

[[v12-12-15]]

^<<v12-12-15,15>>^ They would not call for an accounting from the men to whom they gave the money to give to the workers, for they were trustworthy.

[[v12-12-16]]

^<<v12-12-16,16>>^ However, the money for guilt offerings and the money for sin offerings was not brought to the house of Jehovah; it belonged to the priests.

[[v12-12-17]]

^<<v12-12-17,17>>^ It was then that Hazʹa·el the king of Syria went up to fight against Gath, and he captured it, after which he decided to attack^&#42;1^ Jerusalem.

[NOTE]
====
. Lit., “Hazael set his face to go up against.”
====

[[v12-12-18]]

^<<v12-12-18,18>>^ At that King Je·hoʹash of Judah took all the holy offerings that his forefathers Je·hoshʹa·phat, Je·hoʹram, and A·ha·ziʹah, the kings of Judah, had sanctified, as well as his own holy offerings and all the gold to be found in the treasuries of the house of Jehovah and the king’s house,^&#42;1^ and sent them to Hazʹa·el the king of Syria. So he withdrew from Jerusalem.

[NOTE]
====
. Or “palace.”
====

[[v12-12-19]]

^<<v12-12-19,19>>^ As for the rest of the history of Je·hoʹash, all that he did, is it not written in the book of the history of the times of the kings of Judah?

[[v12-12-20]]

^<<v12-12-20,20>>^ However, his servants joined in a conspiracy against him and struck Je·hoʹash down at the house of the Mound,^&#42;1^ on the way that goes down to Silʹla.

[NOTE]
====
. Or “at Beth-millo.”
====

[[v12-12-21]]

^<<v12-12-21,21>>^ His servants Joʹza·car the son of Shimʹe·ath and Je·hozʹa·bad the son of Shoʹmer were the ones who struck him and put him to death. They buried him with his forefathers in the City of David, and his son Am·a·ziʹah became king in his place.

'''

xref:012-2-kings/012-2-kings-011.adoc#v12-11-0[&#60; Capítulo Anterior] | <<v12-12-0,Topo>> | xref:012-2-kings/012-2-kings-013.adoc#v12-13-0[Próximo Capítulo &#62;]