include::./index.adoc[]

[[v12-4-0]]
=== The Second of Kings, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-4-1]]

^<<v12-4-1,1>>^ Now one of the wives of the sons of the prophets cried out to E·liʹsha, saying: “Your servant my husband is dead, and you well know that your servant had always feared Jehovah. Now a creditor has come to take both of my children as his slaves.”

[[v12-4-2]]

^<<v12-4-2,2>>^ At this E·liʹsha said to her: “What can I do for you? Tell me, what do you have in the house?” She replied: “Your servant has nothing at all in the house but a jar^&#42;1^ of oil.”

[NOTE]
====
. Or “spouted jar.”
====

[[v12-4-3]]

^<<v12-4-3,3>>^ Then he said: “Go outside, ask for containers from all your neighbors, empty containers. Do not limit yourself to a few.

[[v12-4-4]]

^<<v12-4-4,4>>^ Then go in and close the door behind you and your sons. Fill all these containers, and set the full ones aside.”

[[v12-4-5]]

^<<v12-4-5,5>>^ So she left him.
When she closed the door behind her and her sons, they passed the containers to her, and she kept pouring.

[[v12-4-6]]

^<<v12-4-6,6>>^ When the containers were full, she said to one of her sons: “Bring another container to me.” But he said to her: “There are no more containers.” At that the oil stopped.

[[v12-4-7]]

^<<v12-4-7,7>>^ So she came in and told the man of the true God, and he said: “Go, sell the oil and pay off your debts, and you and your sons can live from what is left.”

[[v12-4-8]]

^<<v12-4-8,8>>^ One day E·liʹsha went to Shuʹnem, where there was a prominent woman, and she urged him to eat a meal there. As often as he would pass by, he would stop there to eat.

[[v12-4-9]]

^<<v12-4-9,9>>^ So she said to her husband: “I know that it is a holy man of God who comes this way regularly.

[[v12-4-10]]

^<<v12-4-10,10>>^ Please, let us make a small room on the roof and put there for him a bed, a table, a chair, and a lampstand. Then, whenever he comes to us, he can stay there.”

[[v12-4-11]]

^<<v12-4-11,11>>^ One day he came there, and he went to the room on the roof to lie down.

[[v12-4-12]]

^<<v12-4-12,12>>^ He then said to Ge·haʹzi his attendant: “Call this Shuʹnam·mite woman.” So he called her, and she stood before him.

[[v12-4-13]]

^<<v12-4-13,13>>^ Then he said to Ge·haʹzi: “Please tell her, ‘Here you have gone to all this trouble for us. What can be done for you? Should I speak in your behalf to the king or to the chief of the army?’” But her reply was: “I am living among my own people.”

[[v12-4-14]]

^<<v12-4-14,14>>^ So he said: “Then what can be done for her?” Ge·haʹzi now said: “Well, she does not have a son, and her husband is old.”

[[v12-4-15]]

^<<v12-4-15,15>>^ Immediately he said: “Call her.” So he called her, and she stood at the doorway.

[[v12-4-16]]

^<<v12-4-16,16>>^ Then he said: “At this time next year, you will be embracing a son.” But she said: “No, my master, man of the true God! Do not tell lies to your servant.”

[[v12-4-17]]

^<<v12-4-17,17>>^ However, the woman became pregnant and gave birth to a son at the same time the next year, just as E·liʹsha had told her.

[[v12-4-18]]

^<<v12-4-18,18>>^ The child grew up, and one day he went out to his father, who was with the reapers.

[[v12-4-19]]

^<<v12-4-19,19>>^ He kept saying to his father: “My head, O my head!” Then his father said to the attendant: “Carry him to his mother.”

[[v12-4-20]]

^<<v12-4-20,20>>^ So he carried him back to his mother, and he sat on her lap until noon, and then he died.

[[v12-4-21]]

^<<v12-4-21,21>>^ Then she went up and laid him on the bed of the man of the true God, and she shut the door behind her and left.

[[v12-4-22]]

^<<v12-4-22,22>>^ She now called her husband and said: “Send me, please, one of the attendants and one of the donkeys, and let me go quickly to the man of the true God and return.”

[[v12-4-23]]

^<<v12-4-23,23>>^ But he said: “Why are you going to see him today? It is not a new moon or a sabbath.” However, she said: “Everything is all right.”

[[v12-4-24]]

^<<v12-4-24,24>>^ So she saddled the donkey and said to her attendant: “Go quickly. Do not slow down for me unless I tell you to.”

[[v12-4-25]]

^<<v12-4-25,25>>^ So she went to the man of the true God at Mount Carʹmel. As soon as the man of the true God saw her from afar, he said to Ge·haʹzi his attendant: “Look! The Shuʹnam·mite woman is over there.

[[v12-4-26]]

^<<v12-4-26,26>>^ Please run to meet her and ask her, ‘Are you well? Is your husband well? Is your child well?’” To this she said: “All is well.”

[[v12-4-27]]

^<<v12-4-27,27>>^ When she came to the man of the true God at the mountain, she at once grabbed hold of his feet. At this Ge·haʹzi came near to push her away, but the man of the true God said: “Let her alone, for she is in bitter distress,^&#42;1^ and Jehovah has hidden it from me and has not told me.”

[NOTE]
====
. Or “for her soul is bitter within her.”
====

[[v12-4-28]]

^<<v12-4-28,28>>^ She then said: “Did I ask my lord for a son? Did I not say, ‘You must not give me a false hope’?”

[[v12-4-29]]

^<<v12-4-29,29>>^ He immediately said to Ge·haʹzi: “Wrap your garments around your waist and take my staff in your hand and go. If you encounter anyone, do not greet him; and if anyone should greet you, do not answer him. Go and place my staff on the boy’s face.”

[[v12-4-30]]

^<<v12-4-30,30>>^ At this the boy’s mother said: “As surely as Jehovah is living and as you yourself are^&#42;1^ living, I will not leave you.” So he got up and went with her.

[NOTE]
====
. Or “your soul is.”
====

[[v12-4-31]]

^<<v12-4-31,31>>^ Ge·haʹzi went before them and put the staff on the boy’s face, but there was no sound or response. He went back to meet E·liʹsha and told him: “The boy did not wake up.”

[[v12-4-32]]

^<<v12-4-32,32>>^ When E·liʹsha came into the house, the boy was lying dead on his bed.

[[v12-4-33]]

^<<v12-4-33,33>>^ He went in and closed the door behind them both and began to pray to Jehovah.

[[v12-4-34]]

^<<v12-4-34,34>>^ Then he got up on the bed and lay down on the child and put his own mouth on the boy’s mouth, his own eyes on his eyes, and his own palms on his palms and kept bent over him, and the child’s body started to grow warm.

[[v12-4-35]]

^<<v12-4-35,35>>^ He walked back and forth in the house, and he got up on the bed and bent over him again. The boy sneezed seven times, after which he opened his eyes.

[[v12-4-36]]

^<<v12-4-36,36>>^ E·liʹsha now called Ge·haʹzi and said: “Call the Shuʹnam·mite woman.” So he called her and she came in to him. Then he said: “Pick up your son.”

[[v12-4-37]]

^<<v12-4-37,37>>^ And she came in and fell at his feet and bowed down to the ground before him, after which she picked up her son and went out.

[[v12-4-38]]

^<<v12-4-38,38>>^ When E·liʹsha returned to Gilʹgal, there was famine in the land. The sons of the prophets were sitting before him, and he said to his attendant: “Put the large pot on and boil stew for the sons of the prophets.”

[[v12-4-39]]

^<<v12-4-39,39>>^ So one of them went out to the field to pick mallows, and he found a wild vine and picked wild gourds from it, filling his garment. He then returned and sliced them into the stewpot, not knowing what they were.

[[v12-4-40]]

^<<v12-4-40,40>>^ They later served it to the men to eat, but as soon as they ate from the stew, they cried out: “There is death in the pot, O man of the true God.” And they could not eat it.

[[v12-4-41]]

^<<v12-4-41,41>>^ So he said: “Bring some flour.” After he threw it into the pot, he said: “Serve it to the people.” And nothing harmful was in the pot.

[[v12-4-42]]

^<<v12-4-42,42>>^ A man came from Baʹal-shalʹi·shah, and he brought the man of the true God 20 loaves of barley bread made from the first ripe fruits, as well as a bag of new grain. Then E·liʹsha said: “Give it to the people so that they may eat.”

[[v12-4-43]]

^<<v12-4-43,43>>^ However, his attendant said: “How can I set this before 100 men?” To this he said: “Give it to the people so that they may eat, for this is what Jehovah says, ‘They will eat and have some left over.’”

[[v12-4-44]]

^<<v12-4-44,44>>^ At that he put it before them, and they ate and they had some left over, according to the word of Jehovah.

'''

xref:012-2-kings/012-2-kings-003.adoc#v12-3-0[&#60; Capítulo Anterior] | <<v12-4-0,Topo>> | xref:012-2-kings/012-2-kings-005.adoc#v12-5-0[Próximo Capítulo &#62;]