include::./index.adoc[]

[[v12-7-0]]
=== The Second of Kings, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-7-1]]

^<<v12-7-1,1>>^ E·liʹsha now said, “Listen to the word of Jehovah. This is what Jehovah says: ‘Tomorrow about this time at the gate^&#42;1^ of Sa·marʹi·a, a seah measure^&#42;2^ of fine flour will be worth a shekel,^&#42;3^ and two seah measures of barley will be worth a shekel.’”

[NOTE]
====
. Or “markets.”
. A seah equaled 7.33 L (6.66 dry qt). See App. B14.
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v12-7-2]]

^<<v12-7-2,2>>^ At that the adjutant whom the king relied on said to the man of the true God: “Even if Jehovah should open floodgates in the heavens, could this^&#42;1^ possibly take place?” To that he said: “You will see it with your own eyes, but you will not eat from it.”

[NOTE]
====
. Lit., “this word.”
====

[[v12-7-3]]

^<<v12-7-3,3>>^ There were four lepers at the entrance of the city gate, and they said to one another: “Why are we sitting here until we die?

[[v12-7-4]]

^<<v12-7-4,4>>^ If we say, ‘Let us go into the city,’ while the famine is in the city, we would die there. And if we sit here, we will die anyway. So now let us go over to the camp of the Syrians. If they spare our lives, we will live, but if they put us to death, then we will die.”

[[v12-7-5]]

^<<v12-7-5,5>>^ They then got up in the evening darkness and entered the camp of the Syrians. When they reached the outskirts of the Syrian camp, there was nobody there.

[[v12-7-6]]

^<<v12-7-6,6>>^ For Jehovah had caused the Syrian camp to hear the sound of war chariots and horses, the sound of a huge army. So they said to one another: “Look! The king of Israel has hired the kings of the Hitʹtites and the kings of Egypt to come against us!”

[[v12-7-7]]

^<<v12-7-7,7>>^ They immediately got up and fled in the evening darkness, leaving their tents, horses, donkeys, and the whole camp just as it was, and they fled for their lives.^&#42;1^

[NOTE]
====
. Or “souls.”
====

[[v12-7-8]]

^<<v12-7-8,8>>^ When these lepers reached the outskirts of the camp, they entered into one of the tents and began to eat and drink. They carried away from there silver, gold, and garments and went and hid them. Then they returned and entered another tent and carried things away from there and went and hid them.

[[v12-7-9]]

^<<v12-7-9,9>>^ Finally they said to one another: “What we are doing is not right. This day is a day of good news! If we hesitate and wait until dawn, we will deserve to be punished. Let us now go and report this at the king’s house.”

[[v12-7-10]]

^<<v12-7-10,10>>^ So they went and called out to the gatekeepers of the city and reported to them: “We went into the camp of the Syrians, but nobody was there—we did not hear anyone at all. There were only the horses and donkeys tied and the tents left just as they were.”

[[v12-7-11]]

^<<v12-7-11,11>>^ At once the gatekeepers called out, and it was reported inside the king’s house.

[[v12-7-12]]

^<<v12-7-12,12>>^ Immediately the king got up by night and said to his servants: “Please let me tell you what the Syrians have done to us. They know that we are hungry, so they left the camp to hide in the field, saying, ‘They will come out of the city, and we will catch them alive and enter into the city.’”

[[v12-7-13]]

^<<v12-7-13,13>>^ Then one of his servants said: “Please, let some men take five of the remaining horses that are in the city. Look! They will end up the same as all the crowd of Israel that remain here. Look! They will end up the same as all the crowd of Israel that perished. Let us then send them out and see.”

[[v12-7-14]]

^<<v12-7-14,14>>^ So they took two chariots with horses, and the king sent them out to the camp of the Syrians, saying: “Go and see.”

[[v12-7-15]]

^<<v12-7-15,15>>^ They followed them as far as the Jordan, and the entire way was covered with garments and utensils that the Syrians had thrown away as they fled in panic. The messengers returned and reported it to the king.

[[v12-7-16]]

^<<v12-7-16,16>>^ The people then went out and plundered the camp of the Syrians, so that a seah measure of fine flour came to be worth a shekel, and two seah measures of barley came to be worth a shekel, according to the word of Jehovah.

[[v12-7-17]]

^<<v12-7-17,17>>^ The king had appointed the adjutant whom he relied on to be in charge of the gate, but the people trampled him to death at the gate, just as the man of the true God had told the king when he came down to him.

[[v12-7-18]]

^<<v12-7-18,18>>^ It happened just as the man of the true God had said to the king: “Two seah measures of barley will be worth a shekel, and a seah measure of fine flour will be worth a shekel tomorrow at this time at the gate of Sa·marʹi·a.”

[[v12-7-19]]

^<<v12-7-19,19>>^ But the adjutant had said to the man of the true God: “Even if Jehovah should open floodgates in the heavens, could such a thing^&#42;1^ take place?” To this E·liʹsha had said: “You will see it with your own eyes, but you will not eat from it.”

[NOTE]
====
. Lit., “such a word as this.”
====

[[v12-7-20]]

^<<v12-7-20,20>>^ That is exactly what happened to him, because the people trampled him to death at the gate.

'''

xref:012-2-kings/012-2-kings-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-2-kings/012-2-kings-008.adoc#v12-8-0[Próximo Capítulo &#62;]