include::./index.adoc[]

[[v12-6-0]]
=== The Second of Kings, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-6-1]]

^<<v12-6-1,1>>^ The sons of the prophets said to E·liʹsha: “Look! The place where we are staying with you is too cramped for us.

[[v12-6-2]]

^<<v12-6-2,2>>^ Please let us go to the Jordan. Let each of us take a log from there and make a place there where we can dwell.” He said: “Go.”

[[v12-6-3]]

^<<v12-6-3,3>>^ One of them said: “Will you please come along with your servants?” At that he said: “I will come.”

[[v12-6-4]]

^<<v12-6-4,4>>^ So he went with them, and they came to the Jordan and began to cut down the trees.

[[v12-6-5]]

^<<v12-6-5,5>>^ As one of them was cutting down a tree, the axhead fell into the water, and he cried out: “Alas, my master, it was borrowed!”

[[v12-6-6]]

^<<v12-6-6,6>>^ The man of the true God said: “Where did it fall?” So he showed him the place. He then cut off a piece of wood and threw it there and made the axhead float.

[[v12-6-7]]

^<<v12-6-7,7>>^ He said: “Lift it out.” So he reached out his hand and took it.

[[v12-6-8]]

^<<v12-6-8,8>>^ Now the king of Syria went to war against Israel. He consulted with his servants and said: “I will encamp at such and such a place with you.”

[[v12-6-9]]

^<<v12-6-9,9>>^ Then the man of the true God sent word to the king of Israel, saying: “Beware of passing by this place, because that is where the Syrians are coming down.”

[[v12-6-10]]

^<<v12-6-10,10>>^ So the king of Israel sent word to the place that the man of the true God had warned him about. He kept warning him, and he stayed away from there on several occasions.^&#42;1^

[NOTE]
====
. Or “more than once or twice.”
====

[[v12-6-11]]

^<<v12-6-11,11>>^ This enraged the king^&#42;1^ of Syria, so he summoned his servants and said to them: “Tell me! Who among us is on the side of the king of Israel?”

[NOTE]
====
. Lit., “the heart of the king.”
====

[[v12-6-12]]

^<<v12-6-12,12>>^ Then one of his servants said: “None of us, my lord the king! It is E·liʹsha the prophet in Israel who tells the king of Israel the things that you say in your own bedroom.”

[[v12-6-13]]

^<<v12-6-13,13>>^ He said: “Go and find out where he is, so that I may send men to capture him.” Later the report was made to him: “He is in Doʹthan.”

[[v12-6-14]]

^<<v12-6-14,14>>^ He immediately sent horses and war chariots there, as well as a large army; they came by night and surrounded the city.

[[v12-6-15]]

^<<v12-6-15,15>>^ When the attendant^&#42;1^ of the man of the true God rose early and went outside, he saw that an army with horses and war chariots was surrounding the city. At once the attendant said to him: “Alas, my master! What are we to do?”

[NOTE]
====
. Or “minister.”
====

[[v12-6-16]]

^<<v12-6-16,16>>^ But he said: “Do not be afraid! For there are more who are with us than those who are with them.”

[[v12-6-17]]

^<<v12-6-17,17>>^ Then E·liʹsha began to pray and say: “O Jehovah, open his eyes, please, that he may see.” Immediately Jehovah opened the attendant’s eyes and he saw, and look! the mountainous region was full of horses and war chariots of fire all around E·liʹsha.

[[v12-6-18]]

^<<v12-6-18,18>>^ When the Syrians came down to him, E·liʹsha prayed to Jehovah and said: “Please, strike this nation with blindness.” So he struck them with blindness, just as E·liʹsha had requested.

[[v12-6-19]]

^<<v12-6-19,19>>^ E·liʹsha now said to them: “This is not the way, and this is not the city. Follow me, and let me lead you to the man you are looking for.” However, he led them to Sa·marʹi·a.

[[v12-6-20]]

^<<v12-6-20,20>>^ When they arrived in Sa·marʹi·a, E·liʹsha said: “O Jehovah, open their eyes so that they may see.” So Jehovah opened their eyes, and they saw that they were in the middle of Sa·marʹi·a.

[[v12-6-21]]

^<<v12-6-21,21>>^ When the king of Israel saw them, he said to E·liʹsha: “Should I strike them down, should I strike them down, my father?”

[[v12-6-22]]

^<<v12-6-22,22>>^ But he said: “You must not strike them down. Do you strike down those whom you have taken captive with your sword and with your bow? Give them bread and water so they may eat and drink and return to their lord.”

[[v12-6-23]]

^<<v12-6-23,23>>^ So he spread a great feast for them, and they ate and drank, after which he sent them away to return to their lord. And not once did the marauder bands of the Syrians come again into the land of Israel.

[[v12-6-24]]

^<<v12-6-24,24>>^ Afterward Ben-haʹdad the king of Syria gathered all his army^&#42;1^ together and went up and besieged Sa·marʹi·a.

[NOTE]
====
. Lit., “camp.”
====

[[v12-6-25]]

^<<v12-6-25,25>>^ So there was a great famine in Sa·marʹi·a, and they besieged it until a donkey’s head was worth 80 silver pieces, and a fourth of a cab measure^&#42;1^ of dove’s droppings was worth 5 silver pieces.

[NOTE]
====
. A cab equaled 1.22 L (1.11 dry qt). See App. B14.
====

[[v12-6-26]]

^<<v12-6-26,26>>^ As the king of Israel was passing by on the wall, a woman cried out to him: “Help us, O my lord the king!”

[[v12-6-27]]

^<<v12-6-27,27>>^ To this he said: “If Jehovah does not help you, where can I get help for you? From the threshing floor? Or from the wine or oil press?”

[[v12-6-28]]

^<<v12-6-28,28>>^ The king asked her: “What is the matter with you?” She replied: “This woman said to me, ‘Hand over your son, and we will eat him today, and we will eat my son tomorrow.’

[[v12-6-29]]

^<<v12-6-29,29>>^ So we boiled my son and ate him. The next day I said to her, ‘Hand over your son so that we may eat him.’ But she hid her son.”

[[v12-6-30]]

^<<v12-6-30,30>>^ As soon as the king heard the woman’s words, he ripped his garments apart. When he passed by on the wall, the people saw that he was wearing sackcloth under his clothes.^&#42;1^

[NOTE]
====
. Or “underneath, next to his skin.”
====

[[v12-6-31]]

^<<v12-6-31,31>>^ Then he said: “So may God do to me and add to it if the head of E·liʹsha the son of Shaʹphat remains on him today!”

[[v12-6-32]]

^<<v12-6-32,32>>^ E·liʹsha was sitting in his house, and the elders were sitting with him. The king sent a man ahead of him, but before the messenger arrived, E·liʹsha said to the elders: “Have you seen how this son of a murderer has sent to take off my head? Watch when the messenger comes, close the door, and hold the door shut against him. Is not the sound of his lord’s footsteps behind him?”

[[v12-6-33]]

^<<v12-6-33,33>>^ While he was still speaking with them, the messenger came to him, and the king said: “This calamity is from Jehovah. Why should I wait any longer for Jehovah?”

'''

xref:012-2-kings/012-2-kings-005.adoc#v12-5-0[&#60; Capítulo Anterior] | <<v12-6-0,Topo>> | xref:012-2-kings/012-2-kings-007.adoc#v12-7-0[Próximo Capítulo &#62;]