include::./index.adoc[]

[[v12-17-0]]
=== The Second of Kings, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-17-1]]

^<<v12-17-1,1>>^ In the 12th year of King Aʹhaz of Judah, Ho·sheʹa the son of Eʹlah became king over Israel in Sa·marʹi·a; he ruled for nine years.

[[v12-17-2]]

^<<v12-17-2,2>>^ He continued to do what was bad in Jehovah’s eyes, only not to the extent of the kings of Israel prior to him.

[[v12-17-3]]

^<<v12-17-3,3>>^ King Shal·man·eʹser of As·syrʹi·a came up against him, and Ho·sheʹa became his servant and began to pay tribute to him.

[[v12-17-4]]

^<<v12-17-4,4>>^ However, the king of As·syrʹi·a learned that Ho·sheʹa was involved in a conspiracy, for he had sent messengers to King So of Egypt and did not bring the tribute up to the king of As·syrʹi·a as in former years. Therefore, the king of As·syrʹi·a kept him confined and bound in prison.

[[v12-17-5]]

^<<v12-17-5,5>>^ The king of As·syrʹi·a invaded the entire land, and he came to Sa·marʹi·a and laid siege to it for three years.

[[v12-17-6]]

^<<v12-17-6,6>>^ In the ninth year of Ho·sheʹa, the king of As·syrʹi·a captured Sa·marʹi·a. He then led the people of Israel into exile in As·syrʹi·a and made them dwell in Haʹlah and in Haʹbor at the river Goʹzan and in the cities of the Medes.

[[v12-17-7]]

^<<v12-17-7,7>>^ This happened because the people of Israel had sinned against Jehovah their God, who brought them up out of the land of Egypt from under the control of Pharʹaoh king of Egypt. They worshipped^&#42;1^ other gods,

[NOTE]
====
. Lit., “feared.”
====

[[v12-17-8]]

^<<v12-17-8,8>>^ they followed the customs of the nations that Jehovah had driven out from before the Israelites, and they followed the customs that the kings of Israel had established.

[[v12-17-9]]

^<<v12-17-9,9>>^ The Israelites were pursuing the things that were not right according to Jehovah their God. They kept building high places in all their cities, from watchtower to fortified city.^&#42;1^

[NOTE]
====
. That is, in every place, whether sparsely inhabited or populous.
====

[[v12-17-10]]

^<<v12-17-10,10>>^ They kept setting up for themselves sacred pillars and sacred poles^&#42;1^ on every high hill and under every luxuriant tree;

[NOTE]
====
. See Glossary.
====

[[v12-17-11]]

^<<v12-17-11,11>>^ and on all the high places they would make sacrificial smoke just as the nations did that Jehovah had driven into exile from before them. They kept doing wicked things to offend Jehovah.

[[v12-17-12]]

^<<v12-17-12,12>>^ They continued to serve disgusting idols,^&#42;1^ about which Jehovah had told them: “You must not do this!”

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v12-17-13]]

^<<v12-17-13,13>>^ Jehovah kept warning Israel and Judah through all his prophets and every visionary, saying: “Turn back from your wicked ways! Keep my commandments and my statutes according to all the law that I commanded your forefathers and that I sent to you through my servants the prophets.”

[[v12-17-14]]

^<<v12-17-14,14>>^ But they did not listen, and they remained just as stubborn as^&#42;1^ their forefathers who had not shown faith in Jehovah their God.

[NOTE]
====
. Lit., “hardened their neck like the neck of.”
====

[[v12-17-15]]

^<<v12-17-15,15>>^ They continued rejecting his regulations and his covenant that he had made with their forefathers and his reminders that he had given to warn them, and they kept following worthless idols and became worthless themselves, imitating the nations all around them that Jehovah had commanded them not to imitate.

[[v12-17-16]]

^<<v12-17-16,16>>^ They kept leaving all the commandments of Jehovah their God, and they made metal statues^&#42;1^ of two calves and a sacred pole,^&#42;2^ and they bowed down to all the army of the heavens and served Baʹal.

[NOTE]
====
. Or “molten statues.”
. See Glossary.
====

[[v12-17-17]]

^<<v12-17-17,17>>^ They also made their sons and their daughters pass through the fire, they practiced divination and looked for omens, and they kept devoting^&#42;1^ themselves to do what was bad in the eyes of Jehovah, to offend him.

[NOTE]
====
. Lit., “selling.”
====

[[v12-17-18]]

^<<v12-17-18,18>>^ So Jehovah was very angry with Israel, so that he removed them from his sight. He did not let any remain but the tribe of Judah alone.

[[v12-17-19]]

^<<v12-17-19,19>>^ Even Judah did not keep the commandments of Jehovah their God; they also walked in the customs that Israel followed.

[[v12-17-20]]

^<<v12-17-20,20>>^ Jehovah rejected all the descendants of Israel and humiliated them and gave them into the hand of plunderers, until he had cast them away from before him.

[[v12-17-21]]

^<<v12-17-21,21>>^ He ripped Israel away from the house of David, and they made Jer·o·boʹam the son of Neʹbat king. But Jer·o·boʹam caused Israel to stray from following Jehovah, and he caused them to commit a great sin.

[[v12-17-22]]

^<<v12-17-22,22>>^ And the people of Israel kept walking in all the sins that Jer·o·boʹam had committed. They did not depart from them

[[v12-17-23]]

^<<v12-17-23,23>>^ until Jehovah removed Israel from his sight, just as he had declared through all his servants the prophets. So Israel was taken into exile from its land to As·syrʹi·a, where they remain to this day.

[[v12-17-24]]

^<<v12-17-24,24>>^ The king of As·syrʹi·a then brought people from Babylon, Cuʹthah, Avʹva, Haʹmath, and Seph·ar·vaʹim and settled them in the cities of Sa·marʹi·a in place of the Israelites; they took possession of Sa·marʹi·a and lived in its cities.

[[v12-17-25]]

^<<v12-17-25,25>>^ When they first began dwelling there, they did not fear^&#42;1^ Jehovah. So Jehovah sent lions among them, and they killed some of the people.

[NOTE]
====
. Or “worship.”
====

[[v12-17-26]]

^<<v12-17-26,26>>^ It was reported to the king of As·syrʹi·a: “The nations that you have taken into exile and resettled in the cities of Sa·marʹi·a do not know the religion^&#42;1^ of the God of the land. So he keeps sending lions among them, which are putting them to death, because none of them know the religion of the God of the land.”

[NOTE]
====
. Or “religious customs.”
====

[[v12-17-27]]

^<<v12-17-27,27>>^ At that the king of As·syrʹi·a commanded: “Have one of the priests whom you took into exile from there return to live there and to teach them the religion of the God of the land.”

[[v12-17-28]]

^<<v12-17-28,28>>^ So one of the priests whom they had taken into exile from Sa·marʹi·a came back to live in Bethʹel, and he began to teach them how they should fear^&#42;1^ Jehovah.

[NOTE]
====
. Or “worship.”
====

[[v12-17-29]]

^<<v12-17-29,29>>^ However, each different nation made their own god,^&#42;1^ which they placed in the houses of worship on the high places that the Sa·marʹi·tans had made; each different nation did so in their cities where they were living.

[NOTE]
====
. Or “gods.”
====

[[v12-17-30]]

^<<v12-17-30,30>>^ So the men of Babylon made Sucʹcoth-beʹnoth, the men of Cuth made Nerʹgal, the men of Haʹmath made A·shiʹma,

[[v12-17-31]]

^<<v12-17-31,31>>^ and the Avʹvites made Nibʹhaz and Tarʹtak. The Seʹphar·vites would burn their sons in the fire to A·dramʹme·lech and A·namʹme·lech, the gods of Seph·ar·vaʹim.

[[v12-17-32]]

^<<v12-17-32,32>>^ Although they feared Jehovah, they appointed priests for the high places from the people in general, and these officiated for them at the houses of worship on the high places.

[[v12-17-33]]

^<<v12-17-33,33>>^ Thus, they feared Jehovah, but they worshipped their own gods according to the religion^&#42;1^ of the nations from which they had been deported.

[NOTE]
====
. Or “religious customs.”
====

[[v12-17-34]]

^<<v12-17-34,34>>^ To this day they follow their former religions.^&#42;1^ None of them worship^&#42;2^ Jehovah, and none follow his statutes, his judgments, the Law, and the commandment that Jehovah gave the sons of Jacob, whose name he changed to Israel.

[NOTE]
====
. Or “religious customs.”
. Lit., “fear.”
====

[[v12-17-35]]

^<<v12-17-35,35>>^ When Jehovah made a covenant with them, he commanded them: “You must not fear other gods, and you must not bow down to them or serve them or sacrifice to them.

[[v12-17-36]]

^<<v12-17-36,36>>^ But Jehovah, who brought you up out of the land of Egypt with great power and an outstretched arm, is the One you should fear, and to him you should bow down, and to him you should sacrifice.

[[v12-17-37]]

^<<v12-17-37,37>>^ And the regulations, the judgments, the Law, and the commandment that he wrote for you, you should always follow carefully, and you must not fear other gods.

[[v12-17-38]]

^<<v12-17-38,38>>^ And you must not forget the covenant that I made with you, and you must not fear other gods.

[[v12-17-39]]

^<<v12-17-39,39>>^ But it is Jehovah your God whom you should fear, as he is the one who will rescue you out of the hand of all your enemies.”

[[v12-17-40]]

^<<v12-17-40,40>>^ But they did not obey, and they followed their former religion.^&#42;1^

[NOTE]
====
. Or “religious customs.”
====

[[v12-17-41]]

^<<v12-17-41,41>>^ So these nations came to fear Jehovah, but they were also serving their own graven images. Both their sons and their grandsons have done just as their forefathers did, down to this day.

'''

xref:012-2-kings/012-2-kings-016.adoc#v12-16-0[&#60; Capítulo Anterior] | <<v12-17-0,Topo>> | xref:012-2-kings/012-2-kings-018.adoc#v12-18-0[Próximo Capítulo &#62;]