include::./index.adoc[]

[[v12-23-0]]
=== The Second of Kings, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-23-1]]

^<<v12-23-1,1>>^ So the king sent word, and they summoned all the elders of Judah and Jerusalem.

[[v12-23-2]]

^<<v12-23-2,2>>^ After that the king went up to the house of Jehovah with all the men of Judah, all the inhabitants of Jerusalem, the priests, and the prophets—all the people, from small to great. He read in their hearing all the words of the book of the covenant that had been found in the house of Jehovah.

[[v12-23-3]]

^<<v12-23-3,3>>^ The king stood by the pillar and made a covenant^&#42;1^ before Jehovah, that he would follow Jehovah and keep his commandments, his reminders, and his statutes with all his heart and with all his soul^&#42;2^ by carrying out the words of this covenant that were written in this book. And all the people agreed to the covenant.

[NOTE]
====
. Or “renewed the covenant.”
. See Glossary.
====

[[v12-23-4]]

^<<v12-23-4,4>>^ The king then ordered Hil·kiʹah the high priest, the priests of the second rank, and the doorkeepers to bring out from the temple of Jehovah all the utensils made for Baʹal, for the sacred pole,^&#42;1^ and for all the army of the heavens. Then he burned them outside Jerusalem on the terraces of Kidʹron, and he took their ashes to Bethʹel.

[NOTE]
====
. See Glossary.
====

[[v12-23-5]]

^<<v12-23-5,5>>^ So he put out of business the foreign-god priests, whom the kings of Judah had appointed to make sacrificial smoke on the high places in the cities of Judah and the surroundings of Jerusalem, as well as those making sacrificial smoke to Baʹal, to the sun, to the moon, to the constellations of the zodiac, and to all the army of the heavens.

[[v12-23-6]]

^<<v12-23-6,6>>^ He brought the sacred pole^&#42;1^ out from the house of Jehovah to the outskirts of Jerusalem, to the Kidʹron Valley, and he burned it in the Kidʹron Valley and ground it to dust and scattered its dust on the graves of the common people.

[NOTE]
====
. See Glossary.
====

[[v12-23-7]]

^<<v12-23-7,7>>^ He also tore down the houses of the male temple prostitutes, which were in the house of Jehovah and where the women were weaving tent shrines for the sacred pole.^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v12-23-8]]

^<<v12-23-8,8>>^ Then he brought all the priests out of the cities of Judah, and he made unfit for worship the high places where the priests had been making sacrificial smoke, from Geʹba to Beʹer-sheʹba. He also tore down the high places of the gates that were at the entrance of the gate of Joshua the chief of the city, which were on the left as one entered the city gate.

[[v12-23-9]]

^<<v12-23-9,9>>^ The priests of the high places did not serve at the altar of Jehovah in Jerusalem, but they did eat unleavened bread along with their brothers.

[[v12-23-10]]

^<<v12-23-10,10>>^ He also made unfit for worship Toʹpheth, which is in the Valley of the Sons of Hinʹnom,^&#42;1^ so that no one could make his son or his daughter pass through the fire to Moʹlech.

[NOTE]
====
. See Glossary, “Gehenna.”
====

[[v12-23-11]]

^<<v12-23-11,11>>^ And he prohibited the horses that the kings of Judah had dedicated^&#42;1^ to the sun from entering the house of Jehovah by the chamber^&#42;2^ of Naʹthan-melʹech the court official, which was in the porticoes; and he burned the chariots of the sun in the fire.

[NOTE]
====
. Lit., “given.”
. Or “dining room.”
====

[[v12-23-12]]

^<<v12-23-12,12>>^ The king also tore down the altars that the kings of Judah had set up on the roof of Aʹhaz’s upper chamber, as well as the altars that Ma·nasʹseh had set up in two courtyards of the house of Jehovah. He crushed them and scattered their dust in the Kidʹron Valley.

[[v12-23-13]]

^<<v12-23-13,13>>^ And the king made unfit for worship the high places in front of Jerusalem that were to the south^&#42;1^ of the Mount of Ruination,^&#42;2^ which Solʹo·mon the king of Israel had built to Ashʹto·reth the disgusting goddess of the Si·doʹni·ans; and to Cheʹmosh the disgusting god of Moʹab; and to Milʹcom the detestable god of the Amʹmon·ites.

[NOTE]
====
. Lit., “right.” That is, south, when one faces east.
. That is, the Mount of Olives, particularly the southern extremity also known as the Mount of Offense.
====

[[v12-23-14]]

^<<v12-23-14,14>>^ He broke the sacred pillars to pieces and cut down the sacred poles^&#42;1^ and filled their places with human bones.

[NOTE]
====
. See Glossary.
====

[[v12-23-15]]

^<<v12-23-15,15>>^ He also tore down the altar in Bethʹel, the high place that Jer·o·boʹam the son of Neʹbat had made that caused Israel to sin. After tearing down that altar and the high place, he burned the high place, ground it to dust, and burned the sacred pole.^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v12-23-16]]

^<<v12-23-16,16>>^ When Jo·siʹah turned and saw the graves on the mountain, he had the bones taken from the graves and burned them on the altar, making it unfit for worship, according to Jehovah’s word that had been proclaimed by the man of the true God who foretold that these things would happen.

[[v12-23-17]]

^<<v12-23-17,17>>^ Then he said: “What is the gravestone over there that I am looking at?” At this the men of the city said to him: “It is the grave of the man of the true God from Judah who foretold these things that you have done against the altar of Bethʹel.”

[[v12-23-18]]

^<<v12-23-18,18>>^ So he said: “Let him rest. Do not let anyone disturb his bones.” So they left his bones undisturbed, as well as the bones of the prophet who had come from Sa·marʹi·a.

[[v12-23-19]]

^<<v12-23-19,19>>^ Jo·siʹah also removed all the houses of worship on the high places that were in the cities of Sa·marʹi·a, which the kings of Israel had built to offend God, and he did the same thing to them that he had done at Bethʹel.

[[v12-23-20]]

^<<v12-23-20,20>>^ So he sacrificed on the altars all the priests of the high places who were there, and he burned human bones on them. After that he returned to Jerusalem.

[[v12-23-21]]

^<<v12-23-21,21>>^ The king now commanded all the people: “Hold a Passover to Jehovah your God as is written in this book of the covenant.”

[[v12-23-22]]

^<<v12-23-22,22>>^ No Passover like this had been held since the days when the judges had judged Israel or in all the days of the kings of Israel and the kings of Judah.

[[v12-23-23]]

^<<v12-23-23,23>>^ But in the 18th year of King Jo·siʹah, this Passover to Jehovah was held in Jerusalem.

[[v12-23-24]]

^<<v12-23-24,24>>^ Jo·siʹah also cleared out the spirit mediums, the fortune-tellers, the teraphim statues,^&#42;1^ the disgusting idols,^&#42;2^ and all the disgusting things that had appeared in the land of Judah and in Jerusalem, in order to carry out the words of the Law that were written in the book that Hil·kiʹah the priest had found in the house of Jehovah.

[NOTE]
====
. Or “household gods; idols.”
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v12-23-25]]

^<<v12-23-25,25>>^ There was no king like him prior to him, who returned to Jehovah with all his heart and with all his soul^&#42;1^ and with all his strength, according to all the Law of Moses; nor did anyone like him rise up after him.

[NOTE]
====
. See Glossary.
====

[[v12-23-26]]

^<<v12-23-26,26>>^ Nevertheless, Jehovah did not turn away from his burning anger that blazed against Judah because of all the offensive things that Ma·nasʹseh had done to offend Him.

[[v12-23-27]]

^<<v12-23-27,27>>^ Jehovah said: “I will also remove Judah from my sight, just as I removed Israel; and I will reject this city that I chose, Jerusalem, and the house about which I said, ‘My name will continue there.’”

[[v12-23-28]]

^<<v12-23-28,28>>^ As for the rest of the history of Jo·siʹah, all that he did, is it not written in the book of the history of the times of the kings of Judah?

[[v12-23-29]]

^<<v12-23-29,29>>^ In his days Pharʹaoh Neʹchoh the king of Egypt came to meet the king of As·syrʹi·a by the Eu·phraʹtes River, and King Jo·siʹah went out to confront him; but when Neʹchoh saw him, he put him to death at Me·gidʹdo.

[[v12-23-30]]

^<<v12-23-30,30>>^ So his servants transported his dead body in a chariot from Me·gidʹdo and brought him to Jerusalem and buried him in his grave. Then the people of the land took Jo·siʹah’s son Je·hoʹa·haz and anointed him and made him king in place of his father.

[[v12-23-31]]

^<<v12-23-31,31>>^ Je·hoʹa·haz was 23 years old when he became king, and he reigned for three months in Jerusalem. His mother’s name was Ha·muʹtal the daughter of Jeremiah from Libʹnah.

[[v12-23-32]]

^<<v12-23-32,32>>^ He began to do what was bad in Jehovah’s eyes, according to all that his forefathers had done.

[[v12-23-33]]

^<<v12-23-33,33>>^ Pharʹaoh Neʹchoh imprisoned him at Ribʹlah in the land of Haʹmath, to keep him from reigning in Jerusalem, and then imposed on the land a fine of 100 silver talents^&#42;1^ and a gold talent.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v12-23-34]]

^<<v12-23-34,34>>^ Furthermore, Pharʹaoh Neʹchoh made Jo·siʹah’s son E·liʹa·kim king in place of his father Jo·siʹah and changed his name to Je·hoiʹa·kim; but he took Je·hoʹa·haz and brought him to Egypt, where he eventually died.

[[v12-23-35]]

^<<v12-23-35,35>>^ Je·hoiʹa·kim gave the silver and the gold to Pharʹaoh, but he had to tax the land to give the silver that Pharʹaoh demanded. He exacted an assessed amount of silver and gold from each of the people of the land to give to Pharʹaoh Neʹchoh.

[[v12-23-36]]

^<<v12-23-36,36>>^ Je·hoiʹa·kim was 25 years old when he became king, and he reigned for 11 years in Jerusalem. His mother’s name was Ze·biʹdah the daughter of Pe·daiʹah from Ruʹmah.

[[v12-23-37]]

^<<v12-23-37,37>>^ He continued to do what was bad in Jehovah’s eyes, according to all that his forefathers had done.

'''

xref:012-2-kings/012-2-kings-022.adoc#v12-22-0[&#60; Capítulo Anterior] | <<v12-23-0,Topo>> | xref:012-2-kings/012-2-kings-024.adoc#v12-24-0[Próximo Capítulo &#62;]