include::./index.adoc[]

[[v12-18-0]]
=== The Second of Kings, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-18-1]]

^<<v12-18-1,1>>^ In the third year of Ho·sheʹa the son of Eʹlah the king of Israel, Hez·e·kiʹah the son of King Aʹhaz of Judah became king.

[[v12-18-2]]

^<<v12-18-2,2>>^ He was 25 years old when he became king, and he reigned for 29 years in Jerusalem. His mother’s name was Aʹbi^&#42;1^ the daughter of Zech·a·riʹah.

[NOTE]
====
. An abbreviated form of Abijah.
====

[[v12-18-3]]

^<<v12-18-3,3>>^ He kept doing what was right in Jehovah’s eyes, just as David his forefather had done.

[[v12-18-4]]

^<<v12-18-4,4>>^ He was the one who removed the high places, smashed the sacred pillars, and cut down the sacred pole.^&#42;1^ He also crushed the copper serpent that Moses had made; for down to that time the people of Israel had been making sacrificial smoke to it and it used to be called the copper serpent-idol.^&#42;2^

[NOTE]
====
. See Glossary.
. Or “called Nehushtan.”
====

[[v12-18-5]]

^<<v12-18-5,5>>^ He trusted in Jehovah the God of Israel; there was no one like him among all the kings of Judah after him nor among those prior to him.

[[v12-18-6]]

^<<v12-18-6,6>>^ He held fast to Jehovah. He did not turn away from following him; he continued to keep the commandments that Jehovah had given to Moses.

[[v12-18-7]]

^<<v12-18-7,7>>^ And Jehovah was with him. Wherever he went, he acted wisely. He rebelled against the king of As·syrʹi·a and refused to serve him.

[[v12-18-8]]

^<<v12-18-8,8>>^ He also defeated the Phi·lisʹtines clear to Gazʹa and its territories, from watchtower to fortified city.^&#42;1^

[NOTE]
====
. That is, in every place, whether sparsely inhabited or populous.
====

[[v12-18-9]]

^<<v12-18-9,9>>^ In the fourth year of King Hez·e·kiʹah, that is, the seventh year of Ho·sheʹa the son of Eʹlah the king of Israel, King Shal·man·eʹser of As·syrʹi·a came up against Sa·marʹi·a and began to lay siege to it.

[[v12-18-10]]

^<<v12-18-10,10>>^ They captured it at the end of three years; in the sixth year of Hez·e·kiʹah, which was the ninth year of King Ho·sheʹa of Israel, Sa·marʹi·a was captured.

[[v12-18-11]]

^<<v12-18-11,11>>^ Then the king of As·syrʹi·a took Israel into exile in As·syrʹi·a and settled them in Haʹlah and in Haʹbor at the river Goʹzan and in the cities of the Medes.

[[v12-18-12]]

^<<v12-18-12,12>>^ This was because they had not listened to the voice of Jehovah their God but kept violating his covenant, all that Moses the servant of Jehovah had commanded. They neither listened nor obeyed.

[[v12-18-13]]

^<<v12-18-13,13>>^ In the 14th year of King Hez·e·kiʹah, Sen·nachʹer·ib the king of As·syrʹi·a came up against all the fortified cities of Judah and captured them.

[[v12-18-14]]

^<<v12-18-14,14>>^ So King Hez·e·kiʹah of Judah sent word to the king of As·syrʹi·a at Laʹchish: “I am at fault. Withdraw from against me, and I will give whatever you may impose on me.” The king of As·syrʹi·a imposed on King Hez·e·kiʹah of Judah a fine of 300 silver talents^&#42;1^ and 30 gold talents.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v12-18-15]]

^<<v12-18-15,15>>^ So Hez·e·kiʹah gave all the silver that could be found at the house of Jehovah and in the treasuries of the king’s house.^&#42;1^

[NOTE]
====
. Or “palace.”
====

[[v12-18-16]]

^<<v12-18-16,16>>^ At that time Hez·e·kiʹah removed^&#42;1^ the doors of the temple of Jehovah and the doorposts that King Hez·e·kiʹah of Judah himself had overlaid,^&#42;2^ and he gave them to the king of As·syrʹi·a.

[NOTE]
====
. Lit., “cut off.”
. That is, overlaid with gold.
====

[[v12-18-17]]

^<<v12-18-17,17>>^ The king of As·syrʹi·a then sent the Tarʹtan,^&#42;1^ the Rabʹsa·ris,^&#42;2^ and the Rabʹsha·keh^&#42;3^ with a vast army from Laʹchish to King Hez·e·kiʹah in Jerusalem. They went up to Jerusalem and took up a position by the conduit of the upper pool, which is at the highway of the laundryman’s field.

[NOTE]
====
. Or “the commander.”
. Or “the chief court official.”
. Or “the chief cupbearer.”
====

[[v12-18-18]]

^<<v12-18-18,18>>^ When they called for the king to come out, E·liʹa·kim son of Hil·kiʹah, who was in charge of the household,^&#42;1^ Shebʹnah the secretary, and Joʹah son of Aʹsaph the recorder came out to them.

[NOTE]
====
. Or “palace.”
====

[[v12-18-19]]

^<<v12-18-19,19>>^ So the Rabʹsha·keh said to them: “Please, say to Hez·e·kiʹah, ‘This is what the great king, the king of As·syrʹi·a, says: “What is the basis for your confidence?

[[v12-18-20]]

^<<v12-18-20,20>>^ You are saying, ‘I have a strategy and the power to wage war,’ but these are empty words. In whom have you put your trust, so that you dare to rebel against me?

[[v12-18-21]]

^<<v12-18-21,21>>^ Look! You trust in the support of this crushed reed, Egypt, which if a man should lean on it would enter into his palm and pierce it. That is the way Pharʹaoh king of Egypt is to all those who trust in him.

[[v12-18-22]]

^<<v12-18-22,22>>^ And if you should say to me, ‘We trust in Jehovah our God,’ is he not the one whose high places and altars Hez·e·kiʹah has removed, while he says to Judah and Jerusalem, ‘You should bow down before this altar in Jerusalem’?”’

[[v12-18-23]]

^<<v12-18-23,23>>^ So now make this wager, please, with my lord the king of As·syrʹi·a: I will give you 2,000 horses if you are able to find enough riders for them.

[[v12-18-24]]

^<<v12-18-24,24>>^ How, then, could you drive back even one governor who is the least of my lord’s servants, while you put your trust in Egypt for chariots and for horsemen?

[[v12-18-25]]

^<<v12-18-25,25>>^ Now is it without authorization from Jehovah that I have come up against this place to destroy it? Jehovah himself said to me, ‘Go up against this land and destroy it.’”

[[v12-18-26]]

^<<v12-18-26,26>>^ At this E·liʹa·kim son of Hil·kiʹah, and Shebʹnah and Joʹah said to the Rabʹsha·keh: “Speak to your servants, please, in the Ar·a·maʹic^&#42;1^ language, for we can understand it; do not speak to us in the language of the Jews in the hearing of the people on the wall.”

[NOTE]
====
. Or “Syrian.”
====

[[v12-18-27]]

^<<v12-18-27,27>>^ But the Rabʹsha·keh said to them: “Is it just to your lord and to you that my lord sent me to speak these words? Is it not also to the men who sit on the wall, those who will eat their own excrement and drink their own urine along with you?”

[[v12-18-28]]

^<<v12-18-28,28>>^ Then the Rabʹsha·keh stood and called out loudly in the language of the Jews, saying: “Hear the word of the great king, the king of As·syrʹi·a.

[[v12-18-29]]

^<<v12-18-29,29>>^ This is what the king says, ‘Do not let Hez·e·kiʹah deceive you, for he is not able to rescue you out of my hand.

[[v12-18-30]]

^<<v12-18-30,30>>^ And do not let Hez·e·kiʹah cause you to trust in Jehovah by saying: “Jehovah will surely rescue us, and this city will not be given into the hand of the king of As·syrʹi·a.”

[[v12-18-31]]

^<<v12-18-31,31>>^ Do not listen to Hez·e·kiʹah, for this is what the king of As·syrʹi·a says: “Make peace with me and surrender,^&#42;1^ and each of you will eat from his own vine and from his own fig tree and will drink the water of his own cistern,

[NOTE]
====
. Lit., “Make a blessing with me and come out to me.”
====

[[v12-18-32]]

^<<v12-18-32,32>>^ until I come and take you to a land like your own land, a land of grain and new wine, a land of bread and vineyards, a land of olive trees and honey. Then you will live and not die. Do not listen to Hez·e·kiʹah, for he misleads you by saying, ‘Jehovah will rescue us.’

[[v12-18-33]]

^<<v12-18-33,33>>^ Have any of the gods of the nations rescued their land out of the hand of the king of As·syrʹi·a?

[[v12-18-34]]

^<<v12-18-34,34>>^ Where are the gods of Haʹmath and Arʹpad? Where are the gods of Seph·ar·vaʹim, Heʹna, and Ivʹvah? Have they rescued Sa·marʹi·a out of my hand?

[[v12-18-35]]

^<<v12-18-35,35>>^ Who among all the gods of the lands have rescued their land out of my hand, so that Jehovah should rescue Jerusalem out of my hand?”’”

[[v12-18-36]]

^<<v12-18-36,36>>^ But the people kept silent and did not say a word to him in reply, for the order of the king was, “You must not answer him.”

[[v12-18-37]]

^<<v12-18-37,37>>^ But E·liʹa·kim son of Hil·kiʹah, who was in charge of the household,^&#42;1^ Shebʹnah the secretary, and Joʹah son of Aʹsaph the recorder came to Hez·e·kiʹah with their garments ripped apart and told him the words of the Rabʹsha·keh.

[NOTE]
====
. Or “palace.”
====

'''

xref:012-2-kings/012-2-kings-017.adoc#v12-17-0[&#60; Capítulo Anterior] | <<v12-18-0,Topo>> | xref:012-2-kings/012-2-kings-019.adoc#v12-19-0[Próximo Capítulo &#62;]