include::./index.adoc[]

[[v12-15-0]]
=== The Second of Kings, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-15-1]]

^<<v12-15-1,1>>^ In the 27th year of King Jer·o·boʹam^&#42;1^ of Israel, Az·a·riʹah^&#42;2^ the son of King Am·a·ziʹah of Judah became king.

[NOTE]
====
. That is, Jeroboam II.
. Meaning “Jehovah Has Helped.” He is called Uzziah at 2Ki 15:13; 2Ch 26:1-23; Isa 6:1; and Zec 14:5.
====

[[v12-15-2]]

^<<v12-15-2,2>>^ He was 16 years old when he became king, and he reigned for 52 years in Jerusalem. His mother’s name was Je·co·liʹah of Jerusalem.

[[v12-15-3]]

^<<v12-15-3,3>>^ He continued to do what was right in Jehovah’s eyes, just as his father Am·a·ziʹah had done.

[[v12-15-4]]

^<<v12-15-4,4>>^ However, the high places were not removed, and the people were still sacrificing and making sacrificial smoke on the high places.

[[v12-15-5]]

^<<v12-15-5,5>>^ Jehovah afflicted the king, and he remained a leper until the day of his death; and he stayed in a separate house, while the king’s son Joʹtham was in charge of the house,^&#42;1^ judging the people of the land.

[NOTE]
====
. Or “palace.”
====

[[v12-15-6]]

^<<v12-15-6,6>>^ As for the rest of the history of Az·a·riʹah, all that he did, is it not written in the book of the history of the times of the kings of Judah?

[[v12-15-7]]

^<<v12-15-7,7>>^ Then Az·a·riʹah was laid to rest with his forefathers, and they buried him with his forefathers in the City of David; and his son Joʹtham became king in his place.

[[v12-15-8]]

^<<v12-15-8,8>>^ In the 38th year of King Az·a·riʹah of Judah, Zech·a·riʹah the son of Jer·o·boʹam became king over Israel in Sa·marʹi·a, and he reigned for six months.

[[v12-15-9]]

^<<v12-15-9,9>>^ He did what was bad in Jehovah’s eyes, just as his forefathers had done. He did not depart from the sins that Jer·o·boʹam the son of Neʹbat had caused Israel to commit.

[[v12-15-10]]

^<<v12-15-10,10>>^ Then Shalʹlum the son of Jaʹbesh conspired against him and struck him down at Ibʹle·am. After putting him to death, he became king in his place.

[[v12-15-11]]

^<<v12-15-11,11>>^ As for the rest of the history of Zech·a·riʹah, it is written in the book of the history of the times of the kings of Israel.

[[v12-15-12]]

^<<v12-15-12,12>>^ That fulfilled Jehovah’s word spoken to Jeʹhu: “Four generations of your sons will sit on the throne of Israel.” And that is how it happened.

[[v12-15-13]]

^<<v12-15-13,13>>^ Shalʹlum the son of Jaʹbesh became king in the 39th year of King Uz·ziʹah of Judah, and he reigned for a full month in Sa·marʹi·a.

[[v12-15-14]]

^<<v12-15-14,14>>^ Then Menʹa·hem the son of Gaʹdi came up from Tirʹzah to Sa·marʹi·a and struck down Shalʹlum the son of Jaʹbesh in Sa·marʹi·a. After putting him to death, he became king in his place.

[[v12-15-15]]

^<<v12-15-15,15>>^ As for the rest of the history of Shalʹlum and the conspiracy that he formed, it is written in the book of the history of the times of the kings of Israel.

[[v12-15-16]]

^<<v12-15-16,16>>^ It was then that Menʹa·hem came from Tirʹzah and struck down Tiphʹsah and all who were in it and its territory, because it did not open its gates to him. He struck it down and ripped open its pregnant women.

[[v12-15-17]]

^<<v12-15-17,17>>^ In the 39th year of King Az·a·riʹah of Judah, Menʹa·hem the son of Gaʹdi became king over Israel, and he reigned for ten years in Sa·marʹi·a.

[[v12-15-18]]

^<<v12-15-18,18>>^ He continued to do what was bad in Jehovah’s eyes. He did not depart from all the sins that Jer·o·boʹam the son of Neʹbat had caused Israel to commit, all his days.

[[v12-15-19]]

^<<v12-15-19,19>>^ King Pul of As·syrʹi·a came into the land, and Menʹa·hem gave Pul 1,000 talents^&#42;1^ of silver in return for his support in strengthening his hold on the kingdom.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v12-15-20]]

^<<v12-15-20,20>>^ So Menʹa·hem raised the silver from Israel by exacting it from the prominent, wealthy men. He gave the king of As·syrʹi·a 50 silver shekels^&#42;1^ for each man. Then the king of As·syrʹi·a turned back and did not stay in the land.

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v12-15-21]]

^<<v12-15-21,21>>^ As for the rest of the history of Menʹa·hem, all that he did, is it not written in the book of the history of the times of the kings of Israel?

[[v12-15-22]]

^<<v12-15-22,22>>^ Then Menʹa·hem was laid to rest with his forefathers; and his son Pek·a·hiʹah became king in his place.

[[v12-15-23]]

^<<v12-15-23,23>>^ In the 50th year of King Az·a·riʹah of Judah, Pek·a·hiʹah the son of Menʹa·hem became king over Israel in Sa·marʹi·a, and he reigned for two years.

[[v12-15-24]]

^<<v12-15-24,24>>^ He continued to do what was bad in Jehovah’s eyes. He did not depart from the sins that Jer·o·boʹam the son of Neʹbat had caused Israel to commit.

[[v12-15-25]]

^<<v12-15-25,25>>^ Then his adjutant Peʹkah the son of Rem·a·liʹah conspired against him and struck him down in Sa·marʹi·a in the fortified tower of the king’s house^&#42;1^ with Arʹgob and A·riʹeh. He had 50 men of Gilʹe·ad with him; and after he put him to death, he became king in his place.

[NOTE]
====
. Or “palace.”
====

[[v12-15-26]]

^<<v12-15-26,26>>^ As for the rest of the history of Pek·a·hiʹah, all that he did, it is written in the book of the history of the times of the kings of Israel.

[[v12-15-27]]

^<<v12-15-27,27>>^ In the 52nd year of King Az·a·riʹah of Judah, Peʹkah the son of Rem·a·liʹah became king over Israel in Sa·marʹi·a, and he reigned for 20 years.

[[v12-15-28]]

^<<v12-15-28,28>>^ He continued to do what was bad in Jehovah’s eyes, and he did not depart from the sins that Jer·o·boʹam the son of Neʹbat had caused Israel to commit.

[[v12-15-29]]

^<<v12-15-29,29>>^ In the days of King Peʹkah of Israel, King Tigʹlath-pil·eʹser of As·syrʹi·a invaded and captured Iʹjon, Aʹbel-beth-maʹa·cah, Ja·noʹah, Keʹdesh, Haʹzor, Gilʹe·ad, and Galʹi·lee, all the land of Naphʹta·li, and he took the inhabitants into exile in As·syrʹi·a.

[[v12-15-30]]

^<<v12-15-30,30>>^ Then Ho·sheʹa the son of Eʹlah formed a conspiracy against Peʹkah the son of Rem·a·liʹah, and he struck him and put him to death; and he became king in his place in the 20th year of Joʹtham the son of Uz·ziʹah.

[[v12-15-31]]

^<<v12-15-31,31>>^ As for the rest of the history of Peʹkah, all that he did, it is written in the book of the history of the times of the kings of Israel.

[[v12-15-32]]

^<<v12-15-32,32>>^ In the second year of Peʹkah the son of Rem·a·liʹah the king of Israel, Joʹtham the son of King Uz·ziʹah of Judah became king.

[[v12-15-33]]

^<<v12-15-33,33>>^ He was 25 years old when he became king, and he reigned for 16 years in Jerusalem. His mother’s name was Je·ruʹsha the daughter of Zaʹdok.

[[v12-15-34]]

^<<v12-15-34,34>>^ He kept doing what was right in Jehovah’s eyes, just as his father Uz·ziʹah had done.

[[v12-15-35]]

^<<v12-15-35,35>>^ However, the high places were not removed, and the people were still sacrificing and making sacrificial smoke on the high places. He was the one who built the upper gate of the house of Jehovah.

[[v12-15-36]]

^<<v12-15-36,36>>^ As for the rest of the history of Joʹtham, what he did, is it not written in the book of the history of the times of the kings of Judah?

[[v12-15-37]]

^<<v12-15-37,37>>^ In those days Jehovah began sending Reʹzin the king of Syria and Peʹkah the son of Rem·a·liʹah against Judah.

[[v12-15-38]]

^<<v12-15-38,38>>^ Then Joʹtham was laid to rest with his forefathers and was buried with his forefathers in the City of David his forefather. And his son Aʹhaz became king in his place.

'''

xref:012-2-kings/012-2-kings-014.adoc#v12-14-0[&#60; Capítulo Anterior] | <<v12-15-0,Topo>> | xref:012-2-kings/012-2-kings-016.adoc#v12-16-0[Próximo Capítulo &#62;]