include::./index.adoc[]

[[v12-10-0]]
=== The Second of Kings, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-10-1]]

^<<v12-10-1,1>>^ Now Aʹhab had 70 sons in Sa·marʹi·a. So Jeʹhu wrote letters and sent them to Sa·marʹi·a, to the princes of Jezʹre·el, the elders, and the guardians of Aʹhab’s children,^&#42;1^ saying:

[NOTE]
====
. Lit., “the guardians of Ahab.”
====

[[v12-10-2]]

^<<v12-10-2,2>>^ “Now when this letter comes to you, the sons of your lord will be with you, as well as the war chariots, the horses, a fortified city, and weapons.

[[v12-10-3]]

^<<v12-10-3,3>>^ Select the best and most suitable^&#42;1^ of the sons of your lord and put him on the throne of his father. Then fight for the house of your lord.”

[NOTE]
====
. Or “upright.”
====

[[v12-10-4]]

^<<v12-10-4,4>>^ But they were overcome with fear and said: “Look! If two kings could not stand before him, how can we stand?”

[[v12-10-5]]

^<<v12-10-5,5>>^ So the overseer of the palace,^&#42;1^ the governor of the city, the elders, and the guardians sent this message to Jeʹhu: “We are your servants, and we will do everything that you tell us. We will not make anyone king. Do whatever seems good in your eyes.”

[NOTE]
====
. Lit., “house.”
====

[[v12-10-6]]

^<<v12-10-6,6>>^ Then he wrote them a second letter, saying: “If you belong to me and are willing to obey me, bring the heads of the sons of your lord and come to me tomorrow at this time at Jezʹre·el.”
Now the 70 sons of the king were with the distinguished men of the city who were raising them.

[[v12-10-7]]

^<<v12-10-7,7>>^ As soon as the letter came to them, they took the sons of the king and slaughtered them, 70 men, and they put their heads in baskets and sent them to him at Jezʹre·el.

[[v12-10-8]]

^<<v12-10-8,8>>^ The messenger came in and told him: “They have brought the heads of the sons of the king.” So he said: “Put them in two heaps at the entrance of the city gate until morning.”

[[v12-10-9]]

^<<v12-10-9,9>>^ When he went out in the morning, he stood before all the people and said: “You are innocent.^&#42;1^ Yes, I conspired against my lord, and I killed him, but who struck down all of these?

[NOTE]
====
. Or “righteous.”
====

[[v12-10-10]]

^<<v12-10-10,10>>^ Know, then, that not a single word of Jehovah’s that Jehovah has spoken against the house of Aʹhab will go unfulfilled,^&#42;1^ and Jehovah has done what he spoke through his servant E·liʹjah.”

[NOTE]
====
. Lit., “will fall to the earth.”
====

[[v12-10-11]]

^<<v12-10-11,11>>^ Moreover, Jeʹhu struck down all who were left of the house of Aʹhab in Jezʹre·el, as well as all his distinguished men, his acquaintances, and his priests, until he had left him no survivor.

[[v12-10-12]]

^<<v12-10-12,12>>^ Then he got up and went on his way to Sa·marʹi·a. The binding house^&#42;1^ of the shepherds was on the way.

[NOTE]
====
. Apparently a place where sheep were bound in order to be sheared.
====

[[v12-10-13]]

^<<v12-10-13,13>>^ There Jeʹhu encountered the brothers of King A·ha·ziʹah of Judah, and he said to them, “Who are you?” They said: “We are the brothers of A·ha·ziʹah, and we are on our way down to ask if all is well with the sons of the king and the sons of the queen mother.”^&#42;1^

[NOTE]
====
. Or “the lady.”
====

[[v12-10-14]]

^<<v12-10-14,14>>^ Immediately he said: “Capture them alive!” So they captured them alive and slaughtered them at the cistern of the binding house, 42 men. He did not let a single one of them survive.

[[v12-10-15]]

^<<v12-10-15,15>>^ As he went from there, he encountered Je·honʹa·dab the son of Reʹchab, who was coming to meet him. When he greeted^&#42;1^ him, he said to him: “Is your heart fully^&#42;2^ with me, just as my heart is with your heart?”
Je·honʹa·dab replied: “It is.”
“If so, give me your hand.”
So he gave him his hand, and Jeʹhu pulled him up into the chariot with him.

[NOTE]
====
. Or “blessed.”
. Lit., “upright.”
====

[[v12-10-16]]

^<<v12-10-16,16>>^ Then he said: “Come along with me, and see my toleration of no rivalry toward^&#42;1^ Jehovah.” So they had him ride with him in his war chariot.

[NOTE]
====
. Or “my zeal for.”
====

[[v12-10-17]]

^<<v12-10-17,17>>^ Then he came to Sa·marʹi·a, and he struck down all who were left over of Aʹhab’s house in Sa·marʹi·a until he had annihilated them, according to Jehovah’s word that he had spoken to E·liʹjah.

[[v12-10-18]]

^<<v12-10-18,18>>^ Further, Jeʹhu collected all the people together and said to them: “Aʹhab worshipped Baʹal a little, but Jeʹhu will worship him much more.

[[v12-10-19]]

^<<v12-10-19,19>>^ So summon all the prophets of Baʹal, all his worshippers, and all his priests to me. Do not let a single one be absent, because I have a great sacrifice for Baʹal. Anyone who is absent will not live.” But Jeʹhu was acting with cunning to destroy the worshippers of Baʹal.

[[v12-10-20]]

^<<v12-10-20,20>>^ Jeʹhu continued: “Declare^&#42;1^ a solemn assembly for Baʹal.” So they proclaimed it.

[NOTE]
====
. Lit., “Sanctify.”
====

[[v12-10-21]]

^<<v12-10-21,21>>^ After that Jeʹhu sent word throughout Israel, and all the worshippers of Baʹal came. Not a single one was left out who did not come. They entered the house^&#42;1^ of Baʹal, and the house of Baʹal was filled from end to end.

[NOTE]
====
. Or “temple.”
====

[[v12-10-22]]

^<<v12-10-22,22>>^ He said to the one who was in charge of the wardrobe: “Bring out garments for all the worshippers of Baʹal.” So he brought out the clothing for them.

[[v12-10-23]]

^<<v12-10-23,23>>^ Then Jeʹhu and Je·honʹa·dab the son of Reʹchab went into the house of Baʹal. He now said to the worshippers of Baʹal: “Search carefully and see that there are no worshippers of Jehovah here, only worshippers of Baʹal.”

[[v12-10-24]]

^<<v12-10-24,24>>^ Finally they came in to offer up sacrifices and burnt offerings. Jeʹhu had stationed 80 of his men outside and said: “If any one of the men I am putting into your hands escapes, it will be your life for his.”^&#42;1^

[NOTE]
====
. Or “it will be your soul for his soul.”
====

[[v12-10-25]]

^<<v12-10-25,25>>^ As soon as he finished offering up the burnt offering, Jeʹhu said to the guards^&#42;1^ and the adjutants: “Come in and strike them down! Do not let a single one escape!” So the guards and the adjutants struck them down with the sword and threw them out, and they kept going as far as the inner sanctuary^&#42;2^ of the house of Baʹal.

[NOTE]
====
. Lit., “runners.”
. Lit., “the city,” perhaps a fortresslike structure.
====

[[v12-10-26]]

^<<v12-10-26,26>>^ Then they brought out the sacred pillars of the house of Baʹal and burned each one.

[[v12-10-27]]

^<<v12-10-27,27>>^ They tore down the sacred pillar of Baʹal, and they tore down the house of Baʹal and turned it into latrines, as it remains to this day.

[[v12-10-28]]

^<<v12-10-28,28>>^ Thus Jeʹhu annihilated Baʹal out of Israel.

[[v12-10-29]]

^<<v12-10-29,29>>^ However, Jeʹhu did not turn away from the sins that Jer·o·boʹam the son of Neʹbat had caused Israel to commit as regards the golden calves that were in Bethʹel and in Dan.

[[v12-10-30]]

^<<v12-10-30,30>>^ So Jehovah said to Jeʹhu: “Because you have acted well and have done what is right in my eyes by carrying out all that was in my heart to do to the house of Aʹhab, four generations of your sons will sit on the throne of Israel.”

[[v12-10-31]]

^<<v12-10-31,31>>^ But Jeʹhu did not take care to walk in the Law of Jehovah the God of Israel with all his heart. He did not turn away from the sins that Jer·o·boʹam had caused Israel to commit.

[[v12-10-32]]

^<<v12-10-32,32>>^ In those days Jehovah started to cut off^&#42;1^ Israel piece by piece. Hazʹa·el kept attacking them throughout the territory of Israel,

[NOTE]
====
. Or “reduce.”
====

[[v12-10-33]]

^<<v12-10-33,33>>^ from the Jordan eastward, all the land of Gilʹe·ad—of the Gadʹites, the Reuʹben·ites, and the Ma·nasʹsites—from A·roʹer, which is by the Arʹnon Valley,^&#42;1^ to Gilʹe·ad and Baʹshan.

[NOTE]
====
. Or “Wadi Arnon.”
====

[[v12-10-34]]

^<<v12-10-34,34>>^ And the rest of the history of Jeʹhu, all that he did and all his mightiness, is it not written in the book of the history of the times of the kings of Israel?

[[v12-10-35]]

^<<v12-10-35,35>>^ Then Jeʹhu was laid to rest with his forefathers, and they buried him in Sa·marʹi·a; and his son Je·hoʹa·haz became king in his place.

[[v12-10-36]]

^<<v12-10-36,36>>^ The length^&#42;1^ of Jeʹhu’s reign over Israel was 28 years in Sa·marʹi·a.

[NOTE]
====
. Lit., “The days.”
====

'''

xref:012-2-kings/012-2-kings-009.adoc#v12-9-0[&#60; Capítulo Anterior] | <<v12-10-0,Topo>> | xref:012-2-kings/012-2-kings-011.adoc#v12-11-0[Próximo Capítulo &#62;]