include::./index.adoc[]

[[v12-11-0]]
=== The Second of Kings, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-11-1]]

^<<v12-11-1,1>>^ Now when Ath·a·liʹah, A·ha·ziʹah’s mother, saw that her son had died, she rose up and destroyed the entire royal line.^&#42;1^

[NOTE]
====
. Lit., “all seed of the kingdom.”
====

[[v12-11-2]]

^<<v12-11-2,2>>^ However, Je·hoshʹe·ba the daughter of King Je·hoʹram, A·ha·ziʹah’s sister, took Je·hoʹash the son of A·ha·ziʹah and stole him away from among the sons of the king who were to be put to death, keeping him and his nurse in an inner bedroom. They managed to keep him concealed from Ath·a·liʹah, so he was not put to death.

[[v12-11-3]]

^<<v12-11-3,3>>^ He remained with her for six years, hidden at the house of Jehovah, while Ath·a·liʹah was ruling over the land.

[[v12-11-4]]

^<<v12-11-4,4>>^ In the seventh year, Je·hoiʹa·da sent for the chiefs of hundreds of the Caʹri·an bodyguard and of the palace guards^&#42;1^ and had them come to him at the house of Jehovah. He made a pact^&#42;2^ with them and had them swear to it at the house of Jehovah, and then he showed them the son of the king.

[NOTE]
====
. Lit., “the runners.”
. Or “covenant.”
====

[[v12-11-5]]

^<<v12-11-5,5>>^ He ordered them: “This is what you are to do: One third of you will be on duty on the Sabbath and will keep strict watch over the king’s house,^&#42;1^

[NOTE]
====
. Or “palace.”
====

[[v12-11-6]]

^<<v12-11-6,6>>^ another third will be at the Gate of the Foundation, and another third will be at the gate behind the palace guards. You will take turns watching over the house.

[[v12-11-7]]

^<<v12-11-7,7>>^ Your two divisions that are supposed to be off duty on the Sabbath must keep strict watch over the house of Jehovah to protect the king.

[[v12-11-8]]

^<<v12-11-8,8>>^ You must surround the king on every side, each with his weapons in hand. Anyone entering within the ranks will be put to death. Stay with the king wherever he goes.”^&#42;1^

[NOTE]
====
. Lit., “when he goes out and when he comes in.”
====

[[v12-11-9]]

^<<v12-11-9,9>>^ The chiefs of hundreds did exactly what Je·hoiʹa·da the priest had commanded. So each one took his men who were on duty on the Sabbath, together with those who were off duty on the Sabbath, and they came in to Je·hoiʹa·da the priest.

[[v12-11-10]]

^<<v12-11-10,10>>^ The priest then gave the chiefs of hundreds the spears and the circular shields that had belonged to King David, which were in the house of Jehovah.

[[v12-11-11]]

^<<v12-11-11,11>>^ And the palace guards took their positions, each with his weapons in hand, from the right side of the house to the left side of the house, by the altar and by the house, all around the king.

[[v12-11-12]]

^<<v12-11-12,12>>^ Then Je·hoiʹa·da brought the king’s son out and put on him the crown^&#42;1^ and the Testimony,^&#42;2^ and they made him king and anointed him. They began to clap their hands and say: “Long live the king!”

[NOTE]
====
. Or “diadem.”
. Possibly a scroll containing the Law of God.
====

[[v12-11-13]]

^<<v12-11-13,13>>^ When Ath·a·liʹah heard the sound of the people running, she immediately came to the people at the house of Jehovah.

[[v12-11-14]]

^<<v12-11-14,14>>^ Then she saw the king standing there by the pillar according to the custom. The chiefs and the trumpeters were with the king, and all the people of the land were rejoicing and blowing the trumpets. At this Ath·a·liʹah ripped her garments apart and cried out: “Conspiracy! Conspiracy!”

[[v12-11-15]]

^<<v12-11-15,15>>^ But Je·hoiʹa·da the priest commanded the chiefs of hundreds, those appointed over the army, and said to them: “Take her out from among the ranks, and if anyone follows her, put him to death with the sword!” For the priest had said: “Do not put her to death in the house of Jehovah.”

[[v12-11-16]]

^<<v12-11-16,16>>^ So they seized her, and when she reached the place where the horses enter the king’s house,^&#42;1^ she was put to death there.

[NOTE]
====
. Or “palace.”
====

[[v12-11-17]]

^<<v12-11-17,17>>^ Then Je·hoiʹa·da made a covenant between Jehovah and the king and the people, that they would continue as the people of Jehovah, and he also made a covenant between the king and the people.

[[v12-11-18]]

^<<v12-11-18,18>>^ After that all the people of the land came to the house^&#42;1^ of Baʹal and tore down his altars, completely smashed his images, and killed Matʹtan the priest of Baʹal in front of the altars.
Then the priest appointed overseers over the house of Jehovah.

[NOTE]
====
. Or “temple.”
====

[[v12-11-19]]

^<<v12-11-19,19>>^ Further, he took the chiefs of hundreds, the Caʹri·an bodyguard, the palace guards, and all the people of the land to escort the king down from the house of Jehovah, and they came to the king’s house^&#42;1^ by the way of the gate of the palace guard. He then sat on the throne of the kings.

[NOTE]
====
. Or “palace.”
====

[[v12-11-20]]

^<<v12-11-20,20>>^ So all the people of the land rejoiced and the city was quiet, for they had put Ath·a·liʹah to death with the sword at the king’s house.

[[v12-11-21]]

^<<v12-11-21,21>>^ Je·hoʹash was seven years old when he became king.

'''

xref:012-2-kings/012-2-kings-010.adoc#v12-10-0[&#60; Capítulo Anterior] | <<v12-11-0,Topo>> | xref:012-2-kings/012-2-kings-012.adoc#v12-12-0[Próximo Capítulo &#62;]