include::./index.adoc[]

[[v12-13-0]]
=== The Second of Kings, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-13-1]]

^<<v12-13-1,1>>^ In the 23rd year of Je·hoʹash the son of A·ha·ziʹah the king of Judah, Je·hoʹa·haz the son of Jeʹhu became king over Israel in Sa·marʹi·a, and he reigned for 17 years.

[[v12-13-2]]

^<<v12-13-2,2>>^ He continued to do what was bad in Jehovah’s eyes, and he persisted in the sin that Jer·o·boʹam the son of Neʹbat had caused Israel to commit. He did not turn away from it.

[[v12-13-3]]

^<<v12-13-3,3>>^ So Jehovah’s anger grew hot against Israel, and he gave them into the hand of King Hazʹa·el of Syria and into the hand of Ben-haʹdad the son of Hazʹa·el all their days.

[[v12-13-4]]

^<<v12-13-4,4>>^ In time Je·hoʹa·haz begged for the favor^&#42;1^ of Jehovah, and Jehovah listened to him, for he had seen the oppression the king of Syria had inflicted on Israel.

[NOTE]
====
. Or “softened the face.”
====

[[v12-13-5]]

^<<v12-13-5,5>>^ So Jehovah provided Israel with a savior to free them from Syria’s grip, and the Israelites were able to dwell in their homes as before.^&#42;1^

[NOTE]
====
. That is, in peace and security.
====

[[v12-13-6]]

^<<v12-13-6,6>>^ (However, they did not depart from the sin of the house of Jer·o·boʹam that he had caused Israel to commit. They continued in this sin,^&#42;1^ and the sacred pole^&#42;2^ continued to stand in Sa·marʹi·a.)

[NOTE]
====
. Lit., “In it he walked.”
. See Glossary.
====

[[v12-13-7]]

^<<v12-13-7,7>>^ Je·hoʹa·haz was left with an army of only 50 horsemen, 10 chariots, and 10,000 foot soldiers, because the king of Syria had destroyed them, trampling them like the dust at threshing time.

[[v12-13-8]]

^<<v12-13-8,8>>^ As for the rest of the history of Je·hoʹa·haz, all that he did and his mightiness, is it not written in the book of the history of the times of the kings of Israel?

[[v12-13-9]]

^<<v12-13-9,9>>^ Then Je·hoʹa·haz was laid to rest with his forefathers, and they buried him in Sa·marʹi·a; and his son Je·hoʹash became king in his place.

[[v12-13-10]]

^<<v12-13-10,10>>^ In the 37th year of King Je·hoʹash of Judah, Je·hoʹash the son of Je·hoʹa·haz became king over Israel in Sa·marʹi·a, and he reigned for 16 years.

[[v12-13-11]]

^<<v12-13-11,11>>^ He continued to do what was bad in Jehovah’s eyes, not departing from all the sins that Jer·o·boʹam the son of Neʹbat had made Israel commit. He continued^&#42;1^ in these sins.

[NOTE]
====
. Lit., “walked.”
====

[[v12-13-12]]

^<<v12-13-12,12>>^ As for the rest of the history of Je·hoʹash, all that he did and his mightiness and how he fought against King Am·a·ziʹah of Judah, is it not written in the book of the history of the times of the kings of Israel?

[[v12-13-13]]

^<<v12-13-13,13>>^ Then Je·hoʹash was laid to rest with his forefathers, and Jer·o·boʹam^&#42;1^ sat on his throne. And Je·hoʹash was buried in Sa·marʹi·a with the kings of Israel.

[NOTE]
====
. That is, Jeroboam II.
====

[[v12-13-14]]

^<<v12-13-14,14>>^ Now when E·liʹsha became ill with the sickness from which he eventually died, Je·hoʹash the king of Israel came down to him and wept over him, saying: “My father, my father! The chariot of Israel and his horsemen!”

[[v12-13-15]]

^<<v12-13-15,15>>^ E·liʹsha then said to him: “Take a bow and arrows.” So he took a bow and arrows.

[[v12-13-16]]

^<<v12-13-16,16>>^ Then he said to the king of Israel: “Put your hand to the bow.” So he put his hand to it, after which E·liʹsha laid his hands on the king’s hands.

[[v12-13-17]]

^<<v12-13-17,17>>^ Then he said: “Open the window toward the east.” So he opened it. E·liʹsha said: “Shoot!” So he shot. He now said: “Jehovah’s arrow of victory,^&#42;1^ the arrow of victory over^&#42;2^ Syria! You will strike down^&#42;3^ Syria at Aʹphek until you finish it off.”

[NOTE]
====
. Or “salvation.”
. Or “salvation against.”
. Or “defeat.”
====

[[v12-13-18]]

^<<v12-13-18,18>>^ He continued: “Take the arrows,” and he took them. Then he said to the king of Israel: “Strike the ground.” So he struck the ground three times and stopped.

[[v12-13-19]]

^<<v12-13-19,19>>^ At that the man of the true God grew indignant at him and said: “You should have struck the ground five or six times! Then you would have struck down Syria until you finished it off, but now you will strike down Syria only three times.”

[[v12-13-20]]

^<<v12-13-20,20>>^ After that E·liʹsha died and was buried. There were Moʹab·ite marauder bands that would come into the land at the beginning of the year.^&#42;1^

[NOTE]
====
. Lit., “at the coming in of the year,” likely in the spring.
====

[[v12-13-21]]

^<<v12-13-21,21>>^ As some men were burying a man, they saw the marauder band, so they quickly threw the man into E·liʹsha’s burial place and ran off. When the man touched the bones of E·liʹsha, he came to life and stood on his feet.

[[v12-13-22]]

^<<v12-13-22,22>>^ Now King Hazʹa·el of Syria oppressed Israel all the days of Je·hoʹa·haz.

[[v12-13-23]]

^<<v12-13-23,23>>^ However, Jehovah extended favor and mercy to them and showed his concern for them for the sake of his covenant with Abraham, Isaac, and Jacob. He did not want to bring them to ruin, and he has not cast them away from his presence to this day.

[[v12-13-24]]

^<<v12-13-24,24>>^ When King Hazʹa·el of Syria died, his son Ben-haʹdad became king in his place.

[[v12-13-25]]

^<<v12-13-25,25>>^ Je·hoʹash the son of Je·hoʹa·haz then took back from Ben-haʹdad the son of Hazʹa·el the cities that he had taken in war from Je·hoʹa·haz his father. Three times Je·hoʹash struck him down,^&#42;1^ and he recovered the cities of Israel.

[NOTE]
====
. Or “defeated him.”
====

'''

xref:012-2-kings/012-2-kings-012.adoc#v12-12-0[&#60; Capítulo Anterior] | <<v12-13-0,Topo>> | xref:012-2-kings/012-2-kings-014.adoc#v12-14-0[Próximo Capítulo &#62;]