include::./index.adoc[]

[[v12-3-0]]
=== The Second of Kings, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-3-1]]

^<<v12-3-1,1>>^ Je·hoʹram the son of Aʹhab became king over Israel in Sa·marʹi·a in the 18th year of King Je·hoshʹa·phat of Judah, and he reigned for 12 years.

[[v12-3-2]]

^<<v12-3-2,2>>^ He kept doing what was bad in Jehovah’s eyes, but not to the extent of his father or his mother, for he removed the sacred pillar of Baʹal that his father had made.

[[v12-3-3]]

^<<v12-3-3,3>>^ However, he clung to the sins that Jer·o·boʹam the son of Neʹbat had caused Israel to commit. He did not depart from them.

[[v12-3-4]]

^<<v12-3-4,4>>^ Now Meʹsha the king of Moʹab was a sheep raiser, and he used to pay 100,000 lambs and 100,000 unshorn rams as tribute to the king of Israel.

[[v12-3-5]]

^<<v12-3-5,5>>^ As soon as Aʹhab died, the king of Moʹab revolted against the king of Israel.

[[v12-3-6]]

^<<v12-3-6,6>>^ So King Je·hoʹram went out on that day from Sa·marʹi·a and mustered all Israel.

[[v12-3-7]]

^<<v12-3-7,7>>^ He also sent a message to King Je·hoshʹa·phat of Judah, saying: “The king of Moʹab has revolted against me. Will you go with me to war against Moʹab?” To this he said: “I will go. I am the same as you. My people are the same as your people. My horses are the same as your horses.”

[[v12-3-8]]

^<<v12-3-8,8>>^ Then he asked: “By which way should we go up?” He replied: “By the way of the wilderness of Eʹdom.”

[[v12-3-9]]

^<<v12-3-9,9>>^ The king of Israel then set out with the king of Judah and the king of Eʹdom. After they journeyed roundabout for seven days, there was no water for the camp and for the domestic animals that were following behind them.

[[v12-3-10]]

^<<v12-3-10,10>>^ The king of Israel said: “How terrible! Jehovah has called these three kings, only to give them into the hand of Moʹab!”

[[v12-3-11]]

^<<v12-3-11,11>>^ At that Je·hoshʹa·phat said: “Is there no prophet of Jehovah here through whom we may inquire of Jehovah?” So one of the servants of the king of Israel answered: “There is E·liʹsha the son of Shaʹphat, who used to pour out water on the hands of E·liʹjah.”^&#42;1^

[NOTE]
====
. Or “who was Elijah’s servant.”
====

[[v12-3-12]]

^<<v12-3-12,12>>^ Then Je·hoshʹa·phat said: “The word of Jehovah is with him.” So the king of Israel and Je·hoshʹa·phat and the king of Eʹdom went down to him.

[[v12-3-13]]

^<<v12-3-13,13>>^ E·liʹsha said to the king of Israel: “What do I have to do with you?^&#42;1^ Go to the prophets of your father and to the prophets of your mother.” But the king of Israel said to him: “No, for it is Jehovah who has called these three kings to give them into the hand of Moʹab.”

[NOTE]
====
. Lit., “What to me and to you?”
====

[[v12-3-14]]

^<<v12-3-14,14>>^ To this E·liʹsha said: “As surely as Jehovah of armies whom I serve^&#42;1^ is living, if I did not have regard for King Je·hoshʹa·phat of Judah, I would not look at you or take notice of you.

[NOTE]
====
. Lit., “before whom I stand.”
====

[[v12-3-15]]

^<<v12-3-15,15>>^ Now bring me a harpist.”^&#42;1^ As soon as the harpist started playing, the hand of Jehovah came on him.

[NOTE]
====
. Or “musician.”
====

[[v12-3-16]]

^<<v12-3-16,16>>^ He said, “This is what Jehovah says: ‘Dig trench after trench in this valley,^&#42;1^

[NOTE]
====
. Or “wadi.”
====

[[v12-3-17]]

^<<v12-3-17,17>>^ for this is what Jehovah says: “You will not see wind, and you will not see rain; yet this valley^&#42;1^ will be filled with water, and you will drink from it, you, your livestock, and your other animals.”’

[NOTE]
====
. Or “wadi.”
====

[[v12-3-18]]

^<<v12-3-18,18>>^ But this is a trivial thing in the eyes of Jehovah, for he will also give Moʹab into your hand.

[[v12-3-19]]

^<<v12-3-19,19>>^ You must strike down every fortified city and every choice city, you should cut down every good tree, you should stop up all the springs of water, and you should ruin every good plot of land with stones.”

[[v12-3-20]]

^<<v12-3-20,20>>^ And in the morning, at the time of the morning grain offering, water was suddenly coming from the direction of Eʹdom, and the land became filled with the water.

[[v12-3-21]]

^<<v12-3-21,21>>^ All the Moʹab·ites heard that the kings had come up to fight against them, so they called together all the men who could bear arms,^&#42;1^ and they stationed themselves at the border.

[NOTE]
====
. Or “all who girded on a belt.”
====

[[v12-3-22]]

^<<v12-3-22,22>>^ When they got up early in the morning, the sun was shining on the water, and to the Moʹab·ites on the opposite side, the water looked red like blood.

[[v12-3-23]]

^<<v12-3-23,23>>^ They said: “This is blood! The kings have surely slaughtered one another with the sword. So, then, to the spoil, O Moʹab!”

[[v12-3-24]]

^<<v12-3-24,24>>^ When they came into the camp of Israel, the Israelites rose up and began striking down the Moʹab·ites, who fled from them. They advanced into Moʹab, striking the Moʹab·ites down as they went.

[[v12-3-25]]

^<<v12-3-25,25>>^ They tore down the cities, and each man threw a stone into every good plot of land, filling it with stones; they stopped up every spring of water, and they cut down every good tree. Finally only the stone walls of Kir-harʹe·seth remained standing, and the slingers surrounded it and struck it down.

[[v12-3-26]]

^<<v12-3-26,26>>^ When the king of Moʹab saw that the battle was lost, he took with him 700 men armed with swords to break through to the king of Eʹdom; but they were not able to.

[[v12-3-27]]

^<<v12-3-27,27>>^ So he took his firstborn son who was going to reign in his place and offered him up as a burnt sacrifice on the wall. And there came to be great indignation against Israel, so they withdrew from against him and returned to their land.

'''

xref:012-2-kings/012-2-kings-002.adoc#v12-2-0[&#60; Capítulo Anterior] | <<v12-3-0,Topo>> | xref:012-2-kings/012-2-kings-004.adoc#v12-4-0[Próximo Capítulo &#62;]