include::./index.adoc[]

[[v12-14-0]]
=== The Second of Kings, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-14-1]]

^<<v12-14-1,1>>^ In the second year of Je·hoʹash the son of Je·hoʹa·haz the king of Israel, Am·a·ziʹah the son of King Je·hoʹash of Judah became king.

[[v12-14-2]]

^<<v12-14-2,2>>^ He was 25 years old when he became king, and he reigned for 29 years in Jerusalem. His mother’s name was Je·ho·adʹdin of Jerusalem.

[[v12-14-3]]

^<<v12-14-3,3>>^ He continued to do what was right in Jehovah’s eyes, but not like David his forefather. He did everything as Je·hoʹash his father had done.

[[v12-14-4]]

^<<v12-14-4,4>>^ However, the high places were not removed, and the people were still sacrificing and making sacrificial smoke on the high places.

[[v12-14-5]]

^<<v12-14-5,5>>^ As soon as he had the kingdom firmly in his control, he struck down his servants who had struck down his father the king.

[[v12-14-6]]

^<<v12-14-6,6>>^ But he did not put the sons of the murderers to death, in harmony with Jehovah’s commandment written in the book of Moses’ Law: “Fathers should not be put to death for their sons, and sons should not be put to death for their fathers; but each one should be put to death for his own sin.”

[[v12-14-7]]

^<<v12-14-7,7>>^ He struck down the Eʹdom·ites in the Valley of Salt, 10,000 men, and captured Seʹla in the war, and its name became Jokʹthe·el to this day.

[[v12-14-8]]

^<<v12-14-8,8>>^ Then Am·a·ziʹah sent messengers to Je·hoʹash son of Je·hoʹa·haz son of Jeʹhu the king of Israel, saying: “Come, let us confront each other in battle.”^&#42;1^

[NOTE]
====
. Or “meet face-to-face.”
====

[[v12-14-9]]

^<<v12-14-9,9>>^ King Je·hoʹash of Israel sent this message to King Am·a·ziʹah of Judah: “The thorny weed in Lebʹa·non sent a message to the cedar in Lebʹa·non, ‘Give your daughter to my son as a wife.’ However, a wild beast of Lebʹa·non passed by and trampled down the thorny weed.

[[v12-14-10]]

^<<v12-14-10,10>>^ True, you have struck down Eʹdom, so your heart has become arrogant. Enjoy your glory, but stay in your own house.^&#42;1^ Why should you provoke disaster and fall, bringing Judah down with you?”

[NOTE]
====
. Or “palace.”
====

[[v12-14-11]]

^<<v12-14-11,11>>^ But Am·a·ziʹah did not listen.
So King Je·hoʹash of Israel went up, and he and King Am·a·ziʹah of Judah confronted each other in battle at Beth-sheʹmesh, which belongs to Judah.

[[v12-14-12]]

^<<v12-14-12,12>>^ Judah was defeated by Israel, so each one fled to his home.^&#42;1^

[NOTE]
====
. Lit., “tent.”
====

[[v12-14-13]]

^<<v12-14-13,13>>^ King Je·hoʹash of Israel captured King Am·a·ziʹah of Judah, son of Je·hoʹash son of A·ha·ziʹah, at Beth-sheʹmesh. Then they came to Jerusalem, and he made a breach in the wall of Jerusalem from the Gate of Eʹphra·im to the Corner Gate, 400 cubits.^&#42;1^

[NOTE]
====
. About 178 m (584 ft). See App. B14.
====

[[v12-14-14]]

^<<v12-14-14,14>>^ He took all the gold and the silver and all the articles that were found in the house of Jehovah and in the treasuries of the house^&#42;1^ of the king, as well as hostages. Then he returned to Sa·marʹi·a.

[NOTE]
====
. Or “palace.”
====

[[v12-14-15]]

^<<v12-14-15,15>>^ As for the rest of the history of Je·hoʹash, what he did and his mightiness and how he fought against King Am·a·ziʹah of Judah, is it not written in the book of the history of the times of the kings of Israel?

[[v12-14-16]]

^<<v12-14-16,16>>^ Then Je·hoʹash was laid to rest with his forefathers and was buried in Sa·marʹi·a with the kings of Israel; and his son Jer·o·boʹam^&#42;1^ became king in his place.

[NOTE]
====
. That is, Jeroboam II.
====

[[v12-14-17]]

^<<v12-14-17,17>>^ Am·a·ziʹah the son of Je·hoʹash the king of Judah lived for 15 years after the death of Je·hoʹash the son of Je·hoʹa·haz the king of Israel.

[[v12-14-18]]

^<<v12-14-18,18>>^ As for the rest of the history of Am·a·ziʹah, is it not written in the book of the history of the times of the kings of Judah?

[[v12-14-19]]

^<<v12-14-19,19>>^ Later a conspiracy was formed against him at Jerusalem, and he fled to Laʹchish, but they sent men after him to Laʹchish and put him to death there.

[[v12-14-20]]

^<<v12-14-20,20>>^ So they carried him back on horses, and he was buried in Jerusalem with his forefathers in the City of David.

[[v12-14-21]]

^<<v12-14-21,21>>^ Then all the people of Judah took Az·a·riʹah,^&#42;1^ who was 16 years old, and made him king in place of his father Am·a·ziʹah.

[NOTE]
====
. Meaning “Jehovah Has Helped.” He is called Uzziah at 2Ki 15:13; 2Ch 26:1-23; Isa 6:1; and Zec 14:5.
====

[[v12-14-22]]

^<<v12-14-22,22>>^ He rebuilt Eʹlath and restored it to Judah after the king^&#42;1^ was laid to rest with his forefathers.

[NOTE]
====
. That is, his father Amaziah.
====

[[v12-14-23]]

^<<v12-14-23,23>>^ In the 15th year of Am·a·ziʹah the son of Je·hoʹash the king of Judah, Jer·o·boʹam the son of King Je·hoʹash of Israel became king in Sa·marʹi·a, and he reigned for 41 years.

[[v12-14-24]]

^<<v12-14-24,24>>^ He continued to do what was bad in Jehovah’s eyes. He did not depart from all the sins that Jer·o·boʹam the son of Neʹbat had caused Israel to commit.

[[v12-14-25]]

^<<v12-14-25,25>>^ He restored the boundary of Israel from Leʹbo-haʹmath^&#42;1^ clear to the Sea of the Arʹa·bah,^&#42;2^ according to the word that Jehovah the God of Israel spoke through his servant Joʹnah the son of A·mitʹtai, the prophet from Gath-heʹpher.

[NOTE]
====
. Or “the entrance of Hamath.”
. That is, the Salt Sea, or the Dead Sea.
====

[[v12-14-26]]

^<<v12-14-26,26>>^ For Jehovah had seen the very bitter affliction of Israel. There was no one left to help Israel, not even the helpless or the weak.

[[v12-14-27]]

^<<v12-14-27,27>>^ But Jehovah had promised not to wipe out the name of Israel from under the heavens. So he saved them by the hand of Jer·o·boʹam the son of Je·hoʹash.

[[v12-14-28]]

^<<v12-14-28,28>>^ As for the rest of the history of Jer·o·boʹam, all that he did and his mightiness, how he fought and how he restored Damascus and Haʹmath to Judah in Israel, is it not written in the book of the history of the times of the kings of Israel?

[[v12-14-29]]

^<<v12-14-29,29>>^ Then Jer·o·boʹam was laid to rest with his forefathers, with the kings of Israel; and his son Zech·a·riʹah became king in his place.

'''

xref:012-2-kings/012-2-kings-013.adoc#v12-13-0[&#60; Capítulo Anterior] | <<v12-14-0,Topo>> | xref:012-2-kings/012-2-kings-015.adoc#v12-15-0[Próximo Capítulo &#62;]