include::./index.adoc[]

[[v12-16-0]]
=== The Second of Kings, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-16-1]]

^<<v12-16-1,1>>^ In the 17th year of Peʹkah the son of Rem·a·liʹah, Aʹhaz the son of King Joʹtham of Judah became king.

[[v12-16-2]]

^<<v12-16-2,2>>^ Aʹhaz was 20 years old when he became king, and he reigned for 16 years in Jerusalem. He did not do what was right in the eyes of Jehovah his God as David his forefather had done.

[[v12-16-3]]

^<<v12-16-3,3>>^ Instead, he walked in the way of the kings of Israel, and he even made his own son pass through the fire, following the detestable practices of the nations that Jehovah had driven out from before the Israelites.

[[v12-16-4]]

^<<v12-16-4,4>>^ He also kept sacrificing and making sacrificial smoke on the high places, on the hills, and under every luxuriant tree.

[[v12-16-5]]

^<<v12-16-5,5>>^ It was then that King Reʹzin of Syria and Peʹkah son of Rem·a·liʹah the king of Israel came up to wage war against Jerusalem. They laid siege against Aʹhaz but were not able to capture the city.

[[v12-16-6]]

^<<v12-16-6,6>>^ At that time King Reʹzin of Syria restored Eʹlath to Eʹdom, after which he drove the Jews^&#42;1^ out of Eʹlath. And the Eʹdom·ites entered Eʹlath, and they have occupied it down to this day.

[NOTE]
====
. Or “the men of Judah.”
====

[[v12-16-7]]

^<<v12-16-7,7>>^ So Aʹhaz sent messengers to King Tigʹlath-pil·eʹser of As·syrʹi·a, saying: “I am your servant and your son. Come up and save me from the hand of the king of Syria and the hand of the king of Israel, who are attacking me.”

[[v12-16-8]]

^<<v12-16-8,8>>^ Aʹhaz then took the silver and the gold that was to be found at the house of Jehovah and in the treasuries of the king’s house^&#42;1^ and sent the king of As·syrʹi·a a bribe.

[NOTE]
====
. Or “palace.”
====

[[v12-16-9]]

^<<v12-16-9,9>>^ The king of As·syrʹi·a responded to his request, and he went up to Damascus and captured it and led its people into exile to Kir, and he put Reʹzin to death.

[[v12-16-10]]

^<<v12-16-10,10>>^ Then King Aʹhaz went to meet King Tigʹlath-pil·eʹser of As·syrʹi·a at Damascus. When he saw the altar that was in Damascus, King Aʹhaz sent U·riʹjah the priest a plan of the altar, showing its pattern and how it was made.

[[v12-16-11]]

^<<v12-16-11,11>>^ U·riʹjah the priest built an altar according to all the directions that King Aʹhaz had sent from Damascus. U·riʹjah the priest finished building it before King Aʹhaz returned from Damascus.

[[v12-16-12]]

^<<v12-16-12,12>>^ When the king returned from Damascus and saw the altar, he approached the altar and made offerings on it.

[[v12-16-13]]

^<<v12-16-13,13>>^ And on that altar he continued to make his burnt offerings and his grain offerings smoke; he also poured out his drink offerings and sprinkled the blood of his communion sacrifices on it.

[[v12-16-14]]

^<<v12-16-14,14>>^ Then he moved the copper altar that was before Jehovah from its place in front of the house, from between his own altar and the house of Jehovah, and he put it at the north side of his own altar.

[[v12-16-15]]

^<<v12-16-15,15>>^ King Aʹhaz commanded U·riʹjah the priest: “Make the morning burnt offering smoke on the great altar, also the evening grain offering, the king’s burnt offering, and his grain offering, as well as the burnt offerings, the grain offerings, and the drink offerings of all the people. You should also sprinkle on it all the blood of the burnt offerings and all the blood of the other sacrifices. As for the copper altar, let me decide what to do with it.”

[[v12-16-16]]

^<<v12-16-16,16>>^ And U·riʹjah the priest did everything that King Aʹhaz had commanded.

[[v12-16-17]]

^<<v12-16-17,17>>^ Furthermore, King Aʹhaz cut the side panels of the carriages into pieces and removed the basins from them, and he took the Sea down off the copper bulls that supported it and put it on a stone pavement.

[[v12-16-18]]

^<<v12-16-18,18>>^ And the covered structure for the Sabbath that had been built in the house and the king’s outer entryway he shifted away from the house of Jehovah; he did so because of the king of As·syrʹi·a.

[[v12-16-19]]

^<<v12-16-19,19>>^ As for the rest of the history of Aʹhaz, what he did, is it not written in the book of the history of the times of the kings of Judah?

[[v12-16-20]]

^<<v12-16-20,20>>^ Then Aʹhaz was laid to rest with his forefathers and was buried with his forefathers in the City of David; and his son Hez·e·kiʹah^&#42;1^ became king in his place.

[NOTE]
====
. Meaning “Jehovah Strengthens.”
====

'''

xref:012-2-kings/012-2-kings-015.adoc#v12-15-0[&#60; Capítulo Anterior] | <<v12-16-0,Topo>> | xref:012-2-kings/012-2-kings-017.adoc#v12-17-0[Próximo Capítulo &#62;]