include::./index.adoc[]

[[v12-24-0]]
=== The Second of Kings, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v12-24-1]]

^<<v12-24-1,1>>^ In Je·hoiʹa·kim’s days King Neb·u·chad·nezʹzar of Babylon came against him, and Je·hoiʹa·kim became his servant for three years. However, he turned against him and rebelled.

[[v12-24-2]]

^<<v12-24-2,2>>^ Then Jehovah began to send against him marauder bands of Chal·deʹans, Syrians, Moʹab·ites, and Amʹmon·ites. He kept sending them against Judah to destroy it, according to Jehovah’s word that he had spoken through his servants the prophets.

[[v12-24-3]]

^<<v12-24-3,3>>^ Surely it was by the order of Jehovah that this happened to Judah, to remove them from his sight because of all the sins that Ma·nasʹseh had committed,

[[v12-24-4]]

^<<v12-24-4,4>>^ and also the innocent blood that he had shed, for he had filled Jerusalem with innocent blood and Jehovah was not willing to forgive.

[[v12-24-5]]

^<<v12-24-5,5>>^ As for the rest of the history of Je·hoiʹa·kim, all that he did, is it not written in the book of the history of the times of the kings of Judah?

[[v12-24-6]]

^<<v12-24-6,6>>^ Then Je·hoiʹa·kim was laid to rest with his forefathers; and his son Je·hoiʹa·chin became king in his place.

[[v12-24-7]]

^<<v12-24-7,7>>^ Never again did the king of Egypt venture out of his land, for the king of Babylon had taken all that belonged to the king of Egypt, from the Wadi^&#42;1^ of Egypt up to the Eu·phraʹtes River.

[NOTE]
====
. See Glossary.
====

[[v12-24-8]]

^<<v12-24-8,8>>^ Je·hoiʹa·chin was 18 years old when he became king, and he reigned for three months in Jerusalem. His mother’s name was Ne·hushʹta the daughter of El·naʹthan of Jerusalem.

[[v12-24-9]]

^<<v12-24-9,9>>^ He continued to do what was bad in Jehovah’s eyes, according to all that his father had done.

[[v12-24-10]]

^<<v12-24-10,10>>^ During that time the servants of King Neb·u·chad·nezʹzar of Babylon came up against Jerusalem, and the city came under siege.

[[v12-24-11]]

^<<v12-24-11,11>>^ King Neb·u·chad·nezʹzar of Babylon came to the city while his servants were laying siege to it.

[[v12-24-12]]

^<<v12-24-12,12>>^ King Je·hoiʹa·chin of Judah went out to the king of Babylon, along with his mother, his servants, his princes, and his court officials; and the king of Babylon took him captive in the eighth year of his reign.

[[v12-24-13]]

^<<v12-24-13,13>>^ Then he took out from there all the treasures of the house of Jehovah and the treasures of the king’s house.^&#42;1^ He cut into pieces all the gold utensils that Solʹo·mon the king of Israel had made in the temple of Jehovah. This happened just as Jehovah had foretold.

[NOTE]
====
. Or “palace.”
====

[[v12-24-14]]

^<<v12-24-14,14>>^ He took into exile all Jerusalem, all the princes, all the mighty warriors, and every craftsman and metalworker^&#42;1^—he took 10,000 into exile. No one was left behind except the poorest people of the land.

[NOTE]
====
. Or possibly, “builder of bulwarks.”
====

[[v12-24-15]]

^<<v12-24-15,15>>^ Thus he took Je·hoiʹa·chin into exile to Babylon; he also led away the king’s mother, the king’s wives, his court officials, and the foremost men of the land, taking them into exile from Jerusalem to Babylon.

[[v12-24-16]]

^<<v12-24-16,16>>^ The king of Babylon also took into exile to Babylon all the warriors, 7,000, as well as 1,000 craftsmen and metalworkers,^&#42;1^ all of them mighty men and trained for war.

[NOTE]
====
. Or possibly, “builders of bulwarks.”
====

[[v12-24-17]]

^<<v12-24-17,17>>^ The king of Babylon made Mat·ta·niʹah, Je·hoiʹa·chin’s uncle, king in his place and changed his name to Zed·e·kiʹah.

[[v12-24-18]]

^<<v12-24-18,18>>^ Zed·e·kiʹah was 21 years old when he became king, and he reigned for 11 years in Jerusalem. His mother’s name was Ha·muʹtal the daughter of Jeremiah from Libʹnah.

[[v12-24-19]]

^<<v12-24-19,19>>^ He continued to do what was bad in Jehovah’s eyes, according to all that Je·hoiʹa·kim had done.

[[v12-24-20]]

^<<v12-24-20,20>>^ It was because of Jehovah’s anger that these things took place in Jerusalem and in Judah, until he cast them out of his sight. And Zed·e·kiʹah rebelled against the king of Babylon.

'''

xref:012-2-kings/012-2-kings-023.adoc#v12-23-0[&#60; Capítulo Anterior] | <<v12-24-0,Topo>> | xref:012-2-kings/012-2-kings-025.adoc#v12-25-0[Próximo Capítulo &#62;]