include::./index.adoc[]

[[v9-30-0]]
=== The First of Samuel, 30
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-30-1]]

^<<v9-30-1,1>>^ When David and his men came to Zikʹlag on the third day, the A·malʹek·ites had made a raid on the south^&#42;1^ and on Zikʹlag, and they had attacked Zikʹlag and burned it with fire.

[NOTE]
====
. Or “the Negeb.”
====

[[v9-30-2]]

^<<v9-30-2,2>>^ They had taken captive the women and all who were in it, from the smallest to the greatest. They had not killed anyone, but they had carried them off and gone on their way.

[[v9-30-3]]

^<<v9-30-3,3>>^ When David and his men came to the city, they found it burned down, and their wives and their sons and their daughters had been carried off captive.

[[v9-30-4]]

^<<v9-30-4,4>>^ So David and the men with him began weeping loudly until they had no strength left to weep.

[[v9-30-5]]

^<<v9-30-5,5>>^ David’s two wives had also been carried off captive, A·hinʹo·am of Jezʹre·el and Abʹi·gail the widow of Naʹbal the Carʹmel·ite.

[[v9-30-6]]

^<<v9-30-6,6>>^ David was very distressed, because the men were talking of stoning him, for all the men^&#42;1^ had become very bitter over the loss of their sons and daughters. But David strengthened himself by Jehovah his God.

[NOTE]
====
. Or “for the souls of all the people.”
====

[[v9-30-7]]

^<<v9-30-7,7>>^ David then said to A·biʹa·thar the priest, the son of A·himʹe·lech: “Please bring the ephʹod here.” So A·biʹa·thar brought the ephʹod to David.

[[v9-30-8]]

^<<v9-30-8,8>>^ David inquired of Jehovah: “Should I chase after this marauder band? Will I overtake them?” At this He said to him: “Go in pursuit, for you will certainly overtake them, and you will make the rescue.”

[[v9-30-9]]

^<<v9-30-9,9>>^ David immediately set out with the 600 men who were with him, and they went on as far as the Wadi^&#42;1^ Beʹsor, where some of the men stayed behind.

[NOTE]
====
. See Glossary.
====

[[v9-30-10]]

^<<v9-30-10,10>>^ David kept up the chase with 400 men, but the 200 men who were too tired to cross the Wadi Beʹsor stayed behind.

[[v9-30-11]]

^<<v9-30-11,11>>^ They found an Egyptian man in the field and took him to David. They gave him food to eat and water to drink,

[[v9-30-12]]

^<<v9-30-12,12>>^ as well as a slice of a cake of pressed figs and two cakes of raisins. After he ate, he regained his strength,^&#42;1^ for he had not eaten any food or drunk any water for three days and three nights.

[NOTE]
====
. Lit., “his spirit returned to him.”
====

[[v9-30-13]]

^<<v9-30-13,13>>^ David now asked him: “To whom do you belong, and where are you from?” to which he said: “I am an Egyptian attendant, a slave of an A·malʹek·ite man, but my master left me because I got sick three days ago.

[[v9-30-14]]

^<<v9-30-14,14>>^ We made a raid on the south^&#42;1^ of the Cherʹe·thites and on the territory of Judah and on the south^&#42;2^ of Caʹleb, and Zikʹlag we burned with fire.”

[NOTE]
====
. Or “the Negeb.”
. Or “the Negeb.”
====

[[v9-30-15]]

^<<v9-30-15,15>>^ At this David said to him: “Will you lead me down to this marauder band?” He replied: “If you swear to me by God that you will not put me to death and that you will not hand me over to my master, I will lead you down to this marauder band.”

[[v9-30-16]]

^<<v9-30-16,16>>^ So he led him down to where they were spread out all over the land, eating and drinking and celebrating because of all the great spoil that they had taken from the land of the Phi·lisʹtines and the land of Judah.

[[v9-30-17]]

^<<v9-30-17,17>>^ Then David struck them down from the morning darkness until the following evening; not a man escaped except 400 men who fled on camels.

[[v9-30-18]]

^<<v9-30-18,18>>^ David recovered all that the A·malʹek·ites had taken, and David rescued his two wives.

[[v9-30-19]]

^<<v9-30-19,19>>^ Nothing of theirs was missing, from the smallest to the greatest. They recovered their sons and daughters and the spoil; David recovered everything that they had taken.

[[v9-30-20]]

^<<v9-30-20,20>>^ So David took all the flocks and the herds, which they drove before their own livestock. They said: “This is David’s spoil.”

[[v9-30-21]]

^<<v9-30-21,21>>^ Then David came to the 200 men who had been too tired to go along with David and who had stayed behind by the Wadi Beʹsor, and they came out to meet David and the people with him. When David came near to the men, he asked them how they were.

[[v9-30-22]]

^<<v9-30-22,22>>^ However, every bad and worthless man among those who had gone with David said: “Since they did not go with us, we will not give them any of the spoil that we recovered except that each one may take his wife and his sons and go away.”

[[v9-30-23]]

^<<v9-30-23,23>>^ But David said: “You must not do this, my brothers, with what Jehovah has given us. He protected us and gave into our hand the marauder band that came against us.

[[v9-30-24]]

^<<v9-30-24,24>>^ Who would agree with you on this? The share of the one who went down into the battle will be the same as the share of the one who sat by the baggage. All will have a share together.”

[[v9-30-25]]

^<<v9-30-25,25>>^ And from that day forward, he kept it set as a regulation and a rule for Israel down to this day.

[[v9-30-26]]

^<<v9-30-26,26>>^ When David returned to Zikʹlag, he sent some of the spoil to the elders of Judah who were his friends, saying: “Here is a gift^&#42;1^ for you from the spoil of Jehovah’s enemies.”

[NOTE]
====
. Lit., “blessing.”
====

[[v9-30-27]]

^<<v9-30-27,27>>^ He sent it to those who were in Bethʹel, to those in Raʹmoth of the Negʹeb,^&#42;1^ to those in Jatʹtir,

[NOTE]
====
. Or “the south.”
====

[[v9-30-28]]

^<<v9-30-28,28>>^ to those in A·roʹer, to those in Siphʹmoth, to those in Esh·te·moʹa,

[[v9-30-29]]

^<<v9-30-29,29>>^ to those in Raʹcal, to those in the cities of the Je·rahʹme·el·ites, to those in the cities of the Kenʹites,

[[v9-30-30]]

^<<v9-30-30,30>>^ to those in Horʹmah, to those in Borʹa·shan, to those in Aʹthach,

[[v9-30-31]]

^<<v9-30-31,31>>^ to those in Hebʹron, and to all the places that David and his men had frequented.

'''

xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[&#60; Capítulo Anterior] | <<v9-30-0,Topo>> | xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[Próximo Capítulo &#62;]