include::./index.adoc[]

[[v9-18-0]]
=== The First of Samuel, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-18-1]]

^<<v9-18-1,1>>^ As soon as David had finished speaking to Saul, Jonʹa·than and David became bound together in close friendship,^&#42;1^ and Jonʹa·than began to love him as himself.^&#42;2^

[NOTE]
====
. Or “Jonathan’s soul became bound with David’s soul.”
. Or “as his own soul.”
====

[[v9-18-2]]

^<<v9-18-2,2>>^ From that day, Saul kept David with him, and he did not allow him to return to his father’s house.

[[v9-18-3]]

^<<v9-18-3,3>>^ And Jonʹa·than and David made a covenant, because he loved him as himself.^&#42;1^

[NOTE]
====
. Or “as his own soul.”
====

[[v9-18-4]]

^<<v9-18-4,4>>^ Jonʹa·than took off the sleeveless coat that he wore and gave it to David, along with his gear, his sword, his bow, and his belt.

[[v9-18-5]]

^<<v9-18-5,5>>^ David began going out and was successful^&#42;1^ wherever Saul would send him. So Saul put him in charge of the fighting men, and this pleased all the people and the servants of Saul.

[NOTE]
====
. Or “acted wisely.”
====

[[v9-18-6]]

^<<v9-18-6,6>>^ When David and the others would return from striking down the Phi·lisʹtines, the women would come out from all the cities of Israel with song and dances to meet King Saul with tambourines, with rejoicing, and with lutes.

[[v9-18-7]]

^<<v9-18-7,7>>^ The women who were celebrating would sing:
“Saul has struck down his thousands,
And David his tens of thousands.”

[[v9-18-8]]

^<<v9-18-8,8>>^ Saul became very angry, and this song displeased him, for he said: “They have credited David with tens of thousands, but to me they have credited thousands. The only thing left to give him is the kingship!”

[[v9-18-9]]

^<<v9-18-9,9>>^ From that day on, Saul was always looking at David suspiciously.

[[v9-18-10]]

^<<v9-18-10,10>>^ The next day a bad spirit from God gripped Saul, and he started to act strangely^&#42;1^ inside the house, while David was playing music on the harp as on other occasions. Saul had a spear in his hand,

[NOTE]
====
. Or “behaved like a prophet.”
====

[[v9-18-11]]

^<<v9-18-11,11>>^ and he hurled the spear, saying to himself: ‘I will pin David to the wall!’ But David escaped from him twice.

[[v9-18-12]]

^<<v9-18-12,12>>^ Then Saul was afraid of David because Jehovah was with him but had departed from Saul.

[[v9-18-13]]

^<<v9-18-13,13>>^ So Saul removed him from his presence and appointed him as chief of a thousand, and David would lead the army into battle.^&#42;1^

[NOTE]
====
. Lit., “and he went out and came in before the people.”
====

[[v9-18-14]]

^<<v9-18-14,14>>^ David continued to have success^&#42;1^ in all he did, and Jehovah was with him.

[NOTE]
====
. Or “act wisely.”
====

[[v9-18-15]]

^<<v9-18-15,15>>^ And when Saul saw that he was very successful, he became afraid of him.

[[v9-18-16]]

^<<v9-18-16,16>>^ But all Israel and Judah loved David, because he would lead them in their campaigns.

[[v9-18-17]]

^<<v9-18-17,17>>^ Saul later said to David: “Here is my oldest daughter Meʹrab. I will give her to you as a wife. However, you should continue to display your courage for me and fight the wars of Jehovah.” For Saul said to himself: ‘Do not let my hand come against him. Let the hand of the Phi·lisʹtines strike him.’

[[v9-18-18]]

^<<v9-18-18,18>>^ At this David said to Saul: “Who am I and who are my relatives, my father’s family in Israel, for me to become son-in-law to the king?”

[[v9-18-19]]

^<<v9-18-19,19>>^ However, when the time came to give Saul’s daughter Meʹrab to David, she had already been given to be the wife of Aʹdri·el the Me·holʹath·ite.

[[v9-18-20]]

^<<v9-18-20,20>>^ Now Saul’s daughter Miʹchal was in love with David, and it was reported to Saul, and this pleased him.

[[v9-18-21]]

^<<v9-18-21,21>>^ So Saul said: “I will give her to him to serve as a snare to him, so that the hand of the Phi·lisʹtines may come upon him.” Saul then said to David a second time: “You will form a marriage alliance with me^&#42;1^ today.”

[NOTE]
====
. Or “will become my son-in-law.”
====

[[v9-18-22]]

^<<v9-18-22,22>>^ Further, Saul ordered his servants: “Speak to David secretly and say, ‘Look! The king is pleased with you, and all his servants are fond of you. So now form a marriage alliance with the king.’”

[[v9-18-23]]

^<<v9-18-23,23>>^ When Saul’s servants told David these things, David said: “Is it a trivial matter to you to form a marriage alliance with the king when I am a man poor and lightly esteemed?”

[[v9-18-24]]

^<<v9-18-24,24>>^ Then Saul’s servants reported to him: “These are the words that David spoke.”

[[v9-18-25]]

^<<v9-18-25,25>>^ At that Saul said: “This is what you should say to David, ‘The king does not want any bride price except 100 foreskins of the Phi·lisʹtines, to take revenge on the enemies of the king.’” For Saul was scheming to have David fall by the hand of the Phi·lisʹtines.

[[v9-18-26]]

^<<v9-18-26,26>>^ So his servants reported these words to David, and it was pleasing to David to form a marriage alliance with the king. Before the allotted time,

[[v9-18-27]]

^<<v9-18-27,27>>^ David went with his men and struck down 200 Phi·lisʹtine men, and David brought the full number of their foreskins to the king, to form a marriage alliance with the king. Therefore, Saul gave him his daughter Miʹchal as a wife.

[[v9-18-28]]

^<<v9-18-28,28>>^ Saul realized that Jehovah was with David and that his daughter Miʹchal loved him.

[[v9-18-29]]

^<<v9-18-29,29>>^ This made Saul even more afraid of David, and Saul became an enemy of David for the rest of his life.

[[v9-18-30]]

^<<v9-18-30,30>>^ The princes of the Phi·lisʹtines would go out to battle, but as often as they went out, David was more successful^&#42;1^ than all the servants of Saul; and his name was highly esteemed.

[NOTE]
====
. Or “acted more wisely.”
====

'''

xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[&#60; Capítulo Anterior] | <<v9-18-0,Topo>> | xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[Próximo Capítulo &#62;]