include::./index.adoc[]

[[v9-24-0]]
=== The First of Samuel, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-24-1]]

^<<v9-24-1,1>>^ As soon as Saul returned from pursuing the Phi·lisʹtines, they told him: “Look! David is in the wilderness of En-gedʹi.”

[[v9-24-2]]

^<<v9-24-2,2>>^ So Saul took 3,000 men chosen from all Israel and went to look for David and his men on the rocky cliffs of the mountain goats.

[[v9-24-3]]

^<<v9-24-3,3>>^ Saul came to the stone sheepfolds along the road, where there was a cave, and he went in to relieve himself^&#42;1^ while David and his men were sitting in the recesses at the back of the cave.

[NOTE]
====
. Lit., “to cover his feet.”
====

[[v9-24-4]]

^<<v9-24-4,4>>^ David’s men said to him: “This is the day on which Jehovah is saying to you, ‘Look! I am giving your enemy into your hand, and you can do to him whatever seems good to you.’” So David rose up and quietly cut off the edge of Saul’s sleeveless coat.

[[v9-24-5]]

^<<v9-24-5,5>>^ But afterward David’s heart^&#42;1^ kept striking him because he had cut off the edge of Saul’s sleeveless coat.

[NOTE]
====
. Or “conscience.”
====

[[v9-24-6]]

^<<v9-24-6,6>>^ He said to his men: “It is unthinkable from Jehovah’s standpoint that I should do such a thing to my lord, the anointed of Jehovah, by lifting my hand against him, for he is the anointed of Jehovah.”

[[v9-24-7]]

^<<v9-24-7,7>>^ So David restrained^&#42;1^ his men with these words, and he did not allow them to attack Saul. As for Saul, he rose up from the cave and went on his way.

[NOTE]
====
. Or possibly, “dispersed.”
====

[[v9-24-8]]

^<<v9-24-8,8>>^ Then David got up and went out from the cave and called out after Saul: “My lord the king!” When Saul looked behind him, David bowed down low with his face to the ground and prostrated himself.

[[v9-24-9]]

^<<v9-24-9,9>>^ David said to Saul: “Why do you listen to the words of men who say, ‘Look! David is seeking to harm you’?

[[v9-24-10]]

^<<v9-24-10,10>>^ This very day your own eyes have seen how Jehovah gave you into my hand in the cave. But when someone said to kill you, I had pity on you and said, ‘I will not lift my hand against my lord, for he is the anointed of Jehovah.’

[[v9-24-11]]

^<<v9-24-11,11>>^ And look, my father, yes, see the edge of your sleeveless coat in my hand; for when I cut off the edge of your sleeveless coat, I did not kill you. You can now see and understand that I do not intend to harm you or to rebel, and I have not sinned against you, whereas you are hunting me down to take my life.^&#42;1^

[NOTE]
====
. Or “soul.”
====

[[v9-24-12]]

^<<v9-24-12,12>>^ May Jehovah judge between you and me, and may Jehovah take vengeance on you for me, but my hand will not come against you.

[[v9-24-13]]

^<<v9-24-13,13>>^ Just as the ancient proverb says, ‘From the wicked comes wickedness,’ but my hand will not come against you.

[[v9-24-14]]

^<<v9-24-14,14>>^ After whom has the king of Israel gone out? Whom are you chasing? A dead dog? A single flea?

[[v9-24-15]]

^<<v9-24-15,15>>^ May Jehovah be the judge, and he will judge between you and me, and he will see and will plead my case and judge me and rescue me from your hand.”

[[v9-24-16]]

^<<v9-24-16,16>>^ At the moment that David finished speaking these words to him, Saul said: “Is this your voice, my son David?” And Saul began to weep loudly.

[[v9-24-17]]

^<<v9-24-17,17>>^ He said to David: “You are more righteous than I am, for you have treated me well and I have repaid you with evil.

[[v9-24-18]]

^<<v9-24-18,18>>^ Yes, today you have told me of the good you did by not killing me when Jehovah surrendered me into your hand.

[[v9-24-19]]

^<<v9-24-19,19>>^ For what man finds his enemy and sends him on his way unharmed? Jehovah will reward you with good because of what you have done for me today.

[[v9-24-20]]

^<<v9-24-20,20>>^ And now look! I know that you will surely rule as king and that in your hand the kingdom of Israel will endure.

[[v9-24-21]]

^<<v9-24-21,21>>^ Now swear to me by Jehovah that you will not wipe out my descendants^&#42;1^ after me and that you will not annihilate my name out of my father’s house.”

[NOTE]
====
. Lit., “seed.”
====

[[v9-24-22]]

^<<v9-24-22,22>>^ So David swore to Saul, after which Saul went home. But David and his men went up to the stronghold.

'''

xref:009-1-samuel/009-1-samuel-023.adoc#v9-23-0[&#60; Capítulo Anterior] | <<v9-24-0,Topo>> | xref:009-1-samuel/009-1-samuel-025.adoc#v9-25-0[Próximo Capítulo &#62;]