include::./index.adoc[]

[[v9-3-0]]
=== The First of Samuel, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-3-1]]

^<<v9-3-1,1>>^ Meanwhile, the boy Samuel was ministering to Jehovah before Eʹli, but word from Jehovah had become rare in those days; visions were not widespread.

[[v9-3-2]]

^<<v9-3-2,2>>^ One day Eʹli was lying down in his usual place, and his eyes had grown dim; he was not able to see.

[[v9-3-3]]

^<<v9-3-3,3>>^ The lamp of God had not yet been extinguished, and Samuel was lying in the temple^&#42;1^ of Jehovah, where the Ark of God was.

[NOTE]
====
. That is, the tabernacle.
====

[[v9-3-4]]

^<<v9-3-4,4>>^ Jehovah then called Samuel. He answered: “Here I am.”

[[v9-3-5]]

^<<v9-3-5,5>>^ He ran to Eʹli and said: “Here I am, for you called me.” But he said: “I did not call. Lie down again.” So he went and lay down.

[[v9-3-6]]

^<<v9-3-6,6>>^ Jehovah called once again: “Samuel!” At this Samuel got up and went to Eʹli and said: “Here I am, for you called me.” But he said: “I did not call, my son. Lie down again.”

[[v9-3-7]]

^<<v9-3-7,7>>^ (Now Samuel had not yet come to know Jehovah, and the word of Jehovah had not yet been revealed to him.)

[[v9-3-8]]

^<<v9-3-8,8>>^ So Jehovah called again, a third time: “Samuel!” At that he got up and went to Eʹli and said: “Here I am, for you called me.”
Eʹli then realized that it was Jehovah who was calling the boy.

[[v9-3-9]]

^<<v9-3-9,9>>^ So Eʹli said to Samuel: “Go, lie down, and if he calls you, you should say, ‘Speak, Jehovah, for your servant is listening.’” And Samuel went and lay down in his place.

[[v9-3-10]]

^<<v9-3-10,10>>^ Jehovah came and stood there, and he called as at the other times: “Samuel, Samuel!” At this Samuel said: “Speak, for your servant is listening.”

[[v9-3-11]]

^<<v9-3-11,11>>^ Jehovah said to Samuel: “Look! I am doing something in Israel that will make both ears of anyone who hears about it tingle.

[[v9-3-12]]

^<<v9-3-12,12>>^ On that day I will carry out toward Eʹli all that I said about his house, from start to finish.

[[v9-3-13]]

^<<v9-3-13,13>>^ You must tell him that I am bringing a lasting judgment on his house for the error that he has known about, for his sons are cursing God, but he has not rebuked them.

[[v9-3-14]]

^<<v9-3-14,14>>^ That is why I have sworn to the house of Eʹli that the error of the house of Eʹli will never be atoned for by sacrifices or by offerings.”

[[v9-3-15]]

^<<v9-3-15,15>>^ Samuel lay down until the morning; then he opened the doors of Jehovah’s house. Samuel was afraid to tell Eʹli of the vision.

[[v9-3-16]]

^<<v9-3-16,16>>^ But Eʹli called for Samuel: “Samuel, my son!” At this he said: “Here I am.”

[[v9-3-17]]

^<<v9-3-17,17>>^ He asked: “What message did he speak to you? Please, do not hide it from me. May God do so to you and add to it if you hide from me a single word of all that he said to you.”

[[v9-3-18]]

^<<v9-3-18,18>>^ So Samuel told him everything, and he did not hide anything from him. Eʹli said: “It is Jehovah. Let him do what is good in his eyes.”

[[v9-3-19]]

^<<v9-3-19,19>>^ Samuel continued growing up, and Jehovah himself was with him and did not let any of all his words go unfulfilled.^&#42;1^

[NOTE]
====
. Lit., “fall to the earth.”
====

[[v9-3-20]]

^<<v9-3-20,20>>^ All Israel from Dan to Beʹer-sheʹba became aware that Samuel had been confirmed as Jehovah’s prophet.

[[v9-3-21]]

^<<v9-3-21,21>>^ And Jehovah continued to appear in Shiʹloh, for Jehovah revealed himself to Samuel in Shiʹloh by the word of Jehovah.

'''

xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[&#60; Capítulo Anterior] | <<v9-3-0,Topo>> | xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[Próximo Capítulo &#62;]