include::./index.adoc[]

[[v9-4-0]]
=== The First of Samuel, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-4-1]]

^<<v9-4-1,1>>^ And the word of Samuel went out to all Israel.
Then Israel went out to meet the Phi·lisʹtines in battle; they camped beside Eb·en·eʹzer, and the Phi·lisʹtines were encamped at Aʹphek.

[[v9-4-2]]

^<<v9-4-2,2>>^ The Phi·lisʹtines drew up in battle formation to meet Israel, but the battle went badly and Israel was defeated by the Phi·lisʹtines, who struck down about 4,000 men from the battle line in the field.

[[v9-4-3]]

^<<v9-4-3,3>>^ When the people returned to the camp, the elders of Israel said: “Why did Jehovah allow us to be defeated^&#42;1^ today by the Phi·lisʹtines? Let us take the ark of Jehovah’s covenant with us from Shiʹloh, so that it may be with us and save us from the hand of our enemies.”

[NOTE]
====
. Lit., “Why has Jehovah defeated us?”
====

[[v9-4-4]]

^<<v9-4-4,4>>^ So the people sent men to Shiʹloh, and they carried from there the ark of the covenant of Jehovah of armies, who sits enthroned above^&#42;1^ the cherubs. The two sons of Eʹli, Hophʹni and Phinʹe·has, were also there with the ark of the covenant of the true God.

[NOTE]
====
. Or possibly, “between.”
====

[[v9-4-5]]

^<<v9-4-5,5>>^ As soon as the ark of the covenant of Jehovah came into the camp, all the Israelites broke out into loud shouting, so that the earth shook.

[[v9-4-6]]

^<<v9-4-6,6>>^ When the Phi·lisʹtines heard the sound of the shouting, they said: “Why is there such loud shouting in the camp of the Hebrews?” Finally they learned that the Ark of Jehovah had come into the camp.

[[v9-4-7]]

^<<v9-4-7,7>>^ The Phi·lisʹtines became afraid, for they said: “God has come into the camp!” So they said: “Too bad for us, for nothing like this has ever happened before!

[[v9-4-8]]

^<<v9-4-8,8>>^ Too bad for us! Who will save us from the hand of this majestic God? This is the God who struck Egypt with every sort of slaughter in the wilderness.

[[v9-4-9]]

^<<v9-4-9,9>>^ Be courageous and act like men, you Phi·lisʹtines, so that you may not serve the Hebrews just as they have served you. Act like men and fight!”

[[v9-4-10]]

^<<v9-4-10,10>>^ So the Phi·lisʹtines fought and Israel was defeated, and each one fled to his tent. The slaughter was very great; on Israel’s side, 30,000 foot soldiers fell.

[[v9-4-11]]

^<<v9-4-11,11>>^ Moreover, the Ark of God was captured, and the two sons of Eʹli, Hophʹni and Phinʹe·has, died.

[[v9-4-12]]

^<<v9-4-12,12>>^ A man of Benjamin ran from the battle line and arrived at Shiʹloh on that day with his garments ripped apart and dirt on his head.

[[v9-4-13]]

^<<v9-4-13,13>>^ When the man arrived, Eʹli was sitting on the seat by the roadside watching, because his heart was trembling over the Ark of the true God. The man went into the city to report the news, and the whole city began crying out.

[[v9-4-14]]

^<<v9-4-14,14>>^ When Eʹli heard the sound of the outcry, he asked: “What does the sound of this turmoil mean?” The same man hurried in and reported the news to Eʹli.

[[v9-4-15]]

^<<v9-4-15,15>>^ (Now Eʹli was 98 years old, and his eyes stared straight ahead, and he could not see.)

[[v9-4-16]]

^<<v9-4-16,16>>^ Then the man said to Eʹli: “I am the one who came from the battle line! Just today I fled from the battle line.” At this he asked: “What happened, my son?”

[[v9-4-17]]

^<<v9-4-17,17>>^ So the bearer of the news related: “Israel has fled from the Phi·lisʹtines, and there was a great defeat among the people; also your own two sons, Hophʹni and Phinʹe·has, have died, and the Ark of the true God has been captured.”

[[v9-4-18]]

^<<v9-4-18,18>>^ At the moment he mentioned the Ark of the true God, Eʹli fell backward from his seat beside the gate, and his neck was broken and he died, for he was old and heavy. He had judged Israel for 40 years.

[[v9-4-19]]

^<<v9-4-19,19>>^ His daughter-in-law, the wife of Phinʹe·has, was pregnant and close to giving birth. When she heard the report that the Ark of the true God had been captured and that her father-in-law and her husband had died, she doubled over and unexpectedly went into labor and gave birth.

[[v9-4-20]]

^<<v9-4-20,20>>^ As she was dying, the women standing by her said: “Do not be afraid, for you have given birth to a son.” She did not answer and did not pay attention to it.^&#42;1^

[NOTE]
====
. Or “and did not set her heart on it.”
====

[[v9-4-21]]

^<<v9-4-21,21>>^ But she named the boy Ichʹa·bod,^&#42;1^ saying: “Glory has gone away from Israel into exile,” referring to the capture of the Ark of the true God and what happened to her father-in-law and her husband.

[NOTE]
====
. Meaning “Where Is the Glory?”
====

[[v9-4-22]]

^<<v9-4-22,22>>^ She said: “Glory has gone away from Israel into exile, because the Ark of the true God has been captured.”

'''

xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[&#60; Capítulo Anterior] | <<v9-4-0,Topo>> | xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[Próximo Capítulo &#62;]