include::./index.adoc[]

[[v9-6-0]]
=== The First of Samuel, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-6-1]]

^<<v9-6-1,1>>^ The Ark of Jehovah was in Phi·lisʹtine territory for seven months.

[[v9-6-2]]

^<<v9-6-2,2>>^ The Phi·lisʹtines called the priests and the diviners and asked: “What should we do with the Ark of Jehovah? Let us know how we should send it back to its place.”

[[v9-6-3]]

^<<v9-6-3,3>>^ They replied: “If you send the ark of the covenant of Jehovah the God of Israel away, do not send it back without an offering. You should by all means return to him a guilt offering. Only then will you be healed, and it will be made known to you why his hand has not turned away from you.”

[[v9-6-4]]

^<<v9-6-4,4>>^ So they asked: “What guilt offering should we send to him?” They said: “According to the number of the lords of the Phi·lisʹtines, send five golden piles^&#42;1^ and five golden mice, for the same scourge has afflicted every one of you and your lords.

[NOTE]
====
. Or “hemorrhoids.”
====

[[v9-6-5]]

^<<v9-6-5,5>>^ You should make images of your piles and images of your mice that are bringing the land to ruin, and you should honor the God of Israel. Perhaps he will lighten the weight of his hand that is on you and your god and your land.

[[v9-6-6]]

^<<v9-6-6,6>>^ Why should you harden your heart as Egypt and Pharʹaoh hardened their hearts? When He dealt harshly with them, they had to send Israel away, and they departed.

[[v9-6-7]]

^<<v9-6-7,7>>^ Now prepare a new wagon and two cows that have calves and have never been under a yoke. Then hitch the cows to the wagon, but take their calves back home, away from them.

[[v9-6-8]]

^<<v9-6-8,8>>^ Take the Ark of Jehovah and place it on the wagon, and put the golden articles that you are sending to him as a guilt offering in a box next to it. Then send it on its way

[[v9-6-9]]

^<<v9-6-9,9>>^ and watch: If it goes up the road to Beth-sheʹmesh, to its own territory, then he is the one who has done this great evil to us. But if not, we will know that it was not his hand that struck us; it happened to us by coincidence.”

[[v9-6-10]]

^<<v9-6-10,10>>^ The men did accordingly. They took two cows that had calves and hitched them to the wagon, and the calves they penned up at home.

[[v9-6-11]]

^<<v9-6-11,11>>^ Then they put the Ark of Jehovah on the wagon, as well as the box containing the golden mice and the images of their piles.

[[v9-6-12]]

^<<v9-6-12,12>>^ And the cows went straight ahead on the road to Beth-sheʹmesh. They stayed on the one highway, mooing as they went; they did not turn either to the right or to the left. All the while the lords of the Phi·lisʹtines were walking behind them as far as the boundary of Beth-sheʹmesh.

[[v9-6-13]]

^<<v9-6-13,13>>^ The people of Beth-sheʹmesh were reaping the wheat harvest in the valley plain.^&#42;1^ When they raised their eyes and saw the Ark, they were overjoyed at seeing it.

[NOTE]
====
. Or “low plain.”
====

[[v9-6-14]]

^<<v9-6-14,14>>^ The wagon came into the field of Joshua the Beth-sheʹmite and stopped there near a large stone. So they chopped up the wood of the wagon, and they offered the cows as a burnt offering to Jehovah.

[[v9-6-15]]

^<<v9-6-15,15>>^ The Levites took down the Ark of Jehovah and the box that was with it, which contained the golden articles, and they put them on the large stone. The men of Beth-sheʹmesh offered up burnt offerings and made sacrifices on that day to Jehovah.

[[v9-6-16]]

^<<v9-6-16,16>>^ When the five lords of the Phi·lisʹtines saw it, they returned to Ekʹron on that day.

[[v9-6-17]]

^<<v9-6-17,17>>^ Now these are the golden piles that the Phi·lisʹtines sent as a guilt offering to Jehovah: one for Ashʹdod, one for Gazʹa, one for Ashʹke·lon, one for Gath, one for Ekʹron.

[[v9-6-18]]

^<<v9-6-18,18>>^ And the number of the golden mice corresponded to the number of all the cities of the Phi·lisʹtines that belonged to the five lords—both the fortified cities and the villages in the open country.
And the large stone upon which they rested the Ark of Jehovah serves as a witness down to this day in the field of Joshua the Beth-sheʹmite.

[[v9-6-19]]

^<<v9-6-19,19>>^ But God struck down the men of Beth-sheʹmesh, because they had looked upon the Ark of Jehovah. He struck down 50,070^&#42;1^ among the people, and the people began mourning because Jehovah had struck them down with a great slaughter.

[NOTE]
====
. Lit., “70 men, 50,000 men.”
====

[[v9-6-20]]

^<<v9-6-20,20>>^ So the men of Beth-sheʹmesh asked: “Who will be able to stand before Jehovah, this holy God, and to whom will he go away from us?”

[[v9-6-21]]

^<<v9-6-21,21>>^ So they sent messengers to the inhabitants of Kirʹi·ath-jeʹa·rim, saying: “The Phi·lisʹtines have returned the Ark of Jehovah. Come down and take it up with you.”

'''

xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[&#60; Capítulo Anterior] | <<v9-6-0,Topo>> | xref:009-1-samuel/009-1-samuel-007.adoc#v9-7-0[Próximo Capítulo &#62;]