include::./index.adoc[]

[[v9-10-0]]
=== The First of Samuel, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-10-1]]

^<<v9-10-1,1>>^ Samuel then took the flask of oil and poured it out on Saul’s head. He kissed him and said: “Has not Jehovah anointed you as a leader over his inheritance?

[[v9-10-2]]

^<<v9-10-2,2>>^ When you leave me today, you will find two men near the tomb of Rachel in the territory of Benjamin at Zelʹzah, and they will say to you, ‘The donkeys that you went to look for have been found, but now your father has forgotten about the donkeys and is worried about you. He is saying: “What should I do about my son?”’

[[v9-10-3]]

^<<v9-10-3,3>>^ Go on from there until you come to the big tree of Taʹbor, where you will meet three men going up to the true God at Bethʹel, one carrying three young goats, one carrying three loaves of bread, and one carrying a large jar of wine.

[[v9-10-4]]

^<<v9-10-4,4>>^ They will ask about your welfare and give you two loaves, and you must accept the loaves from them.

[[v9-10-5]]

^<<v9-10-5,5>>^ After that you will come to the hill of the true God, where there is a garrison of the Phi·lisʹtines. When you come to the city, you will meet a group of prophets coming down from the high place, and a stringed instrument and tambourine and flute and harp will be played ahead of them while they are prophesying.

[[v9-10-6]]

^<<v9-10-6,6>>^ The spirit of Jehovah will empower you, and you will prophesy along with them and be changed into a different person.

[[v9-10-7]]

^<<v9-10-7,7>>^ When these signs have taken place, do whatever your hand finds possible, because the true God is with you.

[[v9-10-8]]

^<<v9-10-8,8>>^ Then go down ahead of me to Gilʹgal, and I will go down to you there to offer up burnt sacrifices and communion sacrifices. You should wait for seven days until I come to you. Then I will let you know what you should do.”

[[v9-10-9]]

^<<v9-10-9,9>>^ As soon as Saul turned around to leave Samuel, God began changing his heart to be like that of someone else, and all these signs came true on that day.

[[v9-10-10]]

^<<v9-10-10,10>>^ So they went from there to the hill, and a group of prophets met him. At once the spirit of God empowered him, and he began to prophesy among them.

[[v9-10-11]]

^<<v9-10-11,11>>^ When all those who previously knew him saw him prophesying with the prophets, they said to one another: “What has happened to the son of Kish? Is Saul also among the prophets?”

[[v9-10-12]]

^<<v9-10-12,12>>^ Then a man from there said: “But who is their father?” So it became a saying:^&#42;1^ “Is Saul also among the prophets?”

[NOTE]
====
. Or “a proverb.”
====

[[v9-10-13]]

^<<v9-10-13,13>>^ When he finished prophesying, he came to the high place.

[[v9-10-14]]

^<<v9-10-14,14>>^ The brother of Saul’s father later said to him and to his attendant: “Where did you go?” At that he said: “To look for the donkeys, but we saw that they were not there, so we went to Samuel.”

[[v9-10-15]]

^<<v9-10-15,15>>^ Saul’s uncle asked: “Please tell me, what did Samuel say to you?”

[[v9-10-16]]

^<<v9-10-16,16>>^ Saul replied to his uncle: “He told us that the donkeys had already been found.” But Saul did not tell him what Samuel said about the matter of the kingship.

[[v9-10-17]]

^<<v9-10-17,17>>^ Samuel then called the people together to Jehovah at Mizʹpah

[[v9-10-18]]

^<<v9-10-18,18>>^ and said to the Israelites: “This is what Jehovah the God of Israel says: ‘It was I who brought Israel up out of Egypt and who rescued you from the hand of Egypt and from the hand of all the kingdoms that were oppressing you.

[[v9-10-19]]

^<<v9-10-19,19>>^ But today you have rejected your God who was your Savior out of all your evils and distresses, and you said: “No, you should appoint a king over us.” Now take your stand before Jehovah by your tribes and by your thousands.’”^&#42;1^

[NOTE]
====
. Or “clans.”
====

[[v9-10-20]]

^<<v9-10-20,20>>^ So Samuel had all the tribes of Israel draw near, and the tribe of Benjamin was selected.

[[v9-10-21]]

^<<v9-10-21,21>>^ Then he had the tribe of Benjamin draw near by its families, and the family of the Matʹrites was selected. Finally Saul the son of Kish was selected. But when they went to look for him, he was nowhere to be found.

[[v9-10-22]]

^<<v9-10-22,22>>^ So they inquired of Jehovah: “Has the man come here yet?” Jehovah answered: “There he is hiding himself among the luggage.”

[[v9-10-23]]

^<<v9-10-23,23>>^ So they ran and brought him from there. When he stood in the middle of the people, he was head and shoulders taller than all the other people.

[[v9-10-24]]

^<<v9-10-24,24>>^ Samuel said to all the people: “Do you see the one whom Jehovah has chosen, that there is none like him among all the people?” And all the people began to shout: “Long live the king!”

[[v9-10-25]]

^<<v9-10-25,25>>^ Samuel spoke to the people about the rightful due of kings and wrote it in a book and deposited it before Jehovah. Then Samuel sent all the people away, everyone to his house.

[[v9-10-26]]

^<<v9-10-26,26>>^ Saul also went to his home in Gibʹe·ah, accompanied by the warriors whose hearts Jehovah had touched.

[[v9-10-27]]

^<<v9-10-27,27>>^ But some worthless men said: “How will this one save us?” So they despised him, and they did not bring any gift to him. But he said nothing about it.^&#42;1^

[NOTE]
====
. Lit., “And he was like someone speechless.”
====

'''

xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[&#60; Capítulo Anterior] | <<v9-10-0,Topo>> | xref:009-1-samuel/009-1-samuel-011.adoc#v9-11-0[Próximo Capítulo &#62;]