include::./index.adoc[]

[[v9-8-0]]
=== The First of Samuel, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-8-1]]

^<<v9-8-1,1>>^ When Samuel had grown old, he appointed his sons as judges for Israel.

[[v9-8-2]]

^<<v9-8-2,2>>^ The name of his firstborn son was Joel, and the name of his second, A·biʹjah; they were judges in Beʹer-sheʹba.

[[v9-8-3]]

^<<v9-8-3,3>>^ But his sons did not walk in his ways; they were inclined to pursue dishonest profit, they accepted bribes, and they perverted justice.

[[v9-8-4]]

^<<v9-8-4,4>>^ In time all the elders of Israel gathered together and came to Samuel at Raʹmah.

[[v9-8-5]]

^<<v9-8-5,5>>^ They said to him: “Look! You have grown old, but your sons are not walking in your ways. Now appoint for us a king to judge us like all the other nations.”

[[v9-8-6]]

^<<v9-8-6,6>>^ But it displeased^&#42;1^ Samuel when they said: “Give us a king to judge us.” Then Samuel prayed to Jehovah,

[NOTE]
====
. Lit., “was bad in the eyes of.”
====

[[v9-8-7]]

^<<v9-8-7,7>>^ and Jehovah said to Samuel: “Listen to everything the people say to you; for it is not you whom they have rejected, but it is I whom they have rejected as their king.

[[v9-8-8]]

^<<v9-8-8,8>>^ They are doing just as they have done from the day I brought them up out of Egypt until this day; they keep forsaking me and serving other gods, and that is what they are doing to you.

[[v9-8-9]]

^<<v9-8-9,9>>^ Now listen to them. However, you should solemnly warn them; tell them what the king who rules over them will have the right to demand.”

[[v9-8-10]]

^<<v9-8-10,10>>^ So Samuel told the people who were asking him for a king all the words of Jehovah.

[[v9-8-11]]

^<<v9-8-11,11>>^ He said: “This is what the king who rules over you will have the right to demand: He will take your sons and put them in his chariots and make them his horsemen, and some will have to run before his chariots.

[[v9-8-12]]

^<<v9-8-12,12>>^ And he will appoint for himself chiefs over thousands and chiefs over fifties, and some will do his plowing, reap his harvest, and make his weapons of war and equipment for his chariots.

[[v9-8-13]]

^<<v9-8-13,13>>^ He will take your daughters to be ointment mixers,^&#42;1^ cooks, and bakers.

[NOTE]
====
. Or “perfume makers.”
====

[[v9-8-14]]

^<<v9-8-14,14>>^ He will take the best of your fields, your vineyards, and your olive groves, and he will give them to his servants.

[[v9-8-15]]

^<<v9-8-15,15>>^ He will take the tenth of your grainfields and your vineyards, and he will give it to his court officials and his servants.

[[v9-8-16]]

^<<v9-8-16,16>>^ And he will take your male and female servants, your best herds, and your donkeys, and he will use them for his work.

[[v9-8-17]]

^<<v9-8-17,17>>^ He will take the tenth of your flocks, and you will become his servants.

[[v9-8-18]]

^<<v9-8-18,18>>^ The day will come when you will cry out because of the king you have chosen for yourselves, but Jehovah will not answer you in that day.”

[[v9-8-19]]

^<<v9-8-19,19>>^ However, the people refused to listen to what Samuel told them, and they said: “No, we are determined to have a king over us.

[[v9-8-20]]

^<<v9-8-20,20>>^ Then we will be like all the other nations, and our king will judge us and lead us and fight our battles.”

[[v9-8-21]]

^<<v9-8-21,21>>^ After Samuel heard all the words of the people, he repeated them in the hearing of Jehovah.

[[v9-8-22]]

^<<v9-8-22,22>>^ Jehovah said to Samuel: “Listen to them, and appoint a king to reign over them.” Samuel then said to the men of Israel: “Each of you should return to his city.”

'''

xref:009-1-samuel/009-1-samuel-007.adoc#v9-7-0[&#60; Capítulo Anterior] | <<v9-8-0,Topo>> | xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[Próximo Capítulo &#62;]