include::./index.adoc[]

[[v9-5-0]]
=== The First of Samuel, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-5-1]]

^<<v9-5-1,1>>^ When the Phi·lisʹtines captured the Ark of the true God, they brought it from Eb·en·eʹzer to Ashʹdod.

[[v9-5-2]]

^<<v9-5-2,2>>^ The Phi·lisʹtines took the Ark of the true God and brought it into the house^&#42;1^ of Daʹgon and set it beside Daʹgon.

[NOTE]
====
. Or “temple.”
====

[[v9-5-3]]

^<<v9-5-3,3>>^ When the Ashʹdod·ites got up early the next day, there was Daʹgon fallen facedown on the ground before the Ark of Jehovah. So they took Daʹgon and returned him to his place.

[[v9-5-4]]

^<<v9-5-4,4>>^ When they got up early in the morning on the following day, there was Daʹgon fallen facedown on the ground before the Ark of Jehovah. The head of Daʹgon and the palms of both his hands were cut off and were lying on the threshold. Only the fish part^&#42;1^ had been left intact.

[NOTE]
====
. Lit., “Only Dagon.”
====

[[v9-5-5]]

^<<v9-5-5,5>>^ That is why to this day, the priests of Daʹgon and all those who enter the house of Daʹgon do not walk on the threshold of Daʹgon in Ashʹdod.

[[v9-5-6]]

^<<v9-5-6,6>>^ The hand of Jehovah was heavy against the Ashʹdod·ites, and he devastated them by striking Ashʹdod and its territories with piles.^&#42;1^

[NOTE]
====
. Or “hemorrhoids.”
====

[[v9-5-7]]

^<<v9-5-7,7>>^ When the men of Ashʹdod saw what was happening, they said: “Do not let the Ark of the God of Israel remain with us, for his hand has dealt harshly with us and our god Daʹgon.”

[[v9-5-8]]

^<<v9-5-8,8>>^ So they sent for and gathered all the lords of the Phi·lisʹtines and asked them: “What should we do with the Ark of the God of Israel?” They replied: “Let the Ark of the God of Israel be moved to Gath.” So they moved the Ark of the God of Israel there.

[[v9-5-9]]

^<<v9-5-9,9>>^ After they moved it there, the hand of Jehovah came against the city, bringing great panic. He struck the men of the city, from small to great, and piles broke out on them.

[[v9-5-10]]

^<<v9-5-10,10>>^ So they sent the Ark of the true God to Ekʹron, but as soon as the Ark of the true God came to Ekʹron, the Ekʹron·ites began to cry out: “They have brought the Ark of the God of Israel to us to put us and our people to death!”

[[v9-5-11]]

^<<v9-5-11,11>>^ Then they sent for and gathered all the lords of the Phi·lisʹtines and said: “Send the Ark of the God of Israel away; let it return to its place so that we and our people may not be put to death.” For the terror of death had spread through the whole city; the hand of the true God had been very heavy there,

[[v9-5-12]]

^<<v9-5-12,12>>^ and the men who did not die had been struck with piles. And the city’s cry for help ascended to the heavens.

'''

xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[&#60; Capítulo Anterior] | <<v9-5-0,Topo>> | xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[Próximo Capítulo &#62;]