include::./index.adoc[]

[[v9-13-0]]
=== The First of Samuel, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-13-1]]

^<<v9-13-1,1>>^ Saul was . . .^&#42;1^ years old when he became king, and for two years he reigned over Israel.

[NOTE]
====
. The number is missing in the Hebrew text.
====

[[v9-13-2]]

^<<v9-13-2,2>>^ Saul chose 3,000 men out of Israel; 2,000 of these were with Saul at Michʹmash and in the mountainous region of Bethʹel and 1,000 were with Jonʹa·than at Gibʹe·ah of Benjamin. He sent the rest of the people away, each one to his tent.

[[v9-13-3]]

^<<v9-13-3,3>>^ Then Jonʹa·than struck down the garrison of the Phi·lisʹtines that was in Geʹba, and the Phi·lisʹtines heard about it. And Saul had the horn blown throughout all the land, saying: “Let the Hebrews hear!”

[[v9-13-4]]

^<<v9-13-4,4>>^ All Israel heard the news: “Saul has struck down a garrison of the Phi·lisʹtines, and now Israel has become a stench among the Phi·lisʹtines.” So the people were summoned to follow Saul at Gilʹgal.

[[v9-13-5]]

^<<v9-13-5,5>>^ The Phi·lisʹtines also gathered together to fight against Israel, with 30,000 war chariots and 6,000 horsemen and troops as numerous as the grains of sand on the seashore; and they went up and camped in Michʹmash to the east of Beth-aʹven.

[[v9-13-6]]

^<<v9-13-6,6>>^ And the men of Israel saw that they were in trouble, because they were hard-pressed; so the people hid in the caves, the hollows, the crags, the cellars,^&#42;1^ and the cisterns.

[NOTE]
====
. Or “vaults.”
====

[[v9-13-7]]

^<<v9-13-7,7>>^ Some of the Hebrews even crossed the Jordan to the land of Gad and Gilʹe·ad. But Saul was still in Gilʹgal, and all the people following him were trembling.

[[v9-13-8]]

^<<v9-13-8,8>>^ He continued waiting for seven days until the designated^&#42;1^ time that Samuel had set, but Samuel did not come to Gilʹgal, and the people were scattering from him.

[NOTE]
====
. Or “appointed.”
====

[[v9-13-9]]

^<<v9-13-9,9>>^ Finally Saul said: “Bring to me the burnt sacrifice and the communion sacrifices.” And he offered up the burnt sacrifice.

[[v9-13-10]]

^<<v9-13-10,10>>^ But as soon as he had finished offering up the burnt sacrifice, Samuel arrived. So Saul went out to meet him and bless him.

[[v9-13-11]]

^<<v9-13-11,11>>^ Then Samuel said: “What have you done?” Saul replied: “I saw that the people were deserting me, and you did not come within the designated time, and the Phi·lisʹtines were gathering together at Michʹmash.

[[v9-13-12]]

^<<v9-13-12,12>>^ So I said to myself, ‘Now the Phi·lisʹtines will come down against me at Gilʹgal, and I have not sought the favor^&#42;1^ of Jehovah.’ So I felt obligated to offer up the burnt sacrifice.”

[NOTE]
====
. Or “softened the face.”
====

[[v9-13-13]]

^<<v9-13-13,13>>^ At this Samuel said to Saul: “You have acted foolishly. You have not obeyed the commandment that Jehovah your God gave you. If you had, Jehovah would have made your kingdom firm over Israel forever.

[[v9-13-14]]

^<<v9-13-14,14>>^ But now your kingdom will not last. Jehovah will find a man agreeable to his heart, and Jehovah will commission him as a leader over his people, because you did not obey what Jehovah commanded you.”

[[v9-13-15]]

^<<v9-13-15,15>>^ Then Samuel rose and went his way up from Gilʹgal to Gibʹe·ah of Benjamin, and Saul took the count of the people; those still with him were about 600 men.

[[v9-13-16]]

^<<v9-13-16,16>>^ Saul, his son Jonʹa·than, and the people still with them were dwelling in Geʹba of Benjamin, and the Phi·lisʹtines had encamped at Michʹmash.

[[v9-13-17]]

^<<v9-13-17,17>>^ And the raiding parties would go out from the camp of the Phi·lisʹtines in three bands. One band would turn toward the road to Ophʹrah, to the land of Shuʹal;

[[v9-13-18]]

^<<v9-13-18,18>>^ another band would turn toward the road of Beth-hoʹron; and the third band would turn toward the road leading to the boundary that overlooks the valley of Ze·boʹim, toward the wilderness.

[[v9-13-19]]

^<<v9-13-19,19>>^ Now there was not a metalworker to be found in all the land of Israel, because the Phi·lisʹtines had said: “So that the Hebrews may not make a sword or a spear.”

[[v9-13-20]]

^<<v9-13-20,20>>^ And all the Israelites had to go down to the Phi·lisʹtines to get their plowshares, mattocks, axes, or sickles sharpened.

[[v9-13-21]]

^<<v9-13-21,21>>^ The price for sharpening was a pim^&#42;1^ for the plowshares, for the mattocks, for the three-toothed instruments, for the axes, and for fixing fast the oxgoad.

[NOTE]
====
. An ancient weight, approximately two thirds of a shekel.
====

[[v9-13-22]]

^<<v9-13-22,22>>^ And on the day of battle, not a sword or a spear was found in the hand of any of the people who were with Saul and Jonʹa·than; only Saul and his son Jonʹa·than had weapons.

[[v9-13-23]]

^<<v9-13-23,23>>^ Now a garrison^&#42;1^ of the Phi·lisʹtines had gone out to the ravine pass of Michʹmash.

[NOTE]
====
. Or “an outpost.”
====

'''

xref:009-1-samuel/009-1-samuel-012.adoc#v9-12-0[&#60; Capítulo Anterior] | <<v9-13-0,Topo>> | xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[Próximo Capítulo &#62;]