include::./index.adoc[]

[[v9-22-0]]
=== The First of Samuel, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-22-1]]

^<<v9-22-1,1>>^ So David went from there, escaping to the cave of A·dulʹlam. When his brothers and his father’s entire house heard of it, they went down there to him.

[[v9-22-2]]

^<<v9-22-2,2>>^ And all those who were in trouble and in debt and who had a grievance^&#42;1^ gathered to him, and he became their chief. There were about 400 men with him.

[NOTE]
====
. Or “were bitter of soul.”
====

[[v9-22-3]]

^<<v9-22-3,3>>^ David later went from there to Mizʹpeh in Moʹab and said to the king of Moʹab: “Please let my father and mother stay with you until I know what God will do for me.”

[[v9-22-4]]

^<<v9-22-4,4>>^ So he left them with the king of Moʹab, and they stayed with him the whole time that David was in the stronghold.

[[v9-22-5]]

^<<v9-22-5,5>>^ In time Gad the prophet said to David: “Do not stay in the stronghold. Go from there into the land of Judah.” So David left and went into the forest of Heʹreth.

[[v9-22-6]]

^<<v9-22-6,6>>^ Saul heard that David and the men with him had been found. Saul was then sitting in Gibʹe·ah under the tamarisk tree on the high place with his spear in his hand, and all his servants were stationed around him.

[[v9-22-7]]

^<<v9-22-7,7>>^ Then Saul said to his servants stationed around him: “Listen, please, you Benʹja·min·ites. Will the son of Jesʹse also give fields and vineyards to all of you? Will he appoint all of you as chiefs of thousands and chiefs of hundreds?

[[v9-22-8]]

^<<v9-22-8,8>>^ All of you have conspired against me! No one informed me when my own son made a covenant with the son of Jesʹse! Not one of you has sympathy for me and informs me that my own son has incited my own servant against me to ambush me, as is now the case.”

[[v9-22-9]]

^<<v9-22-9,9>>^ Then Doʹeg the Eʹdom·ite, who was stationed there over the servants of Saul, answered: “I saw the son of Jesʹse come to Nob to A·himʹe·lech the son of A·hiʹtub.

[[v9-22-10]]

^<<v9-22-10,10>>^ And he inquired of Jehovah for him and gave him provisions. He even gave him the sword of Go·liʹath the Phi·lisʹtine.”

[[v9-22-11]]

^<<v9-22-11,11>>^ At once the king sent for A·himʹe·lech son of A·hiʹtub the priest and all the priests of his father’s house, who were in Nob. So all of them came to the king.

[[v9-22-12]]

^<<v9-22-12,12>>^ Saul now said: “Listen, please, you son of A·hiʹtub!” to which he replied: “Here I am, my lord.”

[[v9-22-13]]

^<<v9-22-13,13>>^ Saul said to him: “Why have you conspired against me, you and the son of Jesʹse, by giving him bread and a sword and by making an inquiry of God for him? He opposes me and waits in ambush, as is now the case.”

[[v9-22-14]]

^<<v9-22-14,14>>^ At this A·himʹe·lech answered the king: “Who among all your servants is as trustworthy^&#42;1^ as David? He is the king’s son-in-law and a chief over your bodyguard and honored in your house.

[NOTE]
====
. Or “faithful.”
====

[[v9-22-15]]

^<<v9-22-15,15>>^ Was today the first time I inquired of God for him? What you are saying is unthinkable on my part! Do not let the king hold anything against his servant and against my father’s entire house, for your servant did not know a single thing about any of this.”

[[v9-22-16]]

^<<v9-22-16,16>>^ But the king said: “You will surely die, A·himʹe·lech, you along with all your father’s house.”

[[v9-22-17]]

^<<v9-22-17,17>>^ With that the king said to the guards^&#42;1^ stationed around him: “Turn and kill the priests of Jehovah, because they have sided with David! They knew that he was a runaway, and they did not inform me!” But the king’s servants did not want to lift their hands to assault the priests of Jehovah.

[NOTE]
====
. Lit., “runners.”
====

[[v9-22-18]]

^<<v9-22-18,18>>^ Then the king said to Doʹeg: “You turn and assault the priests!” Immediately Doʹeg the Eʹdom·ite went and assaulted the priests himself. He killed on that day 85 men wearing the linen ephʹod.

[[v9-22-19]]

^<<v9-22-19,19>>^ He also struck Nob, the city of the priests, with the sword; man as well as woman, child as well as infant, bull, donkey, and sheep, he put to the sword.

[[v9-22-20]]

^<<v9-22-20,20>>^ However, one son of A·himʹe·lech the son of A·hiʹtub, whose name was A·biʹa·thar, escaped and ran away to follow David.

[[v9-22-21]]

^<<v9-22-21,21>>^ A·biʹa·thar told David: “Saul has killed the priests of Jehovah.”

[[v9-22-22]]

^<<v9-22-22,22>>^ At this David said to A·biʹa·thar: “I knew on that day, when Doʹeg the Eʹdom·ite was there, that he would be sure to tell Saul. I am personally responsible for the death of everyone^&#42;1^ in your father’s house.

[NOTE]
====
. Or “every soul.”
====

[[v9-22-23]]

^<<v9-22-23,23>>^ Stay with me. Do not be afraid, for whoever seeks your life^&#42;1^ seeks my life;^&#42;2^ you are under my protection.”

[NOTE]
====
. Or “soul.”
. Or “soul.”
====

'''

xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[&#60; Capítulo Anterior] | <<v9-22-0,Topo>> | xref:009-1-samuel/009-1-samuel-023.adoc#v9-23-0[Próximo Capítulo &#62;]