include::./index.adoc[]

[[v9-11-0]]
=== The First of Samuel, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-11-1]]

^<<v9-11-1,1>>^ Then Naʹhash the Amʹmon·ite came up and camped against Jaʹbesh in Gilʹe·ad. All the men of Jaʹbesh said to Naʹhash: “Make a covenant^&#42;1^ with us, and we will serve you.”

[NOTE]
====
. Or “an agreement.”
====

[[v9-11-2]]

^<<v9-11-2,2>>^ Naʹhash the Amʹmon·ite said to them: “I will make it with you on this condition: that all your right eyes be bored out. I will do this to humiliate all Israel.”

[[v9-11-3]]

^<<v9-11-3,3>>^ The elders of Jaʹbesh replied to him: “Give us seven days’ time so that we can send messengers into all the territory of Israel. Then, if there is no one to rescue us, we will surrender to you.”

[[v9-11-4]]

^<<v9-11-4,4>>^ In time the messengers came to Gibʹe·ah of Saul and spoke these words in the hearing of the people, and all the people wept at the top of their voice.

[[v9-11-5]]

^<<v9-11-5,5>>^ But Saul was coming from the field behind the herd, and Saul said: “What is the matter with the people? Why are they weeping?” So they related to him the words of the men of Jaʹbesh.

[[v9-11-6]]

^<<v9-11-6,6>>^ The spirit of God empowered Saul when he heard these words, and he burned with anger.

[[v9-11-7]]

^<<v9-11-7,7>>^ So he took a pair of bulls and cut them into pieces, and he sent these into all the territory of Israel by the hand of the messengers, who said: “Whoever does not follow Saul and Samuel should expect this to be done to his cattle!” And the fear of Jehovah fell upon the people, so that they came out with one accord.^&#42;1^

[NOTE]
====
. Lit., “as one man.”
====

[[v9-11-8]]

^<<v9-11-8,8>>^ Then he counted them in Beʹzek, and there were 300,000 Israelites and 30,000 men of Judah.

[[v9-11-9]]

^<<v9-11-9,9>>^ They now said to the messengers who had come: “This is what you should say to the men of Jaʹbesh in Gilʹe·ad, ‘Tomorrow when the sun gets hot, you will be saved.’” With that the messengers came and told the men of Jaʹbesh, and they were overjoyed.

[[v9-11-10]]

^<<v9-11-10,10>>^ So the men of Jaʹbesh said: “Tomorrow we will surrender to you, and you may do to us whatever seems good to you.”

[[v9-11-11]]

^<<v9-11-11,11>>^ On the next day, Saul divided the people into three bands, and they made their way into the middle of the camp during the morning watch^&#42;1^ and struck down the Amʹmon·ites until the day grew hot. Those who survived were scattered, so that no two of them were left together.

[NOTE]
====
. That is, about 2:00 a.m. until 6:00 a.m.
====

[[v9-11-12]]

^<<v9-11-12,12>>^ Then the people said to Samuel: “Who was saying, ‘Is Saul to be king over us?’ Hand the men over, and we will put them to death.”

[[v9-11-13]]

^<<v9-11-13,13>>^ However, Saul said: “Not a man should be put to death on this day, for today Jehovah has rescued Israel.”

[[v9-11-14]]

^<<v9-11-14,14>>^ Samuel later said to the people: “Come and let us go to Gilʹgal to reconfirm the kingship.”

[[v9-11-15]]

^<<v9-11-15,15>>^ So all the people went to Gilʹgal, and in Gilʹgal they made Saul king before Jehovah. Then they offered communion sacrifices there before Jehovah, and Saul and all the men of Israel celebrated with great joy.

'''

xref:009-1-samuel/009-1-samuel-010.adoc#v9-10-0[&#60; Capítulo Anterior] | <<v9-11-0,Topo>> | xref:009-1-samuel/009-1-samuel-012.adoc#v9-12-0[Próximo Capítulo &#62;]