include::./index.adoc[]

[[v9-17-0]]
=== The First of Samuel, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-17-1]]

^<<v9-17-1,1>>^ And the Phi·lisʹtines assembled their armies^&#42;1^ for war. They assembled at Soʹcoh, which belongs to Judah, and they camped between Soʹcoh and A·zeʹkah, in Eʹphes-damʹmim.

[NOTE]
====
. Lit., “camps.”
====

[[v9-17-2]]

^<<v9-17-2,2>>^ Saul and the men of Israel assembled and camped in the Valley^&#42;1^ of Eʹlah, and they drew up in battle formation to meet the Phi·lisʹtines.

[NOTE]
====
. Or “Low Plain.”
====

[[v9-17-3]]

^<<v9-17-3,3>>^ The Phi·lisʹtines occupied the mountain on one side, and the Israelites occupied the mountain on the other side, with the valley between them.

[[v9-17-4]]

^<<v9-17-4,4>>^ Then a champion came out from the camps of the Phi·lisʹtines; his name was Go·liʹath, from Gath, and his height was six cubits and a span.^&#42;1^

[NOTE]
====
. His height was about 2.9 m (9 ft 5.75 in.). See App. B14.
====

[[v9-17-5]]

^<<v9-17-5,5>>^ He had a helmet of copper on his head, and he was wearing a coat of mail of overlapping scales. The weight of the copper coat of mail was 5,000 shekels.^&#42;1^

[NOTE]
====
. About 57 kg (125 lb). See App. B14.
====

[[v9-17-6]]

^<<v9-17-6,6>>^ He had shin guards of copper on his legs and a javelin of copper slung between his shoulders.

[[v9-17-7]]

^<<v9-17-7,7>>^ The wooden shaft of his spear was like the beam of loom workers, and the iron blade of his spear weighed 600 shekels;^&#42;1^ and his shield-bearer was marching ahead of him.

[NOTE]
====
. About 6.84 kg (15 lb). See App. B14.
====

[[v9-17-8]]

^<<v9-17-8,8>>^ Then he stood and called out to the battle line of Israel and said to them: “Why have you come out to draw up in battle formation? Am I not the Phi·lisʹtine, and are you not the servants of Saul? Choose a man for yourselves, and let him come down to me.

[[v9-17-9]]

^<<v9-17-9,9>>^ If he is able to fight with me and strike me down, we will then become your servants. But if I prevail against him and strike him down, you will become our servants and serve us.”

[[v9-17-10]]

^<<v9-17-10,10>>^ The Phi·lisʹtine then said: “I do taunt^&#42;1^ the battle line of Israel this day. Give me a man, and let us fight it out!”

[NOTE]
====
. Or “challenge.”
====

[[v9-17-11]]

^<<v9-17-11,11>>^ When Saul and all Israel heard these words of the Phi·lisʹtine, they became terrified and greatly afraid.

[[v9-17-12]]

^<<v9-17-12,12>>^ Now David was the son of the Ephʹrath·ite from Bethʹle·hem of Judah named Jesʹse, who had eight sons and who in the days of Saul was already an old man.

[[v9-17-13]]

^<<v9-17-13,13>>^ The three oldest sons of Jesʹse had followed Saul to the war. The names of his three sons who went to war were E·liʹab the firstborn, his second son A·binʹa·dab, and the third Shamʹmah.

[[v9-17-14]]

^<<v9-17-14,14>>^ David was the youngest, and the three oldest followed Saul.

[[v9-17-15]]

^<<v9-17-15,15>>^ David was going back and forth from Saul to tend the sheep of his father at Bethʹle·hem.

[[v9-17-16]]

^<<v9-17-16,16>>^ Meanwhile, the Phi·lisʹtine would come forward and take his position each morning and each evening for 40 days.

[[v9-17-17]]

^<<v9-17-17,17>>^ Then Jesʹse said to his son David: “Take, please, this eʹphah^&#42;1^ of roasted grain and these ten loaves of bread, and carry them quickly to your brothers in the camp.

[NOTE]
====
. About 22 L (20 dry qt). See App. B14.
====

[[v9-17-18]]

^<<v9-17-18,18>>^ And take these ten portions of cheese^&#42;1^ to the chief of the thousand; also, you should check on the welfare of your brothers and bring back some token from them.”

[NOTE]
====
. Lit., “milk.”
====

[[v9-17-19]]

^<<v9-17-19,19>>^ They were with Saul and all the other men of Israel in the Valley^&#42;1^ of Eʹlah, fighting against the Phi·lisʹtines.

[NOTE]
====
. Or “Low Plain.”
====

[[v9-17-20]]

^<<v9-17-20,20>>^ So David got up early in the morning and left someone in charge of the sheep; then he packed up and went just as Jesʹse had commanded him. When he came to the camp enclosure, the army was going out to the battle line, shouting a battle cry.

[[v9-17-21]]

^<<v9-17-21,21>>^ Israel and the Phi·lisʹtines drew up so that one battle line faced the other battle line.

[[v9-17-22]]

^<<v9-17-22,22>>^ David immediately left his baggage in the care of the baggage keeper and ran to the battle line. When he arrived, he began asking about the welfare of his brothers.

[[v9-17-23]]

^<<v9-17-23,23>>^ While he was speaking with them, there came the champion named Go·liʹath, the Phi·lisʹtine from Gath. He came out from the battle line of the Phi·lisʹtines, and he spoke the same words as before, and David heard him.

[[v9-17-24]]

^<<v9-17-24,24>>^ When all the men of Israel saw the man, they fled from him, terrified.

[[v9-17-25]]

^<<v9-17-25,25>>^ The men of Israel were saying: “Have you seen this man who is coming out? He comes to taunt^&#42;1^ Israel. The king will give great riches to the man who strikes him down, he will give him his own daughter, and he will give the house of his father exemption in Israel.”

[NOTE]
====
. Or “challenge.”
====

[[v9-17-26]]

^<<v9-17-26,26>>^ David began to say to the men who were standing near him: “What will be done for the man who strikes down that Phi·lisʹtine over there and takes away reproach from Israel? For who is this uncircumcised Phi·lisʹtine that he should taunt^&#42;1^ the battle line of the living God?”

[NOTE]
====
. Or “challenge.”
====

[[v9-17-27]]

^<<v9-17-27,27>>^ Then the people told him the same thing as before: “This is what will be done for the man who strikes him down.”

[[v9-17-28]]

^<<v9-17-28,28>>^ When his oldest brother E·liʹab heard him speak to the men, he became angry with David and said: “Why have you come down? And with whom did you leave those few sheep in the wilderness? I well know your presumptuousness and the bad intentions of your heart; you came down just to see the battle.”

[[v9-17-29]]

^<<v9-17-29,29>>^ To this David said: “What have I done now? I was only asking a question!”

[[v9-17-30]]

^<<v9-17-30,30>>^ So he turned from him toward someone else and asked the same thing as before, and the people gave him the same reply as before.

[[v9-17-31]]

^<<v9-17-31,31>>^ The words that David had spoken were overheard and reported to Saul. So he sent for him.

[[v9-17-32]]

^<<v9-17-32,32>>^ David said to Saul: “Let no one lose heart^&#42;1^ because of him. Your servant will go and fight with this Phi·lisʹtine.”

[NOTE]
====
. Or “courage.”
====

[[v9-17-33]]

^<<v9-17-33,33>>^ But Saul said to David: “You are not able to go fight against this Phi·lisʹtine, for you are but a boy, and he has been a soldier^&#42;1^ from his youth.”

[NOTE]
====
. Or “a man of war.”
====

[[v9-17-34]]

^<<v9-17-34,34>>^ David then said to Saul: “Your servant became a shepherd of his father’s flock, and a lion came, also a bear, and each carried off a sheep from the flock.

[[v9-17-35]]

^<<v9-17-35,35>>^ I went out after it and struck it down and rescued it from its mouth. When it rose up against me, I grabbed it by its fur^&#42;1^ and struck it down and put it to death.

[NOTE]
====
. Or “by the jaw.” Lit., “by its beard.”
====

[[v9-17-36]]

^<<v9-17-36,36>>^ Your servant struck down both the lion and the bear, and this uncircumcised Phi·lisʹtine will become like one of them, for he has taunted^&#42;1^ the battle lines of the living God.”

[NOTE]
====
. Or “challenged.”
====

[[v9-17-37]]

^<<v9-17-37,37>>^ Then David added: “Jehovah, who rescued me from the claws of the lion and the bear, he is the one who will rescue me from the hand of this Phi·lisʹtine.” At this Saul said to David: “Go, and may Jehovah be with you.”

[[v9-17-38]]

^<<v9-17-38,38>>^ Saul now clothed David with his garments. He put a copper helmet on his head, after which he clothed him with a coat of mail.

[[v9-17-39]]

^<<v9-17-39,39>>^ Then David strapped on his sword over his garments and tried to go but could not, for he was not used to them. David said to Saul: “I am unable to go in these things, for I am not used to them.” So David took them off.

[[v9-17-40]]

^<<v9-17-40,40>>^ He then took his staff in his hand and chose five smooth stones from the streambed^&#42;1^ and placed them in the pouch of his shepherd’s bag, and his sling was in his hand. And he began approaching the Phi·lisʹtine.

[NOTE]
====
. Or “wadi.”
====

[[v9-17-41]]

^<<v9-17-41,41>>^ The Phi·lisʹtine came closer and closer to David, and his shield-bearer was ahead of him.

[[v9-17-42]]

^<<v9-17-42,42>>^ When the Phi·lisʹtine looked and saw David, he sneered at him in contempt because he was just a ruddy and handsome boy.

[[v9-17-43]]

^<<v9-17-43,43>>^ So the Phi·lisʹtine said to David: “Am I a dog, so that you are coming against me with sticks?” With that the Phi·lisʹtine cursed David by his gods.

[[v9-17-44]]

^<<v9-17-44,44>>^ The Phi·lisʹtine said to David: “Just come to me, and I will give your flesh to the birds of the heavens and to the beasts of the field.”

[[v9-17-45]]

^<<v9-17-45,45>>^ David replied to the Phi·lisʹtine: “You are coming against me with sword and spear and javelin, but I am coming against you in the name of Jehovah of armies, the God of the battle line of Israel, whom you have taunted.^&#42;1^

[NOTE]
====
. Or “challenged.”
====

[[v9-17-46]]

^<<v9-17-46,46>>^ This very day Jehovah will surrender you into my hand, and I will strike you down and cut off your head; and on this day I will give the corpses of the camp of the Phi·lisʹtines to the birds of the heavens and to the wild beasts of the earth; and people of all the earth will know that there is a God in Israel.

[[v9-17-47]]

^<<v9-17-47,47>>^ And all those gathered here^&#42;1^ will know that it is not with the sword or the spear that Jehovah saves, for the battle belongs to Jehovah, and he will give all of you into our hand.”

[NOTE]
====
. Lit., “all this congregation.”
====

[[v9-17-48]]

^<<v9-17-48,48>>^ Then the Phi·lisʹtine rose and drew steadily closer to meet David, but David ran quickly toward the battle line to meet the Phi·lisʹtine.

[[v9-17-49]]

^<<v9-17-49,49>>^ David thrust his hand into his bag and took a stone from there and slung it. He struck the Phi·lisʹtine in the forehead, and the stone sank into his forehead and he fell facedown on the ground.

[[v9-17-50]]

^<<v9-17-50,50>>^ So David prevailed over the Phi·lisʹtine with a sling and a stone; he struck down the Phi·lisʹtine and put him to death, though there was no sword in David’s hand.

[[v9-17-51]]

^<<v9-17-51,51>>^ David continued running and stood over him. Then he took hold of the Phi·lisʹtine’s sword and pulled it out of its sheath and made sure that he was dead by cutting off his head with it. When the Phi·lisʹtines saw that their mighty one had died, they fled.

[[v9-17-52]]

^<<v9-17-52,52>>^ At that the men of Israel and of Judah rose and broke into shouting and pursued the Phi·lisʹtines all the way from the valley to the gates of Ekʹron, and the slain of the Phi·lisʹtines lay fallen along the road from Shaʹa·raʹim, as far as Gath and Ekʹron.

[[v9-17-53]]

^<<v9-17-53,53>>^ After the Israelites returned from hotly pursuing the Phi·lisʹtines, they pillaged their camps.

[[v9-17-54]]

^<<v9-17-54,54>>^ Then David took the head of the Phi·lisʹtine and brought it to Jerusalem, but he put the Phi·lisʹtine’s weapons in his own tent.

[[v9-17-55]]

^<<v9-17-55,55>>^ At the moment that Saul saw David go out to meet the Phi·lisʹtine, he said to Abʹner, the chief of the army: “Whose son is this boy, Abʹner?” Abʹner replied: “As surely as you live,^&#42;1^ O king, I do not know!”

[NOTE]
====
. Or “By the life of your soul.”
====

[[v9-17-56]]

^<<v9-17-56,56>>^ The king said: “Find out whose son the young man is.”

[[v9-17-57]]

^<<v9-17-57,57>>^ So as soon as David returned from striking down the Phi·lisʹtine, Abʹner took him and brought him before Saul with the head of the Phi·lisʹtine in his hand.

[[v9-17-58]]

^<<v9-17-58,58>>^ Saul now said to him: “Whose son are you, boy?” to which David said: “The son of your servant Jesʹse the Bethʹle·hem·ite.”

'''

xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[&#60; Capítulo Anterior] | <<v9-17-0,Topo>> | xref:009-1-samuel/009-1-samuel-018.adoc#v9-18-0[Próximo Capítulo &#62;]