include::./index.adoc[]

[[v9-1-0]]
=== The First of Samuel, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-1-1]]

^<<v9-1-1,1>>^ Now there was a man of Ra·math·aʹim-zoʹphim^&#42;1^ of the mountainous region of Eʹphra·im whose name was El·kaʹnah, the son of Je·roʹham, the son of E·liʹhu, the son of Toʹhu, the son of Zuph, an Eʹphra·im·ite.

[NOTE]
====
. Or “of Ramah, a Zuphite.”
====

[[v9-1-2]]

^<<v9-1-2,2>>^ He had two wives; one was named Hanʹnah, and the other was named Pe·ninʹnah. Pe·ninʹnah had children, but Hanʹnah had no children.

[[v9-1-3]]

^<<v9-1-3,3>>^ That man went up from his city year after year to worship^&#42;1^ and to sacrifice to Jehovah of armies in Shiʹloh. That is where the two sons of Eʹli, Hophʹni and Phinʹe·has, served as priests to Jehovah.

[NOTE]
====
. Or “bow down.”
====

[[v9-1-4]]

^<<v9-1-4,4>>^ One day when El·kaʹnah offered a sacrifice, he gave portions to his wife Pe·ninʹnah as well as to all her sons and her daughters,

[[v9-1-5]]

^<<v9-1-5,5>>^ but to Hanʹnah he gave a special portion, because Hanʹnah was the one he loved; but Jehovah had not given her children.^&#42;1^

[NOTE]
====
. Lit., “had closed her womb.”
====

[[v9-1-6]]

^<<v9-1-6,6>>^ Moreover, her rival wife taunted her relentlessly in order to upset her because Jehovah had not given her children.

[[v9-1-7]]

^<<v9-1-7,7>>^ That is what she would do year after year; whenever Hanʹnah went up to the house of Jehovah, her rival would taunt her so much that she would weep and not eat.

[[v9-1-8]]

^<<v9-1-8,8>>^ But her husband El·kaʹnah said to her: “Hanʹnah, why do you weep, and why do you not eat, and why are you so sad?^&#42;1^ Am I not better to you than ten sons?”

[NOTE]
====
. Or “why does your heart feel bad?”
====

[[v9-1-9]]

^<<v9-1-9,9>>^ Then Hanʹnah got up after they had finished eating and drinking in Shiʹloh. At the time, Eʹli the priest was sitting on the seat by the doorpost of the temple^&#42;1^ of Jehovah.

[NOTE]
====
. That is, the tabernacle.
====

[[v9-1-10]]

^<<v9-1-10,10>>^ Hanʹnah was extremely bitter,^&#42;1^ and she began to pray to Jehovah and to weep uncontrollably.

[NOTE]
====
. Or “bitter of soul.”
====

[[v9-1-11]]

^<<v9-1-11,11>>^ And she made this vow: “O Jehovah of armies, if you look upon the affliction of your servant and remember me and you do not forget your servant and give to your servant a male child, I will give him to Jehovah all the days of his life, and no razor will touch his head.”

[[v9-1-12]]

^<<v9-1-12,12>>^ While she prayed for a long time before Jehovah, Eʹli was watching her mouth.

[[v9-1-13]]

^<<v9-1-13,13>>^ Hanʹnah was speaking in her heart, only her lips were trembling, but her voice was not heard. So Eʹli thought she was drunk.

[[v9-1-14]]

^<<v9-1-14,14>>^ Eʹli said to her: “How long will you stay drunk? Stop drinking your wine.”

[[v9-1-15]]

^<<v9-1-15,15>>^ At this Hanʹnah answered: “No, my lord! I am a woman under great stress;^&#42;1^ I have not drunk wine or anything alcoholic, but I am pouring out my soul^&#42;2^ before Jehovah.

[NOTE]
====
. Or “a woman hard-pressed in spirit.”
. See Glossary.
====

[[v9-1-16]]

^<<v9-1-16,16>>^ Do not take your servant for a worthless woman, for I have been speaking until now out of my great anguish and distress.”

[[v9-1-17]]

^<<v9-1-17,17>>^ Then Eʹli answered: “Go in peace, and may the God of Israel grant your petition that you have asked of him.”

[[v9-1-18]]

^<<v9-1-18,18>>^ To this she said: “Let your servant find favor in your eyes.” And the woman went on her way and ate, and her face was no longer downcast.

[[v9-1-19]]

^<<v9-1-19,19>>^ Then they got up early in the morning and bowed before Jehovah, after which they returned to their house in Raʹmah. El·kaʹnah had sexual relations with his wife Hanʹnah, and Jehovah gave attention to^&#42;1^ her.

[NOTE]
====
. Lit., “remembered.”
====

[[v9-1-20]]

^<<v9-1-20,20>>^ Within a year^&#42;1^ Hanʹnah became pregnant and gave birth to a son and named him Samuel,^&#42;2^ because, as she said, “it is from Jehovah that I have asked him.”

[NOTE]
====
. Or possibly, “In due time.”
. Meaning “Name of God.”
====

[[v9-1-21]]

^<<v9-1-21,21>>^ In time El·kaʹnah went up with all his household to offer the yearly sacrifice to Jehovah and to present his vow offering.

[[v9-1-22]]

^<<v9-1-22,22>>^ But Hanʹnah did not go up, for she said to her husband: “As soon as the boy is weaned, I will bring him; then he will appear before Jehovah and remain there from then on.”

[[v9-1-23]]

^<<v9-1-23,23>>^ El·kaʹnah her husband then said to her: “Do what you think is best.^&#42;1^ Stay at home until you wean him. May Jehovah carry out what you have said.” So the woman stayed at home and nursed her son until she weaned him.

[NOTE]
====
. Lit., “what is good in your eyes.”
====

[[v9-1-24]]

^<<v9-1-24,24>>^ As soon as she had weaned him, she took him up to Shiʹloh, along with a three-year-old bull, one eʹphah^&#42;1^ of flour, and a large jar of wine, and she came to the house of Jehovah in Shiʹloh and brought the young boy with her.

[NOTE]
====
. About 22 L (20 dry qt). See App. B14.
====

[[v9-1-25]]

^<<v9-1-25,25>>^ Then they slaughtered the bull and brought the boy to Eʹli.

[[v9-1-26]]

^<<v9-1-26,26>>^ With that she said: “Pardon me, my lord! As surely as you live,^&#42;1^ my lord, I am the woman who was standing with you in this place to pray to Jehovah.

[NOTE]
====
. Or “By the life of your soul.”
====

[[v9-1-27]]

^<<v9-1-27,27>>^ It was for this boy that I prayed, and Jehovah granted my petition that I asked of him.

[[v9-1-28]]

^<<v9-1-28,28>>^ I, in turn, now lend him to Jehovah. For all his days, he is lent to Jehovah.”
And he^&#42;1^ bowed down there to Jehovah.

[NOTE]
====
. Evidently referring to Elkanah.
====

'''

xref:008-ruth/008-ruth-004.adoc#v8-4-0[&#60; Capítulo Anterior] | <<v9-1-0,Topo>> | xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[Próximo Capítulo &#62;]