include::./index.adoc[]

[[v9-7-0]]
=== The First of Samuel, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-7-1]]

^<<v9-7-1,1>>^ So the men of Kirʹi·ath-jeʹa·rim came and took the Ark of Jehovah up into the house of A·binʹa·dab on the hill, and they sanctified his son El·e·aʹzar to guard the Ark of Jehovah.

[[v9-7-2]]

^<<v9-7-2,2>>^ A long time elapsed, 20 years in all, from the day of the Ark’s coming to Kirʹi·ath-jeʹa·rim, and all the house of Israel began to seek^&#42;1^ after Jehovah.

[NOTE]
====
. Or “mourn.”
====

[[v9-7-3]]

^<<v9-7-3,3>>^ Samuel then said to all the house of Israel: “If you are returning to Jehovah with all your heart, put away the foreign gods and the Ashʹto·reth images from among you, and direct your heart unswervingly to Jehovah and serve only him, and he will rescue you from the hand of the Phi·lisʹtines.”

[[v9-7-4]]

^<<v9-7-4,4>>^ At that the Israelites got rid of the Baʹals and the Ashʹto·reth images and served only Jehovah.

[[v9-7-5]]

^<<v9-7-5,5>>^ Then Samuel said: “Gather all Israel together at Mizʹpah, and I will pray to Jehovah in your behalf.”

[[v9-7-6]]

^<<v9-7-6,6>>^ So they gathered together at Mizʹpah, and they drew water and poured it out before Jehovah and kept a fast on that day. There they said: “We have sinned against Jehovah.” And Samuel began serving as judge over the Israelites in Mizʹpah.

[[v9-7-7]]

^<<v9-7-7,7>>^ When the Phi·lisʹtines heard that the Israelites had gathered together at Mizʹpah, the lords of the Phi·lisʹtines went up against Israel. When the Israelites heard of it, they were afraid because of the Phi·lisʹtines.

[[v9-7-8]]

^<<v9-7-8,8>>^ So the Israelites said to Samuel: “Do not stop calling to Jehovah our God to help us and to save us from the hand of the Phi·lisʹtines.”

[[v9-7-9]]

^<<v9-7-9,9>>^ Then Samuel took a suckling lamb and offered it up as a whole burnt offering to Jehovah; and Samuel called to Jehovah for help in behalf of Israel, and Jehovah answered him.

[[v9-7-10]]

^<<v9-7-10,10>>^ As Samuel was offering up the burnt offering, the Phi·lisʹtines advanced for battle against Israel. Jehovah now caused it to thunder loudly on that day against the Phi·lisʹtines, and He threw them into confusion, and they were defeated before Israel.

[[v9-7-11]]

^<<v9-7-11,11>>^ At that the men of Israel went out from Mizʹpah and pursued the Phi·lisʹtines, striking them down as far as south of Beth-car.

[[v9-7-12]]

^<<v9-7-12,12>>^ Then Samuel took a stone and set it between Mizʹpah and Jeshʹa·nah and named it Eb·en·eʹzer,^&#42;1^ for he said: “Until now Jehovah has helped us.”

[NOTE]
====
. Meaning “Stone of Help.”
====

[[v9-7-13]]

^<<v9-7-13,13>>^ Thus the Phi·lisʹtines were subdued, and they did not come again into the territory of Israel; and the hand of Jehovah continued against the Phi·lisʹtines all the days of Samuel.

[[v9-7-14]]

^<<v9-7-14,14>>^ Also, the cities that the Phi·lisʹtines had taken from Israel were returned to Israel, from Ekʹron to Gath, and Israel recovered their territory from the hand of the Phi·lisʹtines.
There was also peace between Israel and the Amʹor·ites.

[[v9-7-15]]

^<<v9-7-15,15>>^ Samuel kept on judging Israel throughout his life.

[[v9-7-16]]

^<<v9-7-16,16>>^ Each year he traveled in a circuit to Bethʹel, Gilʹgal, and Mizʹpah, and he judged Israel in all these places.

[[v9-7-17]]

^<<v9-7-17,17>>^ But he would return to Raʹmah, because his house was there, and there he also judged Israel. He built an altar there to Jehovah.

'''

xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[&#60; Capítulo Anterior] | <<v9-7-0,Topo>> | xref:009-1-samuel/009-1-samuel-008.adoc#v9-8-0[Próximo Capítulo &#62;]