include::./index.adoc[]

[[v9-15-0]]
=== The First of Samuel, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-15-1]]

^<<v9-15-1,1>>^ Then Samuel said to Saul: “Jehovah sent me to anoint you as king over his people Israel; now listen to what Jehovah has to say.

[[v9-15-2]]

^<<v9-15-2,2>>^ This is what Jehovah of armies says: ‘I will call to account the A·malʹek·ites for what they did to Israel when they opposed them along their way coming up from Egypt.

[[v9-15-3]]

^<<v9-15-3,3>>^ Now go, and strike down the A·malʹek·ites, and devote them to destruction along with all that they have. You must not spare^&#42;1^ them; you are to put them to death, man as well as woman, child as well as infant, bull as well as sheep, camel as well as donkey.’”

[NOTE]
====
. Or “show compassion to.”
====

[[v9-15-4]]

^<<v9-15-4,4>>^ Saul summoned the people and counted them in Te·laʹim: There were 200,000 foot soldiers and 10,000 men of Judah.

[[v9-15-5]]

^<<v9-15-5,5>>^ Saul advanced as far as the city of Amʹa·lek and set an ambush by the valley.^&#42;1^

[NOTE]
====
. Or “wadi.”
====

[[v9-15-6]]

^<<v9-15-6,6>>^ Saul then said to the Kenʹites: “Go, depart from among the A·malʹek·ites, so that I do not sweep you away with them. For you showed loyal love to all the people of Israel at the time they came up out of Egypt.” So the Kenʹites departed from the midst of Amʹa·lek.

[[v9-15-7]]

^<<v9-15-7,7>>^ After that Saul struck down the A·malʹek·ites from Havʹi·lah as far as Shur, which is next to Egypt.

[[v9-15-8]]

^<<v9-15-8,8>>^ He caught Aʹgag the king of Amʹa·lek alive, but all the other people he devoted to destruction with the sword.

[[v9-15-9]]

^<<v9-15-9,9>>^ However, Saul and the people spared^&#42;1^ Aʹgag and the best of the flock, the herd, the fattened animals, the rams, and all that was good. They did not want to devote them to destruction. But all the goods that were worthless and unwanted, these they devoted to destruction.

[NOTE]
====
. Or “showed compassion to.”
====

[[v9-15-10]]

^<<v9-15-10,10>>^ Then the word of Jehovah came to Samuel:

[[v9-15-11]]

^<<v9-15-11,11>>^ “I regret^&#42;1^ that I have made Saul king, for he has turned away from following me and he has not carried out my words.” Samuel became very upset, and he kept crying out to Jehovah all night long.

[NOTE]
====
. Or “am grieved.”
====

[[v9-15-12]]

^<<v9-15-12,12>>^ When Samuel got up early in the morning to meet Saul, Samuel was told: “Saul went to Carʹmel, and there he erected a monument for himself. Then he turned around and went down to Gilʹgal.”

[[v9-15-13]]

^<<v9-15-13,13>>^ When Samuel finally came to him, Saul said to him: “May Jehovah bless you. I have carried out the word of Jehovah.”

[[v9-15-14]]

^<<v9-15-14,14>>^ But Samuel said: “Then what is this sound of the flock in my ears and the sound of the cattle that I hear?”

[[v9-15-15]]

^<<v9-15-15,15>>^ To this Saul said: “They were brought from the A·malʹek·ites, because the people spared^&#42;1^ the best of the flock and the herd for sacrificing them to Jehovah your God; but what was left we devoted to destruction.”

[NOTE]
====
. Or “showed compassion to.”
====

[[v9-15-16]]

^<<v9-15-16,16>>^ At this Samuel said to Saul: “Stop! Let me tell you what Jehovah said to me last night.” So he said to him: “Speak!”

[[v9-15-17]]

^<<v9-15-17,17>>^ Samuel continued: “Were you not insignificant in your own eyes when you were made head of the tribes of Israel and when Jehovah anointed you as king over Israel?

[[v9-15-18]]

^<<v9-15-18,18>>^ Jehovah later sent you on a mission and said, ‘Go, and devote the sinful A·malʹek·ites to destruction. Fight against them until you have exterminated them.’

[[v9-15-19]]

^<<v9-15-19,19>>^ So why did you not obey the voice of Jehovah? Instead, you rushed greedily toward the spoil and did what was bad in the eyes of Jehovah!”

[[v9-15-20]]

^<<v9-15-20,20>>^ However, Saul said to Samuel: “But I have obeyed the voice of Jehovah! I went on the mission to which Jehovah sent me, and I brought back Aʹgag the king of Amʹa·lek, and I devoted the A·malʹek·ites to destruction.

[[v9-15-21]]

^<<v9-15-21,21>>^ But the people took sheep and cattle from the spoil, the best of what was devoted to destruction, to sacrifice to Jehovah your God at Gilʹgal.”

[[v9-15-22]]

^<<v9-15-22,22>>^ Samuel then said: “Does Jehovah take as much pleasure in burnt offerings and sacrifices as in obeying the voice of Jehovah? Look! To obey is better than a sacrifice, and to pay attention than the fat of rams;

[[v9-15-23]]

^<<v9-15-23,23>>^ for rebelliousness is the same as the sin of divination, and pushing ahead presumptuously the same as using magical power and idolatry.^&#42;1^ Because you have rejected the word of Jehovah, he has rejected you from being king.”

[NOTE]
====
. Lit., “teraphim statues,” that is, household gods; idols.
====

[[v9-15-24]]

^<<v9-15-24,24>>^ Then Saul said to Samuel: “I have sinned, for I have overstepped the order of Jehovah and your words, because I feared the people and listened to what they said.

[[v9-15-25]]

^<<v9-15-25,25>>^ And now, please, pardon my sin, and return with me so that I may bow down to Jehovah.”

[[v9-15-26]]

^<<v9-15-26,26>>^ But Samuel said to Saul: “I will not return with you, for you have rejected the word of Jehovah, and Jehovah has rejected you from continuing as king over Israel.”

[[v9-15-27]]

^<<v9-15-27,27>>^ As Samuel was turning to go, Saul grabbed hold of the hem of his sleeveless coat, but it ripped away.

[[v9-15-28]]

^<<v9-15-28,28>>^ At this Samuel said to him: “Jehovah has ripped away the royal rule of Israel from you today, and he will give it to one of your fellow men who is better than you.

[[v9-15-29]]

^<<v9-15-29,29>>^ Moreover, the Excellency of Israel will not prove false or change his mind,^&#42;1^ for He is not a mere man that he should change his mind.”^&#42;2^

[NOTE]
====
. Or “feel regret.”
. Or “feel regret.”
====

[[v9-15-30]]

^<<v9-15-30,30>>^ At this he said: “I have sinned. But honor me, please, in front of the elders of my people and in front of Israel. Return with me, and I will bow down to Jehovah your God.”

[[v9-15-31]]

^<<v9-15-31,31>>^ So Samuel returned behind Saul, and Saul bowed down to Jehovah.

[[v9-15-32]]

^<<v9-15-32,32>>^ And Samuel said: “Bring Aʹgag the king of Amʹa·lek near to me.” Then Aʹgag went to him reluctantly,^&#42;1^ for Aʹgag had been saying to himself: ‘Surely the threat^&#42;2^ of death is past.’

[NOTE]
====
. Or possibly, “confidently.”
. Lit., “bitterness.”
====

[[v9-15-33]]

^<<v9-15-33,33>>^ However, Samuel said: “Just as your sword has bereaved women of children, so your mother will be most bereaved among women.” With that Samuel hacked Aʹgag to pieces before Jehovah at Gilʹgal.

[[v9-15-34]]

^<<v9-15-34,34>>^ Samuel now went to Raʹmah, and Saul went up to his own house at Gibʹe·ah of Saul.

[[v9-15-35]]

^<<v9-15-35,35>>^ Samuel did not see Saul again until the day of his death, for Samuel went into mourning for Saul. And Jehovah regretted that he had made Saul king over Israel.

'''

xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[&#60; Capítulo Anterior] | <<v9-15-0,Topo>> | xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[Próximo Capítulo &#62;]