include::./index.adoc[]

[[v9-19-0]]
=== The First of Samuel, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-19-1]]

^<<v9-19-1,1>>^ Saul later spoke to Jonʹa·than his son and to all his servants about putting David to death.

[[v9-19-2]]

^<<v9-19-2,2>>^ Since Saul’s son Jonʹa·than was very fond of David, Jonʹa·than told David: “My father Saul wants to have you put to death. Please be on your guard in the morning, and go to a secret place and remain hidden.

[[v9-19-3]]

^<<v9-19-3,3>>^ I will go out and stand next to my father in the field where you will be. I will talk about you to my father, and if I learn anything, I will be sure to tell you.”

[[v9-19-4]]

^<<v9-19-4,4>>^ So Jonʹa·than spoke well of David to his father Saul. He said to him: “The king should not sin against his servant David, for he has not sinned against you and what he has done for you has benefited you.

[[v9-19-5]]

^<<v9-19-5,5>>^ He risked his life^&#42;1^ to strike down the Phi·lisʹtine, so that Jehovah brought about a great victory^&#42;2^ for all Israel. You saw it, and you were overjoyed. So why should you sin against innocent blood in having David put to death for no reason?”

[NOTE]
====
. Or “put his soul in his hand.”
. Or “salvation.”
====

[[v9-19-6]]

^<<v9-19-6,6>>^ Saul listened to Jonʹa·than, and Saul swore: “As surely as Jehovah is living, he will not be put to death.”

[[v9-19-7]]

^<<v9-19-7,7>>^ Afterward Jonʹa·than called David and told him all these things. So Jonʹa·than brought David to Saul, and he continued to serve him as before.

[[v9-19-8]]

^<<v9-19-8,8>>^ In time war broke out again, and David went out and fought against the Phi·lisʹtines and struck them down with a great slaughter, and they fled from before him.

[[v9-19-9]]

^<<v9-19-9,9>>^ And a bad spirit from Jehovah came upon Saul when he was sitting in his house with his spear in his hand, while David was playing music on the harp.

[[v9-19-10]]

^<<v9-19-10,10>>^ Saul tried to pin David to the wall with the spear, but he eluded Saul, who drove the spear into the wall. David fled and escaped during that night.

[[v9-19-11]]

^<<v9-19-11,11>>^ Saul later sent messengers to David’s house to watch it and to kill him in the morning, but David’s wife Miʹchal told him: “If you do not escape^&#42;1^ tonight, tomorrow you will be a dead man.”

[NOTE]
====
. Or “If you do not let your soul escape.”
====

[[v9-19-12]]

^<<v9-19-12,12>>^ Immediately Miʹchal let David down through the window, so that he could run away and escape.

[[v9-19-13]]

^<<v9-19-13,13>>^ Miʹchal took the teraphim statue^&#42;1^ and placed it on the bed, and she put a net of goat hair at the place of his head, and she covered it with a garment.

[NOTE]
====
. Or “the household god; the idol.”
====

[[v9-19-14]]

^<<v9-19-14,14>>^ Saul now sent messengers to take David, but she said: “He is sick.”

[[v9-19-15]]

^<<v9-19-15,15>>^ So Saul sent the messengers to see David and told them: “Bring him to me on his bed to have him put to death.”

[[v9-19-16]]

^<<v9-19-16,16>>^ When the messengers came in, there was the teraphim statue^&#42;1^ on the bed and a net of goat hair where his head would have been.

[NOTE]
====
. Or “the household god; the idol.”
====

[[v9-19-17]]

^<<v9-19-17,17>>^ Saul said to Miʹchal: “Why did you trick me like this and send my enemy away so that he could escape?” Miʹchal replied to Saul: “He said to me, ‘Send me away, or I will kill you!’”

[[v9-19-18]]

^<<v9-19-18,18>>^ Now David had run away and escaped, and he came to Samuel at Raʹmah. He told him all that Saul had done to him. Then he and Samuel went away, and they stayed in Naiʹoth.

[[v9-19-19]]

^<<v9-19-19,19>>^ In time it was reported to Saul: “Look! David is in Naiʹoth in Raʹmah.”

[[v9-19-20]]

^<<v9-19-20,20>>^ At once Saul sent messengers to seize David. When they saw the elderly ones of the prophets prophesying and Samuel standing and presiding over them, the spirit of God came to be upon Saul’s messengers, and they began behaving as prophets as well.

[[v9-19-21]]

^<<v9-19-21,21>>^ When they told it to Saul, he immediately sent other messengers, and they too began behaving as prophets. So Saul sent messengers again, a third group, and they too began behaving as prophets.

[[v9-19-22]]

^<<v9-19-22,22>>^ Finally he also went to Raʹmah. When he reached the great cistern that is in Seʹcu, he asked: “Where are Samuel and David?” They replied: “There in Naiʹoth in Raʹmah.”

[[v9-19-23]]

^<<v9-19-23,23>>^ While Saul was on his way from there to Naiʹoth in Raʹmah, the spirit of God came upon him as well, and he walked along behaving as a prophet until he came into Naiʹoth in Raʹmah.

[[v9-19-24]]

^<<v9-19-24,24>>^ He also stripped off his garments, and he too behaved as a prophet before Samuel, and he lay there naked^&#42;1^ all that day and all that night. That is why they say: “Is Saul also among the prophets?”

[NOTE]
====
. Or “lightly clad.”
====

'''

xref:009-1-samuel/009-1-samuel-018.adoc#v9-18-0[&#60; Capítulo Anterior] | <<v9-19-0,Topo>> | xref:009-1-samuel/009-1-samuel-020.adoc#v9-20-0[Próximo Capítulo &#62;]