include::./index.adoc[]

[[v9-20-0]]
=== The First of Samuel, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-20-1]]

^<<v9-20-1,1>>^ Then David ran away from Naiʹoth in Raʹmah. However, he came to Jonʹa·than and said: “What have I done? What is my offense, and how have I sinned against your father for him to seek my life?”^&#42;1^

[NOTE]
====
. Or “soul.”
====

[[v9-20-2]]

^<<v9-20-2,2>>^ At this Jonʹa·than said to him: “It is unthinkable! You will not die. Look! My father will not do anything, great or small, without disclosing it to me. Why should my father hide this matter from me? This will not happen.”

[[v9-20-3]]

^<<v9-20-3,3>>^ But David swore further and said: “Your father surely knows that I have found favor in your eyes and would say, ‘Do not let Jonʹa·than know this or he will be upset.’ But as surely as Jehovah is living and as surely as you are^&#42;1^ living, there is only a step between me and death!”

[NOTE]
====
. Or “your soul is.”
====

[[v9-20-4]]

^<<v9-20-4,4>>^ Then Jonʹa·than said to David: “Whatever you say,^&#42;1^ I will do for you.”

[NOTE]
====
. Or “your soul says.”
====

[[v9-20-5]]

^<<v9-20-5,5>>^ David said to Jonʹa·than: “Tomorrow is the new moon, and I am certainly expected to sit with the king to eat; you must send me away, and I will hide in the field until the evening on the third day.

[[v9-20-6]]

^<<v9-20-6,6>>^ If your father misses me at all, then say, ‘David begged me for permission to go quickly to his city Bethʹle·hem, because there is a yearly sacrifice there for all the family.’

[[v9-20-7]]

^<<v9-20-7,7>>^ If his response is, ‘That is fine,’ it means peace to your servant. But if he becomes angry, you can be sure that he is determined to harm me.

[[v9-20-8]]

^<<v9-20-8,8>>^ Show loyal love to your servant, for you have brought your servant into Jehovah’s covenant with you. But if I am guilty, put me to death yourself. Why turn me over to your father?”

[[v9-20-9]]

^<<v9-20-9,9>>^ To this Jonʹa·than said: “It is unthinkable to suggest that about you! If I learn that my father is determined to harm you, would I not tell you?”

[[v9-20-10]]

^<<v9-20-10,10>>^ Then David said to Jonʹa·than: “Who will tell me whether your father gives you a harsh answer?”

[[v9-20-11]]

^<<v9-20-11,11>>^ Jonʹa·than said to David: “Come, let us go out into the field.” So both of them went out into the field.

[[v9-20-12]]

^<<v9-20-12,12>>^ And Jonʹa·than said to David: “Let Jehovah the God of Israel be a witness that I will sound out my father about this time tomorrow or by the third day. If he is favorably disposed toward David, will I not then send you word and disclose it to you?

[[v9-20-13]]

^<<v9-20-13,13>>^ But if my father intends to harm you, may Jehovah do that and more to Jonʹa·than if I do not disclose it to you and send you away in peace. May Jehovah be with you, just as he was with my father.

[[v9-20-14]]

^<<v9-20-14,14>>^ And will you not show me the loyal love of Jehovah while I am alive and even when I die?

[[v9-20-15]]

^<<v9-20-15,15>>^ Never withdraw your loyal love from my household, even when Jehovah wipes out all the enemies of David from the face of the earth.”

[[v9-20-16]]

^<<v9-20-16,16>>^ So Jonʹa·than made a covenant with the house of David, saying, “Jehovah will require it and call David’s enemies to account.”

[[v9-20-17]]

^<<v9-20-17,17>>^ So Jonʹa·than had David swear again by his love for him, for he loved him as he loved himself.^&#42;1^

[NOTE]
====
. Or “his own soul.”
====

[[v9-20-18]]

^<<v9-20-18,18>>^ Jonʹa·than then said to him: “Tomorrow is the new moon, and you will be missed, for your seat will be vacant.

[[v9-20-19]]

^<<v9-20-19,19>>^ By the third day, you will be missed even more, and you must go to the place where you hid the other day^&#42;1^ and stay near the stone here.

[NOTE]
====
. Lit., “on the working day.”
====

[[v9-20-20]]

^<<v9-20-20,20>>^ I will then shoot three arrows to one side of it, as though I were shooting at a target.

[[v9-20-21]]

^<<v9-20-21,21>>^ When I send the attendant, I will say, ‘Go, find the arrows.’ If I say to the attendant, ‘Look! The arrows are on this side of you, get them,’ then you may come back, for as surely as Jehovah is living, it means everything is peaceful for you and there is no danger.

[[v9-20-22]]

^<<v9-20-22,22>>^ But if I should say to the boy, ‘Look! The arrows are beyond you,’ then go, for Jehovah has sent you away.

[[v9-20-23]]

^<<v9-20-23,23>>^ As for the promise that we have made, you and I, may Jehovah be between us forever.”

[[v9-20-24]]

^<<v9-20-24,24>>^ So David hid in the field. When the new moon came, the king took his seat at the meal to eat.

[[v9-20-25]]

^<<v9-20-25,25>>^ The king was sitting in his usual seat by the wall. Jonʹa·than was facing him, and Abʹner was sitting at Saul’s side, but David’s place was vacant.

[[v9-20-26]]

^<<v9-20-26,26>>^ Saul did not say anything that day, for he said to himself: ‘Something has happened so that he is not clean. Yes, he must be unclean.’

[[v9-20-27]]

^<<v9-20-27,27>>^ And the day after the new moon, on the second day, David’s place continued vacant. Saul then said to Jonʹa·than his son: “Why has the son of Jesʹse not come to the meal either yesterday or today?”

[[v9-20-28]]

^<<v9-20-28,28>>^ Jonʹa·than answered Saul: “David begged me for permission to go to Bethʹle·hem.

[[v9-20-29]]

^<<v9-20-29,29>>^ He said, ‘Please permit me to go, because we have a family sacrifice in the city, and my own brother summoned me. So if I have found favor in your eyes, please let me slip away to see my brothers.’ That is why he has not come to the king’s table.”

[[v9-20-30]]

^<<v9-20-30,30>>^ Then Saul became enraged with Jonʹa·than, and he said to him: “You son of a rebellious woman, do you think I do not know that you are choosing to side with the son of Jesʹse, to your own shame and to the shame of your mother?^&#42;1^

[NOTE]
====
. Lit., “to the shame of your mother’s nakedness?”
====

[[v9-20-31]]

^<<v9-20-31,31>>^ As long as the son of Jesʹse is alive on the earth, you and your kingship will not be firmly established. So now send someone to bring him to me, for he must die.”^&#42;1^

[NOTE]
====
. Lit., “for he is a son of death.”
====

[[v9-20-32]]

^<<v9-20-32,32>>^ However, Jonʹa·than said to Saul his father: “Why should he be put to death? What has he done?”

[[v9-20-33]]

^<<v9-20-33,33>>^ At that Saul hurled the spear at him to strike him, so Jonʹa·than knew that his father was determined to put David to death.

[[v9-20-34]]

^<<v9-20-34,34>>^ Jonʹa·than immediately rose up from the table in the heat of anger, and he did not eat any food on the second day after the new moon, for he was upset over David and his own father had humiliated him.

[[v9-20-35]]

^<<v9-20-35,35>>^ In the morning Jonʹa·than went out to the field for the appointment with David, and a young attendant was with him.

[[v9-20-36]]

^<<v9-20-36,36>>^ And he said to his attendant: “Please run and find the arrows that I shoot.” The attendant ran, and Jonʹa·than shot the arrow beyond him.

[[v9-20-37]]

^<<v9-20-37,37>>^ When the attendant reached the place where Jonʹa·than had shot the arrow, Jonʹa·than called out to the attendant: “Is not the arrow beyond you?”

[[v9-20-38]]

^<<v9-20-38,38>>^ Jonʹa·than called out to the attendant: “Hurry! Go quickly! Do not delay!” And Jonʹa·than’s attendant picked up the arrows and came back to his master.

[[v9-20-39]]

^<<v9-20-39,39>>^ The attendant did not understand anything about the matter; only Jonʹa·than and David knew what was meant.

[[v9-20-40]]

^<<v9-20-40,40>>^ Then Jonʹa·than gave his weapons to his attendant and told him: “Go, take them to the city.”

[[v9-20-41]]

^<<v9-20-41,41>>^ When the attendant left, David rose up from a place nearby that was to the south. Then he fell with his face to the ground and bowed three times, and they kissed each other and wept for each other, but David wept the most.

[[v9-20-42]]

^<<v9-20-42,42>>^ Jonʹa·than said to David: “Go in peace, since we have both sworn in the name of Jehovah, saying, ‘May Jehovah be between you and me and between your offspring^&#42;1^ and my offspring^&#42;2^ forever.’”
Then David rose up and left, and Jonʹa·than went back to the city.

[NOTE]
====
. Lit., “seed.”
. Lit., “seed.”
====

'''

xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[&#60; Capítulo Anterior] | <<v9-20-0,Topo>> | xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[Próximo Capítulo &#62;]