include::./index.adoc[]

[[v9-26-0]]
=== The First of Samuel, 26
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-26-1]]

^<<v9-26-1,1>>^ In time the men of Ziph came to Saul at Gibʹe·ah, saying: “Is David not hiding on the hill of Hach·iʹlah facing Je·shiʹmon?”^&#42;1^

[NOTE]
====
. Or possibly, “the desert; the wilderness.”
====

[[v9-26-2]]

^<<v9-26-2,2>>^ So Saul rose up and went down to the wilderness of Ziph with 3,000 chosen men of Israel to look for David in the wilderness of Ziph.

[[v9-26-3]]

^<<v9-26-3,3>>^ Saul camped on the hill of Hach·iʹlah, which faces Je·shiʹmon, by the road. David was then living in the wilderness, and he learned that Saul had come into the wilderness after him.

[[v9-26-4]]

^<<v9-26-4,4>>^ So David sent spies to verify that Saul had indeed come.

[[v9-26-5]]

^<<v9-26-5,5>>^ David later went to the place where Saul had encamped, and David saw the place where Saul and Abʹner the son of Ner, the chief of his army, were lying asleep; Saul lay asleep in the camp enclosure with the troops camping all around him.

[[v9-26-6]]

^<<v9-26-6,6>>^ Then David said to A·himʹe·lech the Hitʹtite and A·bishʹai the son of Ze·ruʹiah, the brother of Joʹab: “Who will go down with me into the camp to Saul?” A·bishʹai replied: “I will go down with you.”

[[v9-26-7]]

^<<v9-26-7,7>>^ So David and A·bishʹai made their way to the troops by night, and they found Saul lying asleep in the camp enclosure with his spear stuck into the ground next to his head; Abʹner and the troops were lying all around him.

[[v9-26-8]]

^<<v9-26-8,8>>^ A·bishʹai now said to David: “Today God has surrendered your enemy into your hand. And now, please, let me pin him to the ground with the spear just once, and I will not need to do it twice.”

[[v9-26-9]]

^<<v9-26-9,9>>^ However, David said to A·bishʹai: “Do not harm him, for who can lift his hand against the anointed of Jehovah and remain innocent?”

[[v9-26-10]]

^<<v9-26-10,10>>^ David continued: “As surely as Jehovah is living, Jehovah himself will strike him down, or his day will come and he will die, or he will go down into battle and perish.

[[v9-26-11]]

^<<v9-26-11,11>>^ It is unthinkable from Jehovah’s standpoint for me to lift my hand against the anointed of Jehovah! So now take, please, the spear next to his head and the water jug, and let us be on our way.”

[[v9-26-12]]

^<<v9-26-12,12>>^ So David took the spear and the water jug from next to Saul’s head, and they went away. No one saw or noticed them or woke up, for they were all asleep, because a deep sleep from Jehovah had fallen upon them.

[[v9-26-13]]

^<<v9-26-13,13>>^ Then David crossed to the other side and stood on the top of the mountain some distance away, with a considerable space between them.

[[v9-26-14]]

^<<v9-26-14,14>>^ David called out to the troops and to Abʹner the son of Ner, saying: “Abʹner, will you not answer?” Abʹner answered: “Who are you who calls to the king?”

[[v9-26-15]]

^<<v9-26-15,15>>^ David said to Abʹner: “Are you not a man? And who is like you in Israel? So why did you not keep watch over your lord the king? For one of the soldiers came in to do away with your lord the king.

[[v9-26-16]]

^<<v9-26-16,16>>^ What you have done is not good. As surely as Jehovah is living, you deserve to die, because you have not kept watch over your lord, the anointed of Jehovah. Now look around! Where are the king’s spear and the water jug that were next to his head?”

[[v9-26-17]]

^<<v9-26-17,17>>^ Then Saul recognized the voice of David and said: “Is this your voice, my son David?” David replied: “It is my voice, my lord the king.”

[[v9-26-18]]

^<<v9-26-18,18>>^ He added: “Why is my lord chasing after his servant, for what have I done, and what am I guilty of?

[[v9-26-19]]

^<<v9-26-19,19>>^ My lord the king, please, listen to the words of his servant: If it is Jehovah who incited you against me, let him accept^&#42;1^ my grain offering. But if men have incited you, they are cursed before Jehovah, because they have driven me away today from being united with Jehovah’s inheritance, saying, ‘Go, serve other gods!’

[NOTE]
====
. Lit., “smell.”
====

[[v9-26-20]]

^<<v9-26-20,20>>^ And now do not let my blood fall to the ground away from the presence of Jehovah, for the king of Israel has gone out to look for a single flea, as if he were chasing a partridge on the mountains.”

[[v9-26-21]]

^<<v9-26-21,21>>^ In turn Saul said: “I have sinned. Come back, my son David, for I will do you no more harm, because you regarded my life^&#42;1^ as precious this day. Yes, I have acted foolishly and have made a terrible mistake.”

[NOTE]
====
. Or “soul.”
====

[[v9-26-22]]

^<<v9-26-22,22>>^ David answered: “Here is the spear of the king. Let one of the young men come over and take it.

[[v9-26-23]]

^<<v9-26-23,23>>^ It is Jehovah who will repay each one for his own righteousness and his own faithfulness, for today Jehovah gave you into my hand, but I was unwilling to lift my hand against the anointed of Jehovah.

[[v9-26-24]]

^<<v9-26-24,24>>^ Look! Just as your life^&#42;1^ was precious to me this day, so may my life^&#42;2^ be precious in the eyes of Jehovah, and may he rescue me out of all distress.”

[NOTE]
====
. Or “soul.”
. Or “soul.”
====

[[v9-26-25]]

^<<v9-26-25,25>>^ Saul replied to David: “May you be blessed, my son David. You will surely do great things, and you will surely prevail.” Then David went on his way, and Saul returned to his place.

'''

xref:009-1-samuel/009-1-samuel-025.adoc#v9-25-0[&#60; Capítulo Anterior] | <<v9-26-0,Topo>> | xref:009-1-samuel/009-1-samuel-027.adoc#v9-27-0[Próximo Capítulo &#62;]