include::./index.adoc[]

[[v9-2-0]]
=== The First of Samuel, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-2-1]]

^<<v9-2-1,1>>^ Then Hanʹnah said in prayer:
“My heart rejoices in Jehovah;
My horn^&#42;1^ is exalted by Jehovah.
My mouth is opened wide against my enemies,
For I rejoice in your acts of salvation.

[NOTE]
====
. Or “strength.” See Glossary.
====

[[v9-2-2]]

^<<v9-2-2,2>>^ There is no one holy like Jehovah,
There is no one but you,
And there is no rock like our God.

[[v9-2-3]]

^<<v9-2-3,3>>^ Do not keep speaking with haughtiness;
Let nothing arrogant come from your mouth,
For Jehovah is a God of knowledge,
And by him deeds are rightly evaluated.

[[v9-2-4]]

^<<v9-2-4,4>>^ The bows of mighty men are shattered,
But those who are stumbling are given strength.

[[v9-2-5]]

^<<v9-2-5,5>>^ The well-fed must hire themselves out for bread,
But the hungry hunger no more.
The barren has given birth to seven,
But she who had many sons has become desolate.^&#42;1^

[NOTE]
====
. Lit., “has withered.”
====

[[v9-2-6]]

^<<v9-2-6,6>>^ Jehovah kills, and he preserves life;^&#42;1^
He brings down to the Grave,^&#42;2^ and he raises up.

[NOTE]
====
. Or “brings to life.”
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v9-2-7]]

^<<v9-2-7,7>>^ Jehovah impoverishes, and he enriches;
He abases, and he exalts.

[[v9-2-8]]

^<<v9-2-8,8>>^ He raises the lowly one from the dust;
He lifts up the poor from the ash heap,^&#42;1^
To make them sit with princes,
Giving them a seat of honor.
To Jehovah belong earth’s supports,
And he places the productive land upon them.

[NOTE]
====
. Or possibly, “garbage dump.”
====

[[v9-2-9]]

^<<v9-2-9,9>>^ He guards the steps of his loyal ones,
But the wicked will be silenced in darkness,
For not by power does a man prevail.

[[v9-2-10]]

^<<v9-2-10,10>>^ Jehovah will shatter those fighting against him;^&#42;1^
He will thunder against them from the heavens.
Jehovah will judge to the ends of the earth,
He will give power to his king
And exalt the horn^&#42;2^ of his anointed one.”

[NOTE]
====
. Or possibly, “Those contending against Jehovah will be terrified.”
. Or “strength.” See Glossary.
====

[[v9-2-11]]

^<<v9-2-11,11>>^ Then El·kaʹnah went to his house in Raʹmah, but the boy became a minister of^&#42;1^ Jehovah before Eʹli the priest.

[NOTE]
====
. Or “was serving.”
====

[[v9-2-12]]

^<<v9-2-12,12>>^ Now the sons of Eʹli were wicked men; they had no regard for Jehovah.

[[v9-2-13]]

^<<v9-2-13,13>>^ This is what they did with the due right of the priests from the people: Whenever any man was offering a sacrifice, an attendant of the priest came with a three-pronged fork in his hand when the meat was boiling,

[[v9-2-14]]

^<<v9-2-14,14>>^ and he would thrust it into the basin, the two-handled cooking pot, the cauldron, or the one-handled cooking pot. Whatever the fork brought up, the priest would take for himself. That is what they would do in Shiʹloh to all the Israelites coming there.

[[v9-2-15]]

^<<v9-2-15,15>>^ Also, even before the man sacrificing could make the fat smoke, an attendant of the priest would come and say to him: “Give the priest meat to roast. He will not take boiled meat from you, only raw meat.”

[[v9-2-16]]

^<<v9-2-16,16>>^ When the man would say to him: “Let them first be sure to make the fat smoke, then take for yourself whatever you desire,”^&#42;1^ he would say: “No, give it to me now; if not, I will take it by force!”

[NOTE]
====
. Or “your soul craves.”
====

[[v9-2-17]]

^<<v9-2-17,17>>^ Thus the sin of the attendants came to be very great before Jehovah, for the men treated the offering of Jehovah with disrespect.

[[v9-2-18]]

^<<v9-2-18,18>>^ Now Samuel was ministering before Jehovah, wearing^&#42;1^ a linen ephʹod, though he was just a boy.

[NOTE]
====
. Lit., “girded with.”
====

[[v9-2-19]]

^<<v9-2-19,19>>^ Also, his mother would make for him a little sleeveless coat, and she brought it up to him year after year when she came up with her husband to offer the yearly sacrifice.

[[v9-2-20]]

^<<v9-2-20,20>>^ And Eʹli blessed El·kaʹnah and his wife and said: “May Jehovah grant you a child from this wife in place of the one who was lent to Jehovah.” And they went back home.

[[v9-2-21]]

^<<v9-2-21,21>>^ Jehovah turned his attention to Hanʹnah, so that she could conceive; and she gave birth to three more sons and two daughters. And the boy Samuel continued growing up before Jehovah.

[[v9-2-22]]

^<<v9-2-22,22>>^ Now Eʹli was very old, but he had heard about everything that his sons were doing to all Israel and how they would lie down with the women who served at the entrance of the tent of meeting.

[[v9-2-23]]

^<<v9-2-23,23>>^ He used to say to them: “Why do you keep doing things like these? For the things I am hearing about you from all the people are bad.

[[v9-2-24]]

^<<v9-2-24,24>>^ No, my sons, the report that I hear circulating among the people of Jehovah is not good.

[[v9-2-25]]

^<<v9-2-25,25>>^ If a man should sin against another man, someone may appeal to Jehovah for him;^&#42;1^ but if a man should sin against Jehovah, who can pray for him?” But they refused to listen to their father, for Jehovah had determined to put them to death.

[NOTE]
====
. Or possibly, “God will arbitrate for him.”
====

[[v9-2-26]]

^<<v9-2-26,26>>^ Meanwhile, the boy Samuel kept growing in stature and in favor both with Jehovah and with the people.

[[v9-2-27]]

^<<v9-2-27,27>>^ A man of God came to Eʹli and said to him: “This is what Jehovah says: ‘Did I not plainly reveal myself to your father’s house while they were in Egypt as slaves to the house of Pharʹaoh?

[[v9-2-28]]

^<<v9-2-28,28>>^ And he was chosen out of all the tribes of Israel to serve as my priest and to go up on my altar to make sacrifices, to offer incense,^&#42;1^ and to bear an ephʹod before me; and I gave to the house of your forefather all the offerings made by fire of the Israelites.^&#42;2^

[NOTE]
====
. Or possibly, “to make sacrificial smoke billow up.”
. Lit., “sons of Israel.”
====

[[v9-2-29]]

^<<v9-2-29,29>>^ Why do you men scorn^&#42;1^ my sacrifice and my offering that I have commanded in my place of dwelling? Why do you keep honoring your sons more than me by fattening yourselves from the best portions of every offering of my people Israel?

[NOTE]
====
. Lit., “kick at.”
====

[[v9-2-30]]

^<<v9-2-30,30>>^ “‘That is why the word of Jehovah the God of Israel is: “I did indeed say that your house and the house of your forefather would always walk before me.” But now Jehovah declares: “It is unthinkable, on my part, because those honoring me I will honor, but those despising me will be treated with contempt.”

[[v9-2-31]]

^<<v9-2-31,31>>^ Look! Days are coming when I will cut off your strength^&#42;1^ and that of your father’s house, so that no man in your house will live to old age.

[NOTE]
====
. Lit., “arm.”
====

[[v9-2-32]]

^<<v9-2-32,32>>^ And you will look upon a rival in my dwelling amid all the good that is done to Israel, and never again will there be an old man in your house.

[[v9-2-33]]

^<<v9-2-33,33>>^ The man of yours whom I do not cut off from serving at my altar will cause your eyes to fail and will bring you grief,^&#42;1^ but the greater number of your house will die by the sword of men.

[NOTE]
====
. Or “will cause your soul to pine away.”
====

[[v9-2-34]]

^<<v9-2-34,34>>^ And what happens to your two sons, Hophʹni and Phinʹe·has, will be the sign for you: On one day both of them will die.

[[v9-2-35]]

^<<v9-2-35,35>>^ Then I will raise up for myself a faithful priest. He will act in harmony with what is my heart’s desire;^&#42;1^ and I will build for him a lasting house, and he will walk before my anointed one always.

[NOTE]
====
. Or “is in my heart and in my soul.”
====

[[v9-2-36]]

^<<v9-2-36,36>>^ Anyone who remains in your house will come and bow down to him for the payment of money and a loaf of bread, and will say: “Assign me, please, to one of the priestly offices to eat a piece of bread.”’”

'''

xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[&#60; Capítulo Anterior] | <<v9-2-0,Topo>> | xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[Próximo Capítulo &#62;]