include::./index.adoc[]

[[v9-31-0]]
=== The First of Samuel, 31
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-31-1]]

^<<v9-31-1,1>>^ Now the Phi·lisʹtines were fighting against Israel. And the men of Israel fled from before the Phi·lisʹtines, and many fell slain on Mount Gil·boʹa.

[[v9-31-2]]

^<<v9-31-2,2>>^ The Phi·lisʹtines kept in close range of Saul and his sons, and the Phi·lisʹtines struck down Jonʹa·than, A·binʹa·dab, and Malʹchi-shuʹa, Saul’s sons.

[[v9-31-3]]

^<<v9-31-3,3>>^ The fighting grew fierce against Saul, and the archers found him, and he was severely wounded by the archers.

[[v9-31-4]]

^<<v9-31-4,4>>^ Then Saul said to his armor-bearer: “Draw your sword and run me through with it, so that these uncircumcised men may not come and run me through and deal ruthlessly^&#42;1^ with me.” But his armor-bearer was unwilling, because he was very much afraid. So Saul took the sword and fell on it.

[NOTE]
====
. Or “abusively.”
====

[[v9-31-5]]

^<<v9-31-5,5>>^ When his armor-bearer saw that Saul was dead, he too fell on his own sword and died with him.

[[v9-31-6]]

^<<v9-31-6,6>>^ Thus Saul, his three sons, his armor-bearer, and all his men died together on that day.

[[v9-31-7]]

^<<v9-31-7,7>>^ When the people of Israel who were in the region of the valley^&#42;1^ and in the region of the Jordan saw that the men of Israel had fled and that Saul and his sons had died, they began to abandon the cities and flee; the Phi·lisʹtines then came and occupied them.

[NOTE]
====
. Or “low plain.”
====

[[v9-31-8]]

^<<v9-31-8,8>>^ The next day, when the Phi·lisʹtines came to strip the slain, they found Saul and his three sons fallen on Mount Gil·boʹa.

[[v9-31-9]]

^<<v9-31-9,9>>^ So they cut off his head and stripped off his armor and sent word throughout the land of the Phi·lisʹtines to spread the news in the houses^&#42;1^ of their idols and among the people.

[NOTE]
====
. Or “temples.”
====

[[v9-31-10]]

^<<v9-31-10,10>>^ Then they put his armor in the house of the Ashʹto·reth images and fastened his corpse to the wall of Beth-shan.

[[v9-31-11]]

^<<v9-31-11,11>>^ When the inhabitants of Jaʹbesh-gilʹe·ad heard what the Phi·lisʹtines had done to Saul,

[[v9-31-12]]

^<<v9-31-12,12>>^ all the warriors rose and traveled all night and took the bodies of Saul and his sons off the wall of Beth-shan. They returned to Jaʹbesh and burned them there.

[[v9-31-13]]

^<<v9-31-13,13>>^ Then they took their bones and buried them under the tamarisk tree in Jaʹbesh, and they fasted for seven days.

'''

xref:009-1-samuel/009-1-samuel-030.adoc#v9-30-0[&#60; Capítulo Anterior] | <<v9-31-0,Topo>> | xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[Próximo Capítulo &#62;]