include::./index.adoc[]

[[v9-21-0]]
=== The First of Samuel, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-21-1]]

^<<v9-21-1,1>>^ David later came to Nob to A·himʹe·lech the priest. A·himʹe·lech began to tremble when he met David, and he said to him: “Why are you by yourself and no one is with you?”

[[v9-21-2]]

^<<v9-21-2,2>>^ David replied to A·himʹe·lech the priest: “The king instructed me to do something, but he said, ‘Do not let anyone know anything about the mission on which I am sending you and about the instructions I have given you.’ I made an appointment with my young men to meet at a certain place.

[[v9-21-3]]

^<<v9-21-3,3>>^ Now if there are five loaves of bread at your disposal, just give them to me, or whatever is available.”

[[v9-21-4]]

^<<v9-21-4,4>>^ But the priest answered David: “There is no ordinary bread on hand, but there is holy bread—provided that the young men have kept away from women.”^&#42;1^

[NOTE]
====
. Or “have abstained from sexual relations.”
====

[[v9-21-5]]

^<<v9-21-5,5>>^ David answered the priest: “Women have certainly been kept away from us as on previous occasions when I went out on a campaign. If the bodies of the young men are holy even when the mission is ordinary, how much more so today should they be holy!”

[[v9-21-6]]

^<<v9-21-6,6>>^ So the priest gave him the holy bread, because there was no bread there except the showbread, which had been removed from Jehovah’s presence to be replaced by fresh bread on the day it was taken away.

[[v9-21-7]]

^<<v9-21-7,7>>^ Now one of Saul’s servants was there on that day, detained before Jehovah. His name was Doʹeg the Eʹdom·ite, the chief of Saul’s shepherds.

[[v9-21-8]]

^<<v9-21-8,8>>^ David then said to A·himʹe·lech: “Is there a spear or a sword here at your disposal? I did not take my own sword or my weapons with me, because the king’s mission was urgent.”

[[v9-21-9]]

^<<v9-21-9,9>>^ To this the priest said: “The sword of Go·liʹath the Phi·lisʹtine, whom you struck down in the Valley^&#42;1^ of Eʹlah, is here, wrapped up in a cloth behind the ephʹod. If you want to take it for yourself, take it, because it is the only one here.” David said: “There is none like it. Give it to me.”

[NOTE]
====
. Or “Low Plain.”
====

[[v9-21-10]]

^<<v9-21-10,10>>^ That day David rose up and continued his flight from Saul, and he eventually came to King Aʹchish of Gath.

[[v9-21-11]]

^<<v9-21-11,11>>^ The servants of Aʹchish said to him: “Is this not David, the king of the land? Is he not the one they sang about when they danced, saying,
‘Saul has struck down his thousands,
And David his tens of thousands’?”

[[v9-21-12]]

^<<v9-21-12,12>>^ David took these words to heart, and he became very much afraid of King Aʹchish of Gath.

[[v9-21-13]]

^<<v9-21-13,13>>^ So he disguised his sanity in their presence and acted insane while among them.^&#42;1^ He was making marks on the doors of the gate and letting his saliva run down his beard.

[NOTE]
====
. Lit., “in their hand.”
====

[[v9-21-14]]

^<<v9-21-14,14>>^ Finally Aʹchish said to his servants: “You see that this man is crazy! Why bring him to me?

[[v9-21-15]]

^<<v9-21-15,15>>^ Do I have a shortage of crazy men that I need to have this one acting crazy before me? Should this man enter my house?”

'''

xref:009-1-samuel/009-1-samuel-020.adoc#v9-20-0[&#60; Capítulo Anterior] | <<v9-21-0,Topo>> | xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[Próximo Capítulo &#62;]