include::./index.adoc[]

[[v9-23-0]]
=== The First of Samuel, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-23-1]]

^<<v9-23-1,1>>^ In time David was told: “The Phi·lisʹtines are fighting against Keiʹlah, and they are raiding the threshing floors.”

[[v9-23-2]]

^<<v9-23-2,2>>^ So David inquired of Jehovah: “Should I go and strike down these Phi·lisʹtines?” Jehovah said to David: “Go, strike down the Phi·lisʹtines and rescue Keiʹlah.”

[[v9-23-3]]

^<<v9-23-3,3>>^ But the men of David said to him: “Look! We are afraid while here in Judah; how much more so if we go to Keiʹlah against the battle line of the Phi·lisʹtines!”

[[v9-23-4]]

^<<v9-23-4,4>>^ So David inquired once again of Jehovah. Jehovah now answered him: “Rise up; go down to Keiʹlah because I will give the Phi·lisʹtines into your hand.”

[[v9-23-5]]

^<<v9-23-5,5>>^ So David went with his men to Keiʹlah and fought against the Phi·lisʹtines; he carried off their livestock and struck them down with a great slaughter, and David rescued the inhabitants of Keiʹlah.

[[v9-23-6]]

^<<v9-23-6,6>>^ Now when A·biʹa·thar the son of A·himʹe·lech ran away to David at Keiʹlah, he had an ephʹod with him.

[[v9-23-7]]

^<<v9-23-7,7>>^ Saul was told: “David has come to Keiʹlah.” Then Saul said: “God has handed him over to me,^&#42;1^ for he has trapped himself by entering a city with gates and bars.”

[NOTE]
====
. Lit., “sold him into my hand.”
====

[[v9-23-8]]

^<<v9-23-8,8>>^ So Saul summoned all the people to war, to go down to Keiʹlah and besiege David and his men.

[[v9-23-9]]

^<<v9-23-9,9>>^ When David learned that Saul was plotting against him, he said to A·biʹa·thar the priest: “Bring the ephʹod here.”

[[v9-23-10]]

^<<v9-23-10,10>>^ Then David said: “O Jehovah the God of Israel, your servant has indeed heard that Saul intends to come to Keiʹlah to destroy the city because of me.

[[v9-23-11]]

^<<v9-23-11,11>>^ Will the leaders^&#42;1^ of Keiʹlah surrender me into his hand? Will Saul come down as your servant has heard? O Jehovah the God of Israel, please tell your servant.” To this Jehovah said: “He will come down.”

[NOTE]
====
. Or possibly, “landowners.”
====

[[v9-23-12]]

^<<v9-23-12,12>>^ David asked: “Will the leaders of Keiʹlah surrender me and my men into Saul’s hand?” Jehovah replied: “They will surrender you.”

[[v9-23-13]]

^<<v9-23-13,13>>^ At once David rose up with his men, about 600 in number, and they left Keiʹlah and moved about wherever they could. When Saul was told that David had escaped from Keiʹlah, he did not go out after him.

[[v9-23-14]]

^<<v9-23-14,14>>^ David stayed in the wilderness in places difficult to approach, in the mountainous region of the wilderness of Ziph. Saul searched for him constantly, but Jehovah did not give him into his hand.

[[v9-23-15]]

^<<v9-23-15,15>>^ David was aware that^&#42;1^ Saul had gone out to seek his life^&#42;2^ while David was in the wilderness of Ziph at Hoʹresh.

[NOTE]
====
. Or possibly, “was fearful because.”
. Or “soul.”
====

[[v9-23-16]]

^<<v9-23-16,16>>^ Jonʹa·than the son of Saul now went out to David at Hoʹresh, and he helped him find strength^&#42;1^ in Jehovah.

[NOTE]
====
. Lit., “he strengthened his hand.”
====

[[v9-23-17]]

^<<v9-23-17,17>>^ He said to him: “Do not be afraid, for my father Saul will not find you; you will be king over Israel, and I will become second to you; and my father Saul also knows that.”

[[v9-23-18]]

^<<v9-23-18,18>>^ Then the two of them made a covenant before Jehovah, and David stayed in Hoʹresh, and Jonʹa·than went to his home.

[[v9-23-19]]

^<<v9-23-19,19>>^ The men of Ziph later went up to Saul at Gibʹe·ah and said: “Is not David hiding near us in the places difficult to approach at Hoʹresh, on the hill of Hach·iʹlah, which is south^&#42;1^ of Je·shiʹmon?^&#42;2^

[NOTE]
====
. Lit., “on the right side.”
. Or possibly, “the desert; the wilderness.”
====

[[v9-23-20]]

^<<v9-23-20,20>>^ Whenever it pleases you^&#42;1^ to come down, O king, come, and we will surrender him into the hand of the king.”

[NOTE]
====
. Or “your soul.”
====

[[v9-23-21]]

^<<v9-23-21,21>>^ At this Saul said: “May you be blessed by Jehovah, for you have shown compassion to me.

[[v9-23-22]]

^<<v9-23-22,22>>^ Please go and try to find out exactly where he is and who saw him there, for I have been told that he is very cunning.

[[v9-23-23]]

^<<v9-23-23,23>>^ Carefully ascertain where all his hiding places are and return to me with the evidence. I will then go with you, and if he is in the land, I will search him out among all the thousands^&#42;1^ of Judah.”

[NOTE]
====
. Or “clans.”
====

[[v9-23-24]]

^<<v9-23-24,24>>^ So they left and went to Ziph ahead of Saul, while David and his men were in the wilderness of Maʹon, in the Arʹa·bah to the south of Je·shiʹmon.

[[v9-23-25]]

^<<v9-23-25,25>>^ Then Saul came with his men to look for him. When David was told, he at once went down to the crag and stayed in the wilderness of Maʹon. When Saul heard this, he chased after David into the wilderness of Maʹon.

[[v9-23-26]]

^<<v9-23-26,26>>^ As Saul came to one side of the mountain, David and his men were on the other side of the mountain. David was hurrying to get away from Saul, but Saul and his men were closing in on David and his men to capture them.

[[v9-23-27]]

^<<v9-23-27,27>>^ But a messenger came to Saul, saying: “Come quickly, for the Phi·lisʹtines have made a raid on the land!”

[[v9-23-28]]

^<<v9-23-28,28>>^ At that Saul stopped chasing after David and went to confront the Phi·lisʹtines. That is why that place was named the Crag of the Divisions.

[[v9-23-29]]

^<<v9-23-29,29>>^ Then David made his way up from there and stayed in the places difficult to approach at En-gedʹi.

'''

xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[&#60; Capítulo Anterior] | <<v9-23-0,Topo>> | xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[Próximo Capítulo &#62;]