include::./index.adoc[]

[[v9-14-0]]
=== The First of Samuel, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v9-14-1]]

^<<v9-14-1,1>>^ One day Jonʹa·than the son of Saul said to the attendant carrying his weapons: “Come and let us cross over to the Phi·lisʹtine outpost on the other side.” But he did not tell his father.

[[v9-14-2]]

^<<v9-14-2,2>>^ Saul was staying on the outskirts of Gibʹe·ah under the pomegranate tree in Migʹron, and there were about 600 men with him.

[[v9-14-3]]

^<<v9-14-3,3>>^ (And A·hiʹjah the son of A·hiʹtub, the brother of Ichʹa·bod, the son of Phinʹe·has, the son of Eʹli, the priest of Jehovah in Shiʹloh, was carrying the ephʹod.) And the people did not know that Jonʹa·than had gone.

[[v9-14-4]]

^<<v9-14-4,4>>^ Now between the passages that Jonʹa·than was trying to cross over to reach the outpost of the Phi·lisʹtines, there was a toothlike crag on one side and a toothlike crag on the other side; the name of the one was Boʹzez, and the name of the other was Seʹneh.

[[v9-14-5]]

^<<v9-14-5,5>>^ The one crag was a pillar on the north facing Michʹmash, and the other was on the south facing Geʹba.

[[v9-14-6]]

^<<v9-14-6,6>>^ So Jonʹa·than said to his armor-bearer: “Come and let us cross over to the outpost of these uncircumcised men. Perhaps Jehovah will act in our behalf, for nothing can hinder Jehovah from saving by many or by few.”

[[v9-14-7]]

^<<v9-14-7,7>>^ At this his armor-bearer said to him: “Do whatever your heart impels you to do. Turn wherever you wish, and I will follow you wherever your heart impels you.”

[[v9-14-8]]

^<<v9-14-8,8>>^ Then Jonʹa·than said: “We will cross over to those men and reveal our presence to them.

[[v9-14-9]]

^<<v9-14-9,9>>^ If they say to us, ‘Stand still until we come to you!’ we will stand where we are and not go up to them.

[[v9-14-10]]

^<<v9-14-10,10>>^ But if they say, ‘Come up against us!’ we will go up, because Jehovah will give them into our hand. This will be our sign.”

[[v9-14-11]]

^<<v9-14-11,11>>^ Then both of them revealed their presence to the outpost of the Phi·lisʹtines. The Phi·lisʹtines said: “Look! The Hebrews are coming out from the holes where they have been hiding.”

[[v9-14-12]]

^<<v9-14-12,12>>^ So the men of the outpost said to Jonʹa·than and his armor-bearer: “Come up to us, and we will teach you a lesson!” At once Jonʹa·than said to his armor-bearer: “Follow me, for Jehovah will give them into the hand of Israel.”

[[v9-14-13]]

^<<v9-14-13,13>>^ And Jonʹa·than climbed up on his hands and feet, and his armor-bearer was behind him; and the Phi·lisʹtines began to fall before Jonʹa·than, and his armor-bearer was putting them to death behind him.

[[v9-14-14]]

^<<v9-14-14,14>>^ In the first attack that Jonʹa·than and his armor-bearer made, they struck down about 20 men within about half the plowing line in an acre of field.^&#42;1^

[NOTE]
====
. Lit., “a span of a field,” that is, the measure of land that a span of bulls can plow in a day.
====

[[v9-14-15]]

^<<v9-14-15,15>>^ Then terror spread in the field camp and among all the people of the outpost, and even the raiding parties were terrified. The earth began quaking, and a terror from God ensued.

[[v9-14-16]]

^<<v9-14-16,16>>^ Saul’s watchmen in Gibʹe·ah of Benjamin saw that the turmoil was spreading in every direction.

[[v9-14-17]]

^<<v9-14-17,17>>^ Saul said to the people with him: “Take a count, please, and see who has left us.” When they took the count, they saw that Jonʹa·than and his armor-bearer were not there.

[[v9-14-18]]

^<<v9-14-18,18>>^ Saul now said to A·hiʹjah: “Bring the Ark of the true God near!” (For the Ark of the true God was with the Israelites at that time.^&#42;1^)

[NOTE]
====
. Lit., “on that day.”
====

[[v9-14-19]]

^<<v9-14-19,19>>^ And while Saul was speaking to the priest, the turmoil in the camp of the Phi·lisʹtines was growing greater and greater. Then Saul said to the priest: “Stop what you are doing.”^&#42;1^

[NOTE]
====
. Lit., “Withdraw your hand.”
====

[[v9-14-20]]

^<<v9-14-20,20>>^ So Saul and all the people with him assembled and went into the battle, where they found that the Phi·lisʹtines had turned their swords against one another, and the confusion was very great.

[[v9-14-21]]

^<<v9-14-21,21>>^ Also, the Hebrews who had previously sided with the Phi·lisʹtines and who had come up with them into the camp were going over to Israel under Saul and Jonʹa·than.

[[v9-14-22]]

^<<v9-14-22,22>>^ All the men of Israel who had hidden in the mountainous region of Eʹphra·im heard that the Phi·lisʹtines had fled, and they too joined in pursuing them in the battle.

[[v9-14-23]]

^<<v9-14-23,23>>^ So Jehovah saved Israel on that day, and the battle extended as far as Beth-aʹven.

[[v9-14-24]]

^<<v9-14-24,24>>^ But the men of Israel were hard-pressed on that day, for Saul had put the people under this oath: “Cursed is the man who eats any food^&#42;1^ before the evening and until I have taken vengeance on my enemies!” So none of the people ate any food.

[NOTE]
====
. Lit., “bread.”
====

[[v9-14-25]]

^<<v9-14-25,25>>^ And all the people^&#42;1^ came into the forest, and there was honey on the ground.

[NOTE]
====
. Lit., “land.”
====

[[v9-14-26]]

^<<v9-14-26,26>>^ When the people came into the forest, they saw the honey dripping, but no one would put his hand to his mouth, because they feared the oath.

[[v9-14-27]]

^<<v9-14-27,27>>^ But Jonʹa·than had not heard his father put the people under an oath, so he stretched out the tip of the staff that was in his hand and dipped it into the honeycomb. When he drew his hand back to his mouth, his eyes brightened.

[[v9-14-28]]

^<<v9-14-28,28>>^ At this one of the people said: “Your father put the people under a strict oath, saying, ‘Cursed is the man who eats food today!’ That is why the people are so tired.”

[[v9-14-29]]

^<<v9-14-29,29>>^ However, Jonʹa·than said: “My father has brought great trouble^&#42;1^ on the land. Look at how my eyes brightened because I tasted this little bit of honey.

[NOTE]
====
. Or “brought ostracism.”
====

[[v9-14-30]]

^<<v9-14-30,30>>^ How much better if the people had eaten freely today from the spoil of their enemies that they found! For then the slaughter of the Phi·lisʹtines would have been even greater.”

[[v9-14-31]]

^<<v9-14-31,31>>^ On that day they kept striking down the Phi·lisʹtines from Michʹmash to Aiʹja·lon, and the people became very tired.

[[v9-14-32]]

^<<v9-14-32,32>>^ So the people began rushing greedily at the spoil, and they took sheep and cattle and calves and slaughtered them on the ground, and they ate the meat along with the blood.

[[v9-14-33]]

^<<v9-14-33,33>>^ So it was reported to Saul: “Look! The people are sinning against Jehovah by eating meat with the blood.” At this he said: “You have acted faithlessly. Roll a large stone to me immediately.”

[[v9-14-34]]

^<<v9-14-34,34>>^ Saul then said: “Spread out among the people and say to them, ‘Each of you must bring his bull and his sheep and slaughter them here and then eat them. Do not sin against Jehovah by eating meat with the blood.’” So each of them brought his bull with him that night and slaughtered it there.

[[v9-14-35]]

^<<v9-14-35,35>>^ And Saul built an altar to Jehovah. This was the first altar he built to Jehovah.

[[v9-14-36]]

^<<v9-14-36,36>>^ Saul later said: “Let us go down after the Phi·lisʹtines by night and plunder them until the morning light. We will not leave a single survivor.” To this they said: “Do whatever seems good in your eyes.” Then the priest said: “Let us approach the true God here.”

[[v9-14-37]]

^<<v9-14-37,37>>^ And Saul inquired of God: “Should I go down after the Phi·lisʹtines? Will you give them into the hand of Israel?” But God did not answer him on that day.

[[v9-14-38]]

^<<v9-14-38,38>>^ So Saul said: “Come here, all you chiefs of the people, and find out what sin has been committed today.

[[v9-14-39]]

^<<v9-14-39,39>>^ For as surely as Jehovah is alive, who rescued Israel, even if it turns out to be Jonʹa·than my son, he must die.” But none of the people would answer him.

[[v9-14-40]]

^<<v9-14-40,40>>^ Then he said to all Israel: “You will be on one side, and my son Jonʹa·than and I will be on the other side.” At this the people said to Saul: “Do whatever seems good in your eyes.”

[[v9-14-41]]

^<<v9-14-41,41>>^ Saul then said to Jehovah: “O God of Israel, answer with the Thumʹmim!” Then Jonʹa·than and Saul were selected, and the people went free.

[[v9-14-42]]

^<<v9-14-42,42>>^ Saul now said: “Cast lots to decide between me and my son Jonʹa·than.” And Jonʹa·than was selected.

[[v9-14-43]]

^<<v9-14-43,43>>^ Then Saul said to Jonʹa·than: “Tell me, what have you done?” So Jonʹa·than told him: “I merely tasted a little honey on the tip of the staff in my hand. Here I am! I am ready to die!”

[[v9-14-44]]

^<<v9-14-44,44>>^ At this Saul said: “Thus may God do and may he add to it if you do not die, Jonʹa·than.”

[[v9-14-45]]

^<<v9-14-45,45>>^ But the people said to Saul: “Should Jonʹa·than die—the one who brought this great victory^&#42;1^ to Israel? It is unthinkable! As surely as Jehovah is alive, not even a single hair of his head should fall to the ground, for it was with God that he acted this day.” With that the people rescued^&#42;2^ Jonʹa·than, and he did not die.

[NOTE]
====
. Or “salvation.”
. Lit., “redeemed.”
====

[[v9-14-46]]

^<<v9-14-46,46>>^ So Saul stopped pursuing the Phi·lisʹtines, and the Phi·lisʹtines went to their own territory.

[[v9-14-47]]

^<<v9-14-47,47>>^ Saul secured the kingship over Israel and fought against all his enemies on every side, against the Moʹab·ites, the Amʹmon·ites, the Eʹdom·ites, the kings of Zoʹbah, and the Phi·lisʹtines; and wherever he went he defeated them.

[[v9-14-48]]

^<<v9-14-48,48>>^ And he fought bravely and conquered the A·malʹek·ites and rescued Israel from the hand of their plunderers.

[[v9-14-49]]

^<<v9-14-49,49>>^ The sons of Saul were Jonʹa·than, Ishʹvi, and Malʹchi-shuʹa. And he had two daughters; the name of the older one was Meʹrab, and the name of the younger one, Miʹchal.

[[v9-14-50]]

^<<v9-14-50,50>>^ The name of Saul’s wife was A·hinʹo·am the daughter of A·himʹa·az. The name of the chief of his army was Abʹner the son of Ner, the uncle of Saul.

[[v9-14-51]]

^<<v9-14-51,51>>^ Kish was the father of Saul, and Ner the father of Abʹner was the son of A·biʹel.

[[v9-14-52]]

^<<v9-14-52,52>>^ There was fierce warfare with the Phi·lisʹtines all the days of Saul. When Saul saw any strong or courageous man, he would recruit him into his service.

'''

xref:009-1-samuel/009-1-samuel-013.adoc#v9-13-0[&#60; Capítulo Anterior] | <<v9-14-0,Topo>> | xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[Próximo Capítulo &#62;]