include::./index.adoc[]

[[v17-7-0]]
=== Esther, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v17-7-1]]

^<<v17-7-1,1>>^ So the king and Haʹman came in to Queen Esther’s banquet.

[[v17-7-2]]

^<<v17-7-2,2>>^ The king said to Esther again on the second day during the banquet of wine: “What is your petition, Queen Esther? It will be granted you. And what is your request? Even to^&#42;1^ the half of my kingdom, it will be done!”

[NOTE]
====
. Or “for.”
====

[[v17-7-3]]

^<<v17-7-3,3>>^ Queen Esther answered: “If I have found favor with you, O king, and if it pleases the king, let my life^&#42;1^ be granted as my petition, and my people as my request.

[NOTE]
====
. Or “soul.”
====

[[v17-7-4]]

^<<v17-7-4,4>>^ For we have been sold, I and my people, to be annihilated, killed, and destroyed. If we had simply been sold as male and female slaves, I would have kept silent. But the distress is not proper, for it will be damaging to the king.”

[[v17-7-5]]

^<<v17-7-5,5>>^ King A·has·u·eʹrus then said to Queen Esther: “Who is this, and where is the man who has dared to do such a thing?”

[[v17-7-6]]

^<<v17-7-6,6>>^ Esther said: “The adversary and enemy is this evil Haʹman.”
Haʹman became terrified because of the king and the queen.

[[v17-7-7]]

^<<v17-7-7,7>>^ The king rose up in a rage from the banquet of wine and went into the palace garden, but Haʹman stood up to plead with Queen Esther for his life,^&#42;1^ for he realized that the king was determined to punish him.

[NOTE]
====
. Or “soul.”
====

[[v17-7-8]]

^<<v17-7-8,8>>^ The king returned from the palace garden to the house of the wine banquet and saw that Haʹman had thrown himself on the couch where Esther was. The king exclaimed: “Is he also going to rape the queen in my own house?” As soon as these words left the king’s mouth, they covered Haʹman’s face.

[[v17-7-9]]

^<<v17-7-9,9>>^ Har·boʹna, one of the king’s court officials, now said: “Haʹman also prepared a stake for Morʹde·cai, whose report saved the king. It is standing at Haʹman’s house, 50 cubits^&#42;1^ high.” At that the king said: “Hang him on it.”

[NOTE]
====
. About 22.3 m (73 ft). See App. B14.
====

[[v17-7-10]]

^<<v17-7-10,10>>^ So they hanged Haʹman on the stake that he had prepared for Morʹde·cai, and the king’s rage subsided.

'''

xref:017-esther/017-esther-006.adoc#v17-6-0[&#60; Capítulo Anterior] | <<v17-7-0,Topo>> | xref:017-esther/017-esther-008.adoc#v17-8-0[Próximo Capítulo &#62;]