include::./index.adoc[]

[[v17-3-0]]
=== Esther, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v17-3-1]]

^<<v17-3-1,1>>^ After this King A·has·u·eʹrus promoted Haʹman the son of Ham·me·daʹtha the Agʹag·ite and exalted him by putting his throne above all the other princes who were with him.

[[v17-3-2]]

^<<v17-3-2,2>>^ And all the king’s servants who were in the king’s gate would bow low and prostrate themselves to Haʹman, for this is what the king had commanded respecting him. But Morʹde·cai refused to bow low or prostrate himself.

[[v17-3-3]]

^<<v17-3-3,3>>^ So the king’s servants who were in the king’s gate said to Morʹde·cai: “Why are you ignoring the king’s commandment?”

[[v17-3-4]]

^<<v17-3-4,4>>^ Day after day they would ask him, but he would not listen to them. Then they told Haʹman to see whether Morʹde·cai’s conduct would be tolerated; for he had told them that he was a Jew.

[[v17-3-5]]

^<<v17-3-5,5>>^ Now when Haʹman saw that Morʹde·cai refused to bow low and prostrate himself to him, Haʹman became filled with rage.

[[v17-3-6]]

^<<v17-3-6,6>>^ But he despised the thought of doing away with^&#42;1^ Morʹde·cai alone, for they had told him about Morʹde·cai’s people. So Haʹman began seeking to annihilate all the Jews who were in the entire realm of A·has·u·eʹrus, all of Morʹde·cai’s people.

[NOTE]
====
. Lit., “laying a hand on.”
====

[[v17-3-7]]

^<<v17-3-7,7>>^ In the first month, that is, the month of Niʹsan,^&#42;1^ in the 12th year of King A·has·u·eʹrus, they cast Pur (that is, the Lot) before Haʹman to determine the day and the month, and it fell on the 12th month, that is, Aʹdar.^&#42;2^

[NOTE]
====
. See App. B15.
. See App. B15.
====

[[v17-3-8]]

^<<v17-3-8,8>>^ Haʹman then said to King A·has·u·eʹrus: “There is a certain people scattered and dispersed among the peoples in all the provinces^&#42;1^ of your realm, whose laws are different from those of all other peoples; and they do not obey the king’s laws, and it is not in the king’s interests to let them be.

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v17-3-9]]

^<<v17-3-9,9>>^ If it pleases the king, let a decree be written that they be destroyed. I will pay 10,000 silver talents^&#42;1^ to the officials to put into the royal treasury.”^&#42;2^

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
. Or possibly, “I will pay 10,000 talents into the royal treasury for those who carry out this work.”
====

[[v17-3-10]]

^<<v17-3-10,10>>^ At that the king removed his signet ring from his own hand and gave it to Haʹman the son of Ham·me·daʹtha the Agʹag·ite, who was the enemy of the Jews.

[[v17-3-11]]

^<<v17-3-11,11>>^ The king said to Haʹman: “The silver and the people are given to you, to do with them as you see fit.”

[[v17-3-12]]

^<<v17-3-12,12>>^ The king’s secretaries were then called on the 13th day of the first month. They put in writing all of Haʹman’s orders to the king’s satraps, the governors who were over the provinces,^&#42;1^ and the princes of the different peoples, to each province^&#42;2^ in its own script^&#42;3^ and to each people in its own language. It was written in the name of King A·has·u·eʹrus and sealed with the king’s signet ring.

[NOTE]
====
. Or “jurisdictional districts.”
. Or “jurisdictional district.”
. Or “style of writing.”
====

[[v17-3-13]]

^<<v17-3-13,13>>^ The letters were sent by means of couriers to all the king’s provinces,^&#42;1^ giving the order to annihilate, to kill, and to destroy all the Jews, young and old alike, children and women, on a single day, on the 13th day of the 12th month, that is, the month of Aʹdar, and to seize their possessions.

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v17-3-14]]

^<<v17-3-14,14>>^ A copy of the document was to be issued as a law in every province^&#42;1^ and proclaimed to all the peoples, so that they would be prepared for that day.

[NOTE]
====
. Or “jurisdictional district.”
====

[[v17-3-15]]

^<<v17-3-15,15>>^ The couriers went out quickly by order of the king; the law was issued in Shuʹshan^&#42;1^ the citadel.^&#42;2^ The king and Haʹman then sat down to drink, but the city of Shuʹshan^&#42;3^ was in confusion.

[NOTE]
====
. Or “Susa.”
. Or “palace; fortress.”
. Or “Susa.”
====

'''

xref:017-esther/017-esther-002.adoc#v17-2-0[&#60; Capítulo Anterior] | <<v17-3-0,Topo>> | xref:017-esther/017-esther-004.adoc#v17-4-0[Próximo Capítulo &#62;]