include::./index.adoc[]

[[v17-2-0]]
=== Esther, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v17-2-1]]

^<<v17-2-1,1>>^ After these things, when the rage of King A·has·u·eʹrus had subsided, he remembered what Vashʹti had done and what had been decided against her.

[[v17-2-2]]

^<<v17-2-2,2>>^ Then the king’s personal attendants said: “A search should be made for young, beautiful virgins for the king.

[[v17-2-3]]

^<<v17-2-3,3>>^ And let the king appoint commissioners in all the provinces^&#42;1^ of his realm to bring together all the beautiful young virgins to Shuʹshan^&#42;2^ the citadel,^&#42;3^ to the house of the women.^&#42;4^ Let them be put in the care of Hegʹa·i the king’s eunuch and guardian of the women, and let them be given beauty treatments.^&#42;5^

[NOTE]
====
. Or “jurisdictional districts.”
. Or “Susa.”
. Or “palace; fortress.”
. Or “to the harem.”
. Or “be given massages.”
====

[[v17-2-4]]

^<<v17-2-4,4>>^ And the young woman who is most pleasing to the king will be queen instead of Vashʹti.” The suggestion was pleasing to the king, and that is what he did.

[[v17-2-5]]

^<<v17-2-5,5>>^ There was a certain Jewish man in Shuʹshan^&#42;1^ the citadel^&#42;2^ whose name was Morʹde·cai son of Jaʹir son of Shimʹe·i son of Kish, a Benʹja·min·ite,

[NOTE]
====
. Or “Susa.”
. Or “palace; fortress.”
====

[[v17-2-6]]

^<<v17-2-6,6>>^ who had been taken into exile from Jerusalem with the people who were deported with King Jec·o·niʹah^&#42;1^ of Judah, whom King Neb·u·chad·nezʹzar of Babylon took into exile.

[NOTE]
====
. Called Jehoiachin at 2Ki 24:8.
====

[[v17-2-7]]

^<<v17-2-7,7>>^ He was the guardian^&#42;1^ of Ha·dasʹsah,^&#42;2^ that is, Esther, the daughter of his father’s brother, for she had neither father nor mother. The young woman was beautifully formed and attractive in appearance, and at the death of her father and her mother, Morʹde·cai took her as his daughter.

[NOTE]
====
. Or “caretaker.”
. Meaning “Myrtle.”
====

[[v17-2-8]]

^<<v17-2-8,8>>^ When the king’s word and his law were proclaimed and when many young women were brought together at Shuʹshan^&#42;1^ the citadel^&#42;2^ under the care of Hegʹa·i, Esther was also taken to the king’s house^&#42;3^ under the care of Hegʹa·i the guardian of the women.

[NOTE]
====
. Or “Susa.”
. Or “palace; fortress.”
. Or “palace.”
====

[[v17-2-9]]

^<<v17-2-9,9>>^ Now the young woman was pleasing to him and won his favor,^&#42;1^ so he promptly arranged for her beauty treatments^&#42;2^ and her diet, and he assigned to her seven selected young women from the king’s house. He also transferred her and her young attendants to the best place in the house of the women.^&#42;3^

[NOTE]
====
. Or “loyal love.”
. Or “her massages.”
. Or “in the harem.”
====

[[v17-2-10]]

^<<v17-2-10,10>>^ Esther did not say anything about her people or her relatives, for Morʹde·cai had instructed her not to tell anyone.

[[v17-2-11]]

^<<v17-2-11,11>>^ Day after day Morʹde·cai would walk in front of the courtyard of the house of the women^&#42;1^ to learn about Esther’s welfare and about what was happening to her.

[NOTE]
====
. Or “of the harem.”
====

[[v17-2-12]]

^<<v17-2-12,12>>^ Each young woman had her turn to go in to King A·has·u·eʹrus after completing the 12-month treatment that was prescribed for the women, for this was the way they had to fulfill their beauty treatment^&#42;1^—six months with oil of myrrh and six months with balsam oil and various ointments for beauty treatment.^&#42;2^

[NOTE]
====
. Or “their massages.”
. Or “and with massages of the women.”
====

[[v17-2-13]]

^<<v17-2-13,13>>^ Then the young woman was ready to go in to the king, and whatever she asked for would be given her when she went from the house of the women^&#42;1^ to the king’s house.

[NOTE]
====
. Or “from the harem.”
====

[[v17-2-14]]

^<<v17-2-14,14>>^ In the evening she would go in, and in the morning she would return to the second house of the women,^&#42;1^ under the care of Sha·ashʹgaz the king’s eunuch, the guardian of the concubines. She would not go to the king again unless the king had been especially pleased with her and she was requested by name.

[NOTE]
====
. Or “the second harem.”
====

[[v17-2-15]]

^<<v17-2-15,15>>^ And when the turn came for Esther the daughter of Abʹi·ha·il the uncle of Morʹde·cai, who had taken her as his daughter, to go in to the king, she did not request anything except what Hegʹa·i the king’s eunuch, the guardian of the women, recommended. (All the while Esther was winning the favor of everyone who saw her.)

[[v17-2-16]]

^<<v17-2-16,16>>^ Esther was taken to King A·has·u·eʹrus at his royal house in the tenth month, that is, the month of Teʹbeth,^&#42;1^ in the seventh year of his reign.

[NOTE]
====
. See App. B15.
====

[[v17-2-17]]

^<<v17-2-17,17>>^ And the king came to love Esther more than all the other women, and she won his favor and approval^&#42;1^ more than any of the other virgins. So he put the royal headdress^&#42;2^ on her head and made her queen instead of Vashʹti.

[NOTE]
====
. Or “loyal love.”
. Or “turban.”
====

[[v17-2-18]]

^<<v17-2-18,18>>^ And the king held a great banquet for all his princes and his servants, the banquet of Esther. He then proclaimed an amnesty for the provinces,^&#42;1^ and he kept giving gifts according to the means of the king.

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v17-2-19]]

^<<v17-2-19,19>>^ Now when virgins^&#42;1^ were brought together a second time, Morʹde·cai was sitting in the king’s gate.

[NOTE]
====
. Or “young women.”
====

[[v17-2-20]]

^<<v17-2-20,20>>^ Esther did not say anything about her relatives and her people, just as Morʹde·cai had instructed her; Esther continued to do what Morʹde·cai said, just as when she was under his care.

[[v17-2-21]]

^<<v17-2-21,21>>^ In those days while Morʹde·cai was sitting in the king’s gate, Bigʹthan and Teʹresh, two court officials of the king, doorkeepers, got angry and plotted to do away with^&#42;1^ King A·has·u·eʹrus.

[NOTE]
====
. Lit., “to lay hand on.”
====

[[v17-2-22]]

^<<v17-2-22,22>>^ But Morʹde·cai learned about it, and he immediately told Queen Esther. Esther then spoke to the king in Morʹde·cai’s name.^&#42;1^

[NOTE]
====
. Or “on behalf of Mordecai.”
====

[[v17-2-23]]

^<<v17-2-23,23>>^ So the matter was investigated and eventually confirmed, and both men were hanged on a stake; and this was all recorded in the book of the history of the times in the presence of the king.

'''

xref:017-esther/017-esther-001.adoc#v17-1-0[&#60; Capítulo Anterior] | <<v17-2-0,Topo>> | xref:017-esther/017-esther-003.adoc#v17-3-0[Próximo Capítulo &#62;]