include::./index.adoc[]

[[v17-5-0]]
=== Esther, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v17-5-1]]

^<<v17-5-1,1>>^ On the third day Esther put on her royal robes and stood in the inner courtyard of the king’s house,^&#42;1^ opposite the king’s house, while the king was sitting on his royal throne in the royal house opposite the entrance.

[NOTE]
====
. Or “palace.”
====

[[v17-5-2]]

^<<v17-5-2,2>>^ As soon as the king saw Queen Esther standing in the courtyard, she gained his favor, and the king held out to Esther the golden scepter that was in his hand. Esther then approached and touched the top of the scepter.

[[v17-5-3]]

^<<v17-5-3,3>>^ The king asked her: “What is the matter, Queen Esther? What is your request? Even to^&#42;1^ the half of my kingdom, it will be granted you!”

[NOTE]
====
. Or “for.”
====

[[v17-5-4]]

^<<v17-5-4,4>>^ Esther replied: “If it pleases the king, let the king along with Haʹman come today to the banquet that I have prepared for him.”

[[v17-5-5]]

^<<v17-5-5,5>>^ So the king said to his men: “Tell Haʹman to come quickly, as Esther requests.” So the king and Haʹman went to the banquet that Esther had prepared.

[[v17-5-6]]

^<<v17-5-6,6>>^ During the banquet of wine, the king said to Esther: “What is your petition? It will be granted you! And what is your request? Even to^&#42;1^ the half of my kingdom, it will be done!”

[NOTE]
====
. Or “for.”
====

[[v17-5-7]]

^<<v17-5-7,7>>^ Esther answered: “My petition and my request is,

[[v17-5-8]]

^<<v17-5-8,8>>^ If I have found favor with the king and if it pleases the king to grant my petition and to act on my request, let the king and Haʹman come to the banquet that I will hold for them tomorrow; and tomorrow I will do as the king says.”

[[v17-5-9]]

^<<v17-5-9,9>>^ On that day Haʹman went out joyful and with a cheerful heart. But when Haʹman saw Morʹde·cai in the king’s gate and noticed that he did not rise and tremble in his presence, Haʹman was filled with rage against Morʹde·cai.

[[v17-5-10]]

^<<v17-5-10,10>>^ However, Haʹman restrained himself and went to his house. Then he sent for his friends and Zeʹresh his wife.

[[v17-5-11]]

^<<v17-5-11,11>>^ Haʹman boasted about his glorious wealth, his many sons, and how the king had promoted him and had exalted him over the princes and the servants of the king.

[[v17-5-12]]

^<<v17-5-12,12>>^ Haʹman added: “What is more, Queen Esther invited no one else but me to accompany the king to the banquet she prepared. I am also invited tomorrow to be with her and the king.

[[v17-5-13]]

^<<v17-5-13,13>>^ But all of this fails to satisfy me as long as I see Morʹde·cai the Jew sitting in the king’s gate.”

[[v17-5-14]]

^<<v17-5-14,14>>^ So Zeʹresh his wife and all his friends said to him: “Have a stake put up, 50 cubits^&#42;1^ high. And in the morning tell the king that Morʹde·cai should be hanged on it. Then go with the king to enjoy yourself at the banquet.” This suggestion seemed good to Haʹman, so he had the stake put up.

[NOTE]
====
. About 22.3 m (73 ft). See App. B14.
====

'''

xref:017-esther/017-esther-004.adoc#v17-4-0[&#60; Capítulo Anterior] | <<v17-5-0,Topo>> | xref:017-esther/017-esther-006.adoc#v17-6-0[Próximo Capítulo &#62;]