include::./index.adoc[]

[[v17-9-0]]
=== Esther, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v17-9-1]]

^<<v17-9-1,1>>^ On the 13th day of the 12th month, that is, the month of Aʹdar,^&#42;1^ when the king’s word and his law were to be carried out, on the day when the enemies of the Jews hoped to overpower them, the opposite happened, and the Jews defeated those who hated them.

[NOTE]
====
. See App. B15.
====

[[v17-9-2]]

^<<v17-9-2,2>>^ The Jews gathered together in their cities in all the provinces^&#42;1^ of King A·has·u·eʹrus to lay hands on those seeking to harm them, and not a man could stand against them, for the dread of them had fallen upon all the peoples.

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v17-9-3]]

^<<v17-9-3,3>>^ And all the princes of the provinces,^&#42;1^ the satraps, the governors, and those handling the business of the king were supporting the Jews, for they were in fear of Morʹde·cai.

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v17-9-4]]

^<<v17-9-4,4>>^ Morʹde·cai had become powerful in the king’s house,^&#42;1^ and his fame was spreading throughout all the provinces,^&#42;2^ because Morʹde·cai was steadily growing more powerful.

[NOTE]
====
. Or “palace.”
. Or “jurisdictional districts.”
====

[[v17-9-5]]

^<<v17-9-5,5>>^ The Jews struck down all their enemies with the sword, killing and destroying them; they did whatever they wanted to those hating them.

[[v17-9-6]]

^<<v17-9-6,6>>^ In Shuʹshan^&#42;1^ the citadel^&#42;2^ the Jews killed and destroyed 500 men.

[NOTE]
====
. Or “Susa.”
. Or “palace; fortress.”
====

[[v17-9-7]]

^<<v17-9-7,7>>^ Also, they killed Par·shan·daʹtha, Dalʹphon, As·paʹtha,

[[v17-9-8]]

^<<v17-9-8,8>>^ Po·raʹtha, A·daʹli·a, A·ri·daʹtha,

[[v17-9-9]]

^<<v17-9-9,9>>^ Par·mashʹta, Arʹi·sai, Arʹi·dai, and Vai·zaʹtha,

[[v17-9-10]]

^<<v17-9-10,10>>^ the ten sons of Haʹman the son of Ham·me·daʹtha, the enemy of the Jews. But after they killed them, they did not seize any plunder.

[[v17-9-11]]

^<<v17-9-11,11>>^ On that day the number of those killed in Shuʹshan^&#42;1^ the citadel^&#42;2^ was reported to the king.

[NOTE]
====
. Or “Susa.”
. Or “palace; fortress.”
====

[[v17-9-12]]

^<<v17-9-12,12>>^ The king said to Queen Esther: “In Shuʹshan^&#42;1^ the citadel^&#42;2^ the Jews have killed and destroyed 500 men and the ten sons of Haʹman. What, then, have they done in the rest of the king’s provinces?^&#42;3^ What is your petition now? It will be granted you. And what is your further request? It will be done.”

[NOTE]
====
. Or “Susa.”
. Or “palace; fortress.”
. Or “jurisdictional districts.”
====

[[v17-9-13]]

^<<v17-9-13,13>>^ Esther replied: “If it pleases the king, let the Jews who are in Shuʹshan^&#42;1^ be permitted to act tomorrow also according to today’s law; and let the ten sons of Haʹman be hanged on the stake.”

[NOTE]
====
. Or “Susa.”
====

[[v17-9-14]]

^<<v17-9-14,14>>^ So the king gave orders for that to be done. A law was issued in Shuʹshan,^&#42;1^ and the ten sons of Haʹman were hanged.

[NOTE]
====
. Or “Susa.”
====

[[v17-9-15]]

^<<v17-9-15,15>>^ The Jews in Shuʹshan^&#42;1^ gathered together again on the 14th day of the month of Aʹdar and killed 300 men in Shuʹshan,^&#42;2^ but they did not seize any plunder.

[NOTE]
====
. Or “Susa.”
. Or “Susa.”
====

[[v17-9-16]]

^<<v17-9-16,16>>^ The rest of the Jews in the provinces^&#42;1^ of the king also gathered together and defended their lives.^&#42;2^ They got rid of their enemies, killing 75,000 of those who hated them; but they did not seize any plunder.

[NOTE]
====
. Or “jurisdictional districts.”
. Or “stood up for their souls.”
====

[[v17-9-17]]

^<<v17-9-17,17>>^ That was on the 13th day of the month of Aʹdar, and they rested on the 14th day and made it a day of feasting and of rejoicing.

[[v17-9-18]]

^<<v17-9-18,18>>^ The Jews in Shuʹshan^&#42;1^ gathered together on the 13th day and on the 14th day, and they rested on the 15th day and made it a day of feasting and rejoicing.

[NOTE]
====
. Or “Susa.”
====

[[v17-9-19]]

^<<v17-9-19,19>>^ That is why the rural Jews inhabiting the cities of the outlying districts made the 14th day of the month of Aʹdar a day of rejoicing and feasting, a day of celebration, and a time to send portions of food to one another.

[[v17-9-20]]

^<<v17-9-20,20>>^ Morʹde·cai recorded these events and sent official letters to all the Jews in all the provinces^&#42;1^ of King A·has·u·eʹrus, both near and far.

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v17-9-21]]

^<<v17-9-21,21>>^ He instructed them to observe the 14th day of the month of Aʹdar, as well as the 15th day, each and every year,

[[v17-9-22]]

^<<v17-9-22,22>>^ because on those days the Jews rested from their enemies and in that month their grief was changed to rejoicing and their mourning to a day of celebration. They were to observe them as days of feasting and rejoicing and as a time to send portions of food to one another and gifts to the poor.

[[v17-9-23]]

^<<v17-9-23,23>>^ And the Jews agreed to continue the celebration that they had started and to do what Morʹde·cai wrote to them.

[[v17-9-24]]

^<<v17-9-24,24>>^ For Haʹman the son of Ham·me·daʹtha the Agʹag·ite, the enemy of all the Jews, had schemed against the Jews to destroy them, and he had cast Pur, that is, the Lot, to throw them into a panic and to destroy them.

[[v17-9-25]]

^<<v17-9-25,25>>^ But when Esther came in before the king, he gave orders in writing: “Let his evil scheme against the Jews come back on his own head”; and they hanged him and his sons on the stake.

[[v17-9-26]]

^<<v17-9-26,26>>^ That is why they called these days Puʹrim, after the name of the Pur.^&#42;1^ Therefore, because of all that was written in this letter and what they saw concerning this matter and what had come upon them,

[NOTE]
====
. “Pur,” meaning “Lot.” The plural form “Purim” came to designate the Jewish festival celebrated in the 12th month of the sacred calendar. See App. B15.
====

[[v17-9-27]]

^<<v17-9-27,27>>^ the Jews obligated themselves and their descendants and all those joining them to celebrate these two days without fail and to carry out what was written concerning them at the appointed time each and every year.

[[v17-9-28]]

^<<v17-9-28,28>>^ These days were to be remembered and observed in every generation, by each family, each province,^&#42;1^ and each city; and these days of Puʹrim should not cease among the Jews, and their commemoration should not come to an end among their descendants.

[NOTE]
====
. Or “jurisdictional district.”
====

[[v17-9-29]]

^<<v17-9-29,29>>^ Then Queen Esther, the daughter of Abʹi·ha·il, and Morʹde·cai the Jew wrote with full authority to confirm a second letter about Puʹrim.

[[v17-9-30]]

^<<v17-9-30,30>>^ He sent official letters to all the Jews in the 127 provinces,^&#42;1^ the realm of A·has·u·eʹrus, in words of peace and truth

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v17-9-31]]

^<<v17-9-31,31>>^ to confirm the observance of the days of Puʹrim at their appointed times, just as Morʹde·cai the Jew and Queen Esther had instructed them to do and just as they had obligated themselves^&#42;1^ and their descendants to carry out, including the fasting and supplication.

[NOTE]
====
. Or “had imposed upon their soul.”
====

[[v17-9-32]]

^<<v17-9-32,32>>^ And the command of Esther confirmed these matters concerning Puʹrim, and it was recorded in a book.

'''

xref:017-esther/017-esther-008.adoc#v17-8-0[&#60; Capítulo Anterior] | <<v17-9-0,Topo>> | xref:017-esther/017-esther-010.adoc#v17-10-0[Próximo Capítulo &#62;]