include::./index.adoc[]

[[v17-1-0]]
=== Esther, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v17-1-1]]

^<<v17-1-1,1>>^ Now in the days of A·has·u·eʹrus,^&#42;1^ that is, the A·has·u·eʹrus who ruled over 127 provinces^&#42;2^ from Inʹdi·a to E·thi·oʹpi·a,^&#42;3^

[NOTE]
====
. Understood to be Xerxes I, son of Darius the Great (Darius Hystaspis).
. Or “jurisdictional districts.”
. Or “Cush.”
====

[[v17-1-2]]

^<<v17-1-2,2>>^ in those days when King A·has·u·eʹrus was sitting on his royal throne in Shuʹshan^&#42;1^ the citadel,^&#42;2^

[NOTE]
====
. Or “Susa.”
. Or “palace; fortress.”
====

[[v17-1-3]]

^<<v17-1-3,3>>^ in the third year of his reign, he held a banquet for all his princes and his servants. The army of Persia and Meʹdi·a, the nobles, and the princes of the provinces^&#42;1^ were before him,

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v17-1-4]]

^<<v17-1-4,4>>^ and he showed them the wealth of his glorious kingdom and the grandeur and the splendor of his magnificence for many days, 180 days.

[[v17-1-5]]

^<<v17-1-5,5>>^ And when these days were completed, the king held a banquet for seven days for all the people present in Shuʹshan^&#42;1^ the citadel,^&#42;2^ from the greatest to the least, in the courtyard of the garden of the king’s palace.

[NOTE]
====
. Or “Susa.”
. Or “palace; fortress.”
====

[[v17-1-6]]

^<<v17-1-6,6>>^ There were linen, fine cotton, and blue material held fast in ropes of fine fabric, purple wool in silver rings, pillars of marble, and couches of gold and silver on a pavement of porphyry, marble, pearl, and black marble.

[[v17-1-7]]

^<<v17-1-7,7>>^ Wine was served in gold cups;^&#42;1^ each cup was different from the other, and the royal wine was plentiful, according to the means of the king.

[NOTE]
====
. Or “vessels; goblets.”
====

[[v17-1-8]]

^<<v17-1-8,8>>^ The drinking was according to the rule that no one was under compulsion,^&#42;1^ for the king had arranged with the officials of his palace that each should do as he pleased.

[NOTE]
====
. Or “restriction.”
====

[[v17-1-9]]

^<<v17-1-9,9>>^ Queen Vashʹti also held a banquet for the women at the royal house^&#42;1^ of King A·has·u·eʹrus.

[NOTE]
====
. Or “palace.”
====

[[v17-1-10]]

^<<v17-1-10,10>>^ On the seventh day, when the king’s heart was in a cheerful mood because of the wine, he told Me·huʹman, Bizʹtha, Har·boʹna, Bigʹtha, A·bagʹtha, Zeʹthar, and Carʹkas, the seven court officials who were personal attendants to King A·has·u·eʹrus,

[[v17-1-11]]

^<<v17-1-11,11>>^ to bring before the king Queen Vashʹti, wearing the royal headdress,^&#42;1^ to show the peoples and the princes her beauty, for she was very beautiful.

[NOTE]
====
. Or “turban.”
====

[[v17-1-12]]

^<<v17-1-12,12>>^ But Queen Vashʹti kept refusing to come at the king’s order that was conveyed through the court officials. At this the king became very angry, and his rage flared up within him.

[[v17-1-13]]

^<<v17-1-13,13>>^ The king then spoke to the wise men who had insight with regard to precedents^&#42;1^ (for in this way the king’s matter came before all those versed in law and legal cases,

[NOTE]
====
. Or “procedures.” Lit., “the times.”
====

[[v17-1-14]]

^<<v17-1-14,14>>^ and those closest to him were Car·sheʹna, Sheʹthar, Ad·maʹtha, Tarʹshish, Meʹres, Mar·seʹna, and Me·muʹcan, seven princes of Persia and Meʹdi·a, who had access to the king and who occupied the highest positions in the kingdom).

[[v17-1-15]]

^<<v17-1-15,15>>^ The king asked: “According to law, what is to be done with Queen Vashʹti because she has not obeyed the order of King A·has·u·eʹrus conveyed through the court officials?”

[[v17-1-16]]

^<<v17-1-16,16>>^ To this Me·muʹcan said in the presence of the king and the princes: “It is not against the king alone that Queen Vashʹti has done wrong, but against all the princes and against all the peoples in all the provinces^&#42;1^ of King A·has·u·eʹrus.

[NOTE]
====
. Or “jurisdictional districts.”
====

[[v17-1-17]]

^<<v17-1-17,17>>^ For what the queen did will become known by all the wives, and they will despise their husbands and say, ‘King A·has·u·eʹrus said to bring in Queen Vashʹti before him, but she refused to come.’

[[v17-1-18]]

^<<v17-1-18,18>>^ This very day the princesses of Persia and Meʹdi·a who know about what the queen did will talk to all the princes of the king, resulting in much contempt and indignation.

[[v17-1-19]]

^<<v17-1-19,19>>^ If it seems good to the king, let a royal decree be issued from him, and let it be written among the laws of Persia and Meʹdi·a, which cannot be repealed, that Vashʹti may never again come in before King A·has·u·eʹrus; and let the king confer her royal position on a woman who is better than she is.

[[v17-1-20]]

^<<v17-1-20,20>>^ And when the decree of the king is heard in all his vast realm, all the wives will give honor to their husbands, from the greatest to the least.”

[[v17-1-21]]

^<<v17-1-21,21>>^ This proposal pleased the king and the princes, and the king did what Me·muʹcan said.

[[v17-1-22]]

^<<v17-1-22,22>>^ So he sent letters to all the royal provinces,^&#42;1^ to each province^&#42;2^ in its own script^&#42;3^ and to each people in its own language, for every husband to be master^&#42;4^ in his own house and to speak in the language of his own people.

[NOTE]
====
. Lit., “the jurisdictional districts of the king.”
. Or “jurisdictional district.”
. Or “style of writing.”
. Or “prince.”
====

'''

xref:016-nehemiah/016-nehemiah-013.adoc#v16-13-0[&#60; Capítulo Anterior] | <<v17-1-0,Topo>> | xref:017-esther/017-esther-002.adoc#v17-2-0[Próximo Capítulo &#62;]