include::./index.adoc[]

[[v46-11-0]]
=== The First to the Corinthians, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v46-11-1]]

^<<v46-11-1,1>>^ Become imitators of me, just as I am of Christ.

[[v46-11-2]]

^<<v46-11-2,2>>^ I commend you because in all things you remember me and you are holding fast the traditions just as I handed them on to you.

[[v46-11-3]]

^<<v46-11-3,3>>^ But I want you to know that the head of every man is the Christ; in turn, the head of a woman is the man; in turn, the head of the Christ is God.

[[v46-11-4]]

^<<v46-11-4,4>>^ Every man who prays or prophesies with something on his head shames his head;

[[v46-11-5]]

^<<v46-11-5,5>>^ but every woman who prays or prophesies with her head uncovered shames her head, for it is one and the same as if she were a woman with a shaved head.

[[v46-11-6]]

^<<v46-11-6,6>>^ For if a woman does not cover herself, she should have her hair cut off; but if it is disgraceful for a woman to have her hair cut off or shaved, she should be covered.

[[v46-11-7]]

^<<v46-11-7,7>>^ For a man should not have his head covered, as he is God’s image and glory, but the woman is man’s glory.

[[v46-11-8]]

^<<v46-11-8,8>>^ For man did not come from woman, but woman came from man.

[[v46-11-9]]

^<<v46-11-9,9>>^ And what is more, man was not created for the sake of the woman, but woman for the sake of the man.

[[v46-11-10]]

^<<v46-11-10,10>>^ That is why the woman ought to have a sign of authority on her head, because of the angels.

[[v46-11-11]]

^<<v46-11-11,11>>^ Besides, in connection with the Lord, neither is woman separate from man nor is man separate from woman.

[[v46-11-12]]

^<<v46-11-12,12>>^ For just as the woman is from the man, so also the man is through the woman; but all things are from God.

[[v46-11-13]]

^<<v46-11-13,13>>^ Judge for yourselves: Is it fitting for a woman to pray to God with her head uncovered?

[[v46-11-14]]

^<<v46-11-14,14>>^ Does not nature itself teach you that long hair is a dishonor to a man,

[[v46-11-15]]

^<<v46-11-15,15>>^ but if a woman has long hair, it is a glory to her? For her hair is given to her instead of a covering.

[[v46-11-16]]

^<<v46-11-16,16>>^ However, if anyone wants to argue in favor of some other custom, we have no other, nor do the congregations of God.

[[v46-11-17]]

^<<v46-11-17,17>>^ But while giving these instructions, I do not commend you, because it is, not for the better, but for the worse that you meet together.

[[v46-11-18]]

^<<v46-11-18,18>>^ For first of all, I hear that when you come together in a congregation, divisions exist among you; and to an extent I believe it.

[[v46-11-19]]

^<<v46-11-19,19>>^ For there will certainly also be sects among you, so that those of you who are approved may also become evident.

[[v46-11-20]]

^<<v46-11-20,20>>^ When you come together in one place, it is not really to eat the Lord’s Evening Meal.

[[v46-11-21]]

^<<v46-11-21,21>>^ For when you eat it, each one takes his own evening meal beforehand, so that one is hungry but another is intoxicated.

[[v46-11-22]]

^<<v46-11-22,22>>^ Do you not have houses for eating and drinking? Or do you despise the congregation of God and make those who have nothing feel ashamed? What can I say to you? Should I commend you? In this I do not commend you.

[[v46-11-23]]

^<<v46-11-23,23>>^ For I received from the Lord what I also handed on to you, that the Lord Jesus on the night on which he was going to be betrayed took a loaf,

[[v46-11-24]]

^<<v46-11-24,24>>^ and after giving thanks, he broke it and said: “This means my body, which is in your behalf. Keep doing this in remembrance of me.”

[[v46-11-25]]

^<<v46-11-25,25>>^ He did the same with the cup also, after they had the evening meal, saying: “This cup means the new covenant by virtue of my blood. Keep doing this, whenever you drink it, in remembrance of me.”

[[v46-11-26]]

^<<v46-11-26,26>>^ For whenever you eat this loaf and drink this cup, you keep proclaiming the death of the Lord, until he comes.

[[v46-11-27]]

^<<v46-11-27,27>>^ Therefore, whoever eats the loaf or drinks the cup of the Lord unworthily will be guilty respecting the body and the blood of the Lord.

[[v46-11-28]]

^<<v46-11-28,28>>^ First let a man approve himself after scrutiny, and only then let him eat of the loaf and drink of the cup.

[[v46-11-29]]

^<<v46-11-29,29>>^ For the one who eats and drinks without discerning the body eats and drinks judgment against himself.

[[v46-11-30]]

^<<v46-11-30,30>>^ That is why many among you are weak and sick, and quite a few are sleeping in death.^&#42;1^

[NOTE]
====
. Evidently referring to spiritual death.
====

[[v46-11-31]]

^<<v46-11-31,31>>^ But if we would discern what we ourselves are, we would not be judged.

[[v46-11-32]]

^<<v46-11-32,32>>^ However, when we are judged, we are disciplined by Jehovah,^&#42;1^ so that we may not become condemned with the world.

[NOTE]
====
. See App. A5.
====

[[v46-11-33]]

^<<v46-11-33,33>>^ Consequently, my brothers, when you come together to eat it, wait for one another.

[[v46-11-34]]

^<<v46-11-34,34>>^ If anyone is hungry, let him eat at home, so that when you come together it is not for judgment. But as for the remaining matters, I will put them in order when I get there.

'''

xref:046-1-corinthians/046-1-corinthians-010.adoc#v46-10-0[&#60; Capítulo Anterior] | <<v46-11-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-012.adoc#v46-12-0[Próximo Capítulo &#62;]