include::./index.adoc[]

[[v46-12-0]]
=== The First to the Corinthians, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v46-12-1]]

^<<v46-12-1,1>>^ Now concerning the spiritual gifts, brothers, I do not want you to be uninformed.

[[v46-12-2]]

^<<v46-12-2,2>>^ You know that when you were people of the nations,^&#42;1^ you were influenced and led astray to those voiceless idols, following wherever they might lead you.

[NOTE]
====
. That is, unbelievers.
====

[[v46-12-3]]

^<<v46-12-3,3>>^ Now I would have you know that nobody when speaking by God’s spirit says: “Jesus is accursed!” and nobody can say: “Jesus is Lord!” except by holy spirit.

[[v46-12-4]]

^<<v46-12-4,4>>^ Now there are different gifts, but there is the same spirit;

[[v46-12-5]]

^<<v46-12-5,5>>^ and there are different ministries, and yet there is the same Lord;

[[v46-12-6]]

^<<v46-12-6,6>>^ and there are different activities,^&#42;1^ and yet it is the same God who performs them all in everyone.

[NOTE]
====
. Or “operations.”
====

[[v46-12-7]]

^<<v46-12-7,7>>^ But the manifestation of the spirit is given to each one for a beneficial purpose.

[[v46-12-8]]

^<<v46-12-8,8>>^ For to one is given speech^&#42;1^ of wisdom through the spirit, to another speech of knowledge according to the same spirit,

[NOTE]
====
. Or “a message.”
====

[[v46-12-9]]

^<<v46-12-9,9>>^ to another faith by the same spirit, to another gifts of healing by that one spirit,

[[v46-12-10]]

^<<v46-12-10,10>>^ to yet another operations of powerful works, to another prophesying, to another discernment of inspired expressions, to another different tongues,^&#42;1^ and to another interpretation of tongues.

[NOTE]
====
. Or “languages.”
====

[[v46-12-11]]

^<<v46-12-11,11>>^ But all these operations are performed by the very same spirit, distributing to each one respectively just as it wills.

[[v46-12-12]]

^<<v46-12-12,12>>^ For just as the body is one but has many members, and all the members of that body, although many, are one body, so too is the Christ.

[[v46-12-13]]

^<<v46-12-13,13>>^ For by one spirit we were all baptized into one body, whether Jews or Greeks, whether slaves or free, and we were all made to drink one spirit.

[[v46-12-14]]

^<<v46-12-14,14>>^ For, indeed, the body is made up not of one member but of many.

[[v46-12-15]]

^<<v46-12-15,15>>^ If the foot should say, “Because I am not a hand, I am no part of the body,” that does not make it no part of the body.

[[v46-12-16]]

^<<v46-12-16,16>>^ And if the ear should say, “Because I am not an eye, I am no part of the body,” that does not make it no part of the body.

[[v46-12-17]]

^<<v46-12-17,17>>^ If the whole body were an eye, where would the sense of hearing be? If it were all hearing, where would the sense of smell be?

[[v46-12-18]]

^<<v46-12-18,18>>^ But now God has arranged each of the body members just as he pleased.

[[v46-12-19]]

^<<v46-12-19,19>>^ If they were all the same member, where would the body be?

[[v46-12-20]]

^<<v46-12-20,20>>^ But now they are many members, yet one body.

[[v46-12-21]]

^<<v46-12-21,21>>^ The eye cannot say to the hand, “I do not need you,” or again, the head cannot say to the feet, “I do not need you.”

[[v46-12-22]]

^<<v46-12-22,22>>^ On the contrary, the members of the body that seem to be weaker are necessary,

[[v46-12-23]]

^<<v46-12-23,23>>^ and the parts of the body that we think to be less honorable we surround with greater honor, so our unseemly parts are treated with greater modesty,

[[v46-12-24]]

^<<v46-12-24,24>>^ whereas our attractive parts do not need anything. Nevertheless, God has so composed the body, giving greater honor to the part that had a lack,

[[v46-12-25]]

^<<v46-12-25,25>>^ so that there should be no division in the body, but its members should have mutual concern for one another.

[[v46-12-26]]

^<<v46-12-26,26>>^ If one member suffers, all the other members suffer with it; or if a member is glorified, all the other members rejoice with it.

[[v46-12-27]]

^<<v46-12-27,27>>^ Now you are Christ’s body, and each of you individually is a member.

[[v46-12-28]]

^<<v46-12-28,28>>^ And God has assigned the respective ones in the congregation: first, apostles; second, prophets; third, teachers; then powerful works; then gifts of healings; helpful services; abilities to direct; different tongues.

[[v46-12-29]]

^<<v46-12-29,29>>^ Not all are apostles, are they? Not all are prophets, are they? Not all are teachers, are they? Not all perform powerful works, do they?

[[v46-12-30]]

^<<v46-12-30,30>>^ Not all have gifts of healings, do they? Not all speak in tongues, do they? Not all are interpreters,^&#42;1^ are they?

[NOTE]
====
. Or “translators.”
====

[[v46-12-31]]

^<<v46-12-31,31>>^ But keep striving for^&#42;1^ the greater gifts. And yet I will show you a surpassing way.

[NOTE]
====
. Or “keep zealously seeking.”
====

'''

xref:046-1-corinthians/046-1-corinthians-011.adoc#v46-11-0[&#60; Capítulo Anterior] | <<v46-12-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-013.adoc#v46-13-0[Próximo Capítulo &#62;]