include::./index.adoc[]

[[v46-10-0]]
=== The First to the Corinthians, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v46-10-1]]

^<<v46-10-1,1>>^ Now I want you to know, brothers, that our forefathers were all under the cloud and all passed through the sea

[[v46-10-2]]

^<<v46-10-2,2>>^ and all got baptized into Moses by means of the cloud and of the sea,

[[v46-10-3]]

^<<v46-10-3,3>>^ and all ate the same spiritual food

[[v46-10-4]]

^<<v46-10-4,4>>^ and all drank the same spiritual drink. For they used to drink from the spiritual rock that followed them, and that rock meant^&#42;1^ the Christ.

[NOTE]
====
. Or “was.”
====

[[v46-10-5]]

^<<v46-10-5,5>>^ Nevertheless, God was not pleased with most of them, for they were struck down in the wilderness.

[[v46-10-6]]

^<<v46-10-6,6>>^ Now these things became examples for us, in order for us not to desire injurious things, as they desired them.

[[v46-10-7]]

^<<v46-10-7,7>>^ Neither become idolaters, as some of them did; just as it is written: “The people sat down to eat and drink. Then they got up to have a good time.”

[[v46-10-8]]

^<<v46-10-8,8>>^ Neither let us practice sexual immorality,^&#42;1^ as some of them committed sexual immorality,^&#42;2^ only to fall, 23,000 of them in one day.

[NOTE]
====
. See Glossary.
. See Glossary.
====

[[v46-10-9]]

^<<v46-10-9,9>>^ Neither let us put Jehovah^&#42;1^ to the test, as some of them put him to the test, only to perish by the serpents.

[NOTE]
====
. See App. A5.
====

[[v46-10-10]]

^<<v46-10-10,10>>^ Neither be murmurers, as some of them murmured, only to perish by the destroyer.

[[v46-10-11]]

^<<v46-10-11,11>>^ Now these things happened to them as examples, and they were written for a warning to us upon whom the ends of the systems of things have come.

[[v46-10-12]]

^<<v46-10-12,12>>^ So let the one who thinks he is standing beware that he does not fall.

[[v46-10-13]]

^<<v46-10-13,13>>^ No temptation has come upon you except what is common to men. But God is faithful, and he will not let you be tempted beyond what you can bear, but along with the temptation he will also make the way out so that you may be able to endure it.

[[v46-10-14]]

^<<v46-10-14,14>>^ Therefore, my beloved ones, flee from idolatry.

[[v46-10-15]]

^<<v46-10-15,15>>^ I speak as to men with discernment; judge for yourselves what I say.

[[v46-10-16]]

^<<v46-10-16,16>>^ The cup of blessing that we bless, is it not a sharing in the blood of the Christ? The loaf that we break, is it not a sharing in the body of the Christ?

[[v46-10-17]]

^<<v46-10-17,17>>^ Because there is one loaf, we, although many, are one body, for we are all partaking of that one loaf.

[[v46-10-18]]

^<<v46-10-18,18>>^ Look at Israel in the fleshly sense: Are not those who eat the sacrifices sharers with the altar?

[[v46-10-19]]

^<<v46-10-19,19>>^ What, then, am I saying? That what is sacrificed to an idol is anything, or that an idol is anything?

[[v46-10-20]]

^<<v46-10-20,20>>^ No; but I say that what the nations sacrifice, they sacrifice to demons and not to God; and I do not want you to become sharers with the demons.

[[v46-10-21]]

^<<v46-10-21,21>>^ You cannot be drinking the cup of Jehovah^&#42;1^ and the cup of demons; you cannot be partaking of “the table of Jehovah”^&#42;2^ and the table of demons.

[NOTE]
====
. See App. A5.
. See App. A5.
====

[[v46-10-22]]

^<<v46-10-22,22>>^ Or ‘are we inciting Jehovah^&#42;1^ to jealousy’? We are not stronger than he is, are we?

[NOTE]
====
. See App. A5.
====

[[v46-10-23]]

^<<v46-10-23,23>>^ All things are lawful,^&#42;1^ but not all things are advantageous. All things are lawful, but not all things build up.

[NOTE]
====
. Or “permissible.”
====

[[v46-10-24]]

^<<v46-10-24,24>>^ Let each one keep seeking, not his own advantage, but that of the other person.

[[v46-10-25]]

^<<v46-10-25,25>>^ Eat whatever is sold in a meat market, making no inquiry because of your conscience,

[[v46-10-26]]

^<<v46-10-26,26>>^ for “to Jehovah^&#42;1^ belong the earth and everything in it.”

[NOTE]
====
. See App. A5.
====

[[v46-10-27]]

^<<v46-10-27,27>>^ If an unbeliever invites you and you want to go, eat whatever is set before you, making no inquiry on account of your conscience.

[[v46-10-28]]

^<<v46-10-28,28>>^ But if anyone says to you, “This is something offered in sacrifice,” do not eat because of the one who told you and because of conscience.

[[v46-10-29]]

^<<v46-10-29,29>>^ I do not mean your own conscience, but that of the other person. For why should my freedom be judged by another person’s conscience?

[[v46-10-30]]

^<<v46-10-30,30>>^ If I am partaking with thanks, why am I to be spoken of abusively over that for which I give thanks?

[[v46-10-31]]

^<<v46-10-31,31>>^ Therefore, whether you are eating or drinking or doing anything else, do all things for God’s glory.

[[v46-10-32]]

^<<v46-10-32,32>>^ Keep from becoming causes for stumbling to Jews as well as Greeks and to the congregation of God,

[[v46-10-33]]

^<<v46-10-33,33>>^ just as I am trying to please all people in all things, not seeking my own advantage, but that of the many, so that they may be saved.

'''

xref:046-1-corinthians/046-1-corinthians-009.adoc#v46-9-0[&#60; Capítulo Anterior] | <<v46-10-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-011.adoc#v46-11-0[Próximo Capítulo &#62;]