include::./index.adoc[]

[[v46-9-0]]
=== The First to the Corinthians, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v46-9-1]]

^<<v46-9-1,1>>^ Am I not free? Am I not an apostle? Have I not seen Jesus our Lord? Are you not my work in the Lord?

[[v46-9-2]]

^<<v46-9-2,2>>^ Even if I am not an apostle to others, I most certainly am to you! For you are the seal confirming my apostleship in the Lord.

[[v46-9-3]]

^<<v46-9-3,3>>^ My defense to those who examine me is as follows:

[[v46-9-4]]

^<<v46-9-4,4>>^ We have the right^&#42;1^ to eat and drink, do we not?

[NOTE]
====
. Lit., “authority.”
====

[[v46-9-5]]

^<<v46-9-5,5>>^ We have the right to be accompanied by a believing wife,^&#42;1^ as the rest of the apostles and the Lord’s brothers and Ceʹphas,^&#42;2^ do we not?

[NOTE]
====
. Or “a sister as a wife.”
. Also called Peter.
====

[[v46-9-6]]

^<<v46-9-6,6>>^ Or is it only Barʹna·bas and I who do not have the right to refrain from working for a living?

[[v46-9-7]]

^<<v46-9-7,7>>^ What soldier ever serves at his own expense? Who plants a vineyard and does not eat of its fruit? Or who shepherds a flock and does not partake of some of the milk of the flock?

[[v46-9-8]]

^<<v46-9-8,8>>^ Am I saying these things from a human viewpoint? Or does not the Law also say these things?

[[v46-9-9]]

^<<v46-9-9,9>>^ For it is written in the Law of Moses: “You must not muzzle a bull when it is threshing out the grain.” Is it bulls that God is concerned about?

[[v46-9-10]]

^<<v46-9-10,10>>^ Or is it actually for our sakes that he says it? It was really written for our sakes, because the man who plows and the man who threshes ought to do so in the hope of receiving a share.

[[v46-9-11]]

^<<v46-9-11,11>>^ If we have sown spiritual things among you, is it too much if we reap material support from you?

[[v46-9-12]]

^<<v46-9-12,12>>^ If other men have this rightful claim over you, do we not have it much more so? Nevertheless, we have not made use of this right,^&#42;1^ but we are enduring all things so that we might not in any way hinder the good news about the Christ.

[NOTE]
====
. Lit., “authority.”
====

[[v46-9-13]]

^<<v46-9-13,13>>^ Do you not know that the men performing sacred duties eat the things of the temple, and that those regularly serving at the altar receive a share from the altar?

[[v46-9-14]]

^<<v46-9-14,14>>^ In this way, too, the Lord commanded for those proclaiming the good news to live by means of the good news.

[[v46-9-15]]

^<<v46-9-15,15>>^ But I have not made use of a single one of these provisions. Indeed, I have not written these things so that this would be done for me, for it would be better to die than—no man will take away my grounds for boasting!

[[v46-9-16]]

^<<v46-9-16,16>>^ Now if I am declaring the good news, it is no reason for me to boast, for necessity is laid upon me. Really, woe to me if I do not declare the good news!

[[v46-9-17]]

^<<v46-9-17,17>>^ If I do this willingly, I have a reward; but even if I do it against my will, I still have a stewardship entrusted to me.

[[v46-9-18]]

^<<v46-9-18,18>>^ What, then, is my reward? That when I declare the good news, I may offer the good news without cost, to avoid abusing my authority^&#42;1^ in the good news.

[NOTE]
====
. Or “rights.”
====

[[v46-9-19]]

^<<v46-9-19,19>>^ For though I am free from all people, I have made myself the slave to all, so that I may gain as many people as possible.

[[v46-9-20]]

^<<v46-9-20,20>>^ To the Jews I became as a Jew in order to gain Jews; to those under law I became as under law, though I myself am not under law, in order to gain those under law.

[[v46-9-21]]

^<<v46-9-21,21>>^ To those without law I became as without law, although I am not without law toward God but under law toward Christ, in order to gain those without law.

[[v46-9-22]]

^<<v46-9-22,22>>^ To the weak I became weak, in order to gain the weak. I have become all things to people of all sorts, so that I might by all possible means save some.

[[v46-9-23]]

^<<v46-9-23,23>>^ But I do all things for the sake of the good news, in order to share it with others.

[[v46-9-24]]

^<<v46-9-24,24>>^ Do you not know that the runners in a race all run, but only one receives the prize? Run in such a way that you may win it.

[[v46-9-25]]

^<<v46-9-25,25>>^ Now everyone competing in a contest^&#42;1^ exercises self-control in all things. Of course, they do it to receive a crown that can perish, but we, one that does not perish.

[NOTE]
====
. Or “every athlete.”
====

[[v46-9-26]]

^<<v46-9-26,26>>^ Therefore, the way I am running is not aimlessly; the way I am aiming my blows is so as not to be striking the air;

[[v46-9-27]]

^<<v46-9-27,27>>^ but I pummel^&#42;1^ my body and lead it as a slave, so that after I have preached to others, I myself should not become disapproved^&#42;2^ somehow.

[NOTE]
====
. Or “punish; strictly discipline.”
. Or “disqualified.”
====

'''

xref:046-1-corinthians/046-1-corinthians-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-010.adoc#v46-10-0[Próximo Capítulo &#62;]