include::./index.adoc[]

[[v46-4-0]]
=== The First to the Corinthians, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v46-4-1]]

^<<v46-4-1,1>>^ A man should regard us as attendants^&#42;1^ of Christ and stewards of God’s sacred secrets.

[NOTE]
====
. Or “subordinates.”
====

[[v46-4-2]]

^<<v46-4-2,2>>^ In this regard, what is expected of stewards is that they be found faithful.

[[v46-4-3]]

^<<v46-4-3,3>>^ Now to me it is of very little importance to be examined by you or by a human tribunal.^&#42;1^ In fact, I do not even examine myself.

[NOTE]
====
. Or “court.”
====

[[v46-4-4]]

^<<v46-4-4,4>>^ For I am not conscious of anything against myself. But by this I am not proved righteous; the one who examines me is Jehovah.^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v46-4-5]]

^<<v46-4-5,5>>^ Therefore, do not judge anything before the due time, until the Lord comes. He will bring the secret things of darkness to light and make known the intentions of the hearts, and then each one will receive his praise from God.

[[v46-4-6]]

^<<v46-4-6,6>>^ Now, brothers, these things I have applied^&#42;1^ to myself and A·polʹlos for your good, that through us you may learn the rule: “Do not go beyond the things that are written,” so that you may not be puffed up with pride, favoring one against the other.

[NOTE]
====
. Or “transferred.”
====

[[v46-4-7]]

^<<v46-4-7,7>>^ For who makes you different from another? Indeed, what do you have that you did not receive? If, in fact, you did receive it, why do you boast as though you did not receive it?

[[v46-4-8]]

^<<v46-4-8,8>>^ Are you already satisfied? Are you already rich? Have you begun ruling as kings without us? I really wish that you had begun ruling as kings, so that we also might rule with you as kings.

[[v46-4-9]]

^<<v46-4-9,9>>^ For it seems to me that God has put us the apostles last on exhibition as men condemned to death, because we have become a theatrical spectacle to the world, and to angels and to men.

[[v46-4-10]]

^<<v46-4-10,10>>^ We are fools because of Christ, but you are discreet in Christ; we are weak, but you are strong; you are held in honor, but we in dishonor.

[[v46-4-11]]

^<<v46-4-11,11>>^ Down to this very hour we continue to hunger and thirst and to be poorly clothed^&#42;1^ and to be beaten^&#42;2^ and to be homeless

[NOTE]
====
. Lit., “and being naked.”
. Or “knocked about.”
====

[[v46-4-12]]

^<<v46-4-12,12>>^ and to toil, working with our own hands. When insulted, we bless; when persecuted, we patiently endure;

[[v46-4-13]]

^<<v46-4-13,13>>^ when slandered, we answer mildly;^&#42;1^ we have become as the refuse^&#42;2^ of the world, the offscouring of all things, until now.

[NOTE]
====
. Lit., “we entreat.”
. Or “garbage; rubbish.”
====

[[v46-4-14]]

^<<v46-4-14,14>>^ I am writing these things, not to put you to shame, but to admonish you as my beloved children.

[[v46-4-15]]

^<<v46-4-15,15>>^ For though you may have 10,000 guardians^&#42;1^ in Christ, you certainly do not have many fathers; for in Christ Jesus, I have become your father through the good news.

[NOTE]
====
. Or “tutors.”
====

[[v46-4-16]]

^<<v46-4-16,16>>^ I urge you, therefore, become imitators of me.

[[v46-4-17]]

^<<v46-4-17,17>>^ That is why I am sending Timothy to you, because he is my beloved and faithful child in the Lord. He will remind you of my methods^&#42;1^ in connection with Christ Jesus, just as I am teaching everywhere in every congregation.

[NOTE]
====
. Lit., “my ways.”
====

[[v46-4-18]]

^<<v46-4-18,18>>^ Some are puffed up with pride, as though I were not coming to you.

[[v46-4-19]]

^<<v46-4-19,19>>^ But I will come to you shortly, if Jehovah^&#42;1^ wills, and I will get to know, not the speech of those who are puffed up with pride, but their power.

[NOTE]
====
. See App. A5.
====

[[v46-4-20]]

^<<v46-4-20,20>>^ For the Kingdom of God is a matter not of speech but of power.

[[v46-4-21]]

^<<v46-4-21,21>>^ Which do you prefer? Shall I come to you with a rod or with love and mildness of spirit?

'''

xref:046-1-corinthians/046-1-corinthians-003.adoc#v46-3-0[&#60; Capítulo Anterior] | <<v46-4-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-005.adoc#v46-5-0[Próximo Capítulo &#62;]