include::./index.adoc[]

[[v46-15-0]]
=== The First to the Corinthians, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v46-15-1]]

^<<v46-15-1,1>>^ Now I remind you, brothers, of the good news that I declared to you, which you also accepted, and for which you have taken your stand.

[[v46-15-2]]

^<<v46-15-2,2>>^ Through it you are also being saved if you hold firmly to the good news I declared to you, unless you became believers for nothing.

[[v46-15-3]]

^<<v46-15-3,3>>^ For among the first things I handed on to you was what I also received, that Christ died for our sins according to the Scriptures;

[[v46-15-4]]

^<<v46-15-4,4>>^ and that he was buried, yes, that he was raised up on the third day according to the Scriptures;

[[v46-15-5]]

^<<v46-15-5,5>>^ and that he appeared to Ceʹphas,^&#42;1^ and then to the Twelve.

[NOTE]
====
. Also called Peter.
====

[[v46-15-6]]

^<<v46-15-6,6>>^ After that he appeared to more than 500 brothers at one time, most of whom are still with us, though some have fallen asleep in death.

[[v46-15-7]]

^<<v46-15-7,7>>^ After that he appeared to James, then to all the apostles.

[[v46-15-8]]

^<<v46-15-8,8>>^ But last of all he appeared also to me as if to one born prematurely.

[[v46-15-9]]

^<<v46-15-9,9>>^ For I am the least of the apostles, and I am not worthy of being called an apostle, because I persecuted the congregation of God.

[[v46-15-10]]

^<<v46-15-10,10>>^ But by God’s undeserved kindness I am what I am. And his undeserved kindness to me was not in vain, but I labored more than all of them; yet it was not I, but the undeserved kindness of God that is with me.

[[v46-15-11]]

^<<v46-15-11,11>>^ Whether, then, it is I or they, this is the way we preach, and this is the way you believed.

[[v46-15-12]]

^<<v46-15-12,12>>^ Now if it is being preached that Christ has been raised from the dead, how is it that some among you say there is no resurrection of the dead?

[[v46-15-13]]

^<<v46-15-13,13>>^ If, indeed, there is no resurrection of the dead, then Christ has not been raised up.

[[v46-15-14]]

^<<v46-15-14,14>>^ But if Christ has not been raised up, our preaching is certainly in vain, and your faith is also in vain.

[[v46-15-15]]

^<<v46-15-15,15>>^ Moreover, we are also found to be false witnesses of God, because we have given witness against God by saying that he raised up the Christ, whom he did not raise up if the dead are really not to be raised up.

[[v46-15-16]]

^<<v46-15-16,16>>^ For if the dead are not to be raised up, neither has Christ been raised up.

[[v46-15-17]]

^<<v46-15-17,17>>^ Further, if Christ has not been raised up, your faith is useless; you remain in your sins.

[[v46-15-18]]

^<<v46-15-18,18>>^ Then also those who have fallen asleep in death in union with Christ have perished.

[[v46-15-19]]

^<<v46-15-19,19>>^ If in this life only we have hoped in Christ, we are to be pitied more than anyone.

[[v46-15-20]]

^<<v46-15-20,20>>^ But now Christ has been raised from the dead, the firstfruits of those who have fallen asleep in death.

[[v46-15-21]]

^<<v46-15-21,21>>^ For since death came through a man, resurrection of the dead also comes through a man.

[[v46-15-22]]

^<<v46-15-22,22>>^ For just as in Adam all are dying, so also in the Christ all will be made alive.

[[v46-15-23]]

^<<v46-15-23,23>>^ But each one in his own proper order: Christ the firstfruits, afterward those who belong to the Christ during his presence.

[[v46-15-24]]

^<<v46-15-24,24>>^ Next, the end, when he hands over the Kingdom to his God and Father, when he has brought to nothing all government and all authority and power.

[[v46-15-25]]

^<<v46-15-25,25>>^ For he must rule as king until God has put all enemies under his feet.

[[v46-15-26]]

^<<v46-15-26,26>>^ And the last enemy, death, is to be brought to nothing.

[[v46-15-27]]

^<<v46-15-27,27>>^ For God “subjected all things under his feet.” But when he says that ‘all things have been subjected,’ it is evident that this does not include the One who subjected all things to him.

[[v46-15-28]]

^<<v46-15-28,28>>^ But when all things will have been subjected to him, then the Son himself will also subject himself to the One who subjected all things to him, that God may be all things to everyone.

[[v46-15-29]]

^<<v46-15-29,29>>^ Otherwise, what will they do who are being baptized for the purpose of being dead ones? If the dead are not to be raised up at all, why are they also being baptized for the purpose of being such?

[[v46-15-30]]

^<<v46-15-30,30>>^ Why are we also in danger every hour?^&#42;1^

[NOTE]
====
. Or “all the time?”
====

[[v46-15-31]]

^<<v46-15-31,31>>^ Daily I face death. This is as sure as my exultation over you, brothers, which I have in Christ Jesus our Lord.

[[v46-15-32]]

^<<v46-15-32,32>>^ If like other men,^&#42;1^ I have fought with wild beasts at Ephʹe·sus, of what good is it to me? If the dead are not to be raised up, “let us eat and drink, for tomorrow we are to die.”

[NOTE]
====
. Or possibly, “from a human viewpoint.”
====

[[v46-15-33]]

^<<v46-15-33,33>>^ Do not be misled. Bad associations spoil useful habits.^&#42;1^

[NOTE]
====
. Or “corrupt good morals.”
====

[[v46-15-34]]

^<<v46-15-34,34>>^ Come to your senses in a righteous way and do not practice sin, for some have no knowledge of God. I am speaking to move you to shame.

[[v46-15-35]]

^<<v46-15-35,35>>^ Nevertheless, someone will say: “How are the dead to be raised up? Yes, with what sort of body are they coming?”

[[v46-15-36]]

^<<v46-15-36,36>>^ You unreasonable person! What you sow is not made alive unless first it dies.

[[v46-15-37]]

^<<v46-15-37,37>>^ And as for what you sow, you sow, not the body that will develop, but just a bare grain, whether of wheat or of some other kind of seed;

[[v46-15-38]]

^<<v46-15-38,38>>^ but God gives it a body just as it has pleased him, and gives to each of the seeds its own body.

[[v46-15-39]]

^<<v46-15-39,39>>^ Not all flesh is the same flesh, but there is one of mankind, there is another flesh of cattle, another flesh of birds, and another of fish.

[[v46-15-40]]

^<<v46-15-40,40>>^ And there are heavenly bodies and earthly bodies; but the glory of the heavenly bodies is one sort, and that of the earthly bodies is a different sort.

[[v46-15-41]]

^<<v46-15-41,41>>^ The glory of the sun is one sort, and the glory of the moon is another, and the glory of the stars is another; in fact, one star differs from another star in glory.

[[v46-15-42]]

^<<v46-15-42,42>>^ So it is with the resurrection of the dead. It is sown in corruption; it is raised up in incorruption.

[[v46-15-43]]

^<<v46-15-43,43>>^ It is sown in dishonor; it is raised up in glory. It is sown in weakness; it is raised up in power.

[[v46-15-44]]

^<<v46-15-44,44>>^ It is sown a physical body; it is raised up a spiritual body. If there is a physical body, there is also a spiritual one.

[[v46-15-45]]

^<<v46-15-45,45>>^ So it is written: “The first man Adam became a living person.”^&#42;1^ The last Adam became a life-giving spirit.

[NOTE]
====
. Or “soul.”
====

[[v46-15-46]]

^<<v46-15-46,46>>^ However, what is spiritual is not first. What is physical is first, and afterward what is spiritual.

[[v46-15-47]]

^<<v46-15-47,47>>^ The first man is from the earth and made of dust; the second man is from heaven.

[[v46-15-48]]

^<<v46-15-48,48>>^ Like the one made of dust, so too are those made of dust; and like the heavenly one, so too are those who are heavenly.

[[v46-15-49]]

^<<v46-15-49,49>>^ And just as we have borne the image of the one made of dust, we will bear also the image of the heavenly one.

[[v46-15-50]]

^<<v46-15-50,50>>^ But I tell you this, brothers, that flesh and blood cannot inherit God’s Kingdom, nor does corruption inherit incorruption.

[[v46-15-51]]

^<<v46-15-51,51>>^ Look! I tell you a sacred secret: We will not all fall asleep in death, but we will all be changed,

[[v46-15-52]]

^<<v46-15-52,52>>^ in a moment, in the blink^&#42;1^ of an eye, during the last trumpet. For the trumpet will sound, and the dead will be raised up incorruptible, and we will be changed.

[NOTE]
====
. Or “twinkling.”
====

[[v46-15-53]]

^<<v46-15-53,53>>^ For this which is corruptible must put on incorruption, and this which is mortal must put on immortality.

[[v46-15-54]]

^<<v46-15-54,54>>^ But when this which is corruptible puts on incorruption and this which is mortal puts on immortality, then the saying that is written will take place: “Death is swallowed up forever.”

[[v46-15-55]]

^<<v46-15-55,55>>^ “Death, where is your victory? Death, where is your sting?”

[[v46-15-56]]

^<<v46-15-56,56>>^ The sting producing death is sin, and the power for sin is the Law.^&#42;1^

[NOTE]
====
. Or “and the Law gives sin its power.”
====

[[v46-15-57]]

^<<v46-15-57,57>>^ But thanks to God, for he gives us the victory through our Lord Jesus Christ!

[[v46-15-58]]

^<<v46-15-58,58>>^ Therefore, my beloved brothers, be steadfast, immovable, always having plenty to do in the work of the Lord, knowing that your labor is not in vain in connection with the Lord.

'''

xref:046-1-corinthians/046-1-corinthians-014.adoc#v46-14-0[&#60; Capítulo Anterior] | <<v46-15-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-016.adoc#v46-16-0[Próximo Capítulo &#62;]