include::./index.adoc[]

[[v46-16-0]]
=== The First to the Corinthians, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v46-16-1]]

^<<v46-16-1,1>>^ Now concerning the collection for the holy ones, you may follow the directions I gave to the congregations of Ga·laʹti·a.

[[v46-16-2]]

^<<v46-16-2,2>>^ On the first day of every week, each of you should set something aside according to his own means, so that collections will not take place when I arrive.

[[v46-16-3]]

^<<v46-16-3,3>>^ But when I get there, I will send the men you approve of in your letters to take your kind gift to Jerusalem.

[[v46-16-4]]

^<<v46-16-4,4>>^ However, if it seems advisable for me to go there also, they will go there with me.

[[v46-16-5]]

^<<v46-16-5,5>>^ But I will come to you when I have gone through Mac·e·doʹni·a, for I will be going through Mac·e·doʹni·a;

[[v46-16-6]]

^<<v46-16-6,6>>^ and perhaps I will stay or even spend the winter with you, so that you may accompany me partway to where I may be going.

[[v46-16-7]]

^<<v46-16-7,7>>^ For I do not want to see you now just in passing, since I hope to spend some time with you, if Jehovah^&#42;1^ permits.

[NOTE]
====
. See App. A5.
====

[[v46-16-8]]

^<<v46-16-8,8>>^ But I am remaining in Ephʹe·sus until the Festival of Pentecost,

[[v46-16-9]]

^<<v46-16-9,9>>^ because a large door that leads to activity has been opened to me, but there are many opposers.

[[v46-16-10]]

^<<v46-16-10,10>>^ Now if Timothy arrives, make sure that he has nothing to fear while among you, for he is performing the work of Jehovah,^&#42;1^ just as I am.

[NOTE]
====
. See App. A5.
====

[[v46-16-11]]

^<<v46-16-11,11>>^ Therefore, let no one look down on him. Send him on his way in peace, so that he may come to me, for I am waiting for him together with the brothers.

[[v46-16-12]]

^<<v46-16-12,12>>^ Now concerning A·polʹlos our brother, I strongly urged him to come to you with the brothers. It was not his intention to come now, but he will come when he has the opportunity.

[[v46-16-13]]

^<<v46-16-13,13>>^ Stay awake, stand firm in the faith, carry on in a manly way,^&#42;1^ grow mighty.

[NOTE]
====
. Or “be courageous.”
====

[[v46-16-14]]

^<<v46-16-14,14>>^ Let everything you do be done with love.

[[v46-16-15]]

^<<v46-16-15,15>>^ Now I urge you, brothers: You know that the household of Stephʹa·nas is the firstfruits of A·chaʹia and that they devoted themselves to ministering to the holy ones.

[[v46-16-16]]

^<<v46-16-16,16>>^ May you also keep submitting yourselves to people like that and to all those cooperating and working hard.

[[v46-16-17]]

^<<v46-16-17,17>>^ But I rejoice over the presence of Stephʹa·nas and For·tu·naʹtus and A·chaʹi·cus, because they have made up for your not being here.

[[v46-16-18]]

^<<v46-16-18,18>>^ For they have refreshed my spirit and yours. Therefore, give recognition to men of that sort.

[[v46-16-19]]

^<<v46-16-19,19>>^ The congregations of Asia send you their greetings. Aqʹui·la and Prisʹca together with the congregation that is in their house greet you heartily in the Lord.

[[v46-16-20]]

^<<v46-16-20,20>>^ All the brothers greet you. Greet one another with a holy kiss.

[[v46-16-21]]

^<<v46-16-21,21>>^ Here is my greeting, Paul’s, in my own hand.

[[v46-16-22]]

^<<v46-16-22,22>>^ If anyone has no affection for the Lord, let him be accursed. O our Lord, come!

[[v46-16-23]]

^<<v46-16-23,23>>^ May the undeserved kindness of the Lord Jesus be with you.

[[v46-16-24]]

^<<v46-16-24,24>>^ May my love be with all of you in union with Christ Jesus.

'''

xref:046-1-corinthians/046-1-corinthians-015.adoc#v46-15-0[&#60; Capítulo Anterior] | <<v46-16-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-001.adoc#v47-1-0[Próximo Capítulo &#62;]