include::./index.adoc[]

[[v46-1-0]]
=== The First to the Corinthians, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v46-1-1]]

^<<v46-1-1,1>>^ Paul, called to be an apostle of Christ Jesus by God’s will, and Sosʹthe·nes our brother,

[[v46-1-2]]

^<<v46-1-2,2>>^ to the congregation of God that is in Corinth, to you who have been sanctified in union with Christ Jesus, called to be holy ones, together with all those everywhere who are calling on the name of our Lord Jesus Christ, their Lord and ours:

[[v46-1-3]]

^<<v46-1-3,3>>^ May you have undeserved kindness and peace from God our Father and the Lord Jesus Christ.

[[v46-1-4]]

^<<v46-1-4,4>>^ I always thank my God for you in view of the undeserved kindness of God given to you in Christ Jesus;

[[v46-1-5]]

^<<v46-1-5,5>>^ because in everything you have been enriched in him, in full ability to speak and in full knowledge,

[[v46-1-6]]

^<<v46-1-6,6>>^ just as the witness about the Christ has been made firm among you,

[[v46-1-7]]

^<<v46-1-7,7>>^ so that you do not lack in any gift at all, while you are eagerly waiting for the revelation of our Lord Jesus Christ.

[[v46-1-8]]

^<<v46-1-8,8>>^ He will also make you firm to the end so that you may be open to no accusation in the day of our Lord Jesus Christ.

[[v46-1-9]]

^<<v46-1-9,9>>^ God is faithful, by whom you were called into fellowship^&#42;1^ with his Son, Jesus Christ our Lord.

[NOTE]
====
. Or “a sharing.”
====

[[v46-1-10]]

^<<v46-1-10,10>>^ Now I urge you, brothers, through the name of our Lord Jesus Christ, that you should all speak in agreement and that there should be no divisions among you, but that you may be completely united in the same mind and in the same line of thought.

[[v46-1-11]]

^<<v46-1-11,11>>^ For some from the house of Chloʹe have informed me regarding you, my brothers, that there are dissensions among you.

[[v46-1-12]]

^<<v46-1-12,12>>^ What I mean is this, that each one of you says: “I belong to Paul,” “But I to A·polʹlos,” “But I to Ceʹphas,”^&#42;1^ “But I to Christ.”

[NOTE]
====
. Also called Peter.
====

[[v46-1-13]]

^<<v46-1-13,13>>^ Is the Christ divided? Paul was not executed on the stake for you, was he? Or were you baptized in the name of Paul?

[[v46-1-14]]

^<<v46-1-14,14>>^ I thank God that I baptized none of you except Crisʹpus and Gaʹius,

[[v46-1-15]]

^<<v46-1-15,15>>^ so that no one may say that you were baptized in my name.

[[v46-1-16]]

^<<v46-1-16,16>>^ Yes, I also baptized the household of Stephʹa·nas. As for the rest, I do not know whether I baptized anyone else.

[[v46-1-17]]

^<<v46-1-17,17>>^ For Christ sent me, not to baptize, but to declare the good news; and not with wisdom of speech,^&#42;1^ so that the torture stake^&#42;2^ of the Christ should not be made useless.

[NOTE]
====
. Or “clever speech.”
. See Glossary.
====

[[v46-1-18]]

^<<v46-1-18,18>>^ For the speech about the torture stake^&#42;1^ is foolishness to those who are perishing, but to us who are being saved, it is God’s power.

[NOTE]
====
. See Glossary.
====

[[v46-1-19]]

^<<v46-1-19,19>>^ For it is written: “I will make the wisdom of the wise men perish, and the intelligence of the intellectuals I will reject.”^&#42;1^

[NOTE]
====
. Or “shove aside.”
====

[[v46-1-20]]

^<<v46-1-20,20>>^ Where is the wise man? Where is the scribe?^&#42;1^ Where is the debater of this system of things?^&#42;2^ Has not God made the wisdom of the world foolish?

[NOTE]
====
. That is, an expert in the Law.
. Or “this age.” See Glossary.
====

[[v46-1-21]]

^<<v46-1-21,21>>^ For since, in the wisdom of God, the world did not get to know God through its wisdom, God was pleased through the foolishness of what is preached to save those believing.

[[v46-1-22]]

^<<v46-1-22,22>>^ For the Jews ask for signs and the Greeks look for wisdom;

[[v46-1-23]]

^<<v46-1-23,23>>^ but we preach Christ executed on the stake, to the Jews a cause for stumbling but to the nations foolishness.

[[v46-1-24]]

^<<v46-1-24,24>>^ However, to those who are called, both Jews and Greeks, Christ is the power of God and the wisdom of God.

[[v46-1-25]]

^<<v46-1-25,25>>^ Because a foolish thing of God is wiser than men, and a weak thing of God is stronger than men.

[[v46-1-26]]

^<<v46-1-26,26>>^ For you see his calling of you, brothers, that there are not many wise in a fleshly way,^&#42;1^ not many powerful, not many of noble birth,^&#42;2^

[NOTE]
====
. Or “by human standards.”
. Or “from important families.”
====

[[v46-1-27]]

^<<v46-1-27,27>>^ but God chose the foolish things of the world to put the wise men to shame; and God chose the weak things of the world to put the strong things to shame;

[[v46-1-28]]

^<<v46-1-28,28>>^ and God chose the insignificant things of the world and the things looked down on, the things that are not, to bring to nothing the things that are,

[[v46-1-29]]

^<<v46-1-29,29>>^ so that no one^&#42;1^ might boast in the sight of God.

[NOTE]
====
. Lit., “flesh.”
====

[[v46-1-30]]

^<<v46-1-30,30>>^ But it is due to him that you are in union with Christ Jesus, who has become to us wisdom from God, also righteousness and sanctification and release by ransom,

[[v46-1-31]]

^<<v46-1-31,31>>^ so that it may be just as it is written: “The one who boasts, let him boast in Jehovah.”^&#42;1^

[NOTE]
====
. See App. A5.
====

'''

xref:045-romans/045-romans-016.adoc#v45-16-0[&#60; Capítulo Anterior] | <<v46-1-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-002.adoc#v46-2-0[Próximo Capítulo &#62;]