include::./index.adoc[]

[[v46-7-0]]
=== The First to the Corinthians, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v46-7-1]]

^<<v46-7-1,1>>^ Now concerning the things about which you wrote, it is better for a man not to touch^&#42;1^ a woman;

[NOTE]
====
. That is, to have sexual contact with.
====

[[v46-7-2]]

^<<v46-7-2,2>>^ but because of the prevalence of sexual immorality,^&#42;1^ let each man have his own wife and each woman have her own husband.

[NOTE]
====
. Plural of the Greek por·neiʹa. See Glossary.
====

[[v46-7-3]]

^<<v46-7-3,3>>^ Let the husband give to his wife her due, and let the wife also do likewise to her husband.

[[v46-7-4]]

^<<v46-7-4,4>>^ The wife does not have authority over her own body, but her husband does; likewise, the husband does not have authority over his own body, but his wife does.

[[v46-7-5]]

^<<v46-7-5,5>>^ Do not deprive each other except by mutual consent for an appointed time, so that you may devote time to prayer and may come together again, in order that Satan may not keep tempting you for your lack of self-control.

[[v46-7-6]]

^<<v46-7-6,6>>^ However, I say this by way of concession, not as a command.

[[v46-7-7]]

^<<v46-7-7,7>>^ But I wish all men were as I am. Nevertheless, each one has his own gift from God, one in this way, another in that way.

[[v46-7-8]]

^<<v46-7-8,8>>^ Now I say to those who are unmarried and to the widows that it is better for them if they remain as I am.

[[v46-7-9]]

^<<v46-7-9,9>>^ But if they do not have self-control, let them marry, for it is better to marry than to be inflamed with passion.

[[v46-7-10]]

^<<v46-7-10,10>>^ To the married people I give instructions, not I but the Lord, that a wife should not separate from her husband.

[[v46-7-11]]

^<<v46-7-11,11>>^ But if she does separate, let her remain unmarried or else be reconciled with her husband; and a husband should not leave his wife.

[[v46-7-12]]

^<<v46-7-12,12>>^ But to the others I say, yes, I, not the Lord: If any brother has an unbelieving wife and she is agreeable to staying with him, let him not leave her;

[[v46-7-13]]

^<<v46-7-13,13>>^ and if a woman has an unbelieving husband and he is agreeable to staying with her, let her not leave her husband.

[[v46-7-14]]

^<<v46-7-14,14>>^ For the unbelieving husband is sanctified in relation to his wife, and the unbelieving wife is sanctified in relation to the brother; otherwise, your children would be unclean, but now they are holy.

[[v46-7-15]]

^<<v46-7-15,15>>^ But if the unbelieving one chooses to depart,^&#42;1^ let him depart; a brother or a sister is not bound under such circumstances, but God has called you to peace.

[NOTE]
====
. Or “separate.”
====

[[v46-7-16]]

^<<v46-7-16,16>>^ For wife, how do you know whether you will save your husband? Or, husband, how do you know whether you will save your wife?

[[v46-7-17]]

^<<v46-7-17,17>>^ Nevertheless, just as Jehovah^&#42;1^ has given each one a portion, let each one so walk as God has called him. And so I give this directive in all the congregations.

[NOTE]
====
. See App. A5.
====

[[v46-7-18]]

^<<v46-7-18,18>>^ Was any man already circumcised when he was called? Let him not undo his circumcision. Has any man been called while uncircumcised? Let him not get circumcised.

[[v46-7-19]]

^<<v46-7-19,19>>^ Circumcision means nothing, and uncircumcision means nothing; what means something is the observing of God’s commandments.

[[v46-7-20]]

^<<v46-7-20,20>>^ In whatever state each one was called, let him remain in it.

[[v46-7-21]]

^<<v46-7-21,21>>^ Were you called when a slave? Do not let it concern you; but if you can become free, then seize the opportunity.

[[v46-7-22]]

^<<v46-7-22,22>>^ For anyone who was called in the Lord when a slave is the Lord’s freedman; likewise anyone who was called when a freeman is a slave of Christ.

[[v46-7-23]]

^<<v46-7-23,23>>^ You were bought with a price; stop becoming slaves of men.

[[v46-7-24]]

^<<v46-7-24,24>>^ In whatever state each one was called, brothers, let him remain in it before God.

[[v46-7-25]]

^<<v46-7-25,25>>^ Now concerning virgins,^&#42;1^ I have no command from the Lord, but I give my opinion as one who had mercy shown him by the Lord to be faithful.

[NOTE]
====
. Or “those who have never married.”
====

[[v46-7-26]]

^<<v46-7-26,26>>^ Therefore, I think that it is best for a man to continue as he is in view of the present difficulty.

[[v46-7-27]]

^<<v46-7-27,27>>^ Are you bound to a wife? Stop seeking a release. Are you freed from a wife? Stop seeking a wife.

[[v46-7-28]]

^<<v46-7-28,28>>^ But even if you did marry, you would commit no sin. And if a virgin married, such a person would commit no sin. However, those who do will have tribulation in their flesh. But I am trying to spare you.

[[v46-7-29]]

^<<v46-7-29,29>>^ Moreover, this I say, brothers, the time left is reduced. From now on, let those who have wives be as though they had none,

[[v46-7-30]]

^<<v46-7-30,30>>^ and those who weep as those who do not weep, and those who rejoice as those who do not rejoice, and those who buy as those who do not possess,

[[v46-7-31]]

^<<v46-7-31,31>>^ and those making use of the world as those not using it to the full; for the scene of this world is changing.

[[v46-7-32]]

^<<v46-7-32,32>>^ Indeed, I want you to be free from anxiety. The unmarried man is anxious for the things of the Lord, how he may gain the Lord’s approval.

[[v46-7-33]]

^<<v46-7-33,33>>^ But the married man is anxious for the things of the world, how he may gain the approval of his wife,

[[v46-7-34]]

^<<v46-7-34,34>>^ and he is divided. Further, the unmarried woman, as well as the virgin, is anxious for the things of the Lord, that she may be holy both in her body and in her spirit. However, the married woman is anxious for the things of the world, how she may gain the approval of her husband.

[[v46-7-35]]

^<<v46-7-35,35>>^ But I am saying this for your personal advantage, not to restrict^&#42;1^ you, but to move you to what is appropriate and to constant devotion to the Lord without distraction.

[NOTE]
====
. Lit., “to cast a noose upon.”
====

[[v46-7-36]]

^<<v46-7-36,36>>^ But if anyone thinks he is behaving improperly by remaining unmarried,^&#42;1^ and if he is past the bloom of youth, then this is what should take place: Let him do what he wants; he does not sin. Let them marry.

[NOTE]
====
. Or “toward his virginity.”
====

[[v46-7-37]]

^<<v46-7-37,37>>^ But if anyone stands settled in his heart and has no necessity, but has authority over his own will and has made the decision in his own heart to remain unmarried,^&#42;1^ he will do well.

[NOTE]
====
. Or “to keep his own virginity.”
====

[[v46-7-38]]

^<<v46-7-38,38>>^ So also, whoever marries^&#42;1^ does well, but whoever does not marry will do better.

[NOTE]
====
. Or “gives his virginity in marriage.”
====

[[v46-7-39]]

^<<v46-7-39,39>>^ A wife is bound as long as her husband is alive. But if her husband should fall asleep in death, she is free to be married to whomever she wants, only in the Lord.

[[v46-7-40]]

^<<v46-7-40,40>>^ But in my opinion, she is happier if she remains as she is; and I certainly think I also have God’s spirit.

'''

xref:046-1-corinthians/046-1-corinthians-006.adoc#v46-6-0[&#60; Capítulo Anterior] | <<v46-7-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-008.adoc#v46-8-0[Próximo Capítulo &#62;]