include::./index.adoc[]

[[v46-6-0]]
=== The First to the Corinthians, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v46-6-1]]

^<<v46-6-1,1>>^ Does any one of you who has a dispute with another dare to go to court before unrighteous men, and not before the holy ones?

[[v46-6-2]]

^<<v46-6-2,2>>^ Or do you not know that the holy ones will judge the world? And if the world is to be judged by you, are you not competent to try very trivial matters?

[[v46-6-3]]

^<<v46-6-3,3>>^ Do you not know that we will judge angels? Then why not matters of this life?

[[v46-6-4]]

^<<v46-6-4,4>>^ If, then, you do have matters of this life to be tried, is it the men looked down on in the congregation whom you assign as judges?

[[v46-6-5]]

^<<v46-6-5,5>>^ I am speaking to move you to shame. Is there not one wise man among you who is able to judge between his brothers?

[[v46-6-6]]

^<<v46-6-6,6>>^ Instead, brother goes to court against brother, and before unbelievers at that!

[[v46-6-7]]

^<<v46-6-7,7>>^ Really, it is already a defeat for you when you have lawsuits with one another. Why not rather let yourselves be wronged? Why do you not rather let yourselves be defrauded?

[[v46-6-8]]

^<<v46-6-8,8>>^ Instead, you wrong and defraud, and your brothers at that!

[[v46-6-9]]

^<<v46-6-9,9>>^ Or do you not know that unrighteous people will not inherit God’s Kingdom? Do not be misled.^&#42;1^ Those who are sexually immoral,^&#42;2^ idolaters, adulterers, men who submit to homosexual acts, men who practice homosexuality,^&#42;3^

[NOTE]
====
. Or “deceived.”
. See Glossary, “Sexual immorality.”
. Or “men who have sex with men.” Lit., “men who lie with men.”
====

[[v46-6-10]]

^<<v46-6-10,10>>^ thieves, greedy people, drunkards, revilers,^&#42;1^ and extortioners will not inherit God’s Kingdom.

[NOTE]
====
. Or “the verbally abusive.”
====

[[v46-6-11]]

^<<v46-6-11,11>>^ And yet that is what some of you were. But you have been washed clean; you have been sanctified; you have been declared righteous in the name of the Lord Jesus Christ and with the spirit of our God.

[[v46-6-12]]

^<<v46-6-12,12>>^ All things are lawful^&#42;1^ for me, but not all things are advantageous. All things are lawful for me, but I will not let myself be controlled^&#42;2^ by anything.

[NOTE]
====
. Or “permissible.”
. Or “brought under authority.”
====

[[v46-6-13]]

^<<v46-6-13,13>>^ Food is for the stomach and the stomach is for food, but God will bring both of them to nothing. The body is not for sexual immorality^&#42;1^ but for the Lord, and the Lord is for the body.

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
====

[[v46-6-14]]

^<<v46-6-14,14>>^ But God raised up the Lord and will also raise us up out of death through his power.

[[v46-6-15]]

^<<v46-6-15,15>>^ Do you not know that your bodies are members of Christ? Should I, then, take the members of the Christ away and join them to a prostitute? By no means!

[[v46-6-16]]

^<<v46-6-16,16>>^ Do you not know that anyone who is joined to a prostitute is one body with her? For “the two,” says he, “will be one flesh.”

[[v46-6-17]]

^<<v46-6-17,17>>^ But whoever is joined to the Lord is one with him in spirit.

[[v46-6-18]]

^<<v46-6-18,18>>^ Flee from sexual immorality!^&#42;1^ Every other sin that a man may commit is outside his body, but whoever practices sexual immorality is sinning against his own body.

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
====

[[v46-6-19]]

^<<v46-6-19,19>>^ Do you not know that your body is the temple of the holy spirit within you, which you have from God? Also, you do not belong to yourselves,

[[v46-6-20]]

^<<v46-6-20,20>>^ for you were bought with a price. By all means, glorify God in your body.

'''

xref:046-1-corinthians/046-1-corinthians-005.adoc#v46-5-0[&#60; Capítulo Anterior] | <<v46-6-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-007.adoc#v46-7-0[Próximo Capítulo &#62;]