include::./index.adoc[]

[[v46-14-0]]
=== The First to the Corinthians, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v46-14-1]]

^<<v46-14-1,1>>^ Pursue love, yet keep striving for^&#42;1^ the spiritual gifts, but preferably that you may prophesy.

[NOTE]
====
. Or “keep zealously seeking.”
====

[[v46-14-2]]

^<<v46-14-2,2>>^ For the one who speaks in a tongue speaks, not to men, but to God, for no one listens, but he speaks sacred secrets by the spirit.

[[v46-14-3]]

^<<v46-14-3,3>>^ However, the one who prophesies builds up and encourages and consoles men by his speech.

[[v46-14-4]]

^<<v46-14-4,4>>^ The one who speaks in a tongue builds up himself, but the one who prophesies builds up a congregation.

[[v46-14-5]]

^<<v46-14-5,5>>^ Now I would like for all of you to speak in tongues, but I prefer that you prophesy. Indeed, the one who prophesies is greater than the one who speaks in tongues, unless he interprets,^&#42;1^ so that the congregation may be built up.

[NOTE]
====
. Or “translates.”
====

[[v46-14-6]]

^<<v46-14-6,6>>^ But at this time, brothers, if I should come speaking to you in tongues, what good would I do you unless I spoke to you either with a revelation or with knowledge or with a prophecy or with a teaching?

[[v46-14-7]]

^<<v46-14-7,7>>^ It is the same with the inanimate things that produce sound, whether a flute or a harp. Unless there is an interval to the tones, how can what is being played on the flute or on the harp be recognized?

[[v46-14-8]]

^<<v46-14-8,8>>^ For if the trumpet sounds an indistinct call, who will get ready for battle?

[[v46-14-9]]

^<<v46-14-9,9>>^ In the same way, unless you with the tongue use speech that is easily understood, how will anyone know what is being said? You will, in fact, be speaking into the air.

[[v46-14-10]]

^<<v46-14-10,10>>^ It may be that there are many kinds of speech in the world, and yet no kind is without meaning.

[[v46-14-11]]

^<<v46-14-11,11>>^ For if I do not understand the sense of the speech, I will be a foreigner to the one speaking, and the one speaking will be a foreigner to me.

[[v46-14-12]]

^<<v46-14-12,12>>^ So also with you, since you eagerly desire the gifts of the spirit, seek to abound in gifts that will build up the congregation.

[[v46-14-13]]

^<<v46-14-13,13>>^ Therefore, let the one who speaks in a tongue pray that he may interpret.^&#42;1^

[NOTE]
====
. Or “translate.”
====

[[v46-14-14]]

^<<v46-14-14,14>>^ For if I am praying in a tongue, it is my gift of the spirit that is praying, but my mind is unproductive.

[[v46-14-15]]

^<<v46-14-15,15>>^ What is to be done, then? I will pray with the gift of the spirit, but I will also pray with my mind. I will sing praise with the gift of the spirit, but I will also sing praise with my mind.

[[v46-14-16]]

^<<v46-14-16,16>>^ Otherwise, if you offer praise with a gift of the spirit, how will the ordinary person in your midst say “Amen” to your giving of thanks, since he does not know what you are saying?

[[v46-14-17]]

^<<v46-14-17,17>>^ True, you are giving thanks in a fine way, but the other man is not being built up.

[[v46-14-18]]

^<<v46-14-18,18>>^ I thank God that I speak in more tongues than all of you do.

[[v46-14-19]]

^<<v46-14-19,19>>^ Nevertheless, in a congregation I would rather speak five words with my mind,^&#42;1^ that I might also instruct^&#42;2^ others, than ten thousand words in a tongue.

[NOTE]
====
. Or “understanding.”
. Or “instruct orally.”
====

[[v46-14-20]]

^<<v46-14-20,20>>^ Brothers, do not become young children in your understanding, but be young children as to badness; and become full-grown in your understanding.

[[v46-14-21]]

^<<v46-14-21,21>>^ In the Law it is written: “‘With the tongues of foreigners and with the lips of strangers I will speak to this people, and even then they will refuse to listen to me,’ says Jehovah.”^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v46-14-22]]

^<<v46-14-22,22>>^ Therefore, tongues are not a sign for the believers but for the unbelievers, whereas prophecy is not for the unbelievers but for the believers.

[[v46-14-23]]

^<<v46-14-23,23>>^ So if the whole congregation comes together to one place and they all speak in tongues, but ordinary people or unbelievers come in, will they not say that you have lost your minds?

[[v46-14-24]]

^<<v46-14-24,24>>^ But if you are all prophesying and an unbeliever or an ordinary person comes in, he will be reproved and closely examined by them all.

[[v46-14-25]]

^<<v46-14-25,25>>^ The secrets of his heart then become evident, so that he will fall facedown and worship God, declaring: “God is really among you.”

[[v46-14-26]]

^<<v46-14-26,26>>^ What is to be done, then, brothers? When you come together, one has a psalm, another has a teaching, another has a revelation, another has a tongue, and another has an interpretation. Let all things take place for building up.

[[v46-14-27]]

^<<v46-14-27,27>>^ And if someone speaks in a tongue, let it be limited to two or three at the most, and in turns, and someone must interpret.^&#42;1^

[NOTE]
====
. Or “translate.”
====

[[v46-14-28]]

^<<v46-14-28,28>>^ But if there is no interpreter,^&#42;1^ he must keep silent in the congregation and speak to himself and to God.

[NOTE]
====
. Or “translator.”
====

[[v46-14-29]]

^<<v46-14-29,29>>^ Let two or three prophets speak, and let the others discern the meaning.

[[v46-14-30]]

^<<v46-14-30,30>>^ But if another one receives a revelation while sitting there, let the first speaker keep silent.

[[v46-14-31]]

^<<v46-14-31,31>>^ For you can all prophesy one at a time, so that all may learn and all may be encouraged.

[[v46-14-32]]

^<<v46-14-32,32>>^ And gifts of the spirit of the prophets are to be controlled by the prophets.

[[v46-14-33]]

^<<v46-14-33,33>>^ For God is a God not of disorder but of peace.
As in all the congregations of the holy ones,

[[v46-14-34]]

^<<v46-14-34,34>>^ let the women keep silent in the congregations, for it is not permitted for them to speak. Rather, let them be in subjection, as the Law also says.

[[v46-14-35]]

^<<v46-14-35,35>>^ If they want to learn something, let them ask their husbands at home, for it is disgraceful for a woman to speak in the congregation.

[[v46-14-36]]

^<<v46-14-36,36>>^ Was it from you that the word of God originated, or did it reach only as far as you?

[[v46-14-37]]

^<<v46-14-37,37>>^ If anyone thinks he is a prophet or is gifted with the spirit, he must acknowledge that the things I am writing to you are the Lord’s commandment.

[[v46-14-38]]

^<<v46-14-38,38>>^ But if anyone disregards this, he will be disregarded.^&#42;1^

[NOTE]
====
. Or possibly, “if anyone is ignorant, he will continue ignorant.”
====

[[v46-14-39]]

^<<v46-14-39,39>>^ So, my brothers, keep striving to prophesy, and yet do not forbid the speaking in tongues.

[[v46-14-40]]

^<<v46-14-40,40>>^ But let all things take place decently and by arrangement.^&#42;1^

[NOTE]
====
. Or “in an orderly manner.”
====

'''

xref:046-1-corinthians/046-1-corinthians-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-015.adoc#v46-15-0[Próximo Capítulo &#62;]