include::./index.adoc[]

[[v6-23-0]]
=== Joshua, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-23-1]]

^<<v6-23-1,1>>^ Many days after Jehovah had given Israel rest from all its surrounding enemies, when Joshua was old and advanced in years,

[[v6-23-2]]

^<<v6-23-2,2>>^ Joshua summoned all Israel, its elders, its heads, its judges, and its officers, and he said to them: “I have grown old; I am advanced in years.

[[v6-23-3]]

^<<v6-23-3,3>>^ And you have seen for yourselves all that Jehovah your God did to all these nations in your behalf because Jehovah your God was the one who was fighting for you.

[[v6-23-4]]

^<<v6-23-4,4>>^ See, I assigned to you by lot^&#42;1^ the land of the nations that remain as an inheritance for your tribes, as well as that of all the nations that I destroyed, from the Jordan to the Great Sea^&#42;2^ on the west.^&#42;3^

[NOTE]
====
. Or “I allotted to you.”
. That is, the Mediterranean.
. Or “toward the sunset.”
====

[[v6-23-5]]

^<<v6-23-5,5>>^ And Jehovah your God was the one who kept thrusting them away from before you, and he drove them out^&#42;1^ for you, and you took possession of their land, just as Jehovah your God promised you.

[NOTE]
====
. Or “dispossessed them.”
====

[[v6-23-6]]

^<<v6-23-6,6>>^ “Now you must be very courageous to observe and carry out all that is written in the book of the Law of Moses by never deviating from it to the right or to the left,

[[v6-23-7]]

^<<v6-23-7,7>>^ by never mingling with these nations that remain with you. You must not even mention the names of their gods nor swear by them, and you must never serve them nor bow down to them.

[[v6-23-8]]

^<<v6-23-8,8>>^ But you must stick to Jehovah your God, just as you have done down to this day.

[[v6-23-9]]

^<<v6-23-9,9>>^ Jehovah will drive away great and mighty nations from before you, for not a man has been able to stand before you to this day.

[[v6-23-10]]

^<<v6-23-10,10>>^ Just one man of you will chase a thousand, because Jehovah your God is fighting for you, just as he promised you.

[[v6-23-11]]

^<<v6-23-11,11>>^ So be on guard constantly^&#42;1^ by loving Jehovah your God.

[NOTE]
====
. Or “So watch your souls carefully.”
====

[[v6-23-12]]

^<<v6-23-12,12>>^ “But if you should turn back at all and stick to what is left of these nations that remain with you and you form marriage alliances^&#42;1^ with them and associate with them and they with you,

[NOTE]
====
. Or “you intermarry.”
====

[[v6-23-13]]

^<<v6-23-13,13>>^ you should know for sure that Jehovah your God will not continue to drive out^&#42;1^ these nations for you. They will become a trap and a snare and a scourge on your flanks and thorns in your eyes until you have perished from this good land that Jehovah your God has given you.

[NOTE]
====
. Or “dispossess.”
====

[[v6-23-14]]

^<<v6-23-14,14>>^ “Now look! I am about to die,^&#42;1^ and you well know with all your heart and with all your soul^&#42;2^ that not one word out of all the good promises that Jehovah your God has spoken to you has failed. They have all come true for you. Not one word of them has failed.

[NOTE]
====
. Lit., “I am going today in the way of all the earth.”
. See Glossary.
====

[[v6-23-15]]

^<<v6-23-15,15>>^ But just as all the good promises that Jehovah your God has spoken to you have come upon you, so Jehovah will bring upon you all the calamity that he promised^&#42;1^ and will annihilate you from this good land that Jehovah your God has given you.

[NOTE]
====
. Or “all the evil word.”
====

[[v6-23-16]]

^<<v6-23-16,16>>^ If you violate the covenant of Jehovah your God that he commanded you to keep and if you go and serve other gods and bow down to them, then Jehovah’s anger will blaze against you and you will quickly perish from the good land that he has given you.”

'''

xref:006-joshua/006-joshua-022.adoc#v6-22-0[&#60; Capítulo Anterior] | <<v6-23-0,Topo>> | xref:006-joshua/006-joshua-024.adoc#v6-24-0[Próximo Capítulo &#62;]