include::./index.adoc[]

[[v6-19-0]]
=== Joshua, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-19-1]]

^<<v6-19-1,1>>^ Then the second lot came out for Simʹe·on, for the tribe of Simʹe·on by their families. And their inheritance was within the inheritance of Judah.

[[v6-19-2]]

^<<v6-19-2,2>>^ Their inheritance was Beʹer-sheʹba with Sheʹba, Mo·laʹdah,

[[v6-19-3]]

^<<v6-19-3,3>>^ Haʹzar-shuʹal, Baʹlah, Eʹzem,

[[v6-19-4]]

^<<v6-19-4,4>>^ El·toʹlad, Beʹthul, Horʹmah,

[[v6-19-5]]

^<<v6-19-5,5>>^ Zikʹlag, Beth-marʹca·both, Haʹzar-suʹsah,

[[v6-19-6]]

^<<v6-19-6,6>>^ Beth-le·baʹoth, and Sha·ruʹhen—13 cities and their settlements;

[[v6-19-7]]

^<<v6-19-7,7>>^ Aʹin, Rimʹmon, Eʹther, and Aʹshan—four cities and their settlements;

[[v6-19-8]]

^<<v6-19-8,8>>^ and all the settlements that were around these cities as far as Baʹal·ath-beʹer, Raʹmah of the south. This was the inheritance of the tribe of Simʹe·on by their families.

[[v6-19-9]]

^<<v6-19-9,9>>^ The inheritance of the descendants of Simʹe·on was taken out of the allotment of Judah, because the share of Judah was too large for them. So the descendants of Simʹe·on received a possession within their inheritance.

[[v6-19-10]]

^<<v6-19-10,10>>^ Next the third lot came up for the descendants of Zebʹu·lun by their families, and the boundary of their inheritance went as far as Saʹrid.

[[v6-19-11]]

^<<v6-19-11,11>>^ Their boundary went up westward to Marʹe·al and reached to Dabʹbe·sheth and then to the valley^&#42;1^ in front of Jokʹne·am.

[NOTE]
====
. Or “wadi.”
====

[[v6-19-12]]

^<<v6-19-12,12>>^ And it went from Saʹrid eastward toward the sunrise, to the border of Chisʹloth-taʹbor and out to Dabʹe·rath and then up to Ja·phiʹa.

[[v6-19-13]]

^<<v6-19-13,13>>^ And from there it continued eastward toward the sunrise to Gath-heʹpher, to Eth-kaʹzin, and out to Rimʹmon, and it extended to Neʹah.

[[v6-19-14]]

^<<v6-19-14,14>>^ And the boundary went around it on the north to Hanʹna·thon, and it ended at the Valley of Iphʹtah-el,

[[v6-19-15]]

^<<v6-19-15,15>>^ and Katʹtath, Na·halʹal, Shimʹron, Iʹda·lah, and Bethʹle·hem—12 cities and their settlements.

[[v6-19-16]]

^<<v6-19-16,16>>^ This was the inheritance of the descendants of Zebʹu·lun by their families. These were the cities and their settlements.

[[v6-19-17]]

^<<v6-19-17,17>>^ The fourth lot came out for Isʹsa·char, for the descendants of Isʹsa·char by their families.

[[v6-19-18]]

^<<v6-19-18,18>>^ And their boundary was to Jezʹre·el, Che·sulʹloth, Shuʹnem,

[[v6-19-19]]

^<<v6-19-19,19>>^ Haphʹa·raʹim, Shiʹon, An·a·haʹrath,

[[v6-19-20]]

^<<v6-19-20,20>>^ Rabʹbith, Kishʹi·on, Eʹbez,

[[v6-19-21]]

^<<v6-19-21,21>>^ Reʹmeth, En-ganʹnim, En-hadʹdah, and Beth-pazʹzez.

[[v6-19-22]]

^<<v6-19-22,22>>^ And the boundary reached to Taʹbor and Sha·ha·zuʹmah and Beth-sheʹmesh, and the end of their border was at the Jordan—16 cities and their settlements.

[[v6-19-23]]

^<<v6-19-23,23>>^ This was the inheritance of the tribe of Isʹsa·char by their families, the cities and their settlements.

[[v6-19-24]]

^<<v6-19-24,24>>^ Then the fifth lot came out for the tribe of Ashʹer by their families.

[[v6-19-25]]

^<<v6-19-25,25>>^ And their boundary was Helʹkath, Haʹli, Beʹten, Achʹshaph,

[[v6-19-26]]

^<<v6-19-26,26>>^ Al·lamʹme·lech, Aʹmad, and Miʹshal. It reached westward to Carʹmel and to Shiʹhor-libʹnath,

[[v6-19-27]]

^<<v6-19-27,27>>^ and it went back toward the east to Beth-daʹgon and reached to Zebʹu·lun and the Valley of Iphʹtah-el to the north, to Beth-eʹmek and Ne·iʹel, and it extended to Caʹbul on the left,

[[v6-19-28]]

^<<v6-19-28,28>>^ and to Eʹbron, Reʹhob, Hamʹmon, and Kaʹnah as far as Great Siʹdon.

[[v6-19-29]]

^<<v6-19-29,29>>^ And the boundary went back to Raʹmah and as far as the fortified city of Tyre. Then the boundary went back to Hoʹsah, and it ended at the sea in the region of Achʹzib,

[[v6-19-30]]

^<<v6-19-30,30>>^ Umʹmah, Aʹphek, and Reʹhob—22 cities and their settlements.

[[v6-19-31]]

^<<v6-19-31,31>>^ This was the inheritance of the tribe of Ashʹer by their families. These were the cities and their settlements.

[[v6-19-32]]

^<<v6-19-32,32>>^ The sixth lot came out for the descendants of Naphʹta·li, for the descendants of Naphʹta·li by their families.

[[v6-19-33]]

^<<v6-19-33,33>>^ Their boundary was from Heʹleph, from the big tree in Za·a·nanʹnim, and Adʹa·mi-neʹkeb and Jabʹne·el as far as Lakʹkum; and it ended at the Jordan.

[[v6-19-34]]

^<<v6-19-34,34>>^ The boundary went back westward to Azʹnoth-taʹbor and extended from there to Hukʹkok and reached to Zebʹu·lun on the south and to Ashʹer on the west and to Judah at the Jordan toward the east.

[[v6-19-35]]

^<<v6-19-35,35>>^ And the fortified cities were Zidʹdim, Zer, Hamʹmath, Rakʹkath, Chinʹne·reth,

[[v6-19-36]]

^<<v6-19-36,36>>^ Adʹa·mah, Raʹmah, Haʹzor,

[[v6-19-37]]

^<<v6-19-37,37>>^ Keʹdesh, Edʹre·i, En-haʹzor,

[[v6-19-38]]

^<<v6-19-38,38>>^ Yiʹron, Migʹdal-el, Hoʹrem, Beth-aʹnath, and Beth-sheʹmesh—19 cities and their settlements.

[[v6-19-39]]

^<<v6-19-39,39>>^ This was the inheritance of the tribe of Naphʹta·li by their families, the cities and their settlements.

[[v6-19-40]]

^<<v6-19-40,40>>^ The seventh lot came out for the tribe of Dan by their families.

[[v6-19-41]]

^<<v6-19-41,41>>^ And the border of their inheritance was Zorʹah, Eshʹta·ol, Ir-sheʹmesh,

[[v6-19-42]]

^<<v6-19-42,42>>^ Sha·al·abʹbin, Aiʹja·lon, Ithʹlah,

[[v6-19-43]]

^<<v6-19-43,43>>^ Eʹlon, Timʹnah, Ekʹron,

[[v6-19-44]]

^<<v6-19-44,44>>^ Elʹte·keh, Gibʹbe·thon, Baʹal·ath,

[[v6-19-45]]

^<<v6-19-45,45>>^ Jeʹhud, Benʹe-beʹrak, Gath-rimʹmon,

[[v6-19-46]]

^<<v6-19-46,46>>^ Me-jarʹkon, and Rakʹkon, with the border facing Jopʹpa.

[[v6-19-47]]

^<<v6-19-47,47>>^ But the territory of Dan was too cramped for them. So they went up and fought against Leʹshem and captured it and struck it with the sword. Then they took possession of it and settled in it, and they changed the name of Leʹshem to Dan, after the name of Dan their forefather.

[[v6-19-48]]

^<<v6-19-48,48>>^ This was the inheritance of the tribe of Dan by their families. These were the cities and their settlements.

[[v6-19-49]]

^<<v6-19-49,49>>^ Thus they finished dividing the land for inheritance by its territories. Then the Israelites gave Joshua the son of Nun an inheritance in their midst.

[[v6-19-50]]

^<<v6-19-50,50>>^ At the order of Jehovah they gave him the city he asked for, Timʹnath-seʹrah, in the mountainous region of Eʹphra·im, and he built up the city and settled in it.

[[v6-19-51]]

^<<v6-19-51,51>>^ These were the inheritances that El·e·aʹzar the priest, Joshua the son of Nun, and the heads of the paternal houses of the tribes of Israel distributed by lot in Shiʹloh before Jehovah, at the entrance of the tent of meeting. So they finished apportioning the land.

'''

xref:006-joshua/006-joshua-018.adoc#v6-18-0[&#60; Capítulo Anterior] | <<v6-19-0,Topo>> | xref:006-joshua/006-joshua-020.adoc#v6-20-0[Próximo Capítulo &#62;]