include::./index.adoc[]

[[v6-10-0]]
=== Joshua, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-10-1]]

^<<v6-10-1,1>>^ As soon as King A·doʹni-zeʹdek of Jerusalem heard that Joshua had captured Aʹi and devoted it to destruction, doing to Aʹi and its king just as he had done to Jerʹi·cho and its king, and how the inhabitants of Gibʹe·on had made peace with Israel and remained among them,

[[v6-10-2]]

^<<v6-10-2,2>>^ he was greatly alarmed, because Gibʹe·on was a great city, like one of the royal cities. It was greater than Aʹi, and all its men were warriors.

[[v6-10-3]]

^<<v6-10-3,3>>^ So A·doʹni-zeʹdek king of Jerusalem sent this message to Hoʹham king of Hebʹron, Piʹram king of Jarʹmuth, Ja·phiʹa king of Laʹchish, and Deʹbir king of Egʹlon:

[[v6-10-4]]

^<<v6-10-4,4>>^ “Come to my aid, and let us attack Gibʹe·on, because it has made peace with Joshua and the Israelites.”

[[v6-10-5]]

^<<v6-10-5,5>>^ At this the five kings of the Amʹor·ites—the king of Jerusalem, the king of Hebʹron, the king of Jarʹmuth, the king of Laʹchish, and the king of Egʹlon—gathered together along with their armies, and they marched on and encamped against Gibʹe·on to fight against it.

[[v6-10-6]]

^<<v6-10-6,6>>^ Then the men of Gibʹe·on sent word to Joshua at the camp at Gilʹgal: “Do not forsake^&#42;1^ your slaves. Come quickly! Rescue us and help us! All the kings of the Amʹor·ites from the mountainous region have gathered against us.”

[NOTE]
====
. Lit., “let your hand drop from.”
====

[[v6-10-7]]

^<<v6-10-7,7>>^ So Joshua went up from Gilʹgal with all the fighting men and the mighty warriors.

[[v6-10-8]]

^<<v6-10-8,8>>^ Jehovah then said to Joshua: “Do not be afraid of them, for I have handed them over to you. Not one of them will be able to stand against you.”

[[v6-10-9]]

^<<v6-10-9,9>>^ Joshua came against them by surprise after marching all night long from Gilʹgal.

[[v6-10-10]]

^<<v6-10-10,10>>^ Jehovah threw them into confusion before Israel, and they inflicted a great slaughter on them at Gibʹe·on, pursuing them by way of the ascent of Beth-hoʹron and striking them down as far as A·zeʹkah and Mak·keʹdah.

[[v6-10-11]]

^<<v6-10-11,11>>^ While they were fleeing from Israel and were on the descent of Beth-hoʹron, Jehovah hurled great hailstones from the sky on them as far as A·zeʹkah, and they perished. In fact, more died from the hail than from the sword of the Israelites.

[[v6-10-12]]

^<<v6-10-12,12>>^ It was then, on the day that Jehovah routed the Amʹor·ites before the eyes of the Israelites, that Joshua said to Jehovah before Israel:
“Sun, stand still over Gibʹe·on,
And moon, over the Valley^&#42;1^ of Aiʹja·lon!”

[NOTE]
====
. Or “Low Plain.”
====

[[v6-10-13]]

^<<v6-10-13,13>>^ So the sun stood still and the moon did not move until the nation could take vengeance on its enemies. Is it not written in the book of Jaʹshar? The sun stood still in the middle of the sky and did not hasten to set for about a whole day.

[[v6-10-14]]

^<<v6-10-14,14>>^ There has never been a day like that one, either before it or after it, when Jehovah listened to the voice of a man, for Jehovah was fighting for Israel.

[[v6-10-15]]

^<<v6-10-15,15>>^ After that Joshua together with all Israel returned to the camp at Gilʹgal.

[[v6-10-16]]

^<<v6-10-16,16>>^ Meanwhile, the five kings fled and hid in the cave at Mak·keʹdah.

[[v6-10-17]]

^<<v6-10-17,17>>^ Then it was reported to Joshua: “The five kings have been found hiding in the cave at Mak·keʹdah.”

[[v6-10-18]]

^<<v6-10-18,18>>^ So Joshua said: “Roll large stones over the mouth of the cave and assign men to guard them.

[[v6-10-19]]

^<<v6-10-19,19>>^ But the rest of you should not stop. Pursue your enemies and strike them from the rear. Do not allow them to enter into their cities, for Jehovah your God has given them into your hands.”

[[v6-10-20]]

^<<v6-10-20,20>>^ After Joshua and the Israelites had finished inflicting a very great slaughter on them, to the point of wiping them out except for some survivors who escaped and entered into the fortified cities,

[[v6-10-21]]

^<<v6-10-21,21>>^ all the people returned safely to Joshua at the camp at Mak·keʹdah. Not a man dared to utter a word^&#42;1^ against the Israelites.

[NOTE]
====
. Lit., “sharpened his tongue.”
====

[[v6-10-22]]

^<<v6-10-22,22>>^ Then Joshua said: “Open the mouth of the cave and bring the five kings out of the cave to me.”

[[v6-10-23]]

^<<v6-10-23,23>>^ So they brought to him from the cave these five kings: the king of Jerusalem, the king of Hebʹron, the king of Jarʹmuth, the king of Laʹchish, and the king of Egʹlon.

[[v6-10-24]]

^<<v6-10-24,24>>^ When they brought these kings to Joshua, he summoned all the men of Israel and said to the commanders of the fighting men who had gone with him: “Come forward. Place your feet on the backs of the necks of these kings.” So they came forward and placed their feet on the backs of their necks.

[[v6-10-25]]

^<<v6-10-25,25>>^ Then Joshua said to them: “Do not be afraid or be terrified. Be courageous and strong, for this is what Jehovah will do to all your enemies against whom you are fighting.”

[[v6-10-26]]

^<<v6-10-26,26>>^ Then Joshua struck them and put them to death and hung them on five stakes,^&#42;1^ and they remained hanging on the stakes until the evening.

[NOTE]
====
. Or “trees.”
====

[[v6-10-27]]

^<<v6-10-27,27>>^ At sunset Joshua ordered that they be taken down off the stakes and thrown into the cave where they had hidden themselves. Then large stones were placed at the mouth of the cave, and these remain to this very day.

[[v6-10-28]]

^<<v6-10-28,28>>^ Joshua captured Mak·keʹdah on that day and struck it with the sword. He devoted its king and everyone^&#42;1^ in it to destruction, letting no survivor remain. He did to the king of Mak·keʹdah just as he had done to the king of Jerʹi·cho.

[NOTE]
====
. Or “every soul.”
====

[[v6-10-29]]

^<<v6-10-29,29>>^ Then Joshua together with all Israel went from Mak·keʹdah to Libʹnah and fought against Libʹnah.

[[v6-10-30]]

^<<v6-10-30,30>>^ Jehovah also gave it and its king into Israel’s hand, and they struck it and everyone^&#42;1^ in it with the sword, not letting a survivor remain in it. So they did to its king just as they had done to the king of Jerʹi·cho.

[NOTE]
====
. Or “every soul.”
====

[[v6-10-31]]

^<<v6-10-31,31>>^ Next Joshua together with all Israel went from Libʹnah to Laʹchish and camped there and fought against it.

[[v6-10-32]]

^<<v6-10-32,32>>^ Jehovah gave Laʹchish into Israel’s hand, and they captured it on the second day. They struck it and everyone^&#42;1^ in it with the sword, just as they had done to Libʹnah.

[NOTE]
====
. Or “every soul.”
====

[[v6-10-33]]

^<<v6-10-33,33>>^ Then Hoʹram king of Geʹzer went up to help Laʹchish, but Joshua struck him and his people down until not one survivor remained.

[[v6-10-34]]

^<<v6-10-34,34>>^ Then Joshua together with all Israel went from Laʹchish to Egʹlon and camped there and fought against it.

[[v6-10-35]]

^<<v6-10-35,35>>^ They captured it on that day and struck it with the sword. They devoted everyone^&#42;1^ in it to destruction on that day, just as they had done to Laʹchish.

[NOTE]
====
. Or “every soul.”
====

[[v6-10-36]]

^<<v6-10-36,36>>^ Then Joshua together with all Israel went up from Egʹlon to Hebʹron and fought against it.

[[v6-10-37]]

^<<v6-10-37,37>>^ They captured it and struck it, its king, its towns, and everyone^&#42;1^ in it with the sword, not letting any survivor remain. Just as he had done to Egʹlon, he devoted it and everyone^&#42;2^ in it to destruction.

[NOTE]
====
. Or “every soul.”
. Or “every soul.”
====

[[v6-10-38]]

^<<v6-10-38,38>>^ Finally Joshua together with all Israel turned toward Deʹbir and fought against it.

[[v6-10-39]]

^<<v6-10-39,39>>^ He captured it, its king, and all its towns, and they struck them down with the sword, devoting everyone^&#42;1^ in it to destruction, not letting any survivor remain. He did to Deʹbir and its king just as he had done to Hebʹron and to Libʹnah and its king.

[NOTE]
====
. Or “every soul.”
====

[[v6-10-40]]

^<<v6-10-40,40>>^ Joshua conquered all the land of the mountainous region, the Negʹeb, the She·pheʹlah, and the slopes, and all their kings, not letting any survivor remain; he devoted everything that breathed to destruction, just as Jehovah the God of Israel had commanded.

[[v6-10-41]]

^<<v6-10-41,41>>^ Joshua conquered them from Kaʹdesh-barʹne·a to Gazʹa and all the land of Goʹshen and up to Gibʹe·on.

[[v6-10-42]]

^<<v6-10-42,42>>^ Joshua captured all these kings and their land, all at the same time, because it was Jehovah the God of Israel who was fighting for Israel.

[[v6-10-43]]

^<<v6-10-43,43>>^ Then Joshua returned with all Israel to the camp at Gilʹgal.

'''

xref:006-joshua/006-joshua-009.adoc#v6-9-0[&#60; Capítulo Anterior] | <<v6-10-0,Topo>> | xref:006-joshua/006-joshua-011.adoc#v6-11-0[Próximo Capítulo &#62;]