include::./index.adoc[]

[[v6-22-0]]
=== Joshua, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-22-1]]

^<<v6-22-1,1>>^ Then Joshua summoned the Reuʹben·ites, the Gadʹites, and the half tribe of Ma·nasʹseh

[[v6-22-2]]

^<<v6-22-2,2>>^ and said to them: “You have done all that Moses the servant of Jehovah commanded you, and you have obeyed my voice in all that I commanded you.

[[v6-22-3]]

^<<v6-22-3,3>>^ You have not forsaken your brothers all this time, down to this day; and you have kept the obligation of the commandment of Jehovah your God.

[[v6-22-4]]

^<<v6-22-4,4>>^ Now Jehovah your God has given your brothers rest, just as he promised them. So now you may return to your tents in the land that Moses the servant of Jehovah gave you to possess on the other side^&#42;1^ of the Jordan.

[NOTE]
====
. That is, the east side.
====

[[v6-22-5]]

^<<v6-22-5,5>>^ Only be very careful to carry out the commandment and the Law that Moses the servant of Jehovah gave you, by loving Jehovah your God, by walking in all his ways, by keeping his commandments, by sticking to him, and by serving him with all your heart and with all your soul.”^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v6-22-6]]

^<<v6-22-6,6>>^ Then Joshua blessed them and sent them away, and they went to their tents.

[[v6-22-7]]

^<<v6-22-7,7>>^ And to the half tribe of Ma·nasʹseh, Moses had given an inheritance in Baʹshan, and to the other half of the tribe, Joshua gave land on the west side of the Jordan, along with their brothers. Moreover, when Joshua sent them away to their tents, he blessed them

[[v6-22-8]]

^<<v6-22-8,8>>^ and said to them: “Return to your tents with many riches, with very much livestock, with silver and gold, copper and iron, and garments in very great quantity. Take your share of the spoil of your enemies, along with your brothers.”

[[v6-22-9]]

^<<v6-22-9,9>>^ After that the Reuʹben·ites, the Gadʹites, and the half tribe of Ma·nasʹseh departed from the other Israelites, from Shiʹloh in the land of Caʹnaan, and they returned to the land of Gilʹe·ad, the land of their possession where they had settled at the order of Jehovah through Moses.

[[v6-22-10]]

^<<v6-22-10,10>>^ When they came to the regions of the Jordan in the land of Caʹnaan, the Reuʹben·ites, the Gadʹites, and the half tribe of Ma·nasʹseh built an altar there by the Jordan, a large, impressive altar.

[[v6-22-11]]

^<<v6-22-11,11>>^ Later the other Israelites heard it said: “Look! The Reuʹben·ites, the Gadʹites, and the half tribe of Ma·nasʹseh have built an altar on the frontier of the land of Caʹnaan in the regions of the Jordan on the side belonging to the Israelites.”

[[v6-22-12]]

^<<v6-22-12,12>>^ When the Israelites heard about it, the whole assembly of the Israelites congregated at Shiʹloh to go to war against them.

[[v6-22-13]]

^<<v6-22-13,13>>^ Then the Israelites sent Phinʹe·has the son of El·e·aʹzar the priest to the Reuʹben·ites, the Gadʹites, and the half tribe of Ma·nasʹseh in the land of Gilʹe·ad,

[[v6-22-14]]

^<<v6-22-14,14>>^ and ten chieftains were with him, one chieftain of each paternal house of all the tribes of Israel, each a head of his paternal house among the thousands^&#42;1^ of Israel.

[NOTE]
====
. Or “clans.”
====

[[v6-22-15]]

^<<v6-22-15,15>>^ When they came to the Reuʹben·ites, the Gadʹites, and the half tribe of Ma·nasʹseh in the land of Gilʹe·ad, they said to them:

[[v6-22-16]]

^<<v6-22-16,16>>^ “This is what all the assembly of Jehovah says: ‘What is this act of unfaithfulness that you have committed against the God of Israel? You have turned back today from following Jehovah by building yourselves an altar and rebelling against Jehovah.

[[v6-22-17]]

^<<v6-22-17,17>>^ Was the error of Peʹor not enough for us? We have not cleansed ourselves from it down to this day, even though a plague came upon the assembly of Jehovah.

[[v6-22-18]]

^<<v6-22-18,18>>^ And you would turn back today from following Jehovah! If you rebel today against Jehovah, then tomorrow he will be indignant against the entire assembly of Israel.

[[v6-22-19]]

^<<v6-22-19,19>>^ Now if it is because the land of your possession is unclean, cross over to the land of Jehovah’s possession where the tabernacle of Jehovah resides and settle among us, but do not rebel against Jehovah, and do not make us rebels by building yourselves an altar in addition to the altar of Jehovah our God.

[[v6-22-20]]

^<<v6-22-20,20>>^ When Aʹchan the son of Zeʹrah committed an act of unfaithfulness regarding what was devoted to destruction, did not indignation come against all the assembly of Israel? And he was not the only man to die for his error.’”

[[v6-22-21]]

^<<v6-22-21,21>>^ At this the Reuʹben·ites, the Gadʹites, and the half tribe of Ma·nasʹseh said in answer to the heads of the thousands^&#42;1^ of Israel:

[NOTE]
====
. Or “clans.”
====

[[v6-22-22]]

^<<v6-22-22,22>>^ “The God of gods, Jehovah!^&#42;1^ The God of gods, Jehovah! He knows, and Israel will also know. If we were rebellious and unfaithful to Jehovah, do not spare us this day.

[NOTE]
====
. Or “The Divine One, God, Jehovah.”
====

[[v6-22-23]]

^<<v6-22-23,23>>^ If we built ourselves an altar to turn back from following Jehovah and to offer burnt offerings, grain offerings, and communion sacrifices on it, Jehovah will exact the penalty.

[[v6-22-24]]

^<<v6-22-24,24>>^ No, it was because of another concern that we did this, for we said, ‘In the future, your sons will say to our sons: “What do you have to do with Jehovah the God of Israel?

[[v6-22-25]]

^<<v6-22-25,25>>^ Jehovah has put the Jordan as a boundary between us and you, the Reuʹben·ites and the Gadʹites. You have no share in Jehovah.” And your sons will hinder our sons from worshipping^&#42;1^ Jehovah.’

[NOTE]
====
. Lit., “fearing.”
====

[[v6-22-26]]

^<<v6-22-26,26>>^ “So we said, ‘Let us by all means take action by building an altar, not for burnt offerings or sacrifices,

[[v6-22-27]]

^<<v6-22-27,27>>^ but to be a witness between you and us and our descendants^&#42;1^ after us that we will carry out our service to Jehovah before him with our burnt offerings and our sacrifices and our communion sacrifices, so that your sons may not say to our sons in the future: “You have no share in Jehovah.”’

[NOTE]
====
. Lit., “generations.”
====

[[v6-22-28]]

^<<v6-22-28,28>>^ So we said, ‘If they should say that to us and to our descendants^&#42;1^ in the future, we will then say: “See the replica of Jehovah’s altar that our forefathers made, not for burnt offerings or sacrifices, but to be a witness between you and us.”’

[NOTE]
====
. Lit., “generations.”
====

[[v6-22-29]]

^<<v6-22-29,29>>^ It is unthinkable for us to rebel against Jehovah and to turn back today from following Jehovah by building an altar for burnt offerings, grain offerings, and sacrifices, other than the altar of Jehovah our God that is before his tabernacle!”

[[v6-22-30]]

^<<v6-22-30,30>>^ When Phinʹe·has the priest, the chieftains of the assembly, and the heads of the thousands^&#42;1^ of Israel who were with him heard the words that the descendants of Reuʹben, Gad, and Ma·nasʹseh spoke, they were satisfied.

[NOTE]
====
. Or “clans.”
====

[[v6-22-31]]

^<<v6-22-31,31>>^ So Phinʹe·has the son of El·e·aʹzar the priest said to the descendants of Reuʹben, Gad, and Ma·nasʹseh: “Today we know that Jehovah is among us, because you have not committed this act of unfaithfulness against Jehovah. Now you have saved the Israelites out of the hand of Jehovah.”

[[v6-22-32]]

^<<v6-22-32,32>>^ Then Phinʹe·has the son of El·e·aʹzar the priest and the chieftains returned from the Reuʹben·ites and the Gadʹites in the land of Gilʹe·ad to the land of Caʹnaan, and they brought back word to the other Israelites.

[[v6-22-33]]

^<<v6-22-33,33>>^ And the Israelites were satisfied with the report. The Israelites then praised God, and they said nothing more about going to war against the Reuʹben·ites and the Gadʹites to destroy the land in which they were dwelling.

[[v6-22-34]]

^<<v6-22-34,34>>^ So the Reuʹben·ites and the Gadʹites named the altar,^&#42;1^ because “it is a witness between us that Jehovah is the true God.”

[NOTE]
====
. From the explanation given, the altar was likely named Witness.
====

'''

xref:006-joshua/006-joshua-021.adoc#v6-21-0[&#60; Capítulo Anterior] | <<v6-22-0,Topo>> | xref:006-joshua/006-joshua-023.adoc#v6-23-0[Próximo Capítulo &#62;]