include::./index.adoc[]

[[v6-3-0]]
=== Joshua, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-3-1]]

^<<v6-3-1,1>>^ Then Joshua got up early in the morning, and he and all the Israelites^&#42;1^ departed from Shitʹtim and came to the Jordan. They spent the night there before crossing over.

[NOTE]
====
. Lit., “sons of Israel.”
====

[[v6-3-2]]

^<<v6-3-2,2>>^ After three days, the officers passed throughout the camp

[[v6-3-3]]

^<<v6-3-3,3>>^ and commanded the people: “As soon as you see the ark of the covenant of Jehovah your God being carried by the Levitical priests, you should depart from your place and follow it.

[[v6-3-4]]

^<<v6-3-4,4>>^ But keep a distance of about 2,000 cubits^&#42;1^ from it; do not come any nearer to it, so that you may know which is the way to go, for you have not traveled on this way before.”

[NOTE]
====
. About 890 m (2,920 ft). See App. B14.
====

[[v6-3-5]]

^<<v6-3-5,5>>^ Joshua now said to the people: “Sanctify yourselves, for tomorrow Jehovah will do wonderful things among you.”

[[v6-3-6]]

^<<v6-3-6,6>>^ Then Joshua said to the priests: “Take up the ark of the covenant and pass ahead of the people.” So they took up the ark of the covenant and went ahead of the people.

[[v6-3-7]]

^<<v6-3-7,7>>^ Then Jehovah said to Joshua: “This day I will start to exalt you in the eyes of all Israel, so that they may know that I will be with you just as I was with Moses.

[[v6-3-8]]

^<<v6-3-8,8>>^ You should give this command to the priests carrying the ark of the covenant: ‘When you reach the edge of the waters of the Jordan, you should stand still in the Jordan.’”

[[v6-3-9]]

^<<v6-3-9,9>>^ And Joshua said to the Israelites: “Come here and listen to the words of Jehovah your God.”

[[v6-3-10]]

^<<v6-3-10,10>>^ Joshua then said: “By this you will know that a living God is among you, and that he will without fail drive away from before you the Caʹnaan·ites, the Hitʹtites, the Hiʹvites, the Perʹiz·zites, the Girʹga·shites, the Amʹor·ites, and the Jebʹu·sites.

[[v6-3-11]]

^<<v6-3-11,11>>^ Look! The ark of the covenant of the Lord of the whole earth is passing ahead of you into the Jordan.

[[v6-3-12]]

^<<v6-3-12,12>>^ Now take 12 men from the tribes of Israel, one man for each tribe,

[[v6-3-13]]

^<<v6-3-13,13>>^ and as soon as the soles of the feet of the priests carrying the Ark of Jehovah, the Lord of the whole earth, touch^&#42;1^ the waters of the Jordan, the waters of the Jordan flowing from upstream will be halted and they will stand still like a dam.”^&#42;2^

[NOTE]
====
. Lit., “rest in.”
. Or “wall.”
====

[[v6-3-14]]

^<<v6-3-14,14>>^ So when the people departed from their tents just before crossing the Jordan, the priests carrying the ark of the covenant went ahead of the people.

[[v6-3-15]]

^<<v6-3-15,15>>^ As soon as the carriers of the Ark reached the Jordan and the priests carrying the Ark dipped their feet into the edge of the waters (now the Jordan overflows its banks all the days of harvest),

[[v6-3-16]]

^<<v6-3-16,16>>^ the waters flowing from upstream stood still. They rose up like a dam^&#42;1^ very far away at Adam, the city near Zarʹe·than, while the waters descending toward the Sea of the Arʹa·bah, the Salt Sea,^&#42;2^ drained away. They were halted, and the people crossed over opposite Jerʹi·cho.

[NOTE]
====
. Or “wall.”
. That is, the Dead Sea.
====

[[v6-3-17]]

^<<v6-3-17,17>>^ While the priests carrying the ark of Jehovah’s covenant kept standing still on dry ground in the middle of the Jordan, all Israel crossed over on dry ground until the whole nation had finished crossing the Jordan.

'''

xref:006-joshua/006-joshua-002.adoc#v6-2-0[&#60; Capítulo Anterior] | <<v6-3-0,Topo>> | xref:006-joshua/006-joshua-004.adoc#v6-4-0[Próximo Capítulo &#62;]