include::./index.adoc[]

[[v6-16-0]]
=== Joshua, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-16-1]]

^<<v6-16-1,1>>^ And the land that fell by lot^&#42;1^ to the descendants of Joseph was from the Jordan at Jerʹi·cho to the waters east of Jerʹi·cho, through the wilderness going up from Jerʹi·cho into the mountainous region of Bethʹel.

[NOTE]
====
. Or “was allotted.”
====

[[v6-16-2]]

^<<v6-16-2,2>>^ It extended from Bethʹel belonging to Luz and continued to the boundary of the Arʹchites at Atʹa·roth,

[[v6-16-3]]

^<<v6-16-3,3>>^ then it went down westward to the boundary of the Japhʹle·tites as far as the boundary of Lower Beth-hoʹron and Geʹzer, and it ended at the sea.

[[v6-16-4]]

^<<v6-16-4,4>>^ So Joseph’s descendants, Ma·nasʹseh and Eʹphra·im, took possession of their land.

[[v6-16-5]]

^<<v6-16-5,5>>^ The boundary of the descendants of Eʹphra·im by their families was as follows: The boundary of their inheritance to the east was Atʹa·roth-adʹdar, as far as Upper Beth-hoʹron,

[[v6-16-6]]

^<<v6-16-6,6>>^ and the boundary extended to the sea. Mich·meʹthath was on the north, and the boundary went around east to Taʹa·nath-shiʹloh, and it passed on the east to Ja·noʹah.

[[v6-16-7]]

^<<v6-16-7,7>>^ Then it went down from Ja·noʹah to Atʹa·roth and Naʹa·rah and reached to Jerʹi·cho and extended to the Jordan.

[[v6-16-8]]

^<<v6-16-8,8>>^ From Tapʹpu·ah the boundary continued westward to the Wadi of Kaʹnah, and it ended at the sea. This is the inheritance of the tribe of Eʹphra·im by their families;

[[v6-16-9]]

^<<v6-16-9,9>>^ the descendants of Eʹphra·im also had enclave cities in the midst of the inheritance of Ma·nasʹseh, all the cities and their settlements.

[[v6-16-10]]

^<<v6-16-10,10>>^ But they did not drive away the Caʹnaan·ites who were dwelling in Geʹzer, and the Caʹnaan·ites continue to dwell among Eʹphra·im to this day and have been subjected to forced labor.

'''

xref:006-joshua/006-joshua-015.adoc#v6-15-0[&#60; Capítulo Anterior] | <<v6-16-0,Topo>> | xref:006-joshua/006-joshua-017.adoc#v6-17-0[Próximo Capítulo &#62;]