include::./index.adoc[]

[[v6-13-0]]
=== Joshua, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-13-1]]

^<<v6-13-1,1>>^ Now Joshua had grown old and was advanced in years. So Jehovah said to him: “You have grown old and are advanced in years; but much of the land remains to be taken in possession.^&#42;1^

[NOTE]
====
. Or “be conquered.”
====

[[v6-13-2]]

^<<v6-13-2,2>>^ This is the land remaining: all the regions of the Phi·lisʹtines and all the Geshʹur·ites

[[v6-13-3]]

^<<v6-13-3,3>>^ (from the branch of the Nile^&#42;1^ that is east of^&#42;2^ Egypt up to the border of Ekʹron to the north, which used to be considered Caʹnaan·ite territory) including that of the five lords of the Phi·lisʹtines—the Gazʹites, the Ashʹdod·ites, the Ashʹke·lon·ites, the Gitʹtites, and the Ekʹron·ites; that of the Avʹvim

[NOTE]
====
. Or “from Shihor.”
. Lit., “in front of.”
====

[[v6-13-4]]

^<<v6-13-4,4>>^ to the south; all the land of the Caʹnaan·ites; Me·arʹah, which belongs to the Si·doʹni·ans, as far as Aʹphek, to the border of the Amʹor·ites;

[[v6-13-5]]

^<<v6-13-5,5>>^ the land of the Geʹbal·ites and all of Lebʹa·non toward the east, from Baʹal-gad at the base of Mount Herʹmon to Leʹbo-haʹmath;^&#42;1^

[NOTE]
====
. Or “the entrance of Hamath.”
====

[[v6-13-6]]

^<<v6-13-6,6>>^ all the inhabitants of the mountainous region from Lebʹa·non to Misʹre·photh-maʹim; and all the Si·doʹni·ans. I will drive them out^&#42;1^ before the Israelites. You have only to assign it to Israel as an inheritance, just as I have commanded you.

[NOTE]
====
. Or “dispossess them.”
====

[[v6-13-7]]

^<<v6-13-7,7>>^ Now you must apportion this land as an inheritance to the nine tribes and the half tribe of Ma·nasʹseh.”

[[v6-13-8]]

^<<v6-13-8,8>>^ With the other half tribe, the Reuʹben·ites and the Gadʹites took their inheritance that Moses gave them on the east side of the Jordan, just as Moses the servant of Jehovah had given them:

[[v6-13-9]]

^<<v6-13-9,9>>^ from A·roʹer, which is on the rim of the Arʹnon Valley,^&#42;1^ and the city that is in the middle of the valley, and all the tableland^&#42;2^ of Medʹe·ba as far as Diʹbon;

[NOTE]
====
. Or “Wadi Arnon.”
. Or “plateau.”
====

[[v6-13-10]]

^<<v6-13-10,10>>^ and all the cities of King Siʹhon of the Amʹor·ites, who reigned in Heshʹbon, up to the border of the Amʹmon·ites;

[[v6-13-11]]

^<<v6-13-11,11>>^ also Gilʹe·ad and the territory of the Geshʹur·ites and the Ma·acʹa·thites and all Mount Herʹmon and all Baʹshan as far as Salʹe·cah;

[[v6-13-12]]

^<<v6-13-12,12>>^ all the royal realm of Og in Baʹshan, who reigned in Ashʹta·roth and in Edʹre·i. (He was one of the last of the Rephʹa·im.) Moses defeated them and drove them out.^&#42;1^

[NOTE]
====
. Or “dispossessed them.”
====

[[v6-13-13]]

^<<v6-13-13,13>>^ But the Israelites did not drive out^&#42;1^ the Geshʹur·ites and the Ma·acʹa·thites, for Geshʹur and Maʹa·cath live in the midst of Israel to this day.

[NOTE]
====
. Or “dispossess.”
====

[[v6-13-14]]

^<<v6-13-14,14>>^ It was only to the tribe of the Levites that he did not give an inheritance. The offerings made by fire to Jehovah the God of Israel are their inheritance, just as he promised them.

[[v6-13-15]]

^<<v6-13-15,15>>^ Then Moses gave an inheritance to the tribe of the Reuʹben·ites by their families,

[[v6-13-16]]

^<<v6-13-16,16>>^ and their territory was from A·roʹer, which is on the rim of the Arʹnon Valley,^&#42;1^ and the city in the middle of the valley, and all the tableland by Medʹe·ba;

[NOTE]
====
. Or “Wadi Arnon.”
====

[[v6-13-17]]

^<<v6-13-17,17>>^ Heshʹbon and all its towns on the tableland, Diʹbon, Baʹmoth-baʹal, Beth-baʹal-meʹon,

[[v6-13-18]]

^<<v6-13-18,18>>^ Jaʹhaz, Kedʹe·moth, Mephʹa·ath,

[[v6-13-19]]

^<<v6-13-19,19>>^ Kir·i·a·thaʹim, Sibʹmah, and Zeʹreth-shaʹhar on the mountain of the valley,^&#42;1^

[NOTE]
====
. Or “low plain.”
====

[[v6-13-20]]

^<<v6-13-20,20>>^ Beth-peʹor, the slopes of Pisʹgah, Beth-jeshʹi·moth,

[[v6-13-21]]

^<<v6-13-21,21>>^ all the cities of the tableland, and all the royal realm of King Siʹhon of the Amʹor·ites, who reigned in Heshʹbon. Moses defeated him and the Midʹi·an·ite chieftains Eʹvi, Reʹkem, Zur, Hur, and Reʹba, vassals^&#42;1^ of Siʹhon who were dwelling in the land.

[NOTE]
====
. That is, kings who were subject to Sihon.
====

[[v6-13-22]]

^<<v6-13-22,22>>^ Baʹlaam the son of Beʹor, the diviner, was one whom the Israelites killed with the sword along with the rest who were slain.

[[v6-13-23]]

^<<v6-13-23,23>>^ The boundary of the Reuʹben·ites was the Jordan; and this territory was the inheritance of the Reuʹben·ites by their families, with the cities and their settlements.

[[v6-13-24]]

^<<v6-13-24,24>>^ Furthermore, Moses gave an inheritance to the tribe of Gad, the Gadʹites by their families,

[[v6-13-25]]

^<<v6-13-25,25>>^ and their territory included Jaʹzer and all the cities of Gilʹe·ad and half of the land of the Amʹmon·ites as far as A·roʹer, which faces Rabʹbah;

[[v6-13-26]]

^<<v6-13-26,26>>^ and from Heshʹbon to Raʹmath-mizʹpeh and Betʹo·nim, and from Ma·ha·naʹim to the border of Deʹbir;

[[v6-13-27]]

^<<v6-13-27,27>>^ and in the valley,^&#42;1^ Beth-haʹram, Beth-nimʹrah, Sucʹcoth, and Zaʹphon, the rest of the royal realm of King Siʹhon of Heshʹbon, with the Jordan as the border from the lower end of the Sea of Chinʹne·reth^&#42;2^ on the east side of the Jordan.

[NOTE]
====
. Or “low plain.”
. That is, the lake of Gennesaret, or the Sea of Galilee.
====

[[v6-13-28]]

^<<v6-13-28,28>>^ This was the inheritance of the Gadʹites by their families, with the cities and their settlements.

[[v6-13-29]]

^<<v6-13-29,29>>^ Further, Moses gave an inheritance to the half tribe of Ma·nasʹseh, to half of the tribe of Ma·nasʹseh by their families.

[[v6-13-30]]

^<<v6-13-30,30>>^ And their territory extended from Ma·ha·naʹim and took in all of Baʹshan, all the royal realm of King Og of Baʹshan, and all the tent villages of Jaʹir in Baʹshan, 60 towns.

[[v6-13-31]]

^<<v6-13-31,31>>^ And half of Gilʹe·ad, and Ashʹta·roth and Edʹre·i, the cities of the royal realm of Og in Baʹshan, went to the sons of Maʹchir the son of Ma·nasʹseh, to half of the sons of Maʹchir by their families.

[[v6-13-32]]

^<<v6-13-32,32>>^ These were the inheritances that Moses gave them on the desert plains of Moʹab beyond the Jordan, east of Jerʹi·cho.

[[v6-13-33]]

^<<v6-13-33,33>>^ But to the tribe of the Levites, Moses did not give an inheritance. Jehovah the God of Israel is their inheritance, just as he promised them.

'''

xref:006-joshua/006-joshua-012.adoc#v6-12-0[&#60; Capítulo Anterior] | <<v6-13-0,Topo>> | xref:006-joshua/006-joshua-014.adoc#v6-14-0[Próximo Capítulo &#62;]