include::./index.adoc[]

[[v6-12-0]]
=== Joshua, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-12-1]]

^<<v6-12-1,1>>^ Now these are the kings of the land whom the Israelites defeated, whose land they took possession of on the east side of the Jordan, from the Arʹnon Valley^&#42;1^ up to Mount Herʹmon and all the Arʹa·bah toward the east:

[NOTE]
====
. Or “Wadi Arnon.”
====

[[v6-12-2]]

^<<v6-12-2,2>>^ King Siʹhon of the Amʹor·ites, who lived in Heshʹbon and ruled from A·roʹer, which was on the rim of the Arʹnon Valley,^&#42;1^ and from the middle of the valley, and half of Gilʹe·ad as far as the Valley^&#42;2^ of Jabʹbok, the boundary of the Amʹmon·ites.

[NOTE]
====
. Or “Wadi Arnon.”
. Or “Wadi.”
====

[[v6-12-3]]

^<<v6-12-3,3>>^ He also ruled over the Arʹa·bah as far as the Sea of Chinʹne·reth^&#42;1^ toward the east and as far as the Sea of the Arʹa·bah, the Salt Sea,^&#42;2^ to the east in the direction of Beth-jeshʹi·moth, and toward the south under the slopes of Pisʹgah.

[NOTE]
====
. That is, the lake of Gennesaret, or the Sea of Galilee.
. That is, the Dead Sea.
====

[[v6-12-4]]

^<<v6-12-4,4>>^ Also the territory of King Og of Baʹshan, who was one of the last of the Rephʹa·im and who lived in Ashʹta·roth and Edʹre·i

[[v6-12-5]]

^<<v6-12-5,5>>^ and ruled in Mount Herʹmon, in Salʹe·cah, and in all Baʹshan, as far as the boundary of the Geshʹur·ites and the Ma·acʹa·thites, and half of Gilʹe·ad, to the territory of King Siʹhon of Heshʹbon.

[[v6-12-6]]

^<<v6-12-6,6>>^ Moses the servant of Jehovah and the Israelites defeated them, after which Moses the servant of Jehovah gave their land as a possession to the Reuʹben·ites, the Gadʹites, and the half tribe of Ma·nasʹseh.

[[v6-12-7]]

^<<v6-12-7,7>>^ These are the kings of the land whom Joshua and the Israelites defeated on the west side of the Jordan, from Baʹal-gad in the Valley of Lebʹa·non and as far as Mount Haʹlak, which goes up to Seʹir, after which Joshua gave their land to the tribes of Israel as a possession by their shares,

[[v6-12-8]]

^<<v6-12-8,8>>^ in the mountainous region, in the She·pheʹlah, in the Arʹa·bah, on the slopes, in the wilderness, and in the Negʹeb—the land of the Hitʹtites, the Amʹor·ites, the Caʹnaan·ites, the Perʹiz·zites, the Hiʹvites, and the Jebʹu·sites:

[[v6-12-9]]

^<<v6-12-9,9>>^ The king of Jerʹi·cho, one; the king of Aʹi, which was beside Bethʹel, one;

[[v6-12-10]]

^<<v6-12-10,10>>^ the king of Jerusalem, one; the king of Hebʹron, one;

[[v6-12-11]]

^<<v6-12-11,11>>^ the king of Jarʹmuth, one; the king of Laʹchish, one;

[[v6-12-12]]

^<<v6-12-12,12>>^ the king of Egʹlon, one; the king of Geʹzer, one;

[[v6-12-13]]

^<<v6-12-13,13>>^ the king of Deʹbir, one; the king of Geʹder, one;

[[v6-12-14]]

^<<v6-12-14,14>>^ the king of Horʹmah, one; the king of Aʹrad, one;

[[v6-12-15]]

^<<v6-12-15,15>>^ the king of Libʹnah, one; the king of A·dulʹlam, one;

[[v6-12-16]]

^<<v6-12-16,16>>^ the king of Mak·keʹdah, one; the king of Bethʹel, one;

[[v6-12-17]]

^<<v6-12-17,17>>^ the king of Tapʹpu·ah, one; the king of Heʹpher, one;

[[v6-12-18]]

^<<v6-12-18,18>>^ the king of Aʹphek, one; the king of Las·sharʹon, one;

[[v6-12-19]]

^<<v6-12-19,19>>^ the king of Maʹdon, one; the king of Haʹzor, one;

[[v6-12-20]]

^<<v6-12-20,20>>^ the king of Shimʹron-meʹron, one; the king of Achʹshaph, one;

[[v6-12-21]]

^<<v6-12-21,21>>^ the king of Taʹa·nach, one; the king of Me·gidʹdo, one;

[[v6-12-22]]

^<<v6-12-22,22>>^ the king of Keʹdesh, one; the king of Jokʹne·am in Carʹmel, one;

[[v6-12-23]]

^<<v6-12-23,23>>^ the king of Dor on the slopes of Dor, one; the king of Goiʹim in Gilʹgal, one;

[[v6-12-24]]

^<<v6-12-24,24>>^ the king of Tirʹzah, one; a total of 31 kings.

'''

xref:006-joshua/006-joshua-011.adoc#v6-11-0[&#60; Capítulo Anterior] | <<v6-12-0,Topo>> | xref:006-joshua/006-joshua-013.adoc#v6-13-0[Próximo Capítulo &#62;]