include::./index.adoc[]

[[v6-5-0]]
=== Joshua, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-5-1]]

^<<v6-5-1,1>>^ As soon as all the kings of the Amʹor·ites who were on the west side^&#42;1^ of the Jordan and all the kings of the Caʹnaan·ites who were by the sea heard that Jehovah had dried up the waters of the Jordan before the Israelites until they had crossed over, they lost heart,^&#42;2^ and they lost all courage^&#42;3^ because of the Israelites.

[NOTE]
====
. Lit., “the side toward the sea.”
. Lit., “their hearts melted.”
. Lit., “and there was no spirit in them any longer.”
====

[[v6-5-2]]

^<<v6-5-2,2>>^ At that time Jehovah said to Joshua: “Make for yourself flint knives and circumcise the men of Israel again, a second time.”

[[v6-5-3]]

^<<v6-5-3,3>>^ So Joshua made flint knives and circumcised the men of Israel at Gibʹe·ath-ha·arʹa·loth.^&#42;1^

[NOTE]
====
. Meaning “Hill of the Foreskins.”
====

[[v6-5-4]]

^<<v6-5-4,4>>^ This is why Joshua circumcised them: All the males of the people who left Egypt, all the men of war,^&#42;1^ had died in the wilderness on the journey after they left Egypt.

[NOTE]
====
. Or “the men of military age.”
====

[[v6-5-5]]

^<<v6-5-5,5>>^ All the people who left Egypt were circumcised, but all the people born in the wilderness on the journey after they left Egypt were not circumcised.

[[v6-5-6]]

^<<v6-5-6,6>>^ The Israelites had walked for 40 years in the wilderness until the entire nation had died off, that is, the men of war who left Egypt who did not obey the voice of Jehovah. Jehovah swore to them that he would never let them see the land that Jehovah had sworn to their forefathers to give to us, a land flowing with milk and honey.

[[v6-5-7]]

^<<v6-5-7,7>>^ So he raised up their sons instead of them. These Joshua circumcised; they were uncircumcised because they had not circumcised them during the journey.

[[v6-5-8]]

^<<v6-5-8,8>>^ When they finished circumcising the entire nation, they remained where they were in the camp until they recovered.

[[v6-5-9]]

^<<v6-5-9,9>>^ Then Jehovah said to Joshua: “Today I have rolled away from you the reproach of Egypt.” So that place has been called Gilʹgal^&#42;1^ until this day.

[NOTE]
====
. Meaning “Rolling; Rolling Away.”
====

[[v6-5-10]]

^<<v6-5-10,10>>^ The Israelites continued to camp at Gilʹgal, and they observed the Passover on the 14th day of the month, in the evening, on the desert plains of Jerʹi·cho.

[[v6-5-11]]

^<<v6-5-11,11>>^ And they began to eat the produce of the land the day after the Passover, unleavened bread and roasted grains, on this same day.

[[v6-5-12]]

^<<v6-5-12,12>>^ And the manna stopped on the following day when they had eaten some of the produce of the land; there was no longer manna for the Israelites, but they began to eat the produce of the land of Caʹnaan in that year.

[[v6-5-13]]

^<<v6-5-13,13>>^ When Joshua was near Jerʹi·cho, he looked up and saw a man standing in front of him with a drawn sword in his hand. Joshua walked up to him and asked: “Are you on our side or on the side of our adversaries?”

[[v6-5-14]]

^<<v6-5-14,14>>^ To this he said: “No, but I have come as prince^&#42;1^ of Jehovah’s army.” With that Joshua fell with his face to the ground and prostrated himself and said to him: “What does my lord have to say to his servant?”

[NOTE]
====
. Or “chief.”
====

[[v6-5-15]]

^<<v6-5-15,15>>^ The prince of Jehovah’s army replied to Joshua: “Remove your sandals from your feet, because the place where you are standing is holy.” At once Joshua did so.

'''

xref:006-joshua/006-joshua-004.adoc#v6-4-0[&#60; Capítulo Anterior] | <<v6-5-0,Topo>> | xref:006-joshua/006-joshua-006.adoc#v6-6-0[Próximo Capítulo &#62;]