include::./index.adoc[]

[[v6-7-0]]
=== Joshua, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-7-1]]

^<<v6-7-1,1>>^ But the Israelites were unfaithful with regard to what had been devoted to destruction, for Aʹchan son of Carʹmi, son of Zabʹdi, son of Zeʹrah, of the tribe of Judah, took some of what was devoted to destruction. At this Jehovah’s anger blazed against the Israelites.

[[v6-7-2]]

^<<v6-7-2,2>>^ Then Joshua sent men out from Jerʹi·cho to Aʹi, which is close by Beth-aʹven and east of Bethʹel, telling them: “Go up and spy on the land.” So the men went up and spied on Aʹi.

[[v6-7-3]]

^<<v6-7-3,3>>^ When they returned to Joshua, they told him: “Not all the people need to go up. About two or three thousand men are enough to defeat Aʹi. Do not tire out all the people by making them go, for there are only a few of them.”

[[v6-7-4]]

^<<v6-7-4,4>>^ So about 3,000 men went up there, but they had to flee from the men of Aʹi.

[[v6-7-5]]

^<<v6-7-5,5>>^ The men of Aʹi struck down 36 men, and they pursued them from outside the city gate as far as Shebʹa·rim,^&#42;1^ and they continued striking them down on the descent. So the courage^&#42;2^ of the people melted and flowed away like water.

[NOTE]
====
. Meaning “Quarries.”
. Lit., “heart.”
====

[[v6-7-6]]

^<<v6-7-6,6>>^ At this Joshua ripped his garments and fell with his face to the ground before the Ark of Jehovah until the evening, he and the elders of Israel, and they kept throwing dust on their heads.

[[v6-7-7]]

^<<v6-7-7,7>>^ Joshua said: “Alas, Sovereign Lord Jehovah, why did you bring this people all the way across the Jordan just to hand us over to the Amʹor·ites to be destroyed? If only we had been satisfied to remain on the other side^&#42;1^ of the Jordan!

[NOTE]
====
. That is, the east side.
====

[[v6-7-8]]

^<<v6-7-8,8>>^ Pardon me, O Jehovah, what can I say now that Israel has retreated^&#42;1^ before his enemies?

[NOTE]
====
. Or “turned his back.”
====

[[v6-7-9]]

^<<v6-7-9,9>>^ When the Caʹnaan·ites and all the inhabitants of the land hear about it, they will surround us and wipe out our very name from the earth, and what will you do about your great name?”

[[v6-7-10]]

^<<v6-7-10,10>>^ Jehovah replied to Joshua: “Get up! Why are you lying on your face?

[[v6-7-11]]

^<<v6-7-11,11>>^ Israel has sinned. They have violated my covenant that I commanded them to keep. They took some of what was devoted to destruction, stealing it and secretly putting it among their own possessions.

[[v6-7-12]]

^<<v6-7-12,12>>^ Therefore, the Israelites will not be able to stand against their enemies. They will turn their backs and flee from their enemies, because they have become something devoted to destruction. I will not be with you again unless you annihilate from your midst what was devoted to destruction.

[[v6-7-13]]

^<<v6-7-13,13>>^ Get up and sanctify the people! Tell them, ‘Sanctify yourselves for tomorrow, for this is what Jehovah the God of Israel says: “What is devoted to destruction is among you, O Israel. You will not be able to stand against your enemies until you remove from your midst the thing devoted to destruction.

[[v6-7-14]]

^<<v6-7-14,14>>^ You are to present yourselves in the morning, tribe by tribe, and the tribe that Jehovah selects will come near, family by family, and the family that Jehovah selects will come near, household by household, and the household that Jehovah selects will come near, man by man.

[[v6-7-15]]

^<<v6-7-15,15>>^ And the one who is caught with the thing devoted to destruction will be burned with fire, he and all that belongs to him, because he has violated the covenant of Jehovah and because he has committed a disgraceful act in Israel.”’”

[[v6-7-16]]

^<<v6-7-16,16>>^ So Joshua rose early the next morning and had Israel come near, tribe by tribe, and the tribe of Judah was selected.

[[v6-7-17]]

^<<v6-7-17,17>>^ He had the families of Judah come near and the family of the Zeʹrah·ites was selected, after which he had the family of the Zeʹrah·ites come near, man by man, and Zabʹdi was selected.

[[v6-7-18]]

^<<v6-7-18,18>>^ Finally he had the household of Zabʹdi come near, man by man, and Aʹchan son of Carʹmi, son of Zabʹdi, son of Zeʹrah, of the tribe of Judah, was selected.

[[v6-7-19]]

^<<v6-7-19,19>>^ Then Joshua said to Aʹchan: “My son, please, honor Jehovah the God of Israel and make confession to him. Tell me, please, what you have done. Do not hide it from me.”

[[v6-7-20]]

^<<v6-7-20,20>>^ Aʹchan answered Joshua: “For a fact I am the one who sinned against Jehovah the God of Israel, and this is what I have done.

[[v6-7-21]]

^<<v6-7-21,21>>^ When I saw among the spoil a good-looking official garment from Shiʹnar and 200 shekels^&#42;1^ of silver and one gold bar weighing 50 shekels, I desired them, so I took them. They are now hidden in the ground inside my tent, with the money underneath.”

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v6-7-22]]

^<<v6-7-22,22>>^ At once Joshua sent messengers, and they ran to the tent, and there the garment was hidden in his tent, with the money underneath it.

[[v6-7-23]]

^<<v6-7-23,23>>^ So they took the things out of the tent and brought them to Joshua and all the Israelites and placed them before Jehovah.

[[v6-7-24]]

^<<v6-7-24,24>>^ Joshua and all Israel with him then took Aʹchan the son of Zeʹrah, the silver, the official garment, and the bar of gold, along with his sons, his daughters, his bull, his donkey, his flock, his tent, and everything that was his, and they brought them up to the Valley^&#42;1^ of Aʹchor.

[NOTE]
====
. Or “Low Plain.”
====

[[v6-7-25]]

^<<v6-7-25,25>>^ Joshua said: “Why have you brought disaster^&#42;1^ upon us? Jehovah will bring disaster upon you on this day.” With that all Israel stoned him, after which they burned them with fire. Thus they stoned all of them.

[NOTE]
====
. Or “trouble; ostracism.”
====

[[v6-7-26]]

^<<v6-7-26,26>>^ And they raised a huge pile of stones over him that remains to this day. At this Jehovah’s hot anger subsided. That is why the name of that place is Valley of Aʹchor^&#42;1^ to this day.

[NOTE]
====
. Meaning “Disaster; Ostracism.”
====

'''

xref:006-joshua/006-joshua-006.adoc#v6-6-0[&#60; Capítulo Anterior] | <<v6-7-0,Topo>> | xref:006-joshua/006-joshua-008.adoc#v6-8-0[Próximo Capítulo &#62;]