include::./index.adoc[]

[[v6-15-0]]
=== Joshua, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-15-1]]

^<<v6-15-1,1>>^ The land allotted^&#42;1^ to the tribe of Judah for their families extended to the boundary of Eʹdom, the wilderness of Zin, to the Negʹeb at its southern end.

[NOTE]
====
. Or “given by lot.”
====

[[v6-15-2]]

^<<v6-15-2,2>>^ Their southern boundary ran from the extremity of the Salt Sea,^&#42;1^ from the bay that faces southward.

[NOTE]
====
. That is, the Dead Sea.
====

[[v6-15-3]]

^<<v6-15-3,3>>^ And it extended south to the ascent of A·krabʹbim, passed over to Zin, then went up from the south to Kaʹdesh-barʹne·a, over to Hezʹron, up to Adʹdar, and went around toward Karʹka.

[[v6-15-4]]

^<<v6-15-4,4>>^ Then it passed on to Azʹmon and extended to the Wadi^&#42;1^ of Egypt, and the boundary ended at the Sea.^&#42;2^ This was their southern boundary.

[NOTE]
====
. See Glossary.
. That is, the Great Sea, the Mediterranean.
====

[[v6-15-5]]

^<<v6-15-5,5>>^ The eastern boundary was the Salt Sea^&#42;1^ up to the end of the Jordan, and the boundary at the northern corner was at the bay of the sea, at the end of the Jordan.

[NOTE]
====
. That is, the Dead Sea.
====

[[v6-15-6]]

^<<v6-15-6,6>>^ The boundary went up to Beth-hogʹlah and passed over at the north of Beth-arʹa·bah, and the boundary went up to the stone of Boʹhan the son of Reuʹben.

[[v6-15-7]]

^<<v6-15-7,7>>^ The boundary went up to Deʹbir at the Valley^&#42;1^ of Aʹchor and turned northward to Gilʹgal, which is in front of the ascent of A·dumʹmim that is south of the wadi, and the boundary passed over to the waters of En-sheʹmesh and ended at En-roʹgel.

[NOTE]
====
. Or “Low Plain.”
====

[[v6-15-8]]

^<<v6-15-8,8>>^ The boundary went up to the Valley of the Son of Hinʹnom to the slope of the Jebʹu·site at the south, that is, Jerusalem, and the boundary went up to the top of the mountain that faces the Valley of Hinʹnom to the west, which is at the extremity of the Valley^&#42;1^ of Rephʹa·im to the north.

[NOTE]
====
. Or “Low Plain.”
====

[[v6-15-9]]

^<<v6-15-9,9>>^ And the boundary was marked from the top of the mountain to the spring of the waters of Neph·toʹah and extended to the cities of Mount Eʹphron; and the boundary was marked to Baʹal·ah, that is, Kirʹi·ath-jeʹa·rim.

[[v6-15-10]]

^<<v6-15-10,10>>^ The boundary went around from Baʹal·ah westward to Mount Seʹir and passed over to the slope of Mount Jeʹa·rim at the north, that is, Chesʹa·lon, and it went down to Beth-sheʹmesh and passed over to Timʹnah.

[[v6-15-11]]

^<<v6-15-11,11>>^ And the boundary extended to the slope of Ekʹron to the north, and the boundary was marked to Shikʹke·ron and passed over to Mount Baʹal·ah and extended to Jabʹne·el, and the boundary ended at the sea.

[[v6-15-12]]

^<<v6-15-12,12>>^ The western boundary was at the Great Sea^&#42;1^ and its coast. This was the boundary of the descendants of Judah by their families on all sides.

[NOTE]
====
. That is, the Mediterranean.
====

[[v6-15-13]]

^<<v6-15-13,13>>^ And to Caʹleb the son of Je·phunʹneh, he gave a share among the descendants of Judah at the order of Jehovah to Joshua, namely, Kirʹi·ath-arʹba (Arʹba was the father of Aʹnak), that is, Hebʹron.

[[v6-15-14]]

^<<v6-15-14,14>>^ So Caʹleb drove out from there the three sons of Aʹnak: Sheʹshai, A·hiʹman, and Talʹmai, descendants of Aʹnak.

[[v6-15-15]]

^<<v6-15-15,15>>^ Then he went up from there against the inhabitants of Deʹbir. (The name of Deʹbir was previously Kirʹi·ath-seʹpher.)

[[v6-15-16]]

^<<v6-15-16,16>>^ Caʹleb then said: “To the man who strikes Kirʹi·ath-seʹpher and captures it, I will give my daughter Achʹsah as a wife.”

[[v6-15-17]]

^<<v6-15-17,17>>^ And Othʹni·el the son of Keʹnaz, Caʹleb’s brother, captured it. So he gave him his daughter Achʹsah as a wife.

[[v6-15-18]]

^<<v6-15-18,18>>^ While she was going home, she urged him to ask her father for a field. Then she dismounted from her donkey.^&#42;1^ Caʹleb asked her: “What do you want?”

[NOTE]
====
. Or possibly, “she clapped her hands while on the donkey.”
====

[[v6-15-19]]

^<<v6-15-19,19>>^ She said: “Please grant me a blessing, for you have given me a piece of land in the south;^&#42;1^ give me also Gulʹloth-maʹim.”^&#42;2^ So he gave her Upper Gulʹloth and Lower Gulʹloth.

[NOTE]
====
. Or “the Negeb.”
. Meaning “Basins (Bowls) of Water.”
====

[[v6-15-20]]

^<<v6-15-20,20>>^ This was the inheritance of the tribe of Judah by their families.

[[v6-15-21]]

^<<v6-15-21,21>>^ The cities at the extremity of the tribe of Judah toward the boundary of Eʹdom in the south were: Kabʹze·el, Eʹder, Jaʹgur,

[[v6-15-22]]

^<<v6-15-22,22>>^ Kiʹnah, Di·moʹnah, A·daʹdah,

[[v6-15-23]]

^<<v6-15-23,23>>^ Keʹdesh, Haʹzor, Ithʹnan,

[[v6-15-24]]

^<<v6-15-24,24>>^ Ziph, Teʹlem, Be·aʹloth,

[[v6-15-25]]

^<<v6-15-25,25>>^ Haʹzor-ha·datʹtah, and Keʹri·oth-hezʹron, that is, Haʹzor,

[[v6-15-26]]

^<<v6-15-26,26>>^ Aʹmam, Sheʹma, Mo·laʹdah,

[[v6-15-27]]

^<<v6-15-27,27>>^ Haʹzar-gadʹdah, Heshʹmon, Beth-pelʹet,

[[v6-15-28]]

^<<v6-15-28,28>>^ Haʹzar-shuʹal, Beʹer-sheʹba, Biz·i·o·thiʹah,

[[v6-15-29]]

^<<v6-15-29,29>>^ Baʹal·ah, Iʹim, Eʹzem,

[[v6-15-30]]

^<<v6-15-30,30>>^ El·toʹlad, Cheʹsil, Horʹmah,

[[v6-15-31]]

^<<v6-15-31,31>>^ Zikʹlag, Mad·manʹnah, San·sanʹnah,

[[v6-15-32]]

^<<v6-15-32,32>>^ Le·baʹoth, Shilʹhim, Aʹin, and Rimʹmon—a total of 29 cities together with their settlements.

[[v6-15-33]]

^<<v6-15-33,33>>^ In the She·pheʹlah, there were: Eshʹta·ol, Zorʹah, Ashʹnah,

[[v6-15-34]]

^<<v6-15-34,34>>^ Za·noʹah, En-ganʹnim, Tapʹpu·ah, Eʹnam,

[[v6-15-35]]

^<<v6-15-35,35>>^ Jarʹmuth, A·dulʹlam, Soʹcoh, A·zeʹkah,

[[v6-15-36]]

^<<v6-15-36,36>>^ Shaʹa·raʹim, Ad·i·thaʹim, and Ge·deʹrah and Ged·e·ro·thaʹim^&#42;1^—14 cities and their settlements.

[NOTE]
====
. Or possibly, “Gederah and its sheepfolds.”
====

[[v6-15-37]]

^<<v6-15-37,37>>^ Zeʹnan, Ha·dashʹah, Migʹdal-gad,

[[v6-15-38]]

^<<v6-15-38,38>>^ Diʹle·an, Mizʹpeh, Jokʹthe·el,

[[v6-15-39]]

^<<v6-15-39,39>>^ Laʹchish, Bozʹkath, Egʹlon,

[[v6-15-40]]

^<<v6-15-40,40>>^ Cabʹbon, Lahʹmam, Chitʹlish,

[[v6-15-41]]

^<<v6-15-41,41>>^ Ge·deʹroth, Beth-daʹgon, Naʹa·mah, and Mak·keʹdah—16 cities and their settlements.

[[v6-15-42]]

^<<v6-15-42,42>>^ Libʹnah, Eʹther, Aʹshan,

[[v6-15-43]]

^<<v6-15-43,43>>^ Iphʹtah, Ashʹnah, Neʹzib,

[[v6-15-44]]

^<<v6-15-44,44>>^ Keiʹlah, Achʹzib, and Ma·reʹshah—nine cities and their settlements.

[[v6-15-45]]

^<<v6-15-45,45>>^ Ekʹron and its dependent^&#42;1^ towns and its settlements;

[NOTE]
====
. Or “surrounding.”
====

[[v6-15-46]]

^<<v6-15-46,46>>^ from Ekʹron westward, all that is alongside Ashʹdod and their settlements.

[[v6-15-47]]

^<<v6-15-47,47>>^ Ashʹdod, its dependent^&#42;1^ towns and its settlements; Gazʹa, its dependent towns and its settlements, down to the Wadi of Egypt, the Great Sea,^&#42;2^ and the adjacent region.

[NOTE]
====
. Or “surrounding.”
. That is, the Mediterranean.
====

[[v6-15-48]]

^<<v6-15-48,48>>^ And in the mountainous region, Shaʹmir, Jatʹtir, Soʹcoh,

[[v6-15-49]]

^<<v6-15-49,49>>^ Danʹnah, Kirʹi·ath-sanʹnah, that is, Deʹbir,

[[v6-15-50]]

^<<v6-15-50,50>>^ Aʹnab, Eshʹte·moh, Aʹnim,

[[v6-15-51]]

^<<v6-15-51,51>>^ Goʹshen, Hoʹlon, and Giʹloh—11 cities and their settlements.

[[v6-15-52]]

^<<v6-15-52,52>>^ Arab, Duʹmah, Eʹshan,

[[v6-15-53]]

^<<v6-15-53,53>>^ Jaʹnim, Beth-tapʹpu·ah, A·pheʹkah,

[[v6-15-54]]

^<<v6-15-54,54>>^ Humʹtah, Kirʹi·ath-arʹba, that is, Hebʹron, and Ziʹor—nine cities and their settlements.

[[v6-15-55]]

^<<v6-15-55,55>>^ Maʹon, Carʹmel, Ziph, Jutʹtah,

[[v6-15-56]]

^<<v6-15-56,56>>^ Jezʹre·el, Jokʹde·am, Za·noʹah,

[[v6-15-57]]

^<<v6-15-57,57>>^ Kaʹin, Gibʹe·ah, and Timʹnah—ten cities and their settlements.

[[v6-15-58]]

^<<v6-15-58,58>>^ Halʹhul, Beth-zur, Geʹdor,

[[v6-15-59]]

^<<v6-15-59,59>>^ Maʹa·rath, Beth-aʹnoth, and Elʹte·kon—six cities and their settlements.

[[v6-15-60]]

^<<v6-15-60,60>>^ Kirʹi·ath-baʹal, that is, Kirʹi·ath-jeʹa·rim, and Rabʹbah—two cities and their settlements.

[[v6-15-61]]

^<<v6-15-61,61>>^ In the wilderness, Beth-arʹa·bah, Midʹdin, Se·caʹcah,

[[v6-15-62]]

^<<v6-15-62,62>>^ Nibʹshan, the City of Salt, and En-gedʹi—six cities and their settlements.

[[v6-15-63]]

^<<v6-15-63,63>>^ As for the Jebʹu·sites who were dwelling in Jerusalem, the men of Judah were not able to drive them away, so the Jebʹu·sites continue dwelling with the people of Judah in Jerusalem to this day.

'''

xref:006-joshua/006-joshua-014.adoc#v6-14-0[&#60; Capítulo Anterior] | <<v6-15-0,Topo>> | xref:006-joshua/006-joshua-016.adoc#v6-16-0[Próximo Capítulo &#62;]