include::./index.adoc[]

[[v6-14-0]]
=== Joshua, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-14-1]]

^<<v6-14-1,1>>^ Now this is what the Israelites took as an inheritance in the land of Caʹnaan, which El·e·aʹzar the priest and Joshua the son of Nun and the heads of the paternal houses of the tribes of Israel gave them to inherit.

[[v6-14-2]]

^<<v6-14-2,2>>^ Their inheritance was by lot, just as Jehovah had commanded through Moses for the nine and a half tribes.

[[v6-14-3]]

^<<v6-14-3,3>>^ Moses had given the inheritance of the other two and a half tribes on the other side^&#42;1^ of the Jordan, and to the Levites he did not give an inheritance among them.

[NOTE]
====
. That is, the east side.
====

[[v6-14-4]]

^<<v6-14-4,4>>^ The descendants of Joseph were considered two tribes, Ma·nasʹseh and Eʹphra·im; and they did not give a share in the land to the Levites, except cities to dwell in and their pastures for their livestock and their property.

[[v6-14-5]]

^<<v6-14-5,5>>^ So the Israelites apportioned the land just as Jehovah had commanded Moses.

[[v6-14-6]]

^<<v6-14-6,6>>^ Then the men of Judah approached Joshua in Gilʹgal, and Caʹleb the son of Je·phunʹneh the Kenʹiz·zite said to him: “You well know what Jehovah said to Moses the man of the true God about you and me at Kaʹdesh-barʹne·a.

[[v6-14-7]]

^<<v6-14-7,7>>^ I was 40 years old when Moses the servant of Jehovah sent me out of Kaʹdesh-barʹne·a to spy out the land, and I returned with a forthright report.^&#42;1^

[NOTE]
====
. Lit., “with a word just as with my heart.”
====

[[v6-14-8]]

^<<v6-14-8,8>>^ Although my brothers who went up with me caused the people to lose heart,^&#42;1^ I followed Jehovah my God wholeheartedly.^&#42;2^

[NOTE]
====
. Lit., “caused the heart of the people to melt.”
. Lit., “fully; completely.”
====

[[v6-14-9]]

^<<v6-14-9,9>>^ Moses swore on that day, saying: ‘The land on which your foot has walked will become a lasting inheritance for you and your sons, because you have followed Jehovah my God wholeheartedly.’

[[v6-14-10]]

^<<v6-14-10,10>>^ Now just as he promised, Jehovah has preserved me alive these 45 years since Jehovah made this promise to Moses when Israel walked in the wilderness; I am still here today, 85 years old.

[[v6-14-11]]

^<<v6-14-11,11>>^ And today I am as strong as on the day Moses sent me out. My strength is now as it was then, for war and for other activities.

[[v6-14-12]]

^<<v6-14-12,12>>^ Therefore, give me this mountainous region that Jehovah promised on that day. Though you heard on that day that there were Anʹa·kim there with great fortified cities, surely^&#42;1^ Jehovah will be with me, and I will drive them out,^&#42;2^ just as Jehovah promised.”

[NOTE]
====
. Or “likely.”
. Or “dispossess them.”
====

[[v6-14-13]]

^<<v6-14-13,13>>^ So Joshua blessed him and gave Hebʹron to Caʹleb the son of Je·phunʹneh as an inheritance.

[[v6-14-14]]

^<<v6-14-14,14>>^ That is why Hebʹron belongs to Caʹleb the son of Je·phunʹneh the Kenʹiz·zite as an inheritance to this day, because he followed Jehovah the God of Israel wholeheartedly.

[[v6-14-15]]

^<<v6-14-15,15>>^ The name of Hebʹron was previously Kirʹi·ath-arʹba (Arʹba was the great man among the Anʹa·kim). And the land had rest from war.

'''

xref:006-joshua/006-joshua-013.adoc#v6-13-0[&#60; Capítulo Anterior] | <<v6-14-0,Topo>> | xref:006-joshua/006-joshua-015.adoc#v6-15-0[Próximo Capítulo &#62;]