include::./index.adoc[]

[[v6-4-0]]
=== Joshua, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-4-1]]

^<<v6-4-1,1>>^ As soon as the whole nation had finished crossing the Jordan, Jehovah said to Joshua:

[[v6-4-2]]

^<<v6-4-2,2>>^ “Take 12 men from the people, one man from each tribe,

[[v6-4-3]]

^<<v6-4-3,3>>^ and give them this command: ‘Take up 12 stones from the middle of the Jordan, from the place where the priests’ feet stood still, and carry them over with you and set them down in the place where you will spend the night.’”

[[v6-4-4]]

^<<v6-4-4,4>>^ So Joshua called the 12 men whom he had appointed from the Israelites, one man from each tribe,

[[v6-4-5]]

^<<v6-4-5,5>>^ and Joshua said to them: “Pass ahead of the Ark of Jehovah your God to the middle of the Jordan, and each of you should lift up a stone on his shoulder, according to the number of the tribes of the Israelites,

[[v6-4-6]]

^<<v6-4-6,6>>^ to serve as a sign among you. If your children^&#42;1^ should later ask you, ‘Why do you have these stones?’

[NOTE]
====
. Lit., “sons.”
====

[[v6-4-7]]

^<<v6-4-7,7>>^ you must tell them: ‘Because the waters of the Jordan were halted from before the ark of Jehovah’s covenant. When it crossed the Jordan, the waters of the Jordan were halted. These stones will serve as a lasting memorial^&#42;1^ to the people of Israel.’”

[NOTE]
====
. Or “reminder.”
====

[[v6-4-8]]

^<<v6-4-8,8>>^ So the Israelites did just as Joshua had commanded. They took up 12 stones from the middle of the Jordan, just as Jehovah had instructed Joshua, to correspond to the number of the tribes of the Israelites. They took them over to the place where they would spend the night and set them down there.

[[v6-4-9]]

^<<v6-4-9,9>>^ Joshua also set up 12 stones in the middle of the Jordan at the place where the feet of the priests who carried the ark of the covenant stood, and the stones are there to this day.

[[v6-4-10]]

^<<v6-4-10,10>>^ The priests carrying the Ark remained standing in the middle of the Jordan until everything that Jehovah had ordered Joshua to tell the people to do was completed, in harmony with all that Moses had commanded Joshua. All the while, the people hurried across.

[[v6-4-11]]

^<<v6-4-11,11>>^ As soon as all the people had finished crossing over, the Ark of Jehovah and the priests crossed over in the sight of the people.

[[v6-4-12]]

^<<v6-4-12,12>>^ And the Reuʹben·ites, the Gadʹites, and the half tribe of Ma·nasʹseh crossed over in battle formation ahead of the other Israelites, just as Moses had instructed them.

[[v6-4-13]]

^<<v6-4-13,13>>^ About 40,000 soldiers armed for battle crossed over before Jehovah onto the desert plains of Jerʹi·cho.

[[v6-4-14]]

^<<v6-4-14,14>>^ On that day Jehovah exalted Joshua in the eyes of all Israel, and they deeply respected^&#42;1^ him all the days of his life, just as they had deeply respected Moses.

[NOTE]
====
. Lit., “they feared.”
====

[[v6-4-15]]

^<<v6-4-15,15>>^ Then Jehovah said to Joshua:

[[v6-4-16]]

^<<v6-4-16,16>>^ “Command the priests carrying the ark of the Testimony to come up out of the Jordan.”

[[v6-4-17]]

^<<v6-4-17,17>>^ So Joshua commanded the priests: “Come up out of the Jordan.”

[[v6-4-18]]

^<<v6-4-18,18>>^ When the priests carrying the ark of the covenant of Jehovah came up from the middle of the Jordan and the soles of the feet of the priests stepped onto dry ground, the waters of the Jordan resumed their course and overflowed the banks as before.

[[v6-4-19]]

^<<v6-4-19,19>>^ The people came up from the Jordan on the tenth day of the first month and camped at Gilʹgal on the eastern border of Jerʹi·cho.

[[v6-4-20]]

^<<v6-4-20,20>>^ As for the 12 stones that they had taken out of the Jordan, Joshua set these up at Gilʹgal.

[[v6-4-21]]

^<<v6-4-21,21>>^ Then he said to the Israelites: “In the future when your children ask their fathers, ‘What do these stones mean?’

[[v6-4-22]]

^<<v6-4-22,22>>^ you must explain to your children: ‘Israel crossed the Jordan on dry land

[[v6-4-23]]

^<<v6-4-23,23>>^ when Jehovah your God dried up the waters of the Jordan before them until they had crossed it, just as Jehovah your God did to the Red Sea when he dried it up before us until we crossed it.

[[v6-4-24]]

^<<v6-4-24,24>>^ He did this so that all the peoples of the earth may know how mighty Jehovah’s hand is and so that you may always fear Jehovah your God.’”

'''

xref:006-joshua/006-joshua-003.adoc#v6-3-0[&#60; Capítulo Anterior] | <<v6-4-0,Topo>> | xref:006-joshua/006-joshua-005.adoc#v6-5-0[Próximo Capítulo &#62;]