include::./index.adoc[]

[[v6-9-0]]
=== Joshua, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v6-9-1]]

^<<v6-9-1,1>>^ When all the kings who were on the west side of the Jordan heard what had happened, those in the mountainous region, in the She·pheʹlah, along the entire coast of the Great Sea,^&#42;1^ and in front of Lebʹa·non—the Hitʹtites, the Amʹor·ites, the Caʹnaan·ites, the Perʹiz·zites, the Hiʹvites, and the Jebʹu·sites—

[NOTE]
====
. That is, the Mediterranean.
====

[[v6-9-2]]

^<<v6-9-2,2>>^ they formed an alliance to fight against Joshua and Israel.

[[v6-9-3]]

^<<v6-9-3,3>>^ The inhabitants of Gibʹe·on also heard what Joshua had done to Jerʹi·cho and Aʹi.

[[v6-9-4]]

^<<v6-9-4,4>>^ So they acted shrewdly and put provisions into worn-out sacks on their donkeys, along with worn-out wineskins that had burst and had been mended;

[[v6-9-5]]

^<<v6-9-5,5>>^ they also had worn-out and patched sandals on their feet, and they were wearing worn-out garments. All the bread of their provisions was dry and crumbly.

[[v6-9-6]]

^<<v6-9-6,6>>^ Then they went to Joshua at the camp at Gilʹgal and said to him and the men of Israel: “We have come from a distant land. Now make a covenant with us.”

[[v6-9-7]]

^<<v6-9-7,7>>^ But the men of Israel said to the Hiʹvites: “Perhaps you are living near us. So how can we make a covenant with you?”

[[v6-9-8]]

^<<v6-9-8,8>>^ They replied to Joshua: “We are your servants.”^&#42;1^
Then Joshua said to them: “Who are you, and where do you come from?”

[NOTE]
====
. Or “slaves.”
====

[[v6-9-9]]

^<<v6-9-9,9>>^ At this they said to him: “Your servants have come from a very distant land out of regard for the name of Jehovah your God, because we have heard about his fame and about all he did in Egypt

[[v6-9-10]]

^<<v6-9-10,10>>^ and about all he did to the two kings of the Amʹor·ites who were on the other side^&#42;1^ of the Jordan, King Siʹhon of Heshʹbon and King Og of Baʹshan, who was in Ashʹta·roth.

[NOTE]
====
. That is, the east side.
====

[[v6-9-11]]

^<<v6-9-11,11>>^ So our elders and all the inhabitants of our land told us, ‘Take provisions with you for the journey and go to meet them. Tell them: “We will be your servants; now make a covenant with us.”’

[[v6-9-12]]

^<<v6-9-12,12>>^ This bread that we took as our provisions was still hot on the day we left our houses to come here to you. Now you can see it is dry and crumbly.

[[v6-9-13]]

^<<v6-9-13,13>>^ And these wineskins were new when we filled them, but now they have burst. And our garments and sandals have worn out because of the great length of the journey.”

[[v6-9-14]]

^<<v6-9-14,14>>^ At that the men took^&#42;1^ some of their provisions, but they did not inquire of Jehovah.

[NOTE]
====
. Or “examined.”
====

[[v6-9-15]]

^<<v6-9-15,15>>^ So Joshua made peace with them and made a covenant with them to let them live, and that is what the chieftains of the assembly swore to them in an oath.

[[v6-9-16]]

^<<v6-9-16,16>>^ At the end of three days, after they made a covenant with them, they heard that they lived nearby, in their vicinity.

[[v6-9-17]]

^<<v6-9-17,17>>^ Then the Israelites set out and came to their cities on the third day; their cities were Gibʹe·on, Che·phiʹrah, Be·erʹoth, and Kirʹi·ath-jeʹa·rim.

[[v6-9-18]]

^<<v6-9-18,18>>^ But the Israelites did not attack them, because the chieftains of the assembly had sworn an oath to them by Jehovah the God of Israel. So all the assembly began to murmur against the chieftains.

[[v6-9-19]]

^<<v6-9-19,19>>^ At this all the chieftains said to the entire assembly: “Since we swore an oath to them by Jehovah the God of Israel, we are not allowed to hurt them.

[[v6-9-20]]

^<<v6-9-20,20>>^ This is what we will do: We will let them live, so that there is no indignation against us because of the oath that we swore to them.”

[[v6-9-21]]

^<<v6-9-21,21>>^ And the chieftains added: “Let them live, but let them become gatherers of wood and drawers of water for all the assembly.” This is what the chieftains promised them.

[[v6-9-22]]

^<<v6-9-22,22>>^ Joshua now called them and said to them: “Why did you trick us by saying, ‘We are from a place very far away from you,’ when you really live right among us?

[[v6-9-23]]

^<<v6-9-23,23>>^ From now on you are cursed, and you will always occupy a slave’s position as gatherers of wood and drawers of water for the house of my God.”

[[v6-9-24]]

^<<v6-9-24,24>>^ They answered Joshua: “It was because your servants were plainly told that Jehovah your God had commanded Moses his servant to give you all the land and to annihilate all its inhabitants from before you. So we were afraid for our lives^&#42;1^ because of you, and that is why we did this.

[NOTE]
====
. Or “souls.”
====

[[v6-9-25]]

^<<v6-9-25,25>>^ Now we are at your mercy.^&#42;1^ Do to us whatever you think is good and right.”

[NOTE]
====
. Lit., “in your hands.”
====

[[v6-9-26]]

^<<v6-9-26,26>>^ And that is what he did with them; he saved them from the hands of the Israelites, and they did not kill them.

[[v6-9-27]]

^<<v6-9-27,27>>^ But that day Joshua made them gatherers of wood and drawers of water for the assembly and for Jehovah’s altar at the place that He should choose, and they remain so to this day.

'''

xref:006-joshua/006-joshua-008.adoc#v6-8-0[&#60; Capítulo Anterior] | <<v6-9-0,Topo>> | xref:006-joshua/006-joshua-010.adoc#v6-10-0[Próximo Capítulo &#62;]