include::./index.adoc[]

[[v19-147-0]]
=== Psalm, 147
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v19-147-1]]

^<<v19-147-1,1>>^ Praise Jah!^&#42;1^
It is good to sing praises^&#42;2^ to our God;
How pleasant and fitting it is to praise him!

[NOTE]
====
. Or “Hallelujah!” “Jah” is a shortened form of the name Jehovah.
. Or “make music.”
====

[[v19-147-2]]

^<<v19-147-2,2>>^ Jehovah is building Jerusalem;
He gathers together the dispersed ones of Israel.

[[v19-147-3]]

^<<v19-147-3,3>>^ He heals the brokenhearted;
He binds up their wounds.

[[v19-147-4]]

^<<v19-147-4,4>>^ He counts the number of the stars;
He calls all of them by name.

[[v19-147-5]]

^<<v19-147-5,5>>^ Our Lord is great and is mighty in power;
His understanding is beyond measure.

[[v19-147-6]]

^<<v19-147-6,6>>^ Jehovah raises up the meek,
But he hurls the wicked to the ground.

[[v19-147-7]]

^<<v19-147-7,7>>^ Sing to Jehovah with thanksgiving;
Sing praises to our God, accompanied by the harp,

[[v19-147-8]]

^<<v19-147-8,8>>^ The One who covers the heavens with clouds,
The One providing rain for the earth,
The One making grass sprout on the mountains.

[[v19-147-9]]

^<<v19-147-9,9>>^ To the animals he gives food,
To the young ravens that call out for it.

[[v19-147-10]]

^<<v19-147-10,10>>^ He does not delight in the power of the horse;
Nor is he impressed by the strong legs of a man.

[[v19-147-11]]

^<<v19-147-11,11>>^ Jehovah finds pleasure in those who fear him,
In those waiting for his loyal love.

[[v19-147-12]]

^<<v19-147-12,12>>^ Glorify Jehovah, O Jerusalem.
Praise your God, O Zion.

[[v19-147-13]]

^<<v19-147-13,13>>^ He makes the bars of your city gates strong;
He blesses your sons within you.

[[v19-147-14]]

^<<v19-147-14,14>>^ He brings peace to your territory;
He satisfies you with the finest^&#42;1^ wheat.

[NOTE]
====
. Lit., “the fat of.”
====

[[v19-147-15]]

^<<v19-147-15,15>>^ He sends his command to the earth;
His word runs swiftly.

[[v19-147-16]]

^<<v19-147-16,16>>^ He sends the snow like wool;
He scatters the frost just like ashes.

[[v19-147-17]]

^<<v19-147-17,17>>^ He hurls down his hailstones^&#42;1^ like morsels of bread.
Who can withstand his cold?

[NOTE]
====
. Or “ice.”
====

[[v19-147-18]]

^<<v19-147-18,18>>^ He sends out his word, and they melt.
He makes his wind blow, and the waters flow.

[[v19-147-19]]

^<<v19-147-19,19>>^ He declares his word to Jacob,
His regulations and judgments to Israel.

[[v19-147-20]]

^<<v19-147-20,20>>^ He has not done so with any other nation;
They know nothing about his judgments.
Praise Jah!^&#42;1^

[NOTE]
====
. Or “Hallelujah!” “Jah” is a shortened form of the name Jehovah.
====

'''

xref:019-psalm/019-psalm-146.adoc#v19-146-0[&#60; Capítulo Anterior] | <<v19-147-0,Topo>> | xref:019-psalm/019-psalm-148.adoc#v19-148-0[Próximo Capítulo &#62;]