include::./index.adoc[]

[[v19-45-0]]
=== Psalm, 45
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director; set to “The Lilies.” Of the sons of Korʹah. Masʹkil.^&#42;1^ A song of love._

[[v19-45-1]]

^<<v19-45-1,1>>^ My heart is stirred by something good.
I say: “My song is^&#42;1^ about a king.”
May my tongue be the stylus^&#42;2^ of a skilled copyist.^&#42;3^

[NOTE]
====
. Lit., “My works are.”
. Or “pen.”
. Or “scribe.”
====

[[v19-45-2]]

^<<v19-45-2,2>>^ You are the most handsome of the sons of men.
Gracious speech flows from your lips.
That is why God has blessed you forever.

[[v19-45-3]]

^<<v19-45-3,3>>^ Strap your sword on your side, O mighty one,
In your dignity and your splendor.

[[v19-45-4]]

^<<v19-45-4,4>>^ And in your splendor go on to victory;^&#42;1^
Ride in the cause of truth and humility and righteousness,
And your right hand will accomplish^&#42;2^ awe-inspiring things.

[NOTE]
====
. Or “success.”
. Lit., “teach you.”
====

[[v19-45-5]]

^<<v19-45-5,5>>^ Your arrows are sharp, making peoples fall before you;
They pierce the hearts of the king’s enemies.

[[v19-45-6]]

^<<v19-45-6,6>>^ God is your throne forever and ever;
The scepter of your kingdom is a scepter of uprightness.^&#42;1^

[NOTE]
====
. Or “justice.”
====

[[v19-45-7]]

^<<v19-45-7,7>>^ You loved righteousness, and you hated wickedness.
That is why God, your God, has anointed you with the oil of exultation more than your companions.

[[v19-45-8]]

^<<v19-45-8,8>>^ All your garments are scented with myrrh and aloeswood and cassia;
From the grand ivory palace, stringed instruments make you rejoice.

[[v19-45-9]]

^<<v19-45-9,9>>^ The daughters of kings are among your ladies of honor.
The royal consort^&#42;1^ has taken her stand at your right hand, adorned in gold of Oʹphir.

[NOTE]
====
. Or “The queen.”
====

[[v19-45-10]]

^<<v19-45-10,10>>^ Listen, O daughter, pay attention and incline your ear;
Forget your people and your father’s house.

[[v19-45-11]]

^<<v19-45-11,11>>^ And the king will long for your beauty,
For he is your lord,
So bow down to him.

[[v19-45-12]]

^<<v19-45-12,12>>^ The daughter of Tyre will come with a gift;
The wealthiest of men will seek your favor.^&#42;1^

[NOTE]
====
. Or “soften your face.”
====

[[v19-45-13]]

^<<v19-45-13,13>>^ Inside the palace^&#42;1^ the king’s daughter is absolutely magnificent;
Her clothing is adorned with^&#42;2^ gold.

[NOTE]
====
. Lit., “Inside.”
. Lit., “with settings of.”
====

[[v19-45-14]]

^<<v19-45-14,14>>^ She will be brought to the king in richly woven garments.^&#42;1^
The virgin companions following her are brought in before you.

[NOTE]
====
. Or possibly, “in embroidered robes.”
====

[[v19-45-15]]

^<<v19-45-15,15>>^ They will be brought with rejoicing and joy;
They will enter into the king’s palace.

[[v19-45-16]]

^<<v19-45-16,16>>^ Your sons will take the place of your forefathers.
You will appoint them as princes in all the earth.

[[v19-45-17]]

^<<v19-45-17,17>>^ I will make your name known throughout all generations to come.
That is why peoples will praise you forever and ever.

'''

xref:019-psalm/019-psalm-044.adoc#v19-44-0[&#60; Capítulo Anterior] | <<v19-45-0,Topo>> | xref:019-psalm/019-psalm-046.adoc#v19-46-0[Próximo Capítulo &#62;]