include::./index.adoc[]

[[v19-19-0]]
=== Psalm, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director. A melody of David._

[[v19-19-1]]

^<<v19-19-1,1>>^ The heavens are declaring the glory of God;
The skies above^&#42;1^ proclaim the work of his hands.

[NOTE]
====
. Or “expanse.”
====

[[v19-19-2]]

^<<v19-19-2,2>>^ Day after day their speech bubbles forth,
And night after night they reveal knowledge.

[[v19-19-3]]

^<<v19-19-3,3>>^ There is no speech, and there are no words;
Their voice is not heard.

[[v19-19-4]]

^<<v19-19-4,4>>^ But into all the earth their sound^&#42;1^ has gone out,
And to the ends of the inhabited earth^&#42;2^ their message.
In the heavens he has pitched a tent for the sun;

[NOTE]
====
. Or possibly, “measuring line.”
. Or “productive land.”
====

[[v19-19-5]]

^<<v19-19-5,5>>^ It is like a bridegroom emerging from the bridal chamber;
It rejoices like a mighty man running his course.

[[v19-19-6]]

^<<v19-19-6,6>>^ It emerges from one end of the heavens,
And it circles to their other end;
And nothing is concealed from its heat.

[[v19-19-7]]

^<<v19-19-7,7>>^ The law of Jehovah is perfect, restoring strength.^&#42;1^
The reminder of Jehovah is trustworthy, making the inexperienced one wise.

[NOTE]
====
. Or “restoring (bringing back) the soul.”
====

[[v19-19-8]]

^<<v19-19-8,8>>^ The orders from Jehovah are righteous, causing the heart to rejoice;
The commandment of Jehovah is clean, making the eyes shine.

[[v19-19-9]]

^<<v19-19-9,9>>^ The fear of Jehovah is pure, lasting forever.
The judgments of Jehovah are true, altogether righteous.

[[v19-19-10]]

^<<v19-19-10,10>>^ They are more desirable than gold,
Than much fine^&#42;1^ gold,
And sweeter than honey, the honey that drips from the combs.

[NOTE]
====
. Or “refined.”
====

[[v19-19-11]]

^<<v19-19-11,11>>^ By them your servant has been warned;
In keeping them, there is a large reward.

[[v19-19-12]]

^<<v19-19-12,12>>^ Who can discern mistakes?
Pronounce me innocent from sins I am unaware of.

[[v19-19-13]]

^<<v19-19-13,13>>^ And hold your servant back from presumptuous acts;
Do not let them dominate me.
Then I will be complete,
And innocent of blatant sins.^&#42;1^

[NOTE]
====
. Or “much transgression.”
====

[[v19-19-14]]

^<<v19-19-14,14>>^ May the words of my mouth and the meditation of my heart
Be pleasing to you, O Jehovah, my Rock and my Redeemer.

'''

xref:019-psalm/019-psalm-018.adoc#v19-18-0[&#60; Capítulo Anterior] | <<v19-19-0,Topo>> | xref:019-psalm/019-psalm-020.adoc#v19-20-0[Próximo Capítulo &#62;]