include::./index.adoc[]

[[v19-143-0]]
=== Psalm, 143
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_A melody of David._

[[v19-143-1]]

^<<v19-143-1,1>>^ O Jehovah, hear my prayer;
Listen to my plea for help.
In your faithfulness and in your righteousness, answer me.

[[v19-143-2]]

^<<v19-143-2,2>>^ Do not enter into judgment with your servant,
For no one living can be righteous before you.

[[v19-143-3]]

^<<v19-143-3,3>>^ For the enemy pursues me;^&#42;1^
He has crushed my life into the ground.
He has caused me to dwell in darkness like those long dead.

[NOTE]
====
. Or “my soul.”
====

[[v19-143-4]]

^<<v19-143-4,4>>^ My spirit^&#42;1^ is failing;
My heart is numb within me.

[NOTE]
====
. Or “strength.”
====

[[v19-143-5]]

^<<v19-143-5,5>>^ I remember the days of old;
I meditate on all your activity;
I eagerly ponder over^&#42;1^ the work of your hands.

[NOTE]
====
. Or “study.”
====

[[v19-143-6]]

^<<v19-143-6,6>>^ I spread out my hands to you;
I am^&#42;1^ like a parched land that thirsts for you. (Selah)

[NOTE]
====
. Or “My soul is.”
====

[[v19-143-7]]

^<<v19-143-7,7>>^ Do answer me quickly, O Jehovah;
My strength^&#42;1^ has come to an end.
Do not hide your face from me,
Or I will be like those going down into the pit.^&#42;2^

[NOTE]
====
. Lit., “spirit.”
. Or “grave.”
====

[[v19-143-8]]

^<<v19-143-8,8>>^ Let me hear your loyal love in the morning,
For I trust in you.
Make known to me the way I should walk,
For to you I turn.^&#42;1^

[NOTE]
====
. Or “For I lift up my soul to you.”
====

[[v19-143-9]]

^<<v19-143-9,9>>^ Rescue me from my enemies, O Jehovah.
I seek your protection.

[[v19-143-10]]

^<<v19-143-10,10>>^ Teach me to do your will,
For you are my God.
Your spirit is good;
May it lead me on level ground.^&#42;1^

[NOTE]
====
. Or “in the land of uprightness.”
====

[[v19-143-11]]

^<<v19-143-11,11>>^ For the sake of your name, O Jehovah, preserve me alive.
In your righteousness, rescue me^&#42;1^ from distress.

[NOTE]
====
. Or “my soul.”
====

[[v19-143-12]]

^<<v19-143-12,12>>^ In your loyal love, put an end to^&#42;1^ my enemies;
Destroy all those harassing me,^&#42;2^
For I am your servant.

[NOTE]
====
. Lit., “silence.”
. Or “my soul.”
====

'''

xref:019-psalm/019-psalm-142.adoc#v19-142-0[&#60; Capítulo Anterior] | <<v19-143-0,Topo>> | xref:019-psalm/019-psalm-144.adoc#v19-144-0[Próximo Capítulo &#62;]