include::./index.adoc[]

[[v19-55-0]]
=== Psalm, 55
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director; to be accompanied with stringed instruments. Masʹkil.^&#42;1^ Of David._

[[v19-55-1]]

^<<v19-55-1,1>>^ Listen to my prayer, O God,
And do not ignore my request for mercy.^&#42;1^

[NOTE]
====
. Or “And do not hide yourself when I pray for help.”
====

[[v19-55-2]]

^<<v19-55-2,2>>^ Do pay attention to me and answer me.
My concern makes me restless,
And I am distraught

[[v19-55-3]]

^<<v19-55-3,3>>^ Because of what the enemy is saying
And the pressure from the wicked one.
For they heap trouble upon me,
And in anger they harbor animosity against me.

[[v19-55-4]]

^<<v19-55-4,4>>^ My heart is in anguish within me,
And the terrors of death overwhelm me.

[[v19-55-5]]

^<<v19-55-5,5>>^ Fear and trembling come upon me,
And shuddering grips me.

[[v19-55-6]]

^<<v19-55-6,6>>^ I keep saying: “If only I had wings like a dove!
I would fly away and reside in safety.

[[v19-55-7]]

^<<v19-55-7,7>>^ Look! I would flee far away.
I would lodge in the wilderness. (Selah)

[[v19-55-8]]

^<<v19-55-8,8>>^ I would hurry to a place of shelter
Away from the raging wind, away from the storm.”

[[v19-55-9]]

^<<v19-55-9,9>>^ Confuse them, O Jehovah, and frustrate their plans,^&#42;1^
For I have seen violence and conflict in the city.

[NOTE]
====
. Lit., “divide their tongue.”
====

[[v19-55-10]]

^<<v19-55-10,10>>^ Day and night they walk around on its walls;
Within it are malice and trouble.

[[v19-55-11]]

^<<v19-55-11,11>>^ Ruin is in its midst;
Oppression and deception never depart from its public square.

[[v19-55-12]]

^<<v19-55-12,12>>^ For it is not an enemy who taunts me;
Otherwise I could put up with it.
It is not a foe who has risen up against me;
Otherwise I could conceal myself from him.

[[v19-55-13]]

^<<v19-55-13,13>>^ But it is you, a man like me,^&#42;1^
My own companion whom I know well.

[NOTE]
====
. Or “a man, my equal.”
====

[[v19-55-14]]

^<<v19-55-14,14>>^ We used to enjoy a warm friendship together;
Into the house of God we used to walk along with the multitude.

[[v19-55-15]]

^<<v19-55-15,15>>^ May destruction overtake them!
Let them go down alive into the Grave;^&#42;1^
For evil resides among them and within them.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v19-55-16]]

^<<v19-55-16,16>>^ As for me, I will call out to God,
And Jehovah will save me.

[[v19-55-17]]

^<<v19-55-17,17>>^ Evening and morning and noontime, I am troubled and I groan,^&#42;1^
And he hears my voice.

[NOTE]
====
. Or “I am boisterous.”
====

[[v19-55-18]]

^<<v19-55-18,18>>^ He will rescue^&#42;1^ me and give me^&#42;2^ peace from those fighting against me,
For multitudes come against me.

[NOTE]
====
. Lit., “redeem.”
. Or “my soul.”
====

[[v19-55-19]]

^<<v19-55-19,19>>^ God will hear and respond to them,
The one who sits enthroned from of old. (Selah)
They will refuse to change,
Those who have not feared God.

[[v19-55-20]]

^<<v19-55-20,20>>^ He^&#42;1^ attacked those at peace with him;
He violated his covenant.

[NOTE]
====
. That is, the former friend mentioned in vss. 13 and 14.
====

[[v19-55-21]]

^<<v19-55-21,21>>^ His words are smoother than butter,
But conflict is in his heart.
His words are softer than oil,
But they are drawn swords.

[[v19-55-22]]

^<<v19-55-22,22>>^ Throw your burden on Jehovah,
And he will sustain you.
Never will he allow the righteous one to fall.^&#42;1^

[NOTE]
====
. Or “stagger; totter.”
====

[[v19-55-23]]

^<<v19-55-23,23>>^ But you, O God, will bring them down to the deepest pit.
Those bloodguilty and deceitful men will not live out half their days.
But as for me, I will trust in you.

'''

xref:019-psalm/019-psalm-054.adoc#v19-54-0[&#60; Capítulo Anterior] | <<v19-55-0,Topo>> | xref:019-psalm/019-psalm-056.adoc#v19-56-0[Próximo Capítulo &#62;]