include::./index.adoc[]

[[v19-116-0]]
=== Psalm, 116
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v19-116-1]]

^<<v19-116-1,1>>^ I love Jehovah
Because he hears^&#42;1^ my voice, my pleas for help.

[NOTE]
====
. Or possibly, “I love because Jehovah hears.”
====

[[v19-116-2]]

^<<v19-116-2,2>>^ For he inclines his ear^&#42;1^ to me,
And I will call on him as long as I live.^&#42;2^

[NOTE]
====
. Or “bends down to listen.”
. Lit., “in my days.”
====

[[v19-116-3]]

^<<v19-116-3,3>>^ The ropes of death encircled me;
The Grave had me in its grip.^&#42;1^
I was overcome by distress and grief.

[NOTE]
====
. Lit., “The distresses of Sheol found me.”
====

[[v19-116-4]]

^<<v19-116-4,4>>^ But I called on the name of Jehovah:
“O Jehovah, rescue me!”^&#42;1^

[NOTE]
====
. Or “my soul.”
====

[[v19-116-5]]

^<<v19-116-5,5>>^ Jehovah is compassionate^&#42;1^ and righteous;
Our God is merciful.

[NOTE]
====
. Or “gracious.”
====

[[v19-116-6]]

^<<v19-116-6,6>>^ Jehovah is guarding the inexperienced.
I was brought low, and he saved me.

[[v19-116-7]]

^<<v19-116-7,7>>^ Let my soul^&#42;1^ rest once again,
For Jehovah has dealt kindly with me.

[NOTE]
====
. See Glossary.
====

[[v19-116-8]]

^<<v19-116-8,8>>^ You have rescued me^&#42;1^ from death,
My eye from tears, my foot from stumbling.

[NOTE]
====
. Or “my soul.”
====

[[v19-116-9]]

^<<v19-116-9,9>>^ I will walk before Jehovah in the land of the living.

[[v19-116-10]]

^<<v19-116-10,10>>^ I had faith, for I spoke;
I was greatly afflicted.

[[v19-116-11]]

^<<v19-116-11,11>>^ As for me, I panicked and said:
“Every man is a liar.”

[[v19-116-12]]

^<<v19-116-12,12>>^ With what will I repay Jehovah
For all the good he has done for me?

[[v19-116-13]]

^<<v19-116-13,13>>^ I will take up the cup of salvation,^&#42;1^
And I will call on the name of Jehovah.

[NOTE]
====
. Or “grand salvation.”
====

[[v19-116-14]]

^<<v19-116-14,14>>^ I will pay my vows to Jehovah
In the presence of all his people.

[[v19-116-15]]

^<<v19-116-15,15>>^ Costly^&#42;1^ in the eyes of Jehovah
Is the death of his loyal ones.

[NOTE]
====
. Lit., “Precious.”
====

[[v19-116-16]]

^<<v19-116-16,16>>^ I beg you, O Jehovah,
For I am your servant.
I am your servant, the son of your slave girl.
You have freed me from my bonds.

[[v19-116-17]]

^<<v19-116-17,17>>^ I will offer to you the sacrifice of thanksgiving;
I will call on the name of Jehovah.

[[v19-116-18]]

^<<v19-116-18,18>>^ I will pay my vows to Jehovah
In the presence of all his people,

[[v19-116-19]]

^<<v19-116-19,19>>^ In the courtyards of the house of Jehovah,
In your midst, O Jerusalem.
Praise Jah!^&#42;1^

[NOTE]
====
. Or “Hallelujah!” “Jah” is a shortened form of the name Jehovah.
====

'''

xref:019-psalm/019-psalm-115.adoc#v19-115-0[&#60; Capítulo Anterior] | <<v19-116-0,Topo>> | xref:019-psalm/019-psalm-117.adoc#v19-117-0[Próximo Capítulo &#62;]