include::./index.adoc[]

[[v19-59-0]]
=== Psalm, 59
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director; set to “Do Not Bring to Ruin.” Of David. Mikʹtam.^&#42;1^ When Saul sent men to watch David’s^&#42;2^ house to put him to death._

[[v19-59-1]]

^<<v19-59-1,1>>^ Rescue me from my enemies, O my God;
Protect me from those rising up against me.

[[v19-59-2]]

^<<v19-59-2,2>>^ Rescue me from those who act wickedly,
And save me from violent^&#42;1^ men.

[NOTE]
====
. Or “bloodthirsty.”
====

[[v19-59-3]]

^<<v19-59-3,3>>^ Look! They wait to ambush me;^&#42;1^
Strong men attack me
But not because I have revolted or sinned, O Jehovah.

[NOTE]
====
. Or “my soul.”
====

[[v19-59-4]]

^<<v19-59-4,4>>^ Though I did no wrong, they run and prepare to attack.
Do arise at my calling and see.

[[v19-59-5]]

^<<v19-59-5,5>>^ For you, O Jehovah God of armies, are the God of Israel.
Awake to turn your attention to all the nations.
Do not show mercy to any malicious traitors. (Selah)

[[v19-59-6]]

^<<v19-59-6,6>>^ They return each evening;
They growl^&#42;1^ like dogs and prowl around the city.

[NOTE]
====
. Or “bark.”
====

[[v19-59-7]]

^<<v19-59-7,7>>^ Look what pours^&#42;1^ forth from their mouth;
Their lips are like swords,
For they say: “Who is listening?”

[NOTE]
====
. Or “bubbles.”
====

[[v19-59-8]]

^<<v19-59-8,8>>^ But you, O Jehovah, will laugh at them;
You will scoff at all the nations.

[[v19-59-9]]

^<<v19-59-9,9>>^ O my Strength, I will keep watch for you;
For God is my secure refuge.^&#42;1^

[NOTE]
====
. Or “secure height.”
====

[[v19-59-10]]

^<<v19-59-10,10>>^ The God who shows loyal love to me will come to my aid;
God will cause me to look in triumph on my foes.

[[v19-59-11]]

^<<v19-59-11,11>>^ Do not kill them, so that my people may not forget.
By your power make them wander about;
Cause their downfall, O Jehovah, our shield.

[[v19-59-12]]

^<<v19-59-12,12>>^ For the sin of their mouth, the word of their lips,
May they be trapped by their pride,
Because of the cursing and deception that they speak.

[[v19-59-13]]

^<<v19-59-13,13>>^ Finish them off in your wrath;
Finish them off, so that they are no more;
Make them know that God is ruling in Jacob and to the ends of the earth. (Selah)

[[v19-59-14]]

^<<v19-59-14,14>>^ Let them return in the evening;
Let them growl^&#42;1^ like dogs and prowl around the city.

[NOTE]
====
. Or “bark.”
====

[[v19-59-15]]

^<<v19-59-15,15>>^ Let them wander about for something to eat;
Do not let them be satisfied or find a lodging place.

[[v19-59-16]]

^<<v19-59-16,16>>^ But as for me, I will sing about your strength;
In the morning I will joyfully tell about your loyal love.
For you are my secure refuge
And a place for me to flee in my time of distress.

[[v19-59-17]]

^<<v19-59-17,17>>^ O my Strength, to you I will sing praises,^&#42;1^
For God is my secure refuge, the God who shows loyal love to me.

[NOTE]
====
. Or “make music.”
====

'''

xref:019-psalm/019-psalm-058.adoc#v19-58-0[&#60; Capítulo Anterior] | <<v19-59-0,Topo>> | xref:019-psalm/019-psalm-060.adoc#v19-60-0[Próximo Capítulo &#62;]