include::./index.adoc[]

[[v19-97-0]]
=== Psalm, 97
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v19-97-1]]

^<<v19-97-1,1>>^ Jehovah has become King!
Let the earth be joyful.
Let the many islands rejoice.

[[v19-97-2]]

^<<v19-97-2,2>>^ Clouds and thick gloom are all around him;
Righteousness and justice are the foundation of his throne.

[[v19-97-3]]

^<<v19-97-3,3>>^ Fire goes before him
And consumes his adversaries on every side.

[[v19-97-4]]

^<<v19-97-4,4>>^ His lightning bolts light up the land;
The earth sees it and trembles.

[[v19-97-5]]

^<<v19-97-5,5>>^ The mountains melt like wax before Jehovah,
Before the Lord of the whole earth.

[[v19-97-6]]

^<<v19-97-6,6>>^ The heavens proclaim his righteousness,
And all the peoples see his glory.

[[v19-97-7]]

^<<v19-97-7,7>>^ Let all those serving any carved image be put to shame,
Those who boast about their worthless gods.
Bow down to^&#42;1^ him, all you gods.

[NOTE]
====
. Or “Worship.”
====

[[v19-97-8]]

^<<v19-97-8,8>>^ Zion hears and rejoices;
The towns^&#42;1^ of Judah are joyful
Because of your judgments, O Jehovah.

[NOTE]
====
. Lit., “daughters.”
====

[[v19-97-9]]

^<<v19-97-9,9>>^ For you, O Jehovah, are the Most High over all the earth;
You are exalted far above all other gods.

[[v19-97-10]]

^<<v19-97-10,10>>^ O you who love Jehovah, hate what is bad.
He is guarding the lives^&#42;1^ of his loyal ones;
He rescues them from the hand^&#42;2^ of the wicked.

[NOTE]
====
. Or “souls.”
. Or “power.”
====

[[v19-97-11]]

^<<v19-97-11,11>>^ Light has flashed up for the righteous
And rejoicing for those upright in heart.

[[v19-97-12]]

^<<v19-97-12,12>>^ Rejoice in Jehovah, you righteous ones,
And give thanks to his holy name.^&#42;1^

[NOTE]
====
. Lit., “memorial.”
====

'''

xref:019-psalm/019-psalm-096.adoc#v19-96-0[&#60; Capítulo Anterior] | <<v19-97-0,Topo>> | xref:019-psalm/019-psalm-098.adoc#v19-98-0[Próximo Capítulo &#62;]