include::./index.adoc[]

[[v19-141-0]]
=== Psalm, 141
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_A melody of David._

[[v19-141-1]]

^<<v19-141-1,1>>^ O Jehovah, I call on you.
Come quickly to help me.
Do pay attention when I call to you.

[[v19-141-2]]

^<<v19-141-2,2>>^ May my prayer be as incense prepared before you,
My uplifted hands like the evening grain offering.

[[v19-141-3]]

^<<v19-141-3,3>>^ Station a guard for my mouth, O Jehovah,
Do set a watch over the door of my lips.

[[v19-141-4]]

^<<v19-141-4,4>>^ Do not let my heart incline to anything bad,
To share in vile deeds with evil men;
May I never feast on their delicacies.

[[v19-141-5]]

^<<v19-141-5,5>>^ Should the righteous one strike me, it would be an act of loyal love;
Should he reprove me, it would be like oil on my head,
Which my head would never refuse.
My prayer will continue even during their calamities.

[[v19-141-6]]

^<<v19-141-6,6>>^ Though their judges are thrown down from the cliff,
The people will pay attention to my words, for they are pleasant.

[[v19-141-7]]

^<<v19-141-7,7>>^ Just as when someone plows and breaks up the soil,
So our bones have been scattered at the mouth of the Grave.^&#42;1^

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v19-141-8]]

^<<v19-141-8,8>>^ But my eyes look to you, O Sovereign Lord Jehovah.
In you I have taken refuge.
Do not take away my life.^&#42;1^

[NOTE]
====
. Or “pour out my soul.”
====

[[v19-141-9]]

^<<v19-141-9,9>>^ Protect me from the jaws of the trap they have laid for me,
From the snares of evildoers.

[[v19-141-10]]

^<<v19-141-10,10>>^ The wicked will fall into their own nets all together
While I pass by safely.

'''

xref:019-psalm/019-psalm-140.adoc#v19-140-0[&#60; Capítulo Anterior] | <<v19-141-0,Topo>> | xref:019-psalm/019-psalm-142.adoc#v19-142-0[Próximo Capítulo &#62;]