include::./index.adoc[]

[[v19-65-0]]
=== Psalm, 65
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director. A melody of David. A song._

[[v19-65-1]]

^<<v19-65-1,1>>^ Praise awaits you, O God, in Zion;
We will pay our vows to you.

[[v19-65-2]]

^<<v19-65-2,2>>^ O Hearer of prayer, to you people of all sorts^&#42;1^ will come.

[NOTE]
====
. Lit., “all flesh.”
====

[[v19-65-3]]

^<<v19-65-3,3>>^ My errors have overwhelmed me,
But you cover over our transgressions.

[[v19-65-4]]

^<<v19-65-4,4>>^ Happy is the one whom you choose and bring near
To reside in your courtyards.
We will be satisfied with the goodness of your house,
Your holy temple.^&#42;1^

[NOTE]
====
. Or “sanctuary.”
====

[[v19-65-5]]

^<<v19-65-5,5>>^ You will answer us with awe-inspiring deeds of righteousness,
O God of our salvation;
You are the Confidence of all the ends of the earth
And of those distant across the sea.

[[v19-65-6]]

^<<v19-65-6,6>>^ You^&#42;1^ firmly established the mountains by your power;
You^&#42;2^ are clothed with mightiness.

[NOTE]
====
. Lit., “He.”
. Lit., “He.”
====

[[v19-65-7]]

^<<v19-65-7,7>>^ You^&#42;1^ calm the raging seas,
The crash of their waves and the turmoil of the nations.

[NOTE]
====
. Lit., “He.”
====

[[v19-65-8]]

^<<v19-65-8,8>>^ The inhabitants of remote places will be awestruck by your signs;
You will cause those from the sunrise to the sunset to shout joyfully.

[[v19-65-9]]

^<<v19-65-9,9>>^ You care for the earth,
Making it abundantly fruitful^&#42;1^ and very rich.
The stream from God is full of water;
You provide grain for them,
For that is how you prepared the earth.

[NOTE]
====
. Lit., “making it overflow.”
====

[[v19-65-10]]

^<<v19-65-10,10>>^ You drench its furrows and level off its plowed soil;^&#42;1^
You soften it with showers of rain; you bless its growth.

[NOTE]
====
. Or “its ridges.”
====

[[v19-65-11]]

^<<v19-65-11,11>>^ You crown the year with your goodness;
Your tracks overflow with abundance.^&#42;1^

[NOTE]
====
. Lit., “drip with fatness.”
====

[[v19-65-12]]

^<<v19-65-12,12>>^ The pastures of the wilderness keep overflowing,^&#42;1^
And the hills are clothed with joyfulness.

[NOTE]
====
. Lit., “dripping.”
====

[[v19-65-13]]

^<<v19-65-13,13>>^ The pastures are covered with flocks,
And the valleys^&#42;1^ are carpeted with grain.
They shout in triumph, yes, they sing.

[NOTE]
====
. Or “low plains.”
====

'''

xref:019-psalm/019-psalm-064.adoc#v19-64-0[&#60; Capítulo Anterior] | <<v19-65-0,Topo>> | xref:019-psalm/019-psalm-066.adoc#v19-66-0[Próximo Capítulo &#62;]