include::./index.adoc[]

[[v19-18-0]]
=== Psalm, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director. By Jehovah’s servant David, who addressed the words of this song to Jehovah in the day that Jehovah rescued him from the hand of all his enemies and from the hand of Saul. He said:_

[[v19-18-1]]

^<<v19-18-1,1>>^ I have affection for you, O Jehovah, my strength.

[[v19-18-2]]

^<<v19-18-2,2>>^ Jehovah is my crag and my stronghold and the One who rescues me.
My God is my rock, in whom I take refuge,
My shield and my horn^&#42;1^ of salvation,^&#42;2^ my secure refuge.^&#42;3^

[NOTE]
====
. See Glossary.
. Or “my powerful savior.”
. Or “secure height.”
====

[[v19-18-3]]

^<<v19-18-3,3>>^ I call on Jehovah, who is worthy of praise,
And I will be saved from my enemies.

[[v19-18-4]]

^<<v19-18-4,4>>^ The ropes of death encircled me;
Flash floods of worthless men terrified me.

[[v19-18-5]]

^<<v19-18-5,5>>^ The ropes of the Grave^&#42;1^ surrounded me;
The snares of death confronted me.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v19-18-6]]

^<<v19-18-6,6>>^ In my distress I called on Jehovah,
To my God I kept crying for help.
From his temple he heard my voice,
And my cry to him for help reached his ears.

[[v19-18-7]]

^<<v19-18-7,7>>^ Then the earth began to shake and rock;
The foundations of the mountains trembled
And shook back and forth because he had been angered.

[[v19-18-8]]

^<<v19-18-8,8>>^ Smoke ascended from his nostrils,
And a consuming fire came from his mouth;
Glowing coals blazed from him.

[[v19-18-9]]

^<<v19-18-9,9>>^ He made the heavens bend as he descended,
And thick gloom was beneath his feet.

[[v19-18-10]]

^<<v19-18-10,10>>^ He rode on a cherub and came flying.
He swooped down on the wings of a spirit.^&#42;1^

[NOTE]
====
. Or “the wind.”
====

[[v19-18-11]]

^<<v19-18-11,11>>^ He then covered himself in darkness,
All around him as a shelter,
Dark waters and thick clouds.

[[v19-18-12]]

^<<v19-18-12,12>>^ From the brightness before him
Hail and fiery coals broke through the clouds.

[[v19-18-13]]

^<<v19-18-13,13>>^ Then Jehovah began to thunder in the heavens;
The Most High made his voice heard
With hailstones and fiery coals.

[[v19-18-14]]

^<<v19-18-14,14>>^ He shot his arrows and scattered them;
He hurled his lightning and threw them into confusion.

[[v19-18-15]]

^<<v19-18-15,15>>^ The streambeds^&#42;1^ became visible;
The foundations of the land were exposed by your rebuke, O Jehovah,
By the blast of the breath from your nostrils.

[NOTE]
====
. Or “water channels.”
====

[[v19-18-16]]

^<<v19-18-16,16>>^ He reached down from on high;
He took hold of me and pulled me from deep waters.

[[v19-18-17]]

^<<v19-18-17,17>>^ He rescued me from my strong enemy,
From those hating me, who were stronger than I was.

[[v19-18-18]]

^<<v19-18-18,18>>^ They confronted me on the day of my disaster,
But Jehovah was my support.

[[v19-18-19]]

^<<v19-18-19,19>>^ He brought me out into a place of safety;^&#42;1^
He rescued me because he was pleased with me.

[NOTE]
====
. Or “a roomy place.”
====

[[v19-18-20]]

^<<v19-18-20,20>>^ Jehovah rewards me according to my righteousness;
He repays me according to the innocence^&#42;1^ of my hands.

[NOTE]
====
. Lit., “the cleanness.”
====

[[v19-18-21]]

^<<v19-18-21,21>>^ For I have kept the ways of Jehovah,
And I have not wickedly abandoned my God.

[[v19-18-22]]

^<<v19-18-22,22>>^ All his judgments are before me;
I will not disregard his statutes.

[[v19-18-23]]

^<<v19-18-23,23>>^ I will remain blameless before him,
And I will keep myself from error.

[[v19-18-24]]

^<<v19-18-24,24>>^ May Jehovah repay me according to my righteousness,
According to the innocence of my hands before him.

[[v19-18-25]]

^<<v19-18-25,25>>^ With someone loyal you act in loyalty;
With the blameless man you deal blamelessly;

[[v19-18-26]]

^<<v19-18-26,26>>^ With the pure you show yourself pure,
But with the crooked you show yourself shrewd.

[[v19-18-27]]

^<<v19-18-27,27>>^ For you save those who are lowly^&#42;1^
But you abase the haughty.^&#42;2^

[NOTE]
====
. Or “afflicted.”
. Lit., “haughty eyes.”
====

[[v19-18-28]]

^<<v19-18-28,28>>^ For it is you who light my lamp, O Jehovah,
My God who lights up my darkness.

[[v19-18-29]]

^<<v19-18-29,29>>^ With your help I can charge against a marauder band;
By God’s power I can scale a wall.

[[v19-18-30]]

^<<v19-18-30,30>>^ The way of the true God is perfect;
The saying of Jehovah is refined.
He is a shield to all those taking refuge in him.

[[v19-18-31]]

^<<v19-18-31,31>>^ For who is a God besides Jehovah?
And who is a rock except our God?

[[v19-18-32]]

^<<v19-18-32,32>>^ The true God is the one who clothes me with strength,
And he will make my way perfect.

[[v19-18-33]]

^<<v19-18-33,33>>^ He makes my feet like those of a deer;
He makes me stand on high places.

[[v19-18-34]]

^<<v19-18-34,34>>^ He trains my hands for warfare;
My arms can bend a bow of copper.

[[v19-18-35]]

^<<v19-18-35,35>>^ You give me your shield of salvation,
Your right hand supports^&#42;1^ me,
And your humility makes me great.

[NOTE]
====
. Or “sustains.”
====

[[v19-18-36]]

^<<v19-18-36,36>>^ You widen the path for my footsteps;
My feet^&#42;1^ will not slip.

[NOTE]
====
. Or “ankles.”
====

[[v19-18-37]]

^<<v19-18-37,37>>^ I will pursue my enemies and overtake them;
I will not return until they are wiped out.

[[v19-18-38]]

^<<v19-18-38,38>>^ I will crush them so that they cannot rise up;
They will fall under my feet.

[[v19-18-39]]

^<<v19-18-39,39>>^ You will equip me with strength for the battle;
You will make my foes collapse under me.

[[v19-18-40]]

^<<v19-18-40,40>>^ You will make my enemies retreat from me,^&#42;1^
And I will put an end to^&#42;2^ those who hate me.

[NOTE]
====
. Or “You will give me the back of my enemies.”
. Lit., “silence.”
====

[[v19-18-41]]

^<<v19-18-41,41>>^ They cry for help, but there is no one to save them;
They even cry to Jehovah, but he does not answer them.

[[v19-18-42]]

^<<v19-18-42,42>>^ I will pound them as fine as dust in the wind;
I will throw them out like mud in the streets.

[[v19-18-43]]

^<<v19-18-43,43>>^ You will rescue me from the faultfinding of the people.
You will appoint me the head of nations.
A people whom I have not known will serve me.

[[v19-18-44]]

^<<v19-18-44,44>>^ At a mere report they will obey me;
Foreigners will come cringing before me.

[[v19-18-45]]

^<<v19-18-45,45>>^ Foreigners will lose courage;^&#42;1^
They will come trembling from their strongholds.

[NOTE]
====
. Or “fade away.”
====

[[v19-18-46]]

^<<v19-18-46,46>>^ Jehovah is alive! Praised be my Rock!
Let the God of my salvation be exalted.

[[v19-18-47]]

^<<v19-18-47,47>>^ The true God executes vengeance for me;
He subdues the peoples under me.

[[v19-18-48]]

^<<v19-18-48,48>>^ He rescues me from my angry enemies;
You lift me high above those who attack me;
You save me from the man of violence.

[[v19-18-49]]

^<<v19-18-49,49>>^ That is why I will glorify you among the nations, O Jehovah,
And to your name I will sing praises.^&#42;1^

[NOTE]
====
. Or “make music.”
====

[[v19-18-50]]

^<<v19-18-50,50>>^ He performs great acts of salvation^&#42;1^ for his king;
He displays loyal love to his anointed one,
To David and his offspring^&#42;2^ forever.

[NOTE]
====
. Or “great victories.”
. Lit., “seed.”
====

'''

xref:019-psalm/019-psalm-017.adoc#v19-17-0[&#60; Capítulo Anterior] | <<v19-18-0,Topo>> | xref:019-psalm/019-psalm-019.adoc#v19-19-0[Próximo Capítulo &#62;]