include::./index.adoc[]

[[v19-42-0]]
=== Psalm, 42
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_BOOK TWO_

_(Psalms 42-72)_

_To the director. Masʹkil^&#42;1^ of the sons of Korʹah._

[[v19-42-1]]

^<<v19-42-1,1>>^ As a deer that longs for streams of water,
So I long^&#42;1^ for you, O God.

[NOTE]
====
. Or “my soul longs.”
====

[[v19-42-2]]

^<<v19-42-2,2>>^ I do thirst^&#42;1^ for God, for the living God.
When may I come and appear before God?

[NOTE]
====
. Or “My soul thirsts.”
====

[[v19-42-3]]

^<<v19-42-3,3>>^ My tears are my food day and night;
All day long people taunt me: “Where is your God?”

[[v19-42-4]]

^<<v19-42-4,4>>^ These things I remember, and I pour out my soul,^&#42;1^
For I once walked along with the multitude;
I used to walk solemnly^&#42;2^ before them to the house of God,
With sounds of rejoicing and thanksgiving,
Those of a crowd celebrating a festival.

[NOTE]
====
. See Glossary.
. Or “slowly.”
====

[[v19-42-5]]

^<<v19-42-5,5>>^ Why am I^&#42;1^ in despair?
Why is this turmoil within me?
Wait for God,
For I will yet praise him as my Grand Savior.

[NOTE]
====
. Or “is my soul.”
====

[[v19-42-6]]

^<<v19-42-6,6>>^ My God, I am^&#42;1^ in despair.
That is why I remember you,
From the land of Jordan and the peaks of Herʹmon,
From Mount Mi·zarʹ.^&#42;2^

[NOTE]
====
. Or “my soul is.”
. Or “the little mountain.”
====

[[v19-42-7]]

^<<v19-42-7,7>>^ Deep waters call to deep waters
At the sound of your waterfalls.
All your surging waves have overwhelmed me.

[[v19-42-8]]

^<<v19-42-8,8>>^ By day Jehovah will grant me his loyal love,
And by night his song will be with me—a prayer to the God of my life.

[[v19-42-9]]

^<<v19-42-9,9>>^ I will say to God, my crag:
“Why have you forgotten me?
Why should I walk about sad because of the oppression by my enemy?”

[[v19-42-10]]

^<<v19-42-10,10>>^ With murderous hostility^&#42;1^ my enemies taunt me;
All day long they taunt me: “Where is your God?”

[NOTE]
====
. Or possibly, “As if crushing my bones.”
====

[[v19-42-11]]

^<<v19-42-11,11>>^ Why am I^&#42;1^ in despair?
Why is this turmoil within me?
Wait for God,
For I will yet praise him as my Grand Savior and my God.

[NOTE]
====
. Or “is my soul.”
====

'''

xref:019-psalm/019-psalm-041.adoc#v19-41-0[&#60; Capítulo Anterior] | <<v19-42-0,Topo>> | xref:019-psalm/019-psalm-043.adoc#v19-43-0[Próximo Capítulo &#62;]