include::./index.adoc[]

[[v19-80-0]]
=== Psalm, 80
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director; set to “The Lilies.” A reminder. Of Aʹsaph. A melody._

[[v19-80-1]]

^<<v19-80-1,1>>^ O Shepherd of Israel, listen,
You who are guiding Joseph just like a flock.
You who sit enthroned above^&#42;1^ the cherubs,
Shine forth.^&#42;2^

[NOTE]
====
. Or possibly, “between.”
. Or “Reveal your radiance.”
====

[[v19-80-2]]

^<<v19-80-2,2>>^ Before Eʹphra·im and Benjamin and Ma·nasʹseh,
Do stir up your mightiness;
Come and save us.

[[v19-80-3]]

^<<v19-80-3,3>>^ O God, restore us;
Let your face shine upon us, so that we may be saved.

[[v19-80-4]]

^<<v19-80-4,4>>^ Jehovah God of armies, how long will you be hostile toward^&#42;1^ the prayer of your people?

[NOTE]
====
. Lit., “fume against.”
====

[[v19-80-5]]

^<<v19-80-5,5>>^ You feed them tears as their bread,
And you make them drink tears beyond measure.

[[v19-80-6]]

^<<v19-80-6,6>>^ You let our neighbors quarrel over us;
Our enemies keep mocking us as they please.

[[v19-80-7]]

^<<v19-80-7,7>>^ O God of armies, restore us;
Let your face shine upon us, so that we may be saved.

[[v19-80-8]]

^<<v19-80-8,8>>^ You made a vine depart from Egypt.
You drove out the nations and planted it.

[[v19-80-9]]

^<<v19-80-9,9>>^ You cleared a space for it,
And it took root and filled the land.

[[v19-80-10]]

^<<v19-80-10,10>>^ The mountains were covered by its shadow,
And the cedars of God by its branches.

[[v19-80-11]]

^<<v19-80-11,11>>^ Its branches reached as far as the sea,
And its shoots to the River.^&#42;1^

[NOTE]
====
. That is, the Euphrates.
====

[[v19-80-12]]

^<<v19-80-12,12>>^ Why have you broken down the stone walls of the vineyard,
So that all those passing by pluck its fruit?

[[v19-80-13]]

^<<v19-80-13,13>>^ The boars of the forest ravage it,
And the wild animals of the field feed on it.

[[v19-80-14]]

^<<v19-80-14,14>>^ O God of armies, please return.
Look down from heaven and see!
Take care of this vine,

[[v19-80-15]]

^<<v19-80-15,15>>^ The stock^&#42;1^ that your right hand has planted,
And look upon the son whom^&#42;2^ you made strong for yourself.

[NOTE]
====
. Or “main stem of the vine.”
. Or “branch that.”
====

[[v19-80-16]]

^<<v19-80-16,16>>^ It is burned with fire, cut down.
They perish at your rebuke.^&#42;1^

[NOTE]
====
. Lit., “the rebuke of your face.”
====

[[v19-80-17]]

^<<v19-80-17,17>>^ May your hand give support to the man at your right hand,
To the son of man you have made strong for yourself.

[[v19-80-18]]

^<<v19-80-18,18>>^ Then we will not turn away from you.
Preserve us alive, so that we may call on your name.

[[v19-80-19]]

^<<v19-80-19,19>>^ O Jehovah God of armies, restore us;
Let your face shine upon us, so that we may be saved.

'''

xref:019-psalm/019-psalm-079.adoc#v19-79-0[&#60; Capítulo Anterior] | <<v19-80-0,Topo>> | xref:019-psalm/019-psalm-081.adoc#v19-81-0[Próximo Capítulo &#62;]