include::./index.adoc[]

[[v19-33-0]]
=== Psalm, 33
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v19-33-1]]

^<<v19-33-1,1>>^ Shout joyfully, you righteous ones, because of Jehovah.
It is fitting for the upright to praise him.

[[v19-33-2]]

^<<v19-33-2,2>>^ Give thanks to Jehovah with the harp;
Sing praises^&#42;1^ to him with a ten-stringed instrument.

[NOTE]
====
. Or “Make music.”
====

[[v19-33-3]]

^<<v19-33-3,3>>^ Sing to him a new song;
Play skillfully on the strings, along with shouts of joy.

[[v19-33-4]]

^<<v19-33-4,4>>^ For the word of Jehovah is upright,
And everything he does is trustworthy.

[[v19-33-5]]

^<<v19-33-5,5>>^ He loves righteousness and justice.
The earth is filled with Jehovah’s loyal love.

[[v19-33-6]]

^<<v19-33-6,6>>^ By the word of Jehovah the heavens were made,
And by the spirit^&#42;1^ of his mouth everything in them.^&#42;2^

[NOTE]
====
. Or “breath.”
. Lit., “all their army.”
====

[[v19-33-7]]

^<<v19-33-7,7>>^ He gathers the seawaters like a dam;
He puts the surging waters in storehouses.

[[v19-33-8]]

^<<v19-33-8,8>>^ Let the whole earth fear Jehovah.
Let the inhabitants of the productive land be in awe of him.

[[v19-33-9]]

^<<v19-33-9,9>>^ For he spoke, and it came to be;
He commanded, and it stood firm.

[[v19-33-10]]

^<<v19-33-10,10>>^ Jehovah has frustrated the schemes^&#42;1^ of the nations;
He has thwarted the plans^&#42;2^ of the peoples.

[NOTE]
====
. Or “counsel.”
. Or “thoughts.”
====

[[v19-33-11]]

^<<v19-33-11,11>>^ But the decisions^&#42;1^ of Jehovah will stand forever;
The thoughts of his heart are from generation to generation.

[NOTE]
====
. Or “counsel.”
====

[[v19-33-12]]

^<<v19-33-12,12>>^ Happy is the nation whose God is Jehovah,
The people he has chosen as his own possession.

[[v19-33-13]]

^<<v19-33-13,13>>^ Jehovah looks down from heaven;
He sees all the sons of men.

[[v19-33-14]]

^<<v19-33-14,14>>^ From his place of residence,
He gazes on the inhabitants of the earth.

[[v19-33-15]]

^<<v19-33-15,15>>^ He is the one forming the hearts of all;
He examines all their works.

[[v19-33-16]]

^<<v19-33-16,16>>^ No king is saved by a large army;
A mighty man is not saved by his great power.

[[v19-33-17]]

^<<v19-33-17,17>>^ The horse is a false hope for salvation;^&#42;1^
Its great strength does not ensure escape.

[NOTE]
====
. Or “for victory.”
====

[[v19-33-18]]

^<<v19-33-18,18>>^ Look! The eye of Jehovah watches over those fearing him,
Those waiting for his loyal love,

[[v19-33-19]]

^<<v19-33-19,19>>^ To rescue them^&#42;1^ from death
And to keep them alive during famine.

[NOTE]
====
. Or “their soul.”
====

[[v19-33-20]]

^<<v19-33-20,20>>^ We are^&#42;1^ in expectation of Jehovah.
He is our helper and our shield.

[NOTE]
====
. Or “Our soul is.”
====

[[v19-33-21]]

^<<v19-33-21,21>>^ Our hearts rejoice in him,
For we trust in his holy name.

[[v19-33-22]]

^<<v19-33-22,22>>^ May your loyal love rest upon us, O Jehovah,
While we keep waiting for you.

'''

xref:019-psalm/019-psalm-032.adoc#v19-32-0[&#60; Capítulo Anterior] | <<v19-33-0,Topo>> | xref:019-psalm/019-psalm-034.adoc#v19-34-0[Próximo Capítulo &#62;]