include::./index.adoc[]

[[v19-46-0]]
=== Psalm, 46
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director. Of the sons of Korʹah. According to the Alʹa·moth style.^&#42;1^ A song._

[[v19-46-1]]

^<<v19-46-1,1>>^ God is our refuge and strength,
A help that is readily found in times of distress.

[[v19-46-2]]

^<<v19-46-2,2>>^ That is why we will not fear, though the earth undergoes change,
Though the mountains topple into the depths of the sea,

[[v19-46-3]]

^<<v19-46-3,3>>^ Though its waters roar and foam over,
Though the mountains rock on account of its turbulence. (Selah)

[[v19-46-4]]

^<<v19-46-4,4>>^ There is a river the streams of which make the city of God rejoice,
The holy grand tabernacle of the Most High.

[[v19-46-5]]

^<<v19-46-5,5>>^ God is in the city; it cannot be overthrown.
God will come to its aid at the break of dawn.

[[v19-46-6]]

^<<v19-46-6,6>>^ The nations were in an uproar, the kingdoms were overthrown;
He raised his voice, and the earth melted.

[[v19-46-7]]

^<<v19-46-7,7>>^ Jehovah of armies is with us;
The God of Jacob is our secure refuge.^&#42;1^ (Selah)

[NOTE]
====
. Or “secure height.”
====

[[v19-46-8]]

^<<v19-46-8,8>>^ Come and witness the activities of Jehovah,
How he has done astonishing things on the earth.

[[v19-46-9]]

^<<v19-46-9,9>>^ He is bringing an end to wars throughout the earth.
He breaks the bow and shatters the spear;
He burns the military wagons^&#42;1^ with fire.

[NOTE]
====
. Or possibly, “the shields.”
====

[[v19-46-10]]

^<<v19-46-10,10>>^ “Give in and know that I am God.
I will be exalted among the nations;
I will be exalted in the earth.”

[[v19-46-11]]

^<<v19-46-11,11>>^ Jehovah of armies is with us;
The God of Jacob is a secure refuge for us. (Selah)

'''

xref:019-psalm/019-psalm-045.adoc#v19-45-0[&#60; Capítulo Anterior] | <<v19-46-0,Topo>> | xref:019-psalm/019-psalm-047.adoc#v19-47-0[Próximo Capítulo &#62;]