include::./index.adoc[]

[[v19-89-0]]
=== Psalm, 89
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_Masʹkil.^&#42;1^ Of Eʹthan the Ezʹra·hite._

[[v19-89-1]]

^<<v19-89-1,1>>^ I will sing about Jehovah’s expressions of loyal love forever.
With my mouth I will make known your faithfulness to all generations.

[[v19-89-2]]

^<<v19-89-2,2>>^ For I have said: “Loyal love will be built up^&#42;1^ forever,
And you have firmly established your faithfulness in the heavens.”

[NOTE]
====
. Or “endure.”
====

[[v19-89-3]]

^<<v19-89-3,3>>^ “I have made a covenant with my chosen one;
I have sworn to David my servant:

[[v19-89-4]]

^<<v19-89-4,4>>^ ‘I will firmly establish your offspring^&#42;1^ forever,
And I will build up your throne for all generations.’” (Selah)

[NOTE]
====
. Lit., “seed.”
====

[[v19-89-5]]

^<<v19-89-5,5>>^ The heavens praise your marvels, O Jehovah,
Yes, your faithfulness in the congregation of the holy ones.

[[v19-89-6]]

^<<v19-89-6,6>>^ For who in the skies can compare to Jehovah?
Who among the sons of God is like Jehovah?

[[v19-89-7]]

^<<v19-89-7,7>>^ God is held in awe in the council^&#42;1^ of holy ones;
He is grand and awe-inspiring to all who are around him.

[NOTE]
====
. Or “assembly.”
====

[[v19-89-8]]

^<<v19-89-8,8>>^ O Jehovah God of armies,
Who is mighty like you, O Jah?
Your faithfulness surrounds you.

[[v19-89-9]]

^<<v19-89-9,9>>^ You rule over the raging of the sea;
When its waves surge, you calm them.

[[v19-89-10]]

^<<v19-89-10,10>>^ You have crushed Raʹhab like one who is slain.
With your strong arm you have scattered your enemies.

[[v19-89-11]]

^<<v19-89-11,11>>^ The heavens are yours, and the earth is yours;
The productive land and what fills it—you have founded them.

[[v19-89-12]]

^<<v19-89-12,12>>^ The north and the south—you created them;
Taʹbor and Herʹmon joyously praise your name.

[[v19-89-13]]

^<<v19-89-13,13>>^ Your arm is mighty;
Your hand is strong;
Your right hand is exalted.

[[v19-89-14]]

^<<v19-89-14,14>>^ Righteousness and justice are the foundation of your throne;
Loyal love and faithfulness stand before you.

[[v19-89-15]]

^<<v19-89-15,15>>^ Happy are the people who know the joyful shouting.
O Jehovah, they walk in the light of your face.

[[v19-89-16]]

^<<v19-89-16,16>>^ They rejoice in your name all day long,
And in your righteousness they are exalted.

[[v19-89-17]]

^<<v19-89-17,17>>^ For you are the glory of their strength,
And by your approval our strength^&#42;1^ is exalted.

[NOTE]
====
. Lit., “horn.”
====

[[v19-89-18]]

^<<v19-89-18,18>>^ For our shield belongs to Jehovah,
Our king belongs to the Holy One of Israel.

[[v19-89-19]]

^<<v19-89-19,19>>^ At that time you spoke in a vision to your loyal ones and said:
“I have granted strength to a mighty one;
I have exalted a chosen one from among the people.

[[v19-89-20]]

^<<v19-89-20,20>>^ I have found David my servant;
With my holy oil I have anointed him.

[[v19-89-21]]

^<<v19-89-21,21>>^ My hand will support him,
And my arm will strengthen him.

[[v19-89-22]]

^<<v19-89-22,22>>^ No enemy will exact tribute from him,
And no unrighteous man will oppress him.

[[v19-89-23]]

^<<v19-89-23,23>>^ I will crush to pieces his adversaries from before him
And strike down those who hate him.

[[v19-89-24]]

^<<v19-89-24,24>>^ My faithfulness and loyal love are with him,
And in my name his strength^&#42;1^ will be exalted.

[NOTE]
====
. Lit., “horn.”
====

[[v19-89-25]]

^<<v19-89-25,25>>^ I will put his hand^&#42;1^ over the sea
And his right hand over the rivers.

[NOTE]
====
. Or “authority.”
====

[[v19-89-26]]

^<<v19-89-26,26>>^ He will call out to me: ‘You are my Father,
My God and the Rock of my salvation.’

[[v19-89-27]]

^<<v19-89-27,27>>^ And I will place him as firstborn,
The highest of the kings of the earth.

[[v19-89-28]]

^<<v19-89-28,28>>^ I will maintain my loyal love for him forever,
And my covenant with him will never fail.

[[v19-89-29]]

^<<v19-89-29,29>>^ I will establish his offspring^&#42;1^ forever
And make his throne as enduring as the heavens.

[NOTE]
====
. Lit., “seed.”
====

[[v19-89-30]]

^<<v19-89-30,30>>^ If his sons leave my law
And do not walk according to my decrees,^&#42;1^

[NOTE]
====
. Or “judgments.”
====

[[v19-89-31]]

^<<v19-89-31,31>>^ If they violate my statutes
And do not keep my commandments,

[[v19-89-32]]

^<<v19-89-32,32>>^ Then I will punish their disobedience^&#42;1^ with a rod
And their error with flogging.

[NOTE]
====
. Or “rebellion.”
====

[[v19-89-33]]

^<<v19-89-33,33>>^ But I will never abandon my loyal love for him
Nor be untrue to my promise.^&#42;1^

[NOTE]
====
. Lit., “Nor be false with my faithfulness.”
====

[[v19-89-34]]

^<<v19-89-34,34>>^ I will not violate my covenant
Or change what my lips have spoken.

[[v19-89-35]]

^<<v19-89-35,35>>^ I have sworn in my holiness, once and for all;
I will not tell lies to David.

[[v19-89-36]]

^<<v19-89-36,36>>^ His offspring^&#42;1^ will endure forever;
His throne will endure like the sun before me.

[NOTE]
====
. Lit., “seed.”
====

[[v19-89-37]]

^<<v19-89-37,37>>^ Like the moon, it will be firmly established forever
As a faithful witness in the skies.” (Selah)

[[v19-89-38]]

^<<v19-89-38,38>>^ But you yourself have cast off and rejected him;
You have become furious with your anointed one.

[[v19-89-39]]

^<<v19-89-39,39>>^ You have spurned the covenant with your servant;
You have profaned his crown^&#42;1^ by throwing it to the ground.

[NOTE]
====
. Or “diadem.”
====

[[v19-89-40]]

^<<v19-89-40,40>>^ You have broken down all his stone walls;^&#42;1^
You have reduced his fortifications to ruins.

[NOTE]
====
. Or “his shelters of stone.”
====

[[v19-89-41]]

^<<v19-89-41,41>>^ All who pass by have pillaged him;
He is a reproach to his neighbors.

[[v19-89-42]]

^<<v19-89-42,42>>^ You have made his adversaries victorious;^&#42;1^
You have caused all his enemies to rejoice.

[NOTE]
====
. Lit., “lifted up the right hand of his adversaries.”
====

[[v19-89-43]]

^<<v19-89-43,43>>^ You have also driven back his sword,
And you have made him lose ground in the battle.

[[v19-89-44]]

^<<v19-89-44,44>>^ You have brought an end to his splendor
And hurled his throne to the ground.

[[v19-89-45]]

^<<v19-89-45,45>>^ You have cut short the days of his youth;
You have clothed him with shame. (Selah)

[[v19-89-46]]

^<<v19-89-46,46>>^ How long, O Jehovah, will you hide yourself? Will it be forever?
Will your rage continue to burn like a fire?

[[v19-89-47]]

^<<v19-89-47,47>>^ Remember how short my life is!
Was it to no purpose that you created all humans?

[[v19-89-48]]

^<<v19-89-48,48>>^ What man can live and never see death?
Can he save himself^&#42;1^ from the power of the Grave?^&#42;2^ (Selah)

[NOTE]
====
. Or “his soul.”
. Lit., “the hand of Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v19-89-49]]

^<<v19-89-49,49>>^ Where are your former acts of loyal love, O Jehovah,
That you swore about to David in your faithfulness?

[[v19-89-50]]

^<<v19-89-50,50>>^ Remember, O Jehovah, the taunts hurled at your servants;
How I have to bear^&#42;1^ the taunts of all the peoples;

[NOTE]
====
. Lit., “carry in my bosom.”
====

[[v19-89-51]]

^<<v19-89-51,51>>^ How your enemies have hurled insults, O Jehovah;
How they have insulted every footstep of your anointed one.

[[v19-89-52]]

^<<v19-89-52,52>>^ May Jehovah be praised forever. Amen and Amen.

'''

xref:019-psalm/019-psalm-088.adoc#v19-88-0[&#60; Capítulo Anterior] | <<v19-89-0,Topo>> | xref:019-psalm/019-psalm-090.adoc#v19-90-0[Próximo Capítulo &#62;]