include::./index.adoc[]

[[v19-48-0]]
=== Psalm, 48
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_A song. A melody of the sons of Korʹah._

[[v19-48-1]]

^<<v19-48-1,1>>^ Jehovah is great and most worthy of praise
In the city of our God, in his holy mountain.

[[v19-48-2]]

^<<v19-48-2,2>>^ Beautiful in its loftiness, the joy of the whole earth,
Is Mount Zion in the far north,
The city of the Grand King.

[[v19-48-3]]

^<<v19-48-3,3>>^ In her fortified towers,
God has made known that he is a secure refuge.^&#42;1^

[NOTE]
====
. Or “secure height.”
====

[[v19-48-4]]

^<<v19-48-4,4>>^ For look! kings have assembled;^&#42;1^
Together they have advanced.

[NOTE]
====
. Or “met by appointment.”
====

[[v19-48-5]]

^<<v19-48-5,5>>^ When they saw it, they were amazed.
They panicked and fled in terror.

[[v19-48-6]]

^<<v19-48-6,6>>^ Trembling seized them there,
Anguish like that of a woman giving birth.

[[v19-48-7]]

^<<v19-48-7,7>>^ With an east wind you wreck the ships of Tarʹshish.

[[v19-48-8]]

^<<v19-48-8,8>>^ What we heard about, we have now seen for ourselves
In the city of Jehovah of armies, in the city of our God.
God will firmly establish it forever. (Selah)

[[v19-48-9]]

^<<v19-48-9,9>>^ We ponder your loyal love, O God,
Within your temple.

[[v19-48-10]]

^<<v19-48-10,10>>^ Like your name, O God, your praise
Reaches to the ends of the earth.
Your right hand is filled with righteousness.

[[v19-48-11]]

^<<v19-48-11,11>>^ May Mount Zion rejoice,
May the towns^&#42;1^ of Judah be joyful, because of your judgments.

[NOTE]
====
. Lit., “daughters.”
====

[[v19-48-12]]

^<<v19-48-12,12>>^ March around Zion; go all around it;
Count its towers.

[[v19-48-13]]

^<<v19-48-13,13>>^ Set your hearts upon its ramparts.^&#42;1^
Inspect its fortified towers,
So that you may tell about it to future generations.

[NOTE]
====
. Or “fortified walls.”
====

[[v19-48-14]]

^<<v19-48-14,14>>^ For this God is our God forever and ever.
He will guide us forevermore.^&#42;1^

[NOTE]
====
. Or possibly, “until we die.”
====

'''

xref:019-psalm/019-psalm-047.adoc#v19-47-0[&#60; Capítulo Anterior] | <<v19-48-0,Topo>> | xref:019-psalm/019-psalm-049.adoc#v19-49-0[Próximo Capítulo &#62;]