include::./index.adoc[]

[[v19-127-0]]
=== Psalm, 127
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_A Song of the Ascents. Of Solomon._

[[v19-127-1]]

^<<v19-127-1,1>>^ Unless Jehovah builds the house,
It is in vain that its builders work hard on it.
Unless Jehovah guards the city,
It is in vain that the guard stays awake.

[[v19-127-2]]

^<<v19-127-2,2>>^ It is in vain that you rise up early,
That you stay up late,
That you toil for your food,
Since he provides for his loved ones while giving them sleep.

[[v19-127-3]]

^<<v19-127-3,3>>^ Look! Sons^&#42;1^ are an inheritance from Jehovah;
The fruit of the womb is a reward.

[NOTE]
====
. Or “Children.”
====

[[v19-127-4]]

^<<v19-127-4,4>>^ Like arrows in the hand of a mighty man,
So are the sons of one’s youth.

[[v19-127-5]]

^<<v19-127-5,5>>^ Happy is the man who fills his quiver with them.
They will not be put to shame,
For they will speak with enemies in the city gate.

'''

xref:019-psalm/019-psalm-126.adoc#v19-126-0[&#60; Capítulo Anterior] | <<v19-127-0,Topo>> | xref:019-psalm/019-psalm-128.adoc#v19-128-0[Próximo Capítulo &#62;]