include::./index.adoc[]

[[v19-35-0]]
=== Psalm, 35
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_Of David._

[[v19-35-1]]

^<<v19-35-1,1>>^ O Jehovah, defend my case against my opposers;
Fight against those who fight against me.

[[v19-35-2]]

^<<v19-35-2,2>>^ Take up your buckler^&#42;1^ and large shield,
And rise up to my defense.

[NOTE]
====
. A small shield, often carried by archers.
====

[[v19-35-3]]

^<<v19-35-3,3>>^ Lift up your spear and battle-ax^&#42;1^ against my pursuers.
Say to me:^&#42;2^ “I am your salvation.”

[NOTE]
====
. Or “double ax.”
. Or “my soul.”
====

[[v19-35-4]]

^<<v19-35-4,4>>^ May those who are hunting for my life^&#42;1^ be put to shame and humiliated.
May those who are plotting to destroy me retreat in disgrace.

[NOTE]
====
. Or “my soul.”
====

[[v19-35-5]]

^<<v19-35-5,5>>^ May they become like chaff in the wind;
May Jehovah’s angel drive them away.

[[v19-35-6]]

^<<v19-35-6,6>>^ May their path be dark and slippery
As Jehovah’s angel pursues them.

[[v19-35-7]]

^<<v19-35-7,7>>^ For without cause they have hidden a net to trap me;
Without cause they have dug a pit for me.^&#42;1^

[NOTE]
====
. Or “my soul.”
====

[[v19-35-8]]

^<<v19-35-8,8>>^ May disaster come upon him by surprise;
May the net that he hid catch him;
May he fall into it and be destroyed.

[[v19-35-9]]

^<<v19-35-9,9>>^ But I^&#42;1^ will rejoice in Jehovah;
I will be joyful in his acts of salvation.

[NOTE]
====
. Or “my soul.”
====

[[v19-35-10]]

^<<v19-35-10,10>>^ All my bones will say:
“O Jehovah, who is like you?
You rescue the helpless from those who are stronger,
The helpless and the poor from those who rob them.”

[[v19-35-11]]

^<<v19-35-11,11>>^ Malicious witnesses come forward,
Asking me things I know nothing about.

[[v19-35-12]]

^<<v19-35-12,12>>^ They repay me with bad for good,
Making me^&#42;1^ feel bereaved.

[NOTE]
====
. Or “my soul.”
====

[[v19-35-13]]

^<<v19-35-13,13>>^ But when they were ill, I clothed myself with sackcloth;
I afflicted myself^&#42;1^ by fasting,
And when my prayer would return unanswered,^&#42;2^

[NOTE]
====
. Or “my soul.”
. Or “would return upon my bosom.”
====

[[v19-35-14]]

^<<v19-35-14,14>>^ I walked about mourning as for a friend or a brother of mine;
I bowed down in sorrow, like one mourning for his mother.

[[v19-35-15]]

^<<v19-35-15,15>>^ But when I stumbled, they rejoiced and gathered together;
They gathered together to strike me down in ambush;
They tore me to pieces and did not keep silent.

[[v19-35-16]]

^<<v19-35-16,16>>^ The ungodly scornfully mock me,^&#42;1^
They grind their teeth against me.

[NOTE]
====
. Or possibly, “The ungodly mock for a cake.”
====

[[v19-35-17]]

^<<v19-35-17,17>>^ O Jehovah, how long will you just look on?
Rescue me^&#42;1^ from their attacks,
My precious life^&#42;2^ from the young lions.^&#42;3^

[NOTE]
====
. Or “my soul.”
. Lit., “My only one,” referring to his soul, or life.
. Or “maned young lions.”
====

[[v19-35-18]]

^<<v19-35-18,18>>^ Then I will give thanks to you in the great congregation;
I will praise you among the throngs of people.

[[v19-35-19]]

^<<v19-35-19,19>>^ Do not let those who for no reason are my enemies gloat over me;
Do not let those hating me without cause wink their eyes maliciously.

[[v19-35-20]]

^<<v19-35-20,20>>^ For they do not speak words of peace,
But they deceptively scheme against the peaceful ones of the land.

[[v19-35-21]]

^<<v19-35-21,21>>^ They open their mouth wide to accuse me,
Saying: “Aha! Aha! Our eyes have seen it.”

[[v19-35-22]]

^<<v19-35-22,22>>^ You have seen this, O Jehovah. Do not remain silent.
O Jehovah, do not stay far from me.

[[v19-35-23]]

^<<v19-35-23,23>>^ Awake and rise to my defense,
My God, Jehovah, defend me in my legal case.

[[v19-35-24]]

^<<v19-35-24,24>>^ Judge me according to your righteousness, O Jehovah my God;
Do not let them gloat over me.

[[v19-35-25]]

^<<v19-35-25,25>>^ May they never say to themselves: “Aha! We got what we wanted.”^&#42;1^
May they never say: “We have swallowed him up.”

[NOTE]
====
. Or “Aha! Our soul.”
====

[[v19-35-26]]

^<<v19-35-26,26>>^ Let all of them be put to shame and disgraced,
Those who gloat over my calamity.
Let those who exalt themselves over me be clothed with shame and humiliation.

[[v19-35-27]]

^<<v19-35-27,27>>^ But let those who take pleasure in my righteousness shout joyfully;
May they constantly say:
“May Jehovah be magnified, who takes pleasure in the peace of his servant.”

[[v19-35-28]]

^<<v19-35-28,28>>^ Then my tongue will recount^&#42;1^ your righteousness
And praise you all day long.

[NOTE]
====
. Or “meditate on.”
====

'''

xref:019-psalm/019-psalm-034.adoc#v19-34-0[&#60; Capítulo Anterior] | <<v19-35-0,Topo>> | xref:019-psalm/019-psalm-036.adoc#v19-36-0[Próximo Capítulo &#62;]