include::./index.adoc[]

[[v19-137-0]]
=== Psalm, 137
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v19-137-1]]

^<<v19-137-1,1>>^ By the rivers of Babylon, there we sat.
We wept when we remembered Zion.

[[v19-137-2]]

^<<v19-137-2,2>>^ Upon the poplar trees in her^&#42;1^ midst,
We hung our harps.

[NOTE]
====
. Referring to Babylon.
====

[[v19-137-3]]

^<<v19-137-3,3>>^ For there our captors asked us for a song,
Those mocking us wanted amusement:
“Sing for us one of the songs of Zion.”

[[v19-137-4]]

^<<v19-137-4,4>>^ How can we sing the song of Jehovah
On foreign soil?

[[v19-137-5]]

^<<v19-137-5,5>>^ If I should forget you, O Jerusalem,
Let my right hand be forgetful.^&#42;1^

[NOTE]
====
. Or possibly, “wither.”
====

[[v19-137-6]]

^<<v19-137-6,6>>^ Let my tongue stick to my palate
If I do not remember you,
If I do not place Jerusalem above
My greatest reasons for rejoicing.

[[v19-137-7]]

^<<v19-137-7,7>>^ Remember, O Jehovah,
What the Eʹdom·ites said on the day Jerusalem fell:
“Tear it down! Tear it down to its foundations!”

[[v19-137-8]]

^<<v19-137-8,8>>^ O daughter of Babylon, who is soon to be devastated,
Happy will be the one who rewards you
With the treatment you inflicted on us.

[[v19-137-9]]

^<<v19-137-9,9>>^ Happy will be the one who seizes your children
And dashes them against the rocks.

'''

xref:019-psalm/019-psalm-136.adoc#v19-136-0[&#60; Capítulo Anterior] | <<v19-137-0,Topo>> | xref:019-psalm/019-psalm-138.adoc#v19-138-0[Próximo Capítulo &#62;]