include::./index.adoc[]

[[v19-44-0]]
=== Psalm, 44
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director. Of the sons of Korʹah. Masʹkil.^&#42;1^_

[[v19-44-1]]

^<<v19-44-1,1>>^ O God, we have heard with our own ears,
Our forefathers have recounted to us,
The deeds you accomplished in their days,
In the days of long ago.

[[v19-44-2]]

^<<v19-44-2,2>>^ With your hand you drove away nations
And settled our forefathers there.
You crushed nations and drove them out.

[[v19-44-3]]

^<<v19-44-3,3>>^ It was not by their own sword that they took possession of the land,
And their own arm did not bring them victory.
Rather, it was by your right hand and your arm and the light of your face,
For you took pleasure in them.

[[v19-44-4]]

^<<v19-44-4,4>>^ You are my King, O God;
Command^&#42;1^ complete victory^&#42;2^ for Jacob.

[NOTE]
====
. Or “Grant.”
. Or “grand salvation.”
====

[[v19-44-5]]

^<<v19-44-5,5>>^ By your power we will drive back our adversaries;
In your name we will trample down those who rise up against us.

[[v19-44-6]]

^<<v19-44-6,6>>^ For I do not trust in my bow,
And my sword cannot save me.

[[v19-44-7]]

^<<v19-44-7,7>>^ It was you who saved us from our adversaries,
You who humiliated those who hate us.

[[v19-44-8]]

^<<v19-44-8,8>>^ To God we will offer praise all day long,
And we will give thanks to your name forever. (Selah)

[[v19-44-9]]

^<<v19-44-9,9>>^ But now you have cast us off and humiliated us,
And you do not go out with our armies.

[[v19-44-10]]

^<<v19-44-10,10>>^ You keep making us retreat from our adversary;
Those who hate us take whatever they want.

[[v19-44-11]]

^<<v19-44-11,11>>^ You hand us over to be devoured like sheep;
You have scattered us among the nations.

[[v19-44-12]]

^<<v19-44-12,12>>^ You sell your people for next to nothing;
You make no profit from the sale.^&#42;1^

[NOTE]
====
. Or “by the price for them.”
====

[[v19-44-13]]

^<<v19-44-13,13>>^ You make us a reproach to our neighbors,
An object of ridicule and jeering to those all around us.

[[v19-44-14]]

^<<v19-44-14,14>>^ You make us an object of scorn^&#42;1^ among the nations,
Something for the peoples to shake their heads at.

[NOTE]
====
. Lit., “a proverb.”
====

[[v19-44-15]]

^<<v19-44-15,15>>^ I feel humiliated all day long,
And I am overwhelmed by my shame,

[[v19-44-16]]

^<<v19-44-16,16>>^ On account of the sound of their taunts and insults,
Because of our enemy who is taking revenge.

[[v19-44-17]]

^<<v19-44-17,17>>^ All of this has come upon us, yet we have not forgotten you,
And we have not violated your covenant.

[[v19-44-18]]

^<<v19-44-18,18>>^ Our heart has not deviated;
Our footsteps do not stray from your path.

[[v19-44-19]]

^<<v19-44-19,19>>^ But you have crushed us where the jackals dwell;
You have covered us with deep shadow.

[[v19-44-20]]

^<<v19-44-20,20>>^ If we have forgotten the name of our God
Or if we spread out our hands in prayer to a foreign god,

[[v19-44-21]]

^<<v19-44-21,21>>^ Will not God discover this?
He is aware of the secrets of the heart.

[[v19-44-22]]

^<<v19-44-22,22>>^ For your sake we are being put to death all day long;
We have been accounted as sheep for slaughtering.

[[v19-44-23]]

^<<v19-44-23,23>>^ Rouse yourself. Why do you keep sleeping, O Jehovah?
Awake! Do not keep casting us off forever.

[[v19-44-24]]

^<<v19-44-24,24>>^ Why do you hide your face?
Why do you forget our affliction and our oppression?

[[v19-44-25]]

^<<v19-44-25,25>>^ For we^&#42;1^ have been brought down to the dust;
Our bodies are pressed to the ground.

[NOTE]
====
. Or “our souls.”
====

[[v19-44-26]]

^<<v19-44-26,26>>^ Rise up as our helper!
Rescue^&#42;1^ us because of your loyal love.

[NOTE]
====
. Lit., “Redeem.”
====

'''

xref:019-psalm/019-psalm-043.adoc#v19-43-0[&#60; Capítulo Anterior] | <<v19-44-0,Topo>> | xref:019-psalm/019-psalm-045.adoc#v19-45-0[Próximo Capítulo &#62;]