include::./index.adoc[]

[[v19-51-0]]
=== Psalm, 51
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director. A melody of David, when Nathan the prophet came in to him after David had relations with Bath-sheʹba._

[[v19-51-1]]

^<<v19-51-1,1>>^ Show me favor, O God, according to your loyal love.
Blot out my transgressions according to your great mercy.

[[v19-51-2]]

^<<v19-51-2,2>>^ Thoroughly wash me from my error,
And cleanse me from my sin.

[[v19-51-3]]

^<<v19-51-3,3>>^ For I am well-aware of my transgressions,
And my sin is always before me.^&#42;1^

[NOTE]
====
. Or “on my mind.”
====

[[v19-51-4]]

^<<v19-51-4,4>>^ Against you—you above all^&#42;1^—I have sinned;
What is bad in your eyes I have done.
Therefore, you are righteous when you speak,
You are right in your judgment.

[NOTE]
====
. Lit., “only you.”
====

[[v19-51-5]]

^<<v19-51-5,5>>^ Look! I was born guilty of error,
And my mother conceived me in sin.^&#42;1^

[NOTE]
====
. Or “And sinful from the moment my mother conceived me.”
====

[[v19-51-6]]

^<<v19-51-6,6>>^ Look! You find pleasure in truth in the inner person;
Teach my innermost self^&#42;1^ true wisdom.

[NOTE]
====
. Or “my secret self.”
====

[[v19-51-7]]

^<<v19-51-7,7>>^ Purify me from my sin with hyssop, so that I will be clean;
Wash me, so that I will be whiter than snow.

[[v19-51-8]]

^<<v19-51-8,8>>^ Let me hear sounds of joy and rejoicing,
So that the bones you crushed will rejoice.

[[v19-51-9]]

^<<v19-51-9,9>>^ Turn your face away^&#42;1^ from my sins,
And wipe away^&#42;2^ all my errors.

[NOTE]
====
. Or “Hide your face.”
. Or “blot out.”
====

[[v19-51-10]]

^<<v19-51-10,10>>^ Create in me a pure heart, O God,
And put within me a new spirit, a steadfast one.

[[v19-51-11]]

^<<v19-51-11,11>>^ Do not cast me out from your presence;
And do not take your holy spirit away from me.

[[v19-51-12]]

^<<v19-51-12,12>>^ Restore to me the joy of your salvation;
Stir within me a willingness to obey you.^&#42;1^

[NOTE]
====
. Lit., “May you support me with a willing ­spirit.”
====

[[v19-51-13]]

^<<v19-51-13,13>>^ I will teach transgressors your ways,
So that sinners will return to you.

[[v19-51-14]]

^<<v19-51-14,14>>^ Save me from bloodguilt, O God, the God of my salvation,
So that my tongue may joyfully declare your righteousness.

[[v19-51-15]]

^<<v19-51-15,15>>^ O Jehovah, open my lips,
So that my mouth may declare your praise.

[[v19-51-16]]

^<<v19-51-16,16>>^ For you do not want a sacrifice—otherwise I would give it;
You do not find delight in a whole burnt offering.

[[v19-51-17]]

^<<v19-51-17,17>>^ The sacrifices pleasing to God are a broken spirit;
A heart broken and crushed, O God, you will not reject.^&#42;1^

[NOTE]
====
. Or “despise.”
====

[[v19-51-18]]

^<<v19-51-18,18>>^ In your goodwill do what is good for Zion;
Build up the walls of Jerusalem.

[[v19-51-19]]

^<<v19-51-19,19>>^ Then you will take delight in the sacrifices of righteousness,
The burnt sacrifices and the whole offerings;
Then bulls will be offered up on your altar.

'''

xref:019-psalm/019-psalm-050.adoc#v19-50-0[&#60; Capítulo Anterior] | <<v19-51-0,Topo>> | xref:019-psalm/019-psalm-052.adoc#v19-52-0[Próximo Capítulo &#62;]