include::./index.adoc[]

[[v19-31-0]]
=== Psalm, 31
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director. A melody of David._

[[v19-31-1]]

^<<v19-31-1,1>>^ In you, O Jehovah, I have taken refuge.
May I never be put to shame.
Rescue me because of your righteousness.

[[v19-31-2]]

^<<v19-31-2,2>>^ Incline your ear^&#42;1^ to me.
Come quickly to my rescue.
Become for me a mountain stronghold,
A fortified place to save me.

[NOTE]
====
. Or “Bend down and listen.”
====

[[v19-31-3]]

^<<v19-31-3,3>>^ For you are my crag and my stronghold;
For the sake of your name, you will lead me and guide me.

[[v19-31-4]]

^<<v19-31-4,4>>^ You will free me from the net that they have secretly laid for me,
For you are my fortress.

[[v19-31-5]]

^<<v19-31-5,5>>^ Into your hand I entrust my spirit.
You have redeemed me, O Jehovah, the God of truth.^&#42;1^

[NOTE]
====
. Or “the faithful God.”
====

[[v19-31-6]]

^<<v19-31-6,6>>^ I hate those who are devoted to worthless, vain idols,
But as for me, I trust in Jehovah.

[[v19-31-7]]

^<<v19-31-7,7>>^ I will rejoice greatly in your loyal love,
For you have seen my affliction;
You are aware of my deep distress.^&#42;1^

[NOTE]
====
. Or “the distresses of my soul.”
====

[[v19-31-8]]

^<<v19-31-8,8>>^ You have not handed me over to the enemy,
But you make me stand in a place of safety.^&#42;1^

[NOTE]
====
. Or “a roomy place.”
====

[[v19-31-9]]

^<<v19-31-9,9>>^ Show me favor, O Jehovah, for I am in distress.
Anguish has made my eyes weak, my whole body^&#42;1^ as well.

[NOTE]
====
. Or “my soul and my belly.”
====

[[v19-31-10]]

^<<v19-31-10,10>>^ My life is consumed with grief
And my years with groaning.
My strength is waning because of my error;
My bones grow weak.

[[v19-31-11]]

^<<v19-31-11,11>>^ I am scorned by all my adversaries,
Especially my neighbors.
And I am dreaded by my acquaintances;
When they see me in public, they flee from me.

[[v19-31-12]]

^<<v19-31-12,12>>^ I am put out of their heart^&#42;1^ and forgotten, as if I were dead;
I am like a broken jar.

[NOTE]
====
. Or “mind.”
====

[[v19-31-13]]

^<<v19-31-13,13>>^ I have heard many evil rumors;
Terror surrounds me.
When they gather together as one against me,
They scheme to take away my life.^&#42;1^

[NOTE]
====
. Or “soul.”
====

[[v19-31-14]]

^<<v19-31-14,14>>^ But I trust in you, O Jehovah.
I declare: “You are my God.”

[[v19-31-15]]

^<<v19-31-15,15>>^ My days^&#42;1^ are in your hand.
Rescue me from the hand of my enemies and from those persecuting me.

[NOTE]
====
. Lit., “times.”
====

[[v19-31-16]]

^<<v19-31-16,16>>^ Make your face shine upon your servant.
Save me by your loyal love.

[[v19-31-17]]

^<<v19-31-17,17>>^ O Jehovah, may I not be put to shame when I call on you.
May the wicked be put to shame;
May they be silenced in the Grave.^&#42;1^

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v19-31-18]]

^<<v19-31-18,18>>^ May lying lips become speechless,
Lips that speak arrogantly against the righteous, with haughtiness and contempt.

[[v19-31-19]]

^<<v19-31-19,19>>^ How abundant your goodness is!
You have stored it up for those who fear you,
And you have shown it before all men, in behalf of those taking refuge in you.

[[v19-31-20]]

^<<v19-31-20,20>>^ You will conceal them in the secret place of your presence
From the schemes of men;
You will hide them in your shelter
From malicious attacks.^&#42;1^

[NOTE]
====
. Lit., “From the quarreling of tongues.”
====

[[v19-31-21]]

^<<v19-31-21,21>>^ May Jehovah be praised,
For in a wonderful way, he has shown his loyal love to me in a besieged city.

[[v19-31-22]]

^<<v19-31-22,22>>^ As for me, I panicked and said:
“I will perish from before you.”
But you heard my pleas for help when I cried out to you.

[[v19-31-23]]

^<<v19-31-23,23>>^ Love Jehovah, all you who are loyal to him!
Jehovah protects the faithful,
But he repays exceedingly anyone showing haughtiness.

[[v19-31-24]]

^<<v19-31-24,24>>^ Be courageous, and may your heart be strong,
All you who are waiting for Jehovah.

'''

xref:019-psalm/019-psalm-030.adoc#v19-30-0[&#60; Capítulo Anterior] | <<v19-31-0,Topo>> | xref:019-psalm/019-psalm-032.adoc#v19-32-0[Próximo Capítulo &#62;]