include::./index.adoc[]

[[v19-132-0]]
=== Psalm, 132
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_A Song of the Ascents._

[[v19-132-1]]

^<<v19-132-1,1>>^ O Jehovah, remember David
And all his suffering;

[[v19-132-2]]

^<<v19-132-2,2>>^ How he swore to Jehovah,
How he vowed to the Powerful One of Jacob:

[[v19-132-3]]

^<<v19-132-3,3>>^ “I will not go into my tent, my home.
I will not lie upon my couch, my bed;

[[v19-132-4]]

^<<v19-132-4,4>>^ I will not allow my eyes to sleep,
Nor my eyelids to slumber

[[v19-132-5]]

^<<v19-132-5,5>>^ Until I find a place for Jehovah,
A fine residence^&#42;1^ for the Powerful One of Jacob.”

[NOTE]
====
. Or “A grand tabernacle.”
====

[[v19-132-6]]

^<<v19-132-6,6>>^ Look! We heard about it in Ephʹra·thah;
We found it in the fields of the forest.

[[v19-132-7]]

^<<v19-132-7,7>>^ Let us come into his residence;^&#42;1^
Let us bow down at his footstool.

[NOTE]
====
. Or “his grand tabernacle.”
====

[[v19-132-8]]

^<<v19-132-8,8>>^ Rise up, O Jehovah, to come to your resting-place,
You and the Ark of your strength.

[[v19-132-9]]

^<<v19-132-9,9>>^ May your priests be clothed with righteousness,
And may your loyal ones shout joyfully.

[[v19-132-10]]

^<<v19-132-10,10>>^ For the sake of David your servant,
Do not reject^&#42;1^ your anointed one.

[NOTE]
====
. Lit., “turn back the face of.”
====

[[v19-132-11]]

^<<v19-132-11,11>>^ Jehovah has sworn to David;
He will surely not go back on his word:
“One of your offspring,^&#42;1^
I will place on your throne.

[NOTE]
====
. Lit., “of the fruit of your womb.”
====

[[v19-132-12]]

^<<v19-132-12,12>>^ If your sons keep my covenant
And my reminders that I teach them,
Their sons too
Will sit on your throne forever.”

[[v19-132-13]]

^<<v19-132-13,13>>^ For Jehovah has chosen Zion;
He has desired it for his dwelling place:

[[v19-132-14]]

^<<v19-132-14,14>>^ “This is my resting-place forever;
Here I will dwell, for this is my desire.

[[v19-132-15]]

^<<v19-132-15,15>>^ I will richly bless it with provisions;
I will satisfy its poor with bread.

[[v19-132-16]]

^<<v19-132-16,16>>^ Its priests I will clothe with salvation,
And its loyal ones will shout joyfully.

[[v19-132-17]]

^<<v19-132-17,17>>^ There I will make the strength^&#42;1^ of David grow.
I have prepared a lamp for my anointed one.

[NOTE]
====
. Lit., “horn.”
====

[[v19-132-18]]

^<<v19-132-18,18>>^ I will clothe his enemies with shame,
But the crown^&#42;1^ on his head will flourish.”

[NOTE]
====
. Or “diadem.”
====

'''

xref:019-psalm/019-psalm-131.adoc#v19-131-0[&#60; Capítulo Anterior] | <<v19-132-0,Topo>> | xref:019-psalm/019-psalm-133.adoc#v19-133-0[Próximo Capítulo &#62;]