include::./index.adoc[]

[[v19-4-0]]
=== Psalm, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director; to be accompanied with stringed instruments. A melody of David._

[[v19-4-1]]

^<<v19-4-1,1>>^ When I call, answer me, O my righteous God.
Make a way of escape^&#42;1^ for me in my distress.
Show me favor and hear my prayer.

[NOTE]
====
. Lit., “Make broad space.”
====

[[v19-4-2]]

^<<v19-4-2,2>>^ You sons of men, how long will you turn my honor into humiliation?
How long will you love what is worthless and search for what is false? (Selah)

[[v19-4-3]]

^<<v19-4-3,3>>^ Know that Jehovah will treat his loyal one in a special way;^&#42;1^
Jehovah will hear when I call to him.

[NOTE]
====
. Or “distinguish his loyal one; set his loyal one apart for himself.”
====

[[v19-4-4]]

^<<v19-4-4,4>>^ Be agitated, but do not sin.
Have your say in your heart, upon your bed, and keep silent. (Selah)

[[v19-4-5]]

^<<v19-4-5,5>>^ Offer the sacrifices of righteousness,
And trust in Jehovah.

[[v19-4-6]]

^<<v19-4-6,6>>^ There are many saying: “Who will show us anything good?”
Let the light of your face shine upon us, O Jehovah.

[[v19-4-7]]

^<<v19-4-7,7>>^ You have filled my heart with greater rejoicing
Than those who have an abundant harvest of grain and new wine.

[[v19-4-8]]

^<<v19-4-8,8>>^ I will lie down and sleep in peace,
For you alone, O Jehovah, make me dwell in security.

'''

xref:019-psalm/019-psalm-003.adoc#v19-3-0[&#60; Capítulo Anterior] | <<v19-4-0,Topo>> | xref:019-psalm/019-psalm-005.adoc#v19-5-0[Próximo Capítulo &#62;]