include::./index.adoc[]

[[v19-82-0]]
=== Psalm, 82
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_A melody of Aʹsaph._

[[v19-82-1]]

^<<v19-82-1,1>>^ God takes his place in the divine assembly;^&#42;1^
In the middle of the gods^&#42;2^ he judges:

[NOTE]
====
. Or “in the assembly of the Divine One.”
. Or “godlike ones.”
====

[[v19-82-2]]

^<<v19-82-2,2>>^ “How long will you continue to judge with injustice
And show partiality to the wicked? (Selah)

[[v19-82-3]]

^<<v19-82-3,3>>^ Defend^&#42;1^ the lowly and the fatherless.
Render justice to the helpless and destitute.

[NOTE]
====
. Or “Judge.”
====

[[v19-82-4]]

^<<v19-82-4,4>>^ Rescue the lowly and the poor;
Save them out of the hand of the wicked.”

[[v19-82-5]]

^<<v19-82-5,5>>^ They do not know, nor do they understand;
They are walking about in darkness;
All the foundations of the earth are being shaken.

[[v19-82-6]]

^<<v19-82-6,6>>^ “I have said, ‘You are gods,^&#42;1^
All of you are sons of the Most High.

[NOTE]
====
. Or “godlike ones.”
====

[[v19-82-7]]

^<<v19-82-7,7>>^ But you will die just as men do;
And like any other prince you will fall!’”

[[v19-82-8]]

^<<v19-82-8,8>>^ Rise up, O God, and judge the earth,
For all the nations belong to you.

'''

xref:019-psalm/019-psalm-081.adoc#v19-81-0[&#60; Capítulo Anterior] | <<v19-82-0,Topo>> | xref:019-psalm/019-psalm-083.adoc#v19-83-0[Próximo Capítulo &#62;]