include::./index.adoc[]

[[v19-101-0]]
=== Psalm, 101
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_Of David. A melody._

[[v19-101-1]]

^<<v19-101-1,1>>^ I will sing about loyal love and justice.
To you, O Jehovah, I will sing praises.^&#42;1^

[NOTE]
====
. Or “make music.”
====

[[v19-101-2]]

^<<v19-101-2,2>>^ I will act with discretion and blamelessness.^&#42;1^
When will you come to me?
I will walk with integrity of heart inside my house.

[NOTE]
====
. Or “integrity.”
====

[[v19-101-3]]

^<<v19-101-3,3>>^ I will not set anything worthless^&#42;1^ before my eyes.
I hate the deeds of those who deviate from what is right;
I will have nothing to do with them.^&#42;2^

[NOTE]
====
. Or “good-for-nothing.”
. Or “Their deeds do not cling to me.”
====

[[v19-101-4]]

^<<v19-101-4,4>>^ A crooked heart is far from me;
I will not accept^&#42;1^ what is bad.

[NOTE]
====
. Lit., “know.”
====

[[v19-101-5]]

^<<v19-101-5,5>>^ Anyone slandering his neighbor in secret,
I will silence.^&#42;1^
Anyone with haughty eyes and an arrogant heart,
I will not tolerate.

[NOTE]
====
. Or “do away with.”
====

[[v19-101-6]]

^<<v19-101-6,6>>^ I will look to the faithful ones of the earth,
So that they may dwell with me.
The one walking in blamelessness^&#42;1^ will minister to me.

[NOTE]
====
. Or “in integrity.”
====

[[v19-101-7]]

^<<v19-101-7,7>>^ No deceitful person will dwell in my house,
And no liar will stand in my presence.^&#42;1^

[NOTE]
====
. Lit., “in front of my eyes.”
====

[[v19-101-8]]

^<<v19-101-8,8>>^ Every morning I will silence^&#42;1^ all the wicked of the earth,
To cut off all wrongdoers from the city of Jehovah.

[NOTE]
====
. Or “do away with.”
====

'''

xref:019-psalm/019-psalm-100.adoc#v19-100-0[&#60; Capítulo Anterior] | <<v19-101-0,Topo>> | xref:019-psalm/019-psalm-102.adoc#v19-102-0[Próximo Capítulo &#62;]