include::./index.adoc[]

[[v19-69-0]]
=== Psalm, 69
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_To the director; set to “The Lilies.” Of David._

[[v19-69-1]]

^<<v19-69-1,1>>^ Save me, O God, for the waters threaten my life.^&#42;1^

[NOTE]
====
. Or “have come to my soul.”
====

[[v19-69-2]]

^<<v19-69-2,2>>^ I have sunk down into the deep mud, where there is no solid ground.
I have come into deep waters,
And the rushing stream has swept me away.

[[v19-69-3]]

^<<v19-69-3,3>>^ I am exhausted from calling out;
My throat has become hoarse.
My eyes have grown weary while waiting for my God.

[[v19-69-4]]

^<<v19-69-4,4>>^ Those hating me without cause
Are more numerous than the hairs of my head.
Those who would do away with me,
My treacherous enemies,^&#42;1^ have become many.
I was forced to hand over what I had not stolen.

[NOTE]
====
. Or “enemies for no reason.”
====

[[v19-69-5]]

^<<v19-69-5,5>>^ O God, you are aware of my foolishness,
And my guilt is not hidden from you.

[[v19-69-6]]

^<<v19-69-6,6>>^ May those hoping in you not be put to shame because of me,
O Sovereign Lord, Jehovah of armies.
May those seeking you not be humiliated because of me,
O God of Israel.

[[v19-69-7]]

^<<v19-69-7,7>>^ I suffer reproach on your account;
Humiliation covers my face.

[[v19-69-8]]

^<<v19-69-8,8>>^ I have become a stranger to my brothers,
A foreigner to the sons of my mother.

[[v19-69-9]]

^<<v19-69-9,9>>^ Zeal for your house has consumed me,
And the reproaches of those reproaching you have fallen upon me.

[[v19-69-10]]

^<<v19-69-10,10>>^ When I humbled myself^&#42;1^ with fasting,^&#42;2^
I was reproached for it.

[NOTE]
====
. Or “my soul.”
. Or possibly, “When I wept and fasted.”
====

[[v19-69-11]]

^<<v19-69-11,11>>^ When I made sackcloth my clothing,
I became an object of scorn^&#42;1^ to them.

[NOTE]
====
. Lit., “a proverb.”
====

[[v19-69-12]]

^<<v19-69-12,12>>^ I am the talk of those sitting in the city gate,
And the drunkards make me the subject of their songs.

[[v19-69-13]]

^<<v19-69-13,13>>^ But may my prayer come to you,
O Jehovah, at an acceptable time.
In your abundant loyal love, O God,
Answer me with your sure acts of salvation.

[[v19-69-14]]

^<<v19-69-14,14>>^ Rescue me from the mire;
Do not let me sink down.
Rescue me from those who hate me
And from the deep waters.

[[v19-69-15]]

^<<v19-69-15,15>>^ Do not let the rushing floodwaters sweep me away,
Or let the deep swallow me,
Or let the well^&#42;1^ close its mouth over me.

[NOTE]
====
. Or “pit.”
====

[[v19-69-16]]

^<<v19-69-16,16>>^ Answer me, O Jehovah, for your loyal love is good.
According to your abundant mercy turn toward me,

[[v19-69-17]]

^<<v19-69-17,17>>^ And do not hide your face from your servant.
Answer me quickly, for I am in distress.

[[v19-69-18]]

^<<v19-69-18,18>>^ Come near to me and rescue me;^&#42;1^
Redeem me on account of my enemies.

[NOTE]
====
. Or “Come near to my soul and reclaim it.”
====

[[v19-69-19]]

^<<v19-69-19,19>>^ You know my reproach and my disgrace and my humiliation.
You see all my foes.

[[v19-69-20]]

^<<v19-69-20,20>>^ Reproach has broken my heart, and the wound is incurable.^&#42;1^
I was hoping for sympathy, but there was none,
And for comforters, but I found none.

[NOTE]
====
. Or “and I am to the point of despair.”
====

[[v19-69-21]]

^<<v19-69-21,21>>^ But for food they gave me poison,^&#42;1^
And for my thirst they gave me vinegar to drink.

[NOTE]
====
. Or “a poisonous plant.”
====

[[v19-69-22]]

^<<v19-69-22,22>>^ Let their table become a trap for them,
And their prosperity, a snare.

[[v19-69-23]]

^<<v19-69-23,23>>^ Let their eyes become darkened so that they cannot see,
And make their hips tremble constantly.

[[v19-69-24]]

^<<v19-69-24,24>>^ Pour out upon them your indignation,^&#42;1^
And may your burning anger overtake them.

[NOTE]
====
. Or “wrath.”
====

[[v19-69-25]]

^<<v19-69-25,25>>^ Let their encampment^&#42;1^ become desolate;
Let there be no inhabitant in their tents.

[NOTE]
====
. Or “walled camp.”
====

[[v19-69-26]]

^<<v19-69-26,26>>^ For they pursue the one whom you struck,
And they keep recounting the pains of those you wounded.

[[v19-69-27]]

^<<v19-69-27,27>>^ Add more guilt to their guilt,
And may they have no share in your righteousness.

[[v19-69-28]]

^<<v19-69-28,28>>^ Let them be erased from the book of the living,^&#42;1^
And may they not be enrolled among the righteous.

[NOTE]
====
. Or “book of life.”
====

[[v19-69-29]]

^<<v19-69-29,29>>^ But I am afflicted and in pain.
May your saving power, O God, protect me.

[[v19-69-30]]

^<<v19-69-30,30>>^ I will sing praises to the name of God,
And I will magnify him with thanksgiving.

[[v19-69-31]]

^<<v19-69-31,31>>^ This will please Jehovah more than a bull,
More than a young bull with horns and hooves.

[[v19-69-32]]

^<<v19-69-32,32>>^ The meek will see it and rejoice.
You who are seeking God, may your hearts revive.

[[v19-69-33]]

^<<v19-69-33,33>>^ For Jehovah is listening to the poor,
And he will not despise his captive people.

[[v19-69-34]]

^<<v19-69-34,34>>^ Let heaven and earth praise him,
The seas and everything that moves in them.

[[v19-69-35]]

^<<v19-69-35,35>>^ For God will save Zion
And will rebuild the cities of Judah,
And they will dwell there and possess it.^&#42;1^

[NOTE]
====
. That is, the land.
====

[[v19-69-36]]

^<<v19-69-36,36>>^ The descendants of his servants will inherit it,
And those who love his name will reside in it.

'''

xref:019-psalm/019-psalm-068.adoc#v19-68-0[&#60; Capítulo Anterior] | <<v19-69-0,Topo>> | xref:019-psalm/019-psalm-070.adoc#v19-70-0[Próximo Capítulo &#62;]