include::./index.adoc[]

[[v19-145-0]]
=== Psalm, 145
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_A praise of David._

_א &#91;Aleph&#93;_

[[v19-145-1]]

^<<v19-145-1,1>>^ I will exalt you, O my God the King,
I will praise your name forever and ever.

_ב &#91;Beth&#93;_

[[v19-145-2]]

^<<v19-145-2,2>>^ All day long I will praise you;
I will praise your name forever and ever.

_ג &#91;Gimel&#93;_

[[v19-145-3]]

^<<v19-145-3,3>>^ Jehovah is great and most worthy of praise;
His greatness is unsearchable.^&#42;1^

[NOTE]
====
. Or “beyond understanding.”
====

_ד &#91;Daleth&#93;_

[[v19-145-4]]

^<<v19-145-4,4>>^ Generation after generation will praise your works;
They will tell about your mighty acts.

_ה &#91;He&#93;_

[[v19-145-5]]

^<<v19-145-5,5>>^ Of the glorious splendor of your majesty they will speak
And on your wonderful works I will meditate.

_ו &#91;Waw&#93;_

[[v19-145-6]]

^<<v19-145-6,6>>^ They will speak about your awe-inspiring deeds,^&#42;1^
And I will declare your greatness.

[NOTE]
====
. Or “power.”
====

_ז &#91;Zayin&#93;_

[[v19-145-7]]

^<<v19-145-7,7>>^ They will bubble over as they recall your abundant goodness,
And they will shout joyfully because of your righteousness.

_ח &#91;Heth&#93;_

[[v19-145-8]]

^<<v19-145-8,8>>^ Jehovah is compassionate^&#42;1^ and merciful,
Slow to anger and great in loyal love.

[NOTE]
====
. Or “gracious.”
====

_ט &#91;Teth&#93;_

[[v19-145-9]]

^<<v19-145-9,9>>^ Jehovah is good to all,
And his mercy is evident in all his works.

_י &#91;Yod&#93;_

[[v19-145-10]]

^<<v19-145-10,10>>^ All your works will glorify you, O Jehovah,
And your loyal ones will praise you.

_כ &#91;Kaph&#93;_

[[v19-145-11]]

^<<v19-145-11,11>>^ They will proclaim the glory of your kingship
And speak about your mightiness,

_ל &#91;Lamed&#93;_

[[v19-145-12]]

^<<v19-145-12,12>>^ To make known to men your mighty acts
And the glorious splendor of your kingship.

_מ &#91;Mem&#93;_

[[v19-145-13]]

^<<v19-145-13,13>>^ Your kingship is an eternal kingship,
And your dominion endures throughout all generations.

_ס &#91;Samekh&#93;_

[[v19-145-14]]

^<<v19-145-14,14>>^ Jehovah supports all who are falling
And raises up all who are bowed down.

_ע &#91;Ayin&#93;_

[[v19-145-15]]

^<<v19-145-15,15>>^ All eyes look hopefully to you;
You give them their food in its season.

_פ &#91;Pe&#93;_

[[v19-145-16]]

^<<v19-145-16,16>>^ You open your hand
And satisfy the desire of every living thing.

_צ &#91;Tsade&#93;_

[[v19-145-17]]

^<<v19-145-17,17>>^ Jehovah is righteous in all his ways
And loyal in all that he does.

_ק &#91;Qoph&#93;_

[[v19-145-18]]

^<<v19-145-18,18>>^ Jehovah is near to all those calling on him,
To all who call on him in truth.^&#42;1^

[NOTE]
====
. Or “in sincerity.”
====

_ר &#91;Resh&#93;_

[[v19-145-19]]

^<<v19-145-19,19>>^ He satisfies the desire of those who fear him;
He hears their cry for help, and he rescues them.

_ש &#91;Shin&#93;_

[[v19-145-20]]

^<<v19-145-20,20>>^ Jehovah guards all those who love him,
But all the wicked he will annihilate.

_ת &#91;Taw&#93;_

[[v19-145-21]]

^<<v19-145-21,21>>^ My mouth will declare the praise of Jehovah;
Let every living thing^&#42;1^ praise his holy name forever and ever.

[NOTE]
====
. Lit., “all flesh.”
====

'''

xref:019-psalm/019-psalm-144.adoc#v19-144-0[&#60; Capítulo Anterior] | <<v19-145-0,Topo>> | xref:019-psalm/019-psalm-146.adoc#v19-146-0[Próximo Capítulo &#62;]