include::./index.adoc[]

[[v19-136-0]]
=== Psalm, 136
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v19-136-1]]

^<<v19-136-1,1>>^ Give thanks to Jehovah, for he is good;
His loyal love endures forever.

[[v19-136-2]]

^<<v19-136-2,2>>^ Give thanks to the God of gods,
For his loyal love endures forever.

[[v19-136-3]]

^<<v19-136-3,3>>^ Give thanks to the Lord of lords,
For his loyal love endures forever.

[[v19-136-4]]

^<<v19-136-4,4>>^ He alone does great wonders,
For his loyal love endures forever.

[[v19-136-5]]

^<<v19-136-5,5>>^ He skillfully made^&#42;1^ the heavens,
For his loyal love endures forever.

[NOTE]
====
. Or “made with understanding.”
====

[[v19-136-6]]

^<<v19-136-6,6>>^ He spread out the earth over the waters,
For his loyal love endures forever.

[[v19-136-7]]

^<<v19-136-7,7>>^ He made the great lights,
For his loyal love endures forever,

[[v19-136-8]]

^<<v19-136-8,8>>^ The sun to rule over the day,
For his loyal love endures forever,

[[v19-136-9]]

^<<v19-136-9,9>>^ The moon and the stars to rule over the night,
For his loyal love endures forever.

[[v19-136-10]]

^<<v19-136-10,10>>^ He struck down Egypt’s firstborn,
For his loyal love endures forever.

[[v19-136-11]]

^<<v19-136-11,11>>^ He brought Israel out from their midst,
For his loyal love endures forever,

[[v19-136-12]]

^<<v19-136-12,12>>^ With a mighty hand and an outstretched arm,
For his loyal love endures forever.

[[v19-136-13]]

^<<v19-136-13,13>>^ He split the Red Sea in two,^&#42;1^
For his loyal love endures forever.

[NOTE]
====
. Lit., “into pieces.”
====

[[v19-136-14]]

^<<v19-136-14,14>>^ He caused Israel to pass through the middle of it,
For his loyal love endures forever.

[[v19-136-15]]

^<<v19-136-15,15>>^ He shook off Pharʹaoh and his army into the Red Sea,
For his loyal love endures forever.

[[v19-136-16]]

^<<v19-136-16,16>>^ He led his people through the wilderness,
For his loyal love endures forever.

[[v19-136-17]]

^<<v19-136-17,17>>^ He struck down great kings,
For his loyal love endures forever.

[[v19-136-18]]

^<<v19-136-18,18>>^ He killed mighty kings,
For his loyal love endures forever,

[[v19-136-19]]

^<<v19-136-19,19>>^ Siʹhon the king of the Amʹor·ites,
For his loyal love endures forever,

[[v19-136-20]]

^<<v19-136-20,20>>^ And Og the king of Baʹshan,
For his loyal love endures forever.

[[v19-136-21]]

^<<v19-136-21,21>>^ He gave their land as an inheritance,
For his loyal love endures forever,

[[v19-136-22]]

^<<v19-136-22,22>>^ An inheritance to Israel his servant,
For his loyal love endures forever.

[[v19-136-23]]

^<<v19-136-23,23>>^ He remembered us when we were low,
For his loyal love endures forever.

[[v19-136-24]]

^<<v19-136-24,24>>^ He kept rescuing us from our adversaries,
For his loyal love endures forever.

[[v19-136-25]]

^<<v19-136-25,25>>^ He gives food to every living thing,^&#42;1^
For his loyal love endures forever.

[NOTE]
====
. Lit., “all flesh.”
====

[[v19-136-26]]

^<<v19-136-26,26>>^ Give thanks to the God of the heavens,
For his loyal love endures forever.

'''

xref:019-psalm/019-psalm-135.adoc#v19-135-0[&#60; Capítulo Anterior] | <<v19-136-0,Topo>> | xref:019-psalm/019-psalm-137.adoc#v19-137-0[Próximo Capítulo &#62;]