include::./index.adoc[]

[[v19-1-0]]
=== Psalm, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_BOOK ONE_

_(Psalms 1-41)_

[[v19-1-1]]

^<<v19-1-1,1>>^ Happy is the man who does not walk according to the advice of the wicked
And does not stand on the path of sinners
And does not sit in the seat of scoffers.

[[v19-1-2]]

^<<v19-1-2,2>>^ But his delight is in the law of Jehovah,
And he reads His law in an undertone^&#42;1^ day and night.

[NOTE]
====
. Or “he meditates on His law.”
====

[[v19-1-3]]

^<<v19-1-3,3>>^ He will be like a tree planted by streams of water,
A tree that produces fruit in its season,
The foliage of which does not wither.
And everything he does will succeed.

[[v19-1-4]]

^<<v19-1-4,4>>^ The wicked are not like that;
They are like the chaff that the wind blows away.

[[v19-1-5]]

^<<v19-1-5,5>>^ That is why the wicked will not remain standing in the judgment;
Nor will sinners remain standing in the assembly of the righteous.

[[v19-1-6]]

^<<v19-1-6,6>>^ For Jehovah is aware of the way of the righteous,
But the way of the wicked will perish.

'''

xref:018-job/018-job-042.adoc#v18-42-0[&#60; Capítulo Anterior] | <<v19-1-0,Topo>> | xref:019-psalm/019-psalm-002.adoc#v19-2-0[Próximo Capítulo &#62;]