include::./index.adoc[]

[[v19-119-0]]
=== Psalm, 119
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_א &#91;Aleph&#93;_

[[v19-119-1]]

^<<v19-119-1,1>>^ Happy are those who are blameless^&#42;1^ in their way,
Who walk in the law of Jehovah.

[NOTE]
====
. Or “who keep integrity.”
====

[[v19-119-2]]

^<<v19-119-2,2>>^ Happy are those who observe his reminders,
Who search for him with all their heart.

[[v19-119-3]]

^<<v19-119-3,3>>^ They practice no unrighteousness;
They walk in his ways.

[[v19-119-4]]

^<<v19-119-4,4>>^ You have commanded
That your orders be carefully kept.

[[v19-119-5]]

^<<v19-119-5,5>>^ If only I could remain steadfast^&#42;1^
So as to observe your regulations!

[NOTE]
====
. Lit., “O that my ways were firmly established.”
====

[[v19-119-6]]

^<<v19-119-6,6>>^ Then I would not be put to shame
When I consider all your commandments.

[[v19-119-7]]

^<<v19-119-7,7>>^ I will praise you with an upright heart
When I learn your righteous judgments.

[[v19-119-8]]

^<<v19-119-8,8>>^ I will observe your regulations.
May you never utterly forsake me.

_ב &#91;Beth&#93;_

[[v19-119-9]]

^<<v19-119-9,9>>^ How can a young man keep his path clean?
By keeping on guard according to your word.

[[v19-119-10]]

^<<v19-119-10,10>>^ With my whole heart I seek you.
Do not let me stray from your commandments.

[[v19-119-11]]

^<<v19-119-11,11>>^ In my heart I treasure up your saying
So that I may not sin against you.

[[v19-119-12]]

^<<v19-119-12,12>>^ May you be praised, O Jehovah;
Teach me your regulations.

[[v19-119-13]]

^<<v19-119-13,13>>^ With my lips I declare
All the judgments that you have spoken.

[[v19-119-14]]

^<<v19-119-14,14>>^ I rejoice over your reminders
More than over all other valuable things.

[[v19-119-15]]

^<<v19-119-15,15>>^ I will ponder over^&#42;1^ your orders
And keep my eyes on your paths.

[NOTE]
====
. Or “study.”
====

[[v19-119-16]]

^<<v19-119-16,16>>^ I am fond of your statutes.
I will not forget your word.

_ג &#91;Gimel&#93;_

[[v19-119-17]]

^<<v19-119-17,17>>^ Deal kindly with your servant,
So that I may live and observe your word.

[[v19-119-18]]

^<<v19-119-18,18>>^ Open my eyes so that I may see clearly
The wonderful things from your law.

[[v19-119-19]]

^<<v19-119-19,19>>^ I am but a foreigner in the land.
Do not hide your commandments from me.

[[v19-119-20]]

^<<v19-119-20,20>>^ I am^&#42;1^ consumed with longing
For your judgments at all times.

[NOTE]
====
. Or “My soul is.”
====

[[v19-119-21]]

^<<v19-119-21,21>>^ You rebuke the presumptuous,
The cursed ones who stray from your commandments.

[[v19-119-22]]

^<<v19-119-22,22>>^ Remove from me^&#42;1^ scorn and contempt,
For I have observed your reminders.

[NOTE]
====
. Lit., “Roll away from upon me.”
====

[[v19-119-23]]

^<<v19-119-23,23>>^ Even when princes sit together and speak against me,
Your servant ponders over^&#42;1^ your regulations.

[NOTE]
====
. Or “studies.”
====

[[v19-119-24]]

^<<v19-119-24,24>>^ I am fond of your reminders;
They are my advisers.

_ד &#91;Daleth&#93;_

[[v19-119-25]]

^<<v19-119-25,25>>^ I lie^&#42;1^ prostrate in the dust.
Preserve me alive according to your word.

[NOTE]
====
. Or “My soul lies.”
====

[[v19-119-26]]

^<<v19-119-26,26>>^ I told you of my ways, and you answered me;
Teach me your regulations.

[[v19-119-27]]

^<<v19-119-27,27>>^ Make me understand the meaning^&#42;1^ of your orders,
So that I may ponder over^&#42;2^ your wonderful works.

[NOTE]
====
. Lit., “way.”
. Or “study.”
====

[[v19-119-28]]

^<<v19-119-28,28>>^ I have^&#42;1^ been sleepless from grief.
Strengthen me according to your word.

[NOTE]
====
. Or “My soul has.”
====

[[v19-119-29]]

^<<v19-119-29,29>>^ Remove from me the way of deception,
And favor me with your law.

[[v19-119-30]]

^<<v19-119-30,30>>^ The way of faithfulness I have chosen.
I recognize that your judgments are right.

[[v19-119-31]]

^<<v19-119-31,31>>^ I cling to your reminders.
O Jehovah, do not let me be disappointed.^&#42;1^

[NOTE]
====
. Or “be put to shame.”
====

[[v19-119-32]]

^<<v19-119-32,32>>^ I will eagerly pursue^&#42;1^ the way of your commandments
Because you make room for it in my heart.^&#42;2^

[NOTE]
====
. Lit., “will run.”
. Or possibly, “you make my heart have the confidence.”
====

_ה &#91;He&#93;_

[[v19-119-33]]

^<<v19-119-33,33>>^ Teach me, O Jehovah, the way of your regulations,
And I will follow it to the end.

[[v19-119-34]]

^<<v19-119-34,34>>^ Give me understanding,
So that I may observe your law
And keep it with my whole heart.

[[v19-119-35]]

^<<v19-119-35,35>>^ Guide me^&#42;1^ in the pathway of your commandments,
For in it I take delight.

[NOTE]
====
. Or “Make me walk.”
====

[[v19-119-36]]

^<<v19-119-36,36>>^ Incline my heart to your reminders,
Not to selfish gain.^&#42;1^

[NOTE]
====
. Or “to profits.”
====

[[v19-119-37]]

^<<v19-119-37,37>>^ Turn my eyes away from looking at what is worthless;
Preserve me alive in your way.

[[v19-119-38]]

^<<v19-119-38,38>>^ Fulfill your promise^&#42;1^ to your servant,
So that you may be feared.^&#42;2^

[NOTE]
====
. Or “saying.”
. Or possibly, “Which is made to those who fear you.”
====

[[v19-119-39]]

^<<v19-119-39,39>>^ Remove the disgrace that I dread,
For your judgments are good.

[[v19-119-40]]

^<<v19-119-40,40>>^ See how I long for your orders.
Preserve me alive in your righteousness.

_ו &#91;Waw&#93;_

[[v19-119-41]]

^<<v19-119-41,41>>^ May I experience your loyal love, O Jehovah,
Your salvation in harmony with your promise;^&#42;1^

[NOTE]
====
. Or “saying.”
====

[[v19-119-42]]

^<<v19-119-42,42>>^ Then I will reply to the one taunting me,
For I put my trust in your word.

[[v19-119-43]]

^<<v19-119-43,43>>^ Do not utterly remove the word of truth from my mouth,
For I have hoped in^&#42;1^ your judgment.

[NOTE]
====
. Or “I wait for.”
====

[[v19-119-44]]

^<<v19-119-44,44>>^ I will keep your law constantly,
Forever and ever.

[[v19-119-45]]

^<<v19-119-45,45>>^ And I will walk about in a place of safety,^&#42;1^
For I search for your orders.

[NOTE]
====
. Or “a roomy place.”
====

[[v19-119-46]]

^<<v19-119-46,46>>^ I will speak about your reminders in front of kings,
And I will not be ashamed.

[[v19-119-47]]

^<<v19-119-47,47>>^ I am fond of your commandments,
Yes, I love them.

[[v19-119-48]]

^<<v19-119-48,48>>^ I will raise my hands to your commandments, which I love,
And I will ponder over^&#42;1^ your regulations.

[NOTE]
====
. Or “study.”
====

_ז &#91;Zayin&#93;_

[[v19-119-49]]

^<<v19-119-49,49>>^ Remember your word^&#42;1^ to your servant,
Through which you give me hope.^&#42;2^

[NOTE]
====
. Or “promise.”
. Or “For which you made me wait.”
====

[[v19-119-50]]

^<<v19-119-50,50>>^ This is my comfort in my affliction,
For your saying has preserved me alive.

[[v19-119-51]]

^<<v19-119-51,51>>^ The presumptuous utterly scorn me,
But I do not deviate from your law.

[[v19-119-52]]

^<<v19-119-52,52>>^ I remember your judgments from of old, O Jehovah,
And I find comfort in them.

[[v19-119-53]]

^<<v19-119-53,53>>^ I am seized with burning rage because of the wicked,
Who forsake your law.

[[v19-119-54]]

^<<v19-119-54,54>>^ Your regulations are songs to me
Wherever I dwell.^&#42;1^

[NOTE]
====
. Or “In the house where I dwell as a foreigner.”
====

[[v19-119-55]]

^<<v19-119-55,55>>^ During the night I remember your name, O Jehovah,
So that I may keep your law.

[[v19-119-56]]

^<<v19-119-56,56>>^ This has been my practice
Because I have observed your orders.

_ח &#91;Heth&#93;_

[[v19-119-57]]

^<<v19-119-57,57>>^ Jehovah is my portion;
I have promised to keep your words.

[[v19-119-58]]

^<<v19-119-58,58>>^ I appeal to you^&#42;1^ with all my heart;
Show me favor according to your promise.^&#42;2^

[NOTE]
====
. Or “I soften (seek the smile of) your face.”
. Or “saying.”
====

[[v19-119-59]]

^<<v19-119-59,59>>^ I have examined my ways,
In order to turn my feet back to your reminders.

[[v19-119-60]]

^<<v19-119-60,60>>^ I hurry and do not delay
To keep your commandments.

[[v19-119-61]]

^<<v19-119-61,61>>^ The ropes of the wicked surround me,
But your law I do not forget.

[[v19-119-62]]

^<<v19-119-62,62>>^ At midnight I get up to give you thanks
For your righteous judgments.

[[v19-119-63]]

^<<v19-119-63,63>>^ I am a friend of all who fear you
And of those who keep your orders.

[[v19-119-64]]

^<<v19-119-64,64>>^ Your loyal love, O Jehovah, fills the earth;
Teach me your regulations.

_ט &#91;Teth&#93;_

[[v19-119-65]]

^<<v19-119-65,65>>^ You have dealt well with your servant,
O Jehovah, according to your word.

[[v19-119-66]]

^<<v19-119-66,66>>^ Teach me good sense and knowledge,
For I have put my trust in your commandments.

[[v19-119-67]]

^<<v19-119-67,67>>^ Before I was afflicted, I used to go astray,^&#42;1^
But now I keep your saying.

[NOTE]
====
. Or “I was sinning by mistake.”
====

[[v19-119-68]]

^<<v19-119-68,68>>^ You are good and your works are good.
Teach me your regulations.

[[v19-119-69]]

^<<v19-119-69,69>>^ The presumptuous smear me with lies,
But I observe your orders with all my heart.

[[v19-119-70]]

^<<v19-119-70,70>>^ Their heart is insensitive,^&#42;1^
But I am fond of your law.

[NOTE]
====
. Lit., “unfeeling, like fat.”
====

[[v19-119-71]]

^<<v19-119-71,71>>^ It is good that I have been afflicted,
So that I may learn your regulations.

[[v19-119-72]]

^<<v19-119-72,72>>^ The law that you have proclaimed is good for me,
More so than thousands of pieces of gold and silver.

_י &#91;Yod&#93;_

[[v19-119-73]]

^<<v19-119-73,73>>^ Your hands made me and formed me.
Give me understanding,
So that I may learn your commandments.

[[v19-119-74]]

^<<v19-119-74,74>>^ Those who fear you see me and rejoice,
For your word is my hope.^&#42;1^

[NOTE]
====
. Or “I wait for your word.”
====

[[v19-119-75]]

^<<v19-119-75,75>>^ I know, O Jehovah, that your judgments are righteous
And that you have afflicted me in your faithfulness.

[[v19-119-76]]

^<<v19-119-76,76>>^ May your loyal love please comfort me,
According to the promise^&#42;1^ you made to your servant.

[NOTE]
====
. Or “saying.”
====

[[v19-119-77]]

^<<v19-119-77,77>>^ Show me mercy, so that I may keep living,
For I am fond of your law.

[[v19-119-78]]

^<<v19-119-78,78>>^ May the presumptuous be put to shame,
For they wrong me without cause.^&#42;1^
But I will ponder over^&#42;2^ your orders.

[NOTE]
====
. Or possibly, “with lies.”
. Or “study.”
====

[[v19-119-79]]

^<<v19-119-79,79>>^ Let those who fear you return to me,
Those who know your reminders.

[[v19-119-80]]

^<<v19-119-80,80>>^ May my heart be blameless in following your regulations,
So that I may not be put to shame.

_כ &#91;Kaph&#93;_

[[v19-119-81]]

^<<v19-119-81,81>>^ I long for^&#42;1^ your salvation,
For your word is my hope.^&#42;2^

[NOTE]
====
. Or “My soul pines for.”
. Or “I wait for your word.”
====

[[v19-119-82]]

^<<v19-119-82,82>>^ My eyes long for your saying
While I say: “When will you comfort me?”

[[v19-119-83]]

^<<v19-119-83,83>>^ For I am like a skin bottle dried up in the smoke,
But your regulations I do not forget.

[[v19-119-84]]

^<<v19-119-84,84>>^ How many days must your servant wait?
When will you bring judgment against those persecuting me?

[[v19-119-85]]

^<<v19-119-85,85>>^ The presumptuous dig pits for me,
Those who defy your law.

[[v19-119-86]]

^<<v19-119-86,86>>^ All your commandments are trustworthy.
Men persecute me without cause; help me!

[[v19-119-87]]

^<<v19-119-87,87>>^ They almost exterminated me from the earth,
But I did not abandon your orders.

[[v19-119-88]]

^<<v19-119-88,88>>^ Preserve me alive because of your loyal love,
So that I may keep the reminders you have spoken.

_ל &#91;Lamed&#93;_

[[v19-119-89]]

^<<v19-119-89,89>>^ Forever, O Jehovah,
Your word will remain in the heavens.

[[v19-119-90]]

^<<v19-119-90,90>>^ Your faithfulness is through all generations.
You have firmly established the earth, so that it continues to stand.

[[v19-119-91]]

^<<v19-119-91,91>>^ By your judgments they^&#42;1^ remain until today,
For they are all your servants.

[NOTE]
====
. That is, all his creative works.
====

[[v19-119-92]]

^<<v19-119-92,92>>^ If I had not been fond of your law,
I would have perished in my affliction.

[[v19-119-93]]

^<<v19-119-93,93>>^ I will never forget your orders,
Because by them you have preserved me alive.

[[v19-119-94]]

^<<v19-119-94,94>>^ I belong to you; save me,
Because I have searched for your orders.

[[v19-119-95]]

^<<v19-119-95,95>>^ The wicked wait to destroy me,
But I give close attention to your reminders.

[[v19-119-96]]

^<<v19-119-96,96>>^ I have seen a limit to all perfection,
But your commandment has no limit.^&#42;1^

[NOTE]
====
. Lit., “is very broad.”
====

_מ &#91;Mem&#93;_

[[v19-119-97]]

^<<v19-119-97,97>>^ How I do love your law!
I ponder over^&#42;1^ it all day long.

[NOTE]
====
. Or “study.”
====

[[v19-119-98]]

^<<v19-119-98,98>>^ Your commandment makes me wiser than my enemies,
Because it is with me forever.

[[v19-119-99]]

^<<v19-119-99,99>>^ I have more insight than all my teachers,
Because I ponder over^&#42;1^ your reminders.

[NOTE]
====
. Or “study.”
====

[[v19-119-100]]

^<<v19-119-100,100>>^ I act with more understanding than older men,
Because I observe your orders.

[[v19-119-101]]

^<<v19-119-101,101>>^ I refuse to walk on any evil path,
So that I may keep your word.

[[v19-119-102]]

^<<v19-119-102,102>>^ I do not turn aside from your judgments,
For you have instructed me.

[[v19-119-103]]

^<<v19-119-103,103>>^ How sweet your sayings are to my palate,
More so than honey to my mouth!

[[v19-119-104]]

^<<v19-119-104,104>>^ By your orders I act with understanding.
That is why I hate every false path.

_נ &#91;Nun&#93;_

[[v19-119-105]]

^<<v19-119-105,105>>^ Your word is a lamp to my foot,
And a light for my path.

[[v19-119-106]]

^<<v19-119-106,106>>^ I have sworn an oath, and I will carry it out,
To observe your righteous judgments.

[[v19-119-107]]

^<<v19-119-107,107>>^ I have been greatly afflicted.
O Jehovah, preserve me alive according to your word.

[[v19-119-108]]

^<<v19-119-108,108>>^ Please take pleasure in my voluntary offerings of praise,^&#42;1^ O Jehovah,
And teach me your judgments.

[NOTE]
====
. Lit., “the voluntary offerings of my mouth.”
====

[[v19-119-109]]

^<<v19-119-109,109>>^ My life is in constant danger,^&#42;1^
But I have not forgotten your law.

[NOTE]
====
. Or “My soul is in my hand constantly.”
====

[[v19-119-110]]

^<<v19-119-110,110>>^ The wicked have set a trap for me,
But I have not strayed from your orders.

[[v19-119-111]]

^<<v19-119-111,111>>^ I take your reminders as my permanent possession,^&#42;1^
For they are the joy of my heart.

[NOTE]
====
. Or “my eternal heritage.”
====

[[v19-119-112]]

^<<v19-119-112,112>>^ I have resolved^&#42;1^ to obey your regulations
At all times, down to the last.

[NOTE]
====
. Lit., “have inclined my heart.”
====

_ס &#91;Samekh&#93;_

[[v19-119-113]]

^<<v19-119-113,113>>^ I hate the halfhearted ones,^&#42;1^
But I love your law.

[NOTE]
====
. Or “men of divided heart.”
====

[[v19-119-114]]

^<<v19-119-114,114>>^ You are my shelter and my shield,
For your word is my hope.^&#42;1^

[NOTE]
====
. Or “I wait for your word.”
====

[[v19-119-115]]

^<<v19-119-115,115>>^ Stay away from me, you evil men,
So that I may observe the commandments of my God.

[[v19-119-116]]

^<<v19-119-116,116>>^ Support me as you promised,^&#42;1^
So that I may keep living;
Do not let my hope turn into disappointment.^&#42;2^

[NOTE]
====
. Or “according to your saying.”
. Or “be put to shame.”
====

[[v19-119-117]]

^<<v19-119-117,117>>^ Support me that I may be saved;
Then I will always concentrate on your regulations.

[[v19-119-118]]

^<<v19-119-118,118>>^ You reject all those who stray from your regulations,
For they are false and deceitful.

[[v19-119-119]]

^<<v19-119-119,119>>^ You discard all the wicked of the earth as if they were worthless dross.
That is why I love your reminders.

[[v19-119-120]]

^<<v19-119-120,120>>^ The dread of you makes my body^&#42;1^ tremble;
I am in fear of your judgments.

[NOTE]
====
. Lit., “flesh.”
====

_ע &#91;Ayin&#93;_

[[v19-119-121]]

^<<v19-119-121,121>>^ I have done what is just and righteous.
Do not abandon me to my oppressors!

[[v19-119-122]]

^<<v19-119-122,122>>^ Guarantee the welfare of your servant;
May the presumptuous not oppress me.

[[v19-119-123]]

^<<v19-119-123,123>>^ My eyes have grown weary waiting for your salvation
And for your righteous promise.^&#42;1^

[NOTE]
====
. Or “saying.”
====

[[v19-119-124]]

^<<v19-119-124,124>>^ Show your loyal love to your servant,
And teach me your regulations.

[[v19-119-125]]

^<<v19-119-125,125>>^ I am your servant; give me understanding,
So that I may know your reminders.

[[v19-119-126]]

^<<v19-119-126,126>>^ The time has come for Jehovah to act,
For they have broken your law.

[[v19-119-127]]

^<<v19-119-127,127>>^ That is why I love your commandments
More than gold, even fine^&#42;1^ gold.

[NOTE]
====
. Or “refined.”
====

[[v19-119-128]]

^<<v19-119-128,128>>^ Therefore, I consider every instruction^&#42;1^ from you to be right;
I hate every false path.

[NOTE]
====
. Or “order.”
====

_פ &#91;Pe&#93;_

[[v19-119-129]]

^<<v19-119-129,129>>^ Your reminders are wonderful.
That is why I observe^&#42;1^ them.

[NOTE]
====
. Or “my soul observes.”
====

[[v19-119-130]]

^<<v19-119-130,130>>^ The disclosure of your words brings light,
Giving understanding to the inexperienced.

[[v19-119-131]]

^<<v19-119-131,131>>^ I open my mouth wide and sigh,^&#42;1^
Because I long for your commandments.

[NOTE]
====
. Lit., “pant.”
====

[[v19-119-132]]

^<<v19-119-132,132>>^ Turn to me and show me favor,
In keeping with your judgment toward those loving your name.

[[v19-119-133]]

^<<v19-119-133,133>>^ Guide my steps safely^&#42;1^ by your saying;
May nothing wicked dominate me.

[NOTE]
====
. Or “Make my steps steady.”
====

[[v19-119-134]]

^<<v19-119-134,134>>^ Rescue^&#42;1^ me from oppressive men,
And I will keep your orders.

[NOTE]
====
. Lit., “Redeem.”
====

[[v19-119-135]]

^<<v19-119-135,135>>^ Make your face shine^&#42;1^ upon your servant,
And teach me your regulations.

[NOTE]
====
. Or “smile.”
====

[[v19-119-136]]

^<<v19-119-136,136>>^ Tears stream down from my eyes
Because people do not keep your law.

_צ &#91;Tsade&#93;_

[[v19-119-137]]

^<<v19-119-137,137>>^ You are righteous, O Jehovah,
And your judgments are fair.

[[v19-119-138]]

^<<v19-119-138,138>>^ The reminders you give are righteous
And completely reliable.

[[v19-119-139]]

^<<v19-119-139,139>>^ My zeal consumes me,
Because my adversaries have forgotten your words.

[[v19-119-140]]

^<<v19-119-140,140>>^ Your saying is thoroughly refined,
And your servant loves it.

[[v19-119-141]]

^<<v19-119-141,141>>^ I am insignificant and despised;
Yet, I have not forgotten your orders.

[[v19-119-142]]

^<<v19-119-142,142>>^ Your righteousness is an eternal righteousness,
And your law is truth.

[[v19-119-143]]

^<<v19-119-143,143>>^ Though distress and difficulty come upon me,
I remain fond of your commandments.

[[v19-119-144]]

^<<v19-119-144,144>>^ The righteousness of your reminders is eternal.
Give me understanding, so that I may keep living.

_ק &#91;Qoph&#93;_

[[v19-119-145]]

^<<v19-119-145,145>>^ I call with my whole heart. Answer me, O Jehovah.
Your regulations I will observe.

[[v19-119-146]]

^<<v19-119-146,146>>^ I call on you; save me!
I will keep your reminders.

[[v19-119-147]]

^<<v19-119-147,147>>^ I have been awake before dawn^&#42;1^ to cry for help,
For your words are my hope.^&#42;2^

[NOTE]
====
. Or “in the morning twilight.”
. Or “I wait for your words.”
====

[[v19-119-148]]

^<<v19-119-148,148>>^ My eyes open before the night watches,
So that I can ponder over^&#42;1^ your saying.

[NOTE]
====
. Or “study.”
====

[[v19-119-149]]

^<<v19-119-149,149>>^ Do listen to my voice because of your loyal love.
O Jehovah, preserve me alive according to your justice.

[[v19-119-150]]

^<<v19-119-150,150>>^ Those who engage in shameful conduct^&#42;1^ come near;
They are far away from your law.

[NOTE]
====
. Or “in obscene conduct.”
====

[[v19-119-151]]

^<<v19-119-151,151>>^ You are near, O Jehovah,
And all your commandments are truth.

[[v19-119-152]]

^<<v19-119-152,152>>^ Long ago I learned about your reminders,
That you have established them to last forever.

_ר &#91;Resh&#93;_

[[v19-119-153]]

^<<v19-119-153,153>>^ Look on my affliction and rescue me,
For I have not forgotten your law.

[[v19-119-154]]

^<<v19-119-154,154>>^ Defend me^&#42;1^ and rescue me;
Preserve me alive in harmony with your promise.^&#42;2^

[NOTE]
====
. Or “Conduct my legal case.”
. Or “saying.”
====

[[v19-119-155]]

^<<v19-119-155,155>>^ Salvation is far away from the wicked,
For they have not searched for your regulations.

[[v19-119-156]]

^<<v19-119-156,156>>^ Your mercy is great, O Jehovah.
Preserve me alive in harmony with your justice.

[[v19-119-157]]

^<<v19-119-157,157>>^ My persecutors and my adversaries are many;
But I have not deviated from your reminders.

[[v19-119-158]]

^<<v19-119-158,158>>^ I look on the treacherous with loathing,
Because they do not keep your saying.

[[v19-119-159]]

^<<v19-119-159,159>>^ See how I love your orders!
O Jehovah, preserve me alive because of your loyal love.

[[v19-119-160]]

^<<v19-119-160,160>>^ The very essence of your word is truth,
And all your righteous judgments endure forever.

_ש &#91;Sin&#93; or &#91;Shin&#93;_

[[v19-119-161]]

^<<v19-119-161,161>>^ Princes persecute me for no cause,
But my heart stands in awe of your words.

[[v19-119-162]]

^<<v19-119-162,162>>^ I rejoice over your saying
Like someone who finds great spoil.

[[v19-119-163]]

^<<v19-119-163,163>>^ I hate falsehood—I detest it—
I love your law.

[[v19-119-164]]

^<<v19-119-164,164>>^ Seven times a day I praise you
Because of your righteous judgments.

[[v19-119-165]]

^<<v19-119-165,165>>^ Abundant peace belongs to those who love your law;
Nothing can make them stumble.^&#42;1^

[NOTE]
====
. Or “For them there is no stumbling block.”
====

[[v19-119-166]]

^<<v19-119-166,166>>^ I hope for your acts of salvation, O Jehovah,
And I observe your commandments.

[[v19-119-167]]

^<<v19-119-167,167>>^ I keep^&#42;1^ your reminders,
And I love them dearly.

[NOTE]
====
. Or “My soul keeps.”
====

[[v19-119-168]]

^<<v19-119-168,168>>^ I observe your orders and your reminders,
For you are aware of all that I do.

_ת &#91;Taw&#93;_

[[v19-119-169]]

^<<v19-119-169,169>>^ May my cry for help reach you, O Jehovah.
According to your word, make me understand.

[[v19-119-170]]

^<<v19-119-170,170>>^ May my request for favor come before you.
Save me, as you have promised.^&#42;1^

[NOTE]
====
. Or “according to your saying.”
====

[[v19-119-171]]

^<<v19-119-171,171>>^ May my lips overflow with praise,
For you teach me your regulations.

[[v19-119-172]]

^<<v19-119-172,172>>^ May my tongue sing about your saying,
For all your commandments are righteous.

[[v19-119-173]]

^<<v19-119-173,173>>^ May your hand be ready to help me,
Because I choose to obey your orders.

[[v19-119-174]]

^<<v19-119-174,174>>^ I long for your salvation, O Jehovah,
And I am fond of your law.

[[v19-119-175]]

^<<v19-119-175,175>>^ Let me^&#42;1^ live so that I may praise you;
May your judgments be my help.

[NOTE]
====
. Or “my soul.”
====

[[v19-119-176]]

^<<v19-119-176,176>>^ I have strayed like a lost sheep. Search for your servant,
For I have not forgotten your commandments.

'''

xref:019-psalm/019-psalm-118.adoc#v19-118-0[&#60; Capítulo Anterior] | <<v19-119-0,Topo>> | xref:019-psalm/019-psalm-120.adoc#v19-120-0[Próximo Capítulo &#62;]