include::./index.adoc[]

[[v2-14-0]]
=== Exodus, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-14-1]]

^<<v2-14-1,1>>^ Jehovah now said to Moses:

[[v2-14-2]]

^<<v2-14-2,2>>^ “Tell the Israelites that they should turn back and encamp before Pi·ha·hiʹroth, between Migʹdol and the sea, within view of Baʹal-zeʹphon. You are to encamp facing it by the sea.

[[v2-14-3]]

^<<v2-14-3,3>>^ Then Pharʹaoh will say about the Israelites, ‘They are wandering in confusion in the land. The wilderness has closed in on them.’

[[v2-14-4]]

^<<v2-14-4,4>>^ I will allow Pharʹaoh’s heart to become obstinate, and he will chase after them, and I will glorify myself by means of Pharʹaoh and all his army; and the Egyptians will certainly know that I am Jehovah.” So that is what they did.

[[v2-14-5]]

^<<v2-14-5,5>>^ Later it was reported to the king of Egypt that the people had run away. Immediately, Pharʹaoh and his servants had a change of heart regarding the people, and they said: “Why did we do this and release Israel from serving as slaves for us?”

[[v2-14-6]]

^<<v2-14-6,6>>^ So he made his war chariots ready, and he took his people with him.

[[v2-14-7]]

^<<v2-14-7,7>>^ He took 600 chosen chariots and all the other chariots of Egypt, with warriors on every one of them.

[[v2-14-8]]

^<<v2-14-8,8>>^ Thus Jehovah allowed the heart of Pharʹaoh king of Egypt to become obstinate, and he chased after the Israelites, while the Israelites were going out with confidence.^&#42;1^

[NOTE]
====
. Lit., “with uplifted hand.”
====

[[v2-14-9]]

^<<v2-14-9,9>>^ The Egyptians chased after them, and all the chariot horses of Pharʹaoh and his cavalrymen and his army were catching up with them while they were camping by the sea, by Pi·ha·hiʹroth, facing Baʹal-zeʹphon.

[[v2-14-10]]

^<<v2-14-10,10>>^ When Pharʹaoh got closer, the Israelites raised their eyes and saw the Egyptians pursuing them. The Israelites became terrified and began to cry out to Jehovah.

[[v2-14-11]]

^<<v2-14-11,11>>^ They said to Moses: “Is it because there are no burial places in Egypt that you have brought us here to die in the wilderness? What have you done to us by leading us out of Egypt?

[[v2-14-12]]

^<<v2-14-12,12>>^ Is this not the very thing we told you in Egypt when we said, ‘Let us alone, so that we may serve the Egyptians’? For it is better for us to serve the Egyptians than to die in the wilderness.”

[[v2-14-13]]

^<<v2-14-13,13>>^ Then Moses said to the people: “Do not be afraid. Stand firm and see the salvation of Jehovah that he will perform for you today. For the Egyptians whom you see today, you will never ever see again.

[[v2-14-14]]

^<<v2-14-14,14>>^ Jehovah himself will fight for you, and you will keep silent.”

[[v2-14-15]]

^<<v2-14-15,15>>^ Jehovah now said to Moses: “Why do you keep crying out to me? Tell the Israelites that they should break camp.

[[v2-14-16]]

^<<v2-14-16,16>>^ As for you, lift up your rod and stretch out your hand over the sea and divide it, so that the Israelites may go through the midst of the sea on dry ground.

[[v2-14-17]]

^<<v2-14-17,17>>^ As for me, I am allowing the hearts of the Egyptians to become obstinate, so that they will go in after them; thus I will glorify myself by means of Pharʹaoh and all his army, his war chariots, and his cavalrymen.

[[v2-14-18]]

^<<v2-14-18,18>>^ And the Egyptians will certainly know that I am Jehovah when I glorify myself by means of Pharʹaoh, his war chariots, and his cavalrymen.”

[[v2-14-19]]

^<<v2-14-19,19>>^ Then the angel of the true God who was going ahead of the camp of Israel departed and went to their rear, and the pillar of cloud that was in front of them moved to the rear and stood behind them.

[[v2-14-20]]

^<<v2-14-20,20>>^ So it came between the camp of the Egyptians and the camp of Israel. On the one side, it was a dark cloud. On the other side, it was lighting up the night. So the one camp did not come near the other camp all night long.

[[v2-14-21]]

^<<v2-14-21,21>>^ Moses now stretched out his hand over the sea; and Jehovah drove the sea back with a strong east wind all night long, turning the sea basin into dry ground, and the waters divided.

[[v2-14-22]]

^<<v2-14-22,22>>^ So the Israelites went through the midst of the sea on dry ground, while the waters formed a wall on their right hand and on their left.

[[v2-14-23]]

^<<v2-14-23,23>>^ The Egyptians pursued them, and all Pharʹaoh’s horses, his war chariots, and his cavalrymen began going after them into the midst of the sea.

[[v2-14-24]]

^<<v2-14-24,24>>^ During the morning watch,^&#42;1^ Jehovah looked at the camp of the Egyptians from within the pillar of fire and cloud, and he threw the camp of the Egyptians into confusion.

[NOTE]
====
. That is, about 2:00 a.m. until 6:00 a.m.
====

[[v2-14-25]]

^<<v2-14-25,25>>^ He kept taking wheels off their chariots so that they were driving them with difficulty, and the Egyptians were saying: “Let us flee from any contact with Israel, because Jehovah is fighting for them against the Egyptians.”

[[v2-14-26]]

^<<v2-14-26,26>>^ Then Jehovah said to Moses: “Stretch out your hand over the sea so that the waters may come back over the Egyptians, their war chariots, and their cavalrymen.”

[[v2-14-27]]

^<<v2-14-27,27>>^ Moses at once stretched out his hand over the sea, and as morning approached, the sea returned to its normal condition. As the Egyptians fled from it, Jehovah shook the Egyptians off into the midst of the sea.

[[v2-14-28]]

^<<v2-14-28,28>>^ The returning waters covered the war chariots and the cavalrymen and all of Pharʹaoh’s army who had gone into the sea after them. Not so much as one among them was allowed to survive.

[[v2-14-29]]

^<<v2-14-29,29>>^ But the Israelites walked on dry ground in the midst of the seabed, and the waters formed a wall on their right hand and on their left.

[[v2-14-30]]

^<<v2-14-30,30>>^ Thus Jehovah saved Israel on that day from the hand of the Egyptians, and Israel saw the Egyptians dead on the seashore.

[[v2-14-31]]

^<<v2-14-31,31>>^ Israel also saw the great power^&#42;1^ that Jehovah wielded against the Egyptians, and the people began to fear Jehovah and to put faith in Jehovah and in his servant Moses.

[NOTE]
====
. Lit., “hand.”
====

'''

xref:002-exodus/002-exodus-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodus/002-exodus-015.adoc#v2-15-0[Próximo Capítulo &#62;]