include::./index.adoc[]

[[v2-4-0]]
=== Exodus, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-4-1]]

^<<v2-4-1,1>>^ However, Moses answered: “But suppose they do not believe me and do not listen to my voice, for they will say, ‘Jehovah did not appear to you.’”

[[v2-4-2]]

^<<v2-4-2,2>>^ Then Jehovah said to him: “What is that in your hand?” He answered: “A rod.”

[[v2-4-3]]

^<<v2-4-3,3>>^ He said: “Throw it on the ground.” So he threw it on the ground, and it became a serpent; and Moses fled from it.

[[v2-4-4]]

^<<v2-4-4,4>>^ Jehovah now said to Moses: “Reach out your hand and seize it by the tail.” So he reached out and seized it, and it became a rod in his hand.

[[v2-4-5]]

^<<v2-4-5,5>>^ God then said: “This is so that they may believe that Jehovah the God of their forefathers, the God of Abraham, the God of Isaac, and the God of Jacob, has appeared to you.”

[[v2-4-6]]

^<<v2-4-6,6>>^ Jehovah said to him once more: “Put your hand, please, into the upper fold of your garment.” So he put his hand into the fold of his garment. When he drew it out, why, his hand was stricken with leprosy like snow!

[[v2-4-7]]

^<<v2-4-7,7>>^ Then he said: “Return your hand into the upper fold of your garment.” So he returned his hand into his garment. When he drew it out of the garment, it was restored like the rest of his flesh!

[[v2-4-8]]

^<<v2-4-8,8>>^ He said: “If they will not believe you or pay attention to the first sign, then they will certainly heed the next sign.

[[v2-4-9]]

^<<v2-4-9,9>>^ Still, even if they will not believe these two signs and refuse to listen to your voice, you will take some water from the Nile River and pour it out on the dry land, and the water that you take from the Nile will become blood on the dry land.”

[[v2-4-10]]

^<<v2-4-10,10>>^ Moses now said to Jehovah: “Pardon me, Jehovah, but I have never been a fluent speaker, neither in the past nor since you have spoken to your servant, for I am slow of speech^&#42;1^ and slow of tongue.”

[NOTE]
====
. Lit., “heavy of mouth.”
====

[[v2-4-11]]

^<<v2-4-11,11>>^ Jehovah said to him: “Who made a mouth for man, or who makes them speechless, deaf, clear-sighted, or blind? Is it not I, Jehovah?

[[v2-4-12]]

^<<v2-4-12,12>>^ So go now, and I will be with you as you speak,^&#42;1^ and I will teach you what you should say.”

[NOTE]
====
. Lit., “with your mouth.”
====

[[v2-4-13]]

^<<v2-4-13,13>>^ But he said: “Pardon me, Jehovah, please send anyone whom you want to send.”

[[v2-4-14]]

^<<v2-4-14,14>>^ Then Jehovah’s anger blazed against Moses, and he said: “What about your brother Aaron the Levite? I know that he can speak very well. And he is now on his way here to meet you. When he sees you, his heart will rejoice.

[[v2-4-15]]

^<<v2-4-15,15>>^ So you must speak to him and put the words in his mouth, and I will be with you and him as you speak, and I will teach you men what to do.

[[v2-4-16]]

^<<v2-4-16,16>>^ He will speak for you to the people, and he will be your spokesman, and you will serve as God to him.^&#42;1^

[NOTE]
====
. Or “will be representing God to him.”
====

[[v2-4-17]]

^<<v2-4-17,17>>^ And you will take this rod in your hand and perform the signs with it.”

[[v2-4-18]]

^<<v2-4-18,18>>^ So Moses went back to Jethʹro his father-in-law and said to him: “I want to go, please, and return to my brothers who are in Egypt to see whether they are still alive.” Jethʹro said to Moses: “Go in peace.”

[[v2-4-19]]

^<<v2-4-19,19>>^ After that Jehovah said to Moses in Midʹi·an: “Go, return to Egypt, because all the men who were seeking to kill you^&#42;1^ are dead.”

[NOTE]
====
. Or “seeking your soul.”
====

[[v2-4-20]]

^<<v2-4-20,20>>^ Then Moses took his wife and his sons and lifted them onto a donkey, and he started back to the land of Egypt. Moreover, Moses took the rod of the true God in his hand.

[[v2-4-21]]

^<<v2-4-21,21>>^ Then Jehovah said to Moses: “After you have returned to Egypt, see that you perform before Pharʹaoh all the miracles that I have empowered you to do. But I will allow his heart to become obstinate, and he will not send the people away.

[[v2-4-22]]

^<<v2-4-22,22>>^ You must say to Pharʹaoh, ‘This is what Jehovah says: “Israel is my son, my firstborn.

[[v2-4-23]]

^<<v2-4-23,23>>^ I say to you, Send my son away so that he may serve me. But if you refuse to send him away, I am going to kill your son, your firstborn.”’”

[[v2-4-24]]

^<<v2-4-24,24>>^ Now on the road at the lodging place, Jehovah met him and was seeking to put him to death.

[[v2-4-25]]

^<<v2-4-25,25>>^ Finally Zip·poʹrah took a flint^&#42;1^ and circumcised her son and caused his foreskin to touch his feet and said: “It is because you are a bridegroom of blood to me.”

[NOTE]
====
. Or “flint knife.”
====

[[v2-4-26]]

^<<v2-4-26,26>>^ So He let him go. At that time she said, “a bridegroom of blood,” because of the circumcision.

[[v2-4-27]]

^<<v2-4-27,27>>^ Then Jehovah said to Aaron: “Go into the wilderness to meet Moses.” So he went and met him at the mountain of the true God and greeted him with a kiss.

[[v2-4-28]]

^<<v2-4-28,28>>^ And Moses told Aaron all the words of Jehovah, who had sent him, and all the signs that He had commanded him to do.

[[v2-4-29]]

^<<v2-4-29,29>>^ After that Moses and Aaron went and gathered all the elders of the Israelites.

[[v2-4-30]]

^<<v2-4-30,30>>^ Aaron told them all the words that Jehovah had spoken to Moses, and he performed the signs before the eyes of the people.

[[v2-4-31]]

^<<v2-4-31,31>>^ At this the people believed. When they heard that Jehovah had turned his attention to the Israelites and that he had seen their affliction, they bowed down and prostrated themselves.

'''

xref:002-exodus/002-exodus-003.adoc#v2-3-0[&#60; Capítulo Anterior] | <<v2-4-0,Topo>> | xref:002-exodus/002-exodus-005.adoc#v2-5-0[Próximo Capítulo &#62;]