include::./index.adoc[]

[[v2-10-0]]
=== Exodus, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-10-1]]

^<<v2-10-1,1>>^ Then Jehovah said to Moses: “Go in to Pharʹaoh, for I have allowed his heart and the hearts of his servants to become unresponsive, so that I may display these signs of mine right before him,

[[v2-10-2]]

^<<v2-10-2,2>>^ and in order that you may declare to your sons and your grandsons how severely I have dealt with Egypt and what signs I have performed among them; and you will certainly know that I am Jehovah.”

[[v2-10-3]]

^<<v2-10-3,3>>^ So Moses and Aaron went in to Pharʹaoh and said to him: “This is what Jehovah the God of the Hebrews has said, ‘How long will you refuse to submit to me? Send my people away so that they may serve me.

[[v2-10-4]]

^<<v2-10-4,4>>^ For if you keep refusing to send my people away, here I am bringing locusts within your boundaries tomorrow.

[[v2-10-5]]

^<<v2-10-5,5>>^ And they will cover the surface of the earth, and it will not be possible to see the ground. They will eat up what escaped the hail and was left for you, and they will eat all your trees that are growing in the field.

[[v2-10-6]]

^<<v2-10-6,6>>^ They will fill your houses, the houses of all your servants, and the houses of all Egypt to an extent that your fathers and your grandfathers never saw from the time they have been in this land until today.’” With that he turned and went out from Pharʹaoh.

[[v2-10-7]]

^<<v2-10-7,7>>^ Then Pharʹaoh’s servants said to him: “How long will this man continue to menace^&#42;1^ us? Send the men away so that they may serve Jehovah their God. Do you not yet realize that Egypt has been ruined?”

[NOTE]
====
. Lit., “be a snare to.”
====

[[v2-10-8]]

^<<v2-10-8,8>>^ So Moses and Aaron were brought back to Pharʹaoh, and he said to them: “Go, serve Jehovah your God. But just who will be going?”

[[v2-10-9]]

^<<v2-10-9,9>>^ Then Moses said: “We will go with our young people, our old people, our sons, our daughters, our sheep, and our cattle, because we will hold a festival to Jehovah.”

[[v2-10-10]]

^<<v2-10-10,10>>^ He said to them: “If I ever send you and your children away, then Jehovah is indeed with you! It is clear that you intend to do something evil.

[[v2-10-11]]

^<<v2-10-11,11>>^ No! Only your men may go and serve Jehovah, for that is what you requested.” With that they were driven out from before Pharʹaoh.

[[v2-10-12]]

^<<v2-10-12,12>>^ Jehovah now said to Moses: “Stretch out your hand over the land of Egypt for the locusts, so that they may come up over the land of Egypt and eat up all the vegetation of the land, everything that the hail has let remain.”

[[v2-10-13]]

^<<v2-10-13,13>>^ At once Moses stretched out his rod over the land of Egypt, and Jehovah caused an east wind to blow on the land all that day and all night. The morning came, and the east wind brought the locusts.

[[v2-10-14]]

^<<v2-10-14,14>>^ And the locusts came up over all the land of Egypt and settled down on the whole territory of Egypt. It was extremely severe; never before had there been so many locusts, nor would there ever be so many again.

[[v2-10-15]]

^<<v2-10-15,15>>^ They covered the surface of the entire land, and the land grew dark with them; they devoured all the vegetation of the land and all the fruit of the trees that the hail had left; nothing green was left on the trees or on the vegetation of the field in all the land of Egypt.

[[v2-10-16]]

^<<v2-10-16,16>>^ So Pharʹaoh quickly called Moses and Aaron and said: “I have sinned against Jehovah your God and against you.

[[v2-10-17]]

^<<v2-10-17,17>>^ Now, please, pardon my sin just this once, and plead with Jehovah your God that he just remove this deadly plague from upon me.”

[[v2-10-18]]

^<<v2-10-18,18>>^ So he^&#42;1^ went out from Pharʹaoh and pleaded with Jehovah.

[NOTE]
====
. Apparently Moses.
====

[[v2-10-19]]

^<<v2-10-19,19>>^ Then Jehovah caused the wind to shift, and it became a very stiff west wind, and it carried the locusts away and drove them into the Red Sea. Not a single locust remained in all the territory of Egypt.

[[v2-10-20]]

^<<v2-10-20,20>>^ However, Jehovah allowed Pharʹaoh’s heart to become obstinate, and he did not send the Israelites away.

[[v2-10-21]]

^<<v2-10-21,21>>^ Jehovah then said to Moses: “Stretch out your hand toward the heavens so that there may be darkness over the land of Egypt, a darkness so thick that it can be felt.”

[[v2-10-22]]

^<<v2-10-22,22>>^ Moses immediately stretched out his hand toward the heavens, and there was a dense darkness in all the land of Egypt for three days.

[[v2-10-23]]

^<<v2-10-23,23>>^ They did not see one another, and none of them got up from where they were for three days; but all the Israelites had light in their dwellings.

[[v2-10-24]]

^<<v2-10-24,24>>^ Pharʹaoh then called Moses and said: “Go, serve Jehovah. Only your sheep and your cattle will remain behind. Even your children may go with you.”

[[v2-10-25]]

^<<v2-10-25,25>>^ But Moses said: “You yourself will also provide us with^&#42;1^ sacrifices and burnt offerings, and we will offer them to Jehovah our God.

[NOTE]
====
. Or “allow us to have.”
====

[[v2-10-26]]

^<<v2-10-26,26>>^ Our livestock will also go with us. Not an animal^&#42;1^ will be allowed to remain, because we will be using some of them to worship Jehovah our God, and we do not know what we will offer in worship to Jehovah until we arrive there.”

[NOTE]
====
. Lit., “a hoof.”
====

[[v2-10-27]]

^<<v2-10-27,27>>^ So Jehovah allowed Pharʹaoh’s heart to become obstinate, and he did not consent to send them away.

[[v2-10-28]]

^<<v2-10-28,28>>^ Pharʹaoh said to him: “Get out of my sight! Make sure that you do not try to see my face again, for on the day you see my face, you will die.”

[[v2-10-29]]

^<<v2-10-29,29>>^ To this Moses said: “Just as you have spoken, I will not try to see your face again.”

'''

xref:002-exodus/002-exodus-009.adoc#v2-9-0[&#60; Capítulo Anterior] | <<v2-10-0,Topo>> | xref:002-exodus/002-exodus-011.adoc#v2-11-0[Próximo Capítulo &#62;]