include::./index.adoc[]

[[v2-13-0]]
=== Exodus, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-13-1]]

^<<v2-13-1,1>>^ Jehovah spoke further to Moses, saying:

[[v2-13-2]]

^<<v2-13-2,2>>^ “Sanctify^&#42;1^ to me every firstborn male^&#42;2^ among the Israelites. The first male to be born, of both human and animal, belongs to me.”

[NOTE]
====
. Or “Set apart.”
. Lit., “every firstborn that opens each womb.”
====

[[v2-13-3]]

^<<v2-13-3,3>>^ Then Moses said to the people: “Remember this day on which you went out of Egypt, from the house of slavery, because with a mighty hand Jehovah brought you out of here. So nothing leavened may be eaten.

[[v2-13-4]]

^<<v2-13-4,4>>^ You are going out on this day, in the month of Aʹbib.^&#42;1^

[NOTE]
====
. See App. B15.
====

[[v2-13-5]]

^<<v2-13-5,5>>^ When Jehovah has brought you into the land of the Caʹnaan·ites, the Hitʹtites, the Amʹor·ites, the Hiʹvites, and the Jebʹu·sites, which he swore to your forefathers to give you, a land flowing with milk and honey, then you must keep this observance in this month.

[[v2-13-6]]

^<<v2-13-6,6>>^ Seven days you are to eat unleavened bread, and on the seventh day, there will be a festival to Jehovah.

[[v2-13-7]]

^<<v2-13-7,7>>^ Unleavened bread is to be eaten for the seven days; and nothing leavened is to be found with you, and no sourdough is to be found with you within all your territory.^&#42;1^

[NOTE]
====
. Lit., “boundaries.”
====

[[v2-13-8]]

^<<v2-13-8,8>>^ And you must tell your son on that day, ‘It is because of what Jehovah did for me when I came out of Egypt.’

[[v2-13-9]]

^<<v2-13-9,9>>^ And this will serve for you as a sign on your hand and as a memorial^&#42;1^ on your forehead,^&#42;2^ so that Jehovah’s law may be in your mouth, for with a mighty hand Jehovah brought you out of Egypt.

[NOTE]
====
. Or “reminder.”
. Lit., “between your eyes.”
====

[[v2-13-10]]

^<<v2-13-10,10>>^ You must keep this statute at its appointed time from year to year.

[[v2-13-11]]

^<<v2-13-11,11>>^ “When Jehovah brings you into the land of the Caʹnaan·ites, which he has sworn to you and to your forefathers to give to you,

[[v2-13-12]]

^<<v2-13-12,12>>^ you must devote to Jehovah every firstborn male,^&#42;1^ as well as every male firstling of the livestock that you acquire. The males belong to Jehovah.

[NOTE]
====
. Lit., “everyone that opens the womb.”
====

[[v2-13-13]]

^<<v2-13-13,13>>^ Every firstling donkey you are to redeem with a sheep, and if you do not redeem it, then you must break its neck. And every firstborn male of your sons you are to redeem.

[[v2-13-14]]

^<<v2-13-14,14>>^ “In case your son should ask you later on, ‘What does this mean?’ then you should say to him, ‘With a mighty hand Jehovah brought us out of Egypt, from the house of slavery.

[[v2-13-15]]

^<<v2-13-15,15>>^ When Pharʹaoh stubbornly refused to send us away, Jehovah killed every firstborn in the land of Egypt, from the firstborn of man to the firstborn of beast. That is why I am sacrificing to Jehovah all the firstborn males,^&#42;1^ and I redeem every firstborn of my sons.’

[NOTE]
====
. Lit., “everything that opens the womb.”
====

[[v2-13-16]]

^<<v2-13-16,16>>^ This must serve as a sign on your hand and as a headband on your forehead,^&#42;1^ for with a mighty hand Jehovah brought us out of Egypt.”

[NOTE]
====
. Lit., “between your eyes.”
====

[[v2-13-17]]

^<<v2-13-17,17>>^ Now when Pharʹaoh sent the people away, God did not lead them by the way of the land of the Phi·lisʹtines, although it was near. For God said: “The people may change their minds when they are confronted by war and will return to Egypt.”

[[v2-13-18]]

^<<v2-13-18,18>>^ So God made the people go around by the way of the wilderness of the Red Sea. But it was in battle formation that the Israelites went up out of the land of Egypt.

[[v2-13-19]]

^<<v2-13-19,19>>^ Moses also took Joseph’s bones with him, because Joseph had made the sons of Israel solemnly swear: “God will not fail to turn his attention to you, and you must take my bones up out of here with you.”

[[v2-13-20]]

^<<v2-13-20,20>>^ They departed from Sucʹcoth and encamped at Eʹtham, at the edge of the wilderness.

[[v2-13-21]]

^<<v2-13-21,21>>^ Now Jehovah was going ahead of them by day in a pillar of cloud to lead them along the way, and by night in a pillar of fire to give them light, so that they could travel by day and by night.

[[v2-13-22]]

^<<v2-13-22,22>>^ The pillar of cloud would not move away from before the people during the day, nor the pillar of fire at night.

'''

xref:002-exodus/002-exodus-012.adoc#v2-12-0[&#60; Capítulo Anterior] | <<v2-13-0,Topo>> | xref:002-exodus/002-exodus-014.adoc#v2-14-0[Próximo Capítulo &#62;]