include::./index.adoc[]

[[v2-8-0]]
=== Exodus, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-8-1]]

^<<v2-8-1,1>>^ Then Jehovah said to Moses: “Go in to Pharʹaoh and say to him, ‘This is what Jehovah says: “Send my people away so that they may serve me.

[[v2-8-2]]

^<<v2-8-2,2>>^ If you keep refusing to send them away, I will plague all your territory with frogs.

[[v2-8-3]]

^<<v2-8-3,3>>^ And the Nile River will swarm with frogs, and they will come up and enter into your house, into your bedroom, on your bed, into the houses of your servants and on your people, into your ovens, and into your kneading troughs.^&#42;1^

[NOTE]
====
. Or “bowls.”
====

[[v2-8-4]]

^<<v2-8-4,4>>^ On you, on your people, and on all your servants, the frogs will come up.”’”

[[v2-8-5]]

^<<v2-8-5,5>>^ Jehovah later said to Moses: “Say to Aaron, ‘Stretch out your hand with your rod over the rivers, the Nile canals, and the marshes, and make the frogs come up over the land of Egypt.’”

[[v2-8-6]]

^<<v2-8-6,6>>^ So Aaron stretched out his hand over the waters of Egypt, and the frogs began to come up and to cover the land of Egypt.

[[v2-8-7]]

^<<v2-8-7,7>>^ However, the magic-practicing priests did the same thing by their secret arts, and they too made the frogs come up over the land of Egypt.

[[v2-8-8]]

^<<v2-8-8,8>>^ Pharʹaoh then called Moses and Aaron and said: “Plead with Jehovah to remove the frogs from me and my people, as I want to send the people away so that they may sacrifice to Jehovah.”

[[v2-8-9]]

^<<v2-8-9,9>>^ Then Moses said to Pharʹaoh: “I leave to you the honor of telling me when I should plead to have the frogs removed from you, your servants, your people, and your houses. Only in the Nile River will they be left.”

[[v2-8-10]]

^<<v2-8-10,10>>^ To this he said: “Tomorrow.” So he said: “It will be according to your word so that you may know that there is no one else like Jehovah our God.

[[v2-8-11]]

^<<v2-8-11,11>>^ The frogs will depart from you, your houses, your servants, and your people. They will be left only in the Nile.”

[[v2-8-12]]

^<<v2-8-12,12>>^ So Moses and Aaron went out from Pharʹaoh, and Moses pleaded with Jehovah about the frogs that He had brought upon Pharʹaoh.

[[v2-8-13]]

^<<v2-8-13,13>>^ Then Jehovah did as Moses asked, and the frogs began to die in the houses, the courtyards, and the fields.

[[v2-8-14]]

^<<v2-8-14,14>>^ They were piling them up in countless heaps, and the land began to stink.

[[v2-8-15]]

^<<v2-8-15,15>>^ When Pharʹaoh saw that there was relief, he hardened his heart and he refused to listen to them, just as Jehovah had said.

[[v2-8-16]]

^<<v2-8-16,16>>^ Jehovah now said to Moses: “Say to Aaron, ‘Stretch out your rod and strike the dust of the earth, and it must become gnats in all the land of Egypt.’”

[[v2-8-17]]

^<<v2-8-17,17>>^ And they did this. Aaron stretched out his hand with his rod and struck the dust of the earth, and the gnats came on man and beast. All the dust of the earth became gnats in all the land of Egypt.

[[v2-8-18]]

^<<v2-8-18,18>>^ The magic-practicing priests tried to do the same and produce gnats by their secret arts, but they could not. And the gnats came on man and beast.

[[v2-8-19]]

^<<v2-8-19,19>>^ So the magic-practicing priests said to Pharʹaoh: “It is the finger of God!” But Pharʹaoh’s heart continued to be obstinate, and he did not listen to them, just as Jehovah had said.

[[v2-8-20]]

^<<v2-8-20,20>>^ Then Jehovah said to Moses: “Get up early in the morning and station yourself in front of Pharʹaoh. Look! He is coming out to the water! And you must say to him, ‘This is what Jehovah has said: “Send my people away so that they may serve me.

[[v2-8-21]]

^<<v2-8-21,21>>^ But if you do not send my people away, I will send on you, your servants, and your people and into your houses the gadfly;^&#42;1^ and the houses of Egypt will be full of gadflies, and they will even cover the ground they^&#42;2^ stand on.

[NOTE]
====
. A type of fly that bites.
. That is, the Egyptians.
====

[[v2-8-22]]

^<<v2-8-22,22>>^ On that day I will certainly set apart the land of Goʹshen, where my people are dwelling. No gadflies will exist there, and by this you will know that I, Jehovah, am here in the land.

[[v2-8-23]]

^<<v2-8-23,23>>^ And I will make a distinction between my people and your people. Tomorrow this sign will take place.”’”

[[v2-8-24]]

^<<v2-8-24,24>>^ And Jehovah did so, and heavy swarms of gadflies began to invade the house of Pharʹaoh and the houses of his servants and all the land of Egypt. The land was ruined by the gadflies.

[[v2-8-25]]

^<<v2-8-25,25>>^ Finally, Pharʹaoh called Moses and Aaron and said: “Go, sacrifice to your God in the land.”

[[v2-8-26]]

^<<v2-8-26,26>>^ But Moses said: “It is not proper to do so, because what we would sacrifice to Jehovah our God would be detestable to the Egyptians. If we would make a sacrifice that was detestable to the Egyptians right before their eyes, would they not stone us?

[[v2-8-27]]

^<<v2-8-27,27>>^ We will make a three-day journey into the wilderness, and there we will sacrifice to Jehovah our God, just as he has said to us.”

[[v2-8-28]]

^<<v2-8-28,28>>^ Pharʹaoh now said: “I will send you away to sacrifice to Jehovah your God in the wilderness. Only, you must not go so far away. Plead in my behalf.”

[[v2-8-29]]

^<<v2-8-29,29>>^ Then Moses said: “Now I am going away from you, and I will plead with Jehovah, and the gadflies will depart from Pharʹaoh, his servants, and his people tomorrow. But Pharʹaoh must stop trifling^&#42;1^ with us by refusing to send the people away to sacrifice to Jehovah.”

[NOTE]
====
. Or “playing games.”
====

[[v2-8-30]]

^<<v2-8-30,30>>^ Moses then went out from Pharʹaoh and pleaded with Jehovah.

[[v2-8-31]]

^<<v2-8-31,31>>^ So Jehovah did according to Moses’ word, and the gadflies departed from Pharʹaoh, his servants, and his people. Not one was left.

[[v2-8-32]]

^<<v2-8-32,32>>^ However, Pharʹaoh again hardened his heart and did not send the people away.

'''

xref:002-exodus/002-exodus-007.adoc#v2-7-0[&#60; Capítulo Anterior] | <<v2-8-0,Topo>> | xref:002-exodus/002-exodus-009.adoc#v2-9-0[Próximo Capítulo &#62;]