include::./index.adoc[]

[[v2-20-0]]
=== Exodus, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-20-1]]

^<<v2-20-1,1>>^ Then God spoke all these words:

[[v2-20-2]]

^<<v2-20-2,2>>^ “I am Jehovah your God, who brought you out of the land of Egypt, out of the house of slavery.

[[v2-20-3]]

^<<v2-20-3,3>>^ You must not have any other gods besides me.^&#42;1^

[NOTE]
====
. Or “in defiance of me.” Lit., “against my face.”
====

[[v2-20-4]]

^<<v2-20-4,4>>^ “You must not make for yourself a carved image or a form^&#42;1^ like anything that is in the heavens above or on the earth below or in the waters under the earth.

[NOTE]
====
. Or “representation.”
====

[[v2-20-5]]

^<<v2-20-5,5>>^ You must not bow down to them nor be enticed to serve them, for I, Jehovah your God, am a God who requires exclusive devotion, bringing punishment for the error of fathers upon sons, upon the third generation and upon the fourth generation of those who hate me,

[[v2-20-6]]

^<<v2-20-6,6>>^ but showing loyal love to the thousandth generation of those who love me and keep my commandments.

[[v2-20-7]]

^<<v2-20-7,7>>^ “You must not take up the name of Jehovah your God in a worthless way, for Jehovah will not leave unpunished the one who takes up His name in a worthless way.

[[v2-20-8]]

^<<v2-20-8,8>>^ “Remember the Sabbath day to keep it sacred.

[[v2-20-9]]

^<<v2-20-9,9>>^ You are to labor and do all your work for six days,

[[v2-20-10]]

^<<v2-20-10,10>>^ but the seventh day is a sabbath to Jehovah your God. You must not do any work, neither you nor your son nor your daughter nor your slave man nor your slave girl nor your domestic animal nor your foreign resident who is inside your settlements.^&#42;1^

[NOTE]
====
. Lit., “gates.”
====

[[v2-20-11]]

^<<v2-20-11,11>>^ For in six days Jehovah made the heavens and the earth, the sea, and all that is in them, and he began to rest on the seventh day. That is why Jehovah blessed the Sabbath day and made it sacred.

[[v2-20-12]]

^<<v2-20-12,12>>^ “Honor your father and your mother, so that you may live a long time in the land that Jehovah your God is giving you.

[[v2-20-13]]

^<<v2-20-13,13>>^ “You must not murder.

[[v2-20-14]]

^<<v2-20-14,14>>^ “You must not commit adultery.

[[v2-20-15]]

^<<v2-20-15,15>>^ “You must not steal.

[[v2-20-16]]

^<<v2-20-16,16>>^ “You must not testify falsely when you are a witness against your fellow man.

[[v2-20-17]]

^<<v2-20-17,17>>^ “You must not desire your fellow man’s house. You must not desire your fellow man’s wife nor his slave man nor his slave girl nor his bull nor his donkey nor anything that belongs to your fellow man.”

[[v2-20-18]]

^<<v2-20-18,18>>^ Now all the people were witnessing the thunder and lightning, the sound of the horn, and the mountain smoking; and seeing this made them tremble and stand at a distance.

[[v2-20-19]]

^<<v2-20-19,19>>^ So they said to Moses: “You speak with us, and we will listen, but do not let God speak with us, for fear that we will die.”

[[v2-20-20]]

^<<v2-20-20,20>>^ So Moses said to the people: “Do not be afraid, for the true God has come to put you to the test, in order that the fear of him may continue with you so that you may not sin.”

[[v2-20-21]]

^<<v2-20-21,21>>^ So the people kept standing at a distance, but Moses went near to the dark cloud where the true God was.

[[v2-20-22]]

^<<v2-20-22,22>>^ Then Jehovah said to Moses: “This is what you are to say to the Israelites, ‘You have seen for yourselves that I spoke with you from heaven.

[[v2-20-23]]

^<<v2-20-23,23>>^ You must not make gods of silver alongside me, and you must not make gods of gold for yourselves.

[[v2-20-24]]

^<<v2-20-24,24>>^ An altar of earth you are to make for me, and you will sacrifice on it your burnt offerings, your communion sacrifices,^&#42;1^ your flock, and your herd. In every place where I cause my name to be remembered I will come to you and I will bless you.

[NOTE]
====
. Or “your peace offerings.”
====

[[v2-20-25]]

^<<v2-20-25,25>>^ If you make an altar of stones for me, you must not build it using stones cut with tools.^&#42;1^ For if you do use your chisel on it, you will profane it.

[NOTE]
====
. Or “using hewn stones.”
====

[[v2-20-26]]

^<<v2-20-26,26>>^ And you must not go up by steps to my altar, that your private parts^&#42;1^ may not be exposed upon it.’

[NOTE]
====
. Lit., “your nakedness.”
====

'''

xref:002-exodus/002-exodus-019.adoc#v2-19-0[&#60; Capítulo Anterior] | <<v2-20-0,Topo>> | xref:002-exodus/002-exodus-021.adoc#v2-21-0[Próximo Capítulo &#62;]