include::./index.adoc[]

[[v2-26-0]]
=== Exodus, 26
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-26-1]]

^<<v2-26-1,1>>^ “You are to make the tabernacle with ten tent cloths of fine twisted linen, blue thread, purple wool, and scarlet material. You are to make them with embroidered cherub designs.

[[v2-26-2]]

^<<v2-26-2,2>>^ Each tent cloth will be 28 cubits^&#42;1^ long and 4 cubits wide. All the tent cloths are to be the same size.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
====

[[v2-26-3]]

^<<v2-26-3,3>>^ Five tent cloths are to be joined one to another to form a series, and the other five tent cloths will be joined in a series.

[[v2-26-4]]

^<<v2-26-4,4>>^ You will make loops of blue thread on the edge of the one tent cloth at the end of the series, and you are to do the same on the outermost edge of the other set where it will join.

[[v2-26-5]]

^<<v2-26-5,5>>^ You will make 50 loops on the one tent cloth and 50 loops on the edge of the other tent cloth so that they will be opposite each other where they join.

[[v2-26-6]]

^<<v2-26-6,6>>^ You are to make 50 gold clasps and join the tent cloths together with the clasps, and the tabernacle will form one unit.

[[v2-26-7]]

^<<v2-26-7,7>>^ “You will also make cloths of goat hair for the tent over the tabernacle. You will make 11 tent cloths.

[[v2-26-8]]

^<<v2-26-8,8>>^ Each tent cloth will be 30 cubits long and 4 cubits wide. All 11 tent cloths are to be the same size.

[[v2-26-9]]

^<<v2-26-9,9>>^ You are to join five of the tent cloths together and join the other six tent cloths together, and you are to fold over the sixth tent cloth at the front of the tent.

[[v2-26-10]]

^<<v2-26-10,10>>^ And you are to make 50 loops on the edge of the one tent cloth, the outermost one in the series, and 50 loops on the edge of the tent cloth at the other place where they join.

[[v2-26-11]]

^<<v2-26-11,11>>^ You are to make 50 copper clasps and put the clasps in the loops and join the tent together, and it will become one unit.

[[v2-26-12]]

^<<v2-26-12,12>>^ The remaining part of the tent cloths will serve as an overhanging. Half of the tent cloth that remains will hang over the back of the tabernacle.

[[v2-26-13]]

^<<v2-26-13,13>>^ The remaining length of the cloths of the tent will serve as an overhanging for the tabernacle by one cubit on each side, in order to cover it.

[[v2-26-14]]

^<<v2-26-14,14>>^ “You will also make a covering for the tent of ram skins dyed red and over that a covering of sealskins.

[[v2-26-15]]

^<<v2-26-15,15>>^ “You will make the panel frames for the tabernacle out of acacia wood standing upright.

[[v2-26-16]]

^<<v2-26-16,16>>^ Each panel frame is to be ten cubits high and a cubit and a half wide.

[[v2-26-17]]

^<<v2-26-17,17>>^ Each panel frame has two tenons^&#42;1^ joined to each other. That is how you should make all the panel frames of the tabernacle.

[NOTE]
====
. Or “upright posts.”
====

[[v2-26-18]]

^<<v2-26-18,18>>^ You are to make 20 panel frames for the south side of the tabernacle, facing south.

[[v2-26-19]]

^<<v2-26-19,19>>^ “You will make 40 silver socket pedestals under the 20 panel frames: two socket pedestals under the one panel frame for its two tenons and two socket pedestals under each following panel frame for its two tenons.

[[v2-26-20]]

^<<v2-26-20,20>>^ For the other side of the tabernacle, the northern side, make 20 panel frames

[[v2-26-21]]

^<<v2-26-21,21>>^ and their 40 silver socket pedestals, two socket pedestals under one panel frame and two socket pedestals under each following panel frame.

[[v2-26-22]]

^<<v2-26-22,22>>^ For the rear section of the tabernacle to the west, you will make six panel frames.

[[v2-26-23]]

^<<v2-26-23,23>>^ You will make two panel frames to serve as the two rear corner posts of the tabernacle.

[[v2-26-24]]

^<<v2-26-24,24>>^ They should be doubled from the bottom to the top, up to the first ring. This should be done for both of them, and they will form the two corner posts.

[[v2-26-25]]

^<<v2-26-25,25>>^ And there will be eight panel frames and their 16 silver socket pedestals, two socket pedestals under the one panel frame and two socket pedestals under each following panel frame.

[[v2-26-26]]

^<<v2-26-26,26>>^ “You will make bars of acacia wood, five for the panel frames of the one side of the tabernacle,

[[v2-26-27]]

^<<v2-26-27,27>>^ and five bars for the panel frames of the other side of the tabernacle, and five bars for the panel frames of the side of the tabernacle to the west, for the rear section.

[[v2-26-28]]

^<<v2-26-28,28>>^ The middle bar that runs along the center of the panel frames should extend from end to end.

[[v2-26-29]]

^<<v2-26-29,29>>^ “You will overlay the panel frames with gold, and you will make their rings of gold as holders for the bars, and you will overlay the bars with gold.

[[v2-26-30]]

^<<v2-26-30,30>>^ You must set up the tabernacle according to its plan that you were shown in the mountain.

[[v2-26-31]]

^<<v2-26-31,31>>^ “You are to make a curtain of blue thread, purple wool, scarlet material, and fine twisted linen. It will be made with cherubs embroidered on it.

[[v2-26-32]]

^<<v2-26-32,32>>^ You will hang it on four pillars of acacia overlaid with gold. Their hooks are to be of gold. The pillars are set on four socket pedestals of silver.

[[v2-26-33]]

^<<v2-26-33,33>>^ You will hang the curtain under the clasps and bring the ark of the Testimony there within the curtain. The curtain will make a division for you between the Holy and the Most Holy.

[[v2-26-34]]

^<<v2-26-34,34>>^ You must put the cover on the ark of the Testimony in the Most Holy.

[[v2-26-35]]

^<<v2-26-35,35>>^ “You will place the table outside the curtain, with the lampstand opposite the table on the south side of the tabernacle; and the table you will put on the north side.

[[v2-26-36]]

^<<v2-26-36,36>>^ You will make a screen^&#42;1^ for the entrance of the tent out of blue thread, purple wool, scarlet material, and fine twisted linen woven together.

[NOTE]
====
. Or “curtain.”
====

[[v2-26-37]]

^<<v2-26-37,37>>^ You will make five pillars of acacia for the screen^&#42;1^ and overlay them with gold. Their hooks are to be of gold, and you will cast five socket pedestals of copper for them.

[NOTE]
====
. Or “curtain.”
====

'''

xref:002-exodus/002-exodus-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodus/002-exodus-027.adoc#v2-27-0[Próximo Capítulo &#62;]