include::./index.adoc[]

[[v2-7-0]]
=== Exodus, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-7-1]]

^<<v2-7-1,1>>^ Jehovah then said to Moses: “See, I have made you like God^&#42;1^ to Pharʹaoh, and Aaron your own brother will become your prophet.

[NOTE]
====
. Lit., “made you God.”
====

[[v2-7-2]]

^<<v2-7-2,2>>^ You are to repeat everything that I will command you, and Aaron your brother will speak to Pharʹaoh, and he will send the Israelites away from his land.

[[v2-7-3]]

^<<v2-7-3,3>>^ As for me, I will allow Pharʹaoh’s heart to become obstinate, and I will multiply my signs and my miracles in the land of Egypt.

[[v2-7-4]]

^<<v2-7-4,4>>^ But Pharʹaoh will not listen to you, and I will lay my hand upon Egypt and bring my multitudes,^&#42;1^ my people, the Israelites, out of the land of Egypt with great judgments.

[NOTE]
====
. Lit., “my armies.”
====

[[v2-7-5]]

^<<v2-7-5,5>>^ And the Egyptians will certainly know that I am Jehovah when I stretch out my hand against Egypt and bring the Israelites out from among them.”

[[v2-7-6]]

^<<v2-7-6,6>>^ Moses and Aaron did what Jehovah had commanded them; they did just so.

[[v2-7-7]]

^<<v2-7-7,7>>^ Moses was 80 years old and Aaron was 83 years old when they spoke to Pharʹaoh.

[[v2-7-8]]

^<<v2-7-8,8>>^ Jehovah now said to Moses and Aaron:

[[v2-7-9]]

^<<v2-7-9,9>>^ “If Pharʹaoh says to you, ‘Perform a miracle,’ then tell Aaron, ‘Take your rod and throw it down before Pharʹaoh.’ It will become a big snake.”

[[v2-7-10]]

^<<v2-7-10,10>>^ So Moses and Aaron went in to Pharʹaoh and did exactly as Jehovah had commanded. Aaron threw his rod down before Pharʹaoh and his servants, and it became a big snake.

[[v2-7-11]]

^<<v2-7-11,11>>^ However, Pharʹaoh summoned the wise men and the sorcerers, and the magic-practicing priests of Egypt also did the same thing with their magic.^&#42;1^

[NOTE]
====
. Or “their magic arts.”
====

[[v2-7-12]]

^<<v2-7-12,12>>^ Each one threw down his rod, and they became big snakes; but Aaron’s rod swallowed up their rods.

[[v2-7-13]]

^<<v2-7-13,13>>^ Still, Pharʹaoh’s heart became obstinate, and he did not listen to them, just as Jehovah had said.

[[v2-7-14]]

^<<v2-7-14,14>>^ Then Jehovah said to Moses: “Pharʹaoh’s heart is unresponsive. He has refused to send the people away.

[[v2-7-15]]

^<<v2-7-15,15>>^ Go to Pharʹaoh in the morning. Look! He is going out to the water! And you should station yourself to meet him by the edge of the Nile River; and take with you in your hand the rod that turned into a serpent.

[[v2-7-16]]

^<<v2-7-16,16>>^ And you must say to him, ‘Jehovah the God of the Hebrews has sent me to you, and he says: “Send my people away so that they may serve me in the wilderness,” but you have not obeyed until now.

[[v2-7-17]]

^<<v2-7-17,17>>^ This is what Jehovah says: “By this you will know that I am Jehovah. Here I am striking the water that is in the Nile River with the rod that is in my hand, and it will turn into blood.

[[v2-7-18]]

^<<v2-7-18,18>>^ And the fish that are in the Nile will die, and the Nile will stink, and the Egyptians will find it impossible to drink water from the Nile.”’”

[[v2-7-19]]

^<<v2-7-19,19>>^ Then Jehovah said to Moses: “Say to Aaron, ‘Take your rod and stretch out your hand over the waters of Egypt, over its rivers, over its canals,^&#42;1^ over its marshes, and over all its reservoirs, that they may become blood.’ There will be blood in all the land of Egypt, even in the wooden and stone containers.”

[NOTE]
====
. That is, canals from the Nile.
====

[[v2-7-20]]

^<<v2-7-20,20>>^ Immediately Moses and Aaron did just as Jehovah had commanded. He lifted up the rod and struck the water that was in the Nile River before the eyes of Pharʹaoh and his servants, and all the water that was in the river was turned into blood.

[[v2-7-21]]

^<<v2-7-21,21>>^ And the fish that were in the river died, and the river began to stink, and the Egyptians were unable to drink water from the Nile, and there was blood throughout the land of Egypt.

[[v2-7-22]]

^<<v2-7-22,22>>^ Nevertheless, the magic-practicing priests of Egypt did the same thing with their secret arts, so that Pharʹaoh’s heart continued to be obstinate, and he did not listen to them, just as Jehovah had said.

[[v2-7-23]]

^<<v2-7-23,23>>^ Then Pharʹaoh returned to his house, and he did not take this to heart either.

[[v2-7-24]]

^<<v2-7-24,24>>^ So all the Egyptians were digging all around the Nile for water to drink, because they could not drink any water of the Nile.

[[v2-7-25]]

^<<v2-7-25,25>>^ And seven full days passed after Jehovah struck the Nile.

'''

xref:002-exodus/002-exodus-006.adoc#v2-6-0[&#60; Capítulo Anterior] | <<v2-7-0,Topo>> | xref:002-exodus/002-exodus-008.adoc#v2-8-0[Próximo Capítulo &#62;]