include::./index.adoc[]

[[v2-35-0]]
=== Exodus, 35
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-35-1]]

^<<v2-35-1,1>>^ Moses later gathered the entire assembly of the Israelites together and said to them: “These are the things that Jehovah has commanded to be done:

[[v2-35-2]]

^<<v2-35-2,2>>^ Work may be done for six days, but the seventh day will become something holy to you, a sabbath of complete rest to Jehovah. Anybody doing work on it will be put to death.

[[v2-35-3]]

^<<v2-35-3,3>>^ You must not light a fire in any of your dwelling places on the Sabbath day.”

[[v2-35-4]]

^<<v2-35-4,4>>^ Moses then said to the entire assembly of the Israelites: “This is what Jehovah has commanded,

[[v2-35-5]]

^<<v2-35-5,5>>^ ‘Take up a contribution for Jehovah from among yourselves. Let everyone with a willing heart bring a contribution for Jehovah: gold, silver, copper,

[[v2-35-6]]

^<<v2-35-6,6>>^ blue thread, purple wool, scarlet material, fine linen, goat hair,

[[v2-35-7]]

^<<v2-35-7,7>>^ ram skins dyed red, sealskins, acacia wood,

[[v2-35-8]]

^<<v2-35-8,8>>^ oil for the lamps, balsam for the anointing oil and for the perfumed incense,

[[v2-35-9]]

^<<v2-35-9,9>>^ onyx stones, and other stones for setting in the ephʹod and the breastpiece.

[[v2-35-10]]

^<<v2-35-10,10>>^ “‘Let all who are skilled^&#42;1^ among you come and make everything that Jehovah has commanded,

[NOTE]
====
. Lit., “wise of heart.”
====

[[v2-35-11]]

^<<v2-35-11,11>>^ namely, the tabernacle with its tent and its covering, its clasps and its panel frames, its bars, its pillars, and its socket pedestals;

[[v2-35-12]]

^<<v2-35-12,12>>^ the Ark and its poles, the cover, and the curtain for the screen;

[[v2-35-13]]

^<<v2-35-13,13>>^ the table and its poles and all its utensils and the showbread;

[[v2-35-14]]

^<<v2-35-14,14>>^ the lampstand for light and its utensils and its lamps and the oil for lighting;

[[v2-35-15]]

^<<v2-35-15,15>>^ the altar of incense and its poles; the anointing oil and the perfumed incense; the screen^&#42;1^ for the tabernacle’s entrance;

[NOTE]
====
. Or “curtain.”
====

[[v2-35-16]]

^<<v2-35-16,16>>^ the altar of burnt offering and its copper grating, its poles and all its utensils; the basin and its stand;

[[v2-35-17]]

^<<v2-35-17,17>>^ the hanging curtains of the courtyard, its pillars and its socket pedestals; the screen^&#42;1^ of the entrance to the courtyard;

[NOTE]
====
. Or “curtain.”
====

[[v2-35-18]]

^<<v2-35-18,18>>^ the tent pins of the tabernacle and the tent pins of the courtyard and their cords;

[[v2-35-19]]

^<<v2-35-19,19>>^ the finely woven garments for ministering in the sanctuary, the holy garments for Aaron the priest, and the garments of his sons for serving as priests.’”

[[v2-35-20]]

^<<v2-35-20,20>>^ So all the assembly of the Israelites went out from before Moses.

[[v2-35-21]]

^<<v2-35-21,21>>^ Then everyone whose heart impelled him and everyone whose spirit incited him came and brought their contribution for Jehovah to be used for the tent of meeting, for all its service, and for the holy garments.

[[v2-35-22]]

^<<v2-35-22,22>>^ They kept coming, the men along with the women, each with a willing heart, bringing brooches, earrings, rings, and other jewelry, as well as all sorts of articles of gold. They all presented their offerings^&#42;1^ of gold to Jehovah.

[NOTE]
====
. Or “wave offerings.”
====

[[v2-35-23]]

^<<v2-35-23,23>>^ And all who had blue thread, purple wool, scarlet material, fine linen, goat hair, ram skins dyed red, and sealskins brought them.

[[v2-35-24]]

^<<v2-35-24,24>>^ All those contributing silver and copper brought Jehovah’s contribution, and all who had acacia wood for any part of the work brought it.

[[v2-35-25]]

^<<v2-35-25,25>>^ All the skilled women spun with their hands, and they brought what they had spun: blue thread, purple wool, scarlet material, and fine linen.

[[v2-35-26]]

^<<v2-35-26,26>>^ And all the skilled women whose hearts impelled them spun the goat hair.

[[v2-35-27]]

^<<v2-35-27,27>>^ And the chieftains brought onyx stones and other stones to be set in the ephʹod and the breastpiece,

[[v2-35-28]]

^<<v2-35-28,28>>^ and the balsam and the oil for lighting and for the anointing oil and for the perfumed incense.

[[v2-35-29]]

^<<v2-35-29,29>>^ All the men and women whose hearts incited them brought something for the work that Jehovah, through Moses, had commanded to be done; the Israelites brought it as a voluntary offering to Jehovah.

[[v2-35-30]]

^<<v2-35-30,30>>^ Then Moses said to the Israelites: “See, Jehovah has chosen Bezʹal·el the son of Uʹri the son of Hur of the tribe of Judah.

[[v2-35-31]]

^<<v2-35-31,31>>^ He has filled him with the spirit of God, giving him wisdom, understanding, and knowledge of every sort of craftsmanship

[[v2-35-32]]

^<<v2-35-32,32>>^ for making artistic designs, for working with gold, silver, and copper,

[[v2-35-33]]

^<<v2-35-33,33>>^ for cutting and setting stones, and for making all kinds of artistic wood products.

[[v2-35-34]]

^<<v2-35-34,34>>^ And he has put it into his heart to teach, he and O·hoʹli·ab the son of A·hisʹa·mach of the tribe of Dan.

[[v2-35-35]]

^<<v2-35-35,35>>^ He has filled them with skill^&#42;1^ to do all the work of a craftsman, an embroiderer, and a weaver using blue thread, purple wool, scarlet material, and fine linen, and of a loom worker. These men will do every sort of work and prepare every sort of design.

[NOTE]
====
. Lit., “wisdom of heart.”
====

'''

xref:002-exodus/002-exodus-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodus/002-exodus-036.adoc#v2-36-0[Próximo Capítulo &#62;]