include::./index.adoc[]

[[v2-19-0]]
=== Exodus, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-19-1]]

^<<v2-19-1,1>>^ In the third month after the Israelites went out of the land of Egypt, on the same day, they came to the wilderness of Siʹnai.

[[v2-19-2]]

^<<v2-19-2,2>>^ They pulled away from Rephʹi·dim and came to the wilderness of Siʹnai and camped in the wilderness. Israel camped there in front of the mountain.

[[v2-19-3]]

^<<v2-19-3,3>>^ Then Moses went up to the true God, and Jehovah called to him from the mountain, saying: “This is what you are to say to the house of Jacob and to tell the Israelites,

[[v2-19-4]]

^<<v2-19-4,4>>^ ‘You have seen for yourselves what I did to the Egyptians, in order to carry you on wings of eagles and bring you to myself.

[[v2-19-5]]

^<<v2-19-5,5>>^ Now if you will strictly obey my voice and keep my covenant, you will certainly become my special property^&#42;1^ out of all peoples, for the whole earth belongs to me.

[NOTE]
====
. Or “treasured possession.”
====

[[v2-19-6]]

^<<v2-19-6,6>>^ You will become to me a kingdom of priests and a holy nation.’ These are the words that you are to say to the Israelites.”

[[v2-19-7]]

^<<v2-19-7,7>>^ So Moses went and summoned the elders of the people and declared to them all these words that Jehovah had commanded him.

[[v2-19-8]]

^<<v2-19-8,8>>^ After that all the people answered unanimously: “All that Jehovah has spoken, we are willing to do.” Moses immediately took the people’s response to Jehovah.

[[v2-19-9]]

^<<v2-19-9,9>>^ And Jehovah said to Moses: “Look! I am coming to you in a dark cloud, so that the people may hear when I speak with you and so that they may always put faith in you as well.” Then Moses reported the words of the people to Jehovah.

[[v2-19-10]]

^<<v2-19-10,10>>^ Then Jehovah said to Moses: “Go to the people and sanctify them today and tomorrow, and they must wash their clothing.

[[v2-19-11]]

^<<v2-19-11,11>>^ And they must be ready for the third day, because on the third day Jehovah will come down upon Mount Siʹnai before the eyes of all the people.

[[v2-19-12]]

^<<v2-19-12,12>>^ You must set boundaries for the people all around it and tell them, ‘Beware of going up to the mountain or touching its border. Anybody touching the mountain will surely be put to death.

[[v2-19-13]]

^<<v2-19-13,13>>^ No hand is to touch him, but he will either be stoned or be shot through.^&#42;1^ Whether beast or man, he will not live.’ But at the sound of the ram’s horn they may come up to the mountain.”

[NOTE]
====
. Perhaps shot with an arrow.
====

[[v2-19-14]]

^<<v2-19-14,14>>^ Then Moses went down from the mountain to the people, and he began to sanctify the people, and they washed their clothing.

[[v2-19-15]]

^<<v2-19-15,15>>^ He said to the people: “Get ready for the third day. Abstain from sexual relations.”^&#42;1^

[NOTE]
====
. Lit., “Do not approach a woman.”
====

[[v2-19-16]]

^<<v2-19-16,16>>^ On the morning of the third day, there was thunder and lightning, and there was a heavy cloud on the mountain and a very loud sound of a horn, and all the people in the camp began to tremble.

[[v2-19-17]]

^<<v2-19-17,17>>^ Moses now brought the people out of the camp to meet the true God, and they took their place at the base of the mountain.

[[v2-19-18]]

^<<v2-19-18,18>>^ Mount Siʹnai smoked all over, because Jehovah came down upon it in fire; and its smoke was rising like the smoke of a kiln, and the whole mountain was trembling violently.

[[v2-19-19]]

^<<v2-19-19,19>>^ As the sound of the horn grew louder and louder, Moses spoke, and the voice of the true God answered him.

[[v2-19-20]]

^<<v2-19-20,20>>^ So Jehovah came down upon Mount Siʹnai to the top of the mountain. Then Jehovah called Moses to the top of the mountain, and Moses went up.

[[v2-19-21]]

^<<v2-19-21,21>>^ Jehovah now said to Moses: “Go down and warn the people not to try to force their way through to look at Jehovah, or many of them will perish.

[[v2-19-22]]

^<<v2-19-22,22>>^ And let the priests who regularly come near to Jehovah sanctify themselves, so that Jehovah may not strike^&#42;1^ them.”

[NOTE]
====
. Lit., “break through on.”
====

[[v2-19-23]]

^<<v2-19-23,23>>^ Moses then said to Jehovah: “The people are not able to come up to Mount Siʹnai because you already warned us, saying, ‘Set boundaries around the mountain, and make it sacred.’”

[[v2-19-24]]

^<<v2-19-24,24>>^ However, Jehovah said to him: “Go, descend, and come back up, you and Aaron with you, but do not let the priests and the people force their way through to come up to Jehovah, so that he may not strike them.”

[[v2-19-25]]

^<<v2-19-25,25>>^ So Moses descended to the people and told them.

'''

xref:002-exodus/002-exodus-018.adoc#v2-18-0[&#60; Capítulo Anterior] | <<v2-19-0,Topo>> | xref:002-exodus/002-exodus-020.adoc#v2-20-0[Próximo Capítulo &#62;]