include::./index.adoc[]

[[v2-6-0]]
=== Exodus, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-6-1]]

^<<v2-6-1,1>>^ So Jehovah said to Moses: “Now you will see what I will do to Pharʹaoh. A mighty hand will force him to send them away, and a mighty hand will force him to drive them out of his land.”

[[v2-6-2]]

^<<v2-6-2,2>>^ Then God said to Moses: “I am Jehovah.

[[v2-6-3]]

^<<v2-6-3,3>>^ And I used to appear to Abraham, Isaac, and Jacob as God Almighty, but with regard to my name Jehovah I did not make myself known to them.

[[v2-6-4]]

^<<v2-6-4,4>>^ I also established my covenant with them to give them the land of Caʹnaan, the land in which they lived as foreigners.

[[v2-6-5]]

^<<v2-6-5,5>>^ Now I myself have heard the groaning of the people of Israel, whom the Egyptians are enslaving, and I remember my covenant.

[[v2-6-6]]

^<<v2-6-6,6>>^ “Therefore, say to the Israelites: ‘I am Jehovah, and I will bring you out from under the burdens of the Egyptians and rescue you from their slavery, and I will reclaim you with an outstretched^&#42;1^ arm and with great judgments.

[NOTE]
====
. Or “a powerful.”
====

[[v2-6-7]]

^<<v2-6-7,7>>^ And I will take you in as my people, and I will be your God, and you will certainly know that I am Jehovah your God who is bringing you out from under the burdens of Egypt.

[[v2-6-8]]

^<<v2-6-8,8>>^ And I will bring you into the land that I swore with an oath^&#42;1^ to give to Abraham, Isaac, and Jacob; and I will give it to you as something to possess. I am Jehovah.’”

[NOTE]
====
. Lit., “I raised my hand.”
====

[[v2-6-9]]

^<<v2-6-9,9>>^ Moses later gave this message to the Israelites, but they did not listen to Moses because of their discouragement and because of the harsh slavery.

[[v2-6-10]]

^<<v2-6-10,10>>^ Then Jehovah spoke to Moses, saying:

[[v2-6-11]]

^<<v2-6-11,11>>^ “Go in and tell Pharʹaoh, Egypt’s king, that he should send the Israelites away out of his land.”

[[v2-6-12]]

^<<v2-6-12,12>>^ However, Moses replied to Jehovah: “Look! The Israelites have not listened to me; how will Pharʹaoh ever listen to me, as I speak with difficulty?”^&#42;1^

[NOTE]
====
. Lit., “I am uncircumcised in lips.”
====

[[v2-6-13]]

^<<v2-6-13,13>>^ But Jehovah again told Moses and Aaron what commands to give to the Israelites and to Pharʹaoh, Egypt’s king, in order to bring the Israelites out of the land of Egypt.

[[v2-6-14]]

^<<v2-6-14,14>>^ These are the heads of the house of their fathers: The sons of Reuʹben, Israel’s firstborn, were Haʹnoch, Palʹlu, Hezʹron, and Carʹmi. These are the families of Reuʹben.

[[v2-6-15]]

^<<v2-6-15,15>>^ The sons of Simʹe·on were Jem·uʹel, Jaʹmin, Oʹhad, Jaʹchin, Zoʹhar, and Shaʹul, the son of a Caʹnaan·ite woman. These are the families of Simʹe·on.

[[v2-6-16]]

^<<v2-6-16,16>>^ These are the names of the sons of Leʹvi, according to their family descents: Gerʹshon, Koʹhath, and Me·rarʹi. The length of Leʹvi’s life was 137 years.

[[v2-6-17]]

^<<v2-6-17,17>>^ The sons of Gerʹshon were Libʹni and Shimʹe·i, according to their families.

[[v2-6-18]]

^<<v2-6-18,18>>^ The sons of Koʹhath were Amʹram, Izʹhar, Hebʹron, and Uzʹzi·el. The length of Koʹhath’s life was 133 years.

[[v2-6-19]]

^<<v2-6-19,19>>^ The sons of Me·rarʹi were Mahʹli and Muʹshi.
These were the families of the Levites, according to their family descents.

[[v2-6-20]]

^<<v2-6-20,20>>^ Now Amʹram took Jochʹe·bed, his father’s sister, as his wife. She bore him Aaron and Moses. The length of Amʹram’s life was 137 years.

[[v2-6-21]]

^<<v2-6-21,21>>^ The sons of Izʹhar were Korʹah, Neʹpheg, and Zichʹri.

[[v2-6-22]]

^<<v2-6-22,22>>^ The sons of Uzʹzi·el were Mishʹa·el, El·zaʹphan, and Sithʹri.

[[v2-6-23]]

^<<v2-6-23,23>>^ Now Aaron took E·liʹshe·ba, Am·minʹa·dab’s daughter, the sister of Nahʹshon, as his wife. She bore him Naʹdab, A·biʹhu, El·e·aʹzar, and Ithʹa·mar.

[[v2-6-24]]

^<<v2-6-24,24>>^ The sons of Korʹah were Asʹsir, El·kaʹnah, and A·biʹa·saph. These were the families of the Korʹah·ites.

[[v2-6-25]]

^<<v2-6-25,25>>^ El·e·aʹzar, Aaron’s son, took one of the daughters of Puʹti·el as his wife. She bore him Phinʹe·has.
These are the heads of the paternal houses of the Levites, according to their families.

[[v2-6-26]]

^<<v2-6-26,26>>^ This is the Aaron and Moses to whom Jehovah said: “Bring the people of Israel out of the land of Egypt, company by company.”^&#42;1^

[NOTE]
====
. Lit., “according to their armies.”
====

[[v2-6-27]]

^<<v2-6-27,27>>^ It was they who spoke to Pharʹaoh, Egypt’s king, to bring the people of Israel out of Egypt. It was this Moses and Aaron.

[[v2-6-28]]

^<<v2-6-28,28>>^ On that day when Jehovah spoke to Moses in the land of Egypt,

[[v2-6-29]]

^<<v2-6-29,29>>^ Jehovah told Moses: “I am Jehovah. Speak to Pharʹaoh, king of Egypt, everything I am speaking to you.”

[[v2-6-30]]

^<<v2-6-30,30>>^ Then Moses said before Jehovah: “Look! I speak with difficulty,^&#42;1^ so how will Pharʹaoh ever listen to me?”

[NOTE]
====
. Lit., “I am uncircumcised in lips.”
====

'''

xref:002-exodus/002-exodus-005.adoc#v2-5-0[&#60; Capítulo Anterior] | <<v2-6-0,Topo>> | xref:002-exodus/002-exodus-007.adoc#v2-7-0[Próximo Capítulo &#62;]