include::./index.adoc[]

[[v2-28-0]]
=== Exodus, 28
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-28-1]]

^<<v2-28-1,1>>^ “You are to summon from the Israelites your brother Aaron, along with his sons, so that he may serve as priest to me—Aaron, along with Naʹdab and A·biʹhu, El·e·aʹzar and Ithʹa·mar, the sons of Aaron.

[[v2-28-2]]

^<<v2-28-2,2>>^ You are to make holy garments for Aaron your brother, for glory and beauty.

[[v2-28-3]]

^<<v2-28-3,3>>^ You are to speak to all those who are skillful,^&#42;1^ those whom I have filled with the spirit of wisdom, and they will make Aaron’s garments for his sanctification, so that he may serve as priest to me.

[NOTE]
====
. Lit., “wise of heart.”
====

[[v2-28-4]]

^<<v2-28-4,4>>^ “These are the garments that they will make: a breastpiece, an ephʹod, a sleeveless coat, a checkered robe, a turban, and a sash; they will make these holy garments for your brother Aaron and his sons, so that he may serve as priest to me.

[[v2-28-5]]

^<<v2-28-5,5>>^ The skilled workers will use the gold, the blue thread, the purple wool, the scarlet material, and the fine linen.

[[v2-28-6]]

^<<v2-28-6,6>>^ “They are to make the ephʹod of gold, blue thread, purple wool, scarlet material, and fine twisted linen, and it should be embroidered.

[[v2-28-7]]

^<<v2-28-7,7>>^ It is to have two shoulder pieces that are joined at the two top edges.

[[v2-28-8]]

^<<v2-28-8,8>>^ The woven belt,^&#42;1^ which is attached to the ephʹod for tying it securely in position, should be of the same materials: gold, blue thread, purple wool, scarlet material, and fine twisted linen.

[NOTE]
====
. Or “waistband.”
====

[[v2-28-9]]

^<<v2-28-9,9>>^ “You are to take two onyx stones and engrave on them the names of the sons of Israel,

[[v2-28-10]]

^<<v2-28-10,10>>^ six names on the one stone and the six remaining names on the other stone, in the order of their births.

[[v2-28-11]]

^<<v2-28-11,11>>^ A stone engraver will engrave the names of the sons of Israel on the two stones as he would engrave a seal. Then you are to have them mounted in gold settings.

[[v2-28-12]]

^<<v2-28-12,12>>^ You are to put the two stones on the shoulder pieces of the ephʹod as memorial stones for the sons of Israel, and Aaron must carry their names before Jehovah on his two shoulder pieces as a memorial.

[[v2-28-13]]

^<<v2-28-13,13>>^ You are to make settings of gold

[[v2-28-14]]

^<<v2-28-14,14>>^ and two chains of pure gold twisted like a cord, and you must attach the corded chains to the settings.

[[v2-28-15]]

^<<v2-28-15,15>>^ “You are to have an embroiderer make the breastpiece of judgment. It should be made like the ephʹod, out of gold, blue thread, purple wool, scarlet material, and fine twisted linen.

[[v2-28-16]]

^<<v2-28-16,16>>^ It should be square when doubled, a span^&#42;1^ long and a span wide.

[NOTE]
====
. That is, the span of the hand, about 22.2 cm (8.75 in.). See App. B14.
====

[[v2-28-17]]

^<<v2-28-17,17>>^ You should set in it mounted stones, four rows of stones. The first row is ruby, topaz, and emerald.

[[v2-28-18]]

^<<v2-28-18,18>>^ The second row is turquoise, sapphire, and jasper.

[[v2-28-19]]

^<<v2-28-19,19>>^ The third row is leshʹem stone,^&#42;1^ agate, and amethyst.

[NOTE]
====
. An unidentified precious stone, possibly referring to amber, hyacinth, opal, or tourmaline.
====

[[v2-28-20]]

^<<v2-28-20,20>>^ The fourth row is chrysʹo·lite, onyx, and jade. They should be mounted in settings of gold.

[[v2-28-21]]

^<<v2-28-21,21>>^ The stones will correspond to the names of the 12 sons of Israel. Each one should be engraved like a seal, each name representing one of the 12 tribes.

[[v2-28-22]]

^<<v2-28-22,22>>^ “You are to make wreathed chains on the breastpiece, like cords of pure gold.

[[v2-28-23]]

^<<v2-28-23,23>>^ You are to make two rings of gold for the breastpiece and attach the two rings to the two ends of the breastpiece.

[[v2-28-24]]

^<<v2-28-24,24>>^ You are to put the two cords of gold through the two rings at the ends of the breastpiece.

[[v2-28-25]]

^<<v2-28-25,25>>^ You will put the two ends of the two cords through the two settings, and you must attach them to the shoulder pieces of the ephʹod, at the front.

[[v2-28-26]]

^<<v2-28-26,26>>^ You are to make two rings of gold and set them at the two ends on the inside edge of the breastpiece, facing the ephʹod.

[[v2-28-27]]

^<<v2-28-27,27>>^ You should make two more rings of gold on the front of the ephʹod, below the two shoulder pieces, close to where it is joined, above the woven belt^&#42;1^ of the ephʹod.

[NOTE]
====
. Or “waistband.”
====

[[v2-28-28]]

^<<v2-28-28,28>>^ The breastpiece should be held in place by a blue cord, tying its rings to the rings of the ephʹod. This will keep the breastpiece in place on the ephʹod, above the woven belt.^&#42;1^

[NOTE]
====
. Or “waistband.”
====

[[v2-28-29]]

^<<v2-28-29,29>>^ “Aaron must carry the names of the sons of Israel on the breastpiece of judgment over his heart when he comes into the Holy as a constant memorial before Jehovah.

[[v2-28-30]]

^<<v2-28-30,30>>^ You will put the Uʹrim and the Thumʹmim^&#42;1^ into the breastpiece of judgment, and they must be over Aaron’s heart when he comes in before Jehovah, and Aaron must carry the means for making judgments of the Israelites over his heart before Jehovah constantly.

[NOTE]
====
. See Glossary.
====

[[v2-28-31]]

^<<v2-28-31,31>>^ “You are to make the sleeveless coat of the ephʹod entirely of blue thread.

[[v2-28-32]]

^<<v2-28-32,32>>^ There will be an opening at the top^&#42;1^ in the middle of it. Its opening should have a border woven all around it by a loom worker. It should be like the opening of a coat of mail, so that it will not be torn.

[NOTE]
====
. Or “for the head.”
====

[[v2-28-33]]

^<<v2-28-33,33>>^ You should make pomegranates of blue thread, purple wool, and scarlet material all around its hem, along with bells of gold in between them.

[[v2-28-34]]

^<<v2-28-34,34>>^ You should alternate a bell of gold and a pomegranate, a bell of gold and a pomegranate, all around the hem of the sleeveless coat.

[[v2-28-35]]

^<<v2-28-35,35>>^ It must be worn by Aaron so that he may minister, and the sound from it must be heard when he goes into the sanctuary before Jehovah and when he comes out, so that he will not die.

[[v2-28-36]]

^<<v2-28-36,36>>^ “You are to make a shining plate of pure gold and engrave on it as one would engrave a seal: ‘Holiness belongs to Jehovah.’

[[v2-28-37]]

^<<v2-28-37,37>>^ You must fasten it to the turban with a blue cord; it is to remain on the front of the turban.

[[v2-28-38]]

^<<v2-28-38,38>>^ It will be on Aaron’s forehead, and Aaron will bear responsibility when someone commits an error against the holy things, which the Israelites sanctify when they offer them as holy gifts. It must always remain on his forehead, so that they may gain approval before Jehovah.

[[v2-28-39]]

^<<v2-28-39,39>>^ “You are to weave the checkered robe of fine linen, make a turban of fine linen, and make a woven sash.

[[v2-28-40]]

^<<v2-28-40,40>>^ “You will also make robes, sashes, and headgear for Aaron’s sons, for glory and beauty.

[[v2-28-41]]

^<<v2-28-41,41>>^ You will clothe your brother Aaron and his sons with him, and you are to anoint them and install them^&#42;1^ and sanctify them, and they will serve as priests to me.

[NOTE]
====
. Lit., “and fill their hand.”
====

[[v2-28-42]]

^<<v2-28-42,42>>^ Also make linen shorts^&#42;1^ for them to cover their naked flesh. These are to extend from the hips to the thighs.

[NOTE]
====
. Or “undergarments.”
====

[[v2-28-43]]

^<<v2-28-43,43>>^ These must be worn by Aaron and his sons when they come into the tent of meeting or when they approach the altar to minister in the holy place, so that they may not incur guilt and die. It is a permanent statute for him and his offspring^&#42;1^ after him.

[NOTE]
====
. Lit., “seed.”
====

'''

xref:002-exodus/002-exodus-027.adoc#v2-27-0[&#60; Capítulo Anterior] | <<v2-28-0,Topo>> | xref:002-exodus/002-exodus-029.adoc#v2-29-0[Próximo Capítulo &#62;]