include::./index.adoc[]

[[v2-1-0]]
=== Exodus, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-1-1]]

^<<v2-1-1,1>>^ Now these are the names of Israel’s sons who came into Egypt with Jacob, each man who came with his household:

[[v2-1-2]]

^<<v2-1-2,2>>^ Reuʹben, Simʹe·on, Leʹvi, and Judah;

[[v2-1-3]]

^<<v2-1-3,3>>^ Isʹsa·char, Zebʹu·lun, and Benjamin;

[[v2-1-4]]

^<<v2-1-4,4>>^ Dan and Naphʹta·li; Gad and Ashʹer.

[[v2-1-5]]

^<<v2-1-5,5>>^ And all those^&#42;1^ who were born to Jacob^&#42;2^ were 70 people,^&#42;3^ but Joseph was already in Egypt.

[NOTE]
====
. Or “the souls.”
. Lit., “who came out from the thigh of Jacob.”
. Or “souls.”
====

[[v2-1-6]]

^<<v2-1-6,6>>^ Joseph eventually died, and also all his brothers and all that generation.

[[v2-1-7]]

^<<v2-1-7,7>>^ And the Israelites^&#42;1^ became fruitful and began to increase greatly, and they kept on multiplying and growing mightier at an extraordinary rate, so that the land became filled with them.

[NOTE]
====
. Lit., “sons of Israel.”
====

[[v2-1-8]]

^<<v2-1-8,8>>^ In time there arose over Egypt a new king, one who did not know Joseph.

[[v2-1-9]]

^<<v2-1-9,9>>^ So he said to his people: “Look! The people of Israel are more numerous and mightier than we are.

[[v2-1-10]]

^<<v2-1-10,10>>^ Let us deal shrewdly with them. Otherwise, they will continue to multiply, and if a war breaks out, they will join our enemies and fight against us and leave the country.”

[[v2-1-11]]

^<<v2-1-11,11>>^ So they appointed chiefs of forced labor^&#42;1^ over them to oppress them with hard labor, and they built storage cities for Pharʹaoh, namely, Piʹthom and Ra·amʹses.

[NOTE]
====
. Or “appointed taskmasters.”
====

[[v2-1-12]]

^<<v2-1-12,12>>^ But the more they would oppress them, the more they would multiply and the more they kept spreading out, so they felt sick with fear because of the Israelites.

[[v2-1-13]]

^<<v2-1-13,13>>^ Consequently, the Egyptians forced the Israelites into harsh slavery.

[[v2-1-14]]

^<<v2-1-14,14>>^ They made their life bitter with hard labor, as they worked with clay mortar and bricks and in every form of slavery in the field. Yes, they made them toil in harsh conditions in every form of slavery.

[[v2-1-15]]

^<<v2-1-15,15>>^ Later the king of Egypt spoke to the Hebrew midwives whose names were Shiphʹrah and Puʹah,

[[v2-1-16]]

^<<v2-1-16,16>>^ and he told them: “When you help the Hebrew women to give birth and you see them on the stool for childbirth,^&#42;1^ you must put the child to death if it is a son; but if it is a daughter, she must live.”

[NOTE]
====
. Or “the birth stool.”
====

[[v2-1-17]]

^<<v2-1-17,17>>^ However, the midwives feared the true God, and they did not do what the king of Egypt told them. Instead, they would keep the male children alive.

[[v2-1-18]]

^<<v2-1-18,18>>^ In time the king of Egypt called the midwives and said to them: “Why have you kept the male children alive?”

[[v2-1-19]]

^<<v2-1-19,19>>^ The midwives said to Pharʹaoh: “The Hebrew women are not like the Egyptian women. They are lively and have already given birth before the midwife can come in to them.”

[[v2-1-20]]

^<<v2-1-20,20>>^ So God dealt well with the midwives, and the people kept increasing and becoming very mighty.

[[v2-1-21]]

^<<v2-1-21,21>>^ And because the midwives had feared the true God, he later gave them families.

[[v2-1-22]]

^<<v2-1-22,22>>^ Finally Pharʹaoh commanded all his people: “You are to throw every newborn son of the Hebrews into the Nile River, but you are to keep every daughter alive.”

'''

xref:001-genesis/001-genesis-050.adoc#v1-50-0[&#60; Capítulo Anterior] | <<v2-1-0,Topo>> | xref:002-exodus/002-exodus-002.adoc#v2-2-0[Próximo Capítulo &#62;]