include::./index.adoc[]

[[v2-9-0]]
=== Exodus, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-9-1]]

^<<v2-9-1,1>>^ So Jehovah said to Moses: “Go in to Pharʹaoh and say to him, ‘This is what Jehovah the God of the Hebrews has said: “Send my people away so that they may serve me.

[[v2-9-2]]

^<<v2-9-2,2>>^ But if you refuse to send them away and you keep holding them,

[[v2-9-3]]

^<<v2-9-3,3>>^ look! Jehovah’s hand will come against your livestock in the field. On the horses, the donkeys, the camels, the herd, and the flock, there will be a devastating plague.

[[v2-9-4]]

^<<v2-9-4,4>>^ And Jehovah will certainly make a distinction between the livestock of Israel and the livestock of Egypt, and nothing that belongs to the Israelites will die.”’”

[[v2-9-5]]

^<<v2-9-5,5>>^ Moreover, Jehovah set an appointed time, saying: “Tomorrow Jehovah will do this in the land.”

[[v2-9-6]]

^<<v2-9-6,6>>^ And Jehovah did this on the very next day, and all sorts of livestock of Egypt began to die, but not one of Israel’s livestock died.

[[v2-9-7]]

^<<v2-9-7,7>>^ When Pharʹaoh inquired, look! not so much as one of Israel’s livestock had died. Nevertheless, Pharʹaoh’s heart continued to be unresponsive, and he did not send the people away.

[[v2-9-8]]

^<<v2-9-8,8>>^ Jehovah then said to Moses and Aaron: “Fill both of your hands with soot from a kiln, and Moses must throw it into the air in front of Pharʹaoh.

[[v2-9-9]]

^<<v2-9-9,9>>^ And it will become a fine dust on all the land of Egypt, and it will become festering boils on man and beast in all the land of Egypt.”

[[v2-9-10]]

^<<v2-9-10,10>>^ So they took soot from a kiln and stood before Pharʹaoh, and Moses tossed it into the air, and it became festering boils breaking out on man and beast.

[[v2-9-11]]

^<<v2-9-11,11>>^ The magic-practicing priests were unable to stand before Moses because of the boils, for they had developed on the magic-practicing priests and on all the Egyptians.

[[v2-9-12]]

^<<v2-9-12,12>>^ But Jehovah allowed Pharʹaoh’s heart to become obstinate, and he did not listen to them, just as Jehovah had told Moses.

[[v2-9-13]]

^<<v2-9-13,13>>^ Then Jehovah said to Moses: “Get up early in the morning and station yourself in front of Pharʹaoh, and say to him, ‘This is what Jehovah the God of the Hebrews has said: “Send my people away so that they may serve me.

[[v2-9-14]]

^<<v2-9-14,14>>^ For now I am directing all my blows to strike your heart, your servants, and your people, so that you may know that there is no one like me in all the earth.

[[v2-9-15]]

^<<v2-9-15,15>>^ For by now I could have thrust my hand out to strike you and your people with a devastating plague, and you would have been wiped out^&#42;1^ from the earth.

[NOTE]
====
. Or “effaced.”
====

[[v2-9-16]]

^<<v2-9-16,16>>^ But for this very reason I have kept you in existence: to show you my power and to have my name declared in all the earth.

[[v2-9-17]]

^<<v2-9-17,17>>^ Are you still behaving arrogantly against my people by not sending them away?

[[v2-9-18]]

^<<v2-9-18,18>>^ Here I will cause a very great hail to rain down tomorrow about this time, such as has never occurred in Egypt from the day it was founded until now.

[[v2-9-19]]

^<<v2-9-19,19>>^ Therefore, send word to bring all your livestock and all that is yours in the field under shelter. Every man and beast caught in the field and not brought into the house will die when the hail comes down on them.”’”

[[v2-9-20]]

^<<v2-9-20,20>>^ Anyone among Pharʹaoh’s servants who feared Jehovah’s word quickly brought his own servants and his livestock into the houses,

[[v2-9-21]]

^<<v2-9-21,21>>^ but whoever did not take Jehovah’s word to heart left his servants and his livestock in the field.

[[v2-9-22]]

^<<v2-9-22,22>>^ Jehovah now said to Moses: “Stretch out your hand toward the heavens, so that hail may come down on all the land of Egypt, on man and beast and all the vegetation of the field in the land of Egypt.”

[[v2-9-23]]

^<<v2-9-23,23>>^ So Moses stretched out his rod toward the heavens, and Jehovah sent thunder and hail, and fire^&#42;1^ fell down to the earth, and Jehovah kept making it rain down hail on the land of Egypt.

[NOTE]
====
. Perhaps describing powerful lightning.
====

[[v2-9-24]]

^<<v2-9-24,24>>^ There was hail, and there was fire flashing in the midst of the hail. It was very heavy; there had never been any like it in the land since Egypt had become a nation.

[[v2-9-25]]

^<<v2-9-25,25>>^ The hail struck everything in the field throughout the land of Egypt, from man to beast, and it struck down all the vegetation and shattered all the trees of the field.

[[v2-9-26]]

^<<v2-9-26,26>>^ Only in the land of Goʹshen, where the Israelites were, there was no hail.

[[v2-9-27]]

^<<v2-9-27,27>>^ So Pharʹaoh sent for Moses and Aaron and said to them: “I have sinned this time. Jehovah is righteous, and I and my people are in the wrong.

[[v2-9-28]]

^<<v2-9-28,28>>^ Plead with Jehovah that there may be an end to God’s thunder and hail. Then I will be willing to send you away, and you will not stay any longer.”

[[v2-9-29]]

^<<v2-9-29,29>>^ So Moses said to him: “As soon as I go out of the city, I will spread out my hands before Jehovah. The thunder will stop and the hail will not continue any longer, so that you may know that the earth belongs to Jehovah.

[[v2-9-30]]

^<<v2-9-30,30>>^ But as for you and your servants, I know already that even then, you will not fear Jehovah God.”

[[v2-9-31]]

^<<v2-9-31,31>>^ Now the flax and the barley had been struck down, because the barley was in the ear and the flax had flower buds.

[[v2-9-32]]

^<<v2-9-32,32>>^ But the wheat and the spelt had not been struck down, because they were later crops.^&#42;1^

[NOTE]
====
. Or “were seasonally late.”
====

[[v2-9-33]]

^<<v2-9-33,33>>^ Moses now went out of the city from Pharʹaoh and spread out his hands before Jehovah, and the thunder and the hail stopped and the rain quit pouring down on the earth.

[[v2-9-34]]

^<<v2-9-34,34>>^ When Pharʹaoh saw that the rain, the hail, and the thunder had stopped, he sinned again and hardened his heart, he as well as his servants.

[[v2-9-35]]

^<<v2-9-35,35>>^ And Pharʹaoh’s heart continued obstinate, and he did not send the Israelites away, just as Jehovah had stated through Moses.

'''

xref:002-exodus/002-exodus-008.adoc#v2-8-0[&#60; Capítulo Anterior] | <<v2-9-0,Topo>> | xref:002-exodus/002-exodus-010.adoc#v2-10-0[Próximo Capítulo &#62;]