include::./index.adoc[]

[[v2-38-0]]
=== Exodus, 38
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-38-1]]

^<<v2-38-1,1>>^ He made the altar of burnt offering out of acacia wood. It was square, five cubits^&#42;1^ long, five cubits wide, and three cubits high.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
====

[[v2-38-2]]

^<<v2-38-2,2>>^ Then he made its horns on its four corners. Its horns were one piece with it. Next he overlaid it with copper.

[[v2-38-3]]

^<<v2-38-3,3>>^ After that he made all the utensils of the altar, the buckets, the shovels, the bowls, the forks, and the fire holders. All its utensils he made of copper.

[[v2-38-4]]

^<<v2-38-4,4>>^ He also made a grating for the altar, a network of copper, under its rim, down toward its center.

[[v2-38-5]]

^<<v2-38-5,5>>^ He cast four rings on the four corners near the grating of copper, as holders for the poles.

[[v2-38-6]]

^<<v2-38-6,6>>^ After that he made the poles of acacia wood and overlaid them with copper.

[[v2-38-7]]

^<<v2-38-7,7>>^ He inserted the poles into the rings on the sides of the altar for carrying it. He made the altar in the form of a hollow chest of planks.

[[v2-38-8]]

^<<v2-38-8,8>>^ Then he made the basin of copper and its copper stand; he used the mirrors^&#42;1^ of the women who were organized to serve at the entrance of the tent of meeting.

[NOTE]
====
. That is, highly polished metal mirrors.
====

[[v2-38-9]]

^<<v2-38-9,9>>^ Then he made the courtyard. For the south side of the courtyard, facing south, he made the hanging curtains of fine twisted linen, for 100 cubits.

[[v2-38-10]]

^<<v2-38-10,10>>^ There were 20 pillars and 20 socket pedestals of copper, and the hooks of the pillars and their connectors^&#42;1^ were of silver.

[NOTE]
====
. Or “rings; hoops; bands” for ­attachments.
====

[[v2-38-11]]

^<<v2-38-11,11>>^ Also, for the north side, there were 100 cubits of hanging curtains. Their 20 pillars and their 20 socket pedestals were of copper. The hooks of the pillars and their connectors^&#42;1^ were of silver.

[NOTE]
====
. Or “rings; hoops; bands” for attachments.
====

[[v2-38-12]]

^<<v2-38-12,12>>^ But for the west side, the hanging curtains were for 50 cubits. There were ten pillars and ten socket pedestals, and the hooks of the pillars and their connectors^&#42;1^ were of silver.

[NOTE]
====
. Or “rings; hoops; bands” for attachments.
====

[[v2-38-13]]

^<<v2-38-13,13>>^ The width of the east side, toward the sunrising, was 50 cubits.

[[v2-38-14]]

^<<v2-38-14,14>>^ There were 15 cubits of hanging curtains on the one wing, with three pillars and three socket pedestals.

[[v2-38-15]]

^<<v2-38-15,15>>^ And for the other wing on the other side of the entrance of the courtyard, there were hanging curtains for 15 cubits, with three pillars and three socket pedestals.

[[v2-38-16]]

^<<v2-38-16,16>>^ All the hanging curtains around the courtyard were of fine twisted linen.

[[v2-38-17]]

^<<v2-38-17,17>>^ The socket pedestals for the pillars were of copper, the hooks of the pillars and their connectors^&#42;1^ were of silver, the tops were overlaid with silver, and there were silver fasteners for all the pillars of the courtyard.

[NOTE]
====
. Or “rings; hoops; bands” for attachments.
====

[[v2-38-18]]

^<<v2-38-18,18>>^ The screen^&#42;1^ of the entrance of the courtyard was woven of blue thread, purple wool, scarlet material, and fine twisted linen. It was 20 cubits long and 5 cubits high, the same height as the hanging curtains of the courtyard.

[NOTE]
====
. Or “curtain.”
====

[[v2-38-19]]

^<<v2-38-19,19>>^ Their four pillars and their four socket pedestals were made of copper. Their hooks and connectors^&#42;1^ were of silver, and their tops were overlaid with silver.

[NOTE]
====
. Or “rings; hoops; bands” for attachments.
====

[[v2-38-20]]

^<<v2-38-20,20>>^ All the tent pins for the tabernacle and around the courtyard were of copper.

[[v2-38-21]]

^<<v2-38-21,21>>^ The following is the inventory of the tabernacle, the tabernacle of the Testimony, which was inventoried at the command of Moses, as the responsibility of the Levites under the direction of Ithʹa·mar the son of Aaron the priest.

[[v2-38-22]]

^<<v2-38-22,22>>^ Bezʹal·el the son of Uʹri the son of Hur of the tribe of Judah did all that Jehovah had commanded Moses.

[[v2-38-23]]

^<<v2-38-23,23>>^ With him was O·hoʹli·ab the son of A·hisʹa·mach of the tribe of Dan, a craftsman and an embroiderer and a weaver of the blue thread, the purple wool, the scarlet material, and the fine linen.

[[v2-38-24]]

^<<v2-38-24,24>>^ All the gold that was used for all the work of the holy place equaled the amount of the gold of the wave offering, 29 talents^&#42;1^ and 730 shekels^&#42;2^ by the standard shekel of the holy place.^&#42;3^

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
. Or “by the holy shekel.”
====

[[v2-38-25]]

^<<v2-38-25,25>>^ And the silver of the ones registered of the assembly was 100 talents and 1,775 shekels by the standard shekel of the holy place.^&#42;1^

[NOTE]
====
. Or “by the holy shekel.”
====

[[v2-38-26]]

^<<v2-38-26,26>>^ The half shekel for each individual was half a shekel by the standard shekel of the holy place^&#42;1^ for every man who was among those registered from 20 years of age and up, amounting to 603,550.

[NOTE]
====
. Or “by the holy shekel.”
====

[[v2-38-27]]

^<<v2-38-27,27>>^ The casting of the socket pedestals of the holy place and the socket pedestals of the curtain amounted to 100 talents; 100 socket pedestals equaled 100 talents, one talent for each socket pedestal.

[[v2-38-28]]

^<<v2-38-28,28>>^ From the 1,775 shekels, he made hooks for the pillars and overlaid their tops and joined them together.

[[v2-38-29]]

^<<v2-38-29,29>>^ The copper of the offering^&#42;1^ was 70 talents and 2,400 shekels.

[NOTE]
====
. Or “wave offering.”
====

[[v2-38-30]]

^<<v2-38-30,30>>^ With this he made the socket pedestals of the entrance of the tent of meeting, the copper altar and its copper grating, all the utensils of the altar,

[[v2-38-31]]

^<<v2-38-31,31>>^ the socket pedestals around the courtyard, the socket pedestals of the entrance of the courtyard, and all the tent pins of the tabernacle and all the tent pins around the courtyard.

'''

xref:002-exodus/002-exodus-037.adoc#v2-37-0[&#60; Capítulo Anterior] | <<v2-38-0,Topo>> | xref:002-exodus/002-exodus-039.adoc#v2-39-0[Próximo Capítulo &#62;]