include::./index.adoc[]

[[v2-32-0]]
=== Exodus, 32
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-32-1]]

^<<v2-32-1,1>>^ Meanwhile, the people saw that Moses was taking a long time coming down from the mountain. So the people gathered around Aaron and said to him: “Get up, make for us a god who will go ahead of us, because we do not know what has happened to this Moses, the man who led us up out of the land of Egypt.”

[[v2-32-2]]

^<<v2-32-2,2>>^ At this Aaron said to them: “Take the gold earrings from the ears of your wives, your sons, and your daughters and bring them to me.”

[[v2-32-3]]

^<<v2-32-3,3>>^ So all the people began taking off the gold earrings that were in their ears and bringing them to Aaron.

[[v2-32-4]]

^<<v2-32-4,4>>^ Then he took the gold from them, and he formed it with an engraving tool and made it into a statue^&#42;1^ of a calf. They began to say: “This is your God, O Israel, who led you up out of the land of Egypt.”

[NOTE]
====
. Or “molten statue.”
====

[[v2-32-5]]

^<<v2-32-5,5>>^ When Aaron saw this, he built an altar before it. Then Aaron called out: “There is a festival to Jehovah tomorrow.”

[[v2-32-6]]

^<<v2-32-6,6>>^ So they got up early on the next day and began offering up burnt offerings and presenting communion sacrifices. After that the people sat down to eat and drink. Then they got up to have a good time.

[[v2-32-7]]

^<<v2-32-7,7>>^ Jehovah now said to Moses: “Go, descend, because your people, whom you led up out of the land of Egypt, have corrupted themselves.

[[v2-32-8]]

^<<v2-32-8,8>>^ They have quickly deviated from the way I commanded them to go. They have made for themselves a statue^&#42;1^ of a calf, and they keep bowing down to it and sacrificing to it and saying, ‘This is your God, O Israel, who led you up out of the land of Egypt.’”

[NOTE]
====
. Or “molten statue.”
====

[[v2-32-9]]

^<<v2-32-9,9>>^ Jehovah went on to say to Moses: “I have seen that this is an obstinate^&#42;1^ people.

[NOTE]
====
. Lit., “stiff-necked.”
====

[[v2-32-10]]

^<<v2-32-10,10>>^ So now let me be, and I will exterminate them in my burning anger, and let me make a great nation from you instead.”

[[v2-32-11]]

^<<v2-32-11,11>>^ Then Moses appealed to^&#42;1^ Jehovah his God and said: “Why, O Jehovah, should you turn your burning anger against your people after bringing them out of the land of Egypt with great power and with a mighty hand?

[NOTE]
====
. Or “softened the face of.”
====

[[v2-32-12]]

^<<v2-32-12,12>>^ Why should the Egyptians say, ‘He had evil intentions when he led them out. He wanted to kill them in the mountains and exterminate them from the surface of the earth’? Turn from your burning anger and reconsider^&#42;1^ your decision to bring this calamity on your people.

[NOTE]
====
. Or “feel regret over.”
====

[[v2-32-13]]

^<<v2-32-13,13>>^ Remember your servants Abraham, Isaac, and Israel, to whom you swore by yourself and said: ‘I will multiply your offspring^&#42;1^ like the stars of the heavens, and I will give all this land that I have designated to your offspring,^&#42;2^ so that they may take it as a permanent possession.’”

[NOTE]
====
. Lit., “seed.”
. Lit., “seed.”
====

[[v2-32-14]]

^<<v2-32-14,14>>^ So Jehovah began to reconsider^&#42;1^ the calamity that he had spoken of bringing on his people.

[NOTE]
====
. Or “felt regret over.”
====

[[v2-32-15]]

^<<v2-32-15,15>>^ Moses then turned and went down from the mountain with the two tablets of the Testimony in his hand. The tablets were inscribed on both sides; they were written on the front and on the back.

[[v2-32-16]]

^<<v2-32-16,16>>^ The tablets were the workmanship of God, and the writing was the writing of God engraved on the tablets.

[[v2-32-17]]

^<<v2-32-17,17>>^ When Joshua began to hear the noise of the people because of their shouting, he said to Moses: “There is the sound of battle in the camp.”

[[v2-32-18]]

^<<v2-32-18,18>>^ But Moses said:
“It is not the sound of singing over a victory,^&#42;1^
And it is not the sound of wailing over a defeat;
I hear the sound of another kind of singing.”

[NOTE]
====
. Or “a mighty act.”
====

[[v2-32-19]]

^<<v2-32-19,19>>^ As soon as Moses got near the camp and saw the calf and the dances, his anger began to blaze, and he threw the tablets from his hands and shattered them at the foot of the mountain.

[[v2-32-20]]

^<<v2-32-20,20>>^ He took the calf that they had made and he burned it with fire and crushed it into powder; then he scattered it on the water and made the Israelites drink it.

[[v2-32-21]]

^<<v2-32-21,21>>^ And Moses said to Aaron: “What did this people do to you that you have brought a great sin upon them?”

[[v2-32-22]]

^<<v2-32-22,22>>^ Aaron replied: “Do not be enraged, my lord. You well know that the people are inclined to do evil.

[[v2-32-23]]

^<<v2-32-23,23>>^ So they said to me, ‘Make for us a god who will go ahead of us, for we do not know what has happened to this Moses, the man who led us up out of the land of Egypt.’

[[v2-32-24]]

^<<v2-32-24,24>>^ So I said to them, ‘Whoever has any gold must take it off and give it to me.’ Then I threw it into the fire and out came this calf.”

[[v2-32-25]]

^<<v2-32-25,25>>^ Moses saw that the people were unrestrained, for Aaron had let them go unrestrained, so that they were a disgrace before their opposers.

[[v2-32-26]]

^<<v2-32-26,26>>^ Then Moses took his position in the gate of the camp and said: “Who is on Jehovah’s side? Come to me!” And all the Levites gathered around him.

[[v2-32-27]]

^<<v2-32-27,27>>^ He now said to them: “This is what Jehovah the God of Israel has said, ‘Each of you must fasten on his sword and pass through all the camp from gate to gate, killing his brother, his neighbor, and his close companion.’”

[[v2-32-28]]

^<<v2-32-28,28>>^ The Levites did what Moses said. So about 3,000 men were killed on that day.

[[v2-32-29]]

^<<v2-32-29,29>>^ Then Moses said: “Set yourselves apart^&#42;1^ for Jehovah today, for each of you has gone against his own son and his own brother; today he will give you a blessing.”

[NOTE]
====
. Lit., “Fill your hand.”
====

[[v2-32-30]]

^<<v2-32-30,30>>^ On the very next day, Moses said to the people: “You committed a very great sin, and now I will go up to Jehovah to see if I can make amends for your sin.”

[[v2-32-31]]

^<<v2-32-31,31>>^ So Moses returned to Jehovah and said: “What a great sin this people has committed! They made themselves a god of gold!

[[v2-32-32]]

^<<v2-32-32,32>>^ But now if you are willing, pardon their sin; if not, please wipe me out from your book that you have written.”

[[v2-32-33]]

^<<v2-32-33,33>>^ However, Jehovah said to Moses: “Whoever has sinned against me, I will wipe him out of my book.

[[v2-32-34]]

^<<v2-32-34,34>>^ Go now, lead the people to the place about which I have spoken to you. Look! My angel will go ahead of you, and on the day when I make an accounting, I will bring punishment on them for their sin.”

[[v2-32-35]]

^<<v2-32-35,35>>^ Then Jehovah began plaguing the people because they had made the calf, the one that Aaron had made.

'''

xref:002-exodus/002-exodus-031.adoc#v2-31-0[&#60; Capítulo Anterior] | <<v2-32-0,Topo>> | xref:002-exodus/002-exodus-033.adoc#v2-33-0[Próximo Capítulo &#62;]