include::./index.adoc[]

[[v2-24-0]]
=== Exodus, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-24-1]]

^<<v2-24-1,1>>^ Then he said to Moses: “Go up to Jehovah, you and Aaron, Naʹdab and A·biʹhu, and 70 of the elders of Israel, and bow down from a distance.

[[v2-24-2]]

^<<v2-24-2,2>>^ Moses should approach Jehovah by himself; but the others should not approach, and the people should not go up with him.”

[[v2-24-3]]

^<<v2-24-3,3>>^ Then Moses came and related to the people all the words of Jehovah and all the judicial decisions, and all the people answered with one voice: “All the words that Jehovah has spoken, we are willing to do.”

[[v2-24-4]]

^<<v2-24-4,4>>^ So Moses wrote down all the words of Jehovah. Then he got up early in the morning and built at the foot of the mountain an altar and 12 pillars corresponding to the 12 tribes of Israel.

[[v2-24-5]]

^<<v2-24-5,5>>^ After that he sent young Israelite men, and they offered up burnt offerings and sacrificed bulls as communion sacrifices to Jehovah.

[[v2-24-6]]

^<<v2-24-6,6>>^ Then Moses took half of the blood and put it in bowls, and half of the blood he sprinkled on the altar.

[[v2-24-7]]

^<<v2-24-7,7>>^ Then he took the book of the covenant and read it aloud to the people. And they said: “All that Jehovah has spoken we are willing to do, and we will be obedient.”

[[v2-24-8]]

^<<v2-24-8,8>>^ So Moses took the blood and sprinkled it on the people and said: “This is the blood of the covenant that Jehovah has made with you in harmony with all these words.”

[[v2-24-9]]

^<<v2-24-9,9>>^ Moses and Aaron, Naʹdab and A·biʹhu, and 70 of the elders of Israel went up,

[[v2-24-10]]

^<<v2-24-10,10>>^ and they saw the God of Israel. Under his feet was what seemed like a sapphire pavement, and it was as pure as the heavens themselves.

[[v2-24-11]]

^<<v2-24-11,11>>^ He did not harm the distinguished men of Israel, and they saw a vision of the true God and ate and drank.

[[v2-24-12]]

^<<v2-24-12,12>>^ Jehovah now said to Moses: “Come up to me on the mountain and stay there. I will give you the stone tablets with the law and the commandment that I will write for their instruction.”

[[v2-24-13]]

^<<v2-24-13,13>>^ So Moses got up with his attendant Joshua, and Moses went up the mountain of the true God.

[[v2-24-14]]

^<<v2-24-14,14>>^ But to the elders he had said: “Wait here for us until we return to you. You have Aaron and Hur with you. Whoever has a legal case may go to them.”

[[v2-24-15]]

^<<v2-24-15,15>>^ Then Moses went up the mountain while the cloud was covering it.

[[v2-24-16]]

^<<v2-24-16,16>>^ Jehovah’s glory remained on Mount Siʹnai, and the cloud covered it for six days. On the seventh day he called to Moses from the midst of the cloud.

[[v2-24-17]]

^<<v2-24-17,17>>^ To the Israelites who were watching, the appearance of Jehovah’s glory was like a consuming fire on the mountaintop.

[[v2-24-18]]

^<<v2-24-18,18>>^ Moses then entered into the cloud and went up the mountain. And Moses stayed on the mountain 40 days and 40 nights.

'''

xref:002-exodus/002-exodus-023.adoc#v2-23-0[&#60; Capítulo Anterior] | <<v2-24-0,Topo>> | xref:002-exodus/002-exodus-025.adoc#v2-25-0[Próximo Capítulo &#62;]