include::./index.adoc[]

[[v2-37-0]]
=== Exodus, 37
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-37-1]]

^<<v2-37-1,1>>^ Bezʹal·el then made the Ark of acacia wood. It was two and a half cubits^&#42;1^ long and a cubit and a half wide and a cubit and a half high.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
====

[[v2-37-2]]

^<<v2-37-2,2>>^ He overlaid it with pure gold inside and outside and made a border^&#42;1^ of gold around it.

[NOTE]
====
. Or “molding.”
====

[[v2-37-3]]

^<<v2-37-3,3>>^ After that he cast four rings of gold for it, for above its four feet, with two rings on its one side and two rings on its other side.

[[v2-37-4]]

^<<v2-37-4,4>>^ He next made poles of acacia wood and overlaid them with gold.

[[v2-37-5]]

^<<v2-37-5,5>>^ Then he put the poles through the rings on the sides of the Ark for carrying the Ark.

[[v2-37-6]]

^<<v2-37-6,6>>^ He made the cover of pure gold. It was two and a half cubits long and a cubit and a half wide.

[[v2-37-7]]

^<<v2-37-7,7>>^ He then made two cherubs of hammered gold on both ends of the cover.

[[v2-37-8]]

^<<v2-37-8,8>>^ One cherub was on one end, and the other cherub on the other end. He made the cherubs on both ends of the cover.

[[v2-37-9]]

^<<v2-37-9,9>>^ The two cherubs spread out their wings upward, overshadowing the cover with their wings. They were facing each other, and their faces were turned toward the cover.

[[v2-37-10]]

^<<v2-37-10,10>>^ He then made the table of acacia wood. It was two cubits long, a cubit wide, and a cubit and a half high.

[[v2-37-11]]

^<<v2-37-11,11>>^ And he overlaid it with pure gold and made a border^&#42;1^ of gold around it.

[NOTE]
====
. Or “molding.”
====

[[v2-37-12]]

^<<v2-37-12,12>>^ Next he made a rim the width of a handbreadth^&#42;1^ to go around it and a border^&#42;2^ of gold to go around the rim.

[NOTE]
====
. About 7.4 cm (2.9 in.). See App. B14.
. Or “molding.”
====

[[v2-37-13]]

^<<v2-37-13,13>>^ Further, he cast four rings of gold for it and placed the rings on the four corners where the four legs were attached.

[[v2-37-14]]

^<<v2-37-14,14>>^ The rings were near the rim, as holders for the poles used for carrying the table.

[[v2-37-15]]

^<<v2-37-15,15>>^ Then he made the poles of acacia wood and overlaid them with gold for carrying the table.

[[v2-37-16]]

^<<v2-37-16,16>>^ After that he made out of pure gold the utensils that went on the table—its dishes, its cups, and its bowls and pitchers from which drink offerings would be poured.

[[v2-37-17]]

^<<v2-37-17,17>>^ Then he made the lampstand of pure gold. He made the lampstand of hammered work. Its base, its stem, its cups, its knobs, and its blossoms were one piece.

[[v2-37-18]]

^<<v2-37-18,18>>^ Six branches were extending out from its stem, three branches of the lampstand from its one side and three branches from its other side.

[[v2-37-19]]

^<<v2-37-19,19>>^ Three cups shaped like almond flowers were on the one set of branches, with knobs and blossoms alternating, and three cups shaped like almond flowers were on the other set of branches, with knobs and blossoms alternating. This was done for the six branches extending out from the stem of the lampstand.

[[v2-37-20]]

^<<v2-37-20,20>>^ And on the stem of the lampstand were four cups shaped like almond flowers, with knobs and blossoms alternating.

[[v2-37-21]]

^<<v2-37-21,21>>^ There was a knob under the first two branches that extended out of the stem and a knob under the next two branches and a knob under the next two branches, for the six branches extending out from the stem of the lampstand.

[[v2-37-22]]

^<<v2-37-22,22>>^ The knobs and the branches and the whole lampstand were made to be one piece of pure, hammered gold.

[[v2-37-23]]

^<<v2-37-23,23>>^ Then he made its seven lamps and its snuffers^&#42;1^ and its fire holders out of pure gold.

[NOTE]
====
. Or “tongs.”
====

[[v2-37-24]]

^<<v2-37-24,24>>^ He made it, along with all its utensils, from a talent^&#42;1^ of pure gold.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v2-37-25]]

^<<v2-37-25,25>>^ He now made the altar of incense out of acacia wood. It was square, a cubit long, a cubit wide, and two cubits high. Its horns were one piece with it.

[[v2-37-26]]

^<<v2-37-26,26>>^ He overlaid it with pure gold, its top surface and its sides all around and its horns, and he made a border^&#42;1^ of gold around it.

[NOTE]
====
. Or “molding.”
====

[[v2-37-27]]

^<<v2-37-27,27>>^ He made two rings of gold for it below its border^&#42;1^ on two opposite sides to hold the poles used for carrying it.

[NOTE]
====
. Or “molding.”
====

[[v2-37-28]]

^<<v2-37-28,28>>^ After that he made the poles of acacia wood and overlaid them with gold.

[[v2-37-29]]

^<<v2-37-29,29>>^ He also made the holy anointing oil and the pure, perfumed incense, skillfully blended.^&#42;1^

[NOTE]
====
. Or “like the work of an ointment maker.”
====

'''

xref:002-exodus/002-exodus-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodus/002-exodus-038.adoc#v2-38-0[Próximo Capítulo &#62;]