include::./index.adoc[]

[[v2-30-0]]
=== Exodus, 30
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-30-1]]

^<<v2-30-1,1>>^ “You are to make an altar as a place for burning incense; you will make it of acacia wood.

[[v2-30-2]]

^<<v2-30-2,2>>^ It should be square, one cubit^&#42;1^ long, one cubit wide, and two cubits high. Its horns will be one piece with it.

[NOTE]
====
. About 44.5 cm (17.5 in.). See App. B14.
====

[[v2-30-3]]

^<<v2-30-3,3>>^ You are to overlay it with pure gold: its top surface, its sides all around, and its horns; and you are to make a gold border^&#42;1^ around it.

[NOTE]
====
. Or “molding.”
====

[[v2-30-4]]

^<<v2-30-4,4>>^ You will also make two rings of gold for it below its border^&#42;1^ on two opposite sides, and these will hold the poles used to carry it.

[NOTE]
====
. Or “molding.”
====

[[v2-30-5]]

^<<v2-30-5,5>>^ Make the poles of acacia wood and overlay them with gold.

[[v2-30-6]]

^<<v2-30-6,6>>^ You are to put it before the curtain that is near the ark of the Testimony, before the cover that is over the Testimony, where I will present myself to you.

[[v2-30-7]]

^<<v2-30-7,7>>^ “Aaron will burn perfumed incense on it, making it smoke on the altar when he maintains the lamps each morning.

[[v2-30-8]]

^<<v2-30-8,8>>^ Also, when Aaron lights the lamps at twilight,^&#42;1^ he will burn the incense. It is a regular incense offering before Jehovah throughout your generations.

[NOTE]
====
. Lit., “between the two evenings.”
====

[[v2-30-9]]

^<<v2-30-9,9>>^ You must not offer on it unauthorized incense or a burnt offering or a grain offering, and you must not pour a drink offering on it.

[[v2-30-10]]

^<<v2-30-10,10>>^ Aaron must make atonement on its horns once a year. With some of the blood of the sin offering of the atonement, he will make atonement for it once a year throughout your generations. It is most holy to Jehovah.”

[[v2-30-11]]

^<<v2-30-11,11>>^ Then Jehovah said to Moses:

[[v2-30-12]]

^<<v2-30-12,12>>^ “Whenever you take a census and count the sons of Israel, each one must give a ransom for his life^&#42;1^ to Jehovah at the time of the census. This is so that no plague may be brought upon them when they are registered.

[NOTE]
====
. Or “soul.”
====

[[v2-30-13]]

^<<v2-30-13,13>>^ This is what all those who are registered will give: a half shekel^&#42;1^ by the standard shekel of the holy place.^&#42;2^ Twenty geʹrahs^&#42;3^ equal a shekel. A half shekel is the contribution to Jehovah.

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
. Or “by the holy shekel.”
. A gerah equaled 0.57 g (0.01835 oz t). See App. B14.
====

[[v2-30-14]]

^<<v2-30-14,14>>^ Everyone registered who is 20 years old and up will give Jehovah’s contribution.

[[v2-30-15]]

^<<v2-30-15,15>>^ The rich should not give more and the poor should not give less than the half shekel^&#42;1^ as a contribution to Jehovah to make atonement for your lives.^&#42;2^

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
. Or “souls.”
====

[[v2-30-16]]

^<<v2-30-16,16>>^ You are to take the silver money of the atonement from the Israelites and give it in behalf of the service of the tent of meeting, that it may serve as a remembrance before Jehovah for the Israelites, to make atonement for your lives.”^&#42;1^

[NOTE]
====
. Or “souls.”
====

[[v2-30-17]]

^<<v2-30-17,17>>^ Jehovah spoke further to Moses, saying:

[[v2-30-18]]

^<<v2-30-18,18>>^ “Make a copper basin and its stand for washing; then place it between the tent of meeting and the altar and put water into it.

[[v2-30-19]]

^<<v2-30-19,19>>^ Aaron and his sons will wash their hands and their feet there.

[[v2-30-20]]

^<<v2-30-20,20>>^ When they go into the tent of meeting or when they approach the altar to minister and to make offerings of fire and smoke to Jehovah, they will wash with water so that they do not die.

[[v2-30-21]]

^<<v2-30-21,21>>^ They must wash their hands and their feet so that they may not die, and it must serve as a permanent regulation for them, for him and his offspring, throughout their generations.”

[[v2-30-22]]

^<<v2-30-22,22>>^ Jehovah continued to speak to Moses:

[[v2-30-23]]

^<<v2-30-23,23>>^ “Next, take the choicest perfumes: 500 units of solidified myrrh, and half that amount, 250 units, of sweet cinnamon, 250 units of sweet calamus,

[[v2-30-24]]

^<<v2-30-24,24>>^ and 500 units of cassia, measured by the standard shekel of the holy place,^&#42;1^ along with a hin^&#42;2^ of olive oil.

[NOTE]
====
. Or “by the holy shekel.”
. A hin equaled 3.67 L (7.75 pt). See App. B14.
====

[[v2-30-25]]

^<<v2-30-25,25>>^ Then make out of it a holy anointing oil; it should be skillfully blended together.^&#42;1^ It is to be a holy anointing oil.

[NOTE]
====
. Or “like the work of an ointment maker.”
====

[[v2-30-26]]

^<<v2-30-26,26>>^ “You are to anoint the tent of meeting and the ark of the Testimony with it,

[[v2-30-27]]

^<<v2-30-27,27>>^ as well as the table and all its utensils, the lampstand and its utensils, the altar of incense,

[[v2-30-28]]

^<<v2-30-28,28>>^ the altar of burnt offering and all its utensils, and the basin and its stand.

[[v2-30-29]]

^<<v2-30-29,29>>^ You must sanctify them that they may become most holy. Anyone touching them is to be holy.

[[v2-30-30]]

^<<v2-30-30,30>>^ And you will anoint Aaron and his sons and sanctify them to serve as priests to me.

[[v2-30-31]]

^<<v2-30-31,31>>^ “You will speak to the Israelites, saying, ‘This is to continue as a holy anointing oil to me during your generations.

[[v2-30-32]]

^<<v2-30-32,32>>^ It is not to be applied to the flesh of mankind, and you must not make anything with a composition like it. It is something holy. It is to continue as something holy for you.

[[v2-30-33]]

^<<v2-30-33,33>>^ Anyone who makes an ointment like it and who puts some of it on an unauthorized person^&#42;1^ must be cut off^&#42;2^ from his people.’”

[NOTE]
====
. Lit., “a stranger,” that is, a man not of Aaron’s family.
. Or “put to death.”
====

[[v2-30-34]]

^<<v2-30-34,34>>^ Then Jehovah said to Moses: “Take equal portions of these perfumes: stacte drops, onycha, perfumed galbanum, and pure frankincense.

[[v2-30-35]]

^<<v2-30-35,35>>^ Make it into an incense; the spice mixture should be skillfully blended,^&#42;1^ salted, pure, and holy.

[NOTE]
====
. Or “like the work of an ointment maker.”
====

[[v2-30-36]]

^<<v2-30-36,36>>^ You are to pound some of it into fine powder and put some of it before the Testimony in the tent of meeting, where I will present myself to you. It should be most holy to you.

[[v2-30-37]]

^<<v2-30-37,37>>^ You must not make for your own use the incense that you make with this composition. You are to regard it as something holy to Jehovah.

[[v2-30-38]]

^<<v2-30-38,38>>^ Whoever makes any like it to enjoy its smell must be cut off^&#42;1^ from his people.”

[NOTE]
====
. Or “put to death.”
====

'''

xref:002-exodus/002-exodus-029.adoc#v2-29-0[&#60; Capítulo Anterior] | <<v2-30-0,Topo>> | xref:002-exodus/002-exodus-031.adoc#v2-31-0[Próximo Capítulo &#62;]