include::./index.adoc[]

[[v2-23-0]]
=== Exodus, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-23-1]]

^<<v2-23-1,1>>^ “You must not spread^&#42;1^ a report that is not true. Do not cooperate with a wicked one by becoming a malicious witness.

[NOTE]
====
. Lit., “take up.”
====

[[v2-23-2]]

^<<v2-23-2,2>>^ You must not follow after the crowd to do evil, and you must not pervert justice by giving testimony to go along with the crowd.^&#42;1^

[NOTE]
====
. Or “testimony that is popular.”
====

[[v2-23-3]]

^<<v2-23-3,3>>^ You must show impartiality in the dispute of a poor person.

[[v2-23-4]]

^<<v2-23-4,4>>^ “If you come upon your enemy’s bull or his donkey straying, you must return it to him.

[[v2-23-5]]

^<<v2-23-5,5>>^ If you see that the donkey of someone who hates you has fallen under its load, you must not ignore it and leave. You must help him release the animal.

[[v2-23-6]]

^<<v2-23-6,6>>^ “You are not to pervert the judgment of the poor one among you in his legal case.

[[v2-23-7]]

^<<v2-23-7,7>>^ “Have nothing to do with a false accusation,^&#42;1^ and do not kill the innocent and the righteous, for I will not declare the wicked one righteous.^&#42;2^

[NOTE]
====
. Lit., “word.”
. Or “acquit the wicked one.”
====

[[v2-23-8]]

^<<v2-23-8,8>>^ “You must not accept a bribe, for the bribe blinds clear-sighted men and can distort the words of righteous men.

[[v2-23-9]]

^<<v2-23-9,9>>^ “You must not oppress a foreign resident. You know how it feels to be a foreigner,^&#42;1^ because you were foreign residents in the land of Egypt.

[NOTE]
====
. Or “know the life (soul) of a foreigner.”
====

[[v2-23-10]]

^<<v2-23-10,10>>^ “You are to sow your land with seed and gather its produce for six years.

[[v2-23-11]]

^<<v2-23-11,11>>^ But the seventh year you should leave it uncultivated and let it lie fallow, and the poor among your people will eat of it, and what they leave, the wild animals of the field will eat. That is what you should do with your vineyard and your olive grove.

[[v2-23-12]]

^<<v2-23-12,12>>^ “Six days you are to do your work; but on the seventh day, you are to cease from your labor, in order that your bull and your donkey may rest and the son of your slave girl and the foreign resident may refresh themselves.

[[v2-23-13]]

^<<v2-23-13,13>>^ “You must be careful to do all that I have said to you, and you must not mention the names of other gods; they should not be heard on your lips.^&#42;1^

[NOTE]
====
. Lit., “mouth.”
====

[[v2-23-14]]

^<<v2-23-14,14>>^ “Three times a year you are to celebrate a festival to me.

[[v2-23-15]]

^<<v2-23-15,15>>^ You will observe the Festival of Unleavened Bread. You will eat unleavened bread for seven days, just as I have commanded you, at the appointed time in the month of Aʹbib,^&#42;1^ for at that time you came out of Egypt. No one is to appear before me empty-handed.

[NOTE]
====
. See App. B15.
====

[[v2-23-16]]

^<<v2-23-16,16>>^ Also, you are to observe the Festival of Harvest^&#42;1^ of the first ripe fruits of your labors, of what you sow in the field; and the Festival of Ingathering^&#42;2^ at the end of the year, when you gather in from the field the results of your labors.

[NOTE]
====
. Also known as the Festival of Weeks, or Pentecost.
. Also known as the Festival of Booths (Tabernacles).
====

[[v2-23-17]]

^<<v2-23-17,17>>^ Three times a year all your men^&#42;1^ are to appear before the true Lord, Jehovah.

[NOTE]
====
. Or “males.”
====

[[v2-23-18]]

^<<v2-23-18,18>>^ “You must not offer the blood of my sacrifice with anything leavened. And the sacrifices of fat offered at my festivals should not stay overnight until the morning.

[[v2-23-19]]

^<<v2-23-19,19>>^ “You are to bring the best of the first ripe fruits of your ground to the house of Jehovah your God.
“You must not boil a young goat in its mother’s milk.

[[v2-23-20]]

^<<v2-23-20,20>>^ “I am sending an angel ahead of you to guard you on the way and to bring you into the place that I have prepared.

[[v2-23-21]]

^<<v2-23-21,21>>^ Pay attention to him, and obey his voice. Do not rebel against him, for he will not pardon your transgressions, because my name is in him.

[[v2-23-22]]

^<<v2-23-22,22>>^ However, if you strictly obey his voice and do all that I say, I will show hostility to your enemies and oppose those who oppose you.

[[v2-23-23]]

^<<v2-23-23,23>>^ For my angel will go ahead of you and will bring you to the Amʹor·ites, the Hitʹtites, the Perʹiz·zites, the Caʹnaan·ites, the Hiʹvites, and the Jebʹu·sites, and I will annihilate them.

[[v2-23-24]]

^<<v2-23-24,24>>^ You must not bow down to their gods or be persuaded to serve them, and you must not imitate their practices. Instead, you must demolish them and smash their sacred pillars.

[[v2-23-25]]

^<<v2-23-25,25>>^ You must serve Jehovah your God, and he will bless your bread and your water. I will remove sickness from among you.

[[v2-23-26]]

^<<v2-23-26,26>>^ The women in your land will not suffer a miscarriage or be barren, and I will give you a full life span.^&#42;1^

[NOTE]
====
. Or “I will make the number of your days full.”
====

[[v2-23-27]]

^<<v2-23-27,27>>^ “I will send the fear of me ahead of you, and I will throw into confusion all the people you encounter, and I will cause all your enemies to flee from you in defeat.^&#42;1^

[NOTE]
====
. Or “I will make all your enemies turn their back to you.”
====

[[v2-23-28]]

^<<v2-23-28,28>>^ I will send the feeling of dejection^&#42;1^ ahead of you, and it will drive the Hiʹvites, the Caʹnaan·ites, and the Hitʹtites out from before you.

[NOTE]
====
. Or possibly, “panic; terror.”
====

[[v2-23-29]]

^<<v2-23-29,29>>^ I will not drive them out from before you in one year, so that the land does not become desolate and the wild animals of the field multiply against you.

[[v2-23-30]]

^<<v2-23-30,30>>^ Little by little I will drive them out from before you, until you become fruitful and take possession of the land.

[[v2-23-31]]

^<<v2-23-31,31>>^ “I will set your boundary from the Red Sea to the sea of the Phi·lisʹtines and from the wilderness to the River;^&#42;1^ for I will give the inhabitants of the land into your hand, and you will drive them out from before you.

[NOTE]
====
. That is, the Euphrates.
====

[[v2-23-32]]

^<<v2-23-32,32>>^ You must not make a covenant with them or their gods.

[[v2-23-33]]

^<<v2-23-33,33>>^ They should not dwell in your land, so that they may not cause you to sin against me. If you should serve their gods, it would surely become a snare to you.”

'''

xref:002-exodus/002-exodus-022.adoc#v2-22-0[&#60; Capítulo Anterior] | <<v2-23-0,Topo>> | xref:002-exodus/002-exodus-024.adoc#v2-24-0[Próximo Capítulo &#62;]