include::./index.adoc[]

[[v2-18-0]]
=== Exodus, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-18-1]]

^<<v2-18-1,1>>^ Now Jethʹro the priest of Midʹi·an, Moses’ father-in-law, heard about all that God had done for Moses and for his people Israel, how Jehovah had brought Israel out of Egypt.

[[v2-18-2]]

^<<v2-18-2,2>>^ Jethʹro, Moses’ father-in-law, had taken in Zip·poʹrah, Moses’ wife, when she was sent back to him,

[[v2-18-3]]

^<<v2-18-3,3>>^ along with her two sons. One son was named Gerʹshom,^&#42;1^ because Moses said, “I have become a foreign resident in a foreign land,”

[NOTE]
====
. Meaning “A Foreign Resident There.”
====

[[v2-18-4]]

^<<v2-18-4,4>>^ and the other was named E·li·eʹzer,^&#42;1^ because he said, “The God of my father is my helper, who rescued me from Pharʹaoh’s sword.”

[NOTE]
====
. Meaning “My God Is Helper.”
====

[[v2-18-5]]

^<<v2-18-5,5>>^ So Jethʹro, Moses’ father-in-law, along with Moses’ sons and his wife, came to Moses into the wilderness where he was camping at the mountain of the true God.

[[v2-18-6]]

^<<v2-18-6,6>>^ Then he sent word to Moses: “I, your father-in-law Jethʹro, am coming to you with your wife and her two sons.”

[[v2-18-7]]

^<<v2-18-7,7>>^ At once Moses went out to meet his father-in-law, and he bowed down and kissed him. Each of them asked about the other’s welfare, and then they went into the tent.

[[v2-18-8]]

^<<v2-18-8,8>>^ Moses related to his father-in-law all that Jehovah had done to Pharʹaoh and Egypt in behalf of Israel, all the hardships that had befallen them along the way, and how Jehovah had delivered them.

[[v2-18-9]]

^<<v2-18-9,9>>^ Jethʹro rejoiced over all the good that Jehovah had done for Israel by rescuing them from Egypt.^&#42;1^

[NOTE]
====
. Lit., “from the hand of Egypt.”
====

[[v2-18-10]]

^<<v2-18-10,10>>^ Then Jethʹro said: “Praised be Jehovah, who rescued you from Egypt and from Pharʹaoh, and who rescued the people from under Egypt’s control.

[[v2-18-11]]

^<<v2-18-11,11>>^ Now I know that Jehovah is greater than all the other gods, because of what he did to those who acted arrogantly against his people.”

[[v2-18-12]]

^<<v2-18-12,12>>^ Then Jethʹro, Moses’ father-in-law, brought a burnt offering and sacrifices for God, and Aaron and all the elders of Israel came to eat a meal with Moses’ father-in-law before the true God.

[[v2-18-13]]

^<<v2-18-13,13>>^ On the next day, Moses sat down as usual to serve as judge for the people, and the people kept standing before Moses from morning until evening.

[[v2-18-14]]

^<<v2-18-14,14>>^ When Moses’ father-in-law saw all that he was doing for the people, he said: “What is this that you are doing for the people? Why do you sit here alone with all the people standing before you from morning until evening?”

[[v2-18-15]]

^<<v2-18-15,15>>^ Moses said to his father-in-law: “Because the people keep coming to me to inquire of God.

[[v2-18-16]]

^<<v2-18-16,16>>^ When a case arises, it comes to me and I must judge between one person and the other, and I make known the decisions of the true God and his laws.”

[[v2-18-17]]

^<<v2-18-17,17>>^ Moses’ father-in-law said to him: “What you are doing is not good.

[[v2-18-18]]

^<<v2-18-18,18>>^ You will surely wear out, both you and this people who are with you, because this is too big a load for you and you cannot carry it by yourself.

[[v2-18-19]]

^<<v2-18-19,19>>^ Now listen to me. I will give you advice, and God will be with you. You serve as representative for the people before the true God, and you must bring the cases to the true God.

[[v2-18-20]]

^<<v2-18-20,20>>^ You should warn them about what the regulations and the laws are and make known to them the way in which they should walk and the work that they should do.

[[v2-18-21]]

^<<v2-18-21,21>>^ But you should select from the people capable men fearing God, trustworthy men hating dishonest profit, and appoint these over them as chiefs over thousands, chiefs over hundreds, chiefs over fifties, and chiefs over tens.

[[v2-18-22]]

^<<v2-18-22,22>>^ They should judge the people when cases arise,^&#42;1^ and they will bring every difficult case to you, but every minor case they will decide. Make it easier for yourself by letting them share the load along with you.

[NOTE]
====
. Lit., “in every time.”
====

[[v2-18-23]]

^<<v2-18-23,23>>^ If you do this, and God so commands you, you will be able to stand the strain, and everyone will go home satisfied.”

[[v2-18-24]]

^<<v2-18-24,24>>^ Moses immediately listened to his father-in-law and did all that he had said.

[[v2-18-25]]

^<<v2-18-25,25>>^ Moses chose capable men out of all Israel and appointed them heads over the people, as chiefs of thousands, chiefs of hundreds, chiefs of fifties, and chiefs of tens.

[[v2-18-26]]

^<<v2-18-26,26>>^ So they judged the people when cases arose. A difficult case they would bring to Moses, but every minor case they would judge.

[[v2-18-27]]

^<<v2-18-27,27>>^ After that Moses saw his father-in-law off, and he went his way to his land.

'''

xref:002-exodus/002-exodus-017.adoc#v2-17-0[&#60; Capítulo Anterior] | <<v2-18-0,Topo>> | xref:002-exodus/002-exodus-019.adoc#v2-19-0[Próximo Capítulo &#62;]