include::./index.adoc[]

[[v2-16-0]]
=== Exodus, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-16-1]]

^<<v2-16-1,1>>^ After they departed from Eʹlim, the entire assembly of the Israelites eventually came to the wilderness of Sin, which is between Eʹlim and Siʹnai, on the 15th day of the second month after their departure from the land of Egypt.

[[v2-16-2]]

^<<v2-16-2,2>>^ Then the entire assembly of the Israelites began to murmur against Moses and Aaron in the wilderness.

[[v2-16-3]]

^<<v2-16-3,3>>^ The Israelites kept saying to them: “If only we had died by Jehovah’s hand in the land of Egypt while we were sitting by the pots of meat, while we were eating bread to satisfaction. Now you have brought us out into this wilderness to put this whole congregation to death by famine.”

[[v2-16-4]]

^<<v2-16-4,4>>^ Then Jehovah said to Moses: “Here I am raining down bread for you from the heavens, and each of the people should go out to gather his amount day by day, so that I may put them to the test to see whether they will walk in my law or not.

[[v2-16-5]]

^<<v2-16-5,5>>^ But on the sixth day when they prepare what they have gathered, it is to be double the amount that they pick up on each of the other days.”

[[v2-16-6]]

^<<v2-16-6,6>>^ So Moses and Aaron said to all the Israelites: “In the evening you will certainly know that it is Jehovah who brought you out of the land of Egypt.

[[v2-16-7]]

^<<v2-16-7,7>>^ In the morning you will see Jehovah’s glory, for he has heard your murmurings against Jehovah. Who are we that you should murmur against us?”

[[v2-16-8]]

^<<v2-16-8,8>>^ Moses continued: “When Jehovah gives you meat to eat in the evening and in the morning bread to satisfaction, you will see that Jehovah has heard your murmurings that you are murmuring against him. But who are we? Your murmurings are not against us, but against Jehovah.”

[[v2-16-9]]

^<<v2-16-9,9>>^ Then Moses said to Aaron: “Tell the entire assembly of the Israelites, ‘Come near before Jehovah, for he has heard your murmurings.’”

[[v2-16-10]]

^<<v2-16-10,10>>^ As soon as Aaron had spoken to the entire assembly of the Israelites, they turned and faced toward the wilderness, and look! Jehovah’s glory appeared in the cloud.

[[v2-16-11]]

^<<v2-16-11,11>>^ Jehovah spoke further to Moses, saying:

[[v2-16-12]]

^<<v2-16-12,12>>^ “I have heard the murmurings of the Israelites. Tell them, ‘At twilight^&#42;1^ you will eat meat, and in the morning you will be satisfied with bread, and you will certainly know that I am Jehovah your God.’”

[NOTE]
====
. Lit., “Between the two evenings.”
====

[[v2-16-13]]

^<<v2-16-13,13>>^ So that evening quail came and covered the camp, and in the morning a layer of dew was all around the camp.

[[v2-16-14]]

^<<v2-16-14,14>>^ When the layer of dew evaporated, there was a fine, flaky substance on the surface of the wilderness, as fine as frost on the ground.

[[v2-16-15]]

^<<v2-16-15,15>>^ When the Israelites saw it, they began to say to one another, “What is it?” for they did not know what it was. Moses said to them: “It is the bread that Jehovah has given you for food.

[[v2-16-16]]

^<<v2-16-16,16>>^ This is what Jehovah has commanded, ‘Each one should gather it according to how much he can eat. You are to take an omer measure^&#42;1^ for each individual according to the number of the people^&#42;2^ that each of you has in his tent.’”

[NOTE]
====
. About 2.2 L (2 dry qt). See App. B14.
. Or “souls.”
====

[[v2-16-17]]

^<<v2-16-17,17>>^ The Israelites began to do so; they gathered it, some gathering much and some gathering little.

[[v2-16-18]]

^<<v2-16-18,18>>^ When they would measure it by the omer, the one who had gathered much had no surplus and the one who had gathered little had no shortage. They each gathered it according to what they could eat.

[[v2-16-19]]

^<<v2-16-19,19>>^ Then Moses said to them: “Nobody should leave any of it until the morning.”

[[v2-16-20]]

^<<v2-16-20,20>>^ But they did not listen to Moses. When some men left some of it until the morning, it bred worms and stank, and Moses became indignant at them.

[[v2-16-21]]

^<<v2-16-21,21>>^ They would pick it up morning by morning, each one according to what he could eat. When the sun got hot, it melted.

[[v2-16-22]]

^<<v2-16-22,22>>^ On the sixth day, they picked up twice as much bread, two omer measures for each person. So all the chieftains of the assembly came and reported it to Moses.

[[v2-16-23]]

^<<v2-16-23,23>>^ At that he said to them: “It is what Jehovah has said. Tomorrow there will be a complete rest,^&#42;1^ a holy sabbath to Jehovah. Bake what you need to bake, and boil what you need to boil; then save whatever is left over and keep it until the morning.”

[NOTE]
====
. Or “a sabbath observance.”
====

[[v2-16-24]]

^<<v2-16-24,24>>^ So they saved it until the morning, just as Moses had commanded, and it did not stink nor were there maggots in it.

[[v2-16-25]]

^<<v2-16-25,25>>^ Then Moses said: “Eat it today, because today is a sabbath to Jehovah. Today you will not find it on the ground.

[[v2-16-26]]

^<<v2-16-26,26>>^ You will pick it up for six days, but on the seventh day, the Sabbath, there will be none.”

[[v2-16-27]]

^<<v2-16-27,27>>^ However, some of the people did go out to pick it up on the seventh day, but they found nothing.

[[v2-16-28]]

^<<v2-16-28,28>>^ So Jehovah said to Moses: “How long will you refuse to keep my commandments and my laws?

[[v2-16-29]]

^<<v2-16-29,29>>^ Take notice of the fact that Jehovah has given you the Sabbath. That is why he is giving you the bread for two days on the sixth day. Everyone must stay where he is; nobody is to leave his locality on the seventh day.”

[[v2-16-30]]

^<<v2-16-30,30>>^ So the people observed the Sabbath^&#42;1^ on the seventh day.

[NOTE]
====
. Or “rested.”
====

[[v2-16-31]]

^<<v2-16-31,31>>^ The house of Israel named the bread “manna.”^&#42;1^ It was white like coriander seed, and its taste was like that of flat cakes with honey.

[NOTE]
====
. Probably from the Hebrew expression “What is it?”
====

[[v2-16-32]]

^<<v2-16-32,32>>^ Then Moses said: “This is what Jehovah has commanded, ‘Fill an omer measure of it as something to be kept throughout your generations, so that they may see the bread that I gave you to eat in the wilderness when I was bringing you out of the land of Egypt.’”

[[v2-16-33]]

^<<v2-16-33,33>>^ So Moses said to Aaron: “Take a jar and put in it an omer measure of manna and deposit it before Jehovah as something to be kept throughout your generations.”

[[v2-16-34]]

^<<v2-16-34,34>>^ Just as Jehovah commanded Moses, Aaron placed it before the Testimony so that it might be preserved.

[[v2-16-35]]

^<<v2-16-35,35>>^ The Israelites ate the manna for 40 years, until they came to a land that was inhabited. They ate the manna until they came to the frontier of the land of Caʹnaan.

[[v2-16-36]]

^<<v2-16-36,36>>^ Now an omer is a tenth of an eʹphah measure.^&#42;1^

[NOTE]
====
. An ephah equaled 22 L (20 dry qt). See App. B14.
====

'''

xref:002-exodus/002-exodus-015.adoc#v2-15-0[&#60; Capítulo Anterior] | <<v2-16-0,Topo>> | xref:002-exodus/002-exodus-017.adoc#v2-17-0[Próximo Capítulo &#62;]