include::./index.adoc[]

[[v2-40-0]]
=== Exodus, 40
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-40-1]]

^<<v2-40-1,1>>^ Then Jehovah said to Moses:

[[v2-40-2]]

^<<v2-40-2,2>>^ “On the first day of the first month, you are to set up the tabernacle, the tent of meeting.

[[v2-40-3]]

^<<v2-40-3,3>>^ Place the ark of the Testimony in it, and screen off the Ark with the curtain.

[[v2-40-4]]

^<<v2-40-4,4>>^ You are to bring the table in and arrange the things that belong on it and bring in the lampstand and light its lamps.

[[v2-40-5]]

^<<v2-40-5,5>>^ Then put the golden altar for incense before the ark of the Testimony and put the screen^&#42;1^ for the entrance of the tabernacle in place.

[NOTE]
====
. Or “curtain.”
====

[[v2-40-6]]

^<<v2-40-6,6>>^ “You are to put the altar of burnt offering before the entrance of the tabernacle, the tent of meeting,

[[v2-40-7]]

^<<v2-40-7,7>>^ and place the basin between the tent of meeting and the altar and put water in it.

[[v2-40-8]]

^<<v2-40-8,8>>^ Then set up the courtyard around it and put up the screen^&#42;1^ for the entrance of the courtyard.

[NOTE]
====
. Or “curtain.”
====

[[v2-40-9]]

^<<v2-40-9,9>>^ Next you are to take the anointing oil and anoint the tabernacle and all that is in it, and sanctify it and all its utensils, so that it will become something holy.

[[v2-40-10]]

^<<v2-40-10,10>>^ You are to anoint the altar of burnt offering and all its utensils and sanctify the altar, so that it will become a most holy altar.

[[v2-40-11]]

^<<v2-40-11,11>>^ And anoint the basin and its stand and sanctify it.

[[v2-40-12]]

^<<v2-40-12,12>>^ “Then bring Aaron and his sons near to the entrance of the tent of meeting, and wash them with water.

[[v2-40-13]]

^<<v2-40-13,13>>^ And you are to clothe Aaron with the holy garments and anoint him and sanctify him, and he will serve as priest to me.

[[v2-40-14]]

^<<v2-40-14,14>>^ After that bring his sons near, and clothe them with robes.

[[v2-40-15]]

^<<v2-40-15,15>>^ You are to anoint them just as you anointed their father, so that they will serve as priests to me, and their anointing will serve continually for them as a lasting priesthood during their generations.”

[[v2-40-16]]

^<<v2-40-16,16>>^ Moses did according to all that Jehovah had commanded him. He did just so.

[[v2-40-17]]

^<<v2-40-17,17>>^ In the first month, in the second year, on the first day of the month, the tabernacle was set up.

[[v2-40-18]]

^<<v2-40-18,18>>^ When Moses set up the tabernacle, he put its socket pedestals down, set up the panel frames, put its bars in, and set up its pillars.

[[v2-40-19]]

^<<v2-40-19,19>>^ He spread out the tent over the tabernacle and placed the covering of the tent over it, just as Jehovah had commanded Moses.

[[v2-40-20]]

^<<v2-40-20,20>>^ After that he took the Testimony and put it into the Ark and placed the poles on the Ark and put the cover on the Ark.

[[v2-40-21]]

^<<v2-40-21,21>>^ He brought the Ark into the tabernacle and put the curtain of the screen in place and screened off the ark of the Testimony, just as Jehovah had commanded Moses.

[[v2-40-22]]

^<<v2-40-22,22>>^ Next he put the table in the tent of meeting on the north side of the tabernacle outside the curtain,

[[v2-40-23]]

^<<v2-40-23,23>>^ and he arranged the row of bread on it before Jehovah, just as Jehovah had commanded Moses.

[[v2-40-24]]

^<<v2-40-24,24>>^ He placed the lampstand in the tent of meeting in front of the table, on the south side of the tabernacle.

[[v2-40-25]]

^<<v2-40-25,25>>^ He lit the lamps before Jehovah, just as Jehovah had commanded Moses.

[[v2-40-26]]

^<<v2-40-26,26>>^ He next placed the golden altar in the tent of meeting before the curtain,

[[v2-40-27]]

^<<v2-40-27,27>>^ in order to make perfumed incense smoke on it, just as Jehovah had commanded Moses.

[[v2-40-28]]

^<<v2-40-28,28>>^ Then he put the screen^&#42;1^ for the entrance of the tabernacle in place.

[NOTE]
====
. Or “curtain.”
====

[[v2-40-29]]

^<<v2-40-29,29>>^ He placed the altar of burnt offering at the entrance of the tabernacle, the tent of meeting, so that he might offer up the burnt offering and the grain offering on it, just as Jehovah had commanded Moses.

[[v2-40-30]]

^<<v2-40-30,30>>^ He then placed the basin between the tent of meeting and the altar and put water in it for washing.

[[v2-40-31]]

^<<v2-40-31,31>>^ Moses and Aaron and his sons washed their hands and their feet at it.

[[v2-40-32]]

^<<v2-40-32,32>>^ Whenever they went into the tent of meeting or approached the altar, they would wash, just as Jehovah had commanded Moses.

[[v2-40-33]]

^<<v2-40-33,33>>^ Finally he set up the courtyard around the tabernacle and the altar and put up the screen^&#42;1^ for the entrance of the courtyard.
So Moses finished the work.

[NOTE]
====
. Or “curtain.”
====

[[v2-40-34]]

^<<v2-40-34,34>>^ And the cloud began to cover the tent of meeting, and Jehovah’s glory filled the tabernacle.

[[v2-40-35]]

^<<v2-40-35,35>>^ Moses was not able to go into the tent of meeting because the cloud remained over it, and Jehovah’s glory filled the tabernacle.

[[v2-40-36]]

^<<v2-40-36,36>>^ And when the cloud lifted from the tabernacle, the Israelites would break camp during all stages of their journey.

[[v2-40-37]]

^<<v2-40-37,37>>^ However, if the cloud did not lift up, then they would not break camp until the day it lifted.

[[v2-40-38]]

^<<v2-40-38,38>>^ For Jehovah’s cloud was over the tabernacle by day, and a fire remained over it by night in the sight of all the house of Israel during all stages of their journey.

'''

xref:002-exodus/002-exodus-039.adoc#v2-39-0[&#60; Capítulo Anterior] | <<v2-40-0,Topo>> | xref:003-leviticus/003-leviticus-001.adoc#v3-1-0[Próximo Capítulo &#62;]