include::./index.adoc[]

[[v2-34-0]]
=== Exodus, 34
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-34-1]]

^<<v2-34-1,1>>^ Then Jehovah said to Moses: “Carve out for yourself two tablets of stone like the first ones, and I will write on the tablets the words that appeared on the first tablets, which you shattered.

[[v2-34-2]]

^<<v2-34-2,2>>^ Get ready for the morning, as you will go up in the morning to Mount Siʹnai and station yourself before me there on the top of the mountain.

[[v2-34-3]]

^<<v2-34-3,3>>^ But nobody may go up with you, and nobody else should be seen anywhere on the mountain. Not even the flocks or herds should graze in front of that mountain.”

[[v2-34-4]]

^<<v2-34-4,4>>^ So Moses carved out two tablets of stone like the first ones and got up early in the morning and went up Mount Siʹnai, just as Jehovah had commanded him, and he took the two tablets of stone in his hand.

[[v2-34-5]]

^<<v2-34-5,5>>^ Then Jehovah came down in the cloud and stationed himself with him there and declared the name of Jehovah.

[[v2-34-6]]

^<<v2-34-6,6>>^ Jehovah was passing before him and declaring: “Jehovah, Jehovah, a God merciful and compassionate,^&#42;1^ slow to anger and abundant in loyal love^&#42;2^ and truth,^&#42;3^

[NOTE]
====
. Or “gracious.”
. Or “loving-kindness.”
. Or “faithfulness.”
====

[[v2-34-7]]

^<<v2-34-7,7>>^ showing loyal love to thousands, pardoning error and transgression and sin, but he will by no means leave the guilty unpunished, bringing punishment for the error of fathers upon sons and upon grandsons, upon the third generation and upon the fourth generation.”

[[v2-34-8]]

^<<v2-34-8,8>>^ Moses hurried to bow low to the earth and prostrate himself.

[[v2-34-9]]

^<<v2-34-9,9>>^ Then he said: “If, now, I have found favor in your eyes, O Jehovah, then please, Jehovah, go along with us in our midst, although we are an obstinate^&#42;1^ people, and forgive our error and our sin, and take us as your own possession.”

[NOTE]
====
. Lit., “stiff-necked.”
====

[[v2-34-10]]

^<<v2-34-10,10>>^ In turn he said: “Here I am making a covenant: Before all your people, I will do wonderful things that have never been done^&#42;1^ in all the earth or among all the nations, and all the people among whom you live will see the work of Jehovah, for it is an awe-inspiring thing that I am doing with you.

[NOTE]
====
. Or “created.”
====

[[v2-34-11]]

^<<v2-34-11,11>>^ “Pay attention to what I am commanding you today. Here I am driving out from before you the Amʹor·ites, the Caʹnaan·ites, the Hitʹtites, the Perʹiz·zites, the Hiʹvites, and the Jebʹu·sites.

[[v2-34-12]]

^<<v2-34-12,12>>^ Be careful that you do not make a covenant with the inhabitants of the land to which you are going, or it may prove to be a snare among you.

[[v2-34-13]]

^<<v2-34-13,13>>^ But you are to pull down their altars, you are to shatter their sacred pillars, and their sacred poles^&#42;1^ you are to cut down.

[NOTE]
====
. See Glossary.
====

[[v2-34-14]]

^<<v2-34-14,14>>^ You must not bow down to another god, for Jehovah is known for^&#42;1^ requiring exclusive devotion.^&#42;2^ Yes, he is a God who requires exclusive devotion.

[NOTE]
====
. Lit., “Jehovah, his name is.”
. Or “not tolerating rivals.”
====

[[v2-34-15]]

^<<v2-34-15,15>>^ Be careful not to make a covenant with the inhabitants of the land, because when they prostitute themselves to their gods and sacrifice to their gods, someone will invite you and you will eat from his sacrifice.

[[v2-34-16]]

^<<v2-34-16,16>>^ Then you will surely take some of their daughters for your sons, and their daughters will prostitute themselves to their gods and cause your sons to prostitute themselves to their gods.

[[v2-34-17]]

^<<v2-34-17,17>>^ “You must not make gods of cast metal.

[[v2-34-18]]

^<<v2-34-18,18>>^ “You are to observe the Festival of Unleavened Bread. You will eat unleavened bread, just as I have commanded you; do this for seven days at the appointed time in the month of Aʹbib,^&#42;1^ because it was in the month of Aʹbib that you came out of Egypt.

[NOTE]
====
. See App. B15.
====

[[v2-34-19]]

^<<v2-34-19,19>>^ “Every firstborn male^&#42;1^ is mine, including all your livestock, whether the first male bull or sheep.

[NOTE]
====
. Lit., “Everything that opens the womb.”
====

[[v2-34-20]]

^<<v2-34-20,20>>^ The firstling of a donkey you are to redeem with a sheep. But if you do not redeem it, then you must break its neck. You are to redeem every firstborn of your sons. No one may appear before me empty-handed.

[[v2-34-21]]

^<<v2-34-21,21>>^ “Six days you are to work, but on the seventh day you will rest.^&#42;1^ Even during plowing time and in harvest, you will rest.

[NOTE]
====
. Or “keep sabbath.”
====

[[v2-34-22]]

^<<v2-34-22,22>>^ “And you will celebrate your Festival of Weeks with the first ripe fruits of the wheat harvest, and the Festival of Ingathering^&#42;1^ at the turn of the year.

[NOTE]
====
. Also known as the Festival of Booths (Tabernacles).
====

[[v2-34-23]]

^<<v2-34-23,23>>^ “Three times a year, all your men^&#42;1^ are to appear before the true Lord, Jehovah, the God of Israel.

[NOTE]
====
. Or “males.”
====

[[v2-34-24]]

^<<v2-34-24,24>>^ For I will drive the nations away from before you, and I will enlarge your territory, and nobody will desire your land while you are going up to see the face of Jehovah your God three times a year.

[[v2-34-25]]

^<<v2-34-25,25>>^ “You must not offer the blood of my sacrifice along with anything leavened. The sacrifice of the festival of the Passover should not be kept overnight until the morning.

[[v2-34-26]]

^<<v2-34-26,26>>^ “The best of the first ripe fruits of your soil you are to bring to the house of Jehovah your God.
“You must not boil a young goat in its mother’s milk.”

[[v2-34-27]]

^<<v2-34-27,27>>^ Jehovah went on to say to Moses: “You are to write down these words, because in accordance with these words, I am making a covenant with you and with Israel.”

[[v2-34-28]]

^<<v2-34-28,28>>^ And he remained there with Jehovah 40 days and 40 nights. He ate no bread and drank no water. And He wrote on the tablets the words of the covenant, the Ten Commandments.^&#42;1^

[NOTE]
====
. Lit., “the Ten Words.” Also known as the Decalogue.
====

[[v2-34-29]]

^<<v2-34-29,29>>^ Moses then came down from Mount Siʹnai, and the two tablets of the Testimony were in his hand. When he came down from the mountain, Moses did not know that the skin of his face was emitting rays because he had been speaking with God.

[[v2-34-30]]

^<<v2-34-30,30>>^ When Aaron and all the Israelites saw Moses, they noticed that the skin of his face emitted rays and they were afraid to go near him.

[[v2-34-31]]

^<<v2-34-31,31>>^ But Moses called to them, so Aaron and all the chieftains of the assembly came to him, and Moses spoke with them.

[[v2-34-32]]

^<<v2-34-32,32>>^ After that all the Israelites came near to him, and he gave them all the commands that Jehovah had given him on Mount Siʹnai.

[[v2-34-33]]

^<<v2-34-33,33>>^ When Moses would finish speaking with them, he would put a veil over his face.

[[v2-34-34]]

^<<v2-34-34,34>>^ But when Moses would go in before Jehovah to speak with him, he would take off the veil until he went out. Then he went out and revealed to the Israelites the commands he had received.

[[v2-34-35]]

^<<v2-34-35,35>>^ And the Israelites saw that the skin of Moses’ face emitted rays; then Moses put the veil back over his face until he went in to speak with God.^&#42;1^

[NOTE]
====
. Lit., “him.”
====

'''

xref:002-exodus/002-exodus-033.adoc#v2-33-0[&#60; Capítulo Anterior] | <<v2-34-0,Topo>> | xref:002-exodus/002-exodus-035.adoc#v2-35-0[Próximo Capítulo &#62;]