include::./index.adoc[]

[[v2-17-0]]
=== Exodus, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-17-1]]

^<<v2-17-1,1>>^ The entire assembly of the Israelites departed from the wilderness of Sin by stages according to the order of Jehovah, and they camped at Rephʹi·dim. But there was no water for the people to drink.

[[v2-17-2]]

^<<v2-17-2,2>>^ So the people began quarreling with Moses and saying: “Give us water to drink.” But Moses said to them: “Why are you quarreling with me? Why do you keep putting Jehovah to the test?”

[[v2-17-3]]

^<<v2-17-3,3>>^ But the people were very thirsty for water there, and they kept murmuring against Moses and saying: “Why have you brought us up out of Egypt to kill us and our sons and our livestock with thirst?”

[[v2-17-4]]

^<<v2-17-4,4>>^ Finally Moses cried out to Jehovah: “What should I do with this people? A little longer and they will stone me!”

[[v2-17-5]]

^<<v2-17-5,5>>^ Then Jehovah said to Moses: “Go ahead of the people, and take with you some of the elders of Israel and your rod with which you struck the Nile River. Take it in your hand and walk on.

[[v2-17-6]]

^<<v2-17-6,6>>^ Look! I will be standing before you there on the rock in Horʹeb. You must strike the rock, and water will come out of it, and the people will drink it.” Moses did so before the eyes of the elders of Israel.

[[v2-17-7]]

^<<v2-17-7,7>>^ So he named the place Masʹsah^&#42;1^ and Merʹi·bah^&#42;2^ because of the quarreling of the Israelites and because they put Jehovah to the test by saying: “Is Jehovah in our midst or not?”

[NOTE]
====
. Meaning “Testing; Trial.”
. Meaning “Quarreling.”
====

[[v2-17-8]]

^<<v2-17-8,8>>^ Then the A·malʹek·ites came and fought against Israel in Rephʹi·dim.

[[v2-17-9]]

^<<v2-17-9,9>>^ At this Moses said to Joshua: “Choose men for us and go out to fight against the A·malʹek·ites. Tomorrow I will stand on top of the hill, with the rod of the true God in my hand.”

[[v2-17-10]]

^<<v2-17-10,10>>^ Then Joshua did just as Moses told him, and he fought against the A·malʹek·ites. And Moses, Aaron, and Hur went up to the top of the hill.

[[v2-17-11]]

^<<v2-17-11,11>>^ As long as Moses kept his hands lifted up, the Israelites prevailed, but as soon as he would let down his hands, the A·malʹek·ites prevailed.

[[v2-17-12]]

^<<v2-17-12,12>>^ When the hands of Moses were heavy, they took a stone and put it under him, and he sat on it. Then Aaron and Hur, one on each side, supported his hands, so that his hands remained steady until the sun set.

[[v2-17-13]]

^<<v2-17-13,13>>^ Thus Joshua defeated Amʹa·lek and his people with the sword.

[[v2-17-14]]

^<<v2-17-14,14>>^ Jehovah now said to Moses: “Write this as a memorial^&#42;1^ in the book and repeat it to Joshua, ‘I will completely wipe out the memory of Amʹa·lek from under the heavens.’”

[NOTE]
====
. Or “reminder.”
====

[[v2-17-15]]

^<<v2-17-15,15>>^ Then Moses built an altar and named it Je·hoʹvah-nisʹsi,^&#42;1^

[NOTE]
====
. Meaning “Jehovah Is My Signal Pole.”
====

[[v2-17-16]]

^<<v2-17-16,16>>^ saying: “Because his hand is against the throne of Jah, Jehovah will have war with Amʹa·lek from generation to generation.”

'''

xref:002-exodus/002-exodus-016.adoc#v2-16-0[&#60; Capítulo Anterior] | <<v2-17-0,Topo>> | xref:002-exodus/002-exodus-018.adoc#v2-18-0[Próximo Capítulo &#62;]