include::./index.adoc[]

[[v2-36-0]]
=== Exodus, 36
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-36-1]]

^<<v2-36-1,1>>^ “Bezʹal·el will work along with O·hoʹli·ab and every skilled man^&#42;1^ to whom Jehovah has given wisdom and understanding so as to know how to do all the work of the holy service just as Jehovah has commanded.”

[NOTE]
====
. Lit., “every man wise of heart.”
====

[[v2-36-2]]

^<<v2-36-2,2>>^ Moses then called Bezʹal·el and O·hoʹli·ab and every skilled man into whose heart Jehovah had put wisdom, everyone whose heart impelled him to volunteer to do the work.

[[v2-36-3]]

^<<v2-36-3,3>>^ Then they took from Moses all the contribution that the Israelites had brought for the work of the holy service. However, these continued to bring him voluntary offerings, morning after morning.

[[v2-36-4]]

^<<v2-36-4,4>>^ Then after they started the holy work, all the skilled workers were coming, one after another,

[[v2-36-5]]

^<<v2-36-5,5>>^ and they were telling Moses: “The people are bringing much more than what is required for the work that Jehovah has commanded to be done.”

[[v2-36-6]]

^<<v2-36-6,6>>^ So Moses commanded that an announcement be made throughout the camp, saying: “Men and women, do not bring any more goods for the holy contribution.” With that the people were restrained from bringing in anything else.

[[v2-36-7]]

^<<v2-36-7,7>>^ The goods were enough for all the work to be done, and more than enough.

[[v2-36-8]]

^<<v2-36-8,8>>^ So all the skilled workers made the tabernacle of ten tent cloths of fine twisted linen, blue thread, purple wool, and scarlet material; he^&#42;1^ made them with cherubs embroidered on them.

[NOTE]
====
. Evidently referring to Bezalel.
====

[[v2-36-9]]

^<<v2-36-9,9>>^ Each tent cloth was 28 cubits^&#42;1^ long and 4 cubits wide. All the tent cloths were the same size.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
====

[[v2-36-10]]

^<<v2-36-10,10>>^ Then he joined five of the tent cloths together, and the other five tent cloths he joined together.

[[v2-36-11]]

^<<v2-36-11,11>>^ After that he made loops of blue thread on the edge of the one tent cloth where it would join. He did the same on the edge of the outermost tent cloth at the corresponding place where it would join.

[[v2-36-12]]

^<<v2-36-12,12>>^ He made 50 loops on the one tent cloth and 50 loops on the other edge of the tent cloth at the place where it would join so that the loops would be opposite one another.

[[v2-36-13]]

^<<v2-36-13,13>>^ Finally, he made 50 gold clasps and joined the tent cloths together with the clasps, so that the tabernacle became one unit.

[[v2-36-14]]

^<<v2-36-14,14>>^ Then he made tent cloths of goat hair for the tent over the tabernacle. He made 11 tent cloths.

[[v2-36-15]]

^<<v2-36-15,15>>^ Each tent cloth was 30 cubits long and 4 cubits wide. The 11 tent cloths were the same size.

[[v2-36-16]]

^<<v2-36-16,16>>^ Then he joined five of the tent cloths together, and he joined the other six tent cloths together.

[[v2-36-17]]

^<<v2-36-17,17>>^ Next he made 50 loops along the edge of the outermost tent cloth where it joined, and he made 50 loops along the edge of the other tent cloth that joined with it.

[[v2-36-18]]

^<<v2-36-18,18>>^ And he made 50 copper clasps for joining the tent together to become one unit.

[[v2-36-19]]

^<<v2-36-19,19>>^ He made a covering for the tent out of ram skins dyed red and a covering out of sealskins to go over that.

[[v2-36-20]]

^<<v2-36-20,20>>^ Then he made out of acacia wood the tabernacle’s panel frames, which stood upright.

[[v2-36-21]]

^<<v2-36-21,21>>^ Each panel frame was ten cubits high and one and a half cubits wide.

[[v2-36-22]]

^<<v2-36-22,22>>^ Each panel frame had two tenons^&#42;1^ joined to each other. That is how he made all the panel frames of the tabernacle.

[NOTE]
====
. Or “upright posts.”
====

[[v2-36-23]]

^<<v2-36-23,23>>^ Thus he made the panel frames for the south side of the tabernacle, 20 panel frames, facing south.

[[v2-36-24]]

^<<v2-36-24,24>>^ Then he made 40 socket pedestals of silver to go under the 20 panel frames, two socket pedestals beneath one panel frame for its two tenons and two socket pedestals under each following panel frame for its two tenons.

[[v2-36-25]]

^<<v2-36-25,25>>^ For the other side of the tabernacle, the northern side, he made 20 panel frames

[[v2-36-26]]

^<<v2-36-26,26>>^ and their 40 socket pedestals of silver, two socket pedestals beneath the one panel frame and two socket pedestals beneath each of the other panel frames.

[[v2-36-27]]

^<<v2-36-27,27>>^ For the rear section of the tabernacle to the west, he made six panel frames.

[[v2-36-28]]

^<<v2-36-28,28>>^ He made two panel frames as corner posts of the tabernacle at the two rear corners.

[[v2-36-29]]

^<<v2-36-29,29>>^ The posts were doubled from the bottom to the top, up to the first ring. That is what he did with the two corner posts.

[[v2-36-30]]

^<<v2-36-30,30>>^ So they amounted to eight panel frames along with their 16 socket pedestals of silver, two socket pedestals under each panel frame.

[[v2-36-31]]

^<<v2-36-31,31>>^ Then he made bars of acacia wood, five bars for the panel frames of the one side of the tabernacle

[[v2-36-32]]

^<<v2-36-32,32>>^ and five bars for the panel frames of the other side of the tabernacle and five for the panel frames of the tabernacle for the rear section to the west.

[[v2-36-33]]

^<<v2-36-33,33>>^ He made the middle bar to extend along the middle of the panel frames from one end to the other.

[[v2-36-34]]

^<<v2-36-34,34>>^ He overlaid the panel frames with gold, and he made their rings of gold as holders for the bars, and he overlaid the bars with gold.

[[v2-36-35]]

^<<v2-36-35,35>>^ Then he made a curtain of blue thread, purple wool, scarlet material, and fine twisted linen. He made it with cherubs embroidered on it.

[[v2-36-36]]

^<<v2-36-36,36>>^ Then he made for it four acacia pillars and overlaid them with gold, along with hooks of gold, and cast four socket pedestals of silver for them.

[[v2-36-37]]

^<<v2-36-37,37>>^ Next he made a screen^&#42;1^ for the entrance of the tent out of blue thread, purple wool, scarlet material, and fine twisted linen woven together,

[NOTE]
====
. Or “curtain.”
====

[[v2-36-38]]

^<<v2-36-38,38>>^ as well as its five pillars and their hooks. He overlaid their tops and their connectors^&#42;1^ with gold, but their five socket pedestals were of copper.

[NOTE]
====
. Or “rings; hoops; bands” for attachments.
====

'''

xref:002-exodus/002-exodus-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodus/002-exodus-037.adoc#v2-37-0[Próximo Capítulo &#62;]