include::./index.adoc[]

[[v2-39-0]]
=== Exodus, 39
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v2-39-1]]

^<<v2-39-1,1>>^ From the blue thread, the purple wool, and the scarlet material, they made finely woven garments for ministering in the holy place. They made the holy garments that were for Aaron, just as Jehovah had commanded Moses.

[[v2-39-2]]

^<<v2-39-2,2>>^ He made the ephʹod of gold, blue thread, purple wool, scarlet material, and fine twisted linen.

[[v2-39-3]]

^<<v2-39-3,3>>^ They hammered plates of gold into thin sheets, and he cut it into threads to work in with the blue thread, the purple wool, the scarlet material, and the fine linen, and it was embroidered.

[[v2-39-4]]

^<<v2-39-4,4>>^ They made shoulder pieces for it that were joined at its two top edges.

[[v2-39-5]]

^<<v2-39-5,5>>^ And the woven belt,^&#42;1^ which was attached to the ephʹod for tying it securely in position, was made of the same material, of gold, blue thread, purple wool, scarlet material, and fine twisted linen, just as Jehovah had commanded Moses.

[NOTE]
====
. Or “waistband.”
====

[[v2-39-6]]

^<<v2-39-6,6>>^ Then they mounted the onyx stones in gold settings, and they engraved them with the names of the sons of Israel, as they would engrave a seal.

[[v2-39-7]]

^<<v2-39-7,7>>^ He placed them on the shoulder pieces of the ephʹod as memorial stones for the sons of Israel, just as Jehovah had commanded Moses.

[[v2-39-8]]

^<<v2-39-8,8>>^ Then he made the breastpiece with the workmanship of an embroiderer, like the workmanship of the ephʹod, out of gold, blue thread, purple wool, scarlet material, and fine twisted linen.

[[v2-39-9]]

^<<v2-39-9,9>>^ It was square when doubled. They made the breastpiece, which, when doubled, was as long and as wide as the span of the hand.^&#42;1^

[NOTE]
====
. About 22.2 cm (8.75 in.). See App. B14.
====

[[v2-39-10]]

^<<v2-39-10,10>>^ They set four rows of stones in it. The first row was ruby, topaz, and emerald.

[[v2-39-11]]

^<<v2-39-11,11>>^ The second row was turquoise, sapphire, and jasper.

[[v2-39-12]]

^<<v2-39-12,12>>^ The third row was leshʹem stone,^&#42;1^ agate, and amethyst.

[NOTE]
====
. An unidentified precious stone, possibly referring to amber, hyacinth, opal, or tourmaline.
====

[[v2-39-13]]

^<<v2-39-13,13>>^ And the fourth row was chrysʹo·lite, onyx, and jade. They were mounted in settings of gold.

[[v2-39-14]]

^<<v2-39-14,14>>^ The stones corresponded to the names of the 12 sons of Israel, and the names were engraved like a seal, each name representing one of the 12 tribes.

[[v2-39-15]]

^<<v2-39-15,15>>^ Then they made wreathed chains on the breastpiece, like cords of pure gold.

[[v2-39-16]]

^<<v2-39-16,16>>^ And they made two settings of gold and two rings of gold and attached the two rings to the two corners of the breastpiece.

[[v2-39-17]]

^<<v2-39-17,17>>^ After that they put the two cords of gold through the two rings at the corners of the breastpiece.

[[v2-39-18]]

^<<v2-39-18,18>>^ Then they put the two ends of the two cords through the two settings and attached them to the shoulder pieces on the front of the ephʹod.

[[v2-39-19]]

^<<v2-39-19,19>>^ Next they made two rings of gold and set them at the two ends on the inside edge of the breastpiece, facing the ephʹod.

[[v2-39-20]]

^<<v2-39-20,20>>^ Then they made two more rings of gold and put them on the front of the ephʹod, below the two shoulder pieces, close to where it is joined, above the woven belt^&#42;1^ of the ephʹod.

[NOTE]
====
. Or “waistband.”
====

[[v2-39-21]]

^<<v2-39-21,21>>^ Finally, they tied the breastpiece with a blue cord from its rings to the rings of the ephʹod, in order to keep the breastpiece in its place on the ephʹod, above the woven belt,^&#42;1^ just as Jehovah had commanded Moses.

[NOTE]
====
. Or “waistband.”
====

[[v2-39-22]]

^<<v2-39-22,22>>^ Then he made the sleeveless coat of the ephʹod, woven by a loom worker, all of blue thread.

[[v2-39-23]]

^<<v2-39-23,23>>^ The opening of the sleeveless coat was in the middle of it, like the opening of a coat of mail. Its opening had a border around it, so that it would not be torn.

[[v2-39-24]]

^<<v2-39-24,24>>^ Next they made on the hem of the sleeveless coat pomegranates of blue thread, purple wool, and scarlet material, twisted together.

[[v2-39-25]]

^<<v2-39-25,25>>^ And they made bells of pure gold and put the bells in between the pomegranates all around the hem of the sleeveless coat, in between the pomegranates;

[[v2-39-26]]

^<<v2-39-26,26>>^ they alternated a bell and a pomegranate, a bell and a pomegranate, all around the hem of the sleeveless coat, which was used for ministering, just as Jehovah had commanded Moses.

[[v2-39-27]]

^<<v2-39-27,27>>^ And they made the robes of fine linen, woven by a loom worker, for Aaron and his sons,

[[v2-39-28]]

^<<v2-39-28,28>>^ and the turban of fine linen, the ornamental headgear of fine linen, the linen shorts^&#42;1^ of fine twisted linen,

[NOTE]
====
. Or “undergarments.”
====

[[v2-39-29]]

^<<v2-39-29,29>>^ and the sash of fine twisted linen, blue thread, purple wool, and scarlet material woven together, just as Jehovah had commanded Moses.

[[v2-39-30]]

^<<v2-39-30,30>>^ Finally, they made the shining plate, the holy sign of dedication,^&#42;1^ out of pure gold and inscribed on it an inscription as one would engrave a seal: “Holiness belongs to Jehovah.”

[NOTE]
====
. Or “the holy diadem.”
====

[[v2-39-31]]

^<<v2-39-31,31>>^ They attached to it a cord made from blue thread in order to put it on the turban, just as Jehovah had commanded Moses.

[[v2-39-32]]

^<<v2-39-32,32>>^ So all the work for the tabernacle, the tent of meeting, was completed, and the Israelites did everything that Jehovah had commanded Moses. They did just so.

[[v2-39-33]]

^<<v2-39-33,33>>^ Then they brought the tabernacle to Moses, the tent and all its equipment: its clasps, its panel frames, its bars and its pillars and its socket pedestals;

[[v2-39-34]]

^<<v2-39-34,34>>^ its covering of ram skins dyed red, its covering of sealskins, the curtain for the screen;

[[v2-39-35]]

^<<v2-39-35,35>>^ the ark of the Testimony and its poles and the cover;

[[v2-39-36]]

^<<v2-39-36,36>>^ the table, all its utensils and the showbread;

[[v2-39-37]]

^<<v2-39-37,37>>^ the lampstand of pure gold, its lamps, the row of lamps, and all its utensils and the oil for lighting;

[[v2-39-38]]

^<<v2-39-38,38>>^ the altar of gold, the anointing oil, the perfumed incense, the screen^&#42;1^ for the entrance of the tent;

[NOTE]
====
. Or “curtain.”
====

[[v2-39-39]]

^<<v2-39-39,39>>^ the altar of copper and its grating of copper, its poles, all its utensils, the basin and its stand;

[[v2-39-40]]

^<<v2-39-40,40>>^ the hanging curtains of the courtyard, its pillars and its socket pedestals, the screen^&#42;1^ for the entrance of the courtyard, its tent cords and its tent pins and all the utensils for the service of the tabernacle, for the tent of meeting;

[NOTE]
====
. Or “curtain.”
====

[[v2-39-41]]

^<<v2-39-41,41>>^ the finely woven garments for ministering in the sanctuary, the holy garments for Aaron the priest, and the garments of his sons for serving as priests.

[[v2-39-42]]

^<<v2-39-42,42>>^ According to all that Jehovah had commanded Moses, that was how the Israelites did all the work.

[[v2-39-43]]

^<<v2-39-43,43>>^ When Moses inspected all their work, he saw that they had done it just as Jehovah had commanded; and Moses blessed them.

'''

xref:002-exodus/002-exodus-038.adoc#v2-38-0[&#60; Capítulo Anterior] | <<v2-39-0,Topo>> | xref:002-exodus/002-exodus-040.adoc#v2-40-0[Próximo Capítulo &#62;]