include::./index.adoc[]

[[v8-2-0]]
=== Ruth, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v8-2-1]]

^<<v8-2-1,1>>^ Now Na·oʹmi had a relative on her husband’s side who was very wealthy; his name was Boʹaz, and he was of the family of E·limʹe·lech.

[[v8-2-2]]

^<<v8-2-2,2>>^ Ruth the Moʹab·i·tess said to Na·oʹmi: “Let me go out, please, to the fields and glean among the ears of grain behind whoever looks on me with favor.” So Na·oʹmi said to her: “Go, my daughter.”

[[v8-2-3]]

^<<v8-2-3,3>>^ At that she went out and began to glean in the field behind the harvesters. By chance she came upon a plot of land belonging to Boʹaz, who was of the family of E·limʹe·lech.

[[v8-2-4]]

^<<v8-2-4,4>>^ Just then Boʹaz arrived from Bethʹle·hem and said to the harvesters: “Jehovah be with you.” And they replied: “Jehovah bless you.”

[[v8-2-5]]

^<<v8-2-5,5>>^ Boʹaz then asked the young man in charge of the harvesters: “To whom does this young woman belong?”

[[v8-2-6]]

^<<v8-2-6,6>>^ The young man in charge of the harvesters answered: “The young woman is a Moʹab·i·tess who returned with Na·oʹmi from the fields of Moʹab.

[[v8-2-7]]

^<<v8-2-7,7>>^ She asked, ‘Please, may I glean and gather among the cut-off ears^&#42;1^ of grain left behind by the harvesters?’ And she has been on her feet since she came this morning until just now, when she sat in the shelter for a short rest.”

[NOTE]
====
. Or possibly, “the sheaves.”
====

[[v8-2-8]]

^<<v8-2-8,8>>^ Then Boʹaz said to Ruth: “Listen, my daughter. Do not go away to glean in another field, and do not go anywhere else; stay close by my young women.

[[v8-2-9]]

^<<v8-2-9,9>>^ Keep your eyes on the field that they harvest, and go with them. I have commanded the young men not to touch^&#42;1^ you. When you are thirsty, go to the water jars and drink from what the young men have drawn.”

[NOTE]
====
. Or “disturb.”
====

[[v8-2-10]]

^<<v8-2-10,10>>^ At that she fell facedown and bowed down to the ground and said to him: “How have I found favor in your eyes, and why have you taken notice of me, when I am a foreigner?”

[[v8-2-11]]

^<<v8-2-11,11>>^ Boʹaz answered her: “A full report was made to me of all you have done for your mother-in-law after the death of your husband and how you left your father and your mother and the land of your relatives to go to a people whom you had not known before.

[[v8-2-12]]

^<<v8-2-12,12>>^ May Jehovah reward you for what you have done, and may there be a perfect wage^&#42;1^ for you from Jehovah the God of Israel, under whose wings you have come to seek refuge.”

[NOTE]
====
. Or “a full reward.”
====

[[v8-2-13]]

^<<v8-2-13,13>>^ To this she said: “Let me find favor in your eyes, my lord, because you have comforted me and spoken reassuringly to^&#42;1^ your servant, although I am not even one of your servants.”

[NOTE]
====
. Lit., “spoken to the heart of.”
====

[[v8-2-14]]

^<<v8-2-14,14>>^ Boʹaz said to her at mealtime: “Come here, eat some of the bread, and dip your piece in the vinegar.” So she sat down beside the harvesters. He then handed her some roasted grain, and she ate and was satisfied, and she had something left over.

[[v8-2-15]]

^<<v8-2-15,15>>^ When she got up to glean, Boʹaz commanded his young men: “Let her glean even among the cut-off ears^&#42;1^ of grain, and do not mistreat her.

[NOTE]
====
. Or possibly, “the sheaves.”
====

[[v8-2-16]]

^<<v8-2-16,16>>^ You should also be sure to pull out some ears of grain from the bundles for her and leave them behind for her to glean, and do not say anything to stop her.”

[[v8-2-17]]

^<<v8-2-17,17>>^ So she continued to glean in the field until evening. When she beat out what she had gleaned, it came to about an eʹphah^&#42;1^ of barley.

[NOTE]
====
. About 22 L (20 dry qt). See App. B14.
====

[[v8-2-18]]

^<<v8-2-18,18>>^ Then she took it and went into the city, and her mother-in-law saw what she had gleaned. Ruth also took out and gave to her the food that was left over after she had eaten her fill.

[[v8-2-19]]

^<<v8-2-19,19>>^ Her mother-in-law then said to her: “Where did you glean today? Where did you work? May the one who took notice of you be blessed.” So she told her mother-in-law about whom she had worked with, saying: “The name of the man I worked with today is Boʹaz.”

[[v8-2-20]]

^<<v8-2-20,20>>^ At that Na·oʹmi said to her daughter-in-law: “May he be blessed by Jehovah, who has not failed in his loyal love toward the living and the dead.” Na·oʹmi continued: “The man is related to us. He is one of our repurchasers.”^&#42;1^

[NOTE]
====
. Or “one of our relatives with the right to repurchase (redeem).”
====

[[v8-2-21]]

^<<v8-2-21,21>>^ Then Ruth the Moʹab·i·tess said: “He also told me, ‘Stay close by my young people until they have finished my entire harvest.’”

[[v8-2-22]]

^<<v8-2-22,22>>^ Na·oʹmi said to her daughter-in-law Ruth: “It is better, my daughter, for you to go out with his young women than to be harassed in another field.”

[[v8-2-23]]

^<<v8-2-23,23>>^ So she stayed close to the young women of Boʹaz and gleaned until the barley harvest and the wheat harvest came to an end. And she kept dwelling with her mother-in-law.

'''

xref:008-ruth/008-ruth-001.adoc#v8-1-0[&#60; Capítulo Anterior] | <<v8-2-0,Topo>> | xref:008-ruth/008-ruth-003.adoc#v8-3-0[Próximo Capítulo &#62;]