include::./index.adoc[]

[[v8-3-0]]
=== Ruth, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v8-3-1]]

^<<v8-3-1,1>>^ Na·oʹmi, her mother-in-law, now said to her: “My daughter, should I not look for a home^&#42;1^ for you, so that it may go well with you?

[NOTE]
====
. Lit., “resting-place.”
====

[[v8-3-2]]

^<<v8-3-2,2>>^ Is not Boʹaz our relative? He is the one whose young women you were with. Tonight he is winnowing barley at the threshing floor.

[[v8-3-3]]

^<<v8-3-3,3>>^ So wash yourself and rub on some perfumed oil; then dress up^&#42;1^ and go down to the threshing floor. Do not make your presence known to the man until he has finished eating and drinking.

[NOTE]
====
. Or “put on your outer garments.”
====

[[v8-3-4]]

^<<v8-3-4,4>>^ When he lies down, take note of the place where he lies down; then go and uncover his feet and lie down. He will tell you what you should do.”

[[v8-3-5]]

^<<v8-3-5,5>>^ At that she replied: “All that you say to me I will do.”

[[v8-3-6]]

^<<v8-3-6,6>>^ So she went down to the threshing floor and did all that her mother-in-law had instructed her to do.

[[v8-3-7]]

^<<v8-3-7,7>>^ Meanwhile, Boʹaz ate and drank and was feeling good at heart. Then he went to lie down at the end of the grain heap. After that she quietly came and uncovered his feet and lay down.

[[v8-3-8]]

^<<v8-3-8,8>>^ At midnight the man began to shiver, and he leaned forward and saw a woman lying at his feet.

[[v8-3-9]]

^<<v8-3-9,9>>^ He said: “Who are you?” She replied: “I am Ruth, your servant. Spread out your garment^&#42;1^ over your servant, for you are a repurchaser.”

[NOTE]
====
. Or “the skirt of your garment.”
====

[[v8-3-10]]

^<<v8-3-10,10>>^ At that he said: “May Jehovah bless you, my daughter. You have shown your loyal love more in this last instance than in the first instance, by not going after the young men, whether poor or rich.

[[v8-3-11]]

^<<v8-3-11,11>>^ And now, my daughter, have no fear. I will do for you everything that you say, for everyone in the city^&#42;1^ knows that you are an excellent woman.

[NOTE]
====
. Lit., “all the gate of my people.”
====

[[v8-3-12]]

^<<v8-3-12,12>>^ While it is true that I am a repurchaser, there is a repurchaser more closely related than I am.

[[v8-3-13]]

^<<v8-3-13,13>>^ Stay here tonight, and if he will repurchase you in the morning, fine! Let him repurchase you. But if he does not want to repurchase you, I will then repurchase you myself, as surely as Jehovah lives. Lie down here until the morning.”

[[v8-3-14]]

^<<v8-3-14,14>>^ So she lay at his feet until the morning and then got up before it was light enough for anyone to be recognized. He then said: “Do not let it be known that a woman came to the threshing floor.”

[[v8-3-15]]

^<<v8-3-15,15>>^ He also said: “Bring the cloak that you are wearing, and hold it out.” So she held it out, and he put six measures^&#42;1^ of barley in it and put it on her, after which he went into the city.

[NOTE]
====
. Possibly six seah measures, or about 44 L (40 dry qt). See App. B14.
====

[[v8-3-16]]

^<<v8-3-16,16>>^ She went her way to her mother-in-law, who now said: “How did it go for you,^&#42;1^ my daughter?” She told her everything that the man had done for her.

[NOTE]
====
. Lit., “Who are you?”
====

[[v8-3-17]]

^<<v8-3-17,17>>^ She added: “He gave me these six measures of barley and said to me, ‘Do not go empty-handed to your mother-in-law.’”

[[v8-3-18]]

^<<v8-3-18,18>>^ At that she said: “Sit here, my daughter, until you learn how the matter will turn out, for the man will not rest until he settles the matter today.”

'''

xref:008-ruth/008-ruth-002.adoc#v8-2-0[&#60; Capítulo Anterior] | <<v8-3-0,Topo>> | xref:008-ruth/008-ruth-004.adoc#v8-4-0[Próximo Capítulo &#62;]