include::./index.adoc[]

[[v48-5-0]]
=== To the Galatians, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v48-5-1]]

^<<v48-5-1,1>>^ For such freedom Christ set us free. Therefore, stand firm, and do not let yourselves be confined again in a yoke of slavery.

[[v48-5-2]]

^<<v48-5-2,2>>^ See! I, Paul, am telling you that if you become circumcised, Christ will be of no benefit to you.

[[v48-5-3]]

^<<v48-5-3,3>>^ Again I bear witness to every man who gets circumcised that he is under obligation to keep the whole Law.

[[v48-5-4]]

^<<v48-5-4,4>>^ You are separated from Christ, you who are trying to be declared righteous by means of law; you have fallen away from his undeserved kindness.

[[v48-5-5]]

^<<v48-5-5,5>>^ For our part, we are by spirit eagerly waiting for the hoped-for righteousness resulting from faith.

[[v48-5-6]]

^<<v48-5-6,6>>^ For in union with Christ Jesus, neither circumcision nor uncircumcision is of any value, but faith operating through love is.

[[v48-5-7]]

^<<v48-5-7,7>>^ You were running well. Who hindered you from continuing to obey the truth?

[[v48-5-8]]

^<<v48-5-8,8>>^ This sort of persuasion does not come from the One calling you.

[[v48-5-9]]

^<<v48-5-9,9>>^ A little leaven ferments the whole batch of dough.

[[v48-5-10]]

^<<v48-5-10,10>>^ I am confident that you who are in union with the Lord will not come to think otherwise; but the one who is causing you trouble, whoever he may be, will receive the judgment he deserves.

[[v48-5-11]]

^<<v48-5-11,11>>^ As for me, brothers, if I am still preaching circumcision, why am I still being persecuted? In that case the stumbling block of the torture stake^&#42;1^ has been eliminated.

[NOTE]
====
. See Glossary.
====

[[v48-5-12]]

^<<v48-5-12,12>>^ I wish the men who are trying to unsettle you would emasculate themselves.^&#42;1^

[NOTE]
====
. Or “castrate themselves; become eunuchs,” thus becoming disqualified from performing the very law they were endorsing.
====

[[v48-5-13]]

^<<v48-5-13,13>>^ You were called to freedom, brothers; only do not use this freedom as an opportunity to pursue fleshly desires, but through love slave for one another.

[[v48-5-14]]

^<<v48-5-14,14>>^ For the entire Law has been fulfilled^&#42;1^ in one commandment, namely: “You must love your neighbor as yourself.”

[NOTE]
====
. Or possibly, “is summed up.”
====

[[v48-5-15]]

^<<v48-5-15,15>>^ If, though, you keep on biting and devouring one another, look out that you do not get annihilated by one another.

[[v48-5-16]]

^<<v48-5-16,16>>^ But I say, Keep walking by spirit and you will carry out no fleshly desire at all.

[[v48-5-17]]

^<<v48-5-17,17>>^ For the flesh is against the spirit in its desire, and the spirit against the flesh; these are opposed to each other, so that you do not do the very things you want to do.

[[v48-5-18]]

^<<v48-5-18,18>>^ Furthermore, if you are being led by spirit, you are not under law.

[[v48-5-19]]

^<<v48-5-19,19>>^ Now the works of the flesh are plainly seen, and they are sexual immorality,^&#42;1^ uncleanness, brazen conduct,^&#42;2^

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
. Or “shameless conduct.” Greek, a·selʹgei·a. See Glossary.
====

[[v48-5-20]]

^<<v48-5-20,20>>^ idolatry, spiritism,^&#42;1^ hostility, strife, jealousy, fits of anger, dissensions, divisions, sects,

[NOTE]
====
. Or “sorcery; druggery.”
====

[[v48-5-21]]

^<<v48-5-21,21>>^ envy, drunkenness, wild parties,^&#42;1^ and things like these. I am forewarning you about these things, the same way I already warned you, that those who practice such things will not inherit God’s Kingdom.

[NOTE]
====
. Or “revelries.”
====

[[v48-5-22]]

^<<v48-5-22,22>>^ On the other hand, the fruitage of the spirit is love, joy, peace, patience,^&#42;1^ kindness, goodness, faith,

[NOTE]
====
. Or “long-suffering.”
====

[[v48-5-23]]

^<<v48-5-23,23>>^ mildness, self-control. Against such things there is no law.

[[v48-5-24]]

^<<v48-5-24,24>>^ Moreover, those who belong to Christ Jesus have nailed to the stake the flesh together with its passions and desires.

[[v48-5-25]]

^<<v48-5-25,25>>^ If we are living by spirit, let us also go on walking orderly by spirit.

[[v48-5-26]]

^<<v48-5-26,26>>^ Let us not become egotistical, stirring up competition with one another, envying one another.

'''

xref:048-galatians/048-galatians-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatians/048-galatians-006.adoc#v48-6-0[Próximo Capítulo &#62;]