include::./index.adoc[]

[[v48-6-0]]
=== To the Galatians, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v48-6-1]]

^<<v48-6-1,1>>^ Brothers, even if a man takes a false step before he is aware of it, you who have spiritual qualifications try to readjust such a man in a spirit of mildness. But keep an eye on yourself, for fear you too may be tempted.

[[v48-6-2]]

^<<v48-6-2,2>>^ Go on carrying the burdens of one another, and in this way you will fulfill the law of the Christ.

[[v48-6-3]]

^<<v48-6-3,3>>^ For if anyone thinks he is something when he is nothing, he is deceiving himself.

[[v48-6-4]]

^<<v48-6-4,4>>^ But let each one examine his own actions, and then he will have cause for rejoicing in regard to himself alone, and not in comparison with the other person.

[[v48-6-5]]

^<<v48-6-5,5>>^ For each one will carry his own load.^&#42;1^

[NOTE]
====
. Or “load of responsibility.”
====

[[v48-6-6]]

^<<v48-6-6,6>>^ Moreover, let anyone who is being taught^&#42;1^ the word share in all good things with the one who gives such teaching.^&#42;2^

[NOTE]
====
. Or “orally taught.”
. Or “such oral teaching.”
====

[[v48-6-7]]

^<<v48-6-7,7>>^ Do not be misled: God is not one to be mocked. For whatever a person is sowing, this he will also reap;

[[v48-6-8]]

^<<v48-6-8,8>>^ because the one sowing with a view to his flesh will reap corruption from his flesh, but the one sowing with a view to the spirit will reap everlasting life from the spirit.

[[v48-6-9]]

^<<v48-6-9,9>>^ So let us not give up in doing what is fine, for in due time we will reap if we do not tire out.^&#42;1^

[NOTE]
====
. Or “give up.”
====

[[v48-6-10]]

^<<v48-6-10,10>>^ So, then, as long as we have the opportunity,^&#42;1^ let us work what is good toward all, but especially toward those related to us in the faith.

[NOTE]
====
. Lit., “appointed time.”
====

[[v48-6-11]]

^<<v48-6-11,11>>^ See with what large letters I have written you with my own hand.

[[v48-6-12]]

^<<v48-6-12,12>>^ All those who want to make a good impression in the flesh^&#42;1^ are the ones who try to compel you to get circumcised, doing so only to avoid being persecuted for the torture stake^&#42;2^ of the Christ.

[NOTE]
====
. Or “who want to look good outwardly.”
. See Glossary.
====

[[v48-6-13]]

^<<v48-6-13,13>>^ For even those who are getting circumcised do not keep the Law themselves, but they want you to be circumcised so that they may have cause for boasting about your flesh.

[[v48-6-14]]

^<<v48-6-14,14>>^ But may I never boast, except in the torture stake^&#42;1^ of our Lord Jesus Christ, through whom the world has been put to death^&#42;2^ with regard to me and I with regard to the world.

[NOTE]
====
. See Glossary.
. Or “executed on the stake.”
====

[[v48-6-15]]

^<<v48-6-15,15>>^ For neither is circumcision anything nor is uncircumcision, but a new creation is.

[[v48-6-16]]

^<<v48-6-16,16>>^ As for all those who walk orderly by this rule of conduct, peace and mercy be upon them, yes, upon the Israel of God.

[[v48-6-17]]

^<<v48-6-17,17>>^ From now on let no one make trouble for me, for I am bearing on my body the brand marks of a slave of Jesus.

[[v48-6-18]]

^<<v48-6-18,18>>^ The undeserved kindness of our Lord Jesus Christ be with the spirit you show, brothers. Amen.

'''

xref:048-galatians/048-galatians-005.adoc#v48-5-0[&#60; Capítulo Anterior] | <<v48-6-0,Topo>> | xref:049-ephesians/049-ephesians-001.adoc#v49-1-0[Próximo Capítulo &#62;]