include::./index.adoc[]

[[v48-2-0]]
=== To the Galatians, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v48-2-1]]

^<<v48-2-1,1>>^ Then after 14 years I again went up to Jerusalem with Barʹna·bas, also taking Titus along with me.

[[v48-2-2]]

^<<v48-2-2,2>>^ I went up as a result of a revelation, and I presented to them the good news that I am preaching among the nations. This was done privately, however, before the men who were highly regarded, to make sure that I was not running or had not run in vain.

[[v48-2-3]]

^<<v48-2-3,3>>^ Nevertheless, not even Titus, who was with me, was compelled to be circumcised, although he was a Greek.

[[v48-2-4]]

^<<v48-2-4,4>>^ But that matter came up because of the false brothers brought in quietly, who slipped in to spy on the freedom we enjoy in union with Christ Jesus, so that they might completely enslave us;

[[v48-2-5]]

^<<v48-2-5,5>>^ we did not yield in submission to them, no, not for a moment,^&#42;1^ so that the truth of the good news might continue with you.

[NOTE]
====
. Lit., “an hour.”
====

[[v48-2-6]]

^<<v48-2-6,6>>^ But regarding those who seemed to be important—whatever they were makes no difference to me, for God does not go by a man’s outward appearance—those highly regarded men imparted nothing new to me.

[[v48-2-7]]

^<<v48-2-7,7>>^ On the contrary, when they saw that I had been entrusted with the good news for those who are uncircumcised, just as Peter had been for those who are circumcised—

[[v48-2-8]]

^<<v48-2-8,8>>^ for the one who empowered Peter for an apostleship to those who are circumcised also empowered me for those who are of the nations—

[[v48-2-9]]

^<<v48-2-9,9>>^ and when they recognized the undeserved kindness that was given me, James and Ceʹphas^&#42;1^ and John, the ones who seemed to be pillars, gave Barʹna·bas and me the right hand of fellowship,^&#42;2^ so that we should go to the nations but they to those who are circumcised.

[NOTE]
====
. Also called Peter.
. Or “partnership.”
====

[[v48-2-10]]

^<<v48-2-10,10>>^ They asked only that we keep the poor in mind, and this I have also earnestly endeavored to do.

[[v48-2-11]]

^<<v48-2-11,11>>^ However, when Ceʹphas^&#42;1^ came to Antioch, I resisted^&#42;2^ him face-to-face, because he was clearly in the wrong.^&#42;3^

[NOTE]
====
. Also called Peter.
. Or “confronted.”
. Or “he stood condemned.”
====

[[v48-2-12]]

^<<v48-2-12,12>>^ For before certain men from James arrived, he used to eat with people of the nations; but when they arrived, he stopped doing this and separated himself, fearing those of the circumcised class.

[[v48-2-13]]

^<<v48-2-13,13>>^ The rest of the Jews also joined him in putting on this pretense,^&#42;1^ so that even Barʹna·bas was led along with them in their pretense.^&#42;2^

[NOTE]
====
. Or “hypocrisy.”
. Or “hypocrisy.”
====

[[v48-2-14]]

^<<v48-2-14,14>>^ But when I saw that they were not walking in step with the truth of the good news, I said to Ceʹphas^&#42;1^ before them all: “If you, though you are a Jew, live as the nations do and not as Jews do, how can you compel people of the nations to live according to Jewish practice?”

[NOTE]
====
. Also called Peter.
====

[[v48-2-15]]

^<<v48-2-15,15>>^ We who are Jews by birth, and not sinners from the nations,

[[v48-2-16]]

^<<v48-2-16,16>>^ recognize that a man is declared righteous, not by works of law, but only through faith in Jesus Christ. So we have put our faith in Christ Jesus, so that we may be declared righteous by faith in Christ and not by works of law, for no one^&#42;1^ will be declared righteous by works of law.

[NOTE]
====
. Lit., “flesh.”
====

[[v48-2-17]]

^<<v48-2-17,17>>^ Now if we have also been found sinners while seeking to be declared righteous by means of Christ, is Christ then sin’s minister? Certainly not!

[[v48-2-18]]

^<<v48-2-18,18>>^ If the very things that I once tore down I build up again, I demonstrate that I am a transgressor.

[[v48-2-19]]

^<<v48-2-19,19>>^ For through law I died toward law, so that I might become alive toward God.

[[v48-2-20]]

^<<v48-2-20,20>>^ I am nailed to the stake along with Christ. It is no longer I who live, but it is Christ who is living in union with me. Indeed, the life that I now live in the flesh I live by faith in the Son of God, who loved me and handed himself over for me.

[[v48-2-21]]

^<<v48-2-21,21>>^ I do not reject^&#42;1^ the undeserved kindness of God, for if righteousness is through law, Christ actually died for nothing.

[NOTE]
====
. Or “shove aside.”
====

'''

xref:048-galatians/048-galatians-001.adoc#v48-1-0[&#60; Capítulo Anterior] | <<v48-2-0,Topo>> | xref:048-galatians/048-galatians-003.adoc#v48-3-0[Próximo Capítulo &#62;]