include::./index.adoc[]

[[v1-8-0]]
=== Genesis, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-8-1]]

^<<v1-8-1,1>>^ But God gave attention to^&#42;1^ Noah and to all the wild animals and domestic animals that were with him in the ark, and God caused a wind to blow over the earth, and the waters began to subside.

[NOTE]
====
. Lit., “remembered.”
====

[[v1-8-2]]

^<<v1-8-2,2>>^ The springs of the watery deep and the floodgates of the heavens were stopped up, so the rain from the heavens stopped falling.^&#42;1^

[NOTE]
====
. Or “was restrained.”
====

[[v1-8-3]]

^<<v1-8-3,3>>^ Then the waters began to recede progressively from the earth. By the end of 150 days, the waters had subsided.

[[v1-8-4]]

^<<v1-8-4,4>>^ In the seventh month, on the 17th day of the month, the ark came to rest on the mountains of Arʹa·rat.

[[v1-8-5]]

^<<v1-8-5,5>>^ And the waters were steadily decreasing until the tenth month. In the tenth month, on the first of the month, the tops of the mountains appeared.

[[v1-8-6]]

^<<v1-8-6,6>>^ So at the end of 40 days, Noah opened the window that he had made in the ark

[[v1-8-7]]

^<<v1-8-7,7>>^ and sent out a raven; it continued flying outside and returning, until the waters dried off the earth.

[[v1-8-8]]

^<<v1-8-8,8>>^ Later he sent out a dove to see whether the waters had receded from the surface of the ground.

[[v1-8-9]]

^<<v1-8-9,9>>^ The dove did not find any resting-place to perch,^&#42;1^ so it returned to him into the ark because the waters were still covering the surface of the whole earth. So he reached his hand out and brought it inside the ark.

[NOTE]
====
. Or “for the sole of its foot.”
====

[[v1-8-10]]

^<<v1-8-10,10>>^ He waited seven more days, and once again he sent out the dove from the ark.

[[v1-8-11]]

^<<v1-8-11,11>>^ When the dove came to him toward evening, he saw that there was a freshly plucked olive leaf in its bill! So Noah knew that the waters had receded from the earth.

[[v1-8-12]]

^<<v1-8-12,12>>^ He waited still another seven days. Then he sent out the dove, but it did not return to him anymore.

[[v1-8-13]]

^<<v1-8-13,13>>^ Now in the 601st year, in the first month, on the first day of the month, the waters had drained from the earth; and Noah removed the covering of the ark and saw that the surface of the ground was drying.

[[v1-8-14]]

^<<v1-8-14,14>>^ In the second month, on the 27th day of the month, the earth had dried off.

[[v1-8-15]]

^<<v1-8-15,15>>^ God now said to Noah:

[[v1-8-16]]

^<<v1-8-16,16>>^ “Go out of the ark, you, your wife, your sons, and your sons’ wives.

[[v1-8-17]]

^<<v1-8-17,17>>^ Bring out with you all the living creatures of every sort of flesh, of the flying creatures and of the animals and of all the creeping animals of the earth, that they may multiply^&#42;1^ on the earth and be fruitful and become many on the earth.”

[NOTE]
====
. Or “swarm.”
====

[[v1-8-18]]

^<<v1-8-18,18>>^ So Noah went out, together with his sons, his wife, and his sons’ wives.

[[v1-8-19]]

^<<v1-8-19,19>>^ Every living creature, every creeping animal and every flying creature, everything that moves on the earth, went out of the ark by families.

[[v1-8-20]]

^<<v1-8-20,20>>^ Then Noah built an altar to Jehovah and took some of all the clean animals and of all the clean flying creatures and offered burnt offerings on the altar.

[[v1-8-21]]

^<<v1-8-21,21>>^ And Jehovah began to smell a pleasing^&#42;1^ aroma. So Jehovah said in his heart: “Never again will I curse^&#42;2^ the ground on man’s account, for the inclination of the heart of man is bad from his youth up; and never again will I strike down every living thing as I have done.

[NOTE]
====
. Or “appeasing; soothing.” Lit., “restful.”
. Or “call down evil upon.”
====

[[v1-8-22]]

^<<v1-8-22,22>>^ From now on, the earth will never cease to have seed-sowing and harvest, cold and heat, summer and winter, and day and night.”

'''

xref:001-genesis/001-genesis-007.adoc#v1-7-0[&#60; Capítulo Anterior] | <<v1-8-0,Topo>> | xref:001-genesis/001-genesis-009.adoc#v1-9-0[Próximo Capítulo &#62;]