include::./index.adoc[]

[[v1-48-0]]
=== Genesis, 48
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-48-1]]

^<<v1-48-1,1>>^ After these things, Joseph was told: “Look, your father is getting weak.” At that he took his two sons Ma·nasʹseh and Eʹphra·im with him.

[[v1-48-2]]

^<<v1-48-2,2>>^ Then Jacob was told: “Here your son Joseph has come to you.” So Israel gathered his strength and sat up on his bed.

[[v1-48-3]]

^<<v1-48-3,3>>^ And Jacob said to Joseph:
“God Almighty appeared to me at Luz in the land of Caʹnaan and blessed me.

[[v1-48-4]]

^<<v1-48-4,4>>^ And he said to me, ‘I am making you fruitful, and I will make you many, and I will transform you into a congregation of peoples, and I will give this land to your offspring^&#42;1^ after you as a lasting possession.’

[NOTE]
====
. Lit., “seed.”
====

[[v1-48-5]]

^<<v1-48-5,5>>^ Now your two sons who were born to you in the land of Egypt before I came to you in Egypt are mine. Eʹphra·im and Ma·nasʹseh will become mine just as Reuʹben and Simʹe·on are mine.

[[v1-48-6]]

^<<v1-48-6,6>>^ But the children born to you after them will become yours. They will be called by the name of their brothers in their inheritance.

[[v1-48-7]]

^<<v1-48-7,7>>^ As for me, when I was coming from Padʹdan, Rachel died alongside me in the land of Caʹnaan, while there was yet a good stretch of land before coming to Ephʹrath. So I buried her there on the way to Ephʹrath, that is, Bethʹle·hem.”

[[v1-48-8]]

^<<v1-48-8,8>>^ Then Israel saw Joseph’s sons and asked: “Who are these?”

[[v1-48-9]]

^<<v1-48-9,9>>^ So Joseph said to his father: “They are my sons whom God has given me in this place.” At this he said: “Bring them to me, please, so that I may bless them.”

[[v1-48-10]]

^<<v1-48-10,10>>^ Now the eyes of Israel were failing from age, and he was unable to see. So Joseph brought them close to him, and he kissed them and embraced them.

[[v1-48-11]]

^<<v1-48-11,11>>^ Israel said to Joseph: “I never imagined I would see your face, but here God has also let me see your offspring.”^&#42;1^

[NOTE]
====
. Lit., “seed.”
====

[[v1-48-12]]

^<<v1-48-12,12>>^ Joseph then removed them from Israel’s knees, and he bowed down with his face to the ground.

[[v1-48-13]]

^<<v1-48-13,13>>^ Joseph now took the two of them, Eʹphra·im with his right hand to Israel’s left and Ma·nasʹseh with his left hand to Israel’s right, and brought them close to him.

[[v1-48-14]]

^<<v1-48-14,14>>^ However, Israel put out his right hand and placed it on Eʹphra·im’s head, although he was the younger, and he placed his left hand on Ma·nasʹseh’s head. He purposely laid his hands this way, since Ma·nasʹseh was the firstborn.

[[v1-48-15]]

^<<v1-48-15,15>>^ Then he blessed Joseph and said:
“The true God before whom my fathers Abraham and Isaac walked,
The true God who has been shepherding me during all my life until this day,

[[v1-48-16]]

^<<v1-48-16,16>>^ The angel who has been recovering me from all calamity, bless the boys.
Let my name be called upon them and the name of my fathers, Abraham and Isaac,
Let them increase to a multitude in the earth.”

[[v1-48-17]]

^<<v1-48-17,17>>^ When Joseph saw that his father kept his right hand placed on Eʹphra·im’s head, it was displeasing to him, so he tried to take hold of his father’s hand to move it from Eʹphra·im’s head to Ma·nasʹseh’s head.

[[v1-48-18]]

^<<v1-48-18,18>>^ Joseph said to his father: “Not so, my father, because this is the firstborn. Put your right hand on his head.”

[[v1-48-19]]

^<<v1-48-19,19>>^ But his father kept refusing and said: “I know it, my son, I know it. He too will become a people, and he too will become great. Nevertheless, his younger brother will become greater than he will, and his offspring^&#42;1^ will become the full equivalent of nations.”

[NOTE]
====
. Lit., “seed.”
====

[[v1-48-20]]

^<<v1-48-20,20>>^ So he continued to bless them on that day, saying:
“Let Israel mention you when they pronounce blessings, saying,
‘May God make you like Eʹphra·im and like Ma·nasʹseh.’”
Thus he kept putting Eʹphra·im before Ma·nasʹseh.

[[v1-48-21]]

^<<v1-48-21,21>>^ Then Israel said to Joseph: “Look, I am dying, but God will certainly continue with you and return you to the land of your forefathers.

[[v1-48-22]]

^<<v1-48-22,22>>^ As for me, I do give you one portion of land^&#42;1^ more than to your brothers, which I took from the hand of the Amʹor·ites with my sword and my bow.”

[NOTE]
====
. Or “one slope of land.” Lit., “one shoulder.”
====

'''

xref:001-genesis/001-genesis-047.adoc#v1-47-0[&#60; Capítulo Anterior] | <<v1-48-0,Topo>> | xref:001-genesis/001-genesis-049.adoc#v1-49-0[Próximo Capítulo &#62;]