include::./index.adoc[]

[[v1-17-0]]
=== Genesis, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-17-1]]

^<<v1-17-1,1>>^ When Aʹbram was 99 years old, Jehovah appeared to Aʹbram and said to him: “I am God Almighty. Walk before me and prove yourself faultless.^&#42;1^

[NOTE]
====
. Or “blameless.”
====

[[v1-17-2]]

^<<v1-17-2,2>>^ I will establish my covenant between me and you, and I will multiply you very, very much.”

[[v1-17-3]]

^<<v1-17-3,3>>^ At this Aʹbram fell facedown, and God continued to speak with him, saying:

[[v1-17-4]]

^<<v1-17-4,4>>^ “As for me, look! my covenant is with you, and you will certainly become a father of many nations.

[[v1-17-5]]

^<<v1-17-5,5>>^ Your name will no longer be Aʹbram;^&#42;1^ your name will become Abraham,^&#42;2^ for I will make you a father of many nations.

[NOTE]
====
. Meaning “Father Is High (Exalted).”
. Meaning “Father of a Crowd (Multitude); Father of Many.”
====

[[v1-17-6]]

^<<v1-17-6,6>>^ I will make you very, very fruitful and will make you become nations, and kings will come from you.

[[v1-17-7]]

^<<v1-17-7,7>>^ “And I will keep my covenant between me and you and your offspring^&#42;1^ after you throughout their generations for an everlasting covenant, to be God to you and to your offspring^&#42;2^ after you.

[NOTE]
====
. Lit., “seed.”
. Lit., “seed.”
====

[[v1-17-8]]

^<<v1-17-8,8>>^ And I will give to you and to your offspring^&#42;1^ after you the land in which you lived as a foreigner—the entire land of Caʹnaan—for a lasting possession, and I will be their God.”

[NOTE]
====
. Lit., “seed.”
====

[[v1-17-9]]

^<<v1-17-9,9>>^ God said further to Abraham: “As for you, you are to keep my covenant, you and your offspring^&#42;1^ after you throughout their generations.

[NOTE]
====
. Lit., “seed.”
====

[[v1-17-10]]

^<<v1-17-10,10>>^ This is my covenant between me and you, that you and your offspring^&#42;1^ after you will keep: Every male among you must get circumcised.

[NOTE]
====
. Lit., “seed.”
====

[[v1-17-11]]

^<<v1-17-11,11>>^ You must circumcise the flesh of your foreskins, and it will serve as a sign of the covenant between me and you.

[[v1-17-12]]

^<<v1-17-12,12>>^ Throughout your generations, every male among you eight days old must be circumcised, anyone who is born in the house and anyone who is not one of your offspring^&#42;1^ and who was purchased with money from a foreigner.

[NOTE]
====
. Lit., “seed.”
====

[[v1-17-13]]

^<<v1-17-13,13>>^ Every man born in your house and every man purchased with your money must be circumcised, and my covenant in your flesh must serve as a lasting covenant.

[[v1-17-14]]

^<<v1-17-14,14>>^ If any uncircumcised male will not circumcise the flesh of his foreskin, that person^&#42;1^ must be cut off^&#42;2^ from his people. He has broken my covenant.”

[NOTE]
====
. Or “soul.”
. Or “put to death.”
====

[[v1-17-15]]

^<<v1-17-15,15>>^ Then God said to Abraham: “As for your wife Sarʹai,^&#42;1^ you must not call her Sarʹai, because Sarah^&#42;2^ will become her name.

[NOTE]
====
. Possibly meaning “Contentious.”
. Meaning “Princess.”
====

[[v1-17-16]]

^<<v1-17-16,16>>^ I will bless her and also give you a son by her; I will bless her and she will become nations; kings of peoples will come from her.”

[[v1-17-17]]

^<<v1-17-17,17>>^ At this Abraham fell facedown and began to laugh and to say in his heart: “Will a man 100 years old have a child born to him, and will Sarah, a woman 90 years old, give birth?”

[[v1-17-18]]

^<<v1-17-18,18>>^ So Abraham said to the true God: “O that Ishʹma·el might live before you!”

[[v1-17-19]]

^<<v1-17-19,19>>^ To this God said: “Your wife Sarah will definitely bear you a son, and you must name him Isaac.^&#42;1^ And I will establish my covenant with him for an everlasting covenant to his offspring^&#42;2^ after him.

[NOTE]
====
. Meaning “Laughter.”
. Lit., “seed.”
====

[[v1-17-20]]

^<<v1-17-20,20>>^ But as regards Ishʹma·el, I have heard you. Look! I will bless him and will make him fruitful and will multiply him very, very much. He will produce 12 chieftains, and I will make him become a great nation.

[[v1-17-21]]

^<<v1-17-21,21>>^ However, I will establish my covenant with Isaac, whom Sarah will bear to you at this appointed time next year.”

[[v1-17-22]]

^<<v1-17-22,22>>^ When God finished speaking with him, he went up from Abraham.

[[v1-17-23]]

^<<v1-17-23,23>>^ Abraham then took Ishʹma·el his son and all the men born in his house and everyone he had purchased with money, every male in the household of Abraham, and he circumcised the flesh of their foreskins on that very day, just as God had spoken with him.

[[v1-17-24]]

^<<v1-17-24,24>>^ Abraham was 99 years old when he had the flesh of his foreskin circumcised.

[[v1-17-25]]

^<<v1-17-25,25>>^ And Ishʹma·el his son was 13 years old when he had the flesh of his foreskin circumcised.

[[v1-17-26]]

^<<v1-17-26,26>>^ On that very day, Abraham was circumcised and also his son Ishʹma·el.

[[v1-17-27]]

^<<v1-17-27,27>>^ All the men of his household, anyone born in the house and anyone purchased with money from a foreigner, were also circumcised with him.

'''

xref:001-genesis/001-genesis-016.adoc#v1-16-0[&#60; Capítulo Anterior] | <<v1-17-0,Topo>> | xref:001-genesis/001-genesis-018.adoc#v1-18-0[Próximo Capítulo &#62;]