include::./index.adoc[]

[[v1-18-0]]
=== Genesis, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-18-1]]

^<<v1-18-1,1>>^ Afterward, Jehovah appeared to him among the big trees of Mamʹre while he was sitting at the entrance of the tent during the hottest part of the day.

[[v1-18-2]]

^<<v1-18-2,2>>^ He looked up and saw three men standing some distance from him. When he saw them, he ran from the entrance of the tent to meet them, and he bowed down to the ground.

[[v1-18-3]]

^<<v1-18-3,3>>^ Then he said: “Jehovah, if I have found favor in your eyes, please do not pass by your servant.

[[v1-18-4]]

^<<v1-18-4,4>>^ Please, let a little water be brought and have your feet washed; then recline under the tree.

[[v1-18-5]]

^<<v1-18-5,5>>^ Seeing that you have come here to your servant, let me bring a piece of bread so that you may refresh yourselves.^&#42;1^ Then you may go on your way.” At this they said: “All right. You may do as you have spoken.”

[NOTE]
====
. Lit., “strengthen your heart.”
====

[[v1-18-6]]

^<<v1-18-6,6>>^ So Abraham hurried to the tent to Sarah and said: “Quick! Get three measures^&#42;1^ of fine flour, knead the dough, and make loaves of bread.”

[NOTE]
====
. Lit., “seah measures.” A seah equaled 7.33 L (6.66 dry qt). See App. B14.
====

[[v1-18-7]]

^<<v1-18-7,7>>^ Next Abraham ran to the herd and chose a tender and good young bull. He gave it to the attendant, who hurried to prepare it.

[[v1-18-8]]

^<<v1-18-8,8>>^ He then took butter and milk and the young bull that he had prepared and set the food before them. Then he stood by them under the tree as they were eating.

[[v1-18-9]]

^<<v1-18-9,9>>^ They said to him: “Where is your wife Sarah?” He replied: “Here in the tent.”

[[v1-18-10]]

^<<v1-18-10,10>>^ So one of them continued: “I will surely return to you next year at this time, and look! your wife Sarah will have a son.” Now Sarah was listening at the tent entrance, which was behind the man.

[[v1-18-11]]

^<<v1-18-11,11>>^ Abraham and Sarah were old, being advanced in years. Sarah was past the age of childbearing.^&#42;1^

[NOTE]
====
. Lit., “The way according to women had ceased for Sarah.”
====

[[v1-18-12]]

^<<v1-18-12,12>>^ So Sarah began to laugh to herself, saying: “After I am worn out and my lord is old, will I really have this pleasure?”

[[v1-18-13]]

^<<v1-18-13,13>>^ Then Jehovah said to Abraham: “Why did Sarah laugh and say, ‘Am I really going to give birth even though I am old?’

[[v1-18-14]]

^<<v1-18-14,14>>^ Is anything too extraordinary for Jehovah? I will return to you next year at this appointed time, and Sarah will have a son.”

[[v1-18-15]]

^<<v1-18-15,15>>^ But Sarah denied it, saying, “I did not laugh!” for she was afraid. At this he said: “Yes! You did laugh.”

[[v1-18-16]]

^<<v1-18-16,16>>^ When the men got up to leave and looked down toward Sodʹom, Abraham was walking with them to escort them.

[[v1-18-17]]

^<<v1-18-17,17>>^ Jehovah said: “Am I keeping hidden from Abraham what I am going to do?

[[v1-18-18]]

^<<v1-18-18,18>>^ Why, Abraham is surely going to become a great and mighty nation, and all the nations of the earth will be blessed^&#42;1^ by means of him.

[NOTE]
====
. Or “will obtain a blessing for themselves.”
====

[[v1-18-19]]

^<<v1-18-19,19>>^ For I have come to know him in order that he may command his sons and his household after him to keep Jehovah’s way by doing what is right and just, so that Jehovah may bring about what he has promised concerning Abraham.”

[[v1-18-20]]

^<<v1-18-20,20>>^ Then Jehovah said: “The outcry against Sodʹom and Go·morʹrah is indeed great, and their sin is very heavy.

[[v1-18-21]]

^<<v1-18-21,21>>^ I will go down to see whether they are acting according to the outcry that has reached me. And if not, I can get to know it.”

[[v1-18-22]]

^<<v1-18-22,22>>^ Then the men left from there and went toward Sodʹom, but Jehovah remained with Abraham.

[[v1-18-23]]

^<<v1-18-23,23>>^ Then Abraham approached and said: “Will you really sweep away the righteous with the wicked?

[[v1-18-24]]

^<<v1-18-24,24>>^ Suppose there are 50 righteous men within the city. Will you, then, sweep them away and not pardon the place for the sake of the 50 righteous who are inside it?

[[v1-18-25]]

^<<v1-18-25,25>>^ It is unthinkable that you would act in this manner by putting the righteous man to death with the wicked one so that the outcome for the righteous man and the wicked is the same! It is unthinkable of you. Will the Judge of all the earth not do what is right?”

[[v1-18-26]]

^<<v1-18-26,26>>^ Then Jehovah said: “If I find in Sodʹom 50 righteous men in the city, I will pardon the whole place for their sake.”

[[v1-18-27]]

^<<v1-18-27,27>>^ But Abraham again responded: “Please, here I have presumed to speak to Jehovah, whereas I am dust and ashes.

[[v1-18-28]]

^<<v1-18-28,28>>^ Suppose the 50 righteous should lack five. Because of the five will you destroy the whole city?” To this he said: “I will not destroy it if I find there 45.”

[[v1-18-29]]

^<<v1-18-29,29>>^ But yet again he spoke to him and said: “Suppose 40 are found there.” He answered: “I will not do it for the sake of the 40.”

[[v1-18-30]]

^<<v1-18-30,30>>^ But he continued: “Jehovah, please, do not become hot with anger, but let me go on speaking: Suppose only 30 are found there.” He answered: “I will not do it if I find 30 there.”

[[v1-18-31]]

^<<v1-18-31,31>>^ But he continued: “Please, here I have presumed to speak to Jehovah: Suppose only 20 are found there.” He answered: “I will not destroy it for the sake of the 20.”

[[v1-18-32]]

^<<v1-18-32,32>>^ Finally he said: “Jehovah, please, do not become hot with anger, but let me speak just once more: Suppose only ten are found there.” He answered: “I will not destroy it for the sake of the ten.”

[[v1-18-33]]

^<<v1-18-33,33>>^ When Jehovah finished speaking to Abraham, he went his way and Abraham returned to his place.

'''

xref:001-genesis/001-genesis-017.adoc#v1-17-0[&#60; Capítulo Anterior] | <<v1-18-0,Topo>> | xref:001-genesis/001-genesis-019.adoc#v1-19-0[Próximo Capítulo &#62;]