include::./index.adoc[]

[[v1-39-0]]
=== Genesis, 39
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-39-1]]

^<<v1-39-1,1>>^ Now Joseph was taken down to Egypt, and an Egyptian named Potʹi·phar, a court official of Pharʹaoh and chief of the guard, bought him from the Ishʹma·el·ites who had taken him down there.

[[v1-39-2]]

^<<v1-39-2,2>>^ But Jehovah was with Joseph. As a result, he became successful and was put over the house of his master, the Egyptian.

[[v1-39-3]]

^<<v1-39-3,3>>^ And his master saw that Jehovah was with him and that Jehovah was making everything that he did successful.

[[v1-39-4]]

^<<v1-39-4,4>>^ Joseph kept finding favor in his eyes, and he became his personal attendant. So he appointed him over his house, and he put him in charge of all that was his.

[[v1-39-5]]

^<<v1-39-5,5>>^ From the time he appointed him over his house and in charge of all that was his, Jehovah kept blessing the house of the Egyptian because of Joseph, and Jehovah’s blessing came to be on all that he had in the house and in the field.

[[v1-39-6]]

^<<v1-39-6,6>>^ He eventually left everything that was his in Joseph’s care, and he gave no thought to anything except the food he was eating. Moreover, Joseph grew to be well-built and handsome.

[[v1-39-7]]

^<<v1-39-7,7>>^ Now after these things, the wife of his master began to cast her eyes on Joseph and say: “Lie down with me.”

[[v1-39-8]]

^<<v1-39-8,8>>^ But he refused and said to his master’s wife: “Here my master does not know what is with me in the house, and he has entrusted everything he has into my care.

[[v1-39-9]]

^<<v1-39-9,9>>^ There is no one greater in this house than I am, and he has not withheld from me anything at all except you, because you are his wife. So how could I commit this great badness and actually sin against God?”

[[v1-39-10]]

^<<v1-39-10,10>>^ So day after day she spoke to Joseph, but he never consented to lie with her or to remain with her.

[[v1-39-11]]

^<<v1-39-11,11>>^ But on one of the days when he went into the house to do his work, none of the household servants were in the house.

[[v1-39-12]]

^<<v1-39-12,12>>^ Then she grabbed hold of him by his garment and said: “Lie down with me!” But he left his garment in her hand and fled outside.

[[v1-39-13]]

^<<v1-39-13,13>>^ As soon as she saw that he had left his garment in her hand and had fled outside,

[[v1-39-14]]

^<<v1-39-14,14>>^ she began to cry out to the men of her house and to say to them: “Look! He brought to us this Hebrew man to make us a laughingstock. He came to me to lie down with me, but I began to cry out at the top of my voice.

[[v1-39-15]]

^<<v1-39-15,15>>^ Then as soon as he heard me raising my voice and screaming, he left his garment beside me and fled outside.”

[[v1-39-16]]

^<<v1-39-16,16>>^ After that she laid his garment beside her until his master came to his house.

[[v1-39-17]]

^<<v1-39-17,17>>^ Then she told him the same thing, saying: “The Hebrew servant whom you brought to us came to me to make me a laughingstock.

[[v1-39-18]]

^<<v1-39-18,18>>^ But as soon as I raised my voice and began to scream, he left his garment beside me and fled outside.”

[[v1-39-19]]

^<<v1-39-19,19>>^ As soon as his master heard the words his wife spoke to him, saying: “These are the things your servant did to me,” his anger blazed.

[[v1-39-20]]

^<<v1-39-20,20>>^ So Joseph’s master took him and gave him over to the prison, the place where the prisoners of the king were kept under arrest, and he remained there in the prison.

[[v1-39-21]]

^<<v1-39-21,21>>^ But Jehovah continued with Joseph and kept showing loyal love to him and granting him favor in the eyes of the chief officer of the prison.

[[v1-39-22]]

^<<v1-39-22,22>>^ So the chief officer of the prison put Joseph in charge of all the prisoners in the prison, and everything that they were doing there, he was the one having it done.

[[v1-39-23]]

^<<v1-39-23,23>>^ The chief officer of the prison was looking after absolutely nothing that was in Joseph’s care, for Jehovah was with Joseph and Jehovah made whatever he did successful.

'''

xref:001-genesis/001-genesis-038.adoc#v1-38-0[&#60; Capítulo Anterior] | <<v1-39-0,Topo>> | xref:001-genesis/001-genesis-040.adoc#v1-40-0[Próximo Capítulo &#62;]