include::./index.adoc[]

[[v1-12-0]]
=== Genesis, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-12-1]]

^<<v1-12-1,1>>^ And Jehovah said to Aʹbram: “Go out from your land and away from your relatives and from the house of your father to the land that I will show you.

[[v1-12-2]]

^<<v1-12-2,2>>^ I will make you a great nation, and I will bless you, and I will make your name great, and you will become a blessing.

[[v1-12-3]]

^<<v1-12-3,3>>^ I will bless those who bless you, and I will curse him who calls down evil on you, and all the families of the ground will certainly be blessed^&#42;1^ by means of you.”

[NOTE]
====
. Or “will obtain a blessing for themselves.”
====

[[v1-12-4]]

^<<v1-12-4,4>>^ So Aʹbram went just as Jehovah had told him, and Lot went with him. Aʹbram was 75 years old when he left Haʹran.

[[v1-12-5]]

^<<v1-12-5,5>>^ Aʹbram took his wife Sarʹai and Lot the son of his brother and all the goods that they had accumulated and the people^&#42;1^ whom they had acquired in Haʹran, and they set out for the land of Caʹnaan. When they reached the land of Caʹnaan,

[NOTE]
====
. Or “souls.”
====

[[v1-12-6]]

^<<v1-12-6,6>>^ Aʹbram traveled through the land as far as the site of Sheʹchem, near the big trees of Moʹreh. At that time the Caʹnaan·ites were in the land.

[[v1-12-7]]

^<<v1-12-7,7>>^ Jehovah then appeared to Aʹbram and said: “To your offspring^&#42;1^ I am going to give this land.” So he built an altar there to Jehovah, who had appeared to him.

[NOTE]
====
. Lit., “seed.”
====

[[v1-12-8]]

^<<v1-12-8,8>>^ Later he moved from there to the mountainous region east of Bethʹel and pitched his tent with Bethʹel on the west and Aʹi on the east. There he built an altar to Jehovah and began to call on the name of Jehovah.

[[v1-12-9]]

^<<v1-12-9,9>>^ Afterward, Aʹbram broke camp and journeyed toward the Negʹeb, moving his camp from one place to another.

[[v1-12-10]]

^<<v1-12-10,10>>^ Now a famine arose in the land, and Aʹbram went down toward Egypt to reside there for a while,^&#42;1^ because the famine in the land was severe.

[NOTE]
====
. Or “to live there as a foreigner.”
====

[[v1-12-11]]

^<<v1-12-11,11>>^ As he was about to enter Egypt, he said to his wife Sarʹai: “Please listen! I know what a beautiful woman you are.

[[v1-12-12]]

^<<v1-12-12,12>>^ So when the Egyptians see you, they will surely say, ‘This is his wife.’ Then they will kill me but keep you alive.

[[v1-12-13]]

^<<v1-12-13,13>>^ Please say you are my sister, so that it may go well with me because of you, and my life will be spared.”^&#42;1^

[NOTE]
====
. Or “my soul will stay alive.”
====

[[v1-12-14]]

^<<v1-12-14,14>>^ As soon as Aʹbram entered Egypt, the Egyptians noticed that the woman was very beautiful.

[[v1-12-15]]

^<<v1-12-15,15>>^ And the princes of Pharʹaoh also saw her, and they began praising her to Pharʹaoh, so that the woman was taken to the house of Pharʹaoh.

[[v1-12-16]]

^<<v1-12-16,16>>^ He treated Aʹbram well because of her, and he acquired sheep, cattle, male and female donkeys, male and female servants, and camels.

[[v1-12-17]]

^<<v1-12-17,17>>^ Then Jehovah struck Pharʹaoh and his household with severe plagues because of Sarʹai, Aʹbram’s wife.

[[v1-12-18]]

^<<v1-12-18,18>>^ So Pharʹaoh called Aʹbram and said: “What is this you have done to me? Why did you not tell me that she was your wife?

[[v1-12-19]]

^<<v1-12-19,19>>^ Why did you say, ‘She is my sister,’ so that I was about to take her as my wife? Here is your wife. Take her and go!”

[[v1-12-20]]

^<<v1-12-20,20>>^ So Pharʹaoh gave his men orders concerning him, and they sent him away with his wife and all that he had.

'''

xref:001-genesis/001-genesis-011.adoc#v1-11-0[&#60; Capítulo Anterior] | <<v1-12-0,Topo>> | xref:001-genesis/001-genesis-013.adoc#v1-13-0[Próximo Capítulo &#62;]