include::./index.adoc[]

[[v1-45-0]]
=== Genesis, 45
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-45-1]]

^<<v1-45-1,1>>^ At this Joseph could no longer control himself before all his attendants. So he cried out: “Have everyone leave me!” No one else stayed with him while Joseph made himself known to his brothers.

[[v1-45-2]]

^<<v1-45-2,2>>^ Then he began to weep so loudly that the Egyptians heard it and Pharʹaoh’s house heard it.

[[v1-45-3]]

^<<v1-45-3,3>>^ Finally Joseph said to his brothers: “I am Joseph. Is my father still alive?” But his brothers were unable to answer him at all, because they were astonished on account of him.

[[v1-45-4]]

^<<v1-45-4,4>>^ So Joseph said to his brothers: “Come close to me, please.” With that they came close to him.
Then he said: “I am Joseph your brother, whom you sold into Egypt.

[[v1-45-5]]

^<<v1-45-5,5>>^ But now do not be upset and do not reproach one another because you sold me here; because God has sent me ahead of you for the preservation of life.

[[v1-45-6]]

^<<v1-45-6,6>>^ This is the second year of the famine in the land, and there are yet five years in which there will be no plowing or harvest.

[[v1-45-7]]

^<<v1-45-7,7>>^ But God sent me ahead of you in order to preserve for you a remnant on the earth^&#42;1^ and to keep you alive by a great deliverance.

[NOTE]
====
. Or “in the land.”
====

[[v1-45-8]]

^<<v1-45-8,8>>^ So, then, it was not you who sent me here, but it was the true God, in order to appoint me as chief adviser^&#42;1^ to Pharʹaoh and lord for all his house and ruler over all the land of Egypt.

[NOTE]
====
. Lit., “as father.”
====

[[v1-45-9]]

^<<v1-45-9,9>>^ “Return quickly to my father, and you must say to him, ‘This is what your son Joseph has said: “God has appointed me lord over all Egypt. Come down to me. Do not delay.

[[v1-45-10]]

^<<v1-45-10,10>>^ You must dwell in the land of Goʹshen, where you will be near me—you, your sons, your grandsons, your flocks, your herds, and everything you have.

[[v1-45-11]]

^<<v1-45-11,11>>^ I will supply you with food there, for there are yet five years of famine. Otherwise, you and your house and everything you have will come to poverty.”’

[[v1-45-12]]

^<<v1-45-12,12>>^ You and my brother Benjamin can now see with your own eyes that I am really the one speaking to you.

[[v1-45-13]]

^<<v1-45-13,13>>^ So you must tell my father about all my glory in Egypt and everything you have seen. Now hurry and bring my father down here.”

[[v1-45-14]]

^<<v1-45-14,14>>^ Then he embraced^&#42;1^ his brother Benjamin and gave way to weeping, and Benjamin wept with his arms around his neck.

[NOTE]
====
. Lit., “fell upon the neck of.”
====

[[v1-45-15]]

^<<v1-45-15,15>>^ And he kissed all his brothers and wept over them, and after that his brothers spoke with him.

[[v1-45-16]]

^<<v1-45-16,16>>^ The news reached the house of Pharʹaoh: “Joseph’s brothers have come!” It was good in the eyes of Pharʹaoh and his servants.

[[v1-45-17]]

^<<v1-45-17,17>>^ So Pharʹaoh said to Joseph: “Tell your brothers, ‘Do this: Load your beasts of burden and go to the land of Caʹnaan,

[[v1-45-18]]

^<<v1-45-18,18>>^ and take your father and your households and come here to me. I will give you the good things of the land of Egypt, and you will eat^&#42;1^ the richest^&#42;2^ part of the land.’

[NOTE]
====
. Or “live off.”
. Or “fat.”
====

[[v1-45-19]]

^<<v1-45-19,19>>^ And you are commanded to tell them: ‘Do this: Take wagons from the land of Egypt for your children and your wives, and you must bring your father on one of them and come here.

[[v1-45-20]]

^<<v1-45-20,20>>^ Do not worry about your belongings, for the best of all the land of Egypt is yours.’”

[[v1-45-21]]

^<<v1-45-21,21>>^ And the sons of Israel did so, and Joseph gave them wagons according to Pharʹaoh’s orders, and he gave them provisions for the journey.

[[v1-45-22]]

^<<v1-45-22,22>>^ To each of them he gave individual changes of clothing, but to Benjamin he gave 300 silver pieces and five changes of clothing.

[[v1-45-23]]

^<<v1-45-23,23>>^ And to his father he sent the following: ten donkeys carrying good things of Egypt and ten female donkeys carrying grain and bread and sustenance for his father for the journey.

[[v1-45-24]]

^<<v1-45-24,24>>^ So he sent his brothers off, and as they departed, he said to them: “Do not become upset with one another on the way.”

[[v1-45-25]]

^<<v1-45-25,25>>^ Then they went up from Egypt and came into the land of Caʹnaan to their father Jacob.

[[v1-45-26]]

^<<v1-45-26,26>>^ Then they reported to him: “Joseph is still alive, and he is the ruler over all the land of Egypt!” But his heart grew numb because he did not believe them.

[[v1-45-27]]

^<<v1-45-27,27>>^ When they went on telling him all the words that Joseph had spoken to them and when he saw the wagons that Joseph had sent to carry him, the spirit of their father Jacob began to revive.

[[v1-45-28]]

^<<v1-45-28,28>>^ Israel exclaimed: “It is enough! My son Joseph is still alive! I must go and see him before I die!”

'''

xref:001-genesis/001-genesis-044.adoc#v1-44-0[&#60; Capítulo Anterior] | <<v1-45-0,Topo>> | xref:001-genesis/001-genesis-046.adoc#v1-46-0[Próximo Capítulo &#62;]