include::./index.adoc[]

[[v1-26-0]]
=== Genesis, 26
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-26-1]]

^<<v1-26-1,1>>^ Now there was a famine in the land, in addition to the first famine that occurred in the days of Abraham, so that Isaac went to A·bimʹe·lech king of the Phi·lisʹtines, in Geʹrar.

[[v1-26-2]]

^<<v1-26-2,2>>^ Then Jehovah appeared to him and said: “Do not go down to Egypt. Dwell in the land that I designate to you.

[[v1-26-3]]

^<<v1-26-3,3>>^ Reside as a foreigner in this land, and I will continue with you and bless you because to you and to your offspring^&#42;1^ I will give all these lands, and I will carry out the oath that I swore to your father Abraham:

[NOTE]
====
. Lit., “seed.”
====

[[v1-26-4]]

^<<v1-26-4,4>>^ ‘I will multiply your offspring^&#42;1^ like the stars of the heavens; and I will give to your offspring^&#42;2^ all these lands; and by means of your offspring,^&#42;3^ all nations of the earth will obtain a blessing for themselves,’

[NOTE]
====
. Lit., “seed.”
. Lit., “seed.”
. Lit., “seed.”
====

[[v1-26-5]]

^<<v1-26-5,5>>^ on account of the fact that Abraham listened to my voice and continued to keep my requirements, my commands, my statutes, and my laws.”

[[v1-26-6]]

^<<v1-26-6,6>>^ So Isaac continued to dwell in Geʹrar.

[[v1-26-7]]

^<<v1-26-7,7>>^ When the men of the place kept asking about his wife, he would say: “She is my sister.” He was afraid to say, “She is my wife,” for he said, “The men of the place might kill me because of Re·bekʹah,” for she was beautiful in appearance.

[[v1-26-8]]

^<<v1-26-8,8>>^ After some time had passed, A·bimʹe·lech king of the Phi·lisʹtines was looking out of the window, and he saw Isaac displaying affection for^&#42;1^ Re·bekʹah his wife.

[NOTE]
====
. Or “embracing.”
====

[[v1-26-9]]

^<<v1-26-9,9>>^ At once A·bimʹe·lech called Isaac and said: “She is actually your wife! Why did you say, ‘She is my sister’?” At this Isaac said to him: “I said it for fear I should die because of her.”

[[v1-26-10]]

^<<v1-26-10,10>>^ But A·bimʹe·lech continued: “What have you done to us? One of the people could easily have lain down with your wife, and you would have brought guilt upon us!”

[[v1-26-11]]

^<<v1-26-11,11>>^ Then A·bimʹe·lech commanded all the people, saying: “Anybody touching this man and his wife will surely be put to death!”

[[v1-26-12]]

^<<v1-26-12,12>>^ And Isaac began to sow seed in that land, and in that year he reaped 100 times what he sowed, for Jehovah was blessing him.

[[v1-26-13]]

^<<v1-26-13,13>>^ The man became wealthy, and he continued to prosper until he became very wealthy.

[[v1-26-14]]

^<<v1-26-14,14>>^ He acquired flocks of sheep and herds of cattle and a large body of servants, and the Phi·lisʹtines began to envy him.

[[v1-26-15]]

^<<v1-26-15,15>>^ So the Phi·lisʹtines took soil and stopped up all the wells that his father’s servants had dug in the days of Abraham.

[[v1-26-16]]

^<<v1-26-16,16>>^ A·bimʹe·lech then said to Isaac: “Move from our neighborhood, for you have grown far stronger than we are.”

[[v1-26-17]]

^<<v1-26-17,17>>^ So Isaac moved from there and encamped in the valley^&#42;1^ of Geʹrar and began dwelling there.

[NOTE]
====
. Or “wadi.”
====

[[v1-26-18]]

^<<v1-26-18,18>>^ And Isaac again dug the wells that had been dug in the days of his father Abraham but that the Phi·lisʹtines had stopped up after Abraham’s death, and he called them by the names that his father had given them.

[[v1-26-19]]

^<<v1-26-19,19>>^ When the servants of Isaac were digging in the valley,^&#42;1^ they found a well of fresh water.

[NOTE]
====
. Or “wadi.”
====

[[v1-26-20]]

^<<v1-26-20,20>>^ And the shepherds of Geʹrar began quarreling with the shepherds of Isaac, saying: “The water is ours!” So he named the well Eʹsek,^&#42;1^ because they had quarreled with him.

[NOTE]
====
. Meaning “Contention.”
====

[[v1-26-21]]

^<<v1-26-21,21>>^ And they started digging another well, and they began quarreling over it also. So he named it Sitʹnah.^&#42;1^

[NOTE]
====
. Meaning “Accusation.”
====

[[v1-26-22]]

^<<v1-26-22,22>>^ Later he moved away from there and dug another well, but they did not quarrel over it. So he named it Re·hoʹboth^&#42;1^ and said: “It is because now Jehovah has given us ample room and has made us fruitful in the land.”

[NOTE]
====
. Meaning “Broad Places.”
====

[[v1-26-23]]

^<<v1-26-23,23>>^ Then he went up from there to Beʹer-sheʹba.

[[v1-26-24]]

^<<v1-26-24,24>>^ That night Jehovah appeared to him and said: “I am the God of your father Abraham. Do not be afraid, for I am with you, and I will bless you and multiply your offspring^&#42;1^ on account of Abraham my servant.”

[NOTE]
====
. Lit., “seed.”
====

[[v1-26-25]]

^<<v1-26-25,25>>^ So he built an altar there and called on the name of Jehovah. And Isaac pitched his tent there, and his servants dug a well there.

[[v1-26-26]]

^<<v1-26-26,26>>^ Later A·bimʹe·lech came to him from Geʹrar with A·huzʹzath his personal adviser and Phiʹcol the chief of his army.

[[v1-26-27]]

^<<v1-26-27,27>>^ At this Isaac said to them: “Why have you come to me, seeing that you hated me and sent me away from your neighborhood?”

[[v1-26-28]]

^<<v1-26-28,28>>^ To this they said: “We have clearly seen that Jehovah has been with you. So we said, ‘Let there, please, be an oath of obligation between us and you, and let us make a covenant with you

[[v1-26-29]]

^<<v1-26-29,29>>^ that you will do nothing bad to us just as we have not harmed you, seeing that we have done only good to you in that we sent you away in peace. You now are the blessed of Jehovah.’”

[[v1-26-30]]

^<<v1-26-30,30>>^ Then he made a feast for them, and they ate and drank.

[[v1-26-31]]

^<<v1-26-31,31>>^ In the morning they got up early and swore an oath to each other. After that Isaac sent them away, and they went from him in peace.

[[v1-26-32]]

^<<v1-26-32,32>>^ On that day the servants of Isaac came and reported to him about the well that they had dug, and they told him: “We have found water!”

[[v1-26-33]]

^<<v1-26-33,33>>^ So he named it Shiʹbah. That is why the name of the city is Beʹer-sheʹba to this day.

[[v1-26-34]]

^<<v1-26-34,34>>^ When Eʹsau was 40 years old, he took as wife Juʹdith the daughter of Be·eʹri the Hitʹtite and also Basʹe·math the daughter of Eʹlon the Hitʹtite.

[[v1-26-35]]

^<<v1-26-35,35>>^ They were a source of great grief^&#42;1^ to Isaac and Re·bekʹah.

[NOTE]
====
. Lit., “bitterness of spirit.”
====

'''

xref:001-genesis/001-genesis-025.adoc#v1-25-0[&#60; Capítulo Anterior] | <<v1-26-0,Topo>> | xref:001-genesis/001-genesis-027.adoc#v1-27-0[Próximo Capítulo &#62;]