include::./index.adoc[]

[[v1-19-0]]
=== Genesis, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-19-1]]

^<<v1-19-1,1>>^ The two angels arrived at Sodʹom by evening, and Lot was sitting in the gate of Sodʹom. When Lot saw them, he got up to meet them and bowed down with his face to the earth.

[[v1-19-2]]

^<<v1-19-2,2>>^ And he said: “Please, my lords, turn aside, please, into the house of your servant and stay overnight and have your feet washed. Then you may get up early and travel on your way.” To this they said: “No, we will stay overnight in the public square.”

[[v1-19-3]]

^<<v1-19-3,3>>^ But he was so insistent with them that they went with him to his house. Then he made a feast for them, and he baked unleavened bread, and they ate.

[[v1-19-4]]

^<<v1-19-4,4>>^ Before they could lie down to sleep, the men of the city—the men of Sodʹom from boy to old man, all of them—surrounded the house in one mob.

[[v1-19-5]]

^<<v1-19-5,5>>^ And they kept calling out to Lot and saying to him: “Where are the men who came in to you tonight? Bring them out to us so that we may have sex with them.”

[[v1-19-6]]

^<<v1-19-6,6>>^ Then Lot went out to them to the doorway, and he shut the door behind him.

[[v1-19-7]]

^<<v1-19-7,7>>^ He said: “Please, my brothers, do not act wickedly.

[[v1-19-8]]

^<<v1-19-8,8>>^ Please, here I have two daughters who have never had sexual relations with a man. Please, let me bring them out to you for you to do to them whatever seems good to you. But do not do anything to these men, for they have come under the shelter^&#42;1^ of my roof.”

[NOTE]
====
. Or “protection.” Lit., “shadow.”
====

[[v1-19-9]]

^<<v1-19-9,9>>^ At this they said: “Stand back!” And they added: “This lone foreigner came to live here, and yet he dares to judge us! Now we are going to do worse to you than to them.” And they crowded in^&#42;1^ on Lot and moved forward to break down the door.

[NOTE]
====
. Or “pressed heavily.”
====

[[v1-19-10]]

^<<v1-19-10,10>>^ So the men reached out their hands and brought Lot into the house with them, and they shut the door.

[[v1-19-11]]

^<<v1-19-11,11>>^ But they struck the men who were at the entrance of the house with blindness, from the least to the greatest, so that they wore themselves out trying to find the doorway.

[[v1-19-12]]

^<<v1-19-12,12>>^ Then the men said to Lot: “Do you have anyone else here? Sons-in-law, your sons, your daughters, and all your people in the city, bring out of this place!

[[v1-19-13]]

^<<v1-19-13,13>>^ For we are going to destroy this place, because the outcry against them has indeed grown great^&#42;1^ before Jehovah, so that Jehovah sent us to destroy the city.”

[NOTE]
====
. Or “loud.”
====

[[v1-19-14]]

^<<v1-19-14,14>>^ So Lot went out and began to speak to his sons-in-law who were to marry his daughters, and he kept saying: “Get up! Get out of this place, because Jehovah will destroy the city!” But to his sons-in-law, he seemed to be joking.

[[v1-19-15]]

^<<v1-19-15,15>>^ As dawn was breaking, the angels became urgent with Lot, saying: “Get up! Take your wife and your two daughters who are here with you, so that you will not be swept away in the error of the city!”

[[v1-19-16]]

^<<v1-19-16,16>>^ When he kept lingering, then because of Jehovah’s compassion for him, the men seized hold of his hand and the hand of his wife and the hands of his two daughters, and they brought him out and stationed him outside the city.

[[v1-19-17]]

^<<v1-19-17,17>>^ As soon as they had brought them to the outskirts, he said: “Escape for your life!^&#42;1^ Do not look behind you and do not stand still in any part of the district! Escape to the mountainous region so that you may not be swept away!”

[NOTE]
====
. Or “soul.”
====

[[v1-19-18]]

^<<v1-19-18,18>>^ Then Lot said to them: “Not there, please, Jehovah!

[[v1-19-19]]

^<<v1-19-19,19>>^ Please, now, your servant has found favor in your eyes and you are showing great kindness^&#42;1^ to me by preserving me^&#42;2^ alive, but I am not able to flee to the mountainous region because I am afraid that disaster may overtake me and I will die.

[NOTE]
====
. Or “loyal love.”
. Or “my soul.”
====

[[v1-19-20]]

^<<v1-19-20,20>>^ Please, now, this town is nearby and I can flee there; it is only a small place. May I, please, escape there? It is only a small place. Then I will survive.”^&#42;1^

[NOTE]
====
. Or “my soul will live on.”
====

[[v1-19-21]]

^<<v1-19-21,21>>^ So he said to him: “Very well, I will also show you consideration by not overthrowing the town you speak of.

[[v1-19-22]]

^<<v1-19-22,22>>^ Hurry! Escape there, because I cannot do anything until you arrive there!” That is why he named the town Zoʹar.^&#42;1^

[NOTE]
====
. Meaning “Smallness.”
====

[[v1-19-23]]

^<<v1-19-23,23>>^ The sun had risen over the land when Lot arrived at Zoʹar.

[[v1-19-24]]

^<<v1-19-24,24>>^ Then Jehovah made it rain sulfur and fire on Sodʹom and Go·morʹrah—it came from Jehovah, from the heavens.

[[v1-19-25]]

^<<v1-19-25,25>>^ So he overthrew these cities, yes, the entire district, including all the inhabitants of the cities and the plants of the ground.

[[v1-19-26]]

^<<v1-19-26,26>>^ But Lot’s wife, who was behind him, began to look back, and she became a pillar of salt.

[[v1-19-27]]

^<<v1-19-27,27>>^ Now Abraham got up early in the morning and went to the place where he had stood before Jehovah.

[[v1-19-28]]

^<<v1-19-28,28>>^ When he looked down toward Sodʹom and Go·morʹrah and all the land of the district, he saw quite a sight. There was dense smoke rising from the land like the dense smoke of a kiln!

[[v1-19-29]]

^<<v1-19-29,29>>^ So when God destroyed the cities of the district, God kept Abraham in mind by sending Lot out from the cities he overthrew, the cities where Lot had been dwelling.

[[v1-19-30]]

^<<v1-19-30,30>>^ Later Lot went up from Zoʹar with his two daughters and began living in the mountainous region, because he was afraid to live in Zoʹar. So he began living in a cave with his two daughters.

[[v1-19-31]]

^<<v1-19-31,31>>^ And the firstborn said to the younger: “Our father is old, and there is not a man in the land to have relations with us according to the custom of the whole earth.

[[v1-19-32]]

^<<v1-19-32,32>>^ Come, let us give our father wine to drink, and let us lie down with him and preserve offspring from our father.”

[[v1-19-33]]

^<<v1-19-33,33>>^ So that night they kept giving their father wine to drink; then the firstborn went in and lay down with her father, but he did not know when she lay down and when she got up.

[[v1-19-34]]

^<<v1-19-34,34>>^ Then on the next day, the firstborn said to the younger: “Here I lay down with my father last night. Let us give him wine to drink tonight also. Then you go in and lie down with him, and let us preserve offspring from our father.”

[[v1-19-35]]

^<<v1-19-35,35>>^ So that night also, they repeatedly gave their father wine to drink; then the younger went and lay down with him, but he did not know when she lay down and when she got up.

[[v1-19-36]]

^<<v1-19-36,36>>^ So both daughters of Lot became pregnant by their father.

[[v1-19-37]]

^<<v1-19-37,37>>^ The firstborn gave birth to a son and named him Moʹab. He is the father of the Moʹab·ites of today.

[[v1-19-38]]

^<<v1-19-38,38>>^ The younger also gave birth to a son, and she named him Ben-amʹmi. He is the father of the Amʹmon·ites of today.

'''

xref:001-genesis/001-genesis-018.adoc#v1-18-0[&#60; Capítulo Anterior] | <<v1-19-0,Topo>> | xref:001-genesis/001-genesis-020.adoc#v1-20-0[Próximo Capítulo &#62;]