include::./index.adoc[]

[[v1-2-0]]
=== Genesis, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-2-1]]

^<<v1-2-1,1>>^ Thus the heavens and the earth and everything in them^&#42;1^ were completed.

[NOTE]
====
. Lit., “and all their army.”
====

[[v1-2-2]]

^<<v1-2-2,2>>^ And by the seventh day, God had completed the work that he had been doing,^&#42;1^ and he began to rest on the seventh day from all his work that he had been doing.^&#42;2^

[NOTE]
====
. Or “making.”
. Or “making.”
====

[[v1-2-3]]

^<<v1-2-3,3>>^ And God went on to bless the seventh day and to declare it sacred, for on it God has been resting from all the work that he has created, all that he purposed to make.

[[v1-2-4]]

^<<v1-2-4,4>>^ This is a history of the heavens and the earth in the time they were created, in the day that Jehovah^&#42;1^ God made earth and heaven.

[NOTE]
====
. The first occurrence of God’s distinctive personal name, יהוה (YHWH). See App. A4.
====

[[v1-2-5]]

^<<v1-2-5,5>>^ No bush of the field was yet on the earth and no vegetation of the field had begun sprouting, because Jehovah God had not made it rain on the earth and there was no man to cultivate the ground.

[[v1-2-6]]

^<<v1-2-6,6>>^ But a mist would go up from the earth, and it watered the entire surface of the ground.

[[v1-2-7]]

^<<v1-2-7,7>>^ And Jehovah God went on to form the man out of dust from the ground and to blow into his nostrils the breath of life, and the man became a living person.^&#42;1^

[NOTE]
====
. Or “soul.” Hebrew, neʹphesh, which literally means “a breathing creature.” See Glossary.
====

[[v1-2-8]]

^<<v1-2-8,8>>^ Further, Jehovah God planted a garden in Eʹden, toward the east; and there he put the man whom he had formed.

[[v1-2-9]]

^<<v1-2-9,9>>^ Thus Jehovah God made to grow out of the ground every tree that was pleasing to look at and good for food and also the tree of life in the middle of the garden and the tree of the knowledge of good and bad.

[[v1-2-10]]

^<<v1-2-10,10>>^ Now there was a river flowing out of Eʹden to water the garden, and from there it divided into four rivers.^&#42;1^

[NOTE]
====
. Lit., “it became four heads.”
====

[[v1-2-11]]

^<<v1-2-11,11>>^ The name of the first is Piʹshon; it is the one encircling the entire land of Havʹi·lah, where there is gold.

[[v1-2-12]]

^<<v1-2-12,12>>^ The gold of that land is good. Bdellium gum and onyx stone are also there.

[[v1-2-13]]

^<<v1-2-13,13>>^ The name of the second river is Giʹhon; it is the one encircling the entire land of Cush.

[[v1-2-14]]

^<<v1-2-14,14>>^ The name of the third river is Hidʹde·kel;^&#42;1^ it is the one going to the east of As·syrʹi·a. And the fourth river is the Eu·phraʹtes.

[NOTE]
====
. Or “Tigris.”
====

[[v1-2-15]]

^<<v1-2-15,15>>^ Jehovah God took the man and settled him in the garden of Eʹden to cultivate it and to take care of it.

[[v1-2-16]]

^<<v1-2-16,16>>^ Jehovah God also gave this command to the man: “From every tree of the garden you may eat to satisfaction.

[[v1-2-17]]

^<<v1-2-17,17>>^ But as for the tree of the knowledge of good and bad, you must not eat from it, for in the day you eat from it you will certainly die.”

[[v1-2-18]]

^<<v1-2-18,18>>^ Then Jehovah God said: “It is not good for the man to continue to be alone. I am going to make a helper for him, as a complement of him.”

[[v1-2-19]]

^<<v1-2-19,19>>^ Now Jehovah God had been forming from the ground every wild animal of the field and every flying creature of the heavens, and he began bringing them to the man to see what he would call each one; and whatever the man would call each living creature,^&#42;1^ that became its name.

[NOTE]
====
. Or “soul.”
====

[[v1-2-20]]

^<<v1-2-20,20>>^ So the man named all the domestic animals and the flying creatures of the heavens and every wild animal of the field, but for man there was no helper as a complement of him.

[[v1-2-21]]

^<<v1-2-21,21>>^ So Jehovah God caused the man to fall into a deep sleep, and while he was sleeping, he took one of his ribs and then closed up the flesh over its place.

[[v1-2-22]]

^<<v1-2-22,22>>^ And Jehovah God built the rib that he had taken from the man into a woman, and he brought her to the man.

[[v1-2-23]]

^<<v1-2-23,23>>^ Then the man said:
“This is at last bone of my bones
And flesh of my flesh.
This one will be called Woman,
Because from man she was taken.”

[[v1-2-24]]

^<<v1-2-24,24>>^ That is why a man will leave his father and his mother and he will stick to^&#42;1^ his wife, and they will become one flesh.

[NOTE]
====
. Or “remain with.”
====

[[v1-2-25]]

^<<v1-2-25,25>>^ And both of them continued to be naked, the man and his wife; yet they were not ashamed.

'''

xref:001-genesis/001-genesis-001.adoc#v1-1-0[&#60; Capítulo Anterior] | <<v1-2-0,Topo>> | xref:001-genesis/001-genesis-003.adoc#v1-3-0[Próximo Capítulo &#62;]