include::./index.adoc[]

[[v1-5-0]]
=== Genesis, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-5-1]]

^<<v1-5-1,1>>^ This is the book of Adam’s history. In the day that God created Adam, he made him in the likeness of God.

[[v1-5-2]]

^<<v1-5-2,2>>^ Male and female he created them. On the day they were created, he blessed them and named them Man.^&#42;1^

[NOTE]
====
. Or “Adam; Mankind.”
====

[[v1-5-3]]

^<<v1-5-3,3>>^ Adam lived for 130 years and then became father to a son in his likeness, in his image, and he named him Seth.

[[v1-5-4]]

^<<v1-5-4,4>>^ After becoming father to Seth, Adam lived for 800 years. And he became father to sons and daughters.

[[v1-5-5]]

^<<v1-5-5,5>>^ So all the days of Adam’s life amounted to 930 years, and then he died.

[[v1-5-6]]

^<<v1-5-6,6>>^ Seth lived for 105 years and then became father to Eʹnosh.

[[v1-5-7]]

^<<v1-5-7,7>>^ After becoming father to Eʹnosh, Seth lived for 807 years. And he became father to sons and daughters.

[[v1-5-8]]

^<<v1-5-8,8>>^ So all the days of Seth amounted to 912 years, and then he died.

[[v1-5-9]]

^<<v1-5-9,9>>^ Eʹnosh lived for 90 years and then became father to Keʹnan.

[[v1-5-10]]

^<<v1-5-10,10>>^ After becoming father to Keʹnan, Eʹnosh lived for 815 years. And he became father to sons and daughters.

[[v1-5-11]]

^<<v1-5-11,11>>^ So all the days of Eʹnosh amounted to 905 years, and then he died.

[[v1-5-12]]

^<<v1-5-12,12>>^ Keʹnan lived for 70 years and then became father to Ma·halʹa·lel.

[[v1-5-13]]

^<<v1-5-13,13>>^ After becoming father to Ma·halʹa·lel, Keʹnan lived for 840 years. And he became father to sons and daughters.

[[v1-5-14]]

^<<v1-5-14,14>>^ So all the days of Keʹnan amounted to 910 years, and then he died.

[[v1-5-15]]

^<<v1-5-15,15>>^ Ma·halʹa·lel lived for 65 years and then became father to Jaʹred.

[[v1-5-16]]

^<<v1-5-16,16>>^ After becoming father to Jaʹred, Ma·halʹa·lel lived for 830 years. And he became father to sons and daughters.

[[v1-5-17]]

^<<v1-5-17,17>>^ So all the days of Ma·halʹa·lel amounted to 895 years, and then he died.

[[v1-5-18]]

^<<v1-5-18,18>>^ Jaʹred lived for 162 years and then became father to Eʹnoch.

[[v1-5-19]]

^<<v1-5-19,19>>^ After becoming father to Eʹnoch, Jaʹred lived for 800 years. And he became father to sons and daughters.

[[v1-5-20]]

^<<v1-5-20,20>>^ So all the days of Jaʹred amounted to 962 years, and then he died.

[[v1-5-21]]

^<<v1-5-21,21>>^ Eʹnoch lived for 65 years and then became father to Me·thuʹse·lah.

[[v1-5-22]]

^<<v1-5-22,22>>^ After becoming father to Me·thuʹse·lah, Eʹnoch continued to walk with the true God^&#42;1^ for 300 years. And he became father to sons and daughters.

[NOTE]
====
. Lit., “the God.” See Glossary.
====

[[v1-5-23]]

^<<v1-5-23,23>>^ So all the days of Eʹnoch amounted to 365 years.

[[v1-5-24]]

^<<v1-5-24,24>>^ Eʹnoch kept walking with the true God. Then he was no more, for God took him.

[[v1-5-25]]

^<<v1-5-25,25>>^ Me·thuʹse·lah lived for 187 years and then became father to Laʹmech.

[[v1-5-26]]

^<<v1-5-26,26>>^ After becoming father to Laʹmech, Me·thuʹse·lah lived for 782 years. And he became father to sons and daughters.

[[v1-5-27]]

^<<v1-5-27,27>>^ So all the days of Me·thuʹse·lah amounted to 969 years, and then he died.

[[v1-5-28]]

^<<v1-5-28,28>>^ Laʹmech lived for 182 years and then became father to a son.

[[v1-5-29]]

^<<v1-5-29,29>>^ He named him Noah,^&#42;1^ saying: “This one will bring us comfort^&#42;2^ from our labor and from the painful toil of our hands because of the ground that Jehovah has cursed.”

[NOTE]
====
. Probably meaning “Rest; Consolation.”
. Or “relief.”
====

[[v1-5-30]]

^<<v1-5-30,30>>^ After becoming father to Noah, Laʹmech lived for 595 years. And he became father to sons and daughters.

[[v1-5-31]]

^<<v1-5-31,31>>^ So all the days of Laʹmech amounted to 777 years, and then he died.

[[v1-5-32]]

^<<v1-5-32,32>>^ After Noah reached 500 years of age, he became father to Shem, Ham, and Jaʹpheth.

'''

xref:001-genesis/001-genesis-004.adoc#v1-4-0[&#60; Capítulo Anterior] | <<v1-5-0,Topo>> | xref:001-genesis/001-genesis-006.adoc#v1-6-0[Próximo Capítulo &#62;]