include::./index.adoc[]

[[v1-33-0]]
=== Genesis, 33
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-33-1]]

^<<v1-33-1,1>>^ Now Jacob raised his eyes and saw Eʹsau coming, and 400 men were with him. So he divided the children among Leʹah, Rachel, and the two female servants.

[[v1-33-2]]

^<<v1-33-2,2>>^ He put the female servants and their children in front, Leʹah and her children after them, and Rachel and Joseph behind them.

[[v1-33-3]]

^<<v1-33-3,3>>^ Then he himself went ahead of them and bowed down to the earth seven times as he came near to his brother.

[[v1-33-4]]

^<<v1-33-4,4>>^ But Eʹsau ran to meet him, and he embraced him and kissed him, and they burst into tears.

[[v1-33-5]]

^<<v1-33-5,5>>^ When he raised his eyes and saw the women and the children, he said: “Who are these with you?” to which he said: “The children with whom God has favored your servant.”

[[v1-33-6]]

^<<v1-33-6,6>>^ At that the female servants came forward with their children and bowed down,

[[v1-33-7]]

^<<v1-33-7,7>>^ and Leʹah too came forward with her children, and they bowed down. Then Joseph came forward with Rachel, and they bowed down.

[[v1-33-8]]

^<<v1-33-8,8>>^ Eʹsau said: “What is the purpose of all this camp of travelers that I have met?” He replied: “In order to find favor in the eyes of my lord.”

[[v1-33-9]]

^<<v1-33-9,9>>^ Then Eʹsau said: “I have a great many possessions, my brother. Keep what is yours.”

[[v1-33-10]]

^<<v1-33-10,10>>^ However, Jacob said: “No, please. If I have found favor in your eyes, you must take my gift from my hand, because I brought it so that I could see your face. And I have seen your face as though seeing God’s face, in that you received me with pleasure.

[[v1-33-11]]

^<<v1-33-11,11>>^ Take, please, the gift conveying my blessing that was brought to you, for God has favored me and I have everything I need.” And he continued to urge him, so that he took it.

[[v1-33-12]]

^<<v1-33-12,12>>^ Later Eʹsau said: “Let us move out and go, and let me go in advance of you.”

[[v1-33-13]]

^<<v1-33-13,13>>^ But he said to him: “My lord is aware that the children are delicate and that in my care are sheep and cattle nursing their young. If they are driven too quickly for one day, then the whole flock will die.

[[v1-33-14]]

^<<v1-33-14,14>>^ Let my lord, please, go on ahead of his servant, but I will continue the journey more slowly at the pace of my livestock and of the children until I come to my lord at Seʹir.”

[[v1-33-15]]

^<<v1-33-15,15>>^ Then Eʹsau said: “Please, let me leave some of my people with you.” To this he said: “Why do this? Just let me find favor in the eyes of my lord.”

[[v1-33-16]]

^<<v1-33-16,16>>^ So that day Eʹsau went on his way back to Seʹir.

[[v1-33-17]]

^<<v1-33-17,17>>^ And Jacob journeyed to Sucʹcoth, and he built a house for himself and he made shelters for his herd. That was why he named the place Sucʹcoth.^&#42;1^

[NOTE]
====
. Meaning “Booths; Shelters.”
====

[[v1-33-18]]

^<<v1-33-18,18>>^ After journeying from Padʹdan-aʹram, Jacob arrived safely at the city of Sheʹchem in the land of Caʹnaan, and he set up his camp near the city.

[[v1-33-19]]

^<<v1-33-19,19>>^ Then he acquired a portion of the field where he pitched his tent from the sons of Haʹmor, the father of Sheʹchem, for 100 pieces of money.

[[v1-33-20]]

^<<v1-33-20,20>>^ There he set up an altar and called it God, the God of Israel.

'''

xref:001-genesis/001-genesis-032.adoc#v1-32-0[&#60; Capítulo Anterior] | <<v1-33-0,Topo>> | xref:001-genesis/001-genesis-034.adoc#v1-34-0[Próximo Capítulo &#62;]