include::./index.adoc[]

[[v1-29-0]]
=== Genesis, 29
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-29-1]]

^<<v1-29-1,1>>^ After that Jacob resumed his journey and traveled on to the land of the people of the East.

[[v1-29-2]]

^<<v1-29-2,2>>^ Now he saw a well in the field and three droves of sheep lying down next to it, because they usually watered the droves from that well. There was a large stone over the mouth of the well.

[[v1-29-3]]

^<<v1-29-3,3>>^ When all the droves had been gathered there, they rolled away the stone from the mouth of the well, and they watered the flocks, after which they returned the stone to its place over the mouth of the well.

[[v1-29-4]]

^<<v1-29-4,4>>^ So Jacob said to them: “My brothers, what place are you from?” to which they said: “We are from Haʹran.”

[[v1-29-5]]

^<<v1-29-5,5>>^ He said to them: “Do you know Laʹban the grandson of Naʹhor?” to which they said: “We know him.”

[[v1-29-6]]

^<<v1-29-6,6>>^ At this he said to them: “Is he well?” They replied: “He is well. And here is his daughter Rachel coming with the sheep!”

[[v1-29-7]]

^<<v1-29-7,7>>^ Then he said: “It is still the middle of the day. It is not the time for gathering the herds. Water the sheep, and then go feed them.”

[[v1-29-8]]

^<<v1-29-8,8>>^ To this they said: “We are not allowed to do so until all the droves are gathered and they roll the stone away from the mouth of the well. Then we water the sheep.”

[[v1-29-9]]

^<<v1-29-9,9>>^ While he was yet speaking with them, Rachel came with her father’s sheep, for she was a shepherdess.

[[v1-29-10]]

^<<v1-29-10,10>>^ When Jacob saw Rachel, the daughter of Laʹban his mother’s brother, and the sheep of Laʹban, Jacob immediately approached and rolled the stone away from the mouth of the well and watered the sheep of Laʹban his mother’s brother.

[[v1-29-11]]

^<<v1-29-11,11>>^ Then Jacob kissed Rachel and raised his voice and burst into tears.

[[v1-29-12]]

^<<v1-29-12,12>>^ And Jacob began to tell Rachel that he was the relative^&#42;1^ of her father and that he was the son of Re·bekʹah. And she ran off and told her father.

[NOTE]
====
. Lit., “brother.”
====

[[v1-29-13]]

^<<v1-29-13,13>>^ As soon as Laʹban heard the report about Jacob the son of his sister, he ran to meet him. He embraced him and kissed him and brought him into his house. And he began to tell Laʹban all these things.

[[v1-29-14]]

^<<v1-29-14,14>>^ Laʹban said to him: “You are indeed my bone and my flesh.”^&#42;1^ So he stayed with him a full month.

[NOTE]
====
. Or “my blood relative.”
====

[[v1-29-15]]

^<<v1-29-15,15>>^ Laʹban then said to Jacob: “Just because you are my relative,^&#42;1^ should you serve me for nothing? Tell me, what are your wages to be?”

[NOTE]
====
. Lit., “brother.”
====

[[v1-29-16]]

^<<v1-29-16,16>>^ Now Laʹban had two daughters. The name of the older was Leʹah, and the name of the younger, Rachel.

[[v1-29-17]]

^<<v1-29-17,17>>^ But the eyes of Leʹah had no luster, whereas Rachel had become a very attractive and beautiful woman.

[[v1-29-18]]

^<<v1-29-18,18>>^ Jacob had fallen in love with Rachel, so he said: “I am willing to serve you seven years for your younger daughter Rachel.”

[[v1-29-19]]

^<<v1-29-19,19>>^ To this Laʹban said: “It is better for me to give her to you than to give her to another man. Keep dwelling with me.”

[[v1-29-20]]

^<<v1-29-20,20>>^ And Jacob served seven years for Rachel, but in his eyes they were like just a few days because of his love for her.

[[v1-29-21]]

^<<v1-29-21,21>>^ Then Jacob said to Laʹban: “Give over my wife because my days are up, and let me have relations with her.”

[[v1-29-22]]

^<<v1-29-22,22>>^ With that Laʹban gathered all the men of the place and made a feast.

[[v1-29-23]]

^<<v1-29-23,23>>^ But during the evening, he resorted to taking his daughter Leʹah and bringing her to him that he might have relations with her.

[[v1-29-24]]

^<<v1-29-24,24>>^ Laʹban also gave his female servant Zilʹpah to his daughter Leʹah as a servant.

[[v1-29-25]]

^<<v1-29-25,25>>^ In the morning Jacob saw that it was Leʹah! So he said to Laʹban: “What have you done to me? Was it not for Rachel that I served you? Why have you tricked me?”

[[v1-29-26]]

^<<v1-29-26,26>>^ To this Laʹban said: “It is not our custom here to give the younger woman before the firstborn.

[[v1-29-27]]

^<<v1-29-27,27>>^ Celebrate the week of this woman. After that you will also be given this other woman in exchange for serving me seven more years.”

[[v1-29-28]]

^<<v1-29-28,28>>^ Jacob did so and celebrated the week of this woman, after which he gave him his daughter Rachel as a wife.

[[v1-29-29]]

^<<v1-29-29,29>>^ Besides, Laʹban gave his female servant Bilʹhah to his daughter Rachel as her servant.

[[v1-29-30]]

^<<v1-29-30,30>>^ Then Jacob had relations also with Rachel, and he loved Rachel more than Leʹah, and he served him for another seven years.

[[v1-29-31]]

^<<v1-29-31,31>>^ When Jehovah saw that Leʹah was unloved,^&#42;1^ he then enabled her to become pregnant,^&#42;2^ but Rachel was barren.

[NOTE]
====
. Lit., “hated.”
. Lit., “he opened her womb.”
====

[[v1-29-32]]

^<<v1-29-32,32>>^ So Leʹah became pregnant and gave birth to a son and named him Reuʹben,^&#42;1^ for she said: “It is because Jehovah has looked upon my affliction, for now my husband will begin to love me.”

[NOTE]
====
. Meaning “See, a Son!”
====

[[v1-29-33]]

^<<v1-29-33,33>>^ And she again became pregnant and gave birth to a son and then said: “It is because Jehovah has listened, in that I was unloved, so he gave me this one also.” Then she named him Simʹe·on.^&#42;1^

[NOTE]
====
. Meaning “Hearing.”
====

[[v1-29-34]]

^<<v1-29-34,34>>^ And she became pregnant yet again and gave birth to a son and then said: “Now this time my husband will join himself to me, because I have borne him three sons.” Therefore, he was named Leʹvi.^&#42;1^

[NOTE]
====
. Meaning “Adherence; Joined.”
====

[[v1-29-35]]

^<<v1-29-35,35>>^ And she became pregnant once more and gave birth to a son and then said: “This time I will praise Jehovah.” She therefore named him Judah.^&#42;1^ After that she stopped giving birth.

[NOTE]
====
. Meaning “Praised; Object of Praise.”
====

'''

xref:001-genesis/001-genesis-028.adoc#v1-28-0[&#60; Capítulo Anterior] | <<v1-29-0,Topo>> | xref:001-genesis/001-genesis-030.adoc#v1-30-0[Próximo Capítulo &#62;]