include::./index.adoc[]

[[v1-3-0]]
=== Genesis, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-3-1]]

^<<v1-3-1,1>>^ Now the serpent was the most cautious^&#42;1^ of all the wild animals of the field that Jehovah God had made. So it said to the woman: “Did God really say that you must not eat from every tree of the garden?”

[NOTE]
====
. Or “shrewdest; craftiest.”
====

[[v1-3-2]]

^<<v1-3-2,2>>^ At this the woman said to the serpent: “We may eat of the fruit of the trees of the garden.

[[v1-3-3]]

^<<v1-3-3,3>>^ But God has said about the fruit of the tree that is in the middle of the garden: ‘You must not eat from it, no, you must not touch it; otherwise you will die.’”

[[v1-3-4]]

^<<v1-3-4,4>>^ At this the serpent said to the woman: “You certainly will not die.

[[v1-3-5]]

^<<v1-3-5,5>>^ For God knows that in the very day you eat from it, your eyes will be opened and you will be like God, knowing good and bad.”

[[v1-3-6]]

^<<v1-3-6,6>>^ Consequently, the woman saw that the tree was good for food and that it was something desirable to the eyes, yes, the tree was pleasing to look at. So she began taking of its fruit and eating it. Afterward, she also gave some to her husband when he was with her, and he began eating it.

[[v1-3-7]]

^<<v1-3-7,7>>^ Then the eyes of both of them were opened, and they realized that they were naked. So they sewed fig leaves together and made loin coverings for themselves.

[[v1-3-8]]

^<<v1-3-8,8>>^ Later they heard the voice of Jehovah God as he was walking in the garden about the breezy part of the day, and the man and his wife hid from the face of Jehovah God among the trees of the garden.

[[v1-3-9]]

^<<v1-3-9,9>>^ And Jehovah God kept calling to the man and saying to him: “Where are you?”

[[v1-3-10]]

^<<v1-3-10,10>>^ Finally he said: “I heard your voice in the garden, but I was afraid because I was naked, so I hid myself.”

[[v1-3-11]]

^<<v1-3-11,11>>^ At that he said: “Who told you that you were naked? Have you eaten from the tree from which I commanded you not to eat?”

[[v1-3-12]]

^<<v1-3-12,12>>^ The man said: “The woman whom you gave to be with me, she gave me fruit from the tree, so I ate.”

[[v1-3-13]]

^<<v1-3-13,13>>^ Jehovah God then said to the woman: “What is this you have done?” The woman replied: “The serpent deceived me, so I ate.”

[[v1-3-14]]

^<<v1-3-14,14>>^ Then Jehovah God said to the serpent: “Because you have done this, you are the cursed one out of all the domestic animals and out of all the wild animals of the field. On your belly you will go, and you will eat dust all the days of your life.

[[v1-3-15]]

^<<v1-3-15,15>>^ And I will put enmity^&#42;1^ between you and the woman and between your offspring^&#42;2^ and her offspring.^&#42;3^ He will crush^&#42;4^ your head, and you will strike^&#42;5^ him in the heel.”

[NOTE]
====
. Or “hostility.”
. Lit., “seed.”
. Lit., “seed.”
. Or “bruise; strike.”
. Or “bruise; crush.”
====

[[v1-3-16]]

^<<v1-3-16,16>>^ To the woman he said: “I will greatly increase the pain of your pregnancy; in pain you will give birth to children, and your longing will be for your husband, and he will dominate you.”

[[v1-3-17]]

^<<v1-3-17,17>>^ And to Adam^&#42;1^ he said: “Because you listened to your wife’s voice and ate from the tree concerning which I gave you this command, ‘You must not eat from it,’ cursed is the ground on your account. In pain you will eat its produce all the days of your life.

[NOTE]
====
. Meaning “Earthling Man; Mankind; Humankind.”
====

[[v1-3-18]]

^<<v1-3-18,18>>^ It will grow thorns and thistles for you, and you must eat the vegetation of the field.

[[v1-3-19]]

^<<v1-3-19,19>>^ In the sweat of your face you will eat bread^&#42;1^ until you return to the ground, for out of it you were taken. For dust you are and to dust you will return.”

[NOTE]
====
. Or “food.”
====

[[v1-3-20]]

^<<v1-3-20,20>>^ After this Adam named his wife Eve,^&#42;1^ because she was to become the mother of everyone living.

[NOTE]
====
. Meaning “Living One.”
====

[[v1-3-21]]

^<<v1-3-21,21>>^ And Jehovah God made long garments from skins for Adam and for his wife, to clothe them.

[[v1-3-22]]

^<<v1-3-22,22>>^ Jehovah God then said: “Here the man has become like one of us in knowing good and bad. Now in order that he may not put his hand out and take fruit also from the tree of life and eat and live forever,^&#42;1^—”

[NOTE]
====
. Or “to time indefinite.”
====

[[v1-3-23]]

^<<v1-3-23,23>>^ With that Jehovah God expelled him from the garden of Eʹden to cultivate the ground from which he had been taken.

[[v1-3-24]]

^<<v1-3-24,24>>^ So he drove the man out, and he posted at the east of the garden of Eʹden the cherubs and the flaming blade of a sword that was turning continuously to guard the way to the tree of life.

'''

xref:001-genesis/001-genesis-002.adoc#v1-2-0[&#60; Capítulo Anterior] | <<v1-3-0,Topo>> | xref:001-genesis/001-genesis-004.adoc#v1-4-0[Próximo Capítulo &#62;]