include::./index.adoc[]

[[v1-4-0]]
=== Genesis, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-4-1]]

^<<v1-4-1,1>>^ Now Adam had sexual relations with his wife Eve, and she became pregnant. When she gave birth to Cain, she said: “I have produced^&#42;1^ a male child with the help of Jehovah.”

[NOTE]
====
. Or “given birth to.”
====

[[v1-4-2]]

^<<v1-4-2,2>>^ Later she again gave birth, to his brother Abel.
Abel became a shepherd of the flock, but Cain became a cultivator of the ground.

[[v1-4-3]]

^<<v1-4-3,3>>^ After some time, Cain brought some fruits of the land as an offering to Jehovah.

[[v1-4-4]]

^<<v1-4-4,4>>^ But Abel brought some firstlings of his flock, including their fat. While Jehovah looked with favor on Abel and on his offering,

[[v1-4-5]]

^<<v1-4-5,5>>^ he did not look with any favor on Cain and on his offering. So Cain grew hot with anger and was dejected.^&#42;1^

[NOTE]
====
. Lit., “and his face fell.”
====

[[v1-4-6]]

^<<v1-4-6,6>>^ Then Jehovah said to Cain: “Why are you so angry and dejected?

[[v1-4-7]]

^<<v1-4-7,7>>^ If you turn to doing good, will you not be restored to favor?^&#42;1^ But if you do not turn to doing good, sin is crouching at the door, and its craving is to dominate you; but will you get the mastery over it?”

[NOTE]
====
. Or “will there not be an exaltation?”
====

[[v1-4-8]]

^<<v1-4-8,8>>^ After that Cain said to his brother Abel: “Let us go over into the field.” So while they were in the field, Cain assaulted his brother Abel and killed him.

[[v1-4-9]]

^<<v1-4-9,9>>^ Later on, Jehovah said to Cain: “Where is your brother Abel?” and he said: “I do not know. Am I my brother’s guardian?”

[[v1-4-10]]

^<<v1-4-10,10>>^ At this He said: “What have you done? Listen! Your brother’s blood is crying out to me from the ground.

[[v1-4-11]]

^<<v1-4-11,11>>^ And now you are cursed in banishment from the ground that has opened its mouth to receive your brother’s blood from your hand.

[[v1-4-12]]

^<<v1-4-12,12>>^ When you cultivate the ground, it will not give you back its produce.^&#42;1^ You will become a wanderer and a fugitive in the earth.”

[NOTE]
====
. Lit., “power.”
====

[[v1-4-13]]

^<<v1-4-13,13>>^ At this Cain said to Jehovah: “The punishment for my error is too great to bear.

[[v1-4-14]]

^<<v1-4-14,14>>^ Today you are driving me from the land,^&#42;1^ and I will be hidden from your face; and I will become a wanderer and a fugitive on the earth, and anyone who finds me will certainly kill me.”

[NOTE]
====
. Lit., “from the face of the ground.”
====

[[v1-4-15]]

^<<v1-4-15,15>>^ So Jehovah said to him: “For that reason, anyone who kills Cain will suffer vengeance seven times.”
So Jehovah set up^&#42;1^ a sign for Cain in order that no one finding him would strike him.

[NOTE]
====
. Or “established.”
====

[[v1-4-16]]

^<<v1-4-16,16>>^ Then Cain went away from before Jehovah and took up residence in the land of Exile,^&#42;1^ to the east of Eʹden.

[NOTE]
====
. Or “the land of Nod.”
====

[[v1-4-17]]

^<<v1-4-17,17>>^ Afterward Cain had sexual relations with his wife, and she became pregnant and gave birth to Eʹnoch. Then he engaged in building a city and named the city after his son Eʹnoch.

[[v1-4-18]]

^<<v1-4-18,18>>^ Later Iʹrad was born to Eʹnoch. And Iʹrad became father to Me·huʹja·el, and Me·huʹja·el became father to Me·thuʹsha·el, and Me·thuʹsha·el became father to Laʹmech.

[[v1-4-19]]

^<<v1-4-19,19>>^ Laʹmech took two wives for himself. The name of the first was Aʹdah, and the name of the second was Zilʹlah.

[[v1-4-20]]

^<<v1-4-20,20>>^ Aʹdah gave birth to Jaʹbal. He was the founder of those who dwell in tents and have livestock.

[[v1-4-21]]

^<<v1-4-21,21>>^ His brother’s name was Juʹbal. He was the founder of all those who play the harp and the pipe.^&#42;1^

[NOTE]
====
. Or “flute.”
====

[[v1-4-22]]

^<<v1-4-22,22>>^ Also, Zilʹlah gave birth to Tuʹbal-cain, who forged every sort of tool of copper and iron. And the sister of Tuʹbal-cain was Naʹa·mah.

[[v1-4-23]]

^<<v1-4-23,23>>^ Then Laʹmech composed these words for his wives Aʹdah and Zilʹlah:
“Hear my voice, you wives of Laʹmech;
Give ear to my saying:
A man I have killed for wounding me,
Yes, a young man for striking me.

[[v1-4-24]]

^<<v1-4-24,24>>^ If 7 times Cain is to be avenged,
Then Laʹmech 77 times.”

[[v1-4-25]]

^<<v1-4-25,25>>^ Adam again had sexual relations with his wife, and she gave birth to a son. She named him Seth^&#42;1^ because, as she said, “God has appointed for me another offspring^&#42;2^ in place of Abel, because Cain killed him.”

[NOTE]
====
. Meaning “Appointed; Put; Set.”
. Lit., “seed.”
====

[[v1-4-26]]

^<<v1-4-26,26>>^ There was also born to Seth a son, and he named him Eʹnosh. At that time people began calling on the name of Jehovah.

'''

xref:001-genesis/001-genesis-003.adoc#v1-3-0[&#60; Capítulo Anterior] | <<v1-4-0,Topo>> | xref:001-genesis/001-genesis-005.adoc#v1-5-0[Próximo Capítulo &#62;]