include::./index.adoc[]

[[v1-49-0]]
=== Genesis, 49
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-49-1]]

^<<v1-49-1,1>>^ And Jacob called his sons and said: “Gather yourselves together that I may tell you what will happen to you in the final part of the days.

[[v1-49-2]]

^<<v1-49-2,2>>^ Assemble yourselves and listen, you sons of Jacob, yes, listen to Israel your father.

[[v1-49-3]]

^<<v1-49-3,3>>^ “Reuʹben, you are my firstborn, my vigor and the beginning of my procreative power, the excellence of dignity and the excellence of strength.

[[v1-49-4]]

^<<v1-49-4,4>>^ With recklessness like turbulent waters, you will not excel, because you have gone up to your father’s bed. At that time you defiled^&#42;1^ my bed. He actually went on to it!

[NOTE]
====
. Or “profaned.”
====

[[v1-49-5]]

^<<v1-49-5,5>>^ “Simʹe·on and Leʹvi are brothers. Instruments of violence are their slaughter weapons.

[[v1-49-6]]

^<<v1-49-6,6>>^ Into their company do not come, O my soul.^&#42;1^ With their assembly do not join, O my honor,^&#42;2^ because in their anger they killed men, and for their pleasure they hamstrung bulls.

[NOTE]
====
. See Glossary.
. Or possibly, “disposition.”
====

[[v1-49-7]]

^<<v1-49-7,7>>^ Cursed be their anger, because it is cruel, and their fury, because it is harsh. Let me disperse them in Jacob, and let me scatter them in Israel.

[[v1-49-8]]

^<<v1-49-8,8>>^ “As for you, Judah, your brothers will praise you. Your hand will be on the neck of your enemies. The sons of your father will bow down before you.

[[v1-49-9]]

^<<v1-49-9,9>>^ Judah is a lion cub. From the prey, my son, you will certainly go up. He has crouched down and stretched himself out like a lion, and like a lion, who dares rouse him?

[[v1-49-10]]

^<<v1-49-10,10>>^ The scepter will not depart from Judah, neither the commander’s staff from between his feet, until Shiʹloh^&#42;1^ comes, and to him the obedience of the peoples will belong.

[NOTE]
====
. Meaning “He Whose It Is; He to Whom It Belongs.”
====

[[v1-49-11]]

^<<v1-49-11,11>>^ Tying his donkey to a vine and his donkey’s colt to a choice vine, he will wash his clothing in wine and his garment in the blood of grapes.

[[v1-49-12]]

^<<v1-49-12,12>>^ Dark red are his eyes from wine, and his teeth are white from milk.

[[v1-49-13]]

^<<v1-49-13,13>>^ “Zebʹu·lun will reside by the seashore, by the shore where the ships lie anchored, and his remote border will be toward Siʹdon.

[[v1-49-14]]

^<<v1-49-14,14>>^ “Isʹsa·char is a strong-boned donkey, lying down between the two saddlebags.

[[v1-49-15]]

^<<v1-49-15,15>>^ And he will see that the resting-place is good and that the land is pleasant. He will bend his shoulder to bear the burden and will submit to forced labor.

[[v1-49-16]]

^<<v1-49-16,16>>^ “Dan will judge his people as one of the tribes of Israel.

[[v1-49-17]]

^<<v1-49-17,17>>^ Let Dan be a serpent by the roadside, a horned snake beside the path, that bites the heels of the horse so that its rider falls backward.

[[v1-49-18]]

^<<v1-49-18,18>>^ I will wait for salvation from you, O Jehovah.

[[v1-49-19]]

^<<v1-49-19,19>>^ “As for Gad, a marauder band will raid him, but he will raid at their heels.

[[v1-49-20]]

^<<v1-49-20,20>>^ “Ashʹer’s bread^&#42;1^ will be abundant,^&#42;2^ and he will provide food fit for a king.

[NOTE]
====
. Or “food.”
. Lit., “fat.”
====

[[v1-49-21]]

^<<v1-49-21,21>>^ “Naphʹta·li is a slender doe. He is speaking words of elegance.

[[v1-49-22]]

^<<v1-49-22,22>>^ “Joseph is the offshoot of a fruitful tree, a fruitful tree by a spring, whose branches extend over the wall.

[[v1-49-23]]

^<<v1-49-23,23>>^ But the archers kept harassing him and shot at him and kept harboring animosity against him.

[[v1-49-24]]

^<<v1-49-24,24>>^ And yet his bow remained in place, and his hands stayed strong and agile. This was from the hands of the powerful one of Jacob, from the shepherd, the stone of Israel.

[[v1-49-25]]

^<<v1-49-25,25>>^ He^&#42;1^ is from the God of your father, and he will help you, and he is with the Almighty, and he will bless you with the blessings of the heavens above, with the blessings of the deep below, with the blessings of the breasts and womb.

[NOTE]
====
. That is, Joseph.
====

[[v1-49-26]]

^<<v1-49-26,26>>^ The blessings of your father will be superior to the blessings of the eternal mountains, to the desirable things of the enduring hills. They will continue upon the head of Joseph, upon the crown of the head of the one singled out from his brothers.

[[v1-49-27]]

^<<v1-49-27,27>>^ “Benjamin will keep on tearing like a wolf. In the morning he will eat the prey, and in the evening he will divide spoil.”

[[v1-49-28]]

^<<v1-49-28,28>>^ All of these are the 12 tribes of Israel, and this is what their father said to them when he was blessing them. He gave each of them an appropriate blessing.

[[v1-49-29]]

^<<v1-49-29,29>>^ After that he gave these commands to them: “I am being gathered to my people.^&#42;1^ Bury me with my fathers in the cave that is in the field of Eʹphron the Hitʹtite,

[NOTE]
====
. This is a poetic expression for death.
====

[[v1-49-30]]

^<<v1-49-30,30>>^ the cave in the field of Mach·peʹlah in front of Mamʹre in the land of Caʹnaan, the field that Abraham purchased from Eʹphron the Hitʹtite as a property for a burial place.

[[v1-49-31]]

^<<v1-49-31,31>>^ There they buried Abraham and his wife Sarah. There they buried Isaac and his wife Re·bekʹah, and there I buried Leʹah.

[[v1-49-32]]

^<<v1-49-32,32>>^ The field and the cave that is in it were purchased from the sons of Heth.”

[[v1-49-33]]

^<<v1-49-33,33>>^ Thus Jacob finished giving these instructions to his sons. Then he drew his feet up onto the bed and breathed his last and was gathered to his people.^&#42;1^

[NOTE]
====
. This is a poetic expression for death.
====

'''

xref:001-genesis/001-genesis-048.adoc#v1-48-0[&#60; Capítulo Anterior] | <<v1-49-0,Topo>> | xref:001-genesis/001-genesis-050.adoc#v1-50-0[Próximo Capítulo &#62;]