include::./index.adoc[]

[[v1-21-0]]
=== Genesis, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-21-1]]

^<<v1-21-1,1>>^ Jehovah turned his attention to Sarah just as he had said, and Jehovah did for Sarah what he had promised.

[[v1-21-2]]

^<<v1-21-2,2>>^ So Sarah became pregnant and then bore a son to Abraham in his old age at the appointed time God had promised him.

[[v1-21-3]]

^<<v1-21-3,3>>^ Abraham named his newborn son, whom Sarah bore to him, Isaac.

[[v1-21-4]]

^<<v1-21-4,4>>^ And Abraham circumcised his son Isaac when he was eight days old, just as God had commanded him.

[[v1-21-5]]

^<<v1-21-5,5>>^ Abraham was 100 years old when his son Isaac was born to him.

[[v1-21-6]]

^<<v1-21-6,6>>^ Then Sarah said: “God has brought me laughter; everybody hearing of it will laugh with me.”^&#42;1^

[NOTE]
====
. Or possibly, “laugh at me.”
====

[[v1-21-7]]

^<<v1-21-7,7>>^ And she added: “Who would have said to Abraham, ‘Sarah will certainly nurse children’? Yet, I have given birth to a son for him in his old age.”

[[v1-21-8]]

^<<v1-21-8,8>>^ Now the child grew and was weaned, and Abraham prepared a big feast on the day that Isaac was weaned.

[[v1-21-9]]

^<<v1-21-9,9>>^ But Sarah kept noticing that the son of Haʹgar the Egyptian, whom she had borne to Abraham, was mocking Isaac.

[[v1-21-10]]

^<<v1-21-10,10>>^ So she said to Abraham: “Drive out this slave girl and her son, for the son of this slave girl is not going to be an heir along with my son, with Isaac!”

[[v1-21-11]]

^<<v1-21-11,11>>^ But what she said about his son was very displeasing to Abraham.

[[v1-21-12]]

^<<v1-21-12,12>>^ Then God said to Abraham: “Do not be displeased by what Sarah is saying to you about the boy and about your slave girl. Listen to her,^&#42;1^ for what will be called your offspring^&#42;2^ will be through Isaac.

[NOTE]
====
. Lit., “to her voice.”
. Lit., “seed.”
====

[[v1-21-13]]

^<<v1-21-13,13>>^ As for the son of the slave girl, I will also make a nation out of him, because he is your offspring.”^&#42;1^

[NOTE]
====
. Lit., “seed.”
====

[[v1-21-14]]

^<<v1-21-14,14>>^ So Abraham got up early in the morning and took bread and a skin bottle of water and gave it to Haʹgar. He set these on her shoulder and then sent her away along with the boy. So she departed and wandered about in the wilderness of Beʹer-sheʹba.

[[v1-21-15]]

^<<v1-21-15,15>>^ Finally the water in the skin bottle was used up, and she pushed the boy under one of the bushes.

[[v1-21-16]]

^<<v1-21-16,16>>^ Then she went on and sat down by herself, about the distance of a bowshot away, because she said: “I do not want to watch the boy die.” So she sat down at a distance and began to cry aloud and to weep.

[[v1-21-17]]

^<<v1-21-17,17>>^ At that God heard the voice of the boy, and God’s angel called to Haʹgar from the heavens and said to her: “What is the matter with you, Haʹgar? Do not be afraid, for God has heard the voice of the boy there where he is.

[[v1-21-18]]

^<<v1-21-18,18>>^ Get up, lift the boy and take hold of him with your hand, for I will make him a great nation.”

[[v1-21-19]]

^<<v1-21-19,19>>^ Then God opened her eyes and she saw a well of water, and she went and filled the skin bottle with water and gave the boy a drink.

[[v1-21-20]]

^<<v1-21-20,20>>^ And God was with the boy as he grew up. He lived in the wilderness and became an archer.

[[v1-21-21]]

^<<v1-21-21,21>>^ He took up dwelling in the wilderness of Paʹran, and his mother took a wife for him from the land of Egypt.

[[v1-21-22]]

^<<v1-21-22,22>>^ At that time A·bimʹe·lech together with Phiʹcol the chief of his army said to Abraham: “God is with you in everything you are doing.

[[v1-21-23]]

^<<v1-21-23,23>>^ So now swear to me here by God that you will not deal falsely with me and with my offspring and with my descendants, and that you will deal with me and with the land where you have been residing with the same loyal love that I have shown you.”

[[v1-21-24]]

^<<v1-21-24,24>>^ So Abraham said: “I swear to this.”

[[v1-21-25]]

^<<v1-21-25,25>>^ However, Abraham complained to A·bimʹe·lech about the well of water that the servants of A·bimʹe·lech had violently seized.

[[v1-21-26]]

^<<v1-21-26,26>>^ A·bimʹe·lech replied: “I do not know who did this; you did not tell me about it, and I heard nothing about it until today.”

[[v1-21-27]]

^<<v1-21-27,27>>^ At that Abraham took sheep and cattle and gave them to A·bimʹe·lech, and the two of them made a covenant.

[[v1-21-28]]

^<<v1-21-28,28>>^ When Abraham set seven female lambs apart from the flock by themselves,

[[v1-21-29]]

^<<v1-21-29,29>>^ A·bimʹe·lech said to Abraham: “Why have you set these seven female lambs here by themselves?”

[[v1-21-30]]

^<<v1-21-30,30>>^ Then he said: “You are to accept the seven female lambs from my hand as a witness that I dug this well.”

[[v1-21-31]]

^<<v1-21-31,31>>^ That is why he called that place Beʹer-sheʹba,^&#42;1^ because there both of them had taken an oath.

[NOTE]
====
. Possibly meaning “Well of the Oath” or “Well of Seven.”
====

[[v1-21-32]]

^<<v1-21-32,32>>^ So they made a covenant at Beʹer-sheʹba, after which A·bimʹe·lech got up together with Phiʹcol the chief of his army, and they returned to the land of the Phi·lisʹtines.

[[v1-21-33]]

^<<v1-21-33,33>>^ After that he planted a tamarisk tree at Beʹer-sheʹba, and there he called on the name of Jehovah, the everlasting God.

[[v1-21-34]]

^<<v1-21-34,34>>^ And Abraham stayed^&#42;1^ in the land of the Phi·lisʹtines for a long time.^&#42;2^

[NOTE]
====
. Or “resided as a foreigner.”
. Lit., “many days.”
====

'''

xref:001-genesis/001-genesis-020.adoc#v1-20-0[&#60; Capítulo Anterior] | <<v1-21-0,Topo>> | xref:001-genesis/001-genesis-022.adoc#v1-22-0[Próximo Capítulo &#62;]