include::./index.adoc[]

[[v1-25-0]]
=== Genesis, 25
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-25-1]]

^<<v1-25-1,1>>^ Now Abraham again took a wife, and her name was Ke·tuʹrah.

[[v1-25-2]]

^<<v1-25-2,2>>^ In time she bore him Zimʹran, Jokʹshan, Meʹdan, Midʹi·an, Ishʹbak, and Shuʹah.

[[v1-25-3]]

^<<v1-25-3,3>>^ Jokʹshan became father to Sheʹba and Deʹdan.
The sons of Deʹdan were As·shuʹrim, Le·tuʹshim, and Le·umʹmim.

[[v1-25-4]]

^<<v1-25-4,4>>^ The sons of Midʹi·an were Eʹphah, Eʹpher, Haʹnoch, A·biʹda, and El·daʹah.
All of these were the sons of Ke·tuʹrah.

[[v1-25-5]]

^<<v1-25-5,5>>^ Later on Abraham gave everything he had to Isaac,

[[v1-25-6]]

^<<v1-25-6,6>>^ but Abraham gave gifts to his sons by his concubines. Then while he was still alive, he sent them eastward, away from Isaac his son, to the land of the East.

[[v1-25-7]]

^<<v1-25-7,7>>^ The years of Abraham’s life were 175 years.

[[v1-25-8]]

^<<v1-25-8,8>>^ Then Abraham breathed his last and died at a good old age, old and satisfied, and was gathered to his people.^&#42;1^

[NOTE]
====
. This is a poetic expression for death.
====

[[v1-25-9]]

^<<v1-25-9,9>>^ His sons Isaac and Ishʹma·el buried him in the cave of Mach·peʹlah in the field of Eʹphron the son of Zoʹhar the Hitʹtite that is in front of Mamʹre,

[[v1-25-10]]

^<<v1-25-10,10>>^ the field that Abraham had purchased from the sons of Heth. There Abraham was buried, with his wife Sarah.

[[v1-25-11]]

^<<v1-25-11,11>>^ After Abraham’s death, God continued to bless his son Isaac, and Isaac was dwelling near Beʹer-laʹhai-roi.

[[v1-25-12]]

^<<v1-25-12,12>>^ This is the history of Ishʹma·el the son of Abraham whom Haʹgar the Egyptian, the servant of Sarah, bore to Abraham.

[[v1-25-13]]

^<<v1-25-13,13>>^ Now these are the names of the sons of Ishʹma·el, by their names according to their family origins: Ishʹma·el’s firstborn Ne·baʹioth, then Keʹdar, Adʹbe·el, Mibʹsam,

[[v1-25-14]]

^<<v1-25-14,14>>^ Mishʹma, Duʹmah, Masʹsa,

[[v1-25-15]]

^<<v1-25-15,15>>^ Haʹdad, Teʹma, Jeʹtur, Naʹphish, and Kedʹe·mah.

[[v1-25-16]]

^<<v1-25-16,16>>^ These are the sons of Ishʹma·el, and these are their names by their settlements and by their encampments,^&#42;1^ 12 chieftains according to their clans.

[NOTE]
====
. Or “walled camps.”
====

[[v1-25-17]]

^<<v1-25-17,17>>^ And Ishʹma·el lived for 137 years. Then he breathed his last and died and was gathered to his people.^&#42;1^

[NOTE]
====
. This is a poetic expression for death.
====

[[v1-25-18]]

^<<v1-25-18,18>>^ And they took up dwelling from Havʹi·lah near Shur, which is close to Egypt, as far as As·syrʹi·a. He settled near all his brothers.^&#42;1^

[NOTE]
====
. Or possibly, “He lived in hostility to all his brothers.”
====

[[v1-25-19]]

^<<v1-25-19,19>>^ And this is the history of Isaac the son of Abraham.
Abraham became father to Isaac.

[[v1-25-20]]

^<<v1-25-20,20>>^ Isaac was 40 years old when he married Re·bekʹah, the daughter of Be·thuʹel the A·ra·maeʹan of Padʹdan-aʹram, the sister of Laʹban the A·ra·maeʹan.

[[v1-25-21]]

^<<v1-25-21,21>>^ And Isaac kept pleading with Jehovah regarding his wife, because she was barren; so Jehovah responded to his plea, and his wife Re·bekʹah became pregnant.

[[v1-25-22]]

^<<v1-25-22,22>>^ And the sons within her began to struggle with each other, so that she said: “If this is the way it is, why should I go on living?” So she inquired of Jehovah.

[[v1-25-23]]

^<<v1-25-23,23>>^ And Jehovah said to her: “Two nations are in your womb, and two peoples will be separated from within you; and the one nation will be stronger than the other nation, and the older will serve the younger.”

[[v1-25-24]]

^<<v1-25-24,24>>^ When the time came for her to give birth, look! twins were in her womb.

[[v1-25-25]]

^<<v1-25-25,25>>^ Then the first came out red all over and was like a garment of hair, so they named him Eʹsau.^&#42;1^

[NOTE]
====
. Meaning “Hairy.”
====

[[v1-25-26]]

^<<v1-25-26,26>>^ After that his brother came out and his hand was holding onto the heel of Eʹsau, so he named him Jacob.^&#42;1^ Isaac was 60 years old when she gave birth to them.

[NOTE]
====
. Meaning “One Seizing the Heel; Supplanter.”
====

[[v1-25-27]]

^<<v1-25-27,27>>^ As the boys got bigger, Eʹsau became a skilled hunter, a man of the field, but Jacob was a blameless man, dwelling in tents.

[[v1-25-28]]

^<<v1-25-28,28>>^ And Isaac loved Eʹsau because it meant game in his mouth, whereas Re·bekʹah loved Jacob.

[[v1-25-29]]

^<<v1-25-29,29>>^ On one occasion Jacob was boiling some stew when Eʹsau returned from the field exhausted.

[[v1-25-30]]

^<<v1-25-30,30>>^ So Eʹsau said to Jacob: “Quick, please, give me some^&#42;1^ of the red stew that you have there,^&#42;2^ for I am exhausted!”^&#42;3^ That is why his name was Eʹdom.^&#42;4^

[NOTE]
====
. Or “give me a swallow.”
. Lit., “the red, this the red.”
. Or “famished.”
. Meaning “Red.”
====

[[v1-25-31]]

^<<v1-25-31,31>>^ To this Jacob said: “First sell me your right as firstborn!”

[[v1-25-32]]

^<<v1-25-32,32>>^ And Eʹsau continued: “Here I am about to die! What use is a birthright to me?”

[[v1-25-33]]

^<<v1-25-33,33>>^ And Jacob added: “Swear to me first!” So he swore to him and sold his right as firstborn to Jacob.

[[v1-25-34]]

^<<v1-25-34,34>>^ Then Jacob gave Eʹsau bread and lentil stew, and he ate and drank, and he got up and went away. Thus Eʹsau despised the birthright.

'''

xref:001-genesis/001-genesis-024.adoc#v1-24-0[&#60; Capítulo Anterior] | <<v1-25-0,Topo>> | xref:001-genesis/001-genesis-026.adoc#v1-26-0[Próximo Capítulo &#62;]