include::./index.adoc[]

[[v1-24-0]]
=== Genesis, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-24-1]]

^<<v1-24-1,1>>^ Abraham was now old, advanced in years, and Jehovah had blessed Abraham in everything.

[[v1-24-2]]

^<<v1-24-2,2>>^ Abraham said to his servant, the oldest one of his household, who was managing all he had: “Please put your hand under my thigh,

[[v1-24-3]]

^<<v1-24-3,3>>^ and I will make you swear by Jehovah, the God of the heavens and the God of the earth, that you will not take a wife for my son from the daughters of the Caʹnaan·ites, among whom I am dwelling.

[[v1-24-4]]

^<<v1-24-4,4>>^ You must go instead to my country and to my relatives and take a wife for my son, for Isaac.”

[[v1-24-5]]

^<<v1-24-5,5>>^ However, the servant said to him: “What if the woman is not willing to come with me to this land? Must I then return your son to the land from which you came?”

[[v1-24-6]]

^<<v1-24-6,6>>^ At this Abraham said to him: “See that you do not take my son there.

[[v1-24-7]]

^<<v1-24-7,7>>^ Jehovah the God of the heavens, who took me from my father’s house and from the land of my relatives and who spoke with me and swore to me: ‘To your offspring^&#42;1^ I am going to give this land,’ he will send his angel ahead of you, and you will certainly take a wife for my son from there.

[NOTE]
====
. Lit., “seed.”
====

[[v1-24-8]]

^<<v1-24-8,8>>^ But if the woman is unwilling to come with you, you will be free from this oath. But you must not take my son there.”

[[v1-24-9]]

^<<v1-24-9,9>>^ With that the servant put his hand under the thigh of Abraham his master and swore to him concerning this matter.

[[v1-24-10]]

^<<v1-24-10,10>>^ So the servant took ten of his master’s camels and departed, taking along all sorts of good things from his master. Then he went on his way to Mes·o·po·taʹmi·a, to the city of Naʹhor.

[[v1-24-11]]

^<<v1-24-11,11>>^ He had the camels kneel down at a well of water outside the city. It was about evening, the time when the women would go out to draw water.

[[v1-24-12]]

^<<v1-24-12,12>>^ Then he said: “Jehovah the God of my master Abraham, please grant me success this day, and show your loyal love to my master Abraham.

[[v1-24-13]]

^<<v1-24-13,13>>^ Here I am standing at a spring of water, and the daughters of the men of the city are coming out to draw water.

[[v1-24-14]]

^<<v1-24-14,14>>^ May it happen that the young woman to whom I say, ‘Please let down your water jar so that I may take a drink,’ and who replies, ‘Take a drink, and I will also water your camels,’ let this be the one you choose for your servant Isaac; and by this let me know that you have shown your loyal love to my master.”

[[v1-24-15]]

^<<v1-24-15,15>>^ Even before he finished speaking, Re·bekʹah, who was the daughter of Be·thuʹel the son of Milʹcah the wife of Naʹhor, Abraham’s brother, came out with her water jar on her shoulder.

[[v1-24-16]]

^<<v1-24-16,16>>^ Now the young woman was very beautiful, a virgin; no man had had sexual relations with her. She went down to the spring, filled her water jar, and then came back up.

[[v1-24-17]]

^<<v1-24-17,17>>^ At once the servant ran to meet her and said: “Please give me a little sip of water from your jar.”

[[v1-24-18]]

^<<v1-24-18,18>>^ In turn she said: “Drink, my lord.” With that she quickly lowered her jar upon her hand and gave him a drink.

[[v1-24-19]]

^<<v1-24-19,19>>^ When she finished giving him a drink, she said: “I will also draw water for your camels until they are done drinking.”

[[v1-24-20]]

^<<v1-24-20,20>>^ So she quickly emptied her jar into the drinking trough and ran again and again to the well to draw water, and she kept drawing water for all his camels.

[[v1-24-21]]

^<<v1-24-21,21>>^ The whole time the man silently stared at her in amazement, wondering whether Jehovah had made his trip successful or not.

[[v1-24-22]]

^<<v1-24-22,22>>^ When the camels had finished drinking, the man took out for her a gold nose ring weighing a half shekel^&#42;1^ and two bracelets of gold weighing ten shekels,^&#42;2^

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v1-24-23]]

^<<v1-24-23,23>>^ and he said: “Please tell me, whose daughter are you? Is there any room at your father’s house for us to spend the night?”

[[v1-24-24]]

^<<v1-24-24,24>>^ At that she said to him: “I am the daughter of Be·thuʹel the son of Milʹcah, whom she bore to Naʹhor.”

[[v1-24-25]]

^<<v1-24-25,25>>^ And she added: “We have both straw and much fodder and also a place to spend the night.”

[[v1-24-26]]

^<<v1-24-26,26>>^ Then the man bowed down and prostrated himself before Jehovah

[[v1-24-27]]

^<<v1-24-27,27>>^ and said: “May Jehovah be praised, the God of my master Abraham, for he has not abandoned his loyal love and his faithfulness toward my master. Jehovah has guided me to the house of the brothers of my master.”

[[v1-24-28]]

^<<v1-24-28,28>>^ And the young woman ran to tell her mother’s household about these things.

[[v1-24-29]]

^<<v1-24-29,29>>^ Now Re·bekʹah had a brother whose name was Laʹban. So Laʹban ran to the man who was outside at the spring.

[[v1-24-30]]

^<<v1-24-30,30>>^ When he saw the nose ring and the bracelets on the hands of his sister and heard the words of his sister Re·bekʹah, who was saying, “This is the way the man spoke to me,” he came to meet the man, who was still there standing by the camels at the spring.

[[v1-24-31]]

^<<v1-24-31,31>>^ At once he said: “Come, you who are blessed by Jehovah. Why do you keep standing out here? I have made the house ready and a place for the camels.”

[[v1-24-32]]

^<<v1-24-32,32>>^ With that the man came into the house, and he^&#42;1^ unharnessed the camels and gave straw and fodder to the camels and water to wash his feet and the feet of the men who were with him.

[NOTE]
====
. Probably referring to Laban.
====

[[v1-24-33]]

^<<v1-24-33,33>>^ However, when something to eat was set before him, he said: “I will not eat until I have told you what I have to say.” So Laʹban said: “Speak!”

[[v1-24-34]]

^<<v1-24-34,34>>^ Then he said: “I am Abraham’s servant.

[[v1-24-35]]

^<<v1-24-35,35>>^ And Jehovah has blessed my master very much, and he has made him very wealthy by giving him sheep and cattle, silver and gold, male and female servants, and camels and donkeys.

[[v1-24-36]]

^<<v1-24-36,36>>^ Further, Sarah the wife of my master bore a son to my master after she grew old, and he will give him everything he has.

[[v1-24-37]]

^<<v1-24-37,37>>^ So my master made me swear, saying: ‘You must not take a wife for my son from the daughters of the Caʹnaan·ites, in whose land I am dwelling.

[[v1-24-38]]

^<<v1-24-38,38>>^ No, but you will go to the house of my father and to my family, and you must take a wife for my son.’

[[v1-24-39]]

^<<v1-24-39,39>>^ But I said to my master: ‘What if the woman is unwilling to come with me?’

[[v1-24-40]]

^<<v1-24-40,40>>^ He said to me: ‘Jehovah, before whom I have walked, will send his angel with you and will certainly give success to your journey, and you must take a wife for my son from my family and from the house of my father.

[[v1-24-41]]

^<<v1-24-41,41>>^ You will be released from your oath to me if you go to my family and they will not give her to you. This will release you from your oath.’

[[v1-24-42]]

^<<v1-24-42,42>>^ “When I got to the spring today, I said: ‘Jehovah the God of my master Abraham, if you will make my journey successful,

[[v1-24-43]]

^<<v1-24-43,43>>^ here I am standing at a spring. What must take place is that when a young woman comes out to draw water, I will say, “Please, let me drink a little water from your jar,”

[[v1-24-44]]

^<<v1-24-44,44>>^ and she will say to me, “You take a drink, and I will also draw water for your camels.” Let that woman be the one whom Jehovah has chosen for the son of my master.’

[[v1-24-45]]

^<<v1-24-45,45>>^ “Before I was finished speaking in my heart, there was Re·bekʹah coming out with her jar on her shoulder, and she made her way down to the spring and began to draw water. Then I said to her: ‘Give me a drink, please.’

[[v1-24-46]]

^<<v1-24-46,46>>^ So she quickly lowered her jar from her shoulder and said: ‘Take a drink, and I will also water your camels.’ Then I took a drink, and she also watered the camels.

[[v1-24-47]]

^<<v1-24-47,47>>^ After that I asked her, ‘Whose daughter are you?’ to which she replied, ‘The daughter of Be·thuʹel the son of Naʹhor, whom Milʹcah bore to him.’ So I put the ring on her nose and the bracelets on her hands.

[[v1-24-48]]

^<<v1-24-48,48>>^ And I bowed down and prostrated myself before Jehovah and praised Jehovah the God of my master Abraham, who had led me on the right path to take the daughter of the brother of my master for his son.

[[v1-24-49]]

^<<v1-24-49,49>>^ And now tell me if you wish to show loyal love and faithfulness toward my master; but if not, tell me, so that I may proceed one way or the other.”^&#42;1^

[NOTE]
====
. Lit., “turn to the right hand or to the left.”
====

[[v1-24-50]]

^<<v1-24-50,50>>^ Then Laʹban and Be·thuʹel answered: “This is from Jehovah. We are not able to say yes or no to you.^&#42;1^

[NOTE]
====
. Or “We are unable to speak bad or good to you.”
====

[[v1-24-51]]

^<<v1-24-51,51>>^ Here is Re·bekʹah before you. Take her and go, and let her become a wife to the son of your master, just as Jehovah has spoken.”

[[v1-24-52]]

^<<v1-24-52,52>>^ When Abraham’s servant heard their words, he at once bowed down on the ground before Jehovah.

[[v1-24-53]]

^<<v1-24-53,53>>^ And the servant began to bring out articles of silver and of gold and garments and to give them to Re·bekʹah, and he gave valuable things to her brother and to her mother.

[[v1-24-54]]

^<<v1-24-54,54>>^ After that he and the men with him ate and drank, and they spent the night there.
When he got up in the morning, he said: “Send me off to my master.”

[[v1-24-55]]

^<<v1-24-55,55>>^ To this her brother and her mother said: “Let the young woman stay with us at least ten days. Then she can go.”

[[v1-24-56]]

^<<v1-24-56,56>>^ But he said to them: “Do not detain me, seeing that Jehovah has made my journey successful. Send me off, in order that I may go to my master.”

[[v1-24-57]]

^<<v1-24-57,57>>^ So they said: “Let us call the young woman and inquire of her.”

[[v1-24-58]]

^<<v1-24-58,58>>^ They called Re·bekʹah and said to her: “Will you go with this man?” She replied: “I am willing to go.”

[[v1-24-59]]

^<<v1-24-59,59>>^ So they sent off their sister Re·bekʹah and her nurse^&#42;1^ and Abraham’s servant and his men.

[NOTE]
====
. That is, her nurse who now served as an attendant.
====

[[v1-24-60]]

^<<v1-24-60,60>>^ And they blessed Re·bekʹah and said to her: “Our sister, may you become thousands times ten thousand,^&#42;1^ and let your offspring^&#42;2^ take possession of the gate^&#42;3^ of those who hate them.”

[NOTE]
====
. Or “become the mother of thousands of myriads.”
. Lit., “seed.”
. Or “the cities.”
====

[[v1-24-61]]

^<<v1-24-61,61>>^ Then Re·bekʹah and her female attendants rose, got on the camels, and followed the man. So the servant took Re·bekʹah and went on his way.

[[v1-24-62]]

^<<v1-24-62,62>>^ Now Isaac had come from the direction of Beʹer-laʹhai-roi, for he was dwelling in the land of the Negʹeb.

[[v1-24-63]]

^<<v1-24-63,63>>^ And Isaac was out walking in the field about nightfall to meditate. When he looked up, why, he saw that camels were coming!

[[v1-24-64]]

^<<v1-24-64,64>>^ When Re·bekʹah looked up, she caught sight of Isaac, and she quickly got down from the camel.

[[v1-24-65]]

^<<v1-24-65,65>>^ Then she asked the servant: “Who is that man there walking in the field to meet us?” And the servant said: “It is my master.” So she took her veil to cover herself.

[[v1-24-66]]

^<<v1-24-66,66>>^ And the servant told Isaac all the things he had done.

[[v1-24-67]]

^<<v1-24-67,67>>^ After that Isaac brought her into the tent of Sarah his mother. Thus he took Re·bekʹah as his wife; and he fell in love with her, and Isaac found comfort after the loss of his mother.

'''

xref:001-genesis/001-genesis-023.adoc#v1-23-0[&#60; Capítulo Anterior] | <<v1-24-0,Topo>> | xref:001-genesis/001-genesis-025.adoc#v1-25-0[Próximo Capítulo &#62;]