include::./index.adoc[]

[[v1-14-0]]
=== Genesis, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-14-1]]

^<<v1-14-1,1>>^ Now in the days of Amʹra·phel king of Shiʹnar, Arʹi·och king of El·laʹsar, Ched·or·la·oʹmer king of Eʹlam, and Tiʹdal king of Goiʹim,

[[v1-14-2]]

^<<v1-14-2,2>>^ these made war with Beʹra king of Sodʹom, Birʹsha king of Go·morʹrah, Shiʹnab king of Adʹmah, Shem·eʹber king of Ze·boiʹim, and the king of Beʹla, that is, Zoʹar.

[[v1-14-3]]

^<<v1-14-3,3>>^ All of these joined forces at the Valley^&#42;1^ of Sidʹdim, that is, the Salt Sea.^&#42;2^

[NOTE]
====
. Or “Low Plain.”
. That is, the Dead Sea.
====

[[v1-14-4]]

^<<v1-14-4,4>>^ They had served Ched·or·la·oʹmer for 12 years, but they rebelled in the 13th year.

[[v1-14-5]]

^<<v1-14-5,5>>^ So in the 14th year, Ched·or·la·oʹmer and the kings who were with him came and defeated the Rephʹa·im in Ashʹte·roth-kar·naʹim, the Zuʹzim in Ham, the Eʹmim in Shaʹveh-kir·i·a·thaʹim,

[[v1-14-6]]

^<<v1-14-6,6>>^ and the Horʹites in their mountain of Seʹir down to El-paʹran, which is at the wilderness.

[[v1-14-7]]

^<<v1-14-7,7>>^ Then they turned back and came to En-mishʹpat, that is, Kaʹdesh, and conquered the whole territory of the A·malʹek·ites and also the Amʹor·ites who were dwelling in Hazʹa·zon-taʹmar.

[[v1-14-8]]

^<<v1-14-8,8>>^ At this point, the king of Sodʹom went on the march, and also the king of Go·morʹrah, the king of Adʹmah, the king of Ze·boiʹim, and the king of Beʹla, that is, Zoʹar, and they drew up in battle formation against them in the Valley^&#42;1^ of Sidʹdim,

[NOTE]
====
. Or “Low Plain.”
====

[[v1-14-9]]

^<<v1-14-9,9>>^ against Ched·or·la·oʹmer king of Eʹlam, Tiʹdal king of Goiʹim, Amʹra·phel king of Shiʹnar, and Arʹi·och king of El·laʹsar—four kings against the five.

[[v1-14-10]]

^<<v1-14-10,10>>^ Now the Valley^&#42;1^ of Sidʹdim was full of bitumen pits, and the kings of Sodʹom and Go·morʹrah tried to escape and fell into them, and those who remained fled to the mountainous region.

[NOTE]
====
. Or “Low Plain.”
====

[[v1-14-11]]

^<<v1-14-11,11>>^ Then the victors took all the goods of Sodʹom and Go·morʹrah and all their food and went on their way.

[[v1-14-12]]

^<<v1-14-12,12>>^ They also took Lot, the son of Aʹbram’s brother who was dwelling in Sodʹom, as well as his goods, and they continued on their way.

[[v1-14-13]]

^<<v1-14-13,13>>^ After that a man who had escaped came and told Aʹbram the Hebrew. He was then dwelling^&#42;1^ among the big trees of Mamʹre the Amʹor·ite, the brother of Eshʹcol and Aʹner. These men were allies of Aʹbram.

[NOTE]
====
. Or “dwelling in tents.”
====

[[v1-14-14]]

^<<v1-14-14,14>>^ Thus Aʹbram heard that his relative^&#42;1^ had been taken captive. With that he mobilized his trained men, 318 servants born in his household, and went in pursuit up to Dan.

[NOTE]
====
. Lit., “brother.”
====

[[v1-14-15]]

^<<v1-14-15,15>>^ During the night, he divided his forces, and he and his servants attacked and defeated them. And he pursued them up to Hoʹbah, which is north of Damascus.

[[v1-14-16]]

^<<v1-14-16,16>>^ He recovered all the goods, and he also recovered Lot his relative, his goods, the women, and the other people.

[[v1-14-17]]

^<<v1-14-17,17>>^ After Aʹbram returned from defeating Ched·or·la·oʹmer and the kings who were with him, the king of Sodʹom went out to meet Aʹbram at the Valley^&#42;1^ of Shaʹveh, that is, the Valley of the King.

[NOTE]
====
. Or “Low Plain.”
====

[[v1-14-18]]

^<<v1-14-18,18>>^ And Mel·chizʹe·dek king of Saʹlem brought out bread and wine; he was priest of the Most High God.

[[v1-14-19]]

^<<v1-14-19,19>>^ Then he blessed him and said:
“Blessed be Aʹbram by the Most High God,
Maker of heaven and earth;

[[v1-14-20]]

^<<v1-14-20,20>>^ And praised be the Most High God,
Who has handed your oppressors over to you!”
And Aʹbram gave him a tenth of everything.

[[v1-14-21]]

^<<v1-14-21,21>>^ After that the king of Sodʹom said to Aʹbram: “Give me the people,^&#42;1^ but take the goods for yourself.”

[NOTE]
====
. Or “souls.”
====

[[v1-14-22]]

^<<v1-14-22,22>>^ But Aʹbram said to the king of Sodʹom: “I raise my hand in an oath to Jehovah the Most High God, Maker of heaven and earth,

[[v1-14-23]]

^<<v1-14-23,23>>^ that I will not take anything that is yours, from a thread to a sandal lace, so that you may not say, ‘I made Aʹbram rich.’

[[v1-14-24]]

^<<v1-14-24,24>>^ I will take nothing except what the young men have already eaten. As for the share of the men who went with me, Aʹner, Eshʹcol, and Mamʹre—let them take their share.”

'''

xref:001-genesis/001-genesis-013.adoc#v1-13-0[&#60; Capítulo Anterior] | <<v1-14-0,Topo>> | xref:001-genesis/001-genesis-015.adoc#v1-15-0[Próximo Capítulo &#62;]