include::./index.adoc[]

[[v1-31-0]]
=== Genesis, 31
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-31-1]]

^<<v1-31-1,1>>^ In time he heard what the sons of Laʹban were saying: “Jacob has taken everything that belonged to our father, and from what belonged to our father, he has amassed all this wealth.”

[[v1-31-2]]

^<<v1-31-2,2>>^ When Jacob would look at the face of Laʹban, he saw that his attitude toward him was not what it used to be.

[[v1-31-3]]

^<<v1-31-3,3>>^ Finally Jehovah said to Jacob: “Return to the land of your fathers and to your relatives, and I will continue with you.”

[[v1-31-4]]

^<<v1-31-4,4>>^ Then Jacob sent a message to Rachel and Leʹah to come out to the field to his flock,

[[v1-31-5]]

^<<v1-31-5,5>>^ and he said to them:
“I have seen that your father’s attitude toward me has changed, but the God of my father has been with me.

[[v1-31-6]]

^<<v1-31-6,6>>^ You yourselves certainly know that I have served your father with all my power.

[[v1-31-7]]

^<<v1-31-7,7>>^ And your father has tried to cheat me and has changed my wages ten times; but God has not allowed him to do me harm.

[[v1-31-8]]

^<<v1-31-8,8>>^ If on the one hand he would say, ‘The speckled ones will be your wages,’ then the whole flock produced speckled ones; but if on the other hand he would say, ‘The striped ones will be your wages,’ then the whole flock produced striped ones.

[[v1-31-9]]

^<<v1-31-9,9>>^ So God kept taking your father’s livestock away from him and giving it to me.

[[v1-31-10]]

^<<v1-31-10,10>>^ Once when the flock got into heat, I raised my eyes and saw in a dream that the he-goats mating with the flock were striped, speckled, and spotty.

[[v1-31-11]]

^<<v1-31-11,11>>^ Then the angel of the true God said to me in the dream, ‘Jacob!’ to which I said, ‘Here I am.’

[[v1-31-12]]

^<<v1-31-12,12>>^ And he continued, ‘Raise your eyes, please, and see that all the he-goats mating with the flock are striped, speckled, and spotty, for I have seen all that Laʹban is doing to you.

[[v1-31-13]]

^<<v1-31-13,13>>^ I am the true God of Bethʹel, where you anointed a pillar and where you made a vow to me. Now get up, go out of this land, and return to the land of your birth.’”

[[v1-31-14]]

^<<v1-31-14,14>>^ At this Rachel and Leʹah answered him: “Is there any share left for us to inherit in our father’s house?

[[v1-31-15]]

^<<v1-31-15,15>>^ Does he not consider us as foreigners, since he has sold us and has been using up the money given for us?

[[v1-31-16]]

^<<v1-31-16,16>>^ All the riches that God has taken away from our father are ours and our children’s. So, then, do everything that God has told you to do.”

[[v1-31-17]]

^<<v1-31-17,17>>^ Then Jacob got up and lifted his children and his wives on the camels,

[[v1-31-18]]

^<<v1-31-18,18>>^ and he began driving all his herd and all the goods that he had accumulated, the livestock in his possession that he had accumulated in Padʹdan-aʹram, to go to Isaac his father in the land of Caʹnaan.

[[v1-31-19]]

^<<v1-31-19,19>>^ Now Laʹban had gone to shear his sheep, and Rachel stole the teraphim statues^&#42;1^ that belonged to her father.

[NOTE]
====
. Or “household gods; idols.”
====

[[v1-31-20]]

^<<v1-31-20,20>>^ Moreover, Jacob outwitted Laʹban the A·ra·maeʹan, for he had not told him that he was running away.

[[v1-31-21]]

^<<v1-31-21,21>>^ And he ran away and crossed the River,^&#42;1^ he and all he had. Then he headed toward the mountainous region of Gilʹe·ad.

[NOTE]
====
. That is, the Euphrates.
====

[[v1-31-22]]

^<<v1-31-22,22>>^ On the third day, Laʹban was told that Jacob had run away.

[[v1-31-23]]

^<<v1-31-23,23>>^ So he took his brothers^&#42;1^ with him and pursued him for a journey of seven days and caught up with him in the mountainous region of Gilʹe·ad.

[NOTE]
====
. Or “relatives.”
====

[[v1-31-24]]

^<<v1-31-24,24>>^ Then God came to Laʹban the A·ra·maeʹan in a dream by night and said to him: “Be careful about what you say to Jacob, either good or bad.”^&#42;1^

[NOTE]
====
. Lit., “Watch yourself that you do not speak with Jacob from good to bad.”
====

[[v1-31-25]]

^<<v1-31-25,25>>^ So Laʹban approached Jacob, as Jacob had pitched his tent in the mountain and Laʹban had encamped with his brothers in the mountainous region of Gilʹe·ad.

[[v1-31-26]]

^<<v1-31-26,26>>^ Then Laʹban said to Jacob: “What have you done? Why have you resorted to outwitting me and carrying my daughters off like captives taken by the sword?

[[v1-31-27]]

^<<v1-31-27,27>>^ Why did you run away secretly and outwit me and not tell me? If you had told me, I could have sent you away with rejoicing and with songs, with tambourine and with harp.

[[v1-31-28]]

^<<v1-31-28,28>>^ But you did not give me a chance to kiss my grandchildren^&#42;1^ and my daughters. You have acted foolishly.

[NOTE]
====
. Lit., “sons.”
====

[[v1-31-29]]

^<<v1-31-29,29>>^ It is in my power to do harm to you, but the God of your father spoke to me last night, saying, ‘Be careful about what you say to Jacob, either good or bad.’

[[v1-31-30]]

^<<v1-31-30,30>>^ Now you have gone because you have been longing to return to the house of your father, but why have you stolen my gods?”

[[v1-31-31]]

^<<v1-31-31,31>>^ Jacob answered Laʹban: “It was because I was afraid, for I said to myself, ‘You might take your daughters away from me by force.’

[[v1-31-32]]

^<<v1-31-32,32>>^ Anyone with whom you find your gods will not live. Before our brothers, examine what I have, and take what is yours.” But Jacob did not know that Rachel had stolen them.

[[v1-31-33]]

^<<v1-31-33,33>>^ So Laʹban went into the tent of Jacob and into the tent of Leʹah and into the tent of the two slave girls, but did not find them. Then he came out of Leʹah’s tent and went into Rachel’s tent.

[[v1-31-34]]

^<<v1-31-34,34>>^ Meanwhile, Rachel had taken the teraphim statues and put them in the woman’s saddle basket of the camel, and she was sitting on them. So Laʹban searched through the whole tent but did not find them.

[[v1-31-35]]

^<<v1-31-35,35>>^ Then she said to her father: “Do not be angry, my lord, because I am not able to get up before you, for the customary thing with women is upon me.” So he searched on carefully but did not find the teraphim statues.

[[v1-31-36]]

^<<v1-31-36,36>>^ At that Jacob became angry and began to criticize Laʹban. Jacob then said to Laʹban: “What is my offense, and for what sin are you hotly pursuing me?

[[v1-31-37]]

^<<v1-31-37,37>>^ Now that you have searched through all my goods, what have you found that belongs to your house? Put it here in front of my brothers and your brothers, and let them decide between the two of us.

[[v1-31-38]]

^<<v1-31-38,38>>^ During these 20 years that I have been with you, your sheep and your goats never miscarried, and I never ate the rams of your flock.

[[v1-31-39]]

^<<v1-31-39,39>>^ I did not bring you any animal torn by wild beasts. I would stand the loss of it myself. Whether the animal was stolen by day or was stolen by night, you would demand compensation from me.

[[v1-31-40]]

^<<v1-31-40,40>>^ By day the heat consumed me, and the cold by night, and sleep would flee from my eyes.

[[v1-31-41]]

^<<v1-31-41,41>>^ This makes 20 years for me in your house. I have served you 14 years for your two daughters and 6 years for your flock, and you kept changing my wages ten times.

[[v1-31-42]]

^<<v1-31-42,42>>^ If the God of my father, the God of Abraham and the One whom Isaac fears,^&#42;1^ had not been on my side, you would now have sent me away empty-handed. God has seen my affliction and the toil of my hands, and that is why he reproved you last night.”

[NOTE]
====
. Lit., “the fear of Isaac.”
====

[[v1-31-43]]

^<<v1-31-43,43>>^ Then Laʹban answered Jacob: “The daughters are my daughters and the children my children and the flock my flock, and everything you are looking at is mine and my daughters’. What can I do today against these or against their children whom they have borne?

[[v1-31-44]]

^<<v1-31-44,44>>^ Now come, let us make a covenant, you and I, and it will serve as a witness between us.”

[[v1-31-45]]

^<<v1-31-45,45>>^ So Jacob took a stone and set it up as a pillar.

[[v1-31-46]]

^<<v1-31-46,46>>^ Then Jacob said to his brothers: “Pick up stones!” And they took stones and made a pile. After that they ate there on the pile of stones.

[[v1-31-47]]

^<<v1-31-47,47>>^ And Laʹban began calling it Jeʹgar-sa·ha·duʹtha,^&#42;1^ but Jacob called it Galʹe·ed.^&#42;2^

[NOTE]
====
. An Aramaic expression meaning “Witness Pile.”
. A Hebrew expression meaning “Witness Pile.”
====

[[v1-31-48]]

^<<v1-31-48,48>>^ Laʹban then said: “This pile of stones is a witness between me and you today.” That is why he named it Galʹe·ed,

[[v1-31-49]]

^<<v1-31-49,49>>^ and the Watchtower, for he said: “Let Jehovah keep watch between you and me when we are out of each other’s sight.

[[v1-31-50]]

^<<v1-31-50,50>>^ If you mistreat my daughters and if you start taking wives in addition to my daughters, though there is no man with us, remember that God will be a witness between you and me.”

[[v1-31-51]]

^<<v1-31-51,51>>^ Laʹban went on to say to Jacob: “Here is this pile of stones, and here is the pillar that I have erected between you and me.

[[v1-31-52]]

^<<v1-31-52,52>>^ This pile of stones is a witness, and the pillar is something that bears witness, that I will not pass beyond this pile of stones to bring harm to you and you will not pass beyond this pile of stones and this pillar to bring harm to me.

[[v1-31-53]]

^<<v1-31-53,53>>^ Let the God of Abraham and the God of Naʹhor, the God of their father, judge between us.” And Jacob swore by the One whom his father Isaac fears.^&#42;1^

[NOTE]
====
. Lit., “by the fear of his father Isaac.”
====

[[v1-31-54]]

^<<v1-31-54,54>>^ After that Jacob offered a sacrifice in the mountain and invited his brothers to eat bread. So they ate and spent the night in the mountain.

[[v1-31-55]]

^<<v1-31-55,55>>^ However, Laʹban got up early in the morning and kissed his grandchildren^&#42;1^ and his daughters and blessed them. Then Laʹban departed and returned home.

[NOTE]
====
. Lit., “sons.”
====

'''

xref:001-genesis/001-genesis-030.adoc#v1-30-0[&#60; Capítulo Anterior] | <<v1-31-0,Topo>> | xref:001-genesis/001-genesis-032.adoc#v1-32-0[Próximo Capítulo &#62;]