include::./index.adoc[]

[[v1-46-0]]
=== Genesis, 46
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-46-1]]

^<<v1-46-1,1>>^ So Israel took all that he had^&#42;1^ and departed. When he arrived at Beʹer-sheʹba, he offered sacrifices to the God of his father Isaac.

[NOTE]
====
. Or “all who were his.”
====

[[v1-46-2]]

^<<v1-46-2,2>>^ Then God spoke to Israel in a vision by night and said: “Jacob, Jacob!” to which he said: “Here I am!”

[[v1-46-3]]

^<<v1-46-3,3>>^ He said: “I am the true God, the God of your father. Do not be afraid to go down to Egypt, for there I will make you into a great nation.

[[v1-46-4]]

^<<v1-46-4,4>>^ I myself will go down with you to Egypt, and I myself will also bring you back from there, and Joseph will lay his hand on your eyes.”^&#42;1^

[NOTE]
====
. That is, to close them at Jacob’s death.
====

[[v1-46-5]]

^<<v1-46-5,5>>^ After that Jacob departed from Beʹer-sheʹba, and the sons of Israel transported Jacob their father and their children and their wives in the wagons that Pharʹaoh had sent to transport him.

[[v1-46-6]]

^<<v1-46-6,6>>^ They took along their herds and their goods, which they had accumulated in the land of Caʹnaan. And so they came into Egypt, Jacob and all his offspring with him.

[[v1-46-7]]

^<<v1-46-7,7>>^ He brought with him into Egypt his sons and his grandsons, his daughters and his granddaughters—all his offspring.

[[v1-46-8]]

^<<v1-46-8,8>>^ Now these are the names of Israel’s sons who came into Egypt, Jacob and his sons: Jacob’s firstborn was Reuʹben.

[[v1-46-9]]

^<<v1-46-9,9>>^ The sons of Reuʹben were Haʹnoch, Palʹlu, Hezʹron, and Carʹmi.

[[v1-46-10]]

^<<v1-46-10,10>>^ The sons of Simʹe·on were Jem·uʹel, Jaʹmin, Oʹhad, Jaʹchin, Zoʹhar, and Shaʹul the son of a Caʹnaan·ite woman.

[[v1-46-11]]

^<<v1-46-11,11>>^ The sons of Leʹvi were Gerʹshon, Koʹhath, and Me·rarʹi.

[[v1-46-12]]

^<<v1-46-12,12>>^ The sons of Judah were Er, Oʹnan, Sheʹlah, Peʹrez, and Zeʹrah. However, Er and Oʹnan died in the land of Caʹnaan.
The sons of Peʹrez came to be Hezʹron and Haʹmul.

[[v1-46-13]]

^<<v1-46-13,13>>^ The sons of Isʹsa·char were Toʹla, Puʹvah, Iob, and Shimʹron.

[[v1-46-14]]

^<<v1-46-14,14>>^ The sons of Zebʹu·lun were Seʹred, Eʹlon, and Jahʹle·el.

[[v1-46-15]]

^<<v1-46-15,15>>^ These are the sons of Leʹah, whom she bore to Jacob in Padʹdan-aʹram, together with his daughter Diʹnah. All his sons and his daughters^&#42;1^ numbered 33.

[NOTE]
====
. Or “All the souls of his sons and daughters.”
====

[[v1-46-16]]

^<<v1-46-16,16>>^ The sons of Gad were Ziphʹi·on, Hagʹgi, Shuʹni, Ezʹbon, Eʹri, Ar·oʹdi, and A·reʹli.

[[v1-46-17]]

^<<v1-46-17,17>>^ The sons of Ashʹer were Imʹnah, Ishʹvah, Ishʹvi, and Be·riʹah, and their sister was Seʹrah.
The sons of Be·riʹah were Heʹber and Malʹchi·el.

[[v1-46-18]]

^<<v1-46-18,18>>^ These are the sons of Zilʹpah, whom Laʹban gave to his daughter Leʹah. She bore these to Jacob: 16 persons^&#42;1^ in all.

[NOTE]
====
. Or “16 souls.”
====

[[v1-46-19]]

^<<v1-46-19,19>>^ The sons of Jacob’s wife Rachel were Joseph and Benjamin.

[[v1-46-20]]

^<<v1-46-20,20>>^ There were born to Joseph in the land of Egypt Ma·nasʹseh and Eʹphra·im, whom Asʹe·nath the daughter of Pot·iʹphe·ra the priest of On^&#42;1^ bore to him.

[NOTE]
====
. That is, Heliopolis.
====

[[v1-46-21]]

^<<v1-46-21,21>>^ The sons of Benjamin were Beʹla, Beʹcher, Ashʹbel, Geʹra, Naʹa·man, Eʹhi, Rosh, Mupʹpim, Hupʹpim, and Ard.

[[v1-46-22]]

^<<v1-46-22,22>>^ These are the sons of Rachel who were born to Jacob: 14 persons^&#42;1^ in all.

[NOTE]
====
. Or “14 souls.”
====

[[v1-46-23]]

^<<v1-46-23,23>>^ The son^&#42;1^ of Dan was Huʹshim.

[NOTE]
====
. Lit., “sons.”
====

[[v1-46-24]]

^<<v1-46-24,24>>^ The sons of Naphʹta·li were Jahʹze·el, Guʹni, Jeʹzer, and Shilʹlem.

[[v1-46-25]]

^<<v1-46-25,25>>^ These are the sons of Bilʹhah, whom Laʹban gave to his daughter Rachel. She bore these to Jacob: seven persons^&#42;1^ in all.

[NOTE]
====
. Or “seven souls.”
====

[[v1-46-26]]

^<<v1-46-26,26>>^ All those^&#42;1^ who descended from Jacob and went into Egypt with him, aside from the wives of Jacob’s sons, were 66.

[NOTE]
====
. Or “All the souls.”
====

[[v1-46-27]]

^<<v1-46-27,27>>^ Joseph’s sons who were born to him in Egypt were two.^&#42;1^ All the people^&#42;2^ of the house of Jacob who came into Egypt were 70.

[NOTE]
====
. Or “two souls.”
. Or “souls.”
====

[[v1-46-28]]

^<<v1-46-28,28>>^ Jacob sent Judah ahead to tell Joseph that he was on the way to Goʹshen. When they came into the land of Goʹshen,

[[v1-46-29]]

^<<v1-46-29,29>>^ Joseph had his chariot prepared and went up to meet Israel his father at Goʹshen. When he presented himself to him, he at once embraced him^&#42;1^ and wept for some time.^&#42;2^

[NOTE]
====
. Lit., “fell upon his neck.”
. Or “wept on his neck again and again.”
====

[[v1-46-30]]

^<<v1-46-30,30>>^ Then Israel said to Joseph: “Now I am ready to die; I have seen your face and know that you are still alive.”

[[v1-46-31]]

^<<v1-46-31,31>>^ Joseph then said to his brothers and to his father’s household: “Let me go up and report to Pharʹaoh and tell him, ‘My brothers and my father’s household who were in the land of Caʹnaan have come here to me.

[[v1-46-32]]

^<<v1-46-32,32>>^ The men are shepherds, and they raise livestock, and they have brought their flocks and their herds and all that they have.’

[[v1-46-33]]

^<<v1-46-33,33>>^ When Pharʹaoh calls you and asks, ‘What is your occupation?’

[[v1-46-34]]

^<<v1-46-34,34>>^ you must say, ‘Your servants have raised livestock from our youth until now, both we and our forefathers,’ so that you may dwell in the land of Goʹshen, for every herder of sheep is detestable to the Egyptians.”

'''

xref:001-genesis/001-genesis-045.adoc#v1-45-0[&#60; Capítulo Anterior] | <<v1-46-0,Topo>> | xref:001-genesis/001-genesis-047.adoc#v1-47-0[Próximo Capítulo &#62;]