include::./index.adoc[]

[[v1-22-0]]
=== Genesis, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-22-1]]

^<<v1-22-1,1>>^ Now after this the true God put Abraham to the test, and he said to him: “Abraham!” to which he replied: “Here I am!”

[[v1-22-2]]

^<<v1-22-2,2>>^ Then he said: “Take, please, your son, your only son whom you so love, Isaac, and travel to the land of Mo·riʹah and offer him up there as a burnt offering on one of the mountains that I will designate to you.”

[[v1-22-3]]

^<<v1-22-3,3>>^ So Abraham got up early in the morning and saddled his donkey and took two of his servants along with him and his son Isaac. He split the wood for the burnt offering, and then he rose and traveled to the place that the true God indicated to him.

[[v1-22-4]]

^<<v1-22-4,4>>^ On the third day, Abraham looked up and saw the place from a distance.

[[v1-22-5]]

^<<v1-22-5,5>>^ Abraham now said to his servants: “You stay here with the donkey, but the boy and I will go over there and worship and return to you.”

[[v1-22-6]]

^<<v1-22-6,6>>^ So Abraham took the wood for the burnt offering and put it on his son Isaac. Then he took in his hands the fire and the knife,^&#42;1^ and the two of them walked on together.

[NOTE]
====
. Or “slaughtering knife.”
====

[[v1-22-7]]

^<<v1-22-7,7>>^ Then Isaac said to his father Abraham: “My father!” He replied: “Yes, my son!” So he continued: “Here are the fire and the wood, but where is the sheep for the burnt offering?”

[[v1-22-8]]

^<<v1-22-8,8>>^ To this Abraham said: “God himself will provide the sheep for the burnt offering, my son.” And both of them walked on together.

[[v1-22-9]]

^<<v1-22-9,9>>^ Finally they reached the place that the true God had indicated to him, and Abraham built an altar there and arranged the wood on it. He bound his son Isaac hand and foot and put him on the altar on top of the wood.

[[v1-22-10]]

^<<v1-22-10,10>>^ Then Abraham reached out his hand and took the knife^&#42;1^ to kill his son.

[NOTE]
====
. Or “slaughtering knife.”
====

[[v1-22-11]]

^<<v1-22-11,11>>^ But Jehovah’s angel called to him from the heavens and said: “Abraham, Abraham!” to which he answered: “Here I am!”

[[v1-22-12]]

^<<v1-22-12,12>>^ Then he said: “Do not harm the boy, and do not do anything at all to him, for now I do know that you are God-fearing because you have not withheld your son, your only one, from me.”

[[v1-22-13]]

^<<v1-22-13,13>>^ At that Abraham looked up, and there just beyond him was a ram caught by its horns in a thicket. So Abraham went and took the ram and offered it up as a burnt offering in place of his son.

[[v1-22-14]]

^<<v1-22-14,14>>^ And Abraham named that place Je·hoʹvah-jiʹreh.^&#42;1^ This is why it is still said today: “In the mountain of Jehovah it will be provided.”

[NOTE]
====
. Meaning “Jehovah Will Provide; Jehovah Will See to It.”
====

[[v1-22-15]]

^<<v1-22-15,15>>^ And Jehovah’s angel called to Abraham a second time from the heavens,

[[v1-22-16]]

^<<v1-22-16,16>>^ saying: “‘By myself I swear,’ declares Jehovah, ‘that because you have done this and you have not withheld your son, your only one,

[[v1-22-17]]

^<<v1-22-17,17>>^ I will surely bless you and I will surely multiply your offspring^&#42;1^ like the stars of the heavens and like the grains of sand on the seashore, and your offspring^&#42;2^ will take possession of the gate^&#42;3^ of his enemies.

[NOTE]
====
. Lit., “seed.”
. Lit., “seed.”
. Or “the cities.”
====

[[v1-22-18]]

^<<v1-22-18,18>>^ And by means of your offspring^&#42;1^ all nations of the earth will obtain a blessing for themselves because you have listened to my voice.’”

[NOTE]
====
. Lit., “seed.”
====

[[v1-22-19]]

^<<v1-22-19,19>>^ After that Abraham returned to his servants, and they got up and went back together to Beʹer-sheʹba; and Abraham continued to dwell at Beʹer-sheʹba.

[[v1-22-20]]

^<<v1-22-20,20>>^ After this it was reported to Abraham: “Here Milʹcah has also borne sons to Naʹhor your brother:

[[v1-22-21]]

^<<v1-22-21,21>>^ Uz his firstborn, Buz his brother, Kem·uʹel the father of Aʹram,

[[v1-22-22]]

^<<v1-22-22,22>>^ Cheʹsed, Haʹzo, Pilʹdash, Jidʹlaph, and Be·thuʹel.”

[[v1-22-23]]

^<<v1-22-23,23>>^ Be·thuʹel became the father of Re·bekʹah. Milʹcah bore these eight to Naʹhor the brother of Abraham.

[[v1-22-24]]

^<<v1-22-24,24>>^ His concubine, whose name was Reuʹmah, also bore sons: Teʹbah, Gaʹham, Taʹhash, and Maʹa·cah.

'''

xref:001-genesis/001-genesis-021.adoc#v1-21-0[&#60; Capítulo Anterior] | <<v1-22-0,Topo>> | xref:001-genesis/001-genesis-023.adoc#v1-23-0[Próximo Capítulo &#62;]