include::./index.adoc[]

[[v1-35-0]]
=== Genesis, 35
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-35-1]]

^<<v1-35-1,1>>^ After that God said to Jacob: “Rise, go up to Bethʹel and dwell there, and make an altar there to the true God, who appeared to you when you were running away from Eʹsau your brother.”

[[v1-35-2]]

^<<v1-35-2,2>>^ Then Jacob said to his household and to all who were with him: “Get rid of the foreign gods that are in your midst, and cleanse yourselves and change your garments,

[[v1-35-3]]

^<<v1-35-3,3>>^ and let us rise and go up to Bethʹel. There I will make an altar to the true God, who answered me in the day of my distress and who has been with me wherever^&#42;1^ I have gone.”

[NOTE]
====
. Or “in the way.”
====

[[v1-35-4]]

^<<v1-35-4,4>>^ So they gave Jacob all the foreign gods they had and the earrings that were in their ears, and Jacob buried^&#42;1^ them under the big tree that was close to Sheʹchem.

[NOTE]
====
. Or “hid.”
====

[[v1-35-5]]

^<<v1-35-5,5>>^ When they traveled on, the terror of God struck the cities around them, so they did not chase after the sons of Jacob.

[[v1-35-6]]

^<<v1-35-6,6>>^ Jacob eventually came to Luz, that is, Bethʹel, in the land of Caʹnaan, he and all the people with him.

[[v1-35-7]]

^<<v1-35-7,7>>^ There he built an altar and called the place El-bethʹel,^&#42;1^ because there the true God had revealed himself to him when he had run away from his brother.

[NOTE]
====
. Meaning “God of Bethel.”
====

[[v1-35-8]]

^<<v1-35-8,8>>^ Later Debʹo·rah, Re·bekʹah’s nurse, died and was buried at the foot of Bethʹel under an oak. So he named it Alʹlon-bacʹuth.^&#42;1^

[NOTE]
====
. Meaning “Oak of Weeping.”
====

[[v1-35-9]]

^<<v1-35-9,9>>^ God appeared to Jacob once again while he was coming from Padʹdan-aʹram and blessed him.

[[v1-35-10]]

^<<v1-35-10,10>>^ God said to him: “Your name is Jacob. Your name will no longer be Jacob, but Israel will be your name.” And he began to call him Israel.

[[v1-35-11]]

^<<v1-35-11,11>>^ God further said to him: “I am God Almighty. Be fruitful and become many. Nations and a congregation of nations will come from you, and kings will descend from you.^&#42;1^

[NOTE]
====
. Lit., “come out of your loins.”
====

[[v1-35-12]]

^<<v1-35-12,12>>^ As for the land that I have given to Abraham and to Isaac, to you I will give it, and to your offspring^&#42;1^ after you I will give the land.”

[NOTE]
====
. Lit., “seed.”
====

[[v1-35-13]]

^<<v1-35-13,13>>^ Then God went up from him at the place where he had spoken with him.

[[v1-35-14]]

^<<v1-35-14,14>>^ So Jacob set up a pillar in the place where he had spoken with him, a pillar of stone, and he poured a drink offering on it and poured oil on it.

[[v1-35-15]]

^<<v1-35-15,15>>^ And Jacob continued to call the place where God had spoken with him Bethʹel.

[[v1-35-16]]

^<<v1-35-16,16>>^ Then they pulled away from Bethʹel. And while they were still some distance from Ephʹrath, Rachel began to give birth, and her labor was very difficult.

[[v1-35-17]]

^<<v1-35-17,17>>^ But while she was struggling to deliver the child, the midwife said to her: “Do not be afraid, for you will have this son also.”

[[v1-35-18]]

^<<v1-35-18,18>>^ Just as her life was slipping away^&#42;1^ (for she was dying), she named him Ben-oʹni,^&#42;2^ but his father called him Benjamin.^&#42;3^

[NOTE]
====
. Or “her soul was going out.”
. Meaning “Son of My Mourning.”
. Meaning “Son of the Right Hand.”
====

[[v1-35-19]]

^<<v1-35-19,19>>^ So Rachel died and was buried on the way to Ephʹrath, that is, Bethʹle·hem.

[[v1-35-20]]

^<<v1-35-20,20>>^ Jacob set up a pillar over her grave; it is the pillar of Rachel’s grave to this day.

[[v1-35-21]]

^<<v1-35-21,21>>^ After that Israel pulled away and pitched his tent a distance beyond the tower of Eʹder.

[[v1-35-22]]

^<<v1-35-22,22>>^ Once while Israel was dwelling in that land, Reuʹben went and lay down with Bilʹhah his father’s concubine, and Israel heard about it.
So there were 12 sons of Jacob.

[[v1-35-23]]

^<<v1-35-23,23>>^ The sons by Leʹah were Jacob’s firstborn Reuʹben, then Simʹe·on, Leʹvi, Judah, Isʹsa·char, and Zebʹu·lun.

[[v1-35-24]]

^<<v1-35-24,24>>^ The sons by Rachel were Joseph and Benjamin.

[[v1-35-25]]

^<<v1-35-25,25>>^ And the sons by Bilʹhah, Rachel’s servant, were Dan and Naphʹta·li.

[[v1-35-26]]

^<<v1-35-26,26>>^ And the sons by Zilʹpah, Leʹah’s servant, were Gad and Ashʹer. These are Jacob’s sons, who were born to him in Padʹdan-aʹram.

[[v1-35-27]]

^<<v1-35-27,27>>^ Jacob eventually came to where his father Isaac was at Mamʹre, to Kirʹi·ath-arʹba, that is, Hebʹron, where Abraham and also Isaac had resided as foreigners.

[[v1-35-28]]

^<<v1-35-28,28>>^ Isaac lived to be 180 years old.

[[v1-35-29]]

^<<v1-35-29,29>>^ Then Isaac breathed his last and died and was gathered to his people,^&#42;1^ after a long and satisfying life;^&#42;2^ and his sons Eʹsau and Jacob buried him.

[NOTE]
====
. This is a poetic expression for death.
. Lit., “old and full of days.”
====

'''

xref:001-genesis/001-genesis-034.adoc#v1-34-0[&#60; Capítulo Anterior] | <<v1-35-0,Topo>> | xref:001-genesis/001-genesis-036.adoc#v1-36-0[Próximo Capítulo &#62;]