include::./index.adoc[]

[[v1-7-0]]
=== Genesis, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-7-1]]

^<<v1-7-1,1>>^ After that Jehovah said to Noah: “Go into the ark, you and all your household, because you are the one I have found to be righteous before me among this generation.

[[v1-7-2]]

^<<v1-7-2,2>>^ You must take with you every kind of clean animal by sevens,^&#42;1^ the male and its mate; and of every animal that is not clean just two, the male and its mate;

[NOTE]
====
. Or possibly, “seven pairs of every clean animal.”
====

[[v1-7-3]]

^<<v1-7-3,3>>^ also of the flying creatures of the sky by sevens,^&#42;1^ male and female, to preserve their offspring alive over all the earth.

[NOTE]
====
. Or possibly, “seven pairs of the flying creatures of the sky.”
====

[[v1-7-4]]

^<<v1-7-4,4>>^ For in just seven days, I will make it rain on the earth for 40 days and 40 nights, and I will wipe from the surface of the ground every living thing that I have made.”

[[v1-7-5]]

^<<v1-7-5,5>>^ Then Noah did everything that Jehovah had commanded him.

[[v1-7-6]]

^<<v1-7-6,6>>^ Noah was 600 years old when the floodwaters came upon the earth.

[[v1-7-7]]

^<<v1-7-7,7>>^ So Noah, along with his sons, his wife, and his sons’ wives, went into the ark ahead of the floodwaters.

[[v1-7-8]]

^<<v1-7-8,8>>^ Of every clean animal and of every animal that is not clean and of the flying creatures and of everything that moves on the ground,

[[v1-7-9]]

^<<v1-7-9,9>>^ they went inside the ark to Noah by twos, male and female, just as God had commanded Noah.

[[v1-7-10]]

^<<v1-7-10,10>>^ And seven days later the floodwaters came upon the earth.

[[v1-7-11]]

^<<v1-7-11,11>>^ In the 600th year of Noah’s life, in the second month, on the 17th day of the month, on that day all the springs of the vast watery deep burst open and the floodgates of the heavens were opened.

[[v1-7-12]]

^<<v1-7-12,12>>^ And the rain poured down on the earth for 40 days and 40 nights.

[[v1-7-13]]

^<<v1-7-13,13>>^ On that very day, Noah went into the ark along with his sons, Shem, Ham, and Jaʹpheth, and his wife and the three wives of his sons.

[[v1-7-14]]

^<<v1-7-14,14>>^ They went in with every wild animal according to its kind, and every domestic animal according to its kind, and every creeping animal of the earth according to its kind, and every flying creature according to its kind, every bird, every winged creature.

[[v1-7-15]]

^<<v1-7-15,15>>^ They kept going to Noah inside the ark, two by two, of every sort of flesh that has the breath of life.^&#42;1^

[NOTE]
====
. Or “the spirit of life.”
====

[[v1-7-16]]

^<<v1-7-16,16>>^ So they went in, male and female of every sort of flesh, just as God had commanded him. After that Jehovah shut the door behind him.

[[v1-7-17]]

^<<v1-7-17,17>>^ The flooding continued^&#42;1^ for 40 days on the earth, and the waters kept increasing and began carrying the ark, and it was floating high above the earth.

[NOTE]
====
. Or “kept coming.”
====

[[v1-7-18]]

^<<v1-7-18,18>>^ The waters became overwhelming and kept increasing greatly upon the earth, but the ark floated on the surface of the waters.

[[v1-7-19]]

^<<v1-7-19,19>>^ The waters overwhelmed the earth so greatly that all the tall mountains under the whole heavens were covered.

[[v1-7-20]]

^<<v1-7-20,20>>^ The waters rose up to 15 cubits^&#42;1^ above the mountains.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
====

[[v1-7-21]]

^<<v1-7-21,21>>^ So all living creatures^&#42;1^ that were moving on the earth perished—the flying creatures, the domestic animals, the wild animals, the swarming creatures, and all mankind.

[NOTE]
====
. Lit., “all flesh.”
====

[[v1-7-22]]

^<<v1-7-22,22>>^ Everything on dry land that had the breath of life^&#42;1^ in its nostrils died.

[NOTE]
====
. Or “the breath of the spirit of life.”
====

[[v1-7-23]]

^<<v1-7-23,23>>^ So He wiped every living thing from the surface of the earth, including man, animals, creeping animals, and the flying creatures of the sky. They were all wiped off the earth; only Noah and those with him in the ark survived.

[[v1-7-24]]

^<<v1-7-24,24>>^ And the waters continued overwhelming the earth for 150 days.

'''

xref:001-genesis/001-genesis-006.adoc#v1-6-0[&#60; Capítulo Anterior] | <<v1-7-0,Topo>> | xref:001-genesis/001-genesis-008.adoc#v1-8-0[Próximo Capítulo &#62;]