include::./index.adoc[]

[[v1-1-0]]
=== Genesis, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-1-1]]

^<<v1-1-1,1>>^ In the beginning God created the heavens and the earth.

[[v1-1-2]]

^<<v1-1-2,2>>^ Now the earth was formless and desolate,^&#42;1^ and there was darkness upon the surface of the watery deep,^&#42;2^ and God’s active force^&#42;3^ was moving about over the surface of the waters.

[NOTE]
====
. Or “empty.”
. Or “the surging waters.”
. Or “God’s spirit.”
====

[[v1-1-3]]

^<<v1-1-3,3>>^ And God said: “Let there be light.” Then there was light.

[[v1-1-4]]

^<<v1-1-4,4>>^ After that God saw that the light was good, and God began to divide the light from the darkness.

[[v1-1-5]]

^<<v1-1-5,5>>^ God called the light Day, but the darkness he called Night. And there was evening and there was morning, a first day.

[[v1-1-6]]

^<<v1-1-6,6>>^ Then God said: “Let there be an expanse between the waters, and let there be a division between the waters and the waters.”

[[v1-1-7]]

^<<v1-1-7,7>>^ Then God went on to make the expanse and divided the waters beneath the expanse from the waters above the expanse. And it was so.

[[v1-1-8]]

^<<v1-1-8,8>>^ God called the expanse Heaven.^&#42;1^ And there was evening and there was morning, a second day.

[NOTE]
====
. Or “Sky.”
====

[[v1-1-9]]

^<<v1-1-9,9>>^ Then God said: “Let the waters under the heavens be collected together into one place, and let the dry land appear.” And it was so.

[[v1-1-10]]

^<<v1-1-10,10>>^ God called the dry land Earth, but the collecting of the waters, he called Seas. And God saw that it was good.

[[v1-1-11]]

^<<v1-1-11,11>>^ Then God said: “Let the earth cause grass to sprout, seed-bearing plants and fruit trees according to their kinds, yielding fruit along with seed on the earth.” And it was so.

[[v1-1-12]]

^<<v1-1-12,12>>^ And the earth began to produce grass, seed-bearing plants and trees yielding fruit along with seed, according to their kinds. Then God saw that it was good.

[[v1-1-13]]

^<<v1-1-13,13>>^ And there was evening and there was morning, a third day.

[[v1-1-14]]

^<<v1-1-14,14>>^ Then God said: “Let there be luminaries^&#42;1^ in the expanse of the heavens to make a division between the day and the night, and they will serve as signs for seasons and for days and years.

[NOTE]
====
. Or “lights.”
====

[[v1-1-15]]

^<<v1-1-15,15>>^ They will serve as luminaries in the expanse of the heavens to shine upon the earth.” And it was so.

[[v1-1-16]]

^<<v1-1-16,16>>^ And God went on to make the two great luminaries, the greater luminary for dominating the day and the lesser luminary for dominating the night, and also the stars.

[[v1-1-17]]

^<<v1-1-17,17>>^ Thus God put them in the expanse of the heavens to shine upon the earth

[[v1-1-18]]

^<<v1-1-18,18>>^ and to dominate by day and by night and to make a division between the light and the darkness. Then God saw that it was good.

[[v1-1-19]]

^<<v1-1-19,19>>^ And there was evening and there was morning, a fourth day.

[[v1-1-20]]

^<<v1-1-20,20>>^ Then God said: “Let the waters swarm with living creatures,^&#42;1^ and let flying creatures fly above the earth across the expanse of the heavens.”^&#42;2^

[NOTE]
====
. Or “souls.”
. Or “sky.”
====

[[v1-1-21]]

^<<v1-1-21,21>>^ And God created the great sea creatures^&#42;1^ and all living creatures^&#42;2^ that move and swarm in the waters according to their kinds and every winged flying creature according to its kind. And God saw that it was good.

[NOTE]
====
. Or “monsters.”
. Or “souls.”
====

[[v1-1-22]]

^<<v1-1-22,22>>^ With that God blessed them, saying: “Be fruitful and become many and fill the waters of the sea, and let the flying creatures become many in the earth.”

[[v1-1-23]]

^<<v1-1-23,23>>^ And there was evening and there was morning, a fifth day.

[[v1-1-24]]

^<<v1-1-24,24>>^ Then God said: “Let the earth bring forth living creatures^&#42;1^ according to their kinds, domestic animals and creeping animals^&#42;2^ and wild animals of the earth according to their kinds.” And it was so.

[NOTE]
====
. Or “souls.”
. Or “moving animals,” apparently including reptiles and forms of animal life different from the other categories.
====

[[v1-1-25]]

^<<v1-1-25,25>>^ And God went on to make the wild animals of the earth according to their kinds and the domestic animals according to their kinds and all the creeping animals of the ground according to their kinds. And God saw that it was good.

[[v1-1-26]]

^<<v1-1-26,26>>^ Then God said: “Let us make man in our image, according to our likeness, and let them have in subjection the fish of the sea and the flying creatures of the heavens and the domestic animals and all the earth and every creeping animal that is moving on the earth.”

[[v1-1-27]]

^<<v1-1-27,27>>^ And God went on to create the man in his image, in God’s image he created him; male and female he created them.

[[v1-1-28]]

^<<v1-1-28,28>>^ Further, God blessed them, and God said to them: “Be fruitful and become many, fill the earth and subdue it, and have in subjection the fish of the sea and the flying creatures of the heavens and every living creature that is moving on the earth.”

[[v1-1-29]]

^<<v1-1-29,29>>^ Then God said: “Here I have given to you every seed-bearing plant that is on the entire earth and every tree with seed-bearing fruit. Let them serve as food for you.

[[v1-1-30]]

^<<v1-1-30,30>>^ And to every wild animal of the earth and to every flying creature of the heavens and to everything moving on the earth in which there is life,^&#42;1^ I have given all green vegetation for food.” And it was so.

[NOTE]
====
. Or “life as a soul; a living soul.”
====

[[v1-1-31]]

^<<v1-1-31,31>>^ After that God saw everything he had made, and look! it was very good. And there was evening and there was morning, a sixth day.

'''

**&#60; Capítulo Anterior** | <<v1-1-0,Topo>> | xref:001-genesis/001-genesis-002.adoc#v1-2-0[Próximo Capítulo &#62;]