include::./index.adoc[]

[[v1-34-0]]
=== Genesis, 34
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-34-1]]

^<<v1-34-1,1>>^ Now Diʹnah, Jacob’s daughter by Leʹah, used to go out to spend time with^&#42;1^ the young women of the land.

[NOTE]
====
. Or “to see.”
====

[[v1-34-2]]

^<<v1-34-2,2>>^ When Sheʹchem, the son of Haʹmor the Hiʹvite, a chieftain of the land, saw her, he took her and lay down with her and violated her.

[[v1-34-3]]

^<<v1-34-3,3>>^ And he^&#42;1^ became very attached to Diʹnah, the daughter of Jacob, and he fell in love with the young woman and spoke persuasively to her.^&#42;2^

[NOTE]
====
. Or “his soul.”
. Lit., “spoke to the heart of the young woman.”
====

[[v1-34-4]]

^<<v1-34-4,4>>^ Finally Sheʹchem said to Haʹmor his father: “Get me this young woman to be my wife.”

[[v1-34-5]]

^<<v1-34-5,5>>^ When Jacob heard that he had defiled Diʹnah his daughter, his sons were with his herd in the field. So Jacob kept silent until they returned.

[[v1-34-6]]

^<<v1-34-6,6>>^ Later Haʹmor, Sheʹchem’s father, went out to speak with Jacob.

[[v1-34-7]]

^<<v1-34-7,7>>^ But the sons of Jacob heard about it and returned from the field right away. They were offended and very angry because he had disgraced Israel by lying down with Jacob’s daughter, something that should not be done.

[[v1-34-8]]

^<<v1-34-8,8>>^ Haʹmor spoke with them, saying: “My son Sheʹchem longs for^&#42;1^ your daughter. Please give her to him as his wife,

[NOTE]
====
. Or “The soul of my son Shechem is attached to.”
====

[[v1-34-9]]

^<<v1-34-9,9>>^ and form marriage alliances^&#42;1^ with us. Give us your daughters, and take our daughters for yourselves.

[NOTE]
====
. Or “and intermarry.”
====

[[v1-34-10]]

^<<v1-34-10,10>>^ You may dwell with us, and the land will become available for you. Dwell and carry on trade in it and settle in it.”

[[v1-34-11]]

^<<v1-34-11,11>>^ Then Sheʹchem said to her father and to her brothers: “Let me find favor in your eyes, and I will give you whatever you ask me.

[[v1-34-12]]

^<<v1-34-12,12>>^ You can demand from me a very high bride price and gift. I am willing to give whatever you may say to me. Just give me the young woman as a wife.”

[[v1-34-13]]

^<<v1-34-13,13>>^ And Jacob’s sons answered Sheʹchem and Haʹmor his father deceitfully because he had defiled Diʹnah their sister.

[[v1-34-14]]

^<<v1-34-14,14>>^ They said to them: “We cannot possibly do such a thing, to give our sister to a man who is not circumcised,^&#42;1^ for that is a disgrace to us.

[NOTE]
====
. Lit., “who has a foreskin.”
====

[[v1-34-15]]

^<<v1-34-15,15>>^ We can only consent on this condition: that you become like us and circumcise all your males.

[[v1-34-16]]

^<<v1-34-16,16>>^ Then we will give our daughters to you, and we will take your daughters for ourselves, and we will dwell with you and become one people.

[[v1-34-17]]

^<<v1-34-17,17>>^ But if you do not listen to us and get circumcised, then we will take our daughter and go.”

[[v1-34-18]]

^<<v1-34-18,18>>^ Their words pleased Haʹmor and Sheʹchem, Haʹmor’s son.

[[v1-34-19]]

^<<v1-34-19,19>>^ The young man did not delay in doing what they asked, because he found delight in Jacob’s daughter, and he was the most honorable of the whole house of his father.

[[v1-34-20]]

^<<v1-34-20,20>>^ So Haʹmor and his son Sheʹchem went to the city gate and spoke to the men of their city, saying:

[[v1-34-21]]

^<<v1-34-21,21>>^ “These men wish to be at peace with us. Let them dwell in the land and carry on trade in it, for the land is large enough to accommodate them. We can take their daughters as wives, and our daughters we can give to them.

[[v1-34-22]]

^<<v1-34-22,22>>^ Only on this one condition will the men consent to dwell with us in order to become one people: that every male among us be circumcised just the way they are circumcised.

[[v1-34-23]]

^<<v1-34-23,23>>^ Then, will not their possessions, their wealth, and all their livestock be ours? So let us give them our consent that they may dwell with us.”

[[v1-34-24]]

^<<v1-34-24,24>>^ All those going out by the gate of his city listened to Haʹmor and to his son Sheʹchem, and all the males got circumcised, all those going out of the city gate.

[[v1-34-25]]

^<<v1-34-25,25>>^ However, on the third day, when they were still in pain, two sons of Jacob, Simʹe·on and Leʹvi, Diʹnah’s brothers, each took his sword and went into the unsuspecting city and killed every male.

[[v1-34-26]]

^<<v1-34-26,26>>^ They killed Haʹmor and his son Sheʹchem with the sword and then took Diʹnah from Sheʹchem’s house and left.

[[v1-34-27]]

^<<v1-34-27,27>>^ Jacob’s other sons came upon the slain men and plundered the city because they had defiled their sister.

[[v1-34-28]]

^<<v1-34-28,28>>^ They took their flocks, their herds, their donkeys, and whatever was in the city and in the field.

[[v1-34-29]]

^<<v1-34-29,29>>^ They also took all their possessions, captured all their little children and their wives, and plundered everything in the houses.

[[v1-34-30]]

^<<v1-34-30,30>>^ At this Jacob said to Simʹe·on and to Leʹvi: “You have brought great trouble^&#42;1^ on me in making me a stench to the inhabitants of the land, to the Caʹnaan·ites and the Perʹiz·zites. I am few in number, and they will certainly gather together to attack me and I will be annihilated, I and my house.”

[NOTE]
====
. Or “brought ostracism.”
====

[[v1-34-31]]

^<<v1-34-31,31>>^ But they said: “Should anyone treat our sister like a prostitute?”

'''

xref:001-genesis/001-genesis-033.adoc#v1-33-0[&#60; Capítulo Anterior] | <<v1-34-0,Topo>> | xref:001-genesis/001-genesis-035.adoc#v1-35-0[Próximo Capítulo &#62;]