include::./index.adoc[]

[[v1-37-0]]
=== Genesis, 37
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-37-1]]

^<<v1-37-1,1>>^ Jacob continued to dwell in the land of Caʹnaan, where his father had lived as a foreigner.

[[v1-37-2]]

^<<v1-37-2,2>>^ This is the history of Jacob.
When Joseph was 17 years old, the young man was tending the flock with the sons of Bilʹhah and the sons of Zilʹpah, the wives of his father. And Joseph brought a bad report about them to their father.

[[v1-37-3]]

^<<v1-37-3,3>>^ Now Israel loved Joseph more than all his other sons because he was the son of his old age, and he had a special robe^&#42;1^ made for him.

[NOTE]
====
. Or “a beautiful long garment.”
====

[[v1-37-4]]

^<<v1-37-4,4>>^ When his brothers saw that their father loved him more than all his brothers, they began to hate him, and they could not speak peaceably to him.

[[v1-37-5]]

^<<v1-37-5,5>>^ Later Joseph had a dream and told it to his brothers, and they found further reason to hate him.

[[v1-37-6]]

^<<v1-37-6,6>>^ He said to them: “Please listen to this dream that I had.

[[v1-37-7]]

^<<v1-37-7,7>>^ There we were binding sheaves in the middle of the field when my sheaf got up and stood erect and your sheaves encircled and bowed down to my sheaf.”

[[v1-37-8]]

^<<v1-37-8,8>>^ His brothers said to him: “Are you really going to make yourself king over us and dominate us?” So they found another reason to hate him, because of his dreams and what he said.

[[v1-37-9]]

^<<v1-37-9,9>>^ After that he had still another dream, and he related it to his brothers: “I have had another dream. This time the sun and the moon and 11 stars were bowing down to me.”

[[v1-37-10]]

^<<v1-37-10,10>>^ Then he related it to his father as well as his brothers, and his father rebuked him and said to him: “What is the meaning of this dream of yours? Am I as well as your mother and your brothers really going to come and bow down to the earth to you?”

[[v1-37-11]]

^<<v1-37-11,11>>^ And his brothers grew jealous of him, but his father kept the saying in mind.

[[v1-37-12]]

^<<v1-37-12,12>>^ His brothers now went to pasture their father’s flock near Sheʹchem.

[[v1-37-13]]

^<<v1-37-13,13>>^ Israel later said to Joseph: “Your brothers are tending flocks near Sheʹchem, are they not? Come, and let me send you to them.” At this he said to him: “I am ready!”

[[v1-37-14]]

^<<v1-37-14,14>>^ So he said to him: “Go, please, and see whether your brothers are well. See how the flock is, and bring word back to me.” With that he sent him away from the valley^&#42;1^ of Hebʹron, and he went on toward Sheʹchem.

[NOTE]
====
. Or “low plain.”
====

[[v1-37-15]]

^<<v1-37-15,15>>^ Later a man found him as he was wandering in a field. The man asked him: “What are you looking for?”

[[v1-37-16]]

^<<v1-37-16,16>>^ To this he said: “I am looking for my brothers. Please tell me, where are they tending flocks?”

[[v1-37-17]]

^<<v1-37-17,17>>^ The man continued: “They have pulled away from here, for I heard them saying, ‘Let us go to Doʹthan.’” So Joseph went after his brothers and found them at Doʹthan.

[[v1-37-18]]

^<<v1-37-18,18>>^ Now they caught sight of him from a distance, and before he reached them, they began plotting against him to put him to death.

[[v1-37-19]]

^<<v1-37-19,19>>^ So they said to one another: “Look! Here comes that dreamer.

[[v1-37-20]]

^<<v1-37-20,20>>^ Come, now, let us kill him and pitch him into one of the waterpits, and we will say that a vicious wild animal devoured him. Then let us see what will become of his dreams.”

[[v1-37-21]]

^<<v1-37-21,21>>^ When Reuʹben heard this, he tried to rescue him from them. So he said: “Let us not take his life.”^&#42;1^

[NOTE]
====
. Or “strike his soul.”
====

[[v1-37-22]]

^<<v1-37-22,22>>^ Reuʹben said to them: “Do not shed blood. Throw him into this waterpit in the wilderness, but do not harm^&#42;1^ him.” His purpose was to rescue him from them in order to return him to his father.

[NOTE]
====
. Or “lay a hand on.”
====

[[v1-37-23]]

^<<v1-37-23,23>>^ So as soon as Joseph came to his brothers, they stripped Joseph of his robe, the special robe that he wore,

[[v1-37-24]]

^<<v1-37-24,24>>^ and they took him and threw him into the waterpit. At the time the pit was empty; there was no water in it.

[[v1-37-25]]

^<<v1-37-25,25>>^ Then they sat down to eat. When they looked up, there was a caravan of Ishʹma·el·ites coming from Gilʹe·ad. Their camels were carrying labdanum gum, balsam, and resinous bark, and they were on their way down to Egypt.

[[v1-37-26]]

^<<v1-37-26,26>>^ At this Judah said to his brothers: “What profit would there be if we killed our brother and covered over his blood?

[[v1-37-27]]

^<<v1-37-27,27>>^ Come, now, let us sell him to the Ishʹma·el·ites, and do not let our hand be upon him. After all, he is our brother, our flesh.” So they listened to their brother.

[[v1-37-28]]

^<<v1-37-28,28>>^ And when the Midʹi·an·ite merchants were passing by, they lifted Joseph up out of the waterpit and sold him to the Ishʹma·el·ites for 20 pieces of silver. These men took Joseph into Egypt.

[[v1-37-29]]

^<<v1-37-29,29>>^ Later when Reuʹben returned to the waterpit and saw that Joseph was not in the waterpit, he ripped his garments apart.

[[v1-37-30]]

^<<v1-37-30,30>>^ When he returned to his brothers, he exclaimed: “The child is gone! And I—what am I going to do?”

[[v1-37-31]]

^<<v1-37-31,31>>^ So they took Joseph’s robe and slaughtered a male goat and dipped the robe in the blood.

[[v1-37-32]]

^<<v1-37-32,32>>^ After that they sent the special robe to their father and said: “This is what we found. Please examine whether this is your son’s robe or not.”

[[v1-37-33]]

^<<v1-37-33,33>>^ Then he examined it and exclaimed: “It is my son’s robe! A vicious wild animal must have devoured him! Joseph is surely torn to pieces!”

[[v1-37-34]]

^<<v1-37-34,34>>^ With that Jacob ripped his garments apart and put sackcloth around his waist and mourned his son for many days.

[[v1-37-35]]

^<<v1-37-35,35>>^ And all his sons and all his daughters kept trying to comfort him, but he kept refusing to take comfort, saying: “I will go down into the Grave^&#42;1^ mourning my son!” And his father continued weeping for him.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v1-37-36]]

^<<v1-37-36,36>>^ Now the Midʹi·an·ites sold him in Egypt to Potʹi·phar, a court official of Pharʹaoh and the chief of the guard.

'''

xref:001-genesis/001-genesis-036.adoc#v1-36-0[&#60; Capítulo Anterior] | <<v1-37-0,Topo>> | xref:001-genesis/001-genesis-038.adoc#v1-38-0[Próximo Capítulo &#62;]