include::./index.adoc[]

[[v1-36-0]]
=== Genesis, 36
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-36-1]]

^<<v1-36-1,1>>^ This is the history of Eʹsau, that is, Eʹdom.

[[v1-36-2]]

^<<v1-36-2,2>>^ Eʹsau took his wives from the daughters of Caʹnaan: Aʹdah the daughter of Eʹlon the Hitʹtite; and O·hol·i·baʹmah the daughter of Aʹnah, the granddaughter of Zibʹe·on the Hiʹvite;

[[v1-36-3]]

^<<v1-36-3,3>>^ and Basʹe·math, Ishʹma·el’s daughter, the sister of Ne·baʹioth.

[[v1-36-4]]

^<<v1-36-4,4>>^ And Aʹdah bore Elʹi·phaz to Eʹsau, and Basʹe·math bore Reuʹel,

[[v1-36-5]]

^<<v1-36-5,5>>^ and O·hol·i·baʹmah bore Jeʹush, Jaʹlam, and Korʹah.
These are the sons of Eʹsau, who were born to him in the land of Caʹnaan.

[[v1-36-6]]

^<<v1-36-6,6>>^ After that Eʹsau took his wives, his sons, his daughters, all the members^&#42;1^ of his household, his herd and all his other beasts, and all the wealth he had accumulated in the land of Caʹnaan and he went to another land some distance away from Jacob his brother.

[NOTE]
====
. Or “souls.”
====

[[v1-36-7]]

^<<v1-36-7,7>>^ For their goods had become too many for them to dwell together, and the land where they were residing^&#42;1^ was not able to sustain them because of their herds.

[NOTE]
====
. Or “living as foreigners.”
====

[[v1-36-8]]

^<<v1-36-8,8>>^ So Eʹsau took up dwelling in the mountainous region of Seʹir. Eʹsau is Eʹdom.

[[v1-36-9]]

^<<v1-36-9,9>>^ And this is the history of Eʹsau the father of Eʹdom in the mountainous region of Seʹir.

[[v1-36-10]]

^<<v1-36-10,10>>^ These are the names of the sons of Eʹsau: Elʹi·phaz the son of Aʹdah, Eʹsau’s wife; Reuʹel the son of Basʹe·math, Eʹsau’s wife.

[[v1-36-11]]

^<<v1-36-11,11>>^ The sons of Elʹi·phaz were Teʹman, Oʹmar, Zeʹpho, Gaʹtam, and Keʹnaz.

[[v1-36-12]]

^<<v1-36-12,12>>^ Timʹna became the concubine of Elʹi·phaz, Eʹsau’s son. In time she bore to Elʹi·phaz, Amʹa·lek. These are the sons of Aʹdah, Eʹsau’s wife.

[[v1-36-13]]

^<<v1-36-13,13>>^ These are the sons of Reuʹel: Naʹhath, Zeʹrah, Shamʹmah, and Mizʹzah. These were the sons of Basʹe·math, Eʹsau’s wife.

[[v1-36-14]]

^<<v1-36-14,14>>^ These were the sons of O·hol·i·baʹmah the daughter of Aʹnah, the granddaughter of Zibʹe·on, Eʹsau’s wife, whom she bore to Eʹsau: Jeʹush, Jaʹlam, and Korʹah.

[[v1-36-15]]

^<<v1-36-15,15>>^ These are the sheikhs^&#42;1^ of the sons of Eʹsau: The sons of Elʹi·phaz, Eʹsau’s firstborn: Sheikh Teʹman, Sheikh Oʹmar, Sheikh Zeʹpho, Sheikh Keʹnaz,

[NOTE]
====
. A sheikh was a tribal chief.
====

[[v1-36-16]]

^<<v1-36-16,16>>^ Sheikh Korʹah, Sheikh Gaʹtam, and Sheikh Amʹa·lek. These are the sheikhs of Elʹi·phaz in the land of Eʹdom. These are the sons by Aʹdah.

[[v1-36-17]]

^<<v1-36-17,17>>^ These are the sons of Reuʹel, Eʹsau’s son: Sheikh Naʹhath, Sheikh Zeʹrah, Sheikh Shamʹmah, and Sheikh Mizʹzah. These are the sheikhs of Reuʹel in the land of Eʹdom. These are the sons by Basʹe·math, Eʹsau’s wife.

[[v1-36-18]]

^<<v1-36-18,18>>^ Finally these are the sons of O·hol·i·baʹmah, Eʹsau’s wife: Sheikh Jeʹush, Sheikh Jaʹlam, and Sheikh Korʹah. These are the sheikhs of O·hol·i·baʹmah the daughter of Aʹnah, Eʹsau’s wife.

[[v1-36-19]]

^<<v1-36-19,19>>^ These are the sons of Eʹsau, and these are their sheikhs. He is Eʹdom.

[[v1-36-20]]

^<<v1-36-20,20>>^ These are the sons of Seʹir the Horʹite, the inhabitants of the land: Loʹtan, Shoʹbal, Zibʹe·on, Aʹnah,

[[v1-36-21]]

^<<v1-36-21,21>>^ Diʹshon, Eʹzer, and Diʹshan. These are the sheikhs of the Horʹites, the sons of Seʹir, in the land of Eʹdom.

[[v1-36-22]]

^<<v1-36-22,22>>^ The sons of Loʹtan were Hoʹri and Heʹmam, and Loʹtan’s sister was Timʹna.

[[v1-36-23]]

^<<v1-36-23,23>>^ These are the sons of Shoʹbal: Alʹvan, Manʹa·hath, Eʹbal, Sheʹpho, and Oʹnam.

[[v1-36-24]]

^<<v1-36-24,24>>^ These are the sons of Zibʹe·on: Aʹiah and Aʹnah. This is the Aʹnah who found the hot springs in the wilderness while he was tending the donkeys for Zibʹe·on his father.

[[v1-36-25]]

^<<v1-36-25,25>>^ These are the children of Aʹnah: Diʹshon and O·hol·i·baʹmah the daughter of Aʹnah.

[[v1-36-26]]

^<<v1-36-26,26>>^ These are the sons of Diʹshon: Hemʹdan, Eshʹban, Ithʹran, and Cheʹran.

[[v1-36-27]]

^<<v1-36-27,27>>^ These are the sons of Eʹzer: Bilʹhan, Zaʹa·van, and Aʹkan.

[[v1-36-28]]

^<<v1-36-28,28>>^ These are the sons of Diʹshan: Uz and Aʹran.

[[v1-36-29]]

^<<v1-36-29,29>>^ These are the sheikhs of the Horʹites: Sheikh Loʹtan, Sheikh Shoʹbal, Sheikh Zibʹe·on, Sheikh Aʹnah,

[[v1-36-30]]

^<<v1-36-30,30>>^ Sheikh Diʹshon, Sheikh Eʹzer, and Sheikh Diʹshan. These are the sheikhs of the Horʹites according to their sheikhs in the land of Seʹir.

[[v1-36-31]]

^<<v1-36-31,31>>^ Now these are the kings who reigned in the land of Eʹdom before any king reigned over the Israelites.^&#42;1^

[NOTE]
====
. Lit., “the sons of Israel.”
====

[[v1-36-32]]

^<<v1-36-32,32>>^ Beʹla son of Beʹor reigned in Eʹdom, and the name of his city was Dinʹha·bah.

[[v1-36-33]]

^<<v1-36-33,33>>^ When Beʹla died, Joʹbab son of Zeʹrah from Bozʹrah began to reign in his place.

[[v1-36-34]]

^<<v1-36-34,34>>^ When Joʹbab died, Huʹsham from the land of the Teʹman·ites began to reign in his place.

[[v1-36-35]]

^<<v1-36-35,35>>^ When Huʹsham died, Haʹdad son of Beʹdad, who defeated the Midʹi·an·ites in the territory^&#42;1^ of Moʹab, began to reign in his place, and the name of his city was Aʹvith.

[NOTE]
====
. Lit., “field.”
====

[[v1-36-36]]

^<<v1-36-36,36>>^ When Haʹdad died, Samʹlah from Mas·reʹkah began to reign in his place.

[[v1-36-37]]

^<<v1-36-37,37>>^ When Samʹlah died, Shaʹul from Re·hoʹboth by the River began to reign in his place.

[[v1-36-38]]

^<<v1-36-38,38>>^ When Shaʹul died, Baʹal-haʹnan the son of Achʹbor began to reign in his place.

[[v1-36-39]]

^<<v1-36-39,39>>^ When Baʹal-haʹnan the son of Achʹbor died, Haʹdar began to reign in his place. The name of his city was Paʹu, and the name of his wife was Me·hetʹa·bel the daughter of Maʹtred the daughter of Meʹza·hab.

[[v1-36-40]]

^<<v1-36-40,40>>^ So these are the names of the sheikhs of Eʹsau according to their families, according to their places, by their names: Sheikh Timʹna, Sheikh Alʹvah, Sheikh Jeʹtheth,

[[v1-36-41]]

^<<v1-36-41,41>>^ Sheikh O·hol·i·baʹmah, Sheikh Eʹlah, Sheikh Piʹnon,

[[v1-36-42]]

^<<v1-36-42,42>>^ Sheikh Keʹnaz, Sheikh Teʹman, Sheikh Mibʹzar,

[[v1-36-43]]

^<<v1-36-43,43>>^ Sheikh Magʹdi·el, and Sheikh Iʹram. These are the sheikhs of Eʹdom according to their settlements in the land of their possession. This is Eʹsau the father of Eʹdom.

'''

xref:001-genesis/001-genesis-035.adoc#v1-35-0[&#60; Capítulo Anterior] | <<v1-36-0,Topo>> | xref:001-genesis/001-genesis-037.adoc#v1-37-0[Próximo Capítulo &#62;]