include::./index.adoc[]

[[v1-43-0]]
=== Genesis, 43
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-43-1]]

^<<v1-43-1,1>>^ Now the famine was severe in the land.

[[v1-43-2]]

^<<v1-43-2,2>>^ So when they had finished eating the grain they had brought from Egypt, their father said to them: “Return and buy a little food for us.”

[[v1-43-3]]

^<<v1-43-3,3>>^ Then Judah said to him: “The man clearly warned us, ‘You must not see my face again unless your brother is with you.’

[[v1-43-4]]

^<<v1-43-4,4>>^ If you send our brother with us, we will go down and buy food for you.

[[v1-43-5]]

^<<v1-43-5,5>>^ But if you do not send him, we will not go down, for the man said to us, ‘You must not see my face again unless your brother is with you.’”

[[v1-43-6]]

^<<v1-43-6,6>>^ And Israel asked: “Why did you have to bring this trouble on me by telling the man that you had another brother?”

[[v1-43-7]]

^<<v1-43-7,7>>^ They replied: “The man directly inquired concerning us and our relatives, saying, ‘Is your father still alive? Do you have another brother?’ and we told him these facts. How could we possibly know that he would say, ‘Bring your brother down’?”

[[v1-43-8]]

^<<v1-43-8,8>>^ Judah then urged Israel his father: “Send the boy with me, and let us go on our way so that we may live and not die—we and you and our children.

[[v1-43-9]]

^<<v1-43-9,9>>^ I will be a guarantee for his safety.^&#42;1^ You may hold me responsible. If I fail to return him to you and present him to you, I will have sinned against you for all time.

[NOTE]
====
. Or “be surety for him.”
====

[[v1-43-10]]

^<<v1-43-10,10>>^ But if we had not delayed, we could have been there and back twice by now.”

[[v1-43-11]]

^<<v1-43-11,11>>^ So Israel their father said to them: “If it must be so, then do this: Take the finest products of the land in your bags^&#42;1^ and carry them down to the man as a gift: a little balsam, a little honey, labdanum, resinous bark, pistachio nuts, and almonds.

[NOTE]
====
. Or “receptacles.”
====

[[v1-43-12]]

^<<v1-43-12,12>>^ Take double the money with you; and also take back the money that was returned in the mouth of your bags. Maybe it was a mistake.

[[v1-43-13]]

^<<v1-43-13,13>>^ Take your brother and go, return to the man.

[[v1-43-14]]

^<<v1-43-14,14>>^ May God Almighty grant you pity from the man, so that he may release to you your other brother and Benjamin. But as for me, if I must be bereaved, I will be bereaved!”

[[v1-43-15]]

^<<v1-43-15,15>>^ So the men took this gift, and they took double the money in their hand and Benjamin. Then they rose and went on their way down to Egypt and again stood before Joseph.

[[v1-43-16]]

^<<v1-43-16,16>>^ When Joseph saw Benjamin with them, he at once said to the man who was over his house: “Take the men to the house and slaughter animals and prepare the meal, for the men are to eat with me at noon.”

[[v1-43-17]]

^<<v1-43-17,17>>^ Immediately the man did just as Joseph had said, and he took them to Joseph’s house.

[[v1-43-18]]

^<<v1-43-18,18>>^ But the men became afraid when they were taken to Joseph’s house, and they began to say: “It is because of the money that was returned in our bags the last time that we are being brought here. Now they will attack us and make us slaves and take our donkeys!”

[[v1-43-19]]

^<<v1-43-19,19>>^ So they approached the man who was over Joseph’s house and spoke to him at the entrance of the house.

[[v1-43-20]]

^<<v1-43-20,20>>^ They said: “Pardon us, my lord! We did come down the first time to buy food.

[[v1-43-21]]

^<<v1-43-21,21>>^ But when we arrived at our lodging place and began opening our bags, why, here was the money of each one in the mouth of his bag, our money in full weight. So we would like to return it personally.

[[v1-43-22]]

^<<v1-43-22,22>>^ And we have brought more money to buy food. We do not know who placed our money in our bags.”

[[v1-43-23]]

^<<v1-43-23,23>>^ Then he said: “It is all right. Do not be afraid. Your God and the God of your father put treasure in your bags. Your money came first to me.” After that he brought out Simʹe·on to them.

[[v1-43-24]]

^<<v1-43-24,24>>^ Then the man brought them into Joseph’s house and gave them water for washing their feet, and he gave fodder for their donkeys.

[[v1-43-25]]

^<<v1-43-25,25>>^ And they prepared the gift for Joseph’s coming at noon, for they had heard that they were going to eat a meal there.

[[v1-43-26]]

^<<v1-43-26,26>>^ When Joseph went into the house, they brought their gift to him into the house and prostrated themselves to him to the ground.

[[v1-43-27]]

^<<v1-43-27,27>>^ After this he inquired about their welfare and said: “How is your aged father of whom you have spoken? Is he still alive?”

[[v1-43-28]]

^<<v1-43-28,28>>^ To this they said: “Your servant our father is well. He is still alive.” Then they bowed down and prostrated themselves.

[[v1-43-29]]

^<<v1-43-29,29>>^ When he looked up and saw Benjamin his brother, the son of his mother, he said: “Is this your brother, the youngest one of whom you have spoken to me?” He added: “May God show you his favor, my son.”

[[v1-43-30]]

^<<v1-43-30,30>>^ Joseph then hurried out, because he was overcome with emotion for his brother, and he looked for a place to weep. So he went into a private room and gave way to tears there.

[[v1-43-31]]

^<<v1-43-31,31>>^ After that he washed his face and went out, now in control of himself, and he said: “Serve the meal.”

[[v1-43-32]]

^<<v1-43-32,32>>^ They served him by himself and them by themselves, and the Egyptians with him ate by themselves, for the Egyptians could not eat a meal with the Hebrews, because that is a detestable thing to the Egyptians.

[[v1-43-33]]

^<<v1-43-33,33>>^ The brothers^&#42;1^ were seated before him, the firstborn according to his right as firstborn and the youngest according to his youth, and they kept looking at one another in amazement.

[NOTE]
====
. Lit., “They.”
====

[[v1-43-34]]

^<<v1-43-34,34>>^ He kept sending portions of food from his table to theirs, but he increased Benjamin’s portion five times the size of the portions of all the others. So they continued banqueting and drinking with him to the full.

'''

xref:001-genesis/001-genesis-042.adoc#v1-42-0[&#60; Capítulo Anterior] | <<v1-43-0,Topo>> | xref:001-genesis/001-genesis-044.adoc#v1-44-0[Próximo Capítulo &#62;]