include::./index.adoc[]

[[v1-30-0]]
=== Genesis, 30
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-30-1]]

^<<v1-30-1,1>>^ When Rachel saw that she had borne no children to Jacob, she became jealous of her sister and began to say to Jacob: “Give me children or else I will die.”

[[v1-30-2]]

^<<v1-30-2,2>>^ At this Jacob’s anger flared up against Rachel, and he said: “Am I in the place of God, who has prevented you from having children?”^&#42;1^

[NOTE]
====
. Or “has withheld the fruit of the womb from you?”
====

[[v1-30-3]]

^<<v1-30-3,3>>^ So she said: “Here is my slave girl Bilʹhah. Have relations with her in order that she may bear children for me^&#42;1^ and that through her, I too may have children.”

[NOTE]
====
. Lit., “give birth upon my knees.”
====

[[v1-30-4]]

^<<v1-30-4,4>>^ With that she gave him her servant Bilʹhah as a wife, and Jacob had relations with her.

[[v1-30-5]]

^<<v1-30-5,5>>^ Bilʹhah became pregnant and in time bore Jacob a son.

[[v1-30-6]]

^<<v1-30-6,6>>^ Then Rachel said: “God has acted as my judge and has also listened to my voice, so that he gave me a son.” That is why she named him Dan.^&#42;1^

[NOTE]
====
. Meaning “Judge.”
====

[[v1-30-7]]

^<<v1-30-7,7>>^ Bilʹhah, Rachel’s servant, became pregnant once more and in time bore Jacob a second son.

[[v1-30-8]]

^<<v1-30-8,8>>^ Then Rachel said: “With strenuous wrestlings I have wrestled with my sister. I have also come off the winner!” So she named him Naphʹta·li.^&#42;1^

[NOTE]
====
. Meaning “My Wrestlings.”
====

[[v1-30-9]]

^<<v1-30-9,9>>^ When Leʹah saw that she had stopped having children, she took her servant Zilʹpah and gave her to Jacob as a wife.

[[v1-30-10]]

^<<v1-30-10,10>>^ And Leʹah’s servant Zilʹpah bore a son to Jacob.

[[v1-30-11]]

^<<v1-30-11,11>>^ Then Leʹah said: “With good fortune!” So she named him Gad.^&#42;1^

[NOTE]
====
. Meaning “Good Fortune.”
====

[[v1-30-12]]

^<<v1-30-12,12>>^ After that Zilʹpah, Leʹah’s servant, bore a second son to Jacob.

[[v1-30-13]]

^<<v1-30-13,13>>^ Then Leʹah said: “With my happiness! For the daughters will certainly pronounce me happy.” So she named him Ashʹer.^&#42;1^

[NOTE]
====
. Meaning “Happy; Happiness.”
====

[[v1-30-14]]

^<<v1-30-14,14>>^ Now Reuʹben was walking in the days of the wheat harvest, and he found mandrakes in the field. So he brought them to his mother Leʹah. Then Rachel said to Leʹah: “Give me, please, some of your son’s mandrakes.”

[[v1-30-15]]

^<<v1-30-15,15>>^ At this she said to her: “Is it a small matter that you took my husband? Would you now take my son’s mandrakes also?” So Rachel said: “Very well. He will lie down with you tonight in exchange for your son’s mandrakes.”

[[v1-30-16]]

^<<v1-30-16,16>>^ When Jacob was coming from the field in the evening, Leʹah went out to meet him and said: “It is with me you are going to have relations, because I have hired you outright with my son’s mandrakes.” So he lay down with her that night.

[[v1-30-17]]

^<<v1-30-17,17>>^ And God heard and answered Leʹah, and she became pregnant and in time bore to Jacob a fifth son.

[[v1-30-18]]

^<<v1-30-18,18>>^ Then Leʹah said: “God has given me my wages^&#42;1^ because I have given my servant to my husband.” So she named him Isʹsa·char.^&#42;2^

[NOTE]
====
. Or “a hireling’s wages.”
. Meaning “He Is Wages.”
====

[[v1-30-19]]

^<<v1-30-19,19>>^ And Leʹah became pregnant once more and in time bore a sixth son to Jacob.

[[v1-30-20]]

^<<v1-30-20,20>>^ Then Leʹah said: “God has endowed me, yes, me, with a good endowment. At last, my husband will tolerate me, for I have borne him six sons.” So she named him Zebʹu·lun.^&#42;1^

[NOTE]
====
. Meaning “Toleration.”
====

[[v1-30-21]]

^<<v1-30-21,21>>^ Afterward she bore a daughter and named her Diʹnah.

[[v1-30-22]]

^<<v1-30-22,22>>^ Finally God remembered Rachel, and God heard and answered her by enabling her to become pregnant.^&#42;1^

[NOTE]
====
. Lit., “and God listened to her and opened her womb.”
====

[[v1-30-23]]

^<<v1-30-23,23>>^ And she became pregnant and gave birth to a son. Then she said: “God has taken away my reproach!”

[[v1-30-24]]

^<<v1-30-24,24>>^ So she named him Joseph,^&#42;1^ saying: “Jehovah is adding another son to me.”

[NOTE]
====
. A shortened form of Josiphiah, which means “May Jah Add (Increase).”
====

[[v1-30-25]]

^<<v1-30-25,25>>^ After Rachel had given birth to Joseph, Jacob immediately said to Laʹban: “Send me away so that I may go to my place and to my land.

[[v1-30-26]]

^<<v1-30-26,26>>^ Give over my wives and my children, for whom I have served with you, that I may go, for you well know how I have served you.”

[[v1-30-27]]

^<<v1-30-27,27>>^ Then Laʹban said to him: “If I have found favor in your eyes,—I have understood by the omens^&#42;1^ that Jehovah is blessing me because of you.”

[NOTE]
====
. Or “from the evidence.”
====

[[v1-30-28]]

^<<v1-30-28,28>>^ And he added: “Stipulate your wages to me, and I will give them.”

[[v1-30-29]]

^<<v1-30-29,29>>^ So Jacob said to him: “You know how I have served you and how your herd has fared with me;

[[v1-30-30]]

^<<v1-30-30,30>>^ you had little before my coming, but your herd has increased and multiplied, and Jehovah has blessed you since I arrived. So when will I do something for my own house?”

[[v1-30-31]]

^<<v1-30-31,31>>^ Then he said: “What should I give you?” And Jacob said: “You will give me nothing whatsoever! If you will do this one thing for me, I will resume shepherding your flock and guarding it.

[[v1-30-32]]

^<<v1-30-32,32>>^ I will pass through your whole flock today. You set aside from there every sheep speckled and with color patches and every dark-brown sheep among the young rams and any color-patched and speckled one among the she-goats. From now on, these must become my wages.

[[v1-30-33]]

^<<v1-30-33,33>>^ And my righteousness^&#42;1^ must speak for me on a future day when you come to look over my wages; every one that is not speckled and color-patched among the she-goats and dark brown among the young rams will be considered stolen if it is with me.”

[NOTE]
====
. Or “honesty.”
====

[[v1-30-34]]

^<<v1-30-34,34>>^ To this Laʹban said: “That is fine! Let it be according to your word.”

[[v1-30-35]]

^<<v1-30-35,35>>^ Then on that day, he set aside the he-goats striped and color-patched and all the she-goats speckled and color-patched, every one in which there was any white and every one dark brown among the young rams, and gave them into the care of his sons.

[[v1-30-36]]

^<<v1-30-36,36>>^ After that he set a distance of three days’ journey between himself and Jacob, and Jacob was shepherding the flocks of Laʹban that remained over.

[[v1-30-37]]

^<<v1-30-37,37>>^ Jacob then took freshly cut staffs of the storax, almond, and plane trees, and he peeled white spots in them by exposing the white wood of the staffs.

[[v1-30-38]]

^<<v1-30-38,38>>^ Then he placed the staffs that he had peeled in front of the flock, in the gutters, in the drinking troughs, where the flocks would come to drink, that they might get into heat in front of them when they came to drink.

[[v1-30-39]]

^<<v1-30-39,39>>^ So the flocks would get into heat in front of the staffs, and the flocks would produce striped, speckled, and color-patched offspring.

[[v1-30-40]]

^<<v1-30-40,40>>^ Then Jacob separated the young rams and turned the flocks to face the striped ones and all the dark-brown ones among the flocks of Laʹban. Then he separated his own flocks and did not mix them with Laʹban’s flocks.

[[v1-30-41]]

^<<v1-30-41,41>>^ And whenever the robust animals would get into heat, Jacob would place the staffs in the gutters before the eyes of the flocks, that they might get into heat by the staffs.

[[v1-30-42]]

^<<v1-30-42,42>>^ But when the animals were weak, he would not place the staffs there. So the weak ones always came to be Laʹban’s, but the robust ones became Jacob’s.

[[v1-30-43]]

^<<v1-30-43,43>>^ And the man grew very prosperous, and he acquired great flocks and male and female servants and camels and donkeys.

'''

xref:001-genesis/001-genesis-029.adoc#v1-29-0[&#60; Capítulo Anterior] | <<v1-30-0,Topo>> | xref:001-genesis/001-genesis-031.adoc#v1-31-0[Próximo Capítulo &#62;]