include::./index.adoc[]

[[v1-38-0]]
=== Genesis, 38
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-38-1]]

^<<v1-38-1,1>>^ About that time Judah left his brothers and pitched his tent near an A·dulʹlam·ite man named Hiʹrah.

[[v1-38-2]]

^<<v1-38-2,2>>^ There Judah saw the daughter of a certain Caʹnaan·ite named Shuʹa. So he took her and had relations with her,

[[v1-38-3]]

^<<v1-38-3,3>>^ and she became pregnant. Later she bore a son, and he named him Er.

[[v1-38-4]]

^<<v1-38-4,4>>^ Again she became pregnant and bore a son and named him Oʹnan.

[[v1-38-5]]

^<<v1-38-5,5>>^ Yet again she bore a son and named him Sheʹlah. He^&#42;1^ was in Achʹzib when she bore him.

[NOTE]
====
. That is, Judah.
====

[[v1-38-6]]

^<<v1-38-6,6>>^ In time Judah took a wife for Er his firstborn, and her name was Taʹmar.

[[v1-38-7]]

^<<v1-38-7,7>>^ But Er, Judah’s firstborn, was displeasing to Jehovah; so Jehovah put him to death.

[[v1-38-8]]

^<<v1-38-8,8>>^ In view of that, Judah said to Oʹnan: “Have relations with your brother’s wife and perform brother-in-law marriage with her and raise up offspring for your brother.”

[[v1-38-9]]

^<<v1-38-9,9>>^ But Oʹnan knew that the offspring would not be considered his. So when he did have relations with his brother’s wife, he wasted his semen on the ground so as not to give offspring to his brother.

[[v1-38-10]]

^<<v1-38-10,10>>^ What he did was bad in the eyes of Jehovah, so he also put him to death.

[[v1-38-11]]

^<<v1-38-11,11>>^ Judah said to Taʹmar his daughter-in-law: “Dwell as a widow in the house of your father until my son Sheʹlah grows up,” for he said to himself: ‘He too may die like his brothers.’ So Taʹmar went and stayed in her own father’s house.

[[v1-38-12]]

^<<v1-38-12,12>>^ Some time passed, and Judah’s wife, the daughter of Shuʹa, died. Judah kept the mourning period, and then he went to his sheepshearers in Timʹnah with his companion Hiʹrah the A·dulʹlam·ite.

[[v1-38-13]]

^<<v1-38-13,13>>^ Taʹmar was told: “Here your father-in-law is going up to Timʹnah to shear his sheep.”

[[v1-38-14]]

^<<v1-38-14,14>>^ With that she removed her widow’s clothing and veiled herself and covered herself with a shawl and sat down at the entrance of E·naʹim, which is on the road to Timʹnah, for she saw that Sheʹlah had grown up and yet she had not been given to him as a wife.

[[v1-38-15]]

^<<v1-38-15,15>>^ When Judah caught sight of her, he at once took her for a prostitute, because she had covered her face.

[[v1-38-16]]

^<<v1-38-16,16>>^ So he turned aside to her by the road and said: “Allow me, please, to have relations with you,” for he did not know that she was his daughter-in-law. However, she said: “What will you give me that you may have relations with me?”

[[v1-38-17]]

^<<v1-38-17,17>>^ To this he said: “I will send a young goat from my herd.” But she said: “Will you give a security until you send it?”

[[v1-38-18]]

^<<v1-38-18,18>>^ He continued: “What security should I give you?” to which she said: “Your seal ring and your cord and your rod that is in your hand.” Then he gave them to her and had relations with her, and she became pregnant by him.

[[v1-38-19]]

^<<v1-38-19,19>>^ After that she got up and went away and removed her shawl and clothed herself with her widow’s clothing.

[[v1-38-20]]

^<<v1-38-20,20>>^ And Judah sent the young goat by the hand of his companion the A·dulʹlam·ite, to get back the security from the hand of the woman, but he never found her.

[[v1-38-21]]

^<<v1-38-21,21>>^ He inquired of the men of her place, saying: “Where is that temple prostitute in E·naʹim along the road?” But they said: “No temple prostitute has ever been in this place.”

[[v1-38-22]]

^<<v1-38-22,22>>^ Finally he returned to Judah and said: “I never found her, and besides, the men of the place said, ‘No temple prostitute has ever been in this place.’”

[[v1-38-23]]

^<<v1-38-23,23>>^ So Judah said: “Let her take them for herself, in order that we may not fall into contempt. At any rate, I have sent this young goat, but you never found her.”

[[v1-38-24]]

^<<v1-38-24,24>>^ However, about three months later, Judah was told: “Taʹmar your daughter-in-law has acted as a prostitute, and she is also pregnant by her prostitution.” At that Judah said: “Bring her out and let her be burned.”

[[v1-38-25]]

^<<v1-38-25,25>>^ As she was being brought out, she sent word to her father-in-law: “I am pregnant by the man to whom these belong.” Then she added: “Please examine to whom these belong, the seal ring and the cord and the rod.”

[[v1-38-26]]

^<<v1-38-26,26>>^ Then Judah examined them and said: “She is more righteous than I am, because I did not give her to Sheʹlah my son.” And he had no further sexual relations with her after that.

[[v1-38-27]]

^<<v1-38-27,27>>^ When the time came for her to give birth, there were twins in her womb.

[[v1-38-28]]

^<<v1-38-28,28>>^ As she was giving birth, one put out his hand, and the midwife immediately took a scarlet thread and tied it around his hand, saying: “This one came out first.”

[[v1-38-29]]

^<<v1-38-29,29>>^ But as soon as he drew back his hand, his brother came out, and she exclaimed: “What a breach you have made for yourself!” So he was named Peʹrez.^&#42;1^

[NOTE]
====
. Meaning “Rupture,” probably referring to a perineal rupture.
====

[[v1-38-30]]

^<<v1-38-30,30>>^ Afterward his brother came out, around whose hand the scarlet thread was tied, and he was named Zeʹrah.

'''

xref:001-genesis/001-genesis-037.adoc#v1-37-0[&#60; Capítulo Anterior] | <<v1-38-0,Topo>> | xref:001-genesis/001-genesis-039.adoc#v1-39-0[Próximo Capítulo &#62;]