include::./index.adoc[]

[[v1-50-0]]
=== Genesis, 50
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-50-1]]

^<<v1-50-1,1>>^ Joseph then threw himself on his father and wept over him and kissed him.

[[v1-50-2]]

^<<v1-50-2,2>>^ After that Joseph commanded his servants, the physicians, to embalm his father. So the physicians embalmed Israel,

[[v1-50-3]]

^<<v1-50-3,3>>^ and they took the full 40 days for him, for this is the full period for the embalming, and the Egyptians continued to shed tears for him 70 days.

[[v1-50-4]]

^<<v1-50-4,4>>^ When the days of mourning for him passed, Joseph spoke to Pharʹaoh’s court,^&#42;1^ saying: “If I have found favor in your eyes, give this message to Pharʹaoh:

[NOTE]
====
. Or “household.”
====

[[v1-50-5]]

^<<v1-50-5,5>>^ ‘My father made me swear, saying: “Look! I am dying. You are to bury me in my burial place, which I have excavated in the land of Caʹnaan.” Please, let me go up and bury my father, after which I will return.’”

[[v1-50-6]]

^<<v1-50-6,6>>^ Pharʹaoh replied: “Go and bury your father just as he made you swear.”

[[v1-50-7]]

^<<v1-50-7,7>>^ So Joseph went up to bury his father, and all of Pharʹaoh’s servants went with him, the elders of his court and all the elders of the land of Egypt

[[v1-50-8]]

^<<v1-50-8,8>>^ and all of Joseph’s household and his brothers and the household of his father. Only their little children and their flocks and their herds they left in the land of Goʹshen.

[[v1-50-9]]

^<<v1-50-9,9>>^ Chariots and horsemen also went up with him, and the camp was very numerous.

[[v1-50-10]]

^<<v1-50-10,10>>^ Then they came to the threshing floor of Aʹtad, which is in the region of the Jordan, and there they carried on a very great and bitter mourning, and he kept mourning for his father seven days.

[[v1-50-11]]

^<<v1-50-11,11>>^ The inhabitants of the land, the Caʹnaan·ites, saw them mourning at the threshing floor of Aʹtad, and they exclaimed: “This is a great mourning for the Egyptians!” That is why it was named Aʹbel-mizʹra·im,^&#42;1^ which is in the region of the Jordan.

[NOTE]
====
. Meaning “Mourning of the Egyptians.”
====

[[v1-50-12]]

^<<v1-50-12,12>>^ So his sons did for him exactly as he had instructed them.

[[v1-50-13]]

^<<v1-50-13,13>>^ His sons carried him into the land of Caʹnaan and buried him in the cave of the field of Mach·peʹlah, the field in front of Mamʹre that Abraham had purchased from Eʹphron the Hitʹtite as property for a burial place.

[[v1-50-14]]

^<<v1-50-14,14>>^ After he buried his father, Joseph returned to Egypt with his brothers and all those who had gone with him to bury his father.

[[v1-50-15]]

^<<v1-50-15,15>>^ When Joseph’s brothers saw that their father was dead, they said: “It may be that Joseph is harboring animosity against us and that he will repay us for all the evil that we did to him.”

[[v1-50-16]]

^<<v1-50-16,16>>^ So they sent a message to Joseph in these words: “Your father gave this command before his death:

[[v1-50-17]]

^<<v1-50-17,17>>^ ‘This is what you are to say to Joseph: “I beg you, please pardon the transgression of your brothers and the sin they committed in bringing such harm to you.”’ Now, please, pardon the transgression of the servants of your father’s God.” And Joseph wept when they spoke to him.

[[v1-50-18]]

^<<v1-50-18,18>>^ Then his brothers also came and fell down before him and said: “Here we are as slaves to you!”

[[v1-50-19]]

^<<v1-50-19,19>>^ Joseph said to them: “Do not be afraid. Am I in the place of God?

[[v1-50-20]]

^<<v1-50-20,20>>^ Although you meant to harm me, God intended it to turn out well and to preserve many people alive, as he is doing today.

[[v1-50-21]]

^<<v1-50-21,21>>^ So now do not be afraid. I will keep supplying you and your little children with food.” Thus he comforted them and spoke reassuringly to them.

[[v1-50-22]]

^<<v1-50-22,22>>^ And Joseph continued to dwell in Egypt, he and the household of his father, and Joseph lived for 110 years.

[[v1-50-23]]

^<<v1-50-23,23>>^ Joseph saw the third generation of Eʹphra·im’s sons, also the sons of Maʹchir, Ma·nasʹseh’s son. They were born upon Joseph’s knees.^&#42;1^

[NOTE]
====
. That is, treated as sons and given special favor.
====

[[v1-50-24]]

^<<v1-50-24,24>>^ At length Joseph said to his brothers: “I am dying, but God will without fail turn his attention to you, and he will certainly bring you up out of this land to the land about which he swore to Abraham, to Isaac, and to Jacob.”

[[v1-50-25]]

^<<v1-50-25,25>>^ So Joseph made the sons of Israel swear, saying: “God will without fail turn his attention to you. You must take my bones up out of here.”

[[v1-50-26]]

^<<v1-50-26,26>>^ And Joseph died at the age of 110, and they had him embalmed, and he was put in a coffin in Egypt.

'''

xref:001-genesis/001-genesis-049.adoc#v1-49-0[&#60; Capítulo Anterior] | <<v1-50-0,Topo>> | xref:002-exodus/002-exodus-001.adoc#v2-1-0[Próximo Capítulo &#62;]