include::./index.adoc[]

[[v1-23-0]]
=== Genesis, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-23-1]]

^<<v1-23-1,1>>^ And Sarah lived for 127 years; these were the years of Sarah’s life.

[[v1-23-2]]

^<<v1-23-2,2>>^ So Sarah died in Kirʹi·ath-arʹba, that is, Hebʹron, in the land of Caʹnaan, and Abraham began to mourn and to weep over Sarah.

[[v1-23-3]]

^<<v1-23-3,3>>^ Then Abraham got up from before his dead wife and he said to the sons of Heth:

[[v1-23-4]]

^<<v1-23-4,4>>^ “I am a foreigner and settler among you. Give me a property to serve as a burial place in your midst so that I may remove my dead for burial.”

[[v1-23-5]]

^<<v1-23-5,5>>^ At this the sons of Heth answered Abraham:

[[v1-23-6]]

^<<v1-23-6,6>>^ “Hear us, my lord. You are a chieftain of God^&#42;1^ among us. You may bury your dead in the choicest of our burial places. None of us will hold back his burial place from you to prevent you from burying your dead.”

[NOTE]
====
. Or possibly, “a great chieftain.”
====

[[v1-23-7]]

^<<v1-23-7,7>>^ So Abraham got up and bowed down to the people of the land, to the sons of Heth,

[[v1-23-8]]

^<<v1-23-8,8>>^ and said to them: “If you^&#42;1^ agree to let me remove my dead for burial, then listen to me and urge Eʹphron the son of Zoʹhar

[NOTE]
====
. Or “your souls.”
====

[[v1-23-9]]

^<<v1-23-9,9>>^ to sell me the cave of Mach·peʹlah, which belongs to him; it is at the edge of his field. Let him sell it to me in your presence for the full amount of silver so that I may have a property for a burial place.”

[[v1-23-10]]

^<<v1-23-10,10>>^ Now Eʹphron was sitting among the sons of Heth. So Eʹphron the Hitʹtite answered Abraham in the hearing of the sons of Heth, and before all who entered the gate of his city, saying:

[[v1-23-11]]

^<<v1-23-11,11>>^ “No, my lord! Listen to me. I give you both the field and the cave that is in it. In the presence of the sons of my people, I give it to you. Bury your dead.”

[[v1-23-12]]

^<<v1-23-12,12>>^ At that Abraham bowed down before the people of the land

[[v1-23-13]]

^<<v1-23-13,13>>^ and spoke to Eʹphron in the hearing of the people, saying: “Listen to me, if you will! I will give you the full amount of silver for the field. Take it from me, in order that I may bury my dead there.”

[[v1-23-14]]

^<<v1-23-14,14>>^ Then Eʹphron answered Abraham:

[[v1-23-15]]

^<<v1-23-15,15>>^ “My lord, listen to me. This land is worth 400 silver shekels,^&#42;1^ but what is that between me and you? So bury your dead.”

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v1-23-16]]

^<<v1-23-16,16>>^ Abraham listened to Eʹphron, and Abraham weighed out to Eʹphron the amount of silver that he had mentioned in the hearing of the sons of Heth, 400 silver shekels^&#42;1^ according to the weight accepted by the merchants.

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v1-23-17]]

^<<v1-23-17,17>>^ Thus the field of Eʹphron in Mach·peʹlah, which was in front of Mamʹre—the field and the cave in it and all the trees within the boundaries of the field—became confirmed as

[[v1-23-18]]

^<<v1-23-18,18>>^ Abraham’s purchased property in the presence of the sons of Heth, before all those entering the gate of his city.

[[v1-23-19]]

^<<v1-23-19,19>>^ After that Abraham buried his wife Sarah in the cave of the field of Mach·peʹlah in front of Mamʹre, that is, Hebʹron, in the land of Caʹnaan.

[[v1-23-20]]

^<<v1-23-20,20>>^ Thus the field and the cave that was in it were transferred by the sons of Heth to Abraham as property for a burial place.

'''

xref:001-genesis/001-genesis-022.adoc#v1-22-0[&#60; Capítulo Anterior] | <<v1-23-0,Topo>> | xref:001-genesis/001-genesis-024.adoc#v1-24-0[Próximo Capítulo &#62;]