include::./index.adoc[]

[[v1-20-0]]
=== Genesis, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v1-20-1]]

^<<v1-20-1,1>>^ Now Abraham moved his camp from there to the land of the Negʹeb and began dwelling between Kaʹdesh and Shur. While he was residing^&#42;1^ at Geʹrar,

[NOTE]
====
. Or “living as a foreigner.”
====

[[v1-20-2]]

^<<v1-20-2,2>>^ Abraham repeated concerning his wife Sarah: “She is my sister.” So A·bimʹe·lech king of Geʹrar sent for Sarah and took her.

[[v1-20-3]]

^<<v1-20-3,3>>^ Afterward, God came by night to A·bimʹe·lech in a dream and said to him: “Here you are as good as dead because of the woman whom you have taken, since she is married and belongs to another man.”

[[v1-20-4]]

^<<v1-20-4,4>>^ However, A·bimʹe·lech had not gone near her.^&#42;1^ So he said: “Jehovah, will you kill a nation that is really innocent?^&#42;2^

[NOTE]
====
. That is, he had not had sexual relations with her.
. Or “righteous.”
====

[[v1-20-5]]

^<<v1-20-5,5>>^ Did he not say to me, ‘She is my sister,’ and did she too not say, ‘He is my brother’? I did this with an honest heart and innocent hands.”

[[v1-20-6]]

^<<v1-20-6,6>>^ Then the true God said to him in the dream: “I know that you did this with an honest heart, so I held you back from sinning against me. That is why I did not allow you to touch her.

[[v1-20-7]]

^<<v1-20-7,7>>^ Now return the man’s wife, for he is a prophet, and he will make supplication for you and you will keep living. But if you are not returning her, know that you will surely die, you and all who are yours.”

[[v1-20-8]]

^<<v1-20-8,8>>^ A·bimʹe·lech got up early in the morning and called all his servants and told them all these things, and they became very frightened.

[[v1-20-9]]

^<<v1-20-9,9>>^ Then A·bimʹe·lech called Abraham and said to him: “What have you done to us? What sin have I committed against you that you would bring upon me and my kingdom such a great sin? What you have done to me was not right.”

[[v1-20-10]]

^<<v1-20-10,10>>^ And A·bimʹe·lech went on to say to Abraham: “What were your intentions when you did this thing?”

[[v1-20-11]]

^<<v1-20-11,11>>^ Abraham said: “It was because I said to myself, ‘Surely there is no fear of God in this place, and they will kill me because of my wife.’

[[v1-20-12]]

^<<v1-20-12,12>>^ And besides, she really is my sister, the daughter of my father but not the daughter of my mother, and she became my wife.

[[v1-20-13]]

^<<v1-20-13,13>>^ So when God caused me to wander from the house of my father, I said to her: ‘Let this be how you show loyal love to me: Everywhere we go, say of me, “He is my brother.”’”

[[v1-20-14]]

^<<v1-20-14,14>>^ A·bimʹe·lech then took sheep and cattle and male and female servants and gave them to Abraham, and he returned his wife Sarah to him.

[[v1-20-15]]

^<<v1-20-15,15>>^ A·bimʹe·lech also said: “Here my land is available to you. Dwell wherever you please.”

[[v1-20-16]]

^<<v1-20-16,16>>^ And to Sarah he said: “Here I give 1,000 pieces of silver to your brother. It is a sign of your innocence^&#42;1^ to all who are with you and before everybody, and you are cleared of reproach.”

[NOTE]
====
. Lit., “Look, it is for you a covering of the eyes.”
====

[[v1-20-17]]

^<<v1-20-17,17>>^ And Abraham began to make supplication to the true God, and God healed A·bimʹe·lech and his wife and his slave girls, and they began having children;

[[v1-20-18]]

^<<v1-20-18,18>>^ for Jehovah had made all the women of the house of A·bimʹe·lech barren^&#42;1^ because of Sarah, Abraham’s wife.

[NOTE]
====
. Or “had completely closed every womb of the house of Abimelech.”
====

'''

xref:001-genesis/001-genesis-019.adoc#v1-19-0[&#60; Capítulo Anterior] | <<v1-20-0,Topo>> | xref:001-genesis/001-genesis-021.adoc#v1-21-0[Próximo Capítulo &#62;]