include::./index.adoc[]

[[v41-1-0]]
=== According to Mark, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v41-1-1]]

^<<v41-1-1,1>>^ The beginning of the good news about Jesus Christ, the Son of God:

[[v41-1-2]]

^<<v41-1-2,2>>^ Just as it is written in Isaiah the prophet: “(Look! I am sending my messenger ahead of you,^&#42;1^ who will prepare your way.)

[NOTE]
====
. Lit., “before your face.”
====

[[v41-1-3]]

^<<v41-1-3,3>>^ A voice of one crying out in the wilderness: ‘Prepare the way of Jehovah!^&#42;1^ Make his roads straight.’”

[NOTE]
====
. See App. A5.
====

[[v41-1-4]]

^<<v41-1-4,4>>^ John the Baptizer was in the wilderness, preaching baptism in symbol of repentance for forgiveness of sins.

[[v41-1-5]]

^<<v41-1-5,5>>^ And all the territory of Ju·deʹa and all the inhabitants of Jerusalem were going out to him, and they were baptized^&#42;1^ by him in the Jordan River, openly confessing their sins.

[NOTE]
====
. Or “dipped; immersed.”
====

[[v41-1-6]]

^<<v41-1-6,6>>^ Now John wore clothing of camel’s hair and a leather belt around his waist, and he ate locusts and wild honey.

[[v41-1-7]]

^<<v41-1-7,7>>^ And he was preaching: “Someone stronger than I am is coming after me, the lace of whose sandals I am not worthy to stoop down and untie.

[[v41-1-8]]

^<<v41-1-8,8>>^ I baptized you with water, but he will baptize you with holy spirit.”

[[v41-1-9]]

^<<v41-1-9,9>>^ In the course of those days, Jesus came from Nazʹa·reth of Galʹi·lee and was baptized in the Jordan by John.

[[v41-1-10]]

^<<v41-1-10,10>>^ And immediately on coming up out of the water, he saw the heavens being parted and, like a dove, the spirit coming down upon him.

[[v41-1-11]]

^<<v41-1-11,11>>^ And a voice came out of the heavens: “You are my Son, the beloved; I have approved you.”

[[v41-1-12]]

^<<v41-1-12,12>>^ And immediately the spirit impelled him to go into the wilderness.

[[v41-1-13]]

^<<v41-1-13,13>>^ So he continued in the wilderness for 40 days, being tempted by Satan. He was with the wild beasts, but the angels were ministering to him.

[[v41-1-14]]

^<<v41-1-14,14>>^ Now after John was arrested, Jesus went into Galʹi·lee, preaching the good news of God

[[v41-1-15]]

^<<v41-1-15,15>>^ and saying: “The appointed time has been fulfilled, and the Kingdom of God has drawn near. Repent, and have faith in the good news.”

[[v41-1-16]]

^<<v41-1-16,16>>^ While walking alongside the Sea of Galʹi·lee, he saw Simon and Simon’s brother Andrew casting their nets into the sea, for they were fishermen.

[[v41-1-17]]

^<<v41-1-17,17>>^ So Jesus said to them: “Come after me, and I will make you fishers of men.”^&#42;1^

[NOTE]
====
. Or “people.”
====

[[v41-1-18]]

^<<v41-1-18,18>>^ And at once they abandoned their nets and followed him.

[[v41-1-19]]

^<<v41-1-19,19>>^ After going a little farther, he saw James the son of Zebʹe·dee and his brother John, while they were in their boat mending their nets,

[[v41-1-20]]

^<<v41-1-20,20>>^ and without delay he called them. So they left their father Zebʹe·dee in the boat with the hired men and went off after him.

[[v41-1-21]]

^<<v41-1-21,21>>^ And they went into Ca·perʹna·um.
As soon as the Sabbath began, he went into the synagogue and started to teach.

[[v41-1-22]]

^<<v41-1-22,22>>^ And they were astounded at his way of teaching, for he was teaching them as one having authority, and not as the scribes.

[[v41-1-23]]

^<<v41-1-23,23>>^ Just then there was a man in their synagogue who was under the power of an unclean spirit, and he shouted:

[[v41-1-24]]

^<<v41-1-24,24>>^ “What have we to do with you, Jesus the Naz·a·reneʹ? Did you come to destroy us? I know exactly who you are, the Holy One of God!”

[[v41-1-25]]

^<<v41-1-25,25>>^ But Jesus rebuked it, saying: “Be silent, and come out of him!”

[[v41-1-26]]

^<<v41-1-26,26>>^ And the unclean spirit, after throwing the man into a convulsion and yelling at the top of its voice, came out of him.

[[v41-1-27]]

^<<v41-1-27,27>>^ Well, the people were all so astonished that they began to discuss it among themselves, saying: “What is this? A new teaching! He authoritatively orders even the unclean spirits, and they obey him.”

[[v41-1-28]]

^<<v41-1-28,28>>^ So the report about him spread quickly in all directions throughout the entire region of Galʹi·lee.

[[v41-1-29]]

^<<v41-1-29,29>>^ At that they left the synagogue and went to the home of Simon and Andrew with James and John.

[[v41-1-30]]

^<<v41-1-30,30>>^ Now Simon’s mother-in-law was lying down sick with a fever, and they at once told him about her.

[[v41-1-31]]

^<<v41-1-31,31>>^ Going to her, he took her by the hand and raised her up. The fever left her, and she began ministering to them.

[[v41-1-32]]

^<<v41-1-32,32>>^ After evening had fallen, when the sun had set, the people began bringing to him all who were ill and demon possessed;

[[v41-1-33]]

^<<v41-1-33,33>>^ and the whole city was gathered right at the door.

[[v41-1-34]]

^<<v41-1-34,34>>^ So he cured many who were ill with various sicknesses, and he expelled many demons, but he would not let the demons speak, for they knew him to be Christ.^&#42;1^

[NOTE]
====
. Or possibly, “they knew who he was.”
====

[[v41-1-35]]

^<<v41-1-35,35>>^ Early in the morning, while it was still dark, he got up and went outside and left for an isolated place, and there he began praying.

[[v41-1-36]]

^<<v41-1-36,36>>^ However, Simon and those with him hunted him down

[[v41-1-37]]

^<<v41-1-37,37>>^ and found him, and they said to him: “Everyone is looking for you.”

[[v41-1-38]]

^<<v41-1-38,38>>^ But he said to them: “Let us go somewhere else, into the towns nearby, so that I may preach there also, for this is why I have come.”

[[v41-1-39]]

^<<v41-1-39,39>>^ And he went, preaching in their synagogues throughout the whole of Galʹi·lee and expelling the demons.

[[v41-1-40]]

^<<v41-1-40,40>>^ There also came to him a leper, pleading with him even on bended knee, saying to him: “If you just want to, you can make me clean.”

[[v41-1-41]]

^<<v41-1-41,41>>^ At that he was moved with pity, and he stretched out his hand and touched him, and said to him: “I want to! Be made clean.”

[[v41-1-42]]

^<<v41-1-42,42>>^ Immediately the leprosy vanished from him, and he became clean.

[[v41-1-43]]

^<<v41-1-43,43>>^ Then he gave him strict orders and at once sent him away,

[[v41-1-44]]

^<<v41-1-44,44>>^ saying to him: “See that you say nothing to anyone, but go show yourself to the priest and offer for your cleansing the things Moses directed, for a witness to them.”

[[v41-1-45]]

^<<v41-1-45,45>>^ But after going away, the man started to proclaim it a great deal and to spread the account widely, so that Jesus was no longer able to enter openly into a city, but he stayed outside in isolated places. Yet they kept coming to him from all sides.

'''

xref:040-matthew/040-matthew-028.adoc#v40-28-0[&#60; Capítulo Anterior] | <<v41-1-0,Topo>> | xref:041-mark/041-mark-002.adoc#v41-2-0[Próximo Capítulo &#62;]