include::./index.adoc[]

[[v41-9-0]]
=== According to Mark, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v41-9-1]]

^<<v41-9-1,1>>^ Furthermore, he said to them: “Truly I say to you that there are some of those standing here who will not taste death at all until first they see the Kingdom of God already having come in power.”

[[v41-9-2]]

^<<v41-9-2,2>>^ Six days later Jesus took Peter and James and John along and led them up into a lofty mountain by themselves. And he was transfigured before them;

[[v41-9-3]]

^<<v41-9-3,3>>^ his outer garments began to glisten, becoming far whiter than any clothes cleaner on earth could whiten them.

[[v41-9-4]]

^<<v41-9-4,4>>^ Also, E·liʹjah with Moses appeared to them, and they were conversing with Jesus.

[[v41-9-5]]

^<<v41-9-5,5>>^ Then Peter said to Jesus: “Rabbi, it is fine for us to be here. So let us erect three tents, one for you, one for Moses, and one for E·liʹjah.”

[[v41-9-6]]

^<<v41-9-6,6>>^ In fact, he did not know how to react, for they were quite fearful.

[[v41-9-7]]

^<<v41-9-7,7>>^ And a cloud formed, overshadowing them, and a voice came out of the cloud: “This is my Son, the beloved. Listen to him.”

[[v41-9-8]]

^<<v41-9-8,8>>^ Then suddenly they looked around and saw that no one was with them any longer except Jesus.

[[v41-9-9]]

^<<v41-9-9,9>>^ As they were coming down from the mountain, he strictly ordered them not to relate to anybody what they had seen until after the Son of man had risen from the dead.

[[v41-9-10]]

^<<v41-9-10,10>>^ They took the word to heart,^&#42;1^ but discussed among themselves what this rising from the dead meant.

[NOTE]
====
. Or possibly, “kept the matter to themselves.”
====

[[v41-9-11]]

^<<v41-9-11,11>>^ And they began to question him, saying: “Why do the scribes say that E·liʹjah must come first?”

[[v41-9-12]]

^<<v41-9-12,12>>^ He said to them: “E·liʹjah does come first and restore all things; but how is it that it is written about the Son of man that he must undergo many sufferings and be treated with contempt?

[[v41-9-13]]

^<<v41-9-13,13>>^ But I say to you that E·liʹjah, in fact, has come, and they did to him whatever they wanted, just as it is written about him.”

[[v41-9-14]]

^<<v41-9-14,14>>^ When they came to the other disciples, they noticed a large crowd around them, and there were scribes arguing with them.

[[v41-9-15]]

^<<v41-9-15,15>>^ But as soon as all the crowd caught sight of him, they were astonished, and they ran up to him to greet him.

[[v41-9-16]]

^<<v41-9-16,16>>^ So he asked them: “What are you arguing about with them?”

[[v41-9-17]]

^<<v41-9-17,17>>^ And one of the crowd answered him: “Teacher, I brought my son to you because he has a speechless spirit.

[[v41-9-18]]

^<<v41-9-18,18>>^ Wherever it seizes him, it throws him to the ground, and he foams at the mouth and grinds his teeth and loses his strength. I asked your disciples to expel it, but they were not able to do so.”

[[v41-9-19]]

^<<v41-9-19,19>>^ In response he said to them: “O faithless generation, how long must I continue with you? How long must I put up with you? Bring him to me.”

[[v41-9-20]]

^<<v41-9-20,20>>^ So they brought the boy to him, but at the sight of him, the spirit at once threw the child into convulsions. After falling on the ground, he kept rolling about, foaming at the mouth.

[[v41-9-21]]

^<<v41-9-21,21>>^ Then Jesus asked the father: “How long has this been happening to him?” He said: “From childhood on,

[[v41-9-22]]

^<<v41-9-22,22>>^ and often it would throw him into the fire and also into the water to destroy him. But if you can do anything, have pity on us and help us.”

[[v41-9-23]]

^<<v41-9-23,23>>^ Jesus said to him: “That expression, ‘If you can’! Why, all things are possible for the one who has faith.”

[[v41-9-24]]

^<<v41-9-24,24>>^ Immediately the child’s father cried out and said: “I have faith! Help me out where I need faith!”

[[v41-9-25]]

^<<v41-9-25,25>>^ Jesus, now noticing that a crowd was rushing toward them, rebuked the unclean spirit, saying to it: “You speechless and deaf spirit, I order you, get out of him and do not enter into him again!”

[[v41-9-26]]

^<<v41-9-26,26>>^ After crying out and going through many convulsions, it came out, and the child seemed to be dead, so that most of the people were saying: “He is dead!”

[[v41-9-27]]

^<<v41-9-27,27>>^ But Jesus took him by the hand and raised him up, and he stood up.

[[v41-9-28]]

^<<v41-9-28,28>>^ So after he entered into a house, his disciples asked him privately: “Why could we not expel it?”

[[v41-9-29]]

^<<v41-9-29,29>>^ He said to them: “This kind can come out only by prayer.”

[[v41-9-30]]

^<<v41-9-30,30>>^ They departed from there and went through Galʹi·lee, but he did not want anyone to get to know about it.

[[v41-9-31]]

^<<v41-9-31,31>>^ For he was teaching his disciples and telling them: “The Son of man is going to be betrayed into men’s hands, and they will kill him, but despite being killed, he will rise three days later.”

[[v41-9-32]]

^<<v41-9-32,32>>^ However, they did not understand his statement, and they were afraid to question him.

[[v41-9-33]]

^<<v41-9-33,33>>^ And they came into Ca·perʹna·um. Now when he was inside the house, he put the question to them: “What were you arguing about on the road?”

[[v41-9-34]]

^<<v41-9-34,34>>^ They kept silent, for on the road they had been arguing among themselves about who is greater.

[[v41-9-35]]

^<<v41-9-35,35>>^ So he sat down and called the Twelve and said to them: “If anyone wants to be first, he must be last of all and minister of all.”

[[v41-9-36]]

^<<v41-9-36,36>>^ Then he took a young child and stood him in their midst; and putting his arms around him, he said to them:

[[v41-9-37]]

^<<v41-9-37,37>>^ “Whoever receives one of such young children on the basis of my name receives me also; and whoever receives me receives not me only but also Him who sent me.”

[[v41-9-38]]

^<<v41-9-38,38>>^ John said to him: “Teacher, we saw someone expelling demons by using your name, and we tried to prevent him, because he was not following us.”

[[v41-9-39]]

^<<v41-9-39,39>>^ But Jesus said: “Do not try to prevent him, for there is no one who will do a powerful work on the basis of my name who will quickly be able to say anything bad about me.

[[v41-9-40]]

^<<v41-9-40,40>>^ For whoever is not against us is for us.

[[v41-9-41]]

^<<v41-9-41,41>>^ And whoever gives you a cup of water to drink because you belong to Christ, I tell you truly, he will by no means lose his reward.

[[v41-9-42]]

^<<v41-9-42,42>>^ But whoever stumbles one of these little ones who have faith, it would be better for him if a millstone that is turned by a donkey were put around his neck and he were pitched into the sea.

[[v41-9-43]]

^<<v41-9-43,43>>^ “If ever your hand makes you stumble, cut it off. It is better for you to enter into life maimed than to go off with two hands into Ge·henʹna,^&#42;1^ into the fire that cannot be put out.

[NOTE]
====
. See Glossary.
====

[[v41-9-44]]

^<<v41-9-44,44>>^ ^&#42;1^ ——

[NOTE]
====
. See App. A3.
====

[[v41-9-45]]

^<<v41-9-45,45>>^ And if your foot makes you stumble, cut it off. It is better for you to enter into life lame than to be thrown with two feet into Ge·henʹna.^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v41-9-46]]

^<<v41-9-46,46>>^ ^&#42;1^ ——

[NOTE]
====
. See App. A3.
====

[[v41-9-47]]

^<<v41-9-47,47>>^ And if your eye makes you stumble, throw it away. It is better for you to enter one-eyed into the Kingdom of God than to be thrown with two eyes into Ge·henʹna,^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v41-9-48]]

^<<v41-9-48,48>>^ where the maggot does not die and the fire is not put out.

[[v41-9-49]]

^<<v41-9-49,49>>^ “For everyone must be salted with fire.

[[v41-9-50]]

^<<v41-9-50,50>>^ Salt is fine, but if the salt ever loses its saltiness, with what will you season it? Have salt in yourselves, and keep peace with one another.”

'''

xref:041-mark/041-mark-008.adoc#v41-8-0[&#60; Capítulo Anterior] | <<v41-9-0,Topo>> | xref:041-mark/041-mark-010.adoc#v41-10-0[Próximo Capítulo &#62;]