include::./index.adoc[]

[[v41-11-0]]
=== According to Mark, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v41-11-1]]

^<<v41-11-1,1>>^ Now when they were getting near to Jerusalem, to Bethʹpha·ge and Bethʹa·ny at the Mount of Olives, he sent two of his disciples

[[v41-11-2]]

^<<v41-11-2,2>>^ and told them: “Go into the village that is within sight, and as soon as you enter it, you will find a colt tied on which no man has sat until now. Untie it and bring it here.

[[v41-11-3]]

^<<v41-11-3,3>>^ And if anyone says to you, ‘Why are you doing this?’ say, ‘The Lord needs it and will send it back here right away.’”

[[v41-11-4]]

^<<v41-11-4,4>>^ So they went away and found the colt tied at a door, outside on the side street, and they untied it.

[[v41-11-5]]

^<<v41-11-5,5>>^ But some of those standing there said to them: “What are you doing untying the colt?”

[[v41-11-6]]

^<<v41-11-6,6>>^ They told them just what Jesus had said, and they let them go.

[[v41-11-7]]

^<<v41-11-7,7>>^ And they brought the colt to Jesus, and they put their outer garments on it, and he sat on it.

[[v41-11-8]]

^<<v41-11-8,8>>^ Also, many spread their outer garments on the road, but others cut down foliage from the fields.

[[v41-11-9]]

^<<v41-11-9,9>>^ And those going in front and those coming behind kept shouting: “Save, we pray! Blessed is the one who comes in Jehovah’s^&#42;1^ name!

[NOTE]
====
. See App. A5.
====

[[v41-11-10]]

^<<v41-11-10,10>>^ Blessed is the coming Kingdom of our father David! Save, we pray, in the heights above!”

[[v41-11-11]]

^<<v41-11-11,11>>^ And he entered Jerusalem and went into the temple, and he looked around at everything, but since the hour was already late, he went out to Bethʹa·ny with the Twelve.

[[v41-11-12]]

^<<v41-11-12,12>>^ The next day when they were leaving Bethʹa·ny, he felt hungry.

[[v41-11-13]]

^<<v41-11-13,13>>^ From a distance he caught sight of a fig tree that had leaves, and he went to see whether he could find something on it. But on coming to it, he found nothing but leaves, for it was not the season for figs.

[[v41-11-14]]

^<<v41-11-14,14>>^ So he said to it: “Let no one eat fruit from you ever again.” And his disciples were listening.

[[v41-11-15]]

^<<v41-11-15,15>>^ They now came to Jerusalem. There he entered the temple and started to throw out those selling and buying in the temple, and he overturned the tables of the money changers and the benches of those selling doves,

[[v41-11-16]]

^<<v41-11-16,16>>^ and he would not let anyone carry a utensil through the temple.

[[v41-11-17]]

^<<v41-11-17,17>>^ He was teaching and saying to them: “Is it not written, ‘My house will be called a house of prayer for all the nations’? But you have made it a cave of robbers.”

[[v41-11-18]]

^<<v41-11-18,18>>^ And the chief priests and the scribes heard it, and they began to seek how to kill him; for they were in fear of him, because all the crowd was astounded at his teaching.

[[v41-11-19]]

^<<v41-11-19,19>>^ When it became late in the day, they went out of the city.

[[v41-11-20]]

^<<v41-11-20,20>>^ But when they were passing by early in the morning, they saw the fig tree already withered from its roots.

[[v41-11-21]]

^<<v41-11-21,21>>^ Peter, remembering it, said to him: “Rabbi, see! the fig tree that you cursed has withered.”

[[v41-11-22]]

^<<v41-11-22,22>>^ In reply Jesus said to them: “Have faith in God.

[[v41-11-23]]

^<<v41-11-23,23>>^ Truly I say to you that whoever tells this mountain, ‘Be lifted up and thrown into the sea,’ and does not doubt in his heart but has faith that what he says is going to happen, he will have it happen.

[[v41-11-24]]

^<<v41-11-24,24>>^ This is why I tell you, all the things you pray and ask for, have faith that you have received them, and you will have them.

[[v41-11-25]]

^<<v41-11-25,25>>^ And when you stand praying, forgive whatever you have against anyone, so that your Father who is in the heavens may also forgive you your trespasses.”

[[v41-11-26]]

^<<v41-11-26,26>>^ ^&#42;1^ ——

[NOTE]
====
. See App. A3.
====

[[v41-11-27]]

^<<v41-11-27,27>>^ They came again to Jerusalem. And as he was walking in the temple, the chief priests and the scribes and the elders came

[[v41-11-28]]

^<<v41-11-28,28>>^ and said to him: “By what authority do you do these things? Or who gave you this authority to do these things?”

[[v41-11-29]]

^<<v41-11-29,29>>^ Jesus said to them: “I will ask you one question. Answer me, and I will tell you by what authority I do these things.

[[v41-11-30]]

^<<v41-11-30,30>>^ Was the baptism by John from heaven or from men?^&#42;1^ Answer me.”

[NOTE]
====
. Or “of human origin?”
====

[[v41-11-31]]

^<<v41-11-31,31>>^ So they began to reason among themselves, saying: “If we say, ‘From heaven,’ he will say, ‘Why, then, did you not believe him?’

[[v41-11-32]]

^<<v41-11-32,32>>^ But dare we say, ‘From men’?” They were in fear of the crowd, for these all held that John had really been a prophet.

[[v41-11-33]]

^<<v41-11-33,33>>^ So they answered Jesus: “We do not know.” Jesus said to them: “Neither am I telling you by what authority I do these things.”

'''

xref:041-mark/041-mark-010.adoc#v41-10-0[&#60; Capítulo Anterior] | <<v41-11-0,Topo>> | xref:041-mark/041-mark-012.adoc#v41-12-0[Próximo Capítulo &#62;]