include::./index.adoc[]

[[v41-5-0]]
=== According to Mark, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v41-5-1]]

^<<v41-5-1,1>>^ Then they came to the other side of the sea into the region of the Gerʹa·senes.

[[v41-5-2]]

^<<v41-5-2,2>>^ And immediately after Jesus got out of the boat, a man under the power of an unclean spirit met him from among the tombs.^&#42;1^

[NOTE]
====
. Or “memorial tombs.”
====

[[v41-5-3]]

^<<v41-5-3,3>>^ His haunt was among the tombs, and up to that time, absolutely no one was able to bind him securely, even with a chain.

[[v41-5-4]]

^<<v41-5-4,4>>^ He had often been bound with fetters and chains, but he snapped the chains apart and smashed the fetters; and nobody had the strength to subdue him.

[[v41-5-5]]

^<<v41-5-5,5>>^ And continually, night and day, he was crying out in the tombs and in the mountains and slashing himself with stones.

[[v41-5-6]]

^<<v41-5-6,6>>^ But on catching sight of Jesus from a distance, he ran and bowed down to him.

[[v41-5-7]]

^<<v41-5-7,7>>^ Then he cried out with a loud voice: “What have I to do with you, Jesus, Son of the Most High God? I put you under oath by God not to torment me.”

[[v41-5-8]]

^<<v41-5-8,8>>^ For Jesus had been saying to it: “Come out of the man, you unclean spirit.”

[[v41-5-9]]

^<<v41-5-9,9>>^ But Jesus asked him: “What is your name?” And he replied: “My name is Legion, because there are many of us.”

[[v41-5-10]]

^<<v41-5-10,10>>^ And he kept pleading with Jesus not to send the spirits out of the country.

[[v41-5-11]]

^<<v41-5-11,11>>^ Now a great herd of swine was feeding there at the mountain.

[[v41-5-12]]

^<<v41-5-12,12>>^ So the spirits pleaded with him: “Send us into the swine, so that we may enter into them.”

[[v41-5-13]]

^<<v41-5-13,13>>^ And he gave them permission. With that the unclean spirits came out and went into the swine, and the herd rushed over the precipice^&#42;1^ into the sea, about 2,000 of them, and were drowned in the sea.

[NOTE]
====
. Or “steep bank.”
====

[[v41-5-14]]

^<<v41-5-14,14>>^ But their herders fled and reported it in the city and in the countryside, and people came to see what had happened.

[[v41-5-15]]

^<<v41-5-15,15>>^ So they came to Jesus and saw the demon-possessed man, the one who previously had the legion, sitting clothed and in his right mind, and they grew fearful.

[[v41-5-16]]

^<<v41-5-16,16>>^ Also, those who had seen it related to them how this had happened to the demon-possessed man and the swine.

[[v41-5-17]]

^<<v41-5-17,17>>^ So they began to plead with Jesus to go away from their region.

[[v41-5-18]]

^<<v41-5-18,18>>^ Now as he was boarding the boat, the man who had been demon-possessed pleaded to go with him.

[[v41-5-19]]

^<<v41-5-19,19>>^ However, he did not let him but said to him: “Go home to your relatives, and report to them all the things Jehovah^&#42;1^ has done for you and the mercy he has shown you.”

[NOTE]
====
. See App. A5.
====

[[v41-5-20]]

^<<v41-5-20,20>>^ This man went away and started to proclaim in the De·capʹo·lis^&#42;1^ all the things Jesus had done for him, and all the people were amazed.

[NOTE]
====
. Or “the Ten City Region.”
====

[[v41-5-21]]

^<<v41-5-21,21>>^ After Jesus had crossed again by boat to the opposite shore, a large crowd gathered together to him, and he was by the sea.

[[v41-5-22]]

^<<v41-5-22,22>>^ One of the presiding officers of the synagogue, named Jaʹi·rus, now came, and on catching sight of him, he fell at his feet.

[[v41-5-23]]

^<<v41-5-23,23>>^ He pleaded with him many times, saying: “My little daughter is extremely ill.^&#42;1^ Please come and put your hands on her so that she may get well and live.”

[NOTE]
====
. Or “is near her end.”
====

[[v41-5-24]]

^<<v41-5-24,24>>^ At that Jesus went with him, and a large crowd was following him and pressing against him.

[[v41-5-25]]

^<<v41-5-25,25>>^ Now there was a woman who had had a flow of blood for 12 years.

[[v41-5-26]]

^<<v41-5-26,26>>^ She had suffered much^&#42;1^ at the hands of many physicians and had spent all her resources, and she was no better but, rather, had become worse.

[NOTE]
====
. Or “had been put to many pains.”
====

[[v41-5-27]]

^<<v41-5-27,27>>^ When she heard the reports about Jesus, she came up behind him in the crowd and touched his outer garment,

[[v41-5-28]]

^<<v41-5-28,28>>^ for she kept saying: “If I touch just his outer garments, I will get well.”

[[v41-5-29]]

^<<v41-5-29,29>>^ And immediately her flow of blood dried up, and she sensed in her body that she had been healed of the grievous sickness.

[[v41-5-30]]

^<<v41-5-30,30>>^ Immediately Jesus realized in himself that power had gone out of him, and he turned around in the crowd and asked: “Who touched my outer garments?”

[[v41-5-31]]

^<<v41-5-31,31>>^ But his disciples said to him: “You see the crowd pressing in on you, and you ask, ‘Who touched me?’”

[[v41-5-32]]

^<<v41-5-32,32>>^ However, he was looking around to see who had done this.

[[v41-5-33]]

^<<v41-5-33,33>>^ The woman, frightened and trembling, knowing what had happened to her, came and fell down before him and told him the whole truth.

[[v41-5-34]]

^<<v41-5-34,34>>^ He said to her: “Daughter, your faith has made you well. Go in peace, and be healed from your grievous sickness.”

[[v41-5-35]]

^<<v41-5-35,35>>^ While he was yet speaking, some men from the home of the presiding officer of the synagogue came and said: “Your daughter died! Why bother the Teacher any longer?”

[[v41-5-36]]

^<<v41-5-36,36>>^ But Jesus overheard their words and said to the presiding officer of the synagogue: “Have no fear,^&#42;1^ only exercise faith.”

[NOTE]
====
. Or “Stop being afraid.”
====

[[v41-5-37]]

^<<v41-5-37,37>>^ Now he did not let anyone follow him except Peter, James, and John the brother of James.

[[v41-5-38]]

^<<v41-5-38,38>>^ So they came to the house of the presiding officer of the synagogue, and he saw the commotion and those weeping and wailing loudly.

[[v41-5-39]]

^<<v41-5-39,39>>^ After stepping in, he said to them: “Why are you weeping and causing this commotion? The child has not died but is sleeping.”

[[v41-5-40]]

^<<v41-5-40,40>>^ At this they began to laugh at him scornfully. But after sending them all outside, he took the child’s father and mother and those with him, and he went in where the child was.

[[v41-5-41]]

^<<v41-5-41,41>>^ Then, taking the hand of the child, he said to her: “Talʹi·tha cuʹmi,” which, when translated, means: “Little girl, I say to you, get up!”

[[v41-5-42]]

^<<v41-5-42,42>>^ And immediately the girl rose and began walking. (She was 12 years old.) And at once they were beside themselves with great ecstasy.

[[v41-5-43]]

^<<v41-5-43,43>>^ But he ordered them again and again^&#42;1^ to let no one learn of this, and he said that something should be given her to eat.

[NOTE]
====
. Or “he strongly ordered them.”
====

'''

xref:041-mark/041-mark-004.adoc#v41-4-0[&#60; Capítulo Anterior] | <<v41-5-0,Topo>> | xref:041-mark/041-mark-006.adoc#v41-6-0[Próximo Capítulo &#62;]