include::./index.adoc[]

[[v41-6-0]]
=== According to Mark, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v41-6-1]]

^<<v41-6-1,1>>^ He departed from there and came into his home territory, and his disciples followed him.

[[v41-6-2]]

^<<v41-6-2,2>>^ When it was the Sabbath, he started teaching in the synagogue, and most who heard him were astounded and said: “Where did this man get these things? And why should this wisdom have been given to him, and such powerful works be performed through his hands?

[[v41-6-3]]

^<<v41-6-3,3>>^ This is the carpenter, the son of Mary and the brother of James, Joseph, Judas, and Simon, is it not? And his sisters are here with us, are they not?” So they began to stumble because of him.

[[v41-6-4]]

^<<v41-6-4,4>>^ But Jesus said to them: “A prophet is not without honor except in his home territory and among his relatives and in his own house.”

[[v41-6-5]]

^<<v41-6-5,5>>^ So he was not able to do any powerful work there except to lay his hands on a few sick people and cure them.

[[v41-6-6]]

^<<v41-6-6,6>>^ Indeed, he was amazed at their lack of faith. And he went around in a circuit to the villages, teaching.

[[v41-6-7]]

^<<v41-6-7,7>>^ He now summoned the Twelve and started sending them out two by two, and he gave them authority over the unclean spirits.

[[v41-6-8]]

^<<v41-6-8,8>>^ Also, he gave them orders to carry nothing for the trip except a staff—no bread, no food pouch, no money^&#42;1^ in their belts—

[NOTE]
====
. Lit., “copper.”
====

[[v41-6-9]]

^<<v41-6-9,9>>^ but to put on sandals and not to wear two garments.^&#42;1^

[NOTE]
====
. Or “an extra garment.”
====

[[v41-6-10]]

^<<v41-6-10,10>>^ Further, he said to them: “Wherever you enter into a home, stay there until you leave that place.

[[v41-6-11]]

^<<v41-6-11,11>>^ And wherever a place will not receive you or listen to you, on going out from there, shake off the dirt that is on your feet for a witness to them.”

[[v41-6-12]]

^<<v41-6-12,12>>^ Then they set out and preached that people should repent,

[[v41-6-13]]

^<<v41-6-13,13>>^ and they expelled many demons and greased many sick people with oil and cured them.

[[v41-6-14]]

^<<v41-6-14,14>>^ Now King Herod heard of this, for the name of Jesus became well-known, and people were saying: “John the Baptizer has been raised up from the dead, and that is why the powerful works are operating in him.”

[[v41-6-15]]

^<<v41-6-15,15>>^ But others were saying: “It is E·liʹjah.” Still others were saying: “It is a prophet like one of the prophets of old.”

[[v41-6-16]]

^<<v41-6-16,16>>^ But when Herod heard it, he said: “The John whom I beheaded, this one has been raised up.”

[[v41-6-17]]

^<<v41-6-17,17>>^ For Herod himself had sent out and arrested John and had bound him in prison on account of He·roʹdi·as, the wife of Philip his brother, because he had married her.

[[v41-6-18]]

^<<v41-6-18,18>>^ For John had been saying to Herod: “It is not lawful for you to have your brother’s wife.”

[[v41-6-19]]

^<<v41-6-19,19>>^ So He·roʹdi·as was nursing a grudge against him and wanted to kill him, but she could not.

[[v41-6-20]]

^<<v41-6-20,20>>^ For Herod was in fear of John, knowing him to be a righteous and holy man, and he was keeping him safe. After hearing him, he was at a great loss as to what to do, yet he continued to hear him gladly.

[[v41-6-21]]

^<<v41-6-21,21>>^ But a convenient day arrived when Herod spread an evening meal on his birthday for his high officials and the military commanders and the most prominent men of Galʹi·lee.

[[v41-6-22]]

^<<v41-6-22,22>>^ And the daughter of He·roʹdi·as came in and danced and pleased Herod and those dining^&#42;1^ with him. The king said to the girl: “Ask me for whatever you want, and I will give it to you.”

[NOTE]
====
. Or “reclining at the table.”
====

[[v41-6-23]]

^<<v41-6-23,23>>^ Yes, he swore to her: “Whatever you ask me for, I will give it to you, up to half my kingdom.”

[[v41-6-24]]

^<<v41-6-24,24>>^ So she went out and said to her mother: “What should I ask for?” She said: “The head of John the Baptizer.”

[[v41-6-25]]

^<<v41-6-25,25>>^ She immediately rushed in to the king and made her request, saying: “I want you to give me right away on a platter the head of John the Baptist.”

[[v41-6-26]]

^<<v41-6-26,26>>^ Although this deeply grieved him, the king did not want to disregard her request, because of his oaths and his guests.^&#42;1^

[NOTE]
====
. Or “and those reclining at the table.”
====

[[v41-6-27]]

^<<v41-6-27,27>>^ So the king immediately sent a bodyguard and commanded him to bring John’s head. So he went off and beheaded him in the prison

[[v41-6-28]]

^<<v41-6-28,28>>^ and brought his head on a platter. He gave it to the girl, and the girl gave it to her mother.

[[v41-6-29]]

^<<v41-6-29,29>>^ When his disciples heard of it, they came and took his body and laid it in a tomb.^&#42;1^

[NOTE]
====
. Or “memorial tomb.”
====

[[v41-6-30]]

^<<v41-6-30,30>>^ The apostles gathered around Jesus and reported to him all the things they had done and taught.

[[v41-6-31]]

^<<v41-6-31,31>>^ And he said to them: “Come, you yourselves, privately into an isolated place and rest up a little.” For there were many coming and going, and they had no leisure time even to eat a meal.

[[v41-6-32]]

^<<v41-6-32,32>>^ So they set off in the boat for an isolated place to be by themselves.

[[v41-6-33]]

^<<v41-6-33,33>>^ But people saw them going and many got to know it, and from all the cities they ran together on foot and got there ahead of them.

[[v41-6-34]]

^<<v41-6-34,34>>^ Well, on getting out, he saw a large crowd, and he was moved with pity for them, because they were as sheep without a shepherd. And he started to teach them many things.

[[v41-6-35]]

^<<v41-6-35,35>>^ By now the hour had grown late, and his disciples came up to him and said: “This place is isolated, and the hour is already late.

[[v41-6-36]]

^<<v41-6-36,36>>^ Send them away, so that they may go off into the surrounding countryside and villages and buy themselves something to eat.”

[[v41-6-37]]

^<<v41-6-37,37>>^ He replied to them: “You give them something to eat.” At this they said to him: “Should we go off and buy 200 de·narʹi·i^&#42;1^ worth of bread and give it to the people to eat?”

[NOTE]
====
. See App. B14.
====

[[v41-6-38]]

^<<v41-6-38,38>>^ He said to them: “How many loaves do you have? Go see!” After finding out, they said: “Five, besides two fish.”

[[v41-6-39]]

^<<v41-6-39,39>>^ And he instructed all the people to recline in groups on the green grass.

[[v41-6-40]]

^<<v41-6-40,40>>^ So they reclined in groups of 100 and of 50.

[[v41-6-41]]

^<<v41-6-41,41>>^ Taking now the five loaves and the two fish, he looked up to heaven and said a blessing. Then he broke the loaves up and began giving them to the disciples to place them before the people, and he divided up the two fish for all.

[[v41-6-42]]

^<<v41-6-42,42>>^ So they all ate and were satisfied,

[[v41-6-43]]

^<<v41-6-43,43>>^ and they took up 12 baskets full of fragments, aside from the fish.

[[v41-6-44]]

^<<v41-6-44,44>>^ Those who ate the loaves were 5,000 men.

[[v41-6-45]]

^<<v41-6-45,45>>^ Then, without delay, he made his disciples board the boat and go on ahead to the opposite shore toward Beth·saʹi·da, while he himself sent the crowd away.

[[v41-6-46]]

^<<v41-6-46,46>>^ But after saying good-bye to them, he went to a mountain to pray.

[[v41-6-47]]

^<<v41-6-47,47>>^ When evening had fallen, the boat was in the middle of the sea, but he was alone on the land.

[[v41-6-48]]

^<<v41-6-48,48>>^ So when he saw them struggling to row, for the wind was against them, about the fourth watch of the night^&#42;1^ he came toward them, walking on the sea; but he was inclined to^&#42;2^ pass them by.

[NOTE]
====
. That is, about 3:00 a.m. until sunrise at about 6:00 a.m.
. Or “about to.”
====

[[v41-6-49]]

^<<v41-6-49,49>>^ On catching sight of him walking on the sea, they thought: “It is an apparition!” And they cried out.

[[v41-6-50]]

^<<v41-6-50,50>>^ For they all saw him and were troubled. But immediately he spoke to them and said: “Take courage! It is I; do not be afraid.”

[[v41-6-51]]

^<<v41-6-51,51>>^ Then he got up into the boat with them, and the wind abated. At this they were utterly amazed,

[[v41-6-52]]

^<<v41-6-52,52>>^ for they had not grasped the meaning of the loaves, but their hearts continued dull in understanding.

[[v41-6-53]]

^<<v41-6-53,53>>^ When they got across to land, they came to Gen·nesʹa·ret and anchored the boat nearby.

[[v41-6-54]]

^<<v41-6-54,54>>^ But as soon as they got out of the boat, people recognized him.

[[v41-6-55]]

^<<v41-6-55,55>>^ They ran around all that region and started to bring on stretchers those who were ailing to where they heard he was.

[[v41-6-56]]

^<<v41-6-56,56>>^ And wherever he would enter into villages or cities or the countryside, they would place the sick ones in the marketplaces, and they would plead with him that they might touch just the fringe of his outer garment. And all those who touched it were made well.

'''

xref:041-mark/041-mark-005.adoc#v41-5-0[&#60; Capítulo Anterior] | <<v41-6-0,Topo>> | xref:041-mark/041-mark-007.adoc#v41-7-0[Próximo Capítulo &#62;]