include::./index.adoc[]

[[v41-8-0]]
=== According to Mark, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v41-8-1]]

^<<v41-8-1,1>>^ In those days, there was again a large crowd, and they had nothing to eat. So he summoned the disciples and said to them:

[[v41-8-2]]

^<<v41-8-2,2>>^ “I feel pity for the crowd, because they have already stayed with me for three days and they have nothing to eat.

[[v41-8-3]]

^<<v41-8-3,3>>^ If I send them off to their homes hungry,^&#42;1^ they will give out on the road, and some of them are from far away.”

[NOTE]
====
. Or “fasting.”
====

[[v41-8-4]]

^<<v41-8-4,4>>^ But his disciples answered him: “From where will anyone get enough bread in this isolated place to satisfy these people?”

[[v41-8-5]]

^<<v41-8-5,5>>^ At this he asked them: “How many loaves do you have?” They said: “Seven.”

[[v41-8-6]]

^<<v41-8-6,6>>^ And he instructed the crowd to recline on the ground. Then he took the seven loaves, gave thanks, broke them, and began giving them to his disciples to serve, and they served them to the crowd.

[[v41-8-7]]

^<<v41-8-7,7>>^ They also had a few small fish, and blessing these, he told them to serve these also.

[[v41-8-8]]

^<<v41-8-8,8>>^ So they ate and were satisfied, and they took up seven large baskets^&#42;1^ full of leftover fragments.

[NOTE]
====
. Or “provision baskets.”
====

[[v41-8-9]]

^<<v41-8-9,9>>^ Now there were about 4,000 men. Then he sent them away.

[[v41-8-10]]

^<<v41-8-10,10>>^ Immediately he boarded the boat with his disciples and came into the region of Dal·ma·nuʹtha.

[[v41-8-11]]

^<<v41-8-11,11>>^ Here the Pharisees came and started disputing with him, demanding from him a sign from heaven, to put him to the test.

[[v41-8-12]]

^<<v41-8-12,12>>^ So he sighed deeply in his spirit and said: “Why does this generation seek a sign? Truly I say, no sign will be given to this generation.”

[[v41-8-13]]

^<<v41-8-13,13>>^ With that he left them, got aboard again, and went to the opposite shore.

[[v41-8-14]]

^<<v41-8-14,14>>^ However, they forgot to take bread along, and they had nothing with them in the boat except for one loaf.

[[v41-8-15]]

^<<v41-8-15,15>>^ And he warned them in no uncertain terms: “Keep your eyes open; look out for the leaven of the Pharisees and the leaven of Herod.”

[[v41-8-16]]

^<<v41-8-16,16>>^ So they began arguing with one another over the fact that they had no bread.

[[v41-8-17]]

^<<v41-8-17,17>>^ Noting this, he said to them: “Why do you argue over your having no bread? Do you not yet perceive and understand? Are your hearts still dull in understanding?

[[v41-8-18]]

^<<v41-8-18,18>>^ ‘Though having eyes, do you not see; and though having ears, do you not hear?’ Do you not remember

[[v41-8-19]]

^<<v41-8-19,19>>^ when I broke the five loaves for the 5,000 men, how many baskets full of fragments you collected?” They said to him: “Twelve.”

[[v41-8-20]]

^<<v41-8-20,20>>^ “When I broke the seven loaves for the 4,000 men, how many large baskets^&#42;1^ full of fragments did you take up?” And they said to him: “Seven.”

[NOTE]
====
. Or “provision baskets.”
====

[[v41-8-21]]

^<<v41-8-21,21>>^ With that he said to them: “Do you not yet understand?”

[[v41-8-22]]

^<<v41-8-22,22>>^ Now they put in at Beth·saʹi·da. Here people brought him a blind man, and they pleaded with him to touch him.

[[v41-8-23]]

^<<v41-8-23,23>>^ And he took the blind man by the hand and brought him outside the village. After spitting on his eyes, he laid his hands on him and asked him: “Do you see anything?”

[[v41-8-24]]

^<<v41-8-24,24>>^ The man looked up and said: “I see people, but they look like trees walking about.”

[[v41-8-25]]

^<<v41-8-25,25>>^ Again he laid his hands on the man’s eyes, and the man saw clearly. His sight was restored, and he could see everything distinctly.

[[v41-8-26]]

^<<v41-8-26,26>>^ So he sent him home, saying: “Do not enter into the village.”

[[v41-8-27]]

^<<v41-8-27,27>>^ Jesus and his disciples now left for the villages of Caes·a·reʹa Phi·lipʹpi, and on the way he began to question his disciples, saying: “Who are people saying that I am?”

[[v41-8-28]]

^<<v41-8-28,28>>^ They said to him: “John the Baptist, but others say E·liʹjah, and still others, one of the prophets.”

[[v41-8-29]]

^<<v41-8-29,29>>^ And he put the question to them: “You, though, who do you say I am?” Peter answered him: “You are the Christ.”

[[v41-8-30]]

^<<v41-8-30,30>>^ At that he strictly ordered them not to tell anyone about him.

[[v41-8-31]]

^<<v41-8-31,31>>^ Also, he began teaching them that the Son of man must undergo many sufferings and be rejected by the elders and the chief priests and the scribes and be killed, and rise three days later.

[[v41-8-32]]

^<<v41-8-32,32>>^ Indeed, he was making that statement openly. But Peter took him aside and began to rebuke him.

[[v41-8-33]]

^<<v41-8-33,33>>^ At this he turned, looked at his disciples, and rebuked Peter, saying: “Get behind me, Satan! because you think, not God’s thoughts, but those of men.”

[[v41-8-34]]

^<<v41-8-34,34>>^ He now called the crowd to him with his disciples and said to them: “If anyone wants to come after me, let him disown himself and pick up his torture stake^&#42;1^ and keep following me.

[NOTE]
====
. See Glossary.
====

[[v41-8-35]]

^<<v41-8-35,35>>^ For whoever wants to save his life^&#42;1^ will lose it, but whoever loses his life^&#42;2^ for my sake and for the sake of the good news will save it.

[NOTE]
====
. Or “soul.”
. Or “soul.”
====

[[v41-8-36]]

^<<v41-8-36,36>>^ Really, what good will it do a man to gain the whole world and to lose his life?^&#42;1^

[NOTE]
====
. Or “soul.”
====

[[v41-8-37]]

^<<v41-8-37,37>>^ What, really, would a man give in exchange for his life?^&#42;1^

[NOTE]
====
. Or “soul.”
====

[[v41-8-38]]

^<<v41-8-38,38>>^ For whoever becomes ashamed of me and my words in this adulterous^&#42;1^ and sinful generation, the Son of man will also be ashamed of him when he comes in the glory of his Father with the holy angels.”

[NOTE]
====
. Or “unfaithful.”
====

'''

xref:041-mark/041-mark-007.adoc#v41-7-0[&#60; Capítulo Anterior] | <<v41-8-0,Topo>> | xref:041-mark/041-mark-009.adoc#v41-9-0[Próximo Capítulo &#62;]