include::./index.adoc[]

[[v41-13-0]]
=== According to Mark, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v41-13-1]]

^<<v41-13-1,1>>^ As he was going out of the temple, one of his disciples said to him: “Teacher, see! what wonderful stones and buildings!”

[[v41-13-2]]

^<<v41-13-2,2>>^ However, Jesus said to him: “Do you see these great buildings? By no means will a stone be left here upon a stone and not be thrown down.”

[[v41-13-3]]

^<<v41-13-3,3>>^ As he was sitting on the Mount of Olives with the temple in view, Peter, James, John, and Andrew asked him privately:

[[v41-13-4]]

^<<v41-13-4,4>>^ “Tell us, when will these things be, and what will be the sign when all these things are to come to a conclusion?”

[[v41-13-5]]

^<<v41-13-5,5>>^ So Jesus began to tell them: “Look out that nobody misleads you.

[[v41-13-6]]

^<<v41-13-6,6>>^ Many will come on the basis of my name, saying, ‘I am he,’ and will mislead many.

[[v41-13-7]]

^<<v41-13-7,7>>^ Moreover, when you hear of wars and reports of wars, do not be alarmed; these things must take place, but the end is not yet.

[[v41-13-8]]

^<<v41-13-8,8>>^ “For nation will rise against nation and kingdom against kingdom; there will be earthquakes in one place after another; there will also be food shortages. These are a beginning of pangs of distress.

[[v41-13-9]]

^<<v41-13-9,9>>^ “As for you, look out for yourselves. People will hand you over to local courts, and you will be beaten in synagogues and be put on the stand before governors and kings for my sake, for a witness to them.

[[v41-13-10]]

^<<v41-13-10,10>>^ Also, in all the nations, the good news has to be preached first.

[[v41-13-11]]

^<<v41-13-11,11>>^ And when they are taking you to hand you over, do not be anxious beforehand about what to say; but whatever is given you in that hour, say this, for you are not the ones speaking, but the holy spirit is.

[[v41-13-12]]

^<<v41-13-12,12>>^ Furthermore, brother will deliver brother over to death, and a father a child, and children will rise up against parents and have them put to death.

[[v41-13-13]]

^<<v41-13-13,13>>^ And you will be hated by all people on account of my name. But the one who has endured^&#42;1^ to the end will be saved.

[NOTE]
====
. Or “who endures.”
====

[[v41-13-14]]

^<<v41-13-14,14>>^ “However, when you catch sight of the disgusting thing that causes desolation standing where it should not be (let the reader use discernment), then let those in Ju·deʹa begin fleeing to the mountains.

[[v41-13-15]]

^<<v41-13-15,15>>^ Let the man on the housetop not come down nor go inside to take anything out of his house;

[[v41-13-16]]

^<<v41-13-16,16>>^ and let the man in the field not return to the things behind to pick up his outer garment.

[[v41-13-17]]

^<<v41-13-17,17>>^ Woe to the pregnant women and those nursing a baby in those days!

[[v41-13-18]]

^<<v41-13-18,18>>^ Keep praying that it may not occur in wintertime;

[[v41-13-19]]

^<<v41-13-19,19>>^ for those days will be days of a tribulation such as has not occurred from the beginning of the creation that God created until that time, and will not occur again.

[[v41-13-20]]

^<<v41-13-20,20>>^ In fact, unless Jehovah^&#42;1^ had cut short the days, no flesh would be saved. But on account of the chosen ones whom he has chosen, he has cut short the days.

[NOTE]
====
. See App. A5.
====

[[v41-13-21]]

^<<v41-13-21,21>>^ “Then, too, if anyone says to you, ‘See! Here is the Christ,’ or, ‘See! There he is,’ do not believe it.

[[v41-13-22]]

^<<v41-13-22,22>>^ For false Christs and false prophets will arise and will perform signs and wonders to lead astray, if possible, the chosen ones.

[[v41-13-23]]

^<<v41-13-23,23>>^ You, then, watch out. I have told you all things beforehand.

[[v41-13-24]]

^<<v41-13-24,24>>^ “But in those days, after that tribulation, the sun will be darkened, and the moon will not give its light,

[[v41-13-25]]

^<<v41-13-25,25>>^ and the stars will be falling out of heaven, and the powers that are in the heavens will be shaken.

[[v41-13-26]]

^<<v41-13-26,26>>^ And then they will see the Son of man coming in the clouds with great power and glory.

[[v41-13-27]]

^<<v41-13-27,27>>^ And then he will send out the angels and will gather his chosen ones together from the four winds, from earth’s extremity to heaven’s extremity.

[[v41-13-28]]

^<<v41-13-28,28>>^ “Now learn this illustration from the fig tree: Just as soon as its young branch grows tender and sprouts its leaves, you know that summer is near.

[[v41-13-29]]

^<<v41-13-29,29>>^ Likewise also you, when you see these things happening, know that he is near at the doors.

[[v41-13-30]]

^<<v41-13-30,30>>^ Truly I say to you that this generation will by no means pass away until all these things happen.

[[v41-13-31]]

^<<v41-13-31,31>>^ Heaven and earth will pass away, but my words will by no means pass away.

[[v41-13-32]]

^<<v41-13-32,32>>^ “Concerning that day or the hour nobody knows, neither the angels in heaven nor the Son, but the Father.

[[v41-13-33]]

^<<v41-13-33,33>>^ Keep looking, keep awake, for you do not know when the appointed time is.

[[v41-13-34]]

^<<v41-13-34,34>>^ It is like a man traveling abroad who left his house and gave the authority to his slaves, to each one his work, and commanded the doorkeeper to keep on the watch.

[[v41-13-35]]

^<<v41-13-35,35>>^ Keep on the watch, therefore, for you do not know when the master of the house is coming, whether late in the day or at midnight or before dawn^&#42;1^ or early in the morning,

[NOTE]
====
. Lit., “when the rooster crows.”
====

[[v41-13-36]]

^<<v41-13-36,36>>^ in order that when he comes suddenly, he does not find you sleeping.

[[v41-13-37]]

^<<v41-13-37,37>>^ But what I say to you, I say to all: Keep on the watch.”

'''

xref:041-mark/041-mark-012.adoc#v41-12-0[&#60; Capítulo Anterior] | <<v41-13-0,Topo>> | xref:041-mark/041-mark-014.adoc#v41-14-0[Próximo Capítulo &#62;]