include::./index.adoc[]

[[v41-4-0]]
=== According to Mark, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v41-4-1]]

^<<v41-4-1,1>>^ Again he began teaching beside the sea, and a very large crowd gathered near him. So he went aboard a boat and sat in it away from the shore, but the whole crowd was next to the sea, along the shore.

[[v41-4-2]]

^<<v41-4-2,2>>^ And he began to teach them many things with illustrations, and while he was teaching, he said to them:

[[v41-4-3]]

^<<v41-4-3,3>>^ “Listen. Look! The sower went out to sow.

[[v41-4-4]]

^<<v41-4-4,4>>^ As he was sowing, some seeds fell alongside the road, and the birds came and ate them up.

[[v41-4-5]]

^<<v41-4-5,5>>^ Others fell on rocky ground where there was not much soil, and they immediately sprang up because the soil was not deep.

[[v41-4-6]]

^<<v41-4-6,6>>^ But when the sun rose, they were scorched, and they withered because they had no root.

[[v41-4-7]]

^<<v41-4-7,7>>^ Other seeds fell among the thorns, and the thorns came up and choked them, and they yielded no fruit.

[[v41-4-8]]

^<<v41-4-8,8>>^ But others fell on the fine soil, and growing up and increasing, they began to yield fruit, and they were bearing 30, 60, and 100 times more.”

[[v41-4-9]]

^<<v41-4-9,9>>^ Then he added: “Let the one who has ears to listen, listen.”

[[v41-4-10]]

^<<v41-4-10,10>>^ Now when he was alone, those around him with the Twelve began questioning him about the illustrations.

[[v41-4-11]]

^<<v41-4-11,11>>^ He said to them: “To you the sacred secret of the Kingdom of God has been given, but to those outside all things are in illustrations,

[[v41-4-12]]

^<<v41-4-12,12>>^ so that, though looking, they may look and still not see, and though hearing, they may hear and still not get the sense of it; nor will they ever turn back and receive forgiveness.”

[[v41-4-13]]

^<<v41-4-13,13>>^ Further, he said to them: “You do not know this illustration, so how will you understand all the other illustrations?

[[v41-4-14]]

^<<v41-4-14,14>>^ “The sower sows the word.

[[v41-4-15]]

^<<v41-4-15,15>>^ These, then, are the ones alongside the road where the word is sown; but as soon as they have heard it, Satan comes and takes away the word that was sown in them.

[[v41-4-16]]

^<<v41-4-16,16>>^ Likewise, these are the ones sown on rocky ground; as soon as they have heard the word, they accept it with joy.

[[v41-4-17]]

^<<v41-4-17,17>>^ Yet they have no root in themselves, but they continue for a time; then as soon as tribulation or persecution arises because of the word, they are stumbled.

[[v41-4-18]]

^<<v41-4-18,18>>^ There are still others that are sown among the thorns. These are the ones who have heard the word,

[[v41-4-19]]

^<<v41-4-19,19>>^ but the anxieties of this system of things^&#42;1^ and the deceptive power of riches and the desires for everything else make inroads and choke the word, and it becomes unfruitful.

[NOTE]
====
. Or “this age.” See Glossary.
====

[[v41-4-20]]

^<<v41-4-20,20>>^ Finally, the ones that were sown on the fine soil are those who listen to the word and favorably receive it and bear fruit—30, 60, and 100 times more.”

[[v41-4-21]]

^<<v41-4-21,21>>^ He also said to them: “A lamp is not brought out to be put under a basket^&#42;1^ or under a bed, is it? Is it not brought out to be put on a lampstand?

[NOTE]
====
. Or “measuring basket.”
====

[[v41-4-22]]

^<<v41-4-22,22>>^ For there is nothing hidden that will not be exposed; nothing is carefully concealed that will not come out in the open.

[[v41-4-23]]

^<<v41-4-23,23>>^ Whoever has ears to listen, let him listen.”

[[v41-4-24]]

^<<v41-4-24,24>>^ He further said to them: “Pay attention to what you are hearing. With the measure that you are measuring out, you will have it measured out to you, yes, you will have more added to you.

[[v41-4-25]]

^<<v41-4-25,25>>^ For whoever has will have more given to him, but whoever does not have, even what he has will be taken away from him.”

[[v41-4-26]]

^<<v41-4-26,26>>^ So he went on to say: “In this way the Kingdom of God is just as when a man casts seeds on the ground.

[[v41-4-27]]

^<<v41-4-27,27>>^ He sleeps at night and rises up by day, and the seeds sprout and grow tall—just how, he does not know.

[[v41-4-28]]

^<<v41-4-28,28>>^ On its own the ground bears fruit gradually, first the stalk, then the head, finally the full grain in the head.

[[v41-4-29]]

^<<v41-4-29,29>>^ But as soon as the crop permits it, he thrusts in the sickle, because the harvesttime has come.”

[[v41-4-30]]

^<<v41-4-30,30>>^ And he went on to say: “With what can we compare the Kingdom of God, or with what illustration can we explain it?

[[v41-4-31]]

^<<v41-4-31,31>>^ It is like a mustard grain, which at the time it was sown in the ground was the tiniest of all the seeds on the earth.

[[v41-4-32]]

^<<v41-4-32,32>>^ But when it has been sown, it grows and becomes greater than all other vegetable plants and produces great branches, so that the birds of heaven are able to find lodging under its shadow.”

[[v41-4-33]]

^<<v41-4-33,33>>^ With many illustrations of that sort he spoke the word to them, to the extent that they were able to listen.

[[v41-4-34]]

^<<v41-4-34,34>>^ Indeed, without an illustration he would not speak to them, but he would explain all things privately to his disciples.

[[v41-4-35]]

^<<v41-4-35,35>>^ And on that day, when evening had fallen, he said to them: “Let us cross to the other shore.”

[[v41-4-36]]

^<<v41-4-36,36>>^ So after they had dismissed the crowd, they took him in the boat, just as he was, and there were other boats with him.

[[v41-4-37]]

^<<v41-4-37,37>>^ Now a great violent windstorm broke out, and the waves kept crashing into the boat, so that the boat was close to being swamped.

[[v41-4-38]]

^<<v41-4-38,38>>^ But he was in the stern, sleeping on the pillow.^&#42;1^ So they woke him up and said to him: “Teacher, do you not care that we are about to perish?”

[NOTE]
====
. Or “cushion.”
====

[[v41-4-39]]

^<<v41-4-39,39>>^ With that he got up and rebuked the wind and said to the sea: “Hush! Be quiet!” And the wind abated, and a great calm set in.

[[v41-4-40]]

^<<v41-4-40,40>>^ So he said to them: “Why are you so afraid?^&#42;1^ Do you not yet have any faith?”

[NOTE]
====
. Or “fainthearted?”
====

[[v41-4-41]]

^<<v41-4-41,41>>^ But they felt an unusual fear, and they said to one another: “Who really is this? Even the wind and the sea obey him.”

'''

xref:041-mark/041-mark-003.adoc#v41-3-0[&#60; Capítulo Anterior] | <<v41-4-0,Topo>> | xref:041-mark/041-mark-005.adoc#v41-5-0[Próximo Capítulo &#62;]