include::./index.adoc[]

[[v41-12-0]]
=== According to Mark, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v41-12-1]]

^<<v41-12-1,1>>^ Then he started to speak to them with illustrations: “A man planted a vineyard and put a fence around it and dug a vat for the winepress and erected a tower; then he leased it to cultivators and traveled abroad.

[[v41-12-2]]

^<<v41-12-2,2>>^ In due season he sent a slave to the cultivators to collect some of the fruits of the vineyard from them.

[[v41-12-3]]

^<<v41-12-3,3>>^ But they took him, beat him, and sent him away empty-handed.

[[v41-12-4]]

^<<v41-12-4,4>>^ Again he sent another slave to them, and that one they struck on the head and dishonored.

[[v41-12-5]]

^<<v41-12-5,5>>^ And he sent another, and that one they killed, and many others, some of whom they beat and some of whom they killed.

[[v41-12-6]]

^<<v41-12-6,6>>^ One more he had, a beloved son. He sent him to them last, saying, ‘They will respect my son.’

[[v41-12-7]]

^<<v41-12-7,7>>^ But those cultivators said among themselves, ‘This is the heir. Come, let us kill him, and the inheritance will be ours.’

[[v41-12-8]]

^<<v41-12-8,8>>^ So they took him and killed him and threw him out of the vineyard.

[[v41-12-9]]

^<<v41-12-9,9>>^ What will the owner of the vineyard do? He will come and kill the cultivators and will give the vineyard to others.

[[v41-12-10]]

^<<v41-12-10,10>>^ Did you never read this scripture: ‘The stone that the builders rejected, this has become the chief cornerstone.^&#42;1^

[NOTE]
====
. Lit., “the head of the corner.”
====

[[v41-12-11]]

^<<v41-12-11,11>>^ This has come from Jehovah,^&#42;1^ and it is marvelous in our eyes’?”

[NOTE]
====
. See App. A5.
====

[[v41-12-12]]

^<<v41-12-12,12>>^ At that they wanted to seize^&#42;1^ him, but they feared the crowd, for they knew that he spoke the illustration with them in mind. So they left him and went away.

[NOTE]
====
. Or “arrest.”
====

[[v41-12-13]]

^<<v41-12-13,13>>^ Next they sent to him some of the Pharisees and of the party followers of Herod in order to catch him in his speech.

[[v41-12-14]]

^<<v41-12-14,14>>^ On arriving, these said to him: “Teacher, we know you are truthful and you do not seek anyone’s favor, for you do not look at the outward appearance of people, but you teach the way of God in line with truth. Is it lawful^&#42;1^ to pay head tax to Caesar or not?

[NOTE]
====
. Or “right.”
====

[[v41-12-15]]

^<<v41-12-15,15>>^ Should we pay, or should we not pay?” Detecting their hypocrisy, he said to them: “Why do you put me to the test? Bring me a de·narʹi·us^&#42;1^ to look at.”

[NOTE]
====
. See App. B14.
====

[[v41-12-16]]

^<<v41-12-16,16>>^ They brought one, and he said to them: “Whose image and inscription is this?” They said to him: “Caesar’s.”

[[v41-12-17]]

^<<v41-12-17,17>>^ Jesus then said: “Pay back Caesar’s things to Caesar, but God’s things to God.” And they were amazed at him.

[[v41-12-18]]

^<<v41-12-18,18>>^ Now the Sadducees, who say there is no resurrection, came and asked him:

[[v41-12-19]]

^<<v41-12-19,19>>^ “Teacher, Moses wrote us that if someone’s brother dies and leaves a wife behind but does not leave a child, his brother should take the wife and raise up offspring for his brother.

[[v41-12-20]]

^<<v41-12-20,20>>^ There were seven brothers. The first took a wife, but when he died he left no offspring.

[[v41-12-21]]

^<<v41-12-21,21>>^ And the second married her but died without leaving offspring, and the third the same way.

[[v41-12-22]]

^<<v41-12-22,22>>^ And all seven left no offspring. Last of all, the woman also died.

[[v41-12-23]]

^<<v41-12-23,23>>^ In the resurrection, whose wife will she be? For the seven had her as a wife.”

[[v41-12-24]]

^<<v41-12-24,24>>^ Jesus said to them: “Is not this why you are mistaken, because you know neither the Scriptures nor the power of God?

[[v41-12-25]]

^<<v41-12-25,25>>^ For when they rise from the dead, neither do men marry nor are women given in marriage, but they are as angels in the heavens.

[[v41-12-26]]

^<<v41-12-26,26>>^ But concerning the dead being raised up, have you not read in the book of Moses, in the account about the thornbush, that God said to him: ‘I am the God of Abraham and God of Isaac and God of Jacob’?

[[v41-12-27]]

^<<v41-12-27,27>>^ He is a God, not of the dead, but of the living. You are very much mistaken.”

[[v41-12-28]]

^<<v41-12-28,28>>^ One of the scribes who had come up and heard them disputing, knowing that he had answered them in a fine way, asked him: “Which commandment is first^&#42;1^ of all?”

[NOTE]
====
. Or “most important.”
====

[[v41-12-29]]

^<<v41-12-29,29>>^ Jesus answered: “The first is, ‘Hear, O Israel, Jehovah^&#42;1^ our God is one Jehovah,^&#42;2^

[NOTE]
====
. See App. A5.
. See App. A5.
====

[[v41-12-30]]

^<<v41-12-30,30>>^ and you must love Jehovah^&#42;1^ your God with your whole heart and with your whole soul^&#42;2^ and with your whole mind and with your whole strength.’

[NOTE]
====
. See App. A5.
. See Glossary.
====

[[v41-12-31]]

^<<v41-12-31,31>>^ The second is this, ‘You must love your neighbor as yourself.’ There is no other commandment greater than these.”

[[v41-12-32]]

^<<v41-12-32,32>>^ The scribe said to him: “Teacher, you spoke well, in line with truth, ‘He is One, and there is no other besides him’;

[[v41-12-33]]

^<<v41-12-33,33>>^ and to love him with one’s whole heart, with one’s whole understanding, and with one’s whole strength and to love one’s neighbor as oneself is worth far more than all the whole burnt offerings and sacrifices.”

[[v41-12-34]]

^<<v41-12-34,34>>^ At this Jesus, discerning that he had answered intelligently, said to him: “You are not far from the Kingdom of God.” But no one had the courage to question him anymore.

[[v41-12-35]]

^<<v41-12-35,35>>^ However, as Jesus continued teaching in the temple, he said: “How is it that the scribes say that the Christ is David’s son?

[[v41-12-36]]

^<<v41-12-36,36>>^ By the holy spirit, David himself said, ‘Jehovah^&#42;1^ said to my Lord: “Sit at my right hand until I put your enemies beneath your feet.”’

[NOTE]
====
. See App. A5.
====

[[v41-12-37]]

^<<v41-12-37,37>>^ David himself calls him Lord, so how can it be that he is his son?”
And the large crowd was listening to him with pleasure.

[[v41-12-38]]

^<<v41-12-38,38>>^ And in his teaching he went on to say: “Beware of the scribes who want to walk around in robes and want greetings in the marketplaces

[[v41-12-39]]

^<<v41-12-39,39>>^ and front^&#42;1^ seats in the synagogues and the most prominent places at evening meals.

[NOTE]
====
. Or “best.”
====

[[v41-12-40]]

^<<v41-12-40,40>>^ They devour the houses^&#42;1^ of the widows, and for show^&#42;2^ they make long prayers. These will receive a more severe^&#42;3^ judgment.”

[NOTE]
====
. Or “property.”
. Or “for a pretext.”
. Or “a heavier.”
====

[[v41-12-41]]

^<<v41-12-41,41>>^ And he sat down with the treasury chests^&#42;1^ in view and began observing how the crowd was dropping money into the treasury chests, and many rich people were dropping in many coins.

[NOTE]
====
. Or “receptacles.”
====

[[v41-12-42]]

^<<v41-12-42,42>>^ Now a poor widow came and dropped in two small coins of very little value.^&#42;1^

[NOTE]
====
. Lit., “two lepta, which is a quadrans.” See App. B14.
====

[[v41-12-43]]

^<<v41-12-43,43>>^ So he called his disciples to him and said to them: “Truly I say to you that this poor widow put in more than all the others who put money into the treasury chests.

[[v41-12-44]]

^<<v41-12-44,44>>^ For they all put in out of their surplus, but she, out of her want,^&#42;1^ put in everything she had, all she had to live on.”

[NOTE]
====
. Or “poverty.”
====

'''

xref:041-mark/041-mark-011.adoc#v41-11-0[&#60; Capítulo Anterior] | <<v41-12-0,Topo>> | xref:041-mark/041-mark-013.adoc#v41-13-0[Próximo Capítulo &#62;]