include::./index.adoc[]

[[v41-3-0]]
=== According to Mark, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v41-3-1]]

^<<v41-3-1,1>>^ Once again he entered into a synagogue, and a man with a withered^&#42;1^ hand was there.

[NOTE]
====
. Or “paralyzed.”
====

[[v41-3-2]]

^<<v41-3-2,2>>^ So they were watching him closely to see whether he would cure the man on the Sabbath, in order to accuse him.

[[v41-3-3]]

^<<v41-3-3,3>>^ He said to the man with the withered^&#42;1^ hand: “Get up and come to the center.”

[NOTE]
====
. Or “paralyzed.”
====

[[v41-3-4]]

^<<v41-3-4,4>>^ Next he said to them: “Is it lawful on the Sabbath to do good or to do harm, to save a life^&#42;1^ or to kill?” But they kept silent.

[NOTE]
====
. Or “soul.”
====

[[v41-3-5]]

^<<v41-3-5,5>>^ After looking around at them with indignation, being thoroughly grieved at the insensibility of their hearts, he said to the man: “Stretch out your hand.” And he stretched it out, and his hand was restored.

[[v41-3-6]]

^<<v41-3-6,6>>^ At that the Pharisees went out and immediately began holding council with the party followers of Herod against him, in order to kill him.

[[v41-3-7]]

^<<v41-3-7,7>>^ But Jesus departed for the sea along with his disciples, and a great multitude from Galʹi·lee and from Ju·deʹa followed him.

[[v41-3-8]]

^<<v41-3-8,8>>^ Even from Jerusalem and from Id·u·meʹa and from across the Jordan and from around Tyre and Siʹdon, a great multitude came to him when they heard about the many things he was doing.

[[v41-3-9]]

^<<v41-3-9,9>>^ And he told his disciples to have a small boat ready for him so that the crowd would not press in on him.

[[v41-3-10]]

^<<v41-3-10,10>>^ Because he cured many, all those who had serious diseases were crowding around him to touch him.

[[v41-3-11]]

^<<v41-3-11,11>>^ Even the unclean spirits, whenever they saw him, would fall down before him and cry out and say: “You are the Son of God.”

[[v41-3-12]]

^<<v41-3-12,12>>^ But many times he sternly ordered them not to make him known.

[[v41-3-13]]

^<<v41-3-13,13>>^ He ascended a mountain and summoned those whom he wanted, and they came to him.

[[v41-3-14]]

^<<v41-3-14,14>>^ And he formed^&#42;1^ a group of 12, whom he also named apostles, those who were to accompany him and whom he would send out to preach

[NOTE]
====
. Or “appointed.”
====

[[v41-3-15]]

^<<v41-3-15,15>>^ and to have authority to expel demons.

[[v41-3-16]]

^<<v41-3-16,16>>^ And the group of 12 that he formed^&#42;1^ were Simon, to whom he also gave the name Peter,

[NOTE]
====
. Or “appointed.”
====

[[v41-3-17]]

^<<v41-3-17,17>>^ James the son of Zebʹe·dee and John the brother of James (he also gave these the name Bo·a·nerʹges, which means “Sons of Thunder”),

[[v41-3-18]]

^<<v41-3-18,18>>^ Andrew, Philip, Bar·tholʹo·mew, Matthew, Thomas, James the son of Al·phaeʹus, Thad·daeʹus, Simon the Ca·na·naeʹan,^&#42;1^

[NOTE]
====
. Or “the zealous one.”
====

[[v41-3-19]]

^<<v41-3-19,19>>^ and Judas Is·carʹi·ot, who later betrayed him.
Then he went into a house,

[[v41-3-20]]

^<<v41-3-20,20>>^ and again the crowd gathered, so that they were not able even to eat a meal.

[[v41-3-21]]

^<<v41-3-21,21>>^ But when his relatives heard about it, they went out to seize him, for they were saying: “He has gone out of his mind.”

[[v41-3-22]]

^<<v41-3-22,22>>^ Also, the scribes who came down from Jerusalem were saying: “He has Be·elʹze·bub,^&#42;1^ and he expels the demons by means of the ruler of the demons.”

[NOTE]
====
. A designation applied to Satan.
====

[[v41-3-23]]

^<<v41-3-23,23>>^ So after calling them to him, he spoke to them with illustrations: “How can Satan expel Satan?

[[v41-3-24]]

^<<v41-3-24,24>>^ If a kingdom becomes divided against itself, that kingdom cannot stand;

[[v41-3-25]]

^<<v41-3-25,25>>^ and if a house becomes divided against itself, that house will not be able to stand.

[[v41-3-26]]

^<<v41-3-26,26>>^ Also, if Satan has risen up against himself and has become divided, he cannot stand but is coming to an end.

[[v41-3-27]]

^<<v41-3-27,27>>^ In fact, no one who enters the house of a strong man is able to steal his possessions unless he first ties up the strong man. Only then can he plunder his house.

[[v41-3-28]]

^<<v41-3-28,28>>^ Truly I say to you that all things will be forgiven the sons of men, no matter what sins they commit and what blasphemies they speak.

[[v41-3-29]]

^<<v41-3-29,29>>^ But whoever blasphemes against the holy spirit has no forgiveness forever but is guilty of everlasting sin.”

[[v41-3-30]]

^<<v41-3-30,30>>^ He said this because they were saying: “He has an unclean spirit.”

[[v41-3-31]]

^<<v41-3-31,31>>^ Now his mother and his brothers came, and standing outside, they sent someone in to call him.

[[v41-3-32]]

^<<v41-3-32,32>>^ As there was a crowd sitting around him, they said to him: “Look! Your mother and your brothers are outside asking for you.”

[[v41-3-33]]

^<<v41-3-33,33>>^ But he replied to them: “Who are my mother and my brothers?”

[[v41-3-34]]

^<<v41-3-34,34>>^ Then he looked at those sitting around him in a circle and said: “See, my mother and my brothers!

[[v41-3-35]]

^<<v41-3-35,35>>^ Whoever does the will of God, this one is my brother and sister and mother.”

'''

xref:041-mark/041-mark-002.adoc#v41-2-0[&#60; Capítulo Anterior] | <<v41-3-0,Topo>> | xref:041-mark/041-mark-004.adoc#v41-4-0[Próximo Capítulo &#62;]