include::./index.adoc[]

[[v53-3-0]]
=== The Second to the Thessalonians, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v53-3-1]]

^<<v53-3-1,1>>^ Finally, brothers, carry on prayer for us, that the word of Jehovah^&#42;1^ may keep spreading rapidly and being glorified, just as it is with you,

[NOTE]
====
. See App. A5.
====

[[v53-3-2]]

^<<v53-3-2,2>>^ and that we may be rescued from harmful and wicked men, for faith is not a possession of all people.

[[v53-3-3]]

^<<v53-3-3,3>>^ But the Lord is faithful, and he will strengthen you and protect you from the wicked one.

[[v53-3-4]]

^<<v53-3-4,4>>^ Moreover, we have confidence in the Lord regarding you, that you are carrying out and will go on carrying out our instructions.

[[v53-3-5]]

^<<v53-3-5,5>>^ May the Lord continue to guide your hearts successfully to the love of God and to the endurance for the Christ.

[[v53-3-6]]

^<<v53-3-6,6>>^ Now we are giving you instructions, brothers, in the name of our Lord Jesus Christ, to withdraw from every brother who is walking disorderly and not according to the tradition^&#42;1^ that you^&#42;2^ received from us.

[NOTE]
====
. Or “instruction.”
. Or possibly, “they.”
====

[[v53-3-7]]

^<<v53-3-7,7>>^ For you yourselves know how you should imitate us, because we did not behave in a disorderly way among you,

[[v53-3-8]]

^<<v53-3-8,8>>^ nor did we eat anyone’s food free.^&#42;1^ On the contrary, by labor and toil we were working night and day so as not to impose an expensive burden on any one of you.

[NOTE]
====
. Or “without paying.”
====

[[v53-3-9]]

^<<v53-3-9,9>>^ Not that we do not have authority, but we wanted to offer ourselves as an example for you to imitate.

[[v53-3-10]]

^<<v53-3-10,10>>^ In fact, when we were with you, we used to give you this order: “If anyone does not want to work, neither let him eat.”

[[v53-3-11]]

^<<v53-3-11,11>>^ For we hear that some are walking disorderly among you, not working at all, but meddling with what does not concern them.

[[v53-3-12]]

^<<v53-3-12,12>>^ To such people we give the order and exhortation in the Lord Jesus Christ that they should work quietly and eat food they themselves earn.

[[v53-3-13]]

^<<v53-3-13,13>>^ For your part, brothers, do not give up in doing good.

[[v53-3-14]]

^<<v53-3-14,14>>^ But if anyone is not obedient to our word through this letter, keep this one marked and stop associating with him, so that he may become ashamed.

[[v53-3-15]]

^<<v53-3-15,15>>^ And yet do not consider him an enemy, but continue admonishing him as a brother.

[[v53-3-16]]

^<<v53-3-16,16>>^ Now may the Lord of peace himself give you peace constantly in every way. May the Lord be with all of you.

[[v53-3-17]]

^<<v53-3-17,17>>^ Here is my greeting, Paul’s, in my own hand, which is a sign in every letter; this is the way I write.

[[v53-3-18]]

^<<v53-3-18,18>>^ The undeserved kindness of our Lord Jesus Christ be with all of you.

'''

xref:053-2-thessalonians/053-2-thessalonians-002.adoc#v53-2-0[&#60; Capítulo Anterior] | <<v53-3-0,Topo>> | xref:054-1-timothy/054-1-timothy-001.adoc#v54-1-0[Próximo Capítulo &#62;]