include::./index.adoc[]

[[v53-1-0]]
=== The Second to the Thessalonians, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v53-1-1]]

^<<v53-1-1,1>>^ Paul, Sil·vaʹnus,^&#42;1^ and Timothy, to the congregation of the Thes·sa·loʹni·ans in union with God our Father and the Lord Jesus Christ:

[NOTE]
====
. Also called Silas.
====

[[v53-1-2]]

^<<v53-1-2,2>>^ May you have undeserved kindness and peace from God the Father and the Lord Jesus Christ.

[[v53-1-3]]

^<<v53-1-3,3>>^ We are obligated always to give thanks to God for you, brothers. This is fitting, because your faith is growing exceedingly and the love of each and every one of you is increasing toward one another.

[[v53-1-4]]

^<<v53-1-4,4>>^ As a result we ourselves take pride in you among the congregations of God because of your endurance and faith in all your persecutions and the hardships^&#42;1^ that you are suffering.^&#42;2^

[NOTE]
====
. Or “tribulations.”
. Or “enduring.”
====

[[v53-1-5]]

^<<v53-1-5,5>>^ This is a proof of the righteous judgment of God, leading to your being counted worthy of the Kingdom of God, for which you are indeed suffering.

[[v53-1-6]]

^<<v53-1-6,6>>^ This takes into account that it is righteous on God’s part to repay tribulation to those who make tribulation for you.

[[v53-1-7]]

^<<v53-1-7,7>>^ But you who suffer tribulation will be given relief along with us at the revelation of the Lord Jesus from heaven with his powerful angels

[[v53-1-8]]

^<<v53-1-8,8>>^ in a flaming fire, as he brings vengeance on those who do not know God and those who do not obey the good news about our Lord Jesus.

[[v53-1-9]]

^<<v53-1-9,9>>^ These very ones will undergo the judicial punishment of everlasting destruction from before the Lord and from the glory of his strength,

[[v53-1-10]]

^<<v53-1-10,10>>^ at the time when he comes to be glorified in connection with his holy ones and to be regarded in that day with wonder among all those who exercised faith, because the witness we gave met with faith among you.

[[v53-1-11]]

^<<v53-1-11,11>>^ To that very end we always pray for you, that our God may count you worthy of his calling and with his power perform completely all the good that he pleases and every work of faith.

[[v53-1-12]]

^<<v53-1-12,12>>^ This is so that the name of our Lord Jesus may be glorified in you and you in union with him, according to the undeserved kindness of our God and of the Lord Jesus Christ.

'''

xref:052-1-thessalonians/052-1-thessalonians-005.adoc#v52-5-0[&#60; Capítulo Anterior] | <<v53-1-0,Topo>> | xref:053-2-thessalonians/053-2-thessalonians-002.adoc#v53-2-0[Próximo Capítulo &#62;]