include::./index.adoc[]

[[v22-5-0]]
=== The Song of Solomon, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v22-5-1]]

^<<v22-5-1,1>>^ “I have entered my garden,
O my sister, my bride.
I have picked my myrrh and my spice.
I have eaten my honeycomb and my honey;
I have drunk my wine and my milk.”
“Eat, dear friends!
Drink and become intoxicated with expressions of affection!”

[[v22-5-2]]

^<<v22-5-2,2>>^ “I am asleep, but my heart is awake.
There is the sound of my dear one knocking!
‘Open to me, O my sister, my beloved,
My dove, my flawless one!
For my head is wet with dew,
The locks of my hair with the moisture of the night.’

[[v22-5-3]]

^<<v22-5-3,3>>^ I have taken off my robe.
Must I put it back on?
I have washed my feet.
Must I soil them again?

[[v22-5-4]]

^<<v22-5-4,4>>^ My dear one withdrew his hand from the hole of the door,
And my feelings for him were stirred.

[[v22-5-5]]

^<<v22-5-5,5>>^ I got up to open to my dear one;
My hands dripped with myrrh,
And my fingers with liquid myrrh,
Onto the handles of the lock.

[[v22-5-6]]

^<<v22-5-6,6>>^ I opened to my dear one,
But my dear one had turned away, he had gone.
I felt despair^&#42;1^ when he departed.^&#42;2^
I sought him, but I did not find him.
I called him, but he did not answer me.

[NOTE]
====
. Or “My soul went out.”
. Or possibly, “My soul left me when he spoke.”
====

[[v22-5-7]]

^<<v22-5-7,7>>^ The watchmen making their rounds in the city found me.
They struck me, they wounded me.
The watchmen of the walls took my shawl^&#42;1^ away from me.

[NOTE]
====
. Or “veil.”
====

[[v22-5-8]]

^<<v22-5-8,8>>^ I put you under oath, O daughters of Jerusalem:
If you find my dear one,
Tell him that I am lovesick.”

[[v22-5-9]]

^<<v22-5-9,9>>^ “How is your dear one better than any other dear one,
You most beautiful of women?
How is your dear one better than any other dear one,
That you put us under such an oath?”

[[v22-5-10]]

^<<v22-5-10,10>>^ “My dear one is dazzling and ruddy;
He stands out among ten thousand.

[[v22-5-11]]

^<<v22-5-11,11>>^ His head is gold, the finest gold.
The locks of his hair are like waving palm fronds,^&#42;1^
As black as the raven.

[NOTE]
====
. Or possibly, “like date clusters.”
====

[[v22-5-12]]

^<<v22-5-12,12>>^ His eyes are like doves by streams of water,
Bathing themselves in milk,
Sitting by a brimming pool.^&#42;1^

[NOTE]
====
. Or possibly, “the fountain rims.”
====

[[v22-5-13]]

^<<v22-5-13,13>>^ His cheeks are like a bed of spices,
Mounds of scented herbs.
His lips are lilies, dripping with liquid myrrh.

[[v22-5-14]]

^<<v22-5-14,14>>^ His hands are cylinders of gold, set with chrysʹo·lite.
His abdomen is polished ivory covered with sapphires.

[[v22-5-15]]

^<<v22-5-15,15>>^ His legs are pillars of marble set on pedestals of the finest gold.
His appearance is like Lebʹa·non, as unrivaled as the cedars.

[[v22-5-16]]

^<<v22-5-16,16>>^ His mouth^&#42;1^ is sweetness itself,
And everything about him is desirable.
This is my dear one, this is my beloved, O daughters of Jerusalem.”

[NOTE]
====
. Lit., “palate.”
====

'''

xref:022-song-of-solomon/022-song-of-solomon-004.adoc#v22-4-0[&#60; Capítulo Anterior] | <<v22-5-0,Topo>> | xref:022-song-of-solomon/022-song-of-solomon-006.adoc#v22-6-0[Próximo Capítulo &#62;]