include::./index.adoc[]

[[v22-2-0]]
=== The Song of Solomon, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v22-2-1]]

^<<v22-2-1,1>>^ “I am but a saffron^&#42;1^ of the coastal plain,
A lily of the valleys.”

[NOTE]
====
. Or “crocus.”
====

[[v22-2-2]]

^<<v22-2-2,2>>^ “Like a lily among thorns
Is my beloved among the daughters.”

[[v22-2-3]]

^<<v22-2-3,3>>^ “Like an apple tree among the trees of the forest,
So is my dear one among the sons.
I passionately desire to sit in his shade,
And his fruit is sweet to my taste.

[[v22-2-4]]

^<<v22-2-4,4>>^ He brought me into the banquet house,^&#42;1^
And his banner over me was love.

[NOTE]
====
. Lit., “the house of wine.”
====

[[v22-2-5]]

^<<v22-2-5,5>>^ Refresh me with raisin cakes;
Sustain me with apples,
For I am lovesick.

[[v22-2-6]]

^<<v22-2-6,6>>^ His left hand is under my head,
And his right hand embraces me.

[[v22-2-7]]

^<<v22-2-7,7>>^ I put you under oath, O daughters of Jerusalem,
By the gazelles and the does of the field:
Do not try to awaken or arouse love in me until it feels inclined.

[[v22-2-8]]

^<<v22-2-8,8>>^ The sound of my dear one!
Look! Here he comes,
Climbing the mountains, leaping over the hills.

[[v22-2-9]]

^<<v22-2-9,9>>^ My dear one is like a gazelle, like a young stag.
There he is, standing behind our wall,
Gazing through the windows,
Looking through the lattices.

[[v22-2-10]]

^<<v22-2-10,10>>^ My dear one speaks, he says to me:
‘Rise up, my beloved,
My beautiful one, come away with me.

[[v22-2-11]]

^<<v22-2-11,11>>^ Look! The winter^&#42;1^ has passed.
The rains are over and gone.

[NOTE]
====
. Or “rainy season.”
====

[[v22-2-12]]

^<<v22-2-12,12>>^ Blossoms have appeared in the land,
The time of pruning has arrived,
And the song of the turtledove is heard in our land.

[[v22-2-13]]

^<<v22-2-13,13>>^ The fig tree ripens its early figs;
The vines are in blossom and give off their fragrance.
Rise up, my beloved, and come.
My beautiful one, come away with me.

[[v22-2-14]]

^<<v22-2-14,14>>^ O my dove, in the retreats of the crag,
In the recesses of the cliff,
Let me see you and hear your voice,
For your voice is pleasant and your appearance is lovely.’”

[[v22-2-15]]

^<<v22-2-15,15>>^ “Catch the foxes for us,
The little foxes that ruin the vineyards,
For our vineyards are in bloom.”

[[v22-2-16]]

^<<v22-2-16,16>>^ “My dear one is mine and I am his.
He is shepherding among the lilies.

[[v22-2-17]]

^<<v22-2-17,17>>^ Until the day grows breezy^&#42;1^ and the shadows flee,
Return quickly, O my dear one,
Like the gazelle or the young stag upon the mountains of separation.^&#42;2^

[NOTE]
====
. Lit., “the day breathes.”
. Or possibly, “the cleft mountains.” Or “the mountains of Bether.”
====

'''

xref:022-song-of-solomon/022-song-of-solomon-001.adoc#v22-1-0[&#60; Capítulo Anterior] | <<v22-2-0,Topo>> | xref:022-song-of-solomon/022-song-of-solomon-003.adoc#v22-3-0[Próximo Capítulo &#62;]