include::./index.adoc[]

[[v43-14-0]]
=== According to John, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-14-1]]

^<<v43-14-1,1>>^ “Do not let your hearts be troubled. Exercise faith in God; exercise faith also in me.

[[v43-14-2]]

^<<v43-14-2,2>>^ In the house of my Father are many dwelling places.^&#42;1^ Otherwise, I would have told you, for I am going my way to prepare a place for you.

[NOTE]
====
. Or “many abodes.”
====

[[v43-14-3]]

^<<v43-14-3,3>>^ Also, if I go my way and prepare a place for you, I will come again and will receive you home to myself, so that where I am you also may be.

[[v43-14-4]]

^<<v43-14-4,4>>^ And where I am going, you know the way.”

[[v43-14-5]]

^<<v43-14-5,5>>^ Thomas said to him: “Lord, we do not know where you are going. How can we know the way?”

[[v43-14-6]]

^<<v43-14-6,6>>^ Jesus said to him: “I am the way and the truth and the life. No one comes to the Father except through me.

[[v43-14-7]]

^<<v43-14-7,7>>^ If you men had known me, you would have known my Father also; from this moment on you know him and have seen him.”

[[v43-14-8]]

^<<v43-14-8,8>>^ Philip said to him: “Lord, show us the Father, and it is enough for us.”

[[v43-14-9]]

^<<v43-14-9,9>>^ Jesus said to him: “Even after I have been with you men for such a long time, Philip, have you not come to know me? Whoever has seen me has seen the Father also. How is it you say, ‘Show us the Father’?

[[v43-14-10]]

^<<v43-14-10,10>>^ Do you not believe that I am in union with the Father and the Father is in union with me? The things I say to you I do not speak of my own originality, but the Father who remains in union with me is doing his works.

[[v43-14-11]]

^<<v43-14-11,11>>^ Believe me that I am in union with the Father and the Father is in union with me; otherwise, believe because of the works themselves.

[[v43-14-12]]

^<<v43-14-12,12>>^ Most truly I say to you, whoever exercises faith in me will also do the works that I do; and he will do works greater than these, because I am going my way to the Father.

[[v43-14-13]]

^<<v43-14-13,13>>^ Also, whatever you ask in my name, I will do this, so that the Father may be glorified in connection with the Son.

[[v43-14-14]]

^<<v43-14-14,14>>^ If you ask anything in my name, I will do it.

[[v43-14-15]]

^<<v43-14-15,15>>^ “If you love me, you will observe my commandments.

[[v43-14-16]]

^<<v43-14-16,16>>^ And I will ask the Father and he will give you another helper^&#42;1^ to be with you forever,

[NOTE]
====
. Or “comforter.”
====

[[v43-14-17]]

^<<v43-14-17,17>>^ the spirit of the truth, which the world cannot receive, because it neither sees it nor knows it. You know it, because it remains with you and is in you.

[[v43-14-18]]

^<<v43-14-18,18>>^ I will not leave you bereaved.^&#42;1^ I am coming to you.

[NOTE]
====
. Or “as orphans.”
====

[[v43-14-19]]

^<<v43-14-19,19>>^ In a little while the world will see me no more, but you will see me, because I live and you will live.

[[v43-14-20]]

^<<v43-14-20,20>>^ In that day you will know that I am in union with my Father and you are in union with me and I am in union with you.

[[v43-14-21]]

^<<v43-14-21,21>>^ Whoever has my commandments and observes them is the one who loves me. In turn, whoever loves me will be loved by my Father, and I will love him and will clearly show myself to him.”

[[v43-14-22]]

^<<v43-14-22,22>>^ Judas, not Is·carʹi·ot, said to him: “Lord, what has happened that you intend to show yourself clearly to us and not to the world?”

[[v43-14-23]]

^<<v43-14-23,23>>^ In answer Jesus said to him: “If anyone loves me, he will observe my word, and my Father will love him, and we will come to him and make our dwelling^&#42;1^ with him.

[NOTE]
====
. Or “abode.”
====

[[v43-14-24]]

^<<v43-14-24,24>>^ Whoever does not love me does not observe my words. The word that you are hearing is not mine, but belongs to the Father who sent me.

[[v43-14-25]]

^<<v43-14-25,25>>^ “I have spoken these things to you while I am still with you.

[[v43-14-26]]

^<<v43-14-26,26>>^ But the helper, the holy spirit, which the Father will send in my name, that one will teach you all things and bring back to your minds all the things I told you.

[[v43-14-27]]

^<<v43-14-27,27>>^ I leave you peace; I give you my peace. I do not give it to you the way that the world gives it. Do not let your hearts be troubled nor let them shrink out of fear.

[[v43-14-28]]

^<<v43-14-28,28>>^ You heard that I said to you, ‘I am going away and I am coming back to you.’ If you loved me, you would rejoice that I am going to the Father, for the Father is greater than I am.

[[v43-14-29]]

^<<v43-14-29,29>>^ So now I have told you before it occurs, so that you may believe when it does occur.

[[v43-14-30]]

^<<v43-14-30,30>>^ I will not speak with you much more, for the ruler of the world is coming, and he has no hold on me.^&#42;1^

[NOTE]
====
. Or “has no power over me.”
====

[[v43-14-31]]

^<<v43-14-31,31>>^ But for the world to know that I love the Father, I am doing just as the Father has commanded me to do. Get up, let us go from here.

'''

xref:043-john/043-john-013.adoc#v43-13-0[&#60; Capítulo Anterior] | <<v43-14-0,Topo>> | xref:043-john/043-john-015.adoc#v43-15-0[Próximo Capítulo &#62;]