include::./index.adoc[]

[[v43-3-0]]
=== According to John, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-3-1]]

^<<v43-3-1,1>>^ There was a man of the Pharisees named Nic·o·deʹmus, a ruler of the Jews.

[[v43-3-2]]

^<<v43-3-2,2>>^ This one came to him in the night and said to him: “Rabbi, we know that you have come from God as a teacher, for no one can perform these signs that you perform unless God is with him.”

[[v43-3-3]]

^<<v43-3-3,3>>^ In response Jesus said to him: “Most truly I say to you, unless anyone is born again,^&#42;1^ he cannot see the Kingdom of God.”

[NOTE]
====
. Or possibly, “born from above.”
====

[[v43-3-4]]

^<<v43-3-4,4>>^ Nic·o·deʹmus said to him: “How can a man be born when he is old? He cannot enter into the womb of his mother a second time and be born, can he?”

[[v43-3-5]]

^<<v43-3-5,5>>^ Jesus answered: “Most truly I say to you, unless anyone is born from water and spirit, he cannot enter into the Kingdom of God.

[[v43-3-6]]

^<<v43-3-6,6>>^ What has been born from the flesh is flesh, and what has been born from the spirit is spirit.

[[v43-3-7]]

^<<v43-3-7,7>>^ Do not be amazed because I told you: You people must be born again.

[[v43-3-8]]

^<<v43-3-8,8>>^ The wind blows where it wants to, and you hear the sound of it, but you do not know where it comes from and where it is going. So it is with everyone who has been born from the spirit.”

[[v43-3-9]]

^<<v43-3-9,9>>^ In answer Nic·o·deʹmus said to him: “How can these things be?”

[[v43-3-10]]

^<<v43-3-10,10>>^ Jesus replied: “Are you a teacher of Israel and yet do not know these things?

[[v43-3-11]]

^<<v43-3-11,11>>^ Most truly I say to you, what we know we speak, and what we have seen we bear witness to, but you do not receive the witness we give.

[[v43-3-12]]

^<<v43-3-12,12>>^ If I have told you earthly things and you still do not believe, how will you believe if I tell you heavenly things?

[[v43-3-13]]

^<<v43-3-13,13>>^ Moreover, no man has ascended into heaven but the one who descended from heaven, the Son of man.

[[v43-3-14]]

^<<v43-3-14,14>>^ And just as Moses lifted up the serpent in the wilderness, so the Son of man must be lifted up,

[[v43-3-15]]

^<<v43-3-15,15>>^ so that everyone believing in him may have everlasting life.

[[v43-3-16]]

^<<v43-3-16,16>>^ “For God loved the world so much that he gave his only-begotten Son, so that everyone exercising faith in him might not be destroyed but have everlasting life.

[[v43-3-17]]

^<<v43-3-17,17>>^ For God did not send his Son into the world for him to judge the world, but for the world to be saved through him.

[[v43-3-18]]

^<<v43-3-18,18>>^ Whoever exercises faith in him is not to be judged. Whoever does not exercise faith has been judged already, because he has not exercised faith in the name of the only-begotten Son of God.

[[v43-3-19]]

^<<v43-3-19,19>>^ Now this is the basis for judgment: that the light has come into the world, but men have loved the darkness rather than the light, for their works were wicked.

[[v43-3-20]]

^<<v43-3-20,20>>^ For whoever practices vile things hates the light and does not come to the light, so that his works may not be reproved.^&#42;1^

[NOTE]
====
. Or “exposed.”
====

[[v43-3-21]]

^<<v43-3-21,21>>^ But whoever does what is true comes to the light, so that his works may be made manifest as having been done in harmony with God.”

[[v43-3-22]]

^<<v43-3-22,22>>^ After this Jesus and his disciples went into the Ju·deʹan countryside, and there he spent some time with them and was baptizing.

[[v43-3-23]]

^<<v43-3-23,23>>^ But John too was baptizing in Aeʹnon near Saʹlim, because there was a great quantity of water there, and people kept coming and were being baptized;

[[v43-3-24]]

^<<v43-3-24,24>>^ for John had not yet been thrown into prison.

[[v43-3-25]]

^<<v43-3-25,25>>^ Now the disciples of John had a dispute with a Jew concerning purification.

[[v43-3-26]]

^<<v43-3-26,26>>^ So they came to John and said to him: “Rabbi, the man who was with you across the Jordan, about whom you bore witness, see, this one is baptizing, and all are going to him.”

[[v43-3-27]]

^<<v43-3-27,27>>^ In answer John said: “A man cannot receive a single thing unless it has been given him from heaven.

[[v43-3-28]]

^<<v43-3-28,28>>^ You yourselves bear me witness that I said, ‘I am not the Christ, but I have been sent ahead of that one.’

[[v43-3-29]]

^<<v43-3-29,29>>^ Whoever has the bride is the bridegroom. But the friend of the bridegroom, when he stands and hears him, has a great deal of joy on account of the voice of the bridegroom. So my joy has been made complete.

[[v43-3-30]]

^<<v43-3-30,30>>^ That one must keep on increasing, but I must keep on decreasing.”

[[v43-3-31]]

^<<v43-3-31,31>>^ The one who comes from above is over all others. The one who is from the earth is from the earth and speaks of things of the earth. The one who comes from heaven is over all others.

[[v43-3-32]]

^<<v43-3-32,32>>^ He bears witness to what he has seen and heard, but no man accepts his witness.

[[v43-3-33]]

^<<v43-3-33,33>>^ Whoever has accepted his witness has put his seal to it^&#42;1^ that God is true.

[NOTE]
====
. Or “has confirmed.”
====

[[v43-3-34]]

^<<v43-3-34,34>>^ For the one whom God sent speaks the sayings of God, for He does not give the spirit sparingly.^&#42;1^

[NOTE]
====
. Or “by measure.”
====

[[v43-3-35]]

^<<v43-3-35,35>>^ The Father loves the Son and has given all things into his hand.

[[v43-3-36]]

^<<v43-3-36,36>>^ The one who exercises faith in the Son has everlasting life; the one who disobeys the Son will not see life, but the wrath of God remains upon him.

'''

xref:043-john/043-john-002.adoc#v43-2-0[&#60; Capítulo Anterior] | <<v43-3-0,Topo>> | xref:043-john/043-john-004.adoc#v43-4-0[Próximo Capítulo &#62;]