include::./index.adoc[]

[[v43-17-0]]
=== According to John, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-17-1]]

^<<v43-17-1,1>>^ Jesus spoke these things, and raising his eyes to heaven, he said: “Father, the hour has come. Glorify your son so that your son may glorify you,

[[v43-17-2]]

^<<v43-17-2,2>>^ just as you have given him authority over all flesh,^&#42;1^ so that he may give everlasting life to all those whom you have given to him.

[NOTE]
====
. Or “mankind; people.”
====

[[v43-17-3]]

^<<v43-17-3,3>>^ This means everlasting life, their coming to know you,^&#42;1^ the only true God, and the one whom you sent, Jesus Christ.

[NOTE]
====
. Or “their taking in knowledge of you.”
====

[[v43-17-4]]

^<<v43-17-4,4>>^ I have glorified you on the earth, having finished the work you have given me to do.

[[v43-17-5]]

^<<v43-17-5,5>>^ So now, Father, glorify me at your side with the glory that I had alongside you before the world was.

[[v43-17-6]]

^<<v43-17-6,6>>^ “I have made your name manifest^&#42;1^ to the men whom you gave me out of the world. They were yours, and you gave them to me, and they have observed^&#42;2^ your word.

[NOTE]
====
. Or “known.”
. Or “obeyed.”
====

[[v43-17-7]]

^<<v43-17-7,7>>^ Now they have come to know that all the things you gave me are from you;

[[v43-17-8]]

^<<v43-17-8,8>>^ because I have given them the sayings that you gave me, and they have accepted them and have certainly come to know that I came as your representative, and they have believed that you sent me.

[[v43-17-9]]

^<<v43-17-9,9>>^ I make request concerning them; I make request, not concerning the world, but concerning those whom you have given me, because they are yours;

[[v43-17-10]]

^<<v43-17-10,10>>^ and all my things are yours and yours are mine, and I have been glorified among them.

[[v43-17-11]]

^<<v43-17-11,11>>^ “I am no longer in the world, but they are in the world, and I am coming to you. Holy Father, watch over them on account of your own name, which you have given me, so that they may be one^&#42;1^ just as we are one.^&#42;2^

[NOTE]
====
. Or “at unity.”
. Or “at unity.”
====

[[v43-17-12]]

^<<v43-17-12,12>>^ When I was with them, I used to watch over them on account of your own name, which you have given me; and I have protected them, and not one of them is destroyed except the son of destruction, so that the scripture might be fulfilled.

[[v43-17-13]]

^<<v43-17-13,13>>^ But now I am coming to you, and I am saying these things in the world, so that they may have my joy made complete in themselves.

[[v43-17-14]]

^<<v43-17-14,14>>^ I have given your word to them, but the world has hated them, because they are no part of the world, just as I am no part of the world.

[[v43-17-15]]

^<<v43-17-15,15>>^ “I do not request that you take them out of the world, but that you watch over them because of the wicked one.

[[v43-17-16]]

^<<v43-17-16,16>>^ They are no part of the world, just as I am no part of the world.

[[v43-17-17]]

^<<v43-17-17,17>>^ Sanctify them^&#42;1^ by means of the truth; your word is truth.

[NOTE]
====
. Or “Set them apart; Make them holy.”
====

[[v43-17-18]]

^<<v43-17-18,18>>^ Just as you sent me into the world, I also sent them into the world.

[[v43-17-19]]

^<<v43-17-19,19>>^ And I am sanctifying myself in their behalf, so that they also may be sanctified by means of truth.

[[v43-17-20]]

^<<v43-17-20,20>>^ “I make request, not concerning these only, but also concerning those putting faith in me through their word,

[[v43-17-21]]

^<<v43-17-21,21>>^ so that they may all be one, just as you, Father, are in union with me and I am in union with you, that they also may be in union with us, so that the world may believe that you sent me.

[[v43-17-22]]

^<<v43-17-22,22>>^ I have given them the glory that you have given me, in order that they may be one just as we are one.

[[v43-17-23]]

^<<v43-17-23,23>>^ I in union with them and you in union with me, in order that they may be perfected into one,^&#42;1^ so that the world may know that you sent me and that you loved them just as you loved me.

[NOTE]
====
. Or “be completely unified.”
====

[[v43-17-24]]

^<<v43-17-24,24>>^ Father, I want those whom you have given me to be with me where I am, in order that they may look upon my glory that you have given me, because you loved me before the founding of the world.

[[v43-17-25]]

^<<v43-17-25,25>>^ Righteous Father, the world has, indeed, not come to know you, but I know you, and these have come to know that you sent me.

[[v43-17-26]]

^<<v43-17-26,26>>^ I have made your name known to them and will make it known, so that the love with which you loved me may be in them and I in union with them.”

'''

xref:043-john/043-john-016.adoc#v43-16-0[&#60; Capítulo Anterior] | <<v43-17-0,Topo>> | xref:043-john/043-john-018.adoc#v43-18-0[Próximo Capítulo &#62;]