include::./index.adoc[]

[[v43-12-0]]
=== According to John, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-12-1]]

^<<v43-12-1,1>>^ Six days before the Passover, Jesus arrived at Bethʹa·ny, where Lazʹa·rus was, whom Jesus had raised up from the dead.

[[v43-12-2]]

^<<v43-12-2,2>>^ So they spread an evening meal for him there, and Martha was serving them, but Lazʹa·rus was one of those dining^&#42;1^ with him.

[NOTE]
====
. Or “reclining at the table.”
====

[[v43-12-3]]

^<<v43-12-3,3>>^ Then Mary took a pound^&#42;1^ of perfumed oil, genuine nard, very costly, and she poured it on the feet of Jesus and wiped his feet dry with her hair. The house became filled with the scent of the perfumed oil.

[NOTE]
====
. That is, a Roman pound, about 327 g (11.5 oz). See App. B14.
====

[[v43-12-4]]

^<<v43-12-4,4>>^ But Judas Is·carʹi·ot, one of his disciples, who was about to betray him, said:

[[v43-12-5]]

^<<v43-12-5,5>>^ “Why was this perfumed oil not sold for 300 de·narʹi·i^&#42;1^ and given to the poor?”

[NOTE]
====
. See App. B14.
====

[[v43-12-6]]

^<<v43-12-6,6>>^ He said this, though, not because he was concerned about the poor, but because he was a thief and had the money box and used to steal the money put in it.

[[v43-12-7]]

^<<v43-12-7,7>>^ Then Jesus said: “Let her alone, so that she may keep this observance in view of the day of my burial.

[[v43-12-8]]

^<<v43-12-8,8>>^ For you always have the poor with you, but you will not always have me.”

[[v43-12-9]]

^<<v43-12-9,9>>^ Meanwhile, a large crowd of Jews got to know that he was there, and they came not only because of Jesus but also to see Lazʹa·rus, whom he had raised up from the dead.

[[v43-12-10]]

^<<v43-12-10,10>>^ The chief priests now conspired to kill Lazʹa·rus also,

[[v43-12-11]]

^<<v43-12-11,11>>^ since it was because of him that many of the Jews were going there and putting faith in Jesus.

[[v43-12-12]]

^<<v43-12-12,12>>^ The next day the large crowd that had come to the festival heard that Jesus was coming to Jerusalem.

[[v43-12-13]]

^<<v43-12-13,13>>^ So they took branches of palm trees and went out to meet him, and they began to shout: “Save, we pray you! Blessed is the one who comes in Jehovah’s^&#42;1^ name, the King of Israel!”

[NOTE]
====
. See App. A5.
====

[[v43-12-14]]

^<<v43-12-14,14>>^ When Jesus found a young donkey, he sat on it, just as it is written:

[[v43-12-15]]

^<<v43-12-15,15>>^ “Have no fear, daughter of Zion. Look! Your king is coming, seated on a donkey’s colt.”

[[v43-12-16]]

^<<v43-12-16,16>>^ These things his disciples did not understand at first, but when Jesus was glorified, they recalled that these things were written about him and that they did these things to him.

[[v43-12-17]]

^<<v43-12-17,17>>^ Now the crowd that was with him when he called Lazʹa·rus out of the tomb^&#42;1^ and raised him up from the dead kept bearing witness.

[NOTE]
====
. Or “memorial tomb.”
====

[[v43-12-18]]

^<<v43-12-18,18>>^ This is also why the crowd went to meet him, because they heard he had performed this sign.

[[v43-12-19]]

^<<v43-12-19,19>>^ So the Pharisees said among themselves: “You see that you are not getting anywhere. Look! The whole world has gone after him.”

[[v43-12-20]]

^<<v43-12-20,20>>^ Now there were some Greeks among those who had come to worship at the festival.

[[v43-12-21]]

^<<v43-12-21,21>>^ So these approached Philip, who was from Beth·saʹi·da of Galʹi·lee, and they began to request him, saying: “Sir, we want to see Jesus.”

[[v43-12-22]]

^<<v43-12-22,22>>^ Philip came and told Andrew. Andrew and Philip came and told Jesus.

[[v43-12-23]]

^<<v43-12-23,23>>^ But Jesus answered them: “The hour has come for the Son of man to be glorified.

[[v43-12-24]]

^<<v43-12-24,24>>^ Most truly I say to you, unless a grain of wheat falls to the ground and dies, it remains just one grain; but if it dies, it then bears much fruit.

[[v43-12-25]]

^<<v43-12-25,25>>^ Whoever is fond of his life^&#42;1^ destroys it, but whoever hates his life^&#42;2^ in this world will safeguard it for everlasting life.

[NOTE]
====
. Or “soul.”
. Or “soul.”
====

[[v43-12-26]]

^<<v43-12-26,26>>^ If anyone would minister to me, let him follow me, and where I am, there my minister will be also. If anyone would minister to me, the Father will honor him.

[[v43-12-27]]

^<<v43-12-27,27>>^ Now I am^&#42;1^ troubled, and what should I say? Father, save me out of this hour. Nevertheless, this is why I have come to this hour.

[NOTE]
====
. Or “my soul is.”
====

[[v43-12-28]]

^<<v43-12-28,28>>^ Father, glorify your name.” Then a voice came out of heaven: “I have glorified it and will glorify it again.”

[[v43-12-29]]

^<<v43-12-29,29>>^ The crowd that was standing there heard it and began to say that it had thundered. Others said: “An angel has spoken to him.”

[[v43-12-30]]

^<<v43-12-30,30>>^ Jesus answered: “This voice has occurred, not for my sake, but for your sakes.

[[v43-12-31]]

^<<v43-12-31,31>>^ Now there is a judging of this world; now the ruler of this world will be cast out.

[[v43-12-32]]

^<<v43-12-32,32>>^ And yet I, if I am lifted up from the earth, will draw all sorts of men to myself.”

[[v43-12-33]]

^<<v43-12-33,33>>^ This he was really saying to indicate what sort of death he was about to die.

[[v43-12-34]]

^<<v43-12-34,34>>^ Then the crowd answered him: “We heard from the Law that the Christ remains forever. How can you say that the Son of man must be lifted up? Who is this Son of man?”

[[v43-12-35]]

^<<v43-12-35,35>>^ So Jesus said to them: “The light will be among you a little while longer. Walk while you still have the light, so that darkness does not overpower you; whoever walks in the darkness does not know where he is going.

[[v43-12-36]]

^<<v43-12-36,36>>^ While you have the light, exercise faith in the light, so that you may become sons of light.”
Jesus said these things and went off and hid from them.

[[v43-12-37]]

^<<v43-12-37,37>>^ Although he had performed so many signs before them, they were not putting faith in him,

[[v43-12-38]]

^<<v43-12-38,38>>^ so that the word of Isaiah the prophet might be fulfilled, who said: “Jehovah,^&#42;1^ who has put faith in the thing heard from us?^&#42;2^ And as for the arm of Jehovah,^&#42;3^ to whom has it been revealed?”

[NOTE]
====
. See App. A5.
. Or “in our report?”
. See App. A5.
====

[[v43-12-39]]

^<<v43-12-39,39>>^ The reason why they were not able to believe is that again Isaiah said:

[[v43-12-40]]

^<<v43-12-40,40>>^ “He has blinded their eyes and has made their hearts hard, so that they would not see with their eyes and understand with their hearts and turn around and I heal them.”

[[v43-12-41]]

^<<v43-12-41,41>>^ Isaiah said these things because he saw his glory, and he spoke about him.

[[v43-12-42]]

^<<v43-12-42,42>>^ All the same, many even of the rulers actually put faith in him, but they would not acknowledge him because of the Pharisees, so that they would not be expelled from the synagogue;

[[v43-12-43]]

^<<v43-12-43,43>>^ for they loved the glory of men even more than the glory of God.

[[v43-12-44]]

^<<v43-12-44,44>>^ However, Jesus called out and said: “Whoever puts faith in me puts faith not only in me but also in him who sent me;

[[v43-12-45]]

^<<v43-12-45,45>>^ and whoever sees me sees also the One who sent me.

[[v43-12-46]]

^<<v43-12-46,46>>^ I have come as a light into the world, so that everyone putting faith in me may not remain in the darkness.

[[v43-12-47]]

^<<v43-12-47,47>>^ But if anyone hears my sayings and does not keep them, I do not judge him; for I came, not to judge the world, but to save the world.

[[v43-12-48]]

^<<v43-12-48,48>>^ Whoever disregards me and does not receive my sayings has one to judge him. The word that I have spoken is what will judge him on the last day.

[[v43-12-49]]

^<<v43-12-49,49>>^ For I have not spoken of my own initiative, but the Father who sent me has himself given me a commandment about what to say and what to speak.

[[v43-12-50]]

^<<v43-12-50,50>>^ And I know that his commandment means everlasting life. So whatever I speak, I speak just as the Father has told me.”

'''

xref:043-john/043-john-011.adoc#v43-11-0[&#60; Capítulo Anterior] | <<v43-12-0,Topo>> | xref:043-john/043-john-013.adoc#v43-13-0[Próximo Capítulo &#62;]