include::./index.adoc[]

[[v43-4-0]]
=== According to John, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-4-1]]

^<<v43-4-1,1>>^ When the Lord became aware that the Pharisees had heard that Jesus was making and baptizing more disciples than John—

[[v43-4-2]]

^<<v43-4-2,2>>^ although Jesus himself did no baptizing but his disciples did—

[[v43-4-3]]

^<<v43-4-3,3>>^ he left Ju·deʹa and departed again for Galʹi·lee.

[[v43-4-4]]

^<<v43-4-4,4>>^ But it was necessary for him to go through Sa·marʹi·a.

[[v43-4-5]]

^<<v43-4-5,5>>^ So he came to a city of Sa·marʹi·a called Syʹchar, near the field that Jacob had given to his son Joseph.

[[v43-4-6]]

^<<v43-4-6,6>>^ In fact, Jacob’s well was there. Now Jesus, tired out as he was from the journey, was sitting at the well.^&#42;1^ It was about the sixth hour.^&#42;2^

[NOTE]
====
. Or “fountain; spring.”
. That is, about 12:00 noon.
====

[[v43-4-7]]

^<<v43-4-7,7>>^ A woman of Sa·marʹi·a came to draw water. Jesus said to her: “Give me a drink.”

[[v43-4-8]]

^<<v43-4-8,8>>^ (For his disciples had gone off into the city to buy food.)

[[v43-4-9]]

^<<v43-4-9,9>>^ So the Sa·marʹi·tan woman said to him: “How is it that you, despite being a Jew, ask me for a drink even though I am a Sa·marʹi·tan woman?” (For Jews have no dealings with Sa·marʹi·tans.)

[[v43-4-10]]

^<<v43-4-10,10>>^ In answer Jesus said to her: “If you had known of the free gift of God and who it is who says to you, ‘Give me a drink,’ you would have asked him, and he would have given you living water.”

[[v43-4-11]]

^<<v43-4-11,11>>^ She said to him: “Sir, you do not even have a bucket for drawing water, and the well is deep. From what source, then, do you have this living water?

[[v43-4-12]]

^<<v43-4-12,12>>^ You are not greater than our forefather Jacob, who gave us the well and who together with his sons and his cattle drank out of it, are you?”

[[v43-4-13]]

^<<v43-4-13,13>>^ In answer Jesus said to her: “Everyone drinking from this water will get thirsty again.

[[v43-4-14]]

^<<v43-4-14,14>>^ Whoever drinks from the water that I will give him will never get thirsty at all, but the water that I will give him will become in him a spring of water bubbling up to impart everlasting life.”

[[v43-4-15]]

^<<v43-4-15,15>>^ The woman said to him: “Sir, give me this water, so that I may neither thirst nor keep coming over to this place to draw water.”

[[v43-4-16]]

^<<v43-4-16,16>>^ He said to her: “Go, call your husband and come to this place.”

[[v43-4-17]]

^<<v43-4-17,17>>^ The woman replied: “I do not have a husband.” Jesus said to her: “You are right in saying, ‘I do not have a husband.’

[[v43-4-18]]

^<<v43-4-18,18>>^ For you have had five husbands, and the man you now have is not your husband. This you have said truthfully.”

[[v43-4-19]]

^<<v43-4-19,19>>^ The woman said to him: “Sir, I see that you are a prophet.

[[v43-4-20]]

^<<v43-4-20,20>>^ Our forefathers worshipped on this mountain, but you people say that in Jerusalem is the place where people must worship.”

[[v43-4-21]]

^<<v43-4-21,21>>^ Jesus said to her: “Believe me, woman, the hour is coming when neither on this mountain nor in Jerusalem will you worship the Father.

[[v43-4-22]]

^<<v43-4-22,22>>^ You worship what you do not know; we worship what we know, because salvation begins with the Jews.

[[v43-4-23]]

^<<v43-4-23,23>>^ Nevertheless, the hour is coming, and it is now, when the true worshippers will worship the Father with spirit and truth, for indeed, the Father is looking for ones like these to worship him.

[[v43-4-24]]

^<<v43-4-24,24>>^ God is a Spirit, and those worshipping him must worship with spirit and truth.”

[[v43-4-25]]

^<<v43-4-25,25>>^ The woman said to him: “I know that Mes·siʹah is coming, who is called Christ. Whenever that one comes, he will declare all things to us openly.”

[[v43-4-26]]

^<<v43-4-26,26>>^ Jesus said to her: “I am he, the one speaking to you.”

[[v43-4-27]]

^<<v43-4-27,27>>^ Just then his disciples arrived, and they were surprised because he was speaking with a woman. Of course, no one said: “What are you looking for?” or “Why are you talking to her?”

[[v43-4-28]]

^<<v43-4-28,28>>^ So the woman left her water jar and went off into the city and told the people:

[[v43-4-29]]

^<<v43-4-29,29>>^ “Come and see a man who told me everything I did. Could this not perhaps be the Christ?”

[[v43-4-30]]

^<<v43-4-30,30>>^ They left the city and began coming to him.

[[v43-4-31]]

^<<v43-4-31,31>>^ Meanwhile, the disciples were urging him: “Rabbi, eat.”

[[v43-4-32]]

^<<v43-4-32,32>>^ But he said to them: “I have food to eat that you do not know about.”

[[v43-4-33]]

^<<v43-4-33,33>>^ So the disciples said to one another: “No one brought him anything to eat, did he?”

[[v43-4-34]]

^<<v43-4-34,34>>^ Jesus said to them: “My food is to do the will of him who sent me and to finish his work.

[[v43-4-35]]

^<<v43-4-35,35>>^ Do you not say that there are yet four months before the harvest comes? Look! I say to you: Lift up your eyes and view the fields, that they are white for harvesting. Already

[[v43-4-36]]

^<<v43-4-36,36>>^ the reaper is receiving wages and gathering fruit for everlasting life, so that the sower and the reaper may rejoice together.

[[v43-4-37]]

^<<v43-4-37,37>>^ For in this respect the saying is true: One is the sower and another the reaper.

[[v43-4-38]]

^<<v43-4-38,38>>^ I sent you to reap what you did not labor on. Others have labored, and you have entered into the benefit of their labor.”

[[v43-4-39]]

^<<v43-4-39,39>>^ Many of the Sa·marʹi·tans from that city put faith in him because of the word of the woman who bore witness, saying: “He told me all the things I did.”

[[v43-4-40]]

^<<v43-4-40,40>>^ So when the Sa·marʹi·tans came to him, they asked him to stay with them, and he stayed there two days.

[[v43-4-41]]

^<<v43-4-41,41>>^ As a result, many more believed because of what he said,

[[v43-4-42]]

^<<v43-4-42,42>>^ and they said to the woman: “We no longer believe just because of what you said; for we have heard for ourselves, and we know that this man really is the savior of the world.”

[[v43-4-43]]

^<<v43-4-43,43>>^ After the two days, he left there for Galʹi·lee.

[[v43-4-44]]

^<<v43-4-44,44>>^ Jesus himself, however, bore witness that a prophet has no honor in his own homeland.

[[v43-4-45]]

^<<v43-4-45,45>>^ So when he arrived in Galʹi·lee, the Gal·i·leʹans welcomed him, because they had seen all the things he did in Jerusalem at the festival, for they too had gone to the festival.

[[v43-4-46]]

^<<v43-4-46,46>>^ Then he came again to Caʹna of Galʹi·lee, where he had turned the water into wine. Now there was a royal official whose son was sick in Ca·perʹna·um.

[[v43-4-47]]

^<<v43-4-47,47>>^ When this man heard that Jesus had come out of Ju·deʹa into Galʹi·lee, he went to him and asked him to come down and heal his son, for he was at the point of dying.

[[v43-4-48]]

^<<v43-4-48,48>>^ But Jesus said to him: “Unless you people see signs and wonders, you will never believe.”

[[v43-4-49]]

^<<v43-4-49,49>>^ The royal official said to him: “Lord, come down before my young child dies.”

[[v43-4-50]]

^<<v43-4-50,50>>^ Jesus said to him: “Go your way; your son lives.” The man believed the word that Jesus spoke to him, and he left.

[[v43-4-51]]

^<<v43-4-51,51>>^ But while he was on his way down, his slaves met him to say that his boy was alive.^&#42;1^

[NOTE]
====
. Or “was recovering.”
====

[[v43-4-52]]

^<<v43-4-52,52>>^ So he asked them at what hour he got better. They replied to him: “The fever left him yesterday at the seventh hour.”^&#42;1^

[NOTE]
====
. That is, about 1:00 p.m.
====

[[v43-4-53]]

^<<v43-4-53,53>>^ The father then knew that it was in the very hour that Jesus had said to him: “Your son lives.” So he and his whole household believed.

[[v43-4-54]]

^<<v43-4-54,54>>^ This was the second sign Jesus performed when he came from Ju·deʹa into Galʹi·lee.

'''

xref:043-john/043-john-003.adoc#v43-3-0[&#60; Capítulo Anterior] | <<v43-4-0,Topo>> | xref:043-john/043-john-005.adoc#v43-5-0[Próximo Capítulo &#62;]