include::./index.adoc[]

[[v43-15-0]]
=== According to John, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-15-1]]

^<<v43-15-1,1>>^ “I am the true vine, and my Father is the cultivator.

[[v43-15-2]]

^<<v43-15-2,2>>^ He takes away every branch in me not bearing fruit, and he cleans every one bearing fruit, so that it may bear more fruit.

[[v43-15-3]]

^<<v43-15-3,3>>^ You are already clean because of the word that I have spoken to you.

[[v43-15-4]]

^<<v43-15-4,4>>^ Remain in union with me, and I will remain in union with you. Just as the branch cannot bear fruit by itself unless it remains in the vine, neither can you unless you remain in union with me.

[[v43-15-5]]

^<<v43-15-5,5>>^ I am the vine; you are the branches. Whoever remains in union with me and I in union with him, this one bears much fruit; for apart from me you can do nothing at all.

[[v43-15-6]]

^<<v43-15-6,6>>^ If anyone does not remain in union with me, he is thrown out like a branch and dries up. And men gather those branches and throw them into the fire, and they are burned.

[[v43-15-7]]

^<<v43-15-7,7>>^ If you remain in union with me and my sayings remain in you, ask whatever you wish and it will take place for you.

[[v43-15-8]]

^<<v43-15-8,8>>^ My Father is glorified in this, that you keep bearing much fruit and prove yourselves my disciples.

[[v43-15-9]]

^<<v43-15-9,9>>^ Just as the Father has loved me, so I have loved you; remain in my love.

[[v43-15-10]]

^<<v43-15-10,10>>^ If you observe my commandments, you will remain in my love, just as I have observed the commandments of the Father and remain in his love.

[[v43-15-11]]

^<<v43-15-11,11>>^ “These things I have spoken to you, so that my joy may be in you and your joy may be made full.

[[v43-15-12]]

^<<v43-15-12,12>>^ This is my commandment, that you love one another just as I have loved you.

[[v43-15-13]]

^<<v43-15-13,13>>^ No one has love greater than this, that someone should surrender his life^&#42;1^ in behalf of his friends.

[NOTE]
====
. Or “soul.”
====

[[v43-15-14]]

^<<v43-15-14,14>>^ You are my friends if you do what I am commanding you.

[[v43-15-15]]

^<<v43-15-15,15>>^ I no longer call you slaves, because a slave does not know what his master does. But I have called you friends, because I have made known to you all the things I have heard from my Father.

[[v43-15-16]]

^<<v43-15-16,16>>^ You did not choose me, but I chose you, and I appointed you to go and keep bearing fruit and that your fruit should remain, so that no matter what you ask the Father in my name, he may give it to you.

[[v43-15-17]]

^<<v43-15-17,17>>^ “These things I command you, that you love one another.

[[v43-15-18]]

^<<v43-15-18,18>>^ If the world hates you, you know that it has hated me before it hated you.

[[v43-15-19]]

^<<v43-15-19,19>>^ If you were part of the world, the world would be fond of what is its own. Now because you are no part of the world, but I have chosen you out of the world, for this reason the world hates you.

[[v43-15-20]]

^<<v43-15-20,20>>^ Keep in mind the word I said to you: A slave is not greater than his master. If they have persecuted me, they will also persecute you; if they have observed my word, they will also observe yours.

[[v43-15-21]]

^<<v43-15-21,21>>^ But they will do all these things against you on account of my name, because they do not know the One who sent me.

[[v43-15-22]]

^<<v43-15-22,22>>^ If I had not come and spoken to them, they would have no sin. But now they have no excuse for their sin.

[[v43-15-23]]

^<<v43-15-23,23>>^ Whoever hates me also hates my Father.

[[v43-15-24]]

^<<v43-15-24,24>>^ If I had not done among them the works that no one else did, they would have no sin; but now they have both seen me and hated me as well as my Father.

[[v43-15-25]]

^<<v43-15-25,25>>^ But this happened in order to fulfill the word written in their Law: ‘They hated me without cause.’

[[v43-15-26]]

^<<v43-15-26,26>>^ When the helper comes that I will send you from the Father, the spirit of the truth, which comes from the Father, that one will bear witness about me;

[[v43-15-27]]

^<<v43-15-27,27>>^ and you, in turn, are to bear witness, because you have been with me from the beginning.

'''

xref:043-john/043-john-014.adoc#v43-14-0[&#60; Capítulo Anterior] | <<v43-15-0,Topo>> | xref:043-john/043-john-016.adoc#v43-16-0[Próximo Capítulo &#62;]