include::./index.adoc[]

[[v43-21-0]]
=== According to John, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-21-1]]

^<<v43-21-1,1>>^ After this Jesus manifested himself^&#42;1^ again to the disciples, at the Sea of Ti·beʹri·as. He made the manifestation in this way.

[NOTE]
====
. Or “appeared.”
====

[[v43-21-2]]

^<<v43-21-2,2>>^ There were together Simon Peter, Thomas (who was called the Twin), Na·thanʹa·el from Caʹna of Galʹi·lee, the sons of Zebʹe·dee, and two others of his disciples.

[[v43-21-3]]

^<<v43-21-3,3>>^ Simon Peter said to them: “I am going fishing.” They said to him: “We are coming with you.” They went out and got aboard the boat, but during that night they caught nothing.

[[v43-21-4]]

^<<v43-21-4,4>>^ However, just as day was breaking, Jesus stood on the beach, but the disciples did not realize that it was Jesus.

[[v43-21-5]]

^<<v43-21-5,5>>^ Then Jesus said to them: “Children, you do not have anything^&#42;1^ to eat, do you?” They answered: “No!”

[NOTE]
====
. Or “any fish.”
====

[[v43-21-6]]

^<<v43-21-6,6>>^ He said to them: “Cast the net on the right side of the boat and you will find some.” So they cast it, but they were not able to haul it in because of the large number of fish.

[[v43-21-7]]

^<<v43-21-7,7>>^ Then the disciple whom Jesus loved said to Peter: “It is the Lord!” Now Simon Peter, on hearing that it was the Lord, put on^&#42;1^ his outer garment, for he was naked,^&#42;2^ and plunged into the sea.

[NOTE]
====
. Or “girded about himself.”
. Or “lightly clad.”
====

[[v43-21-8]]

^<<v43-21-8,8>>^ But the other disciples came in the small boat, dragging the net full of fish, for they were not a long way from land, only about 300 feet^&#42;1^ away.

[NOTE]
====
. About 90 m. Lit., “about 200 cubits.” See App. B14.
====

[[v43-21-9]]

^<<v43-21-9,9>>^ When they came ashore, they saw there a charcoal fire with fish lying on it and bread.

[[v43-21-10]]

^<<v43-21-10,10>>^ Jesus said to them: “Bring some of the fish you just now caught.”

[[v43-21-11]]

^<<v43-21-11,11>>^ So Simon Peter went on board and hauled the net ashore full of big fish, 153 of them. And though there were so many, the net did not burst.

[[v43-21-12]]

^<<v43-21-12,12>>^ Jesus said to them: “Come, have your breakfast.” Not one of the disciples had the courage to ask him: “Who are you?” because they knew it was the Lord.

[[v43-21-13]]

^<<v43-21-13,13>>^ Jesus came and took the bread and gave it to them, and the same with the fish.

[[v43-21-14]]

^<<v43-21-14,14>>^ This was now the third time that Jesus appeared to the disciples after being raised up from the dead.

[[v43-21-15]]

^<<v43-21-15,15>>^ When they had finished breakfast, Jesus said to Simon Peter: “Simon son of John, do you love me more than these?” He replied to him: “Yes, Lord, you know I have affection for you.” He said to him: “Feed my lambs.”

[[v43-21-16]]

^<<v43-21-16,16>>^ Again he said to him a second time: “Simon son of John, do you love me?” He replied: “Yes, Lord, you know I have affection for you.” He said to him: “Shepherd my little sheep.”

[[v43-21-17]]

^<<v43-21-17,17>>^ He said to him a third time: “Simon son of John, do you have affection for me?” Peter became grieved that he asked him the third time: “Do you have affection for me?” So he said to him: “Lord, you are aware of all things; you know that I have affection for you.” Jesus said to him: “Feed my little sheep.

[[v43-21-18]]

^<<v43-21-18,18>>^ Most truly I say to you, when you were younger, you used to clothe yourself and walk about where you wanted. But when you grow old, you will stretch out your hands and another man will clothe you and carry you where you do not wish.”

[[v43-21-19]]

^<<v43-21-19,19>>^ He said this to indicate by what sort of death he would glorify God. After he said this, he said to him: “Continue following me.”

[[v43-21-20]]

^<<v43-21-20,20>>^ Peter turned around and saw the disciple whom Jesus loved following, the one who at the evening meal had also leaned back on his chest and said: “Lord, who is the one betraying you?”

[[v43-21-21]]

^<<v43-21-21,21>>^ So when he caught sight of him, Peter said to Jesus: “Lord, what about this man?”

[[v43-21-22]]

^<<v43-21-22,22>>^ Jesus said to him: “If it is my will for him to remain until I come, of what concern is that to you? You continue following me.”

[[v43-21-23]]

^<<v43-21-23,23>>^ So the saying went out among the brothers that this disciple would not die. However, Jesus did not say to him that he would not die, but he said: “If it is my will for him to remain until I come, of what concern is that to you?”

[[v43-21-24]]

^<<v43-21-24,24>>^ This is the disciple who gives this witness about these things and who wrote these things, and we know that his witness is true.

[[v43-21-25]]

^<<v43-21-25,25>>^ There are also, in fact, many other things that Jesus did, which if ever they were written in full detail, I suppose the world itself could not contain the scrolls written.

'''

xref:043-john/043-john-020.adoc#v43-20-0[&#60; Capítulo Anterior] | <<v43-21-0,Topo>> | xref:044-acts/044-acts-001.adoc#v44-1-0[Próximo Capítulo &#62;]