include::./index.adoc[]

[[v43-18-0]]
=== According to John, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-18-1]]

^<<v43-18-1,1>>^ After he said these things, Jesus went out with his disciples across the Kidʹron Valley^&#42;1^ to where there was a garden, and he and his disciples went into it.

[NOTE]
====
. Or “the winter torrent of Kidron.”
====

[[v43-18-2]]

^<<v43-18-2,2>>^ Now Judas, his betrayer, also knew the place, because Jesus had often met there with his disciples.

[[v43-18-3]]

^<<v43-18-3,3>>^ So Judas brought the detachment of soldiers and officers of the chief priests and of the Pharisees and came there with torches and lamps and weapons.

[[v43-18-4]]

^<<v43-18-4,4>>^ Then Jesus, knowing all the things that were going to happen to him, stepped forward and said to them: “Whom are you looking for?”

[[v43-18-5]]

^<<v43-18-5,5>>^ They answered him: “Jesus the Naz·a·reneʹ.” He said to them: “I am he.” Now Judas, his betrayer, was also standing with them.

[[v43-18-6]]

^<<v43-18-6,6>>^ However, when Jesus said to them, “I am he,” they drew back and fell to the ground.

[[v43-18-7]]

^<<v43-18-7,7>>^ So he asked them again: “Whom are you looking for?” They said: “Jesus the Naz·a·reneʹ.”

[[v43-18-8]]

^<<v43-18-8,8>>^ Jesus answered: “I told you that I am he. So if you are looking for me, let these men go.”

[[v43-18-9]]

^<<v43-18-9,9>>^ This was to fulfill what he had said: “Of those whom you have given me, I have not lost a single one.”

[[v43-18-10]]

^<<v43-18-10,10>>^ Then Simon Peter, who had a sword, drew it and struck the slave of the high priest, cutting off his right ear. The name of the slave was Malchus.

[[v43-18-11]]

^<<v43-18-11,11>>^ Jesus, however, said to Peter: “Put the sword into its sheath. Should I not drink the cup that the Father has given me?”

[[v43-18-12]]

^<<v43-18-12,12>>^ Then the soldiers and the military commander and the officers of the Jews seized^&#42;1^ Jesus and bound him.

[NOTE]
====
. Or “arrested.”
====

[[v43-18-13]]

^<<v43-18-13,13>>^ They led him first to Anʹnas, for he was the father-in-law of Caʹia·phas, who was high priest that year.

[[v43-18-14]]

^<<v43-18-14,14>>^ Caʹia·phas was, in fact, the one who had advised the Jews that it was to their benefit for one man to die in behalf of the people.

[[v43-18-15]]

^<<v43-18-15,15>>^ Now Simon Peter, as well as another disciple, was following Jesus. That disciple was known to the high priest, and he went with Jesus into the courtyard of the high priest,

[[v43-18-16]]

^<<v43-18-16,16>>^ but Peter was standing outside at the door.^&#42;1^ So the other disciple, who was known to the high priest, went out and spoke to the doorkeeper and brought Peter in.

[NOTE]
====
. Or “entrance.”
====

[[v43-18-17]]

^<<v43-18-17,17>>^ The servant girl who was the doorkeeper then said to Peter: “You are not also one of this man’s disciples, are you?” He said: “I am not.”

[[v43-18-18]]

^<<v43-18-18,18>>^ Now the slaves and the officers were standing around a charcoal fire they had made, because it was cold and they were warming themselves. Peter also was standing with them and warming himself.

[[v43-18-19]]

^<<v43-18-19,19>>^ So the chief priest questioned Jesus about his disciples and about his teaching.

[[v43-18-20]]

^<<v43-18-20,20>>^ Jesus answered him: “I have spoken to the world publicly. I always taught in a synagogue and in the temple, where all the Jews come together, and I said nothing in secret.

[[v43-18-21]]

^<<v43-18-21,21>>^ Why do you question me? Question those who have heard what I told them. See! These know what I said.”

[[v43-18-22]]

^<<v43-18-22,22>>^ After he said these things, one of the officers who was standing by gave Jesus a slap in the face and said: “Is that the way you answer the chief priest?”

[[v43-18-23]]

^<<v43-18-23,23>>^ Jesus answered him: “If I said something wrong, bear witness^&#42;1^ about the wrong; but if what I said was right, why do you hit me?”

[NOTE]
====
. Or “testify.”
====

[[v43-18-24]]

^<<v43-18-24,24>>^ Then Anʹnas sent him away bound to Caʹia·phas the high priest.

[[v43-18-25]]

^<<v43-18-25,25>>^ Now Simon Peter was standing there warming himself. Then they said to him: “You are not also one of his disciples, are you?” He denied it and said: “I am not.”

[[v43-18-26]]

^<<v43-18-26,26>>^ One of the slaves of the high priest, who was a relative of the man whose ear Peter had cut off, said: “I saw you in the garden with him, did I not?”

[[v43-18-27]]

^<<v43-18-27,27>>^ However, Peter denied it again, and immediately a rooster crowed.

[[v43-18-28]]

^<<v43-18-28,28>>^ Then they led Jesus from Caʹia·phas to the governor’s residence. It was now early in the morning. But they themselves did not enter into the governor’s residence, so that they would not get defiled but could eat the Passover.

[[v43-18-29]]

^<<v43-18-29,29>>^ So Pilate came outside to them and said: “What accusation do you bring against this man?”

[[v43-18-30]]

^<<v43-18-30,30>>^ They answered him: “If this man were not a wrongdoer,^&#42;1^ we would not have handed him over to you.”

[NOTE]
====
. Or “criminal.”
====

[[v43-18-31]]

^<<v43-18-31,31>>^ So Pilate said to them: “Take him yourselves and judge him according to your law.” The Jews said to him: “It is not lawful for us to kill anyone.”

[[v43-18-32]]

^<<v43-18-32,32>>^ This was to fulfill the word that Jesus had spoken to indicate what sort of death he was about to die.

[[v43-18-33]]

^<<v43-18-33,33>>^ So Pilate entered the governor’s residence again and called Jesus and said to him: “Are you the King of the Jews?”

[[v43-18-34]]

^<<v43-18-34,34>>^ Jesus answered: “Are you asking this of your own originality, or did others tell you about me?”

[[v43-18-35]]

^<<v43-18-35,35>>^ Pilate replied: “I am not a Jew, am I? Your own nation and the chief priests handed you over to me. What did you do?”

[[v43-18-36]]

^<<v43-18-36,36>>^ Jesus answered: “My Kingdom is no part of this world. If my Kingdom were part of this world, my attendants would have fought that I should not be handed over to the Jews. But as it is, my Kingdom is not from this source.”

[[v43-18-37]]

^<<v43-18-37,37>>^ So Pilate said to him: “Well, then, are you a king?” Jesus answered: “You yourself are saying that I am a king. For this I have been born, and for this I have come into the world, that I should bear witness to the truth. Everyone who is on the side of the truth listens to my voice.”

[[v43-18-38]]

^<<v43-18-38,38>>^ Pilate said to him: “What is truth?”
After saying this, he went out again to the Jews and said to them: “I find no fault in him.

[[v43-18-39]]

^<<v43-18-39,39>>^ Moreover, you have a custom that I should release a man to you at the Passover. So do you want me to release to you the King of the Jews?”

[[v43-18-40]]

^<<v43-18-40,40>>^ Again they shouted: “Not this man, but Bar·abʹbas!” Now Bar·abʹbas was a robber.

'''

xref:043-john/043-john-017.adoc#v43-17-0[&#60; Capítulo Anterior] | <<v43-18-0,Topo>> | xref:043-john/043-john-019.adoc#v43-19-0[Próximo Capítulo &#62;]