include::./index.adoc[]

[[v43-7-0]]
=== According to John, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-7-1]]

^<<v43-7-1,1>>^ After this Jesus continued traveling^&#42;1^ about in Galʹi·lee, for he did not want to do so in Ju·deʹa because the Jews were seeking to kill him.

[NOTE]
====
. Or “walking.”
====

[[v43-7-2]]

^<<v43-7-2,2>>^ However, the Jewish Festival of Tabernacles^&#42;1^ was near.

[NOTE]
====
. Or “Booths.”
====

[[v43-7-3]]

^<<v43-7-3,3>>^ So his brothers said to him: “Leave here and go into Ju·deʹa, so that your disciples may also see the works you are doing.

[[v43-7-4]]

^<<v43-7-4,4>>^ For no one does anything in secret when he seeks to be known publicly. If you are doing these things, show yourself to the world.”

[[v43-7-5]]

^<<v43-7-5,5>>^ His brothers were, in fact, not exercising faith in him.

[[v43-7-6]]

^<<v43-7-6,6>>^ So Jesus said to them: “My time has not yet arrived, but your time is always at hand.

[[v43-7-7]]

^<<v43-7-7,7>>^ The world has no reason to hate you, but it hates me, because I bear witness about it that its works are wicked.

[[v43-7-8]]

^<<v43-7-8,8>>^ You go up to the festival; I am not yet going up to this festival, because my time has not yet fully come.”

[[v43-7-9]]

^<<v43-7-9,9>>^ So after he told them these things, he remained in Galʹi·lee.

[[v43-7-10]]

^<<v43-7-10,10>>^ But when his brothers had gone up to the festival, then he also went up, not openly but in secret.

[[v43-7-11]]

^<<v43-7-11,11>>^ So the Jews began looking for him at the festival and saying: “Where is that man?”

[[v43-7-12]]

^<<v43-7-12,12>>^ And there was a lot of subdued talk about him among the crowds. Some would say: “He is a good man.” Others would say: “He is not. He misleads the crowd.”

[[v43-7-13]]

^<<v43-7-13,13>>^ Of course, no one would speak about him publicly because of fear of the Jews.

[[v43-7-14]]

^<<v43-7-14,14>>^ When the festival was half over, Jesus went up into the temple and began teaching.

[[v43-7-15]]

^<<v43-7-15,15>>^ And the Jews were astonished, saying: “How does this man have such a knowledge of the Scriptures^&#42;1^ when he has not studied at the schools?”^&#42;2^

[NOTE]
====
. Lit., “writings.”
. That is, the rabbinic schools.
====

[[v43-7-16]]

^<<v43-7-16,16>>^ Jesus, in turn, answered them and said: “What I teach is not mine, but belongs to him who sent me.

[[v43-7-17]]

^<<v43-7-17,17>>^ If anyone desires to do His will, he will know whether the teaching is from God or I speak of my own originality.

[[v43-7-18]]

^<<v43-7-18,18>>^ Whoever speaks of his own originality is seeking his own glory; but whoever seeks the glory of the one who sent him, this one is true and there is no unrighteousness in him.

[[v43-7-19]]

^<<v43-7-19,19>>^ Moses gave you the Law, did he not? But not one of you obeys the Law. Why are you seeking to kill me?”

[[v43-7-20]]

^<<v43-7-20,20>>^ The crowd answered: “You have a demon. Who is seeking to kill you?”

[[v43-7-21]]

^<<v43-7-21,21>>^ In answer Jesus said to them: “One deed I performed, and you are all surprised.

[[v43-7-22]]

^<<v43-7-22,22>>^ For this reason Moses has given you circumcision—not that it is from Moses, but it is from the forefathers—and you circumcise a man on a sabbath.

[[v43-7-23]]

^<<v43-7-23,23>>^ If a man receives circumcision on a sabbath so that the Law of Moses may not be broken, are you violently angry at me because I made a man completely well on a sabbath?

[[v43-7-24]]

^<<v43-7-24,24>>^ Stop judging by the outward appearance, but judge with righteous judgment.”

[[v43-7-25]]

^<<v43-7-25,25>>^ Then some of the inhabitants of Jerusalem began to say: “This is the man they are seeking to kill, is it not?

[[v43-7-26]]

^<<v43-7-26,26>>^ And yet see! he is speaking in public, and they say nothing to him. Have the rulers come to know for certain that this is the Christ?

[[v43-7-27]]

^<<v43-7-27,27>>^ On the contrary, we know where this man is from; yet when the Christ comes, no one is to know where he is from.”

[[v43-7-28]]

^<<v43-7-28,28>>^ Then as he was teaching in the temple, Jesus called out: “You know me and you know where I am from. And I have not come of my own initiative, but the One who sent me is real, and you do not know him.

[[v43-7-29]]

^<<v43-7-29,29>>^ I know him, because I am a representative from him, and that One sent me.”

[[v43-7-30]]

^<<v43-7-30,30>>^ So they began seeking to get hold of him, but no one laid a hand on him, for his hour had not yet come.

[[v43-7-31]]

^<<v43-7-31,31>>^ Still, many of the crowd put faith in him, and they were saying: “When the Christ comes, he will not perform more signs than this man has done, will he?”

[[v43-7-32]]

^<<v43-7-32,32>>^ The Pharisees heard the crowd murmuring these things about him, and the chief priests and the Pharisees sent officers to seize^&#42;1^ him.

[NOTE]
====
. Or “arrest.”
====

[[v43-7-33]]

^<<v43-7-33,33>>^ Jesus then said: “I will be with you a little while longer before I go to the One who sent me.

[[v43-7-34]]

^<<v43-7-34,34>>^ You will look for me, but you will not find me, and where I am you cannot come.”

[[v43-7-35]]

^<<v43-7-35,35>>^ Therefore, the Jews said among themselves: “Where does this man intend to go, so that we will not find him? He does not intend to go to the Jews dispersed among the Greeks and teach the Greeks, does he?

[[v43-7-36]]

^<<v43-7-36,36>>^ What does he mean when he says, ‘You will look for me, but you will not find me, and where I am you cannot come’?”

[[v43-7-37]]

^<<v43-7-37,37>>^ On the last day, the great day of the festival, Jesus stood up and he called out: “If anyone is thirsty, let him come to me and drink.

[[v43-7-38]]

^<<v43-7-38,38>>^ Whoever puts faith in me, just as the scripture has said: ‘From deep within him streams of living water will flow.’”

[[v43-7-39]]

^<<v43-7-39,39>>^ However, he said this concerning the spirit, which those who put faith in him were about to receive; for as yet there was no spirit, because Jesus had not yet been glorified.

[[v43-7-40]]

^<<v43-7-40,40>>^ Some in the crowd who heard these words began saying: “This really is the Prophet.”

[[v43-7-41]]

^<<v43-7-41,41>>^ Others were saying: “This is the Christ.” But some were saying: “The Christ is not coming out of Galʹi·lee, is he?

[[v43-7-42]]

^<<v43-7-42,42>>^ Does the scripture not say that the Christ is coming from the offspring of David and from Bethʹle·hem, the village where David was?”

[[v43-7-43]]

^<<v43-7-43,43>>^ So a division over him arose among the crowd.

[[v43-7-44]]

^<<v43-7-44,44>>^ Some of them, though, wanted to seize^&#42;1^ him, but no one laid his hands on him.

[NOTE]
====
. Or “arrest.”
====

[[v43-7-45]]

^<<v43-7-45,45>>^ Then the officers went back to the chief priests and Pharisees, and the latter said to them: “Why did you not bring him in?”

[[v43-7-46]]

^<<v43-7-46,46>>^ The officers replied: “Never has any man spoken like this.”

[[v43-7-47]]

^<<v43-7-47,47>>^ In turn the Pharisees answered: “You have not been misled also, have you?

[[v43-7-48]]

^<<v43-7-48,48>>^ Not one of the rulers or of the Pharisees has put faith in him, has he?

[[v43-7-49]]

^<<v43-7-49,49>>^ But this crowd who do not know the Law are accursed people.”

[[v43-7-50]]

^<<v43-7-50,50>>^ Nic·o·deʹmus, who had come to him previously and who was one of them, said to them:

[[v43-7-51]]

^<<v43-7-51,51>>^ “Our Law does not judge a man unless it first hears from him and learns what he is doing, does it?”

[[v43-7-52]]

^<<v43-7-52,52>>^ In answer they said to him: “You are not also out of Galʹi·lee, are you? Search and see that no prophet is to be raised up out of Galʹi·lee.”^&#42;1^

[NOTE]
====
. A number of ancient and authoritative manuscripts omit from vs. 53 to chapter 8, vs. 11.
====

'''

xref:043-john/043-john-006.adoc#v43-6-0[&#60; Capítulo Anterior] | <<v43-7-0,Topo>> | xref:043-john/043-john-008.adoc#v43-8-0[Próximo Capítulo &#62;]