include::./index.adoc[]

[[v43-11-0]]
=== According to John, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-11-1]]

^<<v43-11-1,1>>^ Now a man named Lazʹa·rus was sick; he was from Bethʹa·ny, the village of Mary and her sister Martha.

[[v43-11-2]]

^<<v43-11-2,2>>^ This was the Mary who poured perfumed oil on the Lord and wiped his feet dry with her hair; it was her brother Lazʹa·rus who was sick.

[[v43-11-3]]

^<<v43-11-3,3>>^ So his sisters sent a message to him, saying: “Lord, see! the one you have affection for is sick.”

[[v43-11-4]]

^<<v43-11-4,4>>^ But when Jesus heard it, he said: “This sickness is not meant to end in death, but is for the glory of God, so that the Son of God may be glorified through it.”

[[v43-11-5]]

^<<v43-11-5,5>>^ Now Jesus loved Martha and her sister and Lazʹa·rus.

[[v43-11-6]]

^<<v43-11-6,6>>^ However, when he heard that Lazʹa·rus was sick, he actually remained in the place where he was for two more days.

[[v43-11-7]]

^<<v43-11-7,7>>^ Then after this he said to the disciples: “Let us go into Ju·deʹa again.”

[[v43-11-8]]

^<<v43-11-8,8>>^ The disciples said to him: “Rabbi, just lately the Ju·deʹans were seeking to stone you, and are you going there again?”

[[v43-11-9]]

^<<v43-11-9,9>>^ Jesus answered: “There are 12 hours of daylight, are there not? If anyone walks in daylight, he does not stumble into anything, because he sees the light of this world.

[[v43-11-10]]

^<<v43-11-10,10>>^ But if anyone walks in the night, he stumbles, because the light is not in him.”

[[v43-11-11]]

^<<v43-11-11,11>>^ After he said these things, he added: “Lazʹa·rus our friend has fallen asleep, but I am traveling there to awaken him.”

[[v43-11-12]]

^<<v43-11-12,12>>^ The disciples then said to him: “Lord, if he is sleeping, he will get well.”

[[v43-11-13]]

^<<v43-11-13,13>>^ Jesus, however, had spoken about his death. But they imagined he was speaking about taking rest in sleep.

[[v43-11-14]]

^<<v43-11-14,14>>^ Then Jesus said to them plainly: “Lazʹa·rus has died,

[[v43-11-15]]

^<<v43-11-15,15>>^ and I rejoice for your sake that I was not there, so that you may believe. But let us go to him.”

[[v43-11-16]]

^<<v43-11-16,16>>^ So Thomas, who was called the Twin, said to his fellow disciples: “Let us also go, so that we may die with him.”

[[v43-11-17]]

^<<v43-11-17,17>>^ When Jesus arrived, he found that Lazʹa·rus had already been in the tomb^&#42;1^ for four days.

[NOTE]
====
. Or “memorial tomb.”
====

[[v43-11-18]]

^<<v43-11-18,18>>^ Now Bethʹa·ny was near Jerusalem, about two miles^&#42;1^ away.

[NOTE]
====
. About three km. Lit., “about 15 stadia.” See App. B14.
====

[[v43-11-19]]

^<<v43-11-19,19>>^ And many of the Jews had come to Martha and Mary to console them concerning their brother.

[[v43-11-20]]

^<<v43-11-20,20>>^ When Martha heard that Jesus was coming, she went to meet him; but Mary kept sitting at home.

[[v43-11-21]]

^<<v43-11-21,21>>^ Martha then said to Jesus: “Lord, if you had been here, my brother would not have died.

[[v43-11-22]]

^<<v43-11-22,22>>^ Yet even now I know that whatever you ask God for, God will give you.”

[[v43-11-23]]

^<<v43-11-23,23>>^ Jesus said to her: “Your brother will rise.”

[[v43-11-24]]

^<<v43-11-24,24>>^ Martha said to him: “I know he will rise in the resurrection on the last day.”

[[v43-11-25]]

^<<v43-11-25,25>>^ Jesus said to her: “I am the resurrection and the life. The one who exercises faith in me, even though he dies, will come to life;

[[v43-11-26]]

^<<v43-11-26,26>>^ and everyone who is living and exercises faith in me will never die at all. Do you believe this?”

[[v43-11-27]]

^<<v43-11-27,27>>^ She said to him: “Yes, Lord, I have believed that you are the Christ, the Son of God, the one coming into the world.”

[[v43-11-28]]

^<<v43-11-28,28>>^ When she had said this, she went off and called Mary her sister, saying privately: “The Teacher is here and is calling you.”

[[v43-11-29]]

^<<v43-11-29,29>>^ On hearing this, she got up quickly and went to him.

[[v43-11-30]]

^<<v43-11-30,30>>^ Jesus had not yet come into the village, but he was still in the place where Martha had met him.

[[v43-11-31]]

^<<v43-11-31,31>>^ When the Jews who were with Mary in the house consoling her saw her get up quickly and go out, they followed her, supposing that she was going to the tomb^&#42;1^ to weep there.

[NOTE]
====
. Or “memorial tomb.”
====

[[v43-11-32]]

^<<v43-11-32,32>>^ When Mary arrived where Jesus was and caught sight of him, she fell at his feet and said to him: “Lord, if you had been here, my brother would not have died.”

[[v43-11-33]]

^<<v43-11-33,33>>^ When Jesus saw her weeping and the Jews who had come with her weeping, he groaned within himself^&#42;1^ and became troubled.

[NOTE]
====
. Lit., “in the spirit.”
====

[[v43-11-34]]

^<<v43-11-34,34>>^ He said: “Where have you laid him?” They said to him: “Lord, come and see.”

[[v43-11-35]]

^<<v43-11-35,35>>^ Jesus gave way to tears.

[[v43-11-36]]

^<<v43-11-36,36>>^ At that the Jews began to say: “See, what affection he had for him!”

[[v43-11-37]]

^<<v43-11-37,37>>^ But some of them said: “Could not this man who opened the eyes of the blind man prevent this one from dying?”

[[v43-11-38]]

^<<v43-11-38,38>>^ Then Jesus, after groaning again within himself, came to the tomb.^&#42;1^ It was, in fact, a cave, and a stone was lying against it.

[NOTE]
====
. Or “memorial tomb.”
====

[[v43-11-39]]

^<<v43-11-39,39>>^ Jesus said: “Take the stone away.” Martha, the sister of the deceased, said to him: “Lord, by now he must smell, for it has been four days.”

[[v43-11-40]]

^<<v43-11-40,40>>^ Jesus said to her: “Did I not tell you that if you would believe you would see the glory of God?”

[[v43-11-41]]

^<<v43-11-41,41>>^ So they took the stone away. Then Jesus raised his eyes heavenward and said: “Father, I thank you that you have heard me.

[[v43-11-42]]

^<<v43-11-42,42>>^ True, I knew that you always hear me; but I spoke on account of the crowd standing around, so that they may believe that you sent me.”

[[v43-11-43]]

^<<v43-11-43,43>>^ When he had said these things, he cried out with a loud voice: “Lazʹa·rus, come out!”

[[v43-11-44]]

^<<v43-11-44,44>>^ The man who had been dead came out with his feet and hands bound with wrappings, and his face was wrapped with a cloth. Jesus said to them: “Free him and let him go.”

[[v43-11-45]]

^<<v43-11-45,45>>^ Therefore, many of the Jews who had come to Mary and who saw what he did put faith in him,

[[v43-11-46]]

^<<v43-11-46,46>>^ but some of them went off to the Pharisees and told them what Jesus had done.

[[v43-11-47]]

^<<v43-11-47,47>>^ So the chief priests and the Pharisees gathered the Sanʹhe·drin together and said: “What are we to do, for this man performs many signs?

[[v43-11-48]]

^<<v43-11-48,48>>^ If we let him go on this way, they will all put faith in him, and the Romans will come and take away both our place^&#42;1^ and our nation.”

[NOTE]
====
. That is, the temple.
====

[[v43-11-49]]

^<<v43-11-49,49>>^ But one of them, Caʹia·phas, who was high priest that year, said to them: “You do not know anything at all,

[[v43-11-50]]

^<<v43-11-50,50>>^ and you have not reasoned that it is to your benefit for one man to die in behalf of the people rather than for the whole nation to be destroyed.”

[[v43-11-51]]

^<<v43-11-51,51>>^ He did not say this, however, of his own originality, but because he was high priest that year, he prophesied that Jesus was to die for the nation,

[[v43-11-52]]

^<<v43-11-52,52>>^ and not only for the nation but also to gather together into one the children of God who were scattered about.

[[v43-11-53]]

^<<v43-11-53,53>>^ So from that day on they conspired to kill him.

[[v43-11-54]]

^<<v43-11-54,54>>^ Therefore, Jesus no longer walked about publicly among the Jews, but he departed from there to the region near the wilderness, to a city called Eʹphra·im, and he stayed there with the disciples.

[[v43-11-55]]

^<<v43-11-55,55>>^ Now the Passover of the Jews was near, and many people from the countryside went up to Jerusalem before the Passover to cleanse themselves ceremonially.

[[v43-11-56]]

^<<v43-11-56,56>>^ They were looking for Jesus, and they were saying to one another as they stood around in the temple: “What is your opinion? That he will not come to the festival at all?”

[[v43-11-57]]

^<<v43-11-57,57>>^ But the chief priests and the Pharisees had given orders that if anyone got to know where Jesus was, he should report it, so that they could seize^&#42;1^ him.

[NOTE]
====
. Or “arrest.”
====

'''

xref:043-john/043-john-010.adoc#v43-10-0[&#60; Capítulo Anterior] | <<v43-11-0,Topo>> | xref:043-john/043-john-012.adoc#v43-12-0[Próximo Capítulo &#62;]