include::./index.adoc[]

[[v43-5-0]]
=== According to John, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-5-1]]

^<<v43-5-1,1>>^ After this there was a festival of the Jews, and Jesus went up to Jerusalem.

[[v43-5-2]]

^<<v43-5-2,2>>^ Now in Jerusalem at the Sheep Gate is a pool called in Hebrew Beth·zaʹtha, with five colonnades.

[[v43-5-3]]

^<<v43-5-3,3>>^ Within these a multitude of the sick, blind, lame, and those with withered^&#42;1^ limbs were lying down.

[NOTE]
====
. Or “paralyzed.”
====

[[v43-5-4]]

^<<v43-5-4,4>>^ ^&#42;1^ ——

[NOTE]
====
. See App. A3.
====

[[v43-5-5]]

^<<v43-5-5,5>>^ But one man was there who had been sick for 38 years.

[[v43-5-6]]

^<<v43-5-6,6>>^ Seeing this man lying there and being aware that he had already been sick for a long time, Jesus said to him: “Do you want to get well?”

[[v43-5-7]]

^<<v43-5-7,7>>^ The sick man answered him: “Sir, I do not have anyone to put me into the pool when the water is stirred up, but while I am on my way, another steps down ahead of me.”

[[v43-5-8]]

^<<v43-5-8,8>>^ Jesus said to him: “Get up! Pick up your mat^&#42;1^ and walk.”

[NOTE]
====
. Or “bed.”
====

[[v43-5-9]]

^<<v43-5-9,9>>^ And the man immediately got well, and he picked up his mat^&#42;1^ and began to walk.
That day was the Sabbath.

[NOTE]
====
. Or “bed.”
====

[[v43-5-10]]

^<<v43-5-10,10>>^ So the Jews began to say to the cured man: “It is the Sabbath, and it is not lawful for you to carry the mat.”^&#42;1^

[NOTE]
====
. Or “bed.”
====

[[v43-5-11]]

^<<v43-5-11,11>>^ But he answered them: “The same one who made me well said to me, ‘Pick up your mat^&#42;1^ and walk.’”

[NOTE]
====
. Or “bed.”
====

[[v43-5-12]]

^<<v43-5-12,12>>^ They asked him: “Who is the man who told you, ‘Pick it up and walk’?”

[[v43-5-13]]

^<<v43-5-13,13>>^ But the healed man did not know who he was, for Jesus had slipped away into the crowd that was there.

[[v43-5-14]]

^<<v43-5-14,14>>^ After this Jesus found him in the temple and said to him: “See, you have become well. Do not sin anymore, so that something worse does not happen to you.”

[[v43-5-15]]

^<<v43-5-15,15>>^ The man went away and told the Jews that it was Jesus who had made him well.

[[v43-5-16]]

^<<v43-5-16,16>>^ For this reason the Jews were persecuting Jesus, because he was doing these things during the Sabbath.

[[v43-5-17]]

^<<v43-5-17,17>>^ But he answered them: “My Father has kept working until now, and I keep working.”

[[v43-5-18]]

^<<v43-5-18,18>>^ This is why the Jews began seeking all the more to kill him, because not only was he breaking the Sabbath but he was also calling God his own Father, making himself equal to God.

[[v43-5-19]]

^<<v43-5-19,19>>^ Therefore, in response Jesus said to them: “Most truly I say to you, the Son cannot do a single thing of his own initiative, but only what he sees the Father doing. For whatever things that One does, these things the Son does also in like manner.

[[v43-5-20]]

^<<v43-5-20,20>>^ For the Father has affection for the Son and shows him all the things he himself does, and he will show him works greater than these, so that you may marvel.

[[v43-5-21]]

^<<v43-5-21,21>>^ For just as the Father raises the dead up and makes them alive, so the Son also makes alive whomever he wants to.

[[v43-5-22]]

^<<v43-5-22,22>>^ For the Father judges no one at all, but he has entrusted all the judging to the Son,

[[v43-5-23]]

^<<v43-5-23,23>>^ so that all may honor the Son just as they honor the Father. Whoever does not honor the Son does not honor the Father who sent him.

[[v43-5-24]]

^<<v43-5-24,24>>^ Most truly I say to you, whoever hears my word and believes the One who sent me has everlasting life, and he does not come into judgment but has passed over from death to life.

[[v43-5-25]]

^<<v43-5-25,25>>^ “Most truly I say to you, the hour is coming, and it is now, when the dead will hear the voice of the Son of God, and those who have paid attention will live.

[[v43-5-26]]

^<<v43-5-26,26>>^ For just as the Father has life in himself,^&#42;1^ so he has granted also to the Son to have life in himself.

[NOTE]
====
. Or “has in himself the gift of life.”
====

[[v43-5-27]]

^<<v43-5-27,27>>^ And he has given him authority to do judging, because he is the Son of man.

[[v43-5-28]]

^<<v43-5-28,28>>^ Do not be amazed at this, for the hour is coming in which all those in the memorial tombs will hear his voice

[[v43-5-29]]

^<<v43-5-29,29>>^ and come out, those who did good things to a resurrection of life, and those who practiced vile things to a resurrection of judgment.

[[v43-5-30]]

^<<v43-5-30,30>>^ I cannot do a single thing of my own initiative. Just as I hear, I judge, and my judgment is righteous because I seek, not my own will, but the will of him who sent me.

[[v43-5-31]]

^<<v43-5-31,31>>^ “If I alone bear witness about myself, my witness is not true.

[[v43-5-32]]

^<<v43-5-32,32>>^ There is another who bears witness about me, and I know that the witness he bears about me is true.

[[v43-5-33]]

^<<v43-5-33,33>>^ You have sent men to John, and he has borne witness to the truth.

[[v43-5-34]]

^<<v43-5-34,34>>^ However, I do not accept the witness from man, but I say these things so that you may be saved.

[[v43-5-35]]

^<<v43-5-35,35>>^ That man was a burning and shining lamp, and for a short time you were willing to rejoice greatly in his light.

[[v43-5-36]]

^<<v43-5-36,36>>^ But I have the witness greater than that of John, for the very works that my Father assigned me to accomplish, these works that I am doing, bear witness that the Father sent me.

[[v43-5-37]]

^<<v43-5-37,37>>^ And the Father who sent me has himself borne witness about me. You have neither heard his voice at any time nor seen his form,

[[v43-5-38]]

^<<v43-5-38,38>>^ and you do not have his word residing in you, because you do not believe the very one whom he sent.

[[v43-5-39]]

^<<v43-5-39,39>>^ “You are searching the Scriptures because you think that you will have everlasting life by means of them; and these are the very ones^&#42;1^ that bear witness about me.

[NOTE]
====
. That is, the Scriptures.
====

[[v43-5-40]]

^<<v43-5-40,40>>^ And yet you do not want to come to me so that you may have life.

[[v43-5-41]]

^<<v43-5-41,41>>^ I do not accept glory from men,

[[v43-5-42]]

^<<v43-5-42,42>>^ but I well know that you do not have the love of God in you.

[[v43-5-43]]

^<<v43-5-43,43>>^ I have come in the name of my Father, but you do not receive me. If someone else came in his own name, you would receive that one.

[[v43-5-44]]

^<<v43-5-44,44>>^ How can you believe, when you are accepting glory from one another and you are not seeking the glory that is from the only God?

[[v43-5-45]]

^<<v43-5-45,45>>^ Do not think that I will accuse you to the Father; there is one who accuses you, Moses, in whom you have put your hope.

[[v43-5-46]]

^<<v43-5-46,46>>^ In fact, if you believed Moses, you would believe me, for he wrote about me.

[[v43-5-47]]

^<<v43-5-47,47>>^ But if you do not believe his writings, how will you believe what I say?”

'''

xref:043-john/043-john-004.adoc#v43-4-0[&#60; Capítulo Anterior] | <<v43-5-0,Topo>> | xref:043-john/043-john-006.adoc#v43-6-0[Próximo Capítulo &#62;]