include::./index.adoc[]

[[v43-9-0]]
=== According to John, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-9-1]]

^<<v43-9-1,1>>^ As he was passing along, he saw a man who had been blind from birth.

[[v43-9-2]]

^<<v43-9-2,2>>^ And his disciples asked him: “Rabbi, who sinned, this man or his parents, so that he was born blind?”

[[v43-9-3]]

^<<v43-9-3,3>>^ Jesus answered: “Neither this man sinned nor his parents, but it was so that the works of God might be made manifest in his case.

[[v43-9-4]]

^<<v43-9-4,4>>^ We must do the works of the One who sent me while it is day; the night is coming when no man can work.

[[v43-9-5]]

^<<v43-9-5,5>>^ As long as I am in the world, I am the world’s light.”

[[v43-9-6]]

^<<v43-9-6,6>>^ After he said these things, he spat on the ground and made a paste with the saliva, and he smeared the paste on the man’s eyes

[[v43-9-7]]

^<<v43-9-7,7>>^ and said to him: “Go wash in the pool of Si·loʹam” (which is translated “Sent Forth”). And he went and washed, and came back seeing.

[[v43-9-8]]

^<<v43-9-8,8>>^ Then the neighbors and those who formerly used to see that he was a beggar began to say: “This is the man who used to sit and beg, is it not?”

[[v43-9-9]]

^<<v43-9-9,9>>^ Some were saying: “This is he.” Others were saying: “No, but he looks like him.” The man kept saying: “I am he.”

[[v43-9-10]]

^<<v43-9-10,10>>^ So they asked him: “How, then, were your eyes opened?”

[[v43-9-11]]

^<<v43-9-11,11>>^ He answered: “The man called Jesus made a paste and smeared it on my eyes and said to me, ‘Go to Si·loʹam and wash.’ So I went and washed and gained sight.”

[[v43-9-12]]

^<<v43-9-12,12>>^ At this they said to him: “Where is that man?” He said: “I do not know.”

[[v43-9-13]]

^<<v43-9-13,13>>^ They led the formerly blind man to the Pharisees.

[[v43-9-14]]

^<<v43-9-14,14>>^ Incidentally, the day that Jesus made the paste and opened his eyes was the Sabbath.

[[v43-9-15]]

^<<v43-9-15,15>>^ So this time the Pharisees also began asking the man how he gained sight. He said to them: “He put a paste on my eyes, and I washed, and I can see.”

[[v43-9-16]]

^<<v43-9-16,16>>^ Some of the Pharisees then began to say: “This is not a man from God, for he does not observe the Sabbath.” Others said: “How can a man who is a sinner perform signs of that sort?” So there was a division among them.

[[v43-9-17]]

^<<v43-9-17,17>>^ And again they said to the blind man: “What do you say about him, since it was your eyes that he opened?” The man said: “He is a prophet.”

[[v43-9-18]]

^<<v43-9-18,18>>^ However, the Jews did not believe that he had been blind and had gained sight, until they called the parents of the man who could now see.

[[v43-9-19]]

^<<v43-9-19,19>>^ And they asked them: “Is this your son who you say was born blind? How, then, does he now see?”

[[v43-9-20]]

^<<v43-9-20,20>>^ His parents answered: “We know that this is our son and that he was born blind.

[[v43-9-21]]

^<<v43-9-21,21>>^ But how it is that he now sees, we do not know; or who opened his eyes, we do not know. Ask him. He is of age. He must speak for himself.”

[[v43-9-22]]

^<<v43-9-22,22>>^ His parents said these things because they were in fear of the Jews, for the Jews had already come to an agreement that if anyone acknowledged him as Christ, that person should be expelled from the synagogue.

[[v43-9-23]]

^<<v43-9-23,23>>^ This is why his parents said: “He is of age. Question him.”

[[v43-9-24]]

^<<v43-9-24,24>>^ So a second time they called the man who had been blind and said to him: “Give glory to God; we know that this man is a sinner.”

[[v43-9-25]]

^<<v43-9-25,25>>^ He answered: “Whether he is a sinner, I do not know. One thing I do know, that I was blind, but now I can see.”

[[v43-9-26]]

^<<v43-9-26,26>>^ Then they said to him: “What did he do to you? How did he open your eyes?”

[[v43-9-27]]

^<<v43-9-27,27>>^ He answered them: “I told you already, and yet you did not listen. Why do you want to hear it again? You do not want to become his disciples also, do you?”

[[v43-9-28]]

^<<v43-9-28,28>>^ At this they scornfully told him: “You are a disciple of that man, but we are disciples of Moses.

[[v43-9-29]]

^<<v43-9-29,29>>^ We know that God has spoken to Moses, but as for this man, we do not know where he is from.”

[[v43-9-30]]

^<<v43-9-30,30>>^ The man answered them: “This is certainly amazing, that you do not know where he is from, and yet he opened my eyes.

[[v43-9-31]]

^<<v43-9-31,31>>^ We know that God does not listen to sinners, but if anyone is God-fearing and does his will, he listens to this one.

[[v43-9-32]]

^<<v43-9-32,32>>^ From of old it has never been heard that anyone opened the eyes of one born blind.

[[v43-9-33]]

^<<v43-9-33,33>>^ If this man were not from God, he could do nothing at all.”

[[v43-9-34]]

^<<v43-9-34,34>>^ In answer they said to him: “You were altogether born in sin, and yet are you teaching us?” And they threw him out!

[[v43-9-35]]

^<<v43-9-35,35>>^ Jesus heard that they had thrown him out, and on finding him, he said: “Are you putting faith in the Son of man?”

[[v43-9-36]]

^<<v43-9-36,36>>^ The man answered: “And who is he, sir, so that I may put faith in him?”

[[v43-9-37]]

^<<v43-9-37,37>>^ Jesus said to him: “You have seen him, and in fact, he is the one speaking with you.”

[[v43-9-38]]

^<<v43-9-38,38>>^ He said: “I do put faith in him, Lord.” And he did obeisance^&#42;1^ to him.

[NOTE]
====
. Or “bowed down.”
====

[[v43-9-39]]

^<<v43-9-39,39>>^ Jesus then said: “For this judgment I came into this world, that those not seeing might see and those seeing might become blind.”

[[v43-9-40]]

^<<v43-9-40,40>>^ Those of the Pharisees who were with him heard these things, and they said to him: “We are not blind also, are we?”

[[v43-9-41]]

^<<v43-9-41,41>>^ Jesus said to them: “If you were blind, you would have no sin. But now you say, ‘We see.’ Your sin remains.”

'''

xref:043-john/043-john-008.adoc#v43-8-0[&#60; Capítulo Anterior] | <<v43-9-0,Topo>> | xref:043-john/043-john-010.adoc#v43-10-0[Próximo Capítulo &#62;]