include::./index.adoc[]

[[v43-20-0]]
=== According to John, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-20-1]]

^<<v43-20-1,1>>^ On the first day of the week, Mary Magʹda·lene came to the tomb^&#42;1^ early, while it was still dark, and she saw that the stone had already been taken away from the tomb.^&#42;2^

[NOTE]
====
. Or “memorial tomb.”
. Or “memorial tomb.”
====

[[v43-20-2]]

^<<v43-20-2,2>>^ So she came running to Simon Peter and to the other disciple, for whom Jesus had affection, and she said to them: “They have taken away the Lord out of the tomb, and we do not know where they have laid him.”

[[v43-20-3]]

^<<v43-20-3,3>>^ Then Peter and the other disciple set out for the tomb.

[[v43-20-4]]

^<<v43-20-4,4>>^ The two of them began running together, but the other disciple ran faster than Peter and reached the tomb first.

[[v43-20-5]]

^<<v43-20-5,5>>^ Stooping forward, he saw the linen cloths lying there, but he did not go in.

[[v43-20-6]]

^<<v43-20-6,6>>^ Then Simon Peter also came, following him, and he went into the tomb. And he saw the linen cloths lying there.

[[v43-20-7]]

^<<v43-20-7,7>>^ The cloth that had been on his head was not lying with the other cloth bands but was rolled up in a place by itself.

[[v43-20-8]]

^<<v43-20-8,8>>^ Then the other disciple who had reached the tomb first also went in, and he saw and believed.

[[v43-20-9]]

^<<v43-20-9,9>>^ For they did not yet understand the scripture that he must rise from the dead.

[[v43-20-10]]

^<<v43-20-10,10>>^ So the disciples went back to their homes.

[[v43-20-11]]

^<<v43-20-11,11>>^ Mary, however, kept standing outside near the tomb, weeping. While she was weeping, she stooped forward to look into the tomb,

[[v43-20-12]]

^<<v43-20-12,12>>^ and she saw two angels in white sitting where the body of Jesus had been lying, one at the head and one at the feet.

[[v43-20-13]]

^<<v43-20-13,13>>^ And they said to her: “Woman, why are you weeping?” She said to them: “They have taken my Lord away, and I do not know where they have laid him.”

[[v43-20-14]]

^<<v43-20-14,14>>^ After saying this, she turned around and saw Jesus standing there, but she did not realize that it was Jesus.

[[v43-20-15]]

^<<v43-20-15,15>>^ Jesus said to her: “Woman, why are you weeping? Whom are you looking for?” She, thinking it was the gardener, said to him: “Sir, if you have carried him off, tell me where you have laid him, and I will take him away.”

[[v43-20-16]]

^<<v43-20-16,16>>^ Jesus said to her: “Mary!” On turning around, she said to him in Hebrew: “Rab·boʹni!” (which means “Teacher!”)

[[v43-20-17]]

^<<v43-20-17,17>>^ Jesus said to her: “Stop clinging to me, for I have not yet ascended to the Father. But go to my brothers and say to them, ‘I am ascending to my Father and your Father and to my God and your God.’”

[[v43-20-18]]

^<<v43-20-18,18>>^ Mary Magʹda·lene came and brought the news to the disciples: “I have seen the Lord!” And she told them what he had said to her.

[[v43-20-19]]

^<<v43-20-19,19>>^ When it was late that day, the first day of the week, and the doors were locked where the disciples were for fear of the Jews, Jesus came and stood in their midst and said to them: “May you have peace.”

[[v43-20-20]]

^<<v43-20-20,20>>^ After saying this, he showed them his hands and his side. Then the disciples rejoiced at seeing the Lord.

[[v43-20-21]]

^<<v43-20-21,21>>^ Jesus said to them again: “May you have peace. Just as the Father has sent me, I also am sending you.”

[[v43-20-22]]

^<<v43-20-22,22>>^ After saying this he blew on them and said to them: “Receive holy spirit.

[[v43-20-23]]

^<<v43-20-23,23>>^ If you forgive the sins of anyone, they are forgiven; if you retain those of anyone, they are retained.”

[[v43-20-24]]

^<<v43-20-24,24>>^ But Thomas, one of the Twelve, who was called the Twin, was not with them when Jesus came.

[[v43-20-25]]

^<<v43-20-25,25>>^ So the other disciples were telling him: “We have seen the Lord!” But he said to them: “Unless I see in his hands the print^&#42;1^ of the nails and stick my finger into the print of the nails and stick my hand into his side, I will never believe it.”

[NOTE]
====
. Or “mark.”
====

[[v43-20-26]]

^<<v43-20-26,26>>^ Well, eight days later his disciples were again indoors, and Thomas was with them. Jesus came, although the doors were locked, and he stood in their midst and said: “May you have peace.”

[[v43-20-27]]

^<<v43-20-27,27>>^ Next he said to Thomas: “Put your finger here, and see my hands, and take your hand and stick it into my side, and stop doubting^&#42;1^ but believe.”

[NOTE]
====
. Lit., “being unbelieving.”
====

[[v43-20-28]]

^<<v43-20-28,28>>^ In answer Thomas said to him: “My Lord and my God!”

[[v43-20-29]]

^<<v43-20-29,29>>^ Jesus said to him: “Because you have seen me, have you believed? Happy are those who have not seen and yet believe.”

[[v43-20-30]]

^<<v43-20-30,30>>^ To be sure, Jesus also performed many other signs before the disciples, which are not written down in this scroll.

[[v43-20-31]]

^<<v43-20-31,31>>^ But these have been written down so that you may believe that Jesus is the Christ, the Son of God, and because of believing, you may have life by means of his name.

'''

xref:043-john/043-john-019.adoc#v43-19-0[&#60; Capítulo Anterior] | <<v43-20-0,Topo>> | xref:043-john/043-john-021.adoc#v43-21-0[Próximo Capítulo &#62;]