include::./index.adoc[]

[[v43-6-0]]
=== According to John, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-6-1]]

^<<v43-6-1,1>>^ After this Jesus set out across the Sea of Galʹi·lee, or Ti·beʹri·as.

[[v43-6-2]]

^<<v43-6-2,2>>^ And a large crowd kept following him, because they were observing the miraculous signs he was performing in healing the sick.

[[v43-6-3]]

^<<v43-6-3,3>>^ So Jesus went up on a mountain and sat down there with his disciples.

[[v43-6-4]]

^<<v43-6-4,4>>^ Now the Passover, the festival of the Jews, was near.

[[v43-6-5]]

^<<v43-6-5,5>>^ When Jesus raised his eyes and saw that a large crowd was coming to him, he said to Philip: “Where will we buy bread for these people to eat?”

[[v43-6-6]]

^<<v43-6-6,6>>^ However, he was saying this to test him, for he knew what he was about to do.

[[v43-6-7]]

^<<v43-6-7,7>>^ Philip answered him: “Two hundred de·narʹi·i^&#42;1^ worth of bread is not enough for each of them to get even a little.”

[NOTE]
====
. See App. B14.
====

[[v43-6-8]]

^<<v43-6-8,8>>^ One of his disciples, Andrew, Simon Peter’s brother, said to him:

[[v43-6-9]]

^<<v43-6-9,9>>^ “Here is a little boy who has five barley loaves and two small fish. But what are these among so many?”

[[v43-6-10]]

^<<v43-6-10,10>>^ Jesus said: “Have the people sit down.” As there was a lot of grass in that place, the men sat down there, about 5,000 in number.

[[v43-6-11]]

^<<v43-6-11,11>>^ Jesus took the bread, and after giving thanks, he distributed it to those who were sitting there; he did likewise with the small fish, and they had as much as they wanted.

[[v43-6-12]]

^<<v43-6-12,12>>^ But when they had eaten their fill, he said to his disciples: “Gather together the fragments left over, so that nothing is wasted.”

[[v43-6-13]]

^<<v43-6-13,13>>^ So they gathered them together and filled 12 baskets with fragments left over by those who had eaten from the five barley loaves.

[[v43-6-14]]

^<<v43-6-14,14>>^ When the people saw the sign he performed, they began to say: “This really is the Prophet who was to come into the world.”

[[v43-6-15]]

^<<v43-6-15,15>>^ Then Jesus, knowing that they were about to come and seize him to make him king, withdrew again to the mountain all alone.

[[v43-6-16]]

^<<v43-6-16,16>>^ When evening fell, his disciples went down to the sea,

[[v43-6-17]]

^<<v43-6-17,17>>^ and boarding a boat, they set out across the sea for Ca·perʹna·um. By now it had grown dark, and Jesus had not yet come to them.

[[v43-6-18]]

^<<v43-6-18,18>>^ Also, the sea was getting rough because a strong wind was blowing.

[[v43-6-19]]

^<<v43-6-19,19>>^ However, when they had rowed about three or four miles,^&#42;1^ they saw Jesus walking on the sea and getting near the boat, and they became fearful.

[NOTE]
====
. About five or six km. Lit., “about 25 or 30 stadia.” See App. B14.
====

[[v43-6-20]]

^<<v43-6-20,20>>^ But he said to them: “It is I; do not be afraid!”

[[v43-6-21]]

^<<v43-6-21,21>>^ Then they were willing to take him into the boat, and right away the boat arrived at the land to which they had been heading.

[[v43-6-22]]

^<<v43-6-22,22>>^ The next day the crowd that had stayed on the other side of the sea saw that there was no boat there. A small one had been there, but Jesus had not boarded that boat with his disciples, for his disciples had left by themselves.

[[v43-6-23]]

^<<v43-6-23,23>>^ Boats from Ti·beʹri·as, however, arrived near the place where they ate the bread after the Lord had given thanks.

[[v43-6-24]]

^<<v43-6-24,24>>^ So when the crowd saw that neither Jesus nor his disciples were there, they boarded their boats and came to Ca·perʹna·um to look for Jesus.

[[v43-6-25]]

^<<v43-6-25,25>>^ When they found him across the sea, they said to him: “Rabbi, when did you get here?”

[[v43-6-26]]

^<<v43-6-26,26>>^ Jesus answered them: “Most truly I say to you, you are looking for me, not because you saw signs, but because you ate from the loaves and were satisfied.

[[v43-6-27]]

^<<v43-6-27,27>>^ Work, not for the food that perishes, but for the food that remains for everlasting life, which the Son of man will give you; for on this one the Father, God himself, has put his seal of approval.”

[[v43-6-28]]

^<<v43-6-28,28>>^ So they said to him: “What must we do to carry out the works of God?”

[[v43-6-29]]

^<<v43-6-29,29>>^ In answer Jesus said to them: “This is the work of God, that you exercise faith in the one whom he sent.”

[[v43-6-30]]

^<<v43-6-30,30>>^ Then they said to him: “What are you performing as a sign, so that we may see it and believe you? What work are you doing?

[[v43-6-31]]

^<<v43-6-31,31>>^ Our forefathers ate the manna in the wilderness, just as it is written: ‘He gave them bread from heaven to eat.’”

[[v43-6-32]]

^<<v43-6-32,32>>^ Jesus then said to them: “Most truly I say to you, Moses did not give you the bread from heaven, but my Father gives you the true bread from heaven.

[[v43-6-33]]

^<<v43-6-33,33>>^ For the bread of God is the one who comes down from heaven and gives life to the world.”

[[v43-6-34]]

^<<v43-6-34,34>>^ So they said to him: “Lord, always give us this bread.”

[[v43-6-35]]

^<<v43-6-35,35>>^ Jesus said to them: “I am the bread of life. Whoever comes to me will not get hungry at all, and whoever exercises faith in me will never get thirsty at all.

[[v43-6-36]]

^<<v43-6-36,36>>^ But as I said to you, you have even seen me and yet do not believe.

[[v43-6-37]]

^<<v43-6-37,37>>^ All those whom the Father gives me will come to me, and I will never drive away the one who comes to me;

[[v43-6-38]]

^<<v43-6-38,38>>^ for I have come down from heaven to do, not my own will, but the will of him who sent me.

[[v43-6-39]]

^<<v43-6-39,39>>^ This is the will of him who sent me, that I should lose none out of all those whom he has given me, but that I should resurrect them on the last day.

[[v43-6-40]]

^<<v43-6-40,40>>^ For this is the will of my Father, that everyone who recognizes the Son and exercises faith in him should have everlasting life, and I will resurrect him on the last day.”

[[v43-6-41]]

^<<v43-6-41,41>>^ Then the Jews began to murmur about him because he had said: “I am the bread that came down from heaven.”

[[v43-6-42]]

^<<v43-6-42,42>>^ And they began saying: “Is this not Jesus the son of Joseph, whose father and mother we know? How does he now say, ‘I have come down from heaven’?”

[[v43-6-43]]

^<<v43-6-43,43>>^ In response Jesus said to them: “Stop murmuring among yourselves.

[[v43-6-44]]

^<<v43-6-44,44>>^ No man can come to me unless the Father, who sent me, draws him, and I will resurrect him on the last day.

[[v43-6-45]]

^<<v43-6-45,45>>^ It is written in the Prophets: ‘They will all be taught by Jehovah.’^&#42;1^ Everyone who has listened to the Father and has learned comes to me.

[NOTE]
====
. See App. A5.
====

[[v43-6-46]]

^<<v43-6-46,46>>^ Not that any man has seen the Father, except the one who is from God; this one has seen the Father.

[[v43-6-47]]

^<<v43-6-47,47>>^ Most truly I say to you, whoever believes has everlasting life.

[[v43-6-48]]

^<<v43-6-48,48>>^ “I am the bread of life.

[[v43-6-49]]

^<<v43-6-49,49>>^ Your forefathers ate the manna in the wilderness and yet they died.

[[v43-6-50]]

^<<v43-6-50,50>>^ This is the bread that comes down from heaven, so that anyone may eat of it and not die.

[[v43-6-51]]

^<<v43-6-51,51>>^ I am the living bread that came down from heaven. If anyone eats of this bread he will live forever; and for a fact, the bread that I will give is my flesh in behalf of the life of the world.”

[[v43-6-52]]

^<<v43-6-52,52>>^ Then the Jews began to argue with one another, saying: “How can this man give us his flesh to eat?”

[[v43-6-53]]

^<<v43-6-53,53>>^ So Jesus said to them: “Most truly I say to you, unless you eat the flesh of the Son of man and drink his blood, you have no life in yourselves.

[[v43-6-54]]

^<<v43-6-54,54>>^ Whoever feeds on my flesh and drinks my blood has everlasting life, and I will resurrect him on the last day;

[[v43-6-55]]

^<<v43-6-55,55>>^ for my flesh is true food and my blood is true drink.

[[v43-6-56]]

^<<v43-6-56,56>>^ Whoever feeds on my flesh and drinks my blood remains in union with me, and I in union with him.

[[v43-6-57]]

^<<v43-6-57,57>>^ Just as the living Father sent me and I live because of the Father, so also the one who feeds on me will live because of me.

[[v43-6-58]]

^<<v43-6-58,58>>^ This is the bread that came down from heaven. It is not as when your forefathers ate and yet died. Whoever feeds on this bread will live forever.”

[[v43-6-59]]

^<<v43-6-59,59>>^ He said these things as he was teaching in a synagogue^&#42;1^ in Ca·perʹna·um.

[NOTE]
====
. Or possibly, “public assembly.”
====

[[v43-6-60]]

^<<v43-6-60,60>>^ When they heard this, many of his disciples said: “This speech is shocking; who can listen to it?”

[[v43-6-61]]

^<<v43-6-61,61>>^ But Jesus, knowing in himself that his disciples were murmuring about this, said to them: “Does this stumble you?

[[v43-6-62]]

^<<v43-6-62,62>>^ What, therefore, if you should see the Son of man ascending to where he was before?

[[v43-6-63]]

^<<v43-6-63,63>>^ It is the spirit that is life-giving; the flesh is of no use at all. The sayings that I have spoken to you are spirit and are life.

[[v43-6-64]]

^<<v43-6-64,64>>^ But there are some of you who do not believe.” For Jesus knew from the beginning those who did not believe and the one who would betray him.

[[v43-6-65]]

^<<v43-6-65,65>>^ He went on to say: “This is why I have said to you, no one can come to me unless it is granted him by the Father.”

[[v43-6-66]]

^<<v43-6-66,66>>^ Because of this, many of his disciples went off to the things behind and would no longer walk with him.

[[v43-6-67]]

^<<v43-6-67,67>>^ So Jesus said to the Twelve: “You do not want to go also, do you?”

[[v43-6-68]]

^<<v43-6-68,68>>^ Simon Peter answered him: “Lord, whom shall we go away to? You have sayings of everlasting life.

[[v43-6-69]]

^<<v43-6-69,69>>^ We have believed and have come to know that you are the Holy One of God.”

[[v43-6-70]]

^<<v43-6-70,70>>^ Jesus answered them: “I chose you twelve, did I not? Yet one of you is a slanderer.”^&#42;1^

[NOTE]
====
. Or “a devil.”
====

[[v43-6-71]]

^<<v43-6-71,71>>^ He was, in fact, speaking of Judas the son of Simon Is·carʹi·ot, for this one was going to betray him, although he was one of the Twelve.

'''

xref:043-john/043-john-005.adoc#v43-5-0[&#60; Capítulo Anterior] | <<v43-6-0,Topo>> | xref:043-john/043-john-007.adoc#v43-7-0[Próximo Capítulo &#62;]