include::./index.adoc[]

[[v43-8-0]]
=== According to John, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-8-12]]

^<<v43-8-12,12>>^ Then Jesus spoke again to them, saying: “I am the light of the world. Whoever follows me will by no means walk in darkness, but will possess the light of life.”

[[v43-8-13]]

^<<v43-8-13,13>>^ So the Pharisees said to him: “You bear witness about yourself; your witness is not true.”

[[v43-8-14]]

^<<v43-8-14,14>>^ In answer Jesus said to them: “Even if I do bear witness about myself, my witness is true, because I know where I came from and where I am going. But you do not know where I came from and where I am going.

[[v43-8-15]]

^<<v43-8-15,15>>^ You judge according to the flesh;^&#42;1^ I do not judge any man at all.

[NOTE]
====
. Or “by human standards.”
====

[[v43-8-16]]

^<<v43-8-16,16>>^ And yet even if I do judge, my judgment is truthful, because I am not alone, but the Father who sent me is with me.

[[v43-8-17]]

^<<v43-8-17,17>>^ Also, in your own Law it is written: ‘The witness of two men is true.’

[[v43-8-18]]

^<<v43-8-18,18>>^ I am one who bears witness about myself, and the Father who sent me bears witness about me.”

[[v43-8-19]]

^<<v43-8-19,19>>^ Then they said to him: “Where is your Father?” Jesus answered: “You know neither me nor my Father. If you did know me, you would know my Father also.”

[[v43-8-20]]

^<<v43-8-20,20>>^ He spoke these words in the treasury as he was teaching in the temple. But no one seized him, for his hour had not yet come.

[[v43-8-21]]

^<<v43-8-21,21>>^ So he said to them again: “I am going away, and you will look for me, and yet you will die in your sin. Where I am going, you cannot come.”

[[v43-8-22]]

^<<v43-8-22,22>>^ The Jews then began to say: “He will not kill himself, will he? Because he says, ‘Where I am going, you cannot come.’”

[[v43-8-23]]

^<<v43-8-23,23>>^ He went on to say to them: “You are from the realms below; I am from the realms above. You are from this world; I am not from this world.

[[v43-8-24]]

^<<v43-8-24,24>>^ That is why I said to you: You will die in your sins. For if you do not believe that I am the one, you will die in your sins.”

[[v43-8-25]]

^<<v43-8-25,25>>^ So they began to say to him: “Who are you?” Jesus replied to them: “Why am I even speaking to you at all?

[[v43-8-26]]

^<<v43-8-26,26>>^ I have many things to speak concerning you and to pass judgment on. As a matter of fact, the One who sent me is true, and the very things I heard from him I am speaking in the world.”

[[v43-8-27]]

^<<v43-8-27,27>>^ They did not grasp that he was talking to them about the Father.

[[v43-8-28]]

^<<v43-8-28,28>>^ Jesus then said: “After you have lifted up the Son of man, then you will know that I am he and that I do nothing of my own initiative; but just as the Father taught me, I speak these things.

[[v43-8-29]]

^<<v43-8-29,29>>^ And the One who sent me is with me; he did not abandon me to myself, because I always do the things pleasing to him.”

[[v43-8-30]]

^<<v43-8-30,30>>^ As he was saying these things, many put faith in him.

[[v43-8-31]]

^<<v43-8-31,31>>^ Then Jesus went on to say to the Jews who had believed him: “If you remain in my word, you are really my disciples,

[[v43-8-32]]

^<<v43-8-32,32>>^ and you will know the truth, and the truth will set you free.”

[[v43-8-33]]

^<<v43-8-33,33>>^ They replied to him: “We are Abraham’s offspring and never have been slaves to anyone. How is it you say, ‘You will become free’?”

[[v43-8-34]]

^<<v43-8-34,34>>^ Jesus answered them: “Most truly I say to you, every doer of sin is a slave of sin.

[[v43-8-35]]

^<<v43-8-35,35>>^ Moreover, the slave does not remain in the household forever; the son remains forever.

[[v43-8-36]]

^<<v43-8-36,36>>^ So if the Son sets you free, you will be truly free.

[[v43-8-37]]

^<<v43-8-37,37>>^ I know that you are Abraham’s offspring. But you are seeking to kill me, because my word makes no progress among you.

[[v43-8-38]]

^<<v43-8-38,38>>^ I speak the things I have seen while with my Father, but you do the things you have heard from your father.”

[[v43-8-39]]

^<<v43-8-39,39>>^ In answer they said to him: “Our father is Abraham.” Jesus said to them: “If you were Abraham’s children, you would be doing the works of Abraham.

[[v43-8-40]]

^<<v43-8-40,40>>^ But now you are seeking to kill me, a man who has told you the truth that I heard from God. Abraham did not do this.

[[v43-8-41]]

^<<v43-8-41,41>>^ You are doing the works of your father.” They said to him: “We were not born from immorality;^&#42;1^ we have one Father, God.”

[NOTE]
====
. Or “sexual immorality.” Greek, por·neiʹa. See Glossary.
====

[[v43-8-42]]

^<<v43-8-42,42>>^ Jesus said to them: “If God were your Father, you would love me, for I came from God and I am here. I have not come of my own initiative, but that One sent me.

[[v43-8-43]]

^<<v43-8-43,43>>^ Why do you not understand what I am saying? Because you cannot listen to my word.

[[v43-8-44]]

^<<v43-8-44,44>>^ You are from your father the Devil, and you wish to do the desires of your father. That one was a murderer when he began,^&#42;1^ and he did not stand fast in the truth, because truth is not in him. When he speaks the lie, he speaks according to his own disposition, because he is a liar and the father of the lie.

[NOTE]
====
. Or “from the beginning.”
====

[[v43-8-45]]

^<<v43-8-45,45>>^ Because I, on the other hand, tell you the truth, you do not believe me.

[[v43-8-46]]

^<<v43-8-46,46>>^ Who of you convicts me of sin? If I speak truth, why is it that you do not believe me?

[[v43-8-47]]

^<<v43-8-47,47>>^ The one who is from God listens to the sayings of God. This is why you do not listen, because you are not from God.”

[[v43-8-48]]

^<<v43-8-48,48>>^ In answer the Jews said to him: “Are we not right in saying, ‘You are a Sa·marʹi·tan and have a demon’?”

[[v43-8-49]]

^<<v43-8-49,49>>^ Jesus answered: “I do not have a demon, but I honor my Father, and you dishonor me.

[[v43-8-50]]

^<<v43-8-50,50>>^ But I am not seeking glory for myself; there is One who is seeking and judging.

[[v43-8-51]]

^<<v43-8-51,51>>^ Most truly I say to you, if anyone observes my word, he will never see death at all.”

[[v43-8-52]]

^<<v43-8-52,52>>^ The Jews said to him: “Now we do know that you have a demon. Abraham died, also the prophets, but you say, ‘If anyone observes my word, he will never taste death at all.’

[[v43-8-53]]

^<<v43-8-53,53>>^ You are not greater than our father Abraham, who died, are you? The prophets also died. Who do you claim to be?”

[[v43-8-54]]

^<<v43-8-54,54>>^ Jesus answered: “If I glorify myself, my glory is nothing. It is my Father who glorifies me, the one who you say is your God.

[[v43-8-55]]

^<<v43-8-55,55>>^ Yet you have not known him, but I know him. And if I said I do not know him, I would be like you, a liar. But I do know him and am observing his word.

[[v43-8-56]]

^<<v43-8-56,56>>^ Abraham your father rejoiced greatly at the prospect of seeing my day, and he saw it and rejoiced.”

[[v43-8-57]]

^<<v43-8-57,57>>^ Then the Jews said to him: “You are not yet 50 years old, and still you have seen Abraham?”

[[v43-8-58]]

^<<v43-8-58,58>>^ Jesus said to them: “Most truly I say to you, before Abraham came into existence, I have been.”

[[v43-8-59]]

^<<v43-8-59,59>>^ So they picked up stones to throw at him, but Jesus hid and went out of the temple.

'''

xref:043-john/043-john-007.adoc#v43-7-0[&#60; Capítulo Anterior] | <<v43-8-0,Topo>> | xref:043-john/043-john-009.adoc#v43-9-0[Próximo Capítulo &#62;]