include::./index.adoc[]

[[v43-10-0]]
=== According to John, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-10-1]]

^<<v43-10-1,1>>^ “Most truly I say to you, the one who does not enter into the sheepfold through the door but climbs in by another way, that one is a thief and a plunderer.

[[v43-10-2]]

^<<v43-10-2,2>>^ But the one who enters through the door is the shepherd of the sheep.

[[v43-10-3]]

^<<v43-10-3,3>>^ The doorkeeper opens to this one, and the sheep listen to his voice. He calls his own sheep by name and leads them out.

[[v43-10-4]]

^<<v43-10-4,4>>^ When he has brought all his own out, he goes ahead of them, and the sheep follow him, because they know his voice.

[[v43-10-5]]

^<<v43-10-5,5>>^ They will by no means follow a stranger but will flee from him, because they do not know the voice of strangers.”

[[v43-10-6]]

^<<v43-10-6,6>>^ Jesus spoke this comparison to them, but they did not understand what he was saying to them.

[[v43-10-7]]

^<<v43-10-7,7>>^ So Jesus said again: “Most truly I say to you, I am the door for the sheep.

[[v43-10-8]]

^<<v43-10-8,8>>^ All those who have come in place of me are thieves and plunderers; but the sheep have not listened to them.

[[v43-10-9]]

^<<v43-10-9,9>>^ I am the door; whoever enters through me will be saved, and that one will go in and out and find pasturage.

[[v43-10-10]]

^<<v43-10-10,10>>^ The thief does not come unless it is to steal and slay and destroy. I have come that they may have life and have it in abundance.

[[v43-10-11]]

^<<v43-10-11,11>>^ I am the fine shepherd; the fine shepherd surrenders his life^&#42;1^ in behalf of the sheep.

[NOTE]
====
. Or “soul.”
====

[[v43-10-12]]

^<<v43-10-12,12>>^ The hired man, who is not a shepherd and to whom the sheep do not belong, sees the wolf coming and abandons the sheep and flees—and the wolf snatches them and scatters them—

[[v43-10-13]]

^<<v43-10-13,13>>^ because he is a hired man and does not care for the sheep.

[[v43-10-14]]

^<<v43-10-14,14>>^ I am the fine shepherd. I know my sheep and my sheep know me,

[[v43-10-15]]

^<<v43-10-15,15>>^ just as the Father knows me and I know the Father; and I surrender my life^&#42;1^ in behalf of the sheep.

[NOTE]
====
. Or “soul.”
====

[[v43-10-16]]

^<<v43-10-16,16>>^ “And I have other sheep, which are not of this fold; those too I must bring in, and they will listen to my voice, and they will become one flock, one shepherd.

[[v43-10-17]]

^<<v43-10-17,17>>^ This is why the Father loves me, because I surrender my life,^&#42;1^ so that I may receive it again.

[NOTE]
====
. Or “soul.”
====

[[v43-10-18]]

^<<v43-10-18,18>>^ No man takes it away from me, but I surrender it of my own initiative. I have authority to surrender it, and I have authority to receive it again. This commandment I received from my Father.”

[[v43-10-19]]

^<<v43-10-19,19>>^ A division again resulted among the Jews because of these words.

[[v43-10-20]]

^<<v43-10-20,20>>^ Many of them were saying: “He has a demon and is out of his mind. Why do you listen to him?”

[[v43-10-21]]

^<<v43-10-21,21>>^ Others said: “These are not the sayings of a demonized man. A demon cannot open blind people’s eyes, can it?”

[[v43-10-22]]

^<<v43-10-22,22>>^ At that time the Festival of Dedication took place in Jerusalem. It was wintertime,

[[v43-10-23]]

^<<v43-10-23,23>>^ and Jesus was walking in the temple in the colonnade of Solʹo·mon.

[[v43-10-24]]

^<<v43-10-24,24>>^ Then the Jews surrounded him and began to say to him: “How long are you going to keep us^&#42;1^ in suspense? If you are the Christ, tell us plainly.”

[NOTE]
====
. Or “our souls.”
====

[[v43-10-25]]

^<<v43-10-25,25>>^ Jesus answered them: “I told you, and yet you do not believe. The works that I am doing in my Father’s name, these bear witness about me.

[[v43-10-26]]

^<<v43-10-26,26>>^ But you do not believe, because you are not my sheep.

[[v43-10-27]]

^<<v43-10-27,27>>^ My sheep listen to my voice, and I know them, and they follow me.

[[v43-10-28]]

^<<v43-10-28,28>>^ I give them everlasting life, and they will by no means ever be destroyed, and no one will snatch them out of my hand.

[[v43-10-29]]

^<<v43-10-29,29>>^ What my Father has given me is something greater than all other things, and no one can snatch them out of the hand of the Father.

[[v43-10-30]]

^<<v43-10-30,30>>^ I and the Father are one.”^&#42;1^

[NOTE]
====
. Or “at unity.”
====

[[v43-10-31]]

^<<v43-10-31,31>>^ Once again the Jews picked up stones to stone him.

[[v43-10-32]]

^<<v43-10-32,32>>^ Jesus replied to them: “I displayed to you many fine works from the Father. For which of those works are you stoning me?”

[[v43-10-33]]

^<<v43-10-33,33>>^ The Jews answered him: “We are stoning you, not for a fine work, but for blasphemy; for you, although being a man, make yourself a god.”

[[v43-10-34]]

^<<v43-10-34,34>>^ Jesus answered them: “Is it not written in your Law, ‘I said: “You are gods”’?^&#42;1^

[NOTE]
====
. Or “godlike ones.”
====

[[v43-10-35]]

^<<v43-10-35,35>>^ If he called ‘gods’ those against whom the word of God came—and yet the scripture cannot be nullified—

[[v43-10-36]]

^<<v43-10-36,36>>^ do you say to me whom the Father sanctified and sent into the world, ‘You blaspheme,’ because I said, ‘I am God’s Son’?

[[v43-10-37]]

^<<v43-10-37,37>>^ If I am not doing the works of my Father, do not believe me.

[[v43-10-38]]

^<<v43-10-38,38>>^ But if I am doing them, even though you do not believe me, believe the works, so that you may come to know and may continue knowing that the Father is in union with me and I am in union with the Father.”

[[v43-10-39]]

^<<v43-10-39,39>>^ So they tried again to seize him, but he escaped from their reach.

[[v43-10-40]]

^<<v43-10-40,40>>^ And he went away again across the Jordan to the place where John was baptizing at first, and he stayed there.

[[v43-10-41]]

^<<v43-10-41,41>>^ And many people came to him and began saying: “John did not perform a single sign, but all the things John said about this man were true.”

[[v43-10-42]]

^<<v43-10-42,42>>^ And many put faith in him there.

'''

xref:043-john/043-john-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-john/043-john-011.adoc#v43-11-0[Próximo Capítulo &#62;]