include::./index.adoc[]

[[v43-13-0]]
=== According to John, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-13-1]]

^<<v43-13-1,1>>^ Now because he knew before the festival of the Passover that his hour had come for him to leave this world and go to the Father, Jesus, having loved his own who were in the world, loved them to the end.

[[v43-13-2]]

^<<v43-13-2,2>>^ The evening meal was going on, and the Devil had already put it into the heart of Judas Is·carʹi·ot, the son of Simon, to betray him.

[[v43-13-3]]

^<<v43-13-3,3>>^ So Jesus, knowing that the Father had given all things into his hands and that he came from God and was going to God,

[[v43-13-4]]

^<<v43-13-4,4>>^ got up from the evening meal and laid aside his outer garments. And taking a towel, he wrapped it around his waist.^&#42;1^

[NOTE]
====
. Or “girded himself.”
====

[[v43-13-5]]

^<<v43-13-5,5>>^ After that he put water into a basin and started to wash the feet of the disciples and to dry them off with the towel that was wrapped around him.^&#42;1^

[NOTE]
====
. Or “with which he was girded.”
====

[[v43-13-6]]

^<<v43-13-6,6>>^ Then he came to Simon Peter. He said to him: “Lord, are you washing my feet?”

[[v43-13-7]]

^<<v43-13-7,7>>^ Jesus answered him: “What I am doing you do not understand now, but you will understand after these things.”

[[v43-13-8]]

^<<v43-13-8,8>>^ Peter said to him: “You will certainly never wash my feet.” Jesus answered him: “Unless I wash you, you have no share with me.”

[[v43-13-9]]

^<<v43-13-9,9>>^ Simon Peter said to him: “Lord, wash not only my feet but also my hands and my head.”

[[v43-13-10]]

^<<v43-13-10,10>>^ Jesus said to him: “Whoever has bathed does not need to have more than his feet washed, but is completely clean. And you men are clean, but not all of you.”

[[v43-13-11]]

^<<v43-13-11,11>>^ For he knew the man who was betraying him. This is why he said: “Not all of you are clean.”

[[v43-13-12]]

^<<v43-13-12,12>>^ When, now, he had washed their feet and had put his outer garments on, he again reclined at the table and said to them: “Do you understand what I have done to you?

[[v43-13-13]]

^<<v43-13-13,13>>^ You address me as ‘Teacher’ and ‘Lord,’ and you are correct, for I am such.

[[v43-13-14]]

^<<v43-13-14,14>>^ Therefore, if I, the Lord and Teacher, washed your feet, you also should^&#42;1^ wash the feet of one another.

[NOTE]
====
. Or “you also are under obligation to.”
====

[[v43-13-15]]

^<<v43-13-15,15>>^ For I set the pattern for you, that just as I did to you, you should also do.

[[v43-13-16]]

^<<v43-13-16,16>>^ Most truly I say to you, a slave is not greater than his master, nor is one who is sent greater than the one who sent him.

[[v43-13-17]]

^<<v43-13-17,17>>^ If you know these things, happy you are if you do them.

[[v43-13-18]]

^<<v43-13-18,18>>^ I am not talking about all of you; I know the ones I have chosen. But this was so that the scripture might be fulfilled: ‘The one who was eating my bread has lifted his heel against me.’^&#42;1^

[NOTE]
====
. Or “has turned against me.”
====

[[v43-13-19]]

^<<v43-13-19,19>>^ From this moment on, I am telling you before it occurs, so that when it does occur you may believe that I am he.

[[v43-13-20]]

^<<v43-13-20,20>>^ Most truly I say to you, whoever receives anyone I send receives me also, and whoever receives me receives also the One who sent me.”

[[v43-13-21]]

^<<v43-13-21,21>>^ After saying these things, Jesus became troubled in spirit, and he bore witness, saying: “Most truly I say to you, one of you will betray me.”

[[v43-13-22]]

^<<v43-13-22,22>>^ The disciples began to look at one another, being at a loss as to which one he was talking about.

[[v43-13-23]]

^<<v43-13-23,23>>^ One of the disciples, the one whom Jesus loved, was reclining close to^&#42;1^ Jesus.

[NOTE]
====
. Lit., “in the bosom of.”
====

[[v43-13-24]]

^<<v43-13-24,24>>^ Therefore, Simon Peter nodded to this one and said to him: “Tell us whom he is talking about.”

[[v43-13-25]]

^<<v43-13-25,25>>^ So the latter leaned back on the chest of Jesus and said to him: “Lord, who is it?”

[[v43-13-26]]

^<<v43-13-26,26>>^ Jesus answered: “It is the one to whom I will give the piece of bread that I dip.” So after dipping the bread, he took it and gave it to Judas, the son of Simon Is·carʹi·ot.

[[v43-13-27]]

^<<v43-13-27,27>>^ After Judas took the piece of bread, then Satan entered into him. So Jesus said to him: “What you are doing, do it more quickly.”

[[v43-13-28]]

^<<v43-13-28,28>>^ However, none of those reclining at the table knew why he said this to him.

[[v43-13-29]]

^<<v43-13-29,29>>^ Some, in fact, were thinking that since Judas was holding the money box, Jesus was telling him, “Buy what we need for the festival,” or that he should give something to the poor.

[[v43-13-30]]

^<<v43-13-30,30>>^ So after he received the piece of bread, he went out immediately. And it was night.

[[v43-13-31]]

^<<v43-13-31,31>>^ When, therefore, he had gone out, Jesus said: “Now the Son of man is glorified, and God is glorified in connection with him.

[[v43-13-32]]

^<<v43-13-32,32>>^ God himself will glorify him, and he will glorify him immediately.

[[v43-13-33]]

^<<v43-13-33,33>>^ Little children, I am with you a little longer. You will look for me; and just as I said to the Jews, ‘Where I go you cannot come,’ I now say it also to you.

[[v43-13-34]]

^<<v43-13-34,34>>^ I am giving you a new commandment, that you love one another; just as I have loved you, you also love one another.

[[v43-13-35]]

^<<v43-13-35,35>>^ By this all will know that you are my disciples—if you have love among yourselves.”

[[v43-13-36]]

^<<v43-13-36,36>>^ Simon Peter said to him: “Lord, where are you going?” Jesus answered: “Where I am going, you cannot follow me now, but you will follow later.”

[[v43-13-37]]

^<<v43-13-37,37>>^ Peter said to him: “Lord, why is it I cannot follow you now? I will surrender my life^&#42;1^ in your behalf.”

[NOTE]
====
. Or “soul.”
====

[[v43-13-38]]

^<<v43-13-38,38>>^ Jesus answered: “Will you surrender your life^&#42;1^ in my behalf? Most truly I say to you, a rooster will by no means crow until you have disowned me three times.”

[NOTE]
====
. Or “soul.”
====

'''

xref:043-john/043-john-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-john/043-john-014.adoc#v43-14-0[Próximo Capítulo &#62;]