include::./index.adoc[]

[[v43-1-0]]
=== According to John, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v43-1-1]]

^<<v43-1-1,1>>^ In the beginning was the Word, and the Word was with God, and the Word was a god.^&#42;1^

[NOTE]
====
. Or “was divine.”
====

[[v43-1-2]]

^<<v43-1-2,2>>^ This one was in the beginning with God.

[[v43-1-3]]

^<<v43-1-3,3>>^ All things came into existence through him, and apart from him not even one thing came into existence.
What has come into existence

[[v43-1-4]]

^<<v43-1-4,4>>^ by means of him was life, and the life was the light of men.

[[v43-1-5]]

^<<v43-1-5,5>>^ And the light is shining in the darkness, but the darkness has not overpowered it.

[[v43-1-6]]

^<<v43-1-6,6>>^ There came a man who was sent as a representative of God; his name was John.

[[v43-1-7]]

^<<v43-1-7,7>>^ This man came as a witness, in order to bear witness about the light, so that people of all sorts might believe through him.

[[v43-1-8]]

^<<v43-1-8,8>>^ He was not that light, but he was meant to bear witness about that light.

[[v43-1-9]]

^<<v43-1-9,9>>^ The true light that gives light to every sort of man was about to come into the world.

[[v43-1-10]]

^<<v43-1-10,10>>^ He was in the world, and the world came into existence through him, but the world did not know him.

[[v43-1-11]]

^<<v43-1-11,11>>^ He came to his own home, but his own people did not accept him.

[[v43-1-12]]

^<<v43-1-12,12>>^ However, to all who did receive him, he gave authority to become God’s children, because they were exercising faith in his name.

[[v43-1-13]]

^<<v43-1-13,13>>^ And they were born, not from blood or from a fleshly will or from man’s will, but from God.

[[v43-1-14]]

^<<v43-1-14,14>>^ So the Word became flesh and resided among us, and we had a view of his glory, a glory such as belongs to an only-begotten son from a father; and he was full of divine favor^&#42;1^ and truth.

[NOTE]
====
. Or “of undeserved kindness.”
====

[[v43-1-15]]

^<<v43-1-15,15>>^ (John bore witness about him, yes, he cried out: “This was the one of whom I said, ‘The one coming behind me has advanced in front of me, for he existed before me.’”)

[[v43-1-16]]

^<<v43-1-16,16>>^ For we all received from his fullness, even undeserved kindness upon undeserved kindness.

[[v43-1-17]]

^<<v43-1-17,17>>^ Because the Law was given through Moses, the undeserved kindness and the truth came to be through Jesus Christ.

[[v43-1-18]]

^<<v43-1-18,18>>^ No man has seen God at any time; the only-begotten god who is at the Father’s side^&#42;1^ is the one who has explained Him.

[NOTE]
====
. Or “in the bosom position with the Father.” This refers to a position of special favor.
====

[[v43-1-19]]

^<<v43-1-19,19>>^ This is the witness John gave when the Jews sent priests and Levites from Jerusalem to ask him: “Who are you?”

[[v43-1-20]]

^<<v43-1-20,20>>^ And he admitted it and did not deny it, saying: “I am not the Christ.”

[[v43-1-21]]

^<<v43-1-21,21>>^ And they asked him: “What, then? Are you E·liʹjah?” He replied: “I am not.” “Are you the Prophet?” And he answered: “No!”

[[v43-1-22]]

^<<v43-1-22,22>>^ So they said to him: “Who are you? Tell us so that we may give an answer to those who sent us. What do you say about yourself?”

[[v43-1-23]]

^<<v43-1-23,23>>^ He said: “I am a voice of someone crying out in the wilderness, ‘Make the way of Jehovah^&#42;1^ straight,’ just as Isaiah the prophet said.”

[NOTE]
====
. See App. A5.
====

[[v43-1-24]]

^<<v43-1-24,24>>^ Now those sent were from the Pharisees.

[[v43-1-25]]

^<<v43-1-25,25>>^ So they questioned him and said to him: “Why, then, do you baptize if you are not the Christ or E·liʹjah or the Prophet?”

[[v43-1-26]]

^<<v43-1-26,26>>^ John answered them: “I baptize in water. One is standing among you whom you do not know,

[[v43-1-27]]

^<<v43-1-27,27>>^ the one coming behind me, the lace of whose sandal I am not worthy to untie.”

[[v43-1-28]]

^<<v43-1-28,28>>^ These things took place in Bethʹa·ny across the Jordan, where John was baptizing.

[[v43-1-29]]

^<<v43-1-29,29>>^ The next day he saw Jesus coming toward him, and he said: “See, the Lamb of God who takes away the sin of the world!

[[v43-1-30]]

^<<v43-1-30,30>>^ This is the one about whom I said: ‘Behind me there comes a man who has advanced in front of me, for he existed before me.’

[[v43-1-31]]

^<<v43-1-31,31>>^ Even I did not know him, but the reason why I came baptizing in water was so that he might be made manifest to Israel.”

[[v43-1-32]]

^<<v43-1-32,32>>^ John also bore witness, saying: “I viewed the spirit coming down as a dove out of heaven, and it remained upon him.

[[v43-1-33]]

^<<v43-1-33,33>>^ Even I did not know him, but the very One who sent me to baptize in water said to me: ‘Whoever it is upon whom you see the spirit coming down and remaining, this is the one who baptizes in holy spirit.’

[[v43-1-34]]

^<<v43-1-34,34>>^ And I have seen it, and I have given witness that this one is the Son of God.”

[[v43-1-35]]

^<<v43-1-35,35>>^ Again the next day, John was standing with two of his disciples,

[[v43-1-36]]

^<<v43-1-36,36>>^ and as he looked at Jesus walking, he said: “See, the Lamb of God!”

[[v43-1-37]]

^<<v43-1-37,37>>^ When the two disciples heard him say this, they followed Jesus.

[[v43-1-38]]

^<<v43-1-38,38>>^ Then Jesus turned, and seeing them following, he said to them: “What are you looking for?” They said to him: “Rabbi (which means, when translated, “Teacher”), where are you staying?”

[[v43-1-39]]

^<<v43-1-39,39>>^ He said to them: “Come, and you will see.” So they went and saw where he was staying, and they stayed with him that day; it was about the tenth hour.^&#42;1^

[NOTE]
====
. That is, about 4:00 p.m.
====

[[v43-1-40]]

^<<v43-1-40,40>>^ Andrew, the brother of Simon Peter, was one of the two who heard what John said and followed Jesus.

[[v43-1-41]]

^<<v43-1-41,41>>^ He first found his own brother Simon and said to him: “We have found the Mes·siʹah” (which means, when translated, “Christ”),

[[v43-1-42]]

^<<v43-1-42,42>>^ and he led him to Jesus. When Jesus looked at him, he said: “You are Simon, the son of John; you will be called Ceʹphas” (which is translated “Peter”).

[[v43-1-43]]

^<<v43-1-43,43>>^ The next day he wanted to leave for Galʹi·lee. Jesus then found Philip and said to him: “Be my follower.”

[[v43-1-44]]

^<<v43-1-44,44>>^ Now Philip was from Beth·saʹi·da, from the city of Andrew and Peter.

[[v43-1-45]]

^<<v43-1-45,45>>^ Philip found Na·thanʹa·el and said to him: “We have found the one of whom Moses, in the Law, and the Prophets wrote: Jesus, the son of Joseph, from Nazʹa·reth.”

[[v43-1-46]]

^<<v43-1-46,46>>^ But Na·thanʹa·el said to him: “Can anything good come out of Nazʹa·reth?” Philip said to him: “Come and see.”

[[v43-1-47]]

^<<v43-1-47,47>>^ Jesus saw Na·thanʹa·el coming toward him and said about him: “See, truly an Israelite in whom there is no deceit.”

[[v43-1-48]]

^<<v43-1-48,48>>^ Na·thanʹa·el said to him: “How do you know me?” Jesus answered him: “Before Philip called you, while you were under the fig tree, I saw you.”

[[v43-1-49]]

^<<v43-1-49,49>>^ Na·thanʹa·el responded: “Rabbi, you are the Son of God, you are King of Israel.”

[[v43-1-50]]

^<<v43-1-50,50>>^ Jesus answered him: “Do you believe because I told you I saw you under the fig tree? You will see things greater than these.”

[[v43-1-51]]

^<<v43-1-51,51>>^ He then said to him: “Most truly I say to you men, you will see heaven opened up and the angels of God ascending and descending to the Son of man.”

'''

xref:042-luke/042-luke-024.adoc#v42-24-0[&#60; Capítulo Anterior] | <<v43-1-0,Topo>> | xref:043-john/043-john-002.adoc#v43-2-0[Próximo Capítulo &#62;]