include::./index.adoc[]

[[v20-1-0]]
=== Proverbs, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v20-1-1]]

^<<v20-1-1,1>>^ The proverbs of Solʹo·mon, the son of David, the king of Israel:

[[v20-1-2]]

^<<v20-1-2,2>>^ To learn^&#42;1^ wisdom and discipline;
To understand wise sayings;

[NOTE]
====
. Lit., “To know.”
====

[[v20-1-3]]

^<<v20-1-3,3>>^ To acquire the discipline that gives insight,
Righteousness, good judgment,^&#42;1^ and uprightness;^&#42;2^

[NOTE]
====
. Or “what is just.”
. Or “fairness.”
====

[[v20-1-4]]

^<<v20-1-4,4>>^ To impart shrewdness to the inexperienced;
To give a young man knowledge and thinking ability.

[[v20-1-5]]

^<<v20-1-5,5>>^ A wise person listens and takes in more instruction;
A man of understanding acquires skillful direction^&#42;1^

[NOTE]
====
. Or “wise guidance.”
====

[[v20-1-6]]

^<<v20-1-6,6>>^ To understand a proverb and a puzzling saying,^&#42;1^
The words of the wise and their riddles.

[NOTE]
====
. Or “a parable.”
====

[[v20-1-7]]

^<<v20-1-7,7>>^ The fear of^&#42;1^ Jehovah is the beginning of knowledge.
Only fools despise wisdom and discipline.

[NOTE]
====
. Or “reverence for.”
====

[[v20-1-8]]

^<<v20-1-8,8>>^ Listen, my son, to the discipline of your father,
And do not forsake the instruction^&#42;1^ of your mother.

[NOTE]
====
. Or “law.”
====

[[v20-1-9]]

^<<v20-1-9,9>>^ They are an attractive wreath for your head
And a fine ornament for your neck.

[[v20-1-10]]

^<<v20-1-10,10>>^ My son, if sinners try to entice you, do not consent.

[[v20-1-11]]

^<<v20-1-11,11>>^ If they say: “Come with us.
Let us set an ambush to shed blood.
We will lie hidden, waiting for innocent victims without cause.

[[v20-1-12]]

^<<v20-1-12,12>>^ We will swallow them alive as the Grave^&#42;1^ does,
Whole, like those going down to the pit.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v20-1-13]]

^<<v20-1-13,13>>^ Let us seize all their precious treasures;
We will fill our houses with spoil.

[[v20-1-14]]

^<<v20-1-14,14>>^ You should join us,^&#42;1^
And we will all share equally what we steal.”^&#42;2^

[NOTE]
====
. Or “Throw in your lot with us.”
. Or “share a common bag (purse).”
====

[[v20-1-15]]

^<<v20-1-15,15>>^ My son, do not follow them.
Keep your feet off their path,

[[v20-1-16]]

^<<v20-1-16,16>>^ For their feet run to do evil;
They hurry to shed blood.

[[v20-1-17]]

^<<v20-1-17,17>>^ It is surely in vain to spread a net in full sight of a bird.

[[v20-1-18]]

^<<v20-1-18,18>>^ That is why these lie in ambush to shed blood;
They lie hidden to take the lives^&#42;1^ of others.

[NOTE]
====
. Or “souls.”
====

[[v20-1-19]]

^<<v20-1-19,19>>^ These are the ways of those seeking dishonest profit,
Which will take away the life^&#42;1^ of those who obtain it.

[NOTE]
====
. Or “soul.”
====

[[v20-1-20]]

^<<v20-1-20,20>>^ True wisdom cries aloud in the street.
It keeps raising its voice in the public squares.

[[v20-1-21]]

^<<v20-1-21,21>>^ At the corner^&#42;1^ of the busy streets it calls out.
At the entrances of the city gates it says:

[NOTE]
====
. Lit., “head.”
====

[[v20-1-22]]

^<<v20-1-22,22>>^ “How long will you inexperienced ones love inexperience?
How long will you ridiculers take pleasure in ridicule?
And how long will you foolish ones hate knowledge?

[[v20-1-23]]

^<<v20-1-23,23>>^ Respond to my reproof.^&#42;1^
Then I will pour out my spirit for you;
I will make my words known to you.

[NOTE]
====
. Or “Turn back when I reprove.”
====

[[v20-1-24]]

^<<v20-1-24,24>>^ Because I called out, but you kept refusing,
I stretched out my hand, but no one was paying attention,

[[v20-1-25]]

^<<v20-1-25,25>>^ You kept neglecting all my advice
And rejecting my reproof,

[[v20-1-26]]

^<<v20-1-26,26>>^ I also will laugh when disaster strikes you;
I will mock when what you dread comes,

[[v20-1-27]]

^<<v20-1-27,27>>^ When what you dread comes like a storm,
And your disaster arrives like a storm wind,
When distress and trouble come upon you.

[[v20-1-28]]

^<<v20-1-28,28>>^ At that time they will keep calling me, but I will not answer;
They will eagerly look for me, but they will not find me,

[[v20-1-29]]

^<<v20-1-29,29>>^ Because they hated knowledge,
And they did not choose to fear Jehovah.

[[v20-1-30]]

^<<v20-1-30,30>>^ They refused my advice;
They disrespected all my reproof.

[[v20-1-31]]

^<<v20-1-31,31>>^ So they will bear the consequences^&#42;1^ of their way,
And they will be glutted with their own counsel.^&#42;2^

[NOTE]
====
. Lit., “eat from the fruit.”
. Or “schemes; plans.”
====

[[v20-1-32]]

^<<v20-1-32,32>>^ For the waywardness of the inexperienced will kill them,
And the complacency of fools will destroy them.

[[v20-1-33]]

^<<v20-1-33,33>>^ But the one listening to me will dwell in security
And be undisturbed by the dread of calamity.”

'''

xref:019-psalm/019-psalm-150.adoc#v19-150-0[&#60; Capítulo Anterior] | <<v20-1-0,Topo>> | xref:020-proverbs/020-proverbs-002.adoc#v20-2-0[Próximo Capítulo &#62;]