include::./index.adoc[]

[[v20-16-0]]
=== Proverbs, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v20-16-1]]

^<<v20-16-1,1>>^ A man prepares the thoughts of his heart,^&#42;1^
But the answer he gives^&#42;2^ is from Jehovah.

[NOTE]
====
. Lit., “The arrangings of the heart belong to a man.”
. Or “the right answer.” Lit., “the answer of the tongue.”
====

[[v20-16-2]]

^<<v20-16-2,2>>^ All of a man’s ways seem right^&#42;1^ to him,
But Jehovah examines the motives.^&#42;2^

[NOTE]
====
. Lit., “pure.”
. Lit., “spirits.”
====

[[v20-16-3]]

^<<v20-16-3,3>>^ Commit to Jehovah whatever you do,^&#42;1^
And your plans will succeed.

[NOTE]
====
. Lit., “Roll to Jehovah your works.”
====

[[v20-16-4]]

^<<v20-16-4,4>>^ Jehovah has made everything work for his purpose,
Even the wicked for the day of disaster.

[[v20-16-5]]

^<<v20-16-5,5>>^ Everyone proud in heart is detestable to Jehovah.
Be assured^&#42;1^ that he will not go unpunished.

[NOTE]
====
. Lit., “Hand to hand.”
====

[[v20-16-6]]

^<<v20-16-6,6>>^ By loyal love and faithfulness, error is atoned for,
And by fearing Jehovah one turns away from bad.

[[v20-16-7]]

^<<v20-16-7,7>>^ When Jehovah is pleased with a man’s ways,
He causes even his enemies to be at peace with him.

[[v20-16-8]]

^<<v20-16-8,8>>^ Better is a little with righteousness
Than a large income without justice.

[[v20-16-9]]

^<<v20-16-9,9>>^ A man may plot out his course in his heart,
But it is Jehovah who directs his steps.

[[v20-16-10]]

^<<v20-16-10,10>>^ Inspired^&#42;1^ decision should be on the lips of a king;
He must never betray justice.

[NOTE]
====
. Or “Divine.”
====

[[v20-16-11]]

^<<v20-16-11,11>>^ Honest balances and scales are from Jehovah;
All the weights in the bag are his doing.

[[v20-16-12]]

^<<v20-16-12,12>>^ Wicked practices are detestable to kings,
For the throne is firmly established by righteousness.

[[v20-16-13]]

^<<v20-16-13,13>>^ Righteous speech is a pleasure to kings.
They love someone who speaks honestly.

[[v20-16-14]]

^<<v20-16-14,14>>^ The king’s rage is like a messenger of death,
But the wise man appeases^&#42;1^ it.

[NOTE]
====
. Or “avoids.”
====

[[v20-16-15]]

^<<v20-16-15,15>>^ In the light of the king’s face there is life;
His favor is like a cloud of rain in spring.

[[v20-16-16]]

^<<v20-16-16,16>>^ How much better to acquire wisdom than gold!
To gain understanding is to be chosen over silver.

[[v20-16-17]]

^<<v20-16-17,17>>^ The highway of the upright avoids what is bad.
Whoever safeguards his way preserves his life.^&#42;1^

[NOTE]
====
. Or “soul.”
====

[[v20-16-18]]

^<<v20-16-18,18>>^ Pride is before a crash,
And a haughty spirit before stumbling.

[[v20-16-19]]

^<<v20-16-19,19>>^ Better to be humble^&#42;1^ among the meek
Than to share the spoil of the haughty.

[NOTE]
====
. Lit., “lowly of spirit.”
====

[[v20-16-20]]

^<<v20-16-20,20>>^ The one who shows insight in a matter will find success,^&#42;1^
And happy is the one trusting in Jehovah.

[NOTE]
====
. Lit., “good.”
====

[[v20-16-21]]

^<<v20-16-21,21>>^ The wise in heart will be called understanding,
And the one kind in speech^&#42;1^ adds persuasiveness.

[NOTE]
====
. Or “And appealing speech.” Lit., “And sweetness of lips.”
====

[[v20-16-22]]

^<<v20-16-22,22>>^ Insight is a fountain of life to those possessing it,
But fools are disciplined by their own foolishness.

[[v20-16-23]]

^<<v20-16-23,23>>^ The heart of the wise one gives his mouth insight
And adds persuasiveness to his speech.

[[v20-16-24]]

^<<v20-16-24,24>>^ Pleasant sayings are a honeycomb,
Sweet to the soul^&#42;1^ and a healing to the bones.

[NOTE]
====
. Or “taste.” See Glossary.
====

[[v20-16-25]]

^<<v20-16-25,25>>^ There is a way that seems right to a man,
But in the end it leads to death.

[[v20-16-26]]

^<<v20-16-26,26>>^ The appetite^&#42;1^ of a laborer makes him work hard
For his hunger^&#42;2^ urges him on.

[NOTE]
====
. Or “soul.”
. Lit., “mouth.”
====

[[v20-16-27]]

^<<v20-16-27,27>>^ A worthless man digs up what is bad;
His speech is like a scorching fire.

[[v20-16-28]]

^<<v20-16-28,28>>^ A troublemaker^&#42;1^ causes dissension,
And a slanderer separates close friends.

[NOTE]
====
. Or “A schemer.”
====

[[v20-16-29]]

^<<v20-16-29,29>>^ A violent man entices his neighbor
And leads him in the wrong way.

[[v20-16-30]]

^<<v20-16-30,30>>^ He winks his eye as he schemes harm.
He pinches his lips together as he carries out mischief.

[[v20-16-31]]

^<<v20-16-31,31>>^ Gray hair is a crown of beauty^&#42;1^
When it is found in the way of righteousness.

[NOTE]
====
. Or “glory.”
====

[[v20-16-32]]

^<<v20-16-32,32>>^ The one slow to anger is better than a mighty man,
And the one controlling his temper^&#42;1^ than one conquering a city.

[NOTE]
====
. Lit., “ruling over his spirit.”
====

[[v20-16-33]]

^<<v20-16-33,33>>^ The lot is cast into the lap,
But every decision by it is from Jehovah.

'''

xref:020-proverbs/020-proverbs-015.adoc#v20-15-0[&#60; Capítulo Anterior] | <<v20-16-0,Topo>> | xref:020-proverbs/020-proverbs-017.adoc#v20-17-0[Próximo Capítulo &#62;]