include::./index.adoc[]

[[v20-19-0]]
=== Proverbs, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v20-19-1]]

^<<v20-19-1,1>>^ It is better to be poor and walk in integrity
Than to be stupid and speak lies.

[[v20-19-2]]

^<<v20-19-2,2>>^ A person^&#42;1^ without knowledge is not good,
And the one who acts rashly^&#42;2^ is sinning.

[NOTE]
====
. Or “soul.”
. Lit., “hastens with his feet.”
====

[[v20-19-3]]

^<<v20-19-3,3>>^ It is a man’s own foolishness that distorts his way,
And his heart becomes enraged against Jehovah.

[[v20-19-4]]

^<<v20-19-4,4>>^ Wealth attracts many friends,
But the poor man will be deserted even by his friend.

[[v20-19-5]]

^<<v20-19-5,5>>^ A false witness will not go unpunished,
And the one who lies with every breath will not escape.

[[v20-19-6]]

^<<v20-19-6,6>>^ Many seek the favor of a noble,^&#42;1^
And everyone is a friend to the man who gives gifts.

[NOTE]
====
. Or “generous man.”
====

[[v20-19-7]]

^<<v20-19-7,7>>^ All the brothers of a poor man hate him;
How much more he is shunned by his friends!
He pursues them with requests, but no one responds.

[[v20-19-8]]

^<<v20-19-8,8>>^ Whoever acquires good sense^&#42;1^ loves himself.^&#42;2^
Whoever treasures discernment will find success.^&#42;3^

[NOTE]
====
. Lit., “acquires heart.”
. Or “his soul.”
. Lit., “good.”
====

[[v20-19-9]]

^<<v20-19-9,9>>^ A false witness will not go unpunished,
And the one who lies with every breath will perish.

[[v20-19-10]]

^<<v20-19-10,10>>^ It is not fitting for a fool to live in luxury;
How much less for a servant to rule over princes!

[[v20-19-11]]

^<<v20-19-11,11>>^ The insight of a man certainly slows down his anger,
And it is beauty on his part to overlook^&#42;1^ an offense.^&#42;2^

[NOTE]
====
. Lit., “pass over.”
. Or “a transgression.”
====

[[v20-19-12]]

^<<v20-19-12,12>>^ The king’s rage is like the growling of a lion,^&#42;1^
But his favor is like dew on the vegetation.

[NOTE]
====
. Or “a maned young lion.”
====

[[v20-19-13]]

^<<v20-19-13,13>>^ A stupid son brings adversity on his father,
And a quarrelsome^&#42;1^ wife is like a roof that never stops leaking.

[NOTE]
====
. Or “nagging.”
====

[[v20-19-14]]

^<<v20-19-14,14>>^ A house and wealth are inherited from fathers,
But a discreet wife is from Jehovah.

[[v20-19-15]]

^<<v20-19-15,15>>^ Laziness brings on a deep sleep,
And a sluggish person^&#42;1^ will go hungry.

[NOTE]
====
. Or “soul.”
====

[[v20-19-16]]

^<<v20-19-16,16>>^ The one who keeps the commandment keeps his life;^&#42;1^
The one who is reckless about his ways will die.

[NOTE]
====
. Or “soul.”
====

[[v20-19-17]]

^<<v20-19-17,17>>^ The one showing favor to the lowly is lending to Jehovah,
And He will repay^&#42;1^ him for what he does.

[NOTE]
====
. Or “reward.”
====

[[v20-19-18]]

^<<v20-19-18,18>>^ Discipline your son while there is hope,
And do not become responsible for^&#42;1^ his death.

[NOTE]
====
. Or “desire.” Lit., “raise your soul to.”
====

[[v20-19-19]]

^<<v20-19-19,19>>^ The hot-tempered man will pay the penalty;
If you try to spare him, you will have to do it again and again.

[[v20-19-20]]

^<<v20-19-20,20>>^ Listen to counsel and accept discipline,
In order to become wise in your future.

[[v20-19-21]]

^<<v20-19-21,21>>^ Many are the plans in a man’s heart,
But the counsel^&#42;1^ of Jehovah is what will prevail.

[NOTE]
====
. Or “purpose.”
====

[[v20-19-22]]

^<<v20-19-22,22>>^ The desirable thing in a man is his loyal love;
And it is better to be poor than to be a liar.

[[v20-19-23]]

^<<v20-19-23,23>>^ The fear of Jehovah leads to life;
The one who has it will have a pleasant rest, free from harm.

[[v20-19-24]]

^<<v20-19-24,24>>^ The lazy one buries his hand in the banquet bowl,
But he does not even bother to bring it back to his mouth.

[[v20-19-25]]

^<<v20-19-25,25>>^ Strike the ridiculer, so that the inexperienced one may become shrewd,
And reprove the understanding one, so that he will increase in knowledge.

[[v20-19-26]]

^<<v20-19-26,26>>^ The one who mistreats his father and drives away his mother
Is a son causing shame and disgrace.

[[v20-19-27]]

^<<v20-19-27,27>>^ My son, if you stop listening to discipline,
You will stray from the sayings of knowledge.

[[v20-19-28]]

^<<v20-19-28,28>>^ A worthless witness mocks justice,
And the mouth of the wicked gulps down evil.

[[v20-19-29]]

^<<v20-19-29,29>>^ Judgment is in store for ridiculers,
And beatings for the back of the stupid ones.

'''

xref:020-proverbs/020-proverbs-018.adoc#v20-18-0[&#60; Capítulo Anterior] | <<v20-19-0,Topo>> | xref:020-proverbs/020-proverbs-020.adoc#v20-20-0[Próximo Capítulo &#62;]