include::./index.adoc[]

[[v20-17-0]]
=== Proverbs, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v20-17-1]]

^<<v20-17-1,1>>^ Better is a piece of dry bread where there is peace^&#42;1^
Than a house full of feasting^&#42;2^ along with quarreling.

[NOTE]
====
. Or “quietness.”
. Lit., “sacrifices.”
====

[[v20-17-2]]

^<<v20-17-2,2>>^ A servant with insight will rule over a son who acts shamefully;
He will share in the inheritance as one of the brothers.

[[v20-17-3]]

^<<v20-17-3,3>>^ The refining pot is for silver and the furnace for gold,
But Jehovah is the examiner of hearts.

[[v20-17-4]]

^<<v20-17-4,4>>^ A wicked man pays attention to hurtful speech,
And a deceptive man listens to a malicious tongue.

[[v20-17-5]]

^<<v20-17-5,5>>^ Whoever mocks the poor insults his Maker,
And whoever rejoices over another’s disaster will not go unpunished.

[[v20-17-6]]

^<<v20-17-6,6>>^ Grandsons^&#42;1^ are a crown to the aged,
And fathers^&#42;2^ are the glory of their sons.^&#42;3^

[NOTE]
====
. Or “Grandchildren.”
. Or “parents.”
. Or “children.”
====

[[v20-17-7]]

^<<v20-17-7,7>>^ Upright^&#42;1^ speech does not befit a fool.
How much less does false speech befit a ruler!^&#42;2^

[NOTE]
====
. Or “Fine.”
. Or “noble.”
====

[[v20-17-8]]

^<<v20-17-8,8>>^ A gift is like a precious stone^&#42;1^ to its owner;
Everywhere he turns, it brings him success.

[NOTE]
====
. Or “is a stone that brings favor.”
====

[[v20-17-9]]

^<<v20-17-9,9>>^ Whoever forgives^&#42;1^ a transgression seeks love,
But the one who keeps harping on a matter separates close friends.

[NOTE]
====
. Lit., “covers over.”
====

[[v20-17-10]]

^<<v20-17-10,10>>^ A rebuke makes a deeper impression on one having understanding
Than striking a stupid person a hundred times.

[[v20-17-11]]

^<<v20-17-11,11>>^ A bad man seeks only rebellion,
But a cruel messenger will be sent to punish him.

[[v20-17-12]]

^<<v20-17-12,12>>^ Better to meet a bear bereaved of her cubs
Than to encounter someone stupid in his foolishness.

[[v20-17-13]]

^<<v20-17-13,13>>^ If anyone repays bad for good,
Bad will not depart from his house.

[[v20-17-14]]

^<<v20-17-14,14>>^ Beginning a fight is like opening a floodgate;^&#42;1^
Before the quarrel breaks out, take your leave.

[NOTE]
====
. Or “like opening a dam.” Lit., “letting out waters.”
====

[[v20-17-15]]

^<<v20-17-15,15>>^ Anyone who acquits the wicked one and anyone who condemns the righteous one
—Both of them are detestable to Jehovah.

[[v20-17-16]]

^<<v20-17-16,16>>^ What good is it that the stupid one has the means to acquire wisdom
When he has no heart for acquiring it?^&#42;1^

[NOTE]
====
. Or “When he is lacking good sense?”
====

[[v20-17-17]]

^<<v20-17-17,17>>^ A true friend shows love at all times
And is a brother who is born for times of distress.

[[v20-17-18]]

^<<v20-17-18,18>>^ A man lacking good sense^&#42;1^ shakes hands and agrees
To put up security^&#42;2^ in the presence of his neighbor.

[NOTE]
====
. Lit., “in want of heart.”
. Or “go surety.”
====

[[v20-17-19]]

^<<v20-17-19,19>>^ The one who loves conflict loves transgression.
Anyone who makes his entryway high invites a crash.

[[v20-17-20]]

^<<v20-17-20,20>>^ The one who is crooked at heart will not find success,^&#42;1^
And the one who speaks deceitfully will fall into ruin.

[NOTE]
====
. Lit., “good.”
====

[[v20-17-21]]

^<<v20-17-21,21>>^ The one who fathers a stupid child will experience grief;
And the father of a senseless child has no joy.

[[v20-17-22]]

^<<v20-17-22,22>>^ A joyful heart is good medicine,^&#42;1^
But a crushed spirit saps one’s strength.^&#42;2^

[NOTE]
====
. Or “good for healing.”
. Or “dries up the bones.”
====

[[v20-17-23]]

^<<v20-17-23,23>>^ A wicked man will take a bribe in secret^&#42;1^
To pervert the course of justice.

[NOTE]
====
. Lit., “a bribe from the bosom.”
====

[[v20-17-24]]

^<<v20-17-24,24>>^ Wisdom is directly in front of the discerning person,
But the eyes of the stupid wander to the ends of the earth.

[[v20-17-25]]

^<<v20-17-25,25>>^ A stupid son brings grief to his father
And heartache^&#42;1^ to the one who gave birth to him.

[NOTE]
====
. Lit., “bitterness.”
====

[[v20-17-26]]

^<<v20-17-26,26>>^ To punish^&#42;1^ the righteous one is not good,
And to flog honorable people goes against what is right.

[NOTE]
====
. Or “impose a fine on.”
====

[[v20-17-27]]

^<<v20-17-27,27>>^ A man of knowledge restrains his words,
And a discerning man will remain calm.^&#42;1^

[NOTE]
====
. Lit., “cool of spirit.”
====

[[v20-17-28]]

^<<v20-17-28,28>>^ Even a fool who keeps silent will be considered wise,
And the one who seals his lips, discerning.

'''

xref:020-proverbs/020-proverbs-016.adoc#v20-16-0[&#60; Capítulo Anterior] | <<v20-17-0,Topo>> | xref:020-proverbs/020-proverbs-018.adoc#v20-18-0[Próximo Capítulo &#62;]