include::./index.adoc[]

[[v20-25-0]]
=== Proverbs, 25
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v20-25-1]]

^<<v20-25-1,1>>^ These also are the proverbs of Solʹo·mon, which the men of Hez·e·kiʹah the king of Judah transcribed:^&#42;1^

[NOTE]
====
. Or “copied and compiled.”
====

[[v20-25-2]]

^<<v20-25-2,2>>^ It is the glory of God to keep a matter secret,
And the glory of kings is to search through a matter.

[[v20-25-3]]

^<<v20-25-3,3>>^ As the heavens are high and the earth is deep,
So the heart of kings is unsearchable.

[[v20-25-4]]

^<<v20-25-4,4>>^ Remove the dross from the silver,
And it will emerge completely refined.

[[v20-25-5]]

^<<v20-25-5,5>>^ Remove the wicked one from the king’s presence,
And his throne will be firmly established in righteousness.

[[v20-25-6]]

^<<v20-25-6,6>>^ Do not honor yourself before the king,
And do not take a place among the prominent,

[[v20-25-7]]

^<<v20-25-7,7>>^ For it is better for him to say to you, “Come up here,”
Than to humiliate you in the presence of a noble.

[[v20-25-8]]

^<<v20-25-8,8>>^ Do not rush into a legal dispute,
For what will you do later if your neighbor humiliates you?

[[v20-25-9]]

^<<v20-25-9,9>>^ Plead your case with your neighbor,
But do not reveal what you were told confidentially,^&#42;1^

[NOTE]
====
. Or “the secrets of others.”
====

[[v20-25-10]]

^<<v20-25-10,10>>^ So that the one listening will not put you to shame
And you spread a bad report^&#42;1^ that cannot be recalled.

[NOTE]
====
. Or “a malicious rumor.”
====

[[v20-25-11]]

^<<v20-25-11,11>>^ Like apples of gold in silver carvings^&#42;1^
Is a word spoken at the right time.

[NOTE]
====
. Or “settings.”
====

[[v20-25-12]]

^<<v20-25-12,12>>^ Like an earring of gold and an ornament of fine gold
Is a wise reprover to the receptive ear.

[[v20-25-13]]

^<<v20-25-13,13>>^ Just like the coldness of snow on the day of harvest
Is a faithful messenger to those who sent him,
For he refreshes his master.^&#42;1^

[NOTE]
====
. Or “the soul of his master.”
====

[[v20-25-14]]

^<<v20-25-14,14>>^ Like clouds and wind that bring no rain
Is a man who boasts about a gift never given.^&#42;1^

[NOTE]
====
. Lit., “a gift of falsehood.”
====

[[v20-25-15]]

^<<v20-25-15,15>>^ By patience a commander is won over,
And a gentle^&#42;1^ tongue can break a bone.

[NOTE]
====
. Or “mild.”
====

[[v20-25-16]]

^<<v20-25-16,16>>^ If you find honey, eat only what you need,
For if you take too much, you may vomit it up.

[[v20-25-17]]

^<<v20-25-17,17>>^ Rarely set foot in your neighbor’s house,
So that he does not get tired of you and hate you.

[[v20-25-18]]

^<<v20-25-18,18>>^ Like a war club and a sword and a sharp arrow
Is a man bearing false witness against his neighbor.

[[v20-25-19]]

^<<v20-25-19,19>>^ Like a broken tooth or an unsteady foot
Is confidence in an unreliable^&#42;1^ person in times of trouble.

[NOTE]
====
. Or possibly, “a treacherous.”
====

[[v20-25-20]]

^<<v20-25-20,20>>^ Like one who removes a garment on a cold day
And like vinegar poured on soda^&#42;1^
Is the one who sings songs to a gloomy heart.

[NOTE]
====
. Or “alkali.”
====

[[v20-25-21]]

^<<v20-25-21,21>>^ If your enemy^&#42;1^ is hungry, give him bread to eat;
If he is thirsty, give him water to drink,

[NOTE]
====
. Lit., “the one hating you.”
====

[[v20-25-22]]

^<<v20-25-22,22>>^ For you will be heaping burning coals on his head,^&#42;1^
And Jehovah will reward you.

[NOTE]
====
. That is, to soften the person and melt his hardness.
====

[[v20-25-23]]

^<<v20-25-23,23>>^ The north wind brings a downpour,
And a gossiping tongue brings an angry face.

[[v20-25-24]]

^<<v20-25-24,24>>^ Better to dwell on a corner of the roof
Than in the same house with a quarrelsome^&#42;1^ wife.

[NOTE]
====
. Or “nagging.”
====

[[v20-25-25]]

^<<v20-25-25,25>>^ Like cold water on a tired soul^&#42;1^
Is a good report from a distant land.

[NOTE]
====
. See Glossary.
====

[[v20-25-26]]

^<<v20-25-26,26>>^ Like a muddied spring and a ruined well
Is a righteous person who gives in to^&#42;1^ a wicked one.

[NOTE]
====
. Or “compromises with.” Lit., “staggers before.”
====

[[v20-25-27]]

^<<v20-25-27,27>>^ It is not good to eat too much honey,
Nor is it glorious to seek one’s own glory.

[[v20-25-28]]

^<<v20-25-28,28>>^ As a city broken through, without a wall,
Is the man who cannot control his temper.^&#42;1^

[NOTE]
====
. Or “who has no restraint for his spirit.”
====

'''

xref:020-proverbs/020-proverbs-024.adoc#v20-24-0[&#60; Capítulo Anterior] | <<v20-25-0,Topo>> | xref:020-proverbs/020-proverbs-026.adoc#v20-26-0[Próximo Capítulo &#62;]