include::./index.adoc[]

[[v20-8-0]]
=== Proverbs, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v20-8-1]]

^<<v20-8-1,1>>^ Is not wisdom calling out?
Is not discernment raising its voice?

[[v20-8-2]]

^<<v20-8-2,2>>^ On the heights along the road,
It takes its position at the crossroads.

[[v20-8-3]]

^<<v20-8-3,3>>^ Next to the gates leading into the city,
At the entrances of the doorways,
It keeps crying out loudly:

[[v20-8-4]]

^<<v20-8-4,4>>^ “To you, O people, I am calling;
I raise my voice to everyone.^&#42;1^

[NOTE]
====
. Lit., “to the sons of men.”
====

[[v20-8-5]]

^<<v20-8-5,5>>^ You inexperienced ones, learn shrewdness;
You stupid ones, acquire an understanding heart.^&#42;1^

[NOTE]
====
. Lit., “understand heart.”
====

[[v20-8-6]]

^<<v20-8-6,6>>^ Listen, for what I say is important,
My lips speak what is right;

[[v20-8-7]]

^<<v20-8-7,7>>^ For my mouth softly utters truth,
And my lips detest what is wicked.

[[v20-8-8]]

^<<v20-8-8,8>>^ All the sayings of my mouth are righteous.
None of them are twisted or crooked.

[[v20-8-9]]

^<<v20-8-9,9>>^ They are all straightforward to the discerning
And right to those who have found knowledge.

[[v20-8-10]]

^<<v20-8-10,10>>^ Take my discipline instead of silver,
And knowledge rather than the finest gold,

[[v20-8-11]]

^<<v20-8-11,11>>^ For wisdom is better than corals;^&#42;1^
All other desirable things cannot compare to it.

[NOTE]
====
. See Glossary.
====

[[v20-8-12]]

^<<v20-8-12,12>>^ I, wisdom, dwell together with shrewdness;
I have found knowledge and thinking ability.

[[v20-8-13]]

^<<v20-8-13,13>>^ The fear of Jehovah means the hating of bad.
I hate self-exaltation and pride and the evil way and perverse speech.

[[v20-8-14]]

^<<v20-8-14,14>>^ I possess good advice and practical wisdom;
Understanding and power are mine.

[[v20-8-15]]

^<<v20-8-15,15>>^ By me kings keep reigning,
And high officials decree righteousness.

[[v20-8-16]]

^<<v20-8-16,16>>^ By me princes keep ruling,
And nobles judge in righteousness.

[[v20-8-17]]

^<<v20-8-17,17>>^ I love those loving me,
And those seeking me will find me.

[[v20-8-18]]

^<<v20-8-18,18>>^ Riches and glory are with me,
Lasting wealth^&#42;1^ and righteousness.

[NOTE]
====
. Or “Hereditary values.”
====

[[v20-8-19]]

^<<v20-8-19,19>>^ My fruitage is better than gold, even refined gold,
And what I produce is better than the finest silver.

[[v20-8-20]]

^<<v20-8-20,20>>^ I walk in the path of righteousness,
In the middle of the pathways of justice;

[[v20-8-21]]

^<<v20-8-21,21>>^ I give a rich inheritance to those who love me,
And I fill up their storehouses.

[[v20-8-22]]

^<<v20-8-22,22>>^ Jehovah produced me as the beginning of his way,
The earliest of his achievements of long ago.

[[v20-8-23]]

^<<v20-8-23,23>>^ From ancient times^&#42;1^ I was installed,
From the start, from times earlier than the earth.

[NOTE]
====
. Or “From time immemorial.”
====

[[v20-8-24]]

^<<v20-8-24,24>>^ When there were no deep waters, I was brought forth,^&#42;1^
When there were no springs overflowing with water.

[NOTE]
====
. Or “brought forth as with labor pains.”
====

[[v20-8-25]]

^<<v20-8-25,25>>^ Before the mountains were set in place,
Before the hills, I was brought forth,

[[v20-8-26]]

^<<v20-8-26,26>>^ When he had not yet made the earth and its fields
Or the first clods of earth’s soil.

[[v20-8-27]]

^<<v20-8-27,27>>^ When he prepared the heavens, I was there;
When he marked out the horizon^&#42;1^ on the surface of the waters,

[NOTE]
====
. Lit., “a circle.”
====

[[v20-8-28]]

^<<v20-8-28,28>>^ When he established^&#42;1^ the clouds above,
When he founded the fountains of the deep,

[NOTE]
====
. Lit., “made strong.”
====

[[v20-8-29]]

^<<v20-8-29,29>>^ When he set a decree for the sea
That its waters should not pass beyond his order,
When he established^&#42;1^ the foundations of the earth,

[NOTE]
====
. Or “decreed.”
====

[[v20-8-30]]

^<<v20-8-30,30>>^ Then I was beside him as a master worker.
I was the one he was especially fond of day by day;
I rejoiced before him all the time;

[[v20-8-31]]

^<<v20-8-31,31>>^ I rejoiced over his habitable earth,
And I was especially fond of the sons of men.^&#42;1^

[NOTE]
====
. Or “mankind.”
====

[[v20-8-32]]

^<<v20-8-32,32>>^ And now, my sons, listen to me;
Yes, happy are those who keep my ways.

[[v20-8-33]]

^<<v20-8-33,33>>^ Listen to discipline and become wise,
And never neglect it.

[[v20-8-34]]

^<<v20-8-34,34>>^ Happy is the man who listens to me
By coming early to^&#42;1^ my doors day by day,
By waiting next to my doorposts;

[NOTE]
====
. Or “By keeping awake at.”
====

[[v20-8-35]]

^<<v20-8-35,35>>^ For the one finding me will find life,
And he receives approval from Jehovah.

[[v20-8-36]]

^<<v20-8-36,36>>^ But the one who ignores me harms himself,^&#42;1^
And those who hate me love death.”

[NOTE]
====
. Or “his soul.”
====

'''

xref:020-proverbs/020-proverbs-007.adoc#v20-7-0[&#60; Capítulo Anterior] | <<v20-8-0,Topo>> | xref:020-proverbs/020-proverbs-009.adoc#v20-9-0[Próximo Capítulo &#62;]