include::./index.adoc[]

[[v20-21-0]]
=== Proverbs, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v20-21-1]]

^<<v20-21-1,1>>^ A king’s heart is like streams of water in Jehovah’s hand.
He directs it wherever He pleases.

[[v20-21-2]]

^<<v20-21-2,2>>^ All of a man’s ways seem right to him,
But Jehovah examines the hearts.^&#42;1^

[NOTE]
====
. Or “motives.”
====

[[v20-21-3]]

^<<v20-21-3,3>>^ To do what is right and just
Is more pleasing to Jehovah than a sacrifice.

[[v20-21-4]]

^<<v20-21-4,4>>^ Haughty eyes and an arrogant heart
—The lamp that guides the wicked is sin.

[[v20-21-5]]

^<<v20-21-5,5>>^ The plans of the diligent surely lead to success,^&#42;1^
But all who are hasty surely head for poverty.

[NOTE]
====
. Or “advantage.”
====

[[v20-21-6]]

^<<v20-21-6,6>>^ Gaining treasures by a lying tongue
Is like a vanishing mist, a deadly snare.^&#42;1^

[NOTE]
====
. Or possibly, “for those seeking death.”
====

[[v20-21-7]]

^<<v20-21-7,7>>^ The violence of the wicked will sweep them away,
For they refuse to act with justice.

[[v20-21-8]]

^<<v20-21-8,8>>^ The way of a guilty man is crooked,
But the activity of the pure man is upright.

[[v20-21-9]]

^<<v20-21-9,9>>^ Better to dwell on a corner of the roof
Than in the same house with a quarrelsome^&#42;1^ wife.

[NOTE]
====
. Or “nagging.”
====

[[v20-21-10]]

^<<v20-21-10,10>>^ The wicked man^&#42;1^ craves what is bad;
He shows no favor toward his neighbor.

[NOTE]
====
. Or “The soul of the wicked one.”
====

[[v20-21-11]]

^<<v20-21-11,11>>^ When a ridiculer is punished, the inexperienced become wiser,
And when a wise person receives insight, he gains knowledge.^&#42;1^

[NOTE]
====
. Or “he knows what to do.”
====

[[v20-21-12]]

^<<v20-21-12,12>>^ The Righteous One observes the house of the wicked one;
He overthrows the wicked to their ruin.

[[v20-21-13]]

^<<v20-21-13,13>>^ Whoever stops up his ear to the cry of the lowly one
Will himself call and not be answered.

[[v20-21-14]]

^<<v20-21-14,14>>^ A secret gift subdues anger,
And a hidden bribe,^&#42;1^ fierce rage.

[NOTE]
====
. Lit., “a bribe in the bosom.”
====

[[v20-21-15]]

^<<v20-21-15,15>>^ It is a joy for the righteous one to act with justice,
But it is something terrible to those who practice evil.

[[v20-21-16]]

^<<v20-21-16,16>>^ The man who strays from the way of insight
Will rest in the company of those powerless in death.

[[v20-21-17]]

^<<v20-21-17,17>>^ The one who loves having a good time^&#42;1^ will come to poverty;
The one who loves wine and oil will not grow rich.

[NOTE]
====
. Or “loves pleasure.”
====

[[v20-21-18]]

^<<v20-21-18,18>>^ The wicked one is a ransom for the righteous one,
And the treacherous one will be taken in place of the upright.

[[v20-21-19]]

^<<v20-21-19,19>>^ Better to dwell in the wilderness
Than with a quarrelsome^&#42;1^ and irritable wife.

[NOTE]
====
. Or “nagging.”
====

[[v20-21-20]]

^<<v20-21-20,20>>^ Precious treasure and oil are found in the house of the wise,
But the stupid man will squander^&#42;1^ what he has.

[NOTE]
====
. Lit., “swallow.”
====

[[v20-21-21]]

^<<v20-21-21,21>>^ Whoever pursues righteousness and loyal love
Will find life, righteousness, and glory.

[[v20-21-22]]

^<<v20-21-22,22>>^ A wise man can scale^&#42;1^ the city of the mighty
And undermine the strength in which they trust.

[NOTE]
====
. Or “prevail over.”
====

[[v20-21-23]]

^<<v20-21-23,23>>^ The one guarding his mouth and his tongue
Keeps himself^&#42;1^ out of trouble.

[NOTE]
====
. Or “his soul.”
====

[[v20-21-24]]

^<<v20-21-24,24>>^ A presumptuous, arrogant braggart is what you call
The man who acts with reckless presumptuousness.

[[v20-21-25]]

^<<v20-21-25,25>>^ What the lazy man craves will put him to death,
For his hands refuse to work.

[[v20-21-26]]

^<<v20-21-26,26>>^ All day long he greedily craves,
But the righteous one gives, holding nothing back.

[[v20-21-27]]

^<<v20-21-27,27>>^ The sacrifice of the wicked is detestable.
How much more when he offers it with evil intent!^&#42;1^

[NOTE]
====
. Or “along with shameful conduct!”
====

[[v20-21-28]]

^<<v20-21-28,28>>^ A lying witness will perish,
But the man who listens will testify with success.^&#42;1^

[NOTE]
====
. Lit., “speak forever.”
====

[[v20-21-29]]

^<<v20-21-29,29>>^ The wicked man puts on a bold face,
But it is the upright one whose course is sure.^&#42;1^

[NOTE]
====
. Or “who makes his way sure.”
====

[[v20-21-30]]

^<<v20-21-30,30>>^ There is no wisdom, nor discernment, nor counsel in opposition to Jehovah.

[[v20-21-31]]

^<<v20-21-31,31>>^ The horse is prepared for the day of battle,
But salvation belongs to Jehovah.

'''

xref:020-proverbs/020-proverbs-020.adoc#v20-20-0[&#60; Capítulo Anterior] | <<v20-21-0,Topo>> | xref:020-proverbs/020-proverbs-022.adoc#v20-22-0[Próximo Capítulo &#62;]