include::./index.adoc[]

[[v20-9-0]]
=== Proverbs, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v20-9-1]]

^<<v20-9-1,1>>^ True wisdom has built its house;
It has carved^&#42;1^ out its seven pillars.

[NOTE]
====
. Or “hewed.”
====

[[v20-9-2]]

^<<v20-9-2,2>>^ It has fully prepared its meat;^&#42;1^
It has mixed its wine;
It has also arranged its table.

[NOTE]
====
. Lit., “She has slaughtered her slaughtering.”
====

[[v20-9-3]]

^<<v20-9-3,3>>^ It has sent out its female servants
To call out from the heights above the city:

[[v20-9-4]]

^<<v20-9-4,4>>^ “Whoever is inexperienced, let him come in here.”
She says to the one lacking good sense:^&#42;1^

[NOTE]
====
. Lit., “in want of heart.”
====

[[v20-9-5]]

^<<v20-9-5,5>>^ “Come, eat my bread
And share in drinking the wine that I have mixed.

[[v20-9-6]]

^<<v20-9-6,6>>^ Leave behind your inexperience^&#42;1^ and live;
Walk forward in the way of understanding.”

[NOTE]
====
. Or “the inexperienced ones.”
====

[[v20-9-7]]

^<<v20-9-7,7>>^ The one who corrects a ridiculer invites dishonor,
And whoever reproves someone wicked will get hurt.

[[v20-9-8]]

^<<v20-9-8,8>>^ Do not reprove a ridiculer, or he will hate you.
Reprove a wise person, and he will love you.

[[v20-9-9]]

^<<v20-9-9,9>>^ Share with a wise person, and he will become wiser.
Teach someone righteous, and he will add to his learning.

[[v20-9-10]]

^<<v20-9-10,10>>^ The fear of Jehovah is the beginning of wisdom,
And knowledge of the Most Holy One is understanding.

[[v20-9-11]]

^<<v20-9-11,11>>^ For by me your days will be many,
And years will be added to your life.

[[v20-9-12]]

^<<v20-9-12,12>>^ If you become wise, you are wise to your own advantage,
But if you are a ridiculer, you alone will bear it.

[[v20-9-13]]

^<<v20-9-13,13>>^ A stupid woman is loud.
She is ignorant and knows absolutely nothing.

[[v20-9-14]]

^<<v20-9-14,14>>^ She sits at the entrance of her house
On a seat in the high places of the city,

[[v20-9-15]]

^<<v20-9-15,15>>^ Calling out to those passing by,
To those walking straight ahead on their way:

[[v20-9-16]]

^<<v20-9-16,16>>^ “Whoever is inexperienced, let him come in here.”
She says to those lacking good sense:^&#42;1^

[NOTE]
====
. Lit., “in want of heart.”
====

[[v20-9-17]]

^<<v20-9-17,17>>^ “Stolen waters are sweet,
And food eaten in secret is pleasant.”

[[v20-9-18]]

^<<v20-9-18,18>>^ But he does not know that those powerless in death are there,
That her guests are in the depths of the Grave.^&#42;1^

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

'''

xref:020-proverbs/020-proverbs-008.adoc#v20-8-0[&#60; Capítulo Anterior] | <<v20-9-0,Topo>> | xref:020-proverbs/020-proverbs-010.adoc#v20-10-0[Próximo Capítulo &#62;]