include::./index.adoc[]

[[v20-2-0]]
=== Proverbs, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v20-2-1]]

^<<v20-2-1,1>>^ My son, if you accept my sayings
And treasure up my commandments,

[[v20-2-2]]

^<<v20-2-2,2>>^ By making your ear attentive to wisdom
And inclining your heart to discernment;

[[v20-2-3]]

^<<v20-2-3,3>>^ Moreover, if you call out for understanding
And raise your voice for discernment;

[[v20-2-4]]

^<<v20-2-4,4>>^ If you keep seeking for it as for silver,
And you keep searching for it as for hidden treasures;

[[v20-2-5]]

^<<v20-2-5,5>>^ Then you will understand the fear of Jehovah,
And you will find the knowledge of God.

[[v20-2-6]]

^<<v20-2-6,6>>^ For Jehovah himself gives wisdom;
From his mouth come knowledge and discernment.

[[v20-2-7]]

^<<v20-2-7,7>>^ He treasures up practical wisdom for the upright;
He is a shield for those walking in integrity.

[[v20-2-8]]

^<<v20-2-8,8>>^ He watches over the paths of justice,
And he will guard the way of his loyal ones.

[[v20-2-9]]

^<<v20-2-9,9>>^ Then you will understand what is righteous and just and fair,
The entire course of what is good.

[[v20-2-10]]

^<<v20-2-10,10>>^ When wisdom enters your heart
And knowledge becomes pleasant to your soul,^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v20-2-11]]

^<<v20-2-11,11>>^ Thinking ability will keep watch over you,
And discernment will safeguard you,

[[v20-2-12]]

^<<v20-2-12,12>>^ To save you from the bad course,
From the man speaking perverse things,

[[v20-2-13]]

^<<v20-2-13,13>>^ From those leaving the upright paths
To walk in the ways of darkness,

[[v20-2-14]]

^<<v20-2-14,14>>^ From those who rejoice in wrongdoing,
Who find joy in the perverseness of evil,

[[v20-2-15]]

^<<v20-2-15,15>>^ Those whose paths are crooked
And whose entire course is devious.

[[v20-2-16]]

^<<v20-2-16,16>>^ It will save you from the wayward^&#42;1^ woman,
From the smooth^&#42;2^ words of the immoral^&#42;3^ woman,

[NOTE]
====
. Lit., “strange.” Evidently, one morally estranged from God.
. Or “seductive.”
. Lit., “foreign.” Evidently, one morally alienated from God.
====

[[v20-2-17]]

^<<v20-2-17,17>>^ Who abandons the close companion^&#42;1^ of her youth
And forgets the covenant of her God;

[NOTE]
====
. Or “the husband.”
====

[[v20-2-18]]

^<<v20-2-18,18>>^ For her house sinks down into death,
And her paths^&#42;1^ lead to those powerless in death.

[NOTE]
====
. Lit., “tracks.”
====

[[v20-2-19]]

^<<v20-2-19,19>>^ None of those having relations with^&#42;1^ her will return,
Nor will they regain the pathways of life.

[NOTE]
====
. Lit., “going in to.”
====

[[v20-2-20]]

^<<v20-2-20,20>>^ So follow the way of good people
And stay on the paths of the righteous,

[[v20-2-21]]

^<<v20-2-21,21>>^ For only the upright will reside in the earth,
And the blameless^&#42;1^ will remain in it.

[NOTE]
====
. Or “the one who keeps integrity.”
====

[[v20-2-22]]

^<<v20-2-22,22>>^ As for the wicked, they will be cut off from the earth,
And the treacherous will be torn away from it.

'''

xref:020-proverbs/020-proverbs-001.adoc#v20-1-0[&#60; Capítulo Anterior] | <<v20-2-0,Topo>> | xref:020-proverbs/020-proverbs-003.adoc#v20-3-0[Próximo Capítulo &#62;]