include::./index.adoc[]

[[v20-4-0]]
=== Proverbs, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v20-4-1]]

^<<v20-4-1,1>>^ Listen, my sons, to the discipline of a father;
Pay attention in order to gain understanding,

[[v20-4-2]]

^<<v20-4-2,2>>^ For I will give you good instruction;
Do not forsake my teaching.^&#42;1^

[NOTE]
====
. Or “law.”
====

[[v20-4-3]]

^<<v20-4-3,3>>^ I was a true son to my father
And the one especially loved by my mother.

[[v20-4-4]]

^<<v20-4-4,4>>^ He taught me and said: “May your heart hold fast to my words.
Keep my commandments and continue living.

[[v20-4-5]]

^<<v20-4-5,5>>^ Acquire wisdom, acquire understanding.
Do not forget, and do not turn aside from what I say.

[[v20-4-6]]

^<<v20-4-6,6>>^ Do not forsake it, and it will protect you.
Love it, and it will safeguard you.

[[v20-4-7]]

^<<v20-4-7,7>>^ Wisdom is the most important^&#42;1^ thing, so acquire wisdom,
And with all you acquire, acquire understanding.

[NOTE]
====
. Or “the prime.”
====

[[v20-4-8]]

^<<v20-4-8,8>>^ Highly esteem it, and it will exalt you.
It will honor you because you embrace it.

[[v20-4-9]]

^<<v20-4-9,9>>^ It will place an attractive wreath on your head;
It will adorn you with a crown of beauty.”

[[v20-4-10]]

^<<v20-4-10,10>>^ Listen, my son, and accept my sayings,
And the years of your life will be many.

[[v20-4-11]]

^<<v20-4-11,11>>^ I will instruct you in the way of wisdom;
I will lead you in the tracks of uprightness.

[[v20-4-12]]

^<<v20-4-12,12>>^ When you walk, your steps will not be hindered;
And if you run, you will not stumble.

[[v20-4-13]]

^<<v20-4-13,13>>^ Hold on to discipline; do not let it go.
Safeguard it, for it means your life.

[[v20-4-14]]

^<<v20-4-14,14>>^ Do not enter the path of the wicked,
And do not walk in the way of evil men.

[[v20-4-15]]

^<<v20-4-15,15>>^ Shun it, do not take it;
Turn away from it, and pass it by.

[[v20-4-16]]

^<<v20-4-16,16>>^ For they cannot sleep unless they do what is bad.
They are robbed of sleep unless they cause someone’s downfall.

[[v20-4-17]]

^<<v20-4-17,17>>^ They feed themselves with the bread of wickedness,
And they drink the wine of violence.

[[v20-4-18]]

^<<v20-4-18,18>>^ But the path of the righteous is like the bright morning light
That grows brighter and brighter until full daylight.

[[v20-4-19]]

^<<v20-4-19,19>>^ The way of the wicked is like the darkness;
They do not know what makes them stumble.

[[v20-4-20]]

^<<v20-4-20,20>>^ My son, pay attention to my words;
Listen carefully^&#42;1^ to my sayings.

[NOTE]
====
. Lit., “Incline your ear.”
====

[[v20-4-21]]

^<<v20-4-21,21>>^ Do not lose sight of them;
Keep them deep within your heart,

[[v20-4-22]]

^<<v20-4-22,22>>^ For they are life to those who find them
And health to their whole body.^&#42;1^

[NOTE]
====
. Lit., “to all their flesh.”
====

[[v20-4-23]]

^<<v20-4-23,23>>^ Above all the things that you guard, safeguard your heart,
For out of it are the sources of life.

[[v20-4-24]]

^<<v20-4-24,24>>^ Put crooked speech away from you,
And keep devious talk far away from you.

[[v20-4-25]]

^<<v20-4-25,25>>^ Your eyes should look straight ahead,
Yes, fix your gaze^&#42;1^ straight ahead of you.

[NOTE]
====
. Or “beaming eyes.”
====

[[v20-4-26]]

^<<v20-4-26,26>>^ Smooth out^&#42;1^ the course of your feet,
And all your ways will be sure.

[NOTE]
====
. Or possibly, “Carefully consider.”
====

[[v20-4-27]]

^<<v20-4-27,27>>^ Do not incline to the right or the left.
Turn your feet away from what is bad.

'''

xref:020-proverbs/020-proverbs-003.adoc#v20-3-0[&#60; Capítulo Anterior] | <<v20-4-0,Topo>> | xref:020-proverbs/020-proverbs-005.adoc#v20-5-0[Próximo Capítulo &#62;]