include::./index.adoc[]

[[v24-22-0]]
=== Jeremiah, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-22-1]]

^<<v24-22-1,1>>^ This is what Jehovah says: “Go down to the house^&#42;1^ of the king of Judah, and deliver this message.

[NOTE]
====
. Or “palace.”
====

[[v24-22-2]]

^<<v24-22-2,2>>^ You must say, ‘Hear the word of Jehovah, O king of Judah who sits on the throne of David, you with your servants and your people, those who enter through these gates.

[[v24-22-3]]

^<<v24-22-3,3>>^ This is what Jehovah says: “Uphold justice and righteousness. Rescue the one being robbed from the hand of the defrauder. Do not mistreat any foreign resident, and do not harm any fatherless child^&#42;1^ or widow. And do not shed any innocent blood in this place.

[NOTE]
====
. Or “any orphan.”
====

[[v24-22-4]]

^<<v24-22-4,4>>^ For if you are careful to carry out this word, then the kings who sit on the throne of David will enter through the gates of this house, riding in chariots and on horses, they with their servants and their people.”’

[[v24-22-5]]

^<<v24-22-5,5>>^ “‘But if you will not obey these words, by myself I do swear,’ declares Jehovah, ‘that this house will become a devastated place.’

[[v24-22-6]]

^<<v24-22-6,6>>^ “For this is what Jehovah says concerning the house of the king of Judah,
‘You are as Gilʹe·ad to me,
Like the summit of Lebʹa·non.
But I will make you a wilderness;
Not one of your cities will be inhabited.

[[v24-22-7]]

^<<v24-22-7,7>>^ And I will appoint^&#42;1^ destroyers against you,
Each with his weapons.
They will cut down your choicest cedars
And make them fall into the fire.

[NOTE]
====
. Lit., “sanctify.”
====

[[v24-22-8]]

^<<v24-22-8,8>>^ “‘And many nations will pass by this city and say to one another: “Why did Jehovah do this to this great city?”

[[v24-22-9]]

^<<v24-22-9,9>>^ And they will reply: “Because they abandoned the covenant of Jehovah their God and bowed down to other gods and served them.”’

[[v24-22-10]]

^<<v24-22-10,10>>^ Do not weep for the dead one,
And do not sympathize with him.
Instead, weep profusely for the one going away,
For he will return no more to see the land of his birth.

[[v24-22-11]]

^<<v24-22-11,11>>^ “For this is what Jehovah says concerning Shalʹlum^&#42;1^ son of Jo·siʹah, the king of Judah who is reigning instead of his father Jo·siʹah and who has gone out of this place: ‘He will return there no more.

[NOTE]
====
. Also called Jehoahaz.
====

[[v24-22-12]]

^<<v24-22-12,12>>^ For he will die in the place where they have taken him into exile, and he will see this land no more.’

[[v24-22-13]]

^<<v24-22-13,13>>^ Woe to the one who builds his house without righteousness
And his upper rooms without justice,
Who makes his fellow man serve him for nothing,
Whose wages he refuses to pay;

[[v24-22-14]]

^<<v24-22-14,14>>^ The one saying, ‘I will build for myself a roomy house
With spacious upper rooms.
I will fit it with windows
And panel it with cedar and paint it with vermilion.’^&#42;1^

[NOTE]
====
. Or “red.”
====

[[v24-22-15]]

^<<v24-22-15,15>>^ Will you continue reigning because you outdo others in your use of cedar?
Your father also ate and drank,
But he upheld justice and righteousness,
And it went well with him.

[[v24-22-16]]

^<<v24-22-16,16>>^ He defended the legal claim of the afflicted one and the poor one,
So that it went well.
‘Is that not what it means to know me?’ declares Jehovah.

[[v24-22-17]]

^<<v24-22-17,17>>^ ‘But your eyes and heart are set only on your dishonest gain,
On shedding innocent blood,
And on committing fraud and extortion.’

[[v24-22-18]]

^<<v24-22-18,18>>^ “Therefore this is what Jehovah says concerning Je·hoiʹa·kim son of Jo·siʹah, the king of Judah,
‘They will not mourn him:
“Alas, my brother! Alas, my sister!”
They will not mourn him:
“Alas, O master! Alas, his majesty!”

[[v24-22-19]]

^<<v24-22-19,19>>^ With the burial of a donkey he will be buried,
Dragged about and thrown away,
Outside the gates of Jerusalem.’

[[v24-22-20]]

^<<v24-22-20,20>>^ Go up to Lebʹa·non and cry out,
Raise your voice in Baʹshan,
And cry out from Abʹa·rim,
For all your passionate lovers have been crushed.

[[v24-22-21]]

^<<v24-22-21,21>>^ I spoke to you when you felt secure.
But you said, ‘I will not obey.’
This has been your course since youth,
For you have not obeyed my voice.

[[v24-22-22]]

^<<v24-22-22,22>>^ A wind will shepherd all your shepherds,
And your passionate lovers will go into captivity.
Then you will be put to shame and humiliated because of all your calamity.

[[v24-22-23]]

^<<v24-22-23,23>>^ O you who dwell in Lebʹa·non,
Nestled among the cedars,
How you will groan when pangs come on you,
Anguish^&#42;1^ like that of a woman giving birth!”

[NOTE]
====
. Lit., “Birth pangs.”
====

[[v24-22-24]]

^<<v24-22-24,24>>^ “‘As surely as I am alive,’ declares Jehovah, ‘even if Co·niʹah^&#42;1^ son of Je·hoiʹa·kim, the king of Judah, were the seal ring on my right hand, I would pull you off from there!

[NOTE]
====
. Also called Jehoiachin and Jeconiah.
====

[[v24-22-25]]

^<<v24-22-25,25>>^ I will give you into the hand of those seeking to take your life,^&#42;1^ into the hand of those whom you fear, into the hand of King Neb·u·chad·nezʹzar^&#42;2^ of Babylon, and into the hand of the Chal·deʹans.

[NOTE]
====
. Or “seeking your soul.”
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-22-26]]

^<<v24-22-26,26>>^ And I will hurl you and your mother who gave birth to you into another land where you were not born, and there you will die.

[[v24-22-27]]

^<<v24-22-27,27>>^ And they will never return to the land they yearn for.^&#42;1^

[NOTE]
====
. Or “the land to which they lift up their soul.”
====

[[v24-22-28]]

^<<v24-22-28,28>>^ Is this man Co·niʹah just a despised, broken pot,
A vessel that nobody wants?
Why are he and his descendants hurled down
And thrown into a land they do not know?’

[[v24-22-29]]

^<<v24-22-29,29>>^ O earth,^&#42;1^ earth, earth, hear the word of Jehovah.

[NOTE]
====
. Or “land.”
====

[[v24-22-30]]

^<<v24-22-30,30>>^ This is what Jehovah says:
‘Write down this man as childless,
As a man who will not have any success during his lifetime,^&#42;1^
For none of his descendants will succeed
In sitting on David’s throne and ruling again in Judah.’”

[NOTE]
====
. Lit., “days.”
====

'''

xref:024-jeremiah/024-jeremiah-021.adoc#v24-21-0[&#60; Capítulo Anterior] | <<v24-22-0,Topo>> | xref:024-jeremiah/024-jeremiah-023.adoc#v24-23-0[Próximo Capítulo &#62;]