include::./index.adoc[]

[[v24-7-0]]
=== Jeremiah, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-7-1]]

^<<v24-7-1,1>>^ This is the word that came to Jeremiah from Jehovah, saying:

[[v24-7-2]]

^<<v24-7-2,2>>^ “Stand in the gate of the house of Jehovah and proclaim there this message, ‘Hear the word of Jehovah, all you people of Judah who enter these gates to bow down to Jehovah.

[[v24-7-3]]

^<<v24-7-3,3>>^ This is what Jehovah of armies, the God of Israel, says: “Reform your ways and your actions, and I will allow you to keep residing in this place.

[[v24-7-4]]

^<<v24-7-4,4>>^ Do not put your trust in deceptive words and say, ‘This is^&#42;1^ the temple of Jehovah, the temple of Jehovah, the temple of Jehovah!’

[NOTE]
====
. Lit., “They are,” referring to all the buildings of the temple complex.
====

[[v24-7-5]]

^<<v24-7-5,5>>^ For if you truly reform your ways and actions; if you truly uphold justice between a man and his neighbor;

[[v24-7-6]]

^<<v24-7-6,6>>^ if you do not oppress foreign residents, orphans,^&#42;1^ and widows; if you do not shed innocent blood in this place; and if you do not follow other gods to your own harm;

[NOTE]
====
. Or “fatherless children.”
====

[[v24-7-7]]

^<<v24-7-7,7>>^ then I will allow you to keep residing in this place, in the land I gave to your forefathers for all time.”’”^&#42;1^

[NOTE]
====
. Or “from eternity to eternity.”
====

[[v24-7-8]]

^<<v24-7-8,8>>^ “But you are putting your trust in deceptive words—it will bring absolutely no benefit.

[[v24-7-9]]

^<<v24-7-9,9>>^ Can you steal, murder, commit adultery, swear falsely, make sacrifices^&#42;1^ to Baʹal, and follow after gods you had not known,

[NOTE]
====
. Or “sacrificial smoke.”
====

[[v24-7-10]]

^<<v24-7-10,10>>^ and then come and stand before me in this house that bears my name and say, ‘We will be saved,’ despite your doing all these detestable things?

[[v24-7-11]]

^<<v24-7-11,11>>^ Has this house that bears my name become a cave of robbers in your eyes? Here I have seen it for myself,” declares Jehovah.

[[v24-7-12]]

^<<v24-7-12,12>>^ “‘However, go now to my place in Shiʹloh, where I first caused my name to reside, and see what I did to it because of the badness of my people Israel.

[[v24-7-13]]

^<<v24-7-13,13>>^ But you kept doing all these things,’ declares Jehovah, ‘and even though I spoke to you again and again,^&#42;1^ you did not listen. I kept calling you, but you would not answer.

[NOTE]
====
. Lit., “rising up early and speaking.”
====

[[v24-7-14]]

^<<v24-7-14,14>>^ So I will do to the house that bears my name, in which you are trusting, and to this place that I gave to you and your forefathers, just as I did to Shiʹloh.

[[v24-7-15]]

^<<v24-7-15,15>>^ I will throw you out of my sight, just as I threw out all your brothers, all the descendants of Eʹphra·im.’

[[v24-7-16]]

^<<v24-7-16,16>>^ “As for you, do not pray in behalf of this people. Do not cry out or offer a prayer or plead with me in their behalf, for I will not listen to you.

[[v24-7-17]]

^<<v24-7-17,17>>^ Do you not see what they are doing in the cities of Judah and in the streets of Jerusalem?

[[v24-7-18]]

^<<v24-7-18,18>>^ The sons are gathering wood, the fathers are lighting the fire, and the wives are kneading dough in order to make sacrificial cakes to the Queen of Heaven,^&#42;1^ and they are pouring out drink offerings to other gods to offend me.

[NOTE]
====
. The title of a goddess worshipped by apostate Israelites; possibly a fertility goddess.
====

[[v24-7-19]]

^<<v24-7-19,19>>^ ‘But am I the one they are hurting?’^&#42;1^ declares Jehovah. ‘Is it not they themselves, to their own shame?’

[NOTE]
====
. Or “offending; provoking.”
====

[[v24-7-20]]

^<<v24-7-20,20>>^ Therefore this is what the Sovereign Lord Jehovah says, ‘Look! My anger and my wrath will be poured out on this place, on man and beast, on the trees of the field and the fruitage of the ground; it will burn and will not be extinguished.’

[[v24-7-21]]

^<<v24-7-21,21>>^ “This is what Jehovah of armies, the God of Israel, says, ‘Go ahead, add your whole burnt offerings to your other sacrifices, and eat the flesh yourselves.

[[v24-7-22]]

^<<v24-7-22,22>>^ For on the day I brought your forefathers out of the land of Egypt, I did not speak with them or command them concerning whole burnt offerings and sacrifices.

[[v24-7-23]]

^<<v24-7-23,23>>^ But I did give them this command: “Obey my voice, and I will become your God, and you will become my people. You must walk in all the way that I command, so that it may go well with you.”’

[[v24-7-24]]

^<<v24-7-24,24>>^ But they did not listen or incline their ear; instead, they walked in their own schemes,^&#42;1^ stubbornly following their wicked heart, and they went backward, not forward,

[NOTE]
====
. Or “advice.”
====

[[v24-7-25]]

^<<v24-7-25,25>>^ from the day your forefathers came out of the land of Egypt until this day. So I kept sending all my servants the prophets to you, sending them each day, again and again.^&#42;1^

[NOTE]
====
. Lit., “daily rising up early and sending.”
====

[[v24-7-26]]

^<<v24-7-26,26>>^ But they refused to listen to me, and they did not incline their ear. Instead, they were stubborn,^&#42;1^ and they acted worse than their forefathers!

[NOTE]
====
. Lit., “they hardened their neck.”
====

[[v24-7-27]]

^<<v24-7-27,27>>^ “You will speak all these words to them, but they will not listen to you; you will call to them, but they will not answer you.

[[v24-7-28]]

^<<v24-7-28,28>>^ And you will say to them, ‘This is the nation that did not obey the voice of Jehovah their God and refused to accept discipline. Faithfulness has perished and is not even mentioned among them.’^&#42;1^

[NOTE]
====
. Lit., “is cut off from their mouth.”
====

[[v24-7-29]]

^<<v24-7-29,29>>^ “Shear off your uncut^&#42;1^ hair and throw it away, and on the bare hills raise a dirge,^&#42;2^ for Jehovah has rejected and will abandon this generation that has infuriated him.

[NOTE]
====
. Or “dedicated.”
. Or “song of mourning.”
====

[[v24-7-30]]

^<<v24-7-30,30>>^ ‘For the people of Judah have done what is bad in my eyes,’ declares Jehovah. ‘They have set up their disgusting idols in the house that bears my name, in order to defile it.

[[v24-7-31]]

^<<v24-7-31,31>>^ They have built the high places of Toʹpheth, which is in the Valley of the Son of Hinʹnom,^&#42;1^ in order to burn their sons and their daughters in the fire, something that I had not commanded and that had never even come into my heart.’^&#42;2^

[NOTE]
====
. See Glossary, “Gehenna.”
. Or “had never entered my thoughts.”
====

[[v24-7-32]]

^<<v24-7-32,32>>^ “‘Therefore look! the days are coming,’ declares Jehovah, ‘when it will no longer be called Toʹpheth or the Valley of the Son of Hinʹnom^&#42;1^ but the Valley of the Slaughter. They will bury in Toʹpheth until there is no place left.

[NOTE]
====
. See Glossary, “Gehenna.”
====

[[v24-7-33]]

^<<v24-7-33,33>>^ And the dead bodies of this people will become food for the birds of the heavens and for the beasts of the earth, with no one to frighten them away.

[[v24-7-34]]

^<<v24-7-34,34>>^ I will put an end to the sound of exultation and the sound of rejoicing, the voice of the bridegroom and the voice of the bride, in the cities of Judah and in the streets of Jerusalem, for the land will be reduced to ruins.’”

'''

xref:024-jeremiah/024-jeremiah-006.adoc#v24-6-0[&#60; Capítulo Anterior] | <<v24-7-0,Topo>> | xref:024-jeremiah/024-jeremiah-008.adoc#v24-8-0[Próximo Capítulo &#62;]