include::./index.adoc[]

[[v24-17-0]]
=== Jeremiah, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-17-1]]

^<<v24-17-1,1>>^ “The sin of Judah is written down with an iron stylus.
With a diamond point it is engraved on the tablet of their heart
And on the horns of their altars,

[[v24-17-2]]

^<<v24-17-2,2>>^ While their sons remember their altars and their sacred poles^&#42;1^
Beside a luxuriant tree, on the high hills,

[NOTE]
====
. See Glossary.
====

[[v24-17-3]]

^<<v24-17-3,3>>^ On the mountains in the open countryside.
Your resources, all your treasures, I will give as plunder
—Yes, your high places because of sin throughout your territories.

[[v24-17-4]]

^<<v24-17-4,4>>^ You will forfeit, of your own accord, your inheritance that I gave you.
And I will make you serve your enemies in a land you do not know,
For you have kindled my anger like a fire.^&#42;1^
It will burn for all time.”

[NOTE]
====
. Or possibly, “For as a fire you have been ignited in my anger.”
====

[[v24-17-5]]

^<<v24-17-5,5>>^ This is what Jehovah says:
“Cursed is the man^&#42;1^ who puts his trust in mere humans,
Who relies on human power,^&#42;2^
And whose heart turns away from Jehovah.

[NOTE]
====
. Or “strong man.”
. Lit., “makes flesh his arm.”
====

[[v24-17-6]]

^<<v24-17-6,6>>^ He will become like a solitary tree in the desert.
He will not see when good comes,
But he will reside in parched places in the wilderness,
In a salt land where no one can live.

[[v24-17-7]]

^<<v24-17-7,7>>^ Blessed is the man^&#42;1^ who puts his trust in Jehovah,
Whose confidence is in Jehovah.

[NOTE]
====
. Or “strong man.”
====

[[v24-17-8]]

^<<v24-17-8,8>>^ He will become like a tree planted by the waters,
That sends out its roots to the stream.
He will not notice when heat comes,
But his leaves will always flourish.
And in the year of drought he will not be anxious,
Nor will he quit producing fruit.

[[v24-17-9]]

^<<v24-17-9,9>>^ The heart is more treacherous^&#42;1^ than anything else and is desperate.^&#42;2^
Who can know it?

[NOTE]
====
. Or “deceitful.”
. Or possibly, “incurable.”
====

[[v24-17-10]]

^<<v24-17-10,10>>^ I, Jehovah, am searching the heart,
Examining the innermost thoughts,^&#42;1^
To give to each one according to his ways,
According to the fruitage of his works.

[NOTE]
====
. Or “deepest emotions.” Lit., “kidneys.”
====

[[v24-17-11]]

^<<v24-17-11,11>>^ Like a partridge that gathers what it has not laid,
So is the one who acquires riches dishonestly.^&#42;1^
They will leave him in midlife,
And in the end he will prove senseless.”

[NOTE]
====
. Or “but not with justice.”
====

[[v24-17-12]]

^<<v24-17-12,12>>^ A glorious throne, exalted from the beginning,
Is the place of our sanctuary.

[[v24-17-13]]

^<<v24-17-13,13>>^ O Jehovah, the hope of Israel,
All those who abandon you will be put to shame.
Those apostatizing from you^&#42;1^ will be written in the dust,
Because they have abandoned Jehovah, the source of living water.

[NOTE]
====
. Lit., “from me,” apparently referring to Jehovah.
====

[[v24-17-14]]

^<<v24-17-14,14>>^ Heal me, O Jehovah, and I will be healed.
Save me, and I will be saved,
For you are the object of my praise.

[[v24-17-15]]

^<<v24-17-15,15>>^ Look! There are those saying to me:
“Where is the word of Jehovah?
Let it come, please!”

[[v24-17-16]]

^<<v24-17-16,16>>^ But as for me, I did not run away from following you as a shepherd,
Nor did I long for the day of disaster.
You well know everything my lips have spoken;
It all took place before your face!

[[v24-17-17]]

^<<v24-17-17,17>>^ Do not be a cause of terror to me.
You are my refuge in the day of calamity.

[[v24-17-18]]

^<<v24-17-18,18>>^ Let my persecutors be put to shame,
But do not let me be put to shame.
Let them be struck with terror,
But do not let me be struck with terror.
Bring the day of calamity on them,
And crush them and destroy them completely.^&#42;1^

[NOTE]
====
. Or “destroy them twice over.”
====

[[v24-17-19]]

^<<v24-17-19,19>>^ This is what Jehovah told me: “Go and stand in the gate of the sons of the people by which the kings of Judah go in and out, and in all the gates of Jerusalem.

[[v24-17-20]]

^<<v24-17-20,20>>^ You must say to them, ‘Hear the word of Jehovah, you kings of Judah, all people of Judah, and all inhabitants of Jerusalem, who enter by these gates.

[[v24-17-21]]

^<<v24-17-21,21>>^ This is what Jehovah says: “Watch yourselves,^&#42;1^ and do not carry any load on the Sabbath day or bring it in through the gates of Jerusalem.

[NOTE]
====
. Or “your souls.”
====

[[v24-17-22]]

^<<v24-17-22,22>>^ You must not bring any load out of your homes on the Sabbath day; and you must do no work at all. Keep the Sabbath day sacred, just as I commanded your forefathers.

[[v24-17-23]]

^<<v24-17-23,23>>^ But they did not listen or incline their ear, and they stubbornly refused^&#42;1^ to obey or to accept discipline.”’

[NOTE]
====
. Lit., “they hardened their neck.”
====

[[v24-17-24]]

^<<v24-17-24,24>>^ “‘“However, if you strictly obey me,” declares Jehovah, “and you bring in no load through the gates of this city on the Sabbath day, and you keep the Sabbath day sacred by not doing any work on it,

[[v24-17-25]]

^<<v24-17-25,25>>^ then kings and princes who sit on the throne of David will also enter in through the gates of this city, riding in the chariot and on horses, they and their princes, the men of Judah and the inhabitants of Jerusalem; and this city will be inhabited for all time.

[[v24-17-26]]

^<<v24-17-26,26>>^ And people will come from the cities of Judah, from the places around Jerusalem, from the land of Benjamin, from the lowland, from the mountainous region, and from the Negʹeb,^&#42;1^ bringing whole burnt offerings, sacrifices, grain offerings, frankincense, and thanksgiving sacrifices into the house of Jehovah.

[NOTE]
====
. Or “the south.”
====

[[v24-17-27]]

^<<v24-17-27,27>>^ “‘“But if you do not obey me by keeping the Sabbath day sacred and by not carrying loads and bringing them through the gates of Jerusalem on the Sabbath day, I will set her gates on fire, and it will certainly consume the fortified towers of Jerusalem and will not be extinguished.”’”

'''

xref:024-jeremiah/024-jeremiah-016.adoc#v24-16-0[&#60; Capítulo Anterior] | <<v24-17-0,Topo>> | xref:024-jeremiah/024-jeremiah-018.adoc#v24-18-0[Próximo Capítulo &#62;]