include::./index.adoc[]

[[v24-44-0]]
=== Jeremiah, 44
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-44-1]]

^<<v24-44-1,1>>^ The word that came to Jeremiah for all the Jews living in the land of Egypt, those living in Migʹdol, Tahʹpan·hes, Noph,^&#42;1^ and the land of Pathʹros, saying:

[NOTE]
====
. Or “Memphis.”
====

[[v24-44-2]]

^<<v24-44-2,2>>^ “This is what Jehovah of armies, the God of Israel, says, ‘You have seen all the calamity that I brought on Jerusalem and on all the cities of Judah, and today they are in ruins, without an inhabitant.

[[v24-44-3]]

^<<v24-44-3,3>>^ It is because of the evil things that they did to offend me by going and making sacrifices and serving other gods whom they had not known, neither you nor your forefathers.

[[v24-44-4]]

^<<v24-44-4,4>>^ I kept sending all my servants the prophets to you, sending them again and again,^&#42;1^ saying: “Please do not do this detestable thing that I hate.”

[NOTE]
====
. Lit., “rising up early and sending.”
====

[[v24-44-5]]

^<<v24-44-5,5>>^ But they did not listen or incline their ear to turn back from their evil by not making sacrifices to other gods.

[[v24-44-6]]

^<<v24-44-6,6>>^ So my wrath and my anger were poured out and burned in the cities of Judah and in the streets of Jerusalem, and they became a ruin and a wasteland, as they are today.’

[[v24-44-7]]

^<<v24-44-7,7>>^ “And now this is what Jehovah, the God of armies, the God of Israel, says, ‘Why are you causing a great calamity to yourselves,^&#42;1^ so that every man and woman, child and infant, will perish from Judah, leaving you without a remnant?

[NOTE]
====
. Or “your souls.”
====

[[v24-44-8]]

^<<v24-44-8,8>>^ Why should you offend me with the works of your hands by sacrificing to other gods in the land of Egypt where you have gone to reside? You will perish and become an object of cursing and a reproach among all the nations of the earth.

[[v24-44-9]]

^<<v24-44-9,9>>^ Have you forgotten the wicked deeds of your forefathers and the wicked deeds of the kings of Judah and the wicked deeds of their wives, as well as your own wicked deeds and the wicked deeds of your wives, that were done in the land of Judah and in the streets of Jerusalem?

[[v24-44-10]]

^<<v24-44-10,10>>^ Down to this day they have not humbled themselves,^&#42;1^ they have shown no fear, nor have they walked in my law and my statutes that I set before you and your forefathers.’

[NOTE]
====
. Or “felt crushed.”
====

[[v24-44-11]]

^<<v24-44-11,11>>^ “Therefore this is what Jehovah of armies, the God of Israel, says, ‘Here I am determined to bring calamity on you, to destroy all Judah.

[[v24-44-12]]

^<<v24-44-12,12>>^ And I will take the remnant of Judah who were determined to go to the land of Egypt to reside there, and they will all perish in the land of Egypt. They will fall by the sword and perish by the famine; from the least to the greatest, they will die by the sword and by famine. And they will become a curse, an object of horror, a malediction, and a reproach.

[[v24-44-13]]

^<<v24-44-13,13>>^ I will punish those dwelling in the land of Egypt just as I punished Jerusalem, with the sword, with famine, and with pestilence.^&#42;1^

[NOTE]
====
. Or “disease.”
====

[[v24-44-14]]

^<<v24-44-14,14>>^ And the remnant of Judah who have gone to reside in the land of Egypt will not escape or survive to return to the land of Judah. They will long^&#42;1^ to return and dwell there, but they will not return, except for a few escapees.’”

[NOTE]
====
. Or “lift up their soul.”
====

[[v24-44-15]]

^<<v24-44-15,15>>^ All the men who knew that their wives had been making sacrifices to other gods and all the wives who were standing there, who formed a large group, and all the people who were living in the land of Egypt, in Pathʹros, answered Jeremiah:

[[v24-44-16]]

^<<v24-44-16,16>>^ “We will not listen to the word that you have spoken to us in the name of Jehovah.

[[v24-44-17]]

^<<v24-44-17,17>>^ Instead, we will surely carry out every word that our mouths have spoken, to make sacrifices to the Queen of Heaven^&#42;1^ and to pour out drink offerings to her, just as we, our forefathers, our kings, and our princes did in the cities of Judah and in the streets of Jerusalem when we were satisfied with bread and were well-off, when we saw no calamity at all.

[NOTE]
====
. The title of a goddess worshipped by apostate Israelites; possibly a fertility goddess.
====

[[v24-44-18]]

^<<v24-44-18,18>>^ From the time we quit making sacrifices to the Queen of Heaven^&#42;1^ and pouring out drink offerings to her, we have lacked everything and have perished by the sword and by the famine.”

[NOTE]
====
. The title of a goddess worshipped by apostate Israelites; possibly a fertility goddess.
====

[[v24-44-19]]

^<<v24-44-19,19>>^ The women added: “And when we were making sacrifices to the Queen of Heaven^&#42;1^ and pouring out drink offerings to her, was it without the consent of our husbands that we made sacrificial cakes shaped in her image and we poured out drink offerings to her?”

[NOTE]
====
. The title of a goddess worshipped by apostate Israelites; possibly a fertility goddess.
====

[[v24-44-20]]

^<<v24-44-20,20>>^ Then Jeremiah said to all the people, to the men and their wives and to all the people who were speaking to him:

[[v24-44-21]]

^<<v24-44-21,21>>^ “The sacrifices that you, your forefathers, your kings, your princes, and the people of the land made in the cities of Judah and in the streets of Jerusalem—Jehovah remembered them and they came up into his heart!

[[v24-44-22]]

^<<v24-44-22,22>>^ Finally Jehovah could no longer put up with your evil practices and the detestable things you had done, and your land became a devastated place, an object of horror and cursing, without an inhabitant, as it is today.

[[v24-44-23]]

^<<v24-44-23,23>>^ It is because you have made these sacrifices and because you have sinned against Jehovah by not obeying the voice of Jehovah and following his law, his statutes, and his reminders that this calamity has come upon you, as is the case today.”

[[v24-44-24]]

^<<v24-44-24,24>>^ Jeremiah continued to say to all the people and to all the women: “Hear the word of Jehovah, all you of Judah who are in the land of Egypt.

[[v24-44-25]]

^<<v24-44-25,25>>^ This is what Jehovah of armies, the God of Israel, says, ‘What you and your wives have spoken with your mouths, you have fulfilled with your hands, for you said: “We will surely carry out our vows to make sacrifices to the Queen of Heaven^&#42;1^ and to pour out drink offerings to her.” You women will surely carry out your vows and perform your vows.’

[NOTE]
====
. The title of a goddess worshipped by apostate Israelites; possibly a fertility goddess.
====

[[v24-44-26]]

^<<v24-44-26,26>>^ “Therefore hear the word of Jehovah, all you of Judah who are living in the land of Egypt: ‘“Here I swear by my own great name,” says Jehovah, “that my name will no longer be called on in an oath by any man of Judah in all the land of Egypt who says, ‘As surely as the Sovereign Lord Jehovah is alive!’

[[v24-44-27]]

^<<v24-44-27,27>>^ Now I am watching over them to bring calamity and not something good; all the men of Judah in the land of Egypt will perish by the sword and by the famine, until they cease to exist.

[[v24-44-28]]

^<<v24-44-28,28>>^ Only a few will escape the sword and return from the land of Egypt to the land of Judah. Then all the remnant of Judah who came to the land of Egypt to reside there will know whose word has come true, mine or theirs!”’”

[[v24-44-29]]

^<<v24-44-29,29>>^ “‘And this is the sign for you,’ declares Jehovah, ‘that I will punish you in this place, so that you will know that my words promising calamity against you will surely come true.

[[v24-44-30]]

^<<v24-44-30,30>>^ This is what Jehovah says: “Here I am giving Pharʹaoh Hophʹra, the king of Egypt, into the hand of his enemies and of those seeking to take his life,^&#42;1^ just as I gave King Zed·e·kiʹah of Judah into the hand of King Neb·u·chad·nezʹzar^&#42;2^ of Babylon, who was his enemy and who sought to take his life.”’”^&#42;3^

[NOTE]
====
. Or “seeking his soul.”
. Lit., “Nebuchadrezzar,” a variant spelling.
. Or “was seeking his soul.”
====

'''

xref:024-jeremiah/024-jeremiah-043.adoc#v24-43-0[&#60; Capítulo Anterior] | <<v24-44-0,Topo>> | xref:024-jeremiah/024-jeremiah-045.adoc#v24-45-0[Próximo Capítulo &#62;]