include::./index.adoc[]

[[v24-36-0]]
=== Jeremiah, 36
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-36-1]]

^<<v24-36-1,1>>^ Now in the fourth year of Je·hoiʹa·kim son of Jo·siʹah, the king of Judah, this word came to Jeremiah from Jehovah, saying:

[[v24-36-2]]

^<<v24-36-2,2>>^ “Take a scroll^&#42;1^ and write in it all the words that I have spoken to you against Israel and Judah and all the nations, from the first day I spoke to you in the days of Jo·siʹah to this day.

[NOTE]
====
. Lit., “a scroll of a book.”
====

[[v24-36-3]]

^<<v24-36-3,3>>^ Perhaps when those of the house of Judah hear of all the calamity that I intend to bring on them, they may turn back from their evil ways, so that I may forgive their error and their sin.”

[[v24-36-4]]

^<<v24-36-4,4>>^ Jeremiah then called Barʹuch the son of Ne·riʹah, and Jeremiah dictated all the words that Jehovah had spoken to him, and Barʹuch wrote them in the scroll.^&#42;1^

[NOTE]
====
. Lit., “the scroll of the book.”
====

[[v24-36-5]]

^<<v24-36-5,5>>^ Then Jeremiah commanded Barʹuch: “I am confined and unable to enter the house of Jehovah.

[[v24-36-6]]

^<<v24-36-6,6>>^ So you are the one who must go in and read aloud the words of Jehovah from the scroll that you wrote at my dictation. Read them in the hearing of the people at the house of Jehovah on the day of a fast; thus you will read them to all the people of Judah who come in from their cities.

[[v24-36-7]]

^<<v24-36-7,7>>^ Perhaps their request for favor will reach Jehovah, and they will turn back, each one from his evil ways, for great is the anger and the wrath that Jehovah has declared against this people.”

[[v24-36-8]]

^<<v24-36-8,8>>^ So Barʹuch the son of Ne·riʹah did all that Jeremiah the prophet had commanded him; he read aloud from the scroll^&#42;1^ the words of Jehovah at the house of Jehovah.

[NOTE]
====
. Or “book.”
====

[[v24-36-9]]

^<<v24-36-9,9>>^ Now in the fifth year of Je·hoiʹa·kim son of Jo·siʹah, the king of Judah, in the ninth month, all the people in Jerusalem and all the people who came into Jerusalem from the cities of Judah proclaimed a fast before Jehovah.

[[v24-36-10]]

^<<v24-36-10,10>>^ Barʹuch then read aloud from the scroll^&#42;1^ the words of Jeremiah at the house of Jehovah, in the chamber^&#42;2^ of Gem·a·riʹah the son of Shaʹphan the copyist,^&#42;3^ in the upper courtyard, at the entrance of the new gate of the house of Jehovah, in the hearing of all the people.

[NOTE]
====
. Or “book.”
. Or “dining room.”
. Or “scribe.”
====

[[v24-36-11]]

^<<v24-36-11,11>>^ When Mi·caiʹah the son of Gem·a·riʹah the son of Shaʹphan heard all the words of Jehovah from the scroll,^&#42;1^

[NOTE]
====
. Or “book.”
====

[[v24-36-12]]

^<<v24-36-12,12>>^ he went down to the house^&#42;1^ of the king, to the secretary’s chamber. All the princes^&#42;2^ were sitting there: E·lishʹa·ma the secretary, De·laʹiah the son of She·maiʹah, El·naʹthan the son of Achʹbor, Gem·a·riʹah the son of Shaʹphan, Zed·e·kiʹah the son of Han·a·niʹah, and all the other princes.

[NOTE]
====
. Or “palace.”
. Or “court officials.”
====

[[v24-36-13]]

^<<v24-36-13,13>>^ Mi·caiʹah told them all the words that he had heard when Barʹuch read from the scroll^&#42;1^ in the hearing of the people.

[NOTE]
====
. Or “book.”
====

[[v24-36-14]]

^<<v24-36-14,14>>^ Then all the princes sent Je·huʹdi the son of Neth·a·niʹah the son of Shel·e·miʹah the son of Cushʹi to Barʹuch, saying: “Come and bring with you the scroll from which you read in the hearing of the people.” Barʹuch the son of Ne·riʹah took the scroll in his hand and went in to them.

[[v24-36-15]]

^<<v24-36-15,15>>^ They said to him: “Sit down, please, and read it aloud to us.” So Barʹuch read it to them.

[[v24-36-16]]

^<<v24-36-16,16>>^ Now as soon as they heard all the words, they looked at one another in dread, and they said to Barʹuch: “We must certainly tell the king all these words.”

[[v24-36-17]]

^<<v24-36-17,17>>^ And they asked Barʹuch: “Tell us, please, how you wrote all these words. Was it at his dictation?”

[[v24-36-18]]

^<<v24-36-18,18>>^ Barʹuch replied to them: “He dictated all these words to me, and I wrote them down with ink in this scroll.”^&#42;1^

[NOTE]
====
. Or “book.”
====

[[v24-36-19]]

^<<v24-36-19,19>>^ The princes said to Barʹuch: “Go and hide yourselves, you and Jeremiah, and do not let anyone know where you are.”

[[v24-36-20]]

^<<v24-36-20,20>>^ Then they went in to the king, to the courtyard, and deposited the scroll in the chamber of E·lishʹa·ma the secretary, and they told the king everything they had heard.

[[v24-36-21]]

^<<v24-36-21,21>>^ So the king sent Je·huʹdi out to get the scroll, and he brought it from the chamber of E·lishʹa·ma the secretary. Je·huʹdi began to read it in the hearing of the king and of all the princes standing by the king.

[[v24-36-22]]

^<<v24-36-22,22>>^ The king was sitting in the winter house, in the ninth month,^&#42;1^ with a fire burning in the brazier before him.

[NOTE]
====
. The last half of November and the first half of December. See App. B15.
====

[[v24-36-23]]

^<<v24-36-23,23>>^ After Je·huʹdi had read three or four columns, the king would cut off that portion with the secretary’s knife and pitch it into the fire that was burning in the brazier, until the entire scroll ended up in the fire that was in the brazier.

[[v24-36-24]]

^<<v24-36-24,24>>^ And they felt no dread; neither the king nor all his servants who heard all these words ripped their garments apart.

[[v24-36-25]]

^<<v24-36-25,25>>^ Although El·naʹthan, De·laʹiah, and Gem·a·riʹah pleaded with the king not to burn the scroll, he did not listen to them.

[[v24-36-26]]

^<<v24-36-26,26>>^ Further, the king commanded Je·rahʹme·el the son of the king, Se·raiʹah the son of Azʹri·el, and Shel·e·miʹah the son of Abʹde·el to seize Barʹuch the secretary and Jeremiah the prophet, but Jehovah kept them concealed.

[[v24-36-27]]

^<<v24-36-27,27>>^ And the word of Jehovah again came to Jeremiah after the king had burned up the scroll containing the words that Barʹuch had written at Jeremiah’s dictation, saying:

[[v24-36-28]]

^<<v24-36-28,28>>^ “Take another scroll and write on it all the same words that were on the first scroll, which King Je·hoiʹa·kim of Judah burned up.

[[v24-36-29]]

^<<v24-36-29,29>>^ And you should say against King Je·hoiʹa·kim of Judah, ‘This is what Jehovah says: “You have burned up this scroll and said, ‘Why have you written on it: “The king of Babylon will certainly come and destroy this land and empty it of man and beast”?’

[[v24-36-30]]

^<<v24-36-30,30>>^ Therefore this is what Jehovah says against King Je·hoiʹa·kim of Judah, ‘He will have no one to sit on the throne of David, and his dead body will be left exposed to the heat by day and the frost by night.

[[v24-36-31]]

^<<v24-36-31,31>>^ I will call him and his descendants^&#42;1^ and his servants to account for their error, and I will bring on them and on the inhabitants of Jerusalem and on the men of Judah all the calamity that I have spoken against them, but they did not listen.’”’”

[NOTE]
====
. Lit., “seed.”
====

[[v24-36-32]]

^<<v24-36-32,32>>^ Jeremiah then took another scroll and gave it to Barʹuch the son of Ne·riʹah, the secretary, and at Jeremiah’s dictation he wrote on it all the words of the scroll^&#42;1^ that King Je·hoiʹa·kim of Judah had burned in the fire. And many more words like those were added.

[NOTE]
====
. Or “book.”
====

'''

xref:024-jeremiah/024-jeremiah-035.adoc#v24-35-0[&#60; Capítulo Anterior] | <<v24-36-0,Topo>> | xref:024-jeremiah/024-jeremiah-037.adoc#v24-37-0[Próximo Capítulo &#62;]