include::./index.adoc[]

[[v24-28-0]]
=== Jeremiah, 28
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-28-1]]

^<<v24-28-1,1>>^ In that same year, in the beginning of the reign of King Zed·e·kiʹah of Judah, in the fourth year, in the fifth month, the prophet Han·a·niʹah the son of Azʹzur from Gibʹe·on said to me in the house of Jehovah in the presence of the priests and all the people:

[[v24-28-2]]

^<<v24-28-2,2>>^ “This is what Jehovah of armies, the God of Israel, says, ‘I will break the yoke of the king of Babylon.

[[v24-28-3]]

^<<v24-28-3,3>>^ Within two years^&#42;1^ I am bringing back to this place all the utensils of the house of Jehovah that King Neb·u·chad·nezʹzar of Babylon took from this place and brought to Babylon.’”

[NOTE]
====
. Lit., “years of days.”
====

[[v24-28-4]]

^<<v24-28-4,4>>^ “‘And I will bring back to this place Jec·o·niʹah son of Je·hoiʹa·kim, the king of Judah, and all the exiles of Judah who have gone to Babylon,’ declares Jehovah, ‘for I will break the yoke of the king of Babylon.’”

[[v24-28-5]]

^<<v24-28-5,5>>^ Then Jeremiah the prophet spoke to Han·a·niʹah the prophet in the presence of the priests and all the people who were standing in the house of Jehovah.

[[v24-28-6]]

^<<v24-28-6,6>>^ Jeremiah the prophet said: “Amen!^&#42;1^ May Jehovah do this! May Jehovah fulfill your words that you prophesied by bringing back from Babylon to this place the utensils of the house of Jehovah and all the exiled people!

[NOTE]
====
. Or “So be it!”
====

[[v24-28-7]]

^<<v24-28-7,7>>^ However, hear, please, this message that I am speaking in your ears and in the ears of all the people.

[[v24-28-8]]

^<<v24-28-8,8>>^ Long ago the prophets who were prior to me and prior to you used to prophesy concerning many lands and great kingdoms, about war, calamity, and pestilence.^&#42;1^

[NOTE]
====
. Or “disease.”
====

[[v24-28-9]]

^<<v24-28-9,9>>^ If a prophet prophesies about peace and the word of that prophet comes true, then it will be known that Jehovah truly sent that prophet.”

[[v24-28-10]]

^<<v24-28-10,10>>^ At that Han·a·niʹah the prophet took the yoke bar off the neck of the prophet Jeremiah and broke it.

[[v24-28-11]]

^<<v24-28-11,11>>^ Han·a·niʹah then said in the presence of all the people: “This is what Jehovah says, ‘Just like this I will break the yoke of King Neb·u·chad·nezʹzar of Babylon from off the neck of all the nations within two years.’” And Jeremiah the prophet went on his way.

[[v24-28-12]]

^<<v24-28-12,12>>^ After Han·a·niʹah the prophet had broken the yoke bar from off the neck of Jeremiah the prophet, this message of Jehovah came to Jeremiah:

[[v24-28-13]]

^<<v24-28-13,13>>^ “Go and say to Han·a·niʹah, ‘This is what Jehovah says: “You have broken yoke bars of wood, but instead of them you will make yoke bars of iron.”

[[v24-28-14]]

^<<v24-28-14,14>>^ For this is what Jehovah of armies, the God of Israel, says: “I will put an iron yoke bar on the neck of all these nations, to serve King Neb·u·chad·nezʹzar of Babylon, and they must serve him. Even the wild beasts of the field I will give him.”’”

[[v24-28-15]]

^<<v24-28-15,15>>^ Jeremiah the prophet then said to Han·a·niʹah the prophet: “Listen, please, O Han·a·niʹah! Jehovah has not sent you, but you have caused this people to trust in a lie.

[[v24-28-16]]

^<<v24-28-16,16>>^ Therefore this is what Jehovah says, ‘Look! I am removing you from the face of the ground. This year you will die, for you have urged rebellion against Jehovah.’”

[[v24-28-17]]

^<<v24-28-17,17>>^ So Han·a·niʹah the prophet died in that year, in the seventh month.

'''

xref:024-jeremiah/024-jeremiah-027.adoc#v24-27-0[&#60; Capítulo Anterior] | <<v24-28-0,Topo>> | xref:024-jeremiah/024-jeremiah-029.adoc#v24-29-0[Próximo Capítulo &#62;]