include::./index.adoc[]

[[v24-49-0]]
=== Jeremiah, 49
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-49-1]]

^<<v24-49-1,1>>^ For the Amʹmon·ites, this is what Jehovah says:
“Does Israel have no sons?
Does he have no heir?
Why has Malʹcam taken possession of Gad?
And why are his people living in Israel’s cities?”

[[v24-49-2]]

^<<v24-49-2,2>>^ “‘Therefore look! the days are coming,’ declares Jehovah,
‘When I will cause the alarm signal of war^&#42;1^ to be heard against Rabʹbah of the Amʹmon·ites.
She will become a desolate mound,
And her dependent^&#42;2^ towns will be set on fire.’
‘And Israel will take possession of those who dispossessed him,’ says Jehovah.

[NOTE]
====
. Or possibly, “the sound of the battle cry.”
. Or “surrounding.”
====

[[v24-49-3]]

^<<v24-49-3,3>>^ ‘Wail, O Heshʹbon, for Aʹi has been destroyed!
Cry out, O dependent towns of Rabʹbah.
Put on sackcloth.
Wail and rove about among the stone pens,^&#42;1^
For Malʹcam will go into exile,
Together with his priests and his princes.

[NOTE]
====
. Or “sheep pens.”
====

[[v24-49-4]]

^<<v24-49-4,4>>^ Why do you brag about the valleys,^&#42;1^
About your flowing plain, O unfaithful daughter,
Who trusts in her treasures
And who says: “Who will come against me?”’”

[NOTE]
====
. Or “low plains.”
====

[[v24-49-5]]

^<<v24-49-5,5>>^ “‘Here I am bringing something dreadful on you,’ declares the Sovereign Lord, Jehovah of armies,
‘From all those around you.
You will be dispersed in every direction,
And no one will gather those who flee.’”

[[v24-49-6]]

^<<v24-49-6,6>>^ “‘But afterward I will gather the captives of the Amʹmon·ites,’ declares Jehovah.”

[[v24-49-7]]

^<<v24-49-7,7>>^ For Eʹdom, this is what Jehovah of armies says:
“Is there no longer any wisdom in Teʹman?
Has good advice perished from those with understanding?
Has their wisdom rotted?

[[v24-49-8]]

^<<v24-49-8,8>>^ Flee, turn back!
Go and dwell down in the depths, O inhabitants of Deʹdan!
For I will bring disaster on Eʹsau
When the time comes to turn my attention to him.

[[v24-49-9]]

^<<v24-49-9,9>>^ If grape gatherers came in to you,
Would they not leave some behind for gleaning?
If thieves came in by night,
They would cause only as much ruin as they wanted.

[[v24-49-10]]

^<<v24-49-10,10>>^ But I will strip Eʹsau bare.
I will uncover his places of concealment,
So that he cannot hide.
His children and his brothers and his neighbors will all be destroyed,
And he will be no more.

[[v24-49-11]]

^<<v24-49-11,11>>^ Leave your fatherless children,
And I will preserve them alive,
And your widows will trust in me.”

[[v24-49-12]]

^<<v24-49-12,12>>^ For this is what Jehovah says: “Look! If those not sentenced to drink the cup must drink it, should you be left completely unpunished? You will not be left unpunished, for you must drink it.”

[[v24-49-13]]

^<<v24-49-13,13>>^ “For by myself I have sworn,” declares Jehovah, “that Bozʹrah will become an object of horror, a reproach, a devastation, and a curse; and all her cities will become perpetual ruins.”

[[v24-49-14]]

^<<v24-49-14,14>>^ I have heard a report from Jehovah,
An envoy has been sent among the nations, saying:
“Gather yourselves together and come against her;
Prepare for battle.”

[[v24-49-15]]

^<<v24-49-15,15>>^ “For look! I have made you insignificant among the nations,
Despised among men.

[[v24-49-16]]

^<<v24-49-16,16>>^ The shuddering you caused has deceived you,
The presumptuousness of your heart,
O you who reside in the retreats of the crag,
Occupying the highest hill.
Although you build your nest high up like an eagle,
I will bring you down from there,” declares Jehovah.

[[v24-49-17]]

^<<v24-49-17,17>>^ “And Eʹdom must become an object of horror. Everyone passing along by her will stare in horror and whistle on account of all her plagues.

[[v24-49-18]]

^<<v24-49-18,18>>^ Just as in the overthrow of Sodʹom and Go·morʹrah and of their neighboring towns,” Jehovah says, “no one will dwell there, and no man will settle there.

[[v24-49-19]]

^<<v24-49-19,19>>^ “Look! Someone will come up against the secure pastures like a lion from the dense thickets along the Jordan, but in a moment I will make him run away from her. And I will appoint over her the chosen one. For who is like me, and who will challenge me? What shepherd can stand before me?

[[v24-49-20]]

^<<v24-49-20,20>>^ Therefore hear, O men, the decision^&#42;1^ that Jehovah has made against Eʹdom and what he has thought out against the inhabitants of Teʹman:
Surely the little ones of the flock will be dragged away.
He will make their dwelling place desolate because of them.

[NOTE]
====
. Or “counsel.”
====

[[v24-49-21]]

^<<v24-49-21,21>>^ At the sound of their falling, the earth has quaked.
There is an outcry!
The sound has been heard as far as the Red Sea.

[[v24-49-22]]

^<<v24-49-22,22>>^ Look! Just like an eagle he will ascend and swoop down,
And he will spread out his wings over Bozʹrah.
In that day the heart of the warriors of Eʹdom
Will become like the heart of a woman in childbirth.”

[[v24-49-23]]

^<<v24-49-23,23>>^ For Damascus:
“Haʹmath and Arʹpad have been put to shame,
For they have heard a bad report.
They melt in fear.
There is anxiety in the sea that cannot be calmed.

[[v24-49-24]]

^<<v24-49-24,24>>^ Damascus has lost courage.
She has turned to flee, but panic has seized her.
Distress and pain have taken hold of her,
Like a woman who is giving birth.

[[v24-49-25]]

^<<v24-49-25,25>>^ How is it that the city of praise has not been abandoned,
The town of exultation?

[[v24-49-26]]

^<<v24-49-26,26>>^ For her young men will fall in her public squares,
And all the soldiers will perish in that day,” declares Jehovah of armies.

[[v24-49-27]]

^<<v24-49-27,27>>^ “I will set the wall of Damascus on fire,
And it will consume the fortified towers of Ben-haʹdad.”

[[v24-49-28]]

^<<v24-49-28,28>>^ For Keʹdar and the kingdoms of Haʹzor, which King Neb·u·chad·nezʹzar^&#42;1^ of Babylon struck down, this is what Jehovah says:
“Rise up, go up to Keʹdar,
And destroy the sons of the East.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-49-29]]

^<<v24-49-29,29>>^ Their tents and their flocks will be taken,
Their tent cloths and all their goods.
Their camels will be carried off,
And they will cry out to them, ‘Terror is all around!’”

[[v24-49-30]]

^<<v24-49-30,30>>^ “Flee, go far away!
Go and dwell down in the depths, O inhabitants of Haʹzor,” declares Jehovah.
“For King Neb·u·chad·nezʹzar^&#42;1^ of Babylon has devised a strategy against you,
And he has thought out a plan against you.”

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-49-31]]

^<<v24-49-31,31>>^ “Rise up, go up against the nation that is at peace,
Dwelling in security!” declares Jehovah.
“It has no doors or bars; they live in isolation.

[[v24-49-32]]

^<<v24-49-32,32>>^ Their camels will become plunder,
And their abundant livestock a spoil.
I will scatter them to every wind,^&#42;1^
Those who clip their hair at the temples,
And I will bring their disaster from every direction,” declares Jehovah.

[NOTE]
====
. Or “in every direction.”
====

[[v24-49-33]]

^<<v24-49-33,33>>^ “And Haʹzor will become a lair of jackals,
A perpetual desolation.
No one will dwell there,
And no man will settle in her.”

[[v24-49-34]]

^<<v24-49-34,34>>^ This is the word of Jehovah that came to Jeremiah the prophet concerning Eʹlam in the beginning of the reign of King Zed·e·kiʹah of Judah:

[[v24-49-35]]

^<<v24-49-35,35>>^ “This is what Jehovah of armies says, ‘Here I am breaking the bow of Eʹlam, the source^&#42;1^ of their mightiness.

[NOTE]
====
. Lit., “beginning.”
====

[[v24-49-36]]

^<<v24-49-36,36>>^ I will bring in on Eʹlam the four winds from the four extremities of the heavens, and I will scatter them to all these winds. There will not be a nation to which the dispersed ones of Eʹlam will not go.’”

[[v24-49-37]]

^<<v24-49-37,37>>^ “I will shatter the Eʹlam·ites before their enemies and before those seeking to take their life;^&#42;1^ and I will bring calamity on them, my burning anger,” declares Jehovah. “And I will send the sword after them until I have exterminated them.”

[NOTE]
====
. Or “seeking their soul.”
====

[[v24-49-38]]

^<<v24-49-38,38>>^ “And I will set my throne in Eʹlam, and I will destroy from there the king and the princes,” declares Jehovah.

[[v24-49-39]]

^<<v24-49-39,39>>^ “But in the final part of the days, I will gather the captives of Eʹlam,” declares Jehovah.

'''

xref:024-jeremiah/024-jeremiah-048.adoc#v24-48-0[&#60; Capítulo Anterior] | <<v24-49-0,Topo>> | xref:024-jeremiah/024-jeremiah-050.adoc#v24-50-0[Próximo Capítulo &#62;]