include::./index.adoc[]

[[v24-42-0]]
=== Jeremiah, 42
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-42-1]]

^<<v24-42-1,1>>^ Then all the army chiefs, and Jo·haʹnan the son of Ka·reʹah, Jez·a·niʹah the son of Ho·shaiʹah, and all the people, from the least to the greatest, approached

[[v24-42-2]]

^<<v24-42-2,2>>^ and said to Jeremiah the prophet: “Hear, please, our request for favor, and pray in our behalf to Jehovah your God, in behalf of all this remnant, for just a few of many are left, as you can see.

[[v24-42-3]]

^<<v24-42-3,3>>^ May Jehovah your God tell us the way we should walk and what we should do.”

[[v24-42-4]]

^<<v24-42-4,4>>^ Jeremiah the prophet replied to them: “I have heard you, and I am praying to Jehovah your God according to your request; and every word that Jehovah answers you, I will tell you. I will not hold back a word from you.”

[[v24-42-5]]

^<<v24-42-5,5>>^ They replied to Jeremiah: “May Jehovah be a true and faithful witness against us if we do not do exactly as Jehovah your God instructs us through you.

[[v24-42-6]]

^<<v24-42-6,6>>^ Whether good or bad, we will obey the voice of Jehovah our God, to whom we are sending you, so that it may go well with us because we obey the voice of Jehovah our God.”

[[v24-42-7]]

^<<v24-42-7,7>>^ Now ten days later the word of Jehovah came to Jeremiah.

[[v24-42-8]]

^<<v24-42-8,8>>^ So he called for Jo·haʹnan the son of Ka·reʹah and for all the army chiefs who were with him and for all the people, from the least to the greatest.

[[v24-42-9]]

^<<v24-42-9,9>>^ He said to them: “This is what Jehovah the God of Israel says, to whom you sent me to present your request for favor before him:

[[v24-42-10]]

^<<v24-42-10,10>>^ ‘If you will indeed remain in this land, then I will build you up and not tear you down, and I will plant you and not uproot you, for I will feel regret^&#42;1^ over the calamity I have caused you.

[NOTE]
====
. Or “feel grieved.”
====

[[v24-42-11]]

^<<v24-42-11,11>>^ Do not be afraid because of the king of Babylon, whom you fear.’
“‘Do not be afraid because of him,’ declares Jehovah, ‘for I am with you, to save you and to rescue you out of his hand.

[[v24-42-12]]

^<<v24-42-12,12>>^ And I will show you mercy, and he will have mercy on you and return you to your own land.

[[v24-42-13]]

^<<v24-42-13,13>>^ “‘But if you say, “No, we will not remain in this land!” and you disobey the voice of Jehovah your God

[[v24-42-14]]

^<<v24-42-14,14>>^ by saying, “No, we will go instead to the land of Egypt, where we will not see war or hear the sound of the horn or hunger for bread; there is where we will live,”

[[v24-42-15]]

^<<v24-42-15,15>>^ then hear the word of Jehovah, O remnant of Judah. This is what Jehovah of armies, the God of Israel, says: “If you are absolutely determined to go to Egypt and you go there to reside,^&#42;1^

[NOTE]
====
. Or “to reside for a while.”
====

[[v24-42-16]]

^<<v24-42-16,16>>^ then the very sword you are afraid of will catch up with you there in the land of Egypt, and the very famine you fear will follow after you to Egypt, and there you will die.

[[v24-42-17]]

^<<v24-42-17,17>>^ And all the men who are determined to go to Egypt to reside there will die by the sword, by famine, and by pestilence.^&#42;1^ None of them will survive or escape the calamity that I will bring on them.”’

[NOTE]
====
. Or “disease.”
====

[[v24-42-18]]

^<<v24-42-18,18>>^ “For this is what Jehovah of armies, the God of Israel, says: ‘Just as my anger and my wrath were poured out on the inhabitants of Jerusalem, so my wrath will be poured out on you if you go to Egypt, and you will become a curse, an object of horror, a malediction, and a reproach, and you will never again see this place.’

[[v24-42-19]]

^<<v24-42-19,19>>^ “Jehovah has spoken against you, O remnant of Judah. Do not go to Egypt. You should know for a certainty that I have warned you today

[[v24-42-20]]

^<<v24-42-20,20>>^ that your error will cost you your lives.^&#42;1^ For you sent me to Jehovah your God, saying, ‘Pray in our behalf to Jehovah our God, and tell us everything that Jehovah our God says, and we will do it.’

[NOTE]
====
. Or “souls.”
====

[[v24-42-21]]

^<<v24-42-21,21>>^ And I told you today, but you will not obey the voice of Jehovah your God or do anything he sent me to tell you.

[[v24-42-22]]

^<<v24-42-22,22>>^ Therefore, know for a certainty that by the sword, by famine, and by pestilence you will die in the place where you desire to go and reside.”

'''

xref:024-jeremiah/024-jeremiah-041.adoc#v24-41-0[&#60; Capítulo Anterior] | <<v24-42-0,Topo>> | xref:024-jeremiah/024-jeremiah-043.adoc#v24-43-0[Próximo Capítulo &#62;]