include::./index.adoc[]

[[v24-35-0]]
=== Jeremiah, 35
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-35-1]]

^<<v24-35-1,1>>^ The word that came to Jeremiah from Jehovah in the days of Je·hoiʹa·kim son of Jo·siʹah, the king of Judah, saying:

[[v24-35-2]]

^<<v24-35-2,2>>^ “Go to the house of the Reʹcha·bites and speak with them and bring them into the house of Jehovah, into one of the dining rooms;^&#42;1^ then offer them wine to drink.”

[NOTE]
====
. Or “the chambers.”
====

[[v24-35-3]]

^<<v24-35-3,3>>^ So I took Ja·az·a·niʹah the son of Jeremiah the son of Hab·az·zi·niʹah, his brothers, all his sons, and the entire house of the Reʹcha·bites

[[v24-35-4]]

^<<v24-35-4,4>>^ into the house of Jehovah. I brought them to the dining room of the sons of Haʹnan the son of Ig·da·liʹah, a man of the true God, which was next to the dining room of the princes that was above the dining room of Ma·a·seiʹah the son of Shalʹlum the doorkeeper.

[[v24-35-5]]

^<<v24-35-5,5>>^ Then I put cups and goblets full of wine before the men of the house of the Reʹcha·bites and said to them: “Drink wine.”

[[v24-35-6]]

^<<v24-35-6,6>>^ But they said: “We will not drink wine, because Je·honʹa·dab^&#42;1^ the son of Reʹchab, our forefather, gave us this command, ‘Neither you nor your sons must ever drink wine.

[NOTE]
====
. Lit., “Jonadab,” the shortened form of Jehonadab.
====

[[v24-35-7]]

^<<v24-35-7,7>>^ And you must not build a house, sow seed, or plant or obtain a vineyard. Instead, you must always dwell in tents, so that you may live for a long time in the land where you are residing as foreigners.’

[[v24-35-8]]

^<<v24-35-8,8>>^ So we continue to obey the voice of Je·honʹa·dab the son of our forefather Reʹchab in all that he commanded us, by never drinking any wine—we, our wives, our sons, and our daughters.

[[v24-35-9]]

^<<v24-35-9,9>>^ And we do not build houses to dwell in, nor do we have vineyards or fields or seed.

[[v24-35-10]]

^<<v24-35-10,10>>^ We keep living in tents and obeying all that Je·honʹa·dab^&#42;1^ our forefather commanded us.

[NOTE]
====
. Lit., “Jonadab,” the shortened form of Jehonadab.
====

[[v24-35-11]]

^<<v24-35-11,11>>^ But when King Neb·u·chad·nezʹzar^&#42;1^ of Babylon came up against the land, we said, ‘Come, let us go into Jerusalem to escape the army of the Chal·deʹans and of the Syrians,’ and now we are living in Jerusalem.”

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-35-12]]

^<<v24-35-12,12>>^ And the word of Jehovah came to Jeremiah, saying:

[[v24-35-13]]

^<<v24-35-13,13>>^ “This is what Jehovah of armies, the God of Israel, says, ‘Go and say to the men of Judah and to the inhabitants of Jerusalem: “Were you not continually urged to obey my words?” declares Jehovah.

[[v24-35-14]]

^<<v24-35-14,14>>^ “Je·honʹa·dab the son of Reʹchab commanded his descendants not to drink wine, and they have carried out his words by not drinking it to this day, thus obeying the order of their forefather. However, I have spoken to you again and again,^&#42;1^ but you have not obeyed me.

[NOTE]
====
. Lit., “rising up early and speaking.”
====

[[v24-35-15]]

^<<v24-35-15,15>>^ And I kept sending all my servants the prophets to you, sending them again and again,^&#42;1^ saying, ‘Turn back, please, each of you from your evil ways, and do what is right! Do not walk after other gods and serve them. Then you will keep dwelling in the land that I gave to you and your forefathers.’ But you did not incline your ear or listen to me.

[NOTE]
====
. Lit., “rising up early and sending.”
====

[[v24-35-16]]

^<<v24-35-16,16>>^ The descendants of Je·honʹa·dab the son of Reʹchab have carried out the order that their forefather gave them, but these people have not listened to me.”’”

[[v24-35-17]]

^<<v24-35-17,17>>^ “Therefore this is what Jehovah, the God of armies, the God of Israel, says: ‘Here I am bringing on Judah and on all the inhabitants of Jerusalem all the calamity that I have warned them about, for I have spoken to them, but they would not listen, and I kept calling to them, but they would not answer.’”

[[v24-35-18]]

^<<v24-35-18,18>>^ And Jeremiah said to the household of the Reʹcha·bites: “This is what Jehovah of armies, the God of Israel, says, ‘Because you have obeyed the order of your forefather Je·honʹa·dab and you continue to observe all his orders, doing exactly what he ordered you,

[[v24-35-19]]

^<<v24-35-19,19>>^ this is what Jehovah of armies, the God of Israel, says: “There will never fail to be a descendant of Je·honʹa·dab^&#42;1^ the son of Reʹchab to serve in my presence.”’”

[NOTE]
====
. Lit., “Jonadab,” the shortened form of Jehonadab.
====

'''

xref:024-jeremiah/024-jeremiah-034.adoc#v24-34-0[&#60; Capítulo Anterior] | <<v24-35-0,Topo>> | xref:024-jeremiah/024-jeremiah-036.adoc#v24-36-0[Próximo Capítulo &#62;]