include::./index.adoc[]

[[v24-30-0]]
=== Jeremiah, 30
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-30-1]]

^<<v24-30-1,1>>^ The word that came to Jeremiah from Jehovah, saying:

[[v24-30-2]]

^<<v24-30-2,2>>^ “This is what Jehovah the God of Israel says, ‘Write in a book all the words that I speak to you.

[[v24-30-3]]

^<<v24-30-3,3>>^ For “look! the days are coming,” declares Jehovah, “when I will gather the captives of my people, Israel and Judah,” says Jehovah, “and I will bring them back to the land that I gave to their forefathers, and they will possess it once again.”’”

[[v24-30-4]]

^<<v24-30-4,4>>^ These are the words that Jehovah spoke to Israel and Judah.

[[v24-30-5]]

^<<v24-30-5,5>>^ This is what Jehovah says:
“We have heard the sounds of trembling;
There is terror, and no peace.

[[v24-30-6]]

^<<v24-30-6,6>>^ Ask, please, whether a man can give birth.
Why, then, do I see every strong man with his hands on his stomach^&#42;1^
Like a woman giving birth?
Why has every face turned pale?

[NOTE]
====
. Or “loins.”
====

[[v24-30-7]]

^<<v24-30-7,7>>^ Alas! For that day is a terrible^&#42;1^ one.
There is none like it,
A time of distress for Jacob.
But he will be saved out of it.”

[NOTE]
====
. Lit., “great.”
====

[[v24-30-8]]

^<<v24-30-8,8>>^ “And in that day,” declares Jehovah of armies, “I will break the yoke from off your neck, and your straps^&#42;1^ I will tear in two; and no more will strangers^&#42;2^ make him^&#42;3^ their slave.

[NOTE]
====
. Lit., “bands.”
. Or “foreigners.”
. Or “them.”
====

[[v24-30-9]]

^<<v24-30-9,9>>^ They will serve Jehovah their God and David their king, whom I will raise up for them.”

[[v24-30-10]]

^<<v24-30-10,10>>^ “And you, my servant Jacob, do not be afraid,” declares Jehovah,
“And do not be terrified, O Israel.
For I will save you from far away
And your offspring from the land of their captivity.
Jacob will return and be calm and undisturbed,
With no one to make them afraid.”

[[v24-30-11]]

^<<v24-30-11,11>>^ “For I am with you,” declares Jehovah, “to save you.
But I will make an extermination among all the nations to which I scattered you;
However, you I will not exterminate.
I will discipline^&#42;1^ you to the proper degree,
And I will by no means leave you unpunished.”

[NOTE]
====
. Or “correct.”
====

[[v24-30-12]]

^<<v24-30-12,12>>^ For this is what Jehovah says:
“There is no cure for your breakdown.
Your wound is incurable.

[[v24-30-13]]

^<<v24-30-13,13>>^ There is no one to plead your cause,
No means of healing your ulcer.
There is no cure for you.

[[v24-30-14]]

^<<v24-30-14,14>>^ All your passionate lovers have forgotten you.
They no longer seek you out.
For with the stroke of an enemy I have struck you,
With the punishment of someone cruel,
Because of your great guilt and your many sins.

[[v24-30-15]]

^<<v24-30-15,15>>^ Why do you cry out because of your breakdown?
Your pain is incurable!
Because of your great guilt and your many sins
I have done this to you.

[[v24-30-16]]

^<<v24-30-16,16>>^ Therefore all those devouring you will be devoured,
And all your enemies will also go into captivity.
Those pillaging you will be pillaged,
And I will hand all those plundering you over to plundering.”

[[v24-30-17]]

^<<v24-30-17,17>>^ “But I will restore your health and heal your wounds,” declares Jehovah,
“Though they called you an outcast:
‘Zion, for whom no one searches.’”

[[v24-30-18]]

^<<v24-30-18,18>>^ This is what Jehovah says:
“Here I am gathering the captives of the tents of Jacob,
And I will have pity for his tabernacles.
The city will be rebuilt on her mound,
And the fortified tower will stand on its rightful site.

[[v24-30-19]]

^<<v24-30-19,19>>^ And from them will come thanksgiving and the sounds of laughter.
I will multiply them, and they will not be few;
I will make them numerous,^&#42;1^
And they will not be insignificant.

[NOTE]
====
. Or possibly, “honored.”
====

[[v24-30-20]]

^<<v24-30-20,20>>^ His sons will become as in the past,
And before me his assembly will be firmly established.
I will deal with all his oppressors.

[[v24-30-21]]

^<<v24-30-21,21>>^ His majestic one will be one of his own,
And from his midst his ruler will emerge.
I will cause him to come near, and he will approach me.”
“For otherwise, who would dare^&#42;1^ to approach me?” declares Jehovah.

[NOTE]
====
. Lit., “give his heart in pledge.”
====

[[v24-30-22]]

^<<v24-30-22,22>>^ “And you will become my people, and I will be your God.”

[[v24-30-23]]

^<<v24-30-23,23>>^ Look! A windstorm of Jehovah will burst out in fury,
A sweeping tempest that whirls down on the head of the wicked.

[[v24-30-24]]

^<<v24-30-24,24>>^ The burning anger of Jehovah will not turn back
Until he has carried out and accomplished the intentions of his heart.
In the final part of the days you will understand this.

'''

xref:024-jeremiah/024-jeremiah-029.adoc#v24-29-0[&#60; Capítulo Anterior] | <<v24-30-0,Topo>> | xref:024-jeremiah/024-jeremiah-031.adoc#v24-31-0[Próximo Capítulo &#62;]