include::./index.adoc[]

[[v24-31-0]]
=== Jeremiah, 31
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-31-1]]

^<<v24-31-1,1>>^ “At that time,” declares Jehovah, “I will become God to all the families of Israel, and they will become my people.”

[[v24-31-2]]

^<<v24-31-2,2>>^ This is what Jehovah says:
“The people who survived the sword found favor in the wilderness
When Israel was walking to his resting-place.”

[[v24-31-3]]

^<<v24-31-3,3>>^ From far away Jehovah appeared to me and said:
“I have loved you with an everlasting love.
That is why I have drawn you to me with loyal love.^&#42;1^

[NOTE]
====
. Or “have continued to show loyal love to you.”
====

[[v24-31-4]]

^<<v24-31-4,4>>^ Yet again I will rebuild you and you will be rebuilt.
O virgin of Israel, you will again take up your tambourines
And go forth dancing joyfully.^&#42;1^

[NOTE]
====
. Or “go forth in the dance of those who are laughing.”
====

[[v24-31-5]]

^<<v24-31-5,5>>^ You will again plant vineyards in the mountains of Sa·marʹi·a;
The planters will plant and enjoy their fruit.

[[v24-31-6]]

^<<v24-31-6,6>>^ For the day will come when the watchmen in the mountains of Eʹphra·im will call out:
‘Rise up, let us go up to Zion, to Jehovah our God.’”

[[v24-31-7]]

^<<v24-31-7,7>>^ For this is what Jehovah says:
“Cry out to Jacob with rejoicing.
Shout for joy because you are over the nations.
Proclaim it; offer praise and say,
‘O Jehovah, save your people, the remnant of Israel.’

[[v24-31-8]]

^<<v24-31-8,8>>^ I am bringing them back from the land of the north.
I will gather them together from the remotest parts of the earth.
Among them will be the blind and the lame,
The pregnant woman and the one giving birth, all together.
As a great congregation they will return here.

[[v24-31-9]]

^<<v24-31-9,9>>^ They will come weeping.
I will lead them as they beg for favor.
I will guide them to streams^&#42;1^ of water,
On a level path that will not make them stumble.
For I am a Father to Israel, and Eʹphra·im is my firstborn.”

[NOTE]
====
. Or “wadis.”
====

[[v24-31-10]]

^<<v24-31-10,10>>^ Hear the word of Jehovah, you nations,
And proclaim it among the islands far away:
“The One who scattered Israel will gather him together.
He will watch over him as a shepherd does his flock.

[[v24-31-11]]

^<<v24-31-11,11>>^ For Jehovah will redeem Jacob
And rescue^&#42;1^ him out of the hand of the one stronger than he is.

[NOTE]
====
. Or “reclaim.”
====

[[v24-31-12]]

^<<v24-31-12,12>>^ They will come and shout joyfully on the height of Zion
And become radiant over the goodness of^&#42;1^ Jehovah,
Over the grain and the new wine and the oil,
And over the young of the flock and the herd.
They^&#42;2^ will become like a well-watered garden,
And they will never languish again.”

[NOTE]
====
. Or “the good things from.”
. Or “Their soul.”
====

[[v24-31-13]]

^<<v24-31-13,13>>^ “At that time the virgin will dance joyfully,
Also the young men and the old men together.
I will change their mourning into exultation.
I will comfort them and give them joy instead of their grief.

[[v24-31-14]]

^<<v24-31-14,14>>^ I will satisfy the priests^&#42;1^ with plenty,^&#42;2^
And my people will be satisfied with my goodness,” declares Jehovah.

[NOTE]
====
. Or “the soul of the priests.”
. Lit., “fatness.”
====

[[v24-31-15]]

^<<v24-31-15,15>>^ “This is what Jehovah says:
‘A voice is heard in Raʹmah, lamentation and bitter weeping:
Rachel is weeping over her sons.^&#42;1^
She has refused to be comforted over her sons,
Because they are no more.’”

[NOTE]
====
. Or “children.”
====

[[v24-31-16]]

^<<v24-31-16,16>>^ This is what Jehovah says:
“‘Hold back your voice from weeping and your eyes from tears,
For there is a reward for your activity,’ declares Jehovah.
‘They will return from the land of the enemy.’

[[v24-31-17]]

^<<v24-31-17,17>>^ ‘And there is a hope for your future,’ declares Jehovah.
‘Your sons will return to their own territory.’”

[[v24-31-18]]

^<<v24-31-18,18>>^ “I have surely heard Eʹphra·im’s moaning,
‘You have corrected me, and I have been corrected,
Like a calf that has not been trained.
Bring me back, and I will readily turn back,
For you are Jehovah my God.

[[v24-31-19]]

^<<v24-31-19,19>>^ For after my turning back I felt remorse;
After I was made to understand I struck my thigh in grief.
I was ashamed and humiliated,
For I bore the reproach of my youth.’”

[[v24-31-20]]

^<<v24-31-20,20>>^ “Is Eʹphra·im not a precious son to me, a beloved child?
For as often as I speak against him, I do remember him still.
That is why my emotions^&#42;1^ are stirred for him.
And I will surely have pity on him,” declares Jehovah.

[NOTE]
====
. Lit., “intestines.”
====

[[v24-31-21]]

^<<v24-31-21,21>>^ “Set up road markers for yourself,
And put up signposts.
Pay attention to the highway, the way that you have to go.
Return, O virgin of Israel, return to these cities of yours.

[[v24-31-22]]

^<<v24-31-22,22>>^ How long will you waver, O unfaithful daughter?
For Jehovah has created something new in the earth:
A woman will eagerly pursue a man.”

[[v24-31-23]]

^<<v24-31-23,23>>^ This is what Jehovah of armies, the God of Israel, says: “They will again say these words in the land of Judah and in its cities when I gather back their captives: ‘May Jehovah bless you, O righteous dwelling place, O holy mountain.’

[[v24-31-24]]

^<<v24-31-24,24>>^ And in it Judah and all its cities will dwell all together, farmers and those who lead the flocks.

[[v24-31-25]]

^<<v24-31-25,25>>^ For I will satisfy the weary one^&#42;1^ and fill each one^&#42;2^ who is languishing.”

[NOTE]
====
. Or “soul.”
. Or “soul.”
====

[[v24-31-26]]

^<<v24-31-26,26>>^ At this I awoke and opened my eyes, and my sleep had been pleasurable to me.

[[v24-31-27]]

^<<v24-31-27,27>>^ “Look! The days are coming,” declares Jehovah, “when I will sow the house of Israel and the house of Judah with the seed^&#42;1^ of man and with the seed of livestock.”

[NOTE]
====
. Or “offspring.”
====

[[v24-31-28]]

^<<v24-31-28,28>>^ “And just as I watched over them to uproot, to pull down, to tear down, to destroy, and to do harm, so I will watch over them to build up and to plant,” declares Jehovah.

[[v24-31-29]]

^<<v24-31-29,29>>^ “In those days they will no longer say, ‘The fathers ate sour grapes, but the teeth of the sons were set on edge.’^&#42;1^

[NOTE]
====
. Lit., “got blunted.”
====

[[v24-31-30]]

^<<v24-31-30,30>>^ But then each one will die for his own error. Any man eating sour grapes will have his own teeth set on edge.”

[[v24-31-31]]

^<<v24-31-31,31>>^ “Look! The days are coming,” declares Jehovah, “when I will make with the house of Israel and with the house of Judah a new covenant.

[[v24-31-32]]

^<<v24-31-32,32>>^ It will not be like the covenant that I made with their forefathers on the day I took hold of their hand to lead them out of the land of Egypt, ‘my covenant that they broke, although I was their true master,’^&#42;1^ declares Jehovah.”

[NOTE]
====
. Or possibly, “their husband.”
====

[[v24-31-33]]

^<<v24-31-33,33>>^ “For this is the covenant that I will make with the house of Israel after those days,” declares Jehovah. “I will put my law within them, and in their heart I will write it. And I will become their God, and they will become my people.”

[[v24-31-34]]

^<<v24-31-34,34>>^ “And they will no longer teach each one his neighbor and each one his brother, saying, ‘Know Jehovah!’ for they will all know me, from the least to the greatest of them,” declares Jehovah. “For I will forgive their error, and I will no longer remember their sin.”

[[v24-31-35]]

^<<v24-31-35,35>>^ This is what Jehovah says,
Who gives the sun for light by day,
The laws^&#42;1^ of the moon and the stars for light by night,
Who stirs up the sea and makes its waves boisterous,
Whose name is Jehovah of armies:

[NOTE]
====
. Or “statutes.”
====

[[v24-31-36]]

^<<v24-31-36,36>>^ “‘If these regulations should ever fail,’ declares Jehovah,
‘Only then would the offspring of Israel cease as a nation before me always.’”

[[v24-31-37]]

^<<v24-31-37,37>>^ This is what Jehovah says: “‘If the heavens above could be measured and the foundations of the earth below could be explored, only then could I reject all the offspring of Israel for all they have done,’ declares Jehovah.”

[[v24-31-38]]

^<<v24-31-38,38>>^ “Look! The days are coming,” declares Jehovah, “when the city will be built to Jehovah from the Tower of Ha·nanʹel to the Corner Gate.

[[v24-31-39]]

^<<v24-31-39,39>>^ And the measuring line will go out straight ahead to the hill of Gaʹreb, and it will turn toward Goʹah.

[[v24-31-40]]

^<<v24-31-40,40>>^ And all the valley^&#42;1^ of the carcasses and of ashes^&#42;2^ and all the terraces as far as the Kidʹron Valley, clear to the corner of the Horse Gate toward the east, will be something holy to Jehovah. It will never again be uprooted or torn down.”

[NOTE]
====
. Or “low plain.”
. Or “fatty ashes,” that is, ashes soaked with the fat of the sacrifices.
====

'''

xref:024-jeremiah/024-jeremiah-030.adoc#v24-30-0[&#60; Capítulo Anterior] | <<v24-31-0,Topo>> | xref:024-jeremiah/024-jeremiah-032.adoc#v24-32-0[Próximo Capítulo &#62;]