include::./index.adoc[]

[[v24-9-0]]
=== Jeremiah, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-9-1]]

^<<v24-9-1,1>>^ O that my head were waters,
My eyes a fountain of tears!
Then I would weep day and night
For the slain ones of my people.

[[v24-9-2]]

^<<v24-9-2,2>>^ O that I had a traveler’s lodging place in the wilderness!
Then I would leave my people and go away from them,
For they are all adulterers,
A band of treacherous people.

[[v24-9-3]]

^<<v24-9-3,3>>^ They bend their tongue like a bow;
Falsehood, not faithfulness, prevails in the land.
“They advance from evil to evil,
And they pay no attention to me,” declares Jehovah.

[[v24-9-4]]

^<<v24-9-4,4>>^ “Everyone, be on guard against your neighbor,
And do not trust even your brother.
For every brother is a betrayer,
And every neighbor is a slanderer.

[[v24-9-5]]

^<<v24-9-5,5>>^ Each one cheats his neighbor,
And no one speaks truth.
They have taught their tongue to speak falsehood.
They wear themselves out doing what is wrong.

[[v24-9-6]]

^<<v24-9-6,6>>^ You are living in the midst of deception.
In their deception they refused to know me,” declares Jehovah.

[[v24-9-7]]

^<<v24-9-7,7>>^ Therefore this is what Jehovah of armies says:
“I will smelt them and test them,
For what else can I do with the daughter of my people?

[[v24-9-8]]

^<<v24-9-8,8>>^ Their tongue is a deadly arrow that speaks deception.
With his mouth a person speaks of peace to his neighbor,
But inside he lays an ambush.”

[[v24-9-9]]

^<<v24-9-9,9>>^ “Should I not call them to account for these things?” declares Jehovah.
“Should I^&#42;1^ not avenge myself on such a nation?

[NOTE]
====
. Or “my soul.”
====

[[v24-9-10]]

^<<v24-9-10,10>>^ I will weep and lament over the mountains
And take up a dirge^&#42;1^ over the pastures of the wilderness,
For they have been burned up so that no man passes through,
And the sound of livestock is not heard.
The birds of heaven and the beasts have fled; they are gone.

[NOTE]
====
. Or “song of mourning.”
====

[[v24-9-11]]

^<<v24-9-11,11>>^ I will make Jerusalem piles of stones, the lair of jackals,
And I will make the cities of Judah desolate, without an inhabitant.

[[v24-9-12]]

^<<v24-9-12,12>>^ Who is wise enough to understand this?
To whom has the mouth of Jehovah spoken, that he may declare it?
Why has the land perished?
Why is it scorched like the wilderness,
So that no one is passing through?”

[[v24-9-13]]

^<<v24-9-13,13>>^ Jehovah replied: “Because of their rejecting my law^&#42;1^ that I set before them, and because they have not followed it and obeyed my voice.

[NOTE]
====
. Or “instruction.”
====

[[v24-9-14]]

^<<v24-9-14,14>>^ Instead, they stubbornly followed their own hearts, and they followed the Baʹal images, as their fathers had taught them to do.

[[v24-9-15]]

^<<v24-9-15,15>>^ Therefore this is what Jehovah of armies, the God of Israel, says, ‘Here I am making this people eat wormwood, and I will make them drink poisoned water.

[[v24-9-16]]

^<<v24-9-16,16>>^ I will scatter them among the nations that they and their fathers have not known, and I will send a sword after them until I will have exterminated them.’

[[v24-9-17]]

^<<v24-9-17,17>>^ This is what Jehovah of armies says,
‘Behave with understanding.
Summon the women who sing dirges,^&#42;1^
And send for the skilled women to come,

[NOTE]
====
. Or “songs of mourning.”
====

[[v24-9-18]]

^<<v24-9-18,18>>^ So that they may hurry and raise a lamentation for us,
So that our eyes may stream with tears
And our eyelids trickle with water.

[[v24-9-19]]

^<<v24-9-19,19>>^ For the sound of lamentation has been heard from Zion:
“How we have been devastated!
How great our shame is!
For we have left the land, and they have thrown down our homes.”

[[v24-9-20]]

^<<v24-9-20,20>>^ You women, hear the word of Jehovah.
May your ear receive the word of his mouth.
Teach your daughters this lamentation,
And teach one another this dirge.^&#42;1^

[NOTE]
====
. Or “song of mourning.”
====

[[v24-9-21]]

^<<v24-9-21,21>>^ For death has come up through our windows;
It has entered our fortified towers
To take away the children from the streets
And the young men from the public squares.’

[[v24-9-22]]

^<<v24-9-22,22>>^ Say, ‘This is what Jehovah declares:
“The dead bodies of people will fall like manure on the surface of the field,
Like a row of newly cut grain after the reaper,
With no one to gather them up.”’”

[[v24-9-23]]

^<<v24-9-23,23>>^ This is what Jehovah says:
“Let not the wise man boast about his wisdom;
Let not the mighty man boast about his mightiness;
And let not the rich man boast about his riches.”

[[v24-9-24]]

^<<v24-9-24,24>>^ “But let the one boasting boast about this:
That he has insight and knowledge of me,
That I am Jehovah, the One showing loyal love, justice, and righteousness in the earth,
For in these things I take delight,” declares Jehovah.

[[v24-9-25]]

^<<v24-9-25,25>>^ “Look! Days are coming,” declares Jehovah, “and I will hold an accounting with everyone circumcised and yet uncircumcised,

[[v24-9-26]]

^<<v24-9-26,26>>^ with Egypt and Judah and Eʹdom and the Amʹmon·ites and Moʹab and with all of those with hair clipped at the temples who are dwelling in the wilderness; for all the nations are uncircumcised, and all the house of Israel are uncircumcised in heart.”

'''

xref:024-jeremiah/024-jeremiah-008.adoc#v24-8-0[&#60; Capítulo Anterior] | <<v24-9-0,Topo>> | xref:024-jeremiah/024-jeremiah-010.adoc#v24-10-0[Próximo Capítulo &#62;]