include::./index.adoc[]

[[v24-46-0]]
=== Jeremiah, 46
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-46-1]]

^<<v24-46-1,1>>^ This is the word of Jehovah to Jeremiah the prophet concerning the nations:

[[v24-46-2]]

^<<v24-46-2,2>>^ For Egypt, concerning the army of Pharʹaoh Neʹcho the king of Egypt, who was along the Eu·phraʹtes River and was defeated at Carʹche·mish by King Neb·u·chad·nezʹzar^&#42;1^ of Babylon in the fourth year of Je·hoiʹa·kim son of Jo·siʹah, the king of Judah:

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-46-3]]

^<<v24-46-3,3>>^ “Prepare your bucklers^&#42;1^ and large shields,
And advance to the battle.

[NOTE]
====
. A small shield, often carried by archers.
====

[[v24-46-4]]

^<<v24-46-4,4>>^ Harness the horses and mount, you horsemen.
Take your positions and put on your helmets.
Polish the lances and put on your coats of mail.

[[v24-46-5]]

^<<v24-46-5,5>>^ ‘Why do I see them terror-stricken?
They are retreating, their warriors are crushed.
They have fled in panic, their warriors have not turned around.
There is terror all around,’ declares Jehovah.

[[v24-46-6]]

^<<v24-46-6,6>>^ ‘The swift cannot flee, and the warriors cannot escape.
In the north, by the bank of the Eu·phraʹtes River,
They have stumbled and fallen.’

[[v24-46-7]]

^<<v24-46-7,7>>^ Who is this coming up like the Nile River,
Like the rivers of surging waters?

[[v24-46-8]]

^<<v24-46-8,8>>^ Egypt comes up just like the Nile River,
Like rivers of surging waters,
And it says, ‘I will go up and cover the earth.
I will destroy the city and those inhabiting it.’

[[v24-46-9]]

^<<v24-46-9,9>>^ Go up, you horses!
Drive madly, you chariots!
Let the warriors advance,
Cush and Put, who handle the shield,
And the Luʹdim, who handle and bend^&#42;1^ the bow.

[NOTE]
====
. Lit., “tread.”
====

[[v24-46-10]]

^<<v24-46-10,10>>^ “That day belongs to the Sovereign Lord, Jehovah of armies, the day of vengeance for taking revenge on his adversaries. And the sword will devour and satisfy itself and take its fill of their blood, for the Sovereign Lord, Jehovah of armies, has a sacrifice^&#42;1^ in the land of the north by the Eu·phraʹtes River.

[NOTE]
====
. Or “slaughter.”
====

[[v24-46-11]]

^<<v24-46-11,11>>^ Go up to Gilʹe·ad to get balsam,
O virgin daughter of Egypt.
In vain you have multiplied your remedies,
For there is no cure for you.

[[v24-46-12]]

^<<v24-46-12,12>>^ The nations have heard your dishonor,
And your outcry has filled the land.
For warrior stumbles against warrior,
And they both fall down together.”

[[v24-46-13]]

^<<v24-46-13,13>>^ This is the word that Jehovah spoke to Jeremiah the prophet regarding the coming of King Neb·u·chad·nezʹzar^&#42;1^ of Babylon to strike down the land of Egypt:

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-46-14]]

^<<v24-46-14,14>>^ “Declare it in Egypt, proclaim it in Migʹdol.
Proclaim it in Noph^&#42;1^ and in Tahʹpan·hes.
Say, ‘Take your positions and prepare yourselves,
For a sword will devour all around you.

[NOTE]
====
. Or “Memphis.”
====

[[v24-46-15]]

^<<v24-46-15,15>>^ Why have your powerful men been swept away?
They did not stand their ground,
For Jehovah has pushed them down.

[[v24-46-16]]

^<<v24-46-16,16>>^ In great numbers they are stumbling and falling.
They are saying to one another:
“Get up! Let us return to our people and our homeland
Because of the cruel sword.”’

[[v24-46-17]]

^<<v24-46-17,17>>^ There they have proclaimed,
‘Pharʹaoh king of Egypt is just a meaningless noise
Who has let the opportunity^&#42;1^ pass by.’

[NOTE]
====
. Lit., “appointed time.”
====

[[v24-46-18]]

^<<v24-46-18,18>>^ ‘As surely as I am alive,’ declares the King, whose name is Jehovah of armies,
‘He^&#42;1^ will come in like Taʹbor among the mountains
And like Carʹmel by the sea.

[NOTE]
====
. That is, Egypt’s conqueror.
====

[[v24-46-19]]

^<<v24-46-19,19>>^ Prepare your baggage for exile,
O daughter inhabiting Egypt.
For Noph^&#42;1^ will become an object of horror;
It will be set afire^&#42;2^ and left without an inhabitant.

[NOTE]
====
. Or “Memphis.”
. Or possibly, “will become a wasteland.”
====

[[v24-46-20]]

^<<v24-46-20,20>>^ Egypt is like a good-looking heifer,
But stinging flies will come against her from the north.

[[v24-46-21]]

^<<v24-46-21,21>>^ Even her hired soldiers in her midst are like fattened calves,
But they have also turned back and fled together.
They could not stand their ground,
For the day of their disaster has come upon them,
Their time of reckoning.’

[[v24-46-22]]

^<<v24-46-22,22>>^ ‘Her sound is like that of a slithering serpent,
For they come after her in force, with axes,
Like men cutting down trees.^&#42;1^

[NOTE]
====
. Or “gathering wood.”
====

[[v24-46-23]]

^<<v24-46-23,23>>^ They will cut down her forest,’ declares Jehovah, ‘though it seemed impenetrable.
For they are more numerous than locusts, without number.

[[v24-46-24]]

^<<v24-46-24,24>>^ The daughter of Egypt will be put to shame.
She will be handed over to the people of the north.’

[[v24-46-25]]

^<<v24-46-25,25>>^ “Jehovah of armies, the God of Israel, says: ‘Now I am turning my attention to Aʹmon from No,^&#42;1^ to Pharʹaoh, to Egypt, to her gods, and to her kings—yes, to Pharʹaoh and all those trusting in him.’

[NOTE]
====
. That is, Thebes.
====

[[v24-46-26]]

^<<v24-46-26,26>>^ “‘And I will hand them over to those seeking to take their life,^&#42;1^ to King Neb·u·chad·nezʹzar^&#42;2^ of Babylon and his servants. But afterward she will be inhabited as in times past,’ declares Jehovah.

[NOTE]
====
. Or “seeking their soul.”
. Lit., “Nebucha­drezzar,” a variant spelling.
====

[[v24-46-27]]

^<<v24-46-27,27>>^ ‘As for you, do not be afraid, my servant Jacob,
And do not be terrified, O Israel.
For I will save you from far away
And your offspring^&#42;1^ from the land of their captivity.
Jacob will return and be calm and undisturbed,
With no one to make them afraid.

[NOTE]
====
. Lit., “seed.”
====

[[v24-46-28]]

^<<v24-46-28,28>>^ So do not be afraid, my servant Jacob,’ declares Jehovah, ‘for I am with you.
I will make an extermination among all the nations where I dispersed you,
But you I will not exterminate.
I will discipline^&#42;1^ you to the proper degree,
But I will by no means leave you unpunished.’”

[NOTE]
====
. Or “correct.”
====

'''

xref:024-jeremiah/024-jeremiah-045.adoc#v24-45-0[&#60; Capítulo Anterior] | <<v24-46-0,Topo>> | xref:024-jeremiah/024-jeremiah-047.adoc#v24-47-0[Próximo Capítulo &#62;]