include::./index.adoc[]

[[v24-3-0]]
=== Jeremiah, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-3-1]]

^<<v24-3-1,1>>^ People ask: “If a man sends his wife away and she leaves him and becomes another man’s, should he return to her anymore?”
Has that land not been utterly polluted?
“You have committed prostitution with many companions,
And should you now return to me?” declares Jehovah.

[[v24-3-2]]

^<<v24-3-2,2>>^ “Raise your eyes to the bare hills and see.
Where have you not been raped?
You sat along the roadways for them,
Like a nomad^&#42;1^ in the wilderness.
You keep polluting the land
With your prostitution and your wickedness.

[NOTE]
====
. Lit., “an Ara­bian.”
====

[[v24-3-3]]

^<<v24-3-3,3>>^ So showers of rain are withheld,
And there is no rain in the spring.
You have the brazen look^&#42;1^ of a wife who commits prostitution;
You refuse to feel shame.

[NOTE]
====
. Lit., “the forehead.”
====

[[v24-3-4]]

^<<v24-3-4,4>>^ But now you call out to me,
‘My Father, you are the companion of my youth!

[[v24-3-5]]

^<<v24-3-5,5>>^ Should one stay resentful forever,
Or always hold a grudge?’
This is what you say,
But you keep doing all the evil you are capable of doing.”

[[v24-3-6]]

^<<v24-3-6,6>>^ In the days of King Jo·siʹah, Jehovah said to me: “‘Have you seen what unfaithful Israel has done? She has gone up on every high mountain and underneath every luxuriant tree to commit prostitution.

[[v24-3-7]]

^<<v24-3-7,7>>^ Even after she did all these things, I kept telling her to return to me, but she did not return; and Judah kept watching her treacherous sister.

[[v24-3-8]]

^<<v24-3-8,8>>^ When I saw that, I sent unfaithful Israel away with a full certificate of divorce because of her adultery. But her treacherous sister Judah did not become afraid; she too went out and committed prostitution.

[[v24-3-9]]

^<<v24-3-9,9>>^ She took her prostitution lightly, and she kept polluting the land and committing adultery with stones and with trees.

[[v24-3-10]]

^<<v24-3-10,10>>^ Despite all this, her treacherous sister Judah did not return to me with all her heart, only in pretense,’ declares Jehovah.”

[[v24-3-11]]

^<<v24-3-11,11>>^ Jehovah then said to me: “Unfaithful Israel has shown herself^&#42;1^ to be more righteous than treacherous Judah.

[NOTE]
====
. Or “her soul.”
====

[[v24-3-12]]

^<<v24-3-12,12>>^ Go and proclaim these words to the north:
“‘“Return, O renegade Israel,” declares Jehovah.’ ‘“I will not look down angrily^&#42;1^ on you, for I am loyal,” declares Jehovah.’ ‘“I will not stay resentful forever.

[NOTE]
====
. Lit., “make my face fall.”
====

[[v24-3-13]]

^<<v24-3-13,13>>^ Only acknowledge your guilt, for you have rebelled against Jehovah your God. You continued scattering your favors^&#42;1^ to strangers^&#42;2^ under every luxuriant tree, but you would not obey my voice,” declares Jehovah.’”

[NOTE]
====
. Lit., “ways.”
. Or “foreign gods.”
====

[[v24-3-14]]

^<<v24-3-14,14>>^ “Return, you renegade sons,” declares Jehovah. “For I have become your true master;^&#42;1^ and I will take you, one from a city and two from a family, and I will bring you to Zion.

[NOTE]
====
. Or possibly, “your husband.”
====

[[v24-3-15]]

^<<v24-3-15,15>>^ And I will give you shepherds after my own heart, and they will feed you with knowledge and insight.

[[v24-3-16]]

^<<v24-3-16,16>>^ You will become many and will bear fruit in the land in those days,” declares Jehovah. “No more will they say, ‘The ark of the covenant of Jehovah!’ It will not come up into the heart, nor will they remember it or miss it, and it will not be made again.

[[v24-3-17]]

^<<v24-3-17,17>>^ At that time they will call Jerusalem the throne of Jehovah; and all the nations will be brought together to the name of Jehovah at Jerusalem, and they will no longer stubbornly follow their own wicked heart.”

[[v24-3-18]]

^<<v24-3-18,18>>^ “In those days they will walk together, the house of Judah alongside the house of Israel, and together they will come from the land of the north into the land that I gave to your forefathers as an inheritance.

[[v24-3-19]]

^<<v24-3-19,19>>^ And I thought, ‘How I placed you among the sons and gave you the desirable land, the most beautiful inheritance among the nations!’^&#42;1^ I also thought that you would call me, ‘My Father!’ and that you would not turn away from following me.

[NOTE]
====
. Lit., “of the armies of the nations.”
====

[[v24-3-20]]

^<<v24-3-20,20>>^ ‘Truly as a wife treacherously leaves her husband,^&#42;1^ so also you, O house of Israel, have dealt treacherously with me,’ declares Jehovah.”

[NOTE]
====
. Lit., “companion.”
====

[[v24-3-21]]

^<<v24-3-21,21>>^ On the bare hills a sound is heard,
The weeping and the pleading of the people of Israel,
For they have distorted their way;
They have forgotten Jehovah their God.

[[v24-3-22]]

^<<v24-3-22,22>>^ “Return, you renegade sons.
I will heal your renegade condition.”
“Here we are! We have come to you,
For you, O Jehovah, are our God.

[[v24-3-23]]

^<<v24-3-23,23>>^ Truly the hills and the turmoil on the mountains are a delusion.
Truly in Jehovah our God is the salvation of Israel.

[[v24-3-24]]

^<<v24-3-24,24>>^ But the shameful thing^&#42;1^ has consumed the toil of our forefathers since our youth,
Their flocks and their herds,
Their sons and their daughters.

[NOTE]
====
. Or “the shameful god.”
====

[[v24-3-25]]

^<<v24-3-25,25>>^ Let us lie down in our shame,
And let our disgrace cover us,
For we have sinned against Jehovah our God,
We and our fathers since our youth until this day,
And we have not obeyed the voice of Jehovah our God.”

'''

xref:024-jeremiah/024-jeremiah-002.adoc#v24-2-0[&#60; Capítulo Anterior] | <<v24-3-0,Topo>> | xref:024-jeremiah/024-jeremiah-004.adoc#v24-4-0[Próximo Capítulo &#62;]