include::./index.adoc[]

[[v24-2-0]]
=== Jeremiah, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-2-1]]

^<<v24-2-1,1>>^ The word of Jehovah came to me, saying:

[[v24-2-2]]

^<<v24-2-2,2>>^ “Go and proclaim in the ears of Jerusalem, ‘This is what Jehovah says:
“I well remember the devotion^&#42;1^ of your youth,
The love you showed when you were engaged to marry,
How you followed me in the wilderness,
In a land not sown with seed.

[NOTE]
====
. Or “loyal love.”
====

[[v24-2-3]]

^<<v24-2-3,3>>^ Israel was holy to Jehovah, the firstfruits of his harvest.”’
‘Anyone devouring him would become guilty.
Disaster would come upon them,’ declares Jehovah.”

[[v24-2-4]]

^<<v24-2-4,4>>^ Hear the word of Jehovah, O house of Jacob,
And all you families of the house of Israel.

[[v24-2-5]]

^<<v24-2-5,5>>^ This is what Jehovah says:
“What fault did your forefathers find in me,
So that they strayed so far from me,
And they walked after worthless idols and became worthless themselves?

[[v24-2-6]]

^<<v24-2-6,6>>^ They did not ask, ‘Where is Jehovah,
The One who brought us out of the land of Egypt,
Who led us through the wilderness,
Through a land of deserts and pits,
Through a land of drought and of deep shadow,
Through a land where no man travels
And where no humans dwell?’

[[v24-2-7]]

^<<v24-2-7,7>>^ I then brought you to a land of orchards,
To eat its fruitage and its good things.
But you came in and defiled my land;
You made my inheritance something detestable.

[[v24-2-8]]

^<<v24-2-8,8>>^ The priests did not ask, ‘Where is Jehovah?’
Those handling the Law did not know me,
The shepherds rebelled against me,
The prophets prophesied by Baʹal,
And they followed those who could bring no benefit.

[[v24-2-9]]

^<<v24-2-9,9>>^ ‘So I will contend further with you,’ declares Jehovah,
‘And I will contend with the sons of your sons.’

[[v24-2-10]]

^<<v24-2-10,10>>^ ‘But cross over to the coastlands^&#42;1^ of the Kitʹtim and see.
Yes, send to Keʹdar and consider carefully;
See whether anything like this has happened.

[NOTE]
====
. Or “islands.”
====

[[v24-2-11]]

^<<v24-2-11,11>>^ Has a nation ever changed its gods for those that are not gods?
But my own people have exchanged my glory for what is useless.

[[v24-2-12]]

^<<v24-2-12,12>>^ Stare in amazement at this, you heavens;
Shudder in absolute horror,’ declares Jehovah,

[[v24-2-13]]

^<<v24-2-13,13>>^ ‘Because my people have done two bad things:
They have abandoned me, the source of living water,
And dug^&#42;1^ for themselves cisterns,
Broken cisterns, that cannot hold water.’

[NOTE]
====
. Or “hewed out,” likely from rock.
====

[[v24-2-14]]

^<<v24-2-14,14>>^ ‘Is Israel a servant or a slave born in the household?
Then why has he been given over to plunder?

[[v24-2-15]]

^<<v24-2-15,15>>^ Against him young lions^&#42;1^ roar;
They have raised their voice.
They made his land an object of horror.
His cities have been set on fire, so that there is no inhabitant.

[NOTE]
====
. Or “maned young lions.”
====

[[v24-2-16]]

^<<v24-2-16,16>>^ The people of Noph^&#42;1^ and Tahʹpan·es feed on the crown of your head.

[NOTE]
====
. Or “Memphis.”
====

[[v24-2-17]]

^<<v24-2-17,17>>^ Have you not brought this on yourself
By abandoning Jehovah your God
While he was leading you in the way?

[[v24-2-18]]

^<<v24-2-18,18>>^ Now why do you wish for the way to Egypt
To drink the waters of Shiʹhor?^&#42;1^
Why do you wish for the way to As·syrʹi·a
To drink the waters of the River?^&#42;2^

[NOTE]
====
. That is, a branch of the Nile River.
. That is, the Euphrates.
====

[[v24-2-19]]

^<<v24-2-19,19>>^ Your wickedness should correct you,
And your own unfaithfulness should reprove you.
Know and realize how bad and bitter it is
To abandon Jehovah your God;
You have shown no fear of me,’ declares the Sovereign Lord, Jehovah of armies.

[[v24-2-20]]

^<<v24-2-20,20>>^ ‘For long ago I smashed your yoke
And tore off your shackles.
But you said: “I am not going to serve,”
For on every high hill and under every luxuriant tree
You were lying sprawled out, prostituting yourself.

[[v24-2-21]]

^<<v24-2-21,21>>^ I planted you as a choice red vine, all of it pure seed;
So how have you turned into the degenerate shoots of a foreign vine before me?’

[[v24-2-22]]

^<<v24-2-22,22>>^ ‘Though you should wash with soda^&#42;1^ and use much lye,^&#42;2^
Your guilt would still be a stain before me,’ declares the Sovereign Lord Jehovah.

[NOTE]
====
. Or “alkali.”
. Or “soap.”
====

[[v24-2-23]]

^<<v24-2-23,23>>^ How can you say, ‘I have not defiled myself.
I have not followed the Baʹals’?
Look at your way in the valley.
Consider what you have done.
You are like a swift, young she-camel,
Aimlessly running back and forth in her ways,

[[v24-2-24]]

^<<v24-2-24,24>>^ A wild donkey accustomed to the wilderness,
Sniffing the wind in her lust.^&#42;1^
Who can restrain her when she is in heat?
None of those looking for her will need to weary themselves.
In her season^&#42;2^ they will find her.

[NOTE]
====
. Or “at the craving of her soul.”
. Lit., “her month.”
====

[[v24-2-25]]

^<<v24-2-25,25>>^ Keep your feet from going bare
And your throat from thirst.
But you said, ‘It is hopeless!
No! I have fallen in love with strangers,^&#42;1^
And I will follow them.’

[NOTE]
====
. Or “foreign gods.”
====

[[v24-2-26]]

^<<v24-2-26,26>>^ Like the shame of a thief when he is caught,
So the house of Israel has been put to shame,
They, their kings and their princes,
Their priests and their prophets.

[[v24-2-27]]

^<<v24-2-27,27>>^ They say to a tree, ‘You are my father,’
And to a stone, ‘You gave birth to me.’
But to me they turn their back and not their face.
And in the time of their calamity they will say,
‘Rise up and save us!’

[[v24-2-28]]

^<<v24-2-28,28>>^ Now where are your gods that you made for yourself?
Let them rise up if they can save you in your time of calamity,
For your gods have become as numerous as your cities, O Judah.

[[v24-2-29]]

^<<v24-2-29,29>>^ ‘Why do you keep contending against me?
Why have all of you rebelled against me?’ declares Jehovah.

[[v24-2-30]]

^<<v24-2-30,30>>^ I have struck your sons in vain.
They would accept no discipline;
Your own sword devoured your prophets,
Like a marauding lion.

[[v24-2-31]]

^<<v24-2-31,31>>^ O generation, consider for yourselves the word of Jehovah.
Have I become like a wilderness to Israel
Or a land of oppressive darkness?
Why have these, my people, said, ‘We roam freely.
We will come to you no more’?

[[v24-2-32]]

^<<v24-2-32,32>>^ Can a virgin forget her ornaments,
A bride her breastbands?^&#42;1^
And yet my own people have forgotten me for countless days.

[NOTE]
====
. Or “her wedding sash?”
====

[[v24-2-33]]

^<<v24-2-33,33>>^ How skillfully, O woman, you set your course to seek love!
You have trained yourself in the ways of wickedness.

[[v24-2-34]]

^<<v24-2-34,34>>^ Even your skirts are stained with the blood of the innocent poor ones,^&#42;1^
Though I did not find them in the act of breaking in;
It is on all your skirts.

[NOTE]
====
. Or “souls.”
====

[[v24-2-35]]

^<<v24-2-35,35>>^ But you say, ‘I am innocent.
Surely his anger has turned back from me.’
Now I am bringing judgment against you
Because you say, ‘I have not sinned.’

[[v24-2-36]]

^<<v24-2-36,36>>^ Why do you treat so lightly your unstable course?
You will become ashamed of Egypt too,
Just as you became ashamed of As·syrʹi·a.

[[v24-2-37]]

^<<v24-2-37,37>>^ For this reason also you will go out with your hands on your head,
For Jehovah has rejected those in whom you put confidence;
They will not bring you success.”

'''

xref:024-jeremiah/024-jeremiah-001.adoc#v24-1-0[&#60; Capítulo Anterior] | <<v24-2-0,Topo>> | xref:024-jeremiah/024-jeremiah-003.adoc#v24-3-0[Próximo Capítulo &#62;]