include::./index.adoc[]

[[v24-11-0]]
=== Jeremiah, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-11-1]]

^<<v24-11-1,1>>^ This is the word that came to Jeremiah from Jehovah, saying:

[[v24-11-2]]

^<<v24-11-2,2>>^ “Hear the words of this covenant, you people!
“Speak^&#42;1^ them to the men of Judah and to the inhabitants of Jerusalem

[NOTE]
====
. Apparently addressed to Jeremiah.
====

[[v24-11-3]]

^<<v24-11-3,3>>^ and say to them, ‘This is what Jehovah the God of Israel says: “Cursed is the man who does not obey the words of this covenant,

[[v24-11-4]]

^<<v24-11-4,4>>^ which I commanded your forefathers on the day I brought them out of the land of Egypt, out of the iron-smelting furnace, saying, ‘Obey my voice, and do all the things that I command you; and you will become my people and I will be your God,

[[v24-11-5]]

^<<v24-11-5,5>>^ so that I may fulfill the oath that I swore to your forefathers, to give them the land flowing with milk and honey, as it is this day.’”’”
And I answered: “Amen,^&#42;1^ O Jehovah.”

[NOTE]
====
. Or “So be it.”
====

[[v24-11-6]]

^<<v24-11-6,6>>^ Jehovah then said to me: “Proclaim all these words in the cities of Judah and in the streets of Jerusalem: ‘Hear the words of this covenant, and carry them out.

[[v24-11-7]]

^<<v24-11-7,7>>^ For I solemnly admonished your forefathers in the day I brought them out of the land of Egypt and to this day, admonishing them again and again:^&#42;1^ “Obey my voice.”

[NOTE]
====
. Lit., “rising up early and admonishing.”
====

[[v24-11-8]]

^<<v24-11-8,8>>^ But they did not listen or incline their ear; instead, each kept stubbornly following his own wicked heart. So I brought on them all the words of this covenant that I commanded them to do and that they refused to carry out.’”

[[v24-11-9]]

^<<v24-11-9,9>>^ Jehovah then said to me: “There is a conspiracy among the men of Judah and the inhabitants of Jerusalem.

[[v24-11-10]]

^<<v24-11-10,10>>^ They have returned to the errors of their forefathers of old, who refused to obey my words. They too have followed other gods and have served them. The house of Israel and the house of Judah have broken my covenant that I made with their forefathers.

[[v24-11-11]]

^<<v24-11-11,11>>^ Therefore this is what Jehovah says, ‘Here I am bringing on them a calamity that they will not be able to escape. When they call to me for help, I will not listen to them.

[[v24-11-12]]

^<<v24-11-12,12>>^ Then the cities of Judah and the inhabitants of Jerusalem will go to the gods to which they are making sacrifices^&#42;1^ and call for help, but these will by no means save them in the time of their calamity.

[NOTE]
====
. Or “sacrificial smoke.”
====

[[v24-11-13]]

^<<v24-11-13,13>>^ For your gods have become as many as your cities, O Judah, and you have set up as many altars to the shameful thing^&#42;1^ as there are streets in Jerusalem, altars to make sacrifices to Baʹal.’

[NOTE]
====
. Or “the shameful god.”
====

[[v24-11-14]]

^<<v24-11-14,14>>^ “As for you,^&#42;1^ do not pray in behalf of this people. Do not cry out in their behalf or offer a prayer for them, for I will not be listening when they call out to me because of their calamity.

[NOTE]
====
. That is, Jeremiah.
====

[[v24-11-15]]

^<<v24-11-15,15>>^ What right does my beloved one have to be in my house
When so many have carried out evil schemes?
With holy flesh^&#42;1^ will they avert the calamity when it comes upon you?
Will you exult at that time?

[NOTE]
====
. That is, sacrifices made in the temple.
====

[[v24-11-16]]

^<<v24-11-16,16>>^ Jehovah once called you a thriving olive tree,
Beautiful with fine fruit.
With a great roaring sound, he has set her on fire,
And they have broken its branches.

[[v24-11-17]]

^<<v24-11-17,17>>^ “Jehovah of armies, your Planter, has declared that a calamity will come upon you because of the evil committed by the house of Israel and the house of Judah, who have offended me by making sacrifices to Baʹal.”

[[v24-11-18]]

^<<v24-11-18,18>>^ Jehovah informed me so that I would know;
At that time you caused me to see what they were doing.

[[v24-11-19]]

^<<v24-11-19,19>>^ I was like a docile lamb being brought to the slaughter.
I did not know that they were scheming against me:
“Let us destroy the tree with its fruit,
And let us cut him off from the land of the living,
So that his name may be remembered no more.”

[[v24-11-20]]

^<<v24-11-20,20>>^ But Jehovah of armies judges with righteousness;
He examines the innermost thoughts^&#42;1^ and the heart.
Let me see your vengeance on them,
For to you I have committed my legal case.

[NOTE]
====
. Or “deepest emotions.” Lit., “kidneys.”
====

[[v24-11-21]]

^<<v24-11-21,21>>^ Therefore this is what Jehovah says against the men of Anʹa·thoth who are seeking to take your life^&#42;1^ and who say: “You must not prophesy in the name of Jehovah, or you will die by our hand”;

[NOTE]
====
. Or “seeking your soul.”
====

[[v24-11-22]]

^<<v24-11-22,22>>^ therefore this is what Jehovah of armies says: “Here I am going to call them to account. The young men will die by the sword, and their sons and their daughters will die by famine.

[[v24-11-23]]

^<<v24-11-23,23>>^ Not even a remnant will be left of them, because I will bring calamity on the men of Anʹa·thoth in the year of their being called to account.”

'''

xref:024-jeremiah/024-jeremiah-010.adoc#v24-10-0[&#60; Capítulo Anterior] | <<v24-11-0,Topo>> | xref:024-jeremiah/024-jeremiah-012.adoc#v24-12-0[Próximo Capítulo &#62;]