include::./index.adoc[]

[[v24-39-0]]
=== Jeremiah, 39
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-39-1]]

^<<v24-39-1,1>>^ In the ninth year of King Zed·e·kiʹah of Judah, in the tenth month, King Neb·u·chad·nezʹzar^&#42;1^ of Babylon and all his army came to Jerusalem, and they besieged it.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-39-2]]

^<<v24-39-2,2>>^ In the 11th year of Zed·e·kiʹah, in the fourth month, on the ninth day of the month, they broke through the city wall.

[[v24-39-3]]

^<<v24-39-3,3>>^ And all the princes of the king of Babylon went in and sat down in the Middle Gate, namely, Nerʹgal-shar·eʹzer the Samʹgar, Neʹbo-sarʹse·chim the Rabʹsa·ris,^&#42;1^ Nerʹgal-shar·eʹzer the Rabʹmag,^&#42;2^ and all the rest of the princes of the king of Babylon.

[NOTE]
====
. Or according to a different word division of the Hebrew text, “Nergal-sharezer, Samgar-nebo, Sarsechim, Rabsaris.”
. Or “the chief magician (astrologer).”
====

[[v24-39-4]]

^<<v24-39-4,4>>^ When King Zed·e·kiʹah of Judah and all the soldiers saw them, they fled, going out of the city by night by way of the king’s garden, through the gate between the double wall, and they continued by the way of the Arʹa·bah.

[[v24-39-5]]

^<<v24-39-5,5>>^ But the Chal·deʹan army chased after them, and they overtook Zed·e·kiʹah in the desert plains of Jerʹi·cho. They captured him and brought him up to King Neb·u·chad·nezʹzar^&#42;1^ of Babylon at Ribʹlah in the land of Haʹmath, where he passed sentence on him.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-39-6]]

^<<v24-39-6,6>>^ The king of Babylon had the sons of Zed·e·kiʹah slaughtered before his eyes there at Ribʹlah, and the king of Babylon had all the nobles of Judah slaughtered.

[[v24-39-7]]

^<<v24-39-7,7>>^ Then he blinded the eyes of Zed·e·kiʹah, after which he bound him with copper fetters to bring him to Babylon.

[[v24-39-8]]

^<<v24-39-8,8>>^ The Chal·deʹans then burned down the king’s house^&#42;1^ and the houses of the people, and they tore down the walls of Jerusalem.

[NOTE]
====
. Or “palace.”
====

[[v24-39-9]]

^<<v24-39-9,9>>^ Neb·uʹzar·adʹan the chief of the guard took into exile to Babylon the rest of the people who were left in the city, the deserters who had defected to him, and anyone who remained.

[[v24-39-10]]

^<<v24-39-10,10>>^ But Neb·uʹzar·adʹan the chief of the guard left in the land of Judah some of the poorest people, those who had nothing at all. On that day he also gave them vineyards and fields to work.^&#42;1^

[NOTE]
====
. Or possibly, “compulsory services.”
====

[[v24-39-11]]

^<<v24-39-11,11>>^ Now King Neb·u·chad·nezʹzar^&#42;1^ of Babylon gave Neb·uʹzar·adʹan the chief of the guard these orders concerning Jeremiah:

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-39-12]]

^<<v24-39-12,12>>^ “Take him and look after him; do him no harm, and grant whatever he asks of you.”

[[v24-39-13]]

^<<v24-39-13,13>>^ So Neb·uʹzar·adʹan the chief of the guard, Neb·u·shazʹban the Rabʹsa·ris,^&#42;1^ Nerʹgal-shar·eʹzer the Rabʹmag,^&#42;2^ and all the principal men of the king of Babylon sent

[NOTE]
====
. Or “the chief court official.”
. Or “the chief magician (astrologer).”
====

[[v24-39-14]]

^<<v24-39-14,14>>^ and had Jeremiah taken out of the Courtyard of the Guard and handed him over to Ged·a·liʹah the son of A·hiʹkam the son of Shaʹphan to be brought to his house. So he lived among the people.

[[v24-39-15]]

^<<v24-39-15,15>>^ While Jeremiah was confined in the Courtyard of the Guard, the word of Jehovah came to him, saying:

[[v24-39-16]]

^<<v24-39-16,16>>^ “Go and tell Eʹbed-melʹech the E·thi·oʹpi·an, ‘This is what Jehovah of armies, the God of Israel, says: “Here I am fulfilling my words on this city for calamity and not for good, and in that day you will see it happen.”’

[[v24-39-17]]

^<<v24-39-17,17>>^ “‘But I will rescue you in that day,’ declares Jehovah, ‘and you will not be handed over to the men you fear.’

[[v24-39-18]]

^<<v24-39-18,18>>^ “‘For I will surely provide you with escape, and you will not fall by the sword. You will have your life^&#42;1^ as a spoil,^&#42;2^ because you trusted in me,’ declares Jehovah.”

[NOTE]
====
. Or “soul.”
. Or “will escape with your life.”
====

'''

xref:024-jeremiah/024-jeremiah-038.adoc#v24-38-0[&#60; Capítulo Anterior] | <<v24-39-0,Topo>> | xref:024-jeremiah/024-jeremiah-040.adoc#v24-40-0[Próximo Capítulo &#62;]