include::./index.adoc[]

[[v24-52-0]]
=== Jeremiah, 52
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-52-1]]

^<<v24-52-1,1>>^ Zed·e·kiʹah was 21 years old when he became king, and he reigned for 11 years in Jerusalem. His mother’s name was Ha·muʹtal the daughter of Jeremiah of Libʹnah.

[[v24-52-2]]

^<<v24-52-2,2>>^ He continued to do what was bad in Jehovah’s eyes, according to all that Je·hoiʹa·kim had done.

[[v24-52-3]]

^<<v24-52-3,3>>^ It was because of Jehovah’s anger that these things took place in Jerusalem and in Judah, until he cast them out of his sight. And Zed·e·kiʹah rebelled against the king of Babylon.

[[v24-52-4]]

^<<v24-52-4,4>>^ In the ninth year of Zed·e·kiʹah’s reign, in the tenth month, on the tenth day of the month, King Neb·u·chad·nezʹzar^&#42;1^ of Babylon came with all his army against Jerusalem. They camped against it and built a siege wall all around it.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-52-5]]

^<<v24-52-5,5>>^ And the city was under siege until the 11th year of King Zed·e·kiʹah.

[[v24-52-6]]

^<<v24-52-6,6>>^ In the fourth month, on the ninth day of the month, the famine was severe in the city, and there was no food for the people of the land.

[[v24-52-7]]

^<<v24-52-7,7>>^ Finally the city wall was broken through, and all the soldiers fled from the city by night through the gate between the double wall near the king’s garden, while the Chal·deʹans were surrounding the city; and they continued by the way of the Arʹa·bah.

[[v24-52-8]]

^<<v24-52-8,8>>^ But the Chal·deʹan army pursued the king, and they overtook Zed·e·kiʹah in the desert plains of Jerʹi·cho, and all his troops were scattered from his side.

[[v24-52-9]]

^<<v24-52-9,9>>^ Then they seized the king and brought him up to the king of Babylon at Ribʹlah in the land of Haʹmath, and he passed sentence on him.

[[v24-52-10]]

^<<v24-52-10,10>>^ And the king of Babylon slaughtered Zed·e·kiʹah’s sons before his eyes, and he also slaughtered all the princes of Judah there at Ribʹlah.

[[v24-52-11]]

^<<v24-52-11,11>>^ Then the king of Babylon blinded Zed·e·kiʹah’s eyes, bound him with copper fetters, brought him to Babylon, and kept him imprisoned until the day of his death.

[[v24-52-12]]

^<<v24-52-12,12>>^ In the fifth month, on the tenth day of the month, that is, in the 19th year of King Neb·u·chad·nezʹzar^&#42;1^ the king of Babylon, Neb·uʹzar·adʹan the chief of the guard, who was an attendant of the king of Babylon, came into Jerusalem.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-52-13]]

^<<v24-52-13,13>>^ He burned down the house of Jehovah, the king’s house,^&#42;1^ and all the houses of Jerusalem; he also burned down every large house.

[NOTE]
====
. Or “palace.”
====

[[v24-52-14]]

^<<v24-52-14,14>>^ And the walls surrounding Jerusalem were pulled down by the entire Chal·deʹan army that was with the chief of the guard.

[[v24-52-15]]

^<<v24-52-15,15>>^ Neb·uʹzar·adʹan the chief of the guard took into exile some of the lowly people and the rest of the people who were left in the city. He also took the deserters who had defected to the king of Babylon as well as the rest of the master craftsmen.

[[v24-52-16]]

^<<v24-52-16,16>>^ But Neb·uʹzar·adʹan the chief of the guard left some of the poorest people of the land to serve as vinedressers and as compulsory laborers.

[[v24-52-17]]

^<<v24-52-17,17>>^ And the Chal·deʹans broke into pieces the copper pillars of the house of Jehovah and the carriages and the copper Sea that were in the house of Jehovah, and they carried all the copper away to Babylon.

[[v24-52-18]]

^<<v24-52-18,18>>^ They also took the cans, the shovels, the extinguishers, the bowls, the cups, and all the copper utensils used in the temple service.

[[v24-52-19]]

^<<v24-52-19,19>>^ The chief of the guard took the basins, the fire holders, the bowls, the cans, the lampstands, the cups, and the bowls that were of genuine gold and silver.

[[v24-52-20]]

^<<v24-52-20,20>>^ As for the two pillars, the Sea, the 12 copper bulls under the Sea, and the carriages that King Solʹo·mon had made for the house of Jehovah, the copper of all these articles was beyond weighing.

[[v24-52-21]]

^<<v24-52-21,21>>^ As for the pillars, each pillar was 18 cubits^&#42;1^ high, a measuring cord of 12 cubits could encircle it; its thickness was four fingerbreadths,^&#42;2^ and it was hollow.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
. A fingerbreadth equaled 1.85 cm (0.73 in.). See App. B14.
====

[[v24-52-22]]

^<<v24-52-22,22>>^ And the capital on it was of copper; and the height of the one capital was five cubits; and the network and pomegranates all around on the capital were all made of copper. The second pillar was just like it, also the pomegranates.

[[v24-52-23]]

^<<v24-52-23,23>>^ There were 96 pomegranates on the sides; in all, there were 100 pomegranates around the network.

[[v24-52-24]]

^<<v24-52-24,24>>^ The chief of the guard also took Se·raiʹah the chief priest, Zeph·a·niʹah the second priest, and the three doorkeepers.

[[v24-52-25]]

^<<v24-52-25,25>>^ And he took from the city one court official who was the commissioner over the soldiers, seven close associates of the king who were found in the city, as well as the secretary of the chief of the army, the one mustering the people of the land, and 60 men of the common people of the land who were yet found in the city.

[[v24-52-26]]

^<<v24-52-26,26>>^ Neb·uʹzar·adʹan the chief of the guard took them and brought them to the king of Babylon at Ribʹlah.

[[v24-52-27]]

^<<v24-52-27,27>>^ The king of Babylon struck them down and put them to death at Ribʹlah in the land of Haʹmath. Thus Judah went into exile from its land.

[[v24-52-28]]

^<<v24-52-28,28>>^ These are the people whom Neb·u·chad·nezʹzar^&#42;1^ took into exile: in the seventh year, 3,023 Jews.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-52-29]]

^<<v24-52-29,29>>^ In the 18th year of Neb·u·chad·nezʹzar,^&#42;1^ 832 people^&#42;2^ were taken from Jerusalem.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
. Or “souls.”
====

[[v24-52-30]]

^<<v24-52-30,30>>^ In the 23rd year of Neb·u·chad·nezʹzar,^&#42;1^ Neb·uʹzar·adʹan the chief of the guard took Jews into exile, 745 people.^&#42;2^
In all, 4,600 people^&#42;3^ were taken into exile.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
. Or “souls.”
. Or “souls.”
====

[[v24-52-31]]

^<<v24-52-31,31>>^ Then in the 37th year of the exile of King Je·hoiʹa·chin of Judah, in the 12th month, on the 25th day of the month, King Eʹvil-merʹo·dach of Babylon, in the year he became king, released^&#42;1^ King Je·hoiʹa·chin of Judah and brought him out of prison.

[NOTE]
====
. Lit., “raised up the head of.”
====

[[v24-52-32]]

^<<v24-52-32,32>>^ He spoke kindly with him and put his throne higher than the thrones of the other kings who were with him in Babylon.

[[v24-52-33]]

^<<v24-52-33,33>>^ So Je·hoiʹa·chin took off his prison garments, and he regularly ate before him all the days of his life.

[[v24-52-34]]

^<<v24-52-34,34>>^ A regular allowance of food was given him from the king of Babylon, day after day, until the day of his death, all the days of his life.

'''

xref:024-jeremiah/024-jeremiah-051.adoc#v24-51-0[&#60; Capítulo Anterior] | <<v24-52-0,Topo>> | xref:025-lamentations/025-lamentations-001.adoc#v25-1-0[Próximo Capítulo &#62;]