include::./index.adoc[]

[[v24-20-0]]
=== Jeremiah, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-20-1]]

^<<v24-20-1,1>>^ Now Pashʹhur the son of Imʹmer, the priest, who was also the leading commissioner in the house of Jehovah, was listening when Jeremiah prophesied these things.

[[v24-20-2]]

^<<v24-20-2,2>>^ Then Pashʹhur struck Jeremiah the prophet and put him in the stocks that were at the Upper Gate of Benjamin, which was in the house of Jehovah.

[[v24-20-3]]

^<<v24-20-3,3>>^ But on the following day when Pashʹhur released Jeremiah from the stocks, Jeremiah said to him:
“Jehovah has named you, not Pashʹhur, but Terror All Around.

[[v24-20-4]]

^<<v24-20-4,4>>^ For this is what Jehovah says, ‘I will make you an object of terror to yourself and to all your friends, and they will fall by the sword of their enemies while your eyes are looking on; and I will give all Judah into the hand of the king of Babylon, and he will take them into exile in Babylon and put them to death by the sword.

[[v24-20-5]]

^<<v24-20-5,5>>^ And I will give all the wealth of this city, all its resources, all its precious things, and all the treasures of the kings of Judah into the hand of their enemies. And they will plunder them and seize them and take them to Babylon.

[[v24-20-6]]

^<<v24-20-6,6>>^ And as for you, Pashʹhur, and all who live in your house, you will go into captivity. You will go off to Babylon and die there, and you will be buried there with all your friends, because you have prophesied lies to them.’”

[[v24-20-7]]

^<<v24-20-7,7>>^ You have fooled me, O Jehovah, and I was fooled.
You used your strength against me, and you prevailed.
I have become a laughingstock all day long;
Everyone ridicules me.

[[v24-20-8]]

^<<v24-20-8,8>>^ For whenever I speak, I must cry out and proclaim,
“Violence and destruction!”
For me the word of Jehovah has been the cause of insults and jeering all day long.

[[v24-20-9]]

^<<v24-20-9,9>>^ So I said: “I am not going to make mention of him,
And I will speak no more in his name.”
But in my heart it became like a burning fire shut up in my bones,
And I was tired of holding it in;
I could no longer endure it.

[[v24-20-10]]

^<<v24-20-10,10>>^ For I heard many evil rumors;
Terror surrounded me.
“Denounce him; let us denounce him!”
Every man wishing me peace was watching for my downfall:
“Perhaps he will make a foolish mistake,
And we can prevail and take our revenge against him.”

[[v24-20-11]]

^<<v24-20-11,11>>^ But Jehovah was with me like a fearsome warrior.
That is why those persecuting me will stumble and will not prevail.
They will be put to great shame, for they will not succeed.
Their everlasting humiliation will not be forgotten.

[[v24-20-12]]

^<<v24-20-12,12>>^ But you, O Jehovah of armies, are examining the righteous one;
You see the innermost thoughts^&#42;1^ and the heart.
Let me see your vengeance on them,
For to you I have committed my legal case.

[NOTE]
====
. Or “deepest emotions.” Lit., “kidneys.”
====

[[v24-20-13]]

^<<v24-20-13,13>>^ Sing to Jehovah! Praise Jehovah!
For he has rescued the poor one^&#42;1^ from the hand of evildoers.

[NOTE]
====
. Or “the soul of the poor one.”
====

[[v24-20-14]]

^<<v24-20-14,14>>^ Cursed be the day I was born!
May the day my mother gave birth to me not be blessed!

[[v24-20-15]]

^<<v24-20-15,15>>^ Cursed be the man who brought good news to my father, saying:
“A son has been born to you, a boy!”
Making him rejoice greatly.

[[v24-20-16]]

^<<v24-20-16,16>>^ May that man become like cities that Jehovah overthrew without regret.
May he hear an outcry in the morning and the sound of alarm at midday.

[[v24-20-17]]

^<<v24-20-17,17>>^ Why did he not put me to death in the womb,
So that my mother would become my burial place
And her womb would always remain pregnant?

[[v24-20-18]]

^<<v24-20-18,18>>^ Why did I have to come out of the womb
To see trouble and grief,
To end my days in shame?

'''

xref:024-jeremiah/024-jeremiah-019.adoc#v24-19-0[&#60; Capítulo Anterior] | <<v24-20-0,Topo>> | xref:024-jeremiah/024-jeremiah-021.adoc#v24-21-0[Próximo Capítulo &#62;]