include::./index.adoc[]

[[v24-21-0]]
=== Jeremiah, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-21-1]]

^<<v24-21-1,1>>^ Jeremiah received the word from Jehovah when King Zed·e·kiʹah sent to him Pashʹhur son of Mal·chiʹjah and Zeph·a·niʹah son of Ma·a·seiʹah, the priest, requesting:

[[v24-21-2]]

^<<v24-21-2,2>>^ “Please inquire of Jehovah in our behalf, because King Neb·u·chad·nezʹzar^&#42;1^ of Babylon is waging war against us. Perhaps Jehovah will perform one of his wonderful works in our behalf, so that he will withdraw from us.”

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-21-3]]

^<<v24-21-3,3>>^ Jeremiah said to them: “This is what you should say to Zed·e·kiʹah,

[[v24-21-4]]

^<<v24-21-4,4>>^ ‘This is what Jehovah the God of Israel says: “Here I am turning around against you^&#42;1^ the weapons of war that are in your own hands, with which you are fighting the king of Babylon and the Chal·deʹans who are outside the wall besieging you. And I will gather them into the middle of this city.

[NOTE]
====
. Or “turning in reverse.”
====

[[v24-21-5]]

^<<v24-21-5,5>>^ And I myself will fight against you with an outstretched hand and a mighty arm, with anger and wrath and great indignation.

[[v24-21-6]]

^<<v24-21-6,6>>^ I will strike the inhabitants of this city, both man and beast. By a great pestilence^&#42;1^ they will die.”’

[NOTE]
====
. Or “disease.”
====

[[v24-21-7]]

^<<v24-21-7,7>>^ “‘“And after that,” declares Jehovah, “I will give King Zed·e·kiʹah of Judah and his servants and the people of this city—those who survive the pestilence, the sword, and the famine—into the hand of King Neb·u·chad·nezʹzar^&#42;1^ of Babylon, into the hand of their enemies, and into the hand of those who are seeking to take their life.^&#42;2^ He will strike them down with the sword. He will not feel sorry for them, nor will he show compassion or have any mercy.”’

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
. Or “seeking their soul.”
====

[[v24-21-8]]

^<<v24-21-8,8>>^ “And to this people you should say, ‘This is what Jehovah says: “Here I am putting before you the way of life and the way of death.

[[v24-21-9]]

^<<v24-21-9,9>>^ Those who remain in this city will die by the sword, by famine, and by pestilence. But whoever goes out and surrenders to the Chal·deʹans who are besieging you will keep living, and he will have his life^&#42;1^ as a spoil.”’^&#42;2^

[NOTE]
====
. Or “soul.”
. Or “will escape with his life.”
====

[[v24-21-10]]

^<<v24-21-10,10>>^ “‘“For I have set my face against this city for calamity and not for good,” declares Jehovah. “It will be given into the hand of the king of Babylon, and he will burn it with fire.”

[[v24-21-11]]

^<<v24-21-11,11>>^ “‘To the household of the king of Judah: Hear the word of Jehovah.

[[v24-21-12]]

^<<v24-21-12,12>>^ O house of David, this is what Jehovah says:
“Uphold justice every morning,
And rescue the one being robbed from the hand of the defrauder,
So that my wrath does not blaze like a fire
And burn with no one to extinguish it
Because of your evil deeds.”’

[[v24-21-13]]

^<<v24-21-13,13>>^ ‘Here I am against you, O inhabitant of the valley,^&#42;1^
O rock of the level land,’ declares Jehovah.
‘As for you who say: “Who will come down against us?
And who will invade our dwellings?”

[NOTE]
====
. Or “low plain.”
====

[[v24-21-14]]

^<<v24-21-14,14>>^ I will hold an accounting against you
As your deeds deserve,’ declares Jehovah.
‘And I will set her forest ablaze,
And it will consume all the things around her.’”

'''

xref:024-jeremiah/024-jeremiah-020.adoc#v24-20-0[&#60; Capítulo Anterior] | <<v24-21-0,Topo>> | xref:024-jeremiah/024-jeremiah-022.adoc#v24-22-0[Próximo Capítulo &#62;]