include::./index.adoc[]

[[v24-25-0]]
=== Jeremiah, 25
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-25-1]]

^<<v24-25-1,1>>^ The word that came to Jeremiah concerning all the people of Judah in the fourth year of Je·hoiʹa·kim son of Jo·siʹah, the king of Judah, which was the first year of King Neb·u·chad·nezʹzar^&#42;1^ of Babylon.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-25-2]]

^<<v24-25-2,2>>^ This is what Jeremiah the prophet spoke concerning^&#42;1^ all the people of Judah and all the inhabitants of Jerusalem:

[NOTE]
====
. Or “to.”
====

[[v24-25-3]]

^<<v24-25-3,3>>^ “From the 13th year of Jo·siʹah son of Aʹmon, the king of Judah, to this day, these 23 years, the word of Jehovah has come to me, and I kept speaking to you again and again,^&#42;1^ but you would not listen.

[NOTE]
====
. Lit., “rising up early and speaking.”
====

[[v24-25-4]]

^<<v24-25-4,4>>^ And Jehovah sent all his servants the prophets to you, sending them again and again,^&#42;1^ but you would not listen or incline your ear to hear.

[NOTE]
====
. Lit., “rising up early and sending.”
====

[[v24-25-5]]

^<<v24-25-5,5>>^ They would say, ‘Turn back, please, each of you from your evil ways and your evil deeds; then you will continue dwelling for a long time to come in the land that Jehovah long ago gave to you and to your forefathers.

[[v24-25-6]]

^<<v24-25-6,6>>^ Do not follow other gods and serve them and bow down to them, offending me with the work of your hands; otherwise I will bring calamity on you.’

[[v24-25-7]]

^<<v24-25-7,7>>^ “‘But you would not listen to me,’ declares Jehovah. ‘Instead you offended me with the work of your hands, to your own calamity.’

[[v24-25-8]]

^<<v24-25-8,8>>^ “Therefore this is what Jehovah of armies says, ‘“Because you would not obey my words,

[[v24-25-9]]

^<<v24-25-9,9>>^ I am sending for all the families of the north,” declares Jehovah, “sending for King Neb·u·chad·nezʹzar^&#42;1^ of Babylon, my servant, and I will bring them against this land and against its inhabitants and against all these surrounding nations. I will devote them to destruction and make them an object of horror and something to whistle at and a perpetual ruin.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-25-10]]

^<<v24-25-10,10>>^ I will put an end to the sound of exultation and the sound of rejoicing from them, the voice of the bridegroom and the voice of the bride, the sound of the hand mill and the light of the lamp.

[[v24-25-11]]

^<<v24-25-11,11>>^ And all this land will be reduced to ruins and will become an object of horror, and these nations will have to serve the king of Babylon for 70 years.”’

[[v24-25-12]]

^<<v24-25-12,12>>^ “‘But when 70 years have been fulfilled, I will call to account^&#42;1^ the king of Babylon and that nation for their error,’ declares Jehovah, ‘and I will make the land of the Chal·deʹans a desolate wasteland for all time.

[NOTE]
====
. Or “punish.”
====

[[v24-25-13]]

^<<v24-25-13,13>>^ I will bring on that land all my words that I have spoken against it, all that is written in this book that Jeremiah has prophesied against all the nations.

[[v24-25-14]]

^<<v24-25-14,14>>^ For many nations and great kings will make slaves of them, and I will repay them according to their deeds and the work of their own hands.’”

[[v24-25-15]]

^<<v24-25-15,15>>^ For this is what Jehovah the God of Israel said to me: “Take this cup of the wine of wrath out of my hand, and make all the nations to whom I send you drink it.

[[v24-25-16]]

^<<v24-25-16,16>>^ And they will drink and stagger and act like madmen because of the sword that I am sending among them.”

[[v24-25-17]]

^<<v24-25-17,17>>^ So I took the cup out of the hand of Jehovah and made all the nations to whom Jehovah sent me drink:

[[v24-25-18]]

^<<v24-25-18,18>>^ starting with Jerusalem and the cities of Judah, her kings and her princes, to make them a ruin, an object of horror, something to whistle at and a curse, as it is today;

[[v24-25-19]]

^<<v24-25-19,19>>^ then Pharʹaoh king of Egypt and his servants, his princes, and all his people,

[[v24-25-20]]

^<<v24-25-20,20>>^ and all their mixed populations; all the kings of the land of Uz; all the kings of the land of the Phi·lisʹtines, Ashʹke·lon, Gazʹa, Ekʹron, and those remaining of Ashʹdod;

[[v24-25-21]]

^<<v24-25-21,21>>^ Eʹdom, Moʹab, and the Amʹmon·ites;

[[v24-25-22]]

^<<v24-25-22,22>>^ all the kings of Tyre, all the kings of Siʹdon, and the kings of the island in the sea;

[[v24-25-23]]

^<<v24-25-23,23>>^ Deʹdan, Teʹma, Buz, and all those with hair clipped at the temples;

[[v24-25-24]]

^<<v24-25-24,24>>^ all the kings of the Arabians and all the kings of the mixed populations who reside in the wilderness;

[[v24-25-25]]

^<<v24-25-25,25>>^ all the kings of Zimʹri, all the kings of Eʹlam, and all the kings of the Medes;

[[v24-25-26]]

^<<v24-25-26,26>>^ and all the kings of the north near and far, one after the other, and all the other kingdoms of the earth that are on the surface of the ground; and the king of Sheʹshach^&#42;1^ will drink after them.

[NOTE]
====
. This appears to be a cryptographic name for Babel (Babylon).
====

[[v24-25-27]]

^<<v24-25-27,27>>^ “And you must say to them, ‘This is what Jehovah of armies, the God of Israel, says: “Drink and get drunk and vomit and fall so that you cannot get up because of the sword that I am sending among you.”’

[[v24-25-28]]

^<<v24-25-28,28>>^ And if they refuse to take the cup out of your hand to drink, say to them, ‘This is what Jehovah of armies says: “You must drink it!

[[v24-25-29]]

^<<v24-25-29,29>>^ For look! if I am bringing calamity first on the city that bears my name, should you go unpunished?”’
“‘You will not go unpunished, for I am calling for a sword against all the inhabitants of the earth,’ declares Jehovah of armies.

[[v24-25-30]]

^<<v24-25-30,30>>^ “And you are to prophesy all these words to them and say to them,
‘From on high Jehovah will roar,
And from his holy dwelling he will make his voice heard.
He will roar loudly against his abiding place.
Shouting like those treading the winepress,
He will sing triumphantly against all the inhabitants of the earth.’

[[v24-25-31]]

^<<v24-25-31,31>>^ ‘A noise will resound to the ends of the earth,
For Jehovah has a controversy with the nations.
He will personally pass judgment on all humans.^&#42;1^
And he will put the wicked to the sword,’ declares Jehovah.

[NOTE]
====
. Lit., “all flesh.”
====

[[v24-25-32]]

^<<v24-25-32,32>>^ This is what Jehovah of armies says:
‘Look! A calamity is spreading from nation to nation,
And a great tempest will be unleashed from the remotest parts of the earth.

[[v24-25-33]]

^<<v24-25-33,33>>^ “‘And those slain by Jehovah in that day will be from one end of the earth clear to the other end of the earth. They will not be mourned, nor will they be gathered up or buried. They will become like manure on the surface of the ground.’

[[v24-25-34]]

^<<v24-25-34,34>>^ Wail, you shepherds, and cry out!
Wallow about, you majestic ones of the flock,
Because the time of your slaughter and your dispersion has come,
And you will fall like a precious vessel!

[[v24-25-35]]

^<<v24-25-35,35>>^ The shepherds have no place to flee,
And there is no escape for the majestic ones of the flock.

[[v24-25-36]]

^<<v24-25-36,36>>^ Listen! The outcry of the shepherds
And the wailing of the majestic ones of the flock,
For Jehovah is devastating their pasture.

[[v24-25-37]]

^<<v24-25-37,37>>^ And the peaceful dwelling places have been made lifeless
Because of the burning anger of Jehovah.

[[v24-25-38]]

^<<v24-25-38,38>>^ He has left his lair just like a young lion,^&#42;1^
For their land has become an object of horror
Because of the cruel sword
And because of his burning anger.”

[NOTE]
====
. Or “a maned young lion.”
====

'''

xref:024-jeremiah/024-jeremiah-024.adoc#v24-24-0[&#60; Capítulo Anterior] | <<v24-25-0,Topo>> | xref:024-jeremiah/024-jeremiah-026.adoc#v24-26-0[Próximo Capítulo &#62;]