include::./index.adoc[]

[[v24-50-0]]
=== Jeremiah, 50
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-50-1]]

^<<v24-50-1,1>>^ The word that Jehovah spoke concerning Babylon, concerning the land of the Chal·deʹans, through Jeremiah the prophet:

[[v24-50-2]]

^<<v24-50-2,2>>^ “Declare it among the nations and proclaim it.
Raise a signal^&#42;1^ and proclaim it.
Do not hide anything!
Say, ‘Babylon has been captured.
Bel has been put to shame.
Merʹo·dach has become terrified.
Her images have been put to shame.
Her disgusting idols^&#42;2^ have become terrified.’

[NOTE]
====
. Or “signal pole.”
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v24-50-3]]

^<<v24-50-3,3>>^ For a nation has come against her from the north.
It makes her land an object of horror;
No one is dwelling in her.
Both man and beast have taken flight;
They have gone away.”

[[v24-50-4]]

^<<v24-50-4,4>>^ “In those days and at that time,” declares Jehovah, “the people of Israel and the people of Judah will come together. They will weep as they walk, and together they will seek Jehovah their God.

[[v24-50-5]]

^<<v24-50-5,5>>^ They will ask the way to Zion, with their faces turned in that direction, saying, ‘Come and let us join ourselves to Jehovah in an everlasting covenant that will not be forgotten.’

[[v24-50-6]]

^<<v24-50-6,6>>^ My people have become a flock of lost sheep. Their own shepherds caused them to stray. They led them away onto the mountains, roaming from mountain to hill. They have forgotten their resting-place.

[[v24-50-7]]

^<<v24-50-7,7>>^ All those finding them have devoured them, and their enemies have said, ‘We are not guilty, because they sinned against Jehovah, against the dwelling place of righteousness and the hope of their forefathers, Jehovah.’”

[[v24-50-8]]

^<<v24-50-8,8>>^ “Flee out of the midst of Babylon,
Go out of the land of the Chal·deʹans,
And be like the leading animals before the flock.

[[v24-50-9]]

^<<v24-50-9,9>>^ For here I am raising up and bringing against Babylon
An assembly of great nations from the land of the north.
They will come against her in battle formation;
From there she will be captured.
Their arrows are like those of a warrior
Causing bereavement of children;
They do not come back without results.

[[v24-50-10]]

^<<v24-50-10,10>>^ Chal·deʹa will become a spoil.
All those taking spoil from her will be fully satisfied,” declares Jehovah.

[[v24-50-11]]

^<<v24-50-11,11>>^ “For you kept rejoicing, you kept exulting
When pillaging my own inheritance.
For you kept pawing like a heifer in the grass,
And you kept neighing like stallions.

[[v24-50-12]]

^<<v24-50-12,12>>^ Your mother has been put to shame.
She who gave birth to you has been disappointed.
Look! She is the least of the nations,
A waterless wilderness and a desert.

[[v24-50-13]]

^<<v24-50-13,13>>^ Because of the indignation of Jehovah she will not be inhabited;
She will become utterly desolate.
Anyone passing by Babylon will stare in horror
And whistle because of all her plagues.

[[v24-50-14]]

^<<v24-50-14,14>>^ Come against Babylon in battle formation on every side,
All you who are bending^&#42;1^ the bow.
Shoot at her, spare no arrow,
For it is against Jehovah that she has sinned.

[NOTE]
====
. Lit., “treading.”
====

[[v24-50-15]]

^<<v24-50-15,15>>^ Shout a war cry against her on every side.
She has surrendered.^&#42;1^
Her pillars have fallen, her walls are torn down,
For it is the vengeance of Jehovah.
Take your vengeance on her.
Do to her just as she has done.

[NOTE]
====
. Lit., “given her hand.”
====

[[v24-50-16]]

^<<v24-50-16,16>>^ Cut off the sower from Babylon
And the one handling the sickle in harvesttime.
Because of the cruel sword, each will return to his own people,
Each one will flee to his own land.

[[v24-50-17]]

^<<v24-50-17,17>>^ “The people of Israel are scattered sheep. Lions have dispersed them. First the king of As·syrʹi·a devoured them; then King Neb·u·chad·nezʹzar^&#42;1^ of Babylon gnawed on their bones.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-50-18]]

^<<v24-50-18,18>>^ Therefore this is what Jehovah of armies, the God of Israel, says: ‘Here I will deal with the king of Babylon and with his land in the same way that I dealt with the king of As·syrʹi·a.

[[v24-50-19]]

^<<v24-50-19,19>>^ And I will bring Israel back to his pasture, and he will graze on Carʹmel and on Baʹshan, and on the mountains of Eʹphra·im and of Gilʹe·ad he^&#42;1^ will be satisfied.’”

[NOTE]
====
. Or “his soul.”
====

[[v24-50-20]]

^<<v24-50-20,20>>^ “In those days and at that time,” declares Jehovah,
“Israel’s guilt will be searched for,
But there will be none,
And the sins of Judah will not be found,
For I will forgive those whom I let remain.”

[[v24-50-21]]

^<<v24-50-21,21>>^ “Go up against the land of Mer·a·thaʹim and against the inhabitants of Peʹkod.
Let them be massacred and completely destroyed,”^&#42;1^ declares Jehovah.
“Do all that I have commanded you.

[NOTE]
====
. Or “and devote them to destruction.”
====

[[v24-50-22]]

^<<v24-50-22,22>>^ There is the sound of war in the land,
A great catastrophe.

[[v24-50-23]]

^<<v24-50-23,23>>^ How the forge hammer of all the earth has been cut down and broken!
How Babylon has become an object of horror among the nations!

[[v24-50-24]]

^<<v24-50-24,24>>^ I have laid a snare for you, and you have been caught, O Babylon,
And you did not know it.
You were found and captured,
For it was Jehovah whom you opposed.

[[v24-50-25]]

^<<v24-50-25,25>>^ Jehovah has opened his storehouse,
And he brings out the weapons of his indignation.
For the Sovereign Lord, Jehovah of armies, has a work
In the land of the Chal·deʹans.

[[v24-50-26]]

^<<v24-50-26,26>>^ Come against her from distant places.
Open up her granaries.
Pile her up like heaps of grain.
Destroy her completely.^&#42;1^
May she have no one left.

[NOTE]
====
. Or “Devote her to destruction.”
====

[[v24-50-27]]

^<<v24-50-27,27>>^ Massacre all her young bulls;
Let them go down to the slaughter.
Woe to them, for their day has come,
Their time of reckoning!

[[v24-50-28]]

^<<v24-50-28,28>>^ There is the sound of those fleeing,
Those escaping from the land of Babylon,
To declare in Zion the vengeance of Jehovah our God,
The vengeance for his temple.

[[v24-50-29]]

^<<v24-50-29,29>>^ Summon archers against Babylon,
All who are bending^&#42;1^ the bow.
Camp all around her; let no one escape.
Repay her according to her activity.
Do to her just as she has done.
For she has acted arrogantly against Jehovah,
Against the Holy One of Israel.

[NOTE]
====
. Lit., “treading.”
====

[[v24-50-30]]

^<<v24-50-30,30>>^ So her young men will fall in her public squares,
And all her soldiers will perish^&#42;1^ in that day,” declares Jehovah.

[NOTE]
====
. Lit., “be silenced.”
====

[[v24-50-31]]

^<<v24-50-31,31>>^ “Look! I am against you, O defiant one,” declares the Sovereign Lord, Jehovah of armies,
“For your day must come, the time that I will call you to account.

[[v24-50-32]]

^<<v24-50-32,32>>^ You, O defiant one, will stumble and fall,
With no one to raise you up.
And I will set your cities on fire,
And it will consume everything around you.”

[[v24-50-33]]

^<<v24-50-33,33>>^ This is what Jehovah of armies says:
“The people of Israel and Judah are oppressed,
And all those taking them captive have held onto them.
They have refused to let them go.

[[v24-50-34]]

^<<v24-50-34,34>>^ But their Repurchaser is strong.
Jehovah of armies is his name.
He will surely plead their legal case,
In order to give rest to the land
And to bring agitation to the inhabitants of Babylon.”

[[v24-50-35]]

^<<v24-50-35,35>>^ “There is a sword against the Chal·deʹans,” declares Jehovah,
“Against the inhabitants of Babylon and against her princes and against her wise ones.

[[v24-50-36]]

^<<v24-50-36,36>>^ There is a sword against the empty talkers,^&#42;1^ and they will act foolishly.
There is a sword against her warriors, and they will become terrified.

[NOTE]
====
. Or “the false prophets.”
====

[[v24-50-37]]

^<<v24-50-37,37>>^ There is a sword against their horses and their war chariots,
And against all the mixed populations in her midst,
And they will become like women.
There is a sword against her treasures, and they will be plundered.

[[v24-50-38]]

^<<v24-50-38,38>>^ There is a devastation on her waters, and they will be dried up.
For it is a land of graven images,
And because of their frightful visions they keep acting with madness.

[[v24-50-39]]

^<<v24-50-39,39>>^ Therefore, the desert creatures will dwell with the howling animals,
And in her the ostriches will dwell.
She will never again be inhabited,
Nor will she be a place of residence throughout all generations.”

[[v24-50-40]]

^<<v24-50-40,40>>^ “Just as with God’s overthrow of Sodʹom and Go·morʹrah and of their neighboring towns,” declares Jehovah, “no one will dwell there, and no man will settle there.

[[v24-50-41]]

^<<v24-50-41,41>>^ Look! A people is coming in from the north;
A great nation and grand kings will be raised up
From the remotest parts of the earth.

[[v24-50-42]]

^<<v24-50-42,42>>^ Bow and javelin they wield.
They are cruel and will show no mercy.
Their sound is like the roaring sea,
As they ride on their horses.
Like one man, they line up in battle formation against you, O daughter of Babylon.

[[v24-50-43]]

^<<v24-50-43,43>>^ The king of Babylon has heard the report about them,
And his hands drop down.
Anguish seizes him,
Pain like that of a woman giving birth.

[[v24-50-44]]

^<<v24-50-44,44>>^ “Look! Someone will come up against the secure pastures like a lion from the dense thickets along the Jordan, but in a moment I will make them run away from her. And I will appoint over her the chosen one. For who is like me, and who will challenge me? What shepherd can stand before me?

[[v24-50-45]]

^<<v24-50-45,45>>^ Therefore hear, O men, the decision^&#42;1^ that Jehovah has made against Babylon and what he has thought out against the land of the Chal·deʹans.
Surely the little ones of the flock will be dragged away.
He will make their dwelling place desolate because of them.

[NOTE]
====
. Or “counsel.”
====

[[v24-50-46]]

^<<v24-50-46,46>>^ At the sound of Babylon’s capture, the earth will quake,
And an outcry will be heard among the nations.”

'''

xref:024-jeremiah/024-jeremiah-049.adoc#v24-49-0[&#60; Capítulo Anterior] | <<v24-50-0,Topo>> | xref:024-jeremiah/024-jeremiah-051.adoc#v24-51-0[Próximo Capítulo &#62;]