include::./index.adoc[]

[[v24-33-0]]
=== Jeremiah, 33
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-33-1]]

^<<v24-33-1,1>>^ The word of Jehovah came to Jeremiah the second time, while he was still confined in the Courtyard of the Guard, saying:

[[v24-33-2]]

^<<v24-33-2,2>>^ “This is what Jehovah the Maker of earth says, Jehovah who formed it and firmly established it; Jehovah is his name,

[[v24-33-3]]

^<<v24-33-3,3>>^ ‘Call to me, and I will answer you and readily tell you great and incomprehensible things that you have not known.’”

[[v24-33-4]]

^<<v24-33-4,4>>^ “For this is what Jehovah the God of Israel says concerning the houses of this city and the houses of the kings of Judah that are pulled down because of the siege ramparts and the sword,

[[v24-33-5]]

^<<v24-33-5,5>>^ and concerning those who are coming to fight the Chal·deʹans, filling these places with the carcasses of those whom I struck down in my anger and in my wrath, those whose evil has caused me to hide my face from this city:

[[v24-33-6]]

^<<v24-33-6,6>>^ ‘Here I am bringing recuperation and health to her, and I will heal them and reveal to them an abundance of peace and truth.

[[v24-33-7]]

^<<v24-33-7,7>>^ And I will bring back the captives of Judah and the captives of Israel, and I will build them up as I did at the start.

[[v24-33-8]]

^<<v24-33-8,8>>^ And I will purify them from all the guilt of their sins against me, and I will forgive all the guilt of their sins and their transgressions against me.

[[v24-33-9]]

^<<v24-33-9,9>>^ And she will become to me a name of exultation, a praise, and a beauty before all the nations of the earth who will hear of all the goodness that I bestow on them. And they will be in dread and will tremble because of all the goodness and peace that I will bestow on her.’”

[[v24-33-10]]

^<<v24-33-10,10>>^ “This is what Jehovah says: ‘In this place that you will say is a wasteland, without man or livestock, in the cities of Judah and in the streets of Jerusalem that are desolate, without man or inhabitant or livestock, there will again be heard

[[v24-33-11]]

^<<v24-33-11,11>>^ the sound of exultation and the sound of rejoicing, the voice of the bridegroom and the voice of the bride, the voice of those saying: “Give thanks to Jehovah of armies, for Jehovah is good; his loyal love endures forever!”’
“‘They will bring thanksgiving offerings into the house of Jehovah, for I will bring back the captives of the land, as at the start,’ says Jehovah.”

[[v24-33-12]]

^<<v24-33-12,12>>^ “This is what Jehovah of armies says: ‘In this wasteland, without man or livestock, and in all its cities, there will again be pastures for the shepherds to rest their flocks.’

[[v24-33-13]]

^<<v24-33-13,13>>^ “‘In the cities of the mountainous region, in the cities of the lowland, in the cities of the south, in the land of Benjamin, in the areas around Jerusalem, and in the cities of Judah, flocks will again pass under the hands of the one counting them,’ says Jehovah.”

[[v24-33-14]]

^<<v24-33-14,14>>^ “‘Look! The days are coming,’ declares Jehovah, ‘when I will fulfill the good promise that I have spoken concerning the house of Israel and the house of Judah.

[[v24-33-15]]

^<<v24-33-15,15>>^ In those days and at that time I will cause to sprout for David a righteous sprout,^&#42;1^ and he will execute justice and righteousness in the land.

[NOTE]
====
. Or “heir.”
====

[[v24-33-16]]

^<<v24-33-16,16>>^ In those days Judah will be saved and Jerusalem will reside in security. And this is what she will be called: Jehovah Is Our Righteousness.’”

[[v24-33-17]]

^<<v24-33-17,17>>^ “For this is what Jehovah says: ‘There will never fail to be a man from David’s line to sit on the throne of the house of Israel,

[[v24-33-18]]

^<<v24-33-18,18>>^ nor will the Levitical priests ever fail to have a man stand before me to offer whole burnt offerings, to burn grain offerings, and to offer sacrifices.’”

[[v24-33-19]]

^<<v24-33-19,19>>^ And the word of Jehovah again came to Jeremiah, saying:

[[v24-33-20]]

^<<v24-33-20,20>>^ “This is what Jehovah says, ‘If you could break my covenant regarding the day and my covenant regarding the night, to prevent day and night from coming at their proper time,

[[v24-33-21]]

^<<v24-33-21,21>>^ only then could my covenant with my servant David be broken, so that he should not have a son ruling as king on his throne, and so also my covenant with the Levitical priests, my ministers.

[[v24-33-22]]

^<<v24-33-22,22>>^ Just as the army of the heavens cannot be counted and the sand of the sea cannot be measured, so I will multiply the offspring^&#42;1^ of my servant David and the Levites who are ministering to me.’”

[NOTE]
====
. Lit., “seed.”
====

[[v24-33-23]]

^<<v24-33-23,23>>^ And the word of Jehovah again came to Jeremiah, saying:

[[v24-33-24]]

^<<v24-33-24,24>>^ “Have you not taken note of what this people is saying, ‘Jehovah will reject the two families that he chose’? And they are treating my own people with disrespect, and they no longer regard them as a nation.

[[v24-33-25]]

^<<v24-33-25,25>>^ “This is what Jehovah says: ‘Just as surely as I have established my covenant regarding the day and the night, the laws^&#42;1^ of heaven and earth,

[NOTE]
====
. Or “statutes.”
====

[[v24-33-26]]

^<<v24-33-26,26>>^ so I will never reject the offspring^&#42;1^ of Jacob and of my servant David, so as not to take from his offspring^&#42;2^ rulers over the descendants^&#42;3^ of Abraham, Isaac, and Jacob. For I will gather back their captives and have pity on them.’”

[NOTE]
====
. Lit., “seed.”
. Lit., “seed.”
. Lit., “seed.”
====

'''

xref:024-jeremiah/024-jeremiah-032.adoc#v24-32-0[&#60; Capítulo Anterior] | <<v24-33-0,Topo>> | xref:024-jeremiah/024-jeremiah-034.adoc#v24-34-0[Próximo Capítulo &#62;]