include::./index.adoc[]

[[v24-15-0]]
=== Jeremiah, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-15-1]]

^<<v24-15-1,1>>^ Then Jehovah said to me: “Even if Moses and Samuel were standing before me, I would show no favor toward^&#42;1^ this people. Drive them out from before me. Let them go.

[NOTE]
====
. Or “my soul would not be toward.”
====

[[v24-15-2]]

^<<v24-15-2,2>>^ And if they say to you, ‘Where should we go?’ you must say to them, ‘This is what Jehovah says:
“Whoever is for deadly plague, to deadly plague!
Whoever is for the sword, to the sword!
Whoever is for the famine, to the famine!
And whoever is for the captivity, to the captivity!”’

[[v24-15-3]]

^<<v24-15-3,3>>^ “‘And I will appoint over them four calamities,’^&#42;1^ declares Jehovah, ‘the sword to kill, the dogs to drag away, and the birds of the heavens and the beasts of the earth to devour and to destroy.

[NOTE]
====
. Or possibly, “four kinds of judgment.” Lit., “four families.”
====

[[v24-15-4]]

^<<v24-15-4,4>>^ And I will make them an object of horror to all the kingdoms of the earth because of Ma·nasʹseh the son of Hez·e·kiʹah, the king of Judah, for what he did in Jerusalem.

[[v24-15-5]]

^<<v24-15-5,5>>^ Who will show compassion to you, O Jerusalem,
Who will sympathize with you,
And who will stop to ask about your welfare?’

[[v24-15-6]]

^<<v24-15-6,6>>^ ‘You have deserted me,’ declares Jehovah.
‘You keep turning your back on me.^&#42;1^
So I will stretch out my hand against you and destroy you.
I am tired of feeling pity for you.^&#42;2^

[NOTE]
====
. Or possibly, “keep walking backward.”
. Or “feeling regret.”
====

[[v24-15-7]]

^<<v24-15-7,7>>^ And I will winnow them with a fork in the gates of the land.
I will bereave them of children.
I will destroy my people,
Since they refuse to turn back from their ways.

[[v24-15-8]]

^<<v24-15-8,8>>^ Their widows will become more numerous before me than the sand of the seas.
I will bring a destroyer against them at midday, against mothers and young men.
I will bring agitation and terror upon them suddenly.

[[v24-15-9]]

^<<v24-15-9,9>>^ The woman who bore seven children has grown faint;
She^&#42;1^ struggles for breath.
Her sun has set while it is yet day,
Causing shame and humiliation.’^&#42;2^
‘And those few remaining ones of them
I will give to the sword before their enemies,’ declares Jehovah.”

[NOTE]
====
. Or “Her soul.”
. Or possibly, “It has become ashamed and felt abashed.”
====

[[v24-15-10]]

^<<v24-15-10,10>>^ Woe to me, O my mother, because you gave birth to me,
A man subject to quarrel and strife with all the land.
I have neither loaned nor borrowed;
But all of them curse me.

[[v24-15-11]]

^<<v24-15-11,11>>^ Jehovah said: “I will surely minister to you for good;
I will surely intercede for you in the time of calamity,
In the time of distress against the enemy.

[[v24-15-12]]

^<<v24-15-12,12>>^ Can anyone break iron in pieces,
Iron from the north, and copper?

[[v24-15-13]]

^<<v24-15-13,13>>^ Your resources and your treasures I will give as plunder,
Not for a price, but because of all your sins throughout all your territories.

[[v24-15-14]]

^<<v24-15-14,14>>^ I will give them to your enemies
To take to a land you do not know.
For a fire has been ignited by my anger,
And it is burning against you.”

[[v24-15-15]]

^<<v24-15-15,15>>^ You know, O Jehovah,
Remember me and turn your attention to me.
Take vengeance on my persecutors for me.
Do not let me perish^&#42;1^ because of your slowness to anger.
Know that for your sake I bear this reproach.

[NOTE]
====
. Lit., “Do not take me away.”
====

[[v24-15-16]]

^<<v24-15-16,16>>^ Your words were found, and I ate them;
And your word became to me the exultation and the rejoicing of my heart,
For your name has been called on me, O Jehovah God of armies.

[[v24-15-17]]

^<<v24-15-17,17>>^ I do not sit in the company of merrymakers and rejoice.
Because your hand is upon me, I sit alone,
For you have filled me with indignation.^&#42;1^

[NOTE]
====
. Or “a message of denunciation.”
====

[[v24-15-18]]

^<<v24-15-18,18>>^ Why is my pain chronic and my wound incurable?
It refuses to be healed.
Will you become to me like a deceptive water supply
That cannot be relied on?

[[v24-15-19]]

^<<v24-15-19,19>>^ Therefore this is what Jehovah says:
“If you return, then I will restore you,
And you will stand before me.
If you separate what is precious from what is worthless,
You will become like my own mouth.^&#42;1^
They will have to turn to you,
But you will not turn to them.”

[NOTE]
====
. Or “become my spokesman.”
====

[[v24-15-20]]

^<<v24-15-20,20>>^ “I am making you a fortified copper wall to this people.
They will certainly fight against you,
But they will not prevail against you,^&#42;1^
For I am with you, to save you and to rescue you,” declares Jehovah.

[NOTE]
====
. Or “defeat you.”
====

[[v24-15-21]]

^<<v24-15-21,21>>^ “And I will rescue you from the hand of the wicked
And redeem you from the palm of the ruthless.”

'''

xref:024-jeremiah/024-jeremiah-014.adoc#v24-14-0[&#60; Capítulo Anterior] | <<v24-15-0,Topo>> | xref:024-jeremiah/024-jeremiah-016.adoc#v24-16-0[Próximo Capítulo &#62;]