include::./index.adoc[]

[[v24-14-0]]
=== Jeremiah, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-14-1]]

^<<v24-14-1,1>>^ This is the word of Jehovah that came to Jeremiah concerning the droughts:

[[v24-14-2]]

^<<v24-14-2,2>>^ Judah mourns, and its gates have faded away.
They sink to the ground dejected,
And a cry goes up from Jerusalem.

[[v24-14-3]]

^<<v24-14-3,3>>^ And their masters send their servants^&#42;1^ for water.
They go to the water holes^&#42;2^ and find no water.
They return with their vessels empty.
They are ashamed and disappointed,
And they cover their heads.

[NOTE]
====
. Or “their small ones.”
. Or “the ditches; the cisterns.”
====

[[v24-14-4]]

^<<v24-14-4,4>>^ Because the ground is cracked,
For there is no rain on the land,
The farmers are dismayed and cover their heads.

[[v24-14-5]]

^<<v24-14-5,5>>^ Even the doe in the field forsakes her newborn
Because there is no grass.

[[v24-14-6]]

^<<v24-14-6,6>>^ The wild donkeys stand on the bare hills.
They pant for air like jackals;
Their eyes fail because there is no vegetation.

[[v24-14-7]]

^<<v24-14-7,7>>^ Although our own errors testify against us,
O Jehovah, act for the sake of your name.
For our acts of unfaithfulness are many,
And it is against you that we have sinned.

[[v24-14-8]]

^<<v24-14-8,8>>^ O hope of Israel, his Savior in times of distress,
Why are you like a stranger in the land,
Like a traveler who stops only to spend the night?

[[v24-14-9]]

^<<v24-14-9,9>>^ Why are you like a man who is stunned,
Like a mighty man who cannot save?
For you are among us, O Jehovah,
And your name has been called on us.
Do not abandon us.

[[v24-14-10]]

^<<v24-14-10,10>>^ This is what Jehovah says concerning this people: “They love to wander about; they have not restrained their feet. So Jehovah finds no pleasure in them. Now he will remember their error and call them to account for their sins.”

[[v24-14-11]]

^<<v24-14-11,11>>^ Then Jehovah said to me: “Do not pray for good to come to this people.

[[v24-14-12]]

^<<v24-14-12,12>>^ When they fast, I do not listen to their entreaties, and when they offer whole burnt offerings and grain offerings, I take no pleasure in them, for by the sword, by famine, and by pestilence,^&#42;1^ I will do away with them.”

[NOTE]
====
. Or “disease.”
====

[[v24-14-13]]

^<<v24-14-13,13>>^ At this I said: “Alas, O Sovereign Lord Jehovah! Here the prophets are saying to them, ‘You will not see the sword, and famine will not come upon you, but I will give you true peace in this place.’”

[[v24-14-14]]

^<<v24-14-14,14>>^ Jehovah then said to me: “The prophets are prophesying lies in my name. I have not sent them or commanded them or spoken to them. A lying vision and a worthless divination and the deceit of their own heart is what they are prophesying to you.

[[v24-14-15]]

^<<v24-14-15,15>>^ Therefore this is what Jehovah says concerning the prophets who are prophesying in my name, though I did not send them, and who say that no sword or famine will occur in this land: ‘By sword and by famine those prophets will perish.

[[v24-14-16]]

^<<v24-14-16,16>>^ And the people to whom they are prophesying will be cast out into the streets of Jerusalem because of the famine and the sword, with no one to bury them—them, their wives, their sons, or their daughters—for I will pour out on them the calamity they deserve.’

[[v24-14-17]]

^<<v24-14-17,17>>^ “You must speak this word to them,
‘Let my eyes stream with tears night and day, let them not cease,
For the virgin daughter of my people has been completely crushed and broken,
With an extremely severe wound.

[[v24-14-18]]

^<<v24-14-18,18>>^ If I go out into the field and look,
I see those slain by the sword!
And if I come into the city,
I see the diseases from the famine!
For both the prophet and the priest have gone around in a land that they do not know.’”

[[v24-14-19]]

^<<v24-14-19,19>>^ Have you completely rejected Judah, or have you^&#42;1^ abhorred Zion?
Why have you struck us, so that there is no healing for us?
There was a hope for peace, but nothing good came,
For a time of healing, but there is terror!

[NOTE]
====
. Or “has your soul.”
====

[[v24-14-20]]

^<<v24-14-20,20>>^ We acknowledge our wickedness, O Jehovah,
And the error of our forefathers,
For we have sinned against you.

[[v24-14-21]]

^<<v24-14-21,21>>^ For the sake of your name, do not reject us;
Do not despise your glorious throne.
Remember, and do not break your covenant with us.

[[v24-14-22]]

^<<v24-14-22,22>>^ Can any of the worthless idols of the nations give rain,
Or can even the heavens send showers of rain on their own?
Are you not the only One, O Jehovah our God?
And we hope in you,
For you alone have done all these things.

'''

xref:024-jeremiah/024-jeremiah-013.adoc#v24-13-0[&#60; Capítulo Anterior] | <<v24-14-0,Topo>> | xref:024-jeremiah/024-jeremiah-015.adoc#v24-15-0[Próximo Capítulo &#62;]