include::./index.adoc[]

[[v24-43-0]]
=== Jeremiah, 43
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-43-1]]

^<<v24-43-1,1>>^ When Jeremiah had finished speaking to all the people all these words from Jehovah their God, every single word that Jehovah their God had sent him to tell them,

[[v24-43-2]]

^<<v24-43-2,2>>^ Az·a·riʹah the son of Ho·shaiʹah, Jo·haʹnan the son of Ka·reʹah, and all the presumptuous men said to Jeremiah: “What you are saying is a lie! Jehovah our God has not sent you to say, ‘Do not go to Egypt to reside there.’

[[v24-43-3]]

^<<v24-43-3,3>>^ But Barʹuch the son of Ne·riʹah is inciting you against us to hand us over to the Chal·deʹans, to put us to death or to take us into exile in Babylon.”

[[v24-43-4]]

^<<v24-43-4,4>>^ So Jo·haʹnan the son of Ka·reʹah and all the army chiefs and all the people disobeyed the voice of Jehovah to remain in the land of Judah.

[[v24-43-5]]

^<<v24-43-5,5>>^ Instead, Jo·haʹnan the son of Ka·reʹah and all the army chiefs took with them all the remnant of Judah who had returned to reside in the land of Judah from all the nations where they had been dispersed.

[[v24-43-6]]

^<<v24-43-6,6>>^ They took the men, the women, the children, the daughters of the king, and everyone^&#42;1^ whom Neb·uʹzar·adʹan the chief of the guard had left with Ged·a·liʹah the son of A·hiʹkam the son of Shaʹphan, as well as Jeremiah the prophet and Barʹuch the son of Ne·riʹah.

[NOTE]
====
. Or “every soul.”
====

[[v24-43-7]]

^<<v24-43-7,7>>^ And they went into the land of Egypt, for they did not obey the voice of Jehovah, and they went as far as Tahʹpan·hes.

[[v24-43-8]]

^<<v24-43-8,8>>^ Then the word of Jehovah came to Jeremiah in Tahʹpan·hes, saying:

[[v24-43-9]]

^<<v24-43-9,9>>^ “Take in your hand large stones, and hide them in the mortar in the brick terrace at the entrance of the house of Pharʹaoh in Tahʹpan·hes, with the Jewish men looking on.

[[v24-43-10]]

^<<v24-43-10,10>>^ Then say to them, ‘This is what Jehovah of armies, the God of Israel, says: “Here I am sending for Neb·u·chad·nezʹzar^&#42;1^ the king of Babylon, my servant, and I will place his throne right above these stones that I have hidden, and he will extend his royal tent over them.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-43-11]]

^<<v24-43-11,11>>^ And he will come in and strike the land of Egypt. Whoever is meant for deadly plague will be for deadly plague, and whoever is meant for captivity will be for captivity, and whoever is meant for the sword will be for the sword.

[[v24-43-12]]

^<<v24-43-12,12>>^ And I will set the houses^&#42;1^ of the gods of Egypt on fire, and he will burn them and lead them captive. He will wrap the land of Egypt around himself just as a shepherd wraps himself in his garment, and he will depart from there in peace.^&#42;2^

[NOTE]
====
. Or “temples.”
. Or “unharmed.”
====

[[v24-43-13]]

^<<v24-43-13,13>>^ And he will break to pieces the pillars^&#42;1^ of Beth-sheʹmesh^&#42;2^ in the land of Egypt, and he will burn the houses^&#42;3^ of the gods of Egypt with fire.”’”

[NOTE]
====
. Or “obelisks.”
. Or “House (Temple) of the Sun,” that is, Heliopolis.
. Or “temples.”
====

'''

xref:024-jeremiah/024-jeremiah-042.adoc#v24-42-0[&#60; Capítulo Anterior] | <<v24-43-0,Topo>> | xref:024-jeremiah/024-jeremiah-044.adoc#v24-44-0[Próximo Capítulo &#62;]