include::./index.adoc[]

[[v24-5-0]]
=== Jeremiah, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-5-1]]

^<<v24-5-1,1>>^ Roam the streets of Jerusalem.
Look around and take note.
Search her public squares to see
Whether you can find a man who acts with justice,
One who seeks to be faithful,
And I will forgive her.

[[v24-5-2]]

^<<v24-5-2,2>>^ Even if they say: “As surely as Jehovah is alive!”
They would still swear to what is false.

[[v24-5-3]]

^<<v24-5-3,3>>^ O Jehovah, do your eyes not look for faithfulness?
You struck them, but it made no impact on them.^&#42;1^
You exterminated them, but they refused to accept discipline.
They made their faces harder than a rock,
And they refused to turn around.

[NOTE]
====
. Lit., “they did not become weak.”
====

[[v24-5-4]]

^<<v24-5-4,4>>^ But I said to myself: “Surely these must be the lowly.
They act foolishly, for they do not know the way of Jehovah,
The judgment of their God.

[[v24-5-5]]

^<<v24-5-5,5>>^ I will go to the prominent men and speak with them,
For they must have taken note of the way of Jehovah,
The judgment of their God.
But they had all broken the yoke
And torn apart the restraints.”^&#42;1^

[NOTE]
====
. Lit., “bands.”
====

[[v24-5-6]]

^<<v24-5-6,6>>^ That is why a lion of the forest attacks them,
A wolf of the desert plains keeps ravaging them,
A leopard lies awake at their cities.
Everyone going out from them is torn to pieces.
For their transgressions are many;
Their acts of unfaithfulness are numerous.

[[v24-5-7]]

^<<v24-5-7,7>>^ How can I forgive you for this?
Your sons have abandoned me,
And they swear by what is no God.
I satisfied their needs,
But they kept committing adultery,
And they flocked to the house of a prostitute.

[[v24-5-8]]

^<<v24-5-8,8>>^ They are like eager, lustful horses,
Each neighing after another man’s wife.

[[v24-5-9]]

^<<v24-5-9,9>>^ “Should I not call them to account for these things?” declares Jehovah.
“Should I^&#42;1^ not avenge myself on such a nation?”

[NOTE]
====
. Or “my soul.”
====

[[v24-5-10]]

^<<v24-5-10,10>>^ “Come up against her vineyard terraces and bring ruin,
But do not make a complete extermination.
Take away her spreading shoots,
For they do not belong to Jehovah.

[[v24-5-11]]

^<<v24-5-11,11>>^ For the house of Israel and the house of Judah
Have been utterly treacherous with me,” declares Jehovah.

[[v24-5-12]]

^<<v24-5-12,12>>^ “They have denied Jehovah, and they keep saying,
‘He will do nothing.^&#42;1^
No calamity will come upon us;
We will not see sword or famine.’

[NOTE]
====
. Or possibly, “He does not exist.”
====

[[v24-5-13]]

^<<v24-5-13,13>>^ The prophets are full of wind,
And the word^&#42;1^ is not in them.
Let this happen to them!”

[NOTE]
====
. That is, God’s word.
====

[[v24-5-14]]

^<<v24-5-14,14>>^ Therefore this is what Jehovah, the God of armies, says:
“Because these men are saying this,
Here I am making my words a fire in your mouth,
And this people is the wood,
And it will consume them.”

[[v24-5-15]]

^<<v24-5-15,15>>^ “Here I am bringing in on you a nation from far away, O house of Israel,” declares Jehovah.
“It is an enduring nation.
It is an ancient nation,
A nation whose language you do not know,
And whose speech you cannot understand.

[[v24-5-16]]

^<<v24-5-16,16>>^ Their quiver is like an open grave;
All of them are warriors.

[[v24-5-17]]

^<<v24-5-17,17>>^ They will devour your harvest and your bread.
They will devour your sons and your daughters.
They will devour your flocks and your herds.
They will devour your vines and your fig trees.
They will destroy with the sword your fortified cities in which you trust.”

[[v24-5-18]]

^<<v24-5-18,18>>^ “But even in those days,” declares Jehovah, “I will not carry out a complete extermination of you.

[[v24-5-19]]

^<<v24-5-19,19>>^ And when they ask, ‘Why has Jehovah our God done all these things to us?’ you should answer them, ‘Just as you abandoned me to serve a foreign god in your land, so you will serve foreigners in a land that is not yours.’”

[[v24-5-20]]

^<<v24-5-20,20>>^ Declare this in the house of Jacob,
And proclaim it in Judah, saying:

[[v24-5-21]]

^<<v24-5-21,21>>^ “Hear this, you foolish and senseless people:^&#42;1^
They have eyes but cannot see;
They have ears but cannot hear.

[NOTE]
====
. Lit., “you foolish people without heart.”
====

[[v24-5-22]]

^<<v24-5-22,22>>^ ‘Do you not fear me?’ declares Jehovah,
‘Should you not tremble before me?
It is I who placed the sand as the boundary for the sea,
A permanent regulation that it cannot pass over.
Although its waves toss, they cannot prevail;
Although they roar, they still cannot pass beyond it.

[[v24-5-23]]

^<<v24-5-23,23>>^ But this people has a stubborn and rebellious heart;
They have turned aside and gone their own way.

[[v24-5-24]]

^<<v24-5-24,24>>^ And they do not say in their heart:
“Let us now fear Jehovah our God,
The One who gives the rain in its season,
Both the autumn rain and the spring rain,
The One who guards for us the appointed weeks of the harvest.”

[[v24-5-25]]

^<<v24-5-25,25>>^ Your own errors have prevented these things from coming;
Your own sins have deprived you of what is good.

[[v24-5-26]]

^<<v24-5-26,26>>^ For among my people there are wicked men.
They keep peering, as when birdcatchers crouch down.
They set a deadly trap.
It is men whom they catch.

[[v24-5-27]]

^<<v24-5-27,27>>^ Like a cage full of birds,
So their houses are full of deception.
That is why they have become powerful and rich.

[[v24-5-28]]

^<<v24-5-28,28>>^ They have grown fat and smooth;
They overflow with evil.
They do not plead the legal case of the fatherless,
That they may gain success;
And they deny justice to the poor.’”

[[v24-5-29]]

^<<v24-5-29,29>>^ “Should I not call them to account for these things?” declares Jehovah.
“Should I^&#42;1^ not avenge myself on such a nation?

[NOTE]
====
. Or “my soul.”
====

[[v24-5-30]]

^<<v24-5-30,30>>^ Something appalling and horrible has occurred in the land:

[[v24-5-31]]

^<<v24-5-31,31>>^ The prophets prophesy lies,
And the priests dominate by their own authority.
And my own people love it that way.
But what will you do when the end comes?”

'''

xref:024-jeremiah/024-jeremiah-004.adoc#v24-4-0[&#60; Capítulo Anterior] | <<v24-5-0,Topo>> | xref:024-jeremiah/024-jeremiah-006.adoc#v24-6-0[Próximo Capítulo &#62;]