include::./index.adoc[]

[[v24-48-0]]
=== Jeremiah, 48
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-48-1]]

^<<v24-48-1,1>>^ For Moʹab, this is what Jehovah of armies, the God of Israel, says:
“Woe to Neʹbo, for she has been destroyed!
Kir·i·a·thaʹim has been put to shame and captured.
The secure refuge^&#42;1^ has been put to shame and shattered.

[NOTE]
====
. Or “secure height.”
====

[[v24-48-2]]

^<<v24-48-2,2>>^ They no longer praise Moʹab.
In Heshʹbon they have plotted her downfall:
‘Come, let us put an end to her as a nation.’
You too, O Madʹmen, should keep silent,
For the sword is following you.

[[v24-48-3]]

^<<v24-48-3,3>>^ There is the sound of an outcry from Hor·o·naʹim,
Of destruction and great collapse.

[[v24-48-4]]

^<<v24-48-4,4>>^ Moʹab has been broken down.
Her little ones cry out.

[[v24-48-5]]

^<<v24-48-5,5>>^ On the ascent of Luʹhith they weep continually as they climb.
And on the way down from Hor·o·naʹim they hear cries of distress over the catastrophe.

[[v24-48-6]]

^<<v24-48-6,6>>^ Flee, escape for your lives!^&#42;1^
You must become like a juniper tree in the wilderness.

[NOTE]
====
. Or “souls.”
====

[[v24-48-7]]

^<<v24-48-7,7>>^ Because you trust in your works and in your treasures,
You will also be captured.
And Cheʹmosh will go into exile,
Together with his priests and his princes.

[[v24-48-8]]

^<<v24-48-8,8>>^ The destroyer will come in on every city,
And no city will escape.
The valley^&#42;1^ will perish,
And the level land^&#42;2^ will be annihilated, just as Jehovah has said.

[NOTE]
====
. Or “low plain.”
. Or “the tableland; the plateau.”
====

[[v24-48-9]]

^<<v24-48-9,9>>^ Set up a marker for Moʹab,
For as she falls into ruins she will flee,
And her cities will become an object of horror,
Without an inhabitant.

[[v24-48-10]]

^<<v24-48-10,10>>^ Cursed is the one who carries out the mission of Jehovah neglectfully!
Cursed is the one who holds back his sword from bloodshed!

[[v24-48-11]]

^<<v24-48-11,11>>^ The Moʹab·ites have been undisturbed since their youth,
Like wine that has settled on the dregs.
They have not been poured from one vessel into another,
And they have never gone into exile.
That is why their taste has remained the same,
And their aroma has not changed.

[[v24-48-12]]

^<<v24-48-12,12>>^ “‘Therefore look! the days are coming,’ declares Jehovah, ‘when I will send men to overturn them. They will turn them over and empty out their vessels, and they will smash their large jars to pieces.

[[v24-48-13]]

^<<v24-48-13,13>>^ And the Moʹab·ites will be ashamed of Cheʹmosh, just as the house of Israel is ashamed of Bethʹel, which was their confidence.

[[v24-48-14]]

^<<v24-48-14,14>>^ How dare you say: “We are mighty warriors, ready for battle”?’

[[v24-48-15]]

^<<v24-48-15,15>>^ ‘Moʹab has been destroyed,
Her cities have been invaded,
And their choicest young men have been slaughtered,’
Declares the King, whose name is Jehovah of armies.

[[v24-48-16]]

^<<v24-48-16,16>>^ The disaster on the Moʹab·ites is coming soon,
And their downfall is approaching quickly.

[[v24-48-17]]

^<<v24-48-17,17>>^ All those around them will have to sympathize with them,
All those knowing their name.
Tell them: ‘O how the mighty rod has been broken, the staff of beauty!’

[[v24-48-18]]

^<<v24-48-18,18>>^ Come down from your glory,
And sit down in thirst,^&#42;1^ O daughter inhabiting Diʹbon,
For the destroyer of Moʹab has come against you,
And he will bring your fortified places to ruin.

[NOTE]
====
. Or possibly, “on the dry ground.”
====

[[v24-48-19]]

^<<v24-48-19,19>>^ Stand by the road and watch, inhabitant of A·roʹer.
Ask the man fleeing and the woman escaping, ‘What has happened?’

[[v24-48-20]]

^<<v24-48-20,20>>^ Moʹab has been put to shame and struck with terror.
Wail and cry out.
Proclaim in Arʹnon that Moʹab has been destroyed.

[[v24-48-21]]

^<<v24-48-21,21>>^ “Judgment has come to the level land,^&#42;1^ against Hoʹlon, Jaʹhaz, and Mephʹa·ath;

[NOTE]
====
. Or “the tableland; the plateau.”
====

[[v24-48-22]]

^<<v24-48-22,22>>^ against Diʹbon, Neʹbo, and Beth-dib·la·thaʹim;

[[v24-48-23]]

^<<v24-48-23,23>>^ against Kir·i·a·thaʹim, Beth-gaʹmul, and Beth-meʹon;

[[v24-48-24]]

^<<v24-48-24,24>>^ against Keʹri·oth and Bozʹrah; and against all the cities of the land of Moʹab, those far and near.

[[v24-48-25]]

^<<v24-48-25,25>>^ ‘The strength^&#42;1^ of Moʹab has been cut down;
His arm has been broken,’ declares Jehovah.

[NOTE]
====
. Lit., “horn.”
====

[[v24-48-26]]

^<<v24-48-26,26>>^ ‘Make him drunk, for he has exalted himself against Jehovah.
Moʹab wallows in his vomit,
And he is an object of ridicule.

[[v24-48-27]]

^<<v24-48-27,27>>^ Was Israel not an object of ridicule to you?
Was he found among thieves,
So that you should shake your head and speak against him?

[[v24-48-28]]

^<<v24-48-28,28>>^ Leave the cities and live on the crag, inhabitants of Moʹab,
And become like a dove that nests along the sides of the gorge.’”

[[v24-48-29]]

^<<v24-48-29,29>>^ “We have heard about the pride of Moʹab—he is very haughty—
About his arrogance, his pride, his haughtiness, and the loftiness of his heart.”

[[v24-48-30]]

^<<v24-48-30,30>>^ “‘I know his fury,’ declares Jehovah,
‘But his empty talk will come to nothing.
They will do nothing.

[[v24-48-31]]

^<<v24-48-31,31>>^ That is why I will wail over Moʹab,
For all Moʹab I will cry out
And moan for the men of Kir-heʹres.

[[v24-48-32]]

^<<v24-48-32,32>>^ With more than the weeping for Jaʹzer,
I will weep for you, O vine of Sibʹmah.
Your flourishing shoots have crossed the sea.
To the sea, to Jaʹzer, they have reached.
Upon your summer fruit and your grape harvest
The destroyer has descended.

[[v24-48-33]]

^<<v24-48-33,33>>^ Rejoicing and joyfulness have been removed from the orchard
And from the land of Moʹab.
I have caused the wine to stop flowing from the winepress.
No one will be treading with shouts of joy.
The shouting will be different shouting.’”

[[v24-48-34]]

^<<v24-48-34,34>>^ “‘There is an outcry from Heshʹbon clear to E·le·aʹleh.
They raise their voice clear to Jaʹhaz,
From Zoʹar to Hor·o·naʹim to Egʹlath-she·liʹshi·yah.
Even the waters of Nimʹrim will become desolate.

[[v24-48-35]]

^<<v24-48-35,35>>^ I will cause to cease from Moʹab,’ declares Jehovah,
‘The one bringing an offering on the high place
And the one making sacrifices to his god.

[[v24-48-36]]

^<<v24-48-36,36>>^ That is why my heart will moan^&#42;1^ for Moʹab like a flute,^&#42;2^
And my heart will moan^&#42;3^ for the men of Kir-heʹres like a flute.^&#42;4^
For the wealth he has produced will perish.

[NOTE]
====
. Or “be boisterous.”
. That is, a flute played in lamentation at a funeral.
. Or “be boisterous.”
. That is, a flute played in lamentation at a funeral.
====

[[v24-48-37]]

^<<v24-48-37,37>>^ For every head is bald,
And every beard is clipped.
There are cuts on every hand,
And there is sackcloth on their hips!’”

[[v24-48-38]]

^<<v24-48-38,38>>^ “‘On all the roofs of Moʹab
And in all her public squares,
There is nothing but wailing.
For I have broken Moʹab
Like a discarded jar,’ declares Jehovah.

[[v24-48-39]]

^<<v24-48-39,39>>^ ‘How she is terrified! Wail!
How Moʹab has turned his back in shame!
Moʹab has become an object of ridicule,
Something terrifying to all those around him.’”

[[v24-48-40]]

^<<v24-48-40,40>>^ “For this is what Jehovah says:
‘Look! Just like an eagle that swoops down,
He will spread his wings over Moʹab.

[[v24-48-41]]

^<<v24-48-41,41>>^ The towns will be captured,
And her strongholds will be seized.
In that day the heart of Moʹab’s warriors
Will be like the heart of a woman in childbirth.’”

[[v24-48-42]]

^<<v24-48-42,42>>^ “‘And Moʹab will be annihilated from being a people,
For it is against Jehovah that he has exalted himself.

[[v24-48-43]]

^<<v24-48-43,43>>^ Terror and the pit and the trap are before you,
O inhabitant of Moʹab,’ declares Jehovah.

[[v24-48-44]]

^<<v24-48-44,44>>^ ‘Anyone fleeing the terror will fall into the pit,
And anyone coming up from the pit will be caught in the trap.’
‘For I will bring on Moʹab the year of their punishment,’ declares Jehovah.

[[v24-48-45]]

^<<v24-48-45,45>>^ ‘In the shadow of Heshʹbon, those fleeing stand powerless.
For a fire will come out of Heshʹbon
And a flame from within Siʹhon.
It will consume the forehead of Moʹab
And the skull of the sons of tumult.’

[[v24-48-46]]

^<<v24-48-46,46>>^ ‘Woe to you, O Moʹab!
The people of Cheʹmosh have perished.
For your sons have been taken captive,
And your daughters have gone into exile.

[[v24-48-47]]

^<<v24-48-47,47>>^ But I will gather the captives of Moʹab in the final part of the days,’ declares Jehovah.
‘Down to this point is the judgment on Moʹab.’”

'''

xref:024-jeremiah/024-jeremiah-047.adoc#v24-47-0[&#60; Capítulo Anterior] | <<v24-48-0,Topo>> | xref:024-jeremiah/024-jeremiah-049.adoc#v24-49-0[Próximo Capítulo &#62;]