include::./index.adoc[]

[[v24-12-0]]
=== Jeremiah, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-12-1]]

^<<v24-12-1,1>>^ You are righteous, O Jehovah, when I make my complaint to you,
When I speak about matters of justice with you.
But why is the way of wicked ones successful,
And why are the treacherous unworried?

[[v24-12-2]]

^<<v24-12-2,2>>^ You planted them, and they have taken root.
They have grown and produced fruit.
You are on their lips, but far away from their innermost thoughts.^&#42;1^

[NOTE]
====
. Or “deepest emotions.” Lit., “kidneys.”
====

[[v24-12-3]]

^<<v24-12-3,3>>^ But you know me well, O Jehovah, you see me;
You have examined my heart and found it in union with you.
Single them out like sheep for slaughtering,
And set them apart for the day of killing.

[[v24-12-4]]

^<<v24-12-4,4>>^ How much longer should the land wither away
And the vegetation of every field dry up?
Because of the evil of those dwelling in it,
The beasts and the birds have been swept away.
For they have said: “He does not see what will happen to us.”

[[v24-12-5]]

^<<v24-12-5,5>>^ If you get tired running with footmen,
How can you run a race against horses?
Even if you are confident in the land of peace,
How will you fare among the dense thickets along the Jordan?

[[v24-12-6]]

^<<v24-12-6,6>>^ For even your own brothers, the household of your own father,
Have dealt treacherously with you.
They have raised a loud cry against you.
Do not put faith in them,
Even if they speak good things to you.

[[v24-12-7]]

^<<v24-12-7,7>>^ “I have abandoned my house; I have deserted my inheritance.
I have given my dearly beloved one^&#42;1^ into the hand of her enemies.

[NOTE]
====
. Or “the beloved one of my soul.”
====

[[v24-12-8]]

^<<v24-12-8,8>>^ My inheritance has become to me like a lion in the forest.
She has roared against me.
So I have come to hate her.

[[v24-12-9]]

^<<v24-12-9,9>>^ My inheritance is like a multicolored^&#42;1^ bird of prey to me;
The other birds of prey surround it and attack it.
Come, gather together, all you beasts of the field,
Come to eat.

[NOTE]
====
. Or “speckled.”
====

[[v24-12-10]]

^<<v24-12-10,10>>^ Many shepherds have destroyed my vineyard;
They have trampled my portion of land.
They have turned my desirable portion of land into a desolate wilderness.

[[v24-12-11]]

^<<v24-12-11,11>>^ It has become a wasteland.
It has withered;^&#42;1^
It is desolate before me.
The whole land has been made desolate,
But no man takes it to heart.

[NOTE]
====
. Or possibly, “It mourns.”
====

[[v24-12-12]]

^<<v24-12-12,12>>^ On all the worn paths through the wilderness the destroyers have come,
For the sword of Jehovah is devouring from one end of the land to the other end.
There is no peace for anyone.^&#42;1^

[NOTE]
====
. Lit., “any flesh.”
====

[[v24-12-13]]

^<<v24-12-13,13>>^ They have sown wheat, but they have reaped thorns.
They have worn themselves out, but to no benefit.
They will be ashamed of their produce
Because of the burning anger of Jehovah.”

[[v24-12-14]]

^<<v24-12-14,14>>^ This is what Jehovah says against all my wicked neighbors, who are touching the inheritance that I caused my people Israel to possess: “Here I am uprooting them from their land, and I will uproot the house of Judah from among them.

[[v24-12-15]]

^<<v24-12-15,15>>^ But after I uproot them, I will again have mercy on them and bring each of them back to his inheritance and to his land.”

[[v24-12-16]]

^<<v24-12-16,16>>^ “And if they make sure to learn the ways of my people and to swear by my name, ‘As surely as Jehovah is alive!’ just as they taught my people to swear by Baʹal, they will then be built up among my people.

[[v24-12-17]]

^<<v24-12-17,17>>^ But if they refuse to obey, I will also uproot that nation, uprooting and destroying it,” declares Jehovah.

'''

xref:024-jeremiah/024-jeremiah-011.adoc#v24-11-0[&#60; Capítulo Anterior] | <<v24-12-0,Topo>> | xref:024-jeremiah/024-jeremiah-013.adoc#v24-13-0[Próximo Capítulo &#62;]