include::./index.adoc[]

[[v24-34-0]]
=== Jeremiah, 34
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-34-1]]

^<<v24-34-1,1>>^ The word that came to Jeremiah from Jehovah, when King Neb·u·chad·nezʹzar^&#42;1^ of Babylon and all his army and all the kingdoms of the earth under his dominion and all the peoples were fighting against Jerusalem and all her cities:

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-34-2]]

^<<v24-34-2,2>>^ “This is what Jehovah the God of Israel says, ‘Go and speak to King Zed·e·kiʹah of Judah and tell him: “This is what Jehovah says, ‘Here I am giving this city into the hand of the king of Babylon, and he will burn it with fire.

[[v24-34-3]]

^<<v24-34-3,3>>^ And you will not escape out of his hand, for you will without fail be caught and handed over to him. And you will see the king of Babylon eye to eye, and he will speak to you face-to-face, and you will go to Babylon.’

[[v24-34-4]]

^<<v24-34-4,4>>^ However, hear the word of Jehovah, O King Zed·e·kiʹah of Judah, ‘This is what Jehovah says concerning you: “You will not die by the sword.

[[v24-34-5]]

^<<v24-34-5,5>>^ In peace you will die, and they will make a burning ceremony for you as they did for your fathers, the former kings who were before you, and they will mourn you, ‘Alas, O master!’ for ‘I have spoken the word,’ declares Jehovah.”’”’”

[[v24-34-6]]

^<<v24-34-6,6>>^ Jeremiah the prophet then spoke all these words to King Zed·e·kiʹah of Judah in Jerusalem,

[[v24-34-7]]

^<<v24-34-7,7>>^ when the armies of the king of Babylon were fighting against Jerusalem and against all the cities of Judah that were left, against Laʹchish and against A·zeʹkah; for they were the only fortified cities that remained of the cities of Judah.

[[v24-34-8]]

^<<v24-34-8,8>>^ The word that came to Jeremiah from Jehovah after King Zed·e·kiʹah had made a covenant with all the people in Jerusalem to proclaim liberty to them,

[[v24-34-9]]

^<<v24-34-9,9>>^ that everyone should free his Hebrew slaves, male and female, so that no one would keep a fellow Jew as his slave.

[[v24-34-10]]

^<<v24-34-10,10>>^ So all the princes and all the people obeyed. They had entered into the covenant that everyone should free his male and female slaves and not keep them as slaves any longer. They obeyed and let them go.

[[v24-34-11]]

^<<v24-34-11,11>>^ However, they later brought back the male and female slaves whom they had freed, and they again forced them back into slavery.

[[v24-34-12]]

^<<v24-34-12,12>>^ So the word of Jehovah came to Jeremiah from Jehovah, saying:

[[v24-34-13]]

^<<v24-34-13,13>>^ “This is what Jehovah the God of Israel says, ‘I made a covenant with your forefathers in the day I brought them out of the land of Egypt, out of the house of slavery, saying:

[[v24-34-14]]

^<<v24-34-14,14>>^ “At the end of seven years, each of you should free his Hebrew brother who was sold to you and who has served you six years; you must set him free.” But your forefathers did not listen or incline their ears to me.

[[v24-34-15]]

^<<v24-34-15,15>>^ And recently^&#42;1^ you yourselves turned around and did what was right in my eyes by proclaiming liberty to your fellow men, and you made a covenant before me in the house that bears my name.

[NOTE]
====
. Lit., “today.”
====

[[v24-34-16]]

^<<v24-34-16,16>>^ But then you turned around and profaned my name by bringing back your male and female slaves whom you had freed according to their desire,^&#42;1^ and you forced them back into slavery.’

[NOTE]
====
. Or “soul.”
====

[[v24-34-17]]

^<<v24-34-17,17>>^ “Therefore this is what Jehovah says: ‘You have not obeyed me in proclaiming liberty, each one to his brother and to his fellow man. So I will now proclaim liberty to you,’ declares Jehovah, ‘to the sword, to pestilence,^&#42;1^ and to famine, and I will make you an object of horror to all the kingdoms of the earth.

[NOTE]
====
. Or “disease.”
====

[[v24-34-18]]

^<<v24-34-18,18>>^ And this is what will happen to the men who violated my covenant by not carrying out the words of the covenant that they made before me when they cut the calf in two and passed between the halves,

[[v24-34-19]]

^<<v24-34-19,19>>^ namely, the princes of Judah, the princes of Jerusalem, the court officials, the priests, and all the people of the land who passed between the halves of the calf:

[[v24-34-20]]

^<<v24-34-20,20>>^ I will hand them over to their enemies and to those seeking to take their lives,^&#42;1^ and their dead bodies will become food for the birds of the heavens and for the beasts of the earth.

[NOTE]
====
. Or “seeking their souls.”
====

[[v24-34-21]]

^<<v24-34-21,21>>^ And I will give King Zed·e·kiʹah of Judah and his princes into the hand of their enemies and into the hand of those seeking to take their lives^&#42;1^ and into the hand of the armies of the king of Babylon, who are withdrawing from against you.’

[NOTE]
====
. Or “seeking their souls.”
====

[[v24-34-22]]

^<<v24-34-22,22>>^ “‘Here I will give the order,’ declares Jehovah, ‘and I will bring them back to this city, and they will fight against it and capture it and burn it with fire; and the cities of Judah I will make a wasteland, without an inhabitant.’”

'''

xref:024-jeremiah/024-jeremiah-033.adoc#v24-33-0[&#60; Capítulo Anterior] | <<v24-34-0,Topo>> | xref:024-jeremiah/024-jeremiah-035.adoc#v24-35-0[Próximo Capítulo &#62;]