include::./index.adoc[]

[[v24-4-0]]
=== Jeremiah, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-4-1]]

^<<v24-4-1,1>>^ “If you will return, O Israel,” declares Jehovah,
“If you will return to me
And if you will remove your disgusting idols from before me,
Then you will not be a fugitive.

[[v24-4-2]]

^<<v24-4-2,2>>^ And if you swear,
‘As surely as Jehovah is alive!’ in truth, justice, and righteousness,
Then the nations will obtain a blessing for themselves by him,
And in him they will boast.”

[[v24-4-3]]

^<<v24-4-3,3>>^ For this is what Jehovah says to the men of Judah and to Jerusalem:
“Plow for yourselves arable land,
And do not keep sowing among thorns.

[[v24-4-4]]

^<<v24-4-4,4>>^ Circumcise yourselves to Jehovah,
And remove the foreskins of your hearts,
You men of Judah and inhabitants of Jerusalem,
So that my wrath may not blaze up like a fire
And burn with no one to extinguish it,
Because of your evil deeds.”

[[v24-4-5]]

^<<v24-4-5,5>>^ Declare it in Judah, and proclaim it in Jerusalem.
Shout and blow a horn throughout the land.
Call out loudly and say: “Gather together,
And let us flee into the fortified cities.

[[v24-4-6]]

^<<v24-4-6,6>>^ Raise a signal^&#42;1^ toward Zion.
Seek shelter, and do not stand still,”
For I am bringing in calamity from the north, a great crash.

[NOTE]
====
. Or “signal pole.”
====

[[v24-4-7]]

^<<v24-4-7,7>>^ He has emerged like a lion from his thicket;
The destroyer of nations has set out.
He has gone out from his place to make your land an object of horror.
Your cities will be reduced to ruins, without an inhabitant.

[[v24-4-8]]

^<<v24-4-8,8>>^ Therefore, put on sackcloth,
Mourn^&#42;1^ and wail,
Because the burning anger of Jehovah has not turned away from us.

[NOTE]
====
. Or “Beat your chests.”
====

[[v24-4-9]]

^<<v24-4-9,9>>^ “In that day,” declares Jehovah, “the heart^&#42;1^ of the king will fail him,
Also the heart^&#42;2^ of the princes;
The priests will be horrified, and the prophets will be amazed.”

[NOTE]
====
. Or “courage.”
. Or “courage.”
====

[[v24-4-10]]

^<<v24-4-10,10>>^ Then I said: “Alas, O Sovereign Lord Jehovah! Truly you have utterly deceived this people and Jerusalem, saying, ‘You will have peace,’ when the sword is at our throats.”^&#42;1^

[NOTE]
====
. Or “when the sword has reached our soul.”
====

[[v24-4-11]]

^<<v24-4-11,11>>^ At that time it will be said to this people and to Jerusalem:
“A scorching wind from the barren hills of the desert
Will sweep down on the daughter of^&#42;1^ my people;
It is not coming to winnow or to cleanse.

[NOTE]
====
. A poetic personification, perhaps expressing pity or sympathy.
====

[[v24-4-12]]

^<<v24-4-12,12>>^ The full wind comes from these places at my bidding.
Now I will pronounce judgments against them.

[[v24-4-13]]

^<<v24-4-13,13>>^ Look! He will come like rain clouds,
And his chariots are like a storm wind.
His horses are swifter than eagles.
Woe to us, for we are ruined!

[[v24-4-14]]

^<<v24-4-14,14>>^ Wash your heart clean of wickedness, O Jerusalem, in order to be saved.
How long will you harbor wicked thoughts?

[[v24-4-15]]

^<<v24-4-15,15>>^ For a voice tells the news from Dan,
And it proclaims disaster from the mountains of Eʹphra·im.

[[v24-4-16]]

^<<v24-4-16,16>>^ Report it, yes, to the nations;
Proclaim it against Jerusalem.”
“Sentinels^&#42;1^ are coming from a distant land,
And they will raise their voices against the cities of Judah.

[NOTE]
====
. Lit., “Watchers,” that is, those watching the city to determine when to attack.
====

[[v24-4-17]]

^<<v24-4-17,17>>^ They come against her on all sides like guards of the open field,
Because she has rebelled against me,” declares Jehovah.

[[v24-4-18]]

^<<v24-4-18,18>>^ “Your own ways and your actions will be brought upon you.
How bitter is your disaster,
For it reaches clear to your heart!”

[[v24-4-19]]

^<<v24-4-19,19>>^ O my anguish,^&#42;1^ my anguish!
I feel great pain in my very heart.^&#42;2^
My heart pounds within me.
I cannot keep silent,
For I have^&#42;3^ heard the sound of the horn,
The alarm signal of war.^&#42;4^

[NOTE]
====
. Lit., “my intestines.”
. Lit., “in the walls of my heart.”
. Or “my soul has.”
. Or possibly, “the sound of the battle cry.”
====

[[v24-4-20]]

^<<v24-4-20,20>>^ Disaster after disaster has been reported,
For the whole land has been destroyed.
Suddenly my own tents are destroyed,
In a moment my tent cloths.

[[v24-4-21]]

^<<v24-4-21,21>>^ How long will I keep seeing the signal,^&#42;1^
Keep hearing the sound of the horn?

[NOTE]
====
. Or “signal pole.”
====

[[v24-4-22]]

^<<v24-4-22,22>>^ “For my people are foolish;
They take no note of me.
They are stupid sons, with no understanding.
They are clever^&#42;1^ enough when it comes to doing bad,
But they do not know how to do good.”

[NOTE]
====
. Or “wise.”
====

[[v24-4-23]]

^<<v24-4-23,23>>^ I saw the land, and look! it was empty and desolate.
I looked at the heavens, and their light was no more.

[[v24-4-24]]

^<<v24-4-24,24>>^ I saw the mountains, and look! they were quaking,
And the hills were shaking.

[[v24-4-25]]

^<<v24-4-25,25>>^ I saw, and look! there was no man,
And the birds of the heavens had all fled.

[[v24-4-26]]

^<<v24-4-26,26>>^ I saw, and look! the orchard had become a wilderness,
And its cities had all been torn down.
It was because of Jehovah,
Because of his burning anger.

[[v24-4-27]]

^<<v24-4-27,27>>^ For this is what Jehovah says: “The whole land will become desolate,
But I will not carry out a complete extermination.

[[v24-4-28]]

^<<v24-4-28,28>>^ For this reason the land will mourn,
And the heavens above will become dark.
It is because I have spoken, I have decided,
And I will not change my mind,^&#42;1^ nor will I turn back from it.

[NOTE]
====
. Or “feel regret.”
====

[[v24-4-29]]

^<<v24-4-29,29>>^ At the sound of the horsemen and the archers,
The entire city flees.
They enter into the thickets,
And they climb the rocks.
Every city is abandoned,
And no man dwells in them.”

[[v24-4-30]]

^<<v24-4-30,30>>^ Now that you are devastated, what will you do?
You used to clothe yourself with scarlet,
To deck yourself with gold ornaments,
And to enlarge your eyes with black paint.^&#42;1^
But it is in vain that you beautified yourself,
For those lusting after you have rejected you;
They are now seeking to take your life.^&#42;2^

[NOTE]
====
. Or “eye shadow.”
. Or “seeking your soul.”
====

[[v24-4-31]]

^<<v24-4-31,31>>^ For I have heard the sound like that of a sick woman,
The distress like that of a woman giving birth to her first child,
The voice of the daughter of Zion who keeps gasping for breath.
She says as she spreads out her palms:
“Woe to me, for I am^&#42;1^ exhausted because of the killers!”

[NOTE]
====
. Or “my soul is.”
====

'''

xref:024-jeremiah/024-jeremiah-003.adoc#v24-3-0[&#60; Capítulo Anterior] | <<v24-4-0,Topo>> | xref:024-jeremiah/024-jeremiah-005.adoc#v24-5-0[Próximo Capítulo &#62;]