include::./index.adoc[]

[[v24-32-0]]
=== Jeremiah, 32
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-32-1]]

^<<v24-32-1,1>>^ The word that came to Jeremiah from Jehovah in the 10th year of King Zed·e·kiʹah of Judah, that is, the 18th year of Neb·u·chad·nezʹzar.^&#42;1^

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-32-2]]

^<<v24-32-2,2>>^ At that time the armies of the king of Babylon were besieging Jerusalem, and Jeremiah the prophet was confined in the Courtyard of the Guard in the house^&#42;1^ of the king of Judah.

[NOTE]
====
. Or “palace.”
====

[[v24-32-3]]

^<<v24-32-3,3>>^ For King Zed·e·kiʹah of Judah had confined him, saying, “Why do you prophesy like this? You say, ‘This is what Jehovah says: “I will give this city into the hand of the king of Babylon, and he will capture it,

[[v24-32-4]]

^<<v24-32-4,4>>^ and King Zed·e·kiʹah of Judah will not escape from the Chal·deʹans, for he will surely be given into the hand of the king of Babylon, and he will speak to him face-to-face and see him eye to eye.”’

[[v24-32-5]]

^<<v24-32-5,5>>^ ‘He will take Zed·e·kiʹah to Babylon, and there he will remain until I turn my attention to him,’ declares Jehovah. ‘Although you keep fighting against the Chal·deʹans, you will not succeed.’”

[[v24-32-6]]

^<<v24-32-6,6>>^ Jeremiah said: “The word of Jehovah has come to me, saying,

[[v24-32-7]]

^<<v24-32-7,7>>^ ‘Here Hanʹa·mel the son of Shalʹlum your uncle^&#42;1^ will come to you and say: “Buy for yourself my field in Anʹa·thoth, because you have the first right to repurchase it.”’”

[NOTE]
====
. That is, paternal uncle.
====

[[v24-32-8]]

^<<v24-32-8,8>>^ Hanʹa·mel the son of my uncle came to me, just as Jehovah had said, into the Courtyard of the Guard, and he said to me: “Please buy my field in Anʹa·thoth, in the land of Benjamin, for you have the right to take possession of it and to repurchase it. Buy it for yourself.” At that I knew that this was by the word of Jehovah.

[[v24-32-9]]

^<<v24-32-9,9>>^ So I bought the field in Anʹa·thoth from Hanʹa·mel the son of my uncle. I weighed out the money to him, seven shekels^&#42;1^ and ten silver pieces.

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v24-32-10]]

^<<v24-32-10,10>>^ Then I recorded it in a deed, affixed the seal, called in witnesses, and weighed the money in the scales.

[[v24-32-11]]

^<<v24-32-11,11>>^ I took the deed of purchase, the one that was sealed according to the commandment and legal requirements, as well as the one that was left unsealed,

[[v24-32-12]]

^<<v24-32-12,12>>^ and I gave the deed of purchase to Barʹuch son of Ne·riʹah son of Mah·seiʹah in the presence of Hanʹa·mel the son of my uncle, the witnesses who wrote in the deed of purchase, and all the Jews who were sitting in the Courtyard of the Guard.

[[v24-32-13]]

^<<v24-32-13,13>>^ I now commanded Barʹuch in their presence, saying:

[[v24-32-14]]

^<<v24-32-14,14>>^ “This is what Jehovah of armies, the God of Israel, says, ‘Take these deeds, this deed of purchase, the sealed one and the other deed left unsealed, and put them into an earthenware vessel, so that they may be kept for a long time.’

[[v24-32-15]]

^<<v24-32-15,15>>^ For this is what Jehovah of armies, the God of Israel, says, ‘Houses and fields and vineyards will again be bought in this land.’”

[[v24-32-16]]

^<<v24-32-16,16>>^ Then I prayed to Jehovah after giving the deed of purchase to Barʹuch the son of Ne·riʹah, saying:

[[v24-32-17]]

^<<v24-32-17,17>>^ “Alas, O Sovereign Lord Jehovah! Look! You made the heavens and the earth by your great power and by your outstretched arm. Nothing is too wonderful for you,

[[v24-32-18]]

^<<v24-32-18,18>>^ the One showing loyal love to thousands, but repaying the error of the fathers to^&#42;1^ their sons after them, the true God, the great and mighty One, whose name is Jehovah of armies.

[NOTE]
====
. Lit., “into the bosom of.”
====

[[v24-32-19]]

^<<v24-32-19,19>>^ You are great in counsel^&#42;1^ and mighty in deed, you whose eyes observe all the ways of men, to give to each one according to his ways and according to what he does.

[NOTE]
====
. Or “great as regards your purposes.”
====

[[v24-32-20]]

^<<v24-32-20,20>>^ You have performed signs and miracles in the land of Egypt, which are known down to this day, and thus you have made a name for yourself in Israel and among mankind, as it is today.

[[v24-32-21]]

^<<v24-32-21,21>>^ And you brought your people Israel out of the land of Egypt, with signs, with miracles, with a mighty hand, with an outstretched arm, and with terrifying deeds.

[[v24-32-22]]

^<<v24-32-22,22>>^ “In time you gave them this land that you swore to give to their forefathers, a land flowing with milk and honey.

[[v24-32-23]]

^<<v24-32-23,23>>^ And they came in and took possession of it, but they did not obey your voice or walk in your law. They did not do anything you commanded them to do, so that you caused all this calamity to befall them.

[[v24-32-24]]

^<<v24-32-24,24>>^ Look! Men have come with siege ramparts to capture the city, and because of the sword, the famine, and the pestilence,^&#42;1^ the city will certainly fall into the hands of the Chal·deʹans who are fighting against it; what you said has all happened, as you now see.

[NOTE]
====
. Or “disease.”
====

[[v24-32-25]]

^<<v24-32-25,25>>^ But you have told me, O Sovereign Lord Jehovah, ‘Buy for yourself the field with money and call in witnesses,’ although the city will certainly be given into the hand of the Chal·deʹans.”

[[v24-32-26]]

^<<v24-32-26,26>>^ At that the word of Jehovah came to Jeremiah, saying:

[[v24-32-27]]

^<<v24-32-27,27>>^ “Here I am, Jehovah, the God of all mankind.^&#42;1^ Is there anything too wonderful for me?

[NOTE]
====
. Lit., “all flesh.”
====

[[v24-32-28]]

^<<v24-32-28,28>>^ So this is what Jehovah says, ‘Here I am handing this city over to the Chal·deʹans and into the hand of King Neb·u·chad·nezʹzar^&#42;1^ of Babylon, and he will capture it.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-32-29]]

^<<v24-32-29,29>>^ And the Chal·deʹans fighting against this city will come in and set this city on fire and burn it down along with the houses on whose roofs the people offered sacrifices to Baʹal and poured out drink offerings to other gods to offend me.’

[[v24-32-30]]

^<<v24-32-30,30>>^ “‘For the people of Israel and of Judah have done only what was bad in my eyes, from their youth on; the people of Israel keep offending me by the work of their hands,’ declares Jehovah.

[[v24-32-31]]

^<<v24-32-31,31>>^ ‘For this city, from the day that they built it down to this day, has been nothing but a cause of anger and wrath to me, so that it must be removed from before my face,

[[v24-32-32]]

^<<v24-32-32,32>>^ because of all the evil that the people of Israel and of Judah have done to offend me—they, their kings, their princes, their priests, their prophets, and the men of Judah and the inhabitants of Jerusalem.

[[v24-32-33]]

^<<v24-32-33,33>>^ They kept turning their backs to me, not their faces; although I tried to teach them again and again,^&#42;1^ none of them would listen to receive discipline.

[NOTE]
====
. Lit., “rising up early and teaching.”
====

[[v24-32-34]]

^<<v24-32-34,34>>^ And they put their disgusting idols in the house that bears my name, in order to defile it.

[[v24-32-35]]

^<<v24-32-35,35>>^ Furthermore, they built the high places of Baʹal in the Valley of the Son of Hinʹnom,^&#42;1^ in order to make their sons and their daughters pass through the fire to Moʹlech, something that I had not commanded them and that had never come into my heart^&#42;2^ to do such a detestable thing, causing Judah to sin.’

[NOTE]
====
. See Glossary, “Gehenna.”
. Or “had never entered my thoughts.”
====

[[v24-32-36]]

^<<v24-32-36,36>>^ “Therefore this is what Jehovah the God of Israel says concerning this city that you are saying will be given into the hand of the king of Babylon by the sword, the famine, and the pestilence,

[[v24-32-37]]

^<<v24-32-37,37>>^ ‘Here I will gather them together from all the lands where I dispersed them in my anger and in my wrath and in great indignation, and I will bring them back to this place and let them dwell in security.

[[v24-32-38]]

^<<v24-32-38,38>>^ And they will be my people, and I will be their God.

[[v24-32-39]]

^<<v24-32-39,39>>^ And I will give them one heart and one way so that they may always fear me, for their own good and the good of their children after them.

[[v24-32-40]]

^<<v24-32-40,40>>^ And I will make with them an everlasting covenant, that I will not turn away from doing good to them; and I will put the fear of me in their hearts, so that they will not turn away from me.

[[v24-32-41]]

^<<v24-32-41,41>>^ I will exult over them to do good to them, and I will firmly plant them in this land, with all my heart and with all my soul.’”^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v24-32-42]]

^<<v24-32-42,42>>^ “For this is what Jehovah says, ‘Just as I have brought on this people all this great calamity, so I will bring on them all the goodness^&#42;1^ that I am promising them.

[NOTE]
====
. Or “the good things.”
====

[[v24-32-43]]

^<<v24-32-43,43>>^ And fields will again be bought in this land, though you are saying: “It is a wasteland without man and beast, and it has been handed over to the Chal·deʹans.”’

[[v24-32-44]]

^<<v24-32-44,44>>^ “‘Fields will be bought with money, deeds of purchase will be recorded and sealed, and witnesses will be called in the land of Benjamin, in the areas around Jerusalem, in the cities of Judah, in the cities of the mountainous region, in the cities of the lowland, and in the cities of the south, because I will bring back their captives,’ declares Jehovah.”

'''

xref:024-jeremiah/024-jeremiah-031.adoc#v24-31-0[&#60; Capítulo Anterior] | <<v24-32-0,Topo>> | xref:024-jeremiah/024-jeremiah-033.adoc#v24-33-0[Próximo Capítulo &#62;]