include::./index.adoc[]

[[v24-38-0]]
=== Jeremiah, 38
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-38-1]]

^<<v24-38-1,1>>^ Now Sheph·a·tiʹah the son of Matʹtan, Ged·a·liʹah the son of Pashʹhur, Juʹcal the son of Shel·e·miʹah, and Pashʹhur the son of Mal·chiʹjah heard the words that Jeremiah was speaking to all the people, saying:

[[v24-38-2]]

^<<v24-38-2,2>>^ “This is what Jehovah says, ‘The one who remains in this city will die by the sword, by famine, and by pestilence.^&#42;1^ But the one who surrenders^&#42;2^ to the Chal·deʹans will keep living and will have his life^&#42;3^ as a spoil^&#42;4^ and live.’

[NOTE]
====
. Or “disease.”
. Lit., “goes out.”
. Or “soul.”
. Or “will escape with his life.”
====

[[v24-38-3]]

^<<v24-38-3,3>>^ This is what Jehovah says, ‘This city will surely be handed over to the army of the king of Babylon, and he will capture it.’”

[[v24-38-4]]

^<<v24-38-4,4>>^ The princes said to the king: “Please have this man put to death, for this is how he is weakening the morale^&#42;1^ of the soldiers who are left in this city, as well as that of all the people, by speaking such words to them. For this man seeks, not the peace of this people, but their calamity.”

[NOTE]
====
. Lit., “hands.”
====

[[v24-38-5]]

^<<v24-38-5,5>>^ King Zed·e·kiʹah replied: “Look! He is in your hands, for the king cannot do anything to stop you.”

[[v24-38-6]]

^<<v24-38-6,6>>^ So they took Jeremiah and threw him into the cistern of Mal·chiʹjah the son of the king, which was in the Courtyard of the Guard. They let Jeremiah down by ropes. Now there was no water in the cistern, only mud, and Jeremiah began to sink down into the mud.

[[v24-38-7]]

^<<v24-38-7,7>>^ Eʹbed-melʹech the E·thi·oʹpi·an, a eunuch^&#42;1^ in the king’s house,^&#42;2^ heard that they had put Jeremiah into the cistern. Now the king was sitting in the Gate of Benjamin,

[NOTE]
====
. Or “court official.”
. Or “palace.”
====

[[v24-38-8]]

^<<v24-38-8,8>>^ so Eʹbed-melʹech went out of the king’s house^&#42;1^ and spoke to the king, saying:

[NOTE]
====
. Or “palace.”
====

[[v24-38-9]]

^<<v24-38-9,9>>^ “O my lord the king, what these men have done to Jeremiah the prophet is evil! They have thrown him into the cistern, and he will die there because of the famine, for there is no bread left in the city.”

[[v24-38-10]]

^<<v24-38-10,10>>^ Then the king commanded Eʹbed-melʹech the E·thi·oʹpi·an: “Take 30 men with you from here, and pull Jeremiah the prophet up out of the cistern before he dies.”

[[v24-38-11]]

^<<v24-38-11,11>>^ So Eʹbed-melʹech took the men with him and went into the king’s house^&#42;1^ to a place beneath the treasury, and they took from there some worn-out rags and worn-out pieces of cloth and let them down by ropes to Jeremiah in the cistern.

[NOTE]
====
. Or “palace.”
====

[[v24-38-12]]

^<<v24-38-12,12>>^ Then Eʹbed-melʹech the E·thi·oʹpi·an said to Jeremiah: “Please put the rags and the pieces of cloth between your armpits and the ropes.” Jeremiah did so,

[[v24-38-13]]

^<<v24-38-13,13>>^ and they drew Jeremiah out with the ropes and pulled him up out of the cistern. And Jeremiah remained in the Courtyard of the Guard.

[[v24-38-14]]

^<<v24-38-14,14>>^ King Zed·e·kiʹah sent for Jeremiah the prophet to come to him at the third entrance, which is in the house of Jehovah, and the king said to Jeremiah: “I have something to ask of you. Do not hide anything from me.”

[[v24-38-15]]

^<<v24-38-15,15>>^ Jeremiah then said to Zed·e·kiʹah: “If I tell you, you will certainly put me to death. And if I give you advice, you will not listen to me.”

[[v24-38-16]]

^<<v24-38-16,16>>^ So King Zed·e·kiʹah secretly swore to Jeremiah, saying: “As surely as Jehovah is alive, who has given us this life,^&#42;1^ I will not put you to death, and I will not hand you over to these men who are seeking to take your life.”^&#42;2^

[NOTE]
====
. Or “made for us this soul.”
. Or “seeking your soul.”
====

[[v24-38-17]]

^<<v24-38-17,17>>^ Jeremiah then said to Zed·e·kiʹah: “This is what Jehovah, the God of armies, the God of Israel, says, ‘If you surrender^&#42;1^ to the princes of the king of Babylon, your life will be spared,^&#42;2^ and this city will not be burned with fire, and you and your household will be spared.

[NOTE]
====
. Lit., “go out.”
. Or “your soul will keep living.”
====

[[v24-38-18]]

^<<v24-38-18,18>>^ But if you will not surrender^&#42;1^ to the princes of the king of Babylon, this city will be handed over to the Chal·deʹans, and they will burn it with fire, and you will not escape out of their hand.’”

[NOTE]
====
. Lit., “go out.”
====

[[v24-38-19]]

^<<v24-38-19,19>>^ Then King Zed·e·kiʹah said to Jeremiah: “I am afraid of the Jews who have deserted to the Chal·deʹans, for if I am handed over to them, they may deal cruelly with me.”

[[v24-38-20]]

^<<v24-38-20,20>>^ But Jeremiah said: “You will not be handed over to them. Obey, please, the voice of Jehovah in what I am telling you, and it will go well with you, and you^&#42;1^ will continue to live.

[NOTE]
====
. Or “your soul.”
====

[[v24-38-21]]

^<<v24-38-21,21>>^ But if you refuse to surrender,^&#42;1^ this is what Jehovah has revealed to me:

[NOTE]
====
. Lit., “go out.”
====

[[v24-38-22]]

^<<v24-38-22,22>>^ Look! All the women remaining in the house^&#42;1^ of the king of Judah are being brought out to the princes of the king of Babylon, and they are saying,
‘The men whom you trusted^&#42;2^ have deceived you and overcome you.
They have caused your foot to sink into the mud.
Now they have turned away in retreat.’

[NOTE]
====
. Or “palace.”
. Lit., “The men of your peace.”
====

[[v24-38-23]]

^<<v24-38-23,23>>^ And all your wives and your sons they are bringing out to the Chal·deʹans, and you will not escape out of their hand, but you will be seized by the king of Babylon, and because of you this city will be burned with fire.”

[[v24-38-24]]

^<<v24-38-24,24>>^ Zed·e·kiʹah then said to Jeremiah: “Do not let anyone know about these things, so that you do not die.

[[v24-38-25]]

^<<v24-38-25,25>>^ And if the princes hear that I have spoken with you and they come and say to you, ‘Tell us, please, what you said to the king. Do not hide anything from us, and we will not put you to death. What did the king say to you?’

[[v24-38-26]]

^<<v24-38-26,26>>^ you must answer them, ‘I was making a request of the king, that he not send me back to the house of Je·honʹa·than to die there.’”

[[v24-38-27]]

^<<v24-38-27,27>>^ In time all the princes came in to Jeremiah and questioned him. He told them everything that the king had commanded him to say. So they said no more to him, for no one had heard the conversation.

[[v24-38-28]]

^<<v24-38-28,28>>^ Until the day that Jerusalem was captured, Jeremiah remained in the Courtyard of the Guard; he was still there when Jerusalem was captured.

'''

xref:024-jeremiah/024-jeremiah-037.adoc#v24-37-0[&#60; Capítulo Anterior] | <<v24-38-0,Topo>> | xref:024-jeremiah/024-jeremiah-039.adoc#v24-39-0[Próximo Capítulo &#62;]