include::./index.adoc[]

[[v24-8-0]]
=== Jeremiah, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-8-1]]

^<<v24-8-1,1>>^ “At that time,” declares Jehovah, “the bones of the kings of Judah, the bones of its princes, the bones of the priests, the bones of the prophets, and the bones of the inhabitants of Jerusalem will be taken from their graves.

[[v24-8-2]]

^<<v24-8-2,2>>^ They will be spread out to the sun and to the moon and to all the army of the heavens that they loved and served and followed and sought after and bowed down to. They will not be gathered, nor will they be buried. They will become like manure on the surface of the ground.”

[[v24-8-3]]

^<<v24-8-3,3>>^ “And the remnant of this evil family who survive will choose death over life in all the places where I disperse them,” declares Jehovah of armies.

[[v24-8-4]]

^<<v24-8-4,4>>^ “And you must say to them, ‘This is what Jehovah says:
“Will they fall and not get up again?
If one would turn back, will the other not also turn back?

[[v24-8-5]]

^<<v24-8-5,5>>^ Why is this people, Jerusalem, unfaithful with an enduring unfaithfulness?
They hold fast to deception;
They refuse to turn back.

[[v24-8-6]]

^<<v24-8-6,6>>^ I paid attention and kept listening, but the way they spoke was not right.
Not a man repented over his wickedness or asked, ‘What have I done?’
Each one keeps returning to the popular course, like a horse dashing into the battle.

[[v24-8-7]]

^<<v24-8-7,7>>^ Even the stork in the sky knows its seasons;^&#42;1^
The turtledove and the swift and the thrush^&#42;2^ keep to the time of their return.^&#42;3^
But my own people do not understand the judgment of Jehovah.”’

[NOTE]
====
. Or “appointed times.”
. Or possibly, “crane.”
. Or “migration.”
====

[[v24-8-8]]

^<<v24-8-8,8>>^ ‘How can you say: “We are wise, and we have the law^&#42;1^ of Jehovah”?
For in fact, the lying^&#42;2^ stylus^&#42;3^ of the scribes^&#42;4^ has been used only for falsehood.

[NOTE]
====
. Or “instruction.”
. Or “false.”
. Or “pen.”
. Or “secretaries.”
====

[[v24-8-9]]

^<<v24-8-9,9>>^ The wise have been put to shame.
They have become terrified and will be caught.
Look! They have rejected the word of Jehovah,
And what wisdom do they have?

[[v24-8-10]]

^<<v24-8-10,10>>^ So I will give their wives to other men,
Their fields to other owners;
For from the least to the greatest, each one is making dishonest gain;
From the prophet to the priest, each one is practicing fraud.

[[v24-8-11]]

^<<v24-8-11,11>>^ And they try to heal the breakdown^&#42;1^ of the daughter of my people lightly,^&#42;2^ saying,
“There is peace! There is peace!”
When there is no peace.

[NOTE]
====
. Or “fracture.”
. Or “superficially.”
====

[[v24-8-12]]

^<<v24-8-12,12>>^ Do they feel ashamed of the detestable things they have done?
They feel no shame at all!
They do not even know how to feel humiliated!
So they will fall among the fallen.
When I bring punishment on them they will stumble,’ says Jehovah.

[[v24-8-13]]

^<<v24-8-13,13>>^ ‘When I gather them, I will bring them to their end,’ declares Jehovah.
‘There will be no grapes left on the vine, no figs on the fig tree, and the leaves will wither.
And what I gave to them will be lost to them.’”

[[v24-8-14]]

^<<v24-8-14,14>>^ “Why are we sitting here?
Let us gather together and enter the fortified cities and perish there.
For Jehovah our God will do away with us,
And he gives us poisoned water to drink,
Because we have sinned against Jehovah.

[[v24-8-15]]

^<<v24-8-15,15>>^ There was a hope for peace, but nothing good came,
For a time of healing, but there is terror!

[[v24-8-16]]

^<<v24-8-16,16>>^ From Dan is heard the snorting of his horses.
At the sound of the neighing of his stallions,
The whole land quakes.
They come in and devour the land and everything in it,
The city and its inhabitants.”

[[v24-8-17]]

^<<v24-8-17,17>>^ “For here I am sending in serpents among you,
Poisonous snakes that cannot be charmed,
And they will certainly bite you,” declares Jehovah.

[[v24-8-18]]

^<<v24-8-18,18>>^ My grief is incurable;
My heart is sick.

[[v24-8-19]]

^<<v24-8-19,19>>^ From a distant land there is a cry for help
From the daughter of my people:
“Is Jehovah not in Zion?
Or is her king not in her?”
“Why have they offended me with their graven images,
With their worthless foreign gods?”

[[v24-8-20]]

^<<v24-8-20,20>>^ “The harvest has passed, the summer has ended,
But we have not been saved!”

[[v24-8-21]]

^<<v24-8-21,21>>^ I am shattered over the breakdown of the daughter of my people;
I am dejected.
Horror has seized me.

[[v24-8-22]]

^<<v24-8-22,22>>^ Is there no balsam^&#42;1^ in Gilʹe·ad?
Or is there no healer^&#42;2^ there?
Why has the daughter of my people not been restored to health?

[NOTE]
====
. Or “soothing balm.”
. Or “physician.”
====

'''

xref:024-jeremiah/024-jeremiah-007.adoc#v24-7-0[&#60; Capítulo Anterior] | <<v24-8-0,Topo>> | xref:024-jeremiah/024-jeremiah-009.adoc#v24-9-0[Próximo Capítulo &#62;]