include::./index.adoc[]

[[v24-51-0]]
=== Jeremiah, 51
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-51-1]]

^<<v24-51-1,1>>^ This is what Jehovah says:
“Here I am raising up a destructive wind
Against Babylon and the inhabitants of Leb-kaʹmai.^&#42;1^

[NOTE]
====
. This appears to be a cryptographic name for Chaldea.
====

[[v24-51-2]]

^<<v24-51-2,2>>^ I will send winnowers to Babylon,
And they will winnow her and make her land empty;
They will come against her on all sides in the day of calamity.

[[v24-51-3]]

^<<v24-51-3,3>>^ Let the archer not bend^&#42;1^ his bow.
And let no one stand up in his coat of mail.
Show no compassion for her young men.
Devote all her army to destruction.

[NOTE]
====
. Lit., “tread.”
====

[[v24-51-4]]

^<<v24-51-4,4>>^ And they will fall slain in the land of the Chal·deʹans,
Pierced through in her streets.

[[v24-51-5]]

^<<v24-51-5,5>>^ For Israel and Judah are not widowed from their God, from Jehovah of armies.
But their land^&#42;1^ is full of guilt from the standpoint of the Holy One of Israel.

[NOTE]
====
. That is, the land of the Chaldeans.
====

[[v24-51-6]]

^<<v24-51-6,6>>^ Flee out of the midst of Babylon,
And escape for your life.^&#42;1^
Do not perish because of her error.
For it is the time for Jehovah’s vengeance.
He is paying her back for what she has done.

[NOTE]
====
. Or “soul.”
====

[[v24-51-7]]

^<<v24-51-7,7>>^ Babylon has been a golden cup in the hand of Jehovah;
She made all the earth drunk.
From her wine the nations have drunk;
That is why the nations have gone mad.

[[v24-51-8]]

^<<v24-51-8,8>>^ Suddenly Babylon has fallen and is broken.
Wail over her!
Get balsam for her pain; perhaps she may be healed.”

[[v24-51-9]]

^<<v24-51-9,9>>^ “We tried to heal Babylon, but she could not be healed.
Leave her and let us go, each to his own land.
For her judgment has reached to the heavens;
It is as high as the clouds.

[[v24-51-10]]

^<<v24-51-10,10>>^ Jehovah has brought about justice for us.
Come, let us recount in Zion the work of Jehovah our God.”

[[v24-51-11]]

^<<v24-51-11,11>>^ “Polish the arrows; take up the circular shields.^&#42;1^
Jehovah has stirred up the spirit of the kings of the Medes,
Because he intends to bring Babylon to ruin.
For this is the vengeance of Jehovah, the vengeance for his temple.

[NOTE]
====
. Or possibly, “fill the quivers.”
====

[[v24-51-12]]

^<<v24-51-12,12>>^ Lift up a signal^&#42;1^ against the walls of Babylon.
Strengthen the guard, post the watchmen.
Prepare those in ambush.
For Jehovah has devised the strategy,
And he will carry out what he has promised against the inhabitants of Babylon.”

[NOTE]
====
. Or “signal pole.”
====

[[v24-51-13]]

^<<v24-51-13,13>>^ “O woman who resides on many waters,
With abundant treasures,
Your end has come, the limit^&#42;1^ of your profit-making.

[NOTE]
====
. Lit., “measure.”
====

[[v24-51-14]]

^<<v24-51-14,14>>^ Jehovah of armies has sworn by himself,^&#42;1^
‘I will fill you with men, as numerous as locusts,
And they will shout in triumph over you.’

[NOTE]
====
. Or “his soul.”
====

[[v24-51-15]]

^<<v24-51-15,15>>^ He is the Maker of the earth by his power,
The One who established the productive land by his wisdom
And who stretched out the heavens by his understanding.

[[v24-51-16]]

^<<v24-51-16,16>>^ When he makes his voice heard,
The waters in the heavens are in turmoil,
And he causes clouds^&#42;1^ to ascend from the ends of the earth.
He makes lightning for^&#42;2^ the rain,
And he brings the wind out of his storehouses.

[NOTE]
====
. Or “vapors.”
. Or possibly, “makes sluices for.”
====

[[v24-51-17]]

^<<v24-51-17,17>>^ Every man acts unreasonably and without knowledge.
Every metalworker will be put to shame because of the carved image;
For his metal image^&#42;1^ is a falsehood,
And there is no spirit^&#42;2^ in them.

[NOTE]
====
. Or “molten statue.”
. Or “breath.”
====

[[v24-51-18]]

^<<v24-51-18,18>>^ They are a delusion,^&#42;1^ a work of mockery.
When their day of reckoning comes, they will perish.

[NOTE]
====
. Or “futility.”
====

[[v24-51-19]]

^<<v24-51-19,19>>^ The Share of Jacob is not like these things,
For he is the One who formed everything,
Even the staff of his inheritance.
Jehovah of armies is his name.”

[[v24-51-20]]

^<<v24-51-20,20>>^ “You are a war club for me, a weapon for battle,
For with you I will smash nations.
With you I will bring kingdoms to ruin.

[[v24-51-21]]

^<<v24-51-21,21>>^ With you I will smash the horse and its rider.
With you I will smash the war chariot and its rider.

[[v24-51-22]]

^<<v24-51-22,22>>^ With you I will smash man and woman.
With you I will smash old man and boy.
With you I will smash young man and woman.

[[v24-51-23]]

^<<v24-51-23,23>>^ With you I will smash shepherd and his flock.
With you I will smash farmer and his team of animals.
With you I will smash governors and deputy rulers.

[[v24-51-24]]

^<<v24-51-24,24>>^ And I will repay Babylon and all the inhabitants of Chal·deʹa
For all the evil that they have committed in Zion before your eyes,” declares Jehovah.

[[v24-51-25]]

^<<v24-51-25,25>>^ “Here I am against you, O destructive mountain,” declares Jehovah,
“You destroyer of the whole earth.
I will stretch out my hand against you and roll you down from the crags
And make you a burned-out mountain.”

[[v24-51-26]]

^<<v24-51-26,26>>^ “People will not take from you a cornerstone or a foundation stone,
Because you will become desolate forever,” declares Jehovah.

[[v24-51-27]]

^<<v24-51-27,27>>^ “Lift up a signal^&#42;1^ in the land.
Blow a horn among the nations.
Appoint^&#42;2^ the nations against her.
Summon against her the kingdoms of Arʹa·rat, Minʹni, and Ashʹke·naz.
Commission against her a recruiting officer.
Make the horses come up like bristling locusts.

[NOTE]
====
. Or “signal pole.”
. Lit., “Sanctify.”
====

[[v24-51-28]]

^<<v24-51-28,28>>^ Appoint^&#42;1^ against her the nations,
The kings of Meʹdi·a, its governors and all its deputy rulers
And all the lands they rule over.

[NOTE]
====
. Lit., “Sanctify.”
====

[[v24-51-29]]

^<<v24-51-29,29>>^ And the earth will quake and tremble,
For the thoughts of Jehovah against Babylon will be carried out
To make the land of Babylon an object of horror, without an inhabitant.

[[v24-51-30]]

^<<v24-51-30,30>>^ The warriors of Babylon have quit fighting.
They sit in their strongholds.
Their strength has failed.
They have become like women.
Her homes have been set on fire.
Her bars have been broken.

[[v24-51-31]]

^<<v24-51-31,31>>^ One courier runs to meet another courier,
And one messenger to meet another messenger,
To report to the king of Babylon that his city has been captured on every side,

[[v24-51-32]]

^<<v24-51-32,32>>^ That the fords have been seized,
That the papyrus boats have been burned with fire,
And that the soldiers are terrified.”

[[v24-51-33]]

^<<v24-51-33,33>>^ For this is what Jehovah of armies, the God of Israel, says:
“The daughter of Babylon is like a threshing floor.
It is the time to tread her down solid.
Very soon the time of the harvest will come for her.”

[[v24-51-34]]

^<<v24-51-34,34>>^ “King Neb·u·chad·nezʹzar^&#42;1^ of Babylon has devoured me;
He has thrown me into confusion.
He has set me down as an empty vessel.
He has swallowed me down like a big snake;
He has filled his stomach with my fine things.
He has rinsed me away.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
====

[[v24-51-35]]

^<<v24-51-35,35>>^ ‘May the violence done to me and to my person come upon Babylon!’ says the inhabitant of Zion.
‘And let my blood come upon the inhabitants of Chal·deʹa!’ says Jerusalem.”

[[v24-51-36]]

^<<v24-51-36,36>>^ Therefore this is what Jehovah says:
“Here I am pleading your legal case,
And I will execute vengeance for you.
I will dry up her sea and make her wells dry.

[[v24-51-37]]

^<<v24-51-37,37>>^ And Babylon will become piles of stones,
A lair of jackals,
An object of horror and something to whistle at,
Without an inhabitant.

[[v24-51-38]]

^<<v24-51-38,38>>^ All together they will roar just like young lions.^&#42;1^
They will growl like lion cubs.”

[NOTE]
====
. Or “maned young lions.”
====

[[v24-51-39]]

^<<v24-51-39,39>>^ “When they are inflamed, I will set out their banquet and make them drunk,
In order that they may exult;
Then they will sleep a lasting sleep,
From which they will not wake up,” declares Jehovah.

[[v24-51-40]]

^<<v24-51-40,40>>^ “I will bring them down like lambs to the slaughter,
Like rams along with the goats.”

[[v24-51-41]]

^<<v24-51-41,41>>^ “O how Sheʹshach^&#42;1^ has been captured,
How the Praise of the whole earth has been seized!
How Babylon has become an object of horror among the nations!

[NOTE]
====
. This appears to be a cryptographic name for Babel (Babylon).
====

[[v24-51-42]]

^<<v24-51-42,42>>^ The sea has come up over Babylon.
By the multitude of its waves she has been covered.

[[v24-51-43]]

^<<v24-51-43,43>>^ Her cities have become an object of horror, a waterless land and a desert.
A land where no one will live and where no man will pass through.

[[v24-51-44]]

^<<v24-51-44,44>>^ I will turn my attention to Bel in Babylon,
And I will take out of his mouth what he has swallowed.
To him nations will stream no more,
And the wall of Babylon will fall.

[[v24-51-45]]

^<<v24-51-45,45>>^ Get out of her midst, my people!
Escape for your lives^&#42;1^ from the burning anger of Jehovah!

[NOTE]
====
. Or “souls.”
====

[[v24-51-46]]

^<<v24-51-46,46>>^ Do not be fainthearted or afraid about the report to be heard in the land.
In one year the report will come,
And the next year another report,
Of violence in the land and of ruler against ruler.

[[v24-51-47]]

^<<v24-51-47,47>>^ Therefore look! the days are coming
When I will turn my attention to the graven images of Babylon.
All her land will be put to shame,
And all her slain will fall in her midst.

[[v24-51-48]]

^<<v24-51-48,48>>^ The heavens and the earth and everything in them
Will shout joyfully over Babylon,
For the destroyers will come to her out of the north,” declares Jehovah.

[[v24-51-49]]

^<<v24-51-49,49>>^ “Not only did Babylon cause the slain of Israel to fall
But also at Babylon the slain ones of all the earth have fallen.

[[v24-51-50]]

^<<v24-51-50,50>>^ You who escape the sword, keep going, do not stand still!
Remember Jehovah from far away,
And may Jerusalem come up into your heart.”

[[v24-51-51]]

^<<v24-51-51,51>>^ “We have been put to shame, for we have heard taunts.
Humiliation has covered our faces,
For foreigners^&#42;1^ have come against the holy places of the house of Jehovah.”

[NOTE]
====
. Or “strangers.”
====

[[v24-51-52]]

^<<v24-51-52,52>>^ “Therefore look! the days are coming,” declares Jehovah,
“When I will turn my attention to her graven images,
And throughout all her land the wounded will groan.”

[[v24-51-53]]

^<<v24-51-53,53>>^ “Even if Babylon should ascend to the heavens,
Even if she should fortify her towering strongholds,
From me her destroyers will come,” declares Jehovah.

[[v24-51-54]]

^<<v24-51-54,54>>^ “Listen! There is an outcry from Babylon,
The sound of great disaster from the land of the Chal·deʹans,

[[v24-51-55]]

^<<v24-51-55,55>>^ For Jehovah is destroying Babylon,
He will silence her great voice,
And their waves will roar like many waters.
The sound of their voice will be heard.

[[v24-51-56]]

^<<v24-51-56,56>>^ For the destroyer will come upon Babylon;
Her warriors will be captured,
Their bows will be shattered,
For Jehovah is a God of retribution.
He will surely repay.

[[v24-51-57]]

^<<v24-51-57,57>>^ I will make her princes and her wise men drunk,
Her governors and her deputy rulers and her warriors,
And they will sleep a lasting sleep,
From which they will not wake up,” declares the King, whose name is Jehovah of armies.

[[v24-51-58]]

^<<v24-51-58,58>>^ This is what Jehovah of armies says:
“The wall of Babylon, though broad, will be completely demolished,
And her gates, though high, will be set on fire.
The peoples will toil for nothing;
The nations will weary themselves just to feed the fire.”

[[v24-51-59]]

^<<v24-51-59,59>>^ This is the word that Jeremiah the prophet gave as a command to Se·raiʹah son of Ne·riʹah son of Mah·seiʹah when he went with King Zed·e·kiʹah of Judah to Babylon in the fourth year of his reign; Se·raiʹah was the quartermaster.

[[v24-51-60]]

^<<v24-51-60,60>>^ Jeremiah wrote in one book all the calamity that would come upon Babylon, all these words written against Babylon.

[[v24-51-61]]

^<<v24-51-61,61>>^ Furthermore, Jeremiah said to Se·raiʹah: “When you come to Babylon and see her, you must read aloud all these words.

[[v24-51-62]]

^<<v24-51-62,62>>^ Then say, ‘O Jehovah, you have said against this place that it will be destroyed and left without an inhabitant, man or beast, and that she will become desolate forever.’

[[v24-51-63]]

^<<v24-51-63,63>>^ And when you finish reading this book, tie a stone to it and throw it into the middle of the Eu·phraʹtes.

[[v24-51-64]]

^<<v24-51-64,64>>^ Then say, ‘This is how Babylon will sink down and never rise again because of the calamity that I am bringing on her; and they will grow weary.’”
Down to this point are the words of Jeremiah.

'''

xref:024-jeremiah/024-jeremiah-050.adoc#v24-50-0[&#60; Capítulo Anterior] | <<v24-51-0,Topo>> | xref:024-jeremiah/024-jeremiah-052.adoc#v24-52-0[Próximo Capítulo &#62;]