include::./index.adoc[]

[[v24-23-0]]
=== Jeremiah, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-23-1]]

^<<v24-23-1,1>>^ “Woe to the shepherds who are destroying and scattering the sheep of my pasture!” declares Jehovah.

[[v24-23-2]]

^<<v24-23-2,2>>^ Therefore this is what Jehovah the God of Israel says against the shepherds who are shepherding my people: “You have scattered my sheep; you kept dispersing them, and you have not turned your attention to them.”
“So I will turn my attention to you because of your evil deeds,” declares Jehovah.

[[v24-23-3]]

^<<v24-23-3,3>>^ “Then I will gather together the remnant of my sheep from all the lands to which I have dispersed them, and I will bring them back to their pasture, and they will be fruitful and become many.

[[v24-23-4]]

^<<v24-23-4,4>>^ And I will raise up over them shepherds who will really shepherd them. They will no longer be afraid or be terrified, and none will be missing,” declares Jehovah.

[[v24-23-5]]

^<<v24-23-5,5>>^ “Look! The days are coming,” declares Jehovah, “when I will raise up to David a righteous sprout.^&#42;1^ And a king will reign and show insight and uphold justice and righteousness in the land.

[NOTE]
====
. Or “heir.”
====

[[v24-23-6]]

^<<v24-23-6,6>>^ In his days Judah will be saved, and Israel will reside in security. And this is the name by which he will be called: Jehovah Is Our Righteousness.”

[[v24-23-7]]

^<<v24-23-7,7>>^ “However, the days are coming,” declares Jehovah, “when they will no longer say, ‘As surely as Jehovah is alive, who brought the people of Israel out of the land of Egypt!’

[[v24-23-8]]

^<<v24-23-8,8>>^ but rather, ‘As surely as Jehovah is alive, who brought out and brought back the descendants of the house of Israel from the land of the north and from all the lands to which I had dispersed them,’ and they will dwell in their own land.”

[[v24-23-9]]

^<<v24-23-9,9>>^ Concerning the prophets:
My heart is broken within me.
All my bones are shaking.
I am like a man who is drunk
And like a man overcome by wine,
Because of Jehovah and because of his holy words.

[[v24-23-10]]

^<<v24-23-10,10>>^ For the land is full of adulterers;
Because of the curse the land has gone into mourning
And the pastures of the wilderness have dried up.
Their course is evil, and they abuse their power.

[[v24-23-11]]

^<<v24-23-11,11>>^ “Both the prophet and the priest are polluted.^&#42;1^
Even in my own house I have found their wickedness,” declares Jehovah.

[NOTE]
====
. Or “apostate.”
====

[[v24-23-12]]

^<<v24-23-12,12>>^ “So their path will become slippery and dark;
They will be pushed and will fall.
For I will bring calamity on them
In the year of reckoning,” declares Jehovah.

[[v24-23-13]]

^<<v24-23-13,13>>^ “And in the prophets of Sa·marʹi·a I have seen what is repulsive.
Their prophecies are incited by Baʹal,
And they lead my people Israel astray.

[[v24-23-14]]

^<<v24-23-14,14>>^ And in the prophets of Jerusalem I have seen horrible things.
They commit adultery and walk in falsehood;
They encourage^&#42;1^ evildoers,
And they do not turn away from their wickedness.
To me they are all like Sodʹom,
And her inhabitants are like Go·morʹrah.”

[NOTE]
====
. Lit., “strengthen the hands of.”
====

[[v24-23-15]]

^<<v24-23-15,15>>^ Therefore this is what Jehovah of armies says against the prophets:
“Here I am making them eat wormwood
And giving them poisoned water to drink.
For from the prophets of Jerusalem apostasy has spread throughout the land.”

[[v24-23-16]]

^<<v24-23-16,16>>^ This is what Jehovah of armies says:
“Do not listen to the words of the prophets who are prophesying to you.
They are deluding you.^&#42;1^
The vision they speak is from their own heart,
Not from the mouth of Jehovah.

[NOTE]
====
. Or “They are filling you with empty hopes.”
====

[[v24-23-17]]

^<<v24-23-17,17>>^ They are saying again and again to those who disrespect me,
‘Jehovah has said: “You will enjoy peace.”’
And to everyone who follows his own stubborn heart they say,
‘No calamity will come upon you.’

[[v24-23-18]]

^<<v24-23-18,18>>^ For who has stood in the inner circle of Jehovah
To see and hear his word?
Who has paid attention to his word in order to hear it?

[[v24-23-19]]

^<<v24-23-19,19>>^ Look! The windstorm of Jehovah will burst out in fury;
Like a whirling tempest it will whirl down on the head of the wicked.

[[v24-23-20]]

^<<v24-23-20,20>>^ The anger of Jehovah will not turn back
Until he has carried out and accomplished the intentions of his heart.
In the final part of the days you will clearly understand this.

[[v24-23-21]]

^<<v24-23-21,21>>^ I did not send the prophets, yet they ran.
I did not speak to them, yet they prophesied.

[[v24-23-22]]

^<<v24-23-22,22>>^ But if they had stood in my inner circle,
They would have made my people hear my words
And would have caused them to turn back from their bad way and their evil deeds.”

[[v24-23-23]]

^<<v24-23-23,23>>^ “Am I only a God nearby,” declares Jehovah, “and not a God also from far away?”

[[v24-23-24]]

^<<v24-23-24,24>>^ “Can any man hide in a concealed place where I cannot see him?” declares Jehovah.
“Do I not fill the heavens and the earth?” declares Jehovah.

[[v24-23-25]]

^<<v24-23-25,25>>^ “I have heard the prophets who are prophesying lies in my name say, ‘I had a dream! I had a dream!’

[[v24-23-26]]

^<<v24-23-26,26>>^ How long will this continue in the heart of the prophets, to prophesy lies? They are prophets of the deceit of their own heart.

[[v24-23-27]]

^<<v24-23-27,27>>^ They intend to make my people forget my name by the dreams they relate to one another, just as their fathers forgot my name because of Baʹal.

[[v24-23-28]]

^<<v24-23-28,28>>^ Let the prophet who has a dream relate the dream, but the one who has my word should speak my word truthfully.”
“What does the straw have in common with the grain?” declares Jehovah.

[[v24-23-29]]

^<<v24-23-29,29>>^ “Is not my word just like a fire,” declares Jehovah, “and like a forge hammer that smashes the crag?”

[[v24-23-30]]

^<<v24-23-30,30>>^ “So here I am against the prophets,” declares Jehovah, “who steal my words from one another.”

[[v24-23-31]]

^<<v24-23-31,31>>^ “Here I am against the prophets,” declares Jehovah, “those who use their tongue to say, ‘He declares!’”

[[v24-23-32]]

^<<v24-23-32,32>>^ “Here I am against the prophets of lying dreams,” declares Jehovah, “who relate them and lead my people astray because of their lies and their boasting.”
“But I did not send them or command them. So they will not benefit this people at all,” declares Jehovah.

[[v24-23-33]]

^<<v24-23-33,33>>^ “And when this people or a prophet or a priest asks you, ‘What is the burden^&#42;1^ of Jehovah?’ you should reply to them, ‘“You people are the burden! And I will cast you off,” declares Jehovah.’

[NOTE]
====
. Or “burdensome message.” The Hebrew word has a double meaning: “a weighty divine pronouncement” or “something burdensome.”
====

[[v24-23-34]]

^<<v24-23-34,34>>^ As for the prophet or the priest or the people who say, ‘This is the burden^&#42;1^ of Jehovah!’ I will turn my attention on that man and on his household.

[NOTE]
====
. Or “burdensome message.”
====

[[v24-23-35]]

^<<v24-23-35,35>>^ This is what each of you is saying to his fellow and to his brother, ‘What has Jehovah answered? And what has Jehovah spoken?’

[[v24-23-36]]

^<<v24-23-36,36>>^ But the burden^&#42;1^ of Jehovah you should mention no more, for the burden^&#42;2^ is each one’s own word, and you have changed the words of the living God, Jehovah of armies, our God.

[NOTE]
====
. Or “burdensome message.”
. Or “burdensome message.”
====

[[v24-23-37]]

^<<v24-23-37,37>>^ “This is what you will say to the prophet, ‘What answer has Jehovah given you? And what has Jehovah spoken?

[[v24-23-38]]

^<<v24-23-38,38>>^ And if you keep saying, “The burden^&#42;1^ of Jehovah!” this is what Jehovah says: “Because of your saying, ‘This word is the burden^&#42;2^ of Jehovah,’ after I told you, ‘You must not say: “The burden^&#42;3^ of Jehovah!”’

[NOTE]
====
. Or “burdensome message.”
. Or “burdensome message.”
. Or “burdensome message.”
====

[[v24-23-39]]

^<<v24-23-39,39>>^ look! I will lift you up and throw you away from my presence, both you and the city that I gave to you and your forefathers.

[[v24-23-40]]

^<<v24-23-40,40>>^ And I will bring on you everlasting disgrace and everlasting humiliation, which will not be forgotten.”’”

'''

xref:024-jeremiah/024-jeremiah-022.adoc#v24-22-0[&#60; Capítulo Anterior] | <<v24-23-0,Topo>> | xref:024-jeremiah/024-jeremiah-024.adoc#v24-24-0[Próximo Capítulo &#62;]