include::./index.adoc[]

[[v24-19-0]]
=== Jeremiah, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-19-1]]

^<<v24-19-1,1>>^ This is what Jehovah said: “Go and buy an earthenware flask from a potter. Take some of the elders of the people and some of the elders of the priests,

[[v24-19-2]]

^<<v24-19-2,2>>^ and go out to the Valley of the Son of Hinʹnom, at the entrance of the Gate of the Potsherds. And there proclaim the words that I speak to you.

[[v24-19-3]]

^<<v24-19-3,3>>^ You will say, ‘Hear the word of Jehovah, you kings of Judah and inhabitants of Jerusalem. This is what Jehovah of armies, the God of Israel, says:
“‘“I am about to bring a calamity on this place, and the ears of anyone who hears about it will tingle.

[[v24-19-4]]

^<<v24-19-4,4>>^ It is because they abandoned me and made this place unrecognizable. In it they are sacrificing to other gods, whom they and their forefathers and the kings of Judah had not known, and they have filled this place with the blood of the innocent ones.

[[v24-19-5]]

^<<v24-19-5,5>>^ They built the high places of Baʹal in order to burn their sons in the fire as whole burnt offerings to Baʹal, something that I had not commanded or spoken of and that had never even come into my heart.”’^&#42;1^

[NOTE]
====
. Or “had never entered my thoughts.”
====

[[v24-19-6]]

^<<v24-19-6,6>>^ “‘“Therefore look! the days are coming,” declares Jehovah, “when this place will no longer be called Toʹpheth or the Valley of the Son of Hinʹnom but the Valley of the Slaughter.

[[v24-19-7]]

^<<v24-19-7,7>>^ I will thwart the plans of Judah and Jerusalem in this place, and I will make them fall by the sword before their enemies and by the hand of those seeking to take their life.^&#42;1^ And I will give their dead bodies as food to the birds of the heavens and to the beasts of the earth.

[NOTE]
====
. Or “seeking their soul.”
====

[[v24-19-8]]

^<<v24-19-8,8>>^ And I will make this city an object of horror and something to whistle at. Every last one passing by it will stare in horror and whistle over all its plagues.

[[v24-19-9]]

^<<v24-19-9,9>>^ And I will make them eat the flesh of their sons and daughters, and they will each eat the flesh of his fellow man, because of the siege and their desperation when they are hemmed in by their enemies and those seeking to take their life.”’^&#42;1^

[NOTE]
====
. Or “seeking their soul.”
====

[[v24-19-10]]

^<<v24-19-10,10>>^ “Then break the flask before the eyes of the men who go with you,

[[v24-19-11]]

^<<v24-19-11,11>>^ and say to them, ‘This is what Jehovah of armies says: “This is how I will break this people and this city, like someone who breaks a potter’s vessel so that it can never be repaired; and they will bury the dead in Toʹpheth until there is no more room to bury them.”’

[[v24-19-12]]

^<<v24-19-12,12>>^ “‘That is what I will do to this place,’ declares Jehovah, ‘and to its inhabitants, to make this city like Toʹpheth.

[[v24-19-13]]

^<<v24-19-13,13>>^ And the houses of Jerusalem and the houses of the kings of Judah will become unclean like this place, Toʹpheth, yes, all the houses on whose roofs they offered sacrifices to all the army of the heavens and where they poured out drink offerings to other gods.’”

[[v24-19-14]]

^<<v24-19-14,14>>^ When Jeremiah returned from Toʹpheth where Jehovah sent him to prophesy, he stood in the courtyard of the house of Jehovah and said to all the people:

[[v24-19-15]]

^<<v24-19-15,15>>^ “This is what Jehovah of armies, the God of Israel, says, ‘Here I am bringing on this city and on all its towns all the calamity that I have spoken against it, because they stubbornly refused^&#42;1^ to obey my words.’”

[NOTE]
====
. Lit., “hardened their neck so as not.”
====

'''

xref:024-jeremiah/024-jeremiah-018.adoc#v24-18-0[&#60; Capítulo Anterior] | <<v24-19-0,Topo>> | xref:024-jeremiah/024-jeremiah-020.adoc#v24-20-0[Próximo Capítulo &#62;]