include::./index.adoc[]

[[v24-24-0]]
=== Jeremiah, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-24-1]]

^<<v24-24-1,1>>^ Then Jehovah showed me two baskets of figs set before the temple of Jehovah, after King Neb·u·chad·nezʹzar^&#42;1^ of Babylon had carried into exile Jec·o·niʹah^&#42;2^ son of Je·hoiʹa·kim, the king of Judah, along with the princes of Judah, the craftsmen, and the metalworkers;^&#42;3^ he took them from Jerusalem to Babylon.

[NOTE]
====
. Lit., “Nebuchadrezzar,” a variant spelling.
. Also called Jehoiachin and Coniah.
. Or possibly, “builders of bulwarks.”
====

[[v24-24-2]]

^<<v24-24-2,2>>^ One basket had very good figs, like early figs, but the other basket had very bad figs, so bad that they could not be eaten.

[[v24-24-3]]

^<<v24-24-3,3>>^ Jehovah then asked me: “What do you see, Jeremiah?” So I said: “Figs; the good figs are very good, but the bad ones are very bad, so bad that they cannot be eaten.”

[[v24-24-4]]

^<<v24-24-4,4>>^ Then the word of Jehovah came to me, saying:

[[v24-24-5]]

^<<v24-24-5,5>>^ “This is what Jehovah the God of Israel says, ‘Like these good figs, so I will regard in a good way the exiles of Judah, whom I have sent away from this place to the land of the Chal·deʹans.

[[v24-24-6]]

^<<v24-24-6,6>>^ I will keep my eye on them for their good, and I will cause them to return to this land. I will build them up, and I will not tear down; I will plant them, and I will not uproot.

[[v24-24-7]]

^<<v24-24-7,7>>^ And I will give them a heart to know me, that I am Jehovah. They will become my people, and I will become their God, for they will return to me with all their heart.

[[v24-24-8]]

^<<v24-24-8,8>>^ “‘But concerning the bad figs that are so bad they cannot be eaten, this is what Jehovah says: “So I will regard King Zed·e·kiʹah of Judah, his princes, the remnant of Jerusalem who are left in this land, and those who are dwelling in the land of Egypt.

[[v24-24-9]]

^<<v24-24-9,9>>^ I will make them an object of horror and calamity to all the kingdoms of the earth, a reproach, a proverbial saying, a cause for ridicule, and a curse in all the places to which I disperse them.

[[v24-24-10]]

^<<v24-24-10,10>>^ And I will send against them the sword, the famine, and the pestilence,^&#42;1^ until they have perished from the land that I gave to them and to their forefathers.”’”

[NOTE]
====
. Or “disease.”
====

'''

xref:024-jeremiah/024-jeremiah-023.adoc#v24-23-0[&#60; Capítulo Anterior] | <<v24-24-0,Topo>> | xref:024-jeremiah/024-jeremiah-025.adoc#v24-25-0[Próximo Capítulo &#62;]