include::./index.adoc[]

[[v24-10-0]]
=== Jeremiah, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-10-1]]

^<<v24-10-1,1>>^ Hear the word that Jehovah has spoken against you, O house of Israel.

[[v24-10-2]]

^<<v24-10-2,2>>^ This is what Jehovah says:
“Do not learn the way of the nations,
And do not be terrified by the signs of the heavens
Because the nations are terrified by them.

[[v24-10-3]]

^<<v24-10-3,3>>^ For the customs of the peoples are a delusion.^&#42;1^
It is just a tree of the forest that is cut down,
Worked by the hands of the craftsman with his tool.^&#42;2^

[NOTE]
====
. Or “futility.”
. Or “billhook.”
====

[[v24-10-4]]

^<<v24-10-4,4>>^ They adorn it with silver and gold
And fasten it with hammer and nails so that it will not fall over.

[[v24-10-5]]

^<<v24-10-5,5>>^ Like a scarecrow in a cucumber field, they cannot speak;
They have to be carried, for they cannot walk.
Do not fear them, for they can do no harm,
Nor can they do any good.”

[[v24-10-6]]

^<<v24-10-6,6>>^ No one is like you, O Jehovah.
You are great, and your name is great and mighty.

[[v24-10-7]]

^<<v24-10-7,7>>^ Who should not fear you, O King of the nations, for it is fitting;
Because among all the wise ones of the nations and among all their kingdoms,
There is no one at all like you.

[[v24-10-8]]

^<<v24-10-8,8>>^ They are all unreasoning and stupid.
Instruction from a tree is an utter delusion.^&#42;1^

[NOTE]
====
. Or “futility.”
====

[[v24-10-9]]

^<<v24-10-9,9>>^ Silver plates are imported from Tarʹshish and gold from Uʹphaz,
The work of a craftsman, of the hands of a metalworker.
Their clothing is blue thread and purple wool.
They are all made by skilled workers.

[[v24-10-10]]

^<<v24-10-10,10>>^ But Jehovah is truly God.
He is the living God and the eternal King.
Because of his indignation the earth will quake,
And no nations will endure his denunciation.

[[v24-10-11]]

^<<v24-10-11,11>>^ ^&#42;1^ This is what you should say to them:
“The gods that did not make the heavens and the earth
Will perish from the earth and from under these heavens.”

[NOTE]
====
. Vs. 11 was originally written in Aramaic.
====

[[v24-10-12]]

^<<v24-10-12,12>>^ He is the Maker of the earth by his power,
The One who established the productive land by his wisdom
And who stretched out the heavens by his understanding.

[[v24-10-13]]

^<<v24-10-13,13>>^ When he makes his voice heard,
The waters in the heavens are in turmoil,
And he causes clouds^&#42;1^ to ascend from the ends of the earth.
He makes lightning for^&#42;2^ the rain,
And he brings the wind out of his storehouses.

[NOTE]
====
. Or “vapors.”
. Or possibly, “makes sluices for.”
====

[[v24-10-14]]

^<<v24-10-14,14>>^ Every man acts unreasonably and without knowledge.
Every metalworker will be put to shame because of the carved image;
For his metal image^&#42;1^ is a falsehood,
And there is no spirit^&#42;2^ in them.

[NOTE]
====
. Or “molten statue.”
. Or “breath.”
====

[[v24-10-15]]

^<<v24-10-15,15>>^ They are a delusion,^&#42;1^ a work of mockery.
When their day of reckoning comes, they will perish.

[NOTE]
====
. Or “futility.”
====

[[v24-10-16]]

^<<v24-10-16,16>>^ The Share of Jacob is not like these things,
For he is the One who formed everything,
And Israel is the staff of his inheritance.
Jehovah of armies is his name.

[[v24-10-17]]

^<<v24-10-17,17>>^ Gather up your bundle from the ground,
O woman dwelling under siege.

[[v24-10-18]]

^<<v24-10-18,18>>^ For this is what Jehovah says:
“Here I am hurling^&#42;1^ the inhabitants out of the land at this time,
And I will cause them to experience distress.”

[NOTE]
====
. Or “slinging.”
====

[[v24-10-19]]

^<<v24-10-19,19>>^ Woe to me because of my breakdown!^&#42;1^
My wound is incurable.
And I said: “Surely this is my sickness, and I must bear it.

[NOTE]
====
. Or “fracture!”
====

[[v24-10-20]]

^<<v24-10-20,20>>^ My tent has been devastated, and my tent cords have all been torn apart.
My sons have left me and are no more.
There is no one left to stretch out my tent or raise up my tent cloths.

[[v24-10-21]]

^<<v24-10-21,21>>^ For the shepherds have behaved senselessly,
And they have not inquired of Jehovah.
That is why they have not acted with insight,
And all their flocks have been scattered.”

[[v24-10-22]]

^<<v24-10-22,22>>^ Listen! A report! It is coming!
A great pounding from the land of the north,
To make the cities of Judah desolate, a lair of jackals.

[[v24-10-23]]

^<<v24-10-23,23>>^ I well know, O Jehovah, that man’s way does not belong to him.
It does not belong to man who is walking even to direct his step.

[[v24-10-24]]

^<<v24-10-24,24>>^ Correct me, O Jehovah, with judgment,
But not in your anger, that you may not reduce me to nothing.

[[v24-10-25]]

^<<v24-10-25,25>>^ Pour out your wrath on the nations who ignore you
And on the families who do not call on your name.
For they have devoured Jacob,
Yes, they have devoured him to the point of extermination,
And they have desolated his homeland.

'''

xref:024-jeremiah/024-jeremiah-009.adoc#v24-9-0[&#60; Capítulo Anterior] | <<v24-10-0,Topo>> | xref:024-jeremiah/024-jeremiah-011.adoc#v24-11-0[Próximo Capítulo &#62;]