include::./index.adoc[]

[[v24-6-0]]
=== Jeremiah, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-6-1]]

^<<v24-6-1,1>>^ Take shelter, O sons of Benjamin, away from Jerusalem.
Blow the horn in Te·koʹa;
Light a fire signal over Beth-hac·cheʹrem!
For a calamity looms from the north, a great disaster.

[[v24-6-2]]

^<<v24-6-2,2>>^ The daughter of Zion resembles a beautiful and delicate woman.

[[v24-6-3]]

^<<v24-6-3,3>>^ The shepherds and their droves will come.
They will pitch their tents all around her,
Each grazing the flock in his care.

[[v24-6-4]]

^<<v24-6-4,4>>^ “Prepare for^&#42;1^ war against her!
Rise up, and let us attack her at midday!”
“Woe to us, for the day is declining,
For the shadows of evening are getting longer!”

[NOTE]
====
. Lit., “Sanctify.”
====

[[v24-6-5]]

^<<v24-6-5,5>>^ “Rise up, and let us attack during the night
And destroy her fortified towers.”

[[v24-6-6]]

^<<v24-6-6,6>>^ For this is what Jehovah of armies says:
“Cut down wood and raise up a siege rampart against Jerusalem.
She is the city that must be held to account;
There is nothing but oppression within her.

[[v24-6-7]]

^<<v24-6-7,7>>^ As a cistern keeps its water cool,^&#42;1^
So she keeps her wickedness cool.^&#42;2^
Violence and destruction are heard in her;
Sickness and plague are constantly before me.

[NOTE]
====
. Or “fresh.”
. Or “fresh.”
====

[[v24-6-8]]

^<<v24-6-8,8>>^ Be warned, O Jerusalem, or I^&#42;1^ will turn away from you in disgust;
I will make you desolate, a land without inhabitants.”

[NOTE]
====
. Or “my soul.”
====

[[v24-6-9]]

^<<v24-6-9,9>>^ This is what Jehovah of armies says:
“They will thoroughly glean the remnant of Israel as the last grapes on a vine.
Pass your hand again like one gathering grapes from the vines.”

[[v24-6-10]]

^<<v24-6-10,10>>^ “To whom should I speak and give warning?
Who will listen?
Look! Their ears are closed,^&#42;1^ so that they are unable to pay attention.
Look! The word of Jehovah has become something they scorn;
They find no pleasure in it.

[NOTE]
====
. Lit., “Their ear is uncircumcised.”
====

[[v24-6-11]]

^<<v24-6-11,11>>^ So I am filled with the wrath of Jehovah,
And I am tired of holding it in.”
“Pour it out on the child in the street,
On the groups of young men gathered together.
They will all be captured, a man along with his wife,
The old men along with the very old.^&#42;1^

[NOTE]
====
. Lit., “those full of days.”
====

[[v24-6-12]]

^<<v24-6-12,12>>^ Their houses will be turned over to others,
Together with their fields and their wives.
For I will stretch my hand out against the inhabitants of the land,” declares Jehovah.

[[v24-6-13]]

^<<v24-6-13,13>>^ “For from the least to the greatest, each one is making dishonest gain;
From the prophet to the priest, each one is practicing fraud.

[[v24-6-14]]

^<<v24-6-14,14>>^ And they try to heal the breakdown^&#42;1^ of my people lightly,^&#42;2^ saying,
‘There is peace! There is peace!’
When there is no peace.

[NOTE]
====
. Or “fracture.”
. Or “superficially.”
====

[[v24-6-15]]

^<<v24-6-15,15>>^ Do they feel ashamed of the detestable things they have done?
They feel no shame at all!
They do not even know how to feel humiliated!
So they will fall among the fallen.
When I bring punishment on them they will stumble,” says Jehovah.

[[v24-6-16]]

^<<v24-6-16,16>>^ This is what Jehovah says:
“Stand at the crossroads and see.
Ask about the ancient roadways,
Ask where the good way is, and walk in it,
And find rest for yourselves.”^&#42;1^
But they say: “We will not walk in it.”

[NOTE]
====
. Or “your souls.”
====

[[v24-6-17]]

^<<v24-6-17,17>>^ “And I appointed watchmen who said,
‘Pay attention to the sound of the horn!’”
But they said: “We will not pay attention.”

[[v24-6-18]]

^<<v24-6-18,18>>^ “Therefore hear, O nations!
And know, O assembly,
What will happen to them.

[[v24-6-19]]

^<<v24-6-19,19>>^ Listen, O earth!
I am bringing calamity on this people
As the fruitage of their own schemes,
For they paid no attention to my words
And they rejected my law.”^&#42;1^

[NOTE]
====
. Or “instruction.”
====

[[v24-6-20]]

^<<v24-6-20,20>>^ “What do I care that you bring frankincense from Sheʹba
And sweet cane^&#42;1^ from a distant land?
Your whole burnt offerings are not acceptable,
And your sacrifices do not please me.”

[NOTE]
====
. An aromatic reed.
====

[[v24-6-21]]

^<<v24-6-21,21>>^ Therefore this is what Jehovah says:
“Here I am setting for this people stumbling blocks,
And they will stumble over them,
Fathers and sons together,
A neighbor and his companion,
And they will all perish.”

[[v24-6-22]]

^<<v24-6-22,22>>^ This is what Jehovah says:
“Look! A people is coming from the land of the north,
And a great nation will be awakened from the remotest parts of the earth.

[[v24-6-23]]

^<<v24-6-23,23>>^ They will grab hold of the bow and the javelin.
They are cruel and will have no mercy.
Their voice will roar like the sea,
And they ride on horses.
They draw up in battle order like a man of war against you, O daughter of Zion.”

[[v24-6-24]]

^<<v24-6-24,24>>^ We have heard the report about it.
Our hands fall limp;
Distress has seized us,
Anguish^&#42;1^ like that of a woman giving birth.

[NOTE]
====
. Lit., “Birth pangs.”
====

[[v24-6-25]]

^<<v24-6-25,25>>^ Do not go out into the field,
And do not walk on the road,
For the enemy has a sword;
There is terror all around.

[[v24-6-26]]

^<<v24-6-26,26>>^ O daughter of my people,
Put on sackcloth and roll in the ashes.
Mourn as for an only son, with bitter wailing,
For suddenly the destroyer will come upon us.

[[v24-6-27]]

^<<v24-6-27,27>>^ “I have made you^&#42;1^ a metal tester among my people,
One making a thorough search;
You must take note and examine their way.

[NOTE]
====
. That is, Jeremiah.
====

[[v24-6-28]]

^<<v24-6-28,28>>^ All of them are the most stubborn men,
Walking about as slanderers.
They are like copper and iron;
All of them are corrupt.

[[v24-6-29]]

^<<v24-6-29,29>>^ The bellows have been scorched.
Out from their fire there is lead.
One keeps refining intensely simply for nothing,
And those who are bad have not been separated.

[[v24-6-30]]

^<<v24-6-30,30>>^ Rejected silver is what people will certainly call them,
For Jehovah has rejected them.”

'''

xref:024-jeremiah/024-jeremiah-005.adoc#v24-5-0[&#60; Capítulo Anterior] | <<v24-6-0,Topo>> | xref:024-jeremiah/024-jeremiah-007.adoc#v24-7-0[Próximo Capítulo &#62;]