include::./index.adoc[]

[[v24-16-0]]
=== Jeremiah, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v24-16-1]]

^<<v24-16-1,1>>^ The word of Jehovah again came to me, saying:

[[v24-16-2]]

^<<v24-16-2,2>>^ “You must not take a wife for yourself, and you must not have sons and daughters in this place.

[[v24-16-3]]

^<<v24-16-3,3>>^ For this is what Jehovah says concerning the sons and daughters who are born here and concerning their mothers who give birth to them and concerning their fathers who cause their birth in this land:

[[v24-16-4]]

^<<v24-16-4,4>>^ ‘They will die of deadly diseases, but no one will mourn them or bury them; they will become like manure on the surface of the ground. They will perish by the sword and by famine, and their dead bodies will be food for the birds of the heavens and for the beasts of the earth.’

[[v24-16-5]]

^<<v24-16-5,5>>^ For this is what Jehovah says,
‘Do not enter a house where a mourners’ feast is held,
And do not go to wail or offer sympathy.’
‘For I have taken away my peace from this people,’ declares Jehovah,
‘As well as my loyal love and mercy.

[[v24-16-6]]

^<<v24-16-6,6>>^ Both the great and the small will die in this land.
They will not be buried,
No one will mourn them,
Nor will anyone cut himself or make himself bald for them.^&#42;1^

[NOTE]
====
. Pagan mourning customs apparently practiced in apostate Israel.
====

[[v24-16-7]]

^<<v24-16-7,7>>^ And no one will provide food for those in mourning,
To comfort them over their dead;
Nor will anyone give them the cup of consolation
To drink over the loss of their father or mother.

[[v24-16-8]]

^<<v24-16-8,8>>^ And do not enter a house of feasting
To sit down with them to eat and drink.’

[[v24-16-9]]

^<<v24-16-9,9>>^ “For this is what Jehovah of armies, the God of Israel, says, ‘Here in this place, in your days and before your very eyes, I will put an end to the sounds of exultation and rejoicing, the voice of the bridegroom and the voice of the bride.’

[[v24-16-10]]

^<<v24-16-10,10>>^ “When you tell this people all these words, they will ask you, ‘Why has Jehovah spoken of all this great calamity against us? What error and what sin have we committed against Jehovah our God?’

[[v24-16-11]]

^<<v24-16-11,11>>^ You must reply to them, ‘“Because your forefathers abandoned me,” declares Jehovah, “and they kept following other gods and serving them and bowing down to them. But me they abandoned, and my law they did not keep.

[[v24-16-12]]

^<<v24-16-12,12>>^ And you have behaved far worse than your forefathers, and each one of you follows the stubbornness of his wicked heart instead of obeying me.

[[v24-16-13]]

^<<v24-16-13,13>>^ So I will hurl you out of this land into a land that neither you nor your forefathers have known, and there you will have to serve other gods day and night, because I will show you no favor.”’

[[v24-16-14]]

^<<v24-16-14,14>>^ “‘However, the days are coming,’ declares Jehovah, ‘when they will no longer say: “As surely as Jehovah is alive, who brought the people of Israel out of the land of Egypt!”

[[v24-16-15]]

^<<v24-16-15,15>>^ but rather: “As surely as Jehovah is alive, who brought the people of Israel from the land of the north and from all the lands to which he had dispersed them!” and I will bring them back to their land, which I gave to their forefathers.’

[[v24-16-16]]

^<<v24-16-16,16>>^ ‘Here I am sending for many fishermen,’ declares Jehovah,
‘And they will fish for them.
After that I will send for many hunters,
And they will hunt them down on every mountain and every hill
And out of the clefts of the crags.

[[v24-16-17]]

^<<v24-16-17,17>>^ For my eyes are on everything they do.^&#42;1^
They have not been hidden from before me,
Nor has their error been hidden from my eyes.

[NOTE]
====
. Lit., “on all their ways.”
====

[[v24-16-18]]

^<<v24-16-18,18>>^ First, I will repay the full amount due for their error and their sin,
For they have profaned my land with the lifeless figures^&#42;1^ of their disgusting idols
And have filled my inheritance with their detestable things.’”

[NOTE]
====
. Lit., “the corpses.”
====

[[v24-16-19]]

^<<v24-16-19,19>>^ O Jehovah, my strength and my stronghold,
My place to flee in the day of distress,
To you the nations will come from the ends of the earth,
And they will say: “Our forefathers inherited utter falsehood,
Futility and useless things of no benefit.”

[[v24-16-20]]

^<<v24-16-20,20>>^ Can a man make gods for himself
When they are not really gods?

[[v24-16-21]]

^<<v24-16-21,21>>^ “So I will make them know,
At this time I will make them know my power and my might,
And they will have to know that my name is Jehovah.”

'''

xref:024-jeremiah/024-jeremiah-015.adoc#v24-15-0[&#60; Capítulo Anterior] | <<v24-16-0,Topo>> | xref:024-jeremiah/024-jeremiah-017.adoc#v24-17-0[Próximo Capítulo &#62;]