include::./index.adoc[]

[[v14-2-0]]
=== The Second of Chronicles, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-2-1]]

^<<v14-2-1,1>>^ Solʹo·mon now gave the order to build a house for Jehovah’s name and a house^&#42;1^ for his kingdom.

[NOTE]
====
. Or “palace.”
====

[[v14-2-2]]

^<<v14-2-2,2>>^ Solʹo·mon enlisted 70,000 men as common laborers,^&#42;1^ 80,000 men as stonecutters in the mountains, and 3,600 as overseers over them.

[NOTE]
====
. Or “as burden bearers.”
====

[[v14-2-3]]

^<<v14-2-3,3>>^ Further, Solʹo·mon sent word to Hiʹram the king of Tyre: “Do for me as you did for David my father when you sent him cedarwood to build a house^&#42;1^ to live in.

[NOTE]
====
. Or “palace.”
====

[[v14-2-4]]

^<<v14-2-4,4>>^ Now I am building a house for the name of Jehovah my God, to sanctify it to him, to burn perfumed incense before him, and also for the constant layer bread^&#42;1^ and the burnt offerings, morning and evening, on the Sabbaths, on the new moons, and at the festival seasons of Jehovah our God. This is a lasting obligation for Israel.

[NOTE]
====
. That is, the showbread.
====

[[v14-2-5]]

^<<v14-2-5,5>>^ The house that I am building will be great, for our God is greater than all the other gods.

[[v14-2-6]]

^<<v14-2-6,6>>^ And who is up to the task of building him a house? For the heavens and the heaven of the heavens cannot contain him, so who am I that I should build him a house except as a place for making sacrifices smoke before him?

[[v14-2-7]]

^<<v14-2-7,7>>^ Now send me a craftsman who is skilled in working in gold, silver, copper, iron, purple wool, crimson, and blue thread and who knows how to cut engravings. He will work in Judah and in Jerusalem with my skilled craftsmen, whom David my father has provided.

[[v14-2-8]]

^<<v14-2-8,8>>^ And send me timbers of cedar, juniper, and algum from Lebʹa·non, for I well know that your servants are experienced at cutting down the trees of Lebʹa·non. My servants will work along with your servants

[[v14-2-9]]

^<<v14-2-9,9>>^ to prepare for me great quantities of timber, for the house that I am to build will be extraordinarily great.

[[v14-2-10]]

^<<v14-2-10,10>>^ Now look! I will supply the food for your servants, the woodcutters who cut down the trees: 20,000 cors^&#42;1^ of wheat, 20,000 cors of barley, 20,000 baths^&#42;2^ of wine, and 20,000 baths of oil.”

[NOTE]
====
. A cor equaled 220 L (200 dry qt). See App. B14.
. A bath equaled 22 L (5.81 gal). See App. B14.
====

[[v14-2-11]]

^<<v14-2-11,11>>^ At that Hiʹram the king of Tyre sent this written message to Solʹo·mon: “Because Jehovah loves his people, he has made you their king.”

[[v14-2-12]]

^<<v14-2-12,12>>^ Hiʹram then said: “May Jehovah the God of Israel be praised, who made the heavens and the earth, because he has given to King David a wise son, endowed with discretion and understanding, who will build a house for Jehovah and a house for his kingdom.

[[v14-2-13]]

^<<v14-2-13,13>>^ Now I am sending a skilled craftsman, endowed with understanding, Hiʹram-aʹbi,

[[v14-2-14]]

^<<v14-2-14,14>>^ who is the son of a Danʹite woman but whose father was a man of Tyre; he has experience in working in gold, silver, copper, iron, stones, timbers, purple wool, blue thread, fine fabric, and crimson. He can do every sort of engraving and make any design he is given. He will work with your own skilled craftsmen and the skilled craftsmen of my lord David your father.

[[v14-2-15]]

^<<v14-2-15,15>>^ Now let my lord send the wheat, barley, oil, and wine he has promised to his servants.

[[v14-2-16]]

^<<v14-2-16,16>>^ And we will cut down trees from Lebʹa·non, as many as you need, and we will bring them to you as rafts by sea to Jopʹpa; and you will take them up to Jerusalem.”

[[v14-2-17]]

^<<v14-2-17,17>>^ Solʹo·mon then took a count of all the men who were foreign residents in the land of Israel, after the census taken by David his father, and there were found 153,600.

[[v14-2-18]]

^<<v14-2-18,18>>^ So he assigned 70,000 of them as common laborers,^&#42;1^ 80,000 as stonecutters in the mountains, and 3,600 as overseers for putting the people to work.

[NOTE]
====
. Or “as burden bearers.”
====

'''

xref:014-2-chronicles/014-2-chronicles-001.adoc#v14-1-0[&#60; Capítulo Anterior] | <<v14-2-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-003.adoc#v14-3-0[Próximo Capítulo &#62;]