include::./index.adoc[]

[[v14-19-0]]
=== The Second of Chronicles, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-19-1]]

^<<v14-19-1,1>>^ Then King Je·hoshʹa·phat of Judah returned safely^&#42;1^ to his own house^&#42;2^ in Jerusalem.

[NOTE]
====
. Or “in peace.”
. Or “palace.”
====

[[v14-19-2]]

^<<v14-19-2,2>>^ Jeʹhu the son of Ha·naʹni the visionary went out to meet him and said to King Je·hoshʹa·phat: “Is it the wicked you should be helping, and is it those who hate Jehovah you should love? Because of this the indignation of Jehovah is against you.

[[v14-19-3]]

^<<v14-19-3,3>>^ Nevertheless, there are good things that have been found in you, because you cleared out the sacred poles^&#42;1^ from the land and you have prepared your heart^&#42;2^ to search for the true God.”

[NOTE]
====
. See Glossary.
. Or “your heart is resolved.”
====

[[v14-19-4]]

^<<v14-19-4,4>>^ Je·hoshʹa·phat continued living in Jerusalem, and he went out again among the people from Beʹer-sheʹba to the mountainous region of Eʹphra·im, to bring them back to Jehovah the God of their forefathers.

[[v14-19-5]]

^<<v14-19-5,5>>^ He also appointed judges throughout the land in all the fortified cities of Judah, city by city.

[[v14-19-6]]

^<<v14-19-6,6>>^ And he said to the judges: “Pay attention to what you are doing, for you do not judge for man but for Jehovah, and he is with you when you pass judgment.

[[v14-19-7]]

^<<v14-19-7,7>>^ Now let the fear of Jehovah be upon you. Be careful about what you do, for with Jehovah our God there is no injustice, no partiality, no bribe-taking.”

[[v14-19-8]]

^<<v14-19-8,8>>^ In Jerusalem also, Je·hoshʹa·phat appointed some of the Levites and the priests and some of the heads of the paternal houses of Israel to serve as judges for Jehovah and to settle legal cases for the inhabitants of Jerusalem.

[[v14-19-9]]

^<<v14-19-9,9>>^ And he commanded them: “This is what you should do in the fear of Jehovah, with faithfulness and a complete^&#42;1^ heart:

[NOTE]
====
. Or “completely devoted.”
====

[[v14-19-10]]

^<<v14-19-10,10>>^ Whenever your brothers living in their cities bring a legal case that involves the shedding of blood or a question about a law, a commandment, regulations, or judgments, you should warn them so that they may not become guilty before Jehovah; otherwise his indignation will come against you and your brothers. This is what you should do, so that you may not incur guilt.

[[v14-19-11]]

^<<v14-19-11,11>>^ Here is Am·a·riʹah the chief priest who is over you for every matter of Jehovah. Zeb·a·diʹah the son of Ishʹma·el is the leader of the house of Judah for every matter pertaining to the king. And the Levites will serve as officers for you. Be strong and act, and let Jehovah be with those who do what is good.”^&#42;1^

[NOTE]
====
. Or “with what is good.”
====

'''

xref:014-2-chronicles/014-2-chronicles-018.adoc#v14-18-0[&#60; Capítulo Anterior] | <<v14-19-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-020.adoc#v14-20-0[Próximo Capítulo &#62;]