include::./index.adoc[]

[[v14-32-0]]
=== The Second of Chronicles, 32
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-32-1]]

^<<v14-32-1,1>>^ After these things and these acts of faithfulness, King Sen·nachʹer·ib of As·syrʹi·a came and invaded Judah. He besieged the fortified cities, intent on breaking through and capturing them.

[[v14-32-2]]

^<<v14-32-2,2>>^ When Hez·e·kiʹah saw that Sen·nachʹer·ib had come and intended to wage war against Jerusalem,

[[v14-32-3]]

^<<v14-32-3,3>>^ he decided, after consulting with his princes and his warriors, to stop up the waters of the springs outside the city, and they gave him their support.

[[v14-32-4]]

^<<v14-32-4,4>>^ Many people were gathered together, and they stopped up all the springs and the stream that flowed through the land, saying: “Why should the kings of As·syrʹi·a come and find plenty of water?”

[[v14-32-5]]

^<<v14-32-5,5>>^ Furthermore, with determination he rebuilt the entire broken-down wall and raised towers on it, and outside he made another wall. He also repaired the Mound^&#42;1^ of the City of David, and he made a large number of weapons^&#42;2^ and shields.

[NOTE]
====
. Or “Millo.” A Hebrew term meaning “fill.”
. Or “missiles.”
====

[[v14-32-6]]

^<<v14-32-6,6>>^ He then appointed military chiefs over the people and assembled them at the public square of the city gate and encouraged them,^&#42;1^ saying:

[NOTE]
====
. Lit., “spoke to their heart.”
====

[[v14-32-7]]

^<<v14-32-7,7>>^ “Be courageous and strong. Do not be afraid or be terrified because of the king of As·syrʹi·a and all the multitude with him, for there are more with us than there are with him.

[[v14-32-8]]

^<<v14-32-8,8>>^ With him is an arm of flesh,^&#42;1^ but with us is Jehovah our God to help us and to fight our battles.” And the people were strengthened by the words of King Hez·e·kiʹah of Judah.

[NOTE]
====
. Or “is human strength.”
====

[[v14-32-9]]

^<<v14-32-9,9>>^ After this, while King Sen·nachʹer·ib of As·syrʹi·a was at Laʹchish with all his imperial might,^&#42;1^ he sent his servants to Jerusalem, to King Hez·e·kiʹah of Judah and to all the Ju·deʹans in Jerusalem, saying:

[NOTE]
====
. Or “all his military might and splendor.”
====

[[v14-32-10]]

^<<v14-32-10,10>>^ “This is what King Sen·nachʹer·ib of As·syrʹi·a says, ‘In what are you trusting that you remain in Jerusalem while it is besieged?

[[v14-32-11]]

^<<v14-32-11,11>>^ Is not Hez·e·kiʹah misleading you and handing you over to die by famine and thirst, saying: “Jehovah our God will rescue us from the hand of the king of As·syrʹi·a”?

[[v14-32-12]]

^<<v14-32-12,12>>^ Is this not the same Hez·e·kiʹah who removed your God’s^&#42;1^ high places and His altars and then said to Judah and Jerusalem: “You should bow down before one altar and on it you should make your sacrifices smoke”?

[NOTE]
====
. Lit., “his.”
====

[[v14-32-13]]

^<<v14-32-13,13>>^ Do you not know what I and my forefathers did to all the peoples of the lands? Were the gods of the nations of the lands able to rescue their land from my hand?

[[v14-32-14]]

^<<v14-32-14,14>>^ Who among all the gods of these nations that my forefathers devoted to destruction was able to rescue his people from my hand, so that your God should be able to rescue you from my hand?

[[v14-32-15]]

^<<v14-32-15,15>>^ Now do not let Hez·e·kiʹah deceive you or mislead you like this! Do not put faith in him, for no god of any nation or kingdom was able to rescue his people from my hand and from the hand of my forefathers. How much less, then, will your own God rescue you from my hand!’”

[[v14-32-16]]

^<<v14-32-16,16>>^ His servants said even more against Jehovah the true God and against Hez·e·kiʹah his servant.

[[v14-32-17]]

^<<v14-32-17,17>>^ He also wrote letters to insult Jehovah the God of Israel and to speak against him, saying: “Like the gods of the nations of the lands who could not rescue their people from my hand, so the God of Hez·e·kiʹah will not rescue his people from my hand.”

[[v14-32-18]]

^<<v14-32-18,18>>^ They kept calling loudly in the language of the Jews to the people of Jerusalem who were on the wall, to make them afraid and to terrify them, in order to capture the city.

[[v14-32-19]]

^<<v14-32-19,19>>^ They spoke against the God of Jerusalem the same way as against the gods of the peoples of the earth, which are the work of man’s hands.

[[v14-32-20]]

^<<v14-32-20,20>>^ But King Hez·e·kiʹah and the prophet Isaiah the son of Aʹmoz kept praying about this and crying out to the heavens for help.

[[v14-32-21]]

^<<v14-32-21,21>>^ Then Jehovah sent an angel and wiped out every mighty warrior, leader, and chief in the camp of the king of As·syrʹi·a, so that he went back to his own land in disgrace. He later entered the house^&#42;1^ of his god, and there some of his own sons struck him down with the sword.

[NOTE]
====
. Or “temple.”
====

[[v14-32-22]]

^<<v14-32-22,22>>^ So Jehovah saved Hez·e·kiʹah and the inhabitants of Jerusalem from the hand of King Sen·nachʹer·ib of As·syrʹi·a and from the hand of all others and gave them rest on every side.

[[v14-32-23]]

^<<v14-32-23,23>>^ And many brought gifts to Jehovah at Jerusalem and choice things to King Hez·e·kiʹah of Judah, and he was greatly respected by all the nations after that.

[[v14-32-24]]

^<<v14-32-24,24>>^ In those days Hez·e·kiʹah became sick and was at the point of death, and he prayed to Jehovah, who answered him and gave him a sign.^&#42;1^

[NOTE]
====
. Or “portent.”
====

[[v14-32-25]]

^<<v14-32-25,25>>^ But Hez·e·kiʹah did not respond appreciatively to the good done to him, for his heart became haughty, bringing indignation against him and against Judah and Jerusalem.

[[v14-32-26]]

^<<v14-32-26,26>>^ However, Hez·e·kiʹah humbled himself for the haughtiness of his heart, he and the inhabitants of Jerusalem, and Jehovah’s indignation did not come upon them in the days of Hez·e·kiʹah.

[[v14-32-27]]

^<<v14-32-27,27>>^ And Hez·e·kiʹah came to have vast riches and glory; and he made storehouses for himself for silver, gold, precious stones, balsam oil, shields, and for all the desirable articles.

[[v14-32-28]]

^<<v14-32-28,28>>^ He also made storage places for the produce of grain and new wine and oil, as well as stalls for all the different kinds of livestock and stalls for the flocks.

[[v14-32-29]]

^<<v14-32-29,29>>^ He also acquired cities for himself, and an abundance of livestock, flocks, and herds, for God gave him very many possessions.

[[v14-32-30]]

^<<v14-32-30,30>>^ It was Hez·e·kiʹah who stopped up the upper source of the waters of Giʹhon and directed them straight down to the west to the City of David, and Hez·e·kiʹah was successful in every work of his.

[[v14-32-31]]

^<<v14-32-31,31>>^ However, when the spokesmen of the princes of Babylon were sent to ask him about the sign^&#42;1^ that had occurred in the land, the true God left him alone to put him to the test, to get to know all that was in his heart.

[NOTE]
====
. Or “portent.”
====

[[v14-32-32]]

^<<v14-32-32,32>>^ As for the rest of the history of Hez·e·kiʹah and his acts of loyal love, they are written in the vision of Isaiah the prophet, the son of Aʹmoz, in the Book of the Kings of Judah and of Israel.

[[v14-32-33]]

^<<v14-32-33,33>>^ Then Hez·e·kiʹah was laid to rest with his forefathers, and they buried him in the ascent to the burial places of the sons of David; and all Judah and the inhabitants of Jerusalem honored him at his death. And his son Ma·nasʹseh became king in his place.

'''

xref:014-2-chronicles/014-2-chronicles-031.adoc#v14-31-0[&#60; Capítulo Anterior] | <<v14-32-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-033.adoc#v14-33-0[Próximo Capítulo &#62;]