include::./index.adoc[]

[[v14-27-0]]
=== The Second of Chronicles, 27
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-27-1]]

^<<v14-27-1,1>>^ Joʹtham was 25 years old when he became king, and he reigned for 16 years in Jerusalem. His mother’s name was Je·ruʹshah the daughter of Zaʹdok.

[[v14-27-2]]

^<<v14-27-2,2>>^ He kept doing what was right in Jehovah’s eyes, just as his father Uz·ziʹah had done, except that he did not invade the temple of Jehovah. But the people were still acting ruinously.

[[v14-27-3]]

^<<v14-27-3,3>>^ He built the upper gate of Jehovah’s house, and he did much building on the wall of Oʹphel.

[[v14-27-4]]

^<<v14-27-4,4>>^ He also built cities in the mountainous region of Judah, and he built fortified places and towers in the wooded areas.

[[v14-27-5]]

^<<v14-27-5,5>>^ He waged war against the king of the Amʹmon·ites and eventually prevailed against them, so that the Amʹmon·ites gave him in that year 100 silver talents,^&#42;1^ 10,000 cor measures^&#42;2^ of wheat, and 10,000 of barley. The Amʹmon·ites also paid this to him in the second and third years.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
. A cor equaled 220 L (200 dry qt). See App. B14.
====

[[v14-27-6]]

^<<v14-27-6,6>>^ So Joʹtham kept growing strong, for he established^&#42;1^ his ways before Jehovah his God.

[NOTE]
====
. Or “prepared.”
====

[[v14-27-7]]

^<<v14-27-7,7>>^ As for the rest of the history of Joʹtham, all his wars and his ways, it is written in the Book of the Kings of Israel and of Judah.

[[v14-27-8]]

^<<v14-27-8,8>>^ He was 25 years old when he became king, and he reigned for 16 years in Jerusalem.

[[v14-27-9]]

^<<v14-27-9,9>>^ Then Joʹtham was laid to rest with his forefathers, and they buried him in the City of David. And his son Aʹhaz became king in his place.

'''

xref:014-2-chronicles/014-2-chronicles-026.adoc#v14-26-0[&#60; Capítulo Anterior] | <<v14-27-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-028.adoc#v14-28-0[Próximo Capítulo &#62;]