include::./index.adoc[]

[[v14-35-0]]
=== The Second of Chronicles, 35
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-35-1]]

^<<v14-35-1,1>>^ Jo·siʹah held a Passover to Jehovah in Jerusalem, and they slaughtered the Passover sacrifice on the 14th day of the first month.

[[v14-35-2]]

^<<v14-35-2,2>>^ He assigned the priests to their duties and encouraged them to carry out their service of the house of Jehovah.

[[v14-35-3]]

^<<v14-35-3,3>>^ Then he said to the Levites, the instructors of all Israel, those who were holy to Jehovah: “Put the holy Ark in the house that Solʹo·mon the son of David the king of Israel built; you are no longer to carry it on your shoulders. Now serve Jehovah your God and his people Israel.

[[v14-35-4]]

^<<v14-35-4,4>>^ And prepare yourselves by your paternal houses according to your divisions, following what was written by King David of Israel and by his son Solʹo·mon.

[[v14-35-5]]

^<<v14-35-5,5>>^ Stand in the holy place grouped by the paternal houses of your brothers, the rest of the people,^&#42;1^ with a corresponding group of the paternal house of the Levites.

[NOTE]
====
. Lit., “the sons of the people.”
====

[[v14-35-6]]

^<<v14-35-6,6>>^ Slaughter the Passover sacrifice and sanctify yourselves and make preparation for your brothers to carry out the word of Jehovah through Moses.”

[[v14-35-7]]

^<<v14-35-7,7>>^ Jo·siʹah contributed flocks to the people, male lambs and young male goats, for the Passover sacrifices for all who were present, a total of 30,000, as well as 3,000 cattle. These were from the king’s own property.

[[v14-35-8]]

^<<v14-35-8,8>>^ His princes also made a contribution as a voluntary offering for the people, the priests, and the Levites. Hil·kiʹah, Zech·a·riʹah, and Je·hiʹel, the leaders of the house of the true God, gave to the priests 2,600 Passover sacrifices and 300 cattle.

[[v14-35-9]]

^<<v14-35-9,9>>^ Con·a·niʹah and his brothers She·maiʹah and Ne·thanʹel, along with Hash·a·biʹah, Je·iʹel, and Joʹza·bad, the chiefs of the Levites, contributed to the Levites 5,000 Passover sacrifices and 500 cattle.

[[v14-35-10]]

^<<v14-35-10,10>>^ The service was prepared, and the priests stood at their places and the Levites by their divisions, as the king had commanded.

[[v14-35-11]]

^<<v14-35-11,11>>^ They slaughtered the Passover sacrifices, and the priests sprinkled the blood they received from them, while the Levites were skinning the animals.

[[v14-35-12]]

^<<v14-35-12,12>>^ Next they prepared the burnt offerings so as to distribute them to the rest of the people, who were grouped by paternal house, so that they could be presented to Jehovah as it is written in the book of Moses; and they did the same with the cattle.

[[v14-35-13]]

^<<v14-35-13,13>>^ They cooked^&#42;1^ the Passover offering over the fire according to the custom; and they cooked the holy offerings in pots, cauldrons, and pans, after which they brought it quickly to all the rest of the people.

[NOTE]
====
. Or possibly, “roasted.”
====

[[v14-35-14]]

^<<v14-35-14,14>>^ Then they made preparations for themselves and for the priests, because the priests, the descendants of Aaron, were offering up the burnt sacrifices and the fat pieces until nightfall, so the Levites made preparations for themselves and for the priests, the descendants of Aaron.

[[v14-35-15]]

^<<v14-35-15,15>>^ And the singers, the sons of Aʹsaph, were at their positions by the commandment of David, Aʹsaph, Heʹman, and Je·duʹthun the visionary of the king; and the gatekeepers were at the different gates. There was no need for them to leave their service, because their brothers the Levites made preparations for them.

[[v14-35-16]]

^<<v14-35-16,16>>^ So all the service of Jehovah was prepared on that day to hold the Passover and to offer up the burnt offerings on the altar of Jehovah, according to the order of King Jo·siʹah.

[[v14-35-17]]

^<<v14-35-17,17>>^ The Israelites who were present held the Passover at that time and the Festival of Unleavened Bread for seven days.

[[v14-35-18]]

^<<v14-35-18,18>>^ There had never been held a Passover like it in Israel since the days of Samuel the prophet; nor had any of the other kings of Israel held a Passover like that held by Jo·siʹah, the priests, the Levites, all Judah and Israel who were present, and the inhabitants of Jerusalem.

[[v14-35-19]]

^<<v14-35-19,19>>^ This Passover was held in the 18th year of Jo·siʹah’s reign.

[[v14-35-20]]

^<<v14-35-20,20>>^ After all of this, when Jo·siʹah had prepared the temple,^&#42;1^ King Neʹcho of Egypt came up to fight at Carʹche·mish by the Eu·phraʹtes. Then Jo·siʹah went out against him.

[NOTE]
====
. Lit., “house.”
====

[[v14-35-21]]

^<<v14-35-21,21>>^ So he sent messengers to him, saying: “What does this have to do with you, O king of Judah? I am not coming against you today, but my fight is against another house, and God says that I should hurry. For your own sake, refrain from opposing God, who is with me, or he will bring you to ruin.”

[[v14-35-22]]

^<<v14-35-22,22>>^ However, Jo·siʹah would not turn away from him, but he disguised himself to fight against him and would not listen to the words of Neʹcho, which were from the mouth of God. So he came to fight in the Plain of Me·gidʹdo.

[[v14-35-23]]

^<<v14-35-23,23>>^ And the archers shot King Jo·siʹah, and the king said to his servants: “Get me out of here, for I am severely wounded.”

[[v14-35-24]]

^<<v14-35-24,24>>^ So his servants took him out of the chariot and had him ride in his second war chariot and brought him to Jerusalem. Thus he died and was buried in the tomb of his forefathers, and all Judah and Jerusalem mourned Jo·siʹah.

[[v14-35-25]]

^<<v14-35-25,25>>^ And Jeremiah chanted over Jo·siʹah, and all the male and female singers keep singing about Jo·siʹah in their dirges^&#42;1^ down to this day; and a decision was made that they should be sung in Israel, and they are written among the dirges.

[NOTE]
====
. Or “songs of mourning.”
====

[[v14-35-26]]

^<<v14-35-26,26>>^ As for the rest of the history of Jo·siʹah and his deeds of loyal love, in keeping with what is written in the Law of Jehovah,

[[v14-35-27]]

^<<v14-35-27,27>>^ and what he did, from beginning to end, they are written in the Book of the Kings of Israel and of Judah.

'''

xref:014-2-chronicles/014-2-chronicles-034.adoc#v14-34-0[&#60; Capítulo Anterior] | <<v14-35-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-036.adoc#v14-36-0[Próximo Capítulo &#62;]