include::./index.adoc[]

[[v14-11-0]]
=== The Second of Chronicles, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-11-1]]

^<<v14-11-1,1>>^ When Re·ho·boʹam arrived in Jerusalem, he immediately congregated the house of Judah and Benjamin, 180,000 trained^&#42;1^ warriors, to fight against Israel in order to restore the kingdom to Re·ho·boʹam.

[NOTE]
====
. Lit., “chosen.”
====

[[v14-11-2]]

^<<v14-11-2,2>>^ Then the word of Jehovah came to She·maiʹah the man of the true God, saying:

[[v14-11-3]]

^<<v14-11-3,3>>^ “Say to Re·ho·boʹam the son of Solʹo·mon the king of Judah and to all Israel in Judah and Benjamin,

[[v14-11-4]]

^<<v14-11-4,4>>^ ‘This is what Jehovah says: “You must not go up and fight against your brothers. Each of you return to his house, for I have caused this to happen.”’” So they obeyed the word of Jehovah and returned and did not go against Jer·o·boʹam.

[[v14-11-5]]

^<<v14-11-5,5>>^ Re·ho·boʹam lived in Jerusalem and built fortified cities in Judah.

[[v14-11-6]]

^<<v14-11-6,6>>^ Thus he built up^&#42;1^ Bethʹle·hem, Eʹtam, Te·koʹa,

[NOTE]
====
. Or “fortified.”
====

[[v14-11-7]]

^<<v14-11-7,7>>^ Beth-zur, Soʹco, A·dulʹlam,

[[v14-11-8]]

^<<v14-11-8,8>>^ Gath, Ma·reʹshah, Ziph,

[[v14-11-9]]

^<<v14-11-9,9>>^ Ad·o·raʹim, Laʹchish, A·zeʹkah,

[[v14-11-10]]

^<<v14-11-10,10>>^ Zorʹah, Aiʹja·lon, and Hebʹron, fortified cities that were in Judah and Benjamin.

[[v14-11-11]]

^<<v14-11-11,11>>^ Further, he reinforced the fortified places and put commanders in them and supplied them with food and oil and wine,

[[v14-11-12]]

^<<v14-11-12,12>>^ and he supplied all the different cities with large shields and lances; he reinforced them to a very great degree. And Judah and Benjamin remained his.

[[v14-11-13]]

^<<v14-11-13,13>>^ And the priests and the Levites who were in all Israel took their stand with him, coming out of all their territories.

[[v14-11-14]]

^<<v14-11-14,14>>^ The Levites left their pastures and their possession and came to Judah and Jerusalem, because Jer·o·boʹam and his sons had dismissed them from serving as priests to Jehovah.

[[v14-11-15]]

^<<v14-11-15,15>>^ Jer·o·boʹam then appointed his own priests for the high places and for the goatlike demons^&#42;1^ and for the calves that he had made.

[NOTE]
====
. Lit., “the goats.”
====

[[v14-11-16]]

^<<v14-11-16,16>>^ And those from all the tribes of Israel who had their heart set on seeking Jehovah the God of Israel followed them to Jerusalem to sacrifice to Jehovah the God of their forefathers.

[[v14-11-17]]

^<<v14-11-17,17>>^ For three years they strengthened the kingship of Judah and supported Re·ho·boʹam the son of Solʹo·mon, for they walked in the way of David and Solʹo·mon for three years.

[[v14-11-18]]

^<<v14-11-18,18>>^ Then Re·ho·boʹam took as his wife Maʹha·lath the daughter of David’s son Jerʹi·moth and of Abʹi·ha·il the daughter of Jesʹse’s son E·liʹab.

[[v14-11-19]]

^<<v14-11-19,19>>^ In time she bore him sons: Jeʹush, Shem·a·riʹah, and Zaʹham.

[[v14-11-20]]

^<<v14-11-20,20>>^ After her, he married Maʹa·cah the granddaughter of Abʹsa·lom. In time she bore him A·biʹjah, Atʹtai, Ziʹza, and She·loʹmith.

[[v14-11-21]]

^<<v14-11-21,21>>^ Re·ho·boʹam loved Maʹa·cah the granddaughter of Abʹsa·lom more than all his other wives and concubines, for he took 18 wives and 60 concubines, and he became father to 28 sons and 60 daughters.

[[v14-11-22]]

^<<v14-11-22,22>>^ So Re·ho·boʹam appointed A·biʹjah the son of Maʹa·cah as head and leader among his brothers, for he intended to make him king.

[[v14-11-23]]

^<<v14-11-23,23>>^ However, he acted with understanding and sent^&#42;1^ some of his sons to all the regions of Judah and Benjamin, to all the fortified cities, and gave them abundant provisions and acquired many wives for them.

[NOTE]
====
. Or “dispersed.”
====

'''

xref:014-2-chronicles/014-2-chronicles-010.adoc#v14-10-0[&#60; Capítulo Anterior] | <<v14-11-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-012.adoc#v14-12-0[Próximo Capítulo &#62;]