include::./index.adoc[]

[[v14-13-0]]
=== The Second of Chronicles, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-13-1]]

^<<v14-13-1,1>>^ In the 18th year of King Jer·o·boʹam, A·biʹjah became king over Judah.

[[v14-13-2]]

^<<v14-13-2,2>>^ He reigned for three years in Jerusalem. His mother’s name was Mi·caiʹah the daughter of U·riʹel of Gibʹe·ah. And there was war between A·biʹjah and Jer·o·boʹam.

[[v14-13-3]]

^<<v14-13-3,3>>^ So A·biʹjah went to war with an army of 400,000 mighty, trained^&#42;1^ warriors. And Jer·o·boʹam drew up in battle formation against him with 800,000 trained^&#42;2^ men, mighty warriors.

[NOTE]
====
. Lit., “chosen.”
. Lit., “chosen.”
====

[[v14-13-4]]

^<<v14-13-4,4>>^ A·biʹjah now stood on Mount Zem·a·raʹim, which is in the mountainous region of Eʹphra·im, and said: “Hear me, O Jer·o·boʹam and all Israel.

[[v14-13-5]]

^<<v14-13-5,5>>^ Do you not know that Jehovah the God of Israel gave to David a kingdom over Israel forever, to him and to his sons, by a covenant of salt?^&#42;1^

[NOTE]
====
. That is, a permanent and unchanging covenant.
====

[[v14-13-6]]

^<<v14-13-6,6>>^ But Jer·o·boʹam the son of Neʹbat, the servant of David’s son Solʹo·mon, rose up and rebelled against his lord.

[[v14-13-7]]

^<<v14-13-7,7>>^ And idle, worthless men kept gathering to him. And they proved superior to Re·ho·boʹam the son of Solʹo·mon when Re·ho·boʹam was young and fainthearted, and he could not hold his own against them.

[[v14-13-8]]

^<<v14-13-8,8>>^ “And now you think you can hold your own against the kingdom of Jehovah in the hand of the sons of David because you are a large crowd and you have the golden calves that Jer·o·boʹam made as gods for you.

[[v14-13-9]]

^<<v14-13-9,9>>^ Have you not driven out Jehovah’s priests, the descendants of Aaron, and the Levites, and have you not appointed your own priests just like the peoples of the other lands? Anyone who came along with^&#42;1^ a young bull and seven rams could become a priest of what are not gods.

[NOTE]
====
. Lit., “came to fill his hand with.”
====

[[v14-13-10]]

^<<v14-13-10,10>>^ As for us, Jehovah is our God, and we have not abandoned him; our priests, the descendants of Aaron, are ministering to Jehovah, and the Levites assist in the work.

[[v14-13-11]]

^<<v14-13-11,11>>^ They are making burnt offerings smoke to Jehovah each morning and each evening along with perfumed incense, and the layer bread^&#42;1^ is on the table of pure gold, and they light up the golden lampstand and its lamps each evening, because we are caring for our responsibility to Jehovah our God; but you have abandoned him.

[NOTE]
====
. That is, the showbread.
====

[[v14-13-12]]

^<<v14-13-12,12>>^ Now look! the true God is with us, leading us, with his priests and the signal trumpets for sounding the battle alarm against you. O men of Israel, do not fight against Jehovah the God of your forefathers, for you will not be successful.”

[[v14-13-13]]

^<<v14-13-13,13>>^ But Jer·o·boʹam dispatched an ambush to come from behind them, so that they were in front of Judah and the ambush was behind them.

[[v14-13-14]]

^<<v14-13-14,14>>^ When the men of Judah turned around, they saw that they had to fight the battle both in front and from behind. So they began to cry out to Jehovah, while the priests were loudly sounding the trumpets.

[[v14-13-15]]

^<<v14-13-15,15>>^ The men of Judah broke out in a war cry, and when the men of Judah shouted the war cry, the true God defeated Jer·o·boʹam and all Israel before A·biʹjah and Judah.

[[v14-13-16]]

^<<v14-13-16,16>>^ The Israelites fled before Judah, and God gave them into their hand.

[[v14-13-17]]

^<<v14-13-17,17>>^ A·biʹjah and his people inflicted a great slaughter on them, and the slain of Israel kept falling, 500,000 trained^&#42;1^ men.

[NOTE]
====
. Lit., “chosen.”
====

[[v14-13-18]]

^<<v14-13-18,18>>^ Thus the men of Israel were humbled at that time, but the men of Judah proved superior because they relied^&#42;1^ on Jehovah the God of their forefathers.

[NOTE]
====
. Lit., “leaned.”
====

[[v14-13-19]]

^<<v14-13-19,19>>^ A·biʹjah kept chasing after Jer·o·boʹam and captured cities from him, Bethʹel and its dependent^&#42;1^ towns, Jeshʹa·nah and its dependent towns, and Eʹphra·in and its dependent towns.

[NOTE]
====
. Or “surrounding.”
====

[[v14-13-20]]

^<<v14-13-20,20>>^ And Jer·o·boʹam never regained his power during the time of A·biʹjah; then Jehovah struck him down and he died.

[[v14-13-21]]

^<<v14-13-21,21>>^ But A·biʹjah grew in strength. In time he took 14 wives, and he became father to 22 sons and 16 daughters.

[[v14-13-22]]

^<<v14-13-22,22>>^ And the rest of A·biʹjah’s history, his deeds and his words, is recorded in the writings^&#42;1^ of the prophet Idʹdo.

[NOTE]
====
. Or “exposition; commentary.”
====

'''

xref:014-2-chronicles/014-2-chronicles-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-014.adoc#v14-14-0[Próximo Capítulo &#62;]