include::./index.adoc[]

[[v14-9-0]]
=== The Second of Chronicles, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-9-1]]

^<<v14-9-1,1>>^ Now the queen of Sheʹba heard the report about Solʹo·mon, so she came to Jerusalem to test Solʹo·mon with perplexing questions.^&#42;1^ She was accompanied by a very impressive entourage,^&#42;2^ with camels carrying balsam oil and great quantities of gold and precious stones. She went in to Solʹo·mon and spoke to him about everything that was close to her heart.

[NOTE]
====
. Or “with riddles.”
. Or “train.”
====

[[v14-9-2]]

^<<v14-9-2,2>>^ Solʹo·mon then answered all her questions. There was nothing too difficult for^&#42;1^ Solʹo·mon to explain to her.

[NOTE]
====
. Lit., “nothing hidden from.”
====

[[v14-9-3]]

^<<v14-9-3,3>>^ When the queen of Sheʹba had seen Solʹo·mon’s wisdom, the house that he built,

[[v14-9-4]]

^<<v14-9-4,4>>^ the food of his table, the seating of his servants, the table service of his waiters and their attire, his cupbearers and their attire, and his burnt sacrifices that he regularly offered up at the house of Jehovah, she was left completely breathless.^&#42;1^

[NOTE]
====
. Lit., “there was no more spirit in her.”
====

[[v14-9-5]]

^<<v14-9-5,5>>^ So she said to the king: “The report that I heard in my own land about your achievements^&#42;1^ and about your wisdom was true.

[NOTE]
====
. Or “words.”
====

[[v14-9-6]]

^<<v14-9-6,6>>^ But I did not put faith in the reports until I had come and had seen it with my own eyes. And look! I had not been told the half of your great wisdom. You have far surpassed the report that I heard.

[[v14-9-7]]

^<<v14-9-7,7>>^ Happy are your men, and happy are your servants who stand before you constantly, listening to your wisdom!

[[v14-9-8]]

^<<v14-9-8,8>>^ May Jehovah your God be praised, who has taken pleasure in you by putting you on his throne as king for Jehovah your God. Because your God loves Israel, in order to make it continue forever, he appointed you over it as king to administer justice and righteousness.”

[[v14-9-9]]

^<<v14-9-9,9>>^ Then she gave the king 120 talents^&#42;1^ of gold and a great quantity of balsam oil and precious stones. Never again was such balsam oil brought in as what the queen of Sheʹba gave to King Solʹo·mon.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v14-9-10]]

^<<v14-9-10,10>>^ Moreover, the servants of Hiʹram and the servants of Solʹo·mon who brought gold from Oʹphir also brought algum timbers and precious stones.

[[v14-9-11]]

^<<v14-9-11,11>>^ The king made from the algum timbers stairs for the house of Jehovah and for the king’s house,^&#42;1^ as well as harps and stringed instruments for the singers. Nothing like them had ever been seen before in the land of Judah.

[NOTE]
====
. Or “palace.”
====

[[v14-9-12]]

^<<v14-9-12,12>>^ King Solʹo·mon also gave the queen of Sheʹba whatever she desired and asked for, more than^&#42;1^ what she had brought to the king. Then she left and returned to her own land, together with her servants.

[NOTE]
====
. Or possibly, “in addition to gifts corresponding to the value of.”
====

[[v14-9-13]]

^<<v14-9-13,13>>^ And the weight of the gold that came to Solʹo·mon in one year amounted to 666 talents of gold,

[[v14-9-14]]

^<<v14-9-14,14>>^ besides that brought in by the merchants and the traders and all the kings of the Arabs and the governors of the land who were bringing gold and silver in to Solʹo·mon.

[[v14-9-15]]

^<<v14-9-15,15>>^ King Solʹo·mon made 200 large shields of alloyed gold (600 shekels^&#42;1^ of alloyed gold went on each shield)

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v14-9-16]]

^<<v14-9-16,16>>^ and 300 bucklers^&#42;1^ of alloyed gold (three miʹnas^&#42;2^ of gold went on each buckler). Then the king put them in the House of the Forest of Lebʹa·non.

[NOTE]
====
. A small shield, often carried by archers.
. A mina in the Hebrew Scriptures equaled 570 g (18.35 oz t). See App. B14.
====

[[v14-9-17]]

^<<v14-9-17,17>>^ The king also made a great ivory throne and overlaid it with pure gold.

[[v14-9-18]]

^<<v14-9-18,18>>^ There were six steps to the throne, and there was a gold footstool attached to the throne, and there were armrests on both sides of the seat, and two lions were standing beside the armrests.

[[v14-9-19]]

^<<v14-9-19,19>>^ And there were 12 lions standing on the six steps, one at each end of the six steps. No other kingdom had made anything like it.

[[v14-9-20]]

^<<v14-9-20,20>>^ All the drinking vessels of King Solʹo·mon were of gold, and all the utensils of the House of the Forest of Lebʹa·non were of pure gold. There was nothing made of silver, for silver was considered as nothing in the days of Solʹo·mon.

[[v14-9-21]]

^<<v14-9-21,21>>^ For the king’s ships would go to Tarʹshish with the servants of Hiʹram. Once every three years, the ships of Tarʹshish would come loaded with gold and silver, ivory, apes, and peacocks.

[[v14-9-22]]

^<<v14-9-22,22>>^ So King Solʹo·mon was greater than all the other kings of the earth in riches and wisdom.

[[v14-9-23]]

^<<v14-9-23,23>>^ And the kings of all the earth sought an audience with^&#42;1^ Solʹo·mon to hear his wisdom that the true God had put in his heart.

[NOTE]
====
. Lit., “sought the face of.”
====

[[v14-9-24]]

^<<v14-9-24,24>>^ They would each bring a gift—articles of silver, articles of gold, garments, armor, balsam oil, horses, and mules—and this continued year after year.

[[v14-9-25]]

^<<v14-9-25,25>>^ And Solʹo·mon had 4,000 stalls for his horses and chariots and 12,000 horses,^&#42;1^ and he kept them stationed in the chariot cities and close by the king in Jerusalem.

[NOTE]
====
. Or “horsemen.”
====

[[v14-9-26]]

^<<v14-9-26,26>>^ And he ruled over all the kings from the River^&#42;1^ to the land of the Phi·lisʹtines and to the boundary of Egypt.

[NOTE]
====
. That is, the Euphrates.
====

[[v14-9-27]]

^<<v14-9-27,27>>^ The king made the silver in Jerusalem as plentiful as the stones, and cedarwood as plentiful as the sycamore trees in the She·pheʹlah.

[[v14-9-28]]

^<<v14-9-28,28>>^ And they would bring horses to Solʹo·mon from Egypt and from all the other lands.

[[v14-9-29]]

^<<v14-9-29,29>>^ As for the rest of the history of Solʹo·mon, from beginning to end, is it not written among the words of Nathan the prophet, in the prophecy of A·hiʹjah the Shiʹlo·nite, and in the record of visions of Idʹdo the visionary concerning Jer·o·boʹam the son of Neʹbat?

[[v14-9-30]]

^<<v14-9-30,30>>^ Solʹo·mon reigned in Jerusalem over all Israel for 40 years.

[[v14-9-31]]

^<<v14-9-31,31>>^ Then Solʹo·mon was laid to rest with his forefathers. So they buried him in the City of David his father; and his son Re·ho·boʹam became king in his place.

'''

xref:014-2-chronicles/014-2-chronicles-008.adoc#v14-8-0[&#60; Capítulo Anterior] | <<v14-9-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-010.adoc#v14-10-0[Próximo Capítulo &#62;]