include::./index.adoc[]

[[v14-29-0]]
=== The Second of Chronicles, 29
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-29-1]]

^<<v14-29-1,1>>^ Hez·e·kiʹah became king at the age of 25, and he reigned for 29 years in Jerusalem. His mother’s name was A·biʹjah the daughter of Zech·a·riʹah.

[[v14-29-2]]

^<<v14-29-2,2>>^ He kept doing what was right in Jehovah’s eyes, just as David his forefather had done.

[[v14-29-3]]

^<<v14-29-3,3>>^ In the first year of his reign, in the first month, he opened the doors of the house of Jehovah and repaired them.

[[v14-29-4]]

^<<v14-29-4,4>>^ Then he brought the priests and the Levites and assembled them in the square to the east.

[[v14-29-5]]

^<<v14-29-5,5>>^ He said to them: “Listen to me, you Levites. Now sanctify yourselves and sanctify the house of Jehovah the God of your forefathers, and remove what is impure from the holy place.

[[v14-29-6]]

^<<v14-29-6,6>>^ For our fathers have been unfaithful and have done what was bad in the eyes of Jehovah our God. They abandoned him and turned their faces away from the tabernacle of Jehovah and turned their back on him.

[[v14-29-7]]

^<<v14-29-7,7>>^ They also closed the doors of the porch and extinguished the lamps. They stopped burning incense and offering up burnt sacrifices in the holy place to the God of Israel.

[[v14-29-8]]

^<<v14-29-8,8>>^ Therefore, Jehovah’s indignation came against Judah and Jerusalem, so that he made them an object of horror and astonishment and a cause for whistling,^&#42;1^ as you can see with your own eyes.

[NOTE]
====
. Or “mocking.”
====

[[v14-29-9]]

^<<v14-29-9,9>>^ Here our forefathers fell by the sword, and our sons, our daughters, and our wives went into captivity for this.

[[v14-29-10]]

^<<v14-29-10,10>>^ Now it is my heart’s desire to make a covenant with Jehovah the God of Israel, so that his burning anger may turn away from us.

[[v14-29-11]]

^<<v14-29-11,11>>^ My sons, now is not the time to be negligent,^&#42;1^ for Jehovah has chosen you to stand before him, to serve as his ministers, and to make his sacrifices smoke.”

[NOTE]
====
. Or “to rest.”
====

[[v14-29-12]]

^<<v14-29-12,12>>^ At that the Levites rose up: Maʹhath the son of A·maʹsai and Joel the son of Az·a·riʹah of the Koʹhath·ites; from the Me·rarʹites, Kish the son of Abʹdi and Az·a·riʹah the son of Je·halʹle·lel; from the Gerʹshon·ites, Joʹah the son of Zimʹmah and Eʹden the son of Joʹah;

[[v14-29-13]]

^<<v14-29-13,13>>^ from the sons of E·li·zaʹphan, Shimʹri and Je·uʹel; from the sons of Aʹsaph, Zech·a·riʹah and Mat·ta·niʹah;

[[v14-29-14]]

^<<v14-29-14,14>>^ from the sons of Heʹman, Je·hiʹel and Shimʹe·i; from the sons of Je·duʹthun, She·maiʹah and Uzʹzi·el.

[[v14-29-15]]

^<<v14-29-15,15>>^ Then they gathered their brothers together and sanctified themselves and came, as the king had commanded by the words of Jehovah, to cleanse the house of Jehovah.

[[v14-29-16]]

^<<v14-29-16,16>>^ The priests then went inside the house of Jehovah to do the cleansing and brought out all the uncleanness that they found in the temple of Jehovah and took it to the courtyard of the house of Jehovah. In turn the Levites took it and carried it outside to the Kidʹron Valley.

[[v14-29-17]]

^<<v14-29-17,17>>^ Thus they began the sanctification on the first day of the first month, and on the eighth day of the month they reached the porch of Jehovah. They sanctified the house of Jehovah for eight days, and on the 16th day of the first month they finished.

[[v14-29-18]]

^<<v14-29-18,18>>^ After that they went in to King Hez·e·kiʹah and said: “We have cleansed the whole house of Jehovah, the altar of burnt offering and all its utensils, and the table of the layer bread^&#42;1^ and all its utensils.

[NOTE]
====
. That is, the showbread.
====

[[v14-29-19]]

^<<v14-29-19,19>>^ And all the utensils that King Aʹhaz cast aside during his reign when he acted unfaithfully we have made ready and sanctified, and they are before the altar of Jehovah.”

[[v14-29-20]]

^<<v14-29-20,20>>^ And King Hez·e·kiʹah got up early and gathered the princes of the city together, and they went up to the house of Jehovah.

[[v14-29-21]]

^<<v14-29-21,21>>^ They brought seven bulls, seven rams, seven male lambs, and seven male goats as a sin offering for the kingdom, for the sanctuary, and for Judah. So he told the priests, the descendants of Aaron, to offer them up on the altar of Jehovah.

[[v14-29-22]]

^<<v14-29-22,22>>^ Then they slaughtered the cattle, and the priests took the blood and sprinkled it on the altar; next they slaughtered the rams and sprinkled the blood on the altar, and they slaughtered the male lambs and sprinkled the blood on the altar.

[[v14-29-23]]

^<<v14-29-23,23>>^ Then they brought the male goats of the sin offering before the king and the congregation and laid their hands on them.

[[v14-29-24]]

^<<v14-29-24,24>>^ The priests slaughtered them and made a sin offering with their blood on the altar, to make atonement for all Israel, because the king said that the burnt offering and the sin offering should be for all Israel.

[[v14-29-25]]

^<<v14-29-25,25>>^ Meanwhile, he had the Levites stationed at the house of Jehovah with cymbals, stringed instruments, and harps, by the commandment of David and of Gad the king’s visionary and of Nathan the prophet, for the commandment was from Jehovah through his prophets.

[[v14-29-26]]

^<<v14-29-26,26>>^ So the Levites were standing with the instruments of David, and the priests with the trumpets.

[[v14-29-27]]

^<<v14-29-27,27>>^ Then Hez·e·kiʹah ordered that the burnt sacrifice be offered on the altar. When the burnt offering started, the song of Jehovah started and also the trumpets, following the direction of the instruments of King David of Israel.

[[v14-29-28]]

^<<v14-29-28,28>>^ And the whole congregation bowed down while the song was sung and the trumpets were sounding—all this continued until the burnt offering was finished.

[[v14-29-29]]

^<<v14-29-29,29>>^ And as soon as they finished making the offering, the king and all those with him bowed low and prostrated themselves.

[[v14-29-30]]

^<<v14-29-30,30>>^ King Hez·e·kiʹah and the princes now told the Levites to praise Jehovah with the words of David and of Aʹsaph the visionary. So they offered praise with great rejoicing, and they bowed down and prostrated themselves.

[[v14-29-31]]

^<<v14-29-31,31>>^ Then Hez·e·kiʹah said: “Now that you have been set apart^&#42;1^ for Jehovah, come and bring sacrifices and thanksgiving offerings to the house of Jehovah.” So the congregation began to bring sacrifices and thanksgiving offerings, and everyone with a willing heart brought burnt offerings.

[NOTE]
====
. Lit., “Now you have filled your hand.”
====

[[v14-29-32]]

^<<v14-29-32,32>>^ The number of burnt offerings that the congregation brought was 70 cattle, 100 rams, 200 male lambs—all of these as a burnt offering to Jehovah—

[[v14-29-33]]

^<<v14-29-33,33>>^ and the holy offerings were 600 cattle and 3,000 of the flock.

[[v14-29-34]]

^<<v14-29-34,34>>^ But there were not enough priests to skin all the burnt offerings, so their brothers the Levites helped them out until the work was finished and until the priests could sanctify themselves, for the Levites were more conscientious^&#42;1^ about sanctifying themselves than the priests were.

[NOTE]
====
. Lit., “upright of heart.”
====

[[v14-29-35]]

^<<v14-29-35,35>>^ Also, there were many burnt offerings, as well as the fat pieces of the communion sacrifices and the drink offerings for the burnt offerings. Thus the service of the house of Jehovah was restored.^&#42;1^

[NOTE]
====
. Or “prepared.”
====

[[v14-29-36]]

^<<v14-29-36,36>>^ So Hez·e·kiʹah and all the people rejoiced over what the true God had established for the people, for this had all happened so suddenly.

'''

xref:014-2-chronicles/014-2-chronicles-028.adoc#v14-28-0[&#60; Capítulo Anterior] | <<v14-29-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-030.adoc#v14-30-0[Próximo Capítulo &#62;]