include::./index.adoc[]

[[v14-16-0]]
=== The Second of Chronicles, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-16-1]]

^<<v14-16-1,1>>^ In the 36th year of the reign of Aʹsa, King Baʹa·sha of Israel came up against Judah and began to build up^&#42;1^ Raʹmah to prevent anyone from going out or coming in to^&#42;2^ King Aʹsa of Judah.

[NOTE]
====
. Or “fortify; rebuild.”
. Or “leaving or entering the territory of.”
====

[[v14-16-2]]

^<<v14-16-2,2>>^ At that Aʹsa brought out silver and gold from the treasuries of Jehovah’s house and the king’s house^&#42;1^ and sent them to King Ben-haʹdad of Syria, who was dwelling in Damascus, saying:

[NOTE]
====
. Or “palace.”
====

[[v14-16-3]]

^<<v14-16-3,3>>^ “There is a treaty^&#42;1^ between me and you and between my father and your father. I am sending you silver and gold. Come, break your treaty^&#42;2^ with King Baʹa·sha of Israel, so that he will withdraw from me.”

[NOTE]
====
. Or “covenant.”
. Or “covenant.”
====

[[v14-16-4]]

^<<v14-16-4,4>>^ Ben-haʹdad listened to King Aʹsa and sent the chiefs of his armies against the cities of Israel, and they struck down Iʹjon, Dan, Aʹbel-maʹim, and all the storage places of the cities of Naphʹta·li.

[[v14-16-5]]

^<<v14-16-5,5>>^ When Baʹa·sha heard of it, he immediately quit building^&#42;1^ Raʹmah and abandoned his work on it.

[NOTE]
====
. Or “fortifying; rebuilding.”
====

[[v14-16-6]]

^<<v14-16-6,6>>^ King Aʹsa then took all Judah, and they carried off the stones and timbers of Raʹmah that Baʹa·sha had been building with, and with them he built up^&#42;1^ Geʹba and Mizʹpah.

[NOTE]
====
. Or “fortified; rebuilt.”
====

[[v14-16-7]]

^<<v14-16-7,7>>^ At that time Ha·naʹni the seer came to King Aʹsa of Judah and said to him: “Because you relied^&#42;1^ on the king of Syria and did not rely^&#42;2^ on Jehovah your God, the army of the king of Syria has escaped out of your hand.

[NOTE]
====
. Lit., “leaned.”
. Lit., “lean.”
====

[[v14-16-8]]

^<<v14-16-8,8>>^ Were not the E·thi·oʹpi·ans and the Libʹy·ans a very great army with many chariots and horsemen? But because you relied on Jehovah, he gave them into your hand.

[[v14-16-9]]

^<<v14-16-9,9>>^ For the eyes of Jehovah are roving about through all the earth to show his strength^&#42;1^ in behalf of those whose heart is complete toward^&#42;2^ him. You have acted foolishly in this matter; from now on there will be wars against you.”

[NOTE]
====
. Or “support.”
. Or “completely devoted to.”
====

[[v14-16-10]]

^<<v14-16-10,10>>^ However, Aʹsa became offended at the seer and put him in prison^&#42;1^ because he was enraged at him over this. And Aʹsa began to mistreat others among the people at that same time.

[NOTE]
====
. Lit., “in the house of the stocks.”
====

[[v14-16-11]]

^<<v14-16-11,11>>^ Now the history of Aʹsa, from beginning to end, is written in the Book of the Kings of Judah and of Israel.

[[v14-16-12]]

^<<v14-16-12,12>>^ In the 39th year of his reign, Aʹsa developed an ailment in his feet until he became very sick; and even in his sickness, he turned, not to Jehovah, but to the healers.

[[v14-16-13]]

^<<v14-16-13,13>>^ Then Aʹsa was laid to rest with his forefathers; he died in the 41st year of his reign.

[[v14-16-14]]

^<<v14-16-14,14>>^ So they buried him in the grand burial place that he had excavated for himself in the City of David, and they laid him on a bier that had been filled with balsam oil and different sorts of ingredients mixed into a specially made ointment. Further, they made an extraordinarily great funeral burning for him.^&#42;1^

[NOTE]
====
. Evidently, not a cremation of Asa, but a burning of spices.
====

'''

xref:014-2-chronicles/014-2-chronicles-015.adoc#v14-15-0[&#60; Capítulo Anterior] | <<v14-16-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-017.adoc#v14-17-0[Próximo Capítulo &#62;]