include::./index.adoc[]

[[v14-1-0]]
=== The Second of Chronicles, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-1-1]]

^<<v14-1-1,1>>^ Solʹo·mon the son of David grew ever stronger in his kingship, and Jehovah his God was with him and made him exceedingly great.

[[v14-1-2]]

^<<v14-1-2,2>>^ Solʹo·mon sent for all Israel, the chiefs of the thousands and of the hundreds, the judges, and all the chieftains of all Israel, the heads of the paternal houses.

[[v14-1-3]]

^<<v14-1-3,3>>^ Then Solʹo·mon and all the congregation went to the high place at Gibʹe·on, for that was where the tent of meeting of the true God was, which tent Moses the servant of Jehovah had made in the wilderness.

[[v14-1-4]]

^<<v14-1-4,4>>^ However, David had brought the Ark of the true God up from Kirʹi·ath-jeʹa·rim to the place that David had prepared for it; he had pitched a tent for it in Jerusalem.

[[v14-1-5]]

^<<v14-1-5,5>>^ And the copper altar that Bezʹal·el the son of Uʹri the son of Hur had made had been put before the tabernacle of Jehovah; and Solʹo·mon and the congregation would pray before it.^&#42;1^

[NOTE]
====
. Or “would inquire of Him there.”
====

[[v14-1-6]]

^<<v14-1-6,6>>^ Solʹo·mon now made offerings there before Jehovah, and he offered up 1,000 burnt offerings on the copper altar of the tent of meeting.

[[v14-1-7]]

^<<v14-1-7,7>>^ That night God appeared to Solʹo·mon and said to him: “Ask what you would like me to give you.”

[[v14-1-8]]

^<<v14-1-8,8>>^ At this Solʹo·mon said to God: “You have shown great loyal love toward my father David, and you have made me king in his place.

[[v14-1-9]]

^<<v14-1-9,9>>^ Now, O Jehovah God, let your promise to David my father prove faithful, for you have made me king over a people as numerous as the dust particles of the earth.

[[v14-1-10]]

^<<v14-1-10,10>>^ Give me now wisdom and knowledge to lead this people,^&#42;1^ for who can possibly judge this great people of yours?”

[NOTE]
====
. Lit., “to go out before this people and to come in.”
====

[[v14-1-11]]

^<<v14-1-11,11>>^ Then God said to Solʹo·mon: “Because this is your heart’s desire and you have not asked for wealth, riches, and honor or for the death^&#42;1^ of those hating you, nor have you asked for a long life,^&#42;2^ but you have asked for wisdom and knowledge to judge my people over whom I have made you king,

[NOTE]
====
. Or “soul.”
. Lit., “many days.”
====

[[v14-1-12]]

^<<v14-1-12,12>>^ wisdom and knowledge will be given you; but I will also give you wealth and riches and honor such as no kings before you have had and none after you will have.”

[[v14-1-13]]

^<<v14-1-13,13>>^ So Solʹo·mon came from the high place at Gibʹe·on, from before the tent of meeting, to Jerusalem; and he reigned over Israel.

[[v14-1-14]]

^<<v14-1-14,14>>^ Solʹo·mon kept accumulating chariots and horses;^&#42;1^ he had 1,400 chariots and 12,000 horses,^&#42;2^ and he kept them stationed in the chariot cities and close by the king in Jerusalem.

[NOTE]
====
. Or “horsemen.”
. Or “horsemen.”
====

[[v14-1-15]]

^<<v14-1-15,15>>^ The king made the silver and the gold in Jerusalem as plentiful as the stones, and cedarwood as plentiful as the sycamore trees in the She·pheʹlah.

[[v14-1-16]]

^<<v14-1-16,16>>^ The horses of Solʹo·mon had been imported from Egypt, and the company of the king’s merchants would obtain the horses in droves^&#42;1^ for one price.

[NOTE]
====
. Or possibly, “from Egypt and from Kue; the king’s merchants would buy them from Kue,” perhaps referring to Cilicia.
====

[[v14-1-17]]

^<<v14-1-17,17>>^ Each chariot imported from Egypt cost 600 silver pieces, and a horse cost 150; in turn, they would export them to all the kings of the Hitʹtites and the kings of Syria.

'''

xref:013-1-chronicles/013-1-chronicles-029.adoc#v13-29-0[&#60; Capítulo Anterior] | <<v14-1-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-002.adoc#v14-2-0[Próximo Capítulo &#62;]