include::./index.adoc[]

[[v14-34-0]]
=== The Second of Chronicles, 34
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-34-1]]

^<<v14-34-1,1>>^ Jo·siʹah was eight years old when he became king, and he reigned for 31 years in Jerusalem.

[[v14-34-2]]

^<<v14-34-2,2>>^ He did what was right in Jehovah’s eyes and walked in the ways of David his forefather, and he did not deviate to the right or to the left.

[[v14-34-3]]

^<<v14-34-3,3>>^ In the 8th year of his reign, while he was still a boy, he started to search for the God of David his forefather; and in the 12th year, he started to cleanse Judah and Jerusalem of the high places and the sacred poles,^&#42;1^ the graven images, and the metal statues.^&#42;2^

[NOTE]
====
. See Glossary.
. Or “molten statues.”
====

[[v14-34-4]]

^<<v14-34-4,4>>^ Further, they tore down the altars of the Baʹals in his presence, and he cut down the incense stands that were up above them. He also broke into pieces the sacred poles,^&#42;1^ the graven images, and the metal statues^&#42;2^ and reduced them to powder and sprinkled it over the graves of those who used to sacrifice to them.

[NOTE]
====
. See Glossary.
. Or “molten statues.”
====

[[v14-34-5]]

^<<v14-34-5,5>>^ And he burned the bones of priests on their altars. Thus he cleansed Judah and Jerusalem.

[[v14-34-6]]

^<<v14-34-6,6>>^ And in the cities of Ma·nasʹseh, Eʹphra·im, Simʹe·on, and clear to Naphʹta·li, in their surrounding ruins,

[[v14-34-7]]

^<<v14-34-7,7>>^ he tore down the altars and he crushed the sacred poles^&#42;1^ and the graven images, reducing them to powder; and he cut down all the incense stands in all the land of Israel, after which he returned to Jerusalem.

[NOTE]
====
. See Glossary.
====

[[v14-34-8]]

^<<v14-34-8,8>>^ In the 18th year of his reign, when he had cleansed the land and the temple,^&#42;1^ he sent Shaʹphan the son of Az·a·liʹah, Ma·a·seiʹah the chief of the city, and Joʹah the son of Joʹa·haz the recorder to repair the house of Jehovah his God.

[NOTE]
====
. Lit., “house.”
====

[[v14-34-9]]

^<<v14-34-9,9>>^ They came to Hil·kiʹah the high priest and gave him the money that had been brought to the house of God, which the Levites serving as doorkeepers had collected from Ma·nasʹseh, Eʹphra·im, and all the rest of Israel, as well as from Judah, Benjamin, and the inhabitants of Jerusalem.

[[v14-34-10]]

^<<v14-34-10,10>>^ Then they gave it to those who were appointed over the work in the house of Jehovah. In turn the workers in the house of Jehovah used it to mend and repair the house.

[[v14-34-11]]

^<<v14-34-11,11>>^ They gave it to the craftsmen and the builders to buy hewn stones and timbers for braces and to build with beams the houses that the kings of Judah had allowed to fall into ruin.

[[v14-34-12]]

^<<v14-34-12,12>>^ And the men did the work faithfully. Over them were appointed the Levites Jaʹhath and O·ba·diʹah of the Me·rarʹites, and Zech·a·riʹah and Me·shulʹlam of the Koʹhath·ites, to serve as overseers. And the Levites, all of whom were skilled musicians,

[[v14-34-13]]

^<<v14-34-13,13>>^ were in charge of the common laborers^&#42;1^ and were overseers of all those who were doing the work in every kind of service; and some of the Levites were secretaries, officers, and gatekeepers.

[NOTE]
====
. Or “the burden bearers.”
====

[[v14-34-14]]

^<<v14-34-14,14>>^ While they were taking out the money that had been brought to the house of Jehovah, Hil·kiʹah the priest found the book of Jehovah’s Law given through^&#42;1^ Moses.

[NOTE]
====
. Lit., “by the hand of.”
====

[[v14-34-15]]

^<<v14-34-15,15>>^ So Hil·kiʹah said to Shaʹphan the secretary: “I have found the book of the Law in the house of Jehovah.” With that Hil·kiʹah gave the book to Shaʹphan.

[[v14-34-16]]

^<<v14-34-16,16>>^ Then Shaʹphan brought the book to the king and told him: “Your servants are doing everything that was assigned to them.

[[v14-34-17]]

^<<v14-34-17,17>>^ They have poured out the money that was found in the house of Jehovah, and they have handed it over to the appointed men and to those doing the work.”

[[v14-34-18]]

^<<v14-34-18,18>>^ Shaʹphan the secretary also told the king: “There is a book that Hil·kiʹah the priest has given me.” Then Shaʹphan began to read from it before the king.

[[v14-34-19]]

^<<v14-34-19,19>>^ As soon as the king heard the words of the Law, he ripped his garments apart.

[[v14-34-20]]

^<<v14-34-20,20>>^ Then the king gave this order to Hil·kiʹah, A·hiʹkam the son of Shaʹphan, Abʹdon the son of Miʹcah, Shaʹphan the secretary, and A·saiʹah the king’s servant:

[[v14-34-21]]

^<<v14-34-21,21>>^ “Go, inquire of Jehovah in my behalf and in behalf of those who remain in Israel and in Judah concerning the words of the book that has been found; for Jehovah’s rage that will be poured out against us is great because our forefathers did not carry out the word of Jehovah by observing all that is written in this book.”

[[v14-34-22]]

^<<v14-34-22,22>>^ So Hil·kiʹah, along with those sent by the king, went to Hulʹdah the prophetess. She was the wife of Shalʹlum son of Tikʹvah son of Harʹhas, the caretaker of the wardrobe, and she was dwelling in the Second Quarter of Jerusalem; and they spoke to her there.

[[v14-34-23]]

^<<v14-34-23,23>>^ She said to them: “This is what Jehovah the God of Israel says, ‘Tell the man who sent you to me:

[[v14-34-24]]

^<<v14-34-24,24>>^ “This is what Jehovah says, ‘I will bring calamity on this place and its inhabitants, all the curses that are written in the book that they read before the king of Judah.

[[v14-34-25]]

^<<v14-34-25,25>>^ Because they have abandoned me and are making sacrifices smoke to other gods in order to offend me with all the works of their hands, my rage will pour out on this place and it will not be extinguished.’”

[[v14-34-26]]

^<<v14-34-26,26>>^ But to the king of Judah who sent you to inquire of Jehovah, this is what you should say to him, “This is what Jehovah the God of Israel says: ‘Regarding the words that you have heard,

[[v14-34-27]]

^<<v14-34-27,27>>^ because your heart was responsive^&#42;1^ and you humbled yourself before God on hearing his words concerning this place and its inhabitants and you humbled yourself before me and ripped your garments apart and wept before me, I also have heard you, declares Jehovah.

[NOTE]
====
. Lit., “soft.”
====

[[v14-34-28]]

^<<v14-34-28,28>>^ That is why I will gather you to your ancestors,^&#42;1^ and you will be laid in your grave in peace, and your eyes will not see all the calamity that I will bring on this place and its inhabitants.’”’”
Then they brought the reply to the king.

[NOTE]
====
. This is a poetic expression for death.
====

[[v14-34-29]]

^<<v14-34-29,29>>^ So the king sent word and summoned all the elders of Judah and Jerusalem.

[[v14-34-30]]

^<<v14-34-30,30>>^ After that the king went up to the house of Jehovah with all the men of Judah, the inhabitants of Jerusalem, the priests, the Levites—all the people, the great as well as the small. He read in their hearing all the words of the book of the covenant that had been found in the house of Jehovah.

[[v14-34-31]]

^<<v14-34-31,31>>^ The king stood in his place and made a covenant^&#42;1^ before Jehovah that he would follow Jehovah and keep his commandments, his reminders, and his regulations with all his heart and with all his soul^&#42;2^ by carrying out the words of the covenant that were written in this book.

[NOTE]
====
. Or “renewed the covenant.”
. See Glossary.
====

[[v14-34-32]]

^<<v14-34-32,32>>^ Furthermore, he had all those who were in Jerusalem and Benjamin to agree to it. And the inhabitants of Jerusalem acted according to the covenant of God, the God of their forefathers.

[[v14-34-33]]

^<<v14-34-33,33>>^ Jo·siʹah then removed all the detestable things^&#42;1^ out of all the lands that belonged to the Israelites, and he made everyone in Israel serve Jehovah their God. Throughout his lifetime^&#42;2^ they did not deviate from following Jehovah the God of their forefathers.

[NOTE]
====
. Or “idols.”
. Lit., “All his days.”
====

'''

xref:014-2-chronicles/014-2-chronicles-033.adoc#v14-33-0[&#60; Capítulo Anterior] | <<v14-34-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-035.adoc#v14-35-0[Próximo Capítulo &#62;]