include::./index.adoc[]

[[v14-23-0]]
=== The Second of Chronicles, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-23-1]]

^<<v14-23-1,1>>^ In the seventh year, Je·hoiʹa·da acted courageously and made a pact^&#42;1^ with the chiefs of hundreds, namely, Az·a·riʹah the son of Je·roʹham, Ishʹma·el the son of Je·ho·haʹnan, Az·a·riʹah the son of Oʹbed, Ma·a·seiʹah the son of A·daiʹah, and E·li·shaʹphat the son of Zichʹri.

[NOTE]
====
. Or “covenant.”
====

[[v14-23-2]]

^<<v14-23-2,2>>^ Then they went throughout Judah and gathered together the Levites from all the cities of Judah and the heads of the paternal houses of Israel. When they came to Jerusalem,

[[v14-23-3]]

^<<v14-23-3,3>>^ the entire congregation made a covenant with the king in the house of the true God, after which he said to them:
“Look! The king’s son will reign, just as Jehovah promised concerning the sons of David.

[[v14-23-4]]

^<<v14-23-4,4>>^ This is what you are to do: One third of the priests and of the Levites who will be on duty on the Sabbath will be doorkeepers;

[[v14-23-5]]

^<<v14-23-5,5>>^ another third will be at the house^&#42;1^ of the king, and the other third will be at the Gate of the Foundation, and all the people will be in the courtyards of the house of Jehovah.

[NOTE]
====
. Or “palace.”
====

[[v14-23-6]]

^<<v14-23-6,6>>^ Do not let anyone enter the house of Jehovah except the priests and the Levites who are ministering. These may enter because they are a holy group, and all the people will keep the obligation to Jehovah.

[[v14-23-7]]

^<<v14-23-7,7>>^ The Levites must surround the king on every side, each with his weapons in hand. Anyone entering the house will be put to death. Stay with the king wherever he goes.”^&#42;1^

[NOTE]
====
. Lit., “when he goes out and when he comes in.”
====

[[v14-23-8]]

^<<v14-23-8,8>>^ The Levites and all Judah did exactly what Je·hoiʹa·da the priest had commanded. So each one took his men who were on duty on the Sabbath, together with those who were off duty on the Sabbath, for Je·hoiʹa·da the priest had not dismissed the divisions from their duty.

[[v14-23-9]]

^<<v14-23-9,9>>^ Je·hoiʹa·da the priest then gave the chiefs of hundreds the spears and the bucklers^&#42;1^ and the circular shields that had belonged to King David, which were in the house of the true God.

[NOTE]
====
. A small shield, often carried by archers.
====

[[v14-23-10]]

^<<v14-23-10,10>>^ He then stationed all the people, each with his weapon^&#42;1^ in hand, from the right side of the house to the left side of the house, by the altar and by the house, all around the king.

[NOTE]
====
. Or “missile.”
====

[[v14-23-11]]

^<<v14-23-11,11>>^ Then they brought the king’s son out and put on him the crown^&#42;1^ and the Testimony^&#42;2^ and made him king, and Je·hoiʹa·da and his sons anointed him. Then they said: “Long live the king!”

[NOTE]
====
. Or “diadem.”
. Possibly a scroll containing the Law of God.
====

[[v14-23-12]]

^<<v14-23-12,12>>^ When Ath·a·liʹah heard the sound of the people running and praising the king, she immediately came to the people at the house of Jehovah.

[[v14-23-13]]

^<<v14-23-13,13>>^ Then she saw the king standing there by his pillar at the entrance. The princes and the trumpeters were with the king, and all the people of the land were rejoicing and blowing the trumpets, and the singers with musical instruments were leading^&#42;1^ the praises. At this Ath·a·liʹah ripped her garments apart and cried out: “Conspiracy! Conspiracy!”

[NOTE]
====
. Or “giving the signal for.”
====

[[v14-23-14]]

^<<v14-23-14,14>>^ But Je·hoiʹa·da the priest brought out the chiefs of hundreds, those appointed over the army, and said to them: “Take her out from among the ranks, and if anyone follows her, put him to death with the sword!” For the priest had said: “Do not put her to death in the house of Jehovah.”

[[v14-23-15]]

^<<v14-23-15,15>>^ So they seized her, and when she reached the entrance of the Horse Gate of the king’s house,^&#42;1^ they immediately put her to death there.

[NOTE]
====
. Or “palace.”
====

[[v14-23-16]]

^<<v14-23-16,16>>^ Then Je·hoiʹa·da made a covenant between himself and all the people and the king, that they would continue as the people of Jehovah.

[[v14-23-17]]

^<<v14-23-17,17>>^ After that all the people came to the house^&#42;1^ of Baʹal and tore it down, and they smashed his altars and his images, and they killed Matʹtan the priest of Baʹal in front of the altars.

[NOTE]
====
. Or “temple.”
====

[[v14-23-18]]

^<<v14-23-18,18>>^ Then Je·hoiʹa·da put the oversight of the house of Jehovah in the hands of the priests and the Levites, whom David had assigned in divisions over the house of Jehovah to offer up the burnt sacrifices of Jehovah according to what is written in the Law of Moses, with rejoicing and with song, as directed by^&#42;1^ David.

[NOTE]
====
. Lit., “by the hands of.”
====

[[v14-23-19]]

^<<v14-23-19,19>>^ He also stationed the gatekeepers by the gates of the house of Jehovah, so that no one unclean in any respect could enter.

[[v14-23-20]]

^<<v14-23-20,20>>^ He now took the chiefs of hundreds, the nobles, the rulers of the people, and all the people of the land and escorted the king down from the house of Jehovah. Then they came through the upper gate to the king’s house^&#42;1^ and seated the king on the throne of the kingdom.

[NOTE]
====
. Or “palace.”
====

[[v14-23-21]]

^<<v14-23-21,21>>^ So all the people of the land rejoiced and the city was quiet, for they had put Ath·a·liʹah to death with the sword.

'''

xref:014-2-chronicles/014-2-chronicles-022.adoc#v14-22-0[&#60; Capítulo Anterior] | <<v14-23-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-024.adoc#v14-24-0[Próximo Capítulo &#62;]