include::./index.adoc[]

[[v14-24-0]]
=== The Second of Chronicles, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-24-1]]

^<<v14-24-1,1>>^ Je·hoʹash was seven years old when he became king, and he reigned for 40 years in Jerusalem. His mother’s name was Zibʹi·ah from Beʹer-sheʹba.

[[v14-24-2]]

^<<v14-24-2,2>>^ Je·hoʹash continued doing what was right in Jehovah’s eyes all the days of Je·hoiʹa·da the priest.

[[v14-24-3]]

^<<v14-24-3,3>>^ Je·hoiʹa·da chose two wives for him, and he became father to sons and daughters.

[[v14-24-4]]

^<<v14-24-4,4>>^ Afterward it was the heart’s desire of Je·hoʹash to renovate the house of Jehovah.

[[v14-24-5]]

^<<v14-24-5,5>>^ So he gathered the priests and the Levites together and said to them: “Go out to the cities of Judah and collect money from all Israel to repair the house of your God from year to year; and you should act quickly in the matter.” But the Levites did not act quickly.

[[v14-24-6]]

^<<v14-24-6,6>>^ So the king called Je·hoiʹa·da the chief and said to him: “Why have you not required the Levites to bring in from Judah and Jerusalem the sacred tax ordered by Moses the servant of Jehovah, the sacred tax of the congregation of Israel, for the tent of the Testimony?

[[v14-24-7]]

^<<v14-24-7,7>>^ For the sons of Ath·a·liʹah, that wicked woman, had broken into the house of the true God, and they had used all the holy things of the house of Jehovah for the Baʹals.”

[[v14-24-8]]

^<<v14-24-8,8>>^ Then, at the king’s order, a chest was made and placed outside at the gate of the house of Jehovah.

[[v14-24-9]]

^<<v14-24-9,9>>^ After that a proclamation was issued throughout Judah and Jerusalem to bring to Jehovah the sacred tax that Moses the servant of the true God had imposed on Israel in the wilderness.

[[v14-24-10]]

^<<v14-24-10,10>>^ All the princes and all the people rejoiced, and they kept bringing contributions and dropping them into the chest until it was full.^&#42;1^

[NOTE]
====
. Or possibly, “until they all had given.”
====

[[v14-24-11]]

^<<v14-24-11,11>>^ Whenever the Levites brought the chest in to be turned over to the king and they saw that there was a great deal of money in it, the secretary of the king and the commissioner of the chief priest would come and empty the chest, and then they would take it back to its place. That was what they did from day to day, and they gathered money in abundance.

[[v14-24-12]]

^<<v14-24-12,12>>^ Then the king and Je·hoiʹa·da would give it to those supervising the work of the service of Jehovah’s house, and they would hire the stonecutters and the craftsmen for renovating Jehovah’s house, and also workers in iron and copper to repair Jehovah’s house.

[[v14-24-13]]

^<<v14-24-13,13>>^ And those supervising the work got it started, and the repair work progressed under their supervision, and they restored the house of the true God to its proper condition and reinforced it.

[[v14-24-14]]

^<<v14-24-14,14>>^ And as soon as they finished, they brought the money that was left over to the king and Je·hoiʹa·da, and they used it to make utensils for the house of Jehovah, utensils for the ministry and for making offerings and cups and utensils of gold and of silver. And they would offer up burnt sacrifices at the house of Jehovah regularly all the days of Je·hoiʹa·da.

[[v14-24-15]]

^<<v14-24-15,15>>^ When Je·hoiʹa·da was old and satisfied with years, he died; he was 130 years old at his death.

[[v14-24-16]]

^<<v14-24-16,16>>^ So they buried him in the City of David along with the kings, because he had done good in Israel with respect to the true God and His house.

[[v14-24-17]]

^<<v14-24-17,17>>^ After Je·hoiʹa·da’s death the princes of Judah came and bowed down to the king, and the king listened to them.

[[v14-24-18]]

^<<v14-24-18,18>>^ They abandoned the house of Jehovah the God of their forefathers and began serving the sacred poles^&#42;1^ and the idols, so that God’s anger came^&#42;2^ against Judah and Jerusalem because of their guilt.

[NOTE]
====
. See Glossary.
. Lit., “there was anger.”
====

[[v14-24-19]]

^<<v14-24-19,19>>^ He kept sending prophets among them to bring them back to Jehovah, and they kept warning^&#42;1^ them, but they refused to listen.

[NOTE]
====
. Or “bearing witness against.”
====

[[v14-24-20]]

^<<v14-24-20,20>>^ God’s spirit came upon^&#42;1^ Zech·a·riʹah the son of Je·hoiʹa·da the priest, and he stood above the people and said to them: “This is what the true God says, ‘Why are you violating the commandments of Jehovah? You will not be successful! Because you have abandoned Jehovah, he will, in turn, abandon you.’”

[NOTE]
====
. Lit., “clothed.”
====

[[v14-24-21]]

^<<v14-24-21,21>>^ But they conspired against him and stoned him at the king’s order in the courtyard of Jehovah’s house.

[[v14-24-22]]

^<<v14-24-22,22>>^ Thus King Je·hoʹash did not remember the loyal love that his father^&#42;1^ Je·hoiʹa·da had shown toward him, and he killed his son, who said as he was dying: “May Jehovah see to it and call you to account.”

[NOTE]
====
. That is, Zechariah’s father.
====

[[v14-24-23]]

^<<v14-24-23,23>>^ At the beginning of the year^&#42;1^ the Syrian army came up against Je·hoʹash, and they invaded Judah and Jerusalem. Then they did away with all the princes of the people, and they sent all their spoil to the king of Damascus.

[NOTE]
====
. Lit., “the turn of the year.”
====

[[v14-24-24]]

^<<v14-24-24,24>>^ For although the invading Syrian army had a small number of men, Jehovah handed over to them a very large army, because they had abandoned Jehovah the God of their forefathers; so they^&#42;1^ executed judgment on Je·hoʹash.

[NOTE]
====
. That is, the Syrians.
====

[[v14-24-25]]

^<<v14-24-25,25>>^ And when they withdrew from him (for they left him severely wounded^&#42;1^), his own servants conspired against him because he had shed the blood of the sons^&#42;2^ of Je·hoiʹa·da the priest. They killed him on his own bed. So he died and they buried him in the City of David, but they did not bury him in the burial places of the kings.

[NOTE]
====
. Or “with many diseases.”
. Or “son.” Possibly the plural form denotes excellence.
====

[[v14-24-26]]

^<<v14-24-26,26>>^ These were the conspirators against him: Zaʹbad the son of Shimʹe·ath the Amʹmon·it·ess and Je·hozʹa·bad the son of Shimʹrith the Moʹab·i·tess.

[[v14-24-27]]

^<<v14-24-27,27>>^ Regarding his sons and the many pronouncements against him and the renovation^&#42;1^ of the house of the true God, all these things are recorded in the writings^&#42;2^ of the Book of the Kings. And his son Am·a·ziʹah became king in his place.

[NOTE]
====
. Lit., “founding.”
. Or “exposition; commentary.”
====

'''

xref:014-2-chronicles/014-2-chronicles-023.adoc#v14-23-0[&#60; Capítulo Anterior] | <<v14-24-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-025.adoc#v14-25-0[Próximo Capítulo &#62;]