include::./index.adoc[]

[[v14-17-0]]
=== The Second of Chronicles, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-17-1]]

^<<v14-17-1,1>>^ And his son Je·hoshʹa·phat became king in his place, and he strengthened his position over Israel.

[[v14-17-2]]

^<<v14-17-2,2>>^ He stationed military forces in all the fortified cities of Judah and put garrisons in the land of Judah and in the cities of Eʹphra·im that Aʹsa his father had captured.

[[v14-17-3]]

^<<v14-17-3,3>>^ Jehovah continued with Je·hoshʹa·phat because he walked in the former ways of his forefather David and did not search for the Baʹals.

[[v14-17-4]]

^<<v14-17-4,4>>^ For he searched for the God of his father and followed^&#42;1^ his commandment and not the practices of Israel.

[NOTE]
====
. Lit., “walked in.”
====

[[v14-17-5]]

^<<v14-17-5,5>>^ Jehovah kept the kingdom firmly established in his hand; and all Judah continued to give gifts to Je·hoshʹa·phat, and he had riches and glory in abundance.

[[v14-17-6]]

^<<v14-17-6,6>>^ His heart became bold in the ways of Jehovah, and he even removed the high places and the sacred poles^&#42;1^ from Judah.

[NOTE]
====
. See Glossary.
====

[[v14-17-7]]

^<<v14-17-7,7>>^ In the third year of his reign he sent for his princes, Ben-haʹil, O·ba·diʹah, Zech·a·riʹah, Ne·thanʹel, and Mi·caiʹah, to teach in the cities of Judah.

[[v14-17-8]]

^<<v14-17-8,8>>^ There were Levites with them: She·maiʹah, Neth·a·niʹah, Zeb·a·diʹah, Asʹa·hel, She·mirʹa·moth, Je·honʹa·than, Ad·o·niʹjah, To·biʹjah, and Tob-ad·o·niʹjah, and along with them E·lishʹa·ma and Je·hoʹram the priests.

[[v14-17-9]]

^<<v14-17-9,9>>^ They began teaching in Judah, taking with them the book of Jehovah’s Law, and they went around through all the cities of Judah teaching among the people.

[[v14-17-10]]

^<<v14-17-10,10>>^ And the dread of Jehovah came upon all the kingdoms of the lands surrounding Judah, and they did not fight against Je·hoshʹa·phat.

[[v14-17-11]]

^<<v14-17-11,11>>^ And the Phi·lisʹtines brought to Je·hoshʹa·phat gifts and money as tribute. The Arabs brought him 7,700 rams and 7,700 male goats from their flocks.

[[v14-17-12]]

^<<v14-17-12,12>>^ Je·hoshʹa·phat grew greater and greater, and he continued building fortified places and storage cities in Judah.

[[v14-17-13]]

^<<v14-17-13,13>>^ He carried out extensive projects in the cities of Judah, and he had soldiers, mighty warriors, in Jerusalem.

[[v14-17-14]]

^<<v14-17-14,14>>^ These were grouped by their paternal houses: of Judah the chiefs of thousands, Adʹnah the chief, and with him were 300,000 mighty warriors.

[[v14-17-15]]

^<<v14-17-15,15>>^ And under his command was Je·ho·haʹnan the chief, and with him were 280,000.

[[v14-17-16]]

^<<v14-17-16,16>>^ And also under his command was Am·a·siʹah the son of Zichʹri, who volunteered for Jehovah’s service, and with him were 200,000 mighty warriors.

[[v14-17-17]]

^<<v14-17-17,17>>^ And out of Benjamin was E·liʹa·da, a mighty warrior, and with him were 200,000 men equipped with the bow and shield.

[[v14-17-18]]

^<<v14-17-18,18>>^ And under his command was Je·hozʹa·bad, and with him were 180,000 men equipped for the army.

[[v14-17-19]]

^<<v14-17-19,19>>^ These were ministering to the king in addition to those whom the king put in the fortified cities throughout all Judah.

'''

xref:014-2-chronicles/014-2-chronicles-016.adoc#v14-16-0[&#60; Capítulo Anterior] | <<v14-17-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-018.adoc#v14-18-0[Próximo Capítulo &#62;]