include::./index.adoc[]

[[v14-4-0]]
=== The Second of Chronicles, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-4-1]]

^<<v14-4-1,1>>^ Then he made the copper altar, 20 cubits long, 20 cubits wide, and 10 cubits high.

[[v14-4-2]]

^<<v14-4-2,2>>^ He made the Sea^&#42;1^ of cast metal. It was circular in shape, 10 cubits from brim to brim and 5 cubits high, and it took a measuring line 30 cubits long to encircle it.

[NOTE]
====
. Or “reservoir.”
====

[[v14-4-3]]

^<<v14-4-3,3>>^ And there were ornamental gourds under it, completely encircling it, ten to a cubit all around the Sea. The gourds were in two rows and were cast in one piece with it.

[[v14-4-4]]

^<<v14-4-4,4>>^ It stood on 12 bulls, 3 facing north, 3 facing west, 3 facing south, and 3 facing east; and the Sea rested on them, and all their hindquarters were toward the center.

[[v14-4-5]]

^<<v14-4-5,5>>^ And its thickness was a handbreadth;^&#42;1^ and its brim was made like the brim of a cup, like a lily blossom. The reservoir could hold^&#42;2^ 3,000 bath measures.^&#42;3^

[NOTE]
====
. About 7.4 cm (2.9 in.). See App. B14.
. Or “Its capacity was.”
. A bath equaled 22 L (5.81 gal). See App. B14.
====

[[v14-4-6]]

^<<v14-4-6,6>>^ Further, he made ten basins for washing and put five to the right and five to the left. They would rinse in them the things used for the burnt offering. But the Sea was for the priests for washing.

[[v14-4-7]]

^<<v14-4-7,7>>^ He then made ten lampstands of gold, as specified, and put them in the temple, five on the right and five on the left.

[[v14-4-8]]

^<<v14-4-8,8>>^ He also made ten tables and placed them in the temple, five on the right and five on the left; and he made 100 golden bowls.

[[v14-4-9]]

^<<v14-4-9,9>>^ Then he made the courtyard of the priests and the great court^&#42;1^ and the doors for the court, and he overlaid their doors with copper.

[NOTE]
====
. Or “enclosure.”
====

[[v14-4-10]]

^<<v14-4-10,10>>^ And he placed the Sea on the right side, toward the southeast.

[[v14-4-11]]

^<<v14-4-11,11>>^ Hiʹram also made the cans, the shovels, and the bowls.
So Hiʹram finished the work that he did for King Solʹo·mon on the house of the true God:

[[v14-4-12]]

^<<v14-4-12,12>>^ the two pillars and the bowl-shaped capitals that were on top of the two pillars; the two networks to cover the two bowl-shaped capitals that were on top of the pillars;

[[v14-4-13]]

^<<v14-4-13,13>>^ the 400 pomegranates for the two networks, two rows of pomegranates for each network, to cover the two bowl-shaped capitals that were on the pillars;

[[v14-4-14]]

^<<v14-4-14,14>>^ the ten carriages^&#42;1^ and the ten basins on the carriages;

[NOTE]
====
. Or “water carts.”
====

[[v14-4-15]]

^<<v14-4-15,15>>^ the Sea and the 12 bulls beneath it;

[[v14-4-16]]

^<<v14-4-16,16>>^ and the cans, the shovels, the forks, and all their utensils Hiʹram-aʹbiv made of polished copper for King Solʹo·mon for the house of Jehovah.

[[v14-4-17]]

^<<v14-4-17,17>>^ The king cast them in the district of the Jordan in the thick clay between Sucʹcoth and Zerʹe·dah.

[[v14-4-18]]

^<<v14-4-18,18>>^ Solʹo·mon made all these utensils in great quantities; the weight of the copper was not ascertained.

[[v14-4-19]]

^<<v14-4-19,19>>^ Solʹo·mon made all the utensils for the house of the true God: the altar of gold; the tables with the showbread on them;

[[v14-4-20]]

^<<v14-4-20,20>>^ the lampstands and their lamps of pure gold, to burn before the innermost room according to the requirements;

[[v14-4-21]]

^<<v14-4-21,21>>^ and the blossoms, the lamps, and the snuffers,^&#42;1^ of gold, the purest gold;

[NOTE]
====
. Or “tongs.”
====

[[v14-4-22]]

^<<v14-4-22,22>>^ the extinguishers, the bowls, the cups, and the fire holders, of pure gold; and the entrance of the house, its inner doors for the Most Holy, and the doors of the house of the temple, of gold.

'''

xref:014-2-chronicles/014-2-chronicles-003.adoc#v14-3-0[&#60; Capítulo Anterior] | <<v14-4-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-005.adoc#v14-5-0[Próximo Capítulo &#62;]