include::./index.adoc[]

[[v14-36-0]]
=== The Second of Chronicles, 36
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-36-1]]

^<<v14-36-1,1>>^ Then the people of the land took Jo·siʹah’s son Je·hoʹa·haz and made him king in Jerusalem in place of his father.

[[v14-36-2]]

^<<v14-36-2,2>>^ Je·hoʹa·haz was 23 years old when he became king, and he reigned for three months in Jerusalem.

[[v14-36-3]]

^<<v14-36-3,3>>^ However, the king of Egypt deposed him in Jerusalem and fined the land 100 silver talents^&#42;1^ and a gold talent.

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v14-36-4]]

^<<v14-36-4,4>>^ Furthermore, the king of Egypt made Je·hoʹa·haz’ brother E·liʹa·kim king over Judah and Jerusalem and changed his name to Je·hoiʹa·kim; but Neʹcho took his brother Je·hoʹa·haz and brought him to Egypt.

[[v14-36-5]]

^<<v14-36-5,5>>^ Je·hoiʹa·kim was 25 years old when he became king, and he reigned for 11 years in Jerusalem. He continued to do what was bad in the eyes of Jehovah his God.

[[v14-36-6]]

^<<v14-36-6,6>>^ King Neb·u·chad·nezʹzar of Babylon came up against him in order to bind him with two copper fetters to take him off to Babylon.

[[v14-36-7]]

^<<v14-36-7,7>>^ And Neb·u·chad·nezʹzar took some of the utensils of the house of Jehovah to Babylon and put them in his palace in Babylon.

[[v14-36-8]]

^<<v14-36-8,8>>^ As for the rest of the history of Je·hoiʹa·kim, the detestable things that he did and what was found against him, it is written in the Book of the Kings of Israel and of Judah; and his son Je·hoiʹa·chin became king in his place.

[[v14-36-9]]

^<<v14-36-9,9>>^ Je·hoiʹa·chin was 18 years old when he became king, and he reigned for three months and ten days in Jerusalem; and he continued to do what was bad in Jehovah’s eyes.

[[v14-36-10]]

^<<v14-36-10,10>>^ At the start of the year,^&#42;1^ King Neb·u·chad·nezʹzar sent to have him brought to Babylon, along with valuable articles of the house of Jehovah. And he made his father’s brother Zed·e·kiʹah king over Judah and Jerusalem.

[NOTE]
====
. Possibly, in the spring.
====

[[v14-36-11]]

^<<v14-36-11,11>>^ Zed·e·kiʹah was 21 years old when he became king, and he reigned for 11 years in Jerusalem.

[[v14-36-12]]

^<<v14-36-12,12>>^ He continued to do what was bad in the eyes of Jehovah his God. He did not humble himself before the prophet Jeremiah, who spoke at the order of Jehovah.

[[v14-36-13]]

^<<v14-36-13,13>>^ He also rebelled against King Neb·u·chad·nezʹzar, who had made him take an oath by God, and he remained stubborn^&#42;1^ and hardhearted and refused to turn to Jehovah the God of Israel.

[NOTE]
====
. Lit., “he hardened his neck.”
====

[[v14-36-14]]

^<<v14-36-14,14>>^ All the chiefs of the priests as well as the people were exceedingly unfaithful, practicing all the detestable things of the nations, and they defiled the house of Jehovah that he had sanctified in Jerusalem.

[[v14-36-15]]

^<<v14-36-15,15>>^ Jehovah the God of their forefathers kept warning them by means of his messengers, warning them again and again, because he felt compassion for his people and for his dwelling place.

[[v14-36-16]]

^<<v14-36-16,16>>^ But they kept ridiculing the messengers of the true God, and they despised his words and mocked his prophets, until the rage of Jehovah came up against his people, until they were beyond healing.

[[v14-36-17]]

^<<v14-36-17,17>>^ So he brought against them the king of the Chal·deʹans, who killed their young men with the sword in the house of their sanctuary; he felt no compassion for young man or virgin, old or infirm. God gave everything into his hand.

[[v14-36-18]]

^<<v14-36-18,18>>^ All the utensils of the house of the true God, great and small, as well as the treasures of the house of Jehovah and the treasures of the king and his princes, everything he brought to Babylon.

[[v14-36-19]]

^<<v14-36-19,19>>^ He burned down the house of the true God, tore down the wall of Jerusalem, burned all its fortified towers with fire, and destroyed everything of value.

[[v14-36-20]]

^<<v14-36-20,20>>^ He carried off captive to Babylon those who escaped the sword, and they became servants to him and his sons until the kingdom^&#42;1^ of Persia began to reign,

[NOTE]
====
. Or “royalty.”
====

[[v14-36-21]]

^<<v14-36-21,21>>^ to fulfill Jehovah’s word spoken by Jeremiah, until the land had paid off its sabbaths. All the days it lay desolate it kept sabbath, to fulfill 70 years.

[[v14-36-22]]

^<<v14-36-22,22>>^ In the first year of King Cyrus of Persia, in order that Jehovah’s word spoken by Jeremiah would be fulfilled, Jehovah stirred the spirit of King Cyrus of Persia to make a proclamation throughout his kingdom, which he also put in writing, saying:

[[v14-36-23]]

^<<v14-36-23,23>>^ “This is what King Cyrus of Persia says, ‘Jehovah the God of the heavens has given me all the kingdoms of the earth, and he has commissioned me to build him a house in Jerusalem, which is in Judah. Whoever there is among you of all his people, may Jehovah his God be with him, and let him go up.’”

'''

xref:014-2-chronicles/014-2-chronicles-035.adoc#v14-35-0[&#60; Capítulo Anterior] | <<v14-36-0,Topo>> | xref:015-ezra/015-ezra-001.adoc#v15-1-0[Próximo Capítulo &#62;]