include::./index.adoc[]

[[v14-20-0]]
=== The Second of Chronicles, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-20-1]]

^<<v14-20-1,1>>^ Afterward the Moʹab·ites and the Amʹmon·ites, together with some of the Amʹmon·im,^&#42;1^ came to wage war against Je·hoshʹa·phat.

[NOTE]
====
. Or possibly, “the Meunites.”
====

[[v14-20-2]]

^<<v14-20-2,2>>^ So Je·hoshʹa·phat was told: “A large crowd has come against you from the region of the sea,^&#42;1^ from Eʹdom, and there they are in Hazʹa·zon-taʹmar, that is, En-gedʹi.”

[NOTE]
====
. Evidently, the Dead Sea.
====

[[v14-20-3]]

^<<v14-20-3,3>>^ At that Je·hoshʹa·phat became afraid, and he resolved^&#42;1^ to search for Jehovah. So he proclaimed a fast for all Judah.

[NOTE]
====
. Lit., “set his face.”
====

[[v14-20-4]]

^<<v14-20-4,4>>^ The people of Judah then gathered together to inquire of Jehovah; they came from all the cities of Judah to consult Jehovah.

[[v14-20-5]]

^<<v14-20-5,5>>^ Then Je·hoshʹa·phat stood up in the congregation of Judah and Jerusalem in the house of Jehovah before the new courtyard,

[[v14-20-6]]

^<<v14-20-6,6>>^ and he said:
“O Jehovah the God of our forefathers, are you not God in the heavens; do you not have dominion over all the kingdoms of the nations? In your hand are power and might, and no one can stand against you.

[[v14-20-7]]

^<<v14-20-7,7>>^ O our God, did you not drive away the inhabitants of this land from before your people Israel and then give it as a lasting possession to the offspring^&#42;1^ of your friend Abraham?

[NOTE]
====
. Lit., “seed.”
====

[[v14-20-8]]

^<<v14-20-8,8>>^ And they settled in it, and they built for you there a sanctuary for your name, saying,

[[v14-20-9]]

^<<v14-20-9,9>>^ ‘If disaster should come on us, whether by sword, adverse judgment, pestilence, or famine, let us stand before this house and before you (for your name is in this house) and call to you for help out of our distress, and may you hear and save us.’

[[v14-20-10]]

^<<v14-20-10,10>>^ Now here are the men of Amʹmon, Moʹab, and the mountainous region of Seʹir, whom you did not allow Israel to invade when they came out of the land of Egypt. They turned away from them and did not annihilate them.

[[v14-20-11]]

^<<v14-20-11,11>>^ Now they are repaying us by coming in to drive us out from your possession that you gave us as an inheritance.

[[v14-20-12]]

^<<v14-20-12,12>>^ O our God, will you not execute judgment on them? For we are powerless before this large crowd that is coming against us; and we do not know what we should do, but our eyes are toward you.”

[[v14-20-13]]

^<<v14-20-13,13>>^ Meanwhile, all those of Judah were standing before Jehovah, along with their little ones, their wives, and their children.^&#42;1^

[NOTE]
====
. Lit., “sons.”
====

[[v14-20-14]]

^<<v14-20-14,14>>^ Then in the middle of the congregation, the spirit of Jehovah came upon Ja·ha·ziʹel son of Zech·a·riʹah son of Be·naiʹah son of Je·iʹel son of Mat·ta·niʹah the Levite of the sons of Aʹsaph.

[[v14-20-15]]

^<<v14-20-15,15>>^ He said: “Pay attention, all Judah and you inhabitants of Jerusalem and King Je·hoshʹa·phat! Here is what Jehovah says to you, ‘Do not be afraid or be terrified because of this large crowd, for the battle is not yours but God’s.

[[v14-20-16]]

^<<v14-20-16,16>>^ Tomorrow go down against them. They will be coming up by the pass of Ziz, and you will find them at the end of the valley^&#42;1^ before the wilderness of Je·ruʹel.

[NOTE]
====
. Or “wadi.”
====

[[v14-20-17]]

^<<v14-20-17,17>>^ You will not need to fight this battle. Take your position, stand still, and see the salvation of Jehovah in your behalf.^&#42;1^ O Judah and Jerusalem, do not be afraid or be terrified. Tomorrow go out against them, and Jehovah will be with you.’”

[NOTE]
====
. Or “see how Jehovah rescues you.”
====

[[v14-20-18]]

^<<v14-20-18,18>>^ At once Je·hoshʹa·phat bowed low with his face to the ground, and all Judah and the inhabitants of Jerusalem fell down before Jehovah to worship Jehovah.

[[v14-20-19]]

^<<v14-20-19,19>>^ Then the Levites who were descendants of the Koʹhath·ites and the Korʹah·ites rose up to praise Jehovah the God of Israel with a very loud voice.

[[v14-20-20]]

^<<v14-20-20,20>>^ They rose up early the next morning and went out to the wilderness of Te·koʹa. As they went out, Je·hoshʹa·phat stood up and said: “Listen to me, O Judah and you inhabitants of Jerusalem! Put faith in Jehovah your God so that you may be able to stand firm.^&#42;1^ Put faith in his prophets, and you will be successful.”

[NOTE]
====
. Or “to endure.”
====

[[v14-20-21]]

^<<v14-20-21,21>>^ After he consulted with the people, he appointed men to sing to Jehovah and to offer praise in holy adornment as they went out ahead of the armed men, saying: “Give thanks to Jehovah, for his loyal love endures forever.”

[[v14-20-22]]

^<<v14-20-22,22>>^ When they began joyfully singing praises, Jehovah set an ambush against the men of Amʹmon, Moʹab, and the mountainous region of Seʹir who were invading Judah, and they struck each other down.

[[v14-20-23]]

^<<v14-20-23,23>>^ And the Amʹmon·ites and the Moʹab·ites turned against the inhabitants of the mountainous region of Seʹir to destroy and annihilate them; and when they finished with the inhabitants of Seʹir, they helped to destroy one another.

[[v14-20-24]]

^<<v14-20-24,24>>^ But when Judah came to the watchtower of the wilderness and looked toward the crowd, there they saw their carcasses fallen to the ground; there were no survivors.

[[v14-20-25]]

^<<v14-20-25,25>>^ So Je·hoshʹa·phat and his people came to carry off the spoil from them, and they found among them an abundance of goods, clothing, and desirable articles, which they stripped off for themselves until they could carry no more. It took three days to carry off the spoil, for it was abundant.

[[v14-20-26]]

^<<v14-20-26,26>>^ On the fourth day they congregated together at the Valley^&#42;1^ of Berʹa·cah, for there they praised^&#42;2^ Jehovah. That is why they named that place Valley of Berʹa·cah^&#42;3^—until today.

[NOTE]
====
. Or “Low Plain.”
. Lit., “blessed.”
. Meaning “Blessing.”
====

[[v14-20-27]]

^<<v14-20-27,27>>^ Then all the men of Judah and Jerusalem, with Je·hoshʹa·phat at their head, returned to Jerusalem with rejoicing, for Jehovah had made them rejoice over their enemies.

[[v14-20-28]]

^<<v14-20-28,28>>^ So they came into Jerusalem with stringed instruments, harps, and trumpets and went to the house of Jehovah.

[[v14-20-29]]

^<<v14-20-29,29>>^ And the dread of God came upon all the kingdoms of the lands when they heard that Jehovah had fought against the enemies of Israel.

[[v14-20-30]]

^<<v14-20-30,30>>^ Thus the kingdom of Je·hoshʹa·phat had no disturbance, and his God continued to give him rest on every side.

[[v14-20-31]]

^<<v14-20-31,31>>^ And Je·hoshʹa·phat continued reigning over Judah. He was 35 years old when he became king, and he reigned for 25 years in Jerusalem. His mother’s name was A·zuʹbah the daughter of Shilʹhi.

[[v14-20-32]]

^<<v14-20-32,32>>^ He kept walking in the way of his father Aʹsa. He did not deviate from it, and he did what was right in Jehovah’s eyes.

[[v14-20-33]]

^<<v14-20-33,33>>^ However, the high places were not removed, and the people had not yet prepared their heart for the God of their forefathers.

[[v14-20-34]]

^<<v14-20-34,34>>^ As for the rest of the history of Je·hoshʹa·phat, from beginning to end, there it is written among the words of Jeʹhu the son of Ha·naʹni, which were included in the Book of the Kings of Israel.

[[v14-20-35]]

^<<v14-20-35,35>>^ After this King Je·hoshʹa·phat of Judah made an alliance with King A·ha·ziʹah of Israel, who acted wickedly.

[[v14-20-36]]

^<<v14-20-36,36>>^ So he made him his partner in making ships to go to Tarʹshish, and they built the ships in Eʹzi·on-geʹber.

[[v14-20-37]]

^<<v14-20-37,37>>^ However, E·li·eʹzer the son of Dod·avʹa·hu of Ma·reʹsha spoke prophetically against Je·hoshʹa·phat, saying: “Because you have made an alliance with A·ha·ziʹah, Jehovah will destroy your works.” So the ships were wrecked, and they were unable to go to Tarʹshish.

'''

xref:014-2-chronicles/014-2-chronicles-019.adoc#v14-19-0[&#60; Capítulo Anterior] | <<v14-20-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-021.adoc#v14-21-0[Próximo Capítulo &#62;]