include::./index.adoc[]

[[v14-18-0]]
=== The Second of Chronicles, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-18-1]]

^<<v14-18-1,1>>^ Je·hoshʹa·phat had riches and glory in abundance, but he made a marriage alliance with Aʹhab.

[[v14-18-2]]

^<<v14-18-2,2>>^ So years later he went down to Aʹhab at Sa·marʹi·a, and Aʹhab sacrificed sheep and cattle in abundance for him and for the people with him. And he urged^&#42;1^ him to go up against Raʹmoth-gilʹe·ad.

[NOTE]
====
. Or “persuaded.”
====

[[v14-18-3]]

^<<v14-18-3,3>>^ Then King Aʹhab of Israel said to King Je·hoshʹa·phat of Judah: “Will you go with me to Raʹmoth-gilʹe·ad?” He replied to him: “I am the same as you, and my people are the same as your people and will support you in the war.”

[[v14-18-4]]

^<<v14-18-4,4>>^ But Je·hoshʹa·phat said to the king of Israel: “First inquire, please, for the word of Jehovah.”

[[v14-18-5]]

^<<v14-18-5,5>>^ So the king of Israel gathered the prophets together, 400 men, and said to them: “Should we go to war against Raʹmoth-gilʹe·ad, or should I refrain?” They said: “Go up, and the true God will give it into the king’s hand.”

[[v14-18-6]]

^<<v14-18-6,6>>^ Je·hoshʹa·phat then said: “Is there not here a prophet of Jehovah? Let us also inquire through him.”

[[v14-18-7]]

^<<v14-18-7,7>>^ At that the king of Israel said to Je·hoshʹa·phat: “There is still one more man through whom we can inquire of Jehovah; but I hate him, for he never prophesies good things concerning me, but always bad. He is Mi·caiʹah the son of Imʹlah.” However, Je·hoshʹa·phat said: “The king should not say such a thing.”

[[v14-18-8]]

^<<v14-18-8,8>>^ So the king of Israel called a court official and said: “Bring Mi·caiʹah the son of Imʹlah quickly.”

[[v14-18-9]]

^<<v14-18-9,9>>^ Now the king of Israel and Je·hoshʹa·phat the king of Judah were each sitting on his throne, dressed in royal attire; they were sitting at the threshing floor at the entrance of the gate of Sa·marʹi·a, and all the prophets were prophesying before them.

[[v14-18-10]]

^<<v14-18-10,10>>^ Then Zed·e·kiʹah the son of Che·naʹa·nah made for himself iron horns and said: “This is what Jehovah says, ‘With these you will gore^&#42;1^ the Syrians until you exterminate them.’”

[NOTE]
====
. Or “push.”
====

[[v14-18-11]]

^<<v14-18-11,11>>^ All the other prophets were prophesying the same way, saying: “Go up to Raʹmoth-gilʹe·ad and you will be successful; Jehovah will give it into the king’s hand.”

[[v14-18-12]]

^<<v14-18-12,12>>^ So the messenger who went to call Mi·caiʹah said to him: “Look! The words of the prophets are unanimously favorable to the king. Let your word, please, become like theirs, and speak favorably.”

[[v14-18-13]]

^<<v14-18-13,13>>^ But Mi·caiʹah said: “As surely as Jehovah is living, whatever my God says is what I will speak.”

[[v14-18-14]]

^<<v14-18-14,14>>^ Then he came in to the king, and the king asked him: “Mi·caiʹah, should we go to war against Raʹmoth-gilʹe·ad, or should I refrain?” At once he replied: “Go up and you will be successful; they will be given into your hand.”

[[v14-18-15]]

^<<v14-18-15,15>>^ At that the king said to him: “How many times must I put you under oath not to speak to me anything but the truth in the name of Jehovah?”

[[v14-18-16]]

^<<v14-18-16,16>>^ So he said: “I see all the Israelites scattered on the mountains, like sheep that have no shepherd. Jehovah said: ‘These have no master. Let each one go back to his house in peace.’”

[[v14-18-17]]

^<<v14-18-17,17>>^ Then the king of Israel said to Je·hoshʹa·phat: “Did I not tell you, ‘He will not prophesy good things concerning me, only bad’?”

[[v14-18-18]]

^<<v14-18-18,18>>^ Mi·caiʹah then said: “Therefore, hear the word of Jehovah: I saw Jehovah sitting on his throne and all the army of the heavens standing at his right and at his left.

[[v14-18-19]]

^<<v14-18-19,19>>^ Jehovah then said, ‘Who will fool King Aʹhab of Israel, so that he will go up and fall at Raʹmoth-gilʹe·ad?’ And one was saying one thing while another said something else.

[[v14-18-20]]

^<<v14-18-20,20>>^ Then a spirit^&#42;1^ came forward and stood before Jehovah and said, ‘I will fool him.’ Jehovah asked him, ‘How will you do it?’

[NOTE]
====
. Or “an angel.”
====

[[v14-18-21]]

^<<v14-18-21,21>>^ He replied, ‘I will go out and become a deceptive spirit in the mouth of all his prophets.’ So he said, ‘You will fool him, and what is more, you will be successful. Go out and do that.’

[[v14-18-22]]

^<<v14-18-22,22>>^ And now Jehovah has put a deceptive spirit in the mouth of these prophets of yours, but Jehovah has declared calamity for you.”

[[v14-18-23]]

^<<v14-18-23,23>>^ Zed·e·kiʹah the son of Che·naʹa·nah now approached and struck Mi·caiʹah on the cheek and said: “Which way did the spirit of Jehovah pass from me to speak with you?”

[[v14-18-24]]

^<<v14-18-24,24>>^ Mi·caiʹah replied: “Look! You will see which way on the day when you will enter the innermost room to hide.”

[[v14-18-25]]

^<<v14-18-25,25>>^ Then the king of Israel said: “Take Mi·caiʹah and turn him over to Aʹmon the chief of the city and to Joʹash the king’s son.

[[v14-18-26]]

^<<v14-18-26,26>>^ Tell them, ‘This is what the king says: “Put this fellow in the prison and feed him with a reduced allowance of bread and water until I return in peace.”’”

[[v14-18-27]]

^<<v14-18-27,27>>^ But Mi·caiʹah said: “If you do return in peace, Jehovah has not spoken with me.” Then he added: “Take note, all you peoples.”

[[v14-18-28]]

^<<v14-18-28,28>>^ So the king of Israel and Je·hoshʹa·phat the king of Judah went up to Raʹmoth-gilʹe·ad.

[[v14-18-29]]

^<<v14-18-29,29>>^ The king of Israel now said to Je·hoshʹa·phat: “I will disguise myself and will go into the battle, but you should put on your royal attire.” So the king of Israel disguised himself, and they entered the battle.

[[v14-18-30]]

^<<v14-18-30,30>>^ Now the king of Syria had ordered his chariot commanders: “Do not fight with anyone, small or great, except the king of Israel.”

[[v14-18-31]]

^<<v14-18-31,31>>^ And as soon as the chariot commanders saw Je·hoshʹa·phat, they said to themselves: “It is the king of Israel.” So they turned to fight against him; and Je·hoshʹa·phat began to cry for help, and Jehovah helped him, and God at once diverted them from him.

[[v14-18-32]]

^<<v14-18-32,32>>^ When the chariot commanders saw that it was not the king of Israel, they immediately turned back from following him.

[[v14-18-33]]

^<<v14-18-33,33>>^ But one man shot his bow at random,^&#42;1^ and he struck the king of Israel between the joints of his coat of mail. So the king said to his charioteer: “Turn around and take me out of the battle,^&#42;2^ for I have been badly wounded.”

[NOTE]
====
. Or “in his innocence.”
. Lit., “camp.”
====

[[v14-18-34]]

^<<v14-18-34,34>>^ The fighting raged throughout that day, and the king of Israel had to be propped up in the chariot, facing the Syrians until the evening; and he died at sunset.

'''

xref:014-2-chronicles/014-2-chronicles-017.adoc#v14-17-0[&#60; Capítulo Anterior] | <<v14-18-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-019.adoc#v14-19-0[Próximo Capítulo &#62;]