include::./index.adoc[]

[[v14-25-0]]
=== The Second of Chronicles, 25
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-25-1]]

^<<v14-25-1,1>>^ Am·a·ziʹah was 25 years old when he became king, and he reigned for 29 years in Jerusalem. His mother’s name was Je·ho·adʹdan of Jerusalem.

[[v14-25-2]]

^<<v14-25-2,2>>^ He continued to do what was right in Jehovah’s eyes, but not with a complete heart.

[[v14-25-3]]

^<<v14-25-3,3>>^ As soon as he had the kingdom firmly in his control, he killed his servants who had killed his father the king.

[[v14-25-4]]

^<<v14-25-4,4>>^ But he did not put their sons to death, for he acted in harmony with what is written in the Law, in the book of Moses, where Jehovah commanded: “Fathers should not die for their sons, and sons should not die for their fathers; but each one should die for his own sin.”

[[v14-25-5]]

^<<v14-25-5,5>>^ And Am·a·ziʹah gathered Judah together and had them stand according to the paternal houses, by the chiefs of thousands and by the chiefs of hundreds for all Judah and Benjamin. He registered them from 20 years old and up, and he found them to be 300,000 trained^&#42;1^ warriors to serve in the army, able to handle the lance and the large shield.

[NOTE]
====
. Lit., “chosen.”
====

[[v14-25-6]]

^<<v14-25-6,6>>^ Further, he hired from Israel 100,000 mighty warriors for 100 silver talents.^&#42;1^

[NOTE]
====
. A talent equaled 34.2 kg (1,101 oz t). See App. B14.
====

[[v14-25-7]]

^<<v14-25-7,7>>^ But a man of the true God came to him, saying: “O king, do not let the army of Israel go with you, for Jehovah is not with Israel, not with any of the Eʹphra·im·ites.

[[v14-25-8]]

^<<v14-25-8,8>>^ But go by yourself, act, and be courageous in battle. Otherwise, the true God could cause you to stumble before an enemy, for God has the power to help and to cause stumbling.”

[[v14-25-9]]

^<<v14-25-9,9>>^ At this Am·a·ziʹah said to the man of the true God: “But what about the 100 talents that I have given to the troops of Israel?” The man of the true God replied: “Jehovah has the means to give you much more than that.”

[[v14-25-10]]

^<<v14-25-10,10>>^ So Am·a·ziʹah dismissed the troops that had come to him from Eʹphra·im, sending them to their own place. However, they were very angry with Judah, so they returned to their own place in the heat of anger.

[[v14-25-11]]

^<<v14-25-11,11>>^ Then Am·a·ziʹah took courage and led his own troops to the Valley of Salt, and he struck down 10,000 men of Seʹir.

[[v14-25-12]]

^<<v14-25-12,12>>^ And the men of Judah captured 10,000 alive. So they brought them to the top of the crag and threw them down from the top of the crag, and they were all dashed to pieces.

[[v14-25-13]]

^<<v14-25-13,13>>^ But the members of the troop whom Am·a·ziʹah had sent back from accompanying him to the war were making raids on the cities of Judah, from Sa·marʹi·a clear to Beth-hoʹron; they struck down 3,000 of them and took much spoil.

[[v14-25-14]]

^<<v14-25-14,14>>^ But after Am·a·ziʹah returned from striking down the Eʹdom·ites, he brought the gods of the men of Seʹir and set them up for himself as gods, and he began to bow down before them and to make sacrificial smoke to them.

[[v14-25-15]]

^<<v14-25-15,15>>^ So Jehovah grew very angry with Am·a·ziʹah, and he sent a prophet who said to him: “Why are you following the people’s gods that did not rescue their own people out of your hand?”

[[v14-25-16]]

^<<v14-25-16,16>>^ As he spoke to him, the king said: “Did we appoint you as an adviser to the king? Stop! Why should they strike you down?” Then the prophet quit, but he added: “I know that God has decided to bring you to ruin, because you have done this and you have not listened to my advice.”

[[v14-25-17]]

^<<v14-25-17,17>>^ After consulting with his advisers, King Am·a·ziʹah of Judah sent a message to Je·hoʹash son of Je·hoʹa·haz son of Jeʹhu the king of Israel, saying: “Come, let us confront each other in battle.”^&#42;1^

[NOTE]
====
. Or “meet face-to-face.”
====

[[v14-25-18]]

^<<v14-25-18,18>>^ King Je·hoʹash of Israel sent this message to King Am·a·ziʹah of Judah: “The thorny weed in Lebʹa·non sent a message to the cedar in Lebʹa·non, ‘Give your daughter to my son as a wife.’ However, a wild beast of Lebʹa·non passed by and trampled down the thorny weed.

[[v14-25-19]]

^<<v14-25-19,19>>^ You have said, ‘Look! I^&#42;1^ have struck down Eʹdom.’ So your heart has become arrogant, wanting to be glorified. But now stay in your own house.^&#42;2^ Why should you provoke disaster and fall, bringing Judah down with you?”

[NOTE]
====
. Lit., “You.”
. Or “palace.”
====

[[v14-25-20]]

^<<v14-25-20,20>>^ But Am·a·ziʹah did not listen, for this was from the true God to give them into the hand of the enemy, because they had followed the gods of Eʹdom.

[[v14-25-21]]

^<<v14-25-21,21>>^ So King Je·hoʹash of Israel went up, and he and King Am·a·ziʹah of Judah confronted each other in battle at Beth-sheʹmesh, which belongs to Judah.

[[v14-25-22]]

^<<v14-25-22,22>>^ Judah was defeated by Israel, so each one fled to his home.^&#42;1^

[NOTE]
====
. Lit., “tents.”
====

[[v14-25-23]]

^<<v14-25-23,23>>^ King Je·hoʹash of Israel captured King Am·a·ziʹah of Judah, son of Je·hoʹash son of Je·hoʹa·haz,^&#42;1^ at Beth-sheʹmesh. Then he brought him to Jerusalem and made a breach in the wall of Jerusalem from the Gate of Eʹphra·im to the Corner Gate, 400 cubits.^&#42;2^

[NOTE]
====
. Also called Ahaziah.
. About 178 m (584 ft). See App. B14.
====

[[v14-25-24]]

^<<v14-25-24,24>>^ He took all the gold and the silver and all the articles that were found in the house of the true God with^&#42;1^ Oʹbed-eʹdom and in the treasuries of the king’s house,^&#42;2^ as well as hostages. Then he returned to Sa·marʹi·a.

[NOTE]
====
. Or “under the care of.”
. Or “palace.”
====

[[v14-25-25]]

^<<v14-25-25,25>>^ Am·a·ziʹah the son of Je·hoʹash the king of Judah lived for 15 years after the death of Je·hoʹash the son of Je·hoʹa·haz the king of Israel.

[[v14-25-26]]

^<<v14-25-26,26>>^ As for the rest of the history of Am·a·ziʹah, from beginning to end, look! is it not written in the Book of the Kings of Judah and of Israel?

[[v14-25-27]]

^<<v14-25-27,27>>^ From the time that Am·a·ziʹah turned away from following Jehovah, they formed a conspiracy against him in Jerusalem, and he fled to Laʹchish, but they sent men after him to Laʹchish and put him to death there.

[[v14-25-28]]

^<<v14-25-28,28>>^ So they carried him back on horses and buried him with his forefathers in the city of Judah.

'''

xref:014-2-chronicles/014-2-chronicles-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-026.adoc#v14-26-0[Próximo Capítulo &#62;]