include::./index.adoc[]

[[v14-33-0]]
=== The Second of Chronicles, 33
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-33-1]]

^<<v14-33-1,1>>^ Ma·nasʹseh was 12 years old when he became king, and he reigned for 55 years in Jerusalem.

[[v14-33-2]]

^<<v14-33-2,2>>^ He did what was bad in Jehovah’s eyes, following the detestable practices of the nations that Jehovah had driven out from before the people of Israel.

[[v14-33-3]]

^<<v14-33-3,3>>^ He rebuilt the high places that his father Hez·e·kiʹah had torn down, he set up altars to the Baʹals and made sacred poles,^&#42;1^ and he bowed down to all the army of the heavens and served them.

[NOTE]
====
. See Glossary.
====

[[v14-33-4]]

^<<v14-33-4,4>>^ He also built altars in the house of Jehovah, about which Jehovah had said: “In Jerusalem my name will be forever.”

[[v14-33-5]]

^<<v14-33-5,5>>^ And he built altars to all the army of the heavens in two courtyards of the house of Jehovah.

[[v14-33-6]]

^<<v14-33-6,6>>^ And he made his own sons pass through the fire in the Valley of the Son of Hinʹnom; he practiced magic, used divination, practiced sorcery, and appointed spirit mediums and fortune-tellers. He did on a grand scale what was bad in Jehovah’s eyes, to offend him.

[[v14-33-7]]

^<<v14-33-7,7>>^ He put the carved image that he made into the house of the true God about which God had said to David and to his son Solʹo·mon: “In this house and in Jerusalem, which I have chosen out of all the tribes of Israel, I will permanently put my name.

[[v14-33-8]]

^<<v14-33-8,8>>^ And I will never again remove the feet of Israel from the land that I assigned to their forefathers, provided they carefully observe all that I have commanded them, the entire Law, the regulations and the judicial decisions given through Moses.”

[[v14-33-9]]

^<<v14-33-9,9>>^ Ma·nasʹseh kept leading Judah and the inhabitants of Jerusalem astray, causing them to do worse than the nations that Jehovah had annihilated from before the Israelites.

[[v14-33-10]]

^<<v14-33-10,10>>^ Jehovah kept speaking to Ma·nasʹseh and his people, but they paid no attention.

[[v14-33-11]]

^<<v14-33-11,11>>^ So Jehovah brought against them the army chiefs of the king of As·syrʹi·a, and they captured Ma·nasʹseh with hooks^&#42;1^ and bound him with two copper fetters and took him to Babylon.

[NOTE]
====
. Or possibly, “in the hollows.”
====

[[v14-33-12]]

^<<v14-33-12,12>>^ In his distress, he begged Jehovah his God for favor^&#42;1^ and kept humbling himself greatly before the God of his forefathers.

[NOTE]
====
. Or “softened the face of Jehovah his God.”
====

[[v14-33-13]]

^<<v14-33-13,13>>^ He kept praying to Him, and He was moved by his entreaty and heard his request for favor, and He restored him to Jerusalem to his kingship. Then Ma·nasʹseh came to know that Jehovah is the true God.

[[v14-33-14]]

^<<v14-33-14,14>>^ After this he built an outer wall for the City of David west of Giʹhon in the valley^&#42;1^ and as far as the Fish Gate, and he continued it around to Oʹphel, and he made it very high. Further, he appointed army chiefs in all the fortified cities in Judah.

[NOTE]
====
. Or “wadi.”
====

[[v14-33-15]]

^<<v14-33-15,15>>^ He then removed the foreign gods and the idol image from the house of Jehovah and all the altars that he had built in the mountain of the house of Jehovah and in Jerusalem, and he had them thrown outside the city.

[[v14-33-16]]

^<<v14-33-16,16>>^ He also prepared the altar of Jehovah and began to offer up communion sacrifices and thanksgiving sacrifices on it, and he told Judah to serve Jehovah the God of Israel.

[[v14-33-17]]

^<<v14-33-17,17>>^ Nevertheless, the people were still sacrificing on the high places, although only to Jehovah their God.

[[v14-33-18]]

^<<v14-33-18,18>>^ As for the rest of the history of Ma·nasʹseh, his prayer to his God, and the words of the visionaries who spoke to him in the name of Jehovah the God of Israel, they are recorded in the history of the kings of Israel.

[[v14-33-19]]

^<<v14-33-19,19>>^ Also his prayer and how his entreaty was granted him, all his sins and his unfaithfulness, the locations where he built high places and set up the sacred poles^&#42;1^ and the graven images before he humbled himself, they are written among the words of his visionaries.

[NOTE]
====
. See Glossary.
====

[[v14-33-20]]

^<<v14-33-20,20>>^ Then Ma·nasʹseh was laid to rest with his forefathers, and they buried him at his house; and his son Aʹmon became king in his place.

[[v14-33-21]]

^<<v14-33-21,21>>^ Aʹmon was 22 years old when he became king, and he reigned for two years in Jerusalem.

[[v14-33-22]]

^<<v14-33-22,22>>^ And he continued to do what was bad in Jehovah’s eyes, just as his father Ma·nasʹseh had done; and Aʹmon sacrificed to all the graven images that his father Ma·nasʹseh had made, and he kept serving them.

[[v14-33-23]]

^<<v14-33-23,23>>^ But he did not humble himself before Jehovah as Ma·nasʹseh his father had humbled himself; instead, Aʹmon greatly increased his guilt.

[[v14-33-24]]

^<<v14-33-24,24>>^ Eventually his servants conspired against him and put him to death in his own house.

[[v14-33-25]]

^<<v14-33-25,25>>^ But the people of the land struck down all those who conspired against King Aʹmon, and they made his son Jo·siʹah king in his place.

'''

xref:014-2-chronicles/014-2-chronicles-032.adoc#v14-32-0[&#60; Capítulo Anterior] | <<v14-33-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-034.adoc#v14-34-0[Próximo Capítulo &#62;]