include::./index.adoc[]

[[v14-22-0]]
=== The Second of Chronicles, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-22-1]]

^<<v14-22-1,1>>^ Then the inhabitants of Jerusalem made his youngest son A·ha·ziʹah king in his place, for the marauder band that came with the Arabs to the camp had killed all the older ones. So A·ha·ziʹah the son of Je·hoʹram began to reign as king of Judah.

[[v14-22-2]]

^<<v14-22-2,2>>^ A·ha·ziʹah was 22 years old when he became king, and he reigned for one year in Jerusalem. His mother’s name was Ath·a·liʹah the granddaughter^&#42;1^ of Omʹri.

[NOTE]
====
. Lit., “daughter.”
====

[[v14-22-3]]

^<<v14-22-3,3>>^ He too walked in the ways of the house of Aʹhab, for his mother became his adviser in acting wickedly.

[[v14-22-4]]

^<<v14-22-4,4>>^ And he kept doing what was bad in Jehovah’s eyes, like the house of Aʹhab, for they became his advisers after the death of his father, to his destruction.

[[v14-22-5]]

^<<v14-22-5,5>>^ He followed their advice and went with Je·hoʹram the son of King Aʹhab of Israel to wage war against King Hazʹa·el of Syria at Raʹmoth-gilʹe·ad, where the archers wounded Je·hoʹram.

[[v14-22-6]]

^<<v14-22-6,6>>^ He returned to Jezʹre·el to recover from the wounds that they had inflicted on him at Raʹmah when he fought against King Hazʹa·el of Syria.
A·ha·ziʹah^&#42;1^ the son of Je·hoʹram the king of Judah went down to Jezʹre·el to see Je·hoʹram the son of Aʹhab, because he had been wounded.^&#42;2^

[NOTE]
====
. In some Hebrew manuscripts, “Azariah.”
. Or “he was sick.”
====

[[v14-22-7]]

^<<v14-22-7,7>>^ But God brought about the downfall of A·ha·ziʹah by his coming to Je·hoʹram; and when he came, he went out with Je·hoʹram to meet Jeʹhu the grandson^&#42;1^ of Nimʹshi, whom Jehovah had anointed to do away with^&#42;2^ the house of Aʹhab.

[NOTE]
====
. Lit., “son.”
. Lit., “cut off.”
====

[[v14-22-8]]

^<<v14-22-8,8>>^ When Jeʹhu began to execute judgment on the house of Aʹhab, he found the princes of Judah and the sons of A·ha·ziʹah’s brothers, ministers of A·ha·ziʹah, and he killed them.

[[v14-22-9]]

^<<v14-22-9,9>>^ Then he looked for A·ha·ziʹah; they captured him where he was hiding in Sa·marʹi·a, and they brought him to Jeʹhu. Then they put him to death and buried him, for they said: “He is the grandson of Je·hoshʹa·phat, who searched for Jehovah with all his heart.” There was no one of the house of A·ha·ziʹah who had the power to rule the kingdom.

[[v14-22-10]]

^<<v14-22-10,10>>^ When Ath·a·liʹah, A·ha·ziʹah’s mother, saw that her son had died, she rose up and destroyed the entire royal line^&#42;1^ of the house of Judah.

[NOTE]
====
. Lit., “all seed of the kingdom.”
====

[[v14-22-11]]

^<<v14-22-11,11>>^ However, Je·ho·shabʹe·ath the daughter of the king took Je·hoʹash the son of A·ha·ziʹah and stole him away from among the sons of the king who were to be put to death, and she put him and his nurse in an inner bedroom. Je·ho·shabʹe·ath the daughter of King Je·hoʹram (she was the wife of Je·hoiʹa·da the priest and a sister of A·ha·ziʹah) managed to keep him concealed from Ath·a·liʹah, so that she did not put him to death.

[[v14-22-12]]

^<<v14-22-12,12>>^ He remained with them for six years, hidden at the house of the true God, while Ath·a·liʹah was ruling over the land.

'''

xref:014-2-chronicles/014-2-chronicles-021.adoc#v14-21-0[&#60; Capítulo Anterior] | <<v14-22-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-023.adoc#v14-23-0[Próximo Capítulo &#62;]