include::./index.adoc[]

[[v14-21-0]]
=== The Second of Chronicles, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-21-1]]

^<<v14-21-1,1>>^ Then Je·hoshʹa·phat was laid to rest with his forefathers and was buried with his forefathers in the City of David; and his son Je·hoʹram became king in his place.

[[v14-21-2]]

^<<v14-21-2,2>>^ His brothers, Je·hoshʹa·phat’s sons, were Az·a·riʹah, Je·hiʹel, Zech·a·riʹah, Az·a·riʹah, Miʹcha·el, and Sheph·a·tiʹah; all of these were the sons of King Je·hoshʹa·phat of Israel.

[[v14-21-3]]

^<<v14-21-3,3>>^ And their father had given them many gifts in silver and gold, and valuable things, along with fortified cities in Judah; but he gave the kingdom to Je·hoʹram, for he was the firstborn.

[[v14-21-4]]

^<<v14-21-4,4>>^ When Je·hoʹram had taken control of the kingdom of his father, he strengthened his position by killing all his brothers with the sword, as well as some of the princes of Israel.

[[v14-21-5]]

^<<v14-21-5,5>>^ Je·hoʹram was 32 years old when he became king, and he reigned for eight years in Jerusalem.

[[v14-21-6]]

^<<v14-21-6,6>>^ He walked in the way of the kings of Israel, just as those of the house of Aʹhab had done, for Aʹhab’s daughter had become his wife; and he kept doing what was bad in Jehovah’s eyes.

[[v14-21-7]]

^<<v14-21-7,7>>^ But Jehovah did not want to bring the house of David to ruin for the sake of the covenant that he had made with David, since he had promised to give a lamp to him and to his sons always.

[[v14-21-8]]

^<<v14-21-8,8>>^ In his days Eʹdom revolted against Judah and then set up its own king.

[[v14-21-9]]

^<<v14-21-9,9>>^ So Je·hoʹram and his commanders crossed over with all his chariots, and he rose up by night and defeated the Eʹdom·ites who were surrounding him and the chariot commanders.

[[v14-21-10]]

^<<v14-21-10,10>>^ But Eʹdom has kept up its revolt against Judah to this day. Libʹnah also revolted against him at that time, because he had abandoned Jehovah the God of his forefathers.

[[v14-21-11]]

^<<v14-21-11,11>>^ He had also made high places on the mountains of Judah to cause the inhabitants of Jerusalem to commit spiritual prostitution, and he led Judah astray.

[[v14-21-12]]

^<<v14-21-12,12>>^ Eventually a written message came to him from E·liʹjah the prophet, saying: “This is what Jehovah the God of David your forefather says, ‘You have not walked in the ways of your father Je·hoshʹa·phat or in the ways of King Aʹsa of Judah.

[[v14-21-13]]

^<<v14-21-13,13>>^ But you walk in the way of the kings of Israel and cause Judah and the inhabitants of Jerusalem to commit spiritual prostitution like the prostitution of the house of Aʹhab, and you even killed your own brothers, the household of your father, who were better than you.

[[v14-21-14]]

^<<v14-21-14,14>>^ Therefore, Jehovah is dealing a great blow to your people, to your sons, to your wives, and to all your possessions.

[[v14-21-15]]

^<<v14-21-15,15>>^ And you will suffer with many sicknesses, including a disease of your intestines, until your intestines come out because of the disease, day after day.’”

[[v14-21-16]]

^<<v14-21-16,16>>^ Then Jehovah stirred up against Je·hoʹram the Phi·lisʹtines^&#42;1^ and the Arabs who were near the E·thi·oʹpi·ans.

[NOTE]
====
. Lit., “the spirit of the Philistines.”
====

[[v14-21-17]]

^<<v14-21-17,17>>^ So they invaded Judah, forcing their way in, and carried off all the possessions that were found in the king’s house,^&#42;1^ as well as his sons and his wives; and the only son left to him was Je·hoʹa·haz,^&#42;2^ his youngest son.

[NOTE]
====
. Or “palace.”
. Also called Ahaziah.
====

[[v14-21-18]]

^<<v14-21-18,18>>^ And after all of this, Jehovah afflicted him with an incurable disease in his intestines.

[[v14-21-19]]

^<<v14-21-19,19>>^ Some time later, when two full years had passed, his intestines came out because of his disease, and he died while suffering severely from his disease; and his people did not make a burning for him like the burning that was made for his forefathers.

[[v14-21-20]]

^<<v14-21-20,20>>^ He was 32 years old when he became king, and he reigned for eight years in Jerusalem. No one regretted it when he died. So they buried him in the City of David, but not in the burial places of the kings.

'''

xref:014-2-chronicles/014-2-chronicles-020.adoc#v14-20-0[&#60; Capítulo Anterior] | <<v14-21-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-022.adoc#v14-22-0[Próximo Capítulo &#62;]