include::./index.adoc[]

[[v14-5-0]]
=== The Second of Chronicles, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-5-1]]

^<<v14-5-1,1>>^ So Solʹo·mon completed all the work he had to do for the house of Jehovah. Solʹo·mon then brought in the things that David his father had made holy, and he put the silver, the gold, and all the articles into the treasuries of the house of the true God.

[[v14-5-2]]

^<<v14-5-2,2>>^ At that time Solʹo·mon congregated the elders of Israel, all the heads of the tribes, the chieftains of the paternal houses of Israel. They came to Jerusalem to bring up the ark of the covenant of Jehovah from the City of David, that is, Zion.

[[v14-5-3]]

^<<v14-5-3,3>>^ All the men of Israel assembled before the king at the festival^&#42;1^ that is held in the seventh month.

[NOTE]
====
. That is, the Festival of Booths.
====

[[v14-5-4]]

^<<v14-5-4,4>>^ So all the elders of Israel came, and the Levites lifted up the Ark.

[[v14-5-5]]

^<<v14-5-5,5>>^ They brought up the Ark, the tent of meeting, and all the holy utensils that were in the tent. The priests and the Levites^&#42;1^ brought them up.

[NOTE]
====
. Or “The Levitical priests.”
====

[[v14-5-6]]

^<<v14-5-6,6>>^ King Solʹo·mon and the entire assembly of Israel who had been summoned to meet with him were before the Ark. So many sheep and cattle were being sacrificed that they could not be counted or numbered.

[[v14-5-7]]

^<<v14-5-7,7>>^ Then the priests brought the ark of the covenant of Jehovah to its place, into the innermost room of the house, the Most Holy, underneath the wings of the cherubs.

[[v14-5-8]]

^<<v14-5-8,8>>^ Thus the wings of the cherubs were spread out over the place of the Ark, so that the cherubs covered over the Ark and its poles from above.

[[v14-5-9]]

^<<v14-5-9,9>>^ The poles were so long that the tips of the poles were visible from the Holy in front of the innermost room, but they were not visible from outside. And they are there to this day.

[[v14-5-10]]

^<<v14-5-10,10>>^ There was nothing in the Ark but the two tablets that Moses placed in it at Horʹeb, when Jehovah made a covenant with the people of Israel while they were coming out of Egypt.

[[v14-5-11]]

^<<v14-5-11,11>>^ When the priests came out from the holy place (for all the priests who were present had sanctified themselves, regardless of their divisions),

[[v14-5-12]]

^<<v14-5-12,12>>^ all the Levite singers who belonged to Aʹsaph, to Heʹman, to Je·duʹthun, and to their sons and their brothers were clothed in fine fabric, holding cymbals, stringed instruments, and harps; they were standing east of the altar, and along with them 120 priests were sounding the trumpets.

[[v14-5-13]]

^<<v14-5-13,13>>^ At the moment when the trumpeters and the singers were praising and thanking Jehovah in unison, and as the sound ascended from the trumpets, the cymbals, and the other musical instruments as they were praising Jehovah, “for he is good; his loyal love endures forever,” then the house, the house of Jehovah, was filled with a cloud.

[[v14-5-14]]

^<<v14-5-14,14>>^ The priests were not able to stand to minister because of the cloud, for the glory of Jehovah filled the house of the true God.

'''

xref:014-2-chronicles/014-2-chronicles-004.adoc#v14-4-0[&#60; Capítulo Anterior] | <<v14-5-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-006.adoc#v14-6-0[Próximo Capítulo &#62;]