include::./index.adoc[]

[[v14-15-0]]
=== The Second of Chronicles, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-15-1]]

^<<v14-15-1,1>>^ Now the spirit of God came upon Az·a·riʹah the son of Oʹded.

[[v14-15-2]]

^<<v14-15-2,2>>^ So he went out to meet Aʹsa and said to him: “Hear me, O Aʹsa and all Judah and Benjamin! Jehovah is with you as long as you remain with him; and if you search for him, he will let himself be found by you, but if you abandon him, he will abandon you.

[[v14-15-3]]

^<<v14-15-3,3>>^ For a long time^&#42;1^ Israel had been without the true God, without a priest teaching, and without law.

[NOTE]
====
. Lit., “And many days.”
====

[[v14-15-4]]

^<<v14-15-4,4>>^ But when in their distress they returned to Jehovah the God of Israel and searched for him, he let himself be found by them.

[[v14-15-5]]

^<<v14-15-5,5>>^ In those times no one could travel safely,^&#42;1^ for there was much unrest among all the inhabitants of the lands.

[NOTE]
====
. Lit., “there was no peace for the one going out or the one coming in.”
====

[[v14-15-6]]

^<<v14-15-6,6>>^ Nation was being crushed by nation and one city by another city, because God kept them in disorder with every sort of distress.

[[v14-15-7]]

^<<v14-15-7,7>>^ But you, be strong and do not become discouraged,^&#42;1^ for your activity will be rewarded.”

[NOTE]
====
. Lit., “do not let your hands drop.”
====

[[v14-15-8]]

^<<v14-15-8,8>>^ As soon as Aʹsa heard these words and the prophecy of Oʹded the prophet, he took courage and removed the disgusting idols from all the land of Judah and Benjamin and from the cities that he had captured from the mountainous region of Eʹphra·im, and he restored Jehovah’s altar that was before the porch of Jehovah.

[[v14-15-9]]

^<<v14-15-9,9>>^ And he gathered together all Judah and Benjamin and the foreign residents with them from Eʹphra·im and Ma·nasʹseh and Simʹe·on, for they had deserted to him from Israel in great number when they saw that Jehovah his God was with him.

[[v14-15-10]]

^<<v14-15-10,10>>^ So they were gathered together at Jerusalem in the third month of the 15th year of Aʹsa’s reign.

[[v14-15-11]]

^<<v14-15-11,11>>^ On that day they sacrificed to Jehovah from the spoil they had brought, 700 cattle and 7,000 sheep.

[[v14-15-12]]

^<<v14-15-12,12>>^ Furthermore, they entered into a covenant to search for Jehovah the God of their forefathers with all their heart and with all their soul.^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v14-15-13]]

^<<v14-15-13,13>>^ Whoever would not search for Jehovah the God of Israel was to be put to death, whether small or great, man or woman.

[[v14-15-14]]

^<<v14-15-14,14>>^ So they took an oath to Jehovah with a loud voice, with joyful shouting, and with the trumpets and horns.

[[v14-15-15]]

^<<v14-15-15,15>>^ And all Judah rejoiced over the oath, for they had taken the oath with all their heart and they eagerly sought him and he let himself be found by them, and Jehovah continued to give them rest on every side.

[[v14-15-16]]

^<<v14-15-16,16>>^ Aʹsa the king even removed Maʹa·cah his grandmother from her position as queen mother,^&#42;1^ because she had made an obscene idol for the worship of the sacred pole.^&#42;2^ Aʹsa cut down her obscene idol and pulverized it and burned it in the Kidʹron Valley.

[NOTE]
====
. Or “as lady.”
. See Glossary.
====

[[v14-15-17]]

^<<v14-15-17,17>>^ But the high places were not removed from Israel. Nevertheless, Aʹsa’s heart was complete^&#42;1^ all his life.^&#42;2^

[NOTE]
====
. Or “completely devoted.”
. Lit., “days.”
====

[[v14-15-18]]

^<<v14-15-18,18>>^ And he brought the things that he and his father had made holy into the house of the true God—silver, gold, and various utensils.

[[v14-15-19]]

^<<v14-15-19,19>>^ There was no war until the 35th year of Aʹsa’s reign.

'''

xref:014-2-chronicles/014-2-chronicles-014.adoc#v14-14-0[&#60; Capítulo Anterior] | <<v14-15-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-016.adoc#v14-16-0[Próximo Capítulo &#62;]