include::./index.adoc[]

[[v14-10-0]]
=== The Second of Chronicles, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-10-1]]

^<<v14-10-1,1>>^ Re·ho·boʹam went to Sheʹchem, for all Israel had come to Sheʹchem to make him king.

[[v14-10-2]]

^<<v14-10-2,2>>^ As soon as Jer·o·boʹam the son of Neʹbat heard of it (he was still in Egypt because he had fled on account of King Solʹo·mon), Jer·o·boʹam came back from Egypt.

[[v14-10-3]]

^<<v14-10-3,3>>^ Then they sent for him, and Jer·o·boʹam and all Israel came to Re·ho·boʹam and said:

[[v14-10-4]]

^<<v14-10-4,4>>^ “Your father made our yoke harsh. But if you make the harsh service of your father easier and you lighten the heavy^&#42;1^ yoke he put on us, we will serve you.”

[NOTE]
====
. Or “oppressive.”
====

[[v14-10-5]]

^<<v14-10-5,5>>^ At this he said to them: “Return to me after three days.” So the people went away.

[[v14-10-6]]

^<<v14-10-6,6>>^ King Re·ho·boʹam then consulted with the older men^&#42;1^ who had served his father Solʹo·mon while he was alive, saying: “What advice would you give on how to reply to this people?”

[NOTE]
====
. Or “the elders.”
====

[[v14-10-7]]

^<<v14-10-7,7>>^ They answered him: “If you are good to this people and please them and give them a favorable answer, they will always be your servants.”

[[v14-10-8]]

^<<v14-10-8,8>>^ However, he rejected the advice that the older men^&#42;1^ gave him, and he consulted with the young men who had grown up with him and who were now his attendants.

[NOTE]
====
. Or “the elders.”
====

[[v14-10-9]]

^<<v14-10-9,9>>^ He asked them: “What advice do you offer on how we should reply to this people who have said to me, ‘Make the yoke your father put on us lighter’?”

[[v14-10-10]]

^<<v14-10-10,10>>^ The young men who had grown up with him said to him: “This is what you should say to the people who have said to you, ‘Your father made our yoke heavy, but you should make it lighter for us’; this is what you should tell them, ‘My little finger will be thicker than my father’s hips.

[[v14-10-11]]

^<<v14-10-11,11>>^ My father imposed a heavy yoke on you, but I will add to your yoke. My father punished you with whips, but I will do so with scourges.’”

[[v14-10-12]]

^<<v14-10-12,12>>^ Jer·o·boʹam and all the people came to Re·ho·boʹam on the third day, just as the king had said: “Return to me on the third day.”

[[v14-10-13]]

^<<v14-10-13,13>>^ But the king answered them harshly. Thus King Re·ho·boʹam rejected the advice of the older men.^&#42;1^

[NOTE]
====
. Or “the elders.”
====

[[v14-10-14]]

^<<v14-10-14,14>>^ He spoke to them according to the advice of the young men, saying: “I will make your yoke heavier, and I will add to it. My father punished you with whips, but I will do so with scourges.”

[[v14-10-15]]

^<<v14-10-15,15>>^ So the king did not listen to the people, for this turn of events was caused by the true God, in order to carry out the word that Jehovah had spoken through A·hiʹjah the Shiʹlo·nite to Jer·o·boʹam the son of Neʹbat.

[[v14-10-16]]

^<<v14-10-16,16>>^ As for all Israel, because the king refused to listen to them, the people replied to the king: “What share do we have in David? We have no inheritance in the son of Jesʹse. Each one to your gods, O Israel! Now look after your own house, O David.” With that all Israel returned to their homes.^&#42;1^

[NOTE]
====
. Lit., “tents.”
====

[[v14-10-17]]

^<<v14-10-17,17>>^ But Re·ho·boʹam continued to reign over the Israelites living in the cities of Judah.

[[v14-10-18]]

^<<v14-10-18,18>>^ Then King Re·ho·boʹam sent Ha·doʹram, who was in charge of those conscripted for forced labor, but the Israelites stoned him to death. King Re·ho·boʹam managed to mount his chariot to flee to Jerusalem.

[[v14-10-19]]

^<<v14-10-19,19>>^ And the Israelites have been in revolt against the house of David down to this day.

'''

xref:014-2-chronicles/014-2-chronicles-009.adoc#v14-9-0[&#60; Capítulo Anterior] | <<v14-10-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-011.adoc#v14-11-0[Próximo Capítulo &#62;]