include::./index.adoc[]

[[v14-6-0]]
=== The Second of Chronicles, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v14-6-1]]

^<<v14-6-1,1>>^ At that time Solʹo·mon said: “Jehovah said he would reside in the thick gloom.

[[v14-6-2]]

^<<v14-6-2,2>>^ Now I have built a lofty house for you, an established place for you to dwell in forever.”

[[v14-6-3]]

^<<v14-6-3,3>>^ Then the king turned around and began to bless all the congregation of Israel while all the congregation of Israel stood.

[[v14-6-4]]

^<<v14-6-4,4>>^ He said: “May Jehovah the God of Israel be praised, the one who by his own mouth promised my father David and by his own hands has given fulfillment, saying,

[[v14-6-5]]

^<<v14-6-5,5>>^ ‘From the day I brought my people out of the land of Egypt, I have not chosen a city out of all the tribes of Israel in which to build a house for my name to remain there, and I have not chosen a man to become leader over my people Israel.

[[v14-6-6]]

^<<v14-6-6,6>>^ But I have chosen Jerusalem for my name to remain there, and I have chosen David to be over my people Israel.’

[[v14-6-7]]

^<<v14-6-7,7>>^ And it was the heart’s desire of my father David to build a house for the name of Jehovah the God of Israel.

[[v14-6-8]]

^<<v14-6-8,8>>^ But Jehovah said to my father David, ‘It was your heart’s desire to build a house for my name, and you did well to desire this in your heart.

[[v14-6-9]]

^<<v14-6-9,9>>^ However, you will not build the house, but your own son who is to be born to you^&#42;1^ is the one who will build the house for my name.’

[NOTE]
====
. Lit., “your son, the one coming out of your loins.”
====

[[v14-6-10]]

^<<v14-6-10,10>>^ Jehovah has carried out the promise that he made, for I have succeeded my father David and I sit on the throne of Israel, just as Jehovah promised. I have also built the house for the name of Jehovah the God of Israel,

[[v14-6-11]]

^<<v14-6-11,11>>^ and there I have placed the Ark containing the covenant that Jehovah made with the people of Israel.”

[[v14-6-12]]

^<<v14-6-12,12>>^ Then he stood before the altar of Jehovah in front of all the congregation of Israel, and he spread out his hands.

[[v14-6-13]]

^<<v14-6-13,13>>^ (For Solʹo·mon had made a platform of copper and put it in the middle of the court.^&#42;1^ It was five cubits^&#42;2^ long, five cubits wide, and three cubits high; and he stood on it.) And he knelt down in front of all the congregation of Israel and spread his hands out to the heavens,

[NOTE]
====
. Or “enclosure.”
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
====

[[v14-6-14]]

^<<v14-6-14,14>>^ and he said: “O Jehovah the God of Israel, there is no God like you in the heavens or on the earth, keeping the covenant and showing loyal love to your servants who are walking before you with all their heart.

[[v14-6-15]]

^<<v14-6-15,15>>^ You have kept the promise that you made to your servant David my father. You made the promise with your own mouth, and this day you have fulfilled it with your own hand.

[[v14-6-16]]

^<<v14-6-16,16>>^ And now, O Jehovah the God of Israel, keep the promise you made to your servant David my father when you said: ‘There will never fail to be a man of your line before me to sit on the throne of Israel, if only your sons will pay attention to their way by walking in my law, just as you have walked before me.’

[[v14-6-17]]

^<<v14-6-17,17>>^ And now, O Jehovah the God of Israel, let the promise that you made to your servant David prove trustworthy.

[[v14-6-18]]

^<<v14-6-18,18>>^ “But will God really dwell with mankind on the earth? Look! The heavens, yes, the heaven of the heavens, cannot contain you; how much less, then, this house that I have built!

[[v14-6-19]]

^<<v14-6-19,19>>^ Now pay attention to the prayer of your servant and to his request for favor, O Jehovah my God, and listen to the cry for help and to the prayer that your servant is praying before you.

[[v14-6-20]]

^<<v14-6-20,20>>^ May your eyes be open toward this house day and night, toward the place where you said that you would put your name, to listen to the prayer that your servant prays toward this place.

[[v14-6-21]]

^<<v14-6-21,21>>^ And listen to your servant’s pleas for help and to the pleas of your people Israel when they pray toward this place, and may you hear from your dwelling place, from the heavens; yes, may you hear and forgive.

[[v14-6-22]]

^<<v14-6-22,22>>^ “If a man sins against his fellow man and is made to take an oath^&#42;1^ and is brought under liability to the oath,^&#42;2^ and while under the oath^&#42;3^ he comes before your altar in this house,

[NOTE]
====
. Or “and the latter lays a cursing on him.” That is, an oath that carried with it a curse as its penalty if sworn falsely or violated.
. Lit., “curse.”
. Lit., “curse.”
====

[[v14-6-23]]

^<<v14-6-23,23>>^ may you then hear from the heavens and act and judge your servants by paying back the wicked one and bringing what he did on his own head and by pronouncing the righteous one innocent^&#42;1^ and rewarding him according to his own righteousness.

[NOTE]
====
. Lit., “righteous.”
====

[[v14-6-24]]

^<<v14-6-24,24>>^ “And if your people Israel are defeated by an enemy because they kept sinning against you, and they return and glorify your name and pray and beg for favor before you in this house,

[[v14-6-25]]

^<<v14-6-25,25>>^ may you then hear from the heavens and forgive the sin of your people Israel and bring them back to the land that you gave to them and their forefathers.

[[v14-6-26]]

^<<v14-6-26,26>>^ “When the heavens are shut up and there is no rain because they kept sinning against you, and they pray toward this place and glorify your name and turn back from their sin because you humbled^&#42;1^ them,

[NOTE]
====
. Or “afflicted.”
====

[[v14-6-27]]

^<<v14-6-27,27>>^ may you then hear from the heavens and forgive the sin of your servants, of your people Israel, for you will instruct them about the good way in which they should walk; and bring rain on your land that you gave to your people as an inheritance.

[[v14-6-28]]

^<<v14-6-28,28>>^ “If a famine occurs in the land, or a pestilence, a scorching blight, mildew, swarming locusts, or voracious locusts^&#42;1^ or if their enemies besiege them in any of the cities of the land^&#42;2^ or if any other sort of plague or disease occurs,

[NOTE]
====
. Or “grasshoppers.”
. Lit., “in the land of his gates.”
====

[[v14-6-29]]

^<<v14-6-29,29>>^ whatever prayer, whatever request for favor may be made by any man or by all your people Israel (for each one knows his own plague and his own pain) when they spread out their hands toward this house,

[[v14-6-30]]

^<<v14-6-30,30>>^ then may you hear from the heavens, your dwelling place, and may you forgive; and reward each one according to all his ways, for you know his heart (you alone truly know the human heart),

[[v14-6-31]]

^<<v14-6-31,31>>^ so that they may fear you by walking in your ways all the days they live on the land that you gave to our forefathers.

[[v14-6-32]]

^<<v14-6-32,32>>^ “Also concerning the foreigner who is not part of your people Israel and who comes from a distant land because of your great name^&#42;1^ and your mighty hand and your outstretched arm, and he comes and prays toward this house,

[NOTE]
====
. Or “reputation.”
====

[[v14-6-33]]

^<<v14-6-33,33>>^ may you then listen from the heavens, your dwelling place, and do all that the foreigner asks of you, so that all the peoples of the earth may know your name and fear you, as your people Israel do, and may know that your name has been called on this house that I have built.

[[v14-6-34]]

^<<v14-6-34,34>>^ “If your people go to war against their enemies in the way that you send them and they pray to you in the direction of this city that you have chosen and toward the house that I have built for your name,

[[v14-6-35]]

^<<v14-6-35,35>>^ then hear from the heavens their prayer and their request for favor and execute judgment for them.

[[v14-6-36]]

^<<v14-6-36,36>>^ “If they sin against you (for there is no man who does not sin), and you are furious with them and you abandon them to an enemy, and their captors carry them off captive to a land, far or near,

[[v14-6-37]]

^<<v14-6-37,37>>^ and they come to their senses in the land where they were carried off captive, and they return to you and beg you for favor in the land where they are captives, saying, ‘We have sinned and done wrong; we have acted wickedly,’

[[v14-6-38]]

^<<v14-6-38,38>>^ and they return to you with all their heart and all their soul^&#42;1^ in the land of their captivity where they were carried off captive, and they pray in the direction of their land that you gave to their forefathers and the city that you have chosen and the house that I have built for your name,

[NOTE]
====
. See Glossary.
====

[[v14-6-39]]

^<<v14-6-39,39>>^ then hear from the heavens, your dwelling place, their prayer and their request for favor, and execute judgment for them and forgive your people who have sinned against you.

[[v14-6-40]]

^<<v14-6-40,40>>^ “Now, O my God, please, may your eyes be opened and your ears attentive to the prayer offered in^&#42;1^ this place.

[NOTE]
====
. Or “respecting.”
====

[[v14-6-41]]

^<<v14-6-41,41>>^ And now go up, O Jehovah God, to your resting-place, you and the Ark of your strength. Let your priests, O Jehovah God, be clothed with salvation, and let your loyal ones rejoice in your goodness.

[[v14-6-42]]

^<<v14-6-42,42>>^ O Jehovah God, do not reject^&#42;1^ your anointed one. May you remember your loyal love to David your servant.”

[NOTE]
====
. Lit., “turn away the face of.”
====

'''

xref:014-2-chronicles/014-2-chronicles-005.adoc#v14-5-0[&#60; Capítulo Anterior] | <<v14-6-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-007.adoc#v14-7-0[Próximo Capítulo &#62;]