include::./index.adoc[]

[[v44-7-0]]
=== Acts of Apostles, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-7-1]]

^<<v44-7-1,1>>^ But the high priest said: “Are these things so?”

[[v44-7-2]]

^<<v44-7-2,2>>^ Stephen replied: “Men, brothers and fathers, listen. The God of glory appeared to our forefather Abraham while he was in Mes·o·po·taʹmi·a, before he took up residence in Haʹran,

[[v44-7-3]]

^<<v44-7-3,3>>^ and he said to him: ‘Go out from your land and from your relatives and come into the land that I will show you.’

[[v44-7-4]]

^<<v44-7-4,4>>^ Then he went out of the land of the Chal·deʹans and took up residence in Haʹran. And from there, after his father died, God caused him to resettle in this land where you now dwell.

[[v44-7-5]]

^<<v44-7-5,5>>^ And yet, he did not give him any inheritance in it, no, not even enough to put his foot on; but he promised to give it to him as a possession and after him to his offspring,^&#42;1^ though as yet he had no child.

[NOTE]
====
. Lit., “seed.”
====

[[v44-7-6]]

^<<v44-7-6,6>>^ Moreover, God told him that his offspring^&#42;1^ would be foreigners in a land not theirs and that the people would enslave them and afflict^&#42;2^ them for 400 years.

[NOTE]
====
. Lit., “seed.”
. Or “mistreat.”
====

[[v44-7-7]]

^<<v44-7-7,7>>^ ‘And that nation for which they will slave I will judge,’ God said, ‘and after these things they will come out and will offer sacred service to me in this place.’

[[v44-7-8]]

^<<v44-7-8,8>>^ “He also gave him a covenant of circumcision, and he became the father of Isaac and circumcised him on the eighth day, and Isaac became the father of^&#42;1^ Jacob, and Jacob of the 12 family heads.^&#42;2^

[NOTE]
====
. Or possibly, “did the same with.”
. Or “patriarchs.”
====

[[v44-7-9]]

^<<v44-7-9,9>>^ And the family heads became jealous of Joseph and sold him into Egypt. But God was with him,

[[v44-7-10]]

^<<v44-7-10,10>>^ and he rescued him out of all his tribulations and gave him favor and wisdom before Pharʹaoh king of Egypt. And he appointed him to govern Egypt and his whole house.

[[v44-7-11]]

^<<v44-7-11,11>>^ But a famine came on all of Egypt and Caʹnaan, yes, a great tribulation, and our forefathers could not find anything to eat.

[[v44-7-12]]

^<<v44-7-12,12>>^ But Jacob heard that there were food supplies^&#42;1^ in Egypt, and he sent our forefathers out the first time.

[NOTE]
====
. Or “there was grain.”
====

[[v44-7-13]]

^<<v44-7-13,13>>^ During the second time, Joseph made himself known to his brothers, and the family of Joseph became known to Pharʹaoh.

[[v44-7-14]]

^<<v44-7-14,14>>^ So Joseph sent a message and called his father Jacob and all his relatives from that place, 75 persons^&#42;1^ in all.

[NOTE]
====
. Or “souls.”
====

[[v44-7-15]]

^<<v44-7-15,15>>^ So Jacob went down into Egypt, and he died there, and so did our forefathers.

[[v44-7-16]]

^<<v44-7-16,16>>^ They were carried to Sheʹchem and were laid in the tomb that Abraham had bought for a sum of silver money from the sons of Haʹmor in Sheʹchem.

[[v44-7-17]]

^<<v44-7-17,17>>^ “Just as the time was approaching to fulfill the promise that God had announced to Abraham, the people grew and multiplied in Egypt,

[[v44-7-18]]

^<<v44-7-18,18>>^ until there rose a different king over Egypt, one who did not know of Joseph.

[[v44-7-19]]

^<<v44-7-19,19>>^ This one dealt cunningly with our race and wrongfully forced the fathers to abandon their infants so that they would not be kept alive.

[[v44-7-20]]

^<<v44-7-20,20>>^ At that time Moses was born, and he was divinely beautiful.^&#42;1^ And he was nursed^&#42;2^ for three months in his father’s home.

[NOTE]
====
. Or “was beautiful in God’s sight.”
. Or “brought up.”
====

[[v44-7-21]]

^<<v44-7-21,21>>^ But when he was abandoned,^&#42;1^ the daughter of Pharʹaoh took him and brought him up as her own son.

[NOTE]
====
. Or “exposed.”
====

[[v44-7-22]]

^<<v44-7-22,22>>^ So Moses was instructed in all the wisdom of the Egyptians. In fact, he was powerful in his words and deeds.

[[v44-7-23]]

^<<v44-7-23,23>>^ “Now when he reached the age of 40, it came into his heart^&#42;1^ to make a visit on^&#42;2^ his brothers, the sons of Israel.

[NOTE]
====
. Or “he decided.”
. Or “make an inspection of.”
====

[[v44-7-24]]

^<<v44-7-24,24>>^ When he caught sight of one of them being unjustly treated, he defended him and avenged the one being abused by striking down the Egyptian.

[[v44-7-25]]

^<<v44-7-25,25>>^ He thought that his brothers would grasp that God was giving them salvation by his hand, but they did not grasp it.

[[v44-7-26]]

^<<v44-7-26,26>>^ The next day he appeared to them as they were fighting, and he tried to reconcile them in peace, saying: ‘Men, you are brothers. Why do you mistreat each other?’

[[v44-7-27]]

^<<v44-7-27,27>>^ But the one who was mistreating his neighbor pushed him away, saying: ‘Who appointed you ruler and judge over us?

[[v44-7-28]]

^<<v44-7-28,28>>^ You do not want to do away with me the way you did away with the Egyptian yesterday, do you?’

[[v44-7-29]]

^<<v44-7-29,29>>^ On hearing this, Moses fled and lived as a foreigner in the land of Midʹi·an, where he became the father of two sons.

[[v44-7-30]]

^<<v44-7-30,30>>^ “After 40 years had passed, an angel appeared to him in the wilderness of Mount Siʹnai in the flame of a burning thornbush.

[[v44-7-31]]

^<<v44-7-31,31>>^ When Moses saw it, he was amazed at the sight. But as he was approaching to investigate, Jehovah’s^&#42;1^ voice was heard:

[NOTE]
====
. See App. A5.
====

[[v44-7-32]]

^<<v44-7-32,32>>^ ‘I am the God of your forefathers, the God of Abraham and of Isaac and of Jacob.’ Moses started trembling and did not dare to investigate further.

[[v44-7-33]]

^<<v44-7-33,33>>^ Jehovah^&#42;1^ said to him: ‘Remove the sandals from your feet, for the place where you are standing is holy ground.

[NOTE]
====
. See App. A5.
====

[[v44-7-34]]

^<<v44-7-34,34>>^ I have certainly seen the oppression of my people who are in Egypt, and I have heard their groaning, and I have come down to rescue them. Now come, I will send you off to Egypt.’

[[v44-7-35]]

^<<v44-7-35,35>>^ This same Moses whom they had disowned, saying: ‘Who appointed you ruler and judge?’ is the very one God sent as both ruler and deliverer by means of the angel who appeared to him in the thornbush.

[[v44-7-36]]

^<<v44-7-36,36>>^ This man led them out, performing wonders^&#42;1^ and signs in Egypt and at the Red Sea and in the wilderness for 40 years.

[NOTE]
====
. Or “portents.”
====

[[v44-7-37]]

^<<v44-7-37,37>>^ “This is the Moses who said to the sons of Israel: ‘God will raise up for you from among your brothers a prophet like me.’

[[v44-7-38]]

^<<v44-7-38,38>>^ This is the one who came to be among the congregation in the wilderness with the angel who spoke to him on Mount Siʹnai and with our forefathers, and he received living sacred pronouncements to give us.

[[v44-7-39]]

^<<v44-7-39,39>>^ Our forefathers refused to obey him, but they pushed him aside and in their hearts they turned back to Egypt,

[[v44-7-40]]

^<<v44-7-40,40>>^ saying to Aaron: ‘Make gods for us to go ahead of us. For we do not know what has happened to this Moses, who led us out of the land of Egypt.’

[[v44-7-41]]

^<<v44-7-41,41>>^ So they made a calf in those days and brought a sacrifice to the idol and began to enjoy themselves in the works of their hands.

[[v44-7-42]]

^<<v44-7-42,42>>^ So God turned away from them and handed them over to offer sacred service to the army of heaven, just as it is written in the book of the Prophets: ‘It was not to me that you made offerings and sacrifices for 40 years in the wilderness, was it, O house of Israel?

[[v44-7-43]]

^<<v44-7-43,43>>^ But it was the tent of Moʹloch and the star of the god Reʹphan that you took up, the images that you made to worship them. So I will deport you beyond Babylon.’

[[v44-7-44]]

^<<v44-7-44,44>>^ “Our forefathers had the tent of the witness in the wilderness, just as He gave orders when speaking to Moses to make it according to the pattern he had seen.

[[v44-7-45]]

^<<v44-7-45,45>>^ And our forefathers received possession of it and brought it in with Joshua into the land possessed by the nations, whom God drove out from before our forefathers. Here it remained until the days of David.

[[v44-7-46]]

^<<v44-7-46,46>>^ He found favor in the sight of God and asked for the privilege of providing a dwelling place for the God of Jacob.

[[v44-7-47]]

^<<v44-7-47,47>>^ But it was Solʹo·mon who built a house for him.

[[v44-7-48]]

^<<v44-7-48,48>>^ However, the Most High does not dwell in houses made with hands, just as the prophet says:

[[v44-7-49]]

^<<v44-7-49,49>>^ ‘The heaven is my throne, and the earth is my footstool. What sort of house will you build for me? Jehovah^&#42;1^ says. Or where is my resting-place?

[NOTE]
====
. See App. A5.
====

[[v44-7-50]]

^<<v44-7-50,50>>^ My hand made all these things, did it not?’

[[v44-7-51]]

^<<v44-7-51,51>>^ “Obstinate men and uncircumcised in hearts and ears, you are always resisting the holy spirit; as your forefathers did, so you do.

[[v44-7-52]]

^<<v44-7-52,52>>^ Which one of the prophets did your forefathers not persecute? Yes, they killed those who announced in advance the coming of the righteous one, whose betrayers and murderers you have now become,

[[v44-7-53]]

^<<v44-7-53,53>>^ you who received the Law as transmitted by angels but have not kept it.”

[[v44-7-54]]

^<<v44-7-54,54>>^ Well, at hearing these things, they were infuriated^&#42;1^ in their hearts and began to grind their teeth at him.

[NOTE]
====
. Or “they felt cut.”
====

[[v44-7-55]]

^<<v44-7-55,55>>^ But he, being full of holy spirit, gazed into heaven and caught sight of God’s glory and of Jesus standing at God’s right hand,

[[v44-7-56]]

^<<v44-7-56,56>>^ and he said: “Look! I see the heavens opened up and the Son of man standing at God’s right hand.”

[[v44-7-57]]

^<<v44-7-57,57>>^ At this they cried out at the top of their voices and put their hands over their ears and rushed at him all together.

[[v44-7-58]]

^<<v44-7-58,58>>^ After throwing him outside the city, they began stoning him. The witnesses laid down their outer garments at the feet of a young man called Saul.

[[v44-7-59]]

^<<v44-7-59,59>>^ As they were stoning Stephen, he made this appeal: “Lord Jesus, receive my spirit.”

[[v44-7-60]]

^<<v44-7-60,60>>^ Then, kneeling down, he cried out with a strong voice: “Jehovah,^&#42;1^ do not charge this sin against them.” And after saying this, he fell asleep in death.

[NOTE]
====
. See App. A5.
====

'''

xref:044-acts/044-acts-006.adoc#v44-6-0[&#60; Capítulo Anterior] | <<v44-7-0,Topo>> | xref:044-acts/044-acts-008.adoc#v44-8-0[Próximo Capítulo &#62;]