include::./index.adoc[]

[[v44-8-0]]
=== Acts of Apostles, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-8-1]]

^<<v44-8-1,1>>^ Saul, for his part, approved of his murder.
On that day great persecution arose against the congregation that was in Jerusalem; all except the apostles were scattered throughout the regions of Ju·deʹa and Sa·marʹi·a.

[[v44-8-2]]

^<<v44-8-2,2>>^ But devout men carried Stephen away to bury him, and they made a great mourning over him.

[[v44-8-3]]

^<<v44-8-3,3>>^ Saul, though, began to ravage the congregation. He would invade one house after another, dragging out both men and women and turning them over to prison.

[[v44-8-4]]

^<<v44-8-4,4>>^ However, those who had been scattered went through the land declaring the good news of the word.

[[v44-8-5]]

^<<v44-8-5,5>>^ Now Philip went down to the city^&#42;1^ of Sa·marʹi·a and began to preach the Christ to them.

[NOTE]
====
. Or possibly, “a city.”
====

[[v44-8-6]]

^<<v44-8-6,6>>^ The crowds with one accord were paying attention to what Philip said while they listened and observed the signs he was performing.

[[v44-8-7]]

^<<v44-8-7,7>>^ For many had unclean spirits, and these would cry out with a loud voice and come out. Moreover, many who were paralyzed and lame were cured.

[[v44-8-8]]

^<<v44-8-8,8>>^ So there came to be a great deal of joy in that city.

[[v44-8-9]]

^<<v44-8-9,9>>^ Now in the city was a man named Simon, who prior to this had been practicing magical arts and amazing the nation of Sa·marʹi·a, claiming that he was somebody great.

[[v44-8-10]]

^<<v44-8-10,10>>^ All of them, from the least to the greatest, would pay attention to him and say: “This man is the Power of God, which is called Great.”

[[v44-8-11]]

^<<v44-8-11,11>>^ So they would pay attention to him because he had amazed them for quite a while by his magical arts.

[[v44-8-12]]

^<<v44-8-12,12>>^ But when they believed Philip, who was declaring the good news of the Kingdom of God and of the name of Jesus Christ, both men and women were getting baptized.

[[v44-8-13]]

^<<v44-8-13,13>>^ Simon himself also became a believer, and after being baptized, he continued with Philip; and he was amazed at seeing the signs and great powerful works taking place.

[[v44-8-14]]

^<<v44-8-14,14>>^ When the apostles in Jerusalem heard that Sa·marʹi·a had accepted the word of God, they sent Peter and John to them;

[[v44-8-15]]

^<<v44-8-15,15>>^ and these went down and prayed for them to get holy spirit.

[[v44-8-16]]

^<<v44-8-16,16>>^ For it had not yet come upon any one of them, but they had only been baptized in the name of the Lord Jesus.

[[v44-8-17]]

^<<v44-8-17,17>>^ Then they laid their hands on them, and they began to receive holy spirit.

[[v44-8-18]]

^<<v44-8-18,18>>^ Now when Simon saw that the spirit was given through the laying on of the hands of the apostles, he offered them money,

[[v44-8-19]]

^<<v44-8-19,19>>^ saying: “Give me this authority also, so that anyone on whom I lay my hands may receive holy spirit.”

[[v44-8-20]]

^<<v44-8-20,20>>^ But Peter said to him: “May your silver perish with you, because you thought you could acquire the free gift of God with money.

[[v44-8-21]]

^<<v44-8-21,21>>^ You have neither part nor share in this matter, for your heart is not straight in the sight of God.

[[v44-8-22]]

^<<v44-8-22,22>>^ So repent of this badness of yours, and supplicate Jehovah^&#42;1^ that, if possible, the wicked intention of your heart may be forgiven you;

[NOTE]
====
. See App. A5.
====

[[v44-8-23]]

^<<v44-8-23,23>>^ for I see you are a bitter poison^&#42;1^ and a slave of unrighteousness.”

[NOTE]
====
. Lit., “gall of bitterness.”
====

[[v44-8-24]]

^<<v44-8-24,24>>^ In answer Simon said to them: “Make supplication for me to Jehovah^&#42;1^ that none of the things you have said may come upon me.”

[NOTE]
====
. See App. A5.
====

[[v44-8-25]]

^<<v44-8-25,25>>^ Therefore, when they had given the witness thoroughly and had spoken the word of Jehovah,^&#42;1^ they started back toward Jerusalem, and they went declaring the good news to many villages of the Sa·marʹi·tans.

[NOTE]
====
. See App. A5.
====

[[v44-8-26]]

^<<v44-8-26,26>>^ However, Jehovah’s^&#42;1^ angel spoke to Philip, saying: “Get up and go to the south to the road that runs down from Jerusalem to Gazʹa.” (This is a desert road.)

[NOTE]
====
. See App. A5.
====

[[v44-8-27]]

^<<v44-8-27,27>>^ With that he got up and went, and look! an E·thi·oʹpi·an eunuch,^&#42;1^ a man who had authority under Can·daʹce, queen of the E·thi·oʹpi·ans, and who was in charge of all her treasure. He had gone to Jerusalem to worship,

[NOTE]
====
. Or “court official.”
====

[[v44-8-28]]

^<<v44-8-28,28>>^ and he was returning and was sitting in his chariot, reading aloud the prophet Isaiah.

[[v44-8-29]]

^<<v44-8-29,29>>^ So the spirit said to Philip: “Go over and approach this chariot.”

[[v44-8-30]]

^<<v44-8-30,30>>^ Philip ran alongside and heard him reading aloud Isaiah the prophet, and he said: “Do you actually know^&#42;1^ what you are reading?”

[NOTE]
====
. Or “understand.”
====

[[v44-8-31]]

^<<v44-8-31,31>>^ He said: “Really, how could I ever do so unless someone guided me?” So he urged Philip to get on and sit down with him.

[[v44-8-32]]

^<<v44-8-32,32>>^ Now this was the passage of Scripture that he was reading: “Like a sheep he was brought to the slaughter, and like a lamb that is silent before its shearer, so he does not open his mouth.

[[v44-8-33]]

^<<v44-8-33,33>>^ During his humiliation, justice was taken away from him. Who will tell the details of his generation? Because his life is taken away from the earth.”

[[v44-8-34]]

^<<v44-8-34,34>>^ The eunuch then said to Philip: “I beg you, about whom does the prophet say this? About himself or about some other man?”

[[v44-8-35]]

^<<v44-8-35,35>>^ Philip began to speak, and starting with this scripture, he declared to him the good news about Jesus.

[[v44-8-36]]

^<<v44-8-36,36>>^ Now as they were going along the road, they came to a body of water, and the eunuch said: “Look! Here is water; what prevents me from getting baptized?”

[[v44-8-37]]

^<<v44-8-37,37>>^ ^&#42;1^ ——

[NOTE]
====
. See App. A3.
====

[[v44-8-38]]

^<<v44-8-38,38>>^ With that he commanded the chariot to halt, and both Philip and the eunuch went down into the water, and he baptized him.

[[v44-8-39]]

^<<v44-8-39,39>>^ When they came up out of the water, Jehovah’s^&#42;1^ spirit quickly led Philip away, and the eunuch did not see him anymore, but he went on his way rejoicing.

[NOTE]
====
. See App. A5.
====

[[v44-8-40]]

^<<v44-8-40,40>>^ Philip, however, found himself in Ashʹdod, and he went through the territory and kept on declaring the good news to all the cities until he got to Caes·a·reʹa.

'''

xref:044-acts/044-acts-007.adoc#v44-7-0[&#60; Capítulo Anterior] | <<v44-8-0,Topo>> | xref:044-acts/044-acts-009.adoc#v44-9-0[Próximo Capítulo &#62;]