include::./index.adoc[]

[[v44-26-0]]
=== Acts of Apostles, 26
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-26-1]]

^<<v44-26-1,1>>^ A·gripʹpa said to Paul: “You are permitted to speak in your own behalf.” Then Paul stretched out his hand and proceeded to say in his defense:

[[v44-26-2]]

^<<v44-26-2,2>>^ “Concerning all the things of which I am accused by the Jews, King A·gripʹpa, I consider myself happy that it is before you I am to make my defense this day,

[[v44-26-3]]

^<<v44-26-3,3>>^ especially because you are an expert on all the customs as well as the controversies among the Jews. Therefore, I beg you to hear me patiently.

[[v44-26-4]]

^<<v44-26-4,4>>^ “Indeed, the manner of life I led from youth up among my people^&#42;1^ and in Jerusalem is well-known by all the Jews

[NOTE]
====
. Or “nation.”
====

[[v44-26-5]]

^<<v44-26-5,5>>^ who were previously acquainted with me, if they would be willing to testify, that according to the strictest sect of our form of worship, I lived as a Pharisee.

[[v44-26-6]]

^<<v44-26-6,6>>^ But now for the hope of the promise that was made by God to our forefathers, I stand on trial;

[[v44-26-7]]

^<<v44-26-7,7>>^ this is the same promise our 12 tribes are hoping to see fulfilled by intensely rendering him sacred service night and day. Concerning this hope I am accused by Jews, O King.

[[v44-26-8]]

^<<v44-26-8,8>>^ “Why is it considered^&#42;1^ unbelievable among you that God raises up the dead?

[NOTE]
====
. Lit., “judged.”
====

[[v44-26-9]]

^<<v44-26-9,9>>^ I, for one, was convinced that I should commit many acts of opposition against the name of Jesus the Naz·a·reneʹ.

[[v44-26-10]]

^<<v44-26-10,10>>^ This is exactly what I did in Jerusalem, and I locked up many of the holy ones in prisons, for I had received authority from the chief priests; and when they were to be executed, I cast my vote against them.

[[v44-26-11]]

^<<v44-26-11,11>>^ By punishing them often in all the synagogues, I tried to force them to recant; and since I was extremely furious with them, I went so far as to persecute them even in outlying cities.

[[v44-26-12]]

^<<v44-26-12,12>>^ “While doing this as I was traveling to Damascus with authority and a commission from the chief priests,

[[v44-26-13]]

^<<v44-26-13,13>>^ I saw at midday on the road, O King, a light beyond the brilliance of the sun flash from heaven around me and around those traveling with me.

[[v44-26-14]]

^<<v44-26-14,14>>^ And when we had all fallen to the ground, I heard a voice say to me in the Hebrew language: ‘Saul, Saul, why are you persecuting me? To keep kicking against the goads^&#42;1^ makes it hard for you.’

[NOTE]
====
. A goad is a pointed rod used to urge on an animal.
====

[[v44-26-15]]

^<<v44-26-15,15>>^ But I said: ‘Who are you, Lord?’ And the Lord said: ‘I am Jesus, whom you are persecuting.

[[v44-26-16]]

^<<v44-26-16,16>>^ But rise and stand on your feet. This is why I have appeared to you, to choose you as a servant and a witness both of things you have seen and things I will make you see respecting me.

[[v44-26-17]]

^<<v44-26-17,17>>^ And I will rescue you from this people and from the nations, to whom I am sending you

[[v44-26-18]]

^<<v44-26-18,18>>^ to open their eyes, to turn them from darkness to light and from the authority of Satan to God, so that they may receive forgiveness of sins and an inheritance among those sanctified by their faith in me.’

[[v44-26-19]]

^<<v44-26-19,19>>^ “Therefore, King A·gripʹpa, I did not become disobedient to the heavenly vision,

[[v44-26-20]]

^<<v44-26-20,20>>^ but to those in Damascus first and then to those in Jerusalem, and over all the country of Ju·deʹa, and also to the nations, I was bringing the message that they should repent and turn to God by doing works that befit repentance.

[[v44-26-21]]

^<<v44-26-21,21>>^ This is why the Jews seized me in the temple and tried to kill me.

[[v44-26-22]]

^<<v44-26-22,22>>^ However, because I have experienced the help that is from God, I continue to this day bearing witness to both small and great, saying nothing except what the Prophets as well as Moses stated was going to take place—

[[v44-26-23]]

^<<v44-26-23,23>>^ that the Christ was to suffer and that as the first to be resurrected from the dead, he was going to proclaim light both to this people and to the nations.”

[[v44-26-24]]

^<<v44-26-24,24>>^ Now as Paul was saying these things in his defense, Festus said in a loud voice: “You are going out of your mind, Paul! Great learning is driving you out of your mind!”

[[v44-26-25]]

^<<v44-26-25,25>>^ But Paul said: “I am not going out of my mind, Your Excellency Festus, but I am speaking words of truth and of a sound mind.

[[v44-26-26]]

^<<v44-26-26,26>>^ For a fact, the king to whom I am speaking so freely well knows about these things; I am convinced that not one of these things escapes his notice, for none of this has been done in a corner.

[[v44-26-27]]

^<<v44-26-27,27>>^ Do you, King A·gripʹpa, believe the Prophets? I know that you believe.”

[[v44-26-28]]

^<<v44-26-28,28>>^ But A·gripʹpa said to Paul: “In a short time you would persuade me to become a Christian.”

[[v44-26-29]]

^<<v44-26-29,29>>^ At this Paul said: “I wish to God that whether in a short time or in a long time, not only you but also all those who hear me today would become men such as I am, with the exception of these prison bonds.”

[[v44-26-30]]

^<<v44-26-30,30>>^ Then the king rose and so did the governor and Bernice and the men seated with them.

[[v44-26-31]]

^<<v44-26-31,31>>^ But as they were leaving, they began saying to one another: “This man is doing nothing deserving of death or prison bonds.”

[[v44-26-32]]

^<<v44-26-32,32>>^ A·gripʹpa then said to Festus: “This man could have been released if he had not appealed to Caesar.”

'''

xref:044-acts/044-acts-025.adoc#v44-25-0[&#60; Capítulo Anterior] | <<v44-26-0,Topo>> | xref:044-acts/044-acts-027.adoc#v44-27-0[Próximo Capítulo &#62;]