include::./index.adoc[]

[[v44-20-0]]
=== Acts of Apostles, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-20-1]]

^<<v44-20-1,1>>^ When the uproar had subsided, Paul sent for the disciples, and after he had encouraged them and said farewell, he began his journey to Mac·e·doʹni·a.

[[v44-20-2]]

^<<v44-20-2,2>>^ After going through those regions and giving many words of encouragement to the ones there, he arrived in Greece.

[[v44-20-3]]

^<<v44-20-3,3>>^ He spent three months there, but because a plot was hatched against him by the Jews when he was about to set sail for Syria, he made up his mind to return through Mac·e·doʹni·a.

[[v44-20-4]]

^<<v44-20-4,4>>^ He was accompanied by Sopʹa·ter the son of Pyrʹrhus of Be·roeʹa, Ar·is·tarʹchus and Se·cunʹdus of the Thes·sa·loʹni·ans, Gaʹius of Derʹbe, Timothy and, from the province of Asia, Tychʹi·cus and Trophʹi·mus.

[[v44-20-5]]

^<<v44-20-5,5>>^ These men went on ahead and were waiting for us in Troʹas;

[[v44-20-6]]

^<<v44-20-6,6>>^ but we put out to sea from Phi·lipʹpi after the days of the Unleavened Bread, and within five days we came to them in Troʹas, and there we spent seven days.

[[v44-20-7]]

^<<v44-20-7,7>>^ On the first day of the week, when we were gathered together to have a meal, Paul began addressing them, as he was going to depart the next day; and he prolonged his speech until midnight.

[[v44-20-8]]

^<<v44-20-8,8>>^ So there were quite a few lamps in the upper room where we were gathered together.

[[v44-20-9]]

^<<v44-20-9,9>>^ Seated at the window, a young man named Euʹty·chus sank into a deep sleep while Paul kept talking, and overcome by sleep, he fell down from the third story and was picked up dead.

[[v44-20-10]]

^<<v44-20-10,10>>^ But Paul went downstairs, threw himself on him and embraced him, and said: “Stop making a commotion, for he is alive.”^&#42;1^

[NOTE]
====
. Or “for his soul is in him.”
====

[[v44-20-11]]

^<<v44-20-11,11>>^ He then went upstairs and began the meal^&#42;1^ and ate. He continued conversing for quite a while, until daybreak, and then he departed.

[NOTE]
====
. Lit., “broke the bread.”
====

[[v44-20-12]]

^<<v44-20-12,12>>^ So they took the boy away alive and were comforted beyond measure.

[[v44-20-13]]

^<<v44-20-13,13>>^ We now went ahead to the ship and set sail for Asʹsos, where we were intending to take Paul aboard, for after giving instructions to this effect, he was intending to go there on foot.

[[v44-20-14]]

^<<v44-20-14,14>>^ So when he caught up with us in Asʹsos, we took him aboard and went to Mit·y·leʹne.

[[v44-20-15]]

^<<v44-20-15,15>>^ And sailing away from there the next day, we arrived off Chiʹos, but the day after that, we touched at Saʹmos, and on the following day, we arrived at Mi·leʹtus.

[[v44-20-16]]

^<<v44-20-16,16>>^ Paul had decided to sail past Ephʹe·sus so as not to spend any time in the province of Asia, for he was hurrying to get to Jerusalem on the day of the Festival of Pentecost if he possibly could.

[[v44-20-17]]

^<<v44-20-17,17>>^ However, from Mi·leʹtus he sent word to Ephʹe·sus and called for the elders of the congregation.

[[v44-20-18]]

^<<v44-20-18,18>>^ When they came to him, he said to them: “You well know how I conducted myself among you from the first day I stepped into the province of Asia,

[[v44-20-19]]

^<<v44-20-19,19>>^ slaving for the Lord with all humility^&#42;1^ and with tears and trials that befell me by the plots of the Jews,

[NOTE]
====
. Or “lowliness of mind.”
====

[[v44-20-20]]

^<<v44-20-20,20>>^ while I did not hold back from telling you any of the things that were profitable^&#42;1^ nor from teaching you publicly and from house to house.

[NOTE]
====
. Or “for your good.”
====

[[v44-20-21]]

^<<v44-20-21,21>>^ But I thoroughly bore witness both to Jews and to Greeks about repentance toward God and faith in our Lord Jesus.

[[v44-20-22]]

^<<v44-20-22,22>>^ And now look! bound in^&#42;1^ the spirit, I am traveling to Jerusalem, although not knowing what will happen to me there,

[NOTE]
====
. Or “compelled by.”
====

[[v44-20-23]]

^<<v44-20-23,23>>^ except that from city to city the holy spirit repeatedly bears witness to me, saying that imprisonment and tribulations are waiting for me.

[[v44-20-24]]

^<<v44-20-24,24>>^ Nevertheless, I do not consider my own life^&#42;1^ of any importance to me,^&#42;2^ if only I may finish my course and the ministry that I received from the Lord Jesus, to bear thorough witness to the good news of the undeserved kindness of God.

[NOTE]
====
. Or “soul.”
. Or “of any value to me whatsoever.”
====

[[v44-20-25]]

^<<v44-20-25,25>>^ “And now look! I know that none of you among whom I preached the Kingdom will ever see my face again.

[[v44-20-26]]

^<<v44-20-26,26>>^ So I call you to witness this very day that I am clean from the blood of all men,

[[v44-20-27]]

^<<v44-20-27,27>>^ for I have not held back from telling you all the counsel^&#42;1^ of God.

[NOTE]
====
. Or “the whole purpose.”
====

[[v44-20-28]]

^<<v44-20-28,28>>^ Pay attention to yourselves and to all the flock, among which the holy spirit has appointed you overseers, to shepherd the congregation of God, which he purchased with the blood of his own Son.

[[v44-20-29]]

^<<v44-20-29,29>>^ I know that after my going away oppressive wolves will enter in among you and will not treat the flock with tenderness,

[[v44-20-30]]

^<<v44-20-30,30>>^ and from among you yourselves men will rise and speak twisted things to draw away the disciples after themselves.

[[v44-20-31]]

^<<v44-20-31,31>>^ “Therefore keep awake, and bear in mind that for three years, night and day, I never stopped admonishing each one of you with tears.

[[v44-20-32]]

^<<v44-20-32,32>>^ And now I entrust you to God and to the word of his undeserved kindness, which word can build you up and give you the inheritance among all the sanctified ones.

[[v44-20-33]]

^<<v44-20-33,33>>^ I have desired no man’s silver or gold or clothing.

[[v44-20-34]]

^<<v44-20-34,34>>^ You yourselves know that these hands have provided for my own needs and the needs of those with me.

[[v44-20-35]]

^<<v44-20-35,35>>^ I have shown you in all things that by working hard in this way, you must assist those who are weak and must keep in mind the words of the Lord Jesus, when he himself said: ‘There is more happiness in giving than there is in receiving.’”

[[v44-20-36]]

^<<v44-20-36,36>>^ And when he had said these things, he knelt down with all of them and prayed.

[[v44-20-37]]

^<<v44-20-37,37>>^ Indeed, quite a bit of weeping broke out among them all, and they embraced Paul^&#42;1^ and affectionately^&#42;2^ kissed him,

[NOTE]
====
. Lit., “fell upon Paul’s neck.”
. Or “tenderly.”
====

[[v44-20-38]]

^<<v44-20-38,38>>^ for they were especially pained at the word he had spoken that they would not see his face anymore. Then they accompanied him to the ship.

'''

xref:044-acts/044-acts-019.adoc#v44-19-0[&#60; Capítulo Anterior] | <<v44-20-0,Topo>> | xref:044-acts/044-acts-021.adoc#v44-21-0[Próximo Capítulo &#62;]