include::./index.adoc[]

[[v44-1-0]]
=== Acts of Apostles, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-1-1]]

^<<v44-1-1,1>>^ The first account, O The·ophʹi·lus, I composed about all the things Jesus started to do and to teach

[[v44-1-2]]

^<<v44-1-2,2>>^ until the day that he was taken up, after he had given instructions through holy spirit to the apostles he had chosen.

[[v44-1-3]]

^<<v44-1-3,3>>^ After he had suffered, he showed himself alive to them by many convincing proofs. He was seen by them throughout 40 days, and he was speaking about the Kingdom of God.

[[v44-1-4]]

^<<v44-1-4,4>>^ While he was meeting with them, he ordered them: “Do not leave Jerusalem, but keep waiting for what the Father has promised, about which you heard from me;

[[v44-1-5]]

^<<v44-1-5,5>>^ for John, indeed, baptized with water, but you will be baptized with holy spirit not many days after this.”

[[v44-1-6]]

^<<v44-1-6,6>>^ So when they had assembled, they asked him: “Lord, are you restoring the kingdom to Israel at this time?”

[[v44-1-7]]

^<<v44-1-7,7>>^ He said to them: “It does not belong to you to know the times or seasons that the Father has placed in his own jurisdiction.^&#42;1^

[NOTE]
====
. Or “authority.”
====

[[v44-1-8]]

^<<v44-1-8,8>>^ But you will receive power when the holy spirit comes upon you, and you will be witnesses of me in Jerusalem, in all Ju·deʹa and Sa·marʹi·a, and to the most distant part^&#42;1^ of the earth.”

[NOTE]
====
. Or “to the ends.”
====

[[v44-1-9]]

^<<v44-1-9,9>>^ After he had said these things, while they were looking on, he was lifted up and a cloud caught him up from their sight.

[[v44-1-10]]

^<<v44-1-10,10>>^ And as they were gazing into the sky while he was on his way, suddenly two men in white garments stood beside them

[[v44-1-11]]

^<<v44-1-11,11>>^ and said: “Men of Galʹi·lee, why do you stand looking into the sky? This Jesus who was taken up from you into the sky will come in the same manner as you have seen him going into the sky.”

[[v44-1-12]]

^<<v44-1-12,12>>^ Then they returned to Jerusalem from a mountain called the Mount of Olives, which is near Jerusalem, only a sabbath day’s journey away.

[[v44-1-13]]

^<<v44-1-13,13>>^ When they arrived, they went up into the upper room where they were staying. There were Peter as well as John and James and Andrew, Philip and Thomas, Bar·tholʹo·mew and Matthew, James the son of Al·phaeʹus, and Simon the zealous one, and Judas the son of James.

[[v44-1-14]]

^<<v44-1-14,14>>^ With one purpose all of these were persisting in prayer, together with some women and Mary the mother of Jesus and with his brothers.

[[v44-1-15]]

^<<v44-1-15,15>>^ During those days Peter stood up in the midst of the brothers (the number^&#42;1^ of people was altogether about 120) and said:

[NOTE]
====
. Or “crowd.”
====

[[v44-1-16]]

^<<v44-1-16,16>>^ “Men, brothers, it was necessary for the scripture to be fulfilled that the holy spirit spoke prophetically through David about Judas, who became a guide to those who arrested Jesus.

[[v44-1-17]]

^<<v44-1-17,17>>^ For he had been numbered among us and he obtained a share in this ministry.

[[v44-1-18]]

^<<v44-1-18,18>>^ (This very man, therefore, purchased a field with the wages for unrighteousness, and falling headfirst, his body burst open^&#42;1^ and all his insides spilled out.

[NOTE]
====
. Or “he burst open in the middle.”
====

[[v44-1-19]]

^<<v44-1-19,19>>^ This became known to all the inhabitants of Jerusalem, so that the field was called in their language A·kelʹda·ma, that is, “Field of Blood.”)

[[v44-1-20]]

^<<v44-1-20,20>>^ For it is written in the book of Psalms, ‘Let his dwelling become desolate, and let there be no inhabitant in it’ and, ‘His office of oversight let someone else take.’

[[v44-1-21]]

^<<v44-1-21,21>>^ It is therefore necessary that of the men who accompanied us during all the time in which the Lord Jesus carried on his activities^&#42;1^ among us,

[NOTE]
====
. Lit., “went in and out.”
====

[[v44-1-22]]

^<<v44-1-22,22>>^ starting with his baptism by John until the day he was taken up from us, one of these men should become a witness with us of his resurrection.”

[[v44-1-23]]

^<<v44-1-23,23>>^ So they proposed two, Joseph called Barʹsab·bas, who was also called Justus, and Mat·thiʹas.

[[v44-1-24]]

^<<v44-1-24,24>>^ Then they prayed and said: “You, O Jehovah,^&#42;1^ who know the hearts of all, designate which one of these two men you have chosen

[NOTE]
====
. See App. A5.
====

[[v44-1-25]]

^<<v44-1-25,25>>^ to take the place of this ministry and apostleship, from which Judas deviated to go to his own place.”

[[v44-1-26]]

^<<v44-1-26,26>>^ So they cast lots over them, and the lot fell to Mat·thiʹas, and he was counted^&#42;1^ along with the 11 apostles.

[NOTE]
====
. Or “reckoned,” that is, viewed the same as the other 11.
====

'''

xref:043-john/043-john-021.adoc#v43-21-0[&#60; Capítulo Anterior] | <<v44-1-0,Topo>> | xref:044-acts/044-acts-002.adoc#v44-2-0[Próximo Capítulo &#62;]