include::./index.adoc[]

[[v44-19-0]]
=== Acts of Apostles, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-19-1]]

^<<v44-19-1,1>>^ In the course of events, while A·polʹlos was in Corinth, Paul went through the inland regions and came down to Ephʹe·sus. There he found some disciples

[[v44-19-2]]

^<<v44-19-2,2>>^ and said to them: “Did you receive holy spirit when you became believers?” They replied to him: “Why, we have never heard that there is a holy spirit.”

[[v44-19-3]]

^<<v44-19-3,3>>^ So he said: “In what, then, were you baptized?” They said: “In John’s baptism.”

[[v44-19-4]]

^<<v44-19-4,4>>^ Paul said: “John baptized with the baptism in symbol of repentance, telling the people to believe in the one coming after him, that is, in Jesus.”

[[v44-19-5]]

^<<v44-19-5,5>>^ On hearing this, they got baptized in the name of the Lord Jesus.

[[v44-19-6]]

^<<v44-19-6,6>>^ And when Paul laid his hands on them, the holy spirit came upon them, and they began speaking in foreign languages and prophesying.

[[v44-19-7]]

^<<v44-19-7,7>>^ There were about 12 men in all.

[[v44-19-8]]

^<<v44-19-8,8>>^ Entering the synagogue, for three months he spoke with boldness, giving talks and reasoning persuasively about the Kingdom of God.

[[v44-19-9]]

^<<v44-19-9,9>>^ But when some stubbornly refused to believe,^&#42;1^ speaking injuriously about The Way before the crowd, he withdrew from them and separated the disciples from them, giving talks daily in the school auditorium of Ty·ranʹnus.

[NOTE]
====
. Or “went on hardening themselves and not believing.”
====

[[v44-19-10]]

^<<v44-19-10,10>>^ This went on for two years, so that all those living in the province of Asia heard the word of the Lord, both Jews and Greeks.

[[v44-19-11]]

^<<v44-19-11,11>>^ And God kept performing extraordinary powerful works through the hands of Paul,

[[v44-19-12]]

^<<v44-19-12,12>>^ so that even cloths and aprons that had touched his body were carried to the sick, and the diseases left them, and the wicked spirits came out.

[[v44-19-13]]

^<<v44-19-13,13>>^ But some of the Jews who traveled around casting out demons also tried to use the name of the Lord Jesus over those who had wicked spirits; they would say: “I solemnly charge you by Jesus whom Paul preaches.”

[[v44-19-14]]

^<<v44-19-14,14>>^ Now there were seven sons of a Jewish chief priest named Sceʹva doing this.

[[v44-19-15]]

^<<v44-19-15,15>>^ But in answer the wicked spirit said to them: “I know Jesus and I am acquainted with Paul; but who are you?”

[[v44-19-16]]

^<<v44-19-16,16>>^ At that the man with the wicked spirit leaped on them, overpowered them one after the other, and prevailed against them, so that they fled naked and wounded out of that house.

[[v44-19-17]]

^<<v44-19-17,17>>^ This became known to all, both the Jews and the Greeks who lived in Ephʹe·sus; and fear fell upon them all, and the name of the Lord Jesus went on being magnified.

[[v44-19-18]]

^<<v44-19-18,18>>^ And many of those who had become believers would come and confess and report their practices openly.

[[v44-19-19]]

^<<v44-19-19,19>>^ Indeed, quite a number of those who practiced magical arts brought their books together and burned them up before everybody. And they calculated their value and found them worth 50,000 pieces of silver.

[[v44-19-20]]

^<<v44-19-20,20>>^ Thus in a mighty way, the word of Jehovah^&#42;1^ kept growing and prevailing.

[NOTE]
====
. See App. A5.
====

[[v44-19-21]]

^<<v44-19-21,21>>^ After these things had taken place, Paul resolved in his spirit that after going through Mac·e·doʹni·a and A·chaʹia, he would travel to Jerusalem. He said: “After going there, I must also see Rome.”

[[v44-19-22]]

^<<v44-19-22,22>>^ So he sent to Mac·e·doʹni·a two of those who ministered to him, Timothy and E·rasʹtus, but he himself stayed on for some time in the province of Asia.

[[v44-19-23]]

^<<v44-19-23,23>>^ At that time quite a disturbance arose concerning The Way.

[[v44-19-24]]

^<<v44-19-24,24>>^ For a man named De·meʹtri·us, a silversmith who made silver shrines of Arʹte·mis, brought considerable profit to the craftsmen.

[[v44-19-25]]

^<<v44-19-25,25>>^ He gathered them and others who worked at such things and said: “Men, you well know that from this business comes our prosperity.

[[v44-19-26]]

^<<v44-19-26,26>>^ Now you see and hear how, not only in Ephʹe·sus but in nearly all the province of Asia, this Paul has persuaded a considerable crowd and turned them to another opinion, saying that the gods made by hands are not really gods.

[[v44-19-27]]

^<<v44-19-27,27>>^ Moreover, the danger exists not only that this business of ours will come into disrepute but also that the temple of the great goddess Arʹte·mis will be viewed as nothing, and she who is worshipped in the whole province of Asia and the inhabited earth will be deprived of her magnificence.”

[[v44-19-28]]

^<<v44-19-28,28>>^ Hearing this and becoming full of anger, the men began crying out: “Great is Arʹte·mis of the E·pheʹsians!”

[[v44-19-29]]

^<<v44-19-29,29>>^ So the city became filled with confusion, and all together they rushed into the theater, dragging along with them Gaʹius and Ar·is·tarʹchus, Mac·e·doʹni·ans, traveling companions of Paul.

[[v44-19-30]]

^<<v44-19-30,30>>^ For his part, Paul was willing to go inside to the people, but the disciples would not permit him.

[[v44-19-31]]

^<<v44-19-31,31>>^ Even some of the commissioners of festivals and games who were friendly to him sent word to him, pleading with him not to risk going into the theater.

[[v44-19-32]]

^<<v44-19-32,32>>^ Some were, in fact, crying out one thing and others something else; for the assembly was in confusion and the majority of them did not know the reason why they had come together.

[[v44-19-33]]

^<<v44-19-33,33>>^ So they brought Alexander out of the crowd, the Jews shoving him forward, and Alexander motioned with his hand and wanted to make his defense to the people.

[[v44-19-34]]

^<<v44-19-34,34>>^ But when they recognized that he was a Jew, they all started shouting in unison for about two hours: “Great is Arʹte·mis of the E·pheʹsians!”

[[v44-19-35]]

^<<v44-19-35,35>>^ When the city recorder had finally quieted the crowd, he said: “Men of Ephʹe·sus, who really is there among men who does not know that the city of the E·pheʹsians is the temple keeper of the great Arʹte·mis and of the image that fell from heaven?

[[v44-19-36]]

^<<v44-19-36,36>>^ Since these things are indisputable, you should keep calm and not act rashly.

[[v44-19-37]]

^<<v44-19-37,37>>^ For you have brought these men here who are neither robbers of temples nor blasphemers of our goddess.

[[v44-19-38]]

^<<v44-19-38,38>>^ So if De·meʹtri·us and the craftsmen with him do have a case against someone, court days are held and there are proconsuls;^&#42;1^ let them bring charges against one another.

[NOTE]
====
. A proconsul was the Roman governor of a province. See Glossary.
====

[[v44-19-39]]

^<<v44-19-39,39>>^ But if you are searching for anything beyond that, it must be decided in a regular assembly.

[[v44-19-40]]

^<<v44-19-40,40>>^ For we are really in danger of being charged with sedition over today’s affair, since there are no grounds we could present as a reason for this disorderly mob.”

[[v44-19-41]]

^<<v44-19-41,41>>^ And after saying this, he dismissed the assembly.

'''

xref:044-acts/044-acts-018.adoc#v44-18-0[&#60; Capítulo Anterior] | <<v44-19-0,Topo>> | xref:044-acts/044-acts-020.adoc#v44-20-0[Próximo Capítulo &#62;]