include::./index.adoc[]

[[v44-18-0]]
=== Acts of Apostles, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-18-1]]

^<<v44-18-1,1>>^ After this he departed from Athens and came to Corinth.

[[v44-18-2]]

^<<v44-18-2,2>>^ And he found a Jew named Aqʹui·la, a native of Ponʹtus who had recently come from Italy with Pris·cilʹla his wife, because Claudius had ordered all the Jews to leave Rome. So he went to them,

[[v44-18-3]]

^<<v44-18-3,3>>^ and because he had the same trade, he stayed at their home and worked with them, for they were tentmakers by trade.

[[v44-18-4]]

^<<v44-18-4,4>>^ He would give a talk^&#42;1^ in the synagogue every sabbath and would persuade Jews and Greeks.

[NOTE]
====
. Or “He would reason with them.”
====

[[v44-18-5]]

^<<v44-18-5,5>>^ When, now, both Silas and Timothy came down from Mac·e·doʹni·a, Paul began to be intensely occupied with the word, witnessing to the Jews to prove that Jesus is the Christ.

[[v44-18-6]]

^<<v44-18-6,6>>^ But after they kept on opposing him and speaking abusively, he shook out his garments and said to them: “Let your blood be on your own heads. I am clean. From now on I will go to people of the nations.”

[[v44-18-7]]

^<<v44-18-7,7>>^ So he transferred from there^&#42;1^ and went into the house of a man named Titius Justus, a worshipper of God, whose house adjoined the synagogue.

[NOTE]
====
. That is, the synagogue.
====

[[v44-18-8]]

^<<v44-18-8,8>>^ But Crisʹpus, the presiding officer of the synagogue, became a believer in the Lord, along with all his household. And many of the Corinthians who heard began to believe and be baptized.

[[v44-18-9]]

^<<v44-18-9,9>>^ Moreover, the Lord said to Paul in a vision by night: “Do not be afraid, but keep on speaking and do not keep silent,

[[v44-18-10]]

^<<v44-18-10,10>>^ for I am with you and no man will assault you to harm you; for I have many people in this city.”

[[v44-18-11]]

^<<v44-18-11,11>>^ So he stayed there for a year and six months, teaching the word of God among them.

[[v44-18-12]]

^<<v44-18-12,12>>^ While Galʹli·o was proconsul^&#42;1^ of A·chaʹia, the Jews made a concerted attack against Paul and led him to the judgment seat,

[NOTE]
====
. The Roman governor of a province. See Glossary.
====

[[v44-18-13]]

^<<v44-18-13,13>>^ saying: “This man is persuading people to worship God in a way contrary to the law.”

[[v44-18-14]]

^<<v44-18-14,14>>^ But as Paul was about to speak, Galʹli·o said to the Jews: “If, indeed, it were some wrong or a serious crime, O Jews, it would be reasonable for me to hear you out patiently.

[[v44-18-15]]

^<<v44-18-15,15>>^ But if it is controversies over speech and names and your own law, you yourselves must see to it. I do not wish to be a judge of these things.”

[[v44-18-16]]

^<<v44-18-16,16>>^ With that he drove them away from the judgment seat.

[[v44-18-17]]

^<<v44-18-17,17>>^ So they all seized Sosʹthe·nes, the presiding officer of the synagogue, and began beating him in front of the judgment seat. But Galʹli·o would not get involved at all with these things.

[[v44-18-18]]

^<<v44-18-18,18>>^ However, after staying quite a few days longer, Paul said good-bye to the brothers and sailed away for Syria, accompanied by Pris·cilʹla and Aqʹui·la. He had his hair clipped short in Cenʹchre·ae, for he had made a vow.

[[v44-18-19]]

^<<v44-18-19,19>>^ So they arrived at Ephʹe·sus, and he left them there; but he entered the synagogue and reasoned with the Jews.

[[v44-18-20]]

^<<v44-18-20,20>>^ Although they kept requesting him to stay longer, he would not consent

[[v44-18-21]]

^<<v44-18-21,21>>^ but said good-bye and told them: “I will return to you again, if Jehovah^&#42;1^ is willing.” And he put out to sea from Ephʹe·sus

[NOTE]
====
. See App. A5.
====

[[v44-18-22]]

^<<v44-18-22,22>>^ and came down to Caes·a·reʹa. And he went up^&#42;1^ and greeted the congregation and then went down to Antioch.

[NOTE]
====
. To Jerusalem, apparently.
====

[[v44-18-23]]

^<<v44-18-23,23>>^ After spending some time there, he departed and went from place to place through the country of Ga·laʹti·a and Phrygʹi·a, strengthening all the disciples.

[[v44-18-24]]

^<<v44-18-24,24>>^ Now a Jew named A·polʹlos, a native of Alexandria, arrived in Ephʹe·sus; he was an eloquent man who was well-versed in the Scriptures.

[[v44-18-25]]

^<<v44-18-25,25>>^ This man had been instructed^&#42;1^ in the way of Jehovah,^&#42;2^ and aglow with the spirit, he was speaking and teaching accurately the things about Jesus, but he was acquainted only with the baptism of John.

[NOTE]
====
. Or “orally instructed.”
. See App. A5.
====

[[v44-18-26]]

^<<v44-18-26,26>>^ He began to speak boldly in the synagogue, and when Pris·cilʹla and Aqʹui·la heard him, they took him into their company and explained the way of God more accurately to him.

[[v44-18-27]]

^<<v44-18-27,27>>^ Further, because he wanted to go across to A·chaʹia, the brothers wrote to the disciples, urging them to receive him kindly. So when he got there, he greatly helped those who through God’s undeserved kindness had become believers;

[[v44-18-28]]

^<<v44-18-28,28>>^ for publicly and with great intensity he thoroughly proved the Jews to be wrong, showing them from the Scriptures that Jesus is the Christ.

'''

xref:044-acts/044-acts-017.adoc#v44-17-0[&#60; Capítulo Anterior] | <<v44-18-0,Topo>> | xref:044-acts/044-acts-019.adoc#v44-19-0[Próximo Capítulo &#62;]