include::./index.adoc[]

[[v44-3-0]]
=== Acts of Apostles, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-3-1]]

^<<v44-3-1,1>>^ Now Peter and John were going up into the temple for the hour of prayer, the ninth hour,^&#42;1^

[NOTE]
====
. That is, about 3:00 p.m.
====

[[v44-3-2]]

^<<v44-3-2,2>>^ and a man who was lame from birth was being carried. Every day they would put him near the temple door that was called Beautiful, so he could ask for gifts of mercy from those entering the temple.

[[v44-3-3]]

^<<v44-3-3,3>>^ When he caught sight of Peter and John about to go into the temple, he began asking for gifts of mercy.

[[v44-3-4]]

^<<v44-3-4,4>>^ But Peter, together with John, looked straight at him and said: “Look at us.”

[[v44-3-5]]

^<<v44-3-5,5>>^ So he fixed his attention on them, expecting to get something from them.

[[v44-3-6]]

^<<v44-3-6,6>>^ However, Peter said: “Silver and gold I do not possess, but what I do have is what I give you. In the name of Jesus Christ the Naz·a·reneʹ, walk!”

[[v44-3-7]]

^<<v44-3-7,7>>^ With that he took hold of him by the right hand and raised him up. Instantly his feet and his ankles were made firm;

[[v44-3-8]]

^<<v44-3-8,8>>^ and leaping to his feet, he began walking and went with them into the temple, walking and leaping and praising God.

[[v44-3-9]]

^<<v44-3-9,9>>^ And all the people saw him walking and praising God.

[[v44-3-10]]

^<<v44-3-10,10>>^ And they began to recognize him, that this was the man who used to sit waiting for gifts of mercy at the Beautiful Gate of the temple, and they were completely astonished and ecstatic about what had happened to him.

[[v44-3-11]]

^<<v44-3-11,11>>^ While the man was still holding on to Peter and John, all the people ran together to them at what was called Solʹo·mon’s Colonnade, completely surprised.

[[v44-3-12]]

^<<v44-3-12,12>>^ When Peter saw this, he said to the people: “Men of Israel, why are you so amazed at this, and why are you staring at us as though by personal power or godly devotion we have made him walk?

[[v44-3-13]]

^<<v44-3-13,13>>^ The God of Abraham and of Isaac and of Jacob, the God of our forefathers, has glorified his Servant, Jesus, whom you handed over and disowned before Pilate, even though he had decided to release him.

[[v44-3-14]]

^<<v44-3-14,14>>^ Yes, you disowned that holy and righteous one, and you asked for a man who was a murderer to be given to you,

[[v44-3-15]]

^<<v44-3-15,15>>^ whereas you killed the Chief Agent of life. But God raised him up from the dead, of which fact we are witnesses.

[[v44-3-16]]

^<<v44-3-16,16>>^ And through his name, and by our faith in his name, this man whom you see and know has been made strong. The faith that is through him has made this man completely healthy in front of all of you.

[[v44-3-17]]

^<<v44-3-17,17>>^ And now, brothers, I know that you acted in ignorance, just as your rulers also did.

[[v44-3-18]]

^<<v44-3-18,18>>^ But in this way God has fulfilled the things he announced beforehand through the mouth of all the prophets, that his Christ would suffer.

[[v44-3-19]]

^<<v44-3-19,19>>^ “Repent, therefore, and turn around so as to get your sins blotted out, so that seasons of refreshing may come from Jehovah himself^&#42;1^

[NOTE]
====
. Lit., “from the face of Jehovah.” See App. A5.
====

[[v44-3-20]]

^<<v44-3-20,20>>^ and he may send the Christ appointed for you, Jesus.

[[v44-3-21]]

^<<v44-3-21,21>>^ Heaven must hold this one within itself until the times of restoration of all things of which God spoke through the mouth of his holy prophets of old.

[[v44-3-22]]

^<<v44-3-22,22>>^ In fact, Moses said: ‘Jehovah^&#42;1^ your God will raise up for you from among your brothers a prophet like me. You must listen to whatever he tells you.

[NOTE]
====
. See App. A5.
====

[[v44-3-23]]

^<<v44-3-23,23>>^ Indeed, anyone^&#42;1^ who does not listen to that Prophet will be completely destroyed from among the people.’

[NOTE]
====
. Or “any soul.”
====

[[v44-3-24]]

^<<v44-3-24,24>>^ And all the prophets from Samuel and those who followed him, as many as have spoken, have also plainly declared these days.

[[v44-3-25]]

^<<v44-3-25,25>>^ You are the sons of the prophets and of the covenant that God made with your forefathers, saying to Abraham: ‘And by means of your offspring^&#42;1^ all the families of the earth will be blessed.’

[NOTE]
====
. Lit., “seed.”
====

[[v44-3-26]]

^<<v44-3-26,26>>^ God, after raising up his Servant, sent him to you first to bless you by turning each one of you away from your wicked deeds.”

'''

xref:044-acts/044-acts-002.adoc#v44-2-0[&#60; Capítulo Anterior] | <<v44-3-0,Topo>> | xref:044-acts/044-acts-004.adoc#v44-4-0[Próximo Capítulo &#62;]