include::./index.adoc[]

[[v44-14-0]]
=== Acts of Apostles, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-14-1]]

^<<v44-14-1,1>>^ Now in I·coʹni·um they entered together into the synagogue of the Jews and spoke in such a manner that a great multitude of both Jews and Greeks became believers.

[[v44-14-2]]

^<<v44-14-2,2>>^ But the Jews who did not believe stirred up and wrongly influenced the people^&#42;1^ of the nations against the brothers.

[NOTE]
====
. Or “the souls of the people.”
====

[[v44-14-3]]

^<<v44-14-3,3>>^ So they spent considerable time speaking with boldness by the authority of Jehovah,^&#42;1^ who bore witness to the word of his undeserved kindness by allowing signs and wonders^&#42;2^ to be performed through them.

[NOTE]
====
. See App. A5.
. Or “portents.”
====

[[v44-14-4]]

^<<v44-14-4,4>>^ However, the multitude of the city was divided; some were for the Jews but others for the apostles.

[[v44-14-5]]

^<<v44-14-5,5>>^ When both the people of the nations and the Jews with their rulers made an attempt to treat them insolently and stone them,

[[v44-14-6]]

^<<v44-14-6,6>>^ they were informed of it, and they fled to the cities of Lyc·a·oʹni·a, Lysʹtra and Derʹbe, and to the surrounding country.

[[v44-14-7]]

^<<v44-14-7,7>>^ There they went on declaring the good news.

[[v44-14-8]]

^<<v44-14-8,8>>^ Now in Lysʹtra there was a man sitting down whose feet were crippled. He was lame from birth and had never walked.

[[v44-14-9]]

^<<v44-14-9,9>>^ This man was listening to Paul as he was speaking. Paul, looking intently at him and seeing that he had faith to be made well,

[[v44-14-10]]

^<<v44-14-10,10>>^ said with a loud voice: “Stand up on your feet.” So the man leaped up and began walking.

[[v44-14-11]]

^<<v44-14-11,11>>^ When the crowds saw what Paul had done, they cried out in the Lyc·a·oʹni·an language: “The gods have become like humans and have come down to us!”

[[v44-14-12]]

^<<v44-14-12,12>>^ And they started calling Barʹna·bas Zeus, but Paul Herʹmes, since he was taking the lead in speaking.

[[v44-14-13]]

^<<v44-14-13,13>>^ And the priest of Zeus, whose temple was at the entrance of the city, brought bulls and garlands^&#42;1^ to the gates and wanted to offer sacrifices with the crowds.

[NOTE]
====
. Or “wreaths.”
====

[[v44-14-14]]

^<<v44-14-14,14>>^ However, when the apostles Barʹna·bas and Paul heard of it, they ripped their garments and leaped out into the crowd and cried out:

[[v44-14-15]]

^<<v44-14-15,15>>^ “Men, why are you doing these things? We too are humans having the same infirmities as you have. And we are declaring the good news to you, for you to turn from these vain things to the living God, who made the heaven and the earth and the sea and all the things in them.

[[v44-14-16]]

^<<v44-14-16,16>>^ In past generations he permitted all the nations to go on in their ways,

[[v44-14-17]]

^<<v44-14-17,17>>^ although he did not leave himself without witness in that he did good, giving you rains from heaven and fruitful seasons, satisfying you with food and filling your hearts with gladness.”

[[v44-14-18]]

^<<v44-14-18,18>>^ And yet despite saying these things, they barely restrained the crowds from sacrificing to them.

[[v44-14-19]]

^<<v44-14-19,19>>^ But Jews arrived from Antioch and I·coʹni·um and persuaded the crowds, and they stoned Paul and dragged him outside the city, imagining that he was dead.

[[v44-14-20]]

^<<v44-14-20,20>>^ However, when the disciples surrounded him, he got up and entered the city. On the next day he left with Barʹna·bas for Derʹbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ After declaring the good news to that city and making quite a few disciples, they returned to Lysʹtra, I·coʹni·um, and Antioch.

[[v44-14-22]]

^<<v44-14-22,22>>^ There they strengthened the disciples,^&#42;1^ encouraging them to remain in the faith and saying: “We must enter into the Kingdom of God through many tribulations.”

[NOTE]
====
. Or “the souls of the disciples.”
====

[[v44-14-23]]

^<<v44-14-23,23>>^ Moreover, they appointed elders for them in each congregation, offering prayer with fasting, and they entrusted them to Jehovah,^&#42;1^ in whom they had become believers.

[NOTE]
====
. See App. A5.
====

[[v44-14-24]]

^<<v44-14-24,24>>^ Then they went through Pi·sidʹi·a and came into Pam·phylʹi·a,

[[v44-14-25]]

^<<v44-14-25,25>>^ and after proclaiming the word in Perga, they went down to At·ta·liʹa.

[[v44-14-26]]

^<<v44-14-26,26>>^ From there they sailed off for Antioch, where they had been entrusted to the undeserved kindness of God for the work they had now completed.

[[v44-14-27]]

^<<v44-14-27,27>>^ When they had arrived and had gathered the congregation together, they related the many things God had done by means of them, and that he had opened to the nations the door to faith.

[[v44-14-28]]

^<<v44-14-28,28>>^ So they spent considerable time with the disciples.

'''

xref:044-acts/044-acts-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-acts/044-acts-015.adoc#v44-15-0[Próximo Capítulo &#62;]