include::./index.adoc[]

[[v44-10-0]]
=== Acts of Apostles, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-10-1]]

^<<v44-10-1,1>>^ Now there was a man in Caes·a·reʹa named Cornelius, an army officer^&#42;1^ in what was called the Italian unit.^&#42;2^

[NOTE]
====
. Or “a centurion,” in command of 100 soldiers.
. Or “cohort,” a Roman army unit of 600 soldiers.
====

[[v44-10-2]]

^<<v44-10-2,2>>^ He was a devout man who feared God together with all his household, and he made many gifts of mercy to the people and made supplication to God continually.

[[v44-10-3]]

^<<v44-10-3,3>>^ About the ninth hour of the day,^&#42;1^ he saw plainly in a vision an angel of God come in to him and say: “Cornelius!”

[NOTE]
====
. That is, about 3:00 p.m.
====

[[v44-10-4]]

^<<v44-10-4,4>>^ Cornelius stared at him, terrified, and asked: “What is it, Lord?” He said to him: “Your prayers and gifts of mercy have ascended as a remembrance before God.

[[v44-10-5]]

^<<v44-10-5,5>>^ So now send men to Jopʹpa and summon a man named Simon who is called Peter.

[[v44-10-6]]

^<<v44-10-6,6>>^ This man is staying as a guest with^&#42;1^ Simon, a tanner who has a house by the sea.”

[NOTE]
====
. Or “being entertained by.”
====

[[v44-10-7]]

^<<v44-10-7,7>>^ As soon as the angel who spoke to him left, he called two of his servants and a devout soldier from among those who were his attendants,

[[v44-10-8]]

^<<v44-10-8,8>>^ and he related everything to them and sent them to Jopʹpa.

[[v44-10-9]]

^<<v44-10-9,9>>^ The next day as they were continuing on their journey and were approaching the city, Peter went up to the housetop about the sixth hour^&#42;1^ to pray.

[NOTE]
====
. That is, about 12:00 noon.
====

[[v44-10-10]]

^<<v44-10-10,10>>^ But he became very hungry and wanted to eat. While they were preparing the meal, he fell into a trance

[[v44-10-11]]

^<<v44-10-11,11>>^ and saw heaven opened and something^&#42;1^ descending like a great linen sheet being let down by its four corners on the earth;

[NOTE]
====
. Lit., “some sort of vessel.”
====

[[v44-10-12]]

^<<v44-10-12,12>>^ and in it were all sorts of four-footed animals and reptiles^&#42;1^ of the earth and birds of heaven.

[NOTE]
====
. Or “creeping things.”
====

[[v44-10-13]]

^<<v44-10-13,13>>^ Then a voice said to him: “Get up, Peter, slaughter and eat!”

[[v44-10-14]]

^<<v44-10-14,14>>^ But Peter said: “Not at all, Lord, because I have never eaten anything defiled and unclean.”

[[v44-10-15]]

^<<v44-10-15,15>>^ And the voice spoke again to him, the second time: “Stop calling defiled the things God has cleansed.”

[[v44-10-16]]

^<<v44-10-16,16>>^ This happened a third time, and immediately it^&#42;1^ was taken up into heaven.

[NOTE]
====
. Lit., “the vessel.”
====

[[v44-10-17]]

^<<v44-10-17,17>>^ While Peter was still perplexed about what the vision he had seen could mean, just then the men sent by Cornelius asked where Simon’s house was and stood there at the gate.

[[v44-10-18]]

^<<v44-10-18,18>>^ They called out and inquired whether Simon who was called Peter was a guest there.

[[v44-10-19]]

^<<v44-10-19,19>>^ As Peter was still pondering over the vision, the spirit said: “Look! Three men are asking for you.

[[v44-10-20]]

^<<v44-10-20,20>>^ So get up, go downstairs and go with them, not doubting at all, because I have sent them.”

[[v44-10-21]]

^<<v44-10-21,21>>^ Then Peter went downstairs to the men and said: “Here I am, the one you are looking for. Why are you here?”

[[v44-10-22]]

^<<v44-10-22,22>>^ They said: “Cornelius, an army officer, a righteous and God-fearing man who is well-reported-on by the whole nation of the Jews, was given divine instructions by a holy angel to send for you to come to his house and to hear what you have to say.”

[[v44-10-23]]

^<<v44-10-23,23>>^ So he invited them in and had them stay as his guests.
The next day he got up and went off with them, and some of the brothers from Jopʹpa went with him.

[[v44-10-24]]

^<<v44-10-24,24>>^ The following day he entered into Caes·a·reʹa. Cornelius, of course, was expecting them and had called together his relatives and close friends.

[[v44-10-25]]

^<<v44-10-25,25>>^ As Peter entered, Cornelius met him, fell down at his feet, and did obeisance^&#42;1^ to him.

[NOTE]
====
. Or “bowed down.”
====

[[v44-10-26]]

^<<v44-10-26,26>>^ But Peter lifted him up, saying: “Rise; I too am just a man.”

[[v44-10-27]]

^<<v44-10-27,27>>^ As he conversed with him, he went in and found many people assembled.

[[v44-10-28]]

^<<v44-10-28,28>>^ He said to them: “You well know how unlawful it is for a Jew to associate with or approach a man of another race, and yet God has shown me that I should call no man defiled or unclean.

[[v44-10-29]]

^<<v44-10-29,29>>^ So I came, really without objection, when I was sent for. Therefore, I ask you why you sent for me.”

[[v44-10-30]]

^<<v44-10-30,30>>^ Then Cornelius said: “Four days ago counting from this hour, I was praying in my house at the ninth hour;^&#42;1^ just then a man in bright clothing stood in front of me

[NOTE]
====
. That is, about 3:00 p.m.
====

[[v44-10-31]]

^<<v44-10-31,31>>^ and said: ‘Cornelius, your prayer has been favorably heard, and your gifts of mercy have been remembered before God.

[[v44-10-32]]

^<<v44-10-32,32>>^ Therefore, send to Jopʹpa and call for Simon who is called Peter. This man is a guest in the house of Simon, a tanner, by the sea.’

[[v44-10-33]]

^<<v44-10-33,33>>^ I then sent for you at once, and you were kind enough to come here. So now we are all present before God to hear all the things you have been commanded by Jehovah^&#42;1^ to say.”

[NOTE]
====
. See App. A5.
====

[[v44-10-34]]

^<<v44-10-34,34>>^ At this Peter began to speak, and he said: “Now I truly understand that God is not partial,

[[v44-10-35]]

^<<v44-10-35,35>>^ but in every nation the man who fears him and does what is right is acceptable to him.

[[v44-10-36]]

^<<v44-10-36,36>>^ He sent out the word to the sons of Israel to declare to them the good news of peace through Jesus Christ—this one is Lord of all.

[[v44-10-37]]

^<<v44-10-37,37>>^ You know the subject that was talked about throughout all Ju·deʹa, starting from Galʹi·lee after the baptism that John preached:

[[v44-10-38]]

^<<v44-10-38,38>>^ about Jesus who was from Nazʹa·reth, how God anointed him with holy spirit and power, and he went through the land doing good and healing all those oppressed by the Devil, because God was with him.

[[v44-10-39]]

^<<v44-10-39,39>>^ And we are witnesses of all the things he did both in the country of the Jews and in Jerusalem; but they did away with him by hanging him on a stake.^&#42;1^

[NOTE]
====
. Or “tree.”
====

[[v44-10-40]]

^<<v44-10-40,40>>^ God raised this one up on the third day and allowed him to become manifest,^&#42;1^

[NOTE]
====
. Or “visible.”
====

[[v44-10-41]]

^<<v44-10-41,41>>^ not to all the people, but to witnesses appointed beforehand by God, to us, who ate and drank with him after his rising from the dead.

[[v44-10-42]]

^<<v44-10-42,42>>^ Also, he ordered us to preach to the people and to give a thorough witness that this is the one decreed by God to be judge of the living and the dead.

[[v44-10-43]]

^<<v44-10-43,43>>^ To him all the prophets bear witness, that everyone putting faith in him receives forgiveness of sins through his name.”

[[v44-10-44]]

^<<v44-10-44,44>>^ While Peter was still speaking about these matters, the holy spirit came upon all those hearing the word.

[[v44-10-45]]

^<<v44-10-45,45>>^ And the circumcised believers^&#42;1^ who had come with Peter were amazed, because the free gift of the holy spirit was being poured out also on people of the nations.

[NOTE]
====
. Or “faithful ones.”
====

[[v44-10-46]]

^<<v44-10-46,46>>^ For they heard them speaking in foreign languages^&#42;1^ and magnifying God. Then Peter responded:

[NOTE]
====
. Lit., “in tongues.”
====

[[v44-10-47]]

^<<v44-10-47,47>>^ “Can anyone deny water to prevent these from being baptized who have received the holy spirit just as we have?”

[[v44-10-48]]

^<<v44-10-48,48>>^ With that he commanded them to be baptized in the name of Jesus Christ. Then they requested him to stay for some days.

'''

xref:044-acts/044-acts-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-acts/044-acts-011.adoc#v44-11-0[Próximo Capítulo &#62;]