include::./index.adoc[]

[[v44-5-0]]
=== Acts of Apostles, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-5-1]]

^<<v44-5-1,1>>^ However, a man named An·a·niʹas, together with his wife Sap·phiʹra, sold some property.

[[v44-5-2]]

^<<v44-5-2,2>>^ But he secretly held back some of the price, with his wife’s knowledge, and he brought just a part of it and deposited it at the feet of the apostles.

[[v44-5-3]]

^<<v44-5-3,3>>^ But Peter said: “An·a·niʹas, why has Satan emboldened you to lie to the holy spirit and secretly hold back some of the price of the field?

[[v44-5-4]]

^<<v44-5-4,4>>^ As long as it remained with you, did it not remain yours? And after it was sold, was it not in your control? Why have you thought up such a deed as this in your heart? You have lied, not to men, but to God.”

[[v44-5-5]]

^<<v44-5-5,5>>^ On hearing these words, An·a·niʹas collapsed and died. And great fear came over all those who heard about it.

[[v44-5-6]]

^<<v44-5-6,6>>^ Then the younger men rose, wrapped him in cloths, carried him out, and buried him.

[[v44-5-7]]

^<<v44-5-7,7>>^ Now after an interval of about three hours his wife came in, not knowing what had happened.

[[v44-5-8]]

^<<v44-5-8,8>>^ Peter said to her: “Tell me, did you two sell the field for so much?” She said: “Yes, for that amount.”

[[v44-5-9]]

^<<v44-5-9,9>>^ So Peter said to her: “Why did you two agree to make a test of the spirit of Jehovah?^&#42;1^ Look! The feet of those who buried your husband are at the door, and they will carry you out.”

[NOTE]
====
. See App. A5.
====

[[v44-5-10]]

^<<v44-5-10,10>>^ Instantly she collapsed at his feet and died. When the young men came in, they found her dead and they carried her out and buried her alongside her husband.

[[v44-5-11]]

^<<v44-5-11,11>>^ So great fear came over the whole congregation and over all those hearing about these things.

[[v44-5-12]]

^<<v44-5-12,12>>^ Moreover, through the hands of the apostles many signs and wonders^&#42;1^ continued to occur among the people; and they would all meet together in Solʹo·mon’s Colonnade.

[NOTE]
====
. Or “portents.”
====

[[v44-5-13]]

^<<v44-5-13,13>>^ True, none of the others had the courage to join them; nevertheless, the people were speaking highly of them.

[[v44-5-14]]

^<<v44-5-14,14>>^ More than that, believers in the Lord kept on being added, great numbers both of men and of women.

[[v44-5-15]]

^<<v44-5-15,15>>^ They even brought the sick out into the main streets and laid them there on small beds and mats, so that as Peter would pass by, at least his shadow might fall on some of them.

[[v44-5-16]]

^<<v44-5-16,16>>^ Also, crowds of people from the cities around Jerusalem kept coming, carrying sick people and those troubled with unclean spirits, and they were one and all cured.

[[v44-5-17]]

^<<v44-5-17,17>>^ But the high priest rose, and all those with him, who were of the sect of the Sadducees, and they were filled with jealousy.

[[v44-5-18]]

^<<v44-5-18,18>>^ And they seized^&#42;1^ the apostles and put them in the public jail.

[NOTE]
====
. Or “arrested.”
====

[[v44-5-19]]

^<<v44-5-19,19>>^ But during the night, Jehovah’s^&#42;1^ angel opened the doors of the prison, brought them out, and said:

[NOTE]
====
. See App. A5.
====

[[v44-5-20]]

^<<v44-5-20,20>>^ “Go and take your stand in the temple, and keep on speaking to the people all the sayings about this life.”

[[v44-5-21]]

^<<v44-5-21,21>>^ After hearing this, they entered the temple at daybreak and began to teach.
Now when the high priest and those with him arrived, they called together the Sanʹhe·drin and the entire assembly of elders of the sons of Israel, and they sent out to the jail to have the apostles brought before them.

[[v44-5-22]]

^<<v44-5-22,22>>^ But when the officers got there, they did not find them in the prison. So they returned and made their report,

[[v44-5-23]]

^<<v44-5-23,23>>^ saying: “We found the jail locked and secure, and the guards were standing at the doors, but on opening it up, we found no one inside.”

[[v44-5-24]]

^<<v44-5-24,24>>^ Well, when both the captain of the temple and the chief priests heard these words, they were perplexed about what would come of this.

[[v44-5-25]]

^<<v44-5-25,25>>^ But someone came and reported to them: “Look! The men you put in prison are in the temple, standing and teaching the people.”

[[v44-5-26]]

^<<v44-5-26,26>>^ Then the captain went off with his officers and brought them in, but without violence, because they were afraid of being stoned by the people.

[[v44-5-27]]

^<<v44-5-27,27>>^ So they brought them and stood them before the Sanʹhe·drin. Then the high priest questioned them

[[v44-5-28]]

^<<v44-5-28,28>>^ and said: “We strictly ordered you not to keep teaching on the basis of this name, and yet look! you have filled Jerusalem with your teaching, and you are determined to bring the blood of this man upon us.”

[[v44-5-29]]

^<<v44-5-29,29>>^ In answer Peter and the other apostles said: “We must obey God as ruler rather than men.

[[v44-5-30]]

^<<v44-5-30,30>>^ The God of our forefathers raised up Jesus, whom you killed, hanging him on a stake.^&#42;1^

[NOTE]
====
. Or “tree.”
====

[[v44-5-31]]

^<<v44-5-31,31>>^ God exalted this one as Chief Agent and Savior to his right hand, to give repentance to Israel and forgiveness of sins.

[[v44-5-32]]

^<<v44-5-32,32>>^ And we are witnesses of these matters, and so is the holy spirit, which God has given to those obeying him as ruler.”

[[v44-5-33]]

^<<v44-5-33,33>>^ When they heard this, they were infuriated^&#42;1^ and wanted to do away with them.

[NOTE]
====
. Or “they felt cut.”
====

[[v44-5-34]]

^<<v44-5-34,34>>^ But a Pharisee named Ga·maʹli·el rose in the Sanʹhe·drin; he was a Law teacher esteemed by all the people, and he gave the command to put the men outside for a little while.

[[v44-5-35]]

^<<v44-5-35,35>>^ Then he said to them: “Men of Israel, be careful as to what you intend to do about these men.

[[v44-5-36]]

^<<v44-5-36,36>>^ For instance, before these days Theuʹdas rose up, saying he himself was somebody, and a number of men, about 400, joined his party. But he was done away with, and all those who were following him were dispersed and came to nothing.

[[v44-5-37]]

^<<v44-5-37,37>>^ After him, Judas the Gal·i·leʹan rose up in the days of the registration, and he drew followers after himself. That man also perished, and all those who were following him were scattered.

[[v44-5-38]]

^<<v44-5-38,38>>^ So under the present circumstances, I say to you, do not meddle with these men, but let them alone. For if this scheme or this work is from men, it will be overthrown;

[[v44-5-39]]

^<<v44-5-39,39>>^ but if it is from God, you will not be able to overthrow them. Otherwise, you may even be found fighters against God himself.”

[[v44-5-40]]

^<<v44-5-40,40>>^ At this they took his advice, and they summoned the apostles, flogged^&#42;1^ them, and ordered them to stop speaking on the basis of Jesus’ name, and let them go.

[NOTE]
====
. Or “beat.”
====

[[v44-5-41]]

^<<v44-5-41,41>>^ So they went out from before the Sanʹhe·drin, rejoicing because they had been counted worthy to be dishonored in behalf of his name.

[[v44-5-42]]

^<<v44-5-42,42>>^ And every day in the temple and from house to house they continued without letup teaching and declaring the good news about the Christ, Jesus.

'''

xref:044-acts/044-acts-004.adoc#v44-4-0[&#60; Capítulo Anterior] | <<v44-5-0,Topo>> | xref:044-acts/044-acts-006.adoc#v44-6-0[Próximo Capítulo &#62;]