include::./index.adoc[]

[[v44-11-0]]
=== Acts of Apostles, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-11-1]]

^<<v44-11-1,1>>^ Now the apostles and the brothers who were in Ju·deʹa heard that people of the nations had also accepted the word of God.

[[v44-11-2]]

^<<v44-11-2,2>>^ So when Peter came up to Jerusalem, the supporters of circumcision began to criticize^&#42;1^ him,

[NOTE]
====
. Or “contend with.”
====

[[v44-11-3]]

^<<v44-11-3,3>>^ saying: “You went into the house of men who were not circumcised and ate with them.”

[[v44-11-4]]

^<<v44-11-4,4>>^ At this Peter went on to explain the matter in detail to them, saying:

[[v44-11-5]]

^<<v44-11-5,5>>^ “I was in the city of Jopʹpa praying, and while in a trance I saw a vision, something^&#42;1^ descending like a great linen sheet being let down by its four corners from heaven, and it came right down to me.

[NOTE]
====
. Lit., “some sort of vessel.”
====

[[v44-11-6]]

^<<v44-11-6,6>>^ Looking closely into it, I observed four-footed animals of the earth, wild beasts, reptiles,^&#42;1^ and birds of heaven.

[NOTE]
====
. Or “creeping things.”
====

[[v44-11-7]]

^<<v44-11-7,7>>^ I also heard a voice say to me: ‘Get up, Peter, slaughter and eat!’

[[v44-11-8]]

^<<v44-11-8,8>>^ But I said: ‘Certainly not, Lord, because a defiled or unclean thing has never entered my mouth.’

[[v44-11-9]]

^<<v44-11-9,9>>^ The second time, the voice from heaven answered: ‘You stop calling defiled the things God has cleansed.’

[[v44-11-10]]

^<<v44-11-10,10>>^ This happened a third time, and everything was pulled up again into heaven.

[[v44-11-11]]

^<<v44-11-11,11>>^ Also just at that moment, three men were standing at the house where we were staying, having been sent to me from Caes·a·reʹa.

[[v44-11-12]]

^<<v44-11-12,12>>^ Then the spirit told me to go with them, not doubting at all. But these six brothers also went with me, and we entered into the house of the man.

[[v44-11-13]]

^<<v44-11-13,13>>^ “He reported to us how he saw the angel stand in his house and say: ‘Send men to Jopʹpa and summon Simon who is called Peter,

[[v44-11-14]]

^<<v44-11-14,14>>^ and he will tell you things by which you and all your household may get saved.’

[[v44-11-15]]

^<<v44-11-15,15>>^ But when I started to speak, the holy spirit fell on them just as it did also on us in the beginning.

[[v44-11-16]]

^<<v44-11-16,16>>^ At this I recalled the saying of the Lord, how he used to say: ‘John baptized with water, but you will be baptized with holy spirit.’

[[v44-11-17]]

^<<v44-11-17,17>>^ If, therefore, God gave the same free gift to them that he gave to us who have believed in the Lord Jesus Christ, who was I that I should be able to hinder God?”^&#42;1^

[NOTE]
====
. Or “stand in God’s way?”
====

[[v44-11-18]]

^<<v44-11-18,18>>^ When they heard these things, they stopped objecting,^&#42;1^ and they glorified God, saying: “So, then, God has also granted to people of the nations repentance leading to life.”

[NOTE]
====
. Lit., “they became silent.”
====

[[v44-11-19]]

^<<v44-11-19,19>>^ Now those who had been scattered by the tribulation that arose over Stephen went as far as Phoe·niʹcia, Cyʹprus, and Antioch, but they spoke the word only to the Jews.

[[v44-11-20]]

^<<v44-11-20,20>>^ However, some of the men among them from Cyʹprus and Cy·reʹne came to Antioch and began talking to the Greek-speaking people, declaring the good news of the Lord Jesus.

[[v44-11-21]]

^<<v44-11-21,21>>^ Furthermore, the hand of Jehovah^&#42;1^ was with them, and a great number became believers and turned to the Lord.

[NOTE]
====
. See App. A5.
====

[[v44-11-22]]

^<<v44-11-22,22>>^ The report about them reached the ears of the congregation in Jerusalem, and they sent out Barʹna·bas as far as Antioch.

[[v44-11-23]]

^<<v44-11-23,23>>^ When he arrived and saw the undeserved kindness of God, he rejoiced and began to encourage them all to continue in the Lord with heartfelt resolve;

[[v44-11-24]]

^<<v44-11-24,24>>^ for he was a good man and full of holy spirit and faith. And a considerable crowd was added to the Lord.

[[v44-11-25]]

^<<v44-11-25,25>>^ So he went to Tarsus to make a thorough search for Saul.

[[v44-11-26]]

^<<v44-11-26,26>>^ After he found him, he brought him to Antioch. So for a whole year they assembled with them in the congregation and taught quite a crowd, and it was first in Antioch that the disciples were by divine providence called Christians.

[[v44-11-27]]

^<<v44-11-27,27>>^ In those days prophets came down from Jerusalem to Antioch.

[[v44-11-28]]

^<<v44-11-28,28>>^ One of them named Agʹa·bus stood up and foretold through the spirit that a great famine was about to come on the entire inhabited earth, which, in fact, did take place in the time of Claudius.

[[v44-11-29]]

^<<v44-11-29,29>>^ So the disciples determined, each according to what he could afford, to send relief^&#42;1^ to the brothers living in Ju·deʹa;

[NOTE]
====
. Or “a relief ministration.”
====

[[v44-11-30]]

^<<v44-11-30,30>>^ and this they did, sending it to the elders by the hand of Barʹna·bas and Saul.

'''

xref:044-acts/044-acts-010.adoc#v44-10-0[&#60; Capítulo Anterior] | <<v44-11-0,Topo>> | xref:044-acts/044-acts-012.adoc#v44-12-0[Próximo Capítulo &#62;]