include::./index.adoc[]

[[v44-27-0]]
=== Acts of Apostles, 27
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-27-1]]

^<<v44-27-1,1>>^ Now as it was decided for us to sail away to Italy, they handed Paul and some other prisoners over to an army officer named Julius, of the unit of Au·gusʹtus.

[[v44-27-2]]

^<<v44-27-2,2>>^ Going aboard a ship from Ad·ra·mytʹti·um that was about to sail to ports along the coast of the province of Asia, we set sail; Ar·is·tarʹchus, a Mac·e·doʹni·an from Thes·sa·lo·niʹca, was with us.

[[v44-27-3]]

^<<v44-27-3,3>>^ The next day we landed at Siʹdon, and Julius treated Paul with kindness^&#42;1^ and permitted him to go to his friends and enjoy their care.

[NOTE]
====
. Or “human kindness.”
====

[[v44-27-4]]

^<<v44-27-4,4>>^ And putting out to sea from there, we sailed under the shelter of Cyʹprus, because the winds were against us.

[[v44-27-5]]

^<<v44-27-5,5>>^ Then we navigated through the open sea along Ci·liʹcia and Pam·phylʹi·a and put into port at Myʹra in Lyʹci·a.

[[v44-27-6]]

^<<v44-27-6,6>>^ There the army officer found a ship from Alexandria that was sailing for Italy, and he made us board it.

[[v44-27-7]]

^<<v44-27-7,7>>^ Then after sailing on slowly quite a number of days, we came to Cniʹdus with difficulty. Because the wind did not let us make headway, we sailed under the shelter of Crete off Sal·moʹne.

[[v44-27-8]]

^<<v44-27-8,8>>^ And sailing with difficulty along the coast, we came to a place called Fair Havens, which was near the city of La·seʹa.

[[v44-27-9]]

^<<v44-27-9,9>>^ A considerable time had passed and by now it was hazardous to navigate, because even the fast of Atonement Day was already over, so Paul made a recommendation

[[v44-27-10]]

^<<v44-27-10,10>>^ to them: “Men, I can see that this voyage is going to result in damage and great loss not only of the cargo and the ship but also of our lives.”^&#42;1^

[NOTE]
====
. Or “souls.”
====

[[v44-27-11]]

^<<v44-27-11,11>>^ However, the army officer listened to the pilot and the shipowner rather than to what Paul was saying.

[[v44-27-12]]

^<<v44-27-12,12>>^ Since the harbor was unsuitable for wintering, the majority advised setting sail from there to see if they could somehow make it to spend the winter in Phoenix, a harbor of Crete that opens toward the northeast and toward the southeast.

[[v44-27-13]]

^<<v44-27-13,13>>^ When the south wind blew softly, they thought they had achieved their purpose, and they lifted anchor and began sailing along Crete close to the shore.

[[v44-27-14]]

^<<v44-27-14,14>>^ After a short time, however, a violent wind called Eu·ro·aqʹui·lo^&#42;1^ rushed down on it.

[NOTE]
====
. That is, a northeast wind.
====

[[v44-27-15]]

^<<v44-27-15,15>>^ As the ship was violently seized and was not able to keep its head against the wind, we gave way to it and were driven along.

[[v44-27-16]]

^<<v44-27-16,16>>^ Then we ran under the shelter of a small island called Cauʹda, and yet we were hardly able to get the skiff^&#42;1^ at the stern of the ship under control.

[NOTE]
====
. A small auxiliary boat that could serve as a lifeboat.
====

[[v44-27-17]]

^<<v44-27-17,17>>^ But after hoisting it aboard, they used supports to undergird the ship, and fearing that they would run aground on the Syrʹtis,^&#42;1^ they lowered the gear and so were driven along.

[NOTE]
====
. See Glossary.
====

[[v44-27-18]]

^<<v44-27-18,18>>^ Because we were being violently tossed by the storm, they began to lighten the ship the following day.

[[v44-27-19]]

^<<v44-27-19,19>>^ And on the third day, they threw away the tackling of the ship with their own hands.

[[v44-27-20]]

^<<v44-27-20,20>>^ When neither sun nor stars appeared for many days and a violent^&#42;1^ storm was battering us, all hope of our being saved finally began to fade.

[NOTE]
====
. Lit., “no little.”
====

[[v44-27-21]]

^<<v44-27-21,21>>^ After they had gone a long time without food, Paul stood up in their midst and said: “Men, you certainly should have taken my advice and not have put out to sea from Crete and as a result suffered this damage and loss.

[[v44-27-22]]

^<<v44-27-22,22>>^ Still, I now urge you to take courage, for not one^&#42;1^ of you will be lost, only the ship will.

[NOTE]
====
. Or “a soul.”
====

[[v44-27-23]]

^<<v44-27-23,23>>^ This night an angel of the God to whom I belong and to whom I render sacred service stood by me

[[v44-27-24]]

^<<v44-27-24,24>>^ and said: ‘Have no fear, Paul. You must stand before Caesar, and look! God has granted to you all those sailing with you.’

[[v44-27-25]]

^<<v44-27-25,25>>^ So take courage, men, for I believe God that it will be exactly as I was told.

[[v44-27-26]]

^<<v44-27-26,26>>^ However, we must be cast ashore on some island.”

[[v44-27-27]]

^<<v44-27-27,27>>^ Now when the 14th night fell and we were being tossed about on the Sea of Aʹdri·a, at midnight the sailors began to suspect that they were getting near to some land.

[[v44-27-28]]

^<<v44-27-28,28>>^ They sounded the depth and found it 20 fathoms,^&#42;1^ so they proceeded a short distance and again made a sounding and found it 15 fathoms.^&#42;2^

[NOTE]
====
. About 36 m (120 ft). See App. B14.
. About 27 m (90 ft). See App. B14.
====

[[v44-27-29]]

^<<v44-27-29,29>>^ And fearing that we might run aground on the rocks, they cast out four anchors from the stern and began wishing for it to become day.

[[v44-27-30]]

^<<v44-27-30,30>>^ But when the sailors began trying to escape from the ship and were lowering the skiff into the sea under the pretense of intending to let down anchors from the bow,

[[v44-27-31]]

^<<v44-27-31,31>>^ Paul said to the army officer and the soldiers: “Unless these men remain in the ship, you cannot be saved.”

[[v44-27-32]]

^<<v44-27-32,32>>^ Then the soldiers cut away the ropes of the skiff and let it fall off.

[[v44-27-33]]

^<<v44-27-33,33>>^ Now close to daybreak, Paul encouraged them all to take some food, saying: “Today is the 14th day you have been waiting anxiously, and you have gone without taking any food at all.

[[v44-27-34]]

^<<v44-27-34,34>>^ So I encourage you to eat some food; this is in the interests of your safety, for not a hair of the head of any one of you will perish.”

[[v44-27-35]]

^<<v44-27-35,35>>^ After he said this, he took bread, gave thanks to God before them all, broke it, and started eating.

[[v44-27-36]]

^<<v44-27-36,36>>^ So they all took courage and began taking some food themselves.

[[v44-27-37]]

^<<v44-27-37,37>>^ In all we were 276 persons^&#42;1^ in the ship.

[NOTE]
====
. Or “souls.”
====

[[v44-27-38]]

^<<v44-27-38,38>>^ When they had eaten enough food to be satisfied, they lightened the ship by throwing the wheat overboard into the sea.

[[v44-27-39]]

^<<v44-27-39,39>>^ When daylight came, they could not recognize the land, but they saw a bay with a beach and were determined to beach the ship there if they could.

[[v44-27-40]]

^<<v44-27-40,40>>^ So they cut away the anchors and let them fall into the sea, at the same time loosening the lashings of the rudder oars; and after hoisting the foresail to the wind, they made for the beach.

[[v44-27-41]]

^<<v44-27-41,41>>^ When they struck a shoal washed on each side by the sea, they ran the ship aground and the bow got stuck and stayed immovable, but the stern began to be violently broken to pieces by the waves.

[[v44-27-42]]

^<<v44-27-42,42>>^ At this the soldiers decided to kill the prisoners so that no one might swim away and escape.

[[v44-27-43]]

^<<v44-27-43,43>>^ But the army officer was determined to bring Paul safely through and prevented them from carrying out their plan. He commanded those able to swim to jump into the sea and make it to land first,

[[v44-27-44]]

^<<v44-27-44,44>>^ and the rest were to follow, some on planks and some on pieces of the ship. So all were brought safely to land.

'''

xref:044-acts/044-acts-026.adoc#v44-26-0[&#60; Capítulo Anterior] | <<v44-27-0,Topo>> | xref:044-acts/044-acts-028.adoc#v44-28-0[Próximo Capítulo &#62;]