include::./index.adoc[]

[[v44-15-0]]
=== Acts of Apostles, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-15-1]]

^<<v44-15-1,1>>^ Now some men came down from Ju·deʹa and began to teach the brothers: “Unless you get circumcised according to the custom of Moses, you cannot be saved.”

[[v44-15-2]]

^<<v44-15-2,2>>^ But after quite a bit of dissension and disputing by Paul and Barʹna·bas with them, it was arranged for Paul, Barʹna·bas, and some of the others to go up to the apostles and elders in Jerusalem regarding this issue.^&#42;1^

[NOTE]
====
. Or “dispute.”
====

[[v44-15-3]]

^<<v44-15-3,3>>^ So after being escorted partway by the congregation, these men continued on through both Phoe·niʹcia and Sa·marʹi·a, relating in detail the conversion of people of the nations and bringing great joy to all the brothers.

[[v44-15-4]]

^<<v44-15-4,4>>^ On arriving in Jerusalem, they were kindly received by the congregation and the apostles and the elders, and they related the many things God had done by means of them.

[[v44-15-5]]

^<<v44-15-5,5>>^ But some of those of the sect of the Pharisees who had become believers stood up from their seats and said: “It is necessary to circumcise them and command them to observe the Law of Moses.”

[[v44-15-6]]

^<<v44-15-6,6>>^ So the apostles and the elders gathered together to look into this matter.

[[v44-15-7]]

^<<v44-15-7,7>>^ After much intense discussion^&#42;1^ had taken place, Peter rose and said to them: “Men, brothers, you well know that from early days God made the choice among you that through my mouth people of the nations should hear the word of the good news and believe.

[NOTE]
====
. Or “much disputing.”
====

[[v44-15-8]]

^<<v44-15-8,8>>^ And God, who knows the heart, bore witness by giving them the holy spirit, just as he did to us also.

[[v44-15-9]]

^<<v44-15-9,9>>^ And he made no distinction at all between us and them, but purified their hearts by faith.

[[v44-15-10]]

^<<v44-15-10,10>>^ So why are you now making a test of God by imposing on the neck of the disciples a yoke that neither our forefathers nor we were capable of bearing?

[[v44-15-11]]

^<<v44-15-11,11>>^ On the contrary, we have faith that we are saved through the undeserved kindness of the Lord Jesus in the same way that they are.”

[[v44-15-12]]

^<<v44-15-12,12>>^ At that the entire group became silent, and they began to listen to Barʹna·bas and Paul relate the many signs and wonders^&#42;1^ that God had done through them among the nations.

[NOTE]
====
. Or “portents.”
====

[[v44-15-13]]

^<<v44-15-13,13>>^ After they finished speaking, James replied: “Men, brothers, hear me.

[[v44-15-14]]

^<<v44-15-14,14>>^ Symʹe·on has related thoroughly how God for the first time turned his attention to the nations to take out of them a people for his name.

[[v44-15-15]]

^<<v44-15-15,15>>^ And with this the words of the Prophets agree, just as it is written:

[[v44-15-16]]

^<<v44-15-16,16>>^ ‘After these things I will return and raise up again the tent^&#42;1^ of David that is fallen down; I will rebuild its ruins and restore it,

[NOTE]
====
. Or “booth; house.”
====

[[v44-15-17]]

^<<v44-15-17,17>>^ so that the men who remain may earnestly seek Jehovah,^&#42;1^ together with people of all the nations, people who are called by my name, says Jehovah,^&#42;2^ who is doing these things,

[NOTE]
====
. See App. A5.
. See App. A5.
====

[[v44-15-18]]

^<<v44-15-18,18>>^ known from of old.’

[[v44-15-19]]

^<<v44-15-19,19>>^ Therefore, my decision^&#42;1^ is not to trouble those from the nations who are turning to God,

[NOTE]
====
. Or “opinion.”
====

[[v44-15-20]]

^<<v44-15-20,20>>^ but to write them to abstain from things polluted by idols, from sexual immorality,^&#42;1^ from what is strangled,^&#42;2^ and from blood.

[NOTE]
====
. Greek, por·neiʹa. See Glossary.
. Or “what is killed without draining its blood.”
====

[[v44-15-21]]

^<<v44-15-21,21>>^ For from ancient times Moses has had those who preach him in city after city, because he is read aloud in the synagogues on every sabbath.”

[[v44-15-22]]

^<<v44-15-22,22>>^ Then the apostles and the elders, together with the whole congregation, decided to send chosen men from among them to Antioch, along with Paul and Barʹna·bas; they sent Judas who was called Barʹsab·bas and Silas, who were leading men among the brothers.

[[v44-15-23]]

^<<v44-15-23,23>>^ They wrote this and sent it through them:
“The apostles and the elders, your brothers, to those brothers in Antioch, Syria, and Ci·liʹcia who are from the nations: Greetings!

[[v44-15-24]]

^<<v44-15-24,24>>^ Since we have heard that some went out from among us and caused you trouble with what they have said, trying to subvert you,^&#42;1^ although we did not give them any instructions,

[NOTE]
====
. Or “your souls.”
====

[[v44-15-25]]

^<<v44-15-25,25>>^ we have come to a unanimous decision to choose men to send to you together with our beloved Barʹna·bas and Paul,

[[v44-15-26]]

^<<v44-15-26,26>>^ men who have given up their lives^&#42;1^ for the name of our Lord Jesus Christ.

[NOTE]
====
. Or “souls.”
====

[[v44-15-27]]

^<<v44-15-27,27>>^ We are therefore sending Judas and Silas, so that they also may report the same things by word of mouth.

[[v44-15-28]]

^<<v44-15-28,28>>^ For the holy spirit and we ourselves have favored adding no further burden to you except these necessary things:

[[v44-15-29]]

^<<v44-15-29,29>>^ to keep abstaining from things sacrificed to idols, from blood, from what is strangled,^&#42;1^ and from sexual immorality.^&#42;2^ If you carefully keep yourselves from these things, you will prosper. Good health to you!”^&#42;3^

[NOTE]
====
. Or “what is killed without draining its blood.”
. Greek, por·neiʹa. See Glossary.
. Or “Farewell.”
====

[[v44-15-30]]

^<<v44-15-30,30>>^ So when these men were dismissed, they went down to Antioch, and they gathered the whole group together and handed them the letter.

[[v44-15-31]]

^<<v44-15-31,31>>^ After reading it, they rejoiced over the encouragement.

[[v44-15-32]]

^<<v44-15-32,32>>^ And Judas and Silas, since they were also prophets, encouraged the brothers with many talks and strengthened them.

[[v44-15-33]]

^<<v44-15-33,33>>^ After they had spent some time there, they were sent off in peace by the brothers to those who had sent them.

[[v44-15-34]]

^<<v44-15-34,34>>^ ^&#42;1^ ——

[NOTE]
====
. See App. A3.
====

[[v44-15-35]]

^<<v44-15-35,35>>^ But Paul and Barʹna·bas stayed in Antioch, teaching and declaring, along with many others, the good news of the word of Jehovah.^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v44-15-36]]

^<<v44-15-36,36>>^ After some days, Paul said to Barʹna·bas: “Let us now^&#42;1^ return and visit the brothers in every one of the cities where we proclaimed the word of Jehovah,^&#42;2^ to see how they are.”

[NOTE]
====
. Or possibly, “by all means.”
. See App. A5.
====

[[v44-15-37]]

^<<v44-15-37,37>>^ Barʹna·bas was determined to take along John, who was called Mark.

[[v44-15-38]]

^<<v44-15-38,38>>^ Paul, however, was not in favor of taking him along with them, seeing that he had departed from them in Pam·phylʹi·a and had not gone with them to the work.

[[v44-15-39]]

^<<v44-15-39,39>>^ At this there was a sharp burst of anger, so that they separated from each other; and Barʹna·bas took Mark along and sailed away to Cyʹprus.

[[v44-15-40]]

^<<v44-15-40,40>>^ Paul selected Silas and departed after he had been entrusted by the brothers to the undeserved kindness of Jehovah.^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v44-15-41]]

^<<v44-15-41,41>>^ He went through Syria and Ci·liʹcia, strengthening the congregations.

'''

xref:044-acts/044-acts-014.adoc#v44-14-0[&#60; Capítulo Anterior] | <<v44-15-0,Topo>> | xref:044-acts/044-acts-016.adoc#v44-16-0[Próximo Capítulo &#62;]