include::./index.adoc[]

[[v44-12-0]]
=== Acts of Apostles, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-12-1]]

^<<v44-12-1,1>>^ About that time Herod the king began mistreating some of those of the congregation.

[[v44-12-2]]

^<<v44-12-2,2>>^ He put James the brother of John to death by the sword.

[[v44-12-3]]

^<<v44-12-3,3>>^ When he saw that it was pleasing to the Jews, he also went on to arrest Peter. (This was during the days of the Unleavened Bread.)

[[v44-12-4]]

^<<v44-12-4,4>>^ He seized him and put him in prison, turning him over to four shifts of four soldiers each to guard him, intending to bring him out^&#42;1^ before the people after the Passover.

[NOTE]
====
. Or “bring him out to trial.”
====

[[v44-12-5]]

^<<v44-12-5,5>>^ So Peter was being kept in the prison, but the congregation was intensely praying to God for him.

[[v44-12-6]]

^<<v44-12-6,6>>^ When Herod was about to bring him out, that night Peter was sleeping bound with two chains between two soldiers, and guards in front of the door were keeping watch over the prison.

[[v44-12-7]]

^<<v44-12-7,7>>^ But look! Jehovah’s^&#42;1^ angel was standing there, and a light shone in the prison cell. Hitting Peter on the side, he woke him, saying: “Get up quickly!” And the chains fell off his hands.

[NOTE]
====
. See App. A5.
====

[[v44-12-8]]

^<<v44-12-8,8>>^ The angel said to him: “Get dressed^&#42;1^ and put on your sandals.” He did so. Finally he said to him: “Put your outer garment on, and keep following me.”

[NOTE]
====
. Or “Gird yourself.”
====

[[v44-12-9]]

^<<v44-12-9,9>>^ And he went out and kept following him, but he did not know that what was happening through the angel was real. In fact, he thought he was seeing a vision.

[[v44-12-10]]

^<<v44-12-10,10>>^ Going past the first sentinel guard and the second, they reached the iron gate leading into the city, and this opened to them by itself. After they went out, they made their way down one street, and immediately the angel departed from him.

[[v44-12-11]]

^<<v44-12-11,11>>^ And Peter, realizing what was happening, said: “Now I know for sure that Jehovah^&#42;1^ sent his angel and rescued me from Herod’s hand and from everything that the Jews were expecting to happen.”

[NOTE]
====
. See App. A5.
====

[[v44-12-12]]

^<<v44-12-12,12>>^ After he realized this, he went to the house of Mary the mother of John who was called Mark, where quite a few were gathered together and were praying.

[[v44-12-13]]

^<<v44-12-13,13>>^ When he knocked at the door of the gateway, a servant girl named Rhoda came to answer the call.

[[v44-12-14]]

^<<v44-12-14,14>>^ On recognizing the voice of Peter, she was so overjoyed that she did not open the gate, but ran inside and reported that Peter was standing at the gateway.

[[v44-12-15]]

^<<v44-12-15,15>>^ They said to her: “You are out of your mind.” But she kept insisting that it was so. They began to say: “It is his angel.”

[[v44-12-16]]

^<<v44-12-16,16>>^ But Peter remained there, knocking. When they opened the door, they saw him and were astonished.

[[v44-12-17]]

^<<v44-12-17,17>>^ But he motioned to them with his hand to be silent and told them in detail how Jehovah^&#42;1^ had brought him out of the prison, and he said: “Report these things to James and the brothers.” With that he went out and traveled to another place.

[NOTE]
====
. See App. A5.
====

[[v44-12-18]]

^<<v44-12-18,18>>^ Now when it became day, there was quite a disturbance among the soldiers over what had become of Peter.

[[v44-12-19]]

^<<v44-12-19,19>>^ Herod made a diligent search for him, and not finding him, he interrogated the guards and commanded them to be led off to punishment; and he went down from Ju·deʹa to Caes·a·reʹa and spent some time there.

[[v44-12-20]]

^<<v44-12-20,20>>^ Now he was in an angry^&#42;1^ mood against the people of Tyre and Siʹdon. So they came to him with one purpose, and after persuading Blastus, the man in charge of the king’s household affairs,^&#42;2^ they sued for peace, because their country was supplied with food from the land of the king.

[NOTE]
====
. Or “a fighting.”
. Lit., “the king’s bedchamber.”
====

[[v44-12-21]]

^<<v44-12-21,21>>^ On a set day, Herod clothed himself with royal raiment and sat down on the judgment seat and began giving them a public address.

[[v44-12-22]]

^<<v44-12-22,22>>^ Then the people who were assembled began shouting: “A god’s voice, and not a man’s!”

[[v44-12-23]]

^<<v44-12-23,23>>^ Instantly the angel of Jehovah^&#42;1^ struck him, because he did not give the glory to God, and he was eaten up with worms and died.

[NOTE]
====
. See App. A5.
====

[[v44-12-24]]

^<<v44-12-24,24>>^ But the word of Jehovah^&#42;1^ went on growing and spreading.

[NOTE]
====
. See App. A5.
====

[[v44-12-25]]

^<<v44-12-25,25>>^ As for Barʹna·bas and Saul, after fully carrying out the relief work in Jerusalem, they returned and took along with them John, the one also called Mark.

'''

xref:044-acts/044-acts-011.adoc#v44-11-0[&#60; Capítulo Anterior] | <<v44-12-0,Topo>> | xref:044-acts/044-acts-013.adoc#v44-13-0[Próximo Capítulo &#62;]