include::./index.adoc[]

[[v44-4-0]]
=== Acts of Apostles, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-4-1]]

^<<v44-4-1,1>>^ While the two were speaking to the people, the priests, the captain of the temple, and the Sadducees came up to them.

[[v44-4-2]]

^<<v44-4-2,2>>^ These were annoyed because the apostles were teaching the people and were openly declaring the resurrection of Jesus from the dead.^&#42;1^

[NOTE]
====
. Or “the resurrection from the dead in the case of Jesus.”
====

[[v44-4-3]]

^<<v44-4-3,3>>^ So they seized^&#42;1^ them and took them into custody until the next day, for it was already evening.

[NOTE]
====
. Or “arrested.”
====

[[v44-4-4]]

^<<v44-4-4,4>>^ However, many of those who had listened to the speech believed, and the number of the men became about 5,000.

[[v44-4-5]]

^<<v44-4-5,5>>^ The next day their rulers, elders, and scribes gathered together in Jerusalem,

[[v44-4-6]]

^<<v44-4-6,6>>^ along with Anʹnas the chief priest, Caʹia·phas, John, Alexander, and all who were relatives of the chief priest.

[[v44-4-7]]

^<<v44-4-7,7>>^ They stood Peter and John in their midst and began to question them: “By what power or in whose name did you do this?”

[[v44-4-8]]

^<<v44-4-8,8>>^ Then Peter, filled with holy spirit, said to them:
“Rulers of the people and elders,

[[v44-4-9]]

^<<v44-4-9,9>>^ if we are being examined today about a good deed to a crippled man, and you want to know who made this man well,

[[v44-4-10]]

^<<v44-4-10,10>>^ let it be known to all of you and to all the people of Israel that in the name of Jesus Christ the Naz·a·reneʹ, whom you executed on a stake but whom God raised up from the dead, by means of him this man stands here healthy in front of you.

[[v44-4-11]]

^<<v44-4-11,11>>^ This is ‘the stone that was treated by you builders as of no account that has become the chief cornerstone.’^&#42;1^

[NOTE]
====
. Lit., “the head of the corner.”
====

[[v44-4-12]]

^<<v44-4-12,12>>^ Furthermore, there is no salvation in anyone else, for there is no other name under heaven that has been given among men by which we must get saved.”

[[v44-4-13]]

^<<v44-4-13,13>>^ Now when they saw the outspokenness^&#42;1^ of Peter and John, and perceived that they were uneducated^&#42;2^ and ordinary men, they were astonished. And they began to realize that they had been with Jesus.

[NOTE]
====
. Or “boldness.”
. Or “unlettered,” that is, not educated in the rabbinic schools; not meaning illiterate.
====

[[v44-4-14]]

^<<v44-4-14,14>>^ As they were looking at the man who had been cured standing with them, they had nothing to say in answer to this.

[[v44-4-15]]

^<<v44-4-15,15>>^ So they commanded them to go outside the Sanʹhe·drin hall, and they began consulting with one another,

[[v44-4-16]]

^<<v44-4-16,16>>^ saying: “What should we do with these men? Because, for a fact, a noteworthy sign has occurred through them, one evident to all the inhabitants of Jerusalem, and we cannot deny it.

[[v44-4-17]]

^<<v44-4-17,17>>^ So that this does not spread any further among the people, let us threaten them and tell them not to speak to anyone anymore on the basis of this name.”

[[v44-4-18]]

^<<v44-4-18,18>>^ With that they called them and ordered them not to say anything at all or to teach on the basis of the name of Jesus.

[[v44-4-19]]

^<<v44-4-19,19>>^ But in reply Peter and John said to them: “Whether it is right in the sight of God to listen to you rather than to God, judge for yourselves.

[[v44-4-20]]

^<<v44-4-20,20>>^ But as for us, we cannot stop speaking about the things we have seen and heard.”

[[v44-4-21]]

^<<v44-4-21,21>>^ So after they had threatened them further, they released them, since they did not find any grounds for punishing them and on account of the people, because they were all glorifying God over what had happened.

[[v44-4-22]]

^<<v44-4-22,22>>^ For the man on whom this miracle^&#42;1^ of healing had been done was more than 40 years old.

[NOTE]
====
. Or “sign.”
====

[[v44-4-23]]

^<<v44-4-23,23>>^ After being released, they went to their own people and reported what the chief priests and the elders had said to them.

[[v44-4-24]]

^<<v44-4-24,24>>^ On hearing this, they raised their voices with one accord to God and said:
“Sovereign Lord, you are the One who made the heaven and the earth and the sea and all the things in them,

[[v44-4-25]]

^<<v44-4-25,25>>^ and who said through holy spirit by the mouth of our forefather David, your servant: ‘Why did nations become agitated and peoples meditate on empty things?

[[v44-4-26]]

^<<v44-4-26,26>>^ The kings of the earth took their stand and the rulers gathered together as one against Jehovah^&#42;1^ and against his anointed one.’^&#42;2^

[NOTE]
====
. See App. A5.
. Or “his Christ.”
====

[[v44-4-27]]

^<<v44-4-27,27>>^ For truly both Herod and Pontius Pilate with men of the nations and with peoples of Israel were gathered together in this city against your holy servant Jesus, whom you anointed,

[[v44-4-28]]

^<<v44-4-28,28>>^ to do what your hand and counsel had determined beforehand to occur.

[[v44-4-29]]

^<<v44-4-29,29>>^ And now, Jehovah,^&#42;1^ give attention to their threats, and grant to your slaves to keep speaking your word with all boldness,

[NOTE]
====
. See App. A5.
====

[[v44-4-30]]

^<<v44-4-30,30>>^ while you stretch out your hand for healing and while signs and wonders^&#42;1^ occur through the name of your holy servant Jesus.”

[NOTE]
====
. Or “portents.”
====

[[v44-4-31]]

^<<v44-4-31,31>>^ And when they had made supplication,^&#42;1^ the place where they were gathered together was shaken, and they were one and all filled with the holy spirit and were speaking the word of God with boldness.

[NOTE]
====
. Or “had prayed earnestly.”
====

[[v44-4-32]]

^<<v44-4-32,32>>^ Moreover, the multitude of those who believed were of one heart and soul,^&#42;1^ and not even one of them would say that any of the things he possessed was his own, but they had all things in common.

[NOTE]
====
. See Glossary.
====

[[v44-4-33]]

^<<v44-4-33,33>>^ And with great power the apostles continued giving the witness about the resurrection of the Lord Jesus, and undeserved kindness was upon them all in large measure.

[[v44-4-34]]

^<<v44-4-34,34>>^ In fact, no one was in need among them, for all those who owned fields or houses would sell them and bring the value of what was sold,

[[v44-4-35]]

^<<v44-4-35,35>>^ and they would deposit it at the feet of the apostles. In turn distribution would be made to each one according to his need.

[[v44-4-36]]

^<<v44-4-36,36>>^ So Joseph, who was also called by the apostles Barʹna·bas (which means, when translated, “Son of Comfort”), a Levite, a native of Cyʹprus,

[[v44-4-37]]

^<<v44-4-37,37>>^ owned a piece of land, and he sold it and brought the money and deposited it at the feet of the apostles.

'''

xref:044-acts/044-acts-003.adoc#v44-3-0[&#60; Capítulo Anterior] | <<v44-4-0,Topo>> | xref:044-acts/044-acts-005.adoc#v44-5-0[Próximo Capítulo &#62;]