include::./index.adoc[]

[[v44-23-0]]
=== Acts of Apostles, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-23-1]]

^<<v44-23-1,1>>^ Looking intently at the Sanʹhe·drin, Paul said: “Men, brothers, I have behaved before God with a perfectly clear conscience down to this day.”

[[v44-23-2]]

^<<v44-23-2,2>>^ At this the high priest An·a·niʹas ordered those standing by him to strike him on the mouth.

[[v44-23-3]]

^<<v44-23-3,3>>^ Then Paul said to him: “God is going to strike you, you whitewashed wall. Do you sit to judge me according to the Law and at the same time violate the Law by commanding me to be struck?”

[[v44-23-4]]

^<<v44-23-4,4>>^ Those standing by said: “Are you insulting the high priest of God?”

[[v44-23-5]]

^<<v44-23-5,5>>^ And Paul said: “Brothers, I did not know he was high priest. For it is written, ‘You must not speak injuriously of a ruler of your people.’”

[[v44-23-6]]

^<<v44-23-6,6>>^ Now Paul, knowing that the one part was made up of Sadducees but the other of Pharisees, cried out in the Sanʹhe·drin: “Men, brothers, I am a Pharisee, a son of Pharisees. Over the hope of the resurrection of the dead I am being judged.”

[[v44-23-7]]

^<<v44-23-7,7>>^ Because he said this, a dissension arose between the Pharisees and the Sadducees, and the assembly was split.

[[v44-23-8]]

^<<v44-23-8,8>>^ For the Sadducees say that there is neither resurrection nor angel nor spirit, but the Pharisees accept^&#42;1^ them all.

[NOTE]
====
. Or “publicly declare.”
====

[[v44-23-9]]

^<<v44-23-9,9>>^ So a great uproar broke out, and some of the scribes of the party of the Pharisees rose and began arguing fiercely, saying: “We find nothing wrong in this man, but if a spirit or an angel spoke to him—.”

[[v44-23-10]]

^<<v44-23-10,10>>^ Now when the dissension grew great, the military commander feared that Paul would be torn apart by them, and he commanded the soldiers to go down and snatch him from their midst and bring him into the soldiers’ quarters.

[[v44-23-11]]

^<<v44-23-11,11>>^ But the following night the Lord stood by him and said: “Take courage! For just as you have been giving a thorough witness about me in Jerusalem, so you must also bear witness in Rome.”

[[v44-23-12]]

^<<v44-23-12,12>>^ When it became day, the Jews formed a conspiracy and bound themselves with a curse, saying that they would neither eat nor drink until they had killed Paul.

[[v44-23-13]]

^<<v44-23-13,13>>^ There were more than 40 men who formed this oath-bound conspiracy.

[[v44-23-14]]

^<<v44-23-14,14>>^ These men went to the chief priests and the elders and said: “We have solemnly bound ourselves with a curse^&#42;1^ not to eat anything at all until we have killed Paul.

[NOTE]
====
. Or “an oath.”
====

[[v44-23-15]]

^<<v44-23-15,15>>^ So now you together with the Sanʹhe·drin should inform the military commander that he should bring him down to you as though you want to examine his case more thoroughly. But before he gets near, we will be ready to do away with him.”

[[v44-23-16]]

^<<v44-23-16,16>>^ However, the son of Paul’s sister heard of the ambush they were planning, and he entered the soldiers’ quarters and reported it to Paul.

[[v44-23-17]]

^<<v44-23-17,17>>^ Paul then called one of the army officers to him and said: “Take this young man to the military commander, for he has something to report to him.”

[[v44-23-18]]

^<<v44-23-18,18>>^ So he brought him and led him to the military commander and said: “The prisoner Paul called me and asked me to bring this young man to you because he has something to tell you.”

[[v44-23-19]]

^<<v44-23-19,19>>^ The military commander took him by the hand and withdrew privately and asked him: “What do you have to report to me?”

[[v44-23-20]]

^<<v44-23-20,20>>^ He said: “The Jews have agreed to request you to bring Paul down to the Sanʹhe·drin tomorrow, as though they intend to learn more details about his case.

[[v44-23-21]]

^<<v44-23-21,21>>^ But do not let them persuade you, for more than 40 of their men are waiting to ambush him, and they have bound themselves with a curse^&#42;1^ neither to eat nor to drink until they have killed him; and they are now ready, waiting for the promise from you.”

[NOTE]
====
. Or “an oath.”
====

[[v44-23-22]]

^<<v44-23-22,22>>^ So the military commander let the young man go, after ordering him: “Do not tell anyone that you have informed me of this.”

[[v44-23-23]]

^<<v44-23-23,23>>^ And he summoned two of the army officers and said: “Get 200 soldiers ready to march clear to Caes·a·reʹa, also 70 horsemen and 200 spearmen, at the third hour of the night.^&#42;1^

[NOTE]
====
. That is, about 9:00 p.m.
====

[[v44-23-24]]

^<<v44-23-24,24>>^ Also, provide horses for Paul to ride, to take him safely to Felix the governor.”

[[v44-23-25]]

^<<v44-23-25,25>>^ And he wrote a letter with this content:

[[v44-23-26]]

^<<v44-23-26,26>>^ “Claudius Lysʹi·as to His Excellency, Governor Felix: Greetings!

[[v44-23-27]]

^<<v44-23-27,27>>^ This man was seized by the Jews and was about to be killed by them, but I came quickly with my soldiers and rescued him, because I learned that he is a Roman.

[[v44-23-28]]

^<<v44-23-28,28>>^ And wanting to find out the cause for which they were accusing him, I brought him down into their Sanʹhe·drin.

[[v44-23-29]]

^<<v44-23-29,29>>^ I found him to be accused about questions of their Law, but not charged with a single thing deserving of death or prison bonds.

[[v44-23-30]]

^<<v44-23-30,30>>^ But because a plot against the man has been made known to me, I am at once sending him to you and ordering the accusers to speak against him before you.”

[[v44-23-31]]

^<<v44-23-31,31>>^ So these soldiers took Paul according to their orders and brought him by night to An·tipʹa·tris.

[[v44-23-32]]

^<<v44-23-32,32>>^ The next day they permitted the horsemen to go on with him, but they returned to the soldiers’ quarters.

[[v44-23-33]]

^<<v44-23-33,33>>^ The horsemen entered Caes·a·reʹa and delivered the letter to the governor and also presented Paul to him.

[[v44-23-34]]

^<<v44-23-34,34>>^ So he read it and asked what province he was from and learned that he was from Ci·liʹcia.

[[v44-23-35]]

^<<v44-23-35,35>>^ “I will give you a thorough hearing,” he said, “when your accusers arrive.” And he commanded that he be kept under guard in Herod’s palace.^&#42;1^

[NOTE]
====
. Or “praetorium.”
====

'''

xref:044-acts/044-acts-022.adoc#v44-22-0[&#60; Capítulo Anterior] | <<v44-23-0,Topo>> | xref:044-acts/044-acts-024.adoc#v44-24-0[Próximo Capítulo &#62;]