include::./index.adoc[]

[[v44-28-0]]
=== Acts of Apostles, 28
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-28-1]]

^<<v44-28-1,1>>^ After we made it to safety, we learned that the island was called Malta.

[[v44-28-2]]

^<<v44-28-2,2>>^ And the foreign-speaking people^&#42;1^ showed us extraordinary kindness.^&#42;2^ They kindled a fire and received all of us kindly because of the rain that was falling and because of the cold.

[NOTE]
====
. Or “the local inhabitants.”
. Or “human kindness.”
====

[[v44-28-3]]

^<<v44-28-3,3>>^ But when Paul collected a bundle of sticks and laid it on the fire, a viper came out because of the heat and fastened itself on his hand.

[[v44-28-4]]

^<<v44-28-4,4>>^ When the foreign-speaking people caught sight of the venomous creature hanging from his hand, they began saying to one another: “Surely this man is a murderer, and although he made it to safety from the sea, Justice^&#42;1^ did not permit him to keep on living.”

[NOTE]
====
. Greek Diʹke, possibly referring to the goddess of avenging justice or to the concept of justice in an abstract sense.
====

[[v44-28-5]]

^<<v44-28-5,5>>^ However, he shook the creature off into the fire and suffered no harm.

[[v44-28-6]]

^<<v44-28-6,6>>^ But they were expecting him to swell up or suddenly to drop dead. After they waited for a long time and saw that nothing bad happened to him, they changed their mind and began saying he was a god.

[[v44-28-7]]

^<<v44-28-7,7>>^ Now in the neighborhood of that place were lands belonging to the principal man of the island, whose name was Pubʹli·us, and he welcomed us and entertained us hospitably for three days.

[[v44-28-8]]

^<<v44-28-8,8>>^ It so happened that the father of Pubʹli·us was lying in bed sick with fever and dysentery, and Paul went in to him and prayed, laid his hands on him, and healed him.

[[v44-28-9]]

^<<v44-28-9,9>>^ After this occurred, the rest of the people on the island who were sick also began to come to him and be cured.

[[v44-28-10]]

^<<v44-28-10,10>>^ They also honored us with many gifts, and when we were setting sail, they loaded us up with whatever we needed.

[[v44-28-11]]

^<<v44-28-11,11>>^ Three months later we set sail in a ship with the figurehead “Sons of Zeus.” The ship was from Alexandria and had wintered in the island.

[[v44-28-12]]

^<<v44-28-12,12>>^ Putting into port at Syracuse, we remained there for three days;

[[v44-28-13]]

^<<v44-28-13,13>>^ from there we went along and arrived at Rheʹgi·um. A day later a south wind sprang up and we made it into Pu·teʹo·li on the second day.

[[v44-28-14]]

^<<v44-28-14,14>>^ Here we found brothers and were urged to remain with them for seven days, and so we went toward Rome.

[[v44-28-15]]

^<<v44-28-15,15>>^ From there the brothers, when they heard the news about us, came as far as the Marketplace of Apʹpi·us and Three Taverns to meet us. On catching sight of them, Paul thanked God and took courage.

[[v44-28-16]]

^<<v44-28-16,16>>^ When finally we entered Rome, Paul was permitted to stay by himself with the soldier guarding him.

[[v44-28-17]]

^<<v44-28-17,17>>^ However, three days later he called together the principal men of the Jews. When they had assembled, he said to them: “Men, brothers, although I had done nothing contrary to the people or the customs of our forefathers, I was handed over as a prisoner from Jerusalem into the hands of the Romans.

[[v44-28-18]]

^<<v44-28-18,18>>^ And after making an examination, they wanted to release me, for there were no grounds for putting me to death.

[[v44-28-19]]

^<<v44-28-19,19>>^ But when the Jews objected, I was compelled to appeal to Caesar, but not because I had any accusation to make against my nation.

[[v44-28-20]]

^<<v44-28-20,20>>^ So for this reason I asked to see and speak to you, for it is because of the hope of Israel that I have this chain around me.”

[[v44-28-21]]

^<<v44-28-21,21>>^ They said to him: “We have not received letters about you from Ju·deʹa, nor have any of the brothers who came from there reported or spoken anything bad about you.

[[v44-28-22]]

^<<v44-28-22,22>>^ But we think it proper to hear from you what your thoughts are, for truly as regards this sect, we know that it is spoken against everywhere.”

[[v44-28-23]]

^<<v44-28-23,23>>^ They now arranged for a day to meet with him, and they came in even greater numbers to him in his lodging place. And from morning to evening, he explained the matter to them by bearing thorough witness concerning the Kingdom of God, to persuade them about Jesus from both the Law of Moses and the Prophets.

[[v44-28-24]]

^<<v44-28-24,24>>^ Some began to believe the things he said; others would not believe.

[[v44-28-25]]

^<<v44-28-25,25>>^ So because they disagreed with one another, they began to leave, and Paul made this one comment:
“The holy spirit aptly spoke through Isaiah the prophet to your forefathers,

[[v44-28-26]]

^<<v44-28-26,26>>^ saying, ‘Go to this people and say: “You will indeed hear but by no means understand, and you will indeed look but by no means see.

[[v44-28-27]]

^<<v44-28-27,27>>^ For the heart of this people has grown unreceptive, and with their ears they have heard without response, and they have shut their eyes, so that they might never see with their eyes and hear with their ears and understand with their heart and turn back and I heal them.”’

[[v44-28-28]]

^<<v44-28-28,28>>^ So let it be known to you that this salvation from God has been sent out to the nations; they will certainly listen to it.”

[[v44-28-29]]

^<<v44-28-29,29>>^ ^&#42;1^ ——

[NOTE]
====
. See App. A3.
====

[[v44-28-30]]

^<<v44-28-30,30>>^ So he remained there for an entire two years in his own rented house, and he would kindly receive all those who came to him,

[[v44-28-31]]

^<<v44-28-31,31>>^ preaching the Kingdom of God to them and teaching about the Lord Jesus Christ with the greatest freeness of speech,^&#42;1^ without hindrance.

[NOTE]
====
. Or “with all boldness.”
====

'''

xref:044-acts/044-acts-027.adoc#v44-27-0[&#60; Capítulo Anterior] | <<v44-28-0,Topo>> | xref:045-romans/045-romans-001.adoc#v45-1-0[Próximo Capítulo &#62;]