include::./index.adoc[]

[[v44-16-0]]
=== Acts of Apostles, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-16-1]]

^<<v44-16-1,1>>^ So he arrived at Derʹbe and also at Lysʹtra. And a disciple named Timothy was there, the son of a believing Jewish woman but of a Greek father,

[[v44-16-2]]

^<<v44-16-2,2>>^ and he was well-reported-on by the brothers in Lysʹtra and I·coʹni·um.

[[v44-16-3]]

^<<v44-16-3,3>>^ Paul expressed the desire for Timothy to accompany him, and he took him and circumcised him because of the Jews in those places, for they all knew that his father was a Greek.

[[v44-16-4]]

^<<v44-16-4,4>>^ As they traveled on through the cities, they would deliver to them for observance the decrees that had been decided on by the apostles and the elders who were in Jerusalem.

[[v44-16-5]]

^<<v44-16-5,5>>^ Then, indeed, the congregations continued to be made firm in the faith and to increase in number day by day.

[[v44-16-6]]

^<<v44-16-6,6>>^ Moreover, they traveled through Phrygʹi·a and the country of Ga·laʹti·a, because they were forbidden by the holy spirit to speak the word in the province of Asia.

[[v44-16-7]]

^<<v44-16-7,7>>^ Further, when they came down to Mysʹi·a, they made efforts to go into Bi·thynʹi·a, but the spirit of Jesus did not permit them.

[[v44-16-8]]

^<<v44-16-8,8>>^ So they passed by^&#42;1^ Mysʹi·a and came down to Troʹas.

[NOTE]
====
. Or “passed through.”
====

[[v44-16-9]]

^<<v44-16-9,9>>^ And during the night a vision appeared to Paul—a Mac·e·doʹni·an man was standing there urging him and saying: “Step over into Mac·e·doʹni·a and help us.”

[[v44-16-10]]

^<<v44-16-10,10>>^ As soon as he had seen the vision, we tried to go into Mac·e·doʹni·a, drawing the conclusion that God had summoned us to declare the good news to them.

[[v44-16-11]]

^<<v44-16-11,11>>^ So we put out to sea from Troʹas and made a straight run to Samʹo·thrace, but on the following day to Ne·apʹo·lis;

[[v44-16-12]]

^<<v44-16-12,12>>^ and from there we went to Phi·lipʹpi, a colony, which is the principal city of the district of Mac·e·doʹni·a. We stayed in this city for some days.

[[v44-16-13]]

^<<v44-16-13,13>>^ On the Sabbath day we went outside the gate beside a river, where we thought there was a place of prayer, and we sat down and began speaking to the women who had assembled.

[[v44-16-14]]

^<<v44-16-14,14>>^ And a woman named Lydʹi·a, a seller of purple from the city of Thy·a·tiʹra and a worshipper of God, was listening, and Jehovah^&#42;1^ opened her heart wide to pay attention to the things Paul was saying.

[NOTE]
====
. See App. A5.
====

[[v44-16-15]]

^<<v44-16-15,15>>^ Now when she and her household got baptized, she urged us: “If you have considered me to be faithful to Jehovah,^&#42;1^ come and stay at my house.” And she just made us come.

[NOTE]
====
. See App. A5.
====

[[v44-16-16]]

^<<v44-16-16,16>>^ Now it happened that as we were going to the place of prayer, a servant girl with a spirit, a demon of divination, met us. She supplied her masters with much profit by fortune-telling.^&#42;1^

[NOTE]
====
. Or “practicing the art of prediction.”
====

[[v44-16-17]]

^<<v44-16-17,17>>^ This girl kept following Paul and us and crying out with the words: “These men are slaves of the Most High God and are proclaiming to you the way of salvation.”

[[v44-16-18]]

^<<v44-16-18,18>>^ She kept doing this for many days. Finally Paul got tired of it and turned and said to the spirit: “I order you in the name of Jesus Christ to come out of her.” And it came out that very hour.

[[v44-16-19]]

^<<v44-16-19,19>>^ Well, when her masters saw that their hope of profit was gone, they seized Paul and Silas and dragged them into the marketplace to the rulers.

[[v44-16-20]]

^<<v44-16-20,20>>^ Leading them up to the civil magistrates, they said: “These men are disturbing our city very much. They are Jews,

[[v44-16-21]]

^<<v44-16-21,21>>^ and they are proclaiming customs that it is not lawful for us to adopt or practice, seeing that we are Romans.”

[[v44-16-22]]

^<<v44-16-22,22>>^ And the crowd rose up together against them, and the civil magistrates, after tearing the garments off them, gave the command to beat them with rods.

[[v44-16-23]]

^<<v44-16-23,23>>^ After they had inflicted many blows on them, they threw them into prison and ordered the jailer to guard them securely.

[[v44-16-24]]

^<<v44-16-24,24>>^ Because he got such an order, he threw them into the inner prison and fastened their feet in the stocks.

[[v44-16-25]]

^<<v44-16-25,25>>^ But about the middle of the night, Paul and Silas were praying and praising God with song, and the prisoners were listening to them.

[[v44-16-26]]

^<<v44-16-26,26>>^ Suddenly a great earthquake occurred, so that the foundations of the jail were shaken. Moreover, all the doors were instantly opened, and everyone’s bonds came loose.

[[v44-16-27]]

^<<v44-16-27,27>>^ When the jailer woke up and saw that the prison doors were open, he drew his sword and was about to kill himself, assuming that the prisoners had escaped.

[[v44-16-28]]

^<<v44-16-28,28>>^ But Paul called out with a loud voice: “Do not hurt yourself, for we are all here!”

[[v44-16-29]]

^<<v44-16-29,29>>^ So he asked for lights and rushed in, and seized with trembling, he fell down before Paul and Silas.

[[v44-16-30]]

^<<v44-16-30,30>>^ He brought them outside and said: “Sirs, what must I do to get saved?”

[[v44-16-31]]

^<<v44-16-31,31>>^ They said: “Believe in the Lord Jesus, and you will get saved, you and your household.”

[[v44-16-32]]

^<<v44-16-32,32>>^ Then they spoke the word of Jehovah^&#42;1^ to him together with all those in his house.

[NOTE]
====
. See App. A5.
====

[[v44-16-33]]

^<<v44-16-33,33>>^ And he took them along in that hour of the night and washed their wounds. Then he and his entire household were baptized without delay.

[[v44-16-34]]

^<<v44-16-34,34>>^ He brought them into his house and set a table before them, and he rejoiced greatly with all his household now that he had believed in God.

[[v44-16-35]]

^<<v44-16-35,35>>^ When it became day, the civil magistrates sent the constables to say: “Release those men.”

[[v44-16-36]]

^<<v44-16-36,36>>^ The jailer reported their words to Paul: “The civil magistrates have sent men to have you two released. So come out now and go in peace.”

[[v44-16-37]]

^<<v44-16-37,37>>^ But Paul said to them: “They flogged us publicly, uncondemned,^&#42;1^ though we are Romans, and threw us into prison. Are they now throwing us out secretly? No, indeed! Let them come themselves and escort us out.”

[NOTE]
====
. Or “without a trial.”
====

[[v44-16-38]]

^<<v44-16-38,38>>^ The constables reported these words to the civil magistrates. These grew fearful when they heard that the men were Romans.

[[v44-16-39]]

^<<v44-16-39,39>>^ So they came and pleaded with them, and after escorting them out, they requested them to depart from the city.

[[v44-16-40]]

^<<v44-16-40,40>>^ But they came out of the prison and went to the home of Lydʹi·a; and when they saw the brothers, they encouraged them and departed.

'''

xref:044-acts/044-acts-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-acts/044-acts-017.adoc#v44-17-0[Próximo Capítulo &#62;]