include::./index.adoc[]

[[v44-6-0]]
=== Acts of Apostles, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-6-1]]

^<<v44-6-1,1>>^ Now in those days when the disciples were increasing, the Greek-speaking Jews began complaining against the Hebrew-speaking Jews, because their widows were being overlooked in the daily distribution.

[[v44-6-2]]

^<<v44-6-2,2>>^ So the Twelve called the multitude of the disciples together and said: “It is not right^&#42;1^ for us to leave the word of God to distribute food to tables.

[NOTE]
====
. Lit., “pleasing.”
====

[[v44-6-3]]

^<<v44-6-3,3>>^ So, brothers, select for yourselves seven reputable men^&#42;1^ from among you, full of spirit and wisdom, that we may appoint them over this necessary matter;

[NOTE]
====
. Or “seven men who are well-reported-on.”
====

[[v44-6-4]]

^<<v44-6-4,4>>^ but we will devote ourselves to prayer and to the ministry of the word.”

[[v44-6-5]]

^<<v44-6-5,5>>^ What they said was pleasing to the whole multitude, and they selected Stephen, a man full of faith and holy spirit, as well as Philip, Prochʹo·rus, Ni·caʹnor, Tiʹmon, Parʹme·nas, and Nic·o·laʹus, a proselyte of Antioch.

[[v44-6-6]]

^<<v44-6-6,6>>^ They brought them to the apostles, and after praying, they laid their hands on them.

[[v44-6-7]]

^<<v44-6-7,7>>^ Consequently, the word of God continued to spread, and the number of the disciples kept multiplying very much in Jerusalem; and a large crowd of priests began to be obedient to the faith.

[[v44-6-8]]

^<<v44-6-8,8>>^ Now Stephen, full of divine favor and power, was performing great wonders^&#42;1^ and signs among the people.

[NOTE]
====
. Or “portents.”
====

[[v44-6-9]]

^<<v44-6-9,9>>^ But some men of the so-called Synagogue of the Freedmen came forward, along with some Cy·reʹni·ans and Alexandrians, and some from Ci·liʹcia and Asia, to dispute with Stephen.

[[v44-6-10]]

^<<v44-6-10,10>>^ But they could not hold their own against the wisdom and the spirit with which he was speaking.

[[v44-6-11]]

^<<v44-6-11,11>>^ Then they secretly persuaded men to say: “We have heard him speaking blasphemous things against Moses and God.”

[[v44-6-12]]

^<<v44-6-12,12>>^ And they stirred up the people, the elders, and the scribes, and coming upon him suddenly, they forcibly seized him and led him to the Sanʹhe·drin.

[[v44-6-13]]

^<<v44-6-13,13>>^ And they brought forward false witnesses, who said: “This man does not stop speaking things against this holy place and against the Law.

[[v44-6-14]]

^<<v44-6-14,14>>^ For instance, we have heard him say that this Jesus the Naz·a·reneʹ will throw down this place and change the customs that Moses handed down to us.”

[[v44-6-15]]

^<<v44-6-15,15>>^ And as all those sitting in the Sanʹhe·drin stared at him, they saw that his face was like an angel’s face.

'''

xref:044-acts/044-acts-005.adoc#v44-5-0[&#60; Capítulo Anterior] | <<v44-6-0,Topo>> | xref:044-acts/044-acts-007.adoc#v44-7-0[Próximo Capítulo &#62;]