include::./index.adoc[]

[[v44-24-0]]
=== Acts of Apostles, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-24-1]]

^<<v44-24-1,1>>^ Five days later the high priest An·a·niʹas came down with some elders and a public speaker^&#42;1^ named Ter·tulʹlus, and they presented their case against Paul to the governor.

[NOTE]
====
. Or “a lawyer.”
====

[[v44-24-2]]

^<<v44-24-2,2>>^ When he was called, Ter·tulʹlus started accusing him, saying:
“Seeing that we enjoy great peace through you and that through your forethought reforms are taking place in this nation,

[[v44-24-3]]

^<<v44-24-3,3>>^ at all times and also in all places we acknowledge this, Your Excellency Felix, with the greatest thankfulness.

[[v44-24-4]]

^<<v44-24-4,4>>^ But that I may not detain you any further, I beg you to hear us briefly in your kindness.

[[v44-24-5]]

^<<v44-24-5,5>>^ For we have found this man to be a pest,^&#42;1^ stirring up seditions among all the Jews throughout the inhabited earth, and he is a spearhead of the sect of the Naz·a·renesʹ.

[NOTE]
====
. Or “troublemaker.” Lit., “pestilence.”
====

[[v44-24-6]]

^<<v44-24-6,6>>^ He also tried to profane the temple, so we seized him.

[[v44-24-7]]

^<<v44-24-7,7>>^ ^&#42;1^ ——

[NOTE]
====
. See App. A3.
====

[[v44-24-8]]

^<<v44-24-8,8>>^ When you examine him yourself, you will find out about all these things of which we are accusing him.”

[[v44-24-9]]

^<<v44-24-9,9>>^ With that the Jews also joined in the attack, asserting that these things were true.

[[v44-24-10]]

^<<v44-24-10,10>>^ When the governor nodded to Paul to speak, he answered:
“Knowing well that this nation has had you as judge for many years, I readily speak in my own defense.

[[v44-24-11]]

^<<v44-24-11,11>>^ As you can verify for yourself, it has not been more than 12 days since I went up to worship in Jerusalem;

[[v44-24-12]]

^<<v44-24-12,12>>^ and they found me neither arguing with anyone in the temple nor stirring up a mob, either in the synagogues or throughout the city.

[[v44-24-13]]

^<<v44-24-13,13>>^ Nor can they prove to you the things they are accusing me of right now.

[[v44-24-14]]

^<<v44-24-14,14>>^ But I do admit this to you, that according to the way that they call a sect, in this manner I am rendering sacred service to the God of my forefathers, as I believe all the things set forth in the Law and written in the Prophets.

[[v44-24-15]]

^<<v44-24-15,15>>^ And I have hope toward God, which hope these men also look forward to, that there is going to be a resurrection of both the righteous and the unrighteous.

[[v44-24-16]]

^<<v44-24-16,16>>^ Because of this I always strive to maintain a clear^&#42;1^ conscience before God and men.

[NOTE]
====
. Or “blameless.”
====

[[v44-24-17]]

^<<v44-24-17,17>>^ Now after quite a number of years, I arrived to bring gifts of mercy to my nation and to make offerings.

[[v44-24-18]]

^<<v44-24-18,18>>^ While I was caring for these matters, they found me ceremonially cleansed in the temple, but not with a crowd or causing a disturbance. But there were some Jews from the province of Asia

[[v44-24-19]]

^<<v44-24-19,19>>^ who ought to be present before you to accuse me if they actually have anything against me.

[[v44-24-20]]

^<<v44-24-20,20>>^ Or let the men here say for themselves what wrong they found as I stood before the Sanʹhe·drin,

[[v44-24-21]]

^<<v44-24-21,21>>^ except for this one thing that I cried out while standing among them: ‘Over the resurrection of the dead I am today being judged before you!’”

[[v44-24-22]]

^<<v44-24-22,22>>^ However, Felix, knowing quite well the facts concerning this Way, began to put them off and say: “Whenever Lysʹi·as the military commander comes down, I will decide these matters involving you.”

[[v44-24-23]]

^<<v44-24-23,23>>^ And he gave orders to the army officer that the man be kept under arrest but given some freedom, and that his people be allowed to attend to his needs.

[[v44-24-24]]

^<<v44-24-24,24>>^ Some days later Felix came with Dru·silʹla his wife, who was Jewish, and he sent for Paul and listened to him speak about the belief in Christ Jesus.

[[v44-24-25]]

^<<v44-24-25,25>>^ But as Paul talked about righteousness and self-control and the judgment to come, Felix became frightened and answered: “Go away for now, but when I have an opportunity I will send for you again.”

[[v44-24-26]]

^<<v44-24-26,26>>^ At the same time he was hoping that Paul would give him money. For that reason, he sent for him even more frequently and conversed with him.

[[v44-24-27]]

^<<v44-24-27,27>>^ But when two years had elapsed, Felix was succeeded by Porcius Festus; and because Felix desired to gain favor with the Jews, he left Paul in custody.

'''

xref:044-acts/044-acts-023.adoc#v44-23-0[&#60; Capítulo Anterior] | <<v44-24-0,Topo>> | xref:044-acts/044-acts-025.adoc#v44-25-0[Próximo Capítulo &#62;]