include::./index.adoc[]

[[v44-21-0]]
=== Acts of Apostles, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-21-1]]

^<<v44-21-1,1>>^ After tearing ourselves away from them and putting out to sea, we ran with a straight course and came to Cos, on the next day to Rhodes, and from there to Patʹa·ra.

[[v44-21-2]]

^<<v44-21-2,2>>^ When we found a ship that was crossing to Phoe·niʹcia, we went aboard and sailed away.

[[v44-21-3]]

^<<v44-21-3,3>>^ After coming in sight of the island of Cyʹprus, we left it behind on the left side^&#42;1^ and sailed on to Syria and landed at Tyre, where the ship was to unload its cargo.

[NOTE]
====
. Or “port side.”
====

[[v44-21-4]]

^<<v44-21-4,4>>^ We searched for and found the disciples and remained there for seven days. But through the spirit they repeatedly told Paul not to set foot in Jerusalem.

[[v44-21-5]]

^<<v44-21-5,5>>^ So when our time there was over, we left and started on our way, but they all, together with the women and children, accompanied us until we were outside the city. And kneeling down on the beach, we prayed

[[v44-21-6]]

^<<v44-21-6,6>>^ and said good-bye to one another. Then we went aboard the ship, and they returned to their homes.

[[v44-21-7]]

^<<v44-21-7,7>>^ We then completed the voyage from Tyre and arrived at Ptol·e·maʹis, and we greeted the brothers and stayed one day with them.

[[v44-21-8]]

^<<v44-21-8,8>>^ The next day we left and came to Caes·a·reʹa, and we entered the house of Philip the evangelizer, who was one of the seven men, and we stayed with him.

[[v44-21-9]]

^<<v44-21-9,9>>^ This man had four unmarried^&#42;1^ daughters who prophesied.

[NOTE]
====
. Lit., “virgin.”
====

[[v44-21-10]]

^<<v44-21-10,10>>^ But after we had stayed there for quite a number of days, a prophet named Agʹa·bus came down from Ju·deʹa.

[[v44-21-11]]

^<<v44-21-11,11>>^ And he came to us and took Paul’s belt and tied his own feet and hands and said: “Thus says the holy spirit, ‘The man to whom this belt belongs will be bound like this by the Jews in Jerusalem, and they will give him into the hands of people of the nations.’”

[[v44-21-12]]

^<<v44-21-12,12>>^ Now when we heard this, both we and those who were there began begging him not to go up to Jerusalem.

[[v44-21-13]]

^<<v44-21-13,13>>^ Then Paul answered: “What are you doing by weeping and trying to weaken my resolve?^&#42;1^ Rest assured, I am ready not only to be bound but also to die at Jerusalem for the name of the Lord Jesus.”

[NOTE]
====
. Or “making me weak at heart?”
====

[[v44-21-14]]

^<<v44-21-14,14>>^ When he would not be dissuaded, we stopped objecting^&#42;1^ and said: “Let the will of Jehovah^&#42;2^ take place.”

[NOTE]
====
. Lit., “we became silent.”
. See App. A5.
====

[[v44-21-15]]

^<<v44-21-15,15>>^ Now after these days we prepared for the journey and started on our way to Jerusalem.

[[v44-21-16]]

^<<v44-21-16,16>>^ Some of the disciples from Caes·a·reʹa also went with us, taking us to Mnaʹson of Cyʹprus, an early disciple at whose home we were to be guests.

[[v44-21-17]]

^<<v44-21-17,17>>^ When we got to Jerusalem, the brothers welcomed us gladly.

[[v44-21-18]]

^<<v44-21-18,18>>^ But on the following day Paul went in with us to James, and all the elders were present.

[[v44-21-19]]

^<<v44-21-19,19>>^ And he greeted them and began giving a detailed account of the things God did among the nations through his ministry.

[[v44-21-20]]

^<<v44-21-20,20>>^ After hearing this, they began to glorify God, but they said to him: “You see, brother, how many thousands of believers there are among the Jews, and they are all zealous for the Law.

[[v44-21-21]]

^<<v44-21-21,21>>^ But they have heard it rumored about you that you have been teaching all the Jews among the nations an apostasy from Moses, telling them not to circumcise their children or to follow the customary practices.

[[v44-21-22]]

^<<v44-21-22,22>>^ What, then, is to be done about it? They are certainly going to hear that you have arrived.

[[v44-21-23]]

^<<v44-21-23,23>>^ So do what we tell you: We have four men who have put themselves under a vow.

[[v44-21-24]]

^<<v44-21-24,24>>^ Take these men with you and cleanse yourself ceremonially together with them and take care of their expenses, so that they may have their heads shaved. Then everyone will know that there is nothing to the rumors they were told about you, but that you are walking orderly and you are also keeping the Law.

[[v44-21-25]]

^<<v44-21-25,25>>^ As for the believers from among the nations, we have sent them our decision in writing that they should keep away from what is sacrificed to idols as well as from blood, from what is strangled,^&#42;1^ and from sexual immorality.”^&#42;2^

[NOTE]
====
. Or “what is killed without draining its blood.”
. Greek, por·neiʹa. See Glossary.
====

[[v44-21-26]]

^<<v44-21-26,26>>^ Then Paul took the men the next day and cleansed himself ceremonially along with them, and he went into the temple to give notice of when the days for the ceremonial cleansing would be completed and the offering should be presented for each one of them.

[[v44-21-27]]

^<<v44-21-27,27>>^ Now when the seven days were about to end, the Jews from Asia, on seeing him in the temple, stirred up the whole crowd, and they seized him,

[[v44-21-28]]

^<<v44-21-28,28>>^ shouting: “Men of Israel, help! This is the man who teaches everyone everywhere against our people and our Law and this place. And what is more, he even brought Greeks into the temple and has defiled this holy place.”

[[v44-21-29]]

^<<v44-21-29,29>>^ For they had previously seen Trophʹi·mus the E·pheʹsian in the city with him, and they assumed that Paul had brought him into the temple.

[[v44-21-30]]

^<<v44-21-30,30>>^ The whole city was in an uproar, and the people came running together and seized Paul and dragged him outside the temple, and immediately the doors were closed.

[[v44-21-31]]

^<<v44-21-31,31>>^ While they were trying to kill him, word reached the commander of the army unit that all Jerusalem was in confusion;

[[v44-21-32]]

^<<v44-21-32,32>>^ and he immediately took soldiers and army officers and ran down to them. When they caught sight of the military commander and the soldiers, they stopped beating Paul.

[[v44-21-33]]

^<<v44-21-33,33>>^ Then the military commander came near and took him into custody and ordered that he be bound with two chains; then he inquired who he was and what he had done.

[[v44-21-34]]

^<<v44-21-34,34>>^ But some in the crowd began shouting out one thing, and others something else. So being unable himself to learn anything for certain because of the disturbance, he commanded him to be brought to the soldiers’ quarters.

[[v44-21-35]]

^<<v44-21-35,35>>^ But when he reached the stairs, he had to be carried by the soldiers because of the violence of the crowd,

[[v44-21-36]]

^<<v44-21-36,36>>^ for a crowd of the people kept following, crying out: “Do away with him!”

[[v44-21-37]]

^<<v44-21-37,37>>^ As he was about to be led into the soldiers’ quarters, Paul said to the military commander: “Am I allowed to say something to you?” He said: “Can you speak Greek?

[[v44-21-38]]

^<<v44-21-38,38>>^ Are you not, then, the Egyptian who some time ago stirred up a sedition and led the 4,000 dagger men out into the wilderness?”

[[v44-21-39]]

^<<v44-21-39,39>>^ Then Paul said: “I am, in fact, a Jew, of Tarsus in Ci·liʹcia, a citizen of no obscure city. So I beg you, permit me to speak to the people.”

[[v44-21-40]]

^<<v44-21-40,40>>^ After he gave permission, Paul, standing on the stairs, motioned with his hand to the people. When a great silence fell, he addressed them in the Hebrew language, saying:

'''

xref:044-acts/044-acts-020.adoc#v44-20-0[&#60; Capítulo Anterior] | <<v44-21-0,Topo>> | xref:044-acts/044-acts-022.adoc#v44-22-0[Próximo Capítulo &#62;]