include::./index.adoc[]

[[v44-9-0]]
=== Acts of Apostles, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-9-1]]

^<<v44-9-1,1>>^ But Saul, still breathing threat and murder against the disciples of the Lord, went to the high priest

[[v44-9-2]]

^<<v44-9-2,2>>^ and asked him for letters to the synagogues in Damascus, so that he might bring bound to Jerusalem any whom he found who belonged to The Way, both men and women.

[[v44-9-3]]

^<<v44-9-3,3>>^ Now as he was traveling and getting near Damascus, suddenly a light from heaven flashed around him,

[[v44-9-4]]

^<<v44-9-4,4>>^ and he fell to the ground and heard a voice say to him: “Saul, Saul, why are you persecuting me?”

[[v44-9-5]]

^<<v44-9-5,5>>^ He asked: “Who are you, Lord?” He said: “I am Jesus, whom you are persecuting.

[[v44-9-6]]

^<<v44-9-6,6>>^ But get up and go into the city, and you will be told what you must do.”

[[v44-9-7]]

^<<v44-9-7,7>>^ Now the men who were traveling with him stood speechless, hearing, indeed, the sound of a voice but seeing no one.

[[v44-9-8]]

^<<v44-9-8,8>>^ Saul then got up from the ground, and though his eyes were open, he could see nothing. So they led him by the hand and brought him into Damascus.

[[v44-9-9]]

^<<v44-9-9,9>>^ And for three days he did not see anything, and he neither ate nor drank.

[[v44-9-10]]

^<<v44-9-10,10>>^ There was a disciple named An·a·niʹas in Damascus, and the Lord said to him in a vision: “An·a·niʹas!” He said: “Here I am, Lord.”

[[v44-9-11]]

^<<v44-9-11,11>>^ The Lord said to him: “Get up, go to the street called Straight, and look for a man named Saul, from Tarsus, at the house of Judas. For look! he is praying,

[[v44-9-12]]

^<<v44-9-12,12>>^ and in a vision he has seen a man named An·a·niʹas come in and lay his hands on him so that he may recover sight.”

[[v44-9-13]]

^<<v44-9-13,13>>^ But An·a·niʹas answered: “Lord, I have heard from many about this man, about all the harm he did to your holy ones in Jerusalem.

[[v44-9-14]]

^<<v44-9-14,14>>^ And here he has authority from the chief priests to arrest^&#42;1^ all those calling on your name.”

[NOTE]
====
. Lit., “bind; put in bonds.”
====

[[v44-9-15]]

^<<v44-9-15,15>>^ But the Lord said to him: “Go! because this man is a chosen vessel to me to bear my name to the nations as well as to kings and the sons of Israel.

[[v44-9-16]]

^<<v44-9-16,16>>^ For I will show him plainly how many things he must suffer for my name.”

[[v44-9-17]]

^<<v44-9-17,17>>^ So An·a·niʹas went and entered the house, and he laid his hands on him and said: “Saul, brother, the Lord Jesus, who appeared to you on the road along which you were coming, has sent me so that you may recover sight and be filled with holy spirit.”

[[v44-9-18]]

^<<v44-9-18,18>>^ And immediately, what looked like scales fell from his eyes, and he recovered his sight. He then got up and was baptized,

[[v44-9-19]]

^<<v44-9-19,19>>^ and he ate some food and gained strength.
He stayed for some days with the disciples in Damascus,

[[v44-9-20]]

^<<v44-9-20,20>>^ and immediately in the synagogues he began to preach about Jesus, that this one is the Son of God.

[[v44-9-21]]

^<<v44-9-21,21>>^ But all those hearing him were astonished and were saying: “Is this not the man who ravaged those in Jerusalem who call on this name? Did he not come here for the purpose of arresting them and taking them^&#42;1^ to the chief priests?”

[NOTE]
====
. Lit., “that he might lead them bound.”
====

[[v44-9-22]]

^<<v44-9-22,22>>^ But Saul kept on acquiring more and more power and was confounding the Jews who lived in Damascus, as he proved logically that this is the Christ.

[[v44-9-23]]

^<<v44-9-23,23>>^ Now when many days had passed, the Jews plotted together to do away with him.

[[v44-9-24]]

^<<v44-9-24,24>>^ However, their plot against Saul became known to him. They were also watching the gates closely both day and night in order to do away with him.

[[v44-9-25]]

^<<v44-9-25,25>>^ So his disciples took him and let him down by night through an opening in the wall, lowering him in a basket.

[[v44-9-26]]

^<<v44-9-26,26>>^ On arriving in Jerusalem, he made efforts to join the disciples, but they were all afraid of him, because they did not believe he was a disciple.

[[v44-9-27]]

^<<v44-9-27,27>>^ So Barʹna·bas came to his aid and led him to the apostles, and he told them in detail how on the road he had seen the Lord, and that he had spoken to him, and how in Damascus he had spoken boldly in the name of Jesus.

[[v44-9-28]]

^<<v44-9-28,28>>^ So he remained with them, moving about freely in^&#42;1^ Jerusalem, speaking boldly in the name of the Lord.

[NOTE]
====
. Lit., “walking in and out of.”
====

[[v44-9-29]]

^<<v44-9-29,29>>^ He was talking and disputing with the Greek-speaking Jews, but these made attempts to do away with him.

[[v44-9-30]]

^<<v44-9-30,30>>^ When the brothers found out about this, they brought him down to Caes·a·reʹa and sent him off to Tarsus.

[[v44-9-31]]

^<<v44-9-31,31>>^ Then, indeed, the congregation throughout the whole of Ju·deʹa and Galʹi·lee and Sa·marʹi·a entered into a period of peace, being built up; and as it walked in the fear of Jehovah^&#42;1^ and in the comfort of the holy spirit, it kept on multiplying.

[NOTE]
====
. See App. A5.
====

[[v44-9-32]]

^<<v44-9-32,32>>^ Now as Peter was traveling through all the region, he came down also to the holy ones who lived in Lydʹda.

[[v44-9-33]]

^<<v44-9-33,33>>^ There he found a man named Ae·neʹas, who had been lying flat on his bed for eight years, for he was paralyzed.

[[v44-9-34]]

^<<v44-9-34,34>>^ Peter said to him: “Ae·neʹas, Jesus Christ heals you. Rise and make up your bed.” And he got up immediately.

[[v44-9-35]]

^<<v44-9-35,35>>^ When all those living in Lydʹda and the Plain of Sharʹon saw him, they turned to the Lord.

[[v44-9-36]]

^<<v44-9-36,36>>^ Now there was in Jopʹpa a disciple named Tabʹi·tha, which means, when translated, “Dorʹcas.”^&#42;1^ She abounded in good deeds and gifts of mercy that she was making.

[NOTE]
====
. The Greek name Dorcas and the Aramaic name Tabitha both mean “Gazelle.”
====

[[v44-9-37]]

^<<v44-9-37,37>>^ But in those days she fell sick and died. So they bathed her and laid her in an upper room.

[[v44-9-38]]

^<<v44-9-38,38>>^ Since Lydʹda was near Jopʹpa, when the disciples heard that Peter was in that city, they sent two men to him to urge him: “Please come to us without delay.”

[[v44-9-39]]

^<<v44-9-39,39>>^ At that Peter got up and went with them. And when he arrived, they led him up into the upper room; and all the widows presented themselves to him, weeping and showing many garments and robes^&#42;1^ that Dorʹcas had made while she was with them.

[NOTE]
====
. Or “outer garments.”
====

[[v44-9-40]]

^<<v44-9-40,40>>^ Peter then put everyone outside, and kneeling down, he prayed. Then turning toward the body, he said: “Tabʹi·tha, rise!” She opened her eyes, and as she caught sight of Peter, she sat up.

[[v44-9-41]]

^<<v44-9-41,41>>^ Giving her his hand, he raised her up, and he called the holy ones and the widows and presented her alive.

[[v44-9-42]]

^<<v44-9-42,42>>^ This became known throughout all Jopʹpa, and many became believers in the Lord.

[[v44-9-43]]

^<<v44-9-43,43>>^ He remained for quite a few days in Jopʹpa with a tanner named Simon.

'''

xref:044-acts/044-acts-008.adoc#v44-8-0[&#60; Capítulo Anterior] | <<v44-9-0,Topo>> | xref:044-acts/044-acts-010.adoc#v44-10-0[Próximo Capítulo &#62;]