include::./index.adoc[]

[[v44-22-0]]
=== Acts of Apostles, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v44-22-1]]

^<<v44-22-1,1>>^ “Men, brothers and fathers, hear my defense to you now.”

[[v44-22-2]]

^<<v44-22-2,2>>^ Well, when they heard that he was addressing them in the Hebrew language, they kept all the more silent, and he said:

[[v44-22-3]]

^<<v44-22-3,3>>^ “I am a Jew, born in Tarsus of Ci·liʹcia, but educated in this city at the feet of Ga·maʹli·el, instructed according to the strictness of the ancestral Law, and zealous for God just as all of you are this day.

[[v44-22-4]]

^<<v44-22-4,4>>^ I persecuted this Way to the point of death, binding and handing over to prisons both men and women,

[[v44-22-5]]

^<<v44-22-5,5>>^ as the high priest and all the assembly of elders can bear witness. From them I also obtained letters to the brothers in Damascus, and I was on my way to bring those who were there in bonds to Jerusalem to be punished.

[[v44-22-6]]

^<<v44-22-6,6>>^ “But as I was traveling and getting near to Damascus, about midday, suddenly out of heaven a great light flashed all around me,

[[v44-22-7]]

^<<v44-22-7,7>>^ and I fell to the ground and heard a voice say to me: ‘Saul, Saul, why are you persecuting me?’

[[v44-22-8]]

^<<v44-22-8,8>>^ I answered: ‘Who are you, Lord?’ And he said to me: ‘I am Jesus the Naz·a·reneʹ, whom you are persecuting.’

[[v44-22-9]]

^<<v44-22-9,9>>^ Now the men who were with me did see the light, but they did not hear the voice of the one speaking to me.

[[v44-22-10]]

^<<v44-22-10,10>>^ At that I said: ‘What should I do, Lord?’ The Lord said to me: ‘Rise, go into Damascus, and there you will be told about everything it is appointed for you to do.’

[[v44-22-11]]

^<<v44-22-11,11>>^ But since I could not see anything because of the glory of that light, I arrived in Damascus led by the hand of those who were with me.

[[v44-22-12]]

^<<v44-22-12,12>>^ “Then a man named An·a·niʹas, a devout man according to the Law, well-reported-on by all the Jews living there,

[[v44-22-13]]

^<<v44-22-13,13>>^ came to me. He stood by me and said to me: ‘Saul, brother, regain your sight!’ And that very moment I looked up and saw him.

[[v44-22-14]]

^<<v44-22-14,14>>^ He said: ‘The God of our forefathers has chosen you to come to know his will and to see the righteous one and to hear the voice of his mouth,

[[v44-22-15]]

^<<v44-22-15,15>>^ because you are to be a witness for him to all men of the things you have seen and heard.

[[v44-22-16]]

^<<v44-22-16,16>>^ And now why are you delaying? Rise, get baptized, and wash your sins away by your calling on his name.’

[[v44-22-17]]

^<<v44-22-17,17>>^ “But when I had returned to Jerusalem and was praying in the temple, I fell into a trance

[[v44-22-18]]

^<<v44-22-18,18>>^ and saw him saying to me: ‘Hurry up and get out of Jerusalem quickly, because they will not accept your witness concerning me.’

[[v44-22-19]]

^<<v44-22-19,19>>^ And I said: ‘Lord, they themselves well know that I used to imprison and flog in one synagogue after another those believing in you;

[[v44-22-20]]

^<<v44-22-20,20>>^ and when the blood of Stephen your witness was being spilled, I was standing by and approving and guarding the outer garments of those doing away with him.’

[[v44-22-21]]

^<<v44-22-21,21>>^ And yet he said to me: ‘Go, because I will send you out to nations far away.’”

[[v44-22-22]]

^<<v44-22-22,22>>^ Now they kept listening to him down to this word. Then they raised their voices, saying: “Take such a man away from the earth, for he is not fit to live!”

[[v44-22-23]]

^<<v44-22-23,23>>^ Because they were crying out, throwing their outer garments about, and tossing dust into the air,

[[v44-22-24]]

^<<v44-22-24,24>>^ the military commander ordered Paul to be brought into the soldiers’ quarters and said that he should be interrogated under scourging, so that he could learn exactly why they were shouting against Paul this way.

[[v44-22-25]]

^<<v44-22-25,25>>^ But when they had stretched him out for the whipping, Paul said to the army officer standing there: “Is it lawful for you to scourge a Roman^&#42;1^ who has not been condemned?”^&#42;2^

[NOTE]
====
. Or “Roman citizen.”
. Or “has not had a trial?”
====

[[v44-22-26]]

^<<v44-22-26,26>>^ Well, when the army officer heard this, he went to the military commander and reported it, saying: “What are you intending to do? For this man is a Roman.”

[[v44-22-27]]

^<<v44-22-27,27>>^ So the military commander approached and said to him: “Tell me, are you a Roman?” He said: “Yes.”

[[v44-22-28]]

^<<v44-22-28,28>>^ The military commander responded: “I purchased these rights as a citizen for a large sum of money.” Paul said: “But I have them by birth.”

[[v44-22-29]]

^<<v44-22-29,29>>^ Immediately, therefore, the men who were about to interrogate him under torture backed away from him; and the military commander became afraid when he realized that he was a Roman and that he had bound him in chains.

[[v44-22-30]]

^<<v44-22-30,30>>^ So the next day, because he wanted to know for sure just why he was being accused by the Jews, he released him and commanded the chief priests and all the Sanʹhe·drin to assemble. He then brought Paul down and had him stand among them.

'''

xref:044-acts/044-acts-021.adoc#v44-21-0[&#60; Capítulo Anterior] | <<v44-22-0,Topo>> | xref:044-acts/044-acts-023.adoc#v44-23-0[Próximo Capítulo &#62;]