include::./index.adoc[]

[[v21-3-0]]
=== Ecclesiastes, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v21-3-1]]

^<<v21-3-1,1>>^ There is an appointed time for everything,
A time for every activity under the heavens:

[[v21-3-2]]

^<<v21-3-2,2>>^ A time for birth and a time to die;
A time to plant and a time to uproot what was planted;

[[v21-3-3]]

^<<v21-3-3,3>>^ A time to kill and a time to heal;
A time to tear down and a time to build up;

[[v21-3-4]]

^<<v21-3-4,4>>^ A time to weep and a time to laugh;
A time to wail and a time to dance;^&#42;1^

[NOTE]
====
. Lit., “leap; skip about.”
====

[[v21-3-5]]

^<<v21-3-5,5>>^ A time to throw stones away and a time to gather stones together;
A time to embrace and a time to refrain from embracing;

[[v21-3-6]]

^<<v21-3-6,6>>^ A time to search and a time to give up as lost;
A time to keep and a time to throw away;

[[v21-3-7]]

^<<v21-3-7,7>>^ A time to rip apart and a time to sew together;
A time to be silent and a time to speak;

[[v21-3-8]]

^<<v21-3-8,8>>^ A time to love and a time to hate;
A time for war and a time for peace.

[[v21-3-9]]

^<<v21-3-9,9>>^ What does the worker gain from all his efforts?

[[v21-3-10]]

^<<v21-3-10,10>>^ I have seen the occupation that God has given to the sons of men to keep them occupied.

[[v21-3-11]]

^<<v21-3-11,11>>^ He has made everything beautiful^&#42;1^ in its time. He has even put eternity in their heart; yet mankind will never find out the work that the true God has made from start to finish.

[NOTE]
====
. Or “well-arranged; proper; appropriate.”
====

[[v21-3-12]]

^<<v21-3-12,12>>^ I have concluded that there is nothing better for them than to rejoice and to do good during their life,

[[v21-3-13]]

^<<v21-3-13,13>>^ also that everyone should eat and drink and find enjoyment for all his hard work. It is the gift of God.

[[v21-3-14]]

^<<v21-3-14,14>>^ I have come to know that everything the true God makes will endure forever. There is nothing to add to it and nothing to subtract from it. The true God has made it this way, so that people will fear him.

[[v21-3-15]]

^<<v21-3-15,15>>^ Whatever happens has already happened, and what is to come has already been; but the true God seeks what has been pursued.^&#42;1^

[NOTE]
====
. Or possibly, “what has passed away.”
====

[[v21-3-16]]

^<<v21-3-16,16>>^ I have also seen this under the sun: In the place of justice there was wickedness, and in the place of righteousness there was wickedness.

[[v21-3-17]]

^<<v21-3-17,17>>^ So I said in my heart: “The true God will judge both the righteous and the wicked, for there is a time for every activity and every action.”

[[v21-3-18]]

^<<v21-3-18,18>>^ I also said in my heart about the sons of men that the true God will test them and show them that they are like animals,

[[v21-3-19]]

^<<v21-3-19,19>>^ for there is an outcome^&#42;1^ for humans and an outcome for animals; they all have the same outcome. As the one dies, so the other dies; and they all have but one spirit. So man has no superiority over animals, for everything is futile.

[NOTE]
====
. Or “eventuality.”
====

[[v21-3-20]]

^<<v21-3-20,20>>^ All are going to the same place. They all come from the dust, and they all are returning to the dust.

[[v21-3-21]]

^<<v21-3-21,21>>^ Who really knows whether the spirit of humans ascends upward, and whether the spirit of animals descends down to the earth?

[[v21-3-22]]

^<<v21-3-22,22>>^ And I saw that there is nothing better than for a man to find enjoyment in his work, because that is his reward;^&#42;1^ for who can enable him to see what will happen after he is gone?

[NOTE]
====
. Or “portion.”
====

'''

xref:021-ecclesiastes/021-ecclesiastes-002.adoc#v21-2-0[&#60; Capítulo Anterior] | <<v21-3-0,Topo>> | xref:021-ecclesiastes/021-ecclesiastes-004.adoc#v21-4-0[Próximo Capítulo &#62;]