include::./index.adoc[]

[[v21-11-0]]
=== Ecclesiastes, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v21-11-1]]

^<<v21-11-1,1>>^ Cast^&#42;1^ your bread on the waters, for after many days you will find it again.

[NOTE]
====
. Or “Send out.”
====

[[v21-11-2]]

^<<v21-11-2,2>>^ Give a share to seven or even to eight, for you do not know what disaster^&#42;1^ will occur on the earth.

[NOTE]
====
. Or “calamity.”
====

[[v21-11-3]]

^<<v21-11-3,3>>^ If the clouds are filled with water, they will pour down rain on the earth; and if a tree falls to the south or to the north, the place where the tree falls is where it will lie.

[[v21-11-4]]

^<<v21-11-4,4>>^ The one who watches the wind will not sow seed, and the one who looks at the clouds will not reap.

[[v21-11-5]]

^<<v21-11-5,5>>^ Just as you do not know how the spirit operates in the bones of the child inside^&#42;1^ a pregnant woman, so you do not know the work of the true God, who does all things.

[NOTE]
====
. Lit., “bones in the womb of.”
====

[[v21-11-6]]

^<<v21-11-6,6>>^ Sow your seed in the morning and do not let your hand rest until the evening; for you do not know which will have success, whether this one or that one, or whether they will both do well.

[[v21-11-7]]

^<<v21-11-7,7>>^ Light is sweet, and it is good for the eyes to see the sun.

[[v21-11-8]]

^<<v21-11-8,8>>^ For if a man should live many years, let him enjoy them all. But he should remember that the days of darkness may be many; all that is to come is futility.

[[v21-11-9]]

^<<v21-11-9,9>>^ Rejoice, young man, while you are young, and let your heart be glad in the days of your youth. Follow the ways of your heart and go where your eyes lead you; but know that the true God will bring you into judgment^&#42;1^ for all these things.

[NOTE]
====
. Or “call you to account.”
====

[[v21-11-10]]

^<<v21-11-10,10>>^ So remove troublesome things from your heart, and ward off harmful things from your body,^&#42;1^ for youth and the prime of life are futility.

[NOTE]
====
. Lit., “flesh.”
====

'''

xref:021-ecclesiastes/021-ecclesiastes-010.adoc#v21-10-0[&#60; Capítulo Anterior] | <<v21-11-0,Topo>> | xref:021-ecclesiastes/021-ecclesiastes-012.adoc#v21-12-0[Próximo Capítulo &#62;]