include::./index.adoc[]

[[v21-10-0]]
=== Ecclesiastes, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v21-10-1]]

^<<v21-10-1,1>>^ As dead flies cause the perfumer’s oil to stink and bubble, so a little foolishness outweighs wisdom and glory.

[[v21-10-2]]

^<<v21-10-2,2>>^ The heart of the wise one leads him in the right way,^&#42;1^ but the heart of the stupid one leads him in the wrong way.^&#42;2^

[NOTE]
====
. Lit., “is at his right hand.”
. Lit., “is at his left hand.”
====

[[v21-10-3]]

^<<v21-10-3,3>>^ In whatever way the fool walks, he is lacking good sense,^&#42;1^ and he lets everyone know that he is a fool.

[NOTE]
====
. Lit., “his heart is lacking.”
====

[[v21-10-4]]

^<<v21-10-4,4>>^ If the anger^&#42;1^ of a ruler should flare up against you, do not leave your place, for calmness allays great sins.

[NOTE]
====
. Lit., “spirit; breath.”
====

[[v21-10-5]]

^<<v21-10-5,5>>^ There is something distressing that I have seen under the sun, the sort of mistake made by those in power:

[[v21-10-6]]

^<<v21-10-6,6>>^ Foolishness is put in many high positions, but the rich^&#42;1^ remain in low positions.

[NOTE]
====
. Or “the capable.”
====

[[v21-10-7]]

^<<v21-10-7,7>>^ I have seen servants on horseback but princes walking on foot just like servants.

[[v21-10-8]]

^<<v21-10-8,8>>^ The one who digs a pit may fall into it; and the one who breaks through a stone wall may be bitten by a snake.

[[v21-10-9]]

^<<v21-10-9,9>>^ The one who quarries stones may be hurt by them, and the one who splits logs may be endangered by them.^&#42;1^

[NOTE]
====
. Or possibly, “should be careful with them.”
====

[[v21-10-10]]

^<<v21-10-10,10>>^ If an iron tool is dull and one does not sharpen its edge, he will need to exert much effort. But wisdom helps to achieve success.

[[v21-10-11]]

^<<v21-10-11,11>>^ If the snake bites before it is charmed, there is no advantage to the skilled charmer.^&#42;1^

[NOTE]
====
. Lit., “the master of the tongue.”
====

[[v21-10-12]]

^<<v21-10-12,12>>^ The words from the mouth of the wise one bring favor, but the lips of the stupid one are his ruin.

[[v21-10-13]]

^<<v21-10-13,13>>^ The first words out of his mouth are foolishness, and his last words are disastrous madness.

[[v21-10-14]]

^<<v21-10-14,14>>^ But the fool keeps on speaking.
A man does not know what will happen; who can tell him what will come after him?

[[v21-10-15]]

^<<v21-10-15,15>>^ The hard work of the stupid one wears him out, for he does not even know how to find his way to the city.

[[v21-10-16]]

^<<v21-10-16,16>>^ How terrible for a land when the king is a boy and the princes start their feasting in the morning!

[[v21-10-17]]

^<<v21-10-17,17>>^ How happy for the land when the king is the son of nobles and the princes eat at the proper time for strength, not for drunkenness!

[[v21-10-18]]

^<<v21-10-18,18>>^ Because of extreme laziness the roof beams sag, and because of idle hands the house leaks.

[[v21-10-19]]

^<<v21-10-19,19>>^ Bread^&#42;1^ is made for laughter, and wine makes life enjoyable; but money answers every need.

[NOTE]
====
. Or “Food.”
====

[[v21-10-20]]

^<<v21-10-20,20>>^ Even in your thoughts,^&#42;1^ do not curse^&#42;2^ the king, and do not curse the rich in your bedroom; for a bird^&#42;3^ may convey the sound,^&#42;4^ or a creature with wings may repeat what was said.

[NOTE]
====
. Or possibly, “on your bed.”
. Or “call down evil upon.”
. Lit., “flying creature of the heavens.”
. Or “message.”
====

'''

xref:021-ecclesiastes/021-ecclesiastes-009.adoc#v21-9-0[&#60; Capítulo Anterior] | <<v21-10-0,Topo>> | xref:021-ecclesiastes/021-ecclesiastes-011.adoc#v21-11-0[Próximo Capítulo &#62;]