include::./index.adoc[]

[[v21-7-0]]
=== Ecclesiastes, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v21-7-1]]

^<<v21-7-1,1>>^ A good name^&#42;1^ is better than good oil, and the day of death is better than the day of birth.

[NOTE]
====
. Or “A good reputation.” Lit., “A name.”
====

[[v21-7-2]]

^<<v21-7-2,2>>^ Better to go to the house of mourning than to the house of feasting, for that is the end of every man, and the living should take it to heart.

[[v21-7-3]]

^<<v21-7-3,3>>^ Better is distress than laughter, for the sadness of the face makes the heart better.

[[v21-7-4]]

^<<v21-7-4,4>>^ The heart of the wise is in the house of mourning, but the heart of the stupid is in the house of rejoicing.^&#42;1^

[NOTE]
====
. Or “amusement.”
====

[[v21-7-5]]

^<<v21-7-5,5>>^ Better to listen to a wise man’s rebuke than to listen to the song of fools.

[[v21-7-6]]

^<<v21-7-6,6>>^ For as the crackling of thorns burning under the pot, so is the laughter of the fool; and this too is futility.

[[v21-7-7]]

^<<v21-7-7,7>>^ But oppression can drive the wise one into madness, and a bribe corrupts the heart.

[[v21-7-8]]

^<<v21-7-8,8>>^ Better is the end of a matter than its beginning. Better to be patient than to be haughty in spirit.

[[v21-7-9]]

^<<v21-7-9,9>>^ Do not be quick^&#42;1^ to take offense, for the taking of offense lodges in the bosom of fools.^&#42;2^

[NOTE]
====
. Lit., “hurry in your spirit.”
. Or possibly, “is the mark of a fool.”
====

[[v21-7-10]]

^<<v21-7-10,10>>^ Do not say, “Why were the former days better than these?” for it is not out of wisdom that you ask this.

[[v21-7-11]]

^<<v21-7-11,11>>^ Wisdom together with an inheritance is a good thing and an advantage to those who see the light of day.^&#42;1^

[NOTE]
====
. That is, those alive.
====

[[v21-7-12]]

^<<v21-7-12,12>>^ For wisdom is a protection just as money is a protection, but the advantage of knowledge is this: Wisdom preserves the life of its owner.

[[v21-7-13]]

^<<v21-7-13,13>>^ Consider the work of the true God, for who can straighten out what he has made crooked?

[[v21-7-14]]

^<<v21-7-14,14>>^ On a good day, reflect this goodness, but on the day of adversity,^&#42;1^ consider that God made the one as well as the other, so that men cannot be certain of^&#42;2^ anything that will happen to them in the future.

[NOTE]
====
. Or “calamity.”
. Or “discover.”
====

[[v21-7-15]]

^<<v21-7-15,15>>^ During my futile life I have seen everything—from the righteous one who perishes in his righteousness to the wicked one who lives long despite his badness.

[[v21-7-16]]

^<<v21-7-16,16>>^ Do not be overly righteous, nor show yourself excessively wise. Why should you bring ruin to yourself?

[[v21-7-17]]

^<<v21-7-17,17>>^ Do not be excessively wicked, nor be foolish. Why should you die before your time?

[[v21-7-18]]

^<<v21-7-18,18>>^ It is best to grasp one warning without letting go of the other; for the one who fears God will heed them both.

[[v21-7-19]]

^<<v21-7-19,19>>^ Wisdom makes a wise man more powerful than ten strong men in a city.

[[v21-7-20]]

^<<v21-7-20,20>>^ For there is no righteous man on earth who always does good and never sins.

[[v21-7-21]]

^<<v21-7-21,21>>^ Also, do not take to heart every word that people say; otherwise, you may hear your servant calling down evil on^&#42;1^ you;

[NOTE]
====
. Lit., “cursing.”
====

[[v21-7-22]]

^<<v21-7-22,22>>^ for you well know in your heart that many times you yourself have called down evil on others.

[[v21-7-23]]

^<<v21-7-23,23>>^ All of this I tested with wisdom, and I said: “I will become wise.” But it was beyond me.

[[v21-7-24]]

^<<v21-7-24,24>>^ What has come to be is out of reach and exceedingly deep. Who can understand it?

[[v21-7-25]]

^<<v21-7-25,25>>^ I directed my heart to know and to explore and to search for wisdom and the reason behind things, and to understand the wickedness of stupidity and the folly of madness.

[[v21-7-26]]

^<<v21-7-26,26>>^ Then I discovered this: More bitter than death is the woman who is like a hunter’s net, whose heart is like dragnets, and whose hands are like prison chains. The one who pleases the true God will escape her, but the sinner is captured by her.

[[v21-7-27]]

^<<v21-7-27,27>>^ “See, this is what I found,” says the congregator. “I investigated one thing after another to reach my conclusion,

[[v21-7-28]]

^<<v21-7-28,28>>^ but what I^&#42;1^ continually sought, I have not found. One man^&#42;2^ out of a thousand I found, but a woman among them I have not found.

[NOTE]
====
. Or “my soul.”
. Or “upright man.”
====

[[v21-7-29]]

^<<v21-7-29,29>>^ This alone I have found: The true God made mankind upright, but they have sought out many schemes.”

'''

xref:021-ecclesiastes/021-ecclesiastes-006.adoc#v21-6-0[&#60; Capítulo Anterior] | <<v21-7-0,Topo>> | xref:021-ecclesiastes/021-ecclesiastes-008.adoc#v21-8-0[Próximo Capítulo &#62;]