include::./index.adoc[]

[[v21-2-0]]
=== Ecclesiastes, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v21-2-1]]

^<<v21-2-1,1>>^ Then I said in my heart: “Come and let me try out pleasure^&#42;1^ and see what good comes.” But look! that too was futility.

[NOTE]
====
. Or “rejoicing.”
====

[[v21-2-2]]

^<<v21-2-2,2>>^ I said about laughter, “It is madness!”
And about pleasure,^&#42;1^ “What use is it?”

[NOTE]
====
. Or “rejoicing.”
====

[[v21-2-3]]

^<<v21-2-3,3>>^ I explored with my heart by indulging myself with wine, all the while maintaining my own wisdom; I even embraced foolishness to find out what was the best thing for humans to do during their few days of life under the heavens.

[[v21-2-4]]

^<<v21-2-4,4>>^ I undertook great works. I built houses for myself; I planted vineyards for myself.

[[v21-2-5]]

^<<v21-2-5,5>>^ I made gardens and parks for myself, and I planted in them all sorts of fruit trees.

[[v21-2-6]]

^<<v21-2-6,6>>^ I made pools of water for myself, to irrigate a grove^&#42;1^ of flourishing trees.

[NOTE]
====
. Or “forest.”
====

[[v21-2-7]]

^<<v21-2-7,7>>^ I acquired male and female servants, and I had servants born in my household.^&#42;1^ I also acquired much livestock—cattle and flocks—more than any of my predecessors in Jerusalem.

[NOTE]
====
. Lit., “sons of the house.”
====

[[v21-2-8]]

^<<v21-2-8,8>>^ I accumulated silver and gold for myself, the treasures of^&#42;1^ kings and of provinces. I gathered male and female singers for myself, as well as what brings great pleasure to the sons of men—a woman, yes, many women.^&#42;2^

[NOTE]
====
. Or “property peculiar to.”
. Or “a lady, yes, ladies.”
====

[[v21-2-9]]

^<<v21-2-9,9>>^ So I grew great and surpassed anyone prior to me in Jerusalem. And my wisdom remained with me.

[[v21-2-10]]

^<<v21-2-10,10>>^ I did not deny myself anything that I desired.^&#42;1^ I did not withhold from my heart any sort of pleasure,^&#42;2^ for my heart was joyful because of all my hard work, and this was my reward^&#42;3^ for all my hard work.

[NOTE]
====
. Lit., “that my eyes asked for.”
. Or “rejoicing.”
. Or “portion.”
====

[[v21-2-11]]

^<<v21-2-11,11>>^ But when I reflected on all the works that my own hands had done and on all the hard work that I had toiled to accomplish, I saw that everything was futile, a chasing after the wind; there was nothing of real value^&#42;1^ under the sun.

[NOTE]
====
. Or “of advantage.”
====

[[v21-2-12]]

^<<v21-2-12,12>>^ Then I turned my attention to wisdom and madness and folly. (For what can the man do who comes after the king? Only what has already been done.)

[[v21-2-13]]

^<<v21-2-13,13>>^ And I saw that there is an advantage to wisdom over folly, just as there is an advantage to light over darkness.

[[v21-2-14]]

^<<v21-2-14,14>>^ The wise one has his eyes in his head;^&#42;1^ but the stupid one is walking in darkness. I have also come to realize that there is one outcome^&#42;2^ that befalls all of them.

[NOTE]
====
. Or “has his eyes open.”
. Or “eventuality.”
====

[[v21-2-15]]

^<<v21-2-15,15>>^ Then I said in my heart: “What happens to the stupid one will also happen to me.” What, then, did I gain by becoming excessively wise? So I said in my heart: “This too is futility.”

[[v21-2-16]]

^<<v21-2-16,16>>^ For there is no lasting memory either of the wise one or of the stupid one. In the days to come, everyone will be forgotten. And how will the wise one die? Along with the stupid one.

[[v21-2-17]]

^<<v21-2-17,17>>^ So I came to hate life, because everything being done under the sun seemed distressing to me, for everything was futile, a chasing after the wind.

[[v21-2-18]]

^<<v21-2-18,18>>^ I came to hate all that I had worked so hard for under the sun, because I must leave it behind for the man coming after me.

[[v21-2-19]]

^<<v21-2-19,19>>^ And who knows whether he will be wise or foolish? Yet he will take control over all the things I spent great effort and wisdom to acquire under the sun. This too is futility.

[[v21-2-20]]

^<<v21-2-20,20>>^ So I began to despair in my heart over all the hard work at which I had toiled under the sun.

[[v21-2-21]]

^<<v21-2-21,21>>^ For a man may work hard, guided by wisdom and knowledge and skill, but he must hand over his portion^&#42;1^ to a man who did not work for it. This too is futility and a great tragedy.^&#42;2^

[NOTE]
====
. Or “hand over everything.”
. Or “calamity.”
====

[[v21-2-22]]

^<<v21-2-22,22>>^ What does a man really gain from all his hard work and ambition that drives him^&#42;1^ to work hard under the sun?

[NOTE]
====
. Lit., “and the striving of his heart.”
====

[[v21-2-23]]

^<<v21-2-23,23>>^ For during all his days, his occupation brings pain and frustration, and even at night his heart does not rest. This too is futility.

[[v21-2-24]]

^<<v21-2-24,24>>^ There is nothing better for a man than to eat and drink and find enjoyment^&#42;1^ in his hard work. This too, I have realized, is from the hand of the true God,

[NOTE]
====
. Or “cause his soul to see good.”
====

[[v21-2-25]]

^<<v21-2-25,25>>^ for who eats and who drinks better than I do?

[[v21-2-26]]

^<<v21-2-26,26>>^ To the man who pleases him he gives wisdom and knowledge and rejoicing, but to the sinner he gives the occupation of gathering and merely collecting to give to the one who pleases the true God. This too is futility, a chasing after the wind.

'''

xref:021-ecclesiastes/021-ecclesiastes-001.adoc#v21-1-0[&#60; Capítulo Anterior] | <<v21-2-0,Topo>> | xref:021-ecclesiastes/021-ecclesiastes-003.adoc#v21-3-0[Próximo Capítulo &#62;]