include::./index.adoc[]

[[v21-1-0]]
=== Ecclesiastes, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v21-1-1]]

^<<v21-1-1,1>>^ The words of the congregator,^&#42;1^ the son of David, the king in Jerusalem.

[NOTE]
====
. Or “assembler; convener.”
====

[[v21-1-2]]

^<<v21-1-2,2>>^ “The greatest futility!”^&#42;1^ says the congregator,
“The greatest futility! Everything is futile!”

[NOTE]
====
. Or “vanity.”
====

[[v21-1-3]]

^<<v21-1-3,3>>^ What does a person gain from all his hard work
At which he toils under the sun?

[[v21-1-4]]

^<<v21-1-4,4>>^ A generation is going, and a generation is coming,
But the earth remains^&#42;1^ forever.

[NOTE]
====
. Lit., “is standing.”
====

[[v21-1-5]]

^<<v21-1-5,5>>^ The sun rises,^&#42;1^ and the sun sets;
Then it hurries back^&#42;2^ to the place where it rises again.

[NOTE]
====
. Or “shines forth.”
. Or “returns panting.”
====

[[v21-1-6]]

^<<v21-1-6,6>>^ The wind goes south and circles around to the north;
Round and round it continuously circles; the wind keeps making its rounds.

[[v21-1-7]]

^<<v21-1-7,7>>^ All the streams^&#42;1^ flow into the sea, yet the sea is not full.
To the place from which the streams flow, there they return so as to flow again.

[NOTE]
====
. Or “winter streams; seasonal streams.”
====

[[v21-1-8]]

^<<v21-1-8,8>>^ All things are wearisome;
No one can even speak of it.
The eye is not satisfied at seeing;
Nor is the ear filled from hearing.

[[v21-1-9]]

^<<v21-1-9,9>>^ What has been is what will be,
And what has been done will be done again;
There is nothing new under the sun.

[[v21-1-10]]

^<<v21-1-10,10>>^ Is there anything of which one may say, “Look at this—it is new”?
It already existed from long ago;
It already existed before our time.

[[v21-1-11]]

^<<v21-1-11,11>>^ No one remembers people of former times;
Nor will anyone remember those who come later;
Nor will they be remembered by those who come still later.

[[v21-1-12]]

^<<v21-1-12,12>>^ I, the congregator, have been king over Israel in Jerusalem.

[[v21-1-13]]

^<<v21-1-13,13>>^ I set my heart to study and explore with wisdom everything that has been done under the heavens—the miserable occupation that God has given to the sons of men that keeps them occupied.

[[v21-1-14]]

^<<v21-1-14,14>>^ I saw all the works that were done under the sun,
And look! everything was futile, a chasing after the wind.

[[v21-1-15]]

^<<v21-1-15,15>>^ What is crooked cannot be made straight,
And what is lacking cannot possibly be counted.

[[v21-1-16]]

^<<v21-1-16,16>>^ Then I said in my heart: “Look! I have acquired great wisdom, more than anyone who was before me in Jerusalem, and my heart gained a great deal of wisdom and knowledge.”

[[v21-1-17]]

^<<v21-1-17,17>>^ I applied my heart to knowing wisdom and to knowing madness^&#42;1^ and to knowing folly, and this too is a chasing after the wind.

[NOTE]
====
. Or “extreme foolishness.”
====

[[v21-1-18]]

^<<v21-1-18,18>>^ For an abundance of wisdom brings an abundance of frustration,
So that whoever increases knowledge increases pain.

'''

xref:020-proverbs/020-proverbs-031.adoc#v20-31-0[&#60; Capítulo Anterior] | <<v21-1-0,Topo>> | xref:021-ecclesiastes/021-ecclesiastes-002.adoc#v21-2-0[Próximo Capítulo &#62;]