include::./index.adoc[]

[[v56-3-0]]
=== To Titus, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v56-3-1]]

^<<v56-3-1,1>>^ Continue reminding them to be in subjection and to be obedient to governments and authorities, to be ready for every good work,

[[v56-3-2]]

^<<v56-3-2,2>>^ to speak injuriously of no one, not to be quarrelsome, but to be reasonable, displaying all mildness toward all men.

[[v56-3-3]]

^<<v56-3-3,3>>^ For we too were once senseless, disobedient, led astray, being slaves to various desires and pleasures, carrying on in badness and envy, detestable, hating one another.

[[v56-3-4]]

^<<v56-3-4,4>>^ However, when the kindness of our Savior, God, and his love for mankind were manifested

[[v56-3-5]]

^<<v56-3-5,5>>^ (not because of any righteous works we had done, but because of his own mercy), he saved us by means of the bath that brought us to life and by making us new by holy spirit.

[[v56-3-6]]

^<<v56-3-6,6>>^ He poured this spirit out richly^&#42;1^ on us through Jesus Christ our Savior,

[NOTE]
====
. Or “generously.”
====

[[v56-3-7]]

^<<v56-3-7,7>>^ so that after being declared righteous through the undeserved kindness of that one, we might become heirs according to a hope of everlasting life.

[[v56-3-8]]

^<<v56-3-8,8>>^ These words are trustworthy, and I want you to keep stressing these matters, so that those who have believed God may keep their minds focused on maintaining fine works. These things are fine and beneficial to men.

[[v56-3-9]]

^<<v56-3-9,9>>^ But have nothing to do with foolish arguments and genealogies and disputes and fights over the Law, for they are unprofitable and futile.

[[v56-3-10]]

^<<v56-3-10,10>>^ As for a man who promotes a sect, reject him after a first and a second admonition,^&#42;1^

[NOTE]
====
. Or “warning.”
====

[[v56-3-11]]

^<<v56-3-11,11>>^ knowing that such a man has deviated from the way and is sinning and is self-condemned.

[[v56-3-12]]

^<<v56-3-12,12>>^ When I send Arʹte·mas or Tychʹi·cus to you, do your utmost to come to me at Ni·copʹo·lis, for that is where I have decided to spend the winter.

[[v56-3-13]]

^<<v56-3-13,13>>^ Carefully supply Zeʹnas, who is versed in the Law, and A·polʹlos so that they may lack nothing for their trip.

[[v56-3-14]]

^<<v56-3-14,14>>^ But let our people also learn to maintain fine works so as to help in cases of urgent need, so that they may not be unproductive.^&#42;1^

[NOTE]
====
. Lit., “unfruitful.”
====

[[v56-3-15]]

^<<v56-3-15,15>>^ All those with me send you their greetings. Give my greetings to those who have affection for us in the faith.
May the undeserved kindness be with all of you.

'''

xref:056-titus/056-titus-002.adoc#v56-2-0[&#60; Capítulo Anterior] | <<v56-3-0,Topo>> | xref:057-philemon/057-philemon-001.adoc#v57-1-0[Próximo Capítulo &#62;]