include::./index.adoc[]

[[v56-2-0]]
=== To Titus, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v56-2-1]]

^<<v56-2-1,1>>^ You, however, keep on speaking what is consistent with wholesome^&#42;1^ teaching.

[NOTE]
====
. Or “healthful; beneficial.”
====

[[v56-2-2]]

^<<v56-2-2,2>>^ Let the older men be moderate in habits, serious, sound in mind, healthy in faith, in love, in endurance.

[[v56-2-3]]

^<<v56-2-3,3>>^ Likewise, let the older women be reverent in behavior, not slanderous, not enslaved to a lot of wine, teachers of what is good,

[[v56-2-4]]

^<<v56-2-4,4>>^ so that they may advise^&#42;1^ the younger women to love their husbands, to love their children,

[NOTE]
====
. Or “recall to their senses; train.”
====

[[v56-2-5]]

^<<v56-2-5,5>>^ to be sound in mind, chaste, working at home,^&#42;1^ good, subjecting themselves to their own husbands, so that the word of God may not be spoken of abusively.

[NOTE]
====
. Or “caring for their homes.”
====

[[v56-2-6]]

^<<v56-2-6,6>>^ Likewise, keep on urging the younger men to be sound in mind,

[[v56-2-7]]

^<<v56-2-7,7>>^ showing yourself to be an example of fine works in every way. Teach what is pure^&#42;1^ with all seriousness,

[NOTE]
====
. Or possibly, “Teach with purity.”
====

[[v56-2-8]]

^<<v56-2-8,8>>^ using wholesome^&#42;1^ speech that cannot be criticized, so that those who oppose may be put to shame, having nothing negative^&#42;2^ to say about us.

[NOTE]
====
. Or “healthful; beneficial.”
. Or “vile.”
====

[[v56-2-9]]

^<<v56-2-9,9>>^ Let slaves be in subjection to their owners in all things, trying to please them, not talking back,

[[v56-2-10]]

^<<v56-2-10,10>>^ not stealing from them, but showing complete trustworthiness, so that in every way they may adorn the teaching of our Savior, God.

[[v56-2-11]]

^<<v56-2-11,11>>^ For the undeserved kindness of God has been manifested, bringing salvation to all sorts of people.

[[v56-2-12]]

^<<v56-2-12,12>>^ It trains us to reject ungodliness and worldly desires and to live with soundness of mind and righteousness and godly devotion amid this present system of things,^&#42;1^

[NOTE]
====
. Or “this present age.” See Glossary.
====

[[v56-2-13]]

^<<v56-2-13,13>>^ while we wait for the happy hope and glorious manifestation of the great God and of our Savior, Jesus Christ,

[[v56-2-14]]

^<<v56-2-14,14>>^ who gave himself for us to set us free^&#42;1^ from every sort of lawlessness and to cleanse for himself a people who are his own special possession, zealous for fine works.

[NOTE]
====
. Lit., “to ransom us; to redeem us.”
====

[[v56-2-15]]

^<<v56-2-15,15>>^ Keep on speaking these things and exhorting^&#42;1^ and reproving with full authority. Do not let anyone look down on you.

[NOTE]
====
. Or “encouraging.”
====

'''

xref:056-titus/056-titus-001.adoc#v56-1-0[&#60; Capítulo Anterior] | <<v56-2-0,Topo>> | xref:056-titus/056-titus-003.adoc#v56-3-0[Próximo Capítulo &#62;]