include::./index.adoc[]

[[v59-5-0]]
=== The Letter of James, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v59-5-1]]

^<<v59-5-1,1>>^ Come, now, you rich men, weep and wail over the miseries that are coming upon you.

[[v59-5-2]]

^<<v59-5-2,2>>^ Your riches have rotted, and your clothing has become moth-eaten.

[[v59-5-3]]

^<<v59-5-3,3>>^ Your gold and silver have rusted away, and their rust will be a witness against you and will consume your flesh. What you have stored up will be like a fire in the last days.

[[v59-5-4]]

^<<v59-5-4,4>>^ Look! The wages you have withheld from the workers who harvested your fields keep crying out, and the cries for help of the reapers have reached the ears of Jehovah^&#42;1^ of armies.

[NOTE]
====
. See App. A5.
====

[[v59-5-5]]

^<<v59-5-5,5>>^ You have lived in luxury and for self-gratification on the earth. You have fattened your hearts on the day of slaughter.

[[v59-5-6]]

^<<v59-5-6,6>>^ You have condemned; you have murdered the righteous one. Is he not opposing you?

[[v59-5-7]]

^<<v59-5-7,7>>^ Be patient then, brothers, until the presence of the Lord. Look! The farmer keeps waiting for the precious fruit of the earth, exercising patience over it until the early rain and the late rain arrive.

[[v59-5-8]]

^<<v59-5-8,8>>^ You too exercise patience; make your hearts firm, because the presence of the Lord has drawn close.

[[v59-5-9]]

^<<v59-5-9,9>>^ Do not grumble^&#42;1^ against one another, brothers, so that you do not get judged. Look! The Judge is standing before the doors.

[NOTE]
====
. Or “groan; complain.” Lit., “heave sighs.”
====

[[v59-5-10]]

^<<v59-5-10,10>>^ Brothers, take as a pattern of the suffering of evil and the exercising of patience the prophets who spoke in the name of Jehovah.^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v59-5-11]]

^<<v59-5-11,11>>^ Look! We consider happy^&#42;1^ those who have endured. You have heard of the endurance of Job and have seen the outcome Jehovah^&#42;2^ gave, that Jehovah^&#42;3^ is very tender in affection^&#42;4^ and merciful.

[NOTE]
====
. Or “blessed.”
. See App. A5.
. See App. A5.
. Or “very compassionate.”
====

[[v59-5-12]]

^<<v59-5-12,12>>^ Above all, my brothers, stop swearing, either by heaven or by earth or by any other oath. But let your “Yes” mean yes and your “No,” no, so that you do not become liable to judgment.

[[v59-5-13]]

^<<v59-5-13,13>>^ Is there anyone suffering hardship among you? Let him carry on prayer. Is there anyone in good spirits? Let him sing psalms.

[[v59-5-14]]

^<<v59-5-14,14>>^ Is there anyone sick among you? Let him call the elders of the congregation to him, and let them pray over him, applying oil to him in the name of Jehovah.^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v59-5-15]]

^<<v59-5-15,15>>^ And the prayer of faith will make the sick one^&#42;1^ well, and Jehovah^&#42;2^ will raise him up. Also, if he has committed sins, he will be forgiven.

[NOTE]
====
. Or possibly, “tired one.”
. See App. A5.
====

[[v59-5-16]]

^<<v59-5-16,16>>^ Therefore, openly confess your sins to one another and pray for one another, so that you may be healed. A righteous man’s supplication has a powerful effect.^&#42;1^

[NOTE]
====
. Lit., “has much force when it is at work.”
====

[[v59-5-17]]

^<<v59-5-17,17>>^ E·liʹjah was a man with feelings like ours, and yet when he prayed earnestly for it not to rain, it did not rain on the land for three years and six months.

[[v59-5-18]]

^<<v59-5-18,18>>^ Then he prayed again, and the heaven gave rain and the land produced fruit.

[[v59-5-19]]

^<<v59-5-19,19>>^ My brothers, if anyone among you is led astray from the truth and another turns him back,

[[v59-5-20]]

^<<v59-5-20,20>>^ know that whoever turns a sinner back from the error of his way will save him^&#42;1^ from death and will cover a multitude of sins.

[NOTE]
====
. Or “his soul.”
====

'''

xref:059-james/059-james-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-1-peter/060-1-peter-001.adoc#v60-1-0[Próximo Capítulo &#62;]