include::./index.adoc[]

[[v59-4-0]]
=== The Letter of James, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v59-4-1]]

^<<v59-4-1,1>>^ What is the source of the wars and fights among you? Do they not originate from your fleshly desires that carry on a conflict within you?^&#42;1^

[NOTE]
====
. Lit., “in your members.”
====

[[v59-4-2]]

^<<v59-4-2,2>>^ You desire, and yet you do not have. You go on murdering and coveting, and yet you are not able to obtain. You go on fighting and waging war. You do not have because of your not asking.

[[v59-4-3]]

^<<v59-4-3,3>>^ When you do ask, you do not receive because you are asking for a wrong purpose, so that you may spend it on your fleshly desires.

[[v59-4-4]]

^<<v59-4-4,4>>^ Adulteresses,^&#42;1^ do you not know that friendship with the world is enmity with God? Whoever, therefore, wants to be a friend of the world is making himself an enemy of God.

[NOTE]
====
. Or “You unfaithful ones.”
====

[[v59-4-5]]

^<<v59-4-5,5>>^ Or do you think that for no reason the scripture says: “The spirit that has taken up residence within us keeps enviously longing”?

[[v59-4-6]]

^<<v59-4-6,6>>^ However, the undeserved kindness that He gives is greater. So it says: “God opposes the haughty ones, but he gives undeserved kindness to the humble ones.”

[[v59-4-7]]

^<<v59-4-7,7>>^ Therefore, subject yourselves to God; but oppose the Devil, and he will flee from you.

[[v59-4-8]]

^<<v59-4-8,8>>^ Draw close to God, and he will draw close to you. Cleanse your hands, you sinners, and purify your hearts, you indecisive ones.

[[v59-4-9]]

^<<v59-4-9,9>>^ Give way to misery and mourn and weep. Let your laughter be turned into mourning, and your joy into despair.

[[v59-4-10]]

^<<v59-4-10,10>>^ Humble yourselves in the eyes of Jehovah,^&#42;1^ and he will exalt you.

[NOTE]
====
. See App. A5.
====

[[v59-4-11]]

^<<v59-4-11,11>>^ Stop speaking against one another, brothers. Whoever speaks against a brother or judges his brother speaks against law and judges law. Now if you judge law, you are not a doer of law but a judge.

[[v59-4-12]]

^<<v59-4-12,12>>^ There is only one who is Lawgiver and Judge, the one who is able to save and to destroy. But you, who are you to be judging your neighbor?

[[v59-4-13]]

^<<v59-4-13,13>>^ Come, now, you who say: “Today or tomorrow we will travel to this city and will spend a year there, and we will do business and make some profit,”

[[v59-4-14]]

^<<v59-4-14,14>>^ whereas you do not know what your life will be like tomorrow. For you are a mist that appears for a little while and then disappears.

[[v59-4-15]]

^<<v59-4-15,15>>^ Instead, you should say: “If Jehovah^&#42;1^ wills, we will live and do this or that.”

[NOTE]
====
. See App. A5.
====

[[v59-4-16]]

^<<v59-4-16,16>>^ But now you take pride in your arrogant boasting. All such boasting is wicked.

[[v59-4-17]]

^<<v59-4-17,17>>^ Therefore, if someone knows how to do what is right and yet does not do it, it is a sin for him.

'''

xref:059-james/059-james-003.adoc#v59-3-0[&#60; Capítulo Anterior] | <<v59-4-0,Topo>> | xref:059-james/059-james-005.adoc#v59-5-0[Próximo Capítulo &#62;]