include::./index.adoc[]

[[v59-3-0]]
=== The Letter of James, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v59-3-1]]

^<<v59-3-1,1>>^ Not many of you should become teachers, my brothers, knowing that we will receive heavier^&#42;1^ judgment.

[NOTE]
====
. Or “stricter.”
====

[[v59-3-2]]

^<<v59-3-2,2>>^ For we all stumble^&#42;1^ many times. If anyone does not stumble in word, he is a perfect man, able to bridle also his whole body.

[NOTE]
====
. Or “make mistakes.”
====

[[v59-3-3]]

^<<v59-3-3,3>>^ If we put bridles in the mouths of horses to make them obey us, we guide also their whole body.

[[v59-3-4]]

^<<v59-3-4,4>>^ Look also at ships: Although they are so big and are driven by strong winds, they are steered by a very small rudder wherever the man at the helm is inclined to go.

[[v59-3-5]]

^<<v59-3-5,5>>^ So, too, the tongue is a small part of the body, and yet it makes great brags. See how small a fire it takes to set a great forest ablaze!

[[v59-3-6]]

^<<v59-3-6,6>>^ The tongue is also a fire. The tongue represents a world of unrighteousness among our body members, for it defiles all the body and sets the whole course of life^&#42;1^ on fire, and it is set on fire by Ge·henʹna.^&#42;2^

[NOTE]
====
. Lit., “the wheel of the birth (origin).”
. See Glossary.
====

[[v59-3-7]]

^<<v59-3-7,7>>^ For every kind of wild animal and bird and reptile^&#42;1^ and sea creature is to be tamed and has been tamed by humans.

[NOTE]
====
. Or “creeping thing.”
====

[[v59-3-8]]

^<<v59-3-8,8>>^ But no human can tame the tongue. It is unruly and injurious, full of deadly poison.

[[v59-3-9]]

^<<v59-3-9,9>>^ With it we praise Jehovah,^&#42;1^ the Father, and yet with it we curse men who have come into existence “in the likeness of God.”

[NOTE]
====
. See App. A5.
====

[[v59-3-10]]

^<<v59-3-10,10>>^ Out of the same mouth come blessing and cursing.
My brothers, it is not right for things to happen this way.

[[v59-3-11]]

^<<v59-3-11,11>>^ A spring does not cause the fresh^&#42;1^ water and the bitter water to bubble out of the same opening, does it?

[NOTE]
====
. Lit., “sweet.”
====

[[v59-3-12]]

^<<v59-3-12,12>>^ My brothers, a fig tree cannot produce olives, or a grapevine figs, can it? Neither can salt water produce fresh water.

[[v59-3-13]]

^<<v59-3-13,13>>^ Who is wise and understanding among you? Let him by his fine conduct demonstrate works performed with a mildness that comes from wisdom.

[[v59-3-14]]

^<<v59-3-14,14>>^ But if you have bitter jealousy and contentiousness^&#42;1^ in your hearts, do not be bragging and lying against the truth.

[NOTE]
====
. Or possibly, “selfish ambition.”
====

[[v59-3-15]]

^<<v59-3-15,15>>^ This is not the wisdom that comes down from above; it is earthly, animalistic, demonic.

[[v59-3-16]]

^<<v59-3-16,16>>^ For wherever there are jealousy and contentiousness,^&#42;1^ there will also be disorder and every vile thing.

[NOTE]
====
. Or possibly, “selfish ambition.”
====

[[v59-3-17]]

^<<v59-3-17,17>>^ But the wisdom from above is first of all pure, then peaceable, reasonable, ready to obey, full of mercy and good fruits, impartial, not hypocritical.

[[v59-3-18]]

^<<v59-3-18,18>>^ Moreover, the fruit of righteousness is sown in peaceful conditions for^&#42;1^ those who are making peace.

[NOTE]
====
. Or possibly, “by.”
====

'''

xref:059-james/059-james-002.adoc#v59-2-0[&#60; Capítulo Anterior] | <<v59-3-0,Topo>> | xref:059-james/059-james-004.adoc#v59-4-0[Próximo Capítulo &#62;]