include::./index.adoc[]

[[v5-22-0]]
=== Deuteronomy, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-22-1]]

^<<v5-22-1,1>>^ “If you see your brother’s bull or his sheep going astray, do not deliberately ignore it. You should without fail lead it back to your brother.

[[v5-22-2]]

^<<v5-22-2,2>>^ But if your brother does not live near you or you do not know him, you should bring the animal to your house, and it will remain with you until your brother searches for it. Then you should return it to him.

[[v5-22-3]]

^<<v5-22-3,3>>^ That is what you should do with his donkey, with his clothing, and with anything that your brother has lost and you have found. You must not ignore it.

[[v5-22-4]]

^<<v5-22-4,4>>^ “If you see your brother’s donkey or his bull fall down on the road, you must not deliberately ignore it. You should without fail help him raise the animal up.

[[v5-22-5]]

^<<v5-22-5,5>>^ “A woman must not put on the clothing of a man, nor should a man wear the clothing of a woman. For anyone doing so is detestable to Jehovah your God.

[[v5-22-6]]

^<<v5-22-6,6>>^ “If you happen upon a bird’s nest along the road with young ones or eggs, whether in a tree or on the ground, and the mother is sitting on the young ones or the eggs, you must not take the mother together with her young.

[[v5-22-7]]

^<<v5-22-7,7>>^ Be sure to send the mother away, but you may take the young for yourself. Do this so that it may go well with you and you may live long.

[[v5-22-8]]

^<<v5-22-8,8>>^ “If you build a new house, you must also make a parapet for your roof, so that you may not bring bloodguilt on your house because of someone falling from it.

[[v5-22-9]]

^<<v5-22-9,9>>^ “You must not sow your vineyard with two sorts of seed. Otherwise, everything produced from the seed you sow as well as the product of the vineyard will be forfeited to the sanctuary.

[[v5-22-10]]

^<<v5-22-10,10>>^ “You must not plow with a bull and a donkey together.

[[v5-22-11]]

^<<v5-22-11,11>>^ “You must not wear clothing made of wool and linen mixed together.

[[v5-22-12]]

^<<v5-22-12,12>>^ “You should make tassels on the four corners of the clothing you wear.

[[v5-22-13]]

^<<v5-22-13,13>>^ “If a man takes a wife and has relations with her but then comes to hate her^&#42;1^

[NOTE]
====
. Or “then rejects her.”
====

[[v5-22-14]]

^<<v5-22-14,14>>^ and he accuses her of misconduct and gives her a bad name by saying: ‘I have taken this woman, but when I had relations with her, I did not find evidence that she was a virgin,’

[[v5-22-15]]

^<<v5-22-15,15>>^ the father and mother of the girl should produce the evidence of the girl’s virginity for the elders at the gate of the city.

[[v5-22-16]]

^<<v5-22-16,16>>^ The girl’s father must say to the elders, ‘I gave my daughter to this man as a wife, but he hates^&#42;1^ her

[NOTE]
====
. Or “rejects.”
====

[[v5-22-17]]

^<<v5-22-17,17>>^ and is accusing her of misconduct by saying: “I have found out that your daughter does not have evidence of virginity.” Now this is the evidence of my daughter’s virginity.’ They will then spread out the cloth before the elders of the city.

[[v5-22-18]]

^<<v5-22-18,18>>^ The city elders will take the man and discipline him.

[[v5-22-19]]

^<<v5-22-19,19>>^ They will fine him 100 silver shekels^&#42;1^ and give them to the girl’s father, because the man defamed a virgin of Israel, and she will continue to be his wife. He will not be allowed to divorce her as long as he lives.

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v5-22-20]]

^<<v5-22-20,20>>^ “If, though, the accusation is true, and there is no evidence that the girl was a virgin,

[[v5-22-21]]

^<<v5-22-21,21>>^ they should bring the girl out to the entrance of her father’s house, and the men of her city should stone her to death, because she has committed a disgraceful act in Israel by committing sexual immorality^&#42;1^ in the house of her father. So you must remove what is bad from your midst.

[NOTE]
====
. Or “prostitution.”
====

[[v5-22-22]]

^<<v5-22-22,22>>^ “If a man is found lying down with a woman who is the wife of another man, both of them must die together, the man who lay down with the woman as well as the woman. So you must remove what is bad out of Israel.

[[v5-22-23]]

^<<v5-22-23,23>>^ “If a virgin is engaged to a man, and another man happens to meet her in the city and lies down with her,

[[v5-22-24]]

^<<v5-22-24,24>>^ you should bring them both out to the gate of that city and stone them to death, the girl because she did not scream in the city and the man because he humiliated the wife of his fellow man. So you must remove what is evil from your midst.

[[v5-22-25]]

^<<v5-22-25,25>>^ “If, however, the man happened to meet the engaged girl in the field and the man overpowered her and lay down with her, the man who lay down with her is to die by himself,

[[v5-22-26]]

^<<v5-22-26,26>>^ and you must do nothing to the girl. The girl has not committed a sin deserving of death. This case is the same as when a man attacks his fellow man and murders him.^&#42;1^

[NOTE]
====
. Or “murders him, a soul.”
====

[[v5-22-27]]

^<<v5-22-27,27>>^ For he happened to meet her in the field, and the engaged girl screamed, but there was no one to rescue her.

[[v5-22-28]]

^<<v5-22-28,28>>^ “If a man happens to meet a virgin girl who is not engaged and he seizes her and lies down with her and they are discovered,

[[v5-22-29]]

^<<v5-22-29,29>>^ the man who lay down with her must give the girl’s father 50 silver shekels, and she will become his wife. Because he humiliated her, he will not be allowed to divorce her as long as he lives.

[[v5-22-30]]

^<<v5-22-30,30>>^ “No man should take his father’s wife, so that he may not dishonor his father.^&#42;1^

[NOTE]
====
. Lit., “uncover the skirt of his father.”
====

'''

xref:005-deuteronomy/005-deuteronomy-021.adoc#v5-21-0[&#60; Capítulo Anterior] | <<v5-22-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-023.adoc#v5-23-0[Próximo Capítulo &#62;]