include::./index.adoc[]

[[v5-9-0]]
=== Deuteronomy, 9
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-9-1]]

^<<v5-9-1,1>>^ “Hear, O Israel, today you are crossing the Jordan to go in and dispossess nations greater and mightier than you, cities great and fortified to the heavens,^&#42;1^

[NOTE]
====
. That is, with towering walls.
====

[[v5-9-2]]

^<<v5-9-2,2>>^ a people great and tall, the sons of the Anʹa·kim, about whom you know and have heard it said, ‘Who can stand up to the sons of Aʹnak?’

[[v5-9-3]]

^<<v5-9-3,3>>^ Therefore, you should know this day that Jehovah your God will cross ahead of you. He is a consuming fire, and he will annihilate them. He will subdue them before your eyes so that you may quickly drive them out^&#42;1^ and destroy them, just as Jehovah has promised you.

[NOTE]
====
. Or “dispossess them.”
====

[[v5-9-4]]

^<<v5-9-4,4>>^ “Do not say in your heart when Jehovah your God drives them away from before you, ‘It was because of my own righteousness that Jehovah has brought me in to take possession of this land.’ Rather, it is because of the wickedness of these nations that Jehovah is driving them away from before you.

[[v5-9-5]]

^<<v5-9-5,5>>^ It is not because of your righteousness or the uprightness of your heart that you are going in to take possession of their land. Instead, it is because of the wickedness of these nations that Jehovah your God is driving them away from before you and in order to carry out the word that Jehovah swore to your forefathers, Abraham, Isaac, and Jacob.

[[v5-9-6]]

^<<v5-9-6,6>>^ Know, then, that it is not because of your righteousness that Jehovah your God is giving you this good land to take possession of, because you are an obstinate^&#42;1^ people.

[NOTE]
====
. Lit., “stiff-necked.”
====

[[v5-9-7]]

^<<v5-9-7,7>>^ “Remember—never forget—the way you provoked Jehovah your God in the wilderness. From the day that you left the land of Egypt until your coming to this place, you have rebelled against Jehovah.

[[v5-9-8]]

^<<v5-9-8,8>>^ Even in Horʹeb you provoked Jehovah, and Jehovah was so angry with you that he was ready to annihilate you.

[[v5-9-9]]

^<<v5-9-9,9>>^ When I went up the mountain to receive the stone tablets, the tablets of the covenant that Jehovah made with you, I remained on the mountain 40 days and 40 nights, eating no food and drinking no water.

[[v5-9-10]]

^<<v5-9-10,10>>^ Then Jehovah gave me the two tablets of stone written on with God’s finger, and on them were all the words that Jehovah had spoken to you on the mountain out of the fire in the day of the assembly.^&#42;1^

[NOTE]
====
. Or “congregation.”
====

[[v5-9-11]]

^<<v5-9-11,11>>^ At the end of the 40 days and 40 nights, Jehovah gave me the two tablets of stone, the tablets of the covenant,

[[v5-9-12]]

^<<v5-9-12,12>>^ and Jehovah told me, ‘Get up, go down quickly from here, because your people whom you brought out of Egypt have acted corruptly. They have quickly turned aside from the path I commanded them to follow. They have made a metal image^&#42;1^ for themselves.’

[NOTE]
====
. Or “molten statue.”
====

[[v5-9-13]]

^<<v5-9-13,13>>^ Jehovah then said to me, ‘I have seen this people, and look! it is an obstinate^&#42;1^ people.

[NOTE]
====
. Lit., “stiff-necked.”
====

[[v5-9-14]]

^<<v5-9-14,14>>^ Let me be, and I will annihilate them and wipe out their name from under the heavens, and let me make you a nation mightier and more numerous than they are.’

[[v5-9-15]]

^<<v5-9-15,15>>^ “Then I turned and went down the mountain while the mountain was burning with fire, and the two tablets of the covenant were in both my hands.

[[v5-9-16]]

^<<v5-9-16,16>>^ Then I looked and saw that you had sinned against Jehovah your God! You had made a metal^&#42;1^ calf for yourselves. You had turned aside quickly from the path Jehovah had commanded you to follow.

[NOTE]
====
. Or “molten.”
====

[[v5-9-17]]

^<<v5-9-17,17>>^ So I took hold of the two tablets and threw them down with both my hands and shattered them before your eyes.

[[v5-9-18]]

^<<v5-9-18,18>>^ Then I prostrated myself before Jehovah, as at first, for 40 days and 40 nights. I neither ate food nor drank water, because of all the sins that you had committed by your doing what was evil in Jehovah’s eyes and offending him.

[[v5-9-19]]

^<<v5-9-19,19>>^ For I was terrified because of Jehovah’s great anger against you, in that he was ready to annihilate you. However, Jehovah listened to me that time also.

[[v5-9-20]]

^<<v5-9-20,20>>^ “Jehovah was so angry with Aaron that he was ready to annihilate him, but I made supplication for Aaron at that time also.

[[v5-9-21]]

^<<v5-9-21,21>>^ Then I took the sinful thing you made, the calf, and burned it up in the fire; I crushed it and ground it thoroughly until it was fine like dust, and I threw the dust into the stream that flows down from the mountain.

[[v5-9-22]]

^<<v5-9-22,22>>^ “Further, at Tabʹe·rah, at Masʹsah, and at Kibʹroth-hat·taʹa·vah, you also provoked Jehovah to anger.

[[v5-9-23]]

^<<v5-9-23,23>>^ When Jehovah sent you out of Kaʹdesh-barʹne·a and said, ‘Go up and take possession of the land that I will certainly give you!’ you again rebelled against the order of Jehovah your God, and you did not exercise faith in him and did not obey him.

[[v5-9-24]]

^<<v5-9-24,24>>^ You have rebelled against Jehovah ever since I have known you.

[[v5-9-25]]

^<<v5-9-25,25>>^ “So I kept prostrating myself before Jehovah 40 days and 40 nights, for I prostrated myself in this way because Jehovah said he would annihilate you.

[[v5-9-26]]

^<<v5-9-26,26>>^ I began to make supplication to Jehovah and to say, ‘O Sovereign Lord Jehovah, do not bring your people to ruin. They are your personal possession,^&#42;1^ whom you redeemed through your greatness and brought out of Egypt with a mighty hand.

[NOTE]
====
. Or “your inheritance.”
====

[[v5-9-27]]

^<<v5-9-27,27>>^ Remember your servants Abraham, Isaac, and Jacob. Do not pay attention to the stubbornness of this people, their wickedness, and their sin.

[[v5-9-28]]

^<<v5-9-28,28>>^ Otherwise the people of the land from which you brought us may say: “Jehovah was unable to bring them into the land that he promised them, and because he hated them, he brought them out to put them to death in the wilderness.”

[[v5-9-29]]

^<<v5-9-29,29>>^ For they are your people and your personal possession,^&#42;1^ whom you brought out with your great power and your outstretched arm.’

[NOTE]
====
. Or “your inheritance.”
====

'''

xref:005-deuteronomy/005-deuteronomy-008.adoc#v5-8-0[&#60; Capítulo Anterior] | <<v5-9-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-010.adoc#v5-10-0[Próximo Capítulo &#62;]