include::./index.adoc[]

[[v5-1-0]]
=== Deuteronomy, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-1-1]]

^<<v5-1-1,1>>^ These are the words that Moses spoke to all Israel in the region of the Jordan in the wilderness, on the desert plains in front of Suph, between Paʹran, Toʹphel, Laʹban, Ha·zeʹroth, and Diʹza·hab.

[[v5-1-2]]

^<<v5-1-2,2>>^ It is 11 days from Horʹeb to Kaʹdesh-barʹne·a by way of Mount Seʹir.

[[v5-1-3]]

^<<v5-1-3,3>>^ In the 40th year, in the 11th month, on the first of the month, Moses spoke to the Israelites^&#42;1^ according to all that Jehovah had instructed him to tell them.

[NOTE]
====
. Lit., “sons of Israel.”
====

[[v5-1-4]]

^<<v5-1-4,4>>^ This was after he defeated Siʹhon the king of the Amʹor·ites, who was dwelling in Heshʹbon, and Og the king of Baʹshan, who was dwelling in Ashʹta·roth, in Edʹre·i.

[[v5-1-5]]

^<<v5-1-5,5>>^ In the region of the Jordan in the land of Moʹab, Moses undertook to explain this Law, saying:

[[v5-1-6]]

^<<v5-1-6,6>>^ “Jehovah our God told us in Horʹeb, ‘You have stayed long enough in this mountainous region.

[[v5-1-7]]

^<<v5-1-7,7>>^ Turn and set out for the mountainous region of the Amʹor·ites and toward all their neighbors in the Arʹa·bah, the mountainous region, the She·pheʹlah, the Negʹeb, and the seacoast, the land of the Caʹnaan·ites, and Lebʹa·non,^&#42;1^ up to the great river, the river Eu·phraʹtes.

[NOTE]
====
. Evidently, the Lebanon mountain range.
====

[[v5-1-8]]

^<<v5-1-8,8>>^ See, I have set the land before you. Go in and take possession of the land about which Jehovah swore to your fathers, to Abraham, Isaac, and Jacob, to give it to them and their offspring^&#42;1^ after them.’

[NOTE]
====
. Lit., “seed.”
====

[[v5-1-9]]

^<<v5-1-9,9>>^ “And I told you at that time, ‘I am not able to carry you by myself.

[[v5-1-10]]

^<<v5-1-10,10>>^ Jehovah your God has multiplied you, and here you are today as numerous as the stars of the heavens.

[[v5-1-11]]

^<<v5-1-11,11>>^ May Jehovah, the God of your forefathers, multiply you a thousand times as many as you are, and may he bless you just as he has promised you.

[[v5-1-12]]

^<<v5-1-12,12>>^ How can I bear by myself the burden of you and the load of you and your quarreling?

[[v5-1-13]]

^<<v5-1-13,13>>^ Select wise, discreet, and experienced men of your tribes, and I will appoint them as heads over you.’

[[v5-1-14]]

^<<v5-1-14,14>>^ You answered me, ‘What you have told us to do is good.’

[[v5-1-15]]

^<<v5-1-15,15>>^ So I took the heads of your tribes, wise and experienced men, and appointed them as heads over you, chiefs of thousands, chiefs of hundreds, chiefs of fifties, chiefs of tens, and officers of your tribes.

[[v5-1-16]]

^<<v5-1-16,16>>^ “At that time I instructed your judges, ‘When you hear a case between your brothers, you are to judge with righteousness between a man and his brother or a foreign resident.

[[v5-1-17]]

^<<v5-1-17,17>>^ You must not be partial in judgment. You should hear the small one the same as the great one. You must not become intimidated by men, for the judgment belongs to God; and if a case is too difficult for you, you should present it to me, and I will hear it.’

[[v5-1-18]]

^<<v5-1-18,18>>^ At that time I instructed you regarding all the things that you should do.

[[v5-1-19]]

^<<v5-1-19,19>>^ “Then we departed from Horʹeb and marched through all that great and fearsome wilderness that you saw on the way to the mountainous region of the Amʹor·ites, just as Jehovah our God had commanded us, and we eventually came to Kaʹdesh-barʹne·a.

[[v5-1-20]]

^<<v5-1-20,20>>^ I then said to you, ‘You have come to the mountainous region of the Amʹor·ites, which Jehovah our God is giving to us.

[[v5-1-21]]

^<<v5-1-21,21>>^ See, Jehovah your God has given the land over to you. Go up, take possession of it, just as Jehovah, the God of your forefathers, has told you. Do not be afraid or terrified.’

[[v5-1-22]]

^<<v5-1-22,22>>^ “However, all of you approached me and said, ‘Let us send men ahead of us to search out the land for us and bring word back to us as to what route we should take and what kind of cities we will encounter.’

[[v5-1-23]]

^<<v5-1-23,23>>^ The suggestion seemed good to me, so I selected 12 of your men, one for each tribe.

[[v5-1-24]]

^<<v5-1-24,24>>^ They left and went up into the mountainous region and reached the Valley^&#42;1^ of Eshʹcol and spied it out.

[NOTE]
====
. Or “Wadi.”
====

[[v5-1-25]]

^<<v5-1-25,25>>^ They took some of the fruitage of the land and carried it back to us, and they brought word back to us, ‘The land that Jehovah our God is giving us is good.’

[[v5-1-26]]

^<<v5-1-26,26>>^ But you refused to go up, and you rebelled against the order of Jehovah your God.

[[v5-1-27]]

^<<v5-1-27,27>>^ You kept grumbling in your tents and were saying, ‘It was because Jehovah hated us that he brought us out of the land of Egypt to hand us over to the Amʹor·ites to annihilate us.

[[v5-1-28]]

^<<v5-1-28,28>>^ What kind of place are we going to? Our brothers made us lose heart^&#42;1^ by saying, “They are a people greater and taller than we are, and their cities are great and fortified to the heavens,^&#42;2^ and we saw the sons of the Anʹa·kim there.”’

[NOTE]
====
. Lit., “caused our heart to melt.”
. That is, with towering walls.
====

[[v5-1-29]]

^<<v5-1-29,29>>^ “So I said to you, ‘Do not be struck with terror or be afraid because of them.

[[v5-1-30]]

^<<v5-1-30,30>>^ Jehovah your God will go before you and will fight for you, just as he did in Egypt before your very eyes.

[[v5-1-31]]

^<<v5-1-31,31>>^ And you saw in the wilderness how Jehovah your God carried you just as a man carries his son, everywhere you went until you came to this place.’

[[v5-1-32]]

^<<v5-1-32,32>>^ But despite all of this, you did not put faith in Jehovah your God,

[[v5-1-33]]

^<<v5-1-33,33>>^ who was going ahead of you on the way, to spy out a place for you to camp. He appeared by fire at night and by a cloud in the daytime to show you the way you should walk.

[[v5-1-34]]

^<<v5-1-34,34>>^ “All the while Jehovah heard what you were saying, and he became indignant and solemnly swore,

[[v5-1-35]]

^<<v5-1-35,35>>^ ‘Not one of these men of this evil generation will see the good land that I swore to give to your fathers,

[[v5-1-36]]

^<<v5-1-36,36>>^ except Caʹleb the son of Je·phunʹneh. He will see it, and I will give the land on which he walked to him and to his sons, because he has followed Jehovah wholeheartedly.^&#42;1^

[NOTE]
====
. Lit., “fully; completely.”
====

[[v5-1-37]]

^<<v5-1-37,37>>^ (Jehovah even became angry with me because of you, and he said, “You too will not go in there.

[[v5-1-38]]

^<<v5-1-38,38>>^ Joshua the son of Nun, who stands before you, is the one who will enter into the land. Make him strong,^&#42;1^ for he will cause Israel to inherit it.”)

[NOTE]
====
. Or possibly, “God has made him strong.”
====

[[v5-1-39]]

^<<v5-1-39,39>>^ Moreover, your children who you said would become plunder and your sons who today do not know good or bad, these will enter, and I will give it to them to possess.

[[v5-1-40]]

^<<v5-1-40,40>>^ But as for you, turn back and depart for the wilderness by the way of the Red Sea.’

[[v5-1-41]]

^<<v5-1-41,41>>^ “At this you said to me, ‘We have sinned against Jehovah. We will now go up and fight, just as Jehovah our God has commanded us!’ So each of you put on his weapons of war, and you thought it would be an easy thing to go up the mountain.

[[v5-1-42]]

^<<v5-1-42,42>>^ But Jehovah said to me, ‘Tell them: “You must not go up and fight, for I will not be with you. If you do, you will be defeated by your enemies.”’

[[v5-1-43]]

^<<v5-1-43,43>>^ So I spoke to you, but you did not listen. Instead, you rebelled against Jehovah’s order and presumptuously tried to go up the mountain.

[[v5-1-44]]

^<<v5-1-44,44>>^ Then the Amʹor·ites who were dwelling in that mountain came out to meet you and chased you away like bees do, and they scattered you in Seʹir as far as Horʹmah.

[[v5-1-45]]

^<<v5-1-45,45>>^ So you returned and began to weep before Jehovah, but Jehovah did not listen to you or pay attention to you.

[[v5-1-46]]

^<<v5-1-46,46>>^ That is why you kept dwelling in Kaʹdesh for as long as you did.

'''

xref:004-numbers/004-numbers-036.adoc#v4-36-0[&#60; Capítulo Anterior] | <<v5-1-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-002.adoc#v5-2-0[Próximo Capítulo &#62;]