include::./index.adoc[]

[[v5-13-0]]
=== Deuteronomy, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-13-1]]

^<<v5-13-1,1>>^ “In case a prophet or one who foretells by dreams arises in your midst and gives you a sign or a portent,

[[v5-13-2]]

^<<v5-13-2,2>>^ and the sign or the portent about which he spoke to you comes true while he is saying, ‘Let us walk after other gods,’ gods that you have not known, ‘and let us serve them,’

[[v5-13-3]]

^<<v5-13-3,3>>^ you must not listen to the words of that prophet or that dreamer, for Jehovah your God is testing you to know whether you love Jehovah your God with all your heart and all your soul.^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v5-13-4]]

^<<v5-13-4,4>>^ After Jehovah your God you should walk, him you should fear, his commandments you should keep, to his voice you should listen; he is the one you should serve, and to him you should hold fast.

[[v5-13-5]]

^<<v5-13-5,5>>^ But that prophet or that dreamer should be put to death, because he encouraged rebellion against Jehovah your God—who brought you out of the land of Egypt and redeemed you from the house of slavery—to turn you from the way in which Jehovah your God has commanded you to walk. And you must remove what is evil from your midst.

[[v5-13-6]]

^<<v5-13-6,6>>^ “If your brother, the son of your mother, or your son or your daughter or your cherished wife or your closest companion^&#42;1^ should try to entice you in secrecy, saying, ‘Let us go and serve other gods,’ gods that neither you nor your forefathers have known,

[NOTE]
====
. Or “your companion who is like your own soul.”
====

[[v5-13-7]]

^<<v5-13-7,7>>^ from the gods of the peoples all around you, whether near you or those far away from you, from one end of the land to the other end of the land,

[[v5-13-8]]

^<<v5-13-8,8>>^ you must not give in to him or listen to him, nor should you show pity or feel compassion or protect him;

[[v5-13-9]]

^<<v5-13-9,9>>^ instead, you should kill him without fail. Your hand should be the first to come upon him to put him to death, and the hand of all the people afterward.

[[v5-13-10]]

^<<v5-13-10,10>>^ And you must stone him to death, because he has sought to turn you away from Jehovah your God, who has brought you out of the land of Egypt, out of the house of slavery.

[[v5-13-11]]

^<<v5-13-11,11>>^ Then all Israel will hear and become afraid, and they will never again do anything bad like this among you.

[[v5-13-12]]

^<<v5-13-12,12>>^ “In case you hear it said in one of your cities that Jehovah your God is giving you to occupy,

[[v5-13-13]]

^<<v5-13-13,13>>^ ‘Good-for-nothing men have gone out among you to turn away the inhabitants of their city, saying: “Let us go and serve other gods,” gods that you have not known,’

[[v5-13-14]]

^<<v5-13-14,14>>^ you should look into the matter, making a thorough investigation and inquiry; and if it is confirmed to be true that this detestable thing has been done among you,

[[v5-13-15]]

^<<v5-13-15,15>>^ you should without fail strike down the inhabitants of that city with the sword. Devote it and everything that is in it, including its livestock, to destruction by the sword.

[[v5-13-16]]

^<<v5-13-16,16>>^ You should then collect all its spoil into the middle of its public square and burn the city with fire, and its spoil will serve as a whole offering to Jehovah your God. It will become a permanent heap of ruins. It should never be rebuilt.

[[v5-13-17]]

^<<v5-13-17,17>>^ Your hand should take nothing that was set apart for destruction,^&#42;1^ so that Jehovah may turn away from his burning anger and show you mercy and compassion and multiply you, just as he has sworn to your forefathers.

[NOTE]
====
. Or “made sacred by ban.”
====

[[v5-13-18]]

^<<v5-13-18,18>>^ For you should obey^&#42;1^ Jehovah your God by keeping all his commandments that I am commanding you today, thus doing what is right in the eyes of Jehovah your God.

[NOTE]
====
. Or “listen to the voice of.”
====

'''

xref:005-deuteronomy/005-deuteronomy-012.adoc#v5-12-0[&#60; Capítulo Anterior] | <<v5-13-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-014.adoc#v5-14-0[Próximo Capítulo &#62;]