include::./index.adoc[]

[[v5-10-0]]
=== Deuteronomy, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-10-1]]

^<<v5-10-1,1>>^ “At that time Jehovah said to me, ‘Carve out for yourself two tablets of stone like the first ones, and come up to me on the mountain; also you must make for yourself an ark^&#42;1^ of wood.

[NOTE]
====
. Or “chest.”
====

[[v5-10-2]]

^<<v5-10-2,2>>^ And I will write on the tablets the words that appeared on the first tablets, which you shattered, and you should place them in the ark.’

[[v5-10-3]]

^<<v5-10-3,3>>^ So I made an ark of acacia wood and carved out two tablets of stone like the first ones and went up the mountain with the two tablets in my hand.

[[v5-10-4]]

^<<v5-10-4,4>>^ Then he wrote on the tablets the words he had written before, the Ten Commandments,^&#42;1^ which Jehovah had spoken to you on the mountain out of the fire on the day of the assembly;^&#42;2^ and Jehovah gave them to me.

[NOTE]
====
. Lit., “the Ten Words.” Also known as the Decalogue.
. Or “congregation.”
====

[[v5-10-5]]

^<<v5-10-5,5>>^ Then I turned and went down the mountain and placed the tablets in the ark that I had made, where they remain, just as Jehovah had commanded me.

[[v5-10-6]]

^<<v5-10-6,6>>^ “The Israelites then departed from Be·erʹoth Benʹe-jaʹa·kan for Mo·seʹrah. There Aaron died and was buried, and his son El·e·aʹzar began to serve as priest in his place.

[[v5-10-7]]

^<<v5-10-7,7>>^ From there they departed for Gudʹgo·dah, and from Gudʹgo·dah for Jotʹba·thah, a land flowing with streams of water.^&#42;1^

[NOTE]
====
. Or “wadis of water.”
====

[[v5-10-8]]

^<<v5-10-8,8>>^ “At that time Jehovah set apart the tribe of Leʹvi to carry the ark of Jehovah’s covenant, to stand before Jehovah in order to minister to him, and to bless in his name, as they do to this day.

[[v5-10-9]]

^<<v5-10-9,9>>^ That is why Leʹvi has not been given a share or an inheritance with his brothers. Jehovah is his inheritance, just as Jehovah your God had said to him.

[[v5-10-10]]

^<<v5-10-10,10>>^ I myself stayed on the mountain as I did the first time, 40 days and 40 nights, and Jehovah listened to me on that occasion also. Jehovah did not want to destroy you.

[[v5-10-11]]

^<<v5-10-11,11>>^ Then Jehovah said to me, ‘Go ahead of the people, and prepare to depart, so that they may go in and take possession of the land that I have sworn to their forefathers to give to them.’

[[v5-10-12]]

^<<v5-10-12,12>>^ “Now, O Israel, what is Jehovah your God asking of you? Only this: to fear Jehovah your God, to walk in all his ways, to love him, to serve Jehovah your God with all your heart and all your soul,^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v5-10-13]]

^<<v5-10-13,13>>^ and to keep the commandments and statutes of Jehovah that I am commanding you today for your own good.

[[v5-10-14]]

^<<v5-10-14,14>>^ Look, to Jehovah your God belong the heavens, even the heavens of the heavens,^&#42;1^ and the earth with all that is in it.

[NOTE]
====
. Or “the highest heavens.”
====

[[v5-10-15]]

^<<v5-10-15,15>>^ But only to your forefathers did Jehovah draw close and express his love, and he has chosen you, their offspring, out of all the peoples, as you are today.

[[v5-10-16]]

^<<v5-10-16,16>>^ You must now cleanse^&#42;1^ your hearts and stop being so stubborn.^&#42;2^

[NOTE]
====
. Lit., “circumcise the foreskin of.”
. Lit., “and do not harden your neck any longer.”
====

[[v5-10-17]]

^<<v5-10-17,17>>^ For Jehovah your God is the God of gods and the Lord of lords, the God great, mighty, and awe-inspiring, who treats none with partiality and does not accept a bribe.

[[v5-10-18]]

^<<v5-10-18,18>>^ He executes justice for the fatherless child^&#42;1^ and the widow and loves the foreign resident, giving him food and clothing.

[NOTE]
====
. Or “the orphan.”
====

[[v5-10-19]]

^<<v5-10-19,19>>^ You too must love the foreign resident, for you became foreign residents in the land of Egypt.

[[v5-10-20]]

^<<v5-10-20,20>>^ “Jehovah your God you should fear, him you should serve, to him you should cling, and by his name you should swear.

[[v5-10-21]]

^<<v5-10-21,21>>^ He is the One you are to praise. He is your God, who has done all these great and awe-inspiring things for you that your own eyes have seen.

[[v5-10-22]]

^<<v5-10-22,22>>^ With 70 people^&#42;1^ your forefathers went down into Egypt, and now Jehovah your God has made you as numerous as the stars of the heavens.

[NOTE]
====
. Or “souls.”
====

'''

xref:005-deuteronomy/005-deuteronomy-009.adoc#v5-9-0[&#60; Capítulo Anterior] | <<v5-10-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-011.adoc#v5-11-0[Próximo Capítulo &#62;]