include::./index.adoc[]

[[v5-27-0]]
=== Deuteronomy, 27
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-27-1]]

^<<v5-27-1,1>>^ Then Moses together with the elders of Israel commanded the people, saying: “Observe every commandment that I am giving you today.

[[v5-27-2]]

^<<v5-27-2,2>>^ And in the day when you will cross the Jordan into the land that Jehovah your God is giving you, set up large stones and cover them with plaster.^&#42;1^

[NOTE]
====
. Or “whitewash them with lime.”
====

[[v5-27-3]]

^<<v5-27-3,3>>^ Then write on them all the words of this Law when you have crossed over, so that you may enter into the land that Jehovah your God is giving you, a land flowing with milk and honey, just as Jehovah, the God of your forefathers, has promised you.

[[v5-27-4]]

^<<v5-27-4,4>>^ When you have crossed the Jordan, you should set up these stones on Mount Eʹbal and cover them with plaster,^&#42;1^ just as I am commanding you today.

[NOTE]
====
. Or “whitewash them with lime.”
====

[[v5-27-5]]

^<<v5-27-5,5>>^ You are also to build an altar there to Jehovah your God, an altar of stones. You should not use iron tools on them.

[[v5-27-6]]

^<<v5-27-6,6>>^ You should build the altar of Jehovah your God with whole stones and offer burnt offerings to Jehovah your God on it.

[[v5-27-7]]

^<<v5-27-7,7>>^ You are to offer communion sacrifices and eat them there, and you will rejoice before Jehovah your God.

[[v5-27-8]]

^<<v5-27-8,8>>^ And clearly write on the stones all the words of this Law.”

[[v5-27-9]]

^<<v5-27-9,9>>^ Then Moses and the Levitical priests spoke to all Israel, saying: “Keep silent and listen, O Israel. This day you have become the people of Jehovah your God.

[[v5-27-10]]

^<<v5-27-10,10>>^ You must listen to the voice of Jehovah your God and carry out his commandments and his regulations, which I am commanding you today.”

[[v5-27-11]]

^<<v5-27-11,11>>^ On that day Moses commanded the people, saying:

[[v5-27-12]]

^<<v5-27-12,12>>^ “The following tribes will stand on Mount Gerʹi·zim to bless the people when you have crossed the Jordan: Simʹe·on, Leʹvi, Judah, Isʹsa·char, Joseph, and Benjamin.

[[v5-27-13]]

^<<v5-27-13,13>>^ And the following will stand on Mount Eʹbal to pronounce the curse: Reuʹben, Gad, Ashʹer, Zebʹu·lun, Dan, and Naphʹta·li.

[[v5-27-14]]

^<<v5-27-14,14>>^ And the Levites will answer every man of Israel with a loud voice:

[[v5-27-15]]

^<<v5-27-15,15>>^ “‘Cursed is the man who makes a carved image or a metal statue,^&#42;1^ a thing detestable to Jehovah, the workmanship of the hands of a craftsman,^&#42;2^ and who has hidden it.’ (And all the people will respond, saying, ‘Amen!’^&#42;3^)

[NOTE]
====
. Or “molten statue.”
. Or “a wood-and-metal worker.”
. Or “So be it!”
====

[[v5-27-16]]

^<<v5-27-16,16>>^ “‘Cursed is the one who treats his father or his mother with contempt.’ (And all the people will say, ‘Amen!’)

[[v5-27-17]]

^<<v5-27-17,17>>^ “‘Cursed is the one who moves his neighbor’s boundary marker.’ (And all the people will say, ‘Amen!’)

[[v5-27-18]]

^<<v5-27-18,18>>^ “‘Cursed is the one who causes a blind person to lose his way on the road.’ (And all the people will say, ‘Amen!’)

[[v5-27-19]]

^<<v5-27-19,19>>^ “‘Cursed is the one who perverts the judgment of a foreign resident, a fatherless child,^&#42;1^ or a widow.’ (And all the people will say, ‘Amen!’)

[NOTE]
====
. Or “an orphan.”
====

[[v5-27-20]]

^<<v5-27-20,20>>^ “‘Cursed is the one who lies down with his father’s wife, for he has dishonored his father.’^&#42;1^ (And all the people will say, ‘Amen!’)

[NOTE]
====
. Lit., “uncovered the skirt of his father.”
====

[[v5-27-21]]

^<<v5-27-21,21>>^ “‘Cursed is the one who lies down with any animal.’ (And all the people will say, ‘Amen!’)

[[v5-27-22]]

^<<v5-27-22,22>>^ “‘Cursed is the one who lies down with his sister, the daughter of his father or the daughter of his mother.’ (And all the people will say, ‘Amen!’)

[[v5-27-23]]

^<<v5-27-23,23>>^ “‘Cursed is the one who lies down with his mother-in-law.’ (And all the people will say, ‘Amen!’)

[[v5-27-24]]

^<<v5-27-24,24>>^ “‘Cursed is the one who ambushes and kills his neighbor.’ (And all the people will say, ‘Amen!’)

[[v5-27-25]]

^<<v5-27-25,25>>^ “‘Cursed is the one who accepts a bribe to kill^&#42;1^ an innocent person.’^&#42;2^ (And all the people will say, ‘Amen!’)

[NOTE]
====
. Or “strike down.”
. Or “a soul of innocent blood.”
====

[[v5-27-26]]

^<<v5-27-26,26>>^ “‘Cursed is the one who will not uphold the words of this Law by carrying them out.’ (And all the people will say, ‘Amen!’)

'''

xref:005-deuteronomy/005-deuteronomy-026.adoc#v5-26-0[&#60; Capítulo Anterior] | <<v5-27-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-028.adoc#v5-28-0[Próximo Capítulo &#62;]