include::./index.adoc[]

[[v5-34-0]]
=== Deuteronomy, 34
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-34-1]]

^<<v5-34-1,1>>^ Then Moses went up from the desert plains of Moʹab to Mount Neʹbo, to the top of Pisʹgah, which faces Jerʹi·cho. And Jehovah showed him all the land, from Gilʹe·ad to Dan,

[[v5-34-2]]

^<<v5-34-2,2>>^ and all Naphʹta·li and the land of Eʹphra·im and Ma·nasʹseh, and all the land of Judah as far as the western sea,^&#42;1^

[NOTE]
====
. That is, the Great Sea, the Mediterranean.
====

[[v5-34-3]]

^<<v5-34-3,3>>^ and the Negʹeb and the District, the valley plain of Jerʹi·cho, the city of the palm trees, as far as Zoʹar.

[[v5-34-4]]

^<<v5-34-4,4>>^ Jehovah then said to him: “This is the land about which I have sworn to Abraham, Isaac, and Jacob, saying, ‘To your offspring^&#42;1^ I will give it.’ I have let you see it with your own eyes, but you will not cross over there.”

[NOTE]
====
. Lit., “seed.”
====

[[v5-34-5]]

^<<v5-34-5,5>>^ After that Moses the servant of Jehovah died there in the land of Moʹab just as Jehovah had said.

[[v5-34-6]]

^<<v5-34-6,6>>^ He buried him in the valley in the land of Moʹab, opposite Beth-peʹor, and nobody knows where his grave is down to this day.

[[v5-34-7]]

^<<v5-34-7,7>>^ Moses was 120 years old at his death. His eyes had not grown dim, and his strength had not departed.

[[v5-34-8]]

^<<v5-34-8,8>>^ The people of Israel wept for Moses on the desert plains of Moʹab for 30 days. Then the days of weeping and mourning for Moses were completed.

[[v5-34-9]]

^<<v5-34-9,9>>^ Joshua the son of Nun was full of the spirit of wisdom, for Moses had laid his hand on him; and the Israelites began to listen to him, and they did just as Jehovah had commanded Moses.

[[v5-34-10]]

^<<v5-34-10,10>>^ But there has never again arisen a prophet in Israel like Moses, whom Jehovah knew face-to-face.

[[v5-34-11]]

^<<v5-34-11,11>>^ He performed all the signs and the miracles that Jehovah had sent him to do in the land of Egypt to Pharʹaoh and all his servants and all his land,

[[v5-34-12]]

^<<v5-34-12,12>>^ along with the mighty hand and the awesome power that Moses displayed before the eyes of all Israel.

'''

xref:005-deuteronomy/005-deuteronomy-033.adoc#v5-33-0[&#60; Capítulo Anterior] | <<v5-34-0,Topo>> | xref:006-joshua/006-joshua-001.adoc#v6-1-0[Próximo Capítulo &#62;]