include::./index.adoc[]

[[v5-12-0]]
=== Deuteronomy, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-12-1]]

^<<v5-12-1,1>>^ “These are the regulations and the judicial decisions that you should be careful to carry out all the days that you are alive in the land that Jehovah the God of your forefathers will give you to possess.

[[v5-12-2]]

^<<v5-12-2,2>>^ You should completely destroy all the places where the nations you will dispossess have served their gods, whether on the high mountains or on the hills or under any luxuriant tree.

[[v5-12-3]]

^<<v5-12-3,3>>^ You should pull down their altars, shatter their sacred pillars, burn their sacred poles^&#42;1^ in the fire, and cut down the graven images of their gods, obliterating their very names from that place.

[NOTE]
====
. See Glossary.
====

[[v5-12-4]]

^<<v5-12-4,4>>^ “You must not worship Jehovah your God in that way.

[[v5-12-5]]

^<<v5-12-5,5>>^ Rather, seek Jehovah your God wherever he chooses to establish his name and his place of residence among all your tribes, and go there.

[[v5-12-6]]

^<<v5-12-6,6>>^ That is where you are to bring your burnt offerings, your sacrifices, your tithes,^&#42;1^ the contribution from your hand, your vow offerings, your voluntary offerings, and the firstborn of your herd and flock.

[NOTE]
====
. Or “tenth parts.”
====

[[v5-12-7]]

^<<v5-12-7,7>>^ You and your households must eat there before Jehovah your God and rejoice in all your undertakings, because Jehovah your God has blessed you.

[[v5-12-8]]

^<<v5-12-8,8>>^ “You must not do as we are doing here today, with everyone doing whatever is right in his own eyes,^&#42;1^

[NOTE]
====
. Or “what he thinks is right.”
====

[[v5-12-9]]

^<<v5-12-9,9>>^ because you have not yet come into the resting-place and the inheritance that Jehovah your God is giving you.

[[v5-12-10]]

^<<v5-12-10,10>>^ When you do cross the Jordan and dwell in the land that Jehovah your God is giving you to possess, he will certainly give you rest from all your enemies around you, and you will dwell in security.

[[v5-12-11]]

^<<v5-12-11,11>>^ You will bring all that I am commanding you to the place that Jehovah your God chooses to have his name reside—your burnt offerings, your sacrifices, your tithes, the contribution from your hand, and every vow offering that you vow to Jehovah.

[[v5-12-12]]

^<<v5-12-12,12>>^ You will rejoice before Jehovah your God, you and your sons, your daughters, your male and female slaves, and the Levite inside your cities,^&#42;1^ for he has not been given a share or an inheritance with you.

[NOTE]
====
. Lit., “gates.”
====

[[v5-12-13]]

^<<v5-12-13,13>>^ Be careful not to offer up your burnt offerings in any other place you may see.

[[v5-12-14]]

^<<v5-12-14,14>>^ You should offer your burnt offerings only in the place that Jehovah chooses in one of your tribal territories, and there you should do everything I am commanding you.

[[v5-12-15]]

^<<v5-12-15,15>>^ “But whenever you desire it,^&#42;1^ you may slaughter and eat meat, according to the blessing that Jehovah your God has given you in all your cities.^&#42;2^ The unclean person and the clean person may eat it, as you would eat a gazelle or a deer.

[NOTE]
====
. Or “in all the desire of your soul.”
. Lit., “inside all your gates.”
====

[[v5-12-16]]

^<<v5-12-16,16>>^ But you must not eat the blood; you should pour it out on the ground like water.

[[v5-12-17]]

^<<v5-12-17,17>>^ You will not be allowed to eat within your cities^&#42;1^ the tenth part of your grain, your new wine, your oil, the firstborn of your herd and flock, any of your vow offerings that you vow, your voluntary offerings, or the contribution from your hand.

[NOTE]
====
. Lit., “inside your gates.”
====

[[v5-12-18]]

^<<v5-12-18,18>>^ These you are to eat before Jehovah your God in the place Jehovah your God will choose—you and your son, your daughter, your male and female servant, and the Levite inside your cities;^&#42;1^ and you will rejoice before Jehovah your God in all your undertakings.

[NOTE]
====
. Lit., “gates.”
====

[[v5-12-19]]

^<<v5-12-19,19>>^ Be careful not to neglect the Levite as long as you live in your land.

[[v5-12-20]]

^<<v5-12-20,20>>^ “When Jehovah your God enlarges your territory, just as he has promised you, and you say, ‘I want to eat meat,’ because you desire^&#42;1^ to eat meat, you may eat meat whenever you desire it.^&#42;2^

[NOTE]
====
. Or “your soul desires.”
. Or “in all the desire of your soul.”
====

[[v5-12-21]]

^<<v5-12-21,21>>^ If the place that Jehovah your God chooses to put his name is far away from you, you should then slaughter some of your herd or some of your flock that Jehovah has given you, just as I have commanded you, and you should eat inside your cities^&#42;1^ whenever you desire it.^&#42;2^

[NOTE]
====
. Lit., “gates.”
. Or “in all the desire of your soul.”
====

[[v5-12-22]]

^<<v5-12-22,22>>^ You may eat it as you would eat the gazelle and the deer; both the unclean person and the clean person may eat it.

[[v5-12-23]]

^<<v5-12-23,23>>^ Just be firmly resolved not to eat the blood, because the blood is the life,^&#42;1^ and you must not eat the life^&#42;2^ with the flesh.

[NOTE]
====
. Or “soul.”
. Or “soul.”
====

[[v5-12-24]]

^<<v5-12-24,24>>^ You must not eat it. You should pour it out on the ground like water.

[[v5-12-25]]

^<<v5-12-25,25>>^ You must not eat it, so that it may go well with you and your children after you, because you are doing what is right in Jehovah’s eyes.

[[v5-12-26]]

^<<v5-12-26,26>>^ You should take only the holy things that are yours and your vow offerings when you come to the place that Jehovah will choose.

[[v5-12-27]]

^<<v5-12-27,27>>^ There you will offer your burnt offerings, the flesh and the blood, on the altar of Jehovah your God, and the blood of your sacrifices should be poured out against the altar of Jehovah your God, but the flesh you may eat.

[[v5-12-28]]

^<<v5-12-28,28>>^ “Be careful to obey all these words that I am commanding you, so that it may always go well with you and your sons after you, because you are doing what is good and right in the eyes of Jehovah your God.

[[v5-12-29]]

^<<v5-12-29,29>>^ “When Jehovah your God annihilates the nations that you are to dispossess, and you are living in their land,

[[v5-12-30]]

^<<v5-12-30,30>>^ be careful not to be entrapped after they have been annihilated from before you. Do not ask about their gods, saying, ‘How were these nations accustomed to serve their gods? I too will do the same.’

[[v5-12-31]]

^<<v5-12-31,31>>^ You must not do this to Jehovah your God, because they do for their gods every detestable thing that Jehovah hates, even burning their sons and their daughters in the fire to their gods.

[[v5-12-32]]

^<<v5-12-32,32>>^ Every word that I am commanding you is what you should be careful to do. You must not add to it nor take away from it.

'''

xref:005-deuteronomy/005-deuteronomy-011.adoc#v5-11-0[&#60; Capítulo Anterior] | <<v5-12-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-013.adoc#v5-13-0[Próximo Capítulo &#62;]