include::./index.adoc[]

[[v5-24-0]]
=== Deuteronomy, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-24-1]]

^<<v5-24-1,1>>^ “If a man marries a woman but she does not please him because he found something indecent about her, he must write out a certificate of divorce for her, hand it to her, and dismiss her from his house.

[[v5-24-2]]

^<<v5-24-2,2>>^ After she leaves his house, she may go and become another man’s wife.

[[v5-24-3]]

^<<v5-24-3,3>>^ If the second man hates^&#42;1^ her and writes out a certificate of divorce for her, hands it to her, and dismisses her from his house or if the second man who married her should die,

[NOTE]
====
. Or “rejects.”
====

[[v5-24-4]]

^<<v5-24-4,4>>^ her first husband who dismissed her will not be allowed to take her back again as his wife after she has been defiled, for that is something detestable to Jehovah. You must not bring sin into the land that Jehovah your God is giving you as an inheritance.

[[v5-24-5]]

^<<v5-24-5,5>>^ “When a man is newly married, he should not serve in the army or be given any other duties. He should remain exempt for one year and stay at home and bring joy to his wife.

[[v5-24-6]]

^<<v5-24-6,6>>^ “No one should seize a hand mill or its upper millstone as security for a loan,^&#42;1^ for that would be taking someone’s livelihood^&#42;2^ as security.

[NOTE]
====
. Or “as a pledge.”
. Or “taking a life; taking a soul.”
====

[[v5-24-7]]

^<<v5-24-7,7>>^ “If someone is found to have kidnapped one^&#42;1^ of his Israelite brothers and he has mistreated him and sold him, the kidnapper must die. You should remove what is bad from your midst.

[NOTE]
====
. Or “a soul.”
====

[[v5-24-8]]

^<<v5-24-8,8>>^ “When there is an outbreak of leprosy,^&#42;1^ be very careful to do according to all that the Levitical priests will instruct you. Be careful to do exactly as I commanded them.

[NOTE]
====
. The Hebrew word rendered “leprosy” is broad in meaning and can include various contagious skin diseases. It may also include certain infections found on clothing and in houses.
====

[[v5-24-9]]

^<<v5-24-9,9>>^ Remember what Jehovah your God did to Mirʹi·am on the way when you were coming out of Egypt.

[[v5-24-10]]

^<<v5-24-10,10>>^ “If you make any sort of loan to your neighbor, you must not enter into his house to seize from him what he has offered as security.

[[v5-24-11]]

^<<v5-24-11,11>>^ You should stand outside, and the man who received the loan should bring outside to you what he is giving as security.

[[v5-24-12]]

^<<v5-24-12,12>>^ And if the man is in need, you must not go to bed with what he gave as security still in your possession.

[[v5-24-13]]

^<<v5-24-13,13>>^ You should by all means return to him what he has given as security as soon as the sun sets, and he will go to bed with his garment, and he will bless you; and it will mean righteousness for you before Jehovah your God.

[[v5-24-14]]

^<<v5-24-14,14>>^ “You must not defraud a hired worker who is in need and poor, whether one of your brothers or a foreign resident in your land, within your cities.^&#42;1^

[NOTE]
====
. Lit., “gates.”
====

[[v5-24-15]]

^<<v5-24-15,15>>^ You should give him his wages that very day, before the sun sets, because he is in need and his life^&#42;1^ depends on his wages. Otherwise, he will cry out to Jehovah against you, and you will be guilty of sin.

[NOTE]
====
. Or “soul.”
====

[[v5-24-16]]

^<<v5-24-16,16>>^ “Fathers should not be put to death for what their children do, and children should not be put to death for what their fathers do. A person should be put to death only for his own sin.

[[v5-24-17]]

^<<v5-24-17,17>>^ “You must not pervert the judgment of the foreign resident or of the fatherless child,^&#42;1^ and you must not seize the garment of a widow as security for a loan.^&#42;2^

[NOTE]
====
. Or “the orphan.”
. Or “as a pledge.”
====

[[v5-24-18]]

^<<v5-24-18,18>>^ Remember that you became a slave in Egypt, and Jehovah your God redeemed you from there. That is why I am commanding you to do this.

[[v5-24-19]]

^<<v5-24-19,19>>^ “When you reap your harvest from your field and you have forgotten a sheaf in the field, do not go back to get it. It should be left for the foreign resident, the fatherless child, and the widow, so that Jehovah your God may bless you in all that you do.

[[v5-24-20]]

^<<v5-24-20,20>>^ “When you beat your olive tree, you should not repeat the procedure on its branches. What is left should remain for the foreign resident, the fatherless child, and the widow.

[[v5-24-21]]

^<<v5-24-21,21>>^ “When you gather the grapes of your vineyard, you must not return to gather the leftovers. They should be left for the foreign resident, the fatherless child, and the widow.

[[v5-24-22]]

^<<v5-24-22,22>>^ Remember that you became a slave in the land of Egypt. That is why I am commanding you to do this.

'''

xref:005-deuteronomy/005-deuteronomy-023.adoc#v5-23-0[&#60; Capítulo Anterior] | <<v5-24-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-025.adoc#v5-25-0[Próximo Capítulo &#62;]