include::./index.adoc[]

[[v5-7-0]]
=== Deuteronomy, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-7-1]]

^<<v5-7-1,1>>^ “When Jehovah your God brings you into the land you are about to enter and take possession of, he will also clear away populous nations from before you: the Hitʹtites, the Girʹga·shites, the Amʹor·ites, the Caʹnaan·ites, the Perʹiz·zites, the Hiʹvites, and the Jebʹu·sites, seven nations more populous and mightier than you are.

[[v5-7-2]]

^<<v5-7-2,2>>^ Jehovah your God will give them over to you, and you will defeat them. You should without fail devote them to destruction. You must not make any covenant with them nor show them any favor.

[[v5-7-3]]

^<<v5-7-3,3>>^ You must not form any marriage alliances^&#42;1^ with them. Do not give your daughters to their sons or take their daughters for your sons.

[NOTE]
====
. Or “not intermarry.”
====

[[v5-7-4]]

^<<v5-7-4,4>>^ For they will turn your sons away from following me to serve other gods; then Jehovah’s anger will blaze against you, and he will swiftly annihilate you.

[[v5-7-5]]

^<<v5-7-5,5>>^ “Instead, this is what you should do to them: Tear down their altars, break up their sacred pillars, cut down their sacred poles,^&#42;1^ and burn up their graven images.

[NOTE]
====
. See Glossary.
====

[[v5-7-6]]

^<<v5-7-6,6>>^ For you are a holy people to Jehovah your God, and Jehovah your God has chosen you to become his people, his special property,^&#42;1^ out of all the peoples who are on the face of the earth.

[NOTE]
====
. Or “treasured possession.”
====

[[v5-7-7]]

^<<v5-7-7,7>>^ “It was not because you were the most numerous of all the peoples that Jehovah showed affection for you and chose you, for you were the smallest of all the peoples.

[[v5-7-8]]

^<<v5-7-8,8>>^ Rather, it was because of Jehovah’s love for you and because he kept the oath that he had sworn to your forefathers that Jehovah brought you out with a mighty hand, to redeem you from the house of slavery, from the power^&#42;1^ of Pharʹaoh king of Egypt.

[NOTE]
====
. Lit., “hand.”
====

[[v5-7-9]]

^<<v5-7-9,9>>^ You well know that Jehovah your God is the true God, the faithful God, keeping his covenant and loyal love to a thousand generations of those who love him and keep his commandments.

[[v5-7-10]]

^<<v5-7-10,10>>^ But those who hate him he will repay to their face with destruction. He will not be slow to deal with those who hate him; he will repay them to their face.

[[v5-7-11]]

^<<v5-7-11,11>>^ Therefore, take care to keep the commandments and the regulations and the judicial decisions that I am commanding you today, by observing them.

[[v5-7-12]]

^<<v5-7-12,12>>^ “If you continue listening to these judicial decisions and you observe them and carry them out, Jehovah your God will keep the covenant and the loyal love about which he swore to your forefathers.

[[v5-7-13]]

^<<v5-7-13,13>>^ He will love you and bless you and multiply you. Yes, he will bless you with many children^&#42;1^ and with the produce of your soil, your grain, your new wine, your oil, the calves of your herds and the lambs of your flocks, in the land that he swore to your forefathers to give to you.

[NOTE]
====
. Lit., “bless the fruit of your womb.”
====

[[v5-7-14]]

^<<v5-7-14,14>>^ You will become the most blessed of all the peoples; no man or woman among you will be childless, nor will your livestock be without young.

[[v5-7-15]]

^<<v5-7-15,15>>^ Jehovah will take away from you all sickness, and he will not bring upon you any of the terrible diseases that you have known in Egypt. Instead, he will bring them upon all those who hate you.

[[v5-7-16]]

^<<v5-7-16,16>>^ You are to destroy^&#42;1^ all the peoples whom Jehovah your God gives over to you. You^&#42;2^ must not feel sorry for them, and you must not serve their gods, because that would be a snare to you.

[NOTE]
====
. Lit., “devour.”
. Lit., “Your eye.”
====

[[v5-7-17]]

^<<v5-7-17,17>>^ “If you should say in your heart, ‘These nations outnumber us. How can I drive them away?’

[[v5-7-18]]

^<<v5-7-18,18>>^ you must not be afraid of them. You should remind yourself of what Jehovah your God did to Pharʹaoh and all Egypt,

[[v5-7-19]]

^<<v5-7-19,19>>^ the great judgments^&#42;1^ that your eyes saw and the signs and the miracles and the mighty hand and the outstretched arm with which Jehovah your God brought you out. That is what Jehovah your God will do to all the peoples you fear.

[NOTE]
====
. Or “trials.”
====

[[v5-7-20]]

^<<v5-7-20,20>>^ Jehovah your God will send the feeling of dejection^&#42;1^ upon them until those who were left remaining and who were concealing themselves from before you perish.

[NOTE]
====
. Or possibly, “panic; terror.”
====

[[v5-7-21]]

^<<v5-7-21,21>>^ Do not be struck with terror because of them, for Jehovah your God is with you, a great and awe-inspiring God.

[[v5-7-22]]

^<<v5-7-22,22>>^ “Jehovah your God will certainly drive these nations away from before you little by little. You will not be allowed to put an end to them quickly, so that the wild animals of the field will not multiply against you.

[[v5-7-23]]

^<<v5-7-23,23>>^ Jehovah your God will give them over to you and utterly defeat them until they are annihilated.

[[v5-7-24]]

^<<v5-7-24,24>>^ He will give their kings into your hand, and you will wipe out their names from under the heavens. Nobody will stand up to you, until you have exterminated them.

[[v5-7-25]]

^<<v5-7-25,25>>^ You should burn the graven images of their gods in the fire. Do not desire the silver and the gold on them or take it for yourself, so that you are not ensnared by it, for it is something detestable to Jehovah your God.

[[v5-7-26]]

^<<v5-7-26,26>>^ You must not bring a detestable thing into your house and thereby become something devoted to destruction like it. You should utterly loathe it and absolutely detest it, because it is something devoted to destruction.

'''

xref:005-deuteronomy/005-deuteronomy-006.adoc#v5-6-0[&#60; Capítulo Anterior] | <<v5-7-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-008.adoc#v5-8-0[Próximo Capítulo &#62;]