include::./index.adoc[]

[[v5-25-0]]
=== Deuteronomy, 25
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-25-1]]

^<<v5-25-1,1>>^ “When a dispute arises between men, they may present themselves before the judges, and they will judge them and pronounce the righteous one innocent and the wicked one guilty.

[[v5-25-2]]

^<<v5-25-2,2>>^ If the wicked one deserves to be beaten, the judge will have him lie down prostrate, and he will be beaten in his presence. The number of strokes should correspond to the wickedness of his deed.

[[v5-25-3]]

^<<v5-25-3,3>>^ He may beat him with up to 40 strokes, but no more. If he would continue beating him with more strokes than this, your brother would be disgraced before your eyes.

[[v5-25-4]]

^<<v5-25-4,4>>^ “You must not muzzle a bull when it is threshing out grain.

[[v5-25-5]]

^<<v5-25-5,5>>^ “If brothers dwell together and one of them dies without having a son, the wife of the dead one should not marry someone from outside the family. Her brother-in-law should go to her, take her as his wife, and perform brother-in-law marriage with her.

[[v5-25-6]]

^<<v5-25-6,6>>^ The firstborn whom she will bear will carry on the name of his dead brother, so that his name may not be wiped out of Israel.

[[v5-25-7]]

^<<v5-25-7,7>>^ “Now if the man does not want to marry his brother’s widow, his brother’s widow should then go to the elders at the city gate and say, ‘My husband’s brother has refused to preserve his brother’s name in Israel. He has not consented to perform brother-in-law marriage with me.’

[[v5-25-8]]

^<<v5-25-8,8>>^ The elders of his city must call him and speak to him. Should he insist and say, ‘I do not want to marry her,’

[[v5-25-9]]

^<<v5-25-9,9>>^ then his brother’s widow should approach him before the elders, remove his sandal from his foot, spit in his face, and say, ‘That is what should be done to the man who will not build up his brother’s household.’

[[v5-25-10]]

^<<v5-25-10,10>>^ After that his family name^&#42;1^ in Israel will be known as ‘The house of the one who had his sandal removed.’

[NOTE]
====
. Or “the name of his household.” Lit., “his name.”
====

[[v5-25-11]]

^<<v5-25-11,11>>^ “If two men get into a fight with each other and the wife of the one intervenes to protect her husband from the one striking him and she reaches out her hand and grabs hold of him by his private parts,

[[v5-25-12]]

^<<v5-25-12,12>>^ you must amputate her hand. You^&#42;1^ should not feel sorry.

[NOTE]
====
. Lit., “Your eye.”
====

[[v5-25-13]]

^<<v5-25-13,13>>^ “You must not have in your bag two different stone weights, a large one and a small one.

[[v5-25-14]]

^<<v5-25-14,14>>^ You must not have in your house two different measuring containers,^&#42;1^ a large one and a small one.

[NOTE]
====
. Lit., “in your house an ephah and an ephah.” See App. B14.
====

[[v5-25-15]]

^<<v5-25-15,15>>^ You should keep an accurate and honest weight and an accurate and honest measure, so that you will live long in the land that Jehovah your God is giving you.

[[v5-25-16]]

^<<v5-25-16,16>>^ For every unjust person who does such things is detestable to Jehovah your God.

[[v5-25-17]]

^<<v5-25-17,17>>^ “Remember what Amʹa·lek did to you on the way as you were coming out of Egypt,

[[v5-25-18]]

^<<v5-25-18,18>>^ how he met you along the way and attacked all those straggling behind you when you were exhausted and weary. He did not fear God.

[[v5-25-19]]

^<<v5-25-19,19>>^ When Jehovah your God has given you rest from all your enemies around you in the land that Jehovah your God is giving you as an inheritance to possess, you should wipe out the mention of Amʹa·lek from under the heavens. You must not forget.

'''

xref:005-deuteronomy/005-deuteronomy-024.adoc#v5-24-0[&#60; Capítulo Anterior] | <<v5-25-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-026.adoc#v5-26-0[Próximo Capítulo &#62;]