include::./index.adoc[]

[[v5-33-0]]
=== Deuteronomy, 33
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-33-1]]

^<<v5-33-1,1>>^ Now this is the blessing that Moses the man of the true God pronounced on the Israelites before his death.

[[v5-33-2]]

^<<v5-33-2,2>>^ He said:
“Jehovah—from Siʹnai he came,
And he shone upon them from Seʹir.
He shone forth in glory from the mountainous region of Paʹran,
And with him were holy myriads,^&#42;1^
At his right hand his warriors.

[NOTE]
====
. Or “were tens of thousands of holy ones.”
====

[[v5-33-3]]

^<<v5-33-3,3>>^ He had affection for his people;
All their holy ones are in your hand.
They were sitting at your feet;
They began to listen to your words.

[[v5-33-4]]

^<<v5-33-4,4>>^ (Moses gave us a command, a law,
As a possession of the congregation of Jacob.)

[[v5-33-5]]

^<<v5-33-5,5>>^ And He became king in Jeshʹu·run,^&#42;1^
When the heads of the people gathered together,
Along with all the tribes of Israel.

[NOTE]
====
. Meaning “Upright One,” an honorary title for Israel.
====

[[v5-33-6]]

^<<v5-33-6,6>>^ Let Reuʹben live and not die off,
And may his men not become few.”

[[v5-33-7]]

^<<v5-33-7,7>>^ And he pronounced this blessing on Judah:
“Hear, O Jehovah, the voice of Judah,
And may you bring him back to his people.
His arms have defended^&#42;1^ what belongs to him,
And may you help him against his adversaries.”

[NOTE]
====
. Or “contended for.”
====

[[v5-33-8]]

^<<v5-33-8,8>>^ Of Leʹvi he said:
“Your^&#42;1^ Thumʹmim and your Uʹrim belong to the man loyal to you,
Whom you put to the test at Masʹsah.
You began to contend with him by the waters of Merʹi·bah,

[NOTE]
====
. “Your” and “you” in this verse refer to God.
====

[[v5-33-9]]

^<<v5-33-9,9>>^ The man who said to his father and his mother, ‘I have not shown regard to them.’
Even his brothers he did not acknowledge,
And he ignored his own sons.
For they kept your word,
And they observed your covenant.

[[v5-33-10]]

^<<v5-33-10,10>>^ Let them instruct Jacob in your judicial decisions
And Israel in your Law.
Let them offer up incense as a pleasant aroma for you^&#42;1^
And a whole offering on your altar.

[NOTE]
====
. Lit., “in your nose.”
====

[[v5-33-11]]

^<<v5-33-11,11>>^ Bless, O Jehovah, his strength,
And may you show pleasure in the work of his hands.
Crush the legs^&#42;1^ of those who rise up against him,
So that those who hate him may rise up no more.”

[NOTE]
====
. Or “hips.”
====

[[v5-33-12]]

^<<v5-33-12,12>>^ Of Benjamin he said:
“Let the beloved one of Jehovah reside in security by him;
While he shelters him the whole day,
He will reside between his shoulders.”

[[v5-33-13]]

^<<v5-33-13,13>>^ Of Joseph he said:
“May his land be blessed by Jehovah
With the choice things of heaven,
With dew and the waters from the springs below,

[[v5-33-14]]

^<<v5-33-14,14>>^ With choice things produced by the sun
And the choice yield each month,

[[v5-33-15]]

^<<v5-33-15,15>>^ With the choicest things from the ancient mountains^&#42;1^
And choice things of the enduring hills,

[NOTE]
====
. Or possibly, “the mountains of the east.”
====

[[v5-33-16]]

^<<v5-33-16,16>>^ With the choice things of the earth and what fills it,
And with the approval of the One residing in the thornbush.
May they come upon the head of Joseph,
On the crown of the head of the one singled out from his brothers.

[[v5-33-17]]

^<<v5-33-17,17>>^ His splendor is like that of a firstborn bull,
And his horns are the horns of a wild bull.
With them he will push^&#42;1^ peoples
All together to the ends of the earth.
They are the tens of thousands of Eʹphra·im,
And they are the thousands of Ma·nasʹseh.”

[NOTE]
====
. Or “gore.”
====

[[v5-33-18]]

^<<v5-33-18,18>>^ Of Zebʹu·lun he said:
“Rejoice, O Zebʹu·lun, in your going out,
And you, Isʹsa·char, in your tents.

[[v5-33-19]]

^<<v5-33-19,19>>^ They will call peoples to the mountain.
There they will offer the sacrifices of righteousness.
For they will draw from the abundant wealth of^&#42;1^ the seas
And the hidden hoards^&#42;2^ of the sand.”

[NOTE]
====
. Lit., “will suck the abundance of.”
. Or “treasures.”
====

[[v5-33-20]]

^<<v5-33-20,20>>^ Of Gad he said:
“Blessed is the one widening the borders of Gad.
He lies there like a lion,
Ready to tear off the arm, yes, the crown of the head.

[[v5-33-21]]

^<<v5-33-21,21>>^ He will select the first portion for himself,
For there the allotment of a lawgiver is reserved.
The heads of the people will gather together.
The righteousness of Jehovah he will execute,
And his judicial decisions with Israel.”

[[v5-33-22]]

^<<v5-33-22,22>>^ Of Dan he said:
“Dan is a lion cub.
He will leap out from Baʹshan.”

[[v5-33-23]]

^<<v5-33-23,23>>^ Of Naphʹta·li he said:
“Naphʹta·li is satisfied with the approval
And full of the blessing of Jehovah.
Take possession of the west and south.”

[[v5-33-24]]

^<<v5-33-24,24>>^ Of Ashʹer he said:
“Blessed with sons is Ashʹer.
May he be favored by his brothers,
And may he dip^&#42;1^ his feet in oil.

[NOTE]
====
. Or “bathe.”
====

[[v5-33-25]]

^<<v5-33-25,25>>^ Iron and copper are your gate locks,
And you will be secure all your days.^&#42;1^

[NOTE]
====
. Lit., “And like your days will be your strength.”
====

[[v5-33-26]]

^<<v5-33-26,26>>^ There is none like the true God of Jeshʹu·run,
Who rides through heaven to help you
And who rides upon the clouds in his majesty.

[[v5-33-27]]

^<<v5-33-27,27>>^ God is a refuge from ancient times,
His everlasting arms are beneath you.
And he will drive away the enemy from before you,
And he will say, ‘Annihilate them!’

[[v5-33-28]]

^<<v5-33-28,28>>^ Israel will reside in security,
And the fountain of Jacob will be secluded
In a land of grain and new wine,
Whose skies will drip with dew.

[[v5-33-29]]

^<<v5-33-29,29>>^ Happy you are, O Israel!
Who is there like you,
A people enjoying salvation in Jehovah,
Your protective shield
And your majestic sword?
Your enemies will cringe before you,
And you will tread on their backs.”^&#42;1^

[NOTE]
====
. Or possibly, “high places.”
====

'''

xref:005-deuteronomy/005-deuteronomy-032.adoc#v5-32-0[&#60; Capítulo Anterior] | <<v5-33-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-034.adoc#v5-34-0[Próximo Capítulo &#62;]