include::./index.adoc[]

[[v5-11-0]]
=== Deuteronomy, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-11-1]]

^<<v5-11-1,1>>^ “You must love Jehovah your God and always keep your obligation to him and his statutes, his judicial decisions, and his commandments.

[[v5-11-2]]

^<<v5-11-2,2>>^ You know that today I am addressing you, not your sons who have not known or seen the discipline of Jehovah your God, his greatness, his mighty hand and his outstretched arm.

[[v5-11-3]]

^<<v5-11-3,3>>^ They did not see his signs and his deeds that he did in Egypt to Pharʹaoh king of Egypt and to all his land;

[[v5-11-4]]

^<<v5-11-4,4>>^ or what he did to the armies of Egypt, to Pharʹaoh’s horses and war chariots, which were overwhelmed by the waters of the Red Sea when they were chasing after you, and Jehovah destroyed them once and for all.^&#42;1^

[NOTE]
====
. Or “until this day.”
====

[[v5-11-5]]

^<<v5-11-5,5>>^ They did not see what he has done for^&#42;1^ you in the wilderness until your coming to this place,

[NOTE]
====
. Or “to.”
====

[[v5-11-6]]

^<<v5-11-6,6>>^ or what he did to Daʹthan and A·biʹram, the sons of E·liʹab the son of Reuʹben, when the earth opened and swallowed them up, along with their households and their tents and every living thing that followed them, before the eyes of all Israel.

[[v5-11-7]]

^<<v5-11-7,7>>^ Your own eyes have seen all the great deeds that Jehovah did.

[[v5-11-8]]

^<<v5-11-8,8>>^ “You must keep the whole commandment that I am giving you today, so that you may grow strong and cross over into the land to take possession of it,

[[v5-11-9]]

^<<v5-11-9,9>>^ and so that you may live long in the land that Jehovah swore to give to your forefathers and their offspring,^&#42;1^ a land flowing with milk and honey.

[NOTE]
====
. Lit., “seed.”
====

[[v5-11-10]]

^<<v5-11-10,10>>^ “The land you are going to take possession of is not like the land of Egypt, out of which you came, where you used to sow your seed and irrigate it with your foot,^&#42;1^ like a garden of vegetables.

[NOTE]
====
. Or “water it with your foot,” that is, by some form of foot power, whether on a waterwheel or by forming and opening water channels.
====

[[v5-11-11]]

^<<v5-11-11,11>>^ But the land you are about to cross into and possess is a land of mountains and valley plains. It drinks the water that rains from the heavens;

[[v5-11-12]]

^<<v5-11-12,12>>^ it is a land that Jehovah your God is caring for. The eyes of Jehovah your God are constantly upon it, from the beginning of the year to the close of the year.

[[v5-11-13]]

^<<v5-11-13,13>>^ “And if you will diligently obey my commandments that I am commanding you today and love Jehovah your God and serve him with all your heart and all your soul,^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v5-11-14]]

^<<v5-11-14,14>>^ I will also give rain for your land at its appointed time, autumn rain and spring rain, and you will gather your grain and your new wine and your oil.

[[v5-11-15]]

^<<v5-11-15,15>>^ And I will provide vegetation in your fields for your livestock, and you will eat and be satisfied.

[[v5-11-16]]

^<<v5-11-16,16>>^ Be careful not to let your heart be enticed to go astray and worship other gods and bow down to them.

[[v5-11-17]]

^<<v5-11-17,17>>^ Otherwise, Jehovah’s anger will blaze against you, and he will shut up the heavens so that it will not rain and the ground will not give its produce and you will quickly perish from the good land that Jehovah is giving you.

[[v5-11-18]]

^<<v5-11-18,18>>^ “You must impress these words of mine on your heart and your soul^&#42;1^ and bind them as a reminder on your hand, and they should be like a headband on your forehead.^&#42;2^

[NOTE]
====
. See Glossary.
. Lit., “between your eyes.”
====

[[v5-11-19]]

^<<v5-11-19,19>>^ Teach them to your children, speaking about them when you sit in your house and when you walk on the road and when you lie down and when you get up.

[[v5-11-20]]

^<<v5-11-20,20>>^ Write them on the doorposts of your house and on your gates,

[[v5-11-21]]

^<<v5-11-21,21>>^ so that you and your sons may live long in the land that Jehovah swore to give to your forefathers, for as long as the heavens are over the earth.

[[v5-11-22]]

^<<v5-11-22,22>>^ “If you strictly observe this commandment that I am giving you and you carry it out, to love Jehovah your God, to walk in all his ways and to cling to him,

[[v5-11-23]]

^<<v5-11-23,23>>^ Jehovah will drive away all these nations from before you, and you will dispossess nations greater and more numerous than you are.

[[v5-11-24]]

^<<v5-11-24,24>>^ Every place you set your foot will become yours. From the wilderness up to Lebʹa·non, from the River, the river Eu·phraʹtes, to the western sea,^&#42;1^ your boundary will become.

[NOTE]
====
. That is, the Great Sea, the Mediterranean.
====

[[v5-11-25]]

^<<v5-11-25,25>>^ Nobody will stand up to you. Jehovah your God will spread the dread and the fear of you over the whole land on which you walk, just as he promised you.

[[v5-11-26]]

^<<v5-11-26,26>>^ “See, I am putting before you today a blessing and a curse:

[[v5-11-27]]

^<<v5-11-27,27>>^ the blessing if you obey the commandments of Jehovah your God that I am commanding you today,

[[v5-11-28]]

^<<v5-11-28,28>>^ and the curse if you do not obey the commandments of Jehovah your God and you turn aside from the way I am commanding you to follow today and you follow gods that you have not known.

[[v5-11-29]]

^<<v5-11-29,29>>^ “When Jehovah your God brings you into the land you are to possess, you must pronounce^&#42;1^ the blessing on Mount Gerʹi·zim and the curse on Mount Eʹbal.

[NOTE]
====
. Or “give.”
====

[[v5-11-30]]

^<<v5-11-30,30>>^ Are they not on the other side of the Jordan toward the west,^&#42;1^ in the land of the Caʹnaan·ites who live in the Arʹa·bah, opposite Gilʹgal, beside the big trees of Moʹreh?

[NOTE]
====
. Or “sunset.”
====

[[v5-11-31]]

^<<v5-11-31,31>>^ For you are crossing the Jordan to enter and take possession of the land that Jehovah your God is giving you. When you take possession of it and live in it,

[[v5-11-32]]

^<<v5-11-32,32>>^ you must be careful to carry out all the regulations and the judicial decisions that I am putting before you today.

'''

xref:005-deuteronomy/005-deuteronomy-010.adoc#v5-10-0[&#60; Capítulo Anterior] | <<v5-11-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-012.adoc#v5-12-0[Próximo Capítulo &#62;]