include::./index.adoc[]

[[v5-18-0]]
=== Deuteronomy, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-18-1]]

^<<v5-18-1,1>>^ “The Levitical priests, and indeed the entire tribe of Leʹvi, will not be given a share or an inheritance with Israel. They will eat of the offerings made by fire to Jehovah, which are his inheritance.

[[v5-18-2]]

^<<v5-18-2,2>>^ So they should have no inheritance in the midst of their brothers. Jehovah is their inheritance, just as he has spoken to them.

[[v5-18-3]]

^<<v5-18-3,3>>^ “Now this will be the due right of the priests from the people: Whoever makes a sacrifice, whether a bull or a sheep, is to give the shoulder, the jaws, and the stomach to the priest.

[[v5-18-4]]

^<<v5-18-4,4>>^ The firstfruits of your grain, your new wine, your oil, and the first wool that is shorn from your flock you should give him.

[[v5-18-5]]

^<<v5-18-5,5>>^ Jehovah your God has chosen him and his sons from all your tribes to minister in the name of Jehovah always.

[[v5-18-6]]

^<<v5-18-6,6>>^ “But if a Levite leaves one of your cities in Israel where he was living and he^&#42;1^ desires to go to the place that Jehovah chooses,^&#42;2^

[NOTE]
====
. Or “his soul.”
. That is, the place Jehovah selects as the center for worship.
====

[[v5-18-7]]

^<<v5-18-7,7>>^ he may minister there in the name of Jehovah his God the same as all his brothers, the Levites, who are stationed there before Jehovah.

[[v5-18-8]]

^<<v5-18-8,8>>^ He will receive an equal share of food with them, in addition to what he receives from selling his ancestral possessions.

[[v5-18-9]]

^<<v5-18-9,9>>^ “When you have entered into the land that Jehovah your God is giving you, you must not learn to imitate the detestable practices of those nations.

[[v5-18-10]]

^<<v5-18-10,10>>^ There should not be found in you anyone who makes his son or his daughter pass through the fire, anyone who employs divination, anyone practicing magic, anyone who looks for omens, a sorcerer,

[[v5-18-11]]

^<<v5-18-11,11>>^ anyone binding others with a spell, anyone who consults a spirit medium or a fortune-teller, or anyone who inquires of the dead.

[[v5-18-12]]

^<<v5-18-12,12>>^ For whoever does these things is detestable to Jehovah, and on account of these detestable practices Jehovah your God is driving them away from before you.

[[v5-18-13]]

^<<v5-18-13,13>>^ You should prove yourself blameless before Jehovah your God.

[[v5-18-14]]

^<<v5-18-14,14>>^ “For these nations that you are dispossessing used to listen to those practicing magic and divination, but Jehovah your God has not allowed you to do anything like this.

[[v5-18-15]]

^<<v5-18-15,15>>^ Jehovah your God will raise up for you from among your brothers a prophet like me. You must listen to him.

[[v5-18-16]]

^<<v5-18-16,16>>^ This is in response to what you asked of Jehovah your God in Horʹeb on the day of the assembly^&#42;1^ when you said, ‘Do not let me hear the voice of Jehovah my God or see this great fire anymore, so that I do not die.’

[NOTE]
====
. Or “congregation.”
====

[[v5-18-17]]

^<<v5-18-17,17>>^ Then Jehovah said to me, ‘What they have said is good.

[[v5-18-18]]

^<<v5-18-18,18>>^ I will raise up for them from the midst of their brothers a prophet like you, and I will put my words in his mouth, and he will speak to them all that I command him.

[[v5-18-19]]

^<<v5-18-19,19>>^ Indeed, I will require an account from the man who will not listen to my words that he will speak in my name.

[[v5-18-20]]

^<<v5-18-20,20>>^ “‘If any prophet presumptuously speaks a word in my name that I did not command him to speak or speaks in the name of other gods, that prophet must die.

[[v5-18-21]]

^<<v5-18-21,21>>^ However, you may say in your heart: “How will we know that Jehovah has not spoken the word?”

[[v5-18-22]]

^<<v5-18-22,22>>^ When the prophet speaks in the name of Jehovah and the word is not fulfilled or does not come true, then Jehovah did not speak that word. The prophet spoke it presumptuously. You should not fear him.’

'''

xref:005-deuteronomy/005-deuteronomy-017.adoc#v5-17-0[&#60; Capítulo Anterior] | <<v5-18-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-019.adoc#v5-19-0[Próximo Capítulo &#62;]