include::./index.adoc[]

[[v5-30-0]]
=== Deuteronomy, 30
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-30-1]]

^<<v5-30-1,1>>^ “When all these words come upon you, the blessing and the curse that I have put before you, and you call them to mind^&#42;1^ in all the nations where Jehovah your God has dispersed you,

[NOTE]
====
. Lit., “and you bring them back to your heart.”
====

[[v5-30-2]]

^<<v5-30-2,2>>^ and you return to Jehovah your God and listen to his voice according to all that I am commanding you today, you and your sons, with all your heart and all your soul,^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v5-30-3]]

^<<v5-30-3,3>>^ Jehovah your God will then bring back your captives and show you mercy and regather you from all the peoples where Jehovah your God has scattered you.

[[v5-30-4]]

^<<v5-30-4,4>>^ Even if your people are dispersed to the extremity of the heavens, from there Jehovah your God will gather you and bring you back.

[[v5-30-5]]

^<<v5-30-5,5>>^ Jehovah your God will bring you into the land your fathers took possession of, and you will possess it; and he will make you prosper and will multiply you more than your fathers.

[[v5-30-6]]

^<<v5-30-6,6>>^ Jehovah your God will cleanse^&#42;1^ your heart and the heart of your offspring, so that you will love Jehovah your God with all your heart and all your soul^&#42;2^ and you may live.

[NOTE]
====
. Lit., “circumcise.”
. See Glossary.
====

[[v5-30-7]]

^<<v5-30-7,7>>^ Then Jehovah your God will bring all these curses upon your enemies, who hated and persecuted you.

[[v5-30-8]]

^<<v5-30-8,8>>^ “You will then return and listen to the voice of Jehovah and observe all his commandments that I am commanding you today.

[[v5-30-9]]

^<<v5-30-9,9>>^ Jehovah your God will make you abundantly prosperous in all the work of your hands, multiplying your children and your livestock and the produce of your ground, for Jehovah will again delight to make you prosper, just as he delighted in your forefathers.

[[v5-30-10]]

^<<v5-30-10,10>>^ For then you will listen to the voice of Jehovah your God and keep his commandments and statutes written in this book of the Law, and you will return to Jehovah your God with all your heart and all your soul.^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v5-30-11]]

^<<v5-30-11,11>>^ “Now this commandment that I am commanding you today is not too difficult for you, nor is it beyond your reach.^&#42;1^

[NOTE]
====
. Lit., “nor is it far away.”
====

[[v5-30-12]]

^<<v5-30-12,12>>^ It is not in the heavens, so that you have to say, ‘Who will ascend to the heavens and get it for us, so that we may hear it and observe it?’

[[v5-30-13]]

^<<v5-30-13,13>>^ Nor is it on the other side of the sea, so that you have to say, ‘Who will cross over to the other side of the sea and get it for us, so that we may hear it and observe it?’

[[v5-30-14]]

^<<v5-30-14,14>>^ For the word is very near you, in your own mouth and in your own heart, so that you may do it.

[[v5-30-15]]

^<<v5-30-15,15>>^ “See, I do put before you today life and good, and death and bad.

[[v5-30-16]]

^<<v5-30-16,16>>^ If you listen to the commandments of Jehovah your God that I am commanding you today, by loving Jehovah your God, by walking in his ways, and by keeping his commandments and his statutes and his judicial decisions, then you will live and multiply, and Jehovah your God will bless you in the land you are going to possess.

[[v5-30-17]]

^<<v5-30-17,17>>^ “But if your heart turns away and you do not listen and you are enticed and bow down to other gods and serve them,

[[v5-30-18]]

^<<v5-30-18,18>>^ I tell you today that you will certainly perish. You will not live long in the land you are crossing the Jordan to possess.

[[v5-30-19]]

^<<v5-30-19,19>>^ I take the heavens and the earth as witnesses against you today that I have put life and death before you, the blessing and the curse; and you must choose life so that you may live, you and your descendants,

[[v5-30-20]]

^<<v5-30-20,20>>^ by loving Jehovah your God, by listening to his voice, and by sticking to him, for he is your life and by him you will endure a long time in the land that Jehovah swore to give to your forefathers, Abraham, Isaac, and Jacob.”

'''

xref:005-deuteronomy/005-deuteronomy-029.adoc#v5-29-0[&#60; Capítulo Anterior] | <<v5-30-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-031.adoc#v5-31-0[Próximo Capítulo &#62;]