include::./index.adoc[]

[[v5-31-0]]
=== Deuteronomy, 31
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-31-1]]

^<<v5-31-1,1>>^ Then Moses went out and spoke these words to all Israel,

[[v5-31-2]]

^<<v5-31-2,2>>^ saying to them: “I am 120 years old today. I can no longer lead you,^&#42;1^ for Jehovah has said to me, ‘You will not cross this Jordan.’

[NOTE]
====
. Lit., “go out and come in.”
====

[[v5-31-3]]

^<<v5-31-3,3>>^ Jehovah your God is the one crossing before you, and he himself will annihilate these nations before you, and you will drive them away. Joshua is the one who will lead you across, just as Jehovah has spoken.

[[v5-31-4]]

^<<v5-31-4,4>>^ Jehovah will do to them just as he did to Siʹhon and to Og, the kings of the Amʹor·ites, and to their land when he annihilated them.

[[v5-31-5]]

^<<v5-31-5,5>>^ Jehovah will defeat them for you, and you are to do to them according to the whole commandment that I have given you.

[[v5-31-6]]

^<<v5-31-6,6>>^ Be courageous and strong. Do not be afraid or struck with terror before them, for Jehovah your God is the one marching with you. He will neither desert you nor abandon you.”

[[v5-31-7]]

^<<v5-31-7,7>>^ Moses then called Joshua and said to him before the eyes of all Israel: “Be courageous and strong, for you are the one who will bring this people into the land that Jehovah swore to their forefathers to give to them, and you will give it to them as an inheritance.

[[v5-31-8]]

^<<v5-31-8,8>>^ Jehovah is the one marching before you, and he will continue with you. He will neither desert you nor abandon you. Do not be afraid or be terrified.”

[[v5-31-9]]

^<<v5-31-9,9>>^ Then Moses wrote this Law and gave it to the priests, the Levites, who carry the ark of Jehovah’s covenant, and to all the elders of Israel.

[[v5-31-10]]

^<<v5-31-10,10>>^ Moses commanded them, saying: “At the end of every seven years, at the appointed time in the year of the release, during the Festival of Booths,^&#42;1^

[NOTE]
====
. Or “Temporary Shelters.”
====

[[v5-31-11]]

^<<v5-31-11,11>>^ when all Israel appears before the presence of Jehovah your God in the place that he chooses, you should read this Law for all Israel to hear it.

[[v5-31-12]]

^<<v5-31-12,12>>^ Gather the people together, the men, the women, the children,^&#42;1^ and your foreign resident who is within your cities,^&#42;2^ in order that they may listen and learn about and fear Jehovah your God and take care to carry out all the words of this Law.

[NOTE]
====
. Lit., “little ones.”
. Lit., “gates.”
====

[[v5-31-13]]

^<<v5-31-13,13>>^ Then their sons who have not known this Law will listen and learn to fear Jehovah your God all the days that you live in the land that you are crossing the Jordan to possess.”

[[v5-31-14]]

^<<v5-31-14,14>>^ Jehovah then said to Moses: “Look! The time has drawn near for you to die. Call Joshua, and present yourselves^&#42;1^ at the tent of meeting, so that I may commission him.” So Moses and Joshua went and presented themselves at the tent of meeting.

[NOTE]
====
. Or “take your places.”
====

[[v5-31-15]]

^<<v5-31-15,15>>^ Then Jehovah appeared at the tent in the pillar of cloud, and the pillar of cloud stood by the entrance of the tent.

[[v5-31-16]]

^<<v5-31-16,16>>^ Jehovah now said to Moses: “Look! You are about to die,^&#42;1^ and this people will begin to commit spiritual prostitution with the foreign gods that are around them in the land to which they are going. They will forsake me and break my covenant that I have made with them.

[NOTE]
====
. Lit., “lie down with your fathers.”
====

[[v5-31-17]]

^<<v5-31-17,17>>^ At that time my anger will blaze against them, and I will forsake them and hide my face from them until they are devoured. Then after many calamities and distresses have come upon them, they will say, ‘Is it not because our God is not in our midst that these calamities have come upon us?’

[[v5-31-18]]

^<<v5-31-18,18>>^ But I will keep my face hidden in that day because of all the wickedness that they have done in turning to other gods.

[[v5-31-19]]

^<<v5-31-19,19>>^ “Now write down this song for yourselves and teach it to the Israelites. Have them learn it^&#42;1^ in order that this song may serve as my witness against the people of Israel.

[NOTE]
====
. Lit., “Place it in their mouths.”
====

[[v5-31-20]]

^<<v5-31-20,20>>^ When I bring them to the land that I have sworn about to their forefathers—one flowing with milk and honey—and they eat their fill and prosper,^&#42;1^ they will turn to other gods and serve them and treat me with disrespect and break my covenant.

[NOTE]
====
. Lit., “grow fat.”
====

[[v5-31-21]]

^<<v5-31-21,21>>^ When many calamities and distresses come upon them, this song will serve as a witness to them (for their descendants should not forget it), for I already know the inclination that they have developed even before I bring them into the land about which I have sworn.”

[[v5-31-22]]

^<<v5-31-22,22>>^ So Moses wrote down this song in that day and taught it to the Israelites.

[[v5-31-23]]

^<<v5-31-23,23>>^ He^&#42;1^ then commissioned Joshua the son of Nun and said: “Be courageous and strong, for you are the one who will bring the Israelites into the land about which I have sworn to them, and I will continue with you.”

[NOTE]
====
. Evidently God.
====

[[v5-31-24]]

^<<v5-31-24,24>>^ As soon as Moses had completed writing the words of this Law in a book in their entirety,

[[v5-31-25]]

^<<v5-31-25,25>>^ Moses commanded the Levites who carry the ark of Jehovah’s covenant, saying:

[[v5-31-26]]

^<<v5-31-26,26>>^ “Take this book of the Law and place it at the side of the ark of the covenant of Jehovah your God, and it will serve as a witness there against you.

[[v5-31-27]]

^<<v5-31-27,27>>^ For I myself well know your rebelliousness and your stubbornness.^&#42;1^ If you have been so rebellious against Jehovah while I am still alive with you, then how much more so will you be after my death!

[NOTE]
====
. Lit., “stiff neck.”
====

[[v5-31-28]]

^<<v5-31-28,28>>^ Gather together to me all the elders of your tribes and your officers, and let me speak these words in their hearing, and let me take the heavens and the earth as witnesses against them.

[[v5-31-29]]

^<<v5-31-29,29>>^ For I well know that after my death you will surely act wickedly and turn aside from the way about which I have commanded you. And calamity will certainly befall you at the close of the days, because you will do what is bad in the eyes of Jehovah and you will offend him by the works of your hands.”

[[v5-31-30]]

^<<v5-31-30,30>>^ Then in the hearing of the entire congregation of Israel, Moses recited the words of this song from beginning to end:

'''

xref:005-deuteronomy/005-deuteronomy-030.adoc#v5-30-0[&#60; Capítulo Anterior] | <<v5-31-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-032.adoc#v5-32-0[Próximo Capítulo &#62;]