include::./index.adoc[]

[[v5-29-0]]
=== Deuteronomy, 29
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-29-1]]

^<<v5-29-1,1>>^ These are the words of the covenant that Jehovah commanded Moses to make with the people of Israel in the land of Moʹab, in addition to the covenant that he made with them at Horʹeb.

[[v5-29-2]]

^<<v5-29-2,2>>^ Moses then called together all Israel and said to them: “You have seen all that Jehovah did before your eyes in the land of Egypt to Pharʹaoh and all his servants and all his land,

[[v5-29-3]]

^<<v5-29-3,3>>^ the great judgments^&#42;1^ that your eyes saw, those great signs and miracles.

[NOTE]
====
. Or “trials.”
====

[[v5-29-4]]

^<<v5-29-4,4>>^ But Jehovah has not given you a heart to understand and eyes to see and ears to hear, down to this day.

[[v5-29-5]]

^<<v5-29-5,5>>^ ‘While I kept guiding you for 40 years in the wilderness, your garments did not wear out on you and your sandals did not wear out on your feet.

[[v5-29-6]]

^<<v5-29-6,6>>^ You did not eat bread, and you did not drink wine or anything alcoholic, so that you would know that I am Jehovah your God.’

[[v5-29-7]]

^<<v5-29-7,7>>^ You eventually came to this place, and Siʹhon the king of Heshʹbon and Og the king of Baʹshan came out to meet us in battle, but we defeated them.

[[v5-29-8]]

^<<v5-29-8,8>>^ After that we took their land and gave it as an inheritance to the Reuʹben·ites, the Gadʹites, and the half tribe of the Ma·nasʹsites.

[[v5-29-9]]

^<<v5-29-9,9>>^ Therefore, observe the words of this covenant and obey them, so that everything you do will turn out well.

[[v5-29-10]]

^<<v5-29-10,10>>^ “All of you are stationed today before Jehovah your God, the heads of your tribes, your elders, your officers, every man of Israel,

[[v5-29-11]]

^<<v5-29-11,11>>^ your children, your wives, and your foreign resident who is in the midst of your camp, from the one gathering your wood to the one drawing your water.

[[v5-29-12]]

^<<v5-29-12,12>>^ You are here in order to enter into the covenant of Jehovah your God and his oath, which Jehovah your God is making with you today

[[v5-29-13]]

^<<v5-29-13,13>>^ in order that he may establish you today as his people and that he may be your God, just as he has promised you and just as he swore to your forefathers, Abraham, Isaac, and Jacob.

[[v5-29-14]]

^<<v5-29-14,14>>^ “Now it is not with you alone that I am making this covenant and this oath,

[[v5-29-15]]

^<<v5-29-15,15>>^ but it is with those standing here with us today before Jehovah our God and with those who are not here with us today.

[[v5-29-16]]

^<<v5-29-16,16>>^ (For you well know how we lived in the land of Egypt and how we passed through the midst of various nations on our journey.

[[v5-29-17]]

^<<v5-29-17,17>>^ And you used to see their detestable things and their disgusting idols^&#42;1^ of wood and stone, silver and gold, that were among them.)

[NOTE]
====
. The Hebrew term may be related to a word for “dung” and is used as an expression of contempt.
====

[[v5-29-18]]

^<<v5-29-18,18>>^ Beware that there may not be a man or a woman, a family or a tribe among you today whose heart turns away from Jehovah our God to go serve the gods of those nations, that there may not be a root among you producing poisonous fruit and wormwood.

[[v5-29-19]]

^<<v5-29-19,19>>^ “But if someone hears the words of this oath and boasts in his heart, saying, ‘I will have peace, though I insist on walking in the ways of my own heart,’ to the ruin of everything^&#42;1^ in his path,

[NOTE]
====
. Lit., “the well-watered one along with the dry one.”
====

[[v5-29-20]]

^<<v5-29-20,20>>^ Jehovah will not be willing to forgive him. Instead, Jehovah’s great anger will blaze against that man, and the entire curse written in this book will certainly come upon him, and Jehovah will indeed wipe out his name from under the heavens.

[[v5-29-21]]

^<<v5-29-21,21>>^ Jehovah will then single him out from all the tribes of Israel for calamity in accord with the entire curse of the covenant that is written in this book of the Law.

[[v5-29-22]]

^<<v5-29-22,22>>^ “When the future generation of your sons and the foreigner from a distant land see the plagues of the land, the maladies that Jehovah has brought upon it—

[[v5-29-23]]

^<<v5-29-23,23>>^ sulfur and salt and burning, so that its whole land will not be sown or sprout, nor will any vegetation spring up in it, like the overthrow of Sodʹom and Go·morʹrah, Adʹmah and Ze·boiʹim, which Jehovah overthrew in his anger and in his wrath—

[[v5-29-24]]

^<<v5-29-24,24>>^ they and all the nations will say, ‘Why did Jehovah do this to this land? What caused this great, burning anger?’

[[v5-29-25]]

^<<v5-29-25,25>>^ Then they will say, ‘It was because they abandoned the covenant of Jehovah, the God of their forefathers, which he made with them when he brought them out of the land of Egypt.

[[v5-29-26]]

^<<v5-29-26,26>>^ But they went and served other gods and bowed down to them, gods that they had not known and that he had not permitted them to worship.^&#42;1^

[NOTE]
====
. Lit., “not apportioned to them.”
====

[[v5-29-27]]

^<<v5-29-27,27>>^ Then Jehovah’s burning anger came against that land by bringing upon it the entire curse written in this book.

[[v5-29-28]]

^<<v5-29-28,28>>^ Therefore, Jehovah uprooted them from their soil in his anger and fury and great indignation and deported them to another land, where they are today.’

[[v5-29-29]]

^<<v5-29-29,29>>^ “The things concealed belong to Jehovah our God, but the things revealed belong to us and to our descendants forever, so that we may carry out all the words of this Law.

'''

xref:005-deuteronomy/005-deuteronomy-028.adoc#v5-28-0[&#60; Capítulo Anterior] | <<v5-29-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-030.adoc#v5-30-0[Próximo Capítulo &#62;]