include::./index.adoc[]

[[v5-3-0]]
=== Deuteronomy, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-3-1]]

^<<v5-3-1,1>>^ “Then we turned and went up by the Way of Baʹshan. And Og, the king of Baʹshan, came out with all his people to meet us in battle at Edʹre·i.

[[v5-3-2]]

^<<v5-3-2,2>>^ So Jehovah said to me, ‘Do not be afraid of him, for I will give him and all his people and his land into your hand, and you will do to him just as you did to Siʹhon the king of the Amʹor·ites, who lived in Heshʹbon.’

[[v5-3-3]]

^<<v5-3-3,3>>^ So Jehovah our God also gave King Og of Baʹshan and all his people into our hand, and we kept striking him down until none of his people survived.

[[v5-3-4]]

^<<v5-3-4,4>>^ We then captured all his cities. There was no town that we did not take from them—60 cities, all the region of Arʹgob, the kingdom of Og in Baʹshan.

[[v5-3-5]]

^<<v5-3-5,5>>^ All these cities were fortified with high walls, gates, and bars, along with a great number of rural towns.

[[v5-3-6]]

^<<v5-3-6,6>>^ However, we devoted them to destruction, just as we had done to King Siʹhon of Heshʹbon, in devoting every city to destruction, including men, women, and children.

[[v5-3-7]]

^<<v5-3-7,7>>^ And we took all the livestock and the spoil of the cities for ourselves.

[[v5-3-8]]

^<<v5-3-8,8>>^ “At that time we seized the land of the two Amʹor·ite kings who were in the region of the Jordan, from the Arʹnon Valley^&#42;1^ as far as Mount Herʹmon

[NOTE]
====
. Or “Wadi Arnon.”
====

[[v5-3-9]]

^<<v5-3-9,9>>^ (the mountain that the Si·doʹni·ans used to call Sirʹi·on and the Amʹor·ites used to call Seʹnir),

[[v5-3-10]]

^<<v5-3-10,10>>^ all the cities of the tableland,^&#42;1^ all Gilʹe·ad, and all Baʹshan as far as Salʹe·cah and Edʹre·i, the cities of the kingdom that belonged to Og in Baʹshan.

[NOTE]
====
. Or “plateau.”
====

[[v5-3-11]]

^<<v5-3-11,11>>^ For King Og of Baʹshan was the last remaining one of the Rephʹa·im. His bier^&#42;1^ was made of iron,^&#42;2^ and it is still in Rabʹbah of the Amʹmon·ites. It is nine cubits^&#42;3^ long and four cubits wide, by the standard cubit.

[NOTE]
====
. Or “sarcophagus; coffin.”
. Or possibly, “black basalt.”
. A cubit equaled 44.5 cm (17.5 in.). See App. B14.
====

[[v5-3-12]]

^<<v5-3-12,12>>^ At that time we took possession of this land: from A·roʹer, which is by the Arʹnon Valley,^&#42;1^ and half of the mountainous region of Gilʹe·ad, and I have given its cities to the Reuʹben·ites and the Gadʹites.

[NOTE]
====
. Or “Wadi Arnon.”
====

[[v5-3-13]]

^<<v5-3-13,13>>^ And the rest of Gilʹe·ad and all Baʹshan of the kingdom of Og I have given to the half tribe of Ma·nasʹseh. All the region of Arʹgob, which belongs to Baʹshan, was known as the land of the Rephʹa·im.

[[v5-3-14]]

^<<v5-3-14,14>>^ “Jaʹir the son of Ma·nasʹseh took all the region of Arʹgob as far as the boundary of the Geshʹur·ites and the Ma·acʹa·thites and named those villages of Baʹshan after himself, Havʹvoth-jaʹir,^&#42;1^ to this day.

[NOTE]
====
. Meaning “Tent Villages of Jair.”
====

[[v5-3-15]]

^<<v5-3-15,15>>^ And I have given Gilʹe·ad to Maʹchir.

[[v5-3-16]]

^<<v5-3-16,16>>^ And to the Reuʹben·ites and the Gadʹites, I have given from Gilʹe·ad to the Arʹnon Valley,^&#42;1^ with the middle of the valley as a boundary, and as far as Jabʹbok, the valley that is the boundary of the Amʹmon·ites,

[NOTE]
====
. Or “Wadi Arnon.”
====

[[v5-3-17]]

^<<v5-3-17,17>>^ and the Arʹa·bah and the Jordan and the border, from Chinʹne·reth to the Sea of the Arʹa·bah, the Salt Sea,^&#42;1^ at the base of the slopes of Pisʹgah toward the east.

[NOTE]
====
. That is, the Dead Sea.
====

[[v5-3-18]]

^<<v5-3-18,18>>^ “I then gave you this command: ‘Jehovah your God has given you this land to take possession of it. All your valiant men will take up arms and cross over before your brothers, the Israelites.

[[v5-3-19]]

^<<v5-3-19,19>>^ Only your wives, your children, and your livestock (I well know that you have a great deal of livestock) will continue dwelling in the cities that I have given you,

[[v5-3-20]]

^<<v5-3-20,20>>^ until Jehovah gives your brothers rest, as he does for you, and they also have taken possession of the land that Jehovah your God will give them across the Jordan. Then you will come back, each one to his possession that I have given you.’

[[v5-3-21]]

^<<v5-3-21,21>>^ “At that time I gave this command to Joshua: ‘You have seen with your own eyes what Jehovah your God has done to these two kings. Jehovah will do the same thing to all the kingdoms into which you will cross over.

[[v5-3-22]]

^<<v5-3-22,22>>^ You must not be afraid of them, for Jehovah your God is the one fighting for you.’

[[v5-3-23]]

^<<v5-3-23,23>>^ “At that time I pleaded with Jehovah, saying,

[[v5-3-24]]

^<<v5-3-24,24>>^ ‘O Sovereign Lord Jehovah, you have begun to show your servant your greatness and your mighty arm, for what god in the heavens or on the earth performs such mighty deeds as you?

[[v5-3-25]]

^<<v5-3-25,25>>^ Please let me pass over and see the good land that is across the Jordan, this good mountainous region and Lebʹa·non.’

[[v5-3-26]]

^<<v5-3-26,26>>^ But Jehovah was still furious with me because of you, and he would not listen to me. Rather, Jehovah said to me, ‘Enough from you! Never speak to me again about this matter.

[[v5-3-27]]

^<<v5-3-27,27>>^ Go up to the top of Pisʹgah, and look to the west and north and south and east and view the land with your eyes, for you will not cross over this Jordan.

[[v5-3-28]]

^<<v5-3-28,28>>^ Commission Joshua and encourage him and strengthen him, because he is the one who will cross over before this people and he is the one who will cause them to inherit the land that you will see.’

[[v5-3-29]]

^<<v5-3-29,29>>^ All this happened while we were dwelling in the valley in front of Beth-peʹor.

'''

xref:005-deuteronomy/005-deuteronomy-002.adoc#v5-2-0[&#60; Capítulo Anterior] | <<v5-3-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-004.adoc#v5-4-0[Próximo Capítulo &#62;]