include::./index.adoc[]

[[v5-26-0]]
=== Deuteronomy, 26
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-26-1]]

^<<v5-26-1,1>>^ “When eventually you enter into the land that Jehovah your God is giving you as an inheritance and you have taken possession of it and are dwelling in it,

[[v5-26-2]]

^<<v5-26-2,2>>^ you are to take some of the firstfruits of all the produce^&#42;1^ of the ground, which you will gather from your land that Jehovah your God is giving you, and put them in a basket and go to the place that Jehovah your God chooses to have his name reside.

[NOTE]
====
. Lit., “fruit.”
====

[[v5-26-3]]

^<<v5-26-3,3>>^ You must go to the priest who will be serving in those days and say to him, ‘Today I am reporting to Jehovah your God that I have come into the land that Jehovah swore to our forefathers to give to us.’

[[v5-26-4]]

^<<v5-26-4,4>>^ “The priest will then take the basket out of your hand and deposit it before the altar of Jehovah your God.

[[v5-26-5]]

^<<v5-26-5,5>>^ Then you are to declare before Jehovah your God, ‘My father was a wandering^&#42;1^ A·ra·maeʹan, and he went down to Egypt and resided there as a foreigner, with few in his household. But there he became a great nation, mighty and numerous.

[NOTE]
====
. Or possibly, “perishing.”
====

[[v5-26-6]]

^<<v5-26-6,6>>^ And the Egyptians mistreated and oppressed us and imposed harsh slavery on us.

[[v5-26-7]]

^<<v5-26-7,7>>^ So we began to cry out to Jehovah, the God of our forefathers, and Jehovah heard our voice and looked upon our affliction and our trouble and our oppression.

[[v5-26-8]]

^<<v5-26-8,8>>^ Finally Jehovah brought us out of Egypt with a mighty hand and an outstretched arm and with terrifying deeds and with signs and miracles.

[[v5-26-9]]

^<<v5-26-9,9>>^ Then he brought us to this place and gave us this land, a land flowing with milk and honey.

[[v5-26-10]]

^<<v5-26-10,10>>^ Now I have brought the firstfruits of the produce of the ground that Jehovah has given me.’
“You must deposit it before Jehovah your God and bow down before Jehovah your God.

[[v5-26-11]]

^<<v5-26-11,11>>^ You will then rejoice over all the good that Jehovah your God has given you and your household, you and the Levite and the foreign resident who is among you.

[[v5-26-12]]

^<<v5-26-12,12>>^ “When you finish tithing the entire tenth of your produce in the third year, the year of the tenth, you will give it to the Levite, the foreign resident, the fatherless child,^&#42;1^ and the widow, and they will eat their fill within your cities.^&#42;2^

[NOTE]
====
. Or “the orphan.”
. Lit., “gates.”
====

[[v5-26-13]]

^<<v5-26-13,13>>^ You will then say before Jehovah your God, ‘I have cleared the holy portion out of my house and given it to the Levite, the foreign resident, the fatherless child, and the widow, just as you have commanded me. I have not violated or neglected your commandments.

[[v5-26-14]]

^<<v5-26-14,14>>^ I have not eaten of it while mourning or removed any of it while unclean or given any of it for the dead. I have obeyed the voice of Jehovah my God and have done all that you commanded me.

[[v5-26-15]]

^<<v5-26-15,15>>^ Now look down from your holy dwelling, the heavens, and bless your people Israel and the land that you have given us, just as you swore to our forefathers, the land flowing with milk and honey.’

[[v5-26-16]]

^<<v5-26-16,16>>^ “This day Jehovah your God is commanding you to carry out these regulations and judicial decisions. You must observe them and carry them out with all your heart and all your soul.^&#42;1^

[NOTE]
====
. See Glossary.
====

[[v5-26-17]]

^<<v5-26-17,17>>^ Today you have obtained Jehovah’s declaration that he will become your God as you walk in his ways and observe his regulations, his commandments, and his judicial decisions, and as you listen to his voice.

[[v5-26-18]]

^<<v5-26-18,18>>^ And today Jehovah has obtained your declaration that you will become his people, his special property,^&#42;1^ just as he has promised you, and that you will observe all his commandments

[NOTE]
====
. Or “treasured possession.”
====

[[v5-26-19]]

^<<v5-26-19,19>>^ and that he will put you high above all the other nations that he has made, giving you praise and fame and glory as you prove yourself a people holy to Jehovah your God, just as he has promised.”

'''

xref:005-deuteronomy/005-deuteronomy-025.adoc#v5-25-0[&#60; Capítulo Anterior] | <<v5-26-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-027.adoc#v5-27-0[Próximo Capítulo &#62;]