include::./index.adoc[]

[[v5-6-0]]
=== Deuteronomy, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-6-1]]

^<<v5-6-1,1>>^ “Now these are the commandments, the regulations, and the judicial decisions that Jehovah your God has given to teach you, so that you may observe them when you cross over into the land that you are to take possession of,

[[v5-6-2]]

^<<v5-6-2,2>>^ in order that you may fear Jehovah your God and keep all his statutes and his commandments that I am commanding you—you and your son and your grandson—all the days of your life, so that you may live a long time.

[[v5-6-3]]

^<<v5-6-3,3>>^ And you must listen, O Israel, and carefully observe them, so that you may prosper and become very many in the land flowing with milk and honey, just as Jehovah, the God of your forefathers, has promised you.

[[v5-6-4]]

^<<v5-6-4,4>>^ “Listen, O Israel: Jehovah our God is one Jehovah.

[[v5-6-5]]

^<<v5-6-5,5>>^ You must love Jehovah your God with all your heart and all your soul^&#42;1^ and all your strength.^&#42;2^

[NOTE]
====
. See Glossary.
. Or “vital force; resources.”
====

[[v5-6-6]]

^<<v5-6-6,6>>^ These words that I am commanding you today must be on your heart,

[[v5-6-7]]

^<<v5-6-7,7>>^ and you must inculcate them in^&#42;1^ your sons and speak of them when you sit in your house and when you walk on the road and when you lie down and when you get up.

[NOTE]
====
. Or “repeat them to; impress them upon.”
====

[[v5-6-8]]

^<<v5-6-8,8>>^ Tie them as a reminder on your hand, and they must be like a headband on your forehead.^&#42;1^

[NOTE]
====
. Lit., “between your eyes.”
====

[[v5-6-9]]

^<<v5-6-9,9>>^ Write them on the doorposts of your house and on your gates.

[[v5-6-10]]

^<<v5-6-10,10>>^ “When Jehovah your God brings you into the land that he swore to your forefathers Abraham, Isaac, and Jacob to give you—great and fine cities that you did not build,

[[v5-6-11]]

^<<v5-6-11,11>>^ houses full of all sorts of good things that you did not work for, hewn cisterns that you did not dig, and vineyards and olive trees that you did not plant—and you have eaten and become satisfied,

[[v5-6-12]]

^<<v5-6-12,12>>^ be careful not to forget Jehovah, who brought you out of the land of Egypt, out of the house of slavery.

[[v5-6-13]]

^<<v5-6-13,13>>^ Jehovah your God you should fear, and him you should serve, and by his name you should swear.

[[v5-6-14]]

^<<v5-6-14,14>>^ You must not follow after other gods, any gods of the peoples who are all around you,

[[v5-6-15]]

^<<v5-6-15,15>>^ for Jehovah your God who is in your midst is a God who requires exclusive devotion. Otherwise, the anger of Jehovah your God will blaze against you and he will annihilate you from the face of the earth.

[[v5-6-16]]

^<<v5-6-16,16>>^ “You must not put Jehovah your God to the test the way you put him to the test at Masʹsah.

[[v5-6-17]]

^<<v5-6-17,17>>^ You should diligently observe the commandments of Jehovah your God and his reminders and his regulations that he has commanded you to observe.

[[v5-6-18]]

^<<v5-6-18,18>>^ You must do what is right and good in Jehovah’s eyes, in order that you may prosper and that you may enter and take possession of the good land about which Jehovah has sworn to your forefathers,

[[v5-6-19]]

^<<v5-6-19,19>>^ by driving out all your enemies from before you, just as Jehovah has promised.

[[v5-6-20]]

^<<v5-6-20,20>>^ “In the future, when your son asks you, ‘What is the meaning of the reminders, the regulations, and the judicial decisions that Jehovah our God has commanded you?’

[[v5-6-21]]

^<<v5-6-21,21>>^ then you will say to your son, ‘We became slaves to Pharʹaoh in Egypt, but Jehovah brought us out of Egypt with a mighty hand.

[[v5-6-22]]

^<<v5-6-22,22>>^ So before our eyes Jehovah kept sending signs and miracles, great and devastating, upon Egypt, upon Pharʹaoh, and upon all his household.

[[v5-6-23]]

^<<v5-6-23,23>>^ And he brought us out from there in order to bring us here to give us the land about which he had sworn to our forefathers.

[[v5-6-24]]

^<<v5-6-24,24>>^ Then Jehovah commanded us to carry out all these regulations and to fear Jehovah our God for our lasting good, so that we could keep alive, as we are today.

[[v5-6-25]]

^<<v5-6-25,25>>^ And it will mean righteousness for us if we are careful to observe all these commandments in obedience to^&#42;1^ Jehovah our God, just as he has commanded us.’

[NOTE]
====
. Lit., “before.”
====

'''

xref:005-deuteronomy/005-deuteronomy-005.adoc#v5-5-0[&#60; Capítulo Anterior] | <<v5-6-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-007.adoc#v5-7-0[Próximo Capítulo &#62;]