include::./index.adoc[]

[[v5-23-0]]
=== Deuteronomy, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v5-23-1]]

^<<v5-23-1,1>>^ “No man who has been castrated by having his testicles crushed or who has had his male organ cut off may come into the congregation of Jehovah.

[[v5-23-2]]

^<<v5-23-2,2>>^ “No illegitimate son may come into the congregation of Jehovah. Even to the tenth generation, none of his descendants may come into the congregation of Jehovah.

[[v5-23-3]]

^<<v5-23-3,3>>^ “No Amʹmon·ite or Moʹab·ite may come into the congregation of Jehovah. Even to the tenth generation, none of their descendants may ever come into the congregation of Jehovah,

[[v5-23-4]]

^<<v5-23-4,4>>^ because they did not come to your aid with food and water when you were on the way going out of Egypt, and because they hired against you Baʹlaam the son of Beʹor from Peʹthor of Mes·o·po·taʹmi·a to curse^&#42;1^ you.

[NOTE]
====
. Or “call down evil upon.”
====

[[v5-23-5]]

^<<v5-23-5,5>>^ But Jehovah your God refused to listen to Baʹlaam. Rather, Jehovah your God changed the curse into a blessing for you, because Jehovah your God loved you.

[[v5-23-6]]

^<<v5-23-6,6>>^ You should never seek their welfare or their prosperity all your days.

[[v5-23-7]]

^<<v5-23-7,7>>^ “You must not hate an Eʹdom·ite, for he is your brother.
“You must not hate an Egyptian, for you became a foreign resident in his country.

[[v5-23-8]]

^<<v5-23-8,8>>^ The third generation of children born to them may enter the congregation of Jehovah.

[[v5-23-9]]

^<<v5-23-9,9>>^ “When you are encamped against your enemies, you should avoid anything bad.^&#42;1^

[NOTE]
====
. Or “defiling.”
====

[[v5-23-10]]

^<<v5-23-10,10>>^ If a man becomes unclean because of a nocturnal emission, he should go outside the camp and not reenter the camp.

[[v5-23-11]]

^<<v5-23-11,11>>^ When evening falls, he should wash with water, and then he may return to the camp at sunset.

[[v5-23-12]]

^<<v5-23-12,12>>^ A private place^&#42;1^ should be designated for use outside the camp, and there is where you should go.

[NOTE]
====
. That is, a latrine.
====

[[v5-23-13]]

^<<v5-23-13,13>>^ A peg should be part of your equipment. When you squat outside, you should dig a hole with it and then cover your excrement.

[[v5-23-14]]

^<<v5-23-14,14>>^ For Jehovah your God is walking about within your camp to deliver you and to hand over your enemies to you, and your camp must be holy, so that he does not see anything indecent in you and turn away from accompanying you.

[[v5-23-15]]

^<<v5-23-15,15>>^ “You should not hand over a slave to his master when he escapes from his master and comes to you.

[[v5-23-16]]

^<<v5-23-16,16>>^ He may dwell among you in whatever place he chooses in one of your cities, wherever he likes. You must not mistreat him.

[[v5-23-17]]

^<<v5-23-17,17>>^ “None of the daughters of Israel may become a temple prostitute, neither may anyone of the sons of Israel become a temple prostitute.

[[v5-23-18]]

^<<v5-23-18,18>>^ You must not bring the price paid to a female prostitute or the price paid to^&#42;1^ a male prostitute^&#42;2^ into the house of Jehovah your God to fulfill a vow, for both of them are something detestable to Jehovah your God.

[NOTE]
====
. Or “the earnings of.”
. Lit., “a dog.”
====

[[v5-23-19]]

^<<v5-23-19,19>>^ “You must not make your brother pay interest, whether interest on money, on food, or on anything on which interest may be charged.

[[v5-23-20]]

^<<v5-23-20,20>>^ You may make a foreigner pay interest, but you must not make your brother pay interest, so that Jehovah your God may bless you in every undertaking of yours in the land you are going to take possession of.

[[v5-23-21]]

^<<v5-23-21,21>>^ “If you make a vow to Jehovah your God, do not be slow about paying it. For Jehovah your God will surely require it of you; otherwise, it will be a sin on your part.

[[v5-23-22]]

^<<v5-23-22,22>>^ But if you refrain from making a vow, you will not be guilty of sin.

[[v5-23-23]]

^<<v5-23-23,23>>^ The word of your lips you should keep, and you must carry out what your own mouth vowed as a voluntary offering to Jehovah your God.

[[v5-23-24]]

^<<v5-23-24,24>>^ “If you enter your neighbor’s vineyard, you may eat enough grapes to satisfy your appetite,^&#42;1^ but you should not put any in your container.

[NOTE]
====
. Or “soul.”
====

[[v5-23-25]]

^<<v5-23-25,25>>^ “If you go into your neighbor’s field of standing grain, you may pluck the ripe ears with your hand, but you should not put a sickle to your neighbor’s grain.

'''

xref:005-deuteronomy/005-deuteronomy-022.adoc#v5-22-0[&#60; Capítulo Anterior] | <<v5-23-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-024.adoc#v5-24-0[Próximo Capítulo &#62;]