include::./index.adoc[]

[[v50-1-0]]
=== To the Philippians, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v50-1-1]]

^<<v50-1-1,1>>^ Paul and Timothy, slaves of Christ Jesus, to all the holy ones in union with Christ Jesus who are in Phi·lipʹpi, along with overseers and ministerial servants:

[[v50-1-2]]

^<<v50-1-2,2>>^ May you have undeserved kindness and peace from God our Father and the Lord Jesus Christ.

[[v50-1-3]]

^<<v50-1-3,3>>^ I thank my God always when I remember you

[[v50-1-4]]

^<<v50-1-4,4>>^ in every supplication of mine for all of you. I offer each supplication with joy,

[[v50-1-5]]

^<<v50-1-5,5>>^ because of the contribution you have made to^&#42;1^ the good news from the first day until this moment.

[NOTE]
====
. Or “because of your participation in furthering.”
====

[[v50-1-6]]

^<<v50-1-6,6>>^ For I am confident of this very thing, that the one who started a good work in you will bring it to completion until the day of Christ Jesus.

[[v50-1-7]]

^<<v50-1-7,7>>^ It is only right for me to think this regarding all of you, since I have you in my heart, you who are sharers with me in the undeserved kindness both in my prison bonds and in the defending and legally establishing of the good news.

[[v50-1-8]]

^<<v50-1-8,8>>^ For God is my witness of how I am longing for all of you with such tender affection as Christ Jesus has.

[[v50-1-9]]

^<<v50-1-9,9>>^ And this is what I continue praying, that your love may abound still more and more with accurate knowledge and full discernment;

[[v50-1-10]]

^<<v50-1-10,10>>^ that you may make sure of the more important things, so that you may be flawless and not stumbling others up to the day of Christ;

[[v50-1-11]]

^<<v50-1-11,11>>^ and that you may be filled with righteous fruit, which is through Jesus Christ, to God’s glory and praise.

[[v50-1-12]]

^<<v50-1-12,12>>^ Now I want you to know, brothers, that my situation has actually turned out for the advancement of the good news,

[[v50-1-13]]

^<<v50-1-13,13>>^ so that my prison bonds for the sake of Christ have become public knowledge among all the Prae·toʹri·an Guard and all the rest.

[[v50-1-14]]

^<<v50-1-14,14>>^ Now most of the brothers in the Lord have gained confidence because of my prison bonds, and they are showing all the more courage to speak the word of God fearlessly.

[[v50-1-15]]

^<<v50-1-15,15>>^ True, some are preaching the Christ out of envy and rivalry, but others out of goodwill.

[[v50-1-16]]

^<<v50-1-16,16>>^ The latter are proclaiming the Christ out of love, for they know that I have been appointed to defend the good news;

[[v50-1-17]]

^<<v50-1-17,17>>^ but the former do it out of contentiousness, not with a pure motive, for they are intending to create trouble for me in my prison bonds.

[[v50-1-18]]

^<<v50-1-18,18>>^ With what result? Only that in every way, whether in pretense or in truth, Christ is being proclaimed, and I rejoice over this. In fact, I will also keep on rejoicing,

[[v50-1-19]]

^<<v50-1-19,19>>^ for I know that this will result in my salvation through your supplication and with the support of the spirit of Jesus Christ.

[[v50-1-20]]

^<<v50-1-20,20>>^ This is in harmony with my eager expectation and hope that I will not be ashamed in any respect, but that with all freeness of speech Christ will now, as always before, be magnified by means of my body, whether through life or through death.

[[v50-1-21]]

^<<v50-1-21,21>>^ For in my case, to live is Christ and to die is gain.

[[v50-1-22]]

^<<v50-1-22,22>>^ Now if I am to live on in the flesh, this is a fruitage of my work; yet what I would choose, I do not make known.

[[v50-1-23]]

^<<v50-1-23,23>>^ I am torn between these two things, for I do desire the releasing and the being with Christ, which is, to be sure, far better.

[[v50-1-24]]

^<<v50-1-24,24>>^ However, it is more necessary for me to remain in the flesh for your sakes.

[[v50-1-25]]

^<<v50-1-25,25>>^ So, being confident of this, I know I will remain and continue with all of you for your advancement and your joy in the faith,

[[v50-1-26]]

^<<v50-1-26,26>>^ so that your exultation may overflow in Christ Jesus because of me when I am again present with you.

[[v50-1-27]]

^<<v50-1-27,27>>^ Only behave^&#42;1^ in a manner worthy of the good news about the Christ, so that whether I come and see you or I am absent, I may hear about you and learn that you are standing firm in one spirit, with one soul,^&#42;2^ striving side by side for the faith of the good news,

[NOTE]
====
. Or “carry on as citizens.”
. Or “with one accord.”
====

[[v50-1-28]]

^<<v50-1-28,28>>^ and in no way being frightened by your opponents. This very thing is a proof of destruction for them, but of salvation for you; and this is from God.

[[v50-1-29]]

^<<v50-1-29,29>>^ For you have been given the privilege in behalf of Christ, not only to put your faith in him but also to suffer in his behalf.

[[v50-1-30]]

^<<v50-1-30,30>>^ For you are facing the same struggle that you saw me face, which you now hear that I am still facing.

'''

xref:049-ephesians/049-ephesians-006.adoc#v49-6-0[&#60; Capítulo Anterior] | <<v50-1-0,Topo>> | xref:050-philippians/050-philippians-002.adoc#v50-2-0[Próximo Capítulo &#62;]