include::./index.adoc[]

[[v50-2-0]]
=== To the Philippians, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v50-2-1]]

^<<v50-2-1,1>>^ If, then, there is any encouragement in Christ, if any consolation of love, if any spiritual fellowship,^&#42;1^ if any tender affection and compassion,

[NOTE]
====
. Lit., “any sharing of spirit.”
====

[[v50-2-2]]

^<<v50-2-2,2>>^ make my joy full by being of the same mind and having the same love, being completely united,^&#42;1^ having the one thought in mind.

[NOTE]
====
. Or “being joined together in soul.”
====

[[v50-2-3]]

^<<v50-2-3,3>>^ Do nothing out of contentiousness or out of egotism, but with humility^&#42;1^ consider others superior to you,

[NOTE]
====
. Or “lowliness of mind.”
====

[[v50-2-4]]

^<<v50-2-4,4>>^ as you look out not only for your own interests, but also for the interests of others.

[[v50-2-5]]

^<<v50-2-5,5>>^ Keep this mental attitude in you that was also in Christ Jesus,

[[v50-2-6]]

^<<v50-2-6,6>>^ who, although he was existing in God’s form, did not even consider the idea of trying to be equal to God.

[[v50-2-7]]

^<<v50-2-7,7>>^ No, but he emptied himself and took a slave’s form and became human.^&#42;1^

[NOTE]
====
. Lit., “came to be in the likeness of men.”
====

[[v50-2-8]]

^<<v50-2-8,8>>^ More than that, when he came as a man,^&#42;1^ he humbled himself and became obedient to the point of death, yes, death on a torture stake.^&#42;2^

[NOTE]
====
. Lit., “when he was found in appearance as a man.”
. See Glossary.
====

[[v50-2-9]]

^<<v50-2-9,9>>^ For this very reason, God exalted him to a superior position and kindly gave him the name that is above every other name,

[[v50-2-10]]

^<<v50-2-10,10>>^ so that in the name of Jesus every knee should bend—of those in heaven and those on earth and those under the ground—

[[v50-2-11]]

^<<v50-2-11,11>>^ and every tongue should openly acknowledge that Jesus Christ is Lord to the glory of God the Father.

[[v50-2-12]]

^<<v50-2-12,12>>^ Consequently, my beloved ones, just as you have always obeyed, not only during my presence but now much more readily during my absence, keep working out your own salvation with fear and trembling.

[[v50-2-13]]

^<<v50-2-13,13>>^ For God is the one who for the sake of his good pleasure energizes you, giving you both the desire and the power to act.

[[v50-2-14]]

^<<v50-2-14,14>>^ Keep doing all things free from murmuring and arguments,

[[v50-2-15]]

^<<v50-2-15,15>>^ so that you may come to be blameless and innocent, children of God without a blemish in the midst of a crooked and twisted generation, among whom you are shining as illuminators in the world,

[[v50-2-16]]

^<<v50-2-16,16>>^ keeping a tight grip on the word of life. Then I may have reason for rejoicing in Christ’s day, knowing that I did not run in vain or work hard in vain.

[[v50-2-17]]

^<<v50-2-17,17>>^ However, even if I am being poured out like a drink offering on the sacrifice and the holy service^&#42;1^ to which your faith has led you, I am glad and I rejoice with all of you.

[NOTE]
====
. Or “the public service.”
====

[[v50-2-18]]

^<<v50-2-18,18>>^ In the same way, you also should be glad and rejoice with me.

[[v50-2-19]]

^<<v50-2-19,19>>^ Now I am hoping in the Lord Jesus to send Timothy to you shortly, so that I may be encouraged when I receive news about you.

[[v50-2-20]]

^<<v50-2-20,20>>^ For I have no one else of a disposition like his who will genuinely care for your concerns.

[[v50-2-21]]

^<<v50-2-21,21>>^ For all the others are seeking their own interests, not those of Jesus Christ.

[[v50-2-22]]

^<<v50-2-22,22>>^ But you know the proof he gave of himself, that like a child with a father he slaved with me to advance the good news.

[[v50-2-23]]

^<<v50-2-23,23>>^ Therefore, he is the one I am hoping to send just as soon as I see how things turn out for me.

[[v50-2-24]]

^<<v50-2-24,24>>^ Indeed, I am confident in the Lord that I myself will also come soon.

[[v50-2-25]]

^<<v50-2-25,25>>^ But for now I consider it necessary to send to you E·paph·ro·diʹtus, my brother and fellow worker and fellow soldier, and your envoy and personal servant for my need,

[[v50-2-26]]

^<<v50-2-26,26>>^ since he is longing to see all of you and is depressed because you heard he had fallen sick.

[[v50-2-27]]

^<<v50-2-27,27>>^ Indeed, he did fall sick nearly to the point of death; but God had mercy on him, in fact, not only on him but also on me, so that I should not have one grief after another.

[[v50-2-28]]

^<<v50-2-28,28>>^ Therefore, I am sending him with the greatest urgency, so that when you see him you may again rejoice and I may also be less anxious.

[[v50-2-29]]

^<<v50-2-29,29>>^ So give him the customary welcome in the Lord with all joy, and keep holding men of that sort dear,

[[v50-2-30]]

^<<v50-2-30,30>>^ because he nearly died on account of the work of Christ,^&#42;1^ risking his life^&#42;2^ in order to make up for your not being here to render personal service to me.

[NOTE]
====
. Or possibly, “of the Lord’s work.”
. Or “exposing his soul to danger.”
====

'''

xref:050-philippians/050-philippians-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-philippians/050-philippians-003.adoc#v50-3-0[Próximo Capítulo &#62;]