include::./index.adoc[]

[[v50-3-0]]
=== To the Philippians, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v50-3-1]]

^<<v50-3-1,1>>^ Finally, my brothers, continue rejoicing in the Lord. It is not troublesome for me to write the same things to you, and it is for your safety.

[[v50-3-2]]

^<<v50-3-2,2>>^ Look out for the dogs; look out for those who cause injury; look out for those who mutilate the flesh.

[[v50-3-3]]

^<<v50-3-3,3>>^ For we are those with the real circumcision, we who are rendering sacred service by God’s spirit and boasting in Christ Jesus and who do not base our confidence in the flesh,

[[v50-3-4]]

^<<v50-3-4,4>>^ though I, if anyone, do have grounds for confidence in the flesh.
If any other man thinks he has grounds for confidence in the flesh, I have more:

[[v50-3-5]]

^<<v50-3-5,5>>^ circumcised the eighth day, of the nation of Israel, of the tribe of Benjamin, a Hebrew born from Hebrews; regarding law, a Pharisee;

[[v50-3-6]]

^<<v50-3-6,6>>^ regarding zeal, persecuting the congregation; regarding righteousness based on law, one who proved himself blameless.

[[v50-3-7]]

^<<v50-3-7,7>>^ Yet, the things that were gains to me, I have considered loss^&#42;1^ on account of the Christ.

[NOTE]
====
. Or possibly, “have willingly abandoned.”
====

[[v50-3-8]]

^<<v50-3-8,8>>^ What is more, I do indeed also consider all things to be loss on account of the excelling value of the knowledge of Christ Jesus my Lord. For his sake I have taken the loss of all things and I consider them as a lot of refuse,^&#42;1^ that I may gain Christ

[NOTE]
====
. Or “garbage; rubbish.”
====

[[v50-3-9]]

^<<v50-3-9,9>>^ and be found in union with him, not because of my own righteousness from following the Law, but because of the righteousness that is through faith in Christ, the righteousness from God based on faith.

[[v50-3-10]]

^<<v50-3-10,10>>^ My aim is to know him and the power of his resurrection and to share in his sufferings, submitting myself to a death like his,

[[v50-3-11]]

^<<v50-3-11,11>>^ to see if at all possible I may attain to the earlier resurrection from the dead.

[[v50-3-12]]

^<<v50-3-12,12>>^ Not that I have already received it or am already made perfect, but I am pressing on to see if I may also lay hold on that for which Christ Jesus selected me.^&#42;1^

[NOTE]
====
. Lit., “laid hold on me.”
====

[[v50-3-13]]

^<<v50-3-13,13>>^ Brothers, I do not yet consider myself as having taken hold of it; but one thing is certain: Forgetting the things behind and stretching forward to the things ahead,

[[v50-3-14]]

^<<v50-3-14,14>>^ I am pressing on toward the goal for the prize of the upward call of God by means of Christ Jesus.

[[v50-3-15]]

^<<v50-3-15,15>>^ Therefore, let those of us who are mature be of this mental attitude, and if you are mentally inclined otherwise in any respect, God will reveal the above attitude to you.

[[v50-3-16]]

^<<v50-3-16,16>>^ At any rate, to the extent we have made progress, let us go on walking orderly in this same course.

[[v50-3-17]]

^<<v50-3-17,17>>^ Unitedly become imitators of me, brothers, and keep your eye on those who are walking in a way that is in harmony with the example we set for you.

[[v50-3-18]]

^<<v50-3-18,18>>^ For there are many—I used to mention them often but now I mention them also with weeping—who are walking as enemies of the torture stake^&#42;1^ of the Christ.

[NOTE]
====
. See Glossary.
====

[[v50-3-19]]

^<<v50-3-19,19>>^ Their end is destruction, and their god is their belly, and their glory is really their shame, and they have their minds on earthly things.

[[v50-3-20]]

^<<v50-3-20,20>>^ But our citizenship exists in the heavens, and we are eagerly waiting for a savior from there, the Lord Jesus Christ,

[[v50-3-21]]

^<<v50-3-21,21>>^ who will transform our humble body to be like^&#42;1^ his glorious body by his great power that enables him to subject all things to himself.

[NOTE]
====
. Lit., “to be conformed to.”
====

'''

xref:050-philippians/050-philippians-002.adoc#v50-2-0[&#60; Capítulo Anterior] | <<v50-3-0,Topo>> | xref:050-philippians/050-philippians-004.adoc#v50-4-0[Próximo Capítulo &#62;]