include::./index.adoc[]

[[v25-1-0]]
=== Lamentations, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_א &#91;Aleph&#93;^&#42;1^_

[[v25-1-1]]

^<<v25-1-1,1>>^ How she now sits all alone, the city that was full of people!
How she has become like a widow, she who was populous among the nations!
How she who was a princess among the provinces^&#42;1^ has been put to forced labor!

[NOTE]
====
. Or “jurisdictional districts.”
====

_ב &#91;Beth&#93;_

[[v25-1-2]]

^<<v25-1-2,2>>^ She weeps profusely during the night, and her tears cover her cheeks.
Not one of all her lovers is there to comfort her.
All her own companions have betrayed her; they have become her enemies.

_ג &#91;Gimel&#93;_

[[v25-1-3]]

^<<v25-1-3,3>>^ Judah has gone into exile under affliction and harsh slavery.
She must dwell among the nations; she finds no resting-place.
All her persecutors have overtaken her in her distress.

_ד &#91;Daleth&#93;_

[[v25-1-4]]

^<<v25-1-4,4>>^ The roads to Zion are mourning, because no one is coming to the festival.
All her gates are desolate; her priests are sighing.
Her virgins^&#42;1^ are grieving, and she is in bitter anguish.

[NOTE]
====
. Or “young women.”
====

_ה &#91;He&#93;_

[[v25-1-5]]

^<<v25-1-5,5>>^ Her adversaries are now her master;^&#42;1^ her enemies are carefree.
For Jehovah has brought grief to her because of her many transgressions.
Her children have gone into captivity before the adversary.

[NOTE]
====
. Lit., “head.”
====

_ו &#91;Waw&#93;_

[[v25-1-6]]

^<<v25-1-6,6>>^ All the splendor has departed from the daughter of Zion.
Her princes are like stags that have found no pasture,
And they walk exhausted before the pursuer.

_ז &#91;Zayin&#93;_

[[v25-1-7]]

^<<v25-1-7,7>>^ In the days of her affliction and her homelessness, Jerusalem remembers
All the precious things that were hers in the days of long ago.
When her people fell into the hand of the adversary and she had no helper,
The adversaries saw her and laughed^&#42;1^ over her collapse.

[NOTE]
====
. Or “gloated.”
====

_ח &#91;Heth&#93;_

[[v25-1-8]]

^<<v25-1-8,8>>^ Jerusalem has sinned greatly.
That is why she has become something abhorrent.
All who used to honor her now treat her as something contemptible, for they have seen her nakedness.
She herself groans and turns away in shame.

_ט &#91;Teth&#93;_

[[v25-1-9]]

^<<v25-1-9,9>>^ Her uncleanness is in her skirts.
She gave no thought to her future.
Her downfall was astounding; she has no one to comfort her.
O Jehovah, see my affliction, for the enemy has magnified himself.

_י &#91;Yod&#93;_

[[v25-1-10]]

^<<v25-1-10,10>>^ The adversary has laid his hands on all her treasures.
For she has seen nations enter her sanctuary,
Those whom you commanded should not enter into your congregation.

_כ &#91;Kaph&#93;_

[[v25-1-11]]

^<<v25-1-11,11>>^ All her people are sighing; they are looking for bread.
They have given their valuable things for something to eat, just to stay alive.^&#42;1^
Look, O Jehovah, and see that I have become as a worthless woman.^&#42;2^

[NOTE]
====
. Or “to restore the soul.”
. A personification referring to Jerusalem.
====

_ל &#91;Lamed&#93;_

[[v25-1-12]]

^<<v25-1-12,12>>^ Is it nothing to all of you who pass along the road?
Look and see!
Is there any pain like the pain that was dealt out to me,
Which Jehovah made me suffer in the day of his burning anger?

_מ &#91;Mem&#93;_

[[v25-1-13]]

^<<v25-1-13,13>>^ From on high he has sent fire into my bones, and he subdues each one.
He has spread out a net for my feet; he has forced me to turn backward.
He has made me a desolate woman.
All day long I am ill.

_נ &#91;Nun&#93;_

[[v25-1-14]]

^<<v25-1-14,14>>^ My transgressions are bound as a yoke, fastened together by his hand.
They have been placed on my neck, and my strength has failed.
Jehovah has given me into the hand of those whom I cannot resist.

_ס &#91;Samekh&#93;_

[[v25-1-15]]

^<<v25-1-15,15>>^ Jehovah has tossed aside all the powerful men in my midst.
He has summoned an assembly against me to crush my young men.
Jehovah has trodden the virgin daughter of Judah in the winepress.

_ע &#91;Ayin&#93;_

[[v25-1-16]]

^<<v25-1-16,16>>^ I am weeping because of these things; my eyes flow with tears.
For anyone who could comfort me or refresh me^&#42;1^ is far away from me.
My sons are desolate, for the enemy has prevailed.

[NOTE]
====
. Or “my soul.”
====

_פ &#91;Pe&#93;_

[[v25-1-17]]

^<<v25-1-17,17>>^ Zion has spread out her hands; she has no one to comfort her.
Jehovah has given an order against Jacob to all his adversaries around him.
Jerusalem has become to them an abhorrent thing.

_צ &#91;Tsade&#93;_

[[v25-1-18]]

^<<v25-1-18,18>>^ Jehovah is righteous, for it is against his commands^&#42;1^ that I have rebelled.
Listen, all you peoples, and see my pain.
My virgins^&#42;2^ and my young men have gone into captivity.

[NOTE]
====
. Lit., “mouth.”
. Or “young women.”
====

_ק &#91;Qoph&#93;_

[[v25-1-19]]

^<<v25-1-19,19>>^ I have called out to my lovers, but they have betrayed me.
In the city my priests and my elders have perished,
While they searched for food in order to stay alive.^&#42;1^

[NOTE]
====
. Or “to restore the soul.”
====

_ר &#91;Resh&#93;_

[[v25-1-20]]

^<<v25-1-20,20>>^ See, O Jehovah, for I am in great distress.
My insides^&#42;1^ are churning.
My heart has turned over within me, for I have been completely rebellious.
Outside the sword bereaves; inside the house it is like death.

[NOTE]
====
. Lit., “intestines.”
====

_ש &#91;Shin&#93;_

[[v25-1-21]]

^<<v25-1-21,21>>^ People have heard my sighing; there is no one to comfort me.
All my enemies have heard of my calamity.
They are joyful, because you brought it about.
But you will bring about the day that you proclaimed, when they will become like me.

_ת &#91;Taw&#93;_

[[v25-1-22]]

^<<v25-1-22,22>>^ May all their badness come before you, and may you deal harshly with them,
Just as you have dealt harshly with me because of all my transgressions.
For my sighs are many, and my heart is sick.

'''

xref:024-jeremiah/024-jeremiah-052.adoc#v24-52-0[&#60; Capítulo Anterior] | <<v25-1-0,Topo>> | xref:025-lamentations/025-lamentations-002.adoc#v25-2-0[Próximo Capítulo &#62;]