include::./index.adoc[]

[[v25-4-0]]
=== Lamentations, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_א &#91;Aleph&#93;_

[[v25-4-1]]

^<<v25-4-1,1>>^ How the shining gold has grown dim, the fine gold!
How the holy stones lie scattered at every street corner!^&#42;1^

[NOTE]
====
. Lit., “at the head of all streets!”
====

_ב &#91;Beth&#93;_

[[v25-4-2]]

^<<v25-4-2,2>>^ As for the precious sons of Zion, who were weighed against^&#42;1^ refined gold,
How they have been regarded as earthenware jars,
The work of a potter’s hands!

[NOTE]
====
. Or “were as precious as.”
====

_ג &#91;Gimel&#93;_

[[v25-4-3]]

^<<v25-4-3,3>>^ Even jackals offer the udder to nurse their young,
But the daughter of my people has become cruel, like ostriches in the wilderness.

_ד &#91;Daleth&#93;_

[[v25-4-4]]

^<<v25-4-4,4>>^ The tongue of the nursing infant sticks to its palate because of thirst.
Children beg for bread, but no one gives them any.

_ה &#91;He&#93;_

[[v25-4-5]]

^<<v25-4-5,5>>^ Those who used to eat delicacies lie famished^&#42;1^ in the streets.
Those who were brought up wearing scarlet have embraced ash heaps.

[NOTE]
====
. Lit., “desolate.”
====

_ו &#91;Waw&#93;_

[[v25-4-6]]

^<<v25-4-6,6>>^ The punishment^&#42;1^ of the daughter of my people is greater than the punishment for the sin of Sodʹom,
Which was overthrown in a moment, with no hand to help her.

[NOTE]
====
. Lit., “error.”
====

_ז &#91;Zayin&#93;_

[[v25-4-7]]

^<<v25-4-7,7>>^ Her Nazʹi·rites were purer than snow, whiter than milk.
They were more ruddy than corals; they were like polished sapphires.

_ח &#91;Heth&#93;_

[[v25-4-8]]

^<<v25-4-8,8>>^ Their appearance has become darker than soot;^&#42;1^
They are not recognized in the streets.
Their skin has shriveled over their bones; it has become like dry wood.

[NOTE]
====
. Lit., “blackness.”
====

_ט &#91;Teth&#93;_

[[v25-4-9]]

^<<v25-4-9,9>>^ Those slain with the sword are better off than those slain by famine,
Those who waste away, who are pierced through for lack of food from the field.

_י &#91;Yod&#93;_

[[v25-4-10]]

^<<v25-4-10,10>>^ The hands of compassionate women have boiled their own children.
They have become their food of mourning during the breakdown of the daughter of my people.

_כ &#91;Kaph&#93;_

[[v25-4-11]]

^<<v25-4-11,11>>^ Jehovah has expressed his wrath;
He has poured out his burning anger.
And he starts a fire in Zion that consumes her foundations.

_ל &#91;Lamed&#93;_

[[v25-4-12]]

^<<v25-4-12,12>>^ The kings of the earth and all the inhabitants of the productive land did not believe
That the adversary and the enemy would enter the gates of Jerusalem.

_מ &#91;Mem&#93;_

[[v25-4-13]]

^<<v25-4-13,13>>^ It was because of the sins of her prophets, the errors of her priests,
Who shed the blood of righteous ones in her midst.

_נ &#91;Nun&#93;_

[[v25-4-14]]

^<<v25-4-14,14>>^ They have wandered blindly in the streets.
They are polluted with blood,
So that none are able to touch their garments.

_ס &#91;Samekh&#93;_

[[v25-4-15]]

^<<v25-4-15,15>>^ “Go away! Unclean!” they call out to them. “Go away! Go away! Do not touch us!”
For they have gone homeless and wander about.
People have said among the nations: “They cannot stay here with us.^&#42;1^

[NOTE]
====
. Or “reside here as foreigners.”
====

_פ &#91;Pe&#93;_

[[v25-4-16]]

^<<v25-4-16,16>>^ The face of Jehovah has scattered them;
He will no longer look favorably on them.
Men will show no respect for the priests, no favor to the elders.”

_ע &#91;Ayin&#93;_

[[v25-4-17]]

^<<v25-4-17,17>>^ Even now our eyes are worn out from looking in vain for help.
We looked and looked for help from a nation that could not save us.

_צ &#91;Tsade&#93;_

[[v25-4-18]]

^<<v25-4-18,18>>^ They have hunted us down at every step so that we could not walk in our public squares.
Our end has drawn near; our days have finished, for our end has come.

_ק &#91;Qoph&#93;_

[[v25-4-19]]

^<<v25-4-19,19>>^ Our pursuers were swifter than the eagles of the sky.
They chased us on the mountains; they ambushed us in the wilderness.

_ר &#91;Resh&#93;_

[[v25-4-20]]

^<<v25-4-20,20>>^ The breath of our nostrils, the anointed one of Jehovah, has been captured in their large pit,
The one of whom we said: “In his shade we will live among the nations.”

_ש &#91;Sin&#93;_

[[v25-4-21]]

^<<v25-4-21,21>>^ Exult and rejoice, O daughter of Eʹdom, living as you do in the land of Uz.
But to you also the cup will be passed, and you will become drunk and expose your nakedness.

_ת &#91;Taw&#93;_

[[v25-4-22]]

^<<v25-4-22,22>>^ The punishment for your error, O daughter of Zion, has come to its finish.
He will not carry you off into exile again.
But he will turn his attention to your error, O daughter of Eʹdom.
He will uncover your sins.

'''

xref:025-lamentations/025-lamentations-003.adoc#v25-3-0[&#60; Capítulo Anterior] | <<v25-4-0,Topo>> | xref:025-lamentations/025-lamentations-005.adoc#v25-5-0[Próximo Capítulo &#62;]