include::./index.adoc[]

[[v25-2-0]]
=== Lamentations, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

_א &#91;Aleph&#93;_

[[v25-2-1]]

^<<v25-2-1,1>>^ How Jehovah has covered the daughter of Zion in the cloud of his anger!
He has thrown down the beauty of Israel from heaven to earth.
He has not remembered his footstool in the day of his anger.

_ב &#91;Beth&#93;_

[[v25-2-2]]

^<<v25-2-2,2>>^ Jehovah has swallowed up without compassion all the dwellings of Jacob.
In his fury he has torn down the fortified places of the daughter of Judah.
He has brought down to the ground and profaned the kingdom and her princes.

_ג &#91;Gimel&#93;_

[[v25-2-3]]

^<<v25-2-3,3>>^ In the heat of anger he has cut down all the strength^&#42;1^ of Israel.
He withdrew his right hand when the enemy approached,
And in Jacob he kept burning like a fire that consumed everything around it.

[NOTE]
====
. Lit., “every horn.”
====

_ד &#91;Daleth&#93;_

[[v25-2-4]]

^<<v25-2-4,4>>^ He has bent^&#42;1^ his bow like an enemy; his right hand is poised as an adversary;
He kept killing all those desirable to the eyes.
And he poured out his wrath like a fire into the tent of the daughter of Zion.

[NOTE]
====
. Lit., “trodden.”
====

_ה &#91;He&#93;_

[[v25-2-5]]

^<<v25-2-5,5>>^ Jehovah has become like an enemy;
He has swallowed down Israel.
He has swallowed down all her towers;
He has destroyed all its fortified places.
And in the daughter of Judah he makes mourning and lamentation abound.

_ו &#91;Waw&#93;_

[[v25-2-6]]

^<<v25-2-6,6>>^ He treats his booth violently, like a hut in a garden.
He has put an end to^&#42;1^ his festival.
Jehovah has caused festival and sabbath to be forgotten in Zion,
And in his fierce indignation he shows no regard for king and priest.

[NOTE]
====
. Or “destroyed.”
====

_ז &#91;Zayin&#93;_

[[v25-2-7]]

^<<v25-2-7,7>>^ Jehovah has rejected his altar;
He has spurned his sanctuary.
He has surrendered the walls of her fortified towers into the hand of the enemy.
They have raised their voice in the house of Jehovah, as on the day of a festival.

_ח &#91;Heth&#93;_

[[v25-2-8]]

^<<v25-2-8,8>>^ Jehovah has resolved to destroy the wall of the daughter of Zion.
He has stretched out the measuring line.
He has not held back his hand from bringing destruction.^&#42;1^
And he causes rampart and wall to mourn.
Together they have been made weak.

[NOTE]
====
. Lit., “from swallowing up.”
====

_ט &#91;Teth&#93;_

[[v25-2-9]]

^<<v25-2-9,9>>^ Her gates have sunk down into the earth.
He has destroyed and broken her bars.
Her king and her princes are among the nations.
There is no law;^&#42;1^ even her prophets find no vision from Jehovah.

[NOTE]
====
. Or “instruction.”
====

_י &#91;Yod&#93;_

[[v25-2-10]]

^<<v25-2-10,10>>^ The elders of the daughter of Zion sit on the ground in silence.
They throw dust on their heads and wear sackcloth.
The virgins of Jerusalem have bowed their heads down to the ground.

_כ &#91;Kaph&#93;_

[[v25-2-11]]

^<<v25-2-11,11>>^ My eyes are worn out from shedding tears.
My insides^&#42;1^ are churning.
My liver has been poured out on the ground, because of the downfall of the daughter of^&#42;2^ my people,
Because of the children and infants fainting away in the public squares of the town.

[NOTE]
====
. Lit., “intestines.”
. A poetic personification, perhaps expressing pity or sympathy.
====

_ל &#91;Lamed&#93;_

[[v25-2-12]]

^<<v25-2-12,12>>^ They keep asking their mothers, “Where are grain and wine?”
As they faint away like someone wounded in the public squares of the city,
As their life^&#42;1^ ebbs away in their mothers’ arms.

[NOTE]
====
. Or “soul.”
====

_מ &#91;Mem&#93;_

[[v25-2-13]]

^<<v25-2-13,13>>^ What can I use as a witness,
Or to what can I liken you, O daughter of Jerusalem?
To what can I compare you, to comfort you, O virgin daughter of Zion?
For your breakdown is as vast as the sea. Who can heal you?

_נ &#91;Nun&#93;_

[[v25-2-14]]

^<<v25-2-14,14>>^ The visions your prophets saw for you were false and empty,
And they did not expose your error in order to turn away your captivity,
But they kept visioning for you false and misleading pronouncements.

_ס &#91;Samekh&#93;_

[[v25-2-15]]

^<<v25-2-15,15>>^ At you all those passing by on the road scornfully clap their hands.
They whistle in amazement and shake their heads at the daughter of Jerusalem, saying:
“Is this the city about which they said, ‘It is perfect in beauty, the joy of all the earth’?”

_פ &#91;Pe&#93;_

[[v25-2-16]]

^<<v25-2-16,16>>^ At you all your enemies have opened their mouth.
They whistle and grind their teeth and say: “We have swallowed her down.
This is the day we were waiting for! It has arrived, and we have seen it!”

_ע &#91;Ayin&#93;_

[[v25-2-17]]

^<<v25-2-17,17>>^ Jehovah has done what he intended; he has carried out his saying,
What he commanded long ago.
He has torn down without compassion.
He has let the enemy rejoice over you; he has exalted the strength^&#42;1^ of your adversaries.

[NOTE]
====
. Lit., “horn.”
====

_צ &#91;Tsade&#93;_

[[v25-2-18]]

^<<v25-2-18,18>>^ Their heart cries out to Jehovah, O wall of the daughter of Zion.
Let tears stream down like a torrent day and night.
Give yourself no respite, give your eye^&#42;1^ no rest.

[NOTE]
====
. Lit., “the daughter of your eye.”
====

_ק &#91;Qoph&#93;_

[[v25-2-19]]

^<<v25-2-19,19>>^ Rise up! Cry out during the night, at the start of the watches.
Pour out your heart like water before the face of Jehovah.
Raise your hands to him for the lives^&#42;1^ of your children,
Who are fainting away at every street corner^&#42;2^ because of famine.

[NOTE]
====
. Or “souls.”
. Lit., “at the head of all streets.”
====

_ר &#91;Resh&#93;_

[[v25-2-20]]

^<<v25-2-20,20>>^ See, O Jehovah, and look upon the one with whom you have dealt so harshly.
Should women keep eating their own offspring,^&#42;1^ their own fully formed children,
Or should priests and prophets be killed in the sanctuary of Jehovah?

[NOTE]
====
. Or “fruitage.”
====

_ש &#91;Shin&#93;_

[[v25-2-21]]

^<<v25-2-21,21>>^ Young boy and old man are lying dead on the ground in the streets.
My virgins^&#42;1^ and my young men have fallen by the sword.
You have killed in the day of your anger; you have slaughtered without compassion.

[NOTE]
====
. Or “young women.”
====

_ת &#91;Taw&#93;_

[[v25-2-22]]

^<<v25-2-22,22>>^ As if for a festival day, you summon terrors from every direction.
In the day of the wrath of Jehovah, no one escaped or survived;
Those whom I gave birth to^&#42;1^ and reared, my enemy exterminated.

[NOTE]
====
. Or “brought forth healthy.”
====

'''

xref:025-lamentations/025-lamentations-001.adoc#v25-1-0[&#60; Capítulo Anterior] | <<v25-2-0,Topo>> | xref:025-lamentations/025-lamentations-003.adoc#v25-3-0[Próximo Capítulo &#62;]