include::./index.adoc[]

[[v61-1-0]]
=== The Second of Peter, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v61-1-1]]

^<<v61-1-1,1>>^ Simon Peter, a slave and an apostle of Jesus Christ, to those who have acquired a faith as precious as ours^&#42;1^ through the righteousness of our God and the Savior Jesus Christ:

[NOTE]
====
. Or “a faith held in equal privilege with ours.”
====

[[v61-1-2]]

^<<v61-1-2,2>>^ May undeserved kindness and peace be increased to you by an accurate knowledge of God and of Jesus our Lord,

[[v61-1-3]]

^<<v61-1-3,3>>^ for his divine power has granted^&#42;1^ us all the things that contribute to life and godly devotion through the accurate knowledge of the One who called us by his own glory and virtue.

[NOTE]
====
. Or “freely given.”
====

[[v61-1-4]]

^<<v61-1-4,4>>^ Through these things he has granted^&#42;1^ us the precious and very grand promises, so that through these you may become sharers in divine nature, having escaped from the world’s corruption produced by wrong desire.^&#42;2^

[NOTE]
====
. Or “freely given.”
. Or “by lust.”
====

[[v61-1-5]]

^<<v61-1-5,5>>^ For this very reason, put forth all earnest effort to supply to your faith virtue, to your virtue knowledge,

[[v61-1-6]]

^<<v61-1-6,6>>^ to your knowledge self-control, to your self-control endurance, to your endurance godly devotion,

[[v61-1-7]]

^<<v61-1-7,7>>^ to your godly devotion brotherly affection, to your brotherly affection love.

[[v61-1-8]]

^<<v61-1-8,8>>^ For if these things exist in you and overflow, they will prevent you from being either inactive or unfruitful^&#42;1^ regarding the accurate knowledge of our Lord Jesus Christ.

[NOTE]
====
. Or “unproductive.”
====

[[v61-1-9]]

^<<v61-1-9,9>>^ For anyone lacking these things is blind, shutting his eyes to the light,^&#42;1^ and has become forgetful of his cleansing from his sins of long ago.

[NOTE]
====
. Or possibly, “blind, shortsighted.”
====

[[v61-1-10]]

^<<v61-1-10,10>>^ Therefore, brothers, be all the more diligent to make your calling and choosing sure for yourselves, for if you keep on doing these things, you will by no means ever fail.

[[v61-1-11]]

^<<v61-1-11,11>>^ In fact, in this way you will be richly granted^&#42;1^ entrance into the everlasting Kingdom of our Lord and Savior Jesus Christ.

[NOTE]
====
. Or “abundantly supplied with.”
====

[[v61-1-12]]

^<<v61-1-12,12>>^ For this reason I intend always to remind you of these things, although you know them and are well-established in the truth that is present in you.

[[v61-1-13]]

^<<v61-1-13,13>>^ But I consider it right, as long as I am in this tabernacle,^&#42;1^ to stir you with reminders,

[NOTE]
====
. Or “tent,” that is, his earthly body.
====

[[v61-1-14]]

^<<v61-1-14,14>>^ knowing as I do that my tabernacle is soon to be removed, just as also our Lord Jesus Christ made clear to me.

[[v61-1-15]]

^<<v61-1-15,15>>^ I will always do my utmost so that after my departure, you may be able to recall^&#42;1^ these things for yourselves.

[NOTE]
====
. Or “mention.”
====

[[v61-1-16]]

^<<v61-1-16,16>>^ No, it was not by following artfully contrived false stories that we made known to you the power and presence of our Lord Jesus Christ, but rather, we were eyewitnesses of his magnificence.

[[v61-1-17]]

^<<v61-1-17,17>>^ For he received from God the Father honor and glory when words such as these^&#42;1^ were conveyed to him by the magnificent glory: “This is my Son, my beloved, whom I myself have approved.”

[NOTE]
====
. Lit., “such a voice.”
====

[[v61-1-18]]

^<<v61-1-18,18>>^ Yes, these words we heard coming from heaven while we were with him in the holy mountain.

[[v61-1-19]]

^<<v61-1-19,19>>^ So we have the prophetic word made more sure, and you are doing well in paying attention to it as to a lamp shining in a dark place (until day dawns and a daystar rises) in your hearts.

[[v61-1-20]]

^<<v61-1-20,20>>^ For you know this first, that no prophecy of Scripture springs from any private interpretation.

[[v61-1-21]]

^<<v61-1-21,21>>^ For prophecy was at no time brought by man’s will, but men spoke from God as they were moved^&#42;1^ by holy spirit.

[NOTE]
====
. Lit., “carried along; borne along.”
====

'''

xref:060-1-peter/060-1-peter-005.adoc#v60-5-0[&#60; Capítulo Anterior] | <<v61-1-0,Topo>> | xref:061-2-peter/061-2-peter-002.adoc#v61-2-0[Próximo Capítulo &#62;]