include::./index.adoc[]

[[v61-3-0]]
=== The Second of Peter, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v61-3-1]]

^<<v61-3-1,1>>^ Beloved ones, this is now the second letter I am writing you in which, as in my first one, I am stirring up your clear thinking faculties by way of a reminder,

[[v61-3-2]]

^<<v61-3-2,2>>^ that you should remember the sayings previously spoken^&#42;1^ by the holy prophets and the commandment of the Lord and Savior through your apostles.

[NOTE]
====
. Or “the things foretold.”
====

[[v61-3-3]]

^<<v61-3-3,3>>^ First of all know this, that in the last days ridiculers will come with their ridicule, proceeding according to their own desires

[[v61-3-4]]

^<<v61-3-4,4>>^ and saying: “Where is this promised presence of his? Why, from the day our forefathers fell asleep in death, all things are continuing exactly as they were from creation’s beginning.”

[[v61-3-5]]

^<<v61-3-5,5>>^ For they deliberately ignore this fact, that long ago there were heavens and an earth standing firmly out of water and in the midst of water by the word of God;

[[v61-3-6]]

^<<v61-3-6,6>>^ and that by those means the world of that time suffered destruction when it was flooded with water.

[[v61-3-7]]

^<<v61-3-7,7>>^ But by the same word the heavens and the earth that now exist are reserved for fire and are being kept until the day of judgment and of destruction of the ungodly people.

[[v61-3-8]]

^<<v61-3-8,8>>^ However, do not let this escape your notice, beloved ones, that one day is with Jehovah^&#42;1^ as a thousand years and a thousand years as one day.

[NOTE]
====
. See App. A5.
====

[[v61-3-9]]

^<<v61-3-9,9>>^ Jehovah^&#42;1^ is not slow concerning his promise, as some people consider slowness, but he is patient with you because he does not desire anyone to be destroyed but desires all to attain to repentance.

[NOTE]
====
. See App. A5.
====

[[v61-3-10]]

^<<v61-3-10,10>>^ But Jehovah’s^&#42;1^ day will come as a thief, in which the heavens will pass away with a roar,^&#42;2^ but the elements being intensely hot will be dissolved, and earth and the works in it will be exposed.

[NOTE]
====
. See App. A5.
. Or “a rushing sound.”
====

[[v61-3-11]]

^<<v61-3-11,11>>^ Since all these things are to be dissolved in this way, consider what sort of people you ought to be in holy acts of conduct and deeds of godly devotion,

[[v61-3-12]]

^<<v61-3-12,12>>^ as you await and keep close in mind^&#42;1^ the presence of the day of Jehovah,^&#42;2^ through which the heavens will be destroyed in flames and the elements will melt in the intense heat!

[NOTE]
====
. Or “eagerly desire.” Lit., “speed up.”
. See App. A5.
====

[[v61-3-13]]

^<<v61-3-13,13>>^ But there are new heavens and a new earth that we are awaiting according to his promise, and in these righteousness is to dwell.

[[v61-3-14]]

^<<v61-3-14,14>>^ Therefore, beloved ones, since you are awaiting these things, do your utmost to be found finally by him spotless and unblemished and in peace.

[[v61-3-15]]

^<<v61-3-15,15>>^ Furthermore, consider the patience of our Lord as salvation, just as our beloved brother Paul also wrote you according to the wisdom given him,

[[v61-3-16]]

^<<v61-3-16,16>>^ speaking about these things as he does in all his letters. However, some things in them are hard to understand, and these things the ignorant^&#42;1^ and unstable are twisting, as they do also the rest of the Scriptures, to their own destruction.

[NOTE]
====
. Or “untaught.”
====

[[v61-3-17]]

^<<v61-3-17,17>>^ You, therefore, beloved ones, having this advance knowledge, be on your guard so that you may not be led astray with them by the error of the lawless people and fall from your own steadfastness.^&#42;1^

[NOTE]
====
. Or “stability.”
====

[[v61-3-18]]

^<<v61-3-18,18>>^ No, but go on growing in the undeserved kindness and knowledge of our Lord and Savior Jesus Christ. To him be the glory both now and to the day of eternity. Amen.

'''

xref:061-2-peter/061-2-peter-002.adoc#v61-2-0[&#60; Capítulo Anterior] | <<v61-3-0,Topo>> | xref:062-1-john/062-1-john-001.adoc#v62-1-0[Próximo Capítulo &#62;]