include::./index.adoc[]

[[v18-31-0]]
=== Job, 31
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-31-1]]

^<<v18-31-1,1>>^ “I have made a covenant with my eyes.
So how could I show improper attention to a virgin?

[[v18-31-2]]

^<<v18-31-2,2>>^ What, then, would be my share from God above,
What inheritance from the Almighty on high?

[[v18-31-3]]

^<<v18-31-3,3>>^ Does not disaster await the wrongdoer
And calamity those doing what is harmful?

[[v18-31-4]]

^<<v18-31-4,4>>^ Does he not see my ways
And count all my steps?

[[v18-31-5]]

^<<v18-31-5,5>>^ Have I ever walked in untruth?^&#42;1^
Has my foot hurried to deceive?

[NOTE]
====
. Or possibly, “with men of untruth?”
====

[[v18-31-6]]

^<<v18-31-6,6>>^ Let God weigh me with accurate scales;
Then he will recognize my integrity.

[[v18-31-7]]

^<<v18-31-7,7>>^ If my footsteps deviate from the way
Or my heart has followed after my eyes
Or my hands have been defiled,

[[v18-31-8]]

^<<v18-31-8,8>>^ Then let me sow seed and someone else eat,
And let what I plant be uprooted.^&#42;1^

[NOTE]
====
. Or “let my descendants be rooted out.”
====

[[v18-31-9]]

^<<v18-31-9,9>>^ If my heart has been enticed by a woman
And I have lain in wait at my neighbor’s door,

[[v18-31-10]]

^<<v18-31-10,10>>^ Then let my wife grind grain for another man,
And let other men have sexual relations with her.^&#42;1^

[NOTE]
====
. Lit., “let other men kneel down over her.”
====

[[v18-31-11]]

^<<v18-31-11,11>>^ For that would be shameful conduct,
An error deserving punishment by the judges.

[[v18-31-12]]

^<<v18-31-12,12>>^ It would be a fire that would devour and destroy,^&#42;1^
Consuming even the roots of^&#42;2^ all my produce.

[NOTE]
====
. Lit., “eat (devour) to destruction.”
. Or “Uprooting.”
====

[[v18-31-13]]

^<<v18-31-13,13>>^ If I denied justice to my male or female servants
When they had a complaint^&#42;1^ against me,

[NOTE]
====
. Or “legal case.”
====

[[v18-31-14]]

^<<v18-31-14,14>>^ What can I do when God confronts me?^&#42;1^
What can I answer him when he calls for an accounting?

[NOTE]
====
. Lit., “rises up?”
====

[[v18-31-15]]

^<<v18-31-15,15>>^ Did not the One who made me in the womb also make them?
Was it not the same One who formed us before our birth?^&#42;1^

[NOTE]
====
. Lit., “in the womb.”
====

[[v18-31-16]]

^<<v18-31-16,16>>^ If I refused to give the poor what they desired
Or saddened the eyes of the widow;^&#42;1^

[NOTE]
====
. Lit., “caused the eyes of the widow to fail.”
====

[[v18-31-17]]

^<<v18-31-17,17>>^ If I ate my portion of food alone
Without sharing it with the orphans;

[[v18-31-18]]

^<<v18-31-18,18>>^ (For from my youth the orphan^&#42;1^ grew up with me as though I were his father,
And I have been a guide for the widow^&#42;2^ from childhood.^&#42;3^)

[NOTE]
====
. Lit., “he.”
. Lit., “her.”
. Lit., “from my mother’s womb.”
====

[[v18-31-19]]

^<<v18-31-19,19>>^ If I saw anyone perishing for lack of clothing
Or a poor man with nothing to cover himself;

[[v18-31-20]]

^<<v18-31-20,20>>^ If he^&#42;1^ did not bless me
As he warmed himself with the wool of my sheep;

[NOTE]
====
. Lit., “his loins.”
====

[[v18-31-21]]

^<<v18-31-21,21>>^ If I shook my fist against the orphan
When he needed my assistance in the city gate;^&#42;1^

[NOTE]
====
. Or possibly, “When I saw that I had support in the city gate.”
====

[[v18-31-22]]

^<<v18-31-22,22>>^ Then let my arm^&#42;1^ fall from my shoulder,
And let my arm be broken at the elbow.^&#42;2^

[NOTE]
====
. Or “shoulder blade.”
. Or “from its socket; from its upper bone.”
====

[[v18-31-23]]

^<<v18-31-23,23>>^ For I dreaded disaster from God,
And I could not stand before his dignity.

[[v18-31-24]]

^<<v18-31-24,24>>^ If I put my confidence in gold
Or said to fine gold, ‘You are my security!’

[[v18-31-25]]

^<<v18-31-25,25>>^ If I found my joy in my great wealth
Because of the many possessions I acquired;

[[v18-31-26]]

^<<v18-31-26,26>>^ If I saw the sun^&#42;1^ shining
Or the moon moving in its splendor;

[NOTE]
====
. Lit., “light.”
====

[[v18-31-27]]

^<<v18-31-27,27>>^ And my heart was secretly enticed,
And my mouth kissed my hand in worship of them;

[[v18-31-28]]

^<<v18-31-28,28>>^ Then that would be an error deserving punishment by the judges,
For I would have denied the true God above.

[[v18-31-29]]

^<<v18-31-29,29>>^ Have I ever rejoiced over the destruction of my enemy
Or gloated because evil befell him?

[[v18-31-30]]

^<<v18-31-30,30>>^ I never allowed my mouth to sin
By asking for his life^&#42;1^ in an oath.

[NOTE]
====
. Or “soul.”
====

[[v18-31-31]]

^<<v18-31-31,31>>^ Have the men of my tent not said,
‘Who can find anyone who has not been satisfied with his food?’^&#42;1^

[NOTE]
====
. Lit., “meat.”
====

[[v18-31-32]]

^<<v18-31-32,32>>^ No stranger^&#42;1^ had to spend the night outside;
I opened my doors to the traveler.

[NOTE]
====
. Or “foreign resident.”
====

[[v18-31-33]]

^<<v18-31-33,33>>^ Have I ever tried to cover over my transgressions, like other men,
By hiding my error in the pocket of my garment?

[[v18-31-34]]

^<<v18-31-34,34>>^ Have I been in fear of the reaction of the multitude,
Or have I been terrified by the contempt of other families,
Making me silent and afraid to go outside?

[[v18-31-35]]

^<<v18-31-35,35>>^ If only someone would listen to me!
I would sign my name to what I have said.^&#42;1^
Let the Almighty answer me!
If only my accuser had written out the charges in a document!

[NOTE]
====
. Or “Here is my signature.”
====

[[v18-31-36]]

^<<v18-31-36,36>>^ I would carry it on my shoulder,
And I would bind it around my head like a crown.

[[v18-31-37]]

^<<v18-31-37,37>>^ I would give him an accounting for every step I took;
I would approach him confidently, like a prince.

[[v18-31-38]]

^<<v18-31-38,38>>^ If my own ground would cry out against me
And its furrows would weep together;

[[v18-31-39]]

^<<v18-31-39,39>>^ If I have eaten its fruitage without payment,
Or if I have caused its owners^&#42;1^ to despair;

[NOTE]
====
. Or “the soul of its owners.”
====

[[v18-31-40]]

^<<v18-31-40,40>>^ Then let thorns sprout for me instead of wheat
And foul-smelling weeds instead of barley.”
The words of Job end here.

'''

xref:018-job/018-job-030.adoc#v18-30-0[&#60; Capítulo Anterior] | <<v18-31-0,Topo>> | xref:018-job/018-job-032.adoc#v18-32-0[Próximo Capítulo &#62;]