include::./index.adoc[]

[[v18-16-0]]
=== Job, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-16-1]]

^<<v18-16-1,1>>^ Job said in reply:

[[v18-16-2]]

^<<v18-16-2,2>>^ “I have heard many things like these before.
All of you are troublesome comforters!

[[v18-16-3]]

^<<v18-16-3,3>>^ Is there an end to empty^&#42;1^ words?
What provokes you to answer this way?

[NOTE]
====
. Or “blustery.”
====

[[v18-16-4]]

^<<v18-16-4,4>>^ I could also speak as you do.
If you were in my place,^&#42;1^
I could make persuasive speeches against you
And shake my head at you.

[NOTE]
====
. Or “If your soul were in place of my soul.”
====

[[v18-16-5]]

^<<v18-16-5,5>>^ Instead, though, I would strengthen you with the words of my mouth,
And the consolation of my lips would bring relief.

[[v18-16-6]]

^<<v18-16-6,6>>^ If I speak, my own pain is not relieved,
And if I stop speaking, how much is my pain reduced?

[[v18-16-7]]

^<<v18-16-7,7>>^ But now he has made me weary;
He has devastated my whole household.^&#42;1^

[NOTE]
====
. Or “those assembling with me.”
====

[[v18-16-8]]

^<<v18-16-8,8>>^ You also seize me, and it has become a witness,
So that my own skinniness rises up and testifies to my face.

[[v18-16-9]]

^<<v18-16-9,9>>^ His anger has torn me to pieces, and he harbors animosity against me.
He grinds his teeth against me.
My adversary pierces me with his eyes.

[[v18-16-10]]

^<<v18-16-10,10>>^ They have opened their mouth wide against me,
And they have scornfully struck my cheeks;
In large numbers they gather against me.

[[v18-16-11]]

^<<v18-16-11,11>>^ God hands me over to young boys,
And he thrusts me into the hands of the wicked.

[[v18-16-12]]

^<<v18-16-12,12>>^ I was untroubled, but he shattered me;
He grabbed me by the back of the neck and crushed me;
Then he set me up as his target.

[[v18-16-13]]

^<<v18-16-13,13>>^ His archers surround me;
He pierces my kidneys and feels no compassion;
He pours out my gall on the earth.

[[v18-16-14]]

^<<v18-16-14,14>>^ He breaks through against me with breach after breach;
He rushes at me like a warrior.

[[v18-16-15]]

^<<v18-16-15,15>>^ I have sewn sackcloth together to cover my skin,
And I have buried my dignity^&#42;1^ in the dust.

[NOTE]
====
. Or “strength.” Lit., “horn.”
====

[[v18-16-16]]

^<<v18-16-16,16>>^ My face is red from weeping,
And on my eyelids is deep shadow,^&#42;1^

[NOTE]
====
. Or “death’s shadow.”
====

[[v18-16-17]]

^<<v18-16-17,17>>^ Although my hands have done no violence
And my prayer is pure.

[[v18-16-18]]

^<<v18-16-18,18>>^ O earth, do not cover my blood!
And let there be no resting-place for my outcry!

[[v18-16-19]]

^<<v18-16-19,19>>^ Even now, my witness is in the heavens;
The one who can testify for me is in the heights.

[[v18-16-20]]

^<<v18-16-20,20>>^ My companions ridicule me
As my eye sheds tears^&#42;1^ to God.

[NOTE]
====
. Or possibly, “looks sleeplessly.”
====

[[v18-16-21]]

^<<v18-16-21,21>>^ Let someone arbitrate between a man and God,
As one would between a man and his fellow.

[[v18-16-22]]

^<<v18-16-22,22>>^ For the years to come are few,
And I will go away on the path of no return.

'''

xref:018-job/018-job-015.adoc#v18-15-0[&#60; Capítulo Anterior] | <<v18-16-0,Topo>> | xref:018-job/018-job-017.adoc#v18-17-0[Próximo Capítulo &#62;]