include::./index.adoc[]

[[v18-17-0]]
=== Job, 17
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-17-1]]

^<<v18-17-1,1>>^ “My spirit has been broken, my days have been extinguished;
The graveyard awaits me.

[[v18-17-2]]

^<<v18-17-2,2>>^ Mockers surround me,
And my eye must gaze at^&#42;1^ their rebellious behavior.

[NOTE]
====
. Or “dwell on.”
====

[[v18-17-3]]

^<<v18-17-3,3>>^ Please accept my security, and keep it with you.
Who else will shake hands with me and pledge in my behalf?

[[v18-17-4]]

^<<v18-17-4,4>>^ For you have concealed discernment from their heart;
That is why you do not exalt them.

[[v18-17-5]]

^<<v18-17-5,5>>^ He may offer to share with his friends,
While the eyes of his children fail.

[[v18-17-6]]

^<<v18-17-6,6>>^ He has made me an object of scorn^&#42;1^ among the peoples,
So that I became one in whose face they spit.

[NOTE]
====
. Lit., “a proverb; a byword.”
====

[[v18-17-7]]

^<<v18-17-7,7>>^ From anguish my eyes grow dim,
And all my limbs are but a shadow.

[[v18-17-8]]

^<<v18-17-8,8>>^ Upright people stare in amazement at this,
And the innocent one is disturbed over the godless.^&#42;1^

[NOTE]
====
. Or “the apostate.”
====

[[v18-17-9]]

^<<v18-17-9,9>>^ The righteous one keeps holding fast to his way,
And the one with clean hands grows stronger.

[[v18-17-10]]

^<<v18-17-10,10>>^ However, you may all come and resume your arguing,
For I have not found anyone wise among you.

[[v18-17-11]]

^<<v18-17-11,11>>^ My days are finished;
My plans, the desires of my heart, have been shattered.

[[v18-17-12]]

^<<v18-17-12,12>>^ They keep turning night into day,
Saying, ‘Light must be near because it is dark.’

[[v18-17-13]]

^<<v18-17-13,13>>^ If I wait, the Grave^&#42;1^ will become my home;
I will spread out my bed in darkness.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v18-17-14]]

^<<v18-17-14,14>>^ I will call out to the pit,^&#42;1^ ‘You are my father!’
To the maggot, ‘My mother and my sister!’

[NOTE]
====
. Or “grave.”
====

[[v18-17-15]]

^<<v18-17-15,15>>^ Where, then, is my hope?
Who can see hope for me?

[[v18-17-16]]

^<<v18-17-16,16>>^ It^&#42;1^ will go down to the barred gates of the Grave^&#42;2^
When we all descend together into the dust.”

[NOTE]
====
. That is, my hope.
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

'''

xref:018-job/018-job-016.adoc#v18-16-0[&#60; Capítulo Anterior] | <<v18-17-0,Topo>> | xref:018-job/018-job-018.adoc#v18-18-0[Próximo Capítulo &#62;]