include::./index.adoc[]

[[v18-40-0]]
=== Job, 40
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-40-1]]

^<<v18-40-1,1>>^ Jehovah continued to answer Job:

[[v18-40-2]]

^<<v18-40-2,2>>^ “Should a faultfinder contend with the Almighty?
Let the one who wants to reprove God answer.”

[[v18-40-3]]

^<<v18-40-3,3>>^ Job said in answer to Jehovah:

[[v18-40-4]]

^<<v18-40-4,4>>^ “Look! I am unworthy.
What can I reply to you?
I put my hand over my mouth.

[[v18-40-5]]

^<<v18-40-5,5>>^ I spoke once, but I will not answer again;
Twice, but I will say no more.”

[[v18-40-6]]

^<<v18-40-6,6>>^ Then Jehovah answered Job out of the windstorm:

[[v18-40-7]]

^<<v18-40-7,7>>^ “Brace yourself, please, like a man;
I will question you, and you inform me.

[[v18-40-8]]

^<<v18-40-8,8>>^ Will you call into question^&#42;1^ my justice?
Will you condemn me so that you may be right?

[NOTE]
====
. Or “invalidate.”
====

[[v18-40-9]]

^<<v18-40-9,9>>^ Do you have an arm as powerful as the true God’s,
Or can your voice thunder like his?

[[v18-40-10]]

^<<v18-40-10,10>>^ Adorn yourself, please, with glory and majesty;
Clothe yourself with dignity and splendor.

[[v18-40-11]]

^<<v18-40-11,11>>^ Release the fury of your anger;
Look at everyone who is haughty, and bring him low.

[[v18-40-12]]

^<<v18-40-12,12>>^ Look at everyone who is haughty, and humble him,
And tread down the wicked where they stand.

[[v18-40-13]]

^<<v18-40-13,13>>^ Hide them all in the dust;
Bind them^&#42;1^ in the hidden place,

[NOTE]
====
. Lit., “their faces.”
====

[[v18-40-14]]

^<<v18-40-14,14>>^ Then even I would acknowledge to you^&#42;1^
That your right hand can save you.

[NOTE]
====
. Or “commend you.”
====

[[v18-40-15]]

^<<v18-40-15,15>>^ Here, now, is Be·heʹmoth,^&#42;1^ which I made as I made you.
It eats grass like a bull.

[NOTE]
====
. Possibly the hippopotamus.
====

[[v18-40-16]]

^<<v18-40-16,16>>^ Look at the strength in its hips
And the power in the muscles of its belly!

[[v18-40-17]]

^<<v18-40-17,17>>^ It stiffens its tail like a cedar;
The sinews of its thighs are woven together.

[[v18-40-18]]

^<<v18-40-18,18>>^ Its bones are tubes of copper;
Its limbs are like wrought-iron rods.

[[v18-40-19]]

^<<v18-40-19,19>>^ It ranks first^&#42;1^ among the works of God;
Only its Maker can approach it with his sword.

[NOTE]
====
. Lit., “It is the beginning.”
====

[[v18-40-20]]

^<<v18-40-20,20>>^ For the mountains produce food for it,
Where all the wild animals play.

[[v18-40-21]]

^<<v18-40-21,21>>^ It lies down under the lotus trees,
In the shelter of the reeds of the marsh.

[[v18-40-22]]

^<<v18-40-22,22>>^ The lotus trees cast their shadow on it,
And the poplars of the valley^&#42;1^ surround it.

[NOTE]
====
. Or “wadi.”
====

[[v18-40-23]]

^<<v18-40-23,23>>^ If the river is turbulent, it does not panic.
It is confident, although the Jordan rushes against its mouth.

[[v18-40-24]]

^<<v18-40-24,24>>^ Can anyone capture it while it is watching,
Or pierce its nose with a hook?^&#42;1^

[NOTE]
====
. Lit., “snare.”
====

'''

xref:018-job/018-job-039.adoc#v18-39-0[&#60; Capítulo Anterior] | <<v18-40-0,Topo>> | xref:018-job/018-job-041.adoc#v18-41-0[Próximo Capítulo &#62;]