include::./index.adoc[]

[[v18-22-0]]
=== Job, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-22-1]]

^<<v18-22-1,1>>^ Elʹi·phaz the Teʹman·ite said in reply:

[[v18-22-2]]

^<<v18-22-2,2>>^ “Can a man be of use to God?
Can anyone with insight be of benefit to him?

[[v18-22-3]]

^<<v18-22-3,3>>^ Does the Almighty care^&#42;1^ that you are righteous,
Or does he gain anything because you follow the course of integrity?

[NOTE]
====
. Or “Does it delight the Almighty.”
====

[[v18-22-4]]

^<<v18-22-4,4>>^ Will he punish you
And enter into judgment with you for your reverence?

[[v18-22-5]]

^<<v18-22-5,5>>^ Is it not because your own wickedness is so great
And there is no end to your errors?

[[v18-22-6]]

^<<v18-22-6,6>>^ For you seize a pledge from your brothers for no reason,
And you strip people of their garments, leaving them naked.^&#42;1^

[NOTE]
====
. Lit., “strip off garments of the naked.”
====

[[v18-22-7]]

^<<v18-22-7,7>>^ You do not give the tired one a drink of water,
And you hold back food from the hungry.

[[v18-22-8]]

^<<v18-22-8,8>>^ The land belongs to the powerful man,
And the favored one dwells in it.

[[v18-22-9]]

^<<v18-22-9,9>>^ But you sent away widows empty-handed,
And you crushed the arms of fatherless children.^&#42;1^

[NOTE]
====
. Or “of orphans.”
====

[[v18-22-10]]

^<<v18-22-10,10>>^ That is why you are surrounded by traps,^&#42;1^
And sudden terrors frighten you;

[NOTE]
====
. Lit., “bird traps.”
====

[[v18-22-11]]

^<<v18-22-11,11>>^ That is why it is so dark that you cannot see,
And a flood of water covers you.

[[v18-22-12]]

^<<v18-22-12,12>>^ Is not God in the heights of heaven?
And see how high all the stars are.

[[v18-22-13]]

^<<v18-22-13,13>>^ But you have said: ‘What does God really know?
Can he judge through thick gloom?

[[v18-22-14]]

^<<v18-22-14,14>>^ Clouds screen him off so that he does not see
As he walks about on the vault^&#42;1^ of heaven.’

[NOTE]
====
. Or “circle.”
====

[[v18-22-15]]

^<<v18-22-15,15>>^ Will you follow the ancient path
That wicked men have walked,

[[v18-22-16]]

^<<v18-22-16,16>>^ Men who have been snatched away^&#42;1^ before their time,
Whose foundation was washed away by a flood?^&#42;2^

[NOTE]
====
. Or “whose lives were cut short.”
. Lit., “river.”
====

[[v18-22-17]]

^<<v18-22-17,17>>^ They were saying to the true God: ‘Leave us alone!’
And ‘What can the Almighty do to us?’

[[v18-22-18]]

^<<v18-22-18,18>>^ Yet, he is the One who filled their houses with good things.
(Such wicked thinking is far from my own.)

[[v18-22-19]]

^<<v18-22-19,19>>^ The righteous will see this and rejoice,
And the innocent will mock them and say:

[[v18-22-20]]

^<<v18-22-20,20>>^ ‘Our opponents have been destroyed,
And a fire will consume what is left of them.’

[[v18-22-21]]

^<<v18-22-21,21>>^ Get to know Him, and you will be at peace;
Then good things will come your way.

[[v18-22-22]]

^<<v18-22-22,22>>^ Accept the law from his mouth,
And keep his sayings in your heart.

[[v18-22-23]]

^<<v18-22-23,23>>^ If you return to the Almighty, you will be restored;
If you remove unrighteousness from your tent,

[[v18-22-24]]

^<<v18-22-24,24>>^ If you would throw your gold^&#42;1^ into the dust
And the gold of Oʹphir into the rocky ravines,^&#42;2^

[NOTE]
====
. Or “gold nuggets.”
. Or “wadis.”
====

[[v18-22-25]]

^<<v18-22-25,25>>^ Then the Almighty will become your gold,^&#42;1^
And he will be your choicest silver.

[NOTE]
====
. Or “gold nuggets.”
====

[[v18-22-26]]

^<<v18-22-26,26>>^ For then your delight will be in the Almighty,
And you will lift up your face to God.

[[v18-22-27]]

^<<v18-22-27,27>>^ You will entreat him, and he will hear you;
And your vows you will pay.

[[v18-22-28]]

^<<v18-22-28,28>>^ Whatever you decide to do will succeed,
And light will shine upon your path.

[[v18-22-29]]

^<<v18-22-29,29>>^ For you will be humiliated when you speak arrogantly,
But he will save the humble.^&#42;1^

[NOTE]
====
. Or “the one with downcast eyes.”
====

[[v18-22-30]]

^<<v18-22-30,30>>^ He will rescue those who are innocent;
So if your hands are clean, you will certainly be rescued.”

'''

xref:018-job/018-job-021.adoc#v18-21-0[&#60; Capítulo Anterior] | <<v18-22-0,Topo>> | xref:018-job/018-job-023.adoc#v18-23-0[Próximo Capítulo &#62;]