include::./index.adoc[]

[[v18-37-0]]
=== Job, 37
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-37-1]]

^<<v18-37-1,1>>^ “At this my heart pounds
And leaps from its place.

[[v18-37-2]]

^<<v18-37-2,2>>^ Listen carefully to the rumbling of his voice
And the thunder that comes from his mouth.

[[v18-37-3]]

^<<v18-37-3,3>>^ He unleashes it under the entire heavens
And sends his lightning to the ends of the earth.

[[v18-37-4]]

^<<v18-37-4,4>>^ After that is a roaring sound;
He thunders with a majestic voice,
And he does not hold it back when his voice is heard.

[[v18-37-5]]

^<<v18-37-5,5>>^ God thunders with his voice in a wonderful way;
He does great things that are beyond our understanding.

[[v18-37-6]]

^<<v18-37-6,6>>^ For he says to the snow, ‘Fall to the earth,’
And to the downpour of rain, ‘Pour down mightily.’

[[v18-37-7]]

^<<v18-37-7,7>>^ God puts a stop to all human activity^&#42;1^
So that every mortal man will know His work.

[NOTE]
====
. Lit., “puts a seal on the hand of every human.”
====

[[v18-37-8]]

^<<v18-37-8,8>>^ The wild animals go into their dens
And remain in their lairs.

[[v18-37-9]]

^<<v18-37-9,9>>^ The storm wind blows from its chamber,
And the cold comes from the north winds.

[[v18-37-10]]

^<<v18-37-10,10>>^ By the breath of God, the ice is produced,
And the broad waters are frozen solid.

[[v18-37-11]]

^<<v18-37-11,11>>^ Yes, he weighs down the clouds with moisture;
He scatters his lightning in the clouds;

[[v18-37-12]]

^<<v18-37-12,12>>^ They swirl around where he directs them;
They carry out whatever he commands on the surface of the inhabited earth.^&#42;1^

[NOTE]
====
. Or “of the productive land of the earth.”
====

[[v18-37-13]]

^<<v18-37-13,13>>^ Whether it is for punishment^&#42;1^ or for the sake of the land
Or for loyal love, he causes it to happen.

[NOTE]
====
. Lit., “a rod.”
====

[[v18-37-14]]

^<<v18-37-14,14>>^ Listen to this, Job;
Stop and consider carefully the wonderful works of God.

[[v18-37-15]]

^<<v18-37-15,15>>^ Do you know how God controls^&#42;1^ the clouds
And how he causes the lightning to flash from his cloud?

[NOTE]
====
. Or “commands.”
====

[[v18-37-16]]

^<<v18-37-16,16>>^ Do you know how the clouds float?
These are the wonderful works of the One perfect in knowledge.

[[v18-37-17]]

^<<v18-37-17,17>>^ Why does your clothing become hot
When the earth is still because of the south wind?

[[v18-37-18]]

^<<v18-37-18,18>>^ Can you, with him, spread out^&#42;1^ the skies
As solid as a metal mirror?

[NOTE]
====
. Or “beat out.”
====

[[v18-37-19]]

^<<v18-37-19,19>>^ Tell us what we should say to him;
We cannot answer because we are in the dark.

[[v18-37-20]]

^<<v18-37-20,20>>^ Should he be told that I want to speak?
Or has anyone said something that should be communicated to him?

[[v18-37-21]]

^<<v18-37-21,21>>^ They cannot even see the light,^&#42;1^
Though it is bright in the sky,
Until a wind passes by and clears away the clouds.

[NOTE]
====
. That is, of the sun.
====

[[v18-37-22]]

^<<v18-37-22,22>>^ Out of the north comes golden splendor;
God’s majesty is awe-inspiring.

[[v18-37-23]]

^<<v18-37-23,23>>^ Understanding the Almighty is beyond our reach;
He is great in power,
And he never violates his justice and abundant righteousness.

[[v18-37-24]]

^<<v18-37-24,24>>^ Therefore, people should fear him.
For he does not favor any who think that they are wise.”^&#42;1^

[NOTE]
====
. Lit., “who are wise of heart.”
====

'''

xref:018-job/018-job-036.adoc#v18-36-0[&#60; Capítulo Anterior] | <<v18-37-0,Topo>> | xref:018-job/018-job-038.adoc#v18-38-0[Próximo Capítulo &#62;]