include::./index.adoc[]

[[v18-20-0]]
=== Job, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-20-1]]

^<<v18-20-1,1>>^ Zoʹphar the Naʹa·ma·thite said in reply:

[[v18-20-2]]

^<<v18-20-2,2>>^ “This is why my own troubling thoughts urge me to answer
Because of the agitation I feel.

[[v18-20-3]]

^<<v18-20-3,3>>^ I have heard a reproof that insults me;
And my understanding^&#42;1^ impels me to reply.

[NOTE]
====
. Lit., “a spirit from my understanding.”
====

[[v18-20-4]]

^<<v18-20-4,4>>^ Surely you must have always known this,
For it has been so since man^&#42;1^ was put on the earth,

[NOTE]
====
. Or “mankind; Adam.”
====

[[v18-20-5]]

^<<v18-20-5,5>>^ That the joyful cry of the wicked is brief
And the rejoicing of the godless one^&#42;1^ is for a moment.

[NOTE]
====
. Or “the apostate.”
====

[[v18-20-6]]

^<<v18-20-6,6>>^ Although his greatness ascends to heaven
And his head reaches to the clouds,

[[v18-20-7]]

^<<v18-20-7,7>>^ He will perish forever like his own dung;
Those who used to see him will say, ‘Where is he?’

[[v18-20-8]]

^<<v18-20-8,8>>^ He will fly off like a dream, and they will not find him;
He will be chased away like a vision of the night.

[[v18-20-9]]

^<<v18-20-9,9>>^ The eye that once saw him will not do so again,
And his place will behold him no more.

[[v18-20-10]]

^<<v18-20-10,10>>^ His own children will seek the favor of the poor,
And his own hands will give back his wealth.

[[v18-20-11]]

^<<v18-20-11,11>>^ His bones were full of youthful vigor,
But it^&#42;1^ will lie down with him in mere dust.

[NOTE]
====
. That is, his vigor.
====

[[v18-20-12]]

^<<v18-20-12,12>>^ If what is bad tastes sweet in his mouth,
If he hides it under his tongue,

[[v18-20-13]]

^<<v18-20-13,13>>^ If he savors it and does not let it go
But keeps holding it in his mouth,

[[v18-20-14]]

^<<v18-20-14,14>>^ His food will turn sour inside him;
It will become like the poison^&#42;1^ of cobras within him.

[NOTE]
====
. Or “gall.”
====

[[v18-20-15]]

^<<v18-20-15,15>>^ He has swallowed down wealth, but he will vomit it up;
God will empty it out of his belly.

[[v18-20-16]]

^<<v18-20-16,16>>^ The venom of cobras he will suck;
The fangs^&#42;1^ of a viper will kill him.

[NOTE]
====
. Lit., “tongue.”
====

[[v18-20-17]]

^<<v18-20-17,17>>^ He will never see the streams of water,
The torrents of honey and butter.

[[v18-20-18]]

^<<v18-20-18,18>>^ He will give back his goods without consuming them;^&#42;1^
He will not enjoy the wealth from his trade.

[NOTE]
====
. Lit., “and he will not swallow.”
====

[[v18-20-19]]

^<<v18-20-19,19>>^ For he has crushed and abandoned the poor;
He has seized a house that he did not build.

[[v18-20-20]]

^<<v18-20-20,20>>^ But he will feel no peace within himself;
His wealth will not help him escape.

[[v18-20-21]]

^<<v18-20-21,21>>^ There is nothing left for him to devour;
That is why his prosperity will not last.

[[v18-20-22]]

^<<v18-20-22,22>>^ When his wealth reaches its peak, anxiety will overtake him;
The full force of misfortune will come against him.

[[v18-20-23]]

^<<v18-20-23,23>>^ As he fills his belly,
God^&#42;1^ will send his burning anger upon him,
Raining it down upon him into his bowels.

[NOTE]
====
. Lit., “He.”
====

[[v18-20-24]]

^<<v18-20-24,24>>^ When he flees from weapons of iron,
Arrows from a copper bow will pierce him.

[[v18-20-25]]

^<<v18-20-25,25>>^ He pulls an arrow from his back,
A glittering weapon from his gall,
And terror seizes him.

[[v18-20-26]]

^<<v18-20-26,26>>^ Total darkness awaits his treasures;
A fire that no one fanned will consume him;
Calamity awaits any survivors in his tent.

[[v18-20-27]]

^<<v18-20-27,27>>^ Heaven will uncover his error;
The earth will rise up against him.

[[v18-20-28]]

^<<v18-20-28,28>>^ A flood will sweep his house away;
It will be a heavy torrent on the day of God’s^&#42;1^ anger.

[NOTE]
====
. Lit., “his.”
====

[[v18-20-29]]

^<<v18-20-29,29>>^ This is the wicked man’s share from God,
The inheritance that God has decreed for him.”

'''

xref:018-job/018-job-019.adoc#v18-19-0[&#60; Capítulo Anterior] | <<v18-20-0,Topo>> | xref:018-job/018-job-021.adoc#v18-21-0[Próximo Capítulo &#62;]