include::./index.adoc[]

[[v18-28-0]]
=== Job, 28
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-28-1]]

^<<v18-28-1,1>>^ “There is a place to mine silver
And a place for gold that they refine;

[[v18-28-2]]

^<<v18-28-2,2>>^ Iron is taken from the ground,
And copper is smelted^&#42;1^ from rocks.

[NOTE]
====
. Lit., “poured.”
====

[[v18-28-3]]

^<<v18-28-3,3>>^ Man conquers the darkness;
He probes to the limit in the gloom and darkness,
Searching for ore.^&#42;1^

[NOTE]
====
. Lit., “stone.”
====

[[v18-28-4]]

^<<v18-28-4,4>>^ He sinks a shaft far from where people reside,
In forgotten places, far from where people walk;
Some men descend and swing suspended.

[[v18-28-5]]

^<<v18-28-5,5>>^ Food grows on top of the earth;
But below, there is an upheaval as if by fire.^&#42;1^

[NOTE]
====
. Apparently a reference to mining operations.
====

[[v18-28-6]]

^<<v18-28-6,6>>^ There in the stones is sapphire,
And the dust contains gold.

[[v18-28-7]]

^<<v18-28-7,7>>^ No bird of prey knows the path to it;
The eye of a black kite has not seen it.

[[v18-28-8]]

^<<v18-28-8,8>>^ No majestic beasts have trodden on it;
The young lion has not prowled there.

[[v18-28-9]]

^<<v18-28-9,9>>^ Man strikes the flinty rock with his hand;
He overturns the mountains at their foundation.

[[v18-28-10]]

^<<v18-28-10,10>>^ He cuts water channels in the rock;
His eyes spot every precious thing.

[[v18-28-11]]

^<<v18-28-11,11>>^ He dams up the sources of rivers
And brings what was hidden to the light.

[[v18-28-12]]

^<<v18-28-12,12>>^ But wisdom—where can it be found,
And where is the source of understanding?

[[v18-28-13]]

^<<v18-28-13,13>>^ No man recognizes its value,
And it cannot be found in the land of the living.

[[v18-28-14]]

^<<v18-28-14,14>>^ The deep waters say, ‘It is not in me!’
And the sea says, ‘It is not with me!’

[[v18-28-15]]

^<<v18-28-15,15>>^ It cannot be bought with pure gold;
Nor can silver be weighed out in exchange for it.

[[v18-28-16]]

^<<v18-28-16,16>>^ It cannot be bought with gold of Oʹphir
Nor with rare onyx and sapphire.

[[v18-28-17]]

^<<v18-28-17,17>>^ Gold and glass cannot be compared to it;
Nor can a vessel of fine^&#42;1^ gold be exchanged for it.

[NOTE]
====
. Or “refined.”
====

[[v18-28-18]]

^<<v18-28-18,18>>^ Coral and crystal are not worthy of mention,
For a bagful of wisdom is worth more than one full of pearls.

[[v18-28-19]]

^<<v18-28-19,19>>^ The topaz of Cush cannot be compared to it;
It cannot be purchased even with pure gold.

[[v18-28-20]]

^<<v18-28-20,20>>^ But from where does wisdom come,
And where is the source of understanding?

[[v18-28-21]]

^<<v18-28-21,21>>^ It has been hidden from the eyes of every living thing
And concealed from the birds of the heavens.

[[v18-28-22]]

^<<v18-28-22,22>>^ Destruction and death say,
‘Our ears have heard only a report of it.’

[[v18-28-23]]

^<<v18-28-23,23>>^ God understands the way to find it;
He alone knows where it resides,

[[v18-28-24]]

^<<v18-28-24,24>>^ For he looks to the ends of the earth,
And he sees everything under the heavens.

[[v18-28-25]]

^<<v18-28-25,25>>^ When he set the force^&#42;1^ of the wind
And measured out the waters,

[NOTE]
====
. Lit., “weight.”
====

[[v18-28-26]]

^<<v18-28-26,26>>^ When he made a regulation for the rain
And a path for the thunderous storm cloud,

[[v18-28-27]]

^<<v18-28-27,27>>^ Then he saw wisdom and explained it;
He established and tested it.

[[v18-28-28]]

^<<v18-28-28,28>>^ And he said to man:
‘Look! The fear of Jehovah—that is wisdom,
And to turn away from bad is understanding.’”

'''

xref:018-job/018-job-027.adoc#v18-27-0[&#60; Capítulo Anterior] | <<v18-28-0,Topo>> | xref:018-job/018-job-029.adoc#v18-29-0[Próximo Capítulo &#62;]