include::./index.adoc[]

[[v18-36-0]]
=== Job, 36
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-36-1]]

^<<v18-36-1,1>>^ E·liʹhu continued:

[[v18-36-2]]

^<<v18-36-2,2>>^ “Be patient with me a little longer while I explain,
For I still have words to speak on God’s behalf.

[[v18-36-3]]

^<<v18-36-3,3>>^ I will speak comprehensively about what I know,
And I will ascribe righteousness to my Maker.

[[v18-36-4]]

^<<v18-36-4,4>>^ Truly my words are not false;
The One perfect in knowledge is here before you.

[[v18-36-5]]

^<<v18-36-5,5>>^ Indeed, God is mighty and rejects no one;
He is great in his power of understanding.^&#42;1^

[NOTE]
====
. Lit., “heart.”
====

[[v18-36-6]]

^<<v18-36-6,6>>^ He will not preserve the lives of the wicked,
But he gives justice to the afflicted.

[[v18-36-7]]

^<<v18-36-7,7>>^ He does not take his eyes off the righteous;
He enthrones them with kings,^&#42;1^ and they are exalted forever.

[NOTE]
====
. Or possibly, “He enthrones kings.”
====

[[v18-36-8]]

^<<v18-36-8,8>>^ But if they are bound in shackles
And caught in ropes of affliction,

[[v18-36-9]]

^<<v18-36-9,9>>^ He reveals to them what they have done,
Their transgressions caused by their pride.

[[v18-36-10]]

^<<v18-36-10,10>>^ He opens their ears to correction
And tells them to turn away from wrongdoing.

[[v18-36-11]]

^<<v18-36-11,11>>^ If they obey and serve him,
They will live out their days in prosperity,
And their years will be pleasant.

[[v18-36-12]]

^<<v18-36-12,12>>^ But if they do not obey, they will perish by the sword^&#42;1^
And die without knowledge.

[NOTE]
====
. Or “by a weapon (missile).”
====

[[v18-36-13]]

^<<v18-36-13,13>>^ The godless^&#42;1^ at heart will harbor resentment.
They do not cry for help even when he binds them.

[NOTE]
====
. Or “apostate.”
====

[[v18-36-14]]

^<<v18-36-14,14>>^ They die^&#42;1^ while still young,
Spending^&#42;2^ their life among male temple prostitutes.

[NOTE]
====
. Or “Their soul dies.”
. Or possibly, “Ending.”
====

[[v18-36-15]]

^<<v18-36-15,15>>^ But God^&#42;1^ rescues the afflicted during their affliction;
He opens their ear when they are oppressed.

[NOTE]
====
. Lit., “He.”
====

[[v18-36-16]]

^<<v18-36-16,16>>^ He draws you away from the brink of distress
To a broad space, free of restriction,
With rich food on your table as consolation.

[[v18-36-17]]

^<<v18-36-17,17>>^ Then you will be satisfied with the judgment on the wicked,
When judgment is rendered and justice is upheld.

[[v18-36-18]]

^<<v18-36-18,18>>^ But take care that rage does not lead you into spitefulness,^&#42;1^
And do not let a large bribe lead you astray.

[NOTE]
====
. Or “spiteful handclapping.”
====

[[v18-36-19]]

^<<v18-36-19,19>>^ Would your cry for help
Or any of your strenuous efforts keep you from distress?

[[v18-36-20]]

^<<v18-36-20,20>>^ Do not long for the night,
When people vanish from their place.

[[v18-36-21]]

^<<v18-36-21,21>>^ Beware that you do not turn to wrongdoing,
Choosing this instead of affliction.

[[v18-36-22]]

^<<v18-36-22,22>>^ Look! God is exalted in his power;
What instructor is like him?

[[v18-36-23]]

^<<v18-36-23,23>>^ Who has directed^&#42;1^ his way
Or said to him, ‘What you have done is wrong’?

[NOTE]
====
. Or possibly, “criticized; called him to account for.”
====

[[v18-36-24]]

^<<v18-36-24,24>>^ Remember to magnify his activity,
Of which men have sung.

[[v18-36-25]]

^<<v18-36-25,25>>^ All mankind has seen it,
Mortal man looks on from a distance.

[[v18-36-26]]

^<<v18-36-26,26>>^ Yes, God is greater than we can know;
The number of his years is beyond comprehension.^&#42;1^

[NOTE]
====
. Or “is unsearchable.”
====

[[v18-36-27]]

^<<v18-36-27,27>>^ He draws up the drops of water;
They condense into rain from his mist;

[[v18-36-28]]

^<<v18-36-28,28>>^ Then the clouds pour it down;
They shower down upon mankind.

[[v18-36-29]]

^<<v18-36-29,29>>^ Can anyone understand the layers of clouds,
The thundering from his tent?^&#42;1^

[NOTE]
====
. Lit., “booth.”
====

[[v18-36-30]]

^<<v18-36-30,30>>^ See how he spreads his lightning^&#42;1^ over it
And covers the depths^&#42;2^ of the sea.

[NOTE]
====
. Lit., “light.”
. Lit., “roots.”
====

[[v18-36-31]]

^<<v18-36-31,31>>^ By these he sustains^&#42;1^ the peoples;
He gives them food in abundance.

[NOTE]
====
. Or possibly, “pleads the cause of.”
====

[[v18-36-32]]

^<<v18-36-32,32>>^ With his hands he covers the lightning,
And he directs it against its target.

[[v18-36-33]]

^<<v18-36-33,33>>^ His thunder tells about him,
Even the livestock tell who^&#42;1^ is coming.

[NOTE]
====
. Or possibly, “what.”
====

'''

xref:018-job/018-job-035.adoc#v18-35-0[&#60; Capítulo Anterior] | <<v18-36-0,Topo>> | xref:018-job/018-job-037.adoc#v18-37-0[Próximo Capítulo &#62;]