include::./index.adoc[]

[[v18-39-0]]
=== Job, 39
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-39-1]]

^<<v18-39-1,1>>^ “Do you know the time when the mountain goats give birth?
Have you watched the deer give birth to their young?

[[v18-39-2]]

^<<v18-39-2,2>>^ Do you count the months that they must complete?
Do you know the time when they give birth?

[[v18-39-3]]

^<<v18-39-3,3>>^ They crouch down when they give birth to their young,
And their labor pains end.

[[v18-39-4]]

^<<v18-39-4,4>>^ Their young become strong and grow up in the open field;
They go out and do not return to them.

[[v18-39-5]]

^<<v18-39-5,5>>^ Who set the wild donkey^&#42;1^ free,
And who untied the ropes of the wild donkey?

[NOTE]
====
. Or “onager.”
====

[[v18-39-6]]

^<<v18-39-6,6>>^ I have made the desert plain its home
And the salt land its dwelling.

[[v18-39-7]]

^<<v18-39-7,7>>^ It scorns the tumult of the city;
It does not hear the shouts of the driver.

[[v18-39-8]]

^<<v18-39-8,8>>^ It roams the hills, seeking pasture,
Looking for every green plant.

[[v18-39-9]]

^<<v18-39-9,9>>^ Is the wild bull willing to serve you?
Will it spend the night in your stable?^&#42;1^

[NOTE]
====
. Or “manger.”
====

[[v18-39-10]]

^<<v18-39-10,10>>^ Will you hold a wild bull to the furrow with a rope,
Or will it follow you to plow^&#42;1^ the valley?

[NOTE]
====
. Or “harrow.”
====

[[v18-39-11]]

^<<v18-39-11,11>>^ Will you trust in its great strength
And let it do your heavy work?

[[v18-39-12]]

^<<v18-39-12,12>>^ Will you rely on it to bring back your harvest,^&#42;1^
And will it gather it to your threshing floor?

[NOTE]
====
. Lit., “seed.”
====

[[v18-39-13]]

^<<v18-39-13,13>>^ The wings of the ostrich flap joyfully,
But can her pinions and plumage compare with the stork’s?

[[v18-39-14]]

^<<v18-39-14,14>>^ For she leaves her eggs on the ground,
And she keeps them warm in the dust.

[[v18-39-15]]

^<<v18-39-15,15>>^ She forgets that some foot may crush them
Or that a wild animal may trample them.

[[v18-39-16]]

^<<v18-39-16,16>>^ She treats her sons harshly, as if they were not hers;
She has no fear that her labor may be in vain.

[[v18-39-17]]

^<<v18-39-17,17>>^ For God has deprived her of^&#42;1^ wisdom
And given her no share in understanding.

[NOTE]
====
. Lit., “made her forget.”
====

[[v18-39-18]]

^<<v18-39-18,18>>^ But when she rises up and flaps her wings,
She laughs at the horse and at its rider.

[[v18-39-19]]

^<<v18-39-19,19>>^ Are you the one who gives the horse its strength?
Do you clothe its neck with a rustling mane?

[[v18-39-20]]

^<<v18-39-20,20>>^ Can you cause it to leap like a locust?
Its majestic snorting is terrifying.

[[v18-39-21]]

^<<v18-39-21,21>>^ It paws the ground in the valley and exults mightily;
It charges into the battle.^&#42;1^

[NOTE]
====
. Lit., “It goes out to meet armor.”
====

[[v18-39-22]]

^<<v18-39-22,22>>^ It laughs at fear and is afraid of nothing.
It does not turn back because of the sword.

[[v18-39-23]]

^<<v18-39-23,23>>^ The quiver rattles against it,
The spear and the javelin flash.

[[v18-39-24]]

^<<v18-39-24,24>>^ Trembling with excitement, it surges forward,^&#42;1^
It cannot stand still at^&#42;2^ the sound of the horn.

[NOTE]
====
. Lit., “swallows the ground (earth).”
. Or possibly, “It does not believe.”
====

[[v18-39-25]]

^<<v18-39-25,25>>^ When the horn blows, it says, ‘Aha!’
It smells the battle from afar
And hears the shouting of commanders and the battle cry.

[[v18-39-26]]

^<<v18-39-26,26>>^ Is it by your understanding that the falcon soars,
Spreading its wings to the south?

[[v18-39-27]]

^<<v18-39-27,27>>^ Or is it at your order that an eagle flies upward
And builds its nest high up,

[[v18-39-28]]

^<<v18-39-28,28>>^ Spending the night on a cliff,
Dwelling in its stronghold on a rocky crag?^&#42;1^

[NOTE]
====
. Lit., “on the tooth of a crag.”
====

[[v18-39-29]]

^<<v18-39-29,29>>^ From there it searches for food;
Its eyes look far into the distance.

[[v18-39-30]]

^<<v18-39-30,30>>^ Its young sip up blood;
And wherever the slain are, there it is.”

'''

xref:018-job/018-job-038.adoc#v18-38-0[&#60; Capítulo Anterior] | <<v18-39-0,Topo>> | xref:018-job/018-job-040.adoc#v18-40-0[Próximo Capítulo &#62;]