include::./index.adoc[]

[[v18-23-0]]
=== Job, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-23-1]]

^<<v18-23-1,1>>^ Job said in reply:

[[v18-23-2]]

^<<v18-23-2,2>>^ “Even today I will complain stubbornly;^&#42;1^
My strength is exhausted because of my sighing.

[NOTE]
====
. Or “my complaint is rebellious.”
====

[[v18-23-3]]

^<<v18-23-3,3>>^ If only I knew where to find God!
I would go to his place of dwelling.

[[v18-23-4]]

^<<v18-23-4,4>>^ I would present my case before him
And fill my mouth with arguments;

[[v18-23-5]]

^<<v18-23-5,5>>^ I would learn how he would answer me
And take note of what he says to me.

[[v18-23-6]]

^<<v18-23-6,6>>^ Would he contend with me using his great power?
No, surely he would give me a hearing.

[[v18-23-7]]

^<<v18-23-7,7>>^ There the upright one could set matters straight with him,
And I would be acquitted once and for all by my Judge.

[[v18-23-8]]

^<<v18-23-8,8>>^ But if I go east, he is not there;
And I return and I cannot find him.

[[v18-23-9]]

^<<v18-23-9,9>>^ When he is working on the left, I cannot look upon him;
Then he turns to the right, but I still do not see him.

[[v18-23-10]]

^<<v18-23-10,10>>^ But he knows the path I have taken.
After he has tested me, I will come out as pure gold.

[[v18-23-11]]

^<<v18-23-11,11>>^ My feet have closely followed his footsteps;
I have kept to his way without deviating.

[[v18-23-12]]

^<<v18-23-12,12>>^ I have not departed from the commandment of his lips.
I have treasured up his sayings even more than what was required of me.^&#42;1^

[NOTE]
====
. Or “prescribed for me.”
====

[[v18-23-13]]

^<<v18-23-13,13>>^ When he is determined, who can resist him?
When he^&#42;1^ wants to do something, he does it.

[NOTE]
====
. Or “his soul.”
====

[[v18-23-14]]

^<<v18-23-14,14>>^ For he will carry out completely what has been determined^&#42;1^ for me,
And he has many such things in store.

[NOTE]
====
. Or “prescribed.”
====

[[v18-23-15]]

^<<v18-23-15,15>>^ That is why I am anxious because of him;
When I think about him, my fear grows.

[[v18-23-16]]

^<<v18-23-16,16>>^ God has made me fainthearted,
And the Almighty has made me afraid.

[[v18-23-17]]

^<<v18-23-17,17>>^ But I have not yet been silenced by the darkness
Nor by the gloom that has covered my face.

'''

xref:018-job/018-job-022.adoc#v18-22-0[&#60; Capítulo Anterior] | <<v18-23-0,Topo>> | xref:018-job/018-job-024.adoc#v18-24-0[Próximo Capítulo &#62;]