include::./index.adoc[]

[[v18-34-0]]
=== Job, 34
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-34-1]]

^<<v18-34-1,1>>^ So E·liʹhu continued to say in reply:

[[v18-34-2]]

^<<v18-34-2,2>>^ “Listen to my words, you who are wise;
Hear me, you who know so much.

[[v18-34-3]]

^<<v18-34-3,3>>^ For the ear tests words
Just as the tongue^&#42;1^ tastes food.

[NOTE]
====
. Lit., “palate.”
====

[[v18-34-4]]

^<<v18-34-4,4>>^ Let us evaluate for ourselves what is right;
Let us decide among ourselves what is good.

[[v18-34-5]]

^<<v18-34-5,5>>^ For Job has said, ‘I am in the right,
But God has denied me justice.

[[v18-34-6]]

^<<v18-34-6,6>>^ Would I lie about what my own judgment should be?
My wound is incurable, though there is no transgression.’

[[v18-34-7]]

^<<v18-34-7,7>>^ What other man is like Job,
Who drinks up derision like water?

[[v18-34-8]]

^<<v18-34-8,8>>^ He is in company with wrongdoers
And in association with wicked men.

[[v18-34-9]]

^<<v18-34-9,9>>^ For he has said, ‘A man does not benefit
From trying to please God.’

[[v18-34-10]]

^<<v18-34-10,10>>^ So listen to me, you men of understanding:^&#42;1^
It is unthinkable for the true God to act wickedly,
For the Almighty to do wrong!

[NOTE]
====
. Lit., “heart.”
====

[[v18-34-11]]

^<<v18-34-11,11>>^ For he will reward a man according to what he does
And bring upon him the consequences of his ways.

[[v18-34-12]]

^<<v18-34-12,12>>^ For a certainty, God does not act wickedly;
The Almighty does not pervert justice.

[[v18-34-13]]

^<<v18-34-13,13>>^ Who put him in charge of the earth,
And who appointed him over the whole world?^&#42;1^

[NOTE]
====
. Or “the inhabited earth.”
====

[[v18-34-14]]

^<<v18-34-14,14>>^ If he fixes his attention^&#42;1^ on them,
If he gathers their spirit and breath to himself,

[NOTE]
====
. Lit., “his heart.”
====

[[v18-34-15]]

^<<v18-34-15,15>>^ All humans^&#42;1^ would perish together,
And mankind would return to the dust.

[NOTE]
====
. Lit., “flesh.”
====

[[v18-34-16]]

^<<v18-34-16,16>>^ So if you have understanding, pay attention to this;
Listen carefully to what I say.

[[v18-34-17]]

^<<v18-34-17,17>>^ Should someone who hates justice be in control,
Or would you condemn a powerful one who is righteous?

[[v18-34-18]]

^<<v18-34-18,18>>^ Would you say to a king, ‘You are good for nothing,’
Or to nobles, ‘You are wicked’?

[[v18-34-19]]

^<<v18-34-19,19>>^ There is One who does not show partiality to princes
And who does not favor the rich over the poor,^&#42;1^
For they are all the work of his hands.

[NOTE]
====
. Or “the noble over the lowly.”
====

[[v18-34-20]]

^<<v18-34-20,20>>^ They may die suddenly, in the middle of the night;
They shake violently and pass away;
Even the powerful are removed, but not by human hands.

[[v18-34-21]]

^<<v18-34-21,21>>^ For God’s eyes are upon the ways of a man,
And He sees all his steps.

[[v18-34-22]]

^<<v18-34-22,22>>^ There is no darkness or deep shadow
Where wrongdoers can conceal themselves.

[[v18-34-23]]

^<<v18-34-23,23>>^ For God has not set an appointed time for any man
To appear before him in judgment.

[[v18-34-24]]

^<<v18-34-24,24>>^ He breaks the powerful without needing to investigate
And sets up others in their place.

[[v18-34-25]]

^<<v18-34-25,25>>^ For he knows what they are doing;
He overthrows them during the night, and they are crushed.

[[v18-34-26]]

^<<v18-34-26,26>>^ He strikes them for their wickedness,
In a place where all can see,

[[v18-34-27]]

^<<v18-34-27,27>>^ Because they have turned away from following him
And have no regard for any of his ways;

[[v18-34-28]]

^<<v18-34-28,28>>^ They cause the poor to cry out to him,
So that he hears the outcry of the helpless.

[[v18-34-29]]

^<<v18-34-29,29>>^ When God remains silent, who can condemn him?
When he hides his face, who can see him?
Whether toward a nation or a man, the result is the same,

[[v18-34-30]]

^<<v18-34-30,30>>^ So that a godless person^&#42;1^ may not rule
Or lay snares for the people.

[NOTE]
====
. Or “an apostate.”
====

[[v18-34-31]]

^<<v18-34-31,31>>^ For will anyone say to God,
‘I have been punished, although I have committed no offense;

[[v18-34-32]]

^<<v18-34-32,32>>^ Teach me what I have failed to see;
If I have done anything wrong, I will not do it again’?

[[v18-34-33]]

^<<v18-34-33,33>>^ Should he reward you on your terms when you reject his judgment?
You must decide, not I.
So tell me what you know so well.

[[v18-34-34]]

^<<v18-34-34,34>>^ Men of understanding^&#42;1^ will say to me
—Any wise man who hears me—

[NOTE]
====
. Lit., “heart.”
====

[[v18-34-35]]

^<<v18-34-35,35>>^ ‘Job speaks without knowledge,
And his words lack insight.’

[[v18-34-36]]

^<<v18-34-36,36>>^ Let Job be tested^&#42;1^ to the limit
Because his replies are like those of wicked men!

[NOTE]
====
. Or possibly, “My father, let Job be tested.”
====

[[v18-34-37]]

^<<v18-34-37,37>>^ He adds rebellion to his sin;
He scornfully claps his hands before us
And multiplies his words against the true God!”

'''

xref:018-job/018-job-033.adoc#v18-33-0[&#60; Capítulo Anterior] | <<v18-34-0,Topo>> | xref:018-job/018-job-035.adoc#v18-35-0[Próximo Capítulo &#62;]