include::./index.adoc[]

[[v18-6-0]]
=== Job, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-6-1]]

^<<v18-6-1,1>>^ Job then said in reply:

[[v18-6-2]]

^<<v18-6-2,2>>^ “If only my anguish could be fully weighed
And put on scales together with my calamity!

[[v18-6-3]]

^<<v18-6-3,3>>^ For now it is heavier than the sands of the seas.
That is why my words have been wild talk.^&#42;1^

[NOTE]
====
. Or “rash, reckless speech.”
====

[[v18-6-4]]

^<<v18-6-4,4>>^ For the arrows of the Almighty have pierced me,
And my spirit is drinking their venom;
The terrors from God are lined up against me.

[[v18-6-5]]

^<<v18-6-5,5>>^ Will a wild donkey cry out when it has grass,
Or will a bull bellow when it has fodder?

[[v18-6-6]]

^<<v18-6-6,6>>^ Is tasteless food eaten without salt,
Or is there flavor in the juice of a mallow?

[[v18-6-7]]

^<<v18-6-7,7>>^ I have^&#42;1^ refused to touch such things.
They are like contamination in my food.

[NOTE]
====
. Or “My soul has.”
====

[[v18-6-8]]

^<<v18-6-8,8>>^ O that my request would be realized
And that God would grant my desire!

[[v18-6-9]]

^<<v18-6-9,9>>^ That God would be willing to crush me,
And that he would reach out his hand and do away with me!

[[v18-6-10]]

^<<v18-6-10,10>>^ For even that would bring me comfort;
I would leap for joy despite the unrelenting pain,
For I have not denied the sayings of the Holy One.

[[v18-6-11]]

^<<v18-6-11,11>>^ Do I have the strength to keep waiting?
And what end awaits me, that I should continue to live?^&#42;1^

[NOTE]
====
. Or “that I should prolong my life (soul).”
====

[[v18-6-12]]

^<<v18-6-12,12>>^ Is my strength like that of rock?
Or is my flesh made of copper?

[[v18-6-13]]

^<<v18-6-13,13>>^ Is there any way that I can help myself
When all my means of support has been driven from me?

[[v18-6-14]]

^<<v18-6-14,14>>^ Anyone who withholds loyal love from his fellow man
Will forsake the fear of the Almighty.

[[v18-6-15]]

^<<v18-6-15,15>>^ My own brothers have been as treacherous as a winter stream,
Like the water of winter streams that dry up.

[[v18-6-16]]

^<<v18-6-16,16>>^ They are darkened by ice,
And in them the melting snow is hidden.

[[v18-6-17]]

^<<v18-6-17,17>>^ But in due season they become waterless and come to an end;
When it becomes hot, they dry up.

[[v18-6-18]]

^<<v18-6-18,18>>^ Their course is diverted;
They flow into the desert and vanish.

[[v18-6-19]]

^<<v18-6-19,19>>^ The caravans of Teʹma look for them;
The travelers from Sheʹba^&#42;1^ wait for them.

[NOTE]
====
. Or “The traveling company of the Sabeans.”
====

[[v18-6-20]]

^<<v18-6-20,20>>^ They are ashamed because of their misplaced trust;
They come there only to be disappointed.

[[v18-6-21]]

^<<v18-6-21,21>>^ For this is how you have become to me;
You have seen the terror of my calamity, and you are afraid.

[[v18-6-22]]

^<<v18-6-22,22>>^ Have I said, ‘Give me something,’
Or requested that you make a gift for me from your wealth?

[[v18-6-23]]

^<<v18-6-23,23>>^ Have I asked to be rescued from the hand of an enemy
Or to be saved^&#42;1^ from oppressors?

[NOTE]
====
. Lit., “redeemed.”
====

[[v18-6-24]]

^<<v18-6-24,24>>^ Instruct me, and I will be silent;
Help me to understand my mistake.

[[v18-6-25]]

^<<v18-6-25,25>>^ Honest words are not painful!
But what benefit can be found in your reproof?

[[v18-6-26]]

^<<v18-6-26,26>>^ Are you scheming to reprove my words,
A desperate man’s sayings, which the wind blows away?

[[v18-6-27]]

^<<v18-6-27,27>>^ You would also cast lots over an orphan
And sell^&#42;1^ your own friend!

[NOTE]
====
. Or “barter over.”
====

[[v18-6-28]]

^<<v18-6-28,28>>^ So now turn and look at me,
For I would not lie to your very faces.

[[v18-6-29]]

^<<v18-6-29,29>>^ Reconsider, please—do not misjudge me—
Yes, reconsider, for my righteousness is yet intact.

[[v18-6-30]]

^<<v18-6-30,30>>^ Is my tongue speaking unjustly?
Does my palate not discern that something is wrong?

'''

xref:018-job/018-job-005.adoc#v18-5-0[&#60; Capítulo Anterior] | <<v18-6-0,Topo>> | xref:018-job/018-job-007.adoc#v18-7-0[Próximo Capítulo &#62;]