include::./index.adoc[]

[[v18-4-0]]
=== Job, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-4-1]]

^<<v18-4-1,1>>^ Elʹi·phaz the Teʹman·ite then said in reply:

[[v18-4-2]]

^<<v18-4-2,2>>^ “If someone tries to speak to you, will you become impatient?
For who can hold back from speaking?

[[v18-4-3]]

^<<v18-4-3,3>>^ True, you have corrected many,
And you used to strengthen the weak hands.

[[v18-4-4]]

^<<v18-4-4,4>>^ Your words would raise up anyone stumbling,
And you would strengthen those whose knees were buckling.

[[v18-4-5]]

^<<v18-4-5,5>>^ But now it has happened to you, and you are overwhelmed;^&#42;1^
It touches you, and you are dismayed.

[NOTE]
====
. Lit., “you become weary.”
====

[[v18-4-6]]

^<<v18-4-6,6>>^ Does your reverence for God not give you confidence?
Does your way of integrity not give you hope?

[[v18-4-7]]

^<<v18-4-7,7>>^ Remember, please: What innocent person has ever perished?
When have the upright ever been destroyed?

[[v18-4-8]]

^<<v18-4-8,8>>^ What I have seen is that those who plow^&#42;1^ what is harmful
And those who sow trouble will reap the same.

[NOTE]
====
. Or “devise.”
====

[[v18-4-9]]

^<<v18-4-9,9>>^ By the breath of God they perish,
And through a blast of his anger they come to an end.

[[v18-4-10]]

^<<v18-4-10,10>>^ The lion roars, and a young lion growls,
But even the teeth of strong lions^&#42;1^ are broken.

[NOTE]
====
. Or “maned young lions.”
====

[[v18-4-11]]

^<<v18-4-11,11>>^ A lion perishes for lack of prey,
And the cubs of a lion are scattered.

[[v18-4-12]]

^<<v18-4-12,12>>^ Now a word was brought to me in secret,
And a whisper of it reached my ear.

[[v18-4-13]]

^<<v18-4-13,13>>^ In troubling thoughts during visions of the night,
When deep sleep falls upon men,

[[v18-4-14]]

^<<v18-4-14,14>>^ A terrible trembling came upon me,
Filling all my bones with dread.

[[v18-4-15]]

^<<v18-4-15,15>>^ A spirit passed over my face;
The hair of my flesh bristled.

[[v18-4-16]]

^<<v18-4-16,16>>^ It then stood still,
But I did not recognize its appearance.
A form was in front of my eyes;
There was a calm, and then I heard a voice:

[[v18-4-17]]

^<<v18-4-17,17>>^ ‘Can a mortal man be more righteous than God?
Can a man be cleaner than his own Maker?’

[[v18-4-18]]

^<<v18-4-18,18>>^ Look! He has no faith in his servants,
And he finds fault with his angels.^&#42;1^

[NOTE]
====
. Or “messengers.”
====

[[v18-4-19]]

^<<v18-4-19,19>>^ How much more so with those dwelling in houses of clay,
Whose foundation is in the dust,
Who are crushed as easily as a moth!

[[v18-4-20]]

^<<v18-4-20,20>>^ They are completely crushed from morning to evening;
They perish forever, and no one takes notice.

[[v18-4-21]]

^<<v18-4-21,21>>^ Are they not like a tent whose cord is pulled out?
They die without wisdom.

'''

xref:018-job/018-job-003.adoc#v18-3-0[&#60; Capítulo Anterior] | <<v18-4-0,Topo>> | xref:018-job/018-job-005.adoc#v18-5-0[Próximo Capítulo &#62;]