include::./index.adoc[]

[[v18-14-0]]
=== Job, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-14-1]]

^<<v18-14-1,1>>^ “Man, born of woman,
Is short-lived and filled with trouble.^&#42;1^

[NOTE]
====
. Or “glutted with agitation.”
====

[[v18-14-2]]

^<<v18-14-2,2>>^ He comes up like a blossom and then withers away;^&#42;1^
He flees like a shadow and disappears.

[NOTE]
====
. Or possibly, “and is cut off.”
====

[[v18-14-3]]

^<<v18-14-3,3>>^ Yes, you have fixed your eye upon him,
And you bring him^&#42;1^ into judgment with yourself.

[NOTE]
====
. Lit., “me.”
====

[[v18-14-4]]

^<<v18-14-4,4>>^ Who can produce someone clean from someone unclean?
No one can!

[[v18-14-5]]

^<<v18-14-5,5>>^ If his days are decided,
The number of his months is with you;
You have set a limit for him that he may not go beyond.

[[v18-14-6]]

^<<v18-14-6,6>>^ Turn your gaze away from him so that he may rest,
Until, like a hired worker, he finishes out his day.

[[v18-14-7]]

^<<v18-14-7,7>>^ For there is hope even for a tree.
If it is cut down, it will sprout again,
And its twigs will continue to grow.

[[v18-14-8]]

^<<v18-14-8,8>>^ If its root grows old in the ground
And its stump dies in the soil,

[[v18-14-9]]

^<<v18-14-9,9>>^ At the scent of water it will sprout;
And it will produce branches like a new plant.

[[v18-14-10]]

^<<v18-14-10,10>>^ But a man dies and lies powerless;
When a human expires, where is he?

[[v18-14-11]]

^<<v18-14-11,11>>^ Waters disappear from the sea,
And a river drains away and dries up.

[[v18-14-12]]

^<<v18-14-12,12>>^ Man also lies down and does not get up.
Until heaven is no more, they will not wake up,
Nor will they be aroused from their sleep.

[[v18-14-13]]

^<<v18-14-13,13>>^ O that in the Grave^&#42;1^ you would conceal me,
That you would hide me until your anger passes by,
That you would set a time limit for me and remember me!

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v18-14-14]]

^<<v18-14-14,14>>^ If a man dies, can he live again?
I will wait all the days of my compulsory service
Until my relief comes.

[[v18-14-15]]

^<<v18-14-15,15>>^ You will call, and I will answer you.
You will long^&#42;1^ for the work of your hands.

[NOTE]
====
. Or “yearn.”
====

[[v18-14-16]]

^<<v18-14-16,16>>^ But for now, you keep counting my every step;
You watch only for my sin.

[[v18-14-17]]

^<<v18-14-17,17>>^ My transgression is sealed up in a bag,
And you seal up my error with glue.

[[v18-14-18]]

^<<v18-14-18,18>>^ As a mountain falls and crumbles away
And a rock is dislodged from its place,

[[v18-14-19]]

^<<v18-14-19,19>>^ As water wears away stones
And its torrents wash away earth’s soil,
So you have destroyed the hope of mortal man.

[[v18-14-20]]

^<<v18-14-20,20>>^ You keep overpowering him until he perishes;
You change his appearance, and you send him away.

[[v18-14-21]]

^<<v18-14-21,21>>^ His sons are honored, but he does not know it;
They become insignificant, but he does not realize it.

[[v18-14-22]]

^<<v18-14-22,22>>^ He feels pain only while he is still in his flesh;
He^&#42;1^ mourns only while he is still alive.”

[NOTE]
====
. Or “His soul.”
====

'''

xref:018-job/018-job-013.adoc#v18-13-0[&#60; Capítulo Anterior] | <<v18-14-0,Topo>> | xref:018-job/018-job-015.adoc#v18-15-0[Próximo Capítulo &#62;]