include::./index.adoc[]

[[v18-19-0]]
=== Job, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-19-1]]

^<<v18-19-1,1>>^ Job said in reply:

[[v18-19-2]]

^<<v18-19-2,2>>^ “How long will you keep irritating my soul,^&#42;1^
Crushing me with words?

[NOTE]
====
. Or “irritating me.” See Glossary.
====

[[v18-19-3]]

^<<v18-19-3,3>>^ These ten times you have rebuked^&#42;1^ me;
You are not ashamed to deal harshly with me.

[NOTE]
====
. Or “insulted.”
====

[[v18-19-4]]

^<<v18-19-4,4>>^ And if indeed I made a mistake,
My error remains with me.

[[v18-19-5]]

^<<v18-19-5,5>>^ If you insist on exalting yourselves over me,
Claiming that the reproach against me is justified,

[[v18-19-6]]

^<<v18-19-6,6>>^ Know, then, that it is God who has misled me,
And he has caught me in his hunting net.

[[v18-19-7]]

^<<v18-19-7,7>>^ Look! I keep crying out, ‘Violence!’ but I get no answer;
I keep crying for help, but there is no justice.

[[v18-19-8]]

^<<v18-19-8,8>>^ My path he has blocked with a stone wall, and I cannot pass by;
He has covered my roadways with darkness.

[[v18-19-9]]

^<<v18-19-9,9>>^ He has stripped me of my glory
And removed the crown from my head.

[[v18-19-10]]

^<<v18-19-10,10>>^ He breaks me down on all sides until I perish;
My hope he uproots like a tree.

[[v18-19-11]]

^<<v18-19-11,11>>^ His anger burns against me,
And he views me as his enemy.

[[v18-19-12]]

^<<v18-19-12,12>>^ His troops come together and besiege me,
And they camp around my tent.

[[v18-19-13]]

^<<v18-19-13,13>>^ My own brothers he has driven far away from me,
And those who know me have turned away from me.

[[v18-19-14]]

^<<v18-19-14,14>>^ My close companions^&#42;1^ are gone,
And those whom I knew well have forgotten me.

[NOTE]
====
. Or “My relatives.”
====

[[v18-19-15]]

^<<v18-19-15,15>>^ Guests in my house and my slave girls consider me a stranger;
I am a foreigner in their eyes.

[[v18-19-16]]

^<<v18-19-16,16>>^ I call for my servant, but he does not respond;
With my mouth I beg him for compassion.

[[v18-19-17]]

^<<v18-19-17,17>>^ My very breath has become loathsome to my wife,
And I am a stench to my own brothers.^&#42;1^

[NOTE]
====
. Lit., “the sons of my womb,” that is, the womb that bore me (my mother’s womb).
====

[[v18-19-18]]

^<<v18-19-18,18>>^ Even young children despise me;
When I rise up, they begin jeering at me.

[[v18-19-19]]

^<<v18-19-19,19>>^ All my close friends detest me,
And those whom I loved have turned against me.

[[v18-19-20]]

^<<v18-19-20,20>>^ My bones stick to my skin and my flesh,
And I escape with the skin of my teeth.

[[v18-19-21]]

^<<v18-19-21,21>>^ Show me mercy, my companions, show me mercy,
For God’s own hand has touched me.

[[v18-19-22]]

^<<v18-19-22,22>>^ Why do you keep persecuting me as God does,
Attacking me without letup?^&#42;1^

[NOTE]
====
. Lit., “And not be satisfied with my flesh?”
====

[[v18-19-23]]

^<<v18-19-23,23>>^ If only my words were written down,
If only they could be inscribed in a book!

[[v18-19-24]]

^<<v18-19-24,24>>^ O that they were carved forever in the rock,
With an iron stylus and lead!

[[v18-19-25]]

^<<v18-19-25,25>>^ For I well know that my redeemer^&#42;1^ is alive;
He will come later and rise up over the earth.^&#42;2^

[NOTE]
====
. Or “repurchaser.”
. Lit., “over (upon) the dust.”
====

[[v18-19-26]]

^<<v18-19-26,26>>^ After my skin has thus been destroyed,
While yet in my flesh, I will see God,

[[v18-19-27]]

^<<v18-19-27,27>>^ Whom I will see for myself,
Whom my own eyes will see, not someone else’s.
But deep inside I feel overwhelmed!^&#42;1^

[NOTE]
====
. Or “My kidneys have failed within me.”
====

[[v18-19-28]]

^<<v18-19-28,28>>^ For you say, ‘In what way are we persecuting him?’
Since the root of the problem is with me.

[[v18-19-29]]

^<<v18-19-29,29>>^ Be in fear of the sword yourselves,
For the sword brings punishment against errors;
You should know that there is a judge.”

'''

xref:018-job/018-job-018.adoc#v18-18-0[&#60; Capítulo Anterior] | <<v18-19-0,Topo>> | xref:018-job/018-job-020.adoc#v18-20-0[Próximo Capítulo &#62;]