include::./index.adoc[]

[[v18-32-0]]
=== Job, 32
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-32-1]]

^<<v18-32-1,1>>^ So these three men stopped trying to answer Job, because he was convinced of his own righteousness.^&#42;1^

[NOTE]
====
. Or “because he was righteous in his own eyes.”
====

[[v18-32-2]]

^<<v18-32-2,2>>^ But E·liʹhu the son of Barʹa·chel the Buzʹite of the family of Ram had become very angry. His anger blazed against Job for trying to prove himself^&#42;1^ right rather than God.

[NOTE]
====
. Or “his soul.”
====

[[v18-32-3]]

^<<v18-32-3,3>>^ He was also very angry with Job’s three companions because they could not find an answer but had declared God wicked.

[[v18-32-4]]

^<<v18-32-4,4>>^ E·liʹhu had been waiting to respond to Job, because they were older than he was.

[[v18-32-5]]

^<<v18-32-5,5>>^ When E·liʹhu saw that the three men had nothing to say in answer, his anger flared up.

[[v18-32-6]]

^<<v18-32-6,6>>^ So E·liʹhu the son of Barʹa·chel the Buzʹite began to speak, saying:
“I am young^&#42;1^
And you men are aged.
So I respectfully held back,
And I dared not tell you what I know.

[NOTE]
====
. Lit., “small in days.”
====

[[v18-32-7]]

^<<v18-32-7,7>>^ I thought, ‘Let age^&#42;1^ speak,
And let a multitude of years declare wisdom.’

[NOTE]
====
. Lit., “days.”
====

[[v18-32-8]]

^<<v18-32-8,8>>^ But it is the spirit in people,
The breath of the Almighty, that gives them understanding.

[[v18-32-9]]

^<<v18-32-9,9>>^ Age alone does not^&#42;1^ make one wise,
Nor is it only old men who understand what is right.

[NOTE]
====
. Or “Many days alone do not.”
====

[[v18-32-10]]

^<<v18-32-10,10>>^ So I say, ‘Listen to me,
And I will also tell you what I know.’

[[v18-32-11]]

^<<v18-32-11,11>>^ Look! I have waited for your words;
I kept listening to your reasoning
As you searched for things to say.

[[v18-32-12]]

^<<v18-32-12,12>>^ I paid close attention to you,
But none of you could prove Job wrong^&#42;1^
Or answer his arguments.

[NOTE]
====
. Or “reprove Job.”
====

[[v18-32-13]]

^<<v18-32-13,13>>^ So do not say, ‘We have found wisdom;
It is God who refutes him, not a man.’

[[v18-32-14]]

^<<v18-32-14,14>>^ He did not direct his words against me,
So I will not reply to him with your arguments.

[[v18-32-15]]

^<<v18-32-15,15>>^ They are dismayed, they have no more answers;
They have nothing left to say.

[[v18-32-16]]

^<<v18-32-16,16>>^ I have waited, but they do not continue speaking;
They just stand there, with no further answer.

[[v18-32-17]]

^<<v18-32-17,17>>^ So I too will give an answer;
I too will tell what I know,

[[v18-32-18]]

^<<v18-32-18,18>>^ For I am full of words;
The spirit within me compels me.

[[v18-32-19]]

^<<v18-32-19,19>>^ My insides are like wine that has no vent,
Like new wineskins ready to burst.

[[v18-32-20]]

^<<v18-32-20,20>>^ Let me speak so that I can find relief!
I will open my lips and give an answer.

[[v18-32-21]]

^<<v18-32-21,21>>^ I will not show partiality to anyone;
Nor will I flatter^&#42;1^ any human,

[NOTE]
====
. Or “confer an honorary title to.”
====

[[v18-32-22]]

^<<v18-32-22,22>>^ For I do not know how to flatter;
If I did, my Maker would quickly do away with me.

'''

xref:018-job/018-job-031.adoc#v18-31-0[&#60; Capítulo Anterior] | <<v18-32-0,Topo>> | xref:018-job/018-job-033.adoc#v18-33-0[Próximo Capítulo &#62;]