include::./index.adoc[]

[[v18-29-0]]
=== Job, 29
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-29-1]]

^<<v18-29-1,1>>^ Job continued his discourse,^&#42;1^ saying:

[NOTE]
====
. Lit., “proverb.”
====

[[v18-29-2]]

^<<v18-29-2,2>>^ “If only I were in the months gone by,
In the days when God was watching over me,

[[v18-29-3]]

^<<v18-29-3,3>>^ When he caused his lamp to shine upon my head,
When I walked through darkness by his light,

[[v18-29-4]]

^<<v18-29-4,4>>^ When I was in^&#42;1^ my prime,
When God’s friendship was felt in my tent,

[NOTE]
====
. Lit., “in the days of.”
====

[[v18-29-5]]

^<<v18-29-5,5>>^ When the Almighty was still with me,
When my children^&#42;1^ were all around me,

[NOTE]
====
. Or “attendants.”
====

[[v18-29-6]]

^<<v18-29-6,6>>^ When my steps were awash in butter,
And the rocks poured out streams of oil for me.

[[v18-29-7]]

^<<v18-29-7,7>>^ When I used to go out to the city gate
And take my seat in the public square,

[[v18-29-8]]

^<<v18-29-8,8>>^ The young men would see me and step aside,^&#42;1^
And even the old men would rise and remain standing.

[NOTE]
====
. Lit., “hide themselves.”
====

[[v18-29-9]]

^<<v18-29-9,9>>^ Princes refrained from speaking;
They would put their hand over their mouth.

[[v18-29-10]]

^<<v18-29-10,10>>^ The voices of the prominent men were silenced;
Their tongue was stuck to the roof of their mouth.

[[v18-29-11]]

^<<v18-29-11,11>>^ Whoever heard me would speak well of me,
And those who saw me would testify for me.

[[v18-29-12]]

^<<v18-29-12,12>>^ For I would rescue the poor who cried for help,
Along with the fatherless child and anyone who had no helper.

[[v18-29-13]]

^<<v18-29-13,13>>^ The one about to perish would bless me,
And I made the heart of the widow rejoice.

[[v18-29-14]]

^<<v18-29-14,14>>^ I put on righteousness as my clothing;
My justice was like a robe^&#42;1^ and a turban.

[NOTE]
====
. Or “sleeveless coat.”
====

[[v18-29-15]]

^<<v18-29-15,15>>^ I became eyes to the blind
And feet to the lame.

[[v18-29-16]]

^<<v18-29-16,16>>^ I was a father to the poor;
I would investigate the legal case of those I did not know.

[[v18-29-17]]

^<<v18-29-17,17>>^ I would break the jaws of the wrongdoer
And tear the prey away from his teeth.

[[v18-29-18]]

^<<v18-29-18,18>>^ I used to say, ‘I will die in my own home,^&#42;1^
And my days will be as numerous as the grains of sand.

[NOTE]
====
. Lit., “in my nest.”
====

[[v18-29-19]]

^<<v18-29-19,19>>^ My roots will spread out into the waters,
And dew will stay all night on my branches.

[[v18-29-20]]

^<<v18-29-20,20>>^ My glory is constantly renewed,
And the bow in my hand will keep shooting.’

[[v18-29-21]]

^<<v18-29-21,21>>^ People would listen expectantly,
Waiting in silence for my advice.

[[v18-29-22]]

^<<v18-29-22,22>>^ After I had spoken, they had nothing more to say;
My words would fall gently^&#42;1^ on their ears.

[NOTE]
====
. Lit., “would drip.”
====

[[v18-29-23]]

^<<v18-29-23,23>>^ They waited for me as for the rain;
They opened their mouth wide as for the spring rain.

[[v18-29-24]]

^<<v18-29-24,24>>^ When I smiled at them, they could hardly believe it;
The light of my face would reassure them.^&#42;1^

[NOTE]
====
. Or possibly, “They did not darken the light of my face.”
====

[[v18-29-25]]

^<<v18-29-25,25>>^ I gave them direction as their head,
And I lived like a king among his troops,
Like one who comforts the mourners.

'''

xref:018-job/018-job-028.adoc#v18-28-0[&#60; Capítulo Anterior] | <<v18-29-0,Topo>> | xref:018-job/018-job-030.adoc#v18-30-0[Próximo Capítulo &#62;]