include::./index.adoc[]

[[v18-15-0]]
=== Job, 15
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-15-1]]

^<<v18-15-1,1>>^ Elʹi·phaz the Teʹman·ite said in reply:

[[v18-15-2]]

^<<v18-15-2,2>>^ “Will a wise person answer with empty arguments,^&#42;1^
Or will he fill his belly with the east wind?

[NOTE]
====
. Or “with blustery knowledge.”
====

[[v18-15-3]]

^<<v18-15-3,3>>^ Reproving with mere words is useless,
And talk alone is of no benefit.

[[v18-15-4]]

^<<v18-15-4,4>>^ For you undermine the fear of God,
And you diminish any concern for God.

[[v18-15-5]]

^<<v18-15-5,5>>^ For your error dictates what you say,^&#42;1^
And you choose crafty speech.

[NOTE]
====
. Or “your error trains your mouth.”
====

[[v18-15-6]]

^<<v18-15-6,6>>^ Your own mouth condemns you, and not I;
Your own lips testify against you.

[[v18-15-7]]

^<<v18-15-7,7>>^ Were you the first man ever born,
Or was your birth before that of the hills?

[[v18-15-8]]

^<<v18-15-8,8>>^ Do you listen to the confidential talk of God,
Or do you limit wisdom to yourself?

[[v18-15-9]]

^<<v18-15-9,9>>^ What do you know that we do not know?
What do you understand that we do not?

[[v18-15-10]]

^<<v18-15-10,10>>^ Both the gray-haired and the aged are among us,
Men much older than your father.

[[v18-15-11]]

^<<v18-15-11,11>>^ Are God’s consolations not enough for you,
Or words spoken gently to you?

[[v18-15-12]]

^<<v18-15-12,12>>^ Why does your heart carry you away,
And why do your eyes flash with anger?

[[v18-15-13]]

^<<v18-15-13,13>>^ For you turn your spirit against God himself,
And you allow such words to go out of your own mouth.

[[v18-15-14]]

^<<v18-15-14,14>>^ What is mortal man that he should be pure,
Or anyone born of a woman that he should be righteous?

[[v18-15-15]]

^<<v18-15-15,15>>^ Look! He has no faith in his holy ones,
And even the heavens are not pure in his eyes.

[[v18-15-16]]

^<<v18-15-16,16>>^ How much less so when a person is detestable and corrupt,
A man who drinks in unrighteousness just like water!

[[v18-15-17]]

^<<v18-15-17,17>>^ I will inform you; listen to me!
I will relate what I have seen,

[[v18-15-18]]

^<<v18-15-18,18>>^ What wise men have related from their fathers,
Things they have not hidden.

[[v18-15-19]]

^<<v18-15-19,19>>^ To them alone the land was given,
And no stranger passed among them.

[[v18-15-20]]

^<<v18-15-20,20>>^ A wicked person suffers torment all his days,
Throughout all the years reserved for the tyrant.

[[v18-15-21]]

^<<v18-15-21,21>>^ Terrifying sounds are in his ears;
In a time of peace, marauders attack him.

[[v18-15-22]]

^<<v18-15-22,22>>^ He does not believe that he will escape from darkness;
He is reserved for a sword.

[[v18-15-23]]

^<<v18-15-23,23>>^ He wanders about in search of food^&#42;1^—where is it?
He well knows that the day of darkness is at hand.

[NOTE]
====
. Lit., “bread.”
====

[[v18-15-24]]

^<<v18-15-24,24>>^ Distress and anguish keep terrifying him;
They overpower him like a king ready to launch an attack.

[[v18-15-25]]

^<<v18-15-25,25>>^ For he raises his hand against God himself
And tries to defy^&#42;1^ the Almighty;

[NOTE]
====
. Or “tries to prevail against.”
====

[[v18-15-26]]

^<<v18-15-26,26>>^ He stubbornly rushes against Him,
With his thick, strong shield;^&#42;1^

[NOTE]
====
. Lit., “his thick shield bosses.”
====

[[v18-15-27]]

^<<v18-15-27,27>>^ His face is covered with fat,
And his hips bulge with fat;

[[v18-15-28]]

^<<v18-15-28,28>>^ He resides in cities that will be brought to ruin,
In houses where no one will dwell,
Which will become heaps of stones.

[[v18-15-29]]

^<<v18-15-29,29>>^ He will not grow rich, and his wealth will not accumulate,
Nor will his possessions spread over the land.

[[v18-15-30]]

^<<v18-15-30,30>>^ He will not escape from darkness;
A flame will dry up his twig,^&#42;1^
And he will pass away by a blast of God’s^&#42;2^ mouth.

[NOTE]
====
. That is, any hope of recovery.
. Lit., “his.”
====

[[v18-15-31]]

^<<v18-15-31,31>>^ He should not go astray and trust in what is worthless,
For what he gets in exchange will be worthless;

[[v18-15-32]]

^<<v18-15-32,32>>^ It will happen before his day,
And his branches will never flourish.

[[v18-15-33]]

^<<v18-15-33,33>>^ He will be like a vine that shakes off its unripe grapes,
And like an olive tree that casts off its blossoms.

[[v18-15-34]]

^<<v18-15-34,34>>^ For the assembly of godless ones^&#42;1^ is sterile,
And fire will consume the tents of bribery.

[NOTE]
====
. Or “of apostates.”
====

[[v18-15-35]]

^<<v18-15-35,35>>^ They conceive trouble and give birth to what is wicked,
And their womb produces deceit.”

'''

xref:018-job/018-job-014.adoc#v18-14-0[&#60; Capítulo Anterior] | <<v18-15-0,Topo>> | xref:018-job/018-job-016.adoc#v18-16-0[Próximo Capítulo &#62;]