include::./index.adoc[]

[[v18-7-0]]
=== Job, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-7-1]]

^<<v18-7-1,1>>^ “Is not the life of mortal man on earth like compulsory labor,
And are not his days like those of a hired worker?

[[v18-7-2]]

^<<v18-7-2,2>>^ Like a slave, he longs for the shadow,
And like a hired worker, he waits for his wages.

[[v18-7-3]]

^<<v18-7-3,3>>^ Thus I have been assigned months of futility
And nights of misery have been counted out for me.

[[v18-7-4]]

^<<v18-7-4,4>>^ When I lie down I ask, ‘When will I get up?’
But as the night drags on, I toss restlessly until the dawning of the day.^&#42;1^

[NOTE]
====
. Or “until morning twilight.”
====

[[v18-7-5]]

^<<v18-7-5,5>>^ My flesh is covered with maggots and clods of dirt;
My skin is full of scabs and pus.

[[v18-7-6]]

^<<v18-7-6,6>>^ My days go by more quickly than a weaver’s shuttle,
And they come to an end without hope.

[[v18-7-7]]

^<<v18-7-7,7>>^ Remember that my life is wind,
That my eye will never again see happiness.^&#42;1^

[NOTE]
====
. Lit., “see good.”
====

[[v18-7-8]]

^<<v18-7-8,8>>^ The eye that sees me now will see me no more;
Your eyes will look for me, but I will be gone.

[[v18-7-9]]

^<<v18-7-9,9>>^ Like a cloud that fades and vanishes,
The one who goes down to the Grave^&#42;1^ does not come back up.

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v18-7-10]]

^<<v18-7-10,10>>^ He will not return again to his house,
And his place will acknowledge him no more.

[[v18-7-11]]

^<<v18-7-11,11>>^ Therefore, I will not restrain my mouth.
I will speak in the anguish of my spirit;
I will complain in my bitter distress!^&#42;1^

[NOTE]
====
. Or “with bitterness of my soul!”
====

[[v18-7-12]]

^<<v18-7-12,12>>^ Am I the sea or a sea monster,
That you should set a guard over me?

[[v18-7-13]]

^<<v18-7-13,13>>^ When I say, ‘My couch will comfort me;
My bed will help ease my misery,’

[[v18-7-14]]

^<<v18-7-14,14>>^ Then you terrify me with dreams
And frighten me with visions,

[[v18-7-15]]

^<<v18-7-15,15>>^ So that I^&#42;1^ would choose suffocation,
Yes, death rather than this body of mine.^&#42;2^

[NOTE]
====
. Or “my soul.”
. Lit., “than my bones.”
====

[[v18-7-16]]

^<<v18-7-16,16>>^ I loathe my life; I do not want to go on living.
Leave me alone, for my days are like a breath.

[[v18-7-17]]

^<<v18-7-17,17>>^ What is mortal man that you should concern yourself with him
And fix your attention^&#42;1^ on him?

[NOTE]
====
. Lit., “set your heart.”
====

[[v18-7-18]]

^<<v18-7-18,18>>^ Why do you inspect him every morning
And test him every moment?

[[v18-7-19]]

^<<v18-7-19,19>>^ Will you not look away from me
And leave me alone long enough to swallow my saliva?

[[v18-7-20]]

^<<v18-7-20,20>>^ If I have sinned, how could I harm you, the Observer of mankind?
Why have you made me your target?
Have I become a burden to you?

[[v18-7-21]]

^<<v18-7-21,21>>^ Why do you not pardon my transgression
And excuse my error?
For soon I will lie down in the dust,
And you will look for me, but I will be gone.”

'''

xref:018-job/018-job-006.adoc#v18-6-0[&#60; Capítulo Anterior] | <<v18-7-0,Topo>> | xref:018-job/018-job-008.adoc#v18-8-0[Próximo Capítulo &#62;]