include::./index.adoc[]

[[v18-11-0]]
=== Job, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-11-1]]

^<<v18-11-1,1>>^ Zoʹphar the Naʹa·ma·thite said in reply:

[[v18-11-2]]

^<<v18-11-2,2>>^ “Will all these words go unanswered,
Or will a lot of talking make someone right?^&#42;1^

[NOTE]
====
. Or “will a boaster be right?”
====

[[v18-11-3]]

^<<v18-11-3,3>>^ Will your empty talk silence people?
Will no one rebuke you for your mocking words?

[[v18-11-4]]

^<<v18-11-4,4>>^ For you say, ‘My teaching is pure,
And I am clean in your eyes.’

[[v18-11-5]]

^<<v18-11-5,5>>^ But if only God would speak
And open his lips to you!

[[v18-11-6]]

^<<v18-11-6,6>>^ Then he would reveal to you the secrets of wisdom,
For practical wisdom has many sides.
Then you would realize that God allows some of your error to be forgotten.

[[v18-11-7]]

^<<v18-11-7,7>>^ Can you discover the deep things of God
Or discover everything about^&#42;1^ the Almighty?

[NOTE]
====
. Or “find out the limit of.”
====

[[v18-11-8]]

^<<v18-11-8,8>>^ It is higher than heaven. What can you accomplish?
It is deeper than the Grave.^&#42;1^ What can you know?

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v18-11-9]]

^<<v18-11-9,9>>^ It is longer than the earth
And broader than the sea.

[[v18-11-10]]

^<<v18-11-10,10>>^ If he passes by and detains someone and convenes a court,
Who can resist him?

[[v18-11-11]]

^<<v18-11-11,11>>^ For he knows when men are deceitful.
When he sees what is evil, will he not take notice?

[[v18-11-12]]

^<<v18-11-12,12>>^ But an empty-headed man will understand
Only when a wild donkey can give birth to a man.^&#42;1^

[NOTE]
====
. Or “when a wild donkey is born a man.”
====

[[v18-11-13]]

^<<v18-11-13,13>>^ If only you would prepare your heart
And stretch out your hands to him.

[[v18-11-14]]

^<<v18-11-14,14>>^ If your hand is doing wrong, put it far away,
And let no unrighteousness dwell in your tents.

[[v18-11-15]]

^<<v18-11-15,15>>^ For then you could lift up your face with no defect;
You could stand firm, free of fear.

[[v18-11-16]]

^<<v18-11-16,16>>^ For then you will forget your trouble;
You will remember it as waters that have flowed past you.

[[v18-11-17]]

^<<v18-11-17,17>>^ Your life will become brighter than midday;
Even its darkness will be like the morning.

[[v18-11-18]]

^<<v18-11-18,18>>^ You will be confident because there is hope,
And you will look around and lie down in security.

[[v18-11-19]]

^<<v18-11-19,19>>^ You will lie down, with no one to make you afraid,
And many people will seek your favor.

[[v18-11-20]]

^<<v18-11-20,20>>^ But the eyes of the wicked will fail;
And they will find no place to escape,
And their only hope will be death.”^&#42;1^

[NOTE]
====
. Or “the expiring of the soul.”
====

'''

xref:018-job/018-job-010.adoc#v18-10-0[&#60; Capítulo Anterior] | <<v18-11-0,Topo>> | xref:018-job/018-job-012.adoc#v18-12-0[Próximo Capítulo &#62;]