include::./index.adoc[]

[[v18-27-0]]
=== Job, 27
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-27-1]]

^<<v18-27-1,1>>^ Job continued his discourse,^&#42;1^ saying:

[NOTE]
====
. Lit., “proverb.”
====

[[v18-27-2]]

^<<v18-27-2,2>>^ “As surely as God lives, who has deprived me of justice,
As the Almighty lives, who has made me^&#42;1^ bitter,

[NOTE]
====
. Or “my soul.”
====

[[v18-27-3]]

^<<v18-27-3,3>>^ As long as my breath is within me
And spirit from God is in my nostrils,

[[v18-27-4]]

^<<v18-27-4,4>>^ My lips will not speak unrighteousness;
Nor will my tongue mutter deceit!

[[v18-27-5]]

^<<v18-27-5,5>>^ It is unthinkable for me to declare you men righteous!
Until I die, I will not renounce^&#42;1^ my integrity!

[NOTE]
====
. Or “I will not take away from myself; I will maintain.”
====

[[v18-27-6]]

^<<v18-27-6,6>>^ I will maintain my righteousness and never let it go;
My heart will not condemn^&#42;1^ me as long as I live.^&#42;2^

[NOTE]
====
. Or “taunt.”
. Or “for any of my days.”
====

[[v18-27-7]]

^<<v18-27-7,7>>^ May my enemy become like the wicked,
Those assaulting me like the unrighteous.

[[v18-27-8]]

^<<v18-27-8,8>>^ For what hope does the godless man^&#42;1^ have when he is destroyed,
When God takes away his life?^&#42;2^

[NOTE]
====
. Or “the apostate.”
. Or “soul.”
====

[[v18-27-9]]

^<<v18-27-9,9>>^ Will God hear his outcry
When distress comes upon him?

[[v18-27-10]]

^<<v18-27-10,10>>^ Or will he find delight in the Almighty?
Will he call on God at all times?

[[v18-27-11]]

^<<v18-27-11,11>>^ I will teach you about the power^&#42;1^ of God;
I will not hide anything about the Almighty.

[NOTE]
====
. Or possibly, “by the hand.”
====

[[v18-27-12]]

^<<v18-27-12,12>>^ Look! If you have all seen visions,
Why are your speeches completely empty?

[[v18-27-13]]

^<<v18-27-13,13>>^ This is the wicked man’s share from God,
The inheritance that tyrants receive from the Almighty.

[[v18-27-14]]

^<<v18-27-14,14>>^ If his sons become many, they will fall by the sword,
And his descendants will not have enough food.

[[v18-27-15]]

^<<v18-27-15,15>>^ Those who survive him will be buried by the plague,
And their widows will not weep for them.

[[v18-27-16]]

^<<v18-27-16,16>>^ Even if he piles up silver like the dust
And stores up fine clothing like the clay,

[[v18-27-17]]

^<<v18-27-17,17>>^ Though he may gather it,
The righteous man will wear it,
And the innocent will divide up his silver.

[[v18-27-18]]

^<<v18-27-18,18>>^ The house he builds is as fragile as a moth’s cocoon,
Like a shelter made by a watchman.

[[v18-27-19]]

^<<v18-27-19,19>>^ He will go to bed rich but will gather nothing;
When he opens his eyes, nothing will be there.

[[v18-27-20]]

^<<v18-27-20,20>>^ Terror overtakes him like a flood;
A storm snatches him away by night.

[[v18-27-21]]

^<<v18-27-21,21>>^ An east wind will carry him off, and he will be gone;
It sweeps him away from his place.

[[v18-27-22]]

^<<v18-27-22,22>>^ It will hurl itself at him without pity
As he desperately tries to flee from its force.

[[v18-27-23]]

^<<v18-27-23,23>>^ It claps its hands at him
And whistles at him from its place.^&#42;1^

[NOTE]
====
. Or possibly, “They clap their hands at him and whistle at him from their place.”
====

'''

xref:018-job/018-job-026.adoc#v18-26-0[&#60; Capítulo Anterior] | <<v18-27-0,Topo>> | xref:018-job/018-job-028.adoc#v18-28-0[Próximo Capítulo &#62;]