include::./index.adoc[]

[[v18-10-0]]
=== Job, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-10-1]]

^<<v18-10-1,1>>^ “I loathe^&#42;1^ my life.
I will give vent to my complaints.
I will speak out in my bitter distress!^&#42;2^

[NOTE]
====
. Or “My soul loathes.”
. Or “with bitterness of my soul!”
====

[[v18-10-2]]

^<<v18-10-2,2>>^ I will say to God: ‘Do not pronounce me guilty.
Tell me why you are contending with me.

[[v18-10-3]]

^<<v18-10-3,3>>^ Does it benefit you to oppress,
To despise the work of your hands
While you favor the advice of the wicked?

[[v18-10-4]]

^<<v18-10-4,4>>^ Do you have eyes of flesh,
Or do you see as mortal man does?

[[v18-10-5]]

^<<v18-10-5,5>>^ Are your days like the days of mortals,
Or are your years like those of a man,

[[v18-10-6]]

^<<v18-10-6,6>>^ That you should search out my error
And keep looking for my sin?

[[v18-10-7]]

^<<v18-10-7,7>>^ You know that I am not guilty;
And no one can save me from your hand.

[[v18-10-8]]

^<<v18-10-8,8>>^ Your own hands have shaped me and made me,
But now you would completely destroy me.

[[v18-10-9]]

^<<v18-10-9,9>>^ Remember, please, that you made me out of clay,
But now you make me return to dust.

[[v18-10-10]]

^<<v18-10-10,10>>^ Did you not pour me out like milk
And curdle me like cheese?

[[v18-10-11]]

^<<v18-10-11,11>>^ With skin and flesh you clothed me,
And with bones and sinews you wove me together.

[[v18-10-12]]

^<<v18-10-12,12>>^ You have given me life and loyal love;
You have guarded my spirit^&#42;1^ with your care.

[NOTE]
====
. Or “breath; life.”
====

[[v18-10-13]]

^<<v18-10-13,13>>^ But you secretly intended to do these things.^&#42;1^
I know that these things are from you.

[NOTE]
====
. Lit., “And these things you have hidden in your heart.”
====

[[v18-10-14]]

^<<v18-10-14,14>>^ If I sinned, you would watch me,
And you would not acquit me of my error.

[[v18-10-15]]

^<<v18-10-15,15>>^ If I am guilty, too bad for me!
And even if I am innocent, I cannot raise my head,
For I am filled with dishonor and affliction.

[[v18-10-16]]

^<<v18-10-16,16>>^ If I raise my head up, you hunt for me like a lion
And again show your power against me.

[[v18-10-17]]

^<<v18-10-17,17>>^ You bring new witnesses against me
And increase your anger against me,
As hardship after hardship comes upon me.

[[v18-10-18]]

^<<v18-10-18,18>>^ So why did you bring me out from the womb?
I should have died before any eye could see me.

[[v18-10-19]]

^<<v18-10-19,19>>^ It would have been as though I never existed;
I would have been taken straight from the womb to the grave.’

[[v18-10-20]]

^<<v18-10-20,20>>^ Are not my days few? Let him leave me alone;
Let him turn his eyes away from me, so that I may find some relief^&#42;1^

[NOTE]
====
. Or “cheer up a little.”
====

[[v18-10-21]]

^<<v18-10-21,21>>^ Before I go away—and I will not return—
To the land of deepest darkness,^&#42;1^

[NOTE]
====
. Or “of darkness and death’s shadow.”
====

[[v18-10-22]]

^<<v18-10-22,22>>^ To the land of utter gloom,
A land of deep shadow and disorder,
Where even the light is like the gloom.”

'''

xref:018-job/018-job-009.adoc#v18-9-0[&#60; Capítulo Anterior] | <<v18-10-0,Topo>> | xref:018-job/018-job-011.adoc#v18-11-0[Próximo Capítulo &#62;]