include::./index.adoc[]

[[v18-13-0]]
=== Job, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-13-1]]

^<<v18-13-1,1>>^ “Yes, my eye has seen all of this,
My ear has heard and understood it.

[[v18-13-2]]

^<<v18-13-2,2>>^ What you know, I also know;
I am not inferior to you.

[[v18-13-3]]

^<<v18-13-3,3>>^ For my part, I would rather speak to the Almighty himself;
I desire to argue my case with God.

[[v18-13-4]]

^<<v18-13-4,4>>^ But you are smearing me with lies;
All of you are useless physicians.

[[v18-13-5]]

^<<v18-13-5,5>>^ If only you would keep absolutely silent,
That would show wisdom on your part.

[[v18-13-6]]

^<<v18-13-6,6>>^ Listen, please, to my arguments,
And pay attention to the pleadings of my lips.

[[v18-13-7]]

^<<v18-13-7,7>>^ Will you speak unjustly on God’s behalf,
And will you speak deceitfully for him?

[[v18-13-8]]

^<<v18-13-8,8>>^ Will you take his side,^&#42;1^
Will you try to plead the case of the true God?

[NOTE]
====
. Or “show partiality toward him.”
====

[[v18-13-9]]

^<<v18-13-9,9>>^ Would it turn out well if he examined you?
Will you fool him as you would a mortal man?

[[v18-13-10]]

^<<v18-13-10,10>>^ He will surely rebuke you
If you secretly try to show favoritism.

[[v18-13-11]]

^<<v18-13-11,11>>^ Will not his very dignity terrify you
And the dread of him fall upon you?

[[v18-13-12]]

^<<v18-13-12,12>>^ Your wise^&#42;1^ sayings are proverbs of ashes;
Your defenses^&#42;2^ are as fragile as defenses of clay.

[NOTE]
====
. Or “memorable.”
. Lit., “shield bosses.”
====

[[v18-13-13]]

^<<v18-13-13,13>>^ Keep silent before me, so that I may speak.
Then let whatever may come upon me come!

[[v18-13-14]]

^<<v18-13-14,14>>^ Why do I put myself in danger^&#42;1^
And take my life^&#42;2^ in my hands?

[NOTE]
====
. Lit., “Why do I carry my flesh in my teeth?”
. Or “soul.”
====

[[v18-13-15]]

^<<v18-13-15,15>>^ Though he may slay me, I would still wait;
I would argue my case^&#42;1^ before his face.

[NOTE]
====
. Or “defend my ways.”
====

[[v18-13-16]]

^<<v18-13-16,16>>^ He would then become my salvation,
For no godless person^&#42;1^ may come in before him.

[NOTE]
====
. Or “no apostate.”
====

[[v18-13-17]]

^<<v18-13-17,17>>^ Listen closely to my word;
Pay attention to my declaration.

[[v18-13-18]]

^<<v18-13-18,18>>^ See, now, I have prepared my legal case;
I know I am in the right.

[[v18-13-19]]

^<<v18-13-19,19>>^ Who will contend with me?
I would die if I were to stay silent!^&#42;1^

[NOTE]
====
. Or possibly, “If someone can, I will stay silent and die.”
====

[[v18-13-20]]

^<<v18-13-20,20>>^ Only grant two things to me, O God,^&#42;1^
So that I will not conceal myself from before you:

[NOTE]
====
. Lit., “Only two things, do not do to me.”
====

[[v18-13-21]]

^<<v18-13-21,21>>^ Remove your heavy hand far away from me,
And do not let the fear of you terrify me.

[[v18-13-22]]

^<<v18-13-22,22>>^ Either call and I will answer,
Or let me speak, and you answer me.

[[v18-13-23]]

^<<v18-13-23,23>>^ What are my errors and sins?
Reveal to me my transgression and my sin.

[[v18-13-24]]

^<<v18-13-24,24>>^ Why do you hide your face
And consider me your enemy?

[[v18-13-25]]

^<<v18-13-25,25>>^ Will you try to frighten a windblown leaf
Or chase after dry stubble?

[[v18-13-26]]

^<<v18-13-26,26>>^ For you keep recording bitter accusations against me,
And you make me answer for the sins of my youth.

[[v18-13-27]]

^<<v18-13-27,27>>^ You have put my feet in stocks,
You scrutinize all my paths,
And you trace out each of my footprints.

[[v18-13-28]]

^<<v18-13-28,28>>^ So man^&#42;1^ decays like something rotten,
Like a garment eaten by moths.

[NOTE]
====
. Lit., “he,” possibly referring to Job.
====

'''

xref:018-job/018-job-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-job/018-job-014.adoc#v18-14-0[Próximo Capítulo &#62;]