include::./index.adoc[]

[[v18-24-0]]
=== Job, 24
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v18-24-1]]

^<<v18-24-1,1>>^ “Why does the Almighty not set a time?
Why do those who know him not see his day?^&#42;1^

[NOTE]
====
. That is, his day of judgment.
====

[[v18-24-2]]

^<<v18-24-2,2>>^ People move boundary markers;
They carry off flocks for their own pasture.

[[v18-24-3]]

^<<v18-24-3,3>>^ They drive away the donkey of fatherless children
And seize the widow’s bull as security for a loan.^&#42;1^

[NOTE]
====
. Or “as a pledge.”
====

[[v18-24-4]]

^<<v18-24-4,4>>^ They force the poor off the road;
The helpless of the earth must hide from them.

[[v18-24-5]]

^<<v18-24-5,5>>^ The poor forage for food like wild donkeys in the wilderness;
They seek food in the desert for their children.

[[v18-24-6]]

^<<v18-24-6,6>>^ They must harvest in another’s field^&#42;1^
And glean from the vineyard of the wicked.

[NOTE]
====
. Or possibly, “harvest fodder in the field.”
====

[[v18-24-7]]

^<<v18-24-7,7>>^ They spend the night naked, without clothing;
They have no covering for the cold.

[[v18-24-8]]

^<<v18-24-8,8>>^ They are drenched by the mountain rains;
They cling to the rocks for lack of shelter.

[[v18-24-9]]

^<<v18-24-9,9>>^ The fatherless child is snatched away from the breast;
And the garments of the poor are taken as security for a loan,

[[v18-24-10]]

^<<v18-24-10,10>>^ Forcing them to go about naked, without clothing,
And hungry, as they carry the sheaves of grain.

[[v18-24-11]]

^<<v18-24-11,11>>^ They toil among the terrace walls in the heat of the day;^&#42;1^
They tread the winepresses, yet they go thirsty.

[NOTE]
====
. Or possibly, “They press out oil among the terrace walls.”
====

[[v18-24-12]]

^<<v18-24-12,12>>^ The dying keep groaning in the city;
The fatally wounded^&#42;1^ cry for help,
But God does not regard this as improper.^&#42;2^

[NOTE]
====
. Or “souls of the wounded.”
. Or possibly, “God charges no one with wrong.”
====

[[v18-24-13]]

^<<v18-24-13,13>>^ There are those who rebel against light;
They do not recognize its ways,
And they do not follow its paths.

[[v18-24-14]]

^<<v18-24-14,14>>^ The murderer rises at daybreak;
He slays the helpless and the poor,
While at night he engages in theft.

[[v18-24-15]]

^<<v18-24-15,15>>^ The eye of the adulterer waits for the twilight,
Saying, ‘No one will see me!’
And he covers his face.

[[v18-24-16]]

^<<v18-24-16,16>>^ In the darkness they break into^&#42;1^ houses;
By day they shut themselves in.
They are strangers to the light.

[NOTE]
====
. Lit., “dig into.”
====

[[v18-24-17]]

^<<v18-24-17,17>>^ For morning is the same as deep darkness for them;
They are familiar with the terrors of deep darkness.

[[v18-24-18]]

^<<v18-24-18,18>>^ But they are swiftly carried away by the waters.^&#42;1^
Their portion of the land will be cursed.
They will not return to their vineyards.

[NOTE]
====
. Lit., “He is swift on the surface of the waters.”
====

[[v18-24-19]]

^<<v18-24-19,19>>^ Just as drought and heat take away the melted snow,
The Grave^&#42;1^ takes away those who have sinned!

[NOTE]
====
. Or “Sheol,” that is, the common grave of mankind. See Glossary.
====

[[v18-24-20]]

^<<v18-24-20,20>>^ His mother^&#42;1^ will forget him; the maggot will feast on him.
He will be remembered no more.
And unrighteousness will be broken just like a tree.

[NOTE]
====
. Lit., “The womb.”
====

[[v18-24-21]]

^<<v18-24-21,21>>^ He preys on the barren woman,
And mistreats the widow.

[[v18-24-22]]

^<<v18-24-22,22>>^ God^&#42;1^ will use his strength to do away with the powerful;
Though they may rise up, they have no assurance of life.

[NOTE]
====
. Lit., “He.”
====

[[v18-24-23]]

^<<v18-24-23,23>>^ God^&#42;1^ lets them become confident and secure,
But his eyes are on everything they do.^&#42;2^

[NOTE]
====
. Lit., “He.”
. Lit., “on their ways.”
====

[[v18-24-24]]

^<<v18-24-24,24>>^ They are exalted for a little while, then they are no more.
They are brought low and gathered like everyone else;
They are cut off like heads of grain.

[[v18-24-25]]

^<<v18-24-25,25>>^ Now who can prove me a liar
Or refute my word?”

'''

xref:018-job/018-job-023.adoc#v18-23-0[&#60; Capítulo Anterior] | <<v18-24-0,Topo>> | xref:018-job/018-job-025.adoc#v18-25-0[Próximo Capítulo &#62;]