include::./index.adoc[]

[[v16-12-0]]
=== Nehemiah, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v16-12-1]]

^<<v16-12-1,1>>^ These were the priests and the Levites who went up with Ze·rubʹba·bel the son of She·alʹti·el, and Jeshʹu·a: Se·raiʹah, Jeremiah, Ezʹra,

[[v16-12-2]]

^<<v16-12-2,2>>^ Am·a·riʹah, Malʹluch, Hatʹtush,

[[v16-12-3]]

^<<v16-12-3,3>>^ Shec·a·niʹah, Reʹhum, Merʹe·moth,

[[v16-12-4]]

^<<v16-12-4,4>>^ Idʹdo, Ginʹne·thoi, A·biʹjah,

[[v16-12-5]]

^<<v16-12-5,5>>^ Mijʹa·min, Ma·a·diʹah, Bilʹgah,

[[v16-12-6]]

^<<v16-12-6,6>>^ She·maiʹah, Joiʹa·rib, Je·daʹiah,

[[v16-12-7]]

^<<v16-12-7,7>>^ Salʹlu, Aʹmok, Hil·kiʹah, and Je·daʹiah. These were the heads of the priests and their brothers in the days of Jeshʹu·a.

[[v16-12-8]]

^<<v16-12-8,8>>^ The Levites were Jeshʹu·a, Binʹnu·i, Kadʹmi·el, She·re·biʹah, Judah, and Mat·ta·niʹah, who led the songs of thanksgiving along with his brothers.

[[v16-12-9]]

^<<v16-12-9,9>>^ And Bak·bu·kiʹah and Unʹni their brothers stood opposite them for guard duties.^&#42;1^

[NOTE]
====
. Or possibly, “during the service.”
====

[[v16-12-10]]

^<<v16-12-10,10>>^ Jeshʹu·a became father to Joiʹa·kim, and Joiʹa·kim became father to E·liʹa·shib, and E·liʹa·shib to Joiʹa·da.

[[v16-12-11]]

^<<v16-12-11,11>>^ And Joiʹa·da became father to Jonʹa·than, and Jonʹa·than became father to Jadʹdu·a.

[[v16-12-12]]

^<<v16-12-12,12>>^ In the days of Joiʹa·kim, these were the priests, the heads of the paternal houses: for Se·raiʹah, Me·raiʹah; for Jeremiah, Han·a·niʹah;

[[v16-12-13]]

^<<v16-12-13,13>>^ for Ezʹra, Me·shulʹlam; for Am·a·riʹah, Je·ho·haʹnan;

[[v16-12-14]]

^<<v16-12-14,14>>^ for Malʹlu·chi, Jonʹa·than; for Sheb·a·niʹah, Joseph;

[[v16-12-15]]

^<<v16-12-15,15>>^ for Haʹrim, Adʹna; for Me·raʹioth, Helʹkai;

[[v16-12-16]]

^<<v16-12-16,16>>^ for Idʹdo, Zech·a·riʹah; for Ginʹne·thon, Me·shulʹlam;

[[v16-12-17]]

^<<v16-12-17,17>>^ for A·biʹjah, Zichʹri; for Mi·niʹa·min, . . .  ;^&#42;1^ for Mo·a·diʹah, Pilʹtai;

[NOTE]
====
. The Hebrew text evidently omits a name here.
====

[[v16-12-18]]

^<<v16-12-18,18>>^ for Bilʹgah, Sham·muʹa; for She·maiʹah, Je·honʹa·than;

[[v16-12-19]]

^<<v16-12-19,19>>^ for Joiʹa·rib, Mat·teʹnai; for Je·daʹiah, Uzʹzi;

[[v16-12-20]]

^<<v16-12-20,20>>^ for Sal·laʹi, Kalʹlai; for Aʹmok, Eʹber;

[[v16-12-21]]

^<<v16-12-21,21>>^ for Hil·kiʹah, Hash·a·biʹah; for Je·daʹiah, Ne·thanʹel.

[[v16-12-22]]

^<<v16-12-22,22>>^ The heads of the paternal houses of the Levites in the days of E·liʹa·shib, Joiʹa·da, Jo·haʹnan, and Jadʹdu·a were recorded, as were the priests, down to the kingship of Da·riʹus the Persian.

[[v16-12-23]]

^<<v16-12-23,23>>^ The Levites who were heads of the paternal houses were recorded in the book of the history of the times, down to the days of Jo·haʹnan the son of E·liʹa·shib.

[[v16-12-24]]

^<<v16-12-24,24>>^ The heads of the Levites were Hash·a·biʹah, She·re·biʹah, and Jeshʹu·a the son of Kadʹmi·el, and their brothers stood opposite them to offer praise and give thanks according to the instructions of David the man of the true God, guard group corresponding to guard group.

[[v16-12-25]]

^<<v16-12-25,25>>^ Mat·ta·niʹah, Bak·bu·kiʹah, O·ba·diʹah, Me·shulʹlam, Talʹmon, and Akʹkub were standing guard as gatekeepers, guarding the storerooms by the gates.

[[v16-12-26]]

^<<v16-12-26,26>>^ These served in the days of Joiʹa·kim the son of Jeshʹu·a the son of Joʹza·dak and in the days of Ne·he·miʹah the governor and Ezʹra the priest and copyist.^&#42;1^

[NOTE]
====
. Or “scribe.”
====

[[v16-12-27]]

^<<v16-12-27,27>>^ At the inauguration of the walls of Jerusalem, they sought the Levites and brought them to Jerusalem from all the places they lived to celebrate the inauguration with rejoicing, with songs of thanksgiving, and with cymbals, stringed instruments, and harps.

[[v16-12-28]]

^<<v16-12-28,28>>^ And the sons of the singers^&#42;1^ gathered together from the district,^&#42;2^ from all around Jerusalem, from the settlements of the Ne·tophʹa·thites,

[NOTE]
====
. Or “And the trained singers.”
. That is, the district around the Jordan.
====

[[v16-12-29]]

^<<v16-12-29,29>>^ from Beth-gilʹgal, and from the fields of Geʹba and Azʹma·veth, for the singers had built settlements for themselves all around Jerusalem.

[[v16-12-30]]

^<<v16-12-30,30>>^ And the priests and the Levites purified themselves, and they purified the people, the gates, and the wall.

[[v16-12-31]]

^<<v16-12-31,31>>^ Then I brought the princes of Judah up on top of the wall. Further, I appointed two large thanksgiving choirs and processions, and the one walked to the right on the wall toward the Gate of the Ash Heaps.

[[v16-12-32]]

^<<v16-12-32,32>>^ Ho·shaiʹah and half of the princes of Judah walked behind them,

[[v16-12-33]]

^<<v16-12-33,33>>^ along with Az·a·riʹah, Ezʹra, Me·shulʹlam,

[[v16-12-34]]

^<<v16-12-34,34>>^ Judah, Benjamin, She·maiʹah, and Jeremiah.

[[v16-12-35]]

^<<v16-12-35,35>>^ With them were some of the sons of the priests with the trumpets: Zech·a·riʹah son of Jonʹa·than son of She·maiʹah son of Mat·ta·niʹah son of Mi·caiʹah son of Zacʹcur son of Aʹsaph,

[[v16-12-36]]

^<<v16-12-36,36>>^ and his brothers She·maiʹah, Azʹar·el, Milʹa·lai, Gilʹa·lai, Maʹai, Ne·thanʹel, Judah, and Ha·naʹni, with the musical instruments of David the man of the true God; and Ezʹra the copyist^&#42;1^ went before them.

[NOTE]
====
. Or “scribe.”
====

[[v16-12-37]]

^<<v16-12-37,37>>^ At the Fountain Gate they went straight ahead up the Stairway of the City of David by the ascent of the wall above the House of David and on to the Water Gate to the east.

[[v16-12-38]]

^<<v16-12-38,38>>^ The other thanksgiving choir walked in the opposite direction,^&#42;1^ and I followed it with half of the people, on the wall up over the Tower of the Ovens and on to the Broad Wall

[NOTE]
====
. Or “in front.”
====

[[v16-12-39]]

^<<v16-12-39,39>>^ and up over the Gate of Eʹphra·im and on to the Gate of the Old City and on to the Fish Gate, the Tower of Ha·nanʹel, the Tower of Meʹah, and on to the Sheep Gate; and they came to a halt at the Gate of the Guard.

[[v16-12-40]]

^<<v16-12-40,40>>^ At length the two thanksgiving choirs stood before the house of the true God; so did I and half of the deputy rulers with me,

[[v16-12-41]]

^<<v16-12-41,41>>^ and the priests E·liʹa·kim, Ma·a·seiʹah, Mi·niʹa·min, Mi·caiʹah, Eli·o·eʹnai, Zech·a·riʹah, and Han·a·niʹah, with the trumpets,

[[v16-12-42]]

^<<v16-12-42,42>>^ and Ma·a·seiʹah, She·maiʹah, El·e·aʹzar, Uzʹzi, Je·ho·haʹnan, Mal·chiʹjah, Eʹlam, and Eʹzer. And the singers sang loudly under the oversight of Iz·ra·hiʹah.

[[v16-12-43]]

^<<v16-12-43,43>>^ On that day they offered great sacrifices and rejoiced, for the true God made them rejoice with great joy. The women and the children also rejoiced, so that the rejoicing of Jerusalem could be heard far away.

[[v16-12-44]]

^<<v16-12-44,44>>^ On that day men were appointed over the storehouses for the contributions, the firstfruits, and the tenths.^&#42;1^ Into them they were to gather from the fields of the cities the portions required by the Law for the priests and the Levites, for there was rejoicing in Judah because of the priests and the Levites who were ministering.

[NOTE]
====
. Or “tithes.”
====

[[v16-12-45]]

^<<v16-12-45,45>>^ And they began taking care of the duties of their God and the obligation of the purification, as did the singers and the gatekeepers, according to the instructions of David and his son Solʹo·mon.

[[v16-12-46]]

^<<v16-12-46,46>>^ For long ago in the days of David and Aʹsaph, there were directors^&#42;1^ for the singers and for the songs of praise and thanksgiving to God.

[NOTE]
====
. Lit., “heads.”
====

[[v16-12-47]]

^<<v16-12-47,47>>^ And during the days of Ze·rubʹba·bel and during the days of Ne·he·miʹah, all Israel gave portions to the singers and the gatekeepers, according to the daily need. They also set aside the portion for the Levites, and the Levites set aside the portion for the descendants of Aaron.

'''

xref:016-nehemiah/016-nehemiah-011.adoc#v16-11-0[&#60; Capítulo Anterior] | <<v16-12-0,Topo>> | xref:016-nehemiah/016-nehemiah-013.adoc#v16-13-0[Próximo Capítulo &#62;]