include::./index.adoc[]

[[v16-3-0]]
=== Nehemiah, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v16-3-1]]

^<<v16-3-1,1>>^ E·liʹa·shib the high priest and his brothers the priests got up to build the Sheep Gate. They sanctified^&#42;1^ it and set up its doors; they sanctified it as far as the Tower of Meʹah, as far as the Tower of Ha·nanʹel.

[NOTE]
====
. Or “dedicated.”
====

[[v16-3-2]]

^<<v16-3-2,2>>^ And next to them the men of Jerʹi·cho were building; and next to them Zacʹcur the son of Imʹri was building.

[[v16-3-3]]

^<<v16-3-3,3>>^ The sons of Has·se·naʹah built the Fish Gate; they timbered it and then set up its doors, its bolts, and its bars.

[[v16-3-4]]

^<<v16-3-4,4>>^ And next to them Merʹe·moth the son of U·riʹjah the son of Hakʹkoz did repair work, and next to them Me·shulʹlam the son of Ber·e·chiʹah the son of Me·shezʹa·bel did repair work, and next to them Zaʹdok the son of Baʹa·na did repair work.

[[v16-3-5]]

^<<v16-3-5,5>>^ And next to them the Te·koʹites did repair work, but their prominent men would not lower themselves to share in^&#42;1^ the service of their masters.

[NOTE]
====
. Lit., “not bring their neck into.”
====

[[v16-3-6]]

^<<v16-3-6,6>>^ Joiʹa·da the son of Pa·seʹah and Me·shulʹlam the son of Bes·o·deiʹah repaired the Gate of the Old City; they timbered it and then set up its doors, its bolts, and its bars.

[[v16-3-7]]

^<<v16-3-7,7>>^ Next to them Mel·a·tiʹah the Gibʹe·on·ite and Jaʹdon the Me·ronʹo·thite did repair work, men of Gibʹe·on and Mizʹpah who were under the authority of^&#42;1^ the governor of the region Beyond the River.^&#42;2^

[NOTE]
====
. Lit., “belonging to the throne of.”
. Or “of Trans-Euphrates.”
====

[[v16-3-8]]

^<<v16-3-8,8>>^ Next to them Uzʹzi·el the son of Har·haiʹah, one of the goldsmiths, did repair work, and next to him Han·a·niʹah, one of the ointment mixers,^&#42;1^ did repair work; and they paved^&#42;2^ Jerusalem as far as the Broad Wall.

[NOTE]
====
. Or “the perfume makers.”
. Or “paved with flagstone.”
====

[[v16-3-9]]

^<<v16-3-9,9>>^ And next to them Re·phaʹiah the son of Hur, a prince of half the district of Jerusalem, did repair work.

[[v16-3-10]]

^<<v16-3-10,10>>^ And next to them Je·daʹiah the son of Ha·ruʹmaph did repair work in front of his own house, and next to him Hatʹtush the son of Hash·ab·neiʹah did repair work.

[[v16-3-11]]

^<<v16-3-11,11>>^ Mal·chiʹjah the son of Haʹrim and Hasʹshub the son of Paʹhath-moʹab repaired another section,^&#42;1^ as well as the Tower of the Ovens.

[NOTE]
====
. Or “measured section.”
====

[[v16-3-12]]

^<<v16-3-12,12>>^ And next to them Shalʹlum the son of Hal·loʹhesh, a prince of half the district of Jerusalem, did repair work, along with his daughters.

[[v16-3-13]]

^<<v16-3-13,13>>^ Haʹnun and the inhabitants of Za·noʹah repaired the Valley Gate; they built it and then set up its doors, its bolts, and its bars, and they repaired 1,000 cubits^&#42;1^ of the wall as far as the Gate of the Ash Heaps.

[NOTE]
====
. About 445 m (1,460 ft). See App. B14.
====

[[v16-3-14]]

^<<v16-3-14,14>>^ Mal·chiʹjah the son of Reʹchab, a prince of the district of Beth-hac·cheʹrem, repaired the Gate of the Ash Heaps; he built it and set up its doors, its bolts, and its bars.

[[v16-3-15]]

^<<v16-3-15,15>>^ Shalʹlun the son of Col·hoʹzeh, a prince of the district of Mizʹpah, repaired the Fountain Gate; he built it and its roof, set up its doors, its bolts, and its bars, and also repaired the wall of the Pool of the Canal to the King’s Garden and as far as the Stairway that goes down from the City of David.

[[v16-3-16]]

^<<v16-3-16,16>>^ After him Ne·he·miʹah the son of Azʹbuk, a prince of half the district of Beth-zur, did repair work from in front of the Burial Places of David as far as the pool that had been built and as far as the House of the Mighty Ones.

[[v16-3-17]]

^<<v16-3-17,17>>^ After him the Levites did repair work: Reʹhum the son of Baʹni; and next to him Hash·a·biʹah, a prince of half the district of Keiʹlah, did repair work for his district.

[[v16-3-18]]

^<<v16-3-18,18>>^ After him their brothers did repair work: Bavʹvai the son of Henʹa·dad, a prince of half the district of Keiʹlah.

[[v16-3-19]]

^<<v16-3-19,19>>^ And next to him Eʹzer the son of Jeshʹu·a, a prince of Mizʹpah, was repairing another section in front of the ascent to the Armory at the Buttress.

[[v16-3-20]]

^<<v16-3-20,20>>^ After him Barʹuch the son of Zabʹbai worked with fervor and repaired another section, from the Buttress as far as the entrance of the house of E·liʹa·shib the high priest.

[[v16-3-21]]

^<<v16-3-21,21>>^ After him Merʹe·moth the son of U·riʹjah the son of Hakʹkoz repaired another section, from the entrance of the house of E·liʹa·shib as far as the end of E·liʹa·shib’s house.

[[v16-3-22]]

^<<v16-3-22,22>>^ And after him the priests, men of the district of the Jordan,^&#42;1^ did repair work.

[NOTE]
====
. Or possibly, “the nearby district.”
====

[[v16-3-23]]

^<<v16-3-23,23>>^ After them Benjamin and Hasʹshub did repair work in front of their own house. After them Az·a·riʹah the son of Ma·a·seiʹah the son of A·na·niʹah did repair work near his own house.

[[v16-3-24]]

^<<v16-3-24,24>>^ After him Binʹnu·i the son of Henʹa·dad repaired another section, from the house of Az·a·riʹah as far as the Buttress and as far as the corner.

[[v16-3-25]]

^<<v16-3-25,25>>^ After him Paʹlal the son of Uʹzai did repair work in front of the Buttress and the tower that goes out from the King’s House,^&#42;1^ the upper one that belongs to the Courtyard of the Guard. After him there was Pe·daiʹah the son of Paʹrosh.

[NOTE]
====
. Or “Palace.”
====

[[v16-3-26]]

^<<v16-3-26,26>>^ And the temple servants^&#42;1^ who lived in Oʹphel did repair work as far as in front of the Water Gate on the east and the protruding tower.

[NOTE]
====
. Or “the Nethinim.” Lit., “the given ones.”
====

[[v16-3-27]]

^<<v16-3-27,27>>^ After them the Te·koʹites repaired another section, from in front of the great protruding tower as far as the wall of Oʹphel.

[[v16-3-28]]

^<<v16-3-28,28>>^ The priests did repair work above the Horse Gate, each in front of his own house.

[[v16-3-29]]

^<<v16-3-29,29>>^ After them Zaʹdok the son of Imʹmer did repair work in front of his own house.
And after him She·maiʹah the son of Shec·a·niʹah, the keeper of the East Gate, did repair work.

[[v16-3-30]]

^<<v16-3-30,30>>^ After him Han·a·niʹah the son of Shel·e·miʹah and Haʹnun the sixth son of Zaʹlaph repaired another section.
After him Me·shulʹlam the son of Ber·e·chiʹah did repair work in front of his own hall.

[[v16-3-31]]

^<<v16-3-31,31>>^ After him Mal·chiʹjah, a member of the goldsmith guild, did repair work as far as the house of the temple servants^&#42;1^ and the traders, in front of the Inspection Gate and as far as the roof chamber of the corner.

[NOTE]
====
. Or “the Nethinim.” Lit., “the given ones.”
====

[[v16-3-32]]

^<<v16-3-32,32>>^ And between the roof chamber of the corner and the Sheep Gate, the goldsmiths and the traders did repair work.

'''

xref:016-nehemiah/016-nehemiah-002.adoc#v16-2-0[&#60; Capítulo Anterior] | <<v16-3-0,Topo>> | xref:016-nehemiah/016-nehemiah-004.adoc#v16-4-0[Próximo Capítulo &#62;]