include::./index.adoc[]

[[v16-5-0]]
=== Nehemiah, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v16-5-1]]

^<<v16-5-1,1>>^ However, there was a great outcry from the people and their wives against their Jewish brothers.

[[v16-5-2]]

^<<v16-5-2,2>>^ Some were saying: “We are many with our sons and our daughters. We must get grain in order to eat and stay alive.”

[[v16-5-3]]

^<<v16-5-3,3>>^ Others were saying: “We are giving our fields and our vineyards and our houses as security to get grain during the food shortage.”

[[v16-5-4]]

^<<v16-5-4,4>>^ Still others were saying: “We have borrowed money on our fields and our vineyards for the king’s tribute.

[[v16-5-5]]

^<<v16-5-5,5>>^ Now we are of the same flesh and blood as our brothers,^&#42;1^ and our children are just like their children; yet we have to subject our sons and daughters to slavery, and some of our daughters are already in slavery. But we are powerless to stop this, because our fields and our vineyards belong to others.”

[NOTE]
====
. Lit., “like the flesh of our brothers is our flesh.”
====

[[v16-5-6]]

^<<v16-5-6,6>>^ I became very angry when I heard their outcry and these words.

[[v16-5-7]]

^<<v16-5-7,7>>^ So I considered these things in my heart, and I took issue with the nobles and the deputy rulers and said to them: “Each one of you is demanding interest^&#42;1^ from your own brother.”
Further, I arranged for a great assembly because of them.

[NOTE]
====
. Or “usury.”
====

[[v16-5-8]]

^<<v16-5-8,8>>^ And I said to them: “To the extent possible, we have bought back our own Jewish brothers who were sold to the nations; but will you now sell your own brothers, and are they to be sold back to us?” At this they became speechless, and they could find nothing to say.

[[v16-5-9]]

^<<v16-5-9,9>>^ Then I said: “What you are doing is not good. Should you not walk in the fear of our God so that the nations, our enemies, cannot reproach us?

[[v16-5-10]]

^<<v16-5-10,10>>^ Moreover, I, my brothers, and my attendants are lending them money and grain. Let us, please, stop this lending on interest.

[[v16-5-11]]

^<<v16-5-11,11>>^ Please, restore to them on this very day their fields, their vineyards, their olive groves, and their houses, as well as the hundredth^&#42;1^ of the money, the grain, the new wine, and the oil that you are demanding as interest from them.”

[NOTE]
====
. Or “1 percent,” that is, monthly.
====

[[v16-5-12]]

^<<v16-5-12,12>>^ To this they said: “We will restore these things to them and ask nothing back. We will do precisely as you say.” So I called the priests and made those men swear to keep this promise.

[[v16-5-13]]

^<<v16-5-13,13>>^ Also, I shook out the folds of my garment^&#42;1^ and said: “In this manner may the true God shake out from his house and from his possessions every man who does not carry out this promise, and in this manner may he be shaken out and emptied.” To this all the congregation said: “Amen!”^&#42;2^ And they praised Jehovah, and the people did as they promised.

[NOTE]
====
. Lit., “shook out my bosom.”
. Or “So be it!”
====

[[v16-5-14]]

^<<v16-5-14,14>>^ Moreover, from the day that he commissioned me to become their governor in the land of Judah, from the 20th year to the 32nd year of King Ar·ta·xerxʹes, 12 years, neither I nor my brothers ate the food allowance due the governor.

[[v16-5-15]]

^<<v16-5-15,15>>^ But the former governors who were before me had burdened the people and had been taking from them 40 silver shekels^&#42;1^ for bread and wine each day. Also, their attendants had oppressed the people. But I did not do that because of the fear of God.

[NOTE]
====
. A shekel equaled 11.4 g (0.367 oz t). See App. B14.
====

[[v16-5-16]]

^<<v16-5-16,16>>^ Furthermore, I took a hand in the work on this wall, and not a field did we acquire; all my attendants were gathered there for the work.

[[v16-5-17]]

^<<v16-5-17,17>>^ There were 150 Jews and deputy rulers dining at my table, as well as those who came to us from the nations.

[[v16-5-18]]

^<<v16-5-18,18>>^ Every day one bull, six choice sheep, and birds were prepared for me,^&#42;1^ and once every ten days we had all sorts of wine in abundance. Despite all this I did not demand the food allowance due the governor, because the people were already bearing their burden of service.

[NOTE]
====
. Or “at my expense.”
====

[[v16-5-19]]

^<<v16-5-19,19>>^ Do remember me favorably,^&#42;1^ O my God, for all that I have done in behalf of this people.

[NOTE]
====
. Or “for good.”
====

'''

xref:016-nehemiah/016-nehemiah-004.adoc#v16-4-0[&#60; Capítulo Anterior] | <<v16-5-0,Topo>> | xref:016-nehemiah/016-nehemiah-006.adoc#v16-6-0[Próximo Capítulo &#62;]