include::./index.adoc[]

[[v16-4-0]]
=== Nehemiah, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v16-4-1]]

^<<v16-4-1,1>>^ Now as soon as San·balʹlat heard that we were rebuilding the wall, he became angry and very upset,^&#42;1^ and he kept mocking the Jews.

[NOTE]
====
. Or “offended.”
====

[[v16-4-2]]

^<<v16-4-2,2>>^ And in the presence of his brothers and the army of Sa·marʹi·a, he said: “What are the feeble Jews doing? Will they do this by themselves? Will they offer sacrifices? Will they finish up in a day? Will they bring the charred stones to life out of the heaps of dusty rubble?”

[[v16-4-3]]

^<<v16-4-3,3>>^ Now To·biʹah the Amʹmon·ite, who was standing beside him, said: “If even a fox would climb up on what they are building, it would knock down their stone wall.”

[[v16-4-4]]

^<<v16-4-4,4>>^ Hear, O our God, for we are being treated with contempt, and make their reproach return on their own heads, and give them over as plunder in a land of captivity.

[[v16-4-5]]

^<<v16-4-5,5>>^ And do not cover over their guilt or let their sin be erased from before you, for they have insulted the builders.

[[v16-4-6]]

^<<v16-4-6,6>>^ So we kept building the wall, and the entire wall was joined together and rebuilt up to half its height, and the people continued to put their heart into the work.

[[v16-4-7]]

^<<v16-4-7,7>>^ Now as soon as San·balʹlat, To·biʹah, the Arabians, the Amʹmon·ites, and the Ashʹdod·ites heard that the repairing of the walls of Jerusalem was progressing and that the gaps were being filled in, they became very angry.

[[v16-4-8]]

^<<v16-4-8,8>>^ They conspired together to come and fight against Jerusalem and to create a disturbance in it.

[[v16-4-9]]

^<<v16-4-9,9>>^ But we prayed to our God and kept a guard posted against them day and night.

[[v16-4-10]]

^<<v16-4-10,10>>^ However, people of Judah were saying: “The strength of the laborers^&#42;1^ has failed, and there is so much rubble; we will never be able to build the wall.”

[NOTE]
====
. Or “burden bearers.”
====

[[v16-4-11]]

^<<v16-4-11,11>>^ And our enemies kept saying: “Before they know it or see us, we will come right in among them and kill them and stop the work.”

[[v16-4-12]]

^<<v16-4-12,12>>^ Whenever the Jews living near them came in, they told us again and again:^&#42;1^ “They will come at us from all directions.”

[NOTE]
====
. Lit., “ten times.”
====

[[v16-4-13]]

^<<v16-4-13,13>>^ So I kept men posted at the lowest parts of the space behind the wall at the exposed places, and I posted them by families with their swords, their lances, and their bows.

[[v16-4-14]]

^<<v16-4-14,14>>^ When I saw their fear, I immediately rose and said to the nobles and the deputy rulers and the rest of the people: “Do not be afraid of them. Remember Jehovah, who is great and awe-inspiring; and fight for your brothers, your sons and daughters, your wives and homes.”

[[v16-4-15]]

^<<v16-4-15,15>>^ Now after our enemies heard that what they were doing had become known to us and that the true God had frustrated their plan, we all went back to work on the wall.

[[v16-4-16]]

^<<v16-4-16,16>>^ From that day forward, half of my men would do the work and half of them would hold the lances, the shields, the bows, and the coats of mail. And the princes stood behind the whole house of Judah

[[v16-4-17]]

^<<v16-4-17,17>>^ who were building the wall. Those who were carrying the loads did the work with one hand while holding a weapon^&#42;1^ in the other hand.

[NOTE]
====
. Or “missile.”
====

[[v16-4-18]]

^<<v16-4-18,18>>^ And each of the builders had a sword strapped to his hip while building, and the one to blow the horn stood beside me.

[[v16-4-19]]

^<<v16-4-19,19>>^ I then said to the nobles and the deputy rulers and the rest of the people: “The work is large and extensive, and we are spread out on the wall far apart from one another.

[[v16-4-20]]

^<<v16-4-20,20>>^ When you hear the sound of the horn, gather together to where we are. Our God will fight for us.”

[[v16-4-21]]

^<<v16-4-21,21>>^ So we kept working while the other half were holding the lances, from the break of dawn until the stars came out.

[[v16-4-22]]

^<<v16-4-22,22>>^ At that time I said to the people: “Let the men, each along with his attendant, spend the night inside Jerusalem, and they will guard us by night and work during the day.”

[[v16-4-23]]

^<<v16-4-23,23>>^ So neither I nor my brothers, my attendants, and the guards who followed me ever took off our garments, and each of us kept his weapon in his right hand.

'''

xref:016-nehemiah/016-nehemiah-003.adoc#v16-3-0[&#60; Capítulo Anterior] | <<v16-4-0,Topo>> | xref:016-nehemiah/016-nehemiah-005.adoc#v16-5-0[Próximo Capítulo &#62;]