include::./index.adoc[]

[[v16-6-0]]
=== Nehemiah, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v16-6-1]]

^<<v16-6-1,1>>^ Now as soon as San·balʹlat, To·biʹah, Geʹshem the Arabian, and the rest of our enemies were told that I had rebuilt the wall and that there were no gaps left in it (although up to that time I had not set up the doors in the gates),

[[v16-6-2]]

^<<v16-6-2,2>>^ San·balʹlat and Geʹshem immediately sent this message to me: “Come, and let us set a time to meet together in the villages of the Valley Plain of Oʹno.” But they were scheming to harm me.

[[v16-6-3]]

^<<v16-6-3,3>>^ So I sent messengers to them, saying: “I am engaged in a great work, and I am not able to go down. Why should the work stop while I leave it to come to you?”

[[v16-6-4]]

^<<v16-6-4,4>>^ They sent me the same message four times, and I gave them the same reply each time.

[[v16-6-5]]

^<<v16-6-5,5>>^ Then San·balʹlat sent his attendant to me with the same message a fifth time, with an open letter in his hand.

[[v16-6-6]]

^<<v16-6-6,6>>^ There it was written: “Among the nations it has been heard, and Geʹshem is also saying it, that you and the Jews are scheming to rebel. That is why you are building the wall; and according to these reports you are to become their king.

[[v16-6-7]]

^<<v16-6-7,7>>^ Also, you have appointed prophets to proclaim about you throughout Jerusalem, ‘There is a king in Judah!’ And now these things will be told to the king. So come, and let us discuss this together.”

[[v16-6-8]]

^<<v16-6-8,8>>^ However, I sent him this reply: “None of the things you are saying have taken place; you are making them up out of your own imagination.”^&#42;1^

[NOTE]
====
. Lit., “from your heart.”
====

[[v16-6-9]]

^<<v16-6-9,9>>^ For they were all trying to frighten us, saying: “Their hands will slacken in the work, and it will not be done.” Now, I pray, strengthen my hands.

[[v16-6-10]]

^<<v16-6-10,10>>^ Then I went to the house of She·maiʹah the son of De·laʹiah the son of Me·hetʹa·bel while he was confined there. He said: “Let us set a time to meet at the house of the true God, within the temple, and let us close the doors of the temple, for they are coming to kill you. They are coming to kill you by night.”

[[v16-6-11]]

^<<v16-6-11,11>>^ But I said: “Should a man like me run away? Can a man like me go into the temple and live? I will not go in!”

[[v16-6-12]]

^<<v16-6-12,12>>^ Then I realized that God had not sent him, but that To·biʹah and San·balʹlat had hired him to speak this prophecy against me.

[[v16-6-13]]

^<<v16-6-13,13>>^ He had been hired to frighten me and to cause me to sin, so that they would have grounds to damage my reputation in order to reproach me.

[[v16-6-14]]

^<<v16-6-14,14>>^ Do remember, O my God, To·biʹah and San·balʹlat and these deeds, and also No·a·diʹah the prophetess and the rest of the prophets who were constantly trying to frighten me.

[[v16-6-15]]

^<<v16-6-15,15>>^ So the wall was completed on the 25th day of Eʹlul,^&#42;1^ in 52 days.

[NOTE]
====
. See App. B15.
====

[[v16-6-16]]

^<<v16-6-16,16>>^ As soon as all our enemies heard of it and all the surrounding nations saw it, they became greatly ashamed,^&#42;1^ and they realized that it was with our God’s help that this work had been done.

[NOTE]
====
. Lit., “they fell greatly in their own eyes.”
====

[[v16-6-17]]

^<<v16-6-17,17>>^ In those days the nobles of Judah were sending many letters to To·biʹah, and To·biʹah would reply to them.

[[v16-6-18]]

^<<v16-6-18,18>>^ Many in Judah swore allegiance to him, for he was a son-in-law of Shec·a·niʹah the son of Aʹrah, and his son Je·ho·haʹnan had married the daughter of Me·shulʹlam the son of Ber·e·chiʹah.

[[v16-6-19]]

^<<v16-6-19,19>>^ Also, they would constantly tell me good things about him and then report to him what I said. Then To·biʹah would send letters to frighten me.

'''

xref:016-nehemiah/016-nehemiah-005.adoc#v16-5-0[&#60; Capítulo Anterior] | <<v16-6-0,Topo>> | xref:016-nehemiah/016-nehemiah-007.adoc#v16-7-0[Próximo Capítulo &#62;]