include::./index.adoc[]

[[v16-13-0]]
=== Nehemiah, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v16-13-1]]

^<<v16-13-1,1>>^ On that day the book of Moses was read in the hearing of the people, and it was found written that no Amʹmon·ite or Moʹab·ite should ever enter the congregation of the true God,

[[v16-13-2]]

^<<v16-13-2,2>>^ for they had not met the Israelites with bread and water, but instead they had hired Baʹlaam against them to curse them. However, our God had changed the curse into a blessing.

[[v16-13-3]]

^<<v16-13-3,3>>^ As soon as they heard the Law, they began to separate from Israel all those of foreign descent.^&#42;1^

[NOTE]
====
. Or “mixed descent.”
====

[[v16-13-4]]

^<<v16-13-4,4>>^ Now before this, the priest in charge of the storerooms^&#42;1^ of the house^&#42;2^ of our God was E·liʹa·shib, a relative of To·biʹah.

[NOTE]
====
. Or “dining halls.”
. Or “temple.”
====

[[v16-13-5]]

^<<v16-13-5,5>>^ He had made available for him a large storeroom,^&#42;1^ where previously they used to put the grain offering, the frankincense, and the utensils and the tenth^&#42;2^ of the grain, the new wine, and the oil, to which the Levites, the singers, and the gatekeepers are entitled, along with the contribution for the priests.

[NOTE]
====
. Or “dining hall.”
. Or “tithe.”
====

[[v16-13-6]]

^<<v16-13-6,6>>^ And during all this time I was not in Jerusalem, for I went to the king in the 32nd year of King Ar·ta·xerxʹes of Babylon; and sometime later I asked the king for a leave of absence.

[[v16-13-7]]

^<<v16-13-7,7>>^ Then I came to Jerusalem and noticed the terrible thing that E·liʹa·shib had done in behalf of To·biʹah, making a storeroom available for him in the courtyard of the house of the true God.

[[v16-13-8]]

^<<v16-13-8,8>>^ This was very displeasing to me, so I threw all of To·biʹah’s household furniture out of the storeroom.^&#42;1^

[NOTE]
====
. Or “dining hall.”
====

[[v16-13-9]]

^<<v16-13-9,9>>^ After that I gave orders, and they cleansed the storerooms;^&#42;1^ and I put back there the utensils of the house of the true God, with the grain offering and the frankincense.

[NOTE]
====
. Or “dining halls.”
====

[[v16-13-10]]

^<<v16-13-10,10>>^ I also found out that the portions of the Levites had not been given them, so that the Levites and the singers who did the work had gone off, each to his own field.

[[v16-13-11]]

^<<v16-13-11,11>>^ So I reprimanded the deputy rulers and said: “Why has the house of the true God been neglected?” Then I gathered them together and assigned them back to their posts.

[[v16-13-12]]

^<<v16-13-12,12>>^ And all Judah brought in the tenth of the grain, the new wine, and the oil to the storerooms.

[[v16-13-13]]

^<<v16-13-13,13>>^ Then I put Shel·e·miʹah the priest, Zaʹdok the copyist,^&#42;1^ and Pe·daiʹah of the Levites in charge of the storerooms, and Haʹnan the son of Zacʹcur the son of Mat·ta·niʹah was their assistant, for these men were considered reliable. It was their responsibility to make the distribution to their brothers.

[NOTE]
====
. Or “scribe.”
====

[[v16-13-14]]

^<<v16-13-14,14>>^ Do remember me, O my God, concerning this, and do not wipe out my acts of loyal love that I have done for the house of my God and its services.^&#42;1^

[NOTE]
====
. Or “guardianship.”
====

[[v16-13-15]]

^<<v16-13-15,15>>^ In those days I saw people in Judah treading winepresses on the Sabbath, bringing in heaps of grain and loading them on donkeys, and bringing wine, grapes, figs, and every sort of load into Jerusalem on the Sabbath day. So I warned them against selling provisions on that day.^&#42;1^

[NOTE]
====
. Or possibly, “warned them on that day not to sell provisions.”
====

[[v16-13-16]]

^<<v16-13-16,16>>^ And the Tyrʹi·ans who lived in the city were bringing in fish and all kinds of merchandise, selling them to the people of Judah and in Jerusalem on the Sabbath.

[[v16-13-17]]

^<<v16-13-17,17>>^ So I reprimanded the nobles of Judah and said to them: “What is this evil thing that you are doing, even profaning the Sabbath day?

[[v16-13-18]]

^<<v16-13-18,18>>^ Was not this what your forefathers did, so that our God brought all this disaster on us and also on this city? Now you are adding to the burning anger against Israel by profaning the Sabbath.”

[[v16-13-19]]

^<<v16-13-19,19>>^ So as soon as the shadows began to fall on the gates of Jerusalem before the Sabbath, I ordered that the doors be closed. I also said that they should not open them until after the Sabbath, and I stationed some of my own attendants at the gates so that no loads would be brought in on the Sabbath day.

[[v16-13-20]]

^<<v16-13-20,20>>^ So the traders and the sellers of all kinds of merchandise spent the night outside Jerusalem once or twice.

[[v16-13-21]]

^<<v16-13-21,21>>^ Then I warned them and said to them: “Why are you spending the night in front of the wall? If you do it again, I will use force against you.” From that time on they did not come on the Sabbath.

[[v16-13-22]]

^<<v16-13-22,22>>^ And I told the Levites that they should regularly purify themselves and come and guard the gates to keep the Sabbath day holy. This, also, do remember to my credit, O my God, and show me pity according to your abundant loyal love.

[[v16-13-23]]

^<<v16-13-23,23>>^ In those days I also saw Jews who had married^&#42;1^ Ashʹdod·ite, Amʹmon·ite, and Moʹab·ite women.

[NOTE]
====
. Or “had taken into their houses.”
====

[[v16-13-24]]

^<<v16-13-24,24>>^ Half of their sons were speaking Ashʹdod·ite and half spoke the language of the different peoples, but none of them knew how to speak the language of the Jews.

[[v16-13-25]]

^<<v16-13-25,25>>^ So I reprimanded them and called down a curse on them and struck some of the men and pulled out their hair and made them swear by God: “You should not give your daughters to their sons, and you should not accept any of their daughters for your sons or yourselves.

[[v16-13-26]]

^<<v16-13-26,26>>^ Was it not because of these that King Solʹo·mon of Israel sinned? Among the many nations there was no king like him; and he was loved by his God, so that God made him king over all Israel. But the foreign wives caused even him to sin.

[[v16-13-27]]

^<<v16-13-27,27>>^ Is it not something unheard of for you to commit this great evil in acting unfaithfully against our God by marrying foreign women?”

[[v16-13-28]]

^<<v16-13-28,28>>^ One of the sons of Joiʹa·da the son of E·liʹa·shib the high priest had become a son-in-law of San·balʹlat the Horʹo·nite. So I drove him away from me.

[[v16-13-29]]

^<<v16-13-29,29>>^ Do remember them, O my God, because they have defiled the priesthood and the covenant of the priesthood and the Levites.

[[v16-13-30]]

^<<v16-13-30,30>>^ And I purified them from every foreign defilement, and I assigned duties to the priests and to the Levites, each to his own service,

[[v16-13-31]]

^<<v16-13-31,31>>^ and arranged for the supply of the wood at appointed times and for the first ripe fruits.
Do remember me favorably,^&#42;1^ O my God.

[NOTE]
====
. Or “for good.”
====

'''

xref:016-nehemiah/016-nehemiah-012.adoc#v16-12-0[&#60; Capítulo Anterior] | <<v16-13-0,Topo>> | xref:017-esther/017-esther-001.adoc#v17-1-0[Próximo Capítulo &#62;]