include::./index.adoc[]

[[v16-1-0]]
=== Nehemiah, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v16-1-1]]

^<<v16-1-1,1>>^ The words of Ne·he·miʹah^&#42;1^ the son of Hac·a·liʹah: Now in the month of Chisʹlev,^&#42;2^ in the 20th year, I was in Shuʹshan^&#42;3^ the citadel.^&#42;4^

[NOTE]
====
. Meaning “Jah Comforts.”
. See App. B15.
. Or “Susa.”
. Or “palace; fortress.”
====

[[v16-1-2]]

^<<v16-1-2,2>>^ At that time Ha·naʹni, one of my brothers, arrived with other men from Judah, and I asked them about the remaining Jews who had escaped the captivity, and also about Jerusalem.

[[v16-1-3]]

^<<v16-1-3,3>>^ They replied: “Those remaining there in the province^&#42;1^ who have survived the captivity are in a terrible situation and in disgrace. The walls of Jerusalem are broken down, and its gates have been burned with fire.”

[NOTE]
====
. Or “jurisdictional district.”
====

[[v16-1-4]]

^<<v16-1-4,4>>^ As soon as I heard these words, I sat down and began to weep and mourn for days, and I kept fasting and praying before the God of the heavens.

[[v16-1-5]]

^<<v16-1-5,5>>^ I said: “O Jehovah, the God of the heavens, the great and awe-inspiring God who keeps his covenant and shows loyal love to those who love him and keep his commandments,

[[v16-1-6]]

^<<v16-1-6,6>>^ please, let your ear be attentive and your eyes open to listen to the prayer of your servant that I am praying to you today, day and night, concerning your servants the Israelites, all the while confessing the sins that the people of Israel have committed against you. We have sinned, both I and the house of my father.

[[v16-1-7]]

^<<v16-1-7,7>>^ We have certainly acted corruptly against you by not keeping the commandments, regulations, and judicial decisions that you gave to your servant Moses.

[[v16-1-8]]

^<<v16-1-8,8>>^ “Remember, please, the word that you commanded^&#42;1^ your servant Moses: ‘If you act unfaithfully, I will scatter you among the peoples.

[NOTE]
====
. Or “the warning you gave to.”
====

[[v16-1-9]]

^<<v16-1-9,9>>^ But if you return to me and observe my commandments and obey them, though your dispersed people should be at the end of the heavens, I will gather them from there and bring them to the place that I have chosen to have my name reside.’

[[v16-1-10]]

^<<v16-1-10,10>>^ They are your servants and your people, whom you redeemed by your great power and by your mighty hand.

[[v16-1-11]]

^<<v16-1-11,11>>^ O Jehovah, please, let your ear be attentive to the prayer of your servant and to the prayer of your servants who take delight in fearing your name, and please, grant success to your servant today, and may this man show me compassion.”
Now I was cupbearer to the king.

'''

xref:015-ezra/015-ezra-010.adoc#v15-10-0[&#60; Capítulo Anterior] | <<v16-1-0,Topo>> | xref:016-nehemiah/016-nehemiah-002.adoc#v16-2-0[Próximo Capítulo &#62;]