include::./index.adoc[]

[[v16-11-0]]
=== Nehemiah, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v16-11-1]]

^<<v16-11-1,1>>^ Now the princes of the people were living in Jerusalem; but the rest of the people cast lots to bring one out of every ten to live in Jerusalem, the holy city, while the other nine stayed in the other cities.

[[v16-11-2]]

^<<v16-11-2,2>>^ Moreover, the people blessed all the men who volunteered to live in Jerusalem.

[[v16-11-3]]

^<<v16-11-3,3>>^ And these are the heads of the province^&#42;1^ who lived in Jerusalem. (The rest of Israel, the priests, the Levites, the temple servants,^&#42;2^ and the sons of the servants of Solʹo·mon, lived in the other cities of Judah, each one in his own possession in his city.

[NOTE]
====
. Or “jurisdictional district.”
. Or “the Nethinim.” Lit., “the given ones.”
====

[[v16-11-4]]

^<<v16-11-4,4>>^ Also, there lived in Jerusalem some of the people of Judah and of Benjamin.) Of the people of Judah were A·thaiʹah son of Uz·ziʹah son of Zech·a·riʹah son of Am·a·riʹah son of Sheph·a·tiʹah son of Ma·halʹa·lel of the sons of Peʹrez,

[[v16-11-5]]

^<<v16-11-5,5>>^ and Ma·a·seiʹah son of Barʹuch son of Col·hoʹzeh son of Ha·zaiʹah son of A·daiʹah son of Joiʹa·rib son of Zech·a·riʹah son of the She·laʹnite.

[[v16-11-6]]

^<<v16-11-6,6>>^ All the sons of Peʹrez who were dwelling in Jerusalem were 468 capable men.

[[v16-11-7]]

^<<v16-11-7,7>>^ And these were the people of Benjamin: Salʹlu son of Me·shulʹlam son of Joʹed son of Pe·daiʹah son of Ko·laiʹah son of Ma·a·seiʹah son of Ithʹi·el son of Je·shaʹiah,

[[v16-11-8]]

^<<v16-11-8,8>>^ and after him Gab·baʹi and Sal·laʹi, 928;

[[v16-11-9]]

^<<v16-11-9,9>>^ and Joel the son of Zichʹri was their overseer, and Judah the son of Has·se·nuʹah was second in charge of the city.

[[v16-11-10]]

^<<v16-11-10,10>>^ Of the priests: Je·daʹiah son of Joiʹa·rib, Jaʹchin,

[[v16-11-11]]

^<<v16-11-11,11>>^ Se·raiʹah son of Hil·kiʹah son of Me·shulʹlam son of Zaʹdok son of Me·raʹioth son of A·hiʹtub, a leader of the house^&#42;1^ of the true God,

[NOTE]
====
. Or “temple.”
====

[[v16-11-12]]

^<<v16-11-12,12>>^ and their brothers who did the work of the house, 822; and A·daiʹah son of Je·roʹham son of Pel·a·liʹah son of Amʹzi son of Zech·a·riʹah son of Pashʹhur son of Mal·chiʹjah,

[[v16-11-13]]

^<<v16-11-13,13>>^ and his brothers, heads of paternal houses, 242; and A·mashʹsai son of Azʹar·el son of Ahʹzai son of Me·shilʹle·moth son of Imʹmer,

[[v16-11-14]]

^<<v16-11-14,14>>^ and their brothers who were mighty, courageous men, 128; and their overseer was Zabʹdi·el, a member of a prominent family.

[[v16-11-15]]

^<<v16-11-15,15>>^ And of the Levites: She·maiʹah son of Hasʹshub son of Az·riʹkam son of Hash·a·biʹah son of Bunʹni,

[[v16-11-16]]

^<<v16-11-16,16>>^ and Shabʹbe·thai and Joʹza·bad, of the heads of the Levites, who were in charge of the outside business of the house of the true God;

[[v16-11-17]]

^<<v16-11-17,17>>^ and Mat·ta·niʹah, son of Miʹcah son of Zabʹdi son of Aʹsaph, the conductor of the singing, who led the praises during prayer, and Bak·bu·kiʹah, the second of his brothers, and Abʹda son of Sham·muʹa son of Gaʹlal son of Je·duʹthun.

[[v16-11-18]]

^<<v16-11-18,18>>^ All the Levites in the holy city were 284.

[[v16-11-19]]

^<<v16-11-19,19>>^ And the gatekeepers were Akʹkub, Talʹmon, and their brothers who kept guard in the gates, 172.

[[v16-11-20]]

^<<v16-11-20,20>>^ The rest of Israel, the priests, and the Levites were in all the other cities of Judah, each in his own inherited property.^&#42;1^

[NOTE]
====
. Or “his own inheritance.”
====

[[v16-11-21]]

^<<v16-11-21,21>>^ The temple servants^&#42;1^ were living in Oʹphel, and Ziʹha and Gishʹpa were in charge of the temple servants.^&#42;2^

[NOTE]
====
. Or “the Nethinim.” Lit., “the given ones.”
. Or “the Nethinim.” Lit., “the given ones.”
====

[[v16-11-22]]

^<<v16-11-22,22>>^ The overseer of the Levites in Jerusalem was Uzʹzi son of Baʹni son of Hash·a·biʹah son of Mat·ta·niʹah son of Miʹca, of the sons of Aʹsaph, the singers; he was in charge of the work of the house of the true God.

[[v16-11-23]]

^<<v16-11-23,23>>^ For there was a royal order in their behalf, and there was a fixed provision for the singers as each day required.

[[v16-11-24]]

^<<v16-11-24,24>>^ And Peth·a·hiʹah son of Me·shezʹa·bel of the sons of Zeʹrah son of Judah was the king’s adviser^&#42;1^ for every matter of the people.

[NOTE]
====
. Lit., “was at the king’s hand.”
====

[[v16-11-25]]

^<<v16-11-25,25>>^ Regarding the settlements with their fields, some of the people of Judah lived in Kirʹi·ath-arʹba and its dependent^&#42;1^ towns, in Diʹbon and its dependent towns, in Je·kabʹze·el and its settlements,

[NOTE]
====
. Or “surrounding.”
====

[[v16-11-26]]

^<<v16-11-26,26>>^ in Jeshʹu·a, in Mo·laʹdah, in Beth-pelʹet,

[[v16-11-27]]

^<<v16-11-27,27>>^ in Haʹzar-shuʹal, in Beʹer-sheʹba and its dependent^&#42;1^ towns,

[NOTE]
====
. Or “surrounding.”
====

[[v16-11-28]]

^<<v16-11-28,28>>^ in Zikʹlag, in Me·coʹnah and its dependent^&#42;1^ towns,

[NOTE]
====
. Or “surrounding.”
====

[[v16-11-29]]

^<<v16-11-29,29>>^ in En-rimʹmon, in Zorʹah, and in Jarʹmuth,

[[v16-11-30]]

^<<v16-11-30,30>>^ in Za·noʹah, in A·dulʹlam and their settlements, in Laʹchish and its fields, and in A·zeʹkah and its dependent^&#42;1^ towns. They settled^&#42;2^ from Beʹer-sheʹba clear to the Valley of Hinʹnom.

[NOTE]
====
. Or “surrounding.”
. Or “camped.”
====

[[v16-11-31]]

^<<v16-11-31,31>>^ And the people of Benjamin were in Geʹba, Michʹmash, Aiʹja, Bethʹel and its dependent^&#42;1^ towns,

[NOTE]
====
. Or “surrounding.”
====

[[v16-11-32]]

^<<v16-11-32,32>>^ Anʹa·thoth, Nob, A·na·niʹah,

[[v16-11-33]]

^<<v16-11-33,33>>^ Haʹzor, Raʹmah, Gitʹta·im,

[[v16-11-34]]

^<<v16-11-34,34>>^ Haʹdid, Ze·boʹim, Ne·balʹlat,

[[v16-11-35]]

^<<v16-11-35,35>>^ Lod, and Oʹno, the valley of the craftsmen.

[[v16-11-36]]

^<<v16-11-36,36>>^ And some divisions of the Levites from Judah were assigned to Benjamin.

'''

xref:016-nehemiah/016-nehemiah-010.adoc#v16-10-0[&#60; Capítulo Anterior] | <<v16-11-0,Topo>> | xref:016-nehemiah/016-nehemiah-012.adoc#v16-12-0[Próximo Capítulo &#62;]