include::./index.adoc[]

[[v60-4-0]]
=== The First of Peter, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v60-4-1]]

^<<v60-4-1,1>>^ Since Christ suffered in the flesh, you too arm yourselves with the same mental disposition;^&#42;1^ because the person who has suffered in the flesh has desisted from sins,

[NOTE]
====
. Or “resolve; determination.”
====

[[v60-4-2]]

^<<v60-4-2,2>>^ so that he may live the remainder of his time in the flesh, no more for the desires of men, but for God’s will.

[[v60-4-3]]

^<<v60-4-3,3>>^ For the time that has passed by is sufficient for you to have done the will of the nations when you carried on in acts of brazen conduct,^&#42;1^ unbridled passions, overdrinking, wild parties,^&#42;2^ drinking bouts, and lawless idolatries.

[NOTE]
====
. Or “acts of shameless conduct.” Plural of the Greek a·selʹgei·a. See Glossary.
. Or “revelries.”
====

[[v60-4-4]]

^<<v60-4-4,4>>^ They are puzzled that you do not continue running with them in the same decadent course of debauchery, so they speak abusively of you.

[[v60-4-5]]

^<<v60-4-5,5>>^ But these people will render an account to the one who is ready to judge those living and those dead.

[[v60-4-6]]

^<<v60-4-6,6>>^ In fact, this is why the good news was declared also to the dead, so that although they are judged in the flesh from the standpoint of men, they might live in harmony with the spirit from God’s standpoint.

[[v60-4-7]]

^<<v60-4-7,7>>^ But the end of all things has drawn close. Therefore, be sound in mind, and be vigilant^&#42;1^ with a view to prayers.

[NOTE]
====
. Or “alert; awake.”
====

[[v60-4-8]]

^<<v60-4-8,8>>^ Above all things, have intense love for one another, because love covers a multitude of sins.

[[v60-4-9]]

^<<v60-4-9,9>>^ Be hospitable to one another without grumbling.

[[v60-4-10]]

^<<v60-4-10,10>>^ To the extent that each one has received a gift, use it in ministering to one another as fine stewards of God’s undeserved kindness that is expressed in various ways.

[[v60-4-11]]

^<<v60-4-11,11>>^ If anyone speaks, let him do so as speaking pronouncements from God; if anyone ministers, let him do so as depending on the strength that God supplies; so that in all things God may be glorified through Jesus Christ. The glory and the might are his forever and ever. Amen.

[[v60-4-12]]

^<<v60-4-12,12>>^ Beloved ones, do not be surprised about the fiery trials that you are experiencing, as though something strange were happening to you.

[[v60-4-13]]

^<<v60-4-13,13>>^ On the contrary, go on rejoicing over the extent to which you are sharers in the sufferings of the Christ, so that you may rejoice and be overjoyed also during the revelation of his glory.

[[v60-4-14]]

^<<v60-4-14,14>>^ If you are being reproached^&#42;1^ for the name of Christ, you are happy, because the spirit of glory, yes, the spirit of God, is resting upon you.

[NOTE]
====
. Or “insulted.”
====

[[v60-4-15]]

^<<v60-4-15,15>>^ However, let none of you suffer as a murderer or a thief or a wrongdoer or a busybody in other people’s matters.

[[v60-4-16]]

^<<v60-4-16,16>>^ But if anyone suffers as a Christian, let him not feel ashamed, but let him keep on glorifying God while bearing this name.

[[v60-4-17]]

^<<v60-4-17,17>>^ For it is the appointed time for the judgment to start with the house of God. Now if it starts first with us, what will the outcome be for those who are not obedient to the good news of God?

[[v60-4-18]]

^<<v60-4-18,18>>^ “And if the righteous man is being saved with difficulty, what will happen to the ungodly man and the sinner?”

[[v60-4-19]]

^<<v60-4-19,19>>^ So, then, let those who are suffering in harmony with the will of God keep on entrusting^&#42;1^ themselves^&#42;2^ to a faithful Creator while they are doing good.

[NOTE]
====
. Or “commending.”
. Or “their souls.”
====

'''

xref:060-1-peter/060-1-peter-003.adoc#v60-3-0[&#60; Capítulo Anterior] | <<v60-4-0,Topo>> | xref:060-1-peter/060-1-peter-005.adoc#v60-5-0[Próximo Capítulo &#62;]