include::./index.adoc[]

[[v60-2-0]]
=== The First of Peter, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v60-2-1]]

^<<v60-2-1,1>>^ So rid yourselves of all badness and deceit and hypocrisy and envy and all backbiting.

[[v60-2-2]]

^<<v60-2-2,2>>^ As newborn infants, form a longing for the unadulterated^&#42;1^ milk of the word, so that by means of it you may grow to salvation,

[NOTE]
====
. Or “pure.”
====

[[v60-2-3]]

^<<v60-2-3,3>>^ provided you have tasted^&#42;1^ that the Lord is kind.

[NOTE]
====
. Or “experienced.”
====

[[v60-2-4]]

^<<v60-2-4,4>>^ As you come to him, a living stone rejected by men but chosen, precious to God,

[[v60-2-5]]

^<<v60-2-5,5>>^ you yourselves as living stones are being built up into a spiritual house to be a holy priesthood, in order to offer up spiritual sacrifices acceptable to God through Jesus Christ.

[[v60-2-6]]

^<<v60-2-6,6>>^ For it says in Scripture: “Look! I am laying in Zion a chosen stone, a precious foundation cornerstone, and no one exercising faith in it will ever be disappointed.”^&#42;1^

[NOTE]
====
. Lit., “put to shame.”
====

[[v60-2-7]]

^<<v60-2-7,7>>^ It is to you, therefore, that he is precious, because you are believers; but to those not believing, “the stone that the builders rejected, this has become the chief cornerstone”^&#42;1^

[NOTE]
====
. Lit., “the head of the corner.”
====

[[v60-2-8]]

^<<v60-2-8,8>>^ and “a stone of stumbling and a rock of offense.” They are stumbling because they are disobedient to the word. To this very end they were appointed.

[[v60-2-9]]

^<<v60-2-9,9>>^ But you are “a chosen race, a royal priesthood, a holy nation, a people for special possession, that you should declare abroad the excellencies”^&#42;1^ of the One who called you out of darkness into his wonderful light.

[NOTE]
====
. Lit., “the virtues,” that is, his praiseworthy qualities and deeds.
====

[[v60-2-10]]

^<<v60-2-10,10>>^ For you were once not a people, but now you are God’s people; once you had not been shown mercy, but now you have received mercy.

[[v60-2-11]]

^<<v60-2-11,11>>^ Beloved, I urge you as foreigners and temporary residents to keep abstaining from fleshly desires, which wage war against you.^&#42;1^

[NOTE]
====
. Or “the soul.”
====

[[v60-2-12]]

^<<v60-2-12,12>>^ Maintain your conduct fine among the nations, so that when they accuse you of being wrongdoers, they may be eyewitnesses of your fine works and, as a result, glorify God in the day of his inspection.

[[v60-2-13]]

^<<v60-2-13,13>>^ For the Lord’s sake subject yourselves to every human creation,^&#42;1^ whether to a king as being superior

[NOTE]
====
. Or “institution.”
====

[[v60-2-14]]

^<<v60-2-14,14>>^ or to governors as sent by him to punish wrongdoers but to praise those who do good.

[[v60-2-15]]

^<<v60-2-15,15>>^ For it is the will of God that by doing good you may silence^&#42;1^ the ignorant talk of unreasonable men.

[NOTE]
====
. Lit., “muzzle.”
====

[[v60-2-16]]

^<<v60-2-16,16>>^ Be as free people, using your freedom, not as a cover^&#42;1^ for doing wrong, but as slaves of God.

[NOTE]
====
. Or “an excuse.”
====

[[v60-2-17]]

^<<v60-2-17,17>>^ Honor men of all sorts, have love for the whole association of brothers,^&#42;1^ be in fear of God, honor the king.

[NOTE]
====
. Lit., “the brotherhood.”
====

[[v60-2-18]]

^<<v60-2-18,18>>^ Let servants be in subjection to their masters with all due fear, not only to the good and reasonable but also to those hard to please.

[[v60-2-19]]

^<<v60-2-19,19>>^ For it is agreeable when someone endures hardship^&#42;1^ and suffers unjustly because of conscience toward God.

[NOTE]
====
. Or “grief; pain.”
====

[[v60-2-20]]

^<<v60-2-20,20>>^ For what merit is there if you are beaten for sinning and you endure it? But if you endure suffering because of doing good, this is an agreeable thing to God.

[[v60-2-21]]

^<<v60-2-21,21>>^ In fact, to this course you were called, because even Christ suffered for you, leaving a model for you to follow his steps closely.

[[v60-2-22]]

^<<v60-2-22,22>>^ He committed no sin, nor was deception found in his mouth.

[[v60-2-23]]

^<<v60-2-23,23>>^ When he was being insulted,^&#42;1^ he did not insult^&#42;2^ in return. When he was suffering, he did not threaten, but he entrusted himself to the One who judges righteously.

[NOTE]
====
. Or “reviled.”
. Or “revile.”
====

[[v60-2-24]]

^<<v60-2-24,24>>^ He himself bore our sins in his own body on the stake,^&#42;1^ so that we might die to^&#42;2^ sins and live to righteousness. And “by his wounds you were healed.”

[NOTE]
====
. Or “tree.”
. Or “be finished with.”
====

[[v60-2-25]]

^<<v60-2-25,25>>^ For you were like sheep going astray, but now you have returned to the shepherd and overseer of your souls.^&#42;1^

[NOTE]
====
. Or “lives.”
====

'''

xref:060-1-peter/060-1-peter-001.adoc#v60-1-0[&#60; Capítulo Anterior] | <<v60-2-0,Topo>> | xref:060-1-peter/060-1-peter-003.adoc#v60-3-0[Próximo Capítulo &#62;]