include::./index.adoc[]

[[v60-3-0]]
=== The First of Peter, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v60-3-1]]

^<<v60-3-1,1>>^ In the same way, you wives, be in subjection to your husbands, so that if any are not obedient to the word, they may be won without a word through the conduct of their wives,

[[v60-3-2]]

^<<v60-3-2,2>>^ because of having been eyewitnesses of your chaste conduct together with deep respect.

[[v60-3-3]]

^<<v60-3-3,3>>^ Do not let your adornment be external—the braiding of hair and the wearing of gold ornaments or fine clothing—

[[v60-3-4]]

^<<v60-3-4,4>>^ but let it be the secret person of the heart in the incorruptible adornment of the quiet and mild spirit, which is of great value in the eyes of God.

[[v60-3-5]]

^<<v60-3-5,5>>^ For this is how the holy women of the past who hoped in God used to adorn themselves, subjecting themselves to their husbands,

[[v60-3-6]]

^<<v60-3-6,6>>^ just as Sarah obeyed Abraham, calling him lord. And you have become her children, provided you continue doing good and do not give in to fear.

[[v60-3-7]]

^<<v60-3-7,7>>^ You husbands, in the same way, continue dwelling with them according to knowledge.^&#42;1^ Assign them honor as to a weaker vessel, the feminine one, since they are also heirs with you of the undeserved favor of life, in order for your prayers not to be hindered.

[NOTE]
====
. Or “showing them consideration; understanding them.”
====

[[v60-3-8]]

^<<v60-3-8,8>>^ Finally, all of you have unity of mind,^&#42;1^ fellow feeling, brotherly affection, tender compassion, and humility.

[NOTE]
====
. Or “think in agreement.”
====

[[v60-3-9]]

^<<v60-3-9,9>>^ Do not pay back injury for injury or insult for insult. Instead, repay with a blessing, for you were called to this course, so that you might inherit a blessing.

[[v60-3-10]]

^<<v60-3-10,10>>^ For “whoever would love life and see good days must guard his tongue from bad and his lips from speaking deception.

[[v60-3-11]]

^<<v60-3-11,11>>^ Let him turn away from what is bad and do what is good; let him seek peace and pursue it.

[[v60-3-12]]

^<<v60-3-12,12>>^ For the eyes of Jehovah^&#42;1^ are on the righteous, and his ears listen to their supplication, but the face of Jehovah^&#42;2^ is against those doing bad things.”

[NOTE]
====
. See App. A5.
. See App. A5.
====

[[v60-3-13]]

^<<v60-3-13,13>>^ Indeed, who will harm you if you become zealous for what is good?

[[v60-3-14]]

^<<v60-3-14,14>>^ But even if you should suffer for the sake of righteousness, you are happy. However, do not fear what they fear,^&#42;1^ nor be disturbed.

[NOTE]
====
. Or possibly, “do not fear their threats.”
====

[[v60-3-15]]

^<<v60-3-15,15>>^ But sanctify the Christ as Lord in your hearts, always ready to make a defense before everyone who demands of you a reason for the hope you have, but doing so with a mild temper and deep respect.

[[v60-3-16]]

^<<v60-3-16,16>>^ Maintain a good conscience, so that in whatever way you are spoken against, those who speak against you may be put to shame because of your good conduct as followers of Christ.

[[v60-3-17]]

^<<v60-3-17,17>>^ For it is better to suffer because you are doing good, if it is God’s will to allow it, than because you are doing evil.

[[v60-3-18]]

^<<v60-3-18,18>>^ For Christ died once for all time for sins, a righteous person for unrighteous ones, in order to lead you to God. He was put to death in the flesh but made alive in the spirit.

[[v60-3-19]]

^<<v60-3-19,19>>^ And in this state he went and preached to the spirits in prison,

[[v60-3-20]]

^<<v60-3-20,20>>^ who had formerly been disobedient when God was patiently waiting^&#42;1^ in Noah’s day, while the ark was being constructed, in which a few people, that is, eight souls,^&#42;2^ were carried safely through the water.

[NOTE]
====
. Lit., “the patience of God was waiting.”
. Or “persons.”
====

[[v60-3-21]]

^<<v60-3-21,21>>^ Baptism, which corresponds to this, is also now saving you (not by the removing of the filth of the flesh, but by the request to God for a good conscience), through the resurrection of Jesus Christ.

[[v60-3-22]]

^<<v60-3-22,22>>^ He is at God’s right hand, for he went to heaven, and angels and authorities and powers were made subject to him.

'''

xref:060-1-peter/060-1-peter-002.adoc#v60-2-0[&#60; Capítulo Anterior] | <<v60-3-0,Topo>> | xref:060-1-peter/060-1-peter-004.adoc#v60-4-0[Próximo Capítulo &#62;]