include::./index.adoc[]

[[v60-1-0]]
=== The First of Peter, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v60-1-1]]

^<<v60-1-1,1>>^ Peter, an apostle of Jesus Christ, to the temporary residents scattered about in Ponʹtus, Ga·laʹti·a, Cap·pa·doʹci·a, Asia, and Bi·thynʹi·a, to those chosen

[[v60-1-2]]

^<<v60-1-2,2>>^ according to the foreknowledge of God the Father, with sanctification by the spirit, for the purpose of being obedient and sprinkled with the blood of Jesus Christ:
May undeserved kindness and peace be increased to you.

[[v60-1-3]]

^<<v60-1-3,3>>^ Praised be the God and Father of our Lord Jesus Christ, for according to his great mercy he gave us a new birth to a living hope through the resurrection of Jesus Christ from the dead,

[[v60-1-4]]

^<<v60-1-4,4>>^ to an incorruptible and undefiled and unfading inheritance. It is reserved in the heavens for you,

[[v60-1-5]]

^<<v60-1-5,5>>^ who are being safeguarded by God’s power through faith for a salvation ready to be revealed in the last period of time.

[[v60-1-6]]

^<<v60-1-6,6>>^ Because of this you are greatly rejoicing, though for a short time, if it must be, you have been distressed by various trials,

[[v60-1-7]]

^<<v60-1-7,7>>^ in order that the tested quality of your faith, of much greater value than gold that perishes despite its being tested^&#42;1^ by fire, may be found a cause for praise and glory and honor at the revelation of Jesus Christ.

[NOTE]
====
. Or “refined.”
====

[[v60-1-8]]

^<<v60-1-8,8>>^ Though you never saw him, you love him. Though you do not see him now, yet you exercise faith in him and are greatly rejoicing with an indescribable and glorious joy,

[[v60-1-9]]

^<<v60-1-9,9>>^ as you attain the goal of your faith, your salvation.^&#42;1^

[NOTE]
====
. Or “the salvation of your souls.”
====

[[v60-1-10]]

^<<v60-1-10,10>>^ Concerning this salvation, the prophets who prophesied about the undeserved kindness meant for you made a diligent inquiry and a careful search.

[[v60-1-11]]

^<<v60-1-11,11>>^ They kept on investigating what particular time or what season the spirit within them was indicating concerning Christ as it testified beforehand about the sufferings meant for Christ and about the glory that would follow.

[[v60-1-12]]

^<<v60-1-12,12>>^ It was revealed to them that they were ministering, not to themselves, but to you, regarding what has now been announced to you by those who declared the good news to you with holy spirit sent from heaven. Into these very things, angels are desiring to peer.

[[v60-1-13]]

^<<v60-1-13,13>>^ So brace up your minds for activity; keep your senses completely; set your hope on the undeserved kindness that will be brought to you at the revelation of Jesus Christ.

[[v60-1-14]]

^<<v60-1-14,14>>^ As obedient children, stop being molded by^&#42;1^ the desires you formerly had in your ignorance,

[NOTE]
====
. Or “fashioned after.”
====

[[v60-1-15]]

^<<v60-1-15,15>>^ but like the Holy One who called you, become holy yourselves in all your conduct,

[[v60-1-16]]

^<<v60-1-16,16>>^ for it is written: “You must be holy, because I am holy.”

[[v60-1-17]]

^<<v60-1-17,17>>^ And if you are calling on the Father who judges impartially according to each one’s work, conduct yourselves with fear during the time of your temporary residence.

[[v60-1-18]]

^<<v60-1-18,18>>^ For you know that it was not with corruptible things, with silver or gold, that you were set free^&#42;1^ from your futile way of life handed down to you by your forefathers.^&#42;2^

[NOTE]
====
. Lit., “you were ransomed; you were redeemed.”
. Or “by tradition.”
====

[[v60-1-19]]

^<<v60-1-19,19>>^ But it was with precious blood, like that of an unblemished and spotless lamb, that of Christ.

[[v60-1-20]]

^<<v60-1-20,20>>^ True, he was foreknown before the founding of the world, but he was made manifest at the end of the times for your sake.

[[v60-1-21]]

^<<v60-1-21,21>>^ Through him you are believers in God, the one who raised him up from the dead and gave him glory, so that your faith and hope might be in God.

[[v60-1-22]]

^<<v60-1-22,22>>^ Now that you have purified yourselves^&#42;1^ by your obedience to the truth with unhypocritical brotherly affection as the result, love one another intensely from the heart.

[NOTE]
====
. Or “your souls.”
====

[[v60-1-23]]

^<<v60-1-23,23>>^ For you have been given a new birth, not by corruptible, but by incorruptible seed,^&#42;1^ through the word of the living and enduring God.

[NOTE]
====
. That is, seed capable of reproducing, or bearing fruit.
====

[[v60-1-24]]

^<<v60-1-24,24>>^ For “all flesh is^&#42;1^ like grass, and all its glory is like a blossom of the field; the grass withers, and the flower falls off,

[NOTE]
====
. Or “all humans are.”
====

[[v60-1-25]]

^<<v60-1-25,25>>^ but the saying^&#42;1^ of Jehovah^&#42;2^ endures forever.” And this “saying”^&#42;3^ is the good news that was declared to you.

[NOTE]
====
. Or “word.”
. See App. A5.
. Or “word.”
====

'''

xref:059-james/059-james-005.adoc#v59-5-0[&#60; Capítulo Anterior] | <<v60-1-0,Topo>> | xref:060-1-peter/060-1-peter-002.adoc#v60-2-0[Próximo Capítulo &#62;]