include::./index.adoc[]

[[v60-5-0]]
=== The First of Peter, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v60-5-1]]

^<<v60-5-1,1>>^ Therefore, as a fellow elder, a witness of the sufferings of the Christ and a sharer of the glory that is to be revealed, I make this appeal^&#42;1^ to the elders among you:

[NOTE]
====
. Or “exhortation.”
====

[[v60-5-2]]

^<<v60-5-2,2>>^ Shepherd the flock of God under your care, serving as overseers,^&#42;1^ not under compulsion, but willingly before God; not for love of dishonest gain, but eagerly;

[NOTE]
====
. Or “carefully watching over it.”
====

[[v60-5-3]]

^<<v60-5-3,3>>^ not lording it over those who are God’s inheritance, but becoming examples to the flock.

[[v60-5-4]]

^<<v60-5-4,4>>^ And when the chief shepherd has been made manifest, you will receive the unfading crown of glory.

[[v60-5-5]]

^<<v60-5-5,5>>^ In the same way, you younger men, be in subjection to the older men.^&#42;1^ But all of you clothe^&#42;2^ yourselves with humility^&#42;3^ toward one another, because God opposes the haughty ones, but he gives undeserved kindness to the humble ones.

[NOTE]
====
. Or “the elders.”
. Or “gird.”
. Or “lowliness of mind.”
====

[[v60-5-6]]

^<<v60-5-6,6>>^ Humble yourselves, therefore, under the mighty hand of God, so that he may exalt you in due time,

[[v60-5-7]]

^<<v60-5-7,7>>^ while you throw all your anxiety^&#42;1^ on him, because he cares for you.

[NOTE]
====
. Or “cares; worries.”
====

[[v60-5-8]]

^<<v60-5-8,8>>^ Keep your senses, be watchful! Your adversary, the Devil, walks about like a roaring lion, seeking to devour someone.^&#42;1^

[NOTE]
====
. Or “looking for someone to devour.”
====

[[v60-5-9]]

^<<v60-5-9,9>>^ But take your stand against him, firm in the faith, knowing that the same kind of sufferings are being experienced by the entire association of your brothers^&#42;1^ in the world.

[NOTE]
====
. Lit., “by your brotherhood.”
====

[[v60-5-10]]

^<<v60-5-10,10>>^ But after you have suffered a little while, the God of all undeserved kindness, who called you to his everlasting glory in union with Christ, will himself finish your training. He will make you firm, he will make you strong, he will firmly ground you.

[[v60-5-11]]

^<<v60-5-11,11>>^ To him be the might forever. Amen.

[[v60-5-12]]

^<<v60-5-12,12>>^ Through Sil·vaʹnus,^&#42;1^ whom I regard as a faithful brother, I have written you in few words in order to encourage you and to give an earnest witness that this is the true undeserved kindness of God. Stand firm in it.

[NOTE]
====
. Also called Silas.
====

[[v60-5-13]]

^<<v60-5-13,13>>^ She who is in Babylon, a chosen one like you, sends you her greetings, and so does Mark, my son.

[[v60-5-14]]

^<<v60-5-14,14>>^ Greet one another with a kiss of love.
May all of you who are in union with Christ have peace.

'''

xref:060-1-peter/060-1-peter-004.adoc#v60-4-0[&#60; Capítulo Anterior] | <<v60-5-0,Topo>> | xref:061-2-peter/061-2-peter-001.adoc#v61-1-0[Próximo Capítulo &#62;]