include::./index.adoc[]

[[v29-3-0]]
=== Joel, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v29-3-1]]

^<<v29-3-1,1>>^ “For look! in those days and in that time,
When I bring back the captives of Judah and Jerusalem,

[[v29-3-2]]

^<<v29-3-2,2>>^ I will also gather together all the nations
And bring them down to the Valley^&#42;1^ of Je·hoshʹa·phat.^&#42;2^
I will enter into judgment with them there
In behalf of my people and my inheritance Israel,
For they scattered them among the nations,
And they divided up my land among themselves.

[NOTE]
====
. Or “Low Plain.”
. Meaning “Jehovah Is Judge.”
====

[[v29-3-3]]

^<<v29-3-3,3>>^ For my people they cast lots;
They would trade a boy to hire a prostitute
And sell a girl for wine to drink.

[[v29-3-4]]

^<<v29-3-4,4>>^ Also, what do you have against me,
O Tyre and Siʹdon and all the regions of Phi·lisʹti·a?
Are you repaying me for something?
If you are repaying me,
I will swiftly, speedily bring your repayment on your heads.

[[v29-3-5]]

^<<v29-3-5,5>>^ Because you have taken my silver and gold,
And you have brought my finest treasures into your temples;

[[v29-3-6]]

^<<v29-3-6,6>>^ And the people of Judah and Jerusalem you have sold to the Greeks,
In order to remove them far from their territory;

[[v29-3-7]]

^<<v29-3-7,7>>^ Here I am rousing them to come from the place where you sold them,
And I will bring your repayment on your heads.

[[v29-3-8]]

^<<v29-3-8,8>>^ I will sell your sons and daughters into the hand of the people of Judah,
And they will sell them to the men of Sheʹba, to a nation far away;
For Jehovah himself has spoken it.

[[v29-3-9]]

^<<v29-3-9,9>>^ Proclaim this among the nations:
‘Prepare for^&#42;1^ war! Stir up the mighty men!
Let all the soldiers draw near, let them advance!

[NOTE]
====
. Lit., “Sanctify.”
====

[[v29-3-10]]

^<<v29-3-10,10>>^ Beat your plowshares into swords and your pruning shears into spears.^&#42;1^
Let the weak one say: “I am powerful.”

[NOTE]
====
. Or “lances.”
====

[[v29-3-11]]

^<<v29-3-11,11>>^ Come and help, all you surrounding nations, assemble together!’”
To that place, O Jehovah, bring down your powerful ones.^&#42;1^

[NOTE]
====
. Or “your warriors.”
====

[[v29-3-12]]

^<<v29-3-12,12>>^ “Let the nations be roused and come up to the Valley^&#42;1^ of Je·hoshʹa·phat;
For there I will sit in order to judge all the surrounding nations.

[NOTE]
====
. Or “Low Plain.”
====

[[v29-3-13]]

^<<v29-3-13,13>>^ Thrust in a sickle, for the harvest is ripe.
Come down and tread, for the winepress is full.
The vats overflow, for their badness is abundant.

[[v29-3-14]]

^<<v29-3-14,14>>^ Crowds, crowds are in the valley^&#42;1^ of the decision,
For the day of Jehovah is near in the valley^&#42;2^ of the decision.

[NOTE]
====
. Or “low plain.”
. Or “low plain.”
====

[[v29-3-15]]

^<<v29-3-15,15>>^ Sun and moon will become dark,
And the stars will lose their brightness.

[[v29-3-16]]

^<<v29-3-16,16>>^ And Jehovah will roar out of Zion,
Out of Jerusalem he will raise his voice.
And heaven and earth will rock;
But Jehovah will be a refuge for his people,
A fortress for the people of Israel.

[[v29-3-17]]

^<<v29-3-17,17>>^ And you will have to know that I am Jehovah your God, residing in Zion, my holy mountain.
Jerusalem will become a holy place,
And strangers^&#42;1^ will pass through her no more.

[NOTE]
====
. Or “foreigners.”
====

[[v29-3-18]]

^<<v29-3-18,18>>^ In that day the mountains will drip with sweet wine,
The hills will flow with milk,
And the streams of Judah will all flow with water.
Out of the house of Jehovah a spring will flow,
And it will irrigate the Valley^&#42;1^ of the Acacia Trees.

[NOTE]
====
. Or “Wadi.”
====

[[v29-3-19]]

^<<v29-3-19,19>>^ But Egypt will become desolate,
And Eʹdom will be a desolate wilderness,
Because of the violence done to the people of Judah,
In whose land they shed innocent blood.

[[v29-3-20]]

^<<v29-3-20,20>>^ But Judah will always be inhabited,
And Jerusalem to generation after generation.

[[v29-3-21]]

^<<v29-3-21,21>>^ I will consider innocent their blood^&#42;1^ that I had not considered innocent;
And Jehovah will reside in Zion.”

[NOTE]
====
. Or “bloodguilt.”
====

'''

xref:029-joel/029-joel-002.adoc#v29-2-0[&#60; Capítulo Anterior] | <<v29-3-0,Topo>> | xref:030-amos/030-amos-001.adoc#v30-1-0[Próximo Capítulo &#62;]