include::./index.adoc[]

[[v37-2-0]]
=== Haggai, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v37-2-1]]

^<<v37-2-1,1>>^ In the seventh month, on the 21st day of the month, the word of Jehovah came through Hagʹgai the prophet, saying,

[[v37-2-2]]

^<<v37-2-2,2>>^ “Please ask Ze·rubʹba·bel son of She·alʹti·el, the governor of Judah, and Joshua son of Je·hozʹa·dak, the high priest, and the rest of the people:

[[v37-2-3]]

^<<v37-2-3,3>>^ ‘Who is left among you who saw this house^&#42;1^ in its former glory? How does it look to you now? Does it not seem like nothing in comparison?’

[NOTE]
====
. Or “temple.”
====

[[v37-2-4]]

^<<v37-2-4,4>>^ “‘But now be strong, Ze·rubʹba·bel,’ declares Jehovah, ‘and be strong, Joshua son of Je·hozʹa·dak, the high priest.’
“‘And be strong, all you people of the land,’ declares Jehovah, ‘and work.’
“‘For I am with you,’ declares Jehovah of armies.

[[v37-2-5]]

^<<v37-2-5,5>>^ ‘Remember what I promised you when you came out of Egypt, and my spirit remains among you.^&#42;1^ Do not be afraid.’”

[NOTE]
====
. Or possibly, “and when my spirit was standing in among you.”
====

[[v37-2-6]]

^<<v37-2-6,6>>^ “For this is what Jehovah of armies says, ‘Yet once more—in a little while—and I will shake the heavens and the earth and the sea and the dry land.’

[[v37-2-7]]

^<<v37-2-7,7>>^ “‘And I will shake all the nations, and the precious^&#42;1^ things of all the nations will come in; and I will fill this house with glory,’ says Jehovah of armies.

[NOTE]
====
. Or “desirable.”
====

[[v37-2-8]]

^<<v37-2-8,8>>^ “‘The silver is mine, and the gold is mine,’ declares Jehovah of armies.

[[v37-2-9]]

^<<v37-2-9,9>>^ “‘The future glory of this house will be greater than the former,’ says Jehovah of armies.
“‘And in this place I will grant peace,’ declares Jehovah of armies.”

[[v37-2-10]]

^<<v37-2-10,10>>^ On the 24th day of the ninth month, in the second year of Da·riʹus, the word of Jehovah came to Hagʹgai the prophet, saying:

[[v37-2-11]]

^<<v37-2-11,11>>^ “This is what Jehovah of armies says, ‘Ask, please, the priests about the law:

[[v37-2-12]]

^<<v37-2-12,12>>^ “If a man carries holy flesh in the fold of his clothing, and his clothing touches bread or stew or wine or oil or any sort of food, will it become holy?”’”
The priests answered: “No!”

[[v37-2-13]]

^<<v37-2-13,13>>^ Hagʹgai then asked: “If someone who is unclean from contact with a dead body^&#42;1^ touches any of these things, will it become unclean?”
The priests answered: “It will become unclean.”

[NOTE]
====
. Or “by a soul.” See Glossary.
====

[[v37-2-14]]

^<<v37-2-14,14>>^ So Hagʹgai said: “‘That is how this people is, and that is how this nation is before me,’ declares Jehovah, ‘and that is how all the work of their hands is; whatever they present there is unclean.’

[[v37-2-15]]

^<<v37-2-15,15>>^ “‘But now, please, set your heart on^&#42;1^ this from this day forward: Before a stone was placed on a stone in the temple of Jehovah,

[NOTE]
====
. Or “give careful thought to.”
====

[[v37-2-16]]

^<<v37-2-16,16>>^ how was it then? When someone came to a heap of grain expecting 20 measures, there were only 10; and when someone came to the vat to draw 50 measures from the wine trough, there were only 20;

[[v37-2-17]]

^<<v37-2-17,17>>^ I struck you—all the works of your hands—with scorching blight and mildew and hail, but not one of you turned to me,’ declares Jehovah.

[[v37-2-18]]

^<<v37-2-18,18>>^ “‘Please, set your heart on^&#42;1^ this from this day forward, from the 24th day of the ninth month, from the day that the foundation of the temple of Jehovah was laid; set your heart on this:

[NOTE]
====
. Or “give careful thought to.”
====

[[v37-2-19]]

^<<v37-2-19,19>>^ Is there seed yet in the storehouse?^&#42;1^ The vine, the fig, the pomegranate, and the olive tree—they have not yet borne fruit, have they? From this day I will send a blessing.’”

[NOTE]
====
. Or “grain pit?”
====

[[v37-2-20]]

^<<v37-2-20,20>>^ The word of Jehovah came a second time to Hagʹgai on the 24th day of the month, saying:

[[v37-2-21]]

^<<v37-2-21,21>>^ “Say to Ze·rubʹba·bel, the governor of Judah, ‘I am going to shake the heavens and the earth.

[[v37-2-22]]

^<<v37-2-22,22>>^ I will overthrow the throne of kingdoms and annihilate the strength of the kingdoms of the nations; and I will overthrow the chariot and its riders, and the horses and their riders will fall, each one by the sword of his brother.’”

[[v37-2-23]]

^<<v37-2-23,23>>^ “‘In that day,’ declares Jehovah of armies, ‘I will take you, my servant Ze·rubʹba·bel son of She·alʹti·el,’ declares Jehovah, ‘and I will make you like a seal ring, because you are the one whom I have chosen,’ declares Jehovah of armies.”

'''

xref:037-haggai/037-haggai-001.adoc#v37-1-0[&#60; Capítulo Anterior] | <<v37-2-0,Topo>> | xref:038-zechariah/038-zechariah-001.adoc#v38-1-0[Próximo Capítulo &#62;]