include::./index.adoc[]

[[v58-7-0]]
=== To the Hebrews, 7
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v58-7-1]]

^<<v58-7-1,1>>^ For this Mel·chizʹe·dek, king of Saʹlem, priest of the Most High God, met Abraham returning from the slaughter of the kings and blessed him,

[[v58-7-2]]

^<<v58-7-2,2>>^ and Abraham gave^&#42;1^ him a tenth of everything. First, his name is translated “King of Righteousness,” and then also king of Saʹlem, that is, “King of Peace.”

[NOTE]
====
. Lit., “apportioned.”
====

[[v58-7-3]]

^<<v58-7-3,3>>^ In being fatherless, motherless, without genealogy, having neither a beginning of days nor an end of life, but being made like the Son of God, he remains a priest for all time.^&#42;1^

[NOTE]
====
. Or “perpetually.”
====

[[v58-7-4]]

^<<v58-7-4,4>>^ See how great this man was to whom Abraham, the family head,^&#42;1^ gave a tenth out of the best spoils.

[NOTE]
====
. Or “the patriarch.”
====

[[v58-7-5]]

^<<v58-7-5,5>>^ True, according to the Law, those of the sons of Leʹvi who receive their priestly office have a commandment to collect tithes from the people, that is, from their brothers, even though these are descendants^&#42;1^ of Abraham.

[NOTE]
====
. Lit., “have come out of the loins.”
====

[[v58-7-6]]

^<<v58-7-6,6>>^ But this man who did not trace his genealogy from them took tithes from Abraham and blessed the one who had the promises.

[[v58-7-7]]

^<<v58-7-7,7>>^ Now it is undeniable that the lesser one is blessed by the greater.

[[v58-7-8]]

^<<v58-7-8,8>>^ And in the one case, it is men who are dying who receive tithes, but in the other case, it is someone of whom witness is given that he lives.

[[v58-7-9]]

^<<v58-7-9,9>>^ And it could be said that even Leʹvi, who receives tithes, has paid tithes through Abraham,

[[v58-7-10]]

^<<v58-7-10,10>>^ for he was still a future descendant^&#42;1^ of his forefather when Mel·chizʹe·dek met him.

[NOTE]
====
. Lit., “in the loins.”
====

[[v58-7-11]]

^<<v58-7-11,11>>^ If, then, perfection was attainable through the Levitical priesthood (for it was a feature of the Law that was given to the people), what further need would there be for another priest to arise who is said to be in the manner of Mel·chizʹe·dek and not in the manner of Aaron?

[[v58-7-12]]

^<<v58-7-12,12>>^ For since the priesthood is being changed, it becomes necessary to change the Law as well.

[[v58-7-13]]

^<<v58-7-13,13>>^ For the man about whom these things are said came from another tribe, from which no one has officiated at the altar.

[[v58-7-14]]

^<<v58-7-14,14>>^ For it is clear that our Lord has descended from Judah, yet Moses said nothing about priests coming from that tribe.

[[v58-7-15]]

^<<v58-7-15,15>>^ And this becomes even clearer when another priest arises who is like Mel·chizʹe·dek,

[[v58-7-16]]

^<<v58-7-16,16>>^ who has become such, not by the legal requirement that depends on fleshly descent, but by the power of an indestructible life.

[[v58-7-17]]

^<<v58-7-17,17>>^ For it is said in witness of him: “You are a priest forever in the manner of Mel·chizʹe·dek.”

[[v58-7-18]]

^<<v58-7-18,18>>^ So, then, the former commandment is set aside because it is weak and ineffective.

[[v58-7-19]]

^<<v58-7-19,19>>^ For the Law made nothing perfect, but the introduction of a better hope did, through which we are drawing near to God.

[[v58-7-20]]

^<<v58-7-20,20>>^ Also, inasmuch as this was not done without an oath being sworn

[[v58-7-21]]

^<<v58-7-21,21>>^ (for, indeed, there are men who have become priests without a sworn oath, but this one has become so through an oath sworn respecting him by the One who said: “Jehovah^&#42;1^ has sworn, and he will not change his mind,^&#42;2^ ‘You are a priest forever’”),

[NOTE]
====
. See App. A5.
. Or “will feel no regret.”
====

[[v58-7-22]]

^<<v58-7-22,22>>^ Jesus has accordingly become the guarantee^&#42;1^ of a better covenant.

[NOTE]
====
. Or “the one given in pledge.”
====

[[v58-7-23]]

^<<v58-7-23,23>>^ Furthermore, many had to become priests in succession because death prevented them from continuing as such,

[[v58-7-24]]

^<<v58-7-24,24>>^ but because he continues alive forever, his priesthood has no successors.

[[v58-7-25]]

^<<v58-7-25,25>>^ So he is able also to save completely those who are approaching God through him, because he is always alive to plead for them.

[[v58-7-26]]

^<<v58-7-26,26>>^ For it is fitting for us to have such a high priest who is loyal, innocent, undefiled, separated from the sinners, and exalted above the heavens.

[[v58-7-27]]

^<<v58-7-27,27>>^ Unlike those high priests, he does not need to offer up sacrifices daily, first for his own sins and then for those of the people, because he did this once for all time when he offered himself up.

[[v58-7-28]]

^<<v58-7-28,28>>^ For the Law appoints as high priests men who have weaknesses, but the word of the oath sworn after the Law appoints a Son, who has been made perfect forever.

'''

xref:058-hebrews/058-hebrews-006.adoc#v58-6-0[&#60; Capítulo Anterior] | <<v58-7-0,Topo>> | xref:058-hebrews/058-hebrews-008.adoc#v58-8-0[Próximo Capítulo &#62;]