include::./index.adoc[]

[[v58-10-0]]
=== To the Hebrews, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v58-10-1]]

^<<v58-10-1,1>>^ For since the Law has a shadow of the good things to come, but not the very substance of the things, it^&#42;1^ can never, by the same sacrifices that are continually offered year after year, make those who approach perfect.

[NOTE]
====
. Or possibly, “men.”
====

[[v58-10-2]]

^<<v58-10-2,2>>^ Otherwise, would not the sacrifices have stopped being offered, because those rendering sacred service once cleansed would have no consciousness of sins anymore?

[[v58-10-3]]

^<<v58-10-3,3>>^ On the contrary, these sacrifices are a reminder of sins year after year,

[[v58-10-4]]

^<<v58-10-4,4>>^ for it is not possible for the blood of bulls and of goats to take sins away.

[[v58-10-5]]

^<<v58-10-5,5>>^ So when he comes into the world, he says: “‘Sacrifice and offering you did not want, but you prepared a body for me.

[[v58-10-6]]

^<<v58-10-6,6>>^ You did not approve of whole burnt offerings and sin offerings.’

[[v58-10-7]]

^<<v58-10-7,7>>^ Then I said: ‘Look! I have come (in the scroll^&#42;1^ it is written about me) to do your will, O God.’”

[NOTE]
====
. Lit., “in the scroll of the book.”
====

[[v58-10-8]]

^<<v58-10-8,8>>^ After first saying: “You did not want nor did you approve of sacrifices and offerings and whole burnt offerings and sin offerings”—sacrifices that are offered according to the Law—

[[v58-10-9]]

^<<v58-10-9,9>>^ then he says: “Look! I have come to do your will.” He does away with what is first in order to establish what is second.

[[v58-10-10]]

^<<v58-10-10,10>>^ By this “will” we have been sanctified through the offering of the body of Jesus Christ once for all time.

[[v58-10-11]]

^<<v58-10-11,11>>^ Also, every priest takes his station day after day to offer holy service^&#42;1^ and to make the same sacrifices often, which can never take sins away completely.

[NOTE]
====
. Or “to perform public service.”
====

[[v58-10-12]]

^<<v58-10-12,12>>^ But this man offered one sacrifice for sins for all time and sat down at the right hand of God,

[[v58-10-13]]

^<<v58-10-13,13>>^ from then on waiting until his enemies should be placed as a stool for his feet.

[[v58-10-14]]

^<<v58-10-14,14>>^ For it is by one sacrificial offering that he has made those who are being sanctified perfect for all time.

[[v58-10-15]]

^<<v58-10-15,15>>^ Moreover, the holy spirit also bears witness to us, for after it has said:

[[v58-10-16]]

^<<v58-10-16,16>>^ “‘This is the covenant that I will make with them after those days,’ says Jehovah.^&#42;1^ ‘I will put my laws in their hearts, and in their minds I will write them.’”

[NOTE]
====
. See App. A5.
====

[[v58-10-17]]

^<<v58-10-17,17>>^ Then it says: “And I will no longer call their sins and their lawless deeds to mind.”

[[v58-10-18]]

^<<v58-10-18,18>>^ Now where there is forgiveness of these, there is no longer an offering for sin.

[[v58-10-19]]

^<<v58-10-19,19>>^ Therefore, brothers, since we have boldness^&#42;1^ for the way of entry into the holy place by the blood of Jesus,

[NOTE]
====
. Or “confidence.”
====

[[v58-10-20]]

^<<v58-10-20,20>>^ which he opened up^&#42;1^ for us as a new and living way through the curtain, that is, his flesh,

[NOTE]
====
. Lit., “inaugurated.”
====

[[v58-10-21]]

^<<v58-10-21,21>>^ and since we have a great priest over the house of God,

[[v58-10-22]]

^<<v58-10-22,22>>^ let us approach with sincere hearts and complete faith, having had our hearts sprinkled clean from a wicked conscience and our bodies bathed with clean water.

[[v58-10-23]]

^<<v58-10-23,23>>^ Let us hold firmly the public declaration of our hope without wavering, for the one who promised is faithful.

[[v58-10-24]]

^<<v58-10-24,24>>^ And let us consider^&#42;1^ one another so as to incite^&#42;2^ to love and fine works,

[NOTE]
====
. Or “be concerned about; pay attention to.”
. Or “motivate; stir up.”
====

[[v58-10-25]]

^<<v58-10-25,25>>^ not forsaking our meeting together, as some have the custom, but encouraging one another, and all the more so as you see the day drawing near.

[[v58-10-26]]

^<<v58-10-26,26>>^ For if we practice sin willfully after having received the accurate knowledge of the truth, there is no longer any sacrifice for sins left,

[[v58-10-27]]

^<<v58-10-27,27>>^ but there is a certain fearful expectation of judgment and a burning indignation that is going to consume those in opposition.

[[v58-10-28]]

^<<v58-10-28,28>>^ Anyone who has disregarded the Law of Moses dies without compassion on the testimony of two or three.

[[v58-10-29]]

^<<v58-10-29,29>>^ How much greater punishment do you think a person will deserve who has trampled on the Son of God and who has regarded as of ordinary value the blood of the covenant by which he was sanctified, and who has outraged the spirit of undeserved kindness with contempt?

[[v58-10-30]]

^<<v58-10-30,30>>^ For we know the One who said: “Vengeance is mine; I will repay.” And again: “Jehovah^&#42;1^ will judge his people.”

[NOTE]
====
. See App. A5.
====

[[v58-10-31]]

^<<v58-10-31,31>>^ It is a fearful thing to fall into the hands of the living God.

[[v58-10-32]]

^<<v58-10-32,32>>^ However, keep remembering the former days in which, after you were enlightened, you endured a great struggle along with sufferings.

[[v58-10-33]]

^<<v58-10-33,33>>^ At times you were publicly exposed^&#42;1^ both to reproaches and to tribulations, and at times you shared^&#42;2^ with those who were having such an experience.

[NOTE]
====
. Lit., “were exposed as in a theater.”
. Or “stood side by side.”
====

[[v58-10-34]]

^<<v58-10-34,34>>^ For you expressed sympathy for those in prison and you accepted joyfully the plundering of your belongings, knowing that you yourselves have a better and an enduring possession.

[[v58-10-35]]

^<<v58-10-35,35>>^ Therefore, do not throw away your boldness,^&#42;1^ which will be richly rewarded.

[NOTE]
====
. Lit., “freeness of speech.”
====

[[v58-10-36]]

^<<v58-10-36,36>>^ For you need endurance, so that after you have done the will of God, you may receive the fulfillment of the promise.

[[v58-10-37]]

^<<v58-10-37,37>>^ For yet “a very little while,” and “the one who is coming will arrive and will not delay.”

[[v58-10-38]]

^<<v58-10-38,38>>^ “But my righteous one will live by reason of faith,” and “if he shrinks back, I have^&#42;1^ no pleasure in him.”

[NOTE]
====
. Or “my soul has.”
====

[[v58-10-39]]

^<<v58-10-39,39>>^ Now we are not the sort who shrink back to destruction, but the sort who have faith for the preserving of our lives.^&#42;1^

[NOTE]
====
. Or “souls.”
====

'''

xref:058-hebrews/058-hebrews-009.adoc#v58-9-0[&#60; Capítulo Anterior] | <<v58-10-0,Topo>> | xref:058-hebrews/058-hebrews-011.adoc#v58-11-0[Próximo Capítulo &#62;]