include::./index.adoc[]

[[v58-8-0]]
=== To the Hebrews, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v58-8-1]]

^<<v58-8-1,1>>^ Now this is the main point of what we are saying: We have such a high priest as this, and he has sat down at the right hand of the throne of the Majesty in the heavens,

[[v58-8-2]]

^<<v58-8-2,2>>^ a minister^&#42;1^ of the holy place and of the true tent, which Jehovah^&#42;2^ set up, and not man.

[NOTE]
====
. Or “public servant.”
. See App. A5.
====

[[v58-8-3]]

^<<v58-8-3,3>>^ For every high priest is appointed to offer both gifts and sacrifices; so it was necessary for this one also to have something to offer.

[[v58-8-4]]

^<<v58-8-4,4>>^ If he were on earth, he would not be a priest, since there are already men who offer the gifts according to the Law.

[[v58-8-5]]

^<<v58-8-5,5>>^ These men are offering sacred service in a typical representation and a shadow of the heavenly things; just as Moses, when about to construct the tent, was given the divine command: For He says: “See that you make all things after their pattern that was shown to you in the mountain.”

[[v58-8-6]]

^<<v58-8-6,6>>^ But now Jesus has obtained a more excellent ministry^&#42;1^ because he is also the mediator of a correspondingly better covenant, which has been legally established on better promises.

[NOTE]
====
. Or “public service.”
====

[[v58-8-7]]

^<<v58-8-7,7>>^ If that first covenant had been faultless, there would have been no need for a second.

[[v58-8-8]]

^<<v58-8-8,8>>^ For he does find fault with the people when he says: “‘Look! The days are coming,’ says Jehovah,^&#42;1^ ‘when I will make with the house of Israel and with the house of Judah a new covenant.

[NOTE]
====
. See App. A5.
====

[[v58-8-9]]

^<<v58-8-9,9>>^ It will not be like the covenant that I made with their forefathers on the day I took hold of their hand to lead them out of the land of Egypt, because they did not remain in my covenant, so I stopped caring for them,’ says Jehovah.^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v58-8-10]]

^<<v58-8-10,10>>^ “‘For this is the covenant that I will make with the house of Israel after those days,’ says Jehovah.^&#42;1^ ‘I will put my laws in their mind, and in their hearts I will write them. And I will become their God, and they will become my people.

[NOTE]
====
. See App. A5.
====

[[v58-8-11]]

^<<v58-8-11,11>>^ “‘And they will no longer teach each one his fellow citizen and each one his brother, saying: “Know Jehovah!”^&#42;1^ For they will all know me, from the least to the greatest of them.

[NOTE]
====
. See App. A5.
====

[[v58-8-12]]

^<<v58-8-12,12>>^ For I will be merciful toward their unrighteous deeds, and I will no longer call their sins to mind.’”

[[v58-8-13]]

^<<v58-8-13,13>>^ In his saying “a new covenant,” he has made the former one obsolete. Now what is obsolete and growing old is near to vanishing away.

'''

xref:058-hebrews/058-hebrews-007.adoc#v58-7-0[&#60; Capítulo Anterior] | <<v58-8-0,Topo>> | xref:058-hebrews/058-hebrews-009.adoc#v58-9-0[Próximo Capítulo &#62;]