include::./index.adoc[]

[[v58-1-0]]
=== To the Hebrews, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v58-1-1]]

^<<v58-1-1,1>>^ Long ago God spoke to our forefathers by means of the prophets on many occasions and in many ways.

[[v58-1-2]]

^<<v58-1-2,2>>^ Now at the end of these days he has spoken to us by means of a Son, whom he appointed heir of all things, and through whom he made the systems of things.^&#42;1^

[NOTE]
====
. Or “the ages.” See Glossary.
====

[[v58-1-3]]

^<<v58-1-3,3>>^ He is the reflection of God’s glory and the exact representation of his very being, and he sustains all things by the word of his power. And after he had made a purification for our sins, he sat down at the right hand of the Majesty on high.

[[v58-1-4]]

^<<v58-1-4,4>>^ So he has become better than the angels to the extent that he has inherited a name more excellent than theirs.

[[v58-1-5]]

^<<v58-1-5,5>>^ For example, to which one of the angels did God ever say: “You are my son; today I have become your father”? And again: “I will become his father, and he will become my son”?

[[v58-1-6]]

^<<v58-1-6,6>>^ But when he again brings his Firstborn into the inhabited earth, he says: “And let all of God’s angels do obeisance to him.”^&#42;1^

[NOTE]
====
. Or “bow down to him.”
====

[[v58-1-7]]

^<<v58-1-7,7>>^ Also, he says about the angels: “He makes his angels spirits, and his ministers^&#42;1^ a flame of fire.”

[NOTE]
====
. Or “public servants.”
====

[[v58-1-8]]

^<<v58-1-8,8>>^ But about the Son, he says: “God is your throne forever and ever, and the scepter of your Kingdom is the scepter of uprightness.^&#42;1^

[NOTE]
====
. Or “justice.”
====

[[v58-1-9]]

^<<v58-1-9,9>>^ You loved righteousness, and you hated lawlessness. That is why God, your God, anointed you with the oil of exultation more than your companions.”

[[v58-1-10]]

^<<v58-1-10,10>>^ And: “At the beginning, O Lord, you laid the foundations of the earth, and the heavens are the works of your hands.

[[v58-1-11]]

^<<v58-1-11,11>>^ They will perish, but you will remain; and just like a garment, they will all wear out,

[[v58-1-12]]

^<<v58-1-12,12>>^ and you will wrap them up just as a cloak, as a garment, and they will be changed. But you are the same, and your years will never come to an end.”

[[v58-1-13]]

^<<v58-1-13,13>>^ But about which of the angels has he ever said: “Sit at my right hand until I place your enemies as a stool for your feet”?

[[v58-1-14]]

^<<v58-1-14,14>>^ Are they not all spirits for holy service,^&#42;1^ sent out to minister for those who are going to inherit salvation?

[NOTE]
====
. Or “for public service.”
====

'''

xref:057-philemon/057-philemon-001.adoc#v57-1-0[&#60; Capítulo Anterior] | <<v58-1-0,Topo>> | xref:058-hebrews/058-hebrews-002.adoc#v58-2-0[Próximo Capítulo &#62;]