include::./index.adoc[]

[[v58-12-0]]
=== To the Hebrews, 12
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v58-12-1]]

^<<v58-12-1,1>>^ So, then, because we have such a great cloud of witnesses surrounding us, let us also throw off every weight and the sin that easily entangles us, and let us run with endurance the race that is set before us,

[[v58-12-2]]

^<<v58-12-2,2>>^ as we look intently at the Chief Agent and Perfecter of our faith, Jesus. For the joy that was set before him he endured a torture stake,^&#42;1^ despising shame, and has sat down at the right hand of the throne of God.

[NOTE]
====
. See Glossary.
====

[[v58-12-3]]

^<<v58-12-3,3>>^ Indeed, consider closely the one who has endured such hostile speech from sinners against their own interests, so that you may not get tired and give up.^&#42;1^

[NOTE]
====
. Or “give out in your souls.”
====

[[v58-12-4]]

^<<v58-12-4,4>>^ In your struggle against that sin, you have never yet resisted to the point of having your blood shed.

[[v58-12-5]]

^<<v58-12-5,5>>^ And you have entirely forgotten the exhortation that addresses you as sons: “My son, do not belittle the discipline from Jehovah,^&#42;1^ nor give up when you are corrected by him;

[NOTE]
====
. See App. A5.
====

[[v58-12-6]]

^<<v58-12-6,6>>^ for those whom Jehovah^&#42;1^ loves he disciplines, in fact, he scourges^&#42;2^ everyone whom he receives as a son.”

[NOTE]
====
. See App. A5.
. Or “punishes.”
====

[[v58-12-7]]

^<<v58-12-7,7>>^ You need to endure as part of your discipline.^&#42;1^ God is treating you as sons. For what son is not disciplined by his father?

[NOTE]
====
. Or “training.”
====

[[v58-12-8]]

^<<v58-12-8,8>>^ But if you have not all shared in receiving this discipline, you are really illegitimate children, and not sons.

[[v58-12-9]]

^<<v58-12-9,9>>^ Furthermore, our human fathers^&#42;1^ used to discipline us, and we gave them respect. Should we not more readily submit ourselves to the Father of our spiritual life and live?

[NOTE]
====
. Lit., “the fathers of our flesh.”
====

[[v58-12-10]]

^<<v58-12-10,10>>^ For they disciplined us for a short time according to what seemed good to them, but he does so for our benefit so that we may partake of his holiness.

[[v58-12-11]]

^<<v58-12-11,11>>^ True, no discipline seems for the present to be joyous, but it is painful;^&#42;1^ yet afterward, it yields the peaceable fruit of righteousness to those who have been trained by it.

[NOTE]
====
. Or “grievous.”
====

[[v58-12-12]]

^<<v58-12-12,12>>^ Therefore, strengthen the hands that hang down and the feeble knees,

[[v58-12-13]]

^<<v58-12-13,13>>^ and keep making straight paths for your feet, so that what is lame may not be put out of joint but, rather, may be healed.

[[v58-12-14]]

^<<v58-12-14,14>>^ Pursue peace with all people and the sanctification^&#42;1^ without which no man will see the Lord.

[NOTE]
====
. Or “holiness.”
====

[[v58-12-15]]

^<<v58-12-15,15>>^ Carefully watch that no one fails to obtain the undeserved kindness of God, so that no poisonous root springs up to cause trouble and many are defiled by it;

[[v58-12-16]]

^<<v58-12-16,16>>^ and watch that among you there is no one who is sexually immoral^&#42;1^ nor anyone who does not appreciate sacred things, like Eʹsau, who gave up his rights as firstborn in exchange for one meal.

[NOTE]
====
. See Glossary, “Sexual immorality.”
====

[[v58-12-17]]

^<<v58-12-17,17>>^ For you know that afterward when he wanted to inherit the blessing, he was rejected; for although he earnestly tried to bring about a change of mind^&#42;1^ with tears, it was to no avail.^&#42;2^

[NOTE]
====
. That is, of his father’s mind.
. Lit., “he found no place for it.”
====

[[v58-12-18]]

^<<v58-12-18,18>>^ For you have not approached something that can be felt and that has been set aflame with fire, and a dark cloud and thick darkness and a storm,

[[v58-12-19]]

^<<v58-12-19,19>>^ and the blast of a trumpet and the voice speaking words, which on hearing, the people begged that nothing further should be spoken to them.

[[v58-12-20]]

^<<v58-12-20,20>>^ For they could not bear the command: “If even a beast touches the mountain, it must be stoned.”

[[v58-12-21]]

^<<v58-12-21,21>>^ Also, the display was so terrifying that Moses said: “I am afraid and trembling.”

[[v58-12-22]]

^<<v58-12-22,22>>^ But you have approached a Mount Zion and a city of the living God, heavenly Jerusalem, and myriads^&#42;1^ of angels

[NOTE]
====
. Or “tens of thousands.”
====

[[v58-12-23]]

^<<v58-12-23,23>>^ in general assembly, and the congregation of the firstborn who have been enrolled in the heavens, and God the Judge of all, and the spiritual lives of righteous ones who have been made perfect,

[[v58-12-24]]

^<<v58-12-24,24>>^ and Jesus the mediator of a new covenant, and the sprinkled blood, which speaks in a better way than Abel’s blood.

[[v58-12-25]]

^<<v58-12-25,25>>^ See that you do not refuse to listen to^&#42;1^ the one who is speaking. For if those who refused to listen to the one giving divine warning on earth did not escape, how much more will we not escape if we turn away from him who speaks from the heavens!

[NOTE]
====
. Or “do not make excuses to; do not ignore.”
====

[[v58-12-26]]

^<<v58-12-26,26>>^ At that time his voice shook the earth, but now he has promised: “Yet once more I will shake not only the earth but also the heaven.”

[[v58-12-27]]

^<<v58-12-27,27>>^ Now the expression “yet once more” indicates the removal of the things that are shaken, things that have been made, in order that the things not shaken may remain.

[[v58-12-28]]

^<<v58-12-28,28>>^ Therefore, seeing that we are to receive a Kingdom that cannot be shaken, let us continue to receive undeserved kindness, through which we may acceptably offer God sacred service with godly fear and awe.

[[v58-12-29]]

^<<v58-12-29,29>>^ For our God is a consuming fire.

'''

xref:058-hebrews/058-hebrews-011.adoc#v58-11-0[&#60; Capítulo Anterior] | <<v58-12-0,Topo>> | xref:058-hebrews/058-hebrews-013.adoc#v58-13-0[Próximo Capítulo &#62;]