include::./index.adoc[]

[[v58-2-0]]
=== To the Hebrews, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v58-2-1]]

^<<v58-2-1,1>>^ That is why it is necessary for us to pay more than the usual attention to the things we have heard, so that we never drift away.

[[v58-2-2]]

^<<v58-2-2,2>>^ For if the word spoken through angels proved to be sure, and every transgression and disobedient act received a punishment in harmony with justice,

[[v58-2-3]]

^<<v58-2-3,3>>^ how will we escape if we have neglected so great a salvation? For it began to be spoken through our Lord and was verified for us by those who heard him,

[[v58-2-4]]

^<<v58-2-4,4>>^ while God joined in bearing witness with signs and wonders^&#42;1^ and various powerful works and with the holy spirit distributed according to his will.

[NOTE]
====
. Or “portents.”
====

[[v58-2-5]]

^<<v58-2-5,5>>^ For it is not to angels that he has subjected the inhabited earth to come, about which we are speaking.

[[v58-2-6]]

^<<v58-2-6,6>>^ But in one place a certain witness said: “What is man that you keep him in mind, or a son of man that you take care of him?

[[v58-2-7]]

^<<v58-2-7,7>>^ You made him a little lower than angels; you crowned him with glory and honor, and appointed him over the works of your hands.

[[v58-2-8]]

^<<v58-2-8,8>>^ All things you subjected under his feet.” By subjecting all things to him, God left nothing that is not subject to him. Now, though, we do not yet see all things in subjection to him.

[[v58-2-9]]

^<<v58-2-9,9>>^ But we do see Jesus, who was made a little lower than angels, now crowned with glory and honor for having suffered death, so that by God’s undeserved kindness he might taste death for everyone.

[[v58-2-10]]

^<<v58-2-10,10>>^ For it was fitting that the one for whom and through whom all things exist, in bringing many sons to glory, should make the Chief Agent of their salvation perfect through sufferings.

[[v58-2-11]]

^<<v58-2-11,11>>^ For both the one who is sanctifying and those who are being sanctified all stem from one, and for this reason he is not ashamed to call them brothers,

[[v58-2-12]]

^<<v58-2-12,12>>^ as he says: “I will declare your name to my brothers; in the midst of the congregation I will praise you with song.”

[[v58-2-13]]

^<<v58-2-13,13>>^ And again: “I will put my trust in him.” And again: “Look! I and the young children, whom Jehovah^&#42;1^ gave me.”

[NOTE]
====
. See App. A5.
====

[[v58-2-14]]

^<<v58-2-14,14>>^ Therefore, since the “young children” are sharers of blood and flesh, he also similarly shared in the same things, so that through his death he might bring to nothing the one having the means to cause death, that is, the Devil,

[[v58-2-15]]

^<<v58-2-15,15>>^ and that he might set free^&#42;1^ all those who were held in slavery all their lives by their fear of death.

[NOTE]
====
. Or “emancipate.”
====

[[v58-2-16]]

^<<v58-2-16,16>>^ For it is not really angels he is assisting, but he is assisting Abraham’s offspring.^&#42;1^

[NOTE]
====
. Lit., “seed.”
====

[[v58-2-17]]

^<<v58-2-17,17>>^ Consequently, he had to become like his “brothers” in all respects, so that he could become a merciful and faithful high priest in things relating to God, in order to offer a propitiatory sacrifice^&#42;1^ for the sins of the people.

[NOTE]
====
. Or “to offer an atoning sacrifice; to make atonement.”
====

[[v58-2-18]]

^<<v58-2-18,18>>^ Since he himself has suffered when being put to the test, he is able to come to the aid of those who are being put to the test.

'''

xref:058-hebrews/058-hebrews-001.adoc#v58-1-0[&#60; Capítulo Anterior] | <<v58-2-0,Topo>> | xref:058-hebrews/058-hebrews-003.adoc#v58-3-0[Próximo Capítulo &#62;]