include::./index.adoc[]

[[v58-6-0]]
=== To the Hebrews, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v58-6-1]]

^<<v58-6-1,1>>^ Therefore, now that we have moved beyond the primary doctrine about the Christ, let us press on to maturity, not laying a foundation again, namely, repentance from dead works and faith in God,

[[v58-6-2]]

^<<v58-6-2,2>>^ the teaching on baptisms and the laying on of the hands, the resurrection of the dead and everlasting judgment.

[[v58-6-3]]

^<<v58-6-3,3>>^ And this we will do, if God indeed permits.

[[v58-6-4]]

^<<v58-6-4,4>>^ For as regards those who were once enlightened and who have tasted the heavenly free gift and who have become partakers of holy spirit

[[v58-6-5]]

^<<v58-6-5,5>>^ and who have tasted the fine word of God and powers of the coming system of things,^&#42;1^

[NOTE]
====
. Or “the coming age.” See Glossary.
====

[[v58-6-6]]

^<<v58-6-6,6>>^ but have fallen away, it is impossible to revive them again to repentance, because they nail the Son of God to the stake again for themselves and expose him to public shame.

[[v58-6-7]]

^<<v58-6-7,7>>^ For the ground receives a blessing from God when it drinks in the rain that frequently falls on it and then produces vegetation useful to those for whom it is cultivated.

[[v58-6-8]]

^<<v58-6-8,8>>^ But if it produces thorns and thistles, it is rejected and is near to being cursed, and in the end it will be burned.

[[v58-6-9]]

^<<v58-6-9,9>>^ But in your case, beloved ones, we are convinced of better things, things related to salvation, even though we are speaking in this way.

[[v58-6-10]]

^<<v58-6-10,10>>^ For God is not unrighteous so as to forget your work and the love you showed for his name by ministering and continuing to minister to the holy ones.

[[v58-6-11]]

^<<v58-6-11,11>>^ But we desire each one of you to show the same industriousness so as to have the full assurance of the hope down to the end,

[[v58-6-12]]

^<<v58-6-12,12>>^ so that you may not become sluggish, but be imitators of those who through faith and patience inherit the promises.

[[v58-6-13]]

^<<v58-6-13,13>>^ For when God made his promise to Abraham, since he could not swear by anyone greater, he swore by himself,

[[v58-6-14]]

^<<v58-6-14,14>>^ saying: “I will surely bless you and I will surely multiply you.”

[[v58-6-15]]

^<<v58-6-15,15>>^ So after Abraham had shown patience, he obtained this promise.

[[v58-6-16]]

^<<v58-6-16,16>>^ For men swear by someone greater, and their oath is the end of every dispute, since it is a legal guarantee to them.

[[v58-6-17]]

^<<v58-6-17,17>>^ In this same way, when God decided to demonstrate more clearly to the heirs of the promise the unchangeableness of his purpose,^&#42;1^ he guaranteed it^&#42;2^ with an oath,

[NOTE]
====
. Or “counsel.”
. Or “stepped in.” Lit., “mediated.”
====

[[v58-6-18]]

^<<v58-6-18,18>>^ in order that through two unchangeable things in which it is impossible for God to lie, we who have fled to the refuge may have strong encouragement to take firm hold of the hope set before us.

[[v58-6-19]]

^<<v58-6-19,19>>^ We have this hope as an anchor for the soul,^&#42;1^ both sure and firm, and it enters in within the curtain,

[NOTE]
====
. Or “for our lives.”
====

[[v58-6-20]]

^<<v58-6-20,20>>^ where a forerunner has entered in our behalf, Jesus, who has become a high priest in the manner of Mel·chizʹe·dek forever.

'''

xref:058-hebrews/058-hebrews-005.adoc#v58-5-0[&#60; Capítulo Anterior] | <<v58-6-0,Topo>> | xref:058-hebrews/058-hebrews-007.adoc#v58-7-0[Próximo Capítulo &#62;]