include::./index.adoc[]

[[v58-11-0]]
=== To the Hebrews, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v58-11-1]]

^<<v58-11-1,1>>^ Faith is the assured expectation of what is hoped for, the evident demonstration^&#42;1^ of realities that are not seen.

[NOTE]
====
. Or “convincing evidence.”
====

[[v58-11-2]]

^<<v58-11-2,2>>^ For by means of it, the men of ancient times^&#42;1^ had witness borne to them.

[NOTE]
====
. Or “our ancestors.”
====

[[v58-11-3]]

^<<v58-11-3,3>>^ By faith we perceive that the systems of things^&#42;1^ were put in order by God’s word, so that what is seen has come into existence from things that are not visible.

[NOTE]
====
. Or “the ages.” See Glossary.
====

[[v58-11-4]]

^<<v58-11-4,4>>^ By faith Abel offered God a sacrifice of greater worth than that of Cain, and through that faith he received the witness that he was righteous, for God approved^&#42;1^ his gifts, and although he died, he still speaks through his faith.

[NOTE]
====
. Or “bore witness by acknowledging.”
====

[[v58-11-5]]

^<<v58-11-5,5>>^ By faith Eʹnoch was transferred so as not to see death, and he was nowhere to be found because God had transferred him; for before he was transferred he received the witness that he had pleased God well.

[[v58-11-6]]

^<<v58-11-6,6>>^ Moreover, without faith it is impossible to please God well, for whoever approaches God must believe that he is^&#42;1^ and that he becomes the rewarder of those earnestly seeking him.

[NOTE]
====
. Or “exists.”
====

[[v58-11-7]]

^<<v58-11-7,7>>^ By faith Noah, after receiving divine warning of things not yet seen, showed godly fear and constructed an ark for the saving of his household; and through this faith he condemned the world, and he became an heir of the righteousness that results from faith.

[[v58-11-8]]

^<<v58-11-8,8>>^ By faith Abraham, when he was called, obeyed by going out to a place he was to receive as an inheritance; he went out, although not knowing where he was going.

[[v58-11-9]]

^<<v58-11-9,9>>^ By faith he lived as a foreigner in the land of the promise as in a foreign land, living in tents with Isaac and Jacob, the heirs with him of the very same promise.

[[v58-11-10]]

^<<v58-11-10,10>>^ For he was awaiting the city having real foundations, whose designer^&#42;1^ and builder is God.

[NOTE]
====
. Or “architect.”
====

[[v58-11-11]]

^<<v58-11-11,11>>^ By faith also Sarah received power to conceive offspring,^&#42;1^ even when she was past the age, since she considered Him faithful^&#42;2^ who made the promise.

[NOTE]
====
. Lit., “seed.”
. Or “trustworthy.”
====

[[v58-11-12]]

^<<v58-11-12,12>>^ For this reason, from one man who was as good as dead, there were born children, as many as the stars of heaven in number and as innumerable as the sands by the seaside.

[[v58-11-13]]

^<<v58-11-13,13>>^ In faith all of these died, although they did not receive the fulfillment of the promises; but they saw them from a distance and welcomed them and publicly declared that they were strangers and temporary residents in the land.

[[v58-11-14]]

^<<v58-11-14,14>>^ For those who speak in such a way make it evident that they are earnestly seeking a place of their own.

[[v58-11-15]]

^<<v58-11-15,15>>^ And yet, if they had kept remembering the place from which they had departed, they would have had opportunity to return.

[[v58-11-16]]

^<<v58-11-16,16>>^ But now they are reaching out for a better place, that is, one belonging to heaven. Therefore, God is not ashamed of them, to be called on as their God, for he has prepared a city for them.

[[v58-11-17]]

^<<v58-11-17,17>>^ By faith Abraham, when he was tested, as good as offered up Isaac—the man who had gladly received the promises attempted to offer up his only-begotten son—

[[v58-11-18]]

^<<v58-11-18,18>>^ although it had been said to him: “What will be called your offspring^&#42;1^ will be through Isaac.”

[NOTE]
====
. Lit., “seed.”
====

[[v58-11-19]]

^<<v58-11-19,19>>^ But he reasoned that God was able to raise him up even from the dead, and he did receive him from there in an illustrative way.

[[v58-11-20]]

^<<v58-11-20,20>>^ By faith also Isaac blessed Jacob and Eʹsau concerning things to come.

[[v58-11-21]]

^<<v58-11-21,21>>^ By faith Jacob, when about to die, blessed each of the sons of Joseph and worshipped while leaning on the top of his staff.

[[v58-11-22]]

^<<v58-11-22,22>>^ By faith Joseph, nearing his end, spoke of the exodus of the sons of Israel, and he gave instructions^&#42;1^ concerning his bones.^&#42;2^

[NOTE]
====
. Or “a command.”
. Or “burial.”
====

[[v58-11-23]]

^<<v58-11-23,23>>^ By faith Moses was hid by his parents for three months after his birth, because they saw that the young child was beautiful and they did not fear the order of the king.

[[v58-11-24]]

^<<v58-11-24,24>>^ By faith Moses, when grown up, refused to be called the son of Pharʹaoh’s daughter,

[[v58-11-25]]

^<<v58-11-25,25>>^ choosing to be mistreated with the people of God rather than to have the temporary enjoyment of sin,

[[v58-11-26]]

^<<v58-11-26,26>>^ because he considered the reproach of the Christ to be riches greater than the treasures of Egypt, for he looked intently toward the payment of the reward.

[[v58-11-27]]

^<<v58-11-27,27>>^ By faith he left Egypt, but not fearing the anger of the king, for he continued steadfast as seeing the One who is invisible.

[[v58-11-28]]

^<<v58-11-28,28>>^ By faith he observed the Passover and the splashing of the blood, so that the destroyer might not harm^&#42;1^ their firstborn.

[NOTE]
====
. Lit., “touch.”
====

[[v58-11-29]]

^<<v58-11-29,29>>^ By faith they passed through the Red Sea as on dry land, but when the Egyptians attempted it, they were swallowed up.

[[v58-11-30]]

^<<v58-11-30,30>>^ By faith the walls of Jerʹi·cho fell down after the people had marched around them for seven days.

[[v58-11-31]]

^<<v58-11-31,31>>^ By faith Raʹhab the prostitute did not perish with those who acted disobediently, because she received the spies in a peaceable way.

[[v58-11-32]]

^<<v58-11-32,32>>^ And what more will I say? For time will fail me if I go on to relate about Gidʹe·on, Baʹrak, Samson, Jephʹthah, David, as well as Samuel and the other prophets.

[[v58-11-33]]

^<<v58-11-33,33>>^ Through faith they defeated kingdoms, brought about righteousness, obtained promises, stopped the mouths of lions,

[[v58-11-34]]

^<<v58-11-34,34>>^ quenched the force of fire, escaped the edge of the sword, from a weak state were made powerful, became mighty in war, routed invading armies.

[[v58-11-35]]

^<<v58-11-35,35>>^ Women received their dead by resurrection, but other men were tortured because they would not accept release by some ransom, in order that they might attain a better resurrection.

[[v58-11-36]]

^<<v58-11-36,36>>^ Yes, others received their trial by mockings and scourgings, indeed, more than that, by chains and prisons.

[[v58-11-37]]

^<<v58-11-37,37>>^ They were stoned, they were tried, they were sawn in two,^&#42;1^ they were slaughtered by the sword, they went about in sheepskins, in goatskins, while they were in need, in tribulation, mistreated;

[NOTE]
====
. Or “sawn apart.”
====

[[v58-11-38]]

^<<v58-11-38,38>>^ and the world was not worthy of them. They wandered about in deserts and mountains and caves and dens of the earth.

[[v58-11-39]]

^<<v58-11-39,39>>^ And yet all of these, although they received a favorable witness because of their faith, did not obtain the fulfillment of the promise,

[[v58-11-40]]

^<<v58-11-40,40>>^ because God had foreseen something better for us, so that they might not be made perfect apart from us.

'''

xref:058-hebrews/058-hebrews-010.adoc#v58-10-0[&#60; Capítulo Anterior] | <<v58-11-0,Topo>> | xref:058-hebrews/058-hebrews-012.adoc#v58-12-0[Próximo Capítulo &#62;]