include::./index.adoc[]

[[v58-3-0]]
=== To the Hebrews, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v58-3-1]]

^<<v58-3-1,1>>^ Consequently, holy brothers, partakers of the heavenly calling,^&#42;1^ consider the apostle and high priest whom we acknowledge^&#42;2^—Jesus.

[NOTE]
====
. Or “invitation.”
. Or “confess.”
====

[[v58-3-2]]

^<<v58-3-2,2>>^ He was faithful to the One who appointed him, just as Moses also was in all the house of that One.

[[v58-3-3]]

^<<v58-3-3,3>>^ For he^&#42;1^ is counted worthy of more glory than Moses, since the one who constructs a house has more honor than the house itself.

[NOTE]
====
. That is, Jesus.
====

[[v58-3-4]]

^<<v58-3-4,4>>^ Of course, every house is constructed by someone, but the one who constructed all things is God.

[[v58-3-5]]

^<<v58-3-5,5>>^ Now Moses was faithful as an attendant in all the house of that One as a testimony^&#42;1^ of the things that were to be spoken afterward,

[NOTE]
====
. Or “witness.”
====

[[v58-3-6]]

^<<v58-3-6,6>>^ but Christ was faithful as a son over God’s house. We are His house if, indeed, we hold on firmly to our freeness of speech and the hope of which we boast down to the end.

[[v58-3-7]]

^<<v58-3-7,7>>^ Therefore, just as the holy spirit says, “Today if you listen to his voice,

[[v58-3-8]]

^<<v58-3-8,8>>^ do not harden your hearts as on the occasion of provoking to bitter anger, as in the day of testing in the wilderness,

[[v58-3-9]]

^<<v58-3-9,9>>^ where your forefathers put me to the test and tried me, despite seeing my works for 40 years.

[[v58-3-10]]

^<<v58-3-10,10>>^ This is why I became disgusted with this generation and said: ‘They always go astray in their hearts, and they have not come to know my ways.’

[[v58-3-11]]

^<<v58-3-11,11>>^ So I swore in my anger: ‘They will not enter into my rest.’”

[[v58-3-12]]

^<<v58-3-12,12>>^ Beware, brothers, for fear there should ever develop in any one of you a wicked heart lacking faith by drawing away from the living God;

[[v58-3-13]]

^<<v58-3-13,13>>^ but keep on encouraging one another each day, as long as it is called “Today,” so that none of you should become hardened by the deceptive power of sin.

[[v58-3-14]]

^<<v58-3-14,14>>^ For we actually become partakers of^&#42;1^ the Christ only if we hold firmly down to the end the confidence we had at the beginning.

[NOTE]
====
. Or “have a sharing with.”
====

[[v58-3-15]]

^<<v58-3-15,15>>^ As it is said, “Today if you listen to his voice, do not harden your hearts as on the occasion of provoking to bitter anger.”

[[v58-3-16]]

^<<v58-3-16,16>>^ For who heard and yet provoked him to bitter anger? Was it not, in fact, all those who went out of Egypt under Moses?

[[v58-3-17]]

^<<v58-3-17,17>>^ Moreover, with whom did God become disgusted for 40 years? Was it not with those who sinned, whose dead bodies fell in the wilderness?

[[v58-3-18]]

^<<v58-3-18,18>>^ And to whom did he swear that they would not enter into his rest? Was it not to those who acted disobediently?

[[v58-3-19]]

^<<v58-3-19,19>>^ So we see that they could not enter in because of lack of faith.

'''

xref:058-hebrews/058-hebrews-002.adoc#v58-2-0[&#60; Capítulo Anterior] | <<v58-3-0,Topo>> | xref:058-hebrews/058-hebrews-004.adoc#v58-4-0[Próximo Capítulo &#62;]