include::./index.adoc[]

[[v58-4-0]]
=== To the Hebrews, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v58-4-1]]

^<<v58-4-1,1>>^ Therefore, since a promise of entering into his rest remains, let us be on guard^&#42;1^ for fear someone among you seems to fall short of it.

[NOTE]
====
. Lit., “be in fear.”
====

[[v58-4-2]]

^<<v58-4-2,2>>^ For we have also had the good news declared to us, just as they had; but the word that they heard did not benefit them, because they were not united by faith with those who listened.

[[v58-4-3]]

^<<v58-4-3,3>>^ For we who have exercised faith do enter into the rest, just as he has said: “So I swore in my anger, ‘They will not enter into my rest,’” although his works were finished from the founding of the world.

[[v58-4-4]]

^<<v58-4-4,4>>^ For in one place he has said of the seventh day as follows: “And God rested on the seventh day from all his works,”

[[v58-4-5]]

^<<v58-4-5,5>>^ and here again he says: “They will not enter into my rest.”

[[v58-4-6]]

^<<v58-4-6,6>>^ Therefore, since it remains for some to enter into it, and those to whom the good news was first declared did not enter in because of disobedience,

[[v58-4-7]]

^<<v58-4-7,7>>^ he again marks off a certain day by saying long afterward in David’s psalm, “Today”; just as it has been said above, “Today if you listen to his voice, do not harden your hearts.”

[[v58-4-8]]

^<<v58-4-8,8>>^ For if Joshua had led them into a place of rest, God would not afterward have spoken of another day.

[[v58-4-9]]

^<<v58-4-9,9>>^ So there remains a sabbath-rest for the people of God.

[[v58-4-10]]

^<<v58-4-10,10>>^ For the man who has entered into God’s rest has also rested from his own works, just as God did from his own.

[[v58-4-11]]

^<<v58-4-11,11>>^ Let us therefore do our utmost to enter into that rest, so that no one may fall into the same pattern of disobedience.

[[v58-4-12]]

^<<v58-4-12,12>>^ For the word of God is alive and exerts power and is sharper than any two-edged sword and pierces even to the dividing of soul^&#42;1^ and spirit,^&#42;2^ and of joints from the marrow, and is able to discern thoughts and intentions of the heart.

[NOTE]
====
. See Glossary.
. See Glossary.
====

[[v58-4-13]]

^<<v58-4-13,13>>^ And there is not a creation that is hidden from his sight, but all things are naked and openly exposed to the eyes of the one to whom we must give an account.

[[v58-4-14]]

^<<v58-4-14,14>>^ Therefore, since we have a great high priest who has passed through the heavens, Jesus the Son of God, let us hold on to our public declaration of him.

[[v58-4-15]]

^<<v58-4-15,15>>^ For we do not have a high priest who cannot sympathize with our weaknesses, but we have one who has been tested in all respects as we have, but without sin.

[[v58-4-16]]

^<<v58-4-16,16>>^ Let us, then, approach the throne of undeserved kindness with freeness of speech, so that we may receive mercy and find undeserved kindness to help us at the right time.

'''

xref:058-hebrews/058-hebrews-003.adoc#v58-3-0[&#60; Capítulo Anterior] | <<v58-4-0,Topo>> | xref:058-hebrews/058-hebrews-005.adoc#v58-5-0[Próximo Capítulo &#62;]