include::./index.adoc[]

[[v42-19-0]]
=== According to Luke, 19
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-19-1]]

^<<v42-19-1,1>>^ He then entered Jerʹi·cho and was passing through.

[[v42-19-2]]

^<<v42-19-2,2>>^ Now a man named Zac·chaeʹus was there; he was a chief tax collector, and he was rich.

[[v42-19-3]]

^<<v42-19-3,3>>^ Well, he was trying to see who this Jesus was, but he could not see because of the crowd, since he was short.

[[v42-19-4]]

^<<v42-19-4,4>>^ So he ran ahead and climbed a sycamore^&#42;1^ tree in order to see him, for he was about to pass that way.

[NOTE]
====
. Or “fig-mulberry.”
====

[[v42-19-5]]

^<<v42-19-5,5>>^ Now when Jesus got to the place, he looked up and said to him: “Zac·chaeʹus, hurry and get down, for today I must stay in your house.”

[[v42-19-6]]

^<<v42-19-6,6>>^ With that he hurried down and joyfully welcomed him as a guest.

[[v42-19-7]]

^<<v42-19-7,7>>^ When they saw this, they were all muttering: “He went as a guest to the house of a man who is a sinner.”

[[v42-19-8]]

^<<v42-19-8,8>>^ But Zac·chaeʹus stood up and said to the Lord: “Look! The half of my belongings, Lord, I am giving to the poor, and whatever I extorted^&#42;1^ from anyone, I am restoring four times over.”

[NOTE]
====
. Or “extorted by false accusation.”
====

[[v42-19-9]]

^<<v42-19-9,9>>^ At this Jesus said to him: “Today salvation has come to this house, because he too is a son of Abraham.

[[v42-19-10]]

^<<v42-19-10,10>>^ For the Son of man came to seek and to save what was lost.”

[[v42-19-11]]

^<<v42-19-11,11>>^ While they were listening to these things, he told another illustration, because he was near Jerusalem and they thought that the Kingdom of God was going to appear instantly.

[[v42-19-12]]

^<<v42-19-12,12>>^ So he said: “A man of noble birth traveled to a distant land to secure kingly power for himself and to return.

[[v42-19-13]]

^<<v42-19-13,13>>^ Calling ten of his slaves, he gave them ten miʹnas^&#42;1^ and told them, ‘Do business with these until I come.’

[NOTE]
====
. A Greek mina weighed 340 g (10.9 oz t) and was reckoned to be worth 100 drachmas. See App. B14.
====

[[v42-19-14]]

^<<v42-19-14,14>>^ But his citizens hated him and sent out a body of ambassadors after him to say, ‘We do not want this man to become king over us.’

[[v42-19-15]]

^<<v42-19-15,15>>^ “When he eventually got back after having secured the kingly power,^&#42;1^ he summoned the slaves to whom he had given the money,^&#42;2^ in order to ascertain what they had gained by their business activity.

[NOTE]
====
. Or “the kingdom.”
. Lit., “silver.”
====

[[v42-19-16]]

^<<v42-19-16,16>>^ So the first one came forward and said, ‘Lord, your miʹna gained ten miʹnas.’

[[v42-19-17]]

^<<v42-19-17,17>>^ He said to him, ‘Well done, good slave! Because in a very small matter you have proved yourself faithful, hold authority over ten cities.’

[[v42-19-18]]

^<<v42-19-18,18>>^ Now the second came, saying, ‘Your miʹna, Lord, made five miʹnas.’

[[v42-19-19]]

^<<v42-19-19,19>>^ He said to this one as well, ‘You too be in charge of five cities.’

[[v42-19-20]]

^<<v42-19-20,20>>^ But another one came, saying, ‘Lord, here is your miʹna that I kept hidden away in a cloth.

[[v42-19-21]]

^<<v42-19-21,21>>^ You see, I was in fear of you, because you are a harsh man; you take what you did not deposit, and you reap what you did not sow.’

[[v42-19-22]]

^<<v42-19-22,22>>^ He said to him, ‘By your own words I judge you, wicked slave. You knew, did you, that I am a harsh man, taking what I did not deposit and reaping what I did not sow?

[[v42-19-23]]

^<<v42-19-23,23>>^ So why did you not put my money^&#42;1^ in a bank? Then on my coming, I would have collected it with interest.’

[NOTE]
====
. Lit., “my silver.”
====

[[v42-19-24]]

^<<v42-19-24,24>>^ “With that he said to those standing by, ‘Take the miʹna from him and give it to the one who has the ten miʹnas.’

[[v42-19-25]]

^<<v42-19-25,25>>^ But they said to him, ‘Lord, he has ten miʹnas!’—

[[v42-19-26]]

^<<v42-19-26,26>>^ ‘I say to you, to everyone who has, more will be given, but from the one who does not have, even what he has will be taken away.

[[v42-19-27]]

^<<v42-19-27,27>>^ Moreover, bring these enemies of mine here who did not want me to become king over them and execute them in front of me.’”

[[v42-19-28]]

^<<v42-19-28,28>>^ After he had said these things, he went on ahead, going up to Jerusalem.

[[v42-19-29]]

^<<v42-19-29,29>>^ And when he got near to Bethʹpha·ge and Bethʹa·ny at the mountain called Mount of Olives, he sent two of the disciples,

[[v42-19-30]]

^<<v42-19-30,30>>^ saying: “Go into the village that is within sight, and after you enter it, you will find a colt tied, on which no man has ever sat. Untie it and bring it here.

[[v42-19-31]]

^<<v42-19-31,31>>^ But if anyone asks you, ‘Why are you untying it?’ you must say, ‘The Lord needs it.’”

[[v42-19-32]]

^<<v42-19-32,32>>^ So those who were sent went away and found it just as he had said to them.

[[v42-19-33]]

^<<v42-19-33,33>>^ But as they were untying the colt, its owners said to them: “Why are you untying the colt?”

[[v42-19-34]]

^<<v42-19-34,34>>^ They said: “The Lord needs it.”

[[v42-19-35]]

^<<v42-19-35,35>>^ And they led it to Jesus, and they threw their outer garments on the colt and seated Jesus on it.

[[v42-19-36]]

^<<v42-19-36,36>>^ As he moved along, they were spreading their outer garments on the road.

[[v42-19-37]]

^<<v42-19-37,37>>^ As soon as he got near the road down the Mount of Olives, the whole multitude of the disciples began to rejoice and to praise God with a loud voice because of all the powerful works they had seen,

[[v42-19-38]]

^<<v42-19-38,38>>^ saying: “Blessed is the one coming as the King in Jehovah’s^&#42;1^ name! Peace in heaven, and glory in the heights above!”

[NOTE]
====
. See App. A5.
====

[[v42-19-39]]

^<<v42-19-39,39>>^ However, some of the Pharisees from the crowd said to him: “Teacher, rebuke your disciples.”

[[v42-19-40]]

^<<v42-19-40,40>>^ But in reply he said: “I tell you, if these remained silent, the stones would cry out.”

[[v42-19-41]]

^<<v42-19-41,41>>^ And when he got nearby, he viewed the city and wept over it,

[[v42-19-42]]

^<<v42-19-42,42>>^ saying: “If you, even you, had discerned on this day the things having to do with peace—but now they have been hidden from your eyes.

[[v42-19-43]]

^<<v42-19-43,43>>^ Because the days will come upon you when your enemies will build around you a fortification of pointed stakes and will encircle you and besiege^&#42;1^ you from every side.

[NOTE]
====
. Or “distress.”
====

[[v42-19-44]]

^<<v42-19-44,44>>^ They will dash you and your children within you to the ground, and they will not leave a stone upon a stone in you, because you did not discern the time of your being inspected.”

[[v42-19-45]]

^<<v42-19-45,45>>^ Then he entered the temple and started to throw out those who were selling,

[[v42-19-46]]

^<<v42-19-46,46>>^ saying to them: “It is written, ‘My house will be a house of prayer,’ but you have made it a cave of robbers.”

[[v42-19-47]]

^<<v42-19-47,47>>^ He continued teaching daily in the temple. But the chief priests and the scribes and the principal ones of the people were seeking to kill him;

[[v42-19-48]]

^<<v42-19-48,48>>^ but they did not find any way to do this, for the people one and all kept hanging on to him to hear him.

'''

xref:042-luke/042-luke-018.adoc#v42-18-0[&#60; Capítulo Anterior] | <<v42-19-0,Topo>> | xref:042-luke/042-luke-020.adoc#v42-20-0[Próximo Capítulo &#62;]