include::./index.adoc[]

[[v42-23-0]]
=== According to Luke, 23
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-23-1]]

^<<v42-23-1,1>>^ So the multitude got up, one and all, and led him to Pilate.

[[v42-23-2]]

^<<v42-23-2,2>>^ Then they began to accuse him, saying: “We found this man subverting our nation, forbidding the paying of taxes to Caesar, and saying he himself is Christ a king.”

[[v42-23-3]]

^<<v42-23-3,3>>^ Now Pilate asked him the question: “Are you the King of the Jews?” In answer he said: “You yourself are saying it.”

[[v42-23-4]]

^<<v42-23-4,4>>^ Then Pilate said to the chief priests and the crowds: “I find no crime in this man.”

[[v42-23-5]]

^<<v42-23-5,5>>^ But they insisted, saying: “He stirs up the people by teaching throughout all Ju·deʹa, starting from Galʹi·lee even to here.”

[[v42-23-6]]

^<<v42-23-6,6>>^ On hearing that, Pilate asked whether the man was a Gal·i·leʹan.

[[v42-23-7]]

^<<v42-23-7,7>>^ After ascertaining that he was under the jurisdiction of Herod, he sent him on to Herod, who was also in Jerusalem in those days.

[[v42-23-8]]

^<<v42-23-8,8>>^ When Herod saw Jesus, he rejoiced greatly. For a considerable time he had been wanting to see Jesus because he had heard much about him, and he was hoping to see some sign performed by him.

[[v42-23-9]]

^<<v42-23-9,9>>^ So he began to question him at length, but he gave him no answer.

[[v42-23-10]]

^<<v42-23-10,10>>^ However, the chief priests and the scribes kept standing up and vehemently accusing him.

[[v42-23-11]]

^<<v42-23-11,11>>^ Then Herod together with his soldiers treated him with contempt, and he mocked him by clothing him with a splendid garment and then sent him back to Pilate.

[[v42-23-12]]

^<<v42-23-12,12>>^ Herod and Pilate became friends with each other on that very day, for before that they had been at enmity with each other.

[[v42-23-13]]

^<<v42-23-13,13>>^ Pilate then called together the chief priests, the rulers, and the people

[[v42-23-14]]

^<<v42-23-14,14>>^ and said to them: “You brought this man to me as one inciting the people to revolt. Now look! I examined him in front of you but found in this man no grounds for the charges you are bringing against him.

[[v42-23-15]]

^<<v42-23-15,15>>^ In fact, neither did Herod, for he sent him back to us, and look! he has done nothing deserving of death.

[[v42-23-16]]

^<<v42-23-16,16>>^ I will therefore punish him and release him.”

[[v42-23-17]]

^<<v42-23-17,17>>^ ^&#42;1^ ——

[NOTE]
====
. See App. A3.
====

[[v42-23-18]]

^<<v42-23-18,18>>^ But the whole crowd shouted out: “Do away with this man,^&#42;1^ and release Bar·abʹbas to us!”

[NOTE]
====
. Lit., “Take this one away.”
====

[[v42-23-19]]

^<<v42-23-19,19>>^ (This man had been thrown into prison for sedition that had occurred in the city and for murder.)

[[v42-23-20]]

^<<v42-23-20,20>>^ Again Pilate called out to them, because he wanted to release Jesus.

[[v42-23-21]]

^<<v42-23-21,21>>^ Then they began to yell, saying: “To the stake with him! To the stake with him!”^&#42;1^

[NOTE]
====
. Or “Execute him on the stake! Execute him on the stake!”
====

[[v42-23-22]]

^<<v42-23-22,22>>^ The third time he said to them: “Why? What bad thing did this man do? I found in him nothing deserving of death; I will therefore punish him and release him.”

[[v42-23-23]]

^<<v42-23-23,23>>^ At this they became insistent, demanding with loud voices that he be executed,^&#42;1^ and their voices prevailed.

[NOTE]
====
. Or “executed on the stake.”
====

[[v42-23-24]]

^<<v42-23-24,24>>^ So Pilate made the decision that their demand be met.

[[v42-23-25]]

^<<v42-23-25,25>>^ He released the man whom they were demanding, who had been thrown into prison for sedition and murder, but he surrendered Jesus to their will.

[[v42-23-26]]

^<<v42-23-26,26>>^ Now as they led him away, they seized a certain Simon of Cy·reʹne, who was coming from the countryside, and they placed the torture stake^&#42;1^ on him to carry it behind Jesus.

[NOTE]
====
. See Glossary.
====

[[v42-23-27]]

^<<v42-23-27,27>>^ A large number of people were following him, including women who kept beating themselves in grief and wailing for him.

[[v42-23-28]]

^<<v42-23-28,28>>^ Jesus turned to the women and said: “Daughters of Jerusalem, stop weeping for me. Weep instead for yourselves and for your children;

[[v42-23-29]]

^<<v42-23-29,29>>^ for look! days are coming when people will say, ‘Happy are the barren women, the wombs that did not give birth and the breasts that did not nurse!’

[[v42-23-30]]

^<<v42-23-30,30>>^ Then they will start saying to the mountains, ‘Fall over us!’ and to the hills, ‘Cover us over!’

[[v42-23-31]]

^<<v42-23-31,31>>^ If they do these things when the tree is moist, what will occur when it is withered?”

[[v42-23-32]]

^<<v42-23-32,32>>^ Two other men, criminals, were also being led off to be executed with him.

[[v42-23-33]]

^<<v42-23-33,33>>^ And when they got to the place called Skull, they nailed him to the stake there alongside the criminals, one on his right and one on his left.

[[v42-23-34]]

^<<v42-23-34,34>>^ But Jesus was saying: “Father, forgive them, for they do not know what they are doing.” Furthermore, they cast lots to distribute his garments.

[[v42-23-35]]

^<<v42-23-35,35>>^ And the people stood looking on. But the rulers were sneering and saying: “Others he saved; let him save himself if he is the Christ of God, the Chosen One.”

[[v42-23-36]]

^<<v42-23-36,36>>^ Even the soldiers mocked him, coming up and offering him sour wine

[[v42-23-37]]

^<<v42-23-37,37>>^ and saying: “If you are the King of the Jews, save yourself.”

[[v42-23-38]]

^<<v42-23-38,38>>^ There was also an inscription over him: “This is the King of the Jews.”

[[v42-23-39]]

^<<v42-23-39,39>>^ Then one of the criminals hanging there began to speak abusively to him, saying: “You are the Christ, are you not? Save yourself and us too!”

[[v42-23-40]]

^<<v42-23-40,40>>^ In response the other rebuked him, saying: “Do you not fear God at all, now that you have received the same judgment?

[[v42-23-41]]

^<<v42-23-41,41>>^ And we rightly so, for we are getting back what we deserve for the things we did; but this man did nothing wrong.”

[[v42-23-42]]

^<<v42-23-42,42>>^ Then he said: “Jesus, remember me when you get into your Kingdom.”

[[v42-23-43]]

^<<v42-23-43,43>>^ And he said to him: “Truly I tell you today, you will be with me in Paradise.”

[[v42-23-44]]

^<<v42-23-44,44>>^ Well, by now it was about the sixth hour,^&#42;1^ and yet a darkness fell over all the land until the ninth hour,^&#42;2^

[NOTE]
====
. That is, about 12:00 noon.
. That is, about 3:00 p.m.
====

[[v42-23-45]]

^<<v42-23-45,45>>^ because the sunlight failed; then the curtain of the sanctuary was torn down the middle.

[[v42-23-46]]

^<<v42-23-46,46>>^ And Jesus called out with a loud voice and said: “Father, into your hands I entrust my spirit.” After he said this, he expired.^&#42;1^

[NOTE]
====
. Or “he breathed his last.”
====

[[v42-23-47]]

^<<v42-23-47,47>>^ Because of seeing what occurred, the army officer began to glorify God, saying: “Truly, this man was righteous.”

[[v42-23-48]]

^<<v42-23-48,48>>^ And when all the crowds that were gathered together there for this spectacle saw the things that occurred, they returned home, beating their chests.

[[v42-23-49]]

^<<v42-23-49,49>>^ And all those acquainted with him were standing at a distance. Also, women who had accompanied him from Galʹi·lee were there and saw these things.

[[v42-23-50]]

^<<v42-23-50,50>>^ And look! there was a man named Joseph, a member of the Council, who was a good and righteous man.

[[v42-23-51]]

^<<v42-23-51,51>>^ (This man had not voted in support of their scheme and action.) He was from Ar·i·ma·theʹa, a city of the Ju·deʹans, and was waiting for the Kingdom of God.

[[v42-23-52]]

^<<v42-23-52,52>>^ This man went in before Pilate and asked for the body of Jesus.

[[v42-23-53]]

^<<v42-23-53,53>>^ And he took it down and wrapped it up in fine linen, and he laid it in a tomb^&#42;1^ carved in the rock, where no man had yet lain.

[NOTE]
====
. Or “memorial tomb.”
====

[[v42-23-54]]

^<<v42-23-54,54>>^ Now it was the day of Preparation, and the Sabbath was about to begin.

[[v42-23-55]]

^<<v42-23-55,55>>^ But the women who had come with him from Galʹi·lee followed along and took a look at the tomb^&#42;1^ and saw how his body was laid,

[NOTE]
====
. Or “memorial tomb.”
====

[[v42-23-56]]

^<<v42-23-56,56>>^ and they went back to prepare spices and perfumed oils. But, of course, they rested on the Sabbath according to the commandment.

'''

xref:042-luke/042-luke-022.adoc#v42-22-0[&#60; Capítulo Anterior] | <<v42-23-0,Topo>> | xref:042-luke/042-luke-024.adoc#v42-24-0[Próximo Capítulo &#62;]