include::./index.adoc[]

[[v42-10-0]]
=== According to Luke, 10
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-10-1]]

^<<v42-10-1,1>>^ After these things the Lord designated 70 others and sent them out by twos ahead of him into every city and place where he himself was to go.

[[v42-10-2]]

^<<v42-10-2,2>>^ Then he said to them: “Yes, the harvest is great, but the workers are few. Therefore, beg the Master of the harvest to send out workers into his harvest.

[[v42-10-3]]

^<<v42-10-3,3>>^ Go! Look! I am sending you out as lambs in among wolves.

[[v42-10-4]]

^<<v42-10-4,4>>^ Do not carry a money bag or a food pouch or sandals, and do not greet anyone^&#42;1^ along the road.

[NOTE]
====
. Or “embrace anyone in greeting.”
====

[[v42-10-5]]

^<<v42-10-5,5>>^ Wherever you enter into a house, say first: ‘May this house have peace.’

[[v42-10-6]]

^<<v42-10-6,6>>^ And if a friend of peace is there, your peace will rest upon him. But if there is not, it will return to you.

[[v42-10-7]]

^<<v42-10-7,7>>^ So stay in that house, eating and drinking the things they provide, for the worker is worthy of his wages. Do not keep transferring from house to house.

[[v42-10-8]]

^<<v42-10-8,8>>^ “Also, wherever you enter into a city and they receive you, eat what is set before you

[[v42-10-9]]

^<<v42-10-9,9>>^ and cure the sick ones in it and tell them: ‘The Kingdom of God has come near to you.’

[[v42-10-10]]

^<<v42-10-10,10>>^ But wherever you enter into a city and they do not receive you, go out into its main streets and say:

[[v42-10-11]]

^<<v42-10-11,11>>^ ‘We wipe off against you even the dust that sticks to our feet from your city. Nevertheless, know this, that the Kingdom of God has come near.’

[[v42-10-12]]

^<<v42-10-12,12>>^ I tell you that it will be more endurable for Sodʹom in that day than for that city.

[[v42-10-13]]

^<<v42-10-13,13>>^ “Woe to you, Cho·raʹzin! Woe to you, Beth·saʹi·da! because if the powerful works that have taken place in you had taken place in Tyre and Siʹdon, they would long ago have repented, sitting in sackcloth and ashes.

[[v42-10-14]]

^<<v42-10-14,14>>^ Consequently, it will be more endurable for Tyre and Siʹdon in the judgment than for you.

[[v42-10-15]]

^<<v42-10-15,15>>^ And you, Ca·perʹna·um, will you perhaps be exalted to heaven? Down to the Grave^&#42;1^ you will come!

[NOTE]
====
. Or “Hades,” that is, the common grave of mankind. See Glossary.
====

[[v42-10-16]]

^<<v42-10-16,16>>^ “Whoever listens to you listens to me. And whoever disregards you disregards me also. Moreover, whoever disregards me disregards also Him who sent me.”

[[v42-10-17]]

^<<v42-10-17,17>>^ Then the 70 returned with joy, saying: “Lord, even the demons are made subject to us by the use of your name.”

[[v42-10-18]]

^<<v42-10-18,18>>^ At that he said to them: “I see Satan already fallen like lightning from heaven.

[[v42-10-19]]

^<<v42-10-19,19>>^ Look! I have given you the authority to trample underfoot serpents and scorpions, and over all the power of the enemy, and nothing at all will harm you.

[[v42-10-20]]

^<<v42-10-20,20>>^ Nevertheless, do not rejoice because the spirits are made subject to you, but rejoice because your names have been written in the heavens.”

[[v42-10-21]]

^<<v42-10-21,21>>^ In that very hour he became overjoyed in the holy spirit and said: “I publicly praise you, Father, Lord of heaven and earth, because you have carefully hidden these things from wise and intellectual ones and have revealed them to young children. Yes, O Father, because this is the way you approved.

[[v42-10-22]]

^<<v42-10-22,22>>^ All things have been handed over to me by my Father, and no one knows who the Son is except the Father, and no one knows who the Father is except the Son and anyone to whom the Son is willing to reveal him.”

[[v42-10-23]]

^<<v42-10-23,23>>^ With that he turned to the disciples and told them privately: “Happy are the eyes that see the things you are seeing.

[[v42-10-24]]

^<<v42-10-24,24>>^ For I say to you, many prophets and kings desired to see the things you are observing but did not see them, and to hear the things you are hearing but did not hear them.”

[[v42-10-25]]

^<<v42-10-25,25>>^ Now look! a man versed in the Law stood up to test him and said: “Teacher, what do I need to do to inherit everlasting life?”

[[v42-10-26]]

^<<v42-10-26,26>>^ He said to him: “What is written in the Law? How do you read?”

[[v42-10-27]]

^<<v42-10-27,27>>^ In answer he said: “‘You must love Jehovah^&#42;1^ your God with your whole heart and with your whole soul^&#42;2^ and with your whole strength and with your whole mind’ and ‘your neighbor as yourself.’”

[NOTE]
====
. See App. A5.
. See Glossary.
====

[[v42-10-28]]

^<<v42-10-28,28>>^ He said to him: “You answered correctly; keep doing this and you will get life.”

[[v42-10-29]]

^<<v42-10-29,29>>^ But wanting to prove himself righteous, the man said to Jesus: “Who really is my neighbor?”

[[v42-10-30]]

^<<v42-10-30,30>>^ In reply Jesus said: “A man was going down from Jerusalem to Jerʹi·cho and fell victim to robbers, who stripped him, beat him, and went off, leaving him half-dead.

[[v42-10-31]]

^<<v42-10-31,31>>^ Now by coincidence a priest was going down on that road, but when he saw him, he passed by on the opposite side.

[[v42-10-32]]

^<<v42-10-32,32>>^ Likewise, a Levite, when he came to the place and saw him, passed by on the opposite side.

[[v42-10-33]]

^<<v42-10-33,33>>^ But a certain Sa·marʹi·tan traveling the road came upon him, and at seeing him, he was moved with pity.

[[v42-10-34]]

^<<v42-10-34,34>>^ So he approached him and bandaged his wounds, pouring oil and wine on them. Then he mounted him on his own animal and brought him to an inn and took care of him.

[[v42-10-35]]

^<<v42-10-35,35>>^ The next day he took out two de·narʹi·i,^&#42;1^ gave them to the innkeeper, and said: ‘Take care of him, and whatever you spend besides this, I will repay you when I return.’

[NOTE]
====
. See App. B14.
====

[[v42-10-36]]

^<<v42-10-36,36>>^ Who of these three seems to you to have made himself neighbor to the man who fell victim to the robbers?”

[[v42-10-37]]

^<<v42-10-37,37>>^ He said: “The one who acted mercifully toward him.” Jesus then said to him: “Go and do the same yourself.”

[[v42-10-38]]

^<<v42-10-38,38>>^ Now as they went on their way, he entered into a certain village. Here a woman named Martha received him as a guest in her house.

[[v42-10-39]]

^<<v42-10-39,39>>^ She also had a sister called Mary, who sat down at the feet of the Lord and kept listening to what he was saying.^&#42;1^

[NOTE]
====
. Lit., “his word.”
====

[[v42-10-40]]

^<<v42-10-40,40>>^ Martha, on the other hand, was distracted with attending to many duties. So she came to him and said: “Lord, does it not matter to you that my sister has left me alone to attend to things? Tell her to come and help me.”

[[v42-10-41]]

^<<v42-10-41,41>>^ In answer the Lord said to her: “Martha, Martha, you are anxious and disturbed about many things.

[[v42-10-42]]

^<<v42-10-42,42>>^ A few things, though, are needed, or just one. For her part, Mary chose the good portion,^&#42;1^ and it will not be taken away from her.”

[NOTE]
====
. Or “best portion.”
====

'''

xref:042-luke/042-luke-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-luke/042-luke-011.adoc#v42-11-0[Próximo Capítulo &#62;]