include::./index.adoc[]

[[v42-4-0]]
=== According to Luke, 4
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-4-1]]

^<<v42-4-1,1>>^ Then Jesus, full of holy spirit, turned away from the Jordan, and he was led about by the spirit in the wilderness

[[v42-4-2]]

^<<v42-4-2,2>>^ for 40 days, being tempted by the Devil. And he ate nothing in those days, so when they had ended, he felt hungry.

[[v42-4-3]]

^<<v42-4-3,3>>^ At this the Devil said to him: “If you are a son of God, tell this stone to become a loaf of bread.”

[[v42-4-4]]

^<<v42-4-4,4>>^ But Jesus answered him: “It is written, ‘Man must not live on bread alone.’”

[[v42-4-5]]

^<<v42-4-5,5>>^ So he brought him up and showed him all the kingdoms of the inhabited earth in an instant of time.

[[v42-4-6]]

^<<v42-4-6,6>>^ Then the Devil said to him: “I will give you all this authority and their glory, because it has been handed over to me, and I give it to whomever I wish.

[[v42-4-7]]

^<<v42-4-7,7>>^ If you, therefore, do an act of worship before me, it will all be yours.”

[[v42-4-8]]

^<<v42-4-8,8>>^ In reply Jesus said to him: “It is written, ‘It is Jehovah^&#42;1^ your God you must worship, and it is to him alone you must render sacred service.’”

[NOTE]
====
. See App. A5.
====

[[v42-4-9]]

^<<v42-4-9,9>>^ He then led him into Jerusalem and stationed him on the battlement^&#42;1^ of the temple and said to him: “If you are a son of God, throw yourself down from here,

[NOTE]
====
. Or “parapet; highest point.”
====

[[v42-4-10]]

^<<v42-4-10,10>>^ for it is written, ‘He will give his angels a command concerning you, to preserve you,’

[[v42-4-11]]

^<<v42-4-11,11>>^ and, ‘They will carry you on their hands, so that you may not strike your foot against a stone.’”

[[v42-4-12]]

^<<v42-4-12,12>>^ In answer Jesus said to him: “It is said, ‘You must not put Jehovah^&#42;1^ your God to the test.’”

[NOTE]
====
. See App. A5.
====

[[v42-4-13]]

^<<v42-4-13,13>>^ So the Devil, having finished all the temptation, departed from him until another convenient time.

[[v42-4-14]]

^<<v42-4-14,14>>^ Now Jesus returned in the power of the spirit into Galʹi·lee. And good reports about him spread throughout all the surrounding country.

[[v42-4-15]]

^<<v42-4-15,15>>^ Also, he began to teach in their synagogues, and he was held in honor by all.

[[v42-4-16]]

^<<v42-4-16,16>>^ He then went to Nazʹa·reth, where he had been brought up, and according to his custom on the Sabbath day, he entered the synagogue and stood up to read.

[[v42-4-17]]

^<<v42-4-17,17>>^ So the scroll of the prophet Isaiah was handed to him, and he opened the scroll and found the place where it was written:

[[v42-4-18]]

^<<v42-4-18,18>>^ “Jehovah’s^&#42;1^ spirit is upon me, because he anointed me to declare good news to the poor. He sent me to proclaim liberty to the captives and a recovery of sight to the blind, to send the crushed ones away free,

[NOTE]
====
. See App. A5.
====

[[v42-4-19]]

^<<v42-4-19,19>>^ to preach Jehovah’s^&#42;1^ acceptable year.”

[NOTE]
====
. See App. A5.
====

[[v42-4-20]]

^<<v42-4-20,20>>^ With that he rolled up the scroll, handed it back to the attendant, and sat down; and the eyes of all in the synagogue were intently fixed on him.

[[v42-4-21]]

^<<v42-4-21,21>>^ Then he began to say to them: “Today this scripture that you just heard is fulfilled.”

[[v42-4-22]]

^<<v42-4-22,22>>^ And they all began to give favorable witness about him and to be amazed at the gracious words coming out of his mouth, and they were saying: “This is a son of Joseph, is it not?”

[[v42-4-23]]

^<<v42-4-23,23>>^ At this he said to them: “No doubt you will apply this saying to me, ‘Physician, cure yourself. Do also here in your home territory the things we have heard were done in Ca·perʹna·um.’”

[[v42-4-24]]

^<<v42-4-24,24>>^ So he said: “Truly I tell you that no prophet is accepted in his home territory.

[[v42-4-25]]

^<<v42-4-25,25>>^ For instance, I tell you in truth: There were many widows in Israel in the days of E·liʹjah when heaven was shut up for three years and six months, and a great famine came on all the land.

[[v42-4-26]]

^<<v42-4-26,26>>^ Yet E·liʹjah was sent to none of those women, but only to a widow in Zarʹe·phath in the land of Siʹdon.

[[v42-4-27]]

^<<v42-4-27,27>>^ Also, there were many lepers in Israel in the time of E·liʹsha the prophet; yet not one of them was cleansed,^&#42;1^ only Naʹa·man the Syrian.”

[NOTE]
====
. Or “healed.”
====

[[v42-4-28]]

^<<v42-4-28,28>>^ Now all those hearing these things in the synagogue became filled with anger,

[[v42-4-29]]

^<<v42-4-29,29>>^ and they rose up and rushed him outside the city, and they led him to the brow of the mountain on which their city had been built, in order to throw him down headlong.

[[v42-4-30]]

^<<v42-4-30,30>>^ But he went right through their midst and continued on his way.

[[v42-4-31]]

^<<v42-4-31,31>>^ He then went down to Ca·perʹna·um, a city of Galʹi·lee. And he was teaching them on the Sabbath,

[[v42-4-32]]

^<<v42-4-32,32>>^ and they were astounded at his way of teaching, because he spoke with authority.

[[v42-4-33]]

^<<v42-4-33,33>>^ Now in the synagogue there was a man with a spirit, an unclean demon, and he shouted with a loud voice:

[[v42-4-34]]

^<<v42-4-34,34>>^ “Ah! What have we to do with you, Jesus the Naz·a·reneʹ? Did you come to destroy us? I know exactly who you are, the Holy One of God.”

[[v42-4-35]]

^<<v42-4-35,35>>^ But Jesus rebuked it, saying: “Be silent, and come out of him.” So after throwing the man down in their midst, the demon came out of him without hurting him.

[[v42-4-36]]

^<<v42-4-36,36>>^ At this they were all astonished and began to say to one another: “What kind of speech is this? For with authority and power he orders the unclean spirits, and out they come!”

[[v42-4-37]]

^<<v42-4-37,37>>^ So the news about him kept spreading into every corner of the surrounding country.

[[v42-4-38]]

^<<v42-4-38,38>>^ After leaving the synagogue, he entered into Simon’s home. Now Simon’s mother-in-law was suffering with a high fever, and they asked him to help her.

[[v42-4-39]]

^<<v42-4-39,39>>^ So he stood over her and rebuked the fever, and it left her. Instantly she got up and began ministering to them.

[[v42-4-40]]

^<<v42-4-40,40>>^ But when the sun was setting, all those who had people sick with various diseases brought them to him. By laying his hands on each one of them, he cured them.

[[v42-4-41]]

^<<v42-4-41,41>>^ Demons also came out of many, crying out and saying: “You are the Son of God.” But rebuking them, he would not permit them to speak, for they knew him to be the Christ.

[[v42-4-42]]

^<<v42-4-42,42>>^ However, at daybreak he departed and went to an isolated place. But the crowds began searching^&#42;1^ for him and came to where he was, and they tried to keep him from going away from them.

[NOTE]
====
. Or “hunting.”
====

[[v42-4-43]]

^<<v42-4-43,43>>^ But he said to them: “I must also declare the good news of the Kingdom of God to other cities, because for this I was sent.”

[[v42-4-44]]

^<<v42-4-44,44>>^ So he went on preaching in the synagogues of Ju·deʹa.

'''

xref:042-luke/042-luke-003.adoc#v42-3-0[&#60; Capítulo Anterior] | <<v42-4-0,Topo>> | xref:042-luke/042-luke-005.adoc#v42-5-0[Próximo Capítulo &#62;]