include::./index.adoc[]

[[v42-11-0]]
=== According to Luke, 11
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-11-1]]

^<<v42-11-1,1>>^ Now he was in a certain place praying, and when he stopped, one of his disciples said to him: “Lord, teach us how to pray, just as John also taught his disciples.”

[[v42-11-2]]

^<<v42-11-2,2>>^ So he said to them: “Whenever you pray, say: ‘Father, let your name be sanctified.^&#42;1^ Let your Kingdom come.

[NOTE]
====
. Or “be held sacred; be treated as holy.”
====

[[v42-11-3]]

^<<v42-11-3,3>>^ Give us each day our bread according to our daily needs.

[[v42-11-4]]

^<<v42-11-4,4>>^ And forgive us our sins, for we ourselves also forgive everyone who is in debt to us; and do not bring us into temptation.’”

[[v42-11-5]]

^<<v42-11-5,5>>^ Then he said to them: “Suppose one of you has a friend and you go to him at midnight and say to him, ‘Friend, lend me three loaves,

[[v42-11-6]]

^<<v42-11-6,6>>^ because one of my friends has just come to me on a journey and I have nothing to offer him.’

[[v42-11-7]]

^<<v42-11-7,7>>^ But that one replies from inside: ‘Stop bothering me. The door is already locked, and my young children are with me in bed. I cannot get up and give you anything.’

[[v42-11-8]]

^<<v42-11-8,8>>^ I tell you, even if he will not get up and give him anything because of being his friend, certainly because of his bold persistence he will get up and give him whatever he needs.

[[v42-11-9]]

^<<v42-11-9,9>>^ So I say to you, keep on asking, and it will be given you; keep on seeking, and you will find; keep on knocking, and it will be opened to you.

[[v42-11-10]]

^<<v42-11-10,10>>^ For everyone asking receives, and everyone seeking finds, and to everyone knocking, it will be opened.

[[v42-11-11]]

^<<v42-11-11,11>>^ Indeed, which father among you, if his son asks for a fish, will hand him a serpent instead of a fish?

[[v42-11-12]]

^<<v42-11-12,12>>^ Or if he also asks for an egg, will hand him a scorpion?

[[v42-11-13]]

^<<v42-11-13,13>>^ Therefore, if you, although being wicked, know how to give good gifts to your children, how much more so will the Father in heaven give holy spirit to those asking him!”

[[v42-11-14]]

^<<v42-11-14,14>>^ Later he expelled a speechless demon. After the demon came out, the speechless man spoke, and the crowds were amazed.

[[v42-11-15]]

^<<v42-11-15,15>>^ But some of them said: “He expels the demons by means of Be·elʹze·bub,^&#42;1^ the ruler of the demons.”

[NOTE]
====
. A designation applied to Satan.
====

[[v42-11-16]]

^<<v42-11-16,16>>^ And others, to test him, began demanding a sign out of heaven from him.

[[v42-11-17]]

^<<v42-11-17,17>>^ Knowing their thinking, he said to them: “Every kingdom divided against itself comes to ruin, and a house divided against itself falls.

[[v42-11-18]]

^<<v42-11-18,18>>^ In the same way, if Satan is also divided against himself, how will his kingdom stand? For you say I expel the demons by means of Be·elʹze·bub.

[[v42-11-19]]

^<<v42-11-19,19>>^ If I expel the demons by means of Be·elʹze·bub, by whom do your sons expel them? This is why they will be your judges.

[[v42-11-20]]

^<<v42-11-20,20>>^ But if it is by means of God’s finger that I expel the demons, the Kingdom of God has really overtaken you.

[[v42-11-21]]

^<<v42-11-21,21>>^ When a strong, well-armed man guards his palace, his belongings remain secure.

[[v42-11-22]]

^<<v42-11-22,22>>^ But when someone stronger than he is comes against him and conquers him, that man takes away all his weapons in which he was trusting, and he divides up the things he took from him.

[[v42-11-23]]

^<<v42-11-23,23>>^ Whoever is not on my side is against me, and whoever does not gather with me scatters.

[[v42-11-24]]

^<<v42-11-24,24>>^ “When an unclean spirit comes out of a man, it passes through waterless places in search of a resting-place, and after finding none, it says, ‘I will return to my house from which I moved.’

[[v42-11-25]]

^<<v42-11-25,25>>^ And on arriving, it finds the house swept clean and adorned.

[[v42-11-26]]

^<<v42-11-26,26>>^ Then it goes and takes along seven other spirits more wicked than itself, and after getting inside, they dwell there. So the final circumstances of that man become worse than the first.”

[[v42-11-27]]

^<<v42-11-27,27>>^ Now as he was saying these things, a woman from the crowd called out to him: “Happy is the womb that carried you and the breasts that nursed you!”

[[v42-11-28]]

^<<v42-11-28,28>>^ But he said: “No, rather, happy are those hearing the word of God and keeping it!”

[[v42-11-29]]

^<<v42-11-29,29>>^ When the crowds were massing together, he began to say: “This generation is a wicked generation; it looks for a sign, but no sign will be given to it except the sign of Joʹnah.

[[v42-11-30]]

^<<v42-11-30,30>>^ For just as Joʹnah became a sign to the Ninʹe·vites, so will the Son of man be to this generation.

[[v42-11-31]]

^<<v42-11-31,31>>^ The queen of the south will be raised up in the judgment with the men of this generation and will condemn them, for she came from the ends of the earth to hear the wisdom of Solʹo·mon. But look! something more than Solʹo·mon is here.

[[v42-11-32]]

^<<v42-11-32,32>>^ The men of Ninʹe·veh will rise in the judgment with this generation and will condemn it, because they repented at what Joʹnah preached. But look! something more than Joʹnah is here.

[[v42-11-33]]

^<<v42-11-33,33>>^ After lighting a lamp, a person puts it, not in a hidden place nor under a basket,^&#42;1^ but on the lampstand, so that those who come in may see the light.

[NOTE]
====
. Or “measuring basket.”
====

[[v42-11-34]]

^<<v42-11-34,34>>^ The lamp of the body is your eye. When your eye is focused,^&#42;1^ your whole body is also bright;^&#42;2^ but when it is envious,^&#42;3^ your body is also dark.

[NOTE]
====
. Or “clear.” Lit., “simple.”
. Or “full of light.”
. Lit., “bad; wicked.”
====

[[v42-11-35]]

^<<v42-11-35,35>>^ Be alert, therefore, that the light that is in you is not darkness.

[[v42-11-36]]

^<<v42-11-36,36>>^ Therefore, if your whole body is bright with no part of it dark, it will all be as bright as when a lamp gives you light by its rays.”

[[v42-11-37]]

^<<v42-11-37,37>>^ When he had said this, a Pharisee asked him to dine with him. So he went in and reclined at the table.

[[v42-11-38]]

^<<v42-11-38,38>>^ However, the Pharisee was surprised at seeing that he did not first wash^&#42;1^ before the dinner.

[NOTE]
====
. That is, ceremonially cleanse himself.
====

[[v42-11-39]]

^<<v42-11-39,39>>^ But the Lord said to him: “Now you Pharisees, you cleanse the outside of the cup and dish, but inside you are full of greediness and wickedness.

[[v42-11-40]]

^<<v42-11-40,40>>^ Unreasonable ones! The one who made the outside made also the inside, did he not?

[[v42-11-41]]

^<<v42-11-41,41>>^ But give as gifts of mercy^&#42;1^ the things that are from within, and look! everything about you will be clean.

[NOTE]
====
. Or “gifts to the poor.” See Glossary.
====

[[v42-11-42]]

^<<v42-11-42,42>>^ But woe to you Pharisees, because you give the tenth of the mint and of the rue and of every other garden herb,^&#42;1^ but you disregard the justice and the love of God! These things you were under obligation to do, but not to disregard those other things.

[NOTE]
====
. Or “other vegetable.”
====

[[v42-11-43]]

^<<v42-11-43,43>>^ Woe to you Pharisees, because you love the front^&#42;1^ seats in the synagogues and the greetings in the marketplaces!

[NOTE]
====
. Or “best.”
====

[[v42-11-44]]

^<<v42-11-44,44>>^ Woe to you, because you are as those graves^&#42;1^ that are not clearly visible,^&#42;2^ that men walk on and do not know it!”

[NOTE]
====
. Or “memorial tombs.”
. Or “those unmarked graves.”
====

[[v42-11-45]]

^<<v42-11-45,45>>^ In reply one of those versed in the Law said to him: “Teacher, in saying these things, you insult us also.”

[[v42-11-46]]

^<<v42-11-46,46>>^ Then he said: “Woe also to you who are versed in the Law, because you load men down with loads hard to carry, but you yourselves do not touch the loads with one of your fingers!

[[v42-11-47]]

^<<v42-11-47,47>>^ “Woe to you, because you build the tombs^&#42;1^ of the prophets, but your forefathers killed them!

[NOTE]
====
. Or “memorial tombs.”
====

[[v42-11-48]]

^<<v42-11-48,48>>^ Certainly you are witnesses of the deeds of your forefathers, and yet you approve of them, for they killed the prophets but you are building their tombs.

[[v42-11-49]]

^<<v42-11-49,49>>^ That is why the wisdom of God also said: ‘I will send prophets and apostles to them, and they will kill and persecute some of them,

[[v42-11-50]]

^<<v42-11-50,50>>^ so that the blood of all the prophets spilled from the founding of the world may be charged against^&#42;1^ this generation,

[NOTE]
====
. Or “required from.”
====

[[v42-11-51]]

^<<v42-11-51,51>>^ from the blood of Abel down to the blood of Zech·a·riʹah, who was killed between the altar and the house.’^&#42;1^ Yes, I tell you, it will be charged against^&#42;2^ this generation.

[NOTE]
====
. Or “temple.”
. Or “required from.”
====

[[v42-11-52]]

^<<v42-11-52,52>>^ “Woe to you who are versed in the Law, because you took away the key of knowledge. You yourselves did not go in, and you hinder those going in!”

[[v42-11-53]]

^<<v42-11-53,53>>^ So when he went out from there, the scribes and the Pharisees began to put extreme pressure on him and to ply him with many more questions,

[[v42-11-54]]

^<<v42-11-54,54>>^ lying in wait for him to catch him in something he might say.

'''

xref:042-luke/042-luke-010.adoc#v42-10-0[&#60; Capítulo Anterior] | <<v42-11-0,Topo>> | xref:042-luke/042-luke-012.adoc#v42-12-0[Próximo Capítulo &#62;]