include::./index.adoc[]

[[v42-1-0]]
=== According to Luke, 1
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-1-1]]

^<<v42-1-1,1>>^ Seeing that many have undertaken to compile an account of the facts that are given full credence^&#42;1^ among us,

[NOTE]
====
. Or “credibility.”
====

[[v42-1-2]]

^<<v42-1-2,2>>^ just as these were handed down to us by those who from the beginning were eyewitnesses and attendants of the message,

[[v42-1-3]]

^<<v42-1-3,3>>^ I resolved also, because I have traced all things from the start with accuracy, to write them to you in logical order, most excellent The·ophʹi·lus,

[[v42-1-4]]

^<<v42-1-4,4>>^ so that you may know fully the certainty of the things that you have been taught orally.

[[v42-1-5]]

^<<v42-1-5,5>>^ In the days of Herod,^&#42;1^ king of Ju·deʹa, there was a priest named Zech·a·riʹah of the division of A·biʹjah. His wife was from the daughters of Aaron, and her name was Elizabeth.

[NOTE]
====
. See Glossary.
====

[[v42-1-6]]

^<<v42-1-6,6>>^ They both were righteous before God, walking blamelessly in accord with all the commandments and legal requirements of Jehovah.^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v42-1-7]]

^<<v42-1-7,7>>^ But they had no child, because Elizabeth was barren, and they both were well along in years.

[[v42-1-8]]

^<<v42-1-8,8>>^ Now as he was serving as priest in the assignment of his division before God,

[[v42-1-9]]

^<<v42-1-9,9>>^ according to the established practice^&#42;1^ of the priesthood it became his turn to offer incense when he entered into the sanctuary of Jehovah.^&#42;2^

[NOTE]
====
. Or “custom.”
. See App. A5.
====

[[v42-1-10]]

^<<v42-1-10,10>>^ And the entire multitude of the people were praying outside at the hour of offering incense.

[[v42-1-11]]

^<<v42-1-11,11>>^ Jehovah’s^&#42;1^ angel appeared to him, standing at the right side of the incense altar.

[NOTE]
====
. See App. A5.
====

[[v42-1-12]]

^<<v42-1-12,12>>^ But Zech·a·riʹah became troubled at the sight, and he was overcome with fear.

[[v42-1-13]]

^<<v42-1-13,13>>^ However, the angel said to him: “Do not be afraid, Zech·a·riʹah, because your supplication has been favorably heard, and your wife Elizabeth will bear you a son, and you are to name him John.

[[v42-1-14]]

^<<v42-1-14,14>>^ You will have joy and great gladness, and many will rejoice over his birth,

[[v42-1-15]]

^<<v42-1-15,15>>^ for he will be great in the sight of Jehovah.^&#42;1^ But he must drink no wine or any alcoholic drink at all, and he will be filled with holy spirit even from before birth,^&#42;2^

[NOTE]
====
. See App. A5.
. Or “right from his mother’s womb.”
====

[[v42-1-16]]

^<<v42-1-16,16>>^ and he will turn back many of the sons of Israel to Jehovah^&#42;1^ their God.

[NOTE]
====
. See App. A5.
====

[[v42-1-17]]

^<<v42-1-17,17>>^ Also, he will go ahead of him with E·liʹjah’s spirit and power, to turn back the hearts of fathers to children and the disobedient ones to the practical wisdom of righteous ones, in order to get ready for Jehovah^&#42;1^ a prepared people.”

[NOTE]
====
. See App. A5.
====

[[v42-1-18]]

^<<v42-1-18,18>>^ Zech·a·riʹah said to the angel: “How can I be sure of this? For I am old, and my wife is well along in years.”

[[v42-1-19]]

^<<v42-1-19,19>>^ In reply the angel said to him: “I am Gaʹbri·el, who stands near before God, and I was sent to speak with you and to declare this good news to you.

[[v42-1-20]]

^<<v42-1-20,20>>^ But look! you will be silent and unable to speak until the day these things take place, because you did not believe my words, which will be fulfilled in their appointed time.”

[[v42-1-21]]

^<<v42-1-21,21>>^ Meanwhile, the people continued waiting for Zech·a·riʹah, and they were surprised that he delayed so long in the sanctuary.

[[v42-1-22]]

^<<v42-1-22,22>>^ When he came out, he was unable to speak to them, and they perceived that he had just seen a supernatural sight^&#42;1^ in the sanctuary. He kept making signs to them but remained speechless.

[NOTE]
====
. Or “a vision.”
====

[[v42-1-23]]

^<<v42-1-23,23>>^ When the days of his holy service^&#42;1^ were completed, he went off to his home.

[NOTE]
====
. Or “his public service.”
====

[[v42-1-24]]

^<<v42-1-24,24>>^ Some days later Elizabeth his wife became pregnant, and she kept herself secluded for five months, saying:

[[v42-1-25]]

^<<v42-1-25,25>>^ “This is how Jehovah^&#42;1^ has dealt with me in these days. He has turned his attention to me to take away my reproach among men.”

[NOTE]
====
. See App. A5.
====

[[v42-1-26]]

^<<v42-1-26,26>>^ In her sixth month, the angel Gaʹbri·el was sent from God to a city of Galʹi·lee named Nazʹa·reth,

[[v42-1-27]]

^<<v42-1-27,27>>^ to a virgin promised in marriage^&#42;1^ to a man named Joseph of David’s house, and the name of the virgin was Mary.

[NOTE]
====
. Or “engaged.”
====

[[v42-1-28]]

^<<v42-1-28,28>>^ And coming in, the angel said to her: “Greetings, you highly favored one, Jehovah^&#42;1^ is with you.”

[NOTE]
====
. See App. A5.
====

[[v42-1-29]]

^<<v42-1-29,29>>^ But she was deeply disturbed at his words and tried to understand what kind of greeting this might be.

[[v42-1-30]]

^<<v42-1-30,30>>^ So the angel said to her: “Do not be afraid, Mary, for you have found favor with God.

[[v42-1-31]]

^<<v42-1-31,31>>^ And look! you will become pregnant^&#42;1^ and give birth to a son, and you are to name him Jesus.

[NOTE]
====
. Or “conceive in your womb.”
====

[[v42-1-32]]

^<<v42-1-32,32>>^ This one will be great and will be called Son of the Most High, and Jehovah^&#42;1^ God will give him the throne of David his father,

[NOTE]
====
. See App. A5.
====

[[v42-1-33]]

^<<v42-1-33,33>>^ and he will rule as King over the house of Jacob forever, and there will be no end to his Kingdom.”

[[v42-1-34]]

^<<v42-1-34,34>>^ But Mary said to the angel: “How is this to be, since I am not having sexual relations with a man?”

[[v42-1-35]]

^<<v42-1-35,35>>^ In answer the angel said to her: “Holy spirit will come upon you, and power of the Most High will overshadow you. And for that reason the one who is born will be called holy, God’s Son.

[[v42-1-36]]

^<<v42-1-36,36>>^ And look! Elizabeth your relative has also conceived a son, in her old age, and this is the sixth month for her, the so-called barren woman;

[[v42-1-37]]

^<<v42-1-37,37>>^ for no declaration^&#42;1^ will be impossible for God.”

[NOTE]
====
. Or “nothing.”
====

[[v42-1-38]]

^<<v42-1-38,38>>^ Then Mary said: “Look! Jehovah’s^&#42;1^ slave girl! May it happen to me according to your declaration.” At that the angel departed from her.

[NOTE]
====
. See App. A5.
====

[[v42-1-39]]

^<<v42-1-39,39>>^ So Mary set out in those days and traveled with haste into the mountainous country, to a city of Judah,

[[v42-1-40]]

^<<v42-1-40,40>>^ and she entered the home of Zech·a·riʹah and greeted Elizabeth.

[[v42-1-41]]

^<<v42-1-41,41>>^ Well, as Elizabeth heard the greeting of Mary, the infant in her womb leaped, and Elizabeth was filled with holy spirit

[[v42-1-42]]

^<<v42-1-42,42>>^ and loudly cried out: “Blessed are you among women, and blessed is the fruitage of your womb!

[[v42-1-43]]

^<<v42-1-43,43>>^ So how is it that this privilege is mine, to have the mother of my Lord come to me?

[[v42-1-44]]

^<<v42-1-44,44>>^ For look! as the sound of your greeting reached my ears, the infant in my womb leaped for joy.

[[v42-1-45]]

^<<v42-1-45,45>>^ Happy too is she who believed, for there will be a complete fulfillment of those things spoken to her from Jehovah.”^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v42-1-46]]

^<<v42-1-46,46>>^ And Mary said: “My soul^&#42;1^ magnifies Jehovah,^&#42;2^

[NOTE]
====
. Or “My whole being.” See Glossary.
. See App. A5.
====

[[v42-1-47]]

^<<v42-1-47,47>>^ and my spirit cannot keep from being overjoyed at God my Savior,

[[v42-1-48]]

^<<v42-1-48,48>>^ because he has looked upon the low position of his slave girl. For look! from now on all generations will declare me happy,

[[v42-1-49]]

^<<v42-1-49,49>>^ because the powerful One has done great deeds for me, and holy is his name,

[[v42-1-50]]

^<<v42-1-50,50>>^ and for generation after generation his mercy is upon those who fear him.

[[v42-1-51]]

^<<v42-1-51,51>>^ He has acted mightily with his arm; he has scattered those who are haughty in the intention of their hearts.

[[v42-1-52]]

^<<v42-1-52,52>>^ He has brought down powerful men from thrones and has exalted lowly ones;

[[v42-1-53]]

^<<v42-1-53,53>>^ he has fully satisfied hungry ones with good things and has sent away empty-handed those who had wealth.

[[v42-1-54]]

^<<v42-1-54,54>>^ He has come to the aid of Israel his servant, remembering his mercy,

[[v42-1-55]]

^<<v42-1-55,55>>^ just as he spoke to our forefathers, to Abraham and to his offspring,^&#42;1^ forever.”

[NOTE]
====
. Lit., “seed.”
====

[[v42-1-56]]

^<<v42-1-56,56>>^ Mary stayed with her about three months and then returned to her own home.

[[v42-1-57]]

^<<v42-1-57,57>>^ The time now came for Elizabeth to give birth, and she gave birth to a son.

[[v42-1-58]]

^<<v42-1-58,58>>^ And the neighbors and her relatives heard that Jehovah^&#42;1^ had magnified his mercy to her, and they rejoiced with her.

[NOTE]
====
. See App. A5.
====

[[v42-1-59]]

^<<v42-1-59,59>>^ On the eighth day they came to circumcise the young child, and they were going to name him after his father, Zech·a·riʹah.

[[v42-1-60]]

^<<v42-1-60,60>>^ But his mother said in reply: “No! but he will be called John.”

[[v42-1-61]]

^<<v42-1-61,61>>^ At this they said to her: “Not one of your relatives is called by this name.”

[[v42-1-62]]

^<<v42-1-62,62>>^ Then they asked his father by signs what he wanted him to be called.

[[v42-1-63]]

^<<v42-1-63,63>>^ So he asked for a tablet and wrote: “John is his name.” At this they were all amazed.

[[v42-1-64]]

^<<v42-1-64,64>>^ Instantly his mouth was opened and his tongue was set free and he began to speak, praising God.

[[v42-1-65]]

^<<v42-1-65,65>>^ And fear fell upon all those living in their neighborhood, and all these things began to be talked about in the whole mountainous country of Ju·deʹa.

[[v42-1-66]]

^<<v42-1-66,66>>^ And all who heard noted it in their hearts, saying: “What will this young child turn out to be?” For the hand of Jehovah^&#42;1^ was indeed with him.

[NOTE]
====
. See App. A5.
====

[[v42-1-67]]

^<<v42-1-67,67>>^ Then Zech·a·riʹah his father was filled with holy spirit, and he prophesied, saying:

[[v42-1-68]]

^<<v42-1-68,68>>^ “Let Jehovah^&#42;1^ be praised, the God of Israel, because he has turned his attention to his people and has brought them deliverance.

[NOTE]
====
. See App. A5.
====

[[v42-1-69]]

^<<v42-1-69,69>>^ And he has raised up a horn of salvation^&#42;1^ for us in the house of David his servant,

[NOTE]
====
. Or “a powerful savior.” See Glossary, “Horn.”
====

[[v42-1-70]]

^<<v42-1-70,70>>^ just as he has spoken through the mouth of his holy prophets from of old,

[[v42-1-71]]

^<<v42-1-71,71>>^ of a salvation from our enemies and from the hand of all those hating us;

[[v42-1-72]]

^<<v42-1-72,72>>^ to show mercy in connection with our forefathers and to call to mind his holy covenant,

[[v42-1-73]]

^<<v42-1-73,73>>^ the oath that he swore to Abraham our forefather,

[[v42-1-74]]

^<<v42-1-74,74>>^ to grant us, after we have been rescued from the hands of enemies, the privilege of fearlessly rendering sacred service to him

[[v42-1-75]]

^<<v42-1-75,75>>^ with loyalty and righteousness before him all our days.

[[v42-1-76]]

^<<v42-1-76,76>>^ But as for you, young child, you will be called a prophet of the Most High, for you will go ahead of Jehovah^&#42;1^ to prepare his ways,

[NOTE]
====
. See App. A5.
====

[[v42-1-77]]

^<<v42-1-77,77>>^ to give knowledge of salvation to his people by forgiveness of their sins,

[[v42-1-78]]

^<<v42-1-78,78>>^ because of the tender compassion of our God. With this compassion a daybreak will visit us from on high,

[[v42-1-79]]

^<<v42-1-79,79>>^ to give light to those sitting in darkness and death’s shadow and to guide our feet in the way of peace.”

[[v42-1-80]]

^<<v42-1-80,80>>^ And the young child grew up and became strong in spirit, and he continued in the desert until the day he showed himself openly to Israel.

'''

xref:041-mark/041-mark-016.adoc#v41-16-0[&#60; Capítulo Anterior] | <<v42-1-0,Topo>> | xref:042-luke/042-luke-002.adoc#v42-2-0[Próximo Capítulo &#62;]