include::./index.adoc[]

[[v42-5-0]]
=== According to Luke, 5
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-5-1]]

^<<v42-5-1,1>>^ On one occasion when the crowd was pressing in on him and listening to the word of God, he was standing by the lake of Gen·nesʹa·ret.^&#42;1^

[NOTE]
====
. That is, the Sea of Galilee.
====

[[v42-5-2]]

^<<v42-5-2,2>>^ And he saw two boats docked at the lakeside, but the fishermen had got out of them and were washing off their nets.

[[v42-5-3]]

^<<v42-5-3,3>>^ Going aboard one of the boats, which was Simon’s, he asked him to pull away a bit from land. Then he sat down, and he began teaching the crowds from the boat.

[[v42-5-4]]

^<<v42-5-4,4>>^ When he stopped speaking, he said to Simon: “Pull out to where it is deep, and let down your nets for a catch.”

[[v42-5-5]]

^<<v42-5-5,5>>^ But in reply Simon said: “Instructor, we toiled all night and caught nothing, but at your word I will lower the nets.”

[[v42-5-6]]

^<<v42-5-6,6>>^ Well, when they did this, they caught^&#42;1^ a great number of fish. In fact, their nets began ripping apart.

[NOTE]
====
. Lit., “enclosed.”
====

[[v42-5-7]]

^<<v42-5-7,7>>^ So they motioned to their partners in the other boat to come and assist them, and they came and filled both boats, so that these began to sink.

[[v42-5-8]]

^<<v42-5-8,8>>^ Seeing this, Simon Peter fell down at the knees of Jesus, saying: “Depart from me, Lord, because I am a sinful man.”

[[v42-5-9]]

^<<v42-5-9,9>>^ For both he and those with him were overwhelmed with astonishment at the catch of fish they had taken,

[[v42-5-10]]

^<<v42-5-10,10>>^ and the same was true of both James and John, Zebʹe·dee’s sons, who were partners with Simon. But Jesus said to Simon: “Stop being afraid. From now on you will be catching men^&#42;1^ alive.”

[NOTE]
====
. Or “people.”
====

[[v42-5-11]]

^<<v42-5-11,11>>^ So they brought the boats back to land and abandoned everything and followed him.

[[v42-5-12]]

^<<v42-5-12,12>>^ On another occasion while he was in one of the cities, look! there was a man full of leprosy! When he caught sight of Jesus, he fell facedown and begged him: “Lord, if you just want to, you can make me clean.”

[[v42-5-13]]

^<<v42-5-13,13>>^ So stretching out his hand, he touched him, saying: “I want to! Be made clean.” Immediately the leprosy vanished from him.

[[v42-5-14]]

^<<v42-5-14,14>>^ Then he gave the man orders to tell no one: “But go and show yourself to the priest, and make an offering for your cleansing, just as Moses directed, for a witness to them.”

[[v42-5-15]]

^<<v42-5-15,15>>^ But the news about him just kept spreading, and large crowds would gather together to listen and to be cured of their sicknesses.

[[v42-5-16]]

^<<v42-5-16,16>>^ However, he often went into the desolate areas to pray.

[[v42-5-17]]

^<<v42-5-17,17>>^ On one of those days while he was teaching, Pharisees and teachers of the Law who had come out of every village of Galʹi·lee and Ju·deʹa and from Jerusalem were sitting there; and Jehovah’s^&#42;1^ power was with him to do healing.

[NOTE]
====
. See App. A5.
====

[[v42-5-18]]

^<<v42-5-18,18>>^ And look! men were carrying a paralyzed man on a stretcher, and they were trying to bring him in and place him before Jesus.

[[v42-5-19]]

^<<v42-5-19,19>>^ So not finding a way to bring him in because of the crowd, they climbed up to the roof, and they lowered him on the stretcher through the tiling, right among those in front of Jesus.

[[v42-5-20]]

^<<v42-5-20,20>>^ When he saw their faith, he said: “Man, your sins are forgiven.”

[[v42-5-21]]

^<<v42-5-21,21>>^ Then the scribes and the Pharisees started to reason, saying: “Who is this who speaks blasphemies? Who can forgive sins except God alone?”

[[v42-5-22]]

^<<v42-5-22,22>>^ But Jesus, discerning their reasoning, said in answer to them: “What are you reasoning in your hearts?

[[v42-5-23]]

^<<v42-5-23,23>>^ Which is easier, to say, ‘Your sins are forgiven,’ or to say, ‘Get up and walk’?

[[v42-5-24]]

^<<v42-5-24,24>>^ But in order for you to know that the Son of man has authority on earth to forgive sins—” he said to the paralyzed man: “I say to you, Get up, pick up your stretcher, and go to your home.”

[[v42-5-25]]

^<<v42-5-25,25>>^ At that he stood up before them, picked up what he had been lying on, and went to his home, glorifying God.

[[v42-5-26]]

^<<v42-5-26,26>>^ Then one and all were seized with amazement, and they began to glorify God, and they became filled with awe, saying: “We have seen wonderful things today!”

[[v42-5-27]]

^<<v42-5-27,27>>^ Now after this, he went out and saw a tax collector named Leʹvi sitting at the tax office, and he said to him: “Be my follower.”

[[v42-5-28]]

^<<v42-5-28,28>>^ And leaving everything behind, he rose up and began to follow him.

[[v42-5-29]]

^<<v42-5-29,29>>^ Then Leʹvi spread a big reception feast for him in his house, and there was a large crowd of tax collectors and others who were dining^&#42;1^ with them.

[NOTE]
====
. Or “reclining at the table.”
====

[[v42-5-30]]

^<<v42-5-30,30>>^ At this the Pharisees and their scribes began murmuring to his disciples, saying: “Why do you eat and drink with tax collectors and sinners?”

[[v42-5-31]]

^<<v42-5-31,31>>^ In reply Jesus said to them: “Those who are healthy do not need a physician, but those who are ill do.

[[v42-5-32]]

^<<v42-5-32,32>>^ I have come to call, not righteous people, but sinners to repentance.”

[[v42-5-33]]

^<<v42-5-33,33>>^ They said to him: “John’s disciples fast frequently and offer supplications, and so do those of the Pharisees, but yours eat and drink.”

[[v42-5-34]]

^<<v42-5-34,34>>^ Jesus said to them: “You cannot make the friends of the bridegroom fast while the bridegroom is with them, can you?

[[v42-5-35]]

^<<v42-5-35,35>>^ But days will come when the bridegroom will indeed be taken away from them; then they will fast in those days.”

[[v42-5-36]]

^<<v42-5-36,36>>^ He also gave an illustration to them: “Nobody cuts a patch from a new outer garment and sews it on an old garment. If he does, then the new patch tears away and the patch from the new garment does not match the old.

[[v42-5-37]]

^<<v42-5-37,37>>^ Also, no one puts new wine into old wineskins. If he does, the new wine will burst the wineskins and it will be spilled out and the wineskins will be ruined.

[[v42-5-38]]

^<<v42-5-38,38>>^ But new wine must be put into new wineskins.

[[v42-5-39]]

^<<v42-5-39,39>>^ No one after drinking old wine wants new, for he says, ‘The old is nice.’”

'''

xref:042-luke/042-luke-004.adoc#v42-4-0[&#60; Capítulo Anterior] | <<v42-5-0,Topo>> | xref:042-luke/042-luke-006.adoc#v42-6-0[Próximo Capítulo &#62;]