include::./index.adoc[]

[[v42-21-0]]
=== According to Luke, 21
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-21-1]]

^<<v42-21-1,1>>^ Now as he looked up, he saw the rich dropping their gifts into the treasury chests.^&#42;1^

[NOTE]
====
. Or “receptacles.”
====

[[v42-21-2]]

^<<v42-21-2,2>>^ Then he saw a needy widow drop in two small coins of very little value,^&#42;1^

[NOTE]
====
. Lit., “two lepta.” See App. B14.
====

[[v42-21-3]]

^<<v42-21-3,3>>^ and he said: “Truly I say to you that this poor widow put in more than they all did.

[[v42-21-4]]

^<<v42-21-4,4>>^ For all of these put in gifts out of their surplus, but she, out of her want,^&#42;1^ put in all the means of living she had.”

[NOTE]
====
. Or “poverty.”
====

[[v42-21-5]]

^<<v42-21-5,5>>^ Later, when some were speaking about the temple, how it was adorned with fine stones and dedicated things,

[[v42-21-6]]

^<<v42-21-6,6>>^ he said: “As for these things that you now see, the days will come when not a stone will be left upon a stone and not be thrown down.”

[[v42-21-7]]

^<<v42-21-7,7>>^ Then they questioned him, saying: “Teacher, when will these things actually be, and what will be the sign when these things are to occur?”

[[v42-21-8]]

^<<v42-21-8,8>>^ He said: “Look out that you are not misled, for many will come on the basis of my name, saying, ‘I am he,’ and, ‘The due time is near.’ Do not go after them.

[[v42-21-9]]

^<<v42-21-9,9>>^ Furthermore, when you hear of wars and disturbances,^&#42;1^ do not be terrified. For these things must take place first, but the end will not occur immediately.”

[NOTE]
====
. Or “disorders; uprisings.”
====

[[v42-21-10]]

^<<v42-21-10,10>>^ Then he said to them: “Nation will rise against nation, and kingdom against kingdom.

[[v42-21-11]]

^<<v42-21-11,11>>^ There will be great earthquakes, and in one place after another food shortages and pestilences; and there will be fearful sights and from heaven great signs.

[[v42-21-12]]

^<<v42-21-12,12>>^ “But before all these things happen, people will lay their hands on you and persecute you, handing you over to the synagogues and prisons. You will be brought before kings and governors for the sake of my name.

[[v42-21-13]]

^<<v42-21-13,13>>^ It will result in your giving a witness.

[[v42-21-14]]

^<<v42-21-14,14>>^ Therefore, resolve in your hearts not to rehearse beforehand how to make your defense,

[[v42-21-15]]

^<<v42-21-15,15>>^ for I will give you words and wisdom that all your opposers together will not be able to resist or dispute.

[[v42-21-16]]

^<<v42-21-16,16>>^ Moreover, you will be handed over^&#42;1^ even by parents and brothers and relatives and friends, and they will put some of you to death,

[NOTE]
====
. Or “betrayed.”
====

[[v42-21-17]]

^<<v42-21-17,17>>^ and you will be hated by all people because of my name.

[[v42-21-18]]

^<<v42-21-18,18>>^ But not even a hair of your heads will perish.

[[v42-21-19]]

^<<v42-21-19,19>>^ By your endurance you will preserve your lives.^&#42;1^

[NOTE]
====
. Or “acquire your souls.”
====

[[v42-21-20]]

^<<v42-21-20,20>>^ “However, when you see Jerusalem surrounded by encamped armies, then know that the desolating of her has drawn near.

[[v42-21-21]]

^<<v42-21-21,21>>^ Then let those in Ju·deʹa begin fleeing to the mountains, let those in the midst of her leave, and let those in the countryside not enter into her,

[[v42-21-22]]

^<<v42-21-22,22>>^ because these are days for meting out justice^&#42;1^ in order that all the things written may be fulfilled.

[NOTE]
====
. Or “days of vengeance.”
====

[[v42-21-23]]

^<<v42-21-23,23>>^ Woe to the pregnant women and those nursing a baby in those days! For there will be great distress on the land and wrath against this people.

[[v42-21-24]]

^<<v42-21-24,24>>^ And they will fall by the edge of the sword and be led captive into all the nations; and Jerusalem will be trampled on by the nations^&#42;1^ until the appointed times of the nations^&#42;2^ are fulfilled.

[NOTE]
====
. Or “Gentiles.”
. Or “Gentiles.”
====

[[v42-21-25]]

^<<v42-21-25,25>>^ “Also, there will be signs in the sun and moon and stars, and on the earth anguish of nations not knowing the way out because of the roaring of the sea and its agitation.

[[v42-21-26]]

^<<v42-21-26,26>>^ People will become faint out of fear and expectation of the things coming upon the inhabited earth, for the powers of the heavens will be shaken.

[[v42-21-27]]

^<<v42-21-27,27>>^ And then they will see the Son of man coming in a cloud with power and great glory.

[[v42-21-28]]

^<<v42-21-28,28>>^ But as these things start to occur, stand up straight and lift up your heads, because your deliverance is getting near.”

[[v42-21-29]]

^<<v42-21-29,29>>^ With that he told them an illustration: “Notice the fig tree and all the other trees.

[[v42-21-30]]

^<<v42-21-30,30>>^ When they are budding, you see it for yourselves and know that now the summer is near.

[[v42-21-31]]

^<<v42-21-31,31>>^ Likewise also you, when you see these things happening, know that the Kingdom of God is near.

[[v42-21-32]]

^<<v42-21-32,32>>^ Truly I say to you that this generation will by no means pass away until all things happen.

[[v42-21-33]]

^<<v42-21-33,33>>^ Heaven and earth will pass away, but my words will by no means pass away.

[[v42-21-34]]

^<<v42-21-34,34>>^ “But pay attention to yourselves that your hearts never become weighed down with overeating and heavy drinking and anxieties of life, and suddenly that day be instantly upon you

[[v42-21-35]]

^<<v42-21-35,35>>^ as a snare. For it will come upon all those dwelling on the face of the whole earth.

[[v42-21-36]]

^<<v42-21-36,36>>^ Keep awake, then, all the time making supplication that you may succeed in escaping all these things that must occur and in standing before the Son of man.”

[[v42-21-37]]

^<<v42-21-37,37>>^ So by day he would be teaching in the temple, but by night he would go out and lodge on the mountain called the Mount of Olives.

[[v42-21-38]]

^<<v42-21-38,38>>^ And all the people would come to him early in the morning to hear him in the temple.

'''

xref:042-luke/042-luke-020.adoc#v42-20-0[&#60; Capítulo Anterior] | <<v42-21-0,Topo>> | xref:042-luke/042-luke-022.adoc#v42-22-0[Próximo Capítulo &#62;]