include::./index.adoc[]

[[v42-13-0]]
=== According to Luke, 13
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-13-1]]

^<<v42-13-1,1>>^ At that time some who were present reported to him about the Gal·i·leʹans whose blood Pilate had mixed with their sacrifices.

[[v42-13-2]]

^<<v42-13-2,2>>^ In reply he said to them: “Do you think that those Gal·i·leʹans were worse sinners than all other Gal·i·leʹans because they have suffered these things?

[[v42-13-3]]

^<<v42-13-3,3>>^ No, I tell you; but unless you repent, you will all likewise be destroyed.

[[v42-13-4]]

^<<v42-13-4,4>>^ Or those 18 on whom the tower in Si·loʹam fell, killing them—do you think that they had greater guilt than all other men who live in Jerusalem?

[[v42-13-5]]

^<<v42-13-5,5>>^ No, I tell you; but unless you repent, you will all be destroyed, as they were.”

[[v42-13-6]]

^<<v42-13-6,6>>^ Then he went on to tell this illustration: “A man had a fig tree planted in his vineyard, and he came looking for fruit on it but found none.

[[v42-13-7]]

^<<v42-13-7,7>>^ Then he said to the vinedresser, ‘Here it is three years that I have come looking for fruit on this fig tree, but have found none. Cut it down! Why should it keep the ground useless?’

[[v42-13-8]]

^<<v42-13-8,8>>^ In reply he said to him, ‘Master, leave it alone for one more year until I dig around it and put on manure.

[[v42-13-9]]

^<<v42-13-9,9>>^ If it produces fruit in the future, well and good; but if not, then cut it down.’”

[[v42-13-10]]

^<<v42-13-10,10>>^ Now he was teaching in one of the synagogues on the Sabbath.

[[v42-13-11]]

^<<v42-13-11,11>>^ And look! a woman was there who had had a spirit of weakness^&#42;1^ for 18 years; and she was bent double and was unable to straighten up at all.

[NOTE]
====
. Or “a disabling spirit.”
====

[[v42-13-12]]

^<<v42-13-12,12>>^ When he saw her, Jesus addressed her and said: “Woman, you are released from your weakness.”

[[v42-13-13]]

^<<v42-13-13,13>>^ And he laid his hands on her, and instantly she straightened up and began to glorify God.

[[v42-13-14]]

^<<v42-13-14,14>>^ But in response the presiding officer of the synagogue, indignant because Jesus did the cure on the Sabbath, said to the crowd: “There are six days on which work ought to be done; so come and be cured on those days, and not on the Sabbath day.”

[[v42-13-15]]

^<<v42-13-15,15>>^ However, the Lord answered him: “Hypocrites, does not each one of you on the Sabbath untie his bull or his donkey from the stall and lead it away to give it something to drink?

[[v42-13-16]]

^<<v42-13-16,16>>^ Should not this woman, who is a daughter of Abraham and whom Satan held bound for 18 years, be released from this bondage on the Sabbath day?”

[[v42-13-17]]

^<<v42-13-17,17>>^ Well, when he said these things, all his opposers began to feel shame, but the entire crowd began to rejoice at all the glorious things he did.

[[v42-13-18]]

^<<v42-13-18,18>>^ So he went on to say: “What is the Kingdom of God like, and with what can I compare it?

[[v42-13-19]]

^<<v42-13-19,19>>^ It is like a mustard grain that a man took and planted in his garden, and it grew and became a tree, and the birds of heaven nested in its branches.”

[[v42-13-20]]

^<<v42-13-20,20>>^ And again he said: “With what can I compare the Kingdom of God?

[[v42-13-21]]

^<<v42-13-21,21>>^ It is like leaven that a woman took and mixed with three large measures^&#42;1^ of flour until the whole mass was fermented.”

[NOTE]
====
. Lit., “seah measures.” A seah equaled 7.33 L (6.66 dry qt). See App. B14.
====

[[v42-13-22]]

^<<v42-13-22,22>>^ And he traveled from city to city and from village to village, teaching and continuing on his journey to Jerusalem.

[[v42-13-23]]

^<<v42-13-23,23>>^ Now a man said to him: “Lord, are those being saved few?” He said to them:

[[v42-13-24]]

^<<v42-13-24,24>>^ “Exert yourselves vigorously to get in through the narrow door, because many, I tell you, will seek to get in but will not be able.

[[v42-13-25]]

^<<v42-13-25,25>>^ When the householder gets up and locks the door, you will stand outside knocking at the door, saying, ‘Lord, open to us.’ But in answer he will say to you: ‘I do not know where you are from.’

[[v42-13-26]]

^<<v42-13-26,26>>^ Then you will start saying, ‘We ate and drank in your presence, and you taught in our main streets.’

[[v42-13-27]]

^<<v42-13-27,27>>^ But he will say to you, ‘I do not know where you are from. Get away from me, all you workers of unrighteousness!’

[[v42-13-28]]

^<<v42-13-28,28>>^ There is where your weeping and the gnashing of your teeth will be, when you see Abraham, Isaac, Jacob, and all the prophets in the Kingdom of God, but you yourselves thrown outside.

[[v42-13-29]]

^<<v42-13-29,29>>^ Furthermore, people will come from east and west and from north and south, and will recline at the table in the Kingdom of God.

[[v42-13-30]]

^<<v42-13-30,30>>^ And look! there are those last who will be first, and there are those first who will be last.”

[[v42-13-31]]

^<<v42-13-31,31>>^ In that very hour some of the Pharisees came up and told him: “Get out and go away from here, because Herod wants to kill you.”

[[v42-13-32]]

^<<v42-13-32,32>>^ And he said to them: “Go and tell that fox, ‘Look! I am casting out demons and healing people today and tomorrow, and on the third day I will be finished.’

[[v42-13-33]]

^<<v42-13-33,33>>^ Nevertheless, I must go on today, tomorrow, and the following day, because it cannot be^&#42;1^ that a prophet should be put to death outside of Jerusalem.

[NOTE]
====
. Or “it is inconceivable.”
====

[[v42-13-34]]

^<<v42-13-34,34>>^ Jerusalem, Jerusalem, the killer of the prophets and stoner of those sent to her—how often I wanted to gather your children together the way a hen gathers her brood of chicks under her wings! But you did not want it.

[[v42-13-35]]

^<<v42-13-35,35>>^ Look! Your house is abandoned to you. I tell you, you will by no means see me until you say: ‘Blessed is the one who comes in Jehovah’s^&#42;1^ name!’”

[NOTE]
====
. See App. A5.
====

'''

xref:042-luke/042-luke-012.adoc#v42-12-0[&#60; Capítulo Anterior] | <<v42-13-0,Topo>> | xref:042-luke/042-luke-014.adoc#v42-14-0[Próximo Capítulo &#62;]