include::./index.adoc[]

[[v42-8-0]]
=== According to Luke, 8
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-8-1]]

^<<v42-8-1,1>>^ Shortly afterward he traveled from city to city and from village to village, preaching and declaring the good news of the Kingdom of God. And the Twelve were with him,

[[v42-8-2]]

^<<v42-8-2,2>>^ as were certain women who had been cured of wicked spirits and sicknesses: Mary who was called Magʹda·lene, from whom seven demons had come out;

[[v42-8-3]]

^<<v42-8-3,3>>^ Jo·anʹna the wife of Chuʹza, Herod’s man in charge; Su·sanʹna; and many other women, who were ministering to them from their belongings.

[[v42-8-4]]

^<<v42-8-4,4>>^ Now when a large crowd had gathered together with those who went to him from city to city, he spoke by means of an illustration:

[[v42-8-5]]

^<<v42-8-5,5>>^ “A sower went out to sow his seed. As he was sowing, some of them fell alongside the road and were trampled on, and the birds of heaven ate them up.

[[v42-8-6]]

^<<v42-8-6,6>>^ Some landed on the rock, and after sprouting, they dried up because they had no moisture.

[[v42-8-7]]

^<<v42-8-7,7>>^ Others fell among the thorns, and the thorns that grew up with them choked them.

[[v42-8-8]]

^<<v42-8-8,8>>^ But others fell on the good soil, and after sprouting, they produced 100 times more fruit.” As he said these things, he called out: “Let the one who has ears to listen, listen.”

[[v42-8-9]]

^<<v42-8-9,9>>^ But his disciples asked him what this illustration meant.

[[v42-8-10]]

^<<v42-8-10,10>>^ He said: “To you it is granted to understand the sacred secrets of the Kingdom of God, but for the rest it is in illustrations so that, though looking, they may look in vain, and though hearing, they may not get the sense.

[[v42-8-11]]

^<<v42-8-11,11>>^ Now the illustration means this: The seed is the word of God.

[[v42-8-12]]

^<<v42-8-12,12>>^ Those alongside the road are the ones who have heard, and then the Devil comes and takes the word away from their hearts so that they may not believe and be saved.

[[v42-8-13]]

^<<v42-8-13,13>>^ Those on the rock are the ones who, when they hear the word, receive it with joy, but these have no root. They believe for a while, but in a season of testing, they fall away.

[[v42-8-14]]

^<<v42-8-14,14>>^ As for that which fell among the thorns, these are the ones who have heard, but by being carried away by anxieties, riches, and pleasures of this life, they are completely choked and bring nothing to maturity.

[[v42-8-15]]

^<<v42-8-15,15>>^ As for that on the fine soil, these are the ones who, after hearing the word with a fine and good heart, retain it and bear fruit with endurance.

[[v42-8-16]]

^<<v42-8-16,16>>^ “No one after lighting a lamp covers it with a vessel or puts it underneath a bed, but he puts it on a lampstand so that those who come in may see the light.

[[v42-8-17]]

^<<v42-8-17,17>>^ For there is nothing hidden that will not become manifest, nor anything carefully concealed that will never become known and not come out in the open.

[[v42-8-18]]

^<<v42-8-18,18>>^ Therefore, pay attention to how you listen, for whoever has will be given more, but whoever does not have, even what he imagines he has will be taken away from him.”

[[v42-8-19]]

^<<v42-8-19,19>>^ Now his mother and brothers came to him, but they were unable to get near him because of the crowd.

[[v42-8-20]]

^<<v42-8-20,20>>^ So it was reported to him: “Your mother and your brothers are standing outside, wanting to see you.”

[[v42-8-21]]

^<<v42-8-21,21>>^ In reply he said to them: “My mother and my brothers are these who hear the word of God and do it.”

[[v42-8-22]]

^<<v42-8-22,22>>^ One day he and his disciples got into a boat, and he said to them: “Let us cross to the other side of the lake.” So they set sail.

[[v42-8-23]]

^<<v42-8-23,23>>^ But as they were sailing along, he fell asleep. And a violent windstorm descended on the lake, and their boat began to fill up with water and to be in danger.

[[v42-8-24]]

^<<v42-8-24,24>>^ So they went and woke him up, saying: “Instructor, Instructor, we are about to perish!” With that he got up and rebuked the wind and the raging of the water, and they subsided, and a calm set in.

[[v42-8-25]]

^<<v42-8-25,25>>^ Then he said to them: “Where is your faith?” But they were filled with fear and were astounded, saying to one another: “Who really is this? For he orders even the winds and the water, and they obey him.”

[[v42-8-26]]

^<<v42-8-26,26>>^ And they put in to shore in the region of the Gerʹa·senes, which is on the side opposite Galʹi·lee.

[[v42-8-27]]

^<<v42-8-27,27>>^ As Jesus got out onto land, a demon-possessed man from the city met him. For a considerable time he had not worn clothing, and he was staying, not in a house, but among the tombs.^&#42;1^

[NOTE]
====
. Or “memorial tombs.”
====

[[v42-8-28]]

^<<v42-8-28,28>>^ At the sight of Jesus, he cried out and fell down before him, and with a loud voice, he said: “What have I to do with you, Jesus, Son of the Most High God? I beg you, do not torment me.”

[[v42-8-29]]

^<<v42-8-29,29>>^ (For Jesus had been ordering the unclean spirit to come out of the man. It had seized him on many occasions,^&#42;1^ and he was repeatedly bound with chains and fetters and kept under guard, but he would break the bonds and be driven by the demon into the isolated places.)

[NOTE]
====
. Or possibly, “Over a long time it had held him fast.”
====

[[v42-8-30]]

^<<v42-8-30,30>>^ Jesus asked him: “What is your name?” He said: “Legion,” for many demons had entered into him.

[[v42-8-31]]

^<<v42-8-31,31>>^ And they kept pleading with him not to order them to go away into the abyss.

[[v42-8-32]]

^<<v42-8-32,32>>^ Now a large herd of swine was feeding there on the mountain, so they pleaded with him to permit them to enter into the swine, and he gave them permission.

[[v42-8-33]]

^<<v42-8-33,33>>^ With that the demons came out of the man and went into the swine, and the herd rushed over the precipice^&#42;1^ into the lake and drowned.

[NOTE]
====
. Or “steep bank.”
====

[[v42-8-34]]

^<<v42-8-34,34>>^ But when the herders saw what had happened, they fled and reported it in the city and in the countryside.

[[v42-8-35]]

^<<v42-8-35,35>>^ Then people went out to see what had happened. They came to Jesus and found the man from whom the demons had come out, clothed and in his right mind, sitting at the feet of Jesus, and they grew fearful.

[[v42-8-36]]

^<<v42-8-36,36>>^ Those who had seen it reported to them how the demon-possessed man had been made well.

[[v42-8-37]]

^<<v42-8-37,37>>^ Then a great number from the surrounding region of the Gerʹa·senes asked Jesus to go away from them, because they were gripped by great fear. Then he went aboard the boat to depart.

[[v42-8-38]]

^<<v42-8-38,38>>^ However, the man from whom the demons had gone out kept begging to continue with him, but he sent the man away, saying:

[[v42-8-39]]

^<<v42-8-39,39>>^ “Go back home, and keep on relating what God did for you.” So he went away, proclaiming throughout the whole city what Jesus had done for him.

[[v42-8-40]]

^<<v42-8-40,40>>^ When Jesus returned, the crowd received him kindly, for they were all expecting him.

[[v42-8-41]]

^<<v42-8-41,41>>^ But look! a man named Jaʹi·rus came; this man was a presiding officer of the synagogue. And he fell at the feet of Jesus and began to plead with him to come to his house,

[[v42-8-42]]

^<<v42-8-42,42>>^ because his only^&#42;1^ daughter, who was about 12 years old, was dying.
As Jesus was going, the crowds pressed in on him.

[NOTE]
====
. Lit., “only-begotten.”
====

[[v42-8-43]]

^<<v42-8-43,43>>^ Now there was a woman who had a flow of blood for 12 years, and she had not been able to get a cure from anyone.

[[v42-8-44]]

^<<v42-8-44,44>>^ She approached from behind and touched the fringe of his outer garment, and immediately her flow of blood stopped.

[[v42-8-45]]

^<<v42-8-45,45>>^ So Jesus said: “Who touched me?” When they were all denying it, Peter said: “Instructor, the crowds are hemming you in and pressing against you.”

[[v42-8-46]]

^<<v42-8-46,46>>^ But Jesus said: “Someone touched me, for I know that power went out of me.”

[[v42-8-47]]

^<<v42-8-47,47>>^ Seeing that she had not escaped notice, the woman came trembling and fell down before him and declared before all the people why she touched him and how she was healed immediately.

[[v42-8-48]]

^<<v42-8-48,48>>^ But he said to her: “Daughter, your faith has made you well. Go in peace.”

[[v42-8-49]]

^<<v42-8-49,49>>^ While he was yet speaking, a representative of the presiding officer of the synagogue came, saying: “Your daughter has died; do not bother the Teacher any longer.”

[[v42-8-50]]

^<<v42-8-50,50>>^ On hearing this, Jesus answered him: “Have no fear, only have faith, and she will be saved.”

[[v42-8-51]]

^<<v42-8-51,51>>^ When he reached the house, he did not let anyone go in with him except Peter, John, James, and the girl’s father and mother.

[[v42-8-52]]

^<<v42-8-52,52>>^ But people were all weeping and beating themselves in grief for her. So he said: “Stop weeping, for she did not die but is sleeping.”

[[v42-8-53]]

^<<v42-8-53,53>>^ At this they began to laugh at him scornfully, because they knew she had died.

[[v42-8-54]]

^<<v42-8-54,54>>^ But he took her by the hand and called to her: “Child, get up!”

[[v42-8-55]]

^<<v42-8-55,55>>^ And her spirit^&#42;1^ returned, and she rose immediately, and he ordered that something be given her to eat.

[NOTE]
====
. Or “life force.”
====

[[v42-8-56]]

^<<v42-8-56,56>>^ Well, her parents were beside themselves, but he instructed them to tell no one what had happened.

'''

xref:042-luke/042-luke-007.adoc#v42-7-0[&#60; Capítulo Anterior] | <<v42-8-0,Topo>> | xref:042-luke/042-luke-009.adoc#v42-9-0[Próximo Capítulo &#62;]