include::./index.adoc[]

[[v42-22-0]]
=== According to Luke, 22
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-22-1]]

^<<v42-22-1,1>>^ Now the Festival of the Unleavened Bread, which is called Passover, was getting near.

[[v42-22-2]]

^<<v42-22-2,2>>^ And the chief priests and the scribes were looking for an effective way to get rid of him, because they were afraid of the people.

[[v42-22-3]]

^<<v42-22-3,3>>^ Then Satan entered into Judas, the one called Is·carʹi·ot, who was numbered among the Twelve,

[[v42-22-4]]

^<<v42-22-4,4>>^ and he went off and talked with the chief priests and temple captains about how to betray him to them.

[[v42-22-5]]

^<<v42-22-5,5>>^ They were delighted at this and agreed to give him silver money.

[[v42-22-6]]

^<<v42-22-6,6>>^ So he consented and began looking for a good opportunity to betray him to them without a crowd around.

[[v42-22-7]]

^<<v42-22-7,7>>^ The day of the Unleavened Bread now arrived, on which the Passover sacrifice must be offered;

[[v42-22-8]]

^<<v42-22-8,8>>^ so Jesus sent Peter and John, saying: “Go and get the Passover ready for us to eat.”

[[v42-22-9]]

^<<v42-22-9,9>>^ They said to him: “Where do you want us to get it ready?”

[[v42-22-10]]

^<<v42-22-10,10>>^ He said to them: “Look! When you enter into the city, a man carrying an earthenware water jar will meet you. Follow him into the house that he enters.

[[v42-22-11]]

^<<v42-22-11,11>>^ And say to the landlord of the house, ‘The Teacher says to you: “Where is the guest room where I may eat the Passover with my disciples?”’

[[v42-22-12]]

^<<v42-22-12,12>>^ And that man will show you a large, furnished upper room. Get it ready there.”

[[v42-22-13]]

^<<v42-22-13,13>>^ So they left and found it just as he had told them, and they prepared for the Passover.

[[v42-22-14]]

^<<v42-22-14,14>>^ So when the hour came, he reclined at the table along with the apostles.

[[v42-22-15]]

^<<v42-22-15,15>>^ And he said to them: “I have greatly desired to eat this Passover with you before I suffer;

[[v42-22-16]]

^<<v42-22-16,16>>^ for I tell you, I will not eat it again until it is fulfilled in the Kingdom of God.”

[[v42-22-17]]

^<<v42-22-17,17>>^ And accepting a cup, he gave thanks and said: “Take this and pass it from one to the other among yourselves,

[[v42-22-18]]

^<<v42-22-18,18>>^ for I tell you, from now on, I will not drink again from the product of the vine until the Kingdom of God comes.”

[[v42-22-19]]

^<<v42-22-19,19>>^ Also, he took a loaf, gave thanks, broke it, and gave it to them, saying: “This means my body, which is to be given in your behalf. Keep doing this in remembrance of me.”

[[v42-22-20]]

^<<v42-22-20,20>>^ Also, he did the same with the cup after they had the evening meal, saying: “This cup means the new covenant by virtue of my blood, which is to be poured out in your behalf.

[[v42-22-21]]

^<<v42-22-21,21>>^ “But look! the hand of my betrayer is with me at the table.

[[v42-22-22]]

^<<v42-22-22,22>>^ For, indeed, the Son of man is going his way according to what has been determined; all the same, woe to that man through whom he is betrayed!”

[[v42-22-23]]

^<<v42-22-23,23>>^ So they began to discuss among themselves which one of them could really be about to do this.

[[v42-22-24]]

^<<v42-22-24,24>>^ However, there also arose a heated dispute among them over which one of them was considered to be the greatest.

[[v42-22-25]]

^<<v42-22-25,25>>^ But he said to them: “The kings of the nations lord it over them, and those having authority over them are called Benefactors.

[[v42-22-26]]

^<<v42-22-26,26>>^ You, though, are not to be that way. But let the one who is the greatest among you become as the youngest, and the one taking the lead as the one ministering.

[[v42-22-27]]

^<<v42-22-27,27>>^ For which one is greater, the one dining^&#42;1^ or the one serving?^&#42;2^ Is it not the one dining?^&#42;3^ But I am among you as the one serving.^&#42;4^

[NOTE]
====
. Or “reclining at the table.”
. Or “ministering.”
. Or “reclining at the table.”
. Or “ministering.”
====

[[v42-22-28]]

^<<v42-22-28,28>>^ “However, you are the ones who have stuck with me in my trials;

[[v42-22-29]]

^<<v42-22-29,29>>^ and I make a covenant with you, just as my Father has made a covenant with me, for a kingdom,

[[v42-22-30]]

^<<v42-22-30,30>>^ so that you may eat and drink at my table in my Kingdom, and sit on thrones to judge the 12 tribes of Israel.

[[v42-22-31]]

^<<v42-22-31,31>>^ “Simon, Simon, look! Satan has demanded to have all of you to sift you as wheat.

[[v42-22-32]]

^<<v42-22-32,32>>^ But I have made supplication for you that your faith may not give out; and you, once you have returned, strengthen your brothers.”

[[v42-22-33]]

^<<v42-22-33,33>>^ Then he said to him: “Lord, I am ready to go with you both to prison and to death.”

[[v42-22-34]]

^<<v42-22-34,34>>^ But he said: “I tell you, Peter, a rooster will not crow today until you have denied knowing me three times.”

[[v42-22-35]]

^<<v42-22-35,35>>^ He also said to them: “When I sent you out without a money bag and a food pouch and sandals, you did not lack anything, did you?” They said: “No!”

[[v42-22-36]]

^<<v42-22-36,36>>^ Then he said to them: “But now let the one who has a money bag take it, likewise a food pouch, and let the one who has no sword sell his outer garment and buy one.

[[v42-22-37]]

^<<v42-22-37,37>>^ For I tell you that what is written must be accomplished in me, namely, ‘He was counted with lawless ones.’ For this is being fulfilled concerning me.”

[[v42-22-38]]

^<<v42-22-38,38>>^ Then they said: “Lord, look! here are two swords.” He said to them: “It is enough.”

[[v42-22-39]]

^<<v42-22-39,39>>^ On leaving, he went as was his custom to the Mount of Olives, and the disciples also followed him.

[[v42-22-40]]

^<<v42-22-40,40>>^ On arriving at the place, he said to them: “Carry on prayer so that you do not enter into temptation.”

[[v42-22-41]]

^<<v42-22-41,41>>^ And he withdrew from them about a stone’s throw away, and he bent his knees and began to pray,

[[v42-22-42]]

^<<v42-22-42,42>>^ saying: “Father, if you want to, remove this cup from me. Nevertheless, let, not my will, but yours take place.”

[[v42-22-43]]

^<<v42-22-43,43>>^ Then an angel from heaven appeared to him and strengthened him.

[[v42-22-44]]

^<<v42-22-44,44>>^ But he was in such agony that he kept praying more earnestly; and his sweat became as drops of blood falling to the ground.

[[v42-22-45]]

^<<v42-22-45,45>>^ When he rose from prayer and went to the disciples, he found them slumbering, exhausted from grief.

[[v42-22-46]]

^<<v42-22-46,46>>^ He said to them: “Why are you sleeping? Get up and keep praying, so that you do not enter into temptation.”

[[v42-22-47]]

^<<v42-22-47,47>>^ While he was still speaking, look! a crowd, and the man called Judas, one of the Twelve, was leading them, and he approached Jesus to kiss him.

[[v42-22-48]]

^<<v42-22-48,48>>^ But Jesus said to him: “Judas, are you betraying the Son of man with a kiss?”

[[v42-22-49]]

^<<v42-22-49,49>>^ When those around him saw what was going to happen, they said: “Lord, should we strike with the sword?”

[[v42-22-50]]

^<<v42-22-50,50>>^ One of them even struck the slave of the high priest, taking off his right ear.

[[v42-22-51]]

^<<v42-22-51,51>>^ But in reply Jesus said: “That is enough.” And he touched the ear and healed him.

[[v42-22-52]]

^<<v42-22-52,52>>^ Jesus then said to the chief priests and captains of the temple and elders who had come there for him: “Did you come out with swords and clubs as against a robber?

[[v42-22-53]]

^<<v42-22-53,53>>^ While I was with you in the temple day after day, you did not lay your hands on me. But this is your hour and the authority of darkness.”

[[v42-22-54]]

^<<v42-22-54,54>>^ Then they arrested him and led him off, and they brought him into the house of the high priest; but Peter was following at a distance.

[[v42-22-55]]

^<<v42-22-55,55>>^ When they lit a fire in the middle of the courtyard and sat down together, Peter was sitting among them.

[[v42-22-56]]

^<<v42-22-56,56>>^ But a servant girl, seeing him sitting in the light of the fire, looked closely at him and said: “This man was also with him.”

[[v42-22-57]]

^<<v42-22-57,57>>^ But he denied it, saying: “I do not know him, woman.”

[[v42-22-58]]

^<<v42-22-58,58>>^ After a short time another person saw him and said: “You too are one of them.” But Peter said: “Man, I am not.”

[[v42-22-59]]

^<<v42-22-59,59>>^ And after about an hour had passed, another man began insisting strongly: “Certainly this man was also with him, for he is, in fact, a Gal·i·leʹan!”

[[v42-22-60]]

^<<v42-22-60,60>>^ But Peter said: “Man, I do not know what you are saying.” And instantly, while he was still speaking, a rooster crowed.

[[v42-22-61]]

^<<v42-22-61,61>>^ At this the Lord turned and looked straight at Peter, and Peter recalled the statement of the Lord when he had said to him: “Before a rooster crows today, you will disown me three times.”

[[v42-22-62]]

^<<v42-22-62,62>>^ And he went outside and wept bitterly.

[[v42-22-63]]

^<<v42-22-63,63>>^ Now the men who held Jesus in custody began to mock him, hitting him;

[[v42-22-64]]

^<<v42-22-64,64>>^ and after covering his face, they kept asking: “Prophesy! Who is it that struck you?”

[[v42-22-65]]

^<<v42-22-65,65>>^ And they said many other blasphemous things against him.

[[v42-22-66]]

^<<v42-22-66,66>>^ And when it became day, the assembly of elders of the people, both chief priests and scribes, gathered together, and they led him into their Sanʹhe·drin hall and said:

[[v42-22-67]]

^<<v42-22-67,67>>^ “If you are the Christ, tell us.” But he said to them: “Even if I told you, you would not believe it at all.

[[v42-22-68]]

^<<v42-22-68,68>>^ Moreover, if I questioned you, you would not answer.

[[v42-22-69]]

^<<v42-22-69,69>>^ However, from now on the Son of man will be seated at the powerful right hand of God.”

[[v42-22-70]]

^<<v42-22-70,70>>^ At this they all said: “Are you, therefore, the Son of God?” He said to them: “You yourselves are saying that I am.”

[[v42-22-71]]

^<<v42-22-71,71>>^ They said: “Why do we need further testimony? For we ourselves have heard it out of his own mouth.”

'''

xref:042-luke/042-luke-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-luke/042-luke-023.adoc#v42-23-0[Próximo Capítulo &#62;]