include::./index.adoc[]

[[v42-6-0]]
=== According to Luke, 6
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-6-1]]

^<<v42-6-1,1>>^ Now on a sabbath he was passing through grainfields, and his disciples were plucking and eating the heads of grain, rubbing them with their hands.

[[v42-6-2]]

^<<v42-6-2,2>>^ At this some of the Pharisees said: “Why are you doing what is not lawful on the Sabbath?”

[[v42-6-3]]

^<<v42-6-3,3>>^ But in reply Jesus said to them: “Have you never read what David did when he and the men with him were hungry?

[[v42-6-4]]

^<<v42-6-4,4>>^ How he entered into the house of God and received the loaves of presentation^&#42;1^ and ate and gave some to the men with him, which it is not lawful for anyone to eat but for the priests only?”

[NOTE]
====
. Or “the showbread.”
====

[[v42-6-5]]

^<<v42-6-5,5>>^ Then he said to them: “The Son of man is Lord of the Sabbath.”

[[v42-6-6]]

^<<v42-6-6,6>>^ On another sabbath he entered the synagogue and began teaching. And a man was there whose right hand was withered.^&#42;1^

[NOTE]
====
. Or “paralyzed.”
====

[[v42-6-7]]

^<<v42-6-7,7>>^ The scribes and the Pharisees were now watching Jesus closely to see whether he would cure on the Sabbath, in order to find some way to accuse him.

[[v42-6-8]]

^<<v42-6-8,8>>^ He, however, knew their reasoning, so he said to the man with the withered^&#42;1^ hand: “Get up and stand in the center.” And he rose and stood there.

[NOTE]
====
. Or “paralyzed.”
====

[[v42-6-9]]

^<<v42-6-9,9>>^ Then Jesus said to them: “I ask you men, Is it lawful on the Sabbath to do good or to do harm, to save a life^&#42;1^ or to destroy it?”

[NOTE]
====
. Or “soul.”
====

[[v42-6-10]]

^<<v42-6-10,10>>^ After looking around at them all, he said to the man: “Stretch out your hand.” He did so, and his hand was restored.

[[v42-6-11]]

^<<v42-6-11,11>>^ But they flew into a senseless rage, and they began to talk over with one another what they might do to Jesus.

[[v42-6-12]]

^<<v42-6-12,12>>^ On one of those days he went out to the mountain to pray, and he spent the whole night in prayer to God.

[[v42-6-13]]

^<<v42-6-13,13>>^ And when it became day, he called his disciples to him and chose from among them 12, whom he also named apostles:

[[v42-6-14]]

^<<v42-6-14,14>>^ Simon, whom he also named Peter, Andrew his brother, James, John, Philip, Bar·tholʹo·mew,

[[v42-6-15]]

^<<v42-6-15,15>>^ Matthew, Thomas, James the son of Al·phaeʹus, Simon who is called “the zealous one,”

[[v42-6-16]]

^<<v42-6-16,16>>^ Judas the son of James, and Judas Is·carʹi·ot, who turned traitor.

[[v42-6-17]]

^<<v42-6-17,17>>^ And he came down with them and stood on a level place, and there was a large crowd of his disciples, and a great multitude of people from all Ju·deʹa and Jerusalem and the coastal region of Tyre and Siʹdon, who came to hear him and to be healed of their sicknesses.

[[v42-6-18]]

^<<v42-6-18,18>>^ Even those troubled with unclean spirits were cured.

[[v42-6-19]]

^<<v42-6-19,19>>^ And all the crowd were seeking to touch him, because power was going out of him and healing them all.

[[v42-6-20]]

^<<v42-6-20,20>>^ And he looked up at his disciples and began to say:
“Happy are you who are poor, for yours is the Kingdom of God.

[[v42-6-21]]

^<<v42-6-21,21>>^ “Happy are you who hunger now, for you will be filled.
“Happy are you who weep now, for you will laugh.

[[v42-6-22]]

^<<v42-6-22,22>>^ “Happy are you whenever men hate you, and when they exclude you and reproach you and denounce^&#42;1^ your name as wicked for the sake of the Son of man.

[NOTE]
====
. Or “cast out.”
====

[[v42-6-23]]

^<<v42-6-23,23>>^ Rejoice in that day and leap for joy, for look! your reward is great in heaven, for those are the same things their forefathers used to do to the prophets.

[[v42-6-24]]

^<<v42-6-24,24>>^ “But woe to you who are rich, for you are having your consolation in full.

[[v42-6-25]]

^<<v42-6-25,25>>^ “Woe to you who are filled up now, for you will go hungry.
“Woe, you who are laughing now, for you will mourn and weep.

[[v42-6-26]]

^<<v42-6-26,26>>^ “Woe whenever all men speak well of you, for this is what their forefathers did to the false prophets.

[[v42-6-27]]

^<<v42-6-27,27>>^ “But I say to you who are listening: Continue to love your enemies, to do good to those hating you,

[[v42-6-28]]

^<<v42-6-28,28>>^ to bless those cursing you, to pray for those who are insulting you.

[[v42-6-29]]

^<<v42-6-29,29>>^ To him who strikes you on the one cheek, offer the other also; and from him who takes away your outer garment, do not withhold the inner garment either.

[[v42-6-30]]

^<<v42-6-30,30>>^ Give to everyone asking you, and from the one taking your things away, do not ask them back.

[[v42-6-31]]

^<<v42-6-31,31>>^ “Also, just as you want men to do to you, do the same way to them.

[[v42-6-32]]

^<<v42-6-32,32>>^ “If you love those loving you, of what credit is it to you? For even the sinners love those loving them.

[[v42-6-33]]

^<<v42-6-33,33>>^ And if you do good to those doing good to you, of what credit is it to you? Even the sinners do the same.

[[v42-6-34]]

^<<v42-6-34,34>>^ Also, if you lend^&#42;1^ to those from whom you expect repayment, of what credit is it to you? Even sinners lend to sinners so that they may get back as much.

[NOTE]
====
. That is, without interest.
====

[[v42-6-35]]

^<<v42-6-35,35>>^ On the contrary, continue to love your enemies and to do good and to lend without hoping for anything back; and your reward will be great, and you will be sons of the Most High, for he is kind toward the unthankful and wicked.

[[v42-6-36]]

^<<v42-6-36,36>>^ Continue being merciful, just as your Father is merciful.

[[v42-6-37]]

^<<v42-6-37,37>>^ “Moreover, stop judging, and you will by no means be judged; and stop condemning, and you will by no means be condemned. Keep on forgiving,^&#42;1^ and you will be forgiven.^&#42;2^

[NOTE]
====
. Or “releasing.”
. Or “released.”
====

[[v42-6-38]]

^<<v42-6-38,38>>^ Practice giving, and people will give to you. They will pour into your laps a fine measure, pressed down, shaken together, and overflowing. For with the measure that you are measuring out, they will measure out to you in return.”

[[v42-6-39]]

^<<v42-6-39,39>>^ Then he also told them an illustration: “A blind man cannot guide a blind man, can he? Both will fall into a pit, will they not?

[[v42-6-40]]

^<<v42-6-40,40>>^ A student^&#42;1^ is not above his teacher, but everyone who is perfectly instructed will be like his teacher.

[NOTE]
====
. Or “disciple.”
====

[[v42-6-41]]

^<<v42-6-41,41>>^ Why, then, do you look at the straw in your brother’s eye but do not notice the rafter in your own eye?

[[v42-6-42]]

^<<v42-6-42,42>>^ How can you say to your brother, ‘Brother, allow me to remove the straw that is in your eye,’ while you yourself do not see the rafter in your own eye? Hypocrite! First remove the rafter from your own eye, and then you will see clearly how to remove the straw that is in your brother’s eye.

[[v42-6-43]]

^<<v42-6-43,43>>^ “For no fine tree produces rotten fruit, and no rotten tree produces fine fruit.

[[v42-6-44]]

^<<v42-6-44,44>>^ For each tree is known by its own fruit. For example, people do not gather figs from thorns, nor do they cut grapes off a thornbush.

[[v42-6-45]]

^<<v42-6-45,45>>^ A good man brings good out of the good treasure of his heart, but a wicked man brings what is wicked out of his wicked treasure; for out of the heart’s abundance his mouth speaks.

[[v42-6-46]]

^<<v42-6-46,46>>^ “Why, then, do you call me ‘Lord! Lord!’ but do not do the things I say?

[[v42-6-47]]

^<<v42-6-47,47>>^ Everyone who comes to me and hears my words and does them, I will show you whom he is like:

[[v42-6-48]]

^<<v42-6-48,48>>^ He is like a man who in building a house dug and went down deep and laid a foundation on the rock. Consequently, when a flood came, the river dashed against that house but was not strong enough to shake it, for it was well-built.

[[v42-6-49]]

^<<v42-6-49,49>>^ On the other hand, whoever hears and does nothing is like a man who built a house on the ground without a foundation. The river dashed against it, and immediately it collapsed, and the ruin of that house was great.”

'''

xref:042-luke/042-luke-005.adoc#v42-5-0[&#60; Capítulo Anterior] | <<v42-6-0,Topo>> | xref:042-luke/042-luke-007.adoc#v42-7-0[Próximo Capítulo &#62;]