include::./index.adoc[]

[[v42-18-0]]
=== According to Luke, 18
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-18-1]]

^<<v42-18-1,1>>^ Then he went on to tell them an illustration about the need for them always to pray and not to give up,

[[v42-18-2]]

^<<v42-18-2,2>>^ saying: “In a certain city there was a judge who had no fear of God and no respect for man.

[[v42-18-3]]

^<<v42-18-3,3>>^ There was also a widow in that city who kept going to him and saying, ‘See that I get justice from my legal opponent.’

[[v42-18-4]]

^<<v42-18-4,4>>^ Well, for a while he was unwilling, but afterward he said to himself, ‘Although I do not fear God or respect any man,

[[v42-18-5]]

^<<v42-18-5,5>>^ because this widow keeps making me trouble, I will see that she gets justice so that she will not keep coming and wearing me out with her demand.’”^&#42;1^

[NOTE]
====
. Or “and pummeling me to a finish.”
====

[[v42-18-6]]

^<<v42-18-6,6>>^ Then the Lord said: “Hear what the judge, although unrighteous, said!

[[v42-18-7]]

^<<v42-18-7,7>>^ Certainly, then, will not God cause justice to be done for his chosen ones who cry out to him day and night, while he is patient toward them?

[[v42-18-8]]

^<<v42-18-8,8>>^ I tell you, he will cause justice to be done to them speedily. Nevertheless, when the Son of man arrives, will he really find this faith^&#42;1^ on the earth?”

[NOTE]
====
. Or “this kind of faith.” Lit., “the faith.”
====

[[v42-18-9]]

^<<v42-18-9,9>>^ He also told this illustration to some who trusted in their own righteousness and who considered others as nothing:

[[v42-18-10]]

^<<v42-18-10,10>>^ “Two men went up into the temple to pray, the one a Pharisee and the other a tax collector.

[[v42-18-11]]

^<<v42-18-11,11>>^ The Pharisee stood and began to pray these things to himself, ‘O God, I thank you that I am not like everyone else—extortioners, unrighteous, adulterers—or even like this tax collector.

[[v42-18-12]]

^<<v42-18-12,12>>^ I fast twice a week; I give the tenth of all things I acquire.’

[[v42-18-13]]

^<<v42-18-13,13>>^ But the tax collector, standing at a distance, was not willing even to raise his eyes heavenward but kept beating his chest, saying, ‘O God, be gracious to me,^&#42;1^ a sinner.’

[NOTE]
====
. Or “have mercy on me.”
====

[[v42-18-14]]

^<<v42-18-14,14>>^ I tell you, this man went down to his home and was proved more righteous than that Pharisee. Because everyone who exalts himself will be humiliated, but whoever humbles himself will be exalted.”

[[v42-18-15]]

^<<v42-18-15,15>>^ Now people were also bringing him their infants for him to touch them, but on seeing this, the disciples began to reprimand them.

[[v42-18-16]]

^<<v42-18-16,16>>^ However, Jesus called the infants to him, saying: “Let the young children come to me, and do not try to stop them, for the Kingdom of God belongs to such ones.

[[v42-18-17]]

^<<v42-18-17,17>>^ Truly I say to you, whoever does not receive the Kingdom of God like a young child will by no means enter into it.”

[[v42-18-18]]

^<<v42-18-18,18>>^ And one of the rulers questioned him, saying: “Good Teacher, what must I do to inherit everlasting life?”

[[v42-18-19]]

^<<v42-18-19,19>>^ Jesus said to him: “Why do you call me good? Nobody is good except one, God.

[[v42-18-20]]

^<<v42-18-20,20>>^ You know the commandments: ‘Do not commit adultery, do not murder, do not steal, do not bear false witness, honor your father and your mother.’”

[[v42-18-21]]

^<<v42-18-21,21>>^ Then he said: “All of these I have kept from youth on.”

[[v42-18-22]]

^<<v42-18-22,22>>^ After hearing that, Jesus said to him, “There is still one thing lacking about you: Sell all the things you have and distribute the proceeds to the poor, and you will have treasure in the heavens; and come be my follower.”

[[v42-18-23]]

^<<v42-18-23,23>>^ When he heard this, he became deeply grieved, for he was very rich.

[[v42-18-24]]

^<<v42-18-24,24>>^ Jesus looked at him and said: “How difficult it will be for those having money to make their way into the Kingdom of God!

[[v42-18-25]]

^<<v42-18-25,25>>^ It is easier, in fact, for a camel to get through the eye of a sewing needle than for a rich man to enter the Kingdom of God.”

[[v42-18-26]]

^<<v42-18-26,26>>^ Those who heard this said: “Who possibly can be saved?”

[[v42-18-27]]

^<<v42-18-27,27>>^ He said: “The things impossible with men are possible with God.”

[[v42-18-28]]

^<<v42-18-28,28>>^ But Peter said: “Look! We have left what was ours and followed you.”

[[v42-18-29]]

^<<v42-18-29,29>>^ He said to them: “Truly I say to you, there is no one who has left house or wife or brothers or parents or children for the sake of the Kingdom of God

[[v42-18-30]]

^<<v42-18-30,30>>^ who will not get many times more in this period of time, and in the coming system of things,^&#42;1^ everlasting life.”

[NOTE]
====
. Or “the coming age.” See Glossary.
====

[[v42-18-31]]

^<<v42-18-31,31>>^ Then he took the Twelve aside and said to them: “Look! We are going up to Jerusalem, and all the things written by means of the prophets about the Son of man will be accomplished.^&#42;1^

[NOTE]
====
. Or “completed.”
====

[[v42-18-32]]

^<<v42-18-32,32>>^ For instance, he will be handed over to men of the nations and will be mocked and treated insolently and spat on.

[[v42-18-33]]

^<<v42-18-33,33>>^ And after scourging him, they will kill him, but on the third day he will rise.”

[[v42-18-34]]

^<<v42-18-34,34>>^ However, they did not get the meaning of any of these things, for these words were hidden from them, and they did not understand the things said.

[[v42-18-35]]

^<<v42-18-35,35>>^ Now as Jesus was getting near to Jerʹi·cho, a blind man was sitting beside the road begging.

[[v42-18-36]]

^<<v42-18-36,36>>^ Because he heard a crowd passing by, he began to inquire what was going on.

[[v42-18-37]]

^<<v42-18-37,37>>^ They reported to him: “Jesus the Naz·a·reneʹ is passing by!”

[[v42-18-38]]

^<<v42-18-38,38>>^ At that he cried out: “Jesus, Son of David, have mercy on me!”

[[v42-18-39]]

^<<v42-18-39,39>>^ And those who were in front began rebuking him, telling him to keep quiet, but all the more he kept shouting: “Son of David, have mercy on me!”

[[v42-18-40]]

^<<v42-18-40,40>>^ Then Jesus stopped and commanded that the man be brought to him. After he came near, Jesus asked him:

[[v42-18-41]]

^<<v42-18-41,41>>^ “What do you want me to do for you?” He said: “Lord, let me recover my sight.”

[[v42-18-42]]

^<<v42-18-42,42>>^ So Jesus said to him: “Recover your sight; your faith has made you well.”

[[v42-18-43]]

^<<v42-18-43,43>>^ And instantly he recovered his sight, and he began to follow him, glorifying God. Also, at seeing it, all the people gave praise to God.

'''

xref:042-luke/042-luke-017.adoc#v42-17-0[&#60; Capítulo Anterior] | <<v42-18-0,Topo>> | xref:042-luke/042-luke-019.adoc#v42-19-0[Próximo Capítulo &#62;]