include::./index.adoc[]

[[v42-14-0]]
=== According to Luke, 14
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-14-1]]

^<<v42-14-1,1>>^ On another occasion he went to eat a meal in the house of one of the leaders of the Pharisees on the Sabbath, and they were closely watching him.

[[v42-14-2]]

^<<v42-14-2,2>>^ And look! a man who had dropsy^&#42;1^ was in front of him.

[NOTE]
====
. Or “edema,” an excess buildup of fluid in the body.
====

[[v42-14-3]]

^<<v42-14-3,3>>^ So in response Jesus asked those versed in the Law and the Pharisees: “Is it lawful to cure on the Sabbath or not?”

[[v42-14-4]]

^<<v42-14-4,4>>^ But they kept silent. With that he took hold of the man, healed him, and sent him away.

[[v42-14-5]]

^<<v42-14-5,5>>^ Then he said to them: “Who of you, if his son or bull falls into a well, will not immediately pull him out on the Sabbath day?”

[[v42-14-6]]

^<<v42-14-6,6>>^ And they were not able to reply to this.

[[v42-14-7]]

^<<v42-14-7,7>>^ He then told the invited men an illustration when he noticed how they were choosing the most prominent places for themselves. He said to them:

[[v42-14-8]]

^<<v42-14-8,8>>^ “When you are invited by someone to a marriage feast, do not recline in the most prominent place. Perhaps someone more distinguished than you may also have been invited.

[[v42-14-9]]

^<<v42-14-9,9>>^ Then the one who invited you both will come and say to you, ‘Let this man have your place.’ Then you will proceed with shame to take the lowest place.

[[v42-14-10]]

^<<v42-14-10,10>>^ But when you are invited, go and recline in the lowest place, so that when the man who invited you comes, he will say to you, ‘Friend, go on up higher.’ Then you will have honor in front of all your fellow guests.

[[v42-14-11]]

^<<v42-14-11,11>>^ For everyone who exalts himself will be humbled, and whoever humbles himself will be exalted.”

[[v42-14-12]]

^<<v42-14-12,12>>^ Next he said also to the man who had invited him: “When you spread a dinner or an evening meal, do not call your friends or your brothers or your relatives or your rich neighbors. Otherwise, they might also invite you in return, and it would become a repayment to you.

[[v42-14-13]]

^<<v42-14-13,13>>^ But when you spread a feast, invite the poor, the crippled, the lame, the blind;

[[v42-14-14]]

^<<v42-14-14,14>>^ and you will be happy, because they have nothing with which to repay you. For you will be repaid in the resurrection of the righteous ones.”

[[v42-14-15]]

^<<v42-14-15,15>>^ On hearing these things, one of the fellow guests said to him: “Happy is the one who dines^&#42;1^ in the Kingdom of God.”

[NOTE]
====
. Lit., “eats bread.”
====

[[v42-14-16]]

^<<v42-14-16,16>>^ Jesus said to him: “A man was spreading a grand evening meal, and he invited many.

[[v42-14-17]]

^<<v42-14-17,17>>^ He sent his slave out at the hour of the evening meal to say to the invited ones, ‘Come, because everything is now ready.’

[[v42-14-18]]

^<<v42-14-18,18>>^ But they all alike began to make excuses. The first said to him, ‘I bought a field and need to go out and see it; I ask you, have me excused.’

[[v42-14-19]]

^<<v42-14-19,19>>^ And another said, ‘I bought five yoke^&#42;1^ of cattle and am going to examine them; I ask you, have me excused.’

[NOTE]
====
. Or “pairs.”
====

[[v42-14-20]]

^<<v42-14-20,20>>^ Still another said, ‘I just got married, and for this reason I cannot come.’

[[v42-14-21]]

^<<v42-14-21,21>>^ So the slave came and reported these things to his master. Then the master of the house became angry and said to his slave, ‘Go out quickly to the main streets and the alleys of the city, and bring in here the poor and crippled and blind and lame.’

[[v42-14-22]]

^<<v42-14-22,22>>^ In time the slave said, ‘Master, what you ordered has been done, and still there is room.’

[[v42-14-23]]

^<<v42-14-23,23>>^ So the master said to the slave, ‘Go out to the roads and the lanes and compel them to come in, so that my house may be filled.

[[v42-14-24]]

^<<v42-14-24,24>>^ For I say to you, none of those men who were invited will taste my evening meal.’”

[[v42-14-25]]

^<<v42-14-25,25>>^ Now large crowds were traveling with him, and he turned and said to them:

[[v42-14-26]]

^<<v42-14-26,26>>^ “If anyone comes to me and does not hate^&#42;1^ his father and mother and wife and children and brothers and sisters, yes, and even his own life,^&#42;2^ he cannot be my disciple.

[NOTE]
====
. Or “love to a lesser degree.”
. Or “soul.”
====

[[v42-14-27]]

^<<v42-14-27,27>>^ Whoever does not carry his torture stake^&#42;1^ and come after me cannot be my disciple.

[NOTE]
====
. See Glossary.
====

[[v42-14-28]]

^<<v42-14-28,28>>^ For example, who of you wanting to build a tower does not first sit down and calculate the expense to see if he has enough to complete it?

[[v42-14-29]]

^<<v42-14-29,29>>^ Otherwise, he might lay its foundation but not be able to finish it, and all the onlookers would start to ridicule him,

[[v42-14-30]]

^<<v42-14-30,30>>^ saying: ‘This man started to build but was not able to finish.’

[[v42-14-31]]

^<<v42-14-31,31>>^ Or what king marching out against another king in war does not first sit down and take counsel whether he is able with 10,000 troops to stand up to the one who comes against him with 20,000?

[[v42-14-32]]

^<<v42-14-32,32>>^ If, in fact, he cannot do so, then while that one is yet far away, he sends out a body of ambassadors and sues for peace.

[[v42-14-33]]

^<<v42-14-33,33>>^ In the same way, you may be sure that not one of you who does not say good-bye to^&#42;1^ all his belongings can be my disciple.

[NOTE]
====
. Or “give up.”
====

[[v42-14-34]]

^<<v42-14-34,34>>^ “Salt, to be sure, is fine. But if the salt loses its strength, with what will it be seasoned?

[[v42-14-35]]

^<<v42-14-35,35>>^ It is not suitable for soil or for manure. People throw it away. Let the one who has ears to listen, listen.”

'''

xref:042-luke/042-luke-013.adoc#v42-13-0[&#60; Capítulo Anterior] | <<v42-14-0,Topo>> | xref:042-luke/042-luke-015.adoc#v42-15-0[Próximo Capítulo &#62;]