include::./index.adoc[]

[[v42-3-0]]
=== According to Luke, 3
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-3-1]]

^<<v42-3-1,1>>^ In the 15th year of the reign of Ti·beʹri·us Caesar, when Pontius Pilate was governor of Ju·deʹa, Herod^&#42;1^ was district ruler^&#42;2^ of Galʹi·lee, Philip his brother was district ruler of the country of It·u·raeʹa and Trach·o·niʹtis, and Ly·saʹni·as was district ruler of Ab·i·leʹne,

[NOTE]
====
. That is, Herod Antipas. See Glossary.
. Lit., “the tetrarch.”
====

[[v42-3-2]]

^<<v42-3-2,2>>^ in the days of chief priest Anʹnas and of Caʹia·phas, God’s declaration came to John the son of Zech·a·riʹah in the wilderness.

[[v42-3-3]]

^<<v42-3-3,3>>^ So he went into all the country around the Jordan, preaching baptism in symbol of repentance for forgiveness of sins,

[[v42-3-4]]

^<<v42-3-4,4>>^ just as it is written in the book of the words of Isaiah the prophet: “A voice of one crying out in the wilderness: ‘Prepare the way of Jehovah!^&#42;1^ Make his roads straight.

[NOTE]
====
. See App. A5.
====

[[v42-3-5]]

^<<v42-3-5,5>>^ Every valley must be filled up, and every mountain and hill leveled; the crooked ways must become straight, and the rough ways smooth;

[[v42-3-6]]

^<<v42-3-6,6>>^ and all flesh^&#42;1^ will see the salvation of God.’”^&#42;2^

[NOTE]
====
. Or “all humans.”
. Or “the saving means of God.”
====

[[v42-3-7]]

^<<v42-3-7,7>>^ So he began to say to the crowds coming out to be baptized by him: “You offspring of vipers, who has warned you to flee from the coming wrath?

[[v42-3-8]]

^<<v42-3-8,8>>^ Therefore, produce fruits that befit repentance. Do not start saying to yourselves, ‘We have Abraham as our father.’ For I say to you that God is able to raise up children for Abraham from these stones.

[[v42-3-9]]

^<<v42-3-9,9>>^ Indeed, the ax is already lying at the root of the trees. Every tree, then, that does not produce fine fruit will be cut down and thrown into the fire.”

[[v42-3-10]]

^<<v42-3-10,10>>^ And the crowds were asking him: “What, then, should we do?”

[[v42-3-11]]

^<<v42-3-11,11>>^ In reply he said to them: “Let the man who has two garments^&#42;1^ share with the man who has none, and let the one who has something to eat do the same.”

[NOTE]
====
. Or “an extra garment.”
====

[[v42-3-12]]

^<<v42-3-12,12>>^ Even tax collectors came to be baptized, and they said to him: “Teacher, what should we do?”

[[v42-3-13]]

^<<v42-3-13,13>>^ He said to them: “Do not demand^&#42;1^ anything more than the tax rate.”

[NOTE]
====
. Or “collect.”
====

[[v42-3-14]]

^<<v42-3-14,14>>^ Also, those in military service were asking him: “What should we do?” And he said to them: “Do not harass^&#42;1^ anybody or accuse anybody falsely, but be satisfied with your provisions.”^&#42;2^

[NOTE]
====
. Or “extort from.”
. Or “wages.”
====

[[v42-3-15]]

^<<v42-3-15,15>>^ Now the people were in expectation and all of them were reasoning in their hearts about John, “May he perhaps be the Christ?”

[[v42-3-16]]

^<<v42-3-16,16>>^ John gave the answer, saying to all: “I, for my part, baptize you with water, but the one stronger than I am is coming, the lace of whose sandals I am not worthy to untie. He will baptize you with holy spirit and with fire.

[[v42-3-17]]

^<<v42-3-17,17>>^ His winnowing shovel is in his hand to clean up his threshing floor completely and to gather the wheat into his storehouse, but the chaff he will burn up with fire that cannot be put out.”

[[v42-3-18]]

^<<v42-3-18,18>>^ He also gave many other exhortations and continued declaring good news to the people.

[[v42-3-19]]

^<<v42-3-19,19>>^ But Herod the district ruler, because of being reproved by John concerning He·roʹdi·as the wife of his brother and concerning all the wicked deeds that Herod had done,

[[v42-3-20]]

^<<v42-3-20,20>>^ added this also to all those deeds: He locked John up in prison.

[[v42-3-21]]

^<<v42-3-21,21>>^ Now when all the people were baptized, Jesus too was baptized. As he was praying, the heaven was opened up,

[[v42-3-22]]

^<<v42-3-22,22>>^ and the holy spirit in bodily form like a dove came down upon him, and a voice came out of heaven: “You are my Son, the beloved; I have approved you.”

[[v42-3-23]]

^<<v42-3-23,23>>^ When Jesus began his work, he was about 30 years old, being the son, as the opinion was,
of Joseph,
son of Heʹli,

[[v42-3-24]]

^<<v42-3-24,24>>^ son of Matʹthat,
son of Leʹvi,
son of Melʹchi,
son of Janʹna·i,
son of Joseph,

[[v42-3-25]]

^<<v42-3-25,25>>^ son of Mat·ta·thiʹas,
son of Aʹmos,
son of Naʹhum,
son of Esʹli,
son of Nagʹga·i,

[[v42-3-26]]

^<<v42-3-26,26>>^ son of Maʹath,
son of Mat·ta·thiʹas,
son of Semʹe·in,
son of Joʹsech,
son of Joʹda,

[[v42-3-27]]

^<<v42-3-27,27>>^ son of Jo·anʹan,
son of Rheʹsa,
son of Ze·rubʹba·bel,
son of She·alʹti·el,
son of Neʹri,

[[v42-3-28]]

^<<v42-3-28,28>>^ son of Melʹchi,
son of Adʹdi,
son of Coʹsam,
son of El·maʹdam,
son of Er,

[[v42-3-29]]

^<<v42-3-29,29>>^ son of Jesus,
son of E·li·eʹzer,
son of Joʹrim,
son of Matʹthat,
son of Leʹvi,

[[v42-3-30]]

^<<v42-3-30,30>>^ son of Symʹe·on,
son of Judas,
son of Joseph,
son of Joʹnam,
son of E·liʹa·kim,

[[v42-3-31]]

^<<v42-3-31,31>>^ son of Meʹle·a,
son of Menʹna,
son of Matʹta·tha,
son of Nathan,
son of David,

[[v42-3-32]]

^<<v42-3-32,32>>^ son of Jesʹse,
son of Oʹbed,
son of Boʹaz,
son of Salʹmon,
son of Nahʹshon,

[[v42-3-33]]

^<<v42-3-33,33>>^ son of Am·minʹa·dab,
son of Arʹni,
son of Hezʹron,
son of Peʹrez,
son of Judah,

[[v42-3-34]]

^<<v42-3-34,34>>^ son of Jacob,
son of Isaac,
son of Abraham,
son of Teʹrah,
son of Naʹhor,

[[v42-3-35]]

^<<v42-3-35,35>>^ son of Seʹrug,
son of Reʹu,
son of Peʹleg,
son of Eʹber,
son of Sheʹlah,

[[v42-3-36]]

^<<v42-3-36,36>>^ son of Ca·iʹnan,
son of Ar·pachʹshad,
son of Shem,
son of Noah,
son of Laʹmech,

[[v42-3-37]]

^<<v42-3-37,37>>^ son of Me·thuʹse·lah,
son of Eʹnoch,
son of Jaʹred,
son of Ma·haʹla·le·el,
son of Ca·iʹnan,

[[v42-3-38]]

^<<v42-3-38,38>>^ son of Eʹnosh,
son of Seth,
son of Adam,
son of God.

'''

xref:042-luke/042-luke-002.adoc#v42-2-0[&#60; Capítulo Anterior] | <<v42-3-0,Topo>> | xref:042-luke/042-luke-004.adoc#v42-4-0[Próximo Capítulo &#62;]