include::./index.adoc[]

[[v42-16-0]]
=== According to Luke, 16
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-16-1]]

^<<v42-16-1,1>>^ Then he also said to the disciples: “A rich man had a steward^&#42;1^ who was accused of handling his goods wastefully.

[NOTE]
====
. Or “house manager.”
====

[[v42-16-2]]

^<<v42-16-2,2>>^ So he called him and said, ‘What is this I hear about you? Hand in the account of your stewardship, for you can no longer manage the house.’

[[v42-16-3]]

^<<v42-16-3,3>>^ Then the steward said to himself, ‘What am I to do, seeing that my master is taking the stewardship away from me? I am not strong enough to dig, and I am ashamed to beg.

[[v42-16-4]]

^<<v42-16-4,4>>^ Ah! I know what I will do, so that when I am removed from the stewardship, people will welcome me into their homes.’

[[v42-16-5]]

^<<v42-16-5,5>>^ And calling to him each one of his master’s debtors, he said to the first, ‘How much do you owe my master?’

[[v42-16-6]]

^<<v42-16-6,6>>^ He replied, ‘A hundred measures^&#42;1^ of olive oil.’ He said to him, ‘Take back your written agreement and sit down and quickly write 50.’

[NOTE]
====
. Or “bath measures.” A bath equaled 22 L (5.81 gal). See App. B14.
====

[[v42-16-7]]

^<<v42-16-7,7>>^ Next, he said to another one, ‘Now you, how much do you owe?’ He said, ‘A hundred large measures^&#42;1^ of wheat.’ He said to him, ‘Take back your written agreement and write 80.’

[NOTE]
====
. Or “A hundred cor measures.” A cor equaled 220 L (200 dry qt). See App. B14.
====

[[v42-16-8]]

^<<v42-16-8,8>>^ And his master commended the steward, though unrighteous, because he acted with practical wisdom;^&#42;1^ for the sons of this system of things^&#42;2^ are wiser in a practical way toward their own generation than the sons of the light are.

[NOTE]
====
. Or “acted shrewdly; acted discreetly.”
. Or “this age.” See Glossary.
====

[[v42-16-9]]

^<<v42-16-9,9>>^ “Also, I say to you: Make friends for yourselves by means of the unrighteous riches, so that when such fail, they may receive you into the everlasting dwelling places.

[[v42-16-10]]

^<<v42-16-10,10>>^ The person faithful in what is least is faithful also in much, and the person unrighteous in what is least is unrighteous also in much.

[[v42-16-11]]

^<<v42-16-11,11>>^ Therefore, if you have not proved yourselves faithful in connection with the unrighteous riches, who will entrust you with what is true?

[[v42-16-12]]

^<<v42-16-12,12>>^ And if you have not proved yourselves faithful in connection with what belongs to another, who will give you something for yourselves?

[[v42-16-13]]

^<<v42-16-13,13>>^ No servant can be a slave to two masters, for either he will hate the one and love the other, or he will stick to the one and despise the other. You cannot be slaves to God and to Riches.”

[[v42-16-14]]

^<<v42-16-14,14>>^ Now the Pharisees, who were money lovers, were listening to all these things, and they began to sneer at him.

[[v42-16-15]]

^<<v42-16-15,15>>^ So he said to them: “You are those who declare yourselves righteous before men, but God knows your hearts. For what is considered exalted by men is a disgusting thing in God’s sight.

[[v42-16-16]]

^<<v42-16-16,16>>^ “The Law and the Prophets were until John. From then on, the Kingdom of God is being declared as good news, and every sort of person is pressing forward toward it.

[[v42-16-17]]

^<<v42-16-17,17>>^ Indeed, it is easier for heaven and earth to pass away than for one stroke of a letter of the Law to go unfulfilled.

[[v42-16-18]]

^<<v42-16-18,18>>^ “Everyone who divorces his wife and marries another commits adultery, and whoever marries a woman divorced from her husband commits adultery.

[[v42-16-19]]

^<<v42-16-19,19>>^ “There was a rich man who used to dress in purple and linen, enjoying himself day after day with magnificence.

[[v42-16-20]]

^<<v42-16-20,20>>^ But a beggar named Lazʹa·rus used to be put at his gate, covered with ulcers

[[v42-16-21]]

^<<v42-16-21,21>>^ and desiring to be filled with the things dropping from the table of the rich man. Yes, even the dogs would come and lick his ulcers.

[[v42-16-22]]

^<<v42-16-22,22>>^ Now in the course of time, the beggar died and was carried off by the angels to Abraham’s side.^&#42;1^
“Also, the rich man died and was buried.

[NOTE]
====
. Lit., “to the bosom of Abraham.”
====

[[v42-16-23]]

^<<v42-16-23,23>>^ And in the Grave^&#42;1^ he lifted up his eyes, being in torment, and he saw Abraham from afar and Lazʹa·rus by his side.^&#42;2^

[NOTE]
====
. Or “Hades,” that is, the common grave of mankind. See Glossary.
. Lit., “in his bosom.”
====

[[v42-16-24]]

^<<v42-16-24,24>>^ So he called and said, ‘Father Abraham, have mercy on me, and send Lazʹa·rus to dip the tip of his finger in water and cool my tongue, for I am in anguish in this blazing fire.’

[[v42-16-25]]

^<<v42-16-25,25>>^ But Abraham said, ‘Child, remember that you had your fill of good things in your lifetime, but Lazʹa·rus for his part received bad things. Now, however, he is being comforted here, but you are in anguish.

[[v42-16-26]]

^<<v42-16-26,26>>^ And besides all these things, a great chasm has been fixed between us and you, so that those who want to go over from here to you cannot, neither may people cross over from there to us.’

[[v42-16-27]]

^<<v42-16-27,27>>^ Then he said, ‘That being so, I ask you, father, to send him to the house of my father,

[[v42-16-28]]

^<<v42-16-28,28>>^ for I have five brothers, in order that he may give them a thorough witness so that they will not also come into this place of torment.’

[[v42-16-29]]

^<<v42-16-29,29>>^ But Abraham said, ‘They have Moses and the Prophets; let them listen to these.’

[[v42-16-30]]

^<<v42-16-30,30>>^ Then he said, ‘No, indeed, father Abraham, but if someone from the dead goes to them, they will repent.’

[[v42-16-31]]

^<<v42-16-31,31>>^ But he said to him, ‘If they do not listen to Moses and the Prophets, neither will they be persuaded if someone rises from the dead.’”

'''

xref:042-luke/042-luke-015.adoc#v42-15-0[&#60; Capítulo Anterior] | <<v42-16-0,Topo>> | xref:042-luke/042-luke-017.adoc#v42-17-0[Próximo Capítulo &#62;]