include::./index.adoc[]

[[v42-20-0]]
=== According to Luke, 20
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-20-1]]

^<<v42-20-1,1>>^ On one of the days while he was teaching the people in the temple and declaring the good news, the chief priests and the scribes with the elders came

[[v42-20-2]]

^<<v42-20-2,2>>^ and said to him: “Tell us, by what authority do you do these things? Or who gave you this authority?”

[[v42-20-3]]

^<<v42-20-3,3>>^ He replied to them: “I will also ask you a question, and you tell me:

[[v42-20-4]]

^<<v42-20-4,4>>^ Was the baptism of John from heaven or from men?”^&#42;1^

[NOTE]
====
. Or “of human origin?”
====

[[v42-20-5]]

^<<v42-20-5,5>>^ Then they drew conclusions among themselves, saying: “If we say, ‘From heaven,’ he will say, ‘Why did you not believe him?’

[[v42-20-6]]

^<<v42-20-6,6>>^ But if we say, ‘From men,’ the people one and all will stone us, for they are convinced that John was a prophet.”

[[v42-20-7]]

^<<v42-20-7,7>>^ So they replied that they did not know its source.

[[v42-20-8]]

^<<v42-20-8,8>>^ Jesus said to them: “Neither am I telling you by what authority I do these things.”

[[v42-20-9]]

^<<v42-20-9,9>>^ Then he began to tell the people this illustration: “A man planted a vineyard and leased it to cultivators, and he traveled abroad for a considerable time.

[[v42-20-10]]

^<<v42-20-10,10>>^ In due season he sent a slave to the cultivators so that they would give him some of the fruit of the vineyard. The cultivators, however, sent him away empty-handed, after beating him.

[[v42-20-11]]

^<<v42-20-11,11>>^ But again he sent another slave. That one also they beat and humiliated^&#42;1^ and sent away empty-handed.

[NOTE]
====
. Or “dishonored.”
====

[[v42-20-12]]

^<<v42-20-12,12>>^ Yet again he sent a third; this one also they wounded and threw out.

[[v42-20-13]]

^<<v42-20-13,13>>^ At this the owner of the vineyard said, ‘What should I do? I will send my son, the beloved. They will likely respect this one.’

[[v42-20-14]]

^<<v42-20-14,14>>^ When the cultivators caught sight of him, they reasoned with one another, saying, ‘This is the heir. Let us kill him so that the inheritance may become ours.’

[[v42-20-15]]

^<<v42-20-15,15>>^ So they threw him out of the vineyard and killed him. What, then, will the owner of the vineyard do to them?

[[v42-20-16]]

^<<v42-20-16,16>>^ He will come and kill these cultivators and will give the vineyard to others.”
On hearing this, they said: “Never may that happen!”

[[v42-20-17]]

^<<v42-20-17,17>>^ But he looked straight at them and said: “What, then, does this mean where it is written: ‘The stone that the builders rejected, this has become the chief cornerstone’?^&#42;1^

[NOTE]
====
. Lit., “the head of the corner.”
====

[[v42-20-18]]

^<<v42-20-18,18>>^ Everyone falling on that stone will be shattered. As for anyone on whom it falls, it will crush him.”

[[v42-20-19]]

^<<v42-20-19,19>>^ The scribes and the chief priests then sought to get their hands on him in that very hour, but they feared the people, for they realized that he told this illustration with them in mind.

[[v42-20-20]]

^<<v42-20-20,20>>^ And after observing him closely, they sent men whom they had secretly hired to pretend that they were righteous in order to catch him in his speech, so as to turn him over to the government and to the authority of the governor.

[[v42-20-21]]

^<<v42-20-21,21>>^ And they questioned him, saying: “Teacher, we know you speak and teach correctly and show no partiality, but you teach the way of God in line with truth:

[[v42-20-22]]

^<<v42-20-22,22>>^ Is it lawful^&#42;1^ for us to pay taxes to Caesar or not?”

[NOTE]
====
. Or “right.”
====

[[v42-20-23]]

^<<v42-20-23,23>>^ But he detected their cunning and said to them:

[[v42-20-24]]

^<<v42-20-24,24>>^ “Show me a de·narʹi·us.^&#42;1^ Whose image and inscription does it have?” They said: “Caesar’s.”

[NOTE]
====
. See App. B14.
====

[[v42-20-25]]

^<<v42-20-25,25>>^ He said to them: “By all means, then, pay back Caesar’s things to Caesar but God’s things to God.”

[[v42-20-26]]

^<<v42-20-26,26>>^ Well, they were not able to trap him in his speech before the people, but amazed at his answer, they became silent.

[[v42-20-27]]

^<<v42-20-27,27>>^ However, some of the Sadducees, those who say there is no resurrection, came and asked him:

[[v42-20-28]]

^<<v42-20-28,28>>^ “Teacher, Moses wrote us, ‘If a man’s brother dies, leaving a wife, but he was childless, his brother should take the wife and raise up offspring for his brother.’

[[v42-20-29]]

^<<v42-20-29,29>>^ Now there were seven brothers. The first took a wife but died childless.

[[v42-20-30]]

^<<v42-20-30,30>>^ So the second

[[v42-20-31]]

^<<v42-20-31,31>>^ and the third married her. Likewise even all seven; they died and left no children.

[[v42-20-32]]

^<<v42-20-32,32>>^ Finally the woman also died.

[[v42-20-33]]

^<<v42-20-33,33>>^ Consequently, in the resurrection, whose wife will she become? For the seven had her as a wife.”

[[v42-20-34]]

^<<v42-20-34,34>>^ Jesus said to them: “The children of this system of things^&#42;1^ marry and are given in marriage,

[NOTE]
====
. Or “this age.” See Glossary.
====

[[v42-20-35]]

^<<v42-20-35,35>>^ but those who have been counted worthy of gaining that system of things and the resurrection from the dead neither marry nor are given in marriage.

[[v42-20-36]]

^<<v42-20-36,36>>^ In fact, neither can they die anymore, for they are like the angels, and they are God’s children by being children of the resurrection.

[[v42-20-37]]

^<<v42-20-37,37>>^ But that the dead are raised up, even Moses made known in the account about the thornbush, when he calls Jehovah^&#42;1^ ‘the God of Abraham and God of Isaac and God of Jacob.’

[NOTE]
====
. See App. A5.
====

[[v42-20-38]]

^<<v42-20-38,38>>^ He is a God, not of the dead, but of the living, for they are all living to him.”^&#42;1^

[NOTE]
====
. Or “from his standpoint.”
====

[[v42-20-39]]

^<<v42-20-39,39>>^ In response some of the scribes said: “Teacher, you spoke well.”

[[v42-20-40]]

^<<v42-20-40,40>>^ For they no longer had the courage to ask him a single question.

[[v42-20-41]]

^<<v42-20-41,41>>^ In turn he asked them: “How is it they say that the Christ is David’s son?

[[v42-20-42]]

^<<v42-20-42,42>>^ For David himself says in the book of Psalms, ‘Jehovah^&#42;1^ said to my Lord: “Sit at my right hand

[NOTE]
====
. See App. A5.
====

[[v42-20-43]]

^<<v42-20-43,43>>^ until I place your enemies as a stool for your feet.”’

[[v42-20-44]]

^<<v42-20-44,44>>^ David, therefore, calls him Lord; so how is he his son?”

[[v42-20-45]]

^<<v42-20-45,45>>^ Then, while all the people were listening, he said to his disciples:

[[v42-20-46]]

^<<v42-20-46,46>>^ “Beware of the scribes who like to walk around in robes and who love greetings in the marketplaces and front^&#42;1^ seats in the synagogues and the most prominent places at evening meals,

[NOTE]
====
. Or “best.”
====

[[v42-20-47]]

^<<v42-20-47,47>>^ and who devour the houses^&#42;1^ of the widows and for show^&#42;2^ make long prayers. These will receive a more severe^&#42;3^ judgment.”

[NOTE]
====
. Or “property.”
. Or “for a pretext.”
. Or “a heavier.”
====

'''

xref:042-luke/042-luke-019.adoc#v42-19-0[&#60; Capítulo Anterior] | <<v42-20-0,Topo>> | xref:042-luke/042-luke-021.adoc#v42-21-0[Próximo Capítulo &#62;]