include::./index.adoc[]

[[v42-2-0]]
=== According to Luke, 2
// nwt 2013, nwt - New World Translation of the Holy Scriptures

[[v42-2-1]]

^<<v42-2-1,1>>^ Now in those days a decree went out from Caesar Au·gusʹtus for all the inhabited earth to be registered.

[[v42-2-2]]

^<<v42-2-2,2>>^ (This first registration took place when Qui·rinʹi·us was governor of Syria.)

[[v42-2-3]]

^<<v42-2-3,3>>^ And all the people went to be registered, each one to his own city.

[[v42-2-4]]

^<<v42-2-4,4>>^ Of course, Joseph also went up from Galʹi·lee, from the city of Nazʹa·reth, into Ju·deʹa, to David’s city, which is called Bethʹle·hem, because of his being a member of the house and family of David.

[[v42-2-5]]

^<<v42-2-5,5>>^ He went to get registered with Mary, who had been given him in marriage as promised and who was soon to give birth.

[[v42-2-6]]

^<<v42-2-6,6>>^ While they were there, the time came for her to give birth.

[[v42-2-7]]

^<<v42-2-7,7>>^ And she gave birth to her son, the firstborn, and she wrapped him in strips of cloth and laid him in a manger, because there was no room for them in the lodging place.

[[v42-2-8]]

^<<v42-2-8,8>>^ There were also in the same region shepherds living out of doors and keeping watch in the night over their flocks.

[[v42-2-9]]

^<<v42-2-9,9>>^ Suddenly Jehovah’s^&#42;1^ angel stood before them, and Jehovah’s^&#42;2^ glory gleamed around them, and they became very fearful.

[NOTE]
====
. See App. A5.
. See App. A5.
====

[[v42-2-10]]

^<<v42-2-10,10>>^ But the angel said to them: “Do not be afraid, for look! I am declaring to you good news of a great joy that all the people will have.

[[v42-2-11]]

^<<v42-2-11,11>>^ For today there was born to you in David’s city a savior, who is Christ the Lord.

[[v42-2-12]]

^<<v42-2-12,12>>^ And this is a sign for you: You will find an infant wrapped in strips of cloth and lying in a manger.”

[[v42-2-13]]

^<<v42-2-13,13>>^ Suddenly there was with the angel a multitude of the heavenly army, praising God and saying:

[[v42-2-14]]

^<<v42-2-14,14>>^ “Glory in the heights above to God, and on earth peace among men of goodwill.”^&#42;1^

[NOTE]
====
. Or “people whom he approves.”
====

[[v42-2-15]]

^<<v42-2-15,15>>^ So when the angels had departed from them into heaven, the shepherds began saying to one another: “Let us by all means go over to Bethʹle·hem and see what has taken place, which Jehovah^&#42;1^ has made known to us.”

[NOTE]
====
. See App. A5.
====

[[v42-2-16]]

^<<v42-2-16,16>>^ And they went quickly and found Mary as well as Joseph, and the infant lying in the manger.

[[v42-2-17]]

^<<v42-2-17,17>>^ When they saw this, they made known the message that they had been told concerning this young child.

[[v42-2-18]]

^<<v42-2-18,18>>^ And all who heard were astonished at what the shepherds told them,

[[v42-2-19]]

^<<v42-2-19,19>>^ but Mary began to preserve all these sayings, drawing conclusions in her heart.

[[v42-2-20]]

^<<v42-2-20,20>>^ Then the shepherds went back, glorifying and praising God for all they had heard and seen, just as it had been told to them.

[[v42-2-21]]

^<<v42-2-21,21>>^ After eight days, when it was time to circumcise him, he was named Jesus, the name given by the angel before he was conceived.

[[v42-2-22]]

^<<v42-2-22,22>>^ Also, when the time came for purifying them according to the Law of Moses, they brought him up to Jerusalem to present him to Jehovah,^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v42-2-23]]

^<<v42-2-23,23>>^ just as it is written in Jehovah’s^&#42;1^ Law: “Every firstborn male^&#42;2^ must be called holy to Jehovah.”^&#42;3^

[NOTE]
====
. See App. A5.
. Lit., “Every male opening the womb.”
. See App. A5.
====

[[v42-2-24]]

^<<v42-2-24,24>>^ And they offered a sacrifice according to what is said in the Law of Jehovah:^&#42;1^ “a pair of turtledoves or two young pigeons.”

[NOTE]
====
. See App. A5.
====

[[v42-2-25]]

^<<v42-2-25,25>>^ And look! there was a man in Jerusalem named Simʹe·on, and this man was righteous and devout, waiting for Israel’s consolation, and holy spirit was upon him.

[[v42-2-26]]

^<<v42-2-26,26>>^ Furthermore, it had been divinely revealed to him by the holy spirit that he would not see death before he had seen the Christ of Jehovah.^&#42;1^

[NOTE]
====
. See App. A5.
====

[[v42-2-27]]

^<<v42-2-27,27>>^ Under the power of the spirit, he now came into the temple, and as the parents brought the young child Jesus in to do for him according to the customary practice of the Law,

[[v42-2-28]]

^<<v42-2-28,28>>^ he took the child into his arms and praised God and said:

[[v42-2-29]]

^<<v42-2-29,29>>^ “Now, Sovereign Lord, you are letting your slave go in peace according to your declaration,

[[v42-2-30]]

^<<v42-2-30,30>>^ because my eyes have seen your means of salvation

[[v42-2-31]]

^<<v42-2-31,31>>^ that you have prepared in the sight of all the peoples,

[[v42-2-32]]

^<<v42-2-32,32>>^ a light for removing the veil from the nations and a glory of your people Israel.”

[[v42-2-33]]

^<<v42-2-33,33>>^ And the child’s father and mother continued wondering at the things being spoken about him.

[[v42-2-34]]

^<<v42-2-34,34>>^ Also, Simʹe·on blessed them and said to Mary, the child’s mother: “Look! This child is appointed for the falling and the rising again of many in Israel and for a sign to be spoken against

[[v42-2-35]]

^<<v42-2-35,35>>^ (yes, a long sword will be run through you^&#42;1^), in order that the reasonings of many hearts may be revealed.”

[NOTE]
====
. Or “your own soul.”
====

[[v42-2-36]]

^<<v42-2-36,36>>^ Now there was a prophetess, Anna the daughter of Phanʹu·el, of Ashʹer’s tribe. This woman was well along in years and had lived with her husband for seven years after they were married,^&#42;1^

[NOTE]
====
. Lit., “from her virginity.”
====

[[v42-2-37]]

^<<v42-2-37,37>>^ and she was a widow now 84 years old. She was never missing from the temple, rendering sacred service night and day with fasting and supplications.

[[v42-2-38]]

^<<v42-2-38,38>>^ In that very hour she came near and began giving thanks to God and speaking about the child to all who were waiting for Jerusalem’s deliverance.

[[v42-2-39]]

^<<v42-2-39,39>>^ So when they had carried out all the things according to the Law of Jehovah,^&#42;1^ they went back into Galʹi·lee to their own city, Nazʹa·reth.

[NOTE]
====
. See App. A5.
====

[[v42-2-40]]

^<<v42-2-40,40>>^ And the young child continued growing and getting strong, being filled with wisdom, and God’s favor continued upon him.

[[v42-2-41]]

^<<v42-2-41,41>>^ Now his parents were accustomed to go from year to year to Jerusalem for the festival of the Passover.

[[v42-2-42]]

^<<v42-2-42,42>>^ And when he was 12 years old, they went up according to the custom of the festival.

[[v42-2-43]]

^<<v42-2-43,43>>^ When the days of the festival were over and they were returning, the boy Jesus remained behind in Jerusalem, and his parents did not notice it.

[[v42-2-44]]

^<<v42-2-44,44>>^ Assuming that he was in the group traveling together, they went a day’s journey and then began to search for him among the relatives and acquaintances.

[[v42-2-45]]

^<<v42-2-45,45>>^ But not finding him, they returned to Jerusalem and made a diligent search for him.

[[v42-2-46]]

^<<v42-2-46,46>>^ Well, after three days they found him in the temple, sitting in the midst of the teachers and listening to them and asking them questions.

[[v42-2-47]]

^<<v42-2-47,47>>^ But all those listening to him were in constant amazement at his understanding and his answers.

[[v42-2-48]]

^<<v42-2-48,48>>^ Now when his parents saw him, they were astounded, and his mother said to him: “Child, why did you treat us this way? Here your father and I have been frantically looking for you.”

[[v42-2-49]]

^<<v42-2-49,49>>^ But he said to them: “Why were you looking for me? Did you not know that I must be in the house of my Father?”

[[v42-2-50]]

^<<v42-2-50,50>>^ However, they did not understand what he was saying to them.

[[v42-2-51]]

^<<v42-2-51,51>>^ Then he went down with them and returned to Nazʹa·reth, and he continued subject^&#42;1^ to them. Also, his mother carefully kept all these sayings in her heart.

[NOTE]
====
. Or “remained obedient.”
====

[[v42-2-52]]

^<<v42-2-52,52>>^ And Jesus went on progressing in wisdom and in physical growth and in favor with God and men.

'''

xref:042-luke/042-luke-001.adoc#v42-1-0[&#60; Capítulo Anterior] | <<v42-2-0,Topo>> | xref:042-luke/042-luke-003.adoc#v42-3-0[Próximo Capítulo &#62;]